### DISCUSSION TITLE
localErrorHandlerData.handle is not a function in serverless offline mode

### DISCUSSION THREAD

**Discussion by AhmedRah** [serverless/serverless#10029] [Q&A] [answered]
- [ ] Are you certain it's a bug?
 Not sure , might be my configuration
- [ ] Is the issue caused by a plugin?
 It is not a plugin issue, getting this error both on serverless offline and when deploying
- [ ] Are you using the latest version?
 No using v2.58.0 but tried it on 2.60.0 and getting same error
- [ ] Is there an existing issue for this?
 I have searched existing issues, it hasn't been reported yet
- [ ] Issue description
Getting the following error when making a get request to trigger my handler
```
/usr/lib/node_modules/serverless/node_modules/essentials/index.js:12
                throw reason;
                ^

TypeError: localErrorHandlerData.handle is not a function
    at module.exports (/usr/lib/node_modules/serverless/lib/cli/handle-error.js:108:29)
    at process.<anonymous> (/usr/lib/node_modules/serverless/scripts/serverless.js:51:3)
    at Object.onceWrapper (node:events:510:26)
    at process.emit (node:events:402:35)
    at process.emit (node:domain:475:12)
    at process._fatalException (node:internal/process/execution:170:25)
```

### Service configuration (serverless.yml) content
```
# serverless.yml

service: service-name
custom:
  s3Bucket: bucket-name
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  region: us-east-1
  versionFunctions: false
  layers:
    # Google Chrome for AWS Lambda as a layer
  runtime: nodejs14.x
  memorySize: 2048
  # timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
  environment:
      # Bunch of API keys

functions:
  setup:
    handler: src/handler.setup
    events:
      - http:
          path: setup
          method: get
          integration: lambda
  newOrder:
    handler: src/handler.newOrder
    events:
      - http:
          path: newOrder
          method: post
          integration: lambda

resources:
  Resources:
    pdfsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: ${self:custom.s3Bucket}
        AccessControl: Private
    # Grant public read-only access to the bucket
    pdfsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Principal: "*"
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
        Bucket:
          Ref: bucket-ref

plugins:
  - serverless-offline
```

### Command name and used flags
serverless deploy 
serverless offline start

### Command output
```

offline: GET /setup (λ: setup)
/usr/lib/node_modules/serverless/node_modules/essentials/index.js:12
                throw reason;
                ^

TypeError: localErrorHandlerData.handle is not a function
    at module.exports (/usr/lib/node_modules/serverless/lib/cli/handle-error.js:108:29)
    at process.<anonymous> (/usr/lib/node_modules/serverless/scripts/serverless.js:51:3)
    at Object.onceWrapper (node:events:510:26)
    at process.emit (node:events:402:35)
    at process.emit (node:domain:475:12)
    at process._fatalException (node:internal/process/execution:170:25)
```
### Environment information
```
  "dependencies": {
    "chrome-aws-lambda": "^10.1.0",
    "puppeteer-core": "^10.4.0",
    "serverless": "^2.58.0",
    "serverless-offline": "^8.2.0",
  }
```
