### DISCUSSION TITLE
resourcePolicy not applying to deployed lambda function

### DISCUSSION THREAD

**Discussion by chris-hinds** [serverless/serverless#10031] [General]
I am trying to apply a resourcePolicy to my custom authoriser lambda, so that my HTTP API can invoke the authoriser lambda.

This is my provider setup for the lambda;

```
provider:
  name: aws
  region: ${file(../commonServerlessConfig.yml):region}
  stackName: XXXX-api-authoriser
  runtime: ${file(../commonServerlessConfig.yml):runtime}
  memorySize: ${file(../commonServerlessConfig.yml):memorySize}
  timeout: ${file(../commonServerlessConfig.yml):timeout}
  versionFunctions: ${file(../commonServerlessConfig.yml):versionFunctions}
  httpApi: ${file(../commonServerlessConfig.yml):httpApi}
  resourcePolicy:
    - Effect: Allow
      Action: lambda:InvokeFunction
      Principal:
        Service: apigateway.amazonaws.com
      Resource:
        - arn:aws:lambda:eu-west-1:XXXXXXX:function:apiAuthoriser
      Condition:
        ArnLike:
          AWS:SourceArn: arn:aws:execute-api:eu-west-1:XXXXXX:XXXXXX/authorizers/XXXX
```

When the lambda is deployed there is no attached resourcePolicy. The serverless generated cloud formation includes the resource policy;

```
"versionFunctions": false,
      "httpApi": {
        "id": {
          "Fn::ImportValue": "XXXXHTTPApiGW-HTTPApiId"
        }
      },
      "resourcePolicy": [
        {
          "Effect": "Allow",
          "Action": [
            "lambda:InvokeFunction"
          ],
          "Principal": {
            "Service": [
              "apigateway.amazonaws.com"
            ]
          },
          "Resource": "arn:aws:lambda:eu-west-1:XXXXX:function:apiAuthoriser",
          "Condition": {
            "ArnLike": {
              "AWS:SourceArn": "arn:aws:execute-api:eu-west-1:XXXXXX:XXXXXX/authorizers/XXXX"
            }
          }
        }
      ],
      "stage": "dev",
```

**Comment by pgrzesik** [comment]
Hello @chris-hinds :wave: Could you please share a little bit more information about your config? Maybe a small reproducible example? What is shown in the second snippet? It doesn't look like the compiled CloudFormation template. 

Btw - `resourcePolicy` is applied only for `apiGateway/http` event type, it does not work for `httpApi` events

**Reply by chris-hinds** [reply]
Oops, I shared the serverless-state.json snippet 🤦‍♂️  I am adding this policy in the wrong place then? This authoriser lambda is in its own stack, the http API Gateway and authoriser are in another stack.

**Reply by chris-hinds** [reply]
If I go to the console, and edit this lambda I can manually add a resource policy allowing my api gateway to invoke this lambda, and then everything works as expected.

**Reply by chris-hinds** [reply]
tldr of my stack setup.

**Stack A:**
- Api gateway
- Api gateway custom authoriser with `REQUEST` type

**Stack B:**
- Authroiser Lambda
- This is where I am trying to include a resource policy to allow API GW to invoke this lambda

**Stack C:**
- Lambda API functions with httpApi events, using shared API GW from Stack A

**Comment by pgrzesik** [comment]
How are you referencing that Authorizer Lambda in Stack A? When configuring the authorizer, proper `AWS::Lambda:Permission` should be created to allow invocation of authorizer from API GW.

**Reply by chris-hinds** [reply]
Stack A: Custom Authoriser

```
PhoenixHTTPApiGWAuthorizer:
      Type: "AWS::ApiGatewayV2::Authorizer"
      Properties:
        Name: XXXXXHTTPApiGWAuthorizer
        ApiId: !Ref XXXXXHTTPApiGW
        AuthorizerType: REQUEST
        AuthorizerPayloadFormatVersion: "2.0"
        EnableSimpleResponses: true
        AuthorizerResultTtlInSeconds: 0
        AuthorizerUri:
          Fn::Sub:
            - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthoriserLambdaArn}/invocations"
            - AuthoriserLambdaArn:
                Fn::ImportValue: XXXXHTTPApiGW-HTTPApiAuthoriserArn
        IdentitySource:
          - $request.header.Authorization
```
