### DISCUSSION TITLE
AWS::Cognito::UserPool Not Setting Up Email Verification Code

### DISCUSSION THREAD

**Discussion by Borduhh** [serverless/serverless#10048] [Q&A] [answered]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When adding the following options to `AWS::Cognito::UserPool:

```
VerificationMessageTemplate:
    DefaultEmailOption: CONFIRM_WITH_CODE
```

I expect the UserPool to be set up with email verification (see below):

![Screen Shot 2021-10-01 at 3 21 28 PM](https://user-images.githubusercontent.com/4759596/135675932-0ee41673-1824-446c-986e-a2dc8647d2d1.png)

However, the UserPool is set up with no verification.

### Service configuration (serverless.yml) content

```yaml
resources:
  Resources:
    DriversUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:app}-${self:service}-${self:custom.stage}
        UsernameAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: false        
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: False
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireUppercase: true
            RequireSymbols: false
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE

    DriversUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: emp-mobile-app
        UserPoolId:
          Ref: DriversUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        AccessTokenValidity: 10
        IdTokenValidity: 10
        RefreshTokenValidity: 180
        TokenValidityUnits:
          AccessToken: minutes
          IdToken: minutes
          RefreshToken: days

    DriversIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        AllowUnauthenticatedIdentities: False
        IdentityPoolName: ${self:app}-${self:service}-identity-${self:custom.stage}
        CognitoIdentityProviders:
          - ClientId:
              Ref: DriversUserPoolClient
            ProviderName:
              Fn::GetAtt: [DriversUserPool, ProviderName]
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.60.0 (local)
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.1
```
