### DISCUSSION TITLE
Lambda with Layer using arm64 architecture is throwing error during deployment

### DISCUSSION THREAD

**Discussion by dnalborczyk** [serverless/serverless#10061] [Q&A] [answered]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

when a Lambda (provider arch: **arm64**) is being deployed referencing a layer (compat arch: **arm64**, with a custom runtime), an error is being thrown during deployment.

> Serverless Error ----------------------------------------
>  
>   An error occurred: InventoryLambdaFunction - Resource handler returned message: "Runtime provided does not support the following architectures [arm64]. Please select different architectures from [x86_64, arm64] or select a different runtime. (Service: Lambda, Status Code: 400, Request ID: ..., Extended Request ID: null)" (RequestToken: ..., HandlerErrorCode: InvalidRequest).

Interestingly when **x86_64** is being specified, either by default or explicitly, it works.

I think this error is being thrown by AWS/Cloudformation and not by serverless, as Graviton arm64 architecture support is also fairly new and possibly still a bit buggy.

just wanted to mention this in case serverless applies incorrect values to the template, although it doesn't appear that way as far as I can tell.

### Service configuration (serverless.yml) content

```yaml
provider:
  architecture: arm64
  runtime: provided

layers:
  NodeCustomRuntime:
    compatibleArchitectures: arm64
    package:
      artifact: ./node-custom-runtime.zip

functions:
  inventory:
    events:
      - http:
          method: POST
          path: /inventory
    handler: inventory/src/index.default
    layers:
      - { Ref: NodeCustomRuntimeLambdaLayer }
```

### Command name and used flags

n/a

### Command output

```shell
n/a
```

### Environment information

```shell
Framework Core: 2.61.0 (local)
Plugin: 5.4.5
SDK: 4.3.0
Components: 3.17.1
```
