### DISCUSSION TITLE
StackPolicy not supporting LogicalResourceId in property Resource

### DISCUSSION THREAD

**Discussion by jmonsma** [serverless/serverless#10095] [Q&A] [answered]
Hi,

Since serverless 2.x.x, I'm receiving warnings about the stack policy has an unsupported value in the Resource property.
I have tried to get rid of this warning in multiple ways, but yet unsuccessful.

The warning: 
`Serverless:   at 'provider.stackPolicy[1].Resource[0]': unsupported value`.

According cloudformation the stack policy listed below should be correct:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html#stack-policy-reference

I even tried changing the Resource value to `["LogicalResourceId/DynamoDBUsersTable"]`, but still the warning holds.
I couldn't find any changes in the changelogs that made impact to this.
Does someone have any insights how to solve this warning?
I started noticing this warning around version 2.8.0 and still holds up to the latest version 2.62.0

The stackPolicy and its resource:
```
stackPolicy:
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
    - Effect: Deny
      Principal: "*"
      Action: ["Update:Replace", "Update:Delete"]
      Resource: LogicalResourceId/DynamoDBUsersTable

resources:
  Resources:
    DynamoDBUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rs5-${self:provider.stage}-executions

```
