### DISCUSSION TITLE
Get "MODULE_NOT_FOUND"

### DISCUSSION THREAD

**Discussion by wahlforss** [serverless/serverless#10110] [Q&A]
I get "MODULE_NOT_FOUND" when using aws lambda and node with npm. Any ideas?

**Comment by medikoo** [comment]
@wahlforss `MODULE_NOT_FOUND` simply happens when you try to require a module that's not in a file system, and it's hard to say more having information you provided.

**Comment by wahlforss** [comment]
@medikoo I am requiring "firebase" for example as an npm module.

**Comment by medikoo** [comment]
> @medikoo I am requiring "firebase" for example as an npm module.

Is `firebase` listed in `dependencies` or`devDependencies`? If it's the latter then that's source of an issue, by default dev dependencies are not bundled

**Comment by wahlforss** [comment]
@medikoo listed in `dependencies`

**Comment by wahlforss** [comment]
Now it is asking for:

1b7ab9b-c9d4-4c4d-a30c-5707fdc4cb13	ERROR	Invoke Error	{
    "errorType": "Error",
    "errorMessage": "Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v64-linux-x64-glibc\nFound: [node-v64-darwin-x64-unknown]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'",
    "code": "MODULE_NOT_FOUND",
    "stack": [
        "Error: Failed to load gRPC binary module because it was not installed for the current system",
        "Expected directory: node-v64-linux-x64-glibc",
        "Found: [node-v64-darwin-x64-unknown]",
        "This problem can often be fixed by running \"npm rebuild\" on the current system",
        "Original error: Cannot find module '/var/task/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'",
        "    at Object.<anonymous> (/var/task/node_modules/grpc/src/grpc_extension.js:53:17)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)",
        "    at Module._require.o.require (/var/task/serverless_sdk/index.js:9:76736)",
        "    at require (internal/modules/cjs/helpers.js:25:18)",
        "    at Object.<anonymous> (/var/task/node_modules/grpc/src/client_interceptors.js:144:12)"
    ]

**Comment by medikoo** [comment]
It appears that your project (or one of its dependencies) depends on [grpc](https://www.npmjs.com/package/grpc) which is a C++ module that require compilation for given environment

We currently do not support packaging of C++ node modules. See more info at: https://github.com/serverless/serverless/issues/308#issuecomment-242087480

**Comment by wahlforss** [comment]
@medikoo but my only dependency is firebase?

**Comment by feryardiant** [comment]
Come across the same issue and have no clue what's going on.

```
Error: Cannot find module '../../dialects/postgres/index.js'
Require stack:
- D:\Path\To\Project\backend\.esbuild\.build\main.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\handler-runner\in-process-runner\InProcessRunner.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\handler-runner\in-process-runner\index.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\handler-runner\HandlerRunner.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\handler-runner\index.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\LambdaFunction.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\LambdaFunctionPool.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\Lambda.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\index.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\ServerlessOffline.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\index.js
- D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\main.js
- D:\Path\To\Project\node_modules\.pnpm\serverless@2.62.0\node_modules\serverless\lib\classes\PluginManager.js
- D:\Path\To\Project\node_modules\.pnpm\serverless@2.62.0\node_modules\serverless\lib\Serverless.js
- D:\Path\To\Project\node_modules\.pnpm\serverless@2.62.0\node_modules\serverless\scripts\serverless.js
- D:\Path\To\Project\node_modules\.pnpm\serverless@2.62.0\node_modules\serverless\bin\serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at BH (D:\Path\To\Project\backend\.esbuild\.build\main.js:52:5770)
    at wa (D:\Path\To\Project\backend\.esbuild\.build\main.js:52:6146)
    at GH (D:\Path\To\Project\backend\.esbuild\.build\main.js:56:59524)
    at Object.<anonymous> (D:\Path\To\Project\backend\.esbuild\.build\main.js:56:59832)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\handler-runner\in-process-runner\InProcessRunner.js:157:133
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async InProcessRunner.run (D:\Path\To\Project\node_modules\.pnpm\serverless-offline@8.2.0_serverless@2.62.0\node_modules\serverless-offline\dist\lambda\handler-runner\in-process-runner\InProcessRunner.js:157:9)
```

Here's my `package.json` file
```json
{
  "dependencies": {
    "aws-sdk": "^2.1008.0",
    "chance": "^1.1.8",
    "dotenv": "^10.0.0",
    "knex": "^0.95.11",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "pg": "^8.7.1",
    "qs": "^6.10.1",
    "redis": "^3.1.2"
  },
  "devDependencies": {
    "serverless-esbuild": "^1.20.0",
    "serverless-offline": "^8.2.0"
  }
}
```

And here's my `serverless.yml` file
```yml
plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    minify: true
    watch:
      # anymatch-compatible definition (https://github.com/es128/anymatch)
      pattern: ['./main.js', '(lib|functions)/**/*.js'] # default .
      ignore: [.build, 'dist', 'node_modules', '.serverless']
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs14.x
  stage: staging
  tracing:
    apiGateway: true
    lambda: true
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
```

Any helps appreciated

**Comment by feryardiant** [comment]
Spending some hours to workaround the issue and it's solved by replacing `serverless-esbuild` with `serverless-bundle` and update my `serverless.yml` file with the following

```yml
plugins:
  - serverless-bundle
  # - serverless-esbuild
  - serverless-offline

custom:
  bundle:
    esbuild: true
    forceInclude:
      - pg
    ignorePackages:
      - pg-native
      - hiredis
    externals:
      - knex
      - qs
      - redis
  # esbuild:
  #   minify: true
  #   watch:
  #     # anymatch-compatible definition (https://github.com/es128/anymatch)
  #     pattern: ['./main.js', '(lib|functions)/**/*.js'] # default .
  #     ignore: [.build, 'dist', 'node_modules', '.serverless']
  serverless-offline:
    httpPort: 3001
```

Not sure if it was actually `serverless-esbuild`'s issue, though
