### DISCUSSION TITLE
CognitoUserPoolDomain Not being deleted when UserPool has been deleted

### DISCUSSION THREAD

**Discussion by kyeljmd** [serverless/serverless#10136] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Cognito User Pool Domain not being deleted when we sls remove.

When I did the following steps

1. sls deploy -s dev

it works as expected. The Cognito Domain name I have is kyeljmdmyproject0001-dev 

then id decided to remove my stack with

2. sls remove -s dev

all of the stack gets deleted. now when I run this command

3. sls deploy -s dev 

Using the same domain name, I get this error

`Serverless: Operation failed!
Serverless: View the full error output: https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A127598142473%3Astack%2Fcognito-dev%2Ffb87a1a0-3346-11ec-887f-0238336d1d20

 Serverless Error ----------------------------------------

  ServerlessError: An error occurred: CognitoUserPoolDomain - Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 141f64af-60ff-492a-93e3-98aadc2322f6; Proxy: null).`

### Service configuration (serverless.yml) content

```yaml
service: cognito

frameworkVersion: "2"

disabledDeprecations:
  - CLI_OPTIONS_SCHEMA
  - NEW_VARIABLES_RESOLVER

plugins:
  - serverless-seed

provider:
  name: aws
  runtime: nodejs14.x
  region: ${self:custom.common.resourcesRegion}
  stage: dev
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221
  versionFunctions: false
  memorySize: ${self:custom.common.memSize.${self:custom.common.stage}}
  tracing:
    lambda: true
  environment:
    STAGE: ${self:custom.common.stage}
    AWSREGION: ${self:provider.region}
  iam:
    role:
      statements:
        - ${file(../../../serverless.common.yml):lambdaPolicyXRay}

custom:
  common: ${file(../../../serverless.common.yml):custom}
  seed:
    incremental:
      enabled: true
      disabledFor:
        - prod

package:
  individually: true
  patterns:
    - "!package-lock.json"
    - "!yarn.lock"

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: ${self:custom.common.projectName}-${self:custom.common.stage}
        # AliasAttributes:
        #   - preferred_username
        #   - email
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
          # EmailSendingAccount: DEVELOPER
          # From: "myProject<${ssm:FROM}>"
          # SourceArn:
          #   Fn::Join:
          #     - ""
          #     - - "arn:aws:ses:us-west-2"
          #       # - Ref: AWS::Region
          #       - ":"
          #       - Ref: AWS::AccountId
          #       - ":"
          #       - "identity/"
          #       - ${ssm:FROM}
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            RequireUppercase: false
        # VerificationMessageTemplate:
        #   DefaultEmailOption: CONFIRM_WITH_LINK
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
            StringAttributeConstraints:
              MaxLength: 100
            # NumberAttributeConstraints: NumberAttributeConstraints
            # StringAttributeConstraints: StringAttributeConstraints
          - Name: preferred_username
            AttributeDataType: String
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MaxLength: 100
          - Name: phone_number
            AttributeDataType: String
            Mutable: true
            Required: false
            NumberAttributeConstraints:
              MinValue: 20
          - Name: family_name
            AttributeDataType: String
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MaxLength: 50
          - Name: given_name
            AttributeDataType: String
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MaxLength: 50
          - Name: updated_at
            AttributeDataType: Number
            Mutable: true
            Required: false
            NumberAttributeConstraints:
              MinValue: 0
          - Name: created_at
            AttributeDataType: Number
            Mutable: false
            Required: false
            NumberAttributeConstraints:
              MinValue: 0
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: ${self:custom.common.projectName}-${self:custom..common.stage}
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
        ReadAttributes:
          - preferred_username
          - email
          - phone_number
          - family_name
          - given_name
          - updated_at
          - custom:created_at
        WriteAttributes:
          - preferred_username
          - email
          - phone_number
          - family_name
          - given_name
          - updated_at
          - custom:created_at
    CognitoUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: ${self:custom.common.projectName}-${self:custom.common.stage}
        UserPoolId:
          Ref: CognitoUserPool
    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        # Generate a name based on the stage
        IdentityPoolName: ${self:custom.common.projectName}-${self:custom.common.stage}
        # Don't allow unathenticated users
        AllowUnauthenticatedIdentities: false
        # Link to our User Pool
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClient
            ProviderName:
              Fn::GetAtt: ["CognitoUserPool", "ProviderName"]
    # IAM roles
    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [CognitoAuthRole, Arn]
    # IAM role used for authenticated users
    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud":
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": authenticated
        Policies:
          - PolicyName: "CognitoAuthorizedPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "mobileanalytics:PutEvents"
                    - "cognito-sync:*"
                    - "cognito-identity:*"
                  Resource: "*"
                # Allow users to upload attachments to their
                # folder inside our S3 bucket
                - Effect: "Allow"
                  Action:
                    - "s3:*"
                  Resource: ${cf:storage-${self:custom.common.stage}.BucketArn}

  # Print out the Id of the User Pool that is created
  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool
      Export:
        Name: UserPoolId-${self:custom.common.stage}

    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient

    CognitoUserPoolArn:
      Value:
        Fn::GetAtt:
          - CognitoUserPool
          - Arn
      Export:
        Name: CognitoUserPoolArn-${self:custom.common.stage}
    IdentityPoolId:
      Value:
        Ref: CognitoIdentityPool
    CognitoAuthRole:
      Value:
        Ref: CognitoAuthRole
      Export:
        Name: CognitoAuthRole-${self:custom.common.stage}
```

### Command name and used flags

sls deploy -s dev

### Command output

```shell
Serverless: Operation failed!
Serverless: View the full error output: https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A127598142473%3Astack%2Fcognito-dev%2Ffb87a1a0-3346-11ec-887f-0238336d1d20

 Serverless Error ----------------------------------------

  ServerlessError: An error occurred: CognitoUserPoolDomain - Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: 141f64af-60ff-492a-93e3-98aadc2322f6; Proxy: null).
```

### Environment information

```shell
Framework Core: 2.15.0 (local)
Plugin: 4.6.0
SDK: n/a
Components: 3.17.1
```
