### DISCUSSION TITLE
Using the $default path for API gateway

### DISCUSSION THREAD

**Discussion by liaocanada** [serverless/serverless#10162] [Q&A]
On the API Gateway console, I can specify a $default route for requests that don't match any other routes. 

How can I achieve this using serverless? When I try the following I get the error from serverless
> Invalid "method" property in function cors for httpApi event in serverless.yml

```yaml
  cors:
    handler: cors.handler
    events:
      - httpApi:
          path: $default
```

and when I try to workaround this by including a `method: options` I get an error from AWS
> HttpApiRouteOptionsdefault - The provided route key is not formatted properly for HTTP protocol. Format should be "[HTTP METHOD] /[RESOURCE PATH]" or "$default"
