### DISCUSSION TITLE
Are Kafka events supported?

### DISCUSSION THREAD

**Discussion by hukm** [serverless/serverless#10202] [Q&A] [answered]
Hello everyone, 

I need to add Kafka as an event for lambda function. Looking at the documentation [here](https://www.serverless.com/framework/docs/providers/aws/events/kafka), it seems that Kafka event is supported. However, when I am adding this example to my yaml file, it says 

`Configuration warning at 'functions.kafkaBookingConsumer.events[0]': unsupported function event`

Also I am not able to find `kafka` event [here](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml). So my question is if it supported at all? If so, where the problem might be? 

One last piece of information, previously I was running version 2.15, but I have just updated to 2.65 to have Kafka event available. 

Here is my speck 
```
Framework Core: 2.65.0 (standalone)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.17.2
```

**Comment by pgrzesik** [comment]
Yes, `kafka` events are supported. Are you sure you don't have a locally installed older version of serverless that is being used for your serivce?

**Reply by hukm** [reply]
I don't know how to check that during deploy. When I am doing `serverless -v` from the same folder from where I am doing deploy, it responds with version 2.65.0. And also `which serverless` is pointing to the executable updated yesterday (when I was doing upgrade from 2.15.0)

Btw, I first tried deploying this function with `kafka` event on the 2.15.0 version. Only later I realised that support for it was added in newer releases. Can something be cached because of that? Any hint will be appreciated.

**Reply by pgrzesik** [reply]
I don't think it should have anything to do with cache - are you able to share a simplified version of your service configuration?

**Reply by hukm** [reply]
Sure, here it is

```
service: serverlessiotcore
frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  stackName: ServerlessIotCore-${self:provider.stage}
  memorySize: 128
  timeout: 5
  versionFunctions: false
  role: arn:aws:iam::.......:role/ServerlessIoTCoreLambdaRole
  environment:
    STAGE: ${opt:stage, 'dev'}

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts

package:
  exclude:
    - node_modules/**
    - venv/**

custom:
  stage: ${opt:stage, self:provider.stage}
  ssm: ${ssm:/aws/reference/secretsmanager/ServerlessIoTCore/${opt:stage, self:provider.stage}}
  pythonRequirements:
    dockerizePip: non-linux
  dev:
    ..........
  prod:
    ..........

functions:
  kafkaBookingConsumer:
    handler: functions/kafkaBookingConsumer.lambda_handler
    timeout: 15
    name: KafkaBookingConsumer-${self:custom.stage}
    description: Receiving messages from Kafka
    role: arn:aws:iam::..........:role/MSKReadLambdaRole
    events:
      - kafka:
        accessConfigurations:
          saslScram512Auth: arn:aws:secretsmanager:eu-central-1:.........:secret:AmazonMSK_new_secret-uAEfEU
        topic: api_staging.public.all_bookings
        bootstrapServers:
          - b-1...........kafka.eu-central-1.amazonaws.com:9092
          - b-2...........kafka.eu-central-1.amazonaws.com:9092
```
