### DISCUSSION TITLE
Configuration warning: at 'functions.app.events[0]': unrecognized property 'cors'

### DISCUSSION THREAD

**Discussion by newbaluku** [serverless/serverless#10219] [Q&A]
after updating serverless version:
Framework Core: 2.41.2
Plugin: 5.0.0
SDK: 4.2.2
Components: 3.9.2

I get the following warning during sls deploy

Serverless: Configuration warning:
Serverless:   at 'functions.app.events[0]': unrecognized property 'cors'
Serverless:   at 'functions.app.events[1]': unrecognized property 'cors'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT

any idea how to fix this warning?

I have tried removing any references to cors in my code, not the warning is still there.

Any encountered this before?

**Comment by pgrzesik** [comment]
Hello @newbaluku - could you please share your configuration with sensitive parts masked? It's hard to help without more context.

**Reply by newbaluku** [reply]
Hi @pgrzesik. Thanks

I just realised this might be caused by the 'cors' specifications in these lines:

`
functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
        cors:
          origin: '*'
          headers:
            - Access-Control-Allow-Headers
            - Access-Control-Allow-Origin
            - Authorization
            - Content-Type
            - X-Amz-Date
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - X-Api-Key
      - http: 'ANY {proxy+}'
        cors:
          origin: '*'
          headers:
            - Access-Control-Allow-Headers
            - Access-Control-Allow-Origin
            - Authorization
            - Content-Type
            - X-Amz-Date
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - X-Api-Key
      - schedule:
          rate: rate(10 minutes)
          enabled: ${self:custom.ENABLE_WARMER.${self:custom.stage}}
          input:
            warmer: true
            concurrency: 1

`

I only see these warnings in this version of the serverless tool. Previous version is ok.

**Reply by pgrzesik** [reply]
Could you please format it so it's readable and is valid yaml?

**Reply by newbaluku** [reply]
so sorry, here is the screen capture. from a valid yml file.

![Screenshot 2021-11-10 at 6 40 46 PM](https://user-images.githubusercontent.com/13480257/141098593-d6ac024d-15f1-4bdb-8f7a-1eddc1d7efc6.png)

**Reply by pgrzesik** [reply]
It's an invalid configuration - you're using shorthand string syntax for `http` event definition and are trying to add extra property for cors - you need to use config like this
```
http:
  path: hello
  method: get
  cors: ...
```

**Reply by newbaluku** [reply]
the yml file, if you need to see the whole thing.
[my-serverless.yml.txt](https://github.com/serverless/serverless/files/7512028/my-serverless.yml.txt)

**Reply by newbaluku** [reply]
this is not allowed anymore? Because I'm using serverless-http wrapper. Is there a way to do this? using shorthand syntax but still able to add extra prop for cors?

**Reply by pgrzesik** [reply]
It was never allowed to use both shorthand syntax and additional properties because it's produces an invalid yaml configuration. You can just use the object notation as I've shown in the comment above

**Reply by newbaluku** [reply]
@pgrzesik does it mean anything specified under the cors property in this case does nothing, and serverless just simply ignore them when parsing through the yml?

**Reply by pgrzesik** [reply]
Yes, it is ignored, you need to use proper definition e.g. 

```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
```
