### DISCUSSION TITLE
Getting `got` error intermittently on SLS deploy

### DISCUSSION THREAD

**Discussion by pranavbadami** [serverless/serverless#10232] [Q&A] [answered]
Hey everyone! I'm getting a really strange, intermittent bug when I run `sls deploy` that states:
```
The `onCancel` handler was attached after the promise settled.
``` 

Here's the full stack trace: 
```
sls deploy function -f slackEvent --stage dev
Serverless: Configuration warning at 'functions.handleShortcut.events[0].http': unrecognized property 'allowCredentials'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging function: slackEvent...
Serverless: Excluding development dependencies...
 
 Error ---------------------------------------------------
 
  Error: The `onCancel` handler was attached after the promise settled.
      at onCancel (/usr/local/lib/node_modules/serverless/node_modules/got/node_modules/p-cancelable/index.js:48:12)
      at makeRequest (/usr/local/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/index.js:38:13)
      at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/index.js:143:17)
      at Object.onceWrapper (events.js:520:26)
      at Request.emit (events.js:400:28)
      at Request.emit (domain.js:475:12)
      at Timeout.retry (/usr/local/lib/node_modules/serverless/node_modules/got/dist/source/core/index.js:1264:30)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.18.1
     Framework Version:         2.66.0
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.17.2
 
```

After some initial searching, it seems that this is an issue with the [`got`](https://www.npmjs.com/package/got) package that serverless relies on, but I'm unable to resolve the issue by uninstalling and reinstalling serverless. Does anyone have any pointers on how I can resolve this? Thanks!

**Comment by pgrzesik** [comment]
Hello @pranavbadami - could you show your configuration here as well (with sensitive parts masked out)? Also, could you show the output with `SLS_DEBUG=*` enabled?

**Reply by pranavbadami** [reply]
Hey @pgrzesik , thanks for getting back to me here and so sorry for the late reply! Here's the config I have in `serverless.yml` (with the functions truncated): 
```
service: slack-internal
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  memorySize: 256
  profile: dots
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: Allow
      Action:
        - sqs:CreateQueue
        - sqs:DeleteMessage
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:ListQueues
        - sqs:GetQueueUrl
      Resource:
        - 'arn:aws:sqs:*:*:*'
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - ses:SendTemplatedEmail
      Resource: '*'
  environment:
    stage: ${opt:stage, self:provider.stage}

functions:
  batchFunction:
    handler: BatchFunction.handler
    timeout: 300
    maximumRetryAttempts: 0
    warmup:
      default:
        enabled: false

 ## OTHER FUNCTIONS TRUNCATED ##

plugins:
  - serverless-plugin-warmup
custom:
  warmup:
    default:
      enabled: true
      concurrency: 2
  ## set stage to either what was provided, or default to dev
  stage: '${opt:stage, self:provider.stage}'
  eventEnabled:
    prod: true
    dev: false
```

Also here's the output I see with the `SLS_DEBUG` env var set:
```
sls deploy --stage dev            
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.66.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command warmup
Serverless: Load command warmup:addWarmers
Serverless: Load command warmup:cleanupTempDir
Serverless: Load command warmup:prewarm
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke warmup:addWarmers
Serverless: WarmUp: Creating warmer "default" to warm up 2 functions:
Serverless:           * slack-internal-dev-otherFunction
Serverless:           * slack-internal-dev-otherFunction2
Serverless: WarmUp: Creating warmer "default" to warm up 2 functions:
Serverless:           * slack-internal-dev-otherFunction
Serverless:           * slack-internal-dev-otherFunction2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [AWS sts 200 1.141s 0 retries] getCallerIdentity({})
 
 Error ---------------------------------------------------
 
  Error: The `onCancel` handler was attached after the promise settled.
      at onCancel (/usr/local/lib/node_modules/serverless/node_modules/got/node_modules/p-cancelable/index.js:48:12)
      at makeRequest (/usr/local/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/index.js:38:13)
      at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/got/dist/source/as-promise/index.js:143:17)
      at Object.onceWrapper (events.js:520:26)
      at Request.emit (events.js:400:28)
      at Request.emit (domain.js:475:12)
      at Timeout.retry (/usr/local/lib/node_modules/serverless/node_modules/got/dist/source/core/index.js:1264:30)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.18.1
     Framework Version:         2.66.1
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.0
 
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221".
            While it is highly encouraged to upgrade to new algorithm, you can still use the old approach by setting "provider.lambdaHashingVersion" to "20200924".
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Excluding development dependencies...
```
