### DISCUSSION TITLE
S3 Unable to validate the following destination configurations

### DISCUSSION THREAD

**Discussion by lastdoctor** [serverless/serverless#10249] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a problem with the deployment, I create s3 with SNS resources and when I deploy them. I get  
```
 Serverless Error ----------------------------------------
 
  ServerlessError: An error occurred: S3SourceBucket - Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 6CYB6R5W6P0HJ0D9; S3 Extended Request ID: 8OsnUmHjxYCDUNYSNtGr/LARRbdzyvX5/YAIBcsWcJhPORId0pTfxenBOu21uyMXBUQUWfXZLEw=; Proxy: null).
      at /Users/admin/.nvm/versions/node/v14.18.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:143:23
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async AwsDeploy.update (/Users/admin/.nvm/versions/node/v14.18.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:146:5)
```

### Service configuration (serverless.yml) content

```yaml
service: ${file(./secrets.json):APP_NAME}

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  region: ${self:custom.REGION}
  versionFunctions: false
  stage: dev
  memorySize: 256
  timeout: 30
  lambdaHashingVersion: 20201221

custom:
  APP_NAME: ${file(./secrets.json):APP_NAME}
  REGION: ${file(./secrets.json):AWS_REGION_NAME}
  # S3
  S3_BUCKET_RESULT_NAME: ${self:custom.APP_NAME}-${self:provider.stage}-${file(./secrets.json):S3_BUCKET_RESULT}
  S3_BUCKET_SOURCE_NAME: ${self:custom.APP_NAME}-${self:provider.stage}-${file(./secrets.json):S3_BUCKET_SOURCE}
  # SNS
  SNS_TOPIC_UPLOAD_VIDEO: ${file(./secrets.json):SNS_TOPIC_UPLOAD_VIDEO}

  serverless-offline:
    noPrependStageInUrl: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

resources:
  Resources:
    SNSVideoUploadTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:custom.SNS_TOPIC_UPLOAD_VIDEO}
        TopicName: ${self:custom.SNS_TOPIC_UPLOAD_VIDEO}
    SNSVideoUploadTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      DependsOn: SNSVideoUploadTopic
      Properties:
        Topics:
          - !Ref SNSVideoUploadTopic
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'sns:Publish'
              Resource: !Ref SNSVideoUploadTopic
              Condition:
                ArnLike:
                  aws:SourceArn: !Sub "arn:aws:s3:::${S3SourceBucket}"
              Principal:
                Service: 's3.amazonaws.com'

    S3SourceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3_BUCKET_SOURCE_NAME}
        NotificationConfiguration:
          TopicConfigurations:
            - Event: 's3:ObjectCreated:*'
              Topic: !Ref SNSVideoUploadTopic
        LifecycleConfiguration:
          Rules:
            - Id: DeleteContentAfter1Day
              Status: 'Enabled'
              ExpirationInDays: 1
    S3ResultBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3_BUCKET_RESULT_NAME}

  Outputs:
    S3SourceBucketName:
      Value:
        Ref: S3SourceBucket
      Description: ARN of S3 bucket where the original videos are uploaded
    S3ResultBucketName:
      Value:
        Ref: S3ResultBucket
      Description: ARN of S3 bucket where the transcoded videos and metadata will be stored



variablesResolutionMode: 20210326
```

### Command name and used flags

SLS_DEBUG=*  sls deploy

### Command output

```shell
Serverless Error ----------------------------------------
 
  ServerlessError: An error occurred: S3SourceBucket - Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 6CYB6R5W6P0HJ0D9; S3 Extended Request ID: 8OsnUmHjxYCDUNYSNtGr/LARRbdzyvX5/YAIBcsWcJhPORId0pTfxenBOu21uyMXBUQUWfXZLEw=; Proxy: null).
      at /Users/admin/.nvm/versions/node/v14.18.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:143:23
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async AwsDeploy.update (/Users/admin/.nvm/versions/node/v14.18.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:146:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.18.1
     Framework Version:         2.64.1
     Plugin Version:            5.5.0
     SDK Version:               4.3.0
     Components Version:        3.17.1
```

### Environment information

```shell
Framework Core: 2.64.1
Plugin: 5.5.0
SDK: 4.3.0
Components: 3.17.1
```
