### DISCUSSION TITLE
load properties from a file

### DISCUSSION THREAD

**Discussion by katlim-br** [serverless/serverless#10258] [General]
Hi
I just want to know if it is possible to do this.

I have my serverless.yml as this:
```
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  logs:
    httpApi: true
  apiGateway:
    metrics: true
```

I want to load a file in the following way:
```
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  ${file(../common/prov-common.yml)}
```

which would contain the logs and apiGateway objects.

---
I know that I can do
```
  logs: ${file(../common/prov-common.yml):logs}
```
But I prefer the other way so it is more flexible.

Why?
Because I will have many sls services in a monorepo, and I want all to share part of the same config.

Thanks
