### DISCUSSION TITLE
Additional S3 Events Lambda not getting VPC assigned

### DISCUSSION THREAD

**Discussion by GlebKuzmich** [serverless/serverless#10269] [General]
Hey everyone,

Checked the issues section and could not really find something useful regarding the issue.

So we’re using S3 events with the following config:

```
functions:
  convert:
    handler: packages/lambda.handler
    package:
      patterns:
        - '!packages/**'
    memorySize: 1024
    timeout: 30
    events:
      - s3:
          bucket: nameOfTheBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: x/y/z
            - suffix: .png
          existing: true
```

Everything works just fine, but the only concern is that the additional Lambda function (nameOfTheFunction-custom-resource-existing-s3) gets created because of the `existing: true` option and it does not get VPC, Subnets and Security Groups assigned.

I believe there is no way how to suppress that additional Lambda function, as that’s the way how Serverless work, but is it possible to add some config to it, so it gets the same VPC, Subnets and SGs as the original Lambda function does? 

Not the end of the world, but can’t get AWS SecurityHub fully compliant, also seems to be a bit of a security concern to have Lambda without VPC things.

Best regards,

GK
