### DISCUSSION TITLE
deploymentRole not being assumed

### DISCUSSION THREAD

**Discussion by SophieHTenhaw** [serverless/serverless#10336] [Q&A]
I'm fairly new to serverless. I've created a project that I've managed to get deploying to AWS successfully, however I can't get it to work with the deploymentRole. It seems to deploy using the AWS user credentials I've set up in Environment Variables instead.

The version I'm using is 2.66.1 and here is the provider section of my serverless.yml

```
provider:
  name: aws
  runtime: nodejs14.x
  stackName: stack-name
  iam:
    role:
      name: role-name
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::${self:custom.bucket}/*"
    deploymentRole: arn:aws:iam::[AccountId]:role/[RoleName]
```
    
Does anyone know what I might be doing wrong? Or am I misunderstanding what deploymentRole does?
