### DISCUSSION TITLE
The Serverless version (1.83.3) does not satisfy the "frameworkVersion" (2) in serverless.yml

### DISCUSSION THREAD

**Discussion by DanielAizen** [serverless/serverless#10375] [Q&A]
Hey,

I encounter a problem and would appreciate your help:
I'm using Github actions for CI/CD and when I tried to deploy my service on the AWS It's showing me the error of the framework version.
The version that is currently in the serverless.yml is '2', as far as I can see the latest version for this (based on https://github.com/serverless/github-action) is v1.

this is what I currently have...

![CI_CD_yml](https://user-images.githubusercontent.com/84707942/146384443-4e815bc2-7d12-4f3c-9cd0-84faff09a000.png)

And this is what is shown when I'm trying to push into Github:
![CI_CD](https://user-images.githubusercontent.com/84707942/146383077-cf60a546-c0ef-4098-a45e-d22b5338ec7d.png)

Thank you!!

**Comment by mnapoli** [comment]
Hi,

You may have a `dependencies` to Serverless v1 in your package.json?

**Reply by DanielAizen** [reply]
Hello @mnapoli, no we don't have any dependencies, moreover, I have tried different variations of this command (`serverless/github-action@`), and only the one that "successfully" was uploaded didn't update on AWS.

**Comment by pgrzesik** [comment]
Hello @DanielAizen - you're specifically using `v1` version of the Github Action you need to use `serverless/github-action@master` instead of `serverless/github-action@v1` in your configuration, that should resolve the issue.

**Reply by DanielAizen** [reply]
Hello @pgrzesik, first of all, thank you for your help!
secondly before  switching to `v1` I've actually tried using that command (`serverless/github-action@master`) but when i checked for an update in AWS the new deployment didn't show up... have you got any clues on why this might happen?

**Reply by pgrzesik** [reply]
Hey @DanielAizen 👋 That's a bit weird - could you share the output of running the deployment in CI/CD? Was the service actually succesfully deployed based on CLI output? Maybe there was an error in the process?

**Reply by DanielAizen** [reply]
Hey @pgrzesik so here is the successful deployment where i used the syntax you have suggested `serverless/github-action@master`
(tell me if you can read the screenshot)
![successful_deployment](https://user-images.githubusercontent.com/84707942/146440700-59bf46bf-e924-434e-924a-eaa4fc868748.png)

**Reply by pgrzesik** [reply]
Thanks @DanielAizen - I can see the screenshot but I see that there are some lines hidden (3-8), could you include them too? Based on the output above it's hard to validate what really happened.

**Reply by DanielAizen** [reply]
@pgrzesik Actually there is nothing special there, for your convenience, I added a screenshot with the hidden lines

![successful_deployment2](https://user-images.githubusercontent.com/84707942/146443987-7b65d0f6-4714-4772-9479-249f39e3e36c.png)

**Reply by pgrzesik** [reply]
Oh I see what might be the problem - the only ouput that is visible is the version listing because there's a `-v` flag which doesn't mean verbose, but `--version`. Please remove it and try again

**Reply by DanielAizen** [reply]
Sorry to disappoint, but I tried as you suggested and another error popped, I haven't encunted this one yet..
do you this it has to do anything with the fact i didn't pass `args`

Or maybe it has to do anything with `SLS_INTERACTIVE_SETUP_ENABLE`?

![No_args](https://user-images.githubusercontent.com/84707942/146447004-2cb2e715-7761-4822-9652-159abae1d98a.png)

**Reply by pgrzesik** [reply]
Hello @DanielAizen - it this example it looks like the `deploy` command is no longer passed and it tries to invoke interactive setup which is not what you need - it needs to be passed as previously, only `-v` flag should be removed. Could you share your settings of the github action? Ideally in `yaml` format instead of a screenshot, thanks in advance 🙇

**Reply by DanielAizen** [reply]
Hey and good morning @pgrzesik, sorry for the inconvenience before with the screenshots. I did as you asked and ran it as it appears in the code below.
(And again sorry I'm kinda new at this 😅)
Thank you again for your help
```YAML
jobs:
  (some code before that)

  deploy:
    name: deploy to serverless
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #- name: Configure AWS credentials
      #  uses:  aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: eu-west-1
      - name: Install serverless CLI
        run: npm install -g serverless
      - name: Install dependencies
        run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args:
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

**Reply by pgrzesik** [reply]
Hey @DanielAizen - no worries, screenshots are fine but I always prefer textual version :D In your version, there are no args at all, you need to pass it like this:
```
with:
  args: deploy
```

in order to invoke deploy command.

**Reply by DanielAizen** [reply]
Hey @pgrzesik, now I've returned to the problem that I had in the beginning, it doesn't seem to recognize the AWS profile

```
 Serverless Error ----------------------------------------
 
  AWS profile "paylease" doesn't seem to be configured
 
  Get Support --------------------------------------------
``` 
I've tried to un-comment this section:
```
#- name: Configure AWS credentials
      #  uses:  aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: eu-west-1
```
But had no success either, do you know maybe how can I configure the profile?

**Reply by pgrzesik** [reply]
How are you configuring the AWS profile? Could you please provide a anonymized version of your `serverless.yml` configuration?

**Comment by DanielAizen** [comment]
```YAML
service: ***
app: ***

frameworkVersion: '2'
configValidationMode: error
useDotenv: true

plugins:
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  profile: paylease
  region: eu-west-1
  stage: prod
  
  iam:
    role:
      statements:
        statments

  logs:
    httpApi: true
  
  httpApi:
    cors: true

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

custom:
  enterprise:
    collectLambdaLogs: false
  customDomain:
    certificateName: '***'
    domainName: ***
    basePath: ''
    apiType: http
    endpointType: regional
    stage: ${self:provider.stage}
    createRoute53Record: true

```
