### DISCUSSION TITLE
How to setup Rabbit Auth?

### DISCUSSION THREAD

**Discussion by chanan** [serverless/serverless#10387] [General]
Hi,

The documentation here: https://www.serverless.com/framework/docs/providers/aws/events/rabbitmq

Shows:

```
functions:
  compute:
    handler: handler.compute
    events:
      - rabbitmq:
          arn: arn:aws:mq:us-east-1:0000:broker:ExampleMQBroker:b-xxx-xxx
          queue: queue-name
          basicAuthArn: arn:aws:secretsmanager:us-east-1:01234567890:secret:MySecret
```

What are the values that are stored in the AWS secrets `basicAuthArn`. Rabbit connections need a username and password. How do we store that in the one variable?
