### DISCUSSION TITLE
Transform: AWS::SecretsManager-2020-07-23

### DISCUSSION THREAD

**Discussion by matteoredaelli** [serverless/serverless#10408] [Q&A]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Hello

About serverless & aws how could I convert the following cloudformation code (the row Transform: AWS::SecretsManager-2020-07-23)?

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::SecretsManager-2020-07-23
Description: Deploys an RDS instance
Metadata:
```

It is necessary for autorotating aws keys
  https://nippycodes.com/coding/cloudformation-for-rds-and-autorotate/

The "Transform" key is next to "Description". I tired to add it as suggested by
   https://forum.serverless.com/t/override-the-stack-description/1081/4
but it does not work

**Comment by pgrzesik** [comment]
Hello,

this is not exactly a bug report or request for enhancement in the Framework. I'm going to move it to Discussions.

**Comment by matteoredaelli** [comment]
OK

I'd like to autorotate keys for databases users

The error I have:

```
 Serverless Error ----------------------------------------
 
  ServerlessError: An error occurred: AppGraphqDbAppsSecretRotationSchedule - To use the HostedRotationLambda property, you must use the AWS::SecretsManager transform.
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:143:23
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async AwsDeploy.update (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:146:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.18.2
     Framework Version:         2.64.1
     Plugin Version:            5.5.0
     SDK Version:               4.3.0
     Components Version:        3.17.1
```

See 

  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-secretsmanager.html


My code 

```
Resources:
  AppGraphqlDbAppsSecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: pir-dm-iam-app_graphql-db-apps
      Description: Password for user app_graphql Postgres Apps Database
      GenerateSecretString:
        SecretStringTemplate: '{"username": "app_graphql"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: true
  AppGraphqDbAppsSecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref AppGraphqlDbAppsSecretsManagerSecret
      TargetId: !Join
        - ""
        - - "arn:aws:rds:"
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - "cluster:myproject-"
          - ${self:provider.stage}
          - "-apps"
      TargetType: AWS::RDS::DBCluster
  AppGraphqDbAppsSecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref AppGraphqlDbAppsSecretsManagerSecret
      HostedRotationLambda:
        RotationType: PostgreSQLSingleUser
      RotationRules:
        AutomaticallyAfterDays: 60
```

No errors without "AppGraphqDbAppsSecretRotationSchedule"
