### DISCUSSION TITLE
Error: Cannot find module 'esbuild'

### DISCUSSION THREAD

**Discussion by wenindoubt** [serverless/serverless#10442] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

A **fresh** Serverless + TypeScript project is unable to invoke locally.

```
$ sls create --template aws-nodejs-typescript

$ npm install

$ sls invoke local --function hello
```

### Service configuration (serverless.yml) content

```yaml
// This is the fresh, out-of-the-box `serverless.ts` file that I am using.
// serverless.ts

import type { AWS } from '@serverless/typescript';

import hello from '@functions/hello';

const serverlessConfiguration: AWS = {
  service: 'devops-slack-approval',
  frameworkVersion: '2',
  plugins: ['serverless-esbuild'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
    },
    lambdaHashingVersion: '20201221',
  },
  // import the function via paths
  functions: { hello },
  package: { individually: true },
  custom: {
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ['aws-sdk'],
      target: 'node14',
      define: { 'require.resolve': undefined },
      platform: 'node',
      concurrency: 10,
    },
  },
};

module.exports = serverlessConfiguration;
```
```


### Command name and used flags

$ SLS_DEBUG=* sls invoke local --function hello

### Command output

```shell
$ SLS_DEBUG=* sls invoke local --function hello
Running "serverless" from node_modules
Environment: darwin, node 14.18.2, framework 3.0.0-pre.8417339e, plugin 6.0.0-pre.e20784fc, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Cannot find module 'esbuild'
Require stack:
- /Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless-esbuild/dist/index.js
- /Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless/lib/classes/PluginManager.js
- /Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless/lib/Serverless.js
- /Users/jeffrey.wen/.nvm/versions/node/v14.18.2/lib/node_modules/serverless/lib/Serverless.js
- /Users/jeffrey.wen/.nvm/versions/node/v14.18.2/lib/node_modules/serverless/scripts/serverless.js
- /Users/jeffrey.wen/.nvm/versions/node/v14.18.2/lib/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._resolveFilename (/Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless-esbuild/dist/index.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at requireServicePlugin (/Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless/lib/classes/PluginManager.js:34:12)
    at /Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless/lib/classes/PluginManager.js:181:22
    at Array.map (<anonymous>)
    at PluginManager.resolveServicePlugins (/Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless/lib/classes/PluginManager.js:178:10)
    at PluginManager.loadAllPlugins (/Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless/lib/classes/PluginManager.js:161:10)
    at Serverless.init (/Users/jeffrey.wen/Documents/work/devops-slack-approval/node_modules/serverless/lib/Serverless.js:213:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Serverless.eventuallyFallbackToLocal (/Users/jeffrey.wen/.nvm/versions/node/v14.18.2/lib/node_modules/serverless/lib/Serverless.js:260:5)
    at async Serverless.init (/Users/jeffrey.wen/.nvm/versions/node/v14.18.2/lib/node_modules/serverless/lib/Serverless.js:186:5)
    at async /Users/jeffrey.wen/.nvm/versions/node/v14.18.2/lib/node_modules/serverless/scripts/serverless.js:602:7
```
```


### Environment information

```shell
$ sls --version
Framework Core: 2.70.0
Plugin: 5.5.2
SDK: 4.3.0
Components: 3.18.1

$ node --version
v14.18.2
```
```
