### DISCUSSION TITLE
single endpoint generated for multiple WebSocket functions.

### DISCUSSION THREAD

**Discussion by anand-010** [serverless/serverless#10465] [Q&A]
I am tring to create two wesocket endpoints with two lambda functions.
But i have only got single wss endpoint.
```
functions:
  usersWebsocket:
    handler: handler.usersWebsocket
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
      - websocket:
          route: onMessage
  deviceWebsocket:
    handler: handler.deviceWebsocket
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
      - websocket:
          route: onMessage
```
![desess](https://user-images.githubusercontent.com/32414977/148524843-d57bdb43-6525-46ca-99b9-3d3ffcc3d13c.PNG)
