### DISCUSSION TITLE
Variable unresolved in Service value

### DISCUSSION THREAD

**Discussion by pwildschut** [serverless/serverless#10507] [Q&A] [answered]
Hi, I have created a yaml file with a dynamic service name like so
```
service: foo-${self:provider.stage}-bar

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: local
```
after running the sls deploy `sls deploy --stage dev` I get that the service name is not being resolved and this is affecting the package uploaded to cloudformation asi it is left with the ${}.

I am wondering if this is a bug, does anyone know what could be happening?

Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.71.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1
