### DISCUSSION TITLE
is provider.layers supposed to work ?

### DISCUSSION THREAD

**Discussion by olup** [serverless/serverless#10555] [Q&A] [answered]
Adding layers at provider level does not seem to add them to my lambdas. On function definition it's fine but not otherwise.

eg:
```
provider:
  name: aws
  runtime: nodejs14.x
  layers:
    - !ImportValue MyLayerId
```

**Comment by pgrzesik** [comment]
Yes, they should be applied to your functions. Could you provide a full reproducible example of situation where that is not the case?

**Reply by olup** [reply]
Many thanks for this confirmation that it should work. The config we use is fairly regular, we package layers from zip files : 
```
layers:
  prisma:
    package:
      artifact: ../../.build/layers/prisma-layer.zip
```

import it like this : 
```
    layers:
      - !Ref PrismaLambdaLayer
```

But, on top of my head, we are using three plugins that could alter the way the cf template is generated :
```
plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-plugin-datadog 
```
Everything work when attaching layer to lambda, but is completely ignored when setting it in.the provider's block
