### DISCUSSION TITLE
Serverless CI/CD params + sls offline.

### DISCUSSION THREAD

**Discussion by juanviamonte** [serverless/serverless#10550] [Q&A] [answered]
I'm using parameters in serverless with this notation:
`${param:some_key}` 
but when running locally with serverless offline, an error is shown:
```
Serverless Error ----------------------------------------

  ${param:some_key} not defined
```

is there anyway to pass these params while running offline? 

Thanks a lot.

**Comment by medikoo** [comment]
@juanviamonte what version you're on? And what exactly command you're running?

**Reply by juanviamonte** [reply]
@medikoo Thank you so much for your response:

Here is brief example of our serverless.yml file

```
service: "service"
org: "org"
app: "app"
frameworkVersion: "2"
package:
  individually: true
params:                    <- here I'm defining params to be able to run locally (localhost is one of the stages)
  default:
    honey_badger_api_key: "test"
  localhost:
    honey_badger_api_key: "test"
custom:
  stage: "${opt:stage, self:provider.stage}"
  region: "${opt:region, self:provider.region}"
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - "aws-sdk"
    target: "node14"
    define: {}
    platform: "node"
plugins:
  - "serverless-esbuild"
  - "serverless-offline"
  - "serverless-dotenv-plugin"
  - "serverless-dynamodb-local"
  - "serverless-plugin-datadog"
  - "serverless-add-api-key"
provider:
  name: "aws"
  stage: "localhost"
  environment:
    HONEY_BADGER_API_KEY: ${param.honey_badger_api_key}     <-  I'm expecting this to read "test" when calling process.env
...
```

When calling `console.log(process.env.HONEY_BADGER_API_KEY)` I'm expecting to read "test", from localhost, but the actual string i get is: `process.env.HONEY_BADGER_API_KEY` <- (doesn't seem to be evaluating correctly) this also happens for all the other stages. (I'm able to print other variables from env)

For other stages my params are added in the Serverless CI/CD Dashboard, via Parameters tab

<img width="772" alt="image" src="https://user-images.githubusercontent.com/85184407/151872964-cde19628-41d5-44ef-b339-184980622481.png">

And I can list successfully those via:
`serverless param list --stage develop` <- or passing other stages (production, staging, etc)

Output:
```
Serverless: Stored parameters:

Name                 | Value
honey_badger_api_key   | [REDACTED]
``` 
When running locally i use a command similar to this one: 

`STAGE=localhost REGION=us-east-1 sls offline start --apiKey abc`

The stage changes based on the provided in serverless CI/CD.

Related to package versions:
Node version:
```
"node": ">=14.15.0"
```

```
Packages:
"serverless": "^2.23.0"
"aws-lambda": "^1.0.7"
"aws-sdk": "^2.1029.0"
"@serverless/typescript": "^3.0.0"
"serverless-add-api-key": "^4.2.0",
"serverless-dotenv-plugin": "^3.10.0",
"serverless-dynamodb-local": "^0.2.40",
"serverless-esbuild": "^1.17.1",
"serverless-offline": "^8.2.0",
"serverless-plugin-datadog": "^3.3.0",
"serverless-webpack": "^5.5.5",
"ts-jest": "^27.0.7",
"ts-node": "^9.1.1",
"tsconfig-paths": "^3.9.0",
"typescript": "^4.4.4",
"webpack": "^5.64.1",
"webpack-node-externals": "^3.0.0"
```

Thanks a lot for the help, happy to provide more info.
