### DISCUSSION TITLE
AWS API Gateway stage deployment history been deleted after deployed.

### DISCUSSION THREAD

**Discussion by MelonWang9527** [serverless/serverless#10560] [Q&A] [answered]
Hello, I was trying to build a REST API with AWS Lambda + AWS API Gateway.
Before using Serverless framework, I can deploy the API to a specific stage manually on the website, and there will be deployment history for this stage.
Then, I tried to use Serverless framework(Framework Core: 2.72.2, no plugin) to deploy the API to the same stage multiple times (with modified codes).  
However, the deployment history by Serverless will be deleted and only left the latest one.

![1](https://user-images.githubusercontent.com/20352443/150950335-e4549324-515c-42a4-a231-fc8d603eac34.JPG)

```
service: serverless-myfleetapi

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: ap-northeast-1
  stage: dev
  apiName: test
  memorySize: 512
  timeout: 10
  versionFunctions: true
  stackName: serverless-myfleetapi-${sls:stage}
  apiGateway:
    description: Description by Serverless

# Reference: https://www.serverless.com/framework/docs/providers/aws/guide/functions
functions:                          # If you are using AWS as a provider, all functions inside the service are AWS Lambda functions.
  test-name:                        # Lambda function
    handler: lambda_function.lambda_handler
    name: ${sls:stage}-test         # optional, Deployed Lambda name
    description: My function        # The description of your function.
    memorySize: 512                 
    timeout: 10       
    environment:     
      functionEnvVar: 12345678
    events:                       
      - http: 'GET /'               # REST API endpoint (API Gateway v1)
      - http: 'GET /user'
      - http: 'POST /user/{id}'     
```

I observed that the CloudFormation will delete an API Gateway deployment when I tried to deploy.

![擷取](https://user-images.githubusercontent.com/20352443/150947031-275e8877-c8ce-4ec1-bdae-d4b12c1fa9ed.JPG)

Is there any setting that I can keep the deployment history by Serverless ?

Thanks in advance.
