### DISCUSSION TITLE
How to reference parameter from serverless deploy cli to file (template) referenced in serverless.yaml file?

### DISCUSSION THREAD

**Discussion by nirojshrestha019** [serverless/serverless#10565] [Q&A]
I have `LatencyThreshold` parameter passed during deployment as 
`serverless deploy --stage dev --LambdaLatencyThreshold 3000`

How do I reference `LambdaLatencyThreshold ` parameter in `cloudformation/alarms.yaml` file for the Threshold properties? Thank you.

Here are the detailed sample files:

`serverlesss.yaml`

```
service: testing-test

custom:
  stage: ${opt:stage, self:provider.stage}
  LatencyThreshold: ${opt:LatencyThreshold}

provider:
  name: aws
  region: us-west-2
  stage: dev
  runtime: nodejs14.x
  architecture: x86_64
  memorySize: 512
  logRetentionInDays: 3653 # 10 years
  environment:
    STAGE: ${self:custom.stage}

functions:
  testServer:
    timeout: 40
    description: 'API Server'
    role: ServerLambdaRole
    events:
      - http:
          method: ANY
          path: /

          .........

resources:
  - ${file(cloudformation/alarms.yaml)}

```

`cloudformation/alarms.yaml`

```
Resources:
  ApiGatewayLatencyAlarm:
    DependsOn: ApiGatewayRestApi
    Type: AWS::CloudWatch::Alarm
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: 'We want to explicitly create an alarm name'
    Properties:
      AlarmDescription: Alarm when Api GW average latency is more than 3s; 2 times
      AlarmName: !Join ['.', [testSolution, !Ref Stage, Low, ApiGatewayLatencyAlarm]]
      ActionsEnabled: False
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      MetricName: Latency
      Dimensions:
        - Name: ApiName
          Value: 
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Average
      Threshold: ${self: custom.LambdaLatencyThreshold}
      TreatMissingData: notBreaching
      Unit: Milliseconds
```

Here are some of the links I followed but didn't seem to work:
- https://forum.serverless.com/t/cloudformation-parameters/1777
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
- https://theserverlessway.com/aws/cloudformation/templates/
