### DISCUSSION TITLE
Plugin serverless-offline command not found (version 3)

### DISCUSSION THREAD

**Discussion by rodjul** [serverless/serverless#10630] [Q&A]
Hello,

We are using the latest version of serverless framework, but we can not execute specific plugins.

I don't know the origin of this problem, if it's the serverless or in serverless-offline.

Possible bug: when running the command to start offline, it shows a message saying it did not found the command.

In previous versions below 3.0, like 2.72.2, the same command works fine.

Command:
```bash
rodjul@DESKTOP:~/project $ npm i serverless-offline@8.4.0
rodjul@DESKTOP:~/project $ serverless offline --stage local --region us-east-2 -c serverless_functions.yml
Environment: linux, node 14.18.0, framework 3.0.1, plugin 6.0.0, SDK 4.3.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Serverless command "offline" not found. Run "serverless help" for a list of all available commands.
```

Versions:
```bash
rodjul@DESKTOP:~/project $ serverless --version
Framework Core: 3.0.1
Plugin: 6.0.0
SDK: 4.3.1
```

Serverless file:
```yaml
service: serviceapi

package:
  individually: true
  excludeDevDependencies: false


provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline

custom:
  awsconfig: ${file(awsconfig.yml):${self:provider.stage}}
  serverless-offline:
    ignoreJWTSignature: true


functions:
  get_user_permission:
    handler: src/apigateway/users/get_permission.lambda_handler
    runtime: python3.8
    memorySize: 256
    timeout: 30
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-get_permissions-${self:provider.stage}
    package:
      patterns:
        - src/apigateway/users/get_permission.py
    events:
      - http:
          path: /users/permission
          method: get
          cors: true
          authorizer:
            localAuthorizer:
              name: "mockJWTAuthentication"
              type: "request"
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer


resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: apig-api-${self:provider.stage}
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'


    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - arn:aws:cognito-idp:us-east-2:123456789012:userpool/aaaa
```
