### DISCUSSION TITLE
provisionedConcurrency not working

### DISCUSSION THREAD

**Discussion by orr-levinger** [serverless/serverless#10638] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

using "serverless": "2.70.0"

created a function:

  testProvisionedConcurrency:
    handler: src/functions/testProvisionedConcurrency.handler
    provisionedConcurrency: 1
    timeout: 240

function code:

`import 'source-map-support/register';
import { sleep } from '../utils/utils';

const start = Date.now();
let end = Date.now();

while (end - start < 3000) {
  end = Date.now();
}

export const handler = async (event: any): Promise<string> => {
  await sleep(100);
  return 'OK';
};
`

then when executing the function i have a cold start

### Service configuration (serverless.yml) content

```yaml
this are my plugins:
  - serverless-layers
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-iam-roles-per-function
  - serverless-appsync-simulator
  - serverless-appsync-plugin
  - serverless-plugin-split-stacks
  - serverless-export-env
  - serverless-step-functions
  - serverless-s3-remover
  - serverless-plugin-log-retention
  - serverless-api-gateway-caching
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.70.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1
```

**Comment by medikoo** [comment]
@orr-levinger We need a complete `serverless.yml` content and no plugins involved. There's a high chance that it's a plugin that's responsible for the issue you're observing, in such case bug report needs to go to the corresponding plugin repository.

Additionally please provide command name you're using for deployment and full generated output

**Comment by orr-levinger** [comment]
```
service: testProvisionedConcurrency

frameworkVersion: "2.70.0"

provider:
  package:
    individually: true
    excludeDevDependencies: true
  tags:
    lumigo:auto-trace: "true"
  name: aws
  tracing:
    lambda: true
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  stackName: ${self:custom.base}-stack
  timeout: 15
  endpointType: regional

custom:
  region: ${opt:region, self:provider.region}
  myStage: ${opt:stage, self:provider.stage}
  base: ${self:service}-${self:custom.myStage}

functions:
  testProvisionedConcurrency:
    handler: src/functions/testProvisionedConcurrency.handler
    provisionedConcurrency: 1
    timeout: 240
```

package.json:

```
{
  "name": "blind-chat-backend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "sls": "sls"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/orr-levinger/blind-chat-backend.git"
  },
  "devDependencies": {
    "serverless": "2.70.0"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/orr-levinger/blind-chat-backend/issues"
  },
  "homepage": "https://github.com/orr-levinger/blind-chat-backend#readme"
}
```


This is the lambda
```
const sleep = require('../utils/utils');

const start = Date.now();
let end = Date.now();

while (end - start < 3000) {
  end = Date.now();
}

module.exports.handler = async (event) => {
  await sleep(100);
  return 'OK';
};
```

deploy command: npm run sls deploy

when invoking it i get cold start.
to be more specific when not calling the alias directly or the version but simply invoking the lambda by name.
if i invoke the alias: testProvisionedConcurrency-dev-testProvisionedConcurrency:provisioned
also if i invoke the version: testProvisionedConcurrency-dev-testProvisionedConcurrency:2
it works

must add that in my real app i use appsync as the front facing gateway

but i expect it to work when just invoking the lambda
