### DISCUSSION TITLE
Null properties of "transform" resource are removed in generated CloudFormation template

### DISCUSSION THREAD

**Discussion by trend-jack-c-tang** [serverless/serverless#10649] [Q&A] [answered]
Hi,

Based on the second note of the [resource configuration document](https://github.com/serverless/serverless/blob/main/docs/providers/aws/guide/resources.md#configuration), the properties with null assignment are stripped before upload, because CloudFormation doesn't allow them.

But CloudFormation template supports to include some transforms and macros that take those properties and transform to resources CFN allows. For example, [`AWS::Serverless`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html) is a transform CFN supports. The `ResultPath` specified in `Definition` property of [`AWS::Serverless::StateMachine`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html) resources accepts `null` value with certain purpose. Stripping them make the step functions not work as expected.

Should the strip function bypass resources that will be transformed? Or is there a better suggestion or workaround for this usage? Thanks.

Related PR: https://github.com/serverless/serverless/pull/10304
Related issue: https://github.com/serverless/serverless/issues/10279

**Comment by pgrzesik** [comment]
Hello @jack-c-tang - at the moment, unfortunatelly, there's no workaround as `null` properties are splitted automatically from all properties in generated CloudFormation

**Comment by medikoo** [comment, marked as answer]
@jack-c-tang great thank for rising that. That's an interesting issue, Can you provide a minimal example of CF template that uses `null` values and is accepted as valid by AWS?

**Reply by trend-jack-c-tang** [reply]
Sure:
```
AWSTemplateFormatVersion: 2010-09-09
Description: Serverless transform resource with null assigned property
Transform: AWS::Serverless-2016-10-31
Resources:
  NullResultPathStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      Name: nullResultPathStateMachine
      Policies: arn:aws:iam::aws:policy/AWSStepFunctionsReadOnlyAccess
      Definition:
        StartAt: State1
        States:
          State1:
            Type: Pass
            Parameters:
              parameter: 'sample'
            ResultPath: null
            End: true
```
