### DISCUSSION TITLE
Deploy stage: Expected an iterable for content, received

### DISCUSSION THREAD

**Discussion by nova93** [serverless/serverless#10651] [Q&A] [answered]
Hey,

I'm trying to deploy a simple app. During deploy, at the `Copying existing artifacts` stage, I'm getting the following error:

```
Deploying websocket-test to stage dev (eu-west-1)
Bundling with Webpack...
No external modules needed
Copying existing artifacts...

✖ Stack websocket-test-dev failed to deploy (68s)
Environment: darwin, node 14.17.1, framework 3.1.1 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, "staging" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Expected an iterable for content, received 
    at module.exports (/Users/myuser/Documents/alb-test/server/node_modules/type/lib/resolve-exception.js:12:14)
    at module.exports (/Users/myuser/Documents/alb-test/server/node_modules/type/iterable/ensure.js:17:34)
    at Serverless.addServiceOutputSection (/Users/myuser/Documents/alb-test/server/node_modules/serverless/lib/serverless.js:175:17)
```

Print command works without any issues.

Any ideas?

<hr>

<details>
<summary>serverless.yml</summary>

```yml
service: websocket-test

useDotenv: true

custom:
  serverless-offline:
    httpPort: 4000 # Change this value to run locally on a different port
    noPrependStageInUrl: true
  customDomain:
    domainName: serverless.somedomain.com
    basePath: "websocket-test" # This will be prefixed to all routes
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  logRetentionInDays: 14
  websocketsApiName: websocket-test-websocket

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-bundle

functions:
  webSocketTest:
    handler: main.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

```
</details>

<details>
<summary>main.js</summary>

```js
import {
  ApiGatewayManagementApiClient,
  DeleteConnectionCommand,
  PostToConnectionCommand,
} from "@aws-sdk/client-apigatewaymanagementapi";

const client = new ApiGatewayManagementApiClient({
  region: "eu-west-1",
  endpoint: "http://localhost:3001",
});

export const handler = async (event, context, callback) => {
  let inc;
  try {
    inc = JSON.parse(event.body);
  } catch {}

  if (inc && inc.payload && inc.payload.query) {
    console.log(event);
    // console.log(event.requestContext.connectionId);

    await new Promise((resolve) => setTimeout(resolve, 10000));

    // send data to client
    try {
      const input = {
        ConnectionId: event.requestContext.connectionId,
        Data: JSON.stringify({
          payload: {
            data: {
              comments: {
                id: "some-id",
                content: "hello there",
              },
            },
          },
          id: inc.id,
          type: "data",
        }),
      };

      const command = new PostToConnectionCommand(input);
      const response = await client.send(command);
      console.log("response", response);
    } catch (error) {
      console.error("response failed", error);
    }

    // close the connection
    try {
      const input = {
        ConnectionId: event.requestContext.connectionId,
      };
      const command = new DeleteConnectionCommand(input);
      const response = await client.send(command);
      console.log("response", response);
    } catch (error) {
      console.error("collection close failed", error);
    }

    callback(null, {});
  }
};
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "websocket-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "AWS_PROFILE=staging sls offline start",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Robert Moritz",
  "license": "ISC",
  "devDependencies": {
    "serverless": "^3.1.1",
    "serverless-bundle": "^5.2.0",
    "serverless-domain-manager": "^6.0.0",
    "serverless-offline": "^8.4.0"
  },
  "dependencies": {
    "@aws-sdk/client-apigatewaymanagementapi": "^3.49.0"
  }
}
```

</details>
