### DISCUSSION TITLE
Is it possible to use variables in "${ssm:/}" syntax?

### DISCUSSION THREAD

**Discussion by guyschlider** [serverless/serverless#10658] [Q&A]
Hi all,

I'm using the [serverless-vpc-plugin](https://github.com/smoketurner/serverless-vpc-plugin/) plugin for creating vpcs and so on, when I want to create resources in of the subnets it creates - I need to read the data fro ssm, problem is that the path is based on the stack name but I wasn't able to make 

`${ssm:/} ` to work with variables for example:

```
    Resources:
      ElasticsearchDomain:
        Type: AWS::OpenSearchService::Domain
        Properties:
          DomainName: tasks-${self:custom.stage}
          EngineVersion: 'OpenSearch_1.0'
          ClusterConfig:
            # DedicatedMasterEnabled: true
            InstanceCount: '1'
            # ZoneAwarenessEnabled: true
            InstanceType: 't3.small.search'
            # DedicatedMasterType: 't3.small.elasticsearch'
            # DedicatedMasterCount: '1'
          EBSOptions:
            EBSEnabled: true
            VolumeSize: '16'
            VolumeType: 'gp2'
          AdvancedOptions:
            rest.action.multi.allow_explicit_index: true
          VPCOptions:
            SubnetIds: ${ssm:/SLS/${self:custom.stackName}/DBSubnets~split}
```
(note the ${self:custom...} in the Subnetids parameter.)
this doesn't work, error is: 

ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
