### DISCUSSION TITLE
iam statements not working?

### DISCUSSION THREAD

**Discussion by ehrlichja** [serverless/serverless#10674] [Q&A] [answered]
I have this:
```
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - '*'

```

But when I get the iam role, I only see:
```
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "lambda.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        },
```

Shouldn't I see my dynamodb action in here? Am I looking at the wrong thing? I should see the default statements for cloud logging here too right? What am I missing?
