### DISCUSSION TITLE
Environment Variables Resolution Issue

### DISCUSSION THREAD

**Discussion by brian-pinwheel** [serverless/serverless#10748] [Q&A]
I have configured my lambda's to have environment variables specified in AWS.  I now need to reference some secrets in the AWS Parameter Store.  I have added the following code to my serverless.yml:

```
functions:
  my-func:
    handler: my-handler
    environment:
      USER_NAME: ${ssm:user-name}
      USER_PASSWORD: ${ssm:user-password}
```

Unfortunately, then my other environment variables stopped resolving.  I am guessing the `environment` property is overriding the variables previously provided on the lambda machine.

I then followed the documentation for variables and tried to add all my variables to the `environment` list by
```
environment:
  USER_NAME: ${ssm:user-name}
  USER_PASSWORD: ${ssm:user-password}
  VAR_1: ${env:VAR_1}
  VAR_2: ${env:VAR_2}
```
Unfortunately, this appears to be breaking my deployment as it appears serverless is trying to resolve all the variables at build time.  The build machine does not set env variables so getting the message: 
```
Cannot resolve serverless.yml: Variables resolution errored with:
   - Cannot resolve variable at "functions.api.environment.VAR_1": Value not found at "env" source,
   - Cannot resolve variable at "functions.api.environment.VAR_2": Value not found at "env" source,
 ```

I am trying to find a way to add all my existing lambda runtime env vars while at the same time without having to set a number of env vars on my build machine.  I would welcome any suggestions.
