### DISCUSSION TITLE
Potential discrepancy between Packaging code and documentation?

### DISCUSSION THREAD

**Discussion by pflugs30** [serverless/serverless#10745] [Q&A]
_Relates to [this issue](https://github.com/serverless-heaven/serverless-webpack/issues/1075)_

I'm wondering if there is a discrepancy between [the Serverless packaging code](https://github.com/serverless/serverless/blob/bf79934e9b43a0b2e8613ee29f9430fa22c41481/lib/plugins/package/package.js#L34) and its [documentation](https://www.serverless.com/framework/docs/providers/aws/guide/packaging/#patterns), particularly around the use of the `patterns` configuration.  I recently upgraded a Serverless project from v1.X to v3.X, and I noticed a deprecation warning stating `Support for "package.include" and "package.exclude" will be removed in the next major release. Please use "package.patterns" instead`.

As I dug into that Serverless code, and I found [this module](https://github.com/serverless/serverless/blob/bf79934e9b43a0b2e8613ee29f9430fa22c41481/lib/plugins/package/lib/zip-service.js#L35).  It appears that module only looks for `include` and `exclude` parameters:
![image](https://user-images.githubusercontent.com/4409272/155212670-fe11212e-a48a-4396-88e0-2674a284de3d.png)

Shouldn't the `patterns` config object be added to this code?

Additionally, in reading [this documentation](https://www.serverless.com/framework/docs/providers/aws/guide/packaging/#development-dependencies) on the Development Dependencies, it seems to indicate the `excludeDevDependencies` property will remove `devDependencies` and do something like tree shaking.  That was the impression I got, at least.  In my project, I had Lambda Layer that existed to bundle some NPM packages.  However, each time I deployed the application, none of the packages were included.  I learned through experimenting that the `excludeDevDependencies` property needed to be set to `false` in order for the `node_modules` to be included.  I felt the documentation wasn't clear on this property's behavior.

What is the intent of the `excludeDevDependencies`?  Is it to remove `devDependencies`?  Is it for tree shaking, similar to what webpack might do?  If so, could the documentation be made clearer?

Thanks!

**Comment by pgrzesik** [comment]
Hello @pflugs30 👋 Patterns are added as well, it's the naming in case of this particular function what might be a bit misleading - see what is passed to this logic, e.g. here: https://github.com/serverless/serverless/blob/bf79934e9b43a0b2e8613ee29f9430fa22c41481/lib/plugins/package/lib/package-service.js#L238

As for the development dependencies exclusion - what it basically does is that it excludes all deps that are installed and defined as `devDependencies` in your package.json file. Do you observe behavior where e.g. dependencies defined in regular `dependencies` are getting excluded too?

**Reply by pflugs30** [reply]
Hello @pgrzesik!  Thanks for the reply.  I looked at the link to the code, and I'm relieved the `patterns` are also included.

Regarding the development dependencies exclusion, yes, I am seeing a case where production dependencies aren't included.  I'll try to set up this example.

I have a Serverless project with many Lambdas where I've isolated the production dependencies to a Lambda layer in order to reduce the individual Lambda sizes and speed up deployment.  As such, I've put all my Lambda dependencies in the `devDependencies` section of the `package.json` file.  Then, in the Lambda layer directory, I have a `package.json` file containing all the dependencies so they can be bundled together.  My code files are structured like this:
* root
  * layers
    * appsync-layer
      * package.json
      * yarn.lock
  * serverless.yml
  * package.json
  * webpack.config.js
  * yarn.lock

Note that there are no *.js files in the layers directory.  The `root/layers/appsync-layer/package.json` file contains a list of dependencies:
```
{
  "name": "appsync-layer",
  "description": "Contains the packages needed for the Appsync layer",
  "dependencies": {
    "aws-sdk": "2.1074.0",
    "mysql2": "2.3.3",
    "p-iteration": "1.1.8",
    "sequelize": "6.16.1",
    "uuid": "8.3.2"
  }
}
```

Here's the `package.json` file:
```
{
  "name": "platform-appsync",
  "scripts": { ... },
  "devDependencies": {
     /* ... many others */
    "sequelize-cli": "6.4.1",
    "serverless": "3.2.1",
    "serverless-appsync-plugin": "1.12.1",
    "serverless-appsync-simulator": "0.19.6",
    "serverless-offline": "8.4.0",
    "serverless-webpack": "5.6.1",
    "typescript": "4.5.5",
    "uuid": "8.3.2",
    "webpack": "5.69.0",
    "webpack-cli": "4.9.2",
    "webpack-node-externals": "3.0.0",
    "winston": "3.6.0"
  },
  "dependencies": {} // nothing here!
}
```

Here's a condensed version of `serverless.yml`:
```
service: platform-appsync
useDotenv: true

frameworkVersion: ">=3.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    NODE_PATH: "./:/opt/node_modules"

layers:
  appsync:
    path: layers/appsync-layer
    compatibleRuntimes:
      - nodejs12.x
    package:
      patterns:
        - node_modules/**

functions:
  databaseSync:
    handler: src/databaseSync.handler
    name: ${self:provider.stage}-databaseSync
    layers:
      - { Ref: AppsyncLambdaLayer }

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-offline

custom:
  webpack:
    excludeFiles: "**/*.spec.js"
    includeModules:
      forceExclude:
        - aws-sdk
        - mysql2
        - p-iteration
        - sequelize
        - uuid
      packagePath: "./package.json"
    webpackConfig: "webpack.config.js"
    packager: "yarn"
```

When I run `sls package --stage dev` and inspect the result, I notice the `appsync.zip` file does not contain ANY packages at all.  When I set the `excludeDevDependencies` flag to `false` and package again, then the dependencies are added to the layer zipped file.

I should note I also ran a test where I added a dummy file `test.js` to the layers directory containing the following:
```
require('aws-sdk');
require('mysql2');
require('p-iteration');
require('sequelize');
require('uuid');
```

I thought the file would force the dependency checker to include the packages, but I still found no modules in the lambda zipped file when finished.

Am I to understand that this is not the intended behavior?
