### DISCUSSION TITLE
pointing gateway integration request to an aliased lambda function

### DISCUSSION THREAD

**Discussion by dzorlu** [serverless/serverless#10755] [Q&A] [answered]
Hi- Thanks for all the work. I am a fairly novice user, but managed to get the ci/cd working expect one issue I am struggling with. How do I make sure the `getaway` references to an aliased lambda function? 

I have tried several plugins including `serverless-aws-alias` but no avail. After deployment,  the websocket integration does not point to the provisioned alias, which is used for provisioned concurrency. In the example below, I would like it to point to `ps-streaming-feature-test5-connectionManager:provisioned` instead. 

<img width="1008" alt="Screen Shot 2022-02-24 at 3 55 46 PM" src="https://user-images.githubusercontent.com/3424293/155627217-ec31e60b-435c-40a0-834b-0f61c516bb6a.png">

Any pointers would be very appreciated. 

serverless.yaml
```
org: xxx
app: ps-streaming
service: ps-streaming

provider:
    name: aws
    runtime: python3.7
    stage: ${sls:stage}
    timeout: 30
    memorySize: 2048
    region: us-west-2

.
.

custom:
    pythonRequirements:
        zip: true
    output:
        file: stack-output.json # save the websocket endpoint for e2e testing.
...

functions:
.
.
.
        
    defaultMessage:
        handler: handler.default
        events:
            - websocket:
                route: $default
        provisionedConcurrency: ${self:custom.provisionedConcurrency.defaultMessage.staging, self:custom.provisionedConcurrency.defaultMessage.else}
    ping:
        handler: handler.ping
        events:
            - http:
                path: ping
                method: get

plugins:
  - serverless-python-requirements
  - serverless-plugin-scripts
  - serverless-stack-output
 ```

package.json
```
{
  "dependencies": {
    "serverless-python-requirements": "^5.2.0",
    "serverless-stack-output": "^0.2.3", 
    "serverless-plugin-scripts": "^1.0.2",
  },
  "scripts": {
    "pretest": "pip3 install -r requirements.txt",
    "test": "python -m unittest"
  }
}
```

Deniz
