### DISCUSSION TITLE
HTTP URI integration

### DISCUSSION THREAD

**Discussion by McCo0L** [serverless/serverless#10790] [Q&A] [answered]
I need to redirect options request to a specific URL, I can accomplish this on console by creating a proxy integration to HTTP URI instead of lamba. 
Is it posible with serverless? 
The closest I got is here, these create the paths exactly as I needed but it uses the same lambda integration for both, is there a way to declare a http uri integration for the /{proxy+} part of it?

```
functions:
  app:
    handler: hello.app.main.handler
    events:
      - httpApi:
          path: '*'
      - httpApi:
          path: '/{proxy+}'
          method: options
```

**Comment by pgrzesik** [comment]
Hey, direct APIGW integrations are not supported out of the box, but maybe that plugin would be helpful in your case? https://github.com/serverless-operations/serverless-apigateway-service-proxy

**Reply by McCo0L** [reply]
Will try this! Was trying to extend the httpApi through resources part in serverless.yml without success so far.

**Reply by pgrzesik** [reply]
It should be definitely possible to implement via raw CloudFormation in `resources` section but I don't have a working example to share

**Comment by McCo0L** [comment, marked as answer]
Just in case anyone lokking for a solution, found a solution using resources section with CloudFormation code:

This is the code I've used.
```
resources:
  Resources:
    ProxyIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId:
          Ref: HttpApi
        PayloadFormatVersion: '1.0'
        IntegrationMethod: OPTIONS
        IntegrationType: HTTP_PROXY
        IntegrationUri: http://example.com
    HttpApiRouteProxy:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId:
          Ref: HttpApi
        RouteKey: 'OPTIONS /{proxy+}'
        Target:
          Fn::Join:
            - /
            - - integrations
              - Ref: ProxyIntegration
      DependsOn: ProxyIntegration
```
