### DISCUSSION TITLE
S3 event notifications are not recreated on update

### DISCUSSION THREAD

**Discussion by g-bartoszek** [serverless/serverless#10808] [Q&A] [answered]
We deploy a lambda that we want to be triggered on existing s3 bucket modification: 
```
service: notification-test

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  hello:
    handler: handler.extractFile
    events:
      - s3:
          bucket: gb-notifications-tests
          event: s3:ObjectCreated:Put
          existing: true
```
The above `serverless.yaml` configures a notification in `gb-notifications-tests` and it works as expected. However, when the notification is removed manaully (for example using the console), running `serverless deploy` will not re-create it. The solution is to run `serverless remove` and then `serveless deploy` again but it's not always possible (for example in production). 

Is this a bug or there is a way to refresh notifications on update?

My understanding is that the lambda backed resource responsible for configuring the notifications is not triggered in this case because its definition has not changed. A workaround I found is to add a second "dummy" notification containing a timestamp in its definition (for example in prefix) so that the configuration is always different.

**Comment by pgrzesik** [comment, marked as answer]
Hello @g-bartoszek - the situation in this case is that the underlying custom resource didn't change so it's not updated. Is there a reason as to why you're removing it outside of serverless configuration? In general, you should not expect that something that has been removed manually will be properly recreated by serverless deployment (in most cases that's the behavior, but as you can see not in all of them).

**Reply by g-bartoszek** [reply]
Hi @pgrzesik . Thank you for clarifying. I don't know the specific reason but, unfortunately, it happened several times in our project. Initially we didn't know why notifications are not being configured on update so we added them manually as a workaround. I was wondering if there's a proper solution to this problem.

**Reply by pgrzesik** [reply]
At the moment not really, the best way would be to avoid any manual updates and always do the deployments via `serverless` to ensure integrity of the stack

**Comment by ShnkeWeber** [comment]
For anyone else having the problem: the flag _forceDeploy: true_ solved the issue for me
```
functions:
  hello:
    handler: handler.extractFile
    events:
      - s3:
          bucket: gb-notifications-tests
          event: s3:ObjectCreated:Put
          existing: true
          forceDeploy: true
```
