### DISCUSSION TITLE
Invalid request provided: Updating PackageType is not supported

### DISCUSSION THREAD

**Discussion by gleidsonh** [serverless/serverless#10805] [Q&A]
I'm trying to deploy this function using an ECR image, but without success. Every time I get the error message: UPDATE_FAILED: FunctionLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Invalid request provided: Updating PackageType is not supported"

```
service: service-name
useDotenv: true

provider:
  name: aws
  profile: ${env:PROFILE}
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  apiGateway:
    restApiId: ${self:custom.apiGateway.${self:custom.stage}.restApiId}
    restApiRootResourceId: ${self:custom.apiGateway.${self:custom.stage}.restApiRootResourceId}
    restApiResources:
      service: ${self:custom.apiGateway.${self:custom.stage}.restApiResources}

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-dotenv-plugin

functions:
  function:
    image: 000000000000.dkr.ecr.us-east-1.amazonaws.com/service-name:latest

custom:
  serverless-offline:
    httpPort: 8888
  dotenv:
    path: ../../../../.env
    include:
      - REGION
      - ACCESS_KEY_ID
      - SECRET_ACCESS_KEY
      - JWT_TOKEN
  stage: ${self:provider.stage}
  apiGateway:
    prod:
      restApiId: ${env:CLIENT_PROD_REST_API_ID}
      restApiRootResourceId: ${env:CLIENT_PROD_REST_API_ROOT_RESOURCE_ID}
      restApiResources: ${env:SERVICE_PROD_REST_API_RESOURCES}
    staging:
      restApiId: ${env:CLIENT_STAGING_REST_API_ID}
      restApiRootResourceId: ${env:CLIENT_STAGING_REST_API_ROOT_RESOURCE_ID}
      restApiResources: ${env:SERVICE_STAGING_REST_API_RESOURCES}
    dev:
      restApiId: ${env:CLIENT_DEV_REST_API_ID}
      restApiRootResourceId: ${env:CLIENT_DEV_REST_API_ROOT_RESOURCE_ID}
      restApiResources: ${env:SERVICE_DEV_REST_API_RESOURCES}
  domains:
    prod: ${env:CLIENT_DOMAIN_PROD}
    staging: ${env:CLIENT_DOMAIN_STAGING}
    dev: ${env:CLIENT_DOMAIN_DEV}
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    certificateName: ${env:DOMAIN_CERTIFICATE_NAME}
    createRoute53Record: false
```

As I understand it, there are only two values for PackageType: zip or image. But apparently I don't have access to this configuration, the serverless itself does this, correct? Am I doing something wrong or is there a possibility of a bug in the PackageType?

I'm using:
Environment: linux, node 12.22.0, framework 3.7.1 (local) 3.7.1v (global), plugin 6.1.5, SDK 4.3.2
