### DISCUSSION TITLE
Cannot resolve variable at "provider.stage": Value not found at "env" source

### DISCUSSION THREAD

**Discussion by alakdam07** [serverless/serverless#10858] [Q&A] [answered]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Moments ago, I update my packages to latest version. And trying to learn the app locally. I am getting error: `Cannot resolve variable at "provider.stage": Value not found at "env" source`

## Update from old to new 
![Screenshot 2022-03-16 at 10 36 22](https://user-images.githubusercontent.com/47625626/158551063-a217ff06-ab64-4290-a227-5720c3dd3261.png)

## My env files
![Screenshot 2022-03-16 at 10 42 31](https://user-images.githubusercontent.com/47625626/158551406-68b468b9-360d-4994-8087-e43573b93ffe.png)

### Service configuration (serverless.yml) content

```yaml
service: serverless-aws-graphql-book

package:
  individually: true
  include:
    - src/**

provider:
  name: aws
  profile: ${env:profile}
  runtime: nodejs14.x
  stage: ${env:stage}
  region: eu-north-1
  timeout: 30
  apiName: ${self:service.name}-${self:provider.stage}
  environment:
    ITEM_TABLE: ${self:service}-items-${self:provider.stage}
    COGNITO: ${self:service.name}-pool
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction # Added this like mentioned above
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ITEM_TABLE}'
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ITEM_TABLE}/index/*'

  apiGateway:
    shouldStartNameWithService: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm' # Packager that will be used to package your external modules
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5

functions:
  graphql:
    handler: src/handlers/graphql.default
    events:
      - http:
          path: ${env:api_prefix}/graphql
          method: get
          cors: true
      - http:
          path: ${env:api_prefix}/graphql
          method: post
          cors: true
          authorizer: AuthFunction
  ## Authorization function
  AuthFunction:
    handler: src/auth/auth.default

  ## Create user
  PreSignUp:
    handler: src/handlers/PreSignUp.default
    events:
      - cognitoUserPool:
          pool: ${self:provider.environment.COGNITO}
          trigger: PreSignUp
          existing: true

resources:
  Resources:
    ItemsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.ITEM_TABLE}

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        MfaConfiguration: OFF
        UserPoolName: ${self:provider.environment.COGNITO}
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: False
            RequireNumbers: True
            RequireSymbols: False
            RequireUppercase: True
useDotenv: true
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-prune-plugin
```

### Command name and used flags

npm run serv

### Command output

```shell
"N/A"
```

### Environment information

```shell
{
  "name": ".....",
  "version": "1.0.1",
  "main": "src/handler.js",
  "license": "MIT",
  "scripts": {
    "deploy": "sls deploy --stage development",
    "deploy:production": "sls deploy --stage production",
    "lint": "eslint src --ext ts,js --no-ignore --fix",
    "serve": "sls offline -P 4000",
    "start": "node -e js,ts,jsx,tsx -x npm run serve",
    "test": "jest",
    "test:watch": "jest --watch",
    "build": "sls webpack",
    "setup": "./bin/setup",
    "graphql-codegen": "graphql-codegen --config codegen.yml"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^2.6.2",
    "@graphql-codegen/typescript": "^2.4.7",
    "@types/aws-lambda": "^8.10.93",
    "@types/jest": "^25.2.3",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.10.1",
    "aws-sdk": "^2.1090.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.15.0",
    "husky": "^4.3.8",
    "lint-staged": "^10.5.4",
    "nodemon": "^2.0.0",
    "prettier": "^2.5.1",
    "serverless": "^3.7.5",
    "serverless-dotenv-plugin": "^3.12.2",
    "serverless-offline": "^8.5.0",
    "serverless-plugin-warmup": "^7.1.0",
    "serverless-prune-plugin": "^2.0.1",
    "serverless-webpack": "^5.6.1",
    "ts-jest": "^25.5.1",
    "ts-loader": "^6.2.2",
    "typescript": "^3.6.3",
    "webpack": "^4.46.0",
    "webpack-node-externals": "^1.7.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "src/**/*.{js,ts}": [
      "npm run lint",
      "prettier --write",
      "git add"
    ]
  },
  "dependencies": {
    "apollo-server-core": "^3.5.0",
    "apollo-server-lambda": "^3.5.0",
    "aws-lambda": "^1.0.7",
    "graphql": "^15.8.0",
    "ramda": "^0.28.0",
    "uuid": "^8.3.2"
  }
}
```

**Comment by pgrzesik** [comment, marked as answer]
Hello @alakdam07 - I'm moving it to discussions as it's not a bug report. You migrated two major versions and in the meantime, there was a change in how the variable resolver works. In your case, stage is not available as an environment variable so resolution of it fails. Either make sure it's defined or provide a default value e.g. `${env:stage, 'dev'}`. In general, I would not recommend reading stage from env vars as the env files are recognized per stage.

**Comment by rahmann008** [comment]
HI,

@pgrzesik . Am also getting the same issue while running the sreverless deploy from aws code build. if we ran the command manually it is working but while using buildspec file to run it is not getting the details from env file. below are the error am getting while running the build. please help me with any suggestion



<html>
<body>


[Container] 2022/04/04 10:41:59 Phase complete: INSTALL State: SUCCEEDED
--
116 | [Container] 2022/04/04 10:41:59 Phase context status code:  Message:
117 | [Container] 2022/04/04 10:41:59 Entering phase PRE_BUILD
118 | [Container] 2022/04/04 10:41:59 Phase complete: PRE_BUILD State: SUCCEEDED
119 | [Container] 2022/04/04 10:41:59 Phase context status code:  Message:
120 | [Container] 2022/04/04 10:41:59 Entering phase BUILD
121 | [Container] 2022/04/04 10:41:59 Running command serverless deploy --env uat
122 | Environment: linux, node 14.17.2, framework 3.10.2, plugin 6.2.0, SDK 4.3.2
123 | Docs:        docs.serverless.com
124 | Support:     forum.serverless.com
125 | Bugs:        github.com/serverless/serverless/issues
126 |  
127 | Error:
128 | Cannot resolve serverless.yml: Variables resolution errored with:
129 | - Cannot resolve variable at "custom.stage": Value not found at "env" source
130 |  
131 | [Container] 2022/04/04 10:42:01 Command did not exit successfully serverless deploy --env uat exit status 1
132 | [Container] 2022/04/04 10:42:01 Phase complete: BUILD State: FAILED
133 | [Container] 2022/04/04 10:42:01 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: serverless deploy --env uat. Reason: exit status 1
134 | [Container] 2022/04/04 10:42:01 Entering phase POST_BUILD
135 | [Container] 2022/04/04 10:42:01 Running command pwd


</body>
</html>

**Reply by alakdam07** [reply]
Can you share your Yaml file?

**Reply by pgrzesik** [reply]
Hey @rahmann008 - it's hard to say anything without seeing more details about your setup. What allows you to use `--env` flag? Some plugin?

**Comment by rahmann008** [comment]
@pgrzesik  Sorry for that... first let me tell what I did... Am a devops engineer working on AWS platform.. Here our dev team wrote this code and run successfully in their local machine... when we try to automate it we are facing this issue. Am also not sure why they are using this flag. Two major issue we are facing

1. When we are running the application the serverless file cant take the value from .env file.
2. Taking out that flag(--env) it is running successfully. but it is not injecting the environment variables to the lambda function.

I think both issues are related to one another. If got any input from u guys it will be very helpful. Thanks in Advance.
 @alakdam07 which yaml you want to see buildspec or serverless

**Reply by pgrzesik** [reply]
I would like to see the `serverless.yml` (with potentially sensitive parts masked out). Additionally, are you sure that the `.env` file is available under the expected path? I'm assuming you somehow create the `.env` file on CodeBuild, right?

**Comment by rahmann008** [comment]
@pgrzesik @alakdam07 
This is Serverless.yml file
******************************
# Happy Coding!
service: ${self:custom.serviceName.${self:custom.stage}} #picks service name based on env

frameworkVersion: '2'
useDotenv: true

custom:
  dotenv:
    basePath: ./
  stage: ${env:STAGE}
  region: ${env:REGION}
  time:
    dev: cron(30 3 ? * MON-FRI *)
    qa: cron(30 3 ? * MON-FRI *)
    uat: cron(30 3 ? * MON-FRI *)
    stg: cron(30 3 ? * MON-FRI *)
    prod: cron(30 3 ? * MON-FRI *)
  cronForDocUpload:
    dev: cron(1/10 * ? * MON-FRI *)
    qa: cron(1/10 * ? * MON-FRI *)
    uat: cron(1/10 * ? * MON-FRI *)
    stg: cron(1/10 * ? * MON-FRI *)
    prod: cron(1/10 * ? * MON-FRI *)
  serviceName:
    dev: ******************
    qa: *******************
    uat: *****************
    stg: *****************
    prod: *****************


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${self:custom.stage}
  memorySize: 5120
  region: ${self:custom.region}
  timeout: 30
  environment:
    STAGE: ${self:custom.stage}


functions:
  UserMigrationHandler: 
    handler: handlerUserMigration.S3TriggerUserMigrationHandler
    description: S3 Trigger User migration handler
      events:
      - schedule: 
          rate: ${self:custom.time.${self:custom.stage}}
  DocAddedEmailHandler:
    handler: handler.DocAddedEmailHandler
    description: cron schedule handler for new document added email notification
    events:
      - schedule: 
          rate: ${self:custom.cronForDocUpload.${self:custom.stage}}
  ANYApp:
    handler: index.handler
    description: CMS APPLICATION
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors:
            origin: '*'
            headers: # <-- Specify allowed headers
            - X-Requested-With
            - Content-Type
            - Accept
            - Authorization
            - Cache-Control
            - Access-Control-Request-Headers
            - Access-Control-Allow-Methods
            - x-access-token
            - id-token
            - session-token
            allowCredentials: false
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers: # <-- Specify allowed headers
            - X-Requested-With
            - Content-Type
            - Accept
            - Authorization
            - Cache-Control
            - Access-Control-Request-Headers
            - Access-Control-Allow-Methods
            - x-access-token
            - id-token
            - session-token
            allowCredentials: false
   
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-prune-plugin
  
***************************************************************************
@pgrzesik  Yes the .env is in root path. I didnt get this one (I'm assuming you somehow create the .env file on CodeBuild, right?) clearely. we write and store the .env file in codecommit repository. while creating the build using codebuild i need to get the variables from .env and want to inject those values to the lambda function.

**Reply by pgrzesik** [reply]
Hello @rahmann008 👋 I believe this section is problematic in your case

```
custom:
  dotenv:
    basePath: ./
    stage: ${env:STAGE}
    region: ${env:REGION}
```

`serverless-dotenv-plugin` loads different `.env` files based on the stage (e.g. passed via `--env` arg) but this tries to access `STAGE` from environment. Short "fix" might be to declare stage explicitly as an env var when invoking command .e.g `STAGE=uat sls deploy --env uat` in your case.

**Reply by rahmann008** [reply]
![image](https://user-images.githubusercontent.com/26094813/161690091-5350b303-7ca7-431a-b9ae-fd4c4c2911b2.png)

In this image you can see we have different .env files for different environment. so if i Run the command **sls deploy --env uat** it should inject uat environment values to the lambda function and stage should pick the value from uat environment file. 

I belive thats how it should work. If i explicitly  provide the stage value means it might work but I think thats a hardcoding which is not a best practice. Please suggest what else we can do. 

mean while let me try what you suggested. @pgrzesik thanks.

**Reply by pgrzesik** [reply]
```
custom:
  dotenv:
    basePath: ./
    stage: ${env:STAGE}
```

In this snipped, in config for `dotenv` plugin that is responsible for loading `.env` files you have specified `stage` propery that is intended to be resolved from environment BEFORE the plugin even has a chance to load the `.env` files. To be honest, this is a very weird pattern and I'm struggling to find reasons for the implementation - why was it chosen to be implemented this way? It's hard to say more without knowing the reasoning behind implementing such pattern.

> I belive thats how it should work. If i explicitly provide the stage value means it might work but I think thats a hardcoding which is not a best practice. Please suggest what else we can do.

It's not hardcoding - there's no difference between `STAGE=uat sls deploy` vs `sls deploy --env uat` when it comes to using dynamic values

In order for it to work, there needs to be `STAGE` environment variable defined at the moment you run `sls deploy` command.
