### DISCUSSION TITLE
How to create an S3 bucket for function usage?

### DISCUSSION THREAD

**Discussion by kaihendry** [serverless/serverless#10907] [Q&A] [answered]
Currently I'm hitting this `#/Environment/Variables/variables: expected type: String, found: JSONObject` error. That aside, is there any easier way to setup a bucket with write permissions than the following?

```
service: sls-middy-error-handling
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

# Setup S3 Bucket
resources:
  Resources:
    ProfilerBucket:
      Type: AWS::S3::Bucket
    # Allow cpu_profile to be PubObject
    ProfilerBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ProfilerBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "PublicReadGetObject"
              Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:PutObject"
              Resource:
                - "arn:aws:s3:::!Ref ProfilerBucket/*"



functions:
  hello:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get
    environment:
      variables:
        MIDDY_PROFILER_S3_BUCKET_NAME: !Ref ProfilerBucket
```
