### DISCUSSION TITLE
Why does adding a Cognito Lambda trigger auto-generate a function that I don't specify or have control over

### DISCUSSION THREAD

**Discussion by christhomas** [serverless/serverless#10917] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I've got the following error:

```
ServerlessError: An error occurred: CustomDashresourceDashexistingDashcupLambdaFunction - 
Resource handler returned message: 
"User: arn:aws:sts::<REDACTED>:assumed-role/<REDACTED>-role/AWSCloudFormation is 
not authorized to perform: lambda:GetFunction 
on resource: arn:aws:lambda:eu-west-1:<REDACTED>:function:<REDACTED>-custom-resource-existing-cup 
because no identity-based policy allows the lambda:GetFunction action
```

It's an error which occurs whilst I try to use a cognito lambda trigger, which is specified like this

```
aws_cognito_pre_signup_trigger:
    name: ${self:custom.app.name}-aws-cognito-pre-signup-trigger
    handler: src/handler/pre_signup_trigger.aws_cognito_pre_signup_trigger
    tags:
      <<: *lambdaTags
    events:
      - cognitoUserPool:
          pool: ${self:custom.cognito.poolId}
          trigger: PreSignUp
          existing: true
```

But I'm unsure why this function is being created? I have a very controlled deployment role so I have to account for every resource created and this one is not specified by me but for some reason serverless needs it? 

Anybody know what it is and why do I need this? If it's just a function to test whether a user pool exists, why not just call the AWS SDK to check the user pool exists. It seems to want to create an AWS function to test that.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
yarn run v1.22.17
warning package.json: License should be a valid SPDX license expression
$ /Users/chris/projects/plista/auth-service/node_modules/.bin/serverless --version
Framework Core: 2.72.3 (local)
Plugin: 5.5.4
SDK: 4.3.2
Components: 3.18.2
✨  Done in 0.45s.
```
