### DISCUSSION TITLE
How do folks share the name of another function?

### DISCUSSION THREAD

**Discussion by kaihendry** [serverless/serverless#10932] [Q&A]
I'm curious how to get the full function name into this handler? Set an environment variable with the FunctionName of invokeMEpls?

https://github.com/kaihendry/aws-jest-lambda/blob/main/handler.js#L9

But how?

**Comment by Pwntus** [comment]
Yes, you can set an environment variable like this:

```yml
functions:
  startHere:
    handler: handler.start
    environment:
      MY_FUNCTION: 'hendry-lambda-invoke-test-dev-invokeMEpls'
```

Access the environment variable in the Lambda function code:

```js
const resp = await lambda
    .invoke({
      FunctionName: process.env.MY_FUNCTION, // <------ here
      Payload: JSON.stringify({ foo: "bar" }),
    })
```
