### DISCUSSION TITLE
Missing "sns.topicName" setting (it needs to be provided if "sns.arn" is not provided as plain ARN string)

### DISCUSSION THREAD

**Discussion by alakdam07** [serverless/serverless#10930] [Q&A] [answered]
I exported my `Sns` event to one cloud stack and trying to import the value to another stack. In local environment, it works as expected. When I pushed my code in `git`, it failed in my `CD/CI` pipeline. It says:

> Missing "sns.topicName" setting (it needs to be provided if "sns.arn" is not provided as plain ARN string)

 I sharing minimal yaml code. 

**PS: This Yaml has invalid syntax. In my case, I would like to know how to use imported sns**
```

service: my-imported-task

frameworkVersion: 2.66.0
useDotenv: true # needed by serverless offline
variablesResolutionMode: 20210326 #It's recommended to expose all errors for unresolved variables
unresolvedVariablesNotificationMode: error

provider:
  name: aws
  runtime: nodejs14.x # NOTE: or-tools (native dependency) is pre-built with nodejs12.x, if we change this it must be re-built
  region: eu-west-1
  memorySize: 2048
  stage: ${opt:stage}
  endpointType: ${self:custom.environmentConfig.endpointType}
  versionFunctions: false
  timeout: 30
  tracing:
    lambda: true
  deploymentBucket:
    blockPublicAccess: true
  apiGateway:
    minimumCompressionSize: 1024
    binaryMediaTypes:
      - 'application/pdf'
      - 'image/png'
  environment:
    MY_SNS:
      'Fn::ImportValue': ${self:custom.environmentConfig.mysns}  // Getting the value based on stage


  custom:
   serverlessIfElse:
    - If: '"${self:provider.stage}" != "test"'
      Exclude:
        - functions.start-picking-integration-test
        - functions.create-picking-test-run
   contentCompression: 1024
   environmentConfig:
    test:
      mysns: my-imported-sns-${self:provider.stage} // this my imported sns event name from another cloud formation stack
    qa:
      mysns: my-imported-sns-${self:provider.stage}
    production:
    isDevStage: 'false'
      mysns: my-imported-sns-${self:provider.stage}
    __development:
      mysns: my-imported-sns-${self:provider.stage}

    # Resolved values
    mysns:
      ${self:custom.environmentConfig.${self:provider.stage}.mysns,
      self:custom.environmentConfig.__development.mysns}

 functions:
   my-sns-listener-sns:
    handler: src/functions/urbantz-webhook-listener-sns.handler
    events:
      - sns:
          arn: ${self:provider.environment.MY_SNS} //IN HERE I AM GETTING THE ERROR MESSAGE
    iamRoleStatements:
      - Effect: Allow
        Action: sns:Subscribe
        Resource: ${self:provider.environment.MY_SNS}
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          - 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}*'

```
