### DISCUSSION TITLE
Serverless Deploy using different aws user

### DISCUSSION THREAD

**Discussion by nethkenn** [serverless/serverless#10952] [Q&A]
Hello, I'm trying to deploy a laravel app. I encountered an error saying 

`User: arn:aws:iam::123213213:user/account is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:ap-southeast-1:850626432431:stack/laravel-dev/* because no identity-based policy allows the cloudformation:DescribeStacks action`.

 I already changed the default profile credentials with different account and assigned `AdministratorAccess` for the permission but it's not working. Same old account is displayed when deploying. It's like that the account is already cached.

Tried Solutions:

1. Create a different profile in AWS and specify it in serverless.yml (with Administrator access)
2. Set an environment variable for the user (with Administrator access)

**Comment by pgrzesik** [comment]
Hey @nethkenn - how are you running the `sls deploy` command? Are you specifying the profile somehow? Maybe it's configured in your serverless configuration file?

**Reply by nethkenn** [reply]
Hello @pgrzesik,

Here's the part of my serverless.yml, as you can see i specified an aws profile but still the profile shown on the error is using the default profile.
```
provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: ap-southeast-1
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    profile: serverless
    runtime: provided.al2
    lambdaHashingVersion: 20201221

```

Version:

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              15.8.0
     Framework Version:         2.20.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.5.1
```

I solved it by running,` serverless deploy --aws-profile serverless`, thank you.
