### DISCUSSION TITLE
AWS Lambda with http api gateway always return forbidden in China

### DISCUSSION THREAD

**Discussion by goforu** [serverless/serverless#10958] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I deployed a simple function as follow
```javascript
"use strict";

module.exports.hello = async (event) => {
  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: "Go Serverless v3.0! Your function executed successfully!",
        input: event,
      },
      null,
      2
    ),
  };
};
```
endpoint always return {"message":"Forbidden"}

### Service configuration (serverless.yml) content

```yaml
service: payment
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: cn-northwest-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
```

### Command name and used flags

sls deploy

### Command output

```shell
Deploying payment to stage dev (cn-northwest-1)

✔ Service deployed to stack payment-dev (40s)

endpoint: GET - https://tbajkiy7g0.execute-api.cn-northwest-1.amazonaws.com.cn/
functions:
  hello: payment-dev-hello (1.8 kB)
```

### Environment information

```shell
SLS_GEO_LOCATION=us
```
