### DISCUSSION TITLE
Circular dependency when using Cognito::UserPool lambda triggers and accessing the pool client ID in an environment variable

### DISCUSSION THREAD

**Discussion by tibbe** [serverless/serverless#10981] [Q&A]
I need to pass the user pool client ID to the lambda function that handle my HTTP request (so they can call Python SDK function that require this ID). However since the `functions` section contains both lambda functions that need the user pool client ID and lambda functions used as user pool triggers this creates a circular dependency as I can't tell Serverless to only pass the environment variable to a group of lambda functions but not all (without manually passing it to every single one). My setup:

Need to pass the user pool client ID to the Python code somehow:
```yaml
provider:
  environment:
    USER_POOL_CLIENT_ID: !Ref AppCognitoUserPoolClient
```

Functions that need the user pool client ID:

```yaml
functions:
  SignUpOrSignIn:
    handler: handler.unauthorized_api.sign_up_or_sign_in
    events:
      - httpApi:
          path: /sign_up_or_sign_in
          method: post
  # Many more...
```

and functions defined as triggers for the user pool:

```yaml
  PreSignUp:
    handler: handler.cognito.pre_sign_up
  DefineAuthChallenge:
    handler: handler.cognito.define_auth_challenge
  CreateAuthChallenge:
    handler: handler.cognito.create_auth_challenge
  VerifyAuthChallenge:
    handler: handler.cognito.verify_auth_challenge
```

Finally the user pool and its client:

```yaml
resources:
  Resources:
    AppCognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: App-${sls:stage}
        # ...
        LambdaConfig:
          PreSignUp:
            Fn::GetAtt: [PreSignUpLambdaFunction, Arn]
          DefineAuthChallenge:
            Fn::GetAtt: [DefineAuthChallengeLambdaFunction, Arn]
          CreateAuthChallenge:
            Fn::GetAtt: [CreateAuthChallengeLambdaFunction, Arn]
          VerifyAuthChallengeResponse:
            Fn::GetAtt: [VerifyAuthChallengeLambdaFunction, Arn]
    AppCognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: App-${sls:stage}
        GenerateSecret: false
        UserPoolId:
          Ref: "AppCognitoUserPool"
```

So the problem here is that either you put an environment variables at the `provider` level, which includes the variable for every function and causes a circular dependency, or you provide it manually for every function that needs it, which is error prone.

I kinda wish I could have two `functions` sections and one `environment` config that spans only one of them.
