### DISCUSSION TITLE
Facing problem to set service name from env variable in serverless.yml file after upgrading to latest version

### DISCUSSION THREAD

**Discussion by aniamin** [serverless/serverless#10980] [Q&A]
I am trying to set the serverless service name from the env file. Before deploying serverless, I have set the value of ECR_NAME as
```
export ECR_NAME=$(echo $CI_ENVIRONMENT_SLUG | awk -v srch="-" -v repl="" '{ gsub(srch,repl,$0); print $0 }')
```
Then I have tried to use the value of **ECR_NAME** env variable as below:

> service: ${env:CI_PROJECT_NAME}-${env:ECR_NAME}
> 
> useDotenv: true
> configValidationMode: error
> variablesResolutionMode: 20210326
>  

Getting below error while deploying...

> Error:
> Cannot resolve serverless.yml: "service" property is not accessible (configured behind variables which cannot be resolved at this stage)

Installed version:
```
Framework Core: 3.14.0
Plugin: 6.2.1
SDK: 4.3.2
```

I want to set the service name dynamically. Can I do it in the serverless framework version 2 and using variablesResolutionMode: 20210326

Please suggest. Thanks in advanced.

**Comment by pgrzesik** [comment]
Hello @aniamin - could you share how the `CI_PROJECT_NAME` env var is populated? Is it loaded thanks to `useDotenv`?

**Reply by aniamin** [reply]
Hello @pgrzesik 
Thanks for your reply.

CI_PROJECT_NAME is a gitlab environment variable. We are executing serverless deployment from a gitlab-ci.yml file where the environment is already loaded as environment variable. How can I check if it is loaded?

**Reply by pgrzesik** [reply]
I've tried to replicate your issue on the latest Framework version (3.14.0) and it seems to work without issues - for a config like this

```
service: ${env:ANOTHER}-service-${env:TEST}
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
```

This is the output of `ANOTHER=test TEST=123 sls print` (so the resolved config):

```
service: test-service-123
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  versionFunctions: true
```

Could you share what is the actual value of both environment variables at the time you're running the command? Are both of them defined?
