### DISCUSSION TITLE
Mixing Cognito authorizer and Flask

### DISCUSSION THREAD

**Discussion by tibbe** [serverless/serverless#10992] [Q&A]
Context:
- Python Flask provides a nice way to move routing out of the serverless.yml file into a format that scales better with a large number of functions. It also makes it easier to move your app to another backend (such as running your own HTTP server in an EC2 instance).
- `provider.httpApi.authorizers` provides a nice way to let the AWS Api Gateway and Cognito validate your JWTs without involving your Lambda functions (i.e. the handler will only be called after the JWT has been validated by Cognito).

I'm trying to figure out the best way to mix the two. To use Flask it's recommended to do:

```yaml
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
```

However, since the authorizer is set up using `functions.<function name>.events.httpApi.authorizer` and we only want the authorizer for the part of our API (e.g. for functions requiring authorization but not for functions handling login) using a catch-all doesn't work as well. How can devise a setup for using both Flask and authorizers (for a subset of the API)? Something like:

```yaml
provider:
  httpApi:
    authorizers:
      cognitoJwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - ${self:provider.region}
              - ".amazonaws.com/"
              - !Ref AppCognitoUserPool
        audience:
          - !Ref AppCognitoUserPoolClient

functions:
  unauthorized_api:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /unauthorized/{proxy+}
          method: ANY
  authorized_api:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /authorized/{proxy+}
          method: ANY
          authorizer:
            name: cognitoJwtAuthorizer
```
