### DISCUSSION TITLE
SSM variable not retrieved when using npx

### DISCUSSION THREAD

**Discussion by ryanoolala** [serverless/serverless#10993] [Q&A]
Hi guys, i'm encountering this weird behaviour that i do not understand.

## Setup
```bash
> sls --version
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.72.3 (local)
Plugin: 5.5.4
SDK: 4.3.2
Components: 3.18.2

> npx sls --version
Framework Core: 2.72.3 (local)
Plugin: 5.5.4
SDK: 4.3.2
Components: 3.18.2
```

```yml
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'offline'}
  region: ap-southeast-1
  environment:
    NAME:${ssm:/server/env, ''}
```

## Issue

Whenever i try to do package/deploy i noticed that my SSM environment variable will not be retrieved whenever i use `npx`  

```bash
> SLS_DEBUG=* sls package --stage xx
...
Serverless: [AWS ssm 400 0.174s 0 retries] getParameter({
  Name: '/server/env',
  WithDecryption: true
})

> SLS_DEBUG=* npx sls package --stage xx

Serverless Warning --------------------------------------
 
  A valid SSM parameter to satisfy the declaration 'ssm:/server/env' could not be found.

...

```

in the `npx` instance, there is no `getParameter` log. this results in the final environment being the default empty string even though in the non `npx` version it can retrieve the parameter successfully
