### DISCUSSION TITLE
Deploying a function with a different runtime

### DISCUSSION THREAD

**Discussion by jaipili1401** [serverless/serverless#11032] [General]
I'm using this framework to deploy multiple Lambda functions in which all of them runs on NodeJS. Now, I need to create a new Lambda function that runs on Java11 and I want its configuration to be in the same YAML file along with my NodeJS Lambda functions. My Java code(jar file) is uploaded to an S3 bucket and I'm referencing that bucket in my Java Lambda function to fetch the package and deploy it as the function's code, however, it seems like a wrong package is being deployed to my Lambda as I noticed that the file size is larger than the actual size of my JAR file. Therefore, when I run my lambda function it fails as it cannot find the handler due to incorrect package deployed. I verified it by uploading manually the JAR file to my Java Lambda function and it worked.

Below is the code snippet of my Serverless YAML file:
```
---
service: api

provider:
  name: aws
  stackName: ${self:custom.prefix}-${opt:stage}-${self:service.name}
  runtime: nodejs14.x
  stage: ${opt:custom_stage, opt:stage}
  tracing:
    lambda: Active
  timeout: 30
  logRetentionInDays: 180
  environment:
    STAGE: ${opt:stage, opt:stage}
    ENVIRONMENT: ${self:provider.stage}
    SUPPRESS_NO_CONFIG_WARNING: true
    ALLOW_CONFIG_MUTATIONS: true
    
functions:
  sample-node-function-1:
    role: arn:aws:iam::#{AWS::AccountId}:role/${self:custom.prefix}-${self:provider.stage}-sample-function-1
    name: ${self:custom.prefix}-${opt:stage}-sample-function-1
    handler: authorizers/handler.authHandler1

  sample-node-function-2:
    role: arn:aws:iam::#{AWS::AccountId}:role/${self:custom.prefix}-${self:provider.stage}-sample-function-2
    name: ${self:custom.prefix}-${opt:stage}-sample-function-2
    handler: authorizers/handler.authHandler2

  myJavaFunction:
    role: arn:aws:iam::#{AWS::AccountId}:role/${self:custom.prefix}-${self:provider.stage}-myJavaFunction-role
    name: ${self:custom.prefix}-${opt:stage}-myJavaFunction
    runtime: java11
    package:
      artifact: s3://myBucket/myJarFile.jar
    handler: com.myFunction.LambdaFunctionHandler
    memorySize: 512
    timeout: 900
```

How can I deploy the correct package to my Lambda function by fetching the JAR file from S3 bucket?
