### DISCUSSION TITLE
SQS does not throw error and dead letter queue does not work

### DISCUSSION THREAD

**Discussion by alakdam07** [serverless/serverless#11058] [Q&A]
I  have one Sns event which publish status of my order to one stack. I am using that SNS event to my picking order stack(diffrent stack) where I am listening that SNS event by SQS lambda event. I have trying many times throwing the error but seems like my SQS lambda event does not any throw error. I some how mange to throw error with my order status but I don't see any message to my Dead letter queue. Idk what I kind of stupid mistake I am doing. 

## Two issues:
-  I don't see throw new Error in cloud watch
- If error happen, why it's not showing to dead-letter-queue

## Ps: All the attachments seems alright

**This my yaml file**

```

service: payment

frameworkVersion: 3.16.0
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  memorySize: 2048
  stage: ${opt:stage}

custom:
  contentCompression: 1024
  environmentConfig:
    test:
      paymentEventSnsArn: arn:aws:sns:${aws:region}:${aws:accountId}:payments-${self:provider.stage}-payment-update-stream
    qa:
      paymentEventSnsArn: arn:aws:sns:${aws:region}:${aws:accountId}:payments-${self:provider.stage}-payment-update-stream
    production:
      paymentEventSnsArn: arn:aws:sns:${aws:region}:${aws:accountId}:payments-${self:provider.stage}-payment-update-stream
      endpointType: 'REGIONAL'
      sendAnalyticsTo: 'kafka'
    __development:
      paymentEventSnsArn: arn:aws:sns:${aws:region}:${aws:accountId}:payments-test-payment-update-stream
      endpointType: 'REGIONAL'
      sendAnalyticsTo: 'none'

    # Resolved values

    paymentEventSnsArn: ${self:custom.environmentConfig.${self:provider.stage}.paymentEventSnsArn,
      self:custom.environmentConfig.__development.paymentEventSnsArn}

  logRetentionInDays: ${self:custom.environmentConfig.logRetentionInDays}
  serverless-offline:
    httpPort: 4027
    noPrependStageInUrl: true
    useChildProcesses: true
    useWorkerThreads: true
  customDomain:
    enabled: ${self:custom.environmentConfig.${self:provider.stage}.createCustomDomain, self:custom.environmentConfig.__development.createCustomDomain}
    basePath: ''
    domainName: ${self:custom.apiPath.${opt:stage, self:provider.stage}, self:custom.apiPath.other}
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: true
  serverless-iam-roles-per-function:
    defaultInherit: true

package:
  individually: true
  include:
    - openapi/generated
    - src/assets/*

functions:
  update-status:
    handler: src/functions/update-status.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - PaymentStatusQueue
              - Arn

  Resources:
    PaymentStatusQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-status-queue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt PaymentStatusDlq.Arn
          maxReceiveCount: 1

    PaymentStatusDlq:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-status-queue-dlq

    PaymentsCaptureQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: PaymentStatusQueue
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: Allow-SNS-SendMessage
              Effect: Allow
              Principal: '*'
              Action: SQS:SendMessage
              Resource: !GetAtt PaymentStatusQueue.Arn
              Condition:
                ArnEquals:
                  aws:SourceArn: ${self:custom.environmentConfig.paymentEventSnsArn}

    ## Sns subscription
    PaymentsStatusSnsSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: ${self:custom.environmentConfig.paymentEventSnsArn} ## sns topic name
        Endpoint: !GetAtt PaymentStatusQueue.Arn ## Sqs topic
        Protocol: sqs
        RawMessageDelivery: 'true'
```

**This is my SQS lambda event**

```

import { PaymentStreamSnsMessage } from 'status/types/sns'
import { SQSEvent } from 'aws-lambda'

const paymentStreamSnsMessageHandler = async (message: PaymentStreamSnsMessage): Promise<void> => {
  throw new Error(`Throw error ${message}`)
}

export const handlerFn = (event: SQSEvent): Promise<PromiseSettledResult<void>[]> => {
  return Promise.allSettled(
    event.Records.map((record) => JSON.parse(record.body) as PaymentStreamSnsMessage).map(
      paymentStreamSnsMessageHandler,
    ),
  )
}

export const handler = handlerFn
```
