### DISCUSSION TITLE
How would i assume a role?

### DISCUSSION THREAD

**Discussion by samsen1** [serverless/serverless#11062] [Q&A]
We want to be able to deploy serverless via our self hosted runners using Github Actions. Our runners run in one account and we want to be able to deploy to other accounts (e.g. dev, staging and prod). Each environment reside in their own AWS account. As a test, i created a role/policy in our dev account but I'm encountering an error that shows the following:

```
User: arn:aws:sts::<ACCOUNT_ID_GH_RUNNERS>:assumed-role/<ROLE>/c382a7d48148456baecac78556315651 is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-east-1:<ACCOUNT_ID_GH_RUNNERS>:stack/service-name-dev/*
```

As noted above, it's trying to create the resources within the account where the Github Runners are located and not in the intended environment (dev). I can't for the life of me figure out how to make it use the role I specify. See below

```
service: serverless-alert-notifier

plugins:
  - serverless-plugin-datadog
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  iam:  
    role: arn:aws:iam::<ACCOUNT_ID_DEV>:role/<ROLE_TOASSUME>

```

**Comment by pgrzesik** [comment]
Hello @samsen1 - the `iam.role` setting is for setting the role that will be used by your deployed Lambda functions. If you want to use different role during actual deployment, you should be using `provider.iam.deploymentRole`.

**Reply by samsen1** [reply]
I tried that as well, sorry I didn't mention that in my original msg. I get the same error ...

```
service: serverless-alert-notifier

plugins:
  - serverless-plugin-datadog
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  iam:  
    deploymentRole: arn:aws:iam::<ACCOUNT_ID_DEV>:role/<ROLE_TOASSUME>
 ```
