### DISCUSSION TITLE
Does serverless provider environment support Cloudformation intrinsic functions?

### DISCUSSION THREAD

**Discussion by saraiyakush** [serverless/serverless#11072] [Q&A] [answered]
I am trying to use Cloudformation Mappings to define the provider's environment variables inside a serverless file.

I came across this documentation and it looks like serverless does not support it. Is that correct?
https://www.serverless.com/framework/docs/providers/aws/guide/variables#aws-cloudformation-pseudo-parameters-and-intrinsic-functions

Here is my snippet to help understand what I am trying to achieve.

```yml
service: test

provider:
  name: aws
  environment:
    REGION: !FindInMap [ EnvironmentVariables, "${opt:stage}" , REGION ]

resources:
  Parameters:
    TargetEnvironment:
      Type: String
      AllowedValues:
        - dev
        - staging
        - prod
  Mappings:
    EnvironmentVariables:
      dev:
        REGION: ap-southeast-2
      staging:
        REGION: ap-southeast-1
      prod:
        REGION: ap-southeast-3
```
Output from `sls package --stage dev`:
```bash
Running "serverless" from node_modules
Serverless: Configuration warning at 'provider.environment.REGION': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Packaging service...

```

**Comment by pgrzesik** [comment, marked as answer]
Hello @saraiyakush - yes, the CF intrinsic functions are supported, but e.g. the FindInMap that you're trying to use is not supported by the schema for `environment` and would have to be added in a PR. However, there's a bigger problem with what you're trying to achieve:
1. `resources` section extends the `Resources` section of the underlying CloudFormation template - so the `Mappings` or `Parameters` won't be recognized properly as they should be adjacent to `Resources` in the CF template
2. Even if that would work, how are you going to pass parameter to CF?

Maybe what you're trying to do here is possible to address with native feature of the Framework - stage parameters - https://www.serverless.com/framework/docs/guides/parameters#stage-parameters?

**Reply by saraiyakush** [reply]
Thanks @pgrzesik for the quick response and thanks for sharing the native feature of stage parameters. Yes, I think it might solve my purpose.

As to your question about how to pass parameter to CF - I was going to make use of stage variable from serverless cli i.e. ${opt:stage}.

**Reply by saraiyakush** [reply]
I tried to use the `params` section to define my parameters but as soon as I do that, serverless cli asks me for login. Is that expected?
```yml
service: test

provider:
  name: aws
  environment:
    REGION: ${param:REGION}

params:
  dev:
    REGION: ap-southeast-2
  staging:
    REGION: ap-southeast-1
  prod:
    REGION: ap-southeast-3

```
```bash
serverless package --stage dev
Running "serverless" from node_modules
 
 Serverless Error ----------------------------------------
 
  You are not currently logged in. To log in, use: $ serverless login
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.19.0
     Framework Version:         2.30.3 (local)
     Plugin Version:            4.5.2
     SDK Version:               4.2.2
     Components Version:        3.18.2

```
