### DISCUSSION TITLE
Lambda ZIP files are quite a bit larger after upgrading from 2.X to 3.X

### DISCUSSION THREAD

**Discussion by joshdura** [serverless/serverless#11078] [Q&A]
After upgrading from 2.37.2 to 3.2.1, one of my function deploys is failing due to a lambda size restriction. After researching this, I noticed that my ZIP file for this specific function is quite a bit larger (old was 57.2 MB, new is 79.3 MB). I looked through and noticed that the `sharp` library in node_modules is almost tripled in size. See the screenshot below (2.37.2 compile on the left, 3.2.1 on the right):

<img width="1850" alt="image" src="https://user-images.githubusercontent.com/72485/168449389-1e072e65-5774-4225-a5ce-136b4b1bdbf8.png">

It looks like the dependency is compiled/installed differently, but I haven't changed my Node target at all, and the error output shows exactly the same between the two deploys with only the Serverless version being different. See the screenshot below for the lib differences in the dependency:

<img width="1852" alt="image" src="https://user-images.githubusercontent.com/72485/168449416-37ace4d1-77fb-4acc-ab31-65f24d867577.png">

Is there anything that changed in the 3.X release that could have caused this? Literally nothing else has changed outside of the Serverless version and the necessary deprecation changes needed for a 2 > 3 update.

**Comment by pgrzesik** [comment]
Hey @joshdura - Framework shoudn't have any impact on how things are getting installed into your `node_modules`. Are you sure you didn't update the library in the process or maybe upgraded npm or Node version?

**Reply by joshdura** [reply]
@pgrzesik I thought the same thing and triple checked this on both my local machine and in the docker image this gets run on in CI/CD. Nothing changed, it’s still running node 12.13-alpine. Has the library that serverless uses to compress the files changed at all?

**Reply by pgrzesik** [reply]
It should not - what is the installation type that you're using for `serverless`?

**Reply by joshdura** [reply]
@pgrzesik Not 100% sure what you mean by installation type, but here is the `serverless.yml` without all of our functions:

```
service: emr-services
configValidationMode: error

plugins:
    - serverless-webpack
    - serverless-offline-sqs
    - serverless-offline
    - serverless-domain-manager
    - serverless-plugin-split-stacks
    - serverless-prune-plugin
    - serverless-plugin-lambda-insights

package:
    individually: true
    excludeDevDependencies: true

custom:
    stages:
        - local
        - pro
    serverless-offline:
        host: 0.0.0.0
        httpPort: 3001
        useWorkerThreads: true
        noPrependStageInUrl: true
        apiKey: abc123
    serverless-offline-sqs:
        autoCreate: true
        endpoint: http://sqs:9324
        region: ${self:provider.region}
        accessKeyId: root
        secretAccessKey: root
    lambdaInsights:
        defaultLambdaInsights: true
    customDomain:
        domainName: ${file(./serverless-variables.${self:provider.stage}.yml):customDomain}
        basePath: 'api'
    splitStacks:
        perFunction: true
        perType: false
        perGroupFunction: false
    prune:
        automatic: true
        number: 10
    webpack:
        webpackConfig: './webpack.config.js'
        includeModules:
            nodeModulesRelativeDir: '../../'
            forceExclude:
                - aws-sdk
                - chrome-aws-lambda
        packager: 'yarn'
        packagerOptions:
            noFrozenLockFile: true

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    stage: ${opt:stage,'local'}
    memorySize: 1024
    timeout: 30
    apiGateway:
        apiKeys:
            - vitals-ingest-${opt:stage,'local'}
        minimumCompressionSize: 1024 # Enable gzip compression for responses > 1KB
    iam:
        role:
            statements:
                - Effect: 'Allow'
                  Action:
                      - 'secretsmanager:GetRandomPassword'
                      - 'secretsmanager:GetResourcePolicy'
                      - 'secretsmanager:GetSecretValue'
                      - 'secretsmanager:DescribeSecret'
                      - 'secretsmanager:ListSecretVersionIds'
                      - 'sqs:SendMessageBatch'
                      - 'sqs:SendMessage'
                      - 's3:PutObject'
                      - 's3:PutObjectAcl'
                      - 's3:GetObject'
                      - 's3:ListBucket'
                      - 'lambda:InvokeFunction'
                      - 'dynamodb:Query'
                      - 'dynamodb:Scan'
                      - 'dynamodb:UpdateItem'
                      - 'timestream:DescribeEndpoints'
                      - 'timestream:WriteRecords'
                      - 'timestream:Select'

                  Resource: '*'
    environment:
        GRAPHIUM_AWS_REGION: ${self:provider.region}
        GRAPHIUM_ENV: ${self:provider.stage}
    vpc:
        securityGroupIds:
            - ${file(./serverless-variables.${self:provider.stage}.yml):vpcSecurityGroupId}
        subnetIds:
            - ${file(./serverless-variables.${self:provider.stage}.yml):vpcSubnetA}
            - ${file(./serverless-variables.${self:provider.stage}.yml):vpcSubnetB}
```
