### DISCUSSION TITLE
AccessDenied  on lambda:invokeFunction - 2 different lambda roles in IAM

### DISCUSSION THREAD

**Discussion by bronzeson** [serverless/serverless#11099] [Q&A]
I am getting AccessDenied when trying to invoke a lambda function from my code. 

A snippet of my serverless.yml looks like this 

```
functions:
  checkItems:
    handler: src/check_items.check_items
    events:
      - schedule: 
          rate: rate(${self:custom.jobRate.${self:provider.stage}})
          enabled: ${self:custom.enabled.${self:provider.stage}}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource: ${cf:UserStatsService-${self:provider.stage}.CalculateUserStatsLambdaFunctionQualifiedArn}
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:us-west-2:${self:custom.common.dynamo_arn.${self:provider.stage}}:table/RPAll-${self:provider.stage}/index/GSI1-index

plugins:
  - serverless-iam-roles-per-function

```

That query function is working just fine in my code. But the lambda invocation gets access denied. What's weird is I can see two different IAM roles in AWS.

They are
{servicename}-{stage}-{functionname}-us-west-2
{servicename}-{stage}-us-west-2-lambdaRole

The first one has all of the role statements that I had defined, including the query and the lambda:invokeFunction. The query works correctly in the code. But the lambda invocation throws AccessDenied error.

The second one (with "lambdaRole") just has some log allow statements in it. But what is weird is that when I manually add a  lambdaInvoke allow statement, the AccessDenied exception goes away.

So it looks like to me that the lambda invocation from the code is for some reason using that other role, but it should be using the role with the function name in it. 

Any idea? Thanks in advance!
