### DISCUSSION TITLE
Configuring UserPoolClient generates lots of errors

### DISCUSSION THREAD

**Discussion by johnsoukka** [serverless/serverless#11104] [General]
I have the use case of creating a AWS Cognito user pool companioned by a user pool client.

In my `Serverless.yml` I have (among other specifications) this section which creates the user pool client:

```
UserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      AccessTokenValidity: 30
      ClientName: ${self:custom.userPoolName}-client
      EnableTokenRevocation: true
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      IdTokenValidity: 30
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 10
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      UserPoolId: !Ref CognitoUserPoolMyPool
```

`AccessTokenValidity`, `EnableTokenRevocation`, `IdTokenValidity`, `PreventUserExistenceErrors` and `TokenValidityUnits` are all highlighted as errors since they are not supported by [this specification](https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/reference.json) (is my conclusion).

Why is that? All other properties seems fine. Everything is created properly in AWS as far as I can see so it is not a problem from that perspective.

The alternatives I see is:
1. The errors are noise which is undesirable since it tends to hide other real errors. How can I suppress them?
2. They are in fact something I should act on. What would these actions be?
