### DISCUSSION TITLE
Code 125 on Running docker run --rm -v /root/.cache/serverless-python-requirements/

### DISCUSSION THREAD

**Discussion by vteran93** [serverless/serverless#11116] [Q&A]
Hi, this one is my first experience with the serverless framework and looks like I am doing something wrong setting a Docker Image for the python Requirements plugin. 
This is the section where I am setting up the dependencies.

```yaml
.
.
.
frameworkVersion: ^2.35.0
configValidationMode: error
custom:
  wsgi:
    app: great_control.wsgi.application
  pythonRequirements:
    dockerImage: **********.dkr.ecr.us-east-2.amazonaws.com/some-dependencies:${ENVIRONMENT}
    dockerizePip: true
    usePoetry: false
  prune:
    automatic: true
    number: 5
provider:
  name: aws
  stage: ${opt:stage, 'develop'}
  runtime: python3.8
```
And this it's the error that I am getting (it's running inside a circleci pipeline)

```bash
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Using Python specified in "runtime": python3.8
Serverless: Packaging Python WSGI handler...
Serverless: Generated requirements from /root/project/requirements.txt in /root/project/.serverless/requirements.txt...
Serverless: Installing requirements from /root/.cache/serverless-python-requirements/a2ea73dc49988805a15c032f014bf5554e49fa57a518148e4d4f91a35befaeb7_x86_64_slspyc/requirements.txt ...
Serverless: Docker Image: *********.dkr.ecr.*********.amazonaws.com/******-dependencies:${ENVIRONMENT}
Serverless: Using download cache directory /root/.cache/serverless-python-requirements/downloadCacheslspyc
Serverless: Running docker run --rm -v /root/.cache/serverless-python-requirements/a2ea73dc49988805a15c032f014bf5554e49fa57a518148e4d4f91a35befaeb7_x86_64_slspyc\:/var/task\:z -v /root/.cache/serverless-python-requirements/downloadCacheslspyc\:/var/useDownloadCache\:z 500345361576.dkr.ecr.*********.amazonaws.com/great-control-dependencies:\$\{ENVIRONMENT\} /bin/sh -c 'chown -R 0\\:0 /var/useDownloadCache && python3.8 -m pip install -t /var/task/ -r /var/task/requirements.txt --cache-dir /var/useDownloadCache && chown -R 0\\:0 /var/task && chown -R 0\\:0 /var/useDownloadCache'...
Serverless: [AWS sts 200 0.056s 0 retries] getCallerIdentity({})
 
 Error ---------------------------------------------------
 
  Error: `docker run --rm -v /root/.cache/serverless-python-requirements/a2ea73dc49988805a15c032f014bf5554e49fa57a518148e4d4f91a35befaeb7_x86_64_slspyc:/var/task:z -v /root/.cache/serverless-python-requirements/downloadCacheslspyc:/var/useDownloadCache:z *************.dkr.ecr.*********.amazonaws.com/great-control-dependencies:${ENVIRONMENT} /bin/sh -c chown -R 0\:0 /var/useDownloadCache && python3.8 -m pip install -t /var/task/ -r /var/task/requirements.txt --cache-dir /var/useDownloadCache && chown -R 0\:0 /var/task && chown -R 0\:0 /var/useDownloadCache` Exited with code 125
      at ChildProcess.<anonymous> (/root/project/node_modules/child-process-ext/spawn.js:38:8)
      at ChildProcess.emit (node:events:394:28)
      at ChildProcess.emit (node:domain:475:12)
      at maybeClose (node:internal/child_process:1064:16)
      at Socket.<anonymous> (node:internal/child_process:450:11)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at Pipe.<anonymous> (node:net:672:12)
```

Someone could give some advice about what am I doing wrong? The image referenced in the `dockerImage` variable was properly created and loaded to ECR with the following content:

```
FROM lambci/lambda:python3.8
USER root
COPY pyproject.toml .
COPY poetry.lock .
RUN pip install poetry
RUN poetry check && poetry export -f requirements.txt -o requirements.txt --without-hashes && poetry run pip install -r requirements.txt

```
