### DISCUSSION TITLE
Unable to implement request type lambda authorization in serverless framework

### DISCUSSION THREAD

**Discussion by kiriti999** [serverless/serverless#11128] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

How to implement request type lambda authorizer in serverless framework?

I haven't been able to implement the same in serverless framework compared to aws sam.

I always get 403 forbidden all the time. Here's the [github code](https://github.com/kiriti999/api-gateway-request-auth.git)

Serverless URL: [https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/hello?auth=yes](https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/auth=yes)
Sam URL: [https://7jjym0ms9g.execute-api.ap-southeast-2.amazonaws.com/dev/hello?auth=yes](https://7jjym0ms9g.execute-api.ap-southeast-2.amazonaws.com/dev/hello?auth=yes)

You can test both the URL's above and sam url is working as expected and other one returns 403 always

Serverless template:

```
service: sls-api-gateway-request-auth
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  timeout: 30

functions:
  authFunction:
    handler: ./auth.lambda_handler

  backendFunction:
    handler: ./backend.lambda_handler
    runtime: nodejs14.x
    events:
      - http:
          method: get
          cors: true
          path: /auth
          authorizer:
            name: authFunction
            type: request

  Outputs:
    MyApiAuth:
      Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
      Value: !Sub "https://{sls:instanceId}.execute-api.${AWS::Region}.amazonaws.com/dev/hello?auth=yes"
```

Here's the SAM template which is working fine:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt authFunction.Arn
            Identity:
              QueryStrings:
                - auth
              ReauthorizeEvery: 100

  backendFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: backend.lambda_handler
      Runtime: nodejs10.x
      CodeUri: .
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: GET

  authFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: auth.lambda_handler
      Runtime: nodejs10.x

Outputs:
  ApiUrl:
    Description: "API endpoint URL"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/hello?auth=yes'
```

### Service configuration (serverless.yml) content

```yaml
service: sls-api-gateway-request-auth
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  timeout: 30

functions:
  authFunction:
    handler: ./auth.lambda_handler

  backendFunction:
    handler: ./backend.lambda_handler
    runtime: nodejs14.x
    events:
      - http:
          method: get
          cors: true
          path: /auth
          authorizer:
            name: authFunction
            type: request

resources:
  Resources:
  Outputs:
    MyApiAuth:
      Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
      Value: !Sub "https://{sls:instanceId}.execute-api.${AWS::Region}.amazonaws.com/dev/hello/auth?apiKey=yes"
```

### Command name and used flags

sls deploy

### Command output

```shell
endpoint: GET - https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/auth                                                           
functions:
  authFunction: sls-api-gateway-request-auth-dev-authFunction (2.1 kB)                                                                         
  backendFunction: sls-api-gateway-request-auth-dev-backendFunction (2.1 kB)
```

### Environment information

```shell
Framework Core: 3.18.2
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hey @kiriti999 - this does not look like a bug but rather a problem with implementation - I'm moving it to discussions

**Reply by kiriti-iselect** [reply]
@pgrzesik Not sure what is the problem with implementation? I don't see an example of `REQUEST` type authorizer in REST API V1 and the implementation is not working in serverless and working with SAM. Could you shed some light on the issue?

**Reply by pgrzesik** [reply]
Hey @kiriti-iselect - when configuring custom authorizers, by default the Identity Source is set to `identitySource: method.request.header.Authorization` - if Authorization header will be missing then it will be outright rejected by API Gateway, before even trying to call your custom authorizer. If you want to use different identity source, you have to override it e.g. in your case to use value from querystring

**Reply by kiriti999** [reply]
@pgrzesik Even after setting the `identitySource: method.request.querystring.auth`, its still the same issue. Check here: [https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/hello](https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/hello)

**Reply by pgrzesik** [reply]
I've called it with https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/hello?auth=yes and it worked without issues for me

**Reply by kiriti999** [reply]
@pgrzesik Please test in postman. Its either 401 or 500 with query string. I don't see any cloudwatch logs either

**Reply by pgrzesik** [reply]
I see, it now returns 500 for me too - did you check the API Gateway logs and/or logs for both Lambda functions? Are you sure they're not failing in any way? 

I've tested with such config and it works without issues

```
service: repro-auth

frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x

functions:
  authFunction:
    handler: ./auth.lambda_handler

  backendFunction:
    handler: ./backend.lambda_handler
    events:
      - http:
          method: get
          path: /auth
          authorizer:
            name: authFunction
            type: request
```

**Reply by pgrzesik** [reply]
Please note that `{sls:instanceId}` is not the ID of the API Gateway

**Reply by kiriti999** [reply]
@pgrzesik thanks for your help. I have finally figured out the issue that lambda permissions were missing but one last thing I want to know is how do I refer to lambda function in same template?
In my case I want to refer `authFunction` arn inside `ApiGatewayAuthorizer` as `AuthorizerUri`?
I tried `FunctionName: !GetAtt authFunction.Arn` but getting error:
`The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource authFunction`

**Reply by pgrzesik** [reply]
Could you please share the configuration of what you are trying to do? Why do you need to reference function directly via it's ARN? 

Here you can find naming convention for logical IDs of popular CF resources: https://www.serverless.com/framework/docs/providers/aws/guide/resources

**Reply by kiriti-iselect** [reply]
@pgrzesik  How do I refer the lambda arn from same template?
`{Function Name}{Cloud Formation Resource Type}{Resource Name}{SequentialID, instanceId or Random String}`
is it like this? 
`{Lambda::Function}{authFunctionLambdaFunction}{123}` ?

Also, there is another important issue that `apiKey` content is not being validated in `request` type lambda authorizer. It is just checking whether `apiKey` qurey string is present or not but not the content of the `apiKey`. How do I fix this?

**Reply by kiriti-iselect** [reply]
Here's the updated template:

 ```
 service: api-key-in-querystring-sls
  frameworkVersion: '3'
  configValidationMode: error

  provider:
    name: aws
    region: ap-southeast-2
    runtime: nodejs14.x
    timeout: 30
    stage: ${opt:stage}
    apiGateway:
      apiKeys:
        - value: ${opt:stage}-unbounce-api-key
      usagePlan:
        quota:
          limit: 5000
          offset: 2
          period: MONTH
        throttle:
          burstLimit: 200
          rateLimit: 100

  functions:
    MyAuthFunction:
      description: Extracts api key, authenticates against usage plan, allow/deny http methods and returns auth response object
      handler: ./auth.lambda_handler

    BackendFunction:
      handler: ./backend.lambda_handler
      runtime: nodejs14.x
      events:
        - http:
            method: post
            cors: true
            private: true
            path: /shortfunnel-health
            authorizer:
              name: MyAuthFunction
              type: request
              authorizerId:
                Ref: ApiGatewayAuthorizer

  resources:
    Resources:
      ApiGatewayAuthorizer:
        Type: AWS::ApiGateway::Authorizer
        Properties:
          AuthorizerResultTtlInSeconds: 300
          IdentitySource: method.request.querystring.apiKey
          Name: Authorizer
          RestApiId:
            Ref: ApiGatewayRestApi
          Type: REQUEST
          AuthorizerUri:
            Fn::Join: [ "",
              [
                "arn:aws:apigateway:",
                "ap-southeast-2",
                ":lambda:path/",
                "2015-03-31/functions/", "arn:aws:lambda:ap-southeast-2:327303463717:function:lambda_request_authorizer2",
                "/invocations"
              ]]

      GWAuthPermission:
        Type: "AWS::Lambda::Permission"
        Properties:
          Action: lambda:InvokeFunction
          FunctionName: arn:aws:lambda:ap-southeast-2:327303463717:function:lambda_request_authorizer2
          Principal: "apigateway.amazonaws.com"

    Outputs:
      MyApiHealth:
        Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
        Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${opt:stage}/shortfunnel-health?apiKey=dev-unbounce-api-key"
```
