### DISCUSSION TITLE
Cannot find module ?

### DISCUSSION THREAD

**Discussion by Cariaga** [serverless/serverless#11144] [Q&A] [answered]
- trying to run on aws lambda function

```
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
Require stack:
- /var/task/node_modules/sharp/lib/sharp.js
- /var/task/node_modules/sharp/lib/constructor.js
- /var/task/node_modules/sharp/lib/index.js
- /var/task/app.js
- /var/task/app/app
```
```

 "main": "app.js",
org: test
console: true
service: test
package:
  individually: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-1
  memorySize: 256
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
  
```
```

{
  "name": "proj",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",

  "Comment": "typescript is work but bugged on aws specifically lambda reverted to normal javascript while its not resolved",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node app.js"
  },
  "repository": {
    "type": "git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {},
  "dependencies": {
    "@types/node": "^17.0.41",
    "aws-serverless-koa": "^1.0.2",
    "esm": "^3.2.25",
    "koa": "^2.13.4",
    "serverless-http": "^3.0.1",
    "sharp": "^0.30.6",
    "svgson": "^5.2.1",
    "ts-node": "^10.8.1",
    "tslib": "^2.4.0",
    "typescript": "^4.7.3"
  }
}

```
