### DISCUSSION TITLE
Serverless deploy with new ElasticSearch/OpenSearch instance times out - extend security token period?

### DISCUSSION THREAD

**Discussion by GregAtFramework** [serverless/serverless#11159] [Q&A]
My `serverless.yml` is pretty simple - the whole of it is included below. It deploys a single OpenSearch instance.

Deploying new OpenSeach instances takes a long time. Something in Serverless is timing out after 15 minutes, which is before the CloudFormation stack has updated (which seems to take 16-17 minutes).

Is there a way to extend the security token period?

This doesn't hugely matter when deploying manually, but when deploying via a GitHub action, I would prefer a clean success or failure.

```
greg@Greg-MBP framework-search % sls deploy --stage greg3
Deploying framework-search to stage <stage> (eu-west-1, "framework-aws-provider" provider)

✖ Stack <service>-<stage> failed to deploy (905s)
Warning: Publication to Serverless Dashboard errored with:
            The security token included in the request is expired
Environment: darwin, node 16.15.0, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Credentials: Serverless Dashboard, "framework-aws-provider" provider (https://app.serverless.com/<org>/apps/<app>/<service>/<stage>/eu-west-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The security token included in the request is expired
```

```
org: <org>
app: <app>
service: <service>

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  deploymentMethod: direct

resources:
  Resources:
    OpenSearchInstance:
      Type: AWS::OpenSearchService::Domain
      Properties:
        DomainName: search-${sls:stage}
        EngineVersion: "OpenSearch_1.2"
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        DomainEndpointOptions:
          EnforceHTTPS: true
        EncryptionAtRestOptions:
          Enabled: true
        NodeToNodeEncryptionOptions:
          Enabled: true
        ClusterConfig:
          InstanceType: t3.small.search
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
```
