### DISCUSSION TITLE
API: s3:setBucketAccelerateConfiguration Access Denied for S3 Transfer Acceleration

### DISCUSSION THREAD

**Discussion by arthurliebhardt** [serverless/serverless#11183] [Q&A]
Hello,

I trying to deploy a S3 bucket with S3 Transfer Acceleration.

My bucket is defined like following

```yml
AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccelerateConfiguration:
          AccelerationStatus: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
```

the actual lambda function like

```yml
getImageUploadUrl:
    handler: functions/get-upload-url.handler
    environment:
      BUCKET_NAME: !Ref AssetsBucket
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:PutObjectAcl
        Resource: !Sub ${AssetsBucket.Arn}/*
```

I tried to Allow also the `s3:setBucketAccelerateConfiguration` but didn't help.

Also trying `sls deploy --aws-s3-accelerate` doesn't help.

Environment: darwin, node 14.19.1, framework 3.19.0, plugin 6.2.2, SDK 4.3.2

Thank you and best,
Arthur

**Comment by pgrzesik** [comment]
Hey @arthurliebhardt - could you please clarify what exactly are you trying to achieve and what does not work?

1. `--aws-s3-accelerate` flag is for uploads to deployment bucket, not for any other custom buckets you might create
2. The config you have for custom bucket looks okay to me, is it erroring out during deploy?
3. Are you sure that you're actually requesting to use acceleration when uploading things to bucket? See config of SDK: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/s3clientresolvedconfig.html

**Reply by arthurliebhardt** [reply]
Hi @pgrzesik, 

Thanks for your response. 
Actually I just want to upload an image to s3 with s3 transfer acceleration enabled.

1. Ok, this was then an misunderstanding of me.
2. yes, it crashes during the deploy
3. I didn't came to the step of uploading something. This is just deploying the infrastrucute, in this case the s3 bucket already crashes.

Also my user has AdministratorAccess. It's somehow very strange.

**Reply by pgrzesik** [reply]
Hey @arthurliebhardt, thanks for the clarification 🙇 Could you share the error message that you've run into? That would help out debugging further

**Reply by arthurliebhardt** [reply]
The error in the console is

Deploying appsync-backend to stage dev (eu-central-1)
AppSync Plugin: GraphQl schema valid

```
✖ Stack appsync-backend-dev failed to deploy (70s)
Environment: darwin, node 14.19.1, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: AssetsBucket (AWS::S3::Bucket)
API: s3:setBucketAccelerateConfiguration Access Denied
```

That's actually also the same in the CloudFormation.

**Reply by pgrzesik** [reply]
Thanks for sharing. Are you using `deploymentRole` by any chance? It looks like there are missing permissions to enable acceleration on the role used for deployment.

**Reply by arthurliebhardt** [reply]
No I i'm deploying via cli, which is AdministratorAccess right now. Don't configured any deploymentRoles either.

**Reply by pgrzesik** [reply]
Maybe there's a limit on the organization level for that specific action? Are you using an account within AWS organization? Also, could you share your serverless configuration, of course with sensitive parts masked out? Thanks!

**Reply by arthurliebhardt** [reply]
No, its also my private account. No Organizations created there.

Here is the serverless.yml:

```yml
service: appsync-backend

plugins:
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function
  - serverless-export-env
  - serverless-manifest-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: dev
  lambdaHashingVersion: 20201221
  environment:
    STAGE: ${self:custom.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  region: ${opt:region, self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  appSync: 
    - ${file(serverless.appsync-api.yml)}

  manifest:
    postProcess: ./processManifest.js
    disablePostDeployGeneration: true
    disableOutput: true
    silent: true

functions:
  confirmUserSignup:
    handler: functions/confirm-user-signup.handler
    environment:
      USERS_TABLE: !Ref UsersTable
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt UsersTable.Arn
  
  getImageUploadUrl:
    handler: functions/get-upload-url.handler
    environment:
      BUCKET_NAME: !Ref AssetsBucket
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:setBucketAccelerateConfiguration
        Resource: !Sub ${AssetsBucket.Arn}/*


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        Tags:
          - Key: Environment
            Value: ${self:custom.stage}
          - Key: Name
            Value: users-table
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true
        LambdaConfig:
          PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn
                
    UserPoolInvokeConfirmUserSignupLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref ConfirmUserSignupLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt CognitoUserPool.Arn

    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: web
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        PreventUserExistenceErrors: ENABLED

    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccelerateConfiguration:
          AccelerationStatus: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
        
  Outputs:
    AwsRegion:
      Value: ${self:custom.region}
      
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool

    WebCognitoUserPoolClientId:
      Value: !Ref WebUserPoolClient
```
