### DISCUSSION TITLE
Circular reference with ${self:}

### DISCUSSION THREAD

**Discussion by SamWSoftware** [serverless/serverless#11181] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In the docs for serverless variables, it shows the use of `${self:}` `[ Link to docs
](https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-properties-in-serverlessyml)`

When you try and do that in sls v3, you get the following error

Cannot resolve serverless.ts: Variables resolution errored with:
  - Cannot resolve variable at "custom.thisService": Circular reference. "custom.thisService" refers to itself

[Full repo ](https://github.com/SamWSoftware/sls-self-ref)

All that has really been done is to add `thisService: "${self:}",` to the custom section

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from "@serverless/typescript";

import hello from "@functions/hello";

const serverlessConfiguration: AWS = {
  service: "servicereference",
  frameworkVersion: "3",
  plugins: ["serverless-esbuild"],
  provider: {
    name: "aws",
    runtime: "nodejs14.x",
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1",
      NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000",
    },
  },
  // import the function via paths
  functions: { hello },
  package: { individually: true },
  custom: {
    thisService: "${self:}",
    // serviceName: "${self:service}",

    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ["aws-sdk"],
      target: "node14",
      define: { "require.resolve": undefined },
      platform: "node",
      concurrency: 10,
    },
  },
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

sls package

### Command output

```shell
N/A
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.19.0 (local) 3.14.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
