### DISCUSSION TITLE
Serverless.yml config for REQUEST type authorizer created as TOKEN type

### DISCUSSION THREAD

**Discussion by denlight** [serverless/serverless#11215] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello,

I am following your [documentation](https://github.com/serverless/serverless/blob/9fd56fddbedf85c01d6f4ebd2f63ab26746f6005/docs/providers/aws/events/http-api.md#lambda-request-authorizers) to create a custom REQUEST type Lambda authorizer, but it is converted to TOKEN type after deploy. 

 I navigate to API gateway -> Authorizers, I see that that both are TOKEN authorizers. Please advise :
<img width="827" alt="image" src="https://user-images.githubusercontent.com/4358849/177629861-0c559fee-511f-4351-bde7-15826d16fe7f.png">

 

### Service configuration (serverless.yml) content

```yaml
frameworkVersion: '3'

provider:
  name: aws
  runtime: ${env:RUNTIME}
  deploymentMethod: direct
  region: ${env:PROVIDER_REGION}
  stage: ${opt:stage, 'dev'}
  profile: ${env:PROVIDER_PROFILE}
  httpApi:
    authorizers:
      requestAuthorizer:
        type: request # note the type says REQUEST
        functionName: requestAuthorizer
        identitySource: $request.header.client_id
      tokenAuthorizer:
        type: token
        functionName: tokenAuthorizer
        identitySource: $request.header.Authorization

custom:
  prune:
    automatic: true
    number: 3
  cors:
    origin: '*'
    headers:
      - Content-Type
      - Authorization
      - client_id
    allowCredentials: true

functions:
  identity-api:
    handler: src/functions/api/identity/index.handler
    timeout: 30
    events:
      - http:
          path: /v1/identity/posts
          method: get
          cors: ${self:custom.cors}
          authorizer:
            name: requestAuthorizer
      - http:
          path: /v1/identity/posts/{postId}
          method: get
          cors: ${self:custom.cors}
          authorizer:
            name: tokenAuthorizer
          request:
            parameters:
              paths:
                postId: true

  requestAuthorizer:
    handler: src/functions/auth/requestAuthorizer.handler

  tokenAuthorizer:
    handler: src/functions/auth/tokenAuthorizer.handler
```

### Command name and used flags

sls deploy --verbose --stage prod

### Command output

```shell
yarn deploy-prod
yarn run v1.22.19
$ sls deploy --verbose --stage prod

Deploying amuse-next-api to stage prod (us-west-2)

Packaging
Excluding development dependencies for service package
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service amuse-next-api.zip file to S3 (14.9 MB)
Updating CloudFormation stack
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - amuse-next-api-prod
  CREATE_IN_PROGRESS - AWS::Logs::LogGroup - TokenAuthorizerLogGroup
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - IdentityDashapiLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - MessagingDashapiLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - RoutingDashapiLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - SlackDashmessagingDashqueueLambdaFunction
  CREATE_IN_PROGRESS - AWS::Logs::LogGroup - TokenAuthorizerLogGroup
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - RequestAuthorizerLambdaFunction
  CREATE_COMPLETE - AWS::Logs::LogGroup - TokenAuthorizerLogGroup
  CREATE_IN_PROGRESS - AWS::Lambda::Function - TokenAuthorizerLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Function - TokenAuthorizerLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - RequestAuthorizerLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - RoutingDashapiLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - SlackDashmessagingDashqueueLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - MessagingDashapiLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - IdentityDashapiLambdaFunction
  CREATE_COMPLETE - AWS::Lambda::Function - TokenAuthorizerLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - TokenAuthorizerLambdaVersion5tK0tOhrM3dG1BwRk3coEOwDi4kd889CuN6VQNvQyc
  CREATE_IN_PROGRESS - AWS::ApiGateway::Authorizer - TokenAuthorizerApiGatewayAuthorizer
  CREATE_IN_PROGRESS - AWS::Lambda::Permission - TokenAuthorizerLambdaPermissionApiGateway
  CREATE_IN_PROGRESS - AWS::Lambda::Permission - TokenAuthorizerLambdaPermissionApiGateway
  CREATE_IN_PROGRESS - AWS::Lambda::Version - TokenAuthorizerLambdaVersion5tK0tOhrM3dG1BwRk3coEOwDi4kd889CuN6VQNvQyc
  CREATE_COMPLETE - AWS::Lambda::Version - TokenAuthorizerLambdaVersion5tK0tOhrM3dG1BwRk3coEOwDi4kd889CuN6VQNvQyc
  CREATE_IN_PROGRESS - AWS::ApiGateway::Authorizer - TokenAuthorizerApiGatewayAuthorizer
  CREATE_COMPLETE - AWS::ApiGateway::Authorizer - TokenAuthorizerApiGatewayAuthorizer
  UPDATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodV1IdentityPostsPostidVarGet
  UPDATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodV1IdentityPostsPostidVarGet
  CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1657136324429
  CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1657136324429
  CREATE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1657136324429
  CREATE_COMPLETE - AWS::Lambda::Permission - TokenAuthorizerLambdaPermissionApiGateway
  UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - amuse-next-api-prod
  DELETE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1657135879133
  DELETE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1657135879133
  UPDATE_COMPLETE - AWS::CloudFormation::Stack - amuse-next-api-prod
Retrieving CloudFormation stack
✔ Pruning of functions complete
Removing old service artifacts from S3

✔ Service deployed to stack amuse-next-api-prod (66s)

endpoints:
  GET - https://foo/prod/v1/identity/posts
  GET - https://fooprod/v1/identity/posts/{postId}
  GET - https://foo/prod/v1/routing/onfleet/{entity}
  GET - https://foo/prod/v1/routing/onfleet/{entity}/{id}
  POST - https://foo/prod/v1/messaging/slack/notify
functions:
  identity-api: amuse-next-api-prod-identity-api (15 MB)
  routing-api: amuse-next-api-prod-routing-api (15 MB)
  messaging-api: amuse-next-api-prod-messaging-api (15 MB)
  slack-messaging-queue: amuse-next-api-prod-slack-messaging-queue (15 MB)
  requestAuthorizer: amuse-next-api-prod-requestAuthorizer (15 MB)
  tokenAuthorizer: amuse-next-api-prod-tokenAuthorizer (15 MB)

Stack Outputs:
  RequestAuthorizerLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:910563736318:function:amuse-next-api-prod-requestAuthorizer:5
  RoutingDashapiLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:910563736318:function:amuse-next-api-prod-routing-api:32
  SlackDashmessagingDashqueueLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:910563736318:function:amuse-next-api-prod-slack-messaging-queue:17
  MessagingDashapiLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:910563736318:function:amuse-next-api-prod-messaging-api:17
  IdentityDashapiLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:910563736318:function:amuse-next-api-prod-identity-api:38
  TokenAuthorizerLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:910563736318:function:amuse-next-api-prod-tokenAuthorizer:5
  ServiceEndpoint: https://foo/prod
  ServerlessDeploymentBucketName: amuse-next-api-prod-serverlessdeploymentbucket-yyjkjwdk1uqg

1 deprecation found: run 'serverless doctor' for more details

Monitor all your API routes with Serverless Console: run "serverless --console"
✨  Done in 70.15s.
```

### Environment information

```shell
Framework Core: 3.19.0 (local) 3.2.1 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
