### DISCUSSION TITLE
DynamoDB Stream Filter with Prefix

### DISCUSSION THREAD

**Discussion by bronzeson** [serverless/serverless#11232] [Q&A]
Hi, I'm looking for an example on how I can use the prefix functionality for DynamoDB Stream filtering.

I found a blog post with exactly what I'm looking for, but it keeps failing for me with "Invalid request provided: Invalid filter pattern definition." https://blog.theodo.com/2022/04/dynamodb-streams-serverless-filter-patterns-and-you/

It would also be helpful to see the exact JSON that serverless is trying to provide here for debugging purposes.
Thanks in advance!

Here is my syntax:

```
functions:
    reactionNotifications:
      handler: src.reaction_notifications.reaction_notifications
      events:
        - stream:
            type: dynamodb
            arn: xxxxxxxxxxxxx
            maximumRetryAttempts: 0
            batchSize: 10
            filterPatterns:
              - eventName: [INSERT]
                dynamodb:
                  NewImage:
                    material:
                      S:
                        - prefix: [RXN#]
```

Update: This gets a bit weirder - I just tried changing 'prefix' to 'anything-but' and it works. So maybe prefix is broken?

**Comment by mnapoli** [comment]
The `#` character might be causing issues in YAML parsing, maybe try adding quotes?

**Comment by bronzeson** [comment]
Thanks for the response!
I tried that and it didn't help. And I tried removing it. I don't think the # character is the problem, because it works with "anything-but"

I ended matching fully on a different attribute as a workaround, but this makes me think prefix might be broken somewhere along the way

**Reply by pgrzesik** [reply]
That's quite interesting. I've never tried it, but did you try setting it with prefix via UI? Is it not supported there as well?

**Comment by Maev4l** [comment]
Hi @bronzeson ,

I think the correct syntax is:
(Value for prefix is not an array, but single value)
```
functions:
    reactionNotifications:
      handler: src.reaction_notifications.reaction_notifications
      events:
        - stream:
            type: dynamodb
            arn: xxxxxxxxxxxxx
            maximumRetryAttempts: 0
            batchSize: 10
            filterPatterns:
              - eventName: [INSERT]
                dynamodb:
                  NewImage:
                    material:
                      S:
                        - prefix: 'RXN#' # <-- change to single value instead of array
```
