### DISCUSSION TITLE
Documentation is outdated for : apiKeys param

### DISCUSSION THREAD

**Discussion by jive-akira** [serverless/serverless#11239] [General]
When i Use frameworkVersion: '3'
i have this error

```yml
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  apiKeys:
    - value: 'test-api-key'
```

Warning: Invalid configuration encountered
  at 'provider': unrecognized property 'apiKeys'
