### DISCUSSION TITLE
Unable to deploy S3 event - getting "CREATE_FAILED: CustomDashresourceDashexistingDashs3LambdaFunction"

### DISCUSSION THREAD

**Discussion by jfederer** [serverless/serverless#11247] [Q&A]
My enterprise is restricted to only making S3 buckets using CF templates.  I have made said bucket using a CF template and uploading it:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket Policy for a WORM model for RAW files

Parameters:
  BucketName:
    Type: String
    Description: The name of the bucket to attach the new policy to
    Default: myRawBucketName

Resources:
  Policy:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      ObjectLockEnabled: true
      VersioningConfiguration:
        Status: Enabled
```
This template successfully creates the S3 bucket.

I plan to make a lambda that will place a legal hold on every created object in the bucket.  I'd do this bucket-wide with a single bucket-wide legal hold.... but I DO actually need to occasionally delete files from this bucket (while keeping the others protected) and it's my understanding that having a many legal holds is the only way to do this.  This bucket will have billions of files.

So, I'd like to have an event associated with this S3 bucket, one that triggers a lambda:

```
  handleNewRawObjectInS3:
    handler: lambdas/handleNewRawObjectInS3/handleNewRawObjectInS3.handleS3Event
    events:
      - s3:
          bucket: myRawBucketName
          event: s3:ObjectCreated:*
          existing: true
```

When I go to deploy this, I get the following error:

```
CREATE_FAILED: CustomDashresourceDashexistingDashs3LambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "The role defined for the function cannot be assumed by Lambda. 
```

It's worth noting my enterprise, doesn't allow automated role creation - ie, no "createRole" abilities... so for normal deployments, I define a custom deployment role which gets used without problems. 

```
  iam:
    role: MyServerlessRole 
    deploymentRole:  MyServerlessRole  
```

My IAM role setup looks like this:

```
Resources:
  MyServerlessRole :
    Type: AWS::IAM::Role
    Properties:
      # The permissions boundary is the entire reason we need to specify a custom IAM role instead of letting serverless automatically create an IAM role.
      PermissionsBoundary: arn:aws:iam::xxxxxx:policy/csr-Developer-Permissions-Boundary
      Path: /my/default/path/
      RoleName: MyServerlessRole-${self:service}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: myPolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:logs'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'log-group:/aws/lambda/*:*:*'
    
              - Effect: "Allow"
                Action:
                  - "s3:*"
                Resource: "arn:aws:s3:::*

              - Effect: "Allow"
                Action:
                  - "lambda:*"
                Resource: "*" 
              
              - Effect: "Allow"
                Action:
                  - cloudfront:CreateDistribution
                  - cloudfront:GetDistribution
                  - cloudfront:UpdateDistribution
                  - cloudfront:DeleteDistribution
                  - cloudfront:TagResource
                Resource: "arn:aws:cloudfront:::*"             

```

Worth noting, I've read this very good discussion: https://github.com/serverless/serverless/issues/6771 (and others) but haven't managed to find a solution.

It's my understanding that I have the assumeRole ability...  but it's like it's using this "CustomDashresourceDashexistingDashs3LambdaFunction" thing instead. (is that a role? a function? where is that coming from?)

Framework Core: 3.21.0 (standalone)
Plugin: 6.2.2
SDK: 4.3.2
