### DISCUSSION TITLE
Serverless deployment error integrating with github

### DISCUSSION THREAD

**Discussion by Juanmadepalacios** [serverless/serverless#11254] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Good afternoon, I am going to describe a little the problem we have in the project: We are trying to do a deployment every time a pull request is made to github, it had been working fine for us but we restructured the project to use serverless compose. It turns out that now every time we do the pull request all the deployments fail. The strange thing is that if we do them from the terminal they all work fine, but the idea is to do it every time we make a pull request so as not to step on each other among the team members. This is the error that is giving us. Thank you

![image](https://user-images.githubusercontent.com/54809810/179290404-55249a6d-e821-4be6-ba1a-3b0b05607ba6.png)

### Service configuration (serverless.yml) content

```yaml
org: mydna
app: mydna-b2e-app
service: employersexp
configValidationMode: error
useDotenv: true

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-webpack
  # - serverless-bundle

custom:
  # bundle:
  #   sourcemaps: true
  #   linting: false
  #   ignorePackages:
  #     - pg-hstore
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules

provider:
  environment:
    NODE_ENV: ${param:NODE_ENV}
    DB_NAME: ${param:DB_NAME}
    DB_USER: ${param:DB_USER}
    DB_PASSWORD: ${param:DB_PASSWORD}
    DB_HOST: ${param:DB_HOST}
    DB_PORT: ${param:DB_PORT}
    SECURITY_GROUP_ID: ${param:SECURITY_GROUP_ID}
    SUBNET1_ID: ${param:SUBNET1_ID}
    SUBNET2_ID: ${param:SUBNET2_ID}
    SUBNET3_ID: ${param:SUBNET3_ID}
    SUBNET4_ID: ${param:SUBNET4_ID}
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: us-east-1
  timeout: 30

  vpc:
    securityGroupIds:
      - ${param:SECURITY_GROUP_ID}
    subnetIds:
      - ${param:SUBNET1_ID}
      - ${param:SUBNET2_ID}
      - ${param:SUBNET3_ID}
      - ${param:SUBNET4_ID}

functions:
  #EmployerExp
  createEmployerExp:
    handler: handler.create
    events:
      - http:
          path: exp/{id}
          method: post
          cors: true
  findOneEmployerExp:
    handler: handler.findOne
    events:
      - http:
          path: exp/{id}
          method: get
          cors: true
  destroyEmployerExp:
    handler: handler.destroy
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
  updateEmployerExp:
    handler: handler.update
    events:
      - http:
          path: exp/{id}
          method: put
          cors: true
```

### Command name and used flags

git push

### Command output

```shell
Runner: 0.7.5
Provider: GITHUB
build step: git clone Mydna-apps/b2e-sls
Cloning into 'b2e-sls'...
successfully cloned git repo Mydna-apps/b2e-sls into b2e-sls
build step: git checkout a8f91b9bd76ef3745efca71f57eeba1cc5d5bf28
HEAD is now at a8f91b9 Merge pull request #69 from Mydna-apps/fix/loginCompany
successfully checked out git commit a8f91b9bd76ef3745efca71f57eeba1cc5d5bf28
build step: npm ci --if-present --unsafe-perm
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/serverless/compose.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-15T18_25_12_180Z-debug.log
build step failed: npm ci --if-present --unsafe-perm
Deploy failed!
Error: build step failed: npm ci --if-present --unsafe-perm
```

### Environment information

```shell
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
```
