### DISCUSSION TITLE
Cloudformation dependency issue - EventInvokeConfig created before lambda exists

### DISCUSSION THREAD

**Discussion by colesiegel** [serverless/serverless#11311] [Q&A]
Hi all, 

I recently added a new lambda function to my `serverless.yml` file, it uses an SQS  trigger as documented here https://www.serverless.com/framework/docs/providers/aws/events/sqs

The strange thing is now my other unrelated SQS resources such as `AWS::Lambda::EventInvokeConfig` seem to have their dependencies affected. Previously the functions referenced by `EventInvokeConfig` would automatically get created first but now the creation of `EventInvokeConfig` results in `Cloudformation error: The function doesn't exist. (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException`

Does anyone have any idea what could be the cause and/or how to troubleshoot further?

I've included excerpt of the config below. The preexistingLambda got deployed okay until I added the newLambda with SQS trigger, after doing that the stack fails when I deploy it fresh, as the dependencies for `preexistingLambdaEventHandlerDLQEventInvokeConfig` are out of order

```
Resources:
    preexistingLambdaEventHandlerDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.preexistingLambdaEventHandlerDLQName}
        MessageRetentionPeriod: 1209600 # 14 days in seconds (max amount of time)
  
    preexistingLambdaEventHandlerDLQEventInvokeConfig:
      Type: AWS::Lambda::EventInvokeConfig
      Properties:
        DestinationConfig:
          OnFailure:
            Destination:
              Fn::GetAtt: ['preexistingLambdaEventHandlerDLQ', 'Arn']
        FunctionName: ${self:service}-${self:custom.stage}-preexistingLambdaEventHandler
        Qualifier: $LATEST
  
    newLambdaEventHandlerDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.newLambdaEventHandlerDLQName}
        MessageRetentionPeriod: 1209600
  
    newLambdaPollingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.newLambdaQueueName}
        DelaySeconds: 60
        VisibilityTimeout: 60
        MessageRetentionPeriod: 1209600
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: ['newLambdaEventHandlerDLQ', 'Arn']
          maxReceiveCount: 20

functions:
  preexistingLambdaEventHandler:
    timeout: 60
    handler: dist/preexistingLambda/eventhandlers/preexistingLambdaEventHandler.eventHandler
    environment:
      POLLING_QUEUE_NAME: ${self:custom.newLambdaQueueName}
    events:
      - eventBridge:
          <<: *eventBridgeDefaults
          enabled: ${self:custom.config.enablepreexistingLambdaEventHandler}
          pattern:
            source:
              - op.api
            detail-type:
              - documents:create
          deadLetterQueueArn:
            Fn::GetAtt: ['preexistingLambdaEventHandlerDLQ', 'Arn']
    provisionedConcurrency: ${self:custom.config.provisionedConcurrency.preexistingLambdaEventHandler}

  newLambdaEventHandler:
    timeout: 60
    handler: dist/preexistingLambda/eventhandlers/newLambdaEventHandler.eventHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - newLambdaPollingQueue
              - Arn
          batchSize: 1
    provisionedConcurrency: ${self:custom.config.provisionedConcurrency.newLambdaEventHandler}
```

If I define my event trigger for the new lambda using an EventSourceMapping instead of the serverless inline config, there is no dependency issue and it deploys okay:

```
  newLambdaTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
          - newLambdaPollingQueue
          - Arn
      FunctionName: ${self:service}-${self:custom.stage}-newLambdaEventHandler
```

however for local use with serverless-offline the queue and trigger is not created, so this is not a suitable solution.

**Comment by pgrzesik** [comment]
Hey @colesiegel - based on the description, it sounds like your previous setup was working by chance and introducing a new moving piece caused the race condition to appear. What version of the Framework are you using?

I'm also curious - why do you define your event source mappings explicitly? What is the limitation of native `sqs` event that you're trying to bypass there?

**Reply by colesiegel** [reply]
Hey @pgrzesik 

I tried to define my event source mappings inside the function initially

```
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - newLambdaPollingQueue
              - Arn
          batchSize: 1
```

That is what led me to the dependency issue noted in this discussion. I only explored the explicit mapping as an alternative to resolve my deployment problem. 

The explicit `EventInvokeConfig` located in our resources config was a pre-existing part of the project, which seems to clash with the inline SQS mapping syntax somehow. As soon as I add an inline SQS mapping, the `EventInvokeConfig` is deployed in the wrong order before the functions it references.

I've noticed that `EventInvokeConfig` can also be defined inline using lambda destinations (https://www.serverless.com/blog/lambda-destinations) but the syntax requires an absolute ARN which is less easy to work with, and I'd like to avoid changing large existing parts of our project and introducing more risk unless absolutely necessary. 

Our serverless version in `package.json` is `"^3.16.0"`, not sure what version we end up pulling as we use a bunch of plugins too. Let me try to change it to `"^3.21.0"` and see if the issue persists.
