### DISCUSSION TITLE
Upgrading from 2.67.0 to 3.21.0

### DISCUSSION THREAD

**Discussion by unematiii** [serverless/serverless#11323] [Q&A]
So I tried upgrading serverless framework to latest today and ran into this issue, which I'm not sure how to solve:

`npx serverless deploy --verbose` fails:

```
Environment: linux, node 12.16.1, framework 3.21.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
 
Error:
Error: Not supported
at module.exports (/codebuild/output/xxxxxx/node_modules/serverless/lib/utils/import-module.js:9:39)
at PluginManager.requireServicePlugin (/codebuild/output/xxxxxx/node_modules/serverless/lib/classes/plugin-manager.js:171:14)
at PluginManager.resolveServicePlugins (/codebuild/output/xxxxxx/node_modules/serverless/lib/classes/plugin-manager.js:198:29)
at PluginManager.loadAllPlugins (/codebuild/output/xxxxxx/node_modules/serverless/lib/classes/plugin-manager.js:136:47)
at Serverless.init (/codebuild/output/xxxxxx/node_modules/serverless/lib/serverless.js:141:30)
at async /codebuild/output/xxxxxx/node_modules/serverless/scripts/serverless.js:591:7

```

`serverless.yml`:

```yaml
service: xxxx

useDotenv: true

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${env:STAGE}
    region: eu-central-1
    endpointType: REGIONAL
    memorySize: 256
    timeout: 30
    logRetentionInDays: 30
    iam:
        role:
            statements:
                - // omitted

    deploymentBucket:
        name: ${env:BUILD_S3_BUCKET}
        serverSideEncryption: AES256

    environment:
        // omitted

plugins:
    - serverless-offline
package:
    excludeDevDependencies: true
    patterns:
        - '!**/**'
        - functions/**
        - node_modules/**

functions:
    // omitted

custom:
  serverless-offline:
    httpPort: ${env:SERVER_PORT, 9090}

```

package.json:

```json
{
  "name": "xxxx",
  "version": "xxxx",
  "scripts": {
  },
  "dependencies": {
    "aws-sdk": "^2.1190.0",
  },
  "devDependencies": {
    "dotenv": "^16.0.1",
    "serverless": "3.21.0",
    "serverless-offline": "9.1.7"
  }
}

```

Any suggestions are welcome...
