### DISCUSSION TITLE
Use AWS default Request Validator with custom model

### DISCUSSION THREAD

**Discussion by darrencapner** [serverless/serverless#11321] [Q&A]
Hi,

I ran into an issue today indicating too many request validation schemas when I added another lambda function with an http event and a defined request schema.

I was following the instructions on serverless frameworks website for how to define a request schema validators using a custom schema. https://www.serverless.com/framework/docs/providers/aws/events/apigateway#request-schema-validators

This is instructions by AWS for how to change the request validator in the console just for reference of what is being desired below https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-validation-set-up.html
  ```
login:
    handler: authentication-login/index.login
    memorySize: 512
    timeout: 6
    events:
      - http:
          path: login
          method: post
          cors:
            origins: '${self:custom.cors.${self:provider.stage}}'
            headers:
              - ${self:custom.allowed-headers.${self:provider.stage}}
              - X-Recaptcha-Token
              - X-Web-Access
            allowCredentials: true
          request:
            schema:
              application/json: ${file(authentication-login/request-validators/login_request.json)}
```

The end result of this configuration produces a method resource, model resource and a request validator resource (among others like lambda which is not what is being focused on). The following are cloudformation template snippets for AWS::ApiGateway::Method, AWS::ApiGateway::RequestValidator, and AWS::ApiGateway::Model resources produced by the above serverless yml snippet.
  ```
ApiGatewayMethodLoginPostApplicationJsonModel:
    Type: 'AWS::ApiGateway::Model'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ContentType: application/json
      Schema:
        $schema: 'http://json-schema.org/draft-04/schema#'
        title: Login Schema
        type: object
        properties:
          username:
            type: string
            pattern: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+$'
          password:
            type: string
        required:
          - username
          - password
  ApiGatewayMethodLoginPostValidator:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ValidateRequestBody: true
      ValidateRequestParameters: true
  ApiGatewayMethodLoginPost:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: POST
      RequestParameters: {}
      ResourceId: !Ref ApiGatewayResourceLogin
      RestApiId: !Ref ApiGatewayRestApi
      ApiKeyRequired: false
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Join
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt
              - LoginLambdaFunction
              - Arn
            - /invocations
      MethodResponses: []
      RequestValidatorId: !Ref ApiGatewayMethodLoginPostValidator
      RequestModels:
        application/json: !Ref ApiGatewayMethodLoginPostApplicationJsonModel
```
My understanding is that API Gateway has an undocumented limitation on the number of 'Request Validators' that an API Gateway instance can have. I was reading that I should be using the default request validators that API Gateway provides as much as possible, while indicating a custom model to validate against.

I want to use the default Request Validator 'Validate Body' or provide my own Request Validator that can be reused (custom validate request body), while then referencing a new model for that lambda/http event configuration.

How might I configure this with serverless framework?

This is a link to the question asked on Serverless Framework Slack Channel https://serverless-contrib.slack.com/archives/CA4QT5VU3/p1658328430376339
