### DISCUSSION TITLE
Async Lambda invocation with API Gateway V2

### DISCUSSION THREAD

**Discussion by kaofelix** [serverless/serverless#11344] [Q&A]
Hi folks!

I was trying to setup Async Lambda invocation with API Gateway V2. From what I could gather, on the API Gateway side, we need to set the `X-Amz-Invocation-Type` header to `Event` as documented [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-integration-async.html). I can easily do that with Parameter Mappings through the AWS Web Console. However, I couldn't find a way to set this up from the serverless config. Is there a way to do it?

I know I could switch to API Gateway V1 to have async, but I would rather avoid it if possible since it could impact other parts of our setup.

Thanks!

**Comment by nick-zh** [comment]
This was fixed [here](https://github.com/serverless/serverless/issues/4862)

You should be able to use:
```
    events:
      - http:
          path: users
          method: post
          integration: AWS
          async: true
```
