### DISCUSSION TITLE
How to use github artifacts in conjunction with sls package and deploy

### DISCUSSION THREAD

**Discussion by suryajak** [serverless/serverless#11362] [General]
What is the recommended way of using sls package and deploy for multi stage deployment using github artifacts? 

This is what I have so far:

```
steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci
      
    - name: Package
      run: npm run sls:package -- --stage dev --package my-artifacts

    - name: Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: |
          my-artifacts
          serverless.yml          
```
and somewhere else 

```
deploy-dev:
  - name: Download artifact
    uses: actions/download-artifact@v3
    with:
      name: my-artifacts
      
 - name: Deploy to AWS w/serverless
    run: npx serverless deploy --package my-artifacts --stage dev --verbose 
```

The above isn't working with a serverless.yml similar to below. It first has error as "Cannot resolve variable at "provider.role.Fn::Sub": Value not found at "env" source" at which I ended up adding .env files as part of the artifact. Nows its asking me to include the webpack plugin - "Serverless plugin "serverless-webpack" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-webpack" to install it."

```
service: foo-bar
useDotenv: true

custom:
  tags:
    Name: ${self:service}-${sls:stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'us-west-2'}
  timeout: 30

  stackTags:
    ${self:custom.tags}
  tags:
    ${self:custom.tags}

  deploymentBucket:
    name: mybucket-deploy-${sls:stage}

  role: !Sub arn:aws:iam::${AWS::AccountId}:role/${env:IAM_ROLE_NAME}

functions:
  userInfo:
    handler: src/app.handler
    name: ${self:service}
```
What is a recommended approach to leverage artifacts and separate package and deploy?
