### DISCUSSION TITLE
Enabling api gateway access log auto-generates lambda function in nodejs12.x, nowhere to change version

### DISCUSSION THREAD

**Discussion by 300LiterPropofol** [serverless/serverless#11364] [Q&A]
Hello! 
Recently AWS is stopping support for nodejs12.x in their lambda functions so a feature in serverless framework becomes a bug for me.

I am using serverless framework to create an API gateway in AWS, simple demo is below:

`/serverless.yml`
```
service: nodeversion

frameworkVersion: '2'
useDotenv: true
unresolvedVariablesNotificationMode: error
variablesResolutionMode: 20210326
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'temp'}
  region: eu-west-1
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221
  endpointType: regional
  apiGateway:
    shouldStartNameWithService: true
  logs:
    restApi:
      accessLogging: true
  versionFunctions: true


functions:
  handler:
    handler: handler.handler
    description: Test Lambda
    events:
      - http:
          path: health
          method: get
          cors: false
```

My serverless version is as below:
```
Framework Core: 2.59.0 (standalone)
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```

The `serverless.yml` above will create an API gateway after deployment, because I enabled access logging in the framework too, the deployment will also auto-create a lambda function that handles access logging 
![image](https://user-images.githubusercontent.com/46748408/187473593-2f087abe-249c-46e8-8452-7129cc53ad01.png)

My issue is that the aforementioned lambda function's runtime is always nodejs12.x, which is an outdated version that AWS will stop support soon. I couldn't find anywhere in serverless docs how to change the runtime for this auto-generated access-logging lamdda. 
I wonder how I can change the access-logging lambda runtime to nodejs16.x and how serverless team is gonna proceed with the default nodejs12.x version.
Please help me, thank you a lot!

Best Regards
