### DISCUSSION TITLE
Enabling CORS in API Gateway V2 HTTP API

### DISCUSSION THREAD

**Discussion by tibbing** [serverless/serverless#11382] [Q&A]
Following the instructions to enable CORS in the new API Gateway HTTP API v2 at https://www.serverless.com/blog/aws-http-api-support shows that it should be possible to do:
```
provider:
  name: aws
  httpApi:
    cors: true
    ....
```

However, this results in the following error:
```
Error:
UPDATE_FAILED: HttpApi (AWS::ApiGatewayV2::Api)
allow-credentials is not supported if 'allow-origin' is * (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: xxxxxxxxxxxx; Proxy: null)
```
Explicitly specifying cors settings does work:
```
  httpApi:
    cors:
      allowedOrigins:
        - https://mydomain.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - "*"
      allowCredentials: true
      maxAge: 6000
```
Is this a known problem, or am I missing something? 

Additionally - we used to be able to enable cors for unhandled requests such as 4XX errors, as described [here](https://www.serverless.com/blog/cors-api-gateway-survival-guide/) and [here](https://github.com/serverless/examples/blob/master/aws-node-auth0-custom-authorizers-api/serverless.yml#L33):

```
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
```

This does not seem to work in API Gateway v2. How would we accomplish this?
