### DISCUSSION TITLE
ECR Property in Serverless.yml is not Referencing the set Profile

### DISCUSSION THREAD

**Discussion by selected-pixel-jameson** [serverless/serverless#11380] [Q&A]
I'm attempting to use the ECR property in my serverless.yml file to create and upload a new image to ECR.

I'm doing this like so. 

```
provider:
  name: aws
  profile: profile-name
  versionFunctions: false
  region: us-east-1
  runtime: python3.9
  stage: ${opt:stage, 'local'}
  timeout: 900
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

```

I ran a serverless deploy and everything was built successfully, but I couldn't find a reference to the image anywhere in ECR within AWS.

Finally I checked one of my other AWS accounts and I was surprised to see that the image had been created using my default AWS profile and not the one provided in the serverless.yml file.

Is there no way to use this property without changing the default AWS profile?
