### DISCUSSION TITLE
Does lambda tracking exist with ALB?

### DISCUSSION THREAD

**Discussion by arleyyap** [serverless/serverless#11392] [Q&A]
I'm new to serverless and am currently on a project where I connect my lambdas to ALB. Reading I found that the tracing option can be enabled by adding in the provider:
```
provider:
  name: aws
  tracing:
    lambda: true
```
I also found that tracing supports apiGateway in the following link: 
https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#aws-x-ray-tracing
	
```
provider:
  name: aws
  tracing:
    apiGateway: true
```
Is there an option to enable ALB tracing instead of apigateway or some special configuration?
