### DISCUSSION TITLE
How can I log in to serverless through an Ubuntu Instance running on the cloud?  I'm using github actions and need help with the deployment.

### DISCUSSION THREAD

**Discussion by FaisalRana** [serverless/serverless#11404] [Q&A]
I have an express API that I am using serverless to deploy.  I recently tried to integrate serverless with GitHub actions so that every time I made a commit, it would deploy the latest build.  

I ran into the following issue while I was setting this up: https://github.com/serverless/serverless/issues/8640. 

Whenever I try and deploy my API through GitHub Actions I get the following error:
```
Error:
You are not currently logged in. Follow instructions in http://slss.io/run-in-cicd to set up env vars for authentication.
```

I was able to resolve this issue by removing the "org" from the top of my serverless.yml.  Although this allows me to deploy my app, it also makes it so that the deployment details are missing from my serverless dashboard.  

Here is what my github actions yaml looks like:

```
name: Deploy ***** API - Staging

on:
  push:
    branches:
      - f****
      - d*****
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd amend-express-api && npm ci
    - name: Enter dir and deploy
      uses: serverless/github-action@v3
      with:
        args: -c "cd ./amend-express-api && serverless deploy --stage staging"
        entrypoint: /bin/sh

      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

```

My understanding is that serverless is not logged in on the ubuntu cloud computer that I am using to do this deployment.  

How can I login to serverless without a browser?  Is it possible to login just by using
