### DISCUSSION TITLE
Serverless Cannot resolve variable

### DISCUSSION THREAD

**Discussion by AlessandroMinoccheri** [serverless/serverless#11420] [General]
I would like to take a param from a result of an external JS function but I retrieve this error:

Cannot resolve serverless.yml: Variables resolution errored with:

```
- Cannot resolve variable at "resources.Resources.FileBucket.Properties.BucketName": Value not found at "file" source
```

This is my (a piece) serverless file:

```
service: backend-uploader
frameworkVersion: '3'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${file(./unique-bucket-name.cjs):bucketName} 
```

This is my file unique-bucket-name.cjs in the same directory:

```
module.export = async function () {
  return { bucketName: 'something' }
}
```

I have tried using self and importing the file as custom but the error still. I have tried to use a Json with the same response and it works.

Why my JS file can't be taken from serverless?

Thanks.
