### DISCUSSION TITLE
Add repository tags to ECR

### DISCUSSION THREAD

**Discussion by snoop123** [serverless/serverless#11439] [Q&A]
Hi everyone,

**Q1:**
I want to deploy a service using a lambda container image + add repository tags to the newly created ECR. I tried this configuration but it didn't create the tags:

```
provider:
  ecr: 
    images:
      my-func:
        path: /serverless/source
        tags:
          team: "team"
          environment: "staging"
          managed_by: "serverless"
```

Is it possible?

**Q2:**
Can I run the same deployment and also attach a retention policy to the ECR? 

thank you!
