### DISCUSSION TITLE
IAM deploy role still referenced after being removed from serverless.yml?

### DISCUSSION THREAD

**Discussion by justinwiley** [serverless/serverless#11463] [Q&A]
Hi

As part of a spike, I created and added a custom deployment role to my serverless.yml file following instructions [here](https://serverlessfirst.com/create-iam-deployer-roles-serverless-app/):

```
provider:
  iam:
    deploymentRole:
	  Fn::Sub: 'arn:aws:iam::${AWS::AccountId}:role/MyApp-CloudFormationExecutionRole'
```

After granting myself the ability assume role, I successfully deployed.  

I reverted serverless.yml, which removed the explicit deployment role.  I also deleted the role in the AWS IAM console.  Now, however, it fails with "ServerlessError: ValidationError: Role arn:aws:iam::<my account id>:role/MyApp-CloudFormationExecutionRole is invalid or cannot be assumed".

I deleted the serverless caches in the project and user cache.  I reviewed the CF stack template in AWS, I don't see any reference in the stack template, and as I said I deleted the role.

I'm wondering how to stop referencing the deploy role?
