### DISCUSSION TITLE
Error in production/dev but not on local environment (image proxy with serverless)

### DISCUSSION THREAD

**Discussion by pirmax** [serverless/serverless#11469] [General]
Hello,

I use middy package and serverless and I not have error in local with the following code, but in production/dev stage on serverless.com, I've a **Internal server error** with **502 Bad Gateway**.

```
{
    "message": "Internal server error"
}
```

The following code is a simple image proxy to have no error with CORS and Twitter avatar on my React webpage.

```
import middy from '@middy/core';
import httpErrorHandler from '@middy/http-error-handler';
import httpEventNormalizer from '@middy/http-event-normalizer';
import middyJsonBodyParser from '@middy/http-json-body-parser';
import axios from 'axios';

export const imageProxy = async (event: any) => {
    const params: any = event.queryStringParameters;

    const response = await axios.get(params.url, {
         responseType: 'arraybuffer',
    });

    return {
        statusCode: 200,
        body: response.data,
        isBase64Encoded: true,
        headers: {
            'Content-Type': response.headers['content-type'],
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': true,
        },
    };
};

export const handler = middy(imageProxy)
    .use(middyJsonBodyParser())
    .use(httpEventNormalizer())
    .use(httpErrorHandler());

```

```
functions:
  image-proxy:
    handler: image-proxy.handler
    timeout: 10
    memorySize: 256
    events:
      - http:
          path: /image-proxy
          method: get
```

I don't know how get errors log in serverless, I've invocations but no exception...

Thanks to help me please :)
