### DISCUSSION TITLE
API GW Private Endpoint - Missing Resource Policy

### DISCUSSION THREAD

**Discussion by Veluu** [serverless/serverless#11512] [Q&A]
Hey

I have a config as follows

```
service: aws-api-gateway
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  region: us-east-1
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - "arn:aws:execute-api:*"
      - Effect: Deny
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - "arn:aws:execute-api:*"
        Condition:
          StringNotEquals:
            aws:SourceVpce: vpce-0c149ff20d553cba5
plugins:
  - serverless-openapi-integration-helper # Enable OpenAPI Support

# openApiIntegration:
#   inputFile: api.yaml
#   package: true
#   mapping:
#     - path: integrations
#       stage: [dev, prod]
#     - path: mocks/customer.yml
#       stage: test

functions:

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        ApiKeySourceType: HEADER
        # Body: ~
        Description: "Some Description"
        FailOnWarnings: false
        Name: ${opt:stage, self:provider.stage}-some-name
        EndpointConfiguration:
          Types:
            - PRIVATE
    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId:
          Ref: ApiGatewayRestApi
        StageName: ${opt:stage, self:provider.stage}
```

If the API was `REGIONAL` it would work but I need a `PRIVATE` one. It keeps failing as it says I lack the resource policy.

```✖ Stack aws-api-gateway-dev failed to deploy (211s)
Environment: linux, node 18.12.1, framework 3.24.1 (local) 3.24.1v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: ApiGatewayDeployment (AWS::ApiGateway::Deployment)
Resource handler returned message: "Private REST API doesn't have a resource policy attached to it (Service: ApiGateway, Status Code: 400, Request ID: 0719ef09-3671-4884-b1d5-3427cfe96803)" (RequestToken: 94d4f747-3d0f-2935-91e3-38a65a7b4499, HandlerErrorCode: InvalidRequest)
```

I did provide resource policy as specified in https://www.serverless.com/framework/docs/providers/aws/events/apigateway#resource-policy and I don't understand why SLS does not use it.
