### DISCUSSION TITLE
EventBridge rule with pattern prefix

### DISCUSSION THREAD

**Discussion by matthiasbruns** [serverless/serverless#11536] [Q&A]
Hello community,

I want to create a EventBridge rule for Shopify. The rule that AWS provides for it looks like this:

```json
{
  "source": [{
    "prefix": "aws.partner/shopify.com"
  }]
}
```

My serverless.yml looks like this:

```yaml
    events:
      - eventBridge:
          eventBus: arn:aws:SOME_ARN
          pattern:
            prefix: "aws.partner/shopify.com"
```

which results in a different rule in AWS:

```json
{
  "source": ["aws.partner/shopify.com"]
}
```

I could't find any resource of how to prefix sources, only an example for s3 objects. Is this possible in sls or do I need to go the Cloudformation way?

**Comment by markyangit** [comment]
I think it's missing a '-' on prefix: https://www.serverless.com/framework/docs/providers/aws/events/event-bridge#setting-up-event-pattern-matching

And you not declared which property you want to filter (i dont know if "source" is implicit)

the correct should be:
```
  events:
      - eventBridge:
          eventBus: arn:aws:SOME_ARN
          pattern:
            source:
              - prefix: "aws.partner/shopify.com"
```
