### DISCUSSION TITLE
How to create a data protection policy for a log group?

### DISCUSSION THREAD

**Discussion by yuyokk** [serverless/serverless#11562] [Q&A]
Hi folks,

AWS announced [Protect Sensitive Data with Amazon CloudWatch Logs](https://aws.amazon.com/blogs/aws/protect-sensitive-data-with-amazon-cloudwatch-logs/).

How to do it properly with existing serverless setup?

```yml
# serverless.yml

service: my-express-application
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
 
functions:
  MainApi:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```
