### DISCUSSION TITLE
Serverless with Nest.js on AWS Lambda throws Controller TypeError, function undefined

### DISCUSSION THREAD

**Discussion by basselabbara** [serverless/serverless#11657] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have Nest.js as part of monorepo with Nx. 

Running Nest.js locally works fine, also creating a build and running it independently works fine.

When Nest is deployed to Lambda and I try to hit an endpoint, I get:
`{
    "statusCode": 500,
    "message": "Internal server error"
}`

It runs the decorators just fine, but when it reaches the controller's function it throws an error:
`TypeError: Cannot read properties of undefined (reading 'getAllProfiles')
at ProfileController.<anonymous> (/var/task/packages/backend/src/modules/profile/profile.controller.js:59:59)
`

### Service configuration (serverless.yml) content

```yaml
service: oa

plugins:
 - serverless-plugin-typescript
 - serverless-offline

provider:
 name: aws
 runtime: nodejs18.x

functions:
 backend:
   CodeUri: ./
   handler: lambda.handler
   events:
     - http:
         method: any
         path: /{any+}
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Environment: darwin, node 16.14.2, framework 3.25.1, plugin 6.2.2, SDK 4.3.2
```
