### DISCUSSION TITLE
Help setting up httpApi authorizer using existing amplify cognito

### DISCUSSION THREAD

**Discussion by imoby** [serverless/serverless#11652] [Q&A]
Hello everyone,

I'm trying to follow the steps to add an httpApi authorizer to my lambdas. In the old http method all I needed to do was point it to an arn for my amplify cognito user pool like so:

```
  demoFn:
    handler: /path/demo
    events:
      - http:
          path: '/path/demo'
          method: 'POST'
          authorizer:
            arn: arn:aws:cognito-idp:us-east-{ACCOUNT}:userpool/{SOMEID}
```

However, when trying to set this up with httpApi, I believe the new format is something more like whats mentioned here in the docs: https://www.serverless.com//framework/docs-providers-aws-events-http-api#jwt-authorizers

```
provider:
  httpApi:
    authorizers:
      someJwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${region}.amazonaws.com/${cognitoPoolId}
        audience:
          - ${client1Id}
          - ${client2Id}

	
functions:
  someFunction:
    handler: index.handler
    events:
      - httpApi:
          method: POST
          path: /some-post
          authorizer:
            name: someJwtAuthorizer
            scopes: # Optional
              - user.id
              - user.email
```

I'm curious to know what to set for the audience in this case, when creating an amplify cognito auth it created two `App Clients` for me. Are these App client ids what I need set here then and add more anytime a new UI client needs to access these endpoints?
