### DISCUSSION TITLE
AWS API Gateway `provider.apiGateway.stage` not working?

### DISCUSSION THREAD

**Discussion by mpage-hearsay** [serverless/serverless#11664] [Q&A]
Hello!

I am trying to override the AWS API Gateway Stage name as described [here](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#providing-a-custom-stage-name:~:text=disableDefaultEndpoint%3A%20true-,Providing%20a%20custom%20stage%20name,-By%20default%2C%20the).

However, when I deploy it doesn't create a stage with the overridden name value. It still defaults to using the Serverless stage name for the new API Gateway Stage.

Here's an example of my configs and the deployed URLs. (I'm aware using the Serverless stage as part of the resource path is a little weird but that's a separate discussion.)

```
provider:
  apiGateway:
    restApiId: 1111
    restApiRootResourceId: 2222
    stage: foobar
...

functions:
  func1:
    name: func1-${opt:stage, 'dev'}
    handler: bin/func1
    events:
      - http:
        path: /${opt:stage, 'dev'}/f1
        method: get
  func2:
    name: func2-${opt:stage, 'dev'}
    handler: bin/func2
    events:
      - http:
        path: /${opt:stage, 'dev'}/f2
        method: post
```
These are the URLs I see in the deployed API Gateway Stage(s):
```
https://asdfjkl.execute-api.my-region.amazonaws.com/dev/dev/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/dev/dev/f2
https://asdfjkl.execute-api.my-region.amazonaws.com/prod/prod/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/prod/prod/f2
```
Instead I want to see:
```
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/dev/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/dev/f2
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/prod/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/prod/f2
```
Am I missing something or is this a bug? Thanks!
