### DISCUSSION TITLE
Error with golang on provided.al2

### DISCUSSION THREAD

**Discussion by harryzcy** [serverless/serverless#11667] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm getting `Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]` error when using `provided.al2`. How do I configure the functions exactly?

### Service configuration (serverless.yml) content

```yaml
service: example

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

package:
  patterns:
    - '!./**'
  individually: true

functions:
  exampleFunction1:
    handler: bin/functions/exampleFunction1
    package:
      patterns:
        - './bin/functions/exampleFunction1'
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
Moved to discussions, as it's more a usage support enquiry and not a bug report.

**Comment by G-OD** [comment]
You need to have a bootstrap binary in order for this to work. The easiest method would be to use the serverless-go-plugin. With that you can do something like this:

```yml
service: example
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

plugins:
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true

functions:
  exampleFunction1:
    handler: functions/exampleFunction1/main.go
```
