### DISCUSSION TITLE
How to create a Lambda Function having an existing rule as source event

### DISCUSSION THREAD

**Discussion by caadecarvalho** [serverless/serverless#11687] [Q&A]
Hi, is it possible to create a lambda function with a source event as an existing rule without creating a new rule? The code below is what I'm using and it works, but I end up with having a new rule for each function where I want to reuse it.

Code:
```
...

functions:
  indexFunc:
    handler: src/handlers/handler_daily_execution.lambda_handler
    events:
      - cloudwatchEvent: 
          name: indexFuncDailyMidnightRule
          event:
            arn: 
              - arn:aws:events:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:rule/DailyMidnightRule

...
```

This code works but it creates a new rule that maps to the existing rule but I want only that the lambda function maps to the existing rule.

Thanks.
