### DISCUSSION TITLE
how to read/have access to apikey customerId

### DISCUSSION THREAD

**Discussion by filenda** [serverless/serverless#11698] [Q&A]
```
  apiGateway:
    apiKeys:
      - name: ${self:custom.stage}-evansEventsAPIKey
        customerId: ${self:custom.secrets.EVENTS_CUSTOMER_ID}
```

How can I programatically access the customerId of an apikey. I've logged the input 'event' object from the default hello world lambda but didn't find the api key context containing the customer id.

Do you guys have any idea?
