### DISCUSSION TITLE
Asynchronous Invocation for scheduled events

### DISCUSSION THREAD

**Discussion by chrispytoes** [serverless/serverless#11694] [Q&A]
I am trying to make a scheduled event that takes an extended amount of time to run:
```
functions:
  poSync:
    handler: handler.poSync
    maximumEventAge: 21600
    events:
      - schedule:
          name: po-sync
          rate: rate(1 hour)
          enabled: true
```
However it's stopping after the `timeout` value set in the provider. I do not need a response of any kind, just run it and forget it.
