### DISCUSSION TITLE
How to set a specific handler with ECMAScript modules support?

### DISCUSSION THREAD

**Discussion by ajeecai** [serverless/serverless#11691] [Q&A]
Hi, 

I get a serverless project using typescript node, my purpose is that all of the handlers are `"module": "commonjs"` in tsconfig.json except one which is importing an npm module (compiled as ES module). 

I have searched issues and see this one https://github.com/serverless/serverless/pull/11212, so looks like the fix has been merged into main release. After I upgrade my building environment as 
> Environment: darwin, node 16.15.1, framework 3.26.0 (local) 3.26.0v (global), plugin 6.2.2, SDK 4.3.2

And in serverless.yml:
```
  chatgpt:
    handler: handler/startChat.startChat
    timeout: 30
    events:
      - http:
          path: /startChat
          method: post   
```
The code is placed at handler/startChat.ts, sls offline start is OK but when api access it complains: 
`require() of ES Module xxx from xxx not supported.`

When this file is changed to startChat.mjs, but sls offline start says `Typescript compilation failed. Please ensure handlers exists with ext .ts or .js`, 

So want to know if version 3.26.0 is including this ES module support, how to use it? 

Thanks
