### DISCUSSION TITLE
CONVERT_TO_BINARY is not working in the HTTP_PROXY integration

### DISCUSSION THREAD

**Discussion by Erdene-Ochir0417** [serverless/serverless#11734] [Q&A]
Hello
I am trying to redirect post request to external website in serverless framework without lambda function. But I can't convert request to binary.

full code:
```
service: sls-api 

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  
functions:
  redirect:
    handler: handler.redirect
    events:
      - http:
          path: /
          method: post
          cors: true
          integration: HTTP_PROXY
          request:
            uri: https://example.com/post/request
            contentHandling: CONVERT_TO_BINARY
```
