### DISCUSSION TITLE
compiler of serverless framework change value of environment  variable if it is number

### DISCUSSION THREAD

**Discussion by thanhduyluu** [serverless/serverless#11739] [Q&A]
I would like config `FOO: 10553291267149319188` is environment variable, after I use sls print or sls deploy the compiler of serverless framework changed my variable to `FOO: 10553291267149320000`.

if I change `FOO: "10553291267149319188"`, value of `FOO` still `"10553291267149319188"`, it's correct .

Anyone has problem same me or please can you tell me why compiler change value of my variable

I use serverless verson:

```
ubuntu@test-instance:~/serverless/packages/test-lambda-node$ node -v
v14.21.2

ubuntu@test-instance:~/serverless/packages/test-lambda-node$ yarn serverless --version
yarn run v1.22.19
warning ../../../package.json: No license field
$ /home/ubuntu/serverless/packages/test-lambda-node/node_modules/.bin/serverless --version
Framework Core: 1.83.3 (local)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
Done in 2.18s.
```

My `serverless.yml`

```
service: aws-node-express-api
frameworkVersion: '1.83.3'
plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 127.0.0.1
    port: 3006
  stages:
    dev: 
      STAGE: dev
      FOO: BAR
      PROVISIONED_CONCURRENCY: 15
    test: 
      STAGE: test
      FOO: 10553291267149319188
      PROVISIONED_CONCURRENCY: 15
    prod: 
      STAGE: prod
      FOO: prod
      PROVISIONED_CONCURRENCY: 15
    
provider:
  name: aws
  runtime: nodejs18.x
  profile: duyluu
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'ap-east-1'}
  endpointType: REGIONAL
  environment:
    NODE_ENV: production
    FOO: ${self:custom.stages.${self:provider.stage}.FOO}

functions:
  apiExpressTestEnv:
    environment:
      FOO: ${self:custom.stages.${self:provider.stage}.FOO}
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /env
          method: GET
  
  apiExpressTestCI:
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server_api.handler
    events:
      - http:
          path: /api
          method: GET
      - http:
          path: /api/env
          method: GET
```

Output of `sls print`

```
ubuntu@test-instance:~/serverless/packages/test-lambda-node$ yarn sls print
yarn run v1.22.19
warning ../../../package.json: No license field
$ /home/ubuntu/serverless/packages/test-lambda-node/node_modules/.bin/sls print
service: aws-node-express-api
frameworkVersion: 1.83.3
plugins:
  - serverless-offline
custom:
  serverless-offline:
    host: 127.0.0.1
    port: 3006
  stages:
    dev:
      STAGE: dev
      FOO: BAR
      PROVISIONED_CONCURRENCY: 15
    test:
      STAGE: test
      FOO: 10553291267149320000
      PROVISIONED_CONCURRENCY: 15
    prod:
      STAGE: prod
      FOO: prod
      PROVISIONED_CONCURRENCY: 15
provider:
  stage: test
  region: ap-east-1
  name: aws
  runtime: nodejs18.x
  profile: duyluu
  endpointType: REGIONAL
  environment:
    NODE_ENV: production
    FOO: 10553291267149320000
functions:
  apiExpressTestEnv:
    environment:
      FOO: 10553291267149320000
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /env
          method: GET
    name: aws-node-express-api-test-apiExpressTestEnv
  apiExpressTestCI:
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server_api.handler
    events:
      - http:
          path: /api
          method: GET
      - http:
          path: /api/env
          method: GET
    name: aws-node-express-api-test-apiExpressTestCI

Done in 2.27s.
```
