### DISCUSSION TITLE
Missing dependencies which aren't dev-specific - for specific stage

### DISCUSSION THREAD

**Discussion by eghernqvist** [serverless/serverless#11744] [Q&A] [answered]
Hi!
I'm deploying one of our SLS services to AWS Lambda and it's always worked fine for production but I noticed yesterday that the `dev` stage is broken with a `Error: Cannot find module 'readable-stream'` error. 
The module `readable-stream` is a dependency of `mongodb` which seems to be included in the `node_modules` in my production deploy but not in the deploy to the `dev` stage. 

I've inspected the artifacts from the install job and the module is in there. I downloaded the Lambda deployment package for both `prod` and `dev` and it's there in `prod` but missing in `dev`. It's also included in the package generated via `sls package --stage dev`.

Here are the deployment scripts for both stages, running in GitLab CI pipeline:

```
npm:install:
  stage: install
  script:
    - npm install
  artifacts:
    untracked: true
  only:
    - tags
    - develop

deploy:prod:
  environment: production
  stage: deploy
  dependencies:
    - npm:install
  script:
    - npm install -g serverless@3.26
    - serverless deploy --stage prod --verbose
  only:
    - tags

deploy:dev:
  environment: staging
  stage: deploy
  dependencies:
    - npm:install
  script:
    - npm install -g serverless@3.26
    - serverless deploy --stage dev --verbose
  only:
    - develop
```

Here's my `package.json`

```
{
  ...
  "dependencies": {
    "@sendgrid/mail": "^7.7.0",
    "cors": "^2.8.5",
    "dayjs": "^1.10.7",
    "express": "^4.17.1",
    "express-basic-auth": "^1.2.1",
    "lodash": "^4.17.21",
    "md5": "^2.3.0",
    "moment": "^2.29.1",
    "mongodb": "^3.7.3",
    "mongodb-extjson": "^2.1.5",
    "node-fetch": "^2.6.5",
    "openai": "^3.0.0",
    "pug": "^3.0.2",
    "qrcode": "^1.4.4",
    "serverless-http": "^2.7.0"
  },
  "devDependencies": {
    "serverless-offline": "^8.8.0"
  }
  ...
}
```

And part of `serverless.yml`

```
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  [...]

plugins:
  - serverless-offline

custom:
  enabled:
    dev: false
    prod: true
    other: false
  [...]

functions:
  slingate:
    name: slingate-${opt:stage}
    handler: slingate/handler.handler
    events: [...]
  api:
    name: ${file(sls-config/${opt:stage}.js):functionName}
    environment: ${file(sls-config/${opt:stage}.js):environment}
    handler: handler.handler
    events: [...]

```

Anyone have a clue as to where I can start looking? I see no reasonable explanation after a bit of looking around.

Thanks!
