### DISCUSSION TITLE
How to use GeoRestriction to Cloudfront service

### DISCUSSION THREAD

**Discussion by AnthonyGWeb** [serverless/serverless#11758] [General]
Hi everybody,

After a lot of research, I used serveless to create Cloudfront bucket for my webApp. But I don't find how to set an geolocation restriction in my serverless.yml. I used also serverless-single-page-app-plugin.

Here is my serverless.yml (I have ommited a part of code): 

```
plugins:
  - serverless-single-page-app-plugin

resources:
  Resources:
    CloudFrontBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    CloudFrontBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: CloudFrontBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                    "", [
                      "arn:aws:s3:::",
                      { "Ref": "CloudFrontBucket" },
                      "/*"
                  ]
                ]

    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName:
                Fn::Join: [
                    "", [
                    { "Ref": "CloudFrontBucket" },
                    ".s3.amazonaws.com"
                  ]
                ]
              ## An identifier for the origin which must be unique within the distribution
              Id: ${self:custom.projectId}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          Enabled: 'true'
          HttpVersion: 'http2'
          Aliases: ${file(record_sets.yml):Aliases}
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html

          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: ${self:custom.projectId}
            Compress: true
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            AcmCertificateArn: ${env:ARN_DOMAIN_CERTIFICATE}
            MinimumProtocolVersion: 'TLSv1.2_2021'
            SslSupportMethod: 'sni-only'

    ## Attach domain to cloudfront
    WebsiteDNSName:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${env:HOSTED_ZONE_ID}
        RecordSets: ${file(record_sets.yml):RecordSets}

```

And I would like add an GeoRestriction whitelist like in AWS console. Is it possible ? 🤔 

Thanks for your help.
