### DISCUSSION TITLE
Error whey using image from dockerhub or public ecr image

### DISCUSSION THREAD

**Discussion by aljeshishe** [serverless/serverless#11764] [General]
I want to create reusable lambda and push it to dockerhub or public ecr image
But when I'm trying to use docker image from dockerhub or public ecr image I got error:
```
The region "undefined" of the ECR image "docker.io/aljeshishe/ec2scheduler:latest" must match provider region "eu-central-1".
```
My serverless.yml
```
service: ec2scheduler
provider:
  name: aws
  runtime: python3.9
  region: eu-central-1

functions:
    handler:
      image:
        uri: docker.io/aljeshishe/ec2scheduler:latest
```
Same problem with ECR public image: public.ecr.aws/z5t6z9w7/ec2scheduler:latest
It looks like this is "by design" behavior, but someone probably knows how to work around this. 
I don't want to use lambda layers as there are a lot of limitations(like layer size).
