### DISCUSSION TITLE
how to reference import value

### DISCUSSION THREAD

**Discussion by deeksha-schneider** [serverless/serverless#11761] [Q&A]
below is the template:

```
resources:
  Resources:
    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - "ApiGatewayRestApi"
            - "RootResourceId"
        PathPart: auth-registry-ds/oauth2/token
        RestApiId:
          Ref: "ApiGatewayRestApi"
    ProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: ProxyResource
        RestApiId:
          Ref: "ApiGatewayRestApi"
        HttpMethod: POST 
        MethodResponses:
          - StatusCode: 200
        Integration:
          IntegrationHttpMethod: POST
          Type: HTTP
          Uri: http://internal-das.com/user
          IntegrationResponses:
            - StatusCode: 200
```
and below is failing  
Error:
Template error: every Fn::GetAtt object requires two non-empty parameters, the resource name and the resource attribute
   Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - !ImportValue <name of export>
            - "RootResourceId"

Can someone suggest how can write value of RootResourceId and ApiGatewayRestApi
