### DISCUSSION TITLE
Can somebody please help me how to get the Lambda function ARN into another Lambda Environment variables?

### DISCUSSION THREAD

**Discussion by vikaskoppineedi** [serverless/serverless#11776] [Q&A]
```
  lambda_one:
    handler: lambda_code/lambda_one/lambda_one.entrypoint
    timeout: 60
    memorySize: 128
    description: "This Lambda will be responsible for Getting events and pusing into an SQS Queue" # optional, Description to publish to AWS
    tracing: Active
    environment: ${self:custom.environment.lambda_one.${self:provider.stage}}
```

```
  lambda_two:
    handler: lambda_code/lambda_one/lambda_one.entrypoint
    timeout: 60
    memorySize: 128
    description: "This Lambda will be responsible for Getting events and pusing into an SQS Queue" # optional, Description to publish to AWS
    tracing: Active 
    environment: ${self:custom.environment.lambda_one.${self:provider.stage}}
```

how to inject Lambda two ARN as an environment variable into Lambda one?
