### DISCUSSION TITLE
How to deploy a separate stage than would use less resources when using base api gateway

### DISCUSSION THREAD

**Discussion by piotrwalczak1** [serverless/serverless#11781] [General]
I have a "base" (let's call it "base-api") api that I deploy and I am using this base api to add some services using api gateway reference:
```
 apiGateway:
    # Attach to an externally created REST API via its ID:
    restApiId: xxxx
    # Root resource ID, represent as / path
    restApiRootResourceId: xxxx
```

So I am deploy a base api first (a blueprint for other services to be connected) and use that base gateway for deploying other services like service1.yml - for example users  endpoints,  service2.yaml - some other endpoints.

```
sls deploy --stage "base-api" --config some-config.yml
then:
sls deploy --stage "base-api" --config service1.yaml --> this is using apiGateway reference in yaml
sls deploy --stage "base-api" --config service2.yaml --> this is using apiGateway reference in yaml
```
This would result in 1 api deployed using "base-api" stage with corresponding services with endpoints added.

BUT:
I would like to have a seperate stage (within "base-api", not a separate one) that would have a second stage, but that will contain less methods than the first stage.  When I am doing like:

```
sls deploy --stage "second-stage" --config some-config-applied-with-methods-for-only-this-stage.yml --verbose
```

I am getting the full copy of the "base-api" stage with all methods deployed. I would like to have for example only two methods there. I haven't figured out how to do this. Any help appreciated.
