### DISCUSSION TITLE
Weekly cron expression shows invalid, but daily works

### DISCUSSION THREAD

**Discussion by chrispytoes** [serverless/serverless#11795] [Q&A] [answered]
I'm trying to make a cron schedule for every Friday at 10 AM, like this: `cron(0 10 ? * FRI *)`, but I'm getting back this error: `Parameter ScheduleExpression is not valid.`.

I have other schedules for daily tasks that work fine though:

 - `cron(0 0 * * ? *)`
 - `cron(55 7 * * ? *)`
 - `cron(0 * * * ? *)`
 - `cron(0 7,12 * * ? *)`

Full example:

```
functions:
  example:
    description: example
    handler: src/example.example
    maximumEventAge: 21600
    events:
      - schedule:
          name: example
          rate: cron(0 10 ? * FRI *)
          timezone: America/Chicago
          enabled: true
```
