### DISCUSSION TITLE
Error: EACCES: permission denied, scandir '/var/agentx'

### DISCUSSION THREAD

**Discussion by yudao** [serverless/serverless#11807] [Q&A] [answered]
Hi all ✋ 

I'm working to upgrade an old repository with Serverless framework:

```json
{
    "serverless": "^2.28.6",
    "serverless-localstack": "^0.4.28",
    "serverless-offline": "^8.2.0",
    "serverless-offline-lambda": "^1.0.6",
    "serverless-plugin-optimize": "^4.2.1-rc.1",
    "serverless-plugin-split-stacks": "^1.11.2",
    "serverless-plugin-warmup": "^5.2.2",
}
```
I upgraded Serverless to last version and all these plugin too.

Now, when I try to package I have unexpected access errors :

```sh
SLS DEBUG=* serverless package --aws-profile myProfile

Packaging test-layer for stage dev (us-east-1)
Environment: darwin, node 16.19.1, framework 3.28.1 (local), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error: EACCES: permission denied, scandir '/var/agentx'
```

All project directories and files  are "chown" by me in group staff.

I don't have the problem with old version. I know It's a root problem but why 🥲 

If someone could help me I'm driving completely mad with this 😠 🙏 

Yu.

**Comment by yudao** [comment]
~~Sorry, was my node tool manager (Volta). With using curl/bash method all is fine. 😅~~

With trying curl/bash installation it was ok the first time. Next I loop in same error..... 😞

**Comment by yudao** [comment, marked as answer]
Was due to bad understood root on include paths 🤣 

```yaml
layers:
  test:
    path: layers/test/nodejs
    name: ${sls:stage}-test
    retain: false
    package:
      include:
        - '/**' <= take entire root 🤯 
```

Simple solution 👍🏼 
```yaml
layers:
  test:
    path: layers/test/nodejs
    name: ${sls:stage}-test
    retain: false
    package:
      include:
        - './**' <= from current path 💡 
```

Yu.
