### DISCUSSION TITLE
Unable to update S3 bucket configurations.

### DISCUSSION THREAD

**Discussion by farhanuddin-westwing** [serverless/serverless#11813] [General]
So, I created this custom S3 bucket via the following configurations in serverless.yml: 

```
provider:
  name: aws
  .....
  s3:
    bucketOne:
      name: ${self:custom.buckets.appname_bucket}
```
      
 After that, the bucket was created in S3 on deployment. 
 
 Later on, I wanted to do configuration on this bucket and block public access on it. So, I added the following configs to it with reference to:- https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#s3-buckets
 
 ```
provider:
  name: aws
  ....
   s3:
    bucketOne:
      name: ${self:custom.buckets.appname_bucket}
      accessControl: Private
      publicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```

But S3 isn't updating the configs of the bucket and not blocking the public access. Plus, there is no error on the pipeline as well.

Can you please tell what I am doing wrong or what can be done to fix this.

Thank you.
