### DISCUSSION TITLE
Serverless ECR Image configuration

### DISCUSSION THREAD

**Discussion by xinweiiiii** [serverless/serverless#11866] [General]
Was setting up serverless to run container and i am looking to configure KMS encryption and Tag Immutability via the serverless.yml file. I am not able to find any documentation in the serverless folder. 

```
  ecr:
    images:
      appimage:
        path: ./
```

Expected:
```
  ecr:
    encryption: true # To be added
    tagImmutability: true  # To be added
    images:
      appimage:
        path: ./
```
