### DISCUSSION TITLE
My packaging failed with success?

### DISCUSSION THREAD

**Discussion by alejandroch1202** [serverless/serverless#11877] [Q&A]
When I deploy functions directly from AWS Lambda the size of the files it's about hundreds of Bytes, no more. 
Using Serverless Framework, I want to exclude all files in order to just upload the code of the specific function. So, my serverless.yml I added: 
```yml
package:
  individually: true
  patterns:
    - "!*/**"
    - "!**"
```

And in the functions I want to include just the code for each function:
```yml
functions:
  getUser:
    handler: src/getUser/handler.getUser
    events:
      - http:
          path: users/{id}
          method: GET
    package:
      patterns:
        include:
          - "src/getUser/handler.js"
  getUsers:
    handler: src/getUsers/handler.getUsers
    events:
      - http:
          path: users
          method: GET
    package:
      patterns:
        include:
          - "src/getUsers/handler.js"
```

When I try to `sls deploy` I get the:
```sh
Packaging gmp for stage dev (eu-central-1)
Environment: linux, node 18.14.1, framework 3.28.1, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No file matches include / exclude patterns
```

The thing is when I check the `.serverless` folder my code is correctly packaged, just as I want (just the code of the specific function) and it's size is just a few hundreds of Bytes. But it doesn't let me deploy due the Error.

- Is that the way that I should exclude / include trying to make it work as I want?
- Am I missing something?
- Should be this a issue?
