### DISCUSSION TITLE
Define lambda function with serverless and Docker reference, still causes "missing handler" error.

### DISCUSSION THREAD

**Discussion by mikkelAtVisma** [serverless/serverless#11876] [Q&A] [answered]
Hi everyone, I've been following official documentation to build a docker reference in my serverless file.

In this solution, I've been uploading my docker image to ECR manually, and then just referencing it here in the serverless.yml file.

Unfortunately, it seems that the docker image is not picked up by serverless.

We get either an error about a "handler" missing - or if we do specify the handler, we get that it is packaged as a .zip and not a docker image.

Serverless.yml:

```
service: ${self:custom.serviceName}
description: Serverless stack

package:
  exclude:
    - "**"
  include:
    - "./src/**"
    - ".env"

provider:
  name: aws
  runtime: provided
  versionFunctions: false
  timeout: 30
  stage: test
  cfnRole: "arn:aws:iam::${self:custom.account_id.${self:custom.stage}}:role/cloudformation-serverless"
  deploymentBucket: ${self:custom.serviceName}-${self:custom.stage}-serverless-deployment
  apiName: ar-solver
  ecr:
    scanOnPush: true
    images:
      java-xlsx:
        uri: ${self:custom.xlsxImageName}
  usagePlan:
    throttle:
      burstLimit: 300
      rateLimit: 300
  logs:
    restApi:
      level: INFO
  tracing:
    apiGateway: ${self:custom.enable_xray.${self:custom.stage}}
    lambda: ${self:custom.enable_xray.${self:custom.stage}}
  environment:
    ECS_CLUSTER: ${self:custom.ecsCluster}
    ECS_TASK_DEFINITION: ${self:custom.ecsTaskDefinition}
    ECS_SUBNET_A: ${self:custom.ecsSubnetA}
    ECS_SUBNET_B: ${self:custom.ecsSubnetB}
    ECS_SUBNET_C: ${self:custom.ecsSubnetC}
    ECS_SECURITY_GROUP: ${self:custom.securityGroupId}
    ECS_CONTAINER_NAME: ${self:custom.ecrImageName}
    JOB_TABLE_NAME: ${self:custom.jobTableName}
    JOB_TABLE_KEY: ${self:custom.jobTableKey}
    JOB_STATUS_FIELD: ${self:custom.jobStatusField}
    JOB_ECS_ARN_FIELD: ${self:custom.jobEcsArnField}
    JOB_ERROR_FIELD: ${self:custom.jobErrorField}
    JOB_START_TIME_FIELD: ${self:custom.jobStartTimeField}
    JOB_STOP_TIME_FIELD: ${self:custom.jobStopTimeField}
    JOB_CLIENT_ID_FIELD: ${self:custom.jobClientIdField}
    JOB_CUSTOMER_ID_FIELD: ${self:custom.jobCustomerIdField}
    JOB_USER_ID_FIELD: ${self:custom.jobUserIdField}
    JOB_PARENT_ID_FIELD: ${self:custom.jobParentIdField}
    JOB_NBR_OF_WEEKS_FIELD: ${self:custom.jobNbrOfWeeksField}
    JOB_PERIOD_START_FIELD: ${self:custom.jobPeriodStartField}
    JOB_PERIOD_END_FIELD: ${self:custom.jobPeriodEndField}
    JOB_CLIENT_VERSION_FIELD: ${self:custom.jobClientVersionField}
    JOB_ACCEPTED_FIELD: ${self:custom.jobAcceptedField}
    JOB_REJECTED_FIELD: ${self:custom.jobRejectedField}
    LAUNCHDARKLY_TABLE_NAME: ${self:custom.launchdarklyTableName}
    LAUNCHDARKLY_TABLE_KEY: ${self:custom.launchdarklyTableKey}
    LAUNCHDARKLY_FLAG_STATES_FIELD: ${self:custom.launchdarklyFlagStatesField}
    AUTHORIZER_TABLE_NAME: ${self:custom.authorizerTableName}
    AUTHORIZER_TABLE_KEY: ${self:custom.authorizerTableKey}
    DASHBOARD_TIME_TABLE_NAME: ${self:custom.dashboardTimeTableName}
    DASHBOARD_TIME_TABLE_KEY: ${self:custom.dashboardTimeTableKey}
    DASHBOARD_TIME_TABLE_FIELD: ${self:custom.dashboardTimeTableField}
    XML_BUCKET_NAME: ${self:custom.xmlBucketName}
    RESULT_FOLDER: ${self:custom.s3ResultFolder}
    REQUEST_FOLDER: ${self:custom.s3RequestFolder}
    FC_ERROR_FOLDER: ${self:custom.s3FCErrorFolder}
    XSD_FOLDER: ${self:custom.s3XsdFolder}
    SOLVER_TIMEOUT: ${self:custom.solveTimeout}
    SOLVER_TIMEOUT_SHORT: ${self:custom.solveTimeoutShort}
    USE_SHORT_TIMEOUT: ${self:custom.useShortTimeouts}
    STAGE: ${self:custom.stage}
    AWS_DEFAULT_REGION: ${self:custom.aws_region}
    XLSX_FOLDER: ${self:custom.s3XlsxFolder}

plugins:
  - serverless-aws-documentation
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-plugin-subscription-filter


custom:
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: python3
  useShortTimeouts: "False"
  serviceName: ar-solver-service
  xlsxImageName: [].dkr.ecr.eu-west-1.amazonaws.com/java:latest
  stage: ${opt:stage, self:provider.stage}
  solveTimeout: 7200 # Solver timeout in seconds
  solveTimeoutShort: 120
  jobTableName: job
  jobTableKey: id
  jobStatusField: job_status
  jobEcsArnField: ecs_task_arn
  jobErrorField: error_text
  jobStartTimeField: start_time
  jobStopTimeField: stop_time
  jobClientIdField: client_id
  jobCustomerIdField: customer_id
  jobUserIdField: user_id
  jobClientVersionField: client_version
  jobParentIdField: parent_id
  jobNbrOfWeeksField: nbr_of_weeks
  jobPeriodStartField: period_start
  jobPeriodEndField: period_end
  jobAcceptedField: accepted
  jobRejectedField: rejected
  launchdarklyTableName: launchdarkly
  launchdarklyTableKey: user_id
  launchdarklyFlagStatesField: flag_states
  authorizerTableName: authorizer_table
  authorizerTableKey: jwks_id
  dashboardTimeTableName: dashboard_time
  dashboardTimeTableKey: id
  dashboardTimeTableField: latest_upload
  dashboardApiUrl: ${env:DASHBOARD_API_URL}
  dashboardApiKey: ${env:DASHBOARD_API_KEY}
  xmlBucketName: ${self:custom.serviceName}-${self:custom.stage}-xml-bucket
  healthCheckRequestsBucketName: ${env:HEALTHCHECK_REQUEST_BUCKET_NAME}
  healthCheckRequestsObjectName: ${env:HEALTHCHECK_REQUEST_OBJECT_NAME}
  ecrImageName: solver-wrapper
  s3RequestFolder: "request"
  s3ResultFolder: "result"
  s3XlsxFolder: "xlsx_jobs"
  s3FCErrorFolder: "fc_error_payloads"
  s3XsdFolder: "xsds"
  deploymentBucket: ${self:custom.serviceName}-${self:custom.stage}-serverless-deployment
  ecsTaskDefinition: "arn:aws:ecs:${self:provider.region}:#{AWS::AccountId}:task-definition/${self:custom.serviceName}-task-definition"
  ecsCluster: "${self:custom.serviceName}-fargate-cluster"
  taskExecutionRole: "arn:aws:iam::#{AWS::AccountId}:role/${self:custom.serviceName}-execution-role"
  taskRunRole: "arn:aws:iam::#{AWS::AccountId}:role/${self:custom.serviceName}-task-role"
  taskRunRoleName: "${self:custom.serviceName}-task-role"
  ecsSubnetA:
    "Fn::ImportValue": "private-subnet-a"
  ecsSubnetB:
    "Fn::ImportValue": "private-subnet-b"
  ecsSubnetC:
    "Fn::ImportValue": "private-subnet-c"
  securityGroupId:
    "Fn::ImportValue": "security-group-id"

  set_schedule_healtchchecks:
    test: false
    stage: false
    prod: true
    local: false
    offline: false

  enable_xray:
    test: true
    stage: true
    prod: true
    local: false
    offline: false


  launchdarkly_sdk_key:
    test: ${env:LAUNCHDARKLY_SDK_KEY_TEST}
    stage: ${env:LAUNCHDARKLY_SDK_KEY_STAGE}
    prod: ${env:LAUNCHDARKLY_SDK_KEY_PROD}

  domainStageIdentifier:
    test: int.test
    stage: stag
    prod: prod
    local: local
    offline: offline

  customDomain:
    domainName: ${self:custom.domainName}
    basePath: ""
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: regional

  serverless-offline:
    host: 0.0.0.0

  documentation:
    ${file(resources/cfn-templates/documentation.yml)}

  roles:
    ${file(resources/cfn-templates/roles.yml)}

functions:

  xlsx_test:
    image:
      name: java-xlsx
      command: ["com.visma.omed.serverless.Handler::handleRequest"]
    role: arn:aws:iam::${self:custom.account_id.${self:custom.stage}}:role/lambda-start-role
    environment:
      LAMBDA_IMAGE: 770210762497.dkr.ecr.eu-west-1.amazonaws.com/java:latest
    events:
      - http:
          path: xlsx_test/{id}
          method: get
          authorizer:
            type: REQUEST
            name: jobIdAuthFunc
            resultTtlInSeconds: 0
          request:
            parameters:
              paths:
                id: true
          documentation:
            summary: Get job
            description: Get a job.
            pathParams:
              - name: id
                description: Id of job
            methodResponses:
              - statusCode: '200'
                description: 'A Job'
                responseModels:
                  "application/xml": Job
              - statusCode: '404'
                description: 'Job not found'
              - statusCode: '403'
                description: 'Wrong access key'
              - statusCode: '500'
                description: 'Internal server error'
```
Dockerfile:

```
FROM public.ecr.aws/lambda/java:11

# https://gallery.ecr.aws/lambda/java
# https://hub.docker.com/r/amazon/aws-lambda-java
# Copy function code and runtime dependencies from Maven layout
COPY target/classes ${LAMBDA_TASK_ROOT}
COPY target/dependency/* ${LAMBDA_TASK_ROOT}/lib/
COPY target/or-tools/ortools-linux-x86-64/* ${LAMBDA_TASK_ROOT}/lib/ortools-linux-x86-64/
COPY bootstrap /var/runtime/
RUN chmod +x /var/runtime/bootstrap

# Set the CMD to your handler
CMD ["com.visma.omed.serverless.Handler::handleRequest"]
```
However, the current config will keep giving us the problem:     Missing "handler" property in function "xlsx_test". Please make sure you point to the correct lambda handler. For example: handler.hello. Please check the docs for more info

Which, I think makes no sense - as we are using the image reference.

What is the expected output is what is written in the serverless documentation - namely that we can define a docker image and reference it from ECR in AWS.

We are running version 2.4.0 of Serverless...
