### DISCUSSION TITLE
using lambda docker nestjs ecr  Runtime exited without providing a reason Runtime.ExitError

### DISCUSSION THREAD

**Discussion by Cariaga** [serverless/serverless#11886] [Q&A]
Dockerfile
```
FROM public.ecr.aws/lambda/nodejs:14
WORKDIR /app
# Copy package.json and package-lock.json
COPY package*.json ./
RUN npm install --save-dev

COPY . .
EXPOSE 3000
ENTRYPOINT [ "node", "./dist/src/main.js" ]
CMD [ "node", "./dist/src/main.js" ]
```
serverless.yml
```
service: serverless-app

frameworkVersion: '3'
plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
provider:
  name: aws
  stage: default
  region: my-region
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:*
        - s3:*
      Resource: "*" 
      
  logRetentionInDays: 7
  logs:
    # Change the LogGroupName to a unique name
    apiGateway: false
    websocket: false
    cloudwatch:
      logGroup:
        name: serverless-app-default-main-loggroup
        retentionInDays: 7
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      serverless-clocking:
        path: radom-number.dkr.ecr.ap-northeast-1.amazonaws.com/serverless-app:latest
functions:
  main:
    image: radom-number.dkr.ecr.ap-northeast-1.amazonaws.com/serverless-app:latest
    memorySize: 4096 # function specific
    timeout: 30 # optional, in seconds, default is 6
    url: true
    events:
      - http:
          cors: true
          method: ANY
          path: '{proxy+}'

```
**main.js**
```


import { NestFactory } from '@nestjs/core';
import serverlessExpress from '@vendia/serverless-express';
import { Callback, Context, Handler } from 'aws-lambda';
import { AppModule } from './app.module';

let server: Handler;
async function bootstrap(): Promise<Handler> {
  const app = await NestFactory.create(AppModule);
  await app.init();

  const expressApp = app.getHttpAdapter().getInstance();
  return serverlessExpress({ app: expressApp });
}

export const handler: Handler = async (
  event: any,
  context: Context,
  callback: Callback,
) => {
  server = server ?? (await bootstrap());
  return server(event, context, callback);
};
```
package.json
```
{
  "name": "app",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "main": "dist/src/main.js",
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest --watchAll=false --maxWorkers=1 --detectOpenHandles",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
}
}
```

issue
```
 Runtime exited without providing a reason
Runtime.ExitError
duration: 1053.15 ms	Billed Duration: 1054 ms	Memory Size: 4096 MB	Max Memory Used: 77 MB	
```
error in lambda
lambda some how crashes

what is working
cloudformation,api-gateway, ecr
