### DISCUSSION TITLE
Serverless deployment fails with "Cannot resolve variable" error when inputs are used in Github composite action (or reusable workflow)

### DISCUSSION THREAD

**Discussion by ezmiller** [serverless/serverless#11924] [Q&A]
I have a Github composite action that uses the Serverless Framework to deploy my stack. The action takes two inputs, `serverless-path` and `stage`, and includes the following steps:

```
# ... action metadata ...
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16.13.0'
        cache: yarn

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: *** 

    - name: Install project dependencies
      shell: bash
      run: yarn install --frozen-lockfile
      working-directory: ${{ inputs.serverless-path }}

    - name: debug step
      shell: bash
      run: yarn run serverless print --stage ${STAGE}
      working-directory: ${{ inputs.serverless-path }}
      env:
        STAGE: ${{ inputs.stage }} 
```

However, when I run this action, the serverless command fails with the following error:

```
Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.SHOP": Value not found at "self" source
```

Interestingly, if I replace `${{ inputs.stage }}` with a static string like `dev`, the serverless command runs successfully. This makes me suspect that the problem has to do with how inputs are passed to the serverless command.

What could be causing this error and how can I fix it?

**Comment by ezmiller** [comment]
Just to fill this out a little bit more. One thing, I've tried to demonstrate that this has something to do with nesting in particular, is adjust my serverless.yml file to not use the nesting, but just pull the value that should be set based on the call made from the github action that does: `yarn serverless print --stage ${STAGE}`. So my serverless config looks like: 
```
provider: 
  ...
  environment:
    CUSTOM_STAGE: ${self:custom.stage}
    OPT_STAGE: ${opt:stage}
    SLS_STAGE: ${sls:stage}
    # SHOP: ${self:custom.environment.${self:custom.stage}.SHOP}
...
custom:
  stage: ${opt:stage, 'default'}
```
And then when the print command successfully executes, I get:
```
provider:
  ...
  CUSTOM_STAGE: dev
  OPT_STAGE: dev
  SLS_STAGE: dev
```
