### DISCUSSION TITLE
I can't get the --param to resolve while using serverless-compose.

### DISCUSSION THREAD

**Discussion by jag-ermeister** [serverless/serverless#11934] [General]
I have a `serverless-compose.yml` that looks like this:

```
services:
  app-network:
    path: app-network
  app-db:
    path: app-db
    params:
      myothersecuritygroup: ${app-network.myothersecuritygroup}
```

The relevant part of my `app-network` service `serverless.yml` looks like this:
```
useDotenv: true
service: mimic
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  memorySize: 128
  timeout: 10

resources:
  Resources:
...
    MyVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: my-vpc

...
    MySecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for RDS instance
        VpcId: !Ref MyVPC

    MyOtherSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Another security group
        VpcId: !Ref MyVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
            SourceSecurityGroupId: !GetAtt MySecurityGroup.GroupId
  Outputs:
    myothersecuritygroup:
      Value: !Ref MyOtherSecurityGroup
```

And finally my `app-db` service `serverless.yml` looks like the following:

```
useDotenv: true
service: mimic
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  memorySize: 128
  timeout: 10

resources:
  Resources:
    RDSInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: ${env:DB_NAME}
        Engine: postgres
        DBInstanceClass: db.t3.micro
        MasterUsername: ${env:DB_USER}
        MasterUserPassword: ${env:DB_PASSWORD}
        AllocatedStorage: 5
        DBSubnetGroupName: ${env:DB_SUBNET_GROUP_NAME}
        VPCSecurityGroups:
          - ${param.myothersecuritygroup}
```

Every time I run this, I get the following error:
```
CREATE_FAILED: RDSInstance (AWS::RDS::DBInstance)
Resource handler returned message: "Invalid security group , groupId= ${param.myothersecuritygroup}, groupName=. (Service: Rds, Status Code: 400, Request ID: 149aa576-1def-4610-96d2
-055cc2a31d09)" 
```

In the compose.log file I see this:
```
app-db › Running "serverless deploy --stage dev --param myothersecuritygroup=sg-0eb6c1525baa12380"
```
And then I see the error mentioned above a bit later in the file.

This feels like a bug, but I'm not entirely sure.  Has anybody seen this before?  Even when I run the `serverless deploy --stage dev --param myothersecuritygroup=sg-0eb6c1525baa12380` command directly, I see the same here.  It appears that `${param.myothersecuritygroup}` never evaluates and it is interpreted locally.  If I put the raw security group ID in there, everything deploys just fine.  Any ideas?
