### DISCUSSION TITLE
Unable to set a firehose delivery stream as the event source within serverless.yml

### DISCUSSION THREAD

**Discussion by katebry** [serverless/serverless#11948] [Q&A]
Hey 👋🏻
I'm trying to set up a Lambda that uses a Data Firehose as the event source.
However I keep getting a failure when I run `sls deploy`: `Invalid request provided: Unrecognized event source, must be kinesis, dynamodb stream or sqs.`
To test my logic I swapped out the Firehose delivery stream for a Kinesis Data Stream and this worked - so my question is, is it currently possible to set a Firehose as an event source within `serverless.yml`?

I'm using Serverless v3

Code: 

```
functions:
  transformer:
    handler: index.handler
    events:
      - stream:
          type: kinesis
          arn: <firehose_arn>
```
