### DISCUSSION TITLE
AWS API Gateway proxy + CORS

### DISCUSSION THREAD

**Discussion by pritamrungta** [serverless/serverless#11942] [Q&A]
Serverless(version=3.30.1) deploy throws the following error:
`Warning: You're using the AWS_PROXY in combination with response configuration in your function "web-server". Serverless will remove this configuration automatically before deployment.`
<br>
serverless.yml ->
```yaml
functions:
  web-server:
    handler: app.handler
    events:
      - http: ANY /
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: "http://localhost:3000"
            headers:
              - Content-Type
              - Content-Encoding
              - Accept-Encoding
              - Access-Control-Allow-Origin
              - Authorization
          response:
            headers:
              Cross-Origin-Opener-Policy: "'same-origin'"
              Cross-Origin-Embedder-Policy: "'require-corp'"
              Cross-Origin-Resource-Policy: "'same-origin'"
```

Is this because of the custom CORS configuration? Could you please help on how I can resolve this issue, whilst keeping the cors config(origin+headers) intact.
