### DISCUSSION TITLE
Pointing Two Authorizers to Same Lambda Function

### DISCUSSION THREAD

**Discussion by RajeevMasseyTR** [serverless/serverless#11958] [General]
These are some excerpts from ther serverless yml 

```
functions:
  - ${file(authorizer/src/templates/authorizer-function.yml)}
```

```
  authorizer:
    name: AuthorizerFunction
    arn: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:custom.regionalResourceNamePrefix}-${self:custom.component}-${self:provider.installation}-authorizer
    resultTtlInSeconds: 900
    identitySource: method.request.header.Authorization, method.request.header.X-Application-EID
    type: request

  noApplicationContextAuthorizer:
    name: NoApplicationContextAuthorizer
    arn: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:custom.regionalResourceNamePrefix}-${self:custom.component}-${self:provider.installation}-authorizer
    resultTtlInSeconds: 900
    identitySource: method.request.header.Authorization
    type: request
```

Some excerpts from the authorizer-function.yml

```
AuthorizerFunction:
  description: Backend-to-backend Authorizer Lambda Function
  name: ${self:custom.regionalResourceNamePrefix}-${self:custom.component}-${self:provider.installation}-authorizer
  iamRoleStatementsName: ${self:custom.regionalResourceNamePrefix}-${self:custom.component}-${self:provider.installation}-authorizer
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "ssm:GetParameter"
       - "ssm:PutParameter"
      Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/a${self:custom.assetId}/token/${self:provider.stage}/**"
  handler: ${self:custom.runtimeMap.${self:custom.runtimeMapKeyEnvMap.${self:custom.buildenv}}.handler.function}
  runtime: ${self:custom.runtimeEnvMap.${self:custom.buildenv}}
  provisionedConcurrency: ${self:custom.${self:custom.buildenv}.provisionedConcurrency}
  concurrencyAutoscaling: ${self:custom.${self:custom.buildenv}.concurrencyAutoscaling}
  package:
    artifact: authorizer/${self:custom.runtimeMap.${self:custom.runtimeMapKeyEnvMap.${self:custom.buildenv}}.artifactPath}/authorizer.zip
  environment:
    //values
  tags:
    service: a${self:custom.assetId}-authorizer
    source: java
```

Now when I do a serverless deploy there are two scenario's that happen:

1. When the stack is already present, and it performs an upgrade it is done successfully.
2 When Creating a new stack . that time we get error

```
2023-05-10 13:18:28 UTC+0530	NoApplicationContextAuthorizerLambdaPermissionApiGateway	
CREATE_FAILED
Function not found: arn:aws:lambda:us-east-1:111111:function:abc-authorizer (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: bc770db9-3e1f-409e-bee9-35c3e1f49315; Proxy: null)

2023-05-10 13:18:28 UTC+0530	AuthorizerFunctionLambdaPermissionApiGateway	
CREATE_FAILED
Function not found: arn:aws:lambda:us-east-1:111111:function:abc-authorizer  (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 661beea0-cb33-4b88-bdb6-5894243b6b65; Proxy: null)
```
3. When there is only one authotixzer **_authorizer_** it can create stack from scratch without any problem but when there are two authorizers then we have a problem.
