### DISCUSSION TITLE
Using a param derived from aws parameter store as value for map lookup does not work.

### DISCUSSION THREAD

**Discussion by smartin-qb** [serverless/serverless#11969] [Q&A]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Using a parameter derived from aws parameter store as value for map lookup does not work.

I have a parameter like so, which for the purpose of this issue resolves to a value of dev
```
params:
  default:
    accountName: "{{resolve:ssm:/env/Name}}"
```

I have a map like so for example
```
custom:
  dynamoCapacityForAccount:
    dev:
      read:
        min: 5
        max: 10
      write:
        min: 5
        max: 10
    qa:
      read:
        min: 10
        max: 20
      write:
        min: 10
        max: 20
```

I then lookup the values in the map like so using the param that is defined by using a aws parameter and it fails as as it does not get the value from the map for the `dev` accountName.
```
${self:custom.dynamoCapacityForAccount.${param:accountNamet}.read.min,1}

```

Also just in case it is related or helps if I supply via cli the accountName `--param='accountName=dev'` the lookup of the map does work without issue. So it seems to only not work if the parameter or self:custom is derived from a aws parameter. I believe it is a order of operations type issue, but dynamic params should work the same as cli params and it does not appear to be.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls deploy --stage xyz

### Command output

```shell
N/A
```

### Environment information

```shell
serverless --version
Running "serverless" from node_modules
Framework Core: 3.30.1 (local) 3.26.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
