### DISCUSSION TITLE
How to enable hosted UI on cognito

### DISCUSSION THREAD

**Discussion by fabiomssilva** [serverless/serverless#12013] [General]
Hi, 

I am trying to create a user pool and my code can be found bellow. 
Almost everything is ok and I am not able to enable the hosted UI. 

Getting a but lost on what I am missing. Tried: Documentation, Google, Google again :), stackoverflow, Debuging...etc... no luck . 

Can you help ? 

```
resources:
  Resources:
    MyUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: my-user-pool
        UsernameConfiguration: 
          CaseSensitive: false
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: true
        MfaConfiguration: OPTIONAL
        EnabledMfas:
          - SOFTWARE_TOKEN_MFA
        UsernameAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        Schema:
          - AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Name: email
            Required: true
        AutoVerifiedAttributes:
          - email
        EmailVerificationSubject: Verify your email address
        EmailVerificationMessage: Please click the link below to verify your email address. {####}

    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId:
          Ref: MyUserPool
        ClientName: my-user-pool-client
        GenerateSecret: true
        AllowedOAuthFlowsUserPoolClient: true
        ExplicitAuthFlows:
          - USER_PASSWORD_AUTH
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
          - openid
        CallbackURLs:
          - http://localhost:3000
        IdTokenValidity: 10 #hours
        AccessTokenValidity: 10 #hours
        ReadAttributes:
          - email
          - email_verified
        WriteAttributes: null #Looks like is only for idp...
        LogoutURLs:
          - http://localhost:3000/auth/logout
        SupportedIdentityProviders:
          - COGNITO

    MyUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId:
          Ref: MyUserPool
        Domain: ird-iont-auth
    #CustomDomainConfig: 
    #  CertificateArn: !Ref CertificateArn      
    #If this is not defined, a cognito domain will be created  

    MyUserPoolUI: #Not really used but was a test
      Type: AWS::Cognito::UserPoolUICustomizationAttachment
      Properties:
        ClientId:
          Ref: MyUserPoolClient
        UserPoolId:
          Ref: MyUserPool 





```

**Comment by renanwilliam** [comment]
Hi, your example have just some misconfigurations on user pool client.

```yaml
  UserPoolClientHostedUI:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: my-user-pool-client
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:3000
        - ${env:FRONTEND_URL}
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
```
