### DISCUSSION TITLE
How can I pass stage variables in API Gateway using Serverless framework?

### DISCUSSION THREAD

**Discussion by shaheer-k** [serverless/serverless#12060] [General]
We are using serverless framework to build AWS CloudFormation stacks.
https://www.serverless.com/framework/docs/providers/aws/events/apigateway

We have a use case where we want to pass stage variable. This is possible using CloudFormation template.

``` 
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:           
      StageName: test
      Variables:
        Key1: test1
        Key2: test2
``` 

But can we achieve the same using Serverless framework.
I know that it is possible using the plugin https://github.com/svdgraaf/serverless-plugin-stage-variables.
But is it supported in the native serverless framework without using the above plugin?
