### DISCUSSION TITLE
How to use !Ref or Fn:GetAtt in plugin development

### DISCUSSION THREAD

**Discussion by cmcnicholas** [serverless/serverless#12069] [Q&A]
Hi all, I'm trying to open a PR for lift that requires resolving a `!Ref` as one of its arguments (more here https://github.com/getlift/lift/discussions/345).

But simply put I am trying to achieve the following:

```yaml
resources:
  Resources:
    MyTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: SuperTopic

constructs:
  my-queue:
    type: queue
    worker:
      handler: worker.handler
    subscriptions:
      - topic: !Ref MyTopic # this doesn't work
```

How does a plugin developer go about resolving or specifying to the cloudformation config that the ref needs to be resolved against a dynamically created resource and not a specific arn?

For instance I can do the following but want to support resources that are created by the same serverless config and I'm having difficulty understanding how this should be provided the cloudfront config.

```ts
const topicArn = 'fully-qualified-arn'; // but I want to make this a ref
const topic = Topic.fromTopicArn(this, `${this.provider.stackName}-${id}-${index}`, topicArn);
topic.addSubscription(new SqsSubscription(this.queue, { filterPolicy, rawMessageDelivery: true }));
```

Any plugins that perform this sort of interaction would be really useful to browse through if possible?

**Comment by cmcnicholas** [comment]
OK further to the above I have managed to get the following to work:

```ts
const fn = Fn.getAtt("MyTopic", "TopicArn");
const topic = Topic.fromTopicArn(this, "SomeId", fn.toString());
topic.addSubscription(new SqsSubscription(this.queue, { filterPolicy, rawMessageDelivery: true }));
```

if there a friendly way to serialise/deserialise `Fn.getAtt("MyTopic", "TopicArn")` into yaml? Examples show use of:

```yaml
constructs:
  one-of-them-queues:
    type: queue
    worker:
      handler: worker.handler
    subscriptions:
      - topicRef:
          Fn::GetAtt:
            - MyTopic
            - TopicArn
```

for example, but what type am I expecting `topicRef` to be and/or how do I deserialise to an Fn so I can provide a serialised arn to `fromTopicArn` ?
