### DISCUSSION TITLE
Unrecognized property that I can't find in my yml 🤷

### DISCUSSION THREAD

**Discussion by OmriGilhar** [serverless/serverless#12081] [Q&A]
Hi all,

I'm using Serverless Framework for a while now and I always had a `warning` message that I was ignoring, now I feel its the time to fix it 🪛.

Serverless Framework Spec:
```
Framework Core: 3.27.0
Plugin: 6.2.3
SDK: 4.3.2
```

> Note: I know its no the latest version, but I have to use this version for now.

So my `serverless.yml` file is very simple:

```yml
service: ServiceName

package:
  patterns:
    - '!**'
    - 'src/**'

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-west-2
  runtime: python3.8
  stage: ${opt:stage, 'dev'}

functions:
  getIndex:
    handler: PathToHandler
```

Now the deployment goes well but, there is a warning that repeat itself every time I deploy:

```
Warning: Invalid configuration encountered
  at 'package': unrecognized property 'artifactsS3KeyDirname'
```

I tried to search for an open/close issue and on the community forum but couldn't find any information. The only reference I found regarding this property is in [those lines](https://github.com/serverless/serverless/blob/e4fb0730157e11ecb7f5403ee48d0b8cff46a9c1/lib/plugins/aws/package/index.js#L67).

Does someone have any idea how can I approach this issue?
Is it related to the SLS version I'm using?

Thanks!! 🙏🏼🙏🏼🙏🏼
