### DISCUSSION TITLE
Steaming Lambda Function "setContentType is not a function"

### DISCUSSION THREAD

**Discussion by andreaselia** [serverless/serverless#12090] [Q&A] [answered]
I'm attempting to stream data using my Lambda function deployed using `sls deploy` and the below configuration, but no matter what I do, there's always an issue with things not existing on the `responseStream` such as `setContentType`.

Any help or advice would be greatly appreciated. I've spent a couple of days researching but haven't really found anything that has helped here.

Example:
```javascript
exports.handler = awslambda.streamifyResponse(
    async (event, responseStream, context) => {
        responseStream.setContentType('text/plain');
        responseStream.write('Hello, world!');
        responseStream.end();
    }
);
```

My `serverless.yml` file:
```yml
app: sls
service: sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  timeout: 30

functions:
  api:
    handler: index.handler
    layers:
      - !Ref ApiLambdaLayer
    url:
      invokeMode: RESPONSE_STREAM
    events:
      - httpApi:
          path: /
          method: get

layers:
  api:
    package:
      artifact: ./resources.zip
```
