### DISCUSSION TITLE
Triggering events from an existing S3 bucket which are read in a Lambda function (different regions)

### DISCUSSION THREAD

**Discussion by flmu** [serverless/serverless#12100] [Q&A]
I have the following issue:

```
  newFunct:
    handler: ...
    events:
      - s3:
          bucket: myBucketName
          event: s3:ObjectCreated:*
          existing: true
```

My `newFunct` is deployed to AWS region `eu-central-1`. The bucket `myBucketName` is based in region `eu-west-1`

I got the following error message during my deployment process:
_**the notification destination service region is not valid for the bucket location constraint**_

If the bucket and the Lambda function are in the same region, the setup can be deployed without any problems.

Does anyone know how to solve this problem?
