### DISCUSSION TITLE
Can't get sls and AWS to handle a binary file, even with the simplest code

### DISCUSSION THREAD

**Discussion by mike-hogan** [serverless/serverless#12110] [Q&A]
Hi, this is a cross post from [stackoverflow](https://stackoverflow.com/questions/76874152/cant-get-serverless-com-and-aws-to-handle-a-binary-file-even-with-the-simplest)

I have made a super simple serverless.com repo [here](https://github.com/mike-hogan/sls-pdf-echo) that makes an endpoint in AWS that accepts a PDF and returns it, as a test case to learn how binary files are handled.

Here is the serverless.yml

```
service: sls-pdf-service

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  timeout: 10

functions:
  upload:
    handler: handler.upload
    events:
      - http:
          path: upload
          method: post
          cors: true

plugins:
  - serverless-apigw-binary
  - serverless-offline

custom:
  apigwBinary:
    types:
      - "application/pdf"

```

Here is the handler:

```
module.exports.upload = async (event) => {
  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'application/pdf',
    },
    body: event.body, // Simply return the PDF that was uploaded
    isBase64Encoded: true,
  };
};

```

And here is the package.json

```
{
  "name": "sls-pdf-echo",
  "version": "1.0.0",
  "description": "",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless-apigw-binary": "^0.4.4",
    "serverless-offline": "^12.0.4"
  }
}

```

I run it offline like this:

```
sls offline
```

And I invoke the endpoint like this:

```
curl -X POST -H "Content-Type: application/pdf" --data-binary "@4614fb56-335d-4985-bac6-7996af859297.pdf" http://localhost:3000/dev/upload -o out.pdf
```

The posted PDF is 1.3MB in size, and I get 489 bytes back, and its gibberish.

How do I make this work?

I want to make clear that I want to be able to post a binary PDF to this endpoint, not a base64 encoded one.
