### DISCUSSION TITLE
Parse json objects out of ssm and pull out specific keys

### DISCUSSION THREAD

**Discussion by celioreyes** [serverless/serverless#12143] [Ideas]
Hey serverless team,

I worked on this PR to add a feature to allow for someone to store a JSON object in SSM and be able to plug out the keys you need in `serverless.yml`:

```json
{
  "key1": "val1",
  "key2": "val2"
}
````

```yaml
environment:
  ENVVAL1: ${jsonParse(${ssm:path_to_secret}):key1}
  ENVVAL2: ${jsonParse(${ssm:path_to_secret}):key2}
```

The PR has been stale for a while now since the person who was helping me push it along on the serverless team move on to something else. I was wondering if I could get some help pushing it across the finish line? Thanks!

Issue: https://github.com/serverless/serverless/issues/11289#issuecomment-1702808001
PR: https://github.com/serverless/serverless/pull/12023#issuecomment-1688422223

Sorry for using discussions for this just want to know if this will be merged or if I should look to solve this another way.
