### DISCUSSION TITLE
Customized function name for s3 event with existing: true

### DISCUSSION THREAD

**Discussion by sean-pg** [serverless/serverless#12140] [Q&A]
When I try to deploy one function, I notice the customized function name will not be applied and it will have the prefix ` ${serverless.service.service}-${awsProvider.getStage()}` always.

The following is the partial script in my side

```yaml
functions:
  handler:
    name: "${self:provider.stage}-${self:app}-${self:service}-handler"
    handler: handler.handler
    events:
      - s3:
          bucket: "mybucket"
          event: s3:ObjectCreated:*
          forceDeploy: true
          existing: true
```

After checking the source code, I found it has the different logic about getting function between `existing:false` and `existing:true`

for `existing:true`, it is https://github.com/serverless/serverless/blob/main/lib/plugins/aws/custom-resources/index.js#L30-L43

```js
const funcPrefix = `${serverless.service.service}-${awsProvider.getStage()}`;

  // check which custom resource should be used
  if (resourceName === 's3') {
    functionName = awsProvider.naming.getCustomResourceS3HandlerFunctionName();
    Handler = 's3/handler.handler';
    customResourceFunctionLogicalId =
      awsProvider.naming.getCustomResourceS3HandlerFunctionLogicalId();
  }
```

but for `existing:false`, it is https://github.com/serverless/serverless/blob/main/lib/plugins/aws/package/compile/events/s3/index.js#L234-L240

```js
     const functionObj = this.serverless.service.getFunction(s3EnabledFunction.functionName);

      const permissionTemplate = {
        Type: 'AWS::Lambda::Permission',
        DependsOn: _.get(functionObj.targetAlias, 'logicalId'),
        Properties: {
          FunctionName: resolveLambdaTarget(s3EnabledFunction.functionName, functionObj),
```

That's the reason it cannot apply to the customized function name. Does there have any specific reason for that?
