### DISCUSSION TITLE
Serverless does not include files when functions' handler is specified ?

### DISCUSSION THREAD

**Discussion by tachyon83** [serverless/serverless#12190] [Q&A]
```
functions:
  someFunctionName:
    handler: path/to/dir/function.Handler
    name: some-name
    package:
      patterns:
          - "dir1/dir2/**"
```

I wrote my serverless.yml file like above.
What's specified in package.patterns are never included in the deployed function (someFunctionName).
Is it because handler is defined?
The handler does not have direct dependencies on the files I am trying to include (dir1/dir2/**).
