### DISCUSSION TITLE
Python3.8 to Python3.11 complex project

### DISCUSSION THREAD

**Discussion by Paul-J-Barrett** [serverless/serverless#12213] [General]
Friday I started migrating our AWS Python3.8 serverless project to 3.11. The project is pretty large. About 6 months ago I split the serverless into multiple files with serverless.yaml in root a serverless folder with a file for common, lambdas, layers, step functions, and event schedules.

The project originally was setup with patterns and I thought that the new serverless used include and exclude but that was the old way so I switched it back. The issue is that either I get the error No Files to include or if I the !./** pattern I end up with all lambdas in every zip file and they are all 18M or so. I checked the old serverless with the correct patterns and the files vary in size as is appropriate from 1k to 40k.

So my first question is can you suggest resources for how I can debug the serverless frame work with my project. I think part of the issue is the fact that our project is so complex. Next question would be where would be the best spot to set a break point for the inclusion exclusion of the lambda(functions) inclusion. Also with the limited information that I can give do you think it is worth filing a bug report, I think the serverless.yaml  being broken apart might be part of the issue which might make it hard for the normal serverless dev team to debug this.

One additional note when it does give me the error when I look at the packages they have the appropriate size so maybe right after that is where I would like to set a breakpoint. 

I do have some light node experience and node inspector however I have not done any serverless debugging before.

I will go read documentation on contributions and other things to see if I can figure out what I need to do on my own. But if you could give some suggestions it would be appreciated. 

I will make a pull request once I find the issue and correct it.

**Comment by Paul-J-Barrett** [comment]
Ok here is what I have gleamed in the few minutes between meetings
1. Install Node v14.x
2. Fork Serverless
3. Clone Fork
4. Create a new Branch
5. Figure out how to launch serverless from my cloned fork with  something along the lines of
    serverless dev deploy --stage dev --debug  * --verbose --force 
6. Watch the events find event that happens right after creating the packages.
7. Set breakpoint on appropriate event from 6
8. Start stepping through code to see why it thinks that there are no files meeting pattern after it already created the packages.

**Comment by Paul-J-Barrett** [comment]
Ok new problem. So I did 1-3 in  previous post and am able to run 'npm run test' without issue. However I am not seeing how to  run it also I noticed in the code something about the cli being removed. Which brings to mind new questions about how to test and step through it to find the issue. node bin\serverless.js --version didn't run.

I also ran 'npm install; npm run pkg:build'.

**Comment by Paul-J-Barrett** [comment]
Here is the version information, debug output, and the relevant parts of the yaml files.
PS C:\Users\myusername\source\upgrade311\dataservices\ingestion_pipeline> serverless --version
Running "serverless" from node_modules
Framework Core: 3.25.1 (local) 3.25.1 (global)
Plugin: 6.4.0
SDK: 4.4.0

PS C:\Users\myusername\source\upgrade311\dataservices\ingestion_pipeline> npm install serverless@latest

added 87 packages, changed 6 packages, and audited 547 packages in 15s

74 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
PS C:\Users\myusername\source\upgrade311\dataservices\ingestion_pipeline> serverless --version
Running "serverless" from node_modules
Framework Core: 3.35.2 (local) 3.25.1 (global)
Plugin: 7.0.5
SDK: 4.4.0

lifecycle:command:invoke: Invoke deploy
lifecycle:command:invoke:hook: [1] < before:deploy:deploy
lifecycle:command:invoke: Invoke package
lifecycle:command:invoke:hook: [2]   < before:package:cleanup
Packaging
lifecycle:command:invoke:hook: [2]   > before:package:cleanup
lifecycle:command:invoke:hook: [3]   < package:cleanup
lifecycle:command:invoke: Invoke aws:common:validate
lifecycle:command:invoke:hook: [5]     < aws:common:validate:validate
lifecycle:command:invoke:hook: [5]     > aws:common:validate:validate
lifecycle:command:invoke: Invoke aws:common:cleanupTempDir
lifecycle:command:invoke:hook: [8]     < aws:common:cleanupTempDir:cleanup
lifecycle:command:invoke:hook: [8]     > aws:common:cleanupTempDir:cleanup
lifecycle:command:invoke:hook: [3]   > package:cleanup
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [15]   < package:setupProviderConfiguration
lifecycle:command:invoke:hook: [15]   > package:setupProviderConfiguration
lifecycle:command:invoke:hook: [18]   < package:createDeploymentArtifacts
lifecycle:command:invoke:hook: [18]   > package:createDeploymentArtifacts
lifecycle:command:invoke:hook: [1] > before:deploy:deploy

× Stack dataservices-ingestion-Dev failed to deploy (0s)
process: handle error
process: finalize { error:
   { ServerlessError: No file matches include / exclude patterns
       at C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:317:13
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
       at async Package.packageFunction (C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:193:23)
       at async C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:100:9
       at async Promise.all (index 32)
       at async Package.packageService (C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:129:5)
       at async PluginManager.runHooks (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:530:9)
       at async PluginManager.invoke (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:564:9)
       at async PluginManager.spawn (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:585:5)
       at async before:deploy:deploy (C:\Users\myusername\node_modules\serverless\lib\plugins\deploy.js:48:11)
       at async PluginManager.runHooks (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:530:9)
       at async PluginManager.invoke (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:563:9)
       at async PluginManager.run (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:604:7)
       at async Serverless.run (C:\Users\myusername\node_modules\serverless\lib\serverless.js:179:5)
       at async C:\Users\myusername\node_modules\serverless\scripts\serverless.js:819:9
     [stack]:
      'ServerlessError: No file matches include / exclude patterns\n    at C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:317:13\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Package.packageFunction (C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:193:23)\n    at async C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:100:9\n    at async Promise.all (index 32)\n    at async Package.packageService (C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:129:5)\n    at async PluginManager.runHooks (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:530:9)\n    at async PluginManager.invoke (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:564:9)\n    at async PluginManager.spawn (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:585:5)\n    at async before:deploy:deploy (C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\deploy.js:48:11)\n    at async PluginManager.runHooks (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:530:9)\n    at async PluginManager.invoke (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:563:9)\n    at async PluginManager.run (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:604:7)\n    at async Serverless.run (C:\\Users\\myusername\\node_modules\\serverless\\lib\\serverless.js:179:5)\n    at async C:\\Users\\myusername\\node_modules\\serverless\\scripts\\serverless.js:819:9',
     [message]: 'No file matches include / exclude patterns',
     code: 'NO_MATCHED_FILES',
     decoratedMessage: undefined,
     [name]: 'ServerlessError' },
  shouldBeSync: undefined,
  telemetryData: undefined,
  shouldSendTelemetry: undefined }
Environment: win32, node 16.14.2, framework 3.35.2 (local) 3.25.1v (global), plugin 7.0.5, SDK 4.4.0
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No file matches include / exclude patterns



Some samples from config that is working for 3.8 only changes have been to upgrade to latest serverless and change out runtime to python3.11

```

#serverless.yaml
frameworkVersion: "3"

service: dataservices-ingestion

resources:
  Resources:
    dataservicesrole:
      ${file(./serverless/serverless.roles.yaml):dataservicesrole}
provider:
  ${file(./serverless/serverless.common.yaml):provider}
plugins:
  ${file(./serverless/serverless.common.yaml):plugins}

custom:
  ${file(./serverless/serverless.common.yaml):custom}

package:
  ${file(./serverless/serverless.common.yaml):package}

layers:
  ${file(./serverless/serverless.layers.yaml):layers}

functions:
  - ${file(./serverless/serverless.lambda.yaml):functions}
  - ${file(./serverless/functions/stepfunctionstarter.yaml):functions}

stepFunctions:
  ${file(./serverless/serverless.stepfunctions.yaml):stepFunctions  


#serverless.common.yaml
provider:
  name: aws
  role: dataservicesrole
  runtime: python3.11
  memorySize: 128
  timeout: 900
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'Dev'}
  tags:
    app: dataservices
    env: ${self:provider.stage}
  environment:
    APP_NAMESPACE: "/dataservices/${self:provider.stage}"
    APP_ENV: ${self:provider.stage}
  
plugins:
  - serverless-step-functions
custom:
  enabled:
    Dev: false
    Prod: true
  lowerStage:
    Dev: dev
    Prod: prod

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - "!./**"
    - "!__pycache__/**"
    - "!.pytest_cache/**"
    - "!all_test.sh"
    - "!Makefile"
    - "!test/**"
    - "!tests/**"
    - "!test*.py"
    - "!*.dist-info"
  
  
#Piece of serverless.layers.yaml
layers:
  GeneralFunctions:
    path: lambda_layers/utils
    package:
      patterns:
        - "./**"
    name: GeneralFunctions-${self:provider.stage}
	
	
#Piece of serverless.lambda.yaml
functions:
  GetJobConfig:
    handler: orchestration_lambdas/get_job_config/get_job_config.handler
    layers:
      - { Ref: GeneralFunctionsLambdaLayer }
      - { Ref: PydanticLambdaLayer }
    package:
      patterns:
        - "orchestration_lambdas/get_job_config/**"
    environment:
      S3_CONFIG_BUCKET: somebucket-${self:provider.stage}
```
