### DISCUSSION TITLE
sls invoke retries multiple times

### DISCUSSION THREAD

**Discussion by isaacfink** [serverless/serverless#12225] [Q&A]
I have a lambda function that times out, I am ok with it timing out but when I invoke it with `sls invoke` it seems to retry multiple times, the timeout is set to `900` and there are no other paramaters for retrying, this is the configuration in `serverless.yaml` 
```
function:
    handler: path/to/file/index.handler # your file and method names here
    timeout: 900
    events:
      - schedule: rate(24 hours)
```
I don't know why it is retrying, there is no code that retires on timeout and there is nothing else calling this function
