### DISCUSSION TITLE
DynamoDB stream filterPatterns

### DISCUSSION THREAD

**Discussion by 0xazuki7** [serverless/serverless#12248] [Q&A]
### Are you certain it's a bug?
* [x]  Yes, it looks like a bug

### Is the issue caused by a plugin?
* [x]  It is not a plugin issue

### Are you using the latest v3 release?
* [x]  Yes, I'm using the latest v3 release

### Is there an existing issue for this?
* [x]  I have searched existing issues, it hasn't been reported yet

### Issue description
schema validator reports that lambda events DynamoDB stream filterPatterns must be an array which I think is not correct as when filterPatterns is an array the filter must match one of patterns but when it is an object it must match each pattern

example with an array:

```yaml
functions:
  myLambda:
    handler: src/handlers/myLambda.default
    events:
      - stream:
          arn: arn:aws:dynamodb:region:XXXXXX:table/Test/stream/1970-01-01T00:00:00.000
          batchSize: 5
          filterPatterns:
           - eventName: INSERT
           - dynamodb:
                NewImage:
                  Type:
                    S: [Invoice]
```

in this case if eventName == "INSERT" **OR** record's (item).Type == "Invoice" the record is accepted

example with a key-value object:

```yaml
functions:
  myLambda:
    handler: src/handlers/myLambda.default
    events:
      - stream:
          arn: arn:aws:dynamodb:region:XXXXXX:table/Test/stream/1970-01-01T00:00:00.000
          batchSize: 5
          filterPatterns:
           eventName: INSERT
           dynamodb:
                NewImage:
                  Type:
                    S: [Invoice]
```

in this case if eventName == "INSERT" **AND** record's (item).Type == "Invoice" then the record is accepted

maybe I'm wrong and there's already another method to declare "AND" type filters ?

### Service configuration (serverless.yml) content
```yaml
service: sls-project

frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  region: eu-west-3
  deploymentMethod: direct
functions:
  myLambda:
    handler: src/handlers/myLambda.default
    events:
      - stream:
          arn: arn:aws:dynamodb:region:XXXXXX:table/Test/stream/1970-01-01T00:00:00.000
          batchSize: 5
          filterPatterns:
            eventName: INSERT
            dynamodb:
                NewImage:
                  Type:
                    S: [Invoice]
```

### Command name and used flags
any sls command

### Command output
```shell
Warning: Invalid configuration encountered
  at 'functions.myLambda.events.0.stream.filterPatterns': must be array

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information
```shell
Running "serverless" from node_modules
Framework Core: 3.26.0 (local) 3.26.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by smolmusk** [comment]
I think `filterPaterns` structure is wrong.
```
filterPatterns:
            eventName: INSERT
            dynamodb:
                NewImage:
                  Type:
                    S: [Invoice]

```
Instead of this, please try to use something like this:
```
- {
      eventName: ...
      dynamodb: ...
  }
```
