### DISCUSSION TITLE
The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::ApiGatewayV2::Stage, AWS::ApiGatewayV2::Route, AWS::ApiGatewayV2::Integration, AWS::ApiGatewayV2::Api]

### DISCUSSION THREAD

**Discussion by Aravin** [serverless/serverless#12316] [Q&A]
I am unable to deploy the serverless function into AWS.

The same function is working in local.

I am getting this error: 
The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::ApiGatewayV2::Stage, AWS::ApiGatewayV2::Route, AWS::ApiGatewayV2::Integration, AWS::ApiGatewayV2::Api]

Logs

```
Running "serverless" from node_modules

Deploying gold-loan-app to stage dev (ap-south-2)

Packaging
Compiling with Typescript...
Using local tsconfig.json - tsconfig.json
Typescript compiled.

Warning: Package patterns at function level are only applicable if package.individually is set to true at service level or function level in serverless.yaml. The framework will ignore the patterns defined at the function level and apply only the service-wide ones.
Excluding development dependencies for service package
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service gold-loan-app.zip file to S3 (18.88 MB)

✖ Stack gold-loan-app-stack failed to deploy (33s)
Environment: darwin, node 20.10.0, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::ApiGatewayV2::Stage, AWS::ApiGatewayV2::Route, AWS::ApiGatewayV2::Integration, AWS::ApiGatewayV2::Api]
```

### .yml file

```
service: gold-loan-app
frameworkVersion: "3"

package:
  patterns:
    - "src/**"

custom:
  prefix: gold-loan-app
  tableName: "users-table-${sls:stage}"

params:
  prod:
    domain: myapp.com
  dev:
    domain: preview.myapp.com

# configValidationMode: error
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  stackName: gold-loan-app-stack
  region: ap-south-2

  iam:
    role: arn:aws:iam::715637905274:role/serverless-api-role

# Lambda functions
functions:
  api:
    handler: src/routes/handler.hello
    events:
      - httpApi:
          path: /
          method: get

# SQL - dynamoDB
resources:
  Resources:
    customerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-customers
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: N
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    loanTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-loans
        AttributeDefinitions:
          - AttributeName: loanId
            AttributeType: N
        KeySchema:
          - AttributeName: loanId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    schemeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-scheme
        AttributeDefinitions:
          - AttributeName: loanId
            AttributeType: N
        KeySchema:
          - AttributeName: loanId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
# s3:
#   bucket: ${self.custom.prefix}-bucket

plugins:
  - serverless-plugin-typescript
  - serverless-offline
```
