### DISCUSSION TITLE
YAML layers property doesn't import python package from path causing Runtime.ImportModuleError

### DISCUSSION THREAD

**Discussion by mkj33** [serverless/serverless#12327] [Q&A]
Hello, my goal is to create three layers. I try to implement them basing on this articles:
- https://www.serverless.com/framework/docs/providers/aws/guide/layers
- https://docs.aws.amazon.com/lambda/latest/dg/packaging-layers.html

I have 3 separate requirements.txt files located in layers-requirements/layerA, layers-requirements/layerB, layers-requirements/layerC.

I have created `layers` property in my serverless.yml file, which is set up like that:
```
layers:
  basic:
    path: layers/layerA
    compatibleRuntimes:
      - python3.9
      - python3.10
      - python3.11
    allowedAccounts:
      - '*'

  google:
    path: layers/layerB
    compatibleRuntimes:
      - python3.9
      - python3.10
      - python3.11
    allowedAccounts:
      - '*'

  boto3:
    path: layers/layerC
    compatibleRuntimes:
      - python3.9
      - python3.10
      - python3.11
    allowedAccounts:
      - '*'
 ```
     
Next, I have created a script that installs the requirements.txt file in the layers/layerA, layers/layerB, layers/layerC in the python folder to then create a zip of this python file to get python.zip as instructed on AWS so that the end result is layers/basic/python.zip etc.

Then, following the instructions in the serverless documentation, I created a reference in the `functions` property in the serverless.yml file. For example, it looked like this:
```  
function_for_something:
    handler: src.common.function_for_something.handler.lambda_handler
    layers:
    - !Ref BasicLambdaLayer
    - !Ref Boto3LambdaLayer
    - !Ref GoogleLambdaLayer
  ```
  
After the deployment is done after using sls deploy command, when I test each function in AWS Lambda inline code editor, I get an error:
```
{
    "errorMessage": "Unable to import module 'src.common.function_for_something.handler.handler': No module named 'alembic'",
    "errorType": "Runtime.ImportModuleError",
    "requestId": "262e019a-f242-4a44-95de-dd67af4a9dcf",
    "stackTrace": []
}
```

The thing is that the layer is uploaded to AWS as a zip, which when unzipped has the structure as AWS requires, i.e. python/<folders with installed packages>. 
What am I doing wrong? What is missing from my configuration?
