### DISCUSSION TITLE
Adding Condition to Lambda by overriding AWS CloudFormation resource

### DISCUSSION THREAD

**Discussion by amanangira** [serverless/serverless#12329] [Q&A]
Hello, I want to conditionally enable/disable deployment of a lambda function based on an AWS `Condition`. For this I am trying to leverage AWS CloudFormation override logic [explained here](https://www.serverless.com/framework/docs/providers/aws/guide/resources#override-aws-cloudformation-resource). Although, I am facing the following error 

```
The CloudFormation template is invalid: Template format error: Every Resources object must contain a Type member.
```

I am certain that I am making a syntax error and this is possible to achieve. Since Condition is already documented as a valid resource attribute in the documentation. 

Here is the relevant excerpt from my serverless.yml 
```yaml

resources:
  - ${file(resources/cognito-user-permission.yml)}
  - ${file(resources/conditions.yml)}
  - extensions:
      SyncDashSchedulerLambdaFunction:
        Condition: CreateProdResources


functions:
  sync-scheduler:
    package:
      include:
        - ./bin/syncscheduler
    handler: bin/syncscheduler
    timeout: 300
    events:
      - schedule: cron(30 04 ? * * *) # 04:30 UTC, Everyday
```

conditions.yml
```yaml
Conditions:
  CreateProdResources:
    Fn::Equals:
      - ${self:custom.stage}
      - "prod"
  CreateDevResources:
    Fn::Not:
      - Fn::Equals:
          - ${self:custom.stage}
          - "prod"
```

```
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              20.6.1
     Framework Version:         2.55.0
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.15.1
```

Note -- I have redacted part of the name from function name due to project's privacy.

**Comment by amanangira** [comment]
Upon tweaking the serverless.yaml configuration to 

```yaml
resources:
  - ${file(resources/cognito-user-permission.yml)}
  - ${file(resources/conditions.yml)}
  - extensions:
      SyncDashschedulerLambdaFunction:
        Condition: CreateProdResources

```
I got this error 

` Template format error: Unresolved resource dependencies [SyncDashschedulerLambdaFunction] in the Resources block of the template`

whereas the following works fine 
```yaml
resources:
  - ${file(resources/cognito-user-permission.yml)}
  - ${file(resources/conditions.yml)}
  - extensions:
      SyncDashschedulerLogGroup:
        Properties:
          RetentionInDays: '30'
```
