### DISCUSSION TITLE
How can I create in the CloudFrontDistribution a CacheBehavior without any LambdaEdge function attached

### DISCUSSION THREAD

**Discussion by antoniogomezm** [serverless/serverless#12337] [Q&A]
I'm have a lambda-edge deployment with a function associated to a viewer-request event on a specific pathPattern.

I need to define a new CacheBehavior with higher priority but with no LambdaEdge function linked.

How can I do it?

I've tried to add on the resources.Resource.CloudFrontDistribution section, but it goes always in lower order that the one who have the function.

```
functions:
  foo:
     - cloudfront:
        eventType:  viewer-request
        pathPattern:  some/*
        ....

resource:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
        [...]
        CacheBehaviors:
        - pathPattern: some/other/*
           ....
```
