### DISCUSSION TITLE
Both lambda to have required permissions and scheduler schedule permissions to invoke the lambda

### DISCUSSION THREAD

**Discussion by Tsingis** [serverless/serverless#12419] [Q&A]
Looking at https://www.serverless.com/framework/docs-providers-aws-events-schedule. Isn't the role below for the Lambda, not the Schedule?

How does one make the Lambda have permissions X, Y and Z and the Schedule have permission to invoke the deployed Lambda?

```
functions:
  foo:
    handler: foo.handler
    role: <my awesome role>
    events:
      - schedule:
          method: scheduler
          rate:
            - cron(0 0/4 ? * MON-FRI *)
          timezone: America/New_York
          input:
            key1: value1
            key2: value2
```
