### DISCUSSION TITLE
knative deployment function witj sls

### DISCUSSION THREAD

**Discussion by feniln64** [serverless/serverless#12439] [Q&A]
I am trying to deploy knative function to microk8s cluser and while `sls deploy` it creates new namespace for deployment but then it give HTTP error.
my sls yaml file
```
service: my-project

frameworkVersion: '3'

provider:
  name: knative
  docker:
    username: username
    password: dckr_p1t_12345678901234567

functions:
  hello:
    handler: username/image:latest


plugins:
  - serverless-knative
  ```
getting error 
```
Deploying Kubernetes namespace "sls-my-project-dev"...
Deploying Knative service for function "my-project-hello"...
Environment: win32, node 20.12.2, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.3, SDK 4.5.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
HttpError: HTTP request failed
    at Request._callback (C:\Users\fenil\Documents\extra\microk8s\knative\folder\node_modules\@kubernetes\client-node\dist\gen\api\customObjectsApi.js:1626:40)
    at self.callback (C:\Users\fenil\Documents\extra\microk8s\knative\folder\node_modules\request\request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.emit (node:domain:488:12)
    at Request.<anonymous> (C:\Users\fenil\Documents\extra\microk8s\knative\folder\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:518:28)
    at Request.emit (node:domain:488:12)
    at IncomingMessage.<anonymous> (C:\Users\fenil\Documents\extra\microk8s\knative\folder\node_modules\request\request.js:1076:12)       
    at Object.onceWrapper (node:events:632:28)
    at IncomingMessage.emit (node:events:530:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
is there any way to deploy knative function with sls???? as i need to use sls!!!
