### DISCUSSION TITLE
sls4's bug during 5/2~5/7's changed

### DISCUSSION THREAD

**Discussion by gavinsui1106** [serverless/serverless#12479] [Q&A] [answered]
when i used the command ` serverless deploy --stage ${env}` in sls3 . it always worked!
when i use the command in sls4 first time (2024/5/2) it also worked! but when i use the command after a few days (2024/5/7), it failed!
i dont konw what happend in thoes days, anyone can tell me why ? and how to change my sourcecode? here is the whole error message and my sourcecode.

**error message**
`Failed to resolve variable 'custom.${opt:stage' with resolver 'config' :ERROR :Key "custom.${opt:stage" is not defined in config file.`

**buildspec.yml**
```
serverless deploy --stage ${env}
#${env} is set with environment during AWS's Coodebuild . for example ,Dev is the value of env.
```

**serverless.yml**
```
provider:
  name: test
  runtime: dotnet6
  region: XXX
  environment: ${file(slsconf/serverless_environment.yml)}
  role: arn:aws:iam::${self:custom.${opt:stage, self:provider.stage}.EnvironmentVariable1Val}:/role/${self:custom.${opt:stage, self:provider.stage}.EnvironmentVariable2Val}

custom:
   ${file(slsconf/serverless_custom${opt: stage, self: provider.stage}.yml)}
```
**slsconf/serverless_environment.yml**
```
TZ: XXX
EnvironmentVariable1: ${self: custom.${opt: stage, self: provider.stage}.EnvironmentVariable1Val}
EnvironmentVariable2: ${self: custom.${opt: stage, self: provider.stage}.EnvironmentVariable2Val}
```
**slsconf/serverless_customDev.yml**
```
EnvironmentVariable1Val: XXX
EnvironmentVariable2Val: XXX
```

**Comment by gavinsui1106** [comment]
@serverless-ci @ServerlessBot
pls

**Reply by gavinsui1106** [reply]
@ServerlessBot @serverless-ci

when i used 4.0.30(release date is 2024/5/27)
another error is happened .
maybe this is a bug.
error message:

```
s:core:meta: saving meta record to global .serverless directory. s:cli-error-handler: currentValue.replace is not a function TypeError: currentValue.replace is not a function at #replacePlaceholderInConfig (file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:24501) at #handlePlaceholderNode (file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:20573) at async file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:18650 at async processNodeAndHandleCompletion (file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:13936)
✖ currentValue.replace is not a function TypeError: currentValue.replace is not a function at #replacePlaceholderInConfig (file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:24501) at #handlePlaceholderNode (file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:20573) at async file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:18650 at async processNodeAndHandleCompletion (file:///root/.serverless/releases/4.0.30/package/dist/sf-core.js:1041:13936)
```

**Reply by czubocha** [reply]
Hi @gavinsui1106, unfortunately, I am unable to reproduce the error with the config you provided in the [original comment](https://github.com/serverless/serverless/discussions/12479#discussion-6663888). To assist you better, could you please provide an example configuration that reproduces the error? This will help us identify the issue more accurately and provide a solution.

**Reply by gavinsui1106** [reply]
@czubocha @serverless-ci @ServerlessBot 
here is the source code,when i was deploy,the paramter[environmentDivision] was set with Dev,both serverless 4.0.32 and 4.0.33 was the same error as i said.

buildspec.yml
```
version: 0.2
env:
  secrets-manager:
    SERVERLESS_ACCESS_KEY: XXX
phases:
  install:
    commands:
      - /usr/local/bin/dotnet-install.sh --channel 6.0.2xx
  build:
    commands:
      - dotnet --version
      - dotnet tool install -g Amazon.Lambda.Tools --version 5.3.0
      - export DOTNET_ROOT=/root/.dotnet
      # build
      - cd XXX
      - chmod 777 build.sh
      - ./build.sh
      - find /etc/apt/sources.list.d/yarn* | xargs sed -i "s/deb /deb [trusted=yes] /g"
      - apt update
      - apt -y install npm
      - npm --version
      - npm config set strict-ssl false
      - n 18.20.3
      - node --version
      - hash -r
      - node --version
      # serverless
      ## install
      - npm i @serverless/v4 -g
      - npm install --save-dev serverless-plugin-tracing@2.0.0
      - npm install --save-dev serverless-prune-plugin@2.0.2
      - npm install --save-dev serverless-plugin-split-stacks@1.12.0
      ## deploy
      - serverless deploy --stage ${env} --param="environmentDivision=${envDivision}" --debug
artifacts:
  files: XXX/XXX.zip
```

serverless.yml
```
service: XXX
provider:
  name: aws
  runtime: dotnet6
  region: ap-northeast-1
  stackName: XXX-${opt:stage, self:provider.stage}
  apiName: XXX-${opt:stage, self:provider.stage}
  memorySize: 512
  timeout: 28
  logRetentionInDays: 400
  role: arn:aws:iam::${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT1}:role/${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT2}
  versionFunctions: false
  tracing: 
    apiGateway: true
    lambda: true 
  environment:
    ${file(slsconf/serverless_environment${param:environmentDivision}.yml)}
    
  tags:
    Cost: XXX
  logs:
    restApi: true
  endpointType: private
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
      - Effect: Deny
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          StringNotEquals:
            aws:sourceVpce: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT3}
package:
  artifact: bin/release/netapp6/lambda-function.zip
  exclude:
    - README.md
    - .git/**
    - .gitignore
    - .vscode/**
    - aws-csharp.csproj
    - build.cmd
    - build.sh
    - set_accessKeys.bat
    - unset_proxy.bat

custom:
  ${file(slsconf/serverless_custom${opt:stage, self:provider.stage}.yml)}

plugins:
  - serverless-plugin-tracing
  - serverless-prune-plugin
  - serverless-plugin-split-stacks

functions:
  - ${file(slsconf/serverless_functions${opt:stage, self:provider.stage}.yml)}
```

serverless_environmentRest.yml
```
ENVIRONMENT1: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT1}
ENVIRONMENT2: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT2}
ENVIRONMENT3: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT3}
ENVIRONMENT4: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT4}
ENVIRONMENT5: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT5}
```

serverless_customDev.yml
```
Dev:
  ENVIRONMENT1: Value1
  ENVIRONMENT2: Value2
  ENVIRONMENT3: Value3
  ENVIRONMENT4: Value4
  ENVIRONMENT5: Value5
```

**Reply by gavinsui1106** [reply]
@czubocha @ServerlessBot @serverless-ci 
sorry to bother you again,our release timing is coming soon,when will the bug can be fixed?

**Reply by czubocha** [reply]
Hi @gavinsui1106, we looked into it last week but couldn't reproduce the error using the example you provided. Could you please confirm if you can reproduce the error with the same example? It looks like this might be an isolated case specific to your use case.

**Reply by gavinsui1106** [reply]
@czubocha @serverless-ci @ServerlessBot 
each of the recent release version i had tried! all of them were the same error.when the sls4 was used the first time(2024/5/2) ,i can successfully builded with the same source as now.

**Reply by gavinsui1106** [reply]
maybe i can provided you the latest serverless version's codebuild detailed.

**Reply by gavinsui1106** [reply]
@czubocha @ServerlessBot @serverless-ci 
here it is 
```s:cli-error-handler: currentValue.replace is not a function
TypeError: currentValue.replace is not a function
    at _ResolverManager.#replacePlaceholderInConfig (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/manager.js:676:33)
    at _ResolverManager.#handlePlaceholderNode (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/manager.js:455:10)
    at <anonymous> (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/manager.js:350:11)
    at processNodeAndHandleCompletion (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/graph.js:20:5)

? currentValue.replace is not a function
TypeError: currentValue.replace is not a function
    at _ResolverManager.#replacePlaceholderInConfig (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/manager.js:676:33)
    at _ResolverManager.#handlePlaceholderNode (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/manager.js:455:10)
    at <anonymous> (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/manager.js:350:11)
    at processNodeAndHandleCompletion (/root/.serverless/releases/4.1.4/sf-core/src/lib/resolvers/graph.js:20:5)

For help, try the following:
  ? Run the command again with the "--debug" option
  ? Run "serverless support"
  ? Review the docs: https://www.serverless.com/framework/docs/


[Container] 2024/06/17 09:02:24.467131 Command did not exit successfully serverless deploy --stage ${env} --param="environmentDivision=${envDivision}" --debug exit status 1
[Container] 2024/06/17 09:02:24.472596 Phase complete: BUILD State: FAILED
[Container] 2024/06/17 09:02:24.472643 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: serverless deploy --stage ${env} --param="environmentDivision=${envDivision}" --debug. Reason: exit status 1```

**Reply by gavinsui1106** [reply]
@serverless-ci @ServerlessBot 
#12573
maybe this is the same error as mine

**Reply by czubocha** [reply]
serverless.yml
```
service: XXX
provider:
  name: aws
  runtime: dotnet6
  region: ap-northeast-1
  stackName: XXX-${opt:stage, self:provider.stage}
  apiName: XXX-${opt:stage, self:provider.stage}
  memorySize: 512
  timeout: 28
  logRetentionInDays: 400
  role: arn:aws:iam::${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT1}:role/${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT2}
  versionFunctions: false
  tracing:
    apiGateway: true
    lambda: true
  environment:
    ${file(slsconf/serverless_environment${param:environmentDivision}.yml)}

  tags:
    Cost: XXX
  logs:
    restApi: true
  endpointType: private
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
      - Effect: Deny
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          StringNotEquals:
            aws:sourceVpce: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT3}
package:
  artifact: bin/release/netapp6/lambda-function.zip
  exclude:
    - README.md
    - .git/**
    - .gitignore
    - .vscode/**
    - aws-csharp.csproj
    - build.cmd
    - build.sh
    - set_accessKeys.bat
    - unset_proxy.bat

custom:
  ${file(slsconf/serverless_custom${opt:stage, self:provider.stage}.yml)}

#plugins:
#  - serverless-plugin-tracing
#  - serverless-prune-plugin
#  - serverless-plugin-split-stacks

functions:
   - ${file(slsconf/serverless_custom${opt:stage, self:provider.stage}.yml)}
```
slsconf/serverless_customDev.yml
```
Dev:
  ENVIRONMENT1: Value1
  ENVIRONMENT2: Value2
  ENVIRONMENT3: Value3
  ENVIRONMENT4: Value4
  ENVIRONMENT5: Value5
```
slsconf/serverless_environmentDev.yml
```
ENVIRONMENT1: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT1}
ENVIRONMENT2: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT2}
ENVIRONMENT3: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT3}
ENVIRONMENT4: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT4}
ENVIRONMENT5: ${self:custom.${opt:stage, self:provider.stage}.ENVIRONMENT5}
```
sls print --stage Dev --param="environmentDivision=Dev"
```
service: XXX
provider:
  name: aws
  runtime: dotnet6
  region: ap-northeast-1
  stackName: XXX-Dev
  apiName: XXX-Dev
  memorySize: 512
  timeout: 28
  logRetentionInDays: 400
  role: arn:aws:iam::Value1:role/Value2
  versionFunctions: false
  tracing:
    apiGateway: true
    lambda: true
  environment:
    ENVIRONMENT1: Value1
    ENVIRONMENT2: Value2
    ENVIRONMENT3: Value3
    ENVIRONMENT4: Value4
    ENVIRONMENT5: Value5
  tags:
    Cost: XXX
  logs:
    restApi: true
  endpointType: private
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action:
          - execute-api:Invoke
        Resource: execute-api:/*/*/*
      - Effect: Deny
        Principal: '*'
        Action:
          - execute-api:Invoke
        Resource: execute-api:/*/*/*
        Condition:
          StringNotEquals:
            aws:sourceVpce: Value3
  stage: Dev
package:
  artifact: bin/release/netapp6/lambda-function.zip
  exclude:
    - README.md
    - .git/**
    - .gitignore
    - .vscode/**
    - aws-csharp.csproj
    - build.cmd
    - build.sh
    - set_accessKeys.bat
    - unset_proxy.bat
  artifactsS3KeyDirname: serverless/XXX/Dev/code-artifacts
custom:
  Dev:
    ENVIRONMENT1: Value1
    ENVIRONMENT2: Value2
    ENVIRONMENT3: Value3
    ENVIRONMENT4: Value4
    ENVIRONMENT5: Value5
functions:
  Dev:
    ENVIRONMENT1: Value1
    ENVIRONMENT2: Value2
    ENVIRONMENT3: Value3
    ENVIRONMENT4: Value4
    ENVIRONMENT5: Value5
    events: []
    name: XXX-Dev-Dev
```

@gavinsui1106 I was able to successfully run `sls print --stage Dev --param="environmentDivision=Dev` with the sample configuration you provided. However, you did not include the serverless_functions file referenced in your serverless.yml. The error might be originating from that file. Could you please share more of your configuration so we can better reproduce and diagnose the issue?
