### DISCUSSION TITLE
AWS IoT serverless deploy Error

### DISCUSSION THREAD

**Discussion by ryan-bloom** [serverless/serverless#12473] [Q&A]
Hi! I'm building a serverless lambda function to run on an iot rule but I keep getting an error when running `serverless deploy` that says:
```
Error:
CREATE_FAILED: IotconsumerIotTopicRule1 (AWS::IoT::TopicRule)
Resource handler returned message: "Access denied for operation 'CreateTopicRule'." (RequestToken: 759009f3-8e71-50ff-2ffb-9791d1a540d3, HandlerErrorCode: AccessDenied)
```

my serverless.yaml file's function looks like this and in handler.py, the my method is `iotconsumer(event, context)`:
```
provider:
  name: aws
  deploymentMethod: direct
  region: us-west-2
  runtime: python3.10

functions:
  iotconsumer:
    handler: handler.iotconsumer
    events:
      - iot:
          sql: "SELECT * FROM 'my/topic/here'"
```

I've confirmed that my aws role has the iot:TopicRule and the iot:CreateTopicRule permission policies and cant seem to figure out why this create topic rule is failing.

Am I missing something else from my serverless.yaml that is needed? Any thoughts/help would be greatly appreciated!

**Comment by ryan-bloom** [comment]
I've also tried adding this to my `provider:` section of serverless.yaml which resulted in the same behavior/error:
```
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
                - 'iot:CreateTopicRule'
          Resource: '*'
```
