### DISCUSSION TITLE
Serverless offline display an error when it run

### DISCUSSION THREAD

**Discussion by mferreiradb** [serverless/serverless#12593] [General]
When i run the `sls offline` command my application runs but it display the following warn

> Warning: Invalid configuration encountered
>   at 'functions.api.events.0.httpApi': unrecognized property 'cors'
> 
> Learn more about configuration validation here: http://slss.io/configuration-validation
> 

My serverless.yml

```
provider:
  name: aws
  runtime: nodejs18.x
  deploymentMethod: direct
  stage: v1
  region: us-west-2

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-prune-plugin

custom:
  serverless-offline:
    apiKey: 'local'
    httpPort: 4000
    lambdaPort: 4005
  prune:
    automatic: true
    number: 3

functions:
  api:
    handler: src/handler.run
    timeout: 30
    memorySize: 1024
    url:
      cors:
        allowedOrigins:
          - '*'
        allowedHeaders:
          - '*'
        allowedMethods:
          - '*'
    events:
      - httpApi:
          path: /{proxy*}
          method: ANY
          cors:
            allowCredentials: true
            allowedOrigins:
              - '*'
            allowedHeaders:
              - '*'
            allowedMethods:
              - '*'

```
