### DISCUSSION TITLE
How to pass the MQ Broker ARN to RabbitMQ event using GetAtt?

### DISCUSSION THREAD

**Discussion by nbcchen** [serverless/serverless#12676] [Q&A]
How do I pass the ARN of the broker to the event definition, if the broker is created by the same stack?

```yaml
functions:
  consumer:
    events:
      - rabbitmq:
          arn: !GetAtt Broker.Arn # Serverless said this is not valid 
resources:
  Resources:
    Broker:
      Type: AWS::AmazonMQ::Broker
```

Serverless complains that`arn` has to be a string.
