### DISCUSSION TITLE
RoleARN not set in serverless EventBridge scheduler

### DISCUSSION THREAD

**Discussion by datamaker** [serverless/serverless#12750] [Q&A]
I found out that I can't set roleARN in serverless event bridge. Why?

as-is
`
              roleArn = functionResource.Properties.Role
`

I tried writing the code below.

to-be
`
              roleArn =  event.schedule.roleArn || functionResource.Properties.Role
`

serverless.yml
```yaml
functions:
  function:
    handler: bootstrap
    events:
      - schedule:
          method: scheduler
          name: ${env:BITBUCKET_REPO_SLUG}-scheduler
          rate:
            - cron(0 8 * * ? *)
          timezone: Asia/Seoul
          input:
            command: start
          roleArn: ${env:AWS_IAM_ROLE_SCHEDULER}
```

https://github.com/serverless/serverless/blob/fec8e287743fcb9348827785079716fc91e8e6cb/lib/plugins/aws/package/compile/events/schedule.js#L151

https://github.com/serverless/serverless/pull/11707/files/c17c6e20352881afaceba10890ebae3f0b0d9ca5
