### DISCUSSION TITLE
How to create schedule instead of rule when function uses custom role

### DISCUSSION THREAD

**Discussion by Tsingis** [serverless/serverless#12902] [Q&A]
When I'm switching from 

```
functions:
  handler:
    handler: handler.handler
    role: arn:aws:iam::${aws:accountId}:role/LambdaRole
    events:
      - schedule: cron(0 5 * * ? *)
```
      
  to
  
```
functions:
  handler:
    handler: handler.handler
    role: arn:aws:iam::${aws:accountId}:role/LambdaRole
    events:
      - schedule:
          method: scheduler
          rate: cron(0 7 * * ? *)
          timezone: Europe/Helsinki
```

Schedule is not created at all. Rule is created without issues.

Info picked from https://www.serverless.com/framework/docs/providers/aws/events/schedule
