### DISCUSSION TITLE
Serverless deploys same artifact to all functions despite different artifact paths specified

### DISCUSSION THREAD

**Discussion by iamvishalx** [serverless/serverless#13030] [Q&A]
Hey everyone,

I'm encountering a problem with Serverless where all Lambda functions in my service are being deployed with the same artifact (code bundle), despite explicitly configuring different artifact paths for each function. Specifically, all functions end up using the artifact from the last function defined in the serverless.yml file. 

I'm sharing a stripped-down version of my `serverless.yml` file.

Any insights or workarounds would be greatly appreciated! 

```
service: my-service

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: my-service-${self:provider.stage}

  versionFunctions: false
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 29
  tracing:
    lambda: true

  deploymentBucket:
    name: ${param:OutputPrefix}-deployment-bucket
    serverSideEncryption: AES256
    blockPublicAccess: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

package:
  individually: true

plugins:
  - serverless-offline

custom:
  PUBLIC_KEY: ${ssm:/aws/reference/secretsmanager/PUBLIC_KEY}
  apiVersion: v1
  serverless-offline:
    httpPort: 4001
    lambdaPort: 4003
    noPrependStageInUrl: true
    noAuth: true

functions:
  # Query Operations
  queryOperations:
    handler: index.handler
    name: QueryOperationsFunction-${self:provider.stage}
    package:
      artifact: ../../src/functions/queries/dist/bundle.zip
    environment:
      TOPIC_ARN: ${param:OutputPrefix}-Topic
    events:
      - http:
          path: /${self:custom.apiVersion}/api/get-items
          method: post
          cors: true
          integration: lambda-proxy

  # Mutation Operations
  mutationOperations:
    handler: index.handler
    name: MutationOperationsFunction-${self:provider.stage}
    package:
      artifact: ../../src/functions/mutations/dist/bundle.zip
    environment:
      TABLE_NAME: ${param:OutputPrefix}-Table
    events:
      - http:
          path: /${self:custom.apiVersion}/api/update-item
          method: post
          cors: true
          integration: lambda-proxy

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${param:OutputPrefix}-api-${self:provider.stage}
        EndpointConfiguration:
          Types:
            - REGIONAL
```
