### DISCUSSION TITLE
Provisioned Concurrency is not working as expected

### DISCUSSION THREAD

**Discussion by mydeen1989** [serverless/serverless#9341] [Q&A]
Hi,

I am new user to  serverless framework. My lambda is throwing higher response time. When I see the documentation it can fix by  provisionedConcurrency. I tried to add the same in my serverless.yml but still my issue is not resolved. 

Serverless version

Framework Core: 1.83.3 (local)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9

Added provisionedConcurrency: 3 and versionFunctions: false in serveless.yml

able to see the same in aws console. 

![concurrency](https://user-images.githubusercontent.com/41736927/115188429-89de8400-a102-11eb-8c20-1f69793ea440.PNG)

I have added the below code to verify the cold start fix

var coldStart = true;
console.log("This line of code exists outside the handler, and only executes on a cold start >>>> in Connect lambda");
exports.handler = async event => {
    if (coldStart) {
        console.log("First time the handler was called since this function was deployed in this container");
    }
    coldStart = false;

I can see this log "First time the handler was called since this function was deployed in this container" whenever the lambda function newly invoked.

2021-04-19T11:02:32.624+05:30 | START RequestId: bf9d9030-0527-441d-bf05-d0abd4b32170 Version: $LATEST
-- | --
  | 2021-04-19T11:02:33.191+05:30 | LOGS Name: cloudwatch_lambda_agent State: Subscribed Types: [platform]
  | 2021-04-19T11:02:33.193+05:30 | 2021-04-19T05:32:33.190Z undefined INFO This line of code exists outside the handler, and only executes on a cold start >>>> in Connect lambda
  | 2021-04-19T11:02:33.193+05:30 | EXTENSION Name: cloudwatch_lambda_agent State: Ready Events: [INVOKE,SHUTDOWN]
  | 2021-04-19T11:02:33.196+05:30Copy2021-04-19T05:32:33.196Z	bf9d9030-0527-441d-bf05-d0abd4b32170	INFO	First time the handler was called since this function was deployed in this container | 2021-04-19T05:32:33.196Z bf9d9030-0527-441d-bf05-d0abd4b32170 INFO First time the handler was called since this function was deployed in this container

2021-04-19T11:08:48.960+05:30 | START RequestId: 87a087ed-5fcb-4e62-b42a-e3d44b4353db Version: $LATEST
-- | --
  | 2021-04-19T11:08:49.512+05:30 | LOGS Name: cloudwatch_lambda_agent State: Subscribed Types: [platform]
  | 2021-04-19T11:08:49.513+05:30 | 2021-04-19T05:38:49.511Z undefined INFO This line of code exists outside the handler, and only executes on a cold start >>>> in Connect lambda
  | 2021-04-19T11:08:49.513+05:30 | EXTENSION Name: cloudwatch_lambda_agent State: Ready Events: [INVOKE,SHUTDOWN]
  | 2021-04-19T11:08:49.517+05:30Copy2021-04-19T05:38:49.516Z	87a087ed-5fcb-4e62-b42a-e3d44b4353db	INFO	First time the handler was called since this function was deployed in this container | 2021-04-19T05:38:49.516Z 87a087ed-5fcb-4e62-b42a-e3d44b4353db INFO First time the handler was called since this function was deployed in this container

I have noticed the below logs after lambda deployed 

2021-04-19T10:51:50.841+05:30CopyLOGS	Name: cloudwatch_lambda_agent	State: Subscribed	Types: [platform] | LOGS Name: cloudwatch_lambda_agent State: Subscribed Types: [platform]
-- | --
  | 2021-04-19T10:51:51.656+05:30 | 2021-04-19T05:21:51.648Z undefined INFO This line of code exists outside the handler, and only executes on a cold start >>>> in Connect lambda
  | 2021-04-19T10:51:51.658+05:30CopyEXTENSION	Name: cloudwatch_lambda_agent	State: Ready	Events: [INVOKE,SHUTDOWN] | EXTENSION Name: cloudwatch_lambda_agent State: Ready Events: [INVOKE,SHUTDOWN]

There is no metrics in provisionedConcurrency Invocations. Still my response time higher after I have added provisionedConcurrency: 3 . Could you please help me to resolve this.

![invocations](https://user-images.githubusercontent.com/41736927/115189268-d8d8e900-a103-11eb-89a8-6a37072b912e.PNG)

![lambda](https://user-images.githubusercontent.com/41736927/115189366-fad26b80-a103-11eb-95b1-9edfdf2f8b67.PNG)

**Comment by mydeen1989** [comment]
@medikoo

**Comment by pgrzesik** [comment]
Hello @mydeen1989. Please follow the template that is present when you create a new issue. Additionally, do you have the ability to upgrade to the latest version of the Framework? In `2.7.0` there was a fix for `provisionedConcurrency` for stream events: https://github.com/serverless/serverless/blob/master/CHANGELOG.md#270-2020-10-13

**Comment by mydeen1989** [comment]
@pgrzesik Thanks for your quick reply. Let me try to upgrade the serverless

**Comment by mydeen1989** [comment]
@pgrzesik . Serverless upgraded to latest version and redeployed in aws

Framework Core: 2.35.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3

Still my response time is higher.

![image](https://user-images.githubusercontent.com/41736927/115288437-1161dc80-a16f-11eb-8e62-f40936c4aa88.png)
 
I couldn't see any provisioned concurrency metrics in Invocations widget.

![image](https://user-images.githubusercontent.com/41736927/115288805-81706280-a16f-11eb-9693-bfa95b83e0cf.png)

**Comment by pgrzesik** [comment]
@mydeen1989 Please follow the issue template that is visible when you create a new issue, ideally please provide minimal reproducible example of your issue.

**Comment by mydeen1989** [comment]
@pgrzesik 


Q1: Describe the issue

Provisioned Concurrency is not working as expected . I have added provisionedConcurrency : 3 in serverless.yml to fix the cold start issue. But still I am getting the higher response time.

Q2: Provide FULL content of serverless.yml

```
service: myproject-serverless

provider:
    name: aws
    runtime: nodejs12.x
    versionFunctions: false
    profile: custom-profile
    region: us-east-1
    environment:
        connectionTableName: ${self:custom.connectionTableName}
        discussionTableName: ${self:custom.discussionTableName}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
          Resource: '*'

custom:
    connectionTableName: connections
    discussionTableName: discussions

functions:
    websocket-rfh-connect:
        handler: lambdas/websockets/connect.handler
        events:
            - websocket:
                  route: $connect
            - websocket:
                  route: $disconnect
            - websocket:
                  route: $default
            - websocket:
                  route: message
        provisionedConcurrency: 3
    websocket-response:
        handler: lambdas/websockets/response.handler
        provisionedConcurrency: 3
        events:
            - stream: XXXXXXXXXXXXXXXXXXXXXXXXX

resources:
    Resources:
        RFHUsersConnectionTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.connectionTableName}
                AttributeDefinitions:
                    - AttributeName: connectionId
                      AttributeType: S
                KeySchema:
                    - AttributeName: connectionId
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
        RFHUsersDiscussionTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.discussionTableName}
                AttributeDefinitions:
                    - AttributeName: discussionId
                      AttributeType: S
                KeySchema:
                    - AttributeName: discussionId
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
```

Q3: 
   Command : serverless deploy

Q4 : serverless version

Framework Core: 2.35.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3
