### DISCUSSION TITLE
EventBusPolicy Error

### DISCUSSION THREAD

**Discussion by ranjitharaj1** [serverless/serverless#9393] [Q&A]
Hi, I am trying to create EventBus ResourcePolicy in serverless. I get the below error during sls deploy

serverless -v
===========
Framework Core: 2.22.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.1

YAML
=======
 ```
    MyEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: "myeventbus"
    MyEventBusPolicy:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "allow_account_to_put_events"
        Statement:
          Effect: "Allow"
          Principal:
            AWS: "arn:aws:iam::xxxxxxxxxx:root"
          Action: "events:PutEvents"
          Resource: !GetAtt MyEventBus.Arn
```

An error occurred: MyEventBusPolicy - The relative-id "event-bus/myeventbus" is invalid for ARN "arn:aws:events:ca-central-1:2222222222:event-bus/myeventbus" (Service: AWSEvents; Status Code: 400; Error Code: ValidationException;
