### DISCUSSION TITLE
Serverless rollback does not recongnize the function name

### DISCUSSION THREAD

**Discussion by mehdiAhmed** [serverless/serverless#9486] [Q&A]
Hi,
When I try to rollback my function to the previous version, serverless does not recongnize my current function name.
Here my serverless.yml function

```
custom:
  stage: ${opt:stage, self:provider.stage}
functions:
  usersCreate:
    handler: src/index.handler
    name: Test-${self:custom.stage}
    deploymentSettings:
      type: AllAtOnce
      alias: Live
```

The deployment was made with:
`serverless deploy --stage stage1`

After three deployments, I list all functions deployed:
`serverless deploy list functions -s stage1` 

The results is:
> Serverless: Listing functions and their last 5 versions:
> Serverless: -------------
> Serverless: Test-stage1: $LATEST, 1, 2, 3

When I made the rollback of the function with:
`serverless rollback function --function Test-stage1 --function-version 1`
OR
`serverless rollback function --function Test-stage1 --function-version 1 --stage stage1`
I got the current error:
>`Serverless Error ----------------------------------------

>  Function "Test-stage1" doesn't exist in this Service
>
>  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

>  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.0
     Framework Version:         2.40.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.2`

How can I rollback Test-stage1 function to version 1 correctly please ?
