### DISCUSSION TITLE
The Serverless version (2.41.2) does not satisfy the "frameworkVersion" (2.35.0) in serverless.yml

### DISCUSSION THREAD

**Discussion by arslanalidev** [serverless/serverless#9488] [Q&A]
Recently I had the installed the higher version of the serverless 2.41.2 in my project. Due to this today when I tried to deploy my service on the AWS. It's showing me the error of the framework version. 
Then I tried to degrade my framework by following steps:

I had uninstall the current serverless framework with this command npm uninstall -g serverless.

After that I had run this command npm install -g serverless@2.35.0

But
When I run this command serverless --version it’s still showing the version 2.41.2 on my pc.

Now my question is how can I resolve this issue on my serverless file. Either should I degrade my serverless version. or go with the latest one v2.41.2 which may produce other bugs as well.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: rxd-administration

frameworkVersion: '2.35.0'
useDotenv: true
unresolvedVariablesNotificationMode: error
configValidationMode: error

plugins:
  - serverless-offline
  - serverless-plugin-git-variables
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  domains:
    local: local-api.carierx.app
    develop: develop-api.carierx.app
    staging: staging-api.carierx.app
    prod: api.carierx.app
  stageVariables:
    gitBranch: ${opt:stage, git:branch}

  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    basePath: 'administration'
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  excludeDevDependencies: true
  exclude:
    - /node_modules/** # no need to add this yourself, this plugin does it for you

provider:
  stage: ${opt:stage, git:branch}
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_REGION_CRED, 'us-east-1'}
  versionFunctions: false
  tags: 
    project: rxd-administration
  lambdaHashingVersion: 20201221

functions:
  - ${file(./tenant/serverless.yml)}
  - ${file(./auth/serverless.yml)}

  Outputs:
    AuthorizeUserLambdaFuncExport:
      Value:
        # Ref: SharedLambdaLayer
        Ref: AuthorizeUserLambdaFunction
      Export:
        Name: AuthorizeUserLambdaFunction
```

</details>

<details>
<summary><b><code>sls deploy -s local</code> output</b></summary>

```
 Serverless Error ----------------------------------------
 
  The Serverless version (2.41.2) does not satisfy the "frameworkVersion" (2.35.0) in serverless.yml
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.19.0
     Framework Version:         2.41.2
     Plugin Version:            5.0.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
```

</details>

<b>Installed version</b>

```
Operating System:          win32
Node Version:              12.19.0
Framework Version:         2.41.2
Plugin Version:            5.0.0
SDK Version:               4.2.2
Components Version:        3.9.2
```
