### DISCUSSION TITLE
How to Enable Server Access Logging on s3 bucket

### DISCUSSION THREAD

**Discussion by L-F-Escobar** [serverless/serverless#9527] [Q&A]
How do I programmatically enable `Server Access Logging` within my sls yaml file? 

```
resources:
  Resources:
    ClientLoggingBucketResource:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${file(config.json):LOGS_BUCKET}
        AccessControl: Private
        LoggingConfiguration:
          - TargetBucket: "!Ref DomainBucket"
          - TargetPrefix: logs
```

Ideally I would want something like this, I cant find ANY documentation on this.
