### DISCUSSION TITLE
Configuration Validation Error with Booleans and strToBool

### DISCUSSION THREAD

**Discussion by dapriett** [serverless/serverless#9697] [Q&A]
I am noticing a configuration validation warning when using `strToBool` below:

```
scheduledFunction:
    handler: lib/functions/scheduledFunction/index.handler
    timeout: 30
    events:
      - schedule:
          rate: ${env:SCHEDULE_RATE}
          enabled: strToBool(${env:SCHEDULE_ENABLED})
```

Produces the following validation error, even though generated stack is correct:

```
Serverless: Configuration warning:
Serverless:   at 'functions.scheduledFunction.events[0].schedule.enabled': should be boolean
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```
