### DISCUSSION TITLE
Error creating event rule for partner event bus (which was auto generated by appflow)

### DISCUSSION THREAD

**Discussion by chrisyorkston** [serverless/serverless#9709] [Q&A]
I am trying to create an event rule for the partner event bus i.e. `arn:aws:events:{region}:{accountId}:event-bus/aws.partner/appflow/salesforce.com/{accountId}` to send all events to an SQS queue in serverless but not having much luck, I keep hitting this error:

I can create this via the AWS console i.e. `arn:aws:events:{region}:{accountId}:rule/aws.partner/appflow/salesforce.com/{accountId}/myPartnerEventRule1`, but really struggling to create it via serverless / cloudformation.

Tried a few things with no avail:

* updated serverless to the latest version 2.51
* I do wonder if you create the event rule as part of the appflow definition AWS::AppFlow::Flow but can not find anything in the documentation; maybe im being blind.
* to 'rule' anything else out if i change EventBusName: value to Fn::ImportValue: 'DefaultEventBusARN-${self:custom.deployingStage}' i.e. a non partner event bus it deploys ok. But I want the rule on the partner event bus.
Any ideas?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
SFSubscriptionPartnerEventsRule:
            Type: AWS::Events::Rule
            Properties:
                Description: 'write salesforce subscription event to sqs'
                Name: 'events-${self:custom.deployingStage}-sfsubscriptionevent-sfsubscriptionsqs'
                EventBusName: # '${self:custom.eventBus.customerPlatformEventBusARN}' # '${self:custom.eventBus.customerPlatformSFPartnerEventBusARN}'
                    Fn::GetAtt:
                        - CustomerPlatformSFPartnerEventBus
                        - Arn
                EventPattern:
                    account:
                        - Ref: 'AWS::AccountId'
                State: ENABLED
                Targets:
                    -   Arn:
                            Fn::GetAtt:
                                - SFSubscriptionToCustomerPlatformQueue
                                - Arn
                        Id: '${self:custom.queue.sfSubscriptionToCustomerPlatformQueue}'
                        RetryPolicy:
                            MaximumRetryAttempts: 1
                            MaximumEventAgeInSeconds: 400
                        DeadLetterConfig:
                            Arn:
                                Fn::GetAtt:
                                    - SFSubscriptionToCustomerPlatformDeadLetterQueue
                                    - Arn
```

</details>

<details>
<summary><b><code>sls deploy -v --stage dev --environment dev    </code> output</b></summary>

```
Serverless Error ----------------------------------------
  An error occurred: SFSubscriptionPartnerEventsRule - EventBus name starting with 'aws.' is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: ; Proxy: null).
For context, partner event bus names are auto generated when creating appflow so there is no way of avoiding aws in the name.
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.51.0 (local)
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.2
```
