### DISCUSSION TITLE
How to package the function to always be as "root"

### DISCUSSION THREAD

**Discussion by arditshala** [serverless/serverless#9958] [General]
When you have multiple functions in one configuration, you usually end up having something like this:

```
  fooFunction:
    handler: functions/foo/bar/index.handler
    runtime: nodejs12.x
    package:
      exclude:
        - package*.json
      include:
        - 'functions/foo/bar/**'
```

However, when sls is deploying this, the package (ZIP) has a structure like this, where the handler is:
`/functions/foo/bar/index.js`

```
functions
  |__foo
        |__bar
              |__index.js
              |__config
                      |__default.yml    
```

However, different NPM packages and dependencies expect the handler to be root directory itself, ex. the `config` (node-config) module expects so and when that module tries to read the filesystem for the /config directory it can't, bcs the config directory is not actually at '/functions/foo/bar/config'.

Is there any way one can package the function to be the root folder, so copy everything from `/function/foo/bar/**` and let that be the directory and zip that one up and deploy to AWS?

So you can actually say `fs.readdirSync('./config')` instead of `fs.readdirSync('./functions/foo/bar/config')` on the `index.js` (handler).
