### DISCUSSION TITLE
Handler not getting recognized

### DISCUSSION THREAD

**Discussion by merrcury** [serverless/serverless#9988] [Q&A] [answered]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I wrote a python fastAPI code with Mangum handler and user serverless to deploy it on lambda. It deployed perfectly yesterday. Today, I added some unit test and now it's giving me a weird handler error. 

### Service configuration (serverless.yml) content

```yaml
service: phone-verify

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: phone-verify-layer
      description: Phone Verify Layer
      compatibleRuntimes:
        - python3.8

functions:
    handler: main.handler
    package:
      patterns:
        - "main.py"
        - "!.gitignore"
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.git/**"
        - "!venv/**"
        - "!node_modules/**"
        - "!.pytest_cache/**"
        - "!test/**"
        - "!.idea/**"
    environment:
      STAGE: ${self:provider.stage}
      API_KEY: redacted
      API_KEY_NAME: redacted
      CLIENT_ID: redacted
      CLIENT_SECRET: redacted
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
```

### Command name and used flags

sls deploy --stage staging

### Command output

```shell
Serverless Error ----------------------------------------
 
  Unexpected "handler" function configuration: Expected object received 'main.handler')
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.1
     Framework Version:         2.59.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.1
```

### Environment information

```shell
Framework Core: 2.59.0
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.1
```

**Comment by medikoo** [comment]
@merrcury error message is correct. Note that directly under `functions` you've put `handler: main.handler`.

Framework assumed `handler` as single function configuration which is expected to be an object, while it's a string

**Comment by merrcury** [comment]
HI @medikoo,
Now, There are more warning which are new to me. 
```bash
Serverless: Configuration warning:
Serverless:   at 'functions.package': unrecognized property 'patterns'
Serverless:   at 'functions.handler': should be object
Serverless:   at 'functions.environment': unrecognized property 'STAGE'
Serverless:   at 'functions.environment': unrecognized property 'API_KEY'
Serverless:   at 'functions.environment': unrecognized property 'API_KEY_NAME'
Serverless:   at 'functions.environment': unrecognized property 'CLIENT_ID'
Serverless:   at 'functions.environment': unrecognized property 'CLIENT_SECRET'
Serverless:   at 'functions.layers': should be object
Serverless:   at 'functions.events': should be object
```
I checked patterns as a property of functions.package but still a warning. Environment and handlers also as per [docs](https://www.serverless.com/framework/docs/providers/aws/guide/functions/#environment-variables). I feel I might be missing something silly. Would you throw some light on mistakes? FYI, I am using Apple M1

**Comment by medikoo** [comment, marked as answer]
@merrcury you're using unsupported configuration format.

What Framework supports is:

```yaml
functions:
  functionName:
     # function setting
```

What  you have is:

```yaml
functions:
  # function settings
```

All errors and warnings you see are valid.
