### ISSUE TITLE
SLS package no work for layer

### ISSUE THREAD

**Issue by lizaw** [serverless/serverless#10006]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

layers folder structure
.
└── Layers
    ├── Layer1
    │   └── nodejs
    │       └── node_modules
    │           └── mymodule
    │               ├── node_modules
    │               ├── index.js
    │               └── package.json
    └── serverless.yml

### Service configuration (serverless.yml) content

```yaml
service: layers

frameworkVersion: ^2.60.0

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2

package:
  patterns:
    - ./**

layers:
  layer1:
    path: mymodule
    compatibleRuntimes:
      - nodejs12.x
    package:
      patterns:
        - ./**
```

### Command name and used flags

sls package

### Command output

```shell
Serverless Error ----------------------------------------
 
  ServerlessError: No file matches include / exclude patterns
      at /snapshot/serverless/lib/plugins/package/lib/packageService.js:301:13
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async /snapshot/serverless/lib/plugins/package/lib/packageService.js:109:9
      at async Promise.all (index 0)
      at async Package.packageService (/snapshot/serverless/lib/plugins/package/lib/packageService.js:113:5)
```

### Environment information

```shell
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.60.0 (standalone)
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.1
```
