### ISSUE TITLE
Error when executing Lambda API endpoint: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by omar-enrique** [serverless/serverless#10033]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

So far, developing with Serverless has worked flawlessly for me.  I was able to deploy a functioning Lambda REST API with an endpoint get_customersite, which worked exactly how I expected.  This API is written in Python.  When I created a subfolder, however, and put a new Python script in it that would serve as the source for another API call, called get_site_time, my Lambda function started failing.   This is the directory tree of my project

C:.
├───customersite.py
├───django_layer
├───test_api
│   └───site_info.py
└───serverless

My serverless.yml below shows how I defined both the get_customersite and get_site_time endpoints.  Inside each python file is a python function, named to match the endpoints.  For the sake of diagnosing my problem, I simplified both functions to have the same format:

```
def get_customersite(event, context):
    print('Event', event['queryStringParameters'])
    print('Context', context)
    print('Customersite model', Customersite)
    name = event['queryStringParameters']['name']

    response = {
        "message": "Go Serverless v2.0! Your function executed successfully!",
        "customersite": name
    }
    
    return {
        "body": json.dumps(response),
        "statusCode": 200,
        "headers": {"Content-Type": "application/json"}
    }
```

`get_customersite` executed with a 200 and returns the response.  The endpoint for the get_site_time function found in that site_info python file, however, fails with the error I pasted into the command output section.

The error seems to happen in the file that the Serverless SDK creates when I deployed the lambda function, that is a layer for its execution.  That file is titled `s_get_site_time.py` and is written as follows:

```
import serverless_sdk
sdk = serverless_sdk.SDK(
    SDK_INFO
)

handler_wrapper_kwargs = {'function_name': 'test-api-dev-get_site_time', 'timeout': 6}
try:
    user_handler = serverless_sdk.get_user_handler(test_api.site_info.get_site_time')
    handler = sdk.handler(user_handler, **handler_wrapper_kwargs)
except Exception as error:
    e = error
    def error_handler(event, context):
        raise e
    handler = sdk.handler(error_handler, **handler_wrapper_kwargs)
```

The error message is `too many values to unpack (expected 2)`.

I am really puzzled by this issue.  Is this just saying that I can't have a script that is inside a module folder?  Iss it saying that `test_api.site_info.get_site_time` can only be 2 tokens at most, instead of 3, and therefore, you cannot have any code inside a folder that you need to step into?  

### Service configuration (serverless.yml) content

```yaml
org: test-org
app: test-api
service: test-api

frameworkVersion: '2'


provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: python3.7
  lambdaHashingVersion: 20201221
  
layers:
  djangolayer:
    path: django_layer
    description: ORM for interfacing with Django

functions:
  get_customersite:
    handler: customersite.get_customersite
    events:
      - http:
          path: /get-customersite
          method: get
    layers:
      - { Ref: DjangolayerLambdaLayer }
  get_site_time:
    handler: test_api.site_info.get_site_time
    events:
      - http:
          path: /get-site-time
          method: get
    layers:
      - { Ref: DjangolayerLambdaLayer }
```

### Command name and used flags

Called HTTP REST endpoint that is connected to Lambda function

### Command output

```shell
{
  "errorMessage": "too many values to unpack (expected 2)",
  "errorType": "ValueError",
  "stackTrace": [
    "  File \"/var/task/serverless_sdk/__init__.py\", line 144, in wrapped_handler\n    return user_handler(event, context)\n",
    "  File \"/var/task/s_get_site_time.py\", line 25, in error_handler\n    raise e\n",
    "  File \"/var/runtime/bootstrap.py\", line 127, in handle_event_request\n    response = request_handler(event, lambda_context)\n",
    "  File \"/var/task/serverless_sdk/__init__.py\", line 144, in wrapped_handler\n    return user_handler(event, context)\n",
    "  File \"/var/task/s_get_site_time.py\", line 25, in error_handler\n    raise e\n",
    "  File \"/var/runtime/bootstrap.py\", line 127, in handle_event_request\n    response = request_handler(event, lambda_context)\n",
    "  File \"/var/task/serverless_sdk/__init__.py\", line 144, in wrapped_handler\n    return user_handler(event, context)\n",
    "  File \"/var/task/s_get_site_time.py\", line 25, in error_handler\n    raise e\n",
    "  File \"/var/task/s_get_site_time.py\", line 20, in <module>\n    user_handler = serverless_sdk.get_user_handler('test_api.site_info.get_site_time')\n",
    "  File \"/var/task/serverless_sdk/__init__.py\", line 55, in get_user_handler\n    user_module_name, user_handler_name = user_module_and_handler.split(\".\")\n"
  ]
}
```

### Environment information

```shell
Framework Core: 2.60.1
Plugin: 5.4.5
SDK: 4.3.0
Components: 3.17.1
```
