### ISSUE TITLE
Race Condition when creating Lambda together Cognito UserPool, UserPoolResourceServer and UserPoolClient with custom scope

### ISSUE THREAD

**Issue by chrseidel** [serverless/serverless#10041]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm setting up a Lambda that is triggered by an API Gateway.
This is protected via an COGNITO_USER_POOLS authorizer.
This authorizer is referencing a UserPool which is being setup in the same serverless file.
At the same time, I'm also setting up a Client for client_credentials auth-flow and a custom scope.
This scope is being registered in a Resource Server for this UserPool in the same file as well.

When deploying this setup, the creation of the client fails, as it's trying to be created, before the ResourceServer is setup. I then get an error message, stating that the custom scope provided is invalid.

If I first setup the UserPool with the ResourceServer and only add the creation of the new user in a seperate second deployment, everything works. There seems to be a race condition that is not treated.

I hope this is the right place to report this, as this might also just be an issue of CloudFormation itself... 

### Service configuration (serverless.yml) content

```yaml
service:
  name: 'smart-asset-sorter'

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  timeout: 30
  stage: ${opt:stage, 'dev'}

custom:
  SERVICE_PREFIX: '${self:service.name}-${self:provider.stage}'
  SAS_SCOPE_IDENTIFIER: 'sas'
  SAS_SCOPE_NAME: 'read'
  SAS_READ_SCOPE: '${self:custom.SAS_SCOPE_IDENTIFIER}/${self:custom.SAS_SCOPE_NAME}'

functions:
  sas-sorting-request-handler:
    name: '${self:custom.SERVICE_PREFIX}-request-handler'
    handler: sas-handler/sas-handler
    tracing: Active
    events:
      - http:
          path: /sortings
          method: POST
          cors: true
          authorizer:
            name: '${self:custom.SERVICE_PREFIX}-cognito-authorizer'
            arn: '${self:custom.COGNITO_USER_POOL_ARN}'
            resultTtlInSeconds: 3600
            type: COGNITO_USER_POOLS
            scopes:
              - ${self:custom.SAS_READ_SCOPE}

resources:
  Resources:
    SASCognitoUserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: '${self:custom.SERVICE_PREFIX}-user-pool'
    SASCognitoUserPoolResourceServer:
      Type: "AWS::Cognito::UserPoolResourceServer"
      Properties:
        Identifier: '${self:custom.SAS_SCOPE_IDENTIFIER}'
        Name: '${self:custom.SERVICE_PREFIX}-resource-server'
        UserPoolId:
          Ref: SASCognitoUserPool
        Scopes:
          - ScopeDescription: 'read access'
            ScopeName: '${self:custom.SAS_SCOPE_NAME}'
    SASCognitoAppClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: '${self:custom.COGNITO_USER_POOL_ID}'
        ClientName: SAS_USER
        GenerateSecret: true
        AllowedOAuthFlowsUserPoolClient: True
        AllowedOAuthFlows:
          - client_credentials
        AllowedOAuthScopes:
          - ${self:custom.SAS_READ_SCOPE}
```

### Command name and used flags

serverless deploy --stage $STAGE --config serverless.yaml --region eu-central-1

### Command output

```shell
Run serverless deploy --stage $STAGE --config serverless.yaml --region ***
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service smart-asset-sorter.zip file to S3 (14.89 kB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........................
Serverless: Operation failed!
Serverless: View the full error output: https://***.console.aws.amazon.com/cloudformation/home?region=***#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3A***%3A***%3Astack%2Fsmart-asset-sorter-dev%2F1a14ba80-21eb-11ec-9b70-06fc41f4ceac
 
 Serverless Error ----------------------------------------
 
  An error occurred: SASCognitoAppClient - Invalid scope requested: sas/read (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: ScopeDoesNotExistException; Request ID: b43f235a-ee64-44ee-99ec-1fb9a4ebe36d; Proxy: null).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.18.0
     Framework Version:         2.60.1
     Plugin Version:            5.4.5
     SDK Version:               4.3.0
     Components Version:        3.17.1
 
Serverless: Deprecation warnings:

Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name.
More Info: https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION

Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2

Error: Process completed with exit code 1.
```

### Environment information

```shell
     Operating System:          linux
     Node Version:              14.18.0
     Framework Version:         2.60.1
     Plugin Version:            5.4.5
     SDK Version:               4.3.0
     Components Version:        3.17.1
```
