### ISSUE TITLE
scheduled lambda function not triggering when rate is specified in hours

### ISSUE THREAD

**Issue by b-tiwari** [serverless/serverless#10056]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a  lambda that runs good when I set its scheduled recurring rate to something like 4 or 5 minutes.
However, when I change the rate to 2 hours, it never triggers.

I also tried using **warmup plugin**, still the same. would anyone have any idea whats going wrong here

```
...
...
sendNotifications:
    handler: src/modules/notifications/sendNotifications.main
    warmup:
      default:
        enabled: true
    events:
      - schedule:
          rate: rate(4 minutes) <-- it works with this
          enabled: true
...
...

```

but if I just change the rate to 2 hours it doesn't work

```
...
...
sendNotifications:
    handler: src/modules/notifications/sendNotifications.main
    warmup:
      default:
        enabled: true
    events:
      - schedule:
          rate: rate(2 hours) <-- lambda never triggers with this rate schedule
          enabled: true
...
...

```

### Service configuration (serverless.yml) content

```yaml
service:
  name: my-serverless-api

plugins:
  - serverless-webpack
  - serverless-plugin-warmup

custom:
  dataTable1: "data1-${opt:stage}"
  dataTable2: "data2-${opt:stage}"
  warmup:
    default:
      enabled: true
      role: IamRoleLambdaExecution
      events:
        - schedule: rate(114 minutes)

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: us-east-1

  # iamRoleStatements to set the permissions for Lambda to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Update
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:CreateTopic
        - sns:ListTopics
        - sns:SetTopicAttributes
        - sns:DeleteTopic
        - sns:Publish
        - sns:Subscribe
        - sns:DeleteEndpoint
        - sns:CreatePlatformEndpoint
        - sns:GetEndpointAttributes
        - sns:ListPlatformApplications
      Resource: "arn:aws:sns:us-east-1:*:*"
  environment:
    WORDS_TABLE: ${self:custom.dataTable1}
    USERS_TABLE: ${self:custom.dataTable2}

resources:
  Resources:
    WordsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.dataTable1}
        AttributeDefinitions:
          - AttributeName: someAttr1
            AttributeType: S
          - AttributeName: someAttr2
            AttributeType: S
        KeySchema:
          - AttributeName: someAttr1
            KeyType: HASH
          - AttributeName: someAttr2
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    UsersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.dataTable2}
        AttributeDefinitions:
          - AttributeName: someAttr
            AttributeType: S
        KeySchema:
          - AttributeName: someAttr
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
functions:
  createData1:
    handler: src/modules/data1/create.main
    warmup:
      default:
        enabled: false
    events:
      - http:
          path: data1
          method: post
          cors: true
          authorizer: aws_iam
  getData1:
    handler: src/modules/data1/getById.main
    warmup:
      default:
        enabled: false
    events:
      - http:
          path: data1/{id}
          method: get
          cors: true
          authorizer: aws_iam
  updateData1:
    handler: src/modules/data1/update.main
    warmup:
      default:
        enabled: false
    events:
      - http:
          path: data1/{id}
          method: put
          cors: true
          authorizer: aws_iam
  snsDeviceAppEndpoint:
    handler: src/modules/notifications/snsDeviceAppEndpoint.main
    warmup:
      default:
        enabled: false
    events:
      - http:
          path: snsDeviceAppEndpoint
          method: post
          cors: true
          authorizer: aws_iam
  sendData1Notifications:
    handler: src/modules/notifications/sendNotifications.sendData1Notifications
    warmup:
      default:
        enabled: true
    events:
      - schedule:
          rate: rate(120 minutes)
          enabled: true
  hello:
    handler: handler.hello
    warmup:
      default:
        enabled: false
    events:
      - http:
          method: get
          path: hello
```

### Command name and used flags

n/a

### Command output

```shell
n/a
```

### Environment information

```shell
MacBook-Air:serverless-api btiwari$ serverless -version
Framework Core: 2.61.0
Plugin: 5.4.5
SDK: 4.3.0
Components: 3.17.1
```
