### ISSUE TITLE
s3 lifecycleConfiguration ExpirationInDays field doesn't allow for a CloudFormation If statement

### ISSUE THREAD

**Issue by ROSeaboyer** [serverless/serverless#10081]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I try to deploy a stack with an environment-dependent lifecycle configuration, I have to have configValidationMode set to warn because the s3->lifecycleConfiguration->Rules[]->ExpirationInDays property will only accept an integer value, not the result of an if. However, there's no issue with CloudFormation and the deployment completes successfully.

I'm pretty sure this can be resolved in plugins/aws/package/compile/events/s3/configSchema.js by flipping the ExpirationInDays property to be an anyOf with either the current schema (type of integer, minimum of 0) or the AwsCfIf definition, but there might be an obvious side-effect there that I'm missing

### Service configuration (serverless.yml) content

```yaml
service: sample-test
configValidationMode: warn
provider:
  name: aws
  region: ca-central-1
  stage: ${opt:stage}
  stackName: sample-test-${self:provider.stage}
  deploymentBucket:
    name: sample-test-${env:AWS_ACCOUNT_ID}-${self:provider.region}
    serverSideEncryption: AES256
  lambdaHashingVersion: 20201221
  runtime: python3.8
  memorySize: 128
  timeout: 15
  s3:
    testbucket:
      name: sample-test-${self:provider.stage}-test
      lifecycleConfiguration:
        Rules:
          - Id: Rule1
            Prefix: input/
            Status: Enabled
            ExpirationInDays: !If [TestCondition, 2, 1]
functions:
  testfunction:
    name: sample-test-${self:provider.stage}-test
    handler: test.handler
    events:
      - s3:
          bucket: testbucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: input/
```

### Command name and used flags

package

### Command output

```shell
Serverless: Configuration warning at 'provider.s3.testbucket.lifecycleConfiguration.Rules[0].ExpirationInDays': should be integer
```

### Environment information

```shell
Framework Core: 2.62.0 (local)
Plugin: 5.4.6
SDK: 4.3.0
Components: 3.17.1
```
