### ISSUE TITLE
#!/usr/bin/env node making bug

### ISSUE THREAD

**Issue by albasyir** [serverless/serverless#10084]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Got error when install serverless from npm or brew

![image](https://user-images.githubusercontent.com/28939309/136948329-5541c380-334c-4dd7-83fb-3427d5a3026b.png)

### Service configuration (serverless.yml) content

```yaml
service: teknoplan-app-container

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  apigwBinary:
    types:
      - '*/*'

functions:
  nuxt:
    handler: serverless.hendler
    events:
      - http: ANY {proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-offline
```

### Command name and used flags

sls

### Command output

```shell
/usr/local/Cellar/serverless/2.62.0/libexec/lib/node_modules/serverless/scripts/serverless.js:1
(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInThisContext (node:vm:305:10)
    at wrapSafe (node:internal/modules/cjs/loader:1020:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
 
 Serverless Error ----------------------------------------
 
  Could not resolve path to locally installed serverless.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.11.0
     Framework Version:         2.62.0
     Plugin Version:            5.4.6
     SDK Version:               4.3.0
     Components Version:        3.17.1
```
