### ISSUE TITLE
Ability to pass --platform to docker build 

### ISSUE THREAD

**Issue by earnold** [serverless/serverless#10098]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Hi there,

I want to deploy a docker image to AWS Lambda. The base image for these build comes packaged for multiple architectures. 

I am on an m1 mac. When I build the docker image, it select the appropriate architecture for my machine (arm64). However, that sets me up for downstream issues. When this image is pushed to AWS lambda, it fails. That is because aws expect amd64 architecture. 

You can fix this by using the following `docker build . --platform=linux/amd64`. At present, there is no way to specify the platform component of the command. Therefore I cannot run `sls delply` from my solution. 

### Proposed solution (optional)

I should be able to specify the `platform` argument in serverless.yml. 

I could look like the following

```yml
provider:
  name: aws
  lambdaHashingVersion: 20201221
  ecr:
    images:
      appimage:
        path: ./
        platform: linux/amd64
```
