### ISSUE TITLE
Error when using AWS ECR image with TypeScript

### ISSUE THREAD

**Issue by LorenzoR** [serverless/serverless#10127]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I created a serverless project using template `aws-nodejs-typescript` doing:
`sls create --template aws-nodejs-typescript --path my-ts-project`

Then I added an ECR image and a function using it, similar to what is done in template `aws-nodejs-docker`

````
ecr: {
    images: {
        appimage: {
	    path: "./"
	}
    }
}
````

````
functions: {
    hello,
    docker: {
        image: {
	    name: "appimage"
	}
    }
},
````

Got error `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`.

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from '@serverless/typescript';

import hello from '@functions/hello';

const serverlessConfiguration: AWS = {
  service: 'ts',
  frameworkVersion: '2',
  custom: {
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ['aws-sdk'],
      target: 'node14',
      define: { 'require.resolve': undefined },
      platform: 'node',
    },
  },
  plugins: ['serverless-esbuild'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
    },
    lambdaHashingVersion: '20201221',
    ecr: {
      images: {
        appimage: {
          path: "./"
        }
      }
    }
  },
  // import the function via paths
  functions: {
    hello,
    docker: {
      image: {
        name: "appimage"
      }
    }
  },
};

module.exports = serverlessConfiguration;

```

### Command name and used flags

sls package --stage staging --region ap-southeast-2

### Command output

```shell
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Compiling to node14 bundle with esbuild...
Serverless: Compiling with concurrency: Infinity
 
 Type Error ----------------------------------------------
 
  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      at validateString (internal/validators.js:120:11)
      at Object.extname (path.js:1229:5)
      at /tmp/sarasa/ts/node_modules/serverless-esbuild/dist/helper.js:34:29
      at Array.map (<anonymous>)
      at extractFileNames (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/helper.js:31:35)
      at EsbuildServerlessPlugin.get rootFileNames [as rootFileNames] (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:152:46)
      at EsbuildServerlessPlugin.<anonymous> (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:225:49)
      at Generator.next (<anonymous>)
      at /tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:4:12)
      at EsbuildServerlessPlugin.bundle (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:192:16)
      at EsbuildServerlessPlugin.<anonymous> (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:86:28)
      at Generator.next (<anonymous>)
      at /tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:4:12)
      at before:package:createDeploymentArtifacts (/tmp/sarasa/ts/node_modules/serverless-esbuild/dist/index.js:85:63)
      at PluginManager.runHooks (/tmp/sarasa/ts/node_modules/serverless/lib/classes/PluginManager.js:573:41)
      at PluginManager.invoke (/tmp/sarasa/ts/node_modules/serverless/lib/classes/PluginManager.js:610:20)
      at PluginManager.run (/tmp/sarasa/ts/node_modules/serverless/lib/classes/PluginManager.js:672:7)
      at Serverless.run (/tmp/sarasa/ts/node_modules/serverless/lib/Serverless.js:467:5)
      at /tmp/sarasa/ts/node_modules/serverless/scripts/serverless.js:832:9
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.2
     Framework Version:         2.64.1 (local)
     Plugin Version:            5.5.0
     SDK Version:               4.3.0
     Components Version:        3.17.1
 
Serverless: Deprecation warning: Starting with next major version, "http.request.schema" property will be replaced by "http.request.schemas".
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_SCHEMAS
```

### Environment information

```shell
Framework Core: 2.64.1 (local)
Plugin: 5.5.0
SDK: 4.3.0
Components: 3.17.1
```
