### ISSUE TITLE
Enable deployment bucket versioning breaks encryption & public access block

### ISSUE THREAD

**Issue by mars-lan** [serverless/serverless#10130]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

https://github.com/serverless/serverless/pull/9912 introduced the ability to turn on versioning for the deployment bucket. Unfortunately, turning it on will also inadvertently turned off encryption & public access block, which defeat the original goal of enabling all three in https://github.com/serverless/serverless/issues/5797.

### Service configuration (serverless.yml) content

```yaml
# The part that matters

provider: 
  deploymentBucket:
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.64.1 (local)
Plugin: 5.5.0
SDK: 4.3.0
Components: 3.17.1
```
