### ISSUE TITLE
Exclude function from deployment package

### ISSUE THREAD

**Issue by AlexHladin** [serverless/serverless#10154]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

The main idea here is to allow to stay function in the functions list in the serverless.yml, but exclude it from the deployment package. In the yml configuration it will look like this:
```yml
functions:
  # deprecated
  foo:
    handler: functions/foo/handler.bar
    noDeploy: true
```

The `noDeploy` flag will show to the `Serverless` that function should be excluded from the deployment package.

This feature will allow staying in the code deprecated functions, but not required in the cloud provider.
