### ISSUE TITLE
Functions triggered via S3 events do not use provisioned concurrency

### ISSUE THREAD

**Issue by ankon** [serverless/serverless#10167]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm trying to use a function that reacts to S3 notifications, and has provisioned concurrency. 

The provisioned concurrency is applied, and I can see the alias in the Lambda console as well as the initialization code running in Cloudwatch. 

But, when an S3 event invokes the function a new instance is initialized, and the `:provisioned` alias is not used.

### Service configuration (serverless.yml) content

```yaml
service: serverless10167
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  logs:
    frameworkLambda: true


functions:
  test:
    handler: index.handler
    provisionedConcurrency: 1
    events:
      - s3:
          bucket: !Ref Bucket
          existing: true

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
```

See https://github.com/ankon/serverless-10167 for a runnable repository.

### Command name and used flags

deploy

### Environment information

```shell
Framework Core: 2.64.1 (local)
Plugin: 5.5.0
SDK: 4.3.0
Components: 3.17.1
```
