### ISSUE TITLE
CloudFront customized DefaultCacheBehavior is being overwritten

### ISSUE THREAD

**Issue by rcelestino** [serverless/serverless#10174]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

There are some scenarios where you want to customize your CDN default behavior to follow another origin (s3 or another site, for example, a website) instead of the serverless-lambda-API-etc itself.  To do this you should customize the CloudFront distribution in your Resources section of your serverless.yaml.

```
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
````

In that scenarios, the current implementation is overwriting the default cache behavior no matter you set "isDefaultOrigin" to false. In the current implementation, if you have more than one origin with path patterns, it raises an error but if you have only one, it is moving forward with the packaging process considering the single origin as the default too. 

It would be really nice to avoid this. Probably having a flag to avoid it,  or changing the logic to consider if there is already on defaultcachebehavioir customized in the yaml resources then doesn't overwrite unnecessary if there isn't any function flagged as default.

Related blocks

- https://github.com/serverless/serverless/blob/ee38f6a3081a3a0f22ee9fea8975f13520ac18ec/lib/plugins/aws/package/compile/events/cloudFront.js#L596
- https://github.com/serverless/serverless/blob/ee38f6a3081a3a0f22ee9fea8975f13520ac18ec/lib/plugins/aws/package/compile/events/cloudFront.js#L697

Any idea how to avoid this?

### Service configuration (serverless.yml) content

```yaml
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
```

```
  imageresizercf:
    handler: eventsedge.imageresizer
    timeout: 10
    events:
      - cloudFront:
          eventType: 'origin-response'
          isDefaultOrigin: false
          includeBody: false
          pathPattern: resize/* 
          behavior:
            AllowedMethods:
```
```


### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.64.1
Plugin: 5.5.0
SDK: 4.3.0
Components: 3.17.1
```
