### ISSUE TITLE
Ability to disable the API Gateway Request Validator on v2

### ISSUE THREAD

**Issue by jweyrich** [serverless/serverless#10229]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We migrated some of our projects from Serverless 1.83 to ^2.60 and we are facing an issue related to Request Validators being created and enabled automatically for us on the API Gateway.

This seems related to these commits:
- https://github.com/serverless/serverless/commit/154351f1a5925a745873895014ed31f03b2842b3
- https://github.com/serverless/serverless/commit/cb109dd835ec358bfb1af10fe8f82aa283ffbafe

All our Lambda functions have JSON Schemas defined in serverless.yml, but we never relied on the Request Validator from API Gateway. We have specific code in our Lambdas to validate request body, headers and parameters. Now that we migrated to ^2.60, we noticed our APIs are deployed to the API Gateway with a Request Validator enabled for each endpoint.

I searched for issues related to "Request Validator" and found many people asking the opposite - to enable the request validator, to make it work, to enable it, etc. But since we have complex validation logic in some cases that are not supported by JSON schema, we cannot currently rely on the validations based on the JSON Schema.
The situation now is that some of our responses are being rejected by API Gateway as Bad Request, and the default BadRequest response is being sent. If the validation passes the API Gateway validator, but doesn't pass our Lambda logic that has all complex validations, it returns BadRequest with a completely diferent response from that from API Gateway. We could define a custom response for BadRequest to make it look like the from our Lambda, but as I said, we don't need the API Gateway request validator - in fact, we don't want it - since we already have all validation logic in a single place (Lambda code) that supports all kinds of complex conditions we need.

Is there an option to disable the request validator? An opt-out configuration that we can add to the serverless.yml to disable this behavior?

I reported as a bug since it looks like a new feature in v2 that caused regression to our APIs that were previously running ok on v1. I failed to find a reference or changelog explaining that behaviour as well.  Feel free to update/change this issue to reflect what it looks like to you (maybe a feature request?).

### Service configuration (serverless.yml) content

```yaml
Maybe N/A. It has almost 2k lines and split in different yamls.
```

### Command name and used flags

serverless.js deploy --stage $STAGE --package .artifacts

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.66.1 (local)
Plugin: 5.5.0
SDK: 4.3.0
Components: 3.17.1
```

**Comment by pgrzesik** [comment]
Hello @jweyrich :wave: Thanks for reporting, before moving forward I have a question - could you please share a minimal snipped with how you define schemas for your functions? If you're not using API Gateway schema validation, what is the reason for specifying them and attaching to API Gateway in the first place (that's what `schemas` on event level are responsible for)?

**Comment by jweyrich** [comment]
@pgrzesik thanks for the quick reply. Giving a bit of context, we currently have over 850 deployed lambdas distributed in ~30 projects that use Serverless v1 and we're migrating them to v2.
The main reason for us to define the schemas is to generate SDKs from APIGW and also to export the Swagger/OpenAPI definition so we can publish them to our API documentation (swagger) portal.

Below is an approximate snippet of what we currently use. I've renamed models/paths/descriptions just to avoid publishing useless details of our domain. I've annotated the changes with angle brackets, eg.: `<edited>`, `<removed-lines>`.

```yaml
custom:
  <removed-lines>
  documentation:
    api:
      info:
        version: '1.0.0'
        <removed-lines>
    models:
      - name: ServiceCreateResponse
        description: '<edited> Service creation response.'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                service:
                  $ref: '{{model: ServiceCreateResponse}}'
            result:
              $ref: '{{model: Result}}'
      - name: ServiceFindResponse
        description: '<edited> Service find response.'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            data:
              type: object
              properties:
                services:
                  $ref: '{{model: ServiceModel}}'
            result:
              $ref: '{{model: Result}}'
      - name: ServiceListResponse
        description: '<edited> List services response.'
        contentType: 'application/json'
        schema:
          type: object
          properties:
            data:
              type: array
              items:
                $ref: '{{model: ServiceModel}}'
            result:
              $ref: '{{model: Result}}'
      - name: ServiceModel
        description: '<edited> Service model'
        contentType: 'application/json'
        schema: ${file(docs/service-model.json)}
      - name: ErrorResponse
        contentType: 'application/json'
        schema: ${file(docs/entity-error.json)}
      - name: Result
        description: '<edited> Result de sucesso'
        contentType: 'application/json'
        schema: ${file(docs/result.json)}
  commonModelSchemaFragments:
    MethodResponse404Json:
      statusCode: '404'
      description: 'Not found'
      responseModels:
        'application/json': ErrorResponse
    MethodResponse412Json:
      statusCode: '412'
      description: 'Invalid or required attribute: {attributeName}.'
      responseModels:
        'application/json': ErrorResponse
    MethodResponse400Json:
      statusCode: '400'
      description: 'Invalid request.'
      responseModels:
        'application/json': ErrorResponse

functions:
  v1-service-create:
    handler: build/api/v1/service/create/lambda.execute
    name: ${self:service}-v1-service-create
    timeout: 30
    package:
      include:
        - build/api/v1/service/create/**
    events:
      - http:
          path: v1/services
          method: post
          cors: true
          authorizer:
            <removed-lines>
          documentation:
            summary: 'create a service'
            description: "<removed>"
            tags:
              - service
            requestModels:
              'application/json': 'ServiceModel'
            methodResponses:
              - statusCode: '200'
                responseModels:
                  'application/json': 'ServiceCreateResponse'
              - ${self:custom.commonModelSchemaFragments.MethodResponse400Json}
              - ${self:custom.commonModelSchemaFragments.MethodResponse412Json}
```

For Serverless v1 we were using the [serverless-aws-documentation](https://github.com/deliveryhero/serverless-aws-documentation) plugin to help us publish the documentation to APIGW, but it doesn't support Serverless v2 and is no longer maintained.
For Serverless v2 we were out of options until we found a fork named [serverless-aws-apigateway-documentation](https://github.com/Kakkuk/serverless-aws-apigateway-documentation) that does support Serverless v2.

If you have any suggestions on how we could approach this differently, we're open.
