### ISSUE TITLE
New variable resolver does not print unresolved SSM Parameter Paths

### ISSUE THREAD

**Issue by beanaroo** [serverless/serverless#10246]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Setting `variablesResolutionMode: 20210326` conveniently causes deploy to error when an SSM parameter is not resolved.

Unfortunately, the warning with the parameter path is no longer emitted.

This makes it harder to identify which parameter is unresolved.

With the legacy resolver, it looks like:

```
$ serverless deploy

 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/config/project/environments/development/uk/qa/dynamodb/tables/eu-west-2/Foo/policy/write' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:/config/project/environments/development/uk/qa/dynamodb/tables/eu-west-2/Foo/policy/read' could not be found.

Serverless: Configuration warning:
Serverless:   at 'provider.iam.role.managedPolicies[0]': unsupported configuration format
Serverless:   at 'provider.iam.role.managedPolicies[1]': unsupported configuration format
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Service configuration (serverless.yml) content

```yaml
service: my-service

variablesResolutionMode: 20210326

custom:
  ssm:
    tier: ${env:TIER, 'development'}
    localization: ${env:LOCALE, 'uk'}
    config: /config/project/environments/${self:custom.env.tier}/${self:custom.env.localization}/${self:provider.stage}

provider:
  iam:
    role:
      managedPolicies:
        - ${ssm:${self:custom.env.config}/dynamodb/tables/${self:provider.region}/Foo/policy/read}
        - ${ssm:${self:custom.env.config}/dynamodb/tables/${self:provider.region}/Foo/policy/write}
```

### Command name and used flags

serverless deploy

### Command output

```shell
Serverless Error ----------------------------------------

  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.iam.role.managedPolicies.0": Value not found at "ssm" source,
    - Cannot resolve variable at "provider.iam.role.managedPolicies.1": Value not found at "ssm" source
```

### Environment information

```shell
Framework Core: 2.66.1 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.0
```
