### ISSUE TITLE
Support for ContentHandling on CORS Prefilight OPTION Integration.IntegrationResponses

### ISSUE THREAD

**Issue by alarita** [serverless/serverless#10254]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I have a similar issue related to this post: https://forums.aws.amazon.com/thread.jspa?threadID=256140

The issue I had is that CORS will fail with an "unsupported" error, but I can't see any documentation that supports this out of the box. 

To fix this issue currently is to change the IntegrationResponses 2xx ContentHandling to CONVERT_TO_TEXT using a local custom plugin to intercept the CF using the hook `before:package:finalize`.

This is the expected CloudFormation:
```js
{ 
  "HttpMethod": "OPTIONS",
...
  "Integration": {
    "Type": "MOCK",
    "RequestTemplates": {
      "application/json": "{statusCode:200}"
    },
    "ContentHandling": "CONVERT_TO_TEXT",
    "IntegrationResponses": [
      {
        "StatusCode": "200",
        "ResponseParameters": {
          "method.response.header.Access-Control-Allow-Origin": "'*'",
          "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'",
          "method.response.header.Access-Control-Allow-Methods": "'OPTIONS,GET'"
        },
        "ResponseTemplates": {
          "application/json": "#set($origin = $input.params(\"Origin\"))\n#if($origin == \"\") #set($origin = $input.params(\"origin\")) #end\n#if($origin.matches(\".+\")) #set($context.responseOverride.header.Access-Control-Allow-Origin = $origin) #end"
        },
        "ContentHandling": "CONVERT_TO_TEXT"
      }
    ]
  },
...
}
```

As I can see here no `ContentHandling` in the IntegrationResponses in the codebase https://github.com/serverless/serverless/blob/b8d386547f30ee3701e1f6ee6cacc0be08df426a/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js#L100.

### Proposed solution (optional)

Proposed to add a `response` in the `cors` config.

```yml
functions:
  LambdaFunctionID:
    name: lambda-function-name
    description: Lambda Function Descroption
    handler: lambda-function.handler
    events:
      - http:
          path: /path/to
          method: get
          cors: 
            origin: '*'
            response:
              200:
                contentHandling: CONVERT_TO_TEXT 
            ...
```
