### ISSUE TITLE
[RFC] Stage-specific configuration

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#10264]
### Use case description

Some configuration values in serverless.yml need to be dynamic, for different reasons:

- **Secrets**: to avoid exposing a sensitive value (like a credential)
- **Stage-specific configuration**: to change the configuration based on the stage (dev/prod/etc.)
- Other use cases are intentionally ignored in this initiative because they are less common (for example feature flags, etc.)

There are solutions for secrets (like Serverless Dashboard parameters, SSM, Secrets Manager…)

But for stage-specific configuration, the current and widespread practice is to use the "custom" section in serverless.yml, with nested variables:

```yaml
provider:
  environment:
    APP_DOMAIN: ${self:custom.stages.${sls:stage}.domain}

custom:
  stages:
    staging:
         domain: preview.myapp.com
    prod:
         domain: myapp.com
```

This approach works but is limited and complex. Let's make stage-specific configuration simpler.

### Proposed solution

Introduce a new `params` section in `serverless.yml`:

```yaml
params:
  prod:
    domain: myapp.com
  staging:
    domain: preview.myapp.com
```

The section contains a list of `param: value` listed under stage names.

Every parameter defined in that section can be used with the `${param:xxx}` variable:

```yaml
provider:
  environment:
    APP_DOMAIN: ${param:domain}

params:
  prod:
    domain: myapp.com
  staging:
    domain: preview.myapp.com
```

The variable resolves to the value that matches the current stage:

```yaml
$ serverless deploy --stage=prod
# The domain will be "myapp.com"

$ serverless deploy --stage=staging
# The domain will be "preview.myapp.com"
```

### Defaults

It is possible to define default values via the `default` keyword:

```yaml
provider:
  environment:
    APP_DOMAIN: ${param:domain}

params:
  default:
    domain: ${sls:stage}.myapp.com
  prod:
    domain: myapp.com
```

### Serverless Dashboard parameters

`${param:xxx}` is a variable [that already exists today](https://www.serverless.com/framework/docs/guides/parameters): it resolves parameters from [Serverless Dashboard](https://www.serverless.com/dashboard/), our SaaS monitoring product.

The `${param:xxx}` variable will be expanded to resolve parameters:

- from `serverless.yml`
- and from Serverless Dashboard

Note that using Serverless Dashboard is completely optional. Everything described here works locally without Serverless Dashboard.

Our goal is to provide a single concept that solves "stage-specific configuration" in a simple way. And for those that want to manage secret values with the same `${param:xxx}` variable, they can look into Serverless Dashboard.

### Resolution priority

Here is the priority to resolve a parameter:

- First, look in `params.<stage>` in serverless.yml
- If not found, then look in `params.default`
- If not found, throw an error

For projects that use Serverless Dashboard, here is the priority to resolve a parameter:

- First, look in `params.<stage>` in serverless.yml
- If not found, then look in the instance's parameters in Serverless Dashboard
- If not found, then look in `params.default`
- If not found, then look in the service's parameters in Serverless Dashboard
- If not found, throw an error

If you have any feedback please post it in this issue ❤️

**Comment by mwillbanks** [comment]
I am concerned that over the longevity of the project having the section named `params` might cause future issues where it might make sense for something else; since this is essentially stage variables, to me the naming convention makes more sense as: `stageParams` or `stageVars`. Going too general IMO leads to a future state where that name makes more sense for something else later on and thus requires a BC break or naming the field differently.

**Comment by mnapoli** [comment]
Thanks! @mwillbanks do you have examples/ideas of how the `params` name could be used for other things? I've been thinking about that but I'm not sure I see a scenario concrete enough that would be a problem here.

**Comment by arielweinberger** [comment]
I think this is a topic that should be tackled, so thanks for that. I have worked on multiple Serverless projects. Sometimes, even across teams, the way to define communication is not standardized.

I would recommend taking a look at how it's done at Pulumi (IaC service), which I found very intuitive. In a nutshell:

1. Pulumi uses the concept of **stacks** to define stages. So a project could have stacks named **dev**, **prod** and so on. You create/select stacks using `pulumi stack select dev` for example.
2. Each stack has its own configuration file. Once you create the stack, you get a `Pulumi.dev.yaml` file. These are obviously static configurations - but these are very common.
3. The logic that defines the infrastructure logic then has access to the config when you execute `pulumi up`.

I like this because:
1. It keeps `serverless.yml` clean.
2. It allows for overrides - e.g. `serverless-project/config/dev.local.yaml` which almost acts as an `.env` file that is not meant to be committed to source control.
3. Allows for a base configuration file - e.g. `serverless-project/config/base.yaml` that can be merged into by environment overrides.
3. It is still YAML so no major deviation.
4. Supports GitOps - e.g. patching YAML files in a single isolated file is much safer rather than patching the `serverless.yml` directly.
5. Could potentially include interpolations/templates in it done by t, although I don't have a strong opinion on this.

It might be seen as a slightly opinionated solution. I personally like "splitting" my IAM roles, resources, and also configuration files which reduces chances for conflict makes the easier to look up and maintain overall.

Curious to know what others think.

**Comment by mnapoli** [comment]
@arielweinberger thanks for those details, that interesting!

I can't help but think that it would be possible with that approach:

```yaml
# serverless.yml
...

params:
  default: ${file(serverless.defaults.yml)}
  prod: ${file(serverless.prod.yml)}
```

That approach would indeed work better for projects with 10, 20 or even 50 parameters. But it's still possible, and only requires a few lines of YAML (which make the file inclusion explicit).

Am I missing anything?
