### ISSUE TITLE
Warning on IAM Resource format

### ISSUE THREAD

**Issue by katlim-br** [serverless/serverless#10261]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm using this logic with a file `serverless.js`(instead of yml):
```
        iam: {
            role: {
                statements: [
                    {
                        Effect: "Allow",
                        Action: slsCfg.iam.dynamodb.allowActions,
                        Resource: "!GetAtt MyDynamoTable.Arn"
                    }
                ]
            }
        }
```

And when I run `sls package`, I get this warning (which in sls3 will become an error right?): 
`Configuration warning at 'provider.iam.role.statements[0].Resource[0]': unsupported string format`.

It should not give a warning, am I correct?

### Service configuration (serverless.yml) content

```yaml
iam: {
            role: {
                statements: [
                    {
                        Effect: "Allow",
                        Action: slsCfg.iam.dynamodb.allowActions,
                        Resource: "!GetAtt MyDynamoTable.Arn"
                    }
                ]
            }
        }
```

### Command name and used flags

sls package

### Command output

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Configuration warning at 'provider.iam.role.statements[0].Resource[0]': unsupported string format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.66.2 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
