### ISSUE TITLE
Add event filtering capabilites to stream (dynamodb, kinesis) and sqs events

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#10284]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Since Nov. 26th 2021, event source mapping for invoking lambda from SQS, EventBridge and DynamoDB streams support event filtering (see release [announcement here](https://aws.amazon.com/fr/about-aws/whats-new/2021/11/aws-lambda-event-filtering-amazon-sqs-dynamodb-kinesis-sources/)). I suggest we had the capability to define such filters in Serverless framework, on corresponding events.

### Proposed solution (optional)

This issue should be split in 2 pull requests:
- [x] Adding filter capabilities to `stream` type of event - this will impact DynamoDB and Kinesis event source mapping generation and requires modifications to be made to `lib/plugins/aws/package/compile/events/stream.js`
- [ ] Adding filter capabilities to `sqs` type of event - this will impact SQS event source mapping generation and requires modifications to be made to `lib/plugins/aws/package/compile/events/sqs.js`

The full documentation regarding implementation of those filters using Cloudformation can be found [here](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html).

All 3 sources require the addition of a `FilterCriteria` property on the `AWS::Lambda::EventSourceMapping` resource type.
This additional property is always a JSON with a `Filters` property containing up to 5 filters, each represented as an object containing a `Pattern` property.

In order to simplify pattern definition and be as close as possible to existing `pattern` property of the `eventBridge` event, i suggest the following implementation :

```yml
functions:
  compute:
    handler: handler.compute
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [MyDynamoDbTable, StreamArn]
          patterns:
            - eventName: [ "INSERT" ]
            - dynamodb:
                 NewImage:
                   Id:
                     N:
                       - numeric: [ >, 50, <=, 60 ]
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - MyKinesisStream
              - Arn
          patterns:
            - partitionKey: [ 1 ]
            - data:
                 Location: [ Los Angeles ]
      - sqs:
          arn:
            Fn::GetAtt:
              - MySecondQueue
              - Arn
          patterns:
            - attributes:
                 SenderId: [ AIDAIO23YVJENQZJOL4VO ]
            - body:
                 Location: [ Los Angeles ]
```

**Comment by mnapoli** [comment]
Thanks for getting this started!

One thing to note: you suggest the `patterns` property, but on EventBridge events the property is `pattern` (singular): https://www.serverless.com/framework/docs/providers/aws/events/event-bridge#setting-up-event-pattern-matching

I initially thought it was a typo, but it seems it's intentional: EventBridge matches all rules with an AND whereas, for streams/SQS, patterns are combined with an OR. So in the end going with `patterns` makes sense to me here.

**Comment by pgrzesik** [comment]
Thanks a lot for the proposal @fredericbarthelet - it looks great in my opinion 👍 

One thing that I've found while getting familiar with the feature myself - while the default limit of patterns is 5, it seems like you can request a quota increase to 10 - we should take that into account during implementation. Related docs: https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html

**Comment by medikoo** [comment]
@fredericbarthelet proposal looks great.

I just wonder wouldn't it be better to call the property on our side, a `filterPatterns` and not just `patterns`. It gives better context what those patterns refer to (note we also have `package.patterns`, so it can turn confusing).

WDYT @mnapoli @pgrzesik  ?

**Comment by pgrzesik** [comment]
That is a great suggestion in my opinion @medikoo - it definitely brings more clarity and avoids ambiguity with `package.patterns` as you explained. +1 from me

**Comment by fredericbarthelet** [comment]
Thanks @mnapoli @medikoo @pgrzesik for your suggestions :)

Regarding `patterns` vs `filterPatterns`, my intention was to stick with `eventBridge` events definition as both `SQS/Kinesis/DynamoDB` and `EventBridge` event filtering use the same syntax : hereafter extract from [Lambda event filter documentation](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html#filtering-syntax)
![image](https://user-images.githubusercontent.com/23530626/143897252-9a5cfd53-6486-4f05-8ee2-ca6583209c24.png)

The current way to define filter in `eventBridge` event is the `pattern` property. You can therefore have :

```yml
functions:
  processor:
    handler: index.main
    events:
      - eventBridge:
           pattern:
             detail:
               eventSource:
                 - cloudformation.amazonaws.com
      - stream:
           patterns:
             - data:
                  myValue:
                    - 12
                    - foo
```

To conclude :

| Property name  	| Advantages                                                                    	| Disavantages                                                                        	|
|----------------	|-------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------	|
| patterns       	| similar to `eventBridge.pattern` - helps understand the syntax is the same    	| possible confusion with `package.patterns`                                          	|
| filterPatterns 	| helps developer understand this is linked to Lambda event filter capabilities 	| introduce inconsistency between `eventBridge`, `sqs` and `stream` event definitions 	|
