### ISSUE TITLE
Invoke local doesn't work with individually packaging.

### ISSUE THREAD

**Issue by pikinier20** [serverless/serverless#10301]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Probably the same issue as:
https://github.com/serverless/serverless/issues/8729

Looks like the previous issue was addressed by PR but it still doesn't work for me.

### Service configuration (serverless.yml) content

```yaml
service: xyz

frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221

package:
  individually: true

functions:
  downloader:
    handler: xyz
    package:
      artifact: xyz.jar
    events:
      - sqs: xyz
```

### Command name and used flags

serverless invoke local -f downloader -p eventmock.json

### Command output

```shell
Serverless Error ----------------------------------------
 
  Artifact undefined doesn't exists, please compile it first.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
```

### Environment information

```shell
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              17.0.1
     Framework Version:         2.67.0
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1
```
