### ISSUE TITLE
The automatic ssm resolve "ignore" the (raw) flag.

### ISSUE THREAD

**Issue by omerinvia** [serverless/serverless#10314]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

while trying to use the `(raw)` functionality in the ssm resolve (after migrating to `variablesResolutionMode: 20210326`) it looks like when im trying to run `sls print` with `${ssm(raw):/secure_string}` im getting the `decrypted` value and not the encrypted one.
I tried to specify the region as well, and it looks the same.

### Service configuration (serverless.yml) content

```yaml
service: via-chat-ops
frameworkVersion: "2.68"
variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: python3.7
  environment:
    REGION: ${aws:region}
  lambdaHashingVersion: 20201221
  
custom:
# secure_string is a SecureString ssm param with custom kms_key
  test: ${ssm(raw):/secure_string}
```

### Command name and used flags

sls print

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.68.0 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
