### ISSUE TITLE
Error while deploying with custom jwt authorizer

### ISSUE THREAD

**Issue by RishivikramN** [serverless/serverless#10325]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have created a custom JWT authorizer and tried deploying. It is giving me the following error. The same serverless configuration was working two weeks ago. we tried downgrading the serverless version but still the same error.

```bash
ServerlessError: Function "customAuthorizer" doesn't exist in this Service
```

### Service configuration (serverless.yml) content

```yaml
# NOTE: update this with your service name
service: myservice

# Create an optimized package for our functions
package:
  individually: false

useDotenv: true

custom:
  myStage: ${opt:stage, self:provider.stage}
  bundle:
    disableForkTsChecker: true
    linting: false
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
    ignoreJWTSignature: true
    noAuth: true

plugins:
  - serverless-bundle # Package our functions with Webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: local
  region: us-east-1
  memorySize: 512
  timeout: 10
  lambdaHashingVersion: 20201221
  # These environment variables are made available to our functions
  # under process.env.
  environment:
    secretKey: ${env:AWS_SECRET_KEY}
    accessKey: ${env:AWS_ACCESS_KEY}
    tableName: ${env:PRIMARY_TABLE, '${opt:stage, 'local'}-tablename'}
    stageEnv: ${self:custom.myStage}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
          Resource: 'arn:aws:dynamodb:us-east-1:*:*'
        - Effect: Allow
          Action:
            - 'lambda:InvokeFunction'
          Resource:
            - '*'
  httpApi:
    cors: true
    disableDefaultEndpoint: true
    authorizers:
      customAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ''
            - - 'https://cognito-idp.'
              - '${opt:region, self:provider.region}'
              - '.amazonaws.com/'
              - 'userpool id' #userpool id
        audience:
          - 'appclient id'
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(src/resources/api-gateway-errors.yml)}
  - ${file(src/resources/primary-table.yml)}

functions:
  - ${file(src/resources/rest-api-resources.yml)}
  - ${file(src/resources/http-api-resources.yml)}
```

### Command name and used flags

sls deploy --stage dev

### Command output

```shell
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.67.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Starting type checking service...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Serverless: [AWS sts 200 3.556s 0 retries] getCallerIdentity({})
Serverless: Invoke webpack:package
Serverless: No external modules needed
Serverless: Copying existing artifacts...
Serverless: Packaging service...

 Serverless Error ----------------------------------------

  ServerlessError: Function "customAuthorizer" doesn't exist in this Service
      at Service.getFunction (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/classes/Service.js:318:11)
      at AwsCompileApigEvents.getAuthorizer (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:281:61)
      at /Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:54:36
      at Array.forEach (<anonymous>)
      at /Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:46:37
      at Array.forEach (<anonymous>)
      at AwsCompileApigEvents.validate (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:45:55)
      at package:compileEvents (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:320:31)
      at PluginManager.runHooks (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/classes/PluginManager.js:573:41)
      at async PluginManager.invoke (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/classes/PluginManager.js:611:9)
      at async PluginManager.spawn (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/classes/PluginManager.js:635:5)
      at async before:deploy:deploy (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/plugins/deploy.js:65:11)
      at async PluginManager.runHooks (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/classes/PluginManager.js:573:35)
      at async PluginManager.invoke (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/classes/PluginManager.js:610:9)
      at async PluginManager.run (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/classes/PluginManager.js:672:7)
      at async Serverless.run (/Users/rishi/Workduck/workduck-api/node_modules/serverless/lib/Serverless.js:468:5)
      at async /Users/rishi/Workduck/workduck-api/node_modules/serverless/scripts/serverless.js:832:9

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.22.7
     Framework Version:         2.67.0 (local)
     Plugin Version:            5.5.1
     SDK Version:               4.3.0
     Components Version:        3.18.1

Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Variable syntax error at "provider.environment.tableName": Invalid variable source at index 21 in "${env:PRIMARY_TABLE, '${opt:stage, 'local'}-tablename'}"
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.68.0 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
