### ISSUE TITLE
Enabling ReportBatchItemFailures on existing function 

### ISSUE THREAD

**Issue by zoellner** [serverless/serverless#10323]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Adding `functionResponseType: ReportBatchItemFailures` to an existing function with an existing sqs event hook does not update the configuration to actually enable `ReportBatchItemFailures`

### Service configuration (serverless.yml) content

```yaml
functions:
  JobQueueHandler:
    handler: index.handler
    events:
      - sqs:
          arn: !GetAtt JobQueue.Arn
          # functionResponseType: ReportBatchItemFailures # deploy without this first, then deploy with it
```

### Command name and used flags

sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.62.0 (local)
Plugin: 5.4.6
SDK: 4.3.0
Components: 3.17.1
```
