### ISSUE TITLE
Layers are packaged with absolute file paths in serverless-state.json

### ISSUE THREAD

**Issue by HaaLeo** [serverless/serverless#10326]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

# Description

When packaging a _layer_ serverless adds an **absolute path** to the `.serverless/serverless-state.json` file. For the lambda functions paths seem to be relative.
The absolute path in the `.serverless/serverless-state.json` causes trouble in CI/CD environments. 

## Steps to reproduce
1. We are bundeling everything in a first step (Absolute path is added to the file).  
1. Upload the `.serverless` directory temporary as build artifacts.
1. download the `.serverless` to our deployment environment and run the deployment with the command `npm run deploy -- --stage ${ENVIRONMENT} --package ${CODEBUILD_SRC_DIR_BuildArtifact}/.serverless/ --region ${REGION}`. 

When doing this now the generated absolute path of course is wrong since we deploy all of this from a completely different instance. 

## Expected Result 
when running `sls package` all path to zip archives should be relative including for layers

## Actual Result
when running `sls package` all layers' paths are absolute

## Example
A example for a generated `serverless-state.json` file
```json
{
....
    "layers": {
        "swagger": {
          "path": "swaggerLayer",
          "name": "dev-fastify-swagger",
          "description": "fastify-swagger@4.12.6",
          "compatibleRuntimes": {
            "$ref": "$[\"service\"][\"provider\"][\"compiledCloudFormationTemplate\"][\"Resources\"][\"SwaggerLambdaLayer\"][\"Properties\"][\"CompatibleRuntimes\"]"
          },
          "package": {
            "artifact": "/Users/myUser/some/folder/.serverless/swagger.zip"
          }
        }
      }
}     
```

## Workaround
Currently we fixed this by using `sed` to modify the file and replace the absolute path:
```
sed -i'' 's|"artifact"\: ".*\.serverless/swagger\.zip"|"artifact":"\.serverless/swagger\.zip"|g' .serverless/serverless-state.json
```

However, this obviously is a hacky workaround no sustainable solution to address this issue. 

### Service configuration (serverless.yml) content

```yaml
service: ${env:APP_ID} # This value is present in the CI/CD environment

useDotenv: true # See https://www.serverless.com/framework/docs/environment-variables/

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-reducer

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  deploymentBucket:
    name: ${env:S3_BUCKET} # This value is present in the CI/CD environment
  stackTags:
    AppId: ${env:APP_ID}
    Environment: ${self:provider.stage}
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
  iam:
    deploymentRole: ${env:CF_ROLE_ARN}
  lambdaHashingVersion: 20201221 # To prepare serverless v3.0 compatibility. https://serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - '*'

layers:
  swagger:
    path: swaggerLayer
    name: ${self:provider.stage}-fastify-swagger
    description: fastify-swagger@4.12.6
    compatibleRuntimes:
      - nodejs12.x
      - nodejs14.x

functions:
  main:
    handler: src/main.handler
    memorySize: 128
    timeout: 30
    layers:
      - !Ref SwaggerLambdaLayer

    events:
      - httpApi: # ApiGatewayV2
          method: any
          path: /{proxy+}

resources:
  - extensions:
      HttpApiStage:
        Properties:
          StageName: ${self:provider.stage} # Due to https://github.com/serverless/serverless/issues/8367

# Other serverless files which are not important for the bug
  - ${file(serverless/mappings.yml)}

  - ${file(serverless/database.yml)}

  - ${file(serverless/main-lambda-resources.yml)}
  - ${file(serverless/api-gateway-domain.yml)}
```

### Command name and used flags

npm run sls -- package

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.68.0 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
