### ISSUE TITLE
sign lambda

### ISSUE THREAD

**Issue by yaronbenezra** [serverless/serverless#10351]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi,
I am trying to sign lambda and when I add:
CodeSigningConfigArn:  !Ref CodeSigningConfig.CodeSigningConfigArn
it didn't create the CF template correctly, the attribute is not seen and at the end the lambda is not sign
can you help?

### Service configuration (serverless.yml) content

```yaml
sign_lambda:
    handler: lambdas.lambda_write_two_s3.lambda_write_two_s3_sign
    timeout: 900
    DependsOn:
      - CodeSigningConfig
    role: CreateAthenaExecutionRole
    CodeSigningConfigArn
    CodeSigningConfigArn: !Ref CodeSigningConfig
    logSubscription: false
    environment:
      PYTHONPATH: "lib"
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.67.0 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
