### ISSUE TITLE
 S3BucketPolicy - Invalid principal in policy error

### ISSUE THREAD

**Issue by tetiana-fomina-photobox** [serverless/serverless#10361]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello, I faced with the problem when I try to create s3 bucket with Principal property with IAM role arn(like this https://aws.amazon.com/premiumsupport/knowledge-center/s3-invalid-principal-in-policy-error/). 
Below you can see how I create my policy for bucket: 
```
const s3BucketPolicy: CloudFormationResource = {
  Type: 'AWS::S3::BucketPolicy',
  Properties: {
    PolicyDocument: {
      Statement: [
        {
          Sid: 'myPolicy',
          Effect: 'Allow',
          Action: ['s3:*'],
          Resource: { 'Fn::Join': ['', [{ 'Fn::GetAtt': [s3BucketResource.name, 'Arn'] }, '/*']] },
          Principal: {
            AWS: ['${self:custom.env.s3.myRole}'], // arn of needed role
          },
        },
      ],
    },
    Bucket: { Ref: myBucket.name },
  },
};
```
I have correct builded CloudFormation in my ``.serverless``  folder:
```
"S3BucketPolicy": {
      "Type": "AWS::S3::BucketPolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Sid": "myPolicy",
              "Effect": "Allow",
              "Action": [
                "s3:*"
              ],
              "Resource": {
                "Fn::Join": [
                  "",
                  [
                    {
                      "Fn::GetAtt": [
                        "S3Bucket",
                        "Arn"
                      ]
                    },
                    "/*"
                  ]
                ]
              },
              "Principal": {
                "AWS": [
                  arn:aws:iam::<accountId>:role/<roleName>
                ]
              }
            }
          ]
        },
        "Bucket": {
          "Ref": "S3Bucket"
        }
      }
    }
```

 But when I am deploying my code I get An error occurred: S3BucketPolicy - Invalid principal in policy (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID:....).
What may cause that ?

### Service configuration (serverless.yml) content

```yaml
const s3BucketPolicy: CloudFormationResource = {
  Type: 'AWS::S3::BucketPolicy',
  Properties: {
    PolicyDocument: {
      Statement: [
        {
          Sid: 'myPolicy',
          Effect: 'Allow',
          Action: ['s3:*'],
          Resource: { 'Fn::Join': ['', [{ 'Fn::GetAtt': [s3BucketResource.name, 'Arn'] }, '/*']] },
          Principal: {
            AWS: ['${self:custom.env.s3.myRole}'], // arn of needed role
          },
        },
      ],
    },
    Bucket: { Ref: myBucket.name },
  },
};
```

### Command name and used flags

sls deploy -v --stage <stage>

### Command output

```shell
An error occurred: S3BucketPolicy - Invalid principal in policy (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: ***; S3 Extended Request ID: ***; Proxy: null).
```

### Environment information

```shell
Framework Core: 2.69.0 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
