### ISSUE TITLE
Duplicate function names causes one of them to be ignored without warning

### ISSUE THREAD

**Issue by gilad-embryonics** [serverless/serverless#10410]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In my project I sometimes copy-paste function definitions and edit the necessary fields. Recently I created another function in this manner but forgot to change the function name (FuncA in the sample), and this resulted in the function simply being ignored. It took me quite a while to figure why this function was not being created as part of the stack while there were no errors or warnings of any kind to help me understand.

Sample yml snippet:

```
⋮
FuncA:
  handler: handler1
  events:
    - http:
        path: /path1
        method: get
⋮
FuncA:
  handler: handler2
  events:
    - http:
        path: /path2
        method: get
⋮
```

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  region: us-east-1
  environment:
    SLS_DEBUG: "*"

package:
  individually: false

functions:
  FuncA:
    handler: handler1
    events:
      - http:
          path: /path1
          method: get
  FuncA:
    handler: handler2
    events:
      - http:
          path: /path2
          method: get
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.69.1
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
