### ISSUE TITLE
Long httpApi paths invalid on AmazonApiGatewayV2

### ISSUE THREAD

**Issue by e10jc** [serverless/serverless#10423]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The name generated from my route looks like it exceeds 64 characters and is causing deploys to fail.

```
deleteEvent:
  handler: src/handler.deleteEvent
  events:
    - httpApi:
        path: /{exchangeUrlKey}/calendars/{calendarId}/events/{eventId}.json
        method: DELETE
```

> ServerlessError: An error occurred: HttpApiRouteDeleteExchangeurlkeyVarCalendarsCalendaridVarEventsEventidVarjson - One or more path parts appear to be invalid (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: b85f39be-87c1-4878-9b9b-b803a7560fa7; Proxy: null).

### Service configuration (serverless.yml) content

```yaml
frameworkVersion: '2 || 3'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x
  memorySize: 128
  timeout: 29
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage,'dev'}

functions:
  home:
    handler: src/handler.home
    events:
      - httpApi:
          path: /
          method: GET

  listCalendars:
    handler: src/handler.listCalendars
    events:
      - httpApi:
          path: /{exchangeUrlKey}/calendars.json
          method: GET

  listEvents:
    handler: src/handler.listEvents
    events:
      - httpApi:
          path: /{exchangeUrlKey}/calendars/{calendarId}/events.json
          method: GET

  createEvent:
    handler: src/handler.createEvent
    events:
      - httpApi:
          path: /{exchangeUrlKey}/calendars/{calendarId}/events.json
          method: POST

  showEvent:
    handler: src/handler.showEvent
    events:
      - httpApi:
          path: /{exchangeUrlKey}/calendars/{calendarId}/events/{eventId}.json
          method: GET

  updateEvent:
    handler: src/handler.updateEvent
    events:
      - httpApi:
          path: /{exchangeUrlKey}/calendars/{calendarId}/events/{eventId}.json
          method: PUT

  deleteEvent:
    handler: src/handler.deleteEvent
    events:
      - httpApi:
          path: /{exchangeUrlKey}/calendars/{calendarId}/events/{eventId}.json
          method: DELETE

plugins:
  - serverless-plugin-typescript
  - serverless-offline
```

### Command name and used flags

npx sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.69.1 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
