### ISSUE TITLE
Configuration warning at 'provider.layers': should be array

### ISSUE THREAD

**Issue by chuckthepiranha** [serverless/serverless#10450]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have deployed this on previous versions of serverless and it has worked but it is not working on the latest version. I am deploying an ffmpeg layer and I get the following warning:

`Configuration warning at 'provider.layers': should be array`

I change it to an array and then I get this warning:

`Configuration warning at 'provider.layers[0]': unsupported object format`

And then they both give me this error:

`The CloudFormation template is invalid: Unresolved resource dependencies [FfmpegLambdaLayer] in the Outputs block of the template`

### Service configuration (serverless.yml) content

```yaml
service: <service_name>
org: <org_name>
app: <app_name>

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-west-2
  layers:
    ffmpeg:
      path: layer
resources:
  Outputs:
    FfmpegLayerExport:
      Value:
        Ref: FfmpegLambdaLayer
      Export:
        Name: FfmpegLambdaLayer
```

### Command name and used flags

sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.70.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1
```
