### ISSUE TITLE
Documentation doesn't mention that there is a dev dependency on `ts-node` when using `serverless.ts` files in a npm/yarn project

### ISSUE THREAD

**Issue by Woodz** [serverless/serverless#10451]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When trying to deploy a `serverless.ts` file inside a yarn project, it fails with `Cannot parse "serverless.ts": Resolution of "ts-node" failed with: "ts-node" not found`. This can be resolved by adding a dev dependency on `ts-node`. I understand why `ts-node` is not listed as a peer dependency in the npm package of `serverless` (because it is only required when using .ts files) but it should at least be documented

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from '@serverless/typescript';

const serverlessConfiguration: AWS = {
  service: {
    name: 'foo',
  },
  functions: {
    bar: {
      handler: 'baz',
    },
  },
  provider: {
    name: 'aws',
  },
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

serverless deploy

### Command output

```shell
yarn deploy 
yarn run v1.22.17
warning package.json: No license field
$ serverless deploy
 
 Serverless Error ----------------------------------------
 
  Cannot parse "serverless.ts": Resolution of "ts-node" failed with: "ts-node" not found
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.18.2
     Framework Version:         2.70.0 (local)
     Plugin Version:            5.5.3
     SDK Version:               4.3.0
     Components Version:        3.18.1
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment information

```shell
Framework Core: 2.70.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1
```

### Package.json

```json
{
    "name": "serverless-repro",
    "scripts": {
        "deploy": "serverless deploy",
        "serverless-version": "serverless --version"
    },
    "dependencies": {},
    "devDependencies": {
        "@serverless/typescript": "^2.70.0",
        "@types/node": "^17.0.8",
        "serverless": "^2.70.0",
        "typescript": "^4.5.4"
    }
}

```
