### ISSUE TITLE
VPC configuration for the Lambda automatically created when using existing buckets on S3 Lambda events

### ISSUE THREAD

**Issue by damianoc-linear** [serverless/serverless#10459]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

In this page of the documentation https://www.serverless.com/framework/docs/providers/aws/events/s3/#using-existing-buckets it says that: "Using the existing config will add an additional Lambda function and IAM Role to your stack. The Lambda function backs-up the Custom S3 Resource which is used to support existing S3 buckets."

In normal lambdas defined with the serverless syntax I do this:

```yaml
lambdaName:
  [...]
  vpc:
    securityGroupIds:
      - sg-01234567890abcd
    subnetIds:
      - subnet-01234567890abcd
      - subnet-01234567890abcd
      - subnet-01234567890abcd
```

I found no way to configure this lambda (that is automatically created) in order to connect it to a VPC. The project I'm working on requires that every lambda is created inside a VPC.

### Proposed solution (optional)

Maybe something like this:

```yaml
lambdaName:
  handler: src/lambda_name.handler
  events:
    - s3:
      bucket: bucket-name
      event: s3:ObjectCreated:*
      existing: true
      customResourceExistingS3LambdaConfiguration:
        vpc:
          securityGroupIds:
            - sg-01234567890abcd
          subnetIds:
            - subnet-01234567890abcd
            - subnet-01234567890abcd
            - subnet-01234567890abcd
```

**Comment by ROSeaboyer** [comment]
A possible workaround is adding this to the resources section of your serverless file to let serverless's resource merging logic add it in:
```yaml
    CustomDashresourceDashexistingDashs3LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        VpcConfig:
          SecurityGroupIds:
            - <id>
          SubnetIds:
            - <id>
```
