### ISSUE TITLE
Null stage parameter is not recognized

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#10492]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

With the config below, `serverless info --stage=dev` fails but `serverless info --stage=prod` works.

Here is the error:

> Invalid variable reference syntax for variable param:a. You can only reference env vars, options, & files. You can check our docs for more info.

I'm guessing that because the parameter is empty (null), it is recognized as non-existent. Instead it should be recognized, and the value should be "null"?

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  environment:
    A: ${param:a}

params:
  dev:
    a:
  prod:
    a: abc
```
```


### Command name and used flags

serverless info --stage=dev

### Command output

```shell
Invalid variable reference syntax for variable param:a. You can only reference env vars, options, & files. You can check our docs for more info.
```
```


### Environment information

```shell
v3 beta
```

**Comment by mnapoli** [comment]
Additional info:

- Doesn't work

```yaml
params:
  dev:
    a: ~
```

- Works (I'll use that as a workaround):

```yaml
params:
  dev:
    a: ''
```

**Comment by medikoo** [comment]
@mnapoli in variables resolver, by design, if you want to treat given value as optional, you need to explicitly state that via `null` fallback. e.g. `${param:optional, null}`

It's because in most cases variables from sources are expected to be resolved unconditionally, and if there's no value at the source, it is expected that the variable resolver will report that with an error (e.g. missing file, missing ssm parameter, missing cf output etc).

**Comment by medikoo** [comment]
To give a bit more insight, in this case: the variable `param` source resolver, reads the `null` value from your configuration, and returns it as resolved value to generic variable resolution logic (which from that point is common for resolution from any source). Here `null` is treated as: _no value found for given variable instruction_. In such a case resolver either applies a fallback if it's provided, or throws an error that value is missing.

So technically whether you configure param with `null` or do not configure it all, it'll make no difference. In both cases information is that there's _no value_ for given param.

**Comment by mnapoli** [comment]
Right, but here the parameter is defined explicitly to null. It's different from it not being configured.

Basically I'm trying to set a parameter to an empty value (null).

**Comment by medikoo** [comment]
Yes, as mentioned, assuming `null` is a desired value unconditionally, will be harmful for many other scenarios. e.g. see another example:

```yaml
params:
  prod:
    a: ${env.A, null} # If env.A is not provided, fallback to resolution from dashboard
```

---

And in your specific use case, solution is quite simple. Express explicitly that environment variable `A` is provided to lambda conditionally:

```yaml
provider:
  name: aws
  environment:
    A: ${param:a, null}

params:
  prod:
    a: abc
```

In my eyes, from such config, you can even read the intention easier.

**Comment by mnapoli** [comment]
Note: I haven't forgotten about this, just thinking.

Is this behavior (null == the property is considered as not provided) applied for all variable sources? Or is this specific to `param`?

**Comment by medikoo** [comment]
> Is this behavior (null == the property is considered as not provided) applied for all variable sources? Or is this specific to param?

In JavaScript `null` means lack of value (no value). Variables resolver, receiving `null` (from any source), treats it as information that _there's no requested value at the source_. This results with an error, unless user explicitly states that it's ok if given property ends as empty (as if it was not configured in the config)

**Comment by medikoo** [comment]
Additional notes which may help to further clarify:

When processing Serverless configuration, in all cases properties set to `null` are treated as if they're not set at all, there are no exceptions.

CloudFormation rejects any `null` values in templates (on their side, _lack of value_ can only be expressed by not setting property at all, there is no support `null` JSON values - we automatically clear all `null` properties in generated CF template out of our config)

In any program written in JavaScript, `null` is an additional option, when _generating_ input (to shadow/replace _value_ with _no value_). but when _processing_ generated input all three variants (1) lack of property, (2) property set to `undefined` or  (3) set to `null` explicitly, ideally if are treated the same way. Lack of value is lack of value.

**Comment by mishabruml** [comment]
Hey, I am also running into this issue. My use case is conditonally deploying lambdas into vpc. By deafult, I need to deploy the VPC configuration, but when deploying to stage 'dev' (localstack) I need to set the vpc to `vpc:~` to inhibit the config as per https://www.serverless.com/framework/docs/providers/aws/guide/functions#vpc-configuration

```yml
service: my-service
frameworkVersion: '3'

params:
  default:
    env: uat
    vpc:
      securityGroupIds:
        - !Ref LambdaSecurityGroup
      subnetIds:
        - subnet-XXXXX
        - subnet-XXXXX
        - subnet-XXXXX
        - 
  dev:
    env: dev
    vpc: ~

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  vpc: ${param:vpc}
```

The result for deploying to dev stage e.g. `npx sls deploy -s dev` is that the `default` vpc configuration is used, which is undesired.

Any recommendations for a workaround to this?

**Comment by mishabruml** [comment]
This is what I've done in the end. Annoying, because I'll have to define a `custom.vpcConfig` entry for every defined `stage` 

```yaml
provider:
  name: aws
  vpc: ${self:custom.vpcConfig.${sls:stage}, null}

custom:
  vpcConfig:
    uat:
      securityGroupIds:
        - !Ref LambdaSecurityGroup
      subnetIds:
        - subnet-XXXXX
        - subnet-XXXXX
```
