### ISSUE TITLE
Reference.json schema no longer allows  resource Type AWS::WAFv2::WebACLAssociation

### ISSUE THREAD

**Issue by tony-maynard** [serverless/serverless#10538]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [x] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Upgrade dependencies, previously this code block used to work:
```
resources:
  Resources:
    ApiStageWeb2ACLAssociation:
      Type: "AWS::WAFv2::WebACLAssociation"
      Properties:
        ResourceArn:
          {
            "Fn::Join":
              [
                "",
                [
                  "arn:#{AWS::Partition}:apigateway:#{AWS::Region}::/restapis/",
                  { "Ref": "ApiGatewayRestApi" },
                  "/stages/${self:provider.stage}",
                ],
              ],
          }
        WebACLArn: ${ssm:/waf/waf}
      DependsOn:
        - ApiGatewayDeployment${sls:instanceId}
```
Now I get various validation errors stated below:
```
Value is not accepted. Valid values: "AWS::CloudFront::Distribution".yaml-schema: Serverless Framework Configuration(1)
Serverless Framework Configuration
Type of resource equals only AWS::CloudFront::Distribution

Source: reference.json
---
Property ResourceArn is not allowed.yaml-schema: Serverless Framework Configuration
---
Property WebACLArn is not allowed.yaml-schema: Serverless Framework Configuration
```

### Service configuration (serverless.yml) content

```yaml
service: data-showroom-api
configValidationMode: warn

useDotenv: true
variablesResolutionMode: 20210326

package:
  individually: true
  excludeDevDependencies: false # use serverless-plugin-include-dependencies instead
  exclude:
    - .serverless/**
    - package_output/**
    - tmp/**
    - node_modules/**

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: ${opt:stage, 'v1'}
  apiGateway:
    binaryMediaTypes:
      - "application/octet-stream"
  vpcEndpointIds:
    - ${ssm:/lambda/vpc/endpoint/execute-api}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:#{AWS::AccountId}:table/xTable"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:#{AWS::AccountId}:table/xTable"
    - Effect: Allow
      Action:
        - "eks:DescribeCluster"
      Resource: "*"
  vpc:
    securityGroupIds:
      - ${ssm:/lambda/sg/default}
    subnetIds:
      - ${ssm:/lambda/vpc/private_subnets}
  logRetentionInDays: ${self:custom.logRetentionInDays}
  logs:
    restApi:
      level: INFO
  deploymentBucket:
    name: ${ssm:/lambda/bucket/name}
  tracing:
    apiGateway: true
    lambda: true

custom:
  prefix: ${self:provider.stage}-${self:service}
  logRetentionInDays: 90
  dynamodb:
    stages: ${opt:stage, 'v1'}
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      x:
        sources:
          - table: tenantTable
            sources: [./sample-data/x.json]
  serverless-offline:
    httpPort: 5001
  domainName:
    dev: xxx
    prod: yyy
  customDomain:
    domainName: ${self:custom.domainName.${self:provider.stage}}
    basePath: ${self:provider.stage}
    stage: v1

plugins:
  - serverless-latest-layer-version
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-step-functions
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager

resources:
  Resources:
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ApiGateway

    ApiStageWeb2ACLAssociation:
      Type: "AWS::WAFv2::WebACLAssociation"
      Properties:
        ResourceArn:
          {
            "Fn::Join":
              [
                "",
                [
                  "arn:#{AWS::Partition}:apigateway:#{AWS::Region}::/restapis/",
                  { "Ref": "ApiGatewayRestApi" },
                  "/stages/${self:provider.stage}",
                ],
              ],
          }
        WebACLArn: ${ssm:/waf/xxx}
      DependsOn:
        - ApiGatewayDeployment${sls:instanceId}
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Previous serverless config: 

Framework Core: 2.52.1 (local)
Plugin: 5.4.3
SDK: 4.2.5
Components: 3.14.0
```

After Upgrade:
```
Framework Core: 2.72.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.2
```
```
