### ISSUE TITLE
Warning when specifying EventBus ARN in EventBridge events of a Lambda

### ISSUE THREAD

**Issue by MaximeVivier** [serverless/serverless#10552]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi,

Recently I had an issue deploying a lambda triggered by an EventBridge event.
I specified the ARN of the bus in the following property : `events: { eventBridge: { eventBus: { Get:Att: [<myBusLogicalId>, 'Arn'] } }`.
When I deployed my stack, I got a warning from serverless framework saying `Configuration warning at 'functions.<myFunctionName>.events[0].eventBridge.eventBus['Fn::GetAtt'][1]': should be equal to one of the allowed values [Name]`. Event with this warning message telling me to choose the Name over the Arn of the bus, I was able to deploy successfully.

However, as discussed in #9118, specifying the ARN instead of the name will prevent correct permission creation for the Lambda, resulting in faulty eventbridge invocation of the service. The warning displayed above should therefore fail the deployment rather than relying only on a warning. WDYT ?

I already prepared a PR to suggest another way to generate the faulty AWS::Lambda::Permission even with bus ARN supplied. 

### Service configuration (serverless.yml) content

```yaml
service: test
provider:
  name: aws
  runtime: nodejs14.x
  eventBridge:
    useCloudformation: true
functions:
  myFunction:
    handler: src/handler.main
    events:
      - eventBridge:
          eventBus:
            Fn::GetAtt:
              - MyBus
              - Arn
resources:
  Resources:
    MyBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: myBusName
```

### Command name and used flags

serverless deploy --aws-profile ****** --stage staging

### Command output

```shell
Configuration warning at 'functions.updateHubspotWithApnId.events[0].eventBridge.eventBus['Fn::GetAtt'][1]': should be equal to one of the allowed values [Name]
```

### Environment information

```shell
Framework Core: 2.69.1 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
