### ISSUE TITLE
cant exclude node_modules

### ISSUE THREAD

**Issue by bitsofinfo** [serverless/serverless#10567]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

My serverless.yml has:
```
package:
  exclude:
    - node_modules/**
  include:
    - utils
    - validation
    - '*.js'
...

layers:
  nodeModules:
    name: ${self:service.name}-${opt:stage,'dev'}-nodeModules
    package:
      include:
        - ./**
    path: lambda_layers
    compatibleRuntimes:
      - nodejs14.x
```

Despite this, no matter what combination of `patterns` or `includes` or `excludes` the build zip for the service ALWAYS has `node_modules` within in.... (note the layer zip is correctly built and seems fine)...

### Service configuration (serverless.yml) content

```yaml
package:
  exclude:
    - node_modules/**
  include:
    - utils
    - validation
    - '*.js'
...

layers:
  nodeModules:
    name: ${self:service.name}-${opt:stage,'dev'}-nodeModules
    package:
      include:
        - ./**
    path: lambda_layers
    compatibleRuntimes:
      - nodejs14.x
```
```


### Command name and used flags

serverless package

### Command output

```shell
n/a
```

### Environment information

```shell
Framework Core: 2.70.0 (local)
Plugin: 5.5.2
SDK: 4.3.0
Components: 3.18.1
```
