### ISSUE TITLE
AWS: httpApi (apigwv2) to support custom domains "natively"

### ISSUE THREAD

**Issue by omerinvia** [serverless/serverless#10564]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

the idea is to add some sort of `customDomains` attribute to the `provider.httpApi` and it will create the extra resources that needed in order to define the custom domains
I think that we can "Skip" the certification part so the user will provide
```fullpath, hostedZoneName, sslCertificationArn` and we will create the ApiMapping & Domain & RecordSet.
we can handle it in the same way we are handling authorizer..  

### Proposed solution (optional)

the idea is the use the `provider.httpApi` object and add `customDomains` object
the object will look like
```yaml
domainName:
    path: "myapi.serverless.com"
    hostedZoneName: "serverless.com"
    sslCertificateArn: "ssl....."
otherDomainName:
    ....

```
under the hood we will create the 3 extra resources and it will give a better httpApi usage experience (IMO :D )
I created a draft for this proposal
