### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined at new ServerlessPlugin

### ISSUE THREAD

**Issue by wocodes** [serverless/serverless#10588]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I encountered this error below during a bitbucket-pipelines build process some hours after the latest update to v3.0.0 and I also followed the guide found [here](https://www.serverless.com/framework/docs/providers/aws/cli-reference/deploy)

```
serverless deploy --stage ${SERVERLESS_STAGE}
Environment: linux, node 14.17.5, framework 3.0.0, plugin 6.0.0, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
TypeError: Cannot read property 'bind' of undefined
    at new ServerlessPlugin (/opt/atlassian/pipelines/agent/build/vendor/bref/bref/index.js:56:33)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:88:28)
    at /usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:33
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:8)
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/serverless.js:137:30)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:529:7
```

Here is the section of my bitbucket-pipeline.yml file which reproduces the error

```
    - step: &deploy_to_lambda
        name: Deploy Lambda
        image: node:14.17.5
        caches:
            - node
        deployment: Test Lambda
        trigger: automatic

        script:
            - npm install -g serverless
            - apt-get update && apt-get install -y gettext-base
            - envsubst < .env.pipelines.deploy > .env
            - serverless config credentials --provider aws --key ${AWS_LAMBDA_KEY} --secret ${AWS_LAMBDA_SECRET}
            - serverless deploy --stage ${SERVERLESS_STAGE}

```

### Service configuration (serverless.yml) content

```yaml
service: ****************

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-2
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: ${opt:stage, 'dev'}
    runtime: provided.al2
    versionFunctions: false
    environment:
      APP_ENV: ${self:provider.stage}
      SQS_QUEUE:
        Ref: DefaultQueue
      SQS_HEAVY_DUTY_QUEUE:
        Ref: HeavyDutyQueue
    iamRoleStatements:
      - Effect: Allow
        Action: [sqs:SendMessage, sqs:DeleteMessage]
        Resource:
          - Fn::GetAtt: [DefaultQueue, Arn]
          - Fn::GetAtt: [MailQueue, Arn]
          - Fn::GetAtt: [HeavyDutyQueue, Arn]
          - Fn::GetAtt: [SingleJobQueue, Arn]
```

### Command name and used flags

serverless deploy --stage ${SERVERLESS_STAGE}

### Command output

```shell
+ serverless deploy --stage ${SERVERLESS_STAGE}
Environment: linux, node 14.17.5, framework 3.0.0, plugin 6.0.0, SDK 4.3.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
TypeError: Cannot read property 'bind' of undefined
    at new ServerlessPlugin (/opt/atlassian/pipelines/agent/build/vendor/bref/bref/index.js:56:33)
    at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:88:28)
    at /usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:33
    at Array.forEach (<anonymous>)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:135:8)
    at Serverless.init (/usr/local/lib/node_modules/serverless/lib/serverless.js:137:30)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:529:7
```

### Environment information

```shell
linux, node 14.17.5, framework 3.0.0, plugin 6.0.0, SDK 4.3.0
```
