### ISSUE TITLE
"errorMessage": "Unable to determine event source based on event."

### ISSUE THREAD

**Issue by Mhm0ud** [serverless/serverless#10604]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a test graphql simple app with one file index.js
```
const { ApolloServer, gql } = require('apollo-server-lambda');
const { ApolloServerPluginLandingPageGraphQLPlayground } = require('apollo-server-core');

// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,

  introspection: true,
  plugins: [ApolloServerPluginLandingPageGraphQLPlayground()],
});

exports.handler = server.createHandler();
```

Package.json :

```
{
  "name": "federation-gateway2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-server-lambda": "^3.6.2",
    "graphql": "^16.3.0"
  }
}
```
when I try to run this command `serverless invoke local --function graphql` it throws an error as below.

I created this simple app because I have another application face this issue but I want to make sure that the issue not from the application,

The project structure is the following:
![image](https://user-images.githubusercontent.com/16934190/151807945-688d0919-0e9b-49d8-8e55-aa5ab788daba.png)

### Service configuration (serverless.yml) content

```yaml
# serverless.yml

service: apollo-lambda
provider:
  name: aws
  runtime: nodejs14.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: index.handler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
```

### Command name and used flags

serverless invoke local --function graphql

### Command output

```shell
{
    "errorMessage": "Unable to determine event source based on event.",
    "errorType": "Error",
    "stackTrace": [
        "Error: Unable to determine event source based on event.",
        "    at getEventSourceNameBasedOnEvent (C:\\Users\\MHMAl\\Documents\\GitHub\\federation-gateway2\\node_modules\\@vendia\\serverless-express\\src\\event-sources\\utils.js:88:9)",
        "    at proxy (C:\\Users\\MHMAl\\Documents\\GitHub\\federation-gateway2\\node_modules\\@vendia\\serverless-express\\src\\configure.js:38:51)",
        "    at handler (C:\\Users\\MHMAl\\Documents\\GitHub\\federation-gateway2\\node_modules\\@vendia\\serverless-express\\src\\configure.js:99:12)",
        "    at C:\\Users\\MHMAl\\Documents\\GitHub\\federation-gateway2\\node_modules\\apollo-server-lambda\\dist\\ApolloServer.js:51:27"
    ]
}
```

### Environment information

```shell
Framework Core: 3.0.1
Plugin: 6.0.0
SDK: 4.3.0
```
