### ISSUE TITLE
stackPolicy not working in serverless v3

### ISSUE THREAD

**Issue by jamesgibbons92** [serverless/serverless#10606]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When setting stackPolicy in the provider, serverless deploy fails with cloud formation error when creating the change set:
`Unexpected key 'StackPolicyBody' found in params`

### Service configuration (serverless.yml) content

```yaml
# serverless.yml

service: stack-policy

provider:
  name: aws
  stage: dev # Set the default stage used. Default is dev
  region: us-east-1 # Overwrite the default region used. Default is us-east-1
  stackPolicy: # Optional CF stack policy. The example below allows updates to all resources except deleting/replacing EC2 instances (use with caution!)
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
    - Effect: Deny
      Principal: "*"
      Action:
        - Update:Replace
        - Update:Delete
      Resource: "*"
      Condition:
        StringEquals:
          ResourceType:
            - AWS::EC2::Instance
```

### Command name and used flags

sls deploy

### Command output

```shell
$ sls deploy 

Deploying stack-policy to stage dev (us-east-1)

× Stack stack-policy-dev failed to deploy (0s)
Environment: win32, node 14.17.3, framework 3.0.1, plugin 6.0.0, SDK 4.3.0
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Unexpected key 'StackPolicyBody' found in params
```

### Environment information

```shell
Framework Core: 3.0.1
Plugin: 6.0.0
SDK: 4.3.0
```
