### ISSUE TITLE
v3: An operation on this ChangeSet is currently in progress. (with serverless-esbuild)

### ISSUE THREAD

**Issue by smirowstanitzok** [serverless/serverless#10600]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

On a serverless deploy action with the newest v3.0.1 version I receive the error `An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.`. serverless seems to create multiple changesets with the same name in cloudformation. This happens in every service I've developed. An exception is a service that uses the `serverless-webpack` plugin instead of the `serverless-esbuild` plugin. If you think the plugin could be the cause, then feel free to close the issue. The setup works fine with serverless v2.72.0.

### Service configuration (serverless.yml) content

```yaml
service: safetyop-messaging

plugins:
  - serverless-plugin-epsagon
  - serverless-esbuild
  - serverless-offline

configValidationMode: error

custom:
  noTracing:
    test: false
    prod: false
    default: true
  epsagon:
    token: 'a30ac0a8-301a-446e-a14c-7a1b5b4d389a'
    appName: 'safetyop-${self:provider.stage}'
    disable: ${self:custom.noTracing.${self:provider.stage}, self:custom.noTracing.default}
  esbuild:
    bundle: true
  LogRetention:
    stage-cicd: 1
    stage-dev: 1
    stage-pet: 1
    stage-prod: 7
    stage-test: 7

provider:
  name: aws
  deploymentBucket:
    name: devtoday-serverless-deploys
  stackName: safetyop-messaging-${self:provider.stage}
  runtime: nodejs14.x
  architecture: 'arm64'
  versionFunctions: false
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: ${self:custom.LogRetention.stage-${self:provider.stage}}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: '*'
  tags:
    APPLICATION: safetyop
    SERVICE: safetyop-messaging
    STAGE: ${self:provider.stage}

  environment:
    APPLICATION: safetyop
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    STAGE: ${self:provider.stage}

functions:
  CognitoCustomMessageHandler:
    handler: src/handler.CognitoCustomMessageHandler
  QueueProcessor:
    handler: src/handler.QueueProcessorHandler
    reservedConcurrency: 20
    timeout: 300
    events:
      - sqs:
          arn: !GetAtt Queue.Arn
          batchSize: 1

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: so-messaging-${self:provider.stage}
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
          maxReceiveCount: 3
        VisibilityTimeout: 360
        DelaySeconds: 60

    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: so-messaging-${self:provider.stage}-DLQ
    TopicToQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'allow-sns-messages'
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt Queue.Arn
              Action: 'SQS:SendMessage'
              Condition:
                ArnEquals:
                  'aws:SourceArn': ${cf:safetyop-backend-${self:provider.stage}.EventTopic}
        Queues:
          - Ref: Queue
    TopicToQueueSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: ${cf:safetyop-backend-${self:provider.stage}.EventTopic}
        Endpoint: !GetAtt Queue.Arn
        Protocol: sqs
        RawMessageDelivery: 'true'
```

### Command name and used flags

npx sls deploy --stage cicd --verbose

### Command output

```shell
Deploying safetyop-messaging to stage cicd (eu-central-1)

Packaging
[serverless-plugin-epsagon] Epsagon disabled - not wrapping functions
Compiling to node14 bundle with esbuild...
Compiling with concurrency: Infinity
Compiling completed.
(node:6911) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Zip service safetyop-messaging - 11.26 KB [41 ms]
[serverless-plugin-epsagon] Cleaning up Epsagon's handlers
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading service safetyop-messaging.zip file to S3 (11.53 kB)
Updating CloudFormation stack

✖ Stack safetyop-messaging-cicd failed to deploy (2s)
Environment: darwin, node 17.2.0, framework 3.0.1 (local), plugin 6.0.0, SDK 4.3.0
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
An operation on this ChangeSet is currently in progress.  Please attempt this operation again later.
```

### Environment information

```shell
Framework Core: 3.0.1 (local)
Plugin: 6.0.0
SDK: 4.3.0
```
