### ISSUE TITLE
excludeDevDependencies is not working when package points to parent directory

### ISSUE THREAD

**Issue by vssenko** [serverless/serverless#10609]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless version: ^2.71.0

I decided to move my serverless.yml files into separated folder, and inside it point to the root folder:
```
|*root*
|-/infrastructure
|---serverless.yml
|-/src
|----*all code*
```

I can point serverless to include code from parent dir by using either `include` or `pattern` options in `package` section.
However, in this case all node_modules gets included, even dev deps, even if you provide `excludeDevDependencies: true` in package section.

So I can either include **all** dependencies, or exclude entire **node_modules**, nothing more (obviously, I can manually exclude some node modules, but this would be hell).

### Service configuration (serverless.yml) content

```yaml
service: service-name
package:
  individually: true
  excludeDevDependencies: true
  include:
    - "../../../**/*"
  exclude:
    - "../../../tests/**"
    - "../../../infrastructure/**"

functions:
  processUpdate:
    name: function-name
    handler: ./src/lambdas/processUpdate.handler
```

### Command name and used flags

serverless deploy

### Command output

```shell
Output is normal deployment output, with huge s3 .zip file.

Also, i'm on Windows 10, and inclusion of all node_modules sometimes fails into "EMFILE: too many open files"
```

### Environment information

```shell
Framework Core: 2.71.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1
```

**Comment by pgrzesik** [comment]
Hello @vssenko - thanks a lot for reporting. At the moment, exclusion of dependencies is always run against the `node_modules` placed in service directory, which in your case would be inside the `infrastructure` folder. I will bring this topic up during the internal meeting and will report back.

**Comment by medikoo** [comment]
This is a tricky one.

Technically by how currently Framework works, packaging _base_ directory naturally is expected to be a _service_ directory (which is a directory in which service configuration is placed) and `excludeDevDependencies` are hardcoded to filter `node_modules` against _service_ directory.

I was quite surprised to find that including `../` pattern will change the base path for packaging (it appears it's how `globby` behaves which we use underneath). I see this as a design bug, as it affects how other paths should be written  (e.g. suddenly lambda handlers have also to be updated to be configured against the different _base_ directory, and not against _service_ directory in which service configuration is placed).

I've once wrote a proposal, where `basePath` could be set explicitly, without side effects (in https://github.com/serverless/serverless/issues/9095) so it's not that surprising

-- 

Anyway putting aside above, in this specific case, I think you should be able to achieve what you want via:

```yaml

service: service-name
package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "../../../**/*"
    - "../../../tests/**"
    - "../../../infrastructure/**"
    - "!../../../node_modules/**"
 ```

(note that `includes` and `excludes` are deprecated and `patterns` should be used instead)
