### ISSUE TITLE
 unrecognized property for anchor in serverless.yml

### ISSUE THREAD

**Issue by hex0cter** [serverless/serverless#10635]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When using achors in serverless.yaml, it complains about 
```
Warning: Invalid configuration encountered
  at root: unrecognized property 'achorname'
```

### Service configuration (serverless.yml) content

```yaml
service: my-status-monitor

liveMonitor: &liveMonitor
  handler: api/liveMonitor.handler
  runtime: nodejs14.x
  events:
    - schedule: rate(1 minute)

provider:
  lambdaHashingVersion: 20201221
  name: aws
  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 5
  iamRoleStatements:
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-${opt:stage, self:provider.stage}-my-system-status
  environment:
    SERVICE_NAME: ${self:service}
    STAGE: ${opt:stage, self:provider.stage}

functions:
  trigger:
    handler: api/trigger.handler
    runtime: nodejs14.x
    name: ${self:service}-${opt:stage, self:provider.stage}-trigger
    events:
      - schedule: rate(1 minute)
  mock:
    handler: api/mock.handler
    runtime: nodejs14.x
    name: ${self:service}-${opt:stage, self:provider.stage}-mock
    events:
      - http:
          path: /api/v2/monitor/status
          method: get
          cors: true
  stagingMonitor:
    name: ${self:service}-${opt:stage, self:provider.stage}-stagingMonitor
    environment:
      HOST: https://staging.example.com
    <<: *liveMonitor
  devMonitor:
    name: ${self:service}-${opt:stage, self:provider.stage}-devMonitor
    environment:
      HOST: https://dev.example.com
    <<: *liveMonitor

resources:
  Resources:
    categoryListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage, self:provider.stage}-my-system-status
        AttributeDefinitions:
          - AttributeName: sut
            AttributeType: S
        KeySchema:
          - AttributeName: sut
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```

### Command name and used flags

serverless deploy --stage dev

### Command output

```shell
> my-status-monitor@1.0.0 deploy
> serverless deploy --stage dev


Warning: Invalid configuration encountered
  at root: unrecognized property 'liveMonitor'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
> serverless --version

Framework Core: 3.1.1 (local)
Plugin: 6.0.0
SDK: 4.3.1
```
