### ISSUE TITLE
Support uploading substack yaml files

### ISSUE THREAD

**Issue by nponeccop** [serverless/serverless#10656]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

It is pretty common to have multi-stack deployments, e.g. by putting DynamoDB tables or API Gateway in a separate CloudFormation stack.

These extra stacks are mostly pure CloudFormation stacks, without much Serverless-specific machinery.

Currently the only reasonable approach is to deploy multiple CloudFormation services. 

### Proposed solution (optional)

It's possible to create `AWS::CloudFormation::Stack` resources in the `resources` section already. However, the resource requires a [TemplateURL](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-templateurl) property which requires manual uploading.

I suggest something like 

```yaml
resources:
  Resources:
    subStack1:
      Type: AWS::CloudFormation::Stack
      Properties:
         TemplateURL: $(uploadToDeploymentBucket foo.yaml)
```
