### ISSUE TITLE
ssm keys doesnt work with variables - ValidationException: Parameter name: can't be prefixed with "ssm"

### ISSUE THREAD

**Issue by guyschlider** [serverless/serverless#10671]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When trying to use [variables](https://www.serverless.com/framework/docs/providers/aws/guide/variables) its looks like you can't use any variables

```
SubnetIds: ${ssm:/SLS/myapp-${opt:stage}/DBSubnets}
``
will result in
```
  - Cannot resolve variable at "resources.2.Resources.ElasticsearchDomain.Properties.VPCOptions.SubnetIds": Value not found at "ssm" source
 ```

and 
```
custom:
 stage: ${opt:stage}
...
SubnetIds: ${ssm:/SLS/myapp-${self:custom.stage}/DBSubnets}
```
result with the same error.



### Service configuration (serverless.yml) content

```yaml
service: myservice
variablesResolutionMode: 20210326
custom:
    # Get stage from command line (serverless --stage local|staging|prod)
    stage: ${opt:stage}


provider:
    name: aws
    lambdaHashingVersion: 20201221
    runtime: nodejs14.x
    memorySize: 256
    stage: ${self:custom.stage}
    region: us-east-1

resources:
  Resources:
    ElasticsearchDomain:
      Type: AWS::OpenSearchService::Domain
      Properties:
        DomainName: tasks-${self:custom.stage}
        EngineVersion: 'OpenSearch_1.0'
        ClusterConfig:
          # DedicatedMasterEnabled: true
          InstanceCount: '1'
          # ZoneAwarenessEnabled: true
          InstanceType: 't3.small.search'
          # DedicatedMasterType: 't3.small.elasticsearch'
          # DedicatedMasterCount: '1'
        EBSOptions:
          EBSEnabled: true
          VolumeSize: '16'
          VolumeType: 'gp2'
        AdvancedOptions:
          rest.action.multi.allow_explicit_index: true
        VPCOptions:
          #SecurityGroupIds: ${ssm:/SLS/${AWS::StackName}/AppSecurityGroup}
          SubnetIds: ${ssm:/SLS/myapp-${self:custom.stage}/DBSubnets}
```

### Command name and used flags

SLS_DEBUG=* npx sls package -s dev

### Command output

```shell
Environment: darwin, node 15.14.0, framework 3.1.1 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "resources.Resources.ElasticsearchDomain.Properties.VPCOptions.SubnetIds": Value not found at "ssm" source
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 3.1.1 (local)
Plugin: 6.0.0
SDK: 4.3.1
```

**Comment by pgrzesik** [comment]
Hello @guyschlider - it suggests that it cannot find the value at provided path in ssm. Are you sure that there's a value under the path that you're configuring?

**Comment by silva95gustavo** [comment]
Similar issue. Started today despite no code changes. We are fetching a credential from SSM and storing it in a variable in the `custom` section of our `serverless.yml`:
```
custom:
  secrets:
    database: ${ssm:/aws/reference/secretsmanager/my/path/to/database~true}
```

 But in our case this is the error:

>  Serverless Warning --------------------------------------
 A valid SSM parameter to satisfy the declaration 'ssm:/aws/reference/secretsmanager/my/path/to/database~true' could not be found.

Issue remains with or without the `~true` suffix. The value exists in SSM and I'm confident there were no changes in regards to user permissions in AWS.


Tested in these envs:

> Node: v14.19.0
Framework Core: 2.72.2
Plugin: 5.5.4
SDK: 4.3.0
Components: 3.18.2

>Framework Core: 2.69.1 (standalone)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1

**Comment by NeilJ247** [comment]
@pgrzesik I am seeing something similar.  

To give you background: we have a staging and production environments which are hosted on different AWS accounts.  When deploying we set the AWS secrets in the env and run `sls deploy --stage` with the relevant stage e.g. stage or production.

When I am running this for staging serverless is trying look up variables for production which makes no sense.   Example:

```
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'stage'}
  lambdaHashingVersion: 20201221

  environment:
    DB_HOST: ${self:custom.DB_HOST.${opt:stage}}
    DB_USERNAME: ${self:custom.DB_USERNAME.${opt:stage}}
    DB_PASSWORD: ${self:custom.DB_PASSWORD.${opt:stage}}
    DB_NAME: ${self:custom.DB_NAME.${opt:stage}}
    NODE_ENV: ${self:custom.NODE_ENV.${opt:stage}}

custom:
  DB_HOST:
    stage: ${ssm:/Staging/Service/DB_HOST}
    production: ${ssm:/Production/Service/DB_HOST}
  DB_NAME:
    stage: ${ssm(raw):/Staging/Service/DB_NAME}
    production: ${ssm(raw):/Production/Service/DB_NAME}
  DB_USERNAME:
    stage: ${ssm(raw):/Staging/Service/DB_USERNAME}
    production: ${ssm(raw):/Production/Service/DB_USERNAME}
  DB_PASSWORD:
    stage: ${ssm(raw):/Staging/Service/DB_PASSWORD}
    production: ${ssm(raw):/Production/Service/DB_PASSWORD}
```

Output:

```
sls deploy --stage stage   
Environment: darwin, node 12.20.1, framework 3.7.3, plugin 6.1.5, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "custom.DB_HOST.production": Value not found at "ssm" source,
  - Cannot resolve variable at "custom.DB_NAME.production": Value not found at "ssm" source,
  - Cannot resolve variable at "custom.DB_USERNAME.production": Value not found at "ssm" source,
  - Cannot resolve variable at "custom.DB_PASSWORD.production": Value not found at "ssm" source

```

I can only guess that it is trying to lookup production secrets from our staging AWS account.

Imo it should only be looking up variables for the specific stage being run.  The same behaviour is observed when using params.

Any suggestions on how to fix this?

**Comment by pgrzesik** [comment]
Hey @guyschlider - in the proposed case you don't specify anywhere that certain variable should not be resolved. In order to achieve that, you'd have to use conditional approach where e.g. the path to the ssm variable is using the `${sls:stage}` variable itself - then during resolution only the path that should be fetched will be resolved. Could you share a similar example that is failing for you with `params` ?

**Comment by NeilJ247** [comment]
I've refactored my serverless.yml to use params only and still seeing the same issue:

```
service: MyService

provider:
  name: aws
  region: eu-east-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'stage'}
  lambdaHashingVersion: 20201221
  vpc:
    securityGroupIds: ${param:securityGroupIds}
    subnetIds: ${param:subnetIds}
  vpcEndpointIds: ${param:vpcEndpointIds}

  environment:
    DB_HOST: ${param:DB_HOST}
    DB_USERNAME: ${param:DB_USERNAME}
    DB_PASSWORD: ${param:DB_PASSWORD}
    DB_NAME: ${param:DB_NAME}
    NODE_ENV: ${param:NODE_ENV}

plugins:
  - serverless-layers

params:
  default:
    TOPIC_ARN: arn:aws:sns:${aws:region}:${aws:accountId}:Topic
  stage:
    DB_HOST: ${ssm:/Staging/MyService/DB_HOST}
    DB_NAME:  ${ssm(raw):/Staging/MyService/DB_NAME}
    DB_USERNAME: ${ssm(raw):/Staging/MyService/DB_USERNAME}
    DB_PASSWORD: ${ssm(raw):/Staging/MyService/DB_PASSWORD}
    DB_PORT: 5432
    NODE_ENV: development
    vpcId: VPC_STAGING
    securityGroupIds:
      - sg-1
    subnetIds:
      # Private
      - subnet-1
      # Private
      - subnet-2
    vpcEndpointIds:
      - vpce-1
  production:
    DB_HOST: ${ssm:/Production/MyService/DB_HOST}
    DB_NAME: ${ssm(raw):/Production/MyService/DB_NAME}
    DB_USERNAME: ${ssm(raw):/Production/MyService/DB_USERNAME}
    DB_PASSWORD: ${ssm(raw):/Production/MyService/DB_PASSWORD}
    DB_PORT: 5432
    NODE_ENV: production
    vpcId: VPC_PRODUCTION
    securityGroupIds:
      - sg-1
    subnetIds:
      # Private
      - subnet-1
      # Private
      - subnet-2
    vpcEndpointIds:
      - vpce-1

custom:
  serverless-layers:
    dependenciesPath: ./lambda/layers/package.json
    layersDeploymentBucket: layers-bucket

functions:
  contactVerified:
    timeout: 900
    handler: lambda-dist/lambda/src/functions/lambda.handler
    events:
      - sns:
          arn: ${param:TOPIC_ARN}
```

```
sls deploy --stage stage     
Environment: darwin, node 12.20.1, framework 3.7.3, plugin 6.1.5, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "params.production.DB_HOST": Value not found at "ssm" source,
  - Cannot resolve variable at "params.production.DB_NAME": Value not found at "ssm" source,
  - Cannot resolve variable at "params.production.DB_USERNAME": Value not found at "ssm" source,
  - Cannot resolve variable at "params.production.DB_PASSWORD": Value not found at "ssm" source
```
