### ISSUE TITLE
Supported `null` properties are removed from CloudFormation template

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#10675]
### Discussed in https://github.com/serverless/serverless/discussions/10649

<div type='discussions-op-text'>

<sup>Originally posted by **jack-c-tang** February  7, 2022</sup>
Hi,

Based on the second note of the [resource configuration document](https://github.com/serverless/serverless/blob/main/docs/providers/aws/guide/resources.md#configuration), the properties with null assignment are stripped before upload, because CloudFormation doesn't allow them.

But CloudFormation template supports to include some transforms and macros that take those properties and transform to resources CFN allows. For example, [`AWS::Serverless`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html) is a transform CFN supports. The `ResultPath` specified in `Definition` property of [`AWS::Serverless::StateMachine`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html) resources accepts `null` value with certain purpose. Stripping them make the step functions not work as expected.

Should the strip function bypass resources that will be transformed? Or is there a better suggestion or workaround for this usage? Thanks.

Related PR: https://github.com/serverless/serverless/pull/10304
Related issue: https://github.com/serverless/serverless/issues/10279</div>

**Comment by jack-c-tang** [comment]
@pgrzesik, for this specific transform, to achieve what I'd like to do, it has to be a `null` value. String `null` means another thing. For your reference: https://docs.aws.amazon.com/step-functions/latest/dg/input-output-resultpath.html. Currently we workaround it by another characteristic that step function has, but this might be an issue for other transforms or macros. If they accept `null` for certain purpose and do not have workaround, serverless would make it not work.

**Comment by pgrzesik** [comment]
Thanks for providing more details @jack-c-tang - unfortunately at the moment we don't see a good workaround other than using older version of the Framework (which is not great), disabling the `null`-striping unconditionally is unfortunately not an option as some of the Framework internals already rely on that fact to simplify processing. If you have any suggestions/ideas please let us know

**Comment by medikoo** [comment]
One of the ways to approach it would be:

(1). Revert from stripping all null values from generated CF template
(2a). Strip all `null` values in provided service configuration but only for defined configuration properties (without going deep into objects that are values of defined properties)

That way we'd cleanly separate the contract of service configuration where `null` should treat same way as lack of property, and CF template blocks, where users may want to intentionally insert `null` values.

What's interesting, sole purpose of `null` stripping was to make handling of CF directed properties easier.

In logic we want to be able to simply write code:

```javascript
cfResouceProperties[propertyName] = servicerConfig[propertyName];
```

 instead of

```javascript
if (servicerConfig[propertyName] != null) {
  cfResouceProperties[propertyName] = servicerConfig[propertyName];
}
```

Technically another option (2b) could be to revisit all those parts and add such checks, but it'll be pretty noisy and it's error prone.

On the other hand, we could also (2c) declare which properties are directed to be injected into CF as is, and just do null stopping on those.

Nonetheless (2a) feels as best approach, as it won't require any extra configuration to maintain, it should (hopefully) just work

**Comment by pgrzesik** [comment]
Hello @medikoo - could you please clarify what do you mean by "defined configuration properties" in "Strip all null values in provided service configuration but only for defined configuration properties (without going deep into objects that are values of defined properties)"? Do you mean the properties that are explicitly set to `null` in serverless configuration? How are we going to address such stripping then on the final CloudFormation? Won't we need to maintain the logic that explicitly checks which property from config ends up where in CloudFormation? How is that different from stripping in-place where we use that property for the first time?

**Comment by medikoo** [comment]
> Do you mean the properties that are explicitly set to null in serverless configuration? 

By _defined_ I mean those defined explicitly by our schema. So e.g. `resources.Resources[].Properties` is defined in our schema via `{ type: 'object' }`, but `resources.Resources[].Properties.Foo`  is not, so our logic will delete eventual `resources.Resources[].Properties: null` but won't delete eventual `resources.Resources[].Properties.Foo: null`

ofc it may appear that it's tricky to find out which properties are explicitly defined and which note, but if we can do that, then such solution should work well

**Comment by pgrzesik** [comment]
Thanks for the clarification - what about properties that are defined in our schema that can potentially be mapped to different (even nested) properties in CloudFormation? I cannot recall specific example, but I believe we already support it in at least one instance where you can set a specific property to `null` to remove the setting and it's being stripped by our `null` stripping logic from CF template. I will try to find this specific example

**Comment by medikoo** [comment]
@pgrzesik I think for all AWS CF properties we define directly in schema, `null` is not a supported value in AWS, and if that's the case, we will have to go one step forward, by checking if for given property `null` is explicitly defined as allowed value, and if it's a case do not strip it.

**Comment by pgrzesik** [comment]
@medikoo I'm not mentioning not stripping values - I'm mentioning stripping such values so the behavior that we currently support - I believe I do not follow which values exactly do you want to strip by default and which not. For example, how would we check in the final CloudFormation if the value with `null` as in the example that was a motivation for introducing this feature should be stripped or not (https://github.com/serverless/serverless/issues/10279) ?

**Comment by medikoo** [comment]
> I believe I do not follow which values exactly do you want to strip by default and which not.

All those that are expliclty defined in a schema e.g. `resources.Resources[].Properties` is explicitly defined, but `resources.Resources[].Properties.Foo` is not.

> For example, how would we check in the final CloudFormation

We wouldn't check the final CloudFormation, we would check resolved service configuration.

> environment variable set to null) should be stripped or not (#10279) ?

Yes, it'll be, as `provider.environment[]` is defined in schema (same with `functions[].environment[]`)

**Comment by pgrzesik** [comment]
> We wouldn't check the final CloudFormation, we would check resolved service configuration.

Okay - this is the part that I've misunderstood - I thought we would still be stripping values from final CloudFormation template. Thanks for clarification @medikoo 👍

**Comment by robert2d** [comment]
I think this is related.. But the documentation for AWS EventBridge patterns also allow the passing of `null`for pattern matching: [Matching null values and empty strings in Amazon EventBridge event patterns](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-null-values.html). So when using:
```yaml
  processor:
    handler: handler.processor
    events:
      - eventBridge:
          eventBus: arn:aws:events:ap-southeast-2::event-bus/default
          pattern:
            source:
              - com.company.app
            detail-type:
              - specific-type
            detail:
              string_field:
                - anything-but:
                  - ""
                  - null
```
Raises: `'null' values are not allowed in templates`

**Comment by edmundcong** [comment]
any update on this? or possible workaround? the stripping of `null` means we can't use `ResultPath: null` which is making our step function output exceed the 256k limit imposed by AWS

**Comment by shheo042** [comment]
Suffering same problem. `ResultPath: null` is stripped and the next state cannot receive input.
Fix in https://github.com/serverless/serverless/pull/8975 strips supported null value.
Is there any (temporary) workaround for this?
I have to manually set `ResultPath: null` in SFN currently.

**Comment by carvint-subway** [comment]
Same issue here, EventBridge event patterns that match on null are common for us. Any progress on this issue?

**Comment by tianmarin** [comment]
Please!
Everytime we run the CI pipeline, we need to manually set `ResultPath: null` in the console, otherwise the output is always exceed.
We were checking any workaround and have not found one 😢

**Comment by ronkorving** [comment]
@tianmarin I don't think that's related. This repo is the Serverless Framework.

**Comment by medikoo** [comment]
I've updated top description with implementation proposal for solution that should work. 

PR's welcome!

**Comment by louis-kldzj** [comment]
I managed to get this working after a lot of head -> wall contact. 

If you use `AWS::StepFunctions::StateMachine` and put your template in a `.jsonc` file and reference it with `DefinitionString` it will work.

**Comment by zz22394** [comment]
Dear team:
I hit the same issue, and resolved in this way according to your comments.

``` yaml
  StepMachineTest:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: TestStateMachine01
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${Prefix}-states
      StateMachineType: "STANDARD"
      LoggingConfiguration:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/vendedlogs/states:*
        IncludeExecutionData: true
        Level: ALL
      TracingConfiguration:
        Enabled: false
      DefinitionString:
        Fn::Sub:
          - |
            {
              "Comment": "Test Task Definition",
              "StartAt": "${Env}",
              "States": {
                "${Env}": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::states:startExecution.sync:2",
                  "Parameters": {
                    "StateMachineArn": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${Prefix}-ECS-Test",
                    "Input.$": "$"
                  },
                  "ResultPath": null,
                  "End": true
                }
              }
            }
          - Env: !Ref Env
            Prefix: !Ref Prefix
```
