### ISSUE TITLE
Unexpected non-function AJV validator type

### ISSUE THREAD

**Issue by adrianaferrugento** [serverless/serverless#10679]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless deployment is failing occasionally, this has been happening since updating to version 3.

### Service configuration (serverless.yml) content

```yaml
service: service-name
projectDir: ../../

plugins:
  - serverless-s3-sync

custom:
  bucketName: name-${env:STAGE}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      bucketPrefix: ${env:PR_NUMBER}
      localDir: dist

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              AllowedOrigins:
                - 'https://*.${env:DOMAIN}'

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub '${StaticSite.Arn}/*'
              Principal:
                CanonicalUser: ${cf:apps-${env:STAGE}.S3CanonicalUserId}
```

### Command name and used flags

sls deploy --verbose

### Command output

```shell
× Unexpected validator {}, resolved from source 
Environment: linux, node 16.13.2, framework 3.2.0 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Unexpected non-function AJV validator type. Please report at https://github.com/serverless/serverless including all the logs output
    at getValidate (/home/runner/work/apps/apps/node_modules/.pnpm/serverless@3.2.0/node_modules/serverless/lib/classes/config-schema-handler/resolve-ajv-validate.js:73:11)
    at async ConfigSchemaHandler.validateConfig (/home/runner/work/apps/apps/node_modules/.pnpm/serverless@3.2.0/node_modules/serverless/lib/classes/config-schema-handler/index.js:98:22)
    at async Service.validate (/home/runner/work/apps/apps/node_modules/.pnpm/serverless@3.2.0/node_modules/serverless/lib/classes/service.js:267:5)
    at async Serverless.run (/home/runner/work/apps/apps/node_modules/.pnpm/serverless@3.2.0/node_modules/serverless/lib/serverless.js:162:28)
    at async /home/runner/work/apps/apps/node_modules/.pnpm/serverless@3.2.0/node_modules/serverless/scripts/serverless.js:686:9
undefined
```

### Environment information

```shell
Framework Core: 3.2.0 (local)
Plugin: 6.0.0
SDK: 4.3.1
```
