### ISSUE TITLE
Variables: Add support for sub-level configuration

### ISSUE THREAD

**Issue by j0k3r** [serverless/serverless#10683]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Let's says we do have multiple domain values, so we defined them like that:

```yaml
params:
  dev:
    domain:
      account: member.service.tech
      www: www.service.tech
      support: support.service.tech
  prod:
    domain:
      account: member.service.com
      www: www.service.com
      support: support.service.com
```

That example is simple just to get the _problem_.

I tried to use it that way:

```yaml
functions:
  func:
    environment:
      DOMAIN_ACCOUNT: ${param:domain.account}
      DOMAIN_WWW: ${param:domain.support}
      DOMAIN_SUPPORT: ${param:domain.support}
```

But this throw an error:

```
Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "functions.func.environment.DOMAIN_ACCOUNT": Value not found at "param" source,
  - Cannot resolve variable at "functions.func.environment.DOMAIN_WWW": Value not found at "param" source,
  - Cannot resolve variable at "functions.func.environment.DOMAIN_SUPPORT": Value not found at "param" source,
```
