### ISSUE TITLE
Variable Resolution Behaviour Change

### ISSUE THREAD

**Issue by bchampp** [serverless/serverless#10692]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Variable resolution is no longer working as it previously did. The userTable and requestsTable variables are not being populated correctly anymore and thus are not resolved.  I believe this is similar to the problem described here: https://github.com/serverless/serverless/issues/10683

### Service configuration (serverless.yml) content

```yaml
service: hour-logger

frameworkVersion: '2'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-1
  environment:
    userTable: users-${self:provider.stage}
    requestsTable: requests-${self:provider.stage}
```

### Command name and used flags

serverless deploy --stage=beta

### Command output

```shell
Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.userTable": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.requestsTable": Value not found at "env" source
```

### Environment information

```shell
Environment: linux, node 12.22.10, framework 3.2.0, plugin 6.0.0, SDK 4.3.1
```
