### ISSUE TITLE
Failed deployment - ChangeSet does not exist

### ISSUE THREAD

**Issue by adrianaferrugento** [serverless/serverless#10702]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless deployment is failing occasionally, saying that ChangeSet does not exist. If I rerun it will work.

### Service configuration (serverless.yml) content

```yaml
service: service-name
projectDir: ../../

plugins:
  - serverless-s3-sync

custom:
  bucketName: name-${env:STAGE}
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      bucketPrefix: ${env:PR_NUMBER}
      localDir: dist

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE}

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              AllowedOrigins:
                - 'https://*.${env:DOMAIN}'

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub '${StaticSite.Arn}/*'
              Principal:
                CanonicalUser: ${cf:apps-${env:STAGE}.S3CanonicalUserId}
```

### Command name and used flags

sls deploy --verbose

### Command output

```shell
Waiting for new change set to be created

× Stack apps-navigation-shell-dev failed to deploy (2s)
Environment: linux, node 16.13.2, framework 3.2.1 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:

ChangeSet [apps-navigation-shell-dev-change-set] does not exist
1 deprecation found: run 'serverless doctor' for more details
Waiting for new change set to be created
```

### Environment information

```shell
Framework Core: 3.2.1 (local)
Plugin: 6.0.0
SDK: 4.3.1
```
