### ISSUE TITLE
API Gateway Description not working

### ISSUE THREAD

**Issue by robertocerdasilva** [serverless/serverless#10709]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello!
I am learning to use the Serverless Framework and the deployment works correctly but there is a configuration that does not work and it is the description of my API in API Gateway.

In the serverless.yml file I added the "description" tag in API Gateway but at the time of deployment it seems to ignore it. What am I doing wrong ?

Attached image:
![serverless](https://user-images.githubusercontent.com/72045538/154260058-82727b63-1d15-4747-8e88-45878421eb62.png)

### Service configuration (serverless.yml) content

```yaml
service: api-test-service

provider:
    name: aws
    region: us-west-2
    stackName: api-test-dev
    stage: dev
    runtime: nodejs14.x
    timeout: 10
    memorySize: 1024
    endpointType: regional
    apiName: API Test
    apiGateway:
        description: API Test DEV
        binaryMediaTypes:
            - '*/*'

functions:
    hello:
        handler: handler.hello
        description: Function Test DEV
        events:
            - http:
                method: GET
                path: /hello
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.2.1
Plugin: 6.0.0
SDK: 4.3.1
```
