### ISSUE TITLE
Environmentvariable value boolean values always in lower case

### ISSUE THREAD

**Issue by DennisTruemperMd** [serverless/serverless#10718]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

As you can see in the example serverless.yml I declared a few environment Variables.

Here is what the part of the cloudformation template looks like:

`
 "Environment": {
          "Variables": {
            "GLOBAL_ERROR": "true",
            "GLOBAL_OK": "ThisIsCorrectCase",
            "LOCAL_ERROR_TRUE": "true",
            "LOCAL_ERROR_FALSE": "false",
            "LOCAL_OK": "ThisIsCorrectCase"
          }
        },
`

Here is what I expect:
`
 "Environment": {
          "Variables": {
            "GLOBAL_ERROR": "TRUE",
            "GLOBAL_OK": "ThisIsCorrectCase",
            "LOCAL_ERROR_TRUE": "TRUE",
            "LOCAL_ERROR_FALSE": "FALSE",
            "LOCAL_OK": "ThisIsCorrectCase"
          }
        },
`

When I saw that the variable value was changed in case, I thought, that my case sensitive variables would be changed in case too, but this is not the case. 

Please prevent others from falling into this trap.

### Service configuration (serverless.yml) content

```yaml
service: sls-casing

provider:
  name: aws
  stackName: ${self:service}-${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 1024
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  environment:
    GLOBAL_ERROR: TRUE
    GLOBAL_OK: ThisIsCorrectCase

functions:
  myFunction:
    handler: src/index.js
    environment:
      LOCAL_ERROR_TRUE: TRUE
      LOCAL_ERROR_FALSE: FALSE
      LOCAL_OK: ThisIsCorrectCase
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.72.2 (local)
Plugin: 5.5.4
SDK: 4.3.0
Components: 3.18.2
```
