### ISSUE TITLE
Expose docker's build `--squash` parameter 

### ISSUE THREAD

**Issue by mbsimonovic** [serverless/serverless#10712]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I have a fairly large docker image (6GB and growing), so deployment and provisioning tends to be slow. One way to slim down docker images is to pass the `--squash` parameter to docker build which collapses all filesystem layers into one. See https://docs.docker.com/engine/reference/commandline/build/#squash-an-images-layers---squash-experimental

### Proposed solution (optional)

```
provider:
  name: aws
  ecr:
    images:
      squashed:
        path: ./
        file: Dockerfile
        squash: true
```
