### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded for role

### ISSUE THREAD

**Issue by Borduhh** [serverless/serverless#10747]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When deploying with a lot of functions, we get the following error:

```
ServerlessError: An error occurred: IamRoleLambdaExecution - Maximum policy size of 10240 bytes exceeded for role powor-internal-gateway-dev-lambdaRole (Service: AmazonIdentityManagement; Status Code: 409; Error Code: LimitExceeded; Request ID: b6162fe1-82a5-467e-a465-f221e7286e61; Proxy: null).
      at /tmp/seed/source/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:143:23
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async AwsDeploy.update (/tmp/seed/source/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:156:5)
```

Per PR https://github.com/serverless/serverless/pull/6212, Cloudwatch Log permissions should be combined.

We also tried manually creating the permissions for the role in an effort to have them grouped together.
```
provider:
  iam:
    role:
      name: ${self:app}-${self:service}-${self:custom.stage}-lambdaRole
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
          Resource: 
            - Fn::Sub:
                "arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/${self:app}-${self:service}-*-${self:custom.stage}:*"
        - Effect: Allow
          Action:
            - logs:PutLogEvents
          Resource:
            - Fn::Sub:
                "arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/${self:app}-${self:service}-*-${self:custom.stage}:*:*"
```

### Service configuration (serverless.yml) content

```yaml
Function Definition (30 similar functions):

functions:
  TestFunction:
    name: ${self:app}-${self:service}-TestFunction-${self:custom.stage}
    handler: src/functions/TestFunction.handler
    events:
      - http:
          method: get
          path: /test
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
          cors: true
```
```


### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.71.0 (local)
Plugin: 5.5.3
SDK: 4.3.0
Components: 3.18.1
```
```
