### ISSUE TITLE
Detected unrecognized CLI options

### ISSUE THREAD

**Issue by marlonlimaserra** [serverless/serverless#10742]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I use the --page argument to return the correct domain.

In the old version I never had a problem.

Now that I've updated to the latest version, it doesn't let me pass arguments to create a domain.

To deploy it seems to work normally.

even adding the options described in the documentation, the error keeps happening

Defines the environment variables, and also defined it inside the serverless.yml

the temporary solution I found, was to comment the lines

  /* if (unrecognizedOptions.length) {
     throw new ServerlessError(
       `Detected unrecognized CLI options: "--${unrecognizedOptions.join('", "--')}".\n`,
       'UNSUPPORTED_CLI_OPTIONS'
     );
   }*/

inside ensure-supported-command.js

SLS_DEPRECATION_DISABLE=UNSUPPORTED_CLI_OPTIONS

disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS

reference: https://www.serverless.com/framework/docs/deprecations

thanks

### Service configuration (serverless.yml) content

```yaml
service: SprintHub
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
plugins:
  - serverless-domain-manager
  - serverless-offline 
custom:
  customDomain:
    rest:
      domainName: ${file(./serverless/domainName.js)}
      certificateName: '*.sprinthub.dev'
      stage: 'api'
      basePath: '' 
      createRoute53Record: true
      securityPolicy: tls_1_2
    websocket:
      domainName: wss-svl.sprinthub.dev
      stage: hml
      basePath: ''
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: 'regional'
provider:
  name: aws
  runtime: nodejs14.x
  stage: hml
  region: sa-east-1
  memorySize: 256
  logRetentionInDays: 0
  deploymentBucket:
    name: serverless-deploy-dd-bucket
    serverSideEncryption: AES256
functions: ${file(./licenses.js)}
```

### Command name and used flags

sls create_domain --page=1

### Command output

```shell
Error:
Detected unrecognized CLI options: "--page".
```

### Environment information

```shell
Framework Core: 3.3.0
Plugin: 6.1.0
SDK: 4.3.1
```
