### ISSUE TITLE
The `-c` shorcut option for `--config` doesn't work in v3

### ISSUE THREAD

**Issue by gdraynz** [serverless/serverless#10759]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When using the `--config` option, serverless forces the Serverless dasboard onboarding instead of just executing the command for the specified configuration file.

```bash
$ npx sls -c api.yml info -s dev

Onboarding "sls-api-example" to the Serverless Dashboard

? What org do you want to add this service to? [Skip]

? Do you want to deploy now? No

What next?
Run these commands in the project directory:

serverless deploy    Deploy changes
serverless info      View deployed endpoints and resources
serverless invoke    Invoke deployed functions
serverless --help    Discover more commands
$ mv api.yml serverless.yml
$ npx sls info -s dev
Environment: linux, node 17.6.0, framework 3.3.0 (local), plugin 6.1.0, SDK 4.3.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Stack with id sls-api-example-dev does not exist

```

### Service configuration (serverless.yml) content

```yaml
service: sls-api-example

provider:
  name: aws
  region: eu-west-3
  runtime: python3.9
  stage: ${opt:stage}

  httpApi:
    name: ${self:service}-${sls:stage}
    payload: "2.0"
    cors: true

  environment:
    DJANGO_SETTINGS_MODULE: db.settings
    PYTHONPATH: functions/

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - "!node_modules/**"
    - "!requirements/**"
    - "!./*"

layers:
  requirements:
    name: ${self:service}-${sls:stage}-requirements
    path: requirements
    compatibleRuntimes:
      - ${self:provider.runtime}

functions:
  api:
    handler: main.handler
    layers:
      - !Ref RequirementsLambdaLayer
    events:
      - httpApi:
          method: "*"
          path: /
      - httpApi:
          method: "*"
          path: /{proxy+}

custom:
  # - serverless-scriptable-plugin
  scriptable:
    hooks:
      package:initialize:
        - "make requirements"

plugins:
  - serverless-scriptable-plugin
```

### Command name and used flags

serverless -c api.yml info -s dev

### Command output

```shell
Onboarding "sls-api-example" to the Serverless Dashboard

? What org do you want to add this service to? [Skip]

? Do you want to deploy now? No

What next?
Run these commands in the project directory:

serverless deploy    Deploy changes
serverless info      View deployed endpoints and resources
serverless invoke    Invoke deployed functions
serverless --help    Discover more commands
```

### Environment information

```shell
Framework Core: 3.3.0 (local)
Plugin: 6.1.0
SDK: 4.3.1
```
