### ISSUE TITLE
Error when deleting or reordering scheduled events

### ISSUE THREAD

**Issue by commarla** [serverless/serverless#10751]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi,

I have a service with one function but multiples events with different inputs so I named them. 
When I remove or reorder one of them, serverless recompute the Logical ID used in cloudformation so it recreates every events. 
It causes an issue because it tries to create a event with a name already existing. It doesn't delete it first.

You can easily reproduces it with the provided yaml by deleting the whole `my-custom-name-2` event block.

On first deploy with the 3 events I have in cloudformation :
- HelloEventsRuleSchedule1 : my-custom-event-name-1
- HelloEventsRuleSchedule2 : my-custom-event-name-2
- HelloEventsRuleSchedule3 : my-custom-event-name-3

when I remove `my-custom-event-name-2` and deploy It tries to do : 
- HelloEventsRuleSchedule1 : my-custom-event-name-1
- HelloEventsRuleSchedule2 : my-custom-event-name-3

But it fails because `my-custom-event-name-3` already exists and was not deleted.

If I omit the custom `name` I don't have the issue as serverless append random id to the event name (`my-custom-event-name-3` become `aws-node-test-dev-HelloEventsRuleSchedule3-IFGUIGSEMLUR`)

Thanks,

### Service configuration (serverless.yml) content

```yaml
service: aws-node-test
frameworkVersion: '^3.3.0'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello

    events:
      - schedule:
          name: my-custom-name-1
          rate: rate(1 hour)
          input:
            mykey1: myvalue1
      - schedule:
          name: my-custom-name-2
          rate: rate(1 hour)
          input:
            mykey2: myvalue2
      - schedule:
          name: my-custom-name-3
          rate: rate(1 hour)
          input:
            mykey3: myvalue3
```

### Command name and used flags

./node_modules/serverless/bin/serverless.js deploy

### Command output

```shell
➜ ./node_modules/serverless/bin/serverless.js deploy

Deploying aws-node-test to stage dev (us-east-1)

✖ Stack aws-node-test-dev failed to deploy (41s)
Environment: linux, node 17.3.0, framework 3.3.0 (local), plugin 6.1.0, SDK 4.3.1
Credentials: Local, "staging" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: HelloEventsRuleSchedule2 (AWS::Events::Rule)
my-custom-name-3 already exists in stack arn:aws:cloudformation:us-east-1:ACCOUNTID:stack/aws-node-test-dev/8fdba240-9579-11ec-9295-0e1d2ca4d6ed
```

### Environment information

```shell
Framework Core: 3.3.0 (local)
Plugin: 6.1.0
SDK: 4.3.1
```
