### ISSUE TITLE
Serverless excludes prod dependencies when packaging unless excludeDevDependencies is false

### ISSUE THREAD

**Issue by pflugs30** [serverless/serverless#10750]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

_Pulled from [this discussion topic](https://github.com/serverless/serverless/discussions/10745)..._

I have a Serverless project with many Lambdas where I've isolated the production dependencies to a Lambda layer in order to reduce the individual Lambda sizes and speed up deployment.  As such, I've put all my Lambda dependencies in the `devDependencies` section of the `package.json` file.  Then, in the Lambda layer directory, I have a `package.json` file containing all the dependencies so they can be bundled together.  My code files are structured like this:
* root
  * layers
    * appsync-layer
      * package.json
      * yarn.lock
  * serverless.yml
  * package.json
  * webpack.config.js
  * yarn.lock

Note that there are no *.js files in the layers directory.  The `root/layers/appsync-layer/package.json` file contains a list of dependencies:
```
{
  "name": "appsync-layer",
  "description": "Contains the packages needed for the Appsync layer",
  "dependencies": {
    "aws-sdk": "2.1074.0",
    "mysql2": "2.3.3",
    "p-iteration": "1.1.8",
    "sequelize": "6.16.1",
    "uuid": "8.3.2"
  }
}
```

Here's the `package.json` file:
```
{
  "name": "platform-appsync",
  "scripts": { ... },
  "devDependencies": {
     /* ... many others */
    "sequelize-cli": "6.4.1",
    "serverless": "3.2.1",
    "serverless-appsync-plugin": "1.12.1",
    "serverless-appsync-simulator": "0.19.6",
    "serverless-offline": "8.4.0",
    "serverless-webpack": "5.6.1",
    "typescript": "4.5.5",
    "uuid": "8.3.2",
    "webpack": "5.69.0",
    "webpack-cli": "4.9.2",
    "webpack-node-externals": "3.0.0",
    "winston": "3.6.0"
  },
  "dependencies": {} // nothing here!
}
```

Here's a condensed version of `serverless.yml`:

When I run `sls package --stage dev` and inspect the result, I notice the `appsync.zip` file does not contain ANY packages at all.  When I set the `excludeDevDependencies` flag to `false` and package again, then the dependencies are added to the layer zipped file.

I should note I also ran a test where I added a dummy file `test.js` to the layers directory containing the following:
```
require('aws-sdk');
require('mysql2');
require('p-iteration');
require('sequelize');
require('uuid');
```

I thought the file would force the dependency checker to include the packages, but I still found no modules in the lambda zipped file when finished.

I will create a sample repository after saving this issue.

### Service configuration (serverless.yml) content

```yaml
service: platform-appsync
useDotenv: true

frameworkVersion: ">=3.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    NODE_PATH: "./:/opt/node_modules"

layers:
  appsync:
    path: layers/appsync-layer
    compatibleRuntimes:
      - nodejs12.x
    package:
      patterns:
        - node_modules/**

functions:
  databaseSync:
    handler: src/databaseSync.handler
    name: ${self:provider.stage}-databaseSync
    layers:
      - { Ref: AppsyncLambdaLayer }

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-offline

custom:
  webpack:
    excludeFiles: "**/*.spec.js"
    includeModules:
      forceExclude:
        - aws-sdk
        - mysql2
        - p-iteration
        - sequelize
        - uuid
      packagePath: "./package.json"
    webpackConfig: "webpack.config.js"
    packager: "yarn"
```

### Command name and used flags

serverless package --verbose --region us-east-1 --stage dev

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.2.1 (local)
Plugin: 6.0.0
SDK: 4.3.1
```
