### ISSUE TITLE
Variables/Params List Merge

### ISSUE THREAD

**Issue by samchungy** [serverless/serverless#10756]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

👋  I have a monorepo of Lambdas which share a common values.yaml file.

eg. 

```yml
dev:
  someValue: a
prod:
  someValue: b
```

Is there any way I could bring these values into `params`? Something like using the yaml merge?

### Proposed solution (optional)

eg.

```yml
params:
  default: 
    <<: ${file(./values.${sls:stage})}
    otherLambdaSpecificVariable: a
 ```
