### ISSUE TITLE
`websockets` `provisionedConcurrency` alias is not properly recognized

### ISSUE THREAD

**Issue by dzorlu** [serverless/serverless#10764]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Per the discussion [here](https://github.com/serverless/serverless/discussions/10755), there seems to be a bug with `websockets` where the `provisionedConcurrency` alias is not properly recognized. this issue causes new stack deployments in `ci/cd` not using provisioned concurrency. 

![pic](https://user-images.githubusercontent.com/3424293/155627217-ec31e60b-435c-40a0-834b-0f61c516bb6a.png)

Thank you!
Deniz

### Service configuration (serverless.yml) content

```yaml
org: xxx
app: ps-streaming
service: ps-streaming

provider:
    name: aws
    runtime: python3.8
    stage: ${sls:stage}
    timeout: 30
    memorySize: 2048
    region: us-west-2

    iamRoleStatements:
        - Effect: Allow
          Action:
              - "execute-api:ManageConnections"
          Resource:
              - "arn:aws:execute-api:*:*:**/@connections/*"
        - Effect: Allow
          Action:
              - "dynamodb:PutItem"
              - "dynamodb:GetItem"
              - "dynamodb:UpdateItem"
              - "dynamodb:DeleteItem"
              - "dynamodb:BatchGetItem"
              - "dynamodb:BatchWriteItem"
              - "dynamodb:Scan"
              - "dynamodb:Query"
          Resource:
              - "arn:aws:dynamodb:us-west-2:*:*"
        - Effect: Allow
          Action:
              - "sagemaker:InvokeEndpoint"
          Resource:
              - "*"

custom:
    pythonRequirements:
        zip: true
    scripts:
        hooks:
            'deploy:finalize': "python tests/test_e2e.py" #e2e testing after deployment.
    output:
        file: stack-output.json # save the websocket endpoint for e2e testing.
    provisionedConcurrency:
        defaultMessage:
            production: 100
            main: 100
            develop: 20
            else: 10
        connectionManager:
            production: 10
            main: 10
            develop: 2
            else: 1
        

functions:
    connectionManager:
        handler: handler.connection_manager
        events:
            - websocket:
                route: $connect
            - websocket:
                route: $disconnect
        provisionedConcurrency: ${self:custom.provisionedConcurrency.connectionManager.${sls:stage}, self:custom.provisionedConcurrency.connectionManager.else}
        
    defaultMessage:
        handler: handler.default
        events:
            - websocket:
                route: $default
        provisionedConcurrency: ${self:custom.provisionedConcurrency.defaultMessage.${sls:stage}, self:custom.provisionedConcurrency.defaultMessage.else}
    ping:
        handler: handler.ping
        events:
            - http:
                path: ping
                method: get

plugins:
  - serverless-python-requirements
  - serverless-plugin-scripts
  - serverless-stack-output
```

### Command name and used flags

n/a

### Command output

```shell
n/a
```

### Environment information

```shell
Framework Core: 2.66.2 (local)
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
```
```
