### ISSUE TITLE
Detected unrecognized CLI options - cors

### ISSUE THREAD

**Issue by alifaff** [serverless/serverless#10760]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello,
I recently changed node version from 10.x to 14.x and needed to also make changes to serverless version from 1.19.0 to 3.3.0 (latest).  When running serverless deploy, I receive the following:
deploying serverless project
Environment: linux, node 14.19.0, framework 3.3.0 (local), plugin 6.1.0, SDK 4.3.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Detected unrecognized CLI options: "--cors".
deployName = cruises-content
stage = staging
api prefix = staging-cruises-content
As you can see the error is an undetected option: cors

### Service configuration (serverless.yml) content

```yaml
service: content-api-graphql

plugins:
  - serverless-webpack
  - add-preflight-maxage
  - serverless-prune-plugin

custom:
  stage: ${opt:stage}
  region: us-east-1
  aws_account: xxxx
  rds:
    cluster: prod-aurora-01-cluster
    host: xxx
    db: dbname
    user: db-user
  cache:
    host: ${ssm:/${opt:stage}/caching/memcached}
  cors_origin_primary: 
    dev: "http://${opt:stage}.url.com:8080"
    staging: ${opt:cors}
    production: ${opt:cors}
  cors_origin_additional:
    dev: "http://${opt:stage}.url.com:8081"
    staging: ${opt:cors}
    production: ${opt:cors}
  dynamodb:
    BLOG_TAG_TABLE: blog_tag
  vpc:
    subnet1: subnet-48d3653a
    subnet2: subnet-38d0e23c
    securitygroup1: sg-28d3306
  loglevel: error
  lambda:
    dataCollector: data-collector-${opt:stage}-log
  kinesis:
    logStream: data-logger-${opt:stage}
    logStreamAtoms: data-logger-atoms-${opt:stage}
  s3:
    outputBucket: content-googletags
  prune:
    automatic: true
    number: 25

package:
  exclude:
    - local/**
    - .git/**
    - graphql/**/__tests__/**

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    # TZ: America/Chicago
    REGION: ${self:custom.region}
    RDS_USER: ${self:custom.rds.user}
    RDS_HOST: ${self:custom.rds.host}
    RDS_DB: ${self:custom.rds.db}
    CACHE_HOST: ${self:custom.cache.host}
    NODE_ENV: production
    LOGLEVEL: ${self:custom.loglevel}
    LAMBDA_DATA_COLLECTOR: ${self:custom.lambda.dataCollector}
    S3_RESULT_BUCKET: ${self:custom.s3.outputBucket}
    S3_RESULT_CSV: cruises-${opt:stage}.csv
    KINESIS_LOG: ${self:custom.kinesis.logStream}
    KINESIS_LOG_ATOMS: ${self:custom.kinesis.logStreamAtoms}
    BLOG_TAG_TABLE: ${self:custom.dynamodb.BLOG_TAG_TABLE}
  apiKeys:
    - content-api-${opt:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
    - Effect: Allow
      Action:
        - rds:Describe*
        - rds:ListTagsForResource
        - ec2:DescribeAccountAttributes
        - ec2:DescribeAvailabilityZones
        - ec2:DescribeSecurityGroups
        - ec2:DescribeVpcs
      Resource: "arn:aws:rds:${self:custom.region}:${self:custom.aws_account}:${self:custom.rds.cluster}"
    - Effect: "Allow"
      Action:
        - rds-db:connect
      Resource:
        - "arn:aws:rds-db:${self:custom.region}:${self:custom.aws_account}:dbuser:*/${self:custom.rds.user}"
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource:
        - "arn:aws:lambda:${self:custom.region}:${self:custom.aws_account}:function:${self:custom.lambda.dataCollector}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${self:custom.s3.outputBucket}/*"
    - Effect: "Allow"
      Action:
        - kinesis:DescribeStream
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource:
        - "arn:aws:kinesis:${self:custom.region}:${self:custom.aws_account}:stream/${self:custom.kinesis.logStream}"
        - "arn:aws:kinesis:${self:custom.region}:${self:custom.aws_account}:stream/${self:custom.kinesis.logStreamAtoms}"
    - Effect: "Allow"
      Action:
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:${self:custom.region}:${self:custom.aws_account}:table/${self:custom.dynamodb.BLOG_TAG_TABLE}"     
        - "arn:aws:dynamodb:${self:custom.region}:${self:custom.aws_account}:table/${self:custom.dynamodb.BLOG_TAG_TABLE}/index/*"
  vpc:
    securityGroupIds:
      - ${self:custom.vpc.securitygroup1}
    subnetIds:
      - ${self:custom.vpc.subnet1}
      - ${self:custom.vpc.subnet2}

functions:
  api:
    handler: handler.graphql
    events:
      - http:
        path: graphql
        method: post
        cors: true
        integration: lambda-proxy
        private: true
  apiCookie:
    handler: handler.graphql
    timeout: 10
    events:
      - http:
        path: auth/graphql
        method: post
        authorizer:
          arn: arn:aws:lambda:us-east-1:xxxx:function:${opt:stage}-authSales
          identitySource: method.request.header.Cookie
          resultTtlInSeconds: 0
        cors:
          origins:
            - '${self:custom.cors_origin_primary.${opt:stage}}'
            - '${self:custom.cors_origin_additional.${opt:stage}}'
          allowCredentials: true
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - X-AT-Application-Name
            - X-AT-Application-Version
            - X-AT-Application-Build
            - X-AT-Application-Stage
            - X-AT-Phone-Number
            - X-AT-Client-Id
            - X-AT-Client-Tracking-Id
        integration: lambda
        response:
          headers:
            Access-Control-Allow-Origin: "'https://ms.url.com'"
            Access-Control-Allow-Credentials: "'true'"
            Access-Control-Allow-Headers: "'X-AT-Application-Name,X-AT-Application-Version,X-AT-Application-Build,X-AT-Application-Stage,X-AT-Phone-Number,X-AT-Client-Id,X-AT-Client-Tracking-Id'"
  exportSearchCsv:
    handler: graphql/app/content/content.exportSearchCsv
    events:
      - schedule:
        rate: rate(24 hours)
        enabled: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
```

### Command name and used flags

sls deploy --stage staging

### Command output

```shell
stage = staging
cors = https://ms.url.com
deploying serverless project
Environment: linux, node 14.19.0, framework 3.3.0 (local), plugin 6.1.0, SDK 4.3.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Detected unrecognized CLI options: "--cors".
deployName = cruises-content
stage = staging
```

### Environment information

```shell
3.3.0
```
