### ISSUE TITLE
 load env variables from .env files failed

### ISSUE THREAD

**Issue by Jadenhub** [serverless/serverless#10763]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- no, but when I use the latest version, still get the same issue.

### Issue description

I run `npx serverless offline --apiKey just_key --prefix dev`, but get error.

### Package.json
```
    "serverless-dotenv-plugin": "^2.4.2",
    "serverless-offline": "^5.12.1",
    "serverless-pseudo-parameters": "^2.4.0"
```

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  stage: ${env:AWS_STAGE}
  memorySize: 256
  runtime: nodejs12.x
  role: LambdaRole
  environment:
    STAGE: ${self:custom.STAGE}
    #postgresql
    POSTGRES_DB: ${env:POSTGRES_DB}
    POSTGRES_HOST: ${env:POSTGRESQL.HOST}
    POSTGRES_PORT: ${env:POSTGRESQL.PORT}
    POSTGRES_USER: ${env:POSTGRES_USER}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
custom:
  STAGE: ${opt:stage, self:provider.stage}
  BASE_URL_V1: /api/v1
  POSTGRES_DB: catcrouch_db
  POSTGRESQL:
  #   HOST:
  #     Fn::GetAtt: [PostgreSqlRDSInstance, Endpoint.Address]
  #   PORT:
  #     Fn::GetAtt: [PostgreSqlRDSInstance, Endpoint.Port]
    VPC_CIDR: 10
  POSTGRES_USER: ${env:POSTGRES_USER}
  POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD}
  serverless-offline:
    noAuth: true
    stages: dev

plugins:
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  - serverless-offline
```

### Command name and used flags

npx serverless offline --apiKey just_key --prefix dev

### Command output

```shell
npx serverless offline --apiKey just_key --prefix dev
Environment: darwin, node 12.18.2, framework 3.4.0, plugin 6.1.2, SDK 4.3.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.stage": Value not found at "env" source
```

### Environment information

```shell
Framework Core: 3.4.0
Plugin: 6.1.2
SDK: 4.3.1
```
