### ISSUE TITLE
Can't set public access block for Amazon S3, and it is always set disabled.

### ISSUE THREAD

**Issue by acro-takanori** [serverless/serverless#10774]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I use Severless Framework for AWS.

I set "blockPublicAccess" for Amazon S3 to **true**, but S3 Blocking public access is **not to be enabled**.
And If I manually **set to be enabled** and then deploy it again, it **set to be disabled**.

How can it be enabled?

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  stage: ${opt:stage, "dev"}
  region: us-west-2

  # Deployment bucket
  deploymentBucket:
    name: slsdeploy-example-app-todos-dev
    blockPublicAccess: true

plugins:
  - serverless-prune-plugin
  - serverless-deployment-bucket

functions:
  findTodoList:
    handler: todo_handler.find_todo_list_handler
    events:
      - http:
          path: /todos
          method: get
          cors: true
```
```


### Command name and used flags

sls deploy

### Command output

```shell
Deploying example-app-todos to stage dev (us-west-2)
Using deployment bucket 'slsdeploy-example-app-todos-dev'
Updated deployment bucket public access block
Using deployment bucket 'slsdeploy-example-app-todos-dev'
✔ Pruning of functions complete

✔ Service deployed to stack example-app-todos-dev (78s)```
```
```


### Environment information

```shell
Framework Core: 3.5.1
Plugin: 6.1.2
SDK: 4.3.1
```

**Comment by pgrzesik** [comment]
Hello @acro-takanori - is there a reason why you're using `serverless-deployment-bucket` plugin specifically? Did you try setting it without that plugin? I'm not sure if it's not interfering with the logic in some way that breaks working functionality in the Framework.

**Comment by acro-takanori** [comment]
Hello @pgrzesik , Thank you for your reply.
I use `serverless-deployment-bucket` because it can automatically create the S3 deploy bucket.

When I deployed without using that plugin, the results are the following;

- Can't set "blockPublicAccess" (same as before)
- After set to be enabled manually,  it don't change to be disabled (changed).

Some of the behavior has changed, but it still does not seem to be working correctly.

**Comment by pgrzesik** [comment]
Hello @acro-takanori - I think I understand the issue now - you provide `name` which means that the deployment bucket is created outside of Serverless Framework CloudFormation stack - in such case all other properties have no effect because you essentially configure that you're providing the bucket as is - Framework won't apply any changes. We should improve the behavior to introduce a warning/error that all additional properties are simply ineffective in such a situation.  Can you. confirm that your intention is to create S3 bucket separately and provide it to Serverless Framework?

We'd be happy to accept a PR with such improvement.

**Comment by philvarner** [comment]
The issue here is that serverless-deployment-bucket requires a confusing configuration. I have not verified this theory by looking at the changelogs for serverless and serverless-deployment-bucket, but I believe that the `blockPublicAccess` configuration option was added to serverless-deployment-bucket prior to it being added to serverless, and each requires it to be in a different place in the configuration.

Without the plugin, serverless allows the configuration of the name of a pre-existing bucket **or** other parameters like Block Public Access can be set.

This sets the name to a pre-existing bucket, and does not modify it:
```
provider:
  deploymentBucket:
    name: some-bucket
    blockPublicAccess: true # Ignored!
```

This auto-creates the bucket with the default name, and sets Block Public Access:
```
provider:
  deploymentBucket:
    blockPublicAccess: true
```

Confusingly, when using the serverless-deployment-bucket plugin, the provider/deploymentBucket/name field is used for the bucket name (creating it if it doesn't exist), but the provider/deploymentBucket/blockPublicAccess configuration is **ignored** and only the custom/deploymentBucket/blockPublicAccess is honored.

A correct configuration for using serverless-deployment-bucket will look like this:

```
plugins:
  - serverless-deployment-bucket
...
provider:
  deploymentBucket:
    name: slsdeploy-example-app-todos-dev
...
custom:
  deploymentBucket: # used by serverless-deployment-bucket
    blockPublicAccess: true
```
