### ISSUE TITLE
Cannot use object from AWS Secrets Manager with new v3 staging params

### ISSUE THREAD

**Issue by kgonyon** [serverless/serverless#10788]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We are trying to use the new serverless 3 stage params, but they don't seem to work with objects returned from AWS secrets manager.

We are trying to set api to an object in secrets manager which has the structure
```
{
  admin: string
  url: string
}
```

Trying to access the nested values via `${param:api.admin}` or `${param:api.url}` is throwing an error complaining it doesn't exist.

### Service configuration (serverless.yml) content

```yaml
service: lop-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: local
  region: us-east-1
  environment:
    API_ADMIN_SECRET: ${param:api.admin}

functions:
  auth:
    handler: lib/handlers/auth/index.auth
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: auth/{proxy+}
          method: any

params:
  local:
    api: ${ssm:/aws/reference/secretsmanager/hasura-lop-staging-creds}
  staging:
    api: ${ssm:/aws/reference/secretsmanager/hasura-lop-staging-creds}
  production:
    api: {}
  hasura:
    version: ${env:HASURA_VERSION, 'v2.2.0'}
```

### Command name and used flags

sls param list

### Command output

```shell
Environment: darwin, node 12.22.9, framework 3.7.1 (local), plugin 6.1.5, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.API_ADMIN_SECRET": Value not found at "param" source
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ sls:params: `sls param list`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ sls:params script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kgonyon/.npm/_logs/2022-03-02T17_18_49_270Z-debug.log
```

### Environment information

```shell
Framework Core: 3.7.1 (local)
Plugin: 6.1.5
SDK: 4.3.2
```
