### ISSUE TITLE
Unable to deploy new stack

### ISSUE THREAD

**Issue by ryanwalters** [serverless/serverless#10782]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

**Steps to Reproduce:**
1. Create a new TypeScript project `npx serverless@2 create --template aws-nodejs-typescript --path service` (this command errors when using v3)
2. Update serverless.ts `frameworkVersion` from `2` to `3`
3. Run `npx serverless@3 deploy --stage dev --verbose`

**Expected Result:**
Stack gets created for the `dev` stage

**Actual Result:**
Produces the following error:
```
Stack [service-dev] does not exist
```
Apologies if this is a duplicate, I was unable to find an issue with this particular error message. Please let me know if you need any further details.

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from '@serverless/typescript';
import hello from '~/functions/hello';

const serverlessConfiguration: AWS = {
  service: 'service',
  frameworkVersion: '3',
  plugins: ['serverless-esbuild'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
    },
    lambdaHashingVersion: '20201221',
  },
  // import the function via paths
  functions: { hello },
  package: { individually: true },
  custom: {
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ['aws-sdk'],
      target: 'node14',
      define: { 'require.resolve': undefined },
      platform: 'node',
      concurrency: 10,
    },
  },
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

npx serverless deploy --stage dev --verbose

### Command output

```shell
Deploying service to stage dev (us-east-1)

Packaging
Compiling to node14 bundle with esbuild...
Compiling with concurrency: 10
Compiling completed.
(node:33676) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Zip service service - 13.34 KB [26 ms]
Retrieving CloudFormation stack
Deployment bucket not found. Updating stack to include deployment bucket definition.
Ensuring that deployment bucket exists
Creating new change set.

× Stack service-dev failed to deploy (1s)
Environment: win32, node 16.14.0, framework 3.7.0 (local), plugin 6.1.4, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Stack [service-dev] does not exist

1 deprecation found: run 'serverless doctor' for more details
```

### Environment information

```shell
Framework Core: 3.7.0 (local)
Plugin: 6.1.4
SDK: 4.3.2
```
