### ISSUE TITLE
provisionedConcurrency default is 0 but schema enforces >= 1

### ISSUE THREAD

**Issue by d-fay** [serverless/serverless#10791]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I would like `provisionedConcurrency` set to zero in my lower environments and greater than zero higher environments such as prod. To do this I am currently referencing a local config file. 

[The serverless.yml guide ](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml) mentions that zero is the default when this property is not included. For this reason it seems that I should be able to specify a value of zero even when the property is included. This would allow me to set `provisionedConcurrency` to zero in lower environments and deploy with a number greater than zero in higher environments such as production where availability is more important. Is there a reason that this is not allowed in Serverless Framework version 3?

```
functions:
  # A function
  hello:
    # The file and module for this specific function. Cannot be used with 'image'.
    handler: users.create
      # Provision a minimum number of concurrent instances (default: 0)
      provisionedConcurrency: 3
```

I'm not a javascript developer but I believe I have identified the area of the codebase where this is enforced. I am happy to open a PR to change this if maintainers think this is a reasonable change (to a minimum of zero):
https://github.com/serverless/serverless/blob/3444a5649c95c45d9de38a14ae3d6da873a9a111/lib/plugins/aws/provider.js#L1285 

### Service configuration (serverless.yml) content

```yaml
service: foobar
frameworkVersion: '3'

provider:
    name: aws
    runtime: python3.8
    stage: ${sls:stage}
    region: us-west-1

custom:
    pythonRequirements:
        dockerizePip: non-linux
        usePipenv: true

functions:
    baz:
        handler: handler.baz
        provisionedConcurrency: ${file(service_name_${self:provider.stage}.json):provisioned_concurrency}

plugins:
  - serverless-python-requirements
```

### Command name and used flags

serverless deploy --stage dev

### Command output

```shell
Warning: Invalid configuration encountered
  at 'functions.baz.provisionedConcurrency': must be >= 1

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Framework Core: 3.7.1 (local) 3.7.1 (global)
Plugin: 6.1.5
SDK: 4.3.2
```
