### ISSUE TITLE
Rabbit MQ event missing virtual host

### ISSUE THREAD

**Issue by EnterNameHere7** [serverless/serverless#10813]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When creating a rabbitmq event for a lambda function you can't specify the virtual host

### Service configuration (serverless.yml) content

```yaml
service: enter_name_here
frameworkVersion: ^3.3.0

provider:
  name: aws
  region: eu-west-1
  stackName: enter_name_here

  iam:
    role:
      managedPolicies:
        - { 'Fn::Join': [':', ['arn:aws:iam:', { Ref: 'AWS::AccountId' }, 'policy/sumo-pusher']] }
      statements:
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource:
            - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):secrets.general}
            - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):secrets.rds}
            - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):secrets.redis}


  deploymentBucket:
    name: com.serverless.${self:provider.region}.${opt:stage, 'development'}.enter.deploys
    blockPublicAccess: true
  deploymentPrefix: lambdas

functions:
  enter_name_here:
    handler: LambdaHandler
    name: enter_name_here
    description: enter_name_here lambda desc
    runtime: go1.x
    memorySize: 128
    timeout: 10
    environment:
      LOG_LEVEL: info
      SECRET_NAME: 'configuration/enternamehere'
    vpc:
      securityGroupIds:
        - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):securityGroups.rds-apps}
        - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):securityGroups.redis-apps}
      subnetIds:
        - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):subnets.a}
        - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):subnets.b}
        - ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):subnets.c}
    events:
      - rabbitmq:
          arn: ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):rabbitmq.broker}
          queue: test.queue
          batchSize: 1
          basicAuthArn: ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):rabbitmq.auth}
          virtualHost: ${file(./.deploy/config/${aws:accountId, '1234'}.yaml):rabbitmq.vhost}
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.7.2
Plugin: 6.1.5
SDK: 4.3.2
```
