### ISSUE TITLE
Allow logRetentionInDays to be defined per function (and globally)

### ISSUE THREAD

**Issue by d-fay** [serverless/serverless#10828]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Certain API endpoints and/or functions are invoked at a much greater frequency than others. This can cause a significant increase in log events and in return can cost significantly more to store a high volume log data. Meanwhile other endpoints are invoked less frequently and as such it can be useful to have log events be stored and persisted for a longer amount of time. To ensure the presence of recent log events across all functions while avoiding storing cumbersome amounts of log data on frequently invoked functions, it is useful to be able to set the log retention value on a per function basis. This can be both useful for debugging but more importantly dramatically reduce costs. 

### Proposed solution (optional)

Allow the `logRetentionInDays` to exist as a property of a `function` allowing users to set a different value for `logRetentionInDays` on each lambda handler. Currently it is only possible to set a value for `logRetentionInDays` underneath the `provider` key. 

Example of desired usage:
```yaml
functions:
  foo:
    handler: foo.handler
    timeout: 20
    logRetentionInDays: 3
    events:
      - http:
          path: foo
          method: get
          private: false
```

Please note, this has historically be possible by using the plugin `serverless-plugin-log-retention` but as of v3 the configValidationMode check is raising warnings which will break deployments in v4. 

```
Serverless: Configuration warning:
Serverless:   at 'functions.foo': unrecognized property 'logRetentionInDays'
```
Ideally, no plugin should be necessary for this requested feature.
