### ISSUE TITLE
S3 trigger and function code is not registered after deployment

### ISSUE THREAD

**Issue by may215** [serverless/serverless#10847]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi,
After deploying the to aws there are two issues:
1. After successful deployment, I go to Lambda console’s Triggers tab, but I don’t see any trigger.
So, I added IAM role to yaml as below, but still cannot see any trigger.  
iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
After adding a trigger manually via AWS console, my lambda function worked as expected.
I tried to re-indent the file, but, still the same issue.

2. The code that shows under the code tab is for the first function in the serverless.yml. 
why is that?

### Service configuration (serverless.yml) content

```yaml
service: company-api
frameworkVersion: "2"
useDotenv: true
plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-offline
  - serverless-stage-manager
  - serverless-prune-plugin
  - serverless-plugin-aws-alerts
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs12.x
  stage: staging
  region: us-east-1
  environment:
    userTableName: ${self:custom.USER_TABLE}
    bucketName: ${self:custom.BUCKET_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::company-chat-media"
    - Effect: Allow
      Action:
        - cognito-sync:*
        - cognito-identity:*
      Resource: arn:aws:cognito-identity:*:*:*
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: arn:aws:cognito-idp:*:*:*
    - Effect: Allow
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource: arn:aws:s3:::company-chat-media/*
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:us-east-1:${self:custom.accountId}:table/*"
custom:
  stages:
    - staging
  dynamodb:
    stages:
      - ${self:custom.currentStage}
    start:
      port: 8002
      inMemory: true
      migrate: true
  currentStage: ${opt:staging, 'staging'}
  userPool: amplify_backend_manager_d1qr8duzal0xqh
  USER_PRIMARY_KEY: id
  USER_SORT_KEY: phone
  USER_TABLE: User-${self:custom.tableHash}-${self:custom.currentStage}
  PRIMARY_KEY: id

functions:
  createOrUpdateUser:
    handler: src/functions/user/UserPoolTriggers/createOrUpdateUser.handler
    environment:
      TABLE_NAME: ${self:custom.USER_TABLE}
    events:
      - cognitoUserPool:
          pool: ${self:custom.userPool}
          trigger: PostConfirmation
          existing: true
  postprocess:
    handler: src/functions/media/postUpload.handler
  getPreSignedPostData:
    handler: src/functions/media/preSignedMedia.handler
    integration: lambda
    environment:
      TABLE_NAME: ${self:custom.USER_TABLE}
    events:
      - http:
          path: /getPreSignedPostData
          method: POST
  userGroupNotification:
    handler: src/functions/participant/userGroupNotification.handler
    integration: lambda
    environment:
      USER_TABLE_NAME: ${self:custom.USER_TABLE}
    events:
      - http:
          path: /userGroupNotification
          method: POST
```

### Command name and used flags

SLS_DEBUG=* serverless deploy --stage staging

### Command output

```shell
N/A
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.19.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```
