### ISSUE TITLE
serverless.yml profile attribute doesn't work

### ISSUE THREAD

**Issue by ianzone** [serverless/serverless#10841]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi there, I've specified profile attribute in serverless.yml, but when I run sls deploy, it always chooses the default profile. I have checked my selected profile did exist in ~/.aws/credentials and serverless dashboard.

### Service configuration (serverless.yml) content

```yaml
org: xxx
app: xxx
service: xxx

frameworkVersion: "3"
configValidationMode: error
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  stage: ${opt:stage, "dev"}
  region: eu-west-1
  profile: myProfile
  tags:
    user: ian
    project: ${self:app}
    service: ${self:service}
  httpApi:
    cors: true
  logRetentionInDays: 7
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${param:FaqBucket}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
    REGION: ${aws:region}
    FaqBucket: ${param:FaqBucket}

params:
  dev:
    FaqBucket: my-bucket-dev
  prod:
    FaqBucket: my-bucket-prod

functions:
  fastify:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /{ANY+}
          method: ANY

package:
  patterns:
    - "!src/**"
    - "!test/**"

plugins:
  - serverless-offline
```

### Command name and used flags

sls deploy

### Command output

```shell
❯ npm run deploy

> api@1.0.0 deploy
> tsc && sls deploy

Deploying kendra-api to stage dev (eu-west-1, "default" provider)

✔ Service deployed to stack kendra-api-dev (137s)
```

### Environment information

```shell
❯ sls --version   
Running "serverless" from node_modules
Framework Core: 3.7.4 (local) 3.7.4 (global)
Plugin: 6.1.5
SDK: 4.3.2
```
