### ISSUE TITLE
Kinesis Firehose as Destination for REST API Logs

### ISSUE THREAD

**Issue by waynerobinson** [serverless/serverless#10879]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

REST APIs can use Kinesis Firehose streams as a direct destination for logs.

See https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-logging-to-kinesis.html and  `DestinationArn` in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-stage-accesslogsetting.html

### Proposed solution (optional)

Allow Kinesis Firehose delivery stream to be specified (with appropriate role) as an option when configuring the logging options for REST API.

**Comment by pgrzesik** [comment]
Thanks a lot for your proposal @waynerobinson 👍 It looks like an interesting request, did you think on how it would be best represented in configuration? 

Please note that REST API logging is handled in a bit different way (it's not set by CloudFormation but rather by direct SDK calls), but I think it should still be possible to implement - https://github.com/serverless/serverless/blob/991566f1795beb66d74b24501a168608ba269e4e/lib/plugins/aws/package/compile/events/api-gateway/lib/hack/update-stage.js#L281-L303

**Comment by Blikingor** [comment]
@pgrzesik How about sometime like:
```
# serverless.yml
provider:
  name: aws
  logs:
    restApi:
      accessLogging: false
      accessLoggingDestinationArn: streamname | loggroupname #optional
      executionLogging: false
```

**Comment by pgrzesik** [comment]
Thanks for the proposal @Blikingor. I think it could be nicer with a nested property:
```
logs:
    restApi:
      accessLogging:
        enabled: true
        destinationArn: stream ARN | loggroup ARN #optional
      executionLogging: false
```

I think we should either stick to ARNs or if we want to use names, we should be more explicit if it's a name of a stream or log group, otherwise it's impossible to know
