### ISSUE TITLE
API Keys must be strings

### ISSUE THREAD

**Issue by s-nt-s** [serverless/serverless#10890]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

`sls deploy` report error `API Keys must be strings` but apiKey is defined as is described by documentation: https://www.serverless.com/framework/docs/providers/aws/events/apigateway -> Setting API keys for your Rest API -> example myFourthKeyValue

### Service configuration (serverless.yml) content

```yaml
service: ************
plugins:
  - serverless-offline
  - serverless-python-requirements
custom:
  serverless-offline:
    printOutput: true
    noTimeout: true
  pythonRequirements:
    fileName: requirements.txt
    noDeploy:
      - boto3
      - botocore
    usePipenv: false
    dockerizePip: true
    slim: true
    strip: false
    slimPatternsAppendDefaults: false
    slimPatterns:
      - '**/*.py[c|o]'
      - '**/__pycache__*'
    layer:
      compatibleRuntimes:
        - python3.7
package:
  individually: true
  exclude:
    - ".*/**"
    - .svn/**
    - .git/**
    - myenv
    - build/**
    - Pipfile*
    - node_modules/**
    - package*.json
    - debug/**
    - logs/**
    - "*.sh"
    - "*.md"
    - "**/__pycache__/**"
    - "tests/**"
    - "**/*.pyc"
    - "*requirements*.txt"
    - ".dockerignore"
    - ".gitignore"
    - ".*"
    - "docker_*"
    - "tools/**"
provider:
  name: aws
  runtime: python3.7
  region: eu-west-1
  stage: Prod
  apiName: ${self:service}
  stackName: ${self:service}
  timeout: 900
  memorySize: 2048
  environment:
    DB_TARGET: ${env:DB_TARGET}
  apiKeys:
    - value: '************'
      description: 'Bla bla bla'
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
         - "s3:ListBucket"
       Resource: "arn:aws:s3:::xxxxxxx/*"
functions:
  handler_xxxxxxx:
    handler: lambda_handler.handler_xxxxxx
    name: xxxxxx_xxxxxxx_xxxxx
    description: API Gateway xxxxxxx - xxxxx
    events:
      - http:
          path: xxxxxxx-api/xxxxxxxx/xxxxxx
          method: post
          private: true
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  handler_xxxxxx:
    handler: lambda_handler.handler_xxxxxxx
    name: xxxxxxx_xxxxxx_xxxxxx
    description: API Gateway xxxxxxxx - xxxxx
    events:
      - http:
          path: xxxxxxxxx-api/xxxxxxxxxxx/xxxxxxxxx
          method: post
          private: true
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  handler_descriptiva:
    handler: lambda_handler.handler_xxxxxxxx
    name: xxxxxxxxx_xxxxxxx_xxxx
    description: API Gateway xxxxxxx - xxxxxxx
    events:
      - http:
          path: xxxxxx-api/xxx/xxxxxxx
          method: any
          private: true
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
```

### Command name and used flags

SLS_DEBUG=* sls deploy -v

### Command output

```shell
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generated requirements from /home/*********/wks/*********-*********/src/requirements.txt in /home/*********/wks/*********-*********/src/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /home/*********/.cache/serverless-python-requirements/055d55e5a3a5dd9f38b92374ff75c83b97da16ed05f26d6f4212663a44d5a530_x86_64_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Packaging Python Requirements Lambda Layer...
Serverless: Found cached Python Requirements Lambda Layer file
 
  Serverless Error ---------------------------------------
 
  API Keys must be strings
 
  Stack Trace --------------------------------------------
 
ServerlessError: API Keys must be strings
    at /usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js:17:17
    at arrayEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at AwsCompileApigEvents.compileApiKeys (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js:13:9)
From previous event:
    at Object.package:compileEvents [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:62:12)
    at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at Deploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:438:17)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:114:33
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at /usr/local/lib/node_modules/serverless/bin/serverless:43:28
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/*********/wks/*********-*********/src/node_modules/graceful-fs/graceful-fs.js:61:14
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.oncomplete (node:fs:188:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:43:6
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           16.14.2
     Serverless Version:     1.38.0
```

### Environment information

```shell
N/A
```
