### ISSUE TITLE
New deployments fail because stack policy updates are made before changesets are applied

### ISSUE THREAD

**Issue by neverendingqs** [serverless/serverless#10904]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

CloudFormation stack policies can reference resources in the CloudFormation template. However, `update-stack` currently tries to apply stack policies before applying changesets. This means new deployments will always fail because CloudFormation has no knowledge of any resources other than the ones in `cloudformation-template-create-stack.json`:

https://github.com/serverless/serverless/blob/991566f1795beb66d74b24501a168608ba269e4e/lib/plugins/aws/lib/update-stack.js#L94-L110

EDIT: probably worth noting that this can also happen on stack updates, if a new resource is added to the CloudFormation template and added to the stack policy at the same time.

Minimal, reproducible example: https://github.com/neverendingqs/serverless-stack-policy-bug
Proposed solution: https://github.com/serverless/serverless/pull/10903

### Service configuration (serverless.yml) content

```yaml
service: some-service

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stackPolicy:
    - Effect: Allow
      Principal: '*'
      Action: 'Update:*'
      Resource: '*'
    - Effect: Deny
      Principal: '*'
      Action:
        - Update:Replace
        - Update:Delete
      Resource:
        - LogicalResourceId/SomeBucket

package:
  patterns:
    - '!node_modules/**'

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    SomeBucket:
      Type: AWS::S3::Bucket
```

### Command name and used flags

```shell
sls deploy
```

### Command output

```shell
> serverless-stack-policy-bug@0.0.1 sls <redacted>\serverless-stack-policy-bug
> sls "deploy" "--stage" "mtsetest"


Deploying some-service to stage mtsetest (us-east-1)

× Stack some-service-mtsetest failed to deploy (67s)
Environment: win32, node 14.19.0, framework 3.10.0 (local), plugin 6.2.0, SDK 4.3.2
Credentials: Local, "<redacted" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```

### Environment information

```shell
Framework Core: 3.10.0 (local)
Plugin: 6.2.0
SDK: 4.3.2
```
