### ISSUE TITLE
AWS Local Invocation is stuck when rust is panicking

### ISSUE THREAD

**Issue by SerheyDolgushev** [serverless/serverless#10911]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Steps to reproduce:

1. Clone the latest [serverless-rust-example](https://github.com/SerheyDolgushev/serverless-rust-example):
    ```bash
    git clone git@github.com:SerheyDolgushev/serverless-rust-example.git
    cd serverless-rust-example
    ```
2. Install Node.js dependencies:
    ```bash
    npm install --only=dev
    ```
3. Make sure https://github.com/serverless/serverless/pull/10891 is applied to `node_modules/serverless/lib/plugins/aws/invoke-local/index.js`
4. Invoke local rust function in "panic mode":
    ```bash
    npx serverless invoke local -f hello -d '{"panic": true}'
    ```

### Expected result:

The local rust function is invoked with the following output:
```
...
thread 'main' panicked at 'Panic greetings, world!', src/main.rs:22:9
...
```

### Actual result:

The local rust function is stuck. And the only way to fix it is to open a new terminal and manually kill the docker container there:
```
docker stop $(docker ps --filter "ancestor=sls-docker-provided" -q)
```

Expected result is returned once the docker container is killed

### Service configuration (serverless.yml) content

```yaml
service: demo
provider:
    name: aws
    runtime: rust
plugins:
    - serverless-rust
package:
    individually: true
functions:
    hello:
        handler: lambda
custom:
    rust:
        dockerless: true
```

### Command name and used flags

npx serverless invoke local -f hello -d '{"panic": true}'

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.72.3 (local)
Plugin: 5.5.4
SDK: 4.3.2
Components: 3.18.2
```
