### ISSUE TITLE
APIGateway request validator schema name not valid for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by redouane-dev** [serverless/serverless#10938]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

This issue is similar to https://github.com/serverless/serverless/issues/8191, but while using TypeScript with the plugin `serverless-esbuild` and the latest version of the `serverless` CLI.

**index.ts** (lambda handler, see below for the generated template with `sls print`)
```typescript
import schema from './schema';
...
  events: [
    {
      http: {
        path: 'foo',
        method: 'post',
        request: {
          schemas: {
            'application/x-www-form-urlencoded': schema,  // Validation issue here
          },
        },
      },
    },
  ],
 ```
 
 **schema.ts**
 ```typescript
 export default {
  type: 'object',
  properties: {
    baz: {
      type: 'string',
    },
  },
  required: ['baz'],
} as const;
```

### Service configuration (serverless.yml) content

```yaml
org: foo
app: foo
service: foo
frameworkVersion: '3'
plugins:
  - serverless-esbuild
provider:
  name: aws
functions:
  foo:
    handler: src/functions/foo/handler.main
    events:
      - http:
          path: foo
          method: post
          request:
            schemas:
              application/x-www-form-urlencoded:
                type: object
                properties:
                  baz:
                    type: string
                required:
                  - baz
    name: foo
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define: {}
    platform: node
    concurrency: 10
```

### Command name and used flags

sls deploy

### Command output

```shell
sls deploy
Running "serverless" from node_modules

Deploying foo to stage dev
Compiling to node14 bundle with esbuild...
Compiling with concurrency: 10
Compiling completed.
(node:27851) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Zip function: foo - 202.17 KB [83 ms]

✖ Stack foo failed to deploy (12s)

Error:
The CloudFormation template is invalid: Template format error: Resource name ApiGatewayMethodFooFooPostApplicationX Www Form UrlencodedModel is non alphanumeric.
```

### Environment information

```shell
sls --version
Running "serverless" from node_modules
Framework Core: 3.12.0 (local) 3.12.0 (global)
Plugin: 6.2.1
SDK: 4.3.2
```
