### ISSUE TITLE
Event triggers deleted when triggering resource is updated

### ISSUE THREAD

**Issue by gilad-embryonics** [serverless/serverless#10939]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Whenever I make an update to a resource defined in the Resources section, which has associated event triggers, those triggers will be deleted. This happens for both Cognito user pool triggers and S3 bucket notifications, and I assume it would happen for any other type of resource which is defined in the resources section of the yml. This probably happens because the triggers are not part of the compiled CloudFormation template, but rather are configured with a separate script post-template update, only when the event is committed, and not on every deploy.

### Service configuration (serverless.yml) content

```yaml
functions:

  TriggerExample:
    handler: TriggerExample.lambda_handler
    events:
      - s3:
          existing: true
          bucket: !Ref UploadsBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: prefix
            - suffix: suffix

resources:

  Resources:

    UploadsBucket:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
      Type: AWS::S3::Bucket
      Properties:
        BucketName: TriggerExample
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
> npx serverless --version
Framework Core: 3.11.0 (local)
Plugin: 6.2.1
SDK: 4.3.2
```
