### ISSUE TITLE
`file` function doesn't await Promise resolution

### ISSUE THREAD

**Issue by ccatterina** [serverless/serverless#10948]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi,
I've just upgraded the serverless version from v2.41.2 to v3.12.0.
We use an env.js file that loads asynchronously an object with the environment variables to populate the lambda environment.
While this trick worked fine with serverless 2.41.2, with 3.12.0 doesn't work anymore.
It seems that serverless v3 doesn't await the promise resolution.

Is this the expected behaviour?

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from '@serverless/typescript';
import root from 'app-root-path';
import path from 'path';

import importFromFile from './import-from-file';

const serverlessConfiguration: AWS = {
  service: 'import-from-file',
  frameworkVersion: '3',
  custom: {
    modularize: {
      glob: path.relative(__dirname, `${root}/serverless.common.yaml`),
    },
    webpack: {
      webpackConfig: path.relative(__dirname, `${root}/webpack.config.js`),
      packager: 'yarn',
      includeModules: true,
    },
  },
  plugins: ['serverless-webpack', 'serverless-plugin-modularize'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    environment: '${file(env.js):default}' as never,
    lambdaHashingVersion: '20201221',
    iam: {
      role: {
        statements: [
          {
            Effect: 'Allow',
            Action: ['s3:ListBucket'],
            Resource: ['arn:aws:s3:::${ssm:/bucket/assets_hardware_import/id}'],
          },
          {
            Effect: 'Allow',
            Action: ['s3:GetObject'],
            Resource: ['arn:aws:s3:::${ssm:/bucket/assets_hardware_import/id}/*'],
          },
          {
            Effect: 'Allow',
            Action: [
              'iot:CreateThing',
              'iot:DescribeThing',
              'iot:UpdateCertificate',
              'iot:DescribeCertificate',
            ],
            Resource: ['*'],
          },
        ],
      },
    },
    vpc: {
      securityGroupIds: ['${ssm:/networking/default_sg/id}'],
      subnetIds: { 'Fn::Split': [',', '${ssm:/networking/subnets/private/ids}'] },
    },
  },

  functions: { importFromFile },
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

sls print

### Command output

```shell
Environment: darwin, node 14.17.1, framework 3.12.0, plugin 6.2.1, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.ts: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment": Source "file" returned not supported result: "Promise { <pending> }"
```

### Environment information

```shell
Framework Core: 3.12.0
Plugin: 6.2.1
SDK: 4.3.2
```
