### ISSUE TITLE
Add option to retain log group after Lambda function removal

### ISSUE THREAD

**Issue by rdsedmundo** [serverless/serverless#10943]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

This is pretty much what was asked here: https://forum.serverless.com/t/retain-loggroup-after-lambda-function-removal/14333

Having a dedicated configuration would make this easier so it doesn't need to be repeated for every function inside a service in the `resources` section.

When a Lambda is removed, specially in a production environment, it is most of the times desirable to retain its logs for future reference. I could see this being useful both as a service option (applied to all Lambdas) and also an option at the function-level to override it as needed.

### Proposed solution (optional)

```yml
provider:
    retainLogGroupsUponServiceRemoval: true

functions:
    hello-world:
        timeout: 60
        retainLogGroupsUponServiceRemoval: false
    hello-world-2:
        timeout: 60
```
