### ISSUE TITLE
Support "Lambda Function URL" besides httpApi and restApi

### ISSUE THREAD

**Issue by abdennour** [serverless/serverless#10953]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS announced yesterday the GA of AWS Lambda Function URLs: Built-in HTTPS Endpoints for Single-Function Microservices.

REF: https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/

### Proposed solution (optional)

Based on the [announcement](https://aws.amazon.com/blogs/aws/announcing-aws-lambda-function-urls-built-in-https-endpoints-for-single-function-microservices/), I would suggest to implement this feature , so the user can define it in **serverless.yml** as following:

```yaml
provider:
   functionUrls:
      webook1:
          authType: NONE
          cors:
              allowOrigins:
                  - "https://example.com" 
functions:
  myFn:
     handler: handler.index
     events:
        - functionUrl: webook1
    
```
