### ISSUE TITLE
Serverless:   at 'functions.sign_lambda': unrecognized property 'CodeSigningConfigArn'

### ISSUE THREAD

**Issue by yaronbenezra** [serverless/serverless#10957]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless:   at 'functions.sign_lambda': unrecognized property 'CodeSigningConfigArn'

### Service configuration (serverless.yml) content

```yaml
functions:
  sign_lambda:
    handler: lambdas.write_two_s3_sign
    timeout: 900
    role: signLambdaRole
    CodeSigningConfigArn:  ${cf:utils.LambdaCodeSigningConfigArn}
    environment:
      PYTHONPATH: "lib"
```

### Command name and used flags

N/A

### Command output

```shell
"N/A"
```

### Environment information

```shell
2.70
```
