### ISSUE TITLE
fetching ssm parameter

### ISSUE THREAD

**Issue by BilalFakih95** [serverless/serverless#10968]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Actually, there was an issue reported before, https://github.com/serverless/serverless/issues/9597, but it was for an older version and I'm facing the same issue

When I try to deploy, I get this error message

`parameter name: can't be prefixed with "ssm" (case-insensitive). if formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_`

I tried to use plugin serverless-ssm-fetch as a walkaround but it didn't work for me

### Service configuration (serverless.yml) content

```yaml
provider:
    environment:
        REGION: ${self:provider.region}
        RDS_ENDPOINT: ${self:custom.databaseEndpoint}
        RDS_DB_NAME: RecruitmentServicesDB${self:custom.databaseSuffix}
        RDS_DB_USER: ----
        RDS_DB_PASSWORD: ${ssm:${self:custom.platone.project}-infrastructure-dbpassword~true}
```

### Command name and used flags

sls deploy -s <stage-name> --param="priority=1234"

### Command output

```shell
parameter name: can't be prefixed with "ssm" (case-insensitive). if formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

### Environment information

```shell
Framework Core: 3.10.0
Plugin: 6.2.1
SDK: 4.3.2
```
