### ISSUE TITLE
Problem in deploy

### ISSUE THREAD

**Issue by Anshshah-1609** [serverless/serverless#10972]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I tried to run sls deploy command it give me error. I tried to solve this but I can not solve. Please help me with this error. 

### Service configuration (serverless.yml) content

```yaml
service: hello-world
frameworkVersion: '3'
deprecationNotificationMode: error
configValidationMode: off

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: us-east-1

  
plugins:
  - serverless-offline


functions:
  hello:
    handler: ./handler.hello
  hellofunction:
    handler: src/jobs/api.hellofunction
    events:
      - http:
          method: GET
          path: /api/v1
```

### Command name and used flags

sls deploy

### Command output

```shell
**sls deploy**
Running "serverless" from node_modules

Deploying hello-world to stage dev (us-east-1)

✖ Stack hello-world-dev failed to deploy (4s)
Environment: linux, node 17.4.0, framework 3.12.0 (local) 3.12.0v (global), plugin 6.2.1, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

**Error:**
The security token included in the request is invalid.
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.12.0 (local) 3.12.0 (global)
Plugin: 6.2.1
SDK: 4.3.2
```
