### ISSUE TITLE
Can't deploy if app and org are set

### ISSUE THREAD

**Issue by CodySwannGT** [serverless/serverless#10971]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We're trying to move to dashboard deploys, but we're getting the following error when trying to deploy:

````
Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::102041120520:assumed-role/propswap-cody-IamRoleCustomResourcesLambdaExecutio-FFSHRFHBIHKJ/propswap-cody-custom-resource-apigw-cw-role is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-1::/account because no identity-based policy allows the apigateway:GET action See details in CloudWatch Log: 2022/04/14/[$LATEST]4deb8990447d4c64bb46cdfdf983923d (RequestId: ea5a60d7-1190-4a68-809e-18d6620d868d)
````

We added a provider using this method: https://capture.dropbox.com/WjfwmQ76t74rv7hJ

Everything deploys fine until we add the "org" and "app" keys to our serverless.yml. If we remove them, the service deploys just fine again

### Service configuration (serverless.yml) content

```yaml
service: ${self:custom.environment.SERVICE}
variablesResolutionMode: 20210326
org: gunnertech
app: propswap
frameworkVersion: '3'
custom:
  serviceName: ${self:custom.environment.SERVICE}
  accountId: { Ref: AWS::AccountId }
  identifier: ${self:custom.serviceName}-${self:provider.stage}
  environment: ${file(env.yml):${self:provider.stage}}
  region: ${opt:region, self:provider.region}
  prune:
    automatic: true
    number: 3
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  splitStacks:
    perFunction: true
    perType: false

package:
  individually: false

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-plugin-split-stacks
  - serverless-plugin-scripts
  - serverless-cloudformation-sub-variables

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  versionFunctions: false
  stage: ${file(./amplify/stage.js):stage}
  region: ${file(./amplify/config.js):env.aws_project_region, 'us-east-1'}
  environment:
    AWS_ACCOUNT_ID: { Ref: AWS::AccountId }
    SYSTEM_EMAIL_ADDRESS: ${self:custom.environment.SYSTEM_EMAIL_ADDRESS}
    DOMAIN_NAME: ${self:custom.environment.DOMAIN_NAME}
    ERROR_QUEUE_NAME: ${self:custom.environment.ERROR_QUEUE_NAME}
    TABLES: ${self:custom.fileVars.tableNamesJson}
    STAGE: ${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true
```

### Command name and used flags

serverless deploy --stage cody

### Command output

```shell
`
✖ Stack propswap-cody failed to deploy (358s)
Environment: darwin, node 16.13.1, framework 3.13.0 (local) 3.13.0v (global), plugin 6.2.1, SDK 4.3.2
Credentials: Serverless Dashboard, "propswap-cody" provider (https://app.serverless.com/gunnertech/apps/propswap/propswap/cody/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: CustomApiGatewayAccountCloudWatchRole (Custom::ApiGatewayAccountRole)
Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::102041120520:assumed-role/propswap-cody-IamRoleCustomResourcesLambdaExecutio-FFSHRFHBIHKJ/propswap-cody-custom-resource-apigw-cw-role is not authorized to perform: apigateway:GET on resource: arn:aws:apigateway:us-east-1::/account because no identity-based policy allows the apigateway:GET action See details in CloudWatch Log: 2022/04/14/[$LATEST]4deb8990447d4c64bb46cdfdf983923d (RequestId: ea5a60d7-1190-4a68-809e-18d6620d868d)
````
```


### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.13.0 (local) 3.13.0 (global)
Plugin: 6.2.1
SDK: 4.3.2
```
