### ISSUE TITLE
Platform Flag has no effect when running under Github Actions

### ISSUE THREAD

**Issue by jcampbell05** [serverless/serverless#10982]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When specifying a platform for my image it fails to have any effect on Github actions instead being built for linux/amd64 instead of my specified platform.

The image builds fine since it's a multi-arch base image but when ran it fails since the lambda is expecting a arm64 container and gets a amd64.

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  ecr:
    images:
      hdrimage:
        path: ./apps/hdr-merger
        platform: linux/arm64
  region: eu-west-1
functions:
  hdr-merge:
    architecture: arm64
    memorySize: 2048
    timeout: 900
    image:
      name: hdrimage
```

### Command name and used flags

npx sls deploy --stage dev

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.14.0 (local)
Plugin: 6.2.1
SDK: 4.3.2
```
