### ISSUE TITLE
spawn python3.8 ENOENT while serverless deploy

### ISSUE THREAD

**Issue by dj-ash** [serverless/serverless#10994]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When trying to deploy a python based serverless function, this is the error received in serverless deploy step.
The error is found tryint to deploy through github actions as well as circleci - both gave the same issue. 
Environment: linux, node 14.19.1, framework 3.15.0 (local) 3.15.0v (global), plugin 6.2.2, SDK 4.3.2

Error: spawn python3.8 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Node version is 16.x and python is 3.10. Serverless installation was fine using python 3.10.4. Plugin serverless-python-requirements installation was fine too. But the error is thrown in serverless deploy

### Service configuration (serverless.yml) content

```yaml
version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   node: circleci/node@5.0.1
   serverless: circleci/serverless-framework@1.0.1
jobs:
   one:
     docker:
       - image: cimg/python:3.10
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - node/install:
          install-yarn: true
          node-version: '16.13'
       - run: node --version
       - run: npm install
       - serverless/setup
       - run: sudo apt-get update -y
       - run: sudo apt-get install -y poppler-utils
       - run: sudo apt-get install -y python3.8
       - run:
          name: serverless python plugin
          command: sls plugin install -n serverless-python-requirements
       - run: sls deploy
```

### Command name and used flags

serverless deploy

### Command output

```shell
Error: spawn python3.8 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Environment information

```shell
shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.4/x64/lib
Framework Core: 3.15.0
Plugin: 6.2.2
SDK: 4.3.2
```
