### ISSUE TITLE
Could not find module root

### ISSUE THREAD

**Issue by ratasxy** [serverless/serverless#11011]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

After deploying to aws and making the http request I get:

`{"message": "Internal server error"}`

running `sls offline` the service works correctly

this is the error log:

`2022-04-26T17:57:56.485Z f7ba628e-d1b8-4289-b5eb-d0ce50cb1104 ERROR Error: Could not find module root given file: "/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js". Do you have a `package.json` file? at Function.getRoot (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:41665:13) at bindings (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:41536:32) at Object.1389.bindings (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:126819:34) at o (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:1:632) at /var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:1:683 at Object.1851../sanitize.js (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:160511:13) at o (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:1:632) at /var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:1:683 at Object.1848../json2xml (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:160327:18) at o (/var/task/_optimize/ms-affiliate-inretail-dev-main/dist/serverless.js:1:632)`

### Service configuration (serverless.yml) content

```yaml
service: ms-affiliate-inretail
plugins:
  - serverless-offline
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: any
          path: /{any+}

package:
  excludeDevDependencies: false
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.15.2
Plugin: 6.2.2
SDK: 4.3.2
```
