### ISSUE TITLE
Serverless deploy/offline doesn't work with Node.js + Database

### ISSUE THREAD

**Issue by joaocasarin** [serverless/serverless#11024]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

So, Whenever I try to `serverless deploy` - so this is not a plugin related, or `serverless offline` - this is run by a plugin, but deploy doesn't work as well -, and there is some kind of code that connects and/or interacts with a database, such as the usage of an ORM like Typeorm or Prisma for Node.js, I get these errors, and they are cause when I call this function (just an example):

```ts
import { hash } from 'bcrypt';
import { PrismaClient } from '@prisma/client';
import { InputUser, User } from '@models/User';

export const handle = async (user: InputUser): Promise<User | undefined> => {
    const prisma = new PrismaClient();

    try {
        const { name, age, password } = user;
        const hashedPassword = await hash(password, 10);

        const createdUser = await prisma.user.create({
            data: {
                name,
                age,
                password: hashedPassword
            }
        });

        await prisma.$disconnect();

        return createdUser;
    } catch (error) {
        throw Error("Couldn't connect to database.");
    }
};
```

```sh
PS C:\Users\joaov\Desktop\lambda-ts> serverless deploy
Running "serverless" from node_modules

Deploying lambda-ts to stage dev (us-east-1)

┘ Packaging (0s)
X [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove 
  this error. You can also surround this "require" call with a try/catch block to handle this      
  failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this   
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.
× Stack lambda-ts-dev failed to deploy (0s)
Environment: win32, node 16.14.0, framework 3.14.0 (local) 3.14.0v (global), plugin 6.2.1, SDK 4.3.2  
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Build failed with 2 errors:
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28: ERROR: Could not resolve "mock-aws-s3"  
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23: ERROR: Could not resolve "nock"        
    at failureErrorWithLog (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1603:15)
    at C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1249:28
    at runOnEndCallbacks (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1162:65)
    at buildResponseToResult (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1247:7)
    at C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1356:14
    at C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
PS C:\Users\joaov\Desktop\lambda-ts>
```

### Service configuration (serverless.yml) content

```yaml
It's `serverless.ts`:

import 'dotenv/config';
import type { AWS } from '@serverless/typescript';
import {
    NODE_ENV,
    AWS_RDS_POSTGRES,
    AWS_RDS_POSTGRES_DB,
    AWS_RDS_POSTGRES_PASSWORD,
    AWS_RDS_POSTGRES_PORT,
    AWS_RDS_POSTGRES_USER
} from './src/configs/env_vars';

const serverlessConfiguration: AWS = {
    service: 'lambda-ts',
    frameworkVersion: '3',
    plugins: ['serverless-esbuild', 'serverless-offline'],
    provider: {
        name: 'aws',
        stage: 'dev',
        runtime: 'nodejs14.x',
        apiGateway: {
            minimumCompressionSize: 1024,
            shouldStartNameWithService: true
        },
        environment: {
            AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
            NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
            NODE_ENV,
            AWS_RDS_POSTGRES,
            AWS_RDS_POSTGRES_DB,
            AWS_RDS_POSTGRES_PASSWORD,
            AWS_RDS_POSTGRES_PORT,
            AWS_RDS_POSTGRES_USER
        }
    },
    functions: {
        example: {
            handler: 'src/lambdas/CreateUser/index.handler',
            events: [
                {
                    http: {
                        method: 'post',
                        path: 'create-user',
                        cors: {
                            origin: '*'
                        }
                    }
                }
            ]
        }
    },
    package: { individually: true },
    custom: {
        esbuild: {
            bundle: true,
            minify: false,
            sourcemap: true,
            exclude: ['aws-sdk'],
            target: 'node14',
            define: { 'require.resolve': undefined },
            platform: 'node',
            tsconfig: './tsconfig.build.json',
            concurrency: 10
        }
    }
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

serverless deploy

### Command output

```shell
Running "serverless" from node_modules

Deploying lambda-ts to stage dev (us-east-1)

┘ Packaging (0s)
X [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove 
  this error. You can also surround this "require" call with a try/catch block to handle this      
  failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this   
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.
× Stack lambda-ts-dev failed to deploy (0s)
Environment: win32, node 16.14.0, framework 3.14.0 (local) 3.14.0v (global), plugin 6.2.1, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Build failed with 2 errors:
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28: ERROR: Could not resolve "mock-aws-s3"
node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23: ERROR: Could not resolve "nock"
    at failureErrorWithLog (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1603:15)
    at C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1249:28
    at runOnEndCallbacks (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1162:65)
    at buildResponseToResult (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1247:7)
    at C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:1356:14
    at C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Users\joaov\Desktop\lambda-ts\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.14.0 (local) 3.14.0 (global)
Plugin: 6.2.1
SDK: 4.3.2
```
