### ISSUE TITLE
config file not found

### ISSUE THREAD

**Issue by ananthu7025** [serverless/serverless#11031]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

sh -ac " . ./.env.serverless.dev; serverless offline -c start while typing this command an error is comming config file start not found

### Service configuration (serverless.yml) content

```yaml
service: bidbuddy-v001

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${file(./config/env.js):output.ENV}
  versionFunctions: false # optional, default is true
  region: ${file(./config/env.js):output.REGION}

functions: ${file(./config/functions.js)}

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

package:
  individually: true

custom:
  dotenv:
    path: ./.env
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
(node:3332) ExperimentalWarning: queueMicrotask() is experimental.
Serverless: DOTENV: Loading environment variables:
Serverless:      - ENV
Serverless:      - DOUBLECHECK
Serverless:      - DB_PASSWORD
Serverless:      - DB_DATABASE
Serverless:      - DB_HOST
Serverless:      - DB_USER
Serverless:      - REGION
Serverless:      - HASHING_SALT
Serverless:      - SALT_ROUNDS
Serverless:      - TOKEN_DURATION_SECONDS
Serverless:      - CSRF_COOKIE
Serverless:      - DOMAIN
Serverless:      - COOKIE_DOMAIN
Serverless:      - ORIGIN
Serverless:      - origin
Serverless:      - CLIENT_DOMAIN
Serverless:      - SU
Serverless:      - S3_BUCKET
Serverless:      - mail_user
Serverless:      - mail_password
Framework Core: 1.68.0
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
