### ISSUE TITLE
CREATE_FAILED issue with same Custom S3 resource name for function name deployed to two different stages

### ISSUE THREAD

**Issue by ayharano** [serverless/serverless#11037]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I am using serverless 3.16.0 with `aws` provider.

The base of this issue is related to Custom S3 resource, as it requires the `existing: true` option, and deploying the same function name to two different environments. I am trying to deploy a function to two different stages. For the first one, I am able to successfully deploy using

`sls deploy --verbose --stage first`

However, for the second stage (`sls deploy --verbose --stage second`), I am having issues related to the creation of the resource related to the creation of the custom S3 resource, given that `getCustomResourceS3ResourceLogicalId` relies only on the function name, which is the same for both environments ( serverless code snippet: https://github.com/serverless/serverless/blame/bf79934e9b43a0b2e8613ee29f9430fa22c41481/lib/plugins/aws/lib/naming.js#L567-L572 ). In the output, it can be checked as `FuncCustomS31`.

Is there a suggestion, even if it requires a PR to the codebase, to be able to include the stage in the Custom::S3 resource LogicalId naming? I tried to track where that kind of discussion could be done, but I wasn't successful in finding previous discussions.

### Service configuration (serverless.yml) content

```yaml
service: ServiceName
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'stage'}
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:HeadObject
            - s3:GetObject
          Resource:
            - 'arn:aws:s3:::outputbucketname/anotherprefix/*'

package:
  individually: true
  patterns:
    - "!**"
    - '!.venv/**'
    - '!node_modules/**'
    - '!Makefile'
    - '!package-lock.json'
    - 'src/*.py'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    useDownloadCache: true
    useStaticCache: true

functions:
  func:
    handler: src.lambda.lambda_handler
    events:
      - s3:
          bucket: inputbucketname
          event: s3:ObjectCreated:*
          rules:
            - prefix: aprefix/
            - suffix: .json
          existing: true
```

### Command name and used flags

SLS_DEBUG=* sls deploy --verbose --stage second

### Command output

```shell
Deploying ServiceName to stage second (us-east-1)

Packaging
Generated requirements from /Users/user/repo/requirements.txt in /Users/user/repo/.serverless/requirements.txt
Using static cache of requirements found at /Users/user/Library/Caches/serverless-python-requirements/58a5ac7ff4d5bd2d85befc12c11e1c0a7636c96d31231b2fb169c7aa166957c2_x86_64_slspyc
Excluding development dependencies for function "func"
Injecting required Python packages to package
Generating custom CloudFormation resources
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service func.zip file to S3 (11.18 MB)
Uploading custom CloudFormation resources
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - ServiceName-second
  CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
  CREATE_IN_PROGRESS - AWS::Logs::LogGroup - FuncLogGroup
  CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
  CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
  CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
  CREATE_IN_PROGRESS - AWS::Logs::LogGroup - FuncLogGroup
  CREATE_COMPLETE - AWS::Logs::LogGroup - FuncLogGroup
  CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
  CREATE_COMPLETE - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
  CREATE_IN_PROGRESS - AWS::Lambda::Function - FuncLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Function - FuncLambdaFunction
  CREATE_COMPLETE - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
  CREATE_COMPLETE - AWS::Lambda::Function - FuncLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - FuncLambdaVersionyoBUNcrOcnGfBHFKTUppGdUINudLNo9iuIjBZQxxkg
  CREATE_IN_PROGRESS - Custom::S3 - FuncCustomS31
  CREATE_IN_PROGRESS - AWS::Lambda::Version - FuncLambdaVersionyoBUNcrOcnGfBHFKTUppGdUINudLNo9iuIjBZQxxkg
  CREATE_COMPLETE - AWS::Lambda::Version - FuncLambdaVersionyoBUNcrOcnGfBHFKTUppGdUINudLNo9iuIjBZQxxkg
  CREATE_IN_PROGRESS - Custom::S3 - FuncCustomS31
  CREATE_FAILED - Custom::S3 - FuncCustomS31
  UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - ServiceName-second
  UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - ServiceName-second
  DELETE_SKIPPED - AWS::Lambda::Version - FuncLambdaVersionyoBUNcrOcnGfBHFKTUppGdUINudLNo9iuIjBZQxxkg
  DELETE_IN_PROGRESS - AWS::CloudFormation::CustomResource - FuncCustomS31
  DELETE_FAILED - AWS::CloudFormation::CustomResource - FuncCustomS31
  DELETE_IN_PROGRESS - AWS::Lambda::Function - FuncLambdaFunction
  DELETE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
  DELETE_COMPLETE - AWS::Lambda::Function - FuncLambdaFunction
  DELETE_IN_PROGRESS - AWS::Logs::LogGroup - FuncLogGroup
  DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
  DELETE_COMPLETE - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
  DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
  DELETE_COMPLETE - AWS::Logs::LogGroup - FuncLogGroup
  DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
  DELETE_COMPLETE - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
  DELETE_IN_PROGRESS - AWS::CloudFormation::CustomResource - FuncCustomS31
  DELETE_COMPLETE - AWS::CloudFormation::CustomResource - FuncCustomS31
  UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - ServiceName-second

✖ Stack ServiceName-second failed to deploy (317s)
Environment: darwin, node 14.19.1, framework 3.16.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: FuncCustomS31 (Custom::S3)
Received response status [FAILED] from custom resource. Message returned: Unable to validate the following destination configurations See details in CloudWatch Log: 2022/05/05/[$LATEST]... (RequestId: ...)

View the full error: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-...
```

### Environment information

```shell
Framework Core: 3.16.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
