### ISSUE TITLE
CREATE_FAILED: WebLambdaPermissionFnUrl (AWS::Lambda::Permission)

### ISSUE THREAD

**Issue by tillkruss** [serverless/serverless#11053]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

A brand new deployment fails with:

```
CREATE_FAILED: WebLambdaPermissionFnUrl (AWS::Lambda::Permission)

Cannot find alias arn: arn:aws:lambda:us-east-1:674190564649:function:example-preview-web:provisioned (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: f1bc3ec4-0a8d-4874-976a-c3a96e4c50fb; Proxy: null)
```

### Service configuration (serverless.yml) content

```yaml
service: example
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  profile: example
  runtime: provided.al2
  deploymentBucket:
    name: ${param:bucket}
  tags:
    sls: 'example'
  environment:
    APP_URL: ${param:appUrl}
    ASSET_URL: https://${param:assetsBucket}/${sls:instanceId}

plugins:
  - ./vendor/bref/bref
  - serverless-s3-sync
  - serverless-plugin-git-variables

params:
  default:
    bucket: example.com
    assetsBucket: assets.example.com
  production:
    appUrl: https://example.com
  preview:
    appUrl: https://preview.example.com

functions:
  web:
    handler: public/index.php
    url: true
    timeout: 10
    provisionedConcurrency: 5
    layers:
      - ${bref:layer.php-81-fpm}
    events:
      - httpApi: '*'

package:
  patterns:
    - "!.*/**"
    - '!node_modules'
    - '!public/assets'
    - '!public/storage'
    - '!public/vendor'
    - '!resources/css'
    - '!resources/js'
    - '!storage/framework'
    - '!storage/logs'
    - '!tests'
    - '!package-lock.json'
    - '!README.md'

custom:
  gitVariablesEnvWhitelist: ['GIT_COMMIT_SHORT']
  s3Sync:
    - bucketName: ${param:assetsBucket}
      bucketPrefix: ${sls:instanceId}/
      localDir: public/assets
```

### Command name and used flags

sls deploy -s preview

### Command output

```shell
sls deploy -s preview                                                                                                                                                  ✔  9s   13:42:30 
Running "serverless" from node_modules

Deploying example to stage preview (us-east-1)

✖ Stack example-preview failed to deploy (80s)
Environment: darwin, node 18.0.0, framework 3.16.0 (local) 3.16.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "example" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: WebLambdaPermissionFnUrl (AWS::Lambda::Permission)
Cannot find alias arn: arn:aws:lambda:us-east-1:674190564649:function:example-preview-web:provisioned (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: f1bc3ec4-0a8d-4874-976a-c3a96e4c50fb; Proxy: null)

View the full error: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A674190564649%3Astack%2Fexample-preview%2Fa71e9e50-cfd8-11ec-a735-0a059be1a6d5
```

### Environment information

```shell
Framework Core: 3.16.0 (local) 3.16.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
