### ISSUE TITLE
Expose RetryPolicy parameter on scheduled function events object

### ISSUE THREAD

**Issue by adrianoesch** [serverless/serverless#11051]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I'd like to trigger a lambda function by schedule without retries on failure like this:

```yaml
myFunction:
  events:
    - schedule: 
         rate: cron(30 4 * * ? *)
         retryPolicy:
            maximumRetryAttempts: 0
```

### Proposed solution (optional)

Expose `retryPolicy` Parameter to function schedule object similar to [EventBus](https://github.com/serverless/serverless/issues/8625).

**Comment by pgrzesik** [comment]
Hello @adrianoesch, thanks a lot for submitting the proposal. I think it makes sense to support such notation, mirroring the one supported for `eventBridge` event type 👍 If you'd be interested, we'd love to accept a PR for this 👍

**Comment by adrianoesch** [comment]
Great, I'll have a go at it.

**Comment by mnapoli** [comment]
Are you sure you don't want to use https://www.serverless.com/framework/docs/providers/aws/guide/functions#maximum-event-age-and-maximum-retry-attempts instead?

From what I understand:

1. EventBridge invokes Lambda asynchronously: this is where the EventBridge redrive policy comes into play. What could go wrong is limited (to my knowledge), e.g. a permission issue, or the Lambda service completely down.
2. Then the async event is in Lambda, and Lambda invokes your function: this is where the Function retry attempts come into play. This is what retries your code if it throws an error.

It seems you want to add support for 1., but you actually want 2. and it already exists?

**Comment by adrianoesch** [comment]
Not sure either, I think I haven't fully grasped the difference between the events schedule and EventBridge configuration options yet. I can try to give a bit more context. One of my functions that sends a bunch of emails to staff recently ran into the timeout, whereby triggering two subsequent retries. This resulted in 3 emails sent to the first bunch of addresses that were delivered before the timeout kicked it. Here's my config: 

```yml
functions:
  myFunction:
    image:
      name: xxx
    timeout: 300
    memorySize: 256
    events:
      - schedule:
          rate: cron(30 4 * * ? *)
          input:
            type: emails.send
```

Obviously, I could add some checks in the function to make sure this doesn't happen again. But I thought it would also be neat to just restrict the RetryPolicy with the `maximumRetryAttempts` parameter that AWS exposes ([afaik](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html)). As far as I understand, the `schedule` object in the serverless config is building an EventBridge Rule anyway under the hood. At least that's what I noticed in the AWS console.

**Comment by adrianoesch** [comment]
I see, makes sense... I noticed that the EventBridge rule has the parameter `maximumRetryAttempts` set to 185 by default anyway. So this part was actually delivered successfully, but within lambda the errors lead to repeated attempts. So the solution here is to set the `maximumRetryAttempts` at function object and not the event schedule object like this:

```yml
functions:
  myFunction:
    image:
      name: xxx
    timeout: 300
    maximumRetryAttempts: 0
    memorySize: 256
    events:
      - schedule:
          rate: cron(30 4 * * ? *)
          input:
            type: emails.send
``` 

Thanks for your explanations! Do you want me to try to clarify the relationship between function events and `maximumRetryAttempts` in the docs [here](https://www.serverless.com/framework/docs/providers/aws/guide/functions#asynchronous-invocation)? I think expanding the example with a scheduled event would have helped me in this case.
