### ISSUE TITLE
configuration - Property ephemeralStorageSize unrecognize

### ISSUE THREAD

**Issue by s-pace** [serverless/serverless#11050]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

It seems that the property `ephemeralStorageSize` is not recognized from `serverless.yml` while being expose from both serverless & AWS documentation.

It should have been introduced from :
https://github.com/serverless/serverless/pull/10901

You can see the warning I got:
![image](https://user-images.githubusercontent.com/32097720/167431771-d99c4e7a-fbba-4d25-b03a-c9ec9a063d16.png)

# References:
- https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml
- https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html#configuration-ephemeral-storage

Let me know if I can help

### Service configuration (serverless.yml) content

```yaml
functions:
  downloadRecording:
    name: downloadRecording
    # Configure the size of ephemeral storage available to your Lambda function (in MBs, default: 512)
    ephemeralStorageSize: 8000
```

### Command name and used flags

serverless print

### Command output

```shell
Serverless: Configuration warning at 'functions.downloadRecording': unrecognized property 'ephemeralStorageSize'
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 2.72.3 (local)
Plugin: 5.5.4
SDK: 4.3.2
Components: 3.18.2
```
