### ISSUE TITLE
package patterns not exluding files and folders

### ISSUE THREAD

**Issue by dmtzs** [serverless/serverless#11054]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Im using package patterns like in the documentation so I can ignore the folders and files that I dont want to be uploaded to the lambda function. However this doesnt work and that files that shouldnt be uploaded are uploaded still. Am I missing something?
That fragment of my yml file is like below:
```yml
functions:
  hello2:
    name: personal_name_function2
    package:
          patterns:
            - '!./node_modules/**'
            - '!package.json'
            - '!package-lock.json'
            - '!script.py'
            - '!Notas.txt'
            - '!requirements.txt'
            - '!libraries/**'
            - '!github/**'
```

### Service configuration (serverless.yml) content

```yaml
functions:
  hello2:
    name: personal_name_function2
    package:
          patterns:
            - '!./node_modules/**'
            - '!package.json'
            - '!package-lock.json'
            - '!script.py'
            - '!Notas.txt'
            - '!requirements.txt'
            - '!libraries/**'
            - '!github/**'
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
3.16.0
```

**Comment by pgrzesik** [comment]
Hello @dmtzs - could you please share a minimal reproducible example for your case, ideally in form of a small Github repo? Are you using individual packaging?

**Comment by Harshil-Modi** [comment]
@pgrzesik I'm facing the same issue as well. Here is my template

```yml
service: project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64

custom:
  jetpack:
    concurrency: 15
  splitStacks:
    nestedStackCount: 50
    perFunction: false
    perType: false
    perGroupFunction: false

plugins:
  - serverless-jetpack
  - serverless-plugin-split-stacks

package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - '!*/**'
    - '!*.json'

functions:
  hello:
    handler: ./functions/hello.handler
    package:
      patterns:
        - ./functions/hello.js
```

I tried `!*/**` and `!*.json` patterns separately, but no good luck!

This is how I am organizing my files.
```txt
.
├── config.json
├── email-templates
│   ├── cognito-login-credentials.html
│   └── cognito-password-reset.html
├── functions
│   └── hello.js
├── graphql
│   └── helloworld.schema.graphql
├── layers
│   └── static
│       └── nodejs
│           └── package.json
├── mapping-templates
│   ├── Query.HelloWorld.request.js
│   └── Query.HelloWorld.response.js
├── package.json
├── package-lock.json
├── README.md
├── resources
│   └── cognito
│       ├── userpool-client.yml
│       ├── userpool-domain.yml
│       └── userpool.yml
├── scripts
│   └── npm-postinstall.js
├── serverless.appsync.yml
├── serverless.yml
└── stacks-map.js
```
