### ISSUE TITLE
apigateway dynamodb proxy unable to add response template

### ISSUE THREAD

**Issue by pulomi** [serverless/serverless#11064]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [ ] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

although adding request template works fine , but when adding response template , getting following error 

Error:
**child "dynamodb" fails because ["response" is not allowed]**

### Service configuration (serverless.yml) content

```yaml
custom:
  productsTableName: 'products-${self:provider.stage}'
  apiGatewayServiceProxies:
    - dynamodb:
        path: /v2/dynamodb/{partnerId}
        method: post
        request:
          template:
            application/json : ${file(./templates/postRequestTemplate.txt)}
        response:
          - statusCode: 202
            selectionPattern: '2\\d{2}'
            responseTemplates:
              application/json: ${file(./templates/postResponseTemplate.txt)}
        tableName: ${self:custom.productsTableName}
        hashKey:
          pathParam: requestId
          attributeType: S
        rangeKey: # required if also using sort key. set pathParam or queryStringParam.
          pathParam: partnerId
          attributeType: S
        action: PutItem # specify action to the table what you want
```

### Command name and used flags

sls deploy

### Command output

```shell
Error:
**child "dynamodb" fails because ["response" is not allowed]**
```

### Environment information

```shell
Environment: win32, node 16.13.1, framework 3.16.0 (local) 3.8.0v (global), plugin 6.2.2, SDK 4.3.2
```
