### ISSUE TITLE
⠦ [Webpack] Watch service... Console (animation) cuts out console.log/s

### ISSUE THREAD

**Issue by naretini** [serverless/serverless#11092]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

What is the current behavior?
I'm using webpack (watch mode enabled) along with serverless framework and serverless.offline, serverless-webpack plugins
Runtime Nodejs w/ Typescript.

If the current behavior is a bug, please provide the steps to reproduce.
When I test locally my serverless app executing on console:
sls offline start

I see the following  message(animation) on the console (since I updated serverless to latest):
⠦ [Webpack] Watch service... ( dots are animated )

While the app is running and I starts logging, webpack watch service message might refresh

When webpack watch is polling for changes this message will be rewritten on the log tail, overwriting last lines on my console logs.
Preventing me to see latest log information.

### Service configuration (serverless.yml) content

```yaml
serverless.yml : N/A


webpack.config.js file:

const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  context: __dirname,
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: slsw.lib.webpack.isLocal ? 'cheap-module-source-map' : 'source-map',
  resolve: {
    extensions: ['.mjs', '.json', '.ts'],
    symlinks: false,
    cacheWithContext: false,
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.(tsx?)$/,
        loader: 'ts-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
        options: {
          transpileOnly: true,
          experimentalWatchApi: false,
        },
      },
    ],
  },
  watchOptions: {
    poll: 1000,
    ignored: ["node_modules"]
  }
};
```

### Command name and used flags

sls offline start

### Command output

```shell
⠦ [Webpack] Watch service...
```

### Environment information

```shell
Framework Core: 3.12.0 (local) 3.2.0 (global)
Plugin: 6.2.2
SDK: 4.3.2


package.json :
"serverless": "~3.12.0",
"serverless-offline": "^8.5.0",
"serverless-webpack": "^5.6.1"
```
