### ISSUE TITLE
Serverless framework does not attach permissionBoundary on IAM role created by ApiGatewayCloudwatchRole custom resource

### ISSUE THREAD

**Issue by pmilliotte** [serverless/serverless#11108]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

This issue follows discussion in #6134.

As described in https://github.com/serverless/serverless/blob/main/docs/providers/aws/guide/iam.md#at-glance, it is possible to specify a `permissionBoundary` on all IAM roles created by the framework. However the current implementation of ApiGatewayCloudwatchRole custom resource does not use this value to specify a permission boundary.

This is problematic if we restrain any IAM role creation with the following permissionBoundary:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "ForcePermissionBoundary",
      "Effect": "Deny",
      "Action": [
        "iam:CreateRole"
      ],
      "Resource": "*",
      "Condition": {
        "StringNotEquals": {
          "iam:PermissionsBoundary": [
            "arn:aws:iam::XXXXXX:policy/policyName"
          ]
        }
      }
    }
  ]
}
```

One solution could be adding the use of the permissionBoundary property specified in serverless.yml, in the following lines of code: [https://github.com/serverless/serverless/blob/9eae9652bdfca78eeb29bc4e9dfd4f8a1212[…]tom-resources/resources/api-gateway-cloud-watch-role/handler.js](https://github.com/serverless/serverless/blob/9eae9652bdfca78eeb29bc4e9dfd4f8a12125d56/lib/plugins/aws/custom-resources/resources/api-gateway-cloud-watch-role/handler.js#L42-L57)

### Service configuration (serverless.yml) content

```yaml
service: service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  logs:
    restApi: true
  iam:
    role:
      permissionBoundary: arn:aws:iam::XXXXXX:policy/policyName

functions:
  hello:
    handler: handler.hello

resources:
  extensions:
    IamRoleCustomResourcesLambdaExecution:
      Properties:
        PermissionsBoundary: arn:aws:iam::XXXXXX:policy/policyName
```

### Command name and used flags

serverless deploy

### Command output

```shell
Error:
CREATE_FAILED: CustomApiGatewayAccountCloudWatchRole (Custom::ApiGatewayAccountRole)
Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::XXXXXX:assumed-role/stackName-IamRoleCustomResourcesLambdaExecutio-1AVUF1MP7QH5N/stackName-custom-resource-apigw-cw-role is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::XXXXXX:role/serverlessApiGatewayCloudWatchRole with an explicit deny in a permissions boundary
```

### Environment information

```shell
Framework Core: 3.7.2 (local)
Plugin: 6.1.5
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hello @pmilliotte - thanks a lot for reporting.

I'm not sure about applying `permissionBoundary` automatically to this role as we're not applying all other properties to it as well (.e.g we don't add `managedPolicies` or `statements` to it automatically). But I see how that can be problematic.

What do you think @mnapoli @medikoo ?

**Comment by pmilliotte** [comment]
Thanks for replying @pgrzesik.

I understand your concerns. As the role is relevant to API Gateway, another solution could be specifically setting a permissionBoundary property in the provider.apiGateway section of the serverless configuration file, for example:

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  runtime: nodejs14.x
  logs:
    restApi: true
  apiGateway:
    serviceRole:
      permissionBoundary: arn:aws:iam::XXXXXX:policy/policyName
```

And apply it in  [https://github.com/serverless/serverless/blob/9eae9652bdfca78eeb29bc4e9dfd4f8a1212[…]tom-resources/resources/api-gateway-cloud-watch-role/handler.js](https://github.com/serverless/serverless/blob/9eae9652bdfca78eeb29bc4e9dfd4f8a12125d56/lib/plugins/aws/custom-resources/resources/api-gateway-cloud-watch-role/handler.js#L42-L57)

**Comment by rtolar** [comment]
I get this issue if I try to enable API Gateway logging with a permission boundary similar to the OP's in place.

e.g.

```
provider:
  name: aws
  runtime: python3.8
  timeout: 25
  lambdaHashingVersion: 20201221

  # enable API Gateway logging. 
  # THESE LINES BELOW fail 
  logs:
    restApi: true
```

Adding the 'logs.restApi: true' lines leads to an error:
> serverless deploy --stage test --region us-east-2

An error occurred: IamRoleCustomResourcesLambdaExecution - API: iam:CreateRole User: arn:aws:sts::XXXXXX:assumed-role/terraform_role/gitlab001 is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::XXXXXX:role/myfunction-IamRoleCustomResourcesLambdaExecut-XXXXXXXX with an explicit deny in a permissions boundary.

serverless -v
Framework Core: 2.72.2 (standalone)
Plugin: 5.5.4
SDK: 4.3.1
Components: 3.18.2
