### ISSUE TITLE
Configuration validation fails when I use Fn::Join

### ISSUE THREAD

**Issue by hughescr** [serverless/serverless#11109]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have the following serverless.yml snippet:

`
...
provider:
  environment:
    DB_TABLE:
      Fn::Select:
        - 1
        - Fn::Split:
          - '/'
          - { Fn::GetAtt: [ DBTable, Arn ] }
...
`

This is perfectly valid (and works); it should set the DB_TABLE environment variable provided to my lambda's environment to the name of the (dynamodb) table I'm creating in a resource further down in the config. Depending on how I deploy, this table name changes so that each stage can have its own separate table. I pass this to code via the environment variable.  As I say, this works find, Cloudformation doesn't complain, the table name properly shows up in the deployed lambda, code runs great.  However, the serverless configuration validation says:

`
Warning: Invalid configuration encountered
  at 'provider.environment.DB_TABLE': unsupported object format
`

...which is wrong. In general, any configuration option that validates for a string, should allow a function which will return a string.

### Service configuration (serverless.yml) content

```yaml
org: hughescr
app: zoom-attendee-webhook
# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com

service: Zoom-Attendee-Webhook
configValidationMode: warn

provider:
  name: aws
  # These values are defaults, and can be over-written in each function below
  architecture: arm64
  runtime: nodejs16.x
  memorySize: 256
  timeout: 10
  region: us-west-2
  versionFunctions: false
  stage: ${opt:stage, 'PV'}

  environment:
    # DB_TABLE used by code to store/retrieve data in DynamoDB
    DB_TABLE:
      Fn::Select:
        - 1
        - Fn::Split:
          - '/'
          - { Fn::GetAtt: [ DBTable, Arn ] }

  stackTags:
    Organization: ${param:ORGANIZATION_NAME}
    Project: 'Zoom Attendees'

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - { Fn::GetAtt: [ DBTable, Arn ] }
            - Fn::Join:
              - /
              -
                - { Fn::GetAtt: [ DBTable, Arn ] }
                - index/*

functions:

  webhook:
    handler: index.handleWebhook
    events:
      - httpApi: POST /hook

resources:
  Resources:
    DBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName:
          Fn::Join: [ '' , [ '${param:SHORT_PREFIX}', 'WebinarAttendees' ] ]
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: MeetingID
            AttributeType: N
          - AttributeName: ParticipantID
            AttributeType: S
        KeySchema:
          - AttributeName: MeetingID
            KeyType: HASH
          - AttributeName: ParticipantID
            KeyType: RANGE
```

### Command name and used flags

serverless print

### Command output

```shell
Warning: Invalid configuration encountered
  at 'provider.environment.DB_TABLE': unsupported object format

Learn more about configuration validation here: http://slss.io/configuration-validation

[....and then the config]
```

### Environment information

```shell
Framework Core: 3.18.1 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
