### ISSUE TITLE
Renaming a function does not account for existing log groups

### ISSUE THREAD

**Issue by shadowhand** [serverless/serverless#11117]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I renamed a function from `cron-eligibility` to `CronEligibility` (to avoid CF naming like "cronDashEligibility") and got this error:

```
Error:
CREATE_FAILED: CronEligibilityLogGroup (AWS::Logs::LogGroup)
/aws/lambda/dev-cron-eligibility already exists in stack [redacted]
```

### Service configuration (serverless.yml) content

```yaml
service: dev

plugins:
  - ./vendor/bref/bref

provider:
  region: us-west-2
  name: aws
  stackName: ${self:service}
  apiName: ${self:provider.stackName}
  memorySize: 1024
  runtime: provided.al2
  stage: ${env:STAGE, 'dev'}
  iam:
    role: ${self:custom.config.IAMUser}

functions:
  CronEligibility:
    name: ${self:provider.stackName}-cron-eligibility
    handler: Acme\Fn\CronUpdateEligibility
    timeout: 900
    layers:
      - ${bref:layer.php-81}
    events:
      - schedule:
          rate: cron(0 23 ? * FRI *) # Every Friday @ 11PM UTC
          input:
            bucket: ${env:STACKID}-uploads
```

### Command name and used flags

sls deploy --verbose -s dev

### Command output

```shell
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service dev.zip file to S3 (12.07 MB)
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - dev
  CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CronEligibilityLogGroup
  CREATE_FAILED - AWS::Logs::LogGroup - CronEligibilityLogGroup
  UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - dev
  UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - dev
  DELETE_COMPLETE - AWS::Logs::LogGroup - CronEligibilityLogGroup

✖ Stack dev failed to deploy (93s)
Environment: darwin, node 16.15.0, framework 3.18.2 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: CronEligibilityLogGroup (AWS::Logs::LogGroup)
/aws/lambda/careops-qa-quality-assurance-cron-eligibility already exists in stack arn:aws:cloudformation:us-west-2:104566035342:stack/careops-qa-quality-assurance/f17c24e0-ee2f-11ea-a4af-0262d35609f5

View the full error: https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-west-2%3A104566035342%3Astack%2Fdev%2Ff17c24e0-ee2f-11ea-a4af-0262d35609f5
```
```


### Environment information

```shell
Framework Core: 3.18.2 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
```
