### ISSUE TITLE
Provider.region cannot resolve in Serverless Dashboard

### ISSUE THREAD

**Issue by mataide** [serverless/serverless#11113]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless cannot resolve the region if org and app are applied.
But it works properly if both information is removed.

### Service configuration (serverless.yml) content

```yaml
org: faktura
app: acs-ext-adapter
service: acs-ext-adapter

provider:
  name: aws
  runtime: nodejs14.x
  tracing:
    lambda: true
  stage: ${opt:stage, 'v1'}
  profile: ${self:custom.profiles.${param:PROFILE}}
  region: ${self:custom.regions.${param:PROFILE}}
```
```


### Command name and used flags

sls deploy --stage dev --param="PROFILE=dev"

### Command output

```shell
Error:
Cannot resolve serverless.yml: "provider.region" property is not accessible (configured behind variables which cannot be resolved at this stage)
```
```


### Environment information

```shell
Environment: win32, node 14.19.0, framework 3.16.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```
