### ISSUE TITLE
Unable to create Lambda Function using server less from Bamboo build tool

### ISSUE THREAD

**Issue by ae07177** [serverless/serverless#11112]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I can install Lambda Function using server less cli from a docker locally

Where as if I use the same docker image from bamboo build tool I get the below error, when it invokes "serverless deploy --verbose" command.

25-May-2022 16:27:26 | ✔ Plugin "serverless-python-requirements" installed  (31s)
-- | --
25-May-2022 16:27:27 | Running "serverless" from node_modules
25-May-2022 16:27:32 |  
25-May-2022 16:27:32 | Deploying XXXXX to stage dev (ap-south-1)
25-May-2022 16:27:32 |  
25-May-2022 16:27:32 | Generated requirements from /workspace/master/api_health_lambda/requirements.txt in /workspace/master/api_health_lambda/.serverless/requirements.txt
25-May-2022 16:27:32 | Installing requirements from "/root/.cache/serverless-python-requirements/993a177f330b98d5c2189d004569e1d1bfd60a5874e541041bc3c2d19b870b7b_x86_64_slspyc/requirements.txt"
25-May-2022 16:27:32 | Using download cache directory /root/.cache/serverless-python-requirements/downloadCacheslspyc
25-May-2022 16:27:33 | Running ...
25-May-2022 16:27:34 | Stdout:
**_25-May-2022 16:27:34 | Stderr: ERROR: Can not combine '--user' and '--target'_**

### Service configuration (serverless.yml) content

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: grafana-app-status
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-south-1
  profile: default
  timeout: 10
  memorySize: 128
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
        - health:Describe*
        Resource: "*"
  environment:
     REGION_NAME: ${self:provider.region}
     routing_key: XXX
     chk_svcs: "xx,yy"
     chk_rgns: "us-east-1,us-east-2,us-west-1,us-west-2"

custom:
  pythonRequirements:
   dockerizePip: false

functions:
  f1:
    handler: handler.f1
    events:
      - schedule:
          rate: rate(1 minute)
  f2:
    handler: handler.f2
    events:
      - schedule:
          rate: rate(1 minute)
  f3:
    handler: handler.f3
    events:
      - schedule:
          rate: rate(1 minute)

plugins:
  - serverless-python-requirements
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
25-May-2022 16:27:34 | Stderr: ERROR: Can not combine '--user' and '--target'
```

### Environment information

```shell
dev
```
