### ISSUE TITLE
Order of schedule event triggers cannot be changed when name is specified

### ISSUE THREAD

**Issue by rdsedmundo** [serverless/serverless#11129]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

If I have some existing triggers and add one in the middle (which is nice for grouping/organization), it throws an error saying that some triggers already exist because Serverless Framework apparently is trying to recreate them thinking they are new, but because of the custom names it fails.

I suspect it's related to the sequentiality on the Logical IDs of the CloudFormation resources created for the triggers. They're in the form of `LambdaNameEventsRuleSchedule#`.

### Service configuration (serverless.yml) content

**Before**
```yaml
service: test-edmundo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          name: first_trigger
          rate: cron(30 21 * * ? *)
      - schedule:
          name: second_trigger
          rate: rate(5 minutes)
```

**After**
```
service: test-edmundo
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          name: first_trigger
          rate: cron(30 21 * * ? *)
      - schedule:
          name: third_trigger
          rate: cron(00 21 * * ? *)
      - schedule:
          name: second_trigger
          rate: rate(5 minutes)
```

### Command name and used flags

serverless deploy --stage development

### Command output

```shell
Deploying test-edmundo to stage development (us-east-1)

✖ Stack test-edmundo-development failed to deploy (112s)
Environment: darwin, node 16.15.0, framework 3.19.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: HelloEventsRuleSchedule3 (AWS::Events::Rule)
second_trigger already exists in stack arn:aws:cloudformation:us-east-1:[REDACTED]:stack/test-edmundo-development/a6bcfcc0-e2a4-11ec-9269-1293a31ac441
```

### Environment information

```shell
Framework Core: 3.19.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
