### ISSUE TITLE
Problem sls deploy

### ISSUE THREAD

**Issue by Juanmadepalacios** [serverless/serverless#11124]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Good day. I am writing because I am having a problem implementing serverless deploy, before making the Api Gateway we had no problems executing the sls deploy command.
The error I'm getting when executing the command is: "Cannot deploy to console: Unable to retrieve token (403: {"message":"Forbidden"})" . I hope you can help me, thank you very much

### Service configuration (serverless.yml) content

```yaml
org: juanma36
console: true
service: web-api

custom:
  secrets: ${file(secrets.json)}
  dotenv:
    path: .env

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: ${self:custom.secrets.NODE_ENV}
  profile: default
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
    AWS_BUCKET_NAME: ${self:custom.secrets.AWS_BUCKET_NAME}
    AWS_SECRET_ACCESS_KEY: ${self:custom.secrets.AWS_SECRET_ACCESS_KEY}
    AWS_ACCESS_KEY_ID: ${self:custom.secrets.AWS_ACCESS_KEY_ID}
    HUBSPOT_APIKEY_KEY: ${self:custom.secrets.HUBSPOT_APIKEY_KEY}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}
      - ${self:custom.secrets.SUBNET4_ID}

plugins:
  - serverless-offline

functions:
  healthCheck:
    handler: services/Note/handler.healthCheck
    events:
      - http:
          path: /
          method: get
          cors: true
```

### Command name and used flags

sls deploy

### Command output

```shell
$ sls deploy
Running "serverless" from node_modules

Deploying web-api to stage api (us-east-1)

× Stack web-api-api failed to deploy (7s)
Environment: win32, node 16.13.2, framework 3.17.0 (local) 3.18.2v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot deploy to the Console: Cannot retrieve token (403: {"message":"Forbidden"})
```

### Environment information

```shell
Framework Core: 3.17.0 (local) 3.18.2 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
