### ISSUE TITLE
Error: spawn python3.8 ENOENT - Serverless Github Action

### ISSUE THREAD

**Issue by bertrand-warot-ejara** [serverless/serverless#11122]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Looks like this other issue, but not same cause. https://github.com/serverless/serverless/discussions/10996

I am trying to deploy a serverless function to AWS Lambda using the framework + serverless-python-requirements plugin with Github Actions 

Works fine on my computer.

Get error:
Error: spawn python3.8 ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Service configuration (serverless.yml) content

```yaml
service: cs-telegram-bot

provider:
  name: aws
  architecture: arm64
  memorySize: 128
  runtime: python3.8
  stage: ${env:WORKING_ENVIRONMENT}
  region: us-east-2
  deploymentBucket:
    name: ejara-data-serverless-deployment-artifacts
  environment:
    WORKING_ENVIRONMENT: ${env:WORKING_ENVIRONMENT}
    CLICKUP_CS_CHATBOT_ACCESS_TOKEN: ${env:CLICKUP_CS_CHATBOT_ACCESS_TOKEN}
    CLICKUP_CS_CHAT_TICKET_LIST_ID: ${env:CLICKUP_CS_CHAT_TICKET_LIST_ID}
    TELEGRAM_EJARA_SUPPORT_TOKEN: ${env:TELEGRAM_EJARA_SUPPORT_TOKEN}
    AWS_REGION_NAME: ${env:AWS_REGION_NAME}
    DYNAMODB_CS_CHAT_TICKET: ${env:DYNAMODB_CS_CHAT_TICKET}
    S3_BUCKET_CS_CHAT_TICKET: ${env:S3_BUCKET_CS_CHAT_TICKET}
  iam:
    role:
      name: cs-telegram-bot-${env:WORKING_ENVIRONMENT}
      path: /
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            Fn::GetAtt:
              - CsChatTicketTable
              - Arn
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            Fn::GetAtt:
              - CsChatTicketBucket
              - Arn
        - Effect: Allow
          Action:
            - s3:ListObjects
            - s3:PutObject
            - s3:GetObject
            - s3:PutObjectTagging
            - s3:GetObjectTagging
          Resource:
            Fn::Join:
              - ''
              - - Fn::GetAtt:
                    - CsChatTicketBucket
                    - Arn
                - '/*'

functions:
  clickup:
    handler: handler.clickup
    name: cs-telegram-bot-incoming-clickup-${env:WORKING_ENVIRONMENT}
    timeout: 30
    events:
      - http:
          path: clickup
          method: post
          cors: true
  telegram:
    handler: handler.telegram
    name: cs-telegram-bot-incoming-telegram-${env:WORKING_ENVIRONMENT}
    timeout: 30
    events:
      - http:
          path: telegram
          method: post
          cors: true


resources:
      Resources:
        CsChatTicketTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: ${env:DYNAMODB_CS_CHAT_TICKET}
            AttributeDefinitions:
              - AttributeName: chat_platform
                AttributeType: S
              - AttributeName: chat_id
                AttributeType: S
            KeySchema:
              - AttributeName: chat_platform
                KeyType: HASH
              - AttributeName: chat_id
                KeyType: RANGE
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
              SSEEnabled: false
        CsChatTicketBucket:
          Type: AWS::S3::Bucket
          Properties:
            BucketName: ${env:S3_BUCKET_CS_CHAT_TICKET}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
  pythonBin: python3
  dockerizePip: False
```

### Command name and used flags

serverless deploy

### Command output

```shell
Run serverless/github-action@v3.1
/usr/bin/docker run --name d69c8bf10f40b48dfaf6104eaa86ee2f5_8fc5c5 --label 08450d --workdir /github/workspace --rm -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_REGION_NAME -e WORKING_ENVIRONMENT -e DYNAMODB_CS_CHAT_TICKET -e S3_BUCKET_CS_CHAT_TICKET -e TELEGRAM_EJARA_SUPPORT_TOKEN -e CLICKUP_CS_CHATBOT_ACCESS_TOKEN -e CLICKUP_CS_CHAT_TICKET_LIST_ID -e INPUT_ARGS -e INPUT_ENTRYPOINT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/bin/sh" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/data-cs-bot-telegram-clickup/data-cs-bot-telegram-clickup":"/github/workspace" 08450d:69c8bf10f40b48dfaf6104eaa86ee2f5 -c "serverless plugin install --name serverless-python-requirements && serverless deploy"
Running "serverless" from node_modules

✔ Plugin "serverless-python-requirements" installed  (1s)
Running "serverless" from node_modules

Deploying cs-telegram-bot to *** *** (***)

× Stack cs-telegram-bot-*** failed to deploy (0s)
Environment: linux, node 16.15.0, framework 3.18.2 (local) 3.18.2v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Error:
Support:     forum.serverless.com
Error: spawn python3.8 ENOENT
Bugs:        github.com/serverless/serverless/issues
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)

    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.18.2 (local) 3.18.2 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
