### ISSUE TITLE
Unable to implement request type lambda authorization in serverless framework

### ISSUE THREAD

**Issue by kiriti999** [serverless/serverless#11126]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

How to implement request type lambda authorizer in serverless framework?

I haven't been able to implement the same in serverless framework compared to aws sam.

I always get 403 forbidden all the time. Here's the [github code](https://github.com/kiriti999/api-gateway-request-auth.git)

Serverless URL: [https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/hello?auth=yes](https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/auth=yes)
Sam URL: [https://7jjym0ms9g.execute-api.ap-southeast-2.amazonaws.com/dev/hello?auth=yes](https://7jjym0ms9g.execute-api.ap-southeast-2.amazonaws.com/dev/hello?auth=yes)

You can test both the URL's above and sam url is working as expected and other one returns 403 always

Serverless template:

```
service: sls-api-gateway-request-auth
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  timeout: 30

functions:
  authFunction:
    handler: ./auth.lambda_handler

  backendFunction:
    handler: ./backend.lambda_handler
    runtime: nodejs14.x
    events:
      - http:
          method: get
          cors: true
          path: /auth
          authorizer:
            name: authFunction
            type: request

  Outputs:
    MyApiAuth:
      Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
      Value: !Sub "https://{sls:instanceId}.execute-api.${AWS::Region}.amazonaws.com/dev/hello?auth=yes"
```

Here's the SAM template which is working fine:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt authFunction.Arn
            Identity:
              QueryStrings:
                - auth
              ReauthorizeEvery: 100

  backendFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: backend.lambda_handler
      Runtime: nodejs10.x
      CodeUri: .
      Events:
        HelloAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /hello
            Method: GET

  authFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: auth.lambda_handler
      Runtime: nodejs10.x

Outputs:
  ApiUrl:
    Description: "API endpoint URL"
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/dev/hello?auth=yes'
```

### Service configuration (serverless.yml) content

```yaml
service: sls-api-gateway-request-auth
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  timeout: 30

functions:
  authFunction:
    handler: ./auth.lambda_handler

  backendFunction:
    handler: ./backend.lambda_handler
    runtime: nodejs14.x
    events:
      - http:
          method: get
          cors: true
          path: /auth
          authorizer:
            name: authFunction
            type: request

resources:
  Resources:
  Outputs:
    MyApiAuth:
      Description: "API Gateway endpoint URL for dev stage for api key validation in query string"
      Value: !Sub "https://{sls:instanceId}.execute-api.${AWS::Region}.amazonaws.com/dev/hello/auth?apiKey=yes"
```

### Command name and used flags

sls deploy

### Command output

```shell
endpoint: GET - https://hr4nwgnf96.execute-api.ap-southeast-2.amazonaws.com/dev/auth                                                           
functions:
  authFunction: sls-api-gateway-request-auth-dev-authFunction (2.1 kB)                                                                         
  backendFunction: sls-api-gateway-request-auth-dev-backendFunction (2.1 kB)
```

### Environment information

```shell
Framework Core: 3.18.2
Plugin: 6.2.2
SDK: 4.3.2
```
