### ISSUE TITLE
Serverless compose throws an error `Impossible to parse the output of "serverless info":`

### ISSUE THREAD

**Issue by fitnesssociety** [serverless/serverless#11146]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I run `sls deploy --stage stg` to my serverless-compose.ts, it throws an error `Impossible to parse the output of "serverless info":` and skip the next service.

### Service configuration (serverless.yml) content

```yaml
const serverlessCompose = {
    services: {
        infra: {
            path: "../app-infra"
        },

        service1: {
            path: "../app-service1",
            dependsOn: ["infra"]
        }
    }
}

module.exports = serverlessCompose;
```

### Command name and used flags

sls deploy --stage stg

### Command output

```shell
Impossible to parse the output of "serverless info":
Service Information
service: app-infra
stage: stg
region: ap-southeast-1
stack: app-infra-stg
resources: 22
api keys:
  None
endpoints:
functions:
  None
layers:
  None

Stack Outputs
APIGatewayRestApiRootResourceId: xxxx
ApiGatewayRestApiId: xxxx
CognitoUserPoolApplicationUserPoolId: xxxx
CognitoUserPoolApplicationUserPoolClientId: xxxx
APIGatewayCognitoAuthorizer: xxxx
CognitoUserPoolARN: xxxx
ServerlessDeploymentBucketName: xxxx
```

### Environment information

```shell
Framework Core: 3.19.0 (local) 3.19.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
