### ISSUE TITLE
Forbidden error without more description

### ISSUE THREAD

**Issue by dmtzs** [serverless/serverless#11151]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I try to do deploy by executing the command ``serverless deploy --verbose`` I only get an error that is Forbidden but without more description. A fragment about this is below:

```
Environment: linux, node 16.15.1, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Forbidden
```

Also Im using the last framework version, any one has the same error?

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
Environment: linux, node 16.15.1, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Forbidden
```

### Environment information

```shell
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by pgrzesik** [comment]
Hello @dmtzs - thanks a lot for reporting and sorry you've run into trouble. That does in fact look a bit cryptic and unexpected. Would you be able to share a minimal config that causes this on your side (with sensitive parts masked out)? Especially, are you using any plugins?

**Comment by italo-buono** [comment]
I'm having the same issue here, it was working two days ago and now I'm having the same problem.

Nothing has changed, and I'm using the following serverless as a sample:

```
service: FOO

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iam:
    role: ${env:FOO}
  vpc:
    securityGroupIds:
      - ${env:FOO, 'default'}
    subnetIds:
      - ${env:FOO, 'default'}
      - ${env:FOO, 'default'}
      - ${env:FOO, 'default'}
functions:
  main:
    handler: dist/main.handler
    timeout: 300
    environment:
      NODE_ENV: ${env:NODE_ENV, 'default'}
      FOO: ${env:FOO, 'default'}
    events:
      - cognitoUserPool:
          pool: FOO
          trigger: FOO
          existing: true
```
