### ISSUE TITLE
Adding `X-Amzn-Trace-Id` to default CORS headers

### ISSUE THREAD

**Issue by szbartnik** [serverless/serverless#11157]
### Is there an existing issue for this?

- [x] I have searched existing issues, it hasn't been reported yet

### Use case description

Recently I've started using [AWS CloudWatch RUM](https://aws.amazon.com/blogs/aws/cloudwatch-rum/) which is a relatively new telemetry product.

In order to fully use its capabilities and track frontend & backend transactions with X-Ray in an E2E manner I've activated automatic `X-Amzn-Trace-Id` header passing in the SDK on frontend:
```typescript
telemetries: [
  'performance',
  'errors',
  ['http', { addXRayTraceIdHeader: true }],
],
```

Till this moment I've been using only default CORS headers so I had to add `X-Amzn-Trace-Id` header manually:
```yml
functions:
  api:
    handler: handlers/api/handler.handler
    events:
      - http:
          path: api/{any+}
          method: GET
          cors:
            origin: https://serverless.com
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Amzn-Trace-Id   # <-- have to add this manually!
```

Similar issue from 2017 but about `X-Amz-User-Agent` header which has been eventually added: https://github.com/serverless/serverless/issues/3586

### Proposed solution (optional)

As AWS CloudWatch RUM grows in popularity in the feature I think it makes sense to add `X-Amzn-Trace-Id` to the list of default headers as it makes configuration simpler.

I'm happy to create a [PR](https://github.com/serverless/serverless/compare/main...szbartnik:feat/x-amzn-trace-id-default-header?expand=1) for it when you agree it will help other people too.
