### ISSUE TITLE
serverless deploy function does not work when artifact path is an S3 bucket

### ISSUE THREAD

**Issue by kyle-hiller-nh** [serverless/serverless#11158]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We use artifacts stored in an S3 bucket to implement a build/release/promote pattern for doing deployments, where one set of artifacts can be promoted to higher environments. I was testing out using `sls deploy function` for doing development deploys, but it appears that this command expects the artifact to be in your local filesystem.

### Service configuration (serverless.yml) content

```yaml
service: test-${env:GIT_HASH}

provider:
  name: aws
  runtime: go1.x
  versionFunctions: false
  timeout: 60
  tracing:
    lambda: true

package:
  individually: true

functions:
  Lookup:
    name: lookup
    handler: lookup
    timeout: 60
    package:
      individually: true
      artifact: s3://${env:BUCKET_NAME}/${env:RELEASE_TAG}/lookup.zip
    tracing: Active
```

### Command name and used flags

serveless deploy function --region us-west-2 --function Lookup

### Command output

```shell
Error: ENOENT: no such file or directory, open '$PWD/s3:/bucket/tag/lookup_existing_payee.zip'
```

### Environment information

```shell
Framework Core: 3.19.0 (local) 3.12.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
