### ISSUE TITLE
Forbidden error

### ISSUE THREAD

**Issue by gitkseniya** [serverless/serverless#11161]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

CI/CD pipeline works- deploys when AWS user has admin access. When limiting access to the policies listed below, a vague error is given.

Policies listed under user:
* AmazonEKSClusterPolicy
* AmazonEC2ContainerRegistryFullAccess
* AmazonAPIGatewayAdministrator
* AWSLambdaExecute
* AWSLambdaRole
* ASWLambda_FullAccess
* and several policies allowing "cloudformation:CreateStack", "cloudformation:DescribeStackResource", "iam:AttachRolePolicy", "iam:CreatePolicy", "ssm:GetParameter", "ssm:GetParameters"

### Service configuration (serverless.yml) content

```yaml
name: Deploy main branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: Set up environment

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.3]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test

  deploy:
    needs: setup
    name: Deploy

    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

### Command name and used flags

n/a

### Command output

```shell
× Stack ***-service-develop failed to deploy (1s)
Environment: linux, node 16.15.1, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Forbidden
```

### Environment information

```shell
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
```
