### ISSUE TITLE
serverless with `existing: true` on s3 will create unnecessary IAM role

### ISSUE THREAD

**Issue by Sheile** [serverless/serverless#11163]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless(2.72.3 and 3.19.0) will create unnecessary IAM role and failed if used s3 bucket already exist.

### works
```
functions:
  SlsReproduce:
    handler: handler.handler
    events:
      - s3:
          bucket: new-uncreated-bucket.example.com
          event: s3:ObjectCreated:*
```

### DON'T works
```
functions:
  SlsReproduce:
    handler: handler.handler
    events:
      - s3:
          bucket: created-bucket.example.com
          event: s3:ObjectCreated:*
          existing: true
```

### memo
IMO, [this comment](https://github.com/serverless/serverless/issues/6771#issuecomment-638803619) in other issue is same problem.
But, [root issue](https://github.com/serverless/serverless/issues/6771) looks like different problem.

Our AWS environment restricted `iam:CreateRole` permission for security reason.

### Service configuration (serverless.yml) content

```yaml
service: sls-reproduce

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
  timeout: 60
  stage: dev
  role: arn:aws:iam::xxxxxxxxxxxx:role/already_created_role
  deploymentBucket: created-bucket.example.com

functions:
  SlsReproduce:
    handler: handler.handler
    events:
      - s3:
          bucket: created-bucket.example.com
          event: s3:ObjectCreated:*
          existing: true
```

### Command name and used flags

sls deploy

### Command output

```shell
Deploying sls-reproduce to stage dev (ap-northeast-1)

✖ Stack sls-reproduce-dev failed to deploy (17s)
Environment: linux, node 12.20.2, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: IamRoleCustomResourcesLambdaExecution (AWS::IAM::Role)
API: iam:CreateRole User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/xxxxxxxxx/i-xxxxxxxxxxxx is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::xxxxxxxxxxxx:role/sls-reproduce-dev-IamRoleCustomResourcesLambdaExec-1GN0BSD1UD796 because no identity-based policy allows the iam:CreateRole action
```

### Environment information

```shell
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
```
