### ISSUE TITLE
deploy function does cleanupTempDir too early breaking some plugins

### ISSUE THREAD

**Issue by fancywriter** [serverless/serverless#11179]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello, I am using serverless with bundle (webpack) and sentry plugins and facing issue that sentry doesn't publish source maps properly when using `deploy function` command for just one function, though work just when using `deploy` command to deploy alltogether.

It may be a bug in external plugin of course, that's why I have created it there first https://github.com/arabold/serverless-sentry-plugin/issues/67
However, while debugging and trying to understand the possible root cause I have found that indeed `deploy` and `deploy function` are designed a little bit differently.

The sentry plugin uses content of temp directory, it uses `.serverless/myFunction.zip` contents to publish source map (basically this zip file has two files: minified js code and source map). But for `deploy function` the plugin hook can't find an artifact because `.serverless` directory is recursively deleted, I am getting "Error: Invalid filename" error.

I have found that `deploy` the `cleanupTempDir` method is put into `aws:deploy:finalize:cleanup` event - https://github.com/serverless/serverless/blob/c611ce4015cbc018e07dcc3f48032ad1a0c64c6d/lib/plugins/aws/deploy/index.js#L217
Though for `deploy function` it is put inside last line of `deploy:function:deploy` https://github.com/serverless/serverless/blob/c611ce4015cbc018e07dcc3f48032ad1a0c64c6d/lib/plugins/aws/deploy-function.js#L57

For first case the hooks of event `after:deploy:deploy` have access to artifact files in temp directory https://github.com/arabold/serverless-sentry-plugin/blob/b0dd2d17a184b9b101d103c7f088278a3594d90b/src/index.ts#L153
But for the second case the hooks of event  `after:deploy:function:deploy` are called after the directory is cleaned up https://github.com/arabold/serverless-sentry-plugin/blob/b0dd2d17a184b9b101d103c7f088278a3594d90b/src/index.ts#L165

Clearly `aws:deploy:finalize:cleanup` event comes after `after:deploy:deploy`, could we do similar with `deploy function`?

P.S. Though I used 3.10.1 in my example, I have checked that master branch still have the same code of concern.

### Service configuration (serverless.yml) content

```yaml
plugins:
 - serverless-bundle
 - serverless-sentry
provider:
  name: aws
package:
  individually: true
functions:
  myFunction: <...>
custom:
  sentry:
    dsn: https://xxx.ingest.sentry.io/123456
    organization: github
    project: hello-sentry-serverless
    authToken: abcdef
    release:
      version: true
      refs: true
    sourceMaps:
      urlPrefix: /var/task
```

### Command name and used flags

sls deploy function -f myFunction -s myStage

### Command output

```shell
Error: Invalid filename
```

### Environment information

```shell
Framework Core: 3.10.1 (local) 3.16.0 (global)
Plugin: 6.2.0
SDK: 4.3.2
```
