### ISSUE TITLE
To support mulitple custom in single serverless.yml file

### ISSUE THREAD

**Issue by tappmarket** [serverless/serverless#11185]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

We have different AWS profile (different accounts and different region) for staging, dev, production, and employee personal accounts.

The custom field has been used to define environments for different profile.

`custom: ${file(./env/${env:AWS_PROFILE}.yml)}`
We don't want to have any profile information in serverless.yml, All our profiles are in separate files in `env` folder.

It is very convenient to deploy under specified profile
`AWS_PROFILE=dev sls deploy`

But we found a few common variables across different profile. For example: the plugin information

```
custom:
  serverless-layers:
    functions: # optional
      - my_func2
    dependenciesPath: ./package.json
```

### Proposed solution (optional)

`custom` can support multiple files, like

```
custom:
  -  ${file(./env/${env:AWS_PROFILE}.yml)}
  -  ${file(./env/common.yml)}
```
