### ISSUE TITLE
Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by IamMHC** [serverless/serverless#11184]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I trying to setup appsync-offline but i'm getting this error

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from "@serverless/typescript";
import Resources from "./resources";
import hello from "@functions/hello";

const serverlessConfiguration: AWS = {
  service: "slstest",
  frameworkVersion: "2",
  custom: {
    dynamodb: {
      stages: ["dev"],
      start: {
        port: 8000,
        inMemory: true,
        heapInitial: "200m",
        heapMax: "1g",
        migrate: true,
        seed: true,
        convertEmptyValues: true,
      },
    },
    "appsync-offline": {
      port: 62222,
      dynamodb: {
        client: {
          endpoint: "http://localhost:8000",
          region: "localhost",
          accessKeyId: "a",
          secretAccessKey: "a",
        },
        server: {
          port: 8000,
          dbPath: "./.dynamodb",
          inMemory: false,
          sharedDb: false,
          delayTransientStatuses: false,
          optimizeDbBeforeStartup: false,
        },
      },
    },
    "appsync-simulator": {
      location: ".webpack/service",
      dynamoDb: {
        endpoint: "http://localhost:8000",
      },
    },
    webpack: {
      webpackConfig: "./webpack.config.js",
      includeModules: true,
    },
  },
  plugins: [
    "serverless-webpack",
    "serverless-appsync-plugin",
    "serverless-appsync-offline",
    "serverless-appsync-simulator",
    "serverless-dynamodb-local",
    "serverless-offline",
  ],
  provider: {
    name: "aws",
    runtime: "nodejs14.x",
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1",
    },
    lambdaHashingVersion: "20201221",
  },
  // import the function via paths
  functions: { hello },
  resources: { Resources },
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

sls offline start 

### Command output

```shell
`Running "serverless" from node_modules
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
 
 Type Error ----------------------------------------------
 
  TypeError: Class extends value #<Object> is not a constructor or null`
```

### Environment information

```shell
Framework Core: 2.72.3 (local)
Plugin: 5.5.4
SDK: 4.3.2
Components: 3.18.2
```
