### ISSUE TITLE
Should not resolve params not in current stage

### ISSUE THREAD

**Issue by samchungy** [serverless/serverless#11202]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I am trying to use parameters in conjunction with ssm however the prod secret path is different to the dev path and does not exist in the dev account. I don't think Serverless should be trying to resolve my prod params when I am deploying/packaging for dev.

` - Cannot resolve variable at "params.prod.alertEndpoint": Value not found at "ssm" source`

### Service configuration (serverless.yml) content

```yaml
params:
  dev:
    alertEndpoint: ${ssm:/aws/reference/secretsmanager/dev-alert-path}
  prod:
    alertEndpoint: ${ssm:/aws/reference/secretsmanager/prod-alert-path}
```

### Command name and used flags

serverless package --stage dev

### Command output

```shell
` - Cannot resolve variable at "params.prod.alertEndpoint": Value not found at "ssm" source`
```

### Environment information

```shell
3.19.0
```
