### ISSUE TITLE
Error: The security token included in the request is expired

### ISSUE THREAD

**Issue by marcossv9** [serverless/serverless#11204]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When trying to deploy a newly created flask api using the serverless framework, I get the following error:

`Error:
The security token included in the request is expired`

I checked the profile with the following command, and it's ok:

```
aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                  sandbox              env    ['AWS_PROFILE', 'AWS_DEFAULT_PROFILE']
access_key     ****************CJP2              sso    
secret_key     ****************pXnK              sso    
    region                us-east-2      config-file    ~/.aws/config
```
 
Also, I can list all my s3 buckets within the same environment using aws cli.
Additionally, we have an SSO integration working fine.
I don't know what might be the problem..
Thanks!

### Service configuration (serverless.yml) content

```yaml
service: my_api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: sandbox
  profile: sandbox

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
Running "serverless" from node_modules

Deploying my_api to stage sandbox (us-east-2)

Packaging
Using Python specified in "runtime": python3.8
Packaging Python WSGI handler...
Generated requirements from /home/ms/my_api/requirements.txt in /home/ms/my_api/.serverless/requirements.txt
Using static cache of requirements found at /home/ms/.cache/serverless-python-requirements/632bef70cb6a3b9e57ec918527b546dcbb92468ed4979ae014c9fca924041e64_x86_64_slspyc
Excluding development dependencies for service package
Injecting required Python packages to package
Retrieving CloudFormation stack

✖ Stack my_api failed to deploy (7s)
Environment: linux, node 16.14.2, framework 3.19.0 (local) 3.19.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "sandbox" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The security token included in the request is expired
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.19.0 (local) 3.19.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
