### ISSUE TITLE
Layer throws a warning if >5 runtimes are specified

### ISSUE THREAD

**Issue by anthonyangel** [serverless/serverless#11226]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I create a lambda layer with >5 runtimes specified serverless throws a warning that the limit is 5. According to AWS it should be 15. The warning is non-blocking and the layer is correctly created with all runtimes specified

### Service configuration (serverless.yml) content

```yaml
service: layer

provider:
  name: aws
  stage: prod
  region: eu-west-1

layers:
  layer:
    path: layer
    name: layer
    compatibleRuntimes:
    - nodejs16.x
    - nodejs14.x
    - nodejs12.x
    - python3.9
    - python3.8
    - python3.7
    - python3.6
    - go1.x
    - dotnet6
    - dotnetcore3.1
    compatibleArchitectures:
    - x86_64
    - arm64
    retain: true
```
```


### Command name and used flags

serverless deploy

### Command output

```shell
Warning: Invalid configuration encountered
  at 'layers.layer.compatibleRuntimes': must NOT have more than 5 items

Learn more about configuration validation here: http://slss.io/configuration-validation

Deploying layer-layer to stage prod (eu-west-1)

✔ Service deployed to stack layer-layer-prod (25s)

layers:
  tenants: arn:aws:lambda:eu-west-1:12345678910:layer:layer:2

1 deprecation found: run 'serverless doctor' for more details
```
```


### Environment information

```shell
Framework Core: 3.20.0
Plugin: 6.2.2
SDK: 4.3.2
```
