### ISSUE TITLE
Configured layers are being removed when deploying an individual function when console is enabled

### ISSUE THREAD

**Issue by Danwakeem** [serverless/serverless#11231]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I am deploying a function individually from the serverless CLI and all of the layers I had configured in my serverless.yml file were removed in place of the console extension.

> Note: Re-running sls deploy on the whole serverless.yml file appears to add the configured layers back.

### Service configuration (serverless.yml) content

```yaml
org: consoledemo
service: image-text-extract
configValidationMode: error
console: true

provider:
  name: aws
  runtime: nodejs16.x
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  versionFunctions: false
  iamManagedPolicies: 
    - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
  tracing:
    apiGateway: true
    lambda: true
  environment:
    STAGE: ${opt:stage}
    S3_BUCKET: ${self:custom.S3_BUCKET}
  httpApi:
    payload: '2.0'
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - '*'
      allowedMethods:
        - '*'
      maxAge: 6000 # In seconds
    disableDefaultEndpoint: false
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'states:StartExecution'
          Resource:
            - !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:OCR-direct-${opt:stage}
plugins:
  - serverless-esbuild
  - serverless-step-functions

custom:
  S3_BUCKET: console-demo-bucket-${opt:stage}
  esbuild:
    packager: yarn
    bundle: true
    minify: false
    sourcemap: external
    external:
      - '@aws-sdk/client-s3'
      - '@aws-sdk/s3-request-presigner'

package:
  exclude:
    - coverage/**
    - src/**/*.test.js
    - src/**/*.snap
    - '.*'
    - '.github/*'
    - '*.sh'
    - env.sample
    - assets/**
    - package.json
    - yarn.lock
    - README.md
    - frontend-visualization/**

layers:
  tesseractAl2:
    # and path to contents
    path: ready-to-use/amazonlinux-2
    compatibleRuntimes:
      - nodejs16.x
      - nodejs14.x

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3_BUCKET}
        LifecycleConfiguration:
          Rules:
            - Id: auto-delete
              Status: Enabled
              ExpirationInDays: 1
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders:
            - "*"
            AllowedMethods:
            - PUT
            AllowedOrigins:
            - "*"
            ExposedHeaders:
            - Date
            Id: PutObjectRule
            MaxAge: 3600
  Outputs:
    DirectOCRFunction:
      Description: The ARN of the state machine
      Value:
        Ref: OCRDashdirectDash${opt:stage}

functions:
  lambdaOCR:
    handler: src/states/directOCR.handler
    memorySize: 2048
    timeout: 300
    layers:
      - { Ref: TesseractAl2LambdaLayer }
      - !Sub arn:aws:lambda:${AWS::Region}:764866452798:layer:ghostscript:9


stepFunctions:
  stateMachines:
    OCR-direct:
      name: OCR-direct-${opt:stage}
      definition:
        Comment: A description of my state machine
        StartAt: DetectText
        States:
          DetectText:
            Type: Task
            Catch:
              - ErrorEquals: 
                - States.ALL
                Next: FailState
            Resource:
              Fn::GetAtt: [lambdaOCR, Arn]
            Next: SuccessState
          FailState:
            Type: Fail
          SuccessState:
            Type: Pass
            End: true
```

### Command name and used flags

sls deploy function -f lambdaOCR -s dev

### Command output

```shell
Deploying function lambdaOCR to stage dev (us-east-1)

✔ Function code deployed (14s)
✔ Function configuration updated (22s)


2 deprecations found: run 'serverless doctor' for more details
✨  Done in 27.17s.
```

### Environment information

```shell
Framework Core: 3.20.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
