### ISSUE TITLE
Lambda Authorizer multiple identity sources with OR between them

### ISSUE THREAD

**Issue by Slash7GNR** [serverless/serverless#11233]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Today there is already a feature where multiple identity source can be applied to lambda authorizer. The feature request can be seen [here](https://github.com/serverless/serverless/issues/5746)
As far as I understand, for this case, all the identity sources should be applied, otherwise API gateway will return 401 result automatically.
I would like to have the option that if ONE of the identity sources exists, then the lambda authorizer will be ran.
So for example if I have two identity sources:
1. Authorization Header
2. Cookie Header

- If Cookie header exists and authorization header not exists - lambda authorizer will be ran
- If Authorization header exists but cookie header not exists - lambda authorizer will be ran
- If both Authorization and Cookie header not exists - API Gateway will return 401 automatically.

Is it a use case that can be implemented ?

Regards,
Nadav Mary

**Comment by kmjennison** [comment]
I verified this behavior. An authorizer with multiple identity sources requires all of them to be set, and if any are missing, it returns 401.

This is consistent with [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/configure-api-gateway-lambda-authorization-with-console.html):

> “API Gateway uses the specified identity sources as the request authorizer caching key. When caching is enabled, API Gateway calls the authorizer’s Lambda function only after successfully verifying that all the specified identity sources are present at runtime. If a specified identify source is missing, null, or empty, API Gateway returns a 401 Unauthorized response without calling the authorizer Lambda function.”

One workaround is to define separate events with different authorizer settings:

```yaml
    events:            
      - http:
          path: example/
          method: post
          authorizer:
            arn: ${self:custom.customAuthorizerArn}
            type: request
            resultTtlInSeconds: 300
            identitySource: method.request.header.Authorization
      - http:
          path: example/this-uses-another-identity-source/
          method: post
          authorizer:
            arn: ${self:custom.customAuthorizerArn}
            type: request
            resultTtlInSeconds: 300
            identitySource: method.request.header.X-Some-Other-Header
```

This isn't ideal.

@pgrzesik Do you see a better approach?
