### ISSUE TITLE
serverless isn't configuring sns events to the 'provisioned' lambda alias when using provisionedConcurrency

### ISSUE THREAD

**Issue by y0rd4nis** [serverless/serverless#11246]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm trying to configure an AWS Lambda with provisioned concurrency to an SNS topic but the resulting trigger isn't using the provisioned lambda functions, it's tied to the $LATEST version instead.

I'd tried with SQS - Lambda / ApiGateway - Lambda and for ApiGateway/SQS the trigger is configured as expected, to the "provisioned" alias.

I'm not really sure if it's a serverless bug or the expected serverless behavior with SNS in this case, but it seems to me to be a little weird because serverless does set the requested lambda provisioned concurrency that ends unused.

### Service configuration (serverless.yml) content

```yaml
service: aws-test-python-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev

functions:
  api:
    handler: handler.api_handler
    timeout: 25
    provisionedConcurrency: 1
    events:
      - http:
          method: post
          path: /test

  sqs:
    handler: handler.sqs_handler
    timeout: 60
    provisionedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SqsQueue
              - Arn

  sns:
    handler: handler.sns_handler
    timeout: 60
    provisionedConcurrency: 1
    events:
      - sns:
          arn: !Ref SnsTopic
          topicName: SnsTopic

package:
  patterns:
    - '!node_modules/**'

resources:
  Resources:
    SnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:service}-${self:provider.stage}-SnsTopic
        TopicName: ${self:service}-${self:provider.stage}-SnsTopic

    SqsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-SqsQueue
        VisibilityTimeout: 360
```

### Command name and used flags

sls deploy

### Command output

```shell
Running "serverless" from node_modules

Deploying aws-test-python-project to stage dev (us-east-1)

✔ Service deployed to stack aws-test-python-project-dev (285s)

endpoint: POST - https://dummyapiid.execute-api.us-east-1.amazonaws.com/dev/test
functions:
  api: aws-test-python-project-dev-api (3.3 MB)
  sqs: aws-test-python-project-dev-sqs (3.3 MB)
  sns: aws-test-python-project-dev-sns (3.3 MB)

Improve API performance – monitor it with the Serverless Dashboard: run "serverless"
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.21.0 (local) 3.21.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
