### ISSUE TITLE
DOCKER Expose SSH  Argument. (Secrets Flag) 

### ISSUE THREAD

**Issue by CodeBooster97** [serverless/serverless#11255]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Hello all,

I need to access my private GitHub repos and want that serverless to handle the creation of the ECR Repo and building/push to ECR.
Currently, it's only possible to use buildArgs so I tried to cat my key and put it as build arg in the image. 
Unfourtanetly it seems like 
```
sls.yml

buildArgs:
  SSH_KEY: "$(cat ~/.ssh/id_rsa)"

in docker command:
=> --build-arg SSH_KEY=$(cat ~/.ssh/id_rsa)

Dockerfile

ARG SSH_KEY
RUN mkdir -p ~/.ssh && echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa 
RUN ssh-keyscan github.com > ~/.ssh/known_hosts
RUN echo "$SSH_KEY"
=> $(cat ~/.ssh/id_rsa)

```
is actually not doing the operation as I get the cat command in my ARG instead of the ssh key.

### Proposed solution (optional)

In my opinion, the ssh flag which will use the SSH_AUTH_SOCK would be perfect to handle this.
https://docs.docker.com/develop/develop-images/build_enhancements/

We could add something like this:
```
  ecr:
    images:
      scanOnPush: true
      appimage:
        path: "./"
        file: Dockerfile
        platform: linux/amd64
        ssh: 
            default: $SSH_AUTH_SOCK
            other: $OTHER_SSH_AUTH_SOCK
```
which will modify the docker build command to include
```
docker build ..... --ssh default . --ssh other=$OTHER_SSH_AUTH_SOCK
```

Like this, it would be possible to make use of the mount and even use multiple sockets per build 
```
RUN --mount=type=ssh git clone {{private_git_repo}}#uses default
RUN --mount=type=ssh,id=other git clone {{private_git_repo_2}}#use other ssh auth socket 
```
