### ISSUE TITLE
[Bug][Compose]

### ISSUE THREAD

**Issue by darylteo** [serverless/serverless#11262]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In `serverless-compose.yml`, param placeholders do not have the same "default value" functionality that is available in the general `serverless.yml`

https://github.com/darylteo/serverless-compose-bug-repro

In this reproduction repo, I have 2 services - 1 for the api functions, another for Cloudformation StackSet. I need to pass the RoleARN from the schema service over to the api service. This works once running `sls deploy` but in environments where I cannot do this (developer environments without access keys to remote AWS accounts), it fails to retrieve the ARN as the ARN does not exist yet.

I definitely do not want to make it a requirement for every developer to have to do a deploy before they can perform any changes. So I expected to be able to use the default value template pattern to solve this but it seems that `serverless-compose.yml` does not support this, and insteads just passes the entire placeholder as is. 

As is, I cannot run the service offline using `serverless-offline`, and I cannot run any offline unit tests, without actually doing a deploy first.

I understand this is a beta, and I may have missed something perhaps. If so please let me know!

Appreciate the package.

### Service configuration (serverless.yml) content

```yaml
serverless-compose.yml

services:
  api:
    path: api
    params:
      # does not work - default value does not pass through
      LambdaRoleArn: ${schema.LambdaRoleArn, ''} # runs but entire placeholder is treated as string
      
      # does not run - The variable "${schema.LambdaRoleArn}" cannot be resolved: the referenced output does not exist. 
      # LambdaRoleArn: ${schema.LambdaRoleArn} 
      

      # here to show that params are working
      PassedParam: "Hello World"


  schema:
    path: schema
```

### Command name and used flags

sls api:invoke local --function hello

### Command output

```shell
{
    "statusCode": 200,
    "body": "{\n  \"message\": \"Value: ${schema.LambdaRoleArn, ''} and param is Hello World\",\n  \"input\": \"\"\n}"
}
```

### Environment information

```shell
> sls --version
Running "serverless" from node_modules
Framework Core: 3.21.0 (local) 3.21.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
