### ISSUE TITLE
Encounter `TypeError` message occasionally

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#11286]
### Discussed in https://github.com/serverless/serverless/discussions/11280

/cc @pgrzesik @tommysitehost

<div type='discussions-op-text'>

<sup>Originally posted by **tommysitehost** July 26, 2022</sup>
Hey all,

We encountered this issue a few times before but we have seen this issue more frequently. We run sls deploy on Gitlab CI/CD:
```
AWS_SDK_LOAD_CONFIG=1   sls deploy --verbose --stage team --region us-west-2 --config containers.yml
Running "serverless" from node_modules
Environment: linux, node 12.22.12, framework 3.21.0 (local) 3.16.0v (global), plugin 6.2.2, SDK 4.3.2
```

and receive the error:
```
TypeError: Cannot read property 'shift' of undefined
    at VariablesResolver.resolveVariable (node_modules/serverless/lib/configuration/variables/resolve.js:230:28)
    at async node_modules/serverless/lib/configuration/variables/resolve.js:118:9
    at async Promise.all (index 0)
    at async VariablesResolver.resolveVariables (node_modules/serverless/lib/configuration/variables/resolve.js:112:5)
    at async VariablesResolver.self (node_modules/serverless/lib/configuration/variables/resolve.js:457:9)
    at async Promise.all (index 0)
    at async VariablesResolver.self (node_modules/serverless/lib/configuration/variables/resolve.js:547:9)
    at async Promise.all (index 6)
    at async node_modules/serverless/scripts/serverless.js:462:11
    at async node_modules/serverless/scripts/serverless.js:237:9
```
but then if we rerun the job, it usually succeeds.

This stack consists of multiple ECS services, tasks and ECS instances. As well as a few EC2 instances. It references ~70 files e.g. `${file(...)}`. Not sure if I have reached any limitation here?</div>

**Comment by medikoo** [comment]
@tommysitehost are you able to produce a minimal reproduction test case. It's a clear variable resolution error.

To have the right fix, it'll be good to have some example of `serverless.yml` (and files it imports) to reproduce it

**Comment by tommysitehost** [comment]
Since we have too many referenced files, I only send 2 files that reference the rest. LMK if you wanna look at other files.

Unfortunately, I have not tried to reproduce a minimal reproduction test case. 

`containers.yml` file
<details>
  <summary>Click to expand!</summary>
  
```
service: example-containers-${self:custom.common.regionShorthand.${self:custom.region}}

projectDir: ../../

variablesResolutionMode: 20210326
configValidationMode: error

provider:
  name: aws
  deploymentMethod: direct
  runtime: go1.x
  stage: dev
  region: ${self:custom.region}
  profile: ${self:custom.common.exampleProfile}
  logRetentionInDays: 7
  lambdaHashingVersion: 20201221 

custom:
  common: ${file(../common/common.yml)}
  alerts: ${file(../common/alerts.yml)}
  release: ${file(../config/release.yml)}
  regional: ${file(../common/regional.yml)}
  region: ${opt:region, self:custom.common.defaultRegion}

  createCPUBalanceAlerts:
    demo: true
    prod: true
    default: false
  createCPUBalanceAlert: ${self:custom.createCPUBalanceAlerts.${self:custom.common.stage}, self:custom.createCPUBalanceAlerts.default}

  rollbackEnabled:
    demo: true
    prod: true
    default: false
  rollback: ${self:custom.rollbackEnabled.${self:custom.common.stage}, self:custom.rollbackEnabled.default}

  releaseEnv: ${env:RELEASE, ''}

  team: ${env:TEAM, ''}

  registry:
    hostname: registry.example.com
    credentials: ${file(../config/registry-credentials-${self:custom.common.stage}.json)}

  sslBucket: ${cf:${self:custom.regional.servicesPrefix}.SSLBucket}

  ecsInstanceAMI:
    ap-northeast-1: ami-xyz
    ap-northeast-2: ami-xyz
    ap-northeast-3: ami-xyz
    ap-south-1: ami-xyz
    ap-southeast-1: ami-xyz
    ap-southeast-2: ami-xyz
    ca-central-1: ami-xyz
    eu-central-1: ami-xyz
    eu-north-1: ami-xyz
    eu-west-1: ami-xyz
    eu-west-2: ami-xyz
    eu-west-3: ami-xyz
    sa-east-1: ami-xyz
    us-east-1: ami-xyz
    us-east-2: ami-xyz
    us-west-1: ami-xyz
    us-west-2: ami-xyz

  ecsARMInstanceAMI:
    ap-northeast-1: ami-xyz
    ap-northeast-2: ami-xyz
    ap-south-1: ami-xyz
    ap-southeast-1: ami-xyz
    ap-southeast-2: ami-xyz
    ca-central-1: ami-xyz
    eu-central-1: ami-xyz
    eu-north-1: ami-xyz
    eu-west-1: ami-xyz
    eu-west-2: ami-xyz
    eu-west-3: ami-xyz
    sa-east-1: ami-xyz
    us-east-1: ami-xyz
    us-east-2: ami-xyz
    us-west-1: ami-xyz
    us-west-2: ami-xyz

  ec2InstanceAMI:
    af-south-1: ami-xyz
    ap-east-1: ami-xyz
    ap-northeast-1: ami-xyz
    ap-northeast-2: ami-xyz
    ap-northeast-3: ami-xyz
    ap-southeast-1: ami-xyz
    ap-southeast-2: ami-xyz
    ap-south-1: ami-xyz
    ca-central-1: ami-xyz
    eu-central-1: ami-xyz
    eu-north-1: ami-xyz
    eu-south-1: ami-xyz
    eu-west-1: ami-xyz
    eu-west-2: ami-xyz
    eu-west-3: ami-xyz
    me-south-1: ami-xyz
    sa-east-1: ami-xyz
    us-east-1: ami-xyz
    us-west-1: ami-xyz
    us-east-2: ami-xyz
    us-west-2: ami-xyz

  runner:
    clusterName: example-runner-cluster-${self:custom.common.stage}
    services:
      runner:
        memory:
          default: 768
        cpu:
          default: 1024
        desiredCount:
          default: 0
        image:
          prod: example.com/example/runner:${self:custom.releaseEnv}
          demo: example.com/example/runner:${self:custom.releaseEnv}
          staging: example.com/example/runner:latest
          team: example.com/example/runner:${self:custom.team}
          default: example.com/example/runner:latest
        redisCredentials: ${ssm:/aws/reference/secretsmanager/redis-runner}
        logLevel:
          prod: 100
          demo: 100
          staging: 300
          team: 300
          default: 500

    instances:
      template:
        instanceType:
          default: t3a.small
        instanceAmi: ${self:custom.ecsInstanceAMI.${self:custom.region}}
        publicIp: 'true'
        volume:
          size:
            default: 30
          type:
            default: gp2
          device: '/dev/xvda'
          deleteOnTermination: 'true'
        ebsOptimized: true
        cpuCredits: 'unlimited'
        instanceInitiatedShutdownBehavior: 'terminate'
        instanceInterruptionBehavior: 'terminate'
        marketType: 'spot'
        spotInstanceType: 'one-time'

  front-proxy:
    clusterName: example-front-proxy-cluster-${self:custom.common.stage}
    services:
      front-proxy:
        memory:
          default: 768
        cpu:
          default: 1024
        desiredCount:
          dev: 0
          default: 2
        image:
          prod: example.com/example/front-proxy:${self:custom.releaseEnv}
          demo: example.com/example/front-proxy:${self:custom.releaseEnv}
          staging: example.com/example/front-proxy:${self:custom.common.stage}-${env:CI_COMMIT_SHORT_SHA, 'latest'}
          team: example.com/example/front-proxy:${self:custom.team}-${env:CI_COMMIT_SHORT_SHA, 'latest'}
          default: example.com/example/front-proxy:latest
        redisCredentials: ${ssm:/aws/reference/secretsmanager/redis-front-proxy}
        logLevel:
          prod: 100
          demo: 300
          staging: 600
          team: 600
          default: 600
    instances:
      onDemandBaseCapacity:
        default: 0
      onDemandPercentage:
        prod: 50
        demo: 50
        default: 0
      spotAllocationStrategy:
        default: lowest-price
      spotInstancePools:
        default: 2
      minInstances:
        demo: 1
        prod: 1
        default: 0
      maxInstances: 10
      desiredInstances:
        dev: 0
        default: 2
      template:
        instanceType:
          default: t3a.micro
        instanceAmi: ${self:custom.ecsInstanceAMI.${self:custom.region}}
        publicIp: 'true'
        volume:
          size:
            default: 30
          type:
            default: gp2
          device: '/dev/xvda'
          deleteOnTermination: 'true'

  proxy:
    clusterName: example-proxy-cluster-${self:custom.common.stage}
    services:
      proxy:
        memory:
          default: 256
        cpu:
          default: 512
        desiredCount:
          dev: 1
          default: 2
        image:
          prod: example.com/example/proxy:${self:custom.releaseEnv}
          demo: example.com/example/proxy:${self:custom.releaseEnv}
          staging: example.com/example/proxy:${self:custom.common.stage}-${env:CI_COMMIT_SHORT_SHA, 'latest'}
          team: example.com/example/proxy:${self:custom.team}-${env:CI_COMMIT_SHORT_SHA, 'latest'}
          default: example.com/example/proxy:latest
        domain:
          prod: example.com
          demo: example.com
          staging: example.com
          team: example.com
          default: example.com
    instances:
      onDemandBaseCapacity:
        default: 0
      onDemandPercentage:
        prod: 50  
        demo: 50
        default: 0
      spotAllocationStrategy:
        default: lowest-price
      spotInstancePools:
        default: 2
      minInstances:
        demo: 1
        prod: 1
        default: 0
      maxInstances: 10
      desiredInstances:
        dev: 1
        default: 2
      template:
        instanceType:
          default: t3a.nano
        instanceAmi: ${self:custom.ecsInstanceAMI.${self:custom.region}}
        publicIp: 'true'
        volume:
          size:
            default: 30
          type:
            default: gp2
          device: '/dev/xvda'
          deleteOnTermination: 'true'

  redis:
    name: example-redis-${self:custom.common.stage}
    instanceType:
      default: t3a.micro
      demo: t3a.small
    instanceAmi: ${self:custom.ec2InstanceAMI.${self:custom.region}}
    volumeSize: 10
    userData: ${file(../../example/redis-api/docker/user-data.sh)}
    dockerCompose: ${file(../../example/redis-api/docker/docker-compose)}
    envFile: ${file(../../example/redis-api/docker/.env)}
    updateSSLScript: ${file(../../example/redis-api/docker/update-ssl.sh)}
    updateSSLCron: ${file(../../example/redis-api/docker/update-ssl.cron)}
    hostname:
      team: 'redis.${self:custom.region}.${self:custom.team}.example.com'
      staging: 'redis.${self:custom.region}.${self:custom.common.stage}.example.com'
      default: 'redis.${self:custom.region}.${self:custom.common.stage}.example.com'
    backupRetention:
      default: 14
    backupInterval:
      default: 24
    backupTime:
      default: "13:00"
    desired:
      dev: false
      default: true

  queue:
    desired:
      default: true
      staging: false 
    ha:
      demo: true
      prod: true
      staging: true
      default: false
    queue:
      clusterName: example
      clientPort: 4222
      clusterPort: 6222
      adminPort: 8222
      dataDir: /data
    userData: ${file(../../example/queue/docker/userdata.sh)}
    ecs:
      clusterName: example-queue-cluster-${self:custom.common.stage}
      services:
        queue:
          memory:
            default: 256
          cpu:
            default: 512
          image:
            prod: example.com/example/queue:${self:custom.releaseEnv}
            demo: example.com/example/queue:${self:custom.releaseEnv}
            staging: example.com/example/queue:${self:custom.common.stage}-${env:CI_COMMIT_SHORT_SHA, 'latest'}
            team: example.com/example/queue:${self:custom.team}-${env:CI_COMMIT_SHORT_SHA, 'latest'}
            default: example.com/example/queue:latest
    instances:
      type:
        default: t3a.nano
      ami: ${self:custom.ecsInstanceAMI.${self:custom.region}}
      bootVolume:
        size:
          default: 30 
        type:
          default: gp3
        device: '/dev/xvda'
        deleteOnTermination: 'true'
      dataVolume:
        size:
          default: 30 
        type:
          default: gp3
        device: '/dev/xvdf' 
        mountPoint: '/data'

  loadbalancer:
    desired:
      dev: false
      default: true

  sentryRelay:
    name: example-sentry-relay-${self:custom.common.stage}
    instanceType:
      default: t3a.nano
    instanceAmi: ${self:custom.ec2InstanceAMI.${self:custom.region}}
    volumeSize: 10
    userData: ${file(../../example/sentry-relay/docker/user-data.sh)}
    dockerCompose: ${file(../../example/sentry-relay/docker/docker-compose)}
    updateSSLScript: ${file(../../example/sentry-relay/docker/update-ssl.sh)}
    updateSSLCron: ${file(../../example/sentry-relay/docker/update-ssl.cron)}
    relayConfig: ${file(../../example/sentry-relay/docker/config)}
    hostname:
      default: 'relay.${self:custom.region}.${self:custom.common.stage}.example.com'
      prod: 'relay.${self:custom.region}.example.com'
    desired:
      dev: false
      team: false
      default: true

frameworkVersion: "^3.21.0"

resources: ${file(containers/resources.yml):resources}
```
</details>

`containers/resources.yml` file:

<details>
  <summary>Click to expand!</summary>

```
# Create our resources with separate CloudFormation templates
resources:
  - ${file(containers/resources/shared/log-group.yml)}
  - ${file(containers/resources/shared/security-group.yml)}

  - ${file(containers/resources/roles/task.yml)}
  - ${file(containers/resources/roles/task-execution.yml)}
  - ${file(containers/resources/roles/spot-fleet.yml)}
  - ${file(containers/resources/roles/ecs.yml)}
  - ${file(containers/resources/roles/ecs-ec2.yml)}

  - ${file(containers/resources/load-balancer/elastic-load-balancer.yml)}
  - ${file(containers/resources/load-balancer/target-group.yml)}

  - ${file(containers/resources/redis-instance/ec2-instance.yml)}
  - ${file(containers/resources/redis-instance/elastic-ip-address.yml)}
  - ${file(containers/resources/redis-instance/instance-profile.yml)}
  - ${file(containers/resources/redis-instance/roles.yml)}
  - ${file(containers/resources/redis-instance/security-group.yml)}
  - ${file(containers/resources/redis-instance/volume.yml)}

  - ${file(containers/resources/sentry-relay-instance/ec2-instance.yml)}
  - ${file(containers/resources/sentry-relay-instance/elastic-ip-address.yml)}
  - ${file(containers/resources/sentry-relay-instance/instance-profile.yml)}
  - ${file(containers/resources/sentry-relay-instance/roles.yml)}
  - ${file(containers/resources/sentry-relay-instance/security-group.yml)}

  - ${file(containers/services/front-proxy/security-group.yml)}
  - ${file(containers/services/front-proxy/listeners.yml)}
  - ${file(containers/services/front-proxy/service.yml)}
  - ${file(containers/services/front-proxy/target-groups.yml)}
  - ${file(containers/services/front-proxy/task-definition.yml)}
  - ${file(containers/services/front-proxy/user.yml)}
  - ${file(containers/services/front-proxy/autoscale-group.yml)}
  - ${file(containers/services/front-proxy/ecs-cluster.yml)}

  - ${file(containers/services/proxy/security-group.yml)}
  - ${file(containers/services/proxy/listener.yml)}
  - ${file(containers/services/proxy/service.yml)}
  - ${file(containers/services/proxy/target-group.yml)}
  - ${file(containers/services/proxy/task-definition.yml)}
  - ${file(containers/services/proxy/user.yml)}
  - ${file(containers/services/proxy/autoscale-group.yml)}
  - ${file(containers/services/proxy/ecs-cluster.yml)}

  - ${file(containers/services/runner/service.yml)}
  - ${file(containers/services/runner/task-definition.yml)}
  - ${file(containers/services/runner/launch-template.yml)}
  - ${file(containers/services/runner/ecs-cluster.yml)}

  - ${file(containers/services/queue/instance-profile.yml)}
  - ${file(containers/services/queue/volume.yml)}
  - ${file(containers/services/queue/launch-template.yml)}
  - ${file(containers/services/queue/autoscaling-group.yml)}
  - ${file(containers/services/queue/ecs-cluster.yml)}
  - ${file(containers/services/queue/ecs-service.yml)}
  - ${file(containers/services/queue/ecs-task-definition.yml)}
  - ${file(containers/services/queue/security-group.yml)}
```
</details>
