### ISSUE TITLE
Console server is unavailable, please try again later

### ISSUE THREAD

**Issue by kevinmartinjos** [serverless/serverless#11306]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I cannot deploy anymore. `SLS_DEBUG=* sls deploy` gives:

```
✖ Stack core-dev failed to deploy (20s)
Environment: darwin, node 17.2.0, framework 3.21.0 (local) 3.21.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Serverless Dashboard, "arn:aws:iam::825947527365:role/SFRole-MY-C9NDnu" provider (https://app.serverless.com/lonesword/apps/core/core/dev/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Console server is unavailable, please try again later
```

I have not changed my `serverless.yml` recently - I have been able to successfully deploy with the same yml file before.

I am able to successfully log in to the console using `serverless login --console`.  Running `serverless --console` gives:
```
(venv) bash-3.2$ serverless --console
Running "serverless" from node_modules

Your service is configured with Serverless Console and is ready to be deployed.
```

### Service configuration (serverless.yml) content

```yaml
org: lonesword
app: core
console: true
service: core

package:
  exclude:
    - venv/**
    - node_modules/**


custom:
  tableName: 'UsersTableStaging'
  region: ${opt:region, self:provider.region}
  wsgi:
    app: src.app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  customDomain:
    domainName: dev.tweetscreenr.com
    basePath: ''
    stage: dev
    certificateArn: "arn:aws:acm:us-east-1:825947527365:certificate/59992c66-a821-439b-ae2b-5d8dac3b293c"
    endpointType: regional
    createRoute53Record: true
    apiType: http
    autoDomain: true
    
  serverless-layers:
    dependenciesPath: ./requirements.txt
    layersDeploymentBucket: "layers-bucket-2"

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: 'us-east-1'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - Fn::GetAtt: [ UsersTableStaging, Arn ]

        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource:
            - { "Fn::Join": [ "/", [
              { "Fn::GetAtt": ["UsersTableStaging", "Arn"]}, "index", "AccessTokenIndex"
            ] ] }
            - { "Fn::Join": [ "/", [
              { "Fn::GetAtt": [ "UsersTableStaging", "Arn" ] }, "index", "RSSIndex"
            ] ] }
            - { "Fn::Join": [ "/", [
              { "Fn::GetAtt": [ "UsersTableStaging", "Arn" ] }, "index", "StripeCustomerIndex"
            ] ] }
        - Effect: Allow
          Action:
            - SES:Publish
            - SES:SendEmail
            - SNS:Publish
            - SQS:Publish
            - SQS:SendMessage
            - cloudformation:DescribeStacks
            - lambda:PublishLayerVersion
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - "arn:aws:s3:::layers-bucket-2"

  environment:
    USERS_TABLE: ${self:custom.tableName}
    XIVMAIL_HOSTNAME: "https://dev.tweetscreenr.com"
    DOWNLOAD_QUEUE: {"Fn::Join": ["", ["https://","sqs.${self:custom.region}.amazonaws.com/", {"Ref": "AWS::AccountId"}, "/DownloadQueueStaging"]]}
    USER_POLL_TOPIC: {"Fn::Join": ["", ["arn:aws:sns:${self:custom.region}:", {"Ref": "AWS::AccountId"}, ":UserPollTopicStaging"]]}
    DIGEST_TOPIC: {"Fn::Join": ["", ["arn:aws:sns:${self:custom.region}:", {"Ref": "AWS::AccountId"}, ":DigestTopicStaging"]]}
    XIVMAIL_CONSUMER_KEY: ${param:xivmailkey}
    XIVMAIL_CONSUMER_SECRET: ${param:xivmailsecret}
    ENCRYPTION_KEY: ${param:encryptionkey}
    STRIPE_PRICE_ID: "something"
    STRIPE_WEBHOOK_SECRET: ${param:stripewebhooksecret}
    STRIPE_API_KEY: ${param:stripeapikey}
    IS_LOAD_TEST: 0


functions:
  landing:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /'

  login:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /login'

  logout:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /logout'

  callback:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /sign-in-twitter'

  home:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /home'

  home_feed:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /home/feed'

  settings:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /settings'

  rss:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: 'GET /rss/{rss_id}'
    
  download_paper:
    handler: src.tweetmodel.save_tweet
    memorySize: 128
    timeout: 4
    events:
      - sqs:
          batchSize: 1  # A batch size of 1 artificially slows down requests. Less likely to be blocked by cloudflare and friends
          arn:
            Fn::GetAtt:
              - DownloadQueueStaging
              - Arn

  poll_for_all_users:
    handler: src.jobs.poll_for_tweets_for_all_users
    memorySize: 128
    events:
      - schedule: rate(60 minutes)
      
  poll_for_user_2:
    handler: src.jobs.async_poll_for_tweets_for_user
    memorySize: 128
    timeout: 15
    events:
      - sns: 
          arn: !Ref UserPollTopicStaging
          topicName: "UserPollTopicStaging"

  daily_digest:
    handler: src.jobs.send_daily_digests_for_all_users
    memorySize: 128
    events:
      - schedule: rate(24 hours)

  weekly_digest:
    handler: src.jobs.send_weekly_digests_for_all_users
    memorySize: 128
    events:
      - schedule: rate(168 hours)

  send_digest:
    handler: src.jobs.send_digest_for_user
    memorySize: 128
    events:
      - sns:
          arn: !Ref DigestTopicStaging
          topicName: "DigestTopicStaging"
    
  crawl_test:
    handler: tests.crawl_test.do_crawl_test
    memorySize: 128

  rss_on:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /rss/on'
    memorySize: 128

  rss_off:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /rss/off'
    memorySize: 128

  email_frequency:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /frequency/{frequency}'
    memorySize: 128

  add_domain_blocklist:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /domain-blocklist/add'
    memorySize: 128

  delete_domain_blocklist:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /domain-blocklist/delete'
    memorySize: 128

  add_to_account_blocklist:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /account-blocklist/add'
    memorySize: 128

  delete_from_account_blocklist:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /account-blocklist/delete'
    memorySize: 128

  feed:
    handler: wsgi.handler
    events:
      - httpApi: 'GET /feed'
    memorySize: 128

  add_feed:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /feed/add/{list_id}'
    memorySize: 128

  delete_feed:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /feed/delete/{list_id}'
    memorySize: 128

  checkout:
    handler: wsgi.handler
    events:
      - httpApi: 'GET /checkout'

  checkout_success:
    handler: wsgi.handler
    events:
      - httpApi: 'GET /checkout-success'

  webhook_received:
    handler: wsgi.handler
    events:
      - httpApi: 'POST /webhook'

  manage_subscription:
    handler: wsgi.handler
    events:
      - httpApi: 'GET /manage-subscription'

  privacy_policy:
    handler: wsgi.handler
    events:
      - httpApi: 'GET /privacy-policy'

plugins:
  - serverless-python-requirements
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-wsgi
  - serverless-domain-manager
  - serverless-layers

resources:
  Resources:
    UsersTableStaging:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: twitter_user_id
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: access_token_key
            AttributeType: S
          - AttributeName: rss_id
            AttributeType: S
          - AttributeName: stripe_customer_id
            AttributeType: S
        KeySchema:
          - AttributeName: twitter_user_id
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        GlobalSecondaryIndexes:
          - IndexName: AccessTokenIndex
            KeySchema:
              - AttributeName: access_token_key
                KeyType: HASH
            Projection:
              ProjectionType: 'ALL'
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

          - IndexName: RSSIndex
            KeySchema:
                - AttributeName: rss_id
                  KeyType: HASH
            Projection:
              ProjectionType: 'INCLUDE'
              NonKeyAttributes: ['is_active']
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: StripeCustomerIndex
            KeySchema:
                - AttributeName: stripe_customer_id
                  KeyType: HASH
            Projection:
              ProjectionType: 'INCLUDE'
              NonKeyAttributes: [ 'is_active', 'name', 'email' ]
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    DownloadQueueStaging:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "DownloadQueueStaging"
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          deadLetterTargetArn:
            "Fn::GetAtt":
              - ReceiverDeadLetterQueue
              - Arn
          maxReceiveCount: 2

    ReceiverDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "receiverDLQStaging"
        MessageRetentionPeriod: 1209600 # 14 days in seconds

    UserPollTopicStaging:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "UserPollTopicStaging"

    DigestTopicStaging:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "DigestTopicStaging"
```

### Command name and used flags

SLS_DEBUG=* sls deploy --aws-profile serverless

### Command output

```shell
Deploying core to stage dev (us-east-1, "arn:aws:iam::825947527365:role/SFRole-MY-C9NDnu" provider)


[ LayersPlugin ]: => default
... ○ Downloading ./requirements.txt from bucket...
... ⊗ =============================================================
... ⊗ NOTE: You're currently using incompatible version [Python 3.8.5]
... ⊗ =============================================================

... ○ Comparing requirements.txt dependencies...
... ○  No changes ! Using same layer arn: arn:aws:lambda:us-east-1:*********:core-dev-python-default:4
... ○ Adding layers...
... ✓ provider - arn:aws:lambda:us-east-1:*********:core-dev-python-default:4
... x (Skipped) function.landing - because it has no other layers
... x (Skipped) function.login - because it has no other layers
... x (Skipped) function.logout - because it has no other layers
... x (Skipped) function.callback - because it has no other layers
... x (Skipped) function.home - because it has no other layers
... x (Skipped) function.home_feed - because it has no other layers
... x (Skipped) function.settings - because it has no other layers
... x (Skipped) function.rss - because it has no other layers
... x (Skipped) function.download_paper - because it has no other layers
... x (Skipped) function.poll_for_all_users - because it has no other layers
... x (Skipped) function.poll_for_user_2 - because it has no other layers
... x (Skipped) function.daily_digest - because it has no other layers
... x (Skipped) function.weekly_digest - because it has no other layers
... x (Skipped) function.send_digest - because it has no other layers
... x (Skipped) function.crawl_test - because it has no other layers
... x (Skipped) function.rss_on - because it has no other layers
... x (Skipped) function.rss_off - because it has no other layers
... x (Skipped) function.email_frequency - because it has no other layers
... x (Skipped) function.add_domain_blocklist - because it has no other layers
... x (Skipped) function.delete_domain_blocklist - because it has no other layers
... x (Skipped) function.add_to_account_blocklist - because it has no other layers
... x (Skipped) function.delete_from_account_blocklist - because it has no other layers
... x (Skipped) function.feed - because it has no other layers
... x (Skipped) function.add_feed - because it has no other layers
... x (Skipped) function.delete_feed - because it has no other layers
... x (Skipped) function.checkout - because it has no other layers
... x (Skipped) function.checkout_success - because it has no other layers
... x (Skipped) function.webhook_received - because it has no other layers
... x (Skipped) function.manage_subscription - because it has no other layers
... x (Skipped) function.privacy_policy - because it has no other layers


Warning: Please change "wsgi.handler" to "wsgi_handler.handler" in serverless.yml
Warning: Using "wsgi.handler" still works but has been deprecated and will be removed
Warning: More information at https://github.com/logandk/serverless-wsgi/issues/84
Python executable not found for "runtime": python3.7
Using default Python executable: python
Packaging Python WSGI handler...

✖ Stack core-dev failed to deploy (19s)
Environment: darwin, node 17.2.0, framework 3.21.0 (local) 3.21.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Serverless Dashboard, "arn:aws:iam::825947527365:role/SFRole-MY-C9NDnu" provider (https://app.serverless.com/lonesword/apps/core/core/dev/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Console server is unavailable, please try again later

1 deprecation found: run 'serverless doctor' for more details
```

### Environment information

```shell
(venv) bash-3.2$ serverless --version
Running "serverless" from node_modules
Framework Core: 3.21.0 (local) 3.21.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
