### ISSUE TITLE
Variable resolution errored as it cannot resolve value at `provider.environment` 

### ISSUE THREAD

**Issue by samrith-s** [serverless/serverless#11333]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When trying to use environment variables, it gives me an error and none of the serverless commands work.  My environment variables file is like so:
```bash
# <root>/.env

# MySQL
MYSQL_USER=dummy
MYSQL_PASSWORD=dummy
MYSQL_DATABASE=dummy
MYSQL_ROOT_PASSWORD=dummy

# Nest run locally
DB_HOST=localhost
DB_PORT=3306

# Prisma database connection
DATABASE_URL=mysql://${MYSQL_USER}@${DB_HOST}:${DB_PORT}/${MYSQL_DATABASE}

# Nest
PORT=3000

# Security
JWT_ACCESS_SECRET=dummy
JWT_REFRESH_SECRET=dummy

# Auth0 - all are required
AUTH0_DOMAIN=dummy
AUTH0_CLIENT_ID= # Required
AUTH0_CLIENT_SECRET= # Required
AUTH0_AUDIENCE="http://localhost:3000"
```

### Service configuration (serverless.yml) content

```yaml
service: paemo-core
useDotEnv: true
variablesResolutionMode: 20210326
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    MYSQL_DATABASE: ${env:MYSQL_DATABASE}
    MYSQL_ROOT_PASSWORD: ${env:MYSQL_ROOT_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DATABASE_URL: ${env:DATABASE_URL}
    PORT: ${env:PORT}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: POST
          path: /graphql
```

### Command name and used flags

serverless offline

### Command output

```shell
Environment: darwin, node 16.15.0, framework 3.21.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.MYSQL_DATABASE": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.MYSQL_ROOT_PASSWORD": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.DB_HOST": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.DB_PORT": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.DATABASE_URL": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.PORT": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.ACCESS_TOKEN_SECRET": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.REFRESH_TOKEN_SECRET": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.AUTH0_DOMAIN": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.AUTH0_CLIENT_ID": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.AUTH0_CLIENT_SECRET": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.AUTH0_AUDIENCE": Value not found at "env" source
```

### Environment information

```shell
Framework Core: 3.21.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
