### ISSUE TITLE
bug inconsistent ${file()} in params and resources

### ISSUE THREAD

**Issue by nitram509** [serverless/serverless#11349]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Problem:
when using ${file(...)} in ```params``` section, files are just inserted, but not merged.
when using ${file(...)} in ```resources``` section, files are smart inserted and merged.

This is surprising and inconsistent behavior.
I would love to see consistency AND preferably the merging.

## Context / Use Case

I'm using serverless in a multi-tenant and multi-stage setup.
Hence, I would like to have multiple parameter files, which I could reference by tenant id.
E.g. given tenant A and tenant B, then I would like to have 3 files:
parameters.yml == the ones both tenants share
parameters.a.yml = for A
parameters.b.yml = for B

My hope was to load the shared one first and the second one by CLI parameter
```yml
params:
  - ${file(parameters.yml)}
  - ${file(parameters.${param:tenant_id}.yml)}
```

If there are other approaches, I'm open to switching to them ;)

Here are the 4 files 
[params1.yml.txt](https://github.com/serverless/serverless/files/9397584/params1.yml.txt)
[params3.yml.txt](https://github.com/serverless/serverless/files/9397588/params3.yml.txt)
[resources1.yml.txt](https://github.com/serverless/serverless/files/9397590/resources1.yml.txt)
[resources3.yml.txt](https://github.com/serverless/serverless/files/9397593/resources3.yml.txt)

### Service configuration (serverless.yml) content

```yaml
service: serverless-inconsistent-includes

frameworkVersion: '3'

params:
  - ${file(params1.yml)}
  - ${file(params3.yml)}

resources:
  - ${file(resources1.yml)}
  - ${file(resources3.yml)}

provider:
  name: aws
  runtime: python3.8

#functions:
#  hello:
#    handler: handler.hello
# >>> resolving ${param:One} does fail, since the params section can't merge 2 files
#    description: Paramter value ${param:One}
```

### Command name and used flags

serverless print

### Command output

```shell
Warning: Invalid configuration encountered
  at 'params': must be object

Learn more about configuration validation here: http://slss.io/configuration-validation
service: serverless-inconsistent-includes
frameworkVersion: '3'
params:
  - default:
      One: the number 1
      Two: the number 2
  - default:
      Three: the number 3
      Four: the number 4
resources:
  Parameters:
    One: the number 1
    Two: the number 2
    Three: the number 3
    Four: the number 4
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  versionFunctions: true
```

### Environment information

```shell
Framework Core: 3.21.0
Plugin: 6.2.2
SDK: 4.3.2
```
