### ISSUE TITLE
Serveless v2/v3 causes "Too many requests" error in CloudFormation

### ISSUE THREAD

**Issue by AlexsandroBezerra** [serverless/serverless#11357]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We tried to upgrade from serverless v1 to serverless v3, but it throws a "Too many requests" error in CloudFormation. The error occurred in v3, and it keeps happening when we try to downgrade to v2.

### Service configuration (serverless.yml) content

```yaml
service: project
frameworkVersion: ^3.22.0
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  - serverless-plugin-stage-variables
  - serverless-dynamodb-local
  - serverless-jetpack # To speed up the "Excluding development dependencies..." step
  - serverless-s3-local
  - serverless-offline-sqs
  - serverless-offline
  - "@kakkuk/serverless-aws-apigateway-documentation"
  - serverless-disable-request-validators

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${env:ENV}
  region: sa-east-1
  deploymentBucket:
    name: bucket
    blockPublicAccess: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:*'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'sqs:*'
          Resource: 'arn:aws:sqs:*:*:*'
  environment:
    ENV: ${env:ENV}

custom:
  stageVariables:
    STAGE: ${env:ENV}
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
  s3:
    host: 0.0.0.0
    port: 9000
    directory: /tmp
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: localhost
    accessKeyId: S3RVER
    secretAccessKey: S3RVER
 
package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!./**"
    - build/src/shared/**
    - resources/sql/**
    - node_modules/**

# Excluded functions and resources (DynamoDB Tables and SQS) from serverless.yml provided.
```

### Command name and used flags

npx serverless package --stage $STAGE --package .artifacts && npx serverless deploy --stage $STAGE --package .artifacts

### Command output

```shell
Deploying API to stage hlg (sa-east-1)
× Stack STACK failed to deploy (135s)
Environment: linux, node 16.16.0, framework 3.21.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
UPDATE_FAILED: Model (AWS::ApiGateway::Model)
Resource handler returned message: "Too Many Requests (Service: ApiGateway, Status Code: 429, Request ID: *, Extended Request ID: null)" (RequestToken: *, HandlerErrorCode: InternalFailure)
```

### Environment information

```shell
Environment: linux, node 16.16.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
