### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by mdrijwan** [serverless/serverless#11384]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

i'm trying to deploy docker image through sls

```
functions:
  generatePdf:
    # handler: src/api/generate.pdf
    images: 498157479666.dkr.ecr.ap-southeast-1.amazonaws.com/automate-pdf:latest@sha256:98e17f123e538564dff238122cc31ab38ddf1e735e4cc5f7be853cc2cc5e1dee
    description: A lambda handler that generates PDF file from payload data and upload it to S3 bucket.
    memorySize: 2048
    provisionedConcurrency: 2
    events:
      - http:
          path: pdf
          method: POST
          cors: true
          documentation:
            summary: Generates PDF from payload
            tags:
              - generatePdfS3
```

it works perfectly with `handler` but the moment i switch to `images`, it throws this weird error

```Error:
TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/typescript.js:57:33
    at Array.map (<anonymous>)
```
![Screenshot 2022-09-12 at 11 56 50 PM](https://user-images.githubusercontent.com/22044931/189700510-52708189-c8a2-4db5-b0a3-48e7b56c973a.png)

my sls version is as below:

```
Framework Core: 3.22.0
Plugin: 6.2.2
SDK: 4.3.2
```

### Service configuration (serverless.yml) content

```yaml
service: pdf-api

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  runtime: nodejs14.x
  region: ${opt:region, 'ap-southeast-1'}
  stage: ${opt:stage, 'dev'}
  apiGateway:
    description: An API to generate Cover Note in PDF format and upload it to S3 Bucket
  deploymentBucket:
    name: ${self:provider.environment.DEPLOY_BUCKET}
  environment:
    DEPLOY_BUCKET: automate-${opt:stage, self:provider.stage}-pdf-api
    UPLOAD_BUCKET: automate-${opt:stage, self:provider.stage}-pdf-upload
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:provider.environment.UPLOAD_BUCKET}/*
    - Effect: "Allow"
      Action:
        - ecr:InitiateLayerUpload
        - ecr:SetRepositoryPolicy
        - ecr:GetRepositoryPolicy
      Resource: arn:aws:ecr:${self:provider.region}:${self:custom.account}:repository/*

custom:
  account: ${aws:accountId}
  documentation:
    api:
      info:
        version: '1.0.0'
        title: 'Automate S3 PDF'
        description: 'Service to generate PDF and uploading to S3'
      tags:
        - name: 'generatePDFS3'
          description: 'Services to generate PDF from payload'
    resources:
      - path: '/create'
        description: 'Upload the PDF from payload data'

configValidationMode: off

package:
  excludeDevDependencies: true

plugins:
  - serverless-plugin-typescript
  - serverless-aws-documentation
  - serverless-offline

functions:
  generatePdf:
    # handler: src/api/generate.pdf
    images: 498157479666.dkr.ecr.ap-southeast-1.amazonaws.com/automate-pdf:latest@sha256:98e17f123e538564dff238122cc31ab38ddf1e735e4cc5f7be853cc2cc5e1dee
      # name: appimage
      # command:
      #   - src/api/generate.pdf
      # entryPoint:
      #   - 'entry.sh'

    description: A lambda handler that generates PDF file from payload data and upload it to S3 bucket.
    memorySize: 2048
    provisionedConcurrency: 2
    events:
      - http:
          path: pdf
          method: POST
          cors: true
          documentation:
            summary: Generates PDF from payload
            tags:
              - generatePdfS3
```

### Command name and used flags

serverless deploy

### Command output

```shell
Deploying pdf-api to stage dev (ap-southeast-1)

Packaging
Compiling with Typescript...
Using local tsconfig.json - tsconfig.json

✖ Stack pdf-api-dev failed to deploy (0s)
Environment: darwin, node 17.4.0, framework 3.22.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read properties of undefined (reading 'split')
    at /Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/typescript.js:57:33
    at Array.map (<anonymous>)
    at Object.extractFileNames (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/typescript.js:56:10)
    at TypeScriptPlugin.get rootFileNames [as rootFileNames] (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:102:27)
    at TypeScriptPlugin.<anonymous> (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:159:59)
    at Generator.next (<anonymous>)
    at /Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:4:12)
    at TypeScriptPlugin.compileTs (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:143:16)
    at TypeScriptPlugin.<anonymous> (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:58:28)
    at Generator.next (<anonymous>)
    at /Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:4:12)
    at before:package:createDeploymentArtifacts (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless-plugin-typescript/dist/src/index.js:57:63)
    at PluginManager.runHooks (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/classes/plugin-manager.js:563:20)
    at async PluginManager.spawn (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/plugins/deploy.js:40:11)
    at async PluginManager.runHooks (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/lib/serverless.js:174:5)
    at async /Users/rijwan/code/second/automate-pdf-api/node_modules/serverless/scripts/serverless.js:771:9
```

### Environment information

```shell
node14
```
