### ISSUE TITLE
Allow environment variables based on structured objects, serialized with Fn::ToJsonString

### ISSUE THREAD

**Issue by ronkorving** [serverless/serverless#11409]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

In light of https://aws.amazon.com/about-aws/whats-new/2022/09/aws-cloudformation-new-language-extensions-transform/, it would be nice if a Lambda's environment variable could be crafted like this:

```
FOO_BAR: !Base64 !ToJsonString ${self:custom.some.deep.object}
```

I've tried several variations on this syntax, but inevitably I always end up with an `unsupported object format` error.

**Comment by medikoo** [comment]
@ronkorving thanks for openning that. It appears that our internal schema needs to be updated to support those new functions.

e.g. this is where we define allowed syntax for `environment`: https://github.com/serverless/serverless/blob/b95c7496ec4a49aef756692a1ef59b61e2d95d4b/lib/plugins/aws/provider.js#L561-L571

PR that improves that is welcome!

**Comment by jurriaanpro** [comment]
It seems that to be able to use `Fn::ToJsonString` (and `Fn::Length`) one needs to include the `AWS::LanguageExtensions` transform.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html

Should this be added to `lib/plugins/aws/package/lib/core-cloudformation-template.json` or would the user be required to add this under the `resources:` segment like so?

```yaml
service: aws-node-http-api-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

custom:
  some:
    deep:
      object:
        keyA: valueA

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
    environment:
      FOO_BAR:
        Fn::ToJsonString: ${self:custom.some.deep.object}

resources:
  Transform:
    - AWS::LanguageExtensions
    - SomeOtherMacro
```

Also good to know maybe:
> Short-form YAML syntax isn't supported within a template for intrinsic functions provided by the AWS::LanguageExtensions transform

Could you give some guidance on how to proceed @medikoo?
