### ISSUE TITLE
Support legacy cache settings for CloudFront

### ISSUE THREAD

**Issue by godu** [serverless/serverless#11410]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless doesn't support the legacy cache settings for cloudfront events. There is [some cases](https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-authorization-header/?nc1=h_ls) where AWS recommends to use it.

Serverless generate

```
"CloudFrontDistribution": {
      "Type": "AWS::CloudFront::Distribution",
      "Properties": {
        "DistributionConfig": {
          "Comment": "cloudfront dev",
          "Enabled": true,
          "DefaultCacheBehavior": {
            "ViewerProtocolPolicy": "allow-all",
            "MaxTTL": 0,
            "MinTTL": 0,
            "DefaultTTL": 0,
            "ForwardedValues": {
              "QueryString": true,
              "Cookies": {
                "Forward": "none"
              }
            },
            "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",
            "TargetOriginId": "custom/google.com",
            "LambdaFunctionAssociations": [
              {
                "EventType": "origin-request",
                "LambdaFunctionARN": {
                  "Ref": "PassThroughLambdaVersion28byJfevyEHabjRi2s8Ymoq4ZN5ReW4oOg85Ai1yfiw"
                }
              }
            ]
          },
          "Origins": [
            {
              "DomainName": "google.com",
              "OriginPath": "",
              "CustomOriginConfig": {
                "OriginProtocolPolicy": "https-only",
                "OriginSSLProtocols": [
                  "TLSv1.2"
                ]
              },
              "Id": "custom/google.com"
            }
          ]
        }
      }
    }
  }
```
`ForwardedValues` is ignored if `CachePolicyId` is defined.

### Service configuration (serverless.yml) content

```yaml
service: cloudfront

provider:
  name: aws

functions:
  passThrough:
    handler: src/cloudfront.passThrough
    events:
      - cloudFront:
          eventType: origin-request
          isDefaultOrigin: true
          origin:
            # Id: explorer
            DomainName: 'google.com'
            OriginPath: ""
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
          behavior:
            MaxTTL: 0
            MinTTL: 0
            DefaultTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
```

### Command name and used flags

serverless package

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
