### ISSUE TITLE
individually packaged functions not grabbing correct artifact

### ISSUE THREAD

**Issue by brandonin** [serverless/serverless#11414]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Very similar to: https://github.com/serverless/serverless/issues/11158.

When attempting to utilize s3 artifacts for deployments, it continues to utilize a local path in order to determine artifact location.

The value of `functionObject` from `const functionObject = this.serverless.service.getFunction(functionName);` contains the artifact path of:
```
    package:
     artifact: '/$PWD/.serverless/add-data.zip
```
rather than pathing to the s3 bucket and silently failing in `serverless/lib/plugins/aws/package/compile/functions.js:105`.

### Service configuration (serverless.yml) content

```yaml
package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

functions:
  addData:
    handler: addData.main
    package:
      artifact: s3://some-bucket/add-data.zip
    events:
      - http:
          path: add-data/{code}
          method: post
```

### Command name and used flags

serverless deploy and serverless package

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.22.0 (local) 3.22.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
