### ISSUE TITLE
sls deploy not waiting for MFA to be entered

### ISSUE THREAD

**Issue by dandowd** [serverless/serverless#11417]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

`sls deploy` does not wait for user input when MFA is required.

Steps to reproduce:

1. Add a non-default entry to `.aws/config`
2. Add export AWS_SDK_LOAD_PROFILE=1 to you shell rc file
3. Add mfa_serial, role_arn, and source_profile to non-default entry
4. Run AWS_PROFILE=_profileName_ sls deploy

Below is an example

`
[profile deploy]
mfa_serial = _mfaSerial_
role_arn = _roleArn_
source_profile = default

[default]
region = us-east-2
`

### Service configuration (serverless.yml) content

```yaml
service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
```

### Command name and used flags

AWS_PROFILE=deploy sls deploy

### Command output

```shell
Command does not wait for user input at "Enter MFA code for ${mfaSerial}: "
```

### Environment information

```shell
export AWS_SDK_LOAD_PROFILE=1
AWS_PROFILE=deploy 

Framework Core: 3.22.0
Plugin: 6.2.2
SDK: 4.3.2
```
