### ISSUE TITLE
API gateway timeout not updating

### ISSUE THREAD

**Issue by miniplus** [serverless/serverless#11423]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

According to the docs, the default Http API Gateway timeout is 30s. This seems to be incorrect as we initially didn't specify a timeout and the timeout was set to 6500ms when looking in the AWS console UI.

Afterwards we set the timeout to 30s in both as both `provider.timeout` and `functions.main.timeout`.
The timeout setting for the lambda changed correctly to the requested timeout (30 in the example below). The API gateway however, remained unchanged. (6500ms).

After deleting the CloudFormation stack and redeploying from scratch, the timeout of 30s got set correctly on both Lambda and API gateway.

The expected behaviour is for the API gateway timeout to also update, just as the lambda does.

### Service configuration (serverless.yml) content

```yaml
service: test-service

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30

functions:
  main:
    handler: server/index.handler
    events:
      - httpApi: "*"
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.22.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
