### ISSUE TITLE
Add support for AWS Parameters and Secrets Lambda Extension

### ISSUE THREAD

**Issue by m4t22** [serverless/serverless#11456]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS has just announced https://aws.amazon.com/about-aws/whats-new/2022/10/aws-parameters-secrets-lambda-extension/ it sounds really great and it would be great to have an ability to set it up using serverless framework.

**Comment by medikoo** [comment]
@m4t22 can you propose what would be a solution on grounds of a Serverless Framework?

**Comment by fredericgboutin-yapla** [comment]
Just to add up to it, using the [AWS Parameter and Secrets Lambda extension](http://aws.amazon.com/blogs/compute/using-the-aws-parameter-and-secrets-lambda-extension-to-cache-parameters-and-secrets/) make it difficult to `invoke` locally a lambda function using this layer.

I don't know if there is an issue or a known limitation about "emulating" layers, but this use case is definitely affected.

**Comment by kayoMichael** [comment]
It worked for me when I added the extension by adding the arn directly to the layer inside the function.
Example:
```
functions: 
     function_name:
           layers:
               - rn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
```
https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-integration-lambda-extensions.html#ps-integration-lambda-extensions-add
