### ISSUE TITLE
False schema validation errors within Resources section in serverless.yml

### ISSUE THREAD

**Issue by orshemtov** [serverless/serverless#11474]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi,

Im using VSCode and the Serverless IDE extension, and the JSON schema "Serverless Framework Configuration"

This is the schema:
https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/reference.json

![image](https://user-images.githubusercontent.com/64565195/197879974-198c436a-0ae3-4ab5-9c5c-5ce4b1169c43.png)

For some reason, almost all AWS resources show an error in schema validation when defined under `resources.Resources` section, like so:

![image](https://user-images.githubusercontent.com/64565195/197880071-6bbe041c-379d-4b8a-9521-
58db0e17e396.png)

For some odd reason, it expects every resource I put in to be of type `AWS::AmazonMQ::Broker`:

![image](https://user-images.githubusercontent.com/64565195/197880247-41459871-590b-4dca-b565-c11e4030607d.png)

### Service configuration (serverless.yml) content

```yaml
service: sniper

frameworkVersion: "3"

plugins:
  - serverless-python-requirements
  - serverless-step-functions

custom:
  tradestation: ${ssm:/aws/reference/secretsmanager/tradestation}

  signalsTable: signals-${self:provider.stage}
  watchlistTable: watchlist-${self:provider.stage}
  tradesTable: trades-${self:provider.stage}
  renkoDatabaseName: renko-${self:provider.stage}
  renkoTableName: renko-bars-${self:provider.stage}
  stepFunctionRoleName: step-function-role-${self:provider.stage}

  pythonRequirements:
    layer: true
    noDeploy:
      - pytest
      - black
      - flake8
      - mypy
      - pandas

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  tags:
    env: ${self:provider.stage}
    service: sniper
    version: 0.1.0

  environment:
    TRADESTATION_ACCOUNT_ID: ${self:custom.tradestation.ACCOUNT_ID}
    TRADESTATION_CLIENT_ID: ${self:custom.tradestation.CLIENT_ID}
    TRADESTATION_CLIENT_SECRET: ${self:custom.tradestation.CLIENT_SECRET}
    SIGNALS_TABLE: ${self:custom.signalsTable}
    TRADES_TABLE: trades-${self:provider.stage}
    RENKO_TABLE: ${self:custom.renkoTableName}
    RENKO_DATABASE: ${self:custom.renkoDatabaseName}

  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action: "s3:*"
    - Effect: Allow
      Resource: "*"
      Action: "timestream:*"
    - Effect: Allow
      Resource: "*"
      Action: "ses:*"
    - Effect: Allow
      Resource: "*"
      Action: "dynamodb:*"

  layers:
    - !Ref PythonRequirementsLambdaLayer

functions:
  send_order:
    handler: functions.send_order.lambda_handler
    events:
      - httpApi:
          path: /api/orders
          method: post

  get_orders:
    handler: functions.get_orders.lambda_handler
    events:
      - httpApi:
          path: /api/orders
          method: get

  adjust_stop_loss:
    handler: functions.adjust_stop_loss.lambda_handler
    events:
      - httpApi:
          path: /api/orders/sl/{symbol}
          method: put

  adjust_take_profit:
    handler: functions.adjust_take_profit.lambda_handler
    events:
      - httpApi:
          path: /api/orders/tp/{symbol}
          method: put

  get_positions:
    handler: functions.get_positions.lambda_handler
    events:
      - httpApi:
          path: /api/positions
          method: get

  get_position:
    handler: functions.get_position.lambda_handler
    events:
      - httpApi:
          path: /api/positions/{symbol}
          method: get

  get_balances:
    handler: functions.get_balances.lambda_handler
    events:
      - httpApi:
          path: /api/balances
          method: get

  get_quote:
    handler: functions.get_quote.lambda_handler
    events:
      - httpApi:
          path: /api/quote/{symbol}
          method: get

  get_quotes:
    handler: functions.get_quotes.lambda_handler
    events:
      - httpApi:
          path: /api/quotes/{symbols}
          method: get

  create_signal:
    handler: functions.create_signal.lambda_handler
    events:
      - httpApi:
          method: post
          path: /api/signals

  get_signals:
    handler: functions.get_signals.lambda_handler
    events:
      - httpApi:
          method: get
          path: /api/signals

  write_renko_bar:
    handler: functions.write_renko_bar.lambda_handler
    events:
      - httpApi:
          path: /api/renko
          method: post

  read_renko_bars:
    handler: functions.read_renko_bars.lambda_handler
    layers:
      - arn:aws:lambda:us-east-1:xxxxxxx:layer:pandas-lambda-layer:1
    events:
      - httpApi:
          path: /api/renko/{symbol}
          method: get

  execute_order:
    handler: functions.execute_order.lambda_handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt SignalsTable.StreamArn
          maximumRetryAttempts: 3

  clear_positions:
    handler: functions.clear_positions.lambda_handler
    events:
      - schedule: cron(55 22 ? * MON-FRI *)

  send_signal_email:
    handler: functions.emails.send_signal_email.lambda_handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt SignalsTable.StreamArn
          maximumRetryAttempts: 3

  send_eod_email:
    handler: functions.emails.send_eod_email.lambda_handler
    environment:
      API_GATEWAY_ID: ...
    events:
      - schedule: cron(55 22 ? * MON-FRI *)

resources:
  Resources:
    RenkoBarsDatabase:
      Type: AWS::Timestream::Database
      Properties:
        DatabaseName: ${self:custom.renkoDatabaseName}

    RenkoBarsTable:
      Type: AWS::Timestream::Table
      DependsOn: RenkoBarsDatabase
      Properties:
        DatabaseName: ${self:custom.renkoDatabaseName}
        TableName: ${self:custom.renkoTableName}

    SignalsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.signalsTable}
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S

    TradesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tradesTable}
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S

    WatchlistTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.watchlistTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: symbol
            AttributeType: S
          - AttributeName: updated_at
            AttributeType: S
        KeySchema:
          - AttributeName: symbol
            KeyType: HASH
          - AttributeName: updated_at
            KeyType: RANGE

    StateMachineRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.stepFunctionRoleName}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - states.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: statesPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Resource: arn:aws:lambda:*
                  Action: lambda:InvokeFunction

stepFunctions:
  validate: true
  stateMachines:
    EvaluatePosition:
      role:
        Fn::GetAtt: ["StateMachineRole", "Arn"]
      definition:
        StartAt: Evaluate
        States:
          Evaluate:
            Type: Pass
            Next: Choice

          Choice:
            Type: Choice
            Choices:
              - And:
                  - Variable: $.timePassed
                    NumericGreaterThanEquals: 3
                  - Variable: $.timePassed
                    NumericLessThanEquals: 10
                Next: Adjust Position
              - Variable: $.timePassed
                NumericGreaterThanEquals: 10
                Next: Close Position
            Default: Wait

          Wait:
            Type: Wait
            Seconds: 30
            Next: Evaluate

          Close Position:
            Type: Pass
            Next: Success

          Adjust Position:
            Type: Pass
            Next: Wait

          Success:
            Type: Succeed
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
VSCode 1.72.2
Serverless IDE 0.5.34
```
