### ISSUE TITLE
ApiGatewayV2 HTTP API Integration with Subtype SQS-SendMessage Fails with 400

### ISSUE THREAD

**Issue by miguelespinoza** [serverless/serverless#11486]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm working on an API Gateway HTTP API Integration with subtype `SQS-SendMessage`, and I get an error, that operation `SQS-SendMessage` is not suppported. I've gone through the same process with the aws cli and it works.

How could I debug this issue?

### Service configuration (serverless.yml) content

```yaml
resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 345600
        QueueName: ${self:custom.currentStage}-queue
        VisibilityTimeout: 180
    IAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - apigateway.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.currentStage}-collect-http-api-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Action: sqs:SendMessage
                  Effect: Allow
                  Resource: !GetAtt Queue.Arn
                - Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Effect: Allow
                  Resource: '*'
    Integration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: ${param:CoreHttpAPIRef}
        Description: Proxy incoming HTTP Payload into SQS
        IntegrationSubtype: SQS-SendMessage
        IntegrationType: AWS_PROXY
        ConnectionType: INTERNET
        PayloadFormatVersion: 1.0
        CredentialsArn: !GetAtt IAMRole.Arn
        RequestParameters:
          QueueUrl: !Ref Queue
          MessageBody: $request.body
    Route:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: ${param:CoreHttpAPIRef}
        RouteKey: GET /path
        Target: !Sub integrations/${Integration}
```

### Command name and used flags

serverless service:deploy --stage staging --verbose

### Command output

```shell
service › Error:
service › CREATE_FAILED: Integration (AWS::ApiGatewayV2::Integration)
service › Operation: SQS-SendMessage is not supported. (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: xxxx-xxx-xx-xx-xx; Proxy: null)
service › 
service › View the full error: https://us-east-1.console.aws.amazon.com/cloudformation/xxxx
service ›
```

### Environment information

```shell
Framework Core: 3.23.0 (local) 3.22.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
