### ISSUE TITLE
AWS IoT event source doesn't respect "provisionedConcurreny" setting.

### ISSUE THREAD

**Issue by ui-guang-de-lin** [serverless/serverless#11484]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

It looks like the AWS IoT event source doesn't respect `provisioned` alias when `provisionedConcurreny` is set. I checked `lib/plugins/aws/package/compile/events/iot.js` and it doesn't deal with lambda function aliases like how ApiGateway event source does in `lib/plugins/aws/package/compile/events/api-gateway/lib/method/index.js`.

### Service configuration (serverless.yml) content

```yaml
functions:
  function-with-provisioned-concurrency:
    handler: com.foobar.MyHandler
    provisionedConcurrency: 1
    events:
      - iot:
          sql: "SELECT *, topic(2) as deviceId FROM 'foobar/+'"
          sqlVersion: "beta"
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
$ serverless --version
Framework Core: 3.15.0
Plugin: 6.2.2
SDK: 4.3.2
```
