### ISSUE TITLE
 REST API (API Gateway v1) Cognito User Pool authorizer ImportValue validation

### ISSUE THREAD

**Issue by franzmango** [serverless/serverless#11492]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

```
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:xxx:userpool/us-east-1_ZZZ
            scopes:
              - my-app/read
```

This is an outtake from Serverless documentation that shows how to set up Cognito User Pool authorizer with custom scopes.

Using CloudFormation Fn::ImportValue functions as scope items raises a validation warning (soon to be an error in the next version, I understand), but the values passed on to CloudFormation template work as intended, importing the values as AuthorizationScopes for the API GW method.

```
Warning: Invalid configuration encountered
  at 'functions.function-name.events.0.http.authorizer.scopes.0': must be string
```

### Proposed solution (optional)

Allow the value to be an intrinsic function 😄
Or update the documentation, if I am using it wrong. I did not find the option at all in serverless.yml reference.
https://www.serverless.com/framework/docs/providers/aws/events/apigateway#http-endpoints-with-custom-authorizers

EDIT: I accidentally pressed enter before completing the issue
