### ISSUE TITLE
The CloudFormation template is invalid: Circular dependency between resources

### ISSUE THREAD

**Issue by calexandrepcjr** [serverless/serverless#11499]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm having a Circular dependency problem, and since yesterday, I searched through all the forum/gitter history, and I couldn't find anything that could help me. The error is:

`The CloudFormation template is invalid: Circular dependency between resources: [12NestedStack, 1NestedStack, 11NestedStack, ApiGatewayResourceOfferingOfferingidVarRequirement, 19NestedStack, 2NestedStack, 10NestedStack, 20NestedStack, 9NestedStack, ApiGatewayDeployment1667571081871, 14NestedStack, 4NestedStack, ApiGatewayResourceOfferingOfferingidVarRequirementRequirementidVar]`

![image](https://user-images.githubusercontent.com/4068993/200001114-1461765e-b4b3-41bb-9da5-94dbcdc432d5.png)

The above image is the grep of the claimed resource in the generated pkg.

I've tried changing the URIs, but nothing worked.
When I generate the package locally, everything works. Also, the serverless offline runs...

It started to happen after adding the createRequirement, getRequirement, updateRequirement, removeRequirement resources.

### Service configuration (serverless.yml) content

```yaml
service: amp-serverless
useDotenv: true
configValidationMode: error

# Packaging functions separately
package:
  individually: true
  patterns:
    - "migrations/**"
    - "seeders/**"
    - "!src/functions/**"
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
    # by default exclude above

# You can pin your service to only deploy with a specific Serverless version
frameworkVersion: "3"

provider:
  name: aws
  runtime: ${env:NODEJS_VERSION_SLS, 'nodejs16.x'}
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  memorySize: 256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  authorize:
    handler: src/functions/auth/authorize.auth
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  infraAuthorizer:
    handler: src/functions/infra/authorize.auth
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  runMigrations:
    handler: src/functions/infra/migrator.handler
    timeout: 20
    events:
      - http:
          path: /infra/migrator
          method: post
          cors: true
          authorizer:
            name: infraAuthorizer

  runSeeds:
    handler: src/functions/infra/seeder.handler
    timeout: 20
    events:
      - http:
          path: /infra/seeder
          method: post
          cors: true
          authorizer:
            name: infraAuthorizer

  signup:
    handler: src/functions/signup/index.handler
    timeout: 20
    events:
      - http:
          path: /auth/signup
          method: post
          cors: true
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  account:
    handler: src/functions/account/index.handler
    timeout: 20
    events:
      - http:
          path: /account
          method: any
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  health:
    handler: src/functions/health/index.handler
    timeout: 20
    events:
      - http:
          path: /health
          method: get
          cors: true
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  getBusiness:
    handler: src/functions/business/getBusiness.handler
    timeout: 20
    events:
      - http:
          path: /business
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  updateBusiness:
    handler: src/functions/business/update.handler
    timeout: 20
    events:
      - http:
          path: /business
          method: put
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  listOfferings:
    handler: src/functions/offering/listOfferings.handler
    timeout: 20
    events:
      - http:
          path: /offerings
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  applyOffering:
    handler: src/functions/offering/apply.handler
    timeout: 20
    events:
      - http:
          path: /offering/{offeringId}/apply
          method: post
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  getApplicants:
    handler: src/functions/fundingPartner/getApplicants.handler
    timeout: 20
    events:
      - http:
          path: /partner/applicants
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  updateApplication:
    handler: src/functions/fundingPartner/updateApplication.handler
    timeout: 20
    events:
      - http:
          path: /partner/updateApplication/{id}
          method: put
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"


  getAllBusiness:
    handler: src/functions/fundingPartner/getAllBusiness.handler
    timeout: 20
    events:
      - http:
          path: /partner/business_directory
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  createRequirement:
    handler: src/functions/offering/requirement/create.handler
    timeout: 20
    events:
      - http:
          path: /offering/{offeringId}/requirement
          method: post
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  getRequirement:
    handler: src/functions/offering/requirement/read.handler
    timeout: 20
    events:
      - http:
          path: /offering/{offeringId}/requirement/{requirementId}
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  updateRequirement:
    handler: src/functions/offering/requirement/update.handler
    timeout: 20
    events:
      - http:
          path: /offering/{offeringId}/requirement/{requirementId}
          method: put
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  removeRequirement:
    handler: src/functions/offering/requirement/delete.handler
    timeout: 20
    events:
      - http:
          path: /offering/{offeringId}/requirement/{requirementId}
          method: delete
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  getProgramById:
    handler: src/functions/business/getProgramById.handler
    timeout: 20
    events:
      - http:
          path: /business/program/{id}
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  getLoanByIdForBusiness:
    handler: src/functions/business/getLoanById.handler
    timeout: 20
    events:
      - http:
          path: /business/loan/{id}
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  getAppliedLoans:
    handler: src/functions/business/getAppliedLoans.handler
    timeout: 20
    events:
      - http:
          path: /business/appliedLoans
          method: get
          cors: true
          authorizer: authorize
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  idealMatch:
    handler: src/functions/idealMatch/index.handler
    memorySize: 2048
    events:
      - http:
          path: /ideal_match
          method: post
      - sns:
          arn: arn:aws:sns:us-east-1:939705357057:idealMatch
          topicName: idealMatch
          displayName: Ideal Match generation pipeline
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

  # RETOOL ----------------------------------------------------
  createAdminFields:
    handler: src/functions/retool/createAdminFields.handler
    timeout: 20
    package:
      patterns:
        - "!migrations/**"
        - "!seeders/**"

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-plugin-split-stacks
  - serverless-offline

custom:
  splitStacks:
    perFunction: false
    perType: false
    perGroupFunction: true
    nestedStackCount: 20
    stackConcurrency: 5 # Controls if enabled and how much stacks are deployed in parallel. Disabled if absent.
    resourceConcurrency: 10
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'
  serverless-offline:
    ignoreJWTSignature: true
```

### Command name and used flags

serverless deploy --stage ${STAGE} --aws-s3-accelerate

### Command output

```shell
Deploying amp-serverless to stage pg-16 (us-east-1)
Compiling with Typescript...
Using local tsconfig.json - ./tsconfig.build.json
Typescript compiled.
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-include-dependencies]: WARNING missing optional dependency: pg-native
[serverless-plugin-split-stacks]: Summary: 155 resources migrated in to 13 nested stacks
[serverless-plugin-split-stacks]:    Resources per stack:
[serverless-plugin-split-stacks]:    - (root): 24
[serverless-plugin-split-stacks]:    - 10NestedStack: 36
[serverless-plugin-split-stacks]:    - 11NestedStack: 7
[serverless-plugin-split-stacks]:    - 12NestedStack: 20
[serverless-plugin-split-stacks]:    - 14NestedStack: 9
[serverless-plugin-split-stacks]:    - 16NestedStack: 5
[serverless-plugin-split-stacks]:    - 18NestedStack: 3
[serverless-plugin-split-stacks]:    - 19NestedStack: 20
[serverless-plugin-split-stacks]:    - 1NestedStack: 13
[serverless-plugin-split-stacks]:    - 20NestedStack: 7
[serverless-plugin-split-stacks]:    - 2NestedStack: 5
[serverless-plugin-split-stacks]:    - 4NestedStack: 14
[serverless-plugin-split-stacks]:    - 7NestedStack: 8
[serverless-plugin-split-stacks]:    - 9NestedStack: 8
Using S3 Transfer Acceleration Endpoint...
Using S3 Transfer Acceleration Endpoint...

× Stack amp-serverless-pg-16 failed to deploy (120s)
Environment: linux, node 16.18.0, framework 3.20.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Error:
The CloudFormation template is invalid: Circular dependency between resources: [12NestedStack, 1NestedStack, 11NestedStack, ApiGatewayResourceOfferingOfferingidVarRequirement, 19NestedStack, 2NestedStack, 10NestedStack, 20NestedStack, 9NestedStack, ApiGatewayDeployment1667571081871, 14NestedStack, 4NestedStack, ApiGatewayResourceOfferingOfferingidVarRequirementRequirementidVar]
```

### Environment information

```shell
Framework Core: 3.20.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
