### ISSUE TITLE
Getting serverless error "Cannot read properties of null (reading 'package')" when triggering lambda function locally or even when tried deploying to github actions

### ISSUE THREAD

**Issue by ShahzaiibJogo** [serverless/serverless#11491]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [x] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I tried to invoke lambda function locally, I got this error and even when I deployed these lambda function by using github CI/CD eventually I had the same error.

TypeError: Cannot read properties of null (reading 'package') at D:\node.js\express.js\cms-updates-consumer\node_modules\serverless\lib\plugins\package\package.js:46:39

### Service configuration (serverless.yml) content

```yaml
service: cms-update-consumer

provider:
    name: aws
    runtime: nodejs14.x
    stage: dev
    region: us-east-1
    memorySize: 1024
    timeout: 10
    
plugins:
    - serverless-prune-plugin

custom:
    prune:
        automatic: true
        number: 3

layers:
    nodedependencies:
        path: layers # required, path to layer contents on disk
        description: Nodejs dependencies layer
        compatibleRuntimes: 
            - nodejs14.x
        licenseInfo: "MIT"
    localnodedependencies:

functions:
    addArticlesCMSConsumer:
        timeout: 10
        handler: lambdas/articles/Index.handler
        events:
            - http:
                path: /
                method: GET
                cors: true
        layers:
            - {Ref: NodedependenciesLambdaLayer}
```

### Command name and used flags

serverless invoke local --function addArticlesCMSConsumer

### Command output

```shell
$ serverless invoke local --function addArticlesCMSConsumer
Running "serverless" from node_modules
Environment: win32, node 16.14.2, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot read properties of null (reading 'package')
    at D:\node.js\express.js\cms-updates-consumer\node_modules\serverless\lib\plugins\package\package.js:46:39
    at Array.some (<anonymous>)
    at initialize (D:\node.js\express.js\cms-updates-consumer\node_modules\serverless\lib\plugins\package\package.js:45:63)
    at PluginManager.run (D:\node.js\express.js\cms-updates-consumer\node_modules\serverless\lib\classes\plugin-manager.js:598:65)
    at Serverless.run (D:\node.js\express.js\cms-updates-consumer\node_modules\serverless\lib\serverless.js:174:30)
    at async D:\node.js\express.js\cms-updates-consumer\node_modules\serverless\scripts\serverless.js:771:9
```

### Environment information

```shell
Framework Core: 3.22.0 (local) 3.22.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
