### ISSUE TITLE
serverless deploy working on mac, not windows - No file matches include / exclude patterns

### ISSUE THREAD

**Issue by HancoVisagie** [serverless/serverless#11514]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [ ] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi, 

The issue I am encountering is strange, we use serverless in combination with aws and dotnet 6. 
At work I use a macbook, at home I use a windows machine, when I try to deploy the exact same serverless.yml file from my windows machine I get the following error: 

`No file matches include / exclude patterns`

the strange thing is I am not using any include/exclude patterns, only specifying a path to the artifact. See my serverless below

I have removed most of the garbage such as Iam permissions, and all the functions, but it comes down to this, even trying to deploy this fails, and again, the full exact same file works when deploying on mac

### Service configuration (serverless.yml) content

```yaml
frameworkVersion: '^3.1.0'
service: 'xxx'

provider:
  name: 'aws'
  runtime: 'dotnet6'
  profile: '${self:provider.stage}'
  vpc: '${self:custom.vpc}'
  stage: '${opt:stage, ''dev''}'
  region: 'eu-west-1'
  timeout: 60
  versionFunctions: 'false'
  tracing:
    apiGateway: true
    lambda: true
  memorySize: 3072
  stackTags: # Optional CF stack tags
    Service: '${self:service}'
  deploymentBucket:
    name: 'xxx-deploys-${self:provider.region}-${self:provider.stage}'
    maxPreviousDeploymentArtifacts: '10'
  iam:
    xxx

plugins:
  - 'serverless-plugin-tracing'
  - 'serverless-plugin-warmup'
  - 'serverless-function-outputs'

custom: '${file(serverless_variables.yml)}'

package:
  artifact: 'bin/release/net6/deploy-package.zip'

functions:
  OnDeployed:
    handler: '${self:custom.handler.prefix}.LambdaEventsHandler::OnDeployed'
    timeout: 300
    warmup:
      default:
        enabled: false

resources: ${file(serverless_resources.yml)}
```

### Command name and used flags

serverless deploy

### Command output

```shell
× Stack xxx-xxx-xxx failed to deploy (1s)
Environment: win32, node 16.13.2, framework 3.24.1, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "xxx" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No file matches include / exclude patterns
```

### Environment information

```shell
Framework Core: 3.24.1
Plugin: 6.2.2
SDK: 4.3.2
```
