### ISSUE TITLE
'Unable to load virtualenv, please install\n'

### ISSUE THREAD

**Issue by rrdlpl** [serverless/serverless#11513]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Can't package my service

'Unable to load virtualenv, please install\n'

Requirements.txt
```
Brotli==1.0.9
cffi==1.15.1
click==8.1.3
cssselect2==0.7.0
Flask==2.2.2
flask_weasyprint==1.0.0
fonttools==4.38.0
html5lib==1.1
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.1
pango==0.7.6
Pillow==9.3.0
pycparser==2.21
pydyf==0.5.0
pyphen==0.13.0
serverless-wsgi==1.7.6
six==1.16.0
tinycss2==1.2.1
weasyprint==57.1
webencodings==0.5.1
Werkzeug==2.2.2
zopfli==0.2.1
```

### Service configuration (serverless.yml) content

```yaml
service: example

provider:
  name: aws
  runtime: python3

plugins:
  - serverless-wsgi

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: app.app
```

### Command name and used flags

sls package | sls deploy

### Command output

```shell
Packaging example for stage dev (us-east-1)
Using Python specified in "runtime": python3
Packaging Python WSGI handler...
Packaging required Python packages...
Environment: darwin, node 16.13.1, framework 3.24.1, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
'Unable to load virtualenv, please install\n'
```

### Environment information

```shell
Framework Core: 3.24.1
Plugin: 6.2.2
SDK: 4.3.2

macOS Monterrey
version 12.0.1
chip: Apple M1 Pro
```
