### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'Properties') when i try to deploy to serverless

### ISSUE THREAD

**Issue by uncleboss12** [serverless/serverless#11530]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

the issues started after i deleted the repo of the project i was working on and clone it again. I do not know why it is not working as it was before 

### Service configuration (serverless.yml) content

```yaml
org: uncleboss12
app: serverless-todo-app
service: serverless-todo-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  # Use these variables in the functions and resouorces section below. For example, 
  # ${self:provider.environment.ATTACHMENT_S3_BUCKET}
  environment:
    TODOS_TABLE: Todos-${self:provider.stage}
    TODOS_CREATED_AT_INDEX: CreatedAtIndex
    ATTACHMENT_S3_BUCKET: serverless-c4-todo-images-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

  logs:
    # Enable API Gateway logs
    restApi: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - xray:PutTelemetryRecords
            - xray:PutTraceSegments
          Resource: "*"


functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # TODO: Configure this function - 
  # Provide iamRoleStatements property for performing Actions on DynamoDB
  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true
          authorizer: Auth

  # TODO: Configure this function - 
  # Provide iamRoleStatements property. Decide the Actions and AWS Resource. 
  # To refer to an AWS resource defined in the "Resources" section, you can use "Resource: !GetAtt <resource-name>.Arn"
  # To validate incoming HTTP requests, we have provided the request schemas in function definition below. 
  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
          authorizer: Auth
          request:
            schemas:
              application/json: ${file(models/create-todo-model.json)}

  # TODO: Configure this function
  # Provide property for setting up CORS, Authorizer, iamRoleStatements, and request schemas
  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}

  # TODO: Configure this function
  # Provide property for setting up CORS, Authorizer, iamRoleStatements
  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}

  # TODO: Configure this function
  # Provide property for setting up CORS, Authorizer, iamRoleStatements
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment

resources:
  Resources:
    # Add necessary AWS resources. You will need at least the following AWS resources
    # TODO: Fill the properties
    # Feel free to change the names as you like. 
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
    
    # TODO: Create a DynamoDB table with local secondary index and a composite key
    TodosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: todoId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: todoId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:provider.environment.TODOS_TABLE}
      LocalSecondaryIndexes:
        - IndexName: ${self:provider.environment.TODOS_CREATED_AT_INDEX}
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL # What attributes will be copied to an index

    # TODO: Complete the bucket properties below. 
    # Do not forget to add the CorsConfiguration propoerty
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:

    # TODO: Complete the policy below and attach it to the bucket defined above
    # For cross referencing the name of the bucket, use "!Ref AttachmentsBucket"
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
```

### Command name and used flags

serverless deploy --verbose 

### Command output

```shell
TypeError: Cannot read properties of null (reading 'Properties')
    at AwsPackage.stripNullPropsFromTemplateResources (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\plugins\aws\package\lib\strip-null-props-from-template-resources.js:18:20)
    at aws:package:finalize:stripNullPropsFromTemplateResources (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\plugins\aws\package\index.js:114:14)
    at PluginManager.runHooks (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:530:15)
    at PluginManager.invoke (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:564:20)
    at async PluginManager.spawn (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:585:5)
    at async PluginManager.runHooks (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:530:9)
    at async PluginManager.invoke (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:564:9)
    at async PluginManager.spawn (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:585:5)
    at async before:deploy:deploy (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\plugins\deploy.js:40:11)
    at async PluginManager.runHooks (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:530:9)
    at async PluginManager.invoke (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:563:9)
    at async PluginManager.run (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\classes\plugin-manager.js:604:7)
    at async Serverless.run (C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\lib\serverless.js:170:5)
    at async C:\Users\interactwel\Desktop\cloud-developer\course-04\project\c4-final-project-starter-code\backend\node_modules\serverless\scripts\serverless.js:787:9
```

### Environment information

```shell
× Stack serverless-todo-app-dev failed to deploy (427s)
Environment: win32, node 16.18.0, framework 3.24.1 (local) 3.24.1v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```
