### ISSUE TITLE
Sls automatically generates a lambda function with a deprecation  node version (12).

### ISSUE THREAD

**Issue by firas-tayeb-soniq** [serverless/serverless#11549]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi,

Context: It seems that AWS sands warnings recently (Starting November 14, 2022 Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions .... Node.js 12 End-Of-Life (EOL) reached on April 30, 2022).
Issue: When i am using lambda function event trigger of type ( `cognitoUserPool` and `trigger: PostAuthentication`  ) the serverless FW genereate **automatically** the lambda function called `CustomDashresourceDashexistingDashcupLambdaFunction` using **Node 12 as runtime which is NO longer supported !** , i belive that this issue is due to this piece of code [https://github.com/serverless/serverless/blob/ef526ea132e7f546f58a760f53ac6931d57522f8/lib/plugins/aws/customResources/index.js#L161-L171](url)
`        Properties: {
          Code: {
            S3Bucket,
            S3Key,
          },
          FunctionName: absoluteFunctionName,
          Handler,
          MemorySize: 1024,
          Runtime: 'nodejs12.x',
          Timeout: 180,
        },`
       
**Is there any chance to fix this ASAP.**

Kind regards

### Service configuration (serverless.yml) content

```yaml
functions:
  NameOfMyLambda:
    handler: './src/path/to/my/lambda/handler.handle'
    events:
      - cognitoUserPool:
          pool: ${cf:${self:custom.infrastructureStack}.UserPoolName}
          trigger: PostAuthentication
          existing: true
          forceDeploy: true
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
2
```
