### ISSUE TITLE
Error: Configuration error:       at 'provider.iam.role.statements.1.Action.0': must be string     

### ISSUE THREAD

**Issue by hari5udhan** [serverless/serverless#11541]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

module.export.updateCertificate = async (event) => {
  let certificationId= event.pathParameters.id;
  let data = JSON.parse(event.body);

  try{

    const params = {
      TableName: CERTIFICATE_TABLE_NAME,
      key: { certificationId },
      UpdateExpression: 'set #certificationName= :certificationName, #certificationProvider= :certificationProvider, #certificationLevel= :certificationLevel, #certificationValidationId= :certificationValidationId, #dateOfCertification= :dateOfCertification, #dateOfExpiry= :dateOfExpiry',
      ExpressionAttributeNames:{
        '#certificationName' : 'certificationName',
        '#certificationProvider' : 'certificationProvider',
        '#certificationLevel' : 'certificationLevel',
        '#certificationValidationId' : 'certificationValidationId',
        '#dateOfCertification' : 'dateOfCertification',
        '#dateOfExpiry' : 'dateOfExpiry'
      },
      ExpressionAttributeValues:{
        ':certificationName' : data.certificationName,
        ':certificationProvider' : data.certificationProvider,
        ':certificationLevel' : data.certificationLevel,
        ':certificationValidationId': data.certificationValidationId,
        ':dateOfCertification': data.dateOfCertification,
        ':dateOfExpiry': data.dateOfExpiry
      }
    }

   await documentClient.update(params).promise();
   cb(null,{
    statusCode: 200,
    body: JSON.stringify(data)
  });
  }catch(err){
    cb(null,{
      statusCode: 500,
      body: JSON.stringify(err.message)
    });

  }
  return {
    statusCode: 200,
    body: JSON.stringify("Certification updated! on"+certificationId)
  };
};

### Service configuration (serverless.yml) content

```yaml
service: certificate-api

frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - excute-api:Invoke
          Resource: arn:aws:execute-api:*:*:*
        - Effect: Allow
          Action:
            - dynamodb: UpdateItem
            - dynamodb: PutItem
          Resource: arn:aws:*************/certificate-table
```

### Command name and used flags

When I run serveless deploy I get this error!

### Command output

```shell
Error:
Configuration error: 
     at 'provider.iam.role.statements.1.Action.0': must be string
     at 'provider.iam.role.statements.1.Action.1': must be string

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Environment: darwin, node 18.12.1, framework 3.25.0, plugin 6.2.2, SDK 4.3.2
```
