### ISSUE TITLE
serverless.yaml issue : bug in httpApi template

### ISSUE THREAD

**Issue by RohitSaini15** [serverless/serverless#11550]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Using **httpApi** key in the function key which is not working. Use **http** instead of **httpApi** 

### Service configuration (serverless.yml) content

```yaml
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.25.0
Plugin: 6.2.2
SDK: 4.3.2
```
