### ISSUE TITLE
Cors options are being validated as incorrect while documentation states it is correct

### ISSUE THREAD

**Issue by funkel1989** [serverless/serverless#11557]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

https://www.serverless.com/framework/docs/providers/aws/events/http-api/

The above documentation shows the cors setup for the HTTP API v2 gateway. When followed as below, serverless validation says it is not valid.

```yml
frameworkVersion: ^3.25.0
configValidationMode: error
deprecationNotificationMode: error

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  logRetentionInDays: 3
  timeout: 29
  stackTags: ${self:custom.tags}
  tags: ${self:custom.tags}
  httpApi:
    cors:
      allowCredentials: true
      allowOrigins: 
        - 'dev.ipeslawn.com'
        - 'ipeslawn.com'
      allowMethods: '*'
      allowHeaders: '*'
```

Error:
```
Running "serverless" from node_modules
Environment: linux, node [14](https://github.com/Battle-Line-Productions/FrontlineCrm-Api/actions/runs/3559903364/jobs/5979572845#step:14:15).[21](https://github.com/Battle-Line-Productions/FrontlineCrm-Api/actions/runs/3559903364/jobs/5979572845#step:14:22).1, framework 3.[25](https://github.com/Battle-Line-Productions/FrontlineCrm-Api/actions/runs/3559903364/jobs/5979572845#step:14:26).0 (local) 3.25.0v (global), plugin 6.2.2, SDK 4.3.2
Error:
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Configuration error: 
     at 'provider.httpApi.cors': unrecognized property 'allowOrigins'
     at 'provider.httpApi.cors': unrecognized property 'allowMethods'
     at 'provider.httpApi.cors': unrecognized property 'allowHeaders'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Service configuration (serverless.yml) content

```yaml
service: FrontlineCrm-Api

frameworkVersion: ^3.25.0
configValidationMode: error
deprecationNotificationMode: error

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  logRetentionInDays: 3
  timeout: 29
  stackTags: ${self:custom.tags}
  tags: ${self:custom.tags}
  httpApi:
    cors:
      allowCredentials: true
      allowOrigins: 
        - 'dev.ipeslawn.com'
        - 'ipeslawn.com'
      allowMethods: '*'
      allowHeaders: '*'
  logs:
    httpApi:
      format: '{
        "requestId": "$context.requestId",
        "ip": "$context.identity.sourceIp",
        "requestTime": "$context.requestTime",
        "httpMethod": "$context.httpMethod",
        "routeKey": "$context.routeKey",
        "status": "$context.status",
        "errorMessage": "$context.error.message",
        "responseType": "$context.error.responseType",
        "path": "$context.path",
        "protocol": "$context.protocol",
        "responseLength": "$context.responseLength",
        "responseLatency": "$context.responseLatency",
        "integrationStatus": "$context.integrationStatus",
        "integrationLatency": "$context.integrationLatency",
        "integrationErrorMessage": "$context.integrationErrorMessage",
        "stage": "$context.stage",
        "dataProcessedInBytes": "$context.dataProcessed"
      }'
  iam:
    role:
      statements:
        - Action:
            - lambda:InvokeAsync
            - lambda:InvokeFunction
          Effect: Allow
          Resource: "*"
  environment:
    CryptoKey: ${ssm:/FrontlineCrm/${self:provider.stage}/db/cryptoKey}
    OAuthAuthority: ${self:custom.oAuthAuthorityMap.${self:provider.stage}}
    OAuthAudience: ${self:custom.oAuthAudienceMap.${self:provider.stage}}
    OAuthClientId: ${self:custom.oAuthClientIdMap.${self:provider.stage}}
    OAuthClientSecret: ${ssm:/FrontlineCrm/${self:provider.stage}/auth/clientSecret}
    AwsAccessKey: ${ssm:/FrontlineCrm/${self:provider.stage}/db/AwsAccessKey}
    AwsSecretKey: ${ssm:/FrontlineCrm/${self:provider.stage}/db/AwsSecretKey}
    ASPNETCORE_ENVIRONMENT: ${self:provider.stage}

plugins:
  - serverless-plugin-common-excludes
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-plugin-warmup
  - serverless-domain-manager

package:
  individually: true
  excludeDevDependencies: true

custom:
  warmerApiKey: ${ssm:/FrontlineCrm/${self:provider.stage}/warmer/ApiKey}
  tags:
    'app-id': '100101'
    'app-name': 'frontline-api-crm-dotnet7-lambda-container'
    'iac': 'serverless'
    'environment': '${sls:stage}'
    'development-team-email': 'awsadmin@battlelineproductions.com'
    'infrastructure-team-email': 'awsadmin@battlelineproductions.com'
    'infrastructure-engineer-email': 'awsadmin@battlelineproductions.com'
  includeDependencies:
    enableCaching: true
  prune:
    automatic: true
    includeLayers: true
    number: 10
  dynamoUserTableName: ${self:service}-${self:provider.stage}-Users
  dynamoProductTableName: ${self:service}-${self:provider.stage}-Products
  dynamoApiKeyTableName: ${self:service}-${self:provider.stage}-ApiKeys
  warmup:
    officeHoursWarmer:
      enabled: true
      verbose: true
      prewarm: true
      concurrency: 2
      payload:
        body: '${self:custom.domainMap.${self:provider.stage}} 483fefbe-3c66-4f59-8df9-21e904369b7a ${self:custom.warmerApiKey}'
  oAuthAuthorityMap:
    dev: battleline-dev.us.auth0.com
    prod: battleline-prod.us.auth0.com
  oAuthClientIdMap:
    dev: 'l3G1leVF5KtArDomitGP7t6IgNoNv7Md'
    prod: 'wmfibIFfjks0iKJRSLxjUx6uNhyLCQbN'
  oAuthAudienceMap:
    dev: https://dev-frontlinecrm-api.battlelineproductions.com/
    prod: https://frontlinecrm-api.battlelineproductions.com/
  domainMap:
    dev: dev-frontlinecrm-api.battlelineproductions.com
    prod: frontlinecrm-api.battlelineproductions.com
  certMap:
    dev: "*.battlelineproductions.com"
    prod: "*.battlelineproductions.com"
  imageMap:
    dev: 139279799285.dkr.ecr.us-east-2.amazonaws.com/frontline-crm-dev:${param:TAG}
    prod: 139279799285.dkr.ecr.us-east-2.amazonaws.com/frontline-crm-prod:${param:TAG}
  customDomain:
    domainName: ${self:custom.domainMap.${self:provider.stage}}
    endpointType: regional
    stage: ${self:provider.stage}
    createRoute53Record: false
    certificateName: ${self:custom.certMap.${self:provider.stage}}
    apiType: http

functions:
  api:
    name: ${self:service}-dotnet-lambda-${self:provider.stage}
    memorySize: 1024
    description: API lambda container for FrontlineCrm Api
    image:
      uri: ${self:custom.imageMap.${self:provider.stage}}
      command: 
        - FrontlineCrm.Api::FrontlineCrm.Api.LambdaEntryPoint::FunctionHandlerAsync
    events:
    - httpApi:
        path: /{proxy+}
        method: ANY


resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoUserTableName}
        AttributeDefinitions:
          - AttributeName: SourceSystemId
            AttributeType: S
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: SourceSystemId
            KeyType: HASH
          - AttributeName: Id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoProductTableName}
        AttributeDefinitions:
          - AttributeName: SourceSystemId
            AttributeType: S
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: SourceSystemId
            KeyType: HASH
          - AttributeName: Id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    apiKeyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoApiKeyTableName}
        AttributeDefinitions:
          - AttributeName: SourceSystemId
            AttributeType: S
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: SourceSystemId
            KeyType: HASH
          - AttributeName: Id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
```

### Command name and used flags

deploy --stage=dev  --param="TAG=${{ github.sha }}"

### Command output

```shell
Running "serverless" from node_modules
Environment: linux, node 14.21.1, framework 3.25.0 (local) 3.25.0v (global), plugin 6.2.2, SDK 4.3.2
Error:
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Configuration error: 
     at 'provider.httpApi.cors': unrecognized property 'allowOrigins'
     at 'provider.httpApi.cors': unrecognized property 'allowMethods'
     at 'provider.httpApi.cors': unrecognized property 'allowHeaders'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.25.0 (local) 3.21.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
