### ISSUE TITLE
Docker deploy doesn't work for AWS region eu-west-2

### ISSUE THREAD

**Issue by ben-msn** [serverless/serverless#11563]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When trying to deploy (`npx serverless deploy`) I get an error:

```
Error:
Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter.
```

I can repro this by running 
```
npx serverless create --template aws-nodejs-docker --path aws-nodejs-docker-demo
cd aws-nodejs-docker-demo
npx serverless deploy
```
and changing the serverless.yml to specify AWS region eu-west-2 (see full serverless.yml below). If I don't specify eu-west-2 then the deploy works fine

### Service configuration (serverless.yml) content

```yaml
service: aws-nodejs-docker-demo

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./


functions:
  hello:
    image:
      name: appimage
```

### Command name and used flags

npx serverless deploy

### Command output

```shell
Deploying aws-nodejs-docker-demo to stage dev (eu-west-2)

✖ Stack aws-nodejs-docker-demo-dev failed to deploy (0s)
Environment: darwin, node 16.15.1, framework 3.25.0, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization=AWS ********
```

### Environment information

```shell
Framework Core: 3.25.0
Plugin: 6.2.2
SDK: 4.3.2
```
