### ISSUE TITLE
Unrecognized resource types: [AWS::Scheduler::ScheduleGroup]

### ISSUE THREAD

**Issue by mrkk47** [serverless/serverless#11571]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Deployment fails with the following error:

The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::Scheduler::ScheduleGroup]

There is no typo in the resource type used, verified with CloudFormation documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedulegroup.html

### Service configuration (serverless.yml) content

```yaml
service: infra
frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-west-1

custom:
  app: "app"
  version: "0.1"

resources:
  Resources:
    ScheduleGroup:
      Type: AWS::Scheduler::ScheduleGroup
      Properties:
        Name: ${self:custom.app}-${self:custom.version}-${self:provider.stage}
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
Deploying infra to stage dev (us-west-1)

Packaging
Retrieving CloudFormation stack
Creating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Executing created change set
  CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - infra-dev
  CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
  CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
  CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
  CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
  CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
  CREATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
  CREATE_COMPLETE - AWS::CloudFormation::Stack - infra-dev
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3

× Stack infra-dev failed to deploy (46s)
Environment: win32, node 16.15.1, framework 3.25.1, plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The CloudFormation template is invalid: Template format error: Unrecognized resource types: [AWS::Scheduler::ScheduleGroup]
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```
