### ISSUE TITLE
This is my Env information

### ISSUE THREAD

**Issue by iamdevvalecha** [serverless/serverless#11579]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

This is my Env information
     os                                ubuntu 20.04
     Node Version:              12.18.1
     Framework Version:         2.12.0 (standalone)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.0

When I tried to deploy a new function using sls deploy I got the following Error

  Stack 'Canarias-development' does not exist

  An error occurred: ServerlessDeploymentBucket - You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: 268E39F02B4E145D; S3 Extended Request ID: REQUESTID=; Proxy: null).

### Service configuration (serverless.yml) content

```yaml
service: Canarias
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}
  region: us-west-2
  profile: default
  memorySize: 512
  environment:
    NODE_PATH: "./:/opt"

 functions:
   app:
     handler: index.defineAuthChallange
     events:
       - http:
           path: /
           method: ANY
       - http:
           path: /{proxy+}
           method: ANY
```

### Command name and used flags

serverless deploy function --function stack

### Command output

```shell
Stack 'Canarias-development' does not exist
```

### Environment information

```shell
already given
```
