### ISSUE TITLE
Allow multiple HTTP API IDs

### ISSUE THREAD

**Issue by jaikdean** [serverless/serverless#11573]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I have two API Gateways configured outside of Serverless. I want to integrate one Lambda function with each.

Currently, the API Gateway ID can only be specified at the provider level, so only one may be used.

### Proposed solution (optional)

Allow the HTTP API ID to be specified on a per-function basis, overriding any provider-level configuration. For example:

```
function:
  foo:
    handler: foo
    httpApi:
      id: myFirstApiId
    events:
      - httpApi: "*"
  bar:
    handler: bar
    httpApi:
      id: mySecondApiId
    events:
      - httpApi: "*"
```
