### ISSUE TITLE
using custom naming of serverless file change self usage

### ISSUE THREAD

**Issue by LagerstedtMarcus** [serverless/serverless#11584]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When i have a serverless.legacy.yml file ${self:custom} is not working anymore when i add a file to my serverless.legacy.yml like: 

functions:
  - ${file(./functions.yml):functions}
  
  inside functions i need to use ${self.legacy:custom} which doesnt make sense

### Service configuration (serverless.yml) content

```yaml
File: serverless.legacy.yml
  service: "backend"
  provider:
    name: aws
  
  functions:
    - ${file(./functions.yml):functions}
File: functions.yml
functions:
  myFunction:
    handler: Service.Lambda::My.Service.Functions.myFucntion::Handle
    iamRoleStatementsName: ${self:service}-function-role
```

### Command name and used flags

serverless deploy --config serverless.legacy.yml 

### Command output

```shell
- Cannot resolve variable at "functions.0.myFunction.iamRoleStatementsName": Value not found at "self" source,
```

### Environment information

```shell
Framework Core: 3.23.0 (local)
Plugin: 6.2.2
SDK: 4.3.2

✨  Done in 1.00s.
```
