### ISSUE TITLE
Authorisation error when doing an sls deploy even if AWS profile is admin

### ISSUE THREAD

**Issue by andredicioccio** [serverless/serverless#11597]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When attempting to deploy using sls deploy I am getting an error saying that I am not authorised to perform lambda:GetFunction.

I have had the AWS technical team confirm and the profile that is being used (see serverless.yml file) is definitely marked as with admin rights.

```
➜  user_staff_2 git:(develop) ✗ sls deploy 

Deploying gat-web-admin-api-user-staff-2 to stage dev (ap-southeast-1)
Packing external modules: serverless-mysql@^1.5.4
Warning: Not authorized to perform: lambda:GetFunction for at least one of the lambda functions. Deployment will not be skipped even if service files did not change.

✖ Stack gat-web-admin-api-user-staff-2-dev failed to deploy (79s)
Environment: darwin, node 14.19.0, framework 3.25.1, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "gatserverless" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: CreateUnderscoreuserUnderscorestaffLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "null (Service: Lambda, Status Code: 403, Request ID: e7e72d10-5c7c-472f-bc85-f7c508544b68)" (RequestToken: 11195489-b498-65f4-babf-0c1d1b733e9d, HandlerErrorCode: GeneralServiceException)

View the full error: https://ap-southeast-1.console.aws.amazon.com/cloudformation/home?region=ap-southeast-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-1%3A682486641958%3Astack%2Fgat-web-admin-api-user-staff-2-dev%2F450114b0-7a04-11ed-af97-0227e2c04ce4

2 deprecations found: run 'serverless doctor' for more details

```

### Service configuration (serverless.yml) content

```yaml
service: gat-web-admin-api-user-staff-2

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: gatserverless
  region: ap-southeast-1
  endpointType: REGIONAL
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DOMAIN: ${self:custom.secrets.DOMAIN}
    SERVICE_NAME: ${self:service} 

  iamRoleStatements:
  - Effect: Allow
    Action:
      - rds:*
    Resource: "*"

functions:
  get_by_aws_cognito:
    handler: src/get.by_aws_cognito
    events:
      - http:
          path: user-staff-2/get/aws-cognito/{aws_cognito_id}
          method: get
          cors: true
          # authorizer: aws_iam
  create_user_staff:
    handler: src/create.user_staff
    events:
      - http:
          path: user-staff-2/create
          method: post
          cors: true
          authorizer: aws_iam
```

### Command name and used flags

sls deploy

### Command output

```shell
➜  user_staff_2 git:(develop) ✗ sls deploy 

Deploying gat-web-admin-api-user-staff-2 to stage dev (ap-southeast-1)
Packing external modules: serverless-mysql@^1.5.4
Warning: Not authorized to perform: lambda:GetFunction for at least one of the lambda functions. Deployment will not be skipped even if service files did not change.

✖ Stack gat-web-admin-api-user-staff-2-dev failed to deploy (79s)
Environment: darwin, node 14.19.0, framework 3.25.1, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "gatserverless" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: CreateUnderscoreuserUnderscorestaffLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "null (Service: Lambda, Status Code: 403, Request ID: e7e72d10-5c7c-472f-bc85-f7c508544b68)" (RequestToken: 11195489-b498-65f4-babf-0c1d1b733e9d, HandlerErrorCode: GeneralServiceException)

View the full error: https://ap-southeast-1.console.aws.amazon.com/cloudformation/home?region=ap-southeast-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-1%3A682486641958%3Astack%2Fgat-web-admin-api-user-staff-2-dev%2F450114b0-7a04-11ed-af97-0227e2c04ce4

2 deprecations found: run 'serverless doctor' for more details
➜  user_staff_2 git:(develop) ✗
```

### Environment information

```shell
➜ serverless --version
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```
