### ISSUE TITLE
Packages ~60meg of .../node_modules/.cache/ by default

### ISSUE THREAD

**Issue by tomchiverton** [serverless/serverless#11595]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Adding 
```
package:  
  patterns:  
    - '!node_modules/.cache/**'
```
dramatically shrinks deployment size, and makes it much faster, with no ill effects.

Our project has non-dev dependencies on promise-mysql,yesql and serverless-aws-static-file-handler but has a larger number of dev. deps, which are correctly excluded from the deployment .zip's node_modules, but things like 20meg of `node_modules/.cache/terser-webpack-plugin/` do get included.

Adding `'!node_modules/@types/**'` also helps, though not as much, and should be considered too.

Together, this shrinks our deploy from ~20meg to ~5meg

### Service configuration (serverless.yml) content

```yaml
N/A, but package.json includes 

 "dependencies": {
    "axios": "^0.27.2",
    "jsonwebtoken": "^8.5.1",
    "luxon": "^3.0.1",
    "named": "^1.0.2",
    "node-gzip": "^1.1.2",
    "promise-mysql": "^5.2.0",
    "serverless-aws-static-file-handler": "^3.1.8",
    "uuid": "^8.3.2",
    "yesql": "^5.0.0"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.12.1",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "chai": "^4.3.4",
    "core-js": "^3.6.5",
    "cross-env": "^7.0.3",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "liquor-tree": "^0.2.70",
    "mocha": "^9.0.2",
    "sass": "^1.54.6",
    "sass-loader": "^7.1.0",
    "serverless-lift": "^1.21.0",
    "serverless-plugin-aws-alerts": "^1.7.5",
    "serverless-prune-plugin": "^2.0.1",
    "vee-validate": "^2.2.15",
    "vue": "^2.6.14",
    "vue-body-class": "^3.0.2",
    "vue-fragment": "^1.5.2",
    "vue-gtag": "^1.16.1",
    "vue-invisible-recaptcha": "tomchiverton/vue-invisible-recaptcha#39680de2fced35266b45587975989031c260aeef",
    "vue-router": "^3.0.0",
    "vue-simple-alert": "^1.1.1",
    "vue-template-compiler": "^2.6.14",
    "vuejs-paginate": "^2.1.0",
    "vuex": "^3.1.2"
  },
```

### Command name and used flags

sls package ; ls -laht .serverless/*zip

### Command output

```shell
$ sls package --aws-profile serverless-dev-extravision
Running "serverless" from node_modules

Packaging bt-compare for stage dev (eu-west-1)
Warning: Not deploying alerts on stage dev

✔ Service packaged (27s)
$
```

### Environment information

```shell
$ serverless --version
Running "serverless" from node_modules
Framework Core: 3.21.0 (local) 3.25.1 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
