### ISSUE TITLE
Deploying a function with provisionedConcurrency sets maximumRetryAttempts to 2

### ISSUE THREAD

**Issue by brianliu3** [serverless/serverless#11609]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have an existing lambda function with maximumRetryAttempts set to 0 and no provisionedConcurrency. I want to now set provisionedConcurrency to 1, but when I redeploy my function, maximumRetryAttempts gets set to 2

### Service configuration (serverless.yml) content

```yaml
service: test

provider:
  name: aws
  runtime: python3.8

functions:
  test_function:
    logRetentionInDays: 365
    provisionedConcurrency: 1
    handler: daas.compliance.helpers.algorithm_imports_helper.import_algorithm
    description: Import an algorithm
    timeout: 900
    maximumRetryAttempts: 0
```

### Command name and used flags

sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```
