### ISSUE TITLE
Serverless does not recognise subdirectories in Node

### ISSUE THREAD

**Issue by JuliusGoddard** [serverless/serverless#11619]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When trying to run a simple query locally: serverless invoke local -f graphql -p query.json on Node JS, using Serverless and GraphQL, the console throws this warning:

![image](https://user-images.githubusercontent.com/56204733/208238281-6dcda735-01a1-4c40-a0c4-599dfa62aab3.png)

For some reason, serverless can't seem to understand imports from functions stored in subdirectories: I have a code structure that looks like this:

![image](https://user-images.githubusercontent.com/56204733/208238350-f37e61ee-c979-45ac-a0c4-076163918073.png)

apolloServer.js requires functions and variables from the subdirectories in utils, graphql etc.

It would be too cumbersome to have the entire code in apolloServer.js and so variables and functions need to be stored in subfolders.

Why does Serverless not recognise imports from subdirectories?

### Service configuration (serverless.yml) content

```yaml
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/apolloServer.graphqlHandler 
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
```

### Command name and used flags

serverless invoke local -f graphql -p query.json

### Command output

```shell
× Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\d_gee\Documents\Web Development\rate-repository-api\src\graphql\schema' imported from C:\Users\d_gee\Documents\Web Development\rate-repository-api\src\apolloServer.js
      at new NodeError (node:internal/errors:393:5)
      at finalizeResolution (node:internal/modules/esm/resolve:305:11)
      at moduleResolve (node:internal/modules/esm/resolve:866:10)
      at defaultResolve (node:internal/modules/esm/resolve:1074:11)
      at nextResolve (node:internal/modules/esm/loader:164:28)
      at ESMLoader.resolve (node:internal/modules/esm/loader:839:30)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:426:18)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
      at link (node:internal/modules/esm/module_job:75:36) {
    code: 'ERR_MODULE_NOT_FOUND'
  }
Environment: win32, node 18.8.0, framework 3.25.1, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```
