### ISSUE TITLE
Validator reports invalid configuration for !If function

### ISSUE THREAD

**Issue by karmaniverous** [serverless/serverless#11611]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm using `!If` in a valid configuration that works perfectly when deployed but generates a config warning on deployment. Full description [here](https://github.com/karmaniverous/aws-api-template/tree/dev#serverlessyml-validation)

### Service configuration (serverless.yml) content

```yaml
service: ${env:SERVICE_NAME}
frameworkVersion: '3'

plugins:
  - serverless-domain-manager
  - serverless-offline

params:
  default:
    apiBasePath: ${env:API_VERSION}-${env:ENV}
    authSubdomain: ${env:AUTH_SUBDOMAIN_TOKEN}-${env:API_VERSION}-${env:ENV}
  prod:
    apiBasePath: ${env:API_VERSION}
    authSubdomain: ${env:AUTH_SUBDOMAIN_TOKEN}-${env:API_VERSION}

provider:
  apiGateway:
    disableDefaultEndpoint: true
  apiName: ${self:provider.stackName}
  endpointType: EDGE
  iam:
    role:
      # name:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
          Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stackName: ${env:SERVICE_NAME}-${env:API_VERSION}-${env:ENV}
  stage: ${env:API_VERSION}-${env:ENV}
  timeout: 5

custom:
  customDomain:
    domainName: ${env:API_SUBDOMAIN}.${env:ROOT_DOMAIN}
    basePath: ${param:apiBasePath}
    certificateArn: ${env:CERTIFICATE_ARN}

functions:
  hello:
    handler: api/open/hello.get
    description: GET /hello
    events:
      - http:
          path: hello
          method: get
          cors: true
    # name: ${self:provider.stage}

  secure-hello:
    handler: api/secure/hello.get
    description: GET /secure-hello
    events:
      - http:
          path: secure-hello
          method: get
          cors: true
          authorizer:
            name: UserPoolAuthorizer
            type: COGNITO_USER_POOLS
            arn: !If
              - CreateUserPool
              - !GetAtt UserPool.Arn
              - ${env:COGNITO_USER_POOL_ARN}
            claims:
              - email

resources:
  Conditions:
    CreateUserPool: !Equals ['${env:COGNITO_USER_POOL_ARN}', '*']
    CreateIdentityProviderGoogle: !And
      - !Condition CreateUserPool
      - !Not
        - !Or
          - !Equals ['${env:GOOGLE_CLIENT_ID}', '*']
          - !Equals ['${env:GOOGLE_CLIENT_SECRET}', '*']

  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    UserPool:
      Type: AWS::Cognito::UserPool
      Condition: CreateUserPool
      Properties:
        AutoVerifiedAttributes: ['email']
        Schema:
          - Name: email
            Mutable: true
            Required: true
        UsernameConfiguration:
          CaseSensitive: false
        UserPoolName: ${self:provider.stackName}

    UserPoolIdentityProviderGoogle:
      Type: AWS::Cognito::UserPoolIdentityProvider
      Condition: CreateIdentityProviderGoogle
      Properties:
        UserPoolId: !Ref UserPool
        ProviderName: Google
        ProviderDetails:
          client_id: '${env:GOOGLE_CLIENT_ID}'
          client_secret: '${env:GOOGLE_CLIENT_SECRET}'
          authorize_scopes: 'profile email openid'
        ProviderType: Google
        AttributeMapping:
          email: email

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Condition: CreateUserPool
      Properties:
        AllowedOAuthFlows:
          - code
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - openid
          - profile
        CallbackURLs:
          - 'https://${env:ROOT_DOMAIN}/api/auth/callback/cognito'
          - 'https://${env:WEB_SUBDOMAIN_PROD}.${env:ROOT_DOMAIN}/api/auth/callback/cognito'
          - 'https://${env:WEB_SUBDOMAIN_PREVIEW}.${env:ROOT_DOMAIN}/api/auth/callback/cognito'
          - 'http://localhost:${env:WEB_LOCALHOST_PORT}/api/auth/callback/cognito'
        ClientName: web-app
        GenerateSecret: true
        LogoutURLs:
          - 'https://${env:ROOT_DOMAIN}'
          - 'https://${env:WEB_SUBDOMAIN_PROD}.${env:ROOT_DOMAIN}'
          - 'https://${env:WEB_SUBDOMAIN_PREVIEW}.${env:ROOT_DOMAIN}'
          - 'http://localhost:${env:WEB_LOCALHOST_PORT}'
        SupportedIdentityProviders:
          - COGNITO
          - !If
            - CreateIdentityProviderGoogle
            - Google
            - Ref: AWS::NoValue
        UserPoolId: !Ref UserPool

    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Condition: CreateUserPool
      Properties:
        CustomDomainConfig:
          CertificateArn: ${env:CERTIFICATE_ARN}
        Domain: ${param:authSubdomain}.${env:ROOT_DOMAIN}
        UserPoolId: !Ref UserPool

    UserPoolAlias:
      Type: AWS::Route53::RecordSetGroup
      Condition: CreateUserPool
      Properties:
        HostedZoneName: '${env:ROOT_DOMAIN}.'
        RecordSets:
          - Name: ${param:authSubdomain}.${env:ROOT_DOMAIN}.
            ResourceRecords:
              - !GetAtt UserPoolDomain.CloudFrontDistribution
            TTL: '300'
            Type: CNAME
```

### Command name and used flags

serverless deploy --verbose

### Command output

```shell
Warning: Invalid configuration encountered
  at 'functions.secure-hello.events.0.http.authorizer.arn': unsupported object format

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Framework Core: 3.25.1 (local) 3.25.1 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@karmaniverous I think it's question of adding `If` function support here: https://github.com/serverless/serverless/blob/dd5b8f61de487d67f0cc15036be754816f7fa234/lib/plugins/aws/provider.js#L334-L342

I just wonder whether it's indeed ok to support `If` function whenever we support AWS CF intrinsic functions

**Comment by karmaniverous** [comment]
If I understand [the reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html) correctly, `If` can go anyplace a property value goes.

**Comment by medikoo** [comment]
> If I understand the reference correctly, If can go anyplace a property value goes.

Ok, let's just add it to `awsCfFunction` set

**Comment by denisakira** [comment]
Is this still relevant for the current version? I’d like to contribute

**Comment by karmaniverous** [comment]
picking this one up

**Comment by karmaniverous** [comment]
Definitely still relevant. In fact, there may be an opportunity here to kill several birds with one stone.

I have several valid constructs in `serverless.yml` that build properly at AWS but are throwing lint warnings in VS Code. For reference, here's the latest version of my `serverless.yml`:

```yml
service: ${env:SERVICE_NAME}
frameworkVersion: '3'

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-apigateway-service-proxy
custom:
  apiBasePath: ${self:custom.env2apiBasePath.${env:ENV}}
  apiGatewayServiceProxies:
    - sqs:
        path: visa/epm
        method: post
        queueName: !GetAtt TransactionAlertQueue.QueueName
        requestParameters:
          'integration.request.querystring.MessageAttribute.1.Name': "'network'"
          'integration.request.querystring.MessageAttribute.1.Value.StringValue': "'visa'"
          'integration.request.querystring.MessageAttribute.1.Value.DataType': "'String'"
  authSubdomain: ${self:custom.env2authSubdomain.${env:ENV}}
  customDomain:
    domainName: ${env:API_SUBDOMAIN}.${env:ROOT_DOMAIN}
    basePath: ${self:custom.apiBasePath}
    certificateArn: ${env:CERTIFICATE_ARN}
  env2apiBasePath:
    dev: ${env:API_VERSION}-${env:ENV}
    test: ${env:API_VERSION}-${env:ENV}
    prod: ${env:API_VERSION}
  env2authSubdomain:
    dev: ${env:AUTH_SUBDOMAIN_TOKEN}-${env:API_VERSION}-${env:ENV}
    test: ${env:AUTH_SUBDOMAIN_TOKEN}-${env:API_VERSION}-${env:ENV}
    prod: ${env:AUTH_SUBDOMAIN_TOKEN}-${env:API_VERSION}
  env2webSubdomain:
    dev: ${env:WEB_SUBDOMAIN_TOKEN}-${env:ENV}
    test: ${env:WEB_SUBDOMAIN_TOKEN}-${env:ENV}
    prod: ${env:WEB_SUBDOMAIN_TOKEN}
  webSubdomain: ${self:custom.env2webSubdomain.${env:ENV}}

provider:
  apiGateway:
    disableDefaultEndpoint: true
  apiName: ${self:provider.stackName}
  endpointType: EDGE
  environment:
    LOG_LEVEL: ${env:LOG_LEVEL}
    MAIN_TABLE_NAME: !Ref MainTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - dynamodb:PutItem
            - sqs:SendMessage
          Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stackName: ${env:SERVICE_NAME}-${env:API_VERSION}-${env:ENV}
  stage: ${env:API_VERSION}-${env:ENV}
  timeout: 5

functions:
  hello:
    description: GET hello
    events:
      - http:
          path: hello
          method: get
          cors: true
    handler: api/open/hello.get

  secure-hello:
    description: GET secure-hello
    events:
      - http:
          path: secure-hello
          method: get
          cors: true
          authorizer:
            name: UserPoolAuthorizer
            type: COGNITO_USER_POOLS
            arn: !If
              - CreateUserPool
              - !GetAtt UserPool.Arn
              - ${env:COGNITO_USER_POOL_ARN}
            claims:
              - email
    handler: api/secure/hello.get

  transaction-alert:
    description: transaction alert handler
    events:
      - sqs:
          arn: !GetAtt TransactionAlertQueue.Arn
          batchSize: 1
    handler: aws/transaction-alert.handler

  transaction-insert:
    description: transaction insert handler
    events:
      - stream:
          arn: !GetAtt MainTable.StreamArn
          batchSize: 1
          enabled: true
          filterPatterns:
            - eventName: [INSERT]
              dynamodb:
                Keys:
                  entityPK:
                    S:
                      - prefix: transaction!
          # maximumRetryAttempts: 10
          startingPosition: LATEST
          type: dynamodb
    handler: aws/transaction-insert.handler
    onError: !GetAtt TransactionInsertDLQ.Arn

resources:
  Conditions:
    CreateUserPool: !Equals ['${env:COGNITO_USER_POOL_ARN}', '*']
    CreateIdentityProviderGoogle: !And
      - !Condition CreateUserPool
      - !Not
        - !Or
          - !Equals ['${env:GOOGLE_CLIENT_ID}', '*']
          - !Equals ['${env:GOOGLE_CLIENT_SECRET}', '*']

  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    UserPool:
      Type: AWS::Cognito::UserPool
      Condition: CreateUserPool
      Properties:
        AutoVerifiedAttributes: ['email']
        Schema:
          - Name: email
            Mutable: true
            Required: true
        UsernameConfiguration:
          CaseSensitive: false
        UserPoolName: ${self:provider.stackName}

    UserPoolIdentityProviderGoogle:
      Type: AWS::Cognito::UserPoolIdentityProvider
      Condition: CreateIdentityProviderGoogle
      Properties:
        UserPoolId: !Ref UserPool
        ProviderName: Google
        ProviderDetails:
          client_id: '${env:GOOGLE_CLIENT_ID}'
          client_secret: '${env:GOOGLE_CLIENT_SECRET}'
          authorize_scopes: 'profile email openid'
        ProviderType: Google
        AttributeMapping:
          email: email

    UserClient:
      Type: AWS::Cognito::UserPoolClient
      Condition: CreateUserPool
      Properties:
        AllowedOAuthFlows:
          - code
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - openid
          - profile
        CallbackURLs:
          - 'https://${env:ROOT_DOMAIN}/api/auth/callback/cognito'
          - 'https://${self:custom.webSubdomain}.${env:ROOT_DOMAIN}/api/auth/callback/cognito'
          - 'http://localhost:${env:WEB_LOCALHOST_PORT}/api/auth/callback/cognito'
        ClientName: web-app
        GenerateSecret: true
        LogoutURLs:
          - 'https://${env:ROOT_DOMAIN}'
          - 'https://${self:custom.webSubdomain}.${env:ROOT_DOMAIN}'
          - 'http://localhost:${env:WEB_LOCALHOST_PORT}'
        SupportedIdentityProviders:
          - COGNITO
          - !If
            - CreateIdentityProviderGoogle
            - Google
            - Ref: AWS::NoValue
        UserPoolId: !Ref UserPool

    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Condition: CreateUserPool
      Properties:
        CustomDomainConfig:
          CertificateArn: ${env:CERTIFICATE_ARN}
        Domain: ${self:custom.authSubdomain}.${env:ROOT_DOMAIN}
        UserPoolId: !Ref UserPool

    UserPoolAlias:
      Type: AWS::Route53::RecordSetGroup
      Condition: CreateUserPool
      Properties:
        HostedZoneName: '${env:ROOT_DOMAIN}.'
        RecordSets:
          - Name: ${self:custom.authSubdomain}.${env:ROOT_DOMAIN}.
            ResourceRecords:
              - !GetAtt UserPoolDomain.CloudFrontDistribution
            TTL: '300'
            Type: CNAME

    TransactionAlertQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stackName}-TransactionAlertQueueDLQ

    TransactionAlertQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stackName}-TransactionAlertQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt TransactionAlertQueueDLQ.Arn
          maxReceiveCount: 3
        VisibilityTimeout: 180

    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: entityPK
            AttributeType: S
          - AttributeName: entitySK
            AttributeType: S
          - AttributeName: transactionPK
            AttributeType: S
          - AttributeName: transactionSK
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: entityPK
            KeyType: HASH
          - AttributeName: entitySK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: transaction
            KeySchema:
              - AttributeName: transactionPK
                KeyType: HASH
              - AttributeName: transactionSK
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - raw
                - shardId
                - timestamp
                - transactionId
              ProjectionType: INCLUDE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        TableName: ${self:provider.stackName}-MainTable

    TransactionInsertDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stackName}-TransactionInsertQueueDLQ
```

And here are the warnings this produces:

```json
[{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"string\".",
	"source": "yaml-schema: AwsHttpCognitoAuthorizer",
	"startLineNumber": 86,
	"startColumn": 15,
	"endLineNumber": 89,
	"endColumn": 1
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"CFIntrinsicFunctionRef\".",
	"source": "yaml-schema: CFIntrinsicFunctionRef",
	"startLineNumber": 97,
	"startColumn": 24,
	"endLineNumber": 97,
	"endColumn": 49
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"CFIntrinsicFunctionBase64 | CFIntrinsicFunctionCIDR | CFIntrinsicFunctionFindInMap | CFIntrinsicFunctionGetAttribute | CFIntrinsicFunctionGetAvailabilityZones | CFIntrinsicFunctionImportValue | CFIntrinsicFunctionJoin | CFIntrinsicFunctionRef | CFIntrinsicFunctionSelect | CFIntrinsicFunctionSplit | CFIntrinsicFunctionSub | CFIntrinsicFunctionCovertToJsonString\".",
	"source": "yaml-schema: CFIntrinsicFunctionBase64 | CFIntrinsicFunctionCIDR | CFIntrinsicFunctionFindInMap | CFIntrinsicFunctionGetAttribute | CFIntrinsicFunctionGetAvailabilityZones | CFIntrinsicFunctionImportValue | CFIntrinsicFunctionJoin | CFIntrinsicFunctionRef | CFIntrinsicFunctionSelect | CFIntrinsicFunctionSplit | CFIntrinsicFunctionSub | CFIntrinsicFunctionCovertToJsonString",
	"startLineNumber": 105,
	"startColumn": 24,
	"endLineNumber": 105,
	"endColumn": 43
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"string | FnAnd | FnEquals | FnNot | FnOr | CFIntrinsicFunctionFindInMap\".",
	"source": "yaml-schema: Serverless Framework Configuration | CFIntrinsicFunctionFindInMap",
	"startLineNumber": 123,
	"startColumn": 29,
	"endLineNumber": 123,
	"endColumn": 66
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"string | FnAnd | FnEquals | FnNot | FnOr | CFIntrinsicFunctionFindInMap\".",
	"source": "yaml-schema: Serverless Framework Configuration | CFIntrinsicFunctionFindInMap",
	"startLineNumber": 125,
	"startColumn": 7,
	"endLineNumber": 130,
	"endColumn": 1
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Unresolved tag: !Condition",
	"source": "YAML",
	"startLineNumber": 125,
	"startColumn": 9,
	"endLineNumber": 125,
	"endColumn": 36
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property Condition is not allowed.",
	"source": "yaml-schema: AWSCognitoUserPool",
	"startLineNumber": 144,
	"startColumn": 7,
	"endLineNumber": 144,
	"endColumn": 16
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property Condition is not allowed.",
	"source": "yaml-schema: AWSCognitoUserPoolIdentityProvider",
	"startLineNumber": 157,
	"startColumn": 7,
	"endLineNumber": 157,
	"endColumn": 16
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property Condition is not allowed.",
	"source": "yaml-schema: AWSCognitoUserPoolClient",
	"startLineNumber": 171,
	"startColumn": 7,
	"endLineNumber": 171,
	"endColumn": 16
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"string\".",
	"source": "yaml-schema: AWSCognitoUserPoolClientProperties",
	"startLineNumber": 193,
	"startColumn": 13,
	"endLineNumber": 196,
	"endColumn": 1
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property Condition is not allowed.",
	"source": "yaml-schema: AWSCognitoUserPoolDomain",
	"startLineNumber": 200,
	"startColumn": 7,
	"endLineNumber": 200,
	"endColumn": 16
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property Condition is not allowed.",
	"source": "yaml-schema: AWSRoute53RecordSetGroup",
	"startLineNumber": 209,
	"startColumn": 7,
	"endLineNumber": 209,
	"endColumn": 16
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "String is longer than the maximum length of 1.",
	"source": "yaml-schema: AWSDynamoDBTableAttributeDefinition",
	"startLineNumber": 237,
	"startColumn": 28,
	"endLineNumber": 237,
	"endColumn": 36
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "String is longer than the maximum length of 1.",
	"source": "yaml-schema: AWSDynamoDBTableAttributeDefinition",
	"startLineNumber": 239,
	"startColumn": 28,
	"endLineNumber": 239,
	"endColumn": 36
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "String is longer than the maximum length of 1.",
	"source": "yaml-schema: AWSDynamoDBTableAttributeDefinition",
	"startLineNumber": 241,
	"startColumn": 28,
	"endLineNumber": 241,
	"endColumn": 41
},{
	"resource": "/C:/Code/VeteranCrowd/aws-api/serverless.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "String is longer than the maximum length of 1.",
	"source": "yaml-schema: AWSDynamoDBTableAttributeDefinition",
	"startLineNumber": 243,
	"startColumn": 28,
	"endLineNumber": 243,
	"endColumn": 41
}]
```

If you decide to pick this ticket up I'm happy to help troubleshoot!
