### ISSUE TITLE
Could not find Docker installation. Ensure Docker is installed before continuing.

### ISSUE THREAD

**Issue by Jorgu5** [serverless/serverless#11626]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm getting this error when deploying the docker container image. 

https://i.imgur.com/tCeQSaJ.jpg 

It works without any issues when I'm using `sls deploy` locally; things are happening only during the deployment through GitHub actions. Attaching github actions file and .yml below:

```
name: Deploy staging branch

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
      - uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--prefer-dist --optimize-autoloader --no-dev"
      - run: |
          composer require bref/bref
          php artisan config:cache
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

### Service configuration (serverless.yml) content

```yaml
service: laravel

provider:
    name: aws
    region: eu-central-1
    ecr:
      images:
        web:
          path: ./
    # The stage of the application, e.g. dev, production, staging… ('dev' is the default)
    stage: dev
    runtime: provided.al2
    tracing:
      lambda: true
    lambdaHashingVersion: 20201221
    environment:
      # You can reference AWS resources from the serverless.yml file
      AWS_BUCKET: !Ref Storage
      BREF_BINARY_RESPONSES: '1'
    iam:
      role:
        statements:
          # Allow the function to access the bucket
        - Effect: Allow
          Action: s3:*
          Resource:
              - !Sub '${Storage.Arn}' # the storage bucket
              - !Sub '${Storage.Arn}/*' # and everything inside
    apiGateway:
      binaryMediaTypes:
        - '*/*'
package:
    # Directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:
    # This function runs the Laravel website/API
    web:
        image:
            name: web
        events:
            - httpApi: '*'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-80} # PHP
            - ${bref:layer.console} # The "console" layer
plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions # <----- Add the extra Serverless plugin
resources:
    Resources:
      Storage:
        Type: AWS::S3::Bucket
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```
