### ISSUE TITLE
Add event filtering capabilities to Amazon MSK, Self-Managed Kafka, Amazon MQ for Apache ActiveMQ & Amazon MQ for RabbitMQ

### ISSUE THREAD

**Issue by shreyance-jain** [serverless/serverless#11635]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Since Oct 13th 2022, event source mapping for invoking lambda from  Amazon MSK, Self-Managed Kafka, Amazon MQ for Apache ActiveMQ & Amazon MQ for RabbitMQ support event filtering (see release [announcement here](https://aws.amazon.com/about-aws/whats-new/2022/10/aws-lambda-event-filtering-amazon-msk-kafka-mq-apache-activemq-amazon-mq-rabbit-mq/)). 
I suggest we had the capability to define such filters in Serverless framework, on corresponding events.

### Proposed solution (optional)

We can split in multiple pull requests service wise (feat:service_name)

- [x] Adding filter capabilities to `msk` type of event - this will impact AWS MSK event source mapping generation and requires modifications to be made to `lib/plugins/aws/package/compile/events/msk/index.js`
- [x] Adding filter capabilities to `kafka` type of event - this will impact self-managed Apache Kafka cluster event source mapping generation and requires modifications to be made to `lib/plugins/aws/package/compile/events/kafka.js`
- [x] Adding filter capabilities to `activemq` type of event - this will impact ActiveMQ event source mapping generation and requires modifications to be made to `lib/plugins/aws/package/compile/events/activemq.js`
- [x] Adding filter capabilities to `rabbitmq` type of event - this will impact RabbitMQ event source mapping generation and requires modifications to be made to `lib/plugins/aws/package/compile/events/rabbitmq.js`

The full documentation regarding implementation of those filters using Cloudformation can be found [here](https://docs.aws.amazon.com/lambda/latest/dg/invocation-eventfiltering.html)

All 4 sources require the addition of a FilterCriteria property on the [AWS::Lambda::EventSourceMapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html) resource type.
This additional property is always a JSON with a Filters property containing up to 5 filters(soft limit, max. 10 on quota request), each represented as an object containing a Pattern property.

In order to keep implementation consistent with other event filters such as in DynamoDB, SQS etc., I suggest the following implementation for:

Amazon MSK
```
functions:
  compute:
    handler: handler.compute
    events:
      - msk:
          arn: arn:aws:kafka:region:XXXXXX:cluster/MyCluster/xxxx-xxxxx-xxxx
          topic: mytopic
          filterPatterns:
            - value:
                a: [1]
```

Self-Managed Kafka	
```
functions:
  compute:
    handler: handler.compute
    events:
      - kafka:
          accessConfigurations:
            saslScram512Auth: arn:aws:secretsmanager:us-east-1:01234567890:secret:MyBrokerSecretName
          topic: MySelfManagedKafkaTopic
          consumerGroupId: MyConsumerGroupId
          bootstrapServers:
            - abc3.xyz.com:9092
            - abc2.xyz.com:9092
          filterPatterns:
            - value:
                a: [1]
```

Amazon MQ for Apache ActiveMQ
```
functions:
  compute:
    handler: handler.compute
    events:
      - activemq:
          arn: arn:aws:mq:us-east-1:0000:broker:ExampleMQBroker:b-xxx-xxx
          queue: queue-name
          basicAuthArn: arn:aws:secretsmanager:us-east-1:01234567890:secret:MySecret
          filterPatterns:
            - value:
                a: [1]
```

Amazon MQ for RabbitMQ
```
functions:
  compute:
    handler: handler.compute
    events:
      - rabbitmq:
          arn: arn:aws:mq:us-east-1:0000:broker:ExampleMQBroker:b-xxx-xxx
          queue: queue-name
          basicAuthArn: arn:aws:secretsmanager:us-east-1:01234567890:secret:MySecret
          filterPatterns:
            - value:
                a: [1]
```
