### ISSUE TITLE
DataCloneError

### ISSUE THREAD

**Issue by BhangalePratik** [serverless/serverless#11634]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I started the API gateway locally through the command "serverless offline". It exposed all the endpoints when I hit them. I got the following error : 
Error:
DataCloneError: async (event_, context = {}) => {
    const event = cleanUpEvent(event_, options);

    const request = createR...<omitted>... } could not be cloned.
    at MessagePort.<anonymous> (file:///C:/Users/prati/Desktop/City%20University%20of%20London/Cloud%20Computing/second_trial/recipe/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:30:8)

How do you think I should handle this error?

### Service configuration (serverless.yml) content

```yaml
service: recipe
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - "lambda:InvokeFunction"
            - "lambda:InvokeAsync"
          Resource: "*"

functions:
  main:
    handler: main.handler
    name: main
    events:
      - http:
          path: /healthCheck
          method: get
      - http:
          path: /setWebhook
          method: get
      - http:
          path: /botMessage
          method: post
  getAPIResultStoreInDatabase:
    handler: fetch-api-response.handler
    name: getAPIResultStoreInDatabase
    environment:
      TABLE_NAME: recipeTable

plugins:
  - serverless-offline

resources:
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: recipeName
            AttributeType: S
        KeySchema:
          - AttributeName: recipeName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: recipeTable
```

### Command name and used flags

serverless offline

### Command output

```shell
Error:
DataCloneError: async (event_, context = {}) => {
    const event = cleanUpEvent(event_, options);

    const request = createR...<omitted>... } could not be cloned.
    at MessagePort.<anonymous> (file:///C:/Users/prati/Desktop/City%20University%20of%20London/Cloud%20Computing/second_trial/recipe/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:30:8)
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```
