### ISSUE TITLE
FilterPolicyScope property for sns event on lambda

### ISSUE THREAD

**Issue by cbm-pdossantos** [serverless/serverless#11641]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS introduced last month the payload based message filtering for SNS : https://aws.amazon.com/blogs/compute/introducing-payload-based-message-filtering-for-amazon-sns/

There is a new property named FilterPolicyScope that is needed to filter SNS message based on the message body instead of the message attributes. 

With Cloudformation it looks like this : 
```
  MySubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:myLambda"
      Protocol: lambda
      FilterPolicyScope: MessageBody
      FilterPolicy:
        id:
          - some-id
      TopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:myTopic"
```

Where FilterPolicyScope can have two values : MessageBody or MessageAttributes (default).
It could be nice to have this property directly in the sns event on a lambda along with the FilterPolicy. 🙂 

### Proposed solution (optional)

Simply add the FilterPolicyScope property in the sns events : 

```
MyLambda:
  handler: MyLambdaHandler
  events:
    - sns:
        arn: myTopicArn
        filterPolicyScope: MessageBody (or MessageAttributes)
        filterPolicy:
          id:
            - some_id
```
