### ISSUE TITLE
Per Stage Profiles not works

### ISSUE THREAD

**Issue by jhkcia** [serverless/serverless#11643]
### Are you certain it's a bug?

- [x] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I tried to use per-stage-profile for deploying my application to aws (according to the [documentation](https://www.serverless.com/framework/docs/providers/aws/guide/credentials#per-stage-profiles
)), but it is not using the credentials of that profile. 

I used this command for settting the credentials:
`serverless config credentials --provider aws --key $MY_KEY --secret $MY_SECRET --profile tstProfile`
and used this command for deploying:
`serverless deploy --stage tst  --verbose 
`
and this is a part of my serverless.ts configuration:
```
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    region: 'eu-west-1',
    stage: "${opt:stage}",
    profile: "${self:custom.profiles.${sls:stage}}",
    ...
  },
  custom: {
    profiles: {
      tst: 'tstProfile',
    }
  },
```

with this configuration, it did not use $MY_KEY and $MY_SECRET for aws and showed an error to Check your AWS Secret Access Key and signing method.

I tried to use aws-profile argument in the deploy command and it worked, but it does not work when the profile is set up inside the configuration file like the above configuration.

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from '@serverless/typescript';

import hello from '@functions/hello';

const serverlessConfiguration: AWS = {
  service: 'reusable-container-id-generator',
  frameworkVersion: '3',
  plugins: ['serverless-esbuild', 'serverless-offline'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    region: 'eu-west-1',
    stage: "${opt:stage}",
    stackName: 'reusable-container-id-generator',
    // deploymentInformation
    profile: "${self:custom.profiles.${sls:stage}}",
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
    },
  },
  // import the function via paths
  functions: { hello },
  package: { individually: true },
  custom: {
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ['aws-sdk'],
      target: 'node14',
      define: { 'require.resolve': undefined },
      platform: 'node',
      concurrency: 10,
    },
    profiles: {
      tst: 'tstProfile',
    }
  },
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

serverless deploy --stage tst  --verbose 

### Command output

```shell
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.26.0 (local) 3.26.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
