### ISSUE TITLE
Add support for error action on iot topic rule 

### ISSUE THREAD

**Issue by FMurray** [serverless/serverless#11642]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

[Currently](https://github.com/serverless/serverless/blob/bf79934e9b43a0b2e8613ee29f9430fa22c41481/lib/plugins/aws/package/compile/events/iot.js) the iot event only supports an Action for a topic rule. I want to be able to define an error action (https://docs.aws.amazon.com/iot/latest/developerguide/rule-error-handling.html). 

### Proposed solution (optional)

Provided the YML: 
```
  myFunction:
    handler: ...
    events:
      - iot:
          sql: "SELECT * FROM 'test_unit'"
          errorAction: <ref a function arn here> 
```

The appropriate CF templating will be performed (see reference in description)

**Comment by medikoo** [comment]
@FMurray thanks for reporting. PR's welcome!

**Comment by suhanichawla** [comment]
@medikoo could I give this a shot if no one is working on this?
Is the proposed yaml solution by @FMurray acceptable?
```
  myFunction:
    handler: ...
    events:
      - iot:
          sql: "SELECT * FROM 'test_unit'"
          errorAction: <ref a function arn here>  
```
