### ISSUE TITLE
Deploy crashes randomly - ChangeSet lambdas-dev-change-set cannot be created due to a mismatch with existing attribute Template

### ISSUE THREAD

**Issue by goldylucks** [serverless/serverless#11649]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Every 5 or so deploys, I get this error:

```
Deploying lambdas to stage dev (ap-northeast-1, "default" provider)
Compiling to node16 bundle with esbuild...
Compiling with concurrency: Infinity
Compiling completed.
Zip function: prompt-next-process - 1.11 MB [121 ms]
Zip function: prompt-scheduled-process - 1.11 MB [122 ms]
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service prompt-next-process.zip file to S3 (1.36 MB)
Uploading service prompt-scheduled-process.zip file to S3 (1.36 MB)
Creating new change set
× Stack lambdas-dev failed to deploy (11s)
Publishing service to the Serverless Dashboard...
Successfully published your service to the Serverless Dashboard: https://app.serverless.com/adamgoldman/apps/lambdas/lambdas/dev/ap-northeast-1
Environment: linux, node 18.7.0, framework 3.26.0 (local), plugin 6.2.2, SDK 4.3.2
Credentials: Serverless Dashboard, "default" provider (https://app.serverless.com/adamgoldman/apps/lambdas/lambdas/dev/ap-northeast-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
ChangeSet lambdas-dev-change-set cannot be created due to a mismatch with existing attribute Template
```

### Service configuration (serverless.yml) content

```yaml
functions:
  prompt-next-process:
    handler: handler.promptNextProcess
  prompt-scheduled-process:
    handler: handler.promptScheduledProcess

org: adamgoldman
app: lambdas
service: lambdas
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  environment:
    RESPOND_API_TOKEN: ${param:RESPOND_API_TOKEN}
    MONGODB_URI: ${param:MONGODB_URI}
    NODE_ENV: ${param:NODE_ENV}

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

```
```


### Command name and used flags

NODE_ENV=development sls deploy --verbose --stage=dev

### Command output

```shell
See "issue description"
```

### Environment information

```shell
$ serverless --version
Running "serverless" from node_modules
Framework Core: 3.26.0 (local) 3.26.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
```
