### ISSUE TITLE
VerificationMessageTemplate property fails with custom html with update to v3.26

### ISSUE THREAD

**Issue by lopezdp** [serverless/serverless#11640]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I am using server less framework to deploy cognate resources using a custom verification message template that you can see here:

`VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
          EmailMessage: '<!DOCTYPE html> <html> <head> <title>Email Signature</title> <meta content="text/html; charset=utf-8" http-equiv="Content-Type" /> </head> <body style="font-size: 10pt; font-family: Verdana, sans-serif"> <div style="display: flex; justify-content: center"> <div style="max-width: 100%"> <p style="margin-bottom: auto"> Hi and thank you for becoming a member on AutoMater, </p> <p> Please use the confirmation code below to verify your email and to complete the registration of your account as requested by the application: </p> <h1 style="font-size: 1.5em">{####}</h1> <p>Thank you,</p> <p>AutoMater&trade; Team</p> <p> Please <a href="https://automater.technology/unsubscribe">Unsubscribe</a> me from this list! </p> </div> </div> <hr /> <div style="display: flex; justify-content: center"> <table style=" max-width: 100%; font-family: Verdana, sans-serif; font-size: 10pt; border-spacing: 0; border-collapse: collapse; " cellpadding="0" cellspacing="0" > <tbody> <tr style="height: 33px"> <td style=" font-size: 16pt; font-family: Verdana, sans-serif; color: #007177; width: 500px; padding-bottom: 10px; padding-top: 5px; vertical-align: top; " valign="top" colspan="2" > <strong ><span style=" font-size: 16pt; font-family: Verdana, sans-serif; color: #3300ff; " >AutoMater Leads</span ></strong > </td> </tr> <tr> <td style=" border-right: #fff 3px solid; width: 335px; background-color: #eaeaea; text-align: left; vertical-align: middle; font-size: 10pt; font-family: Verdana, sans-serif; color: #444444; " valign="middle" > <span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #383838; font-weight: bold; " >&nbsp;Real Estate Lead Automation</span > </td> <td> <table cellpadding="0" cellspacing="0"> <tbody> <tr> <td style=" border-right: #fff 3px solid; width: 33px; background-color: #eaeaea; text-align: center; font-size: 10pt; " > <a href="https://twitter.com/bloktime_" target="_blank" rel="noopener" ><img border="0" width="33" alt="twitter icon" style="width: 33px; border: 0" src="https://www.mail-signatures.com/signature-generator/img/templates/flat/tt.png" /></a> </td> <td style="border-right:#fff 3px solid; width:33px; background-color:#eaeaea; text-align:center height:33px; text-align:center; font-size:10pt" > <a href="https://www.instagram.com/bloktime.io/" target="_blank" rel="noopener" ><img border="0" width="33" alt="instagram icon" style="width: 33px; border: 0" src="https://www.mail-signatures.com/signature-generator/img/templates/flat/it.png" /></a> </td> </tr> </tbody> </table> </td> </tr> <tr> <td style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #828282; line-height: 25px; padding-top: 10px; vertical-align: top; " valign="top" colspan="2" > <span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #575757; " >email: info@automater.technology<br /></span ><span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #575757; " >mobile: (516) 410-5330‬<span><br /></span></span ><span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #575757; " >Miami, FL USA</span > </td> </tr> </tbody> </table> </div> </body> </html>'
          EmailSubject: "Confirm your Registration with Lead AutoMater!"`

This used to work perfectly through server less framework v.3.25.1 and now breaks on 3.26 with the following error message:

`'verificationMessageTemplate.emailMessage' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}\s*]*\{####\}[\p{L}\p{M}\p{S}\p{N}\p{P}\s*]* (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException`

here is what it looks like when deployed:

<img width="1469" alt="Screenshot 2022-12-29 at 12 08 16 AM" src="https://user-images.githubusercontent.com/5707191/209905988-0492fc3e-7e23-4937-96e0-9c6b97c6e9ed.png">

For now im going to force 3.25.1 until a solution is found

### Service configuration (serverless.yml) content

```yaml
the error is in the `VerificationMessageTemplate` property:

`VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
          EmailMessage: '<!DOCTYPE html> <html> <head> <title>Email Signature</title> <meta content="text/html; charset=utf-8" http-equiv="Content-Type" /> </head> <body style="font-size: 10pt; font-family: Verdana, sans-serif"> <div style="display: flex; justify-content: center"> <div style="max-width: 100%"> <p style="margin-bottom: auto"> Hi and thank you for becoming a member on AutoMater, </p> <p> Please use the confirmation code below to verify your email and to complete the registration of your account as requested by the application: </p> <h1 style="font-size: 1.5em">{####}</h1> <p>Thank you,</p> <p>AutoMater&trade; Team</p> <p> Please <a href="https://automater.technology/unsubscribe">Unsubscribe</a> me from this list! </p> </div> </div> <hr /> <div style="display: flex; justify-content: center"> <table style=" max-width: 100%; font-family: Verdana, sans-serif; font-size: 10pt; border-spacing: 0; border-collapse: collapse; " cellpadding="0" cellspacing="0" > <tbody> <tr style="height: 33px"> <td style=" font-size: 16pt; font-family: Verdana, sans-serif; color: #007177; width: 500px; padding-bottom: 10px; padding-top: 5px; vertical-align: top; " valign="top" colspan="2" > <strong ><span style=" font-size: 16pt; font-family: Verdana, sans-serif; color: #3300ff; " >AutoMater Leads</span ></strong > </td> </tr> <tr> <td style=" border-right: #fff 3px solid; width: 335px; background-color: #eaeaea; text-align: left; vertical-align: middle; font-size: 10pt; font-family: Verdana, sans-serif; color: #444444; " valign="middle" > <span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #383838; font-weight: bold; " >&nbsp;Real Estate Lead Automation</span > </td> <td> <table cellpadding="0" cellspacing="0"> <tbody> <tr> <td style=" border-right: #fff 3px solid; width: 33px; background-color: #eaeaea; text-align: center; font-size: 10pt; " > <a href="https://twitter.com/bloktime_" target="_blank" rel="noopener" ><img border="0" width="33" alt="twitter icon" style="width: 33px; border: 0" src="https://www.mail-signatures.com/signature-generator/img/templates/flat/tt.png" /></a> </td> <td style="border-right:#fff 3px solid; width:33px; background-color:#eaeaea; text-align:center height:33px; text-align:center; font-size:10pt" > <a href="https://www.instagram.com/bloktime.io/" target="_blank" rel="noopener" ><img border="0" width="33" alt="instagram icon" style="width: 33px; border: 0" src="https://www.mail-signatures.com/signature-generator/img/templates/flat/it.png" /></a> </td> </tr> </tbody> </table> </td> </tr> <tr> <td style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #828282; line-height: 25px; padding-top: 10px; vertical-align: top; " valign="top" colspan="2" > <span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #575757; " >email: info@automater.technology<br /></span ><span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #575757; " >mobile: (516) 410-5330‬<span><br /></span></span ><span style=" font-size: 10pt; font-family: Verdana, sans-serif; color: #575757; " >Miami, FL USA</span > </td> </tr> </tbody> </table> </div> </body> </html>'
          EmailSubject: "Confirm your Registration with Lead AutoMater!"`
```

### Command name and used flags

N/A

### Command output

```shell
`Uploading CloudFormation file to S3
81	Uploading State file to S3
82	Creating new change set
83	Waiting for new change set to be created
84	Change Set did not reach desired state, retrying
85	Change Set did not reach desired state, retrying
86	Executing created change set
87	  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - automater-authentication-api-dev
88	  UPDATE_IN_PROGRESS - AWS::Cognito::UserPool - CognitoUserPool
89	  UPDATE_FAILED - AWS::Cognito::UserPool - CognitoUserPool
90	  UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - automater-authentication-api-dev
91	  UPDATE_COMPLETE - AWS::Cognito::UserPool - CognitoUserPool
92	  UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - automater-authentication-api-dev
93	  UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - automater-authentication-api-dev
94	
95	× Stack automater-authentication-api-dev failed to deploy (37s)
96	Environment: linux, node 14.19.2, framework 3.26.0, plugin 6.2.2, SDK 4.3.2
97	Docs:        docs.serverless.com
98	Support:     forum.serverless.com
99	Bugs:        github.com/serverless/serverless/issues
100	
101	Error:
102	UPDATE_FAILED: CognitoUserPool (AWS::Cognito::UserPool)`
```

### Environment information

```shell
3.26.0
```
