### ISSUE TITLE
Error with golang on provided.al2

### ISSUE THREAD

**Issue by harryzcy** [serverless/serverless#11661]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm getting `Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]` error when using `provided.al2`. How do I configure the functions exactly?

### Service configuration (serverless.yml) content

```yaml
service: example

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

package:
  patterns:
    - '!./**'
  individually: true

functions:
  exampleFunction1:
    handler: bin/functions/exampleFunction1
    package:
      patterns:
        - './bin/functions/exampleFunction1'
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.25.1
Plugin: 6.2.2
SDK: 4.3.2
```
