### ISSUE TITLE
Function is retrying every two minutes with different request ID's

### ISSUE THREAD

**Issue by morgan-young** [serverless/serverless#11672]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I've been using Serverless for a while but am having a problem here. 

My function is in python and appears to be duplicating every 2 minutes or so after I invoke it, with different request ID's. I did some googling, couldn't find anything apart from something about cli_read_timeout on boto3 (but of course with serverless, you guys are doing the lambda connection) and it looks like a bug as I don't see a way to adjust this. 
![Screenshot from 2023-01-12 01-40-36](https://user-images.githubusercontent.com/53994362/212060971-eb8a152e-f620-4893-8b32-3b32cdecc955.png)
Any help would be much appreciated as I can't use my function atm. 

And yeah, I have changed the general timeout of the function to 15 mins. Also, if it runs for under 2 mins, it's fine.

Thanks

### Service configuration (serverless.yml) content

```yaml
service: REDACTED

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_REGION, 'eu-west-2'}
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Resource: '*'
        Action: 'ssm:*'
      - Effect: 'Allow'
        Resource: '*'
        Action: 'ses:*'
      - Effect: 'Allow'
        Resource: '*'
        Action: 'dynamodb:*'
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  robot:
    timeout: 900
    events:
      # Invoke Lambda function every day at 6am
      - schedule: cron(0 6 * * ? *)
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function. See #102
    memorySize: 2048
    image:
      name: img
```

### Command name and used flags

sls invoke -f robot

### Command output

```shell
Nothing returns. It just runs, but then another function will run two minutes later.
```

### Environment information

```shell
Framework Core: 3.17.0 (local) 3.17.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
