### ISSUE TITLE
AWS API Gateway provider.apiGateway.stage not working

### ISSUE THREAD

**Issue by mpage-hearsay** [serverless/serverless#11675]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I started a [discussion](https://github.com/serverless/serverless/discussions/11664) for this but it's not getting any traction so I'm opening this issue.

I am trying to override the AWS API Gateway Stage name as described [here](https://www.serverless.com/framework/docs/providers/aws/events/apigateway#providing-a-custom-stage-name:~:text=disableDefaultEndpoint%3A%20true-,Providing%20a%20custom%20stage%20name,-By%20default%2C%20the).

However, when I deploy it doesn't create a stage with the overridden name value. It still defaults to using the Serverless stage name for the new API Gateway Stage.

These are the URLs I see in the deployed API Gateway Stage(s):

```
https://asdfjkl.execute-api.my-region.amazonaws.com/dev/dev/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/dev/dev/f2
https://asdfjkl.execute-api.my-region.amazonaws.com/prod/prod/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/prod/prod/f2
```

Instead I want to have:

```
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/dev/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/dev/f2
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/prod/f1
https://asdfjkl.execute-api.my-region.amazonaws.com/foobar/prod/f2
```

### Service configuration (serverless.yml) content

```yaml
provider:
  apiGateway:
    restApiId: 1111
    restApiRootResourceId: 2222
    stage: foobar
...

functions:
  func1:
    name: func1-${opt:stage, 'dev'}
    handler: bin/func1
    events:
      - http:
        path: /${opt:stage, 'dev'}/f1
        method: get
  func2:
    name: func2-${opt:stage, 'dev'}
    handler: bin/func2
    events:
      - http:
        path: /${opt:stage, 'dev'}/f2
        method: post
```

### Command name and used flags

sls deploy --stage dev

### Command output

```shell
N/A (deploys successfully).
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.25.1 (local) 3.26.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by mpage-hearsay** [comment]
FYI, I started a [discussion](https://github.com/serverless/serverless/discussions/11664) for this but it's not getting any traction so I opened this issue.

**Comment by medikoo** [comment]
@mpage-hearsay thanks for reporting. Indeed it looks there's a bug, as `provider.apiGateway.stage` is recognized as valid property, yet it seems ineffective.

PR with a fix is welcome!

**Comment by jasonrowsell** [comment]
Hey @mpage-hearsay, I don't think this is an issue. You're trying to reference the stage through using `opt:`, which is for referencing CLI options (ie `serverless deploy --stage foobar`). If you wish to reference the stage defined in your serverless.yml, you'll need to use `self:provider.apiGateway.stage`. Please see https://www.serverless.com/framework/docs/providers/openwhisk/guide/variables for more information.

@medikoo is this right?

**Comment by jattkaim** [comment]
I would love to know if this was ever working? Seems like the code change made in October was quite simple. I am also facing this issue & trying to debug how/where it is going wrong

**Comment by medikoo** [comment]
> I would love to know if this was ever working? Seems like the code change made in October was quite simple. I am also facing this issue & trying to debug how/where it is going wrong

As I checked, it didn't see my comment in original PR

**Comment by jattkaim** [comment]
oh sorry! are we able to mention that PR here. This would be quite a crucial feature for a new SaaS application I was building based off the assumption that this was functional 😞  Happy to help but I currently do not know where to start haha 😢

**Comment by mpage-hearsay** [comment]
@medikoo a question I have about the fix.

What if the API Gateway stage already exists? Will the SLS deploy overwrite an existing stage with the given name?

I ask because we have stages/resources/methods that are defined/managed outside of serverless. I need my serverless app to just add resources/methods to the existing gateway stage.

**Comment by medikoo** [comment]
> @medikoo a question I have about the fix. What if the API Gateway stage already exists?

Such a scenario should only be taken into account if service references an external API Gateway, then I believe updates done via AWS SDK are not considered at all (as we do allow updating API-wide properties when we work with externally defined API) and when endpoints setup in CF is considered it safe to define _stage_ deployment (it won't break other endpoints deployments made to the same stage from eventual another stack)

**Comment by gmetzker** [comment]
Would be nice to see this work for ApiGatewayV2 as well.  Something like:
```yaml
provider:
  apiGateway:
    stage: customStageName
```

As a work around it seems to work if you add some partial content to the Resources section:
```yaml
Resources:
  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      "StageName": "customStageName"
```

**Comment by kevb10** [comment]
> Would be nice to see this work for ApiGatewayV2 as well. Something like:
> 
> ```yaml
> provider:
>   apiGateway:
>     stage: customStageName
> ```
> 
> As a work around it seems to work if you add some partial content to the Resources section:
> 
> ```yaml
> Resources:
>   HttpApiStage:
>     Type: AWS::ApiGatewayV2::Stage
>     Properties:
>       "StageName": "customStageName"
> ```

the workaround here is confirmed to work. just make sure it's under resources like so

```yml
resources:
  Resources:
    HttpApiStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        "StageName": "customStageName"
```

**Comment by theRocket** [comment]
We have been using the following syntax and it's been working fine. Stage is at `provider` level.
```
  apiGateway:
    shouldStartNameWithService: true
    description: ${self:custom.description.${opt:stage}, self:custom.description.nonprod}
    usagePlan: ${file(./serverless/usage-plans.yml):usagePlan}
  stage: ${opt:stage}
```
