### ISSUE TITLE
Add max concurrency support for AWS Lambda functions when using AWS SQS as an event source

### ISSUE THREAD

**Issue by shreyance-jain** [serverless/serverless#11676]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Since 12 Jan 2023A WS Lambda now supports setting Maximum Concurrency to the Amazon SQS event source. Maximum Concurrency for SQS as an event source allows customers to control the maximum concurrent invokes by the Amazon SQS event source.  (see release [announcement here](https://aws.amazon.com/about-aws/whats-new/2023/01/aws-lambda-maximum-concurrency-amazon-sqs-event-source/) and [compute blog from AWS](https://aws.amazon.com/blogs/compute/introducing-maximum-concurrency-of-aws-lambda-functions-when-using-amazon-sqs-as-an-event-source/))
I suggest we had the capability to define max concurrency in Serverless framework 

### Proposed solution (optional)

```
functions:
  compute:
    handler: handler.compute
    events:
      - sqs:
          arn: arn:aws:sqs:region:XXXXXX:myQueue
          batchSize: 10
          maximumBatchingWindow: 60
          maximumConcurrency: 10
```
