### ISSUE TITLE
Allow environment variables based on Fn::Base64

### ISSUE THREAD

**Issue by ronkorving** [serverless/serverless#11670]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

I so so wish I had spotted this during the conversation in https://github.com/serverless/serverless/issues/11409, because it would've probably saved a lot of time. My goal was to base64 encode a JSON structure that I pulled out of a YAML file (via `{self:custom.}` and use that as an environment variable.

Example:

```yaml
environment:
  FOOBAR:
    "Fn::Base64":
      "Fn::ToJsonString": ${self:custom.foobar}
```

@jurriaanpro was kind enough to implement Fn::ToJsonString in https://github.com/serverless/serverless/pull/11461, but I completely missed that `Fn::Base64` is not supported _either_ in environment variables.

### Proposed solution (optional)

https://github.com/serverless/serverless/pull/11671
