### ISSUE TITLE
When creating domain: Invalid tag key. Tag keys cannot start with 'aws:'

### ISSUE THREAD

**Issue by ScopeSV** [serverless/serverless#11692]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Suddenly, when creating a new domain, I get the error 
```
CREATE_FAILED: CustomDomain (AWS::ApiGatewayV2::DomainName)
Invalid tag key. Tag keys cannot start with 'aws:' (case insensitive) 
(Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; 
Request ID: e84a3348-81ee-4405-84ee-72a8e6100d94; Proxy: null)
```

I'm not setting any keys, so I'm not sure what's trying to set a key with `aws:`.

This worked a couple of days ago on a another cloudformation. 

I did find this new issue at aws-cdk, not sure if its related: https://github.com/aws/aws-cdk/issues/23737

### Service configuration (serverless.yml) content

```yaml
Only this is applicable for the error. 


resources:
  Resources:
    CustomDomain:
      Type: AWS::ApiGatewayV2::DomainName
      DependsOn:
        - Certificate
      Properties:
        DomainName: domain-name
        DomainNameConfigurations:
          - CertificateArn: !Ref Certificate
            SecurityPolicy: TLS_1_2
            EndpointType: REGIONAL
```

### Command name and used flags

serverless deploy --stage dev

### Command output

```shell
Deploying hidden to stage dev (eu-west-1)

Packaging
Compiling with Typescript...
Using local tsconfig.json - tsconfig.json
Warning: "rootDir" from local tsconfig.json is overriden
Typescript compiled.
Excluding development dependencies for service package
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service hidden.zip file to S3 (53.04 MB)
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - api-hidden-dev
  CREATE_IN_PROGRESS - AWS::ApiGatewayV2::DomainName - CustomDomain
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - ApiLambdaFunction
  CREATE_FAILED - AWS::ApiGatewayV2::DomainName - CustomDomain
  UPDATE_FAILED - AWS::Lambda::Function - ApiLambdaFunction
  UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - hidden
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - ApiLambdaFunction
  UPDATE_COMPLETE - AWS::Lambda::Function - ApiLambdaFunction
  UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - hidden  DELETE_COMPLETE - AWS::ApiGatewayV2::DomainName - CustomDomain
  UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - hidden

✖ Stack hidden failed to deploy (103s)
Environment: darwin, node 14.18.1, framework 3.25.1 (local) 3.23.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: CustomDomain (AWS::ApiGatewayV2::DomainName)
Invalid tag key. Tag keys cannot start with 'aws:' (case insensitive) (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: e84a3348-81ee-4405-84ee-72a8e6100d94; Proxy: null)

View the full error:
```

### Environment information

```shell
Framework Core: 3.25.1 (local) 3.23.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
