### ISSUE TITLE
Env Vars not being updated in Lambda

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [serverless/serverless#11703]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

#### Steps to reproduce

- Deploy lambda function using serverless, in which lambda function has some env vars.
- Remove one or two env vars in the AWS console.
- Re-deploy the function using serverless

Result: Env vars removed in step 2 were not restored even after the new deployment.

### Service configuration (serverless.yml) content

```yaml
service: serverless-test

useDotenv: true

custom:
  config:
    CODE_DEPLOYMENT_BUCKET: ${env:CODE_DEPLOYMENT_BUCKET}
    ABC: "ABC"
    XYZ: "XYZ"

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'alpha'}
  timeout: 30
  region: ${opt:region, 'ap-south-1'}
  deploymentBucket:
    blockPublicAccess: true
    name: ${self:custom.config.CODE_DEPLOYMENT_BUCKET}
    maxPreviousDeploymentArtifacts: 3

functions:
  test-function:
    handler: handler.lambda_handler
    environment:
      ABC: ${self:custom.config.ABC}
      XYZ: ${self:custom.config.XYZ}
```

### Command name and used flags

serverless deploy --stage <stage> --aws-profile <profile>

### Command output

```shell
Deploying serverless-test to stage beta (ap-south-1)

✔ Service deployed to stack serverless-test-beta (28s)

functions:
  test-function: serverless-test-beta-test-function (153 kB)

Need a better logging experience than CloudWatch? Try our Dev Mode in console: run "serverless --console"
```

### Environment information

```shell
Framework Core: 3.26.0
Plugin: 6.2.2
SDK: 4.3.2
```
