### ISSUE TITLE
AWS Lambda Function deploy with SNS events - filterPolicyScope property not recognized

### ISSUE THREAD

**Issue by juantula** [serverless/serverless#11710]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

For SNS trigger events on lambda functions, the "filterPolicyScope" is not recognized nor applied.

### Service configuration (serverless.yml) content

```yaml
functions:
  example:
    name: example
    handler: dist/example.handler
    description: Example
    memorySize: 128
    timeout: 30
    events:
      - sns:
          arn: ${topic.arn}
          displayName: Trigger events
          filterPolicy: 
            detail:
              destinationReference: 
                - "refs/heads/main"
          filterPolicyScope: MessageBody
```

### Command name and used flags

sls deploy

### Command output

```shell
Running "serverless" from node_modules

Warning: Invalid configuration encountered
  at 'functions.process-notifications.events.0.sns': unrecognized property 'filterPolicyScope'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.26.0 (local) 3.26.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
