### ISSUE TITLE
ResponseHeadersPolicyId  occurs Invalid request provided error

### ISSUE THREAD

**Issue by wjybestcool** [serverless/serverless#11729]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I add the field ”ResponseHeadersPolicyId“ in .yml file, This error occurs Invalid request provided: The specified origin access identity does not exist or is not valid.
I'm sure this ID exists and is valid

### Service configuration (serverless.yml) content

```yaml
cloudfront.yml

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_All
        Aliases:
        - xxx
        Origins:
        - Id: xxx
          DomainName: xxx
          S3OriginConfig:
            OriginAccessIdentity: xxx
        DefaultRootObject: xxx
        DefaultCacheBehavior:
          TargetOriginId: xxx
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
          - GET
          - HEAD
          CachedMethods:
          - GET
          - HEAD
          DefaultTTL: 60
          MaxTTL: 300
          MinTTL: 60
          Compress: true
          ResponseHeadersPolicyId: "xxx"
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
        ViewerCertificate:
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
          AcmCertificateArn: xxx
        HttpVersion: http2
        Enabled: true
```

serverless.yml
```
service: xxxx
useDotenv: true
plugins:
  - serverless-s3-sync
package:
  patterns:
    - "!./**"
provider:
  name: aws
  runtime: python3.8
  timeout: 29 
  stage: ${opt:stage, "kaihatsu"}
  region: ${opt:region, "us-west-2"}
  profile: ${opt:profile, "default"}

custom:
  s3Sync:
    - bucketName: xxx
      bucketPrefix: xxxx
      localDir: xxx
  resourceNamePrefix: xxx

functions: # NO function need

resources:
  - ${file(./resource_config/cloudfront.yml)}
```
```


### Command name and used flags

serverless deploy --config serverless.yml --stage kaihatsu  --region us-west-2

### Command output

```shell
UPDATE_FAILED: CloudFrontDistribution (AWS::CloudFront::Distribution)
Resource handler returned message: "Invalid request provided: The specified origin access identity does not exist or is not valid. (Service: CloudFront, Status Code: 400, Request ID: xxxxxxxxx )" (RequestToken: xxxxxxxxxxxx, HandlerErrorCode: InvalidRequest)
```

### Environment information

```shell
Framework Core: 3.27.0
Plugin: 6.2.3
SDK: 4.3.2
Tencent CLI: 3.21.6 (binary)
```
