### ISSUE TITLE
serverless did not remove alb target group

### ISSUE THREAD

**Issue by shuangqiu123** [serverless/serverless#11726]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

`serverless remove` remove did not remove the target group.
When I ran `serverless deploy`, it gave me the error:
`Resource of type 'AWS::ElasticLoadBalancingV2::TargetGroup' with identifier '' already exists.`

### Service configuration (serverless.yml) content

```yaml
service: hello-world

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: staging

functions:
  hello:
    handler: index.js
    events:
      - alb:
          listenerArn: 
          priority: 99
          targetGroupName: hello-world-tg
          conditions:
            path: /lambda
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.27.0
Plugin: 6.2.3
SDK: 4.3.2
```
