### ISSUE TITLE
Invalid parameters: VIRTUAL_HOST when update application with event source

### ISSUE THREAD

**Issue by nserbass** [serverless/serverless#11733]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi Team!

I've deploy and application with some event sources based on AmazonMQ (RabbitMQ). The first time is deployed properly, but when I try to update my application I'm always getting an error. Looking for more information, I've found out that AWS Cloudformation doesn't allow to perform an `UpdateEventSourceMapping` with property `VIRTUAL_HOST`. More info: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventsourcemapping-sourceaccessconfiguration.html

Is there something I'm missing?

### Service configuration (serverless.yml) content

```yaml
service: api

custom:
  layerConfig:
    packager: 'npm'
    webpack:
      configPath: ./webpack.config.js
      includeModules: false
      externals: [ nodeExternals() ]
  serverless-offline:
    useChildProcesses: true
  customDomain:
    domainName: ${param:domain}
    basePath: ''
    stage: ${self:provider.stage}
    endPointType: regional
    certificateArn: <arn-cert>
    createRoute53Record: true
    enabled: true
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true
  subscriberDir: src
  vhost: ${param:prefix}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-resource-tagging

provider:
  name: aws
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: us-east-1
  stackTags:
    prefix: ${param:prefix}
    domain: ${param:domain}
    branch: ${param:branch}
    user: ${param:user}
    only_api: ${param:only_api}
  vpc:
    securityGroupIds:
      - xxxxx
    subnetIds:
      - xxxxx

  layers:
    - { Ref: DependenciesLambdaLayer }
functions:
  sendConfirmationEmailOnUserWasCreated:
    handler: ${self:custom.subscriberDir}/Web/User/Infrastructure/Lambda/LambdaSendConfirmationEmailOnUserWasCreatedSubscriber.handler
    memorySize: 1024
    timeout: 30
    events:
      - rabbitmq:
          arn: <arn>
          queue: user.register.send_confirmation_email_on_user_was_created
          batchSize: 10
          maximumBatchingWindow: 10
          basicAuthArn: <arn-secret-manager-credentials>
          virtualHost: test
package:
  individually: true
  excludeDevDependencies: true
layers:
  dependencies:
    path: .deps-layer
    description: 'Dependencies layer'
```
```


### Command name and used flags

serverless deploy --config serverless.stage.yml --stage test --param=branch=test --param=domain=xxx --param=prefix=test --param=user=test --param=only_api=true

### Command output

```shell
Deploying api to stage test (us-east-1)
Updated AWS resource tags..

× Stack api-test failed to deploy (475s)
Environment: linux, node 14.19.1, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: SendConfirmationEmailOnUserWasCreatedEventSourceMappingRabbitMQUserregistersendconfirmationemailonuserwascreated (AWS::Lambda::EventSourceMapping)
Resource handler returned message: "Invalid request provided: Invalid parameters: VIRTUAL_HOST (Service: Lambda, Status Code: 400, Request ID: 606ac840-1630-4f70-92e1-c9912f3b0f6e)" (RequestToken: 5a54d77c-c538-c854-e96c-71cad5c6b093, HandlerErrorCode: InvalidRequest)
```

### Environment information

```shell
Framework Core: 3.19.0
Plugin: 6.2.2
SDK: 4.3.2
```
