### ISSUE TITLE
Support for AWS EventBridge Pipes

### ISSUE THREAD

**Issue by bradwood** [serverless/serverless#11735]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS recently announced [EventBridge Pipes](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes.html)

I would like to be able to add an "Enrichment Lambda" to an AWS EventBridge Pipe using the serverless framework.

**Comment by medikoo** [comment]
@bradwood, thanks for reporting that. Can you propose how do you envision providing support for this in the Framework. What would be the new properties added to the configuration and hat would be the effect in generated CloudFormation stack?

**Comment by bradwood** [comment]
@medikoo -- I don't have a strong view on it -- my interest in the serverless framework is more as a PO for a team that uses the framework.

**Comment by cmygray** [comment]
reference:
- [cloudformation resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pipes-pipe.html)
- [eventbridge pipe sources](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-source.html)

input sls template

```yaml
resources:
  Resources:
    MyPipe:
      Type: AWS::Pipes::Pipe
      Properties:
        RoleArn: !Ref AllowSendingToTargetRole
        Source: !Ref MyTable
        Target: !Ref MyEventBus
```

output CF template

```json
{
  "Type" : "AWS::Pipes::Pipe",
  "Properties" : {
    "RoleArn": "arn:aws:iam::000000000000:role/allow-sending-to-target-role",
    "Source": "arn:aws:dynamodb:ap-northeast-2:000000000000:table/my-table",
    "Target": "arn:aws:events:ap-northeast-2:000000000000:event-bus/my-event-bus"
  }
}
```

This is an example template containing only minimum properties(required).
Maybe someone can improve to use things later:
- enrichment
- source params
- target params
