### ISSUE TITLE
eventBridge gives error because it doesn't have lambda:RemovePermission permission

### ISSUE THREAD

**Issue by epicfaace** [serverless/serverless#11730]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I get the following error with eventbridge after upgrading to serverless v3:

<code>
DELETE_FAILED: UpdateScanTaskStatusCustomEventBridge1 (AWS::CloudFormation::CustomResource)
Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::...:assumed-role/crossfeed-staging-IamRoleCustomResourcesLambdaExec-1R4NLUPXSXF94/crossfeed-staging-custom-resource-event-bridge is not authorized to perform: lambda:RemovePermission on resource: arn:aws:lambda:us-east-1:...:function:crossfeed-staging-updateScanTaskStatus because no identity-based policy allows the lambda:RemovePermission action See details in CloudWatch Log: 2023/02/08/[$LATEST]e569ee5357c146518dabbfb145086168 (RequestId: a9334d30-1f88-4dac-925b-b95d9fd00ff6)
</code>

### Service configuration (serverless.yml) content

```yaml
updateScanTaskStatus:
  handler: src/tasks/updateScanTaskStatus.handler
  events:
    - eventBridge:
        pattern:
          source:
            - aws.ecs
          detail-type:
            - ECS Task State Change
          detail:
            clusterArn:
              - ${file(env.yml):${self:provider.stage}-ecs-cluster, ''}
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.25.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```
