### ISSUE TITLE
No integration defined for method - When using API Gateway v1

### ISSUE THREAD

**Issue by rsandrea** [serverless/serverless#11748]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Whenever I try to deploy a service that uses API Gateway v1 it fails with the error:

CREATE_FAILED: ApiGatewayDeployment############ (AWS::ApiGateway::Deployment)
Resource handler returned message: "No integration defined for method (Service: ApiGateway, Status Code: 400, Request ID: #######-####-####-####-##########)" (RequestToken: #######-####-####-####-##########, HandlerErrorCode: InvalidRequest)

I tried with old functions that used to deploy ok, and now they all return with the same error message.

### Service configuration (serverless.yml) content

```yaml
org: XXXXX
app: xxxxxx
service: xxxxxxxxxxxxxxxxxx
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    restApiId: xxxxxxxxxxxx
    restApiRootResourceId: xxxxxxxxx
  iam:
    role: arn:aws:iam::xxxxxxxxxx:xxxxxxxxxxxxxxxxxx

functions:
  process:
    handler: handler.process
    name: "API_xxxxxxxxxxxxxx-${sls:stage}"
    events:
      - http:
          path: /release
          method: get
          private: true
          request:
            parameters:
              querystrings:
                AccountGuid: true
                TelephoneNumber: true
    vpc:
      securityGroupIds:
        - sg-xxxxxxxxxxxxxxxxxx
      subnetIds:
        - subnet-xxxxxxxxxxxxxx
        - subnet-yyyyyyyyyyyyyy
        - subnet-zzzzzzzzzzzzzz
```

### Command name and used flags

serverless deploy --stage=production

### Command output

```shell
Running "serverless" from node_modules

Deploying api-release to stage production (us-east-1, "aws" provider)

✖ Stack api-release-production failed to deploy (54s)
Environment: linux, node 16.18.0, framework 3.15.0 (local) 3.27.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Serverless Dashboard, "aws" provider (https://app.serverless.com/xxxxxxxxxx/apps/xxxxx/api-release/production/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: ApiGatewayDeployment1676326142889 (AWS::ApiGateway::Deployment)
Resource handler returned message: "No integration defined for method (Service: ApiGateway, Status Code: 400, Request ID: fc2eed40-309d-4927-a24d-7649aeae6a93)" (RequestToken: 370a0223-e5c8-0cdb-02b3-e6f06f0ed33d, HandlerErrorCode: InvalidRequest)

View the full error: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A148107793690%3Astack%2Fapi-release-production%2F7fce28b0-c28c-11ec-931d-0e523b72cb63
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.27.0 (local) 3.27.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
