### ISSUE TITLE
deploymentBucket serverSideEncryption does not work with kms configuration

### ISSUE THREAD

**Issue by adamyodinsky** [serverless/serverless#11749]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm having an issue with using KMS for the deployment bucket as described in [the documentation under "Deployment bucket"](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml).

```yaml
provider:
  deploymentBucket:
    serverSideEncryption: "aws:kms"
    sseKMSKeyId: "alias/aws/s3" 
```
    
    
Getting in the update stack file (cloudformation-template-update-stack.json)
with  `"SSEAlgorithm": "AES256"`, not kms. 

```json
"Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
            ...
```

### Service configuration (serverless.yml) content

```yaml
service: myserverless

frameworkVersion: '2 || 3'

variablesResolutionMode: '20210326'

plugins:
  - serverless-offline

package:
  patterns:
    - '!**'
    - 'src/**'
    - 'templates/**'
    - 'get_folder/**'

custom:
  aws_account: ${aws:accountId}


provider:
  deploymentBucket:
    serverSideEncryption: 'aws:kms'
    sseKMSKeyId: 'alias/aws/s3'
    blockPublicAccess: true
    tags:
      "test": "3"
  name: aws
  region: us-west-2
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: 'dev'
  httpApi:
    useProviderTags: true
  tags:
    "test": "3"
  iam:
    role:
      name: <role-arn-masked>
      permissionsBoundary: <policy-arn-masked>
      tags:
        "test": "3"

functions:
  getIndex:
    handler: src/render_template.handler
    environment:
      template_env: ${file(./get_folder/get_folder.js)}
    tags:
      "test": "3"
```

### Command name and used flags

serverless package, serverless deploy

### Command output

```shell
Running "serverless" from node_modules

Packaging cosv3sls-myserverless-adam-101 for stage dev (us-west-2)

✔ Service packaged (0s)

3 deprecations found: run 'serverless doctor' for more details
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.27.0 (local) 3.20.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
