### ISSUE TITLE
Compiler of serverless framework change value of environment variable if it is number 

### ISSUE THREAD

**Issue by thanhduyluu** [serverless/serverless#11743]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I would like config FOO: 10553291267149319188 is environment variable, after I use sls print or sls deploy the compiler of serverless framework changed my variable to FOO: 10553291267149320000.

if I change FOO: "10553291267149319188", value of FOO still "10553291267149319188", it's correct .

Anyone has problem same me or please can you tell me why compiler change value of my variable

### Service configuration (serverless.yml) content

```yaml
service: aws-node-express-api
plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 127.0.0.1
    port: 3006
  stages:
    dev: 
      STAGE: dev
      FOO: BAR
      PROVISIONED_CONCURRENCY: 15
    test: 
      STAGE: test
      FOO: 1050659265498583164
      PROVISIONED_CONCURRENCY: 15
    prod: 
      STAGE: prod
      FOO: prod
      PROVISIONED_CONCURRENCY: 15
    
provider:
  name: aws
  runtime: nodejs16.x
  profile: can-project
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'ap-east-1'}
  endpointType: REGIONAL
  environment:
    NODE_ENV: production
    FOO: ${self:custom.stages.${self:provider.stage}.FOO}

functions:
  apiExpressTestEnv:
    environment:
      FOO: ${self:custom.stages.${self:provider.stage}.FOO}
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /env
          method: GET
  
  apiExpressTestCI:
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server_api.handler
    events:
      - http:
          path: /api
          method: GET
      - http:
          path: /api/env
          method: GET
```

### Command name and used flags

yarn sls print

### Command output

```shell
yarn run v1.22.19
warning ../../../package.json: No license field
$ /home/ubuntu/serverless/packages/test-lambda-node/node_modules/.bin/sls print
service: aws-node-express-api
plugins:
  - serverless-offline
custom:
  serverless-offline:
    host: 127.0.0.1
    port: 3006
  stages:
    dev:
      STAGE: dev
      FOO: BAR
      PROVISIONED_CONCURRENCY: 15
    test:
      STAGE: test
      FOO: 1050659265498583200
      PROVISIONED_CONCURRENCY: 15
    prod:
      STAGE: prod
      FOO: prod
      PROVISIONED_CONCURRENCY: 15
provider:
  name: aws
  runtime: nodejs16.x
  profile: can-project
  stage: test
  region: ap-east-1
  endpointType: REGIONAL
  environment:
    NODE_ENV: production
    FOO: '1050659265498583200'
  versionFunctions: true
functions:
  apiExpressTestEnv:
    environment:
      FOO: '1050659265498583200'
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /env
          method: GET
    name: aws-node-express-api-test-apiExpressTestEnv
  apiExpressTestCI:
    memorySize: 128
    timeout: 30
    tracing: true
    handler: server_api.handler
    events:
      - http:
          path: /api
          method: GET
      - http:
          path: /api/env
          method: GET
    name: aws-node-express-api-test-apiExpressTestCI
```

### Environment information

```shell
ubuntu@test-instance:~/serverless/packages/test-lambda-node$ yarn sls --version
yarn run v1.22.19
warning ../../../package.json: No license field
$ /home/ubuntu/serverless/packages/test-lambda-node/node_modules/.bin/sls --version
Framework Core: 3.27.0 (local)
Plugin: 6.2.3
SDK: 4.3.2

Done in 1.24s.
```
