### ISSUE TITLE
Cannot use nested operator on function events

### ISSUE THREAD

**Issue by eacet** [serverless/serverless#11757]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have to use `!ImportValue` and `!Join` operators together for `Kinesis Stream Event`.
But it doesn't implemented on framework. Problem comes from [here](https://github.com/serverless/serverless/blob/18d4d69eb3b1220814ab031690b6ef899280a93a/lib/plugins/aws/package/compile/events/stream.js#L171).

### Service configuration (serverless.yml) content

```yaml
service: 'example'
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

custom:
  kinesisStreamName: !Join
    - '-'
    - - 'external'
      - '${sls:stage}'
      - 'DynamoDBKinesisStreamArn'
  
  kinesisStreamArn: !ImportValue '${self:custom.kinesisStreamName}'

functions:
  delete:
    handler: index.handler
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.kinesisStreamArn}
          startingPosition: LATEST
          batchSize: 100
          batchWindow: 5
          maximumRetryAttempts: 3
          filterPatterns:
            - data:
                eventName: [REMOVE]
```

### Command name and used flags

serverless package

### Command output

```shell
Packaging example for stage dev (us-east-1)
Environment: darwin, node 18.6.0, framework 3.26.0 (local), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: name.replace is not a function
    at Object.normalizeNameToAlphaNumericOnly (/Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
    at Object.getStreamLogicalId (/Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/plugins/aws/lib/naming.js:388:14)
    at /Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:189:58
    at Array.forEach (<anonymous>)
    at /Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:147:28
    at Array.forEach (<anonymous>)
    at AwsCompileStreamEvents.compileStreamEvents (/Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:97:47)
    at PluginManager.runHooks (/Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at async PluginManager.invoke (/Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/classes/plugin-manager.js:564:9)
    at async PluginManager.run (/Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/erhan/repos/serverless-simple-stack/node_modules/serverless/lib/serverless.js:179:5)
    at async /Users/erhan/repos/serverless-simple-stack/node_modules/serverless/scripts/serverless.js:812:9
```

### Environment information

```shell
Framework Core: 3.26.0
Plugin: 6.2.2
SDK: 4.3.2
```
