### ISSUE TITLE
request schema validation went bad =(

### ISSUE THREAD

**Issue by frani** [serverless/serverless#11754]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I can find what is wrong in my "request schema validation" settings

### Service configuration (serverless.yml) content

```yaml
org: ***
app: reporter
service: reporter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x


functions:
  # base endpoint to generate reports
  reports_generate:
    handler: functions/reports.generate
    events:
      - httpApi:
          path: /reports
          method: post
          request:
            schema:
              type: object
              properties:
                s3Key:
                  type: string
                  required: true
                  minLength: 10
```
```


### Command name and used flags

sls invoke local --function reports_generate --data '{"s3Key":"reports/55828b2787bd_06-02-2023.json"}'

### Command output

```shell
Environment: darwin, node 16.2.0, framework 3.27.0, plugin 6.2.3, SDK 4.3.2
Credentials: Serverless Dashboard, "reporter" provider (https://app.serverless.com/****/apps/reporter/reporter/dev/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Configuration error at 'functions.reports_generate.events.0.httpApi': unrecognized property 'request'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Framework Core: 3.27.0
Plugin: 6.2.3
SDK: 4.3.2
```
