### ISSUE TITLE
Using resourcePolicy results in 403 Forbidden

### ISSUE THREAD

**Issue by piotrwalczak1** [serverless/serverless#11808]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have an api gateway deploy with /helloworld endpoint. I does not require authentication, but it requires an api key.

When I am trying to use a resourcePolicy setting:

```
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          IpAddress:
            aws:SourceIp: ["0.0.0.2", "240.240.240.240"]
```

I am getting the following error:
```
{
  "Message" "User: annonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:eu-west-1:******:<idOfGateway>/test/GET/helloworld
}
```

I don't understand why. I have also tried another Conditions (aws:SourceArn) but the very same error occurrs. How to debug this further ? It seems as a bug to me. According to documentation this should be enough to do the restriction.

### Service configuration (serverless.yml) content

```yaml
resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          IpAddress:
            aws:SourceIp: ["0.0.0.2", "240.240.240.240"]
```
```


### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
3.26.0
```
