### ISSUE TITLE
Support Swift AWS Lambda Runtime

### ISSUE THREAD

**Issue by darylteo** [serverless/serverless#11840]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Swift has an officially supported AWS Lambda Runtime for Swift applications. 

https://www.swift.org/blog/AWS-lambda-runtime/

It would be good if we could support Swift projects without reliance on self hosted OpenWhisk or IBM. 

### Proposed solution (optional)

Ideally this would be a local swift supported project that would

 - enable offline simulation with the Swift LocalLambdaServer
 - compile and archive swift functions to AWS
 - automatically install and configure a Swift Custom Runtime in AWS

**Comment by medikoo** [comment]
@darylteo Thanks for openning that. I believe that this should be introduced as a plugin, especially that (if I see correctly) Swift runtime is not issued by the AWS.

**Comment by darylteo** [comment]
Yes the runtime is a custom baked docker Amazon Linux 2 image that bakes in the archived Swift code and uploads as zip. Not sure if this is better than just a Lambda Layer approach, but if a plugin just wraps around the package then I see no reason to reuse the behaviour.

I guess the question would be how well can a plugin wrap around SwiftPM.

**Comment by PenniePhillippyX** [comment]
Id some research and it seems like there's currently no existing issue for this, but it would definitely be worth creating one and getting the community involved in this project.

**Comment by medikoo** [comment]
@PenniePhillippyX isn't this the open issue for this?

**Comment by darylteo** [comment]
I'm happy to contribute whatever I can while I embark on this journey ...

I have a working POC with the following setup

Serverless.yml
```
plugins:
  - ./swift-plugin.mjs # using my own plugin
  - serverless-better-credentials
  - serverless-dynamodb-local
  - serverless-offline
 
provider:
  name: aws
  region: ap-southeast-2
  architecture: arm64 # must match the runtime below, provided for x86, provided.al2 for graviton
  deploymentMethod: direct

functions:
  swift:
    # anything can go here, but might be useful for future?
    # https://github.com/swift-server/swift-aws-lambda-runtime/issues/57
    handler: src/builders/ios-swiftui/MyLambda 
    
    # this is required if compiling on m1, set to provided if compiling on x86 for now...
    # swiftpm lets you define which one to use by overriding the docker image 
    runtime: provided.al2 
    
    package:
      artifact: ./path/to/swiftpm/.build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/MyLambda/MyLambda.zip
```

myplugin.mjs
```
import { exec } from 'node:child_process';

export default class SwiftPlugin {
  #log;

  constructor(serverless, cliOptions, { log }) {
    this.#log = log;

    this.hooks = {
      'offline:start:init': () => this.#init(),
      'offline:start:end': () => this.#teardown(),
      'package:initialize': () => this.#compileFunctions(), // weird bug here, using package:compileFunctions is too late and leads to errors
    };
  }
  
  #init() {
    // Initialization
    const options = {
      cwd: './src/builders/ios-swiftui',
      env: {
        ...process.env,
        'LOCAL_LAMBDA_SERVER_ENABLED': true,
      }
    };
    
    this.#log.info('Starting server for Swift lambda');
    
    this.process = exec('swift run', options, (error, stdout, stderr) => {
      if (error) {
        this.#log.error(`exec error: ${error}`);
        return;
      }
      
      this.#log.info(stdout);
      this.#log.error(stderr);
    });
  }
  
  #teardown() {
    if (this.process) {
      this.process.kill();
    }
  }
  
  async #compileFunctions() {
    // Before deploy
    const options = {
      cwd: './src/builders/ios-swiftui',
      env: {
        ...process.env,
      }
    };
    
    console.log('Archiving server for Swift lambda');

    return new Promise((resolve, reject) => {
      this.process = exec('swift package --disable-sandbox archive', options, (error, stdout, stderr) => {
        if (error) {
          reject(error);
          return;
        }
        
        this.#log.info(stdout);
        this.#log.error(stderr);
        resolve();
      });
    });
  }
}
```

---

Unfortunately there is a limitation of the serverless-offline plugin (only supports standard runtimes) that prevents me from using the SwiftPM local server in offline mode. I've created [#1673](https://github.com/dherault/serverless-offline/issues/1673) in this regard.

---

What could an official plugin do? 

 - support offline development/invoking/debugging with SwiftPM Local Server and Serverless Offline (managing multiple local server processes with different ports)
 - automatically restart the compilation to hotreload
 - manage the compilation and deployment of multiple swift functions (see this [ticket](https://github.com/swift-server/swift-aws-lambda-runtime/issues/117) - they seem to be internally discussing how to handle multiple functions at this point)
 - supply a synthetic "supported runtime version" such as `swift5` and `swift5.al2` perhaps
