### ISSUE TITLE
Github actions failing to deploy with serverless compose

### ISSUE THREAD

**Issue by dmarzan** [serverless/serverless#11865]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Github actions is failing to deploy;

The plugin is listed in the plugin section as well as in the package.json. However it always deploy successfully from my local environment, it only fails in github actions.

This is the github actions I am using:
--------------------
name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: serverless deploy --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLS_DEBUG: 1 

### Service configuration (serverless.yml) content

```yaml
const serverlessConfiguration = {
  service: "infra",
  frameworkVersion: "3",
  plugins: ["serverless-esbuild"],
  provider: {
    name: "aws",
    runtime: "nodejs14.x",
    stage: "${opt:stage, 'dev'}",
    region: "us-east-1",
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1",
      NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000",
    },
  },
  // import the function via paths
  package: { individually: true },
  resources: {
    Outputs: {
      region: { Value: "${self:provider.region}" },
      websiteBucket: { Value: "${self:custom.websiteBucket}" }
    },
  },
  custom: {
    websiteBucket: "${self:provider.stage}-${self:service}-website-bucket-97971",
    domain: "compose-test",
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ["aws-sdk"],
      target: "node14",
      define: { "require.resolve": undefined },
      platform: "node",
      concurrency: 10,
    },
  }
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

serverless deploy

### Command output

```shell
Deploying to stage dev
infra › waiting
backend_auction_services › waiting
frontend › waiting
infra › deploying
infra › Running "serverless deploy --stage dev"
infra › Running "serverless" from node_modules
infra › Environment: linux, node 16.19.1, framework 3.29.0 (local) 3.29.0v (global), plugin 6.2.3, SDK 4.3.2
infra › Docs:        docs.serverless.com
infra › Support:     forum.serverless.com
infra › Bugs:        github.com/serverless/serverless/issues
infra › Error:
infra › Serverless plugin "serverless-esbuild" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-esbuild" to install it.
infra › error
infra › Error:
infra › Serverless plugin "serverless-esbuild" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-esbuild" to install it.
infra › 
backend_auction_services › skipped
frontend › skipped
```

### Environment information

```shell
Run serverless --version
Running "serverless" from node_modules
Framework Core: 3.29.0 (local) 3.29.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
