### ISSUE TITLE
external websocket authorizers are broken in release v3.29.0

### ISSUE THREAD

**Issue by JamesKyburz** [serverless/serverless#11867]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Commit [16dd286a1](https://github.com/serverless/serverless/commit/16dd286a1d8aa764003565bcd6d7334be290e9bf) changed the file [lib/plugins/aws/package/compile/events/websockets/lib/authorizers.js](https://github.com/serverless/serverless/blob/16dd286a1d8aa764003565bcd6d7334be290e9bf/lib/plugins/aws/package/compile/events/websockets/lib/authorizers.js) to only accept a function authorizer present in the current cloudformation stack.

When the authorizer is external resolving the functionObject crashes because the function doesn't exist.

### Service configuration (serverless.yml) content

```yaml
connections:
  handler: some-path
  runtime: nodejs18.x
  architecture: arm64
  events:
    - websocket:
        route: $connect
        authorizer:
          arn: some-arn
          identitySource:
            - 'route.request.header.cookie'
    - websocket:
        route: $disconnect
```

### Command name and used flags

serverless package

### Command output

```shell
Error:
Function "auth" doesn't exist in this Service
```

### Environment information

```shell
Framework Core: 3.29.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
