### ISSUE TITLE
Add support for AWS Batch Ephmeral Storage on AWS Fargate

### ISSUE THREAD

**Issue by joeyparis** [serverless/serverless#11873]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

https://aws.amazon.com/about-aws/whats-new/2023/03/aws-batch-configurable-ephemeral-storage-fargate/

> AWS Batch now enables you to configure ephemeral storage up to 200 GiB in size on AWS Fargate type jobs. This means that you can expand the available ephemeral storage beyond the default value of 20 GiB for your jobs when using Fargate as the compute platform on AWS Batch. [[...]](https://aws.amazon.com/about-aws/whats-new/2023/03/aws-batch-configurable-ephemeral-storage-fargate/)

### Proposed solution (optional)

Under the `ContainerProperties` attribute for resource type `AWS::Batch::JobDefinition` allow for the ephemeral storage value to be set with the following syntax to match the corresponding job definition configuration JSON.

```
ContainerProperties:
    ...
    EphemeralStorage:
        SizeInGiB: <numeric_value>
PlatformCapabilities:
    - FARGATE
```

**Note** Only Fargate job definitions support the ephemeral storage parameter.

**Comment by medikoo** [comment]
@joeyparis thanks for opening. Still Framework currently doesn't create `AWS::Batch::JobDefinition` resources in any of its functionalities. How do you think this feature should be adopted? Does it apply to any of the core events?

**Comment by joeyparis** [comment]
I disagree. I am able to have serverless create an `AWS::Batch::JobDefinition` by adding the following to my `serverless.yml` file. The only part it doesn't seem to do is let me define the ephemeral storage size. But perhaps I misunderstand how serverless Framework actually interacts with the AWS API.

```
resources:
  Resources:
    myBatchJobDefinition:
        Type: AWS::Batch::JobDefinition
        Properties:
          Type: container
          JobDefinitionName: my_job_name
          ContainerProperties:
            Image: !Sub ${self:custom.account_id}.dkr.ecr.${self:provider.region}.amazonaws.com/my_docker_image:latest
            FargatePlatformConfiguration:
              PlatformVersion: LATEST
            # EphemeralStorage:
            #   SizeInGiB: 200
            ResourceRequirements:
              - Value: 2.0
                Type: VCPU
              - Value: 4096
                Type: MEMORY
            JobRoleArn: arn:aws:iam::XXXXXXXXXXXX:role/ecsTaskExecutionRole
            ExecutionRoleArn: arn:aws:iam::XXXXXXXXXXXX:role/ecsTaskExecutionRole
          PlatformCapabilities:
          - FARGATE
          RetryStrategy:
            Attempts: 1
```

This excerpt does successfully create a job definition in the AWS console for me, I just have to manually set the ephemeral storage via a redefinition. Which thankfully the other resources treat as if they were also generated by serverless, although that's not a safe long term solution. Let me know if I can provide any more information!
