### ISSUE TITLE
functions.[function-name].package.patterns doesn't work as desired

### ISSUE THREAD

**Issue by vighnesh153** [serverless/serverless#11879]
### Are you certain it's a bug?

- [x] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have the following configuration for a function and I only want to package the `dist` directory.

```yml
functions:
  api:
    package:
      patterns:
        - '!./**'
        - dist/**
    handler: dist/index.handler
    events:
      - httpApi: '*'
```

But, it packages the entire root directory instead. 

However, if I move the `package.patterns` to the top level instead of inside of a function scope, it works as expected

```yml
package:
  patterns:
    - '!./**'
    - dist/**
```

### Service configuration (serverless.yml) content

```yaml
service: my-service
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  deploymentMethod: direct
  httpApi:
    cors: true
  logRetentionInDays: 7
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 2
  versionFunctions: false

functions:
  api:
    package:
      patterns:
        - '!./**'
        - dist/**
    handler: dist/index.handler
    events:
      - httpApi: '*'
```

### Command name and used flags

```shell
serverless deploy
```

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.29.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
