### ISSUE TITLE
Cannot set multiple key-value for an alb event "query" with the same key

### ISSUE THREAD

**Issue by Inqnuam** [serverless/serverless#11880]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

AWS Application Load Balancer listener rule allows to set multiple values for a single query key.
<img width="499" alt="Screenshot 2023-04-01 at 13 54 16" src="https://user-images.githubusercontent.com/69360379/229287229-fbc79d20-f5e5-4e69-91ea-7438645ac2a7.png">
<img width="500" alt="Screenshot 2023-04-01 at 13 54 28" src="https://user-images.githubusercontent.com/69360379/229287236-9c857613-dec2-43c5-99c9-612336603387.png">

Currently this is not possible with Serverless Framework as query "value" is defined as string.

### Service configuration (serverless.yml) content

```yaml
service: sls-project

frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  region: eu-west-3
  vpc:
    subnetIds: [subnet-0e2db7f9558f501d7, subnet-0cde9f3600cab039a]
    securityGroupIds: [sg-029d2fbba38db2dc7]

functions:
  lambda:
    handler: src/handlers/lambda.default
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:xxxx
          priority: 936
          conditions:
            path: "/users"
            method: [GET]
            query:
              role: admin
              role: guest
```

### Command name and used flags

"N/A

### Command output

```shell
"N/A
```

### Environment information

```shell
Framework Core: 3.29.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
