### ISSUE TITLE
ALB event conditions combined values length must not exceed 5

### ISSUE THREAD

**Issue by Inqnuam** [serverless/serverless#11882]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

As we can see in AWS [Quotas for your Application Load Balancers](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html), alb event conditions combined values length must not exceed 5.
Currently this isn't verified when packaging. Only conditions length is verified.

### Service configuration (serverless.yml) content

```yaml
service: sls-project

frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  region: eu-west-3
  vpc:
    subnetIds: [subnet-0e2db7f9558f501d7, subnet-0cde9f3600cab039a]
    securityGroupIds: [sg-029d2fbba38db2dc7]

functions:
  lambda:
    handler: src/handlers/lambda.default
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:xxxx
          priority: 936
          conditions:
            path: ["/users", "/members"]
            method: [GET, POST, DELETE, PUT]
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.29.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@Inqnuam thanks for reporting.

If possible we should restrict this purely at schema. PR's welcome!

**Comment by Inqnuam** [comment]
> If possible we should restrict this purely at schema.

I'm not an expert with AJV but I don't think this can be done only at schema level!

**Comment by medikoo** [comment]
@Inqnuam I think this may work: https://ajv.js.org/json-schema.html#maxitems-minitems

**Comment by reshab48** [comment]
@medikoo I am just getting started to understand the project, I'm not an expert in AJV but the link you provided for `maxItems` is an attribute only for type `array` and `conditions` is of type `object`, please correct me if I am wrong.

**Comment by medikoo** [comment]
@reshab48 that's a very good point. I missed that.

Indeed in such case, we can validate that manually in code.

**Comment by Inqnuam** [comment]
@medikoo @reshab48 
Unfortunately it is not about a simple array length or Object.keys length
Here's how we reach the limit
```yaml
functions:
  lambda:
    handler: src/handlers/lambda.default
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:xxxx
          priority: 936
          conditions:
            path: ["/users", "/members"] # 2
            method: [GET, POST, DELETE, PUT] # 4
            # 2 + 4 > 5
```
another one
```yaml
functions:
  lambda:
    handler: src/handlers/lambda.default
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:xxxx
          priority: 936
          conditions:
            path: ["/users", "/members", "/players", "/hello", "world"] # 5
            # so we can't add any other value in "path" or elsewhere anymore
```

another one
```yaml
functions:
  lambda:
    handler: src/handlers/lambda.default
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:xxxx
          priority: 936
          conditions:
            ip:
              - 192.168.0.1/0 # 1
            path: ["/users"] # 1
            method: GET # 1
            header:
              name: Content-Type
              values: ["application/json", "application/xml"] # 2
            # here again alb conditions values limit is reached as 1 + 1 + 1 + 2 = 5
```

I already prepared a PR which will manually check all theses cases. 
But this issue should remain open until we close #11880 and #11884
