### ISSUE TITLE
Wrong ALB event ip condition validation

### ISSUE THREAD

**Issue by Inqnuam** [serverless/serverless#11883]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

CIDR blocs are required inside alb event's ip IPv4 and IPv6 declaration.

<img width="494" alt="Screenshot 2023-04-01 at 23 57 11" src="https://user-images.githubusercontent.com/69360379/229315845-95cd2a02-618d-4828-9eb8-0b40d03b3e08.png">

Currently Serverless schema validator prints a warning message when we include CIDR into ip declaration.

### Service configuration (serverless.yml) content

```yaml
service: sls-project

frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  region: eu-west-3
  vpc:
    subnetIds: [subnet-0e2db7f9558f501d7, subnet-0cde9f3600cab039a]
    securityGroupIds: [sg-029d2fbba38db2dc7]

functions:
  lambda:
    handler: src/handlers/lambda.default
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:xxxx
          priority: 936
          conditions:
            path: "/users"
            method: GET
            ip:
              - fe80:0000:0000:0000:0204:61ff:fe9d:f156/6
              - 192.168.0.1/0
```

### Command name and used flags

serverless package

### Command output

```shell
Warning: Invalid configuration encountered
  at 'functions.lambda.events.0.alb.conditions.ip.0': unsupported string format
  at 'functions.lambda.events.0.alb.conditions.ip.1': unsupported string format

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Framework Core: 3.29.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
