### ISSUE TITLE
Cannot set multiple key-value for an alb event conditions "header"

### ISSUE THREAD

**Issue by Inqnuam** [serverless/serverless#11884]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

AWS Application Load Balancer listener rule allows to set multiple http-header key-value.
<img width="493" alt="Screenshot 2023-04-02 at 14 48 43" src="https://user-images.githubusercontent.com/69360379/229354040-e41b3d6d-4e5e-472f-8745-a847a6a44c51.png">
Currently this isn't possible with Serverless Framework as "header" is an object which accepts only a "name" and "values"

### Service configuration (serverless.yml) content

```yaml
service: sls-project

frameworkVersion: "3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  region: eu-west-3
  vpc:
    subnetIds: [subnet-0e2db7f9558f501d7, subnet-0cde9f3600cab039a]
    securityGroupIds: [sg-029d2fbba38db2dc7]

functions:
  lambda:
    handler: src/handlers/lambda.default
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:xxxx
          priority: 936
          conditions:
            path: "/users"
            method: [GET]
            header:
              name: Content-Type
              values:
                - application/json
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.29.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
