### ISSUE TITLE
sls deploy function -f command is detaching layer from existing Lambda

### ISSUE THREAD

**Issue by steveballardttt** [serverless/serverless#11914]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When using `sls deploy function -f postsHandler` to update an existing function (with layer attached) the layer is being REMOVED from the Lambda. 

As a possible related side note, when I make changes to the postsHandler js file, sometimes it doesn't detect that there are changes and it won't deploy. 

### Service configuration (serverless.yml) content

```yaml
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  vpc:
    securityGroupIds: !Split
      - ','
      - ${param:securityGroupIds, ""}
    subnetIds: !Split
      - ','
      - ${param:subnetIds, ""}
  # stackName: ${self:service}-${param:envName}
  environment:
    REGION: ${self:provider.region}
    STAGE: ${sls:stage}
    ENV_TYPE: ${param:envType}
    S3_BUCKET_NAME: ${param:mediaBucketName, ""}
    S3_URL_EXPIRE_IN_SECONDS: 3600
    SQS_QUEUE_URL: ${param:notificationQueueUrl, ""}
  layers:
    - ${param:servicesSharedUtilsLayerArn}
  httpApi:
    id: ${param:apiGatewayId, ""}
  iam:
    role:
      name: ${self:service}-${sls:stage}-lambda-role
      statements:
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
            - 's3:GetObject'
            - 's3:GetObjectAcl'
            - 'sqs:SendMessage'
          Resource:
            - '*'

# params: *redacted*

functions:
  postsHandler:
    handler: ./controllers/handlerController.handler
    events:
      # indexPosts
      - httpApi:
          path: /v2/posts
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexActivismPosts
      - httpApi:
          path: /v2/posts/activism
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexMobilePosts
      - httpApi:
          path: /v2/posts/mobile
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexDraftPosts
      - httpApi:
          path: /v2/posts/drafts
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # show
      - httpApi:
          path: /v2/posts/{id}
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # showThread:
      - httpApi:
          path: /v2/posts/{id}/thread
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexPostLocations:
      - httpApi:
          path: /v2/posts/locations
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # create:
      - httpApi:
          path: /v2/posts
          method: POST
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # createUpdate:
      - httpApi:
          path: /v2/posts/{id}
          method: POST
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # update:
      - httpApi:
          path: /v2/posts/{id}
          method: PUT
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # delete:
      - httpApi:
          path: /v2/posts/{id}
          method: DELETE
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexBookmarks:
      - httpApi:
          path: /v2/posts/bookmarks
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # createBookmark:
      - httpApi:
          path: /v2/posts/bookmarks
          method: POST
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # deleteBookmark:
      - httpApi:
          path: /v2/posts/bookmarks/{id}
          method: DELETE
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexLocationsByUser:
      - httpApi:
          path: /v2/locations
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexStaff:
      - httpApi:
          path: /v2/posts/staff
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer
      # indexBookmarkLocations:
      - httpApi:
          path: /v2/posts/bookmarks/locations
          method: GET
          authorizer:
            type: jwt
            id: ${param:jwtAuthorizerId}
            name: cognitoAuthorizer

custom:
  stage: ${sls:stage}
  plugins:
    local:
      - serverless-offline
  serverless-offline:
    httpPort: 6000
    websocketPort: 6001
    lambdaPort: 6002
    ignoreJWTSignature: true
    noAuth: true

plugins: ${self:custom.plugins.${sls:stage}, ""}
```

### Command name and used flags

serverless deploy function -f 

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.30.1 (local) 3.30.1 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
