### ISSUE TITLE
Add provisionedConcurrency broken lambda in AWS console

### ISSUE THREAD

**Issue by mohammad1990** [serverless/serverless#11932]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I am deploying using serverless v3 lambda URL but when I add **_provisionedConcurrency_** it breaks the AWS console.
and I can't find anything in serverless lambda Doc about adding _provisionedConcurrency_ to **_lambda URL._** 
when I remove provisionedConcurrency I can see the link in the AWS console. 

<img width="1323" alt="Screen Shot 2023-04-20 at 17 26 15" src="https://user-images.githubusercontent.com/7848562/233414462-663db166-6870-40d0-8fbc-e6cbdd1c48f6.png">

And it added provisionedConcurrency ==> 3  to lambda URL correctly. 

<img width="1081" alt="Screen Shot 2023-04-20 at 17 34 07" src="https://user-images.githubusercontent.com/7848562/233416278-7cf681fd-d74b-4657-b409-7ad6185fa6fc.png">

### Service configuration (serverless.yml) content

```yaml
functions: 
 variantStockState:
    handler: src/serverless/handler.test
    timeout: 30
    url:
      cors: true
    provisionedConcurrency: 2
```

### Command name and used flags

sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```
