### ISSUE TITLE
Error: this.provider.naming.getLambdaFunctionUrlOutputLogicalId is not a function

### ISSUE THREAD

**Issue by suryanarayana** [serverless/serverless#11933]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

**Error:** this.provider.naming.getLambdaFunctionUrlOutputLogicalId is not a function
**File:** lib\plugins\aws\info\get-stack-info.js
![image](https://user-images.githubusercontent.com/1782220/233546367-df5b1232-c9ec-479f-a028-16be2f1b455d.png)
**These are the dev dependencies that we are using:**
 

### Service configuration (serverless.yml) content

```yaml
serverless.yml
plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-apigateway-service-proxy

package.json
"devDependencies": {
    "lodash": "^4.17.21",
    "serverless": "^3.27.0",
    "serverless-apigateway-service-proxy": "^2.2.0",
    "serverless-domain-manager": "^3.3.1",
    "serverless-pseudo-parameters": "^2.5.0",
    "serverless-python-requirements": "^5.4.0"
  }
```

### Command name and used flags

SLS_DEBUG=* AWS_REGION='us-east-1' AWS_PROFILE=local-user sls deploy --stage local --loglevel DEBUG

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 1.72.0
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
