### ISSUE TITLE
EventBridge event doesn't point to version/alias of provisionedConcurrency Lambda

### ISSUE THREAD

**Issue by deasydoesit** [serverless/serverless#11949]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a Lambda function, `myFunc`, which has been given `provisionedConcurrency` and is invoked asynchronously via an EventBridge event.

However, while a new version with the alias `provisioned` gets created for `myFunc`, the ARN of the EventBridge event doesn't point to the Qualified ARN for the alias (e.g., `arn:aws:lambda:aws-region:acct-id:function:myFunc:provisioned`) or version (e.g., `arn:aws:lambda:aws-region:acct-id:function:myFunc:42`), and instead points to the Unqualified ARN (e.g., `arn:aws:lambda:aws-region:acct-id:function:myFunc`).

Accordingly, the provisioned lambdas do not get utilized. 

### Service configuration (serverless.yml) content

```yaml
functions:
  myFunc:
    handler: src/index.handler
    environment:
      DEST_BUCKET: ${self:custom.DEST_BUCKET}
      REGION: ${env:REGION}
    timeout: 15
    logRetentionInDays: 30
    provisionedConcurrency: 10
    reservedConcurrency: 50
    name: myFunc
    description: Replicates S3 objects between buckets
    role: arn:aws:iam::${aws:accountId}:role/myFuncRole
    vpc:
      securityGroupIds:
        - ${ssm:/vpc/s3_replicator_lambda_security_group_id}
      subnetIds:
        - ${ssm:/vpc/private_subnet_id_a}
        - ${ssm:/vpc/private_subnet_id_b}
    maximumRetryAttempts: 2
    maximumEventAge: 21600
    onError: ${ssm:/sqs/dlq_arn}
    events:
      - eventBridge:
          pattern:
            source:
              - "aws.s3"
            detail-type:
              - "Object Created"
            detail:
              bucket:
                name: ${ssm:/s3/bucket_names}
          retryPolicy:
            maximumEventAge: 86400
            maximumRetryAttempts: 185
          deadLetterQueueArn: ${ssm:/sqs/dlq_arn}
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.27.0
Plugin: 6.2.3
SDK: 4.3.2
```
