### ISSUE TITLE
EventBridge Pattern validation does not allow more advanced patterns

### ISSUE THREAD

**Issue by webdestroya** [serverless/serverless#11951]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Using this event pattern:

```
myFunction:
  # ...
  events:
    - eventBridge:
        pattern:
          "$or":
            - source:
                - aws.ecs
              detail-type:
                - ECS Service Action
                - ECS Task State Change
                - ECS Container Instance State Change
                - ECS Deployment State Change
            
            - source:
                - aws.rds
              detail-type:
                - RDS DB Cluster Event
                - RDS DB Instance Event

            - source:
                - aws.ec2
              detail-type:
                - EC2 Spot Instance Interruption Warning
```

Causes this error to be thrown:

```Warning: Invalid configuration encountered
  at 'functions.myFunction.events.0.eventBridge.pattern': unrecognized property '$or'
```

If I ignore this warning, everything works fine. This is a perfectly valid event pattern

### Service configuration (serverless.yml) content

```yaml
Relevant section from my `functions` block


myFunction:
  # ...
  events:
    - eventBridge:
        pattern:
          "$or":
            - source:
                - aws.ecs
              detail-type:
                - ECS Service Action
                - ECS Task State Change
                - ECS Container Instance State Change
                - ECS Deployment State Change
            
            - source:
                - aws.rds
              detail-type:
                - RDS DB Cluster Event
                - RDS DB Instance Event

            - source:
                - aws.ec2
              detail-type:
                - EC2 Spot Instance Interruption Warning
```

### Command name and used flags

serverless package

### Command output

```shell
Warning: Invalid configuration encountered
  at 'functions.myFunction.events.0.eventBridge.pattern': unrecognized property '$or'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Framework Core: 3.30.1 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
