### ISSUE TITLE
Allows specification of an AuthorizerCredentials(Arn) for both HTTP and REST APIs

### ISSUE THREAD

**Issue by lholota** [serverless/serverless#11959]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Both types of API gateway allow specifying in IAM role which is used to execute the authorizer:
- AWS::ApiGateway::Authorizer -> AuthorizerCredentials
- AWS::ApiGatewayV2::Authorizer -> AuthorizerCredentialsArn

This is important when using an authorizer from another AWS account where you must create a role allowing the execution of the underlying lambda which is used for the authorizer.

If I'm missing something and there is a way around I would be really glad to find out, we have several teams currently keen on using an authorizer shared across the whole company from one AWS account and they unfortunately can't because of this issue.

### Proposed solution (optional)

Add property under:
...../events/*/httpApi/authorizer/authorizer_credentials
...../events/*/http/authorizer/authorizer_credentials
provider/httpApi/authorizers/*/authorizer_credentials

which would map to the corresponding CloudFormation properties based on the API type.

**Comment by medikoo** [comment]
@lholota thanks for openning that issue. PR is welcome, but let's first agree how we will include it in the configuration (please post a proposal)

**Comment by lholota** [comment]
Hi @medikoo, as I hinted above, I would suggest adding it as follows:

## HTTP API (Gateway V2)
```yaml
provider:
  httpApi:
    authorizers:
      customAuthorizer:
        # ...
        authorizerCredentials: # Role ARN
           GetAtt: [MyRole, Arn] # Referencing a role created in the resources section
```
## REST API (Gateway V1)

```yaml
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          # ...
          authorizer:
            name: authorizerFunc
             # ...
            authorizerCredentials: # Role ARN
               GetAtt: [MyRole, Arn] # Referencing a role created in the resources section
  authorizerFunc:
    handler: handler.authorizerFunc
```

Both V1 and V2 gateways have the same property (although it has a slightly different name in each it takes the same value).
