### ISSUE TITLE
How to deploy lambda code individualy on aws console?

### ISSUE THREAD

**Issue by Satyam8891** [serverless/serverless#11950]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Maybe I am doing something wrong because while deploying python lambda, it zip all the code and deployed for all the lambdas.
Example- let's suppose I have 3 lambda A, B and C. First time, I have to deploy all together that's fine but when I check on aws console then every lambda has all the code that means A has handler functions those are specific for b and c lambda.
even for each lambda I have separate file

### Service configuration (serverless.yml) content

```yaml
frameworkVersion: '3'

package:
  individually: True
  exclude:
    - package-lock.json
    - package.json
    - node_modules/**

provider:
  name: aws
  runtime: python3.8
  region: eu-west-2



  name: relay_calculation
  handler: relay_calculation/relay_calculator.handler
  memorySize: 10240
  timeout: 900
  role: "arn:aws:iam::*****:role/momentsnap-ratings-importer-role"
```

### Command name and used flags

"N/A"

### Command output

```shell
"N/A"
```

### Environment information

```shell
Framework Core: 3.24.1
Plugin: 6.2.2
SDK: 4.3.2
```
