### ISSUE TITLE
Migrating EventBridge events from custom resources to cloudformation fails

### ISSUE THREAD

**Issue by tie624** [serverless/serverless#11970]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When migrating from an EventBridge event that was provisioned using custom resources to an EventBridge event provisioned using CloudFormation. The same name is being used and it's complaining that it already exists. Using a different naming convention for custom resources should solve this issue.

Original serverless.yml

```yaml
service: sample-service

provider:
  name: aws
  runtime: nodejs18.x
  eventBridge:
    useCloudFormation: false

functions:
  function1:
    handler: index.handler
    events:
      - eventBridge:
          pattern:
            detail-type:
              - SAMPLE_EVENT
```

### Service configuration (serverless.yml) content

```yaml
service: sample-service

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - eventBridge:
          pattern:
            detail-type:
              - SAMPLE_EVENT
```

### Command name and used flags

sls deploy

### Command output

```shell
Deploying sample-service to stage dev (us-east-1)

✖ Stack sample-service-dev failed to deploy (25s)
Environment: darwin, node 18.15.0, framework 3.30.1 (local), plugin 6.2.3, SDK 4.3.2
Credentials: Local, "tie" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: Sampleservicedevfunction1rule1EventBridgeRule (AWS::Events::Rule)
sample-service-dev-function1-rule-1 already exists
```

### Environment information

```shell
Framework Core: 3.30.1 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
