### ISSUE TITLE
Lambda Trigger Not Adding Path From HTTP API (API Gateway v2)

### ISSUE THREAD

**Issue by Ryan-og** [serverless/serverless#11986]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have found a bug where Serverless is not adding the path to the trigger endpoint on the Lambda after deploying. It just creates a trigger with the default endpoint even though the route is created on the api gateway and the integration is linked to the lambda. The manual workaround seems to be detaching and re-attaching the integration on the Http API Gateway in AWS console. This issue does not happen when I run the same code for a Rest gateway.

### Service configuration (serverless.yml) content

```yaml
---
service: Serverless-foobar

frameworkVersion: "3.31.0"

package:
  individually: true	

provider:
  name: aws
  deploymentMethod: direct
  runtimeManagement: auto
  stage: ${opt:stage}
  region: foo
  memorySize: 1024
  timeout: 30
  apiName: ${self:service}
  apiGateway:
    description: HTTP API ${self:service}
    metrics: true
  environment:
    S3_REGION: foo
    TOKEN_EXPIRATION_TIME_MINUTES: 60
    TOKEN_GENERATION_MAX_RETRIES: 3
  iam:
    role: foo
  httpApi:
    metrics: true


plugins:
  - serverless-vpc-discovery
  - serverless-plugin-datadog

custom:

  datadog:
    site: foo
    apiKey: bar

  vpcDiscovery:
    vpcName: ${param:vpc}
    subnets:
      - tagKey: Name
        tagValues:
          - "${param:subnet}"

    securityGroups:
      - tagKey: Name
        tagValues:
          - "${param:securitygroup}"

functions: ${file(functions.yml):functions}



Functions.yml below:

---
functions:
           
  foo1:
    handler: src/foo1/handler.lambda_handler
    runtime: python3.8
    environment:
      foo: "bar"
      foo: "bar"
      foo: "bar"
      foo: "bar"
      foo: "bar"
    events:
       - httpApi:
           method: POST
           path: /foo/bar
          
  foo2:
    handler: src/foo2/bar/handler.lambda_handler
    runtime: python3.9
    environment:
      foo: "bar"
      foo: "bar"

    events:
      - httpApi:
          method: get
          path: /foo2/bar	
          authorizer:
            type: aws_iam
          
  foo3:
    handler: src/foo3/handler.lambda_handler
    runtime: python3.9
    environment:
      foo: "bar"
      foo: "bar"
      foo: "bar"
      foo: "bar"
      foo: "bar"
      foo: "bar"
      foo: "bar"

    events:
      - httpApi: 'POST /foo3/bar'

  foo4:
    handler: src/foo4/handler.lambda_handler
    runtime: python3.9
    environment:
      foo: "bar"
      foo: "bar"
      foo: "bar"

    events:
      - httpApi:
          method: POST
          path: /foo4/bar
```

### Command name and used flags

npx serverless deploy -s test --param="vpcname=foo-bar"

### Command output

```shell
N/A
```

### Environment information

```shell
serverless --version                                                               
Running "serverless" from node_modules
Framework Core: 3.31.0 (local) 3.28.1 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
