### ISSUE TITLE
GCF 2nd Generation

### ISSUE THREAD

**Issue by satya-500** [serverless/serverless#11983]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

wanted to deploy google cloud function [2nd generation](https://cloud.google.com/blog/products/serverless/cloud-functions-2nd-generation-now-generally-available) 

### Proposed solution (optional)

```yaml
service: test

provider:
  name: google
  stage: dev
  runtime: python310
  region: us-central1
  project: heisenberg
  credentials: secret.json
  generation: "2nd"  # <------------------------ second generation
```
