### ISSUE TITLE
Serverless does not allow references to own resources in `ResponseHeadersPolicyId` CloudFront behaviour property.

### ISSUE THREAD

**Issue by antoniogomezm** [serverless/serverless#11993]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless complains when setting a reference to a `ResponseHeadersPolicy` object in the resources section on the  `ResponseHeadersPolicyId` field.

It looks like the schema for CloudFront events [events/cloud-front.js] the filed is defined as `type: 'string'` instead of `anyOf: [{ type: 'string' }, { $ref: '#/definitions/awsCfFunction' }]`

https://github.com/serverless/serverless/blob/f2d1e23f591a8cae2d41a93ca476b135dfcdac68/lib/plugins/aws/package/compile/events/cloud-front.js#L133

### Service configuration (serverless.yml) content

```yaml
ResponseHeadersPolicyId:
   Ref: CustomResponseHeaderPolicy

resources:
  Resources:
    CustomResponseHeaderPolicy:
      Type: AWS::CloudFront::ResponseHeadersPolicy
```

### Command name and used flags

serverless deploy

### Command output

```shell
$ serverless deploy
Error:
Configuration error at 'functions.lambda-edge.events.0.cloudFront.behavior.ResponseHeadersPolicyId': must be string
```

### Environment information

```shell
Framework Core: 3.31.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
