### ISSUE TITLE
Generate AWS::ApiGateway::ApiKey with custom resource name

### ISSUE THREAD

**Issue by axot** [serverless/serverless#12010]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Consider following definition.

```
service: my-service
provider:
  name: aws
  apiGateway:
    apiKeys:
      - name: firstKey
      - name: secondKey
```

The existing generation logic will trigger the regeneration of the `secondKey` when the `firstKey` is deleted.

### Proposed solution (optional)

Instead using array, key value structure works better.
```
service: my-service
provider:
  name: aws
  apiGateway:
    apiKeys:
      firstKey:
        name: firstKey
      secondKey:
        name: secondKey
```
