### ISSUE TITLE
Inconsistent Lambda Layer Naming Logic

### ISSUE THREAD

**Issue by bojanraic** [serverless/serverless#12011]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

It seems that Lambda Layer naming logic is inconsistent. 
Say I wish to build a layer where the name contains version information to keep track of external dependency version that went into the layer. 

Now, I know that `The layer name can contain only letters, numbers, hyphens, and underscores.`. However, if I still set version as `1.0`, serverless seems to strip it to just `1`, or `mylayer-1`, which is kind of misleading.

I say misleading, because if I set version as `1.1`, or `1.3`, then it fails, because naming is rightfully not valid. 

So I suppose to be more consistent, perhaps consider either throwing an error for cases such as `1.0`, or simply replace invalid chars with underscores or hyphens, which are valid, as long as this is documented. 

Examples:
- When the layer name contains a version-like pattern specified as `1.0`, the generated CFN Template has it set to: `"LayerName": "mylayer_1_arm64"` 
- When specifying a different value, such as `1.3.2` via `sls package --param='layer-version=1.43.2'`, it rightfully complains: 
```
Error:
Configuration error at 'layers.mylayer.name': must match pattern "^((arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+)|[a-zA-Z0-9-_]+)$"
```

  

### Service configuration (serverless.yml) content

```yaml
service: layer-naming
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs18.x
  architecture: arm64

layers:
  mylayer:
    path: ./layer/
    name: mylayer_${self:custom.layer-version}_${self:provider.architecture}
    description: 'My Lambda Layer version ${self:custom.layer-version} for ${self:provider.architecture}'

custom:
  layer-version: ${param:layer-version, 1.0}
```

### Command name and used flags

sls package --param='layer-version=1.1'

### Command output

```shell
Environment: darwin, node 20.2.0, framework 3.32.2, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Configuration error at 'layers.mylayer.name': must match pattern "^((arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+)|[a-zA-Z0-9-_]+)$"

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Framework Core: 3.32.2
Plugin: 6.2.3
SDK: 4.3.2
```
