### ISSUE TITLE
Acess ECR URI Natively

### ISSUE THREAD

**Issue by felipegenef** [serverless/serverless#12018]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Hey guys, I have a project where I created an ECR and a TaskDefinition for AWS FARGATE on my resources tab, but I had to deploy an aws function with my container image to have access to my URI. It would be nice if we could deploy and access something like "${self:provider.ecr.images.imageName.uri}" to get the deployed container URI or simply have imageName as the URI value as default (Similar behaviour from lambda images). This way we would be able to "!Ref" it on the resources tab.

### Proposed solution (optional)

# EX1:
```yaml
service: fargate-test
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  ecr:
    images:
      imageName:
        path: ./containerFolder
  resources:
    Resources:
      EcsCluster:
        Type: AWS::ECS::Cluster
        Properties:
          ClusterName: ${self:service}-cluster
      TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
          RequiresCompatibilities:
            - FARGATE
          Cpu:  250
          Memory: 500
          ContainerDefinitions:
            - Name: container-name
              Image: ${self:custom.ecr.images.imageName.uri}
```
# EX2:
```yaml
service: fargate-test
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  ecr:
    images:
      imageName:
        path: ./containerFolder
  resources:
    Resources:
      EcsCluster:
        Type: AWS::ECS::Cluster
        Properties:
          ClusterName: ${self:service}-cluster
      TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
          RequiresCompatibilities:
            - FARGATE
          Cpu:  250
          Memory: 500
          ContainerDefinitions:
            - Name: container-name
              Image: imageName
        ```
