### ISSUE TITLE
The supported syntaxes for `function.events.stream.arn` are too restrictive

### ISSUE THREAD

**Issue by Woodz** [serverless/serverless#12026]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When defining a Lambda that is triggered by a DDB event stream, the ARN field has very specific restrictions that are not documented and severely limit the functionality of this field.

Specifically, the value of `arn` field can only support the following syntaxes:
1. The hardcoded ARN
1. `Fn::GetAtt` where the first parameter is a hardcoded string
1. `Fn::ImportValue` where the parameter is a harcoded string
1. `ref` where the parameter is a harcoded string
1. `Fn::Join` where the parameters are hardcoded strings

This is based on the logic in https://github.com/serverless/serverless/blob/17d64e6c94b88a5daf36f28a4fa192c231052cfb/lib/plugins/aws/package/compile/events/stream.js#L191C15-L213 which handles only these specific cases before calling `getStreamLogicalId` which requires the parsed `streamName` to be a string

This does not work for more complex scenarios, e.g.
```
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          arn:
            Fn::ImportValue:
              !Join [ ':', [ !Ref StreamStackName, !Ref StreamArnExportSuffix ] ]
```

which fails with 
```
TypeError: name.replace is not a function
    at Object.normalizeNameToAlphaNumericOnly (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
    at Object.getStreamLogicalId (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/lib/naming.js:391:14)
    at /Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:209:58
    at Array.forEach (<anonymous>)
    at /Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:167:28
    at Array.forEach (<anonymous>)
    at AwsCompileStreamEvents.compileStreamEvents (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:117:47)
    at package:compileEvents (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:33:49)
    at PluginManager.runHooks (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at async PluginManager.invoke (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:564:9)
    at async PluginManager.spawn (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/deploy.js:40:11)
    at async PluginManager.runHooks (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/serverless.js:179:5)
    at async /Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/scripts/serverless.js:834:9
```

I strongly recommend that as a short-term workaround, this limitation is documented and a useful error message is shown if an unsupported usage is detected. In the longer-term, I don't think it is sustainable to try to generate a logical resource name from a stream ARN field so would recommend considering alternatives, e.g. adding a LogicalName field or nesting the stream under an named object (as per functions)

### Service configuration (serverless.yml) content

```yaml
DDB serverless.yml:
-------------------

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TestTableName:
    Type: String

Resources:
  TestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TestTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      StreamSpecification:
        StreamViewType: OLD_IMAGE

Outputs:
  TestTableStreamArn:
    Value: !GetAtt TestTable.StreamArn
    Export:
      Name: !Sub "${AWS::StackName}-GetAtt:TestTable:StreamArn"
```

Lambda listener serverless.yml
----------
```
functions:
  testProcessor:
    handler: src/handler.handle
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          arn:
            Fn::ImportValue:
              !Join [ ':', [ !Ref StreamStackName, !Ref StreamArnExportSuffix ] ]
Parameters:
  StreamArnExportSuffix:
    Type: String
    Default: GetAtt:TestTable:StreamArn
  StreamStackName:
    Type: String
    Default: ${env:DDB_STACK_NAME}
```
```


### Command name and used flags

serverless deploy

### Command output

```shell
TypeError: name.replace is not a function
    at Object.normalizeNameToAlphaNumericOnly (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
    at Object.getStreamLogicalId (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/lib/naming.js:391:14)
    at /Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:209:58
    at Array.forEach (<anonymous>)
    at /Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:167:28
    at Array.forEach (<anonymous>)
    at AwsCompileStreamEvents.compileStreamEvents (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:117:47)
    at package:compileEvents (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/aws/package/compile/events/stream.js:33:49)
    at PluginManager.runHooks (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at async PluginManager.invoke (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:564:9)
    at async PluginManager.spawn (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:585:5)
    at async before:deploy:deploy (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/plugins/deploy.js:40:11)
    at async PluginManager.runHooks (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:530:9)
    at async PluginManager.invoke (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:563:9)
    at async PluginManager.run (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (/Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/lib/serverless.js:179:5)
    at async /Users/richardwise/src/cf-dda/data-analytics-reporting/node_modules/serverless/scripts/serverless.js:834:9
```
```


### Environment information

```shell
Framework Core: 3.32.2 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
