### ISSUE TITLE
AWS::Scheduler::Schedule events do not work with custom IAM Roles

### ISSUE THREAD

**Issue by bhb603** [serverless/serverless#12022]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When using the [AWS::Scheduler](https://www.serverless.com/framework/docs/providers/aws/events/schedule#use-awsschedulerschedule-instead-of-awseventrule) events, and the function has a custom IAM Role, the Cloudformation template is invalid.

### Service configuration (serverless.yml) content

```yaml
service: brians-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  rateHandler:
    role: MyRole
    handler: index.run
    events:
      - schedule:
          method: scheduler
          rate: rate(1 minute)
          timezone: America/New_York

resources:
  Resources:
    MyRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
```

### Command name and used flags

sls deploy

### Command output

```shell
✖ Stack brians-sls-dev failed to deploy (2s)
Environment: darwin, node 18.16.0, framework 3.32.2, plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource IamRoleLambdaExecution
```

### Environment information

```shell
Framework Core: 3.32.2
Plugin: 6.2.3
SDK: 4.3.2
```
