### ISSUE TITLE
Bug in environment variables which have dollar sign inside

### ISSUE THREAD

**Issue by ellenaua** [serverless/serverless#12047]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In serverless.yml we specify environment variables for Lambda function this way:

```
environment:
  POSTGRESQL_HOST: ${env:POSTGRESQL_HOST}
  POSTGRESQL_PORT: ${env:POSTGRESQL_PORT}
  POSTGRESQL_USERNAME: ${env:POSTGRESQL_USERNAME}
  POSTGRESQL_PASSWORD: ${env:POSTGRESQL_PASSWORD}
```

Problem is:
- if POSTGRESQL_PASSWORD contains a dollar sign (`$`) - a piece of part of password is disappearing and as a result that Lambda function cannot connect to the database

Use cases:

- if process.env.POSTGRESQL_PASSWORD is `abcdefghijk`
  - Lambda function after deploy has POSTGRESQL_PASSWORD is `abcdefghijk` (same)
- if process.env.POSTGRESQL_PASSWORD is `abcdefghij$`
  - Lambda function after deploy has POSTGRESQL_PASSWORD is `abcdefghij$` (same)
- if process.env.POSTGRESQL_PASSWORD is `ab$defghijk`
  - Lambda function after deploy has POSTGRESQL_PASSWORD is `ab` ($defghijk disappeared)
- if process.env.POSTGRESQL_PASSWORD is `ab$defgh@jk`
  - Lambda function after deploy has POSTGRESQL_PASSWORD is `ab@jk` ($defgh disappeared)
    
    

### Service configuration (serverless.yml) content

```yaml
frameworkVersion: '3'
service: some-service
useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: ${opt:stage}

  environment:
    POSTGRESQL_HOST: ${env:POSTGRESQL_HOST}
    POSTGRESQL_DATABASE: ${env:POSTGRESQL_DATABASE}
    POSTGRESQL_USERNAME: ${env:POSTGRESQL_USERNAME}
    POSTGRESQL_PASSWORD: ${env:POSTGRESQL_PASSWORD}

functions:
  main_event_handler:
    handler: src/main_event_handler.main_event_handler
    description: "Some Service - ${self:provider.stage}"
    timeout: 900
    memorySize: 3008
```

### Command name and used flags

sls print --stage development

### Command output

```shell
frameworkVersion: '3'
service: some-service
useDotenv: true
configValidationMode: error
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: development
  environment:
    POSTGRESQL_HOST: legacy-api-production-instance-1.cs7ml4k0cjya.us-east-1.rds.amazonaws.com
    POSTGRESQL_DATABASE: hp-production
    POSTGRESQL_USERNAME: legacy_db_user_202301
    POSTGRESQL_PASSWORD: ab@jk
  versionFunctions: true
functions:
  main_event_handler:
    handler: src/main_event_handler.main_event_handler
    description: Some Service - development
    timeout: 900
    memorySize: 3008
    events: []
    name: some-service-development-main_event_handler
```

### Environment information

```shell
Framework Core: 3.33.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
