### ISSUE TITLE
Error creating resource for request validator model in shared API Gateway

### ISSUE THREAD

**Issue by paolorossig** [serverless/serverless#12048]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I had problems creating a global/reusable request validator schema in `provider.apiGateway.request.schemas` when I have a **shared Api Gateway**.
It seems that the cloud formation template to create de Model Resource failed to map the RestApiId, this is the output for that resource:
```json
"ApiGatewayStartExecutionModel": {
  "Type": "AWS::ApiGateway::Model",
  "Properties": {
    "RestApiId": {},
    "Schema": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Start Execution Schema",
      "type": "object",
      "properties": {
        "start_date": {
          "type": "string"
        }
      }
    },
    "ContentType": "application/json",
    "Name": "StartExecutionSchema"
  }
},
```

### Service configuration (serverless.yml) content

```yaml
service: test
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.7
  apiGateway:
    restApiId: ${param:restApiId}
    restApiRootResourceId: ${param:restApiRootResourceId}
    request:
      schemas:
        start-execution:
          name:  StartExecutionSchema
          schema: ${file(start_execution.json)}

functions:
  health:
    handler: api.handler
    events:
      - http:
          path: /test
          method: POST
          request:
            schemas:
              application/json: start-execution
```

### Command name and used flags

serverless deploy --stage dev

### Command output

```shell
Error:
CREATE_FAILED: ApiGatewayStartExecutionModel (AWS::ApiGateway::Model)
Identifiers must be of type String or Number. {[]} at {/properties/RestApiId} is of type {OBJECT}
```

### Environment information

```shell
Framework Core: 3.33.0 (local) 3.33.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
