### ISSUE TITLE
Value not found at cf source

### ISSUE THREAD

**Issue by bharathkumar223** [serverless/serverless#12042]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.COGNITO_USER_POOL_ID": Value not found at "cf" source,
  - Cannot resolve variable at "provider.environment.COGNITO_CLIENT_ID": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getUser.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.updateUser.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.deleteUser.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.updateUserToken.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getShopByID.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.createNewShop.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.createScheduledService.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.inviteUserToCognito.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getServiceAgreementUrl.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getMembers.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.sendSignUpLoopEmail.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "resources.Resources.PostConfirmTriggerInvokePermission.Properties.SourceArn": Value not found at "cf" source

1 deprecation found: run 'serverless doctor' for more details

am getting the above error when am trying to deploy test function

### Service configuration (serverless.yml) content

```yaml
service: motorvate-services
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - apiGateway:GET
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: ${self:provider.stage}-user-pool
        MfaConfiguration: "OFF"
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: ${self:provider.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false

    CognitoIdentityPool:
      Type: "AWS::Cognito::IdentityPool"
      Properties:
        IdentityPoolName: ${self:provider.stage}-identity-pool
        AllowUnauthenticatedIdentities: true
        CognitoIdentityProviders:
          - ClientId: !Ref CognitoUserPoolClient
            ProviderName: !GetAtt CognitoUserPool.ProviderName

    ProxyApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: api gateway proxy

    ApiGatewayAuthorizer: 
      Type: AWS::ApiGateway::Authorizer
      Properties: 
        Name: CognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId: { "Ref": "ProxyApi" }
        ProviderARNs: 
          - Fn::GetAtt:
              - CognitoUserPool
              - Arn

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: tokens-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        TimeToLiveSpecification:
          AttributeName: timestamp
          Enabled: true
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST

  Outputs:
    UserPoolArn:
      Value:
        Fn::GetAtt: CognitoUserPool.Arn
      Export:
        Name: ExtCognitoUserPool-${self:provider.stage}

    UserPoolId:
      Value:
        Ref: CognitoUserPool
      Export:
        Name: ExtCognitoUserPoolId-${self:provider.stage}

    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
      Export:
        Name: ExtCognitoUserPoolClientId-${self:provider.stage}
    
    IdentityPoolId:
      Value:
        Ref: CognitoIdentityPool

    ApiGatewayAuthorizerId:
      Value:
        Ref: ApiGatewayAuthorizer
      Export:
        Name: ExtApiGatewayAuthorizer-${self:provider.stage}

    TokenTableArn:
      Value:
        Fn::GetAtt: TokensTable.Arn
      Export:
        Name: ExttokensArn-${self:provider.stage}
    TokenTableStreamArn:
      Value:
        Fn::GetAtt: TokensTable.StreamArn
      Export:
        Name: ExttokensStreamArn-${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 1
```

### Command name and used flags

serverless deploy -f testFunction -s test  

### Command output

```shell
Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.COGNITO_USER_POOL_ID": Value not found at "cf" source,
  - Cannot resolve variable at "provider.environment.COGNITO_CLIENT_ID": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getUser.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.updateUser.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.deleteUser.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.updateUserToken.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getShopByID.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.createNewShop.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.createScheduledService.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.inviteUserToCognito.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getServiceAgreementUrl.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.getMembers.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "functions.sendSignUpLoopEmail.events.0.http.authorizer.arn": Value not found at "cf" source,
  - Cannot resolve variable at "resources.Resources.PostConfirmTriggerInvokePermission.Properties.SourceArn": Value not found at "cf" source

1 deprecation found: run 'serverless doctor' for more details
```

### Environment information

```shell
API_BASE_URL=apistage.motorvate.app
APPLICATION_ARN=arn:aws:sns:us-east-1:689607767306:app/APNS_SANDBOX/IOSAppTest
NOTIFICATIONS_API_KEY=CrO6429EVO95KCLZg5Lrb5BcxFLMY6q424XOdOlw
PRODUCTION=staging
LOOP_API_KEY=34cc24bffb99f8164128e4a165a3f75e
```

**Comment by medikoo** [comment]
@bharathkumar223 this report doesn't look as complete. Resolver complains it cannot resolve variables at `provider.environment.`, yet you didn't list this section in your `serverless.yml` content.

Also I believe everything works as expected, please take a look closer at reported message, it signals that environment variables are configured with `cf` variables, yet resolver using provided AWS credentials is unable to resolve those values from AWS

**Comment by s1mrankaur** [comment]
@bharathkumar223 Were you able to resolve this? I am seeing this behaviour with sls remove

**Comment by AVandana-1806** [comment]
I was trying to run the sls from account A to account B cross account and got the error on cf variable, once I gave the proper assume role in account A, I was able to resolve the issue.

**Comment by xreyc** [comment]
I have the same related issue with cf not found.

I solved mine by running the whole script first without using all the ${cf:} variables first.
It seems like the resource has to exist first before using the ${cf:} variable, weird.

First, comment out all scripts that contain ${cf:}
Second, run **sls deploy** to provision the initial resources.
Third, uncomment the scripts then run sls again..
Or the other way around, run script on a separate serverless.yml


I'll give you an example:

```
app: serverless1
service: serverless1
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  environment:
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "cognito-idp:AdminConfirmSignUp"
            - "cognito-idp:ListUsers"
          Resource: "*"

functions:
  # Lambda authorizer
  lambdaAuthorizer:
    handler: src/handlers/auth/lambdaAuthorizer.authorize

  # Lambda authorizer protected route
  lambdaAuthorizerProtectedResource:
    handler: src/handlers/test/handler2.getTest
    events:
      - http:
          path: lambda/protected/getTest
          method: GET
          authorizer: lambdaAuthorizer

  # Cognito authorizer protected route
  cognitoAuthorizerProtectedResource:
    handler: src/handlers/test/handler3.getTest
    events:
      - http:
          path: cognito/protected/getTest
          method: GET
          cors: true
          authorizer:
            arn: ${cf:serverless1-${self:provider.stage}.CognitoUserPoolArn}

# Resources
resources:
  Resources:
    # Cognito
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-${self:provider.stage}-MyAppClient
        UserPoolId:
          Ref: CognitoUserPool

  Outputs:
    CognitoUserPoolArn:
      Value:
        Fn::GetAtt:
          - CognitoUserPool
          - Arn
      Export:
        Name: "serverless1-${self:provider.stage}"
```

On this example, first comment the
```
authorizer:
            arn: ${cf:serverless1-${self:provider.stage}.CognitoUserPoolArn}
```
on first deploy, then uncomment and redeploy
