### ISSUE TITLE
An error occurred: CustomDashresourceDashexistingDashcupLambdaFunction - Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions."

### ISSUE THREAD

**Issue by aryakrishn** [serverless/serverless#12054]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Getting error on deploying the code.

An error occurred: CustomDashresourceDashexistingDashcupLambdaFunction - Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions.

The run time is set to nodejs18.x as in the attached serverless.yml format.

This error is happening when I add cognitoUserPool event to the function. Without it deployment works.

### Service configuration (serverless.yml) content

```yaml
service: app-backend

plugins:
  - serverless-dotenv-plugin
  - serverless-prune-plugin

custom:
  dotenv:
    variableExpansion: false
  prune:
    automatic: true
    number: 5
      
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20200924

functions:
business-user-create:
    handler: handler.user.message
    events:
      - http:
          path: /user/message
          method: post
          cors: true
      - cognitoUserPool:
          pool: ${env:COGNITO_POOL_NAME}
          trigger: PostConfirmation
          existing: true
          forceDeploy: true
```

### Command name and used flags

serverless deploy 

### Command output

```shell
Serverless Error ----------------------------------------
 
  An error occurred: CustomDashresourceDashexistingDashcupLambdaFunction - Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. "
```

### Environment information

```shell
serverless --version

Framework Core: 3.33.0
Plugin: 6.2.3
SDK: 4.3.2
```
