### ISSUE TITLE
Getting type error on adding resources section in serverless.ts file

### ISSUE THREAD

**Issue by nirmalmaheshs** [serverless/serverless#12050]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I am using the aws-nodejs-typescript template. The application contains a few cloudformation templates which need to be deployed with serverless deployment.

I used to import the YML files using the resources section with an array of strings. When I try to do the same in the typescript template, I am getting the following type error:

Type 'string[]' has no properties in common with type '{ AWSTemplateFormatVersion?: string; Conditions?: { [k: string]: unknown; }; Description?: string; Mappings?: { [k: string]: unknown; }; Metadata?: { [k: string]: unknown; }; Outputs?: { [k: string]: unknown; }; Parameters?: { [k: string]: unknown; }; Resources?: { ...; };

It looks like the type definition only accepts the only  JSON cloudformation templates. But still, the deployment works if I extend the type definition in my serverless.ts file

<img width="1056" alt="image" src="https://github.com/serverless/serverless/assets/97349797/5d65b632-9b72-4c9b-ac0d-4ca366965726">

### Service configuration (serverless.yml) content

```yaml
import type {AWS} from '@serverless/typescript';

import {hello} from './services/modify-chime-meeting/app';


const serverlessConfiguration: AWS = {
    service: 'platform',
    frameworkVersion: '3',
    plugins: [
        'serverless-esbuild',
        'serverless-deployment-bucket',
        'serverless-prune-plugin',
        'serverless-dotenv-plugin',
        'serverless-offline'
    ],
    useDotenv: true,
    provider: {
        name: 'aws',
        runtime: 'nodejs14.x',
        stage: "${opt:stage, 'dev'}",
        apiGateway: {
            minimumCompressionSize: 1024,
            shouldStartNameWithService: true,
        },
        tracing: {
            lambda: true,
            apiGateway: true,
        },
        logs: {
            restApi: {
                executionLogging: false,
            },
        },
        environment: {
            AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
            NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
        },
        lambdaHashingVersion: '20201221',
    },
    // import the function via paths
    functions: {hello},
    package: {individually: true},
    custom: {
        prune: {
            automatic: true,
            includeLayers: true,
            number: 5,
        },
        esbuild: {
            bundle: true,
            minify: true,
            sourcemap: true,
            exclude: ['aws-sdk'],
            target: 'node14',
            define: {'require.resolve': undefined},
            platform: 'node',
            concurrency: 10,
        },
    },
    resources: [
        "${file(./services/platform/infra-assets/eventbus.yml)}",
    ]
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

sls deploy --stage dev

### Command output

```shell
Cannot load "platform.serverless.ts": Initialization error: TSError: ⨯ Unable to compile TypeScript:
platform.serverless.ts:60:5 - error TS2559: Type 'string[]' has no properties in common with type '{ AWSTemplateFormatVersion?: string; Conditions?: { [k: string]: unknown; }; Description?: string; Mappings?: { [k: string]: unknown; }; Metadata?: { [k: string]: unknown; }; Outputs?: { [k: string]: unknown; }; Parameters?: { [k: string]: unknown; }; Resources?: { ...; }; Transform?: string[]; extensions?: { ...; }...'.

60     resources: [
       ~~~~~~~~~

  node_modules/@serverless/typescript/index.d.ts:1254:3
    1254   resources?: {
           ~~~~~~~~~
    The expected type comes from property 'resources' which is declared here on type 'AWS'
```

### Environment information

```shell
Framework Core: 3.33.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
