### ISSUE TITLE
Can't deploy to same region with existing S3 event

### ISSUE THREAD

**Issue by bcgreenwood-rs** [serverless/serverless#12062]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a single stack which contains, among other things, a function listening for PutObject events on an existing S3 bucket defined in the same `serverless.yml` file in the Resources section.

In my case, I need to deploy this stack not only to our three stage environments (dev, staging, prod), but also four separate geographical locations within those stages corresponding to our web server locations. Two of those four are Australia and New Zealand. Until such time as the Auckland region is available for our needs, the AU and NZ versions of the stack are both being deployed to `ap-southeast-2` (Sydney). All our resources have the region (which is passed in via a command line parameter) being used as a part of their name so as to stay unique.

The problem arises when Serverless creates the `Custom::S3` resources. There appears to be no way to specify, or at least contribute to, the name that gets used for this, and so we end up with a conflict between the AU and NZ stacks when trying to deploy.

### Service configuration (serverless.yml) content

```yaml
service: cloud-images
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: default

functions:
  PutLanding:
    name: cloud-images-${param:region}-${sls:stage}-PutLanding
    handler: dist/handler.putLanding
    role: PutLandingRole
    reservedConcurrency: 50
    memorySize: 512
    timeout: 30
    events:
      - s3:
          bucket: !Ref ImageLandingBucket
          existing: true
          event: s3:ObjectCreated:*

resources:
  Resources:
    ImageLandingBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: !Sub image-landing-${param:region}-${sls:stage}-${aws:accountId}
          LifecycleConfiguration:
            Rules:
              - Id: ThreeDayExpiry
                Status: Enabled
                ExpirationInDays: 3
```

### Command name and used flags

sls deploy --stage dev --region ap-southeast-2 --aws-profile default --param="region=au"

### Command output

```shell
Deploying cloud-images to stage dev (ap-southeast-2)

✖ Stack cloud-images-dev failed to deploy (458s)
Environment: darwin, node 16.10.0, framework 3.33.0, plugin 6.2.3, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: PutLandingCustomS31 (Custom::S3)
Received response status [FAILED] from custom resource. Message returned: Unable to validate the following destination configurations See details in CloudWatch Log: 2023/07/12/[$LATEST]edc8b7d7815e4b8a8648272bacc62681 (RequestId: eb3148ef-2fbd-4485-8369-62fb30ea7681)

View the full error: https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A776354364980%3Astack%2Fcloud-images-dev%2Fa4cc19a0-2100-11ee-819c-0214fc504ce6
```

### Environment information

```shell
Framework Core: 3.33.0
Plugin: 6.2.3
SDK: 4.3.2
```
