### ISSUE TITLE
Serverless command "deploy" not found

### ISSUE THREAD

**Issue by LeicHHH** [serverless/serverless#12066]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello, i am trying to deploy to azure but deploy is not recognized, i have used serverless to deploy to AWS before.

I also run the command `npm install --save serverless-azure-functions` and serverless is installed.

### Service configuration (serverless.yml) content

```yaml
`service: azure-python-service

provider:
  name: azure
  location: West US
  runtime: python3.8

functions:
  pythonSAP:
    handler: handler.main
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - get
`
```

### Command name and used flags

serverless deploy

### Command output

```shell
Environment: linux, node 18.16.0, framework 3.33.0, plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Serverless command "deploy" not found. Run "serverless help" for a list of all available commands.
```

### Environment information

```shell
Environment: linux, node 18.16.0, framework 3.33.0, plugin 6.2.3, SDK 4.3.2
```

**Comment by vibovenkat123** [comment]
Try installing serverless-azure-functions:

```yaml
service: azure-python-service

provider:
  name: azure
  location: eastus
  runtime: python3.8

plugins:
  - serverless-azure-functions

functions:
  pythonSAP:
    handler: handler.main
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
          methods:
            - get
```

and then installing with npm:

` npm i -D serverless-azure-functions`
