### ISSUE TITLE
I have "jsreport-core": "^2.10.1", installed in my serverless Node App. I have tried to deploy on AWS lambda. But this throws below error like dependency 

### ISSUE THREAD

**Issue by jayakumar1998** [serverless/serverless#12075]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

below is the error throws while deploying the serverless deploy on github actions.
Not sure what i have missed.
Compiling ...
Warning: G] "vm2/lib/sandbox.js" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/jsreport-core/lib/reporter.js:162:62:
      162 │ ...ion.resource('sandbox.js', require.resolve('vm2/lib/sandbox.js'))
          ╵                                               ~~~~~~~~~~~~~~~~~~~~

Warning: G] "vm2/lib/contextify.js" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/jsreport-core/lib/reporter.js:163:65:
      163 │ ...source('contextify.js', require.resolve('vm2/lib/contextify.js'))
          ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~

Warning: G] "handlebars" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/jsreport-handlebars/lib/handlebars.js:8:[12](https://github.com/Steama-team/ev-backend/actions/runs/5613676095/job/15210200211#step:7:13)8:
      8 │ ...nition.options.handlebarsModulePath : require.resolve('handlebars')
        ╵                                                          ~~~~~~~~~~~~

Error: R] Could not resolve "emitter"

    node_modules/batch/index.js:9:24:
      9 │   var Emitter = require('emitter');
        ╵                         ~~~~~~~~~

  You can mark the path "emitter" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

Error: R] Could not resolve "should"

    node_modules/jsreport-core/test/store/common.js:1:23:
      1 │ const should = require('should')
        ╵                        ~~~~~~~~

  You can mark the path "should" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

Error: R] Could not resolve "should"

    node_modules/jsreport-core/test/blobStorage/common.js:1:8:
      1 │ require('should')
        ╵         ~~~~~~~~

  You can mark the path "should" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

× Stack ev-backend-sls-app-dev failed to deploy (25s)
Environment: linux, node 16.20.0, framework 3.33.0, plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Error:
Docs:        docs.serverless.com
Error: Build failed with 3 errors:
Support:     forum.serverless.com
node_modules/batch/index.js:9:24: ERROR: Could not resolve "emitter"
Bugs:        github.com/serverless/serverless/issues
node_modules/jsreport-core/test/blobStorage/common.js:1:8: ERROR: Could not resolve "should"

node_modules/jsreport-core/test/store/common.js:1:23: ERROR: Could not resolve "should"
    at failureErrorWithLog (/github/workspace/node_modules/esbuild/lib/main.js:1604:15)
    at /github/workspace/node_modules/esbuild/lib/main.js:1056:28
    at /github/workspace/node_modules/esbuild/lib/main.js:1001:67
    at buildResponseToResult (/github/workspace/node_modules/esbuild/lib/main.js:1054:7)
    at /github/workspace/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/github/workspace/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/github/workspace/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/github/workspace/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:5[13](https://github.com/Steama-team/ev-backend/actions/runs/5613676095/job/15210200211#step:7:14):28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:3[15](https://github.com/Steama-team/ev-backend/actions/runs/5613676095/job/15210200211#step:7:16):12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:[19](https://github.com/Steama-team/ev-backend/actions/runs/5613676095/job/15210200211#step:7:20)0:[23](https://github.com/Steama-team/ev-backend/actions/runs/5613676095/job/15210200211#step:7:24))
<img width="1072" alt="image" src="https://github.com/serverless/serverless/assets/131142027/e9a5222f-e3c5-49a9-a525-b52c6173dee6">

### Service configuration (serverless.yml) content

```yaml
Package.json
  
"dependencies": {
    "async": "^3.2.4",
    "aws-amplify": "^5.0.12",
    "axios": "^1.3.4",
    "base64-arraybuffer": "^1.0.2",
    "cheerio": "^1.0.0-rc.12",
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "handlebars": "4.7.7",
    "html-to-xlsx": "^2.1.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "pg": "^8.9.0",
    "pg-native": "^3.0.1",
    "serverless-http": "^3.1.1",
    "typescript": "^4.9.5",
    "winston": "^3.8.2",
    "xlsx": "^0.18.5",
    "jsreport-assets": "^1.7.0",
    "jsreport-chrome-pdf": "^1.10.0",
    "jsreport-core": "^2.10.1",
    "jsreport-handlebars": "^2.1.0",
    "jsreport-html-to-xlsx": "2.6.0",
    "jsreport-phantom-pdf": "^2.6.1"
  },


Serverless.yaml

service: ev-backend-sls-app

custom:
  # esbuild:
  #   bundle: true
  #   minify: false
  domain_test: <<Sample Data>>
  domain_dev: <<>>
  domain_staging: <<>>
  userPoolName: <<>>
  publicBucketName: <<>>
  privateBucketName: <<>>
  allowed-headers:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
  authorizer:
    cognito_authorizer:
      name: cognito_authorizer
      type: COGNITO_USER_POOLS
      arn:
        Fn::GetAtt:
          - cognitoUserPool
          - Arn
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    PUBLIC_BUCKET_NAME: ${self:custom.publicBucketName}
    PRIVATE_BUCKET_NAME: ${self:custom.privateBucketName}
    STAGE: ${self:provider.stage}
    TWILIO_BASE64: <<>>
    TWILIO_SID: <<>>
    TWILIO_SECRET: <<>>
    masterOtp: <<>>
    OCPP_IP: <<>>
    DB_USER: <<>>
    PASSWORD: <<>>
    HOST: <<>>
    DB_PORT: <<>>
    DATABASE: <<>>
    CREATE_AUTH_CHALLENGE_OTP: <<>>
    RESET_PASSWORD_PAGE_URL: <<>>
package:
  patterns:
    - "!.serverless"
    - "!.env"
    - "!test.js"
    - "!gitignore"
    - "!package-lock.json"
    - "!node_modules/.cache/**"
layers:
  preBuilt:
    package:
      artifact: layer-dist/layer1.zip
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```
