### ISSUE TITLE
I'm seeing this after deploy serverless: "Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions

### ISSUE THREAD

**Issue by talhafayyaz112** [serverless/serverless#12082]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I got this error after deploying this morning.

I'm seeing this after deploy serverless: "Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions

after updating the node js verions I got this error 
Embedded stack arn:aws:cloudformation:us-east-:stack/ams-test-PoliciesNestedStack-1GCD was not successfully created: The following resource(s) failed to create: [UploadsBucketAllowPublicReadPolicy]

### Service configuration (serverless.yml) content

```yaml
service: ams

frameworkVersion: '2'

plugins:
  - serverless-esbuild
  - serverless-plugin-split-stacks
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs14.x
  architecture: arm64
  memorySize: 1024
  timeout : 500
  lambdaHashingVersion: 20201221
  iam: ${file(./resources/iam.yml)}
  environment:
    COGNITO_ADMIN_KEY: ${env:COGNITO_ADMIN_KEY, ''}
    USER_POOL_ID: ${self:custom.userPoolId.${env:ENV, 'remote'}}
    USER_POOL_CLIENT_ID: ${self:custom.userPoolClientId.${env:ENV, 'remote'}}
    TABLE_NAME: ${self:custom.tableName}
    UPLOADS_BUCKET_NAME: ${self:custom.uploadsBucketName}
    STRIPE_API_KEY: ${env:STRIPE_API_KEY}
    FRONTEND_URL: ${self:custom.frontendUrl.${env:STAGE}, '${self:custom.frontendUrl.dev}'}
    DEFAULT_INDIVIDUAL_FEE: 10
    DEFAULT_PORTFOLIO_FEE: 30
    SLOW_READING_SPEED: 150
    MEDIUM_READING_SPEED: 200
    FAST_READING_SPEED: 250
    SOURCE_EMAIL: ${env:SOURCE_EMAIL}
    NO_REPLY_EMAIL: ${env:NO_REPLY_EMAIL}
  apiGateway:
    # binaryMediaTypes:
    #   - '*/*'






custom:
  base: ${self:service}-${opt:stage}
  splitStacks:
    perFunction: true
  dynamodb:
    stages:
      - test
  serverless-offline:
    noPrependStageInUrl: true
  userPoolId:
    local: ${env:USER_POOL_ID, ''}
    remote: !Ref UserPool
  userPoolClientId:
    local: ${env:USER_POOL_CLIENT_ID, ''}
    remote: !Ref UserPoolClient
  authorizer:
    type: COGNITO_USER_POOLS
    authorizerId:
      Ref: ApiGatewayAuthorizer
  cors:
    origin: '*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - X-User-ID
      - X-Partner-Code
    allowCredentials: true
  tableName: ${self:custom.base}-table
  uploadsBucketName: ${self:custom.base}-uploads-bucket
  frontendUrl:
    local: http://localhost:3001
    dev: https://-------.org
    qa: https://------.org
    stage: https://-------.org
    prod: https://-----.app

functions: ${file(./resources/functions.yml)}

resources:
  - ${file(./resources/api-gateway.yml)}
  - ${file(./resources/cognito.yml)}
  - ${file(./resources/dynamodb.yml)}
  - ${file(./resources/s3.yml)}
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/a
```

### Environment information

```shell
serverless: 2.72.4
```
