### ISSUE TITLE
Principal for CloudWatch Subscription Filter incorrect in China region(s)

### ISSUE THREAD

**Issue by peebles** [serverless/serverless#12087]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

In version 3.32.2:

Deploying to an account in the cn-north-1 region, a lambda function with events like:
```yaml
    events:
      - cloudwatchLog:
          logGroup: /aws/lambda/my-function
          filter: '[w1!=START && w1!=END && w1!=REPORT && w1!=INIT_START, w2]'
```
The template created includes this permissions policy:
```json
    "LogsDashprocessorLambdaPermissionLogsSubscriptionFilterCloudWatchLog": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "LogsDashprocessorLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": {
          "Fn::Join": [
            "",
            [
              "logs.",
              {
                "Ref": "AWS::Region"
              },
              ".amazonaws.com"
            ]
          ]
        },
       ...
```

The "Principal" in China must end with ".amazonaws.com.cn".  Otherwise you get a "principal was not valid" error during deployment and the stack is rolled back.

This is a good post with principal requirements for gov and china: https://github.com/aws/aws-cdk/issues/1282

This temporary change in serverless.yaml gets around the problem:

```yaml
resources:
  extensions:
    # Serverless does not add the required ".cn" to the principal!
    LogsDashprocessorLambdaPermissionLogsSubscriptionFilterCloudWatchLog:
      Properties:
        Principal: "logs.cn-north-1.amazonaws.com.cn"
```

Deploying with this "fix" is successful.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

AWS_PROFILE=china AWS_REGION=cn-north-1 npx sls deploy

### Command output

```shell
Error:
CREATE_FAILED: LogsDashprocessorLambdaPermissionLogsSubscriptionFilterCloudWatchLog (AWS::Lambda::Permission)
Resource handler returned message: "The provided principal was invalid. Please check the principal and try again. (Service: Lambda, Status Code: 400, Request ID: b49c8f8a-c9cc-4c03-a7b7-818c52826449)" (RequestToken: 387b6e7b-1fdd-c551-aaa1-0e05b9d32cb9, HandlerErrorCode: InvalidRequest)
```

### Environment information

```shell
Framework Core: 3.32.2 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
