### ISSUE TITLE
Different size zip package local vs CI

### ISSUE THREAD

**Issue by mrbatista** [serverless/serverless#12084]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I notice that if run serverless deploy command on gitlab CI the size is greater than local.
I use same node and serveless version only different is system operation.

**Deploy on my local machine:**
Running "serverless" from node_modules
Environment: darwin, node 16.20.1, framework 3.33.0 (local) 3.33.0v (global), plugin 6.2.3, SDK 4.3.2

serverless deploy --stage staging --verbose
Running "serverless" from node_modules

Deploying package-name to stage staging (eu-central-1)

Packaging
Excluding development dependencies for service package
Generating custom CloudFormation resources
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service package-name.zip file to S3 (26.75 MB)

**Deploy on gitlab CI:**
Environment: linux, node 16.20.1, framework 3.33.0 (local), plugin 6.2.3, SDK 4.3.2
serverless deploy --stage staging --verbose
Deploying  package-name to stage staging (eu-central-1)
Excluding development dependencies for service package
Generating custom CloudFormation resources
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service  package-name.zip file to S3 (161.82 MB)

Deploy with CI throw error:
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400....

### Service configuration (serverless.yml) content

```yaml
service: package-name

frameworkVersion: '3'

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs16.x

  environment:
    NODE_ENV: ${sls:stage}

functions:
  handler1:
    handler: dist/index.handler1
    events:
      - s3:
          bucket: ${env:AWS_S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: prefix-directory/
          existing: true
          forceDeploy: true

constructs:
  handler2:
    type: queue
    worker:
      handler: dist/index.handler2
      fifo: true
      timeout: 600

plugins:
  - serverless-lift
```

### Command name and used flags

serverless deploy --stage staging --verbose

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.33.0 (local) 3.33.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
