### ISSUE TITLE
SEED Deploy breaking when trying to upgrade from node version 12.x

### ISSUE THREAD

**Issue by NicholasACTran** [serverless/serverless#12083]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When deploying with nodejs12.x, it usually deploys fine, but when attempting to deploy using any version higher than that, I get the following deploy errors in SEED.

`$ SLS_DEBUG=* serverless package --stage dev --package sls-package-output
46.20 s
Running "serverless" from node_modules
Packaging crm-databases for stage dev (us-east-1)
AppSync Plugin: GraphQl schema valid
Compiling to node10 bundle with esbuild...
Compiling with concurrency: Infinity
Compiling completed.
Packaging: No files found. Skipping esbuild.
Killed
ERROR: Failed to run: SLS_DEBUG=* serverless package --stage dev --package sls-package-output
Build v1648 completed in 1m 8s. Used 2 build minutes.`

### Service configuration (serverless.yml) content

```yaml
service: crm-databases

plugins:
  - serverless-esbuild
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-step-functions

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
```

### Command name and used flags

SLS_DEBUG=* serverless package --stage dev --package sls-package-output

### Command output

```shell
SLS_DEBUG=* serverless package --stage dev --package sls-package-output
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.22.0 (local) 3.33.0 (global)
Plugin: 6.2.2
SDK: 4.3.2
```
