### ISSUE TITLE
not all node modules being uploaded

### ISSUE THREAD

**Issue by matthewberryman** [serverless/serverless#12109]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

`sls deploy` not packaging a node module - possibly because of the namespace?

https://github.com/matthewberryman/midsomerplots-content/blob/c907a978ab4443825c921033f2f0e2635f4ac398/package.json#L24

is missing from zip file

```
➜ unzip -t midsomerplots-content.zip 
Archive:  midsomerplots-content.zip
    testing: .eslintignore            OK
    testing: .eslintrc.json           OK
    testing: index.js                 OK
    testing: LICENSE                  OK
    testing: node_modules/.package-lock.json   OK
    testing: node_modules/mersenne-twister/.npmignore   OK
    testing: node_modules/mersenne-twister/.travis.yml   OK
    testing: node_modules/mersenne-twister/Makefile   OK
    testing: node_modules/mersenne-twister/package.json   OK
    testing: node_modules/mersenne-twister/README.md   OK
    testing: node_modules/mersenne-twister/src/mersenne-twister.js   OK
    testing: node_modules/mersenne-twister/test/generator.js   OK
    testing: package-lock.json        OK
    testing: package.json             OK
    testing: plot-elements-old.json   OK
    testing: plot-elements-old2.json   OK
    testing: plot-elements-old3.json   OK
    testing: plot-elements-old4.json   OK
    testing: plot-elements-old5.json   OK
    testing: plot-elements.json       OK
    testing: README.md                OK
    testing: test/index.js            OK
    testing: web/index.css            OK
    testing: web/index.html           OK
    testing: web/index.js             OK
No errors detected in compressed data of midsomerplots-content.zip.
```

### Service configuration (serverless.yml) content

```yaml
service: midsomerplots-content

#plugins:
#  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: prod
  region: us-east-1

functions:
  getPlot:
    timeout: 30
    memorySize: 2048
    handler: index.handler
    events:
      - http:
          path: plot
          cors: true
          method: get

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
```

### Command name and used flags

serverless deploy

### Command output

```shell
➜ serverless deploy

Deploying midsomerplots-content to stage prod (us-east-1)

No changes to deploy. Deployment skipped. (8s)

Need a faster logging experience than CloudWatch? Try our Dev Mode in Console: run "serverless dev"
```

### Environment information

```shell
➜ serverless --version
Framework Core: 3.34.0
Plugin: 6.2.3
SDK: 4.3.2
```
