### ISSUE TITLE
Kinesis stream starting position AT_TIMESTAMP "Invalid request provided: Need to specify a timestamp"

### ISSUE THREAD

**Issue by jtoronto** [serverless/serverless#12111]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a Kinesis stream handler and I'm trying to use AT_TIMESTAMP as the starting position. I am specifying the timestamp as indicated in the docs. 
https://www.serverless.com/framework/docs/providers/aws/events/streams#setting-the-kinesis-startingposition

after deploy, I see the following error message

```
CREATE_FAILED: MessageCreateToRTSWKSSentimentEventSourceMappingKinesisSlackStreamArn (AWS::Lambda::EventSourceMapping)
Resource handler returned message: "Invalid request provided: Need to specify a timestamp (Service: Lambda, Status Code: 400, Request ID: cd7efa0f-e5ca-4472-88eb-51ecfb585fc2)" (RequestToken: affbfa4b-1c86-7bb4-2727-8fbb3a38aca2, HandlerErrorCode: InvalidRequest)
```
If I use TRIM_HORIZON or LATEST it works fine. 

I have also tried using

`2023-07-01T00:00:00.000-00:00` (valid according to AWS docs, doesn't pass serverless validation) 
`1688169600.000` (valid according to AWS docs)
`1688169600000` (ms without the decimal)

### Service configuration (serverless.yml) content

```yaml
The entire serverless.yml is over 1000 lines long. This is the function definition.


FunctionName:
    handler: *redacted*
    description: *redacted
    architecture: arm64
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:4
      - arn:aws:lambda:us-east-1:027255383542:layer:AWS-AppConfig-Extension-Arm64:2
    events:
      - stream:
          type: kinesis
          arn: !ImportValue *redacted*
          functionResponseType: ReportBatchItemFailures
          filterPatterns:
            - data:
                event: ['message.create']
                version: [0.1]
          maximumRetryAttempts: 3
          startingPosition: AT_TIMESTAMP
          startingPositionTimestamp: 1688169600
```
```


### Command name and used flags

sls deploy --verbose --stage staging

### Command output

```shell
✖ Stack *redacted* failed to deploy (367s)
Publishing service to the Serverless Dashboard...
Successfully published your service to the Serverless Dashboard: 
*redacted*
Environment: darwin, node 18.14.0, framework 3.33.0 (local) 3.33.0v (global), plugin 6.2.3, SDK 4.3.2
Credentials: Serverless Dashboard, "aws-circus-staging" provider 
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: *function Name*
 (AWS::Lambda::EventSourceMapping)
Resource handler returned message: "Invalid request provided: Need to specify a timestamp (Service: Lambda, Status Code: 400, Request ID: cd7efa0f-e5ca-4472-88eb-51ecfb585fc2)" (RequestToken: affbfa4b-1c86-7bb4-2727-8fbb3a38aca2, HandlerErrorCode: InvalidRequest)
```

### Environment information

```shell
Framework Core: 3.33.0 (local) 3.33.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
```
