### ISSUE TITLE
Add support to use an existing IoT rule

### ISSUE THREAD

**Issue by darshil-doshi** [serverless/serverless#12114]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Currently, the IoT event creates a new rule and creates a trigger for the associated lambda function. This approach has a limitation - we cannot add further actions for the rule.

https://www.serverless.com/framework/docs/providers/aws/events/iot

### Proposed solution (optional)

Add a provision to use an existing IoT rule as a function event.

```
myFunction:
  handler: ...
  events:
    - iot:
        useExisting: true
        arn: <ARN of the existing rule>
```
