### ISSUE TITLE
sls Deploy not working, n appropriate error given

### ISSUE THREAD

**Issue by TusharKuwar** [serverless/serverless#12113]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

![image](https://github.com/serverless/serverless/assets/48707281/5b69b247-da1c-4235-83c5-fa54245b89ca)

### Service configuration (serverless.yml) content

```yaml
service: xxx	
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: ["xxx/*",
          "xxx"
          ]
functions:
  app:
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
```

### Command name and used flags

sls deploy

### Command output

```shell
Error:
Console server is not available, please try again later
```

### Environment information

```shell
Environment: win32, node 16.20.0, framework 3.34.0, plugin 6.2.3, SDK 4.3.2
```
