### ISSUE TITLE
golang aws templates refer to go1.x runtime which is being depreciated

### ISSUE THREAD

**Issue by jvsteiner** [serverless/serverless#12123]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I got a message today that the existing "go1.x" runtime is being depreciated, and replaced with a new `provided.al2` runtime.  AWS has published instructions on how to migrate [here](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/) - some of which would likely involve modifying how the handler and entrypoint are referred to in the `serverless.yaml` file.  I upgrade serverless to latest, but I still see that new projects are created with the old runtime, despite it being depreciated early next year.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
$ serverless --version
Framework Core: 3.34.0
Plugin: 6.2.3
SDK: 4.3.2
```

**Comment by Fyb3roptik** [comment]
Here for this as well

**Comment by ShiriNmi1520** [comment]
I second that as I received a deprecated notice from aws.

**Comment by ShiriNmi1520** [comment]
As I tested so far, simply change the runtime can still make deployment succes, however, when I trying to test it by simply making http request to it, I got the following error.
Maybe the further change is required 🥲 
## Errors
```json
{"message":"Internal Server Error"}
```
## Output logs
```
# myawesomeproject git:awesome-branch ● [^._.^]ﾉ彡ミ彡ミ
$ serverless --org=shirinmi


✔ Your project is ready to be deployed to Serverless Dashboard (org: "myorg", app: "myawesomeproject")

? Do you want to deploy now? Yes

Deploying myawesomeproject to stage dev (ap-southeast-1)
Warning: Serverless Dashboard monitoring features do not support the following runtime: provided.al2

✔ Service deployed to stack myawesomeproject-dev (123s)

console: https://console.serverless.com/shirinmi/metrics/awsLambda?globalEnvironments=dev&globalNamespace= myawesomeproject&globalRegions=ap-southeast-1&globalScope=awsLambda&globalTimeFrame=15m
dashboard: dashboard-url
endpoints:
  GET - endpoint1
  GET - endpoint2
functions:
  hello: myawesomeproject-dev-hello (5.9 MB)
  world: myawesomeproject-dev-world (5.9 MB)

What next?
Run these commands in the project directory:

serverless deploy    Deploy changes
serverless info      View deployed endpoints and resources
serverless invoke    Invoke deployed functions
serverless --help    Discover more commands
```
## Serverless configuration file
```yml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: refrigeratorfoodcleaner
# app and org for use with dashboard.serverless.com
app: myawesomeproject
org: myorg

configValidationMode: error

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  stage: dev
  region: ap-southeast-1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - httpApi:
          path: /hello
          method: get
  world:
    handler: bin/world
    events:
      - httpApi:
          path: /world
          method: get
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
# events:
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
```

**Comment by Fyb3roptik** [comment]
You have to name the binary specifically. Check that doc

**Comment by ribtoks** [comment]
> You have to name the binary specifically

Regarding this. Would be great if Serverless allowed to rename the binary automatically. It's quite annoying to start managing it if you're deploying more than 1 binary and they are stored (typically) in the common `./bin/` dir

**Comment by devalexandre** [comment]
I have this problem too

```yml
service: app-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1

package:
  patterns:
    - '!./**'
    - bootstrap


functions:
  app:
    handler: bootstrap
    events:
      - httpApi:
          path: /v1/api
          method: post
      
``` 

my makefile

```sh
.PHONY: build clean deploy zip

build:
	go get ./...
	go mod vendor
	env GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o bootstrap -tags lambda.norpc cmd/main.go

zip:
	zip -j app.zip bootstrap

clean:
	rm -rf ./bin ./vendor

deploy: clean build zip
	sls deploy --verbose 
```

**Comment by Fyb3roptik** [comment]
Maybe we could just do `./bin/func1/bootstrap`? That using the folder structure to know which one to use?

**Comment by shout-poor** [comment]
It looks like `bootstrap` needs to be placed at the root of the package.
https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html

**Comment by jvsteiner** [comment]
Something like `./bin/func1/bootstrap` was what I was hoping to see - makes sense

**Comment by ribtoks** [comment]
Using `./bin/func1/bootstrap` is annoying locally. Of course you _can_ make this workaround today, but I think it will be much friendlier if serverless framework will package it for you like this. Zip archive is created by serverless so it should be easy to create file in the archive with a different mapping.

**Comment by jvsteiner** [comment]
What is annoying about it?  What folder structure locally would you propose?  I understanding you have in mind that you could maybe have binaries `./bin/func1` and `./bin/func2` locally, and then package them as `./bin/func1/bootstrap` and `./bin/func1/bootstrap`  in the container, but what is the benefit?

**Comment by ribtoks** [comment]
Personally for me, the benefits are:

- having all binaries in a single directory which is prefixed to the `$PATH` when I need it
- clarity when I do `ls` what is what
- lambda and non-lambda binaries in the single directory
- consistency in the `Makefile`

**Comment by Fyb3roptik** [comment]
Agreed with the above 100%, just saying as a workaround is all. I hope serverless handles this in the build process

**Comment by yasuto-nishii** [comment]
I agree as well. For now, I'm developing Makefile to do above process.

**Comment by alock** [comment]
From my understanding of the required migration you can no longer pass a binary into the runtime.  [This blogpost](https://blog.matthiasbruns.com/running-multiple-golang-aws-lambda-functions-on-arm64-with-serverlesscom) by @matthiasbruns helped me out a bunch (thanks!)

changes to our build logic:
```shell
GOOS=linux GOARCH=arm64 go build -ldflags -s -d -w -tags lambda.norpc -mod=readonly -o bin/function/bootstrap cmd/function/main.go
zip -j bin/function.zip bin/function/bootstrap
```

changes to our serverless files where below:
```yaml
provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
...
package:
  individually: true
...
functions:
  function:
    handler: bootstrap
    package:
      artifact: bin/function.zip
...
```
