### ISSUE TITLE
Cannot assign to read only property 'defaultCoreCipherList'

### ISSUE THREAD

**Issue by tvpmb** [serverless/serverless#12139]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I try to run this command, I get a strange error, from what seems to be from node-crypto?

`sls offline --port=3001 --host=0.0.0.0 start --stage local`

### Service configuration (serverless.yml) content

```yaml
service: experience-service

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-plugin-existing-s3
  - serverless-domain-manager
  - serverless-s3-sync
  - serverless-s3-local-sync

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-west-2
  environment:
    ENV: ${self:custom.${self:provider.stage}.env}
    SITE_BUCKET_NAME: ${self:custom.${self:provider.stage}.siteBucket}
    SITE_DEPENDENCIES_BUCKET_NAME: ${self:custom.${self:provider.stage}.siteDependenciesBucket}
    ASSETS_BUCKET_NAME: ${self:custom.${self:provider.stage}.assetsBucket}
    HUB_CONFIG_FILENAME: ${self:custom.${self:provider.stage}.hubConfigFileName}
    SITE_TEMPLATES_BUCKET_NAME: ${self:custom.${self:provider.stage}.templatesBucket}
    SERVICE_DOMAIN_POSTFIX: ${self:custom.${self:provider.stage}.serviceDomainPostfix}
    WIDGET_BUCKET_NAME: ${self:custom.${self:provider.stage}.widgetsBucket}

    S3_KEY_ALIAS_CONFIG: ${env:S3_KEY_ALIAS_CONFIG}
    SERVER_TO_SERVER_AUTH_KEY: ${env:SERVER_TO_SERVER_AUTH_KEY}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogStream"
        - "s3:*"
        - "logs:CreateLogGroup"
        - "logs:PutLogEvents"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource:
        - "*"

custom:
  test:
    env: "test"
    siteBucket: "<hostname>"
    siteDependenciesBucket: "<hostname>"
    assetsBucket: "<hostname>"
    templatesBucket: "<hostname>"
    hubConfigFileName: "test_config.json"
    siteDomain: "<hostname>"
    certificate: "*.<hostname>"
    serviceDomainPostfix: ".<hostname>"
    widgetsBucket: "<hostname>"

  stage:
    env: "stage"
    siteBucket: "<hostname>"
    siteDependenciesBucket: "<hostname>"
    assetsBucket: "<folder>"
    templatesBucket: "<folder>"
    hubConfigFileName: "stage_config.json"
    siteDomain: "<hostname>"
    certificate: "*.<hostname>"
    serviceDomainPostfix: ".<hostname>"
    widgetsBucket: "<hostname>"

  prod:
    env: "prod"
    siteBucket: "<hostname>"
    siteDependenciesBucket: "<hostname>"
    assetsBucket: "<folder>"
    templatesBucket: "<folder>"
    hubConfigFileName: "prod_config.json"
    siteDomain: "<hostname>"
    certificate: "*.<hostname>"
    serviceDomainPostfix: ".<hostname>"
    widgetsBucket: "<hostname>"

  local:
    env: "local"
    siteBucket: "<hostname>"
    siteDependenciesBucket: "<hostname>"
    assetsBucket: "<folder>"
    templatesBucket: "<folder>"
    hubConfigFileName: "prod_config.json"
    siteDomain: "<hostname>"
    certificate: "*.<hostname>"
    serviceDomainPostfix: ".<hostname>"
    widgetsBucket: "<hostname>"

  s3:
    host: 0.0.0.0
    port: 8000
    directory: ../buckets

  s3Sync:
    bucketName: <folder>
    src: ./templates

  customDomain:
    domainName: ${self:custom.${self:provider.stage}.siteDomain}
    stage: ${opt:stage}
    certificateName: ${self:custom.${self:provider.stage}.certificate}
    createRoute53Record: true
    endpointType: 'regional'

functions:
  site-serve:
    handler: experience.serve
    tags:
      datadog: yes
    events:
      - http:
          path: /{bucket_key+}
          method: get
          cors: true

  publish-site:
    handler: experience.publish
    events:
      - existingS3:
          bucket: ${self:custom.${self:provider.stage}.assetsBucket}
          events:
            - s3:ObjectCreated:*

      - existingS3:
          bucket: ${self:custom.${self:provider.stage}.templatesBucket}
          events:
            - s3:ObjectCreated:*

  publish-widget:
    handler: experience.widget
    events:
      - existingS3:
          bucket: ${self:custom.${self:provider.stage}.widgetsBucket}
          events:
            - s3:ObjectCreated:*
```

### Command name and used flags

sls offline --port=3001 --host=0.0.0.0 start --stage local

### Command output

```shell
$ sls offline --port=3001 --host=0.0.0.0 start --stage local
(node:39128) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39128) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy

  Type Error ---------------------------------------------

     Cannot assign to read only property 'defaultCoreCipherList'
     of object '[object Object]'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       14.21.3
     Serverless Version: 1.8.0
```

### Environment information

```shell
$ serverless --version
1.8.0
(node:40008) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40008) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```
