### ISSUE TITLE
After 3.35.2 upgrade, deploy failing with node v12.3.0 unsupported error.

### ISSUE THREAD

**Issue by bhuvaneshwari** [serverless/serverless#12169]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The last time I ran serverless deploy successfully was with v3.34.0. Now when I try to run deploy again for frameworkVersion "3", the version is 3.35.2 and deploy fails with following error on AWS

` Error: Serverless Framework v3 does not support Node.js v12.13.0. Please upgrade Node.js to the latest LTS version (v14.0.0 is a minimum supported version)`

### Service configuration (serverless.yml) content

```yaml
service: backup-exception
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  timeout: 900
  region: us-east-1
  vpc:
    securityGroupIds: ${self:custom.SECURITY_GROUPS}
    subnetIds: ${self:custom.SUBNETS}
  deploymentBucket:
    name: ${self:custom.admin_account}-lambda-package-us-east-1
    serverSideEncryption: AES256
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - sts:AssumeRole
            - secretsmanager:GetSecretValue
            - lambda:InvokeFunction
          Resource:
            - '*'
  endpointType: PRIVATE
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
  environment:
    sddcapi_boot_dir: config
    region_secret: ${self:custom.region_secret}
    ADMIN_ACCOUNT: ${self:custom.admin_account}
    SUBNETS: ${self.custom.SUBNETS}
    LOG_LEVEL: ${self:custom.LOG_LEVEL}

functions:
  get:
    handler: sls/idms_sync/app/get_exception.handler
    timeout: 900
    events:
      - alb:
          listenerArn: ${self:custom.alb_listener}
          priority: 356
          conditions:
            path: /v1/exceptions/backup-exception/*
            method:
              - GET
    environment:
      ALLOWED_GROUPS: ${self:custom.ALLOWED_GROUPS_GET}
      ALLOWED_ROLES: ${self:custom.ALLOWED_ROLES_GET}
    layers:
      - ${self:custom.LAYER_CLOUDX_AUTHORIZER}
      - ${self:custom.LAYER_CLOUDX_LOGGER}
      - ${self:custom.LAYER_CLOUDX_APPSYNC_HELPER}

  apply:
    handler: backup_exception_api/app/apply_exception.handler
    timeout: 900
    events:
      - alb:
          listenerArn: ${self:custom.alb_listener}
          priority: 357
          conditions:
            path: /v1/exceptions/backup-exception
            method:
              - POST
    environment:
      ALLOWED_GROUPS: ${self:custom.ALLOWED_GROUPS_APPLY}
      ALLOWED_ROLES: ${self:custom.ALLOWED_ROLES_APPLY}
      vpcxiam_scope: ${self:custom.vpcxiam_scope}
      vpcxiam_endpoint: ${self:custom.vpcxiam_endpoint}
      vpcxiam_host: ${self:custom.vpcxiam_host}
      token_url: ${self:custom.token_url}
      app_client_id: ${self:custom.app_client_id}
    layers:
      - ${self:custom.LAYER_CLOUDX_AUTHORIZER}
      - ${self:custom.LAYER_CLOUDX_LOGGER}
      - ${self:custom.LAYER_CLOUDX_APPSYNC_HELPER}

  verify:
    handler: sls/idms_sync/app/verify_exception.handler
    timeout: 900
    events:
      - alb:
          listenerArn: ${self:custom.alb_listener}
          priority: 358
          conditions:
            path: /v1/exceptions/backup-exception/*
            method:
              - PUT
    environment:
      ALLOWED_GROUPS: ${self:custom.ALLOWED_GROUPS_VERIFY}
      ALLOWED_ROLES: ${self:custom.ALLOWED_ROLES_VERIFY}
    layers:
      - ${self:custom.LAYER_CLOUDX_AUTHORIZER}
      - ${self:custom.LAYER_CLOUDX_LOGGER}
      - ${self:custom.LAYER_CLOUDX_APPSYNC_HELPER}

  remove:
    handler: sls/idms_sync/app/remove.handler
    timeout: 900
    events:
      - alb:
          listenerArn: ${self:custom.alb_listener}
          priority: 359
          conditions:
            path: v1/exceptions/backup-exception/*
            method:
              - DELETE
    environment:
      ALLOWED_GROUPS: ${self:custom.ALLOWED_GROUPS_REMOVE}
      ALLOWED_ROLES: ${self:custom.ALLOWED_ROLES_REMOVE}
    layers:
      - ${self:custom.LAYER_CLOUDX_AUTHORIZER}
      - ${self:custom.LAYER_CLOUDX_LOGGER}
      - ${self:custom.LAYER_CLOUDX_APPSYNC_HELPER}


custom:
  output:
    file: stack-outputs.json
  prune:
    automatic: true
    number: 3
  logSubscription:
    enabled: false
    destinationArn: ${file(config/config.${opt:stage}.json):LOGGING.LOG_DESTINATION}
    apiGatewayLogs: false
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    slimPatterns:
      - "**/*.egg-info*"
    noDeploy: [ ]
    pipCmdExtraArgs:
      ${file(config/config.common.json):pipCmdExtraArgs}
  stage: ${opt:stage}
  func_prefix: ${self:service}-${self:custom.stage}
  region_secret: ${opt:region, self:provider.region}
  admin_account: ${file(config/config.${opt:stage}.json):MAIN.ADMIN_ACCOUNT}
  SUBNETS: ${file(config/config.${opt:stage}.json):DEPLOYMENT.SUBNETS}
  SECURITY_GROUPS: ${file(config/config.${opt:stage}.json):DEPLOYMENT.SECURITY_GROUPS}
  LOG_LEVEL: ${file(config/config.${opt:stage}.json):MAIN.LOG_LEVEL}
  ALLOWED_GROUPS_GET: ${file(config/config.common.json):GET.ALLOWED_GROUPS}
  ALLOWED_GROUPS_APPLY: ${file(config/config.common.json):APPLY.ALLOWED_GROUPS}
  ALLOWED_GROUPS_VERIFY: ${file(config/config.common.json):VERIFY.ALLOWED_GROUPS}
  ALLOWED_GROUPS_REMOVE: ${file(config/config.common.json):REMOVE.ALLOWED_GROUPS}
  ALLOWED_ROLES_GET: ${file(config/config.common.json):GET.ALLOWED_ROLES}
  ALLOWED_ROLES_APPLY: ${file(config/config.common.json):APPLY.ALLOWED_ROLES}
  ALLOWED_ROLES_VERIFY: ${file(config/config.common.json):VERIFY.ALLOWED_ROLES}
  ALLOWED_ROLES_REMOVE: ${file(config/config.common.json):APPLY.ALLOWED_ROLES}
  alb_listener: ${file(config/config.${opt:stage}.json):DEPLOYMENT.ALB_LISTENER}
  LAYER_CLOUDX_AUTHORIZER: ${file(config/config.${opt:stage}.json):DEPLOYMENT.CLOUDX_AUTHORIZER}
  LAYER_CLOUDX_LOGGER: ${file(config/config.${opt:stage}.json):DEPLOYMENT.CLOUDX_LOGGER}
  LAYER_CLOUDX_APPSYNC_HELPER: ${file(config/config.${opt:stage}.json):DEPLOYMENT.CLOUDX_APPSYNC_HELPER}
  ADMIN_IAM_ROLE_ARN: ${file(config/config.${opt:stage}.json):DEPLOYMENT.ADMIN_IAM_ROLE_ARN}
  vpcxiam_endpoint: ${file(config/config.${opt:stage}.json):VPCXIAM.VPCXIAM_ENDPOINT}
  vpcxiam_host: ${file(config/config.${opt:stage}.json):VPCXIAM.VPCXIAM_HOST}
  vpcxiam_scope: ${file(config/config.${opt:stage}.json):VPCXIAM.VPCXIAM_SCOPE}
  token_url: ${file(config/config.common.json):ENVIRONMENT.LDAP_TOKEN_URL}
  app_client_id: ${file(config/config.${opt:stage}.json):OAUTH2.APP_CLIENT_ID}

plugins:
  - serverless-python-requirements
  - serverless-stack-output
  - serverless-prune-plugin
  - serverless-plugin-log-subscription

package:
  patterns:
    - '!node_modules/**'
    - '!sls/read_only_user_group/tests/**'
    - '!sls/utils/tests/**'
    - '!scripts/**'
```

### Command name and used flags

serverless deploy -s ${ENV} -c ${sls_file_name} --force

### Command output

```shell
Error: Serverless Framework v3 does not support Node.js v12.13.0. Please upgrade Node.js to the latest LTS version (v14.0.0 is a minimum supported version
```

### Environment information

```shell
3.35.2

serverless --version also returns the following 
Error: Serverless Framework v3 does not support Node.js v12.13.0. Please upgrade Node.js to the latest LTS version (v14.0.0 is a minimum supported version)
```
