### ISSUE TITLE
Console server is unavailable, please try again later

### ISSUE THREAD

**Issue by jordmax12** [serverless/serverless#12166]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Trying to deploy a gamelift service and keeps hitting this error, other services work fine. This worked fine before upgrade to 3.34.0

### Service configuration (serverless.yml) content

```yaml
service: gamelift
app: rps
org: app
frameworkVersion: '^3'
configValidationMode: error

provider:
  name: aws
  region: us-east-1
  tags:
    APP: ${self:app}
    SERVICE: ${self:service}

custom:
  timeoutInSeconds:
    dev: 600
    staging: 600
    prod: 600

resources:
  Resources:
    GameLiftMatchmakingRuleSet:
      Type: AWS::GameLift::MatchmakingRuleSet
      Properties:
        Name: rps-gp-matchmaking-rule-set
        RuleSetBody: '{"name":"app-matchmaking-ruleset","ruleLanguageVersion":"1.0","teams":[{"name":"69","minPlayers":1,"maxPlayers":1},{"name":"420","minPlayers":1,"maxPlayers":1}]}'
    GameLiftMatchmakingV2RuleSet:
      Type: AWS::GameLift::MatchmakingRuleSet
      Properties:
        Name: rps-gp-matchmaking-rule-set-v2
        RuleSetBody: '{"name":"app-matchmaking-ruleset","ruleLanguageVersion":"1.0","playerAttributes":[{"name":"skill","type":"number","default":0}],"teams":[{"name":"69","minPlayers":1,"maxPlayers":1},{"name":"420","minPlayers":1,"maxPlayers":1}],"rules":[{"name":"FairTeamSkill","description":"Range of 4","type":"distance","measurements":["teams[420].players.attributes[skill]"],"referenceValue":"max(teams[69].players.attributes[skill])","maxDistance":4}]}'
    GameLiftMatchmakingV3RuleSet:
      Type: AWS::GameLift::MatchmakingRuleSet
      Properties:
        Name: rps-gp-matchmaking-rule-set-v3
        RuleSetBody: '{"name":"app-matchmaking-ruleset","ruleLanguageVersion":"1.0","playerAttributes":[{"name":"skill","type":"number","default":0},{"name":"lastGameLobby","type":"string","default":""}],"teams":[{"name":"69","minPlayers":1,"maxPlayers":1},{"name":"420","minPlayers":1,"maxPlayers":1}],"rules":[{"name":"FairTeamSkill","description":"Range of 4","type":"distance","measurements":["teams[420].players.attributes[skill]"],"referenceValue":"max(teams[69].players.attributes[skill])","maxDistance":3},{"name":"DontPlaySamePlayer","description":"Ensure we dont match users up who just played eachother.","type":"comparison","operation":"!=","measurements":["flatten(teams[*].players.attributes[lastGameLobby])"]}]}'
    GameLiftMatchmakingV4RuleSet:
      Type: AWS::GameLift::MatchmakingRuleSet
      Properties:
        Name: rps-gp-matchmaking-rule-set-v4
        RuleSetBody: '{"name":"app-matchmaking-ruleset","ruleLanguageVersion":"1.0","playerAttributes":[{"name":"skill","type":"number","default":0},{"name":"BlockList","type":"string_list","default":[]}],"teams":[{"name":"69","minPlayers":1,"maxPlayers":1},{"name":"420","minPlayers":1,"maxPlayers":1}],"rules":[{"name":"FairTeamSkill","description":"Range of 4","type":"distance","measurements":["teams[420].players.attributes[skill]"],"referenceValue":"max(teams[69].players.attributes[skill])","maxDistance":3},{"name":"BlockList","type":"collection","operation":"reference_intersection_count","measurements":"flatten(teams[*].players.attributes[BlockList])","referenceValue":"flatten(teams[*].players[playerId])","maxCount":0}]}'
    GameLiftMatchmakingConfiguration:
      Type: AWS::GameLift::MatchmakingConfiguration
      Properties:
        AcceptanceRequired: false
        AdditionalPlayerCount: 0
        BackfillMode: MANUAL
        Description: Matchmaking configuration for RPS.
        FlexMatchMode: STANDALONE
        Name: rps-gp-matchmaking-configuration
        NotificationTarget: ${cf:sns-${sls:stage}.MatchmakingTopicArn}
        RequestTimeoutSeconds: ${self:custom.timeoutInSeconds.${sls:stage}}
        RuleSetName: !Ref GameLiftMatchmakingV4RuleSet
  Outputs:
    GameLiftMatchmakingConfigurationName:
      Value: !Ref GameLiftMatchmakingConfiguration

plugins:
  - serverless-plugin-monorepo

```

### Command name and used flags

sls deploy

### Command output

```shell
✖ Stack gamelift-dev failed to deploy (11s)
Publishing Service to the Serverless Framework Dashboard...
Successfully published your Service to the Serverless Framework Dashboard: https://app.serverless.com/<app_name>/apps/rps/gamelift/dev/us-east-1
Environment: darwin, node 16.17.0, framework 3.35.2 (local) 3.22.0v (global), plugin 7.0.2, SDK 4.4.0
Credentials: Serverless Framework Provider: "dev" (https://app.serverless.com/<app_name>/apps/rps/gamelift/dev/us-east-1/providers)
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Console server is unavailable, please try again later
```

### Environment information

```shell
Framework Core: 3.35.2 (local) 3.22.0 (global)
Plugin: 7.0.2
SDK: 4.4.0
```
