### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded for role (many lambdas with onFailure sqs destination)

### ISSUE THREAD

**Issue by colesiegel** [serverless/serverless#12167]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I add several functions to my project with an sqs failure destination set, deployment fails with error `Error:
UPDATE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role)
Maximum policy size of 10240 bytes exceeded for role xxx`

```
  eventHandler:
    timeout: 300
    handler: dist/app.eventHandler
    destinations:
      onFailure:
        type: sqs
        arn:
          Fn::GetAtt: ['EventHandlerDLQ', 'Arn']
```

The generated serverless IAM policy has an entry for `sqs:SendMessage` for every queue configured as an `onFailure` destination even though my IAM policy is already allowing these queues with a wildcard permission.

```
        {
            "Action": "sqs:SendMessage",
            "Resource": "arn:aws:sqs:xxx:xxx:test",
            "Effect": "Allow"
        },
        etc.
```

As a result deployment is failing because the IAM policy is very large.

### Service configuration (serverless.yml) content

```yaml
iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:TagQueue
            - sqs:GetQueueUrl
            - sqs:UntagQueue
            - sqs:PurgeQueue
            - sqs:ReceiveMessage
            - sqs:DeleteQueue
            - sqs:DeleteMessage
            - sqs:SendMessage
            - sqs:GetQueueAttributes
            - sqs:ListQueueTags
            - sqs:CreateQueue
          Resource: ${self:custom.config.sqsQueues.arnPrefix}*

functions:
  eventHandler:
    timeout: 300
    handler: dist/app.eventHandler
    destinations:
      onFailure:
        type: sqs
        arn:
          Fn::GetAtt: ['EventHandlerDLQ', 'Arn']

Resources:
  EventHandlerDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test
      MessageRetentionPeriod: 1209600
```

### Command name and used flags

N/A

### Command output

```shell
Error: UPDATE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role) Maximum policy size of 10240 bytes exceeded for role xxx
```

### Environment information

```shell
latest
```

**Comment by marcosleonel** [comment]
I had the same error. But it seems not the role created by the new resource (SQS in @colesiegel  case) permission itself but by a new function being added to the service role created automatically by Serverless Framework.

To deal with the error, I first split the default role into smaller ones to be attached at the function level. But then I realized that the role exceeding the size limit was the one created to the whole service to create and read logs of all lambda functions. Checking it in the AWS console I could see that the `<service name>-<region>-lambdaRole` permission has a long list of all lambda functions in my app in the `Resource`  array.

Looking into the Serverless Framework documentation I couldn't find a way to customize this role. Only options to customize the lambda roles are given.

Serverless Framework should provide I way to customize this service role or/and it should be split automatically after exceeding the 10240 bytes.

```bash
✖ Stack bjj-backend-dev failed to deploy (333s)
Environment: linux, node 16.16.0, framework 3.35.2 (local) 3.33.0v (global), plugin 7.0.5, SDK 4.4.0
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role)
Resource handler returned message: "Maximum policy size of 10240 bytes exceeded for role <service name>-<region>-lambdaRole (Service: Iam, Status Code: 409, Request ID: 43fb6d5c-570a-4413-8677-10cb6b7e29b3)" (RequestToken: e7400e6c-eea3-dad8-4a7d-f24480f08982, HandlerErrorCode: ServiceLimitExceeded)

```
``

**Comment by despinozap** [comment]
> I had the same error. But it seems not the role created by the new resource (SQS in @colesiegel case) permission itself but by a new function being added to the service role created automatically by Serverless Framework.
> 
> To deal with the error, I first split the default role into smaller ones to be attached at the function level. But then I realized that the role exceeding the size limit was the one created to the whole service to create and read logs of all lambda functions. Checking it in the AWS console I could see that the `<service name>-<region>-lambdaRole` permission has a long list of all lambda functions in my app in the `Resource` array.
> 
> Looking into the Serverless Framework documentation I couldn't find a way to customize this role. Only options to customize the lambda roles are given.
> 
> Serverless Framework should provide I way to customize this service role or/and it should be split automatically after exceeding the 10240 bytes.
> 
> ```shell
> ✖ Stack bjj-backend-dev failed to deploy (333s)
> Environment: linux, node 16.16.0, framework 3.35.2 (local) 3.33.0v (global), plugin 7.0.5, SDK 4.4.0
> Credentials: Local, environment variables
> Docs:        docs.serverless.com
> Support:     forum.serverless.com
> Bugs:        github.com/serverless/serverless/issues
> 
> Error:
> UPDATE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role)
> Resource handler returned message: "Maximum policy size of 10240 bytes exceeded for role <service name>-<region>-lambdaRole (Service: Iam, Status Code: 409, Request ID: 43fb6d5c-570a-4413-8677-10cb6b7e29b3)" (RequestToken: e7400e6c-eea3-dad8-4a7d-f24480f08982, HandlerErrorCode: ServiceLimitExceeded)
> ```
> 
> ``

hey there @marcosleonel! Were you capable of fix it? I'm currently stuck facing the same issue. I'd appreciate any tip. Thanks in advance 🙌 .

**Comment by jpacareu-locqube** [comment]
Hi guys did you solve this issue?

**Comment by jpacareu-locqube** [comment]
I found a solution/workaround with the help of Cursor, and the [docs](https://www.serverless.com/framework/docs/providers/aws/guide/iam#custom-iam-roles)

```yml
provider:
  iam:
    role: !GetAtt LambdaIAMRole.Arn

resources:
  Resources:
    LambdaIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
        Policies:
          - PolicyName: lambda-logs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:TagResource
                  Resource: 
                    - "arn:aws:logs:${self:provider.region}:${self:custom.vars.accountId}:log-group:/aws/lambda/<lambda_name>-*:*"
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - "arn:aws:logs:${self:provider.region}:${self:custom.vars.accountId}:log-group:/aws/lambda/<lambda_name>-*:*:*"
```

**Comment by talaikis** [comment]
Solution.

First, external policy:

```
provider:
  name: aws
  ...
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::${aws:accountId}:policy/PolicyName"
```

Second, remove options that can increase the policy size from functions (for example, onError, destination).
