### ISSUE TITLE
Lambda with referenced sqs onFailure destination fails deployment with ValidationException

### ISSUE THREAD

**Issue by colesiegel** [serverless/serverless#12165]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I reference an SQS queue in my lambda onFailure destination per (https://www.serverless.com/framework/docs/providers/aws/guide/functions#destinations), it fails to deploy with 400 error:

`
1 validation error detected: Value 'https://sqs.redacted-region.amazonaws.com/redacted-account-number/test' at 'destinationConfig.onFailure.destination' failed to satisfy constraint: Member must satisfy regular expression pattern: ^$|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*) (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: 8d30da38-098d-4fdb-9e34-88fede7b1e1b; Proxy: null)
`

From the looks of it, using Ref is pulling the queue URL when it should be getting the queue ARN.

### Service configuration (serverless.yml) content

```yaml
functions:
  eventHandler:
    timeout: 300
    handler: dist/app.eventHandler
    destinations:
      onFailure:
        type: sqs
        arn:
          Ref: 'EventHandlerDLQ'

Resources:
  EventHandlerDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test
      MessageRetentionPeriod: 1209600
```

### Command name and used flags

N/A

### Command output

```shell
1 validation error detected: Value 'https://sqs.redacted-region.amazonaws.com/redacted-account-number/test' at 'destinationConfig.onFailure.destination' failed to satisfy constraint: Member must satisfy regular expression pattern: ^$|arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*) (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: 8d30da38-098d-4fdb-9e34-88fede7b1e1b; Proxy: null)
```

### Environment information

```shell
latest
```

**Comment by colesiegel** [comment]
I think it relates to https://github.com/serverless/serverless/pull/10845 / https://github.com/serverless/serverless/issues/10799

**Comment by colesiegel** [comment]
I tried changing my `serverless.yml` to below but it fails with permission errors:

```
    destinations:
      onFailure:
        type: sqs
        arn:
          Fn::GetAtt: ['EventHandlerDLQ', 'Arn']
```

```
Error:
CREATE_FAILED: eventHandlerLambdaEvConf (AWS::Lambda::EventInvokeConfig)
The function's execution role does not have permissions to call SendMessage on arn:aws:sqs:redacted-region:************:test (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 150e3dcf-a5b5-4422-97f7-ecd5599a0a75; Proxy: null)
```

**Comment by colesiegel** [comment]
Got it working with the config below I think the documentation just needs to be a bit clearer

```
functions:
  eventHandler:
    timeout: 300
    handler: dist/app.eventHandler
    destinations:
      onFailure:
        type: sqs
        arn:
          Fn::GetAtt: ['EventHandlerDLQ', 'Arn']
```
