### ISSUE TITLE
Too many files opened (In latest node version, with latest serverless package)

### ISSUE THREAD

**Issue by abhim1509** [serverless/serverless#12171]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Too many files opened (In latest node version, with latest serverless package)

![image](https://github.com/serverless/serverless/assets/43211436/aea86697-ca94-44c3-b4e0-13d73c9355f5)

### Service configuration (serverless.yml) content

```yaml
frameworkVersion: "3"

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript
```

### Command name and used flags

serverless package

### Command output

```shell
Throws error
```

### Environment information

```shell
framework 3.34.0 (local) 3.35.2v (global)
```
