### ISSUE TITLE
resources.Rules property is unregonized

### ISSUE THREAD

**Issue by Itamaram** [serverless/serverless#12182]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Adding a `Rules` property to the `resources` section in a serverless yml file eg
```yml
resources:
  Rules:
    ValidateStage:
      Assertions:
        - Assert:
            'Fn::Contains':
              - - dev
                - int
              - ${self:provider.stage}
          AssertDescription: Stack must only be deployed in lower envs
```
Yields the following warning:
> Invalid configuration encountered at 'resources': unrecognized property 'Rules'

Despite it yielding the correct json:
```json
  "Rules": {
    "ValidateStage": {
      "Assertions": [
        {
          "Assert": {
            "Fn::Contains": [
              [
                "dev",
                "int"
              ],
              "dev"
            ]
          },
          "AssertDescription": "Stack must only be deployed in lower envs"
        }
      ]
    }
  }
```

(Which behaves correctly)

It appears this issue is just the validation of the serverless.yml file is incorrect, and the `Rule` property should be regonized.

### Service configuration (serverless.yml) content

```yaml
service: sample-service
configValidationMode: error

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Rules:
    ValidateStage:
      Assertions:
        - Assert:
            'Fn::Contains':
              - - dev
                - int
              - ${self:provider.stage}
          AssertDescription: Stack must only be deployed in lower envs
```

### Command name and used flags

serverless deploy

### Command output

```shell
Environment: win32, node 18.7.0, framework 3.35.2 (local), plugin 7.0.3, SDK 4.4.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Configuration error at 'resources': unrecognized property 'Rules'
```

### Environment information

```shell
Framework Core: 3.35.2 (local)
Plugin: 7.0.3
SDK: 4.4.0
```
