### ISSUE TITLE
Event Bus Policy should accept several actions or principals

### ISSUE THREAD

**Issue by nora-soderlund** [serverless/serverless#12199]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

An EventBusPolicy resource should be able to contain several actions or several principals, but serverless framework is not parsing this correctly.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbuspolicy.html (see the examples section)

### Service configuration (serverless.yml) content

```yaml
ExternalEventBusDomainPolicy:
    Type: AWS::Events::EventBusPolicy
    DependsOn: ExternalEventBus
    Properties:
      EventBusName:
        Ref: ExternalEventBus
      Action:
        - events:PutEvents
      Principal:
        - ${self:custom.domains.financing.accountId}
      StatementId: ${self:service}ExternalEventBusDomainPolicy
```

### Command name and used flags

serverless deploy --verbose

### Command output

Not posting complete output due to sensitive information.

```shell
CREATE_FAILED: ExternalEventBusDomainPolicy (AWS::Events::EventBusPolicy)
Property validation failure: [Value of property {/Action} does not match type {String}, Value of property {/Principal} does not match type {String}]
```

### Environment information

```shell
Framework Core: 3.31.0 (local)
Plugin: 6.2.3
SDK: 4.3.2
```
