### ISSUE TITLE
Docker push fails because of new (docker 24.0.0?) output from push command (missing sha256 digest) 

### ISSUE THREAD

**Issue by joepjoosten** [serverless/serverless#12192]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

After upgrading to latest docker engine (macos) version 24, the docker push command for pushing a function into aws ecs is failing, because the sha256 digest is not printed anymore by docker at the end of the push

### Service configuration (serverless.yml) content

```yaml
- Latest docker engine on macos (24.0.6 currently)
- A serverless config with a ecr image, and lambda using it:

 ecr: {
      images: {
        testHandler: {
          platform: 'linux/arm64',
          path: 'bin/src/test',
          file: 'Dockerfile',
        },
      },
    },
```
```


### Command name and used flags

serverless deploy

### Command output

```shell
TypeError: Cannot read properties of null (reading '0')
    at AwsProvider.Object.defineProperties.memoizeeMethods.resolveImageUriAndShaFromPath.d.promise (/User/me/project/node_modules/.pnpm/serverless@3.28.1_bufferutil@4.0.6_debug@4.3.4_utf-8-validate@5.0.5/node_modules/serverless/lib/plugins/aws/provider.js:2277:69)
1 deprecation found: run 'serverless doctor' for more details
Waiting for the debugger to disconnect...
Warning: run-commands command "sls deploy --stage shared" exited with non-zero status codeWaiting for the debugger to disconnect...
```

### Environment information

```shell
Framework Core: 3.28.1 (local)
Plugin: 6.3.0
SDK: 4.3.2
```
