### ISSUE TITLE
Multiple alb events doesn't create permissions for all target groups

### ISSUE THREAD

**Issue by perrefe** [serverless/serverless#12202]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

For a serverless function configuration with two alb events, the deployed function just have one trigger, the one related to the second alb in the list. It's expected that the resource based policy created for the function should contain both created target groups, but it only contains one.

```
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "dev-sandbox-alb-test-ServerlessDashfcnLambdaPermissionRegisterTarget-DtOzEOe1ApzI",
      "Effect": "Allow",
      "Principal": {
        "Service": "elasticloadbalancing.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:xxxxxxx:function:dev-sandbox-alb-test"
    },
    {
      "Sid": "dev-sandbox-alb-test-ServerlessDashfcnLambdaPermissionAlb-IDcWaxP1vJV1",
      "Effect": "Allow",
      "Principal": {
        "Service": "elasticloadbalancing.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:us-east-1:xxxxxxxxx:function:dev-sandbox-alb-test",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:elasticloadbalancing:us-east-1:xxxxxxxx:targetgroup/sandbox-lambda-tg-02/c943161561acc96d"
        }
      }
    }
  ]
}
```

### Service configuration (serverless.yml) content

```yaml
service: sandbox-alb-test

custom:
    stage: ${opt:stage, 'dev'}
    executionRole: sls-base-role
    settings:
        dev:
            environment: dev
        test:
            environment: test
        production:
            environment: prod

provider:
    name: aws
    region: us-east-1
    stage: ${self:custom.stage}
    stackName: ${self:custom.stage}-${self:service}
    runtime: nodejs18.x
    architecture: arm64
    versionFunctions: false
    iam:
        role: arn:aws:iam::${aws:accountId}:role/${self:custom.stage}-${self:custom.executionRole}

functions:
    serverless-fcn:
        name: ${self:custom.stage}-${self:service}
        handler: src/Handler.mainHandler
        memorySize: 128
        timeout: 20
        logRetentionInDays: 14
        events:
            - alb:
                listenerArn: arn:aws:elasticloadbalancing:us-east-1:xxxxxxx:listener/app/sandbox-alb/5d6e8fda366f73f6/8efb43601e013c6b
                targetGroupName: sandbox-lambda-tg-01
                priority: 1
                conditions:
                    path: "/test"
            - alb:
                listenerArn: arn:aws:elasticloadbalancing:us-east-1:xxxxxxx.listener/app/sandbox-alb-2/ec6863b87bf3ca03/14d78d4e11bb0628
                targetGroupName: sandbox-lambda-tg-02
                priority: 10
                conditions:
                    path: "/test"
```

### Command name and used flags

sls deploy

### Command output

```shell
Service deployed to stack dev-sandbox-alb-test
```

### Environment information

```shell
Framework Core: 3.35.2 (standalone)
Plugin: 7.0.2
SDK: 4.4.0
```
