### ISSUE TITLE
V3 Deployments Missing Layer for Serverless SDK

### ISSUE THREAD

**Issue by patricktyndall** [serverless/serverless#12207]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

**TLDR**
The Serverless SDK Lambda layer is not deploying with SDK V3. Are there any gotchas that would cause this layer not to be present on deployed lambdas? I've checked everything, and I am seeing no explanation for this; we're also encountering some inconsistencies with deploying to existing vs. new stages.

**Issue Detail**
Starting last Friday (2023-10-06), we're experiencing problems deploying our app using `sls deploy`. After deployment, our API suddenly started to 502. We've identified that the Lambda Layer for the serverless SDK is missing (Cloudwatch errors (nodeJS) also have `Cannot find module '@serverless/sdk'\nRequire stack:...`).

Additionally, we are experiencing very strange behaviors.
- The behavior is _different across stages_. Deploying to one (previously existing) stage works just fine (all lambdas have the sls-sdk-node-v0-15-14 layer after deployment). However, deploying to another pre-existing stage always results in missing layers. We're using the `-s` CLI option here. 
  - Even more worrying, deploying to a _new_ stage (calling sls deploy with a new stage name) always breaks; the created lambdas do not have a layer attached. 
- I also noticed that two deploys (both to new stages) resulted in different `Resource path` configuration in the Lambda console. 
  - One has `Resource path: /`, while the other has `Resource path: /{proxy+}`. Other values are the same.
 
Some usage information:
- Plugins: We're using serverless-prune-plugin (though I have disabled it in serverless.yml and the issue persists), and serverless-plugin-git-variables
- We do not have serverless SDK installed in our package.json; we're using a global installation as outlined in the migration guide.
- We have followed all other options in the migration guide as well, including listing `frameworkVersion: '3'` in serverless.yml

We've triple-checked all info in the [migration guide](https://www.serverless.com/framework/docs/guides/upgrading-v3), and we're complying with all the steps there.
- To reiterate -- we had successful deploys of all our existing stages using V3 up until this point, using the exact same version of our code/deployment workflow as we are no (though we had not tried creating a new stage).

I've listed relevant versions of software in the "Environment information".

<img width="1257" alt="image" src="https://github.com/serverless/serverless/assets/10466863/7b026cbb-8bba-4c18-8b03-a9d978ea40ff">

### Service configuration (serverless.yml) content

```yaml
# NOTE I've redacted some values here, but this is our configuration.
# Our complete service consists of ~30 lambdas all using either HTTP or cron event

app: my-app
service: my-app
frameworkVersion: '3'

plugins:
  - serverless-plugin-git-variables
  - serverless-prune-versions

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:stage}
  region: us-east-1
  role: arn:redacted
  timeout: 900
  vpc: ${self:custom.vpc-config}
  environment:
    stage: ${env:stage}
    my_var: ${env:my_var}

package:
  excludeDevDependencies: false
  individually: false
  exclude:
    - ./**
  include:
    - ./functions/**
    - ./node_modules/**
    - ./modules/**

custom:
  vpc-config:
    securityGroupIds:
      - sg-redacted
    subnetIds:
      - subnet-redacted
  # prune:
  #   automatic: true
  #   includeLayers: true # unused (we don't use layers) but recommended in prune-versions docs as best practice
  #   number: 3

functions:
  app:
    timeout: 29
    memorySize: 3008
    handler: functions/app/index.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

  myCron:
    handler: functions/crons/index.myCron
    reservedConcurrency: 1
    events:
      - schedule: cron(0 * ? * * *) # beginning of every hour
```

### Command name and used flags

serverless deploy -s beta --org my-org --verbose

### Command output

```shell
...
Service deployed to stack my-app-beta
...
```

### Environment information

```shell
Serverless:
Framework Core: 3.35.2
Plugin: 7.0.5
SDK: 4.4.0

Node:
v14.17.0

NPM:
6.14.13
```
