### ISSUE TITLE
Aws Python3.11 deployment issue with complex project and included yaml files.

### ISSUE THREAD

**Issue by Paul-J-Barrett** [serverless/serverless#12214]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Upgraded to newest serverless so I could upgrade my python lambdas and libraries to python3.11 from 3.8. Prior to upgrading and changing runtimes deployment was not an issue and has been working for over 2 years.

Also of note. After failing with error below the .serverless folder has all of the zip files and they are the proper sizes ie 1-3k and contain a single python file. But if I remove the '!./**' from the serverless.common.yaml file then it will deploy but all zip files are about 18M (contains all of the lamba functions) and one of the lambda functions would not run because it couldn't be found in the package.

I also started a discussion here https://github.com/serverless/serverless/discussions/12213 I was trying to solve myself but don't know enough about how to get a functioning debug environment running for serverless cli deployment. I Would love to figure that out as well if someone could make some suggestions or outline some steps in the discussion. Also FYI we use bitbucket pipelines also but have not tested there yet.

First version information that works and deploys properly with Python3.8 runtimes in the configs
PS C:\Users\myusername\source\upgrade311\dataservices\ingestion_pipeline> serverless --version
Running "serverless" from node_modules
Framework Core: 3.25.1 (local) 3.25.1 (global)
Plugin: 6.4.0
SDK: 4.4.0

I installed serverless latest globally also but it doesn't change the error outcome below. And when installed locally it should be using the local before global.

PS C:\Users\myusername\source\upgrade311\dataservices\ingestion_pipeline> npm install serverless@latest

added 87 packages, changed 6 packages, and audited 547 packages in 15s

74 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

PS C:\Users\myusername\source\upgrade311\dataservices\ingestion_pipeline> serverless --version
Running "serverless" from node_modules
Framework Core: 3.35.2 (local) 3.25.1 (global)
Plugin: 7.0.5
SDK: 4.4.0

When deploying the project with runtimes set to 3.11 I get this in essence. Complete output below.
     [message]: 'No file matches include / exclude patterns',
     code: 'NO_MATCHED_FILES',
     decoratedMessage: undefined,
     [name]: 'ServerlessError' },

Error:
No file matches include / exclude patterns

### Service configuration (serverless.yml) content

```yaml
Can not include complete files due to intellectual property. But included the important parts (patterns). The file was getting huge so we broke it up to aid management. A sample from the layers, lambdas, common, and the main serverless.yaml file are above. serverless and common are pretty much complete.


#serverless.yaml
frameworkVersion: "3"

service: dataservices-ingestion

resources:
  Resources:
    dataservicesrole:
      ${file(./serverless/serverless.roles.yaml):dataservicesrole}
provider:
  ${file(./serverless/serverless.common.yaml):provider}
plugins:
  ${file(./serverless/serverless.common.yaml):plugins}

custom:
  ${file(./serverless/serverless.common.yaml):custom}

package:
  ${file(./serverless/serverless.common.yaml):package}
layers:
  ${file(./serverless/serverless.layers.yaml):layers}


functions:
  - ${file(./serverless/serverless.lambda.yaml):functions}
  - ${file(./serverless/functions/stepfunctionstarter.yaml):functions}

stepFunctions:
  ${file(./serverless/serverless.stepfunctions.yaml):stepFunctions

  


#serverless.common.yaml
provider:
  name: aws
  role: dataservicesrole
  runtime: python3.11
  memorySize: 128
  timeout: 900
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'Dev'}
  tags:
    app: dataservices
    env: ${self:provider.stage}
  environment:
    APP_NAMESPACE: "/dataservices/${self:provider.stage}"
    APP_ENV: ${self:provider.stage}
  
plugins:
  - serverless-step-functions
custom:
  enabled:
    Dev: false
    Prod: true
  lowerStage:
    Dev: dev
    Prod: prod

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - "!./**"
    - "!__pycache__/**"
    - "!.pytest_cache/**"
    - "!all_test.sh"
    - "!Makefile"
    - "!test/**"
    - "!tests/**"
    - "!test*.py"
    - "!*.dist-info"
  
  
#Piece of serverless.layers.yaml
layers:
  GeneralFunctions:
    path: lambda_layers/utils
    package:
      patterns:
        - "./**"
    name: GeneralFunctions-${self:provider.stage}
	
	
#Piece of serverless.lambda.yaml
functions:
  GetJobConfig:
    handler: orchestration_lambdas/get_job_config/get_job_config.handler
    layers:
      - { Ref: GeneralFunctionsLambdaLayer }
      - { Ref: PydanticLambdaLayer }
    package:
      patterns:
        - "orchestration_lambdas/get_job_config/**"
    environment:
      S3_CONFIG_BUCKET: somebucket-${self:provider.stage}
```

### Command name and used flags

serverless deploy --stage Dev --debug * --verbose --force; date

### Command output

```shell
Running "serverless" from node_modules
config: Retrieve local config, auth data undefined
config: Retrieve global config, auth data undefined
process: resolve CLI input (no service schema)
process: resolve CLI input (service schema)
process: resolve eventual service configuration
process: service configuration found at C:\\Users\\myusername\\source\\upgrade311\\dataservices\\ingestion_pipeline\\serverless.yaml
process: service configuration file successfully parsed
process: resolve variables meta
process: resolve variables in core properties
process: resolve CLI input (AWS service schema)
process: resolve variables in core properties #2
process: resolve variables in all properties
process: resolve CLI input (AWS service schema)
process: construct Serverless instance
process: initialize Serverless instance
lifecycle:command:register: config
lifecycle:command:register: config:credentials
lifecycle:command:register: create
lifecycle:command:register: install
lifecycle:command:register: package
lifecycle:command:register: package:function
lifecycle:command:register: deploy
lifecycle:command:register: deploy:function
lifecycle:command:register: deploy:list
lifecycle:command:register: deploy:list:functions
lifecycle:command:register: invoke
lifecycle:command:register: invoke:local
lifecycle:command:register: info
lifecycle:command:register: logs
lifecycle:command:register: metrics
lifecycle:command:register: print
lifecycle:command:register: remove
lifecycle:command:register: rollback
lifecycle:command:register: rollback:function
lifecycle:command:register: slstats
lifecycle:command:register: plugin
lifecycle:command:register: plugin
lifecycle:command:register: plugin:list
lifecycle:command:register: plugin
lifecycle:command:register: plugin:search
lifecycle:command:register: config
lifecycle:command:register: config:credentials
lifecycle:command:register: aws
lifecycle:command:register: aws:common
lifecycle:command:register: aws:common:validate
lifecycle:command:register: aws:common:cleanupTempDir
lifecycle:command:register: aws:common:moveArtifactsToPackage
lifecycle:command:register: aws:common:moveArtifactsToTemp
lifecycle:command:register: aws
lifecycle:command:register: aws:package
lifecycle:command:register: aws:package:finalize
lifecycle:command:register: aws
lifecycle:command:register: aws:deploy
lifecycle:command:register: aws:deploy:deploy
lifecycle:command:register: aws:deploy:finalize
lifecycle:command:register: aws
lifecycle:command:register: aws:info
lifecycle:command:register: upgrade
lifecycle:command:register: uninstall
lifecycle:command:register: invoke
lifecycle:command:register: invoke:stepf
lifecycle:command:register: login
lifecycle:command:register: logout
lifecycle:command:register: generate-event
lifecycle:command:register: test
lifecycle:command:register: dashboard
lifecycle:command:register: output
lifecycle:command:register: output:get
lifecycle:command:register: output:list
lifecycle:command:register: param
lifecycle:command:register: param:get
lifecycle:command:register: param:list
process: resolve CLI input (+ plugins schema)
process: run Serverless instance

Deploying dataservices-ingestion to stage Dev (us-xxxxxx-2)

aws: [1] { name: 'STS',
  params:
   { credentials:
      SharedIniFileCredentials {
        expired: false,
        expireTime: null,
        refreshCallbacks: [],
        accessKeyId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        sessionToken: undefined,
        filename: undefined,
        profile: 'default',
        disableAssumeRole: false,
        preferStaticCredentials: false,
        tokenCodeFn: [Function (anonymous)],
        httpOptions: null },
     region: 'us-xxxxxx-2',
     isS3TransferAccelerationEnabled: false } } getCallerIdentity [ {} ]
lifecycle:command:invoke: Invoke deploy
lifecycle:command:invoke:hook: [1] < before:deploy:deploy
lifecycle:command:invoke: Invoke package
lifecycle:command:invoke:hook: [2]   < before:package:cleanup
Packaging
lifecycle:command:invoke:hook: [2]   > before:package:cleanup
lifecycle:command:invoke:hook: [3]   < package:cleanup
lifecycle:command:invoke: Invoke aws:common:validate
lifecycle:command:invoke:hook: [5]     < aws:common:validate:validate
lifecycle:command:invoke:hook: [5]     > aws:common:validate:validate
lifecycle:command:invoke: Invoke aws:common:cleanupTempDir
lifecycle:command:invoke:hook: [8]     < aws:common:cleanupTempDir:cleanup
lifecycle:command:invoke:hook: [8]     > aws:common:cleanupTempDir:cleanup
lifecycle:command:invoke:hook: [3]   > package:cleanup
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [15]   < package:setupProviderConfiguration
lifecycle:command:invoke:hook: [15]   > package:setupProviderConfiguration
lifecycle:command:invoke:hook: [18]   < package:createDeploymentArtifacts
lifecycle:command:invoke:hook: [18]   > package:createDeploymentArtifacts
lifecycle:command:invoke:hook: [1] > before:deploy:deploy

× Stack dataservices-ingestion-Dev failed to deploy (0s)
process: handle error
process: finalize { error:
   { ServerlessError: No file matches include / exclude patterns
       at C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:317:13
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
       at async Package.packageFunction (C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:193:23)
       at async C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:100:9
       at async Promise.all (index 32)
       at async Package.packageService (C:\Users\myusername\node_modules\serverless\lib\plugins\package\lib\package-service.js:129:5)
       at async PluginManager.runHooks (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:530:9)
       at async PluginManager.invoke (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:564:9)
       at async PluginManager.spawn (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:585:5)
       at async before:deploy:deploy (C:\Users\myusername\node_modules\serverless\lib\plugins\deploy.js:48:11)
       at async PluginManager.runHooks (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:530:9)
       at async PluginManager.invoke (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:563:9)
       at async PluginManager.run (C:\Users\myusername\node_modules\serverless\lib\classes\plugin-manager.js:604:7)
       at async Serverless.run (C:\Users\myusername\node_modules\serverless\lib\serverless.js:179:5)
       at async C:\Users\myusername\node_modules\serverless\scripts\serverless.js:819:9
     [stack]:
      'ServerlessError: No file matches include / exclude patterns\n    at C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:317:13\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Package.packageFunction (C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:193:23)\n    at async C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:100:9\n    at async Promise.all (index 32)\n    at async Package.packageService (C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\package\\lib\\package-service.js:129:5)\n    at async PluginManager.runHooks (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:530:9)\n    at async PluginManager.invoke (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:564:9)\n    at async PluginManager.spawn (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:585:5)\n    at async before:deploy:deploy (C:\\Users\\myusername\\node_modules\\serverless\\lib\\plugins\\deploy.js:48:11)\n    at async PluginManager.runHooks (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:530:9)\n    at async PluginManager.invoke (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:563:9)\n    at async PluginManager.run (C:\\Users\\myusername\\node_modules\\serverless\\lib\\classes\\plugin-manager.js:604:7)\n    at async Serverless.run (C:\\Users\\myusername\\node_modules\\serverless\\lib\\serverless.js:179:5)\n    at async C:\\Users\\myusername\\node_modules\\serverless\\scripts\\serverless.js:819:9',
     [message]: 'No file matches include / exclude patterns',
     code: 'NO_MATCHED_FILES',
     decoratedMessage: undefined,
     [name]: 'ServerlessError' },
  shouldBeSync: undefined,
  telemetryData: undefined,
  shouldSendTelemetry: undefined }
Environment: win32, node 16.14.2, framework 3.35.2 (local) 3.25.1v (global), plugin 7.0.5, SDK 4.4.0
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
No file matches include / exclude patterns

1 deprecation found: run 'serverless doctor' for more details
config: Retrieve local config, auth data undefined
config: Retrieve global config, auth data undefined
config: Retrieve local config, auth data undefined
config: Retrieve global config, auth data undefined
config: Retrieve local config, auth data undefined
config: Retrieve global config, auth data undefined
config: Retrieve local config, auth data undefined
config: Retrieve global config, auth data undefined
telemetry: payload { ciName: null,
  isTtyTerminal: true,
  isDockerInstalled: true,
  dockerVersion: '20.10.24',
  cliName: 'serverless',
  command: 'deploy',
  commandOptionNames: [ 'stage', 'debug', 'region', [length]: 3 ],
  dashboard: { userId: null, orgUid: undefined },
  firstLocalInstallationTimestamp: 1697218364,
  frameworkLocalUserId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  installationType: 'local:fallback',
  isAutoUpdateEnabled: false,
  isUsingCompose: false,
  notificationsMode: 'on',
  timestamp: 1697495877849,
  timezone: 'America/Los_Angeles',
  triggeredDeprecations: [ 'PROVIDER_IAM_SETTINGS_V3', [length]: 1 ],
  versions: { serverless: '3.35.2', '@serverless/dashboard-plugin': '7.0.5' },
  commandDurationMs: 5716,
  hasLocalCredentials: true,
  npmDependencies: [ [length]: 0 ],
  config:
   { configValidationMode: 'warn',
     provider: { name: 'aws', runtime: 'python3.11', stage: 'Dev', region: 'us-west-2' },
     variableSources: [ 'file', 'opt', 'self', [length]: 3 ],
     plugins: [ 'serverless-step-functions', [length]: 1 ],
     functions:
      [ { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: '$containerimage', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: '$containerimage', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [length]: 0 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        { url: false, runtime: 'python3.11', events: [ [Object], [length]: 1 ] },
        [length]: 63 ],
     resources: { general: [ 'AWS::IAM::Role', [length]: 1 ] },
     paramsCount: 0 },
  isConfigValid: true,
  didCreateService: false,
  commandUsage: {} }
aws: [1] { ResponseMetadata: { RequestId: 'xxxxxxxxxxxxxxxxxxxxxxx' },
  UserId: 'xxxxxxxxxxxxxxxxxxxxx',
  Account: 'xxxxxxxxxxxxxxxxxxxxxx',
  Arn: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' }
```

### Environment information

```shell
PS C:\Users\myusername\source\upgrade311\dataservices\ingestion_pipeline> serverless --version
Running "serverless" from node_modules
Framework Core: 3.35.2 (local) 3.25.1 (global)   ----> I tried also with npm install -g serverless@latest got same issue.
Plugin: 7.0.5
SDK: 4.4.0
```
