### ISSUE TITLE
folded strings are converted to block literals for no reason

### ISSUE THREAD

**Issue by pkit** [serverless/serverless#12226]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The perfectly valid folded yaml:
```yaml
provider:
  logs:
    restApi:
      format: >-
        {
           "some": "format"
        }
```
gets converted to a valid but different yaml:
```yaml
provider:
  logs:
    restApi:
      format: |-
        {
           "some": "format"
        }
```
Unfortunately this example then fails to deploy as AWS log format MUST be one line. Which it is in the original. And is not - in the "re-formatted" one.

The funny fact that if we use the string literal:
```yaml
provider:
  logs:
    restApi:
      format: '.....very very long string....'
```
It gets "re-formatted" into:
```yaml
provider:
  logs:
    restApi:
      format: >-
        .....very 
        very long 
        string....
```
Which is ok. But it would be better not to mangle the original `>-` folded format.

### Service configuration (serverless.yml) content

```yaml
See above
```

### Command name and used flags

sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```
