### ISSUE TITLE
Cannot resolve serverless.yml: Variables resolution errored when seems to be correctly described

### ISSUE THREAD

**Issue by MathRobin** [serverless/serverless#12235]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi, i get this error when trying to deploy :

```
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.NODE_ENV": The param "NODE_ENV" cannot be resolved from CLI options or stage params. If you are using Serverless Framework Compose, make sure to run commands via Compose so that all parameters can be resolved
```
I tried to get help through chat but still stucked.

You can see full process into screenshot attached. Another screenshot shows NODE_ENV is well defined at good place. So I don't understand why I'm stucked.

![2023-11-06_15-00](https://github.com/serverless/serverless/assets/1046585/358c2244-7cdd-4666-9f49-f79e2d8678ce)
![2023-11-06_15-47](https://github.com/serverless/serverless/assets/1046585/91be487f-f541-4a31-8259-2cbfca534566)

Thanks in advance!

### Service configuration (serverless.yml) content

```yaml
service: slack-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  environment:
    NODE_ENV: ${param:NODE_ENV}
plugins: []
functions:
  statusGet:
    handler: handler.statusGet
    timeout: 29
    events:
      - httpApi:
          path: /status
          method: get
```

### Command name and used flags

serverless deploy

### Command output

```shell
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.NODE_ENV": The param "NODE_ENV" cannot be resolved from CLI options or stage params. If you are using Serverless Framework Compose, make sure to run commands via Compose so that all parameters can be resolved
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.36.0 (local) 3.36.0 (global)
Plugin: 7.1.0
SDK: 4.4.0
```

**Comment by yeukfei02** [comment]
```
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  environment:
    NODE_ENV: ${param:NODE_ENV}
```

@MathRobin 
in serverless dashboard, did you add in parameters into your service?
