### ISSUE TITLE
Cannot create/attach aws managed policy

### ISSUE THREAD

**Issue by ashishjullia** [serverless/serverless#12244]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

With the attached `serverless.yml` when I'm running `sls print`, it gives me:

```yaml
service: test-service
frameworkVersion: '3'
custom:
  stage: staging
  accountMapping:
    staging: 'xxxxxxxxxxxxxx'
    prod: 'xxxxxxxxxxxxxx'
  accountId: 'xxxxxxxxxxxxxx'
  regions:
    prod: us-east-1
    staging: us-east-1
  deploymentBucket:
    staging:
      name: test-service-staging-1-slsdeploymentbucket
    prod:
      name: test-service-prod-slsdeploymentbucket
    versioning: true
    blockPublicAccess: true
    accessLog: false
    accelerate: false
  permissions:
    prod:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:dev
    staging:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:dev
  managedPolicyArns:
    staging:
      - arn:aws:iam::aws:policy/AmazonEMRReadOnlyAccessPolicy_v2
      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
    prod:
      - arn:aws:iam::aws:policy/AmazonEMRReadOnlyAccessPolicy_v2
      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
provider:
  name: aws
  runtime: python3.7
  stage: staging
  memorySize: 512
  timeout: 900
  lambdaHashingVersion: '20201221'
  deploymentBucket: test-service-staging-1-slsdeploymentbucket
  region: us-east-1
  environment:
    DYNAMO_TABLE_NAME: dev
  ecr:
    scanOnPush: true
    images:
      customimage:
        path: .
        buildArgs:
          STAGE: staging
        platform: linux/amd64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:dev
      managedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEMRReadOnlyAccessPolicy_v2
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
  stackTags:
    Environment: staging
    Project: test-service
  versionFunctions: true
  deploymentBucketObject:
    name: test-service-staging-1-slsdeploymentbucket
functions:
  test-service:
    memorySize: 512
    image:
      name: customimage
    events: []
    name: test-service-staging-test-service
plugins:
  - serverless-deployment-bucket
  - serverless-tag-resources

```

And the values inside the file look completely right but when I'm actually deploying it, it is not attaching the aws managed policies to the lambda execution role and only the stements (customer inline).

 Note: The AWS IAM user which which I am running/deploying it, it has ADMIN level permissions.

### Service configuration (serverless.yml) content

```yaml
# Service name
service: test-service
frameworkVersion: "3"

custom:
  stage: ${opt:stage, self:provider.stage}
  accountMapping:
    staging: 'xxxxxxxxxxxxxx'
    prod: 'xxxxxxxxxxxxxx'
  accountId: ${self:custom.accountMapping.${self:custom.stage}}
  regions:
    prod: us-east-1
    staging: us-east-1
  deploymentBucket:
    # <service-name>-<stage>-<version>-<slsdeploymentbucket>
    staging:
      name: test-service-staging-1-slsdeploymentbucket
    prod:
      name: test-service-prod-slsdeploymentbucket
    versioning: true
    blockPublicAccess: true
  permissions:
    prod:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:dev
    staging:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:dev
  managedPolicyArns:
    staging:
      - arn:aws:iam::aws:policy/AmazonEMRReadOnlyAccessPolicy_v2
      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
    prod:
      - arn:aws:iam::aws:policy/AmazonEMRReadOnlyAccessPolicy_v2
      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess

# Provider settings
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'staging'} # Default to 'staging' if no stage is provided
  memorySize: 512
  timeout: 900  # 15 minutes
  lambdaHashingVersion: 20201221
  deploymentBucket: 
    name: ${self:custom.deploymentBucket.${self:provider.stage}.name}
  region: ${self:custom.regions.${self:provider.stage}}
  environment:
    DYNAMO_TABLE_NAME: ${env:DYNAMO_TABLE_NAME}
  ecr:
    scanOnPush: true
    images:
      customimage:
        path: .
        buildArgs:
          STAGE: ${sls:stage}
        platform: linux/amd64
  iam:
    role:
      statements: ${self:custom.permissions.${self:custom.stage}}
      managedPolicyArns: ${self:custom.managedPolicyArns.${self:custom.stage}}
  stackTags:
    Environment: ${self:provider.stage}
    Project: test-service

functions:
  test-service:
    memorySize: 512
    image:
      name: customimage

plugins:
  - serverless-deployment-bucket
  - serverless-tag-resources
```

### Command name and used flags

sls deploy --stage=staging

### Command output

```shell
(node:85290) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

Warning: Invalid configuration encountered
  at 'provider.iam.role': unsupported object format

Learn more about configuration validation here: http://slss.io/configuration-validation
Removing test-service from stage staging (us-east-1)

✔ Service test-service has been successfully removed (27s)
```

### Environment information

```shell
Framework Core: 3.36.0
Plugin: 7.1.0
SDK: 4.4.0
```

**Comment by ashishjullia** [comment]
My bad, I was using the wrong value, here is the correct format:

```yaml
  iam:
    role:
      statements: ${self:custom.permissions.${self:custom.stage}}
      managedPolicies: ${self:custom.managedPolicyArns.${self:custom.stage}}
```
