### ISSUE TITLE
Add support for Ipv6AllowedForDualStack in vpc config

### ISSUE THREAD

**Issue by bryceml** [serverless/serverless#12253]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

When adding ipv6AllowedForDualStack, it doesn't work

```yaml
    vpc:
      securityGroupIds: ${self:custom.SecurityGroups}
      subnetIds: ${self:custom.SubnetIds}
      ipv6AllowedForDualStack: true
```

it outputs:

```
Warning: Invalid configuration encountered
  at 'functions.bob.vpc': unrecognized property 'ipv6AllowedForDualStack'
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-vpcconfig.html
