### ISSUE TITLE
Provider runtime nodejs20.x is missing

### ISSUE THREAD

**Issue by ad-si** [serverless/serverless#12252]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When setting `provider.runtime` to `` I'm getting following warning: 
```txt
Warning: Invalid configuration encountered
  at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.7, python3.8, python3.9, python3.10, python3.11, ruby2.7, ruby3.2]
```
However, it deploys just fine and lists Node.js 20 as the used runtime in AWS Lambda.
  

### Service configuration (serverless.yml) content

```yaml
service: cron-execute
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  cronHandler:
    handler: src/test.main
    events:
      - schedule: cron(0/10 * * * ? *)
```

### Command name and used flags

serverless deploy

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.36.0 (local)
Plugin: 7.1.0
SDK: 4.4.0
```
