### ISSUE TITLE
EventBridge - Lambda invoke permission have wrong sourceArnformat

### ISSUE THREAD

**Issue by janithaaws** [serverless/serverless#12257]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I am trying to use a custom event bus as events for my lambda functions. In my case, I created the custom bus using a different serverless application and referred to it using the arn.
Upon deployment, everything is created without any errors, and rules are created along the lambda functions. But when there are events on the event bus, although the rule is triggered I noticed that the lambda function is never triggered.
Upon further inspection, I found the error is on Lambda Invoke Permission where the format of the sourceArn is incorrect.

ARN in the lambda
`arn:aws:events:us-east-1:XXXXXXXXXX:rule/arn:aws:events:us-east-1:XXXXXXXXXXX:event-bus/boost-trigger-event-bus-dev/test-rule-dev`

But when I manually edit it on the lambda console to follow it works perfectly
`arn:aws:events:us-east-1:XXXXXXXXXXXXXX:rule/boost-trigger-event-bus-dev/test-rule-dev`

In order to check why this is happening I went through the cloud formation stack created by serverless and found where it is generated.

```javascript
"TestTriggerEventBridgeLambdaPermission1": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "FunctionName": {
          "Fn::GetAtt": [
            "TestTriggerLambdaFunction",
            "Arn"
          ]
        },
        "Principal": "events.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            ":",
            [
              "arn",
              {
                "Ref": "AWS::Partition"
              },
              "events",
              {
                "Ref": "AWS::Region"
              },
              {
                "Ref": "AWS::AccountId"
              },
              {
                "Fn::Join": [
                  "/",
                  [
                    "rule",
                    {
                      "Fn::ImportValue": "trigger-event-bus-arn-output-dev"
                    },
                    "test-rule-dev"
                  ]
                ]
              }
            ]
          ]
        }
      }
    },
``` 
I tried with setting `useCloudFormation: true` but still the same issue.

### Service configuration (serverless.yml) content

```yaml
testTrigger: {
    handler: `src/functions/automation/triggers/test/handler.main`,
    events: [
      {
        eventBridge: {
          name: 'test-rule-${sls:stage}',
          eventBus: { 'Fn::ImportValue': 'trigger-event-bus-arn-output-${sls:stage}' },
          pattern: {
            source: ['test-${sls:stage}'],
          },
        },
      },
    ],
  },
};
```

### Command name and used flags

sls deploy

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```
