### ISSUE TITLE
Serverless v3.36.0,Error: The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions

### ISSUE THREAD

**Issue by dhruvkumar456** [serverless/serverless#12258]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hi all,

Getting below error while deploying my serverless project to aws, even after using latest serverless version:

```
✖ Stack serverless-services-qa failed to deploy (351s)
Environment: darwin, node 16.20.1, framework 3.36.0 (local), plugin 7.1.0, SDK 4.4.0
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: WarmUpPluginLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 0ac45980-7624-4db4-97c3-da0f22351ce5)" (RequestToken: f4731e48-f80e-dac2-3732-b77d2ac75bad, HandlerErrorCode: InvalidRequest)

View the full error: https://ap-south-1.console.aws.amazon.com/cloudformation/home?region=ap-south-1#/stack/detail?XXXXXXXXXXXXXXX
```

Package.json file:
```
{
  "name": "aws-nodejs-typescript",
  "version": "1.0.0",
  "description": "Serverless webpack example using Typescript",
  "main": "handler.js",
  "scripts": {
    "dev": "sls offline --stage qa",
    "test": "tsc && mocha build/test/*/*.js --timeout 10000",
    "code_coverage": "tsc && nyc --reporter=html --reporter=text  mocha build/test/*/*.js --timeout 10000 --reporter mochaReport"
  },
  "resolutions": {
    "terser": "3.14.1"
  },
  "dependencies": {
    "@types/bluebird": "3.5.30",
    "@types/mongoose": "^5.11.97",
    "aws-sdk": "2.517.0",
    "axios": "0.19.0",
    "crypto": "1.0.1",
    "elasticsearch": "^16.7.3",
    "fuzzball": "1.3.0",
    "handlebars": "4.5.3",
    "jsonschema": "1.2.4",
    "lodash": "4.17.5",
    "moment": "2.24.0",
    "moment-timezone": "0.5.26",
    "mongoose": "5.6.9",
    "mongoose-delete": "0.5.0",
    "mongoose-paginate-v2": "^1.7.1",
    "path": "0.12.7",
    "request": "2.88.2",
    "request-promise": "4.2.4",
    "serverless-domain-manager": "3.3.0",
    "uuid": "^9.0.0",
    "xlsx": "0.14.4",
    "xml-stream": "0.4.5",
    "xml2js": "0.4.23"
  },
  "devDependencies": {
    "@babel/core": "7.8.7",
    "@babel/preset-env": "7.8.7",
    "@types/aws-lambda": "8.10.17",
    "@types/mocha": "5.2.7",
    "@types/node": "10.17.17",
    "@types/uuid": "^9.0.0",
    "babel-loader": "8.0.6",
    "chai": "4.2.0",
    "copy-webpack-plugin": "5.1.1",
    "core-js": "3.6.4",
    "mocha": "6.2.0",
    "nock": "10.0.6",
    "nyc": "14.1.1",
    "serverless": "3.36.0",
    "serverless-offline": "5.12.1",
    "serverless-plugin-warmup": "4.8.0",
    "serverless-webpack": "5.9.0",
    "sinon": "7.4.1",
    "sinon-chai": "3.3.0",
    "sinon-mongoose": "2.3.0",
    "ts-loader": "5.3.3",
    "typescript": "3.2.4",
    "webpack": "4.41.5"
  },
  "author": "The serverless webpack authors (https://github.com/elastic-coders/serverless-webpack)",
  "license": "MIT"
}
```

### Service configuration (serverless.yml) content

```yaml
service: serverless-services

package:
  individually: true

# Add the serverless-webpack plugin

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-warmup
  - serverless-offline
provider:
  name: aws
  versionFunctions: false
  region: ap-south-1
  runtime: nodejs16.x
  stage: ${opt:stage}
  vpc:
    securityGroupIds:
      - ${file(./secrets.yml):${opt:stage}.SECURITY_GROUP}
    subnetIds:
      - ${file(./secrets.yml):${opt:stage}.SUBNET}
  role: arn:aws:iam::830068832459:role/Tripeur-Lambda-Role
  deploymentBucket:
    name: ${self:custom.bucketname}

  environment:
    ENV: ${file(./secrets.yml):${opt:stage}.ENV}
    MAIN_URL: ${file(./secrets.yml):${opt:stage}.MAIN_URL}
    # MANY MORE SECRETS

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'access-token,Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

custom:  
  stage: ${opt:stage, self:provider.stage}
  warmup:
    enabled: true
    folderName: '_warmup'
    cleanFolder: false
    name: 'service-${opt:stage, self:provider.stage}-warmup'
    events:
      - schedule: cron(0/12 8-17 ? * MON-FRI *)
    prewarm: true
  domains:
    prod: XXX
    stage: XXXX
    qa: XXX
    dev: XXX
    qa2: XXX
  customDomain:
    basePath: "services"
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true
    serverless-offline:
      httpsProtocol: "dev-certs"
      port: 4000
  bucketname: tripeur-${opt:stage}-deployment-artifacts
  
functions:

  mapUnmapAmenities:
    handler: functions/masterAmenities/index.mapUnmapAmenities
    warmup:
      enabled: false

  
  dedupe:
    handler: functions/dedupe/index.dedupe
    warmup:
      enabled: true

  # MANY MORE FUNCTION with warmup enabled: true/false
```

### Command name and used flags

node ./node_modules/serverless/bin/serverless.js deploy --stage qa | tee logs4.txt

### Command output

```shell
.......
Warning: You're using the AWS_PROXY in combination with response configuration in your function "getSearchHistory". Serverless will remove this configuration automatically before deployment.

✖ Stack serverless-hotels-qa failed to deploy (351s)
Environment: darwin, node 16.20.1, framework 3.36.0 (local), plugin 7.1.0, SDK 4.4.0
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: WarmUpPluginLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 0ac45980-7624-4db4-97c3-da0f22351ce5)" (RequestToken: f4731e48-f80e-dac2-3732-b77d2ac75bad, HandlerErrorCode: InvalidRequest)

View the full error: https://ap-south-1.console.aws.amazon.com/cloudformation/home?region=ap-south-1#/stack/detail?XXXXX
```

### Environment information

```shell
"node ./node_modules/serverless/bin/serverless.js --version" output:

Framework Core: 3.36.0 (local)
Plugin: 7.1.0
SDK: 4.4.0
```
