### ISSUE TITLE
S3 event on existing bucket creates "old" nodejs16 function, should be configurable / up to date

### ISSUE THREAD

**Issue by janik6n** [serverless/serverless#12265]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

When Lambda function is configured to use S3 event trigger (Nodejs20.x runtime) with existing bucket, the additional Lambda function described here https://www.serverless.com/framework/docs/providers/aws/events/s3 `Using existing buckets` is always created with nodejs16.x runtime.

Example configuration:
```yaml
events:
      - s3:
          bucket: ${param:myBucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .xml
          existing: true
          forceDeploy: true
```

The runtime for this additional function should be:
a) configurable
b) use `${self:provider.runtime}` as default.

Nodejs 16 runtime will be deprecated next year (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), and I would like to have my function runtimes up to date.
