### ISSUE TITLE
Deploy fails on mobile network

### ISSUE THREAD

**Issue by 23navi** [serverless/serverless#12266]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

`Recoverable error occurred (write EPIPE), sleeping for ~5 seconds. Try 1 of 4`
When trying to deploy the service using `sls deploy` on my wifi network with 100Mbps it works fine but when I try to deploy the service using my mobile network (Hotspot) with either 4G or 5G with (~40Mbps) speed, I get this retrying error.

### Service configuration (serverless.yml) content

```yaml
service: auction-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: GET
          path: /auction

custom:
  bundle:
    linting: false
```

### Command name and used flags

sls deploy 

### Command output

```shell
➜  auction-service git:(auction) ✗ sls deploy --verbose
Running "serverless" from node_modules

Deploying auction-service to stage dev (ap-south-1)

Packaging
Excluding development dependencies for service package
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service auction-service.zip file to S3 (16.09 MB)
Recoverable error occurred (write EPIPE), sleeping for ~5 seconds. Try 1 of 4
```

### Environment information

```shell
➜  Serverless git:(auction) ✗ sls -v
Running "serverless" from node_modules
Framework Core: 3.37.0 (local) 3.37.0 (global)
Plugin: 7.2.0
SDK: 4.5.1
```
