### ISSUE TITLE
Missing support of nodejs20.x runtime (new runtime available at AWS Lambda for Node) 

### ISSUE THREAD

**Issue by roland-pep** [serverless/serverless#12269]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Starting from 15 November 2023, a new Node runtime version for AWS Lamba is available, "node20.x". See [Node.js 20.x runtime now available in AWS Lambda](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/) for the news release.

Running sls info in a project that refers to the nodejs20.x runtime in the provider section of the serverless.yml returns:

> Warning: Invalid configuration encountered
>   at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.7, python3.8, python3.9, python3.10, python3.11, ruby2.7, ruby3.2]

### Service configuration (serverless.yml) content

```yaml
...
provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, self:custom.default.region}
  stage: ${opt:stage, self:custom.default.stage}
  timeout: 30
  memorySize: 3008
  versionFunctions: true
  environment:
    NODE_ENV: production
...
```

### Command name and used flags

sls info

### Command output

```shell
Warning: Invalid configuration encountered
  at 'provider.runtime': must be equal to one of the allowed values [dotnet6, go1.x, java17, java11, java8, java8.al2, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.7, python3.8, python3.9, python3.10, python3.11, ruby2.7, ruby3.2]
```

### Environment information

```shell
Running "serverless" from node_modules
Framework Core: 3.36.0 (local) 3.36.0 (global)
Plugin: 7.1.0
SDK: 4.4.0
```
