### ISSUE TITLE
Enable LoggingConfig configuration on Lambda Functions

### ISSUE THREAD

**Issue by samchungy** [serverless/serverless#12264]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

https://aws.amazon.com/blogs/compute/introducing-advanced-logging-controls-for-aws-lambda-functions/

Recently announced, would be nice to be able to configure

**Comment by ryy** [comment]
Looking at the documentation, it seems that defining [LoggingConfig](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-loggingconfig.html) is a good idea.

What about the following settings?

```
functions:
  hello:
    ...
    loggingConfig:
      ApplicationLogLevel: <value>
      LogFormat: <value>
      LogGroup: <value>
      SystemLogLevel: <value>
```

Also can I work on this?
