### ISSUE TITLE
Malformed policy being created in Cloudformation template on deploy

### ISSUE THREAD

**Issue by mdelclaro** [serverless/serverless#12276]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

`The CloudFormation template is invalid: Template error: instance of Fn::Sub references invalid resource attribute WebBucket.Arn` when tryinig to deploy with `sls deploy`. This is the invalid policy being created under `LogBucketPolicy`:

```
            {
              "Effect": "Deny",
              "Principal": "*",
              "Action": "s3:*",
              "Resource": [
                {
                  "Fn::Sub": "${WebBucket.Arn}/*"
                },
                {
                  "Fn::GetAtt": "WebBucket.Arn"
                }
              ],
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": false
                }
              }
            }
```

Is there a way to override this policy or prevent it from being created? I was using node 17 and this was not being created, only after upgrading it.

### Service configuration (serverless.yml) content

```yaml
package:
  individually: true
  excludeDevDependencies: true
provider:
  name: aws
  runtime: provided.al2
  architecture: x86_64
  region: us-east-1
  stage: ${opt:stage,'dev'}
  memorySize: 128
  timeout: 10
  tracing:
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - codedeploy:*
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - states:StartExecution
          Resource:
            - ${file(../configs/config.${opt:stage, 'dev'}.json):ENV}
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 
            - "arn:aws:secretsmanager(...)"
            - "arn:aws:secretsmanager(...)"
        - Effect: Allow
          Action:
            - "rds-data:BatchExecuteStatement"
            - "rds-data:BeginTransaction"
            - "rds-data:CommitTransaction"
            - "rds-data:ExecuteStatement"
            - "rds-data:RollbackTransaction"
          Resource: "*"

custom:
  prune:
    automatic: true
    number: 3

functions:
  healthCheck:
    handler: ./src/functions/healthCheck/main.go
    events:
      - http:
          method: GET
          caching:
            enabled: false
          path: /health-check
          cors:
            origins: 
              - ${file(../configs/config.${opt:stage, 'dev'}.json):CORS}
          documentation: ${file(documentation.yml):functions.healthCheckFunction}
```

### Command name and used flags

sls deploy -s dev

### Command output

```shell
✖ Stack api-dev failed to deploy (83s)
Environment: linux, node 20.10.0, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "swap-v2" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The CloudFormation template is invalid: Template error: instance of Fn::Sub references invalid resource attribute WebBucket.Arn
```

### Environment information

```shell
➜  api git:(develop) ✗ serverless --version
Running "serverless" from node_modules
Framework Core: 3.38.0 (local) 3.38.0 (global)
Plugin: 7.2.0
SDK: 4.5.1
```
