### ISSUE TITLE
Add configuration for CloudWatch Log for choosing LogGroupClass

### ISSUE THREAD

**Issue by davidsoendoro** [serverless/serverless#12278]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS CloudWatch Log has just released a new option for log class at the 26th of November 2023. The new option is to use Infrequent Access log type on storing the logs in CloudWatch. This option is suitable for those who are not using features of CloudWatch Logs other than storing the logs as it enables 50% lower cost for data ingestion. Full announcement of the release is available [here](https://aws.amazon.com/blogs/aws/new-amazon-cloudwatch-log-class-for-infrequent-access-logs-at-a-reduced-price/)

### Proposed solution (optional)

Add an additional configuration in the AWS function

```
functions:
  myCloudWatchLog:
    handler: myCloudWatchLog.handler
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/hello'
          filter: '{$.userIdentity.type = Root}'
          logClass: 'Infrequent Access'
```
Which value will be used in the CloudFormation LogGroupClass as described [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html). Example:

```
{
  "Type" : "AWS::Logs::LogGroup",
  "Properties" : {
      "DataProtectionPolicy" : Json,
      "KmsKeyId" : String,
      "LogGroupClass" : String,
      "LogGroupName" : String,
      "RetentionInDays" : Integer,
      "Tags" : [ Tag, ... ]
    }
}
```

**Comment by JaredAAT** [comment]
related: https://github.com/serverless/serverless/issues/12264

**Comment by darcoli** [comment]
@davidsoendoro please see [this](https://github.com/serverless/serverless/pull/12282#issuecomment-1859814737) comment and confirm whether you agree on the mentioned approach

**Comment by SadmiB** [comment]
I'm interested in the same feature. AWS introduced CloudWatch logs `Infrequent Access` storage class, offering less cost than the standard one. However, it seems the serverless framework still hasn't adapted the feature yet.

it would be nice to have it.

**Comment by affanshahab** [comment]
Any update on this yet?

**Comment by louyshong** [comment]
I have written a [plugin to achieve this](https://www.npmjs.com/package/serverless-plugin-infrequent-access-logs), feel free to check it out :)

**Comment by affanshahab** [comment]
> Any update on this yet?

that's how I ended up doing. Guidelines here: https://www.linkedin.com/pulse/aws-cloudwatch-infrequent-access-lambda-serverless-save-affan-shahab-zylxc/?trackingId=yZ0%2FsbI%2FQX2XCuzD4XSsuw%3D%3D

**Comment by jamiel** [comment]
An [alternative plugin](https://github.com/qubops/serverless-plugin-log-class) as we needed a bit more flexibility and to support a wider range of framework versions.

**Comment by czubocha** [comment]
Hey folks, this was shipped in **[v4.37.0](https://github.com/serverless/serverless/releases/tag/sf-core%404.37.0)**.

You can now opt into the Infrequent Access log class at the provider or function level:

```yaml
provider:
  logs:
    lambda:
      logGroupClass: infrequent_access   # service-wide default

functions:
  realTimeReports:
    handler: handler.reports
    logs:
      logGroupClass: standard            # override per function
```

This maps to the CloudFormation `LogGroupClass` property and wires Lambda's `LoggingConfig.LogGroup` accordingly. A couple of caveats worth knowing: AWS doesn't allow the class of an existing log group to be changed in place, and `serverless logs -f <function>` can't read IA groups.

Docs: https://www.serverless.com/framework/docs/providers/aws/guide/functions#infrequent-access-log-class

Closing as released - thanks for the request!
