### ISSUE TITLE
python3.11 deploy errors

### ISSUE THREAD

**Issue by AMO-brandon** [serverless/serverless#12281]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Updated my runtime to python3.11 now my gitlab pipeline is erroring out, the error isnt very clear so not sure whats going on.

```
× Stack serverless-admin-tables-staging failed to deploy (3s)
Environment: linux, node [18](https://github.com/XXX/XXX/actions/runs/7022211058/job/19106006982#step:7:19).18.2, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Error:
Error: `python3.11 -m pip install -t /home/runner/work/es-admin-tables-serverless/es-admin-tables-serverless/.serverless/requirements -r /home/runner/work/es-admin-tables-serverless/es-admin-tables-serverless/.serverless/requirements/requirements.txt` Exited with code 1
    at ChildProcess.<anonymous> (/home/runner/work/es-admin-tables-serverless/es-admin-tables-serverless/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
Bugs:        github.com/serverless/serverless/issues
```

Here is my workflow:

```
name: Deploy Admin Tables Elastic Search

on:
    push:
        tags:
            - "development-*"
            - "staging-*"

jobs:
    deploy:
        name: Deploy Serverless
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Install Serverless Framework
              run: npm install -g serverless
            - name: Install Plugins
              run: sls plugin install -n serverless-stage-manager && sls plugin install -n serverless-python-requirements && sls plugin install -n serverless-offline && sls plugin install -n serverless-plugin-datadog
            - name: Deploy Serverless
              if: startsWith(github.ref, 'refs/tags/staging-')
              run: sls deploy -s staging
            - name: Deploy Serverless
              if: startsWith(github.ref, 'refs/tags/development-')
              run: sls deploy -s development
```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls deploy -s staging

### Command output

```shell
× Stack serverless-admin-tables-staging failed to deploy (3s)
Environment: linux, node [18](https://github.com/XXX/XXX/actions/runs/7022211058/job/19106006982#step:7:19).18.2, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Error:
Error: `python3.11 -m pip install -t /home/runner/work/es-admin-tables-serverless/es-admin-tables-serverless/.serverless/requirements -r /home/runner/work/es-admin-tables-serverless/es-admin-tables-serverless/.serverless/requirements/requirements.txt` Exited with code 1
    at ChildProcess.<anonymous> (/home/runner/work/es-admin-tables-serverless/es-admin-tables-serverless/node_modules/child-process-ext/spawn.js:38:8)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
Bugs:        github.com/serverless/serverless/issues
```

### Environment information

```shell
Environment: linux, node [18](https://github.com/XXX/XXX/actions/runs/7022211058/job/19106006982#step:7:19).18.2, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
```
