### ISSUE TITLE
DELETE_FAILED: ServerlessDeploymentBucket (AWS::S3::Bucket)

### ISSUE THREAD

**Issue by tyroneyellowcard** [serverless/serverless#12286]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a deployed service on AWS. I was previously using the default deployment bucket that sls creates when deploying the service. We have decided to manage the amount of buckets created by using a single deployment bucket approach. 

I added in the deploymentBucket.name property under provider. This bucket was created outside of the serverless framework for use in the serverless.yml. When I run `sls deploy --stage staging --region eu-west-2` the artifacts are loaded into this new deployment bucket but the default deployment bucket fails to delete as it is not empty. However this default bucket successfully deletes if I run `sls remove` without the deploymentBucket.name property in the serverless.yml file. 

I checked previous posts where users had the same or similar problem and this issue has been addressed in later versions to when the posts were created (v1). We could use a plugin to empty the default deployment bucket before sls attempts to delete it however it requires a workaround to be able to add the bucket in the removal list dynamically as the default deployment bucket names are generated dynamically. 

It was my understanding the sls framework would delete the previous deployment bucket without the need for a plugin. 

Am I correct in saying that when adding in a custom deployment bucket for single deployment purposes that the previously created default deployment bucket would be deleted? 

### Service configuration (serverless.yml) content

```yaml
service: gw-access-logging
frameworkVersion: '3'

package:
  individually: false
  excludeDevDependencies: true

custom:
  defaultRegion: eu-west-2
  serviceName: Gateway-Access-Logging
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, file(../../config/provider.common.yml):region}
  accountId: ${file(../../config/provider.common.yml):accountId}
  defaultStage:
    dev: dev
    staging: staging
    prod: prod
    other: staging
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 5
  warmup: true
  datadog:
    addExtension: true
    apiKeySecretArn: ${file(../../config/provider.common.yml):DdApiKeySecretArn}
    enableSourceCodeIntegration: true
    service: ${self:service}
    version: ${file(./package.json):version} # get version from package.json
    tags: 'pod:devops' # NOTE: update this with your pod name
    env: ${self:custom.stage}

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs18.x
  region: ${opt:region, file(../../config/provider.common.yml):region}
  environment: ${file(./serverless.env.yml):${self:custom.stage}, file(./serverless.env.yml):${file(../../config/provider.common.yml):defaultStage}}
  deploymentBucket:
    name: devops-tools-${aws:accountId}-${self:provider.region}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
          Resource:
            - arn:aws:ssm:${self:provider.region}:${self:custom.accountId}:parameter/*
        - Effect: 'Allow'
          Action:
            - cloudwatch:PutMetricData
          Resource:
            - '*'
        - Effect: 'Deny'
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - arn:aws:logs:*:*:*
        - Effect: 'Allow'
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - 'apigatewayv2:GetStage'
            - 'apigatewayv2:UpdateStage'
            - 'apigateway:GET'
            - 'apigateway:PATCH'
          Resource: '*'
        - Effect: 'Allow'
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - arn:aws:secretsmanager:${self:custom.region}:${self:custom.accountId}:secret:*
        - Effect: 'Allow'
          Action:
            - sqs:*
          Resource:
            - arn:aws:sqs:${self:custom.region}:${self:custom.accountId}:yellowcard-communications-queue-${file(../../config/provider.common.yml):defaultStage}

functions:
  # - ${file(./api-functions.yml)}
  - ${file(./functions.yml)}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-datadog
resources:
  - Conditions:
      CreateDevResources: !Equals ['${self:custom.stage}', 'dev']
      CreateStagingResources: !Equals ['${self:custom.stage}', 'staging']
      CreateProdResources: !Equals ['${self:custom.stage}', 'prod']
      NotCreatePrResources: !Or
        - Condition: CreateDevResources
        - Condition: CreateStagingResources
        - Condition: CreateProdResources
  # - ${file(./resources.yml)}
#just to trigger deployment ...
```

### Command name and used flags

sls deploy --stage staging --region eu-west-2

### Command output

```shell
DELETE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
  DELETE_FAILED - AWS::S3::Bucket - ServerlessDeploymentBucket
  DELETE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
  DELETE_FAILED - AWS::S3::Bucket - ServerlessDeploymentBucket
  DELETE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
  DELETE_FAILED - AWS::S3::Bucket - ServerlessDeploymentBucket
  UPDATE_COMPLETE - AWS::CloudFormation::Stack - gw-access-logging-staging

The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID:
```

### Environment information

```shell
3.31.0 (local) 3.36.0 (global)
```
