### ISSUE TITLE
lambdaAuthorizerConfig not being picked up by my serverless.yaml

### ISSUE THREAD

**Issue by urehmani** [serverless/serverless#12297]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

as part of my appsync deployment I am trying to add another authorization mechanism with `AWS_LAMBDA`

and any time I try to deploy this code in my serverless.yaml I keep getting the error 
```
Error:
UPDATE_FAILED: GraphQlApi (AWS::AppSync::GraphQLApi)
Lambda Authorizer Config missing (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 9061ddb7-ea27-45f2-908e-4e73cb1c992d; Proxy: null)
```

### Service configuration (serverless.yml) content

```yaml
service: tq-core-api-appsync
frameworkVersion: ${self:custom.ENV.FRAMEWORK_VERSION}
useDotenv: true

#******************************************************************** Plugins **
plugins:
    - serverless-appsync-plugin

#******************************************************************* Provider **
provider:
    name: aws
    stage: ${self:custom.ENV.STAGE}
    region: ${self:custom.ENV.TARGET_REGION}
    runtime: ${self:custom.ENV.RUNTIME}
    logRetentionInDays: ${self:custom.ENV.LOG_RETENTION_IN_DAYS}
    environment:
        STAGE: ${self:provider.stage}

#********************************************************************* Custom **
custom:
    ENV: ${file(../../serverless.common.yml)}

    appSync:
        name: ${self:service}-${self:provider.stage}
        region: ${self:provider.region}
        tags: ${self:custom.ENV.TAGS}
        schema: 'schema.graphql'
        authenticationType: OPENID_CONNECT
        serviceRole: '${self:service}-AppSyncServiceRole'

        openIdConnectConfig:
          issuer: ${self:custom.ENV.AUTH0_DOMAIN}

        additionalAuthenticationProviders:
          - authenticationType: API_KEY
          - authenticationType: AWS_LAMBDA
            lambdaAuthorizerConfig:
              functionName: validateApiKey
              lambdaFunctionArn:
                Fn::ImportValue: ${self:provider.stage}-ValidateApiKeyLambdaFunctionArn
```

### Command name and used flags

sls deploy --stage ur

### Command output

```shell
Error:
UPDATE_FAILED: GraphQlApi (AWS::AppSync::GraphQLApi)
Lambda Authorizer Config missing (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: 9061ddb7-ea27-45f2-908e-4e73cb1c992d; Proxy: null)
```

### Environment information

```shell
Framework Core: 3.15.2
Plugin: 6.2.2
SDK: 4.3.2
```
