### ISSUE TITLE
Params are not resolved under EventBridge triggers' pattern

### ISSUE THREAD

**Issue by ada-cienciala** [serverless/serverless#12303]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I'm creating an event bridge trigger in serverless, I cannot pass values by `${param:XXX}` - they are not resolved properly

<img width="335" alt="image" src="https://github.com/serverless/serverless/assets/86961468/4d91a549-c754-481f-bbe1-9760c7b714fc">

Funny enough, works without issue in HTTP triggers.

Also, deploying it with serverless compose, if it makes a difference.

### Service configuration (serverless.yml) content

```yaml
service: ServiceName
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
    
# Create an individual package for each function
package:  
  individually: true

custom:
  detailTypes:
    example: exampleType

functions:
  example:
    handler: src/example/handler
    events:
      - eventBridge:
          pattern:
            detail-type:
              - "${self:custom.detailTypes.example}"
            source:
             - "${param.taskEventSource}"
```

### Command name and used flags

serverless deploy --param taskEventSource=com.example.task.source

### Command output

```shell
AWS Console shows that custom variables are resolved, params not: 
```

<img width="335" alt="image" src="https://github.com/serverless/serverless/assets/86961468/4d91a549-c754-481f-bbe1-9760c7b714fc">

### Environment information

```shell
Framework Core: 3.34.0
Plugin: 6.2.3
SDK: 4.3.2
```
