### ISSUE TITLE
ModuleNotFoundError: No module named 'handler' when using module & running invoke local 

### ISSUE THREAD

**Issue by TimeKeeperM** [serverless/serverless#12309]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have folder structure:

project-root
 - admin
    - handler.py
    - requirements.txt

serverless.yml is configured as below. 

buy when I tried to run the function locally, it's throwing error:
```
ModuleNotFoundError: No module named 'handler'
```

but it deployed successfully & running on lambda.

according to documentation of `serverless-python-requirement`, when we use `module` in function in yml, then we dont have to add folder prefix in `handler`.

but when I change config to this:
```

  my-test-func:
    name: my-test-func
    handler: admin/handler.lambda_handler
    module: admin
```

It works fine in local but not on aws Lambda.

### Service configuration (serverless.yml) content

```yaml
service: my-project-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

package:
  individually: true
  patterns:
    - "!*/**"
    - "!*"

functions:
  my-test-func:
    name: my-test-func
    handler: handler.lambda_handler
    module: admin
    package:
      patterns:
        - admin/*
    events:
      - http:
          path: /admin
          method: get

plugins:
  - serverless-python-requirements
```

### Command name and used flags

serverless invoke local --function my-test-func

### Command output

```shell
ModuleNotFoundError: No module named 'handler'
```

### Environment information

```shell
Framework Core: 3.38.0
Plugin: 7.2.0
SDK: 4.5.1
```
