### ISSUE TITLE
Many Events for one lambda cause permission policy size to exceed limit (20480)

### ISSUE THREAD

**Issue by charlotteveitner** [serverless/serverless#12308]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I have a lambda function that has 50+ schedules. The input variables vary for each schedule and I can thus not consolidate them into one scheduled event. My deployment works fine with ~30 schedules and only fails thereafter. 

Severless creates a policy statement for each of the schedules that grants the event rule access to invoke the lambda function. This leads to the issue of the permission policy document of the lambda exceeding the limit of 2040MB. 
Each policy looks like this (where the {schedule index} is a running count of the scheduled events per lambda) : 

`{
"Sid": "{service_name}-{normalized function name}LambdaPermissionEventsRuleSchedule{schedule index}-{random ID 1}",
"Effect": "Allow",
"Principal": {
     "Service": "events.amazonaws.com"
},
"Action": "lambda:InvokeFunction",
"Resource": "arn:aws:lambda:{region}:{account_id}:function:{service_name}-{function_name}",
"Condition": {
     "ArnLike": {
          "AWS:SourceArn": "arn:aws:events:{region}:{account_id}:rule/{service_name}-{normalized function name}EventsRuleSchedule{schedule index}--{random ID 2}"
     }
}
}
`

I would like to implement one consolidated policy statement that grants all event rules access to my lambda function.
The condition of the rule should be similar to wildcard like: `"arn:aws:events:{region}:{account_id}:rule/{service_name}-{normalized function name}EventsRuleSchedule*"`

Is there a workaround to stop the creation of the individual roles?

I tried adding a new resource to my serverless that creates the role but unfortunately it doesn't prevent the creation of the per event schedule roles that is causing the policy limit issue. The role I definined looks like this: 
```
resources:
  Resources:
    GeneralInvokePermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          Fn::GetAtt:
            - {normalized function name}LambdaFunction
            - Arn
        Action: "lambda:InvokeFunction"
        Principal: "events.amazonaws.com"
        SourceArn:
          Fn::Sub: arn:aws:events:{region}:{account_id}:rule/${self:service}*
```

The full error message is 
```
Error:
CREATE_FAILED: {NormalizedFunctionName}LambdaPermissionEventsRuleSchedule{Index that fails (in my case 31)} (AWS::Lambda::Permission)
Resource handler returned message: "The final policy size (20485) is bigger than the limit (20480). (Service: Lambda, Status Code: 400, Request ID: c5b62677-fdc1-40c0-a8b4-33ac332ad3c7)" (RequestToken: ed1a4eea-86d3-7e35-ae6b-e3f7fb3f05d1, HandlerErrorCode: InvalidRequest)
```

### Service configuration (serverless.yml) content

```yaml
service: {service_name}

provider:
  name: aws
  runtime: python3.9
  memorySize: 2048
  timeout: 800
  stage: ${opt:stage, 'local'}
  region: ${file(./config/${self:provider.stage}.yml):aws.region}
  stackTags:
    SERVICE: ${self:service}
  endpointType: REGIONAL
  environment:
    PROJECT: ${self:service}-${self:provider.stage}
    ENV: ${self:provider.stage}
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - cloudwatch:PutMetricData
          Resource: '*'
        - Effect: "Allow"
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: '*'

custom:
  pythonRequirements:
    dockerizePip: non-linux

  customDomain:
    domainName: '${self:service}-${self:provider.stage}.services.{custom_domain}.com'
    stage: ${self:provider.stage}
    certificateName: '*.services.{custom_domain}.com'
    createRoute53Record: true
    endpointType: REGIONAL


plugins:
  - serverless-python-requirements
  - serverless-domain-manager


functions:
  {function_name}:
    handler: {path to handler}
    events:
      - schedule:
          rate: cron(45 8,17 * * ? *)
          input:
            task: 'input_1'

      - schedule:
          rate: cron(50 4 * * ? *)
          input:
            task: 'input_2'

      - schedule:
          rate: cron(55 4 * * ? *)
          input:
            task: 'input_3'

      - schedule:
          rate: cron(30 4 * * ? *)
          input:
            task: 'input_4'

      - .... (many more schedules)

      - schedule:
          rate: cron(15 22 * * ? *)
          input:
            task: 'input_51'
      
      - schedule:
          rate: cron(15 23 * * ? *)
          input:
            task: 'input_52'

resources:
  Resources:
    GeneralInvokePermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          Fn::GetAtt:
            - {normalized function name}LambdaFunction
            - Arn
        Action: "lambda:InvokeFunction"
        Principal: "events.amazonaws.com"
        SourceArn:
          Fn::Sub: arn:aws:events:{region}:{account_id}:rule/${self:service}*
```

### Command name and used flags

serverless deploy --stage production

### Command output

```shell
Error:
CREATE_FAILED: OrchestrateLambdaPermissionEventsRuleSchedule31 (AWS::Lambda::Permission)
Resource handler returned message: "The final policy size (20485) is bigger than the limit (20480). (Service: Lambda, Status Code: 400, Request ID: c5b62677-fdc1-40c0-a8b4-33ac332ad3c7)" (RequestToken: ed1a4eea-86d3-7e35-ae6b-e3f7fb3f05d1, HandlerErrorCode: InvalidRequest)
```

### Environment information

```shell
3.38.0
```

**Comment by joshverma** [comment]
Have you found a solution for this?

**Comment by locerito** [comment]
Any solutions or workaround?

**Comment by charlotteveitner** [comment]
> Any solutions or workaround?

@locerito I ended up splitting the events and deploying two seperate lambda functions with half of the events in each. Obviously not the cleanest approach but at least I am still able to deploy 👍🏽

**Comment by locerito** [comment]
Thanks for the answer, I will investigate a little more but since there is no clean way to do it, for now I apply another approach.
I'll tell you what I've done in case you're interested.

I apply a common permission to all event bridge rules with a wildcard.

```
resources:
  Resources:
    PermissionToCallEventRouterController:
      Type: "AWS::Lambda::Permission"
      Properties: 
        Action: lambda:InvokeFunction
        FunctionName: 
          Ref: EventUnderscorerouterUnderscorecontrollerLambdaFunction
        Principal: "events.amazonaws.com"
        SourceArn: "arn:aws:events:${self:provider.region}:${file(config.${opt:stage, 'dev'}.json):account}:rule/ocr_*"
```

To deploy, I run a package command, then I delete all EventBridgeLambdaPermission cloudformation resources for every rule in the cloudformation template files, and finally deploy with the package parameter.

```bash
serverless package --stage $ENVIRONMENT
python remove_cloudformation_resources.py .serverless/serverless-state.json EventUnderscorerouterUnderscorecontrollerEventBridgeLambdaPermission
python remove_cloudformation_resources.py .serverless/cloudformation-template-update-stack.json EventUnderscorerouterUnderscorecontrollerEventBridgeLambdaPermission
serverless deploy --stage $ENVIRONMENT --package .serverless
```

This is the python code I used (remove_cloudformation_resources.py):

```python
import json
import sys


def read_json_file(file):
    with open(file) as json_file:
        data = json.load(json_file)
    return data


def write_json_file(file, data):
    with open(file, 'w') as outfile:
        json.dump(data, outfile, indent=2)


def remove_resources_from_serverless_state(data, name):
    data_copy = data.copy()
    cloudformation_template = data["service"]["provider"]["compiledCloudFormationTemplate"]["Resources"]
    cloudformation_template_copy = cloudformation_template.copy()
    for resource_name, item in cloudformation_template.items():
        if item["Type"] == "AWS::Lambda::Permission" and resource_name.startswith(name):
            print("Removing resource: " + resource_name)
            cloudformation_template_copy.pop(resource_name, None)
    data_copy["service"]["provider"]["compiledCloudFormationTemplate"]["Resources"] = cloudformation_template_copy
    return data_copy

def remove_resources_from_cloudformation(data, name):
    data_copy = data.copy()
    cloudformation_template = data["Resources"]
    cloudformation_template_copy = cloudformation_template.copy()
    for resource_name, item in cloudformation_template.items():
        if item["Type"] == "AWS::Lambda::Permission" and resource_name.startswith(name):
            print("Removing resource: " + resource_name)
            cloudformation_template_copy.pop(resource_name, None)
    data_copy["Resources"] = cloudformation_template_copy
    return data_copy


if __name__ == "__main__":
    filename = sys.argv[1]
    resource_pattern = sys.argv[2]

    data = read_json_file(filename)
    if "serverless-state" in filename:
        data_fix = remove_resources_from_serverless_state(data, resource_pattern)
    elif "cloudformation-template" in filename:
        data_fix = remove_resources_from_cloudformation(data, resource_pattern)
    write_json_file(filename, data_fix)
```
