### ISSUE TITLE
Deploying node20 AWS Lambda function through Serverless.com sets module import to ESM

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#12318]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We have a function that we wanted to upgrade to node20, but after doing that we get the error in AWS after deploy as:
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'handler'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```
The code and files are all CommonJS, and there is no `type` in `package.json`

Executing the function locally using `sls invoke local -f routeInvoice...` works fine!

### Service configuration (serverless.yml) content

```yaml
service: serverless-ap
frameworkVersion: '3'

package:
  individually: true

plugins:
  # - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1

functions:
  validator:
    handler: src/validator/handler.run
    memorySize: 2048
    ephemeralStorageSize: 4096
    timeout: 300
    url:
      invokeMode: RESPONSE_STREAM
```

### Command name and used flags

serverless deploy -s test

### Command output

```shell
Service deployed to stack
```

### Environment information

```shell
Framework Core: 3.38.0 (local)
Plugin: 7.2.0
SDK: 4.5.1
```
