### ISSUE TITLE
CREATE_FAILED: ApiGatewayLogGroup (AWS::Logs::LogGroup)  Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"xxx"}' already exists." 

### ISSUE THREAD

**Issue by nkumar-repay** [serverless/serverless#12312]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Using following configuration for our app.
`provider:
  name: aws
  runtime: java17
  region: ${param:region}
  stage: ${opt:stage}
  tracing: true
  logs:
    restApi:
      accessLogging: true
      format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'
      executionLogging: false
`
**and getting ERROR:**
× Stack app-name failed to deploy (51s)

Environment: linux, node 14.21.3, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1

Credentials: Local, "serverless" profile

Docs:        docs.serverless.com

Support:     forum.serverless.com

Bugs:        github.com/serverless/serverless/issues

Error:

CREATE_FAILED: ApiGatewayLogGroup (AWS::Logs::LogGroup)

Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/api-gateway/xxx}' already exists." (RequestToken: 8e551884-4931-47f4-aed0-b8d55133bb6d, HandlerErrorCode: AlreadyExists)

Existing issue: https://github.com/serverless/serverless/issues/6906

### Service configuration (serverless.yml) content

```yaml
provider:
  name: aws
  runtime: java17
  region: ${param:region}
  stage: ${opt:stage}
  tracing: true
  logs:
    restApi:
      accessLogging: true
      format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency}'
      executionLogging: false
```

### Command name and used flags

sls deploy

### Command output

```shell
× Stack app-name failed to deploy (51s)

Environment: linux, node 14.21.3, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1

Credentials: Local, "serverless" profile

Docs:        docs.serverless.com

Support:     forum.serverless.com

Bugs:        github.com/serverless/serverless/issues



Error:

CREATE_FAILED: ApiGatewayLogGroup (AWS::Logs::LogGroup)

Resource handler returned message: "Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/api-gateway/app-name"}' already exists." (RequestToken: 8e551884-4931-47f4-aed0-b8d55133bb6d, HandlerErrorCode: AlreadyExists)
```

### Environment information

```shell
framework 3.38.0
```
