### ISSUE TITLE
Each DynamoDB stream event handler duplicates the IAM policy, causing "Maximum policy size exceeded"

### ISSUE THREAD

**Issue by tibbe** [serverless/serverless#12313]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We recently started seeing a deployment error

```
UPDATE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role)
Resource handler returned message: "Maximum policy size of 10240 bytes exceeded for role backend-xxxxxx-eu-central-1-lambdaRole (Service: Iam, Status Code: 409, Request ID: 0ab39c5b-fef4-491b-be1d-d1a730xxxxxx)" (RequestToken: 7591a9ce-5117-b2b5-c915-161cb4xxxxxx, HandlerErrorCode: ServiceLimitExceeded)
```

Debugging further I noticed the same IAM Role section repeated 29 times (2 repeats shown below for demonstration purposes) in the generated `backend-xxxxxx-eu-central-1-lambdaRole` role:

```json
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": [
                "arn:aws:dynamodb:eu-central-1:227135xxxxxx:table/backend-xxxxxx-Users/stream/2023-07-11T08:50:35.845"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": [
                "arn:aws:dynamodb:eu-central-1:227135xxxxxx:table/backend-xxxxxx-Users/stream/2023-07-11T08:50:35.845"
            ],
            "Effect": "Allow"
        },
```

(The resource is the same in each section so this is truly duplicated.)

It's seem like that for each

```yml
  events:
    - stream:
      type: dynamodb
```

section in the YAML config we get a new repeat of the above policy, eventually causing the size to go over the limit.

### Service configuration (serverless.yml) content

```yaml
# The whole config too large to include and mask out sensitive parts of. Here's the relevant part:
ProjectDeleter:
  image:
    name: backend
    command:
      - xxxxxx.clean_up.project_deleted_handler.handle
  timeout: 300  # 5 minutes
  events:
    - stream:
        type: dynamodb
        arn:
          { "Fn::GetAtt": ["DynamoDBTable", "StreamArn"] }
        filterPatterns:
          - eventName: [REMOVE]
            dynamodb:
              OldImage:
                Type:
                  S: [PROJECT]
        batchWindow: 0
        batchSize: 10
        functionResponseType: ReportBatchItemFailures
  environment:
    POWERTOOLS_SERVICE_NAME: ProjectDeleter
```

(We have 29 of these in our config.)

### Command name and used flags

serverless deploy --stage=xxxxxx

### Command output

```shell
UPDATE_FAILED: IamRoleLambdaExecution (AWS::IAM::Role)
Resource handler returned message: "Maximum policy size of 10240 bytes exceeded for role backend-xxxxxx-eu-central-1-lambdaRole (Service: Iam, Status Code: 409, Request ID: 0ab39c5b-fef4-491b-be1d-d1a730xxxxxx)" (RequestToken: 7591a9ce-5117-b2b5-c915-161cb4xxxxxx, HandlerErrorCode: ServiceLimitExceeded)
```

### Environment information

```shell
Framework Core: 3.35.2 (local) 3.33.0 (global)
Plugin: 7.0.5
SDK: 4.4.0
```
