### ISSUE TITLE
Serverless stuck infinitely for aws provider on deploy

### ISSUE THREAD

**Issue by adminy** [serverless/serverless#12323]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

sls deploy is stuck forever deploying without any message of something going wrong.

### Service configuration (serverless.yml) content

```yaml
service: REDACTED
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-better-credentials
  - serverless-domain-manager
  - serverless-iam-roles-per-function
  - serverless-plugin-aws-alerts
  - serverless-plugin-utils
  - sls-py

provider:
  name: aws
  runtime: python3.10
  region: ${opt:region, "REDACTED"}
  stage: ${opt:stage, "dev"}
  deploymentMethod: direct
  deploymentBucket:
    name: ${env:REDACTED}
  deploymentPrefix: deployment_artifacts
  logRetentionInDays: 60
  stackTags:
    REDACTED: REDACTED
  environment:
    BUCKET_NAME: ${env:REDACTED}
    STAGE: ${upper(${sls:stage})}
    REGION: ${self:provider.region}
    POWERTOOLS_SERVICE_NAME: ${self:service}
  endpointType: PRIVATE
  vpcEndpointIds:
    - ${env:REDACTED}
  vpc:
    subnetIds: !Split [",", "${env:REDACTED}"]
    securityGroupIds:
      - ${env:REDACTED}
      - ${env:REDACTED}
  apiGateway:
    metrics: True
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: 'execute-api:Invoke'
        Resource: 'execute-api:/*/*/*'
custom:
  customDomain:
    apiType: rest
    endpointType: regional
    securityPolicy: tls_1_2
    stage: REDACTED
    domainName: REDACTED
    basePath: REDACTED
    certificateName: "*.REDACTED"
    certificateArn: REDACTED
    createRoute53Record: false
    createRoute53IPv6Record: false
    preserveExternalPathMappings: true
    hostedZonePrivate: true
    autoDomain: true
  alerts:
    alarms:
      - functionErrors
      - functionThrottles
    definitions:
      functionErrors:
        treatMissingData: notBreaching
      functionThrottles:
        treatMissingData: notBreaching

  pythonRequirements:
    enableLambdaInsights: true
    vpc: ${self:provider.vpc}
    timeout: 29
    indexUrl: REDACTED
    extraIndexUrl: REDACTED
    trustedHost: REDACTED

functions:
  ...
  health:
    module: package
    handler: file.function_handler
    events:
      - http:
          method: GET
          path: /health
```

### Command name and used flags

timeout -s SIGUSR1 10m node -r why-is-node-running/include node_modules/serverless/bin/serverless.js deploy -s ${{ inputs.stage }} -r ${{ inputs.region }} --force --verbose --debug="*"

### Command output

```shell
config: Retrieve local config, auth data undefined
config: Stored config at /github/home/.serverlessrc, auth data  undefined
config: Retrieve global config, auth data undefined
process: resolve CLI input (no service schema)
process: resolve CLI input (service schema)
process: resolve eventual service configuration
process: service configuration found at /project/serverless.yml
process: service configuration file successfully parsed
process: resolve variables meta
process: resolve CLI input (AWS service schema)
process: resolve variables in core properties
process: resolve variables in all properties
process: resolve CLI input (AWS service schema)
process: construct Serverless instance
process: initialize Serverless instance
lifecycle:command:register: config
lifecycle:command:register: config:credentials
lifecycle:command:register: create
lifecycle:command:register: install
lifecycle:command:register: package
lifecycle:command:register: package:function
lifecycle:command:register: deploy
lifecycle:command:register: deploy:function
lifecycle:command:register: deploy:list
lifecycle:command:register: deploy:list:functions
lifecycle:command:register: invoke
lifecycle:command:register: invoke:local
lifecycle:command:register: info
lifecycle:command:register: logs
lifecycle:command:register: metrics
lifecycle:command:register: print
lifecycle:command:register: remove
lifecycle:command:register: rollback
lifecycle:command:register: rollback:function
lifecycle:command:register: slstats
lifecycle:command:register: plugin
lifecycle:command:register: plugin
lifecycle:command:register: plugin:list
lifecycle:command:register: plugin
lifecycle:command:register: plugin:search
lifecycle:command:register: config
lifecycle:command:register: config:credentials
lifecycle:command:register: aws
lifecycle:command:register: aws:common
lifecycle:command:register: aws:common:validate
lifecycle:command:register: aws:common:cleanupTempDir
lifecycle:command:register: aws:common:moveArtifactsToPackage
lifecycle:command:register: aws:common:moveArtifactsToTemp
lifecycle:command:register: aws
lifecycle:command:register: aws:package
lifecycle:command:register: aws:package:finalize
lifecycle:command:register: aws
lifecycle:command:register: aws:deploy
lifecycle:command:register: aws:deploy:deploy
lifecycle:command:register: aws:deploy:finalize
lifecycle:command:register: aws
lifecycle:command:register: aws:info
lifecycle:command:register: upgrade
lifecycle:command:register: uninstall
serverless-better-credentials: provider.getCredentials patched
lifecycle:command:register: create_domain
lifecycle:command:register: delete_domain
lifecycle:command:register: login
lifecycle:command:register: logout
lifecycle:command:register: generate-event
lifecycle:command:register: test
lifecycle:command:register: dashboard
lifecycle:command:register: output
lifecycle:command:register: output:get
lifecycle:command:register: output:list
lifecycle:command:register: param
lifecycle:command:register: param:get
lifecycle:command:register: param:list
process: resolve CLI input (+ plugins schema)
process: resolve variables
process: resolve all variables
first attempt to getting aws credentials
aws: [1] { name: 'STS',
  params:
   { credentials:
      AwsCredentials {
        expired: true,
        expireTime: null,
        refreshCallbacks: [],
        accessKeyId: 'ACCESS_KEY_ID',
        sessionToken: undefined,
        hint: 'No credentials resolved',
        hintShown: false,
        chain:
         CredentialProviderChain {
           providers:
            [ [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)] ],
           resolveCallbacks: [] },
        logHintFn: [Function (anonymous)] },
     region: 'REDACTED',
     isS3TransferAccelerationEnabled: false } } getCallerIdentity [ {} ]
✔ serverless-better-credentials: credentials resolved from config SharedIniFileCredentials: AWS_DEFAULT_PROFILE (default)
aws: [1] { ResponseMetadata: { RequestId: 'REDACTED' },
  UserId: 'REDACTED',
  Account: 'REDACTED',
  Arn: 'arn:aws:iam::REDACTED' }
process: run Serverless instance
Deploying REDACTED to stage dev (REDACTED)
aws: [2] { name: 'STS',
  params:
   { credentials:
      AwsCredentials {
        expired: false,
        expireTime: null,
        refreshCallbacks: [],
        accessKeyId: 'REDACTED',
        sessionToken:
         'REDACTED==',
        hint: 'from config SharedIniFileCredentials: AWS_DEFAULT_PROFILE (default)',
        hintShown: true,
        chain:
         CredentialProviderChain {
           providers:
            [ [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)] ],
           resolveCallbacks: [] },
        logHintFn: [Function (anonymous)] },
     region: 'REDACTED',
     isS3TransferAccelerationEnabled: false } } getCallerIdentity [ {} ]
lifecycle:command:invoke: Invoke deploy
lifecycle:command:invoke:hook: [1] < before:deploy:deploy
lifecycle:command:invoke: Invoke package
lifecycle:command:invoke:hook: [2]   < before:package:cleanup
lifecycle:command:invoke:hook: [2]   > before:package:cleanup
lifecycle:command:invoke:hook: [3]   < package:cleanup
lifecycle:command:invoke: Invoke aws:common:validate
lifecycle:command:invoke:hook: [5]     < aws:common:validate:validate
lifecycle:command:invoke:hook: [5]     > aws:common:validate:validate
lifecycle:command:invoke: Invoke aws:common:cleanupTempDir
lifecycle:command:invoke:hook: [8]     < aws:common:cleanupTempDir:cleanup
lifecycle:command:invoke:hook: [8]     > aws:common:cleanupTempDir:cleanup
lifecycle:command:invoke:hook: [3]   > package:cleanup
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [12]   < package:initialize
lifecycle:command:invoke:hook: [12]   > package:initialize
lifecycle:command:invoke:hook: [15]   < package:setupProviderConfiguration
lifecycle:command:invoke:hook: [15]   > package:setupProviderConfiguration
lifecycle:command:invoke:hook: [17]   < before:package:createDeploymentArtifacts
aws: [2] { ResponseMetadata: { RequestId: 'REDACTED' },
  UserId: 'REDACTED',
  Account: 'REDACTED',
  Arn: 'arn:aws:iam::REDACTED' }
lifecycle:command:invoke:hook: [17]   > before:package:createDeploymentArtifacts
lifecycle:command:invoke:hook: [18]   < package:createDeploymentArtifacts
lifecycle:command:invoke:hook: [18]   > package:createDeploymentArtifacts
lifecycle:command:invoke:hook: [20]   < before:package:compileLayers
lifecycle:command:invoke:hook: [20]   > before:package:compileLayers
lifecycle:command:invoke:hook: [21]   < package:compileLayers
aws: [3] { name: 'CloudFormation',
  params:
   { credentials:
      AwsCredentials {
        expired: false,
        expireTime: null,
        refreshCallbacks: [],
        accessKeyId: 'REDACTED',
        sessionToken:
         'REDACTED==',
        hint: 'from config SharedIniFileCredentials: AWS_DEFAULT_PROFILE (default)',
        hintShown: true,
        chain:
         CredentialProviderChain {
           providers:
            [ [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)],
              [Function (anonymous)] ],
           resolveCallbacks: [] },
        logHintFn: [Function (anonymous)] },
     region: 'REDACTED',
     isS3TransferAccelerationEnabled: false } } describeStacks [ { StackName: 'REDACTED' } ]
aws: [3] { ResponseMetadata: { RequestId: 'REDACTED' },
  Stacks:
   [ { StackId: 'arn:aws:cloudformation:REDACTED',
       StackName: 'REDACTED',
       Description: 'The AWS CloudFormation template for this Serverless application',
       Parameters: [],
       CreationTime: 2024-01-05T19:15:40.634Z,
       LastUpdatedTime: 2024-01-05T19:18:37.098Z,
       RollbackConfiguration: {},
       StackStatus: 'UPDATE_COMPLETE',
       DisableRollback: false,
       NotificationARNs: [],
       Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM' ],
       Outputs:
        [ REDACTED ],
       Tags:
        [ REDACTED ],
       EnableTerminationProtection: false,
       DriftInformation: { StackDriftStatus: 'NOT_CHECKED' } } ] }
lifecycle:command:invoke:hook: [21]   > package:compileLayers
lifecycle:command:invoke:hook: [23]   < before:package:compileFunctions
lifecycle:command:invoke:hook: [23]   > before:package:compileFunctions
lifecycle:command:invoke:hook: [23]   < before:package:compileFunctions
lifecycle:command:invoke:hook: [23]   > before:package:compileFunctions
lifecycle:command:invoke:hook: [24]   < package:compileFunctions
lifecycle:command:invoke:hook: [24]   > package:compileFunctions
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [27]   < package:compileEvents
lifecycle:command:invoke:hook: [27]   > package:compileEvents
lifecycle:command:invoke:hook: [29]   < before:package:finalize
lifecycle:command:invoke:hook: [29]   > before:package:finalize
lifecycle:command:invoke:hook: [30]   < package:finalize
lifecycle:command:invoke: Invoke aws:package:finalize
lifecycle:command:invoke:hook: [32]     < aws:package:finalize:addExportNameForOutputs
lifecycle:command:invoke:hook: [32]     > aws:package:finalize:addExportNameForOutputs
lifecycle:command:invoke:hook: [35]     < aws:package:finalize:mergeCustomProviderResources
lifecycle:command:invoke:hook: [35]     > aws:package:finalize:mergeCustomProviderResources
lifecycle:command:invoke:hook: [38]     < aws:package:finalize:stripNullPropsFromTemplateResources
lifecycle:command:invoke:hook: [38]     > aws:package:finalize:stripNullPropsFromTemplateResources
lifecycle:command:invoke:hook: [41]     < aws:package:finalize:saveServiceState
lifecycle:command:invoke: Invoke aws:common:moveArtifactsToPackage
lifecycle:command:invoke:hook: [43]       < aws:common:moveArtifactsToPackage:move
lifecycle:command:invoke:hook: [43]       > aws:common:moveArtifactsToPackage:move
lifecycle:command:invoke:hook: [41]     > aws:package:finalize:saveServiceState
lifecycle:command:invoke:hook: [30]   > package:finalize
lifecycle:command:invoke:hook: [46]   < after:package:finalize
lifecycle:command:invoke:hook: [46]   > after:package:finalize
lifecycle:command:invoke:hook: [1] > before:deploy:deploy
lifecycle:command:invoke:hook: [1] < before:deploy:deploy
lifecycle:command:invoke: Invoke aws:common:validate
lifecycle:command:invoke:hook: [48]   < aws:common:validate:validate
lifecycle:command:invoke:hook: [48]   > aws:common:validate:validate
lifecycle:command:invoke:hook: [1] > before:deploy:deploy
lifecycle:command:invoke:hook: [1] < before:deploy:deploy
```

### Environment information

```shell
Framework Core: 3.38.0 (local)
Plugin: 7.2.0
SDK: 4.5.1
```
