### ISSUE TITLE
Configuration validation reports `unsupported value` on valid AWS::ApiGatewayV2::Authorizer config

### ISSUE THREAD

**Issue by IanBlockAngel** [serverless/serverless#12328]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Configuration validation reports:
```
Configuration error at 'provider.httpApi.authorizers.jwtAuthorizer': unsupported value
```
Even when the configuration generates a valid CloudFormation template that successfully deploys a AWS::ApiGatewayV2::Authorizer

---

With `configValidationMode: error` (to be the default in future releases) this is preventing me from deploying an authorizer.
I have tried a number of configurations and attempted to satisfy the `authorizerSchema` in [serverless/lib/plugins/aws/package/compile/events/api-gateway/index.js](https://github.com/serverless/serverless/blob/main/lib/plugins/aws/package/compile/events/api-gateway/index.js#L52) but nothing seems to work for me.

As an aside, maybe this should be a separate issue, but the [docs](https://github.com/serverless/serverless/blob/7b1e0120b0c97e811ea32b67a51e4c9e9ccf4edd/docs/providers/aws/events/http-api.md?plain=1#L133) say to use `type: jwt` while it seems the correct setting is `type: token`

### Service configuration (serverless.yml) content

```yaml
service: authorizers-validation-bug
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    authorizers:
      jwtAuthorizer:
        type: token
        identitySource: $request.header.Authorization
        issuerUrl: https://dev-ayrlnchoa04bhc5w.us.auth0.com/
        audience: foo

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
          authorizer:
            name: jwtAuthorizer
```

### Command name and used flags

serverless package

### Command output

```shell
Environment: darwin, node 20.11.0, framework 3.38.0 (local), plugin 7.2.0, SDK 4.5.1
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Configuration error at 'provider.httpApi.authorizers.jwtAuthorizer': unsupported value

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Environment information

```shell
Framework Core: 3.38.0 (local)
Plugin: 7.2.0
SDK: 4.5.1
```
