### ISSUE TITLE
unrecognized property 'fileSystemConfigs'

### ISSUE THREAD

**Issue by pranavburnwal** [serverless/serverless#12343]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Using the EFS config as mentioned in https://github.com/serverless/serverless/issues/7848#issuecomment-741853547

Error is:
```bash
Warning: Invalid configuration encountered
  at 'functions.app': unrecognized property 'fileSystemConfigs'

Learn more about configuration validation here: http://slss.io/configuration-validation
```

### Service configuration (serverless.yml) content

```yaml
service: serverless-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: develop
  timeout: 30
  region: ap-southeast-1
  vpc:
    securityGroupIds:
      - xx-xxx
    subnetIds:
      - subnet-XXX
      - subnet-XXX
      - subnet-XXX

plugins:
  - serverless-webpack

functions:
  testHandlerTrigger:
    handler: src/<filename>.handler
    events:
       - schedule:
          name: cron-triggers
          rate: rate(15 minutes)
  app: # This always goes last
    handler: src/app.handler
    logRetentionInDays: 30
    ephemeralStorageSize: 1024
    dependsOn:
      - FileSystemMountTarget
    layers:
      - arn:aws:lambda:ap-southeast-1:XXXXXXXXX:layer:chromium118:1
    fileSystemConfigs:
      - localMountPath: /mnt/efs
        arn:
          Fn::GetAtt:
            - FileSystemAccessPoint
            - Arn
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  patterns:
    - '!./**'  # Exclude all files/folders     
    - dist/**
    - package.json

custom:
  webpack:
    webpackConfig: webpack.config.js
    # includeModules: true
    keepOutputDirectory: true
    packager: 'npm'
    forceExclude:
      - aws-sdk

resources:
  Resources:
    FileSystem:
      Type: AWS::EFS::FileSystem
    FileSystemMountTarget:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId:
          Fn::GetAtt:
            - FileSystem
            - FileSystemId
        SecurityGroups:
          - ${self:provider.vpc.securityGroupIds.0}
        SubnetId: ${self:provider.vpc.subnetIds.0}
    FileSystemAccessPoint:
      Type: AWS::EFS::AccessPoint
      DependsOn: FileSystemMountTarget
      Properties:
        FileSystemId:
          Fn::GetAtt:
            - FileSystem
            - FileSystemId
        PosixUser:
          Uid: '1000'
          Gid: '1000'
        RootDirectory:
          CreationInfo:
            OwnerUid: '1000'
            OwnerGid: '1000'
            Permissions: 755
          Path: /
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.34.0 (local) 3.38.0 (global)
Plugin: 6.2.3
SDK: 4.3.2
```
