### ISSUE TITLE
Bug: REST API usage plan ignores 'apiGateway.stage' parameter

### ISSUE THREAD

**Issue by barys-liutkouski** [serverless/serverless#12349]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When deploying a REST API with a usage plan, the generated usage plan template attempts to reference the `provider.stage` parameter, instead of `provider.apiGateway.stage` (when configured).

This results in an error when deploying the stack.

Serverless.yml configuration:

```yaml
provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    stage: api-2 # this is the part that gets ignored
    usagePlan:
      throttle:
        burstLimit: 500
        rateLimit: 1000
```

Resulting UsagePlan resource:
```json
"ApiGatewayUsagePlan": {
  "Type": "AWS::ApiGateway::UsagePlan",
  "DependsOn": "ApiGatewayDeployment1707470569325",
  "Properties": {
    "ApiStages": [
      {
        "ApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "Stage": "dev" // `dev` stage is referenced even though `api-2` is set as the apiGateway stage
      }
    ],
    "Description": "Usage plan for usage-plan-repro dev stage",
    "UsagePlanName": "usage-plan-repro-dev",
    "Throttle": {
      "BurstLimit": 500,
      "RateLimit": 1000
    }
  }
}
```

Root cause seems to be that `usage-plan.js` uses `that.provider.getStage()` to set the stage, instead of `this.provider.getApiGatewayStage()`.

I will submit a PR with a fix.

### Service configuration (serverless.yml) content

```yaml
service: usage-plan-repro
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    stage: api-2
    metrics: true
    usagePlan:
      throttle:
        burstLimit: 500
        rateLimit: 1000
      

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
```

### Command name and used flags

serverless deploy

### Command output

```shell
> serverless deploy

Deploying usage-plan-repro to stage dev (us-east-1)

✖ Stack usage-plan-repro-dev failed to deploy (114s)
Environment: darwin, node 18.18.0, framework 3.38.0 (local), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "personal" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: ApiGatewayUsagePlan (AWS::ApiGateway::UsagePlan)
Resource handler returned message: "API Stage not found: aisl7hvubb:dev (Service: ApiGateway, Status Code: 404, Request ID: 20d73366-b153-41a5-8813-312fa693befd)" (RequestToken: 04927a79-fa5c-c410-0f88-1a14a7a1058c, HandlerErrorCode: NotFound)
```

### Environment information

```shell
Framework Core: 3.38.0 (local)
Plugin: 7.2.0
SDK: 4.5.1
```
