### ISSUE TITLE
serverless-python-requirements bug is some libraries

### ISSUE THREAD

**Issue by Ismola** [serverless/serverless#12342]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

[I opened this thread on stackoverflow](https://stackoverflow.com/questions/77866176/serverless-framework-with-serverless-python-requirements-does-not-work)

I've been using serverless-python-requirements. It works perfectly for me locally, but in production, when I deployed the following thing happened to me: In some lambdas functions, an internal function was used that gave me an error:

`[ERROR] Runtime.ImportModuleError: Unable to import module 'handlerSimulationDatabase': No module named 'cachetools' Traceback (most recent call last):`

This error only happened to me in some lambda functions. Other lambda functions, which also used that internal function that that python library used, works well for me.

In summary: randomly, some lambdas did not recognize some python library.

My requirements.txt

```
cachetools==5.3.2
certificate==2023.11.17
charset-normalizer==3.3.2
dnspython==2.3.0
idna==3.6
numpy==1.21.6
numpy-financial==1.0.0
pymongo==4.6.1
requests==2.31.0
urllib3>=1.26.0,<2.0.0
boto3==1.33.13
```

By doing several tests, I verified that by removing the "custom" field from my serverless, this error did not appear. I would like to know if it is a serverless failure or if it is simply mine because I do not know any serverless framwork configuration

This is how it works:

```
plugins:
  - serverless-offline
  - serverless-python-requirements

# custom:
#   pythonRequirements:
#     dockerizePip: non-linux
#     zip: true
```

### Service configuration (serverless.yml) content

```yaml
service: solar-simulator-back-staging
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  stage: staging
  region: us-east-1
  timeout: 29
  memorySize: 1024
  httpApi:
    cors: true
package:
  patterns:
    - "!node_modules/**"
    - "!Lib/**"
    - "!README.md"
    - "!build/**"
    - "!__pycache__/**"
    - "!Include/**"
    - "!venv/**"
    - "!__pycache__/**"
    - "!.serverless/**"
    - "!.vscode/**"
    - "!node_modules/**"
    - "!preproduction/**"
    - "!production/**"
    - "!Lib/**"
    - "!README.md"
    - "!build/**"
    - "!Include/**"
    # Files
    - "!cspell.json"
    - "!package-lock.json"
    - "!package.json"

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

functions:
  # PV Calculation
  test:
    handler: handlerPV.test
    events:
      - httpApi:
          path: /test
          method: post
  getCalculation:
    handler: handlerPV.getPVCalculation
    events:
      - httpApi:
          path: /getPVCalculation
          method: post
```

### Command name and used flags

serverless deploy

### Command output

```shell
[ERROR] Runtime.ImportModuleError: Unable to import module 'handlerSimulationDatabase': No module named 'cachetools' Traceback (most recent call last):
```

### Environment information

```shell
Framework Core: 3.35.2 (local) 3.38.0 (global)
Plugin: 7.1.0
SDK: 4.4.0
```
