### ISSUE TITLE
DLQ for EventBridge Schedules

### ISSUE THREAD

**Issue by mzl-md** [serverless/serverless#12358]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

AWS Schedules can have a dead letter queue configured, see [AWS::Scheduler::Schedule DeadLetterConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-scheduler-schedule-deadletterconfig.html). Serverless should support this for schedule events with method `scheduler`.

This is related to #8379.

### Proposed solution (optional)

Similar to #12357, PR coming soon. The property is called like the one in sns events redrivePolicy. We could make it an object `deadLetterConfig` with property `arn` or `targetArn` since it is an object in CloudFormation, which implies there could be more properties in the future.

```yaml
functions:
  myFunction:
    handler: src/myFunction.handler
    events:
      - schedule:
          rate: cron(0 13 6 * ? *)
          method: scheduler
          name: my-schedule
          deadLetterTargetArn: !GettAtt MyDLQ.Arn
```
