### ISSUE TITLE
Key needs to be array of objects to trigger event bridge

### ISSUE THREAD

**Issue by vikaspowerschool** [serverless/serverless#12351]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I need to trigger event bridge when I upload a certain file type to a bucket. The code (Please ignore bucket name or other names, I obfuscated it, they are working fine) creates pattern like this

`{
  "detail-type": ["Object Created"],
  "source": ["aws.s3"],
  "detail": {
    "bucket": {
      "name": ["s3BucketName"]
    },
    "object": {
      "key": {
        "suffix": [".imscc"]
      }
    }
  }
}`
                    
     
    
    This does not work. If I manually make key as array of objects, it works, 
    Eg 
    
    ` "object": {
      "key": [{
        "suffix": ".imscc"
      }]
    }`
    
    
    how to solve this ?

### Service configuration (serverless.yml) content

```yaml
`events:
      - eventBridge:
          name: evebt-bridge-trigger-1
          pattern:
            source:
              - "aws.s3"
            detail-type:
              - "Object Created"
            detail:
              bucket:
                name:
                  - s3BucketName
              object:
                key:
                  suffix:
                    - ".imscc"`
```

### Command name and used flags

NA

### Command output

```shell
NA
```

### Environment information

```shell
NA
```
