### ISSUE TITLE
Compose CLI Command Schema

### ISSUE THREAD

**Issue by Mmarzex** [serverless/serverless#12389]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

Framework currently follows a command format in the CLI where the action is the first action followed by an optional resource type and then whatever flags the command may require. However as new features such as Compose were added, we did not adhere to this standard and instead introduced further fragmentation where you would run Compose commands with different syntax. 

In V4, we are going to keep the framework syntax as is, there will be no changes there. However we are going to revise the CLI command standards for Compose & Extensions. 

We are going to introduce the following basic schema,

```
serverless <SERVICE/RESOURCE> <ACTION>
```

The goal is to have Compose and EXT adhere to this model going forward. 

### serverless-compose.yml
```yaml
# Framework Service
service-a:
  path: ./service-a

# EXT Service
service-b:
  path: ./service-b
```

###  Framework Service serverless.yml
```yaml
service: aws-node-express-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
```

### Extension Service serverless.yml
```yaml
my-extension:
  extension: my-extension@latest

my-extension-two:
  extension: my-extension@latest
```

So with these files we can then run commands in the following ways,

#### Run Deploy on a specific service in Compose

```bash
serverless service-a deploy
```

#### Run a command on a specific extension instance in Compose

```bash
serverless service-b my-extension deploy
```
