### ISSUE TITLE
Lambda invokeMode as RESPONSE_STREAM is not set in deployment

### ISSUE THREAD

**Issue by ibrahimjelliti** [serverless/serverless#12409]
### Issue description

Hi,
I am create a lambda with response stream as response type. i define the response type in serverless.yml but its not applying to the deployed lambda or appears as option in "Type": "AWS::Lambda::Url" so the URL takes the default value BUFFERED.

### Context

serverless.yml
```
  Filters:
    handler: src/functions/filters.handler
    memorySize: 128
    timeout: 30
    url:
      invokeMode: RESPONSE_STREAM
```
cloudformation update stack json:
```
    "FiltersLambdaFunctionUrl": {
      "Type": "AWS::Lambda::Url",
      "Properties": {
        "AuthType": "NONE",
        "TargetFunctionArn": {
          "Fn::GetAtt": [
            "FiltersLambdaFunction",
            "Arn"
          ]
        },
        "Cors": {
          "AllowHeaders": [
            "Content-Type",
            "X-Amz-Date",
            "Authorization",
            "X-Api-Key",
            "X-Amz-Security-Token",
            "X-Amzn-Trace-Id"
          ],
          "AllowMethods": [
            "*"
          ],
          "AllowOrigins": [
            "*"
          ]
        }
      }
    },
```
I am expecting to have invoke mode in the json as `RESPONSE_STEAM`
