### ISSUE TITLE
`httpApi` JWT Authorizer based on Docs cannot be found when specified

### ISSUE THREAD

**Issue by flecher0** [serverless/serverless#12457]
### Issue description

As I am adding a JWT authorizer, which is supposed to send requests to the Auth0 authorization server, to each endpoint's Lambda function based on the deployment stage, I am receiving the error below when I tried to deploy by `serverless deploy --stage local --region ap-east-1 --verbose`:

```
✖ Stack myapp-users-local failed to deploy (7s)
Environment: darwin, node 18.18.0, framework 3.38.0, plugin 7.2.0, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Function "localAuthorizer" doesn't exist in this Service
```

### Context

I have defined 3 authorizers under the `provider` section and each is used for a specific stage or a specific group of stages.  Such implementation is based on the `JWT Authorizers` section of the docmentation here: https://www.serverless.com/framework/docs/providers/aws/events/http-api#jwt-authorizers

Each function uses a custom variable that represents a set of function definitions. Each function definition in the set is stage-based and uses an authorizer, which is defined in the `provider.httpApi` section and corresponds to the deployment `stage`.

My serverless.yml is as follows:
```
// serverless.yml
custom:
  stageBasedFunction: # function definition for `dev`, `staging`, `canary`
    createUser:
      handler: dist/createUser.handler
      events:
        - http:
            path: user/create
            method: post
            authorizer:
              name: stageBasedJWTAuthorizer
              scopes:
                - user.id
                - user.email
    getUser:
      handler: dist/getUser.handler
      events:
        - http:
            path: user
            method: get
            authorizer:
              name: stageBasedJWTAuthorizer
              scopes:
                - user.id
                - user.email
    updateUser:
      handler: dist/updateUser.handler
      events:
        - http:
            path: user/{userId}/update
            method: patch
            authorizer:
              name: stageBasedJWTAuthorizer
              scopes:
                - user.id
                - user.email
    deleteUser:
      handler: dist/deleteUser.handler
      events:
        - http:
            path: user/{userId}/delete
            method: delete
            authorizer:
              name: stageBasedJWTAuthorizer
              scopes:
                - user.id
                - user.email
  createUser:
    local:
      handler: dist/createUser.handler
      events:
        - http:
            path: user/create
            method: post
            authorizer:
              name: localAuthorizer
              scopes:
                - user.id
                - user.email
    dev: ${self:custom.stageBasedFunction.createUser}
    staging: ${self:custom.stageBasedFunction.createUser}
    canary: ${self:custom.stageBasedFunction.createUser}
    prod:
      handler: dist/createUser.handler
      events:
        - http:
            path: /user/create
            method: post
            authorizer:
              name: prodAuthorizer
              scopes:
                - user.id
                - user.email
  getUser:
    local:
      handler: dist/getUser.handler
      events:
        - http:
            path: user
            method: get
            authorizer:
              name: localAuthorizer
              scopes:
                - user.id
                - user.email
    dev: ${self:custom.stageBasedFunction.getUser}
    staging: ${self:custom.stageBasedFunction.getUser}
    canary: ${self:custom.stageBasedFunction.getUser}
    prod:
      handler: dist/getUser.handler
      events:
        - http:
            path: user
            method: get
            authorizer:
              name: prodAuthorizer
              scopes:
                - user.id
                - user.email
  updateUser:
    local:
      handler: dist/updateUser.handler
      events:
        - http:
            path: user/{userId}/update
            method: patch
            authorizer:
              name: localAuthorizer
              scopes:
                - user.id
                - user.email
    dev: ${self:custom.stageBasedFunction.updateUser}
    staging: ${self:custom.stageBasedFunction.updateUser}
    canary: ${self:custom.stageBasedFunction.updateUser}
    prod:
      handler: dist/updateUser.handler
      events:
        - http:
            path: user/{userId}/update
            method: patch
            authorizer:
              name: prodAuthorizer
              scopes:
                - user.id
                - user.email
  deleteUser:
    local:
      handler: dist/deleteUser.handler
      events:
        - http:
            path: user/{userId}/delete
            method: delete
            authorizer:
              name: localAuthorizer
              scopes:
                - user.id
                - user.email
    dev: ${self:custom.stageBasedFunction.deleteUser}
    staging: ${self:custom.stageBasedFunction.deleteUser}
    canary: ${self:custom.stageBasedFunction.deleteUser}
    prod:
      handler: dist/deleteUser.handler
      events:
        - http:
            path: user/{userId}/delete
            method: delete
            authorizer:
              name: prodAuthorizer
              scopes:
                - user.id
                - user.email
provider:
  name: aws
  endpointType: regional
  runtime: nodejs20.x
  region: ${opt:region, 'ap-east-1'} # Default to ap-east-1 if not specified
  stage: ${opt:stage, 'dev'} # Default to dev if not specified
  httpApi:
    authorizers:
      localAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://myapp-dev.jp.auth0.com
        audience:
          - https://myapp-authorizer-identifier
      stageBasedJWTAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://myapp-${self:provider.stage}.jp.auth0.com
        audience:
          - https://myapp-authorizer-identifier
      prodAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://myapp.jp.auth0.com
        audience:
          - https://myapp-authorizer-identifier
functions:
  createUser: ${self:custom.createUser.${self:provider.stage}}
  updateUser: ${self:custom.updateUser.${self:provider.stage}}
  deleteUser: ${self:custom.deleteUser.${self:provider.stage}}
  getUser: ${self:custom.getUser.${self:provider.stage}}
```
