### ISSUE TITLE
The Serverless diff ignores some aspects of the CloudFormation template

### ISSUE THREAD

**Issue by dmitry-serkoff** [serverless/serverless#12488]
### Issue description

Deploy lambda function with cron event trigger
```
functionName:
    role: arn:aws:iam::${self:custom.config.accountId}:role/service
    timeout: 900
    reservedConcurrency: 200
    handler: handler.default
    name: function-name
    events:
      - schedule:
          name: event-name
          rate: rate(5 minutes)
          enabled: false
```
redeploy this function with events - schedule - enabled: true

I used different variations of `sls deploy` command. I tried `sls deploy`, `sls deploy function --force -u` and other combination, but trigger configuration didn't changed it stay disabled.

### Context

I compare cloudformation templates and found a differnce.

AWS cloudformation template:
```
"FunctionEventsRuleSchedule1": {
	"Type": "AWS::Events::Rule",
	"Properties": {
		"ScheduleExpression": "rate(5 minutes)",
		"State": "DISABLED",
		"Name": "function-name",
		"Targets": [
			{
				"InputTransformer": {
					"InputTemplate": "{\"eventTime\":<eventTime>, \"env\":\"live\"}",
					"InputPathsMap": {
						"eventTime": "$.time"
					}
				},
				"Id": "functionSchedule"
			}
		]
	}
},
```
Genrated cloudformation-template-update-stack.json fragment

```
"FunctionEventsRuleSchedule1": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "ScheduleExpression": "rate(5 minutes)",
        "State": "ENABLED",
        "Name": "function-name",
        "Targets": [
          {
            "InputTransformer": {
              "InputTemplate": "{\"eventTime\":<eventTime>, \"env\":\"live\"}",
              "InputPathsMap": {
                "eventTime": "$.time"
              }
            }
          }
        ]
      }
    },
```
