### ISSUE TITLE
Serverless stop create s3 trigger on deploy

### ISSUE THREAD

**Issue by luis-guts** [serverless/serverless#12480]
### Issue description

Using serverless v3
Since may 13 the serverless deploy is not creating the s3 trigger [on](s3:ObjectCreated:*) on a existing bucket with no changes in the serverless.yaml.
This issue can be related to the serverless framework lambda custom-resources with node16 runtime hardcoded, wich will be deprecated soon, but I'm not sure.

### Context

```
  processor:
    enabled: true
    handler: src/handlers/processor.handler
    events:
      - s3:
          bucket: ${self:provider.stage}-github-webhook-dispatcher-github-webhook-messages
          event: s3:ObjectCreated:*
          existing: true
```
