### ISSUE TITLE
npm install pulling v4 breaking CI

### ISSUE THREAD

**Issue by LorenzoRogai** [serverless/serverless#12503]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

The "npm install serverless" command now pulls the v4 breaking all the CIs

was this announced? I read that the v4 is still in beta

This workflow now fails and it was working fine before

```
name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Serverless
        run: sudo npm install -g serverless
      - name: Test
        run: |
          serverless --version
```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```
