### ISSUE TITLE
[Kafka Trigger] Ease multiple topics consumption

### ISSUE THREAD

**Issue by Giovannini** [serverless/serverless#12527]
### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Use case description

The Serverless configuration for Kafka trigger only enables the consumption of [a single topic per trigger](https://github.com/serverless/serverless/blob/1b14f1da249bc69def2b8ee085d69ab8c9e4c1bc/lib/plugins/aws/package/compile/events/kafka.js#L92). AWS already enables to [reference multiple topics](https://docs.aws.amazon.com/lambda/latest/dg/with-kafka.html#services-kafka-parms) on a single trigger so this is not a technical limitation.

### Proposed solution (optional)

The configuration parameters can be updated to load either a list of topics or a single topic and that list can be [sent to AWS](https://github.com/serverless/serverless/blob/1b14f1da249bc69def2b8ee085d69ab8c9e4c1bc/lib/plugins/aws/package/compile/events/kafka.js#L183).

To keep compatibility with existing API (which uses `topic` singular), we may add a new field `key` and ensure that only one of the two is used. This could look like this:

```
events:
  - kafka:
      accessConfigurations: ...
      topics:
        - myTopic-1
        - myTopic-2
      consumerGroupId: ...
      bootstrapServers:
        - ...
```
