### ISSUE TITLE
Unable to Disable esbuild Bundling in Serverless4: 'Cannot use "external" without "bundle"'

### ISSUE THREAD

**Issue by NicoHinderling** [serverless/serverless#12530]
### Issue description

Hello, I tried to upgrade to serverless4 this week and while I'm very excited about the new changes, I want to test how things would work with everything new **except** the bundling happening.

Following the updated docs in the README, I added

```
build:
  esbuild:
    bundle: false
```

near the top of my serverless.yml file and when I ran `npx sls package` I get the following error:

<img width="1005" alt="image" src="https://github.com/serverless/serverless/assets/9902528/73d6d7ac-fa0a-4dfd-ae41-2bf559df82c9">

I took a quick look and I'm guessing the issue [is on this line](https://github.com/serverless/serverless/blob/main/lib/plugins/esbuild/index.js#L300).

### Context

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.0.24
- Service Config File: serverless.yml
- Service Name: internalSlackbot
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-west-1
- Command: package

## Service Path
/Users/nicolashinderling/dev/emerge/backend/services/internalSlackbot

## Service Config
```
service: internalSlackbot
projectDir: ../../
frameworkVersion: '3'
configValidationMode: error
build:
  esbuild:
    bundle: false

provider:
  name: aws
  region: us-west-1
  environment:
    SERVERLESS_STAGE: ${sls:stage}
  deploymentMethod: direct
  vpc: ${file(../../serverless.common.yml):vpc}
  runtime: nodejs20.x
  architecture: arm64
  versionFunctions: false
  iam:
    role:
      managedPolicies:
        {redacted}
functions:
  testNico:
    handler: src/engagement/index.nicoHandler
    timeout: 3
    maximumRetryAttempts: 0
    memorySize: 1024
    events:
      - httpApi:
          method: 'GET'
          path: '/slack/testNico'
  engagementUpdate:
    handler: src/engagement/index.update
    timeout: 60
    memorySize: 4096
    maximumRetryAttempts: 0
    events:
      - schedule:
          rate: rate(24 hours)
```
