### ISSUE TITLE
V4 Broken error reporting: functionHandler is not defined

### ISSUE THREAD

**Issue by darioackermann** [serverless/serverless#12542]
### Issue description

This has occured after the v4 version of serverless is released. Before pinning to v3, our serverless commmand would try to package, but fail with an odd error as follows:

```$ serverless package
✖ functionHandler is not defined
ReferenceError: functionHandler is not defined
    at file:///root/.serverless/releases/4.0.27/package/dist/sf-core.js:795:36085
    at Array.some (<anonymous>)
    at Esbuild.WillEsBuildRun (file:///root/.serverless/releases/4.0.27/package/dist/sf-core.js:795:35823)
    at Meta.addAnalysisEventToBatch (file:///root/.serverless/releases/4.0.27/package/dist/sf-core.js:795:51314)
    at file:///root/.serverless/releases/4.0.27/package/dist/sf-core.js:1044:1638
    at async route (file:///root/.serverless/releases/4.0.27/package/dist/sf-core.js:1044:1182)
    at async Object.run2 [as run] (file:///root/.serverless/releases/4.0.27/package/dist/sf-core.js:1044:4534)
    at async Object.handler (file:///root/.serverless/releases/4.0.27/package/dist/sf-core.js:1044:9037)
```

If I understood the docs correctly, it should rather complain about a missing access / license key, this seems like a bug in the package itself... Also, 4.0.27 is not even yet released, I am a bit confused on how this one managed to make it onto the machine (?)

Pinning to v3 resolves the issue, but you might want to look into this regardless.

### Context

serverless.yml can be as simple as 

```yml
service: main

provider:
    name: aws
    runtime: nodejs20.x
    region: eu-central-1

functions:
  main:
    handler: dist/serverless.handler

plugins:
    - serverless-jetpack
```
