### ISSUE TITLE
V4: ${opt:stage} does not resolve when using "-s" but does when using "--stage"

### ISSUE THREAD

**Issue by jaffadog** [serverless/serverless#12545]
### Issue description

when deploying to AWS using:
serverless deploy -s v1

${opt:stage} does not resolve and results in unexpected results when using things like this in you yml:
  environment:
    bucket: ${self:custom.${opt:stage, self:provider.stage}.bucket}

If instead you deploy to AWS using:
serverless deploy --stage v1

then things wok fine.

Documentation states:
--stage or -s The stage in your service that you want to deploy to.
(ref https://www.serverless.com/framework/docs-providers-aws-cli-reference-deploy)

### Context

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.0.28
- Service Config File: serverless.yml
- Service Name: fastseas-oscar2-data
- Service Runtime: python3.9
- Service Stage: test
- Service Region: us-east-1
- Command: deploy --s v1
- Error Code: MISSING_VARIABLE_RESULT

## Service Path
/home/ec2-user/environment/fastseas/fastseas-get-oscar2-data

## Error Message
Cannot resolve '${opt:stage}' variable at 'provider.environment.test1'. None of the variables returned a value and no default value was provided. Please check your variable definitions or provide a default value.

## Error Stacktrace
```
at _ResolverManager.resolve (file:///home/ec2-user/.serverless/releases/4.0.28/package/dist/sf-core.js:1041:21692)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async #handlePlaceholderNode (file:///home/ec2-user/.serverless/releases/4.0.28/package/dist/sf-core.js:1041:20280)
at async file:///home/ec2-user/.serverless/releases/4.0.28/package/dist/sf-core.js:1041:18419
at async processNodeAndHandleCompletion (file:///home/ec2-user/.serverless/releases/4.0.28/package/dist/sf-core.js:1041:13702)
```

## Service Config
```
service: fastseas-oscar2-data
provider:
  name: aws
  stage: test
  runtime: python3.9
  memorySize: 128
  timeout: 300
  versionFunctions: false
  role: arn:aws:iam::XXXXX:role/fastseas-service-role
  region: ${opt:region, 'us-east-1'}
  deploymentBucket: fastseas-serverless-deployment-${self:provider.region}
  environment:
    bucket: ${self:custom.${opt:stage, self:provider.stage}.bucket}
    HOME: /tmp
    machine: urs.earthdata.nasa.gov
    login: fastseas
    password: XXXXXX
    PODAAC_LOGLEVEL: DEBUG
    test1: ${opt:stage}
custom:
  test:
    bucket: fastseas-gribs-test-${self:provider.region}
    #name: fastseas-get-oscar2-data-test
  v1:
    bucket: fastseas-gribs-${self:provider.region}
    #name: fastseas-get-oscar2-data
functions:
  get:
    handler: handler.lambda_handler
    #name: ${self:custom.${opt:stage, self:provider.stage}.name}
    description: Gets OSCAR grib files from NOAA FTP servers
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
