### ISSUE TITLE
Serverless4: Using esbuild's "packages: external" flag doesn't seem to work

### ISSUE THREAD

**Issue by NicoHinderling** [serverless/serverless#12551]
### Issue description

Hi again 👋 I'm trying to onboard to serverless4 and while I love esbuild, I have been struggling with some issues. Here's another:

esbuild has a `packages` flag [in their docs](https://esbuild.github.io/api/#packages) which it seems like we should be able to use via build -> esbuild:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/cdf9fd89-e4b1-466c-a1d1-c83ae62796f0/8fc5cbd1-7df3-414f-8bad-ca047ae31a45?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi9jZGY5ZmQ4OS1lNGIxLTQ2NmMtYTFkMS1jODNhZTYyNzk2ZjAvOGZjNWNiZDEtN2RmMy00MTRmLThiYWQtY2EwNDdhZTMxYTQ1IiwiaWF0IjoxNzE2OTk0NTE1LCJleHAiOjMzMjg3NTU0NTE1fQ.UGblQ5rSSG5yTDwtXgIzJ8YR7fOAOZr9y7fvBLZRK4A)

When I try using it though:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/44174d8f-e765-45a3-898c-dea4e0ae8d66/d26e0e55-8998-489b-ba79-bd993d37afc4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi80NDE3NGQ4Zi1lNzY1LTQ1YTMtODk4Yy1kZWE0ZTBhZThkNjYvZDI2ZTBlNTUtODk5OC00ODliLWJhNzktYmQ5OTNkMzdhZmM0IiwiaWF0IjoxNzE2OTk0NTE1LCJleHAiOjMzMjg3NTU0NTE1fQ.HkyldtKej-a9beaHfcCQdifIVSlG-bt-YRW9O5MsvVM)

none of my node modules are pulled out:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/6e4ddb81-e77e-4daa-a09a-8d2a47a23cd2/1c341f4f-4bc6-4e90-b5a1-2a2d0a225780?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi82ZTRkZGI4MS1lNzdlLTRkYWEtYTA5YS04ZDJhNDdhMjNjZDIvMWMzNDFmNGYtNGJjNi00ZTkwLWI1YTEtMmEyZDBhMjI1NzgwIiwiaWF0IjoxNzE2OTk0NTE1LCJleHAiOjMzMjg3NTU0NTE1fQ.H36jcqDhnNw3Ir7MbKQ3KktcTw-KyuYb3P2nNeYy0aY "=207x")

When I try using the `external` flag instead:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/37a9b7b2-9ce4-4345-81da-e336b01df0a6/094393fc-99e8-4795-8fe0-d5c70a598eaf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi8zN2E5YjdiMi05Y2U0LTQzNDUtODFkYS1lMzM2YjAxZGYwYTYvMDk0MzkzZmMtOTllOC00Nzk1LThmZTAtZDVjNzBhNTk4ZWFmIiwiaWF0IjoxNzE2OTk0NTE1LCJleHAiOjMzMjg3NTU0NTE1fQ.FBzr3HpMPdDyV4hVsikmiZ3ghflXDf2KIAVTeaCo_ZU)

I DO see those modules pulled out:

![image](https://uploads.linear.app/ca066160-e400-4ed9-98d8-d8fef15dbdf2/0c27959e-ce0a-40ac-bcbe-4bc8fe252bb8/ec3015cc-39a8-4418-9bf0-63e3f86af5f4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NhMDY2MTYwLWU0MDAtNGVkOS05OGQ4LWQ4ZmVmMTVkYmRmMi8wYzI3OTU5ZS1jZTBhLTQwYWMtYmNiZS00YmM4ZmUyNTJiYjgvZWMzMDE1Y2MtMzlhOC00NDE4LTliZjAtNjNlM2Y4NmFmNWY0IiwiaWF0IjoxNzE2OTk0NTE1LCJleHAiOjMzMjg3NTU0NTE1fQ.wPosTawiiQOyABd1Q25AAq072BhmdUlTxXm904EQrxQ "=259x")

Perhaps I'm missing something! Let me know :) 🙏

### Context

# Service Overview

* Serverless Framework Version: 4.0.30
* Service Config File: serverless.yml
* Service Name: internalSlackbot
* Service Runtime: nodejs20.x
* Service Stage: dev
* Service Region: us-west-1
* Command: package

## Service Config

```
service: internalSlackbot
projectDir: ../../
frameworkVersion: '4'
configValidationMode: error
build:
  esbuild:
    external:
      - 'prisma'
      - '@prisma/client'
provider:
  name: aws
  region: us-west-1
  environment:
    SERVERLESS_STAGE: ${sls:stage}
  deploymentMethod: direct
  vpc: ${file(../../serverless.common.yml):vpc}
  runtime: nodejs20.x
  architecture: arm64
  versionFunctions: false
  iam:
    role:
      managedPolicies:
        - {omitted by me}
functions:
  testNico:
    handler: src/engagement/nico.nicoHandler
    timeout: 3
    maximumRetryAttempts: 0
    memorySize: 1024
    events:
      - httpApi:
          method: 'GET'
          path: '/slack/testNico'
  testNicoTWO:
    handler: src/appsize/nicoTwo.nicoHandler
    timeout: 3
    maximumRetryAttempts: 0
    memorySize: 1024
    events:
      - httpApi:
          method: 'GET'
          path: '/slack/testNicoTwo'
```
