### ISSUE TITLE
Unable to set `maximumConcurrency` on `events.sqs`

### ISSUE THREAD

**Issue by harryjamesuk** [serverless/serverless#12579]
### Issue description

Setting `maximumConcurrency` as described [here](https://www.serverless.com/framework/docs-providers-aws-events-sqs#setting-the-maximum-concurrency) produces this warning when using the `aws` provider:

```
Warning: Invalid configuration encountered
  at 'functions.example-function.1.sqs': unrecognized property 'maximumConcurrency'
```

The deployed function's event also does not have `maximumConcurrency` set on it in AWS after going in to check.

### Context

**Example Configuration**

```yml
service: example-service
app: example-service
 
frameworkVersion: '3'
 
provider:
  name: aws
 
functions:
  example-function:
    handler: src/Handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ExampleQueue
              - Arn
          maximumConcurrency: 2 # not recognised
 
resources:
  Resources:
    ExampleQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: example-queue
```

`sls -v` output:

```
Framework Core: 3.39.0
Plugin: 7.2.3
SDK: 4.5.1
```
