### ISSUE TITLE
Custom resource deployment hangs forever

### ISSUE THREAD

**Issue by sean-legitscript** [serverless/serverless#12597]
### Issue description

We have a lambda that uses S3 events to be triggered.
```
processSpreadsheet:
  architecture: arm64
  memorySize: 3008
  timeout: 900
  handler: src/_handlers.processSpreadsheet
  events:
    - s3:
        bucket: example-bucket
        event: s3:ObjectCreated:*
        existing: true
        forceDeploy: true
```

When we deploy this the first time, it and all of the other lambdas are successfully deployed. However, upon subsequent deployments, the following happens:
- The sls deployment hangs
- In the Cloudformation Stack Resources section, I found the following:

```
Logical ID | Physical ID | Type | Status | Module
CustomDashresourceDashexistingDashs3LambdaFunction | example-STAGE-custom-resource-existing-s3 | AWS::Lambda::Function | UPDATE_COMPLETE
ProcessSpreadsheetCustomS31 | CustomResourceExistingS3 | Custom::S3 | UPDATE_IN_PROGRESS
```

- After 60 minutes, the stack goes into ROLLBACK_IN_PROGRESS with the following error messages:

_The following resource(s) failed to update: [ProcessSpreadsheetCustomS31]._
_CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [02a99d31-512c-4a2f-a989-a932bee1a310]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version._

- I've tried finding those cloudwatch logs but they don't seem to exist anywhere. After another 60 minutes, the stack goes into UPDATE_ROLLBACK_FAILED and gives me the same error messages it did when it went into ROLLBACK_IN_PROGRESS.

### Context

**Serverless Version**: 3.38.0

**Plugins**:
  - serverless-api-gateway-caching
  - serverless-v2-aws-documentation
  - serverless-domain-manager
  - serverless-offline
  - serverless-step-functions
  - serverless-plugin-aws-alerts
  - serverless-webpack
  - serverless-dependson-plugin
