### ISSUE TITLE
`sls info -v` not showing stack outputs

### ISSUE THREAD

**Issue by mikybars** [serverless/serverless#12603]
### Issue description

This is all the output I'm getting:
```
(node:64217) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
service: url-shortener-resources
stage: dev
region: eu-west-1
stack: url-shortener-resources-dev
```

### Context

(node:63719) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.1.4
- Service Config File: serverless.02.resources.yml
- Service Name: url-shortener-resources
- Service App: url-shortener
- Service Stage: dev
- Service Region: eu-west-1

## Service Path
/Users/miguel.perez/dev/mikybars/miguelito-api

## Command
info --version true,--config serverless.02.resources.yml

## Service Config
```
app: url-shortener
service: ${self:app}-resources
frameworkVersion: '4'
useDotenv: true
configValidationMode: error
disabledDeprecations:
  - LAMBDA_HASHING_VERSION_V2
provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
custom:
  rootDomain: ${cf:${self:app}-dns.RootDomain}
  certificateArn: ${env:CERTIFICATE_ARN}
  accessTokenValidity:
    dev: 60
    pro: 5
  idTokenValidity:
    dev: 60
    pro: 5
  refreshTokenValidity:
    dev: 600
    pro: 60
stages:
  dev:
    params:
      accessTokenValidity: 60
  pro:
    params:
      accessTokenValidity: 5
resources:
  - Conditions:
      IsPro: !Equals ["${self:provider.stage}", pro]
      IsDev: !Not [Condition: IsPro]
  - ${file(resources/web.resources.yml)}
  - ${file(resources/db.resources.yml)}
  - ${file(resources/users.resources.yml)}
  - ${file(resources/dns.resources.yml)}
  - Outputs:
      UserPoolArn:
        Value: !GetAtt CognitoUserPool.Arn
      UserPoolId:
        Value: !Ref CognitoUserPool
      UserPoolClientId:
        Value: !Ref CognitoUserPoolClient
      UserPoolDomain:
        Value: !If [IsPro, !Ref CognitoUserPoolDomain, !Ref CognitoUserPoolDomainPrefix]
      RedirectBucketName:
        Value: !Ref RedirectBucket
      LinksTable:
        Value: !Ref LinksTable
      UsersTable:
        Value: !Ref UsersTable
      UniquesTable:
        Value: !Ref UniquesTable
      CountersTable:
        Value: !Ref CountersTable
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
