### ISSUE TITLE
Dev command does not work when custom IAM role set

### ISSUE THREAD

**Issue by darbio** [serverless/serverless#12619]
### Issue description

When I run `sls dev` with a stack which uses `serverless-iam-roles-per-function` the `aws:iot:*` permission is not added to the IAM role for the function when `sls dev` is run.

The function hangs as it does not have the IoT permissions for the instrumentation.

### Context

N/A

**Comment by eahefnawy** [comment]
@darbio Thanks for reporting this issue. I'll look into it asap.

To help me reproduce it, could you please share your YAML config? (feel free to redact any sensitive info)

**Comment by darbio** [comment]
```yaml
provider:
  name: aws
  runtime: nodejs20.x

functions:
  api_v1_test_get:
    handler: api/v1/test/get.handler
    events:
      - http:
          path: /test
          method: get
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - cognito-idp:ListUsers
        Resource: abc
plugins:
  - serverless-iam-roles-per-function
```
