### ISSUE TITLE
No forceInclude equivalent in the new build.esbuild configuration

### ISSUE THREAD

**Issue by kdybicz** [serverless/serverless#12615]
### Issue description

Based on the documentation found [here](https://www.serverless.com/framework/docs/providers/aws/guide/building) and some tests I've run locally I see that there is one important piece of functionality missing in the new ESBild configuration. I see that there is an equivalent to:
```
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
```
from the "deprecated" `serverless-webpack` plugin, in form of:
```
build:
  esbuild:
    # NPM packages to not be bundled, as well as not included in node_modules
    # in the zip file uploaded to Lambda. By default this will be set to aws-sdk
    # if the runtime is set to nodejs16.x or lower or set to @aws-sdk/* if set to nodejs18.x or higher.
    exclude:
```

But there is no equivalent to:
```
custom:
  webpack:
    includeModules:
      forceInclude:
        - '@keyv/redis'
```

It's making migration to Serverless v4 impossible in some cases, that's why I'm raising it as a bug instead of a feature request.

### Context

# Service Overview
- Serverless Framework Version: 4.1.4
- Service Config File: serverless.yml
- Service Runtime: nodejs20.x
- Service Stage: staging
- Service Region: eu-west-1
- Command: package --stage staging

**Comment by garethmcc** [comment]
Thanks @kdybicz . One thing to mention is that 4.1.5 went out with some changes that may or may not have helped with this. If possible, could you confirm while we look into this.

**Comment by kdybicz** [comment]
Hey @garethmcc! I'm afraid I don't see anything useful in the Changelog. I've tried again with `include` and `forceInclude` in the `build.esbuild` for the sls 4.1.5, but it gave me the same error message:
```
✖ Build failed with 1 error:
/Users/kamil/.serverless/releases/4.1.5/package/node_modules/esbuild/lib/main.js:253:12: ERROR: Invalid option in build() call: "forceInclude"
ServerlessError2: Build failed with 1 error:
/Users/kamil/.serverless/releases/4.1.5/package/node_modules/esbuild/lib/main.js:253:12: ERROR: Invalid option in build() call: "forceInclude"
    at Esbuild._build (file:///Users/kamil/.serverless/releases/4.1.5/package/dist/sf-core.js:1026:11533)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async before:package:createDeploymentArtifacts (file:///Users/kamil/.serverless/releases/4.1.5/package/dist/sf-core.js:1026:4371)
```

**Comment by Mmarzex** [comment]
Hi @kdybicz , it sounds like what you are looking for is the `external` property. Any npm modules you set there are not included and instead will be put in a `node_modules` folder in the resulting zip file that gets uploaded to AWS.

**Comment by kdybicz** [comment]
@Mmarzex well, I guess I would like this module to be included instead :)

**Comment by Mmarzex** [comment]
@kdybicz Included in what? If you want it included in the deployment package but not bundled you would use `external`, which I believe is what you are asking for here from my understanding of forceInclude.

**Comment by kdybicz** [comment]
To make it clear, as the `@keyv/redis` is more referenced in code directly, but is required for the code to work I needed to use:
```
custom:
  webpack:
    includeModules:
      forceInclude:
        - '@keyv/redis'
```
to be bundled at all: https://github.com/apollographql/apollo-server/issues/6682#issuecomment-1184732168

I will test the `external` later Today and let you know if that has solved my issue.
