### ISSUE TITLE
Params top-level property is not loading when defined in a file

### ISSUE THREAD

**Issue by salemol** [serverless/serverless#12623]
### Issue description

In V3, we're using the `params` top-level property to define our parameters. which is defined in a yml file and referenced in the `serverless.yml` file as below,
- serverless.yml:
```
service: my-service
params: ${file(env.yml)}
```
- env.yml:
```
default:
  XXX: "default"
staging:
  XXX: "staging"
prod:
  XXX: "prod"
```

When upgrading to V4,  it seems like params are not being correctly referenced or loaded and getting the below error when deploying. 
![image](https://github.com/serverless/serverless/assets/60991409/427a5e7b-6f31-4b40-829f-7261745bde14)
I've tried copying the content of `env.yml` file into the `serverless.yml` file and it worked. 

Is there a change to how the file is being loaded?

**Comment by austencollins** [comment]
@salemol Thanks for reporting. We'll look into this.

There are a handful of workarounds for this in the interim. I recommend trying our new `stages` property, which supports `params`. I've just tested it and it supports your use-case. Here's how to do it:

```yaml
# serverless.yml 

org: acmeorg
app: framework-v4
service: v4-service-1

stages:
  default:
    params: ${file(env.yml):default}
  prod:
    params: ${file(env.yml):prod}

provider:
  name: aws
  runtime: nodejs20.x

functions:
  one:
    handler: handler.hello
    environment:
      FOO1: ${param:foo1}
      FOO2: ${param:foo2}
    events:
      - http:
          path: one/two
          method: get
```

```env.yml
# env.yml

default:
  foo1: bar1
  foo2: bar2
prod:
  foo1: bar1-prod
  foo2: bar2-prod
```

```bash
# CLI

$ serverless print

org: acmeorg
app: framework-v4
service: v4-service-1
stages:
  default:
    params:
      foo1: bar1
      foo2: bar2
  prod:
    params: ${file(env.yml):prod}
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  versionFunctions: true
functions:
  one:
    handler: handler.hello
    environment:
      FOO1: bar1
      FOO2: bar2
    events:
      - http:
          path: one/two
          method: get
    name: v4-service-1-dev-one
```
