### ISSUE TITLE
V4: serverless dev command does not work in eu-south-1 region.

### ISSUE THREAD

**Issue by gsavvidis96** [serverless/serverless#12627]
### Issue description

serverless dev command does not work specifically with eu-south-1. It works with other regions that I tried, like eu-central-1 or us-east-1. What I noticed is that it does not try to create the resources but tries to connect to connect immediately.

### Context

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.1.5
- Service Config File: serverless.yml
- Service Name: test
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: eu-south-1
- Command: dev

## Service Path
C:\Users\sav\Desktop\gym-appointments-api

## Error Message
Inaccessible host: `iot.eu-south-1.amazonaws.com' at port `undefined'. This service may not be available in the `eu-south-1' region.

## Error Stacktrace
```
at file:///C:/Users/sav/.serverless/releases/4.1.5/package/dist/sf-core.js:817:36
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async persistentRequest (file:///C:/Users/sav/.serverless/releases/4.1.5/package/dist/sf-core.js:816:1961)
```

## Error Code
AWS_IOT_DESCRIBE_ENDPOINT_UNKNOWN_ENDPOINT

## Service Config
```
service: test
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-south-1
  profile: gsavvidis
  deploymentMethod: direct
  httpApi:
    cors: true
functions:
  custom:
    handler: handler.handler
```

# Service Overview
- Serverless Framework Version: 4.1.5
- Command: support --summary true
