### ISSUE TITLE
existing:true S3 Bucket Still Tries to get deleted

### ISSUE THREAD

**Issue by jonathan-bird** [serverless/serverless#12636]
### Issue description

In our serverless.yml file, we set existing: true and forceDeploy: true and yet the process still fails on the S3 trigger, so we delete this manually (even though I thought forceDeploy: true is meant to fix this), and then it tries to delete our S3 bucket even though we have existing: true.

We are running the latest serverless, updated using `serverless update` just before running `serverless deploy`.

Here is our serverless.yml file:

```
service:image-optimizer-v8

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  memorySize: 2056
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "cloudfront:CreateInvalidation"
      Resource: 
        - "arn:aws:s3:::product-images-optimizer-v8"
        - "arn:aws:s3:::product-images-optimizer-v8/*"
        - "arn:aws:cloudfront::xxxxxx:distribution/xxxxxx"
        - "arn:aws:cloudfront::xxxxxx:distribution/xxxxxx/*"
  environment:
    AWS_CLIENT_TIMEOUT: 60000

functions:
  s3_statements:
    handler: app.handler
    environment:
      BUCKET:product-images-optimizer-v8
      CLOUDFRONT_DISTRIBUTION: xxxxxx
    timeout: 60
    reservedConcurrency: 100
    events:
      - s3:
          bucket: product-images-optimizer-v8
          event: s3:ObjectCreated:*
          rules:
            - prefix: originals/
          existing: true
          forceDeploy: true
```

Errors:

First one was the S3 notification trigger which we got around by deleting the trigger:

```
✖ An error occurred: S3UnderscorestatementsCustomS31 - Received response status [FAILED] from custom resource. Message returned: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.
```

Then the important one where it tried to delete our S3 bucket:

```
✖ An error occurred: S3BucketProductimagesoptimizerv8 - Resource handler returned message: "The bucket you tried to delete is not empty (Service: S3, Status Code: 409, Request ID: NXNCDG9X6PRMD5N6, Extended Request ID: tnw52HexrctjKIkz4rGC6vm1Stud2shJXSS4oJ15KfbCbMRCzSeDwZGmZUNvhrfjLdIK+Pab0xLC8mX18xmypA==)" (RequestToken: 787f927c-00bf-31dd-e47c-13529335a1b8, HandlerErrorCode: GeneralServiceException).
```

### Context

# Service Overview
- Serverless Framework Version: 4.1.6
- Service Config File: serverless.yml
- Service Name: image-optimizer-v8
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: ap-southeast-2
- Command: deploy

## Service Path
/Users/jonathanbird/Dev/serverless-image-optimizer

## Error Message
An error occurred: S3BucketProductimagesoptimizerv8 - Resource handler returned message: "The bucket you tried to delete is not empty (Service: S3, Status Code: 409, Request ID: NXNCDG9X6PRMD5N6, Extended Request ID: tnw52HexrctjKIkz4rGC6vm1Stud2shJXSS4oJ15KfbCbMRCzSeDwZGmZUNvhrfjLdIK+Pab0xLC8mX18xmypA==)" (RequestToken: 787f927c-00bf-31dd-e47c-13529335a1b8, HandlerErrorCode: GeneralServiceException).

## Error Stacktrace
```
at file:///Users/jonathanbird/.serverless/releases/4.1.6/package/dist/sf-core.js:835:830
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async AwsDeploy.update (file:///Users/jonathanbird/.serverless/releases/4.1.6/package/dist/sf-core.js:835:25478)
```

## Error Code
AWS_CLOUD_FORMATION_UPDATE_STACK_INTERNAL_S3_BUCKET_DELETE_FAILED

## Service Config
```
service: image-optimizer-v8
provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  memorySize: 2056
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - "cloudfront:CreateInvalidation"
      Resource:
        - "arn:aws:s3:::product-images-optimizer-v8"
        - "arn:aws:s3:::product-images-optimizer-v8/*"
        - "arn:aws:cloudfront::xxxxxxxx:distribution/xxxxxxxx"
        - "arn:aws:cloudfront::xxxxxxxx:distribution/xxxxxxxx/*"
  environment:
    AWS_CLIENT_TIMEOUT: 60000
functions:
  s3_statements:
    handler: app.handler
    environment:
      BUCKET: product-images-optimizer-v8
      CLOUDFRONT_DISTRIBUTION: xxxxxxxx
    timeout: 60
    reservedConcurrency: 100
    events:
      - s3:
          bucket: product-images-optimizer-v8
          event: s3:ObjectCreated:*
          rules:
            - prefix: originals/
          existing: true
          forceDeploy: true
```

# Service Overview
- Serverless Framework Version: 4.1.6
- Command: support
