### ISSUE TITLE
API Gateway Rest API V1 Access Logging creation

### ISSUE THREAD

**Issue by nbcchen** [serverless/serverless#12670]
### Issue description

Cannot create access log with the direction here https://www.serverless.com/framework/docs/providers/aws/events/apigateway#logs

### Context

Framework Core: 3.39.0 (local)
Plugin: 7.2.3
SDK: 4.5.1

I added this section to serverless.yml
```yaml
provider:
  name: aws
  logs:
    restApi:
      accessLogging: true
      format: '{ "requestId":"$context.requestId",   "ip": "$context.identity.sourceIp", "status":"$context.status", "protocol":"$context.protocol" }'
  apiGateway:
    description: blah blah
        apiKeys:
          - name: abc
        resourcePolicy:
          - Effect: Allow
      ...
```

But I don't see access loging enabled in the CloudFormation template nor in the AWS console.
