### ISSUE TITLE
Unable to bundle @aws-sdk in v4

### ISSUE THREAD

**Issue by faradaytrs** [serverless/serverless#12674]
### Issue description

I override default configuration and i wish @aws-sdk to be bundled, but i can clearly see that it's excluded automatically just like in default behavior.
````yaml
build:
    esbuild:
        bundle: true
        minify: false
        exclude:
            - sharp
        external:
            - sharp
 ````

### Context

# Service Overview
- Serverless Framework Version: 4.1.11
- Service Config File: serverless.yml
- Service Name: caprica
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: eu-central-1
- Command: deploy --stage dev

## Service Path
/Users/andrei/projects/globus/apps/caprica

## Service Config
```
service: caprica
useDotenv: true
package:
    individually: true
    patterns:
        - assets/watermark.png
provider:
    name: aws
    runtime: nodejs20.x
    stage: ${opt:stage, 'dev'}
    region: eu-central-1
    deploymentMethod: direct
    endpointType: REGIONAL
    iam:
        role:
            statements:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                      - "s3:GetObject"
                  Resource: "arn:aws:s3:::images-collection1/*"
                - Effect: "Allow"
                  Action:
                      - "s3:GetObject"
                  Resource: "arn:aws:s3:::pictures1/*"
    tracing:
        lambda: false
build:
    esbuild:
        bundle: true
        minify: false
        exclude:
            - sharp
        external:
            - sharp
custom:
    prune:
        automatic: true
        number: 5 # Number of versions to keep
    s3:
        host: localhost
        directory: /tmp
    serverless-offline:
        noPrependStageInUrl: true
        httpPort: 4000
functions:
    image:
        handler: src/image.handler
        memorySize: 1536
        timeout: 20
        architecture: ${env:ARCH}
        url: true
        environment:
            TZ: Asia/Shanghai
            AWS_KEY: ${env:AWS_ACCESS_KEY_ID}
            AWS_SECRET: ${env:AWS_SECRET_ACCESS_KEY}
            SPACES_KEY: ${env:SPACES_KEY}
            SPACES_SECRET: ${env:SPACES_SECRET}
            DEFAULT_AREA: ${env:DEFAULT_AREA, 'fr'}
            GOOGLE_APPLICATION_CREDENTIALS: ${env:GOOGLE_APPLICATION_CREDENTIALS}
            VIPS_DISC_THRESHOLD: 1024m
            CAPRICA_SECURE: ${env:CAPRICA_SECURE}
plugins:
    - serverless-s3-local
    - serverless-offline
    - serverless-prune-plugin
```

# Service Overview
- Serverless Framework Version: 4.1.11
- Command: support

**Comment by eahefnawy** [comment]
Hi @faradaytrs thanks for reporting. I was just debugging a similar issue. I'll look into this as well 👌

**Comment by Mmarzex** [comment]
@faradaytrs This has been addressed in `v4.1.13` you can run `serverless update` and then update your esbuild config to be

```
build:
  esbuild:
    external:
       - "!@aws-sdk/*"

**Comment by faradaytrs** [comment]
@Mmarzex It's broken in different way, now it doesn't exclude sharp:
````yaml
build:
    esbuild:
        bundle: true
        minify: false
        exclude:
            - sharp
        external:
            - sharp
            - "!@aws-sdk/*"
 ````
