### ISSUE TITLE
Outage: Version 4.1.13 Breaking Changes (Deployments + Building)

### ISSUE THREAD

**Issue by NicoHinderling** [serverless/serverless#12689]
### Issue description

As of one hour ago, all of our SLS commands have broken. It seems like the inclusion/exclusion logic changes are causing issues.

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/13134b18-8e3a-4908-8b6b-338f9bd62a02">

the errors pop up for non aws-sdk things too (ex. "semver" or "datadog-lambda-js")

All of our CI is essentially broken :(

Two asks:
1. **Most important** How can we pin to a specific version of serverless? This is the second time now where deployments broke from a bad version release and as far as I can tell, there's no way to turn off [the auto updating](https://github.com/serverless/serverless/discussions/12683) of serverless4. I already tried pinning to version 4.1.12 in our `package.json` but it still installs 4.1.13 under the hood which makes it impossible for us to mitigate this issue ourselves right now. Please tell me if I'm missing something!
2. Request to help mitigate the underlying issues in 4.1.13 so we can eventually roll forward

**Comment by noahsmartin** [comment]
I suspect it's this line: https://github.com/serverless/serverless/pull/12678/files#diff-8e49a112b340fce94cbf8b22d2d457889d33bd028e3e83d02d332e98a5a74a1bR410 which if I'm reading it correctly would break any external/excluded rules that are for dependencies not install in the package.json (for example anything in a lambda layer which we'd want to mark as external)

**Comment by NicoHinderling** [comment]
cc @austencollins  @Mmarzex

**Comment by austencollins** [comment]
We're looking into this right now..

**Comment by austencollins** [comment]
Working on the fix. ETA coming shortly.

**Comment by Mmarzex** [comment]
@NicoHinderling are you able to share what your esbuild configuration is? I believe I know the issue but want to confirm based on what you are doing.

**Comment by NicoHinderling** [comment]
for this service it is currently:

```
build:
  esbuild:
    external:
      - '.prisma'
      - 'semver'
      - 'sharp'
      - 'pg-format'
      - 'simple-plist'
      - 'mustache'
      - 'datadog-lambda-js' # required to be external: https://docs.datadoghq.com/serverless/guide/serverless_tracing_and_webpack/#esbuild
    exclude:
      - 'datadog-lambda-js' # required to be also be excluded: https://docs.datadoghq.com/serverless/guide/serverless_tracing_and_webpack/#esbuild
    minify: false
```
