### ISSUE TITLE
[V4] Dev mode: handler not found in service directory

### ISSUE THREAD

**Issue by tiemenv** [serverless/serverless#12681]
### Issue description

We have a monorepo setup where one of our Typescript backend API's is running on the serverless framework.

While we can test development by using `sls deploy --stage dev`, which makes all the functions available, if we try the same with `sls dev --stage dev`: the moment we try to fetch any API endpoint, we are greeted with:

```
s:cli-error-handler: Handler "./src/handler.handler" not found in service directory (DEV_MODE_HANDLER_NOT_FOUND)

✖ Handler "./src/handler.handler" not found in service directory
```

We have included the appropriate tsconfig files as suggested by the documentation. We've previously tried to include a proposed fix from https://github.com/serverless/serverless/issues/12535 but to no avail.

### Context

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.1.12
- Service Config File: serverless.yml
- Service Name: rest-api
- Service App: app
- Service Runtime: nodejs18.x
- Service Stage: dev
- Service Region: eu-west-1
- Command: dev --stage dev,--debug *

## Service Path
/Users/<user>/monorepo/apps/rest-api

## Service Config
```
org: orgname
app: app
service: rest-api
frameworkVersion: "4"
# projectDir: ../
# Create an optimized package for our functions
package:
  individually: true
provider:
  httpApi:
    id: !ImportValue OrgApiGatewayHTTPApiId
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stackName: ${self:app}-${self:service}
  timeout: 30
stages:
  dev: # Rename to whatever your production Stage is to ensure Observability is enabled.
    observability: false
  default: # This will disable observability for every Stage other than your production Stage.
    observability: false
functions:
  helloWorld:
    handler: ./src/handler.handler
    name: ${self:service}-${opt:stage}-hello-world
    events:
      - httpApi:
          path: "/hello"
          method: get
          # authorizer:
          #   type: jwt
          #   id:
          #     Fn::ImportValue: OrgHTTPApiAuthorizer
  createLesson:
    handler: ./src/controllers/LessonController.handler
    name: ${self:service}-${opt:stage}-create-lesson
    events:
      - httpApi:
          path: "/lessons"
          method: post
          # authorizer:
          #   type: jwt
          #   id:
          #     Fn::ImportValue: OrgHTTPApiAuthorizer
      # - websocket:
      #     route: $connect
      #     authorizer:
      #       type: jwt
      #       id:
      #         Fn::ImportValue: OrgHTTPApiAuthorizer
```

# Service Overview
- Serverless Framework Version: 4.1.12
- Command: support
