### ISSUE TITLE
Keys cannot contain Serverless Variables - How to deal?

### ISSUE THREAD

**Issue by gleitoncampos** [serverless/serverless#12694]
### Issue description

Here we need to do something like this:

```
resources:
  Resources:
    myApiGatewayDeployment${sls:instanceId}:
      Type: AWS::ApiGateway::Deployment
```
but this leads to:

```
 The CloudFormation template is invalid: Template format error: Resource name 
myApiGatewayDeployment${sls:instanceId} is non alphanumeric.
```

As said in #6271 "_Keys cannot contain Serverless Variables_", but the answer don't point us in how to deal with that. In the example above is clear that without use the Serverless Variables, we are not able to override the ApiGW deployment. 
The answer points to #2892 where was said "_We looked into this problem when implementing new resolver, and it looks as something that will introduce an additional significant complexity, while use case is rare and can be addressed with alternative means._" but what alternative meas we have?
