### ISSUE TITLE
Nested variable reference throws error when inserted into a reference to SSM parameter store

### ISSUE THREAD

**Issue by SamGhiseven** [serverless/serverless#12697]
### Issue description

My team is encountering errors converting our V3 .yml files to V4. The particular issue in question is related to nesting a reference to a custom variable WITHIN a reference to a variable stored in AWS SSM Parameter Store [https://www.serverless.com/framework/docs/guides/variables/ssm](url)

```
custom:
    stageVariables:
        stg:
            NODE_ENV: staging
        prod:
            NODE_ENV: production

provider:
    stage: ${opt:stage}
    name: aws    
    region: ap-southeast-1
    environment:
        REDIS_HOST: ${ssm:/service/${self:custom.stageVariables.${self:provider.stage}.NODE_ENV}/redis-host}

```
From testing, it seems that the issue is most likely caused by symbols used in the nested reference "${}" being rejected. Hard coding the value as text has no issues. This line in the error stands out.

 _If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the_ **following 3 symbols .-_**

Would kindly like the team to investigate this if possible. 

### Context

Context
Expected Behavior:
We expect no issues with the given variable reference. It worked perfectly in V3

Current Behavior:
`SLS throws the following error: ✖ Failed to resolve variable '/service/${self:custom.stageVariables.${self:provider.stage}.NODE_ENV}/redis-host' with resolver 'ssm' and provider 'aws': ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
`
Serverless Framework Version: "serverless": "^4.1.16"
