### ISSUE TITLE
Error: Internal Server Error at Authentication.getClientDataFromAccessKey

### ISSUE THREAD

**Issue by scolastico** [serverless/serverless#12726]
### Issue description

I cant get the cli to work as expected. I always get an "Internal Server Error", i allready tryd deleting the .serverlessrc but with the same result.

```log
jb@desk:/my/project/dir$ sls offline start

✔ Serverless Framework V4 CLI is free for developers and organizations making less than $2 million annually, but requires an account or a license key.

Please login/register or enter your license key: · Login/Register

If your browser does not open automatically, please open this URL: [redacted]

✔ You have successfully signed in.


✖ Internal Server Error
Error: Internal Server Error
    at Authentication.getClientDataFromAccessKey (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:912:17054)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Authentication.getAuthenticatedData (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:912:3687)
    at async Authentication.resolverAuthenticate (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:912:20540)
    at async _Meta.authenticateAndResolve (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:10814)
    at async route (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:16254)
    at async Object.run2 [as run] (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:16702)
    at async run3 (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:17962)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/
```

### Context

# Service Overview
- Serverless Framework Version: 4.1.19
- Service Path: /my/project/dir
- Service Config File: serverless.yaml
- Service Runtime: nodejs20.x
- Command: offline start 

## Service Name
{
  "name": "why-do-you-need-this"
}

## Error Message
Internal Server Error

## Error Stacktrace
```
at Authentication.getClientDataFromAccessKey (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:912:17054)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Authentication.getAuthenticatedData (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:912:3687)
at async Authentication.resolverAuthenticate (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:912:20540)
at async _Meta.authenticateAndResolve (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:10814)
at async route (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:16254)
at async Object.run2 [as run] (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:16702)
at async run3 (file:///home/jb/.serverless/releases/4.1.19/package/dist/sf-core.js:920:17962)
```

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: scolastico
service:
  name: why-do-you-need-this
plugins:
  - serverless-plugin-optimize
  - serverless-offline
provider:
  name: aws
  runtime: nodejs20.x
functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
```
