### ISSUE TITLE
Failed to construct URL with https://ssm.${param:region}.amazonaws.com TypeError: Invalid URL

### ISSUE THREAD

**Issue by kenlfg** [serverless/serverless#12728]
### Issue description

I'm upgrading from v3 to v4 and went through the process of updating the serverless.yml to work with the new stages/format (non-breaking wasn't exactly true). I've got stages set up with defaults and all, even have some things coming in off a .env file just fine.

The problem I'm running into is when building or running serverless-offline (haven't tried a deploy since I don't want to deploy this yet), I'm getting this error:

`Failed to construct URL with https://ssm.${param:region}.amazonaws.com TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at getEndpointUrl (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:360:14)
    at evaluateEndpointRule (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:390:10)
    at evaluateRules (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:426:35)
    at evaluateTreeRule (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:416:10)
    at evaluateRules (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:433:35)
    at evaluateTreeRule (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:416:10)
    at evaluateRules (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:433:35)
    at resolveEndpoint (C:\Users\[redacted]\.serverless\releases\node_modules\@smithy\util-endpoints\dist-cjs\index.js:462:20)
    at Object.defaultEndpointResolver (C:\Users\[redacted]\.serverless\releases\node_modules\@aws-sdk\client-ssm\dist-cjs\endpoint\endpointResolver.js:8:33) {
  code: 'ERR_INVALID_URL',
  input: 'https://ssm.${param:region}.amazonaws.com'
}`

My provider block starts like so:

`provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, param:stage}
  region: ${param:region}`

I've tried various alternatives (e.g., ${env:region}, etc.). The only thing that works is specifying a literal (e.g., "us-east-1"). 

I figure no one's reporting this because they either don't need a variable region or it's just working so not sure what I might be doing wrong here. For the short term, I can live with the region being hardcoded but longer term I would rather it be a variable if possible. 

### Context

Here's the serverless support output (note: I've redacted a bunch here and removed all the functions just for privacy's sake).

# Service Overview
- Serverless Framework Version: 4.1.19
- Command: support --summary true

# Service Overview
- Serverless Framework Version: 4.1.19
- Service Path: C:\Development\[redacted]\Clients\[redacted]\[redacted]-api
- Service Config File: serverless.yml
- Service Name: [redacted]-api
- Service App: [redacted]
- Service Runtime: nodejs20.x
- Service Stage: local
- Service Region: us-east-1
- Command: offline --debug *
- Error Code: RESOLVER_RESOLVE_VARIABLE_ERROR

## Error Message
Failed to resolve variable '/[redacted]-api/local/region-dyndb' with resolver 'ssm' and provider 'aws': TypeError: Invalid URL

## Error Stacktrace
```
at _ResolverManager.#resolveKey (C:\Users\[redacted]\.serverless\releases\4.1.19\sf-core\src\lib\resolvers\manager.js:212:13)
at _ResolverManager.resolve (C:\Users\[redacted]\.serverless\releases\4.1.19\sf-core\src\lib\resolvers\manager.js:495:29)
at _ResolverManager.#handlePlaceholderNode (C:\Users\[redacted]\.serverless\releases\4.1.19\sf-core\src\lib\resolvers\manager.js:445:9)
at <anonymous> (C:\Users\[redacted]\.serverless\releases\4.1.19\sf-core\src\lib\resolvers\manager.js:342:11)
at processNodeAndHandleCompletion (C:\Users\[redacted]\.serverless\releases\4.1.19\sf-core\src\lib\resolvers\graph.js:20:5)
```

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: [redacted]studios
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: [redacted]
# service: ${self:custom.baseServiceName}-${self:custom.region.${opt:stage, self:custom.defaultStage}}
service: ${self:custom.baseServiceName}
custom:
  baseServiceName: [redacted]-api
  defaultStage: local
  serverless-offline:
    httpPort: 8500
    lambdaPort: 8501
    noPrependStageInUrl: true
    reloadHandler: true
    noTimeout: true
  export-env:
    pathFromRoot: ".jest"
    filename: ".env.local"
stages:
  default:
    params:
      service_name: ${self:service}
      region: ${opt:region, env:region, 'us-east-1'}
      profile: ${env:AWS_PROFILE}
      account: [redacted]
      stage: ${env:STAGE}
      versions: false
      memory: 512
      timeout: 15
      tracing: false
      api_key: [redacted]
  local:
    params:
      stage: local
      profile: [redacted]ApiLocal
      api_key: [redacted]
      memory: 256
  test:
    params:
      stage: test
      profile: [redacted]ApiTest
      api_key: [redacted]
      memory: 256
      tracing: true
  staging:
    params:
      stage: staging
      profile: [redacted]ApiStaging
      account: [redacted]
      api_key: [redacted]
      tracing: true
  prod:
    params:
      stage: prod
      profile: [redacted]ApiProd
      account: [redacted]
      api_key: [redacted]
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, param:stage}
  region: ${param:region}
  memorySize: ${param:memory}
  timeout: ${param:timeout}
  profile: ${param:profile}
  iam:
    role: [snip]
    deploymentRole: [snip]
  tracing: 
    lambda: ${param:tracing}
  versionFunctions: ${param:versions}
  environment:
    [snip]
package:
  exclude:
    - .hg/**
    - .vscode/**
    - _deploy/**
    - "**/aws-sdk/**"
functions:
  [snip]
  
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${param:service_name}-${self:provider.stage}
    # Gateway Response Custom Responses - START
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        ResponseTemplates:
          application/json: "{\"statusCode\": 4xx, \"error\": \"Generic 4xx\", \"message\": \"Check details for more information.\", \"details\":$context.message}"
    GatewayResponseUnauthorized:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        ResponseTemplates:
          application/json: "{\"statusCode\": 401, \"error\": \"Unauthorized\", \"message\": \"Access to this resource required authorization.\", \"details\":$context.message}"
    GatewayResponseAuthorizerFailure:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: AUTHORIZER_FAILURE
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        ResponseTemplates:
          application/json: "{\"statusCode\": 403, \"error\": \"Forbidden\", \"message\": \"User is not authorized to access this resource.\", \"details\":$context.message}"
    # Gateway Response Custom Responses - END
plugins:
  - serverless-offline
  - serverless-export-env
```
