### ISSUE TITLE
Build override package Pattern  V4

### ISSUE THREAD

**Issue by slasia** [serverless/serverless#12742]
### Issue description

This is my serverless (V4) file: 

```
build:
  esbuild:
    bundle: true
    minify: true
    external:
      - "@aws-sdk/client-s3"
    exclude:
      - "@aws-sdk/*"
      - "!@aws-sdk/client-bedrock-runtime"
    packages: external
    buildConcurrency: 3
    sourcemap:
      type: linked
      setNodeOptions: true

package:
  individually: true
  
functions:
  function1:
    handler: src/authorizer/handler.auth0Authorizer
    package: 
      patterns:
        - '!node_modules/fastify/**'
  function2:
    handler: src/functions/function2/handler.handler
    package:
      patterns:
        - "!node_modules/fastify/**"
        - "!node_modules/serverless-http/**"
```

 When I run `sls package` it generates two zip files that weigh the same, so it seems that the node_modules exclude that I added is not working. Could it be that esbuild is overriding the package patterns of each function?
 
I want to exclude packages by lambda functions, but the way I did it before no longer works if I use build. That's why I asked if the build statement could be executed for each function in that way, the exclude would apply only to the specific function.

I need to exclude libraries by function and not globally, for example function2 does not need the serverles-http library and function1 does, so I do not want it in the function2 bundle.
