### ISSUE TITLE
[V4] Parameters defined in global stages property not loading when used in custom property

### ISSUE THREAD

**Issue by salemol** [serverless/serverless#12755]
### Issue description

Failed to load parameters defined in global stages property when used in custom property

- serverless.yml:
```
service: my-service

stages:
  default:
    params: ${file(env.yml):default}
  prod:
    params: ${file(env.yml):prod}

provider:
  name: aws
  region: ap-southeast-2
  runtime: dotnet8

custom:
  myCustomParameterName: /product/${self:service}-${param:BranchName}-details
```

- env.yml:
```
default:
  BranchName: "develop"
prod:
  BranchName: "prod"
```

When deploying with serverless version `4.1.19`, the parameters failed to load, and I'm encountering the following error:
![image](https://github.com/user-attachments/assets/6dedbad4-0e89-4233-b67c-1ec259c4bb30)

I attempted to resolve this by copying the content from the `env.yml` file into the `serverless.yml` file, which worked. I also tried using the old `params` top-level property, but the error persisted.
