### ISSUE TITLE
Serverless V4 fails to resolve default when parameter is not found

### ISSUE THREAD

**Issue by djrobinson** [serverless/serverless#12763]
## Issue:

I have created a repo to display this issue: https://github.com/djrobinson/serverless-defaults/tree/main

In v3, serverless's default syntax allowed a fallback value when a parameter passed to the CLI wasn't found.
V4 does not allow the same and will give you a "failed to resolve" error.

Example serverless.yml:
```
service: v4-example

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: us-east-1
  environment:
    SOME_VARIABLE: ${self:custom.SOME_VARIABLE.${param:arg}, self:custom.SOME_VARIABLE.default}

functions:
  not-working-lambda-example:
    handler: index.handler
    name: simple-example-v4

custom:
  SOME_VARIABLE:
    default: 'DEFAULT'
    option1: 'OPTION 1'
    option2:  'OPTION 2'
```
Error when running for a variable that is not defined in v4 (Ex: `sls deploy --param="arg=option3"`)
```
✖ Failed to resolve variable 'custom.SOME_VARIABLE.option3' with resolver 'config' and provider 'self': Error: Key "custom.SOME_VARIABLE.option3" is not defined in config file
Error: Failed to resolve variable 'custom.SOME_VARIABLE.option3' with resolver 'config' and provider 'self': Error: Key "custom.SOME_VARIABLE.option3" is not defined in config file
```

## Steps to recreate:
Clone this repo: https://github.com/djrobinson/serverless-defaults/tree/main
See v3 success:
```
cd v3
yarn
yarn deploy --param="arg=option3"
```
See v4 failure:
```
cd v4
yarn
yarn deploy --param="arg=option3"
```

### Context

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.1.22
- Command:  --version true

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
