### ISSUE TITLE
LIft: `Provider construct is not supported` error 

### ISSUE THREAD

**Issue by skierkowski** [serverless/serverless#12774]
I'm still getting this error `Provider construct is not supported` with 
```JSON
"serverless": "4.1.23",
"serverless-lift": "1.29.0",
```

_Originally posted by @diestrin in https://github.com/serverless/serverless/issues/12571#issuecomment-2301031385_

**Comment by skierkowski** [comment]
@diestrin @czubocha I opened a new issue from [this comment](https://github.com/serverless/serverless/issues/12571#issuecomment-2301031385) so we have the dedicated issue to track here.

**Comment by diestrin** [comment]
Is anyone actively working on this? This is blocking a deployment of a paid customer to production. We were forced to update to v4 because of issues in v3, and we're now paying an anual subscription for a product we can't use to deploy.

**Comment by skierkowski** [comment]
@diestrin Yes, this is on our radar and we'll try to get this addressed in the next release. It's been slow going as I haven't been able to reproduce this issue locally (yet) and there have been very few reported instances of this error.

**Comment by aareyes96** [comment]
same issue:

 "serverless-lift": "^1.30.2",


 Serverless ϟ Framework
 • 4.3.2

**Comment by czubocha** [comment]
Hey @diestrin @aareyes96
I wasn’t able to reproduce the issue either, using this template:
```
org:  my-org
service: my-service

plugins:
  - serverless-lift

provider:
  name: aws
  region: us-east-1

constructs:
  avatars:
    type: storage
  matcher:
    type: queue
    worker:
      handler: handler.handler
      environment:
        BUCKET_NAME: ${construct:avatars.bucketName}
        QUEUE_URL: ${construct:matcher.queueUrl}

functions:
  web:
    handler: handler.handler
    environment:
      BUCKET_NAME: ${env:MATCHER_BUCKET_NAME, construct:avatars.bucketName}
      QUEUE_URL: ${env:MATCHER_QUEUE_URL, construct:matcher.queueUrl}
```
Are you perhaps using the `construct` variable in the params section?
