### ISSUE TITLE
Unable to find Route by key [request method] [route] within the provided RouteSettings

### ISSUE THREAD

**Issue by belenbuccolo** [serverless/serverless#12776]
### Issue description

When removing a route from the `serverless.yml` file, the subsequent deployment fails with an error indicating that the removed route cannot be found. This occurs even when using the --force flag.

## Steps to Reproduce
1. Have an existing serverless.yml file with a route defined (e.g., `exampleRoute` function with `GET /example-route` route).
2. Remove the route and its associated function from the serverless.yml file.
3. Attempt to deploy the updated configuration.

## Current Behavior
The deployment fails with the following error:
```
✖ Stack [stack] failed to deploy (74s)
Environment: linux, node 18.19.1, framework 3.39.0 (local) 3.38.0v (global), plugin 7.2.3, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Unable to find Route by key GET /example-route within the provided RouteSettings
```

## Expected Behavior
The deployment should succeed, removing the specified route from the API Gateway without errors.

```yaml
service: [service]
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  # ... (other provider settings)

functions:
  # ... (other functions)
  
  # The following function and route have been removed:
  # exampleRoute:
  #   handler: src/handler.exampleRoute
  #   memorySize: 128
  #   events:
  #     - httpApi:
  #         method: GET
  #         path: /example-route

# ... (rest of the configuration)
```

This issue is different from the one reported in [#9686](https://github.com/serverless/serverless/issues/9686) "Serverless not Auto Deploying RestApis". In that case, the problem was related to changing a route's path and here the issue occurs when attempting to remove a route entirely.
Any insights or workarounds would be greatly appreciated

### Context

Environment: linux, node 18.19.1, framework 3.39.0 (local) 3.38.0v (global), plugin 7.2.3, SDK 4.5.1
