### ISSUE TITLE
"refresh-outputs" is not currently supported by Compose.

### ISSUE THREAD

**Issue by zocom-johan-kivi** [serverless/serverless#12791]
### Issue description

When trying to refresh outputs in a composed services I get the following error. 

`The command "refresh-outputs" is not currently supported by Compose.`

I now use Serverless 4.2.4.
Worked fine in 3.8.x.

### Context

# serverless-compose.yml
```
services:
  base:
    path: base-services
  auth:
    path: auth-api
    dependsOn: base
    params:
      userDetailsTable: ${base.userDetailsTable}
      userDetailsTableName: ${base.userDetailsTableName}
      userPool: ${base.userPool}
      userPoolClient: ${base.userPoolClient}
  externalservices:
    path: services-api
    dependsOn: base
    params:
      contentTable: ${base.contentTable}
      contentTableName: ${base.contentTableName}
      userDetailsTable: ${base.userDetailsTable}
      userDetailsTableName: ${base.userDetailsTableName}
      learningRecordsTable: ${base.learningRecordsTable}
      learningRecordsTableName: ${base.learningRecordsTableName}
      userPool: ${base.userPool}
      userPoolClient: ${base.userPoolClient}
```
# serverless.yml
```
service: services-api
frameworkVersion: "4"
org: my-org

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: eu-north-1
  httpApi:
    cors: true
    authorizers:
      serviceAuthorizer:
        type: request
        functionName: authorizer
        payloadVersion: "2.0"
        enableSimpleResponses: true

plugins:
  - serverless-iam-roles-per-function

build:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - "@aws-sdk/*"

package:
  individually: true

functions:
  - ${file(./yaml/auth-functions.yml)}
  - ${file(./yaml/calendar-functions.yml)}
  ```
