### ISSUE TITLE
Custom resource deployment hangs forever

### ISSUE THREAD

**Issue by sean-legitscript** [serverless/serverless#12804]
### Issue description

We have a lambda that uses S3 events to be triggered.
```
processSpreadsheet:
  architecture: arm64
  memorySize: 3008
  timeout: 900
  handler: src/_handlers.processSpreadsheet
  events:
    - s3:
        bucket: example-bucket
        event: s3:ObjectCreated:*
        existing: true
        forceDeploy: true
```

Our team needs to deploy this lambda for each of our stages. However, after we successfully deploy this lambda for one stage, all other sls deployments hang. After about an hour, the deployment fails with:
```
✔ Service packaged (89s)
(node:31517) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

Deploying merchantsmyls to stage qa (us-west-2)

✖ Stack merchantsmyls-qa failed to deploy (3777s)
Environment: darwin, node 20.11.1, framework 3.38.0 (local), plugin 7.2.3, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: ProcessSpreadsheetCustomS31 (Custom::S3)
CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [3c8d63e8-087d-48fc-938b-87e266eca2c4]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
```

We need to be able to deploy this lambda for more then one stage. We thought that using the forceDeploy: true flag would allow us to push forward but it still doesn't work. We need a way to push forward.

### Context

Serverless Version: 3.38.0

Plugins:
- serverless-api-gateway-caching
- serverless-v2-aws-documentation
- serverless-domain-manager
- serverless-offline
- serverless-step-functions
- serverless-plugin-aws-alerts
- serverless-webpack
- serverless-dependson-plugin
