### ISSUE TITLE
Serverless package command requires AWS connectivity

### ISSUE THREAD

**Issue by jamessawle** [serverless/serverless#12825]
### Issue description

The `serverless package` command requires connectivity to an SSM parameter (`/serverless-framework/deployment/s3-bucket`) and S3 bucket. As this is generating a local artefact(s), there is no need for access to these, or even AWS credentials at all.

For context, my organisation has been using the Serverless Framework for local development (`serverless-offline`) and function packaging (historically with `serverless-esbuild`) to simplify our development processes. However, we have an internal deployment tool that we use to deploy our artefacts (along with a number of different artefact types that Serverless does not support). This has meant that our local engineers have not had to give the Serverless CLI access to our AWS environments, or for us to create any Serverless specific resources in our accounts. However, with the new version, this is not possible as we get the following errors:

When no default resolver provided within the `serverless.yml`
```bash
✖ AWS credentials missing or invalid. Original error from AWS: Could not load credentials from any providers
```

And when given a read-only role, with resources not existing within the account
```bash
✖ Access denied when storing the parameter "/serverless-framework/deployment/s3-bucket". Please check your permissions and try again. You have the following options:
• Ensure you have permission to create SSM and S3 resources.
• Use the "provider.deploymentBucket" field to specify an existing S3 bucket.
• Manually create the S3 bucket and SSM parameter.

For more details, please refer to the documentation: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#provider
```

Our infrastructure team do not allow for the creation of AWS resources outside of their tools, nor do they wish to create these sorts of resources (as squads are allowed to pick their own tooling choices and this could lead to an explosion of them).

Is there a reason why the packaging stage needs access to AWS at all, instead of making this a deployment only concern? If nothing else, artefacts should be environment agnostic where possible, and use environment variables to drive dynamic things (such as S3 bucket routing etc), so confused why it cares at all about stage and environment at the packaging time.

Any assistance on this would be amazing, as would love to support Serverless as it moves forward, even if we don't do deployments etc.

### Context

We are looking at migrating to V4 and a PoC failed due to the above issue and therefore I do not have a license and can not run the `serverless support --summary` command. I have made a dummy service that does the bare minimum to highlight the issue:

```
org: ORG-NAME-HERE
service: v4Test
frameworkVersion: '4'
configValidationMode: error

stages:
  default:
    resolvers:
      generic:
        type: aws
        profile: NAME-OF-AWS-PROFILE-HERE
        region: eu-west-1

package:
  individually: true

build:
  minify: true
  sourceMap:
    type: linked

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128
  region: eu-west-1
  environment:
    LOG_LEVEL: info
    POWERTOOLS_DEV: "true"
    NODE_OPTIONS: "--enable-source-maps"

functions:
  hello:
    handler: src/handler.handle
    timeout: 10
    events:
      - alb:
          # Made up to make serverless-offline work
          listenerArn: arn:aws:elasticloadbalancing:eu-west-1:12345:listener/app/my-load-balancer/abcd/abcd
          priority: 1100
          conditions:
            path: /hello
            method: GET
            # Made up to make serverless-offline work
            host: "ENVIRONMENT.CLOUDFORMATIONOUTPUTDOMAIN"

plugins:
  - serverless-offline
```
