### ISSUE TITLE
Lambda eventbridge event breaks when using event bus with `${AWS::Region}` instead of `${aws:region}`

### ISSUE THREAD

**Issue by lscheilling** [serverless/serverless#12821]
### Issue description

The lambda policy statement for an eventbridge event gets broken when you use an event bus with `${AWS::Region}` parameters instead of `${aws:region}` parameters. If you use the broken type you get something like:
```json
{
    "Principal": "events.amazonaws.com",
    "Effect": "Allow",
    "Action": "lambda:InvokeFunction",
    "Conditions": [
        {
            "ArnLike": {
                "AWS:SourceArn": "arn:aws:events:{region}:{account_id}:rule/arn:aws:events:{region}:{account_id}:event-bus/{bus_name}/{rule_name}"
            }
        }
    ]
}
```
instead of the expected:
```json
{
    "Principal": "events.amazonaws.com",
    "Effect": "Allow",
    "Action": "lambda:InvokeFunction",
    "Conditions": [
        {
            "ArnLike": {
                "AWS:SourceArn": "arn:aws:events:{region}:{account_id}:rule/{bus_name}/{rule_name}"
            }
        }
    ]
}
```

### Context

Serverless V3

Working serveless.yaml:
```yaml
service: ...
frameworkVersion: "3"

provider:
  name: aws
  region: eu-west-2
  runtime: python3.9
  stackName: ...
  
functions:
  sample-function:
    handler: app.lambda_handler
    description: description
    events:
      - eventBridge:
          eventBus: arn:aws:events:${aws:region}:${aws:accountId}:event-bus/...
          description: Rule to trigger lambda
          pattern:
            ...
          state: ENABLED
```

Broken serveless.yaml:
```yaml
service: ...
frameworkVersion: "3"

provider:
  name: aws
  region: eu-west-2
  runtime: python3.9
  stackName: ...
  
functions:
  sample-function:
    handler: app.lambda_handler
    description: description
    events:
      - eventBridge:
          eventBus: !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/...
          description: Rule to trigger lambda
          pattern:
            ...
          state: ENABLED
```
