### ISSUE TITLE
Big slowdown in packaging lambdas from v3.31 to v3.39

### ISSUE THREAD

**Issue by mrbrianevans** [serverless/serverless#12833]
### Issue description

A project was using v3.31 of serverless and took around 5 minutes to deploy 5 lambdas and some custom resources.
After upgrading serverless in package.json to version 3.39, the deploy now takes around 10 minutes.
Same thing happened in another repo going from 3.27 to 3.39, so I don't think its too specific to one particular project or setup.

Has anyone else experienced a massive slow down after updating to v3.39?

It seems the time taken is in packaging the lambdas. See the output below before and after the upgrade:

Version 3.27: (89 seconds)
```
> sls package --stage $npm_config_stage

(node:5098) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

Warning: Invalid configuration encountered
  at 'functions.commentsProcessor.runtime': must be equal to one of the allowed values [dotnet6, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs12.x, nodejs14.x, nodejs16.x, nodejs18.x, provided, provided.al2, python3.6, python3.7, python3.8, python3.9, ruby2.7]
Learn more about configuration validation here: http://slss.io/configuration-validation

Packaging data-repo-name for stage dev (us-east-1)
✔ Service packaged (89s)
4 deprecations found: run 'serverless doctor' for more details
```

Version 3.39: (397 seconds)
```
> sls package --stage $npm_config_stage

Packaging data-repo-name for stage dev (us-east-1)
✔ Service packaged (397s)
3 deprecations found: run 'serverless doctor' for more details
```

The above was copied from codebuild logs for the `serverless package` command.

### Context

As I've observed this same increase occur in two different projects, I don't believe it to be related to anything specific in one of their serverless.ymls or lambda source codes.

Here is the serverless.yml of one of the projects (with some unrelated bits renamed or removed):
```yml
service: data-repo-name

frameworkVersion: "3"

provider:
  name: aws
  versionFunctions: false
  tracing:
    apiGateway: true
    lambda: true
  role: arn:aws:iam::123456789:role/SFRole-asdf-l
  stage: ${self:provider.environment.env}
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  environment: ${file(./environment-variables/${opt:stage}.yml),file(./environment-variables/dev.yml)}

plugins:
  - serverless-plugin-conditional-functions

package:
  individually: true
  patterns:
    - "!./*"
    - "!deploy/*"
    - "!environment-variables/*"
    - "!**/fixtures/*"
    - "!lambdas/**"

functions:
  lambda1:
    handler: ./lambdas/lambda1/lambda1.index
    runtime: nodejs18.x
    package:
      patterns:
        - ./lambdas/lambda1/**
  lambda2:
    handler: ./lambdas/lambda2/lambda2.index
    runtime: nodejs18.x
    package:
      patterns:
        - ./lambdas/lambda2/**
  lambda3:
    handler: ./lambdas/lambda3/lambda3.index
    runtime: nodejs18.x
    package:
      patterns:
        - ./lambdas/lambda3/**
  lambda4:
    handler: ./lambdas/lambda4/lambda4.index
    runtime: nodejs18.x
    package:
      patterns:
        - ./lambdas/lambda4/**
      individually: true
  lambda5:
    handler: ./lambdas/lambda5/lambda5.index
    runtime: nodejs18.x
    package:
      patterns:
        - ./lambdas/lambda5/**
      individually: true
  lambda6:
    handler: ./lambdas/lambda6/lambda6.index
    runtime: nodejs18.x
    package:
      patterns:
        - ./lambdas/lambda6/**
      individually: true
  lambda7:
    architecture: arm64
    handler: ./lambdas/lambda7/handler.index
    runtime: nodejs18.x
    package:
      patterns:
        - ./lambdas/lambda7/**
      individually: true

  lambda8go:
    architecture: arm64
    handler: bootstrap
    runtime: provided.al2023
    package:
      individually: true
      exclude:
        - "**/*"
      include:
        - lambdas/lambda8go/bootstrap

```
