### ISSUE TITLE
External modules not being included

### ISSUE THREAD

**Issue by demian85** [serverless/serverless#12840]
### Issue description

I merged 2 repos into a new one and set up serverless-compose. Both were using serverless v4 and working fine. 
Now the final lambda packages are not including node_modules with the dependencies marked as external in the esbuild config file.
I can't understand what's going on since the config files for both sls and esbuild are exactly the same as before, except that now I'm using a compose.yml file.

Part of my setup:

esbuild.config.js
```js
const env = require('esbuild-plugin-env')
const path = require('node:path')

module.exports = (serverless) => {
  return {
    external: [
      '@aws-sdk/client-s3',
      '@aws-sdk/client-sns',
      'pg-native',
      'sharp',
    ],
    platform: 'node',
    plugins: [env()],
    alias: {
      '@lib': path.resolve(__dirname, 'src/lib/'),
    },
  }
}
```

src/api/serverless.yml
```yml
...
package:
  individually: true

build:
  esbuild:
    configFile: ../../esbuild.config.js
    bundle: true
    minify: true
    sourcemap:
      type: linked
      setNodeOptions: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  endpointType: regional
  timeout: 30
  memorySize: 256
  logRetentionInDays: 7

functions:
    ...
```
serverless-compose.yml
```yml
# serverless-compose.yml
services:
  rest-api:
    path: src/api
  lambda-functions:
    path: src/lambda
```

There are a few functions that must include the `sharp` external module and I'm getting module not found error. The final artifact does not include a node_modules folder like before. Not sure why.

Also, can someone please clarify how the `patterns` option work in serverless when using esbuild? Who is in charge of including the node_modules? esbuild or sls? what is included by default? Nothing stated in the docs!
