### ISSUE TITLE
Serverless v4 text file is busy (ETXTBSY) in CI workflows with parallel tasks

### ISSUE THREAD

**Issue by dgoerdes** [serverless/serverless#12857]
### Issue description

Hey since we updated from V3 to V4 we experience issues with our GitHub workflows when it comes to to running `serverless package`  or `serverless deploy` tasks in parallel.

Error on `sls package`:
```
Error: spawnSync /home/runner/work/<REPO>/node_modules/serverless/node_modules/.bin/serverless-linux-amd64-0.0.2 ETXTBSY
```

`Error on sls deploy`:
```
Error fetching release: ETXTBSY: text file is busy, open '/home/runner/work/<REPO>/node_modules/serverless/node_modules/.bin/serverless-linux-amd64-0.0.2'
  node:internal/errors:984
    const err = new Error(message);
                ^
  
  Error: Command failed: sls deploy --stage ***
      at genericNodeError (node:internal/errors:984:15)
      at wrappedFn (node:internal/errors:538:14)
      at checkExecSyncError (node:child_process:891:11)
      at execSync (node:child_process:963:15)
      at file:///home/runner/work/<REPO>/tools/scripts/slsDeploy.mjs:32:1
      at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
    status: 1,
    signal: null,
    output: [ null, null, null ],
    pid: 2464,
    stdout: null,
    stderr: null
  } 
```

### Context

We have multiple Serverless stacks within one Repository using NX for the repository tooling. This way in our CI workflows we run multiple builds or deploy tasks in parallel to save some time.

GitHub Workflow
```yaml
jobs:
  ci:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci

      - run: npm run nx -- format:check
      - run: npm run nx -- affected --target=lint --parallel=3
      - run: npm run nx -- affected --target=test --parallel=3 --ci --code-coverage

      # The command producing the issue
      # This will run sls deploy --stage=qa within each affected stacks workdir
      - run: npx nx affected --target=deploy --parallel=3 --stage=qa
```

The same issue comes from the build target which runs `sls package`
`- run: npm run nx -- affected --target=build --parallel=3`

As soon as we set --parallel=1 it works

So the issue is about running multiple Serverless tasks in parallel which was possible with version 3.
