### ISSUE TITLE
Serverless compose not printing individual service template errors

### ISSUE THREAD

**Issue by ycrc5** [serverless/serverless#12852]
### Issue description

Hi team,

I am testing out Serverless v4 on a v3 project inside of our monorepo.

I have added a compose file as follow to the root of the repo:
```yaml
services:
  my-service:
    path: services/my-service
```

And when I run `sls deploy -r eu-west-2 -s poc` , nothing happens and no error or success output . As seen in image.
![Screenshot 2024-10-07 at 13 02 02](https://github.com/user-attachments/assets/ee5b48b6-a0c2-473b-8488-f5896a2771af)

However, when I add the `--debug` flag, it prints out the error that I was expecting, which I get when running deploy in the service itself.

### Context

Summary Report -----------------

No previous command information was found

To include more details, please run a serverless command before running 'serverless support'

# Service Overview
- Serverless Framework Version: 4.4.4

**Comment by eahefnawy** [comment]
Thanks for reproting @ycrc5 ... I'll look into this and try to reproduce.

**Comment by eahefnawy** [comment]
Unfortunately I'm unable to reproduce this issue.

<img width="802" alt="Screenshot 2024-10-15 at 3 48 24 PM" src="https://github.com/user-attachments/assets/cf654fd8-9470-4860-a28c-29bfa075f30a">

Could you provide more details on the error you see in debug mode? And what your service looks like?

**Comment by danielvijge** [comment]
A simple test case, with two different services. They are both based on the default template:

service-a:
```
service: service-a
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    package:
      artifact: index.js
```

and service-b:
```
service: service-b
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    package:
      artifact: index.js
    environment:
      SOME_VARIABLE: ${file(../env.yml):${self:provider.stage}.someVariable}
```
The file "env.yml" doesn't exist, and it what should trigger the error message.

Now cmpose using:
```
services:
  service-a:
    path: service-a
  service-b:
    path: service-b
    dependsOn:
      - service-a
```
The dependency isn't really needed, but does illustrate the problem better.

When doing an operation (I used package in this case, but deploy is the same) it goes through all the services, but fails silently on service-b. There is a non-zero error code, but if you don't look carefully it appears that things did succeed.
<img width="722" alt="Screenshot 2024-10-18 at 10 13 27" src="https://github.com/user-attachments/assets/098ccf07-77e5-48b3-b564-546f0376ddc6">

A correct error message is in `service-b/.serverless/meta.json`, but as shown in the screenshot never displayed in the CLI.
