### ISSUE TITLE
V4: dev mode throws error when function invoked: Cannot find module '/opt/sls-sdk-node'

### ISSUE THREAD

**Issue by dave-hf** [serverless/serverless#12860]
Issue description
After running serverless dev on a simple service, running serverless invoke on a function in the service or invoking it by making an HTTP request causes dev mode to fail with an error. Full serverless support output in Context below.

Error received:

Error: Cannot find module '/opt/sls-sdk-node'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1574:5)
    at loadPreloadModules (node:internal/process/pre_execution:723:5)
    at setupUserModules (node:internal/process/pre_execution:203:5)
    at prepareExecution (node:internal/process/pre_execution:159:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:54:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v20.12.2

# Service Overview
- Serverless Framework Version: 4.1.22
- Command:  

# Service Overview
- Serverless Framework Version: 4.1.21
- Service Config File: lambda.yml
- Service Name: mainThreads
- Service App: conversaly-api
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: deploy --config mainThreads/lambda.yml

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: neuralcreative
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: conversaly-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: mainThreads
provider:
  name: aws
  runtime: nodejs20.x
functions:
  getReply:
    handler: handler.getReply
```

# Service Overview
- Serverless Framework Version: 4.2.4
- Service Config File: serverless.yml
- Service Name: conversaly-mainThreads
- Service App: conversaly
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1

## Command
dev --config src/mainThreads/serverless.yml,--stage dev

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: neuralcreative2
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: conversaly
# "service" is the name of this project. This will also be added to your AWS resource names.
service: conversaly-mainThreads
provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  timeout: 25
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}-stack


stages:
  prod:
    observability: true
  dev:
    observability: false

functions:
  processTools: 
    name: ${self:service}-${self:provider.stage}-processTools
    handler: processTools/handler.processTools
    events:
      - httpApi:
          method: post
          path: /processTools
          authorizer:
            type: aws_iam
    environment:
      
  getReply:
    name: ${self:service}-${self:provider.stage}-getReply
    handler: handler.getReply
    events:
      - httpApi:
          method: post
          path: /getReply
          authorizer:
            type: aws_iam
    environment:
      DEVSESSION: "false"
      RUN_STAGE: ${sls:stage}

_Originally posted by @dave-hf in https://github.com/serverless/serverless/issues/12535#issuecomment-2313630811_
