### ISSUE TITLE
Cannot resolve package when `minify: true`

### ISSUE THREAD

**Issue by sans-clue** [serverless/serverless#12887]
### Issue description

Trying the built-in build feature documented [here](https://www.serverless.com/framework/docs/providers/aws/guide/building).

```yaml
build:
  esbuild:
    minify: true
```

When trying to deploy, results in the errors shown below.

To replicate:

1. Create a new project and use the AWS + NodeJS + Express API template
2. Added my `org` name and `profile`
3. Run `sls deploy` or `sls package`

### Context

# Service Overview

- Serverless Framework Version: 4.4.7
- Service Config File: serverless.yml
- Service Name: v4-minify-test
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: package
- Error Code: ESBULD_BUILD_ERROR

## Service Path

/home/user/Projects/serverless/v4-minify-test

## Error Message

```
Build failed with 2 errors:
handler.js:1:27: ERROR: Could not resolve "serverless-http"
handler.js:2:24: ERROR: Could not resolve "express"
```

## Error Stacktrace

```
at Esbuild._build (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:685:36178)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async before:package:createDeploymentArtifacts (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:685:25113)
at async PluginManager.runHooks (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:953:9311)
at async PluginManager.invoke (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:953:10023)
at async PluginManager.run (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:953:10813)
at async Serverless.run (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:960:10612)
at async runFramework (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:983:2696)
at async route (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:1011:14772)
at async Object.run2 [as run] (file:///home/user/.serverless/releases/4.4.7/package/dist/sf-core.js:1011:15173)
```

## Service Config

```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: org-name
# "service" is the name of this project. This will also be added to your AWS resource names.
service: v4-minify-test
provider:
  name: aws
  runtime: nodejs20.x
  profile: org-profile-name
build:
  esbuild:
    minify: false
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
```
