### ISSUE TITLE
[V4] ESBuild adding same file to zip multiple times.

### ISSUE THREAD

**Issue by alexw23** [serverless/serverless#12890]
### Issue Summary:
After upgrading to V4 with esbuild (built-in), we are encountering an issue with AWS deployment. The final ZIP file includes multiple instances of the same `src/index.js` and `src/index.js.map` files, despite them having the same resulting path. This redundancy unnecessarily inflates the ZIP size.

### Observations:
- Each function appears to add the same `src/index.js` and `src/index.js.map` files to the ZIP.
- Even though these files are identical and should only appear once, they are included for every function we define, leading to a larger ZIP file.
- Example from the current ZIP contents:

```
unzip -vl REDACTED.zip
Archive:  REDACTED.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
 6502260  Defl:N  1602332  75% 10-26-2024 07:55 af5d8b99  src/index.js
11476823  Defl:N  2855682  75% 10-26-2024 07:55 18ba93bb  src/index.js.map
   52376  Defl:N    11949  77% 10-26-2024 07:55 88cdd256  .warmup/defaultWarmer/index.js
   80197  Defl:N    19440  76% 10-26-2024 07:55 2c450637  .warmup/defaultWarmer/index.js.map
  760144  Defl:N   163546  79% 04-11-2024 08:37 ad41ae11  src/xyz/files/REDACTED
  673945  Defl:N   195900  71% 04-12-2024 11:53 6d2d9eef  src/xyz/files/REDACTED
  683042  Defl:N   196219  71% 04-12-2024 11:01 b420b36b  src/xyz/files/REDACTED
     851  Defl:N      251  71% 04-11-2024 05:26 9883678e  src/xyz/files/REDACTED
   41071  Defl:N    10611  74% 04-11-2024 06:40 9c2c82a2  src/xyz/files/REDACTED
    2810  Defl:N      843  70% 04-11-2024 05:25 2671bb33  src/xyz/files/REDACTED
  189744  Defl:N    15525  92% 04-11-2024 12:01 0e37fd38  src/xyz/files/REDACTED
```

### Root Cause:
It seems that ES build is treating each `src/index.js` as a unique file, resulting in duplicate entries in the ZIP. This is likely due to the packaging configuration or a quirk in how the new esbuild plugin handles output files for multiple functions.

### Context

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.7
- Service Config File: serverless.yml
- Service Name: REDACTED
- Service Runtime: nodejs20.x
- Service Stage: production
- Service Region: REDACTED
- Command: package --stage production,--debug *

## Service Path
REDACTED

## Service Config
```
service: REDACTED

configValidationMode: error
deprecationNotificationMode: error

useDotenv: true

plugins:
  - serverless-plugin-warmup
  - serverless-offline-ssm
  - serverless-offline
  - serverless-prune-plugin

package:
  patterns:
    - src/zyx/files/**/*

build:
  esbuild:
    configFile: ./esbuild.config.js

functions:
  health:
    handler: src/index.health
    events:
      - httpApi:
          path: /health
          method: get
  otherFunction:
    handler: src/index.otherFunction
    events:
      - httpApi:
          path: /other
          method: get
  anotherFunction:
    handler: src/index.anotherFunction
    events:
      - httpApi:
          path: /another
          method: get

# Service Overview
- Serverless Framework Version: 4.4.7
- Command: support 

# ES Build Config
```
import env from "esbuild-plugin-env";

export default () => {
  return {
    plugins: [
      env()
    ],
  };
};
```
