### ISSUE TITLE
Serverless dev not working - IoT connection closed

### ISSUE THREAD

**Issue by Mdelaf** [serverless/serverless#12897]
### Issue description

Using `serverless dev` does not work for me. The IoT connection gets closed right away and then the function timeouts. This happens every time I try to execute the function using dev mode.

CloudWatch logs:
```
INIT_START Runtime - Version: nodejs:20.v42     Runtime Version ARN: arn:aws:lambda:us-west-2::runtime:af2737389420ddcdbcdc4db3585842c334ad2482127c15295905f54a62feefc6
START - 0b84f783-90b8-4365-ac38-bafee104ec04 - Version: $LATEST
2024-10-30 19:12:02.045 - undefined - INFO    AWS IoT connection closed
2024-10-30 19:12:02.207 - undefined - INFO    []
2024-10-31T02:12:08.068Z 0b84f783-90b8-4365-ac38-bafee104ec04 Task timed out after 6.02 seconds
END - 0b84f783-90b8-4365-ac38-bafee104ec04
REPORT - 0b84f783-90b8-4365-ac38-bafee104ec04
Duration: 6024.14 ms    Billed Duration: 6000 ms        Memory Size: 128 MB     Max Memory Used: 29 MB
```

Any ideas?

### Context

# Service Overview
- Serverless Framework Version: 4.4.7
- Service Path: /home/mdelaf/github/backend-services
- Service Config File: serverless.yml
- Service Name: backend-services
- Service App: backend-services
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-west-2
- Command: logs --function migrator

## Service Config
```
org: connectpets
app: backend-services
service: backend-services
provider:
  name: aws
  region: us-west-2
  memorySize: 128
  runtime: nodejs20.x
  httpApi:
    cors: true
package:
  individually: true
functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_USER: ${env:DB_USER}
      DB_PORT: ${env:DB_PORT}
      DB_PASSWORD: ${env:DB_PASSWORD}
    vpc:
      securityGroupIds:
        - ${env:VPC_SECURITY_GROUP}
      subnetIds:
        - ${env:VPC_SUBNET1}
  migrator:
    handler: src/infrastructure/postgres/migrator.migratorHandler
    events:
      - httpApi:
          path: /migrate
          method: GET
    vpc:
      securityGroupIds:
        - ${env:VPC_SECURITY_GROUP}
      subnetIds:
        - ${env:VPC_SUBNET1}
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_USER: ${env:DB_USER}
      DB_PORT: ${env:DB_PORT}
      DB_PASSWORD: ${env:DB_PASSWORD}
    package:
      patterns:
        - 'src/infrastructure/postgres/migrations/**'
build:
  esbuild:
    bundle: true
    packages: external
```
