### ISSUE TITLE
package or deploy failing with package.json not found

### ISSUE THREAD

**Issue by fridaystreet** [serverless/serverless#12901]
### Issue description

Seems to be some sort of bug with the custom esbuild config. I thought at first it was our config, but 
I have run it with the vanilla example in the docs and it still happens. If I run without custom config file it comples the package/deploy fine

module.exports = (serverless) => {
  return {
    external: ['@aws-sdk/client-s3']
  }
}

and it still has the issue

s:core:meta: saving meta record to global .serverless directory.
s:cli-error-handler: Error: ENOENT: no such file or directory, open '/Users/fridaystreet/dev/backend/.serverless/build/package.json'
    at async open (node:internal/fs/promises:639:25)
    at async writeFile (node:internal/fs/promises:1212:14)
    at async Esbuild._preparePackageJson (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/plugins/esbuild/index.js:901:5)
    at async before:package:createDeploymentArtifacts (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/plugins/esbuild/index.js:45:11)
    at async PluginManager.runHooks (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:680:9)
    at async PluginManager.invoke (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:718:9)
    at async PluginManager.run (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:768:7)
    at async Serverless.run (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/serverless.js:221:5)
    at async runFramework (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/lib/runners/framework.js:291:5)
    at async route (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/lib/router.js:221:10)
    at async Object.run2 (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/index.js:45:3)
    at async run3 (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/bin/sf-core.js:33:3)

✖ Error: ENOENT: no such file or directory, open '/Users/fridaystreet/dev/backend/.serverless/build/package.json'
    at async open (node:internal/fs/promises:639:25)
    at async writeFile (node:internal/fs/promises:1212:14)
    at async Esbuild._preparePackageJson (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/plugins/esbuild/index.js:901:5)
    at async before:package:createDeploymentArtifacts (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/plugins/esbuild/index.js:45:11)
    at async PluginManager.runHooks (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:680:9)
    at async PluginManager.invoke (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:718:9)
    at async PluginManager.run (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:768:7)
    at async Serverless.run (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/serverless.js:221:5)
    at async runFramework (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/lib/runners/framework.js:291:5)
    at async route (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/lib/router.js:221:10)
    at async Object.run2 (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/index.js:45:3)
    at async run3 (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/bin/sf-core.js:33:3)

### Context

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.7
- Service Config File: serverless.yml
- Service Name: aleign-api
- Service Runtime: nodejs20.x
- Service Stage: development
- Service Region: ap-southeast-2
- Error Code: ENOENT

## Service Path
/Users/fridaystreet/dev/backend

## Command
package --package .packaged,--stage development,--debug *

## Error Message
ENOENT: no such file or directory, open '/Users/fridaystreet/dev/backend/.serverless/build/package.json'

## Error Stacktrace
```
at async open (node:internal/fs/promises:639:25)
at async writeFile (node:internal/fs/promises:1212:14)
at async Esbuild._preparePackageJson (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/plugins/esbuild/index.js:901:5)
at async before:package:createDeploymentArtifacts (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/plugins/esbuild/index.js:45:11)
at async PluginManager.runHooks (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:680:9)
at async PluginManager.invoke (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:718:9)
at async PluginManager.run (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/classes/plugin-manager.js:768:7)
at async Serverless.run (/Users/fridaystreet/.serverless/releases/4.4.7/serverless/lib/serverless.js:221:5)
at async runFramework (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/lib/runners/framework.js:291:5)
at async route (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/lib/router.js:221:10)
at async Object.run2 (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/src/index.js:45:3)
at async run3 (/Users/fridaystreet/.serverless/releases/4.4.7/sf-core/bin/sf-core.js:33:3)
```

## Service Config
```
# Welcome to Serverless!
# migrate from serverless
# https://medium.com/ssense-tech/the-ssense-migration-journey-from-serverless-framework-to-sam-5fa611d658d6
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
service: aleign-api
# app and org for use with dashboard.serverless.com
frameworkVersion: "4"
plugins:
  # - serverless-sentry
  - serverless-prune-plugin
  - serverless-localstack
build:
  esbuild:
    configFile: ./test.config.js
# you can add packaging information here
# package:
  # individually: true
   patterns:
     - '!node_modules/**'
     - 'node_modules/@abraham/**/*'

custom:
  localstack:
    stages:
      - development
    host: localhost
    edgePort: 4566
    autostart: false
    # lambda:
    #   mountCode: .serverless/build
      # watch: true
      # hotReload: true
    websocket:
      useRestApi: true

  prune:
    automatic: true
    number: 10
provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 10240
  timeout: 30
  # you can overwrite defaults here
  stage: ${opt:stage, 'development'}
  region: ap-southeast-2
  #deploymentBucket: ${self:custom.${self:provider.stage}.bucket}
  #vpc: ${self:custom.${self:provider.stage}.vpc}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cloudwatch:GetMetricStatistics
            - cloudwatch:ListMetrics
            - cloudwatch:PutMetricData
          Resource: "*"
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource: 'arn:aws:execute-api:*:*:*/${self:provider.stage}/POST/@connections/*'
        - Effect: Allow
          Action:
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DescribeStream
            - dynamodb:DescribeTable
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListStreams
          Resource: "*"
        - Effect: Allow
          Action:
            - ses:SendRawEmail
          Resource: "*"
 
  # you can define service wide environment variables here
  environment:
    # AWS_REGION: ap-southeast-2
    NODE_CONFIG_DIR: ./src/config
    NODE_ENV: ${self:provider.stage}
    STAGE: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    APIG_ENDPOINT:
      Fn::Join:
        - ""
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:provider.stage}
functions:
  httpHandler:
    handler: dist/index.handleHttp
    tracing: PassThrough
    events:
      - http:
          path: graphql
          method: any
          # integration: lambda
          cors:
            origin: ${self:custom.${self:provider.stage}.cors.origin}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Client-Version
              - X-Forwarded-*
              - sentry-trace
              - baggage
            allowCredentials: true
          response:
            headers:
              Set-Cookie: integration.response.body.Cookie
  webSocketHandler:
    handler: dist/index.handleWebSocket
    tracing: PassThrough
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  pubSubStreamHandler:
    handler: dist/index.handlePubSubStream
    #this needs to be added manually for now
    tracing: PassThrough
    events:
      - stream:
          enabled: true
          type: dynamodb
          arn:
            Fn::GetAtt: [GraphQLMessagesDynamoDBTable, StreamArn]
          batchSize: 100
          maximumRetryAttempts: 6
          maximumRecordAgeInSeconds: 600
          startingPosition: TRIM_HORIZON
          bisectBatchOnFunctionError: true

resources:
  extensions:
    ApiGatewayRestApi:
      Properties:
        Tags:
          - Key: _custom_id_
            Value: aleign
  
```

test.config.js
```
module.exports = (serverless) => {
  return {
    external: ['@aws-sdk/client-s3']
  }
}
```
package.json
```
{
  "name": "aleign-backend",
  "author": "",
  "license": "ISC",
  "version": "2.0.0",
  "description": "graphql backend api server for aleign.com",
  "main": "src/index.ts",
  "dependencies": {

   ...rest

}
```

**Comment by fridaystreet** [comment]
probably want tsconfig too

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "esnext",
    "target": "esnext",
    "lib": [
      "dom",
      "esnext",
      "esnext.asynciterable"
    ],
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "ignoreDeprecations": "5.0",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "inlineSources": true,
    "importHelpers": true,
    "esModuleInterop": true,
    "declaration": true,
    "sourceRoot": "/",
    "outDir": "./dist",
    "rootDir": "./src",
    "baseUrl": "./",
    "paths": {
      "@utils": ["./src/@utils"],
      "@api/*": ["./src/modules/api/*"],
      "@modules": ["./src/modules"],
      "@data": ["./src/modules/data"],
      "@services": ["./src/modules/services"],
      "@graphql-errors": ["src/@graphql-errors"],
      "@lambda-websocket-server": ["src/@lambda-websocket-server"]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.js", "src/**/*.mjs", "src/**/*.ejs", "src/**/*.graphql"],
  "exclude": ["node_modules"]
}
```

**Comment by fridaystreet** [comment]
The error seems to occur with any attempt to customise the esbuild config. Running now with the example config from the serverless build documentation and getting the same error

The only way I can get it to build is to have no build option in the serverless.yml

build:
  esbuild:
    bundle: true
    # Enable minifying function code. (Default: false)
    minify: false
    # NPM packages to not be bundled. Glob patterns are supported here.
    external:
      - '@aws-sdk/client-s3'
    # NPM packages to not be bundled, as well as not included in node_modules
    # in the zip file uploaded to Lambda. By default this will be set to aws-sdk
    # if the runtime is set to nodejs16.x or lower or set to @aws-sdk/* if set to nodejs18.x or higher.
    # Glob patterns are supported here.
    exclude:
      - '@aws-sdk/*'
      - '!@aws-sdk/client-bedrock-runtime'
    # The packages config, this can be set to override the behavior of external
    # If this is set then all dependencies will be treated as external and not bundled.
    packages: external
    # By default Framework will attempt to build and package all functions concurrently.
    # This property can bet set to a different number if you wish to limit the
    # concurrency of those operations.
    buildConcurrency: 3
    # Enable or configure sourcemaps, can be set to true or to an object with further configuration.
    sourcemap:
      # The sourcemap type to use, options are (inline, linked, or external)
      type: linked
      # Whether to set the NODE_OPTIONS on functions to enable sourcemaps on Lambda
      setNodeOptions: true

**Comment by fridaystreet** [comment]
So not sure if this is just something I'm totally missing, but I've had to just move away from serverless esbuild and do it manually. I still think the above could be a bug as I couldn't get it working even with the doco examples. The only thing I hadn't completely ruled out was some issue with our specific code, but I figured if we can build it ourselves in esbuild, there shouldn't be any issues

our esbuild.config.js file runs fine standalone and tbh I didn't even realise you could do this wioth serverless. Happy accident to discover it had packaed the entire repo into the zip. The lightbulb went off and I thought, oh ok, so if I just build it myself and then use the paackage pattern match to only include my build, we should be cooking on eggs!!  I'm probably just catching up I realise, but if it's of use to anyone else. Just disable it like belwo, run your own build and include it in the serverless package.



```
build:
  esbuild: false
package:
  patterns:
    - '!**'
    - 'node_modules/@abraham/**/*'
    - 'dist/**'
    - 'package.json'
  ```
