### ISSUE TITLE
Migration from v3 to v4 not removing dev dependencies

### ISSUE THREAD

**Issue by ajouve** [serverless/serverless#12918]
### Issue description

I just tried to move from serverless v3 to v4.

This is the main part of my `serverless.yml`

```yml
service: api
frameworkVersion: '4'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  environment:
    STAGE: ${sls:stage}

functions:
  app:
    handler: index.controller
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline
  - serverless-prune-plugin
```

This is ths packege.json

```
{
  "scripts": {
    "mongo-index": "node bin/mongoIndex.js",
    "start": "serverless offline start --host 0.0.0.0 --httpPort 8080 --noPrependStageInUrl --localEnvironment --reloadHandler --stage dev",
    "test": "jest --forceExit --runInBand"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.699.0",
    "@aws-sdk/client-sqs": "^3.699.0",
    "@aws-sdk/s3-request-presigner": "^3.699.0",
    "@sentry/serverless": "^7.114.0",
    "body-parser": "^1.20.2",
    "express": "^4.21.1",
    "joi": "^17.12.2",
    "joi-objectid": "^4.0.2",
    "mailgun.js": "^10.2.4",
    "mime-types": "^2.1.35",
    "moment": "^2.30.1",
    "mongodb": "^6.11.0",
    "node-fetch": "^2.7.0",
    "openai": "^4.73.0",
    "pdfmake": "^0.2.10",
    "request-ip": "^3.3.0",
    "serverless": "^4.4.11",
    "serverless-http": "^3.2.0"
  },
  "devDependencies": {
    "jest": "^29.7.0",
    "mongodb-memory-server": "^10.1.2",
    "serverless-offline": "^14.3.4",
    "serverless-prune-plugin": "^2.1.0"
  }
}
```

Then running `serverless deploy --verbose` I can see `Excluding development dependencies for service package` but then I have an issue `Unzipped size must be smaller than 262144000 bytes`.
Downloading the zip file from s3 all the dev dependencies are in the `node_modules` for example `serverless-offline` is in the packaged modules.

Due to this issue I can not deploy as the package is to heavy
