### ISSUE TITLE
Local invocations require valid provider token (BC break)

### ISSUE THREAD

**Issue by jameshalsall** [serverless/serverless#12912]
### Issue description

If you run a local invocation in SLS v4 without valid provider credentials then you get an access denied type error, e.g. for AWS you need to ensure you have a valid set of AWS credentials in your environment in order to invoke **locally,** e.g.

```
$ /path/to/project/node_modules/.bin/sls invoke local -f migrate --data '{"action": "upgrade"}'

✖ ExpiredToken: The security token included in the request is expired
```

In SLS v3, this worked without AWS credentials. 

Additionally, local invocations are very slow in v4 compared with v3. In v3 they are almost instant.

### Context

# Service Overview
- Serverless Framework Version: 4.4.7
- Command:  --version true

# Service Overview
- Serverless Framework Version: 4.4.11
- Service Config File: serverless.yml
- Service Name: migrate
- Service Runtime: python3.11
- Service Stage: dev
- Service Region: eu-west-1

## Service Path
/Users/jameshalsall/Code/xxx

## Command
invoke local --data {"action": "upgrade"},--function migrate

## Error Message
The security token included in the request is expired

## Error Stacktrace
```
at throwDefaultError (file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:88:8019)
at file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:88:8293
at de_CommandError (file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:162:33465)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:77:25128
at async file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:78:12236
at async file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:88:27574
at async file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:141:7174
at async resolveAccountId (file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:186:996058)
at async getAwsCredentialProvider (file:///Users/jameshalsall/.serverless/releases/4.4.11/package/dist/sf-core.js:248:455896)
```

## Service Config
```
service: migrate
plugins:
  - serverless-python-requirements
  - serverless-plugin-log-retention
  - serverless-prune-plugin
  - serverless-plugin-resource-tagging
custom:
  stage: ${opt:stage, 'dev'}
  lumigo_env_tag_map:
    staging: Staging
    production: Production
    dev: Development
  lumigo_logging:
    layer: arn:aws:lambda:eu-west-1:114300393969:layer:lumigo-log-collector-${self:provider.architecture, 'amd64'}:10
    endpoint: https://ga.lumigo-tracer-edge.golumigo.com/api/logs?token=${self:custom.tf.lumigo_tracer_token}
  tf: ${file(terraform/outputs.json)}
  pythonRequirements:
    dockerizePip: true
    dockerFile: tools/serverless/python-requirements/Dockerfile
    dockerBuildCmdExtraArgs: [ '--platform', 'linux/${self:provider.architecture, "amd64"}' ]
    useDownloadCache: true
    useStaticCache: false
    slim: true
    noDeploy:
      - botocore
      - boto3
    cacheLocation: '.serverless/requirements_cache'
  logRetentionInDays: 30
  prune:
    automatic: true
    includeLayers: true
    number: 3
  vpc_config:
    vpc:
      securityGroupIds: ${self:custom.tf.vpc_security_group_ids}
      subnetIds: ${self:custom.tf.vpc_subnet_ids}
dashboard:
  disableMonitoring: true
provider:
  name: aws
  runtime: python3.11
  memorySize: 512
  timeout: 10
  stage: ${self:custom.stage}
  region: eu-west-1
  deploymentMethod: direct
  environment:
    ENV: ${env:ENV, self:provider.stage}
    LUMIGO_LOG_ENDPOINT: ${self:custom.lumigo_logging.endpoint}
  stackTags:
    DeploymentBy: Serverless
    CostCentre: Migrate
    Environment: ${self:provider.stage}
    lumigo:auto-trace: "true"
    # Match Lumigo's default `Staging` and `Production` tags, otherwise we will have duplicates
    LUMIGO_TAG: ${self:custom.lumigo_env_tag_map.${self:provider.stage}}
  layers:
    - ${self:custom.lumigo_logging.layer}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "rds:CreateDBClusterSnapshot"
            - "rds:ModifyDBCluster"
            - "rds:DescribeDBClusterSnapshots"
            - "rds:DeleteDBClusterSnapshot"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "ssm:PutParameter"
          Resource:
            - ${self:custom.tf.database_schema_version_arn}
package:
  patterns:
    - "!**"
    - xxx/**
    - terraform/outputs.json
functions:
  migrate:
    handler: xxx.lambdas.migrate.execute
    maximumRetryAttempts: 0
    timeout: 300
    vpc: ${self:custom.vpc_config.vpc}
    tags:
      component: migrate
```
