### ISSUE TITLE
Invoke local performance degradation between SLS 3 and SLS 4

### ISSUE THREAD

**Issue by tombarton** [serverless/serverless#12927]
### Issue description

We have a relatively complex and large service that runs 43 different Lambdas. On top of this, we use the `serverless-iam-roles-per-function` to define permissions on an individual Lambda basis. As a result, each Lambda has numerous template strings associated with it.

After upgrading to SLS 4, we've seen a huge performance degradation when it comes to invoking Lambdas locally. On SLS3 , we could invoke a Lambda in roughly 3.5 seconds. On SLS 4, this same Lambda now takes roughly 164 seconds; the vast majority of this is waiting for the configuration to be parsed and the resolver manager to do its thing. If we were to remove all of the templated strings from our configuration, we get roughly the same performance as the SLS 3 setup.

The template strings themselves are just using provider values or environment variables; there are a couple of instances of `!Import` but maybe five or six in total so I don't believe its to do with AWS variables being resolved.

Whilst I know we can use `dev` mode, this isn't always suitable, especially when invoking an individual Lambda in a specific environment.

Any advice would be much appreciated.

### Context

# Service Overview
- Serverless Framework Version: 4.4.6
- Service Config File: serverless.yml
- Service Name: lambdas
- Service App: api
- Service Runtime: nodejs18.x
- Service Stage: dev
- Service Region: eu-west-1

**Comment by czubocha** [comment]
Hey @tombarton, thanks for reporting. To investigate, I'd like to confirm a few details:
* Which variable resolvers are you using? From your description it seems like `self` and `env`are being used - is there anything else? Could you share a rough example of a function definition that heavily uses variables?
* When you run `invoke local` with the `--debug` flag, what logs are displayed during processing? Are they related to variable resolution?
* Do you also notice this performance degradation when running the `print` command, comparing v4 to v3?

**Comment by tombarton** [comment]
Hey @czubocha,

Thanks for getting back to me so quickly. 

1. Please find an example of the heavily used variables below:

* `self:provider.region`
* `AWS::AccountId`
* `self:provider.environment.X`
* `self:custom.stage`

I've attached an example of a small function here:

```
 testFunctionA:
    handler: src/functioNA
    timeout: 30
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - dynamodb:Query
          - dynamodb:UpdateItem
          - dynamodb:PutItem
          - dynamodb:DeleteItem
          - dynamodb:GetItem
        Resource:
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_A}'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_A}/*'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_B}'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_B}/*'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_C}'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_C}/*'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_D}'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_D}/*'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_E}'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_E}/*'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_F}'
          - !Sub 'arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:provider.environment.TABLE_F}/*'
      - Effect: 'Allow'
        Action:
          - 'lambda:invokeFunction'
        Resource:
          - !Sub 'arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:functionB-${self:custom.stage}'
          - !Sub 'arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:functionB-${self:custom.stage}/*'
          - !Sub 'arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:functionC-${self:custom.stage}'
          - !Sub 'arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:functionC-${self:custom.stage}/*'
```

2. Yes, the logs are related to invocation. You can see the placeholders graph prints out, followed by the resolver manager. You see a numerous logs such as `resolved ${env:RESOURCE_SUFFIX, ""} to -dev6` and `resolved ${self:provider.region} to eu-west-1`. This is what seems to take the longest amount of time. This service has one Terraform resolver but if I remove this, there is little to no change. As soon as the `s:core:resolver:manager` logs finish, things speed up greatly. It seems to be resolving `provider.region` which seems to cause the most delays.

3. Yes, I witness the same performance degradation when using the `print` command:

```
npx sls print --debug  178.15s user 1.79s system 98% cpu 3:02.60 total
```

4. I can confirm upgrading to `4.4.12` does not have any impact on this:

```
npx serverless invoke local --stage dev6 --function getActiveOrderForUser     172.09s user 2.32s system 98% cpu 2:57.95 total

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.12
- Service Config File: serverless.yml
- Service Name: lambdas
- Service App: api
- Service Runtime: nodejs18.x
- Service Stage: dev6
- Service Region: eu-west-1
```
