### ISSUE TITLE
[Go Runtime] Different behavior in `serverless invoke local` between v3 and v4

### ISSUE THREAD

**Issue by mkusaka** [serverless/serverless#12921]
## Description

I found behavioral differences in `serverless invoke local` for Go runtime Lambda functions between Serverless Framework v3 and v4. While Node.js runtime functions maintain consistent behavior across versions, Go runtime functions show significant differences.

### Go Runtime in v3

```bash
❯ serverless invoke local --function hello-golang --data '{"name": "test"}' --verbose
Lambda function starting...
START RequestId: c042d736-4031-18d6-71aa-9ff2eba7ff46 Version: $LATEST
Received request: {Name:test}
Sending response: {
  "message": "Hello, test!",
  "input": {
    "name": "test"
  }
}
END RequestId: c042d736-4031-18d6-71aa-9ff2eba7ff46
REPORT RequestId: c042d736-4031-18d6-71aa-9ff2eba7ff46
{"message":"Hello, test!","input":{"name":"test"}}
```

### Go Runtime in v4

```bash
❯ serverless invoke local --function hello-golang --data '{"name": "test"}' --verbose

Excluding development dependencies for function "hello"

```

### Key Differences

1. Output Display
   - v3: Shows function stdout/stderr, Lambda execution logs, and response
   - v4: Shows no output at all
2. Error Handling
   - v3: Returns non-zero exit code and shows error messages when function fails
   - v4: Always returns exit code 0 and shows no error messages
3. Debug Information
   - v3: Provides detailed execution information including request ID, duration, memory usage
   - v4: Provides no execution information

## Expected Behavior
The Go runtime in v4 should maintain the same behavior as v3, especially considering that [the official v4 upgrade guide](https://www.serverless.com/framework/docs/guides/upgrading-v4) does not mention any breaking changes for the AWS provider. 

The expected behavior includes:
- Display function stdout/stderr and Lambda execution logs
- Show function response
- Return appropriate exit codes (non-zero for failures)
- Show error messages when functions fail

## Steps to Reproduce

1. Clone reproduction repository: https://github.com/mkusaka/serverless-framework-v4-golang-local-invoke
2. Test with v3:

```bash
npm i -g serverless@3
make test-local      # Shows full output
make test-local-fail # Shows error and returns non-zero exit code
```

3. Test with v4:

```bash
npm i -g serverless@4
make test-local      # No output
make test-local-fail # No output, returns 0
```

## Environment

- OS: macOS
- Node.js: 20.9.0
- Serverless Framework v3: 3.39.0
- Serverless Framework v4: 4.4.12
- Go: 1.23

## Additional Context

- Node.js runtime functions maintain consistent behavior in both v3 and v4

### Context

# Service Overview
- Serverless Framework Version: 4.4.12
- Service Config File: serverless.yml
- Service Name: local-invoke-demo
- Service Stage: dev
- Service Region: ap-northeast-1

## Service Path
/Users/username/src/github.com/mkusaka/serverless-framework-v4-golang-local-invoke

## Command
invoke local --function hello-golang,--data {"name": "fail"},--verbose true

## Service Config
```
service: local-invoke-demo
# frameworkVersion: '4'
# plugins:
#   - serverless-better-credentials
provider:
  name: aws
  region: ap-northeast-1
  architecture: arm64
package:
  individually: true
  patterns:
    - '!./**'
    - '!./**/*.go'
functions:
  hello:
    handler: handler.hello
    runtime: nodejs20.x
    package:
      patterns:
        - handler.js
  hello-golang:
    handler: bootstrap
    runtime: provided.al2
    package:
      artifact: bin/hello-golang.zip
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
