### ISSUE TITLE
The image manifest or layer media type for the source image is not supported

### ISSUE THREAD

**Issue by talaikis** [serverless/serverless#12933]
### Issue description

No longer able to push images to ECR after upgrading Docker:

```
UPDATE_FAILED: XXXLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "The image manifest or layer media type for the source image xxxxxx.dkr.ecr.region.amazonaws.com/serverless-xxx-stage@sha256:80966d8006f61a65f21ca9ce8a9e1c972ccc9b4b2b79d79
ad2a83e6a54e02ccc is not supported. (Service: Lambda, Status Code: 400, Request ID: 873aad37-92bf-4242-914c-361d010f64e
e)" (RequestToken: 9335626b-3947-aea0-d4bd-1913eb03c3ae, HandlerErrorCode: InvalidRequest)
```

### Context

serverless.yml

```
frameworkVersion: '3'

provider:
  runtime: "nodejs18.x"
  architecture: x86_64
  ecr:
    images:
      firebase:
        path: /image/
```

Dockerfile

```
FROM public.ecr.aws/lambda/nodejs:18
```

Docker version 27.3.1, build ce12230
