### ISSUE TITLE
The value at this path is object, but it should be a string.

### ISSUE THREAD

**Issue by randomhash** [serverless/serverless#12934]
### Issue description

The bug occurs when utilizing templating to set vpc for the lambdas.
sample config:

sls-file1.yml
```
commonSettings: &commonSettings
  handler: src/xxx/handler.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ssm:GetParameters'
      Resource:
        - 'arn:aws:ssm:*:*:parameter/some/parameter'

vpcSettings: &vpcSettings
  securityGroupIds: ${ssm:/ids}
  subnetIds: ${ssm:/ids2}

functions:
  fn1
    <<: *commonSettings
    name: fn1
    vpc: *vpcSettings
    environment:
      some: '1'
  fn2:
    <<: *commonSettings
    name: fn2
    vpc: *vpcSettings
    environment:
      some: '0'
```
main-sls.yml
```
...
functions:
  - ${file(./src/sls-file1.yml):functions}
  - ${file(./src/some-lambda/serverless.yml)}
...
```

The most important thing is that if i have just 1 function that tries to inherit vpcSettings - it's working fine
e.g. each function must define it's vpc property, and i can't find solution on how to actually use template in here not causing the error from title
