### ISSUE TITLE
ESbuild configuration issues

### ISSUE THREAD

**Issue by tombarton** [serverless/serverless#12944]
### Issue description

Hey team,

I'm 95% sure this is user error at this point and apologies if so but thought I'd drop a note just in case. I've been seeing some discrepancies between what I'd expect ESBuild to do and the behaviour I'm witnessing when executing it via the SLS 4 integration. I've put together a [repository here](https://github.com/tombarton/sls-esbuild-issue) highlighting the issue.

If I have a basic ESBuild configuration like so:

```
package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: false
    exclude:
      - "aws-lambda"
      - "@aws-sdk/*"
```

I would expect to see my handlers packaged individually in their relevant zip directories. This is half true in that it produces a handler file with the relevant dependencies bundled and excludes packages I've listed in `exclude`, however, it also adds a `package.json` and `node_modules` directory into the zip. At this point, I have dependencies duplicated between the bundled file and a `node_modules` dir.

If I were to switch over to the popular ESBuild plugin with the exact same config, it produces what I would expect (e.g. an individual bundled file with no package.json or node_modules directory).

I tried using package patterns to exclude node_modules but this had no effect.

Any advice would be much appreciated.

### Context

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.15
- Service Config File: serverless.yml
- Service Name: service-a
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: eu-west-1
- Command: package --debug *

## Service Path
/Users/tombarton/Development/serverless-esbuild-example

## Service Config
```
org: arandomorg
service: service-a
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  logRetentionInDays: 14
functions:
  lambdaA:
    handler: src/lambdaA.handler
    events:
      - httpApi:
          path: /testing
          method: post
package:
  individually: true
# Native ESBuild
build:
  esbuild:
    bundle: true
    minify: false
    exclude:
      - "aws-lambda"
      - "@aws-sdk/*"
# # ESBuild Plugin
# plugins:
#   - serverless-esbuild
# custom:
#   esbuild:
#     bundle: true
#     minify: false
#     exclude:
#       - "aws-lambda"y
#       - "@aws-sdk/*"
# build:
#   esbuild: false
```
