### ISSUE TITLE
node_modules Not Included in Packaging Folder with esbuild Configuration

### ISSUE THREAD

**Issue by khancirhan** [serverless/serverless#12947]
### Issue description

After the recent update, **node_modules** is no longer being included in the packaging folder when using esbuild with the following configuration. This issue occurs in an npm workspace setup.

This is my esbuild.config.js configuration:

```
const pkg = require('./package.json');
const globalPkg = require('../../package.json');
const env = require('esbuild-plugin-env');

module.exports = (serverless) => {
    const externalDeps = Object.keys(pkg.dependencies).filter((dep) => !dep.startsWith('@quantam/'));
    const globalExternalDeps = Object.keys(globalPkg.dependencies);

    return {
        entryPoints: ['handler.ts'],
        bundle: true,
        minify: true,
        sourcemap: 'external',
        platform: 'node',
        external: [...externalDeps, ...globalExternalDeps],
        plugins: [env()],
    };
};
```

The serverless.yml configuration looks like this:
```
yaml
service: <name>

build:
    esbuild:
        configFile: ./esbuild.config.js

plugins:
    - serverless-offline

provider:
    name: aws
    runtime: nodejs20.x
    region: me-central-1
    stage: ${opt:stage, 'dev'}
    
functions:
    app:
        handler: handler.handler
        timeout: 900
        memorySize: 4096
        events:
            - http:
                method: POST
                path: /api/v2/{var1}/images/{var2}

custom:
    serverless-offline:
        httpPort: 5002
        reloadHandler: true
```

Expected Behavior:
**node_modules** dependencies should be included in the packaging folder to allow the service to run properly.

Actual Behavior:
**node_modules** is not included, causing the deployed service to fail due to missing dependencies.

Environment Information:

Node.js version: 20.12.2
Serverless Framework version: 4.4.15

**Important Note:**
When I downgraded the version by specifying frameworkVersion: '4.1.19' in serverless.yml, the issue was resolved, and node_modules was included in the packaging folder as expected.
