### ISSUE TITLE
Serverless V4 not packaging external modules as part of zip when using Serverless Compose

### ISSUE THREAD

**Issue by joe-price-jt** [serverless/serverless#12957]
### Issue description

# Bug

We're currently using Serverless Compose to deploy a number of Node services defined in a single repository in sequence. All services use a common build file:

```yml
# build.yml

esbuild:
  treeShaking: true
  sourcemap: true
  minifyWhitespace: true
  minifySyntax: true
  external:
    - zod
```

```yml
# serverless.yml

service: some-service

frameworkVersion: '4'

build: ${file(../build.yml)}

provider:
  name: aws
  region: eu-west-2

functions:
  hello:
    handler: handler.hello
    runtime: nodejs20.x
```

In this case, `zod` is labelled as a dependency in our top-level `package.json`.

As `zod` is being labelled as an external dependency in the build configuration; when I package this service via Serverless Compose (e.g. `npx sls some-service package --stage=local`), I expect `zod` to be included as part of the `node_modules` directory for each lambda function zip. However, this is not the case:

<img width="787" alt="Screenshot 2024-12-16 at 10 18 52" src="https://github.com/user-attachments/assets/b8b43a0e-8aa2-4234-9707-f8950014fafa" />

This is behaving as expected in a different repository with the same build configuration where Serverless Compose is not being utilised:

<img width="787" alt="Screenshot 2024-12-16 at 10 20 32" src="https://github.com/user-attachments/assets/a45dff56-7261-43de-93f4-3743c12772c2" />

When packaging via Serverless Compose with debug logs enabled, I can see that Serverless V4 is registering `zod` as an external dependency:

```
s:esbuild: Setting default external for node version  20 nodejs20.x
s:esbuild: Initial External  [ '@aws-sdk/*', 'zod' ]
s:esbuild: Initial Exclude  [ '@aws-sdk/*' ]
s:esbuild: Setting default external for node version  20 nodejs20.x
s:esbuild: Initial External  [ '@aws-sdk/*', 'zod' ]
s:esbuild: Initial Exclude  [ '@aws-sdk/*' ]
```

# Summary

When packaging services via Serverless Compose, Serverless V4 does not seem to include packages labelled as external in the build configuration as part of the `node_modules` directory for each lambda function zip. This is preventing us from migrating our repository using Serverless Compose to V4. Is there something that I've missed here?

### Context

Serverless Framework version: 4.4.16
