### ISSUE TITLE
Issue with stack deploy: utils folder not uploading to Lambda

### ISSUE THREAD

**Issue by cvargas-xbrein** [serverless/serverless#12951]
### Issue description

While performing a stack deploy that includes a Lambda function, I encountered an issue where the folder named utils is not being uploaded correctly to the Lambda environment. As a result, I had to move the utils folder into the shared directory to include it in the deployment.

Details of the issue:
Project: [Project Name]
Context: I am using the Serverless Framework to manage my Lambda functions.
Configuration file: functions.yml
Path of the utils folder: server_api/src/utils
Example Code:
Relevant part of the functions.yml file

```
estimation:  
  name: ${self:service}-${self:custom.stage}-estimation  
  description: Implement local canibalization and distribution from parameters.  
  memorySize: 512  
  timeout: 90  
  handler: src/canibalizacion/handler.canibalizacion  
  maximumRetryAttempts: 0  
  layers:  
    - Ref: PythonRequirementsLambdaLayer  
    - arn:aws:lambda:us-east-1:776094321928:layer:Klayers-p39-psycopg2-binary:1  
    - arn:aws:lambda:us-east-1:958513130367:layer:p11-opencvxl:1  
  package:  
    patterns:  
      - "**" # Exclude everything first  
      - "shared/**" # Include everything in shared  
      - "src/canibalizacion/**" # Explicitly include the folder and its content
```

![image](https://github.com/user-attachments/assets/c80a11d0-50f4-43eb-9f82-96ee8a26492f)

Environment: win32, node 18.17.1, framework 3.34.0, plugin 6.4.0, SDK 4.4.0
Observations:
When attempting this deploy, the utils folder is not included unless it is moved to shared.
This behavior is unexpected and causes confusion, as it should allow folders under src to be uploaded automatically.
Steps to Reproduce:
Run the stack deploy command using the functions.yml file that contains a reference to utils.
Check the AWS Lambda console to see if the utils folder is present.

### Context

Environment: win32, node 18.17.1, framework 3.34.0, plugin 6.4.0, SDK 4.4.0

I hope this issue can be resolved so that the utils folder is included without needing to move it to the shared directory. This would facilitate project structure and make dependency and utility management clearer.

Thank you for your attention, and I look forward to any updates.
