### ISSUE TITLE
Error %userprofile% is not defined when running npm run dev from the project root (monorepo)

### ISSUE THREAD

**Issue by santisemhan** [serverless/serverless#12954]
### Description:
When running `npm run dev` from the monorepo root, I encounter the error:

`Error: %userprofile% is not defined`

However, if I run `npm run dev` from the serverless project directory (apps/serverless), it works correctly.

This issue only occurs with Serverless Framework version `4.4.16` and Serverless Offline version `14.4.0`. When using Serverless Framework `3.39.0` and Serverless Offline `13.9.0`, the command works correctly even from the monorepo root.

### Aditional Data:

Monorepo `package.json`:

```json
{
  "private": true,
  "scripts": {
    "build": "turbo build",
    "dev": "turbo dev --parallel",
    "lint": "turbo lint",
    "format": "prettier --write \"**/*.{ts,tsx,md,js,jsx}\""
  },
  "devDependencies": {
    "@types/node": "^22.10.2",
    "prettier": "^3.4.2",
    "turbo": "^2.3.3",
    "typescript": "^5.7.2"
  },
  "engines": {
    "node": "20.x"
  },
  "packageManager": "npm@10.9.2",
  "workspaces": [
    "apps/*",
    "packages/*"
  ]
}

```

Serverless project `package.json`:

```json
{
  "version": "0.1.0",
  "scripts": {
    "dev": "serverless offline --noPrependStageInUrl --reloadHandler --stage local",
    "lint": "eslint \"src/**/*.{ts,js}\""
  },
  "devDependencies": {
    "@repo/eslint-config": "*",
    "@types/aws-lambda": "^8.10.146",
    "@types/reflect-metadata": "^0.0.5",
    "reflect-metadata": "^0.2.2",
    "serverless": "^4.4.16",
    "serverless-offline": "^14.4.0",
    "typedi": "^0.10.0"
  }
}
```

Serverless configuration:
```yaml
service: backend  
frameworkVersion: '4'  

provider:  
  name: aws  
  runtime: nodejs20.x  
  region: ${self:custom.region}  
  stage: local  

custom:  
  environment: ${file(./src/main/serverless/configuration/environment.yaml)}  
  region: "us-east-1"  
  stage: ${opt:stage, self:provider.stage}  
  serverless-offline:  
    httpPort: ${env:SERVERLESS_OFFLINE_HTTP_PORT, 3000}  
    websocketPort: ${env:SERVERLESS_OFFLINE_WEBSOCKET_PORT, 3001}  
    noPrependStageInUrl: true  
    reloadHandler: true  

plugins:  
  - serverless-offline  

functions:  
  - ${file(./src/main/serverless/functions/Example.yaml)} 
```

`npm run dev` on root: 

![image](https://github.com/user-attachments/assets/021eb196-fa13-4c5c-9077-e01095b9172d)

`npm run dev` on serverless app root:

![image](https://github.com/user-attachments/assets/6adadc9d-f429-4c84-b1af-2b33192e7224)
