### ISSUE TITLE
Serverless prod deploy cli doesn't compile from typescript to JS

### ISSUE THREAD

**Issue by Andriy-Kulak** [serverless/serverless#12967]
### Issue description

The latest Serverless framework has native typescript support but has deployment issues if im using cli to deploy.

Locally when I invoke functions, they work great. however, when i deploy using github actions using `serverless deploy` [ref](https://github.com/serverless/github-action), the deployed files in AWS Lambda are still in typescript when they should be transpiled to javascript. Lambda obviously doesn't understand typescript and cannot find handler.

how do I ensure that javascript build files are created so that lambda can reference them in production? what can i do in `serverless.yaml` or via cli to fix this? I tried adding below in serverless.yaml but it did nothing in prod. Cheers

```yaml
# serverless.yaml
build:
  esbuild:
    # Enable or Disable bundling the function code and dependencies into a single file. (Default: true)
    bundle: true
    minify: true
```

### Context

Using ` "serverless": "^4.4.18"`
