### ISSUE TITLE
V4 cannot deploy using --package option

### ISSUE THREAD

**Issue by aidmax** [serverless/serverless#12964]
### Issue description

Hello, it seems [v4.4.17](https://github.com/serverless/serverless/releases/tag/v4.4.17) did not resolve deployment issue https://github.com/serverless/serverless/issues/12775 for us. 

### Context

Commands:
`$ sls package --stage dv

Packaging "aircrafts-api" for stage "dv" (eu-west-1)

[serverless-package-external] Symlinking ../../shared

[serverless-package-external] is complete

[serverless-package-external] cleaning up

✔ Service packaged (3s)

$ sls deploy --stage dv -p .serverless --verbose

Deploying "aircrafts-api" to stage "dv" (eu-west-1)
✖ Stack aircrafts-api-dv failed to deploy (0s)

✖ ServerlessError2: No aircrafts-api.zip file found in the package path you provided.
    at file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:724:2729
    at Array.forEach (<anonymous>)
    at AwsDeploy.extendedValidate (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:724:1767)
    at before:deploy:deploy (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:738:4651)
    at async PluginManager.runHooks (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:925:9311)
    at async PluginManager.invoke (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:925:10023)
    at async PluginManager.run (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:925:10813)
    at async Serverless.run (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:932:10667)
    at async runFramework (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:980:2770)
    at async route (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:1010:14772)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/

$ tree .serverless
.serverless
├── build
│   ├── aircrafts-api.zip
│   ├── functions
│   │   ├── create.js
│   │   ├── create.js.map
│   │   ├── delete.js
│   │   ├── delete.js.map
│   │   ├── getById.js
│   │   ├── getById.js.map
│   │   ├── getMany.js
│   │   ├── getMany.js.map
│   │   ├── update.js
│   │   └── update.js.map
│   ├── package-lock.json
│   └── package.json
├── cloudformation-template-create-stack.json
├── cloudformation-template-update-stack.json
├── meta.json
└── serverless-state.json

2 directories, 17 files

$ tail .serverless/serverless-state.json
    },
    "appId": null,
    "orgId": null,
    "layers": {}
  },
  "package": {
    "artifactDirectoryName": "serverless/aircrafts-api/dv/1734948449706-2024-12-23T10:07:29.706Z",
    "artifact": "aircrafts-api.zip"
  }
}%
`

$ serverless support --summary

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.17
- Service Config File: serverless.yml
- Service Name: aircrafts-api
- Service Runtime: nodejs18.x
- Service Stage: dv
- Service Region: eu-west-1
- Error Code: MISSING_ARTIFACT_FILE

## Service Path
/Users/Maksim_Milykh/Documents/git/SNN-AIR/snn-db/src/aircrafts

## Command
deploy --stage dv,--verbose true,--package .serverless

## Error Message
No aircrafts-api.zip file found in the package path you provided.

## Error Stacktrace
```
at file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:724:2729
at Array.forEach (<anonymous>)
at AwsDeploy.extendedValidate (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:724:1767)
at before:deploy:deploy (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:738:4651)
at async PluginManager.runHooks (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:925:9311)
at async PluginManager.invoke (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:925:10023)
at async PluginManager.run (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:925:10813)
at async Serverless.run (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:932:10667)
at async runFramework (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:980:2770)
at async route (file:///Users/Maksim_Milykh/.serverless/releases/4.4.17/package/dist/sf-core.js:1010:14772)
```

## Service Config
```
service: aircrafts-api
frameworkVersion: '4.4.17'
configValidationMode: error
provider:
    name: aws
    runtime: nodejs18.x
    region: eu-west-1
    stage: ${opt:stage, 'dv'}
    vpc: ${self:custom.vpc.${self:provider.stage}}
    tracing:
        lambda: true
    environment:
    <redacted>
    apiGateway:
    <redacted>

functions:
    get_aircrafts:
        handler: functions/getMany.handler
        timeout: 20
        events:
            - http:
                path: aircrafts
                method: get
 <redacted>
    create_aircrafts:
        handler: functions/create.handler
        timeout: 20
        events:
            - http:
                path: aircrafts
                method: post
 <redacted>
    get_aircrafts_by_id:
        handler: functions/getById.handler
        timeout: 20
        events:
            - http:
                path: aircrafts/{id}
                method: get
 <redacted>
    update_aircrafts_by_id:
        handler: functions/update.handler
        timeout: 20
        events:
            - http:
                path: aircrafts/{id}
                method: put
 <redacted>
    delete_aircrafts_by_id:
        handler: functions/delete.handler
        timeout: 20
        events:
            - http:
                path: aircrafts/{id}
                method: delete
 <redacted>
plugins:
    - serverless-offline
    - serverless-package-external
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
