### ISSUE TITLE
Serverless dev not working - Dev Mode Disconnected

### ISSUE THREAD

**Issue by heymaaz** [serverless/serverless#12968]
### Issue description

I created a serverless project using serverless cli and got the default HTTP API in NodeJS. I tried serverless deploy and after setting up a bunch of IAM got it working, but when I switch to serverless dev it says its running
serverless dev
```

Dev ϟ Mode

Dev Mode redirects live AWS Lambda events to your local code enabling you to develop faster without the slowness of deploying changes.

Docs: https://www.serverless.com/framework/docs/providers/aws/cli-reference/dev

Run "serverless deploy" after a Dev Mode session to restore original code.

Functions:
  hello: LessonDepot-dev-hello (80 kB)

Endpoints:
  GET - https://rra33cx69g.execute-api.eu-west-2.amazonaws.com/
```

but on the website I get the following error:
`
Dev Mode Disconnected: This AWS Lambda function is instrumented with Serverless Framework's Dev Mode but the Dev Mode session is no longer active. Run `serverless dev` to reconnect, or `serverless deploy` to remove Dev Mode's instrumentation and restore the original code.
`

### Context

# Service Overview
- Serverless Framework Version: 4.4.18
- Service Config File: serverless.yml
- Service Name: LessonDepot
- Service Runtime: nodejs22.x
- Service Stage: dev
- Service Region: eu-west-2
- Command: dev 

## Service Path
/Users/maazchowdhry/Documents/LessonDepot

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: heymaaz
# "service" is the name of this project. This will also be added to your AWS resource names.
service: LessonDepot
provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'iot:*'
      Resource: '*'
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
```
