### ISSUE TITLE
V4 - sls deploy does not throw if handler path is incorrect or does not exist

### ISSUE THREAD

**Issue by james-cohen** [serverless/serverless#12970]
### Issue description

We experienced a bug recently because the path to a handler in our serverless.yml was incorrect but `sls deploy` succeeded, giving no indication that anything was wrong. On inspection, the only indicator was that the file size for the deployed zip was 1.2kb.

The `deploy` and `package` functions should throw if a path is invalid

### Context

```
service: test-api

package:
  individually: true

build:
  esbuild:
    configFile: ./config/esbuild.config.js

provider:
  name: aws
  profile: ***
  deploymentMethod: direct
  versionFunctions: false
  runtime: nodejs22.x
  memorySize: 1536
  region: ${opt:region, 'eu-west-2'}
  stage: ${opt:stage}
functions:
  testHandler:
    handler: handlers/madeUpPath.default <-- does not exist
```

Output when running `sls deploy function -f testHandler -s dev`:

```
⠏ Initializing(node:42618) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Deploying function "testHandler" to stage "dev" (eu-west-2)
Loading AppSync config
⠋ Uploading (1.2 kB)
✔ Function code deployed (1s)
Retrying configuration update for function: testHandler. Reason: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:eu-west-2:531882032324:function:test-api-dev-testHandler
✔ Function configuration updated (2s)

Retrying ensure function state for function: testHandler.
Retrying ensure function state for function: testHandler.
```
