### ISSUE TITLE
Provider-level layer with 'sls deploy function' gives error

### ISSUE THREAD

**Issue by tkgregory** [serverless/serverless#12975]
### Issue description

I'm using a layer defined at the provider level that applies to all functions.

```yml
layers:
  test:
    path: layer
provider:
  layers:
    - !Ref TestLambdaLayer
 ```

The [docs](https://www.serverless.com/framework/docs/providers/aws/guide/layers#using-your-layers) describe using `!Ref` like this to reference a layer within the same service as supported.

But with such a configuration, when I deploy an individual function, I get this error.

```
sls deploy function -f grantRepositoryAccess

Deploying function "grantRepositoryAccess" to stage "dev" (us-east-1)

✔ Function code deployed (2s)


✖ ServerlessError2: Expected params.Layers[0] to be a string
    at file:///Users/tom/.serverless/releases/4.4.18/package/dist/sf-core.js:700:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async persistentRequest (file:///Users/tom/.serverless/releases/4.4.18/package/dist/sf-core.js:699:1962)
```

Note that even though an error is printed, the function code is still updated.

Since there is no error when I use the plain `sls deploy`, I expect the same behaviour .

### Context

# Service Overview
- Serverless Framework Version: 4.4.18
- Service Path: /Users/tom/workspace/devlaunchpad-site
- Service Config File: serverless.yml
- Service Name: devlaunchpad-site
- Service Runtime: nodejs22.x
- Service Stage: dev
- Service Region: us-east-1
- Command: deploy

**Comment by tkgregory** [comment]
@czubocha Good to know. But how come no error is reported when the layers are defined on the function level?

```
functions:
  grantRepositoryAccess:
    handler: serverless/functions/custom/grant-repository-access.handler
    layers:
      - !Ref ApiLambdaLayer
   ```

Running `sls deploy function -f grantRepositoryAccess` gives:
```
Deploying function "grantRepositoryAccess" to stage "dev" (us-east-1)

✔ Function code deployed (2s)

Function configuration did not change, so the update was skipped. If you made changes to the service configuration and expected them to be deployed, this most likely means that they can only be applied with a full service deployment: "serverless deploy". (2s)
```

I was expecting the behaviour to match (ideally without the error).
