### ISSUE TITLE
[v4] `serverless deploy` workflow breaks with new `poetry` version 2.0.0

### ISSUE THREAD

**Issue by johnlarkin1** [serverless/serverless#12987]
### Issue description

I tried numerous numerous things to get this working. 

Upgrading to poetry 2.0.0  causes this workflow to break, specifically it does not end up pulling the relevant third party or external Github packages. 

What is even more interesting is the underlying `requirements.txt` that is generated in poetry < 2 and poetry = 2 are the exact same. More than happy to provide more detail, but after ~45min i just downgraded `poetry` again and re-ran the `serverless deploy` command and everything worked fine. It was a noticable package discrepancy in terms of size (5MB vs 30MB) so it seems to be something with how those packages are being pulled in in poetry 2.0.0.

### Context

╭─johnlarkin@Larkins-Unit ~/Documents/coding/scrollz/lambdas/email-ingestion-lambda ‹hotfix/john/load-vs-python-dotenv*›
╰─➤  serverless support --summary

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.18
- Service Config File: serverless.yml
- Service Name: ses-email-processor
- Service Runtime: python3.12
- Service Stage: dev
- Service Region: us-east-1
- Command: deploy

## Service Path
/Users/johnlarkin/Documents/coding/scrollz/lambdas/email-ingestion-lambda

## Service Config
```
service: ses-email-processor
provider:
  name: aws
  runtime: python3.12
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    VELVET_API_KEY: ${env:VELVET_API_KEY}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::scrollz-emails/*"
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
        - "sns:Subscribe"
      Resource:
        - "arn:aws:sns:us-east-1:999691295565:ses-email-topic"
functions:
  processEmail:
    handler: lambda_function.lambda_handler
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:999691295565:ses-email-topic
    timeout: 300
    memorySize: 512
# resources:
#   Resources:
#     SnsTopic:
#       Type: AWS::SNS::Topic
#       Properties:
#         TopicName: ses-email-topic
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    usePoetry: true
    dockerizePip: true
    poetryWithGroups:
      - main
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
