### ISSUE TITLE
Serverless Dependency Bundling not respecting lockfiles

### ISSUE THREAD

**Issue by samchungy** [serverless/serverless#12990]
### Issue description

Ran into an icky bug today where we suddenly couldn't deploy because Serverless does not seem to consider our project's lock file and pulled in the latest version of a dependency which had a bug which was very confusing to us as we assumed Serverless would use our locked version.

When we checked the output build we discovered:

Serverless `.build` folder `yarn lock`

![Image](https://github.com/user-attachments/assets/d6cb4ed1-a95a-49c6-b2e4-f58c462072e9)

Project's `yarn lock` file.

![Image](https://github.com/user-attachments/assets/43241790-18d1-404c-9429-459d0b7eabb9)

Serverless `build` config:

```
build:
  esbuild:
    bundle: true
    minify: false
    sourcemap:
      type: linked
      # Whether to set the NODE_OPTIONS on functions to enable sourcemaps on Lambda
      setNodeOptions: true
    target: 'node20'
    define: { 'require.resolve': undefined }
    platform: 'node'
    buildConcurrency: 10
    packages: external
```
