### ISSUE TITLE
Runtime errors when using built-in esbuild

### ISSUE THREAD

**Issue by codan84** [serverless/serverless#12998]
### Issue description

Minimal repo to recreate the issue:
https://github.com/codan84/serverless-esbuild-issue

When using built-in esbuild (afaik version [0.19.12](https://github.com/serverless/serverless/blob/main/package.json#L46)) with the below config, some node_modules will get bundled in such a way as to cause runtime error (also below).   
Config:
```
build:
  esbuild:
    bundle: true
    target: es2020
    platform: node
    sourcemap:
      type: linked
      setNodeOptions: true
```
Error:
```
{
    "timestamp": "2025-01-22T21:18:37.441Z",
    "level": "ERROR",
    "message": {
        "errorType": "Error",
        "errorMessage": "Dynamic require of \"node:os\" is not supported",
        "stackTrace": [
            "Error: Dynamic require of \"node:os\" is not supported",
            "    at file:///var/task/src/index.js:11:9",
            "    at node_modules/pino/pino.js (/node_modules/pino/pino.js:3:12)",
            "    at __require2 (file:///var/task/src/index.js:14:50)",
            "    at <anonymous> (/src/index.ts:1:22)",
            "    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)",
            "    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)",
            "    at async _tryAwaitImport (file:///var/runtime/index.mjs:1008:16)",
            "    at async _tryRequire (file:///var/runtime/index.mjs:1057:37)",
            "    at async _loadUserApp (file:///var/runtime/index.mjs:1081:16)",
            "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)"
        ]
    }
}
```

When I manually package with latest esbuild and following config, all works fine. Differences in bundled files are small, but obviously significant.
```
npx esbuild src/index.ts --bundle --sourcemap --platform=node --target=es2020 --outdir=artifacts/src
```

I am unsure if there are some hidden default config differences etc, because when bundling manually with the same version of esbuild as what comes with serverless, everything still runs alright:
```
npx esbuild@0.19.12 src/index.ts --bundle --sourcemap --platform=node --target=es2020 --outdir=artifacts/src
```

Expected behaviour: all dependencies get bundled correctly and there are no runtime errors.

### Context

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.19
- Service Config File: serverless.yml
- Service Name: serverless-esbuild-issues
- Service Runtime: nodejs22.x
- Service Stage: dev
- Service Region: eu-west-2
- Command: deploy 

## Service Path
/Users/dang/workspace/priv/serverless-build-issue

## Service Config
```
service: serverless-esbuild-issues
## Uncomment below for manual bundling with esbuild
# package:
#   artifact: artifacts/lambda.zip
## Uncomment below for serverless esbuild scenario
build:
  esbuild:
    bundle: true
    target: es2020
    platform: node
    sourcemap:
      type: linked
      setNodeOptions: true
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  runtime: nodejs22.x
  logs:
    lambda:
      logFormat: JSON
functions:
  user:
    handler: src/index.handle
    events:
      - httpApi:
          path: /
          method: get
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
