### ISSUE TITLE
Serverless ignores package->artifact config

### ISSUE THREAD

**Issue by codan84** [serverless/serverless#12999]
### Issue description

Minimal repo to recreate the issue (this repo also represents bundling issue, submitted separetly):
https://github.com/codan84/serverless-esbuild-issue

Config:
```
package:
  artifact: artifacts/lambda.zip
```

The artifact exists at the path above.  
According to the [docs](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#package) when running `serverless deploy` the default packaging behaviour should be ignored and the existing zip used.  
For some reason serverless still does its own bundling/packaging and the zip is ignored.

### Context

Serverless ϟ Support

This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.19
- Service Config File: serverless.yml
- Service Name: serverless-esbuild-issues
- Service Runtime: nodejs22.x
- Service Stage: dev
- Service Region: eu-west-2
- Command: deploy 

## Service Path
/Users/dang/workspace/priv/serverless-build-issue

## Service Config
```
service: serverless-esbuild-issues
## Uncomment below for manual bundling with esbuild
 package:
   artifact: artifacts/lambda.zip
## Uncomment below for serverless esbuild scenario
#build:
#  esbuild:
#    bundle: true
#    target: es2020
#    platform: node
#    sourcemap:
#      type: linked
#      setNodeOptions: true
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  runtime: nodejs22.x
  logs:
    lambda:
      logFormat: JSON
functions:
  user:
    handler: src/index.handle
    events:
      - httpApi:
          path: /
          method: get
```

Above is a summary report of your last Serverless Framework command.

Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue
