### ISSUE TITLE
How to disable auto-update v4

### ISSUE THREAD

**Issue by babay123** [serverless/serverless#13003]
### Issue description

We used Serverless v4.4.18 and serverless/compose, and it worked well. However, today version 4.5.0 was released, and now it doesn’t work during deployment. It throws the error: `Cannot parse "serverless": Unsupported file extension` for one of the services.

We even specified the version we wanted with `npm install serverless@4.4.18 -g`. While it initially installs v4.4.18, it immediately updates to v4.5.0, causing the deployment to crash.

**Comment by czubocha** [comment]
Hey @babay123,

You can pin the version by using the `frameworkVersion` property in your config file ([docs](https://www.serverless.com/framework/docs/providers/aws/guide/services#pinning-a-version)).
 
The `cannot parse "serverless": Unsupported file extension` error seems to occur in v4.5.0 when there’s a directory named `serverless` in the same location as your configuration file. The fix for that will be included in the next release.

Could you confirm if this is the case for you as well? If not, would you mind sharing your working directory structure?

**Comment by czubocha** [comment]
Hey @babay123

I tried to reproduce the issue but was unable to. Could you please double-check that there isn't a directory named `serverless` in the same location as your `serverless-compose.yml` or `serverless.yml`? Is it possible that such a directory is being created during your deployment pipeline process?

Does it work if you deploy directly from the service directory without using Compose? If possible, could you share the execution debug logs for further investigation?

Regarding `frameworkVersion` with Compose, I agree this is a limitation. We'll work on adding support for `frameworkVersion` in `serverless-compose.yml`

This is the configuration I used to test the issue:
```
  serverless-compose.yml
  services/
    service-a/
      handler.js
      serverless.yml
    service-b/
      handler.js
      serverless.yml
```

serverless-compose.yml
```
services:
  service-a:
    path: services/service-a
  service-b:
    path: services/service-b
```
services/service-a/serverless.yml
```
service: compose-a

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
```

services/service-b/serverless.yml
```
service: compose-b

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
```

sls version
```
Serverless ϟ Framework 4.5.0
```

sls deploy
```
Serverless ϟ Compose
Serverless Compose enables you to deploy multiple services in one command, in parallel, or ordered by dependencies.
Docs: https://www.serverless.com/framework/docs/guides/compose

✔ service-b
    HelloLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:xxx
    ServerlessDeploymentBucketName: serverless-framework-deployments-us-east-1-xxx
 
✔ service-a
    HelloLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:xxx
    ServerlessDeploymentBucketName: serverless-framework-deployments-us-east-1-xxx
 
Results: 2 services succeeded, 0 failed, 0 skipped, 2 total    Time: 1m 7s
```
