### ISSUE TITLE
Unable to use Gitlab CI - IncompleteSignature

### ISSUE THREAD

**Issue by flaviu-chelaru** [serverless/serverless#13008]
### Issue description

I configured the serverless framework in a Gitlab CI pipeline 

```yaml
stages:
  - publish

#variables:
#  CI_DEBUG_TRACE: 0
#  AWS_ACCESS_KEY_ID: ''
#  AWS_SECRET_ACCESS_KEY: ''

.deploy:
  image: node:20.12-alpine
  stage: publish
  interruptible: true
  before_script:
    - yarn install --cache-folder $CI_PROJECT_DIR/.yarn
  cache:
    key: npm-${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn
      - node_modules
  script:
    - yarn install --cache-folder .yarn
    - yarn run sls deploy --stage=$CI_ENVIRONMENT_NAME --debug

Deploy to test env:
  extends: .deploy
  environment: 'alpha'
  rules:
    - when: manual
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Publish to prod:
  extends: .deploy
  environment: 'production'
  rules:
    - if: $CI_COMMIT_TAG


```

My serverless file

```yaml
org: cfv1000
app: app-mo
service: app-mo
configValidationMode: error

stages:
  dev:
    resolvers:
      aws-account-1:
        type: aws
        region: eu-central-1
        profile: default
        dashboard: false
  alpha:
    resolvers:
      aws-account-1:
        type: aws
        region: eu-central-1
        accessKeyId: ${env:AWS_ACCESS_KEY_ID, ''}
        secretAccessKey: ${env:AWS_SECRET_ACCESS_KEY, ''}
        dashboard: false
  production:
    resolvers:
      aws-account-1:
        type: aws
        region: eu-central-1
        accessKeyId: ${env:AWS_ACCESS_KEY_ID, ''}
        secretAccessKey: ${env:AWS_SECRET_ACCESS_KEY, ''}
        dashboard: false

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs20.x
  stage: ${opt:stage, 'alpha'}
  environment:
    DOCUMENTS_BUCKET: ${self:service}-${opt:stage, self:provider.stage}-documents
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - 'arn:aws:s3:::${self:provider.environment.DOCUMENTS_BUCKET}/*'

functions:
  rateHandler:
    name: download-mo-docs-${opt:stage, self:provider.stage}
    handler: handler.run
    timeout: 300
    logRetentionInDays: 1
    memorySize: 1024
    events:
      - schedule:
          method: scheduler
          rate:
            - cron(0 23 ? * MON-FRI *)
          timezone: Europe/Bucharest

resources:
  Resources:
    S3Documents:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:provider.environment.DOCUMENTS_BUCKET}

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@types/*'
      - serverless
    external:
      - serverless
      - axios
      - cheerio
      - '@aws-sdk/client-s3'


```

With these configurations, i have an error on authenticating to AWS, even though i have configured correctly the `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `SERVERLESS_ACCESS_KEY` keys ( i checked multiple times - no spaces, values are passed, everything works)

<img width="1001" alt="Image" src="https://github.com/user-attachments/assets/b34c072e-a741-4403-9fb0-9b93f599458d" />

Full relevant trace bellow - 

```
Finishing
s:core:meta: IncompleteSignature: Invalid key=value pair (missing equal-sign) in Authorization header (hashed with SHA-256 and encoded with Base64): 'XBN9CqnPB+Nko16q0x3O5xCOzbW5HP+hqlII3xiHotM='.
    at throwDefaultError (/root/.serverless/releases/node_modules/@smithy/smithy-client/dist-cjs/index.js:846:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/smithy-client/dist-cjs/index.js:855:5)
    at de_CommandError (/root/.serverless/releases/node_modules/@aws-sdk/client-sts/dist-cjs/index.js:476:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/core/dist-es/middleware-http-signing/httpSigningMiddleware.js:18:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38)
    at <anonymous> (/root/.serverless/releases/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22)
    at resolveAccountId (/root/.serverless/releases/4.4.19/sf-core/src/lib/resolvers/providers/aws/aws.js:169:34)
    at getAwsCredentialProvider (/root/.serverless/releases/4.4.19/sf-core/src/utils/credentials/index.js:40:20)
s:cli-error-handler: IncompleteSignature: Invalid key=value pair (missing equal-sign) in Authorization header (hashed with SHA-256 and encoded with Base64): 'XBN9CqnPB+Nko16q0x3O5xCOzbW5HP+hqlII3xiHotM='.
    at throwDefaultError (/root/.serverless/releases/node_modules/@smithy/smithy-client/dist-cjs/index.js:846:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/smithy-client/dist-cjs/index.js:855:5)
    at de_CommandError (/root/.serverless/releases/node_modules/@aws-sdk/client-sts/dist-cjs/index.js:476:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/core/dist-es/middleware-http-signing/httpSigningMiddleware.js:18:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38)
    at <anonymous> (/root/.serverless/releases/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22)
    at resolveAccountId (/root/.serverless/releases/4.4.19/sf-core/src/lib/resolvers/providers/aws/aws.js:169:34)
    at getAwsCredentialProvider (/root/.serverless/releases/4.4.19/sf-core/src/utils/credentials/index.js:40:20)
✖ IncompleteSignature: Invalid key=value pair (missing equal-sign) in Authorization header (hashed with SHA-256 and encoded with Base64): 'XBN9CqnPB+Nko16q0x3O5xCOzbW5HP+hqlII3xiHotM='.
    at throwDefaultError (/root/.serverless/releases/node_modules/@smithy/smithy-client/dist-cjs/index.js:846:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/smithy-client/dist-cjs/index.js:855:5)
    at de_CommandError (/root/.serverless/releases/node_modules/@aws-sdk/client-sts/dist-cjs/index.js:476:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/core/dist-es/middleware-http-signing/httpSigningMiddleware.js:18:20)
    at <anonymous> (/root/.serverless/releases/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38)
    at <anonymous> (/root/.serverless/releases/node_modules/@aws-sdk/client-sts/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22)
    at resolveAccountId (/root/.serverless/releases/4.4.19/sf-core/src/lib/resolvers/providers/aws/aws.js:169:34)
    at getAwsCredentialProvider (/root/.serverless/releases/4.4.19/sf-core/src/utils/credentials/index.js:40:20)
For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/

```

### Context

<img width="1001" alt="Image" src="https://github.com/user-attachments/assets/d2f4b9db-379b-4583-9d43-683116e7bd7a" />
