### ISSUE TITLE
Serverless v4 Variable Resolution Interprets CloudWatch Dynamic Expression Syntax ${PROP(...)} as a Variable

### ISSUE THREAD

**Issue by trend-bill-battushig** [serverless/serverless#13015]
### Description:

When packaging a CloudWatch Dashboard JSON that contains metrics label using the CloudWatch dynamic expression syntax (e.g., ${PROP("Dim.InstanceID")}), the Serverless Framework mistakenly tries to resolve the expression as a Serverless variable. Since no provider named PROP exists, this leads to an error:

```
Error: Provider PROP is not supported
    at createResolverProvider (file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:13836)
    at #addResolverProvider (file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:29349)
    at #handleProviderNode (file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:29842)
    at file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:28364
    at processNodeAndHandleCompletion (file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:17190)
    at processNodeAndManagePromise (file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:17843)
    at file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:17660
    at Array.forEach (<anonymous>)
    at processSinks (file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:17615)
    at processGraphInParallel (file:///Users/billbattushig/.serverless/releases/4.6.0/package/dist/sf-core.js:925:17294)
```

This prevents deployment even though the intended usage is to pass the literal string to CloudWatch (where it is handled as a dynamic label).

### Expected Behavior:
Serverless should ignore or correctly escape CloudWatch’s ${PROP(...)} syntax so that the final deployed CloudFormation template passes the literal string ${PROP("Dim.InstanceID")} to CloudWatch without attempting to resolve it as a Serverless variable.

### Actual Behavior:
Serverless scans the dashboard JSON for variable patterns (${...}) and tries to resolve ${PROP("Dim.InstanceID")}. Since there is no provider for PROP, the packaging process fails with an error.

### Reproduction Steps:
Create a file named `demoDashboard.json`:
```
{
    "widgets": [
      {
        "type": "metric",
        "properties": {
          "metrics": [
            [
              {
                "expression": "REMOVE_EMPTY(SEARCH('{AWS/WAFV2,Region,Rule,WebACL} MetricName=\"AllowedRequests\"', 'Average', 300))",
                "label": "${PROP(\"Dim.InstanceID\")} MyMetric",
                "id": "e1",
                "period": 300,
                "region": "us-east-2"
              }
            ]
          ]
        }
      }
    ]
  }
``` 

Create a file named `demo.js`:
```
const fs = require("fs");
const createDashboard = async (resolveVariable) => {
  // Read the dashboard template from a JSON file.
  // (Assume the file is located at the root of your project.)
  const dashboardTemplate = fs.readFileSync("./demoDashboard.json", "utf8");
  const dashboardJson = JSON.parse(dashboardTemplate);
  // The dashboardJson contains a metric label with the problematic expression.
  // When Serverless packages this, it will try to resolve ${PROP("Dim.InstanceID")}.
  return {
    Resources: {
      MyDashboard: {
        Type: "AWS::CloudWatch::Dashboard",
        Properties: {
          DashboardName: "MyTestDashboard",
          DashboardBody: JSON.stringify(dashboardJson)
        }
      }
    }
  };
};
exports.createDashboard = createDashboard;
```

In `Serverless.yml` file:

```
# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: billtrendmicro
# "service" is the name of this project. This will also be added to your AWS resource names.
service: test-variable-resolution

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'} # Use stage given in --stage or default to dev
  region: ${opt:region}

custom:
  configFileNameStage:
    dev: config.dev.yaml
    default: config.default.yaml
  stageConfigFileName: ${self:custom.configFileNameStage.${self:provider.stage},self:custom.configFileNameStage.dev}
  stageConfig: ${file(${self:custom.stageConfigFileName})}
  defaultConfig: ${file(config.default.yaml)}

  test1: ${self:custom.stageConfig.test.${self:provider.region}, self:custom.defaultConfig.test}

functions:
  hello:
    handler: handler.hello
    name: ${file(test.js):testResolution}

resources:
  - Resources:
    - ${file(demo.js):createDashboard}
```

### Environment

`"serverless": "^4.6.0"`

Thank you for looking into this! If you need any more details or want me to test any potential fixes, please let me know.

**Comment by zhil3** [comment]
Hi team, 
We are suffering from the similar issue. 

What we wanna implement is to keep the string as `arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/cmd/dsagent/${!iot:ClientId}/resp/*` without serverless to resolve `${!iot:ClientId}` during the deploy, but let the CloudFormation to resolve it. 

Before with serverless V3, we could use  `variableSyntax` to customize the serverless syntax that let it separate from CloudFormation's format. But this is no longer supported in serverless v4.

Any suggestions and help will be appreciated!

**Comment by czubocha** [comment]
Hey @zhil3, thanks for reporting the `iot` case. We'll update the logic to ignore it so CloudFormation can resolve the variable instead of Serverless Variables.

@trend-bill-battushig @zhil3 This fix will be included in the next release.

**Comment by czubocha** [comment]
Hey @zhil3 @trend-bill-battushig, the fix for this has been released in [v4.6.3](https://github.com/serverless/serverless/releases/tag/v4.6.3). Let us know if this resolves the issue for you!

**Comment by zhil3** [comment]
Hi @czubocha , thank you for putting such quick fix. 
Tried with the latest version v4.6.3, but still see the error....
The usage from my serverless.yml file is
```
 - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/$aws/things/${!iot:ClientId}/shadow/update
```
The issue I see right now is below
![Image](https://github.com/user-attachments/assets/0b23e2cb-41d3-4d52-a3f6-eb7aae9d25e5)

Is there a specific format needs to be followed with the fix?

**Comment by czubocha** [comment]
@zhil3 The official [AWS format for IoT policy variables](https://docs.aws.amazon.com/iot/latest/developerguide/basic-policy-variables.html) is `${iot:ClientId}` so you can remove the extra `!` before `iot`, and it should work correctly.

**Comment by zhil3** [comment]
Thank you for the info @czubocha !
Now the serverless.yml is like below
```
arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/$aws/things/${iot:ClientId}/shadow/update
```
And new issue comes up
```
 | customIoTPolicy | UPDATE_FAILED | Received response status [FAILED] from custom resource. Message returned: An error occurred (MalformedPolicyException) when calling the CreatePolicy operation: Policy document is Malformed: Unsupported iot variables [resource:!iot:ClientId, resource:!iot:Connection.Thing.Attributes[tenantGuid]] in policy document (RequestId: fb06d336-6b39-4529-abae-8cb6805e5d3f)
```
This is to setup a IoT Policy, And according to [Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html), ${!} is a standard Fn::Sub substitutes variables in an input string, which I am trying to do so. 

![Image](https://github.com/user-attachments/assets/488eceb6-fe67-4dae-bf0e-6cba147cd473)

**Comment by czubocha** [comment]
Let me clarify: Do you still have `${!iot:XXX}` in your IoT Policy? Have you tried removing the `!` from there as well? Or does CloudFormation throw an error when using `${iot:XXX}` inside `Sub` without the `!`?

**Comment by zhil3** [comment]
Hi @czubocha ,
I removed the `!` from the yaml file with using !Sub function. So currently my yaml file is like below 
```
Resource:
   - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/$aws/things/${iot:ClientId}/shadow/update
```
But got the issue of `MalformedPolicyException` from AWS side.

**Comment by czubocha** [comment]
In the error message, I see `resource:!iot:Connection.Thing.Attributes[tenantGuid]`, but it's not present in the snippet you provided:
```
Resource:
   - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/$aws/things/${iot:ClientId}/shadow/update
 ```
I believe the `MalformedPolicyException` is caused by another part of your configuration. Could you check if `${!iot:Connection.Thing.Attributes[tenantGuid]}` is used elsewhere?

**Comment by zhil3** [comment]
Yes, it is like 
```
Resource:
       - !Sub arn:${AWS::Partition}:iot:${AWS::Region}:${AWS::AccountId}:topic/cmd/dstenant/${iot:Connection.Thing.Attributes[tenantGuid]}/req/*
```

**Comment by trend-bill-battushig** [comment]
Hello @czubocha ,

Thank you for the fix for "PROP" issue. However, I started seeing more issues like:
`${!...}`
syntax conflict in an SSM document 

**Broken template that causes YAML error**:
```
Resources:
  ReproduceSSMSyntaxIssue:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        mainSteps:
        - action: "aws:runShellScript"
          name: "ReproduceIssue"
          inputs:
            runCommand:
            - "#!/bin/bash"
            - "echo \"Script path: ${!BASH_SOURCE[0]}\""  # <-- Problematic unescaped syntax
      DocumentType: Command

```
**Workaround:**
`"echo \"Script path: $${!BASH_SOURCE[0]}\""  # <-- Escaped with $$`
The ${!...} syntax is valid in Bash but conflicts with CloudFormation's intrinsic function syntax.

**Broken template that causes YAML error**:
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        parameters:
          SourceInfo:
            default: !s3_url/https "my-bucket/path"  # <-- Invalid syntax
  ...
```
**Workaround:**
`SourceInfo:
          default: "s3://${SoftwareBucket}/path"  <-- Valid reference`

**Comment by czubocha** [comment]
Hey, since version [v4.7.0](https://github.com/serverless/serverless/releases/tag/v4.7.0), Serverless Variables ignore placeholders if they have an exclamation point at the beginning `${!...}` to allow using literal values in CloudFormation's `Fn::Sub`. That should resolve any outstanding issues. Let me know if you're still experiencing any.

**Comment by trend-bill-battushig** [comment]
Hello @czubocha,

Thank you for fixing the above issue. However, I started seeing more issues like the following:

**Context**

- The SSM document contains a valid S3 HTTPS URL that works when executed directly in AWS. Serverless Framework v3 allowed this pattern as it didn't strictly validate parameter combinations. The new v4 seems to enforce strict validation of SourceType/SourceInfo.
- The error occurs during CloudFormation template resolution in Serverless Framework v4. It fails at resource validation phase before deployment. The SSM document itself is technically valid in AWS, but fails framework validation.
- When the CloudFormation template is parsed, ${s3_url/https:\\\\/\\\\//} becomes ${s3_url/https:\/\/}, which in Bash would be replacing "https://" with nothing. Serverless v4, attempts to resolve ${} everywhere, including inside strings and nested objects. I think the workaround would be avoid ${...} in SSM document content.

**Error Context**

```
Serverless Framework v4 Error:
Error: Provider s3_url/https is not supported
  at [Organization]ParameterResolver.resolve (/path/to/parser.js:123:45)
  at SSMDocument.validate (/path/to/ssm-resource.js:456:32)
...
```

**Example**

```
resources:
  Resources:
    ChefSSMDocument:
      Type: AWS::SSM::Document
      Properties:
        Content:
          schemaVersion: "2.2"
          description: "Failing document"
          parameters:
            SourceType:
              type: "String"
              default: "S3"
              allowedValues: ["S3"]
            SourceInfo:
              type: "StringMap"
              default:
                path: "https://...." # HTTPS format
          mainSteps:
            - action: "aws:downloadContent"
              inputs:
                SourceType: "{{ SourceType }}"
                SourceInfo: "{{ SourceInfo }}"
        DocumentFormat: YAML
        DocumentType: Command

    ValidS3Doc:
      Type: AWS::SSM::Document 
      Properties:
        Content:
          schemaVersion: "2.2"
          parameters:
            SourceType:
              type: "String"
              default: "S3"
            SourceInfo:
              type: "StringMap"
              default:
                path: "s3://valid-bucket/valid-path" # S3 URI format
          mainSteps:
            - action: "aws:downloadContent"
              inputs:
                SourceType: "{{ SourceType }}"
                SourceInfo: "{{ SourceInfo }}"
        DocumentFormat: YAML
        DocumentType: Command
```
