### ISSUE TITLE
[AWS Lambda] Support provisioned pollers configuration for Kafka EventSourceMapping

### ISSUE THREAD

**Issue by sra17** [serverless/serverless#13024]
### Is there an existing issue for this?

- [x] I have searched existing issues, it hasn't been reported yet

### Use case description

Aws announced provisioned mode for their EventSourceMapping with MSK and Self-managed Kafka in Nov. 2024. This feature allows users to optimize the throughput of Kafka ESM by provisioning event polling resources that remain ready to handle sudden spikes in traffic. Read more here - https://aws.amazon.com/about-aws/whats-new/2024/11/aws-lambda-provisioned-mode-kafka-esms/

This post highlights the performance improvements with the provisioned mode. https://aws.amazon.com/blogs/compute/introducing-provisioned-mode-for-kafka-event-source-mappings-with-aws-lambda/

Serverless frameworks is missing the support for provisioned poller configuration on Aws Lambda event source mapping trigger. 

### Proposed solution (optional)

```
functions:
  compute:
    handler: handler.compute
    events:
      - kafka:
          accessConfigurations:
            saslScram512Auth: arn:aws:secretsmanager:us-east-1:01234567890:secret:MyBrokerSecretName
          topic: MySelfManagedKafkaTopic
          bootstrapServers:
            - abc3.xyz.com:9092
            - abc2.xyz.com:9092
          batchSize: 1000
          maximumBatchingWindow: 30
          startingPosition: LATEST
          provisionedPollerConfig:
            minimumPollers: 4
            maximumPollers: 100
```

**Comment by credpath-seek** [comment]
+1 this would be nice to have

**Comment by czubocha** [comment]
Released in [Serverless Framework 4.42.0](https://github.com/serverless/serverless/releases/tag/sf-core%404.42.0) via #13835. `provisionedPollerConfig` is supported on `kafka`, `msk`, and `sqs` events in exactly the shape you proposed:

```yaml
events:
  - kafka:
      # ...
      provisionedPollerConfig:
        minimumPollers: 4
        maximumPollers: 100
```

`provisionedPollerConfig` and `maximumConcurrency` are mutually exclusive scaling modes, and the Framework validates that only one is set. Docs: [Kafka provisioned mode](https://www.serverless.com/framework/docs/providers/aws/events/kafka#provisioned-mode), [MSK](https://www.serverless.com/framework/docs/providers/aws/events/msk), [SQS provisioned mode](https://www.serverless.com/framework/docs/providers/aws/events/sqs#provisioned-mode).
