### ISSUE TITLE
Lambda EventBridge SourceArn formed incorrectly if default eventBus is explicity provided

### ISSUE THREAD

**Issue by fabiosenracorrea** [serverless/serverless#13038]
### Issue description

Pretty much the tittle.

The ARN of a EventBridge rule only has the `/EVENT_BUS_NAME` before the rule name if its not the `default` event bus every AWS account have.

While the current code does account for that if the eventBus is not specified, if you pass in `eventBus: default` it gets incorrectly created as

 `arn:${partition}:events:${region}:${accountId}:rule/${eventBusName}/${ruleName}`

instead of

 `arn:${partition}:events:${region}:${accountId}:rule/${ruleName}`

Simple test:

```yml
  BuildFinishedSlackNotification:
    handler: test.handler
    events:
      - eventBridge:
          name: test-rule-name
          eventBus: default # <================
```
