### ISSUE TITLE
serverless remove via serverless-compose failed to resolve variable * with resolver 'ssm' and provider 'default-aws-credential-resolver':

### ISSUE THREAD

**Issue by ecv-jgreventar** [serverless/serverless#13041]
### Issue description

**serverless deploy** works fine but when executing **serverless remove** it cant resolve ssm parameters properly.

### Context

serverless-compose.yml

```
Summary Report -----------------
# Service Overview
- Serverless Framework Version: 4.9.0
- Service Config File: serverless-compose.yml

## Service Path
/x/x/x/x/x/serff-typescript/serverless-compose.yml

## Command
remove --region us-east-1,--stage sandbox,--verbose true

## Service Config
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: xxx
locals:
  project: xxx
  environment: ${opt:stage, 'sandbox'}
  region: ${opt:region, 'us-east-1'}
  ssmPrefix: ${self:locals.project}/${self:locals.environment}
services:
  test-service:
    path: test-service
    params:
      service: test-service
      org: ${self:org}
      project: ${self:locals.project}
      environment: ${self:locals.environment}
      region: ${self:locals.region}
      ssmPrefix: ${self:locals.ssmPrefix}
  test-service-2:
    path: test-service-2
    params:
      service: test-service-2
      org: ${self:org}
      project: ${self:locals.project}
      environment: ${self:locals.environment}
      region: ${self:locals.region}
      ssmPrefix: ${self:locals.ssmPrefix}
```
test-service/serverless.yml

```
provider:
  name: aws
  deploymentMethod: direct
  region: ${param:region}
  stage: ${param:environment}
  logRetentionInDays: 180
  memorySize: 256
  timeout: 29
  runtime: nodejs20.x
  versionFunctions: false
  # Attach defined layers here
  layers:
    # AWS Lambda Powertool Layer
    - arn:aws:lambda:${param:region}:094274105915:layer:AWSLambdaPowertoolsTypeScriptV2:22
  vpc:
    securityGroupIds:
      - ${ssm:/${param:ssmPrefix}/lambda/sg}
    subnetIds:
      - ${ssm:/${param:ssmPrefix}/private/subnet/1}
      - ${ssm:/${param:ssmPrefix}/private/subnet/2}
  iam:
    role:
      name: ${self:service}-${param:environment}-role
      statements:
        # Define proper policies the IAM role needs
        - Effect: Allow
          Action: '*'
          Resource: '*'
  stackTags:
    project: ${param:project}
    service: ${param:service}-${param:version, '1'}
  tracing:
    lambda: true
  environment:
    PROJECT_NAME: ${param:project}
    SERVICE_NAME: ${param:service}
    ENVIRONMENT: ${param:environment}
    # DEFINE USABLE SSM RESOURCES HERE
    PROJECT_BACKEND_S3_PRIVATE_BUCKET: ${ssm:/${param:ssmPrefix}/s3/private-bucket}
    PROJECT_MAIN_BUS: ${ssm:/${param:ssmPrefix}/event-bridge/main/bus/arn}
    COGNITO_ADMIN_USER_POOL_ARN: ${ssm:/${param:ssmPrefix}/cognito/admin-user-pool/arn}
    # **If you are using rds uncomment these lines
    RDS_HOST: ${ssm:/${param:ssmPrefix}/rds/host}
    RDS_DATABASE: ${ssm:/${param:ssmPrefix}/rds/db/name}
    RDS_PORT: ${ssm:/${param:ssmPrefix}/rds/port}
    RDS_SECRET: ${ssm:/${param:ssmPrefix}/rds/secret/arn}
```

![Image](https://github.com/user-attachments/assets/7366d511-45f5-4020-9737-b27f8897eb21)

**Comment by czubocha** [comment]
Hey @ecv-jgreventar, thanks for reporting this. We'll look into this behavior.

**Comment by czubocha** [comment]
Hey @ecv-jgreventar, we’ll push the fix in the next release. Thanks again for reporting this!

By the way, you can simplify your setup by defining global params at the `stages` block, in your Compose file, instead of duplicating them in each service ([docs](https://www.serverless.com/framework/docs/guides/parameters#stage-parameters)). This approach also avoids the issue with the `remove` command, even without the upcoming fix. Here’s an example:

```
org: xxx

stages:
  default:
    params:
      project: xxx
      environment: ${opt:stage, 'sandbox'}
      ssmPrefix: ${param:project}/${param:environment}

services:
  service-a:
    path: service-a
  service-b:
    path: service-b
    params:
      apiUrl: ${service-a.apiUrl}
```

With this setup, `project`, `environment`, and `ssmPrefix` are automatically available in all services. You can reference them using the `param` resolver as usual:

service-b/serverless.yml:
```
service: compose-b

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    environment:
      apiUrl: ${param:apiUrl}
      ssmValue: ${ssm:/${param:ssmPrefix}/private/subnet/1}
```
