### ISSUE TITLE
The need to avoid ${...} in SSM document content

### ISSUE THREAD

**Issue by trend-bill-battushig** [serverless/serverless#13040]
> Hello @czubocha,
> 
> Thank you for fixing the above issue. However, I started seeing more issues like the following:
> 
> **Context**
> 
> - The SSM document contains a valid S3 HTTPS URL that works when executed directly in AWS. Serverless Framework v3 allowed this pattern as it didn't strictly validate parameter combinations. The new v4 seems to enforce strict validation of SourceType/SourceInfo.
> - The error occurs during CloudFormation template resolution in Serverless Framework v4. It fails at resource validation phase before deployment. The SSM document itself is technically valid in AWS, but fails framework validation.
> - When the CloudFormation template is parsed, ${s3_url/https:\\\\/\\\\//} becomes ${s3_url/https:\/\/}, which in Bash would be replacing "https://" with nothing. Serverless v4, attempts to resolve ${} everywhere, including inside strings and nested objects. I think the workaround would be avoid ${...} in SSM document content.
> 
> **Error Context**
> 
> ```
> Serverless Framework v4 Error:
> Error: Provider s3_url/https is not supported
>   at [Organization]ParameterResolver.resolve (/path/to/parser.js:123:45)
>   at SSMDocument.validate (/path/to/ssm-resource.js:456:32)
> ...
> ```
> 
> **Example**
> 
> ```
> resources:
>   Resources:
>     FailingSSMDocument:
>       Type: AWS::SSM::Document
>       Properties:
>         Content:
>           schemaVersion: "2.2"
>           description: "Failing document"
>           parameters:
>             SourceType:
>               type: "String"
>               default: "S3"
>               allowedValues: ["S3"]
>             SourceInfo:
>               type: "StringMap"
>               default:
>                 path: "https://...." # HTTPS format
>           mainSteps:
>             - action: "aws:downloadContent"
>               inputs:
>                 SourceType: "{{ SourceType }}"
>                 SourceInfo: "{{ SourceInfo }}"
>         DocumentFormat: YAML
>         DocumentType: Command
> 
>     ValidS3Doc:
>       Type: AWS::SSM::Document 
>       Properties:
>         Content:
>           schemaVersion: "2.2"
>           parameters:
>             SourceType:
>               type: "String"
>               default: "S3"
>             SourceInfo:
>               type: "StringMap"
>               default:
>                 path: "s3://valid-bucket/valid-path" # S3 URI format
>           mainSteps:
>             - action: "aws:downloadContent"
>               inputs:
>                 SourceType: "{{ SourceType }}"
>                 SourceInfo: "{{ SourceInfo }}"
>         DocumentFormat: YAML
>         DocumentType: Command
> ```  

 _Originally posted by @trend-bill-battushig in [#13015](https://github.com/serverless/serverless/issues/13015#issuecomment-2704282581)_

**Comment by trend-bill-battushig** [comment]
Hello @czubocha ,
Would you be able to take a look at this issue? This has been a blocker for a month now. Thank you very much for your time and help!

**Comment by czubocha** [comment]
Hey @trend-bill-battushig, sorry it took us a while to get back to you. We're looking into this.

**Comment by czubocha** [comment]
Hey @trend-bill-battushig, thanks for the detailed report - I'm trying to fully understand the issue here.

From what I gather, you're using `${}` syntax within your `AWS::SSM::Document` resource, and it's being mistakenly interpreted by the Serverless Framework's variable system. However, I didn't see a direct example of `${}` in the content you shared. Could you provide a minimal, complete example that reproduces the issue on your side?

Also, just to confirm - are you using `${}` inside something like an `aws:runShellScript` step?

If your goal is to include a literal `${s3_url/https://}` string without it being resolved by the framework, one workaround would be to store that string in an SSM parameter and then reference it using `{{ssm:parameter-name}}` inside your document content. Here's a reference from the AWS docs: https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-syntax-data-elements-parameters.html#top-level

Let us know, and we'll be happy to dig deeper!

**Comment by trend-bill-battushig** [comment]
### Issue Summary

We are encountering an error when deploying an AWS::SSM::Document containing bash scripts with Serverless Framework v4. The framework is incorrectly interpreting bash parameter expansion/substitution syntax (like `${!variable}` and `${variable/pattern/replacement}`) as Serverless variables, causing deployment failures.

### Technical Details

Our SSM document contains bash scripts that use standard parameter expansion syntax for string manipulation, including:

- Variable indirection: `${!variable}`
- String substitution: `${variable/pattern/replacement}`
- String length calculation: `${#variable}`
- Substring extraction: `${variable:offset:length}`


These are valid bash constructs, but Serverless Framework v4 appears to be incorrectly parsing them as Serverless variable references.

For example, a line like `s3_url_without_protocol=$(echo "${!s3_url/https:\/\//}")` in our bash script causes the error because Serverless tries to interpret `${!s3_url/https` as a variable reference with provider `s3_url/https`

### Minimal Reproducible Example

```
service: ssm-document-example
frameworkVersion: '4.9.1'

provider:
  name: aws
  region: us-east-1

resources:
  Resources:
    TestSSMDocument:
      Type: AWS::SSM::Document
      Properties:
        DocumentType: Command
        Content:
          schemaVersion: "2.2"
          description: "Test document with bash parameter expansion"
          mainSteps:
            - action: "aws:runShellScript"
              name: "runScript"
              inputs:
                runCommand:
                  - "#!/bin/bash"
                  - "# Variable declaration"
                  - "s3_url=\"https://example.com/path\""
                  - "# These bash parameter expansions trigger the error:"
                  - "# String substitution"
                  - "s3_url_without_protocol=$(echo \"${s3_url/https:\/\//}\")"
                  - "# length calculation"
                  - "url_length=${#s3_url}"
                  - "# Variable indirection"
                  - "var_name=\"s3_url\"
                  - "var_value=${!var_name}"
```

### Expected Behavior

The Serverless Framework should treat the content of the SSM document as a literal string and not attempt to interpret bash parameter expansion syntax as Serverless variables. This content should be passes as is to CloudFormation.

Thank you for your help in resolving this issue.
