### ISSUE TITLE
v4 compose breaks plugins executing in wrong working directory

### ISSUE THREAD

**Issue by phmasek** [serverless/serverless#13048]
### Issue description

In Serverless v3, when using the serverless-compose plugin, each service executed within its own working directory. This allowed plugins like [serverless-plugin-scripts](https://github.com/mvila/serverless-plugin-scripts) to run bash commands defined in the `package.json` of the respective service in a monorepo setup.

In Serverless v4, the execution context has shifted to the root folder where `serverless-compose.yml` is located. This breaks plugins that depend on local execution within each service’s folder.

### Context

# Service Overview
- Serverless Framework Version: 4.10.1
- Service Config File: serverless-compose.yml
- Command: deploy --stage dev

## Service Path
\<redacted\>/serverless-compose.yml

## Service Config
```
services:
  service1:
    path: services/service1
  service2:
    path: services/service2
  service3:
    path: services/service3
  service4:
    path: services/service4
  service5:
    path: services/service5
  documentation:
    path: services/documentation
    dependsOn:
     - service1
     - service2
     - service3
     - service4
     - service5
```
