### ISSUE TITLE
`deploy` does not update `Runtime.Handler`

### ISSUE THREAD

**Issue by aashutoshrathi** [serverless/serverless#13055]
### Issue description

In case where, the lambda's Runtime Handler is updated from the AWS Console by someone, when redeploying the function using `sls deploy` it doesn't update the Runtime.Handler to the handler configured in serverless.yml file.

Is this expected behaviour? If so, what's the way to always update handler with deployment too? 

Here's my serverless file
```yml
service: schedule-consumer

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    HANDLER_URL: ${env:HANDLER_URL}
    API_KEY: ${env:API_KEY}

functions:
  consumer:
    handler: handler.handleMessage
```
