### ISSUE TITLE
Error in deploy using CLI sls deploy (v4)

### ISSUE THREAD

**Issue by DevJoaoLopes** [serverless/serverless#13053]
### Issue description

I have an application made in NestJs (default) and when executing the sls deploy command I am getting the following error:

![Image](https://github.com/user-attachments/assets/ca4a8b26-2d00-44b4-b14e-708fb2ef68bb)

serverless.yml 

```yml
service: api-rest-aws-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_ENV: production

functions:
  api:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
```

file `main.ts` following [guide](https://docs.nestjs.com/faq/serverless#example-integration)

```ts
import { NestFactory } from '@nestjs/core';
import serverlessExpress from '@codegenie/serverless-express';
import { Callback, Context, Handler } from 'aws-lambda';
import { AppModule } from './app.module';

let server: Handler;

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.init();

  const expressApp = app.getHttpAdapter().getInstance();
  return serverlessExpress({ app: expressApp });
  // await app.listen(process.env.PORT ?? 3000);
}

export const handler: Handler = async (
  event: any,
  context: Context,
  callback: Callback,
) => {
  server = server ?? (await bootstrap());
  return server(event, context, callback);
};
```

### Context

# Service Overview
- Serverless Framework Version: 4.11.1
- Service Config File: serverless.yml
- Service Name: api-rest-aws-lambda
- Service Runtime: nodejs20.x
- Service Region: us-east-1
- Command: login

## Service Path
/home/joaolopes/Desenvolvimento/api-rest-aws-lambda/serverless.yml

## Service Config
```
service: api-rest-aws-lambda
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_ENV: production
    
functions:
  api:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
```

**Comment by czubocha** [comment]
Hey @DevJoaoLopes 

The error `AWS credentials missing or invalid` means the Serverless Framework couldn't find valid AWS credentials on your machine.

Here’s how to resolve it:

1. **Set up credentials**  
   Run:
   ```bash
   aws configure
   ```
   This will configure your default AWS profile.

2. **Using a custom profile?**  
   Be sure to specify it in your `serverless.yml` or in `--aws-profile` CLI option
   ```yaml
   provider:
     name: aws
     profile: your-profile-name
   ```

3. **Using temporary credentials (e.g. SSO or `credential_process`)?**  
   Ensure they're still valid and properly configured.

More on configuring credentials:
- AWS CLI authentication guide: https://docs.aws.amazon.com/cli/v1/userguide/cli-chap-authentication.html
- Serverless Framework docs: https://www.serverless.com/framework/docs/providers/aws/guide/credentials
