### ISSUE TITLE
v4: Loading stages from YAML file doesn't work

### ISSUE THREAD

**Issue by andrewchernow** [serverless/serverless#13060]
### Issue description

I am trying to load the contents of "stages" from a YAML file . When I put the contents directly into the serverless.yml file, everything works fine; I am just doing a `sls print` command. When I load from a YAML file via `${file()}` I get the below error:

```
Error: Cannot resolve '${param:func_dir}' variable at 'functions.example-api.handler'. 
No value is available for this variable, and no default value was provided. Please check 
your variable definitions or provide a default value.
```

The YAML stages file looks like this 

```yaml
default:
    params:
        func_dir: src/functions
        artifact_dir: ./.artifacts
```

From the serverless.yml file, I reference the above file like this:

```yaml
service: example
stages: ${file(../../serverless/stages.yml)}
functions:
    example-api:
        handler: ${param:func_dir}/api/entry.handler
```

If I do this in serverless.yml, it works

```yaml
service: example
stages: 
    default:
        params:
            func_dir: src/functions
            artifact_dir: ./.artifacts
```

### Context

Serverless Framework Version: 4.14.1
System: darwin-arm64 (M4)

Full serviceless.yml file:
```yaml
service: example
frameworkVersion: ^4.14.1
configValidationMode: error
deprecationNotificationMode: warn:summary
stages: ${file(../../serverless/stages.yml)}
provider:
    name: aws
    runtime: nodejs22.x
    architecture: arm64
package:
    individually: true
build:
    esbuild: false
functions:
    example-api:
        handler: ${param:func_dir}/api/entry.handler
        name: example-api
        package:
            artifact: ${param:artifact_dir}/api.zip
        events:
            -   httpApi:
                    method: GET
                    path: /example
```

I am just now switching to v4. In v3, stages was params. That worked fine, I can load params via `file()` in v3. In v4, I have to use stages because I am using `resolvers`.

**Comment by czubocha** [comment]
Hey @andrewchernow, thanks for the detailed report and context.

At the moment, extracting the entire `stages` block into a separate file via `${file()}` is not supported. However, you *can* use `${file()}` to load just the `params` block within a specific stage. For example:

```yaml
service: example

stages:
  default:
    params: ${file(../../serverless/params.yml)}
```
