### ISSUE TITLE
V4 - New version is breaking plugin serverless-auto-swagger

### ISSUE THREAD

**Issue by phmasek** [serverless/serverless#13066]
### Issue description

After upgrading to V4 the plugin does not include the generated handlers in the uploaded artifacts to the lambda functions as it did in previous version.

### Context

Serverless ϟ Support
This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.
Summary Report -----------------
# Service Overview
- Serverless Framework Version: 4.14.1
- Service Config File: serverless-compose.yml
- Command: documentation deploy

## Service Path
/<<redacted>>/serverless-compose.yml

## Error Message
An error occurred: IamRoleLambdaExecution - Resource handler returned message: "Policy statement must contain resources. (Service: Iam, Status Code: 400, Request ID: 4851ceea-8968-4758-902b-c2f8af1315c9) (SDK Attempt Count: 1)" (RequestToken: bf3e033a-acd1-31e8-d190-990b43f7aa5a, HandlerErrorCode: InvalidRequest).

## Error Stacktrace
```
at file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:904:828
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async AwsDeploy.update (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:904:25270)
at async aws:deploy:deploy:updateStack (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:915:7906)
at async PluginManager.runHooks (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:1106:9549)
at async PluginManager.invoke (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:1106:10318)
at async PluginManager.spawn (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:1106:10677)
at async PluginManager.runHooks (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:1106:9549)
at async PluginManager.invoke (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:1106:10318)
at async PluginManager.run (file:///<<redacted>>/.serverless/releases/4.14.1/package/dist/sf-core.js:1106:11047)
```

## Error Code
AWS_CLOUD_FORMATION_UPDATE_STACK_INTERNAL_I_A_M_ROLE_UPDATE_FAILED

## Service Config
```
services:
  programme:
    path: services/api/programme
  course:
    path: services/api/course
  token:
    path: services/api/token
  cart:
    path: services/api/cart
  customer:
    path: services/api/customer
  documentation:
    path: services/api/documentation
    dependsOn:
     - cart
     - programme
     - customer
     - course
     - token
```

Above is a summary report of your last Serverless Framework command.
Use it to debug with AI (e.g. ChatGPT) or report a new Github Issue: https://slss.io/issue

✨  Done in 4.60s.
