### ISSUE TITLE
Serverless doesn't bundle node_modules when a pnpm-workspace.yaml file exists

### ISSUE THREAD

**Issue by AaronMoat** [serverless/serverless#13078]
### Issue description

A weird one, the presence of pnpm-workspace.yaml (even if it's empty) means no node_modules get copied. What could be going on here? 

```
$ pnpm serverless package --config=serverless.yml --verbose

Packaging "my-serverless-app" for stage "dev" (ap-southeast-2)
Auto instrumenting functions with Datadog
Skipping adding Lambda Library Layers, make sure you are packaging them yourself
Adding Datadog Lambda Extension Layer to functions
Adding Datadog Env Vars
Adding Plugin Version 5.92.0 tag
Adding source code integration
Skipping enabling source code integration because encrypted credentials through KMS/Secrets Manager is not supported for this integration. Please set either DATADOG_API_KEY in your environment, or set the apiKey parameter in Serverless.
✔ Service packaged (3s)
$ ls .serverless/build/node_modules
ls: .serverless/build/node_modules: No such file or directory
$ 
$ 
$ rm pnpm-workspace.yaml
$ 
$ pnpm serverless package --config=serverless.yml --verbose

Packaging "my-serverless-app" for stage "dev" (ap-southeast-2)
Auto instrumenting functions with Datadog
Skipping adding Lambda Library Layers, make sure you are packaging them yourself
Adding Datadog Lambda Extension Layer to functions
Adding Datadog Env Vars
Adding Plugin Version 5.92.0 tag
Adding source code integration
Skipping enabling source code integration because encrypted credentials through KMS/Secrets Manager is not supported for this integration. Please set either DATADOG_API_KEY in your environment, or set the apiKey parameter in Serverless.
✔ Service packaged (6s)
$ ls .serverless/build/node_modules
my-node-modules-here
```

### Context

Summary Report -----------------
# Service Overview
- Serverless Framework Version: 4.14.3
- Service Config File: serverless.yml
- Service Name: my-serverless-app
- Service Runtime: nodejs22.x
- Service Stage: dev
- Service Region: ap-southeast-2

## Service Path
/path-to-repo/serverless.yml

## Command
package --config serverless.yml,--verbose true

## Service Config
```
service: my-serverless-app
frameworkVersion: '4'
configValidationMode: error
params:
  default:
    datadogApiKeySecretArn: an-arn
  dev:
    isProduction: 'false'
    sourceTopicArn: an-arn
  prod:
    isProduction: 'true'
    sourceTopicArn: an-arn
custom:
  datadog:
    addLayers: false
    apiKeySecretArn: ${param:datadogApiKeySecretArn}
    enableDDLogs: false
    enableDDTracing: false
    enabled: true
    injectLogContext: false
    version: ${env:VERSION}
plugins:
  - serverless-plugin-datadog
provider:
  logRetentionInDays: 30
  name: aws
  region: ap-southeast-2
  runtime: nodejs22.x
  architecture: arm64
  versionFunctions: false
  stackName: ${self:service}
  stage: ${env:ENVIRONMENT}
  deploymentBucket:
    name: ${cf:infra-artefacts.BucketName}
  environment:
    # https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    # https://nodejs.org/api/cli.html#cli_node_options_options
    NODE_OPTIONS: --enable-source-maps
  iam:
    role:
      statements:
        - Action: secretsManager:GetSecretValue
          Effect: Allow
          Resource:
            - ${param:datadogApiKeySecretArn}-??????
        - Action: sqs:SendMessage*
          Effect: Allow
          Resource: !GetAtt DeadLetterQueue.Arn
build:
  esbuild:
    bundle: true
    minify: false
    sourcemap:
      type: linked
      # Whether to set the NODE_OPTIONS on functions to enable sourcemaps on Lambda
      setNodeOptions: true
    target: 'node22'
    define: { 'require.resolve': undefined }
    platform: 'node'
    buildConcurrency: 10
    packages: external
functions:
  MyApp:
    name: ${self:service}
    handler: src/app.handler
    memorySize: 128
    events:
      - sqs:
          arn: !GetAtt MessageQueue.Arn
          batchSize: 10
resources:
  Resources:
    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 1209600
        KmsDataKeyReusePeriodSeconds: 300
        QueueName: ${self:service}-dead-letters
    MessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 1209600
        KmsDataKeyReusePeriodSeconds: 300
        QueueName: ${self:service}-messages
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
          maxReceiveCount: 10
        VisibilityTimeout: 180
    MessageQueuePolicy: 
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action: sqs:SendMessage
              Condition:
                ArnEquals:
                  aws:SourceArn: ${param:sourceTopicArn}
              Effect: Allow
              Principal:
                AWS: '*'
              Resource: '*'
        Queues:
          - !Ref MessageQueue
    TopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: !GetAtt MessageQueue.Arn
        Protocol: sqs
        RawMessageDelivery: true
        Region: !Ref AWS::Region
        TopicArn: ${param:sourceTopicArn}
```
