### ISSUE TITLE
ImportModuleError with matplotlib

### ISSUE THREAD

**Issue by Enorio** [serverless/serverless#13081]
### Issue description

I have a lambda that uses matplotlib to create a graph. That lambda was with:
- python 3.7
- serverless 3.36.0
- matplotlib 3.3.4

It worked correctly and the matplotlib folder was in the lambda code.

Now I'm trying to upgrade the python to 3.10. The serverless version is the same, and the matplotlib version is 3.10.3.
The deploy works fine, but now the code does not have the matplotlib folder.

Is this somehow related to this [issue](https://github.com/serverless/serverless/issues/12342)

### Context

```yaml
service: foo
useDotenv: true

custom:
  pythonRequirements:
    usePipenv: false
    dockerizePip: true

provider:
  name: aws
  runtime: python3.10
  region: eu-west-1

functions:
  run:
    handler: main.run
    environment:
         ...
    timeout: 900

plugins:
  - serverless-better-credentials
  - serverless-python-requirements
```
