### ISSUE TITLE
[v4] Can't generate esbuild metafile using serverless esbuild

### ISSUE THREAD

**Issue by renanwilliam** [serverless/serverless#13080]
### Issue description

I need to analyze my bundle dependencies size using esbuild [metafile](https://esbuild.github.io/api/#metafile),  and it is not possible. 

### Context

Serverless ϟ Support
This generates a report from your last Serverless Framework command (including any errors) to use for Github Issues, debugging w/ AI, or creating a support ticket w/ Serverless Inc.
Summary Report -----------------
# Service Overview
- Serverless Framework Version: 4.14.4
- Service Config File: serverless.yml
- Service Name: th-platform-service
- Service Runtime: nodejs22.x
- Service Stage: dev
- Service Region: us-east-1
- Command: deploy

## Service Path
/Users/renan/Projetos/tunnelhub/tunnelhub-backend/platform-service/serverless.yml

## Service Config
```
service: th-platform-service
frameworkVersion: '4'
useDotenv: true
plugins:
  - serverless-plugin-lambda-insights
  - serverless-iam-roles-per-function
  - serverless-domain-manager
package:
  individually: true
provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 90
  deploymentMethod: direct
  tracing:
    apiGateway: true
    lambda: true
  stackTags:
    Product: TunnelHub
  iam:
    role:
      statements:
        - ${file(iam/CognitoRoleIAM.yml):CognitoRoleIAM}
        - ${file(iam/ApplicationTableIAM.yml):ApplicationTableIAM}
        - ${file(iam/XRayTracingIAM.yml):XRayTracingIAM}
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_OPTIONS: '--enable-source-maps'
    APPLICATION_TABLE_NAME: ${self:custom.ApplicationTable.name}
    SYSTEM_ADMIN_ROLE: 'SystemAdmin'
    SYSTEM_SUPPORT_ROLE: 'SystemUser'
    TENANT_ADMIN_ROLE: 'TenantAdmin'
    TENANT_USER_ROLE: 'TenantUser'
    FRONTEND_URL: ${self:custom.frontendUrl}
    TOP_LEVEL_DOMAIN: ${env:TOP_LEVEL_DOMAIN}
    API_GATEWAY_DOMAIN: ${env:API_GATEWAY_DOMAIN}
    S3_BUCKET_NAME: ${self:custom.GeneralS3Bucket.name}
    SLS_STAGE: ${self:provider.stage}
functions:
  createSequence:
    handler: src/handlers/sequences/createSequence.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /sequences
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getSequences:
    handler: src/handlers/sequences/getSequences.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /sequences
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getSequence:
    handler: src/handlers/sequences/getSequence.handler
    events:
      - http:
          method: GET
          path: /sequences/{sequenceName}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  updateSequence:
    handler: src/handlers/sequences/updateSequence.handler
    memorySize: 1024
    events:
      - http:
          method: PATCH
          path: /sequences/{sequenceName}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  deleteSequence:
    handler: src/handlers/sequences/deleteSequence.handler
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /sequences/{sequenceName}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  incrementSequence:
    handler: src/handlers/sequences/incrementSequence.handler
    memorySize: 1024
    events:
      - http:
          method: PUT
          path: /sequences/{sequenceName}/increment
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  createDataStore:
    handler: src/handlers/dataStores/createDataStore.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /dataStores
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getDataStores:
    handler: src/handlers/dataStores/getDataStores.handler
    events:
      - http:
          method: GET
          path: /dataStores
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getDataStore:
    handler: src/handlers/dataStores/getDataStore.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /dataStores/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  updateDataStore:
    handler: src/handlers/dataStores/updateDataStore.handler
    memorySize: 1024
    events:
      - http:
          method: PATCH
          path: /dataStores/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  deleteDataStore:
    handler: src/handlers/dataStores/deleteDataStore.handler
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /dataStores/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  batchDeleteDataStores:
    handler: src/handlers/dataStores/batchDeleteDataStores.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /dataStores/batch/delete
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  createDataStoreItem:
    handler: src/handlers/dataStores/createDataStoreItem.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /dataStores/{id}/items
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getDataStoreItems:
    handler: src/handlers/dataStores/getDataStoreItems.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          method: GET
          path: /dataStores/{id}/items
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getDataStoreItem:
    handler: src/handlers/dataStores/getDataStoreItem.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /dataStores/{id}/items/{itemId}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  updateDataStoreItem:
    handler: src/handlers/dataStores/updateDataStoreItem.handler
    memorySize: 1024
    events:
      - http:
          method: PATCH
          path: /dataStores/{id}/items/{itemId}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  deleteDataStoreItem:
    handler: src/handlers/dataStores/deleteDataStoreItem.handler
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /dataStores/{id}/items/{itemId}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  batchDeleteDataStoreItems:
    handler: src/handlers/dataStores/batchDeleteDataStoreItems.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /dataStores/{id}/items/batch/delete
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  batchFullLoadDataStoreItems:
    handler: src/handlers/dataStores/batchFullLoadDataStoreItems.handler
    memorySize: 1024
    timeout: 29
    events:
      - http:
          method: POST
          path: /dataStores/{id}/items/batch/full
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  initiateTempImageUpload:
    handler: src/handlers/initiateTempImageUpload.handler
    memorySize: 1024
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: ${self:custom.GeneralS3Bucket.arn}/tmp/*
    events:
      - http:
          method: POST
          path: events/{eventId}/photos/initiate-upload
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  createEnvironment:
    handler: src/handlers/environments/createEnvironment.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /environments
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getEnvironments:
    handler: src/handlers/environments/getEnvironments.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /environments
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getEnvironmentsAvailableToTransport:
    handler: src/handlers/environments/getEnvironmentsAvailableToTransport.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /environments/current/availableToTransport
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getEnvironment:
    handler: src/handlers/environments/getEnvironment.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /environments/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  updateEnvironment:
    handler: src/handlers/environments/updateEnvironment.handler
    memorySize: 1024
    events:
      - http:
          method: PATCH
          path: /environments/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  deleteEnvironment:
    handler: src/handlers/environments/deleteEnvironment.handler
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /environments/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  batchDeleteEnvironments:
    handler: src/handlers/environments/batchDeleteEnvironments.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /environments/batch/delete
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  createBackgroundProcessing:
    handler: src/handlers/backgroundProcessings/createBackgroundProcessing.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /backgroundProcessings
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getBackgroundProcessings:
    handler: src/handlers/backgroundProcessings/getBackgroundProcessings.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /backgroundProcessings
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  getBackgroundProcessing:
    handler: src/handlers/backgroundProcessings/getBackgroundProcessing.handler
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /backgroundProcessings/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  updateBackgroundProcessing:
    handler: src/handlers/backgroundProcessings/updateBackgroundProcessing.handler
    memorySize: 1024
    events:
      - http:
          method: PATCH
          path: /backgroundProcessings/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  deleteBackgroundProcessing:
    handler: src/handlers/backgroundProcessings/deleteBackgroundProcessing.handler
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /backgroundProcessings/{id}
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  batchDeleteBackgroundProcessings:
    handler: src/handlers/backgroundProcessings/batchDeleteBackgroundProcessings.handler
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /backgroundProcessings/batch/delete
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  authorizeGoogleSheet:
    handler: src/handlers/authorizeGoogleSheet.handler
    memorySize: 1024
    timeout: 20
    environment:
      GOOGLE_API_CLIENT_ID: ${env:GOOGLE_API_CLIENT_ID}
      GOOGLE_API_CLIENT_SECRET: ${env:GOOGLE_API_CLIENT_SECRET}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
      - Effect: Allow
        Action:
          - sqs:SendMessage
          - sqs:SendMessageBatch
        Resource: '*'
    events:
      - http:
          method: POST
          path: /oauth/authorizeGoogleSheet
          authorizer:
            arn: ${self:custom.idTokenAuthorizer}
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.Authorization
            identityValidationExpression: ".+"
  googleSheetCallback:
    handler: src/handlers/googleSheetCallback.handler
    memorySize: 1024
    environment:
      GOOGLE_API_CLIENT_ID: ${env:GOOGLE_API_CLIENT_ID}
      GOOGLE_API_CLIENT_SECRET: ${env:GOOGLE_API_CLIENT_SECRET}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
      - Effect: Allow
        Action:
          - sqs:SendMessage
          - sqs:SendMessageBatch
        Resource: '*'
    events:
      - http:
          method: GET
          path: /google-sheets/oauth/callback
  idTokenWebsocketAuthorizer:
    handler: src/handlers/websocketAuthorizer.handler
  userWebsocketRequests:
    handler: src/handlers/websocket.handler
    maximumRetryAttempts: 0
    events:
      - websocket:
          route: $connect
          authorizer:
            name: idTokenWebsocketAuthorizer
            identitySource:
              - 'route.request.querystring.Auth'
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource: arn:aws:lambda:${aws:region}:${aws:accountId}:function:th-integrations-service-${self:provider.stage}-analyzeExecutionLogsErrors
  datalakeExtractors:
    handler: src/handlers/datalake/extractors.handler
    timeout: 90
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: ${self:custom.GeneralS3Bucket.arn}/datalake/tables/*
  handleDynamoDBItemStream:
    handler: src/handlers/datalake/ddbStream.handler
    timeout: 90
    events:
      - stream:
          arn: ${self:custom.ApplicationTable.stream_arn}
          filterPatterns:
            - dynamodb:
                NewImage:
                  dynamoLogicalEntityName:
                    S:
                      - ENVIRONMENT
                      - DATASTORE
                      - SEQUENCE
            - dynamodb:
                OldImage:
                  dynamoLogicalEntityName:
                    S:
                      - ENVIRONMENT
                      - DATASTORE
                      - SEQUENCE
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: ${self:custom.GeneralS3Bucket.arn}/datalake/tables/*
  cleanupOldSftpFiles:
    handler: src/handlers/cleanupOldSftpFiles.handler
    timeout: 900
    events:
      - schedule: rate(7 days)
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
      - Effect: Allow
        Action:
          - s3:*
        Resource: ${self:custom.GeneralS3Bucket.arn}/private/ftps/*
  getLoginBackgrounds:
    handler: src/handlers/getLoginBackgrounds.handler
    events:
      - http:
          method: GET
          path: /loginBackgrounds
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateGroups}
      - ${file(iam/LambdaInsightsIAM.yml):LambdaInsightsIAMCreateLogStreams}
resources:
  - ${file(resources/glue-tables.yml)}
build:
  esbuild:
    buildConcurrency: 2
    sourcemap: true
    metafile: true
    exclude:
      - '@aws-sdk/**'
custom:
  lambdaInsights:
    defaultLambdaInsights: false
    lambdaInsightsVersion: 23
  frontendUrl: ${env:FRONTEND_URL}
  customDomain:
    rest:
      domainName: ${env:API_GATEWAY_DOMAIN}
      stage: ${self:provider.stage}
      basePath: 'platform-service'
      certificateName: ${env:API_GATEWAY_CERTIFICATE_NAME}
      createRoute53Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2
      apiType: rest
      autoDomain: true
    websocket:
      domainName: "ws.${env:TOP_LEVEL_DOMAIN}"
      stage: ${self:provider.stage}
      basePath: ''
      certificateName: ${env:API_GATEWAY_CERTIFICATE_NAME}
      createRoute53Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2
      autoDomain: true
  accessTokenAuthorizer: arn:aws:lambda:${aws:region}:${aws:accountId}:function:th-auth-service-${self:provider.stage}-accessTokenAuthorizer
  idTokenAuthorizer: arn:aws:lambda:${aws:region}:${aws:accountId}:function:th-auth-service-${self:provider.stage}-idTokenAuthorizer
  ApplicationTable:
    name: ${ssm:th-table-name}
    arn: ${ssm:th-table-arn}
    stream_arn: ${ssm:th-table-stream-arn}
  GeneralS3Bucket:
    arn: ${ssm:th-common_bucket-arn}
    name: ${ssm:th-common_bucket-name}
  GlueCatalogDatabase:
    name: ${ssm:th-glue-catalog-database-name}
    arn: ${ssm:th-glue-catalog-database-arn}
```
