### ISSUE TITLE
Final AWS serverless.yaml syntax

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1340]
### Initial AWS serverless.yaml
This is the file that will be generated on `serverless create --name myService --provider aws` 
```yml
service: myService
provider: aws
functions:
  hello:
    handler: handler.hello
```
It only contains the most essential data and all else are set as defaults the user could overwrite at the service level, or function level.

### Overwriting Defaults: Service Level
User could overwrite the assumed service defaults above like this:

```yml
service: myService
provider: aws
defaults:
  stage: beta
  region: us-west-2
  timeout: 3
  memory: 512
  include:
    - lib
    - functions
   exclude:
    - tmp
    - .git
functions:
  hello:
    handler: handler.hello
```

### Overwriting Defaults: Function Level
Or they can overwrite the defaults by specifying the properties at the function level.

```yml
service: myService
provider: aws
defaults:
  stage: beta
  region: us-west-2
functions:
  hello:
    handler: handler.hello
    timeout: 3
    memory: 512
    include:
      - lib
      - functions
     exclude:
      - tmp
      - .git
```

### Complete Example
Here's a complete example that combines both, as well as adding events. The main principle here is to add only what needs to be explicitly added to overwrite a default behavior.
```yml
service: myService
provider: aws
defaults:
  stage: beta
  region: us-west-2
  timeout: 6
  memory: 1024
  include:
    - lib
    - functions
   exclude:
    - tmp
    - .git
functions:
  hello: # function config is inherited from defaults above
    handler: handler.hello 
  user: # function config overwrite defaults above
    handler: handler.user
    timeout: 3
    memory: 512
    include:
      - lib
      - functions
     exclude:
      - tmp
      - .git
    events:
      - http: get users/list
      - http:
          method: post
          method: users/create
          cors: true
          caching: true
      - schedule: 5 mins
      - s3:
          bucket: users.bucket
          event: some:bucket:event
```
