### ISSUE TITLE
Add DynamoDB event source

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1441]
Another interesting event source is DynamoDB (based on community feedback) which should be implemented.

**Comment by franz-josef-kaiser** [comment]
…especially as it is already working in the v0.x versions.

**Comment by pouledodue** [comment]
+1000
I need this to implement ES/CQRS

**Comment by pouledodue** [comment]
can we tag this v1.0.0-beta

**Comment by pmuens** [comment]
Added docs how one can set this up in https://github.com/serverless/serverless/pull/1751

**Comment by thenikso** [comment]
I was getting this (in the cloud formation console, not in the Serverless error output which would be great to have instead)

> Please ensure the role can perform the GetRecords, GetShardIterator, DescribeStream, and ListStreams Actions on your stream in IAM.

So to make all this work I had to add:

```
provider:
  name: aws
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:DescribeStream"
        - "dynamodb:ListStreams"
      Resource: "arn:aws:dynamodb:<region>:*:table/<table-name>/stream/*"
```
