### ISSUE TITLE
Feature Request: Defaults in serverless.yaml

### ISSUE THREAD

**Issue by danhumphrey** [serverless/serverless#1487]
When creating a new service, I would like to see the defaults in the `serverless.yaml` file. I think this avoids ambiguity. The defaults can be edited or removed, but I think the visibility helps with understanding.

If I'm not following protocol in raising this, please correct me..

```
service: first-service
provider: aws
functions:
    hello:
        handler: handler.hello
defaults:
  stage: "dev"
  region: "us-east-1"
  memory: 1024
  timeout: 6
```
