### ISSUE TITLE
V1: VPC configuration

### ISSUE THREAD

**Issue by nikgraf** [serverless/serverless#1489]
I couldn't find any VPC configuration in v1 (neither docs nor code)

**Comment by eahefnawy** [comment]
yeah it's currently not supported. I think you can do it by via CF though by adding resources to serverless.yaml

**Comment by eahefnawy** [comment]
This should be easy to implement:

```yml
functions:
    hello:
        handler: handler.hello
        vpc:
            securityGroupIds:
                - firstId
                - secondId
            subnetIds:
                - firstId
                - secondId
```
We'll just grab these configs and pass it to the Lambda CF template.
