### ISSUE TITLE
functionObj.events.forEach is not a function after adding events

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [serverless/serverless#1507]
I am trying to deploy the project with this config:

```
service: projectname
provider: aws

defaults:
    stage: dev
    region: eu-central-1

functions:
    register:
        handler: handler.handler
        events:
            http:
                path: auth/register
                method: post
```

I just added  the events part, the rest is already deployed. I get this error:

```
  Type Error ---------------------------------------------
 
     functionObj.events.forEach is not a function
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Stack Trace --------------------------------------------

TypeError: functionObj.events.forEach is not a function
    at /usr/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/index.js:33:32
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:2654:24)
    at /usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:4380:18
    at forEach (/usr/lib/node_modules/serverless/node_modules/lodash/lodash.js:8634:14)
    at AwsCompileApigEvents.hooks.deploy:compileEvents.forEach (/usr/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/index.js:31:9)
    at /usr/lib/node_modules/serverless/lib/classes/PluginManager.js:69:38
    at tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by RudolfVonKrugstein** [comment]
The events must be a list, like this:

```
service: projectname
provider: aws

defaults:
    stage: dev
    region: eu-central-1

functions:
    register:
        handler: handler.handler
        events:
            - http:
                path: auth/register
                method: post
```

This is different in the documentation: https://github.com/serverless/serverless/blob/v1.0/docs/understanding-serverless/serverless-yaml.md
