### ISSUE TITLE
Bring back 2 level indentation for YAML

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1514]
Right now we indent everything with 4 spaces.

This is not necessary anymore (and not common in YAML). The only constraint is that list items need to be properly indentend (two spaces after the name of the event) --> see [here](https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#nested-dictionaries) for more information about this issue.

```
functions:
  hello:
    - events:
        s3: my-bucket
```

instead of

```
functions:
    hello:
        - events:
            s3: my-bucket
```

**Things to update:**

- [x] Docs
- [x] Yaml package usage
- [x] Template files
- [x] Yaml parser
