### ISSUE TITLE
npm package from private git repo

### ISSUE THREAD

**Issue by foobar8675** [serverless/serverless#1528]
I have a package.json that looks like

```
{
  "dependencies": {
    "starling-api-model": "git+ssh://git@bitbucket-privaterepo.git#v0.0.1"
     ...
  },
}

```
this npm package, starling-api-model uses bcrypt, which uses node-gyp, so i dont think just copying the files will work.

and in elastic bean stalk, in order to pull from the private repo, i have a couple scripts in my `.ebextensions` like the following

```
commands:
  01copys3rsakey:
    command: aws s3 cp s3://s3bucket/dev/id_rsa /root/.ssh/id_rsa
    ignoreErrors: true
  02setrsapermission:
    command: chmod 600 /root/.ssh/id_rsa
    ignoreErrors: true

```

```
Content-Disposition: form-data; name="fileName"; filename="02_sshconfig.config"
Content-Type: application/octet-stream

files:
    "/root/.ssh/config":
        owner: root
        group: root
        mode: "000600"
        content: |
            Host bitbucket.com
                User git
                Hostname bitbucket.com
                IdentityFile /root/.ssh/id_rsa
    "/root/.ssh/known_hosts":
        owner: root
        group: root
        mode: "000644"
        content: |
```

is there a way to accomplish this with serverless?
