### ISSUE TITLE
mixing handlers with and without events doesn't work as expected.

### ISSUE THREAD

**Issue by janaka** [serverless/serverless#1588]
##### Serverless Framework Version: 
1.0 alpha

##### Operating System: 
OSX

##### Expected Behavior:
The following should work but it doesn't.

```
service: serverless-graphql
provider: aws
functions:
    hello:
        handler: handler.hello
    graphql:
        handler: handler.graphql
        events:
           - http:
                path: graphql
                method: post     
```

##### Actual Behavior:
serverless.yaml

```
service: serverless-graphql
provider: aws
functions:
    hello:
        handler: handler.hello
        events:
            - http:
    graphql:
        handler: handler.graphql
        events:
           - http:
                path: graphql
                method: post     
```

Note needs 

```
        events:
            - http:
```
