### ISSUE TITLE
Support Custom Authorizers in APIG

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1594]
APIG Custom Authorizers are missing in v1, we need to bring back this functionality to let users set certain functions as authorizers for endpoints. The way this would work is that we add a new `authorizer` key for aws `http` event:

```yml
- http:
    method: get
    path: user/create
    authorizer: hello # this is the authorizer function name
```
The framework would then set the `hello` function as an authorizer for this endpoint, and will set the authorization type of this endpoint method to `CUSTOM` (rather than the default `NONE`)

Thoughts...? cc/ @flomotlik @pmuens @ac360 

Main Parent Issue:
https://github.com/serverless/serverless/issues/1408

**Comment by ac360** [comment]
@eslam A few thoughts:

* We'll need the Authorizer Lambda Function ARN.  Not sure how to get this in our current deployment method.
* Authorizer names/ARNS will likely be different for each stage.  How can people enter a dynamic variable here?

**Comment by ajagnanan** [comment]
Also, can we add a way for endpoints to use an existing custom authorizer?

**Comment by eahefnawy** [comment]
@ac360 I think this will be pretty easy now that we're using CF. We'll simply `GetAttr` the function ARN by referring to the function logical ID (we're already doing that all over our events). And since we have a CF template for each stage, staging should work out of the box.

**Comment by eahefnawy** [comment]
@ajagnanan you mean a function that is not managed by Serverless? hmmm theoretically we can, but I'm not sure about the use cases of this. It might cause the config to be a bit confusing/messy.

@flomotlik what's your thoughts on this?

**Comment by ajagnanan** [comment]
Yea, so currently i have 3 serverless services, and the 1st one contains the custom authorizer. Currently we need the custom authorizer s-function in the service for it to work, so I have to copy/paste it into the 3 services. It would be awesome if we can just reference existing custom authorizers to avoid copy/paste issues.

**Comment by eahefnawy** [comment]
This is now implemented in [PR 1620](https://github.com/serverless/serverless/pull/1620).

You can set an authorizer simply with:

```yml
- http:
    method: get
    path: user/create
    authorizer: authFunc # this is the authorizer function name
```
or:
```yml
- http:
    method: get
    path: user/create
    authorizer: 
        name: authFunc
        ttl: 300 # result time to live
        header: method.request.header.Auth # the header that will contain the authorization token
```
Both of these examples are identical. The second example lets you modify the defaults. Of course the referenced authorizer function must exist in your service. @ajagnanan let's see what @flomotlik think about that and maybe we can implement an "outsider" authorizer soon.

**Comment by ajagnanan** [comment]
sounds good!

**Comment by eahefnawy** [comment]
@ajagnanan I think the way we could add support for this is that you would simply provide the arn of the lambda you want to set as a provider instead of the name of the Serverless function:

```yml
- http:
    method: get
    path: user/create
    authorizer: auth::function::arn::string
```
or
```yml
- http:
    method: get
    path: user/create
    authorizer: 
        name: auth::function::arn::string
        ttl: 300
        header: method.request.header.Auth
```
We can then detect that this is an arn rather than a function name based on that arn format and set it for you.

One thing I dont like though is that you're providing an arn to the `name` property, which is a bit confusing. So maybe the second example should be this instead:

```yml
- http:
    method: get
    path: user/create
    authorizer: 
        arn: auth::function::arn::string
        ttl: 300
        header: method.request.header.Auth
```
