### ISSUE TITLE
Add support for APIG API Keys

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1595]
As an improvement for APIG, we need to add support for specifying API keys for the entire **service** API. Since this is a service wide config, it doesn't really fit inside the `http` event object, because it applies to all endpoints rather than a specific endpoint config. So what I'm thinking is ([based on other discussions on provider specific config](https://github.com/serverless/serverless/issues/1567)):

```yml
service: my-service
provider:
    name: aws
    apiKeys:
            - myFirstKey
            - ${mySecondSecretKey}
functions:
    hello:
    events:
        - http:
            path: user/create
            method: get
            private: true # Default is false. Set this endpoint/method to require API Key auth
```

This will simply take this keys array and compile each into `AWS::ApiGateway::ApiKey` resource and point it to the rest api. Clients connecting to this rest api will then need to set any of these API keys in the `x-api-key` header of their request if this endpoint has `private` set to true.

Thoughts...? cc/ @flomotlik @pmuens @ac360 

Main Parent Issue:
https://github.com/serverless/serverless/issues/1408
