### ISSUE TITLE
Support caching for APIG

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1597]
Support caching for APIG. This is a service-wide config (enabling caching/cache size for the APIG). So what I'm thinking is something like:

``` yml
service: my-service
provider:
    name: aws
    cacheSize: 0.5 # this is the cache cluster size.
```

Thoughts...? cc/ @flomotlik @pmuens @ac360

Parent Issue:
[#1408](https://github.com/serverless/serverless/issues/1408)

**Comment by ac360** [comment]
If the user enters a REST API into custom resources, does it overwrite the default REST API that is created?  Perhaps users should be able to do that, and specify caching settings in there.  I'm worried we're going to rewrite CloudFormation w/ `config`.

**Comment by eahefnawy** [comment]
From AWS guide on caching:

```
API Gateway enables caching by creating a dedicated cache instance. This process can take up to 4 minutes.
```
This could slow down deployment significantly, but it is up to the user whether it's worth it to optionally use caching or not.

**Comment by flomotlik** [comment]
I think Caching is a cool feature, I don't know if we already have enough info on how to implement it or which config values are important. Do we already have some people asking for it? Otherwise I would keep it open here and wait for more feedback going forward.

**Comment by eahefnawy** [comment]
I think implementation won't be hard at all. @HyperBrain what you think? are you using caching at all?

**Comment by HyperBrain** [comment]
Nope. I wanted to do some experiments with API caching, but with a very low prio, as even my AWS contact downvoted the feature because it is very hard to setup and even predict the effectiveness when using with parameterized endpoints.
I remember that there was an old issue for 0.5.x where there was a complaint about the setup og the caches in SLS.

**Comment by flomotlik** [comment]
ok, lets wait for more use cases, seems like it would be pretty simple to implement in the future

**Comment by nicka** [comment]
IMHO the CloudFront cach option for APIG sucks. It's either cache everything or nothing.

We always create the CloudFront Distribution and APIG deployment ourselves with CloudFormation in order to have more cache control. We also added the `ApiGatewayApi` Output, this way sls is able to deploy all the endpoint paths later on.

**Comment by nicka** [comment]
Another reason why I think the default CloudFront Distribution isn't very usable(yet). Is because of  the custom domain support. To my knowledge you can't configure custom SSL certificates through the CLI/API, only via the AWS console. All these issues can be fixed with a custom CloudFront Distribution resource with CloudFormation.

**Comment by flomotlik** [comment]
@nicka you mean the plugin would set up Cloudfront and APIG deployment by hand instead of going through the APIG Caching? Imho that sounds like a really interesting plugin. The only thing is I wouldn't put it right into core, but into our new Community Plugin Repo. Basically what we want to capture there are community contributed plugins that are interesting, where we help out and guarantee some level of quality.

When we put something into the core (e.g. caching support) it should be using the official AWS stuff as much as possible as we otherwise go against what is expected by users.

But I would really like to have this plugin if thats something you are interested in!

**Comment by nicka** [comment]
> You mean the plugin would set up Cloudfront and APIG deployment by hand instead of going through the APIG Caching?

Exactly!

### Rough draft

```yaml
service: hello

provider:
  name: aws
  runtime: nodejs4.3

plugins:
  httpCaching:
    Aliases:
      - foo.com
    ViewerCertificate:
      IamCertificateId: ${cloudFrontSsId}
    PriceClass: ${cloudFrontPriceClass}
    DefaultCacheBehavior:
      ForwardedValues:
        QueryString: true
        Headers:
          - Access-Control-Request-Headers
          - Access-Control-Request-Method
          - Origin
        Cookies:
          Forward: none
      ViewerProtocolPolicy: https-only
      DefaultTTL: ${cloudFrontDefaultTTL}
      MinTTL: ${cloudFrontMinTTL}
      MaxTTL: ${cloudFrontMaxTTL}
    CustomErrorResponses: # Optional
      - ErrorCode: 403
        ErrorCachingMinTTL: 0
    Logging: # # If key is present it will create a Logging S3 bucket
      IncludeCookies: false

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: api/v1.0/hello
          method: get
          httpCaching:
            PathPattern: "api/v1.0/hello" # Will be autogenerated based on the path
            # Could be autogenerated based on the method: get
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            # Could be autogenerated based on the method: get
            CachedMethods:
              - HEAD
              - GET
              - OPTIONS
            ForwardedValues:
              Cookies:
                Forward: none
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Origin
              QueryString: true
            # Optional
            DefaultTTL: ${cloudFrontDefaultTTL}
            MinTTL: ${cloudFrontMinTTL}
            MaxTTL: ${cloudFrontMaxTTL}
      - http:
          path: api/v1.0/hello
          method: post
          httpCaching:
            PathPattern: "api/v1.0/hello" # Will be autogenerated based on the path
            # Could be autogenerated based on the method: get
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - POST
            # Could be autogenerated based on the method: get
            CachedMethods:
              - HEAD
              - GET
              - OPTIONS
            ForwardedValues:
              Cookies:
                Forward: none
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Authorization
                - Origin
              QueryString: true
            # Optional
            DefaultTTL: ${cloudFrontDefaultTTL}
            MinTTL: ${cloudFrontMinTTL}
            MaxTTL: ${cloudFrontMaxTTL}
```

> When we put something into the core (e.g. caching support) it should be using the official AWS stuff as much as possible as we otherwise go against what is expected by users.

Understood

> But I would really like to have this plugin if thats something you are interested in!

I need some guidance into the community plugin repo. An example plugin would be useful ;)
