### ISSUE TITLE
Add support for APIG proxy settings

### ISSUE THREAD

**Issue by eahefnawy** [serverless/serverless#1598]
Give users the option to specify a certain endpoint to act as an HTTP proxy to another URI. This needs some thinking because setting an endpoint as a proxy means that the endpoint is not tied to a specific function, so it wouldn't make sense to have the config inside an `http` event object. Maybe this particular option could be a higher level config? How about:

```yml
service: my-service
config:
    aws:
        proxies:
            - method: get
              path: users/list
              url: www.example.com/users
            - method: get
              path: posts/list
              url: www.example.com/posts
```

Thats one way to do it, but it looks like too much config. One thing to keep in mind is that users can easily create proxy endpoints with CloudFormation if we document it well. They just need to know the correct template to add and how to reference the restApi id and so on.

What you guys think? should we just leave this for custom CF resources? or provide this nice config based abstraction layer? cc/ @flomotlik @pmuens @ac360 

Parent Issue:
[#1408](https://github.com/serverless/serverless/issues/1408)
