### ISSUE TITLE
Add correct indentation for events as objects in serverless.yaml and docs

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#1648]
The current indentation of the events (if they are an object) is not correct.

It's

```yaml
functions:
  hello:
    events:
       - http:
         path: foo
         method: get
```

but should be

```yaml
functions:
  hello:
    events:
       - http:
            path: foo
            method: get
```

Should be done after https://github.com/serverless/serverless/pull/1644 is merged.
