### ISSUE TITLE
API endpoints not created in serverless@1.0.0-alpha2

### ISSUE THREAD

**Issue by anthonyshull** [serverless/serverless#1660]
##### Expected Behavior:

When I attempt to deploy a service I expect the API endpoints I define in serverless.yaml to be created.

##### Actual Behavior:

Lambda functions are created and cloud formation resources defined in an external JSON file are created, but no endpoints are created in API Gateway.

##### Additional Details:
```
service: authorize
provider: aws
runtime: nodejs4.3

functions:
  login:
    handler: authorize.login
    events:
      - http:
         path: login
         method: post
  authorize:
    handler: authorize.authorize
```
Discussion template  ----------------------------------------------
