### ISSUE TITLE
Cannot use AWS Policy Variable in template

### ISSUE THREAD

**Issue by johncmckim** [serverless/serverless#1679]
I have been testing severless alpha on AWS. I am trying to create an IoT project with a few different services. I've run into an issue when creating a Policy document for the IoT things.

**Serverless Framework Version:** serverless@1.0.0-alpha.2
**Operating System:** OSX 10.11.5

##### Expected Behavior:
I have the following resource in my serverless.yaml
```
SensorThingPolicy:
      Type: "AWS::IoT::Policy"
      Properties:
        PolicyName: "garden_aid_iot_sensor_policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: ["iot:Connect"]
              Resource: ["arn:aws:iot:us-east-1:123451234510:client/${iot:ClientId}"]
            - Effect: "Allow"
              Action: ["iot:Publish"]
              Resource: ["arn:aws:iot:us-east-1:123451234510:garden/soil/moisture/${iot:ClientId}"]
```

Take note of the **${iot:ClientId}** variable. The variable is an [AWS policy variable](http://docs.aws.amazon.com/iot/latest/developerguide/authorization.html) not a serverless variable. It should be included in the template as is, rather than being substituted for a variable.

##### Actual Behavior:
When I try to deploy the project I get the following.

```
ServerlessError: Variable "iot:ClientId" doesn't exist in serverless.env.yaml. Please add it to serverless.env.yaml.
    at /usr/local/lib/node_modules/serverless/lib/classes/Service.js:199:23
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/lib/classes/Service.js:166:42)
    at walker (/usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:190:22)
    at /usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:298:31)
    at walker (/usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:203:13)
    at /usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:298:31)
    at walker (/usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:203:13)
    at /usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:298:31)
    at walker (/usr/local/lib/node_modules/serverless/node_modules/traverse/index.js:203:13)
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:10:28
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:19:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
```

It would be great if we could escape these variables or even better (if possible) serverless recognised policy variables and ignored them.

*P.S. I am really liking the 1.0 alpha so far*

**Comment by johncmckim** [comment]
Another example of an affected template: **"${clientId()}"** and **"${timestamp()}"**

```
SensorThingRule:
    Type: "AWS::IoT::TopicRule"
    Properties:
      RuleName: "soil_sensor_store_data"
      TopicRulePayload:
        RuleDisabled: false
        Sql: "SELECT DeviceId, Recorded, Level FROM 'garden/soil/moisture'"
        Actions:
          -
            DynamoDB:
              TableName: { Ref: MoistureData }
              HashKeyField: "ClientId"
              HashKeyValue: "${clientId()}"
              RangeKeyField: "Timestamp"
              RangeKeyValue: "${timestamp()}"
              PayloadField: "Data"
              RoleArn: { Fn::GetAtt: [ IotThingRole, Arn ] }
```

I'm also happy to contribute a fix once a solution is decided upon.

**Comment by eahefnawy** [comment]
@johncmckim maybe you can put the entire `Resource: ["arn:aws:iot:us-east-1:123451234510:client/${iot:ClientId}"]` string into a serverless variable. I think it should work in that case cause we only populate variables once.

**Comment by johncmckim** [comment]
@eahefnawy that does resolve the issues. Thanks for the suggestion.

The solution is a little bit awkward, especially for the `SensorThingRule` example. Variables exist for re-use, so it seems a little strange to have to create a variable for a single property. The separation also makes it harder to understand the template as you have to look at `serverless.yml` and `serverless.env.yml`.

**Comment by eahefnawy** [comment]
I do agree it's a bit awkward. Here's another solution: you can defined your own variable syntax to replace the default `${}` syntax (which in this case conflicts with AWS). We added the ability to overwrite variable syntax for that exact reason actually. You just need to provide a regex:

```yml
service: service-name
variableSyntax: '\\${{([\\s\\S]+?)}}' # this will match ${{}}
functions:
resources:
```

I just noticed that this is not covered in the docs, sorry about that. Opening an issue now to cover this.

Hope this helps 😊

**Comment by johncmckim** [comment]
Thanks. I'll give that a go tomorrow morning.

**Comment by johncmckim** [comment]
@eahefnawy I changed the variable syntax to `'\${{([\s\S]+?)}}'` and it worked perfectly. Thanks for your help.

**Comment by mvayngrib** [comment]
@johncmckim hm, I couldn't get it to work for me. Would you mind sharing the relevant piece of yml that worked for you? I'm using serverless@1.14.0

This is what I have:

```yml
provider:
  variableSyntax: '\${{([\s\S]+?)}}'
# ...
resources:
  Resources:
    IoTClientPolicy:
      Type: AWS::IoT::Policy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            # restrict client connect by client id
            - Effect: Allow
              Action: ["iot:Connect"]
              Resource: ["aws:iot:::client/${iot:ClientId}"]
            # allow all clients to publish to thd send topic
            - Effect: "Allow"
              Action: ["iot:Publish"]
              Resource: ["aws:iot:::topic/send"]
            # restrict client topic subscriptions by their client id
            - Effect: "Allow"
              Action: ["iot:Subscribe"]
              Resource: ["aws:iot:::topicfilter/${iot:ClientId}"]
            # restrict messages clients receive by their client id
            # this has the same function as the Subscribe rule above
            # provided the Subscribe policy is upheld, this policy should always give a pass
            - Effect: "Allow"
              Action: ["iot:Receive"]
              Resource: ["aws:iot:::topic/${iot:ClientId}"]
```

and the error:

```sh
 Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: IoTClientPolicy
     - Policy document is Malformed: The following resources
     are invalid : aws:iot:::client/${iot:ClientId}.
```

**Comment by pmuens** [comment]
@mvayngrib could you try to use double quotes for the variable syntax (instead of single quotes)?

I ran into the same issue the other day (see: https://github.com/serverless/serverless/issues/3561#issuecomment-299848141)

**Comment by mvayngrib** [comment]
@pmuens yea, didn't help :(

**Comment by pmuens** [comment]
> @pmuens yea, didn't help :(

😞 hmm. Maybe @johncmckim comes back and shares the way he resolved it.

**Comment by tkbrady** [comment]
@mvayngrib were you able to resolve this?  i'm having the same problem now.

**Comment by mvayngrib** [comment]
@tkbrady yep, here's my variable syntax and iam statement

```yaml
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"
...
                  Resource:
                    - Fn::Join:
                      - ":"
                      - - 'arn:aws:iot'
                        - Ref: AWS::Region
                        - Ref: AWS::AccountId
                        - 'client/${iot:ClientId}'
```
