### ISSUE TITLE
Environment/stage variable issue

### ISSUE THREAD

**Issue by svdgraaf** [serverless/serverless#1704]
Bug Report Template -----------------------------------------------

##### Serverless Framework Version: 
1.0a2 (git checkout)

##### Operating System: 
osx

##### Expected Behavior:
When I setup different environment variables for different stages, and use the variable in my custom resources, I'd expect them to be correctly parsed

##### Actual Behavior:
Given the following serverless.env.yml:
```yml
vars: null
stages:
  production:
    vars:
      bucketname: foobar-prod
      keyname: thumbnails-production
  dev:
    vars:
      bucketname: foobar-dev
```

And given some custom resource in `serverless.yml`:
```yml
resources:
  Resources:
    FoobarBucket:
      Type: AWS::S3::Bucket
      Properties:
       BucketName: ${bucketname}
```

When I deploy `sls deploy`, everything is fine, a bucket is created with a bucket name of `foobar-dev`. When I deploy with the `sls deploy -s production`, the deploy fails, and CF indicates that the specified bucket already exists (eg: it get's the same name `foobar-dev`).

Perhaps I'm missing something, but it doesn't sound like this is the way it is supposed to work? 😄 

Also, is there a way to use the `stageName` in the resources? So we could do:

```yml
resources:
  Resources:
    FoobarBucket:
      Type: AWS::S3::Bucket
      Properties:
       BucketName: ${stageName}-foobar-bucket
```

```bash
$ sls deploy -s production

  Serverless Error ---------------------------------------

     Variable "stage" doesn't exist in serverless.env.yml.
     Please add it to serverless.env.yml.

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

If not, perhaps that would be nice to have?

**Comment by svdgraaf** [comment]
I found the bug (the `-s` doesn't work, `--stage` does), I also found the issue with the `stage` not being available, am now trying to figure out a fix 😄

**Comment by eahefnawy** [comment]
@svdgraaf I think there's a misconception here. The options you pass **are not variables to be populated**. So just because you're passing the stage as an option doesn't mean that it'll be available as a variable. If you want the stage as a variable, you can simply add it to `serverless.env.yml`:

```yml
vars: null
stages:
  production:
    vars:
      stageName: production
```
Maybe we should include this variable by default for you? I guess it depends on the use cases.
