### ISSUE TITLE
[Breaking change] serverless deploy does not work with 1.0.0-beta.1 when deploying services built with 1.0.0-alpha.2

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1752]
##### Serverless Framework Version: 

```
1.0.0-beta.1
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/17402212/e8e22b6e-5a49-11e6-970f-12d2018723f4.png)

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/17402232/08cf3836-5a4a-11e6-9ae5-2e438c289aca.png)

![image](https://cloud.githubusercontent.com/assets/3421858/17402493/7339511a-5a4b-11e6-81b8-0f50cb28a6dc.png)

And here is the template:

```
{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application's resources outside of Lambdas and Api Gateway","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket"},"IamRoleLambda":{"Type":"AWS::IAM::Role","Properties":{"AssumeRolePolicyDocument":{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com"]},"Action":["sts:AssumeRole"]}]},"Path":"/"}},"IamPolicyLambda":{"Type":"AWS::IAM::Policy","Properties":{"PolicyName":"dev-graphql-lambda","PolicyDocument":{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":["logs:CreateLogGroup","logs:CreateLogStream","logs:PutLogEvents"],"Resource":"arn:aws:logs:us-west-2:*:*"}]},"Roles":[{"Ref":"IamRoleLambda"}]}},"LinksDynamo":{"Type":"AWS::DynamoDB::Table","DeletionPolicy":"Retain","Properties":{"AttributeDefinitions":[{"AttributeName":"id","AttributeType":"S"}],"KeySchema":[{"AttributeName":"id","KeyType":"HASH"}],"ProvisionedThroughput":{"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableName":"graphql-links-dev"}},"PostsDynamo":{"Type":"AWS::DynamoDB::Table","DeletionPolicy":"Retain","Properties":{"AttributeDefinitions":[{"AttributeName":"id","AttributeType":"S"}],"KeySchema":[{"AttributeName":"id","KeyType":"HASH"}],"ProvisionedThroughput":{"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableName":"graphql-posts-dev"}},"AuthorsDynamo":{"Type":"AWS::DynamoDB::Table","DeletionPolicy":"Retain","Properties":{"AttributeDefinitions":[{"AttributeName":"id","AttributeType":"S"}],"KeySchema":[{"AttributeName":"id","KeyType":"HASH"}],"ProvisionedThroughput":{"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableName":"graphql-authors-dev"}},"CommentsDynamo":{"Type":"AWS::DynamoDB::Table","DeletionPolicy":"Retain","Properties":{"AttributeDefinitions":[{"AttributeName":"id","AttributeType":"S"}],"KeySchema":[{"AttributeName":"id","KeyType":"HASH"}],"ProvisionedThroughput":{"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableName":"graphql-comments-dev"}},"graphql":{"Type":"AWS::Lambda::Function","Properties":{"Code":{"S3Bucket":{"Ref":"ServerlessDeploymentBucket"},"S3Key":"graphql-1470136751048.zip"},"FunctionName":"graphql-dev-graphql","Handler":"handler.graphql","MemorySize":1024,"Role":{"Fn::GetAtt":["IamRoleLambda","Arn"]},"Runtime":"nodejs4.3","Timeout":6}},"RestApiApigEvent":{"Type":"AWS::ApiGateway::RestApi","Properties":{"Name":"dev-graphql"}},"ResourceApigEvent0":{"Type":"AWS::ApiGateway::Resource","Properties":{"ParentId":{"Ref":"ResourceApigEvent1"},"PathPart":"graphql","RestApiId":{"Ref":"RestApiApigEvent"}}},"ResourceApigEvent1":{"Type":"AWS::ApiGateway::Resource","Properties":{"ParentId":{"Fn::GetAtt":["RestApiApigEvent","RootResourceId"]},"PathPart":"egamitv","RestApiId":{"Ref":"RestApiApigEvent"}}},"PostMethodApigEvent0":{"Type":"AWS::ApiGateway::Method","Properties":{"AuthorizationType":"NONE","HttpMethod":"POST","MethodResponses":[{"ResponseModels":{},"ResponseParameters":{},"StatusCode":"200"}],"RequestParameters":{},"Integration":{"IntegrationHttpMethod":"POST","Type":"AWS","Uri":"arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:0675512353434:function:graphql-dev-graphql/invocations","RequestTemplates":{"application/json":"\n            #define( $loop )\n              {\n              #foreach($key in $map.keySet())\n                  \"$util.escapeJavaScript($key)\":\n                    \"$util.escapeJavaScript($map.get($key))\"\n                    #if( $foreach.hasNext ) , #end\n              #end\n              }\n            #end\n            {\n              \"body\": $input.json(\"$\"),\n              \"method\": \"$context.httpMethod\",\n              \n              #set( $map = $input.params().header )\n              \"headers\": $loop,\n  \n              #set( $map = $input.params().querystring )\n              \"query\": $loop,\n  \n              #set( $map = $input.params().path )\n              \"path\": $loop,\n  \n              #set( $map = $context.identity )\n              \"identity\": $loop,\n  \n              #set( $map = $stageVariables )\n              \"stageVariables\": $loop\n            }\n          "},"IntegrationResponses":[{"StatusCode":"200","ResponseParameters":{},"ResponseTemplates":{"application/json":""}}]},"ResourceId":{"Ref":"ResourceApigEvent0"},"RestApiId":{"Ref":"RestApiApigEvent"}}},"DeploymentApigEvent":{"Type":"AWS::ApiGateway::Deployment","DependsOn":"PostMethodApigEvent0","Properties":{"RestApiId":{"Ref":"RestApiApigEvent"},"StageName":"dev"}},"PostPermissionApigEvent0":{"Type":"AWS::Lambda::Permission","Properties":{"FunctionName":{"Fn::GetAtt":["graphql","Arn"]},"Action":"lambda:InvokeFunction","Principal":"apigateway.amazonaws.com"}}},"Outputs":{"IamRoleArnLambda":{"Description":"ARN of the lambda IAM role","Value":{"Fn::GetAtt":["IamRoleLambda","Arn"]}},"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}
```

`serverless deploy` worked perfectly with `1.0.0-alpha.1` and `1.0.0-alpha.2`

 @pmuens ? @eahefnawy ? @wedgybo ?

**Comment by wedgybo** [comment]
Paste your cloudformation logs to see where it failed if you could please

**Comment by pmuens** [comment]
@codepreneur thanks for reporting!

Might have something todo with this PR https://github.com/serverless/serverless/pull/1702 from @wedgybo

**Comment by wedgybo** [comment]
Yup, if it's a redeploy there might be issues we haven't considered. The cloudformation error should help more

**Comment by codepreneur** [comment]
@wedgybo see above.

**Comment by wedgybo** [comment]
You'll need to grab the logs from the cloudformation site as that error isn't very helpful unfortunately.

Specifically you want to look for the status reason next to the failed event for that deploy.

Should be another feature to pull that into back.

https://www.dropbox.com/s/jpsnknwk0ugsso9/Screenshot%202016-08-04%2014.08.37.png?dl=1

**Comment by codepreneur** [comment]
@wedgybo thats what I did. Here they are again:

![image](https://cloud.githubusercontent.com/assets/3421858/17402493/7339511a-5a4b-11e6-81b8-0f50cb28a6dc.png)

**Comment by wedgybo** [comment]
Hah sorry about that. Forgot to refresh 🔫 

Okly, can you paste your config. Looks like it thinks two things are the same so there could be an issue with the resource names based on the paths you've specified.

**Comment by codepreneur** [comment]
`serverless.yaml`

```
service: graphql
provider: aws
runtime: nodejs4.3

defaults:
  stage: dev
  region: us-west-2
  memory: 1024
  timeout: 6

functions:
    graphql:
        handler: handler.graphql
        events:
          - http:
              path: egamitv/graphql
              method: post
resources:
  Resources: 

    LinksDynamo: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: id
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${service}-links-${stage}

    PostsDynamo: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: id
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${service}-posts-${stage}

    AuthorsDynamo: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: id
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${service}-authors-${stage}

    CommentsDynamo: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: id
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${service}-comments-${stage}

```

`serverless.env.yaml`

```
vars: null
stages:
    dev:
        vars: null
        regions:
            us-west-2:
                vars:
                    service: graphql
                    stage: dev
                    iamRoleArnLambda: >-
                        [ LAMBDA ARN ]
                    serverlessDeploymentBucketName: [MY BUCKET NAME]

```
