### ISSUE TITLE
Variable mapping looks broken

### ISSUE THREAD

**Issue by nicka** [serverless/serverless#1754]
##### Actual Behavior: Function is being named `dev-us-east-1-foo`

# Additional info

Atm variable mapping seems broken or I don't properly get it? Do default `${stage}` and `${region}` variables exist?

`serverless.yml`
```yaml
functions:
  foo:
    name: ${stage}-${region}-foo
    handler: handler.foo
    events:
      - http:
          path: greet
          method: get
```

`serverless.env.yml`
```yaml
vars:
  stage:
  region:
stages:
  devnick:
    vars:
      stage: devnick
    regions:
      eu-central-1:
        vars:
          region: eu-central-1
  dev:
    vars:
      stage: dev
    regions:
      us-east-1:
        vars:
          region: us-east-1
```

My function ends up being called: `dev-us-east-1-foo`

<img width="1072" alt="screen shot 2016-08-04 at 16 10 49" src="https://cloud.githubusercontent.com/assets/195404/17405033/4931067a-5a5e-11e6-9bbb-15c2df9004b9.png">

**Comment by eahefnawy** [comment]
You need to pass the stage/region as options so you'd trigger the framework to use the stage & region vars rather than the common vars (which are null for stage/region)

```
serverless deploy --stage devnick --region eu-central-1
```

Hope this helps 😊

**Comment by nicka** [comment]
@eahefnawy Thanks for the heads up. I tried it without the stage and regions variables with .env.yml witout success. I was using -s and -r instead of --stage and --region. Maybe this should be more prominent within the docs 👍

**Comment by nicka** [comment]
```
functions:
  hello:
    name: ${stage}-hello
    handler: handler.hello
    events:
      - http:
          path: greet
          method: get
```

`sls deploy --stage devnick --region eu-central-1`

Output:
```

  Serverless Error ---------------------------------------

     Variable "stage" doesn't exist in serverless.env.yml.
     Please add it to serverless.env.yml.

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```
