### ISSUE TITLE
[Critical Bug] sometimes endpoints do not get deployed to API Gateway

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1766]
##### Serverless Framework Version: 

```
1.0.0-beta.1
```

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

Endpoints get deployed to amazon

![image](https://cloud.githubusercontent.com/assets/3421858/17432805/0fb64d38-5af9-11e6-99e6-85224fd6203e.png)

##### Actual Behavior:

![image](https://cloud.githubusercontent.com/assets/3421858/17432795/0288490e-5af9-11e6-9045-b7a66b990316.png)

`cloudformation`

![image](https://cloud.githubusercontent.com/assets/3421858/17432816/27d20a06-5af9-11e6-9c4d-86d96b9006d0.png)

I created a completely new amazon account, set up IAM and did a fresh deploy.

What is weird is that endpoint for my other lambda service got deployed perfectly fine:

![image](https://cloud.githubusercontent.com/assets/3421858/17432873/68d8b766-5af9-11e6-9cdc-eba5a477e0db.png)

`cloudformation`

![image](https://cloud.githubusercontent.com/assets/3421858/17432891/85c09e70-5af9-11e6-8072-e687eefc09d4.png)
![image](https://cloud.githubusercontent.com/assets/3421858/17432899/8e6ffb2e-5af9-11e6-8308-d3840e1d3960.png)

I tried fresh deploy (sls remove -> sls deploy), changing method from post to get changing name of endpoint. Same problem.

 @pmuens ? @eahefnawy ? @wedgybo ?

**Comment by codepreneur** [comment]
I found what the problem is.

Apparently endpoint path HAVE TO start with the same name as function name, or otherwise it gets ignored.

Like so:

```
functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post

```

and

```
functions:
  embedly:
    handler: handler.embedly
    events:
      - http:
          path: embedly/extract
          method: get
```

Is this a bug introduced in `beta.1`? or intended requirement to create endpoints that's not documented ?

**Comment by pmuilu** [comment]
+1

I first noticed this as I changed method from get to post. This update was correctly propagated to "Resources" -section but in "Stages" there was only old GET version visible. Then I did sls remove and sls deploy. This method was again visible fine in Resources but now totally missing from "Stages". Then I did sls remove/deploy again and it was now fine. 

Sorry I can't be more specific as my understanding with API GW is currently limited :)

**Comment by wedgybo** [comment]
I'm struggling to replicate the issue where the path must be the same as the function name. I'm running off the the latest commit on master though.

@pmuilu Yes your issue is a replica of #1684 where redeployments won't update correctly to the stage.

```
functions:

    hello:
        handler: handler.hello
        events:
          - http:
              path: greet
              method: get
    crawl:
        handler: handler.crawl
        events:
          - http:
              path: crawl
              method: get
    walk:
        handler: jog/index.walk
        events:
          - http:
              path: steve
              method: post
    run:
        handler: jog/index.run
        events:
          - http:
              path: montague/runs/free/and/wild
              method: get
```

```
endpoints:
  POST - https://ceybm28uy1.execute-api.eu-west-1.amazonaws.com/dev/steve
  GET - https://ceybm28uy1.execute-api.eu-west-1.amazonaws.com/dev/montague/runs/free/and/wild
  GET - https://ceybm28uy1.execute-api.eu-west-1.amazonaws.com/dev/greet
  GET - https://ceybm28uy1.execute-api.eu-west-1.amazonaws.com/dev/crawl
```
