### ISSUE TITLE
Support base path methods

### ISSUE THREAD

**Issue by jatsrt** [serverless/serverless#1778]
1.0.0-beta.1

This is in context of organizing a large project, and maybe it's more a clarification than anything else.

If I am developing a large serverless project to back a "complex" api.

So, I would have as part of the serverless project 

Service: users
  Endpoint: / GET
Service: widgets
  Endpoint: / GET

Or I could have:

Service: myservice
  Endpoint: /users GET
  Endpoint: /widgets GET

The second option seems to be contrary to what serverless is trying to accomplish with the services model.

However, the problem, and this may be a bit AWS/APIG specific.

I am going to generate as seperate managed deploys:
myapp-users
myapp-widgets 

This creates two APIG APIs
If I want to combine these into a single hostname/Custom Domain Name

I would generlaly want to map
"/users" -> myapp-users
"/widgets" -> myapp-widgets

This is generally allowed and doable in APIG/Lambda

So the bug:
you cannot in the current events/HTTP create base path methods

```
functions:
  list:
    handler: handler.list
    #   you can add any of the following events
    events:
      - http:
          path: ""
          method: get
```

This would force 

```
functions:
  list:
    handler: handler.list
    #   you can add any of the following events
    events:
      - http:
          path: users
          method: get
```

Then the API with a custom domain would be
/users/users

So, either, allow base path mappings or be more clear on large project structure requiring them to not be separate services, but always one service per project that will be combined as an API?

Or functions as designed sorry, nothing can be done?
