### ISSUE TITLE
upgrade to v.1 - "Missing Authentication Token"

### ISSUE THREAD

**Issue by andyfenelon** [serverless/serverless#1780]
when i change 

```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: post
```

i'm getting 

> {
>   "message": "Missing Authentication Token"
> }
