### ISSUE TITLE
VPC not created correctly in 1.0.0-beta

### ISSUE THREAD

**Issue by jeremybmerrill** [serverless/serverless#1786]
##### Serverless Framework Version:

1.0.0-beta
##### Operating System:

Windows/Cygwin. (Sorry! My real computer died in a flood localized to my kitchen table and the replacement hasn't arrived yet. This hurts me more than it hurts you.)
##### Expected Behavior:

specifying `vpc` for either under a function or under `provider` should set the VPC correctly in the AWS Lambda console 
##### Actual Behavior:

It doesn't. When I add the relevant stuff (see below) and `sls deploy`, I get an error saying ````  Serverless Error ---------------------------------------

``````
 An error occurred while provisioning your cloudformation:
 The following resource(s) failed to update: [myfunctionname].````
``````
##### Stack-Trace (Optional):

```
$ SLS_DEBUG=true sls deploy
Serverless: Zipping service...
Serverless: Removing old service versions...
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
Serverless: Checking stack update progress...

  Serverless Error ---------------------------------------

     An error occurred while provisioning your cloudformation:
     The following resource(s) failed to update: [myfunctionname].


  Stack Trace --------------------------------------------

ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to update: [myfunctionname].
    at C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\lib\updateStack.js:56:33
    at tryCatcher (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\JeremyB\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The config in my `serverless.yml` looks like this, whether under `provider` or under `functions`.`myfunctionname`:

```
    vpc:
      securityGroupIds:
        - sg-abcdefg
      subnetIds: 
        - subnet-abcdefg1
        - subnet-abcdefg2
        - subnet-abcdefg3
        - subnet-abcdefg4
```

A possible hint: when I use the IAM role created by serverless (myproject-dev-IamRoleLambda-5ABCDEFGH) and attempt to add the VPC settings in the Lambda console, the console complains "Your role does not have VPC permissions. Please go back and select "Basic with VPC" under the role dropdown to add these permissions.". Is it possible that the serverless-created roles don't have the right permissions? 

Thanks for your help. First started with serverless this morning and it's already really awesome. Thanks for your hard work!!

**Comment by jeremybmerrill** [comment]
I should add that I fixed the issue (for myself) by adding the `AWSLambdaVPCAccessExecutionRole` "Managed Policy" to serverless's IAM role (i.e. "myproject-dev-IamRoleLambda-5ABCDEFGH") in the IAM console.

Presumably that's the fix: that the role created by serverless should give itself VPC permissions like those in the managed policy...

**Comment by olegZastavnyi** [comment]
When this issue will be fixed? We really need to have it working.

**Comment by pmuens** [comment]
Hey @jeremybmerrill thanks for reporting and providing a solution.

We've recently implemented a way to add roles. You can see the docs here: https://github.com/serverless/serverless/blob/master/docs/guide/custom-provider-resources.md#adding-custom-iam-role-statements

This is not yet released in the beta release so you might want to checkout the current master branch.

@jeremybmerrill @olegZastavnyi let me know if this resolves your issues or if I can help you otherwise!

**Comment by olegZastavnyi** [comment]
@pmuens  thanks

**Comment by flomotlik** [comment]
@pmuens @jeremybmerrill the problem here is that The Lambda execution role needs access to a few additional EC2 actions:

`ec2:CreateNetworkInterface, ec2:DescribeNetworkInterfaces, and ec2:DeleteNetworkInterface`

according to : http://docs.aws.amazon.com/lambda/latest/dg/vpc.html

Basically I see 2 different ways to resolve this going forward:

1. Add documentation that outlines how to add those specific EC2 IAM actions yourself through what @pmuens described
2. Automatically add those to the IAM role so you don't have to set up anything (and document that we do this)

Otherwise imho its going to be painful for people to start using VPC's properly.

**Comment by olegZastavnyi** [comment]
@pmuens Could you please provide doc. how to configure  IAM role for lambda?

**Comment by jeremybmerrill** [comment]
Seems like the easier out-of-the-box, the better. My vote -- which ought to count for nothing, I know :D -- would for option 2.

**Comment by olegZastavnyi** [comment]
trying to add role as described in document but nothing happens. 
Here how I am trying:

provider:
  name: aws
  runtime: java8
  iamRoleStatements:
        -  Effect: "Allow"
           Action:
             - "logs:CreateLogGroup"
             - "logs:CreateLogStream"
             - "logs:PutLogEvents"
             - "ec2:CreateNetworkInterface"
             - "ec2:DescribeNetworkInterfaces"
             - "ec2:DeleteNetworkInterface"
           Resource: { "Fn::Join" : ["", ["arn:aws:lambda:::", { "Ref" : "dataExtractorLambdaFunction"} ] ] }

I am doing something wrong ?

**Comment by flomotlik** [comment]
@olegZastavnyi have you tried with * in the resources? I don't think limiting the resources for Network Interfaces works in this way

**Comment by olegZastavnyi** [comment]
@flomotlik yes, but it does't work! Seems to me this feature is buggy as well

**Comment by flomotlik** [comment]
Can you print a screenshot of the serverless.yml and the resulting cloud formation template you see in CF?

**Comment by olegZastavnyi** [comment]
ok, got it working. For other people who cross over this issue.

resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Policy for allowing vpc connection.
        Roles:
          - {"Ref" : "IamRoleLambda"}
        PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
               - "logs:CreateLogGroup"
               - "logs:CreateLogStream"
               - "logs:PutLogEvents"
               - "ec2:CreateNetworkInterface"
               - "ec2:DescribeNetworkInterfaces"
               - "ec2:DeleteNetworkInterface"
              Resource: "*"

**Comment by JulienWeiler** [comment]
@olegZastavnyi I can't get this to work. My current settings are the following.
Did you add anything else then this? I get the same error as mention in the first post.

```
resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Policy for allowing vpc connection.
        Roles:
          - {"Ref" : "IamRoleLambda"}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "ec2:CreateNetworkInterface"
                - "ec2:DescribeNetworkInterfaces"
                - "ec2:DeleteNetworkInterface"
              Resource: "*"
```

My provider configuration look like this:

**Comment by olegZastavnyi** [comment]
```
@JulienWeiler 
Here is my full code.

# This file is the main config file for your service.
service: observation # NOTE: update this with your service name

provider:
  name: aws
  runtime: java8

# you can overwrite defaults here
defaults:
  stage: dev
  region: us-west-2

# you can add packaging information here
package:
#  include:
#    - include-me.java
#  exclude:
#    - exclude-me.java
  artifact: target/jar-1.0-SNAPSHOT.jar

functions:
  #Adding AWS lambda functions.
  lambdaFunction:
    handler: com.Lambda
    vpc:
      securityGroupIds:
        - sg-*****
        - sg-*****
      subnetIds:
        - subnet-*****
        - subnet-*****
        - subnet-*****
    events:
#      - schedule: cron(0/1 * * * ? *) #Every minute
      - http:
          path: getaway/getResources
          method: GET

# you can add CloudFormation resource templates here
resources:
  Resources:
    #Adding AWS lambda access policy.
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - {"Ref" : "IamRoleLambda"}
        PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
               - "logs:CreateLogGroup"
               - "logs:CreateLogStream"
               - "logs:PutLogEvents"
               - "ec2:CreateNetworkInterface"
               - "ec2:DescribeNetworkInterfaces"
               - "ec2:DeleteNetworkInterface"
              Resource: "*"
 
```
