### ISSUE TITLE
Serverless seems to ignore certain options

### ISSUE THREAD

**Issue by paulmerlin** [serverless/serverless#1798]
Dearest reader!  This may be a case of PEBKAC, but i'm having trouble setting some really simple stuff using serverless.

Here's the `serverless.yml` file i'm using:

```yml
service: my-test-service

provider:
  name: aws
  runtime: python2.7

defaults:
  stage: dev
  region: ap-southeast-2

functions:
  sendmail:
    handler: handler.send_email
    memorySize: 128
    customRole: ${iamRoleArnLambdaEmail}
    events:
      - http:
          path: send_email
          method: get
```

`serverless.env.yml` contains:

```yml
vars:
stages:
  dev:
    vars:
      iamRoleArnLambdaEmail: "arn:aws:iam::123123:role/iamRoleArnLambdaEmail"
    regions:
      ap-southeast-2:
        vars:
```

The `iamRoleArnLambdaEmail` is a role i created on AWS with the `AmazonSES_FullAccess` permission so that my lambda function can send email, but that is not being picked up either.

##### Serverless Framework Version: 

serverless beta installed using `npm install -g serverless@beta`

##### Operating System: 

CentOS/7

##### Expected Behavior:

I expect that a deployed stack will have MemorySize: 128 set when i go and look in the AWS console under CloudFormation.  Likewise i expect the custom role to be added to my lambda function.

##### Actual Behavior:

Instead, it shows the default value of MemorySize: 1024, and i cannot seem to get that to change.  Secondarily, the `customRole` property seems to be ignored, but that may or may not be related. 

Please don't hesitate to ask if you need more info, and my apologies if this is a very dumb error on my part.  Thanks!

**Comment by flomotlik** [comment]
@paulmerlin I just deployed a function with the following config and it properly changed the memorySize:

```
  hello:
    handler: handler.hello
    memorySize: 320
```

Could you update to the latest version of serverless and try again to make sure? It should be working fine out of the box.

**Comment by flomotlik** [comment]
And regarding `customRole` that is not implemented yet but there is an issue here: #1772 and here #1807

**Comment by markvivanco** [comment]
I am also finding I cannot set memorySize to 128.  memorySize is being set to 256 instead.  My yml looks like:

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}

**Comment by pmuens** [comment]
Hey @markvivanco thanks for getting back. I tried to reproduce this locally but was unsuccessful.

Here's the `serverless.yml` I've used:

```yml
service: service

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128

functions:
  hello:
    handler: handler.hello
```

What Serverless version are you using? Are you overwriting the `memorySize` on a function level?
