### ISSUE TITLE
[Critical Bug] Tables cannot be updated (e.g. adding a RANGE key) after creation

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#1803]
##### Serverless Framework Version: 

```
1.0.0-beta.1
```

Well to be more accurate I am on `master` and this commit: `d1942f4937a85823f6f7deb9094bd32a4acdea`

##### Operating System: 

![image](https://cloud.githubusercontent.com/assets/3421858/16957931/5fe5d11e-4dd6-11e6-9d95-a5734cdee160.png)

##### Expected Behavior:

Table to update in aws console

##### Actual Behavior:

I deployed first like so:

```
resources:
  Resources: 

    VideosDynamo: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: id
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${service}-videos-${stage}

```
then changed it like so
```
resources:
  Resources: 

    VideosDynamo: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: id
            AttributeType: S
          - 
            AttributeName: content_provider_id
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: id
            KeyType: HASH
          - 
            AttributeName: content_provider_id
            KeyType: RANGE
        ProvisionedThroughput: 
          ReadCapacityUnits: 20
          WriteCapacityUnits: 20
        TableName: ${service}-videos-${stage}

```

to get the following error below:

![image](https://cloud.githubusercontent.com/assets/3421858/17515644/7a9714bc-5e31-11e6-8b0b-d2ea04723f7e.png)

`cloudformation`

![image](https://cloud.githubusercontent.com/assets/3421858/17515868/ebbf5298-5e32-11e6-9b53-69494be6499d.png)

This should work, because:

![image](https://cloud.githubusercontent.com/assets/3421858/17515730/106086d6-5e32-11e6-8c26-3a88a2164f49.png)

 @pmuens ? @eahefnawy ? @wedgybo ?

**Comment by flomotlik** [comment]
Can you check the CF template if `TableName: ${service}-videos-${stage}` gets properly set up? At the moment ${stage}, ... are not available as a variable. We're currently working on this in #1801

**Comment by codepreneur** [comment]
I have declared those variables in `serverless.env.yml` like so:

```

vars:
stages:
  dev:
    vars:
    regions:
      us-east-1:
        vars:
          service: graphql
          stage: dev

```

and it does get set up correctly on aws console, the first time I deploy.
