### ISSUE TITLE
Endpoint not created

### ISSUE THREAD

**Issue by zachheine** [serverless/serverless#1810]
Deploying:
```
functions:
  createUsers:
    handler: handler.createUsers
    events:
      - http:
        path: users/create
        method: get
```
does not result in the creation of an endpoint.

However, when I use:
```
functions:
  createUsers:
    handler: handler.createUsers
    events:
      - http: GET users/create
```
an endpoint is created.

**Comment by pmuens** [comment]
Hey @zachheine
Thanks for reporting!

It's a problem with indentation. You need to add 2 more spaces after the `-http` like this:

```
functions:
  createUsers:
    handler: handler.createUsers
    events:
      - http:
          path: users/create
          method: get
```

That should do the trick! Let me know if it solves the problem or you're facing other issues!
