### ISSUE TITLE
Unresolved resource dependencies [RestApiApigEvent]

### ISSUE THREAD

**Issue by danielfosbery** [serverless/serverless#1822]
Hey guys. Firstly love the project, have been using it for our Lambda deployments since seeing the Lambda talk at the recent AWS London Summit and it has really simplified things for us.

I'm getting an error when trying to deploy a project that has a resource that uses `{ "Ref" : "RestApiApigEvent" }`. This only happens when trying to deploy a new project with this reference, it seems to work fine if the resource that uses the Ref is added after the first deployment.

##### Serverless Framework Version: 
Beta1

##### Operating System: 
OSX 10.11.6

##### Expected Behavior:
This should create the 'partnerPostOrder' Lambda function as well as adding the 'AWS::ApiGateway::BasePathMapping'

##### Actual Behavior:
I'm getting the following error when running the first deploy with a 'AWS::ApiGateway::BasePathMapping' resource

`Template format error: Unresolved resource dependencies
     [RestApiApigEvent] in the Resources block of the template`

Now this only happens on the initial deploy. If I remove the 'AWS::ApiGateway::BasePathMapping', then deploy it obviously works fine. However after this initial deploy with just the Lambda function, if I add the BasePathMapping resource back into the yaml file and then deploy again everything works fine, both the Lambda function is deployed and the BasePathMapping resource is created correctly without any errors.

This is my serverless.yaml file.

```
service: api-hooks
provider:
    name: aws

defaults:
    stage: dev
    region: eu-west-1
    memory: 512
    timeout: 5

functions:
    partnerPostOrder:
        handler: lib/functions/partner/order-status.handler
        events:
            - http:
                path: partner/order-status
                method: POST

resources:
    Resources:
        APIDomainMapping:
            Type: AWS::ApiGateway::BasePathMapping
            Properties:
                BasePath: hooks
                DomainName: ${domain}
                RestApiId: { "Ref" : "RestApiApigEvent" }
                Stage: ${stage}
```

##### Stack-Trace (Optional):
```
ValidationError: Template format error: Unresolved resource dependencies [RestApiApigEvent] in the Resources block of the template
    at Request.extractError (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/query.js:40:29)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> `(/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)`
```

**Comment by flomotlik** [comment]
@danielfosbery this is a known but yet unresolved feature. The problem is that we're using the custom resource upon initial stack creation (when it should really only have the S3 bucket in it). When you reference resources that we'll create in a later step this will fail.  #1783 is resolving this, but we'll have to jump on this one soon as its a big issue

**Comment by danielfosbery** [comment]
Brilliant, looks like its on its way to being sorted. Thanks @flomotlik, keep up the good work!

**Comment by flomotlik** [comment]
@danielfosbery can you look into the latest beta and how we're merging resources now? Basically everything should be working fine now.

**Comment by danielfosbery** [comment]
All works as expected. Thanks @flomotlik !

**Comment by jetheurer** [comment]
I'm a little confused on how to use this feature in `1.0.0-rc.1`.  Right now my `serverless.yml` looks like:
```
resources:
  Resources:
    APIDomainMapping:
        Type: AWS::ApiGateway::BasePathMapping
        Properties:
            BasePath: ${opt:stage}
            DomainName: ####
            RestApiId:
              Ref: RestApiApigEvent
            Stage: ${opt:stage}
```

I'm not sure how to reference the `RestApiId`
