### ISSUE TITLE
functions can't be renamed without modifying the path

### ISSUE THREAD

**Issue by wxs** [serverless/serverless#1828]
Say I have a function defined in serverless.yml;

```
functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: hello
         method: get
```

and I decide to rename the function but keep it living at the same HTTP path.

```
  helloGetFoo:
    handler: handler.hello
    events:
     - http:
         path: hello
         method: get
```

Serverless will fail when I try to deploy.

##### Serverless Framework Version: 
1.0.0-beta.1

##### Operating System: 
Mac OS X 10.11.6 

##### Expected Behavior:

Everything deploys just fine.

##### Actual Behavior:

```
Serverless: Zipping service...
Serverless: Removing old service versions...
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your cloudformation:
     The following resource(s) failed to create: [ResourceApigEventHellogetfooHello,
     helloGetFoo].
 
```

##### Drawbacks:

* Can't rename functions
