### ISSUE TITLE
Extended event definitions don't deploy

### ISSUE THREAD

**Issue by Lepozepo** [serverless/serverless#1848]
Bug Report Template -----------------------------------------------

##### Expected Behavior:
Using the http syntax described [here](https://github.com/serverless/serverless/blob/master/docs/guide/overview-of-event-sources.md#http-endpoint) should create an HTTP endpoint

##### Actual Behavior:
The syntax does not create an HTTP endpoint.

**Comment by pouledodue** [comment]
did you doublecheck indentation

**Comment by Lepozepo** [comment]
```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
        path: greet
        method: get
```
I did >_< is two spaces ok? Should I use tabs instead?

**Comment by pouledodue** [comment]
you are missing spaces before path and method ^^

**Comment by pmuens** [comment]
Yep @pouledodue is right.

The correct syntax should be:
```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: greet
          method: get
```
