### ISSUE TITLE
Unable to override AuthorizationType in YML

### ISSUE THREAD

**Issue by DanielRuskin1** [serverless/serverless#1851]
Bug Report Template -----------------------------------------------

##### Serverless Framework Version
`1.0.0-beta.1.1`

##### Operating System
OSX

##### Expected Behavior: 
`AuthorizationType` should be `AWS_IAM` for the `PostMethodApigEventCreatecontactformfunctionContactformsCreate` method.

##### Actual Behavior: 
`AuthorizationType` is NONE.

##### My serverless.yml

```
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: form-service 

provider:
  name: aws
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "ec2:CreateNetworkInterface"
      Resource: "*"
  runtime: nodejs4.3
defaults:
  stage: dev
  region: us-west-2

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  createContactFormFunction:
    name: ${prefix}-createContactForm
    handler: handler.createContactForm
    events:
      - http:
          path: contact_forms/create
          method: POST
          cors: true
    vpc:
      securityGroupIds:
        - sg-12345
      subnetIds:
        - subnet-12345
        - subnet-12345
        - subnet-12345

resources:
  Resources:
    PostMethodApigEventCreatecontactformfunctionContactformsCreate:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: ResourceApigEventCreatecontactformfunctionContactformsCreate
        RestApiId:
          Ref: RestApiApigEvent
        HttpMethod: POST
        AuthorizationType: AWS_IAM
        MethodResponses:
          - StatusCode: 200
          - StatusCode: 400
          - StatusCode: 500
        Integration:
          IntegrationHttpMethod: POST
          Credentials: arn:aws:iam::*:user/*
          Type: AWS
          Uri:
            Fn::Join:
              - ""
              -
                - "arn:aws:apigateway:"
                - Ref: "AWS::Region"
                - ":lambda:path/2015-03-31/functions/"
                - Fn::GetAtt:
                  - createContactFormFunction
                  - Arn
                - "/invocations"
          RequestTemplates:
            application/json: |
              #define( $loop )
                {
                #foreach($key in $map.keySet())
                    "$util.escapeJavaScript($key)":
                      "$util.escapeJavaScript($map.get($key))"
                      #if( $foreach.hasNext ) , #end
                #end
                }
              #end
              {
                "body": $input.json("$"),
                "method": "$context.httpMethod",
                "principalId": "$context.authorizer.principalId",
                #set( $map = $input.params().header )
                "headers": $loop,
                #set( $map = $input.params().querystring )
                "query": $loop,
                #set( $map = $input.params().path )
                "path": $loop,
                #set( $map = $context.identity )
                "identity": $loop,
                #set( $map = $stageVariables )
                "stageVariables": $loop
              }
          IntegrationResponses:
            - 
              StatusCode: 200
              SelectionPattern: "^(?![\\s\\S])"
            - 
              StatusCode: 400
              SelectionPattern: "^400$"
            - 
              StatusCode: 500
              ResponseTemplates:
                application/json: "{\"success\": false, \"errors\": { \"UNKNOWN_ERROR\": [\"An unknown error occurred.\"] }}"

```
