### ISSUE TITLE
Redesign CF Logical ID's of all resources we create

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1869]
At the moment we don't have consistent CF logical ID naming across Serverless. This leads to various issues where resources are recreated when methods are renamed or resources can't be deployed because they already exist but under a different name.

Before the V1 release we need to have a consistent naming scheme for CF resources and we need to document them everywhere.

Items to check:

- [ ] Function Compilation
- [ ] S3 Event
- [ ] SNS Event
- [ ] API Gateway Event
- [ ] Scheduled Event

**Comment by nickchisiu** [comment]
I suggest having a persistent UUID ( v4 or v5 ) for every function on serverless.yml , this can be added automatically when a new template it's created as : 

```
functions:
  helloThere:
    uuid: 123e4567-e89b-12d3-a456-426655440000
    handler: handler.hello
```

And for the current function the resource id can be constructed as :

 S3 Event - `123e4567-e89b-12d3-a456-426655440000-Resource-S3`
 SNS Event - `123e4567-e89b-12d3-a456-426655440000-Resource-SNS`
 API Gateway Event - `123e4567-e89b-12d3-a456-426655440000-Resource-Apig`
 Scheduled Event - `123e4567-e89b-12d3-a456-426655440000-Resource-ScheduledEvent`

This way resources can be traced and checked later on AWS even for multiple purposes and further to other micro services clouds like Azure , Google, etc..

A quick suggestion for an implementation plan would be : 
- generate uuid on template creation
- require every function to have an unique uuid
- check functions before deployment for uuid duplicity ( in case developer used copy/paste to create a function or added it manually with an already existent uuid )
- integrate uuid logical id creation for all resources ( S3, SNS, API gateway, Scheduled Event)
- add tests for the new logical ids algorithm

**Comment by nicka** [comment]
>@flomotlik At the moment we don't have consistent CF logical ID naming across Serverless. This leads to various issues where resources are recreated when methods are renamed or resources can't be deployed because they already exist but under a different name.

I have the feeling that we're making it harder than it actually is. What's the issue with renaming methods and having new resources created and old ones removed? CF is pretty good at this.

### Let's think about the use case:
From the UX point of view users want to create multiple endpoints/events/triggers and don't care about the naming/renaming. The only issue would be when they wan't to overwrite a specific resource which normally would be generated by the framework. In this case I would like to be able to specify a specific identifier(logical-id for AWS) and use the same identifier(resource name) within the `resources:` section. CF will always create/update resources prior to removing them.

---

### Proposal 1

However I do agree that we should stick to a standard way of naming CF template.

Example:
```yaml
functions:
  users:
    handler: handler.users
    events:
      - http:
          path: users
          method: get
      - http:
          path: users/:id/likes # Not sure if :id actually works...
          method: get
      - http:
          path: users
          method: post
```

Resources:
  - `UsersFunction` Users based on the function name, Function based on functions
  - `UsersGetHttp` Users based on the path, Get based on the method, Http based on event type
  - `UsersIdLikesGetHttp` UsersIdLikes based on the path, Get based on the method, Http based on the event type
  - `UsersPostApiGetHttp` Users based on the path, Post based on the method, Http based on the event type

---

### Proposal 2

Specific identifier key.

Example:
```yaml
functions:
  users:
    handler: handler.users
    events:
      - http:
          identifier: users-all
          path: users
          method: get
      - http:
          identifier: users-likes
          path: users/:id/likes # Not sure if :id actually works...
          method: get
      - http:
          identifier: users-create
          path: users
          method: post
```

Resources:
  - `UsersAll`
  - `UsersLikes`
  - `UsersCreate`
