### ISSUE TITLE
Cannot add multiple http endpoints to single function

### ISSUE THREAD

**Issue by brendanmckenzie** [serverless/serverless#1908]
##### Serverless Framework Version: 
1.0.0-beta.2

##### Operating System: 
OSX 10.11.6

##### Expected Behavior:

Added two `-http` endpoints to a function (see below), received an error on deployment.

```
functions:
  getProfile:
    handler: handler.getProfile
    events:
      - http:
          path: user/{id}/profile
          method: get
          cors: true
      - http:
          path: user/profile
          method: get
          cors: true
```

##### Actual Behavior:

```
$ sls deploy
Serverless: Zipping service...
Serverless: Removing old service versions...
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
.. 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your cloudformation:
     The following resource(s) failed to create: [ResourceApigEventGetprofileUserProfile,
     PreflightMethodApigEvent0]. The following resource(s)
     failed to update: [getProfile]. 
```
