### ISSUE TITLE
"Invalid permissions on Lambda function"

### ISSUE THREAD

**Issue by DanielRuskin1** [serverless/serverless#1913]
##### Serverless Framework Version: 
`1.0.0-beta.2`

##### Operating System: 
OSX

##### Expected Behavior:
When making a request via API Gateway, it should correctly direct it to the Lambda function.

##### Actual Behavior:
API gateway logs an error: "Execution failed due to configuration error: Invalid permissions on Lambda function".

##### `serverless.yml` file

```
service: form-service 

provider:
  name: aws
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces" 
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  runtime: nodejs4.3
defaults:
  stage: dev
  region: us-west-2

functions:
  createContactFormFunction:
    name: ${prefix}-createContactForm
    handler: handler.createContactForm
    events:
      - http:
          path: contact_forms/create
          method: POST
          cors: true
    vpc:
      securityGroupIds:
        - REDACTED_ID
      subnetIds:
        - REDACTED_ID
        - REDACTED_ID
        - REDACTED_ID

resources:
  Resources:
    PostMethodApigEventCreatecontactformfunctionContactformsCreate:
      Type: AWS::ApiGateway::Method
      Properties:
        AuthorizationType: AWS_IAM
        MethodResponses:
          - StatusCode: 200
          - StatusCode: 400
          - StatusCode: 500
        Integration:
          Credentials: arn:aws:iam::*:user/*
          IntegrationResponses:
            - 
              StatusCode: 200
              SelectionPattern: "^(?![\\s\\S])"
            - 
              StatusCode: 400
              SelectionPattern: "^400$"
            - 
              StatusCode: 500
              ResponseTemplates:
                application/json: "{\"success\": false, \"errors\": { \"UNKNOWN_ERROR\": [\"An unknown error occurred.\"] }}"
```
