### ISSUE TITLE
How can I enable logging in API Gateway?

### ISSUE THREAD

**Issue by wei-xu-myob** [serverless/serverless#1918]
I want to know the proper way to enable logging in Api Gateway Stage.

AWS CloudFormation support it by using resource type AWS::ApiGateway::Stage, I can define the customized resource, but it requires two parameter "DeploymentId" and "RestApiId" which are dynamically generated in serverless.

Any suggestions on how to enable it? 

the CloudFormation doc I'm referencing is http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html

Thanks

**Comment by flomotlik** [comment]
@wei-xu-myob Take a look at Custom provider resources: https://github.com/serverless/serverless/blob/master/docs/guide/custom-provider-resources.md#adding-custom-provider-resources

You can overwrite anything we create in the Cloudformation template easily there. I'm going to close this one as its more of a support request and is better suited to our [Forum](forum.serverless.com)

**Comment by nzmkey** [comment]
For those who look for a solution here is what I have done:

1. Install the [serverless-plugin-stage-variables](https://github.com/svdgraaf/serverless-plugin-stage-variables) which will sort out the "DeploymentId" and "RestApiId" for you.
2. Follow [custom-provider-resources](https://github.com/serverless/serverless/blob/master/docs/01-guide/06-custom-provider-resources.md) to add your stage setting.

EG, below is an example of serverless.yml to enable logging:
 ```yml
service: lambda-blah
custom:
  stageVariables:
    env: ${self:provider.stage} 
plugins:
  - serverless-plugin-stage-variables
provider: aws
functions:
  ...
resources:
  Resources:
    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        MethodSettings:
          - DataTraceEnabled: true
          - LoggingLevel: INFO
          - MetricsEnabled: true
```

There is a bug in serverless-plugin-stage-variables which will overwrite what custom-provider-resources does.  There is a [pull request](https://github.com/svdgraaf/serverless-plugin-stage-variables/pull/4) waiting.

**Comment by jacob-meacham** [comment]
As an alternative to the method described by @nzmkey above, I've created a plugin, https://github.com/jacob-meacham/serverless-plugin-bind-deployment-id, which exposes the randomly generated deployment resource to your custom resources. This lets you write something like this:

```
PathMapping:
  Type: AWS::ApiGateway::BasePathMapping
  DependsOn: __deployment__
  Properties:
    BasePath: analytics
    DomainName: ${self:provider.domain}
    RestApiId:
      Ref: ApiGatewayRestApi
    Stage: ${self:provider.stage}
__deployment__:
   Properties:
      StageSettings:
          DataTraceEnabled: true
          MetricsEnabled: false
ApiGatewayStage:
  Type: AWS::ApiGateway::Stage
  Properties:
    DeploymentId:
      Ref: __deployment__
    RestApiId:
      Ref: ApiGatewayRestApi
    StageName : ${self:provider.stage}
    MethodSettings:
      - DataTraceEnabled: false
        HttpMethod: "GET"
        LoggingLevel: INFO
        ResourcePath: "/foo"
        MetricsEnabled: false
```
