### ISSUE TITLE
feature: CORS Allow-Origins configured once for all HTTP APIs in project

### ISSUE THREAD

**Issue by jokeyrhyme** [serverless/serverless#1930]
##### Feature Request:

- CORS Allow-Origins configured once for all HTTP APIs in project

- perhaps under "defaults", e.g.

```yml
defaults:
  events:
    http:
      cors:
        origins:
          - 'http://localhost:4000'
          - 'https://example.surge.sh'
```

- all HTTP event handler configurations inherit the `cors.origins` values

- this can still be overridden on a per-handler basis by using the current configuration approach: https://github.com/serverless/serverless/tree/master/lib/plugins/aws/deploy/compile/events/apiGateway#enabling-cors-for-your-endpoints

- `cors: false` can be used to completely opt-out of these defaults and explicitly disable CORS as per the current configuration approach

##### Benefits:

- the CORS Allow-Origins setting is likely to be the same across all HTTP APIs, so this saves an incredible amount of copy-pasting and error-prone maintenance

##### Drawbacks:

- settings that affect a particular HTTP API are no longer all collected together in the one place

**Comment by pmuens** [comment]
@jokeyrhyme thanks. That's a really good idea.

However we're about to drop the `defaults` property soon. So we might to think about a different place. Any ideas @eahefnawy ?

**Comment by eahefnawy** [comment]
@jokeyrhyme You can make use of the upcoming variable system to have this functionality for reusability. You can just use `self.defaults.cors` or something. Checkout #1834 ☺️

**Comment by jokeyrhyme** [comment]
@eahefnawy ah, okay. So I could do something like...

cors.yml:

```yml
origins:
  - 'http://localhost:4000'
  - 'https://example.surge.sh'  
```

serverless.yml:

```yml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: user/create
          method: get
          cors: ${file(./cors.yml).data.subProp}
```

??

**Comment by jokeyrhyme** [comment]
This substitution is very powerful. This probably addresses some of the other ideas I have, too. :D

**Comment by flomotlik** [comment]
We can probably put this into `provider` as well in the future, though I'd like to have it through the var system at first.

@jokeyrhyme you can also do the following so its in the same file (vars in this case is a custom thing you set up, not defined by us so you can call it anything):

```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: user/create
          method: get
          cors: ${self.vars.cors}
vars:
  cors:
    origins:
      - 'http://localhost:4000'
      - 'https://example.surge.sh' 
```
