### ISSUE TITLE
Function Role Requires CreateNetworkInterface Permission

### ISSUE THREAD

**Issue by jtrefry** [serverless/serverless#1966]
##### Serverless Framework Version: 
1.0.0-beta.2

##### Operating System: 
Windows 10 Home

##### Expected Behavior:
Deploy command configures Cloud Formation for serverless.yaml file containing a Lambda function with http event and vpc configuration.

```yaml
service: foo-api

defaults:
  stage: dev
  region: us-west-2

provider:
  name: aws
  runtime: nodejs4.3

functions:
  foo:
    name: ${prefix}foo
    handler: handler.foo
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: ${prefix}foo
          method: POST
    vpc:
      securityGroupIds:
        - sg-xxxxxxxx
      subnetIds:
        - subnet-xxxxxxxx
        - subnet-xxxxxxxx
        - subnet-xxxxxxxx
```

##### Actual Behavior:
An error occurred while provisioning your cloudformation:
     The following resource(s) failed to update: [function name]. 

AWS Cloud Formation Error:
Your access has been denied by EC2, please make sure your function execution role have permission to 
*CreateNetworkInterface*.  EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation.

##### Work-Around:
Temporarily attach AdministratorAccess policy to the function execution role that was created by the serverless deploy command. Run deploy command. Remove AdministratorAccess policy from the function execution role.
