### ISSUE TITLE
Deploy failing when passing configuration object to authorizer

### ISSUE THREAD

**Issue by olistic** [serverless/serverless#1976]
# This is a Bug Report

## Description

Function deploy is failing when passing a configuration object to the `authorizer` key, as explained [here](https://github.com/serverless/serverless/tree/master/lib/plugins/aws/deploy/compile/events/apiGateway#http-setup-with-custom-authorizer).

Using this config:

```yml
# serverless.yml
functions:
  authorizer:
    handler: handler.authorizer
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          authorizer:
            name: authorizer
            identitySource: method.request.header.Authorization
```

And running `$ sls deploy`, results in:

```
Serverless: Zipping service...
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
... 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your cloudformation:
     The following resource(s) failed to create: [authorizerAuthorizer].
     
 
  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

## Additional Data

* ***Serverless Framework Version you're using:*** 1.0.0-beta.2
* ***Operating System:*** OS X El Capitan (version 10.11.6)
