### ISSUE TITLE
api_gateway cors custom headers not pushed to aws

### ISSUE THREAD

**Issue by yonahforst** [serverless/serverless#1984]
# This is a (Bug Report / Feature Proposal)
Bug Report

## Description
I'm setting custom cors headers as described in [the documentation](https://github.com/serverless/serverless/blob/85f4084e6b0fd4a6d763ace8cd0db82817bbc712/lib/plugins/aws/deploy/compile/events/apiGateway/README.md#enabling-cors-for-your-endpoints) but they don't appear in the method's IntegrationResponse/HeaderMappings

I think the problem is here, these lines should be removed: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js#L61-L62

For bug reports:
* What went wrong?
my custom headers did not appear in the method's IntegrationResponse/HeaderMappings (the additional origin did)
![screen shot 2016-08-30 at 6 36 16 pm](https://cloud.githubusercontent.com/assets/1440796/18097965/843b3182-6ee0-11e6-9f1d-2f615af8ca16.png)

* What did you expect should have happened?
either the specified headers should have been merged with the defaults, or replaced them completely. 
* What was the config you used?
```yml
httpDefaults: &http_defaults
  method: get
  private: true
  cors:
    origins:
      - '*'
      - 'example.com'
    headers:
      - x-user-id

functions:
  updateTicket:
    handler: functions/tickets.updateTicket
    events:
      - http:
          << : *http_defaults
          path: tickets/{ticket_id}
          method: put
```

Similar or dependent issues:
* #1960

## Additional Data

* ***Serverless Framework Version you're using:***
1.0.0-beta.2
* ***Operating System:***
osx - el capitan
