### ISSUE TITLE
Support Function level Includes/Excludes

### ISSUE THREAD

**Issue by tpj800** [serverless/serverless#1986]
# Question
Is it possible to specify `includes` and `excludes` on a function level in v1.0?

# Background
I have a number functions, each with an endpoint in a single API.  Some have very little shared code (`node_modules` or `site-packages` for python code) others have a lot. As in, enough to reach the limit for lambda zip packages.  I dont want to include the large functions in the package of the small ones.

Using serverless 0.5.x I could include various levels of shared code by using subdirectory reference like so:

```
handler: functions/maker/handler.handler,
```

Or, for small packages not requiring shared code:

```
handler: handler.handler,
```

I could also use `excludePatterns` in the `s-function.json` to trim down the  uploaded package for each function.

It may be a reasonable argument that such different functions should be in different *services* but suppose I want to deploy them together. Is this possible with the new version of serverless?

# Proposal

1. Have a root `serverless.yml` which remains the same spec as it currently is.
2. Allow function level `serverless.yml` (perhaps `function.yml`) files which may only contain:

```
package:
  include:
    -  dir1/
  exclude:
    - dir2/

functions:
  funct1:
    handler: handler.helloworld
    memorySize: 512
    ...
```
