### ISSUE TITLE
Not all Lambda Permissions are actually set by CFN

### ISSUE THREAD

**Issue by kmfk** [serverless/serverless#1995]
# Permissions not getting set when using many event sources (ie, SNS Topics)
## Description

This is actually currently a bug in AWS / Lambda which was confirmed by AWS Support.

From Support:

> I looked into the issue and found out there is currently a bug with the way Lambda handles multiple (parallel) requests to add permissions. A current workaround is using the DependsOn[1] attribute to force CFN to send the requests one at a time. This will remove the parallel creation of these permissions (it might take a little longer to create than before), but it should prevent the issue from happening (example below). You will need to chain the dependencies to each permission ( each permission is dependent on the last one).

This typically materializes when you have many event sources on one function, using SNS Topics as an example, ie:

```
functions:
  func1:
    handler: handler.handle
    events:
     - sns: my-topic-1
     - sns: my-topic-2
     - sns: my-topic-3
     - sns: my-topic-4
     - sns: my-topic-5
     - sns: my-topic-6
     - sns: my-topic-7
     - sns: my-topic-8
     - sns: my-topic-9
     - sns: my-topic-10
```

The correct `AWS::Lambda::Permission` resources get added to the CFN template and CFN will even show all items as correctly created, but the resultant Lambda policy will be missing some at random due to the bug referenced above.

I think it would be worth adding the `DependsOn` to the Permissions until this is resolved by AWS.  I'd think a listener on the `deploy:compileEvents` hook that runs last could iterate through the `AWS::Lambda::Permission` type resources and append the `DependsOn` accordingly for the item listed before it.

I'm not opposed to working on a PR to address this.  In the interim, will probably just handle it via a plugin.

**Comment by kmfk** [comment]
Will mention that I did do a quick listener on `after:deploy:compileEvents` to force those `DependsOn` statements in a plugin we already had:

```
afterCompileEvents() {
    this.serverless.cli.log("Appending DependsOn statements for Lambda Permissions...");

    let template = this.serverless.service.provider.compiledCloudFormationTemplate;

    let dependsOn = null;
    for (let key in template.Resources) {
        let resource = template.Resources[key];
        if ('AWS::Lambda::Permission' == resource.Type) {
            if (null !== dependsOn) {
                resource.DependsOn = [dependsOn];
            }

            dependsOn = key;
        }
    }
}
```

It definitely increased the deploy process (via CFN) by about 200%...

**Comment by flomotlik** [comment]
We're currently looking into this for our 1.2 milestone and will check this out to make sure it works fine.

**Comment by pmuens** [comment]
Hey @kmfk thanks for reporting and for adding a code snippet to resolve this bug! 👍  💯 

Do you have any references how many different resources it takes to force the bug to happen? Would be interesting to see if this bug comes up quite often or if this is an edge case right now.

Not sure if we should address this right now, because a 200% increase in deployment time is huge.

@eahefnawy @flomotlik what do you think about this?

**Comment by kurtmaile** [comment]
Awesome work guys - will this make the 1.2 milestone (tomorrow?) - its affecting us  at the moment (weve a fair number of services and dependant resources)  Think an increase in deployment time is better then having this an issue.

Cheers

**Comment by kmfk** [comment]
@pmuens This is somewhat arbitrary, but typically if we only had a handful of event sources (1-5), it seemed like it would properly add all of them - after 5, it was intermittent.  The more event sources you added after that, the more likely you'd run into the issue.

You could try and avoid the dependsOn statements if the overall count of event sources is low, but I'm not sure how reliable that'd be.

Also, I agree with @kurtmaile -  I'd much rather wait and be sure it works correctly and this should only be an issue on initial deployments where event sources are added.

**Comment by pmuens** [comment]
Hey guys!

Any chance to get a `serverless.yml` so that we can reproduce this bug. I tried the SNS setup @kmfk posted but didn't faced this bug during deployment.

I just opened up a PR with the fixes from @kmfk to resolve this issue --> https://github.com/serverless/serverless/pull/2704. However if you try it (with the `serverless.yml` file in the PR description) you'll run into an error when you use `s3` events.

**Comment by pmuens** [comment]
My current thought about this is that we should add a `DependsOn` which points to the resource of the created event type in the `permission`.

E.g. add a `DependsOn` to the permission for the SNS event which points to the SNS resource which it belongs to. This way we ensure that the permission is created when the event is created.

**Comment by pmuens** [comment]
Moving this one out of the current milestone. We'll tackle it again once we can reproduce it

/cc @eahefnawy

**Comment by connaryscott** [comment]
I seem to have an inline policy limitation?   I see, as a result of 8 SNS subscriptions:

```
  event-collector:
    handler: handler_actions.event_collector
    name: ${self:service}-event-collector-${self:custom.stage}
    environment:
      TABLE_NAME: ${self:service}-${self:custom.stage}-${self:custom.region}
    events:
      - sns: ${self:service}-error-${self:custom.stage}
      - sns: ${self:service}-retrieve-${self:custom.stage}
      - sns: ${self:service}-create-stack-${self:custom.stage}
      - sns: ${self:service}-delete-stack-${self:custom.stage}
      - sns: ${self:service}-compile-${self:custom.stage}
      - sns: ${self:service}-deploy-${self:custom.stage}
      - sns: ${self:service}-destroy-${self:custom.stage}
      - sns: ${self:service}-deploy-notify-${self:custom.stage}
```

 that one of my functions has a policy size that is conspicuously at 2401 bytes and two sns topics will not trigger this lambda function.   Could this be a reason on why some folks get this type of trouble?
