### ISSUE TITLE
APIG events now force both json and form-urlencoded templates

### ISSUE THREAD

**Issue by anreved** [serverless/serverless#1999]
# This is a Feature Proposal
## Description

When defining APIG http events the code now forces creation of mappings for both `application/json` as well as `application/x-www-form-urlencoded`.  While you can override the template, there is no way to **exclude** these mappings (i.e., I only want to allow json requests on an endpoint)

This change was recently introduced via [this commit](https://github.com/serverless/serverless/commit/d6d2f83bee520721c650b0b87cc5789f0836c2c2#diff-194d3970cc4b47abac5ae6c1a66059c1) into [lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/apiGateway/lib/methods.js):

``` javascript
const integrationRequestTemplates = {
  'application/json': DEFAULT_JSON_REQUEST_TEMPLATE,
  'application/x-www-form-urlencoded': DEFAULT_FORM_URL_ENCODED_REQUEST_TEMPLATE,
};
```

While I think it's incredibly useful to have these 2 options (and templates pre-defined), I think it would be best to allow the user to optionally include only the templates they want.

Something like the following might make sense:

``` yml
functions:
  create:
    handler: posts.create
    events:
      - http:
          method: get
          path: whatever
          request:
            template:
              text/xhtml: { "stage" : "$context.stage" }   # add additional template
              application/json: { "httpMethod" : "$context.httpMethod" }  # add mapping and override default template
              application/x-www-form-urlencoded: true    # add mapping and use default template 
```

With the current open issue (#1168) around APIG pass through behavior, and a pending PR (#1992) to address it, this becomes more important to be able to fully restrict methods to desired Content-Types.
