### ISSUE TITLE
deploy does not update lambda code

### ISSUE THREAD

**Issue by fiducioso-dan** [serverless/serverless#2003]
# This is a Bug Report

## Description

I'm developing a Java based project with serverless. When I rebuild my distribution .zip and run `serverless deploy` the lambda code does not update.

```
$ gradle build # rebuild .zip
...
BUILD SUCCESSFUL
...
$ openssl dgst -sha256 -binary build/distributions/func.zip | openssl enc -base64 # calculate new function code checksum
ZDEZ/DsT2VkKXwrnV8qbqh4RzHyzv5cgT4//iq9ceq4=
$ aws lambda get-function --function-name func-ss-dev-func --query Configuration.CodeSha256 --output text # show existing function code checksun
sSKcUhBI8JEEkpDVhNy4tJkoMvAaBsM8WFnQM8Pc17k=
$ serverless deploy
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
..........................
Serverless: Deployment successful!

Service Information
service: func-ss
stage: dev
region: us-east-1
endpoints:
  POST - https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/func
functions:
  func-ss-dev-func: arn:aws:lambda:us-east-1:111111111111:function:func-ss-dev-func

$ aws lambda get-function --function-name func-ss-dev-func --query Configuration.CodeSha256 --output text # show "new" code checksum
sSKcUhBI8JEEkpDVhNy4tJkoMvAaBsM8WFnQM8Pc17k=
```

Expected the CodeSha256 to update to the locally calculated one, or change at all. Also executing the function shows the code is stale.

My serverless.yml looks like this:

```
package:
  artifact: build/distributions/func.zip

functions:
  func:
    handler: com.fiducioso.xxxxxxxxxxxx.LambdaHandler::apiGateway
    memorySize: 128
    events:
      - http:
          path: func
          method: post
```

## Additional Data

* ***Serverless Framework Version you're using:***
1.0.0-beta2
* ***Operating System:***
Ubuntu 16.04 LTS
Node 4.5.0
