### ISSUE TITLE
[BUG] When we deploy, no apigw endpoints are created (aws).

### ISSUE THREAD

**Issue by jdavidls** [serverless/serverless#2010]
# This is a Bug Report

## Description

When we deploy the mos simple starting service, sls do not build any ApiGateway endpoint.

Bug steps:

1. We have started wich v1-beta.2, creating a service following the instructions (`sls create -t aws-nodejs`).

2. undocumenting the relevant lines, we have the following serverles.yml fragment:
    ```yaml
    functions:
      hello:
        handler: handler.hello
        events:
          - http:
    	      path: users/create
    		  method: get
    ```
    the yaml file are checked with `js-taml serverless.yml` to see if we had any fault in the format (It was what I suspected at first), the result is as follows:

    ```json
    {
      "service": "aws-nodejs",
      "provider": {
        "name": "aws",
        "runtime": "nodejs4.3"
      },
      "functions": {
        "hello": {
          "handler": "handler.hello",
          "events": [
            {
              "http": {
                "path": "users/create",
                "method": "get"
              }
            }
          ]
        }
      }
    }
    ```

3. Finally, we run `sls deploy` with following output:
    ```
    Serverless: Creating Stack...
    Serverless: Checking stack creation progress...
    ......
    Serverless: Stack successfully created.
    Serverless: Zipping service...
    Serverless: Uploading .zip file to S3...
    Serverless: Updating Stack...
    Serverless: Checking stack update progress...
    ................
    Serverless: Deployment successful!
    
    Service Information
    service: aws-nodejs
    stage: dev
    region: us-east-1
    endpoints:
      None                  <-- something not working
    functions:
      aws-nodejs-dev-hello: arn:aws:lambda:us-east-1:############:function:aws-nodejs-dev-hello
    ```

We are doing any wrong or this is really a strange bug?

**I forgot to mention**, we have reproduced the same steps with _alpha.2_ version obtaining good results.

## Additional Data
CloudFormation Template:
```json
{  
   "AWSTemplateFormatVersion":"2010-09-09",
   "Description":"The AWS CloudFormation template for this Serverless application",
   "Resources":{  
      "ServerlessDeploymentBucket":{  
         "Type":"AWS::S3::Bucket"
      },
      "IamRoleLambda":{  
         "Type":"AWS::IAM::Role",
         "Properties":{  
            "AssumeRolePolicyDocument":{  
               "Version":"2012-10-17",
               "Statement":[  
                  {  
                     "Effect":"Allow",
                     "Principal":{  
                        "Service":[  
                           "lambda.amazonaws.com"
                        ]
                     },
                     "Action":[  
                        "sts:AssumeRole"
                     ]
                  }
               ]
            },
            "Path":"/"
         }
      },
      "IamPolicyLambda":{  
         "Type":"AWS::IAM::Policy",
         "Properties":{  
            "PolicyName":"dev-aws-nodejs-lambda",
            "PolicyDocument":{  
               "Version":"2012-10-17",
               "Statement":[  
                  {  
                     "Effect":"Allow",
                     "Action":[  
                        "logs:CreateLogGroup",
                        "logs:CreateLogStream",
                        "logs:PutLogEvents"
                     ],
                     "Resource":"arn:aws:logs:us-east-1:*:*"
                  }
               ]
            },
            "Roles":[  
               {  
                  "Ref":"IamRoleLambda"
               }
            ]
         }
      },
      "hello":{  
         "Type":"AWS::Lambda::Function",
         "Properties":{  
            "Code":{  
               "S3Bucket":{  
                  "Ref":"ServerlessDeploymentBucket"
               },
               "S3Key":"aws-nodejs-1472982220810.zip"
            },
            "FunctionName":"aws-nodejs-dev-hello",
            "Handler":"handler.hello",
            "MemorySize":1024,
            "Role":{  
               "Fn::GetAtt":[  
                  "IamRoleLambda",
                  "Arn"
               ]
            },
            "Runtime":"nodejs4.3",
            "Timeout":6
         }
      }
   },
   "Outputs":{  
      "ServerlessDeploymentBucketName":{  
         "Value":{  
            "Ref":"ServerlessDeploymentBucket"
         }
      },
      "Function1Arn":{  
         "Description":"Lambda function info",
         "Value":{  
            "Fn::GetAtt":[  
               "hello",
               "Arn"
            ]
         }
      }
   }
}

```
* serverless 1.0.0-beta.2 (over node 4.4.7)

**Comment by flomotlik** [comment]
@jdavidls this is weird. Could you try installing the latest release with `npm install -g serverless/serverless` and retry?

**Comment by flomotlik** [comment]
Also thanks for the very detailed report. This definitely helps a lot!

**Comment by jdavidls** [comment]
Great @flomotlik, the latest version solves this problem, thank you very much for your attention and congratulations for your work. This bug can be closed as it seems to be solved.

**Comment by 5hanth** [comment]
this issue persists on `1.25.0` & `1.26` 

```
Service Information
service: my-service
stage: dev
region: us-east-1
stack: my-service-dev
api keys:
  None
endpoints:
  None
functions:
  hello: my-service-dev-hello
```

```yml
functions:
  hello:
    handler: handler.hello
	events:
	  - http: GET hello
```

any ideas?
