### ISSUE TITLE
Cloudformation Error when Adding new Lambda

### ISSUE THREAD

**Issue by fny** [serverless/serverless#2013]
Whenever I add a new endpoint as follows

```
  myNewFunction:
    handler: handler.debug
    memorySize: 128
    events:
      - http:
          path: my_new_function
          method: post
          cors: true
```

I see the following error during the deploy process

```
Serverless: Zipping service...
Serverless: Removing old service versions...
Serverless: Uploading .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking stack update progress...
..
  Serverless Error ---------------------------------------

     An error occurred while provisioning your cloudformation:
     The following resource(s) failed to create: [PreflightMethodApigEvent7,
     myNewFunction]. The following resource(s) failed to update:
     [myPrefFnA, myPrefFnB, myPrefFnC].

```
