### ISSUE TITLE
Encountered non numeric value for property AllocatedStorage

### ISSUE THREAD

**Issue by atwoodjw** [serverless/serverless#2048]
# This is a Bug Report

## Description
Provisioning stack fails when including a `AWS::RDS::DBInstance` resource type.

Using this config.

```yaml
# serverless.yml
resources:
  Resources:
    DBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 5,
        DBInstanceClass: db.t2.micro,
        DBName: devDb,
        Engine: postgres,
        MasterUsername: devUsername,
        MasterUserPassword: devPassword
      DeletionPolicy: Delete
```

```
Serverless Error ---------------------------------------

   An error occurred while provisioning your stack: DBInstance
   - Encountered non numeric value for property AllocatedStorage.
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.1
* ***Operating System***: OS X El Capitan 10.11.6 (15G31)
