### ISSUE TITLE
Variables not expanded in "provider" config section

### ISSUE THREAD

**Issue by fruffin** [serverless/serverless#2054]
# This is a Bug Report

## Description

* What went wrong?
I am trying to set up my lambda functions in a VPC. In v1.0-beta2 I just had my array of subnets and VPC ID in serverless.env.yml so that the right set of subnets was picked up.
All functions in my service are going to need this, so I have decided to configure this at the provider level instead of at the function level.

Since upgrading to RC1 and migrating to the new configuration system, it doesn't look like variables get expanded properly anymore. In my case, the subnetIds property doesn't get populated. I haven't tried with other properties of the "provider" object yet.

If I hardcode my array of subnets in the provider object in serverless.yml everything works fine, so I can confirm this is not a problem with the vpc configuration itself.

If I copy the vpc configuration from the "provider" object and move it to each of my function definitions, everything works fine and the variables get populated correctly, so this is not a syntax problem.

* What did you expect should have happened?

* What was the config you used?
This doesn't work:
```
custom:
  currentStage: ${opt:stage, self:provider.stage}
  currentRegion: ${opt:region, self:provider.region}
  currentEnvSettings: ${file(./serverless.env.yml):stages.${self:custom.currentStage}.regions.${self:custom.currentRegion}}
  VpcId: ${self:custom.currentEnvSettings.VpcId}
  SubnetIds: ${self:custom.currentEnvSettings.SubnetIds}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  vpc:
    securityGroupIds:
      - Ref: LambdaSecurityGroup
    subnetIds: ${self:custom.SubnetIds}
```

But this does:
```
functions:
  serviceA:
    handler: services.A
    memorySize: 128 # default is 1024
    timeout: 20
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds: ${self:custom.SubnetIds}
    events:
      - http:
          path: services/A/{param}
          method: get
```

As you can see, the VPC configuration is exactly the same at the provider and function level (I actually copy/pasted it)

* What stacktrace or error message from your provider did you see?
No error

## Additional Data

* ***Serverless Framework Version***: 1.0 RC1
* ***Operating System***: Windows
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

I've had a look at the code for the new configuration engine, but I'm not quite sure how everything hangs together yet. My gut feeling is that variables are parsed/loaded only after the provider section is parsed/loaded and this is just an ordering issue
