### ISSUE TITLE
Unable to create service with VPC configuration

### ISSUE THREAD

**Issue by mthenw** [serverless/serverless#2055]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Got error after running `serverless deploy` for new service

```
Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: xxx
     - Your access has been denied by EC2, please make sure
     your request credentials have permission to DescribeSecurityGroups
     for xxxx. EC2 Error Code: UnauthorizedOperation.
     EC2 Error Message: You are not authorized to perform
     this operation..

```

Usualy this error means that function role doesn't have enough permissions. But I put

```
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
```

Workaround for that is to comment `vpc` section, deploy then uncomment and deploy again.

* What was the config you used?

```
provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 1024
  timeout: 3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  vpc:
    securityGroupIds: xxx
    subnetIds: xxx
```
