### ISSUE TITLE
VPC attachment not working on initial deployment "Your access has been denied by EC2"

### ISSUE THREAD

**Issue by alekstr** [serverless/serverless#2064]
# This is a Bug Report

## Description

If you are attaching VPC for a function and initially deploying function - you'll get "Your access has been denied by EC2" with resource creation failed for Lambda function. This is due to Lambda need to have role assigned prior configuring VPC, however in Cloudformation template lambda function does not depend on Role resource - so in some cases role creation is not completed before lambda creation which leads to a failure.

serverless.yml config file:
```
service: test # NOTE: update this with your service name

provider:
    name: aws
    runtime: nodejs4.3
    iamRoleStatements:
        $ref: ../config/iamRolesDefinition.json

defaults:
    stage: dev
    region: eu-west-1

package:
    include:
        - ./lib
        - ./node_modules
        - ./config
functions:
    auth:
        handler: handler.main
        timeout: 120
        events:
            - http:
                path: das/auth
                method: post
                cors: true
        vpc:
            securityGroupIds:
                - sg-g1
            subnetIds:
                - subnet-1
                - subnet-2
```
iamRolesDefinition.json
```
[
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "ec2:DescribeInstances",
        "ec2:CreateNetworkInterface",
        "ec2:DescribeNetworkInterfaces",
        "ec2:DeleteNetworkInterface"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "dynamodb:*"
      ],
      "Resource": [
        "*"
      ]
    }
]
```
## How to reproduce

- Remove stack if exists (sls remove);
- Add VPC configuration int serverless.yml;
- Deploy function.

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-beta.2
* ***Operating System***: Red Hat Enterprise Linux Server release 6.7 (Santiago)

To fix issue - I've added "DependsOn" parameter into Function configuration:
aws/deploy/compile/functions/index.js after the line 79:
`
"DependsOn": "IamPolicyLambda",
`
This will require Lambda function to wait till Policy is created.
