### ISSUE TITLE
Self referenced variables don't allow for fallback

### ISSUE THREAD

**Issue by andymac4182** [serverless/serverless#2081]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 

When referencing a `self:` variable the `getDeepValue` function returns an empty object that means it doesn't fallback to the other option. 
* What did you expect should have happened?

It load the fallback value
* What was the config you used?
```
default:
  CorsOrigins: 
    - 'http://test.com'
currentVars:
  CorsOrigins: ${self:custom.${self:custom.currentStage}.CorsOrigins, self:custom.default.CorsOrigins}
  cors:
    origins: ${self:custom.currentVars.CorsOrigins}
```
* What stacktrace or error message from your provider did you see?
```
  Type Error ---------------------------------------------

     cors.origins.join is not a function
```

After changing https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js#L172 to ```valueToPopulate = undefined;``` the fallback option was loaded correctly. It appears that the `overwrite` function is checking for `undefined` or `null`. https://github.com/serverless/serverless/blob/master/lib/classes/Variables.js#L95

## Additional Data

* ***Serverless Framework Version you're using***: Master
* ***Operating System***: Win 10
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by eahefnawy** [comment]
@andymac4182 thanks for reporting this. This is an issue, but I think the solution is in the overwrite method to also overwrite if object is empty, something like this:

```js
return (typeof finalValue !== 'undefined' && finalValue !== null) && !_.isEmpty(finalValue);
```
could you try something like that in your PR instead? 😊 

This reverting to empty object when it's undefined "feature" is a fix for an issue reported by @flomotlik a while back that allows us to deeply/recursively check non existing sub properties without throwing `can't read property of undefined` error. In other words, it makes the following overwrite works:

```yml
custom:
  testA: i am a string not object
  testB: hello world
  testC: ${self:custom.testA.some.invalid.property, self:custom.testB}
```
Without this reverting to an empty object, we'd be trying to access the `invalid` sub property of an undefined `some` sub property, which of course throws an Error.
