### ISSUE TITLE
Provide a way to use the default request templates

### ISSUE THREAD

**Issue by WooDzu** [serverless/serverless#2085]
# This is a Feature Request

SLS should provide a way of exposing the default request template for other json-compatible formats such as `application/vnd.api+json` or even `application/vnd.books.example.com-api-v1.0+json`. 

```yml
functions:
  create:
    handler: posts.create
    events:
      - http:
          method: get
          path: whatever
          request:
            template:
              application/vnd.api+json: ?????
```

EDIT: Even if this is through a `${file(../../../node_modules/serverless/lib/templates/request.default.vm)}` that should do the job to for now.
