### ISSUE TITLE
plugin constructor options argument is longer populated in rc1

### ISSUE THREAD

**Issue by Bilal-S** [serverless/serverless#2093]
Change from beta2 to rc1.
Plugin init no longer populates options objects
````
class AwsInfo {
  constructor(serverless, options) {
````
options in beta two:
![beta2-options](https://cloud.githubusercontent.com/assets/668901/18422669/c4f86714-786b-11e6-8128-2906ab2d9cb3.PNG)

options in rc1:
![rc1-options](https://cloud.githubusercontent.com/assets/668901/18422675/ce3019e4-786b-11e6-8817-975be40ae219.PNG)

Configuration files were adjusted: rc1 config `serverless.yml` looks like this:
````
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2  
````
