### ISSUE TITLE
Corrupted bucket name   - Bucket name should not contain '['.

### ISSUE THREAD

**Issue by EnriqueGC** [serverless/serverless#2107]
# This is a Bug Report

## Description
When creating a bucket with a given name under the resources section will produce a bad CF script where the bucket's name will be replaced by ```[object Object]``` therefore the deployment will failing  with the error. 

```
 An error occurred while provisioning your stack: S3BucketObjectObject
     - Bucket name should not contain '['.

```
### Example: 
```
Resources:
  MyS3Bucket:
    Properties:
      BucketName: "eg-bucketname-346"
```
will be translated as 

```
"S3BucketObjectObject": {
	"Type": "AWS::S3::Bucket",
	"Properties": {
		 "BucketName": "[object Object]",
		"NotificationConfiguration": {
			"LambdaConfigurations": [{
				"Event": "s3:ObjectCreated:*",
				"Function": {
					"Fn::GetAtt": ["EchoLambdaFunction",
					"Arn"]
				}
			},
```

## Additional Data
* ***Operating System***:
OS: Windows 10
* ***Serverless Framework Version you're using***:
1.0.0-rc.1

**Comment by flomotlik** [comment]
I just tried it with this service and it worked fine:

```
service: test-service 

provider:
  name: aws

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "eg-bucketname-346"
```

Which compiles to:

```
"MyS3Bucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "eg-bucketname-346"
      }
    }
```

This looks more like a problem in the event configuration of an S3 bucket. Can you check the event config to see if there was a problem with the Echo function. I'll close for now as I don't think this is a bug, but please report back in case it is and I'll reopen.

**Comment by EnriqueGC** [comment]
understood, I'll do some research on my side and follow up if necessary

**Comment by EnriqueGC** [comment]
Here is my scenario: I want to create a bucket,( which eventually will host a static web site) any change in the bucket ( new object or removed) will trigger a lambda which should be able to write back to that  bucket.
Given that I would like to customize that bucket folder further I'm trying to create the bucket as a separate resource and not "implicitly" with the function for example:
This scenario works : ```BucketName: "eg-bucketname-346```
This case fails: 
 ``` 
 bucket: 
              - "Ref" : "MyS3Bucket"
```

Hopefully I'm doing something wrong

Here is a full example where you can replicate the error:

```
service: T52

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
      - Effect: "Allow"
        Action:
           - "s3:*"
        Resource: "*"

Resources:
 MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: eg-bucketname-346
functions:
  echo:
    handler: echo.lambda_handler
    events:
      - s3:
          bucket:
             Ref : MyS3Bucket
          event: s3:ObjectCreated:*
      - s3:
          bucket:
            Ref : MyS3Bucket
          event: s3:ObjectRemoved:*
```

**Comment by rowanu** [comment]
Is that your actual `serverless.yml`? The indentation looks very strange. Can you confirm that your actual `serverless.yml` is indented 2 spaces at every level, and update the snippet you've provided?

If the indentation is mixed up, the YAML will not convert to JSON cleanly, and you could end up with an object where the config is expecting a string (and hence the `"BucketName": "[object Object]"` issue).

**Comment by EnriqueGC** [comment]
@rowanu,   here you go:
```
service: T52
provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:*
    Resource: "*"
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: eg-bucketname-346
functions:
  echo:
    handler: echo.lambda_handler
    events:
    - s3:
        bucket:
          Ref: MyS3Bucket
        event: s3:ObjectCreated:*
    - s3:
        bucket:
          Ref: MyS3Bucket
        event: s3:ObjectRemoved:*
```
![image](https://cloud.githubusercontent.com/assets/9368226/18724624/193c70da-800b-11e6-92de-b2cef0f7acf6.png)

**Comment by EnriqueGC** [comment]
anyone?

**Comment by flomotlik** [comment]
@EnriqueGC can you run `serverless deploy --noDeploy` and show us the configuration in the CloudFormation templated that is created for you in the .serverless folder

**Comment by EnriqueGC** [comment]
here you go see attached files for originals: 
cloudformation-template-create-stack.json
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    }
  }
}
```
cloudformation-template-update-stack.json
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Path": "/"
      }
    },
    "IamPolicyLambdaExecution": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "dev-T52-lambda",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:us-east-1:*:*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:*"
              ],
              "Resource": "*"
            }
          ]
        },
        "Roles": [
          {
            "Ref": "IamRoleLambdaExecution"
          }
        ]
      }
    },
    "EchoLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "1474567877455-2016-09-22T18:11:17.455Z/T52.zip"
        },
        "FunctionName": "T52-dev-echo",
        "Handler": "echo.lambda_handler",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "python2.7",
        "Timeout": 6
      }
    },
    "S3BucketObjectObject": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "[object Object]",
        "NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Event": "s3:ObjectCreated:*",
              "Function": {
                "Fn::GetAtt": [
                  "EchoLambdaFunction",
                  "Arn"
                ]
              }
            },
            {
              "Event": "s3:ObjectRemoved:*",
              "Function": {
                "Fn::GetAtt": [
                  "EchoLambdaFunction",
                  "Arn"
                ]
              }
            }
          ]
        }
      }
    },
    "EchoLambdaPermissionS3": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "EchoLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": "s3.amazonaws.com"
      }
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "EchoLambdaFunctionArn": {
      "Description": "Lambda function info",
      "Value": {
        "Fn::GetAtt": [
          "EchoLambdaFunction",
          "Arn"
        ]
      }
    }
  }
}
```


[templates.zip](https://github.com/serverless/serverless/files/488082/templates.zip)

**Comment by flomotlik** [comment]
Looks like your YAML is invalid. Checked it with http://codebeautify.org/yaml-to-json-xml-csv and here is a fixed versio:

```
service: T52
provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:*
    Resource: "*"
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: eg-bucketname-346
functions:
  echo:
    handler: echo.lambda_handler
    events:
      - s3:
        bucket:
          Ref: MyS3Bucket
        event: s3:ObjectCreated:*
      - s3:
        bucket:
          Ref: MyS3Bucket
        event: s3:ObjectRemoved:*
```

**Comment by EnriqueGC** [comment]
Tried your template, it does not error out but the bucket is nowhere to be found here are the generated CF templates:
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    }
  }
}
```

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Path": "/"
      }
    },
    "IamPolicyLambdaExecution": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "dev-T52-lambda",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:us-east-1:*:*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:*"
              ],
              "Resource": "*"
            }
          ]
        },
        "Roles": [
          {
            "Ref": "IamRoleLambdaExecution"
          }
        ]
      }
    },
    "EchoLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "1474569424658-2016-09-22T18:37:04.658Z/T52.zip"
        },
        "FunctionName": "T52-dev-echo",
        "Handler": "echo.lambda_handler",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "python2.7",
        "Timeout": 6
      }
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "EchoLambdaFunctionArn": {
      "Description": "Lambda function info",
      "Value": {
        "Fn::GetAtt": [
          "EchoLambdaFunction",
          "Arn"
        ]
      }
    }
  }
}
```

**Comment by flomotlik** [comment]
Can you post this to our Forum at forum.serverless.com to see if other users can help out with this.

The functionality here in general works, it looks like there is some configuration issue and we don't have enough resources to help with specific configuration issues at the moment. It looks like there is an issue with the YAML syntax.

**Comment by teppokauppinen** [comment]
There seems to be a problem with the S3 bucket creation with proper YAML format in 1.0.2

With following YAML, neither create-stack.json or update-stack.json contains any information about the bucket
```
functions:
  hello:
    handler: handler.hello
    events:
      - s3: 
        bucket: demo-bucket
        event: s3:ObjectCreated:*
```

With the following YAML conf, the update-stack.json contains the bucket
```
functions:
  hello:
    handler: handler.hello
    events:
      - s3: 
          bucket: demo-bucket
          event: s3:ObjectCreated:*
```
So the difference is that there is 4 spaces in front of 'bucket' and 'event' instead of the standard two spaces. The example in the docs (https://serverless.com/framework/docs/providers/aws/events/s3/) does seem to use 4 spaces also, but I would assume it would work with the 'normal' indentation also.
