### ISSUE TITLE
error running sls remove and subsequent deploy

### ISSUE THREAD

**Issue by viz** [serverless/serverless#2108]
# This is a Bug Report

## Description
In trying to upgrade my service from 1.0.0-beta.2 to 1.0.0-rc.1 I wanted to ensure that changes to my custom authorizer config and request template were successful, so I tried to remove the service created with 1.0.0-beta.2 and then redeploy the updated config.

On running remove, I got the following failure:
```
$ ./node_modules/.bin/sls remove --stage dev
Serverless: Deprecation Notice: the "defaults" property in serverless.yml is deprecated. The     "stage", "region" & "variableSyntax" properties has been moved to the "provider" property instead.   Please update your serverless.yml file asap. For more info, you can check our docs.
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
  ....................................Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: IamRoleLambda
     - Cannot delete entity, must delete policies first..

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```
When inspecting my aws setup, the lambda functions and api gateway 'apis' were successfully remove along with the S3 bucket, however the IAM role wasn't removed.

On attempting to re-deploy I get the following failure:
```
$ ./node_modules/.bin/sls deploy --stage dev
Serverless: Bundling with Webpack...
Time: 7324ms
       Asset     Size  Chunks             Chunk Names
./handler.js  8.22 kB       0  [emitted]  main
Serverless: Packing external modules: rollbar,pusher,lodash
Serverless: Packaging service...

  Serverless Error ---------------------------------------

     The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```

my serverless.yml looks like:
```
service: pusherService 

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules:  
    - rollbar
    - pusher
    - lodash

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1

functions:
  pusher:
    handler: handler.handler
    events:
      - http:
          path: notify
          method: post
          cors: true
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: post
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:xxx:function:authService-prod-authorise
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization

```
(note: I fixed the deprecated `defaults` issue noted in the first report above)

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.0-rc.1 to execute commands, original service created using 1.0.0-beta.2
* ***Operating System***: OSX 10.11.6
* ***Stack Trace***:
* ***Provider Error messages***:
