### ISSUE TITLE
Can't deploy very simple project, Unresolved resource dependencies [ApiGatewayResource]

### ISSUE THREAD

**Issue by wxs** [serverless/serverless#2124]
# This is a (Bug Report / Feature Proposal)

Bug Report
## Description

I have an extremely minimal test serverless.yml nearly unchanged from the template:

```
service: oden

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-1

functions:
  crash:
    handler: handler.log_crash
    events:
      - http:
          path: /crash
          method: post
```

when I try to deploy via `sls deploy -v` I get the following message:

```
     Template format error: Unresolved resource dependencies
     [ApiGatewayResource] in the Resources block of the template
```

The first time I tried this it printed a bit of extra information before giving the same error:

```
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - oden-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - oden-dev
```

but on subsequent deploys it no longer prints those messages. I tried to deploy with `--noDeploy` to look at the CloudFormation stack files; here is the portion of `cloudformation-template-update-stack.json` where it mentions `ApiGatewayResource`:

```
    "ApiGatewayResourceCrash": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Ref": "ApiGatewayResource"
        },
        "PathPart": "crash",
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        }
      }
    },
```
## Additional Data
- **_Serverless Framework Version you're using**_:
  v1.0.0-rc1
- **_Operating System**_:
  Mac OS X 
- **_Stack Trace**_:
- **_Provider Error messages**_:
