### ISSUE TITLE
Endpoints not deployed to API Gateway

### ISSUE THREAD

**Issue by thundo** [serverless/serverless#2131]
***Serverless Framework Version***

    1.0.0-rc.1

***Operating System***

    Debian 8 (docker container)

***Expected Behavior***

Endpoints get deployed to API Gateway.

***Actual Behavior***

Endpoints get __never__ deployed. I tried changing paths, methods, function names, remove/(re)deploy to no avail.

![image](https://cloud.githubusercontent.com/assets/703181/18506229/490ab7d6-7a6b-11e6-881c-3f39016e504d.png)

![image](https://cloud.githubusercontent.com/assets/703181/18506300/a3d135fa-7a6b-11e6-8a41-0739904c3e6a.png)

![image](https://cloud.githubusercontent.com/assets/703181/18506330/cc9e3712-7a6b-11e6-9ab9-94c68a23397d.png)

Possibly duplicated of #1766 and #1684.

That's my first experience with Sls. Did I miss something?

**Comment by rowanu** [comment]
Shouldn't your `path` and `method` parameters be indented another level? i.e.

```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
```
