### ISSUE TITLE
Add Lambda description option to serverless.yml

### ISSUE THREAD

**Issue by asantibanez** [serverless/serverless#2146]
# This is a Feature Proposal

## Description

* It would be great to have a description text for Lambda functions when deploying. As of today in v1 each Lambda description deploys with a blank description. v0 accepted managed a description for every Lambda.

## Proposed Solution

Add description token to functions configuration. Example:
```yml
functions: 
  loginUser:
    name: loginUser
    description: Verifies credentials for authorization to platform
```
