### ISSUE TITLE
Custom Response Templates not Uploading to AWS (Bug?)

### ISSUE THREAD

**Issue by eecdc** [serverless/serverless#2170]
# This is a Bug Report
## Description

I am trying to create a custom response template that gets uploaded in to AWS as integration responses. Currently I want the response to expose my error object as a content-type of application/json. What I've created doesn't seem to get uploaded into AWS, however writing the template directly in to AWS works.

config:

```
functions:
  signin:
    handler: credentials/authentication/signin/handler.signin
    package:
      include:
        - lib\auth
    events:
      - http:
          path: authentication/signin/{provider}
          method: post
          private: true
          response:
            headers:
              Content-Type: "'application/json'"
            template: ${file(response-template.txt)}
```

response-template.txt contains the following:

```
#set ($errorMessageObj = $util.parseJson($input.path('$.errorMessage')))
{
   "status" : "$errorMessageObj.status",
    "error" : {
    "type": "$errorMessageObj.error.type",
    "message": "$errorMessageObj.error.message",
    "detail": "$errorMessageObj.error.detail",
    "code": $errorMessageObj.error.code
    }
}
```

After a successful sls deploy and making the post request that fails I get the following which is my error object as a string

```
{
    "errorMessage": "{\"status\":\"[500]\",\"error\":{\"type\":\"API\",\"message\":\"Unexpected error has occurred.\",\"detail\":null,\"code\":6}}"
}
```

If I paste the template directly in to AWS I get the response formatted as I'd expect. It would appear, unless I am doing something wrong that the template is not being uploading into AWS.

**Comment by Cabsy** [comment]
By way of an update I have found that my template is applied to the default mapping.

 Is there a way to apply it to the following?

.*\[400\].*
.*\[401\].*
.*\[403\].*
.*\[404\].*
.*\[422\].* 
.*(Process\s?exited\s?before\s?completing\s?request|\[500\]).*
.*\[502\].*
.*\[504\].*

**Comment by rowanu** [comment]
Can you please put your snippets in code blocks i.e. surrounded by "```" so that we can see your exact configuration - whitespace is significant in YAML, and might be why you're having problems.

For more info, see the [Github markdown page](https://guides.github.com/features/mastering-markdown/).

**Comment by Cabsy** [comment]
Sure thing, that's done.

**Comment by flomotlik** [comment]
You can do that now: https://serverless.com/framework/docs/providers/aws/events/apigateway#custom-status-codes

**Comment by chaitanya11** [comment]
Hi, 
  I am throwing runtime exception in java as below 
 ```
public class LambdaInfoHandler implements RequestHandler<String, String> {
  @Override
    public String handleRequest(String input, Context context) {

        Map<String, Object> errorPayload = new HashMap();
        errorPayload.put("errorType", "BadRequest");
        errorPayload.put("httpStatus", 400);
        errorPayload.put("requestId", context.getAwsRequestId());
        errorPayload.put("message", "An unknown error has occurred. Please try again.");
        String message = new ObjectMapper().writeValueAsString(errorPayload);
        
        throw new RuntimeException(message);
    }
 }
```

and my serverless configuration for this lambda function is 

```
lambdaInfo:
    handler: LambdaInfoHandler
    events:
      - http:
          path: lambda
          method: post
          response:
            headers:
              Content-Type: "'application/json'"
            template: ${file(response-template.txt)}
```
This is my `response-template.txt` file content
```
#set ($errorMessageObj = $util.parseJson($input.path('$.errorMessage')))
{
  "type" : "$errorMessageObj.errorType",
  "message" : "$errorMessageObj.message",
  "httpStatus" : "$errorMessageObj.httpStatus"
}
```


So, when i hitting lambda function i am getting 
502 error with body as 
```
{
    "message": "Internal server error"
}
```

So, the mapping template is not working as expected ... 
can any one suggest the actual way of implementing it if i am wrong...
I followed this [this](https://aws.amazon.com/blogs/compute/error-handling-patterns-in-amazon-api-gateway-and-aws-lambda/).

**Comment by HyperBrain** [comment]
Hi @chaitanya11 ,

the default integration type for lambda endpoints in Serverless is Lambda-Proxy. You are about to use the lambda integration type that uses templates, so you have to specify that in your serverless.yml:

```
...
events:
      - http:
          integration: lambda
          path: lambda
          method: post
          ...
```

For some info see here: https://serverless.com/framework/docs/providers/aws/events/apigateway/
