### ISSUE TITLE
serverless.yml configuration object model differs for equivalent configuration options

### ISSUE THREAD

**Issue by Bilal-S** [serverless/serverless#2178]
According to serverless guide:
https://github.com/serverless/serverless/blob/master/docs/01-guide/05-event-sources.md

the following serverless config entries should be equivalent

This is from a serverless.yml like this:

```
 service: aws-nodejs 

 functions:
   hello:
     handler: handler.hello
     events: 
       - http: GET greet
```

is represented like this in the object model for endpoint:
![endpoint rc 1 version a](https://cloud.githubusercontent.com/assets/668901/18719532/b7c12630-7ff5-11e6-9e0f-170b507633fb.PNG)

and the classic one:

```
 service: aws-nodejs 

 functions:
   hello:
     handler: handler.hello
     events: 
       - http: 
             path: greet
             method: GET
```

![endpoint rc 1 version b](https://cloud.githubusercontent.com/assets/668901/18719541/c4b33a18-7ff5-11e6-9ebd-9e11b51ef87e.PNG)

As you can see the representation of endpoint method and path are very different though the configuration options are equivalent according to docs.

This is most likely the result of system init sequence for serverless core. It looks like the configuration object is validated after the plug-ins are loaded.  Could this be corrected so that plugins have a fully validated configuration object to work with. If multiple ways of configuring the system should lead to the same outcome it would probably be better to represent them the same way in the object model. An additional key like "raw" could be added to the config model with the raw serverless.yml content for plugins that need this as a starting point. 

Thanks,
Bilal
