### ISSUE TITLE
resources - deploy when dynamodb table exists

### ISSUE THREAD

**Issue by andyfenelon** [serverless/serverless#2181]
when the table exists it presents the error on deploy

>   Serverless Error ---------------------------------------
>  
>      An error occurred while provisioning your stack: TodosDynamoDbTable
>      - users already exists.

is there a way to deploy resources when a table already exists ?
i've set the DeletionPolicy Attribute to 'Retain' so i don't wipe it?

```
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

```
```
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'users'
```
