### ISSUE TITLE
API Gateway - allow AWS_IAM as authorizer 

### ISSUE THREAD

**Issue by nachoab** [serverless/serverless#2186]
Maybe with this syntax:

authorizer: AWS_IAM
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.0rc1
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by flomotlik** [comment]
At the moment this is possible through custom resources, not sure if we're going to implement ourselves so I'm closing here.

**Comment by robbiehanson** [comment]
> At the moment this is possible through custom resources

Can you provide an example?

**Comment by marcelocbf** [comment]
Hey @robbiehanson , that's how I did. I went to the .serverless folder after running "sls deploy" and opened the cloudformation-template-update-stack.json, looked for the API Gateway method Serverless created for me and copied (changed to YAML) the important parts and put it in the serverless.yml file under resources with my other resources. It looked like this:

    ApiGatewayMethodNamePost:
      Type: AWS::ApiGateway::Method
      Properties:
        AuthorizationType: AWS_IAM
 
I don't know if that's the recommended approach but I just did it and it worked for me...

Cheers

**Comment by robbiehanson** [comment]
I found an alternative that I think is a little cleaner. It's a serverless plugin, which you can get here:
https://dl.dropboxusercontent.com/u/8824928/serverless-plugin.zip

Here are the instructions that come with it:

Credit for the code goes to Nacho García (@nachoab)

**Instructions**

- Place the `api-gateway-auth-plugin` folder into the `node_modules` folder of your project.
- Add the following to your "serverless.yml" file (at root level, i.e. no indentation)

```
plugins:
  - api-gateway-auth-plugin
```

- Then simply change the desired events:

```
foobar:
    handler: foobar.myMethod
    timeout: 30
    events:
      - http:
          path: do-something/{where}/{when}
          method: GET
          useIAMAuth: true
      - http:
          path: do-something-else
          method: POST
          useIAMAuth: true
          invokeWithCallerCredentials: true
```

**Testing**

You can run the following command to perform a "dry run":

```
serverless deploy --noDeploy
```

This will create all the relevent files in the `.serverless` directory:

```
cd .serverless
```

Then you can inspect the `cloudformation-template-update-stack.json` file. If you search for `AWS_IAM` you should find matching results:

```
"ApiGatewayMethodDoDashsomethingDashelsePost": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "POST",
        "RequestParameters": {},
        "ResourceId": {
          "Ref": "ApiGatewayResourceFoobar"
        },
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "AuthorizationType": "AWS_IAM",
```

**Comment by marcelocbf** [comment]
Yes, it is cleaner. I'll use it too. Thanks @robbiehanson

**Comment by nachoab** [comment]
@flomotlik is there a reason not to implement this ? it seems straightforward looking at https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/apiGateway/lib/method/authorization.js

Is it because you intent to create a spec that is provider neutral and the authorizer AWS_IAM is aws specific? (same for invoking with caller credentials). It doesn't look like that given that we can configure s3 events for example

We could use resources for this, just like this

```
ApiGatewayMethodResourceNameMethodName:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: AWS_IAM
    Integration:
      Credentials: "arn:aws:iam::*:user/*"
```

But this have a big problem which is guessing the `ApiGatewayMethodResourceNameMethodName` name.
You have to read the code to know how to. Using dashes in your paths makes it even worse.

And is not this the kind work we want sls to abstract  for us ?

**Comment by sublimator** [comment]
bump ?

**Comment by n1ru4l** [comment]
For other people searching  ;)

**This is possible since 1.14** https://github.com/serverless/serverless/pull/3534

```yaml
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          authorizer: aws_iam
```
