### ISSUE TITLE
Error "Invalid template resource property 'ResourceId'" on HTTP Proxy

### ISSUE THREAD

**Issue by citosid** [serverless/serverless#2237]
# This is a Bug Report
## Description

**What went wrong?**

With the following yaml:

```
resources:
  Resources:
    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi # our default Rest API logical ID
            - RootResourceId
        PathPart: /auth/keys # the endpoint in your API that is set as proxy
        RestApiId:
          Ref: RestApiApigEvent
    ProxyMethod:
      ResourceId:
        Ref: ProxyResource
      RestApiId:
        Ref: RestApiApigEvent
      Type: AWS::ApiGateway::Method
      Properties:
        HttpMethod: GET # the method of your proxy. Is it GET or POST or ... ?
        MethodResponses:
          - StatusCode: 200
        Integration:
          IntegrationHttpMethod: POST
          Type: HTTP
          Uri: https://site.org/auth/keys # the URL you want to set a proxy to
          IntegrationResponses:
            - StatusCode: 200
```

**What did you expect should have happened?**

It should create an entry for `my-api.server.org/auth/keys` as a proxy for `site.org/auth/keys`

**What was the config you used?**

Default, it is a brand new installation

**What stacktrace or error message from your provider did you see?**

```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

     Invalid template resource property 'ResourceId'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```
## Additional Data
- **_Serverless Framework Version you're using**_:

```
➔ serverless --version
1.0.0-rc.2
```
- **_Operating System**_:
  AWS Linux
- **_Stack Trace**_:

```
➔ slss deploy --verbose
Serverless: Packaging service...
Serverless: Removing old service versions...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

     Invalid template resource property 'ResourceId'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
```
- **_Provider Error messages**_:
