### ISSUE TITLE
Pin/Lock serverless.yml file to a specific serverless version

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2252]
# This is a Feature Proposal
## Description

@nikgraf mentioned that it would be useful if a `serverless.yml` file could be (optionally) pinned to a specific version so that deployment etc. will only work if the target Serverless version is installed on the local machine.

Another way to deal with this could be to print just a warning message that the Serverless version does not fit the version defined in the `serverless.yml` file.

This could look something like this:

```
# serverless.yml
version: 1.0.0-rc.2

service: my-service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
```
