### ISSUE TITLE
Event type check executes before pulling referenced file contents.

### ISSUE THREAD

**Issue by mjzone** [serverless/serverless#2269]
# This is a (Bug Report)
## Description

I've been using v1@rc.1 and I could reference function events from a different file to avoid clutter in the serverless.yml file. 

``` functions:
  todo:
    handler: handlers/todo/handler.todo
    events: ${file(handlers/todo/config.yml):events}
```

**config.yml**

```
events:
  - http:
      method: GET
      path: todos/getAll
      cors: true
      request: ${file(./templates.yml):request}

  - http:
      method: DELETE
      path: todos/delete/{id}
      cors: true
      request: ${file(./templates.yml):request}

  - http:
      method: POST
      path: todos
      cors: true
      request: ${file(./templates.yml):request}

  - http:
      method: PUT
      path: todos/update
      cors: true
      request: ${file(./templates.yml):request}
```

But with the **events array type check** introduced in rc2 evaluates the reference as string before pulling the content from the config.yml file and errors. 

```
 Serverless Error ---------------------------------------

    Events for "todo" must be an array, not an string

 Stack Trace --------------------------------------------
```
