### ISSUE TITLE
Unresponsive CLI when stack fails to update

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2275]
# This is a Bug Report

## Description

CLI gets stuck / unresponsive when stack cannot be updated successfully.
Just create a Serverless service with the `serverless.yml` file below.

## Additional Data

```yml
service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET greet

resources:
  Resources:
    WebsiteS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html
    WebsiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebsiteS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
              - Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: WebsiteS3Bucket
                  - "/*"
    CloudFrontDistribution:
      DependsOn: WebsiteS3Bucket
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          DefaultRootObject: index.html
          Enabled: 'true'
          DefaultCacheBehavior:
            AllowedMethods:
            - HEAD
            - GET
            - PUT
            - POST
            - PATCH
            - OPTIONS
            - DELETE
            CachedMethods:
            - GET
            - HEAD
            ForwardedValues:
              QueryString: true
              Headers:
              - Origin
            MinTTL: '0'
            MaxTTL: '86400'
            TargetOriginId: WebsiteS3Bucket
            ViewerProtocolPolicy: allow-all
          Origins:
          - DomainName:
              Fn::Join:
              - ''
              - - Ref: WebsiteS3Bucket
                - ".s3.amazonaws.com"
            Id: some-id
            S3OriginConfig:
              OriginAccessIdentity: ''
          CustomErrorResponses:
          -
            ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
```
