### ISSUE TITLE
Setting custom authorizer with ARN results in INVALID

### ISSUE THREAD

**Issue by itsovereasy** [serverless/serverless#2277]
Using serverless v1.0.0-rc.2

When setting an authorizer via ARN as shown in the docs:

```
  updateAssets:
    handler: handler.update
    events:
      - http:
          path: cases/update
          method: PUT
          cors: true
          authorizer: arn:aws:lambda:us-west-2:<my-account-id>:function:auth-service-dev-authorize
```

The following configuration results:

<img width="420" alt="screen shot 2016-10-07 at 11 43 44" src="https://cloud.githubusercontent.com/assets/20520946/19201680/a43b44d4-8c83-11e6-8c0a-fd8e5a65e5f4.png">
