### ISSUE TITLE
Support for custom response default status code

### ISSUE THREAD

**Issue by keinu** [serverless/serverless#2281]
# This is a Feature Proposal
## Description

Let's say you want your request to return a 301 or 302 redirect response code. It is currently not possible to specify a different status code other than the default 200

In combination with the _Location_ header settings, it could be useful to respond with a 301/302 to allow a redirect. 

Use cases could be: URL shorteners, authorised downloads

The configuration would involve the following

``` yaml
method: get
response:
  statusCode: 302
  headers:
    Location: "integration.response.body.url"
```

Omitting `statusCode` property would fallback to the default 200

Similar issues:
- #2046
