### ISSUE TITLE
AWS provider credentials not found

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#2340]
Serverless Framework Version - `1.0.0-rc.2`

I have setup `accessKeyId` and `secretAccessKey` like this in `serverless.yml`

```
provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: us-west-2
  credentials:
      accessKeyId: accessKeyIdhere
      secretAccessKey: secretAccessKeyhere
```

but when run `serverless deploy -v` i got following error

```
Error --------------------------------------------------

     ServerlessError: ServerlessError: AWS provider credentials
     not found. You can find more info on how to set up provider
     credentials in our docs here: https://git.io/viZAC

     For debugging logs, run again after setting SLS_DEBUG env var.

Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.
```

It should work because this is also one of option i found in document rathan than setup using aws cli

**Comment by eahefnawy** [comment]
@nirmalgoswami support for credentials object is not available in version `1.0.0-rc.2` ... please hold for the v1 release coming VERY soon 😊

**Comment by nirmalgoswami** [comment]
Thanks for fast reply,any workaround for this ? using master branch ?

**Comment by eahefnawy** [comment]
Please update to v1 which we just released 😊

**Comment by nirmalgoswami** [comment]
@eahefnawy Wow,just checked,keep working like this. you are our role model :)

**Comment by 14mar1983** [comment]
I changed the version to sls deploy -v1 but still I m getting the error. Please suggest.
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: https://git.io/vXsdd.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.1.0
     Serverless Version:     1.20.2
 

/bin/bash ./serverless.sh returned exit code 1

**Comment by pmuens** [comment]
@14mar1983 thanks for commenting 👍.

Have you followed this guide to setup the provider credentials? How does your `serverless.yml` file look like?

**Comment by 14mar1983** [comment]
Thank you. Could you please guide if any sample for python code in
circle.yml, we need to add multiple python functions in serverless.yml

**Comment by 14mar1983** [comment]
We are getting below error.
*  Cannot read property 'events' of null*

*This is my serverless.yml file*
service: Nike-CircleCi-Lambda
custom:
stage: ${opt:stage, self:provider.stage}
stageConfig:
dev:
ucName: Dev
domain: Nike-CircleCi-Lambda.COM
plugins:
- serverless-plugin-custom-domain
provider:
name: aws
runtime: python2.7
stage: dev
region: us-west-2
profile: support-circle-ci
environment:
NODE_ENV: ${self:custom.stage}
functions:
switchboard1_func1:
incoming:
handler: switchboard._airflow_request
events:
- http:
path: ${self:custom.stage}/Nike-CircleCi-Lambda
method: post
package:
exclude:
- '.*'
- 'postman/**'
- 'package.json' Please suggest

**Comment by pmuens** [comment]
@14mar1983 thanks for sharing the `serverless.yml`.

I've copy and pasted it here and will indent it the way it should be indented. While doing that I saw that there's an `switchboard1_func1` function which has no further definition. This function could be the problem why it errors out. I've commented it out in the indented code below.

Maybe you could try to remove the `switchboard1_func1` function and try again?

```yml
service: Nike-CircleCi-Lambda

custom:
  stage: ${opt:stage, self:provider.stage}
  stageConfig:
    dev:
    ucName: Dev
    domain: Nike-CircleCi-Lambda.COM

plugins:
  - serverless-plugin-custom-domain

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-2
  profile: support-circle-ci

environment:
  NODE_ENV: ${self:custom.stage}

functions:
  # NOTE: this is an empty function definition and should be filled out or be removed
  # switchboard1_func1:
  incoming:
    handler: switchboard._airflow_request
    events:
      - http:
           path: ${self:custom.stage}/Nike-CircleCi-Lambda
           method: post

package:
  exclude:
    - '.*'
    - 'postman/**'
    - 'package.json'
```

Toes this resolve your problem?
