### ISSUE TITLE
Cron scheduled syntax is rejected

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2344]
Maybe a bug in the service, maybe a doco bug, I can't tell --
1. Using this serverless.yml:

```
service: xxxxxxxx

provider:
    name: aws
    runtime: python2.7
    stage: prod
    region: us-east-1

package:
    exclude:
        - __vendored-**

functions:
    run:
        handler: handler.run
        timeout: 20
        events:
            - schedule:
                cron: cron(5 8 * * ? *)
                enabled: false
```

Produces this error:
  Serverless Error ---------------------------------------

```
 Missing "rate" property for schedule event in function
 run The correct syntax is: schedule: rate(10 minutes)
 OR an object with "rate" property. Please check the
 docs for more info.
```

The documentation at https://serverless.com/framework/docs/providers/aws/events/schedule/ suggests this events / schedule / cron syntax would be OK.
1.  Single-line variation (with no enabled field):

```
service: xxxxxxxx

provider:
    name: aws
    runtime: python2.7
    stage: prod
    region: us-east-1

package:
    exclude:
        - __vendored-**

functions:
    run:
        handler: handler.run
        timeout: 250
        events:
            - schedule: cron(5 8 * * ? *)
```

This variation works fine.

**Comment by rowanu** [comment]
Yep, this is a bug bug. It's an issue with [the schedule object check](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/schedule/index.js#L29).

I will submit a fix.

**Comment by rowanu** [comment]
Upon closer inspection, this is **not a bug** 😕 Probably just needs some better examples in the docs using the cron syntax.

Change your `cron` property name in your schedule event to `rate` and it will work i.e.:

```yaml
...
        events:
            - schedule:
                rate: cron(5 8 * * ? *)
                enabled: false
```

**Comment by chris-hailstorm** [comment]
Confirmed

**Comment by chris-hailstorm** [comment]
Now using Serverless v1.1.0, this cron syntax is failing:

```
    funcname:
        events:
            - schedule:
                rate: cron(0 5 * * * ?)
```

with this error message:

```
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: SenderEventsRuleSchedule1
     - Parameter ScheduleExpression is not valid..
```

The `rate: rate(5 minutes)` syntax is working, but the cron-ized version version.
