### ISSUE TITLE
Cannot set AuthorizationType in CF Method (was working in RC2)

### ISSUE THREAD

**Issue by riccardo-89** [serverless/serverless#2359]
# BUG
## Description

For bug reports:
- What went wrong?
  I have updated serverless to version 1.0.2 (was working in rc2) since the update if I try to
  set the AuthorizationType to CUSTOM for using a user pool or AWS_IAM this is ignored thing that
  before was going smooth (on the other end if I set ApiKeyRequired) this goes smoothly as before.
- What did you expect should have happened?
  Setting resources props directly in cloud formation was working like charm before v1, now I think is broken in some cases.
- What was the config you used?
- What stacktrace or error message from your provider did you see?
  I do not see any errors, simply the prop is not being set.
## Additional Data
- **_Serverless Framework Version you're using**_: v1.0.2
- **_Operating System**_: mac os
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by flomotlik** [comment]
Can confirm, here is a config for it: 

```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/me
          method: post
      - http:
          path: users/me
          method: put

resources:
  Resources:
    ServerlessDeploymentBucket:
      Properties:
        BucketName: Testname
    ApiGatewayMethodUsersMePost:
      Properties:
        AuthorizationType: "AWS_IAM"
        Something: Something
        HttpMethod: "Whatever"
```

**Comment by eahefnawy** [comment]
@riccardo-89 thanks a lot for reporting, I looked into it and can easily reproduce. It used to work because we merged custom resources **after** compiling functions/events, but due to a recent accidental change, it's now merging custom resources **before** compiling functions/events, hence no overwrite happens.

Working on a fix now 😊

**Comment by riccardo-89** [comment]
thanks a lot guys! :D

**Comment by pmuens** [comment]
Should be resolved with #2385 /cc @flomotlik

**Comment by endymion00** [comment]
Hi,
The bug should be reopen.
When a path parameter is used it does not work.
Here is my custom vars & method definition:

```
custom:
    versionPath: v1
    usersPath: users
    cors: true

functions:
  test:
    handler: functions/users_handler.test 
    events:
        - http:
            path: ${self:custom.versionPath}/${self:custom.usersPath}/{user_id}/test
            method: post
            cors: ${self:custom.cors}
            integration: lambda

resources:
    Resources:
      ApiGatewayMethodV1UsersUseridTestPost: 
        Type: "AWS::ApiGateway::Method"
        Properties:
          HttpMethod: "POST"
          AuthorizationType: "AWS_IAM"

```

sls deploy produces this error:

Serverless: Packaging service…
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-user-service-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodV1UsersUseridTestPost
CloudFormation - **CREATE_FAILED** - AWS::ApiGateway::Method - ApiGatewayMethodV1UsersUseridTestPost
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - **CREATE_FAILED** - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - **CREATE_FAILED** - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-user-service-dev
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-user-service-dev
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodV1UsersUseridTestPost
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - serverless-user-service-dev
Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     **An error occurred while provisioning your stack: ApiGatewayMethodV1UsersUseridTestPost
     - undefined.**

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       4.3.0
     Serverless Version: 1.0.3

**Comment by goldenbearkin** [comment]
I got the same error message as @endymion00 mentioned above. Please kindly reopen this thread.

**Comment by pmuens** [comment]
@endymion00 @goldenbearkin could you checkout the `master` and try again?

We've pushed a lot of fixes recently which should resolve this problem.

**Comment by mfrankwork** [comment]
@endymion00 The resource name for the API Gateway method needs to include the normalized path variable, which is converted to `<variable>Var` format by the [AWS naming library](https://github.com/serverless/serverless/blob/v1.5.0/lib/plugins/aws/lib/naming.test.js#L54-L58).  I believe your `serverless.yml` should look like the following (_HttpMethod_ is not required since it is included in the resource name):

```yaml
custom:
    versionPath: v1
    usersPath: users
    cors: true

functions:
  test:
    handler: functions/users_handler.test 
    events:
        - http:
            path: ${self:custom.versionPath}/${self:custom.usersPath}/{user_id}/test
            method: post
            cors: ${self:custom.cors}
            integration: lambda

resources:
    Resources:
      ApiGatewayMethodV1UsersUseridVarTestPost: 
        Type: "AWS::ApiGateway::Method"
        Properties:
          AuthorizationType: "AWS_IAM"
```
