### ISSUE TITLE
Output final effective serverless.yml

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2366]
The new variable syntax is great.  However sometimes I need to debug what I do with it.

It'd be useful to have a command line option to render the serverless.yml file and dump it to stdout.  This would helps to understand the effects of recursive variable expansion and whatnot.  Some users may also use it to make a record of config files for source code control.

**Comment by horike37** [comment]
@chris-hailstorm

I think it's a good idea! Do you have a sense of the following?
If you write serverless.yml as follow:
```yml
service: new-service
provider: aws
functions:
  hello:
      name: ${opt:stage}-hello
      handler: handler.hello
  world:
      name: ${opt:stage}-world
      handler: handler.world
```

And you execute `a command line option to render the serverless.yml file`, then dump it to stdout as follow:
```yml
service: new-service
provider: aws
functions:
  hello:
      name: dev-hello
      handler: handler.hello
  world:
      name: dev-world
      handler: handler.world
```
