### ISSUE TITLE
Which is best folder/file structure to organize multiple functions of service in v1.0

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#2372]
This is related to the serverless` v1.0` . I am opening this for discussion only.

How we can organize multiple function in proper manner 
1. folder structure of multiple functions.
2, `serverless.yml` sample 
3. depedency of node_modules for particular function,some node module is only require for specific function.
4. Optimize size of function to load only require files/folder

Which is best approach to do above things ?

**Comment by horike37** [comment]
I made `src` directory in my Serverless project root, and add multiple functions to it as follow.
also `node_modules` add to it.
```
├── serverless.yml
└── src
     ├── function1.js
     ├── function2.js
     ├── function3.js
     └── node_modules
```

serverless.yml setting as follow:
```yml
functions:
  function1:
    handler: src/function1.handler
    events:
      - http:
          path: function1
          method: get
      - http:
          path: function1
          method: post
  function2:
    handler: src/function2.handler
    events:
      - http:
          path: function2
          method: get
      - http:
          path: function2
          method: post
  function3:
    handler: src/function3.handler
    events:
      - http:
          path: function3
          method: get
      - http:
          path: function3
          method: post
```

**Comment by nirmalgoswami** [comment]
@horike37 thanks for reply,how you are dealing with include/exclude with function because some node module only require for specific function,we cant upload everything with single function zip,if you will check your function folder after download from aws lambda console you will some irreverent file in zip like node module or other function's file

**Comment by horike37** [comment]
@nirmalgoswami 

I see. How about bellow?
## Serverless project tree
```
├── serverless.yml
├── function1
│      ├── node_modules
│      └── index.js
└── function2
       ├── node_modules
       └── index.js
```

## serverless.yml setting
```yml
package:
   individually: true
functions:
  function1:
    handler: function1/index.handler
    package:
      exclude:
        - function2/**
  function2:
    handler:  function2/index.handler
    package:
      exclude: 
        - function1/**
```
https://serverless.com/framework/docs/guide/packaging/

But Every time you add a function, adding exclude file/folder the statements in the `exclude`.
I think a best way to  be implemented in serverless as follow 

For example
- 1. Add include files/folder the statements in the `include`
- 2. Deploy only added it.
```yml
functions:
  function1:
    handler: function1/index.handler
    package:
      include:
        - function1/**
        - node_modules/RequireModule1
        - node_modules/RequireModule2
  function2:
    handler:  function2/index.handler
    package:
      include: 
        - function2/**
        - node_modules/RequireModule3
```

**Comment by nirmalgoswami** [comment]
> But Every time you add a function, adding exclude file/folder the statements in the exclude.
> I think a best way to be implemented in serverless as follow

yes this was main issue in serverless `0.5`

Your approach seems perfect 💯

**Comment by horike37** [comment]
@pmuens @flomotlik 
What do you think that add `include`  statement in each functions in serverless.yml?
I think that is good.

**Comment by rowanu** [comment]
I think having a per-function directory (each with it's own `node_modules` directory) is the way to go. While there may be some duplication between modules in each `node_modules` directory, disk is cheap 😄

**Comment by andrewoh531** [comment]
@horike37 do you know how your suggestion works with plugins? I'm trying to structure my project like: 
```
├── serverless.yml
└── src
     ├── function1.js
     ├── function2.js
     ├── function3.js
     └── node_modules
     └── package.json
```

and within my `serverless.yml` I'm trying to use `serverless-webpack` and have defined:
```
plugins:
  - serverless-webpack
```

but am getting the error: `Cannot find module 'serverless-webpack'`

**Comment by goncaloneves** [comment]
Running into the same scenario that I want to use include inside each function to avoid bloat in the artifact.
I agree about one parent package.json and choosing modules per function package include/exclude.

**Comment by acorbel** [comment]
with 
```yaml
functions:
  function1:
    handler: function1/index.handler
    package:
      include:
        - function1/**
        - node_modules/RequireModule1
        - node_modules/RequireModule2
  function2:
    handler:  function2/index.handler
    package:
      include: 
        - function2/**
        - node_modules/RequireModule3
```

Do you strictly use npm2 or is there a way to use npm3 (which has a flat structure)?

**Comment by ecstasy2** [comment]
+1 on adding `include` to cherry pick which modules to include in the package.
One potential problem is that some function could use a given package that is not referenced in the `include` and all test would pass but the function would fail once packaged and deployed.

**Comment by danawoodman** [comment]
I'm doing the following and I like it thus far:

```
├── serverless.yml
└── functions
     └── users
          ├── create.js
          ├── delete.js
          ├── read.js
          └── update.js
     └── emails
          ├── forgot-password.js
          └── welcome.js  
```

**Comment by jamiechong** [comment]
Checkout this plugin https://github.com/doapp-ryanp/serverless-plugin-browserify which handles efficient bundling for you. My folder structure is like this: 
```
- serverless.yml
- package.json
- functions
    - function1.js
    - function2.js
- node_modules
- includes
    - util.js
```

In each `functionsX.js` require the modules you need. In `serverless.yml` just point the handler to appropriate file like so (and don't worry about includes or excludes):

```
functions:
  function1:
    handler: functions/function1.handler
  function2:
    handler: functions/function2.handler
```

The browserfy plugin will create  the optimal package using only the dependencies required.
