### ISSUE TITLE
AWS CloudFormation limit of 200 maximum allowed resources

### ISSUE THREAD

**Issue by jordanmack** [serverless/serverless#2387]
# This is a Bug Report
## Description
- What went wrong?

After upgrading my project from 0.5.6 to 1.0.0 I attempted to deploy and received this error:

`Template format error: Number of resources, 202, is greater than maximum allowed, 200`
- What did you expect should have happened?

I expect that this should have worked since there is no limitation on AWS that should forbid this, and it was working on 0.5.6. Serverless should break up the template resources automatically to make this possible.

With the current method you are forced to break up the service, which should not be necessary. This causes problems with general project structure, custom domain mapping, and shared dependencies.
- What was the config you used?

The example config below will generate the error by creating 65 endpoints.

```
service: test

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: e00
          method: get
          cors: true
      - http:
          path: e01
          method: get
          cors: true
      - http:
          path: e02
          method: get
          cors: true
      - http:
          path: e03
          method: get
          cors: true
      - http:
          path: e04
          method: get
          cors: true
      - http:
          path: e05
          method: get
          cors: true
      - http:
          path: e06
          method: get
          cors: true
      - http:
          path: e07
          method: get
          cors: true
      - http:
          path: e08
          method: get
          cors: true
      - http:
          path: e09
          method: get
          cors: true
      - http:
          path: e10
          method: get
          cors: true
      - http:
          path: e11
          method: get
          cors: true
      - http:
          path: e12
          method: get
          cors: true
      - http:
          path: e13
          method: get
          cors: true
      - http:
          path: e14
          method: get
          cors: true
      - http:
          path: e15
          method: get
          cors: true
      - http:
          path: e16
          method: get
          cors: true
      - http:
          path: e17
          method: get
          cors: true
      - http:
          path: e18
          method: get
          cors: true
      - http:
          path: e19
          method: get
          cors: true
      - http:
          path: e20
          method: get
          cors: true
      - http:
          path: e21
          method: get
          cors: true
      - http:
          path: e22
          method: get
          cors: true
      - http:
          path: e23
          method: get
          cors: true
      - http:
          path: e24
          method: get
          cors: true
      - http:
          path: e25
          method: get
          cors: true
      - http:
          path: e26
          method: get
          cors: true
      - http:
          path: e27
          method: get
          cors: true
      - http:
          path: e28
          method: get
          cors: true
      - http:
          path: e29
          method: get
          cors: true
      - http:
          path: e30
          method: get
          cors: true
      - http:
          path: e31
          method: get
          cors: true
      - http:
          path: e32
          method: get
          cors: true
      - http:
          path: e33
          method: get
          cors: true
      - http:
          path: e34
          method: get
          cors: true
      - http:
          path: e35
          method: get
          cors: true
      - http:
          path: e36
          method: get
          cors: true
      - http:
          path: e37
          method: get
          cors: true
      - http:
          path: e38
          method: get
          cors: true
      - http:
          path: e39
          method: get
          cors: true
      - http:
          path: e40
          method: get
          cors: true
      - http:
          path: e41
          method: get
          cors: true
      - http:
          path: e42
          method: get
          cors: true
      - http:
          path: e43
          method: get
          cors: true
      - http:
          path: e44
          method: get
          cors: true
      - http:
          path: e45
          method: get
          cors: true
      - http:
          path: e46
          method: get
          cors: true
      - http:
          path: e47
          method: get
          cors: true
      - http:
          path: e48
          method: get
          cors: true
      - http:
          path: e49
          method: get
          cors: true
      - http:
          path: e50
          method: get
          cors: true
      - http:
          path: e51
          method: get
          cors: true
      - http:
          path: e52
          method: get
          cors: true
      - http:
          path: e53
          method: get
          cors: true
      - http:
          path: e54
          method: get
          cors: true
      - http:
          path: e55
          method: get
          cors: true
      - http:
          path: e56
          method: get
          cors: true
      - http:
          path: e57
          method: get
          cors: true
      - http:
          path: e58
          method: get
          cors: true
      - http:
          path: e59
          method: get
          cors: true
      - http:
          path: e60
          method: get
          cors: true
      - http:
          path: e61
          method: get
          cors: true
      - http:
          path: e62
          method: get
          cors: true
      - http:
          path: e63
          method: get
          cors: true
      - http:
          path: e64
          method: get
          cors: true
```
- What stacktrace or error message from your provider did you see?

`Template format error: Number of resources, 214, is greater than maximum allowed, 200`

another possible error

`Template may not exceed 460800 bytes in size.`
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.2
- **_Operating System**_: Windows 10 x64
- **_Stack Trace**_: N/A
- **_Provider Error messages**_: See above

**Comment by dougmoscrop** [comment]
> I expect that this should have worked since there is no limitation on AWS that should forbid this

This isn't entirely true - I mean, it's a limitation of CloudFormation. In order to overcome this, Serverless would have to create nested stacks based on both number of resources and template size. (There's also a limit, though soft, on how many stacks you can have).

I would be curious if you have a real-world example of something that fits the appreciably vague definition of a "micro" service that is hitting this limit. That might inform a way that serverless could split the CFN definition in to multiple without having to be 'intelligent' about it?

**Comment by jordanmack** [comment]
@dougmoscrop 

> it's a limitation of CloudFormation.

When I say 'there is no limitation on AWS that should forbid this' I'm specifically referring to Serverless v1.0 being unable able to successfully deploy a number of endpoints that is far lower than what AWS actually supports.

> I would be curious if you have a real-world example of something that fits the appreciably vague definition of a "micro" service that is hitting this limit.

Absolutely I do. I was attempting to migrate my current project from Serverless 0.5.6 to 1.0.0 when I hit this roadblock. I have around 40 endpoints, some with multiple methods, and CORS enabled. This alone far exceeds to 200 resource limit, and I'm only done with a fraction of the project. I've had to go back to Serverless 0.5.6 so that I could continue working.

> serverless could split the CFN definition in to multiple without having to be 'intelligent' about it?

- A property could be added at the function level that indicates which CloudFormation template group to use, then Serverless would split up the templates using these groups.
- Serverless could calculate the resource count per function, then split up the templates automatically if it detects it will exceed the limit. This one would require a bit of logic though, since it would be possible for a function to move from one template to another, possibly creating a resource collision.

**Comment by doapp-ryanp** [comment]
I'd propose the management of lambda's is taken out of CloudFormation.  When we 1st developed JAWS I had a CF file for labmdas and a CF file for everything else for this reason (among others).  We eventually decided to deploy lambdas via API for speed of deployment, limits of CF and complexity of breaking up and managing multiple CF files.  

I struggle with depending on CloudFormation for any "newer" services from AWS (like lambda, APIG, CloudFormation) because the CF team really struggles with keeping up on new features (rightly so, there are feats being released all the time).

**Comment by mdang** [comment]
I just experienced this exact same issue. We're transitioning our REST API with Serverless, started with around 6 endpoints, everything worked perfectly. Then configured all the routes for the remaining 80 endpoints, transitioned controllers, etc, deployed the code and saw this error [Template may not exceed 460800 bytes in size.] 

I'm guessing our issue also has to be due to the high number of endpoints because the file itself is only 15kb, well under the maximum byte size. 

Do you guys recommend downgrading to v0.5.6?

**Comment by jordanmack** [comment]
> Do you guys recommend downgrading to v0.5.6?

@mdang At this point you can downgrade back to v0.5.6, or restructure your program into multiple smaller services. I downgraded since restructuring really isn't an option since I have a spec I need to adhere to.

@flomotlik Do you have any thoughts on this?

**Comment by mdang** [comment]
Thanks @jordanmack, I was hoping to avoid that but at this point it's better than losing all the work we already put into it. 

Did you have to do much to make your project backwards compatible with 0.5.6? I'm trying to look into what changes are needed in order to do that

**Comment by andymac4182** [comment]
@mdang You could try using some of the catch all routes and do some routing in the functions using something like KOA or Express.

**Comment by jordanmack** [comment]
> Did you have to do much to make your project backwards compatible with 0.5.6? I'm trying to look into what changes are needed in order to do that

@mdang In my case I didn't have to do anything since my changes for v1.0 were in their own branch. I just didn't merge. The two versions are pretty different, so there isn't too much you can do to make a v1.0 project backwards compatible with a v0.5.x version.

Perhaps @flomotlik will be able tell us what direction Serverless plans to take in the future, so we can figure out what the best approach is.

**Comment by doapp-ryanp** [comment]
I've started work on [a plugin](https://github.com/doapp-ryanp/serverless-plugin-swag) to address this issue (among others), as we are also unable to use v1 as it is architected.  In short using CloudFormation to manage API Gateway and Lambda plain does not work for us (README.md in my plugin goes into [specifics on why](https://github.com/doapp-ryanp/serverless-plugin-swag#why)).  IMO current v1 is good for development, but not a real world production environment.  We are stuck on `v0.5` for our existing workloads.

We prefer to let swagger be the interface to manage APIG and direct API integration to create and update Lambdas, while keeping permissions (IAM) and other not frequently changing resources in CloudFormation (or maybe Terraform).

Does anyone have similar sentiments?

**Comment by mdang** [comment]
@jordanmack I did some research and you're right. They're both pretty different and it would cause me to rewrite quite a bit, which normally wouldn't be a problem but in this case it's for an architecture that's being deviated quite a bit from. Sooner or later I'm going to have to transition it back to v1+. 

@andymac4182 You're a genius. I completely forgot I can use method **any** and have the function itself route the request to another controller. This might be my saving grace and allow me to salvage the work that went into it already. It'll allow me to combine a lot of my REST routes, I just hope that it's enough to overcome this limitation. I have around 86 endpoints, what's the most? 50? It doesn't really say. 

@doapp-jeremy If this was ready for use I'd install it in a heartbeat. I'll keep watching it 

Serverless is amazing, I hope this gets worked out because I can see it being a show stopper for many. I know it's still new but maybe consider a "gotcha" type page for people looking to use it for something like a full REST API

**Comment by doapp-ryanp** [comment]
@mdang it will prob be a few weeks til its ready.  

Unrelated - curious does my name show up as `doapp-jeremy` because I've had people mention me quite a few times lately on github as that.  Should be showing up as `doapp-ryanp`. Hopefully its just an autocomplete mixup.

**Comment by mdang** [comment]
@doapp-ryanp Oops, doapp-jeremy is the first option that comes up and I didn't pay attention before hitting enter

**Comment by jordanmack** [comment]
> Does anyone have similar sentiments?

@doapp-ryanp I don't have a firm stance on use of Swagger, but my experiences with CloudFormation have been very mixed. The noted limits from this issue aside, it's slow, quirky, and bug prone. Frankly, I don't trust the thing to consistently work right. The deployment method used in v0.5.6 had it's minor quirks, but I still view it as the better option.

**Comment by dougmoscrop** [comment]
@mdang have a look at serverless-http you can do a bunch of routing in one function. Separate by lifecycle (separate repos, separate deployments) and use shared libs.

**Comment by doapp-ryanp** [comment]
@johncmckim yea my question was more in regard to decoupling serverless v1 from cloudformation for create/update of APIGateway .  I have a substatial list of other reasons on why, but since it was large I didn't want to hijack this thread but I think for clarity I've changed my mind, and will put it inline:

-  CloudFormation has item limits (this issue)
-  It is not a security best practice to allow deletion of assets from an AWS API Key (can't back with MFA)
-  CloudFormation is very powerful.  We like to visually validate (via diff and CF web UI diff function) exactly what is going to change, not hide it in the framework internals.
-  Serverless [deletes and re-creates APIG distro on every update](https://github.com/serverless/serverless/issues/2530)
-  CloudFormation is not good for frequently changing assets because it sometimes gets into a update/rollback failed state.  You must delete CF and re-create.  Not fun hitting this in production
-  CloudFormation does not stay on top of new AWS features

**Comment by mdang** [comment]
@dougmoscrop Thanks, I didn't see that and this could be exactly what I need. So if I understand correctly, I would just have one service with one Lambda function that handles all the possible routes for the request? 

Today I went down the route of separating the app into 4 distinct services, however I quickly realized that having to have duplicates of all my library files, .env, packages doesn't make much sense. Not to mention my API now has 4 distinct endpoints that will need to be called within any client apps.

**Comment by jordanmack** [comment]
> Today I went down the route of separating the app into 4 distinct services, however I quickly realized that having to have duplicates of all my library files, .env, packages doesn't make much sense. Not to mention my API now has 4 distinct endpoints that will need to be called within any client apps.

@mdang I tried something similar as well. For me it doesn't work because of the way AWS handles mapping of paths to a custom domain. You cannot have two services that share same domain and path. For me that was a breaker since my API would then be out of spec.

I also hit the library problem. Fortunately that will be addressed soon. I know they are working on enhancing the include/exclude functionality. @doapp-ryanp also put together a [plugin](https://github.com/doapp-ryanp/serverless-plugin-browserify) that I believe would handle this situation.

**Comment by mdang** [comment]
@jordanmack It's nice to know I'm not the only one trying solutions like these, I was wondering if I was going the completely wrong direction. The solution with multiple services/host url's and duplication of libraries, etc is not ideal but I accepted that this is still really new and I'm going to have to redo this at some point, right now getting it to work is most important. Hopefully I can learn enough about how Lambda/API Gateway and Serverless work to make some contributions back some day.

**Comment by jordanmack** [comment]
It looks like there might be some new similar issues to this: #2853, #2605

Per flomotlik:
> We won't be able to fix this soon by ourselves as its an edge case and we need to prioritise other things higher for now.

**Comment by jordanmack** [comment]
@doapp-ryanp It doesn't look like this issue will be addressed by the Serverless team any time soon. Any new thoughts on how to implement a patch to work around this?

> Serverless deletes and re-creates APIG distro on every update

Is this being done because of issue #1684? If that's the case, then breaking up the CF template for the APIG deployment might still be a plausible solution. Since Serverless is doing a full delete and redeploy each time, the breakup process of the CF template could remain a "dumb" procedure that doesn't track resource changes in any way.

**Comment by doapp-ryanp** [comment]
@jordanmack I've begun work on a new serverless plugin https://github.com/doapp-ryanp/serverless-plugin-swag .  I haven't spent much time on it yet as I wanted to see what was going to be announced @ re:invent. Honestly I'm not sure when I will get time to work on it in the next few weeks - prob wont be til beginning of next year.  But I can assure you I have the same issues (and more) as you so I will have to address them at somepoint.

**Comment by asantibanez** [comment]
Hi! I also hit this issue today. Any workarounds? Thanks in advance. Don't know how to deploy my project now :(

**Comment by asantibanez** [comment]
`LogGroup`s are taking up space from the CF stack from what I have seen.

**Comment by jordanmack** [comment]
@asantibanez The only way to work around this that I'm aware of right now is to break up your service into several smaller services. Unfortunately there doesn't seem to be a good way to get around this right now.

**Comment by asantibanez** [comment]
Hey @jordanmack ! Just hit this issue today. Any luck or workaround with this issue? Don't know where to start fixing this. Any ideas? Saw the `nesting cf stacks` answers but that seems killer.

**Comment by pmuens** [comment]
Notifying @nicka about this one as he has experience with this.

You can use `Fn::ImportValue` (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html) to reference stuff in other stacks.

**Comment by mwawrusch** [comment]
Any updates on this? This is
* A show stopper
* Will delay our launch

**Comment by nicka** [comment]
@jordanmack is right! Depending on your setup, another solution could be grouping functions and using something like [serverless-http](https://github.com/dougmoscrop/serverless-http).

```
functions:
  foo:
    handler: handler.foo
    events:
      - http: # Catch all proxy useful for express/koa apps
          path: '{proxy+}'
          method: any
```

@asantibanez @mwawrusch We're currently splitting our stacks(services) with `Fn::ImportValue`'s as they are the most flexible(for us). Please check (https://www.youtube.com/watch?v=TDalsML3QqY) from 13:27.

Should the framework do all of this? It would definitely be possible for the framework to do all the heavy lifting for you, but IMHO this would become very complex fast. As a developer I think you'd rather have control over this your self(think about order of stack deployments etc.).
