### ISSUE TITLE
Cannot use Serverless variables in provider 1.0.2

### ISSUE THREAD

**Issue by jordanmack** [serverless/serverless#2389]
# This is a Bug Report
## Description
- What went wrong?

When trying to use a Serverless variable for the provider in serverless.yml the following error was received:

```
     Provider "${file(../lib/mixins.yml):provider}" is not
     supported. Valid values for provider are: aws, azure,
     google, ibm. Please provide one of those values to the
     "provider" property in serverless.yml.
```
- What did you expect should have happened?

It should have parsed the variable normally.
- What was the config you used?

serverless.yml:

```
service: test

provider: ${file(./serverless-mixins.yml):providerDefault}

functions:
  hello:
    handler: handler.hello
```

serverless-mixins.yml:

```
providerDefault:
  name: aws
  runtime: nodejs4.3
```
- What stacktrace or error message from your provider did you see?

See above.
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.2
- **_Operating System**_: Windows 10 x64
- **_Stack Trace**_: N/A
- **_Provider Error messages**_: See above.
