### ISSUE TITLE
Variables -- how to refer to function ID within function?

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2405]
This may be pushing the limits of what serverless.yml variables are meant to do.

Here's a snippet of my serverless.yml:

```
functions:
    run:
        name: ${self:service}-feed---run---${opt:stage}
        handler: handler.run
        timeout: 20
        events:
            - sns: run---${self:service}-feed---${opt:stage}
```

I'd like to be able to refer to the name "run" (the function's ID / name before the custom "name" field is applied to it) from inside that function definition, something like this:

```
functions:
    run:
        name: ${self:service}-feed---${WHAT GOES HERE THAT = "run"?}---${opt:stage}
        handler: handler.${WHAT GOES HERE THAT = "run"?}
        timeout: 20
        events:
            - sns: ${WHAT GOES HERE THAT = "run"?}---${self:service}-feed---${opt:stage}
```

Is there such a thing?

Thanks
