### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2411]
# This is a Feature Proposal
## Description

Aliasing functions can help users with including functions deployed through serverless into systems that are not deployed through serverless. To that end we should have a simple configuration option to deploy aliases

``` yaml
functions:
  hello:
    handler: handler.hello
    alias: somealias
```

``` yaml
functions:
  hello:
    handler: handler.hello
    aliases:
      - somealias
      - anotheralias
```

Aliases will always point to the latest deployed version. As we don't have versioning support in our Lambda support Aliases are simply a nicer way to name your Lambda Function ARN than using $LATEST.

Similar or dependent issues:
- #1457
## Additional Data
- **_Serverless Framework Version you're using**_:
- **_Operating System**_:
- **_Stack Trace**_:
- **_Provider Error messages**_:

**Comment by kfloz** [comment]
This is great and much needed thanks!  If an alias is defined for a function, serverless should use the alias in the relevant provisioned event source mappings instead of the actual ARN 

e.g APIG Integration Requests Lambda config 

Great stuff!

**Comment by flomotlik** [comment]
@kfloz we're not going to use the alias as its not exposed inside of CF. We could not rely solely on built-in CF functions like Ref or GetAtt which would make the code more brittle.

**Comment by flomotlik** [comment]
I had some great conversations about this at SLSConf and the main issue with Aliases here is that because we deploy through Cloudformation there is only one version available, so aliasing doesn't really make a lot of sense here as the LATEST will always point to any alias we can set here. Its even going to be an issue because users might think the alias sticks around or points somewhere else, when in reality it doesn't.

So I'm going to close this for now and we're not going to implement alias support for now.

**Comment by mikeplavsky** [comment]
@flomotlik There can be several aliases pointing to the same versions. If there is an alias per Customer, then it allows such things as: 1) Monitoring per Customer 2) Triggering of Lambda function per Customer 3) And finally Lambda knows which Customer called by using```context.invoked_function_arn```

So it helps with multi-tenancy a little.

**Comment by arabold** [comment]
@flomotlik Currently there is no open feature/ticket for alias support in Serverless. Does that mean this is completely off the table for good or is aliasing support still planned?

**Comment by pmuens** [comment]
@mikeplavsky @arabold reopening this one as Lambda versioning was merged recently (see https://github.com/serverless/serverless/pull/2676) and aliases might be a good addition here.

However we need to investigate the comment above about the usefulness when deploying through CloudFormation: https://github.com/serverless/serverless/issues/2411#issuecomment-257269555

Any feedback or comments about that are appreciated 👍

**Comment by arabold** [comment]
To elaborate on our use case for aliases a bit and keep the discussion going: We have a set of 150 distinct Lambda functions for various modules. Basically our whole backend is server-less and designed around AWS Lambda. With that number of functions it's not practical for us to have different function names for every stage (e.g. append a "`-dev`", "`-user1`", "`-user2`", "`-test`", etc.). Due to the number of different stages/environments, having dedicated AWS accounts isn't a solution either. We certainly prefer aliases instead. So if "`user1`" deploys something to his stage "`user1`", we create a new Lambda version and tag it with "`user1`". Through API Gateway this stage can be mapped and directly accessed via something like https://api.example.com/user1/function-name. `$LATEST` is always pointing to the latest version - that's okay, nobody is using it. Version x and y can be completely different branches with different environment variables and configuration. It doesn't matter as we're always accessing Lambdas via their alias, never via a version number. Same is true if we want to create end-user facing versions for our API Gateway. We can label a version "`v1`" and another one "`v2`" and distinguish different API versions this way and even update them independently.

SLS 0.5.6 did offer this functionality and it's working nicely for us. For every environment we want to support we have a dedicated stage. AWS Lambda has perfect support for this, too, as it shows the stats for every alias independently. So if you check the stats for alias "`test`" you can see all invocations, latencies and error rates independently from which version number it was and is. It shows the stats of all versions ever tagged `test`. 

My request is to bring this functionality back to SLS 1.0. I want to be able to directly map stages/environments to AWS Lambda aliases.

**Comment by arabold** [comment]
I've finally found time to dive deeper into Serverless 1.4. Up to this point we're still on 0.5 and have our own fork that addresses some of the issues left open in the old version. 

From the structure of 1.x it seems the cleanest solution would be to give the user more granular control over the naming of Lambda functions and API Gateway endpoints via a handful of new options in the `.yaml` config. Here's what I have in mind:

```yaml
service: myService

provider:
  # ...

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

functions:
  createUser:
    handler: handler.createUser
    name: ${self:service}-myFunc # Overwrite the default Lambda name to NOT include the stage anymore
    alias: ${self:custom.stage} # Instead create an alias that points to the latest deployed version
```

The `name` property would control the Lambda function name. Instead of `myService-dev-myFunc` it would become `myService-myFunc` per configuration above.
The `alias` property automatically tags the latest deployed version number with the alias name defined, in this case the stage name. But this could be anything the user might want, e.g. `v1` vs `v2` if a new generation of an API is released, etc.

To me this seems like a clean solution that fits into the framework without breaking core principles. The events would have to be updated to respect the new name and alias (if an alias is defined the event must trigger the Lambda function with that alias as qualifier instead of `$LATEST`).

The final piece would be support for stages in API Gateway (see #2445). This could work implicitly via the `alias` property but I think we would do better with a separate configuration option that controls the API Gateway API name. This would probably have to go somewhere in the main properties like this (not sure which syntax would make sense here):

```yaml
service: myService

provider: 
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  apig:
    name: ${self:service}
    stage: ${opt:stage, self:provider.stage}
```

Any thoughts?
