### ISSUE TITLE
Lambda-proxy is not being set

### ISSUE THREAD

**Issue by jsnowacki** [serverless/serverless#2413]
# This is a Bug Report 

## Description

The bug has been discovered using [serverless-wsgi](https://github.com/logandk/serverless-wsgi). The package requires `lambda-proxy` to be set as follows (in my project):
```yaml
events:
      - http:
          path: task
          method: get
          integration: lambda-proxy
          cors: true
```

For bug reports:
* What went wrong?
  * Despite `integration: lambda-proxy`, integration is just `lambda` not `lambda-proxy`; no error is issued.
* What did you expect should have happened?
  * Integration should be set to `lambda-proxy`
* What was the config you used?
  * As above.
* What stacktrace or error message from your provider did you see?
  * None; everything goes through fine.

## Additional information
* When I set it manually in the AWS console, it remains `lambda-proxy` for future deployment. 
* Deploying with and without CORS does not change anything.
* New API endpoints also does not have `lambda-proxy` even if the others have been changed to  `lambda-proxy`.

* ***Serverless Framework Version you're using***:
1.0.0-rc.2
* ***Operating System***:
Windows 10 and Ubuntu 14.04 LTE

**Comment by fruffin** [comment]
@jsnowacki  I had the opposite problem when upgrading to the RTW version. It was defaulting to lambda-proxy when I needed just "lambda" (I didn't have anything set). My API was set in proxy mode in the console, so I'd say just upgrade serverless and everything should run fine.

**Comment by jsnowacki** [comment]
@fruffin Thank you for the suggestion. Indeed, I was a bit behind with the version. 

I have updated to Serverless 1.0.2 and added another endpoint to the existing one, i.e.:
```yaml
events:
      - http:
          path: task
          method: get
          integration: lambda-proxy
          cors: true
      - http:
          path: baz
          method: get
          integration: lambda-proxy
          cors: true
```
But now when I try to deploy it I get the below error:
```
Serverless: Packaging Python WSGI handler...
Serverless: Packaging required Python packages...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
................Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: ApiGatewayResourceTaskIdVar
     - Another resource with the same parent already has
     this name: {id}.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 linux
     Node Version:       4.6.0
     Serverless Version: 1.0.2
```
