### ISSUE TITLE
severless deploying bloated functions

### ISSUE THREAD

**Issue by n8sabes** [serverless/serverless#2427]
Severless v1.0.2 `sls deploy` deploys all functions with the same huge size (aggregate size of all functions). Appears to be .zip of everything used for each function.

Subsequent `sls deploy function -f funcName` deploys individual functions as their proper isolated smaller code size.

`sls deploy` should deploy each function as its own isolated size.

To Reproduce:
1. Create a service with multiple functions (foo1, foo2, bar1, bar2)
2. `sls deploy`
3. Check Lambda function sizes in AWS Console -- all are the same size (incorrect, bloated)
4. `sls deploy function -f foo1`
5. Check Lambda foo1 function size, it will be 1/4th the size (correct)

BTW -- It would be great to have the serverless-optimizer-plugin back for v1.0... or better, webpack2 tree-shaking.

**Comment by DavidWells** [comment]
@n8sabes have you tried out the webpack plugin? https://github.com/elastic-coders/serverless-webpack

**Comment by n8sabes** [comment]
Yes, I'm using `serverless-webpack` due to ES6 / babel requirements.

It appears expected behavior is possible via packaging for non-webpack:

```
package:
  individually: true
```

For non-webpack, it seems individual packaging should be the deployment default.

This doesn't work for webpack (ES6 babel requirements), but @gertjvr has pointed to a serverless-webpack PR fix https://github.com/elastic-coders/serverless-webpack/issues/48

Seems like a shortcoming / bug as-is in v1.0.2.

**Comment by gertjvr** [comment]
> This doesn't work for webpack (ES6 babel requirements)
Confused at to why serverless-wepack isn't working for you? my latest serverless service is using lastest preset and its work as expected

**Comment by n8sabes** [comment]
After updating to the recommended syntax and serverless-webpack PR 48, still not working and get deployment bloat.

It would be of value to have an example project for v1.0.2 that:

1. has multi-functions
2. uses webpack (for babel ES6/ES7 support)
3. functions link different code from common library directory (thus different sizes, and code re-use)
4. correctly deploys individually packaged functions (preventing bloat)

On packaging: It seems current sls packaging behavior should be reversed, whereas v1.x `sls deploy` defaults to individually packaged functions to prevent unnecessary deployment bloat.

**Comment by briguy202** [comment]
@n8sabes, I believe I have the same issue.  I have multiple functions, a single serverless.yml and webpack.config.js, and want as a result a single API Gateway deployed with multiple, properly sized Lambda functions running through Webpack for transpilation.  The only workaround I've been able to find so far is this:

In my serverless.yml, I have:
```
...
plugins:
  - serverless-webpack
package:
  individually: true
functions:
  somefunc:
    name: somefunc
    handler: index.handler
    package:
      exclude:
        - "!*(somefunc.js)"
...
```
I used a glob pattern to remove out the non-relevant code for the individual package.  Then in my webpack.config.js I use multiple `entry` values to split into the individual lambda functions.

It's not the best, and I agree that it would be nice to see this type of use case supported, but it at least allows us to move forward without deploying the entire app into each Lambda.

**Comment by n8sabes** [comment]
Thanks @briguy202, @gertjvr, et al. I have a configuration that works.

**Step 1 - Install serverless-webpack PR48**
`npm i -g elastic-coders/serverless-webpack#pull/48/head`

**Step 2 - Configure `serverless.yml`**
```
service: example
provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: nodejs4.3
plugins:
  - serverless-webpack
package:
  individually: true
  exclude:
    - "*.json"
functions:
  echo:
    handler: echoHandler.handler
    package:
      exclude:
        - "!*(echoHandler.js)"
    events:
      - http:
          path: echo
          method: post
  foo:
    handler: fooHandler.handler
    package:
      exclude:
        - "!*(fooHandler.js)"
    events:
      - http:
          path: foo
          method: get
  bar:
    handler: barHandler.handler
    package:
      exclude:
        - "!*(barHandler.js)"
    events:
      - http:
          path: bar
          method: get
```

**Step 3 - Configure `webpack.config.js`**
```
const path = require('path');
module.exports = {
  target: 'node',
  entry: {
    'echoHandler': './echoHandler.js',
    'fooHandler': './fooHandler.js',
    'barHandler': './barHandler.js',
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  externals: [
    'aws-sdk', // aws-sdk included in Lambda
  ],
  resolve: {
    root: __dirname,
  },
  module: {
    preLoaders: [
      { test: /\.js$/, exclude: /node_modules/, loader: 'eslint' },
    ],
    loaders: [
      { test: /\.js$/, loaders: ['babel'], exclude: /node_modules/ },
      { test: /\.json$/, loader: 'json' },
    ],
  },
  plugins: [
  ],
  target: 'node',
  devtool: 'source-map',
};
```

**Step 4 - Create three handlers [fooHandler.js, barHandler.js, echoHandler.js] as such (each with some code variations to demonstrate size diff):**
```
'use strict';
module.exports.handler = (event, context, callback) => {
  const spreadTest = { c: 3, d: "d"};
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: {
        text: "foo!",
        a: 1,
        b: "b",
        ...spreadTest,   // requires babel object spread polyfill
      },
      input: event,
    }),
  };

  callback(null, response);
};
```

**Step 5 - Deploy**
`sls deploy`
This should deploy correct size functions.
