### ISSUE TITLE
API Keys don't work unless attached to a usage plan 

### ISSUE THREAD

**Issue by davidduffett** [serverless/serverless#2450]
# This is a Bug Report
## Description

Creating API Keys and marking endpoints as `private` does not actually enable those API keys to be used against any endpoints in API Gateway.  Instead those endpoints just return `403 Forbidden`, whether you provide an API key or not.

In order for API keys to work, you need to:
1. Create a usage plan (it does not have to have any throttling or quota)
2. Add your API and stage to the usage plan
3. Add your API key to the usage plan

I haven't got a proposal at present for how serverless could support usage plans, just informing that API keys do not currently work as specified in serverless documentation without extra manual work setting up the usage plan.

Similar or dependent issues:
- #2058

**Comment by flomotlik** [comment]
@davidduffett we'll look into this and report back. Thanks for bringing it up

**Comment by ansraliant** [comment]
I'm also affected by this. Serverless Deploy generates the API Keys correctly, but you you have to assign manually the keys as @davidduffett describes.

**Comment by ansraliant** [comment]
According to the [Cloud Formation Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplan.html) it is possible to create a usage plan with Cloud Formation, BUT it does not say anything about assigning an API Key to a Usage Plan. That would cover half our problem at least. [It's something](http://i2.kym-cdn.com/photos/images/newsfeed/000/114/139/tumblr_lgedv2Vtt21qf4x93o1_40020110725-22047-38imqt.jpg)

**Comment by jong-eatsa** [comment]
+1

**Comment by pmuens** [comment]
Just leaving this link here: http://stackoverflow.com/a/39919130

I started tto work on this today as our integration tests (see #2655) also suffer from this.
Unfortunately you can only create the usage plan but not associate a key with a usage plan through CloudFormation right now. This lack of functionality makes it not possible to implement this right now 😢

**Comment by zaklampert** [comment]
Is there any more succinct instruction to setting up api keys? I'm attempting to follow david's instructions to no avail (still getting forbidden).

**Comment by pmuens** [comment]
Usage plan support was introduced recently: https://aws.amazon.com/de/about-aws/whats-new/2017/03/aws-cloudformation-supports-authoring-templates-with-code-references-and-amazon-vpc-peering/

**Comment by rentrop** [comment]
Any updates?

**Comment by pmuens** [comment]
@rentrop not yet. This issue is on our todo list and we'll look into it soon!

The last update was that it's not possible to establish a connection between the usage plan resource and the API key resource in CloudFormation. Don't know if that's changed in the meantime 🤔 .

**Comment by rentrop** [comment]
@pmuens Thanks for the quick response

**Comment by laardee** [comment]
@pmuens, have you already started to implement this? I ran into the same problem and I could try to fix this. It is now possible to with `AWS::ApiGateway::UsagePlan` and `AWS::ApiGateway::UsagePlanKey`. At least it worked when I created an API Gateway with vanilla CloudFormation (which is a horrible task to do compared how easy it is with the Serverless...).

**Comment by pmuens** [comment]
Awesome! Thanks for working on that @laardee (already saw the PR 🎉 ).

There's no other implementation in the pipeline yet, so this is the perfect timing. Really excited about that feature 👍

**Comment by softprops** [comment]
the documentation says this is optional https://serverless.com/framework/docs/providers/aws/events/apigateway#setting-api-keys-for-your-rest-api

> When using API keys, you can _optionally_ define usage plan quota and throttle, using usagePlan object.

Is this really the case?

**Comment by elyobo** [comment]
Doesn't appear to be optional; not creating a usage plan seems to result in no API keys being created.

**Comment by FarwaCielo** [comment]
is there any update on this issue? I ran into same problem. My serverless configuration for api keys and usage plan looks like this:
```
custom:
  customDomain:
    domainName: ${file(../.././variables-${self:provider.stage}.yml):domainName}
    stage: ${self:provider.stage}
    basePath: 'myrules'
    endpointType: ${file(../.././variables-${self:provider.stage}.yml):endpointType}
    certificateArn: ${file(../.././variables-${self:provider.stage}.yml):certificateArn}
    certificateName: ${file(../.././variables-${self:provider.stage}.yml):certificateName}
    createRoute53Record: ${file(../.././variables-${self:provider.stage}.yml):createRoute53Record}
    hostedZoneId: ${file(../.././variables-${self:provider.stage}.yml):hostedZoneId}
  apiKeys:
   - name: ${file(../.././variables-${self:provider.stage}.yml):ServerlessCoreAPIKey}
  usagePlan:
    name: CieloRestAPIUsage
    throttle:
      burstLimit: 2000
      rateLimit: 5000
```
When i deploy it following configuration is done which is not what I was expecting:
