### ISSUE TITLE
Failed to deploy on v1.0.2

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#2459]
# This is a Bug Report
## Description

For bug reports:
- What went wrong?
  I updated Serverless to v1.0.2 from v1.0-rc2 on my project. 
  When v1.0-rc2, it has been successful, but v1.0.2 failed.
- What was the config you used?
  my `serverless.yml` as follow

``` yml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: shifter-beta # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  stage: development
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:table/Site"
        - "arn:aws:dynamodb:us-east-1:*:table/SiteProgress"
        - "arn:aws:dynamodb:us-east-1:*:table/FbUsers"
        - "arn:aws:dynamodb:us-east-1:*:table/Archive"
        - "arn:aws:dynamodb:us-east-1:*:table/SiteGenLog"
        - "arn:aws:dynamodb:us-east-1:*:table/SiteGenLog-development"
        - "arn:aws:dynamodb:us-east-1:*:table/CloudFrontTransaction"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - "arn:aws:lambda:us-east-1:*:function:docker-swarm-controller"
        - "arn:aws:lambda:us-east-1:*:function:site-gen-start"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - "arn:aws:lambda:us-east-1:*:function:docker-swarm-controller"
        - "arn:aws:lambda:us-east-1:*:function:site-gen-start"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::sys.status.getshifter/*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::wp-archives-files/*"
    - Effect: "Allow"
      Action:
        - "cloudfront:GetDistributionConfig"
        - "cloudfront:UpdateDistribution"
      Resource:
        - "*"

# you can add packaging information here
package:
  include:
    - src/
  exclude:
    - client/
    - doc/
#  artifact: my-service-code.zip

functions:
  staticsites:
    handler: src/staticsites.handler
    events:
      - http:
          path: staticsites/{site_id}
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: staticsites/{site_id}
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: staticsites/{site_id}
          method: delete
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  fbusers:
    handler: src/fbusers.handler
    events:
      - http:
          path: fbusers
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: fbusers
          method: post
          cors: true
  archives:
    handler: src/archives.handler
    events:
      - http:
          path: archives
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: archives/{archive_id}
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: archives/{archive_id}
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: archives/{archive_id}
          method: delete
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: archives/{archive_id}
          method: put
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  websites:
    handler: src/websites.handler
    events:
      - http:
          path: websites
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: websites/{site_id}
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: websites
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: websites/{site_id}
          method: delete
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: websites/{site_id}
          method: put
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  containers:
    handler: src/containers.handler
    events:
      - http:
          path: containers/{site_id}
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: containers/{site_id}
          method: put
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: containers/{site_id}
          method: delete
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
      - http:
          path: containers/{site_id}
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  generatehistory:
    handler: src/generatehistory.handler
    events:
      - http:
          path: generatehistory/{site_id}
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  transactions:
    handler: src/transactions.handler
    events:
      - http:
          path: transactions/{distribution_id}
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  authorizerFunc:
    handler: src/authorizer.handler

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

```
- What stacktrace or error message from your provider did you see?
  Cloudformation log as follow

```
$sls deploy -v --stage test2
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - shifter-beta-test2
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - shifter-beta-test2
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - shifter-beta-test2
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - WebsitesLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - TransactionsLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ArchivesLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ContainersLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - StaticsitesLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - GeneratehistoryLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - FbusersLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - AuthorizerFuncLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - ContainersLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - TransactionsLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - TransactionsLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ArchivesLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - ArchivesLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceFbusers
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - WebsitesLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceFbusers
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - WebsitesLambdaFunction
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - GeneratehistoryLambdaFunction
CloudFormation - CREATE_FAILED - AWS::ApiGateway::Resource - ApiGatewayResourceFbusers
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - FbusersLambdaFunction
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - StaticsitesLambdaFunction
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - AuthorizerFuncLambdaFunction
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - shifter-beta-test2
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - shifter-beta-test2
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - FbusersLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceFbusers
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - StaticsitesLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - ArchivesLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::Resource - ApiGatewayResourceFbusers
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - WebsitesLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - StaticsitesLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - ArchivesLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - FbusersLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - AuthorizerFuncLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - TransactionsLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - ContainersLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Function - GeneratehistoryLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - AuthorizerFuncLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - WebsitesLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - GeneratehistoryLambdaFunction
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - TransactionsLambdaFunction
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - shifter-beta-test2
Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: ContainersLambdaFunction
     - The role defined for the function cannot be assumed
     by Lambda..

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.7.0
     Serverless Version: 1.0.2

```
## Additional Data
- **_Serverless Framework Version you're using**_:1.0.2
- **_Operating System**_:OS X Elcapitan 10.11.2
- **_Template**_:aws-nodejs
