### ISSUE TITLE
Stack launch failure in case resources from serverless.yaml depend on the API Gateway resources, because that would be created in a later step

### ISSUE THREAD

**Issue by cristim** [serverless/serverless#2462]
# This is a Bug Report

## Description

* What went wrong?
 - Stack creation fails in case there are resources that depend on the ApiGatewayRestApi resource. That resource is created in the template used for the stack update, while the resources that would depend on it are attempted to be created from the very beginning.
* What did you expect should have happened?
 - The stack creation should work, the resources specified in serverless.yaml should be applied only in the update step, when the ApiGatewayRestApi resource is available.
* What was the config you used?
 - I have a CloudFront resource in front of my APIG, and I am trying to configure it to use the APIG as an origin:
```
[...]
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          DefaultRootObject: ''
          Enabled: true
          DefaultCacheBehavior:
            AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
            ForwardedValues:
              QueryString: true
            MinTTL: '0'
            TargetOriginId: ${opt:stage}-api-gateway
            ViewerProtocolPolicy: redirect-to-https
          Origins:
          - CustomOriginConfig:
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
              - TLSv1.1
              - TLSv1.2
            OriginPath: "/${opt:stage}"
            DomainName:
              Fn::Join:
              -
              - - Ref: ApiGatewayRestApi
                - ".execute-api."
                - Ref: AWS::Region
                - ".amazonaws.com"
            Id: ${opt:stage}-api-gateway
```

* What stacktrace or error message from your provider did you see?
```
Serverless: Creating Stack...
 
  Serverless Error ---------------------------------------
 
     Template format error: Unresolved resource dependencies
     [ApiGatewayRestApi] in the Resources block of the template
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Infomation -----------------------------
     OS:                 linux
     Node Version:       6.3.1
     Serverless Version: 1.0.2
```
## Additional Data

* ***Serverless Framework Version you're using***: 1.0.2
* ***Operating System***: Ubuntu
* ***Provider Error messages***: see above
