### ISSUE TITLE
v1.0.2 won't allow two http functions with same path / different HTTP methods 

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2469]
Section of serverless.yml:

```
functions:
    getxml:
        name: ${self:service}-getxml---run---${opt:stage}
        handler: wsgi.strip
        timeout: 20
        events:
            - http:
                path: send-template.xml
                method: get
                integration: lambda-proxy
    postxml:
        name: ${self:service}-postxml---run---${opt:stage}
        handler: wsgi.strip
        timeout: 20
        events:
            - http:
                path: send-template.xml
                method: post
                integration: lambda-proxy
```

The paths are the same, but the methods are different, GET vs. POST.

In v.1.0.0-rc.2, this was fine -- deployed many times, ran fine.  I upgrade to v1.0.2 and now when I try to deploy, I get this error:

```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..........................Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ApiGatewayResourceSendDashtemplatexml
     - Another resource with the same parent already has
     this name: send-template.xml.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.3.1
     Serverless Version: 1.0.2
```

It appears this happened during deployment -- SLS didn't object but AWS did.  Was there a change to the CF naming conventions or anything else between these versions that would prevent the 1.0.2 deployment from refreshing / overwriting the 1.0.0-rc.2 deployment?

Thanks
