### ISSUE TITLE
1.0.2 does not enact the package-exclude directive

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2471]
Snippet of serverless.yml:

```
package:
    exclude:
        - notes
```

Running v1.0.0-rc.2, the "notes" directory was excluded.  Now running 1.0.2, it is not excluded.  The serverless.yml file has not changed.

**Comment by pmuens** [comment]
@chris-hailstorm Thanks for reporting 👍 

Serverless v1.0 has switched to globs for excluding. Here's a link to the docs: https://serverless.com/framework/docs/guide/packaging/#excluding-files-from-packaging

**Comment by chris-hailstorm** [comment]
Tried this:

```

package:
    exclude:
        - notes/**
```

and this: 

```
package:
    exclude:
        - ./notes/**
```

In both cases, directory notes and its two files are still in the zip file:

```
      905  10-19-16 19:30   node_modules/wrappy/wrappy.js
       57  10-19-16 19:30   notes/to-deploy.txt
       80  10-19-16 19:30   notes/to-invoke.txt
    80176  10-19-16 19:30   vendored-copy/ipaddress.py
 ```

??

**Comment by chris-hailstorm** [comment]
I like the idea of globs but per my second comment, either they're not working or the syntax is not obvious.

**Comment by pmuens** [comment]
Hmm. That's strange. Works for me.

Here's me `serverless.yml`:

```yml
service: my-test-service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello

package:
  exclude:
    - notes/**
```

And here's the directory structure:

![bildschirmfoto 2016-10-20 um 07 46 05](https://cloud.githubusercontent.com/assets/1606004/19547595/65a0f5d2-9699-11e6-86bf-782a5c1ab220.png)

When I run `serverless deploy --noDeploy` and inspect the zip file I cannot find the `notes` directory.
