### ISSUE TITLE
Template format error: Resource name *** is non alphanumeric

### ISSUE THREAD

**Issue by adambiggs** [serverless/serverless#2474]
# This is a Bug Report

### What went wrong?
Can't deploy DyanmoDB stream event modifications due to "resource name is non alphanumeric" errors.

### What did you expect should happen?
The function should deploy without errors.

### What was the config you used?
Relevant config (tables without `_` in the name seem to work fine):

```yml
functions:
  backup:
    # ...
    events:
      - stream: arn:aws:dynamodb:us-east-1:***:table/prod.table_name/stream/2016-08-06T23:50:59.100
    # ...
```

### What stacktrace or error message from your provider did you see?
```
Template format error: Resource name BackupEventSourceMappingDynamodbProdtable_name is non alphanumeric.
```

### Similar or dependent issues:
* #2017

## Additional Data

* ***Serverless Framework Version you're using***: v1.0.2
* ***Operating System***: OSX 10.11.6
