### ISSUE TITLE
Trigger multiple functions from events on same S3 bucket, not working.

### ISSUE THREAD

**Issue by bdruth** [serverless/serverless#2475]
Looking at the new docs here: https://serverless.com/framework/docs/providers/aws/events/s3/#s3 and trying to follow them so that I have one bucket where 3 different Lambda functions are invoked based on the suffix of the file uploaded, and it's not working ... by which I mean, serverless isn't generating the CF template for it. It actually doesn't have *any* event configuration for the lambdas at all. The only thing it has is a generated bit from custom resource configuration where I set the CORS policy on the S3 bucket.

Here's what I have ...

```
functions:
  firstFn:
    handler: lib/first_fn.firstFn
    rules:
      - s3:
        bucket: ${self:custom.vars.bucketIn}
        event: s3:ObjectCreated:*
        rules:
          - suffix: manifest.json
  secondFn:
    handler: lib/second_fn.secondFn
    rules:
      - s3:
        bucket: ${self:custom.vars.bucketIn}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .ext1
  thirdFn:
    handler: lib/third_fn.thirdFn
  fourthFn:
    handler: lib/fourth_fn.fourthFn
    rules:
      - s3:
        bucket: ${self:custom.vars.bucketIn}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .ext2
```

**Comment by bdruth** [comment]
So, there's a few issues here - first, the docs are inconsistent and incorrect, I think - you'll see them reference
```
functionName:
  events:
...
```
as well as
```
functionName:
  rules:
...
```
As near as I can tell in the specs, the former is actually the correct syntax.

That said, it doesn't actually work. If I provide
```
  functionName:
    events:
      - s3:
        bucket: ${self:custom.vars.bucketIn}
        event: s3:ObjectCreated:*
```
It doesn't result in any CF configuration for the bucket. The only thing that seems to generate any configuration is ``- s3: <bucketname>`` and this then generates just the default event definition.
```
    events:
      - s3: ${self:custom.vars.bucketIn}
```
Doing something like:
```
      - s3:
        bucket: ${self:custom.vars.bucketIn}
        event: s3:ObjectCreated:*
        rules:
          - suffix: manifest.json
```
Should generate the expected CF template and repeating this on different functions, with the same bucket name, but different rules, should generate different event definitions on the same bucket.

What is bizarre is that I see specs testing this here -> https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/compile/events/s3/tests/index.js#L130, but I can't get the same type of configuration to work.

**Comment by mthenw** [comment]
@bdruth the main issue with your config is that 

```
  functionName:
    events:
      - s3:
        bucket: ${self:custom.vars.bucketIn}
        event: s3:ObjectCreated:*
```

is not equal to
```
  functionName:
    events:
      - s3:
          bucket: ${self:custom.vars.bucketIn}
          event: s3:ObjectCreated:*
```

The indention here is important. Please update you config and let me know if it's working.

**Comment by bdruth** [comment]
OK - that worked, but - wow - that's super not obvious. Why the double-indent there? What's that for? Everything else is indented one level?! Also, I think there's still a documentation error with this block:
```
functions:
  users:
    handler: users.handler
    rules:
      - s3:
          bucket: photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
```
Note the ``rules:`` under ``handler: users.handler``.

**Last question** - I noticed that the generated ``AWS::S3::Bucket`` doesn't carry any ``DependsOn`` properties for the ``AWS::Lambda::Function`` definitions - in my experience, this is needed as the Lambda needs to exist before CF tries to associate the events on the bucket - I think AWS "tests" if the event notification would work and the Lambda needs to exist for that to pass.
