### ISSUE TITLE
setting multiple allowed-origins in CORS results in AWS APIG that defies W3C

### ISSUE THREAD

**Issue by jokeyrhyme** [serverless/serverless#2476]
# This is a Bug Report
- What went wrong?

TL;DR: Access-Control-Allow-Origin header contains multiple origins, which violates the W3C specification and makes Chrome cranky

There's a combination of things here...

The documentation and YAML structure imply that multiple allowed-origins for CORS settings are supported, because it is a list with plural name (origins), and not a string with a singular name (origin):

https://serverless.com/framework/docs/providers/aws/events/apigateway/#enabling-cors-for-your-endpoints

``` yaml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: user/create
          method: get
          cors:
            origins:
              - '*'
```

Serverless seems to configure a static HTTP response header for Access-Control-Allow-Origin, with a string value that is a comma-delimited version of the list that we specify in the YAML.

This is against the W3C CORS specification, and Chrome complains (in the console) when it sees `Access-Control-Allow-Origin: https://origin1.com,https://origin2.com`

https://www.w3.org/TR/cors/#resource-requests

> add a single Access-Control-Allow-Origin header, with either the value of the Origin header or the string "*" as value

The Access-Control-Allow-Origin header has to be a single origin that is the same as the incoming Origin header, or the wildcard "*". It is not allowed to be multiple origins. I would think that this design is to avoid information disclosure, to prevent a failed pre-flight check from telling malicious parties all about all the other origins that can try.

Unfortunately, AWS API Gateway itself only supports a single allowed-origin, probably to simplify implementation and improve the performance of the service:

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html

> Use the console-provided value of '_*' as the Access-Control-Allow-Origin header value to allow access requests from all domains, or specify a named domain to all access requests from the specified domain

"a named domain" - singular
- What did you expect should have happened?

For example, say I allow 2 origins: https://origin1.com and https://origin2.com
- request from https://origin1.com = Access-Control-Allow-Origin: https://origin1.com
- request from https://origin2.com = Access-Control-Allow-Origin: https://origin2.com
- request from https://origin3.com = no CORS headers

Server-side web server frameworks like Hapi.js support configuring multiple allowed-origins, but only ever actually respond with the incoming request Origin header if there is a match:

https://github.com/hapijs/hapi/blob/v15.1.1/lib/cors.js#L85

Ideally, AWS APIG would support multiple headers to be configured, and perform this request-time match for us. But that doesn't seem available just now.

Alternatively, is it possible to achieve this sort of matching with an APIG response header template that Serverless defines?
- What was the config you used?

``` yaml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: user/create
          method: get
          cors:
            origins:
              - https://origin1.com
              - https://origin2.com
```
- What stacktrace or error message from your provider did you see?

n/a
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.0-rc.2
- **_Operating System**_: macOS Sierra
