### ISSUE TITLE
Feature request: create CloudWatch alarms for invocation errors

### ISSUE THREAD

**Issue by cristim** [serverless/serverless#2478]
# This is a Feature Proposal
## Description

It would be nice to have serverless generate CloudWatch alarms for lambda function metrics, on a per-function basis, so we can easily get notified when something goes wrong with our function.
- Duration > defined value
- Errors > defined value
- Throttles > defined value
- Invocations < or > defined value, depending on use case

Since the invocations alert would make sense to alert when there were no invocations (like if someone disabled the Cloudwatch event and the function stops running), it would be nice to support both comparison operators.

The alerts should be configured automatically to use an SNS topic and accept any target supported by SNS

The config would look like this:

```
functions:
  myfunction:
    handler: handler.myhandler
    memorySize: 512
    events:
      - http:
          method: get
          path: mypath
    [...]
    alarms:
    - Duration: # name of the metric
        Period: 300 # expressed in seconds?
        Threshold: 10000 # expressed in milliseconds?
        Statistic: Average  # anything that CloudWatch supports
        ComparisonOperator: MoreThanThreshold # anything that CloudWatch supports
        Actions: # would create an SNS topic with this endpoint
        - EmailSomeone:
            Protocol: email
            Endpoint: john.doe@example.com
        - CallAFunction:
            Protocol: lambda
            Endpoint:
              Ref: an-alert-handler-lambda-function-defined-in-serverless-yaml
```
