### ISSUE TITLE
cannot start with {var}  in `events: http: path` syntax 

### ISSUE THREAD

**Issue by masarakki** [serverless/serverless#2479]
# This is a Bug Report
## Description

Error occurred when writing string that begin with `{variable}` in `path:` section.
## examples and outputs

``` yaml
functions:
  hello:
  handler: handler.hello
  events:
     - http:
         path: {hello}/world
         method: get
```

```
Y A M L Exception --------------------------------------

     can not read a block mapping entry; a multiline key
     may not be an implicit key in "/home/masaki/slstest/serverless.yml"
     at line 51, column 17:
              method: get

                      ^

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

YAMLException: can not read a block mapping entry; a multiline key may not be an
 implicit key in "/home/masaki/slstest/serverless.yml" at line 51, column 17:
              method: get
```

and also, this code will be error (but not same error)

``` yaml
  events:
     - http:
         path: {hello}
         method: get
```

```
   path.split is not a function

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

TypeError: path.split is not a function
    at functionObject.events.forEach.event (/home/masaki/.nvm/lib/node_modules/s
erverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/resources.js:38:3
9)
```
## 

they are ok. 

``` yaml
  events:
    http: GET {hello}/world
```

``` yaml
  events:
    - http: 
       path: hello/{world}
       method: get
```
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.2
- **_Operating System**_: Ubuntu 16.04 / node 6.3.0
