### ISSUE TITLE
Allow adding properties to S3 trigger bucket

### ISSUE THREAD

**Issue by talolard** [serverless/serverless#2486]
I think this is related to #1823 #1839 

## Description
I'm using serverless 1.0.0-rc.2 on ubuntu.

I want to set up a lambda that is tiggered by an s3 event, and also allow CORS on the bucket to allow users to upload it. 

My ideal template looks like 

```yaml
custom:
   writeEnvVars:
      BUCKET_AUDIO: some-audio-${opt:stage}

functions:
  s3handler:
    handler: handler.hello
    events:
      - s3:  ${self:custom.writeEnvVars.BUCKET_AUDIO}
resources:
  Resources:
    AudioBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: - s3:  ${self:custom.writeEnvVars.BUCKET_AUDIO}
        CorsConfiguration:
          CorsRules:
            -
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - "GET"
              AllowedOrigins:
                - "*"
              ExposedHeaders:
                - "Date"
              Id: "myCORSRuleId1"
              MaxAge: "3600"

```

but when I deploy that I get the 

> 
> Serverless Error ---------------------------------------
>  
>      An error occurred while provisioning your stack: S3BucketSomeudiotest
>      - some-audio-test already exists in stack arn:aws:cloudformation:us-east-1:052831428797:stack/some-backend-test/9c903900-96c5-11e6-9c84-50d5cd265c36.
>  
> 

And indeed, if I look at the cloudformation template, I see
```json
    "AudioBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "some-audio-test",
        "CorsConfiguration": {
          "CorsRules": [
            {
              "AllowedHeaders": [
                "*"
              ],
              "AllowedMethods": [
                "GET"
              ],
              "AllowedOrigins": [
                "*"
              ],
              "ExposedHeaders": [
                "Date"
              ],
              "Id": "myCORSRuleId1",
              "MaxAge": "3600"
            }
          ]
        }
      }
    }
```

And 
```json
"S3BucketSomeaudiotest": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "some-audio-test",
        "NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Event": "s3:ObjectCreated:*",
              "Function": {
                "Fn::GetAtt": [
                  "ScheduleSomeSubjobsLambdaFunction",
                  "Arn"
                ]
              }
            }
          ]
        }
      }
```
(I changed the naming slightly ) 

So i understand that the bucket is being made twice. Can I set the trigger to use the bucket I defined in the resources section instead? 

Thanks

**Comment by flomotlik** [comment]
You can simply overwrite/extend the bucket we create for the event with new data, e.g.

```
resources:
  Resources:
    S3BucketSomeaudiotest:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            -
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - "GET"
              AllowedOrigins:
                - "*"
              ExposedHeaders:
                - "Date"
              Id: "myCORSRuleId1"
              MaxAge: "3600"
```

it will merge this configuration into the CF template and the two configs will be merged together.

You can read more about this in our docs: https://serverless.com/framework/docs/guide/custom-provider-resources/
