### ISSUE TITLE
File variable fallback option fails

### ISSUE THREAD

**Issue by briguy202** [serverless/serverless#2490]
# This is a Bug Report

## Description
* What went wrong?
When attempting to use a file variable with a fallback option, and when the file doesn't exist, the fallback is not used and instead I receive an error.

* What did you expect should have happened?
According to the [documentation](https://serverless.com/framework/docs/guide/serverless-variables#overwriting-variables), it should be possible to have a configuration like: `somevalue: ${file(path):value, self:fallback}` and if a file at `path` does not exist, or if path does exist and there is no `value` within it, fallback to using `self:fallback`)

* What was the config you used?
```
...
provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  iamRoleARN: ${file(.slsconfig):iamRoleARN, self:custom.configuration.iamRoleARN}
custom:
  configuration:
    iamRoleARN: arn:aws:iam::890665980307:role/AA-Lambda-Execution-Role
...
```

* What stacktrace or error message from your provider did you see?
ENOENT: no such file or directory, open '/path/to/.slsconfig'

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.0.2
* ***Operating System***: OSX
* ***Stack Trace***:
* ***Provider Error messages***:
