### ISSUE TITLE
Kinesis event not get created, using version 1.0.2

### ISSUE THREAD

**Issue by derekshi** [serverless/serverless#2506]
Based on the documentation, I configured my lambda in serverless.yml as follows:
```
 functions:
  watcher:
    name: ${self:service}-${opt:stage, self:provider.stage}-watcher
    handler: analytics-watcher.handler
    timeout: 60
    memory: 1024
    events:
      - stream:
        arn: ${self:custom.config.cheetahArnVariable}
        batchSize: 100
        startingPosition: LATEST
        enabled: true
```

I am absolutely sure the `${self:custom.config.cheetahArnVariable}` provides valid kinesis arn. The whole process went through without errors, but kinesis trigger is not created. I also tried different indentations but in vain. any ideas?
