### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded for role

### ISSUE THREAD

**Issue by adambiggs** [serverless/serverless#2508]
# This is a Bug Report
### What went wrong?

I tried to deploy a function that listens to 50+ DynamoDB streams. The deploy hung for around 5-10min before eventually failing.
### What did you expect should have happened?

The function should have deployed without any errors.
### What was the config you used?

``` yml
service: ddb-backup

provider:
  name: aws
  runtime: nodejs4.3

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::my-bucket/backups/dynamodb/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:DescribeStream"
        - "dynamodb:ListStreams"
      Resource:
        - "*"

functions:

  backup:
    description: "Backs up DynamoDB records to S3 when modified."
    handler: handler.default
    events:
      - stream: arn:aws:dynamodb:us-east-1:***:table/table-1/stream/2016-01-01T00:00:00.000
      - stream: arn:aws:dynamodb:us-east-1:***:table/table-2/stream/2016-01-01T00:00:00.000
      # ... 50+ more stream events ...
```
### What stacktrace or error message from your provider did you see?

Console output:

```
CloudFormation - UPDATE_FAILED - AWS::IAM::Policy - IamPolicyLambdaExecution
```

CloudFormation output in AWS console:

```
Maximum policy size of 10240 bytes exceeded for role ddb-backup-prod-IamRoleLambdaExecution-ASDF1234
```
## Additional Data
- **_Serverless Framework Version you're using**_: 1.0.3
- **_Operating System**_: OSX 10.11.6

I was able to deploy the function after commenting out most of the event stream mappings. I then had a look at the IAM profile CloudFormation was complaining about. This is when I noticed that Serverless adds it's own policy statements... One for each event source mapping. The end result looks something like this:

``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:us-east-1:*:*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket/backups/dynamodb/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": "arn:aws:dynamodb:us-east-1:***:table/table-1/stream/2016-01-01T00:00:00.000",
            "Effect": "Allow"
        },
        {
            "Action": [
                "dynamodb:GetRecords",
                "dynamodb:GetShardIterator",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams"
            ],
            "Resource": "arn:aws:dynamodb:us-east-1:***:table/table-2/stream/2016-01-01T00:00:00.000",
            "Effect": "Allow"
        }
        // ... etc, etc, etc...
    ]
}
```

These individual policy statements are far too verbose to be scaleable given AWS' limit on policy size. Also, in my case they're totally redundant because I've already defined a catch-all statement that covers these actions.

IMO there are two solutions that would be helpful in solving the issue:
- 1. Serverless should create a single policy statement with all event stream ARNs added to a single `Resource: []` array. This would greatly cut down on the verbosity, allowing the policy to scale past ~50 events.
- 2. Allow some way in Serverless to disable this behaviour all together for those who want to manually define policy statements in `serverless.yml`. This would provide a way to bypass these potential scaling issues.
