### ISSUE TITLE
Error trying to access undefined resource IamPolicyLambdaExecution when a iamRoleARN is provided

### ISSUE THREAD

**Issue by lgvo** [serverless/serverless#2549]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? _Error trying to access  `undefined` resource `IamPolicyLambdaExecution` when a `iamRoleARN` is provided_
* What did you expect should have happened? _Just use the provided ARN role and bypass the CloudFormation template creation._
* What was the config you used?
```yaml
provider:
  name: aws
  runtime: nodejs4.3
  memorSize: 128
  iamRoleARN: arn:aws:iam::xxxxxxx:role/role-name
 vpc:
   securityGroupsIds:
     - sg-xxxxxx
   subnetIds:
    - subnet-xxxxxx
    - subnet-xxxxxx

functions:
   funcName:
      handler: handler.funcName
      events:
          - stream:
              arn: arn:aws:dynamodb:us-east-1:xxxxxxx:table/table-name/stream/<date>
              batchSize: 10
              startingPosition: LATEST
              enabled: true

```

## Additional Data

* ***Serverless Framework Version you're using***: `1.0.3`
* ***Operating System***: `Linx`
* ***Stack Trace***: 
```
TypeError: Cannot read property 'Properties' of undefined
    at functionObj.events.forEach.event (/home/xxxx/.nvm/versions/node/v6.2.1/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:125:15)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/home/xxxx/.nvm/versions/node/v6.2.1/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:20:28)
    at Array.forEach (native)
    at AwsCompileStreamEvents.compileStreamEvents (/home/xxxx/.nvm/versions/node/v6.2.1/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:16:47
```
* ***Provider Error messages***: `Cannot read property 'Properties' of undefined`
