### ISSUE TITLE
DX: Encapsulation to aid provider plugin developers

### ISSUE THREAD

**Issue by gertjvr** [serverless/serverless#2554]
# This is a Feature Proposal
## Description

We are in the process of developing a plugin to simulate API Gateway and executing lambda(s) locally to achieve this I need to parse the `serverless.yml` and setup endpoints, but am left with duplicating logic around authorizer that are buried deep in the aws deploy authorizer plugin.

This allows the plugin developer to focus on the extension rather than duplicating logic that exists in the provider and core plugins.

I like to propose an encapsulation where calling `this.serviceless.service.getFunction(functionName)` give use a normalized view of the function definition with all defaults applied.

This request goes further than just the `authorizer` I would normalize the entire `serverless.yml`
## Example with AWS API Gateway + AWS Lambda

Say we have a service define as below

```
functions:
  customAuthorizer:
    handler: functions/authorizer.handler

  getLists:
    handler: functions/getLists.handler
    events: 
      - http:
          path: lists
          method: GET
          authorizer: customAuthorizer
```

calling `const func = this.serviceless.service.getFunction("getLists")` would result in the function being expanded with all defaults applied

```
{
    name: "getLists",
    handler: "functions/getLists.handler",
    memorySize: 128,
    timeout: 30,
    events [{ 
        "http": {
            path: "lists",
            method: "GET",
            authorizer: { 
               name: "customAuthorizer",
               type: "TOKEN",
               identitySource: "method.request.header.Authorization"
           }
       }
    ]
```

calling `func.getAuthorizer()` would result in 

```
{
    name:  "customAuthorizer",
    handler: "functions/authorizer.handler",
    type: "TOKEN",
    identitySource: "method.request.header.Authorization"
}
```

**Comment by johncmckim** [comment]
@flomotlik this what I was mentioning last night. It applies to API Gateway events too. In regards to API Gateway, if the user specifies this

```
foo:
    handler: functions/index.handler
    events:
      - http:
          path: foo
          method: GET
          integration: lambda
```

We need to get access to the request templates and integration responses.
