### ISSUE TITLE
How can I reference the ARN of a function defined in serverless.yml?

### ISSUE THREAD

**Issue by jch254** [serverless/serverless#2579]
I'm trying to create an AWS::Logs::SubscriptionFilter resource which requires a destination ARN. I want this to be the function I'm defining in serverless.yml - is that possible?

See below for an example:

```
service: log-beam

provider:
  name: aws
  runtime: nodejs4.3
  stage: test
  region: ap-southeast-2
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "logs:Describe*"
       - "logs:Get*"
     Resource: "arn:aws:logs:ap-southeast-2...my-log-group"

functions:
  process:
    handler: handler.process

resources:
  Resources:
    LogSubscription:
      Type: AWS::Logs::SubscriptionFilter
      Properties:
        DestinationArn: Needs to be functions.process.arn
        FilterPattern: ""
        LogGroupName: my-log-group
```

Cheers for any help

**Comment by gertjvr** [comment]
we are waiting on a few PR to be merge but it is possible. here is an [example](https://github.com/andymac4182/serverless_example)

**Comment by jch254** [comment]
Great thanks, got it working!

**Comment by bschoenfeld** [comment]
I've got a similar use case, but I need the ARN of one function's SNS trigger as an environment variable in another function. The posted example shows how to get the ARN with cloud formation, but I don't think that will work in this case, will it?

```
functions:
  foo:
    handler: foo.handle
    environment:
      bar-trigger: {bar-topic.arn}
  bar:
    handler: bar.handle
    events:
      - sns: bar-topic
```

**Comment by vangorra** [comment]
@bschoenfeld I'm in the same position. Did you get this working?

**Comment by bschoenfeld** [comment]
@vangorra Yeah, but it's a work around. I'm ended up just relying on the fact that the ARN format is well defined

```
functions:
  foo:
    handler: foo.handle
    environment:
      bar-trigger: "arn:aws:sns:us-east-1:123456789:${opt:stage}-bar-topic"
  bar:
    handler: bar.handle
    events:
      - sns: ${opt:stage}-bar-topic
```
