### ISSUE TITLE
Memory setting not working.

### ISSUE THREAD

**Issue by jarrettj** [serverless/serverless#2594]
Hi,

Good day. 

* What went wrong?
Serverless.yml memory setting not applied to lambda function.
* What did you expect should have happened?
Set memory to 128. Value of function still reads 1024.
* What was the config you used?
I've been working with the latest serverless v1. Using the serverless-crud repo as a starting point, I quickly built/deployed a few crud functions. All other settings work. See function below:

```
  readOne:
    handler: handler.readOne
    timeout: 1
    memory: 128
    events:
      - http:
          path: articles/{id}
          method: get
          cors: true
          caching: true
          private: true
```

* What stacktrace or error message from your provider did you see?
N/A

* ***Serverless Framework Version you're using***:
1.1.0
* ***Operating System***:
Ubuntu 16.04
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A
