### ISSUE TITLE
Unable to use IAM policy variables in serverless.yml

### ISSUE THREAD

**Issue by michaelorionmcmanus** [serverless/serverless#2601]
# This is a Bug Report

## Description

When writing IAM policies one can provide variables that allow resources to be evaluated in a context sensitive manner. The syntax for IAM policy variables closely, if not exactly, matches the servereless.yml variable syntax. It is therefore not possible to reference resources that include IAM policy variables because the IAM policy variables are interpreted as local variables. 

For more information see: http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html

Consider the following policy statement definition:
```
Statement: 
  -
    Effect: "Allow"
    Action:
    - "iot:Receive"
    Resource:
    - "arn:aws:iot:us-west-2:xxxxxxxx:topic/${cognito-identity.amazonaws.com:sub}"
```

The policy variable `${cognito-identity.amazonaws.com:sub}` will cause the following error, when running `serverless deploy`:

```
  Serverless Error ---------------------------------------

     Invalid variable reference syntax for variable cognito-identity.amazonaws.com:sub.
     You can only reference env vars, options, & files. You
     can check our docs for more info.
```

## Additional Data

* ***Serverless Framework Version***: 1.1.0 and 1.3.0
* ***Operating System***: darwin
