### ISSUE TITLE
CloudFormation Resources limit reached

### ISSUE THREAD

**Issue by Titozzz** [serverless/serverless#2605]
Hi again,

I tried to update my project to serverless v1.1, in order to use the new log group feature, but, once again, as in my last issue (#2466), my project has reached the limits.

I know I could split my project into smaller projects, and I will, but i'd love to find a solution before I do that 😢 .

Stacktrace:
  ```
Serverless Error ---------------------------------------
     An error occurred while provisioning your stack: UsersIdNotificationsPostLogGroup
     - Resource limit exceeded..

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       5.6.0
     Serverless Version: 1.1.0
```

**Comment by flomotlik** [comment]
@Titozzz with 1.1 we released a new Plugin system where you can add service local plugins: https://serverless.com/framework/docs/providers/aws/guide/plugins#service-local-plugin

This means it should be pretty easy to add some code that changes the the template to not have the logs included.

In general I totally get the problem you're running into there, but there isn't really a lot we can do about it because its an edge case and a fundamental limitation of the way Cloudformation works. It would require a lot of resources on our end to work around this and we can't really do that for edge cases. Hope the solution with the service local plugin works for you.

**Comment by andymac4182** [comment]
@flomotlik Have you had a look at using swagger to define the endpoints for the api instead of cloudformation? That would minimize the amount of cloudformation resources I think.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html

**Comment by Titozzz** [comment]
I already use swagger to define my endpoints ... :)

**Comment by flomotlik** [comment]
@andymac4182 the problem with using swagger is that it wouldn't be completely embedded into CF, so you couldn't easily reference resources, ...

Thats why we decided against it and went completely CF native.

**Comment by mwawrusch** [comment]
So I hit this problem too today - with a rather small service. This is a show stopper

**Comment by pmuens** [comment]
@mwawrusch 😞 could you share your `serverless.yml` file so that we can see what your config looks like? Thanks!

**Comment by justinmchase** [comment]
I'm hitting this problem as well. I have a single lambda and am using [a plugin](https://github.com/tsub/serverless-plugin-subscription-filter) to create subscription filters for CloudWatch logs all going to this lambda. Here is my serverless file:

```
service: mya-input-logging

custom:
  stage: "${opt:stage, self:provider.stage}"

plugins:
  - serverless-plugin-subscription-filter
  - serverless-remove-cf-outputs-plugin # added to fix this, didn't work

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - kinesis:*
        - es:*
        - ec2:*
      Resource: "*"

functions:
  cloudwatch_to_elasticsearch:
    handler: handler.cloudWatchToElasticSearch
    timeout: 30
    environment: ${file(env.yml):${self:custom.stage}}
    events:
      - subscriptionFilter:
          stage: ${self:custom.stage}
          logGroupName: /aws/lambda/mya-input-feeds-${self:custom.stage}-ping
          filterPattern: '[timestamp=*Z, id, event]'
      - subscriptionFilter:
          stage: ${self:custom.stage}
          logGroupName: /aws/lambda/mya-input-feeds-${self:custom.stage}-unsubscribe
          filterPattern: '[timestamp=*Z, id, event]'
    vpc:
      securityGroupIds:
        - sg-<id>
      subnetIds:
        - subnet-<id>
```
