### ISSUE TITLE
Allow JSON input for Lambdas that are deployed with a schedule

### ISSUE THREAD

**Issue by Raiju1** [serverless/serverless#2611]
This is a Feature Proposal

## Description
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
When deploying Lambda functions that run on a schedule, there should be a way to make the input passed to the Lambda from the event a constant JSON input, rather than the default matched event. Currently, it appears that this is only possible by going into the Lambda's scheduled invocation rule and changing it there.

* If there is additional config how would it look
This would be configured in the Serverless.yml file under a function similar to:

```
functions:
  functionName:
    handler: functionName.handlerName
    description: "Function Description"
    memorySize: 128
    timeout: 300
    events:
      - schedule: cron(0 */4 * * ? *)
      input: {
                "JSON":"Input"
             }
```
