### ISSUE TITLE
Deploy Error: IamPolicyLambdaExecution - LogGroup doesn't exist

### ISSUE THREAD

**Issue by adambiggs** [serverless/serverless#2614]
# This is a Bug Report

## Description

* What went wrong?
After updating to v1.1.0, adding `cfLogs: true` to my config, and deleting my existing CloudWatch log groups as instructed by the CLI, I can no longer deploy my functions.

* What did you expect should have happened?
Functions should deploy and log groups should be recreated.

* What was the config you used?
```yml
frameworkVersion: 1.1.0
service: my-service-name

provider:
  name: aws
  cfLogs: true
  runtime: nodejs4.3

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetRecords"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - "*"

# ...
```

* What stacktrace or error message from your provider did you see?
```
An error occurred while provisioning your stack: IamPolicyLambdaExecution
     - Template error: LogGroup /aws/lambda/my-service-name-dev-functionName
     doesn't exist.
```

## Additional Data

* ***Serverless Framework Version you're using***: v1.1.0
* ***Operating System***: OSX

**Comment by adambiggs** [comment]
Seems like some kind of race condition since the log group CF is complaining about has been successfully created by that point...

```
CREATE_COMPLETE	AWS::Logs::LogGroup	FunctionNameLogGroup
```

**Comment by adambiggs** [comment]
May have narrowed down the issue to a problem with function naming conventions. After commenting out the function definitions in my `serverless.yml`, I noticed that I could successfully deploy all but 2 of the 9 functions in this service.

The only thing that stands out about these two functions is that their names are a subset of two other functions in the service. E.g.:

```yml
functions:

  # This function deploys fine
  haListingContentIndex:
    # ...

  # This function fails
  haListingContent:
    # ...
```

If I remove the stage (delete the CF stack), and comment out either one of these functions, the deploy will be successful.

**Comment by martinmicunda** [comment]
I have exactly the same issue with `v1.1.0` and `cfLogs` set to `true` however I am deploying these functions as separate projects.

First I deploy shift-template project:
```yml
functions:

  # This function deploys fine
  shiftTemplate:
    # ...
```

and then shift project:
```yml
functions:
  # This function fails
  shift:
    # ...
```

**Comment by faizhasim** [comment]
I've verified the claims above. My workaround for this is to change the name.

So, instead of:

```yaml
someFunction:
  handler: handler.someFunction

someFunctionCallback:
  handler: handler.someFunctionCallback
```

I just rename one of the functions:

```yaml
someFunction:
  handler: handler.someFunction

2SomeFunctionCallback:
  handler: handler.someFunctionCallback
```
