### ISSUE TITLE
 Task timed out after 6.00 seconds

### ISSUE THREAD

**Issue by jdheeter** [serverless/serverless#2640]
# This is a (Bug Report / Feature Proposal)

## Description
When long-running script is running, get's cut short by Lambda timeout.
For bug reports:
* What went wrong?
function was unable to finish task
* What did you expect should have happened?
I should be able to customize the maximum timeout
* What was the config you used?
```
service: coinTrading # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

functions:
  test:
    handler: handler.test

  checkDGB:
    handler: handler.checkDGB
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
```

* What stacktrace or error message from your provider did you see?
2016-11-06T13:34:53.148Z c87ba3d4-a425-11e6-a3f3-8b55b3bf8bcf Task timed out after 6.00 seconds
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
documentation for correct configuration to customize timeout
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
