### ISSUE TITLE
The command you entered did not catch on any hooks

### ISSUE THREAD

**Issue by chris-hailstorm** [serverless/serverless#2649]
# This is a Bug Report

## Description

For bug reports:
* deployed service as usual
* attempted to invoke via Serverless command line
* response: `Serverless Error -- The command you entered did not catch on any hooks`

## Additional Data

Function definition looks like:
```
    sender:
        name: ${self:service}-sender---run---${opt:stage}
        handler: handler.run
        timeout: 20
        events:
            - sns: run---${self:service}-sender---${opt:stage}
            - schedule:
                rate: rate(5 minutes)
                enabled: ${self:custom.cron_${opt:stage}}
```

Attempted invoking using both short and long name:

```
sls invoke --debug --function=sender --stage=stage --data @msg
```

and

```
sls invoke --debug --function=hermes-ping---run---stage --stage=stage --data @msg
```

Same result for both

Does the "sls invoke" execution path / event needs to be explicitly enabled?  Did not before

* ***Serverless Framework Version you're using***: v1.1.0
* ***Operating System***: OSX

**Comment by dougmoscrop** [comment]
I made up this error message (before it was just "command not found") - It displays this when there there are no plugins adding hooks to the lifecycle events raised by the command you entered.

What does sls help print? Especially the bottom part where it lists plugins

**Comment by flomotlik** [comment]
@chris-hailstorm are you running this in a folder with a serverless.yml? We have an issue open for #2116 when you're in a folder without serverless.com

**Comment by chris-hailstorm** [comment]
The `sls help` output looks pretty basic to me:

```
Commands
* Serverless documentation: http://docs.serverless.com
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--help" after any <command> for contextual help

create ........................ Create new Serverless service
install ....................... Install a Serverless service from GitHub
deploy ........................ Deploy a Serverless service
deploy function ............... Deploy a single function from the service
deploy list ................... List deployed version of your Serverless Service
invoke ........................ Invoke a deployed function
invoke local .................. Invoke function locally
info .......................... Display information about the service
logs .......................... Output the logs of a deployed function
remove ........................ Remove Serverless service and all resources
rollback ...................... Rollback the Serverless service to a specific deployment
slstats ....................... Enable or disable stats

Plugins
Create, Deploy, Info, Install, Invoke, Logs, Package, Remove, Rollback, SlStats
```

**Comment by chris-hailstorm** [comment]
And yes, the directory I was working in is the parent of the `.serverless` directory.

**Comment by dougmoscrop** [comment]
What provider do you have set in serverless.yml? It doesn't look like aws
loaded.

**Comment by chris-hailstorm** [comment]
Like this:
```
provider:
    name: aws
    runtime: python2.7
    region: us-east-1
```

**Comment by dougmoscrop** [comment]
Is there any way you can pare down your repo and provide a reproducible example .zip?

**Comment by mthenw** [comment]
@chris-hailstorm let us know if it's still an issue for you. If yes please provide info that @dougmoscrop asked for.

Closing for now.

**Comment by connor11528** [comment]
I am getting this same error. I created a new project and am trying to configure my credentials:

```
$ mkdir myProject
$ cd myProject
$ serverless create --template=aws-nodejs
$ serverless config --provider aws --key AWS_PUBLIC_KEY --secret AWS_SECRET_KEY

  Serverless Error ---------------------------------------
 
     The command you entered did not catch on any hooks
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       8.1.0
     Serverless Version: 1.8.0
```

**Comment by pmuens** [comment]
@connor11528 thanks for commenting 👍!

Could you please update your Serverless version and try again? Thanks in advance!

**Comment by connor11528** [comment]
It worked! Thank you

Downloaded 1.19.0 latest version, was on 1.8.0 before. What's interesting is that is was only a warning. When I ran serverless deploy even on the previous version the site still went up fine. Thanks @pmuens

**Comment by pmuens** [comment]
> It worked! Thank you

> Downloaded 1.19.0 latest version, was on 1.8.0 before. What's interesting is that is was only a warning. When I ran serverless deploy even on the previous version the site still went up fine. Thanks @pmuens

Great @connor11528 👍! Glad to hear that updating resolved the issue.

**Comment by ricardo-dlc** [comment]
I'm on version 2.48.0 and getting this same error. When I run `sls deploy --stage dev --region us-west-2` there is no output and nothing happens. If I add the `SLS_DEBUG` variable like `SLS_DEBUG=* sls deploy --stage dev --region us-west-2` I'm getting the following output:

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command deploy
Serverless: Load command warmup
Serverless: Load command warmup:addWarmers
Serverless: Load command warmup:cleanupTempDir
Serverless: Load command warmup:prewarm
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Warning: The command you entered did not catch on any hooks
```
Trying to debug the problem I found that when `this.getHooks(events)` is executed the function returns an empty array but I don't know if this works as expected because if I add `list` subcommand I get the expected outoput. If I execute another command like `invoke function -f fnName` I get the execution logs without any problems.

**Comment by pgrzesik** [comment]
@ricardo-dlc Could you share a minimal reproducible example with `serverless.yml` config?

**Comment by ricardo-dlc** [comment]
Yeah sure, I was updating some configurations beacause I have been using serverless v1 but I wanted to move to v2. File befroe changes and with version 1 works fine, after solve the deprecatio codes with version 2 nothing happens.

```yml
# serverless.yml
variablesResolutionMode: 20210326

useDotenv: true

service: my-service-name

plugins:
  - serverless-apigateway-service-proxy
  - serverless-pseudo-parameters
  - serverless-feature-flag
  - serverless-plugin-slsignore
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, '${env:stage, "dev"}'}
  region: ${opt:region, '${env:region, "us-east-1"}'}
  lambdaHashingVersion: 20201221

custom:
  someCustomName:  ${self:provider.stage}-${env:stack, "default"}
  rest_api_id: ${env:rest_api_id, "ABCDEF"}

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - "!./**"

functions:
 - ${file(yml/lambdas.yml):functions}

resources:
  - Description: Some Description
  - ${file(yml/lambdas.yml):resources}
  # Some other files
```

```yml
# yml/lamdas.yml

functions:
  FuntionName1:
    handler: path/to/index1.handler
    name: ${self:custom.someCustomName}-name1
    package:
      patterns:
        - ./path/to/index1.js
        - ./node_modules/some_node_module/**
    environment:
      env_var: someValue
  FuntionName2:
    handler: path/to/index2.handler
    name: ${self:custom.someCustomName}-name2
    package:
      patterns:
        - ./path/to/index2.js
        - ./node_modules/some_node_module/**
    environment:
      env_var: someValue
resources:
  Resources:
    ResourceName:
      Type: "AWS::ApiGateway::Resource"
      Properties:
        RestApiId:  ${self:custom.rest_api_id}
        ParentId: !Ref ReferenceToOtherResource
        PathPart: user
```

The command `sls print` works fine, I get the expected output, since `sls deploy` is not showing more warnings or errors I don´t know what could be happen.
