### ISSUE TITLE
It should have `memorySize` default attr sample on template

### ISSUE THREAD

**Issue by hinaloe** [serverless/serverless#2678]
# This is a Feature Proposal

## Description

* it should be there `memorySize` sample attr on `create` plugins's template

In default of `aws` provider,  the `memorySize` value is `1024`
Yes, it is documented, and we can overrider on provider or function section.
but… there is no comment or like one on `create`'s template.
It effects cost of function, so it's not small different!

I think that... in many case, 1024 MB is too large for use, but some user will think "So large config are not used"

## proposal for solve
```yaml
provider:
  name: aws
  runtime: nodejs4.3

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1
#  memorySize: 1024
```

 
Like that: https://github.com/serverless/serverless/compare/master...hinaloe:create-template-add-memorysize
