### ISSUE TITLE
Custom IAM roles not getting associated with functions

### ISSUE THREAD

**Issue by ctbucha** [serverless/serverless#2689]
# Bug Report

## Description

For bug reports:
* What went wrong?

The generated CloudFormation template refers to the default IAM role that gets created instead of the custom one.

* What did you expect should have happened?

The generated CloudFormation template should have referred to the custom IAM role.

* What was the config you used?

```
# serverless.yml
provider:
  #no role defined
  ...

functions:
  hello:
    handler: hello.handler
    role: myCustomRole

resources:
  Resources:
    myCustomRole:
      Type: AWS::IAM::Role
      ...
```

* What stacktrace or error message from your provider did you see?

N/A

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.1.0
* ***Operating System***: OSX 10.11.6
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
