### ISSUE TITLE
Reference Variables in other Service Stacks

### ISSUE THREAD

**Issue by kurtmaile** [serverless/serverless#2690]
# This is a (Feature Proposal)

## Description

For feature proposals:

With the new cross stack variable referencing feature of cloudF, it would be great to be able to refer to generated resource outputs from other serverless stacks.

e.g I have an 'infrastructure services' stack (no lambda funtions) containing all shared services (e.g shared kinesis stream).  My Order service now wants to use a stream in that stack as its event source, but I do not want to hard code the arn.

**Comment by rowanu** [comment]
I'm not sure what you're actually proposing here - you can use CFN cross-stack references right now.

If you just need to export a value then you just need to define it in your `Outputs` under the ['resources'](https://serverless.com/framework/docs/providers/aws/guide/resources/) section of `serverless.yml`.

**Comment by bjfletcher** [comment]
@rowanu I'm intrigued by your reply.

I'm at a loss as to how to do this...

```
resources:
  Resources:
    BFCDN:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName:
              "Fn::Sub":
                - "${bucket}.s3.amazonaws.com"
                -
                  - bucket:
                    "Fn::ImportValue": BFBucket
```

But that gives the error:

```
  Serverless Error ---------------------------------------

     Invalid variable reference syntax for variable bucket.
     You can only reference env vars, options, & files. You
     can check our docs for more info.
```

I see there's an example in https://github.com/serverless/serverless/issues/2240#issuecomment-268411199 how to use this with functions, but that's because `environment` is passed straight in (as far as I can tell)... but how to import values for use *within* the `serverless.yml` template?
