### ISSUE TITLE
Checking Stack update progress... never completes

### ISSUE THREAD

**Issue by nwhite89** [serverless/serverless#2691]
# Bug Report

## Description

For bug reports:
* What went wrong?

When running deploy I can't get past `Serverless: Checking Stack update progress…`. Despite the CloudFormation in AWS stating that it is `UPDATE_COMPLETE`

* What did you expect should have happened?

Update with completion from `CloudFormation` and Service Information

* What was the config you used?

```
provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  deploymentBucket: lambda-test-formats
  cfLogs: true
package:
  exclude:
    - .reports/**
    - .git/**
    - api/**
    - dist/**
    - grunt/**
    - test/**
functions:
  demos:
    handler: handler.demos
    events:
      - http:
          path: demos
          method: get
  publish:
    handler: handler2.publish
    events:
      - http:
          path: publish
          method: get
```

* What stacktrace or error message from your provider did you see?
N/A

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.10
* ***Operating System***: OSX 10.11.4
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

![screen shot 2016-11-11 at 10 20 30 1](https://cloud.githubusercontent.com/assets/1407863/20212220/df2916c0-a7f9-11e6-9305-24f9b9d9c82f.png)
