### ISSUE TITLE
Can't subscribe to S3 events on a bucket in CF Stack

### ISSUE THREAD

**Issue by asprouse** [serverless/serverless#2717]
# This is a Bug Report

## Description
I know @flomotlik weighed in (#2154) on attaching events to s3 buckets not created by Cloudformation. I am having this issue with an s3 bucket that IS in the Cloudformation stack but it was created in the `resources` section of the `serverless.yml`:

```yml
functions:
 upload-hook:
    handler: api/upload-hook/index.handler
    events:
      - s3:
          bucket: ${self:service}.${self:custom.stage}.assets
          event: s3:ObjectCreated:*

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: "${self:service}.${self:custom.stage}.assets"
        CorsConfiguration:
          CorsRules:
          - AllowedOrigins:
              - http://example.dev:3001
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
          - AllowedOrigins:
              - https://dev.example.com
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
```
It seems that there are two sections in the `cloudformation-template-update-stack.json` one is named `S3BucketExampleapidevassets` and the other is named `AssetsBucket`. It seems that these should get merged by serverless.

```
Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: S3BucketExampleapidevassets
     - example-api.dev.assets already exists in stack arn:aws:cloudformation:us-east-1:xxxxxx:stack/example-api-dev/de90bc30-aaa2-11e6-bd9e-500c20fafe62.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.0.0
     Serverless Version: 1.1.0
```

**Comment by asprouse** [comment]
The issue for me here is to have the ability to custom configuration such as `CorsConfiguration` on a bucket. If you are making an app where you allow users to upload directly to s3 you need this configuration.

Perhaps [mergeCustomProviderResources()](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/mergeCustomProviderResources.js) can be updated to properly merge buckets created by the s3 events with the custom defined one. If the Serverless team thinks this is a reasonable approach I am happy to provide a pull request. @flomotlik @ac360 @eahefnawy any thoughts?

**Comment by pmuens** [comment]
Hey @asprouse thanks for reporting this. 👍 

Couldn't you use the resource id Serverless creates for you if you use the `s3` event (in this case `S3BucketExampleapidevassets `) in the custom resource section to add / overwrite the configuration?

```yml
resources:
  Resources:
    S3BucketExampleapidevassets:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: "${self:service}.${self:custom.stage}.assets"
        CorsConfiguration:
          CorsRules:
          - AllowedOrigins:
              - http://example.dev:3001
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
          - AllowedOrigins:
              - https://dev.example.com
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
```

**Comment by asprouse** [comment]
@pmuens that's what I tried first but I found that it wouldn't work since the bucket name in this example is dynamic and so you can't predict the resource id .

**Comment by pmuens** [comment]
@asprouse Thanks for the reply.

You could also use Serverless variables in the resource id. Here are the docs which show you how the resource id is generated: https://serverless.com/framework/docs/providers/aws/guide/resources/

So in your case you could do something like this:

```yml
functions:
 upload-hook:
    handler: api/upload-hook/index.handler
    events:
      - s3:
          bucket: ${self:service}.${self:custom.stage}.assets
          event: s3:ObjectCreated:*

resources:
  Resources:
    S3Bucket${self:service}${self:custom.stage}assets:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: "${self:service}.${self:custom.stage}.assets"
        CorsConfiguration:
          CorsRules:
          - AllowedOrigins:
              - http://example.dev:3001
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
          - AllowedOrigins:
              - https://dev.example.com
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - GET
```

**Comment by asprouse** [comment]
This makes sense but it relies on the fact that the way that the naming function normalizes your bucket name is always 1-1 with your variables. For example a dash or capitalization  in the bucket name. It appears each resource has different conventions  which are confusing. I have a PR with the change I am proposing you can check out. Another solution which might be less code is to allow the user to specify the custom resource is in the http event.

**Comment by pmuens** [comment]
Hey @asprouse thanks for mentioning that. That makes sense.

We've just pushed Serverless v1.2.0 which adds support for dynamic Serverless Variables (https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files). This way you can write a simple function which can create this dynamic data easily for you. This should make it possible to resolve the problem you described here.

**Comment by asprouse** [comment]
@pmuens Thanks that looks promising, but still using a custom js config file that simulates [naming.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js) seems like a lot of hoops to jump through to support something that seems like basic functionality. 

Matching a generated resource id  will be hard to explain to new users, especially when there are different conventions for  each resource type that aren't clear unless you read the code for [naming.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js).

I think that intelligent merging by bucket name (or at least explicitly mentioning the custom resource id in the http event) should be considered as an enhancement.

**Comment by pmuens** [comment]
Yep, I agree @asprouse! 👍 
Going through such steps should only be a workaround and not a "best practice".
This is definitely something we need to tackle to make it easier for users to overwrite such configurations.

/cc @eahefnawy

**Comment by simoami** [comment]
I agree with @asprouse. Merging templates should work intuitively! but it's good to know there are possible workarounds.

**Comment by simoami** [comment]
@pmuens I'm wondering what workaround works at this point. Trying to plug variables into resource ids does work. I get `Template format error: Resource name S3Bucket${self:custom.servicePrefix}
     is non alphanumeric.`
Can you shed some light on what can be done here?

**Comment by nachoab** [comment]
I had to modify  `lib/plugins/aws/deploy/compile/events/s3/index.js` here  https://github.com/nachoab/serverless/commit/77ba504e9c480ec45ec7c89f39957ba6154b80f3
until we know how to do this.

With that change I can reference a Bucket from s3 events using it's name without sls attempting to create the bucket ignoring my resource definition

**Comment by pmuens** [comment]
@simoami have you tried to use JavaScript for dynamic Serverless Variables https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files ?

This way you should be able to generate the resourceId dynamically.

**Comment by glennr** [comment]
@pmuens - I'm also not clear on how JS variables help with your workaround; i.e.

```
resources:
  Resources:
    S3Bucket${self:service}${self:custom.stage}assets:  
```
yielding

```
Template format error: Resource name S3Bucket${self:service}${self:custom.stage}assets
     is non alphanumeric.
```

**Comment by pmuens** [comment]
Thanks @glennr for confirming this issue.
We've got some issues with the variable system we'll tackle in v1.5.

Seems like the variables in the resources section are somehow not resolved...

**Comment by eahefnawy** [comment]
@pmuens @glennr you can't use serverless variables in property keys (eg. resource logical IDs). You can only populate values, not keys.

@pmuens what variables issues are you referring to?

**Comment by eahefnawy** [comment]
PRed an update to the docs that adds a note about this for clarity:
https://github.com/serverless/serverless/pull/2979

**Comment by pmuens** [comment]
Thanks @eahefnawy ! Just merged it.

The issue I was talking about (cannot find it right now) also dealt with Serverless variables in keys...

**Comment by glennr** [comment]
@pmuens @eahefnawy thanks for the quick reply.

Regarding the original issue in the thread, I'm to get sls to 1) create a bucket and 2) create *two* events that use this very same bucket i.e.

```
functions:
  handlerOne: 
    handler: handler.handlerOne 
    events: 
      - s3:
          bucket: ${self:custom.s3BucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: one.json

  normalizeGmail: 
    handler: handler.normalizeGmail 
    events: 
      - s3:
          bucket: ${self:custom.s3BucketName}
          event: s3:ObjectCreated:*
          rules:
            - suffix: two.json

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        AccessControl: Private
      DeletionPolicy: Retain

custom:
  defaultStage: dev
  s3BucketName: "incoming.${opt:stage, self:custom.defaultStage}"

```

Would this even work? Can I have two Events referencing the same bucket?

From @pmuens suggestion to change the Resource name to match the one auto-generated by the Event, the implication is that the bucket created by the Event is the one that takes precedence? (correct me if I'm wrong).
