### ISSUE TITLE
API Gateway authorizer cannot access custom authorizer lambda

### ISSUE THREAD

**Issue by rochdev** [serverless/serverless#2726]
When using an existing custom authorizer lambda from an API Gateway HTTP event handler function, it cannot be accessed from the API Gateway.

For example, with the following configuration the gateway doesn't have access to the custom authorizer lambda.

```yaml
getPosts:
    handler: posts.retrieve
    events:
      - http:
          path: posts
          method: GET
          authorizer: arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:authentication-dev-authorizer
```

From my understanding, when you use the API Gateway UI to create the authorizer it asks permission to access the lambda (I didn't find where the permission is stored in that case).

Otherwise, you can set the execution role for the authorizer so it can reach the custom authorizer lambda.

Neither options seem to be available in serverless, so the lambda cannot be accessed by the authorizer resulting in an error.
