### ISSUE TITLE
Suddenly timeouts with every deploy

### ISSUE THREAD

**Issue by ksnyde** [serverless/serverless#2731]
# What went wrong

Have been using serverless for a few small Lambda functions and have really been enjoying it. All functions are very small but there are some additional deps in the graph and I notice that my last successful deployment was 178mb which is surprising because I thought Lambda limit was 50mb but maybe that's just the way Serverless packages things up? As you can see even now my dependencies are quite small:

![image](https://cloud.githubusercontent.com/assets/980757/20386125/142ab826-acb2-11e6-8272-a129379ea0ef.png)

In any event, I went looking for other issues like mine and it seems there have been some but none open. In any event one thing I saw mentioned was trying:

```sh
SLS_DEBUG=true sls deploy -v
```

I tried that but the only additional info was a stack trace:

```sh
ServerlessError: Connection timed out after 120000ms
    at Response.req.send (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:142:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
```

With the main error message being:

```
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.1.0
```

# Expected Outcome

These are very small lambda functions, I'd have expected them to go right through. I'm also concerned about the Lambda sizes that are showing up in AWS:

![image](https://cloud.githubusercontent.com/assets/980757/20386325/1161e438-acb3-11e6-9e97-c025ec2b128d.png)

potentially this is just my mis-understanding but these look way out of proportion to what they should be.

# Configuration

I'm on MacOS, using serverless version `1.1.0` and my `serverless.yml` has the following config:

```yml
service: mycompany-services

provider:
  name: aws
  runtime: nodejs4.3
  profile: truecash
  stage: prod
  region: eu-west-1

functions:
  authorize:
    handler: lib/authorize.handler
    events:
      - http: GET accounting/authorize

  accessToken:
    handler: lib/access-token.handler
    events:
      - http: GET accounting/accessToken

  accounting:
    handler: lib/get-accounting.handler
    events:
      - http: GET accounting/get
```

As a next step I will try using the [serverless-optimizer-plugin](https://github.com/serverless/serverless-optimizer-plugin) that I noticed when researching this issue. Regardless if this helps me get this working I feel my very limited functions should work without the need for compression and so I'm raising this now.

**Comment by ksnyde** [comment]
I have tried it with the optimizer as discussed above and the issue is unchanged.

**Comment by ksnyde** [comment]
For additional context here's a view into the file sizes in this project:

![image](https://cloud.githubusercontent.com/assets/980757/20387063/44b0e016-acb6-11e6-90da-7e40a5bc6c9f.png)

As you can see, nothing of significant size.

**Comment by ksnyde** [comment]
I'm now concerned that maybe serverless is packaging up node modules that are only "devDeps"? Is that the case? Not that I have a lot there either but I do have all that comes with the Gulp ecosystem and few other things I use in my build pipeline (like Typescript)

**Comment by pmuens** [comment]
Hey @ksnyde thanks for opening this! 👍 

This is actually pretty strange. Serverless packages the whole service (which includes the whole `node_modules` dir --> `dependencies` and `dev-dependencies`). @zaubernerd opened an issue the other day with a proposal on how to prevent this: (https://github.com/serverless/serverless/issues/2709)

**Comment by ksnyde** [comment]
yikes. I'm seeing if maybe a work around I can use `npm@2` and then use **exclude** for all the gulp deps.

**Comment by ksnyde** [comment]
Really dying to find a workaround as I need to re-release today. Thought this would work for sure:

```yml
provider:
  name: aws
  runtime: nodejs4.3
  profile: truecash
  stage: prod
  region: eu-west-1
  package:
    include:
      - "lib/*"
      - "node_modules/firebase/*"
      - "node_modules/bluebird/*"
      - "node_modules/moment/*"
      - "node_modules/oauth/*"
      - "node_modules/dotenv/*"
    exclude:
      - "test/*"
      - "src/*"
      - "node_modules/**"
```

This was done with `npm@2`'s flat dep structure and I still get the same error. Is there possibly something else going on?

**Comment by pmuens** [comment]
Serverless v1.1.0 doesn't support `include` right now. The current `master` version does. Could you pull this version and redeploy with the config shown above?

**Comment by ksnyde** [comment]
Well I was expecting `node_modules` to be the biggy but forgot about `.git`. Definitely should add this to the solution in #2709 

![2016-11-17_13-23-03](https://cloud.githubusercontent.com/assets/980757/20391010/47f2b142-acc9-11e6-8b89-18961b18830d.png)

That said, even excluding `.git/**` I'm still failing to deploy with same error.

> Note: this is the last successful deploy that came in at 178mb which was a lot larger than the 21mb I was seeing a few days before (the growth seems to be almost exclusively from `.git`)

I then ran a disk map on the current -- e.g.,  failing -- directory and found this:

![2016-11-17_13-48-49](https://cloud.githubusercontent.com/assets/980757/20391868/3423c5c6-accd-11e6-9259-dee3381ee0ca.png)

Uh oh. Seems the `.serverless` directory may be getting in the way? Or is this just the filesize of the payload that timed out when deploying?

**Comment by ksnyde** [comment]
also, can i change the timeout period for large files like this. I have used `node-lambda` in the past to upload files just shy of 500mb and it works pretty well. Pretty sure it's compressing before sending but then I guess the optimiser plugin you get that here too (shouldn't that be the default?)

**Comment by pmuens** [comment]
Hmm. That's really odd. Serverless should ignore `.git/**` by default. Could you remove the `.serverless` directory and run `serverless deploy --noDeploy` (this will only build the deployment artifacts without deploying) and then look at the size of the .zip file?

Large uploads will timeout (we had a discussion about that here: https://github.com/serverless/serverless/issues/2363).

**Comment by ksnyde** [comment]
- after experimenting i can see that the zip file in the `.serverless` directory is just a representation of what will be pushed to AWS. 
- That's good, was afraid it was a recursive problem but my `.git` growth appears to be down to not excluding the .serverless directory from version control (or at least the zip file)
- My current `serverless.yml` should ignore everything but a very small payload but for whatever reason it is not excluding files (that's the only explanation I can come up with anyway)

```yml
provider:
  name: aws
  runtime: nodejs4.3
  profile: truecash
  stage: prod
  region: eu-west-1
  package:
    include:
      - "lib/*"
      - "node_modules/firebase/**"
      - "node_modules/bluebird/**"
      - "node_modules/moment/**"
      - "node_modules/oauth/**"
      - "node_modules/dotenv/**"
      - "node_modules/lodash/**"
    exclude:
      - "*.mp3"
      - "test/*"
      - "src/*"
      - ".git/**"
      - ".serverless/*.zip"
      - "node_modules/**"
```

**Comment by pmuens** [comment]
Yes, the .zip file is exactly what is pushed to AWS 💯 

I think I got the solution 😬 

Could you put the `package` config on the root level (and not nest it inside of `provider`) and try again?

**Comment by ksnyde** [comment]
I can conclude now that the exclusion of ".git/**" does NOT exclude the git files. Physically removing the git files _does_ exclude it but doesn't represent a reasonable work-around

**Comment by ksnyde** [comment]
ok let me try that but in the mean time, found another work-around:

- add `.serverless/*.zip` to `.gitignore` (probably a good idea regardless)
- `rm -rf node_modules`
- `yarn install --production` (if you use yarn); if you're using npm then `npm install --production`

That will put ONLY the real dependencies in node_modules. You're now ready to deploy.

**Comment by ksnyde** [comment]
Note that if you've corrupted your git repo with prior versions of the **zip** file then you'll need to purge that first. I suggest https://rtyley.github.io/bfg-repo-cleaner/

**Comment by pmuens** [comment]
Yep.

This

```yml
provider:
  name: aws
  runtime: nodejs4.3
  profile: truecash
  stage: prod
  region: eu-west-1
  package:
    include:
      - "lib/*"
      - "node_modules/firebase/**"
      - "node_modules/bluebird/**"
      - "node_modules/moment/**"
      - "node_modules/oauth/**"
      - "node_modules/dotenv/**"
      - "node_modules/lodash/**"
    exclude:
      - "*.mp3"
      - "test/*"
      - "src/*"
      - ".git/**"
      - ".serverless/*.zip"
      - "node_modules/**"
```

should be updated to look like this:

```yml
provider:
  name: aws
  runtime: nodejs4.3
  profile: truecash
  stage: prod
  region: eu-west-1

package:
  include:
    - "lib/*"
    - "node_modules/firebase/**"
    - "node_modules/bluebird/**"
    - "node_modules/moment/**"
    - "node_modules/oauth/**"
    - "node_modules/dotenv/**"
    - "node_modules/lodash/**"
  exclude:
    - "*.mp3"
    - "test/*"
    - "src/*"
    - ".git/**"
    - ".serverless/*.zip"
    - "node_modules/**"
```

**Comment by ksnyde** [comment]
With this work-around my 178mb function is now 8mb!

**Comment by ksnyde** [comment]
yeah i understood and have just updated my `yml`; the reason I did it the way I did is that there was an example in the documentation that had it there. I'll see if I can find it.

**Comment by ksnyde** [comment]
For now I think my approach will be largely rely on the production flag to prep "node_modules" until a better solution is available but I will exclude no-brainers like `.git` too.

**Comment by pmuens** [comment]
Awesome! Great to hear that it works.

Please let us know where those docs are so that those can be changed. 👍

**Comment by pmuens** [comment]
BTW. The next Serverless version will exclude `.git` and `.serverless` by default (see: https://github.com/serverless/serverless/pull/2617).

**Comment by pmuens** [comment]
Closing this one as it seems to be resolved. @ksnyde please let us know if you need any further help!

**Comment by ksnyde** [comment]
no help needed but I wanted to make sure there is an issue being tracked to get this truly "solved". I've come up with a work-around but I think Serverless needs to "out-of-the-box" support for:

- only publishing the production requirements. 
- Further, unless I missed it in the docs, you need to be explicit about adding `.serverless/*.zip` to your `.gitignore` so that you don't start getting leftover ZIPs added to your repo. 
- Also, no one is going to want `.git` in their deployments so I think some sensible defaults for what to exclude should be the default

**Comment by pmuens** [comment]
@ksnyde thanks for the detailed list!

Just looked through the issues and saw that we've covered / tracked all the stuff. 👍

**Comment by ksnyde** [comment]
Sweet. Great job guys on this project. Super helpful.

**Comment by pmuens** [comment]
Thank you very much @ksnyde 👍  💯 

Feel free to chime in on issue discussions or raise a new one if you need anything!

**Comment by mrowles** [comment]
This seems to ignore "uuid" package in node_modules:

```
package:
  include:
    - "node_modules/uuid/**"
  exclude:
    - "node_modules/**"
```
