### ISSUE TITLE
Allow CORS/Configuration of bucket created by S3 event

### ISSUE THREAD

**Issue by jeffski** [serverless/serverless#2749]
### What is the use case that should be solved.
I'm using Serverless to create a service that processes user uploaded videos and uses a Lambda to queue them to Elastic Transcoder. I've got a function and an event like this:

```
functions:
  transcoder:
    handler: handler.transcoder
    events:
      - s3: myBucket
        event: s3:ObjectCreated:*
```

The problem is that files can't be uploaded because by default the bucket will not accept CORS requests, I've got a website hosted on S3 that is doing the uploads.

I have tried to add a resource for the bucket and add CORS configuration but get an error because the bucket has already been created by the previous events setup.

I think this will be a reasonably common use case - handling user submitted uploads from a web site to S3 and users will get the CORS error.

I'd like to see either a way to configure/enable CORS on the event bucket or don't create the bucket and make that a task that has to be done in resources.

**Comment by jeffski** [comment]
Just to add - for now I've gone in to S3 in the web console and added the CORS rules.

**Comment by pmuens** [comment]
Thanks for opening this! 👍 

This could be a great config parameter for the extended bucket configuration. What do you think @eahefnawy

**Comment by jeffski** [comment]
I've run in to another problem to do with the automatic creation of buckets for events - basically if the bucket already exists then I am getting an error like `bucket already exists in stack arn...` - the bucket is created in another serverless.yml resource/cloud formation setup.

A way to disable the creation of the bucket might be good, or ignore if exists or users just create buckets manually via resources which should avoid this situation and allow CORS to be setup.

**Comment by kennu** [comment]
I also just ran into this issue now, trying to setup a public S3 upload bucket which needs CORS configuration (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-cors.html).

**Comment by obezuk** [comment]
Just so this thread is aware, I'm also experiencing the same issue but it's been discussed in more detail in a related issue #2967.

**Comment by drazafsky** [comment]
I've also run into this issue and it's proving to be a major hassle since it means adding an extra step outside of the Serverless deployment to any bucket that needs to have CORS configured. Really disappointed that the answer seems to be that it's just not going to be supported.

**Comment by wulftone** [comment]
Any progress on this issue? It's a big roadblock in our serverless stack.

**Comment by pmuens** [comment]
> Any progress on this issue? It's a big roadblock in our serverless stack.

@wulftone We've not worked on that yet. I added the `help-wanted` label.

**Comment by epeli** [comment]
As a scripted workaround it is possible to upload cors configuration with aws cli:

    aws s3api put-bucket-cors --bucket mybucket --cors-configuration file://s3-cors.json

s3-cors.json:

```json
{
    "CORSRules": [
        {
            "AllowedOrigins": ["*"],
            "AllowedHeaders": ["*"],
            "AllowedMethods": ["PUT", "POST", "DELETE"],
            "MaxAgeSeconds": 3000
        },
        {
            "AllowedOrigins": ["*"],
            "AllowedHeaders": ["Authorization"],
            "AllowedMethods": ["GET"],
            "MaxAgeSeconds": 3000
        }
    ]
}
```

**Comment by xj42** [comment]
this would be a huge help

**Comment by floydspace** [comment]
> functions:
>   transcoder:
>     handler: handler.transcoder
>     events:
>       - s3: myBucket
>         event: s3:ObjectCreated:*

you can add in addition to function configuration this:

```
resources:
  Resources:
    S3BucketMyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myBucket
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
              MaxAge: 3000
    TranscoderLambdaPermissionMyBucketS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt:
            - TranscoderLambdaFunction
            - Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: arn:aws:s3:::myBucket
```
and it should work.

see [Custom bucket configuration](https://serverless.com/framework/docs/providers/aws/events/s3#custom-bucket-configuration)

**Comment by medikoo** [comment]
Addressed with https://github.com/serverless/serverless/pull/7156

**Comment by Edweis** [comment]
I had to read the PR to actually get the syntax, here it is :
```
  custom:
    handler: core.custom
    events:
      - s3:
          bucket: customBucket
```
With the ressource:
```
    customBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: MyBucket
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT]
              AllowedOrigins: ['*']
````
