### ISSUE TITLE
Api Gateway Deployment Failure

### ISSUE THREAD

**Issue by joshwils82** [serverless/serverless#2771]
This is a Bug Report

## Description

For bug reports:
* What went wrong?
Deploying API Gateway endpoints via cloud formation errors out in sls 1.2.  This seems to be an issue when upgrading from 1.1.

* What did you expect should have happened?
Should have deployed successfully as it did in sls 1.1

* What was the config you used?
```
functions:
  themes:
    handler: services/themes/handler.dispatch
    events:
      - http:
          path: themes
          method: get
          cors: true
      - http:
          path: themes/{themeId}
          method: get
          cors: true
```

* What stacktrace or error message from your provider did you see?

```
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ApiGatewayResourceThemesThemeIdVar
     - Another resource with the same parent already has
     this name: {themeId}.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.3.2
     Serverless Version: 1.2.0
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.2 (saw the bug after upgrading from 1.1)
* ***Operating System***: Linux
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by bdgamble** [comment]
I am also getting this exact failure after upgrading to 1.2 from 1.1 with a near identical template.

**Comment by pmuens** [comment]
Oh snap! Thanks for reporting! 👍 

We've refactored the API Gateway code recently. Removing the API Gateway and redeploying should resolve this issue.

Any ideas what caused this error @eahefnawy?

**Comment by nicka** [comment]
Use the sls diff plugin 😉

**Comment by pmuens** [comment]
@nicka thanks for this pointer 👍 

@eahefnawy yep you should definitely use https://github.com/nicka/serverless-plugin-diff a `--noDeply` with an old version and the new one should show what the issue is.

**Comment by dougmoscrop** [comment]
small note

the command, with that plugin, is `serverless diff` not `serverless deploy diff` (as it currently says in the README)

**Comment by eahefnawy** [comment]
Confirmed the bug and fixed it in #2774. There was a very tiny accidental change in the logical ID of the APIG Resource template. I brought it back it fixed the issue.

Could you guys try the PR and confirm that it fixes the issue? So we can release a patch right away.

**Comment by nicka** [comment]
@dougmoscrop thanks, will update!

**Comment by eahefnawy** [comment]
Alright we just released a patch for this (`v1.2.1`) ... if you're still facing this issue, just update to `v1.2.1` and deployment should be working again 🙌 ... If you had already removed the service and deployed it again from scratch using `v1.2.0` as a workaround, I'm afraid you're gonna have to do that again ... eitherway, this issue is now fixed 🎉 

Thanks a lot for your quick reporting guys, and sorry this break slipped through 😊 ☺️

**Comment by joshwils82** [comment]
Working great now with 1.2.1.  Thanks for the quick turnaround.

**Comment by AndrewFarley** [comment]
Can we re-open this bug...?  As this _exact_ same thing happens when (re)deploying a project deployed from serverless v1.2 to serverless v1.4.

```autobotv2[git master] $ serverless deploy
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (3.26 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ApiGatewayResourceAutobotv2sns
     - Another resource with the same parent already has
     this name: autobotv2SNS.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.6.2
     Serverless Version: 1.4.0
```

I fixed this issue by doing what someone recommended above, and changing my endpoint's path, redeploying, and then renaming it back to the original name and re-deploying again.

**Comment by pmuens** [comment]
@AndrewFarley that's interesting since versions above v1.2.1 should have this fix...

Could you please provide your `serverless.yml` file for reference?

/ccing @eahefnawy here since he's implemented the fix...

**Comment by AndrewFarley** [comment]
This has actually happened to me on 3 separate deployed projects when upgrading from 1.2 to 1.4.  To fix it before I simply did the serverless remove/add because these were still development endpoints and I didn't file a bug or really care... but for this project I could not lose the URL/API Gateway that it had created since it had be propagated into various CloudFormation scripts and automation stacks and so I had to figure out that workaround by renaming/redeploying/un-renaming/redeploying.

And of course, here's my serverless.yml...

```
service: autobot-v2

#plugins:
#  - serverless-offline

package:
  exclude:
    - 'old/**'
    - 's3_files/**'
    - '*/*.md'
    - '*/*.json'
    - '*/*.yml'
  include:
    - '.ssh'

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    provider_level: provider
  stage: live
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
        - sts:AssumeRole
        - lambda:InvokeFunction
      Resource: "*"
  vpc:
    securityGroupIds:
      - sg-c9f9abac
      - sg-cbf9abae
      - sg-f2f9ab97
    subnetIds:
      - subnet-22ef4b55

functions:
  autobotv2SNS:
    handler: autobotv2SNS.handler
    timeout: 60
    events:
      - http:
          path: autobotv2SNS
          method: post
  autobotv2SNSadd:
    handler: autobotv2SNSadd.handler
    timeout: 300
```

And in-case you're curious, the permissions are in place for cascading, one Lambda calls the other lambda, one in a VPC, the other not in a VPC, effectively similar to an OSS project of mine...

https://github.com/AndrewFarley/serverless-cloudwatch-rds-custom-metrics

^  In the deployed instances of this project I had the same problem when upgrading from 1.2 to 1.4.  But since I wasn't using API Gateway for that it didn't matter, I just removed and re-deployed.

**Comment by eahefnawy** [comment]
@andrew-templeton I think you're facing a different issue but with the same error message. This bug and its corresponding fix happens when you have a variable in the path with the `{var}` syntax. It was an issue of how we compile that into CF. You config seems different though.

Are those all the endpoints your service has?

**Comment by AndrewFarley** [comment]
@eahefnawy - There was one more endpoint I excluded for length but I figured was irrelevant... but yeah if you guys can't easily replicate this... when I have some cycles in the next few days I'll dig in and file a detailed bug report on this.  Just this bug was eerily similar and the solution fixed my bug, so I thought I'd comment.  The endpoint I omitted was...

```
  notify:
    handler: notify.handler
    timeout: 60
    events:
      - http:
          path: notify
          method: get
```
