### ISSUE TITLE
cannot load config from separate file   #2169 s

### ISSUE THREAD

**Issue by greendavegreen** [serverless/serverless#2773]
I just installed 1.2 and was going to try using environment variables AND moving sensitive items into a separate file that I can .gitignore.

I created a config.yml file to store the items subject to change.  and then tried loading them into my serverless.yml.

contents of config.yml:

```

dropBucket: lobby.worky
keepBucket: keep.worky


```

and the opening of my serverless.yml
```
service: sls-python-demo

cfg: ${file(../configVars.yml)}

custom:
  dropBucet: lobby.worky
  keepBucket: keep.worky


provider:
  name: aws
  runtime: python2.7

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: arn:aws:s3:::${self:cfg.dropBucket}/*
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.keepBucket}/*
    - Effect: Allow
      Action:
        - "sns:*"
      Resource: "*"
```

results in the error message:

```
  Serverless Error ---------------------------------------
 
     Trying to populate non string value into a string for
     variable ${self:cfg.dropBucket}. Please make sure the
     value of the property is a string.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.6.0
     Serverless Version: 1.2.0
```

If I change the troubled Resource statement to use self.custom.dropBucket instead of self.cfg.dropBucket, my deploy works fine.  I would like to get the custom items out of this file and safely into separate file of info likely to change from deploy to deploy.

Similar or dependent issues:
* #2169

**Comment by pmuens** [comment]
Hmm. This should work according to https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-other-files

Is your filename correct? In the description it says that the name is `config.yml` but in the `serverless.yml` it says `configVars.yml`.

**Comment by pmuens** [comment]
@greendavegreen any updates on this one? Have you tried the suggestion above?

We've merged some changes recently. You might also want to check against the current `master` branch.

**Comment by camhart** [comment]
I'm running 1.4 on a **windows 10** box and I cannot get this to work either.

`service: supercoolsoftware
frameworkVersion: "=1.4.0"

provider:
  name: aws
  runtime: dotnetcore1.0
  cfLogs: true
  region: us-west-2
  environment:
    exampleConfigValue: ${file(./env.yml)} #loads appropriate stage file from configs/*.json`

env.yml is located in the root of the project, alongside serverless.yml.  It's contents are as follows:
`
dev:
  message: hello there!
`

**Comment by gmadole** [comment]
@camhart I just discovered this too!  Objects aren't allowed...

I'd like for when processing environment-variables, that if the property is an object to stringify it before  adding it to the CF template.  That way we can still add in objects (that may be dynamic in size/property names) to environment variables.  Inside the app code we could handle the stringified object.

**Comment by massimocode** [comment]
We are facing the same issue. Trying to import a JSON file. Our file looks roughly like this:
```
functions:
  foo: ${file(functions/foo/s-function.json)}
```
And we get the error:
```
  Type Error ---------------------------------------------

     Cannot create property 'events' on string '${file(functions/premier-membership-expired/s-function.json)}'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.5.0
     Serverless Version: 1.5.0
```

**Comment by hassankhan** [comment]
Have you tried this:
```
// serverless.yml
```

```
// serverless.yml
functions:
  foo: ${file(functions/foo/s-function.json):foo}
```

**Comment by jveldboom** [comment]
You have to include the colon and object reference within the file being included. For example:

```yaml
# serverless.yml
functions:
   testAuth: ${file(routes.yml):testAuth}
   postArticles: ${file(routes.yml):postArticles}
```

```yaml
# routes.yml
testAuth:
   handler: routes/test.handler
postArticles:
   handler: routes/postArticles.handler
```
