### ISSUE TITLE
variable not being substituted

### ISSUE THREAD

**Issue by dreadjr** [serverless/serverless#2782]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong? Variable is not being substituted into the a field (e.g. description of function)
* What did you expect should have happened? custom variable to be evaluated first, then substituted into description
* What was the config you used?

```yaml
frameworkVersion: "=1.2.0"

service: authorizer

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true,
  codeship:
    CI_COMMIT_ID: ${env:CI_COMMIT_ID, 'CI_COMMIT_ID'}
    CI_BUILD_URL: ${env:CI_BUILD_URL, 'CI_BUILD_URL'}

provider:
  name: aws
  cfLogs: true

functions:
  api:
    #  ${env:FUNC_PREFIX}
    runtime: nodejs4.3
    name: ${self:provider.stage}_${self:service}
    description: >
      CI_BUILD_URL=${self:custom.codeship.CI_BUILD_URL}
    handler: src/handler.authorizer
    timeout: 3
    memorySize: 128

    # CI can setup environmental variables for build
    environment:
      SOME_ENV: ${env:SOME_ENV}
      # https://github.com/serverless/serverless/issues/2764
```

* What stacktrace or error message from your provider did you see?
n/a

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Would be nice to be able to build strings based on evaulated variables. Seems to work for things like `${self.provider.stage}, etc`
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.0
* ***Operating System***: osx
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
@dreadjr thanks for reporting.

Could you re-try it with this slight change (no string fallback for the `CI_COMMIT_ID` Serverless variable:

```yml
custom:
  webpackIncludeModules: true,
  codeship:
    CI_COMMIT_ID: ${env:CI_COMMIT_ID}
```

Are you seeing the same error?

**Comment by pmuens** [comment]
@dreadjr any update on this one? Does the code example above resolves the issue?

**Comment by willmorgan** [comment]
I am also getting this issue. If I'm using Serverless variables to look at the environment first, then fall back to defaults, what should the below yield if the env var isn't set? Should it fall back to default? (I think it should, but I get undefined.)

```
  defaults:
    stage: 'dev'
    email: 'test+fromlambda@example.org'
  sendAlertEmail:
    handler: alerts-handler.sendAlertEmail
    environment:
      EMAIL: ${env:EMAIL, self:defaults.email}
```

**Comment by dreadjr** [comment]
@pmuens That is not working for me either. I am wondering if i can use the yaml features in conjunction to make this work.

**Comment by pmuens** [comment]
@dreadjr thanks for getting back!

We'll look into this more closely and try to reproduce it.

**Comment by eahefnawy** [comment]
@dreadjr I just took a deep dive into this. I was able to reproduce, but then I realized that we don't currently support what you're trying to accomplish.

The issue is that you're trying to overwrite with string fallbacks, while our implementation only supports valid variable sources (ie. `env:`, `self:`, `file:`...etc). So as a work around you can do the following, which is basically the same thing:

```yml
custom:
  webpackIncludeModules: true,
  defaults:
    CI_COMMIT_ID: CI_COMMIT_ID
    CI_BUILD_URL: CI_BUILD_URL
  codeship:
    CI_COMMIT_ID: ${env:CI_COMMIT_ID, self:custom.defaults.CI_COMMIT_ID}
    CI_BUILD_URL: ${env:CI_BUILD_URL, self:custom.defaults.CI_BUILD_URL}
```

I do realize this is more complex than it needs to be, but imo supporting your use case is a bigger question to discuss, and it opens even more questions (ie. should we support other types too? not just strings).

Did you see anywhere in the docs that references this usage? If so we should probably update the docs.

I'm gonna close this issue as it's not really a bug. If you feel this functionality is critical for you, please feel free to open another issue as a feature proposal 😊
