### ISSUE TITLE
RDS VPC permissions don't seem to work

### ISSUE THREAD

**Issue by continuata** [serverless/serverless#2795]
# This is a Bug Report

## Can't deploy to Lambda due to RDS permission restrictions

I've added VPC and IAM permissions so that my functions will be able to connect to an RDS database on a VPC.
My config looks like this

```
provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds:*
        - cloudwatch:DescribeAlarms
        - cloudwatch:GetMetricStatistics
        - ec2:DescribeAccountAttributes
        - ec2:DescribeAvailabilityZones
        - ec2:DescribeSecurityGroups
        - ec2:DescribeSubnets
        - ec2:DescribeVpcs
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DetachNetworkInterface
        - ec2:DeleteNetworkInterface
        - sns:ListSubscriptions
        - sns:ListTopics
        - logs:DescribeLogStreams
        - logs:GetLogEvents
      Resource: "*"
  vpc:
    securityGroupIds:
      - sg-566cf12b
    subnetIds:
      - subnet-165ac861
      - subnet-9ce23ab7
```

However deployment fails, claiming that Lambda doesn't have the CreateNetworkInterface permission, that is clearly there as an Action. Here is the `serverless deploy` output

```
......Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ApiLambdaFunction
     - Your access has been denied by EC2, please make sure
     your function execution role have permission to CreateNetworkInterface.
     EC2 Error Code: UnauthorizedOperation. EC2 Error Message:
     You are not authorized to perform this operation..
```

Is this a bug, or have I totally missed something?

**Comment by laardee** [comment]
Hi @continuata, there is an issue in role creation, but this https://github.com/serverless/serverless/pull/2743 should fix that.

**Comment by continuata** [comment]
Hi @laardee thanks, I just tried the approach you suggested, but I get another error.

```
  Template format error: Unresolved resource dependencies
     [IamRoleLambdaExecution, IamPolicyLambdaExecution] in
     the Resources block of the template
```
Also your example missed adding the resource role to the function e.g.

```
functions:
  hello:
    role: HelloLambdaFunction
```

**Comment by laardee** [comment]
The `HelloLambdaFunction` in resources is "extending" the `hello` function with `DependsOn`. The `HelloLambdaFunction` is the name that CloudFormation uses. So if you have, e.g.
```
functions:
  foobar:
    handler: handler.foobar
```
you need to extend it with
```
resources:
  Resources:
    FoobarLambdaFunction:
      Type: "AWS::Lambda::Function"
      DependsOn:
        - IamRoleLambdaExecution
        - IamPolicyLambdaExecution
```
If you have many functions there is going to be a lot of those extends. Hopefully the PR gets merged soon. 😄
