### ISSUE TITLE
DynamoDB resource creation error - Property Projection cannot be empty..

### ISSUE THREAD

**Issue by prabhatsharma** [serverless/serverless#2805]
Am trying to creae a dynamodb table with a GSI, but sls is complaining about Projection property. If I remove the GSI section it works perfectly alright. Am not sure, but this looks like an issue or is my syntax wrong.

```
Table1: 
  Type: "AWS::DynamoDB::Table"
  Properties: 
    AttributeDefinitions: 
    - AttributeName: "uid"
      AttributeType: "S"
    - AttributeName: "bid"
      AttributeType: "S"
    KeySchema: 
    - AttributeName: "uid"
      KeyType: "HASH"
    - AttributeName: "bid"
      KeyType: "RANGE"
    GlobalSecondaryIndexes:
    - IndexName: "bid-uid-index"
    - KeySchema:
      - AttributeName: "bid"
        KeyType: "HASH"
      - AttributeName: "uid"
        KeyType: "RANGE"
    - Projection: 
      - ProjectionType: "ALL"
    - ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    ProvisionedThroughput: 
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    TableName: "Table1"
```

Apart from the above syntax for projection I also tried without success
- Projection: "ALL"

## Additional Data

* ***Serverless Framework Version you're using***: 1.2
* ***Operating System***: Ubuntu 16.0 LTS
* ***Stack Trace***:
* ***Provider Error messages***: - Property Projection cannot be empty..

**Comment by prabhatsharma** [comment]
Never mind, my syntax was wrong

```
GlobalSecondaryIndexes:
- IndexName: "bid-uid-index"
    KeySchema:
    - AttributeName: "bid"
    KeyType: "HASH"
    - AttributeName: "uid"
    KeyType: "RANGE"
    Projection: 
    ProjectionType: "ALL"
    ProvisionedThroughput:
    ReadCapacityUnits: 1
    WriteCapacityUnits: 1
```

Changing it to above fixed the errors...
