### ISSUE TITLE
Form Urlencoded values containing single quotes incorrectly escaped

### ISSUE THREAD

**Issue by evilantnie** [serverless/serverless#2807]
# This is a Bug Report
### What went wrong?
Similar to the problem reported in #2270, values in a JSON object that contain a single quote in an application/x-www-form-urlencoded body submitted to an API Gateway method using the DEFAULT_FORM_URL_ENCODED_REQUEST_TEMPLATE body mapping template return an error:

```
{"message": "Could not parse request body into json: Unrecognized character escape \'\'\' (code 39)\n at [Source: [B@3eb459f3; line: 6, column: 594]"}
```

You should be able to repro with the following curl command:

```
curl -v -X POST -d "payload=%7B%22testkey%22%3A%22what%27s+up%22%7D" -H "Accept: application/x-www-form-urlencoded" <your test endpoint>
```

### What did you expect should have happened?
Expected body mapping from application/x-www-form-urlencoded to JSON to succeed. Followed by invocation of the method integration.

### What was the config you used?
```
functions:
  response:
    handler: handler.response_handler
    events:
      - http:
          path: sprints/response
          method: post
          integration: lambda
```

### What stacktrace or error message from your provider did you see?
```
Could not parse request body into json: Unrecognized character escape \'\'\' (code 39)\n at [Source: [B@3eb459f3; line: 6, column: 594]
```

### Similar or dependent issues:
* #2270

## Additional Data

* ***Serverless Framework Version you're using***: 1.1.0
* ***Operating System***: OS X 10.11.6
* ***Stack Trace***:
* ***Provider Error messages***:
