### ISSUE TITLE
stream-event compiler fails to parse non-string arn parameter

### ISSUE THREAD

**Issue by jjuitt** [serverless/serverless#2812]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Generating handler for stream event fails with error  
`EventSourceArn.split is not a function`
* What did you expect should have happened?
Cloudformation template would have been successfully generated and function deployed.
* What was the config you used?
```yml
  dynamoTrigger:
    handler: handler.trigger
    description: "Neat description"
    events:
      - stream:
          arn:
            Fn::GetAtt:
              - DynamoTableInResources
              - StreamArn
```
Current [documentation](https://serverless.com/framework/docs/providers/aws/events/streams/) shows that it is fine to generate the ARN using CF functions.
* Serverless stacktrace (relevant parts)
```
TypeError: EventSourceArn.split is not a function
    at functionObj.events.forEach.event (/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:60:47)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:20:28)
    at Array.forEach (native)
    at AwsCompileStreamEvents.compileStreamEvents (/node_modules/serverless/lib/plugins/aws/deploy/compile/events/stream/index.js:16:47)
    at BbPromise.reduce (/node_modules/serverless/lib/classes/PluginManager.js:160:50)
    at tryCatcher 
```

Similar or dependent issues:
* [#2365](https://github.com/serverless/serverless/issues/2365)
Seems like I jumped the gun a little, since that is an exact clone.

## Additional Data

* ***Serverless Framework Version you're using***:
1.2
* ***Operating System***:
Ubuntu 16.04

**Comment by jjuitt** [comment]
Seems like this bug is being worked on in [#2488](https://github.com/serverless/serverless/pull/2488).
However, I didn't see any test cases for
```yml
dynamoTrigger:
    handler: handler.trigger
    description: "Neat description"
    events:
      - dynamodb:
          arn:
            Fn::GetAtt:
              - DynamoTableInResources
              - StreamArn
```
while event `kinesis` had a test case for `Fn::GetAtt:` structure. Will it not support GetAtt for DynamoDB streams?
