### ISSUE TITLE
Local environment variables don't work with CloudFormation references

### ISSUE THREAD

**Issue by jeremydaly** [serverless/serverless#2817]
# This is a Bug Report

## Description
When specifying CloudFormation references in environment variables (e.g. `QUEUE_URL: { "Ref": "queue" }`), the values don't load when invoking the function locally.

For bug reports:
* What went wrong?
Environment variables that used CloudFormation references displayed `[Object object]`
* What did you expect should have happened?
The CloudFormation references should have been resolved (e.g. `arn:aws:sns:us-east-1:XXXXXXXXXXXX:notifications`)
* What was the config you used?
```
environment:
  NOTIFICATION_TOPIC: { "Ref": "notifications" }
```
* What stacktrace or error message from your provider did you see?
n/a
Similar or dependent issues:
* none

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: MacOS
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

**Comment by dougmoscrop** [comment]
You're mixing YAML and JSON, but it's effectively a string because serverless is not parsing json-within-yaml.

```yaml
environment:
  NOTIFICATION_TOPIC:
    Ref: notifications
```

or

```yaml
environment:
  ROOT:
    Fn::GetAtt:
      - ApiGatewayRestApi
      - RootResourceId
```
