### ISSUE TITLE
provider.stage and provider.region do not respect options.{stage, region}

### ISSUE THREAD

**Issue by dougmoscrop** [serverless/serverless#2824]
# This is a Bug Report

## Description

Consider: `sls deploy -s test`

What a lot of people end up doing is something like this:

```yml
custom:
  stage: ${opt.stage, self:provider.stage}

provider:
  environment:
    stage: ${self:custom.stage}
```

I think that's unnecessarily verbose and to people who don't know to do the 'custom.stage alias' they get this kind of bug:

```yml
provider:
  environment:
    stage: ${self:provider.stage}
```

this would deploy a function, foo, to `foo-test` but with `process.env.stage=dev` because provider.stage is always the default stage.

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: OS X
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a
