### ISSUE TITLE
[v1.0.2] Custom authenticators not always working

### ISSUE THREAD

**Issue by jagi** [serverless/serverless#2827]
Hi, I'm trying to use custom authenticator and it works as long as I assign it to the single lambda function. If I assign it to more functions it randomly fails to authenticate user. Here is an example of not working code:

```js
// handlers.js
const fs = require('fs');
const jwt = require('jsonwebtoken');

function authenticate(token) {
  const secret = fs.readFileSync(`${__dirname}/secret.key`);
  return jwt.verify(token.split(' ')[1], secret);
}

function generatePolicy(principalId, effect, resource) {
  const authResponse = {};
  authResponse.principalId = principalId;
  if (effect && resource) {
    const policyDocument = {};
    policyDocument.Version = '2012-10-17';
    policyDocument.Statement = [];
    const statementOne = {};
    statementOne.Action = 'execute-api:Invoke';
    statementOne.Effect = effect;
    statementOne.Resource = resource;
    policyDocument.Statement[0] = statementOne;
    authResponse.policyDocument = policyDocument;
  }
  return authResponse;
}

module.exports.authorizer = (request, context, callback) => {
  const token = request.authorizationToken;
  try {
    const decoded = authenticate(token);
    callback(null, generatePolicy(decoded.email, 'Allow', request.methodArn));
  }
  catch(err) {
    callback('Unauthorized');
  }
};

module.exports.handlerA = (request, context, callback) => {
  const email = request.requestContext.authorizer.principalId;
  return handlerA(email).then(function(data) {
    const response = {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin' : '*'
      },
      body: JSON.stringify(data)
    };
    callback(null, response);
  }).error(function(err) {
    callback(err);
  });
};

module.exports.handlerB = (request, context, callback) => {
  const email = request.requestContext.authorizer.principalId;
  return handlerB(email).then(function(data) {
    const response = {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin' : '*'
      },
      body: JSON.stringify(data)
    };
    callback(null, response);
  }).error(function(err) {
    callback(err);
  });
};
```

```yml
# serverless.yml
functions:
  authorizer:
    handler: handlers.authorizer
  handlerA:
    handler: handlers.handlerA
    events:
      - http:
          path: handlerA
          method: get
          cors: true
          authorizer: authorizer
  handlerB:
    handler: handlers.handlerB
    events:
      - http:
          path: handlerB
          method: get
          cors: true
          authorizer: authorizer
```

@zacharyrote proposed solution for that problem that is working but is not perfect workaround. When you create separate authorizer handler for each lambda function, then it will work. Does anyone know how to solve this problem with single authorizer function?
