### ISSUE TITLE
CloudWatchEvent rule name and description fields

### ISSUE THREAD

**Issue by ajshukury** [serverless/serverless#2832]
```
functions:
  run:
    handler: handler.run
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: false
          name: "I want my own name prefix here"
          description: "I want my own description here"
```
When deploying lambda with scheduled events, a cloud watch event rule gets created with the schedule specified in yml. How can we add the name and description field? Currently, it adds an ugly long name with no description.
