### ISSUE TITLE
Function zip files using `artifact` overwrite each other in ServerlessDeploymentBucket

### ISSUE THREAD

**Issue by mariusmarais** [serverless/serverless#2837]
# This is a Bug Report

## Description
Given the `serverless.yml`:
```yaml
...
package:
  individually: true

functions:
  thing1:
     ...
     package:
       artifact: thing1/dist/package.zip

  thing2:
     ...
     package:
       artifact: thing2/dist/package.zip
```

Serverless uploads the zip files to `${ServerlessDeploymentBucketName}/${stage}/xxx/` without changing the filenames, causing all defined functions to run the code from the last-uploaded `package.zip`. Hilarity ensues.

* What went wrong?
    Last-uploaded function package overwrites other functions' packages, causing all functions to run the same code
* What did you expect should have happened?
    Filenames in the S3 bucket should be replaced / prepended with the function name or otherwise uniqueified.
* What was the config you used?
    See above.
* What stacktrace or error message from your provider did you see?
    None.

## Workaround
Rather use a `serverless.yml` like:
```yaml
...
package:
  individually: true

functions:
  thing1:
     ...
     package:
       artifact: thing1/dist/package1.zip

  thing2:
     ...
     package:
       artifact: thing2/dist/package2.zip
```

But this is error-prone and slightly cumbersome with a standardized function build process.

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: OSX 10.12.1 (Sierra)
* ***Stack Trace***: None
* ***Provider Error messages***: None
