### ISSUE TITLE
Input information passed in from schedule events , not appearing in the event object of the lambda function

### ISSUE THREAD

**Issue by soumyadash14** [serverless/serverless#2844]
# This is a (Bug Report)

## Description
I am trying to pass in stage information to the scheduled function like this -->

```yml
events:
  - schedule:
       rate: rate(1 minute)
       enabled: true
       input:
         stageParams:
            stage: ${opt:stage , self:custom.defaultStage}
```

But I am not getting these information in the event object in my lambda function.

Can someone please let me know if there is a way to pass in these information to the lambda function ?

## Additional Data
Serverless Version-  v1.1.0
Win8.1***:
