### ISSUE TITLE
Cannot get authorizer to work! 

### ISSUE THREAD

**Issue by neoadventist** [serverless/serverless#2869]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
> tried to make a authorizer function with lambda. 
* What did you expect should have happened?
> I expected the handler.js function to fire. 
* What was the config you used?
```
functions:
  authorizerFunc:
    handler: handler.authorize
    events:
      - http:
          path: a/authorize
          method: get
          cors: true
  properties:
    handler: handler.properties
    events:
      - http:
          path: a/properties
          method: get
          cors: true
          authorizer: authorizerFunc
```
* What stacktrace or error message from your provider did you see?
`{"message":"Unauthorized"}` 

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.1.0
* ***Operating System***: Ubuntu
* ***Stack Trace***:
```
{
    "errorMessage": "Converting circular structure to JSON",
    "errorType": "TypeError",
    "stackTrace": []
}
```
* ***Provider Error messages***:
