### ISSUE TITLE
Option to disable Lambda versioning

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#2871]
# This is a Feature Proposal

## Description

Right now Lambda versioning is turned on by default. It would be great to have a way to turn it off again.

We could implement it like this (`provider` level means global, `function` level overwrites provider level):

```yml
provider:
  versionLambda: false

functions:
  foo:
    versionLambda: false
```
