### ISSUE TITLE
Circular dependency between resources when adding SNS Publish iamRoleStatements

### ISSUE THREAD

**Issue by sime** [serverless/serverless#2873]
# This is a Bug Report
Regression from 1.2.1.

Previously working SNS Publish  policy `iamRoleStatements` is no longer functioning in 1.3.0.

Two functions:
1. `goodbye` is triggered by SNS `message-topic`. 
2. `hello` function will publish to `message-topic`. Publish access to the SNS topic was granted globally in `iamRoleStatements`.

## Description

* What went wrong?
Running the below configuration fails with a `Circular dependency between resources` error in 1.3.0
* What was the config you used?
```yaml
service: snspublish

provider:
  name: aws
  runtime: nodejs4.3

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "sns:Publish"
      Resource:
       - "Ref" : "SNSTopicMessagetopic"

functions:
  hello:
    handler: handler.hello

  goodbye:
    handler: handler.goodbye
    events:
       - sns: message-topic
```
* What stacktrace or error message from your provider did you see?
`Circular dependency between resources`

## Additional Data

* ***Serverless Framework Version you're using***:
1.3.0
* ***Operating System***:
OS X
* ***Stack Trace***:
```bash
$ serverless deploy -v
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - snspublish-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - snspublish-dev
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (599 B)...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

     Circular dependency between resources: [HelloLambdaVersionfMe8fdZCMj6QS5bnQ5ePNY04DFpGrH0dAp9Zneb5Fo,
     GoodbyeLambdaFunction, HelloLambdaFunction, IamPolicyLambdaExecution,
     GoodbyeLambdaPermissionMessagetopicSNS, GoodbyeLambdaVersionfMe8fdZCMj6QS5bnQ5ePNY04DFpGrH0dAp9Zneb5Fo,
     SNSTopicMessagetopic]

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.7.0
     Serverless Version: 1.3.0

```
* ***Provider Error messages***:

**Comment by sime** [comment]
Should note a quick workaround is `Resource: "*"`

**Comment by eahefnawy** [comment]
@sime So the issue is that `goodbye` function depends on the SNS topic (due to the global IAM role), and the SNS topic depends on the `goodbye` function.

I think the solution for you is to use custom function role instead of global roles. Check it out here:
https://serverless.com/framework/docs/providers/aws/guide/iam/#a-custom-default-role--custom-function-roles

Closing this as it's not really a bug imo

**Comment by sime** [comment]
@eahefnawy I logged as a bug because it was working previously.

I've stayed away from custom IAM roles due to the big fat `WARNING` on the documentation.

Though since SNS is the preferred way to communicate between Lambda's this method seems very verbose?

**Comment by eahefnawy** [comment]
@sime agreed. We're currently investigating adding support for the recently announced AWS SAM standard. This should delegate the permission handling to AWS even more and I think might solve this issue. So lambda/sns communication should work out of the box, based on my assumptions.

**Comment by kennu** [comment]
Shouldn't this be considered a bug? It seems like a pretty basic requirement that if you create an SNS topic, you also need to be able to publish messages to it. Particularly since the support for subscribing to existing SNS topics was removed in Serverless 1.x.

**Comment by kennu** [comment]
Btw, using a custom Lambda role only helps if you split it into a separate `AWS::IAM::Role` and `AWS::IAM::Policy` so that the circular dependency is eliminated. I think Serverless should be doing that by default for the built-in `iamRoleStatements`.

**Comment by pmuens** [comment]
Hey @kennu thanks for your response!

@dougmoscrop PRed a change that adds the possibility to connect a function to an existing topic via the topics `arn`. Maybe you can look into the PR if you have some time. We're about to release it in the upcoming version: https://github.com/serverless/serverless/pull/2796

**Comment by kennu** [comment]
@pmuens It seems like a very useful feature! Although I don't think it removes the need for simple adding of publish permissions for SNS topics created by Serverless itself. I think all possible variations will occur in loosely architected applications (publish to own SNS topic, publish to another service's SNS topic, listen to own SNS topic, listen to another service's SNS topic).

**Comment by pmuens** [comment]
Ah ok. Thanks for the clarification @kennu 

/cc @eahefnawy

**Comment by guillaumervls** [comment]
@sime & @eahefnawy Having also struggled about this, to avoid custom function roles you can declare your SNS topic in the `resource` section and use it thanks to @pmuens feature :

```yaml
service: snspublish

provider:
  name: aws
  runtime: nodejs4.3

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "sns:Publish"
      Resource:
       - "Ref" : "SNSTopicMessagetopic"

functions:
  hello:
    handler: handler.hello

  goodbye:
    handler: handler.goodbye
    events:
       - sns:message-topic
           arn:
             Ref: SNSTopicMessagetopic
           topicName: message-topic

resources:
  Resources:
    SNSTopicMessagetopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: message-topic
```
