### ISSUE TITLE
Move Authorizer Settings to Custom Authorizer Function

### ISSUE THREAD

**Issue by SectorNine50** [serverless/serverless#2887]
Currently, the settings for a custom authorizer function are set within the event settings for each function:

```yaml
functions:
  newFunction:
    handler: function.handler
    events:
      -  http:
            path: url/path
            method: get
            authorizer:
              name: customAuth
              resultTtlInSeconds: 30
              identityValidationExpression: .*

  customAuth:
    handler: auth.handler
    memorySize: 128
```

This leaves room for those settings to be redefined multiple times in the configuration, and can introduce uncertainty, particularly when there are multiple hands touching the code.

It would be beneficial to have everything related to the custom authorizer in one spot, and just reference the authorizer by name in each function.  Something like this:

```yaml
functions:
  newFunction:
    handler: function.handler
    events:
      -  http:
            path: url/path
            method: get
            authorizer: customAuth

  customAuth:
    handler: auth.handler
    memorySize: 128
    authorizerSettings:
      resultTtlInSeconds: 30
      identityValidationExpression: .*
```

**Comment by pmuens** [comment]
Thanks for the suggestion @SectorNine50 

I'll close this to keep the issue count low. Furthermore the current settings definition is widely adopted and changing it would introduce a breaking change.

**Comment by mpaleo** [comment]
@pmuens So, if we have 5, 50 or N functions, we have to redefine identitySource and identityValidationExpression, etc, every time ?

Thanks!

**Comment by SectorNine50** [comment]
For what it's worth, I think this could be implemented in a way that it wouldn't cause a breaking change.

**Comment by mpaleo** [comment]
@SectorNine50 I'm not familiar with the implementation and retro-compatibility of the project, but it would help to follow the "DRY" principle and reduce errors.

Thanks for the response

**Comment by SectorNine50** [comment]
@mpaleo Sorry, wasn't referencing your comment, was referencing @pmuens.

I agree with you entirely, I was the original creator of this issue! ;-)

**Comment by HyperBrain** [comment]
IMO semantically the authorizer (and its settings) are part of the endpoint definition (APIG) and should be specified there (as is in the http event).

But there would be a Serverless solution for that by using variables (if they support objects as values and not only strings). Imagine you would declare your settings in a variable like this and use that:
```
functions:
  newFunction:
    handler: function.handler
    events:
      -  http:
            path: url/path
            method: get
            authorizer: ${self:custom.myCustomAuthDef}

  customAuth:
    handler: auth.handler
    memorySize: 128

custom:
  myCustomAuthDef:
    name: customAuth
    resultTtlInSeconds: 30
    identityValidationExpression: .*

```

That will allow to keep settings and properties where they belong, but also let reuse configurations as much as possible. How does that sound?

@pmuens Can you put some info here on support ob "object" variables?

**Comment by SectorNine50** [comment]
@HyperBrain That works, sure.  Personally, it feels a little hacky, and I don't think should be a long-term solution...  But maybe I'm being too pedantic.

It's ultimately just odd to see it implemented the way it is in Serverless seeing as how an Authorizer in CloudFormation is described independently, and then referenced by ID in each Method.

Authorizer:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html

Method:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html

**Comment by pmuens** [comment]
Thanks for the feedback @SectorNine50 @mpaleo and @HyperBrain 

Reopening and waiting for more feedback on this one since it seems to be a DX issue.

**Comment by SectorNine50** [comment]
In my mind, there's no reason to remove the previous functionality, we could just make the new style take precedent, if it exists.

For example, if this is the serverless config:
```yaml
functions:
  newFunction:
    handler: function.handler
    events:
      -  http:
            path: url/path
            method: get
            authorizer: customAuth

  newFunction2:
    handler: function2.handler
    events:
      -  http:
            path: url/path2
            method: get
            authorizer:
              name: customAuth
              resultTtlInSeconds: 45
              identityValidationExpression: \d*

  customAuth:
    handler: auth.handler
    memorySize: 128
    authorizerSettings:
      resultTtlInSeconds: 30
      identityValidationExpression: .*
```

Since `customAuth` has the `authorizerSettings` key, Serverless should ignore `newFunction2`'s settings. Or perhaps just error out stating that both styles are in use, and recommend a move to the new style.

**Comment by fantapop** [comment]
I'd be interested in something along these lines.  My assumption would be that authorizer params closer to the actual event would override the outer definition.

**Comment by chrisoverzero** [comment]
I've been reducing the repetition of this by using the YAML anchors feature.

```yaml
custom:
  <<: &authorizer # Establish the anchor, named "authorizer".
    arn: arn:aws:lambda:re-name-1:4234545:function:I-Am-An-Authorizer
    identityValidationExpression: ^Bearer +[-0-9a-zA-Z\._]*$
    # Other values as necessary.

functions:
  routeRequest:
    handler: handler.routeRequest
    events:
      - http:
          path: routeRequest
          method: POST
          authorizer: *authorizer # This sets the anchored object as the value for the key.
```

(The key with the anchor "authorizer" could be "authorizer", as well, but I like the "<<" syntax to keep the object anonymous.)

This strikes me as a better solution than expanding Serverless' string interpolation syntax to handle objects somehow.

**Comment by fantapop** [comment]
I've been using the js syntax for this since it came it.  It works well.  The only tricky part about the JS syntax is that the file doesn't know what the stage is at the time of execution of the javascript so I had to mix serverless interpolation syntax with javascript syntax and export my js config to additionally include a function that returns the config.

**Comment by iscofield** [comment]
+1'ing @SectorNine50's approach.  I have a ton of functions and I'd like to not paste the same object hundreds of times and would prefer to declare it once per authorizer.

**Comment by medikoo** [comment]
It looks to me as design bug that authorizer settings are configured at event level, e.g. in following example configuration same authorizer is used for two events, in each, different value for `resultTtlInSeconds` is provided. Unexpected result is that only one authorizer setup is created (which is reused for both events) and it's only the latter `resultTtlInSeconds` value that's respected.

```yaml
functions:
  authorize:
    handler: authorize.handler
  function:
    handler: index.handler
    events:
      - http:
          path: /test
          method: GET
          authorizer:
            name: authorize
            resultTtlInSeconds: 45
  function2:
    handler: index.handler
    events:
      - http:
          path: /test2
          method: GET
          authorizer:
            name: authorize
            resultTtlInSeconds: 30
```

I believe in case of `http` events, authorizers should be configured same as it's in case of `httpApi` events, where only endpoint specific authorizer settings can be configured at event level, and rest is expected to be configured in `provider.httpApi.authorizers[]` section. 

I've updated main description with short implementation proposal
