### ISSUE TITLE
Deploy fails when using deploymentBucket / SSE support

### ISSUE THREAD

**Issue by gmetzker** [serverless/serverless#2888]
I'm trying to use `serverless deploy` with a pre-existing bucket for the deployment package.  When I add the `deploymentBucket` value in the provider I get the following error:  **self signed certificate in certificate chain**

If I remove `deploymentBucket` the CF stack attempts to create but I don't have permissions to create buckets (nor do I want to).

Can I use the issue described here #2189 to define a pre-existing target S3 bucket where packages are uploaded to?

```
$ serverless deploy -v
 
  Serverless Error ---------------------------------------
 
     self signed certificate in certificate chain
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.2.1
     Serverless Version: 1.3.0
```

Here is a snippit from my serverless.yml
```
provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-2
  deploymentBucket: my-cool-bucket
  profile: sdrad-workflow-dev
```
Any ideas?

**Comment by gmetzker** [comment]
I think this might be caused by the requirement on our buckets for server side encryption.  I'll try and test later with a bucket without this policy.

```
        {
            "Sid": "DenyNoEncryption",
            "Effect": "Deny",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::hli-workflow-sdrad-pdx/*",
            "Condition": {
                "StringNotEquals": {
                    "s3:x-amz-server-side-encryption": "AES256"
                }
            }
        },
```

**Comment by pmuens** [comment]
@gmetzker thanks for the update!

Yes, I've also found these links:
https://forums.aws.amazon.com/message.jspa?messageID=604354
http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html

Seems like something has to be configured in your end?! Would be great if you could report back once you've hopefully resolved this problem 👍

**Comment by gmetzker** [comment]
It turns out this encryption policy was causing my issue.  When I use a bucket that is less strict I don't get this error.

It seems like it might be helpful to support the various S3 encryption options.  Maybe on the provider there we should implement a section that specifies all the standard ss3/kms options for the s3 uploads.

```
deploymentBucketOptions:
  deploymentBucket: {bucket name}
  sse: {AES256|aws:kms}
  sseKmsKeyId:  {kms keyid for serverside encryption}
  sseCustomerKey:  {Customer Provided Encryption Key use for server-side encryption}

```
