### ISSUE TITLE
Enable serverless variables on keys as well

### ISSUE THREAD

**Issue by borisirota** [serverless/serverless#2892]
# This is a Feature Proposal

## Description

S3 enabled object tagging about a month ago and added access control policy variables with [dynamic key names](http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html#tagging-and-policies).

I faced it when tried to set the next policy in `serverless.yml`:
```
...
resources:
  Resources:
    ...
    IamPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: policy name
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - myBucket
              Condition:
                StringEquals:
                  "s3:ExistingObjectTag/${self:custom.tags.key}": ${self:custom.tags.value}
...
```
And the generated CF template contained the `s3:ExistingObjectTag/${self:custom.tags.key}` as is.

Without supporting dynamic key names in `serverless.yml` there is no option to manage the tags in a common config with access from multiple places but rather hard code the tags in the `serverless.yml`.

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: Mac OSX

**Comment by pmuens** [comment]
Thanks for reporting @borisirota 👍 
You can use JavaScript to generate those values dynamically https://serverless.com/framework/docs/providers/aws/guide/variables/

Does this solve your problem?

**Comment by borisirota** [comment]
@pmuens Thanks for the quick reply !

Yes it helps since I can return dynamically created object from file.

But does this solution is better than enabling dynamic key names in the `serverless.yml` config ?
It means that the CF template's structure (not only the dynamic values) is being split across several files which isn't ideal IMHO.

**Comment by pmuens** [comment]
@borisirota glad to hear that it helped.

How could an implementation for dynamic keys look like? Can your provide an example? Thanks!

**Comment by borisirota** [comment]
@pmuens hmmm I provided in the description. I updated the example with relevant context.

Please focus me on what you are exactly asking for in case I didn't understand you correctly.

**Comment by SectorNine50** [comment]
The problem that I've ran into with Serverless and the CloudFormation templates in `serverless.yml`, is that the variables don't seem to get parsed within the CF template.  I _think_ that might be what he's trying to get at here; it would be really nice to be able to define variables in the `serverless.yml` file that can be utilized in the CF template, as well as other locations in the configuration file.  Means that when you want to make a change, you would just change that variable, and wouldn't have to hunt for all the other places that need to be changed in unison.

**Comment by borisirota** [comment]
@SectorNine50 I just want to clarify that I have issues only when using variables as keys in the CF template. I didn't ran into issues when using variables as values (I have 400 lines of CF template with variables being used all over inside `serverless.yml`).

=>

The input:
```
Condition:
  StringEquals:
    "s3:ExistingObjectTag/${self:custom.tags.key}": ${self:custom.tags.value}
```
generates the output:
```
Condition:
  StringEquals:
    "s3:ExistingObjectTag/${self:custom.tags.key}": REAL_VALUE
```

Is this your case also or you have issues using variables as values as well ?

**Comment by SectorNine50** [comment]
Oh, hm...  I haven't been able to get the value to work in CF templates, not sure why.

I'll bow-out then. :)

**Comment by bartvollebregt** [comment]
Yep... This is very annoying when using `AWS::Cognito::IdentityPoolRoleAttachment`.
The `RoleMappings` property needs a key which contains Authentication provider id...
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html#cfn-cognito-identitypoolroleattachment-rolemappings

This is impossible to do without key interpolation.

Example:
```
# Assigns the roles to the Identity Pool
IdentityPoolRoleMapping:
  Type: "AWS::Cognito::IdentityPoolRoleAttachment"
  Properties:
    IdentityPoolId:
      Ref: IdentityPool
    RoleMappings:
      cognito-idp.YOUR_REGION.amazonaws.com/YOUR_COGNITO_USERPOOL_ID:YOUR_COGNITO_CLIENT_ID:
        Type: "Rules"
        AmbiguousRoleResolution: "AuthenticatedRole"
        RulesConfiguration:
          Rules:
            - Claim: "cognito:groups"
              MatchType: "Contains"
              RoleARN: { "Fn::GetAtt": ["CognitoAuthorizedRole", "Arn"] }
              Value: "Admin"
    Roles:
      authenticated: { "Fn::GetAtt": ["CognitoUnAuthorizedRole", "Arn"] }
      unauthenticated: { "Fn::GetAtt": ["CognitoUnAuthorizedRole", "Arn"] }
```

**Comment by rkim-work** [comment]
@bartvollebregt 
did you found a solution ? 
Same case : how to define rbac identity pool rolemappings without key interpolation in serverless.yml? (By simply first deploy & then update to add the key with previously created ids?)

**Comment by bartvollebregt** [comment]
@rkim-work 
So far the only "solution" I found is indeed to provision it in 2 steps (which sucks...).
First provision without role-mappings, editing the keys and then re-provision.

**Comment by bartvollebregt** [comment]
Feel like this thread on the AWS forums is related as well:
https://forums.aws.amazon.com/thread.jspa?messageID=783626#783626

**Comment by bartvollebregt** [comment]
@rkim-work So I managed to find a workaround for this issue which allows the rolemapping key to be dynamic. It's based on the [forum thread](https://forums.aws.amazon.com/thread.jspa?messageID=783626#783626) I posted before.
The workaround consists of Custom Resource which pulls it's mappings from a Lambda function.
The Lambda function is only called on deployment.

This works quite well. The only issue I'm having is when I change the mapping I get the following error:
`An error occurred: IdentityPoolRoleMapping - Resource cannot be updated.`

Below is an example of the Serverless Resources required to get this working (based on the configuration in [my first post](https://github.com/serverless/serverless/issues/2892#issuecomment-400326146).

```
Resources:
#  ... UserPool, UserPoolClient, Roles, etc.

  DynamicMapTransformLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Transform to generate maps with computed keys
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs6.10
      Timeout: '30'
      Code:
        ZipFile: |
          const { send, SUCCESS, ERROR } = require('cfn-response');
          exports.handler = (event, context, callback) => {
            console.log(JSON.stringify(event, null, 2));
            const { RequestType, ResourceProperties: props = { } } = event;
            const { Entries: entries = [ ], AttributeName: attName } = props;

            switch(RequestType) {
              case 'Create':
              case 'Update':
                const result = { };
                for (let i = 0; i < entries.length; i++) {
                  const { Key, Value } = entries[i]
                  if (Key) {
                    result[Key] = Value
                  }
                }
                send(event, context, SUCCESS, { [attName]: result });
                break;
              case 'Delete':
                send(event, context, SUCCESS);
                break;
            }
          };

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
            
  # Assigns the roles to the Identity Pool
  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId:
        Ref: IdentityPool
      RoleMappings:
        Fn::GetAtt:
        - IdentityPoolRoleAttachmentMapping
        - RoleMappings
      Roles:
        authenticated: { "Fn::GetAtt": ["CognitoUnAuthorizedRole", "Arn"] }
        unauthenticated: { "Fn::GetAtt": ["CognitoUnAuthorizedRole", "Arn"] }

  IdentityPoolRoleAttachmentMapping:
    Type: Custom::DynamicMapTransform
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - DynamicMapTransformLambda
          - Arn
      AttributeName: RoleMappings
      Entries:
        - Key:
            Fn::Join:
              - ":"
              - - Fn::GetAtt:
                    - UserPool
                    - ProviderName
                - Ref: UserPoolClient
          Value:
            Type: Rules
            AmbiguousRoleResolution: AuthenticatedRole
            RulesConfiguration:
              Rules:
              - Claim: "cognito:groups"
                MatchType: "Contains"
                Value: "Admin"
                RoleARN: { "Fn::GetAtt": ["CognitoAuthorizedRole", "Arn"] }

```

**Comment by kevinsperrine** [comment]
@bartvollebregt Have you found a solution for the "Resource cannot be updated." error?

**Comment by bartvollebregt** [comment]
> @bartvollebregt Have you found a solution for the "Resource cannot be updated." error?

Negative... It seems to be a CloudFormation issue.

**Comment by kevinsperrine** [comment]
@bartvollebregt Yep. It is. I opened a support ticket with AWS and they confirmed it. 

From AWS Support:
>  the problem is actually a discrepancy in the documentation, as updating the RoleAttachment in a Cognito Identitypool isn't supported by Cloud Formation. I do apologize about the confusion and inconvenience, but this is a limitation of the Cloud Formation service. We have a feature request in and I have went ahead and +1 the ticket on your behalf.

**Comment by bartvollebregt** [comment]
@kevinsperrine Thanks! Please let us know if you hear anything from AWS Support

**Comment by rdsedmundo** [comment]
Also wanting this. I'll try the JavaScript solution.

Without this feature proposed here it's impossible to create a custom Bucket with a dynamic name, and use it with an `s3` event because the Logical ID contains the dynamic bucket name.

**Comment by mblarsen** [comment]
> Thanks for reporting @borisirota +1
> You can use JavaScript to generate those values dynamically https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files
> 
> Does this solve your problem?

Would it be possible to reference other resources through the `serverless` function argument this way.

To be able to create RoleMappings for IdentiyPool the keys for external providers are easy, they are just static strings like `graph.facebook.com`, but for Cognito it needs to be the user pool ID e.g. `cognito-idp-east-1.amazonaws.com/us-east-1_abcdefghi:app_client_id`

I guess you would need something like this:

```javascript
module.exports.promised = serverless => {
  return new Promise((resolve, reject) => {
    ... subscribe to hook post user pool creation then ...
     const userPoolId = ...
     return {
         [userPoolId]: { ... role mapping values ... },
         'graph.facebook.com': { ... facebook role mapping values ...  },
     }
  })
}
```

Does this approach make sense? What would be the hook to subscribe to?

**Comment by medikoo** [comment]
We looked into this problem when implementing new resolver, and it looks as something that will  introduce an additional significant complexity, while use case is rare and can be addressed with alternative means.

-  Resolved key, technically may match already existing key, so even if value is successfully resolved we may need to reject the configuration
- Variable in a key technically means that we cannot assume any not existing property as not existing before resolving key in question. That makes resolution of those properties pending until key is resolved.

Use case in main example can  be quite easily solved with variable JS file resolver (as pointed by @pmuens in [first comment](https://github.com/serverless/serverless/issues/2892#issuecomment-265679992)), and with new variables resolver, [JS resolver can access all configuration properties in resolved form](https://www.serverless.com/framework/docs/providers/aws/guide/variables#exporting-a-function), So his is how I would recommend solving this:

```yaml
resources:
  Resources:
    ...
      Condition:
        StringEquals: ${file()}
          "s3:ExistingObjectTag/${self:custom.tags.key}": ${self:custom.tags.value}
...
```

```condition.js
module.exports = async ({ resolveConfigurationProperty }) => {
  return {
     `s3:ExistingObjectTag/${await resolveConfigurationProperty(["custom", "tags", "key"])}`: ${await resolveConfigurationProperty(["custom", "tags", "value"])}
  };
}
```

Closing, but if you still struggle with some use case please comment, we'll do our best to come up with satisfiable solution
