### ISSUE TITLE
Add Retry property for SNS events

### ISSUE THREAD

**Issue by mtomic** [serverless/serverless#2929]
# This is a Feature Proposal

## Description

By default all SNS topics created in AWS have a default number of retries set to 3. That includes topics created by the serverless framework.  This can sometimes be undesirable.   It would be good to be able to control the number of retries via ```serverless.yml``` file

I propose something like this:
```
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns: dispatch
           retries: 3
  dispatcher2:
    handler: dispatcher2.dispatch
    events:
      - sns:
          topicName: aggregate
          displayName: Data aggregation pipeline
          retries: 0
```

Or even better, support the full set of delivery options below:
<img width="811" alt="screen shot 2016-12-13 at 11 52 30 pm" src="https://cloud.githubusercontent.com/assets/1195051/21141014/10cda75a-c18f-11e6-8c02-8b694fe9b37a.png">

## Additional Data

* ***Serverless Framework Version v1.3.0***:

**Comment by mthenw** [comment]
Retry policy applies only for HTTP delivery so I would prefix this with `http`

```
httpRetries: 0
```

**Comment by mtomic** [comment]
good point @mthenw

**Comment by nicka** [comment]
I may be incorrect, but I think this feature does not (yet) exist within CloudFormation. Only thing we could do here is include a Custom CloudFormation resource to set/update this value, oooooor go the sls 0.5x way of doing some aws-sdk magic behind the scenes.

**Comment by pmuens** [comment]
Closing since this issue is quite old and apparently not 100% supported for every type via CloudFormation. Feel free to re-open if support was added...

**Comment by sheakelly** [comment]
Looks like cloudformation supports this now
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html

**Comment by vladgolubev** [comment]
Since the CloudFormation support was added 1 year ago, are there any plans to support this feature?

**Comment by KnupMan** [comment]
Would be great to have this feature supported!

**Comment by pgrzesik** [comment]
Since this is supported in `CloudFormation`, I believe we should be able to support it. Is someone interested in proposing how the configuration should look like in `serverless.yml`? Should we support other properties of `DeliveryPolicy` in addition to `retries`?

**Comment by gmcrocetti** [comment]
Hi @pgrzesik :). I would say we should support the full spec of `DeliveryPolicy`.

```yaml
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns:
          arn: !Ref SuperTopic
          deliveryPolicy:
            numRetries: 20
            minDelayTarget: 10
            maxDelayTarget: 30
            numMinDelayRetries: 3
            numMaxDelayRetries: 17
            numNoDelayRetries: 0
            backoffFunction: exponential
            maxReceivesPerSecond: 10

        
resources:
  Resources:
    SuperTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: MyCustomTopic
```

The `deliveryPolicy` would be mapped to a JSON of the following type:

```json
{
  "healthyRetryPolicy": {
    "numRetries": 20,
    "minDelayTarget": 10,
    "maxDelayTarget": 30,
    "numMinDelayRetries": 3,
    "numMaxDelayRetries": 17,
    "numNoDelayRetries": 0,
    "backoffFunction": "exponential",

  },
  "throttlePolicy": {
    "maxReceivesPerSecond": 10
  }
}
```
What's your thoughts ?
