### ISSUE TITLE
Schedule events not always working

### ISSUE THREAD

**Issue by erndob** [serverless/serverless#2936]
# This is a (Bug Report)
Bug Report
## Description

For bug reports:
* What went wrong?
Scheduled event not triggering.
* What did you expect should have happened?
Event should trigger no matter how it was defined.
* What was the config you used?
```
    handler: test.test
    events:
      - schedule:
          rate: rate(10 minutes)
```
* What stacktrace or error message from your provider did you see?

* ***Serverless Framework Version you're using***: 1.3.0
* ***Operating System***: Windows 10
* ***Stack Trace***:
* ***Provider Error messages***:
