### ISSUE TITLE
Support for variables that are objects

### ISSUE THREAD

**Issue by mariusmarais** [serverless/serverless#2943]
# This is a Feature Proposal

## Description
Currently `serverless.yml` variables can only be simple strings, but in some cases it would be useful to specify a full object which can be used as the content of the variable.

The main use case is to allow using the CloudFront functions in the yaml template, for instance:
 * in a policy statement, use `Fn::GetAtt`:
```yaml
Statement:
  - Effect: Allow
    Action:
      - logs:PutLogEvents
    Resource:
      Fn::GetAtt: [LogGroupDefinedElsewhere, 'Arn']
  ```
 * passing a DynamoDB ARN to a function as a Lambda variable:
```yaml
function:
  myfn:
    ...
    environment:
      DEPLOY_TABLE: Fn::Join: ['', ['arn:aws:dynamodb:', {Ref: AWS::Region}, ':', {Ref: AWS::AccountId}, ':table/', { Ref: DeploymentsDynamo }]]
```
 * passing outputs exported from a different stack into the current stack:
```yaml
function:
  myfn:
    ...
    environment:
      THE_BUCKET: { Fn::ImportValue: '${self:custom.other_stack_name}-DeploymentS3Bucket' }
```

Other use cases spring to mind, but these are most poignant for us at the moment.

Ideally one would define a variable with the above `Fn::xxx` definitions centrally under `custom`, but this is not currently legal, meaning that they have to be copy & pasted (carefully).

Alternatives:
  * Javascript file includes: Not sufficient, since the JS cannot access the other variables defined in `serverless.yml`
  * Custom plugin:
    * Would require specifying an alternative variable syntax just for the plugin
    * Would still not work (reliably), since there is no single `initialized` Serverless hook that reliably fires for all commands (AFAIK) which can serve as a global configuration injection point.

## Additional Data

* ***Serverless Framework Version you're using***: 1.2.1
* ***Operating System***: OSX 10.12.1
* ***Stack Trace***: None
* ***Provider Error messages***: None
