### ISSUE TITLE
event.queryStringParameters undefined when integration:lambda set

### ISSUE THREAD

**Issue by RobinJayaswal** [serverless/serverless#2958]
# This is a Bug Report

## Description

One of my handlers accesses `event.queryStringParameters`. When I added `integration: lambda` to its http endpoint in `serverless.yml` like so:

```
foo:
    handler: handler.foo
    events:
      - http:
          path: /foo
          method: get
          integration: lambda
```

suddenly `event.queryStringParameters` is undefined, and I have to access them in `event.query`. Though this is a simple solution, it leads to a confusing inconsistency in my code between functions that use lambda integration and ones that do not.
