### ISSUE TITLE
Template format error: Unresolved resource dependencies [*bucket-name*] in the Resources block of the template

### ISSUE THREAD

**Issue by pierskarsenbarg** [serverless/serverless#2976]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? I got the error message  **Template format error: Unresolved resource dependencies [pk-bucket] in the Resources block of the template**
* What did you expect should have happened? An IAM policy should be created that allows access from lambda to S3 bucket
* What was the config you used?

```yaml
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pk-bucket
    myDefaultRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /my/default/path
        RoleName: MyDefaultRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:                
                -  Effect: "Allow"
                   Action:
                     - "s3:PutObject"
                   Resource:
                     Fn::Join:
                       - ""
                       - - "arn:aws:s3:::"
                         - "Ref" : "pk-bucket"
```

* What stacktrace or error message from your provider did you see? See above

## Additional Data

* ***Serverless Framework Version you're using***: 1.4
* ***Operating System***: Windows 10
* ***Stack Trace***:
* ***Provider Error messages***:
