### ISSUE TITLE
Support for Lambda Function DeadLetterConfig (SQS|SNS)

### ISSUE THREAD

**Issue by gmetzker** [serverless/serverless#2982]
# This is a (Bug Report / Feature Proposal)
Feature Proposal 

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

  The AWS Lambda team recently [added support for a DeadLetterConfig](http://docs.aws.amazon.com/lambda/latest/dg/dlq.html) where the lambda can write to a queue or topic after execution fails.  It would be nice to support this in serverless.  Although this is not currently supported through cloudformation perhaps we could define the syntax now and support this by rendering a post deploy `updateFunctionConfiguration` call to set the DeadLetterConfig.  After CloudFormation support is implemented serverless could be updated to use CF directly.

* If there is additional config how would it look

Function definition:
```
functions:
  hello:
    handler: handler.hello
    name: ${self:provider.stage}-lambdaName
    deadLetterConfig: {
       targetArn:  "...arn to SQS or SNS"
    }
...
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by mthenw** [comment]
We need to wait for CF support for DLQ.

**Comment by gmetzker** [comment]
FYI I've created a plugin for this that will work until CF supports `DeadLetterConfig`

https://github.com/gmetzker/serverless-plugin-lambda-dead-letter
https://www.npmjs.com/package/serverless-plugin-lambda-dead-letter

#### DeadLetter Queue
Use the `deadLetter.sqs` to create a new dead letter queue for the function.  


The resulting cloudformation stack will contain an SQS Queue and it's respective QueuePolicy.  

#### Create new dead-letter queue by name
```YAML
# 'functions' in serverless.yml

functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetter:
      sqs:  createUser-dl-queue  # New Queue with this name
```

#### Create new dead-letter queue with properties
```YAML
# 'functions' in serverless.yml

functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetter:
      sqs:      # New Queue with these properties
        queueName: createUser-dl-queue
        delaySeconds: 60
        maximumMessageSize: 2048
        messageRetentionPeriod: 200000
        receiveMessageWaitTimeSeconds: 15
        visibilityTimeout: 300
```

#### DeadLetter Topic

Use the `deadLetter.sns` to create a new dead letter topic for the function.

The resulting cloudformation stack will contain an SQS Topic resource.

```YAML
# 'functions' in serverless.yml

functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetter:
      sns:  createUser-dl-topic
```

**Comment by pmuens** [comment]
Wow. That's really nice @gmetzker thanks for that!

Would be great if this is added to the [plugins repository](https://github.com/serverless/plugins).

Would you mind adding it there? Otherwise I can add it too (don't want to steal the contributions you'll get when you submit the PR 😄)...

**Comment by gmetzker** [comment]
Sure I'll update the list.

**Comment by gmetzker** [comment]
Should I also update the plugin list on the serverless/serverless readme or do you do that periodically with some tool?

**Comment by pmuens** [comment]
We have a script which is run from time to time, so no need for you to do it (but thanks for offering your help!)

**Comment by horike37** [comment]
CF have just supported DLQ :heart:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

**Comment by gmetzker** [comment]
If it's added to serverless is the syntax below reasonable?  Maybe similar to [my plugin](https://github.com/gmetzker/serverless-plugin-lambda-dead-letter)

Pre-existing ARN
```YAML
functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetterConfig:
      targetArn:  {some arn here}
```

#### Create new dead-letter queue by name
```YAML
# 'functions' in serverless.yml

functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetterConfig:
      sqs:  createUser-dl-queue  # New Queue with this name
```

#### Create new dead-letter queue with properties
```YAML
# 'functions' in serverless.yml

functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetterConfig:
      sqs:      # New Queue with these properties
        queueName: createUser-dl-queue
        delaySeconds: 60
        maximumMessageSize: 2048
        messageRetentionPeriod: 200000
        receiveMessageWaitTimeSeconds: 15
        visibilityTimeout: 300
```

#### DeadLetter Topic

Use the `deadLetter.sns` to create a new dead letter topic for the function.

The resulting cloudformation stack will contain an SQS Topic resource.

```YAML
# 'functions' in serverless.yml

functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetterConfig:
      sns:  createUser-dl-topic
```

**Comment by pmuens** [comment]
Thanks for the 🔝 proposal @gmetzker 

Looks good at a first glance. I personally need to dig deeper into DeadLetter support.

Anyone else has some feedback on it?

**Comment by gmetzker** [comment]
Lambda `DeadLetterConfig` out of the box only has a single property `targetArn` that can support either an SQS queue or SNS topic.

In the plugin I was trying to support a few use cases:

1. Developer wants to reference an existing `targetArn` with an queue or topic that exists and was created externally.

2. a) User wants to create a new queue or topic as the DeadLetter (w/simple syntax where they just supply a name)
 
2. b) User wants to create a new queue as the DeadLetter and set specific Properties on that queue (`delaySeconds`, `visibilityTimeout`, etc...)

**Comment by pmuens** [comment]
@gmetzker thanks for the insights. That makes sense!

Really like your proposal after looking into DeadLetter support more 👍

**Comment by pmuens** [comment]
Hey @gmetzker just another quick addition.

We're planning to prefix provider dependent properties like this: `x-provider-`. This way users can immediately see that those properties are not supported by other cloud providers.

Could rename the config parameter to `x-aws-deadLetterConfig` in the implementation?

Here's an example from a `serverless.yml` file for a Azure service: https://github.com/serverless/examples/blob/71ddf26e40c37336d0ff174e7d552d42066aaa49/azure-node-simple-http-endpoint/serverless.yml#L26

There you can see how this prefixing looks like.

Thanks in advance! 👍

**Comment by gmetzker** [comment]
@pmuens Is the plan to make this approach for all provider specific objects/properties?  Just curious if AWS specific events will be renamed as well?

For example:  Under events will `sns` become `aws-sns`?
```
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - aws-sns: dispatch
```
