### ISSUE TITLE
Deployment issue with S3 upload

### ISSUE THREAD

**Issue by diit** [serverless/serverless#2988]
# This is a (Bug Report)

## Having repeated 
`Connection timed out after 120000ms`
 or 
```
Your socket connection to the server was not read from
     or written to within the timeout period. Idle connections
     will be closed.
``` 
errors while running `serverless deploy`.

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: win32
* ***Stack Trace***:
* ***Provider Error messages***: "Your socket connection to the server was not read from
     or written to within the timeout period. Idle connections
     will be closed." / "Connection timed out after 120000ms"

* *** 
```
service: xxx

provider:
  name: aws
  runtime: nodejs4.3

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: xxx
          method: post
          cors: true
          authorizer:
            arn: xxx
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
```
