### ISSUE TITLE
Add KMS key selection to AWS provider

### ISSUE THREAD

**Issue by DonMcNamara** [serverless/serverless#2996]
# This is a Feature Proposal

## Description
Add the ability to select a KMS key in the AWS provider and/or function configuration.

AWS Lambdas now support environment variables and selecting a KMS key used at runtime. The KMS key is used by AWS to encrypt environment variables at rest. Serverless configuration should allow selecting a KMS key.

This would only be a small change to allow full configuration of the KMS key.

For feature proposals:
* Use case: Use a KMS key other than the default lambda KMS key.
* Possible configuration example:
```
provider:
  kmsKeyArn: arn:aws:kms:us-east-1:1234567890:key/76aa38ca-17b7-4c96-9a89-38df27cbeafe

function:
  kmsKeyArn: arn:aws:kms:us-east-1:1234567890:key/76aa38ca-17b7-4c96-9a89-38df27cbeafe
```

Similar or dependent issues:
* #472
* [secrets-serverless-plugin issue](https://github.com/ServerlessInc/serverless-secrets-plugin/issues/1)

## Additional Data

* Cloudformation docs: [Lambda KmsKeyArn](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-kmskeyarn)
