### ISSUE TITLE
Empty environment variables are set as `null` in cloudformation script and fails to deploy

### ISSUE THREAD

**Issue by bytesnz** [serverless/serverless#3007]
# This is a (Bug Report)

## Description
When trying to deploy a configuration with an empty environment variable, the following error is produced:
```
  Serverless Error ---------------------------------------

     [/Resources/DemosLambdaFunction/Type/Environment/Variables/SNS_PORT]
     'null' values are not allowed in templates

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.3.2
     Serverless Version: 1.4.0
```

Expected result is empty environment variables are set to "" and it deploys with no issue

Extract of `serverless.yml` file:
`serverless.yml`
```yaml
provider:
  name: aws
  timeout: 20
  memorySize: 1536
  environment:
    # Storage Environment Vars
    STORAGE_BUCKET: ${file(env.yml):STORAGE_BUCKET}
    SNS_PORT: ${file(env.yml):SNS_PORT}
```

`env.yml`
```yaml
STORAGE_BUCKET: //example.com
SNS_PORT:
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: Ubuntu 16.04
* ***Stack Trace***:
* ***Provider Error messages***:
