### ISSUE TITLE
Unable to import module 'index'

### ISSUE THREAD

**Issue by Puneeth-n** [serverless/serverless#3017]
Hi all,

I am getting this below error on AWS Lambda with `serverless version 1.4.0` and unable to debug the issue.

```
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/index.js:5:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
```

I have a `serverless.yml` with 4 handlers. I use `npm link .. ` to link two modules that are outside the `serverless.yml` directory.

upon performing `sls deploy --noDeploy --stage beta -region eu-west-1` and analyzing the zip file in `.serverless` directory, I can see `sls` copied the `link`ed libraries in `node_modules`

```
frameworkVersion: "=1.4.0"

service: elasticsearch

custom: ${file(../provider.yml)}

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: ${self:custom.provider.cfLogs}
  stage: ${self:custom.provider.stage}

package:
  include:
    - ./node_modules/lambda_slack_notifier/**
    - ./node_modules/factories/**
  exclude:
    - .serverless/**

functions:
  bookingItems:
    name: lambda-elasticsearch-booking_item-${self:provider.stage}
    handler: index.bookingItems

  travelers:
    name: lambda-elasticsearch-traveler-${self:provider.stage}
    handler: index.travelers

  companies:
    name: lambda-elasticsearch-company-${self:provider.stage}
    handler: index.companies

  bookings:
    name: lambda-elasticsearch-booking-${self:provider.stage}
    handler: index.bookings

  offers:
    name: lambda-elasticsearch-offer-${self:provider.stage}
    handler: index.offers
```
