### ISSUE TITLE
AWS Step Functions support

### ISSUE THREAD

**Issue by lielran** [serverless/serverless#3024]
# aws step functions support

Feature proposals:
* the new [aws step function](https://aws.amazon.com/step-functions/) is based on aws lambda and seem like perfect for lambda orchestration(state machine style). 
* serverless integration can be very handy.

**Comment by rowanu** [comment]
How would this work? Would people have to write their own FSM using [AWSSL](https://states-language.net/spec.html)?

**Comment by lielran** [comment]
IMO,since the Json format is very simple(unlike cloudformation),It will be a good idea to write FSM using AWSSL and let serverless handle that for you. 
One of the issues is that you need to provide ARN for your lambdas function. In that case we will need a place holder or a pointer to your function.

**Comment by lielran** [comment]
it's also possible to define a Task("Activity") without ARN that will ping an HTTP endpoint.

**Comment by rowanu** [comment]
Can this issue be closed then?

**Comment by pmuens** [comment]
Not sure if we should put this into core some time (based on @horike37 plugin)...

Any thoughts @eahefnawy @nikgraf @mthenw ?

**Comment by eahefnawy** [comment]
We may add it, but I'm guessing the design won't exactly match @horike37 plugin...mainly for cross-provider compatibility reasons. I feel that the config used with that plugin is too AWS specific.

**Comment by lielran** [comment]
I think it should be in the core since it's the really one way to support flows and keep the function small(and not mini-application).I like the idea that @horike37 plugin support the aws step file. 
also, I'm not sure about multi-providers since it may not be any time soon.

**Comment by williamgueiros** [comment]
@lielran i think @horike37 is correct, i can't found information, how add information on aws step functions, without interface .

Do you saw that information?

**Comment by rowanu** [comment]
https://aws.amazon.com/about-aws/whats-new/2017/02/aws-cloudformation-adds-support-for-aws-step-functions

**Comment by horike37** [comment]
How would this work finally?
If including in the core, I would love to this work.
I think the first step is that we should decide command design and structure of serverless.yml for Step functions.

**Comment by horike37** [comment]
Hey everyone.
I will begin to implement this feature. So I'm considering serverless.yml setting for this as follow and will include the following in 'sls deploy' without adding new commands.
I would like to get your opinion.

```yaml
provider:
  name: aws
  runtime: nodejs4.3

custom: 
  accountId: xxxxxx

functions:
  hellofunc:
    handler: handler.hello

stepFunctions:
  role: arn:aws:iam:::role/InsertYourFavoriteRoleNameHere #Optional, you can chose the existing IAM Role
  stateMachines:
    myStateMachine1:
      events: #Here is events for stepfunctions. You can define http, schedule and cloudwatchEvent.
        - http:
          method: GET
          path: executeMyStateMachine
        - schedule: rate(2 hours)
        - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              state:
                - pending
      definition: #Required. Here is the Amazon States Language definition.
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States: 
          HelloWorld1:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-hello
            End: true
    hellostepfunc2:
      definition:
        StartAt: HelloWorld2
        States: 
          HelloWorld2: 
            Type: Task
            Resource: arn:aws:states:${opt:region}:${self:custom.accountId}:activity:${self:service}-${opt:stage}-myTask
            End: true
  activities: #Here is Task activites
    - myTask
```

**Comment by horike37** [comment]
Additionally,  we should extend `sls invoke` command so that a stepfunction can be invoked.
I consider that add `sls invoke --stepfunction <statemachin name>` option to this.

**Comment by pmuens** [comment]
Thanks for jumping on this @horike37 👍 

Not 100% sure about the syntax yet. But TBH I don't have a better proposal yet.

Is it possible to build this more around the Lamdba functions rather than as a separate kind of resource in the `serverless.yml` file?

Curious what others who've used step functions think how this should look like... /cc @serverless/vip

**Comment by lielran** [comment]
@horike37  don't you think we need some kind of link between ```hellofunc``` and the ```Resource``` section?

**Comment by HyperBrain** [comment]
@pmuens @horike37 This function reference seems a bit too hard-coded for me:
```
          HelloWorld1:
            Type: Task
            Resource: arn:aws:lambda:${opt:region}:${self:custom.accountId}:function:${self:service}-${opt:stage}-hello
            End: true
```
The same for the activity reference. Woudn't the reference be easier by referencing the function via "Ref" or "GetAtt"? Function naming is a integral part of the framework itself (provider.naming module) and having the need to assemble the arns manually would increase the risk of errors.

**Comment by horike37** [comment]
@pmuens 
>Is it possible to build this more around the Lamdba functions rather than as a separate kind of >resource / section in the serverless.yml file?
Does it mean to define stepfunction setting in `functions` section? 
Like this:
```
functions:
  hellofunc:
    handler: handler.hello
    stepfunction: .....
```

@lielran @HyperBrain
Yes, I agree. It would be nice to link it. However, there is one problem. To use `Ref` or `GetAtt` you need to get logicalName of Resource, but there is no way how you get this in `functions` section in serverless.yml.

**Comment by HyperBrain** [comment]
@horike37 For lambda functions you can get the logical id with `provider.naming.getLambdaLogicalId(functionName)`. So, if you would allow:
```
HelloWorld1:
  Type: Task
  Function: hellofunc
  End: true
```
You can easily deduct the resource name with the given function from naming. Internally you can then set `Resource: { Fn::GetAtt: [ 'deref'd function resource', 'Arn' ] }` in the compiled CF template.

In general, I would allow the definition to have multiple ways of linking a function into the step resources. Also manually specifying an Arn parameter that you also copy to Resource.

**Comment by erikerikson** [comment]
@pmuens IMO, breaking the step functions apart (so as to define pieces under function definitions) would be a nightmare.  To reason about a step function you need it collected in a single reviewable chunk.  Additionally, it might prohibit or at least make awkward defining Passed, Fail, Succeed, Type: Activity, and Parallel (others?) state types (where would you attach them).
@horike37 I agree with @pmuens that the formatting needs iteration but need a real keyboard to give feedback properly.  I also agree with @HyperBrain about allowing the use of the raw function name.  I'd suggest also allowing full ARN, or objects such as Fn::GetAtt and Fn:: ImportValue.  We should probably have a reusable "functionReference" module to make this handling easier and more consistent.  Not that you're obligated in this context, it just occurrs to me that this has shown up multiple times in multiple places so the framework would win if someone did this.

**Comment by erikerikson** [comment]
Additionally, I strongly support the integration of StepFunction support into the existing deploy command.  Same with regard to the invoke command but with -sf as an additional short version of the flag.

**Comment by HyperBrain** [comment]
@erikerikson Indeed. #3212 is the proposal for that. It should provide a universal Arn paser including the detection of refs, getatts and - additionally - the function name case should be added.

**Comment by HyperBrain** [comment]
@erikerikson Indeed. #3212 is the proposal for that. It should provide a universal Arn paser including the detection of refs, getatts and - additionally - the function name case should be added.

**Comment by erikerikson** [comment]
Thanks @HyperBrain

**Comment by erikerikson** [comment]
@horike37 some feedback and then a modified example desired target follow.

1) the role is an attribute belonging to a specific step function and should probably not be declared at the top level, implying it should be used for all step functions.  As such, moved it under machine.
2) I think from a user perspective, the user population will expect event declarations to use the same declaration syntax and offer the same features as the corresponding Lambda event declarations.  As such, the same code should probably be used for processing both.  Some abstraction may be necessary relative to the current state.
3) the role for a SF should allow multiple value types.
4) the value of Resource under a Task should allow multiple value types.

```
stepFunctions:
  activities:
    - myActivity0
    - myActivity1
  stateMachines:
    myStateMachine0:
      role: [ARN | Fn::GetAtt | Fn::ImportValue | etc.]
      events:
        - http: # I would expect this to mirror the corresponding http declaration for lambdas, including support for the compacted form (`- http: GET executeMyStateMachine`), etc. and even use the same codebase for processing.  See https://serverless.com/framework/docs/providers/aws/events/apigateway/ for examples
        - schedule: # should also mirror declaration capability of Lambda
        - cloudwatch: # should also mirror declaration capability of Lambda
      definition:
        Comment: "A comment..."
        StartAt: HelloWorld
        States: 
          HelloWorld:
            Type: Task
            Resource: [lambda name | activity name | lambda ARN | activity ARN | Fn::GetAtt (lambda) | Fn::Ref (activity) | Fn::ImportValue]
            End: true
    myStateMachine1: [...]
```

Thank you!
