### ISSUE TITLE
Strange YAML Required by Stream Events

### ISSUE THREAD

**Issue by hakutsuru** [serverless/serverless#3029]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Function event config was ignored.

* What did you expect should have happened?

EventSourceMapping should have been created.

* What was the config you used?

Failing config:
```
functions:
  epxFunction:
    handler: handler.epxFunction
    name: ${self:service}-${self:provider.stage}
    description: ${self:service} - read from kinesis and check logs
    memorySize: 1024
    timeout: 300
    events:
      - stream:
        arn: arn:aws:kinesis:us-east-1:${self:custom.${self:provider.stage}.accountId}:stream/prod-copy-diagnostic-stream
        batchSize: 10
        startingPosition: TRIM_HORIZON
```

Forgive me, but I read the documentation, checked all the issues and validated the yaml. For this to fail is very confusing.

Working config:
```
# yaml indentation of two spaces expected, but somehow
# items under stream must be indended four spaces
# or "EventSourceMapping" will not be created
functions:
  epxFunction:
    handler: handler.epxFunction
    name: ${self:service}-${self:provider.stage}
    description: ${self:service} - read from kinesis and check logs
    memorySize: 1024
    timeout: 300
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:${self:custom.${self:provider.stage}.accountId}:stream/prod-copy-diagnostic-stream
          batchSize: 10
          startingPosition: TRIM_HORIZON
```

Also, yaml folded style prevents variable interpolation, so there appears no way to implement a "block style" config (if there was to be a feature, it would enable configs to use sane line continuation).

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
$ serverless --version
1.4.0
* ***Operating System***:
Ubuntu Trusty
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @hakutsuru thanks for reporting. Yes, I agree the YAML syntax is a little bit odd.

I faced the exact same problem when I worked on the `http` event integration and wanted to do something like:

```yml
events:
  - http:
    path: hello
    method: GET
```

which failed. I had to do:

```yml
events:
  - http:
      path: hello
      method: GET
```

so that it works.

Unfortunately those quirks are YAML based so we cannot do something about it yet. However there are plans to support JSON for configurations as well.

I'll close this for now as we won't be able to fix this anytime soon.

**Comment by hakutsuru** [comment]
Ah, right. I do see clear examples in the docs. Just confusing, because the two-space indenting appears to be valid yaml and works for ansible, etc. Thanks.

**Comment by pmuens** [comment]
Yes. The problem is that both syntaxes are correct, but represent something different.

```yml
events:
  - http:
    path: hello
    method: GET
```

translates to this

```json
{
  "events": [
    {
      "http": null,
      "path": "hello",
      "method": "GET"
    }
  ]
}
```

whereas

```yml
events:
  - http:
      path: hello
      method: GET
```

translates to this

```json
{
  "events": [
    {
      "http": {
        "path": "hello",
        "method": "GET"
      }
    }
  ]
}
```
