### ISSUE TITLE
S3 event with Ref for bucket name causes error 

### ISSUE THREAD

**Issue by bschoenfeld** [serverless/serverless#3034]
# This is a Bug Report

## Description

* What went wrong?

Tried creating an S3 event on a function, using a `Ref` object instead of a string for the bucket name. The object is treated like a string. The output contains a resource with logical name `S3BucketObjectObject` and `BucketName` `[object Object]`.

* What did you expect should have happened?

Ideally, the Ref to the resource should be recognized and the new configuration should be pushed onto that object. This behavior is supported if the bucket has already been created on a lambda function, but not if the bucket was created in the resource section.

While this is not supported, an error should be thrown if the bucket name is not a string.

* What was the config you used?

```
service: test-buckets

provider:
  name: aws
  runtime: python2.7

resources:
  Resources:
    MyTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${opt:stage}-my-topic
    
    BarBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${opt:stage}-bar
        NotificationConfiguration:
          TopicConfigurations:
            - Event: "s3:ObjectCreated:*"
              Topic:
                Ref: MyTopic

functions:
  foo:
    handler: handler.foo
    events:
      - s3:
          bucket:
            Ref: BarBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: test/
```

* What stacktrace or error message from your provider did you see?

```
 An error occurred while provisioning your stack: S3BucketObjectObject
     - Bucket name should not contain '['.
```

Similar or dependent issues:
* #2107

## Additional Data

* ***Serverless Framework Version you're using***:
1.4.0
* ***Operating System***:
macOS 10.12.1
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by bschoenfeld** [comment]
Here's the generated stack update:

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Path": "/"
      }
    },
    "IamPolicyLambdaExecution": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "dev-test-buckets-lambda",
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream"
              ],
              "Resource": "arn:aws:logs:us-east-1:*:*"
            },
            {
              "Effect": "Allow",
              "Action": [
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:us-east-1:*:*"
            }
          ]
        },
        "Roles": [
          {
            "Ref": "IamRoleLambdaExecution"
          }
        ]
      }
    },
    "FooLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/test-buckets/dev/1483117107553-2016-12-30T16:58:27.553Z/test-buckets.zip"
        },
        "FunctionName": "test-buckets-dev-foo",
        "Handler": "handler.foo",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "python2.7",
        "Timeout": 6
      }
    },
    "S3BucketObjectObject": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "[object Object]",
        "NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Event": "s3:ObjectCreated:*",
              "Function": {
                "Fn::GetAtt": [
                  "FooLambdaFunction",
                  "Arn"
                ]
              },
              "Filter": {
                "S3Key": {
                  "Rules": [
                    {
                      "Name": "prefix",
                      "Value": "test/"
                    }
                  ]
                }
              }
            }
          ]
        }
      }
    },
    "FooLambdaPermissionS3": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "FooLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": "s3.amazonaws.com"
      }
    },
    "MyTopic": {
      "Type": "AWS::SNS::Topic",
      "Properties": {
        "TopicName": "dev-my-topic"
      }
    },
    "BarBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "dev-bar",
        "NotificationConfiguration": {
          "TopicConfigurations": [
            {
              "Event": "s3:ObjectCreated:*",
              "Topic": {
                "Ref": "MyTopic"
              }
            }
          ]
        }
      }
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "FooLambdaFunctionArn": {
      "Description": "Lambda function info",
      "Value": {
        "Fn::GetAtt": [
          "FooLambdaFunction",
          "Arn"
        ]
      }
    }
  }
```

**Comment by swarajgiri** [comment]
I am facing the same issue. Is the fix going to be in v1.10?

**Comment by christophgysin** [comment]
> Is the fix going to be in v1.10?

1.10 has been released yesterday:
https://github.com/serverless/serverless/releases/tag/v1.10.0
https://serverless.com/blog/serverless-v1.10.0

**Comment by nielsgl** [comment]
It doesn't seem to be fixed in v1.10.1, I'm facing a similar issue

```bash
Serverless: Packaging service...

  Type Error ---------------------------------------------

     name.replace is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

and in my `serverless.yml` I have:

```yaml
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::*

functions:
  s3eventlogger:
    handler: src/s3logger.logger
    events:
      - s3:
          bucket:
            Ref: applesbucket
          event: s3:ObjectCreated:*

resources:
  Resources:
    applesbucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.APPLES_BUCKET_NAME}
```

**Comment by mrowles** [comment]
Any love / workarounds?

**Comment by mvayngrib** [comment]
being able to refer to a bucket by ref would be great

**Comment by Hafiz974** [comment]
Was there a fix for this yet?

**Comment by jraede** [comment]
Has there been a fix for this yet? Or another way to use bucket resource refs in the lambda trigger?

**Comment by MustSeeMelons** [comment]
```
  preSignUp:
    handler: src/user/userService.preSignUp
    events:
      - cognitoUserPool:
          pool:
            - Ref: UserPool
          trigger: PreSignUp
```

The same issue, but I'm trying to reference a Cognito pool resource.
