### ISSUE TITLE
serverless config credentials requires --stage flag with existing repo on new machine

### ISSUE THREAD

**Issue by alexbielen** [serverless/serverless#3049]
# This is a Bug Report 

## Description
I am working with an existing serverless repo on a new machine. In the `serverless.yml` the stage variable is set using the `${opt:stage}` variable, i.e.
```
provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: us-east-1
```
Because of this 
`sls config credentials --provider aws --key <key> --secret <secret>` fails when the --stage flag is not used. 

For bug reports:
* What went wrong? 
`config credentials` failed 
* What did you expect should have happened?
I expected config credentials to set up credentials; it eventually worked once passed the `--stage` flag. It could just be that this behavior is lacking documentation. 
* What was the config you used?
```
service: restapi
provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: us-east-1
functions:
  hello:
    handler: handler.hello
    events: 
        - http:
              path: hello/world
              method: get
```
* What stacktrace or error message from your provider did you see?
```
  Serverless Error ---------------------------------------

     Trying to populate non string value into a string for
     variable ${opt:stage}. Please make sure the value of
     the property is a string.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.0.0
     Serverless Version: 1.4.0
```
