### ISSUE TITLE
Cannot use " in body for scheduling

### ISSUE THREAD

**Issue by BenRomberg** [serverless/serverless#3069]
# This is a Bug Report

## Description

With the following schedule configuration:
```
      - schedule:
          rate: rate(1 minute)
          enabled: true
          input:
            path: /switch
            httpMethod: POST
            headers:
              Content-Type: application/json
            queryStringParameters: {}
            body: '{ "functionId": "..." }'
```
I get the following exception:
```
SyntaxError: Unexpected token f
    at Object.parse (native)
    at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/schedule/index.js:123:41
    at Array.forEach (native)
    at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/schedule/index.js:21:28
```

Looking at the code, the problem is with escaping the input in `lib/plugins/aws/deploy/compile/events/schedule/index.js` in the variable `scheduleTemplate`. The quotes in the body get transformed to `\"` in `Input`, and then to `\\"` in `scheduleTemplate`. Note the missing backslash - only the original backslack gets escaped, not the quotes.

I was able to hack a quick fix together and it works (not suggesting as a fix, just to illustrate that this would fix it). The original `scheduleTemplate` was renamed to `scheduleTemplate2` before:
```
const scheduleTemplate = scheduleTemplate2.replace(/\\\\"/g, '\\\\\\"');
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: Xubuntu 16.10
* ***Stack Trace***:
* ***Provider Error messages***:
