### ISSUE TITLE
Serverless does not see custom environment variables

### ISSUE THREAD

**Issue by ilyanoskov** [serverless/serverless#3071]
# This is a Bug Report

## Description

I am using dotenv module, together with a serverless plugin (serverless-plugin-write-env-vars )

For bug reports:
* What went wrong?
I have specified the variables I need in my serverless.yml file, they do get created in the .env but they are not seen.

Here is a part of my serverless.yml:

```
  followup:
    handler: handler.followup
    memory: 1024
    timeout: 300
  onExpired:
    handler: handler.onExpired
    memory: 1024
    timeout: 300

resources:
  Resources:
    $ref: ./cloudFormation.json

custom:
  defaultRegion: us-east-1
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage}
  writeEnvVars:
    SERVICE_NAME: ${self:service}
    STAGE: ${self:custom.stage}
    REGION: ${self:custom.region}
    REQUESTS_TABLE: ${opt:stage}-requests
    ACCOUNTS_TABLE: ${opt:stage}-accounts

plugins:
  - serverless-plugin-write-env-vars
```

* What did you expect should have happened?
I expect that when I did console.log(process.env) I would see the variables there (they are not there)
* What was the config you used?
* What stacktrace or error message from your provider did you see?

```
{
    "errorMessage": "Missing required key 'TableName' in params",
    "errorType": "MissingRequiredParameter",
    "stackTrace": [
        "ParamValidator.fail (/var/task/node_modules/request-lifecycle/node_modules/request/node_modules/aws-sdk/lib/param_validator.js:50:37)",
        "ParamValidator.validateStructure (/var/task/node_modules/request-lifecycle/node_modules/request/node_modules/aws-sdk/lib/param_validator.js:61:14)",
        "ParamValidator.validateMember (/var/task/node_modules/request-lifecycle/node_modules/request/node_modules/aws-sdk/lib/param_validator.js:88:21)",
        "ParamValidator.validate (/var/task/node_modules/request-lifecycle/node_modules/request/node_modules/aws-sdk/lib/param_validator.js:34:10)",
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.5
* ***Operating System***: Mac OSX Sierra
