### ISSUE TITLE
Multiple Path Vars for same function

### ISSUE THREAD

**Issue by marckaraujo** [serverless/serverless#3075]
# This is a (Bug Report)

## Description

Serverless dont allow you to create multiple path vars for the same function. If you create another function with different handler, it works.

```
profilePlayer:
            description: "Profile"
            handler: api/profile/player/handler.default
            memorySize: 256
            timeout: 18
            events:
              - http:
                  path: profile/player/{id}
                  method: GET
                  cors: true
              - http:
                  path: profile/player/{game}
                  method: POST
                  cors: true 
```

For bug reports:
* What went wrong?
```
 Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ApiGatewayResourceProfilePlayerGameVar
     - A sibling ({id}) of this resource already has a variable
     path part -- only one is allowed.
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.0
* ***Operating System***: MacOS El Capitan
* ***Stack Trace***:
* ***Provider Error messages***:
