### ISSUE TITLE
VPC Configuration Role Docs

### ISSUE THREAD

**Issue by marckaraujo** [serverless/serverless#3076]
# This is a (Feature Proposal)

## Description

This role configuration should be described here:
https://serverless.com/framework/docs/providers/aws/guide/functions/#vpc-configuration
```
iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
      Resource: '*'
    - Effect: Allow
      Action:
        - ec2:DeleteNetworkInterface
        - ec2:DescribeNetworkInterfaces
      Resource: 'arn:aws:ec2:${self:provider.region}:*:network-interface/*'
```

Also should add all securityGroupIds to Inbounds Rules, like below:
![screenshot 2017-01-09 23 02 33](https://cloud.githubusercontent.com/assets/3084181/21789993/710de602-d6c0-11e6-9032-0d519ee53fe7.png)
