### ISSUE TITLE
Error on `sls invoke`: Unexpected token ...

### ISSUE THREAD

**Issue by d3ming** [serverless/serverless#3087]
# This is a bug report

* What went wrong?
I get the following error when trying to invoke a simple `health` function:
```
$ SLS_DEBUG=* sls invoke -f health
{
    "errorMessage": "Unexpected token ...",
    "errorType": "SyntaxError",
    "stackTrace": [
        "Object.Module._extensions..js (module.js:416:10)",
        "Module.load (module.js:343:32)",
        "Function.Module._load (module.js:300:12)",
        "Module.require (module.js:353:17)",
        "require (internal/module.js:12:17)",
        "Object.<anonymous> (/var/task/handler.js:160:19)",
        "__webpack_require__ (/var/task/handler.js:20:30)",
        "Object.<anonymous> (/var/task/handler.js:120:27)"
    ]
}

  Error --------------------------------------------------

     Invoked function failed

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Invoked function failed
    at AwsInvoke.log (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:122:31)
    at AwsInvoke.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Here's my `serverless.yml`:
```
service: advision-api

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev

custom:
  webpackIncludeModules: true

functions:
  health:
    handler: handler.health
    events:
      - http:
          path: api/health
          method: get
          cors: true

  capture:
    handler: handler.capture
    events:
      - http:
          path: api/capture
          method: post
          cors: true
```

Here's the `handler.js`:
```
import * as webcapture from './lib/webcapture';

if (!global._babelPolyfill) {
  require('babel-polyfill');
}

export const health = (event, context, cb) =>
  cb(null, {
    message: 'AdSense is alive and well!',
  });

export const capture = (event, context, cb) => {
  console.log(`event data: ${JSON.stringify(event)}`);

  if (!event || !event.url) {
    console.error('No url given!');
    cb(new Error('No URL specified!'));
    return;
  }

  const url = event.url;
  const driver = webcapture.getDriver(
    webcapture.BROWSER_CONFIGS.Chrome);
    webcapture.capture(driver, url)
    .then(() => {
      driver.getTitle().then((title) => {
        driver.quit();
        return cb(null, {
          message: `webcapture got title: ${title}!`,
          event,
        });
      });
    })
    .catch(e => cb(e));
};
```

I'm using the `serverless-webpack` plugin and when I try to run things locally with `serverless webpack invoke -f health`, things work as expected:

```
$ sls webpack invoke -f health
Serverless: Bundling with Webpack...
Time: 510ms
     Asset     Size  Chunks             Chunk Names
handler.js  4.69 kB       0  [emitted]  main
Serverless: Run function health...
{ message: 'AdSense is alive and well!' }
```

So I'm thinking it must be some configuration issue when trying to get this to work on Lambda.  Please help, the error message doesn't seem to point at anything in my code.
