### ISSUE TITLE
Multiple claims for authorizer break body mapping template

### ISSUE THREAD

**Issue by pisaacs** [serverless/serverless#3088]
# This is a Bug Report

## Description
Setting multiple claims for an authorizer breaks the body mapping template. 

For bug reports:
* What went wrong?
Received the following error from API Gateway: `{"message": "Could not parse request body into json: Unexpected character (\',\' (code 44)): was expecting double-quote to start field name\n at...`

* What did you expect should have happened?
Body mapping template to correctly parse claim fields. 
* What was the config you used?
The below:
``` yaml
...
    events:
      - http:
          path: person
          method: post
          cors: true
          integration: lambda
          authorizer:
            arn: ${self:custom.apiGatewayUserPoolAuthorization}
            claims:
              - email
              - name
....
```
* What stacktrace or error message from your provider did you see?
Received the following from API gateway: `{"message": "Could not parse request body into json: Unexpected character (\',\' (code 44)): was expecting double-quote to start field name\n at...`

## Additional Data

With two claims, the body mapping template for `application/x-www-form-urlencoded` gets configured as the below. **Two commas appear between the fields**. 

```json
.....   
 "cognitoPoolClaims" : {
       "email": "$context.authorizer.claims.email",,"name": "$context.authorizer.claims.name",
       "sub": "$context.authorizer.claims.sub"
    },
.....
```

* ***Serverless Framework Version you're using***: 1.5.0
* ***Operating System***: darwin
