### ISSUE TITLE
batchSize for dynamoDB streams

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#3090]
# This is a Bug Report / Feature Proposal

## Description

if I set up dynamoDB stream like so:

```
functions:
  cloudsearchve:
    handler: handler.cloudsearchve
    events:
      - stream: arn:aws:dynamodb:us-east-1:12345324323:table/graphql-videos-dev/stream/2016-08-11T17:16:12.691

```

then it will set up dynamoDB trigger on the aws console with the batch size of 10, but it will not trigger the lambda :(.

However, if I setup the same stream like so:

```
functions:
  cloudsearchve:
    handler: handler.cloudsearchve
    events:
      - stream: 
          arn: arn:aws:dynamodb:us-east-1:12345324323:table/graphql-videos-dev/stream/2016-08-11T17:16:12.691
          batchSize: 100
          startingPosition: LATEST
          enabled: true
```

then, in aws console it sets it up like so:

![image](https://cloud.githubusercontent.com/assets/3421858/21897635/20f73f32-d8e2-11e6-9027-068d59ed0cbe.png)

and

![image](https://cloud.githubusercontent.com/assets/3421858/21897658/3302ff7c-d8e2-11e6-8671-59589d8c2fae.png)

Even though everything is correctly set up on aws (see above), that trigger just doesn't invoke `cloudsearchve` lambda, no matter what.

Now, I understand that cloudsearch lambda will be triggered every 

        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

making `batchSize` irrelevant, but  what about `BatchWrite`? Is it even possible (should it be?) to change `batchSize` for dynamoDB streams? Or only for kinesis streams?

And if it isn't possible, why is it being set to 10 ?

Also, why everything is being set up correctly on aws console and then not being triggered? If it's not possible to change default batchSize for dynamoDB streams, `serverless` shouldn't even let it deploy, me thinks? @pmuens 

Just before you ask, yes the stream is enabled:

![image](https://cloud.githubusercontent.com/assets/3421858/21897846/ad34d6ee-d8e2-11e6-816b-43574fdfb9e8.png)

Similar or dependent issues:
* N/A

## Additional Data

* ***Serverless Framework Version you're using***:
`1.5`
* ***Operating System***:
![image](https://cloud.githubusercontent.com/assets/3421858/21897374/50283280-d8e1-11e6-8930-0fd7757a3952.png)

* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A

**Comment by codepreneur** [comment]
UPDATE: it doesn't even work when I do it like its described in documentation:

```
functions:
  cloudsearchve:
    handler: handler.cloudsearchve
    events:
      - stream: arn:aws:dynamodb:us-east-1:3243565523:table/graphql-videos-dev/stream/2016-08-11T17:16:12.691

```

**Comment by codepreneur** [comment]
I got a new message (no changes since I posted this issue):

![image](https://cloud.githubusercontent.com/assets/3421858/21931115/8e0bccb4-d991-11e6-9652-f6e74c8ad179.png)

and

![image](https://cloud.githubusercontent.com/assets/3421858/21931143/b0c36654-d991-11e6-9684-86bdcf9b31cf.png)

**Comment by pmuens** [comment]
Hey @codepreneur I tried to reproduce this on my machine which unfortunately wasn't successful.

I created a DynamoDB table called `test` and enabled stream support for it. The `View type` is `New and old images`.

I then deployed the following service:

```yml
service: service

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true
  #region: ap-southeast-2
  #stage: prod

functions:
  hello:
    handler: handler.hello
    events:
      - stream: arn:aws:dynamodb:us-east-1:XXXXX:table/test/stream/2017-01-14T22:25:06.810
```

And if I insert a new record in the table my lambda gets triggered.

Could you provide mir information about your service setup and maybe even the `serverless.yml` you're using?!

Thanks in advance!

**Comment by codepreneur** [comment]
Managed to get it working, but the `batchSize` is still being ignored. Closing the issue.

**Comment by pmuens** [comment]
@codepreneur thanks for the response. Could you maybe quickly revisit what you've changed so that you got it working?

**Comment by codepreneur** [comment]
@pmuens the problem was that I started with kinesis example from documentation and just replaced `arn` with dynamoDB stream and when that didn't work I replaced that with dynamoDB documentation example just with `arn`, which didn't work either. But when I removed the service entirely (`env SLS_DEBUG=true sls remove`) and redeployed with dynamoDB example with just `arn` it worked (If something doesn't work the first thing you do is turn it off and on :D)

I just prefer the UX/UI with kinesis example with `enabled` flag, because that is much easier to turn on and off (just like with scheduled events) than removing `arn` and then trying to scavenge github commit logs to put it back on when I want it turned on again.

Also, I do have a question for you: if you do a `batchWrite`and have dynamoDB stream enabled, it would just ignore `batchSize` anyway and just add them to `cloudsearch` 1 by 1 even though you are giving say 100 at a time ?

**Comment by pmuens** [comment]
Hey @codepreneur thanks for getting back! Glad to hear that the issue was resolved...

Yes, I can feel your pain migrating things from version to version. You should be able to use the `enabled` flag with both, Kinesis and DynamoDB:

```yml
functions:
  preprocess:
    handler: handler.preprocess
    events:
      - stream:
          arn: arn:aws:kinesis:region:XXXXXX:stream/foo # this can be a Kinesis or DynamoDB arn
          enabled: false
```

Regarding the `batchSize`: I just created a service from scratch and can configure the `batchSize`...

Here's the `serverless.yml` I used:

```yml
service: service

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: hello
          integration: LAMBDA
      - sns: my-topic
  goodbye:
    handler: handler.goodbye
    events:
      - http: GET goodbye
      - s3: some.serverless.example.service.bucket
      - stream:
          arn: arn:aws:dynamodb:us-east-1:XXXX:table/test/stream/2017-01-20T08:43:46.636
          batchSize: 100
          enabled: false

```

I can see the `batchSize` set to `100` if I look under `Triggers` in the Lambda function console...
