### ISSUE TITLE
Changing route specificity results in errors

### ISSUE THREAD

**Issue by jeff3yan** [serverless/serverless#3092]
I have realized that whenever route specificity changes, this results in a number of 500 errors.

The simplest example of this is something like starting off with a single endpoint:
GET `/items/users/:id`

After this endpoint has been deployed, the route configuration is changed to:
GET `/items/:type/:id`

If either of these configurations is deployed from scratch, there are no issues. However, only when changing from one to the other causes the request to return a 500 error with a JSON response:
`{"message": "Internal server error"}`
A header from cloudfront is also present on the response:
`X-Cache:Error from cloudfront`

The initial `serverless.yml` configuration looks like:
```
functions:
  items:
    handler: /items.handler
    events:
      - http:
          path: /items/users/{id}
          method: get
```

The modification to this endpoint is:
```
functions:
  items:
    handler: /items.handler
    events:
      - http:
          path: /items/{type}/{id}
          method: get
```
