### ISSUE TITLE
'pathmapping' for custom urls does not allow for modern TLD's ('.xyz')

### ISSUE THREAD

**Issue by mrowles** [serverless/serverless#3098]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
I tried to deploy our lambda's and use a custom domain name but '.xyz' doesn't seem to be recognised (even though we are using it in AWS) and stops the deploy. 'domain.xyz' gets halted whereas if I change it to 'domain.com' it does not get halted or error out

* What did you expect should have happened?
For our deployment to work and for us to be able to hit 'domain.xyz/api/endpoint'.

* What was the config you used?

```
esources:
  Resources:
    pathmapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        BasePath: 'api'
        DomainName: 'domain.xyz'
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: ${self:provider.stage}
```

* What stacktrace or error message from your provider did you see?

Error message (full stack trace further down):
```
An error occurred while provisioning your stack: pathmapping - Invalid domain name identifier specified.
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

This could be a cloud formation issue but just want to see if anyone else knows has experienced this before.

* If there is additional config how would it look

Unsure

Similar or dependent issues:

Unsure

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.0

* ***Operating System***: OSX 10.12.2

* ***Stack Trace***:
```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (24.06 KB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: pathmapping
     - Invalid domain name identifier specified.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.0.0
     Serverless Version: 1.5.0
```

* ***Provider Error messages***:

**Comment by mrowles** [comment]
Any love?

**Comment by pmuens** [comment]
Thanks for getting back @mrowles this seems to be a problem on AWS end since we're simply merging the resources (the `Type: AWS::ApiGateway::BasePathMapping` in your case) into the CloudFormation template and deploy everything.

Have you looked into the AWS forums / filed an issue there?

**Comment by mrowles** [comment]
@pmuens Cheers for the reply! I'm going to attempt to migrate the domain ownership to AWS and attempt again, perhaps that is the issue. Then I'll raise it with AWS if this doesn't prevail...will keep this issue updated :)

**Comment by pmuens** [comment]
Thanks you very much @mrowles 👍 That sounds like a good plan!

**Comment by mrowles** [comment]
@pmuens I've raised this in the API Gateway forums, no love yet but still running up that hill holding out for hope! https://forums.aws.amazon.com/message.jspa?messageID=769627#769627

**Comment by pmuens** [comment]
Thanks @mrowles 👍

**Comment by pmuens** [comment]
Closing this for now since it's something on AWS end.

Feel free to continue the discussion and also please provide some information if you know something new!

**Comment by mrowles** [comment]
It appears that this issue is due to me not adding the custom domain in API Gateway - with AWS' new integration between API Gateway and ACM (https://aws.amazon.com/about-aws/whats-new/2017/03/amazon-api-gateway-integrates-with-aws-certificate-manager-acm/) maybe Serverless could automate this somewhere.

**Comment by pmuens** [comment]
Thanks for the response @mrowles 👍 Well look into API Gateway in combination with ACM.

**Comment by j0k3r** [comment]
Hello guys,

Just to let you know we have successfully integrated a domain and its certificate (which was imported manually in the aws console) using:

```yaml
        CustomDomainName:
            Type: AWS::ApiGateway::DomainName
            Properties:
                CertificateArn: arn:aws:acm:us-east-1:XXXXXX:certificate/XXXXXX
                DomainName: 'api.domain.fr'

        CustomDomainMapping:
            Type: AWS::ApiGateway::BasePathMapping
            Properties:
                BasePath: ''
                DomainName:
                    Ref: CustomDomainName
                RestApiId:
                    Ref: ApiGatewayRestApi
                Stage: "${opt:stage}"
            DependsOn: ApiGatewayRestApi
```
