### ISSUE TITLE
Cannot read property 'path' of null

### ISSUE THREAD

**Issue by cdichiara** [serverless/serverless#3099]
# This is a Bug Report

## Description
I am converting a large v0.5.6 configuration to v1.x, am starting the first deployments of the service. After a few syntax errors that I was walked through by your *much* improved error messages, I got this:

```
Serverless: Packaging service...

  Type Error ---------------------------------------------

     Cannot read property 'path' of null

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'path' of null
    at AwsCompileApigEvents.getHttpPath (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:144:20)
    at _.forEach (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:46:28)
    at arrayEach (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:9344:14)
    at _.forEach (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:42:9)
    at C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:4970:15
    at baseForOwn (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:3020:24)
    at C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:4939:18
    at Function.forEach (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\lodash\lodash.js:9344:14)
    at AwsCompileApigEvents.validate (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\lib\validate.js:41:7)
    at deploy:compileEvents (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\compile\events\apiGateway\index.js:42:31)
    at BbPromise.reduce (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:160:50)
    at tryCatcher (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:157:18)
    at Object.gotAccum (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\reduce.js:144:25)
    at Object.tryCatcher (C:\Users\Carmine DiChiara\AppData\Roaming\npm\node_modules\serverless\node_modules\bluebird\js\release\util.js:16:23)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.9.2
     Serverless Version: 1.5.0
```

Here's my large serverless.yml, still probably with bunches of bugs:
```
# Serverless configuration file
service: irh

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

plugins:
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs4.3
  memorysize: 1536 # can be overwritten on a per-function basis
  timeout: 9 # can be overwritten on a per-function basis
  stage: beta # default stage, can be overridden with serverless deploy -s xxx
  region: us-east-1 # default region, can be overridden with serverless deploy -r xxx
  role: ${self:service}LambdaRole
  environment:
    AwsRegion: ${opt:region, self:provider.region}
    CognitoDeveloperName: cognito.irewardhealth
    UserDbEmailIndex: Users-email
    DeviceDbUserIndex: Devices-userId
    SponsorDbNameIndex: Sponsor-name
    SponsorshipDbNameIndex: Sponsorships-fullNameDob
    CodeDir: lib/
    EventTemplateDir: event_templates/
    RewardFilterDir: reward_filters/
    PointAdjust: adjust
    PointReward: reward
    PointRedeem: redeem
    EventPoints: point
    EventActivity: activity
    EventDietary: dietary
    EventWeight: weight
    EventMealBreakfast: breakfast
    EventMealLunch: lunch
    EventMealDinner: dinner
    EventMealSnack: snack
    WeightSI: kg
    WeightUS: lb
    CognitoIdentityPool: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.CognitoIdentityPool}
    DwollaKey: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.DwollaKey}
    IosSnsKey: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.IosSnsKey}
    EveryoneSnstopic: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.EveryoneSnsTopic}
    IosSnsPlatform: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.IosSnsPlatform}
    AndroidSnsPlatform: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.AndroidSnsPlatform}
    Financials: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.Financials}
    Languages: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.Languages}
    Regions: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.Regions}
    DefaultCurrency: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.DefaultCurrency}
    DefaultFinancial: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.DefaultFinancial}
    DefaultLanguage: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.DefaultLanguage}
    DefaultRegion: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.DefaultRegion}
    DefaultUnits: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.DefaultUnits}
    ActivitiesDb: ${self:custom.${opt:region, self:provider.region}.${opt:stage, self:provider.stage}.ActivitiesDb}
    UsersDb: ${self:resources.Outputs.UsersDb}
    EventsDb: ${self:resources.Outputs.EventsDb}
    SponsorsDb: ${self:resources.Outputs.SponsorsDb}
    SponsorshipsDb: ${self:resources.Outputs.SponsorshipsDb}
    DevicesDb: ${self:resources.Outputs.DevicesDb}
    FeedbackDb: ${self:resources.Outputs.FeedbackDb}
    EveryoneSnsTopic: ${self:resources.Outputs.EveryoneSnsTopic}
#    ImageBucket: ${self:resources.Outputs.ImageBucket}
# DwollaDb is unique in that it is shared by all stages.
    DwollaDb: ${file(./resources/serverless.yml):resources.DwollaDb.Properties.TableName}
functions:
  clientApi:
    handler: handlers/clientApi.handler
    description: REST API, server interface to client applications
    events:
      - http:
        path: users
        method: post
        cors: true
        documentation:
          requestModels:
            application/json: userCreateRequest
          methodResponses:
            - statusCode: 200
              responseModels:
                application/json: userCreateResponse
            - statusCode: 400
              responseModels:
                application/json: userCreateResponse
            - statusCode: 500
              responseModels:
                application/json: userCreateResponse
```
(Truncated after the issue was solved - it was way too long)

For bug reports:
* What went wrong?
More of an internal error message from `sls deploy`

* What did you expect should have happened?
An error message that was actionable by me.

* What was the config you used?
See above

* What stacktrace or error message from your provider did you see?
See above - SLS_DEBUG environment variable was set to true.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345
Unknown

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
I believe that is all listed above - Windows 10.

**Comment by cdichiara** [comment]
Ah, I found one error ... the last http event configuration didn't change `path` to `configuration`, it still says `activities/search/{query}` ... but after fixing it the problem still remains...

**Comment by laardee** [comment]
@cdichiara, hi, serverless framework uses lambda-proxy integration in api gateway endpoints by default, so I think you need to add `integration: lambda` to your endpoints.
Like this
```
    - http:
        path: activities/search/{query}
        method: get
        cors: true
        integration: lambda
        documentation:
          requestModels:
            application/json: emptyRequest
          methodResponses:
            - statusCode: 200
              responseModels:
                application/json: activityGetResponse
            - statusCode: 400
              responseModels:
                application/json: activityGetResponse
            - statusCode: 500
              responseModels:
                application/json: activityGetResponse
```

here is the documentation https://serverless.com/framework/docs/providers/aws/events/apigateway/
