### ISSUE TITLE
${env:xxx} variables not replacing properly?

### ISSUE THREAD

**Issue by cdichiara** [serverless/serverless#3103]
# This is a Bug Report

## Description
Replacement of ${env:xxx} variables does not seem to be occurring?

Here are excerpts of `serverless.yml`:
```
provider:
  name: aws
  runtime: nodejs4.3
  memorysize: 1536 # can be overwritten on a per-function basis
  timeout: 9 # can be overwritten on a per-function basis
  stage: beta # default stage, can be overridden with serverless deploy -s xxx
  region: us-east-1 # default region, can be overridden with serverless deploy -r xxx
  role: lambdaRole
  environment:
    AwsRegion: ${opt:region, self:provider.region}
    CognitoDeveloperName: cognito.irewardhealth
    UserDbEmailIndex: Users-email
    DeviceDbUserIndex: Devices-userId
    SponsorDbNameIndex: Sponsor-name

    SponsorsDynamoDb:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:service}-Sponsors-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: sponsorId
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: sponsorId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: ${env:SponsorDbNameIndex}
            KeySchema:
              - AttributeName: name
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
```

Here is an excerpt of `cloudformation-template-update-stack.json`:
```
    "SponsorsDynamoDb": {
      "Type": "AWS::DynamoDB::Table",
      "DeletionPolicy": "Delete",
      "Properties": {
        "TableName": "irh-Sponsors-boreas",
        "AttributeDefinitions": [
          {
            "AttributeName": "sponsorId",
            "AttributeType": "S"
          },
          {
            "AttributeName": "name",
            "AttributeType": "S"
          }
        ],
        "KeySchema": [
          {
            "AttributeName": "sponsorId",
            "KeyType": "HASH"
          }
        ],
        "ProvisionedThroughput": {
          "ReadCapacityUnits": 1,
          "WriteCapacityUnits": 1
        },
        "GlobalSecondaryIndexes": [
          {
            "KeySchema": [
              {
                "AttributeName": "name",
                "KeyType": "HASH"
              }
            ],
            "Projection": {
              "ProjectionType": "ALL"
            },
            "ProvisionedThroughput": {
              "ReadCapacityUnits": 1,
              "WriteCapacityUnits": 1
            }
          }
        ]
      }
    },
```

Here is the error:
```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (5.76 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: SponsorsDynamoDb
     - Property IndexName cannot be empty..

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 win32
     Node Version:       6.9.2
     Serverless Version: 1.5.0
```

I've looked and it appears that all of my ${env:xxx} references are not being replaced. I have the workaround of ${self:provider.environment.xxx}, because I'm not using the overruling feature you guys are doing on a per-function basis ... but I wanted you to know about it, see if this is a known bug.

Full serverless.yml:
[https://drive.google.com/open?id=0B9rhfueQGcNta1JHVFBDVVlZVDg](url)
Full cloudformation-template-update-stack.json:
[https://drive.google.com/open?id=0B9rhfueQGcNtQ2lDaF9TOG9PU2c](url)

Similar or dependent issues:
I didn't find any...

## Additional Data
Version of software is included in the error message above ... Windows 10 x32.
