### ISSUE TITLE
Request: Supporting Method Request settings with lambda-proxy integration

### ISSUE THREAD

**Issue by cdichiara** [serverless/serverless#3105]
# This is a Feature Proposal
* **Description**
This is a request for support of Method Request settings simultaneously while having lambda-proxy integration.
* **What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.**
The serverless configuration of:
```
      - http:
          path: activities/search/{query}
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                language: false
                region: false
```
Elicits this error:
```
Serverless: Warning! You're using the LAMBDA-PROXY in combination with request / response configuration in your function "clientApi". Serverless will remove this configuration automatically before deployment.
```
Again, congratulations on your error messages - they are light years ahead of where v0.5.6 is. 🥇 The issue is, there's nothing that stops me from defining queryStrings *and* having lambda-proxy integration in the AWS Console. For example, I did this workaround:

```
resources:
  Resources:
    ApiGatewayMethodActivitiesSearchQueryVarGet:
      Properties:
        RequestParameters:
          method.request.querystring.language: false
          method.request.querystring.region: false
        AuthorizationType: AWS_IAM
```
And the query string parameters show up in the Method Request section of the APIG console. The reason this is important to us is because I am generating Mobile SDKs, and if I don't have the query strings there, the mobile developers won't have them as options in their SDKs.

* **If there is additional config how would it look**
I'd think you'd just relax the rules on lambda-proxy and reuse the request parameters that you are already using...

* **Similar or dependent issues:**
I couldn't find one.

## Additional Data

* ***Serverless Framework Version you're using***: v1.5
* ***Operating System***: Windows 10 x32, Node v6.9.0
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by pmuens** [comment]
Hey @cdichiara thanks for opening this issue.

Lambda Proxy is not designed to pass additional configuration as the request is passed as-is to the Lambda. You can read more about it here:
- https://aws.amazon.com/de/blogs/compute/easier-integration-with-aws-lambda-and-amazon-api-gateway/
- https://aws.amazon.com/de/blogs/aws/api-gateway-update-new-features-simplify-api-development/

You need to change to the integration type `lambda` to specify more configuration.

Closing this now as there's no way to relax `lambda-proxy` configuration rules.

**Comment by cdichiara** [comment]
Thanks for reviewing, @pmuens ... thanks for the links too.

Just for your future reference ...

Here's my serverless config Without Endpoint Info:
```
functions:
  clientApi:
    handler: lib/handleClientApi.handler
    description: REST API, server interface to client applications
    events:
      - http:
          path: activities/search/{query}
          method: get
          cors: true
          documentation:
            requestModels:
              application/json: emptyRequest
            methodResponses:
              - statusCode: 200
                responseModels:
                  application/json: activityGetResponse
              - statusCode: 400
                responseModels:
                  application/json: activityGetResponse
              - statusCode: 500
                responseModels:
                  application/json: activityGetResponse
resources:
  Resources:
    ApiGatewayMethodActivitiesSearchQueryVarGet:
      Properties:
        # RequestParameters:
          # method.request.path.query: true
          # method.request.querystring.language: false
          # method.request.querystring.region: false
        AuthorizationType: AWS_IAM
```
Here's my serverless config With Endpoint Info:
```
functions:
  clientApi:
    handler: lib/handleClientApi.handler
    description: REST API, server interface to client applications
    events:
      - http:
          path: activities/search/{query}
          method: get
          cors: true
          documentation:
            requestModels:
              application/json: emptyRequest
            methodResponses:
              - statusCode: 200
                responseModels:
                  application/json: activityGetResponse
              - statusCode: 400
                responseModels:
                  application/json: activityGetResponse
              - statusCode: 500
                responseModels:
                  application/json: activityGetResponse
resources:
  Resources:
    ApiGatewayMethodActivitiesSearchQueryVarGet:
      Properties:
        RequestParameters:
          method.request.path.query: true
          method.request.querystring.language: false
          method.request.querystring.region: false
        AuthorizationType: AWS_IAM
```
Console Image of Without Endpoint Info:
https://drive.google.com/open?id=0B9rhfueQGcNta19uSVNJQjc2UVU
Console Image of With Endpoint Info:
https://drive.google.com/open?id=0B9rhfueQGcNtc1I5RWxDNXVZekk

Here's the generated Android SDK without Endpoint Info:
```
    /**
     * 
     * 
     * @param body 
     * @return ActivityGetResponse
     */
    @com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/activities/search/{query}", method = "GET")
    ActivityGetResponse activitiesSearchQueryGet(
            EmptyRequest body);
```

And here is the Android Generated SDK With Endpoint Info:
```
    /**
     * 
     * 
     * @param query 
     * @param body 
     * @param region 
     * @param language 
     * @return ActivityGetResponse
     */
    @com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/activities/search/{query}", method = "GET")
    ActivityGetResponse activitiesSearchQueryGet(
            @com.amazonaws.mobileconnectors.apigateway.annotation.Parameter(name = "query", location = "path")
            String query,
            EmptyRequest body,
            @com.amazonaws.mobileconnectors.apigateway.annotation.Parameter(name = "region", location = "query")
            String region,
            @com.amazonaws.mobileconnectors.apigateway.annotation.Parameter(name = "language", location = "query")
            String language);
```
Anyways, as you can see it's necessary for using the generated SDK, and as far as I know it isn't interfering with lambda_proxy integration. I have no explanation why I have to declare the path variable ... it shows up in the Method Request area without it, but the Mobile SDK just doesn't recognize it. :( That's probably an AWS bug. I don't feel like switching back to lambda integration ... all those mapping templates, they create issues with nonexistent parameters, generating empty strings have to delete them ... just a mess.

Good luck!
