### ISSUE TITLE
(http) event variables

### ISSUE THREAD

**Issue by elgubenis** [serverless/serverless#3116]
# This is a Feature Proposal

## Description
* id like to know or propose a way to define custom variables per (in my specific case http) event
* additional config looks like this:

```yml
functions:
  status:
    handler: handler.status
    events:
      - http:
          method: GET
          path: /
          integration: lambda
          cors: true
          variables:
            handler: getStatus
      - http:
           method: POST
           path: /
           integration: lambda
           cors: true
           variables:
             handler: setStatus
```
* my goal is to evaluate the variable when executing the handler, lets say i have the following js export:

```js
'use strict';

const methods = {
  setStatus: (event, context, cb) => ...,
  getStatus: (event, context, cb) => ...,
};

module.exports.status = (event, context, cb) => {
  const method = methods[event.variables.handler];
  return method(event, context, cb);
};
```

* I could also imagine having a handler directly in every event, without having to define the variables, so the js could look like this:

```js
'use strict';

module.exports.status = {
  setStatus: (event, context, cb) => ...,
  getStatus: (event, context, cb) => ...,
};
```

not sure if possible though, i guess that'll need a wrapper function.

Could i explain myself, does that make any sense?
