### ISSUE TITLE
'sls deploy function -f xyz --noDeploy' does not honor --noDeploy

### ISSUE THREAD

**Issue by gkylafas** [serverless/serverless#3120]
# This is a Bug Report

## Description

* What went wrong?

> $ sls deploy function -f xyz --noDeploy
> Serverless: Deploying function: xyz...
> Serverless: Packaging function: xyz...
> Serverless: Uploading function: xyz (834.32 KB)...
> Serverless: Successfully deployed function: xyz
> $

* What did you expect should have happened?

The function to be packaged but not deployed, similarly to what `sls deploy --noDeploy` does.
The underlying reason for this is to verify that my packaging instructions in serverless.yml produce the correct zip file.

* What was the config you used?

```yaml
package:
  individually: true
functions:
  xyz:
    handler: xyz.handler
    package:
      exclude:
        - ./**
      include:
        - source/xyz.js
        - source/abc.js
        - lib/node_modules/qwerty/**
```

* What stacktrace or error message from your provider did you see?
nothing

## Additional Data

* ***Serverless Framework Version you're using***:
1.5.0
* ***Operating System***:
Ubuntu Linux 16.10
* ***Stack Trace***:
none
* ***Provider Error messages***:
none
