### ISSUE TITLE
Init Hook

### ISSUE THREAD

**Issue by Squareomatic** [serverless/serverless#3144]
# This is a Bug Report / Question

## Description

For bug reports:
* What went wrong? 

**I create my infrastructure outside from serverless to have more flexibility (mainly because of the CF template size limitations). Using the scriptable plugin I download some files and save them in the project to reference those through serverless variables:**

```
scriptHooks:
    before:deploy:cleanup: scripts/discover.js
```

```
provider:
  name: aws
  runtime: nodejs4.3
  stage:  ${opt:stage, ${self:custom.stage}}
  region: ${opt:region, ${self:custom.region}}
  profile: ${self:custom.profiles.${self:provider.stage}}
  environment: ${file(./global-lambda-variables-${self:provider.stage}.yml):environment}
```

**thing is that I have always the outdated version of the variables and I have to deploy twice because the serverless.yml file has been already filled in when I get the actual files from remote.**

* What did you expect should have happened?

**The latest version of the serverless.yml object after the files were downloaded.**

* What was the config you used?
* What stacktrace or error message from your provider did you see? 

**no error**

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

**Have a blocking hook that is always run before anything else to allow to download config info from remote and then returning a promise to tell serverless that the work has been done.**

**Is there already something similar?**

**thanks!**

## Additional Data

* ***Serverless Framework Version you're using***: 1.3
* ***Operating System***: mac os
