### ISSUE TITLE
Delploy error UPDATE_ROLLBACK_FAILED

### ISSUE THREAD

**Issue by marckaraujo** [serverless/serverless#3146]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

I can't deploy my project. It was fully working when I refactored a function from:
```

streamProfileLol:
                description: "Stream Profile Lol"
                handler: api/profile/stream/handler.default
                memorySize: 256
                timeout: 36
                vpc:
                  securityGroupIds:
                    - sg-XXXXXX
                  subnetIds:
                    - subnet-XXXXX
                    - subnet-XXXXX
                    - subnet-XXXXX
                events:
                  - stream: arn:aws:dynamodb:${self:provider.region}:XXXXXX:table/Lol/stream/XXXXXX
```
Then I just moved the handler to:

`                handler: api/stream/profile/handler.default
`
So I first got this error:

  ```
Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: StreamProfileLolLambdaFunction
     - The provided execution role does not have permissions
     to call DescribeNetworkInterfaces on EC2.
```

But this function was working and I do have this permission:

```
- Effect: Allow
       Action:
         - ec2:DeleteNetworkInterface
         - ec2:DescribeNetworkInterfaces
       Resource: 'arn:aws:ec2:${self:provider.region}:*:network-interface/*'
```

and Now I get this message every time I try to deploy:

```
Serverless Error ---------------------------------------
 
     Stack:arn:aws:cloudformation:us-east-2:418346753775:stack/proak-api-dev/1a0b87f0-d2ac-11e6-a687-50faf8bc7c9a
     is in UPDATE_ROLLBACK_FAILED state and can not be updated.
```

Any workaround to make this work again without do a serverless remove? I tried to back the handler to the previous position but still not working.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.1
* ***Operating System***: Mac OS El Capitan
* ***Stack Trace***:
* ***Provider Error messages***:
