### ISSUE TITLE
Skip resources if already exist

### ISSUE THREAD

**Issue by marckaraujo** [serverless/serverless#3148]
# This is a (Bug Report)

## Description

For bug reports:

* What went wrong?
I had a bug that cloudformation just stuck at UPDATE_ROLLBACK_FAILED.
So I should to delete the stack and deploy serverless again.

But now I got another problem:

```
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: AvailableDynamoDbTable
     - Available already exists.
```
With this error I need to delete the table to make serverless deploy again. But I cant delete the table and also I dont want to remove the resources from serverless.yml.

* What did you expect should have happened?

It should skip the resource deploy if it already exist.

* What was the config you used?
* What stacktrace or error message from your provider did you see?

```
Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: AvailableDynamoDbTable
     - Available already exists.
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.1
* ***Operating System***: Mac OS El Capitan
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @marckaraujo could you please share your `serverless.yml` file? Thanks!

**Comment by marckaraujo** [comment]
Hello @pmuens , just had to cover some info but here you go.

```
 
service: XXXX-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
   name: aws
   runtime: nodejs4.3
   stage: dev # Set the default stage used. Default is dev
   region: us-east-2 # Overwrite the default region used. Default is us-east-1
   profile: devProfile
   #cfLogs: true # Set this in next version
   apiKeys:
    - ${self:provider.stage}-api-key
   iamRoleStatements:
     - Effect: "Allow"
       Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
       Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
     - Effect: Allow
       Action:
         - ec2:CreateNetworkInterface
       Resource: '*'
     - Effect: Allow
       Action:
         - ec2:DeleteNetworkInterface
         - ec2:DescribeNetworkInterfaces
       Resource: 'arn:aws:ec2:${self:provider.region}:*:network-interface/*'
    #  - Effect: "Allow"
    #    Action:
    #       - kms:Decrypt
    #    Resource: "arn:aws:kms:${self:provider.region}:*:*"

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  #- serverless-crypt

custom:
  serverless-offline:
      babelOptions:
        presets: ["es2015"]

package:
  individually: true

# Keeping packages small by excluding node_modules
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - node_modules/**

functions:
  xxxxCreate:
    description: "XXXXX"
    handler: api/xxxx/xxxx/handler.default
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: xxxxx
          method: POST
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
          private: true
          headers:
            - Content-Type
            - Authorization
            - Accept
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - x-secret

  xxxxUpdate:
    description: "xxxxxxx"
    handler: api/xxxxx/update/handler.default
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: xxxxxx
          method: PUT
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
          private: true
          headers:
            - Content-Type
            - Authorization
            - Accept
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - x-secret

  xxxxxLogin:
    description: "xxxxx"
    handler: api/xxxxxxx/login/handler.default
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: xxxxxx
          method: POST
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
          private: true
          headers:
            - Content-Type
            - Authorization
            - Accept
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - x-secret

  xxxxxCreate:
    description: "Xxxxxx"
    handler: api/xxxxx/xxxxx/create/handler.default
    memorySize: 256
    timeout: 12
    events:
      - http:
          path: xxxxxxx
          method: POST
          cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
          private: true
          headers:
            - Content-Type
            - Authorization
            - Accept
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - x-secret

  xxxxxxDelete:
        description: "xxxxxxx"
        handler: api/xxxx/xxxx/delete/handler.default
        memorySize: 256
        timeout: 12
        events:
          - http:
              path: xxxxxxxx
              method: DELETE
              cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
              private: true
              headers:
                - Content-Type
                - Authorization
                - Accept
                - X-Amz-Date
                - X-Api-Key
                - X-Amz-Security-Token
                - x-secret

  xxxxxGet:
          description: "xxxxxx"
          handler: api/xxxx/xxxxx/get/handler.default
          memorySize: 256
          timeout: 12
          events:
            - http:
                path: xxxxxxx
                method: GET
                cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                private: true
                headers:
                  - Content-Type
                  - Authorization
                  - Accept
                  - X-Amz-Date
                  - X-Api-Key
                  - X-Amz-Security-Token
                  - x-secret

  xxxxxxxPlayer:
            description: "xxxxxx"
            handler: api/xxxxxx/player/handler.default
            memorySize: 256
            timeout: 18
            events:
              - http:
                  path: xxxxxxx
                  method: GET
                  cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                  private: true
                  headers:
                    - Content-Type
                    - Authorization
                    - Accept
                    - X-Amz-Date
                    - X-Api-Key
                    - X-Amz-Security-Token
                    - x-secret
              - http:
                  path: xxxx
                  method: POST
                  cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                  private: true
                  headers:
                    - Content-Type
                    - Authorization
                    - Accept
                    - X-Amz-Date
                    - X-Api-Key
                    - X-Amz-Security-Token
                    - x-secret

  xxxxxVerify:
              description: "xxxxxxxx"
              handler: api/xxxxx/verify/handler.default
              memorySize: 256
              timeout: 12
              events:
                - http:
                    path: xxxxx
                    method: POST
                    cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                    private: true
                    headers:
                      - Content-Type
                      - Authorization
                      - Accept
                      - X-Amz-Date
                      - X-Api-Key
                      - X-Amz-Security-Token
                      - x-secret

  xxxxxxxAvailable:
                description: "xxxxxxx"
                handler: api/xxxx/available/handler.default
                memorySize: 256
                timeout: 12
                events:
                  - http:
                      path: xxxxxxx
                      method: GET
                      cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                      private: true
                      headers:
                        - Content-Type
                        - Authorization
                        - Accept
                        - X-Amz-Date
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - x-secret
                  - http:
                      path: xxxxxx
                      method: POST
                      cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                      private: true
                      headers:
                        - Content-Type
                        - Authorization
                        - Accept
                        - X-Amz-Date
                        - X-Api-Key
                        - X-Amz-Security-Token
                        - x-secret

  xxxxRoom:
                  description: "xxxxx"
                  handler: api/xxxxxx/room/handler.default
                  memorySize: 256
                  timeout: 12
                  events:
                    - http:
                        path: xxxxxx
                        method: GET
                        cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                        private: true
                        headers:
                          - Content-Type
                          - Authorization
                          - Accept
                          - X-Amz-Date
                          - X-Api-Key
                          - X-Amz-Security-Token
                          - x-secret
                    - http:
                        path: xxxxxx
                        method: POST
                        cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                        private: true
                        headers:
                          - Content-Type
                          - Authorization
                          - Accept
                          - X-Amz-Date
                          - X-Api-Key
                          - X-Amz-Security-Token
                          - x-secret
                    - http:
                        path: xxxxxx
                        method: PATCH
                        cors: true # Turn on CORS for this endpoint, but don't forget to return the right header in your response
                        private: true
                        headers:
                          - Content-Type
                          - Authorization
                          - Accept
                          - X-Amz-Date
                          - X-Api-Key
                          - X-Amz-Security-Token
                          - x-secret

  xxxxxxxxP:
                  description: "xxxxxx"
                  handler: api/xxxxx/profile/handler.default
                  memorySize: 256
                  timeout: 36
                  vpc:
                    securityGroupIds:
                      - sg-xxxxx
                    subnetIds:
                      - subnet-xxxxxx
                      - subnet-xxxxxx
                      - subnet-xxxxxxx
                  events:
                    - stream: arn:aws:dynamodb:${self:provider.region}:xxxxxx:table/xxxxx/stream/2017-01-26T22:29:43.433

  xxxxxxRoom:
                  description: "xxxxxx"
                  handler: api/xxxxx/room/handler.default
                  memorySize: 256
                  timeout: 36
                  events:
                    - stream: arn:aws:dynamodb:${self:provider.region}:xxxxxxxx:table/xxxxx/stream/2017-01-26T22:29:39.874
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
  Resources:
    xxxxxDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
          -
            AttributeName: password
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          -
            IndexName: password-index
            KeySchema:
              -
                AttributeName: password
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        TableName: 'xxxxxx'
    xxxxDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: title
            AttributeType: S
        KeySchema:
          -
            AttributeName: title
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: 'xxxxx'
    xxxxxDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: 'xxxxx'
    xxxxxDynamoDbTable:
          Type: 'AWS::DynamoDB::Table'
          DeletionPolicy: Retain
          Properties:
            AttributeDefinitions:
              -
                AttributeName: userId
                AttributeType: S
            KeySchema:
              -
                AttributeName: userId
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            TableName: 'xxxxxxx'
    xxxxxDynamoDbTable:
              Type: 'AWS::DynamoDB::Table'
              DeletionPolicy: Retain
              Properties:
                AttributeDefinitions:
                  -
                    AttributeName: id
                    AttributeType: S
                  -
                    AttributeName: status
                    AttributeType: S
                  -
                    AttributeName: game
                    AttributeType: S
                KeySchema:
                  -
                    AttributeName: id
                    KeyType: HASH
                ProvisionedThroughput:
                  ReadCapacityUnits: 5
                  WriteCapacityUnits: 5
                GlobalSecondaryIndexes:
                  -
                    IndexName: status-index
                    KeySchema:
                      -
                        AttributeName: status
                        KeyType: HASH
                      -
                        AttributeName: game
                        KeyType: RANGE
                    Projection:
                      ProjectionType: ALL
                    ProvisionedThroughput:
                      ReadCapacityUnits: 5
                      WriteCapacityUnits: 5
                TableName: 'xxxx'

```
