### ISSUE TITLE
YML Does Not Allow Tags, Especially ImportValue

### ISSUE THREAD

**Issue by jthomerson** [serverless/serverless#3162]
# This is a Bug Report

## Description

Recently #2183 was closed by #2796. However, the updated code uses a bit of a hack that relies on `if (valueStartsWith('arn:'))` to determine if this is an "external" SNS topic. That doesn't work with [cross-stack references](https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/) to SNS topics.

I think it's very important to encourage the most granular microservices possible. Thus, here's an example of a set of microservices that exemplifies why this support is needed:

 1. One microservice is a very simple service for ingestion of certain files that need to be processed by various business processes. It provides an S3 bucket for the to-be-processed files to be uploaded to. It sets up the S3 bucket so that new files in the bucket notify an SNS topic - this is its "API" if you will - the way other microservices know about uploaded files.
 2. Another microservice provides one of the types of processing that needs to be done on these ingested files. It provides a Lambda function that takes a new file and does some processing on it - saving it to a database, indexing it in CloudSearch, etc. It needs to be able to subscribe its Lambda function to the SNS topic of the previous microservice.

The only way to accomplish this with the just-merged code is to manually create the arn based on variables and CF references. It would be a much better abstraction to rely on the exported value from the other stack.

However, the real underlying issue is that the new `!ImportValue` and other tags described in the [cross-stack references blog post](https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/) are not supported by SLS. Supporting these would be a huge win not only for SNS, but other cross-stack dependency needs.

See the attached example services to reproduce the issue: [sls-3162-importvalue-support.tar.gz](https://github.com/serverless/serverless/files/750808/sls-3162-importvalue-support.tar.gz)

Similar or dependent issues:
* #2183

**Comment by moh-abk** [comment]
Not sure if this applies but referencing an SNS topic that'll be created in the stack doesn't work either:

```
  functions:
  stage_website:
    handler: handler.handler
    name: ${self:provider.stage}-stage-website
    description: Lambda function to Stage Website
    role: ${self:resources.Outputs.StageWebsiteLambdaIAMRoleArn.Value}
    runtime: nodejs4.3
    memorySize: 1024
    timeout: 300
    events:
      - sns: ${self:resources.Outputs.StageWebsiteLambdaSNSTopicArn.Value}
```

```
 Serverless Error ---------------------------------------

     Missing or invalid "topicName" property for sns event
     in function stage_website The correct syntax is: sns:
     topic-name-or-arn OR an object with "topicName" AND
     "displayName" strings. Please check the docs for more
     info.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.6.0
```

**Comment by pmuens** [comment]
@moh-abk The problem is that the variable population happens before the stack is created / deployed. This way Serverless variables can not access the Outputs section of your CloudFormation template.

The only way to do what you intended to do is to use `GetAtt` / `Ref` and reference a topic in your resources or a JavaScript function for your Serverless variable which computes the `arn` --> https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files.

**Comment by ironmanwaring** [comment]
The use case in the issue matches how I was expecting this feature to be implemented.  From @pmuens reply it sounds like there isn't a straightforward way to change this behavior?

**Comment by pmuens** [comment]
@ironmanwaring correct, right now it's not possible to reference an output value with the help of the variable system.

**Comment by jthomerson** [comment]
What @moh-abk asks is not possible, but it's also not what this issue is about. The problem described in this issue is that we can not use any of the new syntax that CFN supports. For example:

 1. `!Ref SomeResource`
 2. `!FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]`
 3. `!GetAtt [foo, bar]`
 4. `!ImportValue AccountSG` **<-- this is the most important one because this is the way you access exported values from other stacks**

I'm going to rename the issue to keep it a bit more on focus. If that one feature was supported, it would resolve a lot of "can't depend on external foo" type issues - not just SNS.

**Comment by jthomerson** [comment]
Attaching a sample that contains two dependent services.

[sls-3162-importvalue-support.tar.gz](https://github.com/serverless/serverless/files/750808/sls-3162-importvalue-support.tar.gz)

**Comment by dougmoscrop** [comment]
Yes, I implemented the arn detection "hack" to solve an immediate use case. It's not a big deal to expand that detection to support `Fn::ImportValue` or `Ref` as next steps.

The reference to the YAML syntax is conflating two different things, I believe.

**Comment by dougmoscrop** [comment]
Also while it's not possible to reference *output* is that even normal or allowed CF usage? I would expect to use `Ref` / `Fn:GetAtt` / `Fn::ImportValue` and you would use the Logical ID of the topic, @moh-abk

**Comment by picsoung** [comment]
I had a similar issue #2240 

and at that time I was able to solve it having environment variables using `Ref`, and then consume those variables in the event property

Today this hack does not work anymore :(

```yml
provider:
  name: aws
  environment:
    SNS_TOPIC_ARN:
     Ref: SNStopic
functions:
  hello:
    handler: handler.hello
    events:
      - sns: "${env:SNS_TOPIC_ARN}"

resources:
 Resources:
   SNStopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "${opt:stage, self:provider.stage}-${self:service}-threescaleAsync"
```
