### ISSUE TITLE
module initialization error: Error

### ISSUE THREAD

**Issue by daviskoh** [serverless/serverless#3176]
# This is a Bug Report

## Description

Anytime the Lambda function is run i get:

```
module initialization error: Error
```

regardless of whether I `curl` them or run it straight from Lambda Management Console using the `Test` button. The functions work fine when I run them locally using `sls invoke local -f`

## Source Code

All my Lambda functions from this service fail with this same error. I even uploaded a very simple function with no dependencies that still fails. From `handler.js`:

```
module.exports.healthcheck = (event, context, callback) => {
  console.log(event);

  callback(null, {
    statusCode: 200,
    body: JSON.stringify({
      message: `All good: ${new Date().toTimeString()}.`,
      env: `${process.env.NODE_ENV}`,
    }),
  });
};
```

The relevant section from the `serverless.yaml` is

```
functions:
  healthcheck:
      handler: handler.healthcheck
      events:
        - http:
            path: healthcheck
            method: get
            cors: true
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.1
* ***Operating System***: macOS Sierra 10.12.2 (local) & Ubuntu 14.04 (CircleCI / deploy)
* ***Stack Trace***:

Straight from CloudWatch, below is all there is

![image](https://cloud.githubusercontent.com/assets/5395403/22487160/464a185c-e7da-11e6-834d-0aaedda4a665.png)

Any assistance would be greatly appreciated!
