### ISSUE TITLE
Support for Usage Plans

### ISSUE THREAD

**Issue by edmofro** [serverless/serverless#3182]
# This is a Feature Proposal

## Description
As documented in #3030, Serverless Framework does not support attaching API's to usage plans. This was because CloudFormation did not support it, but it [now does](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-usageplan.html). Would be nice to see this supported in Serverless, and documentation explaining it.

## Additional Data

* ***Serverless Framework Version you're using***: 1.4.0
* ***Operating System***: OSX El Capitan

**Comment by edmofro** [comment]
See also #2831

**Comment by pmuens** [comment]
Thanks for letting us know @edmofro 👍

**Comment by pmuens** [comment]
Hey @edmofro I'm closing this because we have in-depth conversations in #2539 and #2450.

Thanks for bringing this topic up again!

**Comment by edmofro** [comment]
@pmuens No problem, although my requirement for a usage plan wasn't to attach an API key, but rather to set a quota on requests. I've had success using the following in my serverless.yml
```
resources:
  Resources:
    UsagePlan:
      Type: AWS::ApiGateway::UsagePlan
      Properties:
        ApiStages:
        - ApiId:
            Ref: "ApiGatewayRestApi"
          Stage: ${self:provider.stage}
        Description: ${self:provider.stage} usage plan
        Quota: # Limit the total HTTP requests to 20,000,000 per week to avoid an unexpected bill
          Limit: 20000000
          Period: "WEEK"
        UsagePlanName: "${self:service}-${self:provider.stage}"
```
I had hoped by opening this issue, the team behind Serverless Framework might add support within the 'provider' section of the yaml to create/attach a usage plan, and if not, document the 'resources' route.

**Comment by pmuens** [comment]
Ah ok. That makes sense...

Thanks for sharing the resource definition! Will re-open this issue since it's not solely about API Keys! 👍

**Comment by kevindiamond** [comment]
Until this is supported in the provider section I had success with the following in the Resources section:
```yaml
    UsagePlan:
      Type: "AWS::ApiGateway::UsagePlan"
      Properties:
        UsagePlanName: servicename-${opt:stage}-usageplan
        ApiStages:
        - ApiId:
            Ref: ApiGatewayRestApi
          Stage: ${opt:stage}
        Description: servicename-${opt:stage}-usageplan
        Quota:
          Limit: 5000
          Period: DAY
        Throttle:
          BurstLimit: 2000
          RateLimit: 1000
      DependsOn: ApiGatewayApiKey1
    UsagePlanKey:
      Type: "AWS::ApiGateway::UsagePlanKey"
      Properties:
        KeyId:
          Ref: ApiGatewayApiKey1
        KeyType: API_KEY
        UsagePlanId:
          Ref: UsagePlan
```

**Comment by pmuens** [comment]
Thanks for sharing this @kevindiamond! 👍

**Comment by talawahtech** [comment]
FYI, apparently Usage Plans create a chicken and egg problem that causes attempts to delete the stack to fail on the first try: http://stackoverflow.com/questions/42125380/cloudformation-stack-resource-dependency-issues-api-gateway-deployment-usagep

Calling `serverless remove` a second time works, but it may be confusing/concerning to users.

**Comment by pmuens** [comment]
Closing this issue since we're discussing the implementation details in #2450

**Comment by Leomel** [comment]
#2831 #4006

**Comment by tommedema** [comment]
If you define a usagePlan while not using API keys, are these then applied to the overall API gateway?

```
provider:
  usagePlan:
    quota:
      limit: 10000
      offset: 0
      period: DAY
    throttle:
      burstLimit: 100
      rateLimit: 50
```

The documentation is not clear about this
