### ISSUE TITLE
Variables syntax collides with AWS params syntax

### ISSUE THREAD

**Issue by paulSambolin** [serverless/serverless#3184]
I was attempting to use !Sub as shown in the [EC2 metadata file section](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#d0e29330)

This example is exactly reflected on the [Fn::Sub Page](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#intrinsic-function-reference-sub-example.yaml)

Yet when I place this in the serverless.yml I get the following exception:

```Y A M L Exception --------------------------------------

     unknown tag !<!Sub> in "/Users/paulsambolin/Desktop/serverless.yml"
     at line 317, column 15:
                  mode: "000644"

                      ^

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

YAMLException: unknown tag !<!Sub> in "/Users/paulsambolin/Desktop/serverless.yml" at line 317, column 15:
                  mode: "000644"
                  ^
    at generateError (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at composeNode (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1398:7)
    at readBlockMapping (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
From previous event:
    at __dirname (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/bin/serverless:15:28)
    at Object.<anonymous> (/Users/paulsambolin/.nvm/versions/node/v6.3.0/lib/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

Similar issue: https://github.com/serverless/serverless/issues/8116

--- 

## Proposed solution

Improve variables format regex into `'\\${([^{}:]+?:[^:{}][^{}]*?)}'` - This should ensure that notations `${StepFunctionArn}` (as reported at https://github.com/serverless/serverless/issues/8116)  or `${AWS::Whatever}` are not picked as SLS variables

Additionally to ensure a solution for eventual more difficult cases (not necessary AWS related) we may consider to introduce an escape notation (so e.g. `\${` is not recognized as variables start bracket)

**Comment by ProTip** [comment]
It would be great if serverless could either output yaml and preserve the tags, or render the tags properly into the long form for the json output.

**Comment by pas256** [comment]
I tried to do this very thing yesterday to discover I couldn't.

**Comment by HyperBrain** [comment]
Sub clashed with the Serverless "${}" variable declaration syntax as AWS uses exactly the same syntax with Fn::Sub

**Comment by pas256** [comment]
Exactly. There are probably many ways to support both. 

Ideally, serverless recognizes the `Sub`, and then skips variables it doesn't know about expecting CloudFormation to solve it. That sounds hard.

Another idea is to make it explicit with a prefix much like `${self:}`:

    Fn::Sub: 
        - "${cf:NotAServerlessVar}-abcd-${ServerlessVar}-${cf:NotAServerlessVar2}"
        - NotAServerlessVar: 123
          NotAServerlessVar2: xyz

**Comment by HyperBrain** [comment]
Introducing a separate CF: prefix for vars sounds more irritating because it just would skip the variable substitution.

More intuitive would be to use double-$ to escape variable substitution. So `$${NotAServerlessVar}` would not be treated as variable and end up as `${NotAServerlessVar}` in the CF template,

How does that sound?

**Comment by pas256** [comment]
That works too.

**Comment by pmuens** [comment]
> More intuitive would be to use double-$ to escape variable substitution. So $${NotAServerlessVar} would not be treated as variable and end up as ${NotAServerlessVar} in the CF template

Yes, that sounds like a good idea. Since `cf` would be AWS specific an Serverless is build to support multiple providers from the ground up...

Here's another, old discussion about escaping etc. https://github.com/serverless/serverless/issues/1728#issuecomment-237049273

Furthermore you can use the `variableSyntax` property to define your own variable syntax: https://github.com/serverless/serverless/pull/1764

**Comment by eric-tucker** [comment]
What was ultimately done to address this?  Or is escaping a $ to a CloudFormation object not supported yet?

**Comment by pkubat** [comment]
here is my workaround for now, exclude 'AWS::' as these are the variables that I needed for Fn::Sub.

Example
```
Resource:
        "Fn::Sub": "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table...
```

serverless.yml
```
provider:
  name: aws
  runtime: nodejs6.10
  # Allow for cf "AWS::" variables, see https://serverless.com/framework/docs/providers/aws/guide/variables#using-custom-variable-syntax
  variableSyntax: "\\${(?!AWS::)([ :a-zA-Z0-9._,\\-\\/\\(\\)]+?)}"
```

**Comment by pmuens** [comment]
Looks good. Thanks for shairng @pkubat 👍 

We currently have a PR (https://github.com/serverless/serverless/pull/3694) in the pipeline which enhances the variable syntax and will help here.

**Comment by lorengordon** [comment]
This plugin does this pretty well, for me anyway.

https://gitlab.com/kabo/serverless-cf-vars

**Comment by sam3d** [comment]
Any updates on this being implemented natively?

**Comment by deftomat** [comment]
@sam3d not sure but we solve this by using the *serverless.js* instead of *serverless.yml*.
I can say that once you try it, you don’t want to use yaml anymore. JS file can export the promise, so you have an infinite amount of possibilities how to construct the config and this issue becomes obsolete. 

I’m not sure why this is not mentioned in a docs as a recommended way how to define your stack 😉

**Comment by aaronosb** [comment]
Would definitely also appreciate an update on how to support this without adding additional plugins, I have run into this issue multiple times in the past week and would appreciate a native solution. Like the purposed double escape $$

**Comment by seriouscoderone** [comment]
I believe the workaround is to just use `Ref` https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html

You may have to nest a `Ref` inside a `Fn::Join` in order to get the `Fn::Sub` functionality. 

For example:
`"Fn::Sub": "arn:aws:iam::${AWS::AccountId}:root"`
Becomes:
`"Fn::Join": ["", [ "arn:aws:iam::", { "Ref": "AWS::AccountId" }, ":root"]]`

**Comment by cyberfox1** [comment]
Everyday those people saying serverless just causes more problems than it solves, just use raw CloudFormation, make more and more sense to me.

**Comment by ksac1** [comment]
I have this issue: An error occurred (ValidationError) when calling the ValidateTemplate operation: Template error: variable names in Fn::Sub syntax must contain only alphanumeric characters, underscores, periods, and colons
ERROR: Job failed: exit code 1

Any solution?

**Comment by et304383** [comment]
How is this not solved yet?  It's been almost 3 years.

**Comment by lepidotteri** [comment]
ping

**Comment by et304383** [comment]
Seriously, can we just do like a double $$ and be done with it?  This is getting ridiculous.  I feel so dirty having to use Fn::Join with serverless.

**Comment by igorrocha** [comment]
> Seriously, can we just do like a double $$ and be done with it? This is getting ridiculous. I feel so dirty having to use Fn::Join with serverless.

It really is a bit frustrating... I've solved my problem using this plugin: https://www.npmjs.com/package/serverless-pseudo-parameters

Variables declared with ${} will be handled by serverless, and variables declared with #{} will be subbed for ${} on the final template, letting CF do its work.

**Comment by milesgranger** [comment]
I couldn't end up using `serverless-pseudo-parameters` because it would try to be too smart and inject another `!Sub` statement. :man_shrugging: 

So instead this works:

```yaml
# serverless.yml
provider:
  # serverless ignores ${AWS...} and ${_...}
  variableSyntax: "\\${((?!AWS|_)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)]+?)}"

# later on this works as expected.
foos: 
  - !Sub
    - some-${_specialVar1}-${_specialVar2}-string
    - _specialVar1: bar1
      _specialVar2: bar2
```
Not claiming to be the _best_ solution, but I like it. And one can change the prefix (`_`) to whatever else is preferred.

**Comment by Ownmarc** [comment]
You can now place ${} literals in your templates using ${!} like this:

```
Resource:
    - !Sub
        - "arn:aws:s3:::${BucketName}/protected/${!cognito-identity.amazonaws.com:sub}/*"
        - {"BucketName": !Ref ParamBucketName}
```

**Comment by et304383** [comment]
@Ownmarc  if that's working for you it's becuase you've defined a variableSyntax value that states that that serverless shouldn't interpret ${!<var name>} as a serverless var.  That's no different than the solution above your post.

**Comment by Ownmarc** [comment]
@et304383 I didn't define variableSyntax

its in the doc here : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

**Comment by mnapoli** [comment]
Hi all, I think I have found a possible solution.

The [serverless-pseudo-parameters plugin](https://github.com/svdgraaf/serverless-pseudo-parameters) has been mentioned, and it has the disadvantage of having a custom/weird syntax (`#{Resource.Attr}`) to avoid collision with serverless variables.

However, I managed to make it work with the serverless variable syntax. Here are a few examples:

```yaml
functions:
    hello:
        handler: handler.hello
        environment:
            # We can reference `AWS::` variables
            REGION: ${AWS::Region}

            # We can use !Ref inline via the `ref:` prefix:
            BUCKET_NAME: ${ref:MyBucket}

            # We can use !GetAtt inline via the `getatt:` prefix:
            BUCKET_URL: 'https://${getatt:MyBucket.DomainName}'

            # We can use mix all that together in a string:
            REGIONAL_URL: 'https://${ref:MyBucket}.s3.${AWS::Region}.amazonaws.com'

            # We can also mix all of that with actual serverless variables (e.g. `${self:provider.stage}`)

resources:
    Resources:
        MyBucket:
            Type: AWS::S3::Bucket
```

In my example above, although I don't explicitly write `!Sub`, the end result is the same: I can "subtract" variables in a string.

And all of those strings are compiled to `Fn::Sub` in the CloudFormation template generated by serverless.

### How it works

Nothing clever. For my proof of concept, I defined the following variables via a plugin:

- `${AWS::xxx}` is compiled to `#{AWS::xxx}`
- `${ref::xxx}` is compiled to `#{xxx}`
- `${getatt::xxx.yyy}` is compiled to `#{xxx.yyy}`

Then, the [serverless-pseudo-parameters plugin](https://github.com/svdgraaf/serverless-pseudo-parameters) transforms these variables to `!Sub` calls.

Now, while it works, is this something that we could eventually integrate into Serverless? (this is a question for maintainers)

I will be opening the same issue in the plugin (to see if we can add support more quickly), but if we can have that officially, I'm up for giving it a try (maybe with some advice/help?). I don't like the 2 step process, maybe we can do better. Also, all those CloudFormation variables do not work locally, but in any case I don't see how we could make things work locally when we reference cloud resources (which is what `!Ref` and al is all about).

**Comment by Nemo64** [comment]
I want to add an alternative.

serverless allows to adjust the variableSyntax:

```yaml
provider:
  # Allow using CloudFormation variable syntax without changing the serverless syntax
  # The differentiating factor is the capitalization of the first character
  # Upper case character means CloudFormation syntax, eg: ${AWS::Region}, ${DatabaseSecret}
  # Everything else means serverless syntax, eg: ${ssm:...}, ${self:...}
  # https://www.serverless.com/framework/docs/providers/aws/guide/variables#using-custom-variable-syntax
  variableSyntax: "\\${((?![A-Z])[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)]+?)}"
```

With that configuration you can then do stuff like this:

```yaml
provider:
  # [...]
  environment:
    STAGE: ${opt:stage, self:provider.stage} # use serverless syntax as usual
    MAILER_DSN: !Sub 'ses://default?region=${AWS::Region}' # use CloudFormation !Sub as usual
    DATABASE_URL: !Sub '//${AWS::Region}/${Database}' # reference other resource as long as they use the UpperCamelCase naming convention
```
