### ISSUE TITLE
yaml exception

### ISSUE THREAD

**Issue by QuantumInformation** [serverless/serverless#3190]
I don't see what is wrong here:

![image](https://cloud.githubusercontent.com/assets/216566/22620173/59512b5e-eafd-11e6-9963-3e2ada32146c.png)

```yaml
Resources:
  TasksDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
          -
          AttributeName: id
           AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: 'todos'
          BucketName: my-new-bucket
```

Also, is there a good editor for yaml, editing in webstorm is not fun.

**Comment by pmuens** [comment]
Hey @QuantumInformation 

you need to "wrap" the `Resources` into `resources`. So basically:

```yml
resources:
  Resources:
    TasksDynamoDbTable
      ...
```

I use Atom all the time. Have been a long time WebStorm user before that...

**Comment by QuantumInformation** [comment]
I think I will download atom just for this:

issue remains:

![image](https://cloud.githubusercontent.com/assets/216566/22620204/6f89a1c0-eafe-11e6-8845-dee3317d685b.png)

all code:
```yml

service: quantumjs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: DescribeTable
        - dynamodb: Query
        - dynamodb: Scan
        - dynamodb: GetItem
        - dynamodb: PutItem
        - dynamodb: UpdateItem
        - dynamodb: DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

  region: us-west-2


functions:
  sendMail:
    handler: emailServices.sendMail
  createTodo:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true

    events:
      - http:
          path: email
          method: get
          cors: true

resources:
  Resources:
    TasksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
            -
            AttributeName: id
             AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'todos'
            BucketName: my-new-bucket
```

**Comment by pmuens** [comment]
Hey @QuantumInformation you have some errors in your `serverless.yml` file.

**The first one ist that you don't need to define `events` twice in a function definition:**

```yml
functions:
  createTodo:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true
    events:
      - http:
          path: email
          method: get
          cors: true
```

should be written like this:

```yml
functions:
  createTodo:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true
      - http:
          path: email
          method: get
          cors: true
```

**Next up you need to remove the spaces in the `iamRoleStatements`:**

```yml
provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb: DescribeTable
        - dynamodb: Query
        - dynamodb: Scan
        - dynamodb: GetItem
        - dynamodb: PutItem
        - dynamodb: UpdateItem
        - dynamodb: DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
```

Should be

```yml
provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"
```

**And the final one is that you need to remove the `BucketName` definition in the `resources` section:**

```yml
resources:
  Resources:
    TasksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
            -
            AttributeName: id
             AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'todos'
            BucketName: my-new-bucket
```

becomes

```yml
resources:
  Resources:
    TasksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
            -
            AttributeName: id
             AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'todos'
```

---

So all in all the `serverless.yml` file looks like this:

```yml
service: quantumjs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

  region: us-west-2


functions:
  sendMail:
    handler: emailServices.sendMail
  createTodo:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true
      - http:
          path: email
          method: get
          cors: true

resources:
  Resources:
    TasksDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: 'Retain'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'todos'
```

BTW: I've used https://www.json2yaml.com/ to validate the JSON. Is sometimes a handy tool to take quick look at what's wrong...

Let us know if this resolves your issue.
