### ISSUE TITLE
functionArn.split is not a function when using Fn::Join

### ISSUE THREAD

**Issue by rochdev** [serverless/serverless#3212]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Error when trying to reference ARN from another CF stack.

* What did you expect should have happened?
The function should have been created using the provided external ARN.

* What was the config you used?
```yaml
functions:
  myFunction:
    handler: handler.myFunction
    events:
      - http:
          ...
          authorizer:
            arn: { "Fn::Join" : [ ":", [ "arn:aws:lambda", { "Ref" : "AWS::Region" }, { "Ref" : "AWS::AccountId" }, "function:myAuthorizer" ] ] }
            ...
```

* What stacktrace or error message from your provider did you see?
```
Serverless: Packaging service...

  Type Error ---------------------------------------------

     functionArn.split is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.2
     Serverless Version: 1.6.1
```
Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.1
* ***Operating System***: macOS Sierra 10.12.3
* ***Stack Trace***: (see above)
* ***Provider Error messages***: (see above)

**Comment by jatsrt** [comment]
Similar issue: 
One project that is the global authorizer, and exports lambda function ARNs

Other project that want to use that authorizer

```
authorizer:
  apn:
    Fn::ImportValue: ${self:authService}:${opt:stage, self:provider.stage}:AuthLambdaARN
```

This yields the same problem as the naming cannot be determined from this.  Only other option is to hardcode the ARN for now.

**Comment by HyperBrain** [comment]
@eahefnawy @pmuens This is a similar issue as the arn parsing in the stream arns. I think we need a general arn parser function somewhere that is capable to
(1) read string formatted arns
(2) read arbitrary dynamic arns (Fn::Join, Fn::GetAttr, Ref)
And return the reference resource logical id.
It makes no sense to fix the problem in various places separately with different implementations.

I suggest to have one parseArn() function in serverless.utils that would be used from everywhere.

In my plugin I used a very generic function for that:
```
	static findAllReferences(root) {
		const resourceRefs = [];
		const stack = [ { parent: null, value: root, path: '' } ];

		while (!_.isEmpty(stack)) {
			const property = stack.pop();

			_.forOwn(property.value, (value, key) => {
				if (key === 'Ref') {
					resourceRefs.push({ ref: value, path: property.path });
				} else if (key === 'Fn::GetAtt') {
					resourceRefs.push({ ref: value[0], path: property.path });
				} else if (_.isObject(value)) {
					key = _.isArray(property.value) ? `[${key}]` : (_.isEmpty(property.path) ? `${key}` : `.${key}`);
					stack.push({ parent: property, value, path: `${property.path}${key}` });
				}
			});
		}

		return resourceRefs;
	}
```

Given a root object (in this case the arn: object) it will return an array of all contained references (including those contained within GetAtt) with their path. You can use _.get(root, refPath) to access the ref object or just use the returned refs (which are the logical resource ids).

**Comment by pmuens** [comment]
@HyperBrain love the idea of having a central ARN parser!

What do you think about opening up a separate issue for this. Or should we rename this one?

**Comment by HyperBrain** [comment]
@pmuens I think we should open a separate issue and link all existing arn parser exception issue there. Then it is clear for every single issue that it will be handled centrally.

**Comment by HyperBrain** [comment]
Link to https://github.com/serverless/serverless/issues/3212#issuecomment-285731535 as the s3 event bucket specification could also be a generic ARN as an alternative to create the bucket implicitly. This would make the s3 events much more flexible.

**Comment by HyperBrain** [comment]
Adding a good example brought up by @erikerikson in the context of step functions:
```
Resource: [lambda name | activity name | lambda ARN | activity ARN | Fn::GetAtt (lambda) | Fn::Ref (activity) | Fn::ImportValue]
```

So the Arn parser should support the following declarations and parse them correctly:

- lambda name
- Fully qualified ARN (arn:<service>:....)
- Fn::Ref <resource id>
- Fn::GetAtt <resource id>,<identifier>
- Fn::Join (containing a split arn possibly with Fn::Ref, Fn::GetAtt or Fn::ImportValue as parts)
- Fn::ImportValue
- Fn::Sub

Any additions are welcome.

**Comment by pmuens** [comment]
Thanks for updating @HyperBrain 

Here's the link to the comment mentioned above 🔝 --> https://github.com/serverless/serverless/issues/3024#issuecomment-291334434

**Comment by jliebrand** [comment]
Perhaps I'm missing something; but isn't this issue also about referencing resources from within the same stack?

I have a cognito user pool in my Resources section, and I would like to reference it as an authorizer using Fn::GetAtt but the way the code is written today, this is not possible, right?

ie this is no *just* for cross stack referencing, is it?  Or is there a way of doing what i want that I'm missing?

**Comment by HyperBrain** [comment]
This task is for a general universal ARN parser that allows specifying references as ARN string, Fn::GetAtt, Ref or whatever notations there are to reference resources. It should unify the references, may it be  event declarations or something else.
So you're completely right - the initial reason for the task was, that multiple places where in-stack resources had been referenced where/are implemented differently in the different locations with the effect that e.g. some notations work in one place but not in other places.

**Comment by jliebrand** [comment]
Ok; and to be clear; right now there's no way to define a Cognito UserPool in the Resources section and then have the functions use events that auth against that newly created user pool, since there's no way to get to the ARN of that created pool; correct?

**Comment by erikerikson** [comment]
As HyperBrain notes, ARN parser was the original thought this was created under (the stream attribute was used for both Kinesis and Dynamo streams) but it is definitely intended to be a generalized resource reference implementation.

**Comment by erikerikson** [comment]
The reason for this is current inconsistency in the implementation.  That sometimes you can use Ref or ImportValue, et cetera but not others.  For a specific case, try it and see.

**Comment by pmuens** [comment]
> As HyperBrain notes, ARN parser was the original thought this was created under (the stream attribute was used for both Kinesis and Dynamo streams) but it is definitely intended to be a generalized resource reference implementation.
> The reason for this is current inconsistency in the implementation. That sometimes you can use Ref or ImportValue, et cetera but not others. For a specific case, try it and see.

@erikerikson comments are a pretty good summary of the purpose for the `arn` parser.

@jliebrand have you used the new `cognitoUserPool` event source (released in v1.15) to achieve that? Or are you using another solution right now?

**Comment by jliebrand** [comment]
@pmuens no, I wasn't aware of any cognito event source... What I do now is first deploy my stack with the functions having simply no authorizer at all... Then once the stack is deployed for each of my stages, I add these custom vars to the top of my yml:
```
custom:
  stagingUserPool: arn:aws:cognito-idp:xxxOne
  masterUserPool: arn:aws:cognito-idp:xxxTwo
  devUserPool: arn:aws:cognito-idp:xxxThree
```

And then add these authorizers:
```
          authorizer:
            arn: ${self:custom.${opt:stage}UserPool}
```

This will obviously break if I ever remove and re-deploy a stack, so it's far from ideal

**Comment by pmuens** [comment]
Interesting solution. Thanks for sharing 👍 

We've just added the `cognitoUserPool` event source. But this only supports triggers right now...

**Comment by hassankhan** [comment]
Just chiming in to say a global ARN parser would be incredibly useful. 

With #3657 we can define user pools, but we can't reference their ARNs as Lambda authorizers. This unfortunately means either having to split a stack or deploy once without authorizers and then again after retrieving and setting the ARN 😞

**Comment by horike37** [comment]
I'm also happy it would implement this.
With my https://github.com/horike37/serverless-step-functions plugin, you need describe Lambda ARN directly, so not userfrendly..
Therefore I'd like to use a global ARN parser and would also like to reference Lambda functions ARN

**Comment by ProTip** [comment]
A general issue that we run into is that an intrinsic function of choice(GetAttr, Sub, Split, Join, Ref, Import, etc) is seemingly randomly unavailable. It feel like there may be a bit of unfortunate one-off logic for config parsing going. Will the "ARN parser" work allow the intrinsic functions to work all the places one would expect(everywhere)?

**Comment by erikerikson** [comment]
That is exactly the intent (as valid) @protip

**Comment by pmuens** [comment]
> Will the "ARN parser" work allow the intrinsic functions to work all the places one would expect(everywhere)?

@ProTip yes, that's exactly the intention of this issue / proposal (as @erikerikson also pointed out above).

The title might be a little bit misleading. I'll update it.

**Comment by pmuens** [comment]
Just a quick update on this one.

The inital implementation for a global `arn` parser can be found in this PR: https://github.com/serverless/serverless/pull/3878. The function is accessible at `this.provider.findAllCfReferences()`.

**Comment by scottsanchez** [comment]
Glad to see this is making progress. Having to hard-code ARN for cognito identity pools after sls creates them them (rather than being able to dynamically reference them) seems counter intuitive :)

See also: 

http://forum.serverless.com/t/cognito-user-identity-pools-as-serverless-yml-resource-defs/2050/8

and 

http://forum.serverless.com/t/cognito-user-identity-pools-as-serverless-yml-resource-defs/2050/9

**Comment by pmuens** [comment]
Just a quick update on this one:

https://github.com/serverless/serverless/pull/3878 which included a global `arn` parser will closed in favor of https://github.com/serverless/serverless/pull/3934 which doesn't include an `arn` parser implementation.

That's why we labeled it from `in-progress` back to `help-wanted`

(so any help here is highly welcomed! 👍)

**Comment by tobyhede** [comment]
Is anyone working on this one atm?

**Comment by rifhanakram** [comment]
Hi @pmuens 
any idea on when this feature will be released ?
- Thanks in advance

**Comment by alekbarszczewski** [comment]
Just started using serverless and referencing user pool arn was the first issue I ran into :(.

**Comment by iDVB** [comment]
@alekbarszczewski We overcame this issue by separating our "Auth" and "API" into two separate Stacks. Where the Auth stack provides CFN `Outputs` for the needed things. 
Then referencing one from the other by...
```javascript
auth-stack: my-auth-${self:custom.stage}
userPoolId: ${cf:${self:custom.auth-stack}.UserPoolId}
userPoolClientId: ${cf:${self:custom.auth-stack}.UserPoolClientId}
```

**Comment by alekbarszczewski** [comment]
@iDVB Thanks, I will try this!

**Comment by raphadko** [comment]
+1. Any updates?

**Comment by andersonjohnf** [comment]
@iDVB That worked great, thanks.  Here is my example for posterity:

In my "user" service with the auth function:
```
functions:
  auth:
    name: "${self:provider.stage}-user-auth"
    handler: "handler.auth"

resources:
  Outputs:
    LambdaAuthorizer:
      Value: {"Fn::Join": [":", ["arn:aws:lambda", {Ref: "AWS::Region"}, {Ref: "AWS::AccountId"}, "function:${self:provider.stage}-user-auth"]]}
```

In my other services:
```
functions:
  myFunction:
    handler: "handler.myFunction"
    events:
      - http:
          path: 'path/to/function'
          method: "get"
          authorizer:
            arn: "${cf:user-${self:provider.stage}.LambdaAuthorizer}"
            resultTtlInSeconds: 120
            identitySource: "method.request.header.Authorization"
            type: "token"
  otherFunction:
    handler: "handler.otherFunction"
    events:
      - http:
          path: 'path/to/function'
          method: "get"
          authorizer:
            arn: "${cf:user-${self:provider.stage}.LambdaAuthorizer}"
```

**Comment by logemann** [comment]
just stopping by to vote for the arn parser feature cause otherwise life is harder than it should be :-)

**Comment by et304383** [comment]
1.5 years later.  Not resolved.  :(

**Comment by otbe** [comment]
You can! Its not so intuitive as it could be, but its definitly possible.
As always you can augment function definitions:

```yml
functions:
  hello:
    handler: src/index.handle
    events:
      - http:
          method: get
          path: /hello
          cors: true

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: my-user-pool

   # augments the compiled function cf json
    ApiGatewayMethodHelloGet:
      Properties:
        AuthorizationType: COGNITO_USER_POOLS
        AuthorizerId:
          Ref: CognitoAuthorizer

    CognitoAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.Authorization
        Name: my-authorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [UserPool, Arn]
```

It took me a while to figure this out, maybe this should be added to the docs in the meantime?

**Comment by et304383** [comment]
@otbe this is the first useful workaround in this entire thread.  Thanks!

**Comment by jagthedrummer** [comment]
Thanks a ton for the workaround @otbe. This is way better than hard coding an ARN.

(I hope that the workaround will be unnecessary soon and that we'll be able to reference other parts of the cloudformation stack directly (or do I mean indirectly?) where the function and event is defined.

**Comment by sortegam** [comment]
@otbe I see the purpose of your example but I don't understand how you actually setup / assign the created Cognito Authorizer into the hello function. Is this really possible?

**Comment by otbe** [comment]
@sortegam 
In my example `ApiGatewayMethodHelloGet` is the [generated](https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference) Cloudfromation resource name of the hello method. Serverless merges all resources into one JSON. The content of `cloudformation-template-update-stack.json` looks like this:

```json
{
"ApiGatewayMethodHelloGet": {
  "Type": "AWS::ApiGateway::Method",
  "Properties": {
    "HttpMethod": "GET",
    "RequestParameters": {},
    "ResourceId": {
      "Ref": "ApiGatewayResourceHello"
     },
     "RestApiId": {
       "Ref": "ApiGatewayRestApi"
     },
     "ApiKeyRequired": false,
     "AuthorizationType": "COGNITO_USER_POOLS",
     "Integration": {},
      "MethodResponses": [],
      "AuthorizerId": {
         "Ref": "CognitoAuthorizer"
      }
    }
  }
}
```

**Comment by sortegam** [comment]
@otbe Aha! I didn't know that! Thank you very much!

**Comment by RobertBrewitz** [comment]
https://forum.serverless.com/t/dynamic-arn-to-cognito-authorizer/2161/6

If anyone's interested in a pointer for this issue.

**Comment by Curtis017** [comment]
Thank you @otbe, that solution is awesome!!!! To @sortegam 's  point above, I believe you forgot to add the cognito authorizer to the function in your yaml example:
```
functions:
  hello:
    handler: src/index.handle
    events:
      - http:
          method: get
          path: /hello
          cors: true
          authorizer: <--- declare authorizer for the function 
            type: COGNITO_USER_POOLS
            authorizerId: 
              Ref: CognitoAuthorizer

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: my-user-pool

   # augments the compiled function cf json
    ApiGatewayMethodHelloGet:
      Properties:
        AuthorizationType: COGNITO_USER_POOLS
        AuthorizerId:
          Ref: CognitoAuthorizer

    CognitoAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.Authorization
        Name: my-authorizer
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [UserPool, Arn]
```

**Comment by maddymaster** [comment]
@otbe thank you for the solution.

**Comment by agroff** [comment]
@otbe That worked great for getting a UserPool set up but now when I run `serverless remove` I get the error "Stack with id UserPool does not exist." Is this expected with using custom resources. If so is there any work around?

**Comment by otbe** [comment]
Mh. Can't reproduce this on our stacks. Deployed and removed several stacks last week with current sls 🤔
Maybe it's related to something different?

**Comment by agroff** [comment]
Hmmm yea I definitely broke something. I get that error no matter what I do now. I'll keep digging. Thank you!

**Comment by OndeVai** [comment]
I hate the to be the guy that whines about this wonderful open source project or the folks that selflessly contribute great work to it, but this bug is a major hinderance. Hard coding the User Pool arn is a nasty solution and having to split your Cognito into a separate stack is equally nasty (for us). It's been almost a year and still no fix. My naive question is this: can  a quick fix be put in just to get` auth:{dynamicclounfrontarn}` working for api's, then work on the grander solution later?

**Comment by orndorffgrant** [comment]
@OndeVai 

@RobertBrewitz posted this a while ago in this thread, but one of his links has broken so I'll leave this here. This solution does not require hardcoding, separate stacks, or augmenting each function in CloudFormation.

```yaml
...

functions:
  getStuff:
    handler: path/to/handler
    events:
      - http:
          path: /path/to/whatever
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

...

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: whatever
    ApiGatewayAuthorizer:
      DependsOn:
        - ApiGatewayRestApi
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: whatever
        IdentitySource: method.request.header.Authorization
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - Fn::GetAtt: [CognitoUserPool, Arn]

...
```

This is working for me with serverless 1.32.0

**Comment by amitaymolko** [comment]
Works well!!
Thanks a lot!

**Comment by RobertBrewitz** [comment]
@orndorffgrant thanks, links fixed in the forums :+1:

**Comment by michaelm88** [comment]
could you help me please , how can i create an event for S3 bucket which already exists , i dont want to overwrite it

**Comment by tbabak** [comment]
> could you help me please , how can i create an event for S3 bucket which already exists , i dont want to overwrite it

@michaelm88 this does not seem to be the right place for your question but use `serverless-plugin-existing-s3` maybe?!

**Comment by andreanaya** [comment]
After a lot of try and error, I figured that if you add a `name` prop the whole thing works. I didn't try to find why it works, to be honest. I'll leave that for @rochdev ;)

```yml
hello-world:
  handler: hello-world.handler
  events:
    - http:
        path: /hello-world
        authorizer:
          name: SharedAuthorizer
          arn:
            'Fn::ImportValue': ${self:provider.stage}-SharedAuthorizer
```
