### ISSUE TITLE
Allow for Predictable inter-Service References (`${local:...}`)

### ISSUE THREAD

**Issue by erikerikson** [serverless/serverless#3233]
# This is a Feature Proposal

Add a `local` variable type, that resolves as a reference to the file that contains it, rather than `self` which resolves to the current service.

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

The use case to be solved is cross-references in serverless services.

For example, I define:

~/svc1/serverless.yml
```
service: svc1

custom:
  svc1Version: 2
  exportSvc1ExportedResource: ${self:service}-svc1ExportedResourceName-${self:custom.svc1Version}
[...]
resources:
  Outputs:
    Svc1ExportedResource:
      Description: A resource that is exported to other services
      Value:
        Ref: Svc1Resource
      Export:
        Name: ${self:custom.exportSvc1ExportedResource}
```

To abide by the [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) principle, I don't want to copy paste the many-part export name, so I load ~/svc1/serverless.yml in a dependent service definition:

~/svc2/serverless.yml
```
service: svc2

custom:
  svc1Version: 1
  svc1: ${file(~/svc1/serverless.yml)}

provider:
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "aws:action"
       Resource:
         Fn::ImportValue: ${self:custom.svc1.exportSvc1ExportedResource}
[...]
```

Right now, the deploy of `~/svc2/serverless.yml` will fail because `${self:custom.svc1.exportSvc1ExportedResource}`, in the context of `svc2` will resolve `${self:service}` (from the `exportSvc1ExportedResource` declaration in `~/svc1/serverless.yml`) to `svc2` instead of `svc1`.  Note that It will also resolve `svc1Version` differently but that's exactly what I want (since I haven't updated my use of the API [or whatever] yet).

As a service defining an export to be used in other services, I'd love to be able to specify where the information is drawn from (i.e. the defining service or the consuming service).  I propose this could be accomplished with the following syntax (`${local:...}`):

```
  exportSvc1ExportedResource: ${local:service}-svc1ExportedResourceName-${self:custom.svc1Version}
```

This way, the right unique prefix is used but other services can choose which version of my first service to depend on.

Originally discussed in the context of https://github.com/serverless/serverless/issues/3206, https://github.com/serverless/serverless/issues/3207, and https://github.com/serverless/serverless/pull/3208.
