### ISSUE TITLE
LogGroup doesn't exist when one name is the part of another

### ISSUE THREAD

**Issue by KKomarov** [serverless/serverless#3240]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
I cant deploy this simple config. The problem happens when one function has name that is the part of another name.

* What did you expect should have happened?
Stack created.

* What was the config you used?
```
service: myservice

provider:
  name: aws
  stage: ohmydays
  region: us-east-1
  runtime: python2.7

package:
  individually: true
  include:
    - "*.py"

functions:
  omglol:
    handler: handler.lambda_handler

  omglolanother:
    handler: handler.lambda_handler
```

* What stacktrace or error message from your provider did you see?
![image](https://cloud.githubusercontent.com/assets/14128194/22890080/4bfd7112-f21c-11e6-8cc7-b8bf1596c792.png)

## Additional Data

* ***Serverless Framework Version you're using***: >=1.6.0 or cfLogs: true
* ***Operating System***: Ubuntu
