### ISSUE TITLE
Deploy fails after upgrade to 1.7.0

### ISSUE THREAD

**Issue by seanohollaren** [serverless/serverless#3246]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

After upgrading serverless to 1.7.0 (from 1.4.0), I'm no longer able to deploy existing functions.  It seems to hinge around the fact that *Serverless might not be currently handling log group removals or log group updates properly*.

When I attempt to deploy an existing function, I get this error message: 

```
Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: HelloLogGroup
     - /aws/lambda/dummyPost-dev-hello already exists.
```

The first thing I tried was to run `sls remove` to tear down the stack, which reported that it successfully removed the stack.

When I then tried to run `sls deploy` again, I got the same error as above.

After manually checking the CloudWatch log groups, I can see that the `/aws/lambda/dummyPost-dev-hello` log group still exists and *was not* removed by the `sls remove` command.

I manually removed the log group and was then able to successfully deploy with `sls deploy`.

* What did you expect should have happened?

I would expect that Serverless removes the cloudwatch log group.

* What was the config you used?

```yml
service: dummyPost

provider:
  name: aws
  role: arn:aws:iam::514220683169:role/analyticsIntakePoC-dev-us-east-1-lambdaRole
  runtime: nodejs4.3
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
    environment:
      destinationStreamName: ${file(config/dev.yml):processingStreamName}
```

* What stacktrace or error message from your provider did you see?

```
Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: HelloLogGroup
     - /aws/lambda/dummyPost-dev-hello already exists.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.3.1
     Serverless Version: 1.7.0
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.7.0
* ***Operating System***: OS X 10.10.5
