### ISSUE TITLE
Problem to deploy when removing a schedule from a lambda function

### ISSUE THREAD

**Issue by christiansaiki** [serverless/serverless#3255]
# This is a Bug Report

## Description
I've edited my serverless.yml file to remove a schedule
Then I've tried to deploy with sls deploy -v but I've got the following message
Serverless Error ---------------------------------------
 An error occurred while provisioning your stack: StartInstancesEventsRuleSchedule1- <my_schedule>
 exists in stack arn:aws:cloudformation:us-east-1:...
What is the proper way to remove a schedule?
Thanks in advance

For bug reports:
* What went wrong?
The deploy of the service didn't go through

* What did you expect should have happened?
I was expecting to have my service deployed without the schedule that was supposed to be deleted

* What was the config you used?
```
service: lambda-jobs 
plugins:
  - serverless-plugin-include-dependencies
provider:
  name: aws
  runtime: nodejs4.3

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
   - Effect: Allow
     Action:
       - ec2:StartInstances
       - ec2:StopInstances
       - ec2:DescribeInstances
       - ec2:DescribeInstanceStatus
       - ec2:CreateNetworkInterface
       - ec2:DescribeNetworkInterfaces
       - ec2:DeleteNetworkInterface
     Resource: "*"
     Condition:
       StringEquals:
         ec2:Region: us-east-1

   - Effect: Allow
     Action:
       - kms:Decrypt
     Resource: "*"


# you can define service wide environment variables here
  environment:
   B_ENV: lambda-jobs
   B_PRODUCTION: true

functions:
  startInstanceAndEtl:
    vpc:
      securityGroupIds:
        - my-sg
      subnetIds:
        - my-subnet
    handler: functions/startInstanceAndEtl.startInstanceAndEtl
    timeout: 120
    events:
    - schedule:
        name: 'startInstanceAndEtl_atomic_events'
        enabled: true
        description: 'startInstanceAndEtl_atomic_events'
        rate: cron(30 7 * * ? *)
        input:
          databaseName: 'atomic_events'
          clusterName: ingestor-only-atomic_events
          periodicity: default
    - schedule:
        name: 'startInstanceAndEtl_sales_per_marketing_channel_everyday'
        enabled: true
        description: 'startInstanceAndEtl_sales_per_marketing_channel_everyday'
        rate: cron(50 8 * * ? *)
        input:
          databaseName: 'sales_per_marketing_channel'
          clusterName: ingestor-only-sales_per_marketing
          periodicity: default
  startInstances:
    vpc:
      securityGroupIds:
        - my-sg
      subnetIds:
        - my-subnet
    handler: functions/startInstance.startInstances
    timeout: 120
    events:
    - schedule:
        name: 'start_ingestor_only_fact_sales_saturday'
        enabled: true
        description: 'start_ingestor_only_fact_sales_saturday'
        rate: cron(50 9 ? * SAT *)
        input:
          clusterName: ingestor_only_fact_sales
          periodicity: Saturday
      #fact_sale_per_sku_per_store
    - schedule:
        name: 'start_ingestor_only_fact_sale_per_sku_per_store_sun_to_fri'
        enabled: true
        description: 'start_ingestor_only_fact_sale_per_sku_per_store_sunday_through_friday'
        rate: cron(5 9 ? * SUN-FRI *)
        input:
          clusterName: ingestor_only_fact_sale_per_sku_per_store
          periodicity: default

# you can add CloudFormation resource templates here
#resources:
Resources:
 NewResource:
   Type: AWS::S3::Bucket
   Properties:
     BucketName: lambda-jobs
```

* What stacktrace or error message from your provider did you see?
Serverless Error ---------------------------------------
An error occurred while provisioning your stack: StartInstancesEventsRuleSchedule1- <my_schedule>
exists in stack arn:aws:cloudformation:us-east-1:...

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.1
* ***Operating System***: Elementary OS Freya
