### ISSUE TITLE
s3 events can't refer to existing bucket

### ISSUE THREAD

**Issue by christophgysin** [serverless/serverless#3257]
# This is a Bug Report

## Description

When specifying an s3 event, serverless will always create a new bucket. I would like to be able to specify an existing bucket defined in resources, e.g.:

```yaml
functions:
  myfunction:
    handler: handler.handler
    events:
      - s3:
          bucket: mybucket

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mybucket
```

## Additional Data

Currently, that causes an error, because `mybucket` ends up being defined twice in the CloudFormation template.

```bash
$ serverless deploy
```
```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading service .zip file to S3 (3.85 KB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........................Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: S3BucketServerlessexample
     - mybucket already exists
     in stack arn:aws:cloudformation:us-east-1:872755943855:stack/example-dev/06bf9a10-f42b-11e6-a0f4-500c221b72d1.
```

**Comment by eahefnawy** [comment]
Thanks for opening this up @chris-olszewski 😊 .... I think your usecase is not really an "existing" bucket, but rather a new bucket that you're creating via custom resources.

You can merge any new configuration for any of our core resources (ie the S3 event resource) by adding a new resource under the resources section **with the same core logical id**. The framework will merge the default configuration and your updates together. So that means you can do the following:

```yml
functions:
  myfunction:
    handler: handler.handler
    events:
      - s3: something

resources:
  Resources:
    S3BucketSomething:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: overwrittenBucketName
```

Notice the same logical ID. The bucket name should end up with `overwrittenBucketName` instead of `something`

**Comment by christophgysin** [comment]
I see. While it's not strictly necessary as your example demonstrates, I think it's more obvious to link the two by bucket name.

The example above relies on the way logical IDs are formed. If that would ever change, it will break :(

**Comment by eahefnawy** [comment]
great point! which is why we have a naming standard for logical IDs and any changes there would be listed as a breaking change and users would be warned firsthand

**Comment by christophgysin** [comment]
Alright, I'm convinced ;)

Could we document this behvoiur in the S3 events? Or is it already documented, and I just missed it?

**Comment by ironmanwaring** [comment]
@eahefnawy Is there any additional configuration needed for the example you provided to work?  I have a bare bones example that follows the convention and I consistently get the following error from CloudFormation:  'unable to validate the following destination configurations'

(possibly related to #3038)

I'm using 1.7.0 if that makes a difference

**Comment by pmuens** [comment]
@christophgysin you can find the CloudFormation resource reference here: https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference

@ironmanwaring could you please share the `serverless.yml` so that we can look into your configuration? Thanks!

**Comment by ironmanwaring** [comment]
@pmuens sure thing, thanks for following up.  I've simplified my configuration to the point where I don't need to specify the bucket in the resources section - my ultimate use case for doing so is to use the bucket as a static site and trigger actions when the files there change.  I've run this simple configuration several times now to try and identify the root cause.

Anyways this gist shows that even without site configuration or anything else the issue is still present: [serverless.yml](https://gist.github.com/ironmanwaring/a33b58b5ad3386c88196666a4bbebd6c)

I've tried many variations of the configuration with the same results and I'm sure I must be missing something obvious - apologies and thanks in advance

**Comment by pmuens** [comment]
Hey @manwaring 
thanks for the `serverless.yml` file.

Serverless will create a `testSite` S3 bucket for you. The resource logical id for this bucket is `S3BucketTestsite` (here's the table with the rules Serverless uses to generate those ids: https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/resources.md#aws-cloudformation-resource-reference).

I think you've misspelled the resource logical id since it's `S3BucketTestsite` and not `S3BucketTestSite`.

**Comment by manwaring** [comment]
@pmuens Thanks for the quick response.  The naming convention doesn't seem to be the problem, still getting the same error message.  I'm going to spend more time looking at this over the weekend, trying different versions and seeing what CloudFormation is being produced.  If I can't figure it out I'll create a new issue instead of continuing this one.

Thanks again for your help!

**Comment by pmuens** [comment]
@manwaring thanks for the quick update! 👍 

Would be nice if you'll share your insights here.

Sad to hear that the naming convention was not the issue 🤔 ...

**Comment by manwaring** [comment]
@pmuens 

It looks like the issue is caused by missing DependsOn attributes in the generated CloudFormation template.  I created a repo for testing this with different versions of the serverless framework and different serverless.yml configurations here: [serverless-bucket-events](https://github.com/manwaring/serverless-bucket-events)

If I try to use the configuration @eahefnawy shared above I consistently get a 'unable to validate the following destination configurations' error message.  See [relevant issue guide from aws here](https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/)

From the guide the issue is caused by circular dependencies, and sure enough if I create a bucket in the resources section of the [serverless.yml](https://github.com/manwaring/serverless-bucket-events/blob/master/serverless.yml) and manually associate it with a function defined there using the correct DependsOn configuration the bucket is created just fine and events trigger correctly.

I included the .serverless stack files in the repo for ease of looking at.  Also you can compare the [relevant-cloudformation-doesntwork.json](https://github.com/manwaring/serverless-bucket-events/blob/master/relevant-cloudformation-doesntwork.json) and [relevant-cloudformation-works.json](https://github.com/manwaring/serverless-bucket-events/blob/master/relevant-cloudformation-works.json) files to see that the only difference between what I manually configured and what was generated is the missing DependsOn values.

**Comment by manwaring** [comment]
I'm not sure if the framework supports DependsOn or not - I haven't seen it in any of the generated files in my projects.

The use case I'm trying to solve for with this configuration is being able to specify more of the s3 properties than what I can using the inline event syntax.  While I haven't seen anyone else trying to implement this for static sites like I am, it looks like others are dealing with the same underlying issue (how to specify additional s3 properties on the buckets created through serverless events.   #3309 for example

If there's a better place to continue this discussion please let me know - if there's a consensus on what the resolution for this category of request is I'd like to help implement it

**Comment by pmuens** [comment]
Thanks for the detailed response @manwaring 

🤔 Yes, that sounds like a good use case for `DependsOn`. We had similar race conditions in the past...

You could use the `resources` section to add those. Here's a (not related) issue where something similar was done: https://github.com/serverless/serverless/issues/3339#issuecomment-285591096

**Comment by yoyeung** [comment]
For this issue. Is because someone in the work they are using the same name of bucket.
(I don't know why AWS have this logic)
So if u can try to create a bucket in AWS bucket console, u will see this error msg.

**Comment by Lepozepo** [comment]
@pmuens @manwaring has the use case on being able to modify S3 properties under `Resources` been resolved? Or has it moved to a new issue?

**Comment by pmuens** [comment]
@Lepozepo AFAIK this is still an issue and no separate issue was opened so far...

**Comment by Lepozepo** [comment]
Opened a new issue [here](https://github.com/serverless/serverless/issues/3448) guys for anyone that's interested ^_^

**Comment by pmuens** [comment]
Thanks for opening @Lepozepo 👍

**Comment by kiwifellows** [comment]
Hi,

Just a question as I'm coming across an issue with using S3 buckets as an event for a Lambda function. When deploying the S3 bucket hasn't been created and the trigger isn't showing in the Lambda function. Can you please clarify if this is the correct process or do I need to define an S3 bucket in the resources section. BTW I've defined other events that are API Gateway and they get created from the deploy process and work perfectly.

I've defined a function with an event to a new bucket which I expect to be created as part of the deploy.

``` yaml

service: cloudAPI

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2
  memorySize: 256
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to EC2
        - ec2:*
      Resource: "*"
    - Effect: Allow
      Action: # Gives permission to EC2
        - sts:AssumeRole
      Resource: "arn:aws:iam::*:role/*-TeemOps-*"

functions:
  ec2Task:
    handler: ec2.ec2Task
    description: Launch Ec2 Task (start, stop, terminate etc...)
    timeout: 6
    memorySize: 512
    events:
      - s3:
        bucket: s3qteemopsapidev
        event: s3:ObjectCreated:*
        rules:
          - prefix: ec2/
          - suffix: *
```

**Comment by pmuens** [comment]
Hey @kiwifellows that behavior is not something to expect.

Seems like your YAML indentation for the `s3` event is wrong. Could you update this:

```yml
functions:
  ec2Task:
    handler: ec2.ec2Task
    description: Launch Ec2 Task (start, stop, terminate etc...)
    timeout: 6
    memorySize: 512
    events:
      - s3:
        bucket: s3qteemopsapidev
        event: s3:ObjectCreated:*
        rules:
          - prefix: ec2/
          - suffix: *
```

to look like this:

```yml
functions:
  ec2Task:
    handler: ec2.ec2Task
    description: Launch Ec2 Task (start, stop, terminate etc...)
    timeout: 6
    memorySize: 512
    events:
      - s3:
          bucket: s3qteemopsapidev
          event: s3:ObjectCreated:*
          rules:
            - prefix: ec2/
            - suffix: *
```

and try again? Thanks!

**Comment by kiwifellows** [comment]
Hi @pmuens thanks!

**Comment by razbomi** [comment]
@pmuens Please help... I am not sure why this is closed, maybe there is another ticket regarding issue (if there is pease point me to it)... 

But, If I try to use "logical id" in the events section of the bucket, the generated function permission refers to the local id instead of the amazing bucket name.

Eg.
```
custom:
  bucket: myawsomelyamazingpartyhardbucketwhatevs

functions:
  hello:
    handler: handler.hello
    description: Organises amazing hello upload bucket parties
    events:
      - s3: upload

resources:
  Resources:
    S3BucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
```

The generated cf includes `upload` in the arn instead of my bucket name:
```
    "HelloLambdaPermissionUploadS3": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "HelloLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": "s3.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:aws:s3:::upload"
            ]
          ]
        }
      }
    },
```

This causes cf to spit out the highly informative message, like one that only a true enterprise java developer could ever come up with `Unable to validate the following destination configurations` on the  `S3BucketUpload` resource.

I thought this maybe related, any ideas or suggestions?

**Comment by pmuens** [comment]
Hey @razbomi thanks for getting back.

A quick solution would be to overwrite the `HelloLambdaPermissionUploadS3` resource as well.

Something like (untested):

```yaml
resources:
  Resources:
    S3BucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
  HelloLambdaPermissionUploadS3:
    Properties:
      SourceArn: arn:aws:s3:::${self:custom.bucket}
```
