### ISSUE TITLE
BUG: deploy from Semaphore CI fails (accuses bad yml file)

### ISSUE THREAD

**Issue by IgorRocha** [serverless/serverless#3262]
# Bug Report

## Description

* What went wrong?
Deploying a new service resulted in YAML error. The deploy was made through a Semaphore CI build. The same service can be successfully when running sls deploy locally.
* What did you expect should have happened?
The new service should be deployed correctly, as the YML file I'm using has the exact same structure from the ones I've already deployed through Semaphore CI. Also, checking my YAML file with  https://www.json2yaml.com/ shows that the syntax is correct.
* What was the config you used?
Here is my serverless.yml file (the ******* parts are placeholders, used to hide sensitive business info)

```
frameworkVersion: "=1.1.0"
service: testnew-service

provider:
  name: aws
  runtime: python2.7
  iamRoleARN: arn:aws:iam::********************
  stage: ${opt:stage, self:provider.default_stage}
  default_stage: dev
  region: us-east-1
  memorySize: 128

custom:
  writeEnvVars: ${file(./env/env.yml)}
plugins:
 - serverless-plugin-write-env-vars

# you can add packaging information here 
package:
  include:
    - vendored/*
  exclude:
    - tests/*
#  artifact: my-service-code.zip

_definitions:
  auth: &auth
    Properties:
      AuthorizationType: NONE
      RequestParameters:
        method.request.header.*********: integration.request.header.**********
  vpc: &fixed_ip_vpc
    securityGroupIds:
    - sg-*******
    subnetIds:
    - subnet-*******
    - subnet-********
  #_vpc: &_db_vpc
    #- "None"
  cors: &cors
    origins:
    - '*'
    headers:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - ********

functions:
# CSV upload function, triggered directly by an S3 upload
  clientsBatchCreateInternal:
    handler: clientsBatchCreateInternal.handler
    events:
      - s3:
          bucket: ${self:provider.stage}-clients-csv-******
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv


# you can add CloudFormation resource templates here
resources:
```

* What stacktrace or error message from your provider did you see?
Semaphore CI stacktrace:
```
Serverless: Wrote .env file to /tmp/deploy_serverless_12_24086/.env
Serverless: Packaging service…
Serverless: Deleted .env file from /tmp/deploy_serverless_12_24086/.env
Serverless: Uploading CloudFormation file to S3…
Serverless: Uploading service .zip file to S3…
Serverless: Updating Stack…
Serverless: Checking Stack update progress…
...Finished installation
Finished installation
 
  Y A M L Exception --------------------------------------
 
     end of the stream or a document separator is expected
     in "/tmp/deploy_serverless_13_8076/serverless.yml" at
     line 2, column 1:
    _definitions:
    ^
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.2.6
     Serverless Version: 1.1.0
 
Serverless: Wrote .env file to /tmp/deploy_serverless_11_31868/.env
Serverless: Packaging service…
..
Serverless: Stack update finished…
Serverless: Removing old service versions…
```

Similar or dependent issues:
* Couldn't find any, only this Serverless forum post http://forum.serverless.com/t/issue-with-yml-file/943

## Additional Data

* ***Serverless Framework Version you're using***: 1.1.0
* ***Operating System***: linux
* ***Provider Error messages***:

>   Y A M L Exception --------------------------------------
>  
>      end of the stream or a document separator is expected
>      in "/tmp/deploy_serverless_13_8076/serverless.yml" at
>      line 2, column 1:
>     _definitions:
>     ^
>  
>      For debugging logs, run again after setting SLS_DEBUG env var.
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>  
>      Please report this error. We think it might be a bug.
