### ISSUE TITLE
Version's names get set as "Invalid Date" when I deploy

### ISSUE THREAD

**Issue by joaqo** [serverless/serverless#3264]
# Bug Report

## Description

* What went wrong?
The new version of serverless supports lambda versions. On each deploy a new version is created. For some reason the version names are always "Invalid Date".

![screen shot 2017-02-22 at 1 03 19 pm](https://cloud.githubusercontent.com/assets/14966348/23220012/5bfa9164-f8ff-11e6-953a-64ed9a2a04a5.png)

* What did you expect should have happened?
Some automated name, probably the date-time
* What was the config you used?

```
service: some_service_name

provider:
  name: aws
  runtime: python2.7
  iamRoleStatements:  # We need these to work in a custom VPC
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  stage: dev
  region: us-west-2
  profile: default
  timeout: 60
  vpc:
      securityGroupIds:
        - sg-XXXXXX
      subnetIds: 
        - subnet-XXXXXXXX

functions:
  orders:
    handler: handler.receive_order
```
* What stacktrace or error message from your provider did you see?
None

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.1
* ***Operating System***: MacOS 10.12.1
* ***Stack Trace***:
* ***Provider Error messages***:
