### ISSUE TITLE
Duplicated mapping key in serverless.yml

### ISSUE THREAD

**Issue by armen52** [serverless/serverless#3277]
# This is a Bug Report

## Description

**What went wrong?**

Trying to deploy my project for the first time. I did my best to follow the docs to define two DynamoDB tables as resources, and grant the appropriate permissions. This is my first time using serverless and CloudFormation.

Running the deploy command resulted in an error about a duplicate mapping key, seemingly to do with the attempt to grant IAM permissions to both table resources. See below for details.

**What did you expect should have happened?**
Expected the project to be deployed, with appropriate permissions set.

**What was the config you used?**

Here is the provider section of my serverless.yml file:
```
provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2
  memorySize: 128
  versionFunctions: false
  environment:
    ARMTOENG_TABLE: aaas-Dynamodb-${opt:stage, self:provider.stage}-ArmToEng
    ENGTOARM_TABLE: aaas-Dynamodb-${opt:stage, self:provider.stage}-EngToArm
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ARMTOENG_TABLE}"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ENGTOARM_TABLE}"

```
**What stacktrace or error message from your provider did you see?**
None.

**Similar or dependent issues:**
* Could not find any.

## Additional Data

* ***Serverless Framework Version you're using***: 1.7.0
* ***Operating System***: OS X 10.11.6
* ***Stack Trace***: 
```
  Y A M L Exception --------------------------------------
 
     duplicated mapping key in "/Users/armen/Projects/aaas/serverless.yml"
     at line 39, column 123:
     ... der.environment.ENGTOARM_TABLE}"

                                             ^
  Stack Trace --------------------------------------------
 
YAMLException: duplicated mapping key in "/Users/armen/Projects/aaas/serverless.yml" at line 39, column 123:
     ... der.environment.ENGTOARM_TABLE}"
                                         ^
    at generateError (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readBlockMapping (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1066:9)
    at composeNode (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockSequence (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:925:5)
    at composeNode (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readBlockMapping (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
    at composeNode (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readDocument (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
    at loadDocuments (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at Object.load (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
    at Utils.readFileSync (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/classes/Utils.js:99:23)
    at YamlParser.parse (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/lib/classes/YamlParser.js:19:40)
From previous event:
    at __dirname (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/bin/serverless:15:28)
    at Object.<anonymous> (/Users/armen/.nvm/versions/node/v7.5.0/lib/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

* ***Provider Error messages***:
None

**Comment by pmuens** [comment]
Hey @armen52 thanks for opening this.

At first glance it seems like you can resolve this issue by separating the `iamRoleStatements` like this:

```yml
provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2
  memorySize: 128
  versionFunctions: false
  environment:
    ARMTOENG_TABLE: aaas-Dynamodb-${opt:stage, self:provider.stage}-ArmToEng
    ENGTOARM_TABLE: aaas-Dynamodb-${opt:stage, self:provider.stage}-EngToArm
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ARMTOENG_TABLE}"
  - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.ENGTOARM_TABLE}"
```
