### ISSUE TITLE
Removing private: true from function does not change it's state

### ISSUE THREAD

**Issue by ardeshireshghi** [serverless/serverless#3285]
# Bug Report 

## Description

* What went wrong?
I defined a lambda function and an API gateway endpoint associated with it. Initially the `private` key was set to `true`. I deployed the API with that setting. Later on, I decided to make it none private. I assumed this will happen by removing the key. However, after deployment I realised that I can still not access the endpoint receiving:
```
{"Message":"User is not authorized to access this resource"}
```
* What did you expect should have happened?
I expected that by removing the `private:true` it turns into public.
* What was the config you used?
`import` is the name of the function:

```
import:
    handler: handler.importUserHandler
    events:
      - http:
          path: users/import
          method: post
          integration: lambda
          authorizer: authGateway
          cors: true 
```

## Additional Data
I finally fixed it by adding `private: false`.

* ***Serverless Framework Version you're using***:
1.6.1
* ***Operating System***:
Mac OS
