### ISSUE TITLE
Allow Stream event source to reference resources in template

### ISSUE THREAD

**Issue by e-r-w** [serverless/serverless#3290]
# This is a Feature Proposal

Allow Stream event source to reference resources in cf template

## Description

Encountered a case where we were creating a Dynamo table in our `serverless.yml`, and wanted to reference the stream created with the table as an event source for a function:

```yml
resources:
  Resources:
    dynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        # ...etc
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  myFn:
    handler: myHandler.myFn
    events:
      - stream: ???? 
     # Dynamo stream ARNs take the form of 
     # arn:aws:dynamodb:[region]:[account]:table/[table name]/stream/[timestamp], 
     # the timestamp making it impossible to reference,
     # even with the region/account/table name available
```

The issue is at the time of creating the event source mapping, the event source mapping template expects a string for the ARN:

```js
const streamTemplate = `
  {
    "Type": "AWS::Lambda::EventSourceMapping",
    "DependsOn": ${dependsOn},
    "Properties": {
      "BatchSize": ${BatchSize},
      "EventSourceArn": "${EventSourceArn}", // can't do { "Ref": "myKinesisStream" } for example
      "FunctionName": {
        "Fn::GetAtt": [
          "${lambdaLogicalId}",
          "Arn"
        ]
      },
      "StartingPosition": "${StartingPosition}",
      "Enabled": "${Enabled}"
    }
  }
`;
```

Could possibly have a special key in the `stream` object:

```yml
functions:
  myFn:
    handler: myHandler.myFn
    events:
      - stream:
        dynamoTable: myTable
      - stream:
        kinesisStream: myStream
```

That outputs a `Fn::GetAtt` or `Fn::Ref` for the corresponding stream resources ARN instead of a hardcoded string? happy to submit a PR if the proposal looks good

EDIT: Intrinsic functions should work with the generated policy statement too
