### ISSUE TITLE
Support cloudformation intrinsic function reference for SNS event

### ISSUE THREAD

**Issue by gertjvr** [serverless/serverless#3295]
# This is a Feature Proposal

## Description
Allow aws sns event definitions to use [cloudformation intrinsic function references](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) to refer to an existing resource in the cloudformation template.

```yaml
functions:
  consumer:
    handler: consumer.handler
    environment:
      SQS_QUEUE_URL:
        Ref: TaskQueue
      WORKER_LAMBDA_FUNCTION_NAME:
        Fn::GetAtt:
          - WorkerLambdaFunction
          - Arn
    events:
      - schedule: rate(1 hour)
      - sns:
          Fn::GetAtt:
            - TaskNotification
            - Arn
        
resources:
  Resources:
    TaskNotification:
      Type: AWS::SNS::Topic
      Properties: 
        TopicName: ${{self:service}}-${{self:provider.stage}}-task-notification
        Subscription:
          SNS Subscription
```

For feature proposals:
Normalized resource names is making it hard to refer to resource created by the serverless template, its really brittle at the moment and can get out of sync very quickly.
Using intrinsic function reference will allow you can generate the name in the resources section and use it to create the sns subscription, without any magic strings.

| AWS Resource          |  Name Template                                          | Example                       |
|---                    |---                                                      | ---                           |
|SNS::Topic | SNSTopic{normalizedTopicName} | SNSTopicSometopic |
|SNS::Subscription | {normalizedFunctionName}SnsSubscription{normalizedTopicName} | HelloSnsSubscriptionSomeTopic |
