### ISSUE TITLE
S3 Bucket Object Lifecycle support

### ISSUE THREAD

**Issue by camhart** [serverless/serverless#3308]
# This is a Feature Proposal

## Description
When creating S3 buckets using the s3 event, there's no support to define lifecycle rules for the objects stored within that bucket.

From serverless.yml:
```
functions:
  createThumbnails:
    handler: handler.createThumbnail
    timeout: 10
    memorySize: 128
    events:
      - s3:
          bucket: ${self:provider.stage}-supercoolsoftware-images
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg
```

I would like to add something like lifecycle as a property to the s3 object which defines the objects lifecycle in that s3 object.

Similar or dependent issues:
Not that I could find
