### ISSUE TITLE
Support IoT Things in Serverless

### ISSUE THREAD

**Issue by deathweaselx86** [serverless/serverless#3316]
# This is a Feature Proposal

It would be really useful to be able to manage IoT Things in serverless.yml.

## Description

I am currently working on a project where I am connecting AWS Lambdas, IoT events, and IoT Things. It would be nice if I could push as much Thing configuration and management into serverless.yml as possible rather managing it manually in AWS.

I am not sure what config would look like, but maybe like this:
```
  Resources:
    MyThing:
      Type: AWS::IoT::Thing
      Properties:
        ThingName: "Lightbulb"
        Attributes:
          Model: "foo"
          Wattage: "75"
```

**Comment by johncmckim** [comment]
@deathweaselx86 the configuration in the `Resources` section of `serverless.yml` is plain CloudFormation.

You should just be able to use the `AWS::IoT::Thing` CloudFormaation resource. See [the docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-thing.html).

For example
```yaml
Resources: 
  MyThing: 
    Type: "AWS::IoT::Thing"
    Properties: 
      ThingName: Lightbulb
      AttributePayload: 
        Attributes: 
          Model: foo
          Wattage: 75
```

Let me know if that isn't what you are looking for or if you have some questions.
