### ISSUE TITLE
Code is packaged differently in deploy function vs deploy

### ISSUE THREAD

**Issue by jdbevan** [serverless/serverless#3320]
# This is a Bug Report

## Description

* What went wrong?

`serverless deploy function` generated a different ZIP compared to `serverless deploy`:

```
$ serverless deploy --stage dev --noDeploy -v                                                                                                                                                    [16:09:26]
Serverless: Bundling with Webpack...
Time: 6937ms
                    Asset    Size  Chunks                    Chunk Names
modules/sync-scheduler.js  885 kB       0  [emitted]  [big]  main
Serverless: Packaging service...
Serverless: Did not deploy due to --noDeploy

$ serverless deploy function -f schedule --stage dev -v
Serverless: Deploying function: schedule...
Serverless: Packaging function: schedule...
Serverless: Uploading function: schedule (16.65 MB)...
^C
```

* What did you expect should have happened?

Packaging of an individual function to be consistent regardless of whether that function is deployed individually or with the whole service. The output above shows that Webpack wasn't used to do the bundling during the individual function packaging.

In this instance, deploying the whole service generates a ZIP with size 259KB but deploying the individual function generates a huge 17MB file!

* What was the config you used?

```yaml
service: jons-sync-scheduler

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2
  profile: product
  environment:
    DISPATCHER_URL: ${self:custom.${opt:stage}DispatcherUrl}
    PRODUCTION: ${self:custom.${opt:stage}Production}

plugins:
  - serverless-webpack

custom:
  devDispatcherUrl:  'http://localhost:5050'
  devProduction:      false

functions:
  schedule:
    handler: modules/sync-scheduler.handle
    events:
      - schedule: rate(1 minute)
```

This is my webpack config:
```js
const webpack = require('webpack');

const config = {
    context: __dirname + "/app",

    // Instead of browser
    target: "node",
    entry: './modules/sync-scheduler.js',
    output: {
        libraryTarget: 'commonjs',
        path: './.webpack/',
        filename: 'modules/sync-scheduler.js'
    },

    externals: ['aws-sdk'],

    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [{
                    loader: 'babel-loader',
                    options: {
                        presets: [["es2015", { "modules": false }]]
                    }
                }]
            }
        ]
    },

    plugins: [
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            mangle: false
        })
    ]
};

module.exports = config;
```

Here's my package.json:
```json
{
  "name": "jons-sync-scheduler",
  "version": "1.0.0",
  "dependencies": {
    "request": "^2.79.0"
  },
  "devDependencies": {
    "aws-sdk": "^2.7.13",
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-preset-es2015": "^6.22.0",
    "serverless": "^1.7.0",
    "serverless-webpack": "1.0.0-rc.4",
    "webpack": "^2.2.1"
  }
}
```

* What stacktrace or error message from your provider did you see?

No stacktrace or error, just a much larger ZIP file than expected because serverless had bundled all node_modules into the file.

Similar or dependent issues:
* #2409 might be related to this, I'm not 100% sure

## Additional Data

* ***Serverless Framework Version you're using***:
1.8.0

* ***Operating System***:
macOS Sierra 10.12.3

* ***Stack Trace***:
none

* ***Provider Error messages***:
none
