### ISSUE TITLE
Having an event only for prod stage

### ISSUE THREAD

**Issue by chrishiste** [serverless/serverless#3323]
# This is a Bug Report

## Description

I'm would like to use a schedule event on a function but only on the production stage. I'm trying to do something like that : 

    functions:
        myfunction:
            handler: myfunction.handler
                stage: production
                    events:
                         - schedule: cron(0 15 * * ? *)

Is there a way to do that ? Thanks a lot 

## Additional Data

* ***Serverless Framework Version you're using***: 1.5.1
* ***Operating System***: OS X 10.12

**Comment by andymac4182** [comment]
I believe you could use the variable system to load nothing into events for every stage other than production.

**Comment by Leomel** [comment]
👍

**Comment by chrishiste** [comment]
Ok thanks a lot ! I'm gonna check it out

**Comment by chrishiste** [comment]
Hello again, I've been trying to use the variable system but even though it seems really powerful I couldn't find a way to do what you said. It seems that there is no way to do an if statement like : 
if ${opt:stage} == 'prod', I could also do it from JS and references it like they show in the doc but then I don't know which stage I'm deploying too. Did you already do something similar ? Sorry, I'm fairly new to Serverless

**Comment by buggy** [comment]
@chrishiste I don't have time to test it at the moment but it will look something like:

```yaml
custom:
  stage: "${opt:stage, self:provider.stage}"
  prod:
    schedule:
       - schedule: cron(0 15 * * ? *)
  dev:
    schedule:

functions:
    myfunction:
        handler: myfunction.handler
            stage: production
                events: ${self:custom.${self:custom.stage}.schedule}        
```

That way it loads `custom.prod.schedule` when you're on deploying to production and `custom.dev.schedule` when you're deploying to development.

**Comment by chrishiste** [comment]
THANKS A LOT! I actually didn't understood the variable system but now it's good

In case someone wants to do something similar this worked for :

**Comment by chrishiste** [comment]
THANKS A LOT! I didn't really understood the variable system until now

If anyone is looking to do something similar that's how I did it : 

```yaml
custom:
  stage: "${opt:stage, self:provider.stage}"
    production:
      schedule: cron(0 15 * * ? *)
   dev:
      schedule:

functions:
   myFunction:
     handler: myFunction.handler
     events:
       - schedule: ${self:custom.${self:custom.stage}.schedule}
```

Just make sure you pass "--stage" and not "-s"

**Comment by pmuens** [comment]
Nice! Thanks for helping and thanks for posting the solution so that others can use it as well!

**Comment by ruipaulo** [comment]
Maybe this could be added to the main schedule documentation, I think it is a quite common use case to only have the schedular running for the production lambda.

**Comment by oligirling** [comment]
Could also use `enabled` to turn them on or off for different stages

```
functions:
  fetch:
    handler: handler.fetch
    events:
    - schedule:
        rate: rate(1 minute)
        enabled: ${self:custom.scheduleEnabled.${self:provider.stage}}

custom:
  scheduleEnabled:
    prod: true
    dev: false
    local: false
```

**Comment by juanilarregui** [comment]
> Could also use `enabled` to turn them on or off for different stages
> 
> ```
> functions:
>   fetch:
>     handler: handler.fetch
>     events:
>     - schedule:
>         rate: rate(1 minute)
>         enabled: ${self:custom.scheduleEnabled.${self:provider.stage}}
> 
> custom:
>   scheduleEnabled:
>     prod: true
>     dev: false
>     local: false
> ```

Is this confirmed to work, with booleans? Because it seems that booleans are not allowed, giving `Trying to populate non string value into a string...` error.

**Comment by arliber** [comment]
@juanilarregui I have a similar issue when I write `enabled: false` it does deploy but I can see that the CloudWatch event is still enabled in the AWS Console. 

Have you found a way to make it work?

**Comment by oligirling** [comment]
I dont seem to get any issues with the code I posted above. Could you post a copy of what your doing?

**Comment by steadweb** [comment]
> Could also use `enabled` to turn them on or off for different stages
> 
> ```
> functions:
>   fetch:
>     handler: handler.fetch
>     events:
>     - schedule:
>         rate: rate(1 minute)
>         enabled: ${self:custom.scheduleEnabled.${self:provider.stage}}
> 
> custom:
>   scheduleEnabled:
>     prod: true
>     dev: false
>     local: false
> ```

This doesn't disable the schedule, it deploys though.

**Comment by juancarlosortizr** [comment]
> 

doesn't work for me. Says the indentation isn't correct, and I can't get the indentation to work no matter what I do to it

**Comment by juancarlosortizr** [comment]
> THANKS A LOT! I didn't really understood the variable system until now
> 
> If anyone is looking to do something similar that's how I did it :
> 
> ```yaml
> custom:
>   stage: "${opt:stage, self:provider.stage}"
>     prod:
>       schedule: cron(0 15 * * ? *)
>    dev:
>       schedule:
> 
> functions:
>    myFunction:
>      handler: myFunction.handler
>      events:
>        - schedule: ${self:custom.${self:custom.stage}.schedule}
> ```
> 
> Just make sure you pass "--stage" and not "-s"

doesn't work for me. Says the indentation isn't correct, and I can't get the indentation to work no matter what I do to it

**Comment by JoshCoady** [comment]
You can do this using params which will allow you to set a default and the only override the default for the stages that need it to be different.
```yaml
params:
  default:
    enableSchedule: false
  prod:
    enableSchedule: true

functions:
  myFunc:
    handler: handlers.myFunc
    events:
      - schedule:
          rate: cron(5/15 * * * ? *)
          enabled: ${param:enableSchedule}
```
