### ISSUE TITLE
Specifying single CORS origin produces multiple allowed origins

### ISSUE THREAD

**Issue by sime** [serverless/serverless#3324]
# This is a Bug Report

## Description
Specifying a single CORS origin, the wildcard origin is always appended.

* What went wrong?
HTTP OPTIONS request returned the following header:
`Access-Control-Allow-Origin:http://localhost:5050,*`
* What did you expect should have happened?
`Access-Control-Allow-Origin:http://localhost:5050`
* What was the config you used?

```yaml
functions:
  demo:
    handler: handler.demo
    events:
      - http:
          path: api/1/demo
          method: post
          cors:
            origins:
              - 'http://localhost:5050'
            allowCredentials: true
```
* What error message from the client did you see?
`XMLHttpRequest cannot load https://demo.execute-api.eu-west-1.amazonaws.com/skippydev/api/1/demo. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:5050,*', but only one is allowed. Origin 'http://localhost:5050' is therefore not allowed access.`

Similar or dependent issues:
* #2476 

## Additional Data

* ***Serverless Framework Version you're using***:
1.8.0
* ***Operating System***:
OS X
