### ISSUE TITLE
CORS does not work for nested paths 

### ISSUE THREAD

**Issue by waglik** [serverless/serverless#3330]
Hi guys

I have trouble making cors requests works. It seems to me that nested paths does not work. For example I created a quick test. my serverless.yml

```yml
functions:
  create:
    handler: create.create
    events:
      - http:
          path: crud
          method: post
          cors: true

  test:
      handler: create.create
      events:
        - http:
            path: advert/crud
            method: post
            cors: true
```

while "create" function works "test" one fails. both use same handler.
