### ISSUE TITLE
RequestLimitExceeded error when creating lambda functions inside VPC

### ISSUE THREAD

**Issue by zacharynevin** [serverless/serverless#3339]
This is a Bug Report

## Description

* What went wrong?
I have around 40 lambda functions in my serverless file. When I do `serverless deploy` without a VPC configuration, it deploys fine.

However, when I add a VPC configuration like this:
``` 
vpc:
  securityGroupIds:
    - ***
  subnetIds:
    - ***
```
I have a few of the functions create and then the CF deployment fails because of the following error:
```
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: MyLambdaFunction
     - Your request has been throttled by EC2, please make
     sure you have enough API rate limit. EC2 Error Code:
     RequestLimitExceeded. EC2 Error Message: Request limit
     exceeded..
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.6.0
     Serverless Version: 1.8.0
```
After filing an AWS support request, this error appears because there is a hard limit on the create function. This can be solved in one of two ways:

- Split the serverless.yaml file into smaller pieces.
- Add the `DependsOn` parameter to each lambda function.

Personally I like the 2nd option because I won't need to modify my existing `serverless.yaml` file. However, I could not find anything in the Serverless documentation or the Github issues list that indicates there is an optional `DependsOn` property for lambda functions, so that I can delay the creation of a lambda function until another one has finished creating.

If this exists, can you let me know how it works? If it does not exist, is there is a package or a feature proposal for this?

Thanks so much!

**Comment by zacharynevin** [comment]
@pmuens What would be your recommendation for avoiding this error, for now?

**Comment by pmuens** [comment]
Hey @zacharynevin you could use the `resources` section to overwrite the generated CloudFormation code and extend the Lambda code: https://serverless.com/framework/docs/providers/aws/guide/resources#aws-cloudformation-resource-reference

Other than that you could ask AWS to increase your limits.

**Comment by zacharynevin** [comment]
@pmuens it worked! For other interested parties, this is what I did:

```
service: myservice
provider:
  type: aws
  ...

functions:
  myExampleFunction:
    handler: ...
  my-other-example-function:
    handler: ...

resources:
  Resources:
    # notice how the string is always PascalCase, and the resource is appended with "LambdaFunction"
    MyExampleFunctionLambdaFunction:
      Type: AWS::Lambda::Function
      DependsOn: MyOtherExampleFunctionLambdaFunction
```
