### ISSUE TITLE
Support HTTP Proxy Api Gateway Integration Type

### ISSUE THREAD

**Issue by kkozmic-seek** [serverless/serverless#3362]
# This is a Feature Proposal
To support this:
![screen shot 2017-03-14 at 3 40 09 pm](https://cloud.githubusercontent.com/assets/9712217/23886150/b746bae8-08cc-11e7-84f6-a6607c598b5e.png)

## Description

* I want to just hide an internal/old API so I can later point the endpoint at another backend without breaking clients

* additional config:
something like:
```
proxy:
  myEndpoint:
    url: "http://myapp.com/oldEndpoint/"
    method: get
```

**Comment by Christoph-Schabert** [comment]
+

**Comment by Alex-Mann** [comment]
Is there any update on this?

**Comment by pmuens** [comment]
@Alex-Mann thanks for your comment.

We're currently waiting for some more feedback on this issue. Best is to always leave a 👍 as a reaction so that we can see which issues are highly appreciated.

**Comment by mikefrancis** [comment]
I am not sure how #3534 addresses this as you still need to specify a Lambda function to use the `http-proxy`?

**Comment by pmuens** [comment]
@mikefrancis that's a really good question 🤔 

@arabold do you have an answer for that since you've implemented it in #3534 ?

**Comment by mikefrancis** [comment]
@pmuens I like the idea of having some kind of `proxy` namespace as originally suggested, but keen to hear your thoughts on the matter?

To anyone having the same issue, it feels super hacky but you can get around it by having a NPM script which runs `serverless deploy [options]` and then straight afterwards runs a custom bash script which uses `aws-cli` to apply the proxy passthrough.

**Comment by arabold** [comment]
In #3534 I've added `HTTP_PROXY` support. However, you still have to specify a Lambda function that will _NOT_ be executed for this proxy call. That's due to the structure of Serverless which requires (http) events to be attached to functions.

With #3534 you can add the http or http-proxy integration to any existing Lambda function you have, e.g. something like this:

```yml
functions:
  myFunction:
    handler: myFunction/handler.handle
    events:
      - http:
          path: foo/bar
          method: get
          integration: lambda-proxy # default AWS_PROXY that will call your Lambda handler
      - http:
          path: foo/baz
          method: post
          integration: http-proxy # or http; your Lambda function will NOT be called.
          request:
            uri: https://example.com # required
            method: post # optional, defaults to http.method
            contentHandling: CONVERT_TO_TEXT # optional
```

In future, after the PR is approved, I would want to add the possibility to define API Gateway endpoints without attaching them to functions. But let's go one step at a time ;-)

If you really, really cannot accept adding it to a function, I'm pretty sure you can define the proxy call as a CloudFormation definition within `resources` as well. But I've never tried this.
