### ISSUE TITLE
Can't seem to use CloudFormation functions in environment variables

### ISSUE THREAD

**Issue by austenLacy** [serverless/serverless#3371]
# This is a (Bug Report / Feature Proposal)
Not sure if bug or feature proposal since the docs don't officially say it's supported I'll lean towards feature.

## Description

[CloudFormation Intrinsic Functions](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) don't seem to be working when used for setting environment variables.

For bug reports:
* Only ever seeing `[object Object]` for the environment variable rather than the actual string value
* Should see correctly evaluated string value for the env var
* What was the config you used?
```yaml
service: user

frameworkVersion: ">=1.1.0 <2.0.0"
custom: ${file(.serverless.env.yml)}
provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  environment:
    DB_HOST_1: { "Fn::Join" : ["-", [ "foo", "bar", "baz" ] ] }
    DB_HOST_2: { "Fn::If" : [ { "Fn::Equals" : [ "${opt:stage}", "production" ] }, "${env:DB_HOST}", "${self:custom.${opt:stage}.DB_HOST" ] }

plugins:
  - serverless-offline

functions:
  createUser:
    description: creates a user
    handler: handler.createUser
    events:
      - http: post users
```

You can see 2 different attempts at using the cloud formation functions to set `DB_HOST_1` and `DB_HOST_2` with one being simple and the other slightly more complex.

For feature proposals:
* I think there are a lot of potential use cases, but as the example above shows 1 example of loading env var values from different sources (a file, local env var, etc.) depending on the stage.

Similar or dependent issues:

## Additional Data

* ***Serverless version***: `1.8.0`
* ***OS***: macOS

**Comment by ryansb** [comment]
This doesn't reproduce for me. I have this in my sls.yml:

```
provider:
  name: aws
  runtime: nodejs4.3
  environment:
    SHORTENER_TABLE: {Ref: LinkDB}
    TEST_THINGS: {"Fn::Join": ['-', ['stuff', {Ref: LinkDB}, 'things']]}
```

and it translates to this in CloudFormation:

```
        "Environment": {
          "Variables": {
            "SHORTENER_TABLE": {
              "Ref": "LinkDB"
            },
            "TEST_THINGS": {
              "Fn::Join": [
                "-",
                [
                  "stuff",
                  {
                    "Ref": "LinkDB"
                  },
                  "things"
                ]
              ]
            }
          }
        }
```

Which does what I'd expect (grabbing the name of the resource, and putting it in the environment).
