### ISSUE TITLE
Allow module import from serverless.yaml via file(...)

### ISSUE THREAD

**Issue by lteacher** [serverless/serverless#3372]
# This is a Feature Proposal

## Description

Hi,

Sorry if this is a duplicate but as I was writing some plugin today I realised the fantastic feature where you can import a js file. Unfortunately in my case I want to use some default config style that no one would wrap in a function. The config itself is already an object so I was wondering why we can only pull in the js file as a function, moreover it appears to do some split on ':'  disallowing any default export. 

It seems straightforward inspecting the logic to allow a straight require of the js file as a module if it corresponds to the syntax, see example in below section.

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

When authoring a plugin I would like to have some config which can be imported into an entire config object without wrapping it as a function. For example

```yaml
custom:
  coolplugin:
    config: ${file(./config.js)}
```

* If there is additional config how would it look
Here is a custom config

```yaml
custom:
  example: ${file(./example.js)}
  named: ${file(./example.js)}:named
  property: ${file(./example.js)}:named.thing
```

```javascript
// example.js
module.exports = {
  named: {
    thing: 'Hi'
  }
}
```
We can continue to test if its a function or not as well to remain backwards compatible.

Again sorry if this is a duplicate because I had trouble finding anything without going through all the issues.
