### ISSUE TITLE
AWS http Service Endpoint URL is hard-coded to include stage name

### ISSUE THREAD

**Issue by bugeats** [serverless/serverless#3382]
> What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I need flexibility on my published urls. Right now, including the stage name is hard coded:

https://github.com/serverless/serverless/blob/fef9b68e5a453ea56bb1cd7d68f790789f404b6c/lib/plugins/aws/deploy/compile/events/apiGateway/lib/deployment.js#L31

This string should be configurable.

> If there is additional config how would it look

Maybe like this:

```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          pathPrefix: ""
          method: get
      - http:
          path: /
          pathPrefix: ${this.opts.stage} # back to default
          method: post
```
