### ISSUE TITLE
`Missing required key 'Bucket' in params` when trying to deploy 

### ISSUE THREAD

**Issue by dancrumb** [serverless/serverless#3384]
# This is a Bug Report

## Description

When trying to initially deploy a serverless service, it fails with `Missing required key 'Bucket' in params`.

I expected it to deploy properly.
## Additional Data

```
Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.8.0
```

### Data Capture

```
SLS_DEBUG=* sls deploy
Serverless: Bundling with Webpack...
Time: 948ms
     Asset    Size  Chunks             Chunk Names
handler.js  254 kB       0  [emitted]  main
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
 
  Serverless Error ---------------------------------------
 
     Missing required key 'Bucket' in params
 
  Stack Trace --------------------------------------------
 
ServerlessError: Missing required key 'Bucket' in params
    at Response.req.send (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:163:20)
    at Request.<anonymous> (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:35:11)
    at Request.<anonymous> (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:75:9
    at finish (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:308:7)
    at /Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:324:9
    at SharedIniFileCredentials.get (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:318:24)
    at Config.getCredentials (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/config.js:338:9)
    at Request.VALIDATE_CREDENTIALS (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:70:26)
    at Request.callListeners (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
From previous event:
    at persistentRequest (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:128:38)
    at AwsProvider.request (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:144:12)
    at AwsDeploy.uploadCloudFormationFile (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:23:26)
From previous event:
    at AwsDeploy.uploadArtifacts (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:76:8)
From previous event:
    at deploy:deploy (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:54:10)
    at BbPromise.reduce (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:160:50)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at PluginManager.run (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/classes/PluginManager.js:160:22)
    at Serverless.run (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/lib/Serverless.js:95:31)
    at serverless.init.then (/Users/danrumney/.nvm/versions/node/v6.9.1/lib/node_modules/serverless/bin/serverless:23:50)
```

### Config

```
service: samhain

provider:
  name: aws
  runtime: nodejs4.3
  stage: production
  region: us-east-1
  profile: personal

plugins:
  - serverless-webpack
  - serverless-s3-deploy

custom:
  assets:
    bucket: samhain.today
    files:
        - source: assets/
          globs: "**/*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:
    sessionsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "sessionsTable"
        AttributeDefinitions:
          -
            AttributeName: "SessionKey"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "SessionKey"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```
