### ISSUE TITLE
When http is null, validation throws 'TypeError: Cannot read property 'path' of null'

### ISSUE THREAD

**Issue by yamadapc** [serverless/serverless#3394]
# This is a Bug Report

## Description

```
vim serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js +145
```

Throws:
```
TypeError: Cannot read property 'path' of null
    at AwsCompileApigEvents.getHttpPath (/Users/yamadapc/n/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:145:20)
    at _.forEach (/Users/yamadapc/n/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:46:28)
    at arrayEach (/Users/yamadapc/n/lib/node_modules/serverless/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/yamadapc/n/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/Users/yamadapc/n/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:42:9)
    at /Users/yamadapc/n/lib/node_modules/serverless/node_modules/lodash/lodash.js:4970:15
    at baseForOwn (/Users/yamadapc/n/lib/node_modules/serverless/node_modules/lodash/lodash.js:3020:24)
    at /Users/yamadapc/n/lib/node_modules/serverless/node_modules/lodash/lodash.js:4939:18
    at Function.forEach (/Users/yamadapc/n/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at AwsCompileApigEvents.validate (/Users/yamadapc/n/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/lib/validate.js:41:7)
    at deploy:compileEvents (/Users/yamadapc/n/lib/node_modules/serverless/lib/plugins/aws/deploy/compile/events/apiGateway/index.js:42:31)
    at BbPromise.reduce (/Users/yamadapc/n/lib/node_modules/serverless/lib/classes/PluginManager.js:156:50)
From previous event:
    at PluginManager.run (/Users/yamadapc/n/lib/node_modules/serverless/lib/classes/PluginManager.js:156:22)
    at Serverless.run (/Users/yamadapc/n/lib/node_modules/serverless/lib/Serverless.js:95:31)
    at serverless.init.then (/Users/yamadapc/n/lib/node_modules/serverless/bin/serverless:23:50)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

For this typo in the configuration (when `http` is not defined):
```
service: myservice
provider:
  name: aws
  runtime: python2.7
  stage: production
  region: us-east-1
functions:
  fn:
    handler: handler.fn
    events:
      - http: # this is null, so it throws
        path: instances
        method: get
```

**Comment by pmuens** [comment]
Hey @yamadapc thanks for reporting 👍 

This is a classical YAML indentation problem (I've been there too!). You need to add 2 extra spaces after `http:` like this:


```yml
service: myservice
provider:
  name: aws
  runtime: python2.7
  stage: production
  region: us-east-1
functions:
  fn:
    handler: handler.fn
    events:
      - http:
          path: instances
          method: get
```

I'll close this one since it should resolve the bug. Let us know if it didn't and we'll reopen! 👍
