### ISSUE TITLE
Add CloudWatch Log event source

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3399]
# This is a Feature Proposal

## Description

Add a new `cloudwatchLog` event source. Syntax should look smth. like this:

```yaml
functions:
  myCloudWatch:
    handler: myCloudWatch.handler
    events:
      - cloudwatchLog:
          ...
```

/cc @horike37 💯 

**Note:** Other event sources (Issues and their PRs) are captured in #1409
