### ISSUE TITLE
Add SES event source

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3401]
# This is a Feature Proposal

## Description

Add a `ses` event source.

**Note:** Other event sources (Issues and their PRs) are captured in #1409

**Comment by horike37** [comment]
CloudFormation has not supported `SES` yet.
Waiting for it.

**Comment by pmuens** [comment]
Thanks for the update @horike37 👍

**Comment by arg20** [comment]
@horike37 is there any way to create a lambda function triggered by an incoming email via SES without this?

**Comment by hmngwy** [comment]
@horike37 is this the support we are waiting for?

[AWS::SES::ReceiptRuleSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-receiptruleset.html)

**Comment by derrickbeining** [comment]
Has there been any movement on this? We've built all of our client's AWS Lambdas using Serverless, and now we're working a new service for processing incoming mail through AWS Simple Email Service and Lambda. I'd love to not have to create new dev project and process for just this one function.

**Comment by danielrbradley** [comment]
I'm interested in starting working on this. I've built SES configurations in serverless manually, so happy it's all working, but a couple of questions before diving into building a proper integration...

The components you need to get full SES receiving working are as follows:
1. `LambdaInvokePermission` - allow SES within your account to invoke the Lambda.
2. `AWS::SES::ReceiptRule`
    - Recipients to pick up mail for
    - Actions to take (invoke lambda)
3. `AWS::SES::ReceiptRuleSet`
    - Do we want to set up a new rule set that can then be activated manually?
    - Do we default to the `default-rule-set` if nothing specified?
    - Might we want to add to an existing differently named rule set rather than setting up a new rule set?
4. `AWS::S3::Bucket` - Emails bucket for dumping the raw emails into
    - This is optional, but it's the only way of accessing the original email from the Lambda as the invoke payload doesn't include the original content. Using SNS does allow access to the raw content, but this fails if the email is too big as it'll truncate the raw body. Therefore S3 is the only good approach here.
    - This should have a policy set up to allow SES to write to the bucket:
    ```yaml
      Type: AWS::S3::BucketPolicy
      Properties: 
        Bucket: 
          Ref: TheEmailsS3Bucket
        PolicyDocument: 
          Statement: 
            - Action: 
                - "s3:PutObject"
              Effect: "Allow"
              Resource: arn:aws:s3:::TheEmailsS3Bucket/*
              Principal:
                Service: ses.amazonaws.com
              Condition: 
                StringEquals: 
                  aws:Referer:
                    Ref: AWS::AccountId
    ```
    - Something I would also build in here is a lifecycle configuration to auto-delete S3 objects after a fixed time so the bucket doesn't fill up over time. Maybe this should be an additional option in the future?
5. `IamRoleLambdaExecution` - need to add access to S3 if we're using that:
    ```json
                {
                  "Effect": "Allow",
                  "Action": [
                    "s3:GetObject"
                  ],
                  "Resource": "arn:aws:s3:::TheEmailsS3Bucket/*"
                }
    ```

The main questions I'd like feedback on are:
 - Should we add an extra S3 bucket by default?
 - Should we add to the default rule set unless specified?
