### ISSUE TITLE
Custom authorizer naming leads to clashes

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#3413]
# Problem
When specifying a custom authorizer for an http endpoint in this way:

```
functions:
  testfct1:
    description: 'Echo function echoes alias'
    handler: handlers/testfct1/handler.handle
    events:
      - http:
          method: GET
          path: /func1
          authorizer:
            name: myAuth
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0
            arn: arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth
```

the generated authorizer is named _auth_.
After some experimentation I analyzed that the name will be unconditionally the last part of the arn.

ARN | Authorizer name
----- | ------------------
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth | auth
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token | token
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth:dev | dev
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth:prod | prod

This is not acceptable as all authorizer arns with the same ending (especially when using aliased functions) get the same name. This most likely breaks in any environment.

# Expectation

ARN | Authorizer name
----- | ------------------
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth | access-token-auth
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token | access-token
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth:dev | access-token-auth (alt. access-token-auth-dev)
arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth:prod | access-token-auth (alt. access-token-auth-prod)

# Hint
The error happens in `validate.js: getAuthorizer(http, functionName)` which rewrites the given authorizer definition from the service.
