### ISSUE TITLE
Erroneous handling of pre-existing event resources.

### ISSUE THREAD

**Issue by hermanmedsleuth** [serverless/serverless#3435]
# This is a Bug Report
## Description

* What went wrong?
Deployment failed. (see attached output below)
The error message states that the SNS topic resource already exists. However, it does not. 
ref: [forum disucssion - deploy failing on sns topic](http://forum.serverless.com/t/deploy-failing-on-sns-topic/1586)

Note that since there are 3 functions being deployed, each triggered by a SNS topic, the error is not always reported on the same topic. However, in all cases, the SNS topic which is reported to be already existing, is not found.

* What did you expect should have happened?
Since the SNS topic does not exist, I expect that it would be created, and deployment would proceed without error. This how similar deployments in our enterprise go.

Clearly, however, in these failed deployments, there is a problem. More accurate reporting of the error would facilitate diagnosis, and correction of the problem(s).

* What was the config you used?
`serverless.yml` is shown below. The JSON used to provide parameter values is shown in the output at the end of this post.
```
#
#  Breeze Python Services cfg for ServerLess (tm)
#
# *$Author: Scott Herman<herman@medsleuth.com> $*'
# *$Id: update-2017-18-07-18-278-gc67eae3 $*'
# *$Time: 2017-03-29 16:26:51 -07:00 (Wed, 29 Mar 2017) $*'
# *$Path: BREEZE//lambda/serverless/pl-services/serverless.yml $*'
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: bps

provider:
  name: aws
  runtime: python2.7
  vpc: ${file(blsparms.json):vpc}

  iamRoleStatements:
      - Effect: Allow
        Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
        Resource: "*"
      - Effect: Allow
        Action:
          - "ec2:CreateNetworkInterface"
          - "ec2:DescribeNetworkInterfaces"
          - "ec2:DeleteNetworkInterface"
        Resource: "*"
      - Effect: Allow
        Action:
          - "sns:*"
        Resource: "*"
      - Effect: Allow
        Action:
          - "s3:*"
        Resource: "*"


stage: ${file(blsparms.json):stage}
region: us-east-1

package:
  individually: true
  include:
    - lib/**

functions:
  solicitations:
    handler: bpl-services.solicitationHandler

    events:
      - sns: SolicitationRequests

    environment: ${file(blsparms.json):env}

  notifications:
    handler: bpl-services.notificationHandler

    events:
      - sns: SurveyNotificationRequests

    environment: ${file(blsparms.json):env}

  followups:
    handler: bpl-services.followupRequestHandler

    events:
      - sns: FollowupScheduleRequests

    environment: ${file(blsparms.json):env}
```
* What stacktrace or error message from your provider did you see?
output is shown at the bottom of this post.

Similar or dependent issues:
* #3183 

## Additional Data

* ***Serverless Framework Version you're using***:
```
     Node Version:       4.3.2
     Serverless Version: 1.5.0
```

* ***Operating System***:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

* ***Stack Trace***:
No stack dump occurred

* ***Provider Error messages***:
The relevant portion of the output of one of the many failed deployments is shown below. That is all the error reporting which occurred.
```
{
   "env": {
      "AWS_ACCOUNT_ID": "xxxxxxx - redacted - xxxxxxxxxx", 
      "BREEZE_AMQP_ACCESS": "xxxxxxx - redacted - xxxxxxxxxx", 
      "BREEZE_CFG_REF": "xxxxxxx - redacted - xxxxxxxxxx"
   }, 
   "stage": "test", 
   "vpc": {
      "securityGroupIds": [
         "sg-baca05c5", 
         "sg-c3ca05bc", 
         "sg-c4ca05bb"
      ], 
      "subnetIds": [
         "subnet-884d72a5", 
         "subnet-9d8c63d5"
      ]
   }
}
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading function .zip files to S3...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - bps-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - NotificationsLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - FollowupsLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SolicitationsLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - FollowupsLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - NotificationsLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SolicitationsLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - SolicitationsLambdaPermissionSolicitationRequestsSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - NotificationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - NotificationsLambdaPermissionSurveyNotificationRequestsSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SolicitationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Topic - SNSTopicFollowupScheduleRequests
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Topic - SNSTopicSolicitationRequests
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - NotificationsLambdaPermissionSurveyNotificationRequestsSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - SolicitationsLambdaPermissionSolicitationRequestsSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - FollowupsLambdaPermissionFollowupScheduleRequestsSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - FollowupsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - CREATE_FAILED - AWS::SNS::Topic - SNSTopicSolicitationRequests
CloudFormation - CREATE_FAILED - AWS::SNS::Topic - SNSTopicFollowupScheduleRequests
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - NotificationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - FollowupsLambdaPermissionFollowupScheduleRequestsSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Topic - SNSTopicSurveyNotificationRequests
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - NotificationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - CREATE_FAILED - AWS::Lambda::Permission - SolicitationsLambdaPermissionSolicitationRequestsSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SolicitationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - CREATE_FAILED - AWS::Lambda::Permission - FollowupsLambdaPermissionFollowupScheduleRequestsSNS
CloudFormation - CREATE_FAILED - AWS::Lambda::Permission - NotificationsLambdaPermissionSurveyNotificationRequestsSNS
CloudFormation - CREATE_FAILED - AWS::SNS::Topic - SNSTopicSurveyNotificationRequests
CloudFormation - CREATE_FAILED - AWS::Lambda::Version - SolicitationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - CREATE_FAILED - AWS::Lambda::Version - FollowupsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - bps-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Policy - IamPolicyLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - NotificationsLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - FollowupsLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - SolicitationsLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - NotificationsLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - SolicitationsLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - FollowupsLambdaFunction
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - bps-dev
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Permission - NotificationsLambdaPermissionSurveyNotificationRequestsSNS
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - FollowupsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - DELETE_COMPLETE - AWS::SNS::Topic - SNSTopicSolicitationRequests
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - SolicitationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Version - NotificationsLambdaVersion2Wxc4BWOAGWwWtzHoiJlji6JVDrV3SUkk9filq0bE
CloudFormation - DELETE_COMPLETE - AWS::SNS::Topic - SNSTopicFollowupScheduleRequests
CloudFormation - DELETE_COMPLETE - AWS::SNS::Topic - SNSTopicSurveyNotificationRequests
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Permission - FollowupsLambdaPermissionFollowupScheduleRequestsSNS
CloudFormation - DELETE_IN_PROGRESS - AWS::Lambda::Permission - SolicitationsLambdaPermissionSolicitationRequestsSNS
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Permission - NotificationsLambdaPermissionSurveyNotificationRequestsSNS
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Permission - FollowupsLambdaPermissionFollowupScheduleRequestsSNS
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Permission - SolicitationsLambdaPermissionSolicitationRequestsSNS
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - bps-dev
Serverless: Deployment failed!
 
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: SNSTopicSolicitationRequests
     - SolicitationRequests already exists in stack arn:aws:cloudformation:us-east-1:785321780735:stack/bsvcs-dev/cc6e4300-0520-11e7-be4c-503acac41e99.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.3.2
     Serverless Version: 1.5.0
 
serverless deploy Failure
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
