### ISSUE TITLE
Support for cross service references via Import and Export

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3442]
# This is a Feature Proposal

## Description

The best practice of architecting a Serverless application is to separate functionality on a per-service basis ("Microservices).

This means that one service (e.g. `users`) translates to one `serverless.yml` file.

Until now there's no native way to interconnect two or more services and share values between them (e.g. Network interfaces).

This proposal describes a native, multi-provider way to `exports` and `imports` values from different Serverless services to make it easier to build large scale Serverless architectures and applications.

Refs #3441
Refs #3411
Refs #2995
Refs #2387

**Note:** This is a WIP which will be refined based on the feedback in this issue. Feedback is (as usual) highly welcomed! :muscle:

/cc @brianneisler @eahefnawy

## Syntax

The proposed syntax for `exports` is:

```yml
exports:
  <key>: <value>
```

The proposed syntax for `imports` is:

```yml
imports:
  <service-name>:
    - <key>
```

## An example

The following is an example how the usage of `imports` and `exports` could look like. In this case two different services share values between them.

```yml
# serverless.yml of users service

service: users

exports:
  writeKey: QWERTY1234
  subnetId:
    Ref: PublicSubnet
  securityGroup:
    Fn::GetAtt:
      - WebServerSecurityGroup
      - GroupId
```

```yml
# serverless.yml of posts service

name: posts

exports:
  someKey: someValue

imports:
  users:
    - subnetId
    - securityGroup
    - writeKey

resources:
  Resources:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: ${imports:users.writeKey}
```

## Implementation

The `imports` and `exports` statements are key / value based configuration parameters. This kind of abstraction enables a good way to implement this feature in a multi provider way.

The imported values will be available as a part of the variable system so that those values can be placed wherever needed (e.g. in the `Resources` section).

In AWS case the values will be translated to corresponding `Outputs` and `Fn::ImportValue` statements ([click here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html) for an example how this looks like in CloudFormation syntax).

## Problems / Issues we need to solve

- How do we deal with services in different regions (AWS currently has no support for cross region stack references)
- Happens if they are in different accounts?
- How do we deal with custom stack name
- How do we deal with the dependency on the stack name?
- How do we deal with stack removals if they depend on each other via Import and Export?

**Comment by nicka** [comment]
Ok, I really like where this is going ❤️

**Comment by pmuens** [comment]
@serverless/vip what do you think about such a functionality? What do you think is missing here? How does your dream implementation looks like?

**Comment by kennu** [comment]
It sounds like it would nicely manage the details related to CloudFormation globally unique export names. So you could logically just refer to Serverless service names & variables.

I'm not sure how stages would be handled though. Usually this kind of variables need to be exported/imported separately for each stage.

**Comment by HyperBrain** [comment]
@kennu It is good practice to prepend the stack name to the variable name when exporting stack output vars. The framework should do this implicitly, so stages wouldn't be a problem, as the stack names are known.

**Comment by ryansb** [comment]
Inside `ExportValue` statements you can use `!Sub` to put things like the stage & project name into the exported name, so if you (in serverless.yml) were exporting a function "hello" or something, the generated CFN would look like 

```
!ExportValue: "${service name}${service stage}Hello"
```

**Comment by kennu** [comment]
So if I would use the proposed syntax:

    export:
      - someKey: someValue

    import:
      - keyFromUsers:
          users: someKey

Does it mean the exporting service would be required to have exactly the same stage name as the importing service?

**Comment by pmuens** [comment]
Quick update here.

We've just pushed a WIP PR which implements this firs pass on the `imports` and `exports` syntax --> https://github.com/serverless/serverless/pull/3475

**Comment by erikerikson** [comment]
@pmuens given this:
```
imports:
  <service-name>:
    - <key>
```
Is the intention that `<service-name>` is sufficient to build the context in order to query the appropriate resources in the appropriate provider context?  How will things like region, credential profile, et cetera be declared?  What if you are, in one service, referencing resources spread across multiple services across different providers and/or rights contexts (e.g. accounts)?

My naive thought is that the following pattern should work:
```
aws:
  profile: '...' # & other config
  import:
    stackName1:
      values:
        key: value
    stackName2:
      profile: '...2' # override provider-wide settings
      values:
        key: value
  export:
    key1: value1
    key2: value2
  resources:
    [...]
azure:
  subId: '...' # & other config
  import:
    stackName3:
      serviceId: my-custom-stack-name
      values:
        key: value
  export:
    key3: value3
    key4: value4
  resources:
    [...]
```
Note features like the inheritance and overriding of values in order to specify complex use cases, the ability to manually supply stack/other deployment unit IDs in order to deal with custom names (the idea would be if you supply a `serviceId` field, this would be used, otherwise, the framework would do the provider-specific transform on the given service name so that it would match what is done to produce the actually deployed asset).

One thought that occurs to me is that in a cross-provider use case that you're selecting for a reasonably selective and aware population so that the entry bar and complexity allowance for this feature can be a slight bit higher.

Of course, this sort of multi-provider format allowance is something I've been suggesting for awhile so please let me know about my failure to grok the going wisdom against this notion.  ;)

**Comment by pmuens** [comment]
@erikerikson thanks for the really in-depth answer (as usual).

I like the idea of importing properties from stacks in other regions and accounts. The current implementation is based on `Outputs` and `Fn::ImportValue` for the `provider: aws` case which is quite limited regarding this (see: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html).

Do you think #3475 could be used a first iteration and we can add other features / more support on top of this or is the current implementation in #3475 (`Outputs` and `Fn::ImportValue`) not usable in your scenarios?

**Comment by arabold** [comment]
As this functionality applies to AWS only as far as I know, I wonder if you see specific advantages over using AWS-style references like this:

```yaml
provider:
  environment:
    TABLE_NAME:
      Ref: MyDynamoDbTable
    IMPORTED_VAR:
      Fn::ImportValue: MyOtherStack-ExportedVar
# ...
resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        # ...
```

We're already making heavy use of this since a while to decouple our stacks and access dynamically created resource names from within our code. This works very well for environment variables but also for pretty much everything else where you would need a reference to a CloudFormation resource.

**Comment by thepont** [comment]
FYI, if anyone lands here looking for a way of referencing CloudFormation stack exports cross region I wrote a plugin __serverless-plugin-cloudformation-cross-region-variables__.

[git](https://github.com/blueflag/serverless-plugin-cloudformation-cross-region-variables) - [npm](https://www.npmjs.com/package/serverless-plugin-cloudformation-cross-region-variables)

**Comment by icj217** [comment]
Not sure if my use case is different, but we deploy our User Pool in a separate service and use cross-stack references for the `arn` value successfully. Note that the `CognitoUserPoolArnOutput` in the `arn` value is not the export name of the Output, but the name of the Output resource itself

Our CUP Service (stack name: `static-resources`):
```yaml
Outputs:
    CognitoUserPoolArnOutput:
      Description: The ARN of Cognito User Pool used for this stage of the API (across multiple services)
      Value: {"Ref": OurCognitoUserPoolResource}
      Export:
        Name: ${self:service}:${opt:stage, self:provider.stage}:CognitoUserPoolArn
```

Our API Service:
```yaml
authorizer:
            arn: ${cf:static-resources-${opt:stage, self:provider.stage}.CognitoUserPoolArnOutput}
```
