### ISSUE TITLE
Add more S3 Bucket configuration options

### ISSUE THREAD

**Issue by Lepozepo** [serverless/serverless#3448]
# This is a (Bug Report / Feature Proposal)
Feature Proposal

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
At the moment it is a real pain to set up additional properties (`CorsConfiguration`, `AccessControl`, etc) on an S3 bucket that's been defined and attached to a function. Pretty much the only way to do it is to create a CloudFormation Template but this forces the developer to also have to attach events "manually".

* If there is additional config how would it look
I think everyone is expecting to be able to do something like this in the YML file:
``` yml
functions:
  doSomething:
    handler: handler.default
    events:
      - s3: stuffBucket

resources:
  Resources:
    S3BucketStuffBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: stuff-bucket-${opt:stage}
        AccessControl: 'PublicReadWrite'
```
This currently produces an error during upload that reads: `Unable to validate the following destination configurations.`

To actually get it to work you need to do this instead:
``` yml
functions:
  foo:
    handler: handler.foo

resources:
  Resources:
    S3BucketMyBucketDev:
      DependsOn:
        - FooLambdaPermissionS3BucketMyBucketDevS3
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-bucket-${self:provider.stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              Function:
                "Fn::GetAtt": [ FooLambdaFunction, Arn ]
    FooLambdaPermissionS3BucketMyBucketDevS3:
      DependsOn:
        - FooLambdaFunction
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt": [ FooLambdaFunction, Arn ]
        Action: "lambda:InvokeFunction"
        Principal: "s3.amazonaws.com"
        SourceArn: "arn:aws:s3:::my-bucket-${self:provider.stage}"
```
This is mentioned in the forums [here](http://forum.serverless.com/t/add-additional-configuration-to-an-s3-bucket-with-a-dynamic-name/705/3) and works.

Similar or dependent issues:
* #3257

## Additional Data
@manwaring tested a couple of different ways of achieving this [here](https://github.com/manwaring/serverless-bucket-events/blob/master/serverless-works.yml)

* ***Serverless Framework Version you're using***: 1.10.2
* ***Operating System***: Mac OS X
* ***Stack Trace***:
* ***Provider Error messages***:
