### ISSUE TITLE
Update SNS event to support arn config parameter

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3473]
# This is a Feature Proposal

## Description

#3443 recently added the functionality to use intrinsic functions for `arn` definitions. The `sns` event also supports the usage of `arn` like this:

```yml
functions:
  hello:
    handler: handler.hello
    events:
      - sns: arn:aws:sns:us-east-1:XXXX:some-topic
```

However it should also be possible to specify the `arn` like this:

```yml
functions:
  hello:
    handler: handler.hello
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:XXXX:some-topic
```
