### ISSUE TITLE
Add CORS automatically for http string event representation

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3486]
# This is a Feature Proposal

## Description

In #3402 we've discussed a way to deprecate the simple `http` event definition since it's almost always "useless" because most of the time you need to at least configure CORS to have something one can work with.

@patil16nit was kind enough to get this started in #3408. However removing the string representation would be a breaking change.

Furthermore removing the string representation provides no direct, additional benefit (except for the fact that we remove technical debt).

The proposal here is to add CORS automatically when using the `http` string event definition:

```yml
functions:
  hello:
    handler: handler.handler
    events:
      - http: POST hello # this will automatically enable CORS by default
```

/cc @eahefnawy @brianneisler
