### ISSUE TITLE
Connection with DynamoDB

### ISSUE THREAD

**Issue by ed-zm** [serverless/serverless#3492]
Hello guys, I've been using serverless for a while and I am not able to connect to a remote dynamodb when I invoke a lamda function locally.

I am using this conf to connect in lambda when it is deloyed 

```
provider:
    name: aws
    runtime: nodejs4.3
    stage: dev
    region: eu-central-1
    profile: ******
    iamRoleStatements:
       -  Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
```

In aws works ok, I can do all operations but locally it is impossible to access to the remote database. thanks in advance.
