### ISSUE TITLE
Stream event has incorrect DependsOn value when role passed as logical id string value

### ISSUE THREAD

**Issue by tobyhede** [serverless/serverless#3499]
# This is a Bug Report

## Description

Given a function with a custom role (MyRole) and a kinesis event stream, deployment fails with an error

```
Template format error: Unresolved resource dependencies [IamRoleLambdaExecution] in the Resources block of the template
```

Examining the CloudFormation template reveals the dependency in the EventSourceMapping:

```
"PopEventSourceMappingKinesisKinesis": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": "IamRoleLambdaExecution",
```

The IamRoleLambdaExecution Resource does not exist as no functions reference it. 

Expected the Depends On to equal the value of the specified role MyRole and deployment to work. 

```
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.10.1
     Serverless Version: 1.9.0
```

**Comment by pmuens** [comment]
Hmm. I tried to reproduce this locally with the recent `master`. Semmes to be fine on my end.

Here's my `serverless.yml`:

```yml
service: service

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    role: testKinesisStream
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:XXXX:stream/test
          startingPosition: LATEST
          enabled: false

resources:
  Resources:
    testKinesisStream:
      Type: AWS::IAM::Role
      Properties:
        RoleName: test-kinesis-stream-dev-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: test-kinesis-stream-dev-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "kinesis:DescribeStream"
                    - "kinesis:GetShardIterator"
                    - "kinesis:GetRecords"
                    - "kinesis:ListStreams"
                  Resource: arn:aws:kinesis:us-east-1:XXXX:stream/test
```

Could you try the latest master (your version was Serverless v1.9.0) and see if this problem was already fixed?

Otherwise could you please paste a `serverless.yml` which show how to reproduce the bug.

Thanks
