### ISSUE TITLE
Add additional hooks/entry points to the info plugin

### ISSUE THREAD

**Issue by HyperBrain** [serverless/serverless#3502]
# This is a Feature Proposal

## Description

Currently the info plugin writes its output en bloc. 

```
Service Information
service: auth
stage: dev
region: us-east-1
api keys:
  None
endpoints:
  None
functions:
  postauth: auth-dev-postauth
  authenticate: auth-dev-authenticate
  authorize: auth-dev-authorize
aliases:
  dev
```

The problem is, that plugins only can add their output at the end of the full info output (see _aliases_).

It would be better, if the info plugin would offer additional hooks and entrypoints per info section, that

1. Enable plugins to print their information within the info section by hooking after the section event

2. Lets plugins output a section via the info plugin (via pluginManager.spawn('info:print:_section-name_') )

3. Lets plugins overwrite original section outputs by overwriting the events hook implementation.

## Summary

With adding new events and entrypoints to the info plugin all actions mentioned above should be available to plugins. The effort to add this is minimal and non-risky.
