### ISSUE TITLE
Converting circular structure to JSON when using package command with self reference

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3509]
# This is a Bug Report

Refs #3344 and #3467

/cc @HyperBrain @eahefnawy 

## Description

The `serverless package` command is currently broken when using the `${self:}` serverless variable.

Use the following `serverless.yml` file to reproduce the issue with `master` by running `serverless package`

(The example is taken from https://github.com/serverless/serverless/pull/3208#pullrequestreview-24424693)

```yml
service: self-reference

provider:
  name: aws
  runtime: nodejs4.3

custom:
  newService: ${self:}
  exportName: ${self:custom.newService.service}-export

functions:
  hello:
    handler: handler.hello

resources:
  Outputs:
    selfExport:
      Value: 'A Value To Export'
      Export:
        Name: ${self:custom.exportName}
    OptExport:
      Value: 'Exported option variable'
      Export:
        Name: ${opt:}
    EnvExport:
      Value: 'Exported env variable'
      Export:
        Name: ${env:}
```

Here's the stack trace:

```
root@14c148d98242:/app/self# ../../../bin/serverless package
Serverless: Packaging service...
 
  Type Error ---------------------------------------------
 
     Converting circular structure to JSON
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Utils.writeFileSync (/app/lib/classes/Utils.js:51:23)
    at AwsPackage.saveServiceState (/app/lib/plugins/aws/package/lib/saveServiceState.js:32:27)
From previous event:
    at Object.aws:package:finalize:saveServiceState [as hook] (/app/lib/plugins/aws/package/index.js:81:10)
    at BbPromise.reduce (/app/lib/classes/PluginManager.js:234:55)
From previous event:
    at PluginManager.invoke (/app/lib/classes/PluginManager.js:234:22)
    at PluginManager.spawn (/app/lib/classes/PluginManager.js:246:17)
    at AwsPackage.BbPromise.bind.then (/app/lib/plugins/aws/package/index.js:69:51)
From previous event:
    at Object.package:finalize [as hook] (/app/lib/plugins/aws/package/index.js:69:10)
    at BbPromise.reduce (/app/lib/classes/PluginManager.js:234:55)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at PluginManager.invoke (/app/lib/classes/PluginManager.js:234:22)
    at PluginManager.run (/app/lib/classes/PluginManager.js:253:17)
    at Serverless.run (/app/lib/Serverless.js:97:31)
    at serverless.init.then (/app/bin/serverless:23:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       7.9.0
     Serverless Version: 1.11.0
```
