### ISSUE TITLE
Allow for service property to be an object

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3513]
# This is a Feature Proposal

## Description

Allow for the the `service` property in `serverless.yml` to be an object instead of just a string. This way we can add additional service specific properties such as `version`, `license`, `description`, `email`, `repository`, etc.

```yaml
service:
  name: 'my-service'
  version: 1.0.0
  license: 'MIT'
  description: 'My Awesome Service'
  email: 'project@hostname.com'
  repository: 'https://github.com/serverless/serverless.git'
```
