### ISSUE TITLE
Environment variables not working - different AWS keys returned

### ISSUE THREAD

**Issue by weavermedia** [serverless/serverless#3514]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I assign env vars in `serverless.yml` but get back different vars from `process.env`
* What did you expect should have happened?
I expected to get back the vars that I set
* What was the config you used?
I'm using node-s3-client to upload file to S3
* What stacktrace or error message from your provider did you see?
```
unable to upload: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:343:35) 
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:100:18) 
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10) 
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:604:14) 
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:21:12) 
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12) 
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10 
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:22:9) 
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:606:12) 
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```
I set my own AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in `serverless.yml` like:

```
provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
    environment:
      AWS_ACCESS_KEY_ID: <MY-ACCESS-KEY-ID>
      AWS_SECRET_ACCESS_KEY: <MY-SECRET-ACCESS-KEY>
```
but `process.env.AWS_ACCESS_KEY_ID` and `process.env.AWS_SECRET_ACCESS_KEY` return different values, not even from my own AWS account.

If I place the keys directly in `handler.js` access to AWS is granted and the upload works fine.

Also, I'm invoking these function from the Serverless Mac app. Just in case that makes a difference.

Is this likely an issue with the NPM module or is it a framework issue?

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***: OS X 10.11.5
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by srikanna** [comment]
Lambda sets these exact same variables [ associated with the IAM role attached to Lambda]. So its likely not a bug with serverless.

**Comment by weavermedia** [comment]
Okay, good point - I'm picking up already-set env vars.

So my problem is actually that I can't access the env vars set in `serverless.yml` in my `handler.js`:

```
// serverless.js

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    MY_VAR: 123

// handler.js

module.exports.hello = (event, context, callback) => {
  callback(null, "" + process.env.MY_VAR)
};
```

Invoking this results in: `"undefined"`

According to https://github.com/serverless/examples/tree/master/aws-node-env-variables this would be the way to access the env vars I set in `serverless/yml`.

I must be missing something obvious.

**Comment by pmuens** [comment]
@weavermedia thanks fro reporting. What Serverless version are you currently using?

**Comment by weavermedia** [comment]
This was with 1.1.0.

I tried updating to 1.2.0 but hit some deploy errors, although that looks like it was an AWS issue.

**Comment by pmuens** [comment]
> I tried updating to 1.2.0 but hit some deploy errors, although that looks like it was an AWS issue.

Have you tried again to deploy with v1.2.0?

**Comment by kiwifellows** [comment]
Hi @weavermedia I'm surprised serverless supports this as a feature. Personally storing access key/secret into a serverless.yml doesn't make sense from a security perspective - AWS advise against this kind of practice. As an alternative and recommended approach you could define a role in serverless.yml that allows access to given resources in your AWS environment. Doing the following will automatically create an IAM role your Lambda can use. Here's an example from 1 of mine:
```yaml
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-2
  memorySize: 256
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to EC2
        - ec2:*
      Resource: "*"
```

I understand you could do this per function as well.

cheers,

kiwifellows
