### ISSUE TITLE
AWS_IAM authorizerType support

### ISSUE THREAD

**Issue by srikanna** [serverless/serverless#3518]
Not a bug but a feature request. there are many use cases where one might want to protect their API using AWS_IAM other than using Cognito user pools or custom authorizer. I understand there are work arounds using plugin to achieve this, is there a plan to support AWS_IAM as AuthorizationType of API-GW events natively?

**Comment by pmuens** [comment]
Thanks for mentioning @srikanna 

Adding the `feature` label. We're waiting for more feedback on this one to see if others also think that this should be in core.

**Comment by arabold** [comment]
The [serverless-plugin-api-gateway-auth](https://github.com/nochtap/serverless-plugin-api-gateway-auth) seems to be a valid option, but I definitely think this needs to be part of Serverless Core. Standard AWS functionality should be supported without the need of potentially unmaintained 3rd party plugins IMO.

**Comment by arabold** [comment]
Okay, this is really a trivial change and a PR shouldn't take me long. The 64 dollar question is: How should we define this in the `.yaml`?

My suggestion:
```yaml
functions:
  foo:
    handler: handlers/foo/handler.foo
    events:
    - http:
        path: "/foo"
        method: GET
        authorizationType: aws_iam
```

Or completely different?

As a reminder, custom authorizers are defined like this:
```yaml
functions:
  foo:
    handler: handlers/foo/handler.foo
    events:
    - http:
        path: "/foo"
        method: GET
        authorizer:
          name: myAuth
          identitySource: method.request.header.Authorization
          resultTtlInSeconds: 0
          arn: arn:aws:lambda:us-east-1:XXXXXXX:function:access-token-auth
```

**Comment by srikanna** [comment]
sounds like a Low effort to add to the core!

**Comment by hassankhan** [comment]
In agreement with @arabold, an `AWS_IAM` authorizer would be awesome to have

**Comment by pmuens** [comment]
Thanks for the RP @arabold 👍 

Also not 100% sure how we should name it. I'm also in favor with v1 (`authorizationType`).

**Comment by brianneisler** [comment]
Seems that it makes the most sense to keep this in line with other authorization options. It wouldn't make sense to have both an `authorizationType` and `authorizer` property supplied at the same time. I would suggest going with this option...

```yaml
functions:
  foo:
    handler: handlers/foo/handler.foo
    events:
    - http:
        path: "/foo"
        method: GET
        authorizer: aws_iam
```

**Comment by HyperBrain** [comment]
Hmmm. `authorizer` and `authorizationType` are quite different things. Authorizers are Lambdas that do the actual authorization. Authorization type is the kind of authorization that is used -> AWS_IAM means that an internal authorizer supplied by AWS is used that does authorization via the AWS Sig V4 method.

According to the AWS docs:

> authorizationType
> The method's authorization type. Valid values are NONE for open access, AWS_IAM for using AWS IAM permissions, CUSTOM for using a custom authorizer, or COGNITO_USER_POOLS for using a Cognito user pool.
>
> authorizerId
> The identifier of an Authorizer to use on this method. The authorizationType must be CUSTOM.

Wouldn't it be better to stick to this definition and use both properties in the serverless.yml. Then it is much easier to understand what is configured when comparing it to the AWS docs.

**Comment by brianneisler** [comment]
@HyperBrain agree that they're different things but they are definitely connected. It was actually the reading through of those docs that made me think this approach makes sense.

Since the docs call out that `The authorizationType must be CUSTOM.` it means that the combination of an `authorizer` and any other value of `authorizationType` is a misconfiguration. By moving the type configuration to the `authorizer` value we prevent the possibility of that misconfiguration.

That being said, It's not the strongest argument, but I'm also trying to consider what offers the most generic implementation and makes sense for multiple providers. A single property where config can be held for all of authorization for the http endpoint seems simplest. We could perhaps allow for `type` to be supplied in the authorizer property like so...

```yaml
functions:
  foo:
    handler: handlers/foo/handler.foo
    events:
    - http:
        path: "/foo"
        method: GET
        authorizer: 
          type: some_type
          other: config
          ...
```
Effectively this would make the string implementation the short hand of the above.
```yaml
authorizer: aws_iam

# is short hand for ...

authorizer: 
  type: aws_iam
```
