### ISSUE TITLE
Expose setting logging configuration per method

### ISSUE THREAD

**Issue by et304383** [serverless/serverless#3522]
# This is a Feature Proposal

## Description

This may be marked as a duplicate of #1918 but I don't believe it is a duplicate.

I would like to see the ability to specify logging configuration at the http event level.  So something like this:

```
functions:
  api:
    name: ${self:provider.stage}-api
    handler: wsgi.handler
    environment: ${self:custom.env.environment}
    events:
    - http:
        method: GET
        path: /user/{user_id}
        logging:
          level: INFO
          metrics: true
          dataTraceEnabled: false
```

Similar or dependent issues:
* #1918
