### ISSUE TITLE
Add default event path for invoking functions locally

### ISSUE THREAD

**Issue by mnort9** [serverless/serverless#3538]
# This is a Feature Proposal

## Description

When invoking functions locally, I find it repetitive to specify the "--path" CLI argument each time. At least in my workflow, I'm almost always using the same event path (per function).

I'm thinking the local event path can be specified like so:

```
functions:
  usersCreate: # A Function
    handler: users.create
    events: 
      - http: 
          path: users/create 
          method: get
          eventPath: event-create.json
``` 

And of course the "--path" argument will always override the default.

Thoughts? 

If it's something the community is interested in, I can give it a go and submit a PR 😀
