### ISSUE TITLE
Multiple SNS events created but not properly added as Lambda triggers

### ISSUE THREAD

**Issue by El-Fitz** [serverless/serverless#3544]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 
While both SNS topics were created, my AWS Lambda was deployed with one SNS Trigger instead of two.
* What did you expect should have happened?
I expected my AWS Lambda function to be deployed with two SNS Triggers
* What was the config you used?
aws-nodejs, using serverless 1.0
* What stacktrace or error message from your provider did you see?
None

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
*

## Additional Data

* ***Serverless Framework Version you're using***: 1.0
* ***Operating System***: macOS 10.12.4
* ***Stack Trace***: /
* ***Provider Error messages***: /

Just in case it may help, or I did something wrong, this is what my function looks like in serverless.yml
```
functionName:
    handler: path/to.handler
    events:
      - sns:
          topicName: firstTopic
          displayName: 'First topic's display name'
      - sns:
          topicName: secondTopic
          displayName: 'Second topic's display name'
```
