### ISSUE TITLE
Custom variableSyntax bug is not detected in new async variable system

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#3561]
# This is a Bug Report

## Description

The recently merged async Serverless variable system PR https://github.com/serverless/serverless/pull/3554 introduces a bug where an infinite loop is produced when using the variableSyntax.

Use this `serverless.yml` and run `serverless package`. After that look into the `Outputs` section of the generated CloudFormation file to see that the custom variable syntax is not used.

```yml
service: service

provider:
  name: aws
  runtime: nodejs6.10
  variableSyntax: \\${{([\\s\\S]+?)}}

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello

custom:
  var: test

resources:
  Outputs:
    varA:
      Value: ${clientId()}
      Export:
        Name: varA
    varB:
      Value: ${{self:custom.var}}
      Export:
        Name: varB
```

The Problem was uncovered once all Promise usages were switched to Bluebird (see #3560) which introduced an infinte loop.

More instructions on how to reproduce the infinite loop when using Bluebird can be found in the follow-up PR which fixes some uses of native Promises where Bluebird Promises should be used --> https://github.com/serverless/serverless/pull/3560#issue-226535180

---

/cc @eahefnawy @brianneisler
