### ISSUE TITLE
Unable to send xml response with serverless framework

### ISSUE THREAD

**Issue by malikasinger1** [serverless/serverless#3568]
I'm working with twilio in which when call comes to my twilio number it invokes webhook, I'm using lambda function as webhook, 

twilio expects xml(formerly called twiml) response from webhook and i'm unable to send xml response from lambda function

I'm using serverless framework

here is my code
**function:**

    module.exports.voice = (event, context, callback) => {
    
      console.log("event", JSON.stringify(event))
      var twiml = new VoiceResponse();
    
      twiml.say({ voice: 'alice' }, 'Hello, What type of podcast would you like to listen? ');
      twiml.say({ voice: 'alice' }, 'Please record your response after the beep. Press any key to finish.');
    
      twiml.record({
        transcribe: true,
        transcribeCallback: '/voice/transcribe',
        maxLength: 10
      });
    
      console.log("xml: ", twiml.toString())
    
      context.succeed({
        body: twiml.toString()
      });
    };

**yml:**

    service: aws-nodejs

    provider:
      name: aws
      runtime: nodejs6.10
      timeout: 10

    iamRoleStatements:
        - Effect: "Allow"
          Action: "*"
          Resource: "*"

    functions:
      voice:
        handler: handler.voice
        events:
          - http:
              path: voice
              method: post
              integration: lambda
              response:
                headers:
                  Content-Type: "'application/xml'"
              template: $input.path("$")
              statusCodes:
                    200:
                        pattern: '.*' # JSON response
                        template:
                          application/xml: $input.path("$.body") # XML return object
                        headers:
                          Content-Type: "'application/xml'"
    
      

**Response:**
[![enter image description here][1]][1]
[![enter image description here][2]][2]

please let me know if I'm making some mistake in code
also asked on [stackoverflow](http://stackoverflow.com/questions/43829577/unable-to-send-xml-response-with-serverless-framework) 

Thank you,
Inzamam Malik

  [1]: https://i.stack.imgur.com/x5F0O.png
  [2]: https://i.stack.imgur.com/gg9vy.png

**Comment by pmuens** [comment]
Hey @malikasinger1 thanks for opening. 👍 

I'll close this one for now since some answers were posted in the corresponding StackOverflow thread.

**Comment by malikasinger1** [comment]
no one worked for me

**Comment by malikasinger1** [comment]
@pmuens why you think that answers are correct and should work?

**Comment by pmuens** [comment]
@malikasinger1 it seems like your mapping template should be updated. Smth. like this: https://stackoverflow.com/questions/32035338/aws-api-gateway-convert-response-to-xml

Furthermore it might be easier to use a the [lamda proxy integration type](https://serverless.com/framework/docs/providers/aws/events/apigateway#lambda-proxy-integration) and do this in code like UXDart suggested here: https://stackoverflow.com/a/43830851

**Comment by newbreedofgeek** [comment]
@malikasinger1 did you work out a solution for this? I have the same issue and now of the replies here work. I'm sure this can be done in serverless.yml instead of having to head into AWS API Gateway to configure the mapping

**Comment by glenchao** [comment]
@newbreedofgeek i got mine to work with this. hope this helps
```yml
events:
      - http:
          path: call/receive
          method: post
          integration: lambda
          response:
            headers: 
              Content-Type: "'application/xml'"
            template: $input.path("$")
            statusCodes:
              200:
                pattern: ''
                template: 
                  application/json: $input.path("$")
                headers:
                  Content-Type: "'application/xml'"
```

```js
callback(null, twiml.toString());
```
