### ISSUE TITLE
Package validation fails when no functions declared. 

### ISSUE THREAD

**Issue by tobyhede** [serverless/serverless#3569]
# This is a Bug Report  but also maybe a Feature Proposal

This is a wacky issue cause by my abuse/extension of the framework

## Description

I built a "containerless" plugin that extends serverless to allow functions to be deployed to an ECS cluster with a really simple set of config. I love the deployment model and philosophy of serverless, and all the heavy lifting of variables and stages and resources etc etc etc is done by the framework. A+, would plugin again.

In our case, when a service is defined without a function, the framework throws a validation error.

```
ServerlessError: No containerless.zip file found in the package path you provided.
```

We might have a service without a lambda function because everything is being deployed in this case to ECS.

For example:

```
service: containerless

provider:
  name: aws

custom:
  containerless:
    cluster:
      vpcId: vpc-abc
      subnets:
        - subnet-abc
        - subnet-def
    repository: amazonaws.com/containerless
    applications:
      hello:
        url: /hello
```

This is a pretty edge case, and I can work around by adding a dummy function in and documenting this in the plugin.  

However, I am happy to patch to handle this case as well.

One option would be to not fail the deployment at package time, but display a warning that no functions had been defined. If a function had been defined, and no JS was present then the current empty zip error is valid and should remain.
