### ISSUE TITLE
Add sls config commands

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3574]
# This is a Feature Proposal

## Description

PR #3558 recently added support for a `.serverlessrc` file. This file will now hold the configured serverless platform credentials and other config info. We should add generic config commands for managing these files in a programmatic way.

- [ ] Take care of file permission handling (e.g. check when file is read)

### .serverlessrc file format
The `.serverlessrc` format is JSON. 

#### `sls config set -k <key> -v <value> [-g|--global]`
* Sets a config value in `.serverlessrc`.
* Defaults to setting values at the project level (cwd). 
* To set a value at the global level (`~/.serverless/.serverlessrc`) use the `-g` option.
* Creates a `.serverlessrc` file if one does not exist.
* Since the config file is json, key depth can be specified using `.`
  + Example: running `sls config set -k foo.bar -v hello` results in...
```
{
  "foo": {
    "bar": "hello
  }
}
```
* Command should return success message 
```
Successfully configured ~/path/to/.serverlessrc
<key>: <value>
```

#### `sls config get -k <key>`
* Gets a config value
* Key depth can be specified using `.`
* Command outputs value found at `key`

#### `sls config delete -k <key> [-g|--global]`
* Deletes a config value
* Executes at the project level by default
* Key depth can be specified using `.`
* Command outputs value deleted at `key`
* To delete a value at the global level (`~/.serverless/.serverlessrc`) use the `-g` option.

#### `sls config list`
* Lists all config from both the project and global levels
* Command outputs...
```
Global config `~/.serverless/.serverlessrc`
{
  "foo": "bar"
}

Project config 
Global config `~/path/to/project/.serverlessrc`
{
  "bar": "baz"
}
```

**Comment by pmuens** [comment]
> Creates a .serverlessrc file if one does not exist.

@brianneisler is there an example for a `.serverlessrc` skeleton with the default config which should be always in place? Or should we simply create an empty JSON file?

**Comment by brianneisler** [comment]
@pmuens no skeleton or default config at the moment. Simply create an empty json file and add the config being set by the command.

**Comment by HyperBrain** [comment]
Could we support YAML and JSON for the rc file? With the parser that is used in SLS this should work easily. (see my PR to add something similar for the serverless.yml/yaml/json here https://github.com/serverless/serverless/pull/3647)

**Comment by brianneisler** [comment]
@HyperBrain makes sense to me!

**Comment by lucas-rudd** [comment]
Is the `.serverlessrc` file just used for credentials and the like? Or, can I put configuration variables for my `serverless.yml` file in there as well?

For example, say I have the following provider definition in my `serverless.yml` file.

```
provider:
    name: aws
    role: ${file(config/env/${opt:stage}.yml):role}
    region: ${file(config/env/${opt:stage}.yml):region}
    runtime: nodejs6.10
    deploymentBucket: ${opt:stage}-serverless-lambda-deployments
    stackTags: ${file(config/env/${opt:stage}.yml):tags}
    vpc: ${file(config/env/${opt:stage}.yml):vpc}
    alias: ${opt:alias, 'release'}
    environment:
        NODE_ENV: ${opt:stage}
```

Can I somehow replace the current references to `${file(config/env/${opt:stage}.yml}` by using `.serverlessrc`? And, if so, how?

It would be nice to see some more detailed information on how to use `.serverlessrc` in the README.
