### ISSUE TITLE
serverless deploy function ignores package artifact

### ISSUE THREAD

**Issue by ubaniabalogun** [serverless/serverless#3580]
# This is a Bug Report

### What went wrong?
Consider the below serverless.yml file
```
service: test-service

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
    package:
      artifact: upload.zip
```

When `serverless deploy function -f hello` is run, Serverless ignores the `functions.hello.package.artifact` configuration and falls back to whatever exclude/include configuration it determines.
This indicates that `serverless deploy function -f` is currently ignoring the `functions.[function name].package.artifact` config  
### What did you expect should have happened?
I expected `serverless deploy function -f` to respect the `functions.[function name].package.artifact` configuration the same way `serverless deploy` does.
 
### What was the config you used?
See description

### What stacktrace or error message from your provider did you see?
No error but the behavior is inconsistent with expectations

## Additional Data

* ***Serverless Framework Version you're using***: 1.12.1
* ***Operating System***: OS X El Capitan
* ***Stack Trace***:
* ***Provider Error messages***:
