### ISSUE TITLE
CORS: Add `X-Amz-User-Agent` to list of allowed headers

### ISSUE THREAD

**Issue by arabold** [serverless/serverless#3586]
# This is a Feature Request

## Description

I'm using the default CORS options in our backend Lambda to allow our frontend to access it via JavaScript. In order to make this work properly I needed to add `X-Amz-User-Agent` to the list of `Access-Control-Allow-Origin` headers as shown in this example:

```yaml
functions:
  api:
    handler: handlers/api/handler.handler
    description: General API
    events:
      - http:
          path: api/{any+}
          method: GET
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Amz-Security-Token
              - X-Amz-User-Agent      # <-- have to add this manually!
              - X-Api-Key
          authorizer: aws_iam
```

My request is to simply add `X-Amz-User-Agent` as a default allowed header. That would make things much simpler.

## Additional Data

* ***Serverless Framework Version you're using***: 1.12.1
