### ISSUE TITLE
Validation Error Detected v1.13.0

### ISSUE THREAD

**Issue by selected-pixel-jameson** [serverless/serverless#3587]
As of the release of version 1.13.0 I get the following validation error message when running a deploy. This doesn't happen with version 1.12.1. I've only seen then when migrating directly from version 1.5.0 to 1.13.0. I haven't tested to see if it happens from any other migration paths. 
```
  An error occurred while provisioning your stack: media
     - 1 validation error detected: Value '${self:custom.databasePrefix}-media'
     at 'tableName' failed to satisfy constraint: Member
     must satisfy regular expression pattern: [a-zA-Z0-9_.-]+.
```

**Comment by eahefnawy** [comment]
hmmm it seems that the `${self:custom.databasePrefix}` not getting populated, are you sure you're referencing it correctly? Could you show us your `serverless.yml`? 😊

**Comment by selected-pixel-jameson** [comment]
I'll post the serverless.yml file in a second, but I've been using the same file more or less since version 1.2. Also it works fine on version 1.12.1, but when I try to use version 1.13.0 it generates this error. So it doesn't seem like an issue with the serverless variables unless something has changed with those in version 1.13.0.

Jameson W Parker
Owner & Software Developer
www.selectedpixel.com
920.203.4106

**Comment by selected-pixel-jameson** [comment]
This is where I'm creating the variable.

```
custom:
  stage: ${opt:stage, self:provider.stage}
  accountNo: xxxxxxxxxxx
  logsEnabled: Deny
  functionPrefix: xxxxxxxxxxx-api-${self:custom.stage}
  rolePrefix: xxxxxxxxxxx-${self:custom.stage}
  databasePrefix: xxxxxxxxxxx-${self:custom.stage}
  apiVersion: /v1
  identityPool: arn:aws:cognito-identity:us-east-1:xxxxxxxxxxx:identitypool/us-east-1:xxxxxxxxxxxxxxxxx
```
And this is how I'm referencing it it in the cloudformation-resources.json file.

```
 "media": {
    "Type": "AWS::DynamoDB::Table",
    "Properties": {
      "TableName": "${self:custom.databasePrefix}-media",
........
```

**Comment by pmuens** [comment]
Thanks for sharing your `serverless.yml` @selected-pixel-jameson 👍 

@eahefnawy do you think it might be related to the race condition we're working on in https://github.com/serverless/serverless/pull/3560?

**Comment by eahefnawy** [comment]
@pmuens not entirely sure. I'm gonna test this variable ref structure and see if I can reproduce it and debug from here. At first glance though it seems that @selected-pixel-jameson file is valid :blush:

**Comment by eahefnawy** [comment]
> And this is how I'm referencing it it in the cloudformation-resources.json file.

@selected-pixel-jameson and how are you referencing this file?

**Comment by selected-pixel-jameson** [comment]
```
resources:
  Description: Serverless Resources for ${self:service} - ${opt:stage, self:provider.stage}
  Resources: ${file(cloudformation-resources.json)}
  Outputs: ${file(cloudformation-outputs.json)}
```
