### ISSUE TITLE
YAML creates nested objects instead of string representations

### ISSUE THREAD

**Issue by alex20465** [serverless/serverless#3607]
# ESDomain.AdvancedOptions parsed to object.

## Description
The update/deployment of an "AWS::Elasticsearch::Domain" using 1.13.x

For bug reports:

The AdvancedOptions are broken and invalid for cloudformation:

```
  Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: ESDomain
     - Value of property AdvancedOptions must be an object
     with String (or simple type) properties.
```

The cloudFormation definition should provide the following options:
```
   "AdvancedOptions": {
          "rest.action.multi.allow_explicit_index": "true",
          "indices.fielddata.cache.size": ""
}
```

Here are the AWS::Elasticsearch::Domain defintions

```
resources:
  Resources:
    ESDomain:
      Type: AWS::Elasticsearch::Domain
      Properties:
        AccessPolicies: 'xxx'
        DomainName: xxxx
        ElasticsearchVersion: "5.1"
        ElasticsearchClusterConfig:
          InstanceType: t2.medium.elasticsearch
          InstanceCount: 1
        EBSOptions:
          EBSEnabled: true
          VolumeType: standard
          VolumeSize: 10
        AdvancedOptions:
          rest.action.multi.allow_explicit_index: "true"
          indices.fielddata.cache.size: ""
```

Here is the cloudformation-template-update-stack.json (ES.Domain AdvancedOptions part) which is invalid for cloud-formation.

```
        "AdvancedOptions": {
          "rest.action.multi.allow_explicit_index": "true",
          "indices.fielddata.cache.size": "",
          "rest": {
            "action": {
              "multi": {
                "allow_explicit_index": "true"
              }
            }
          },
          "indices": {
            "fielddata": {
              "cache": {
                "size": ""
              }
            }
          }
        }
```

## Additional Data

* ***Serverless Framework Version***: 1.13.x

**Comment by pmuens** [comment]
@alex20465 thanks for reporting.

So this is a blank deployment with v1.13? Or have you deployed this service with another Serverless version previously?

It looks like the YAML parser parses the `.` notation to JSON objects with properties.

Not too familiar with the expected JSON output for CloudFormation (if those values should be strings rather then objects) but can you try to wrap the definitions which use dots in quotes like this:

```yml
resources:
  Resources:
    ESDomain:
      Type: AWS::Elasticsearch::Domain
      Properties:
        AccessPolicies: 'xxx'
        DomainName: xxxx
        ElasticsearchVersion: "5.1"
        ElasticsearchClusterConfig:
          InstanceType: t2.medium.elasticsearch
          InstanceCount: 1
        EBSOptions:
          EBSEnabled: true
          VolumeType: standard
          VolumeSize: 10
        AdvancedOptions:
          "rest.action.multi.allow_explicit_index": "true"
          "indices.fielddata.cache.size": ""
```
