### ISSUE TITLE
Resource name 'a.b.c' creates nested objects in the RequestParameters property

### ISSUE THREAD

**Issue by mykemd** [serverless/serverless#3613]
Hi guys,

Upgraded to 1.13.1 and can't deploy my project - getting an error 

```
 Serverless Error ---------------------------------------
 
     An error occurred while provisioning your stack: MyMethod
     - Value of property RequestParameters must be an object
     with String (or simple type) properties.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       7.5.0
     Serverless Version: 1.13.1

```

IT looks like integration.request.path.proxy key is getting parsed and nested objects are created in the cloud formation.

1.12.1 works well

Here's serverless.yml snippet
```
 MyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: AAA
        RestApiId:
          Ref: AAApi
        HttpMethod: ANY
        AuthorizationType: NONE
        RequestParameters:
          method.request.path.proxy: true
        Integration:
          Type: HTTP_PROXY
          IntegrationHttpMethod: ANY
          Uri: "https://aaaa"
          IntegrationResponses:
            - StatusCode: 200
          RequestParameters:
            "integration.request.path.proxy": method.request.path.proxy
```

in the cloud formation script the output is the following
```
 "MyMethod": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "ResourceId": {
          "Ref": "AAA"
        },
        "RestApiId": {
          "Ref": "AAApi"
        },
        "HttpMethod": "ANY",
        "AuthorizationType": "NONE",
        "RequestParameters": {
          "method.request.path.proxy": true
        },
        "Integration": {
          "Type": "HTTP_PROXY",
          "IntegrationHttpMethod": "ANY",
          "Uri": "https://aaa",
          "IntegrationResponses": [
            {
              "StatusCode": 200
            }
          ],
          "RequestParameters": {
            "integration.request.path.proxy": "method.request.path.proxy",
            "integration" : {
                 "request": {
                    "path" : {
                        "proxy": "method.request.path.proxy"
                    }
                 }
            }
          }
        }
      }
    }
```
Is there a way to remove this nested resolution behaviour?

## Additional Data

* Serverless Version 1.31.1
* mac osx
