### ISSUE TITLE
Variables replacement does not work in nested templates

### ISSUE THREAD

**Issue by ssideleau** [serverless/serverless#3615]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Variables replacement did not work in my resources file.
This is not a problem in 1.12.1

Using the `sls package` command the DynamoTable part of the `cloudformation-template-update-stack.json` is :
```
"DynamoTable": {
    "Type": "AWS::DynamoDB::Table",
    "Properties": {
      "TableName": "${self:service}-${self:custom.stage}-myAttribute",
      "AttributeDefinitions": [
        {
          "AttributeName": "myAttribute",
          "AttributeType": "S"
        }
      ],
      "KeySchema": [
        {
          "AttributeName": "myAttribute",
          "KeyType": "HASH"
        }
      ],
      "ProvisionedThroughput": {
        "ReadCapacityUnits": 10,
        "WriteCapacityUnits": 10
      }
    }
  }
```
* What did you expect should have happened?

The DynamoTable part of `cloudformation-template-update-stack.json` should be:
```
    "DynamoTable": {
      "Type": "AWS::DynamoDB::Table",
      "Properties": {
        "TableName": "sls-variables-test-dev-myAttribute",
        "AttributeDefinitions": [
          {
            "AttributeName": "myAttribute",
            "AttributeType": "S"
          }
        ],
        "KeySchema": [
          {
            "AttributeName": "myAttribute",
            "KeyType": "HASH"
          }
        ],
        "ProvisionedThroughput": {
          "ReadCapacityUnits": 10,
          "WriteCapacityUnits": 10
        }
      }
    }
```
* What was the config you used?

**Project Structure**
```
.
├── handler.js
├── serverless.yml
└── slsConfig
    └── aws-resources
        ├── dev.resources.yml
        └── templates
            └── dynamoDB.resources.yml
```
**serverless.yml**
```
service: sls-variables-test

custom:
  stage: ${opt:stage, self:provider.stage}
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    ${file(slsConfig/aws-resources/${self:custom.stage}.resources.yml)}
```
**slsConfig/aws-resources/dev.resources.yml**
```
${file(slsConfig/aws-resources/templates/dynamoDB.resources.yml)}
```
**slsConfig/aws-resources/templates/dynamoDB.resources.yml**
```
DynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: '${self:service}-${self:custom.stage}-myAttribute'
    AttributeDefinitions:
      - AttributeName: myAttribute
        AttributeType: S
    KeySchema:
      - AttributeName: myAttribute
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 10
      WriteCapacityUnits: 10
```
* What stacktrace or error message from your provider did you see?

```
..........Serverless: Deployment failed!

  Serverless Error ---------------------------------------

     An error occurred while provisioning your stack: DynamoTable
     - 1 validation error detected: Value '${self:service}-${self:custom.stage}-myAttribute'
     at 'tableName' failed to satisfy constraint: Member
     must satisfy regular expression pattern: [a-zA-Z0-9_.-]+.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       6.10.2
     Serverless Version: 1.13.0
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.13.0
* ***Operating System***: Gnome Ubuntu 16.04
* ***Stack Trace***:
* ***Provider Error messages***:
