### ISSUE TITLE
authorizer: aws_iam doesn't work

### ISSUE THREAD

**Issue by rogemita** [serverless/serverless#3623]
## Description

authorizer: aws_iam config into serverless.yml doesn't work.

* What did you expect should have happened?
It should set up Authorization = AWS_IAM into the api gateway's resource.
* What was the config you used?
That one mentioned here in doc: https://serverless.com/framework/docs/providers/aws/events/apigateway#http-endpoints-with-aws_iam-authorizers
```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: ''
          method: get
          authorizer: aws_iam
```
* What stacktrace or error message from your provider did you see?
```
Serverless: Packaging service...

  Serverless Error ---------------------------------------

     Function "aws_iam" doesn't exist in this Service

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       4.4.3
     Serverless Version: 1.13.0
```
