### ISSUE TITLE
Support runtime ranges for `runtime` property

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3626]
# This is a Feature Proposal

## Description
In an effort to be a bit more provider agnostic and allow for easier management of services we should support runtime range declarations. 

Currently the runtime property allows for values of this format...
```yaml
provider:
  runtime: nodejs6.10

functions:
  hello:
    runtime: python2.7 # optional overwrite, default is provider runtime
```
These are very explicit. Not every provider supports these exact runtime values. Instead, we should allow for a range to be declared at the function and service level that indicate the required runtime range for the function to operate correctly. 

```yaml
service:
  runtime: nodejs6.x

functions:
  hello:
    runtime: python>=2.7 # optional overwrite, default is provider runtime
```

The range declarations should follow semantics similar to the [semver model](https://docs.npmjs.com/misc/semver#ranges)

If a range is detected during deployment the framework should swap the range for the explicit value the provider expects for the runtime property. 

In the case that a range is detected that the provider does not support, the framework should throw an error during deployment.

Example: [here](http://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime) the valid values are listed for AWS lambda. 

```yaml
functions:
  hello:
    runtime: python>=2.7<3.0
```
would become the following in the output cloudformation...
```json
{
  "Type" : "AWS::Lambda::Function",
  "Properties" : {
    "Runtime" : "python2.7",
    ...
  }
}
```
