### ISSUE TITLE
Serverless generates an error when using a self:custom.variable which has been created with the function Fn::Join

### ISSUE THREAD

**Issue by xavicolomer** [serverless/serverless#3630]
# This is a (Bug Report / Feature Proposal)

## Description
Serverless generates an error when using a self:custom.variable which has been created with the function **Fn::Join**. 

**It works fine when using string variable 'version'**

**variable definition**
```
custom:
  version: v1
  snsTopic:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - snsTopic
```
**function definition**
```
my-function:
    handler: handler.function
    events:
      - http:
          method: method
          path: path/to/resource
          integration: lambda
          request:
            template:
              application/json: '{ "key": "${self:custom.snsTopic}" }'
```
* ***Serverless Framework Version you're using***:
v1.7.0

* ***Operating System***:
Windows 10
