### ISSUE TITLE
AWS Cognito User Pool triggers support

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#3637]
# This is a Feature Proposal

## Description
I'd like to be able to create functions that hook into a User Pool for various use-cases such as `preSignup`, `customMessage` etc. (which are defined [here](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html)). 

Currently I deploy the functions then manually attach them via AWS Console (although this can probably be automated using the AWS SDK).

I am aware that Lambda event sources are different from Lambda triggers (at least conceptually), but in practice they both seem to be only fired when an event occurs. Therefore, it would be lovely if I could define them in `serverless.yml` with something as follows:

```yml
functions:
  preSignup:
    handler: handler.preSignup
    events:
      - cognito-user-pool:
          pool: <POOL-ID>
          trigger: PreSignUp
```

Similar or dependent issues:
* #3400

**Comment by horike37** [comment]
Thank you for sending the greate PR @hassankhan :heart_eyes:
That could be super helpful and really useful! 
I often use `Cognito User Pool` too, and face the same problem :sweat_smile:

As you say, these triggers are a little different from Lambda event sources, so it may be better to change the syntax to distinguish `events` from Lambda triggers.

For example
```
functions:
  preSignup:
    handler: handler.preSignup
    aws-triggers:
      - cognitoUserPool:
          pool: <POOL-ID>
          target: preSignUp
```
What do you think? @pmuens @eahefnawy

**Comment by hassankhan** [comment]
Could perhaps even be just `triggers` instead of `aws-triggers`?

**Comment by brianneisler** [comment]
@horike37 I think it would make sense to keep these as `events`. It helps keep the cognitive overhead low. As stated by @hassankhan 

> I am aware that Lambda event sources are different from Lambda triggers (at least conceptually), but in practice they both seem to be only fired when an event occurs. 

I really agree with this conceptually. Internally at Serverless we're striving to boil everything down to two simple concepts, events and functions. 

That being said, I think this implementation is the most straightforward and familiar.

```yaml
functions:
  preSignup:
    handler: handler.preSignup
    events:
      - cognitoUserPool:
          pool: <POOL-ID>
          trigger: PreSignUp
```
