### ISSUE TITLE
Deploying does not rely on artifact config parameter.

### ISSUE THREAD

**Issue by dlcron** [serverless/serverless#3643]
# This is a Bug Report

## Description

My serverless.yml
```
service: ss

frameworkVersion: ">=1.12.0"

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage}

# lambda functions and events trigerring them
functions:
  create_vast:
    handler: ss.ss.xxx
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: create
          method: post
          authorizer: aws_iam
    artifact: sss.zip
```

I expect it to use sss.zip when deploying the package, but it isn't. There is new package created and deployed with the whole root packed.

## Similar or dependent issues:
* #3526

## Additional Data

* serverless version 1.13.2
