### ISSUE TITLE
`serverless package` doesn't honor the artifact and package individually configuration

### ISSUE THREAD

**Issue by shikasta-kashti** [serverless/serverless#3684]
# This is a (Bug Report)

## Description
I'm trying to use this command: `serverless package --stage devd --account dev` to create packages for my AWS Lambda functions and it doesn't work properly.

It's supposed to use the files that I reference in the `artifact` property instead it archives the root zip folder.

## What went wrong?
When using `serverless package` command with config `artifact` and `package`.`individually: true` it zips/archives the whole root folder instead of honoring the configuration in the serverless.yml file.

## What did you expect should have happened?
I'm trying to use the `artifact` and `package`.`individually: true` to have separate packages for each of my function and use the zip files that I generate with gulp.

## What was the config you used?
```
service: test

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: us-east-1
  profile: ${opt:account}

functions:
  hello1:
    handler: handler1.hello1
    package:
      artifact: dist/hello1.zip
    events:
        - schedule: rate(1 minute)
  
  hello2:
    handler: handler2.hello2
    package:
      artifact: dist/hello2.zip
    events:
        - schedule: rate(1 minute)
```
## What stacktrace or error message from your provider did you see?
None.

## Similar or dependent issues:
* #3526
* #3643

## Additional Data

* ***Serverless Framework Version you're using***: v.1.14.0
* ***Operating System***: Windows 7
* ***Stack Trace***: None.
* ***Provider Error messages***: None.

**Comment by dlcron** [comment]
Dunno if we are on the same page with how artifacts works. If you use artifact, then you must be the one to build it. So first you build, then you provide it in configs.

Serverless framework will still build the package, but when deploying it will use yours artifact.

**Comment by shikasta-kashti** [comment]
Yes, I'm building the artifacts with my gulp scripts. I was expecting `serverless package` to do everything same as `serverless deploy` except the deployment part.

Does that mean it's a bug in `serverless package` then?

**Comment by dlcron** [comment]
It might be. Try to deploy it and test it out. I was looking only at results of builded package. Not at the outcome of deploying it, where things were fine.

**Comment by shikasta-kashti** [comment]
Ok, so I tried `serverless deploy` and it works properly. I believe it's still a bug in `serverless package` command.

Just to provide some more information, my directory structure for the above test was like this:
```
/dist/
/dist/hello1.zip
/dist/hello2.zip
serverless.yml

```

but in the local `.serverless` directory, it generates some .json files for CloudFormation and two ZIP files: 

* hello1.zip
* hello2.zip

The contents of both ZIP files are the same and they have just zipped the complete `/dist/` folder.

**Comment by dlcron** [comment]
Right, so we have the bug here.

**Comment by HyperBrain** [comment]
@shikasta-kashti @dlcron Technically a "serverless deploy" without the package switch is just a "serverless package" and then a "serverless deploy". So manually invoking package and deploy should yield exactly the same results.
Did you use "individually: true" (on the package level, or on the function level)? If not, you'll get a service ZIP which is the same for all functions.

**Comment by eahefnawy** [comment]
adding to @HyperBrain great notes, you can also specify the package path under the `package.path` property in `serverless.yml` and it'll get picked up whenever you do `sls package` or `sls deploy`. Also note that the pacakge path is an absolute path, not a relative path.

**Comment by pmuens** [comment]
I believe the problem is the relative path (according to the config you've provided).

Refing https://github.com/serverless/serverless/issues/3621 here which captures this problem.

@shikasta-kashti could you try to use an absolute path and see if this produces the desired result?

**Comment by dlcron** [comment]
I took part in the discussion as @shikasta-kashti engaged me here #3643. I just point my observations how things work here from my experience.

How does the correct procedure for building artifacts work? 

Is the correct behavior correct?
My serverless:
```
$ cat serverless.yml
service: poc

frameworkVersion: ">=1.12.0"

provider:
  name: aws
  runtime: python3.6

package:
  artifact: t.zip

functions:
  fun:
    handler: handler.handler
```

```
$ touch t.zip
$ zless t.zip => empty
$ serverless package
Serverless: Packaging service...
```

Now I expect to serverless package to have my `t.zip` entry in the package listing, while I have poc.zip. 
```
$ ls -lah .serverless       
cloudformation-template-create-stack.json  
cloudformation-template-update-stack.json  
poc.zip  
serverless-state.json
                                                                                                                                                          
$ zless poc.zip => 
def handler():
    pass
```

Am I missing how things work here? When I deploy things, then my t.zip appears to be deployed. I run this on 1.13.2.

**Comment by tyrsius** [comment]
I am experiencing a similar issue, but the results are not quite the same. Serverless attempts to zip my function during `sls package` no matter what configuration I provide. I am on version `1.14.0`

My serverless config
```
service: LambdaTemplate
package:
  individually: true
  artifact: local-build-proxy.zip

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  memorySize: 128
  timeout: 5
  versionFunctions: false
  environment:
    stage: ${opt:stage}

functions:
  LambdaTemplateNodeProxy:
    handler: proxy.handler
    package:
      artifact: local-build-proxy.zip
      individually: true
```

I have tried commenting out the `package.artifact` line, as well as `functions.func.package.individually`. When I run `sls package`, I get this error

```
Serverless: Packaging service...
fs.js:1000
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/Users/tkye/dev/lambda-template-node/node_modules/node-jwt-authorizer'
    at Error (native)
    at Object.fs.statSync (fs.js:1000:11)
    at files.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:53:26)
...
```

That file doesnt exist, but serveless shouldnt not be trying to zip anything when I provide my own artifact.

**Comment by tyrsius** [comment]
This bug does not appear to be present in `1.11.0`. I think the package command broke the artifact/individually support

**Comment by tyrsius** [comment]
@dlcron @HyperBrain This bug has been stopping us from upgrading from `1.11.0`, and serverless is up to `1.15.3`. Has there been any update on it?

**Comment by pmuens** [comment]
Thanks for getting back again @tyrsius 👍 

This bug seems to be still around. We'll look into it ASAP. /cc @eahefnawy

**Comment by dlcron** [comment]
@tyrsius I've also met this error, but I thought it was kind of sanity check to make sure that the file you'd created, and now which was packed, really exists. But the exception, indeed, is not sanity check :)

My case still exists in 1.16.0. I just confirmed this. Here's the bash script with this use case (I am not sure you understand me before as there was no reply, so this code should explain my concerns and expectations at that point). 

```bash
#!/bin/bash

mkdir -p dlctest
cd dlctest

# Create the structure
sls create --template aws-python3

# Create the files
echo "service: poc

frameworkVersion: \">=1.12.0\"

provider:
  name: aws
  runtime: python3.6

package:
  artifact: t.zip

functions:
  fun:
    handler: handler.handler
" > serverless.yml

echo "
def handler():
    pass   
" > handler.py

touch t.zip

# pack the package
sls package

# check the content
EXPECTED_FILE=".serverless/t.zip"
FOUND_FILE=`find .serverless -name '*.zip'`

if [ -f "$EXPECTED_FILE" ] && [ "$EXPECTED_FILE" == "$FOUND_FILE" ];
then
  echo "OK"
else
  echo "'t.zip' should appear as the file to be deployed, as this file appears in cloudformation template."   
  echo "run \"grep -F 't.zip' .serverless/cloudformation-template-update-stack.json\" to verify."
  echo "Found $FOUND_FILE"
fi

cd ..
rm -rf dlctest
```
Now I understand, that the "S3 key" is important here and when deploying it's not a bug, but just introduces confusion. The fix for both my case, and @tyrsius would be: do not build the artifact if one is provided.

**Comment by adrienjt** [comment]
FYI when you work on fixing this bug: even with 1.11.0, if individual artifacts are in different directories but named the same (e.g. `function1/artifact.zip` and `function2/artifact.zip`), Serverless saves them on top of each other in the deployment bucket, so there ends up being only one artifact used by all functions (the latest defined).

```yaml
service: myservice

frameworkVersion: =1.11.0

provider:
  name: aws
  runtime: python2.7
  versionFunctions: false

package:
  individually: true

functions:
  function1:
    package:
      artifact: function1/artifact.zip
    handler: function1.lambda_handler
  function2:
    package:
      artifact: function2/artifact.zip
    handler: function2.lambda_handler
  function3:
    package:
      artifact: function3/artifact.zip
    handler: function3.lambda_handler
```
A workaround is to name them differently: `artifact1.zip`, `artifact2.zip`, and `artifact3.zip`.
