### ISSUE TITLE
Unable to deploy stage - "{LambdaFunctionName} already exists"

### ISSUE THREAD

**Issue by adambiggs** [serverless/serverless#3697]
# This is a Bug Report

### What went wrong?
Trying to deploy a new service. Created a new `staging` stage, and all went as expected. Then tried deploying the same service to a new `production` stage, but every attempt fails with the following error:

```
An error occurred while provisioning your stack: MyFunctionNameLambdaFunction
     - my-service-name-production-my-function-name already exists.
```

### What did you expect should have happened?
The function should have been deployed without any errors.

### What was the config you used?
Simplified sample config:

```yml
frameworkVersion: ">=1.14.0"
service: my-service-name

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  timeout: 60
  deploymentBucket: my-deploy-bucket
  role: arn:aws:iam::000000000000:role/my-lambda-execution-role

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

functions:
  myFuncitonName:
    handler: functions/my-function.handler
    events:
      - http:
          path: something/{something_id}/something-else/{another_id}/blah
          method: get
          cors: true
          authorizer: aws_iam
```

### What stacktrace or error message from your provider did you see?
```
An error occurred while provisioning your stack: MyFunctionNameLambdaFunction
     - my-service-name-production-my-function-name already exists.
```
Worth noting that my service has multiple functions, and the error complains about different functions between deploy attempts.

## Additional Data

* ***Serverless Framework Version you're using***: 1.14.0
* ***Operating System***: OSX
