### ISSUE TITLE
Failing to successfully create a trigger in AWS Lambda

### ISSUE THREAD

**Issue by christiansaiki** [serverless/serverless#3713]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
  -  I've created 5 triggers in cloudwatch events for a lambda function. All the five rules were successfully created in cloudwatch events. But only 4 became triggers

## Additional Data

* ***Serverless Framework Version you're using***: 1.14.0
* ***Operating System***: MacOS Sierra

**Comment by pmuens** [comment]
@christiansaiki thanks for reporting. 👍 

Could you please share your `serverless.yml` so that we can look into it? Thanks!

**Comment by christiansaiki** [comment]
```yml
service: beluga-lambda-jobs 
plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs6.10

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
   - Effect: Allow
     Action:
       - ec2:StartInstances
       - ec2:StopInstances
       - ec2:DescribeInstances
       - ec2:DescribeInstanceStatus
       - ec2:CreateNetworkInterface
       - ec2:DescribeNetworkInterfaces
       - ec2:DeleteNetworkInterface
     Resource: "*"
     Condition:
       StringEquals:
         ec2:Region: us-east-1
   - Effect: Allow
     Action:
       - s3:*
     Resource:
       - arn:aws:s3*

   - Effect: Allow
     Action:
       - kms:Decrypt
     Resource: "*"


# you can define service wide environment variables here
  environment:
   B_ENV: lambda-jobs
   B_PRODUCTION: true

functions:
  startInstanceAndEtl:
    vpc:
      securityGroupIds:
        - <mysg>
      subnetIds:
        - <mysubnet>
    handler: functions/startInstanceAndEtl.startInstanceAndEtl
    timeout: 120
    events:
    # sales_per_marketing_channel
    - schedule:
        name: 'startInstanceAndEtl_sales_per_marketing_channel_everyday'
        enabled: true
        description: 'startInstanceAndEtl_sales_per_marketing_channel_everyday'
        rate: cron(50 9 * * ? *) # DST cron(50 8 * * ? *)
        input:
          databaseName: sales_per_marketing_channel
          periodicity: default
        # sales_per_sku_per_country
    - schedule:
        name: 'startInstanceAndEtl_sales_per_sku_per_country_everyday'
        enabled: true
        description: 'startInstanceAndEtl_sales_per_sku_per_country_everyday'
        rate: cron(0 10 * * ? *) # DST cron(0 9 * * ? *)
        input:
          databaseName: sales_per_sku_per_country
          periodicity: default
  
        # delivery_outbound_events
    - schedule:
        name: 'startInstanceAndEtl_delivery_outbound_events_sunday_to_friday'
        enabled: true
        description: 'startInstanceAndEtl_delivery_outbound_events_sunday_to_friday'
        rate: cron(57 9 ? * SUN-FRI *) # DST cron(55 8 ? * SUN-FRI *)
        input:
          databaseName: delivery_outbound_events
          periodicity: default
    - schedule:
        name: 'startInstanceAndEtl_delivery_outbound_events_saturday'
        enabled: true
        description: 'startInstanceAndEtl_delivery_outbound_events_saturday'
        rate: cron(20 10 ? * SAT *) # DST cron(20 9 ? * SAT *)
        input:
          databaseName: delivery_outbound_events
          periodicity: Saturday
          # warehouse_outbound_events
    - schedule:
        name: 'startInstanceAndEtl_warehouse_outbound_events_everyday'
        enabled: true
        description: 'startInstanceAndEtl_warehouse_outbound_events_everyday'
        rate: cron(47 9 * * ? *) #DST cron(50 8 * * ? *)
        input:
          databaseName: warehouse_outbound_events
          periodicity: default
```
