### ISSUE TITLE
Lambda: SNS events subscriptions only partially registered

### ISSUE THREAD

**Issue by beInDev** [serverless/serverless#3719]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
When I deploy a certain service, not all pre-existing SNS events subscriptions are registered in the lambda triggers. (18 out of 22)
* What did you expect should have happened?
That all the events are properly subscribed too
* What was the config you used?
```YAML
custom:
     baseEventName: { Fn::Join: [':', ["arn:aws:sns",Ref: "AWS::Region", Ref: "AWS::AccountId", "event-${opt:stage, self:provider.stage}"]] }
functions:
    onIncomingMessage:
        handler: index.onIncomingMessage
        events:
        - sns:
            arn: { Fn::Join: ['-', ["${self:custom.baseEventName}", "onBusinessUpdated"]] }
            topicName: onBusinessUpdated
        - sns:
            arn: { Fn::Join: ['-', ["${self:custom.baseEventName}", "onBusinessAccountCompleted"]] }
            topicName: onBusinessAccountCompleted
.... (20 more like that)
```
* What stacktrace or error message from your provider did you see?
N/A

According to CloudFormation, everything was created succesfully

## Additional Data

* ***Serverless Framework Version you're using***: 1.13.2 (but happens with 1.14.0 too)
* ***Operating System***: Linux Mint
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
