### ISSUE TITLE
Changing path of http event in a function doesn't clear the previous function

### ISSUE THREAD

**Issue by guywald** [serverless/serverless#3730]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Changing 'path' value of an http event for a function didn't remove the old path from the stage after _serverless deploy_. Both paths existed.

* What did you expect should have happened?
The previous path to be removed and the new path to exist instead.
* What was the config you used?
Serverless v1.14.10
* What stacktrace or error message from your provider did you see?
Nothing

## Additional Data

* ***Serverless Framework Version you're using***: v1.14.0
* ***Operating System***: osx 10.12.5
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

**Comment by pmuens** [comment]
Thanks for opening @guywald 

Could you please give an example / steps to reproduce? Thanks!

**Comment by guywald** [comment]
I'm not sure if this is a concept of backwards compatibility in the staged api or a diff issue in cloudformation.


**Step 1)** - _serverless depoy_: (handler.hello is the default file which is generated on _sls create -t aws-nodejs_)

**serverless.yml:**
    
```
service: api-end-point-test
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: api/v1/hello
          method: get
```

From the **Api Gateway**:
![apigateway1](https://cloud.githubusercontent.com/assets/1183312/26816263/7d08aad0-4a99-11e7-81cd-944361c2ff94.png)

**Step 2)** - Change the path (removing the _/v1/_)

**changed serverless.yml:**
```
service: api-end-point-test
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: **api/hello**
          method: get
```

The current state of Api Gateway:
![apigateway2](https://cloud.githubusercontent.com/assets/1183312/26816442/4e4e4d16-4a9a-11e7-818d-4b1b40078c1b.png)

I assumed the _/v1/_ routes would not appear after deployment.
