### ISSUE TITLE
DX: Add support for preconfigured event sub-types for simpler event configuration

### ISSUE THREAD

**Issue by brianneisler** [serverless/serverless#3734]
# This is a Feature Proposal

## Description

Currently the only shorthand for existing events is usually by supplying a string after the type declaration which defaults a number of values. 

Example:
```
functions:
  hello: 
    handler: handler.hello
    events:
      - s3: my-bucket 
```
Is shorthand for...
```yaml
functions:  
  hello: 
    handler: handler.hello
    events:
     - s3:
          bucket: my-bucket
          event: s3:ObjectCreated:*
```
However, there are many other available s3 event triggers. It would be nice to introduce a convenience mechanism for other common event types.

Instead of just `[event-type]`,  we could add support for an additional sub-type to support pre-config sets `[event-type].[event-sub-type]`

Example:
```
# current framework s3 definition (more verbose than it needs to be with the sub `event` property)
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: photos
          event: s3:ObjectCreated:*
      - s3:
          bucket: photos
          event: s3:ObjectRemoved:*
```
Same as above with pre-configured subtypes. This is much much easier to write and read.
```
functions:
  users:
    handler: users.handler
    events:
      - s3.ObjectCreated: photos
      - s3.ObjectRemoved: photos
```

Overrides/additional props could be supplied as you would normally expect.
```
functions:
  users:
    handler: users.handler
    events:
      - s3.ObjectCreated:
          bucket: photos
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3.ObjectRemoved:
          bucket: photos
          rules:
            - prefix: uploads/
            - suffix: .jpg
```
