### ISSUE TITLE
Add support for AWS managed policies

### ISSUE THREAD

**Issue by Mortinke** [serverless/serverless#3751]
# This is a Feature Proposal

## Description

Currently, I write lambda functions to create AWS accounts, aws roles, policies, ....  To be able to do this, the lambda functions needs almost all IAM actions. I would like to attach AWS managed policies (e.g. IAMFullAccess) instead of define the content of this policy again. Currently I have to add the following lines in the serverless.yml file:
```
iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "iam:*"
      Resource: "*"
```
I'd be grateful if we can attach AWS managed policies instead, for example:
```
iamRoleStatements:
    policies:
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.14.0
* ***Operating System***: WIN7

**Comment by dmytrozzz** [comment]
I believe this is already implemented and can be closed. E.g.

```
myDefaultRole:
  Type: AWS::IAM::Role
  Properties: 
    ...
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
```

Please refer to documentation from [Serverless](https://serverless.com/framework/docs/providers/aws/guide/iam#one-custom-iam-role-for-all-functions) and [AWS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-managepolicyarns)
