### ISSUE TITLE
Adding authorizer to http returns Invalid lambda function.

### ISSUE THREAD

**Issue by larrybek** [serverless/serverless#3769]
1. Created lambda function
2. added to YAML file
3. Created user pool
4. Copied user pool arn and added to YAML http request
5. returns Invalid lambda function.
6. Removing authorizer works fine

```yaml
commonData:
    handler: common.data
    events:
      - http:
          path: common/data
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-west-*:************:userpool/us-west-*******
```
