### ISSUE TITLE
Support for Cognito User Pool Triggers isn't working.

### ISSUE THREAD

**Issue by keshavkaul** [serverless/serverless#3773]
# This is a Bug Report
## Description
Support for Cognito User Pool Triggers isn't working.

For bug reports:
* What went wrong?
Cannot link lamda to cognito user pool triggers
* What did you expect should have happened?
Cognito user pool triggers should have been updated with the correct lambda.
* What was the config you used?
```yaml
service: hc-cognito-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10

functions:
  customMessageHandler:
    handler: custom-message-handler.handle
    events:
      - cognitoUserPool:
          pool: <my pool Id>
          trigger: CustomMessage
```
* What stacktrace or error message from your provider did you see?
No error messages were seen.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
NA
* If there is additional config how would it look
NA

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.2
* ***Operating System***: MacOS 10.12.5
* ***Stack Trace***: None
* ***Provider Error messages***: None
