### ISSUE TITLE
Support for Multiple authorizers

### ISSUE THREAD

**Issue by pentateu** [serverless/serverless#3782]
# This is a Feature Proposal

## Description
Be able to specify multiple authorizers for a single api end point:

At the moment we are restricted to have only one (at least I could not find in the docs how to specify multiples), example:

```yaml
- http:
    path: graphql
    method: post
    cors:
      origins:
        - '*'
    authorizer:
      arn: arn:aws:cognito-idp:us-east-1:XXXXX:userpool/us-east-XXXXXX
      identitySource: method.request.header.Authorization
```

I can configure multiple authorizers using the API Gateway Web UI. 

In my case I have 2 UserPools and also Facebook authentication  (that I'll implement as a custom authorizer). A user authenticated in any of these should be able to access the API.
