### ISSUE TITLE
Warning Messages

### ISSUE THREAD

**Issue by rahulkulmi** [serverless/serverless#3786]
Getting warning message multiple time when deploy new code on lambda function.
```
Warning, the following targets are using a decimal version:

  node: 6.5

We recommend using a string for minor/patch versions to avoid numbers like 6.10
getting parsed as 6.1, which can lead to unexpected behavior.
```

Serverless version 1.15.3
runtime: nodejs6.10

**Comment by pmuens** [comment]
🤔 hmm. That's strange. Could you please post your `serverless.yml` file?

**Comment by jpdoria** [comment]
I experienced the same thing. I got the same warning message when I started using a plugin.

```
service: lex-client-facebook-chatbot

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  validation:
    handler: index.handler
    description: Client Facebook Chatbot
    memorySize: 128
    timeout: 60
    tags:
      Name: ClientFBChatBot
      CostCenter: Client

plugins:
  - serverless-plugin-optimize
```

**Comment by rahulkulmi** [comment]
This is my serverless.yml file code.
```
service: facebook-bot

frameworkVersion: "=1.15.3"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2

functions:
  app:
    handler: app.handler
    description: Client Facebook Chatbot
    memorySize: 1536
    timeout: 30
    events:
     - http:
         path: user
         method: post

plugins:
  - serverless-plugin-optimize
```
