### ISSUE TITLE
Service name does not get populated when a variable is used

### ISSUE THREAD

**Issue by nicka** [serverless/serverless#3789]
# This is a Bug Report

## Description

The service name is not populated when the variable system is used within plugins.

For bug reports:
* What went wrong?

* What did you expect should have happened?

That `serverless.service.service` returns a string from `package.json:name`.

* What was the config you used?

```yaml
# serverless.yml
service:
  name: ${file(package.json):name}
# OR
service: ${file(package.json):name}
```

```js
// Plugin example
class Foo {
  constructor(serverless, options) {
    this.serverless = serverless;
    this.serviceName = serverless.service.service;
    this.hooks = {
      'deploy:compileEvents': this.functionFoo.bind(this),
    };
  }
}
```

* What stacktrace or error message from your provider did you see?

None.

## Additional Data

* ***Serverless Framework Version you're using***:  ^1.15.3
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
