### ISSUE TITLE
Everytime I run env SLS_DEBUG=true sls deploy I get:

### ISSUE THREAD

**Issue by codepreneur** [serverless/serverless#3794]
# This is a (Bug Report)

## Description
```
env SLS_DEBUG=true sls deploy

Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (7.57 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..............
Serverless: Stack update finished...
Service Information
service: graphql-auth
stage: dev
region: us-west-2
api keys:
  None
endpoints:
  POST - https://asd231gjh2dss.execute-api.us-west-2.amazonaws.com/dev/graphql
functions:
  graphql: graphql-auth-dev-graphql
(node:16145) Warning: a promise was created in a handler at /usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:97:15 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:196:13)
Serverless: Removing old service versions...
```
please return the promise @pmuens :)

## Additional Data

* ***Serverless Framework Version you're using***:
```
1.15.3
```
* ***Operating System***:
![image](https://user-images.githubusercontent.com/3421858/27121393-08b8dfc8-50df-11e7-8112-d7f3c99cd709.png)

* ***Stack Trace***:
```
(node:16145) Warning: a promise was created in a handler at /usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:97:15 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:196:13)
```

**Comment by pmuens** [comment]
Interesting 🤔 

Thanks for opening @codepreneur 👍 

Could you please share your `serverless.yml` file so that we can look into the config you've used as well?

Thanks!

**Comment by codepreneur** [comment]
@pmuens sure:

```
service: graphql-auth 

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  stage: dev
  region: us-east-1
  timeout: 6
  memorySize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true

```

everything works and gets deployed like it should, its just that error keeps annoying me ;)
