### ISSUE TITLE
Cannot package function: Buffer exception

### ISSUE THREAD

**Issue by LucasObendorf** [serverless/serverless#3807]
# This is a Bug Report

## Description

Cannot package any function. Getting a low information buffer error.

I have tried serverless 1.15.3, 1.15.2, 1.15.0, and 1.14.0 and have received the same error.

Error:
``` sh
Serverless: Packaging function: api...
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:37:10)
    at allocate (buffer.js:189:12)
    at Function.Buffer.allocUnsafe (buffer.js:152:10)
    at tryCreateBuffer (fs.js:468:21)
    at Object.fs.readFileSync (fs.js:502:14)
    at files.forEach (/home/vagrant/.npm-global/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:62:25)
    at Array.forEach (native)
    at WriteStream.output.on (/home/vagrant/.npm-global/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:53:13)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:191:7)
    at WriteStream.<anonymous> (fs.js:2041:10)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

serverless.yml:
``` yml
service: service
provider:
  name: aws
  runtime: python2.7
  region: us-west-1
package:
  individually: true

functions:
  api:
    handler: handler.Handler
    package:
      artifact: .functions/api.zip
plugins:
  - serverless-plugin-localstack

custom:
  localstack:
    endpoint: localstack_endpoints.json
```

I have also used this serverless config without the localstack plugin and obtained the same error:
``` yml
service: service
provider:
  name: aws
  runtime: python2.7
  region: us-west-1
package:
  individually: true

functions:
  api:
    handler: handler.Handler
    package:
      artifact: .functions/api.zip
```

Commands tried that output the error:
``` sh
serverless deploy
serverless deploy function -f api
serverless package
```
## Additional Data

Environment Info:
``` sh
Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           7.10.0
     Serverless Version:     1.15.3
```

* Linux 16.04 on a vmware workstation virtual machine
* launching and managing the vm with Vagrant version 1.9.2
