### ISSUE TITLE
Support for S3 tags when using a deployment bucket

### ISSUE THREAD

**Issue by bclodius** [serverless/serverless#3817]
# This is a Feature Proposal

## Description

Configuration should support an option for tagging for deploymentBucket.  Example below.

```yaml
provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  timeout: 20
  deploymentBucket:
    name: mybucket.test
    tags:
      CostCenter: 1234
      Email: myemail@example.com
```

I would like to attempt the PR for this if admin's are supportive.
