### ISSUE TITLE
Setting function with Serverless Variables not working

### ISSUE THREAD

**Issue by jayzalowitz** [serverless/serverless#3818]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 
    Failure to deploy
* What did you expect should have happened?
   Deployment
* What was the config you used?

```
service: my-lambda-test # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "= 1.15.4-alpha.1"

provider:
  name: aws
  runtime: python2.7
  # stage: dev
  region: us-east-1
  memorySize: 256 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  role: rolenameishere
  profile: cantsay
  deploymentBucket:
    # name: my.serverless.deployment.bucket.test
    serverSideEncryption: AES256

functions:
  test-lambda:
    handler: health-check/handler.hello # required, handler set in AWS Lambda
    name: test-lambda-stuff- # ${self:provider.stage} optional, Deployed Lambda name
    description: This is a test # optional, Description to publish to AWS
    runtime: python2.7 # optional overwrite, default is provider runtime
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6

  hello-world:
    handler: health-check/handler.hello
```
* What stacktrace or error message from your provider did you see?

$ sls deploy -s dev -verbose
Serverless: Packaging service...
 
  Serverless Error ---------------------------------------
 
  The stack service name "my-lambda-test-dev,true" is not valid. A service name should only contain alphanumeric (case sensitive) and hyphens. It should start with an alphabetic character and shouldn't exceed 128 characters.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.8.0
     Serverless Version:     1.15.4-alpha.1

If i uncomment the bucketname it becomes Could not locate deployment bucket. Error: this.getStage(...).toUpperCase is not a function

**Comment by pmuens** [comment]
Thanks for testing out the alpha and reporting the bug @jayzalowitz 👍 

Do you deploy this service from scratch or do you update an existing deployment with the config above?

**Comment by pmuens** [comment]
Hey @jayzalowitz just a quick update.

I tried to reproduce this but (un)fortunately was not able to do so.

Could you shed some more light into the steps you've done to get this error? Thanks in advance! 👍

**Comment by jayzalowitz** [comment]
```
$ sls deploy -s dev -verbose
 
  Serverless Error ---------------------------------------
 
  Could not locate deployment bucket. Error: this.getStage(...).toUpperCase is not a function
 
  Stack Trace --------------------------------------------
 
ServerlessError: Could not locate deployment bucket. Error: this.getStage(...).toUpperCase is not a function
    at AwsPackage.BbPromise.bind.then.then.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/lib/generateCoreTemplate.js:40:17)
From previous event:
    at AwsPackage.generateCoreTemplate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/lib/generateCoreTemplate.js:39:15)
From previous event:
    at Object.package:initialize [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/index.js:60:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:229:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:95:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:93:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:103:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:90:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:30:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.8.0
     Serverless Version:     1.15.4-alpha.1
``
```

**Comment by jayzalowitz** [comment]
Deploy from scratch

**Comment by pmuens** [comment]
Thanks for sharing @jayzalowitz 👍 

We'll look into it and try tor reproduce it.

**Comment by jayzalowitz** [comment]
@pmuens This is still effecting 1.16 for me.

Removing the deployment bucket keeps the this.getstage issue.
Im happy to get on a call with you guys if you want.

**Comment by pmuens** [comment]
Thanks for getting back @jayzalowitz 👍 

I think the problem is your deployment bucket.

Right now you could either use the `deploymentBucket` you need to setup beforehand with the encryption. Or the one Serverless generates automatically for you (which has no encryption).

Automatic encryption for the deployment bucket Serverless generates for you is currently not supported.

**Comment by jayzalowitz** [comment]
The deploymentBucket was already set up before hand.

Also according to the branch you merged that would be the case, as all objects have that encryption tag.

I was able to get an initial deployment out by removing the .toUpperCase() in this line:
https://github.com/serverless/serverless/blame/b87326d5dda83ac2a81e3825ecf25abb19b06ec9/lib/plugins/aws/provider/awsProvider.js#L179

Dont know if that helps, but it might be getting invoked differently by the bucket code added below.

**Comment by pmuens** [comment]
Nice catch! Thanks for digging deeper into this @jayzalowitz 👍 

Still a little but unsure how the code of the deployment bucket might interfere here 🤔 

Just pasting the PR URL here: https://github.com/serverless/serverless/pull/3804

It seems to have smth. todo with the credentials lookup. You're using a different profile to deploy your service. Could you try to deploy with your default profile (and comment out the `provider.profile` config) to see if it's related to that?

Thanks in advance 👍 

---

Were you able to get the encryption support working for your project? Or is this still a blocker for you?

**Comment by pmuens** [comment]
Ok. I think I got another idea.

```yml
functions:
  test-lambda:
    handler: health-check/handler.hello # required, handler set in AWS Lambda
    name: test-lambda-stuff- # ${self:provider.stage} optional, Deployed Lambda name
```

It looks like the initial error with the wrong function name ("The stack service name "my-lambda-test-dev,true" is not valid.") is caused by the usage of the Serverless Variables system.

It seems like some values are missing during the population.

Don't know how the `serverless.yml` config looks like you're using for deployment though.
