### ISSUE TITLE
Set a custom Role

### ISSUE THREAD

**Issue by davidgatti** [serverless/serverless#3822]
# This is a questions

## Description

![screen shot 2017-06-21 at 12 39 41 pm](https://user-images.githubusercontent.com/411114/27380357-16c1e92a-567f-11e7-94f2-0cf2ac6ccf50.png)

I want to set a custom role for my Lambda function, and I have the following:

```
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  role: arn:aws:iam::28240630XXXX:role/LambdaExecutionRole
```

This doesn't work, and I have to set it manually as shown in the screenshot above. What did I miss?

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.3
* ***Operating System***: Debian
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by pmuens** [comment]
Hey @davidgatti thanks for opening 👍 

Could you please provider the whole `serverless.yml` file since the role can be e.g. overwritten on a function level or via `iamRoleStatements`.

Thanks in advance!

**Comment by davidgatti** [comment]
No problemo, there you go :) 

```
service: amazingname

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  role: arn:aws:iam::28240630XXXX:role/LambdaExecutionRole

functions:
  handler:
    handler: handler.autodeploy
    description: This functions waits for S3 to Autodeploy new code
    tags:
      env: development
    events:
      - s3:
          bucket: io.sequr.repos.dev
          event: s3:ObjectCreated:*
```
