### ISSUE TITLE
Support all intrinsic functions for SNS definition

### ISSUE THREAD

**Issue by timsuchanek** [serverless/serverless#3824]
# This is a Bug Report

## Description

The docs state, that you can use cloudformation intrinsic functions while defining the sns source for a function, however, when I take this example:
```yaml
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":MyCustomTopic"
          topicName: MyCustomTopic
```
and adjust it to ours needs
```yaml
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":"
                - { Fn::GetAtt: [ Infrastructure, Outputs.SNSTopic ] }
          topicName: { Fn::GetAtt: [ Infrastructure, Outputs.SNSTopic ] }
```
it returns the following error:
```sh
  Stack Trace --------------------------------------------

TypeError: event.sns.arn.indexOf is not a function
    at functionObj.events.forEach.event (/Users/tim/npm-global/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:36:44)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/Users/tim/npm-global/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:22:28)
    at Array.forEach (native)
    at AwsCompileSNSEvents.compileSNSEvents (/Users/tim/npm-global/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:18:47)
    at BbPromise.reduce (/Users/tim/npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:254:55)
From previous event:
    at PluginManager.invoke (/Users/tim/npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:254:22)
    at PluginManager.spawn (/Users/tim/npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:266:17)
    at Deploy.BbPromise.bind.then (/Users/tim/npm-global/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:88:48)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/tim/npm-global/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:86:8)
    at BbPromise.reduce (/Users/tim/npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:254:55)
From previous event:
    at PluginManager.invoke (/Users/tim/npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:254:22)
    at PluginManager.run (/Users/tim/npm-global/lib/node_modules/serverless/lib/classes/PluginManager.js:273:17)
    at variables.populateService.then (/Users/tim/npm-global/lib/node_modules/serverless/lib/Serverless.js:105:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/tim/npm-global/lib/node_modules/serverless/lib/Serverless.js:92:74)
    at serverless.init.then (/Users/tim/npm-global/lib/node_modules/serverless/bin/serverless:30:50)
```
The example how it is in the docs works without problems, but adding the `Fn::GetAtt` makes it fail.

Related PR
- https://github.com/serverless/serverless/pull/3443/files

## Additional Data

Your Environment Information
- OS:                     darwin
- Node Version:           7.9.0
- Serverless Version:     1.15.3

**Comment by pmuens** [comment]
Thanks for opening @timsuchanek 👍 

Just dropping a line that the global `arn` parser could help here: https://github.com/serverless/serverless/issues/3212

**Comment by jaikdean** [comment]
+1

**Comment by gabrielkaputa** [comment]
+1

**Comment by itzaliza** [comment]
+1

**Comment by reidblomquist** [comment]
+1 poked around looks like the type checking in `serverless/lib/plugins/aws/package/compile/events/sns/index.js` is way too fuzzy and allows for indexOf to be called on objects - if trying to define TopicName as an object it skips the first check in typeof event.topicName === 'string' and tries to reference the indexOf on event.sns.arn inside of an if that checks typeof event.sns.arn === 'object' || 'string'...  Ideally this would at least be patched for now with a more meaningful error until it can properly parse objects

**Comment by crysislinux** [comment]
any updates? I have to hardcode those arn related things for now. Feels not flexible.

**Comment by astroanu** [comment]
Is this being investigated ??

**Comment by AJF4** [comment]
+1 - any updates on this?

**Comment by DavidJFelix** [comment]
We're also running into this using `Fn::ImportValue` we have one serverless project which defines and exports the arn of the event from the outputs section of resources and the other attempts to import them and fails with the same error shown above.

```yaml
 hello:
    handler: handleHelloTopic
    events:
      - sns: 
          arn: {Fn::ImportValue: 'HelloSNSTopicArn'}
```

**Comment by gaviniflix** [comment]
```yml
handler: src/handlers/on-demand-extensions/index.extensionCreated
events:
  - sns: 
      arn:
        Fn::GetAtt:
          - OnDemandExtensionsCreatedTopic
          - Arn
      topicName: 
        Fn::Gett:
          - OnDemandExtensionsCreatedTopic
          - TopicName
```
gives me: 
```
TypeError: event.sns.arn.indexOf is not a function
    at functionObj.events.forEach.event (/Users/gavinvangent/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:35:44)
    at Array.forEach (native)
    at serverless.service.getAllFunctions.forEach (/Users/gavinvangent/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:22:28)
```

**Comment by drexler** [comment]
+1 here. is there a workaround in the  interim for this? Using `serverless@1.30.1`

**Comment by ttdiemchi** [comment]
Any update on this?

**Comment by hmshwt** [comment]
@gaviniflix I found a work around by using the custom section in serverless.yml. I import the arn value from another cloudformation stack there.
```yaml
custom:
  snsTopic:
    Fn::ImportValue: 'other-cloudformation-stack-${self:provider.stage}:TopicName'
```
and later in the events section I substitute it:
```yaml
    events:
      - sns:
          arn: ${self:custom.snsTopic}
          topicName: 'TopicName'
```
It works for me on SLS version 1.32.0, node 8.10.0 . I hope it is helpful for you too.

**Comment by yahehe** [comment]
@hmshwt I'm using the same version of SLS, node 8.12.0, and that does not work for me.

**Comment by hmshwt** [comment]
@yahehe Could you please paste the error and the relevant section of the serverless.yml file.

**Comment by yahehe** [comment]
Serverless:
```
custom:
  snsTopic:
    Fn::ImportValue: '${self:provider.stage}:other-stack:OtherStackTopicName'
...
    events:
      - sns:
          arn: ${self:custom.snsTopic}
```

Error:
```
Type Error ---------------------------------------------

  event.sns.arn.indexOf is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: event.sns.arn.indexOf is not a function
    at functionObj.events.forEach.event (/usr/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:35:44)
    at Array.forEach (<anonymous>)
    at serverless.service.getAllFunctions.forEach (/usr/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:22:28)
    at Array.forEach (<anonymous>)
    at AwsCompileSNSEvents.compileSNSEvents (/usr/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:18:47)
    at BbPromise.reduce (/usr/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
```

**Comment by hmshwt** [comment]
@yahehe Have you tried adding
```yaml
topicName: 'TopicName'
```
after 
```yaml
arn: ${self:custom.snsTopic}
```
?

**Comment by yahehe** [comment]
That won't do anything, the way the code is structured will have it fail before it looks at the topic name. I'm working on a fix now

**Comment by hmshwt** [comment]
@yahehe I tried to remove the topicName property and I get the same error as you did
```
event.sns.arn.indexOf is not a function ...
```
Once I add it back, the deployment is successful. 
Anyway, thank you for working on solving the root problem and I hope it is merged soon.

**Comment by yahehe** [comment]
@hmshwt ah you know what, I think you might be right. Part of my issue is I was trying to have `topicName` be a function as well, as it wasn't clear that it's really only being used to name the cloudformation resources.

**Comment by chensjlv** [comment]
Just figured out, by reading https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/sns/index.js#L32

topicName has to be a string for this to work.

```
functions:
  ***:
    handler: ***/***
    events:
      - sns:
          arn:
            Ref: SnsTopic
          topicName: ${self:custom.snsTopic}
```

**Comment by nkhine** [comment]
i am also getting this error, here is my serverless.yml

```
  s3ToFtp:
    handler: bin/s3-to-ftp
    # files are stored in memory, Ram should be sufficient to accomdate the file
    memorySize: 256
    timeout: 120
    package:
      individually: true
      include:
        - ./bin/s3-to-ftp
    environment:
      FTP_HOST: ${file(./config.yml):${opt:stage}.FTP_HOST}
      FTP_USERNAME: ${file(./config.yml):${opt:stage}.FTP_USERNAME}
      FTP_PASSWORD: ${file(./config.yml):${opt:stage}.FTP_PASSWORD}
    events:
      - sns:
          arn:
            Fn::GetAtt:
              - OriginalFileUploadSNSTopic
              - Arn
```

and my resource, section:

```
      OriginalFileUploadSQSQueue:
        Type: AWS::SQS::Queue
        Properties:
          MessageRetentionPeriod:
            Ref: MessageRetentionPeriod
          # QueueName:
          #   Ref: QueueName
          VisibilityTimeout:
            Ref: VisibilityTimeout
      OriginalFileUploadSQSQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
          PolicyDocument:
            Version: '2008-10-17'
            Statement:
            - Effect: Allow
              Principal:
                AWS: "*"
              Action:
              - SQS:SendMessage
              Resource: "*"
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: OriginalFileUploadSNSTopic
          Queues:
            - Ref: OriginalFileUploadSQSQueue
      OriginalFileUploadSNSTopic:
        Type: AWS::SNS::Topic
        Properties:
          Subscription:
          - Endpoint:
              Fn::GetAtt:
              - OriginalFileUploadSQSQueue
              - Arn
            Protocol: sqs
```

produces:

```
TypeError: event.sns.arn.indexOf is not a function
    at functionObj.events.forEach.event (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:35:44)
    at Array.forEach (<anonymous>)
    at serverless.service.getAllFunctions.forEach (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:22:28)
    at Array.forEach (<anonymous>)
    at AwsCompileSNSEvents.compileSNSEvents (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sns/index.js:18:47)
    at BbPromise.reduce (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
From previous event:
    at PluginManager.invoke (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at Deploy.BbPromise.bind.then (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:407:55)
From previous event:
    at PluginManager.invoke (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.run (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:438:17)
    at variables.populateService.then.then (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless:43:28)
    at /home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at /home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/home/khine/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
