### ISSUE TITLE
Custom authorizer - Does not get triggered

### ISSUE THREAD

**Issue by sajeetharan** [serverless/serverless#3828]
I am  using a custom authorize lambda function with Node to authenticate the apis, after deploying i can manually test authorize function and it logs the errors in cloud watch. But when i request the same api through postman, it does not log anything on the cloud watch. It always returns the error 401 unauthorized.

Here is the code:

```
functions:
 testAuthorize:
    handler: handler.testAuthorize
accountFunctions:
    handler: handler.accountFunctions
    events:
      - http:
            path: account/testApi
            method : get
            authorizer: testAuthorize
```
