### ISSUE TITLE
http-proxy integration with path variables fails to deploy

### ISSUE THREAD

**Issue by wmagda** [serverless/serverless#3840]
# Bug Report

## Description
I believe there is a bug here when you combine path variable with http-proxy integration.
Example:
  ```
  handler: membership/handler.get
    timeout: 20 # optional, default is 6
    events:
      - http:
          path: membership/{sub}
          method: get
          cors: true
          integration: http-proxy # or http
          request:
            uri: https://www.mywebsite.com/user/{sub}/ # required
            parameters:
              paths:
                sub: true
```

* What went wrong?
This results in cloud formation code that looks like this:
```
"ApiGatewayMethodUserSubVarGet": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "GET",
        "RequestParameters": {
          "paths": {
            "sub": true
          }
        },
```

instead of something like this:
```
"ApiGatewayMethodUserSubVarGet": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "GET",
        "RequestParameters": {
          "method.request.path.sub": true
        },
```

* What stacktrace or error message from your provider did you see?
This results in the following error:
` An error occurred while provisioning your stack: ApiGatewayMethodMembershipSubVarGet - Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression specified: paths].`

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.0
* ***Operating System***: OSX
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a
