### ISSUE TITLE
When http indenting in yml isn't correct error message doesn't mention function name that has the issue

### ISSUE THREAD

**Issue by activescott** [serverless/serverless#3845]
# This is a Bug Report

## Description

When a function is improperly indented like so (note path & method are not properly indented under http):

```
  pingfunction:
    handler: handler.ping
    events:
      - http:
      path: api/ping
      method: get
```

For bug reports:
The actual error message is `Cannot read property 'path' of null` and doesn't mention the function name with the problem.

* What did you expect should have happened?
Expected the function name to be in the error message to make it easier to find the source of this generic error.

* What was the config you used?
release

* What stacktrace or error message from your provider did you see?
none

## Additional Data

* ***Serverless Framework Version you're using***:
1.15.3

* ***Operating System***:
macOS

* ***Stack Trace***:
none

* ***Provider Error messages***:
