### ISSUE TITLE
S3 bucket event does not create bucket as documented

### ISSUE THREAD

**Issue by cove** [serverless/serverless#3851]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Creating an S3 event didn't create the S3 bucket as documented.

* What did you expect should have happened?
The S3 bucket would be created as documented.

From https://serverless.com/framework/docs/providers/aws/events/s3/:
> This will create a photos bucket which fires the resize function when an object is added or modified inside the bucket. A hardcoded bucket name can lead to issues as a bucket name can only be used once in S3. For that you can use the Serverless Variable syntax and add dynamic elements to the bucket name.

* What was the config you used?

From https://serverless.com/framework/docs/providers/aws/events/s3/
```
service: serverless-event-test

provider:
  name: aws
  runtime: python2.7

functions:
  resize:
    handler: resize.handler
    events:
      - s3: photos
```

* What stacktrace or error message from your provider did you see?
No errors, silently doesn't get created.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* 

## Additional Data

* ***Serverless Framework Version you're using***:
  1.16.0
* ***Operating System***:
darwin
* ***Stack Trace***:
(see above)
* ***Provider Error messages***:
none

**Comment by cove** [comment]
Closing since after doing an npm update the issue appears to have gone away.

**Comment by pmuens** [comment]
> Closing since after doing an npm update the issue appears to have gone away.

Thanks for getting back and providing the solution for this @cove 👍 Glad to hear that it's resolved.

**Comment by rikbrown** [comment]
Also seeing this problem.   Function setup as below but don't see any S3 bucket called "photos".

```
functions:
  resize:
    handler: codes.rik.greeter.hypogen.vision.lambda.handler.VisionHypogenHandler
    events:
      - s3:
        bucket: photos
```
