### ISSUE TITLE
API Gateway with CORS enabled not deploying correctly

### ISSUE THREAD

**Issue by brettcooper** [serverless/serverless#3867]
# This is a (Bug Report / Feature Proposal)
Bug Report

## Description

For bug reports:
* What went wrong? 
   I have a REST API I am deploying to API Gateway with CORS enabled.  But, when deploying the API, CORS is not working as expected. I ended up having to go into API Gateway, enabling CORS on each REST API endpoint and redeploying the API in order for CORS to work.
* What did you expect should have happened? The REST API should deploy successfully with CORS enabled and shouldn't require manual intervention to get it working.
* What was the config you used?

```
service: unific-rest-api-lambda

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.15.0"

plugins:
  - serverless-plugin-lambda-dead-letter
  - serverless-plugin-aws-alerts
  - serverless-sqs-alarms-plugin
  - serverless-aws-documentation

provider:
  name: aws
  runtime: java8
  region: us-west-2
  profile: circle-ci
  versionFunctions: true
  role: arn:aws:iam::188664007186:role/omnipotent_lambda_role

  deploymentBucket: unific-lambdas
  # This is a workaround to get the base path mapping to run after the lambda is created so the first deploy works
  # https://github.com/serverless/serverless/issues/2233
  apiKeys:
    - ${self:custom.stage}-${self:service}

# you can add packaging information here
package:
  artifact: target/unific-rest-api-lambda-${file(target/classes/version.yml):version}.jar

functions:
  unific-rest-api-campaign-lambda:
    handler: com.unific.api.campaigns.CampaignRestHandler::handleRequest
    name: ${self:custom.stage}-unific-rest-api-campaign-lambda
    memorySize: 1536
    timeout: 30
    description: Handles HTTP REST requests for campaigns.
    environment: ${file(env.yml):${self:custom.stage}}

    events:
      - http:
          path: /v1/campaigns/{id}
          method: any
          authorizer:
            name: ${self:custom.stage}-application-scoped-authorization-lambda
            arn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-application-scoped-authorization-lambda
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer .+$
            resultTtlInSeconds: 0
            cors: true
          documentation:
            summary: "Campaigns API endpoint."
            description: "Create, Read or Update a campaign based on the campaign id."
            requestHeaders:
              - name: "Authorization"
                description: "Authorization header: Bearer <Auth0JWT>."
                required: true
            pathParams:
              - name: "id"
                description: "The campaign id."

      - http:
          path: /v1/campaigns
          method: any
          authorizer:
            name: ${self:custom.stage}-application-scoped-authorization-lambda
            arn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-application-scoped-authorization-lambda
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer .+$
            resultTtlInSeconds: 0
            cors: true
          documentation:
            summary: "Campaigns API endpoint."
            description: "Read all campaigns for a given application id."
            requestHeaders:
              - name: "Authorization"
                description: "Authorization header: Bearer <Auth0JWT>."
                required: true

    deadLetter:
          sqs: ${self:custom.stage}-unific-rest-api-campaign-lambda-dlq  # New Queue with this name
          delaySeconds: 60
          maximumMessageSize: 2048
          messageRetentionPeriod: 200000
          receiveMessageWaitTimeSeconds: 15
          visibilityTimeout: 300

    alarms: # merged with function alarms
          - name: ${self:custom.stage}-unific-rest-api-campaign-lambda-errors-alarm
            namespace: 'AWS/Lambda'
            metric: errors # define custom metrics here
            threshold: 1
            statistic: Minimum
            period: 60
            evaluationPeriods: 1
            comparisonOperator: GreaterThanThreshold

    vpc: ${self:custom.vpc}
    awsKmsKeyArn: arn:aws:kms:${self:provider.region}:188664007186:key/5c6cb7c4-0fec-4eb0-8628-6c8a7dbf857e

    unificRestApiCampaignLambdaLogAggregationSubscriptionFilter:
      Type: AWS::Logs::SubscriptionFilter
      DependsOn: UnificDashRestDashApiDashlambdaLogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:custom.stage}-unific-rest-api-campaign-lambda
        FilterPattern: "[timestamp=20*, region=us*, initialAwsRequestId, awsRequestId, functionName, functionVersion, level, logger, message]"
        DestinationArn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-elasticsearch-log-aggregation

  unific-rest-api-orderconfirmation-statistics-lambda:
    handler: com.unific.api.orderconfirmations.OrderConfirmationStatisticsRestHandler::handleRequest
    name: ${self:custom.stage}-unific-rest-api-orderconfirmation-statistics-lambda
    memorySize: 1536
    timeout: 30
    description: Handles HTTP REST requests for order confirmation statistics.
    environment: ${file(env.yml):${self:custom.stage}}
    events:
      - http:
          path: /v1/orderconfirmationstats
          method: any
          authorizer:
            name: ${self:custom.stage}-application-scoped-authorization-lambda
            arn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-application-scoped-authorization-lambda
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer .+$
            resultTtlInSeconds: 0
            cors: true
          documentation:
            summary: "Order confirmation email statistics API endpoint."
            description: "Returns a list of all campaigns and their order confirmation email statistics."
            requestHeaders:
              - name: "Authorization"
                description: "Authorization header: Bearer <Auth0JWT>."
                required: true

    deadLetter:
          sqs: ${self:custom.stage}-unific-rest-api-orderconfirmation-statistics-lambda-dlq  # New Queue with this name
          delaySeconds: 60
          maximumMessageSize: 2048
          messageRetentionPeriod: 200000
          receiveMessageWaitTimeSeconds: 15
          visibilityTimeout: 300

    alarms: # merged with function alarms
          - name: ${self:custom.stage}-unific-rest-api-orderconfirmation-statistics-lambda-errors-alarm
            namespace: 'AWS/Lambda'
            metric: errors # define custom metrics here
            threshold: 1
            statistic: Minimum
            period: 60
            evaluationPeriods: 1
            comparisonOperator: GreaterThanThreshold

    vpc: ${self:custom.vpc}
    awsKmsKeyArn: arn:aws:kms:${self:provider.region}:188664007186:key/5c6cb7c4-0fec-4eb0-8628-6c8a7dbf857e

    unificRestApiOrderConfirmationStatisticsLambdaLogAggregationSubscriptionFilter:
      Type: AWS::Logs::SubscriptionFilter
      DependsOn: UnificDashRestDashApiDashlambdaLogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:custom.stage}-unific-rest-api-orderconfirmation-statistics-lambda
        FilterPattern: "[timestamp=20*, region=us*, initialAwsRequestId, awsRequestId, functionName, functionVersion, level, logger, message]"
        DestinationArn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-elasticsearch-log-aggregation

  unific-rest-api-couponrule-lambda:
    handler: com.unific.api.couponrules.CouponRuleRestHandler::handleRequest
    name: ${self:custom.stage}-unific-rest-api-couponrule-lambda
    memorySize: 1536
    timeout: 30
    description: Handles HTTP REST requests for couponrules.
    environment: ${file(env.yml):${self:custom.stage}}

    events:
      - http:
          path: /v1/couponrules/{id}
          method: any
          authorizer:
            name: ${self:custom.stage}-application-scoped-authorization-lambda
            arn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-application-scoped-authorization-lambda
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer .+$
            resultTtlInSeconds: 0
            cors: true
          documentation:
            summary: "couponrules API endpoint."
            description: "Create, Read or Update a couponrule based on the couponrule id."
            requestHeaders:
              - name: "Authorization"
                description: "Authorization header: Bearer <Auth0JWT>."
                required: true
            pathParams:
              - name: "id"
                description: "The couponrule id."

      - http:
          path: /v1/couponrules
          method: any
          authorizer:
            name: ${self:custom.stage}-application-scoped-authorization-lambda
            arn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-application-scoped-authorization-lambda
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer .+$
            resultTtlInSeconds: 0
            cors: true
          documentation:
            summary: "couponrules API endpoint."
            description: "Read all couponrules for a given application id."
            requestHeaders:
              - name: "Authorization"
                description: "Authorization header: Bearer <Auth0JWT>."
                required: true

    deadLetter:
          sqs: ${self:custom.stage}-unific-rest-api-couponrule-lambda-dlq  # New Queue with this name
          delaySeconds: 60
          maximumMessageSize: 2048
          messageRetentionPeriod: 200000
          receiveMessageWaitTimeSeconds: 15
          visibilityTimeout: 300

    alarms: # merged with function alarms
          - name: ${self:custom.stage}-unific-rest-api-couponrule-lambda-errors-alarm
            namespace: 'AWS/Lambda'
            metric: errors # define custom metrics here
            threshold: 1
            statistic: Minimum
            period: 60
            evaluationPeriods: 1
            comparisonOperator: GreaterThanThreshold

    vpc: ${self:custom.vpc}
    awsKmsKeyArn: arn:aws:kms:${self:provider.region}:188664007186:key/5c6cb7c4-0fec-4eb0-8628-6c8a7dbf857e

    unificRestApiCouponRuleLambdaLogAggregationSubscriptionFilter:
      Type: AWS::Logs::SubscriptionFilter
      DependsOn: UnificDashRestDashApiDashlambdaLogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:custom.stage}-unific-rest-api-couponrule-lambda
        FilterPattern: "[timestamp=20*, region=us*, initialAwsRequestId, awsRequestId, functionName, functionVersion, level, logger, message]"
        DestinationArn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-elasticsearch-log-aggregation

  unific-rest-api-products-lambda:
    handler: com.unific.api.products.ProductsRestHandler::handleRequest
    name: ${self:custom.stage}-unific-rest-api-products-lambda
    memorySize: 1536
    timeout: 30
    description: Handles HTTP REST requests for listing products and its variants.
    environment: ${file(env.yml):${self:custom.stage}}
    events:
      - http:
          path: /v1/products
          method: any
          authorizer:
            name: ${self:custom.stage}-application-scoped-authorization-lambda
            arn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-application-scoped-authorization-lambda
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer .+$
            resultTtlInSeconds: 0
            cors: true
          documentation:
            summary: "Products API endpoint."
            description: "Gets a list of all products for the given application."
            requestHeaders:
              - name: "Authorization"
                description: "Authorization header: Bearer <Auth0JWT>."
                required: true

    deadLetter:
          sqs: ${self:custom.stage}-unific-rest-api-products-lambda-dlq  # New Queue with this name
          delaySeconds: 60
          maximumMessageSize: 2048
          messageRetentionPeriod: 200000
          receiveMessageWaitTimeSeconds: 15
          visibilityTimeout: 300

    alarms: # merged with function alarms
         - name: ${self:custom.stage}-unific-rest-api-products-lambda-errors-alarm
           namespace: 'AWS/Lambda'
           metric: errors # define custom metrics here
           threshold: 1
           statistic: Minimum
           period: 60
           evaluationPeriods: 1
           comparisonOperator: GreaterThanThreshold

    vpc: ${self:custom.vpc}
    awsKmsKeyArn: arn:aws:kms:${self:provider.region}:188664007186:key/5c6cb7c4-0fec-4eb0-8628-6c8a7dbf857e

    unificRestApiProductsLambdaLogAggregationSubscriptionFilter:
      Type: AWS::Logs::SubscriptionFilter
      DependsOn: UnificDashRestDashApiDashlambdaLogGroup
      Properties:
        LogGroupName: /aws/lambda/${self:custom.stage}-unific-rest-api-products-lambda
        FilterPattern: "[timestamp=20*, region=us*, initialAwsRequestId, awsRequestId, functionName, functionVersion, level, logger, message]"
        DestinationArn: arn:aws:lambda:${self:provider.region}:188664007186:function:${self:custom.stage}-elasticsearch-log-aggregation

resources:
  Resources:
    unificRestApiPathMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn: ApiGatewayApiKey1
      Properties:
        BasePath: api
        DomainName: ${file(domains.yml):${self:custom.stage}}
        RestApiId:
            Ref: ApiGatewayRestApi
        Stage: ${self:custom.stage}

custom:
  notifications:
    - protocol: sns
      endpoint: ${self:custom.opsTeamArn}

  opsTeamArn: arn:aws:sns:${self:provider.region}:188664007186:UnificOpsTeam

  alerts:
    topics:
      alarm:
        topic: ${self:custom.stage}-${self:service}-alerts-alarm
        notifications: ${self:custom.notifications}
    global:
      - functionThrottles

  stage: "${opt:stage, self:provider.stage}"
  vpc: ${file(vpc.yml):${self:custom.stage}}

  sqs-alarms:
    - queue: ${self:custom.stage}-${self:service}-dlq
      topic: ${self:custom.alerts.topics.alarm.topic}
      thresholds:
        - 1

  documentation:
      version: ${file(target/classes/version.yml):version}
      summary: "Unific's REST API."
      description: "Unific's REST API for calling methods on the backend."
      authorizers:
        - name: ${self:custom.stage}-application-scoped-authorization-lambda
          description: "Auth0 lambda authorizer."
```

* What stacktrace or error message from your provider did you see?

I tried a CORS enabled AJAX request at https://resttesttest.com/ to verify CORS was working on the REST endpoint (it was not working).

Oh no! Javascript returned an HTTP 0 error. One common reason this might happen is that you requested a cross-domain resource from a server that did not include the appropriate CORS headers in the response. Better open up your Firebug...

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #3330 
* #3840 

## Additional Data

* ***Serverless Framework Version you're using***: 1.15.3
* ***Operating System***: OS X - El Capitain
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @brettcooper thanks for opening 👍 

It looks like the `cors` config setup you're using is wrong.

It needs to be indented right under the `http` event like this: https://serverless.com/framework/docs/providers/aws/events/apigateway#enabling-cors

**Comment by brettcooper** [comment]
Dope!  I feel like an idiot.  I fixed the spacing issue and the CORS setup is now working correctly!  One thing that might be nice to have is if the serverless.yml syntax is bad then throw an error.  That way in the future, if the yml syntax is off, I'll at least get an error so I know I need to fix it.  Thank you so much for your help!

**Comment by pmuens** [comment]
> Dope! I feel like an idiot. I fixed the spacing issue and the CORS setup is now working correctly! One thing that might be nice to have is if the serverless.yml syntax is bad then throw an error. That way in the future, if the yml syntax is off, I'll at least get an error so I know I need to fix it. Thanks @pmuens so much for your help!

Great! Thanks for getting back @brettcooper 👍 Glad to hear that the issue was resolved 💪 

Thanks for the proposal to validate the `serverless.yml` file. This is already on our radar. 💯 

Let us know if you face any other issues.

**Comment by bertero** [comment]
Hello guys (@pmuens),
I am facing a similar issue. However it seems that my `serverless.yml` looks correct.

```yml
service: person-server
provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  region: sa-east-1
  apiKeys:
    - ${env:PERSON_API_KEY}
  vpc:
    securityGroupIds:
      - ${env:AWS_SG}
    subnetIds:
      - ${env:AWS_PRIVATE_SUBNET_1}
      - ${env:AWS_PRIVATE_SUBNET_2}
package:
  exclude:
    - .git/**
    - .commands/**
    - __mocks__/**
plugins:
  - serverless-offline
  - serverless-plugin-split-stacks
custom:
  splitStacks:
    perFunction: false
    perType: true
  shouldWarmUp:
    dev: false
    production: true
functions:
  login:
    handler: index.login
    environment:
      LAMBDA_FUNCTION: person-login
    description: Person Login function
    events:
      - schedule:
          rate: cron(0/5 5-23 * * ? *)
          enabled: ${self:custom.shouldWarmUp.${env:NODE_ENV}, self.custom.dev}
      - http:
          path: /login
          method: post
          cors: true
```

The thing is: I manually changed the CORS configuration in the API Gateway console (`Access-Control-Allow-Origin*` from `'*'` to `'http://<mydomain.com>'`); then, when deploying the service via `serverless` (with the `serverless.yml` above), nothing changes. I tried deploying the whole service and one function individually.

Is the file above setting the cors correctly?
