### ISSUE TITLE
Hanging on sls deploy, with no output

### ISSUE THREAD

**Issue by El-Fitz** [serverless/serverless#3882]
# This is a (Bug Report / Feature Proposal)

## Description

* What went wrong?
I referenced custom variables in a file two folders higher in the folder hierarchy, and used them to set a variable in serverless.yml. When doing sls deploy, nothing happens, it just 'hangs', with no output, and I have to kill it. Like an infinite loop or recursion.

* What did you expect should have happened?
To set the variables properly and deploy ? ^^

* What was the config you used?
?

* What stacktrace or error message from your provider did you see?
None

It's kinda funny ^^"

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: macOS 10.13 beta(17A291j)
* ***Stack Trace***: None
* ***Provider Error messages***: None

Faulty lines in serverless.yml (makes sls deploy hang indefinitely):

```
custom:
  private: ${file(../../slsconf/private.yml)}
  sns: ${file(../../slsconf/sns.yml)}
```

Replacing them with the following works just fine
```
custom:
  private: ${file(../../slsconf/private.yml)}
  sns:
    topicNames:
    sources:
      source:
        action: sources_source_action_${self:provider.stage}
  arns:
    sources:
      source:
        action: arn:aws:sns:${self:provider.region}:${self:custom.private.IDs.aws}:${self:custom.sns.topicNames.sources.source.action}
```

Content of private.yml
```
APIKeys:
  baseSync: anApiKey
IDs:
  aws: myAwsId
misc:
  baseUserAgent: anUser/Agent
  baseTestClientDeviceUUID: anUUID
```

Content of sns.yml
```
topicNames:
  sources:
    source:
      action: sources_source_action_${self:provider.stage}

arns:
  sources:
    source:
      action: arn:aws:sns:${self:provider.region}:${self:custom.private.IDs.aws}:${self:custom.sns.topicNames.sources.source.action}
```
