### ISSUE TITLE
How to create KMS key using serverless 

### ISSUE THREAD

**Issue by arunsubbanna** [serverless/serverless#3892]
Can someone tell me how to create a KMS key using serverless yml and refer the same for an API or a lambda function ?
Thanks!

**Comment by pmuens** [comment]
Hey @arunsubbanna thanks for the question. 👍 

You could provide the [corresponding CloudFormation resources]( http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html) with the help of the [resources section](https://serverless.com/framework/docs/providers/aws/guide/resources/).

After that you could use the `awsKmsKeyArn` config parameter with the help of the [Serverless Variable system](https://serverless.com/framework/docs/providers/aws/guide/variables/) to generate the arn on the fly according to your CloudFormation resources.

Smth. like this (untested):

```yml
service:
  awsKmsKeyArn: arn:aws:kms:${opt:region}:XXXXXX:key/some-hash

functions:
  myFunc:
    handler: handler.handler

resources:
  Resources:
    MyKmsKey:
      Type: AWS::KMS::Key
      Properties: 
        Description: Some description
        ...
```

You might also want to ask this question in [our forums](http://forum.serverless.com) since that's the best place for such use-case questions.
