### ISSUE TITLE
Configure API gateway “Gateway Responses” from serverless

### ISSUE THREAD

**Issue by manV** [serverless/serverless#3896]
# This is a Question/Feature Proposal

## Description

* I am not sure if this is possible with serverless, but I couldn't find anything in the docs. When using Cognito authorises with serverless, when identity token becomes invalid, the response from the api gateway is 401(unauthorised), but there is no way to set cors headers on that response. While using AWS Console this can be done via "Gateway Responses" (see image below) tab. ![console way to do it](http://i.imgur.com/gy5gvcm.png)

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: ubuntu 16.04

**Comment by asierba** [comment]
We are having the same issue at the moment. We are trying to setup cors headers for 401s and can't find a way to setup this through serverless.

**Comment by frangeris** [comment]
Same here... related [How configure “Gateway Responses”, inside API gateway from serverless](http://forum.serverless.com/t/how-configure-gateway-responses-inside-api-gateway-from-serverless/2201/2)

**Comment by asierba** [comment]
I've looking to this a bit further and talking to aws support. 
So far at the moment there is no way to create _Gateway Responses_ through cloudformation. Probably because the feature is quite new. Hopefully this will change soon.
The only way to create _Gateway Responses_ in and automated way is using the api for apigateway: http://docs.aws.amazon.com/apigateway/api-reference/link-relation/gatewayresponse-put/

**Comment by pmuens** [comment]
> I've looking to this a bit further and talking to aws support.
So far at the moment there is no way to create Gateway Responses through cloudformation. Probably because the feature is quite new. Hopefully this will change soon.
The only way to create Gateway Responses in and automated way is using the api for apigateway: http://docs.aws.amazon.com/apigateway/api-reference/link-relation/gatewayresponse-put/

Thanks for following up with AWS and thanks for sharing that info @asierba 👍

Hopefully AWS will add support for this on CloudFormation soon (we'll keep an eye on the upcoming announcements 👀).

**Comment by manV** [comment]
Thanks @pmuens @asierba, let's hope Cloudformation support for Gateway Responses lends soon.

**Comment by rsshilli** [comment]
For other folks reading this, the good news is that the values stay when serverless updates your stack.  So it's only the first install that you have to configure this stuff manually, then it sticks around.

**Comment by manV** [comment]
I can see the support for Gateway Responses added to CloudFormation on August 18. Please see the Release history [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).

**Comment by nedvisol** [comment]
In case anyone needs it, this is how I added it to my serverless.yml

```
resources:
  Resources:
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId: 
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
```

**Comment by jch254** [comment]
@nedvisol you are champion!

**Comment by pmuens** [comment]
Good stuff! Thanks for sharing @nedvisol 👍

Would be nice if we could add this to the Framework core! Anyone here who wants to take a first stab at it?

**Comment by stenio123** [comment]
Just to expand on @nedvisol 's response, the "GatewayResponse' is just a name to be used in this file, can be anything and must be unique if defining multiple error codes. And for 4XX:
```
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
```

**Comment by sime** [comment]
I'm trying to use this for the first time and I get following CloudFormation validation error.

`The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ApiGatewayRestApi] in the Resources block of the template`

**Comment by sime** [comment]
Ignore me, had a test project with no HTTP events.

**Comment by jonatassaraiva** [comment]
Just to expand on @nedvisol 's response:
```
resources:
  Resources:
    GatewayResponseInvalidApiKey:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        RestApiId: 
          Ref: 'ApiGatewayRestApi'
        ResponseType: INVALID_API_KEY
        ResponseTemplates:
          application/json: "{\"error\":{\"code\":\"custom-403-invalid-api-key\",\"message\":$context.error.messageString},\"requestId\":\"$context.requestId\"}"
    GatewayResponseResourceNotFound:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        RestApiId: 
          Ref: 'ApiGatewayRestApi'
        ResponseType: RESOURCE_NOT_FOUND
        ResponseTemplates:
          application/json: "{\"error\":{\"code\":\"custom-404-resource-not-found\",\"message\":$context.error.messageString},\"requestId\":\"$context.requestId\"}"
```

More: https://gist.github.com/jonatassaraiva/4c33dd8225605c02318cd71a55b2335d

**Comment by leonardreidy** [comment]
@jonatassaraiva , thanks for the gist. This helped me to relieve an awful lot of headaches. But I have a question if you have a moment. I need to map the output from a lambda function to the headers and output model of arbitrary integration responses. I can't do it via the console, because this is disabled for lambda-proxy integration. Do you know if I can configure a Lambda Error Regex from serverless? Sorry if this isn't the right place to raise this question. If it isn't I'll naturally remove the comment!

**Comment by fubar** [comment]
This should absolutely be added to the CORS section in the docs (https://serverless.com/framework/docs/providers/aws/events/apigateway/#enabling-cors). Enabling CORS only adds CORS headers to 200 responses, but that is just half of the way there. The application I'm working on parses 401 responses to determine if an access token is expired, and it was not able to read the 401 payload until I added the configs as per @stenio123 - thanks for that btw, very helpful!

**Comment by mmairs9** [comment]
How would one be able to read the 401 error in the client if Cors request origin is dynamic and unable to be wildcarded because you are sending credentials?

**Comment by rsshilli** [comment]
@mmairs9 You're confused.  The CORS request origin can be wildcarded.  Also, credentials should not be your path and definitely not in your request origin.  

Take a look at @stenio123 's comment from Oct 3, 2017.  Specifically this line:
```
             gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
```

That's where you put your origin.  According to the [W3 spec](https://www.w3.org/TR/cors/#access-control-allow-origin-response-header), you can just put the first part of your URL in place of the star.  So if you wanted to accept requests from https://my.website.com/* you'd make it:
```
             gatewayresponse.header.Access-Control-Allow-Origin: "'https://my.website.com'"
```
And it will accept requests from any URL that starts with `https://my.website.com` (ex. `https://my.website.com/some.path/likeThis?would=work&just=fine`)

**Comment by chrisoverzero** [comment]
@rsshilli I'm afraid it's you who is confused.

If "Access-Control-Allow-Credentials" is passed, "Access-Control-Allow-Origin" [is not allowed to be wildcarded][].

[is not allowed to be wildcarded]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#Directives

**Comment by rsshilli** [comment]
Ah!  Fair enough.  I'm sorry.  You have to know the domain of the of your front end host.  It can't be "*".  

But you can still read 401 errors even though you have configured to send credentials.   Setting the origin to `https://my.website.com` is the same as setting it as `https://my.website.com/*`.  The wildcard at the end is inferred.

**Comment by dattatrayhkulkarni** [comment]
> In case anyone needs it, this is how I added it to my serverless.yml
> 
> ```
> resources:
>   Resources:
>     GatewayResponse:
>       Type: 'AWS::ApiGateway::GatewayResponse'
>       Properties:
>         ResponseParameters:
>           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
>           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
>         ResponseType: EXPIRED_TOKEN
>         RestApiId: 
>           Ref: 'ApiGatewayRestApi'
>         StatusCode: '401'
> ```
I added this to my serverless.yml file, but still not getting the CORS header in the response.
Do I need to remove the stack ( sls remove) and redploy? ( serverless deploy)
Or Do I need to give reference of this GatewayResponse anywhere else also?

**Comment by chrisoverzero** [comment]
@dattatrayhkulkarni The snippet you've quoted will only add CORS response headers to failed authentication responses. Is that where you're trying to see CORS response headers? (If not, read on.)

For CORS response headers in response to preflight requests, look up the `cors` property on a Serverless `http` event. For CORS response headers for requests that make it into the handler, those have to be supplied by the handler. They can’t be added by Serverless on the way out.

**Comment by dattatrayhkulkarni** [comment]
> @dattatrayhkulkarni The snippet you've quoted will only add CORS response headers to expired token authentication responses. Is that where you're trying to see CORS response headers? (If not, next paragraph.) Maybe switch the response type to `UNAUTHORIZED` or `DEFAULT_4XX`. I don’t remember what circumstances cause API Gateway to emit an `EXPIRED_TOKEN` gateway response. I believe it's not possible from a Lambda Authorizer, for example.
> 
> For CORS response headers in response to preflight requests, look up the `cors` property on a Serverless `http` event. For CORS response headers for requests that make it into the handler, those have to be supplied by the handler. They can’t be added by Serverless on the way out.

Thanks, this worked.

**Comment by jlcastrillon91** [comment]
> In case anyone needs it, this is how I added it to my serverless.yml
> 
> ```
> resources:
>   Resources:
>     GatewayResponse:
>       Type: 'AWS::ApiGateway::GatewayResponse'
>       Properties:
>         ResponseParameters:
>           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
>           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
>         ResponseType: EXPIRED_TOKEN
>         RestApiId: 
>           Ref: 'ApiGatewayRestApi'
>         StatusCode: '401'
> ```

I have tried this solution, it triggers the custom gateway response fine but after some re-deployments it stops working. Has anyone else gone through this issue?

**Comment by victorblevi** [comment]
@jlcastrillon91 The same is happening to me.

**Comment by rsshilli** [comment]
The only way we've gotten this to work repeatedly is to put the Gateway responses in a separate CloudFormation file, and then to deploy:
* Delete the Gateway Responses CloudFormation stack
* Run serverless
* Add the Gateway response CF stack back again

This is repeatable and after about a year it's pretty flawless.

**Comment by mkyung** [comment]
> How would one be able to read the 401 error in the client if Cors request origin is dynamic and unable to be wildcarded because you are sending credentials?

Anyone has solution for this ... after almost two years?

**Comment by famartinez80** [comment]
Same issue but I need to modify the response when x-api-key is invalid or missing, I always got  "message": "Forbidden" any knows how to fix this, also locally in offline mode.

**Comment by medikoo** [comment]
If I understand correctly, this issue is about ensuring CORS headers for some 4xx responses.

Currently CORS headers are ensured only for `200` response here: https://github.com/serverless/serverless/blob/fd83d8d66567898b1d9367665d45230087579f82/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js#L103-L121

If this configuration can be extended to support other codes, we're definitely open to host such improvement.

We can introduce `functions[].events[].http.cors.statusCodes` option, through which we may configure what other status codes should be accompanied with CORS headers.

What do you think?

**Comment by chachan** [comment]
an example for shared API Gateways:
```
resources:
  Resources:
    4XXGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: a1b2c3d4e5
```
