### ISSUE TITLE
AWS profile setting not honored

### ISSUE THREAD

**Issue by esalter** [serverless/serverless#3899]
I apologize if this is known.  I searched for "profile" and some issues did come up that seemed similar but nothing specifically talking about the "profile" setting in serverless.yml.  I saw at least one comment suggesting to use the default profile instead in an attempt to resolve an issue, so I do think that there is a bug around this feature somehow.

# This is a Bug Report

## Description

For bug reports:
* What went wrong? 
"serverless deploy" attempted to use default AWS credentials, but the "profile" setting in serverless.yml specified a different profile that should have been used.  
WORKAROUND: setting the AWS_PROFILE=cdp environment variable does work as expected. 
* What did you expect should have happened?
serverless should use the profile specified in serverless.yml
* What was the config you used?

serverless.yml:
````
service: myservice

provider:
  name: aws
  runtime: nodejs6.10
  stage: esalter
  region: us-east-1
  profile: cdp
  cfLogs: true
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DeleteNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
      Resource: "*"

package:
  include:
    - .env
    - src/common
    - node_modules/aws-sdk
    - node_modules/babel-polyfill
    - node_modules/biguint-format
    - node_modules/bluebird
    - node_modules/bunyan
    - node_modules/dateformat
    - node_modules/dotenv
    - node_modules/hashtablejs
    - node_modules/jasmine-co
    - node_modules/request
    - node_modules/request-promise
    - node_modules/soap-as-promised
    - node_modules/xml2js
    - node_modules/xmlbuilder
  exclude:
    - .babelrc
    - .gitignore
    - .synk
    - .travis.yml
    - deploy.sh
    - package.json
    - README.md
    - test

functions:
  SessionInit:
    handler: lib/sessionInit/index.handler
    memorySize: 128
    timeout: 30
    events:
      - sns: SomeAction-${self:provider.stage}
      - sns: SomeOtherAction-${self:provider.stage}
````
* What stacktrace or error message from your provider did you see?
The stack failed to create due to a permissions error.  I have a default profile, but do not have access to create certain features in the default profile that serverless wants to create with that profile.  So the error is "expected" but only because serverless used the wrong profile.  

Similar or dependent issues:
I'm not sure if this is related or not:
- https://github.com/serverless/serverless/issues/3833

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: osx sierra
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

**Comment by esalter** [comment]
I'm terribly sorry - this was a misconfiguration on my side.

**Comment by pmuens** [comment]
> I'm terribly sorry - this was a misconfiguration on my side.

No worries! Glad to hear that you were able to resolve it!

**Comment by RafLeszczynski** [comment]
@esalter what kind of misconfiguration are you talking about? I have a similar issue with a hallo world serverless sample project. All `serverless` cli commands are using my default AWS profile.

serverless.yml
```yml
service: hello-world-serverless
provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless-admin
functions:
  hello:
    handler: handler.hello
```

~/.aws/credentials
```
[default]
aws_access_key_id = xxxxxxxxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[serverless-admin]
aws_access_key_id =xxxxxxxxxxxxxxxxxxxxxxxxxxxx
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 ```
