### ISSUE TITLE
Allow the use of fixed default values in ${...} variable definitions

### ISSUE THREAD

**Issue by arabold** [serverless/serverless#3900]
# This is a Feature Proposal

## Description

**Expected behavior:** `${opt:myopt, "bar"}` and/or `${opt:myopt, bar}` should print the value of the `myopt` command line option if set or the string "bar" otherwise.

Right now this isn't possible AFAIK. Instead you have to work around by defining an intermediate variable like this:
```yaml
custom:
  bar_string: bar
  myopt: ${opt:myopt, $self:custom.bar_string}
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.16
