### ISSUE TITLE
Support setting API Gateway domain name

### ISSUE THREAD

**Issue by hassankhan** [serverless/serverless#3906]
# This is a Feature Proposal

## Description

AWS have [just added support](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html) for defining custom domains via CloudFormation. It would be brilliant if we could define one for the API Gateway resource that Serverless deploys.

```yaml
provider:
  aws:
    apiGateway:
      customDomain: <custom domain>
      certificateArn: <arn of cert from ACM> 
```

**Comment by rdehnhardt** [comment]
I make this post, but I don't receive any answers yet 

https://forum.serverless.com/t/how-can-i-get-api-gateway/2206

**Comment by hassankhan** [comment]
I believe your issue is unrelated @rdehnhardt, I've commented in the forum with more details.

**Comment by pmuens** [comment]
Hey @hassankhan thanks for opening! 👍 

Really like this feature! Not sure about the config just yet.

We have `provider. apiKeys` and `provider.usagePlans`. What about adding a `provider.domainName` property to keep it consistent to the way AWS names their resources (since we follow a similar pattern)..

Something like this:

```yml
provider:
  domainName:
    customDomain: <custom domain>
    certificateArn: <arn of cert from ACM> 
```

Later on we could move this to an API Gateway related umbrella config. Something like:

```yml
provider:
  apiGateway:
    apiKeys:
      - myFirstKey
      - ${opt:stage}-myFirstKey
      - ${env:MY_API_KEY} # you can hide it in a serverless variable
    usagePlan: # Optional usage plan configuration
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
    domainName:
      customDomain: <custom domain>
      certificateArn: <arn of cert from ACM> 
```
