### ISSUE TITLE
Serverless package does not include all modules when a package.json file is provided

### ISSUE THREAD

**Issue by xmissio** [serverless/serverless#3915]
# This is a (Bug Report)
## Description
When deploying multiple versions of a service or just versions of the function within the service, but sometimes some modules are not included in the package in presence of a package.json file

* What went wrong?
When using ``sls deploy`` or ``sls deploy -f functionName`` or ``sls package`` the ``service.zip`` doest not include all my node_modules, when I checked the package I figured out that some modules were missing 
My tree:
```
lamba
  dir
  dir
  index.js
  package.json
  serverless.yml
  node_modules
```

My package.json file was something like this:
```
{
  "name": "lambda",
  "version": "1.0.0",
  "description": "lambda",
  "main": "index.js",
  "dependencies": {
    "handlebars": "^4.0.10",
    "html-pdf": "^2.1.0",
    "mathfinjs": "^1.0.2",
    "moment": "^2.18.1",
    "numeral": "^2.0.6",
    "path": "^0.12.7",
    "pdfkit": "^0.8.3",
    "pg": "^6.4.0",
    "request-promise": "^4.2.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "RAZ",
  "license": "ISC"
}
```
* What did you expect should have happened?

That every time that I deploy a service/function the package be the same but ``request-promise`` and ``pg`` were missing

* What was the config you used?
```
service: service

frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  versionFunctions: false

functions:
  function:
    handler: index.handler
    description: description
    memorySize: 1024
    timeout: 30
    role: arn-role
    tags:
      Department: IT
      Name: name
      Team: team
      TeamMember: TeamMember
    environment:
      var: value
      var: value
      var: value
      var: value
      var: value
    
```
* What stacktrace or error message from your provider did you see?
```
{
  "errorMessage": "Cannot find module 'request-promise'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/index.js:14:23)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}
```
```
Unable to import module 'index': Error
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/index.js:14:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Similar or dependent issues:

## Additional Data
Even using ``include: file`` was useless

**The solution for me was to rename/remove package.json file**

* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: macOS Sierra 10.12.5
