### ISSUE TITLE
Reverse version sorting for "sls deploy list functions"

### ISSUE THREAD

**Issue by 5290charlie** [serverless/serverless#3917]
# This is a Bug Report

## Description
Checking function versions using command: `sls deploy list functions`

Sorting of latest function versions seems backwards. I would expect to see the highest version numbers as the "last 5", but always showing "1-4 & $LATEST"

For bug reports:
* What went wrong?
  * Order of "last 5 function versions" seems to be in the wrong order
  * All functions show: `4, 3, 2, 1, $LATEST` (most have published versions beyond 4)
* What did you expect should have happened?
  * Expected to see version numbers in reverse sorted order
  * Example: `9, 10, 11, 12, $LATEST`
* What was the config you used?
  * Using basic config for Route53 domain management via Lambda:
```yaml
service: domain-manager

frameworkVersion: "<=1.17.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "route53:*"
      Resource: "*"

functions:
  list-zones:
    handler: zones.list
  get-zone:
    handler: zones.get
  create-zone:
    handler: zones.create
  delete-zone:
    handler: zones.delete

  list-records:
    handler: records.list
  create-record:
    handler: records.upsert
  update-record:
    handler: records.upsert
  delete-record:
    handler: records.delete
```
* What stacktrace or error message from your provider did you see?
  * No actual errors, just seems the sorting is backwards

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* none (that I could find)

## Additional Data

* ***Serverless Framework Version you're using***: `1.17.0`
* ***Operating System***: `Linux Mint 18.1 Serena`
* ***Stack Trace***: `N/A`
* ***Provider Error messages***: `N/A`
