### ISSUE TITLE
Specify AWS profile instead of credentials

### ISSUE THREAD

**Issue by katspaugh** [serverless/serverless#392]
In JAWS – in `admin.env` – you just said which AWS profile to use – and it was very convnient.
In Serverless `admin.env` needs to contain AWS credentials. 😔

With Serverless I have to do this on CircleCI:

```
deployment:
  dev:
    branch: master
    commands:
      - cat ~/.aws/credentials | grep aws_access_key_id | sed 's/aws_access_key_id = /SERVERLESS_ADMIN_AWS_ACCESS_KEY_ID=/g' > admin.env
      - cat ~/.aws/credentials | grep aws_secret_access_key | sed 's/aws_secret_access_key = /SERVERLESS_ADMIN_AWS_SECRET_ACCESS_KEY=/g' >> admin.env
      - serverless resources deploy
```
