### ISSUE TITLE
node_modules is ignored in package > exclude statement in serverless.yml

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#3938]
# This is a (Bug Report)

## Description
For bug reports:
* What went wrong?
It didn't exclude from a deployment package if you describe `node_modules` in `package > exclude` statement in serverless.yml. Is this a bug or by design?

**Step to reproduce**
1. Describe `node_modules` in `package > exclude` statement in serverless.yml
```yaml
package:
  exclude:
    - node_modules/**
```
2. Run `sls package`

* What did you expect should have happened?

I expected the package was created with excluding `node_modules`. However the package has included  `node_modules`. 

If you specify a directory name other than `node_modules`, it is excluded correctly.

* What was the config you used?
Here is my serverless.yml

```yml
service: sls-test-2

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - package-lock.json
    - node_modules/**
    - test/**

functions:
  hello:
    handler: handler.hello
```
* What stacktrace or error message from your provider did you see?
nothing

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: macOS Sierra 10.12.5
* ***Stack Trace***: nothing
* ***Provider Error messages***: nothing
