### ISSUE TITLE
Separate Event for Alexa Smart Home Skill Trigger

### ISSUE THREAD

**Issue by Nedervino** [serverless/serverless#3955]
# This is a Feature Proposal

## Description
AWS offers a separate trigger called 'Alexa Smart Home' for their Smart Home skills, besides the regular 'Alexa Skills Kit' trigger. As these both work in different ways, Serverless's current 'alexaSkill' event does not work for Smart Home skills. Adding a separate event type for this trigger allows the Serverless framework to work for Smart Home skills, which it currently doesn't.

Similar or dependent issues:
* #1409 

## Additional Data
Serverless Framework Version: latest

**Comment by horike37** [comment]
@Nedervino 
Good idea. it would be greate if `Alexa Smart Home` will be added as new event source.
so, it would be something like this:
```yaml
functions:
  index:
    handler: handler.hello
    events:
      - alexaSmartHome
```

Then, here is the developer guid for this.
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference

**Comment by pmuens** [comment]
Thanks for opening @Nedervino 👍 

That's a good idea! I like @horike37 proposal to add a `-alexaSmartHome` event source.

Is there anything additional we could configure or is it similar to an `alexaSkill` where most of the configuration is done in the AWS console?

**Comment by horike37** [comment]
As far as I see the AWS console, it would require `applicationId` and `enable flag`
<img width="1246" alt="aws-console" src="https://user-images.githubusercontent.com/1301012/28416354-9cfbbce8-6d8e-11e7-9bc7-9dc08c1e4d52.png">

so, it would be something like this:
```yaml
functions:
  index:
    handler: handler.hello
    events:
      - alexaSmartHome
          appId: xxxxx
          enabled: true or false
```
And here is short version
```yaml
functions:
  index:
    handler: handler.hello
    events:
      - alexaSmartHome: <appId>
```

**Comment by pmuens** [comment]
Thanks for the porposal @horike37 👍 

That looks good! I like it! 👍 💯

Now we just need to take a look into the CloudFormation template / what we could configure via CloudFormation.

**Comment by horike37** [comment]
I just registerd amazon developer console and took a look into this for a little.
Seems like that need to give only the following function policy. maybe it would use `AWS::Lambda::Permission` to give the policy in CloudFormation template

```yaml
{
    "Version": "2012-10-17",
    "Id": "default",
    "Statement": [
        {
            "Sid": "lc-7185b299-1e7f-499b-8b26-a7020343775b",
            "Effect": "Allow",
            "Principal": {
                "Service": "alexa-connectedhome.amazon.com"
            },
            "Action": "lambda:InvokeFunction",
            "Resource": "arn:aws:lambda:us-east-1:<aws account ID>:function:alexa",
            "Condition": {
                "StringEquals": {
                    "lambda:EventSourceToken": "amzn1.ask.skill.xxxxx-xxx-xxx-xx-xx"
                }
            }
        }
    ]
}
```
