### ISSUE TITLE
Lambda not created when only function is triggered by existing s3 bucket

### ISSUE THREAD

**Issue by Slymodi** [serverless/serverless#3968]
# This is a (Bug Report)

## Description
I have a serverless project that has one function that is activated on create from an s3 bucket that is created by another serverless project and the lambda is not created but a cloudformation stack is

## Additional Data

```yml
service: vision

provider:
  name: aws
  runtime: java8
  memorySize: 512
  stage: dev
  region: us-east-1
  custom:
    stage: ${opt:stage, self:provider.stage}

package:
  artifact: target/vision-0.1.jar

function:
  handler:
    name: handler
    handler: com.handler.handler
    events:
        - s3:
            bucket: previously-created-bucket
            event: s3:ObjectCreated:*
```
