### ISSUE TITLE
very high memory usage for single function deployment

### ISSUE THREAD

**Issue by Rukenshia** [serverless/serverless#3981]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? I'm deploying a single AWS lambda function (`sls deploy function -f mylambda`) and see very high memory on a AWS t2.micro instance (>900MB RAM from the node process)
* What did you expect should have happened? there should be a way to lower the memory consumption.
* What was the config you used? one lambda function with a http event, ZIP file with ~10MB in size.
* What stacktrace or error message from your provider did you see? none

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 0.18.0, node 8.2.1
* ***Operating System***: Amazon Linux
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @Rukenshia thanks for opening 👍

Could you please provide more information about your service? (e.g. the `serverless.yml` file and the artifact you tried to upload).

Do you see this frequently or are those outliers?

**Comment by Rukenshia** [comment]
@pmuens The behavior is consistent, I can't provide you with the exact ZIP I'm uploading because it's work stuff, but it's a Node.js lambda built with typescript with various node_modules that makes the zip ~10MB in size. Here's parts of the serverless.yml file:

```
plugins:
  - serverless-api-stage 
service: my-service
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 8
  stage: ${opt:stage}
  apiKeys:
    - ${self:provider.stage}-privateKey
  region: some-region
  domainName: mydomain
  deploymentBucket: mybucket
  versionFunctions: true
package:
  individually: true

custom:
  config: ${file(../serverless/${self:provider.stage}/lambda-definition.json)}

my-lambda:
    handler: ${self:custom.config.my-lambda.handler}
    description: some description
    package:
      artifact: ${self:custom.config.my-lambda.artifact}
    environment:
      SOME_ENV: Fn::ImportValue ...
    events:
      - http:
          method: POST
          path: /do-something
          private: true
    runtime: ${self:custom.config.my-lambda.environment.runtime}
    memorySize: ${self:custom.config.my-lambda.environment.memory}
    timeout: ${self:custom.config.my-lambda.environment.timeout}
    role: ${self:custom.config.my-lambda.iam-role}
```

the artifact gets downloaded earlier and is defined in the lambda-definition file. We have a CloudFormation stack that's referenced in the environment variables. I'm sorry I can't really provide much more information, if you need more information feel free to ask however.
