### ISSUE TITLE
DX: Make it easier to use API gateway base URL in environment variables

### ISSUE THREAD

**Issue by DavidWells** [serverless/serverless#3986]
This post http://www.goingserverless.com/blog/api-gateway-url outlines how to grab the base API gateway url from cloud-formation. 

This is a pretty common url case and prevents folks from having to hardcode strings

It works but is god awful to write. No human should ever ever ever ever ever ever have to write:

 ```
{ "Fn::Join" : ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}" ] ]  }
```

Here is a working serverless.yml example:

```yml
service: the-service

custom:
  stage: "${opt:stage, self:provider.stage}"
  region: "${opt:region, self:provider.region}"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    IT_WORKS: { "Fn::Join" : ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:custom.region}.amazonaws.com/${self:custom.stage}" ] ]  }

functions:
  myFunc:
    handler: handler.test
    events:
      - http:
          path: whatever
          method: post
          cors: true
```

```js
// hander.js
module.exports.test = (event, context, callback) => {
  console.log('API URL IT_WORKS', process.env.IT_WORKS)
  // now I can call other urls of service without hardcoding stuff
}
```

Suggestion: Make a shorthand variable to reference this instead of the verbose cloudformation.

Something like: `${apiGatewayUrl}` (or something)

Let's make it easy to write and read! =)

**Comment by mim-Armand** [comment]
AN old topic but thought I'd share this and bump it so we close it if it's not needed anymore,
I use this and it works fine:
```yml
baseUrl: ${cf:my-api-name-${self:provider.stage}.ServiceEndpoint}
```

**Comment by msheakoski** [comment]
@mim-Armand This only works if you have an existing stack. If you are deploying a new stack, you will get an error that the stack does not exist.

**Comment by mim-Armand** [comment]
@msheakoski the solution I mentioned is for a Micro-service architecture ( multiple SLS projects all orchestrated through a parent project ), otherwise, that's obvious that you can't reference the stack that you are deploying in itself, for that you can use Cloud Formation outputs instead :+1:

**Comment by msheakoski** [comment]
@mim-Armand Interesting. I'm only 1 week into serverless so still learning. I will definitely look into more of a micro-service architecture setup. I found a lot of helpful information so far on architecture and best practices at https://serverless-stack.com.

In case anyone is trying to get a URL to another function, here is what I ended up doing:
```yaml
custom:
  # stage and region not required to be here

provider:
  name: aws
  runtime: nodejs10.x
  # stage and region not required to be here either

functions:
  apples:
    handler: handler.apples
    events:
      - http: {method: get, path: apples}
    environment:
      BANANAS_URL:
        Fn::Join: ["", [
          "https://", !Ref ApiGatewayRestApi, ".execute-api.", !Ref AWS::Region, ".amazonaws.com",
          "/${self:provider.stage}/${self:functions.bananas.events.0.http.path}"
        ]]
  bananas:
    handler: handler.bananas
    events:
      - http: {method: get, path: bananas}
```
It differs from previous solutions in that it doesn't require putting anything in `custom` and it reads the region from CloudFormation instead of directly from the yaml file.

Another way to accomplish it is with [YAML anchors](https://confluence.atlassian.com/bitbucket/yaml-anchors-960154027.html). Keep in mind that the function with the anchor must appear before the other function that is referencing it:
```yaml
functions:
  bananas:
    handler: handler.bananas
    events:
      - http: {method: get, path: &bananas_path bananas}
  apples:
    handler: handler.apples
    events:
      - http: {method: get, path: apples}
    environment:
      BANANAS_URL:
        Fn::Join: ["", [
          "https://", !Ref ApiGatewayRestApi, ".execute-api.", !Ref AWS::Region, ".amazonaws.com",
          "/${self:provider.stage}/", *bananas_path
        ]]
```
