### ISSUE TITLE
Allow to set NotificationARNs parameter for AWS provider

### ISSUE THREAD

**Issue by rmax** [serverless/serverless#3998]
# This is a Feature Proposal

## Description

Cloudformation provides a [NotificationARNs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-notificationarns) property to be able to send Cloudformation events to one or more SNS topics.

This is useful for custom integrations, i.e.: a Slack bot that listens to the SNS topic and send the events to a Slack channel.

The initial idea is to add a new provider parameter ``notificationArns``, for example:

```
provider:
  name: aws
  runtime: python3.6
  notificationArns:
    - 'arn:aws:sns:us-west-2:1234567890:deploy-events'

```
