### ISSUE TITLE
Cognito User Pool event creates redundant permission resources

### ISSUE THREAD

**Issue by jmalins** [serverless/serverless#4000]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Registering the same function for multiple Cognito User Pool events on the same pool creates redundant Lambda permissions. 

We are using a single Lambda to log User Pool events for compliance purposes. This involves connecting the same Lambda to multiple triggers. It works, but the CFN template contains multiple permissions granting `cognito-idp` invoke rights. Not harmful, but should probably be cleaned up.

* What did you expect should have happened?

Serverless should create only one permission resource for each function, regardless of how many triggers on the pool it is connected to.

Additionally, it would be great if the `cognitoUserPool` event supported an array for `trigger`. This would perhaps be a more straightforward fix than de-duping the function names.

* What was the config you used?
```
  trigger:
    description: Trigger to log UserPool events and enforce account disable
    handler: src/index.handleUserPoolEvent
    events:
      - cognitoUserPool:
          pool: Application
          trigger: PreSignUp
      - cognitoUserPool:
          pool: Application
          trigger: PreAuthentication
      - cognitoUserPool:
          pool: Application
          trigger: PostAuthentication
```
* What stacktrace or error message from your provider did you see? 
N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0
* ***Operating System***: MacOS X 10.12.5
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
