### ISSUE TITLE
Not working override AWS::Logs::LogGroup retention time sample code

### ISSUE THREAD

**Issue by tuxinaut** [serverless/serverless#4002]
# This is a Bug Report

## Description

I used the **example** code ([docu](https://serverless.com/framework/docs/providers/aws/guide/resources/#override-aws-cloudformation-resource)) for overriding ```AWS::Logs::LogGroup``` retention time. I only adjusted the name because of the name of my function.

* What went wrong?

The deployment has been successful but the retention time wasn't changed.

* What did you expect should have happened?

That the ```AWS::Logs::LogGroup``` retention time for the function would have been adjusted to the defined value.

* What was the config you used?

\-

* What stacktrace or error message from your provider did you see?

\- 

* Solution

**Function name**: my-function
**normalizedFunctionName**: MyDashfunction

After using ```MyDashfunction``` (instead of ```MyDashFunction```) as **normalizedFunctionName** which is not compliance with the documentation, retention time has been adjusted correctly.

## Additional Data

* ***Serverless Framework Version you're using***: 1.18.0
* ***Operating System***: Ubuntu 14.04
* ***Stack Trace***: -
* ***Provider Error messages***: -

**Comment by boazdejong** [comment]
The example does not specify the resource type.

Specifying your resource like this might solve your issue:
```yaml
resources:
  Resources:
    WriteDashPostLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
```

**Comment by thundron** [comment]
Hello there,

I'm having problems with this too, I specified the resource group as this

```yml
resources:
  Resources:
    RouteDashGetLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "30"
```

but it doesn't change anything. I already tried removing/re-deploying, manually changing the log retention and deploying again, nothing seems to work.
