### ISSUE TITLE
Serverless Run: Add provider config parameter to function level

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#4014]
The Serverless `run` plugin should implement a functionality which makes it possible to define multiple providers per service. Additionally it should implement a feature to read a `provider` configuration on a function level (to determine for which provider the function is written for).

This is necessary so that one service (one `serverless.yml` file) can host multiple functions with different `providers`.

---

**Note:** The implementation should be done in the `run` plugin and should **NOT** be introduced in the core since it's for demo purposes only and might be refactored / re-architected later on.

---

Here's an example how this could look like:

```yml
service:
  name: my-service

# new `providers` attribute
providers:
  - aws:
      runtime: nodejs6.10
  - google:
      runtime: nodejs

functions:
  helloWorldAws:
    handler: aws/index.helloWorld
    # new `provider` attribute
    provider: aws
  helloWorldGoogle:
    handler: google/index.helloWorld
    # new `provider` attribute
    provider: google
```

This data can be used to generate the `functionConfig` data when deploying each function to the Emulator.

/cc @eahefnawy @brianneisler

**Comment by brianneisler** [comment]
If we plan to reference providers by name then it might make more sense to make the providers property a map rather than an array.

```yaml
providers:
  aws:
    runtime: nodejs6.10
  google:
    runtime: nodejs
```

**Comment by brianneisler** [comment]
Hmm, we also might need to indicate a type in that situation to allow for more than one of the same type of provider.

```yaml
providers:
  some-key:
    type: aws 
    runtime: nodejs6.10
  some-other-key:
    type: aws 
    runtime: nodejs
```
