### ISSUE TITLE
Can not use custom artifact zip in v1.18

### ISSUE THREAD

**Issue by sethkor** [serverless/serverless#4015]
This is a Bug Report 

Can not use custom artifacts in v1.18

When upgrading to v1.18 of the serverless framework, the artifact tag in the serveless.yml file is ignored.  Instead it searches for an artifact named with the service: tag in the yaml file.

For me I had this tag under:

```yml
functions:
   MyFunction:
   package:
      artifact: ./lambda.zip
```

Reverting back to serverless 1.16 and also testing with 1.17 i can see the behaviour I expect with my custom zip specified by the artifact tag being used for deployment.

I’m using nodejs 6.10 on AWS lambda.
