### ISSUE TITLE
Support StackSet?

### ISSUE THREAD

**Issue by bdruth** [serverless/serverless#4018]
Feature request - Amazon announced cross-account and cross-region CF provisioning with StackSet: https://aws.amazon.com/about-aws/whats-new/2017/07/aws-cloudformation-supports-multiple-account-and-region-provisioning-with-stackset/ -- not sure about cross-account, but cross-region would actually be useful for us. We're currently deployed in multiple regions (manually) for failover purposes (in case we hit another S3 outage 😉), but doing that automatically would mean less manual processes to make sure things stay in sync.

**Comment by horike37** [comment]
Great idea! Adding the feature to the Framework would make it easy to do multi-region strategy.
this would be something like this
```yaml
provider:
  name: aws
  awsMultiRegion:
    - us-east-1
    - ap-northeast-1
```
