### ISSUE TITLE
Cognito Trigger Configuration and Fn::GetAtt - Circular Dependency Issue

### ISSUE THREAD

**Issue by pgali** [serverless/serverless#4039]
# This is a (Bug Report / Feature Proposal)

## Description
Currently using SLS 1.19, trying to get CognitoPool event configured, but Cloud Formation throws errors when Fn::GetAtt is called as part of the environment variable setup. Its complaining about circular dependency.

When I comment out the environment variable definition, serverless deploys without any issue.

If there are any other ways I can export the ARN as export variable, please advice. Other lambda's need the pool id.

For bug reports:
* What went wrong?
Fn::GetAtt throws circular dependency error.

I need the ARN name to be passed to other lambda functions.
* What did you expect should have happened?
* What was the config you used?
```
service: users

provider:
  name: aws
  runtime: java8
  memorySize: 512
  stage: dev
  region: us-east-1

  custom:
    stage: ${opt:stage, self:provider.stage}

  environment:
    AWS_STAGE: ${self:provider.custom.stage}-
    DYNAMODB_TABLE: ${self:provider.environment.AWS_STAGE}${self:service}
    USER_POOL:
       'Fn::GetAtt': [ CognitoUserPoolMyUserPool, Arn ]
   
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"
    - Effect: "Allow"
      Action:
        - "cognito-idp:*"
      Resource: "arn:aws:cognito-idp:${self:provider.region}:*:userpool/*"
    - Effect: 'Allow'
      Action:
              - "ses:SendEmail"
      Resource: "*"
    - Effect: 'Allow'
      Action:
              - "s3:*"
      Resource: "*"

package:
  artifact: target/users-0.1.jar


functions:
    postconfirmation:
      name: ${self:provider.custom.stage}-postconfirmation
      handler: com.XXX.users.handlers.PostConfirmationHandler
      events:
        - cognitoUserPool:
           pool: MyUserPool
           trigger: PostConfirmation


resources:
  Resources:
    CognitoUserPoolMyUserPool:
        Type: AWS::Cognito::UserPool
        Properties:
          AdminCreateUserConfig:
            AllowAdminCreateUserOnly: true
          UserPoolName: ${self:provider.custom.stage}-mypool
          Schema:
            - AttributeDataType: String
              Mutable: true
              Name: role
```
* What stacktrace or error message from your provider did you see?
```
 Error --------------------------------------------------

  The CloudFormation template is invalid: Circular dependency between resources: [PostconfirmationLambdaFunction, PostconfirmationLambdaVersiony9d6So9mzrgPdQT1h0S2XJakfA3oQ2csfG0hikKoQ, CognitoUserPoolMyUserPool, PostconfirmationLambdaPermissionCognitoUserPoolMyUserPoolTriggerSourcePostConfirmation]

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: The CloudFormation template is invalid: Circular dependency between resources: [PostconfirmationLambdaFunction, PostconfirmationLambdaVersiony9d6So9mzrgPdQT1h0S2XJakfA3oQ2csfG0hikKoQ, CognitoUserPoolMyUserPool, PostconfirmationLambdaPermissionCognitoUserPoolMyUserPoolTriggerSourcePostConfirmation]
    at provider.request.catch (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:25:13)
From previous event:
    at AwsDeploy.validateTemplate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:12)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:117:39)
From previous event:
    at Object.aws:deploy:deploy:validateTemplate [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:113:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:248:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:255:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.2.1
     Serverless Version:     1.19.0
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by RafalWilinski** [comment]
Thanks for reporting issue @pgali. 

I've managed to reproduce it using provided config and by debugging CloudFormation file it seems that Cognito pool `DependsOn` Lambda function because of `PostConfirmation` hook, and Lambda depends on ENV variable from pool. 

Right now, I don't have any idea how to fix that issue, however, I think it's quite easy to mitigate it. Your event from pool should include `poolId` attribute. Thanks to that, you can easily build ARN on your own. It should look something like this:

`serverless.yml`
```
environment:
  REGION: ${self:region}
  ACCOUNT_ID:
    - Ref: AWS::AccountId
```

`com.XXX.users.handlers.PostConfirmationHandler.java`
```java
String arn = String.format("arn:aws:cognito-idp:%s:%s:userpool/%s", env.get("REGION"), env.get("ACCOUNT_ID"), event.identityPoolId);
```

Hope that helps.

**Comment by pgali** [comment]
Thank you very much for looking into this issue @RafalWilinski 

Unfortunately, the environment variable was not for this trigger handler lambda function. It is for another lambda function.
I have another handler that receives a user request for creating an user in our platform and I turn around and use AdminCreateUser call provided by Lambda. Hence the reason to expose the ARN via Environment Variable.

Any thoughts on how I can mitigate it?

```    postuser:
      name: ${self:provider.custom.stage}-postuser
      handler: com.XXX.users.handlers.PostUsersHandler
      events:
        - http:
            path: organizations/{organization_id}/users
            method: post
            cors: true

PostUsersHandler:
private static final String COGNITO_POOL_ID = Environment.getUserPoolID();

inside the handler method:
AdminCreateUserRequest cognitoRequest = new AdminCreateUserRequest()
                            .withUserPoolId(COGNITO_POOL_ID)
                            .withUsername(email)
                            .withUserAttributes(
                                    new AttributeType()
                                            .withName("email")
                                            .withValue(email)
                             ....



public class Environment {
    public static final String getAWSEnvironment() {
        return System.getenv("AWS_STAGE");
    }

    public static final String getUserPoolID() {
        String userPoolProperty = System.getenv("USER_POOL");
        return userPoolProperty.substring(userPoolProperty.indexOf("/") +1, userPoolProperty.length());
    }```

Thank you so much again for helping me with this issue.

Also, if you have some pointers on how you debug CF file that would be great, I have been wanting to dig deeper into CF, but SLS has been sparing me the trouble :) except when I hit the limits

**Comment by RafalWilinski** [comment]
If it's for another function, you can set environment variables explicitly just for this one function, not on service level and see whether that helps. I think this might eliminate circular dependency issue.

```
functions:
  PostUsersHandler:
    name: ${self:provider.custom.stage}-postuser
    handler: com.XXX.users.handlers.PostUsersHandler
    environment:
      USER_POOL: 'Fn::GetAtt': [ CognitoUserPoolMyUserPool, Arn ]
```
