### ISSUE TITLE
Adding Kinesis stream as a event trigger for lambda function not working

### ISSUE THREAD

**Issue by runtimeZero** [serverless/serverless#4052]
I am trying to add a kinesis stream as the event course:

here is the snippet from serverless.yml

    functions:
      Foo:
        handler: handler.foo
        events:
          - stream:
            arn: arn:aws:kinesis:us-east-1:783995676505:stream/search-helper
            batchSize: 100
            startingPosition: LATEST
            enabled: false

(note: the kinesis stream already exist in the system)

The deployment via "serverless deploy" is successful HOWEVER the trigger does not get added to the function configuration.

I checked the yml file using a yml validatior and there are no errors. This looks straightforward enough and i have played around for hours. Either this is a bug or I am not doing something right here ?

**Comment by horike37** [comment]
Thank you for opening @runtimeZero :blush:
 
Seems that the indent under `- stream` go wrong. It would be needed more spaces.
Could you fix the serverless.yml syntax as follw and try again.

```yaml
functions:
  Foo:
    handler: handler.foo
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:783995676505:stream/search-helper
          batchSize: 100
          startingPosition: LATEST
          enabled: false
```
