### ISSUE TITLE
Reference SSM Parameters as Variables

### ISSUE THREAD

**Issue by lorengordon** [serverless/serverless#4053]
# This is a Feature Proposal

## Description

I was thinking it would be great to have the ability to reference SSM parameters as serverless variables. The syntax would probably look something like this:

```
service: new-service
provider: aws
functions:
  hello:
      name: ${ssm:param-name}
      handler: handler.hello
```

I looked at the current code, and I think the implementation would be pretty similar to the s3 variable reference. I'd be happy to test a patch and submit a pull request if there is interest. The feature should include a couple things:

- [x] Ability to reference both regular and [path-based](http://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-working.html#sysman-paramstore-su-organize) SSM parameters.
- [x] Ability to specify `WithDecryption`. Not sure quite yet where this would go. Any ideas for this one? Maybe a new provider option?

**Comment by horike37** [comment]
@lorengordon 
Good idea, but imo I think it is better that the feature would be provided as an external plugin. because the feature is essential for all framework users. I don't know that you can add a custom reference parameters from an external plugin though

What do you think?

**Comment by lorengordon** [comment]
@horike37 I'm pretty indifferent to the actual implementation. If an external plugin works, I'll pursue that. I would simply observe that the s3 lookup capability exists in the core framework, so there is at least some precedent for including this type of feature here. However, I admit to being rather surprised that no other issue existed for this already, particularly considering that this type of total environment/deployment customization is pretty central to the promise of the SSM parameter store. Perhaps, being new to serverless, I am just missing the common design pattern that others are utilizing?

To take full advantage of the proposed capability, I would envision something like this being more typical than my prior, simplistic example:

```
service: new-service
provider: aws
functions:
  hello:
      name: ${ssm:/serverless/${self:service.name}/${self:provider.stage}/param-name}
      handler: handler.hello
```

I have used the plugin, `serverless-pseudo-parameters`, which mostly appears to work through a modified variable reference syntax (`#{foo}`). If that works for them, it could certainly work here also. But it seems like a shame not to promote something so powerful and simple in the core feature set.

How are you managing your per-service, per-stage, etc, variables now?

**Comment by lorengordon** [comment]
I created https://github.com/serverless/serverless/issues/4062 to demonstrate working code and further the discussion.

**Comment by pmuens** [comment]
> I created #4062 to demonstrate working code and further the discussion.

Nice! Thank you very much for your work on this @lorengordon 👍 

I agree with @horike37 (thanks for jumping in 👍), that this might only affect a few Framework users and could be encapsulated in an external plugin. However we should maybe wait for other feedback here.

Thanks again @lorengordon for getting this started and showing a potential implementation via #4062 for this! 💯

**Comment by lorengordon** [comment]
@pmuens I've actually never developed a javascript app or plugin (mostly do python). Got any pointers, or a good template? And how might I go about hooking into serverless's variable evaluation via a plugin?

**Comment by horike37** [comment]
@lorengordon 
What about using `custom` section in serverless.yml?
I alway write up the following setting to separate some parameters in the deferent stages.

In this case, the memory size will be applied corresponding to the stage you specified
 
```yaml
service: awesome-service

custom:
  stage:  ${opt:stage, self:provider.stage}
  memorySize:
    development: 128   #  128M stage[development]
    production: 512    #  512M stage[production]
    default: 128       # fallback to default if you specify others

provider:
  stage: development
  memorySize: ${self:custom.memorySize.${self:custom.stage}, self:custom.memorySize.default}

```

My personal best solution for total environment/deployment customization is to combine `variables` feature with `custom` section.

**Comment by pmuens** [comment]
> @pmuens I've actually never developed a javascript app or plugin (mostly do python). Got any pointers, or a good template? And how might I go about hooking into serverless's variable evaluation via a plugin?

Good start for someone who just started with JavaScript development! 💪

🤔 AFAIK this is currently not possible since the variables are populated before the plugins are executed (see [here](https://github.com/serverless/serverless/blob/49354484f1a4db6d50be7bbbcaa0fc6734697619/lib/Serverless.js#L86-L100)).

I think @horike37 approach is a good starting point.

**Comment by lorengordon** [comment]
@horike37 I'd rather not store all my values directly in the serverless template. I'd like my templates to be fairly generic, so I'm free to host them publicly. Environment and cli variables work for me personally, but are not great for teams. Or rather, the values _still_ need be stored somewhere the team can reference them. Which could be a file read into a custom variable, sure, but then I need to store those files somewhere.

The SSM parameter store really is built for this, so to me it seems like a no-brainer.

I do understand the hesitancy, as the serverless variable system does not (yet?) have externally-accessible hooks, and not everyone uses AWS, and this is definitely an AWS-centric feature. (Though I could easily see many external key-value stores being valuable for variable lookups. A common template pattern might one day become: `${${self:custom.store}:param-name}`, to support the user's choice of key-value stores.)

@pmuens, if it's not possible to hook into the variable system, then I don't really see any way to do this as a plugin, other than to define a _new_ variable regex pattern, and interpolate the references _after_ serverless populates its variables (what `serverless-pseudo-parameters` appears to do).

One problem with that approach becomes deconflicting the multiple variable regex patterns. I.e. what if I want to use a hypothetical `serverless-ssm-parameters` plugin and the `serverless-pseudo-parameters` plugin? We need to account for the default regex used across all such plugins, and provide overrides. Seems like the implementation gets significantly more complex.

Another problem (or unfortunate side effect), if this were implemented as a plugin, would be the inability to utilize variable overrides and nesting.

**Comment by horike37** [comment]
@lorengordon 
What about describing Systems Manager Resources into `resources` section in serverless.yml?
As far as I read the AWS doc, CloudFormation has supported `Systems Manager`, so you can use `resources` section.

It would be something like this:
``` yml
functions:
  hello:
    name: ${self:resources.Resources.ssm...}
    handler: handler.hello

resources:
  Resources:
    ssm:
      AWS::SSM::Parameter
      Properties:
       .....
```

Although, I don't know about Systems Manager very much since I have never used that.

**Comment by lorengordon** [comment]
@horike37 I believe that would be _creating_ the SSM parameters via the serverless template. I'd then need to specify the values in the template as well (or otherwise use serverless variables to set them). Chicken/egg. I'd like to manage the values outside of serverless (or perhaps just using a different, separate, more private template), using SSM as the permanent parameter store for our serverless apps.

**Comment by lorengordon** [comment]
@pmuens I'm not sure I'm following the proposal... Are you talking about how to implement a hook into Variables.js by extending the variable reference syntax types somehow to templates? And which we then somehow hook a call to a user-defined handler into `getValueFromSource()`?

Something like this:

```
provider:
  name: aws
  runtime: nodejs6.10
  variableSyntaxExtension:
    ssmRefSyntax: "/^ssm:([a-zA-Z0-9_.-/]+)[~]?(true|false)?/"
```

Where maybe the key `ssmRefSyntax` is actually a reference to a handler?
