### ISSUE TITLE
Documentation error triggering request/response warning 

### ISSUE THREAD

**Issue by tcchau** [serverless/serverless#4070]
# This is a Bug Report

## Description

I followed the documentation for AWS Events, [lambda-proxy configuration] to configure a path parameter for my endpoint (https://serverless.com/framework/docs/providers/aws/events/apigateway#request-parameters), including a request configuration block. This triggered the warning, ` Warning! You're using the LAMBDA-PROXY in combination with request / response configuration in your function "<function_name>". Serverless will remove this configuration automatically before deployment.`

Removing the request configuration block, but retaining the path parameter, e.g. `{id}` in the path descriptor made the warning go away, and the API endpoint still works.

I think a documentation update is all that's necessary. I'm new to the serverless framework though, so I thought I would post this bug report before updating the documentation and issuing a PR.

Similar or dependent issues:
N/A

## Additional Data
N/A

**Comment by horike37** [comment]
Thank you for reporting @tcchau !
Cloud you show us serverless.yml when including the request configuration block?
We'd like to check the detail.

**Comment by tcchau** [comment]
Of course! Let me know if I've missed something and that's the reason the warning is being triggered:

```
service: gameBackend

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements: # permissions for all of your functions can be set here
      - Effect: Allow
        Action: # Gives permission to DynamoDB tables in a specific region
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:us-west-2:*:*"
functions:
  storeGameState:
    handler: storeGameState.handler
    events:
      - http:
          path: users/{id}/game-state
          method: put
          authorizer: auth
          cors: true
          request:
            parameters:
              paths:
                id: false
  retrieveGameState:
    handler: retrieveGameState.handler
    events:
      - http:
          path: users/{id}/game-state
          method: get
          authorizer: auth
          cors: true
  auth:
    handler: authorize.handler
package:
  exclude:
    - .git/*
    - npm-debug*
```

The warning is triggered for `storeGameState`, but not for `retrieveGameState`
