### ISSUE TITLE
Outputs Example on Documentation is Incorrect

### ISSUE THREAD

**Issue by ProbablePrime** [serverless/serverless#4079]
# This is a Bug Report

## Description

In the documentation on the [page with an example serverless.yml file](serverless.com/framework/docs/providers/aws/guide/serverless.yml) the format for the example output is incorrect.

It reads:
```
  Outputs:
    UsersTableArn:
      Description: The ARN for the User's Table
      Value:
        "Fn::GetAtt": [ usersTable, Arn ]
      Export: ${self:service}:${opt:stage}:UsersTableArn
```

But based on the documentation for cloudformation outputs this should be:
```
  Outputs:
    UsersTableArn:
      Description: The ARN for the User's Table
      Value:
        "Fn::GetAtt": [ usersTable, Arn ]
      Export: 
        Name: ${self:service}:${opt:stage}:UsersTableArn
```
Using this as an example will lead to:
`The CloudFormation template is invalid: Template format error: Output UsersTableArn is malformed. The Export field of every Outputs member must be a Map.`

Similar or dependent issues:
* https://github.com/serverless/site/issues/120
