### ISSUE TITLE
Lambda onError can't use CloudFormation "Ref", requires ARN string

### ISSUE THREAD

**Issue by shentonfreude** [serverless/serverless#4094]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?

I created an SNS topic 'resource' and tried to reference it in the Lambda function's 'onError' 

```
resources:
  Resources:
    DeadLetterQueue:
      Type: AWS::SNS::Topic
      Properties:
        Subscription:
          - Endpoint: chris+dlqtest@example.com
            Protocol: email

functions:
  DlqTest:
    handler: dlqtest.handler
    onError: 
       Ref: DeadLetterQueue  # doesn't work: "onError config must be provided as a string"
    events:
      - s3:
          bucket: cshenton-dlqtest
          event: s3:ObjectCreated:*
```

It complained:

```
onError config must be provided as a string
```

* What did you expect should have happened?

Framework should accept the CloudFormation reference just like it does for other references to the newly-created resource. E.g., I have in the same serverless.yml this ref that works fine:

```
provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sns:Publish"
      Resource: 
        Ref: DeadLetterQueue
```

* What was the config you used?

The entirely of my serverless.yml is above, but not ordered as in that file. Is this the "config" you mean?

* What stacktrace or error message from your provider did you see?
```
onError config must be provided as a string
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* Code that looks for 'string' only: https://github.com/serverless/serverless/pull/3609/files
* DLQ plugin that might be helpful: http://forum.serverless.com/t/published-a-lambda-dead-letter-queue-plugin/1200?source_topic_id=2476

## Additional Data

* ***Serverless Framework Version you're using***: 1.19.0 (also seen with 1.18.0)
* ***Operating System***: Mac OSX 10.11.6 El Capitan
* ***Stack Trace***: 
```

  Stack Trace --------------------------------------------
 
ServerlessError: onError config must be provided as a string
    at AwsCompileFunctions.compileFunction (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:181:15)
    at serverless.service.getAllFunctions.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:325:39)
    at Array.forEach (native)
    at AwsCompileFunctions.compileFunctions (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:325:8)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:236:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:255:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.7.4
     Serverless Version:     1.19.0
 ```

* ***Provider Error messages***:

```
chris@Haruspex:ocreva$ sls package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  onError config must be provided as a string
 ```
