### ISSUE TITLE
Request: CLI command for printing computed variables

### ISSUE THREAD

**Issue by marshall007** [serverless/serverless#4125]
# Feature Proposal

## Description

I may have missed something, but I haven't found a way to debug the result of various templated variables in `serverless.yml`. It would be nice if there were a CLI command that simply read through all the configuration, computes all templated values, and dumps the resulting YAML and/or JSON.

This would help debug complex variable configurations.

For example, given the following `serverless.yml` template:

```yaml
service: my-service

custom: ${file(config.yml):${opt:stage, self:provider.stage}}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: ${self:custom.aws_profile}
  timeout: 15
  environment:
    S3_BUCKET: ${self:custom.s3_bucket}
  apiKeys:
    - "${self:custom.api_key}"

# ...
```

I would want to see the this kind of output:

```yaml
opt: ...
env: ...
cf: ...
self:
  service: "my-service"
  custom:
    s3_bucket: "my-s3-bucket"
    api_key: "TEST_API_KEY"
    aws_profile: "test"
  provider:
    # ...
    environment:
      S3_BUCKET: "my-s3-bucket"
    apiKeys:
      - "TEST_API_KEY"
```
