### ISSUE TITLE
Multiple functions use same package artifact

### ISSUE THREAD

**Issue by liamawhite** [serverless/serverless#4128]
# Bug Report

## Description

* When deploying multiple functions in a single service the code it uploads in Lambda is the same for both functions. Seems to switch between which code it chooses at random.

* Expected each different handler.zip to be uploaded to the relevent functions.

```
service: Fixtures
package:
  individually: true

functions:
  retrieve-soccer-leagues:
    handler: handler.Handle
    name: RetrieveSoccerLeagues
    package:
      artifact: soccer-leagues/handler.zip
  notify-slack:
    handler: handler.Handle
    name: NotifySlack
    package:
      artifact: notify-slack/handler.zip
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.20.2
* ***Operating System***: OSX 10.12.6
* ***Stack Trace***:
* ***Provider Error messages***:
