### ISSUE TITLE
Rate Exceeded Error when deploying Helloworld Lambda using Serverless

### ISSUE THREAD

**Issue by adsil2** [serverless/serverless#4136]
# This is a Bug Report

## Description

I have a simple Serverless application (see attachment)  --hello world example. 

When I try to deploy this lambda using serverless : serverless deploy -v I get the following:

```
  Serverless Error ---------------------------------------
 
  ServerlessError: Rate exceeded
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.10.0
     Serverless Version:     1.18.0
```

However, if I update serverless.yml with region as us-east-1 it works fine.

(see attachment for reproduction)

For bug reports:
* What went wrong? Rate Exceeded Error
* What did you expect should have happened? Lambda should have deployed 
* What was the config you used?
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

```yml
# The `service` block is the name of the service
service: serverless-hello-world

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
```

* What stacktrace or error message from your provider did you see?
  ServerlessError: Rate exceeded

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Need to deploy lambda in us-west-2 since that contains all our subnets and security groups.

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
OSX 
* ***Stack Trace***:
* ***Provider Error messages***:
