### ISSUE TITLE
(AWS) Tagging works with new lambda functions, not existing.

### ISSUE THREAD

**Issue by terrybonds** [serverless/serverless#4138]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?  

Tagging for lambda functions appears to work at point of function creation only, it isn't possible to apply tags to existing functions.

* What did you expect should have happened?

Adding `tags` to the serverless.yaml file should apply tags to a lambda function; whether it's new or existing i.e. for when a tag (e.g. team email) needs updating.

* What was the config you used?

```
functions:
  cloudhealth_cmdb_etl:
    handler: lambdas/cloudhealth_cmdb_etl.lambda_handler
    description: ETL job to blah blah *snip*
    tags:
      systemCode: cloudhealth-cmdb-etl
      environment: p
      teamDL: ***oops.... snip***
    timeout: 300
    events:
      - schedule: cron(0 22 * * ? *)
```

* What stacktrace or error message from your provider did you see?  

No error occurs during the stack update, it appears all okay from the cloudformation events.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* n/a

## Additional Data

* ***Serverless Framework Version you're using***: v1.17.0
* ***Operating System***: darwin ~ our serverless deployments are made via GoCD (version 17.7.0) - link: https://www.gocd.org/
* ***Node Version***: 8.1.4
* ***Stack Trace***: No errors occur that I can see
* ***Provider Error messages***: No errors occur that I can see
