### ISSUE TITLE
Overwriting options with default values does not work

### ISSUE THREAD

**Issue by awildturtok** [serverless/serverless#4149]
# This is a Bug Report

## Description

When deploying to AWS with Serverless, instead of overwriting a value if it does not exist, the whole string is used.

```
service: ${opt:id}
provider:
  name: aws
  runtime: nodejs6.10

functions:
  execute:
    name: ${self:service}
    handler: handlers/handler
    environment:
      CONFIGS: ${file(${opt:actions, ''})} 
      ENTRY_POINT: ${opt:entry_point, ''}
```

* Invoking `sls deploy --id do` deploys a lambda with env:  `CONFIGS=${file(${opt:actions, ''})}` and `ENTRY_POINT=${opt:entry_point, ''}`, when they should be empty.

* Invoking `sls deploy --id do --actions 'scratch' --entry_point 'comb' ` deploys a lambda with env:  `CONFIGS=${file(${opt:actions, ''})}` and `ENTRY_POINT=${opt:entry_point, ''}`, when they should contain the contents of scratch, and `ENTRY_POINT=comb`.

## Additional Data

* ***Serverless Framework Version you're using***:  1.20.2
* ***Operating System***: Windows
