### ISSUE TITLE
Bitbucket Pipeline

### ISSUE THREAD

**Issue by dscis** [serverless/serverless#4165]
Hello,

I am trying to setup a pipeline on a serverless framework bitbucket repository. Everything works until the service is getting packaged. Any advice is appreciated.

```
Serverless: Bundling with Webpack...
Time: 1544ms
               Asset       Size  Chunks             Chunk Names
     /src/handler.js    33.6 kB       0  [emitted]  main
src/keys/private.key    1.67 kB          [emitted]  
 src/keys/public.pem  425 bytes          [emitted]  
Serverless: Packing external modules: babel-runtime@^6.23.0, bcryptjs@^2.4.3, jsonwebtoken@^7.4.1, uuid@^3.0.1, keypair@^1.0.1, moment@^2.18.1, bluebird@^3.5.0, mongoose@^4.10.8
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.10.3
     Serverless Version:     1.20.2
```

Thanks,

dscis

**Comment by HyperBrain** [comment]
@dscis Which version of the serverless-webpack plugin do you use (you use it, right)? The plugin should disable any packaging of Serverless, because webpack dictates what has to be packaged and what not.

So it looks like the `Serverless: Excluding development dependencies...` log should not appear. Can you post your function definitions from `serverless.yml` and your webpack.config.js?

**Comment by dscis** [comment]
Serverless.yml
```
functions:

  login:
    handler: src/handler.login
    warmup: true
    events:
      - http:
          path: auth/login
          method: post
          cors: true
          integration: lambda-proxy

  reset:
    handler: src/handler.reset
    events:
      - http:
          path: auth/reset
          method: post
          cors: true
          integration: lambda-proxy

  reset_confirm:
    handler: src/handler.reset_confirm
    events:
      - http:
          path: auth/reset/confirm
          method: post
          cors: true
          integration: lambda-proxy

  update:
    handler: src/handler.update
    events:
      - http:
          path: auth/update
          method: post
          cors: true
          integration: lambda-proxy

  profile:
    handler: src/handler.profile
    warmup: true
    events:
      - http:
          path: auth/profile
          method: get
          cors: true
          integration: lambda-proxy

  verify:
    handler: src/handler.verify
    warmup: true
    events:
      - http:
          path: auth/verify
          method: post
          cors: true
          integration: lambda-proxy

  logout:
    handler: src/handler.logout
    events:
      - http:
          path: auth/logout
          method: post
          cors: true
          integration: lambda-proxy

  log:
    handler: src/handler.log
    warmup: true
    events:
      - http:
          path: auth/log
          method: post
          cors: true
          integration: lambda-proxy
```
```

var glob = require('glob');
var path = require('path');
var nodeExternals = require('webpack-node-externals');
var CopyWebpackPlugin = require('copy-webpack-plugin');

// Required for Create React App Babel transform
process.env.NODE_ENV = 'production';

module.exports = {
  // Use all js files in project root (except
  // the webpack config) as an entry
  entry: __dirname + '/src/handler.js',
  target: 'node',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  // Run babel on all .js files and skip those in node_modules
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['babel'],
      include: __dirname,
      exclude: /node_modules/,
    }]
  },
  plugins: [
    new CopyWebpackPlugin([
        { from: 'src/keys', to: 'src/keys' }
      ])
  ],
  // We are going to create multiple APIs in this guide, and we are 
  // going to create a js file to for each, we need this output block
  output: {
    libraryTarget: 'commonjs',
    path: __dirname + '/.webpack',
    filename: 'src/handler.js'
  },
};


```
