### ISSUE TITLE
S3 event _without_ specifying bucket name?

### ISSUE THREAD

**Issue by lorengordon** [serverless/serverless#4166]
# This is a Bug Report

## Description

I understand that when I specify an S3 event on a function, serverless will actually create that bucket so that it can also set the event on the bucket.

However, it seems that serverless uses the value of the `bucket` property in two ways: 1) as the name of the resource in the template, and 2) as the BucketName in the template (which is not a required property). The second usage is the problem. This seems remarkably fragile, since S3 bucket names must be globally unique. The odds of picking an existing name are quite high.

I don't care about the bucket name; this is not a pet. The auto-generated name would be perfectly acceptable. But if I remove the bucket name, then serverless complains about it being a required property. How can I create an S3 event for a function, _without_ having the BucketName field populated in the resulting template?

### What went wrong?

If you attempt to deploy the below config, you'll get the error: `Missing "bucket" property for s3 event in function hello. The correct syntax is: s3: bucketName OR an object with "bucket" property. Please check the docs for more info.`

```
service: hello

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          event: s3:ObjectCreated:Put
```

And if you attempt to deploy this config, you'll get the error: `An error occurred while provisioning your stack: S3BucketHello - hello already exists.`

```
service: hello

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: hello
          event: s3:ObjectCreated:Put

```

### What did you expect should have happened?

The `bucket` property should not be required. If absent, it should create the bucket with an auto-generated name.

### What was the config you used?

See above. 

### What stacktrace or error message from your provider did you see?

Depending on the setup, either:

`Missing "bucket" property for s3 event in function hello. The correct syntax is: s3: bucketName OR an object with "bucket" property. Please check the docs for more info.`

-OR-

`An error occurred while provisioning your stack: S3BucketHello - hello already exists.`

## Additional Data

* ***Serverless Framework Version you're using***:  1.20.2
* ***Operating System***: Windows 10
