### ISSUE TITLE
BatchSize property ignored from YML file

### ISSUE THREAD

**Issue by aterreno** [serverless/serverless#4176]
# This is a (Bug Report / Feature Proposal)

## Description

It seems like the batchSize config property in the yml gets always ignored, specifying a serverless.yml file like this:

```yaml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
    - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
      batchSize: 666
```
Generates a cloudformation template like this: 

```json
    "HelloEventSourceMappingDynamodbFoo": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": "IamRoleLambdaExecution",
      "Properties": {
        "BatchSize": 10,
        "EventSourceArn": "arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000",
        "FunctionName": {
          "Fn::GetAtt": [
            "HelloLambdaFunction",
            "Arn"
          ]
        },
        "StartingPosition": "TRIM_HORIZON",
        "Enabled": "True"
      }
    }
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.19.0
* ***Operating System***: Darwin Kernel Version 16.7.0
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by RafalWilinski** [comment]
Thanks @aterreno for reporting the issue.

`batchSize` property is not specified because you provided a `string` to `event.stream` instead of an `object`. https://github.com/serverless/serverless/blob/aebce86ab20faaf95db32e037990de81f28e8dda/lib/plugins/aws/package/compile/events/stream/index.js#L93

It should rather look something like this:
```yml
events:
  - stream:
      arn: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
      batchSize: 666
```

Generated CFN template:
```json
"HelloEventSourceMappingDynamodbFoo": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": "IamRoleLambdaExecution",
      "Properties": {
        "BatchSize": 666,
        "EventSourceArn": "arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000",
        "FunctionName": {
          "Fn::GetAtt": [
            "HelloLambdaFunction",
            "Arn"
          ]
        },
        "StartingPosition": "TRIM_HORIZON",
        "Enabled": "True"
      }
    }
```

**Comment by aterreno** [comment]
Hey Cheers, I think I've based our yml file from the template generated from sls, which inlines the arn just as I did. 
Same on those linked projects:
https://github.com/pmuens/serverless-kinesis-streams/blob/master/serverless.yml
https://github.com/pmuens/serverless-dynamodb-streams/blob/master/serverless.yml

And I've just tried to re-generate a new serverless project, it does inline the arn. Is just the latest version supporting an object? 

I can try and dig into the template generation code and change the docs. 

```yaml
functions:
  hello:
    handler: handler.hello

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
```

is what is currently generated.
