### ISSUE TITLE
'name.replace is not a function' while serverless deploy

### ISSUE THREAD

**Issue by happyvig** [serverless/serverless#4194]
#This is a (Bug Report)

## Description

When I run `serverless deploy` in a n AWS Lambda project that has python library (Pillow - for image processing) dependencies, I get the following deployment error.

For bug reports:
* What went wrong?
 `serverless deploy` didnt work.
* What did you expect should have happened?
The deployment should have been successful and the lambda function should have worked. 
* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***:  1.21.0
* ***Operating System***: Mac 10.12.6 Sierra
* ***Stack Trace***:

```
> serverless deploy -v

Serverless: Parsing Python requirements.txt
Serverless: Installing required Python packages for runtime python2.7...
Serverless: Docker Image: lambci/lambda:build-python2.7
Serverless: Linking required Python packages...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Unlinking required Python packages...

  Type Error ---------------------------------------------

    name.replace is not a function

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: name.replace is not a function
    at Object.normalizeNameToAlphaNumericOnly (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
    at Object.normalizeBucketName (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:200:17)
    at Object.getLambdaS3PermissionLogicalId (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:263:8)
    at s3EnabledFunctions.forEach.s3EnabledFunction (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/s3/index.js:189:10)
    at Array.forEach (<anonymous>)
    at AwsCompileS3Events.compileS3Events (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/s3/index.js:167:24)
    at BbPromise.reduce (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/classes/PluginManager.js:242:55)
From previous event:
    at PluginManager.invoke (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/classes/PluginManager.js:242:22)
    at PluginManager.spawn (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/classes/PluginManager.js:254:17)
    at Deploy.BbPromise.bind.then.then (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:101:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:99:10)
    at BbPromise.reduce (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/classes/PluginManager.js:242:55)
From previous event:
    at PluginManager.invoke (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/classes/PluginManager.js:242:22)
    at PluginManager.run (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/classes/PluginManager.js:261:17)
    at variables.populateService.then (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/vkumar/.nvm/versions/node/v8.1.3/lib/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>


  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.3.0
     Serverless Version:     1.21.0
```

* ***Provider Error messages***:  'name.replace is not a function'

**Comment by RafalWilinski** [comment]
Hi @happyvig, thanks for reporting issue.

I've tried to reproduce your bug, however, everything works fine for me, here's log:
```
sls-python ⍉ ➜ ls
handler.py     serverless.yml
sls-python ➜ pip3 freeze > requirements.txt
sls-python ➜ ls
handler.py       requirements.txt serverless.yml
sls-python ➜ cat requirements.txt
appdirs==1.4.0
click==6.7
container-transform==1.1.4
cycler==0.10.0
dask==0.14.1
decorator==4.0.11
Jinja2==2.9.6
MarkupSafe==1.0
matplotlib==2.0.0
networkx==1.11
numpy==1.12.0
olefile==0.44
packaging==16.8
Pillow==4.0.0
protobuf==3.2.0
pyparsing==2.1.10
python-dateutil==2.6.0
pytz==2016.10
PyYAML==3.12
scikit-image==0.12.3
scipy==0.19.0
six==1.10.0
tensorflow==1.0.0
toolz==0.8.2
sls-python ➜ serverless deploy -v
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - aws-python3-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - aws-python3-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (768 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - aws-python3-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - HelloLogGroup
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - HelloLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersiongaJxZWX4j8TswgQhsiPmbHTsLi1QKJHzka5p8EdM0
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloLambdaVersiongaJxZWX4j8TswgQhsiPmbHTsLi1QKJHzka5p8EdM0
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - HelloLambdaVersiongaJxZWX4j8TswgQhsiPmbHTsLi1QKJHzka5p8EdM0
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - aws-python3-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - aws-python3-dev
Serverless: Stack update finished...
Service Information
service: aws-python3
stage: dev
region: us-east-1
stack: aws-python3-dev
api keys:
  None
endpoints:
  None
functions:
  hello: aws-python3-dev-hello

Stack Outputs
HelloLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:085108115628:function:aws-python3-dev-hello:1
ServerlessDeploymentBucketName: aws-python3-dev-serverlessdeploymentbucket-vqh8sbuyvdxv

Serverless: Publish service to Serverless Platform...
Service successfully published! Your service details are available at:
https://platform.serverless.com/services/RafalWilinski/aws-python3
```

Could you please post your `serverless.yml` as well as your `requirements.txt`? Thanks.

**Comment by mchristopher** [comment]
I'm running into this same issue.

```yaml
service: importer
frameworkVersion: "=1.19.0"

plugins:
  - serverless-plugin-scripts
  - serverless-python-requirements

custom:
  stage: dev
  pythonRequirements:
    dockerizePip: true
  scripts:
    hooks:
      'before:package:cleanup': rm -fr __pycache__
      'before:package:createDeploymentArtifacts': rm -fr .requirements/pandas/tests && rm -fr .requirements/psycopg2/tests && find . -name '*.pyc' -type f -delete
      'before:deploy:function:packageFunction': rm -fr .requirements/pandas/tests && rm -fr .requirements/psycopg2/tests && find . -name '*.pyc' -type f -delete

provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.stage}
  region: us-east-1

  memorySize: 128
  timeout: 300

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: ServerlessDeploymentBucket
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: ServerlessDeploymentBucket
            - "/*"

  package:
    exclude:
      - .git/**
      - node_modules/**
      - __pycache__/**

functions:
  data_importer:
    handler: handler.import_data
    events:
      - s3:
          bucket:
            Ref: ServerlessDeploymentBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: firehose/

resources:
  Resources:
    scraperStream:
      Type: AWS::Kinesis::Stream
      Properties:
        ShardCount: 6
        RetentionPeriodHours: 24
    scraperFirehoseDeliveryRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: ''
              Effect: Allow
              Principal:
                Service: firehose.amazonaws.com
              Action: 'sts:AssumeRole'
              Condition:
                StringEquals:
                  "sts:ExternalId":
                    "Ref": AWS::AccountId
    scraperFirehoseDeliveryPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: firehose_delivery_policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 's3:AbortMultipartUpload'
                - 's3:GetBucketLocation'
                - 's3:GetObject'
                - 's3:ListBucket'
                - 's3:ListBucketMultipartUploads'
                - 's3:PutObject'
              Resource:
                - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: ServerlessDeploymentBucket
                - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: ServerlessDeploymentBucket
                    - "/firehose/*"
        Roles:
          - Ref: scraperDeliveryRole
```

```
# Eggs available on Lambda
boto3==1.4.7 #no-deploy
botocore==1.7.7 #no-deploy
docutils==0.14 #no-deploy
jmespath==0.9.3 #no-deploy
python-dateutil==2.6.1 #no-deploy
s3transfer==0.1.11 #no-deploy
six==1.10.0 #no-deploy

pandas==0.20.3
numpy==1.13.1
beautifulsoup4==4.6.0
requests==2.18.4
decorator==4.1.2
inflection==0.3.1
SQLAlchemy==1.1.14
psycopg2==2.7.3.1
SQLAlchemy-Utils==0.32.16
```

**Comment by RafalWilinski** [comment]
Thanks @mchristopher for such detailed info 🙌 

I'll try to debug it asap.

**Comment by amberlion** [comment]
I had same issue.
I suppose serverless.yml doesn't have support "Ref" in events[].s3.bucket.

```yaml
    events:
      - s3:
          bucket:
            Ref: ServerlessDeploymentBucket // not supported`
```

**Comment by jippity** [comment]
The error for mchristopher is caused by
`stage: ${self:custom.stage}`
It should be 
`stage: ${self:custom:stage}`
(':' instead of '.')

**Comment by inciteAnalytics** [comment]
I have the same issue. I looks like it is because we are trying to make reference to the `ServerlessDeploymentBucket`.

I am trying to set up a Lambda event triggered by s3 whenever there is a deploy from serverless. I need to create RDS tables via Lambda whenever a user deploys a new instance.

**Comment by ryanwitt** [comment]
Likely duplicate of https://github.com/serverless/serverless/issues/3034

**Comment by risabhkumar-cc** [comment]
Any updates on this?

**Comment by yasirunilan** [comment]
I also ran into the same issue. any update on this?
![screenshot from 2018-06-03 16-00-47](https://user-images.githubusercontent.com/9814784/40885616-5b1a5f42-6747-11e8-9073-94a20349bd22.png)

**Comment by Eldavid** [comment]
Same issue here. Are there a working solution?

**Comment by risabhkumar-cc** [comment]
@Eldavid instead of referencing your bucket using `Ref: s3-bucket-reference`, 
you may use `Ref: "arn:aws:s3:::s3-bucket-name"` until this is resolved.

**Comment by mkondel** [comment]
@risabhkumar-cc how would you write that as part of the trigger event? Here is what I thought should work:
```javascript
functions:
  thumb:
    handler: thumb/thumb.handler
    events:
      - s3:
          bucket: 
            Ref: S3BucketImages
resources:
  Resources:
    S3BucketImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}

// ERROR: name.replace is not a function
```

And here is how I tried to change it, and now get a different error:
```javascript
functions:
  thumb:
    handler: thumb/thumb.handler
    events:
      - s3:
          bucket: arn:aws:s3:::${env:BUCKET_NAME}
resources:
  Resources:
    S3BucketImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}

/* ERROR: An error occurred: S3BucketArnawss3THEACTUALBUCKETNAME - Bad Request 
(Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 
421E7BE173C303C4; S3 Extended Request ID: 
KxwHQS17ddd3YlnR02NfX2UkEX3RY4DB4olVHYW4kZy/dX2H4tifcgpibEi6BwjVOguK0PP9OBk=).*/
```
I noticed that serverless may be adding 'S3Bucket' in front of whatever ARN it gets from events.s3.bucket. In my case, if ```{$env:BUCKET_NAME}=THEACTUALBUCKETNAME```, then the error would have ```S3BucketArnawss3THEACTUALBUCKETNAME```.

So since my serverless ref is called S3BucketImages, I then tried with ```bucket: Images```. This is a new third error now:
```bash
An error occurred: S3BucketImages - Unable to validate the following destination configurations 
(Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 
479BA4207D9F4C65; S3 Extended Request ID: 
NX59h1JoXsjE05GeD9DA6gOKtJI7cPk0FK6Em3Jdwj1AoDcGWsAuVCsHaXkx0Oh7bHxTWYghpTE=).```

**Comment by mkondel** [comment]
[This link explains the serverless naming convention that makes it possible to reference your s3 events.](https://serverless.com/framework/docs/providers/aws/events/s3#custom-bucket-configuration)
I was close with my bucket name and event naming, but did not have the required permissions. There are 3 components to this magic:
- ID of the function: 'thumb'
- ID of the bucket: 'S3BucketImages'
- FunctionName in the permissions: 'ThumbLambdaFunction'

Here is a working version of my yaml file:
```yaml
functions:
  thumb:
    handler: thumb/thumb.handler
    events:
      - s3: images
resources:
  Resources:
    S3BucketImages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
    ResizeLambdaPermissionPhotosS3:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - ThumbLambdaFunction
            - Arn
        Principal: "s3.amazonaws.com"
        Action: "lambda:InvokeFunction"
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: "arn:aws:s3:::${env:BUCKET_NAME}"
```

It works, my function gets triggered when a file gets uploaded to my custom s3 bucket. Everything was created by the serverless deploy command. Strangely there are 2 triggers on my lambda now, the bottom one is to my bucket, but the top one is to someone who has the s3 bucket named 'images'.
![image](https://user-images.githubusercontent.com/3288757/42736969-a88c8e1a-883c-11e8-8d73-bb46f769913a.png)

**Comment by lemmingworks** [comment]
I've found that using a value stored in a config.yml file to reference the bucket name works well:

*serverless.yml*
```
....
functions:
  doSomethingLambda:
    handler: do-something.handler
    events:
      - s3:
          bucket: ${file(./config.yml):${self:provider.stage}.region}.my-s3-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: location/in/bucket/
            - suffix: .csv

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./config.yml):${self:provider.stage}.region}.my-s3-bucket
....
```

*config.yml*
....
```
dev:
  region: eu-west-1
  data-bucket: my-s3-bucket.dev

prod:
  region: eu-west-2
  data-bucket: my-s3-bucket.prod
....
```

**Comment by jmineraud** [comment]
Actually the documentation of serverless provides the answer:
[https://serverless.com/framework/docs/providers/aws/events/s3/#custom-bucket-configuration](https://serverless.com/framework/docs/providers/aws/events/s3/#custom-bucket-configuration)

The naming convention is quite strict, and s3 events actually create the bucket, so in order to configure the bucket appropriately, one need to see the Resource name of the bucket rightfully. I would suggest simple name for the bucket.

For example, if we have a simple `process` function which is trigger by a createObject s3 event for the bucket event reference `test`
```Yaml
functions:
  process:
    handler: process.Handler
    role:
      Fn::GetAtt:
        - processRole
        - Arn
    events:
      - s3:
          bucket: test
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
```

With these resources, you can actually name the bucket properly, have different bucket names for stages, etc...

The key things are:
* S3Bucket{First letter capitalized of the name of bucket in event}
  * the event bucket name must be uncapitalized
* Name your bucket in BucketName with service and stage otherwise deploying multiple stage will trigger an error (S3 bucket already exists with that name)

```Yaml
Resources:
  S3BucketTest:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self.service}-${opt:stage, self:provider.stage}-more-complicated-name-for-test-bucket
      # add additional custom bucket configuration here                                          
  processLambdaPermissionTestS3:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
        "Fn::GetAtt":
          - ProcessLambdaFunction
          - Arn
      Principal: "s3.amazonaws.com"
      Action: "lambda:InvokeFunction"
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn: "arn:aws:s3:::${self.service}-${opt:stage, self:provider.stage}-more-complicated-name-for-test-bucket"

  TestBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketTest
      PolicyDocument:
        Statement:
          -                                                                                      
            Action:
              - "s3:GetObject"
              - "s3:DeleteObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - '/'
                - - Fn::GetAtt:
                    - S3BucketTest
                    - Arn
                  - '*'
            Principal:
              AWS:
                Fn::GetAtt:
                  - processRole
                  - Arn
  processRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
```

**Comment by JonChristensen** [comment]
@jmineraud's example is fantastic and it's what finally got me past this. He shows how to have different names by stage unlike the example in the documentation here: https://serverless.com/framework/docs/providers/aws/events/s3/#custom-bucket-configuration . The only thing that I would add for anything else that finds this is that the name of the lambda permissions for the bucket should be capitalized in the first letter.  So his example "processLambdaPermissionTestS3:" should be "ProcessLambdaPermissionTestS3:".  The only way I was able to figure this out was to reduce my stack down to the bare minimums.  Just one function and one bucket and I noticed that it was creating two versions of the lambda permissions.  One lower case one and an upper case one.  Thank you for this example @jmineraud!

**Comment by pmuens** [comment]
Closing since https://github.com/serverless/serverless/issues/4194#issuecomment-455568672 shows how it can be fixed.

Feel free to continue the discussion.

**Comment by deftomat** [comment]
It is really nice that it works when one keeps the naming convention.

However, what should we do when we already created a bucket with incompatible LogicalID ("Bucket" instead of "S3BucketFoo") and we want to add S3 event handler?

We have a ton of files in bucket already so it is not easy to to change the logical name. 😞

**Comment by JonChristensen** [comment]
@deftomat some people are claiming success for your scenario with a plugin called https://www.npmjs.com/package/serverless-plugin-existing-s3

**Comment by deftomat** [comment]
@JonChristensen Thanks, but this library leads to corrupted deployments as its need to be done in two steps 😞 

Anyway, I solved it by completely ignoring the `serverless` features and instead of using `events.s3` in function definition, we are defining the function ARN in bucket's template:

```
  Bucket: {
    Type: 'AWS::S3::Bucket',
    Properties: {
      BucketName: 'bucket-name',
      NotificationConfiguration: {
        LambdaConfigurations: [
          {
            Event: 's3:ObjectCreated:Put',
            Function: { 'Fn::GetAtt': ['FooLambdaFunction', 'Arn'] }
          }
        ]
      }
    }
```

**Comment by Nxtra** [comment]
Might using Eventbridge solve this problem?

**Comment by ghukill** [comment]
Not sure if others are still grappling with this, but it looks as thought serverless has a [flag to allow for pre-existing buckets](https://www.serverless.com/framework/docs/providers/aws/events/s3/#custom-bucket-configuration):

```yaml
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: legacy-photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          existing: true   <----------------------------------
```
