### ISSUE TITLE
S3 bucket event does not create bucket as documented

### ISSUE THREAD

**Issue by rikbrown** [serverless/serverless#4203]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Creating an S3 event didn't create the S3 bucket as documented.  The lambda is there but no S3 bucket at all.

* What did you expect should have happened?
The S3 bucket would be created as documented.

* What was the config you used?
```
service: my-service
provider:
  name: aws
  runtime: java8
  profile: myprofile
  region: us-west-2
  stage: dev
package:
  artifact: build/distributions/my-service-1.0-SNAPSHOT.zip
functions:
  myService:
    handler: codes.rik.myservice.MyServiceHandler
    events:
          - s3:
            bucket: photos
```

Similar or dependent issues:
* #3851

## Additional Data

* ***Serverless Framework Version you're using***: 1.21.0
* ***Operating System***: OS X
