### ISSUE TITLE
Access-Control-Allow-Origin problem WITH headers set correctly

### ISSUE THREAD

**Issue by prakashsanker** [serverless/serverless#4225]
# This is a Bug Report

## Description

For bug reports:
I *think* I've correctly set everything up to deal with Access-Control-Allow-Origin, but it does not seem to work.

I have a custom header being passed back and this is what my serverless.yml looks like -

```
  getCompletedTests:
    handler: src/endpoints/tests.completed
    events:
      - http:
          path: /users/{userId}/tests
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - snaphuntjwttoken
              - Access-Control-Allow-Headers
            allowCredentials: false
```

I build my response like this 

```
export function success(statusCode, payload) {
  return {
    statusCode,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Credentials": true,
      "Access-Control-Allow-Headers": "snaphuntjwttoken",
      "Access-Control-Allow-Methods": "GET,HEAD,OPTIONS,POST,PUT",
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  };
}

```

So I'm setting the correct headers.

In Cloudfront, I have these logs -

```
2017-09-07T14:13:48.716Z	c3297d56-93d6-11e7-87f1-d349464ab3c0	WHAT IS RESPONSE

14:13:48
2017-09-07T14:13:48.716Z	c3297d56-93d6-11e7-87f1-d349464ab3c0	{ statusCode: 200, headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': true, 'Access-Control-Allow-Headers': 'snaphuntjwttoken', 'Access-Control-Allow-Methods': 'GET,HEAD,OPTIONS,POST,PUT', 'Content-Type': 'application/json' }, body: '[]' }
2017-09-07T14:13:48.716Z	c3297d56-93d6-11e7-87f1-d349464ab3c0	{ statusCode: 200,
headers: 
{ 'Access-Control-Allow-Origin': '*',
'Access-Control-Allow-Credentials': true,
'Access-Control-Allow-Headers': 'snaphuntjwttoken',
'Access-Control-Allow-Methods': 'GET,HEAD,OPTIONS,POST,PUT',
'Content-Type': 'application/json' },
body: '[]' }
```

So everything is being correctly set.

However, two things happen. 

The first is that the request times out, even though `callback(null, response)` is being called. 
The second is that 

```
ET https://lwzturgwo0.execute-api.ap-southeast-1.amazonaws.com/dev/users/d5cc34e0-93d0-11e7-b8da-8361e1ca24b4/tests 502 ()
dashboard:1 Fetch API cannot load https://lwzturgwo0.execute-api.ap-southeast-1.amazonaws.com/dev/users/d5cc34e0-93d0-11e7-b8da-8361e1ca24b4/tests. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://snaphunt-frontend.s3-website-ap-southeast-1.amazonaws.com' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
I think these are related, but I've done everything that is recommended.

You can hit the url here 

http://snaphunt-frontend.s3-website-ap-southeast-1.amazonaws.com/dashboard

## Additional Data

I'm on 1.17.0
