### ISSUE TITLE
Deploy to a different version for the api endpoint

### ISSUE THREAD

**Issue by prakashraman** [serverless/serverless#4226]
Hi, 

Great stuff again! I am sure you guys hear it all the time.

I am using serverless-lambda-api-gateway to manage my api endpoints. One important workflow I would like to have is everytime I release a set of APIs I would like it to be "versioned" (e.g v1, v1.1, etc).

Do you suggest I use the "stage" option and specify my version or is there another way I should be considering?

`serverless deploy --stage v1`

and next time

`serverless deloy --stage v2`

Would you suggest this?

**Comment by horike37** [comment]
Again hey @prakashraman!

IMO, I don't recommend to use it for managing own API version since the purpose of a stage parameter is to switch each environment something like dev or staging or prod.

The way I do is to write `baseUrl` within serverless.yml as a custom parameter something like this:

```yaml
custom:
  baseUrl: v1

functions:
  subUsers:
    handler: lambdas/api-backend.subUsers
    events:
      - http:
          path: ${self:custom.baseUrl}/sub_users
          method: get
      - http:
          path: ${self:custom.baseUrl}/sub_users
          method: post
```
How do you like it?

**Comment by prakashraman** [comment]
Hey @horike37 thanks for all the help on my questions :) You've been great!

Ah, I see. Might not be the best way do define a prefix/namespace/base-url. But I guess it is good enough :)

Thanks again! Closing the issue.

**Comment by pmuens** [comment]
Thanks for helping out @horike37 👍

@prakashraman glad to hear that this resolved the issue 👍

**Comment by wasenbr** [comment]
Ok, but it could be difficult to maintain the old versions working. How could I deploy a version 2.0 and maintain the 1.0 working?

I should to duplicate my API entry points and deploy 2 handlers, one to each entry point like this:

```
custom:
  baseUrl: V2

functions:
  subUsers:
    handler: lambdas/api-backend.subUsers
    events:
      - http:
          path: ${self:custom.baseUrl}/sub_users
          method: get
      - http:
          path: ${self:custom.baseUrl}/sub_users
          method: post

  subUsersV1:
    handler: lambdas/api-backendV1.subUsers
    events:
      - http:
          path: V1/sub_users
          method: get
      - http:
          path: V1/sub_users
          method: post
```

That is your idea?
