### ISSUE TITLE
Circular dependency between resources

### ISSUE THREAD

**Issue by himadriganguly** [serverless/serverless#4231]
When I am adding the following code in **serverless.yml** file

```
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: [REGION]
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "s3:GetObject"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": [S3BucketBUCKET_NAME] }, "/*" ] ] }
```
On deployment, I am getting **“The CloudFormation template is invalid: Circular dependency between resources:”**

I am using **boto3** with **python3** to get the private file that is uploaded to the S3 bucket after the trigger event so like to give the permission to **Lambda function** for that bucket.

Here is my complete **serverless.yml** file [https://gist.github.com/himadriganguly/9fa02dc82da2382bc1871e8335542351](https://gist.github.com/himadriganguly/9fa02dc82da2382bc1871e8335542351)
