### ISSUE TITLE
Unresolved config variables when passed to plugin

### ISSUE THREAD

**Issue by boazdejong** [serverless/serverless#4244]
# This is a Bug Report

## Description
Variables in the `serverless.yml` are not resolved when passed in to my custom plugin.

### What went wrong?
```yaml
service: test-service

plugins:
  - myCustomPlugin

custom:
  myPluginConfig:
    name: ${opt:stage}-${self:service}
```

In my plugin class constructor, `serverless.service.custom.myPluginConfig.name` is an actual string that holds `${opt:stage}-${self:service}`

### What did you expect should have happened?
The config variables to be resolved.

## Additional Data

* ***Serverless Framework Version you're using***: 1.21.1
