### ISSUE TITLE
Unexpected key 'TimeToLiveSpecification' found in params

### ISSUE THREAD

**Issue by andreimc** [serverless/serverless#4250]
# This is a (Bug Report / Feature Proposal)

## Description
Can't start locally if I specify the         TimeToLiveSpecification for a dynamodb table

It should start.
```
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dynamodb-autoscaling
  - serverless-plugin-custom-domain


    Table:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "crypto_coins"
        TimeToLiveSpecification:
          AttributeName: expiryTime
          Enabled: true
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "currency"
          AttributeType: "S"
        - AttributeName: "expiryTime"
          AttributeType: "N"
        - AttributeName: "dataBlob"
          AttributeType: "B"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "currency"
          KeyType: "RANGE"
        GlobalSecondaryIndexes: 
          - IndexName: currency-id
            KeySchema:
            - AttributeName: "currency"
              KeyType: "HASH"
            - AttributeName: "dataBlob"
              KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: expiry-id
            KeySchema:
            - AttributeName: "id"
              KeyType: "HASH"
            - AttributeName: "expiryTime"
              KeyType: "RANGE"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```
For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

SLS_VERSION: 1.21.1
OS: macOS
node 6.10

STACK_TRACE
```
serverless: Watching with Webpack...
Dynamodb Local Started, Visit: http://localhost:8181/shell
Serverless: DynamoDB - Error -

  Unexpected Parameter -----------------------------------

  Unexpected key 'TimeToLiveSpecification' found in params

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

UnexpectedParameter: Unexpected key 'TimeToLiveSpecification' found in params
    at ParamValidator.fail (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/config.js:315:7)
    at /Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/config.js:333:9
    at Credentials.get (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/config.js:327:24)
    at Config.getCredentials (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/config.js:347:9)
    at Request.VALIDATE_CREDENTIALS (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/event_listeners.js:80:26)
    at Request.callListeners (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/request.js:403:15)
    at Request.send (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/request.js:367:10)
    at makeRequest (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/service.js:193:27)
    at svc.(anonymous function) [as createTable] (/Users/andrei/personal/crypto-api/node_modules/aws-sdk/lib/service.js:474:23)
    at BbPromise (/Users/andrei/personal/crypto-api/node_modules/serverless-dynamodb-local/index.js:244:26)
    at ServerlessDynamodbLocal.createTable (/Users/andrei/personal/crypto-api/node_modules/serverless-dynamodb-local/index.js:240:16)
    at BbPromise.each (/Users/andrei/personal/crypto-api/node_modules/serverless-dynamodb-local/index.js:133:55)
From previous event:
    at ServerlessDynamodbLocal.migrateHandler (/Users/andrei/personal/crypto-api/node_modules/serverless-dynamodb-local/index.js:133:26)
    at BbPromise.resolve.then (/Users/andrei/personal/crypto-api/node_modules/serverless-dynamodb-local/index.js:169:45)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at ServerlessDynamodbLocal.startHandler (/Users/andrei/personal/crypto-api/node_modules/serverless-dynamodb-local/index.js:169:10)
    at BbPromise.reduce (/Users/andrei/personal/crypto-api/node_modules/serverless/lib/classes/PluginManager.js:261:55)
    at emitRecords.err (/Users/andrei/personal/crypto-api/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/andrei/personal/crypto-api/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/andrei/personal/crypto-api/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/andrei/personal/crypto-api/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/andrei/personal/crypto-api/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/andrei/personal/crypto-api/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/andrei/personal/crypto-api/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/andrei/personal/crypto-api/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/andrei/personal/crypto-api/node_modules/webpack/lib/Compiler.js:354:15)
    at /Users/andrei/personal/crypto-api/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/andrei/personal/crypto-api/node_modules/async/dist/async.js:998:13)
    at /Users/andrei/personal/crypto-api/node_modules/async/dist/async.js:906:16
    at /Users/andrei/personal/crypto-api/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at PluginManager.invoke (/Users/andrei/personal/crypto-api/node_modules/serverless/lib/classes/PluginManager.js:261:22)
    at PluginManager.run (/Users/andrei/personal/crypto-api/node_modules/serverless/lib/classes/PluginManager.js:292:17)
    at variables.populateService.then (/Users/andrei/personal/crypto-api/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Serverless.run (/Users/andrei/personal/crypto-api/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/andrei/personal/crypto-api/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.10.0
     Serverless Version:     1.21.1
```
