### ISSUE TITLE
SSM : Inaccessible host: `ssm.'. This service may not be available in the `.......' region.

### ISSUE THREAD

**Issue by anantab** [serverless/serverless#4251]
Serverless throws error when AWS region is referenced from another variable or from another file.

**Comment by lorengordon** [comment]
@anantab Can you share a serverless.yml setup that reproduces the error?

**Comment by anantab** [comment]
Here is my serverless.yml

service: ${self:custom.config.SERVICE_NAME}
custom : 
  defaultStage: dev
  defaultProfile: default
  currentStage: ${opt:stage, self:custom.defaultStage}
  config:  ${file(../config/env-${self:custom.currentStage}/infrastructure.yml)}
  configDB:  ${file(../config/env-${self:custom.currentStage}/lamdaConfigs.yml)}
  AuthorizerTTL: 0
  
provider:
  name: aws
  runtime: ${self:custom.config.NODEJS_RUNTIME_VERSION}
  stage: ${self:custom.currentStage}
  region : ${self:custom.config.AWS_REGION}
  timeout: 60
  
  environment:
    DB_PASSWORD: ${ssm:dbPassword}

The error I am getting is
Inaccessible host: `ssm.'. This service may not be available in the `${self:custom.config.AWS_REGION}' region.

**Comment by lorengordon** [comment]
Ok, then as best I can tell the AWS region which you are using just does not currently support SSM. What region are you using? Here are the regions that support SSM:

* http://docs.aws.amazon.com/general/latest/gr/rande.html#ssm_region

**Comment by anantab** [comment]
Hi, 
I am using ap-southeast-2 which supports SSM. When I hardcode region in serverless.yml, I do not get the error.  I think the error is due to trying to fetch SSM variable before serverless has resolved variable reference.

**Comment by pmuens** [comment]
Thanks for opening @anantab and thanks for providing help here @lorengordon 👍

> I think the error is due to trying to fetch SSM variable before serverless has resolved variable reference.

@anantab I think you're correct. The `AWS_REGION` variable is not be populated yet since the SSM Serverless Variable is itself a variable.

AFAIK there's no way to do this right now (other than hardcoding the region).

Do you have any creative idea how this could be solved in another way @eahefnawy?

**Comment by lorengordon** [comment]
>The AWS_REGION variable is not be populated yet since the SSM Serverless Variable is itself a variable

Ahh, ok, so looking at the code this would be a problem for all variable syntaxes that resolve the variable from AWS services, including CF and S3, not just SSM.

**Comment by lorengordon** [comment]
@anantab Does it work if you remove the `region` line from serverless.yml and pass it on the command line? i.e. `serverless package --region ap-southeast-2`?

**Comment by lorengordon** [comment]
Here's a minimal serverless.yml to reproduce the error and test any patch:

```
service: hello

custom:
  region: "us-east-1"

provider:
  name: aws
  region: ${self:custom.region}
  runtime: nodejs6.10
  environment:
    BARFOO: ${ssm:/bar/foo}

functions:
  hello:
    handler: handler.hello
```

error with `serverless package`:
```
  Serverless Error ---------------------------------------

  Inaccessible host: `ssm.'. This service may not be available in the `${self:custom.region}' region.
```

**Comment by lorengordon** [comment]
And passing the region on the command line does indeed work.

serverless.yml:
```
service: hello

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    BARFOO: ${ssm:/bar/foo}

functions:
  hello:
    handler: handler.hello
```

```
> serverless package --region us-east-2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
> grep FOO .serverless/cloudformation-template-update-stack.json
            "BARFOO": "bar"
```
