### ISSUE TITLE
`sls plugin install` fails

### ISSUE THREAD

**Issue by ryanmurakami** [serverless/serverless#4258]
# This is a Bug Report

## Description

When installing a plugin with a command like:
`sls plugin install --name serverless-webpack`

The command fails with the error:
`Type Error: Cannot read property 'kind' of null`

## Additional Data

* ***Serverless Framework Version you're using***: 1.22
* ***Node.js Version you're using***: 8.5.0
* ***Operating System***: macos

**Comment by horike37** [comment]
Thank you for reporting @ryanmurakami !
We'll take a look into it ASAP.

**Comment by ryanmurakami** [comment]
@horike37 npm v5.3.0
Thanks!

**Comment by horike37** [comment]
@ryanmurakami 
I tried to reproduce it with node v8.5.0 and npm v5.3.0, but didn't on my end..
We should investigate the step to reproduce and the condition.

Could you share the serverless.yml and package.json you faced the problem?
In addition, when the command failing, Could you see a stack trace of the error?

**Comment by pmuens** [comment]
Yes, a `serverless.yml` and the stack trace would be helpful 👍

It looks like the error pops up in the `yamlAstParser.js` file (somewhere [here](https://github.com/serverless/serverless/blob/965ae8acec4813f668f2fd15bb2153281a9d1474/lib/utils/yamlAstParser.js#L23-L47)).

**Comment by ryanmurakami** [comment]
Yep, it's reproing on 8.3.0 also. Here's the full stack:

```sh
TypeError: Cannot read property 'kind' of null
    at _.forEach (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/utils/yamlAstParser.js:27:38)
    at arrayEach (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:9359:14)
    at parseAST (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/utils/yamlAstParser.js:26:7)
    at _.forEach (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/utils/yamlAstParser.js:31:24)
    at arrayEach (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:9359:14)
    at parseAST (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/utils/yamlAstParser.js:26:7)
    at fs.readFileAsync.then.yamlContent (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/utils/yamlAstParser.js:51:21)
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
From previous event:
    at Object.addNewArrayItem (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/utils/yamlAstParser.js:50:35)
    at getServerlessFilePath.then.serverlessFilePath (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/plugins/plugin/install/install.js:124:28)
    at /Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at PluginInstall.addPluginToServerlessFile (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/plugins/plugin/install/install.js:111:41)
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
From previous event:
    at PluginInstall.BbPromise.bind.then.then.then (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/plugins/plugin/install/install.js:62:12)
From previous event:
    at PluginInstall.install (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/plugins/plugin/install/install.js:57:8)
From previous event:
    at Object.plugin:install:install [as hook] (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/plugins/plugin/install/install.js:44:10)
    at BbPromise.reduce (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:358:55)
From previous event:
    at PluginManager.invoke (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:358:22)
    at PluginManager.run (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/classes/PluginManager.js:389:17)
    at variables.populateService.then (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/mrsaturn/.nvm/versions/node/v8.3.0/lib/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.3.0
     Serverless Version:     1.22.0
```

**Comment by ryanmurakami** [comment]
```yml
# serverless.yml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: spotinst-service

provider:
  name: spotinst
  spotinst:
    #environment: <env-XXXX> # NOTE: Remember to add the environment ID

functions:
  hello:
    runtime: nodejs4.8
    handler: handler.main
    memory: 128
    timeout: 30

# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-spotinst-functions
```
