### ISSUE TITLE
serverless package is very slow

### ISSUE THREAD

**Issue by vangorra** [serverless/serverless#4263]
# This is a (Bug Report / Feature Proposal)

## Description
My project written in node and bundled with webpack. It has a lot of dependencies. We have over a dozen functions. 

For bug reports:
* What went wrong?
Running 'serverless package' will run for 20 minutes before I just give up on it. It has been tolerable but slow for some time.

* What did you expect should have happened?
With out function and package configs, this should run in less than 30 seconds.

* What was the config you used?
Here are the relevant bits:
``` yml
package:
  individually: true
  exclude:
    - "**"

functions:
  Function1:
    handler: modules/server/dist/app/handlers/Function1.handler
    memorySize: 256
    timeout: 300
    package:
      include:
      - modules/server/dist/app/handlers/Function1.js
      - modules/server/dist/app/handlers/Function1.js.map

  Function2:
    handler: modules/server/dist/app/handlers/Function2.handler
    memorySize: 256
    timeout: 300
    package:
      include:
      - modules/server/dist/app/handlers/Function2.js
      - modules/server/dist/app/handlers/Function2.js.map
```

* What stacktrace or error message from your provider did you see?
No errors or stack trace. The CPU goes to 100% until I stop the process 20 minutes later. One or two functions do eventually get packaged in .serverless. 

## Additional Data

* ***Serverless Framework Version you're using***:
Confirmed this occurs in 1.18.0 and 1.22.0

* ***Operating System***:
Ubuntu 17.04

It almost seems like the package code is walking the entire file system tree even though it has been explicitly told to ignore all files. I set the function's artifact to a manual zip file and sure enough the package process runs instantly.

**Comment by ljovanovic** [comment]
@vangorra you might try configuring the process to disable the excludeDevDependencies feature.  
```
package:
  individually: true
  excludeDevDependencies: false
```
Ours was having issues completing until we disabled that recently.  I also logged an issue ( #4266 ) describing our situation.

**Comment by vangorra** [comment]
@ljovanovic I toyed with excludeDevDependencies and didn't notice a difference in performance. Then again, package never completes.

As a work around, I wrote our own package code in gulp and set the artifact value on each function. It packages all 15 of our functions in 16 seconds.

``` yml
package:
  individually: true
  exclude:
    - "**"

functions:
  Function1:
    handler: modules/server/dist/app/handlers/Function1.handler
    memorySize: 256
    timeout: 300
    package:
      archive: dist/packages/Function1.zip
      include:
      - modules/server/dist/app/handlers/Function1.js
      - modules/server/dist/app/handlers/Function1.js.map

  Function2:
    handler: modules/server/dist/app/handlers/Function2.handler
    memorySize: 256
    timeout: 300
    package:
      archive: dist/packages/Function2.zip
      include:
      - modules/server/dist/app/handlers/Function2.js
      - modules/server/dist/app/handlers/Function2.js.map
```

``` typescript
import * as yml from 'js-yaml';
import * as archiver from 'archiver';
import * as fs from 'fs-extra';

gulp.task('package:run', async () => {
  assertStage();
  assertAwsCredentails();

  // Package the functions.
  const packagesDir = path.join(__dirname, '/dist/packages');
  fs.removeSync(packagesDir);
  fs.ensureDirSync(packagesDir);

  const slsConfig = yml.safeLoad(fs.readFileSync('./serverless.yml', 'utf-8'));
  for (const funcName of Object.keys(slsConfig.functions)) {
    const funcConfig = slsConfig.functions[funcName];

    if (!funcConfig.package) {
      throw new Error(`functions.${funcName}.package is not set in serverless.yml.`);
    }

    if (!funcConfig.package.artifact) {
      throw new Error(`functions.${funcName}.package.artifact is not set in serverless.yml.`);
    }

    if (!funcConfig.package.include) {
      throw new Error(`functions.${funcName}.package.include is not set in serverless.yml.`);
    }

    if (fs.existsSync(funcConfig.package.artifact)) {
      throw new Error(`Artifact ${funcConfig.artifact} already exists. There's probably another config with the same value in serverless.yml.`);
    }

    console.log(`Creating ${funcConfig.package.artifact}.`);
    const output = fs.createWriteStream(funcConfig.package.artifact);
    const archive = archiver('zip', {
      zlib: { level: 9 } // Sets the compression level.
    });

    archive.pipe(output);

    for (const glob of funcConfig.package.include) {
      archive.glob(glob);
    }

    await archive.finalize();
  }

  // Have serverless generate the cloudformation files.
  runCommand(
    './node_modules/.bin/serverless',
    [
      'package',
      '--stage', stage,
      '--verbose',
    ]
  );
});
```
