### ISSUE TITLE
Lost feature Only redeploy when the code/config changes - #3838

### ISSUE THREAD

**Issue by KKomarov** [serverless/serverless#4289]
# This is a Bug Report

## Description
#3838 Very convenient feature but it was lost :(

For bug reports:
* What went wrong?
```
sls deploy -v
sls deploy -v
```
Redeploys stack two times instead of one

* What did you expect should have happened?
The second deploy should be skipped as no changes

* What was the config you used?
any simple config
```
service: myservice
provider:
  name: aws
  stage: lost
  region: us-east-1
  memorySize: 512

package:
  individually: true

functions:

  func2:
    handler: handler
    timeout: 60
    runtime: nodejs4.3
```

## Additional Data
It was worked in 1.17.0 - 1.20.2 and broken now in 1.21.0 - 1.22.0 (current)

* ***Serverless Framework Version you're using***: ^
* ***Operating System***: linux
* ***Stack Trace***: no stack

**Comment by RafalWilinski** [comment]
I've investigated the issue and it seems that every time `sls deploy` command is executed, Serverless Framework outputs a little bit different CloudFormation template.

Specifically, `AWS::ApiGateway::Deployment` changes: 
![screen shot 2017-09-20 at 13 22 58](https://user-images.githubusercontent.com/3391616/30641373-169fa480-9e07-11e7-8f25-6cea37a6e315.png)

Because of: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js#L151


But there's more.


After digging a little bit more, I've also found that `serverless deploy function -f hello` also perform a full function deployment instead of skipping it, as described here: https://github.com/serverless/serverless/pull/3838

I found out, that following `serverless deploy functions` operations also produce a radically different hash:

<img width="544" alt="screen shot 2017-09-20 at 13 47 23" src="https://user-images.githubusercontent.com/3391616/30642237-4962419a-9e0a-11e7-9e57-61c7bcf45bd5.png">

After opening two ZIP artifacts, I found out that they look simillar, however order of "big pieces" was a little bit off:

![screen shot 2017-09-20 at 13 59 12](https://user-images.githubusercontent.com/3391616/30642660-081e59e2-9e0c-11e7-9d40-6596842ba5e0.png)

That is, because files are not always packaged in the same sequence. You can clearly see that if you add `debugger` statement here:

https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/zipService.js#L90

Result:

![rafal rafals-macbook-pro node serverless-develop examples basic zsh 2017-09-20 13-55-56](https://user-images.githubusercontent.com/3391616/30642558-a46e3b10-9e0b-11e7-9827-adb045821fc4.png)

That's because of async nature of `this.getFileContent`. Sometimes it's faster to read one file, sometimes it's faster to read another one.

Fixing it might be tricky. I'll try to come up with something.

cc @pmuens @eahefnawy

**Comment by HyperBrain** [comment]
@RafalWilinski FYI: The APIG deployment MUST be different on each deploy, as it resembles the current state of all deployed APIG resources. If it is not different the deployment will not work as expected.
There are other resources that must change from deploy to deploy as well.

Imo the identity check for changes templates must explicitly exclude these resources that rather affect the deployment process behavior than the actual contained data resources (like functions). Other examples for such resources are the function version resources which also MUST change on each deploy if the function code or configuration changed.

Regarding the function versions, it would be imo better to have these only change after it has been checked that the code or configuration changed and keep the already deployed resources otherwise in the template. This will automatically lead to a difference deployment without the need to check for anything else than the code + function configs. Even changes in the CF template do not have to be changed because CF fully takes care of that.

**Comment by KKomarov** [comment]
@RafalWilinski thank you for quick PRs! I forgot to mention that #3838 feature does not take pre-builded package artifacts into account. So, such config will always be redeployed. Can you check it too?
```
provider:
  name: aws
  stage: artifact
  region: us-east-1
  memorySize: 512

package:
  individually: true

functions:

  func1:
    handler: myfolder.handler
    timeout: 60
    runtime: nodejs4.3
    package:
      artifact: mypackage.zip
```
