### ISSUE TITLE
"serverless run" producing error

### ISSUE THREAD

**Issue by leroyjware** [serverless/serverless#4307]
# This is a (Bug Report / Feature Proposal)

## Description
After running "serverless login", when I run "serverless run" in a service folder, I am seeing the following error. My serverless.yml file contains a single function (I'm using your "analytics" service from the Event Gateway examples (https://github.com/serverless/event-gateway-example/tree/master/services/analytics).

 Error --------------------------------------------------
 
  Failed to register at least one function.

 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Failed to register at least one function.

    at Promise.all.then.catch.functionError (/usr/local/lib/node_modules/serverless/node_modules/@serverless/fdk/lib/configure.js:34:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Thanks for opening @leroyjware 👍

Could you please share your `serverless.yml` file and the Serverless Framework version you're using so that we can look into it? Thanks!

**Comment by torchhound** [comment]
I am experiencing a slightly different error with a similar stack trace. I'm running serverless 1.25.0, on Arch Linux, Node Version 9.3.0. When I run `serverless run` I get this error but not when I run `serverless deploy` to AWS. 

Error:
`
Failed to configure the Event Gateway. Failed to configure the Event Gateway. Failed to subscribe the event undefined to the function thorus-api-scheduledDelete due the error: Subscription doesn't validate. Validation error: "Key: 'Subscription.Event' Error:Field validation for 'Event' failed on the 'required' tag"
`
Stack Trace:
`
Error: Failed to configure the Event Gateway. Failed to configure the Event Gateway. Failed to subscribe the event undefined to the function thorus-api-scheduledDelete due the error: Subscription doesn't validate. Validation error: "Key: 'Subscription.Event' Error:Field validation for 'Event' failed on the 'required' tag"
    at Promise.all.then.catch.functionError (/usr/lib/node_modules/serverless/node_modules/@serverless/fdk/lib/configure.js:35:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
`
Serverless.yml:
```
service: thorus-api
# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
provider:
  name: aws
  apiKeys:
    - prodKey
    - ${self:provider.stage}-prodKey
    - ${file(./config.json):apiKey} #Clients connecting to this Rest API will then need to set any of these API keys values in the x-api-key header of their request.
  runtime: nodejs6.10
  stage: prod
  region: ${file(./config.json):region}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: ${file(./config.json):dynamoResource}
functions:
  createThread:
    handler: handler.createThread
    events:
      - http:
          path: thorus/create/thread
          method: post
          cors: true
          private: true
  getAllThreads:
    handler: handler.getAllThreads
    events:
      - http:
          path: thorus/read/{days}
          method: get
          request:
            parameters:
              paths:
                days: true
          cors: true
          private: true
  createPost:
    handler: handler.createPost
    events:
      - http:
          path: thorus/create/{thread}
          method: post
          request:
            parameters:
              paths:
                thread: true
          cors: true
          private: true
  scheduledDelete:
    handler: handler.scheduledDelete
    events:
      - schedule: rate(7 days)
```
