### ISSUE TITLE
Get stacktrace of error from Node.js Invoke local

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#4309]
# This is a Feature Proposal

## Description

With the previous Serverless Offline we got the Stacktrace of the error helping us debug the errors/bugs but the new Severless version with "invoke local" (Which is totally great to get included) we only get the "Lambda" error, e.g.:

`
{
    "errorMessage": "The specified key does not exist.",
    "errorType": "Error"
}
`

## Additional Data

* ***Serverless Framework Version you're using***: 1.17.0
* ***Operating System***: Ubuntu subsystem on Windows 10 and Linux
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by horike37** [comment]
Hey, @QAnders! Thank you for opening this issue!
It would be good if you can share us more information so that we can take a look into that 

- Which version are you using Serverless Offline?
- Am I correct in understanding that you can't get the stacktrace of the error with the combination of Serverless 1.23.0 + Serverless Offline the version which you are using? Does this sound good?
- In addition, Could you share your serverless.yml?

**Comment by horike37** [comment]
Seems that the related issue of #4310

**Comment by QAnders** [comment]
No, not related to #4310...

I am using 1.17.0 of SLS with Webpack.

`sls invoke local --function createeInvoice --path ../test.createeinvoice.json  --contextPath /mnt/d/Q/GitHub-Repos/test.createeinvoice.context.json`

```
service: invoice-routing

plugins:
  - serverless-webpack
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  # profile: qiptest
  memorySize: 512
  timeout: 15
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DeleteNetworkInterface'
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource: '*'
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.VPC_SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.VPC_SUBNET_ID1}
      - ${self:custom.secrets.VPC_SUBNET_ID2}

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  # Internal

  createeInvoice:
    handler: handler.createeInvoiceHandler
	x
	x
	x
	x
```
