### ISSUE TITLE
nested variables don't work with custom variableSyntax

### ISSUE THREAD

**Issue by mvayngrib** [serverless/serverless#4312]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

syntax error when using nested variables with a custom `variableSyntax`

* What was the config you used?
```yml
service: nestedvarstest
plugins:
  - print

custom:
  stage: dev
  # DRAGONS BE HERE
  nested: ${{file(./config.${{self:custom.stage}}.json)}}

provider:
  name: aws
  runtime: nodejs6.10
  variableSyntax: "\\${{([\\s\\S]+?)}}"

functions:
  hello:
    handler: handler.hello
```
* What stacktrace or error message from your provider did you see?
```sh
$ serverless package
 
  Serverless Error ---------------------------------------
 
  Invalid variable reference syntax for variable file(./config.${{self:custom.stage. You can only reference env vars, options, & files. You can check our docs for more info.
 
```

## Additional Data
```sh
Environment Information
     OS:                     darwin
     Node Version:           7.10.1
     Serverless Version:     1.23.0
```

See [repo](https://github.com/mvayngrib/serverless-nested-vars) with this config
