### ISSUE TITLE
Feature Proposal: Customize the default IAM role on function level

### ISSUE THREAD

**Issue by balassy** [serverless/serverless#4313]
## Description

Currently when I define IAM role statements on function level, they will override the default generated IAM role customized at the provider level. However there can be functions that would need additional permissions to operate properly. Following the principle of least privilege it would be great, if the IAM role generated for a function could not only replace the default role, but there would be an option to extend or customize the provider level role on function level.

Examples: 
* I have multiple functions, but only 1 of them needs to access S3.
* I have multiple functions that needs to access S3, but only 1 of them needs to delete from S3.

If this is already possible, please extend to existing documentation to describe how.

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0

Thanks for creating and maintaining this project!

**Comment by horike37** [comment]
Thank you for sending a great feature proposal @balassy 💯 
We are likely to need more feedback from someone else so that we know the detail of specification or how to set up looks like in serverless.yml 👍

**Comment by balassy** [comment]
Thanks for the feedback, Takahiro.

Currently you can define an `iamRoleStatements` property on the `provider` level with effect, action and resource, and a `role` element with a name on function level. I propose a new `extendIamRoleStatements` (any other name can work well of course) element on function level which allows configuring effects, actions and resources, and the union of the provider level and the function level statements is applied to the function during deployment.

How can I help?

**Comment by theburningmonk** [comment]
+100 to this, many people (including folks at AWS) I speak to wants the ability to define per-function policies easily, you can already do it with the serverless framework but it's [rather clumsy](https://serverless.com/framework/docs/providers/aws/guide/iam/#custom-iam-roles-for-each-function) and adds a lot of friction (requires setting up the role as custom CF resource, and have to manually include the permissions the Serverless framework adds for you out by default, eg. CWLogs), and as such I don’t know of anyone who actually do this in production.

```
service: new-service

provider:
  name: aws
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::"
             - Ref: ServerlessDeploymentBucket

functions:
  func0:
    ...
    iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "s3:PutObject"
         Resource:
           Fn::Join:
             - ""
             - - "arn:aws:s3:::"
               - Ref: ServerlessDeploymentBucket
               - "/*"
    func1:
      ...
    func2:
      ...
```
In the above example, `func1` and `func2` would inherit the IAM role created at the service level, with the permission for `s3:ListBuckets`. But since `func0` specifies its own IAM statement, these statements should be concatenated with the service level IAM statements to create a new role, and assigned to the `func0` function, giving it permissions for both `s3:ListBuckets` and `s3:PutObject`.

**Comment by horike37** [comment]
Thank you for the proposal @theburningmonk and @balassy :+1: 
I almost agree with https://github.com/serverless/serverless/issues/4313#issuecomment-349614369 example.

Additionally, we might want to consider the case which we want to override the IAM role created at the service level instead of inheritance.
imo, as default, inheriting the service level, and you can completely override by adding optional property under `iamRoleStatements` at the function level.
It would be something like this.

```
functions:
  func0: 
    iamRoleStatements:
      type: override #you can specify `override` or `inherit `
      definitation:
        -  Effect: "Allow"
           Action:
             - "s3:PutObject"
           Resource:
             Fn::Join:
               - ""
               - - "arn:aws:s3:::"
                 - Ref: ServerlessDeploymentBucket
                 - "/*"
```

You can omit `type` property. In this case, the IAM role at the function level inherits it at the service level.

```
functions:
  func0: 
    iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "s3:PutObject"
         Resource:
           Fn::Join:
             - ""
             - - "arn:aws:s3:::"
               - Ref: ServerlessDeploymentBucket
               - "/*"
```

What do you think?
cc @serverless/framework-maintainers
