### ISSUE TITLE
Serverless Function Deploy Validation Errors Appear After Upgrade to 1.22.0

### ISSUE THREAD

**Issue by enhanse** [serverless/serverless#4329]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Since upgrading from serverless 1.21.1 to 1.22.0,
when using `serverless deploy function -f myfunction`
near the end of the deploy, errors are thrown. See the `Additional Data` section.

A snippet of the serverless.yml is as follows:
```  environment:
    REGION: ${{self:provider.region}}
    PREPARE_STREAM_ID: "my-prepare-stream"
    PREPARE_STREAM:
      Ref: PrepareStream
    PROCESS_STREAM_ID: "my-process-stream"
    PROCESS_STREAM:
      Ref: ProcessStream
    SERVICE_ENDPOINT:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: ApiGatewayRestApi
          - ".execute-api."
          - ${{self:provider.region}}
          - ".amazonaws.com/"
          - ${{self:provider.stage}}
```

It seems that computed/CF variables are incorrectly expected to be a string.

* What did you expect should have happened?
A successful deploy. This appears to only affect function deploy, `serverless deploy` still works as expected.
* What was the config you used?
* What stacktrace or error message from your provider did you see?
```Serverless: Packaging function: prepare...
Serverless: Uploading function: myfunction (6.94 MB)...
 
  Serverless Error ---------------------------------------
 
  There were 3 validation errors:
* InvalidParameterType: Expected params.Environment.Variables['PREPARE_STREAM'] to be a string
* InvalidParameterType: Expected params.Environment.Variables['PROCESS_STREAM'] to be a string
* InvalidParameterType: Expected params.Environment.Variables['SERVICE_ENDPOINT'] to be a string
```

## Additional Data

* ***Serverless Framework Version you're using***:
1.22.0
* ***Operating System***:
node 6.10.3
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Hey, @enhanse. Thank you for reporting the bug 👍 
Could you share your entire serverless.yml file so that we can try to reproduce that?

**Comment by mancvso** [comment]
I can confirm, here is my serverless.yml

```yml
# Welcome to Estuario!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: transportes-del-estuario

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
  # Could not make Lambda work with Elasticache :C
  # vpc:
  #   securityGroupIds:
  #    - 'Fn::GetAtt': SecurityGroup.GroupId
  #   subnetIds:
  #    - Ref: Private1
  #    - Ref: Private2

provider:
  name: aws
  memorySize: 256
  timeout: 5
  region: us-west-2
  apiKeys:
    - ${opt:stage, self:provider.stage}-secret-name
  environment:
    TABLE_NAME: { "Ref": "PasajesTable" }
    TABLE_ARN: { "Fn::GetAtt": ["PasajesTable", "Arn" ] }
    TABLE_STREAM_ARN: { "Fn::GetAtt": ["PasajesTable", "StreamArn" ] }
    TABLE_COMPRAS_NAME: { "Ref": "ComprasTable" }
    TABLE_COMPRAS_ARN: { "Fn::GetAtt": ["ComprasTable", "Arn" ] }
    TABLE_COMPRAS_STREAM_ARN: { "Fn::GetAtt": ["ComprasTable", "StreamArn" ] }
    TABLE_VEHICULOS_NAME: { "Ref": "VehiculosTable" }
    BOLETOS_BUCKET: { "Ref": "BoletosBucket" }
    #REDIS_ADDRESS: { "Fn::GetAtt": ["EstuarioElasticacheCluster", "RedisEndpoint.Address"] }
    #REDIS_PORT: { "Fn::GetAtt": ["EstuarioElasticacheCluster", "RedisEndpoint.Port"] }
    #REDIS_PASS: { "Fn::GetAtt": ["EstuarioElasticacheCluster", "RedisEndpoint.Port"] }#REDIS_ADDRESS: { "Fn::GetAtt": ["EstuarioElasticacheCluster", "RedisEndpoint.Address"] }
    REDIS_ADDRESS: "external-service-because-i-suck-at-vpc"
    REDIS_PORT: "11429"
    REDIS_PASS: "external-password"
    REDIS_TIMEOUT: "1000"
  iamRoleStatements:
     - Effect: Allow
       Resource: { "Fn::GetAtt": ["PasajesTable", "Arn" ] }
       Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
     - Effect: Allow
       Resource: { "Fn::GetAtt": ["ComprasTable", "Arn" ] }
       Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
     - Effect: Allow
       Resource: "*"
       Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  #capacities:
  #  - table: ComprasTable  # DynamoDB Resource
  #    index:              # List or single index name
  #      - custom-index-name
  #    read:
  #      minimum: 5        # Minimum read capacity
  #      maximum: 1000     # Maximum read capacity
  #      usage: 0.75       # Targeted usage percentage
  #    write:
  #      minimum: 40       # Minimum write capacity
  #      maximum: 200      # Maximum write capacity
  #      usage: 0.5        # Targeted usage percentage

plugins:
  #- serverless-dynamodb-autoscaling
  - serverless-dynamodb-local # debe ir antes de -offline
  - serverless-offline

functions:
  PasajesGet:
    handler: pasajes/index.get
    runtime: nodejs6.10
    events:
      - http:
          path: pasajes/{Id}
          method: get
          cors: true
          private: true
          request:
            parameters:
              paths:
                Id: true
  
  PasajesDelete:
    handler: pasajes/index.delete
    runtime: nodejs6.10
    events:
      - http:
          path: pasajes/{Id}
          method: delete
          request:
            parameters:
              paths:
                Id: true
  
  PasajesPut:
    handler: pasajes/index.put
    runtime: nodejs6.10
    events:
      - http:
          path: pasajes/{Id}
          method: put
          request:
            parameters:
              paths:
                Id: true
  
  Contador:
    handler: metricas/index.contar
    runtime: nodejs6.10
    events:
      - stream:
          arn: { "Fn::GetAtt": ["PasajesTable", "StreamArn" ] }
          type: dynamodb
          batchSize: 10
          startingPosition: LATEST
          enabled: true

  GenerarOrdenCompra:
    handler: compras/index.generar_orden_compra
    runtime: nodejs6.10
    events:
      - http:
          path: compras/
          method: post
          cors: true
          authorizer: aws_iam #arn: arn:aws:cognito-idp:us-west-2:937141152670:userpool/us-west-2_qDcdGeFE6

  GenerarBoleto:
    handler: boletos/handler.generar
    runtime: nodejs6.10
    events:
      - http:
          path: boleto/
          method: post
          cors: true
          authorizer: aws_iam #arn: arn:aws:cognito-idp:us-west-2:937141152670:userpool/us-west-2_qDcdGeFE6
  
  ConsultarVehiculo:
    handler: vehiculos/handler.consultar
    runtime: python3.6
    events:
      - http:
          path: vehiculos/
          method: post
          cors: true
          authorizer: aws_iam

# =============== TRANSBANK

  IniciarCompra:
    handler: transbank/handler.ack
    runtime: nodejs6.10
    events:
      - http:
          path: transbank/iniciar
          method: post
          cors: true
          private: true
          #authorizer: aws_iam #arn: arn:aws:cognito-idp:us-west-2:937141152670:userpool/us-west-2_qDcdGeFE6

  VerificarCompra:
    handler: transbank/handler.ack
    runtime: nodejs6.10
    events:
      - http:
          path: transbank/verificar
          method: post
          cors: true
          private: true
          #authorizer: aws_iam #arn: arn:aws:cognito-idp:us-west-2:937141152670:userpool/us-west-2_qDcdGeFE6

  ConsolidarCompra:
    handler: transbank/handler.ack
    runtime: nodejs6.10
    events:
      - http:
          path: transbank/consolidar
          method: post
          cors: true
          private: true
          #authorizer: aws_iam #arn: arn:aws:cognito-idp:us-west-2:937141152670:userpool/us-west-2_qDcdGeFE6

# DynamoDB stream to trigger ticket generation
resources:
  Resources:
    PasajesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PasajesTable
        AttributeDefinitions: 
          - 
            AttributeName: "Id"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "Id"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        StreamSpecification:
          StreamViewType: "NEW_IMAGE"

    ComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ComprasTable
        AttributeDefinitions: 
          - 
            AttributeName: "Id"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "Id"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_IMAGE"
        #GlobalSecondaryIndexes:
        #- IndexName: pantente_index
        #  KeySchema:
        #    - AttributeName: patente
        #      KeyType: HASH
        #  Projection:
        #    ProjectionType: ALL
        #  ProvisionedThroughput:
        #    ReadCapacityUnits: 5
        #    WriteCapacityUnits: 5
    VehiculosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VehiculosTable
        AttributeDefinitions: 
          - { AttributeName: "patente", AttributeType: "S" }
        KeySchema: 
          - {AttributeName: "patente", KeyType: "HASH" }
        ProvisionedThroughput: 
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_IMAGE"

    BoletosBucket:
      Type: AWS::S3::Bucket
    
   # Could not make Lambda work with Elasticache :C
    # EstuarioVPC:
    #   Type: AWS::EC2::VPC
    #   Properties:
    #     CidrBlock: "10.0.0.0/16"

    # PublicSubnet:
    #   DependsOn: EstuarioVPC
    #   Type: AWS::EC2::Subnet
    #   Properties:
    #     VpcId:
    #       Ref: EstuarioVPC
    #     AvailabilityZone: 'us-west-2a'
    #     CidrBlock: "10.0.0.0/24"

    # Private1:
    #   Type: AWS::EC2::Subnet
    #   Properties:
    #     VpcId:
    #       Ref: EstuarioVPC
    #     AvailabilityZone: 'us-west-2a'
    #     CidrBlock: "10.0.1.0/24"

    # Private2:
    #   Type: AWS::EC2::Subnet
    #   Properties:
    #     VpcId:
    #       Ref: EstuarioVPC
    #     AvailabilityZone: 'us-west-2c'
    #     CidrBlock: "10.0.2.0/24"

    # InternetGateway:
    #   Type: AWS::EC2::InternetGateway

    # InternetGatewayAssociation:
    #   Type: AWS::EC2::VPCGatewayAttachment
    #   Properties:
    #     VpcId:
    #       Ref: EstuarioVPC
    #     InternetGatewayId:
    #       Ref: InternetGateway

    # NATIP:
    #   DependsOn: InternetGatewayAssociation
    #   Type: AWS::EC2::EIP
    #   Properties:
    #     Domain: vpc

    # NatGateway:
    #   Type: AWS::EC2::NatGateway
    #   Properties:
    #     AllocationId: {"Fn::GetAtt": ["NATIP","AllocationId"]}
    #     SubnetId:
    #       Ref: PublicSubnet

    # igRouteTable:
    #   Type: AWS::EC2::RouteTable
    #   Properties:
    #     VpcId:
    #       Ref: EstuarioVPC
     
    # igRoute:
    #   Type: AWS::EC2::Route
    #   Properties:
    #     RouteTableId:
    #       Ref: igRouteTable
    #     DestinationCidrBlock: 0.0.0.0/0
    #     GatewayId:
    #       Ref: InternetGateway

    # natRouteTable:
    #   Type: AWS::EC2::RouteTable
    #   Properties:
    #     VpcId:
    #       Ref: EstuarioVPC

    # natRoute:
    #   Type: AWS::EC2::Route
    #   Properties:
    #     RouteTableId:
    #       Ref: natRouteTable
    #     DestinationCidrBlock: 0.0.0.0/0
    #     NatGatewayId:
    #       Ref: NatGateway

    # PrivateSubnetRouteTableAssociation1:
    #   Type: AWS::EC2::SubnetRouteTableAssociation
    #   Properties:
    #     SubnetId:
    #       Ref: Private1
    #     RouteTableId:
    #       Ref: natRouteTable

    # PrivateSubnetRouteTableAssociation2:
    #   Type: AWS::EC2::SubnetRouteTableAssociation
    #   Properties:
    #     SubnetId:
    #       Ref: Private2
    #     RouteTableId:
    #       Ref: natRouteTable
 
    # SecurityGroup:
    #   Type: AWS::EC2::SecurityGroup
    #   Properties:
    #     GroupDescription: Limits security group egress traffic
    #     VpcId:
    #       Ref: EstuarioVPC
    #     SecurityGroupIngress:
    #      - IpProtocol: "-1"
    #     SecurityGroupEgress:
    #      - IpProtocol: "-1"
    #        CidrIp: 0.0.0.0/0

    # InternalSecurityGroup:
    #   Type: AWS::EC2::SecurityGroup
    #   Properties:
    #     VpcId:
    #       Ref: EstuarioVPC
    #     GroupDescription: Allow the machines in this group to share all kinds of traffic between each other
    #     SecurityGroupIngress:
    #      - IpProtocol: "-1"
    #        FromPort: "-1"
    #        ToPort: "-1"
    #        SourceSecurityGroupId:
    #          Ref: SecurityGroup

    # Endpoint:
    #   Type: 'AWS::EC2::VPCEndpoint'
    #   Properties:
    #     ServiceName: 'com.amazonaws.us-west-2.dynamodb'
    #     VpcId:
    #       Ref: EstuarioVPC

    # EstuarioElasticacheSubnetGroup:
    #   Type: AWS::ElastiCache::SubnetGroup
    #   Properties:
    #     Description: "Cache Subnet Group"
    #     SubnetIds:
    #     - Ref: Private1
    #     - Ref: Private2

    # EstuarioElasticacheCluster:
    #   DependsOn: EstuarioVPC
    #   Type: AWS::ElastiCache::CacheCluster
    #   Properties:
    #     AutoMinorVersionUpgrade: true
    #     Engine: redis
    #     CacheNodeType: cache.t2.micro
    #     NumCacheNodes: 1
    #     VpcSecurityGroupIds:
    #     - Ref: InternalSecurityGroup
    #     CacheSubnetGroupName:
    #       Ref: EstuarioElasticacheSubnetGroup

```
