### ISSUE TITLE
Use different yml files for stages. 

### ISSUE THREAD

**Issue by pralivera** [serverless/serverless#4330]
I want to manage separate yml files for each AWS stage. That means my DEV and PROD stages have two different yml files. 
I tried Serverless deploy --config prod.yml command to use this files, but it still referring the default yml file in the folder.
How can I use multiple yml files?

**Comment by horike37** [comment]
Thank you for opening this issue @pralivera 💯 

It is possible to do multiple files strategy by using variables system of Serverless Framework.
https://serverless.com/framework/docs/providers/aws/guide/variables/#variables

For instance, if you want to read the value corresponding to stages, you can define something like this

```yaml
custom:
  config: ${file(./${opt:stage}.yml):config}

functions:
  hello:
     name: ${self:custom.config.functionName}
```
And corresponding stage yml file is something like this
```yaml
config:
  functionName: hello
  xxx: yyyy
  aaa: bbb
```

Ping us if you have any other questions 👍
