### ISSUE TITLE
APIG POST method has not the same headers configured as OPTIONS (header maps not copied completely)

### ISSUE THREAD

**Issue by componentDidMount** [serverless/serverless#4334]
# This is a Bug Report

## Description
- Header mappings were not configured equally for OPTIONS when creating a POST endpoint
- I expected the POST response to have a Access-Control-Allow-Credentials header (like the OPTIONS did)
- I used the following config: 

```
functions:
  index:
    handler: handler.index
    events:
      - http:
          method: POST
          path: /graphql
          integration: lambda
          cors:
            origins:
              - http://localhost:3000
            headers:
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Methods
              - Access-Control-Allow-Credentials
              - Origin
              - Host
              - X-Requested-With
              - Content-Type
            allowCredentials: true
          response:
            headers:
              Set-Cookie: integration.response.body.cookie
            template: $input.json('$.json')
```

- I saw that a OPTIONS method was created with the Access-Control-Allow-Credentials header in API Gateway but the POST method was missing those, the only one it copied was the Access-Control-Allow-Origin header.
- I was able to fix this issue manually by entering API Gateway, adding the headers also to the POST methods 'Method Response' and 'Integration Response' by hand, i expected that to happen automatically (I guess)

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Mac OS X
* ***Stack Trace***: nope
* ***Provider Error messages***: nope

This is what the POST looked like: https://www.dropbox.com/s/qc9wiugiac2346i/Screenshot%202017-10-03%2015.53.30.png?dl=0 while OPTIONS looked like this: https://www.dropbox.com/s/ngvmsesrbt0f6ms/Screenshot%202017-10-03%2015.54.10.png?dl=0
(different response headers)
