### ISSUE TITLE
Unable to deploy dependency (xmlhttprequest, uuid)

### ISSUE THREAD

**Issue by rajivkanaujia** [serverless/serverless#4336]
# This is a Bug Report

## Description

For bug reports:
* Using API Gateway and Lambda for Serverless. A lambda function uses "xmlhttprequest" to do a PUT request. 
* The request should have executed, as it works successfully in serverless invoke local.
* The deployed lambda fails as it cannot find xmlhttprequest
* What was the config you used?
```
{
  "name": "<-removed->",
  "version": "1.0.0",
  "description": "<-removed->",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/<-removed->"
  },
  "keywords": [],
  "author": "<-removed->",
  "license": "ISC",
  "devDependencies": {
    "aws-sdk": "^2.12.0",
    "serverless": "^1.21.0",
    "serverless-dynamodb-local": "^0.2.18",
    "serverless-offline": "^3.16.0"
  },
  "bugs": {
    "url": "https://github.com/<-removed->/issues"
  },
  "homepage": "https://github.com/<-removed->#readme",
  "dependencies": {
    "fs": "^0.0.1-security",
    "path": "^0.12.7",
    "uuid": "^2.0.3",
    "serverless-aws-documentation": "^0.8.0",
    "xmlhttprequest": "^1.8.0"
  }
}
```
* Key items from Serverless.yml
```
package:
#  include:
#    - include-me.js
#    - include-me-dir/**
  exclude:
    - config.yml   # used to pass env to Lambda 
#    - exclude-me.js
#    - exclude-me-dir/**
functions:
  createAccount:
    handler: handler.createAccount
    events:
      - http:
          path: /v1/account/{account_id}/create 
          method: post
          cors: true
plugins:
  - serverless-dynamodb-local
  - serverless-offline
```

* What stacktrace or error message from your provider did you see?
```
2017-10-03 13:09:56.968 (-04:00) Error: Cannot find module 'xmlhttprequest'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports.createArchiveAccount (/var/task/handler.js:233:51)
```
Similar or dependent issues:
* https://github.com/serverless/serverless/issues/1914

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Mac 10.13 (17A365)
