### ISSUE TITLE
Deploying / removing functions to GCF suddenly stopped working

### ISSUE THREAD

**Issue by jfcieslak** [serverless/serverless#4343]
# This is a Bug Report

## Description
* What went wrong?
Suddenly I am not able to deploy (or remove) functions to GCF.
My configuration has not changed, neither on google cloud, nor in my serverless.yml
I was able to deploy my functions without any trouble before.

* What did you expect should have happened?
I should be able to deploy / remove functions with sls cli
* What was the config you used?
Here is my serverless.yml:
```
service: blc-functions

provider:
    name: google
    runtime: nodejs
    project: britishlawcentre-180122
    credentials: ~/.gcloud/britishlawcentre-180122/keyfile.json

plugins:
    - serverless-google-cloudfunctions

package:
    exclude:
        - node_modules/**
        - .gitignore
        - .git/**

functions:
    clSignature:
        handler: clSignature
        events:
            - http: path
    mailer:
        handler: mailer
        events:
            - http: path
```
* What stacktrace or error message from your provider did you see?
```
Error: Error: Not Found
    at filArgs.reduce (/Users/franz/Sites/blc-functions/node_modules/serverless-google-cloudfunctions/provider/googleProvider.js:67:33)
    at JWT.OAuth2Client._postRequest (/Users/franz/Sites/blc-functions/node_modules/google-auth-library/lib/auth/oauth2client.js:402:3)
    at postRequestCb (/Users/franz/Sites/blc-functions/node_modules/google-auth-library/lib/auth/oauth2client.js:362:12)
    at Request._callback (/Users/franz/Sites/blc-functions/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/Users/franz/Sites/blc-functions/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/franz/Sites/blc-functions/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/franz/Sites/blc-functions/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
From previous event:
    at PluginManager.invoke (/Users/franz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/Users/franz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/Users/franz/.config/yarn/global/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Serverless.run (/Users/franz/.config/yarn/global/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/franz/.config/yarn/global/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>
```
* ***Serverless Framework Version you're using***: 1.22
* ***Operating System***: Mac OSX / darwin
* ***Stack Trace***:
* ***Provider Error messages***:
