### ISSUE TITLE
"sls remove" not work after setting CloudWatchEvent's target to a version instead of deafult

### ISSUE THREAD

**Issue by boyuwangva** [serverless/serverless#4352]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?

  After changing cloud watch event's target from default to one version of AWS lambda function, 
  the "sls remove" can not work well and must delete CloudFormation stack manually.

* What did you expect should have happened?

  Even change target of generated "cloud watch event rule" to a version or an alias,
  of course, belongs to the same function deployed by sls,
  the "sls remove" should work fine, is it possible?

* What was the config you used?

  Just the most simple yml
```
service: vam-versiontest # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7

  region: ap-northeast-1


functions:
  vam:
    handler: handler.hello
    name: vamTest
    events:
      - schedule:
          rate: cron(0 3 ? * FRI *)
          enabled: true
```
* What stacktrace or error message from your provider did you see?

```
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
......
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: VamEventsRuleSchedule1 - Rule can't be deleted since it has targets..

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.3
     Serverless Version:     1.21.0

```

## Additional Data

* ***Serverless Framework Version you're using***:1.21.0
* ***Operating System***:CentOS 7.3.1611
* ***Stack Trace***:
* ***Provider Error messages***:
