### ISSUE TITLE
Introduce a functionality which deploy api-gateway events attach to external lambda

### ISSUE THREAD

**Issue by lintaonz** [serverless/serverless#4369]
# This is a Feature Proposal

## Description

For feature proposals:

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Our api-gateway different endpoints point to different lambda functions which are hosted in different repo and maintained by different teams. We need to deploy these lambda functions individually and a global serverless.yml which just deploy api-gateway events.

* If there is additional config how would it look

```
service: serverless-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10

functions:
  currentTime:
    arn: xxx:xxx:Lambda-Name
    events:
      - http:
          path: ping
          method: get
```

## Additional Data

* ***Serverless Framework Version you're using***:  1.22.0
