### ISSUE TITLE
Custom Authorizer sample is not passing Enhanced Context to the target Lambda function

### ISSUE THREAD

**Issue by behrangsa** [serverless/serverless#4374]
# This is a Bug Report

## Description

* What went wrong?

Cognito Enhanced Context properties did not get passed to the target Lambda function.

* What did you expect should have happened?

Cognito Enhanced Context properties get passed to the target Lambda function.

* What was the config you used?

```yml
service: twitter-auth-service

provider:
  name: aws
  runtime: nodejs6.10

functions:

  authorizer:
    handler: authorizer.handler

  protected:
    handler: protected.handler
    events:
      - http:
          path: api/protected
          method: get
          integration: lambda
          authorizer: authorizer
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
```

Where in the authorizer is:

```js
module.exports.handler = function (event, context, callback) {
    console.log("Custom authorizer", event, context);

    let authResponse = {};
    let policyDocument = {};
    policyDocument.Version = '2012-10-17';
    policyDocument.Statement = [];
    policyDocument.Statement.push({
        Action: 'execute-api:Invoke',
        Effect: 'Allow',
        Resource: event.methodArn
    });

    authResponse.policyDocument = policyDocument;
    authResponse.principalId = "xyz";
    authResponse.context = {
        "stringKey": "stringval",
        "numberKey": 123,
        "booleanKey": true
    };

    callback(null, authResponse);
};
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: Ubuntu 17.04

## Extra details

If you modify the response of the sample [here](https://github.com/serverless/examples/tree/master/aws-node-auth0-custom-authorizers-api) to include extra information passed using [enhanced context](https://aws.amazon.com/about-aws/whats-new/2016/12/enhanced-context-for-custom-authorizers-in-amazon-api-gateway/), they don't get passed to the target function.

For example, if I use the following dummy authorizer

```
module.exports.handler = function (event, context, callback) {
    console.log("Custom authorizer", event, context);

    let authResponse = {};
    let policyDocument = {};
    policyDocument.Version = '2012-10-17';
    policyDocument.Statement = [];
    policyDocument.Statement.push({
        Action: 'execute-api:Invoke',
        Effect: 'Allow',
        Resource: event.methodArn
    });

    authResponse.policyDocument = policyDocument;
    authResponse.principalId = "xyz";
    authResponse.context = {
        "stringKey": "stringval",
        "numberKey": 123,
        "booleanKey": true
    };

    callback(null, authResponse);
};
```
These variables are not getting passed to my Lambda function:

```
        "stringKey": "stringval"
        "numberKey": 123
        "booleanKey": true
```

I think this is due to this information not being present in the Body Mapping Templates generated by Serverless:

```
  #set( $body = $input.json("$") )

    
  #define( $loop )
    {
    #foreach($key in $map.keySet())
        #set( $k = $util.escapeJavaScript($key) )
        #set( $v = $util.escapeJavaScript($map.get($key)).replaceAll("\\'", "'") )
        "$k":
          "$v"
          #if( $foreach.hasNext ) , #end
    #end
    }
  #end

  {
    "body": $body,
    "method": "$context.httpMethod",
    "principalId": "$context.authorizer.principalId",
    "stage": "$context.stage",

    "cognitoPoolClaims" : {
       
       "sub": "$context.authorizer.claims.sub"
    },

    #set( $map = $input.params().header )
    "headers": $loop,

    #set( $map = $input.params().querystring )
    "query": $loop,

    #set( $map = $input.params().path )
    "path": $loop,

    #set( $map = $context.identity )
    "identity": $loop,

    #set( $map = $stageVariables )
    "stageVariables": $loop
  }
```

From the [docs](http://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html#api-gateway-custom-authorizer-output):

> You can access the stringKey, numberKey, or booleanKey value (for example, "value", "1", or "true") of the context map in a mapping template by calling $context.authorizer.stringKey, $context.authorizer.numberKey, or $context.authorizer.booleanKey, respectively. The returned values are all stringified. Notice that you cannot set a JSON object or array as a valid value of any key in the context map.

Adding something like this to the template defined in `lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js` can bring the variables in to the function:

```
    #set( $map = $context.authorizer )
    "enhancedAuthContext": $loop,
```
