### ISSUE TITLE
AWS::Lambda::Method Supports

### ISSUE THREAD

**Issue by rossbu** [serverless/serverless#4380]
## Description
It seems serverless cli does NOT support Method definition in resource/resources section but only in functions block

* What went wrong?
Can not remove functions block from yml file
* What did you expect should have happened?
use AWS::Lambda::Method to replace functions block
* What was the config you used?
Removed below functions def:
```
functions:
  getToken:
    handler: index.getToken
    name: getToken
    memorySize: 256
```

Use new Method instead
```
resource
 Resources:
   getToken: 
      Type: "AWS::Lambda::Function"
      Properties: 
        Handler: "index.getToken"
        MemorySize: 256
        Role: 
          Fn::GetAtt: 
            - "LambdaExecutionRole"
            - "Arn"
        Code: 
          S3Bucket: "yourbucketofDeployment"
          S3Key: "service1.zip"
        Runtime: ${self:provider.runtime}
        Timeout: 25
        TracingConfig:
          Mode: "Active"
```
* What stacktrace or error message from your provider did you see?
  Cannot read property 'Properties' of undefined  -- sls deploy --alias dev

* env
     OS:                     win32
     Node Version:           8.5.0
     Serverless Version:     1.22.0
