### ISSUE TITLE
${opt:stage, 'dev'} in provider.stage variable causing error when trying to deploy. 

### ISSUE THREAD

**Issue by jollifft** [serverless/serverless#4396]
# This is a Bug Report

## Description
I am trying to dynamically set the provider.stage variable, with a default value of dev. I am following the example found here https://serverless.com/framework/docs/providers/aws/guide/variables#current-variable-sources 
When trying to deploy, I get a serverless error saying the service name is not valid. 

For bug reports:
* What went wrong?
   See description
* What did you expect should have happened?
   I expected the service to deploy with the stage defaulting to 'dev'
* What was the config you used?
   serverless.yml
```
service: stage-test-service

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  environment:
      STAGE: ${self:provider.stage}

functions:
  hello:
    handler: handler.hello
```
* What stacktrace or error message from your provider did you see?
```
kii-ict1586:stagetest tylerjolliff$ sls deploy
Serverless: Packaging service...

  Serverless Error ---------------------------------------

  The stack service name "stage-test-service-${opt:stage, 'dev'}" is not valid. A service name should only contain alphanumeric (case sensitive) and hyphens. It should start with an alphabetic character and shouldn't exceed 128 characters.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.10.1
     Serverless Version:     1.18.0
```

Similar or dependent issues:
* #3293

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
