### ISSUE TITLE
External files packaging

### ISSUE THREAD

**Issue by goldytech** [serverless/serverless#4408]
Hi,

My folder structure for the serverless app is

```
-src
-schema
    ce.json
    schema-reader.js
-serverless.yml

```
I want to include all the *.json files under the schema folder into the package zip file, as my function read this file. The code for reading this json file is in schema-reader.js file , where i use node fs module api to `readFile('./ce.json)`

I've setup my serverless.yml "package" attribute as follows
```
package:
  include:
    - src/schema/**
  exclude:
#    - exclude-me.js
    - '!src/schema/**'

```
But the zip file that is generated by `sls deploy` command doesn't contains the schema folder or the json files in it

Can you please advise where I'm going wrong ?
