### ISSUE TITLE
Serverless Deploy Error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by cmwhited** [serverless/serverless#4424]
# This is a (Bug Report / Feature Proposal)

## Description

Serverless deploy error: Path must be a string. Received undefined.

## Additional Data
- OS: Mac OS X
- Serverless version: 1.23.0
- Webpack version: 1.14.0
- Serverless webpack version: ^1.0.0-rc.3
- Typescript version: ^2.2.0

## Stack Tract

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1383:5)
    at functionNames.forEach.name (/Users/cmwhited/TransitPros/projects/cloud-api/node_modules/serverless-webpack/lib/cleanup.js:27:28)
    at Array.forEach (<anonymous>)
    at fse.copy (/Users/cmwhited/TransitPros/projects/cloud-api/node_modules/serverless-webpack/lib/cleanup.js:23:31)
    at doneOne (/Users/cmwhited/TransitPros/projects/cloud-api/node_modules/serverless-webpack/node_modules/fs-extra/lib/copy/ncp.js:237:40)
    at /Users/cmwhited/TransitPros/projects/cloud-api/node_modules/serverless-webpack/node_modules/fs-extra/lib/copy/ncp.js:122:11
    at /Users/cmwhited/TransitPros/projects/cloud-api/node_modules/serverless-webpack/node_modules/graceful-fs/polyfills.js:239:18
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by horike37** [comment]
Thanks @cmwhited for reporting :+1: 
Could you share the serverless.yml you are using so that we can try to reproduce it?

**Comment by HyperBrain** [comment]
@cmwhited , @horike37 I see that this happened with `serverless-webpack` while checking for the function handlers (`at functionNames.forEach.name`).
Can you post the function definitions from your `serverless.yml`? It is important that the handlers specified in there point to the correct location of the actual handler files (with a relative path in case the handlers are located in subfolders). A sample would be: `lib/src/handlers/myhandler.handle`

**Comment by cmwhited** [comment]
Hey guys. Sorry for the late response. Been a busy couple days. 
```
service: vendor-locations

package:
  individually: true

custom:
  database: ${file(../config/database.yml):database.${opt:stage}}
  encryption: ${file(../config/encryption.yml):encryption.${opt:stage}}
  site: ${file(../config/site.yml):site.${opt:stage}}
  s3: ${file(../config/s3.yml):s3.${opt:stage}}
  google: ${file(../config/google.yml):google.${opt:stage}}

provider:
  name: aws
  runtime: nodejs8.4.0
  stage: dev
  region: us-east-1
  profile: default
  memorySize: 1024
  environment:
    DB_HOSTNAME: ${self:custom.database.hostname}
    DB_PORT: ${self:custom.database.port}
    DB_DATABASE: ${self:custom.database.database}
    DB_USERNAME: ${self:custom.database.username}
    DB_PASSWORD: ${self:custom.database.password}
    DOMAIN: ${self:custom.site.domain}
    ENCRYPTION_KEY: ${self:custom.encryption.secret_key}
    S3_ACCESS_KEY: ${self:custom.s3.access_key}
    S3_SECRET_KEY: ${self:custom.s3.secret_access_key}
    S3_REGION: ${self:custom.s3.region}
    S3_BUCKET_NAME: ${self:custom.s3.bucket_name}
    SERVERLESS_STAGE: ${opt:stage}
    GOOGLE_CLIENT: ${self:custom.google.client}
    GOOGLE_KEY: ${self:custom.google.key}
  cfLogs: true

plugins:
  - serverless-webpack

resources:
  Resources:
    pathmapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        BasePath: ${self:service}
        DomainName: ${self:custom.site.basepath}
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: ${opt:stage}

functions:
  list:
    name: ${opt:stage}-vendor-locations-list
    description: List of Vendory company records with a location within a given radius
    handler: list.main
    timeout: 30
    events:
      - http:
          path: ''
          method: get
          cors: true
```
There is my serverless.yml. 
I will try updating my `serverless-webpack` and `webpack` versions
