### ISSUE TITLE
Serverless deploy --stage wrong value

### ISSUE THREAD

**Issue by marckaraujo** [serverless/serverless#4430]
# This is a Bug Report

## Description

When I deploy with `serverless deploy --stage dev`

I get the following error:

```
Serverless Error ---------------------------------------
 
  An error occurred: RoomDynamoDbTable - Room already exists in stack arn:aws:cloudformation:us-east-2:xxxx:stack/proak-api-prod/xxxxx.
```

Look that the stack that is trying to deploy is `proak-api-prod`, it should be dev.

* ***Stack Trace***:
```
Serverless: Optimize: starting engines
Serverless: Optimize: proak-api-dev-userPerfil
Serverless: Optimize: proak-api-dev-userSession
Serverless: Optimize: proak-api-dev-userBeta
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: RoomDynamoDbTable - Room already exists in stack arn:aws:cloudformation:us-east-2:xxxxx:stack/proak-api-prod/xxxxxx.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           7.4.0
     Serverless Version:     1.23.0
```

**Comment by RafalWilinski** [comment]
Hi @marckaraujo, can you please share your `serverless.yml` file?

**Comment by marckaraujo** [comment]
Cant provide you the fullFile but I think that the most important is:

```
provider:
   name: aws
   runtime: nodejs6.10
   stage: ${opt:stage, self:custom.defaultStage}
   region: us-east-2 # Overwrite the default region used. Default is us-east-1
   profile: ${self:custom.profiles.${self:provider.stage}}
   apiKeys:
     - ${self:provider.stage}-api-key
   usagePlan:
     quota:
       limit: 5000
       offset: 0
       period: DAY
     throttle:
       burstLimit: 200
       rateLimit: 100
   environment:
     STAGE: ${self:provider.stage}
   iamRoleStatements:
     - Effect: Allow
       Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
       Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
     - Effect: Allow
       Action:
         - ec2:CreateNetworkInterface
         - ec2:DescribeNetworkInterfaces
         - ec2:DeleteNetworkInterface
       Resource: '*'
     - Effect: Allow
       Action:
         - kms:Decrypt
         - kms:Encrypt
         - kms:DescribeKey
         - kms:GetKeyPolicy
       Resource: "arn:aws:kms:${self:provider.region}:*:*"

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-delete-loggroups
#  - serverless-dynamodb-autoscaling

custom:
  dynamodbProvisions:
    dev: 1
    prod: 5
  streamAccounts:
    dev: xxxx
    prod: xxxx
  enableScheduleEvents:
    dev: false
    prod: true
  defaultStage: dev
  profiles:
    dev: devProfile
    prod: prodProfile
  serverless-offline:
    babelOptions:
      presets: ["es2015"]


package:
  individually: true
```

**Comment by marckaraujo** [comment]
I had to remove the table from PROD, thats a really big issue for me..

**Comment by HyperBrain** [comment]
@marckaraujo How do you define the DynamoDB table - and more importantly, how do you exactly reference it, or do you export the ARN or table name of the Room table from a stack?

If you export (output variable export) any variable, its name has to be globally unique. E.g. if you exported the table name as "Room" it will clash, as there is already an existing export with that name.
For exports it is important, that you include the stackname in the export.
Sample:
```
        ...
        Export:
          'Fn::Join':
            - '-'
            -
              - Ref: 'AWS::StackName'   <--- IMPORTANT
              - ...
```

**Comment by marckaraujo** [comment]
Well, atm I dont use export at all.
Here is the table that was causing the error:

```
RoomDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: status
            AttributeType: S
          -
            AttributeName: game
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
          WriteCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          -
            IndexName: status-index
            KeySchema:
              -
                AttributeName: status
                KeyType: HASH
              -
                AttributeName: game
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
              WriteCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
        TableName: 'Room'
```

Should I have the TableName with a stage tag?

**Comment by HyperBrain** [comment]
Indeed. You try to create the same table twice (because you use a hardcoded table name).

If you drop the `TableName` property completely, CF will create one for you that includes the stackname, the logical id and a random appendix.

You have to set the tablename then through the environment to make it available in your functions:
```yaml
# serverless.yml
provider:
  environment:
    ROOM_TABLE:
      Ref: RoomTable

resources:
  Resources:
    RoomTable:
      Type: 'AWS::DynamoDB::Table'
      ... # Without explicit TableName property!
```

This will automatically create a table `<stackname>-RoomTable-<Random Hash>` which is guaranteed to be uniquely named.

If you want to have the environment variable be resolved for `sls invoke local` you should add the `serverless-export-env` plugin.
