### ISSUE TITLE
sls run fail with "socket hang up"

### ISSUE THREAD

**Issue by gulbinas** [serverless/serverless#4436]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

```sls run``` failed with ```socket hang up```

* What did you expect should have happened?

success

* What was the config you used?

```
frameworkVersion: ">=v1.12"


custom:
  profile: AAAAA
  region: eu-west-1
  stage: dev
  pkgPyFuncs: # plugin configuration
    buildDir: _build
    requirementsFile: 'requirements.txt'
    globalIncludes:
      - ./lib
    cleanup: true
    useDocker: true
    dockerImage: lambci/lambda:build-python2.7



provider:
  name: aws
  runtime: python2.7
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  role: AAAAA
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: arn:aws:sns:${opt:region, self:provider.region}:*:*
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:${opt:region, self:provider.region}:*:*
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: AAAAA
  environment:
    
    LOG_LEVEL: "DEBUG"
   

package:
  individually: true

functions:
  AAAA: ${file(src/AAAA/config.yml):AAAA}
  AAAA: ${file(src/AAAA/config.yml):AAAA}

plugins:
  - serverless-package-python-functions

```

* What stacktrace or error message from your provider did you see?

```
[AAAAA@AAAAA-6 AAAA (develop *$)]$ SLS_DEBUG=* sls run
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke run
 Serverless     Emulator initializing...
 Serverless     Emulator listening on: http://localhost:4002
 Serverless     Functions loading...

  Fetch Error --------------------------------------------

  request to http://localhost:4002/v0/emulator/api/functions/deploy failed, reason: socket hang up

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

FetchError: request to http://localhost:4002/v0/emulator/api/functions/deploy failed, reason: socket hang up
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
From previous event:
    at deployFunctionsToLocalEmulator (/usr/local/lib/node_modules/serverless/lib/plugins/run/utils/deployFunctionsToLocalEmulator.js:33:20)
    at Socket.cp.stdout.on.stdout (/usr/local/lib/node_modules/serverless/lib/plugins/run/utils/manageLocalEmulator.js:29:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:

```
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.6.0
     Serverless Version:     1.23.0
```
