### ISSUE TITLE
Deploy on another stage fails

### ISSUE THREAD

**Issue by gulbinas** [serverless/serverless#4456]
# This is a Bug Report

## Description

* What went wrong?

Deployment to ```prod``` stage failed

* What did you expect should have happened?

Deployment to ```prod``` stage

* What was the config you used?

```
service: AAAAAA


frameworkVersion: ">=v1.12"


custom:
  profile: AAAAAA
  region: eu-west-1
  stage: dev
  pkgPyFuncs: # plugin configuration
    buildDir: _build
    requirementsFile: 'requirements.txt'
    # globalRequirements:
    #   - ./requirements.txt
    globalIncludes:
      - ./lib
    #cleanup: true
    #useDocker: false
    useDocker: true
    dockerImage: lambci/lambda:build-python2.7



provider:
  name: aws
  runtime: python2.7
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  role: arn:aws:iam::AAAAAA:role/AAAAAA-dev-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: arn:aws:sns:${opt:region, self:provider.region}:*:*
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:${opt:region, self:provider.region}:*:*
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:*
  environment:
    AAAAAA: "AAAAAA"

package:
  individually: true

functions:
  AAAAAA: ${file(src/slackAPI/config.yml):AAAAAA}
plugins:
  - serverless-package-python-functions

```

* What stacktrace or error message from your provider did you see?

```
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: SNSTopicAAAAAAQueue - SlackAAAAAAAQueue already exists in stack arn:aws:cloudformation:eu-west-1:645465924714:stack/BBBBBB-dev/9b7ef6c0-90e1-11e7-bbd1-50a686343cd2.
```

Similar or dependent issues:
* https://github.com/ubaniabalogun/serverless-package-python-functions/issues/27

## Additional Data

Deploy on another stage fails after successful deployment to previous one.

Looks like it deploys to dev stack: ```arn:aws:cloudformation:eu-west-1:645465924714:stack/BBBBBB-dev/9b7ef6c0-90e1-11e7-bbd1-50a686343cd2````

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: MacOS 15.6.0
* ***Stack Trace***:

```
ServerlessError: An error occurred: SNSTopicAAAAAAAAQueue - AAAAAAAAQueue already exists in stack arn:aws:cloudformation:eu-west-1:645465924714:stack/BBBBBB-dev/9b7ef6c0-90e1-11e7-bbd1-50a686343cd2.
    at provider.request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:114:33)
From previous event:
    at AwsDeploy.monitorStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:30)
From previous event:
    at AwsDeploy.update (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:88:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:105:12)
From previous event:
    at AwsDeploy.updateStack (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:99:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:125:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:121:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:378:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

* ***Provider Error messages***:

**Comment by gulbinas** [comment]
Looks like despite fact that stage changes, the SNS queue name is made the same.

Somewhat workaround

```
CreateBox:
  handler: handler.CreateBox
  timeout: 30
  events:
    - sns:
      topicName: CreateBoxQueue2-${opt:stage}

```

What is correct way to do it in sls framework?

**Comment by RafalWilinski** [comment]
`Somewhat workaround: to provide stage name in topicName.` - Yes, this is the recommended way.

My personal way is to create some "computed" variables in `custom` section (single source of truth) and then refer these in `provider.environment` and `resources` sections. 

Let me show you what I mean by that:
```yml
custom:
  topicName: ${self:service}-CreateBoxQueue-${opt:stage, self:provider.stage}    # Can be refered using ${self:custom.topicName}

provider:
  environment:
    - TOPIC_NAME: ${self:custom.topicName}.   # Pass "computed" variable as environment variable to code

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        Name: ${self:custom.topicName}
```

You can also extract these to separate file if your variables are sensitive and refer them using `${file(./secrets.yml):custom.dev}. 

Hope that helps!

**Comment by RafalWilinski** [comment]
`Somewhat workaround: to provide stage name in topicName.` - Yes, this is the recommended way.

My personal way is to create some "computed" variables in `custom` section (single source of truth) and then refer these in `provider.environment` and `resources` sections. 

Let me show you what I mean by that:
```yml
custom:
  topicName: ${self:service}-CreateBoxQueue-${opt:stage, self:provider.stage}    # Can be refered using ${self:custom.topicName}

provider:
  environment:
    - TOPIC_NAME: ${self:custom.topicName}.   # Pass "computed" variable as environment variable to code

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        Name: ${self:custom.topicName}
```

You can also extract these to separate file if your variables are sensitive and refer them using `${file(./secrets.yml):custom.dev}. 

Hope that helps!

**Comment by RafalWilinski** [comment]
`Somewhat workaround: to provide stage name in topicName.` - Yes, this is the recommended way.

My personal way is to create some "computed" variables in `custom` section (single source of truth) and then refer these in `provider.environment` and `resources` sections. 

Let me show you what I mean by that:
```yml
custom:
  topicName: ${self:service}-CreateBoxQueue-${opt:stage, self:provider.stage}    # Can be refered using ${self:custom.topicName}

provider:
  environment:
    - TOPIC_NAME: ${self:custom.topicName}.   # Pass "computed" variable as environment variable to code

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        Name: ${self:custom.topicName}
```

You can also extract these to separate file if your variables are sensitive and refer them using `${file(./secrets.yml):custom.dev}. 

Hope that helps!

**Comment by RafalWilinski** [comment]
`Somewhat workaround: to provide stage name in topicName.` - Yes, this is the recommended way.

My personal way is to create some "computed" variables in `custom` section (single source of truth) and then refer these in `provider.environment` and `resources` sections. 

Let me show you what I mean by that:
```yml
custom:
  topicName: ${self:service}-CreateBoxQueue-${opt:stage, self:provider.stage}    # Can be refered using ${self:custom.topicName}

provider:
  environment:
    - TOPIC_NAME: ${self:custom.topicName}.   # Pass "computed" variable as environment variable to code

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        Name: ${self:custom.topicName}
```

You can also extract these to separate file if your variables are sensitive and refer them using `${file(./secrets.yml):custom.dev}. 

Hope that helps!

**Comment by RafalWilinski** [comment]
`Somewhat workaround: to provide stage name in topicName.` - Yes, this is the recommended way.

My personal way is to create some "computed" variables in `custom` section (single source of truth) and then refer these in `provider.environment` and `resources` sections. 

Let me show you what I mean by that:
```yml
custom:
  topicName: ${self:service}-CreateBoxQueue-${opt:stage, self:provider.stage}    # Can be refered using ${self:custom.topicName}

provider:
  environment:
    - TOPIC_NAME: ${self:custom.topicName}.   # Pass "computed" variable as environment variable to code

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        Name: ${self:custom.topicName}
```

You can also extract these to separate file if your variables are sensitive and refer them using `${file(./secrets.yml):custom.dev}. 

Hope that helps!
