### ISSUE TITLE
[feature request ] - enable/disable option for plugin

### ISSUE THREAD

**Issue by ozbillwang** [serverless/serverless#4469]
# This is a Feature Proposal

## Description

When I manage plugin in serverless framework, it is hard to manage the plugin with different stages. 

Could we have an enable/disable option for all plugins (it should be a core service in Serverless framework) that I can easily define manage which plugin will be used. For example,

```
custom:
  dev:
    offline_plugin: true
    stage_variables_plugin: true
  staging:
    offline_plugin: false
    stage_variables_plugin: true

plugins:
  - serverless-plugin-stage-variables
     enabled: ${self:custom.dev.stage_variables_plugin}
  - serverless-offline
     enable:  ${self:custom.dev.offline_plugin}
```

**Comment by HyperBrain** [comment]
Hi @ozbillwang ,

what is the exact problem you want to solve with such a feature?

In general, plugins are not meant to be disabled within different stages of a project. Plugins hook into the serverless process and only execute when they are meant to or they add custom commands. E.g. the offline plugin you mentioned only adds the offline command, but does not do anything else. There is no reason to remove it for a specific stage, as that has absolutely no impact on the builds or deployments.

Having a manual configuration here will imo introduce additional failures and inconsistencies that would increase the incoming issues here because of misconfigurations. Additionally, you do not know if a specific plugin hooks somewhere, as it is any plugin's own responsibility how it works. Another example would be the alias plugin. If you disable it for a stage, it will destroy your deployment. So I think opening this door will also open a big can of worms.

@serverless/framework-maintainers Any opinion on this?

**Comment by ozbillwang** [comment]
@HyperBrain 

Thanks for the details, I'd like to have a if-else condition for the plugins or when condition to control which plugin should be used in different stage.

Second, in some stage, I can reduce the deploy time, if some of plugins are not required.

**Comment by horike37** [comment]
Thanks @ozbillwang for the suggestion :smile: 

>I'd like to have a if-else condition for the plugins or when condition to control which plugin should be used in different stage.
>Second, in some stage, I can reduce the deploy time, if some of plugins are not required.

I just understood what's your purpose on this :+1: 
IMO, it would be good to resolve it with [variables system](https://serverless.com/framework/docs/providers/aws/guide/variables/) rather than introducing such a new functionality.

For instance, how about setting up the following serverless.yml?
By this, you may switch using plugins corresponding to each stage.

```yaml
provider:
  stage: development
custom:
  stage:  ${opt:stage, self:provider.stage}
  plugins:
    development:
      - serverless-webpack
      - serverless-step-functions
      - serverless-s3-remover
    production:
      - serverless-webpack
      - serverless-step-functions
    default:
      - serverless-webpack

plugins: ${self:custom.plugins.${self:custom.stage}, self:custom.plugins.default}
```
