### ISSUE TITLE
Allow explicitly specifying `serverless.yml` file in CLI options or env var

### ISSUE THREAD

**Issue by ccll** [serverless/serverless#4473]
# This is a (Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I'd like to make different deployments in dev/stage/prod environments, and I need to include or exclude certain config blocks conditionally in `serverless.yml`, which is not supported by now.

Instead of implementing conditional logic into `serverless.yml`, a simpler way is to allow the CLI accepts an explicit '-f' option, or an env var, then we could put different configs in `serverless.dev.yml` and `serverless.prod.yml`, etc.

Or even better, the main `serverless.yml` file is always taken and user could specify **extra** config files to be merged with the main config, like how `docker-compose -f` works.

* If there is additional config how would it look

Similar or dependent issues:
None

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
Hi @ccll , thanks for the question/idea.

Having dynamic yaml imports based on the stage should be possible already by using the variable system.

```yaml
custom:
  stage: ${opt:stage, self:provider.stage}
  config: ${file(serverless.${custom:stage}.yml):config}
resources:
  Resources: ${file(serverless.${custom:stage}.yml):Resources}
  # This means to fetch the Resources property from the external yaml file
```

You also could retrieve any value from the environment if you want to make the imports dependent on these with `${env:xxxxxx}` as variable reference.
