### ISSUE TITLE
Stuck at Checking Stack Removal Progress

### ISSUE THREAD

**Issue by callmekatootie** [serverless/serverless#4477]
# This is a Bug Report

## Description
I deployed a sample app to AWS using [this article](https://hackernoon.com/a-crash-course-on-serverless-with-node-js-632b37d58b44). 2 days later I decided to remove the app and executed:

`$ serverless remove`

* What went wrong?
The console had the following output:

```
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
.....................
```
and even after waiting 10 minutes, nothing happened after that.

* What did you expect should have happened?
I expected the command to complete execution successfully.

* What was the config you used?

```
service: my-service
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/get
          method: get
```
* What stacktrace or error message from your provider did you see?
No errors. The command execution was stuck.

## Additional Data

* ***Serverless Framework Version you're using***:
1.24.1
* ***Operating System***:
Ubuntu 16.04
