### ISSUE TITLE
${stageVariables.xxxxxx} for lambda function name of serverless event http

### ISSUE THREAD

**Issue by markjayniel** [serverless/serverless#4481]
# This is a (Bug Report / Feature Proposal)
Not sure if this is a feature proposal or maybe I just don't know if it even exists

## Description
We are new to serverless arch and we are trying to setup serverless in our AWS environment for dry run testing. We can't find a way how to setup ${stageVariables.<string|variable|function|xxxx>} to event http. 

When I setup the **lambda function name** like below: 
`functions:
  root-lambda:
    handler: index.handler
    name: "${stageVariables.function}"
    events:
      - http:
         path: /api/v1
         method: get
         integration: lambda
         request:
              passThrough: WHEN_NO_MATCH
}`

I get an error:
`  The CloudFormation template is invalid: Template error: instance of Fn::Sub references invalid resource attribute stageVariables.function`

If I add the "!" for lambda function name, it gives different error:
`functions:
  root-lambda:
    handler: index.handler
    name: "${!stageVariables.function}"
    events:
      - http:
         path: /api/v1
         method: get
         integration: lambda
         request:
              passThrough: WHEN_NO_MATCH
}`

I get this error:
`  An error occurred: RootDashlambdaLogGroup - 1 validation error detected: Value '/aws/lambda/${!stageVariables.function}' at 'logGroupNamePrefix' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+.
`

`serverless -v
1.24.1`

**Comment by RafalWilinski** [comment]
Thanks for reporting this bug @markjayniel! 💯 

Can you please share whole `serverless.yml` file? It might help us debug this problem.

**Comment by markjayniel** [comment]
hi @RafalWilinski,

sorry for late response. Here's my serverless.yml
```
service: lambda-api-for-the-winners
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" #nothing should conflict with cloudformation foo with this setup
package:
  include:
    - ../whatever/**
  export:
    - ../exportwhatever/**
functions:
  root-lambda:
    handler: index.handler
    name: ${stageVariables.alias_func} 
    events:
         - http:
               '${{file(v1/basics.yml)}}'
plugins:
  - serverless-plugin-bespoken
  - serverless-aws-documentation
```
Below is the basics.yml
```
path: v1/basics
method: get
integration: lambda
region: us-east-2
request:
  passThrough: WHEN_NO_TEMPLATES
response:
  headers:
       Access-Control-Allow-Origin: '*'
  template: $input.json('$')	
documentation:
   summary: "function summary test"
   description: "function summary description"
   methodResponses:
     -
      statusCode: "200"
```

We are following this setup: https://remysharp.com/2016/12/02/aws-lambda-gateway-workflow and the function name variables(${stageVariables.alias_func}) change base on how the apps is used :)
