### ISSUE TITLE
Cloudformation custom resources' functions are not run on subsequent deploys

### ISSUE THREAD

**Issue by tommedema** [serverless/serverless#4483]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I created a cloudformation custom resource and set its handler to a serverless function (see steps to reproduce below). This is surprisingly easy to setup, and seems to work well on first deploy. I can confirm that the custom resource causes the lambda to run and its data property is received through cloudformation logs. Problem is that if I now change the function (e.g. have it return something else), and redeploy (`sls deploy`), the custom resource is not triggered again, and the reference to the custom resource value (`Fn::GetAtt: [MyCustomResource, test]`) remains the old value and not the updated value.  There are no more logs in cloudformation, i.e. the function never run.

* What did you expect should have happened?
On subsequent deploys, I expect the function to be run again as it was updated and therefore the custom resource to now expose updated attributes as returned by the updated function.

* What was the config you used?

_serverless.yml_
```
service: simple-cr

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-2'}
  
custom:
  customResourceValue:
    Fn::GetAtt: [MyCustomResource, test]
      
functions:
  customResource:
    handler: custom.handler
  
resources:
  Resources:
          
    MyCustomResource:
      Type: Custom::MyCustomResource
      Properties:
        ServiceToken:
          Fn::GetAtt: [CustomResourceLambdaFunction, Arn]
```

_custom.js_
```
const response = require('cfn-response');
 
exports.handler = function(event, context) {
  console.log('sending hello as custom resource lambda function handler response');
  return response.send(event, context, response.SUCCESS, {
    test: 'hello'
  });
};
```

* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #12345

## Steps to reproduce

1. create above 2 files `serverless.yml` and `custom.js`
2. run `npm install --save cfn-response`
3. run `sls deploy`
4. confirm that cloudwatch has log entries for the lambda function, i.e. the custom resource works
5. change the output of the function from `test: 'hello'` to something else, like `test: 'goodbye'`
6. run `sls deploy`
7. notice that there are no cloudwatch entries and that the custom value `Fn::GetAtt: [MyCustomResource, test]` still refers to the old value returned by the previous function

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: OSX
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by tommedema** [comment]
Note that if I were to add a random property to the custom resource, it does update:

```
MyCustomResource:
      Type: Custom::MyCustomResource
      Properties:
        SomeRandomProperty: "changeThisOnEveryDeploy..."
        ServiceToken:
          Fn::GetAtt: [CustomResourceLambdaFunction, Arn]
```

But of course that's not ideal.

**Comment by dougmoscrop** [comment]
What happens when you add a DependsOn ?

**Comment by tommedema** [comment]
@dougmoscrop that did not change the behavior. I guess that makes sense since it also has an indirect dependency due to the `Fn::GetAtt` call.

**Comment by dougmoscrop** [comment]
Yeah, I was pretty sure it would not. I think this bug/behavior is unrelated to Serverless though - like you could have the same situation happen using pure CloudFormation?

**Comment by dougmoscrop** [comment]
One solution would be to pass the function code hash as a parameter so when the package changes it triggers a rerun of the fn.

**Comment by tommedema** [comment]
@dougmoscrop that's not a solution because the code can remain the same while the output changes, e.g. when you call an API within the lambda. This is very likely, e.g. in the case of when you check if a SSL certificate expired or not.

**Comment by dougmoscrop** [comment]
Well that seems like another input parameter to the resource.  It's a solution for the issue describes here, not your overall goal - which I think has other problems anyway, e.g. you have to happen to run an sls deploy to renew your cert.

**Comment by simlu** [comment]
Also very interested in a fix for this...

**Comment by simlu** [comment]
Also very interested in a fix for this... Any update on this @tommedema?

**Comment by tommedema** [comment]
@simlu not really.. I worked around it with a somewhat ugly hack, forcing it to recreate on each deploy using a unique parameter UUID:

serverless.yml
```
  Resources:
    
    # custom resource to retrieve SSL certificates
    CertificateResource:
      Condition: ShouldRequestCertificate
      Type: Custom::CertificateResource
      Properties:
        # a UUID forces a refetch from lambda on eacha deploy
        UUID: ${{file(./scripts/uuid.js)}}
        ...
        ServiceToken:
          Fn::GetAtt: [RequestCertificateLambdaFunction, Arn]
```

uuid.js
```
module.exports = () => require('uuid/v4')()
```

**Comment by tommedema** [comment]
I will close this since it is assumed that this is apparently cloudformation behavior and  not specific to serverless. It is somewhat surprising though.

**Comment by simlu** [comment]
@tommedema Show we file a bug report on AWS forums?

**Comment by tommedema** [comment]
@simlu we could, but I am afraid this might be considered as a "feature" by them.

I believe that Cloudformation creates an internal state, and then if the resource is already created once, it won't be created again unless you previously deleted it. If you then change the parameters of the resource, it will be run again with the `Update` `event.RequestType`.

But this does not make sense for custom resources that need to perform a certain check on each deploy. In that case perhaps the most pragmatic way would be to use a unique ID in the parameters?

One behavior I do not understand is that currently cloudformation seems to send a `Delete` request type after creating the resource, as if it wants to clean it up again. The challenge then becomes to distinguish between a "cleanup" delete and a "permanent" delete (i.e. one where the resource is removed from the stack or the stack itself is deleted).

**Comment by dougmoscrop** [comment]
CloudFormation is for provisioning, not orchestration. I could expect the
resource to rerun when the code changes. But not on deploy.

**Comment by tommedema** [comment]
@dougmoscrop that makes sense. Since terraform is also for provisioning, how would you do orchestration in a serverless setup?

**Comment by dougmoscrop** [comment]
Well I think you have to decide what exactly it is you want to achieve - this isn't the best forum for the conversation, but I think the gist of it is you want to renew a resource (like a certificate) when it expires - but you're doing this check on deploy. What happens if you happen not to deploy the code before the cert expires? etc. -- consider, rather some kind of Lambda that runs very occasionally (e.g. once a month) that checks and does the renewal. Or of course for certs specifically I think AWS does DNS based renewal now.

**Comment by guss77** [comment]
@tommedema - I have the same issue with delete after update and would be very interested about this "physical resource ID" that you mentioned. 

Did you manage to get CloudFormation to not "clean up the old version of the custom resource", and if so - how?

**Comment by sfi-dmather** [comment]
This was the only post that I found that pointed me in the right direction on a cloud formation update to a custom resource.  The way I finally got my custom resource to update was to reference a parameter in a property under the custom resource.  So where above he changes SomeRandomProperty: "changeThisOnEveryDeploy..." each time, I set that to SomeRandomProperty: !Ref myParam.  This causes the property to change when you edit the field on Parameters section when you run the update, causing it to finally pass the update event to the custom resource. Thank you

**Comment by danketrotzdem** [comment]
You can set `SomeRandomProperty: ${env:RANDOM} ` whereas set the env var first export RANDOM=$(date +%s) first. Random will then be the current timestamp. Not nice. But there is no fix currently, right?

**Comment by dougmoscrop** [comment]
Ideally you could make it a hash of the function source code. Since CFn will rerrun when other things, like Parameters, change - I think the only thing missing is on code change.  You could also maybe use explicit function versions and point the resource to that which should change on every version (I'm presuming $LATEST is what's confusing - the ARN doesn't change)

**Comment by whitfin** [comment]
Just to add a little more to this as it's still necessary in 2025 🙃:

```yml
MyCustomResource:
  Type: AWS::CloudFormation::CustomResource
  Properties:
    ServiceToken: !GetAtt MyCustomResourceLambda.Arn
    ForceUpdate: ${sls:instanceId}
```

There is a builtin `instanceId` you can use which should be unique per-deployment, forcing the redeploy without having to do anything fancy.
