### ISSUE TITLE
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [Tenant_Group] in the Resources block of the template

### ISSUE THREAD

**Issue by balakrishna222111** [serverless/serverless#4504]
1. i want a lambda(verify-tenant)function that should be come in "trigger-->postconfirmation" which is in user cognito poool 
but it throws an error like "The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [Tenant_Group] in the Resources block of the template"
-------------------------------------------------------------------------------------------------------------------
```yml
service: tenant-dev

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1
  authorizer: CognitoAuthorizer
  apiGateway: TenantAPI
  userPool: Tenant_Group

  environment:
    COGNITO_USERPOOLID: ap-southeast-1_faQUIpTCq
    COGNITO_REGION: ap-southeast-1
    GROUP_NAME: TenantGroup
    COGNITO_GROUP_ROLE: arn:aws:iam::526821537466:role/Cognito_TenantIDPoolAuth_Role

custom:
  region: ${self:provider.region}
  authorizer: ${self:provider.authorizer}
  apiGateway: ${self:provider.apiGateway}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  userPool: ${self:provider.userPool}


functions:
    verifyTenant:
    Type: 'AWS::Lambda::Function'
    timeout: 10
    handler: functions/VerifyTenant/verifyTenant.handler
    name: ${self:custom.prefix}-verifyTenant
    events:
    - cognitoUserPool:
        pool: ${self:custom.userPool}
        trigger: PostConfirmation


resources:
  Resources:
    UserPool:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName:
          Ref: ${self:custom.userPool}
```
