### ISSUE TITLE
"Fallback/Overwrite" variable technique doesn't recurse into objects

### ISSUE THREAD

**Issue by dsole** [serverless/serverless#4509]
# This is a Bug Report

## Description

When the serverless configuration is resolving a variable that is the overwrite/default value technique, when resolving any of the options that refer to an object, it does not resolve the variables within that object.

So given a configuration:
 ```
provider:
  name: aws
  stage: dev

custom:
  test: ${env:I_DONT_EXIST, self:custom.nested}
  nested:
    child: ${self:provider.stage}
```
In my plugin I expect `serverless.service.custom.test` to be
```
{
  child: "dev"
}
```
But what I get is 
```
{
  child: "${self:provider.stage}"
}
```

Similar or dependent issues:
 * #3604

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Windows 10
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by dsole** [comment]
in `Variables.populateProperty()` when it calls `this.getVariablesFromSource()` it follows it up with a check for whether the result is an object, and if so then it populates that object

**In `Variables.populateProperty()`**
```javascript
singleValueToPopulate = this.getValueFromSource(variableString)
  .then(valueToPopulate => {
    if (typeof valueToPopulate === 'object') {
      return this.populateObject(valueToPopulate);
    }
    return valueToPopulate;
  });
```

When it resolves the options within an overwrite syntax, it doesnt do that check.

**In `Variables.overwrite()`**
```javascript
const allValuesFromSource = variableStringsArray
      .map(variableString => this.getValueFromSource(variableString));
```

I could resolve this bug easily by just adding that same object-check code into the `Variables.overwrite()` function, but it feels like it should be put into getValueFromSource() so that we're not repeating it again in future. 

Any preference ?

**Comment by horike37** [comment]
Hi @dsole, thanks you for reporting :smile: 
Is it possible to share your plugin code so that we will take a look into it?

I tried to run `sls print` with your configuration and see working fine.
```
$sls print
service: test
provider:
  name: aws
  stage: dev
custom:
  test:
    child: dev
  nested:
    child: dev
```

However, something might go wrong to write it up within a plugin :thinking:

**Comment by dsole** [comment]
I've put a complete example in this Gist
https://gist.github.com/dsole/bb2f7ba74f8dace2113744f3828e367a

You'll need to copy the plugin script to a .serverless-plugins directory since Gist won't do directories.
```
mkdir .serverless-plugins
cp serverless-plugin-test.js .serverless_plugins/
```

My example plugin just has a hook function that writes the variable to the console and then kills the process to avoid actually deploying anything.
```javascript
  beforeDeployResources() {
    this.serverless.cli.log(this.serverless.service.custom.test.child);
    process.exit();
}
```

`sls print` seems to resolve the config correctly. However when I access the nested variable in a plugin it still has the variable placeholder syntax. 

**`$ sls print`**
```
service: test
provider:
  name: aws
  stage: dev
plugins:
  - serverless-plugin-test
custom:
  test:
    child: dev
  nested:
    child: dev
```

**`$ sls deploy`**
```
Serverless: ${self:provider.stage}
```
