### ISSUE TITLE
sls remove fails to remove SNS Subscriptions

### ISSUE THREAD

**Issue by gulbinas** [serverless/serverless#4512]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
  When invoking ```sls remove`` it fails to remove SNS Subscriptions
* What did you expect should have happened?
 SNS Subscriptions should be removed
* What was the config you used?
```

functions:
 ParseJobRange:
  handler: handler.ParseJobRange
  events:
    - sns:
        arn:
          Fn::Join:
            - ""
            - - "arn:aws:sns:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":${self:service}-${self:provider.stage}-ParseJobRangeQueue"
        topicName: ${self:service}-${self:provider.stage}-ParseJobRangeQueue
```
```  

Resources:
  resources:    
    parsejobrangeQueue:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-ParseJobRangeQueue
```
* What stacktrace or error message from your provider did you see?
  None

## Additional Data

* ***Serverless Framework Version you're using***:
```
 Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.6.0
     Serverless Version:     1.23.0
```
* ***Operating System***:
```
macOS 10.11.6
```

**Comment by horike37** [comment]
Hi @gulbinas, thank you for reporting :+1: 
Could you share your whole serverless.yml?

I tried it with the provided configuration, but `sls deploy` failed.

```
Serverless Error ---------------------------------------
  An error occurred: ParseJobRangeSnsSubscriptionSlstestdevParseJobRangeQueue - Topic does not exist.
```

**Comment by gulbinas** [comment]
@horike37: for me it's working configuration
```
service: AAAAA

frameworkVersion: ">=v1.23"

# custom: ${file(./environments/serverless/${opt:stage, 'prod'}.yml)}

provider:
  name: aws
  runtime: python2.7
  profile: AAAAAA
  region: eu-central-1
  stage: ${opt:stage, 'prod'}
  iamRoleStatements: ${file(iamRoleStatements.yml):iamRoleStatements}
custom:
  pkgPyFuncs:
    buildDir: _build
    requirementsFile: 'requirements.txt'
    globalIncludes:
      - ./lib
    globalRequirements:
      - ./requirements.txt
    cleanup: true
    # useDocker: true
    dockerImage: lambci/lambda:build-python2.7
    # dockerImage: lambci/lambda:build-python3.6


package:
  individually: true
  excludeDevDependencies: true

functions:
  ParseJobRange: ${file(src/AAAAAA/config.yml):ParseJobRange}

resources: ${file(resources.yml):resources}

plugins:
  - serverless-package-python-functions
```

```
ParseJobRange:
  handler: handler.ParseJobRange
  timeout: 300
  events:
    - sns:
        arn:
          Fn::Join:
            - ""
            - - "arn:aws:sns:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":${self:service}-${self:provider.stage}-ParseJobRangeQueue"
        topicName: ${self:service}-${self:provider.stage}-ParseJobRangeQueue
  package:
    include:
      - src/AAAAA
    artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:service}-${self:provider.stage}-ParseJobRange.zip
  environment:
    HTTP_PROXY: "http://172.31.33.231:8888"
    HTTPS_PROXY: "http://172.31.33.231:8888"
```

```
resources:
  Resources:

    parsejobQueue:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-ParseJobQueue


    parsejobrangeQueue:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-ParseJobRangeQueue
```

**Comment by RafalWilinski** [comment]
In order to reproduce this issue I had to modify config a bit:

```yml
service: AAAAA

frameworkVersion: ">=v1.23"

# custom: ${file(./environments/serverless/${opt:stage, 'prod'}.yml)}

provider:
  name: aws
  runtime: python2.7
  region: eu-central-1
  stage: ${opt:stage, 'prod'}
custom:
  pkgPyFuncs:
    buildDir: _build
    requirementsFile: 'requirements.txt'
    globalIncludes:
      - ./lib
    globalRequirements:
      - ./requirements.txt
    cleanup: true
    # useDocker: true
    dockerImage: lambci/lambda:build-python2.7
    # dockerImage: lambci/lambda:build-python3.6


package:
  individually: true
  excludeDevDependencies: true

functions:
  ParseJobRange: ${file(config.yml):ParseJobRange}

resources: ${file(resources.yml):resources}

```

```yml
resources:
  Resources:

    parsejobQueue:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-ParseJobQueue


    parsejobrangeQueue:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:service}-${self:provider.stage}-ParseJobRangeQueue
```

```yml
ParseJobRange:
  handler: handler.ParseJobRange
  timeout: 300
  events:
    - sns:
        arn:
          Fn::Join:
            - ""
            - - "arn:aws:sns:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":${self:service}-${self:provider.stage}-ParseJobRangeQueue"
        topicName: ${self:service}-${self:provider.stage}-ParseJobRangeQueue
  package:
    include:
      - src/AAAAA
  environment:
    HTTP_PROXY: "http://172.31.33.231:8888"
    HTTPS_PROXY: "http://172.31.33.231:8888"
```

I tried reproducing this issue, however `sls remove` works for me. Maybe you assigned some SNS subscriptions manually?
