### ISSUE TITLE
http proxy integration - doesn't support {proxy+} 

### ISSUE THREAD

**Issue by ozbillwang** [serverless/serverless#4514]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

serverless framework's http proxy integration doesn't support `{proxy+}`

* What did you expect should have happened?

Should be supported as aws api gateway document http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html

* What was the config you used?

```
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create/{proxy+}
          method: post
          integration: http # or http-proxy
          request:
            uri: https://example.com/{proxy}
            method: post # optional, defaults to http.method
```

get error 

    {"message": "Internal server error"}

Similar or dependent issues:
* related PR: #3534

**Comment by HyperBrain** [comment]
@ozbillwang Thanks for raising the issue 👍 .
Indeed, as shown in the referenced PR above and the AWS documentation, `{proxy+}/{proxy}` is supported by HTTP proxy endpoints. So it is valid, to have the support in Serverless too.

**Comment by ozbillwang** [comment]
@HyperBrain 

I test with `{id}`, got same error. I updated the issue with this new founding. 

Are they the same problem or difference?

**Comment by ozbillwang** [comment]
Seems PR (#3953) will fix this issue, leave my ticket open, until the PR is merged and I will test it.

**Comment by ozbillwang** [comment]
@lovenm 

I have this problem currently, guess you know how to fix it. 

Do you know how to set the paths id for `{proxy+}`

For example, it works with your PR (currently it has been merged)

```
request:
  uri: https://example.com/{id} # required
  method: post # optional, defaults to http.method
  parameters:
    paths:
      id: true
  headers:
    Content-Type: "text/xml;charset=utf-8"
```

But if I replace `id` to `proxy+`, how to reference it in `paths`?

**Comment by ozbillwang** [comment]
I can confirm this works with the PR (#3534) recently merged.

```
      - http:
          path: users/{proxy+}
          method: GET
          cors: true
          integration: http-proxy
          request:
            uri: ${self:custom.users.url}/{proxy}
            parameters:
              paths:
                proxy: true
```
