### ISSUE TITLE
Update to resource type AWS::Lambda::Version is not supported

### ISSUE THREAD

**Issue by Pjack** [serverless/serverless#4519]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
   There are two functions in the serverless.xml. 
   We modified one of the functions, i.e. another function is identical with before.
   But when we deploy the service, it will deploy fail
   
   sls deploy -s alpha

   I suspect it is caused by the option "individually" in serverless.yml
   Is it the expected behavior  or a bug?
 
* What did you expect should have happened?
 
I expect the identical function will not be deployed

* What was the config you used?
<pre>
provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs6.10
  memorySize: 128
  timeout: 3

package:
  individually: true
  exclude:
    - function1/**
    - function2/**
    - test/**
    - Makefile
  include:
    - config.yml

functions:
  function1:
    handler: function1/index.handler
    timeout: 120
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.kinesis.dailyEvents.arn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          enabled: true
    package:
      include:
        - function1/**

  function2:
    handler: function2/index.handler
    timeout: 120
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.config.kinesis.dailyEvents.arn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
          enabled: true
    package:
      include:
        - function2/**
</pre>

* What stacktrace or error message from your provider did you see?
An error occurred: AggregateLambdaVersionxlLCwdjyFiAJ08Phnp5rUCkcrKGghbeFQ4VOl7MOGo - Update to resource type AWS::Lambda::Version is not supported..

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: Ubuntu 14.04
* ***Stack Trace***: nope
* ***Provider Error messages***: nope

**Comment by HyperBrain** [comment]
Hi @Pjack, thanks for reporting the issue 😄 .
This might be an issue with the ap-northeast-1, i.e. maybe not all operations are supported there.
@horike37 Do you have some experience with that region?

**Comment by horike37** [comment]
Umm :thinking: 
I have never faced such a problem with ap-northeast-1.

**Comment by dynamikus** [comment]
It might not be a region thing I am having the same problem in us-east-1, but it fails only when I try to update an existing project. When I deploy for the first time it works just fine.

```
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: JobsubmitLambdaVersionIgGQw2gI6oL9U94w3HHxzyaeMy1iVdYdIq6AmUZvms - Update to resource type AWS::Lambda::Version is not supported..
```
**My serverless file:**
```yaml
provider:
  name: aws
  runtime: nodejs6.10  
  region: us-east-1
  stage: ${opt:stage, 'Development'}
  apiKeys: 
    - batch-dispatch-api-${self:provider.stage}
  iamRoleStatements: 
    - Effect: 'Allow'
      Action:
        - 'batch:SubmitJob'
        - 'batch:DescribeJobDefinitions'
      Resource: '*'        

functions:
  jobsubmit:
    handler: λ/job.submit
    name: ${self:service}-submit-${self:provider.stage}
    description: Responsible for submiting a job to the job queue. Repo- ${self:custom.packageJson.homepage} 
    memorySize: 128
    timeout: 3 
    tags: 
      System: Dex     
      Environment: ${self:provider.stage}
    events:
      - http:
          path: aws/batch/job/submit
          method: post
          cors: true
          private: true
```
