### ISSUE TITLE
Bug: resources not working for new lambda function

### ISSUE THREAD

**Issue by simlu** [serverless/serverless#4523]
When referencing a lambda function in `resources` that would be newly created with the deploy, I get an error saying that the lambda function can not be found. Should the Invoke Permission be updated after the functions are created?

Example:
```yaml
functions:
  some-function:
    ...

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: ${self:service}-${self:provider.stage}-some-function
        Principal: logs.${self:provider.region}.amazonaws.com
```

Error:
`An error occurred: LambdaInvokePermission - Function not found: arn:aws:lambda:REGION:XXXXXXXXXXX:function:SERVICE-ENV-some-function`

**Comment by HyperBrain** [comment]
Hi @simlu ,

I'm sure this is a problem with the order of the deployment. Assumingly, CloudFormation tries to create the permission before the lambda function has been created.

Can you try to add an DependsOn property to the permission resource, that references the function resource?
```yaml
LambdaInvokePermission:
  Type: ...
  Properties: ...
  DependsOn:
    - someFunctionLambdaFunction
```
