### ISSUE TITLE
Unresolved resource dependencies with Cloudformation conditions

### ISSUE THREAD

**Issue by Mortinke** [serverless/serverless#4535]
# This is a Bug Report

## Description

We get the error message "Template format error: Unresolved resource dependencies <resource_name> in the Resources block of the template" if we use Cloudformation conditions. 

I'd like to deploy two functions in different regions (eu-central-1 and eu-west-1). The function 1 (eu-central-1) need a security group which use a Cloudformation export for the VPC ID. In the region eu-west-1 the VPC/Cloudformation export doesn't exists. For this I added a condition that checks the region and should only create the security group if the region = eu-central-1.

config:
```
  Conditions:
    IsInFrankfurt:
      Fn::Equals: [ Ref: AWS::Region, "eu-central-1" ]
  Resources:
    LambdaSecurityRole:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: ${self:service}-${opt:stage}-security-group
        VpcId:
          Fn::ImportValue: vpc
      Condition: IsInFrankfurt
```

error message:
```
$ serverless deploy -s dev -v
Serverless: Removing Python requirements helper...
Serverless: Adding Python requirements helper...
Serverless: Installing required Python packages for runtime python2.7...
Serverless: Zipping required Python packages...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Removing Python requirements helper...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (4.16 MB)...
Serverless: Validating template...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

  Template format error: Unresolved resource dependencies [LambdaSecurityRole] in the Resources block of the template

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.9.2
     Serverless Version:     1.24.1
```

**Comment by HyperBrain** [comment]
@RafalWilinski Do you know, if Serverless currently supports embedding conditions at all into the CloudFormation template? The reason why I ask is, that the Conditions object needs to reside besides the Resources object in the template.
If that's the case, we should declare condition support rather as feature.

**Comment by tommedema** [comment]
Conditions work for me, so this feature already seems to exist. I am using it as follows:

_serverless.yml_
```
frameworkVersion: '=1.24.1'

service: ${{file(./package.json):name}}
        
custom:
  
  # environment specific domain names, if any; do not add www. as
  # this is setup automatically to redirect to your root domain
  domains:
    dev:
      name: tommedema-acm.tk
      requestCertificate: true
    
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 10
  stage: ${{opt:stage, 'dev'}}
  region: ${{opt:region, 'eu-west-2'}}
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}" # use ${{}} to access serverless variables
      
functions:
  # special function backing custom resource to generate SSL certificates
  requestCertificate:
    handler: scripts/request-certificate.handler
    timeout: 300
          
resources:
  Conditions:
    ShouldSetupDomain:
      Fn::Not:
        - Fn::Equals:
          - ${{self:custom.domains.${{self:provider.stage}}.name, 'none'}}
          - 'none'
          
    ShouldRequestCertificate:
      Fn::And:
        - Condition: ShouldSetupDomain
        - Fn::Equals:
            - ${{self:custom.domains.${{self:provider.stage}}.requestCertificate, 'false'}}
            - true
   
  Resources:
    
    # custom resource to retrieve SSL certificates
    CertificateResource:
      Condition: ShouldRequestCertificate
      Type: Custom::CertificateResource
      Properties:
        RootDomain: ${{self:custom.domains.${{self:provider.stage}}.name, 'none'}}
        ServiceToken:
          Fn::GetAtt: [RequestCertificateLambdaFunction, Arn]
```

**Comment by tommedema** [comment]
@Mortinke perhaps you are depending somewhere else in your cloudformation on `LambdaSecurityRole` while `IsInFrankfurt` equates to false; this would probably raise that error message you are getting, because you are depending on a resource that is not being created.

**Comment by Mortinke** [comment]
Sorry for the delay!

@tommedema: I can't find any other dependencies for the ```LambdaSecurityRole```.
Only the function ```create_postgres_user``` use this security group.

Here is the complete serverless.yaml file:
```
service: aws-cloudformation-utils

custom:
  pythonRequirements:
    zip: true
    invalidateCaches: true

provider:
  name: aws
  runtime: python2.7
  stage: tst

functions:
  create_postgres_user:
    handler: lambda_funct/create_postgres_user.create_postgres_user
    region: eu-central-1
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityRole
      subnetIds:
        - 'Fn::ImportValue': 'vpc-sub-priv-a1'
        - 'Fn::ImportValue': 'vpc-sub-priv-b1'
        - 'Fn::ImportValue': 'vpc-sub-priv-c1'
    memorySize: 128
    timeout: 60
    role: CreatePostgresUserLambdaRole
  verify_domain:
    handler: lambda_funct/ses_verify_domain.verify_domain
    region: eu-west-1
    role: SESVerifyDomainLambdaRole
    timeout: 60

resources:
  Conditions:
    IsInFrankfurt:
      Fn::Equals: [ Ref: AWS::Region, "eu-central-1" ]
  Resources:
    LambdaSecurityRole:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: ${self:service}-${opt:stage}-security-group
        VpcId:
          Fn::ImportValue: vpc
      Condition: IsInFrankfurt
    CreatePostgresUserLambdaRole:
       .....
    SESVerifyDomainLambdaRole:
      ....

plugins:
  - serverless-python-requirements
```
