### ISSUE TITLE
Serverless Function Deploy Validation Errors For Non-string Environment Variables

### ISSUE THREAD

**Issue by hybby** [serverless/serverless#4536]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
When performing a function update with `serverless deploy -f <function_name>`, where non-string environment variables are defined, `InvalidParameterType` errors are thrown after a successful deployment is reported.

The example I used includes an environment variable that is an integer:

```
$ serverless print --stage drew
...snip...
functions:
  devstack:
    handler: handler.devstack
    events:
      - http:
          path: devstack
          method: get
          private: true
    environment:
      STRING: foobar
      NOT_A_STRING: 123
...snip...
```

* What did you expect should have happened?
I expect the environment variables with values like this to pass validation.

* What was the config you used?
In `serverless.yml`:
```
functions:
  devstack:
    handler: handler.devstack
    events:
      - http:
          path: devstack
          method: get
          private: true
    environment:
      STRING: foobar
      NOT_A_STRING: 123
```

Note that surrounding the value of `NOT_A_STRING` in single quotes allows the function to deploy without error:

```
functions:
  devstack:
    handler: handler.devstack
    events:
      - http:
          path: devstack
          method: get
          private: true
    environment:
      STRING: foobar
      NOT_A_STRING: '123'  # this seems to be valid
```

* What stacktrace or error message from your provider did you see?
```
$ serverless deploy -f devstack --stage drew
Serverless: Installing required Python packages with python3.6...
Serverless: Linking required Python packages...
Serverless: Packaging function: devstack...
Serverless: Excluding development dependencies...
Serverless: Unlinking required Python packages...
Serverless: Uploading function: devstack (8.49 MB)...
Serverless: Successfully deployed function: devstack

  Serverless Error ---------------------------------------

  Expected params.Environment.Variables['NOT_A_STRING'] to be a string

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.7.0
     Serverless Version:     1.24.1
```

For feature proposals:
N/A

Similar or dependent issues:
* #4329

## Additional Data

* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: MacOSX
* ***Stack Trace***: N/A
* ***Provider Error messages***: Provided above
