### ISSUE TITLE
[Feature Proposal] Support HTTP Proxy Api Gateway Integration

### ISSUE THREAD

**Issue by syang** [serverless/serverless#4539]
# This is a Feature Proposal

## Description

* Serverless.yml should be able to provide an easy and straightforward way to describe HTTP Proxy to a service endpoint. something like

`proxy:
  myEndpoint:
    url: "http://myapp.com/oldEndpoint/"
    method: get`

* This feature should be a first class citizen in the api-gateway entry definition, instead of the current piggy back (or in a sense semi-hidden) way embedded inside a lambda function definition (which has been enabled in #3534 

## Use cases:

* someone defined an AWS ElasticSearch service https://search-YOURDOMAINSTRING.us-east-1.es.amazonaws.com, but would like to have API-Gateway as its proxy (e.g., to enable CORS like the one discussed at https://stackoverflow.com/questions/33337157/aws-elasticsearch-and-cors -- see solutions given by *Le3wood* there)

For related discussions please see:
* #3362

**Comment by Pat-rice** [comment]
This would be a good feature and also adding the method `ANY` would be handy.
It's straightforward to do such thing in AWS web console as explained [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html)

**Comment by massa-man** [comment]
It would be great if this implements all features of API gateway HTTP proxy, including the client certificate. We really need this to be able to keep our backend APIs private while proxying them via API gateway

**Comment by Pat-rice** [comment]
I'm not sure if that helps anyone, but I've managed to setup a proxy (main-api/{proxy+}) in serverless by setting up the following resources:

```
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: test-api-gateway
        Description: 'The main entry point of test APIs'
    MainApiBasePath:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: 'main-api'
        RestApiId:
          Ref: ApiGatewayRestApi
    MainApiProxyPath:
      Type: AWS::ApiGateway::Resource 
      Properties:
        ParentId:
          Ref: MainApiBasePath
        PathPart: '{proxy+}'
        RestApiId:
          Ref: ApiGatewayRestApi
    MainApiProxyAnyMethod:
      Type: AWS::ApiGateway::Method 
      Properties:
        AuthorizationType: NONE
        HttpMethod: ANY
        Integration: 
          IntegrationHttpMethod: ANY
          Type: HTTP_PROXY
          Uri: <existing_api_endpoint>/{proxy}
          PassthroughBehavior: WHEN_NO_MATCH
          RequestParameters:
            'integration.request.path.proxy': 'method.request.path.proxy'
        MethodResponses:
          - StatusCode: 200
        RequestParameters:
            'method.request.path.proxy': true
        ResourceId:
          Ref: MainApiProxyPath
        RestApiId:
          Ref: ApiGatewayRestApi
```

The proxy path has to be in its own resource declaration, it cannot be declared as `/a/path/{proxy+}`, but it's the same behavior in AWS API Gateway console.
