### ISSUE TITLE
http proxy integration - doesn't support {id} or any {resourcePath}

### ISSUE THREAD

**Issue by ozbillwang** [serverless/serverless#4549]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

serverless framework's http proxy integration doesn't support `{id}` or any with `{ }`

A similar problem has been reported via #4514, but looks like the are different problems. 

* What did you expect should have happened?

Should be supported as aws api gateway document http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html

* What was the config you used?

Example 1
```
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create/{id}
          method: post
          integration: http # or http-proxy
          request:
            uri: https://example.com/{id}
            method: post # optional, defaults to http.method
```
**get error** 

    {"message": "Internal server error"}

Then I replace `{id}` with one of valid id `1`

```
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create/1
          method: post
          integration: http # or http-proxy
          request:
            uri: https://example.com/1
            method: post # optional, defaults to http.method
```

**run `sls deploy` again, I can access the backend url with `id=1`**

Then I change it back to `{id}`, run `sls deploy` again.

**This time, it is fine. I can get backend url with different ids.** 

I enabled access logs and see the differences:

With error ` "Internal server error"`, the log is 

    (03eba8df-dd99-11e7-868e-19dc272ab184) Endpoint request URI: https://example.com/{id}

Runs well, the log is

    (0637a6ec-dd97-11e7-92c4-cff9f492c967) Sending request to https://example.com/1

So I am not sure why at first time, it can't resolve `{id}` to the dynamic ID.

**Comment by lovenm** [comment]
Your event definition is missing the request path parameter atleast, the request part should look something like this:

```
request:
  uri: https://example.com/{id} # required
  method: post # optional, defaults to http.method
  parameters:
    paths:
      id: true
```

However, the http/http-proxy integration still has some bugs related to this (https://github.com/serverless/serverless/issues/3840), but there's a PR (https://github.com/serverless/serverless/pull/3953) to fix them in review.

**Comment by ozbillwang** [comment]
@lovenm 

Thanks for the details and the PR.

Regarding your PR (#3953), I tested it and have some suggestions.

1) For the prompt when run `serverless deploy`, it doesn't make sense for me, what's meaning?

>Serverless: Warning! You're using the HTTP_PROXY in combination with a request configuration in your function "path". Only the request.parameters, request.uri configs are available in conjunction with HTTP_PROXY. Serverless will remove this configuration automatically before deployment.
Serverless: Warning! You're using the HTTP_PROXY in combination with a request configuration in your function "path". Only the request.parameters, request.uri configs are available in conjunction with HTTP_PROXY. Serverless will remove this configuration automatically before deployment.

2) You only merged the release 1.22.0 to your fork repo.

Could you please merge the latest master branch, currently it is already 1.25.0 released.

**Comment by lovenm** [comment]
I haven't worked on this for a while, but IIRC how it works, you're getting the warning because you've set some attribute other than parameters or uri in your request object when using http-proxy as integration, which will be stripped out since the proxy integration will only use those two.

I'll see if I have time to bump my fork with the latest release.

**Comment by ozbillwang** [comment]
Thanks, @lovenm 

I do have the extra setting as below, do you mean I can't use others, only parameters, uri and method?

```
request:
  uri: https://example.com/{id} # required
  method: post # optional, defaults to http.method
  parameters:
    paths:
      id: true
  headers:
    Content-Type: "text/xml;charset=utf-8"
```
