### ISSUE TITLE
Feature Request: Set Concurrency Limits on Individual AWS Lambda 

### ISSUE THREAD

**Issue by itzaliza** [serverless/serverless#4555]
# This is a Feature Proposal

## Description

Following AWS announcement of the ability to set the concurrency limit per each Lambda function (https://aws.amazon.com/about-aws/whats-new/2017/11/set-concurrency-limits-on-individual-aws-lambda-functions/), it would be nice to get this ability through the serverless framework.

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

```
functions:
  hello:
    handler: handler.hello # required, handler set in AWS Lambda
    name: ${self:provider.stage}-lambdaName # optional, Deployed Lambda name
    description: Description of what the lambda function does 
    concurrency: 5
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
