### ISSUE TITLE
Use one yml for multiple providers based on command line args

### ISSUE THREAD

**Issue by huemansdesign** [serverless/serverless#4568]
Hi team, love serverless. I'm trying to deploy to provider dynamically via command line args setting the name attribute. It fails silently and never deploys when I set the provider name via command line arg ${opt:provider} shown below in my serverless .yml. Is this possible, is my approach wrong? The cli output is below as well. Thanks!

---------- cli command 
```bash
sls deploy -v --provider=azure
```
---------- 

---------- my serverless.yml
```yaml
service: ${file(./config/constants.json):solution.name}-${self:provider.stage}
 
provider:
  name: ${opt:provider, 'azure'}
  runtime: nodejs6.10
  region: ${opt:region, 'us-east-1'}
  location: ${opt:location, 'East US'}
  stage: stage
  environment:
    ExecuteSequenceContent: ${file(./config/constants.json) :shared.executeApi}/ExecuteSequenceContent
    ExecuteSequencePaginate: ${file(./config/constants.json):shared.executeApi}/ExecuteSequencePaginate 
    paginateSequenceGenerator: ${file(./config/constants.json):shared.api}/paginateSequenceGenerator  
    contentSequenceGenerator:  ${file(./config/constants.json):shared.api}/contentSequenceGenerator
    DataAcces: ${file(./config/constants.json):shared.api}/DataAccess
    CONTENT_TABLE: ${self:service}-Content 
    CONTENT_URLS_TABLE: ${self:service}-ContentUrls    
    PAGINATE_URLS_TABLE: ${self:service}-PaginateUrls  
plugins:
  - serverless-azure-functions 

package:
  individually: true
  exclude:
    - functions/**
    - config/**
    - libs/**

functions: ${file(./config/${opt:provider}.yml)}  
```
---------- 

---------- command output (it always only shows below and fails after a minute or so )
sls deploy --provider=azure --verbose
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...

----------
