### ISSUE TITLE
Filter pattern improvement for cloudwatchLog events (aws)

### ISSUE THREAD

**Issue by willwhy** [serverless/serverless#4569]
# This is a Feature Proposal (Improvement)

## Description

For feature proposals:
* When adding a cloudwatchLog event, as mentioned by AWS document `Metric filter terms that include characters other than alphanumeric or underscore must be placed inside double quotes ("")`, if we want to add a filter like `"Total amount" - "level=DEBUG"`, we need to write it like this:

```yaml
events:
      - cloudwatchLog:
          logGroup: "/aws/lambda/my-lambda-log-group"
          filter: "\\\"Total amount\\\" -\\\"level=DEBUG\\\""
```
It is not straightforward and it is not obvious to users. I only found out that I need to write like above when I check the [source code](https://github.com/serverless/serverless/blob/v1.24.1/lib/plugins/aws/package/compile/events/cloudWatchLog/index.js#L87).

* Do you think it necessary to modify it and let it accept format like below:
```yaml
events:
      - cloudwatchLog:
          logGroup: "/aws/lambda/my-lambda-log-group"
          filter: '"Total amount" -"level=DEBUG"'
```

* Need to consider backwards compatible
* I can try to implement the improvement if you agree to make this change

Similar or dependent issues:
* None

## Additional Data

* ***Serverless Framework Version you're using***: v1.24.1
* ***Operating System***: Mac OSX, Linux, AWS AIM
* ***Stack Trace***:
* ***Provider Error messages***:
