### ISSUE TITLE
how to enable cors in serverless yml file

### ISSUE THREAD

**Issue by balakrishna222111** [serverless/serverless#4580]
@jchris @cselmer @jthomas @philhawksworth @whatupdave @horike37 i want to enable cors in serverless yml file

**Comment by tommedema** [comment]
Something like this?

```
functions:
  
  create:
    handler: functions/create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
```

Notice the `cors: true`
