### ISSUE TITLE
Cognito User Pool Trigger

### ISSUE THREAD

**Issue by mataide** [serverless/serverless#4600]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
Serverless dont allow me to create a trigger for Pre-token Generation
* What did you expect should have happened?
This should be a valid trigger.
* What was the config you used?
```
cognitoPretoken:
                description: "Cognito Pre-token"
                handler: api/cognito/pretoken/handler.default
                memorySize: 256
                timeout: 30
                events:
                  - cognitoUserPool:
                      pool: proak-cognito
                      trigger: PreTokenGeneration
```
* What stacktrace or error message from your provider did you see?
```
Cognito User Pool trigger source is invalid, must be one of: PreSignUp, PostConfirmation, PreAuthentication, PostAuthentication, CustomMessage, DefineAut
hChallenge, CreateAuthChallenge, VerifyAuthChallengeResponse. Please check the docs for more info.
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.25
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

```
Cognito User Pool trigger source is invalid, must be one of: PreSignUp, PostConfirmation, PreAuthentication, PostAuthentication, CustomMessage, DefineAut
hChallenge, CreateAuthChallenge, VerifyAuthChallengeResponse. Please check the docs for more info.
```
