### ISSUE TITLE
is not authorized to perform

### ISSUE THREAD

**Issue by ilrein** [serverless/serverless#4613]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?

Despite following the config @ https://github.com/serverless/examples/tree/master/aws-node-rest-api-with-dynamodb, I cannot get my permissions to pass.

```
"err": {
        "message": "User: arn:aws:sts::869691786575:assumed-role/profile-dev-us-east-1-lambdaRole/profile-dev-list is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-east-1:869691786575:table/blackbook-profiles",
```

* What did you expect should have happened?

I should have been able to invoke the function with no permission errors.

* What was the config you used?

```
service: profile

plugins:
  - serverless-plugin-optimize

package:
  individually: true

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  list:
    handler: functions/list.index
    events:
      - http:
          path: todos
          method: get
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
```

* What stacktrace or error message from your provider did you see?

```
iliareingold@MLA0RLI082 ~/g/b/m/profile> sls invoke -f list -l
{
    "err": {
        "message": "User: arn:aws:sts::869691786575:assumed-role/profile-dev-us-east-1-lambdaRole/profile-dev-list is not authorized to perform: dynamodb:PutItem on resource: arn:aws:dynamodb:us-east-1:869691786575:table/blackbook-profiles",
        "code": "AccessDeniedException",
        "time": "2017-12-27T20:55:47.871Z",
        "requestId": "N2RL5FAG4HHGV2F14NNL99BA13VV4KQNSO5AEMVJF66Q9ASUAAJG",
        "statusCode": 400,
        "retryable": false,
        "retryDelay": 9.679242056992843
    }
}
```

## Additional Data

* SLS v1.24.1
* MacOSx
