### ISSUE TITLE
Can't parse variable system when a second argument is hard-coded

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4624]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

When using a variable system, you can't parse properly a specified value when a second argument is hard-coded.

* What did you expect should have happened?

parsing as expected.

* What was the config you used?

```yaml
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    LAMBDA_SCHEDULE: ${env:LAMBDA_SCHEDULE, 'cron(0 0 * * ? *)'}
functions:
    cronFunc:
        handler: handler.cronFunc
        events:
           - schedule:
              rate: ${self:provider.environment.LAMBDA_SCHEDULE}
              enabled: true
```

Currently, it is transformed like this:

```yaml
"Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/aws-pppppp/dev/1514995580830-2018-01-03T16:06:20.830Z/aws-pppppp.zip"
        },
        "FunctionName": "aws-pppppp-dev-cronFunc",
        "Handler": "handler.cronFunc",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs6.10",
        "Timeout": 6,
        "Environment": {
          "Variables": {
            "LAMBDA_SCHEDULE": "${env:LAMBDA_SCHEDULE, 'cron(0 0 * * ? *)'}"
          }
        }
      }
```

* What stacktrace or error message from your provider did you see?
Any errors are not detected.

## Additional Data
* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: darwin
* ***Stack Trace***: none
* ***Provider Error messages***: none
