### ISSUE TITLE
deploy lambda function with vpc apparently fails silently

### ISSUE THREAD

**Issue by eliasisrael** [serverless/serverless#4630]
# This is a (Bug Report / Feature Proposal)
Bug Report

## Description
When deploying some functions into a VPC using the AWS provider, my 'vpc' block appears to entirely ignored.

For bug reports:
* What went wrong?
I defined a vpc block for a number of functions (3 of them, specifically) as follows:

```
vpc:
      vpc:
            SecurityGroupIds:
                - { "Ref" : "vpcSecurityGroup"}
            SubnetIds:
                - { "Ref": "esSubnet" }
```

* What did you expect should have happened?
I expected the vpc configuration to be put on the functions.

* What was the config you used?

* What stacktrace or error message from your provider did you see?
No error message. Instead, the functions are created with VPC configuration information.

* #12345

## Additional Data

I am using the serverless-domain-manager plugin and the serverless-split-stacks plugin. No other plugins.

* ***Serverless Framework Version you're using***:
1.25.0

* ***Operating System***:
MacOS High Sierra

* ***Stack Trace***:
None given

* ***Provider Error messages***:
None given

**Comment by hassankhan** [comment]
Should be as follows: 

```yaml
vpc:
    securityGroupIds:
      - xxx
    subnetIds:
      - xxx
      - xxx
```

**Comment by eliasisrael** [comment]
I tried that, no difference. I have a suspicion, but nothing concrete yet, that suggests it's because of the split-stacks plugin.

**Comment by TomYip** [comment]
I have the same problem and I'm using serverless version 1.26.0

**Comment by hassankhan** [comment]
@eliasisrael It might be an idea to create a simple test project with a single Lambda and VPC configuration with and without the `split-stacks` plugin to diagnose. 😄 

@TomYip Could we see your `serverless.yml`, please?

**Comment by TomYip** [comment]
Thanks for the quick response! I got my problem figured out... there’s a typo in my yml, and looking at the code if one of the properties in the vpc object is missing then the whole vpc section will be ignored. 

I suggest the serverless tool to throw an error if vpc object is detected but there are missing properties. Thanks!

**Comment by mgsteinkamp** [comment]
This really does need SOME kind of message... a missing space in my yaml for one VPC section resulted in the VPC settings for all subsequent lambda functions failing silently...

**Comment by lancekrogers** [comment]
Off topic, but how many subnets do I need in my serverless config per lambda function?

**Comment by jsleeuw** [comment]
I'm experiencing this problem too. Can anyone spot any issues with the yaml here? 

```
...
functions:
  graphql:
    handler: handler.handler
    vpc:
      securityGroupIds:
        - sg-xxx
      subnetdIds:
        - subnet-xxx
        - subnet-xxx
```

**Comment by engmsaleh** [comment]
I had the same problem and it appeared after a lot of trials it is a matter of the wrong indentation.

**Comment by rishimittal** [comment]
+1
...
  vpc:
    securityGroupIds:
      - "sg-xxx"
    subnetdIds:
      - "subnet-xxxxxx"
      - "subnet-xxxxxx"
      - "subnet-xxxxxx"

**Comment by rishimittal** [comment]
@drexler thanks my bad, somehow missed it, but still strange is that this fails silently.

**Comment by DrakkenSaer** [comment]
I too am experiencing this problem. 

```
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  role: ${opt:role}
  deploymentBucket:
    name: ${opt:bucket}
  deploymentPrefix: ${self:provider.stage}/${self:service}
  vpc:
    securityGroupIds:
      - ${opt:security-group, env:SECURITY_GROUP} 
    subnetdIds:
      - ${opt:security-group-subnet-1, env:SECURITY_GROUP_SUBNET_1}
      - ${opt:security-group-subnet-2, env:SECURITY_GROUP_SUBNET_2}
      - ${opt:security-group-subnet-3, env:SECURITY_GROUP_SUBNET_3}
```

After running `sls package` while supplying all the option variables, I can see the VPC values in `.serverless/serverless-state.json` but the values do not appear in `.serverless/cloudformation-template-update-stack.json`

**Comment by jonvaughan** [comment]
@DrakkenSaer you also have subnetdIds instead of subnetIds

**Comment by DrakkenSaer** [comment]
@jonvaughan Wow I feel silly now! That was the problem

**Comment by shubsaini09** [comment]
I was also facing the same issue. 

Yaml formatting is correct.
VPC getting added to  cloudformation template

but my function is not getting VPC. 
```
...
timeout: 30
    description: Push data to splunk
    vpc:
      securityGroupIds:
        - ${file(./env.yaml):${opt:stage, self:provider.stage}.securitygroupid}
      subnetIds:
        - ${file(./env.yaml):${opt:stage, self:provider.stage}.subnet_id}
    events:
...
```

If i used provider object then it is attaching VPC to all the functions (which i don't want) except that one. Very strange.  

Same IAM role is being used for all the functions. 

What i did? I deleted my lambda function and recreated it with a different name using serverless and i got the vpc in it properly. Same thing happened with me for log group error also. Try renaming/creating new resource. This is some problem with serverless itself. 

Hope it helps some one in need.
