### ISSUE TITLE
Unable to deploy in offline mode a dynamoDB table having tags

### ISSUE THREAD

**Issue by andreea-mirea** [serverless/serverless#4635]
This is a Bug Report

Trying to deploy in offline mode a dynamoDB table with tags, gives the following error
UnexpectedParameter: Unexpected key 'Tags' found in params

Configuration:
```
resources:
  Resources:
    CustomDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
          -
            AttributeName: id
            AttributeType: S        
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
          -
            AttributeName: id
            KeyType: RANGE
        TableName: ${self:provider.environment.CUSTOM_DYNAMODB_TABLE}
        Tags:
          - 
            Key: 'Status'
            Value: 'InDevelopment'
          - 
            Key: 'Version'
            Value: '1.0.0'
```
Deploying this to aws works fine.
Serverless version 1.21.1

Stacktrace:
```
UnexpectedParameter: Unexpected key 'Tags' found in params
    at ParamValidator.fail (/Users/user/project/backend/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/user/project/backend/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/Users/user/project/backend/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/user/project/backend/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/user/project/backend/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/Users/user/project/backend/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/user/project/backend/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/user/project/backend/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/Users/user/project/backend/node_modules/aws-sdk/lib/config.js:320:7)
    at /Users/user/project/backend/node_modules/aws-sdk/lib/config.js:338:9
    at Credentials.get (/Users/user/project/backend/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/user/project/backend/node_modules/aws-sdk/lib/config.js:332:24)
    at Config.getCredentials (/Users/user/project/backend/node_modules/aws-sdk/lib/config.js:352:9)
    at Request.VALIDATE_CREDENTIALS (/Users/user/project/backend/node_modules/aws-sdk/lib/event_listeners.js:80:26)
    at Request.callListeners (/Users/user/project/backend/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
    at Request.emit (/Users/user/project/backend/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/user/project/backend/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/user/project/backend/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/user/project/backend/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at Request.runTo (/Users/user/project/backend/node_modules/aws-sdk/lib/request.js:403:15)
    at Request.send (/Users/user/projects/backend/node_modules/aws-sdk/lib/request.js:367:10)
    at makeRequest (/Users/user/project/backend/node_modules/aws-sdk/lib/service.js:193:27)
    at svc.(anonymous function) [as createTable] (/Users/user/project/backend/node_modules/aws-sdk/lib/service.js:499:23)
    at BbPromise (/Users/user/project/backend/node_modules/serverless-dynamodb-local/index.js:247:26)
    at ServerlessDynamodbLocal.createTable (/Users/user/project/backend/node_modules/serverless-dynamodb-local/index.js:240:16)
    at BbPromise.each (/Users/user/project/backend/node_modules/serverless-dynamodb-local/index.js:133:55)
From previous event:
    at PluginManager.invoke (/Users/user/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:261:22)
    at PluginManager.run (/Users/user/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:292:17)
    at variables.populateService.then (/Users/user/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/user/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/user/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/bin/serverless:39:50)
```
Thanks in advance
