### ISSUE TITLE
Deploy failed to subscribe function to existing SNS Topic

### ISSUE THREAD

**Issue by alexb-uk** [serverless/serverless#4637]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Deploy failed to subscribe function to existing SNS Topic when ARN is specified as a sub parameter.
* What did you expect should have happened?
Subscription should have been created.
* What was the config you used?
See example in docs: https://serverless.com/framework/docs/providers/aws/events/sns/#using-a-pre-existing-topic

```
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns:
          arn: arn:xxx
```

* What stacktrace or error message from your provider did you see?
N/A deploy completed with success:
```bash
$ serverless deploy --verbose
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - geocoder-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - geocoder-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (10.08 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - geocoder-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GeocodeLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - GeocodeLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - GeocodeLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - GeocodeLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - GeocodeLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - GeocodeLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - GeocodeLambdaVersionRmRziP4pdOkGzNTTPDps1BAxX6QUsEImdKe9Yyn7qk
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - GeocodeLambdaVersionRmRziP4pdOkGzNTTPDps1BAxX6QUsEImdKe9Yyn7qk
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - GeocodeLambdaVersionRmRziP4pdOkGzNTTPDps1BAxX6QUsEImdKe9Yyn7qk
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - geocoder-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - geocoder-dev
Serverless: Stack update finished...
Service Information
service: geocoder
stage: dev
region: eu-west-2
stack: geocoder-dev
api keys:
  None
endpoints:
  None
functions:
  geocode: geocoder-dev-geocode

Stack Outputs
ServerlessDeploymentBucketName: geocoder-dev-serverlessdeploymentbucket-a9oksuw16rmp
GeocodeLambdaFunctionQualifiedArn: arn:aws:lambda:eu-west-2:xxxxxx:function:geocoder-dev-geocode:1
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: Windows
* ***Node***: 6.10.3

**Please note that the first example in the docs DOES work:**

```
functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns: arn:xxx
```

Working output:
```
$ serverless deploy --verbose
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (10.08 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - geocoder-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - GeocodeLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - GeocodeLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - GeocodeLambdaPermissionListingseventsdevSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Subscription - GeocodeSnsSubscriptionListingseventsdev
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - GeocodeLambdaPermissionListingseventsdevSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Subscription - GeocodeSnsSubscriptionListingseventsdev
CloudFormation - CREATE_COMPLETE - AWS::SNS::Subscription - GeocodeSnsSubscriptionListingseventsdev
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - GeocodeLambdaPermissionListingseventsdevSNS
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - geocoder-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - geocoder-dev
Serverless: Stack update finished...
Service Information
service: geocoder
stage: dev
region: eu-west-2
stack: geocoder-dev
api keys:
  None
endpoints:
  None
functions:
  geocode: geocoder-dev-geocode

Stack Outputs
ServerlessDeploymentBucketName: geocoder-dev-serverlessdeploymentbucket-a9oksuw16rmp
GeocodeLambdaFunctionQualifiedArn: arn:aws:lambda:eu-west-2:xxxxx:function:geocoder-dev-geocode:1
```

Sorry I'm not sure if this is a bug with the example in the documentation or code?

Thanks a lot for all the hard work on Serverless.

Alex

**Comment by ctimmins** [comment]
@alexb-uk the example successfully deployed for you?  I can't get a successful deploy using a topic arn to subscribe a lambda to an already existing sns topic
```
functions:
  activateSubWorkflow:
      handler: activate_workflow.activate_workflow
      events:
        - sns: "arn:aws:sns:<REGION>:<ACCOUNT>:<TOPIC_NAME>"
```  

serverless deploy complains `Invalid parameter: TopicArn.`  Its trying to concatenate the name of the function with the topic name instead of using the arn to subscripe the function to

**Comment by alexb-uk** [comment]
@ctimmins I suspect you need to remove the double quotes. 

Are the angled brackets, <REGION>, just placeholders or are they actually in your template? Reason I ask is I don't believe they are valid syntax... either ${varname} or you can use CloudFormation style: https://serverless.com/framework/docs/providers/aws/events/sns/

For example here is my function definition:
```
functions:
  geocode:
    handler: functions/geocode.handler
    onError: arn:aws:sns:eu-west-2:xxxxx:sysops-admins
    events:
      - sns: arn:aws:sns:eu-west-2:xxxxx:create-events-${self:provider.stage}
```

**Comment by ctimmins** [comment]
The angled brackets are just placeholders and I used a valid SNS ARN.  Interestingly, I tried using an invalid ARN `arn:aws:bleep:bloop:xxxxx` and serverless complained about the provided ARN not matching a specific pattern.  I also tried using the CloudFormation intrinsic function to build the ARN but it just doesn't work (same error of `Invalid parameter: TopicArn`).

Long story short, i do think there is a bug with the binding of the lambda to an _already existing_ SNS topic.  I gave up though and just created a new SNS topic via serverless

**Comment by hassankhan** [comment]
Try specifying the ARN as follows:

```yaml
functions:
  geocode:
    handler: functions/geocode.handler
    onError: arn:aws:sns:eu-west-2:xxxxx:sysops-admins
    events:
      - sns: 
          arn: arn:aws:sns:eu-west-2:xxxxx:create-events-${self:provider.stage}
          topicName: "MyTopic"
```

**Comment by alexb-uk** [comment]
@hassankhan thanks for the suggestion but that didn't seem to work.
Without the SNS topic actually existing the suggestion above completed but no topic was created or subscription.

After manually creating a new SNS topic the following did work:

```yaml
directions:
      handler: functions/directions.handler
      onError: arn:aws:sns:eu-west-2:xxxxx:sysops-admins
      events:
        - sns: arn:aws:sns:eu-west-2:xxxxx:routes-events-${self:provider.stage}
          topicName: routes-events-${self:provider.stage}
          displayName: Routes API
```

Output:
```
$ serverless deploy --verbose
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (10.43 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - geocoder-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - GeocodeLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - BulkGeocodeLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - DirectionsLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - BulkGeocodeLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - GeocodeLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - DirectionsLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - DirectionsLambdaPermissionRouteseventsdevSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Subscription - DirectionsSnsSubscriptionRouteseventsdev
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - DirectionsLambdaPermissionRouteseventsdevSNS
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Subscription - DirectionsSnsSubscriptionRouteseventsdev
CloudFormation - CREATE_COMPLETE - AWS::SNS::Subscription - DirectionsSnsSubscriptionRouteseventsdev
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - DirectionsLambdaPermissionRouteseventsdevSNS
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - geocoder-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - geocoder-dev
Serverless: Stack update finished...
Service Information
service: geocoder
stage: dev
region: eu-west-2
stack: geocoder-dev
api keys:
  None
endpoints:
  None
functions:
  geocode: geocoder-dev-geocode
  bulkGeocode: geocoder-dev-bulkGeocode
  directions: geocoder-dev-directions

Stack Outputs
DirectionsLambdaFunctionQualifiedArn: arn:aws:lambda:eu-west-2:xxxxx:function:geocoder-dev-directions:3
BulkGeocodeLambdaFunctionQualifiedArn: arn:aws:lambda:eu-west-2:xxxxx:function:geocoder-dev-bulkGeocode:12
ServerlessDeploymentBucketName: geocoder-dev-serverlessdeploymentbucket-xxxxxx
GeocodeLambdaFunctionQualifiedArn: arn:aws:lambda:eu-west-2:xxxxx:function:geocoder-dev-geocode:13

Serverless: Removing old service versions...
```

Thanks again.

**Comment by jakubholynet** [comment]
same problem here. I have (account IDs changed):

```yaml
  codedeploy-ses-notifications:
    cljs: lambda.core/codedeploy-ses-notifications
    events:
      - ses: arn:aws:sns:eu-west-1:123456789012:cd-sns-lambda # -prod
      - ses: arn:aws:sns:eu-west-1:00000000000:cd-sns-lambda # -stage
```

subscriptions are not created and the lambda policy is not updated to add invoke permissions to SNS.

**Comment by johntellsall** [comment]
We're being affected by this too.  In my research, it appears Serverless either 1) creates *both* the SNS topic and the Lambda binding, or 2) re-uses an existing SNS topic.  It does not *update* an existing topic with a new binding.

For us, we're using CI/CD, which means that our deployments cannot update AWS resources automatically. Either we zap the topics manually and have Serverless (re)create & bind them, or we have to manually adjust the Lambda bindings.

Using CI/CD with Serverless sounds like a useful feature, what workarounds have people found?

One direction is for us to use Serverless to create + bind the topic, then we manually import the topic + binding into Terraform. For downstream environments (dev, staging, sales, production), we use Terraform only and tell Serverless to just re-use the TF-created Topics.  I'm hoping for a simpler and more durable solution. :)

**Comment by obie** [comment]
Having a similar issue although it's sporadic and haven't been able to discern what the pattern is to some subscriptions working and some not. What's strange is that the right directives seem to end up in the Cloudformation template, and AWS knows that I was trying to make the subscription happen. When I use the AWS console to examine a lambda that has a failed subscription, it has this message:

![image](https://user-images.githubusercontent.com/3908/52586784-fca29500-2dfd-11e9-8b3b-a14c67e53234.png)

Clicking 'Fix' then 'Save' does indeed fix the subscription. The sporadic nature of this failure is what concerns me the most. I guess we have to add a manual verification step to our deployments.

**Comment by jkruse14** [comment]
Just wanted to add my voice here. We ran into this exact issue and the workaround from @marcelalburg got us fixed up.

**Comment by obie** [comment]
Thanks @jkruse14 

Unfortunately this is an extremely unattractive workaround for us, because of the direction of the dependency. Our `Topic` resources are defined in the stacks where those messages originate. Those stacks should not have prior knowledge or coupling to the consuming lambdas, which by the nature of our application architecture exist in other stacks, in some cases being managed by other teams in other repositories.

cc: @marcelalburg

**Comment by noreabu** [comment]
After several hours of trial and error we came up with somthing that worked.

Our use case:
1. monitor the memory consumption of a lambda function
2. raise an alarm when > number
3. Alarm action to send details to SNS Topic
4. SNS triggers a lambda function (which posts the alarm to slack)

Complete example is not available due to reasons..., but i hope i have included all required parts:
```
custom:
  alarms:
    topicName: "${env:DEPLOYMENT_NAME}-foobar-alarms"
    topicArn:
      Fn::Join:
        - ":"
        - - "arn:aws:sns"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "${env:DEPLOYMENT_NAME}-foobar-alarms"
```
Note, there are more functions, but only this one is subscribed to sns.
**Beware of the indentation below** Two spaces less in front of `arn` and `topicName` and it stops working...
```
functions:
  snsToSlack:
    DependsOn:
      - AlarmTopic
    package:
      exclude:
        - ./**
      include:
        - ./bin/lambdas/all/snsToSlack/main
    handler: bin/lambdas/all/snsToSlack/main
    events:
      - sns:
          arn: ${self:custom.alarms.topicArn}
          topicName: ${self:custom.alarms.topicName}
```
...
```
    AlarmTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "Foo Bar Alarms"
        TopicName: ${self:custom.alarms.topicName}
    AlarmTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      DependsOn:
        - AlarmTopic
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowCloudWatchToPublish
              Effect: Allow
              Principal:
                AWS: '*'
              Action: 'sns:Publish'
              Resource:
                Ref: AlarmTopic
        Topics:
          - Ref: AlarmTopic
    FooMemoryMetric:
      Type: "AWS::Logs::MetricFilter"
      Properties:
        FilterPattern: '[ report_label="REPORT", ..., label="Used:", max_memory_used_value, unit="MB" ]'
        LogGroupName:
          Ref: FooLogGroup
        MetricTransformations:
          - MetricName:
              'Fn::Join':
                - '-'
                - - Ref: FooLambdaFunction
                  - MaxMemory
            MetricNamespace: LogMetrics/Lambda
            MetricValue: $max_memory_used_value
    FooMemoryAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn:
        - FooLambdaFunction
        - SnsToSlackLambdaFunction
      Properties:
        Namespace: LogMetrics/Lambda
        MetricName:
          'Fn::Join':
            - '-'
            - - Ref: FooLambdaFunction
              - MaxMemory
        AlarmDescription:
          'Fn::Join':
            - ' '
            - - Ref: FooLambdaFunction
              - Memory Alarm
        Threshold: ${self:custom.foo.memoryAlarmThreshold}
        Period: 10
        EvaluationPeriods: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        AlarmActions:
          - ${self:custom.alarms.topicArn}
        Statistic: Maximum
```

**Comment by Ryanauger95** [comment]
Experiencing this issue in September still. Had to manually subscribe the lambda to the topic

**Comment by adamdiy** [comment]
still experiencing this issue now as well

**Comment by darbio** [comment]
and in December!

**Comment by ludaavics** [comment]
And in 2020..

**Comment by shawngrona** [comment]
same, following this one

**Comment by lazartravica** [comment]
Following

**Comment by mcshiz** [comment]
For a pretty easy workaround I've just decided to use SQS to trigger my lambda instead of SNS.
In order to do so I had to create a Queue, a Queue Policy, and a SNS Subscription subscribing the queue to the topic.

``` yaml
PurpleTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Join [ "-", [ "${self:provider.stage}", "purple-topic"]]
PurpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-purple-queue
      VisibilityTimeout: 60
      RedrivePolicy:
        maxReceiveCount: 4
        deadLetterTargetArn: !GetAtt PurpleQueueDLQueue.Arn
PurpleQueueDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-purple-dql
      VisibilityTimeout: 60
PurpleQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref PurpleQueue
      PolicyDocument:
        Statement:
          - Sid: allow-sqs-sendmessage
            Effect: Allow
            Principal:
              AWS: "*"
            Action: SQS:SendMessage
            Resource: !GetAtt PurpleQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref PurpleTopic
PurpleTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt PurpleQueue.Arn
      Protocol: sqs
      Region: us-west-2
      TopicArn: !Ref PurpleTopic

```

And then triggering my Lambda from the SQS instead
``` yaml
snsToStep:
  handler: functions/snsToStep.handler
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - PurpleQueue
            - Arn  
```

**Comment by dtieber** [comment]
It's working for me again, but I had to delete the function and the subscription because updating the stack did not work anymore after I changed the subscription filter manually on the AWS UI.

```     
events:
  - sns:
      arn: arn:aws:sns:${opt:region, self:provider.region}:#{AWS::AccountId}:app-${opt:stage}-change-notification
      filterPolicy:
        type:
          - "employees"
```

I'm using 
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.0
     Framework Version:         1.67.0
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Version:        2.22.3
```

**Comment by violiveira** [comment]
@dtieber I guess you are using this plugin right: https://www.serverless.com/plugins/serverless-pseudo-parameters ?

**Comment by ftruzzi** [comment]
Hi,

I just started using serverless today but can't find a solution to this when subscribing an existing topic as an onFailure destination for a dynamodb stream.

```yaml
resources:
  Resources:
    failTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "topicName"
        Subscription:
          - Endpoint: "francesco@truzzi.me"
            Protocol: EMAIL

functions:
  myfunction:
    events:
    - stream:
      # stuff
      destinations:
        onFailure:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sns
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - Fn::GetAtt [ failTopic ]
          type: sns
```

or

```yaml
        onFailure:
          arn:
            Ref: failTopic
          type: sns
```

both return `failTopic - topicName already exists in stack arn:aws:cloudformation:`

Any tips? Thanks
