### ISSUE TITLE
Build suddenly fails on Travis CI 

### ISSUE THREAD

**Issue by sallyamoore** [serverless/serverless#4642]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?
Travis CI build failed with: 
```
Error --------------------------------------------------
 
  ENOENT: no such file or directory, open '/home/travis/build/<my package>/node_modules/create-hash/node_modules/.bin/sha.js'
```

The build passed two days ago. I made minimal changes and found that the build was failing. I then restarted the _same build_ that passed two days previously, and it failed as well.

I see that the serverless postinstall script is now outputing:
```
> serverless@1.25.0 postinstall /home/travis/build/k0ru/ats-taleo/node_modules/serverless
> node ./scripts/postinstall.js

- cipher-base@1.0.4 node_modules/cipher-base
- hash-base@2.0.2 node_modules/hash-base
- commander@2.12.2 node_modules/json-refs/node_modules/commander
- ripemd160@2.0.1 node_modules/ripemd160
- uuid@3.1.0 node_modules/serverless/node_modules/aws-sdk/node_modules/uuid
- sha.js@2.4.9 node_modules/sha.js
- create-hash@1.1.3 node_modules/create-hash
- create-hmac@1.1.6 node_modules/create-hmac
- aws-sdk@2.179.0 node_modules/serverless/node_modules/aws-sdk
```

On the last passing build, the equivalent output was: 
```
> serverless@1.25.0 postinstall /home/travis/build/k0ru/ats-taleo/node_modules/serverless
> node ./scripts/postinstall.js

- commander@2.12.2 node_modules/json-refs/node_modules/commander
- uuid@3.1.0 node_modules/serverless/node_modules/aws-sdk/node_modules/uuid
- aws-sdk@2.176.0 node_modules/serverless/node_modules/aws-sdk
```

* What did you expect should have happened?
The build passes. 
* What was the config you used?
```
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage} 
  version: 1
  region: us-east-1
  deploymentBucket: ${self:service}-deployments
  memorySize: 128
  environment:
    STAGE: ${self:provider.stage}
  iamRoleStatements:
    <various permissions> 

plugins:
  - serverless-plugin-aws-alerts

package:
  exclude:
    - .travis.yml
    - '*.env'
    - env.tar.gz
    - env.tar.gz.enc
    - .eslintrc.js
    - yarn.lock
    - .ci/**
    - tests/**
    - README.md

functions:
   <function info here> 
```
* What stacktrace or error message from your provider did you see?
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, open '/home/travis/build/k0ru/ats-taleo/node_modules/create-hash/node_modules/.bin/sha.js'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, open '/home/travis/build/k0ru/ats-taleo/node_modules/create-hash/node_modules/.bin/sha.js'
    at Error (native)
From previous event:
    at Package.getFileContent (/home/travis/build/<my_package>/node_modules/serverless/lib/plugins/package/lib/zipService.js:116:15)
    at Package.getFileContentAndStat (/home/travis/build/<my_package>/node_modules/serverless/lib/plugins/package/lib/zipService.js:105:12)
    at Array.map (native)
    at WriteStream.output.on (/home/travis/build/<my_package>/node_modules/serverless/lib/plugins/package/lib/zipService.js:83:29)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at /home/travis/build/<my_package>/node_modules/graceful-fs/graceful-fs.js:214:14
    at /home/travis/build/<my_package>/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:123:15)
```

For feature proposals: NA
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* None known

## Additional Data

* ***Serverless Framework Version you're using***:
1.25.0
* ***Operating System***:
Travis: Ubuntu 14.04.5, Locally: Mac High Sierra
* ***Stack Trace***: see above
* ***Provider Error messages***: see above
