### ISSUE TITLE
The specified bucket does not exist

### ISSUE THREAD

**Issue by lukasholzer** [serverless/serverless#4649]
# This is a  Bug Report

### What went wrong?
When I want to deploy my serverless Application I get the message **The specified bucket does not exist**. The local invoke is working! So if I run `serverless invoke local --function generate -l --path calls/generate.json` I get the result I want.

### What did you expect should have happened?
Working deployment  with `serverless deploy

### What was the config you used?
my **serverless.yml** file
```yml
service: pdf-service

custom:
  bucket: pdf-service-upload
  webpack: ./config/webpack.config.js  
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
functions:
  generate:
    handler: api/pdf.generate
    events:
      - http:
          path: generate/{$id}
          method: get
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

```

### What stacktrace or error message from your provider did you see?
```bash
serverless deploy
Serverless: Bundling with Webpack...
Time: 84ms
     Asset     Size  Chunks             Chunk Names
api/pdf.js  5.41 kB       0  [emitted]  api/pdf
   [0] ./api/pdf.js 981 bytes {0} [built]
   [1] external "html-pdf-chrome" 42 bytes {0} [not cacheable]
   [2] external "path" 42 bytes {0} [not cacheable]
   [3] external "fs" 42 bytes {0} [not cacheable]
   [4] ./api/libs/response.js 355 bytes {0} [built]
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: html-pdf-chrome@^0.4.1
Serverless: Packaging service...
 
  Serverless Error ---------------------------------------
 
  The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.2.1
     Serverless Version:     1.25.0

```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* [72](https://github.com/serverless/serverless-graphql/issues/72)
## Additional Data
* [link to the gitrepo](https://github.com/type-flow/pdf-service-aws)
* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: MacOSX
* ***Stack Trace***:
* ***Provider Error messages***:

Regards Lukas
