### ISSUE TITLE
Share API Gateway does not work.

### ISSUE THREAD

**Issue by lgaidzik** [serverless/serverless#4655]
# This is a Bug Report 

## Description

For bug reports:
* What went wrong?
I try to deploy my functions to aws using an existing apiGateway. I specified my resources like it is documentated: https://serverless.com/framework/docs/providers/aws/events/apigateway/#share-api-gateway-and-api-resources.
When i deploy `sls deploy` a new api gateway will be generated.

* What did you expect should have happened?
My existing Api Gateway will be extended with the new lambda functions.

* What was the config you used?
```
service: my-service
frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 512
  versionFunctions: false
  apiGateway:
      restApiId: m951cb3dff
      restApiRootResourceId: mppa37p3o1
  #    restApiResources: # List of existing resources that were created in the REST API. This is required or the stack will be conflicted
  #      '/users': xxxxxxxxxx
  #      '/users/create': xxxxxxxxxx

  # S3 Bucket
  deploymentBucket:
    name: lambda.serverless.deploys

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
```

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data
My existing api gateway has only the `restApiRootResourceId`.

* ***Serverless Framework Version you're using***:
```
sls -v 
1.25.0
```
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by horike37** [comment]
Hi, @lgaidzik.
Currently, the shared API functionality has not been available yet.
It will be released in v 1.26.0.
You can install it with `npm install -g serverless/serverless#master` if you want to use it as soon as possible.

**Comment by perevernihata** [comment]
Hi guys, when I try to attach multiple services to the same api gateway using the approach above. But I'm gettings this error: 
`An error occurred: 2UnderscorevX1V74l4iApiGatewayAuthorizer - Authorizer name must be unique. Authorizer 2_vX1V74l4i already exists in this RestApi..`
I use cognito authorizer with every function in all of my services, and it seems like serverless tries to recreate it for every service under the API gateway with same name which obviously can not work.
Am I missing something obvious?

**Comment by HyperBrain** [comment]
@perevernihata Authorizers are API global, i.e. one authorizer only can exist once in an API. So only one of your services must define the authorizer and all others must reference it by arn.
As I'm not using the shared API Gateway, perhaps one of the authors or reviewers of #3078 can shed some light on this or give some advice. 
/cc @hgiasac @horike37 @RafalWilinski

**Comment by hgiasac** [comment]
I submitted this PR #4197 for enabling custom authorizer reference. I don't know if there is any new PR for  better solution.

**Comment by perevernihata** [comment]
@HyperBrain yea I know that authorizers are global, and I already pointing to the Cognito ARN, which is one per all services. I've provided more details there https://github.com/serverless/serverless/issues/4824

**Comment by jupeter** [comment]
Guys, on master still does not work. 
> The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ApiGatewayRestApi] in the Resources block of the template

Workaround, I added:
```
resources:
  Parameters:
    ApiGatewayRestApi:
      Description: API REST Gateway
      Type: String
      Default: '[ID]'
```
+ https://github.com/serverless/serverless/pull/4897
