### ISSUE TITLE
Support authorization scopes for COGNITO_USER_POOLS authorizer

### ISSUE THREAD

**Issue by davidduffett** [serverless/serverless#4661]
# This is a Feature Proposal

## Description

When using client credentials flow with Cognito, API Gateway provides the `authorizationScopes` property on the API Gateway Method to match against scopes in the access token.

This is currently only supported by the API Gateway API, and not yet by CloudFormation, which I'm guessing is why it is not yet supported by Serverless. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html

Probably best to wait for CloudFormation to catch up on this so I'm just registering as a future task.

Additional config may take shape in the form of a `authorizationScopes` list property underneath `authorizer`:

```yml
functions:
  myFunction:
    events:
      - http:
          authorizer:
            arn: arn:aws:cognito-idp:ap-southeast-2:XXXXXXXXXXXX:userpool/ap-southeast-2_XXXXXXXXX
            authorizationScopes:
              - myScope1
              - myScope2
```

**Comment by raphadko** [comment]
+1

**Comment by bmccann36** [comment]
+1

**Comment by Sarcasmonaut** [comment]
+1

**Comment by akuchar** [comment]
Do it finally!!!!

**Comment by LucasBadico** [comment]
Any news on this?

**Comment by aoggz** [comment]
Has anyone posted on the AWS forums requesting this feature be implemented in CloudFormation? I haven't found anything

**Comment by hotgazpacho** [comment]
It looks like this is possible via API calls. Specifically [`putMethod`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html#putMethod-property) in the JS SDK. According to the [API Docs](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/method-update/), it would have to be 2 calls: the first to remove the existing `authorizationScopes` and the second to set the new value. `op:replace` is not supported for this key.

Some enterprising individual could probably write a serverless plugin that hooks into the post-deploy event, as many other plugins do, to make this happen.

**Comment by mdanku** [comment]
Here is a plugin that handles it:
https://github.com/birdcatcher/serverless-oauth-scopes

**Comment by mattbryce93** [comment]
> Here is a plugin that handles it:
> https://github.com/birdcatcher/serverless-oauth-scopes

Works perfectly, thanks @mdanku !! This should really just be brought into the main project as it really helps!

**Comment by gwosty** [comment]
doesn't work for me :( 

AWSOAuthScope: /api/something/{input+} : GET : api/something
 
  Type Error ---------------------------------------------
 
  Cannot read property 'id' of undefined

**Comment by mattbryce93** [comment]
@gwosty this is what I tested and managed to get it working if it's at all helpful :S
```
plugins:
  - serverless-oauth-scopes

service:
  name: Cognito-Authentication-Test

custom:
  stage: dev

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          integration: lambda
          scopes: [aws.cognito.signin.user.admin]
          authorizer:
            name: authorizer
            arn: <redacted>
            identitySource: method.request.header.Authorization
```

> > Here is a plugin that handles it:
> > https://github.com/birdcatcher/serverless-oauth-scopes
> 
> doesn't work for me :(
> 
> AWSOAuthScope: /api/something/{input+} : GET : api/something
> 
> Type Error ---------------------------------------------
> 
> Cannot read property 'id' of undefined

**Comment by mikemckibben** [comment]
Looks like CloudFormation supports this now with `AuthorizationScopes` property on the AWS::ApiGateway::Method type (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html)

I was able to add scopes by manually overriding the method resource in the `resources` section, replacing ` {ServerlessResourceMethodName}` from the below snippet with the serverless generated name for the api gateway method (using `serverless package` to look at the generated cloudformation template was useful in discovering the correct resource name for the method)

```
resources:
  Resources:
      {ServerlessResourceMethodName}:
        Type: "AWS::ApiGateway::Method"
        Properties:
          AuthorizationScopes:
            - "myscope"
```

**Comment by gwosty** [comment]
@mattbryce93 thanks for the example. It looks like I forgot the array brackets. It still doesn't work though. Could it be that it's because I have a proxy resource? 

```
AWSOAuthScope: /co2/xml/{chassis+} : GET : api/co2
 
  Type Error ---------------------------------------------
 
  Cannot read property 'id' of undefined
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'id' of undefined
    at setOAuthScopes (/builds/CRP/CRP/backend/co2/node_modules/serverless-oauth-scopes/index.js:37:86)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

@mdanku do you have any idea why this fails?

**Comment by mdanku** [comment]
@gwosty It looks like it isn't able to find a resource item with path matching the defined path in your serverless config.  Try adding some logging to your local copy of serverless-oauth-scopes/index.js to see if that helps.  Log the value of "path" after line 29 and the value of "resp.items" after line 36.

**Comment by gwosty** [comment]
@mdanku i did what you suggested. It looks like it fails because in index.js we retrieve stage name as
`const stage = serverless.service.provider.stage;`

This only works if the stage is set inside serverless.yml. It doesn't seam to work if you pass the stage name as a CLI option. I'm looking for a fix now, do you know where the options are saved?

**Comment by djakaitis** [comment]
@mikemckibben can you clarify what you mean by 

> 'the serverless generated name for the api gateway method'

**Comment by herebebogans** [comment]
as per @mikemckibben comment the AuthorizationScopes property of "AWS::ApiGateway::Method" is now supported by cloudformation.

Time to bring this into apigateway http event natively?

**Comment by Roustalski** [comment]
Until this is implemented, we have decided to use an environment variable as a workaround:
```
...
authorizer:
    handler: ...
    environment:
      SCOPES: [your,scopes,here]
```
