### ISSUE TITLE
Invoke local for Python can not run handler in subpackage

### ISSUE THREAD

**Issue by herophuong** [serverless/serverless#4663]
# This is a Bug Report

## Description

* What went wrong?

    When I put my python handler function in a subpackage, `invoke local` can not run it.

* What did you expect should have happened?

    `invoke local` should be able to run it, the same as on AWS.

* What was the config you used?

```yaml
functions:
  events-sqs-queuehandler:
    handler: events.sqs.queuehandler.handler
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.25.0
* ***Operating System***: Docker
* ***Stack Trace***:
```
Traceback (most recent call last):
  File "/usr/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 61, in <module>
    handler = getattr(module, args.handler_name)
AttributeError: module 'events' has no attribute 'sqs'
```

**Comment by dfee** [comment]
I just ran into this, too. Is there a work-around – I'm struggling to think of one without re-inventing a huge swath of `invoke local` functionality.

**Comment by dfee** [comment]
FWIW, this is definitely a bug, but solvable through a crude method that looks like the following:

```yaml
# serverless.yaml
functions:
  task_runner:
    handler: invoke-proxy.invoke
    # handler: xyz.scripts.task.entrypoint
```

```python
# /invoke-proxy.py
from xyz.scripts.task import entrypoint
```
