### ISSUE TITLE
Sls deploy -s test => "stack with id XX does not exist"

### ISSUE THREAD

**Issue by yonahforst** [serverless/serverless#4685]
# This is a Bug Report

## Description
In my serverless.yml, I’m setting an environment variable like so:
`USERPOOL_ARN: ${cf:${self:provider.environment.STACK_NAME}.UserPoolArn}`

Works fine when I deploy to the default stage, but when I try to deploy to a different stage, I get an error saying stack does not exist. I checked in cloudformation and the stack definitely exists.

However, this works:
`AWS_PROFILE=testProfile sls deploy -s test`

## Additional Data
```
  Serverless Error ---------------------------------------
 
  Stack with id physician-manager-test does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.6.0
     Serverless Version:     1.16.0
 ```

**Comment by RyanMcDonald** [comment]
It sounds like Serverless is using the wrong AWS account when it tries to deploy, and by using `AWS_PROFILE=testProfile` you're forcing it to use the correct one.

Do you specify the profile with the `profile` property in your serverless.yml? Otherwise it will use the `default` profile. Does adding `profile: testProfile` in serverless.yml fix it?

**Comment by yonahforst** [comment]
I have my profiles setup like so:
```
custom:
  defaultStage: dev
  profiles:
    dev: devProfile
    test: testProfile
    prod: prodProfile
  stage: ${opt:stage, self:custom.defaultStage}

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30
  memorySize: 128
  stage: ${self:custom.stage}
  profile: ${self:custom.profiles.${self:custom.stage}}
```
