### ISSUE TITLE
Error overriding AWS Lambda resource configuration

### ISSUE THREAD

**Issue by nykolaslima** [serverless/serverless#4691]
I'm trying to define the `DependsOn` attribute of a lambda function but when running the `serverless deploy` I'm getting an error:

Here is my serverless.yml configuration:
```
functions:
  graphql:
    handler: functions/graphql.execute
    events:
    - http:
        path: /graphql
        method: post

  otherFunction:
    handler: functions/other.execute
    events:
    - http:
        path: /other
        method: post


resources:
  Resources:
    otherFunctionLambdaFunction:
      Type: AWS::Lambda::Function
      DependsOn: graphqlLambdaFunction
```

The thrown error:
```
TypeError: Cannot read property 'Code' of undefined
    at _.forEach (/home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:13:26)
    at /home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:3001:24)
    at /home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:9359:14)
    at Object.normalizeCloudFormationTemplate (/home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:10:7)
    at AwsDeploy.checkIfDeploymentIsNecessary (/home/travis/.nvm/versions/node/v6.5.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:89:45)
```

Looks like this happens because I'm not defining the `Code` attribute of my resource, because the [`normalizeCloudFormation`](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/normalizeFiles.js#L13) function always try to reset the `S3Key` attribute of Lambda Resources.

Is this really a bug or I must always define the `Properties.Code` attribute?
