### ISSUE TITLE
Package Artifact Not Working as Described

### ISSUE THREAD

**Issue by kinmanlam** [serverless/serverless#4692]
Hello,

I'm attempting to deploy a Python script as a service. This Python script requires libraries which I have built and packaged using an Amazon Linux EC2. I have verified the zip file works if I manually deploy it.

In my serverless.yml:
```
service:
    name: python-lambda
package:
    artifact: deployment-pkg.zip
```

EXPECTATION:
Based on the documentation, this should override the default packaging behavior and instead simply use the deployment-pkg.zip as is, and deploy the deployment-pkg.zip as the end result to my lambda function.

deployment-pkg.zip gets repackaged as python-lambda.zip contents being:
```
-libdep1\
-libdep2\
-source.py
```

REALITY:
I inspect the ./serverless folder which contains the deploy package the python-lambda.zip contents are:
```
-deployment-pkg.zip
-source.py
```

The overall result is when this package gets deploy, my lambda function complains it cannot find it's dependencies as that deployment package is not correctly structured.

I am running the latest version of serverless 1.26.0

**Comment by snurmine** [comment]
Tested with master (06c82220cfd368adf9110b0e00d8659cdc28960e), but `serverless package` didn't generate zip under .serverless. 
```
service: env-test
  
package:
  artifact: foo.zip
provider:
  name: aws
  runtime: nodejs6.10

```
zoo.zip:
```
foo/lib1/
foo/lib2/
foo/source.py
foo/lib1/lib.py
foo/lib2/lib2.py
```
