### ISSUE TITLE
Feature Proposal: Restricting alexaSkill function invocations by skill id

### ISSUE THREAD

**Issue by kobim** [serverless/serverless#4700]
# This is a Feature Proposal

## Description

Alexa skills can run any lambda ARNs, given default execution permissions. The [official documentation](https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-an-aws-lambda-function.html#configuring-the-alexa-skills-kit-trigger) encourages setting an "EventSourceToken" (Alexa Skill ID) for each Alexa lambda function, to avoid verifying that the request was intended for your function.

As of today, the following configuration is present:
```yaml
functions:
  alexa:
    handler: handler.alexa
    events:
      - alexaSkill
```

I suggest adding optional parameters for the Alexa skill ID and function status (just like the [alexaSmartHome](https://www.serverless.com/framework/docs/providers/aws/events/alexa-smart-home) event):
```yaml
functions:
  alexa:
    handler: handler.alexa
    events:
      - alexaSkill: amzn1.ask.skill.5ac5b15a-ee34-44d8-97d1-d1c1c658102a
  anotherAlexaSkill:
    handler: handler.anotherAlexaSkill
    events:
      - alexaSkill:
          appId: amzn1.ask.skill.5ac5b15a-ee34-44d8-97d1-d1c1c658102a
          enabled: false
```

## Additional Data

* Maybe add some warning during deployment if this parameter is omitted, in order to encourage people to use it.
