### ISSUE TITLE
Serverless 1.26 doesn't set default API Gateway response template

### ISSUE THREAD

**Issue by 18BEA442** [serverless/serverless#4705]
# This is a Bug Report

## Description
After upgrading from Serverless 1.25.0 to Serverless 1.26.0, response templates are not set anymore in API Gateway.
* Here is a deployment made with 1.25.0: https://postimg.org/image/r6530fb1n/
* Here is the very same deployment made with 1.26.0: https://postimg.org/image/q3uwhvzy3/

You'll notice the difference in the bottom half: no _Integration Response_ and no _Method Response_.
I believe this is a bug because I found no mention of this change in the changelog.

* What went wrong?
 _Integration Response_ and _Method Response_ are not set. So when I invoke an endpoint, I get an error message "Internal server error", which in the API Gateway logs corresponds to "Execution failed due to configuration error: No match for output mapping and no default output mapping configured"

* What did you expect should have happened?
 _Integration Response_ and _Method Response_ should be set with sensible default values, like in Serverless 1.25.0

* What was the config you used?
Here it is, I removed most functions for the sake of briefness:
```
service: apiBO

# https://serverless.com/framework/docs/providers/aws/guide/version/
frameworkVersion: "^1.25.0"

# documentation about getting variables from CLI, file, etc.: https://github.com/serverless/serverless/pull/1834
custom:
  deployStage: ${opt:stage, self:provider.stage}
  envVarCommon: ${file(config/env-variables-common.json)}
  writeEnvVars:
    SERVERLESS_PROJECT_NAME: ${self:custom.envVarCommon.projectName}
    SERVERLESS_REGION: ${self:provider.region}
    SERVERLESS_STAGE: ${self:custom.deployStage}
    SERVERLESS_TABLE_NAME_PREFIX: [removed]-api-${self:custom.deployStage}-
    SERVERLESS_MANDRILL_KEY: ${self:custom.envVarCommon.mandrillKey}
    SERVERLESS_MANDRILL_KEY_TEST: ${self:custom.envVarCommon.mandrillKeyTest}

plugins:
  - serverless-plugin-write-env-vars

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 30
  cfLogs: true

  iamRoleStatements:
    # IamPolicyDynamoDB
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource: arn:aws:dynamodb:us-east-1:[removed]:table/[removed]-api-${self:custom.deployStage}-*
    # IamPolicyDynamoDBStreams
    - Effect: Allow
      Action:
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:us-east-1:[removed]:table/[removed]-api-${self:custom.deployStage}-*
    # IamPolicyCognitoUnAuth
    - Effect: Allow
      Action:
        - "mobileanalytics:PutEvents"
        - "cognito-sync:*"
      Resource: "*"
    # IamPolicyCognitoAuth
    - Effect: Allow
      Action:
        - execute-api:Invoke
        - lambda:InvokeFunction
      Resource: "*"
    # To access S3 buckets
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "*"

package:
  excludeDevDependencies: true
  exclude:
    - .npmignore
    - config/**
    - dts/**
    - package.json
    - package-lock.json
    - readme.md
    - slslocal.sh
    - tsconfig.json
    - events/**
    - '*.bat'
    - '*.ts'
    - '**/*.ts'
    - node_modules/.bin/**

functions:
  account:
    memorySize: 512
    timeout: 10
    handler: haccount.handler
    name: ${self:custom.envVarCommon.projectName}-${self:custom.deployStage}-account
    description: BO account things (login, logout...)
    tags:
      api: BO
    events:
      - http:
          path: login
          method: post
          integration: lambda
          cors:
            origins:
              - '*'
          request:
            template:
              application/json: ${file(config/apiGatewayRequestTemplate.txt)}
            passThrough: WHEN_NO_MATCH
            parameters:
              query:
                body: true
      - http:
          path: logout
          method: post
          integration: lambda
          cors:
            origins:
              - '*'
            headers:
              - sessionToken
              - Content-Type
          request:
            template:
              application/json: ${file(config/apiGatewayRequestTemplate.txt)}
            passThrough: WHEN_NO_MATCH
      - http:
          path: account/ping
          method: get
          integration: lambda
          request:
            template:
              application/json: ${file(config/apiGatewayRequestTemplate.txt)}
            passThrough: WHEN_NO_MATCH
      - http:
          path: mirror
          method: post
          integration: lambda
          cors:
            origins:
              - '*'
            headers:
              - sessionToken
              - Content-Type
          request:
            template:
              application/json: ${file(config/apiGatewayRequestTemplate.txt)}
            passThrough: WHEN_NO_MATCH

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}
        Description: API back-office (${self:custom.deployStage} stage)
```

* What stacktrace or error message from your provider did you see?
No particular error, here is the deployment log with `SLS_DEBUG=*`:
```
$ sls deploy --aws-s3-accelerate                                                                                                       
Serverless: Load command run                                                                                                           
Serverless: Load command config                                                                                                        
Serverless: Load command config:credentials                                                                                            
Serverless: Load command create                                                                                                        
Serverless: Load command install                                                                                                       
Serverless: Load command package                                                                                                       
Serverless: Load command deploy                                                                                                        
Serverless: Load command deploy:function                                                                                               
Serverless: Load command deploy:list                                                                                                   
Serverless: Load command deploy:list:functions                                                                                         
Serverless: Load command invoke                                                                                                        
Serverless: Load command invoke:local                                                                                                  
Serverless: Load command info                                                                                                          
Serverless: Load command logs                                                                                                          
Serverless: Load command login                                                                                                         
Serverless: Load command logout                                                                                                        
Serverless: Load command metrics                                                                                                       
Serverless: Load command print                                                                                                         
Serverless: Load command remove                                                                                                        
Serverless: Load command rollback                                                                                                      
Serverless: Load command rollback:function                                                                                             
Serverless: Load command slstats                                                                                                       
Serverless: Load command plugin                                                                                                        
Serverless: Load command plugin                                                                                                        
Serverless: Load command plugin:install                                                                                                
Serverless: Load command plugin                                                                                                        
Serverless: Load command plugin:uninstall                                                                                              
Serverless: Load command plugin                                                                                                        
Serverless: Load command plugin:list                                                                                                   
Serverless: Load command plugin                                                                                                        
Serverless: Load command plugin:search                                                                                                 
Serverless: Load command emit                                                                                                          
Serverless: Load command config                                                                                                        
Serverless: Load command config:credentials                                                                                            
Serverless: Load command rollback                                                                                                      
Serverless: Load command rollback:function                                                                                             
Serverless: Invoke deploy                                                                                                              
Serverless: Invoke package                                                                                                             
Serverless: Invoke aws:common:validate                                                                                                 
Serverless: Invoke aws:common:cleanupTempDir                                                                                           
Serverless: Wrote .env file to [path]\[removed]\API\apiBO\.env                                                                             
Serverless: Packaging service...                                                                                                       
Serverless: Excluding development dependencies...                                                                                      
Serverless: Deleted .env file from [path]\[removed]\API\apiBO\.env                                                                         
Serverless: Invoke aws:package:finalize                                                                                                
Serverless: Invoke aws:common:moveArtifactsToPackage                                                                                   
Serverless: Invoke aws:common:validate                                                                                                 
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: WARNING: Function [removed] has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 
30 seconds.                                                                                                                            
Serverless: Invoke aws:deploy:deploy                                                                                                   
Serverless: Uploading CloudFormation file to S3...                                                                                     
Serverless: Using S3 Transfer Acceleration Endpoint...                                                                                 
Serverless: Uploading artifacts...                                                                                                     
Serverless: Uploading service .zip file to S3 (318.64 KB)...                                                                           
Serverless: Using S3 Transfer Acceleration Endpoint...                                                                                 
Serverless: Validating template...                                                                                                     
Serverless: Updating Stack...                                                                                                          
Serverless: Checking Stack update progress...                                                                                          
..................                                                                                                                     
Serverless: Stack update finished...                                                                                                   
Serverless: Invoke aws:info                                                                                                            
Service Information                                                                                                                    
service: apiBO                                                                                                                         
stage: dev                                                                                                                             
region: us-east-1                                                                                                                      
stack: apiBO-dev                                                                                                                       
api keys:                                                                                                                              
  None                                                                                                                                 
endpoints:                                                                                                                             
  POST - https://[removed].execute-api.us-east-1.amazonaws.com/dev/login                                                              
  POST - https://[removed].execute-api.us-east-1.amazonaws.com/dev/logout                                           
  GET - https://[removed].execute-api.us-east-1.amazonaws.com/dev/account/ping       
  [I removed the rest]  
functions:                                                                                                                
  [removed]: apiBO-dev-[removed]       
  [I removed the rest]    
Serverless: Invoke aws:deploy:finalize                                                                                                 
Serverless: Removing old service versions...                                                                                           
```

Similar or dependent issues:
I haven't found any

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0 (works with 1.25.0)
* ***Operating System***: Windows 7/10 x64, Node 8.9.4 LTS
* ***Stack Trace***: cf above
* ***Provider Error messages***: as mentioned above: "Execution failed due to configuration error: No match for output mapping and no default output mapping configured"

**Comment by dashmug** [comment]
I had this problem as well.

**Comment by ztmdsbt** [comment]
I faced this problem too.

**Comment by ztmdsbt** [comment]
This issue may not caused by serverless. I tried to downgrade serverless to 1.25.0, 1.24.1, 1.23.0. both not working.
Below is the deploy logs:
``` log
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (38.28 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......................................................................................................................................................
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: vehicle-api-V1-1-24-1-second
stage: test
region: ap-southeast-2
stack: vehicle-api-V1-1-24-1-second-test
api keys:
  vehicle-api-V1-1-24-1-second-test-token: am0Dal3Tzq5J5MCVIzck91gOfRZGK4Is3GaK2ema
endpoints:
  PUT - https://iv19diaxob.execute-api.ap-southeast-2.amazonaws.com/test/V1-1-24-1-second/vehicle/updateContact
  GET - https://iv19diaxob.execute-api.ap-southeast-2.amazonaws.com/test/V1-1-24-1-second/vehicle/types
  GET - https://iv19diaxob.execute-api.ap-southeast-2.amazonaws.com/test/V1-1-24-1-second/vehicle/types/{type}/makes
  GET - https://iv19diaxob.execute-api.ap-southeast-2.amazonaws.com/test/V1-1-24-1-second/vehicle/types/{type}/makes/{make}/models
  GET - https://iv19diaxob.execute-api.ap-southeast-2.amazonaws.com/test/V1-1-24-1-second/vehicle/types/{type}/makes/{make}/models/{model}/years
  GET - https://iv19diaxob.execute-api.ap-southeast-2.amazonaws.com/test/V1-1-24-1-second/vehicle/types/{type}/makes/{make}/models/{model}/years/{year}/colors
functions:
  updateContact: vehicle-api-V1-1-24-1-second-test-updateContact
  getTypes: vehicle-api-V1-1-24-1-second-test-getTypes
  getMakes: vehicle-api-V1-1-24-1-second-test-getMakes
  getModels: vehicle-api-V1-1-24-1-second-test-getModels
  getYears: vehicle-api-V1-1-24-1-second-test-getYears
  getColors: vehicle-api-V1-1-24-1-second-test-getColors
Serverless: Invoke aws:deploy:finalize
```
Below is  the serverless.yml:
``` yaml
service: vehicle-api-${self:custom.version}

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  memorySize: 128
  timeout: 15
  environment:
    NODE_ENV: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
  vpc:
      securityGroupIds:
        - Ref: vehicleApiSecurityGroup
      subnetIds:
        "Fn::Split":
          - ","
          - ${opt:subnetId}
  apiKeys:
    - ${self:service}-${opt:stage}-token
resources:
  Resources:
    vehicleApiSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group which allows access on ports 80 but only to machines of this security group.
        VpcId: ${opt:vpcId}
        SecurityGroupIngress:
          -
            IpProtocol: TCP
            CidrIp: 0.0.0.0/0
            FromPort: 80
            ToPort: 80

package:
 exclude:
   - .gitignore
   - package.json
   - test/**
   - developmentServer.js
   - .git
   - .vscode/
   - node_modules/.bin/**

custom:
  version: V1-1-24-1-second
  serviceName:  ${self:service} 

functions:
  updateContact:
    handler: handler.updateContact
    events:
      - http:
          path: /${self:custom.version}/vehicle/updateContact
          method: put
          integration: lambda
          response:
            headers:
              Content-Type: "'application/JSON'"
  getTypes:
    handler: handler.search
    events:
      - http:
          path: /${self:custom.version}/vehicle/types
          method: get
          private: true
          integration: lambda
  getMakes:
    handler: handler.search
    events:
      - http:
          path: /${self:custom.version}/vehicle/types/{type}/makes
          method: get
          private: true
          integration: lambda
  getModels:
    handler: handler.search
    events:
      - http:
          path: /${self:custom.version}/vehicle/types/{type}/makes/{make}/models/
          method: get
          private: true
          integration: lambda
  getYears:
    handler: handler.search
    events:
      - http:
          path: /${self:custom.version}/vehicle/types/{type}/makes/{make}/models/{model}/years
          method: get
          private: true
          integration: lambda
  getColors:
    handler: handler.search
    events:
      - http:
          path: /${self:custom.version}/vehicle/types/{type}/makes/{make}/models/{model}/years/{year}/colors
          method: get
          private: true
          integration: lambda

plugins:
  - serverless-offline

```
