### ISSUE TITLE
"no such file or directory" when executing Go function in AWS Lambda

### ISSUE THREAD

**Issue by Napas** [serverless/serverless#4710]
When running my Lambda function I get this error:

`START RequestId: 3df5e64a-0863-11e8-903f-919b29535603 Version: $LATEST
fork/exec /var/task/bin/ping: no such file or directory: PathError
null
END RequestId: 3df5e64a-0863-11e8-903f-919b29535603
REPORT RequestId: 3df5e64a-0863-11e8-903f-919b29535603	Duration: 0.21 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 12 MB	`

I did check zip file in S3 - it has an executable in it ./bin/ping

Any ideas how to solve that?

My serverless.yml
```
service: ping
provider:
  name: aws
  runtime: go1.x
  stage: staging
  region: us-east-1
  memorySize: 128
  timeout: 1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  ping:
    handler: bin/ping
    events:
      - http:
          path: ping
          method: get
          private: false
```

my ping/main.go file:

```
package main

import (
	"github.com/aws/aws-lambda-go/lambda"
	"time"
	"github.com/aws/aws-lambda-go/events"
	"encoding/json"
)

// Response object
type Response struct {
	Payload string            `json:"Payload"`
	Meta    map[string]string `json:"Meta"`
}

// Ping handles ping response
func Ping(request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	meta := make(map[string]string)
	meta["CreatedAt"] = time.Now().Format(time.RFC3339);
	resp := Response{
		Payload: "Pong",
		Meta: meta,
	}

	body, _ := json.Marshal(resp)

	return events.APIGatewayProxyResponse{
		StatusCode: 200,
		Body: string(body),
	}, nil
}

func main() {
	lambda.Start(Ping)
}
```
