### ISSUE TITLE
Serverless Error ---- No .serverless/*.zip file found in the package path you provided

### ISSUE THREAD

**Issue by ryub3n** [serverless/serverless#4720]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
Serverless deploy on AWS CodeBuild using an artifact from s3 caused a Serverless Error **No .serverless/*.zip** found
* What did you expect should have happened?
The CF stack should've been created.
* What was the config you used?
My config is big and it deployed the package correctly when I ran serverless deploy from my laptop using AWS profile.
* What stacktrace or error message from your provider did you see?
[log.txt](https://github.com/serverless/serverless/files/1694866/log.txt)
I'm calling serverless deploy in the build phase and it copies my package contents to the .serverless folder and then says it can't find it. I've even listed the contents of the folder and can see it.

My artifact comes from s3 and it's a zip file with the below contents:
- employee-service-sls-dev
- employee-service-sls-stg
- buildspec.yml
- package.json
- serverless.config.dev.yml
- serverless.config.stg.yml
- serverless.yml
- sls

I even tried invoking it from post_build with no luck.

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: Ubuntu container with nodejs6.3.1 but the project uses nodejs6.10
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by ryub3n** [comment]
Seems to be an issue with "package individually: true" which I set only at service level. When I removed it the deployment works fine using CodeBuild but my functions are not packed individually which I need.

**Comment by kendrickkesley** [comment]
Hi @ryub3n ! I recently stuck with the same problem as you! As a work around, I can use package:individually in the service level and use include/exclude in the function level.

**Comment by Kexerval** [comment]
Just had this happen to me using the latest version of serveless while using the serverless lambda@edge plugin. Setting package:individually at the service level fixed my issue! Thanks @kkesley

**Comment by dennisjade** [comment]
After I upgrade to the latest(1.32) I got this same issue and removing the individually: true somewhat fixes the issue. But then I have to specify that in every function

**Comment by nkhine** [comment]
serverless@1.39.0 also breaks this, here is part of my serverless.yml

```
service: apis

plugins:
  - serverless-parameters
  - serverless-pseudo-parameters
  - serverless-plugin-tracing
  - serverless-iam-roles-per-function
provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:getObject
        - s3:putObject
        - s3:GetObjectVersion
        - s3:ListBucketVersions
        - s3:putBucketPolicy
        - states:startExecution
      Resource: "*"
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  stage: ${opt:stage}
  region: ${file(./config.yml):${opt:stage}.REGION}
  tracing: true # enable tracing

package:
  individually: true
  exclude:
    - ./**

functions:
  status:
    handler: bin/status
    description: Status/healthcheck function for API
    memorySize: 128
    package:
      individually: true
      include:
        - ./bin/status
    events:
      - http:
          path: status
          method: get
    timeout: 30
```

on serverless@1.39.0 i get:

```
  Serverless Error ---------------------------------------
 
  No status.zip file found in the package path you provided.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.11.2
     Serverless Version:     1.39.0
 
Makefile:23: recipe for target 'deploy' failed
make: *** [deploy] Error 1
```

downgrading to serverless@1.38.0 works

**Comment by cheesiangcs** [comment]
> serverless@1.39.0 also breaks this, here is part of my serverless.yml
> 
> ```
> service: apis
> 
> plugins:
>   - serverless-parameters
>   - serverless-pseudo-parameters
>   - serverless-plugin-tracing
>   - serverless-iam-roles-per-function
> provider:
>   name: aws
>   runtime: go1.x
>   iamRoleStatements:
>     - Effect: Allow
>       Action:
>         - s3:getObject
>         - s3:putObject
>         - s3:GetObjectVersion
>         - s3:ListBucketVersions
>         - s3:putBucketPolicy
>         - states:startExecution
>       Resource: "*"
>     - Effect: "Allow" # xray permissions (required)
>       Action:
>         - "xray:PutTraceSegments"
>         - "xray:PutTelemetryRecords"
>       Resource:
>         - "*"
>   stage: ${opt:stage}
>   region: ${file(./config.yml):${opt:stage}.REGION}
>   tracing: true # enable tracing
> 
> package:
>   individually: true
>   exclude:
>     - ./**
> 
> functions:
>   status:
>     handler: bin/status
>     description: Status/healthcheck function for API
>     memorySize: 128
>     package:
>       individually: true
>       include:
>         - ./bin/status
>     events:
>       - http:
>           path: status
>           method: get
>     timeout: 30
> ```
> on serverless@1.39.0 i get:
> 
> ```
>   Serverless Error ---------------------------------------
>  
>   No status.zip file found in the package path you provided.
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Issues:        forum.serverless.com
>  
>   Your Environment Information -----------------------------
>      OS:                     linux
>      Node Version:           8.11.2
>      Serverless Version:     1.39.0
>  
> Makefile:23: recipe for target 'deploy' failed
> make: *** [deploy] Error 1
> ```
> downgrading to serverless@1.38.0 works

Encountered the same problem after v1.39...
Downgrading to v1.38 works for now..

#5931

**Comment by brainstorm** [comment]
I can confirm this bug, works fine with 1.38.x and breaks on 1.39.x (see referenced commit/issue right above) :/

**Comment by brainstorm** [comment]
Related with https://github.com/serverless/serverless/issues/5931

**Comment by joshtrotter** [comment]
Same here - encountering this on 1.39.0, works fine on 1.38.0

**Comment by aidinkhosrowshahi** [comment]
I have same issue too, it was working before but started failing

Serverless: [AWS s3 200 0.058s 0 retries] getBucketLocation({ Bucket: '*******-artifacts-us-east-1' })
 Serverless Error ---------------------------------------
 No *****.zip file found in the package path you provided.

Serverless Version: 1.39.0

**Comment by janpoltan** [comment]
I have this issue also in 1.39.0

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  No ######.zip file found in the package path you provided.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.39.0
 
Exited with code 1
```

**Comment by shierro** [comment]
same issue with previous 2 comments. it's weird since when I check the `.serverless.zip` file, it contains the missing zip file mentioned by the error stack trace

**Comment by calexandrepcjr** [comment]
Only happens on >1.39.0

**Comment by nikita-clearscale** [comment]
Any news? Any workariunds? I have downgraded to `1.38.0` and got same issue :(

**Comment by anil-grexit** [comment]
It's happening in the version 1.54.0 as well. I am using CodeBuild to package and deploy the functions individually on a service level rather than funciton level. I can do `ls -l` in the CodeBuild logs to see the contents but the deployment fails with the error that `No function.zip is found in the path package you provided`.

Any help is appreciated.

**Comment by warapitiya** [comment]
Any workarounds?

**Comment by MichaelGoberling** [comment]
This is STILL happening in 1.67.0. I am using Azure Pipelines to try to deploy the functions individually on a service level. I can see the zip files in the .serverless directory in the logs, but the deployment fails with `No function.zip is found in the path package you provided`.

This is a total deal breaker if you're trying to implement a workflow to pull down the latest staging artifacts and deploy them to production. I can't believe this has zero visibility or responses.

**Comment by sschulze** [comment]
Looks like the absolute path to the packaged artifacts is written in the serverless-state.json. Due to this the package isn't portable anymore.
I think the fix should be to write the artifact paths relative to the package-root into the serverless-state.json.
In the case that the user provided an explicit artifact path in serverless.yml I guess it should be copied into the package directory. This way the artifact stays portable and archivable.

As a workaround I'll try to rewrite the serverless-state.json during deployment. But it's rather ugly....  :-(

**Comment by jack-morrissey-calabrio** [comment]
Having the exact same problems as @MichaelGoberling and would prefer not to go down the route @sschulze. Any updates now?

**Comment by medikoo** [comment]
@MichaelGoberling @jack-morrissey-calabrio please report at https://github.com/serverless/serverless-azure-functions

**Comment by aychtang** [comment]
@medikoo This happens also on my jenkins environment and the original user was using codebuild, I'm not sure if such issue should be pushed to azure specific issues.

**Comment by aychtang** [comment]
In other news I moved my service level `package` properties into the function level and now it works. Not sure what is happening there...

Before (throws missing zip error):
```
package:
  individually: true
  exclude: - "*/**"

fn:
  package:
    include: []
..
```

After (now working):
```
fn:
  package:
    individually: true
    exclude: - "*/**"
    include: []
..
```
