### ISSUE TITLE
Unable to Deploy to AWS Gov Cloud Region

### ISSUE THREAD

**Issue by jseiser** [serverless/serverless#4726]
# This is a (Bug Report / Feature Proposal)
Bug Report

## Description
For bug reports:
* What went wrong?

> Unable to deploy services to AWS Gov Cloud

* What did you expect should have happened?

Expected service to deploy like it has for other accounts/regions

* What was the config you used?
```
service: ec2CloudWatchAlarms

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  timeout: 120
  memorySize: 1536
  deploymentBucket:
    name: stuff-${opt:region, self:provider.region}-${ssm:accountID}-serverless
  environment:
    commonSNS: ${ssm:commonSNS}
    urgentSNS: ${ssm:urgentSNS}
    accountID: ${ssm:accountID}
    jiraSNS:   ${ssm:jiraSNS}
    region:    ${opt:region, self:provider.region}
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "ec2:*"
       - "cloudwatch:*"
       - "iam:CreateServiceLinkedRole"
     Resource: "*"

package:
  exclude:
    - .idea/**
    - .git/**

custom:
  enabled:
    dev: false
    prod: true

  alerts:
    stages:
      - dev
      - prod

    dashboards: true

    topics:
      alarm: ${ssm:jiraSNS}
    definitions:
      functionErrors:
        treatMissingData: notBreaching
      functionThrottles:
        treatMissingData: notBreaching
      functionInvocations:
        treatMissingData: notBreaching
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations

plugins:
  - serverless-plugin-aws-alerts

functions:
  ec2ScheduledEvent:
    handler: ec2ScheduledEvent.ec2alarms
    events:
      - cloudwatchEvent:
          description: 'CloudWatch Event triggered on EC2 Instance pending state'
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              state:
                - running

```
* What stacktrace or error message from your provider did you see?

> 
> I see two, they appear to happen at random.
>  
> 
>   The CloudFormation template is invalid: S3 error: The specified bucket does not exist
>  For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
>  
> or
>  
>  Stack with id ec2CloudWatchAlarms-prod does not exist
> 
## Additional Data
 

>     OS:                     linux
>      Node Version:           9.5.0
>      Serverless Version:     1.26.0
>
