### ISSUE TITLE
Dynamodb - Supported Data Types

### ISSUE THREAD

**Issue by marckaraujo** [serverless/serverless#4728]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
```
Serverless Error ---------------------------------------
  An error occurred: TeamDynamoDbTable - 1 validation error detected: Value 'SS' at 'attributeDefinitions.2.member.attributeType' failed to satisfy constraint: Member must satisfy enum value set: [B, N, S].
```
* What did you expect should have happened?
From Docs, Collections types are allowed: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html

```
Java type | DynamoDB type
All number types | N (number type)
Strings | S (string type)
Boolean | BOOL (boolean type), 0 or 1.
ByteBuffer | B (binary type)
Date | S (string type). The Date values are stored as ISO-8601 formatted strings.
Set collection types | SS (string set) type, NS (number set) type, or BS (binary set) type.
```

Config:
```
TeamDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: name
            AttributeType: S
          -
            AttributeName: members
            AttributeType: SS
        KeySchema:
          -
            AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
          WriteCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          -
            IndexName: members-index
            KeySchema:
              -
                AttributeName: members
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
              WriteCapacityUnits: ${self:custom.dynamodbProvisions.${self:provider.stage}}
        TableName: Team-${self:provider.stage}
```

* ***Serverless Framework Version you're using***: 1.25.0
