### ISSUE TITLE
Custom Variables in Plugins

### ISSUE THREAD

**Issue by jonathankeebler** [serverless/serverless#4735]
# This is a Feature Proposal

## Description

Currently a serverless.yml can contain [Variables from several sources](https://serverless.com/framework/docs/providers/aws/guide/variables/). For example, to include an environment variable in a statement, you can use the syntax:
```
${env:FUNC_PREFIX}-world
```
where FUNC_PREFIX is the environment variable.

I propose adding the ability for [Plugins](https://serverless.com/framework/docs/providers/aws/guide/plugins/) to support adding their own variable types. For example:
```
${custom_type:VARIABLE}
```
This would allow the serverless.yml to be cleaner by replacing duplicate statements as needed. For example, if config called for a timeout that is coming from a variable:
```
func1:
    handler: lambda.handler
    timeout: 10
func2:
    handler: lambda.handler
    timeout: 10
func3:
    handler: lambda.handler
    timeout: 10
```
it could be replaced with:
```
func1:
    handler: lambda.handler
    timeout: ${timeout:DEFAULT}
func2:
    handler: lambda.handler
    timeout: ${timeout:DEFAULT}
func3:
    handler: lambda.handler
    timeout: ${timeout:DEFAULT}
```
In the plugin library, I suggest the following syntax for defining the custom variable:
```js
class ServerlessPlugin {
  constructor(serverless, options) {
	this.variables = {
		timeout: {
			usage: 'Timeout values in seconds'
		  }
	};
	this.hooks = {
		"variable:timeout:initialize": this.replace_variable.bind(this)
	};
  }
}
```
A lifecycle event would trigger a hook called variable:VARIABLE_NAME:initialize which would fire when the value of the variable is needed. It will receive a single parameter with the value of the variable e.g. in this case of the "timeout" variable above, the value would be "DEFAULT".

Custom variables should resolve before built-in variables so they can use built in variables. For example: ${timeout:DEFAULT} could resolve with "${env:FUNC_PREFIX}" which would then be replaced with the environment variable FUNC_PREFIX.

Please post your comments below. Happy to implement this if everyone thinks it's a good idea.

Cheers!

**Comment by HyperBrain** [comment]
Hi @jonathankeebler . I'm not really sure what exactly the benefit is, of having a plugin capable variable system compared to the current one.

In  your example you can define the default timeout as follows:
```
custom:
  timeout:
    default: 10

functions:
  func1:
    handler: myhandler
    timeout: ${self:custom.timeout.default}
```

Instead of 10 you just can set `default: ${env:MY_TIMEOUT}`, so you can easily change every default timeout in one place. You can even reference variables in variable names to access different variables dynamically, as well as set default values for variables.

I do not see any advantage in having a plugin capability. It would even increase technical debt and is a very complex thing. You would have to think about variable dependencies, deferred resolution (variables return promises that eventually get resolved). Even the assumption that "Custom variables should resolve before built-in variables" is deterministic is wrong, because you easily can create circular references (which also are handled right now by the variable handling) or even self-references of the whole service.

Maybe I just do not see the concrete improvements, so I'd appreciate a discussion here.
