### ISSUE TITLE
read provider value defined in serverless.yml from the function

### ISSUE THREAD

**Issue by abdennour** [serverless/serverless#4740]
# Feature/Proposal
- As I programmer, I want to be able to read the value of "provider:" ( defined in serverless.yml)
## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

You may need to build a logic in your functions according to "provider" which is defined inside "serverless.yml".
     
* If there is additional config how would it look

```js
// POC
console.log(process.env.SERVERLESS_YAML_PROVIDER); // aws

```
## Additional Data
- My NPM module "serverless-http-interface" is a use case.

**Comment by alexdebrie** [comment]
Hey @abdennour, you can do this yourself with the existing variable syntax.

In your `serverless.yml`:

```yml
# serverless.yml

service: my-service

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  environment:
    SERVERLESS_YAML_PROVIDER: ${self:provider.name}

functions:
....
```

This will inject the `SERVERLESS_YAML_PROVIDER` environment variable into your function.

Because of that, I'm going to close this. Feel free to hit me up if you have any questions!
