### ISSUE TITLE
Resources with the same name in different accounts override each other => include account in names

### ISSUE THREAD

**Issue by jakubholynet** [serverless/serverless#4742]
# This is a Bug Report
### What went wrong?

I have an AWS Lambda function with two SNS events. Notice the topics have the same name but are in different accounts:

```yaml
functions:
  codedeploy-sns-notifications:
    events:
      - sns: arn:aws:sns:eu-west-1:1111111111111111:cd-sns-lambda # prod
      - sns: arn:aws:sns:eu-west-1:222222222222:cd-sns-lambda # stage
```

Serverless creates _only_ subscription for the latter and it tries to do so in both accounts. It also only grants the `InvokeLambda` permission to the latter.

The reason is that the name of the CloudFormation resources (the subscription and the permission) is based only on the function and topic names, ignoring that the topics are in different accounts, so the latter overrides the former.

The same problem would occur if they were in different regions (if it is possible).

This is the only subscription and only permission in the resulting CF template:

```yaml
# function: codedeploy-sns-notifications
# topic: cd-sns-lambda
CodedeployDashsnsDashnotificationsSnsSubscriptionCdsnslambda:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: 'arn:aws:sns:eu-west-1:222222222222:cd-sns-lambda'
      Protocol: lambda
      Endpoint: !GetAtt 
        - CodedeployDashsnsDashnotificationsLambdaFunction
        - Arn
CodedeployDashsnsDashnotificationsLambdaPermissionCdsnslambdaSNS:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt 
        - CodedeployDashsnsDashnotificationsLambdaFunction
        - Arn
      Action: 'lambda:InvokeFunction'
      Principal: sns.amazonaws.com
      SourceArn: 'arn:aws:sns:eu-west-1:222222222222:cd-sns-lambda'
```

I think it would be best to include e.g. a hash of the whole arn (up to the name) as a part of the CF names so that the name would be unique for resources in different accounts / regions / ... .
For the relevant code, see [`serverless/lib/plugins/aws/lib/naming.js`](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/lib/naming.js), namely `getLambdaSnsSubscriptionLogicalId` and `getTopicLogicalId`.

* What did you expect should have happened?

I expected to get subscription for 1111111111111111:cd-sns-lambda in the 1111111111111111 account and subscription for 222222222222:cd-sns-lambda in the 222222222222 account and to have InvokeLambda permission for both.

* What was the config you used?

See above.

Similar or dependent issues:
* #3676 
* 4637

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: OSX 10.13

**Comment by eric-dorsey** [comment]
Thank you @holyjak 

Adding to this bug, `topicName` is still required even when using the **same account** but across different regions. 

Use case was invoking a Lambda function from multiple SNS topics in different regions but same account number (and same SNS Topic Names). This is what eventually worked:

```
functions:
  SomeFunction:
    handler: main.lambda_handler
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:123456789012:SomeSNSTopic
          topicName: us-east-1
      - sns:
          arn: arn:aws:sns:us-east-2:123456789012:SomeSNSTopic
          topicName: us-east-2

```
