### ISSUE TITLE
Getting the following error: "Unresolved resource dependencies [GeneralPurposeContainerRole] in the Resources block of the template"

### ISSUE THREAD

**Issue by claudiadast** [serverless/serverless#4745]
Upon testing my cloudformation template, I was receiving the following error:
```
An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: Unresolved resource dependencies [GeneralPurposeContainerRole] in the Resources block of the template
```
I don't understand what specifically this error is pointing to. Below is the part of the template that appears to be the source of the error:

```
Resources:
  GeneralPurposeContainerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
            - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: ContainerS3Access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:List*
              Resource:
                # TODO: Make these non psychcore-specific
              - arn:aws:s3:::pipeline-validation/*
              - arn:aws:s3:::wgs-pipeline-vqsr-test/*
              - arn:aws:s3:::test-references/*
              - arn:aws:s3:::psychcore-pipelines/output/*
              - arn:aws:s3:::psychcore-pipelines/validation/samples/*
              - arn:aws:s3:::psychcore-data/reference_indexs/*
              - arn:aws:s3:::psychcore-pipelines
              - arn:aws:s3:::psychcore-pipelines
              - arn:aws:s3:::psychcore-data
              - arn:aws:s3:::*
            - Effect: Allow
              Action:
              - s3:List*
              - s3:ListMultipartUploadParts
              - s3:AbortMultipartUpload
              - s3:ListBucketMultipartUploads
              Resource:
              - arn:aws:s3:::pipeline-validation
              - arn:aws:s3:::wgs-pipeline-vqsr-test
              - arn:aws:s3:::test-references
              - arn:aws:s3:::psychcore-pipelines/output/
              - arn:aws:s3:::psychcore-pipelines/validation/samples/
              - arn:aws:s3:::psychcore-data/reference_indexs/
              - arn:aws:s3:::psychcore-pipelines
              - arn:aws:s3:::psychcore-pipelines
              - arn:aws:s3:::psychcore-data
              - arn:aws:s3:::*
```

**Comment by claudiadast** [comment]
Hi @HyperBrain! Thank you for the prompt response. Hmm, you could be right, although, we've never had an issue before from the lack of indentation in those nodes.

**Comment by HyperBrain** [comment]
I did not say that this solves the original problem :-D - maybe a second one.

Good that you mentioned the nested stack. So the original message `Unresolved resource dependencies [GeneralPurposeContainerRole]` seems to be emitted by the stack that references the resource, which is the parent stack.
I'm not an expert on these nested stacks, but isn't it so, that the nested stacks only can use resources from their parents and not vice versa?

**Comment by claudiadast** [comment]
Yes you are correct. So previously, I had everything in one stack template, including the GeneralPurposeContainerRole. But because I had hit the limit for max number of bytes, I had to disperse that single template into child templates and then call to them from within the master template. Part of that was creating a child stack called **batch.yaml**, which now contains the GeneralPurposeContainerRole. I was able to simply move it (as-is) to the child stack because GeneralPurposeContainerRole didn't get referenced anywhere else in the original template. That's why I was having trouble understanding the "dependencies" error.

**Comment by HyperBrain** [comment]
@claudiadast Great that I could help 😄 

Can we close this issue or is there anything left that you wish to discuss?

**Comment by claudiadast** [comment]
@HyperBrain, I'm still getting the same error but am still unsure why. When I try creating the stack it still shoots out the same error.

**Comment by HyperBrain** [comment]
@serverless/vip Anyone ran into this before? It would be great if you could help @claudiadast 😄

**Comment by laardee** [comment]
@claudiadast do you have the `Resources` under `resources`?
```
resources:
  Resources:
    GeneralPurposeContainerRole:
    Type: "AWS::IAM::Role"
    ....
```
