### ISSUE TITLE
Only one iamRoleStatement is getting parsed

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#4749]
# This is a Bug Report

## Description

* What went wrong?

Only a single `iamRoleStatement` is getting packaged in the CF yaml file.

* What did you expect should have happened?

`iamRoleStatements` should be able to accept multiple statements.

* What stacktrace or error message from your provider did you see?

No errors.

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: macOS 10.13.3
* ***Stack Trace***:
* ***Provider Error messages***:

Example:

```yaml
functions:
  searchIndexer:
    handler: indexer.handler
    name: ${self:provider.stage}-searchIndexer
    description: Indexes things in Algolia
    memorySize: 1024
    timeout: 10
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:ListStreams
          - dynamodb:DescribeStream
          - dynamodb:GetShardIterator
          - dynamodb:GetRecords
        Resource:
          Fn::GetAtt: [TracksTable, StreamArn]
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource:
          Fn::GetAtt: [TracksTable, Arn]
```

I can see in `.serverless/cloudformation-template-update-stack.json` that the `dynamodb:UpdateItem` action is missing entirely.

```json
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogStream"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:
log-group:/aws/lambda/dev-searchIndexer:*"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:PutLogEvents"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:
log-group:/aws/lambda/dev-searchIndexer:*:*"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "dynamodb:GetRecords",
                    "dynamodb:GetShardIterator",
                    "dynamodb:DescribeStream",
                    "dynamodb:ListStreams"
                  ],
                  "Resource": [
                    {
                      "Fn::GetAtt": [
                        "TracksTable",
                        "StreamArn"
                      ]
                    }
                  ]
                }
              ]
            }
```
