### ISSUE TITLE
Alexa Skill event of function "embargoes" is not an object or string. The correct syntax is: alexaSkill. Please check the docs for more info.

### ISSUE THREAD

**Issue by jfix** [serverless/serverless#4765]
# This is a Bug Report

## Description

I get an error regarding an apparent syntax error in my `serverless.yml` file when deploying. The process stops and doesn't deploy.

The complete `serverless.yml` file looks like this (I only replaced the appId value):

```
service: alexa-test-embargoes

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1 # Alexa skills are supported only by this region in EU

functions:
  embargoes:
    handler: index.handler
    events:
      - alexaSkill:
          appId: amzn1.ask.skill.there-althin-ghere-ofcourse
          enabled: true
```

When running `sls deploy` on the command line I get this output:

```
$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  Alexa Skill event of function "embargoes" is not an object or string. The correct syntax is: alexaSkill. Please check the docs for more info.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.9.1
     Serverless Version:     1.26.0
```

I've checked the `serverless.yml`, rewritten it, had it created by `sls create` but the output doesn't change, and the service doesn't get deployed.

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: MacOS
* ***Stack Trace***: n/a
* ***Provider Error messages***: Alexa Skill event of function "embargoes" is not an object or string. The correct syntax is: alexaSkill. Please check the docs for more info.

**Comment by HyperBrain** [comment]
Hi @jfix . This has been added with https://github.com/serverless/serverless/issues/4700 and will be published with version 1.27.

However, I assume the docs are created from the live sources in the master branch, so they might already reflect this (not yet available) state.

Here's a quote from the other issue that explains the current (1.26) implementation:

As of today, the following configuration is present:
```yaml
functions:
  alexa:
    handler: handler.alexa
    events:
      - alexaSkill
```
