### ISSUE TITLE
lambda {AWS:Region} and Arn RegionS

### ISSUE THREAD

**Issue by tgensol** [serverless/serverless#4767]
Hi,

I am getting an issue, when I want to use severals resources from regions which are not the same as the serverless function region. Like in these examples : 

```
service: serverless-function

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  cfLogs: true

functions:
  post:
    handler: handler.post
    memorySize: 512
    timeout: 60
    iamRoleStatements:
         - Effect: "Allow"        
           Action:
             - lambda:InvokeFunction
           Resource: 
             - arn:aws:lambda:us-east-1:###
             - arn:aws:lambda:eu-west-1:###    
```

```
service: serverless-function

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: 
             - arn:aws:lambda:us-east-1:###
             - arn:aws:lambda:eu-west-1:###    
      Action:
        -  "lambda:InvokeFunction" 
```

Both the final ARN on the AWS IAM will become arn:aws:lambda:us-east-1:### and arn:aws:lambda:**us-east-1**:###   because the function is in the region **us-east-1**

How can we have ARNS from different regions of the actual region of the function ? 

I can see that the cloud formation template automatically replace the regions with _**{AWS::Region}**_. 
But can we disable this ? Is it a bug, or a misunderstanding of myself ?

The only way I found, was to create myself an IAM ROLE with the access to the Resources I wanted

Thanks !
