### ISSUE TITLE
onError dlq doesn't create proper IAM permissions when using a Ref to the sns topic

### ISSUE THREAD

**Issue by glicht** [serverless/serverless#4770]
# This is a Bug Report 

## Description

When using a DLQ for a function (defined via `onError`) that has a Ref to an SNS::Topic defined in the Resources section the IamRoleLambdaExecution role is not updated with the publish permission for the referenced topic. This results in the following error during deployment: `An error occurred: TestSnsLambdaFunction - The provided execution role does not have permissions to call Publish on SNS.`. 
For bug reports:
* What went wrong? Deployment failed
* What did you expect should have happened? Deployment should succeed.
* What was the config you used? Sample serverless.yml which fails deployment:
```yaml
service: test-dlq 

provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  stage: dev
  region: us-east-1

functions:
  testSns:
    handler: handler.hello
    events:
      - sns: lambda-test-sns-topic
    onError: 
      Ref: LambdaDLQTopic

resources:
  Resources:    
    #sns dlg
    LambdaDLQTopic:
      Type: AWS::SNS::Topic
      Properties: 
        DisplayName: lambda-test-dlq
        TopicName: lambda-test-dlq
```

* What stacktrace or error message from your provider did you see? Output from deploy:
```
» DEBUG=* sls deploy --verbose                            
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (410 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - test-dlq-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - TestSnsLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Topic - LambdaDLQTopic
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - TestSnsLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::SNS::Topic - LambdaDLQTopic
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - TestSnsLogGroup
CloudFormation - CREATE_COMPLETE - AWS::SNS::Topic - LambdaDLQTopic
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - TestSnsLambdaFunction
CloudFormation - CREATE_FAILED - AWS::Lambda::Function - TestSnsLambdaFunction
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - test-dlq-dev
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - test-dlq-dev
CloudFormation - DELETE_COMPLETE - AWS::Lambda::Function - TestSnsLambdaFunction
CloudFormation - DELETE_IN_PROGRESS - AWS::SNS::Topic - LambdaDLQTopic
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - TestSnsLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - TestSnsLogGroup
CloudFormation - DELETE_COMPLETE - AWS::SNS::Topic - LambdaDLQTopic
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - test-dlq-dev
Serverless: Operation failed!

  Serverless Error ---------------------------------------

  An error occurred: TestSnsLambdaFunction - The provided execution role does not have permissions to call Publish on SNS.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.11.1
     Serverless Version:     1.26.0
```

## Additional Data

* ***Workaround***:
When using an arn for onError configuration the proper permission is added and the deployment works fine. Also adding the following to the iamRoleStatements section resolves the issue:
```yaml
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sns:Publish        
      Resource: 
        Ref: LambdaDLQTopic
```

* ***Serverless Framework Version you're using***: 1.26.0
* ***Operating System***: Windows 10
* ***Stack Trace***: See above
* ***Provider Error messages***: `An error occurred: TestSnsLambdaFunction - The provided execution role does not have permissions to call Publish on SNS.`
