### ISSUE TITLE
Fn::ImportValue for authorizer arn.

### ISSUE THREAD

**Issue by AndreasAugustin** [serverless/serverless#4771]
It is not possible to use the Fn::ImportValue Cloud Formation functionality for authorizers.
The feature would be helpful because of the Cloud Formation deletion policy.

There have been some discussions about the import functionality:
#3442 
#3475
#3575

**Comment by flomotlik** [comment]
@HyperBrain & @horike37  any chance this will make it into Serverless? At the moment we're kind of blocked because we have to define custom authorizers for every service instead of creating one custom authorizer and reusing it across services.

**Comment by horike37** [comment]
Thanks @AndreasAugustin for opening this issue and thanks @flomotlik for commenting :+1: 
Is it hard to solve your problem with `${cf:stackName.outputKey}`? This allows you to reference an external stack output of CloudFormation.

If not, it might be good to introduce it to the core as a possible idea. However, We would like to know more details what is the use case that should be solved and how to realize that at first.

Would be good if we can do more in-depth discussion for that.

**Comment by AndreasAugustin** [comment]
Hi @horike37 
Thanks for the response. 
`${cf:stackName.outputKey}` is nice, but actually it is just querying the CF output. We want to import the value to have some CF features.
Use case:
Imagine you delete the stack where the `${cf:stackName.outputKey}` is created. Without importing the value there is no check (CF) if some stacks are using the value. Afaik with imported value a check would be present.
Another problem (which @flomotlik is reffering) is that we always need an extra authorizer per serverless stack, even if we use the same lambda arn because the authorizer name need to be unique (this seems to be a serverless check).
It would be super nice if we would be able to use the same custom authorizer within many serverless stacks. (one of the problems is that there is a soft limit of 10 for custom authorizers per API GW).
We have a growing amount of serverless stacks (Microservice architecture) all of the stacks using a global authorizer lambda as custom authorizer.

**Comment by davidgf** [comment]
After digging out on this, I found out that this is already supported. The only thing we need to make sure is that we pass the authorizer's name as well as the imported ARN:

```yaml
...
custom:
  defaultStage: test
  currentStage: ${opt:stage, self:custom.defaultStage}
  authorizerArn:
    Fn::ImportValue: MARVAdminAuthorizerArn-${self:custom.currentStage}

functions:
  adminsOnly:
    handler: handler.hiAdmins
    events:
      - http:
          path: /hiAdmins
          method: get
          authorizer:
            name: authorizer
            arn: ${self:custom.authorizerArn}
```

The reason behind this is that when [it gets the details about the authorizer](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js#L238), if no name is provided it tries to extract it from the ARN. Also, I think the name could be anything, as it's simply the display name of the authorizer
