### ISSUE TITLE
SessionCredentials fail on ReportLambdaFunction

### ISSUE THREAD

**Issue by thepont** [serverless/serverless#4786]
# This is a Bug Report

## Description

Using SessionCredentials for a serverless deploy fails while attempting to monitor the status of the deploy with AccessDenied.

This does not happen while using the profile's credentials.

### Script for getting session credentials.
```javascript
        var credentials = new AWS.SharedIniFileCredentials({
            profile: options.profile
        });
        var sts = new AWS.STS({
          credentials
        });
        var sessionCredentials = await sts.getSessionToken({
            DurationSeconds: 3600
        })
        .promise()
        .then(ii => ii.Credentials)

        dockerEnv.AWS_ACCESS_KEY_ID = sessionCredentials.AccessKeyId
        dockerEnv.AWS_SECRET_ACCESS_KEY = sessionCredentials.SecretAccessKey
        dockerEnv.AWS_SESSION_TOKEN = sessionCredentials.SessionToken
```

### What went wrong

AWS returned AccessDenied while attempting to use the session credentials to monitor the status of the deployed.

### What did you expect should have happened?

Serverless should react the same with SessionCredentials as with all other credentials, deploy should succeed as long as the user has the correct access.

### What was the config you used
```
provider:
  name: aws
  versionFunctions: false
  memorySize: 1536
  runtime: java8
  region: ap-southeast-2
  environment:
    REPORT_TEMPLATE_NAME: reports-processor-export
    LAMBDA_STAGE: ${opt:stage}
    LAMBDA_NAME: ${self:service}
    USE_LAMBDA: true
    S3_BUCKET: ${self:service}-${opt:stage}-files-bucket
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "*"
package:
  artifact: chekt-reports.jar
functions:
  report:
    description: Run a report using report-service, called from the http function.
    handler: com.blueflag.report_service.handlers.ProcessReportHandler
    timeout: 300

  postReport:
    description: Handle all HTTP requests for the report-service.
    handler: com.blueflag.report_service.handlers.PostReportHandler
    timeout: 300
    events:
      - http: POST /report/

  getReportInfo:
    description: Handle all HTTP requests for the report-service.
    handler: com.blueflag.report_service.handlers.GetReportInfoHandler
    timeout: 300
    events:
      - http: GET /report/status/{id}
  
resources:
  Resources:
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${opt:stage}-files-bucket
        LifecycleConfiguration:
          Rules:
            - Id: GlacierRule
              Prefix: glacier
              Status: Enabled
              ExpirationInDays: '30'
              Transitions:
                - TransitionInDays: '5'
                  StorageClass: Glacier

```

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Ubuntu running a docker container with Alpine.
* ***Stack Trace***: ```
$ /root/deploy/node_modules/.bin/serverless deploy -s dev -c

Serverless: Packaging service...

Serverless: Uploading CloudFormation file to S3...

Serverless: Uploading artifacts...

Serverless: Validating template...

Serverless: Updating Stack...

Serverless: Checking Stack update progress...

..
..
Serverless: Operation failed!

 

  Serverless Error ---------------------------------------
 
  An error occurred: ReportLambdaFunction - AccessDenied. User doesn't have permission to call iam:GetRole.
 

  Get Support --------------------------------------------

     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Forums:        forum.serverless.com

     Chat:          gitter.im/serverless/serverless

 
  Your Environment Information -----------------------------
     OS:                     linux

     Node Version:           8.9.4
     Serverless Version:     1.26.1
 

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

child process exited with code 1
```
