### ISSUE TITLE
Regions being mangled in ARNs, CF doesn't match

### ISSUE THREAD

**Issue by philchristensen** [serverless/serverless#4791]
# This is Bug Report

## Description

For bug reports:
* What went wrong? **ARN in IAM policy is being replaced with Fn::Sub and ${AWS::Region}**
* What did you expect should have happened? **When I hardcode a region string in an ARN, it should never be replaced.**
* What was the config you used?
serverless deploy --region us-east-2 --stage prod
```
service: lifeline-shim
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  memorySize: 128
  tracing: true
  environment:
    ENABLE_XRAY: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "arn:aws:logs:*:*:*"
    # xray permissions (required)
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    # Couldn't get this to work right when self-referencing, probably a Serverless bug
    # TODO: Tighten security to only allow publishing to *this* DLQ
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"
    # Access to SimpleDB account database
    - Effect: "Allow"
      Action:
        - "sdb:Select"
      Resource: "arn:aws:sdb:us-east-1:475806025084:*"
    # So the shim function can call the step functions
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource:
        - "arn:aws:states:us-east-1:475806025084:stateMachine:lifeline-${opt:stage}-create"
        - "arn:aws:states:us-east-1:475806025084:stateMachine:lifeline-${opt:stage}-copy"
        - "arn:aws:states:us-east-1:475806025084:stateMachine:lifeline-${opt:stage}-cleanup"
functions:
  # This listens to incoming events on the event bus and checks if they look
  # like Lifeline invocations (e.g., the originating rule matches with 'lifeline-<ENV>-schedule')
  shim:
    description: Stub function to invoke Lifeline from cross-account scheduled events.
    handler: lifeline_shim.shim.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.events"
            detail-type:
              - "Scheduled Event"
plugins:
  - serverless-plugin-tracing
  - serverless-pseudo-parameters
```

* What stacktrace or error message from your provider did you see?

No errors, but when I output the CloudFormation template with `--noDeploy` the saved template has *not* been mangled. When I deploy it, then look at the template in CloudFormation, *that* template is mangled.

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: OS X High Sierra
