### ISSUE TITLE
Deploying S3 bucket with SNS notification event not possible

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#4797]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

It's not possible to deploy a stack with an S3 bucket that has an SNS topic as an event notification. Is something missing in the CloudFormation file generated by Serverless? According to this AWS support article, it seems an `AWS::SNS::TopicPolicy` is needed, and this is not generated by Serverless:
https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/

* What did you expect should have happened?

The stack should deploy without errors.

* What was the config you used?

See bottom for `serverless.yml` file.

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: macOS 10.13.3
* ***Stack Trace***:
* ***Provider Error messages***:
```
  Serverless Error ---------------------------------------

  An error occurred: TestBucket - Unable to validate the following destination configurations.
```

serverless.yaml:
```yaml
service:
  name: TestStack

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  variableSyntax: '\$\(([\s\S]+?)\)'

custom:
  stage: $(opt:stage, self:provider.stage)
  topicName: kerpow
  topic: $(self:service)-$(self:custom.topicName)-$(self:custom.stage)
  topicArn:
    Fn::Sub: arn:aws:sns:$(self:provider.region):${AWS::AccountId}:$(self:custom.topic)

functions:
  first:
    handler: first.hello
    events:
      - sns: $(self:custom.topic)

resources:
  Resources:
    TestBucket:
      Type: AWS::S3::Bucket
      DependsOn: SNSTopic$(self:service)$(self:custom.topicName)$(self:custom.stage)
      Properties:
        BucketName: aa-test-95872017
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:Put
              Filter:
                S3Key:
                  Rules:
                    - Name: prefix
                      Value: staging/
              Topic: $(self:custom.topicArn)
```

**Comment by ffxsam** [comment]
This template works. It's a bit messier than I'd like. IMO Serverless should handle this automatically.

```yaml
service:
  name: TestStack

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  variableSyntax: '\$\(([\s\S]+?)\)'

custom:
  stage: $(opt:stage, self:provider.stage)
  topicName: kerpow
  topic: $(self:service)-$(self:custom.topicName)-$(self:custom.stage)
  topicArn:
    Fn::Sub: arn:aws:sns:$(self:provider.region):${AWS::AccountId}:$(self:custom.topic)

functions:
  first:
    handler: first.hello
    events:
      - sns: $(self:custom.topic)

resources:
  Resources:
    TestBucket:
      Type: AWS::S3::Bucket
      DependsOn: SNSTopicPolicy
      Properties:
        BucketName: aa-test-95872017
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:Put
              Filter:
                S3Key:
                  Rules:
                    - Name: prefix
                      Value: staging/
              Topic: $(self:custom.topicArn)
    SNSTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS: "*"
              Action: sns:Publish
              Resource: $(self:custom.topicArn)
              Condition:
                ArnLike:
                  aws:SourceArn: arn:aws:s3:::aa-test-95872017
        Topics:
          - Ref: SNSTopic$(self:service)$(self:custom.topicName)$(self:custom.stage)
```
