### ISSUE TITLE
Bug: packaging with the "request" dependency creates 'no such file' error.

### ISSUE THREAD

**Issue by warrenronsiek** [serverless/serverless#4813]
# This is a Bug Report 

## Description
I have a lambda function that uses the package request and request-promise. Everything runs and is fine for several months. Recently re-deployed, and now I get an error saying "no such file or directory, open '/types/mime.types'" whenever I have a `require('request')`. Nothing has changed in my webpack config or serverless.yml between now and when things worked. 

### What went wrong?
Serverless function throws `no such file or directory` error when running `require('requests')`
### What did you expect should have happened?
`require('requests')` should execute successfully.

### What was the config you used?
I use webpack to build and then I deploy with `sls deploy`. 

webpack.config.js
```
const build = {
  entry: paths.index,
  resolve: {
    extensions: ['.js']
  },
  target: 'node',
  output: {
    path: paths.dist,
    filename: '[name].js',
    libraryTarget: "commonjs"
  },
  module: {
    loaders: [
      {
        test: /\.jst$|\.md$|\.def$|\.d\.ts$|\.ts/,
        loader: 'ignore-loader',
        include: [paths.typings, paths.nodeModules]
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: [paths.typings]
      },
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        exclude: [paths.typings, paths.nodeModules]
      },
      {
        test: /\.json$/,
        loader: 'json-loader',
        query: {
          presets: 'env'
        }
      }
    ]
  },
  externals: ["aws-sdk"],
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: {warnings: false, drop_console: false},
      beautify: false,
      comments: false,
      mangle: {except: ['$', 'webpackJsonp'], screw_ie8: true}
    })
  ]
};
```

serverless.yml (too long, but I've included relevant parts):
```
provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, self:custom.default_stage}
  runtime: nodejs6.10
  memorySize: 128
  apiKeys:
    - [a key]
  environment:
    stage: ${self:provider.stage}
    [more env variables]
  iam:
     [Iam roles]
...
package:
  excludeDevDependencies: false
  include:
    - dist/**
  exclude:
    - lib/**
    - package.json
    - package-lock.json
    - typings/**
    - test/**
    - request_templates/**
    - .git
    - .gitignore
    - .babelrc
    - .npmignore
    - tsconfig.json
    - typings.json
    - typings/**
    - webpack.config.js
    - .idea/**
    - node_modules/**
    - '!node_modules/jwt-decode/**'
    - '!node_modules/uuid/**'
    - '!node_modules/request/**'
    - '!node_modules/request-promise/**'
...
functions:
    [standard serverless functions]

```
### What stacktrace or error message from your provider did you see?
Error: ENOENT: no such file or directory, open '/types/mime.types'
at Error (native)
at Object.fs.openSync (fs.js:641:18)
at Object.fs.readFileSync (fs.js:509:33)
at t.load (/var/task/dist/stripeRedirect.js:1:183053)
at Object.<anonymous> (/var/task/dist/stripeRedirect.js:1:183476)
at Object.<anonymous> (/var/task/dist/stripeRedirect.js:1:183671)
at o (/var/task/dist/stripeRedirect.js:1:211)
at Object.<anonymous> (/var/task/dist/stripeRedirect.js:1:156866)
at o (/var/task/dist/stripeRedirect.js:1:211)
at Object.<anonymous> (/var/task/dist/stripeRedirect.js:1:12503)

### Similar or dependent issues:
* [190](https://github.com/serverless-heaven/serverless-webpack/issues/190)
* [3915](https://github.com/serverless/serverless/issues/3915)

## Additional Data
I've tried this with  and without `excludeDevDependencies: false`.
I've also tried this with and without the entries:
```
    - '!node_modules/request/**'
    - '!node_modules/request-promise/**'
```
The error only seems to happen when I require the `request` dependency. Requiring `request-promise` by itself without having a `require(request)` throws an error that says:
```
### The "request" library is not installed automatically anymore.
### But required by "request-promise".
```
This seems to indicate that the package `request-promise` is successfully required, it just doesn't have  access to the request package. This happens even when the request package is included in the "do not exclude" part of package.exclude.

Also note that the lambda function successfully requires other packages (like jwt-decode) included under package.exclude. 

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: MacOS
* ***Stack Trace***: see above
* ***Provider Error messages***: see above
