### ISSUE TITLE
Feature request for compiling difference since last update

### ISSUE THREAD

**Issue by mishrakrishnakant** [serverless/serverless#4816]
# This is a  (Feature Proposal)

## Description

* When compiling serverless definitions that have a large set of functions, all functions get compiled and updated.
* This of course happens even if that particular resource changed or not, in terms of code, definition of the resource, role, change in policy, etc.
* This causes cost in compile time (we use codebuild but any other resource would cost something or the other)

## Solution
I of course realize that detecting change in all those things is very difficult and then update only the diff lambdas. So here is a proposed solution:

* Having a flag mechanism for compiling serverless definitions
* Have a central flag at the top of all definitions like 
```
provider:
    name: aws
    runtime: nodejs5.0
    functionFlag: ajva2ta@
# function definition from a previous build
functionDefinitionThatDidChange:
   handler: handler/directory
   functionFlag: 6j15A#aas
functionDefinitionThatDidChange:
   handler: handler/directory
   functionFlag: ajva2ta@
```
* And then at compile time, we only look for build tasks in current queue and compile and update them. Saving cost in compile and update.
* Additionally, if the main functionFlag is removed or commented out, simply update everything indicating a change in important libraries, etc which require a global update of all resource definitions.
