### ISSUE TITLE
Lambda Proxy isn't working

### ISSUE THREAD

**Issue by walkerlangley** [serverless/serverless#4819]
# This is a (Bug Report / Feature Proposal)

## Description

* What went wrong?
  - after testing locally by invoking my function and also using serverless-offline, when I deployed the function I get a 504 and Gateway Timeout.  I bumped up the timeout to 30 seconds and the function typically runs around 5-6 seconds, so it's not timing out.  I added a log right before the return statement and it logs in CloudWatch, so it seems that something is going on between lambda and apiGateway.  This is my return statement

```javascript
  console.log('EXP: ', exp);  // This logs in cloudwatch

  return callback(null, {
    statusCode: 200,
    headers: {
      'Set-Cookie': `x-jwt=${token}; expires=${exp}`,
      'Access-Control-Allow-Origin' : "*", // Required for CORS support to work
      'Access-Control-Allow-Credentials' : true // Required for cookies, authorization headers with HTTPS
    }
  });
```

* What did you expect should have happened?
  - The function should return the same result when testing locally and after deploying

The CloudWatch logs for apiGateway just say "sending to the lambda", then 30 seconds later a "Execution failed due to a timeout error" message.

* serverless.yml
```yml
service: wl-login-test

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true
  serverless-offline:
    babelOptions:
      presets: ["env"]

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  timeout: 15

functions:
  login:
    handler: handler.login
    environment:
      SECRET: secret
      TABLE_NAME: tableName
      AWS_PROFILE: profile
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pgPassword
      POSTGRES_DB: dbName
      POSTGRES_HOST: hostName
    events:
      - http:
          path: login
          method: post
          cors: true
```
If I add `integration: lambda` to to the events, the function returns as expected, but then I can't test locally (and I also don't want lambda integration, but want lambda-proxy).

I tried rolling back to Serverless: v1.26.0 but got the same results

Any help would be appreciated.
Thanks in advance,
Walker

## Additional Data
* ***Serverless Framework Version you're using***: 1.26.1 (also tried 1.26.0)
* ***Operating System***: OSX v10.13.3
* ***Provider Error messages***:
