### ISSUE TITLE
Unable to consolidate services under same ApiGateway if using Cognito authorizer

### ISSUE THREAD

**Issue by perevernihata** [serverless/serverless#4824]
# This is a Bug

## Description

For bug reports:
* What went wrong?
When I try to consolidate multiple services under same Api Gateway im getting an error. I;m using multiple service with lambda integration and Cognito authorization.

* What did you expect should have happened?
It should not try to recreate authorizer OR it should generate unique name for every authorizer (mix the service name into it)
* What was the config you used?
```
service: companiesService
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256
  stage: ${opt:stage, 'development'}
  region: ap-southeast-2
  iamRoleStatements: ${file(../../devops/dynamoIamRole.yaml)}
  apiGateway: ${file(../../devops/sharedApiGateway.yaml)}
functions:
  createCompany:
    handler: handlers/createCompany.handler
    environment: ${file(../../devops/environmentVariables.yaml)}
    events:
      - http:
          path: companies
          method: post
          integration: lambda
          response: ${file(../../devops/eventResponse.yaml)}
          authorizer: ${file(../../devops/eventAuthorizer.yaml)}
  updateCompany:
    handler: handlers/updateCompany.handler
    environment: ${file(../../devops/environmentVariables.yaml)}
    events:
      - http:
          path: companies/{id}
          method: put
          integration: lambda
          response: ${file(../../devops/eventResponse.yaml)}
          authorizer: ${file(../../devops/eventAuthorizer.yaml)}
  getCompanies:
    handler: handlers/getCompanies.handler
    environment: ${file(../../devops/environmentVariables.yaml)}
    events:
      - http:
          path: companies
          method: get
          integration: lambda
          response: ${file(../../devops/eventResponse.yaml)}
          authorizer: ${file(../../devops/eventAuthorizer.yaml)}
resources:
  Resources:
    DDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${file(../../devops/configs/${opt:stage, 'development'}.config.json):CompaniesTable}
        AttributeDefinitions:
          -
            AttributeName: "CompanyId"
            AttributeType: "S"
          -
            AttributeName: "TenantId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "TenantId"
            KeyType: "HASH"
          -
            AttributeName: "CompanyId"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```

eventAuthorizer.yaml looks like this: 

```
  arn: ${file(../../devops/configs/${opt:stage, 'development'}.config.json):CongnitoARN}
  claims:
    - email
    - custom:agencyId
```

* What stacktrace or error message from your provider did you see?
`An error occurred: 2UnderscorevX1V74l4iApiGatewayAuthorizer - Authorizer name must be unique. Authorizer 2_vX1V74l4i already exists in this RestApi..`

Similar or dependent issues:
* #4655

## Additional Data

* ***Serverless Framework Version you're using***:
```
$ sls -v
1.26.0
```
* ***Operating System***:
Windows 10
