### ISSUE TITLE
Package: excluding devDependencies from build not working with node v8.10.0

### ISSUE THREAD

**Issue by coreylight** [serverless/serverless#4830]
# This is a Bug Report

## Description

The "excluding dev dependencies" feature does not seem to be working with node v8.10.0, where it does with node v6.10.3.

For bug reports:
* What went wrong?
devDependencies not excluded from sls package
* What did you expect should have happened?
devDependencies should be excluded
* What was the config you used?
```yml
service: XXX
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  timeout: 30
  vpc:
    securityGroupIds:
      - XXX
    subnetIds:
      - XXX
  environment:
    XXX: YYY
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - XXX
        - YYY
      Resource:
        - XXX
package:
  exclude:
    - src/**
functions:
  schedule:
    handler: functions/schedule.handle
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: ${opt:stage = "prod"}
  execute:
    handler: functions/execute.handle
custom:
  defaultStage: staging
```
* What stacktrace or error message from your provider did you see?
Everything runs without errors, but package is very large.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.26.1
* ***Operating System***:
Mac OSX 10.13.3
* ***Stack Trace***:
* ***Provider Error messages***:
* ***Node Version***:
8.10.0
