### ISSUE TITLE
Invoke aws:common:moveArtifactsToPackage freezing

### ISSUE THREAD

**Issue by Vadorequest** [serverless/serverless#4835]
# This is a **Bug Report**

## Description

I tried to deploy but the process got stuck at the step

> Invoke aws:common:moveArtifactsToPackage

Any idea what this can be related to? I was able to deploy without issue before, I did a few changes in the serverless.yml, basically replaced hardcoded stuff by `${self:service}` but I don't see how that relates because I did a `sls print` and everything looks fine...

* ***Serverless Framework Version you're using***: 1.26.1

**Comment by Vadorequest** [comment]
I tried to `sls remove` and `sls deploy` again, I'm stuck all the same. This is a serious bug as I have no idea what triggered it and how to resolve it.

**Comment by Vadorequest** [comment]
And now it just worked after 10 failures. Maybe related to AWS?

**Comment by HyperBrain** [comment]
@Vadorequest Did the issue reappear again, or was it just intermittent?

**Comment by Vadorequest** [comment]
@HyperBrain It didn't. Seems like it was a temporary issue. I don't know what should be done about it, the main issue was that I had no idea what was wrong and I thought it was from my code or SLS architecture somehow, which made me `sls remove` stuff while it wasn't necessary, and blocked me to deploy. I'm glad it wasn't anything in production :D

**Comment by Vadorequest** [comment]
I'm experimenting the same issue again right now, I changed something in my scripts and `aws:common:moveArtifactsToPackage` has been hanging for about 5mn.

Maybe it isn't AWS failure, maybe it's a bad serverless.yml that is the source of the issue.

---

In order to make sure, I rolled back my script changes, deployed again, and it worked. Then, I made the same changes again, deployed, and it hanged again.

So, I can tell that it isn't some kind of AWS failure like a server down or something, but rather something in the SLS configuration that isn't right and makes it fail. But it's weird because the first time it happened to me (when I opened this issue) I didn't change anything (as far as I remember) in the serverless.yml, and it was failing until it worked, without changes.

---

Here is a detail of what I did today, using the same and unchanged serverless.yml:

<details>

```yml
service: loan-advisor

frameworkVersion: "=1.26.1"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  serverless-offline:
    port: 3000 # We run our SLS/Express endpoints there (Next app will run on 3001)
  webpackIncludeModules:
    # Enable auto-packing of external modules
    # See https://serverless-stack.com/chapters/add-support-for-es6-es7-javascript.html
    forceInclude:
      - classnames
      - deepmerge
      - http-proxy
      - htmlescape
      - next-redux-wrapper
      - prop-types
      - react-ga # TODO useful?
      - react-gtm
      - react-redux
      - react-select
      - react-style-proptype
      - reactstrap
      - recompose
      - redux-devtools-extension # Shouldn't be necessary, but it is because of the way it's imported
      - redux-thunk
      - styled-jsx
  environment: ${env:NODE_ENV, 'development'}
  stages:
    development: # XXX Kept for compatibility but useless, development stage doesn't go to AWS
      domain:
        name:
      memorySize:
    hepStaging:
      domain:
        name: staging.hep.${self:service}.studylink.fr
      memorySize: 512
    hep:
      domain:
        name: hep.${self:service}.studylink.fr
      memorySize: 512 # TODO Check how much is actually needed
  customDomain:
    enabled: true
    domainName: ${self:custom.stages.${self:provider.stage}.domain.name}
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false # See https://serverless.com/framework/docs/providers/aws/guide/functions#versioning-deployed-functions
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'eu-west-3'}
  memorySize: ${self:custom.stages.${self:provider.stage}.memorySize, '128'}
  deploymentBucket:
    name: studylink-${self:service}-serverless
    serverSideEncryption: AES256
  environment:
    NODE_ENV: ${self:custom.environment}
    GROUP_NAME: ${env:GROUP_NAME}
  stackTags:
    env: ${self:custom.environment}
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    product: ${self:service}
    type: website

functions:
  server:
    handler: src/functions/server/server.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: /static/{any+}
      - http:
          method: GET
          path: /_next/{proxy+} # Catch Next specific routes
      - http:
          method: ANY
          path: /{any+} # Catch all unknown routes and redirect to main handler

```

</details>

I usually deploy against AWS using the `staging` environment. But something wasn't working quite right in my app so I switched from `staging` to `development`, as follow:

## 1. First failure case 

When running `npm run deploy:hep`

package.json
```json
  "scripts": {
    "build:hep": "cross-env-shell GROUP_NAME=staging.hep NODE_ENV=development \"next build && serverless package -s hepStaging\"",
    "deploy:hep": "cross-env-shell GROUP_NAME=staging.hep NODE_ENV=development \"npm run build:hep && serverless deploy -v --package .serverless -s hepStaging\"",
  },
```


The only things impacted in `serverless.yml` by the NODE_ENV are:

- `custom.environment`
- `provider.environment.NODE_ENV`
- `provider.stackTags.env`

Nothing that should cause a AWS deploy failure, in my opinion? Note that I'm still using the `hepStaging` stage. And therefore it should deploy on `staging.hep.${self:service}.studylink.fr`, which already hosts my staging environment (from previous sls deploys)

With this setup, I got stuck on `aws:common:moveArtifactsToPackage` for more than 5mn, then killed it.

## 2. Rollback the scripts changes (works)

I rollbacked my script changes to see if it was a AWS failure, basically, I switched from NODE_ENV=development to `staging`, as follow:

```json
  "scripts": {
    "build:hep": "cross-env-shell GROUP_NAME=staging.hep NODE_ENV=staging \"next build && serverless package -s hepStaging\"",
    "deploy:hep": "cross-env-shell GROUP_NAME=staging.hep NODE_ENV=staging \"npm run build:hep && serverless deploy -v --package .serverless -s hepStaging\"",
  },
```

I didn't change anything in serverless.yml, and the `npm run deploy:hep` worked.

## 3. Use `NODE_ENV=development` once more

So, at this point I assumed AWS works just fine and it's something to do with my serverless.yml, to make sure, I basically go back to how it was in the `1. First failure case` and run `npm run deploy:hep` again.

It's still hanging at `aws:common:moveArtifactsToPackage` after more than 20mn (the time to write this post)

---

# Conclusion:

Hard to tell what's happening, hard to tell what's wrong. Hard to reproduce.

When it happened to me the very first time, I didn't change anything (AFAIR) in either package.json nor serverless.yml) between my various attempts, and it magically worked at some point. (that's, at least, what I remember)

But today, it doesn't appear to be an AWS deployment issue. And it's very hard to tell what's wrong without more logs. 

For further debug, here is the generated `serverless.yml`:

`NODE_ENV=staging sls print -s hepStaging`

<details>

```yml
service: loan-advisor
frameworkVersion: =1.26.1
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
custom:
  serverless-offline:
    port: 3000
  webpackIncludeModules:
    forceInclude:
      - classnames
      - deepmerge
      - http-proxy
      - htmlescape
      - next-redux-wrapper
      - prop-types
      - react-ga
      - react-gtm
      - react-redux
      - react-select
      - react-style-proptype
      - reactstrap
      - recompose
      - redux-devtools-extension
      - redux-thunk
      - styled-jsx
  environment: staging
  stages:
    development:
      domain:
        name: null
      memorySize: null
    hepStaging:
      domain:
        name: staging.hep.loan-advisor.studylink.fr
      memorySize: 512
    hep:
      domain:
        name: hep.loan-advisor.studylink.fr
      memorySize: 512
  customDomain:
    enabled: true
    domainName: staging.hep.loan-advisor.studylink.fr
    stage: hepStaging
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false
  stage: hepStaging
  region: eu-west-3
  memorySize: 512
  deploymentBucket:
    name: studylink-loan-advisor-serverless
    serverSideEncryption: AES256
  environment:
    NODE_ENV: staging
  stackTags:
    env: staging
    stage: hepStaging
    region: eu-west-3
    product: loan-advisor
    type: website
functions:
  server:
    handler: src/functions/server/server.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: '/static/{any+}'
      - http:
          method: GET
          path: '/_next/{proxy+}'
      - http:
          method: ANY
          path: '/{any+}'

```

</details>

---

`NODE_ENV=development sls print -s hepStaging`

<details>

```yml
service: loan-advisor
frameworkVersion: =1.26.1
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
custom:
  serverless-offline:
    port: 3000
  webpackIncludeModules:
    forceInclude:
      - classnames
      - deepmerge
      - http-proxy
      - htmlescape
      - next-redux-wrapper
      - prop-types
      - react-ga
      - react-gtm
      - react-redux
      - react-select
      - react-style-proptype
      - reactstrap
      - recompose
      - redux-devtools-extension
      - redux-thunk
      - styled-jsx
  environment: development
  stages:
    development:
      domain:
        name: null
      memorySize: null
    hepStaging:
      domain:
        name: staging.hep.loan-advisor.studylink.fr
      memorySize: 512
    hep:
      domain:
        name: hep.loan-advisor.studylink.fr
      memorySize: 512
  customDomain:
    enabled: true
    domainName: staging.hep.loan-advisor.studylink.fr
    stage: hepStaging
    createRoute53Record: true
provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false
  stage: hepStaging
  region: eu-west-3
  memorySize: 512
  deploymentBucket:
    name: studylink-loan-advisor-serverless
    serverSideEncryption: AES256
  environment:
    NODE_ENV: development
  stackTags:
    env: development
    stage: hepStaging
    region: eu-west-3
    product: loan-advisor
    type: website
functions:
  server:
    handler: src/functions/server/server.handler
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: '/static/{any+}'
      - http:
          method: GET
          path: '/_next/{proxy+}'
      - http:
          method: ANY
          path: '/{any+}'

```

</details>
