### ISSUE TITLE
Feature request: specify `reservedConcurrentExecutions` for each function

### ISSUE THREAD

**Issue by theburningmonk** [serverless/serverless#4836]
# This is a Feature Proposal

## Description

Allow you to specify the no. of reserved concurrent executions for a function via the `serverless.yml` now that it's [supported by CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-reservedconcurrentexecutions)

Configuration might look like this:

```
functions:
  usersCreate:
    handler: users.create
    reservedConcurrentExecutions: 1 # limit concurrency of function to 1
```

I'm not a fan of the name `reserved` as it doesn't reflect the fact that it's setting a "limit" on the level of concurrency for that function.. but, it's what AWS has called it, so using a different name here might be even more confusing as user would have to a) still understand what "reserved" means in AWS Lambda, and additionally b) map a different terminology to what AWS uses already :-/
