### ISSUE TITLE
Configure local plugins folder

### ISSUE THREAD

**Issue by nolde** [serverless/serverless#4839]
# This is a Feature Proposal

## Description

Right now, when creating small local plugins, the only current option is to create a folder named `.serverless_plugins` to store it.

It would be nice to be able to configure the local plugins folder. This is good for projects with a well defined folder structure, that must then have an enforced folder that breaks the mould. That is specially true for _dot_ prefixed folders, which are usually used for working environment metadata, and commonly _gitignored_.

Behaviour would be exactly the same as today, it would only change the folder from `.serverless_plugins` to the configured one.

```yaml
service:
  name: my-serverless-stuff

# we could have a simple new property...
localPluginsFolder: './sls/plugins'
plugins:
  - plugin-one
  - plugin-two
...
```

```yaml
service: my-serverless-stuff  # fallback!

# or we could have an enhanced plugin object, with fallback into the "import", 
# just as "service" does with "name" 
plugins:
  localFolder: './sls/plugins'
  import:
    - plugin-one
    - plugin-two
...
```
## Additional Data

* https://serverless.com/framework/docs/providers/aws/guide/plugins/

**Comment by HyperBrain** [comment]
Hi @nolde , thanks for the feature request 👍 . This is indeed a valuable improvement.

I would prefer something like the second alternative with a fallback to the old declaration instead of adding a new root key. Maybe we can use a different name than `import` that more precisely describes the plugin list node, e.g.

```yaml
plugins:
  localPath: './sls/plugins',
  modules:
    - plugin1
    - plugin2
```

What do you think?
