### ISSUE TITLE
Deploy fails with certificate issue behind corporate proxy

### ISSUE THREAD

**Issue by bence-takacs** [serverless/serverless#4841]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Behind corporate proxy I get the following error: "Could not locate deployment bucket. Error: unable to get local issuer certificate"
* What did you expect should have happened?
No error or at least not with the certificate. Or at least more details about what server did it try to connect and/or a suggestion how to to bypass/resolve certificate issues.
* What was the config you used?
```
service: dashboard-poc

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  profile: my-devops
  deploymentBucket:
    name: my-dashboard
  versionFunctions: false 

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get
          
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-dashboard
```
* What stacktrace or error message from your provider did you see?
```
$ echo $http_proxy
http://my-proxy:80
$ export SLS_DEBUG=*; sls deploy --verbose
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate

  Serverless Error ---------------------------------------

  Could not locate deployment bucket. Error: unable to get local issuer certificate

  Stack Trace --------------------------------------------

ServerlessError: Could not locate deployment bucket. Error: unable to get local issuer certificate
    at BbPromise.resolve.then.then.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/existsDeploymentBucket.js:26:15)
From previous event:
    at AwsDeploy.existsDeploymentBucket (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/existsDeploymentBucket.js:25:13)
    at AwsDeploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:81:25)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:78:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #3508
* #3958

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: OSX Sierra
* ***Stack Trace***: see above
* ***Provider Error messages***: see above
