### ISSUE TITLE
Arrays\Objects as Variables in serverless.yml - Feature Request

### ISSUE THREAD

**Issue by NimrodGeva** [serverless/serverless#4843]
# This is a Feature Proposal

## Description

For bug reports:
* What went wrong? 
N/A
* What did you expect should have happened? 
N/A
* What was the config you used? 
N/A
* What stacktrace or error message from your provider did you see? 
N/A

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I'm having a hard time believing this was not previously requested as a feature, but I couldn't find a similar feature request in the issues.

I can think of many use-cases for having array\object variables.
The one I ran into is this: 
I have many functions triggered by API Gateway paths.
These functions have CORS enabled, but I had to edit the CORS configuration. This configuration is shared by all functions, but has to be explicitly defined in each.

My serverless.yml:
```
functions:
  func1:
    ...
    events:
      - http: 
          ...
          cors:
            origin: ${self:custom.corsOrigin}
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          ...
  ...
  funcN: 
    ...
    events:
      - http: 
          ...
          cors:
            origin: ${self:custom.corsOrigin}
            headers: 
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
          ...
```

The serverless.yml with object variables:

```
functions:
  func1:
    ...
    events:
      - http: 
          ...
          cors: ${self:custom.corsConfig}
          ...
  ...
  funcN: 
    ...
    events:
      - http: 
          ...
          cors: ${self:custom.corsConfig}
          ...
```

At the very least, the serverless.yml with only array variables:
```
functions:
  func1:
    ...
    events:
      - http: 
          ...
          cors:
            origin: ${self:custom.corsConfig.corsOrigin}
            headers: ${self:custom.corsConfig.corsHeaders}
            allowCredentials: true
          ...
  ...
  funcN: 
    ...
    events:
      - http: 
          ...
          cors:
            origin: ${self:custom.corsConfig.corsOrigin}
            headers: ${self:custom.corsConfig.corsHeaders}
            allowCredentials: true
          ...
```

There might be some centralised way to define the CORS configuration for all functions that I missed, but the feature is still required if, for example, one has 2 separate CORS configurations. Obviously this might be helpful for lots of other use cases other than CORS as well.

* If there is additional config how would it look
N/A

Similar or dependent issues:
N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: mac OS High Sierra 
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
