### ISSUE TITLE
Schedule event not created when supplying options

### ISSUE THREAD

**Issue by GlynnPhillips** [serverless/serverless#4844]
# This is a Bug Report
## Description

For bug reports:
* What went wrong?
Using the following serverless config doesn't create the cloudwatch trigger

```
functions:
  listener:
    handler: dist/functions/listener.handler
    events:
      - schedule:
        rate: cron(0 12 * * ? *)
        input:
            key1: value1
```

If I use the "inline" config the trigger is created but this limits me to not be able to supply any other parameters such as input.

Example of working "inline" version
```
functions:
  listener:
    handler: dist/functions/listener.handler
    events:
      - schedule: cron(0 12 * * ? *)
```

* What did you expect should have happened?
I expected cloudwatch trigger to be created that triggers at the relevant cron time. I also expected the the inputs to be in the "Constant (JSON text)" part of the CloudWatch rule

* What was the config you used?

```
functions:
  listener:
    handler: dist/functions/listener.handler
    events:
      - schedule:
        rate: cron(0 12 * * ? *)
        input:
            key1: value1
```

* What stacktrace or error message from your provider did you see?
N/A

* Similar or dependent issues:
#3886

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***:  MacOS 10.13.3
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by GlynnPhillips** [comment]
Sorry, this was user error and I actually just had the wrong indentation.

Correct indentation
```
functions:
  listener:
    handler: dist/functions/listener.handler
    events:
      - schedule:
          rate: cron(0 12 * * ? *)
          input:
            key: value
```

![Homer Simpson retreating into a hedge](https://user-images.githubusercontent.com/524573/37721485-8c90d9d0-2d21-11e8-8efc-68a196e91871.gif)
