### ISSUE TITLE
Multiple usage plans

### ISSUE THREAD

**Issue by thinkski** [serverless/serverless#4846]
# This is a Feature Proposal

## Description

Currently, only a single usage plan is supported. However, API Gateway supports multiple usage plans. For instance, suppose an API has tiers of access, a free tier and a paid tier. For this use case it makes sense to have separate usage plans and affiliate API keys with one or the other.

The config could look something like this:
```
provider:
  name: aws
  usagePlans:
    - free:
      quota:
        limit: 1000
        period: MONTH
      throttle:
        burstLimit: 1
        rateLimit: 1
    - paid:
      quota:
        limit: 1000000
        period: MONTH
      throttle:
        burstLimit: 1000
        rateLimit: 1000
```
