### ISSUE TITLE
The CloudFormation template is invalid: S3 error: The specified bucket does not exist

### ISSUE THREAD

**Issue by pnispel** [serverless/serverless#4853]
# This is a Bug Report

## Description
After deploying a function to `us-east-1` successfully, I tried deploying to `us-gov-west-1`. I'm now getting this error:

```
The CloudFormation template is invalid: S3 error: The specified bucket does not exist
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```
Looking at the cloud formation template, all the buckets exist. I've checked in the console that `ServerlessDeploymentBucket` references the correct bucket and it exists. 

The deployment `.zip` gets uploaded to the deployment bucket correctly.
The two resource buckets exist
The user has full s3 access
Tried deleting and recreating the cloudformation stack

```
service: thumbnail-generator

custom:
  apigwBinary:
    types:
      - '*/*'
  bucket:
    dev: thumbnail-lambda-bucket-dev
    prod: thumbnail-lambda-bucket-prod
  webpackIncludeModules: false # disable auto including modules
  serverless-offline:
    port: 4000
  profile:
    us-gov-west-1: lambda-govcloud
    us-east-1: lambda
  iamRoleStatements:
    us-gov-west-1:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: "arn:aws-us-gov:s3:::bucket/*"
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource: "arn:aws-us-gov:s3:::${self:custom.bucket.${opt:stage, self:provider.stage}}/*"
    us-east-1:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: "arn:aws:s3:::bucket/*"
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:PutObject
        Resource: "arn:aws:s3:::${self:custom.bucket.${opt:stage, self:provider.stage}}/*"

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-webpack
  - serverless-offline
  - serverless-mocha-plugin

package:
  exclude:
    - .serverless
    - .webpack
    - .gitignore
    - LICENSE
    - package.json
    - README.md
    - serverless.yml
    - webpack.config.js

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, "dev"}
  profile: ${self:custom.profile.${opt:region, "us-east-1"}}
  region: ${opt:region, "us-east-1"}
  iamRoleStatements: ${self:custom.iamRoleStatements.${opt:region, "us-east-1"}}

functions:
  resize:
    handler: handler.resize
    events:
      - http:
          path: /{bucket}/{key+}
          method: get
          authorizer: aws_iam
          contentHandling: CONVERT_TO_BINARY
    environment:
      DESTINATION_BUCKET: ${self:custom.bucket.${opt:stage, self:provider.stage}}

resources:
  Resources:
    devThumbnailBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: thumbnail-lambda-bucket-dev
    prodThumbnailBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: thumbnail-lambda-bucket-prod
```

Similar or dependent issues:
https://github.com/serverless/serverless-graphql/issues/72
https://github.com/serverless/serverless/issues/4649

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: macOS 10.13.3
* ***Stack Trace***: 
```
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...

  Error --------------------------------------------------

  The CloudFormation template is invalid: S3 error: The specified bucket does not exist
For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```
* ***Provider Error messages***: none
