### ISSUE TITLE
Bug: Deploy fails when setting stream ARN explicitly with additional params

### ISSUE THREAD

**Issue by annebyrne** [serverless/serverless#4856]
# This is a Bug Report

## Description

* What went wrong?

Unable to deploy when kinesis event ARN is set explicitly with additional parameters such as `startingPosition`, rather than with `Fn::` syntax.

* What did you expect should have happened?

From the docs [here](https://serverless.com/framework/docs/providers/aws/events/streams#setting-the-batchsize-and-startingposition), it looks as if we could define our kinesis event in the following manner:
```
functions:
  preprocess:
    handler: handler.preprocess
    events:
      - stream:
          arn: arn:aws:kinesis:region:XXXXXX:stream/foo
          batchSize: 100
          startingPosition: LATEST
          enabled: false
```
* What was the config you used?
```
service: cx-save-user-device-from-segment

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: ${opt:stage, 'staging'}
  role: ${self:provider.stage}RoleArn
  environment:
    CwMetricName: ms-behind-iterator
    CwNamespace: cx-save-device-id

    productionStreamArn: arn:aws:kinesis:eu-west-1:219541440308:stream/traffic-events
    productionRoleArn: arn:aws:iam::219541440308:role/api-lambda-execute-role
    productionTableName: cx-device-id

    stagingStreamArn: arn:aws:kinesis:eu-west-1:161050250068:stream/traffic-events
    stagingRoleArn: arn:aws:iam::161050250068:role/kinesis-lambda
    stagingTableName: cx-user-device-id

    TableName: ${self:provider.stage}TableName

functions:
  addUserIdDevice:
    handler: lambda.addUserIdDevice
    events:
     - stream: 
         type: kinesis
         arn: ${self:provider.stage}StreamArn
         batchSize: 100
         startingPosition: TRIM_HORIZON
         enabled: true
```

* What stacktrace or error message from your provider did you see?

The following error was seen when attempting to deploy (more detailed stack trace below):
```
TypeError: Cannot read property 'replace' of undefined
    at Object.normalizeNameToAlphaNumericOnly (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
    at Object.getStreamLogicalId (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:228:13)
```

From looking at the [code](), it looks as if `streamName` is undefined as we are not setting the arn with the `Fn` key:

```
EventSourceArn = event.stream.arn;
....
....
const streamName = (function () {
              if (EventSourceArn['Fn::GetAtt']) {
                return EventSourceArn['Fn::GetAtt'][0];
              } else if (EventSourceArn['Fn::ImportValue']) {
                return EventSourceArn['Fn::ImportValue'];
              }
              return EventSourceArn.split('/')[1];
            }());
```
Replacing my original config code with `stream: 'arn:foo`, or `stream: Fn::` seems to resolve this issue. Not sure if this is just amending docs to reflect desired behaviour or a bug thats been introduced.

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: darwin
* ***Stack Trace***:
```
TypeError: Cannot read property 'replace' of undefined
    at Object.normalizeNameToAlphaNumericOnly (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
    at Object.getStreamLogicalId (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:228:13)
    at functionObj.events.forEach.event (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:119:16)
    at Array.forEach (<anonymous>)
    at serverless.service.getAllFunctions.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:41:28)
    at Array.forEach (<anonymous>)
    at AwsCompileStreamEvents.compileStreamEvents (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:16:47)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```

**Comment by ashtonmeuser** [comment]
Also having this issue. Using the [serverless-cf-vars](https://gitlab.com/kabo/serverless-cf-vars) plugin. 

The function below works perfectly fine when included in my `serverless.yml` file.

```
functions:
  something:
    name: project-${self:provider.stage}-something
    handler: something.handler
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          enabled: true
          arn:
            Fn::GetAtt: [DynamoDbItemTable, StreamArn]
```

When I replace that with the following, I get `Cannot read property 'replace' of undefined`. This happens when I attempt to run `sls deploy` and appears after the line that says `Serverless: Excluding development dependencies...`.

```
functions:
  something:
    name: project-${self:provider.stage}-something
    handler: something.handler
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          enabled: true
          arn: "#{DynamoDbItemTable.StreamArn}"
```

Stack trace when setting `SLS_DEBUG` to `true`:

```
Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'replace' of undefined
    at Object.normalizeNameToAlphaNumericOnly (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
    at Object.getStreamLogicalId (/usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/naming.js:228:13)
    at functionObj.events.forEach.event (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:119:16)
    at Array.forEach (<anonymous>)
    at serverless.service.getAllFunctions.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:41:28)
    at Array.forEach (<anonymous>)
    at AwsCompileStreamEvents.compileStreamEvents (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:16:47)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:390:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```
