### ISSUE TITLE
method, path validation vs. Unexpected token errors

### ISSUE THREAD

**Issue by PatrickHeneise** [serverless/serverless#4858]
# This is a Bug Report
## Description

For bug reports:
* What went wrong?
I've been going through docs and examples all day to deploy a function to Google Cloud Functions. Here are some official examples which don't work:

functions/list.js: `module.exports.get = (request, response) => { ...}`

```
functions:
  list:
    handler: functions/list.list
    events:
       - http:
          path: users
          method: get
          cors: true
```

This returns the following:

```
The "handler" property for the function "list" is invalid. Handlers should be plain strings referencing only the exported function name without characters such as "." or "/" (so e.g. "http" instead of "index.http"). Do you want to nest your functions code in a subdirectory? Google solves this by utilizing the "main" config in the projects package.json file. Please check the docs for more info.
```

I got this from an AWS example, so I guess google doesn't support it (but isn't that the point of serverless?). So I changed the handler, added an index.js to export the functions and got this:

```
  Error --------------------------------------------------
 
  Unexpected token : in JSON at position 19
```

That's the example from the serverless Google documentation, so it should work? It relates to `http`. I removed the method and cors to get to this:

```
functions:
  list:
    handler: list
    events:
       - http: GET users
```

Which works for deployment, but breaks `sls run` and I can't test the function locally anymore:

```
Failed to configure the Event Gateway. Failed to configure the Event Gateway. Failed to subscribe the event http to the function users-list due the error: Subscription doesn't validate. Validation error: "Missing required fields (method, path) for HTTP event."
```

* What did you expect should have happened?

`sls deploy` and `sls run` to work

* What was the config you used?

see above

* What stacktrace or error message from your provider did you see?

see above

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: macOS
* ***Stack Trace***:
* ***Provider Error messages***:
