### ISSUE TITLE
Add support for asynchronous lambda invocation with integration type AWS

### ISSUE THREAD

**Issue by bsdkurt** [serverless/serverless#4862]
# This is a Feature Proposal

## Description

API Gateway supports asynchronous lambda invocation when integration type is AWS. Described here:
https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-lambda.html
Currently it is not possible to configure this in serverless directly and requires a resource override to enable. This feature proposal is to add support for integration type AWS, asynchronous lambda invocation without using an resource override. 

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Asynchronous lambda invocation allows for a quick response back (e.g. 202 Accepted) while allowing the lambda to continue running. This would be desired if you wish to kick off a lambda that runs longer then the API GW 30 second timeout, or if the application needs a quick response without the need for direct success for failure of the longer running lambda.  

* If there is additional config how would it look

Add new integration type `AWS_ASYNC` that configures the `X-Amz-Invocation-Type` correctly:
```yaml
  lambda:
    handler: index.handler
    events:
      - http:
          path: users
          method: post
          integration: AWS_ASYNC
```
* Cloud Formation Information

`AWS_ASYNC` would set the integration type to AWS and add ` "integration.request.header.X-Amz-Invocation-Type": "'Event'"` to `Integration { RequestParameters: {} }` similar to as follows:
```
          "ApiGatewayMethodUsersPost": {
            "Type": "AWS::ApiGateway::Method",
            "Properties": {
              "HttpMethod": "POST",
              "RequestParameters": {
              },
              "Integration": {
                "IntegrationHttpMethod": "POST",
                "Type": "AWS",
                "RequestParameters": {
                  "integration.request.header.X-Amz-Invocation-Type": "'Event'"
                }
```
## Additional Data

* ***Serverless Framework Version you're using***:
serverless/serverless as of 4/28/2018
* ***Operating System***:
Ubuntu 16.04
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A

**Comment by bsdkurt** [comment]
@jjkirby Developed the following resource override to use as a work-around until the feature proposal is complete:
```yaml
resources:
   Resources:
     ApiGatewayMethodUsersPost:
       Type: AWS::ApiGateway::Method
       Properties:
         HttpMethod: POST
         Integration:
           IntegrationHttpMethod: POST
           Type: "AWS"
           RequestParameters:
              "integration.request.header.X-Amz-Invocation-Type": "'Event'"
```
@jjkirby If you find there is a need for additional resource overrides please add that information here. Thanks

**Comment by jjkirby** [comment]
Or just add an element like async which does the header settings under the hood such as:

```
lambda:
    handler: index.handler
    events:
      - http:
          path: users
          method: post
          integration: AWS
          async: true
```
