### ISSUE TITLE
sls sam export fails with multiple http endpoints on one function

### ISSUE THREAD

**Issue by SpaceHeroGuide** [serverless/serverless#4864]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
`sls sam export` fails when the serverless.yml contains multiple http endpoints for a single function. `sls deploy` however works.
* What did you expect should have happened?
I expected `sls sam export` to export a template with both http endpoints refering to the same function.
* What was the config you used?
**serverless.yml**
```yml
service: test

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: dev
  region: eu-central-1
    
plugins:
  - serverless-sam
  
package:
  exclude:
    - ../**
  include:
    - ../../bin/*
    
custom:
  legal: ${file(_legal.yml):legal}
    
functions:
  legal: ${self:custom.legal}
```

**_legal.yml**
```yaml
legal:
  handler: bin/wh-legal
  events:
# IMPRINT SCREEN FUNCTION
# GET /impressum
    - http:
        path: /impressum
        method: get
# TERMS OF USE SCREEN FUNCTION
# GET /nutzungsbedingungen  
    - http:
        path: /nutzungsbedingungen
        method: get
```

When removing the http path settings for `/nutzungsbedingungen` completely or adding the `handler` and `events` part in front of it one more time it works.

* What stacktrace or error message from your provider did you see?
```bash
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command sam
Serverless: Load command sam:export
Serverless: Invoke sam:export
Serverless: Working folder: /Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam
Serverless: Validate
Serverless: Preparing original CloudFormation template
Serverless: Packaging functions
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Export:
Serverless: Exporting resources
Serverless: Exporting outputs
Serverless: Exporting parameters
Serverless: Exporting conditions
Serverless: Exporting functions
Serverless: Exporting function: test-dev-home as TestDevHome
Serverless: Exporting function: test-dev-legal as TestDevLegal
 
  Error --------------------------------------------------
 
  Resource TestDevLegalLambdaPermission already exists
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Resource TestDevLegalLambdaPermission already exists
    at SamBuilder.addCustomResource (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/sam/SamBuilder.js:56:13)
    at SamBuilder.addLambdaPermission (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/sam/SamBuilder.js:63:10)
    at Object.keys.forEach (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/FunctionConverter.js:112:29)
    at Array.forEach (<anonymous>)
    at serverlessFunction.events.forEach (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/FunctionConverter.js:91:33)
    at Array.forEach (<anonymous>)
    at FunctionConverter.serverlessFunctionToSam (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/FunctionConverter.js:85:33)
    at allFunctions.forEach (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/SamGenerator.js:119:32)
    at Array.forEach (<anonymous>)
    at SamGenerator.readFunctions (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/SamGenerator.js:109:20)
    at SamGenerator.generate (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/lib/SamGenerator.js:58:10)
    at BbPromise (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/index.js:206:46)
    at SamPlugin.exportSam (/Users/matthias/Golang/src/github.com/SpaceHeroGuide/test/node_modules/serverless-sam/index.js:203:12)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```
## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: darwin
* ***Stack Trace***:
* ***Provider Error messages***:
