### ISSUE TITLE
allow s3 bucket that is linked for events to exist, do not require creation

### ISSUE THREAD

**Issue by silky** [serverless/serverless#4866]
if i have the following (overly-complicated) function definition:

```
functions:
  compute-projections:
    handler: handler.compute_projections
    events:
      - http:
          path: compute_projections
          method: get
      - s3:
          bucket: something-scratch
          event: s3:ObjectCreated:*
          rules:
              - prefix: lambda-test/
              - suffix: .xml

resources:
  Resources:
    S3Bucketsomethingscratch:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: something-scratch
    ComputeDashprojectionsLambdaPermissionPhotosS3:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - ComputeDashprojectionsLambdaFunction
            - Arn
        Principal: "s3.amazonaws.com"
        Action: "lambda:InvokeFunction"
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: "arn:aws:s3:::something-scratch"
```

then, if the `something-scratch` bucket _already exists_, the deployment command will fail.

all i want to do here is point this event at a pre-existing bucket, so that i can be consisently uploading files there.

how can i achieve this?

related to: https://github.com/serverless/serverless/issues/4840
