### ISSUE TITLE
Problems deploying from Amazon Linux EC2

### ISSUE THREAD

**Issue by sidewaiise** [serverless/serverless#4870]
# This is a Bug Report

## Description

I had to use Amazon Linux to build some project dependencies. So deploying from Amazon linux using serverless was the logical option after. However, when running `serverless deploy` on the Amazon Linux EC2 instance, I get the following:

``` shell
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Killed
```

No further information is provided, even when using `SLS_DEBUG=*`

I have assigned IAM role to the instance and tested aws cli - all working fine.

Here's a copy of `serverless.yaml`:

``` yaml
service: 
  name: myService

frameworkVersion: ">=1.1.0"

custom:
  bucket: bucket-name

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  region: ap-southeast-2

package:
  include:
    - lib/**

functions:
  fn:
    handler: fn.handler
    events:
      - http:
          method: get
          path: vectorize
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg

resources:
  Resources:
    S3BucketBucketname:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
```

## Expected behavior

Should deploy without error.
