### ISSUE TITLE
Can't evaluate ${self:custom.varName} from inside custom block when custom block is a file var

### ISSUE THREAD

**Issue by dehuszar** [serverless/serverless#4880]
# This is a Bug Report

## Description

My serverless.yml file uses the following pattern:

```
service: ServiceName
provider:
  name: aws
  runtime: nodejs8.10
  [...]
custom: ${file(sls-partials/custom.yml)}
functions: ${file(sls-partials/functions.yml)}
resources:
  Resources: ${file(sls-partials/resources.yml)}
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
```
When referencing custom-block vars from inside my functions.yml (i.e. `${self:custom.userPools.${self:custom.stage}}`) everything runs fine.

When trying to reference other custom vars from inside the custom block, `SLS_DEBUG=* sls deploy` exits prior to any invoking deploy with no errors posted.  So...
```
custom:
  domains:
    dev: api.dev
    stage: api.stage
    prod: api
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}.example.com
```
evaluates and deploys just fine when it lives in the top-level serverless.yml file, but when read from a `${file}` reference, it doesn't.

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Ubuntu 17.10
* ***Stack Trace***: No exceptions thrown
* ***Provider Error messages***: When deploy doesn't work, here's what is output
```
$ SLS_DEBUG=* sls deploy
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command create_domain
Serverless: Load command delete_domain
```
