### ISSUE TITLE
Different validation behavior between `serverless deploy` & `serverless deploy function`

### ISSUE THREAD

**Issue by ddimitrioglo** [serverless/serverless#4884]
# This is a `Bug Report`

## Description

* What went wrong?
I'm facing the validation issue when running `serverless deploy function --function facebook-events`
**BUT** everything is working as expected when I'm running `serverless deploy`

* What did you expect should have happened?
The same validation rules should be applied.

* What was the config you used?

```yml
...
functions:
  facebook-albums:
    handler: facebook-albums/index.handler
    package:
      include: ['facebook-albums/**']
    environment:
      API_TOKEN: ${ssm:facebookApiToken}

  facebook-events:
    handler: facebook-events/index.handler
    package:
      include: ['facebook-events/**']
    environment:
      COUNT: 6 # <== ISSUE 
      API_TOKEN: ${ssm:facebookApiToken}
...
```

* What stacktrace or error message from your provider did you see?

`Expected params.Environment.Variables['COUNT'] to be a string`

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: macOS 10.13.4
* ***Node.js Version***: v6.11.4
