### ISSUE TITLE
The bucket you tried to delete is not empty.

### ISSUE THREAD

**Issue by SandeepVattapparambil** [serverless/serverless#4893]
# This is a (Bug Report)

## Description
When trying to deploy a lambda function with an s3 bucket based trigger, the following error was shown.

```
Serverless Error ---------------------------------------
  An error occurred: S3BucketNylndatestings - The bucket you tried to delete is not empty.
```

For bug reports:
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (24.49 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: S3BucketNylndatestings - The bucket you tried to delete is not empty.

```
The following was the yml setu used.

```
service: aws-nodejs 
plugins:
  - serverless-offline
  - serverless-plugin-existing-s3
provider:
  name: aws
  stage: dev
  region: us-east-1
  profile: default
  runtime: nodejs6.10
  memorySize: 256
  timeout: 30
  environment:


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
       Fn::Join:
        - ""
        - - "*"
custom:
  ACCOUNT_ID: "338135766024"
  MEDIA_BUCKET: "nylndamedia-dev-bucket"
functions:
  cool:
    handler: handler.cool
    events:
      - existingS3:
          bucket: nylnda-testing-s3
#          bucket: nylndamedia-dev-bucket
          event: s3:ObjectCreated:PUT
          rules:
            - prefix: Reaction/Videos/
```
