### ISSUE TITLE
VPN attribute is not working on Serverless.yml

### ISSUE THREAD

**Issue by abtinzo** [serverless/serverless#4901]
# This is a Bug

## Description
VPN doesn't create proper settings for lambda when defined under provider

```
vpc: 
          securityGroupIds:
            - sg-0aXXXX
          subnetIds:
            - subnet-fb2XXX
            - subnet-eXXX
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Windows 10
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
Hi @abtinzo . Can you please fill in the issue template that is shown when creating a new bug? This helps us to understand what you've tried and analyze the issue.

Additionally, you should show how you declared the vpc settings under provider in this case like this
```
provider:
  vpc:
    securityGroupIds:
      - xxxx
    subnetIds:
      - yyyy
      - zzzz
```

Thank you.
