### ISSUE TITLE
Fn::Join is not allowed on role

### ISSUE THREAD

**Issue by zRosenthal** [serverless/serverless#4916]
# This is a Feature Proposal

## Description
Currently `Fn::Join` is not supported on the `role` node.
[Code](https://github.com/serverless/serverless/blob/2a3d57e3907ecce537bcf8d1b73074ed6a38a1b4/lib/plugins/aws/package/compile/functions/index.js#L36)
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I would like to be able to `Ref: AccountId` and build a role arn with `Fn::Join`
```yaml
role:
  Fn::Join:
    - ""
    - -  "arn:aws:iam::"
      - Ref: AWS::AccountId
      - ":role/MyRoleName"
```

If we agree this is a good feature to implement I would be happy to submit a PR as it looks like the code required is minimal and fairly straight forward.

**Comment by hounded** [comment]
Hi zRosenthal, 

I'm trying to implement a serverless dynamodb with scaling. How do I handle the join function with out the implementation !Join . Could you advise on how I could write this cloud formation in serverless, else I see no other way than SAM 

Cloud formation : 
```yaml
WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 15
      MinCapacity: 5
      ResourceId: !Join
        - /
        - - table
          - !Ref readings
      RoleARN: !GetAtt ScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
```
Serverless : 
```yaml 
WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 50
      MinCapacity: 5
      ResourceId: Fn::Join:
        - /
        - - table
          - Fn::Ref:readings
      RoleARN:
        Fn::GetAtt
          - ScalingRole
          - Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
```

**Comment by rayterrill** [comment]
Just ran into this same issue - would like to dynamically build the ARN for the pre-created role using FN::Join.

**Comment by aendrew** [comment]
It's really frustrating to be unable to provide a role without an account ID. I've tried like 5 different ways to work around this to no avail... 😞

**Comment by adamnoakes** [comment]
+1

**Comment by johanfagerstroem** [comment]
+1

this would be awsome to have

**Comment by f00f** [comment]
+1 (tried `!Sub`)

Is this limitation stated somewhere in the docs?
I would try creating a patch if someone could point me into the right direction to get started.

**Comment by f00f** [comment]
I dug through the code to find `https://github.com/serverless/serverless/blob/main/lib/plugins/aws/provider.js`.
There, `provider.iam.deploymentRole` is defined as `awsArn` which in turn allows `awsArnString` and `awsCfFunction`. Looks correct, all the way through till `awsCfSub`.

🤷‍♂️ Any clue why it would not accept a `!Sub` or `Fn::Sub`?

My serverless version:
Environment: win32, node 16.16.0, framework 3.21.0 (standalone), plugin 6.2.2, SDK 4.3.2

My service:
```
service: cross-account-canary
frameworkVersion: '3'
provider:
  name: aws
  iam:
    deploymentRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/CloudFormationExecutionRole"
```

`sls deploy` results in `Expected params.RoleARN to be a string`.

Same error with

```
  iam:
    deploymentRole:
      Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/CloudFormationExecutionRole"
```

The same sub works fine in another service, where it's used as principal in an `AssumeRolePolicyDocument`.
