### ISSUE TITLE
Shared API functionality has been broken on top of master

### ISSUE THREAD

**Issue by horike37** [serverless/serverless#4923]
# This is a (Bug Report)

## Description
It seems that Shared API functionality has been broken on top of master with following error when sls deploy. maybe any one of PRs have introduced this after releasing v1.26.1

```
$sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (409 B)...
Serverless: Validating template...
 
  Error --------------------------------------------------
 
  The CloudFormation template is invalid: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.8.1
     Serverless Version:     1.26.0
```
Here is serverless.yml
```yml
service: shared-service

provider:
  name: aws
  runtime: nodejs6.10
  apiGateway:
    restApiId: [ID]
    restApiRootResourceId: [ID2]

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
```

## Additional Data

* ***Serverless Framework Version you're using***: top of master
* ***Operating System***: darwin
* ***Stack Trace***: above
* ***Provider Error messages***: above
