### ISSUE TITLE
Serverless Variables: external JS files do not get reference to serverless object

### ISSUE THREAD

**Issue by jkruse14** [serverless/serverless#4924]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
I tried to reference the Serverless object in an external JS file to use as a variable in my config, but it comes back as `undefined`
* What did you expect should have happened?
Ability to reference teh Serverless object and config as documented here:
https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-javascript-files
* What was the config you used?
here's a snippet:
**serverless.yml**
```
provider:
  name: aws
  security-groups: ${opt:security-groups, self:custom.local}
  subnets: ${opt:subnets, self:custom.local}
  vpc:
    securityGroupIds:
      - ${file(./scripts/serverless/lib/config.js):lists.securityGroups}
    subnetIds:
      - ${file(./scripts/serverless/lib/config.js):lists.subnets}
```
**config.js**
```
module.exports.lists = (serverless) => {
    console.log(serverless); // prints 'undefined'
    return ({
        subnets: serverless.provider.subnets.split(','), // error: Cannot read property 'provider' of undefined
        securityGroups: serverless.provider['security-groups'].split(','),
    });
};
```
**
* What stacktrace or error message from your provider did you see?
Noted above:
`Type Error: Cannot read property 'provider' of undefined`

## Additional Data

* ***Serverless Framework Version you're using***: 1.23.0
* ***Operating System***: MacOS High Sierra 10.13.3
* ***Stack Trace***:
* ***Provider Error messages***:
