### ISSUE TITLE
API Gateway Resource Policy Support Feature

### ISSUE THREAD

**Issue by ptrivedi9400** [serverless/serverless#4926]
# This is a Feature Proposal

## Description
Recently API Gateway (April 2nd, 2018) started providing resource policy to handle each API. Which includes blacklisting IP or allowing denying IP.

This is currently only supported by the API Gateway API, AWS console, AWS SDK and not yet by CloudFormation, which I'm guessing is why it is not yet supported by Serverless. 

[Announcement](https://aws.amazon.com/about-aws/whats-new/2018/04/amazon-api-gateway-supports-resource-policies/)

[Blog for console-based setup](https://lobster1234.github.io/2018/04/14/amazon-api-gateway-ip-whitelisting/)

Probably best to wait for CloudFormation to catch up on this so I'm just registering for a future task.

For feature proposals:
* IP Blacklisting or allowing a certain type of method. Basically IAM type policy but without creating IAM role/policy.
* Json input or parameter based information can be set up.  

Note
** [Forum Question in relation](https://forum.serverless.com/t/api-gateway-resource-policy/4215
)

**Comment by horike37** [comment]
@ptrivedi9400 
Sounds good to introduce this functionality :smile: 
I just added `wait-cf-support` tag so that someone can get started to implement it after support.

**Comment by laardee** [comment]
@horike37 Just noticed that CloudFormation supports resource policy. Here's a PR https://github.com/serverless/serverless/pull/5071

**Comment by horike37** [comment]
@laardee 
Awesome! Great!
We will review as soon as possible 👍

**Comment by superandrew** [comment]
such a good news! would this enable serverless to use private vpc endpoints?

**Comment by dailyherold** [comment]
@superandrew still believe there's a pre-req to create the vpc endpoint (type integration). CF just added support for that end of last week, but don't think it's in scope of this PR.

**Comment by superandrew** [comment]
@dailyherold does this mean that we have to manually create the VPC endpoint in API Gateway and link it manually to the CloudFormation stack which has to be built without the API Gateway?

**Comment by laardee** [comment]
@superandrew this PR (https://github.com/serverless/serverless/pull/5080) adds support for private endpoints

**Comment by dailyherold** [comment]
@superandrew three parts to this private endpoint cocktail based on my recent implementation:

1. VPC Endpoint (Integration type) which was added [June 21st](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html). Need to specify service name `com.amazonaws.{region}.execute-api`, a SG that allows 443 ingress, associated subnets (where the ENIs will be created), Enable Private DNS set to true, and the VPC you're setting this up in must have DNS resolution enabled (default is true).
2. API Gateway "Endpoint Type" set to Private.
3. API Gateway resource policy allowing api execution from the VPC Endpoint ID.

\#2 is being taken care of by #5080, \#3 by this PR, and \#1 is still a pre-requirement in my mind because the VPCE ID must be available at time of serverless deploy, or you update the resource policy after. I'm still somewhat new to serverless so not sure best practice for creating or updating other dependent infra code? Resource block or plugin?

This week I implemented temporary solutions in anticipation of `1.28` release in my apps Jenkins pipeline. For my VPC endpoint I kept that infra code outside my serverless repo because it is generic and something that multiple services/repos will utilize. Then for API Gateway stuff I used the aws cli to [update-rest-api](https://docs.aws.amazon.com/cli/latest/reference/apigateway/update-rest-api.html) both for endpoint type and resource policy. I then run the serverless deploy again after because any change to the resource policy [requires a redeploy](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html).

**Comment by jkon** [comment]
Hi, I am trying to use this feature to add an IP whitelist to my qa and uat app environments. But when I deploy, I'm not seeing the update in the api gateway console. I tried removing the existing policy to see if it just wasn't updating an existing one, but it looks like it won't even add one when doesn't exist. 
My resource policy looks like this:
```
resourcePolicy:
    qa:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          IpAddress:
            aws:SourceIp: ${self:custom.ipWhitelist}
    # uat whitelist should be the same as qa at least for now
    uat:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          IpAddress:
            aws:SourceIp: ${self:custom.ipWhitelist}
    prod:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*

  ipWhitelist:
    - "123.123.123.123/24"
   ```
Any insights on why my policy isn't updating would be appreciated. Thanks

**Comment by jkon** [comment]
@laardee that is essentially what I had, but I made a couple of little changes from yours, but still no dice. The policy remains unchanged after deployments. Is there anything else that I might be missing?

**Comment by laardee** [comment]
@jkon Which serverless version are you using? There were some issues with variable resolution in 1.30.X version. 

Did you check if the CloudFormation template contains the policy?  Open the `.serverless/cloudformation-template-update-stack.json` and search for `ApiGatewayRestApi`, it should contain 
```yaml
        "Policy": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": "*",
              "Action": "execute-api:Invoke",
              "Resource": [
                "execute-api:/*/*/*"
              ]
            }
          ]
        }
```
