### ISSUE TITLE
sls info reports "api keys: None" although there is an api key

### ISSUE THREAD

**Issue by oleschaper** [serverless/serverless#4928]
# This is a Bug Report

## Description

* What went wrong?

`sls info -v`

reports 

`api keys:
  None`

although there is an api key (and also a usage plan).

Unfortunately, this is not a consistent behaviour, we are deploying 10 services, all with the same configurations. Most of them work fine, but 1 or 2 show the described behaviour.
If it fails once, it does also fail for every following attempt.

If I delete the stack and completely recreate it, I can see from the Cloudformation log output, that the api key and usage plan is created successfully and I can also see the api key on the AWS control center.

Sometimes I can fix it by deleting the stack and recreating it, but this does also not always work.
(See the log below)

- Maybe this is some kind of timing issue? But it also does not help, if I wait a few minutes after deployment before I do `sls info` which brings me to my next question:

- Where does sls info gather it's information from? Can I execute it manually somehow? If not:

- How can I debug this?

Any help would be greatly appreciated!

----

* What did you expect should have happened?
It should print the correct api key.

* What was the config you used?

* What stacktrace or error message from your provider did you see?
None

Similar or dependent issues:
* None found

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: Mac OSX High Sierra
* ***Stack Trace***: None
* ***Provider Error messages***: None

----
Log:

```
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - SocialUpdateFriendLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::ApiKey - ApiGatewayApiKey1
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::UsagePlan - ApiGatewayUsagePlan
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::UsagePlan - ApiGatewayUsagePlan
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::UsagePlan - ApiGatewayUsagePlan
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::ApiKey - ApiGatewayApiKey1
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::ApiKey - ApiGatewayApiKey1
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::UsagePlanKey - ApiGatewayUsagePlanKey1
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::UsagePlanKey - ApiGatewayUsagePlanKey1
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::UsagePlanKey - ApiGatewayUsagePlanKey1
CloudFormation - CREATE_COMPLETE - AWS::Events::Rule - WarmUpPluginEventsRuleSchedule1
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - WarmUpPluginLambdaPermissionEventsRuleSchedule1
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - WarmUpPluginLambdaPermissionEventsRuleSchedule1
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - WarmUpPluginLambdaPermissionEventsRuleSchedule1
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - Test-Service-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - Test-Service-dev
Serverless: Stack update finished...
Service Information
service: Test-Service
stage: dev
region: us-east-1
stack: Test-Service-dev
api keys:
  None
endpoints:
  ANY - https://abcdefghij.execute-api.us-east-1.amazonaws.com/dev/social/updatefriend
  ANY - https://abcdefghij.execute-api.us-east-1.amazonaws.com/dev/social/addfriend
  ANY - https://abcdefghij.execute-api.us-east-1.amazonaws.com/dev/social/addfacebookfriends
  ANY - https://abcdefghij.execute-api.us-east-1.amazonaws.com/dev/social/getfriendlist
functions:
  socialUpdateFriend: Test-Service-dev-socialUpdateFriend
  socialAddFriend: Test-Service-dev-socialAddFriend
  socialAddFacebookFriends: Test-Service-dev-socialAddFacebookFriends
  socialGetFriendList: Test-Service-dev-socialGetFriendList
  warmUpPlugin: Test-Service-dev-warmUpPlugin

Stack Outputs
ServiceEndpoint: https://abcdefghij.execute-api.us-east-1.amazonaws.com/dev
ServerlessDeploymentBucketName: Test-Service-dev-serverlessdeploymentbucket-123456789
```

**Comment by oleschaper** [comment]
Ok, so nobody knows anything?

**Comment by iannickb** [comment]
We are having the same problem. I wonder it is it related to defining a custom usage plan.

**Comment by id-kemo** [comment]
The very same issue is happening on our end. Would really appreciate any hints or any workaround.

**Comment by molinan2** [comment]
I have the same issue: after every `serverless deploy` or `sls info -v`, it shows the `api keys:  None` message. However, the api keys are created and the requests work as expected.

My workaround for this is doing the first `serverless deploy` without `apiKeys` in the `serverless.yml`. Once done, I add the `apiKeys` and repeat the `serverless deploy`. This time the `api keys` are shown in the console, no matter the stage.

**Comment by msafder** [comment]
The api keys are NOT appearing in the API Gateway for me. What is the best practice for this going forward of is this a legitimate bug?

**Comment by dschep** [comment]
I attempted to reproduce this issue in [dschep-bug-repos/sls-4928](https://github.com/dschep-bug-repos/sls-4928) but it printed out an API key as expected. Could one of you share a `serverless.yml` that causes this issue?

Output from my test:
```
[:tmp] master $ sls create -t aws-nodejs -n sls-4928 -p sls-4928
[:tmp] master $ cd sls-4928
[:sls-4928] master $ sls deploy
Serverless: WARNING: Missing "tenant" and "app" properties in serverless.yml. Without these properties, you can not publish the service
to the Serverless Platform.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (387 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Stack update finished...
Service Information
service: sls-4928
stage: dev
region: us-east-1
stack: sls-4928-dev
api keys:
  None
endpoints:
  None
functions:
  hello: sls-4928-dev-hello
layers:
  None
[:sls-4928] master 1 $ vim serverless.yml # edit to add event & api key!
[:sls-4928] master 1 $ git diff
diff --git a/serverless.yml b/serverless.yml
index ee1c332..5c18f3f 100644
--- a/serverless.yml
+++ b/serverless.yml
@@ -20,6 +20,8 @@ service: sls-4928 # NOTE: update this with your service name
 provider:
   name: aws
   runtime: nodejs8.10
+  apiKeys:
+    - testApiKey

 # you can overwrite defaults here
 #  stage: dev
@@ -61,10 +63,10 @@ functions:
 #    The following are a few example events you can configure
 #    NOTE: Please make sure to change your handler code to work with those events
 #    Check the event documentation for details
-#    events:
-#      - http:
-#          path: users/create
-#          method: get
+    events:
+      - http:
+          path: users/create
+          method: get
 #      - s3: ${env:BUCKET}
 #      - schedule: rate(10 minutes)
 #      - sns: greeter-topic
[:sls-4928] master $ sls deploy
Serverless: WARNING: Missing "tenant" and "app" properties in serverless.yml. Without these properties, you can not publish the service
to the Serverless Platform.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (387 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
................................
Serverless: Stack update finished...
Service Information
service: sls-4928
stage: dev
region: us-east-1
stack: sls-4928-dev
api keys:
  testApiKey: IytTSzuz0q8dsicm2BWoX8YoaObucYTy5DstMRRJ
endpoints:
  GET - https://d7vn4s9swf.execute-api.us-east-1.amazonaws.com/dev/users/create
functions:
  hello: sls-4928-dev-hello
layers:
  None
```

**Comment by id-kemo** [comment]
I have noticed one thing, particularly with naming the API key, see the serverless.yml below.

```
service: SomeService

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
# ## This works every single time.
  apiKeys:
    - ${self:provider.stage}-key
# ## Also this would work, however we lost the option of fallback value 'dev'
# apiKeys:
#   - ${opt:stage}-key
# ## Again, this works as well (when creating new stack)
# apiKeys:
#   - fixedNamekey
# ## However this format has always caused the key was not created
#  apiKeys:
#    - key_${self:provider.stage}

functions:
  someLambda:
    handler: handler.main
    memorySize: 128
    events:
      - http:
          path: somePath
          method: get
          private: true
          cors: true

```

**Comment by molinan2** [comment]
I'm using this kind-of small template:

```
service: myService

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  apiName: myServiceApi-${self:provider.stage}
  timeout: 30
  apiKeys:
    - myServiceAPiKey-${self:provider.stage}

functions:
  myFunction:
    handler: index.handler
    name: myFunction-${self:provider.stage}
    description: A description for this microservice
    timeout: 8
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: myEndpoint
          method: post
          private: true
```

This happened randomly in multiple projects. They only differ in the number of HTTP events and the naming convention (`myApiKey-${self:provider.stage}` vs. `my-api-key-${self:provider.stage}`).

**Comment by iamtekeste** [comment]
Do we know if this is being fixed or if there is a workaround for it?

**Comment by molinan2** [comment]
This has not happened to me even once since recent versions (>1.46.0). Previous to this, it was a 50/50! I don't have more details, but it's fine for me now (thanks 🙂).

**Comment by navrkald** [comment]
I had this issue with Serverless 1.35.1 but after upgrade to 1.57.0 it works. I think this issue could be closed.

**Comment by kelvinluime** [comment]
This issue still happens to me as the api keys section in deploy output is always None. sls version 1.78.1

**Comment by isupremedyou** [comment]
I just followed this documentation and also had this issue:
https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#setting-api-keys-for-your-rest-api

**Comment by duc2019** [comment]
Same issue here, this is my serverless.yml.

```
service: service
frameworkVersion: '2'
provider:
  name: aws
  stage: ${opt:stage, 'testing'}
  region: ${opt:region, 'ap-northeast-1'}
  profile: ${opt:profile, 'saml'}
  stackName: 'sls-${self:provider.stage}-xxx'
  apiName: 'sls-${self:provider.stage}-xxx'
  runtime: nodejs12.x
  apiKeys:
    - xxx-api-key
plugins:
  - serverless-cloudformation-sub-variables
  - serverless-apigateway-service-proxy
custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /v1/xxx/catalog
        method: post
        queueName: !GetAtt CatalogQueue.QueueName
        private: true
        cors: true
resources:
  Resources:
    CatalogQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'sls-${self:provider.stage}-xxx-queue-catalog'
```

The version of serverless is 2.3.0.

**Comment by chenjr95** [comment]
I'm having the same issue on v 2.4.0

**Comment by hanischandrew** [comment]
I was able to work around this by adding a bogus "private" lambda function. Once that was added, it created the api key.

```
...

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  apiKeys:
    - ${opt:stage, self:provider.stage}-${self:service}-api-key

custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /registration
        method: post
        queueName: !GetAtt MessageQueue.QueueName
        private: true
        requestParameters:
          'integration.request.querystring.MessageGroupId': "'UniqueQueue'"

functions:
  healthCheck:
    handler: handler.healthCheck
    events:
      - http:
          path: /health
          private: true
          method: get

plugins:
  - serverless-apigateway-service-proxy

...
```
