### ISSUE TITLE
LogGroup ignores stage flag passed in from CLI tool.

### ISSUE THREAD

**Issue by bvanderlugt** [serverless/serverless#4929]
# This is a Bug Report

## LogGroup not being named correctly with the --stage flag

When the serverless.yml has no stage key, and you use the --stage flag, the LogGroup created does not use the value from the flag. Instead, LogGroup will be named using the default dev stage.

To reproduce, create a serverless.yml with no stage specified.

sls --stage test deploy 
```
service: banana

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    name: hello-${self:provider.stage}
       Value: "Some output value"
```

The relevant cloudformation-template-update-stack.json
```
...
    "HelloLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/hello-dev"
      }
    }
...
```

serverless v1.26.1
osx 10.13.4
