### ISSUE TITLE
Default values for cf references

### ISSUE THREAD

**Issue by walery** [serverless/serverless#4940]
# This is a (Bug Report / ~Feature Proposal~)

Using cf references it's not possible to provide default values. Example:

    ${cf:non-existing-stack.foo, 'bar'}

## Description

For bug reports:
* What went wrong?

Default value was not picked. Instead of this I got error message:

      Serverless Error ---------------------------------------

      Stack with id non-existing-stack does not exist

* What did you expect should have happened?

Because I've set default value this should be used.

* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: darwin
* ***Stack Trace***:
* ***Provider Error messages***: Stack with id non-existing-stack does not exist

**Comment by kobim** [comment]
The existing behaviour in case of a non-exported variable from a stack is resulting in error too:
```
  Serverless Error ---------------------------------------

  Trying to request a non exported variable from CloudFormation. Stack name: "my-prod-stack" Requested variable: "foo".
```

Is the appropriate fix is to allow default values in both cases, or throw an error?

I like the first approach (not throwing an error), as there's a warning shown if a default parameter isn't specified:
```
 Serverless Warning --------------------------------------

  A valid CloudFormation stack/variable to satisfy the declaration 'cf:my-prod-stack.foo' could not be found.
```

What do you think?

**Comment by HyperBrain** [comment]
From a CI/CD perspective it is in my opinion better to error out than to product non-working deployments silently. In the worst case a wrongly set variable value might not be noticed immediately in a deployed system and lead to weird behavior that is difficult to debug.
Serverless as a deployment tool cannot know which default value would be appropriate - you do not know what is stored in a CF variable. It could just be anything with any semantical meaning.

**Comment by J-Rojas** [comment]
I'm having similar trouble when first initializing my deployment. My lambda functions depend on output from a CF stack, but the CF stack is defined in the resources section so the variable is not yet defined on the first deployment. After the first deployment, everything works well.

Is there a best practice for solving this dependency cycle problem?

**Comment by kobim** [comment]
@J-Rojas any reason you refer to Outputs rather than actual Resources of your stack?
Can you share your serverless.yml so I can have a look?

**Comment by J-Rojas** [comment]
@kobim, I need to reference Outputs generated by AWS CF stack that I don't define directly in my CF template. For example, I need the URL to a RDS instance that is auto-generated after the CF stack is created.

Here's a sample. I found the only way to fix this 'chicken-egg' cycle was to break up the serverless file in two; one part would handle the resources, while the other would handle deploying the lambdas that rely on these resources.

If the CF stack deployment was somehow processed before the lambdas, then my specific problem would not exist.

```
plugins:
  - serverless-python-requirements
  - serverless-scriptable-plugin
service: database-serverless

custom:
  pythonRequirements:
    dockerizePip: non-linux

  scriptHooks:
    after:aws:deploy:deploy:updateStack: sls invoke -f configure-database

provider:
  name: aws
  runtime: python3.6
  environment:
    DATABASE_URL: ${cf:database-serverless-${opt:stage,'dev'}.DatabaseUrl}
    DATABASE_PORT: ${cf:database-serverless-${opt:stage,'dev'}.DatabasePort}
    DATABASE_USERNAME: dbadmin
    DATABASE_PASSWORD_SSM_KEY: DATABASE_PASSWORD_SSM_KEY
    DATABASE_NAME: db
    DATABASE_NAMES: db_v1
    DATABASE_USERS: db_user
    DATABASE_PASSWORD_KEYS: DB_V1_PASSWORD

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource:  arn:aws:ssm:us-west-2:*:parameter/*
    - Effect: "Allow"
      Action:
        - "ssm:PutParameter"
      Resource:  arn:aws:ssm:us-west-2:*:parameter/*

# you can overwrite defaults here
  stage: dev
  region: us-west-2

functions:

  configure-database:
    handler: database.bootstrap_database

resources:
  Resources:

    DBInstance:
      Type: "AWS::RDS::DBInstance"
      Properties:      
        DBInstanceClass: db.t2.small
        Engine: postgres        
        MasterUsername: dbadmin
        MasterUserPassword: "SomePassword"
        DBName: esdb
        Port: 5432                
        AllocatedStorage: 20
        PreferredBackupWindow: 06:14-06:44
        BackupRetentionPeriod: 6
        DBSecurityGroups: []
        VPCSecurityGroups: [sg-0b345777]
        DBParameterGroupName: encrypted-db          
        AvailabilityZone: us-west-2a
        DBSubnetGroupName: default
        PreferredMaintenanceWindow: sun:13:19-sun:13:49
        MultiAZ: false
        EngineVersion: 9.6.6
        AutoMinorVersionUpgrade: true
        LicenseModel: postgresql-license
        PubliclyAccessible: true
        StorageType: gp2        
        StorageEncrypted: true
        KmsKeyId: arn:aws:kms:us-west-2:*:key/*
        CopyTagsToSnapshot: false
        MonitoringInterval: 0
  Outputs:
    DatabaseUrl:
      Description: The url for the database
      Value:
        "Fn::GetAtt": [ DBInstance, Endpoint.Address ]
    DatabasePort:
      Description: The port for the database
      Value:
        "Fn::GetAtt": [ DBInstance, Endpoint.Port ]
```

**Comment by kobim** [comment]
You can directly reference the Resource in your environment variables definition:
```yml
provider:
  name: aws
  runtime: python3.6
  environment:
    DATABASE_URL:
      "Fn::GetAtt": [ DBInstance, Endpoint.Address ]
    DATABASE_PORT:
      "Fn::GetAtt": [ DBInstance, Endpoint.Port ]
```

(and even omit the Outputs section)

**Comment by J-Rojas** [comment]
@kobim that worked! I didn't realize I could use references in the environment section. Thanks for the help.

**Comment by ivanbarlog** [comment]
@kobim how would you solve the reference for Cognito UserPoolId in ENV variables?

I tried `Ref: LogicalNameOfTheUserPool` but I get circular reference error. When I am trying the `${cf:myStack-myStage.UserPoolId}` where `UserPoolId` is Output of `Ref: LogicalNameOfTheUserPool` I get the `Stack with id myStackId does not exist`.

From the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html) I can read that only `Arn` can be read via `Fn::GetAtt` which contains the UserPoolId which I need to reference. Should I just parse it from there or there is some better way to obtain UserPoolId within ENV variables that you can think of?

Thanks for help

**Comment by kobim** [comment]
You didn't share your _Resources_ section, but I'll assume it is probably like:
```yaml
Resources:
  LogicalNameOfTheUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: 'My Pool'
```

hence you can refer to it in the env variables as following:
```yaml
provider:
  environment:
    USER_POOL:
      Ref: LogicalNameOfTheUserPool
```

Generally, if you don't use the Outputs of your CloudFormation stack **outside the stack**, you don't need to define it at all. Just refer to your resources inside _serverless.yml_ where required.

Hope this makes sense.

**Comment by ivanbarlog** [comment]
Thanks @kobim that was the first thing I have tried but unfortunately that caused me a circular dependency :-(

```
  The CloudFormation template is invalid: Circular dependency between resources: [lots, of, my, resource, logical, names, giving, me, no clue, where, the, circular, dependency, may, be]
```

**Comment by kobim** [comment]
Do you mind sharing the yml file?

**Comment by kobim** [comment]
It sure looks like a `serverless-appsync-plugin` issue - sid88in/serverless-appsync-plugin#82.

An alternative will be as you said - defining the AppSync resources yourself (that issue has a nice example of that)

**Comment by mikecann** [comment]
@ivanbarlog @kobim I have exactly the same issue (with userpoolid and circular references) and im not using appsync.

The following produced this error:

```
  The CloudFormation template is invalid: Circular dependency between resources: [SecretLambdaFunction, HelloLambdaPermissionApiGateway, PreSignUpLambdaFunction, ApiGatewayDeployment1538103844756, SecretLambdaPermissionApiGateway, ApiGatewayMethodHelloGet, MyUsersClient, SecretLambdaVersionOFfqoJDtyCrmcRj0j0QB6PGp0pgv99GQsTs6k1QppI, HelloLambdaFunction, PreSignUpLambdaPermissionCognitoUserPoolMyUserPoolTriggerSourcePreSignUp, PreSignUpLambdaVersion6TuGz1NCl26cdNufjAG9T7N4llBX58Jsjm9miEdsg, HelloLambdaVersionwlFLXuH5zH8AGM9gB3D6nyy4aPgYZAAkkqN5vzKPH0, ApiGatewayMethodSecretPost, CognitoUserPoolMyUserPool]
```

In serverless.yml:

```
service:
  name: my-service

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  developer: ${file(./src/config/local.config.json):DEVELOPER}
  prefix: ${self:service}-${self:provider.stage}
  webpack:
    includeModules: true # enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, env:SERVERLESS_STAGE, self:custom.developer}
  region: ${opt:region, 'ap-southeast-2'}
  memorySize: 256
  environment:
    REGION: ${self:provider.region}
    AWS_USER_POOL_ID:
      Ref: CognitoUserPoolMyUserPool

functions:

  hello:
    handler: src/api/hello/hello.main
    events:
      - http:
          method: get
          path: hello

  secret:
    handler: src/api/secret/secret.main
    events:
      - http:
          method: post
          path: secret
          authorizer: aws_iam

  preSignUp:
    handler: src/triggers/cognito/preSignUp/preSignUp.main
    events:
      - cognitoUserPool:
          pool: MyUserPool
          trigger: PreSignUp

resources:
  - ${file(resources/user-pool.yml)}
```
in resources/user-pool.yml
```
Resources:
  # The pool for our users
  CognitoUserPoolMyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MyUsers_${self:provider.stage}
      EmailVerificationSubject: Your verification code
      SmsAuthenticationMessage: Your authentication code is {####}.
      AutoVerifiedAttributes:
        - phone_number
      LambdaConfig: {}
      AdminCreateUserConfig:
        InviteMessageTemplate:
          EmailMessage: "Your username is {username} and temporary password is
            {####}. "
          EmailSubject: "Your temporary password"
          SMSMessage: "Hi, Your username is {username} and temporary password is
            {####}. "
        UnusedAccountValidityDays: 7
        AllowAdminCreateUserOnly: false
      EmailConfiguration: {}
      AliasAttributes:
        - email
        - phone_number
      Policies:
        PasswordPolicy:
          RequireLowercase: false
          RequireSymbols: false
          RequireNumbers: true
          MinimumLength: 12
          RequireUppercase: false
      UserPoolTags: {}
      SmsVerificationMessage: "Your Account verification code is {####}. "
      EmailVerificationMessage: "Your verification code is {####}. "

  # The client used to connect to the pool
  MyUsersClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: MyUsersClient_${self:provider.stage}
      UserPoolId:
        Ref: CognitoUserPoolMyUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

# Outputs are needed for the "setStage" script to work
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPoolMyUserPool

  UserPoolClientId:
    Value:
      Ref: MyUsersClient
```
