### ISSUE TITLE
Deep custom variables are not loaded properly when using ${file()}

### ISSUE THREAD

**Issue by bvalerius** [serverless/serverless#4953]
# This is a Bug Report

## Description
Variables are no longer loaded from custom config using `${file()}` with deep vars

Example: serverless.yml
```yaml
provider:
  name: aws
  stage: ${env:NODE_ENV}
  vpc:
    securityGroupIds: ${self:custom.config.stage.vpc.securityGroupIds}

custom:
  config:
    stage: ${file(config/${self:provider.stage}.yml)}
```

Example: my_stage.yml
```yaml
vpc:
  securityGroupIds:
    - sg-foo
```

Similar or dependent issues:
* #4946

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.1
* ***Operating System***: OSX 10.13.4
* ***Stack Trace***:
* ***Provider Error messages***:
```
Serverless Warning --------------------------------------
  A valid undefined to satisfy the declaration 'deep:2.vpc.securityGroupIds' could not be found.
```
