### ISSUE TITLE
Too many requests cause exception, while retry request should be done

### ISSUE THREAD

**Issue by maciejtreder** [serverless/serverless#4957]
# This is a Bug Report

## Description

For bug reports:
* After updating to version 1.27.1 I runned into 'Too many requests' error ([when using serverless-apigw-binary plugin](https://github.com/maciejtreder/serverless-apigw-binary))
* As in version 1.26.x - request should be retried
* Used config:
```
service: my-service

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 192
  timeout: 10
  stage: production
  region: eu-central-1

package:
  exclude:
   - src/**
   - node_modules/**
   - firebug-lite/**
   - e2e/**
   - coverage/**
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/binary-case/**'
   - '!node_modules/type-is/**'
   - '!node_modules/media-typer/**'
   - '!node_modules/mime-types/**'
   - '!node_modules/mime-db/**'

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /

```

* What stacktrace or error message from your provider did you see?
```
  Serverless Error ---------------------------------------
 
  Too Many Requests
 
  Stack Trace --------------------------------------------
 
ServerlessError: Too Many Requests
    at BbPromise.fromCallback.catch.err (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:262:11)
From previous event:
    at persistentRequest (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:250:13)
    at doCall (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:206:9)
    at BbPromise (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:219:14)
From previous event:
    at persistentRequest (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:204:38)
    at Object.request.requestQueue.add [as promiseGenerator] (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:240:49)
    at Queue._dequeue (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/promise-queue/lib/index.js:153:30)
    at /Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/promise-queue/lib/index.js:109:18
From previous event:
    at Queue.add (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/promise-queue/lib/index.js:94:16)
    at AwsProvider.request (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:240:39)
    at BinarySupport.createDeployment (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless-apigw-binary/src/index.js:30:26)
    at putSwagger.then (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless-apigw-binary/src/index.js:64:21)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at getApiId.then.apiId (/Users/mtreder/Documents/private/work/angular-universal-serverless/application/node_modules/serverless-apigw-binary/src/index.js:62:51)
    at <anonymous>
```

In version 1.26.1 output for same configuration is:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (1.29 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....................
Serverless: Stack update finished...
Service Information
service: binary-express-maciej-treder
stage: production
region: eu-central-1
stack: binary-express-maciej-treder-production
api keys:
  None
endpoints:
  ANY - https://k904suh2ag.execute-api.eu-central-1.amazonaws.com/production/{proxy+}
  ANY - https://k904suh2ag.execute-api.eu-central-1.amazonaws.com/production
functions:
  api: binary-express-maciej-treder-production-api
Serverless: 'Too many requests' received, sleeping 5 seconds
Serverless: 'Too many requests' received, sleeping 5 seconds
```

And application is deployed succesfully
