### ISSUE TITLE
Optional path parameter

### ISSUE THREAD

**Issue by Baptiste-Garcin** [serverless/serverless#4971]
# This is a Bug Report

I am trying to pass an optional path parameter. As specified in the [official documentation](https://serverless.com/framework/docs/providers/aws/events/apigateway/#request-parameters), I declared the events in the serverless.yml this way:

```
events:
      - http:
          path: user/{id}
          method: get
          request:
            parameters:
              paths:
                id: false
```

When I make a call with postman to `/url/user`, I received `{ "message": "Missing Authentication Token" }`

In the other hand, when I make a call to `/url/user/12`, everything is going well.

Find the complete serverless.yml :
```

service: lambda-serverless
provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: eu-west-3

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: *******

functions:
  getUser:
    handler: user.getUser
    events:
      - http:
          path: user/{id}
          method: get
          request:
            parameters:
              paths:
                id: false

resources:
  Resources:
    movieTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```

## Additional Data

* Serverless version: 1.27.2
* OS: Debian 9*
* Provider: AWS
