### ISSUE TITLE
S3 _Files_ for Configuration Feature Proposal

### ISSUE THREAD

**Issue by aloof-ruf** [serverless/serverless#4974]
# Feature Proposal: S3 _files_ for configuration

## Description

It is possible to grab individual attributes from S3 Objects but I would find it more convenient to grab entire JSON/YAML files from a single S3 Object. This would be an imitation of the ${file} behaviour. For example, instead of having...

```yaml
# ...

functions:
  api:
    handler: something.api
    environment:
      ARG1: ${s3:my-bucket/${opt:deploy-env}/ARG1}
      ARG2: ${s3:my-bucket/${opt:deploy-env}/ARG2}
      ARG3: ${s3:my-bucket/${opt:deploy-env}/ARG3}
      ARG4: ${s3:my-bucket/${opt:deploy-env}/ARG4}
    events:
      - http:
          path: /something
          method: post

# ...
```

It would be handy to go like...

```yaml
# ...

functions:
  api:
    handler: something.api
    environment: ${s3file:my-bucket/${opt:deploy-env}}
    events:
      - http:
          path: /something
          method: post

# ...
```

Where the S3 Object being loaded is a JSON or YAML file. This behaviour is already available for local JSON/YAML files and I find it convenient. It would also clean up things in an S3 bucket providing those configurations.
