### ISSUE TITLE
pathParameters should be uri decoded

### ISSUE THREAD

**Issue by ichernev** [serverless/serverless#5037]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? -- url pathParameters should be uri decoded
* What did you expect should have happened? -- url pathParameters should be uri decoded
* What was the config you used?
```
functions:
  create:
    handler: posts.post_detail
    events:
      - http:
          path: posts/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
```

Now try to pass `/posts/@` --url encoded--> `/posts/%40` and you'll get `%40` in your handler for`event.pathParameters.id`.

serverless version `1.27.3`
