### ISSUE TITLE
Error: Could not locate deployment bucket

### ISSUE THREAD

**Issue by und3fined** [serverless/serverless#5041]
# This is a Bug Report

## Description

My serverless.yml

```
# Finsify merchant lambda

service: fbs-serverless

frameworkVersion: ">=1.1.0 <2.0.0"

custom: ${file(./serverless/config/${opt:stage}.yml)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.profile}
  region: ${self:custom.region}
  memorySize: 320
  logRetentionInDays: 30 # Set the default RetentionInDays for a CloudWatch LogGroup

  deploymentBucket:
    name: com.serverless.${self:provider.region}.deploys # Deployment bucket name. Default is generated by the framework
    # name: fbs.serverless.${self:custom.env_file}.${self:provider.region}.deploys # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption

  versionFunctions: false # Optional function versioning

  environment: ${file(./serverless/env/${self:custom.env_file}.yml)}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}"
        - "arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "${self:provider.environment.TOPIC_ARN}"

functions:
  chrome:
    handler: handler.chrome_fork
    timeout: 300
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":${self:custom.topic_trigger}-${self:provider.stage}"
          topicName: ${self:custom.topic_trigger}-${self:provider.stage}
          displayName: ${self:custom.topic_trigger}-${self:provider.stage} trigger data for lambda

resources:
  Resources:
    initialSNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: ${self:custom.topic_trigger}-${self:provider.stage}

plugins:
  - serverless-plugin-stack-outputs
```

## Additional Data

* ***Serverless Framework Version you're using***:  1.27.3
* ***Operating System***: darwin
* ***Stack Trace***:
```
ServerlessError: Could not locate deployment bucket. Error: Access Denied
    at BbPromise.resolve.then.then.catch.err (./node_modules/serverless/lib/plugins/aws/deploy/lib/existsDeploymentBucket.js:26:15)
From previous event:
    at AwsDeploy.existsDeploymentBucket (./node_modules/serverless/lib/plugins/aws/deploy/lib/existsDeploymentBucket.js:25:13)
    at AwsDeploy.BbPromise.bind.then.then (./node_modules/serverless/lib/plugins/aws/deploy/index.js:81:25)
From previous event:
    at Object.before:deploy:deploy [as hook] (./node_modules/serverless/lib/plugins/aws/deploy/index.js:78:10)
    at BbPromise.reduce (./node_modules/serverless/lib/classes/PluginManager.js:372:55)
From previous event:
    at PluginManager.invoke (./node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (./node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (./node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (./node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (./node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```

* ***Provider Error messages***: 
Fuk error:
If `deploymentBucket name` is `com.serverless.${self:provider.region}.deploys` -> error `Could not locate deployment bucket. Error: Access Denied`
If `deploymentBucket name` is `fbs.serverless.${self:custom.env_file}.${self:provider.region}.deploys` -> error `Could not locate deployment bucket. Error: The specified bucket does not exist`

Not config `deploymentBucket` deployment work well!
