### ISSUE TITLE
Variable not replaced correctly

### ISSUE THREAD

**Issue by eangeeag** [serverless/serverless#5044]
# This is a (Bug Report)

## Description

* What went wrong?

Running `serverless dynamodb install` with the following config

```
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: local
  region: us-east-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:custom.myStage}

custom:
  stageSuffix:
    local: dev
    dev: dev
    prod: prod
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  defaultPort: 4000
  myStage: ${opt:stage, self:provider.stage}
  myRegion: ${opt:region, self:provider.region}
  serverlessBucket: com-kaizen-serverless-${self:custom.stageSuffix.${self:custom.myStage}}
```
Shows error:

```
Serverless Error ---------------------------------------

  Trying to populate non string value into a string for variable ${self:custom.stageSuffix.self:custom.myStage}. Please make sure the value of the property is a string.

Stack Trace --------------------------------------------

ServerlessError: Trying to populate non string value into a string for variable ${self:custom.stageSuffix.self:custom.myStage}. Please
make sure the value of the property is a string.
    at Variables.populateVariable (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:391:13)
    at Variables.renderMatches (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:317:21)
    at BbPromise.all.then.results (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:337:29)
From previous event:
    at Variables.populateValue (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:337:8)    at _.map.variable (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:223:24)
    at arrayMap (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\node_modules\lodash\lodash.js:639:23)
    at Function.map (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\node_modules\lodash\lodash.js:9554:14)
    at Variables.populateVariables (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:222:14)
    at Variables.populateObjectImpl (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:251:30)
    at assignProperties.then (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:256:24)
From previous event:
    at Variables.populateObjectImpl (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:256:8)
    at prepopulateService.then (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:135:26)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at initialCall (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:135:10)
    at Variables.initialCall (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:66:12)
    at Variables.populateService (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\classes\Variables.js:133:17)
    at Serverless.run (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\lib\Serverless.js:89:27)
    at serverless.init.then (C:\Users\estebana\Software\node-v10.3.0-win-x64\node_modules\serverless\bin\serverless:42:50)
```
Looks to me that `${self:custom.myStage}` is not being interpolated properly.

* What did you expect should have happened?

I expect that the value of  `serverlessBucket` would have been computed to `com-kaizen-serverless-dev`

## Additional Data

* ***Serverless Framework Version you're using***:
`1.27.3`
