### ISSUE TITLE
Add support for Api Gateway private endpoints

### ISSUE THREAD

**Issue by jsphweid** [serverless/serverless#5052]
For feature proposals:

> _What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us._

AWS just announced last night that it can now support private endpoints: https://aws.amazon.com/blogs/compute/introducing-amazon-api-gateway-private-endpoints/

It would be cool if serverless could have basic support for this.

> _If there is additional config how would it look_

For implementing via VPC, it might look like:
```
    events:
      - http:
          method: post
          path: tokenGetter
          private: true
          vpc:
            securityGroupIds:
              - sg-18fjoij
            subnetIds: 
              - subnet-879etcet
              - subnet-asd8f798
              - subnet-whatever
```
