### ISSUE TITLE
Create command didn't use service name given as -n option.

### ISSUE THREAD

**Issue by HiromiShikata** [serverless/serverless#5070]
# This is a Bug Report

## Description
Create command works fine with template likes below:
```
service: example-service
~~~
```
But likes below, It didn't rename service name.
```
service: 
  name: example-service
~~~
```

It's dengerous becouse if I deployed multiple projects, firsrt project will be overriten by second one.

I flushed one service's all data in DynamoDB by "aws-nodejs-typescript" template. 

:cry: 

Similar or dependent issues:
* I coudn't find it.

## Additional Data
* ***Serverless Framework Version you're using***:
```
hiromi@hiromi-Matebook:~/git$ sls -v
1.27.3
```
* ***Operating System***:
```
hiromi@hiromi-Matebook:~/git$ uname -a
Linux hiromi-Matebook 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
hiromi@hiromi-Matebook:~/git$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
hiromi@hiromi-Matebook:~/git$ 
```
* ***Stack Trace***:
n/a
* ***Provider Error messages***:
n/a

p.s. Many of my services made with serverless FW. It's GREAT project. Thank you.

**Comment by horike37** [comment]
@HiromiShikata 
Thank you for opening this issue 😄 
Do you mean that -n option of create command does not work as expected?
Would be great if you can share some more details what your problem is.

**Comment by HiromiShikata** [comment]
@horike37 

Thank you for replying.
Yes, create command doesn't work as I expect.


When I create a project using this command: ```sls create -t aws-nodejs-typescript -n some-project```

I expecting server name in serverless.yml like this:
```
service:
  name: some-project

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

```

But actually:
```
service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
```

Service name wasn't changed.

We can enhance here, I think: https://github.com/serverless/serverless/blob/master/lib/plugins/create/create.js#L233
```
     serverlessYmlFileContent = serverlessYmlFileContent
        .replace(/service: .+/, `service: ${newServiceName}`);
```

Thank you.
