### ISSUE TITLE
SQS triggers for Lambda functions

### ISSUE THREAD

**Issue by GeoffMcLennan** [serverless/serverless#5085]
# This is a Feature Proposal

## Description

I would like to be able to add [SQS as a trigger for Lambda functions](https://docs.aws.amazon.com/lambda/latest/dg/invoking-lambda-function.html#supported-event-source-sqs) through Serverless.

This seems to be a recent addition to [Lambda's capabilities](https://docs.aws.amazon.com/lambda/latest/dg/history.html) but this fits a use case for a Serverless project I am working on extremely well, and we'd love to be able to use it without a workaround in our serverless.yml.

The change allows Lambda functions to be triggered directly by an SQS queue and passes the message (or batch of messages) as the payload to the function. This removes the requirement to poll the queue using some AWS compute service to check to see if there is any messages available for handling, which is what we currently have in our system.

As far as I can tell, this trigger can be created using the [AWS::Lambda::EventSourceMapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html) Cloudformation entity.

To support this in Serverless, an SQS option should be added to the functions' events object:
```
functions:
  myFunction:
    handler: handler.myFunction
    events:
      - sqs:
          name: myQueueName
          # all other SQS cloudformation parameters
          enabled: true
          batchSize: 10
```

If possible with my work schedule, I can try to make this change myself and submit a pull request.

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***: Windows
