### ISSUE TITLE
Custom apiName not applied

### ISSUE THREAD

**Issue by afgallo** [serverless/serverless#5090]
# This is a (Bug Report)

## Description

* What went wrong?
I've set the field `apiName` to a custom name but this was ignored by the framework
* What did you expect should have happened?
The framework should have created my api gateway with a custom name
* What was the config you used?
```
provider:
  name: aws
  profile: my-profile # The default profile to use with this service
  stage: development # Set the default stage used. Default is dev
  stackName: my-stack-name # Use a custom name for the CloudFormation stack
  apiName: my-custom-name
```
* What stacktrace or error message from your provider did you see?
No errors, just not the name I wanted

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.3
* ***Operating System***:
macOS Sierra
* ***Stack Trace***:
No stack trace
* ***Provider Error messages***:
No errors

I can definitely see in the source this is kind of doing the write thing:
https://github.com/serverless/serverless/blob/2eb915f8d96619bf73970ce1ddb71e50ef2cefca/lib/plugins/aws/lib/naming.js#L151

and relevant unit tests: https://github.com/serverless/serverless/blob/2eb915f8d96619bf73970ce1ddb71e50ef2cefca/lib/plugins/aws/lib/naming.test.js#L223

But not really sure what's wrong. Thanks!

**Comment by afgallo** [comment]
I actually noticed most of my custom configuration is being ignored by serverless. I guess there's something wrong with my setup but I can't figure it out. Here is my complete `serverless.yml`:

```
service: opportunity-svc

frameworkVersion: "=1.27.3"

provider:
  name: aws
  profile: my-profile # The default profile to use with this service
  stage: development # Set the default stage used. Default is dev
  stackName: my-stack-name # Use a custom name for the CloudFormation stack
  apiName: my-custom-name
  region: us-east-1 # Overwrite the default region used. Default is us-east-1
  deploymentBucket:
    name: deploy-bucket-xxx
    serverSideEncryption: AES256 # when using server-side encryption
  memorySize: 3008 # Overwrite the default memory size. Default is 1024
  runtime: nodejs8.10
  timeout: 3 # optional, in seconds, default is 6
  versionFunctions: true # Optional function versioning

functions:
  GetOpportunity:
    description: Gets an Opportunity
    handler: src/GetOpportunityRequestHandler.handler
    events:  # The Events that trigger this Function
      - http: get /api/opportunity/

package:
  exclude:
    - node_modules/**
    - test/**
    - coverage/**
    - .nyc_output/**
    - .eslintignore
    - .eslintrc.js
    - .gitignore
    - aws.policy.json
    - package-lock.json
    - package.json
  include:
    - ../../shared/**
    - src/**

```

I have also thought it could be related to permissions for the user `my-profile` but also tried giving it admin access and no luck. Any help would be greatly appreciated!
