### ISSUE TITLE
'invoke local --function' - Cannot find module ....\.webpack\service'

### ISSUE THREAD

**Issue by nickwcook** [serverless/serverless#5095]
# This is a Bug Report

## Running command 'serverless invoke local --function create --path ../mocks/create-event.json' returns error 'Cannot find module 'C:\Users\Me\Documents\Personal\serverless-react\notes-app-api\.webpack\service' when bundling with webpack. .webpack/service folder is empty after creation.

* What went wrong?:
  Above error returned.

* What did you expect should have happened?:
  .webpack/service folder should contain module. Command should return object as below:

```
{
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Credentials': true
      },
      body: '{"userId":"USER-SUB-1234","noteId":"578eb840-f70f-11e6-9d1a-1359b3b22944","content":"hello 
      world","attachment":"hello.jpg","createdAt":1487800950620}'
    }
```

* What was the config you used?
    **serverless.yml:**

```
service: notes-app-api

  # Use the serverless-webpack plugin to transpile ES6
  plugins:
    - serverless-webpack
    - serverless-offline

  # serverless-webpack configuration
  # Enable auto-packing of external modules
  custom:
    webpack:
      webpackConfig: ./webpack.config.js
      includeModules: true

  provider:
    name: aws
    runtime: nodejs8.10
    stage: prod
    region: eu-west-2

    # 'iamRoleStatements' defines the permission policy for the Lambda function.
    # In this case Lambda functions are granted with permissions to access DynamoDB.
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:eu-west-2:*:*"

  functions:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /notes
    # - method: POST request
    # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
    #     domain api call
    # - authorizer: authenticate using the AWS IAM role
    create:
      handler: '../create.main'
      events:
        - http:
            path: notes
            method: post
            cors: true
            authorizer: aws_iam
  
    get:
      handler: get.main
      events:
        - http:
          path: notes/id
          method: get
         cors: true
          authorizer: aws_iam
```

  **webpack.config.js:**

```
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    // We do not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: __dirname,
        exclude: /node_modules/
      },
      {
          test: /\.scss$/,
          use: [
              {
                  loader: 'style-loader'
              },
              {
                  loader: 'css-loader'
              },
              {
                  loader: 'sass-loader'
              }
          ]
      }
    ]
  }
}
```

* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: Windows 10
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
