### ISSUE TITLE
sls invoke local should make it possible to override environment variables

### ISSUE THREAD

**Issue by cihati** [serverless/serverless#5096]
# This is a (Feature Proposal)

## Description

`sls invoke local` should make it possible to override environment variables as command line arguments. For instance `sls invoke local -f myFunction --env myvar1=123 --env myvar2=foobar`

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.1
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by lbalceda** [comment]
what I do is use a section in your secrets for local overrides, and use that stage 

for example this is how mine is set up 

serverless.yml
```
...
custom:
  secrets: ${file(secrets.yml)}
provider:
  environment:
    region: ${self:provider.region}
...
```

secrets.yml
```
default: &default
  foo: "bar"
localstage:
  <<: *default
  foo: "foobar"     
```

so then 
`sls local invoke -s localstage`
