### ISSUE TITLE
Cannot deploy another stage with Shared API Gateway

### ISSUE THREAD

**Issue by byF** [serverless/serverless#5097]
# This is a Bug Report

## Description
I've got a shared API Gateway and a function behind it:
```yaml
provider:
  name: aws
  runtime: nodejs8.10
  apiGateway:
    restApiId: XXX
    restApiRootResourceId: XXX
functions:
  fn:
    handler: index.handler
    events:
      - http:
          path: /api/{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors: true
```
I deploy with `sls deploy -s dev`. That works fine. When I try to deploy another stage, e.g. `sls deploy -s test`, it fails with:

> An error occurred: ApiGatewayResourceApi - Another resource with the same parent already has this name: api (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: 376cb9fd-8088-11e8-b623-870ee5cd4bfb).

## Additional Data

* ***Serverless Framework Version you're using***:
1.27.3
* ***Operating System***:
OSX 10.13.5
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A

**Comment by byF** [comment]
I understand it's probably the behavior described in docs:

> The above example services both reference the same parent path /posts. However, Cloudformation will throw an error if we try to generate an existing path resource. To avoid that, we reference the resource ID of /posts:

I don't think this behavior makes sense for the different stages of the same service. I define the AGW outside serverless because I need elsewhere (Cloudfront origin).

**Comment by kyeljmd** [comment]
How did you resolve this?

**Comment by byF** [comment]
@kyeljmd I got rid of the shared gateway altogether. Sorry :)

**Comment by api-spinner** [comment]
This worked for me:

```
service: myservice

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: myprofile
  region: us-east-1
  environment:
    SERVICE_NAME: ${self:service}
  apiGateway:
    restApiId: xxxxxxxxxx
    restApiRootResourceId: xxxxxxxxxx
    description: description

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-domain-manager

functions:
  function:
    handler: handler.handler
    events:
      - http:
          path: path
          method: get
          cors: true

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: prod.domain.com
    staging: staging.domain.com
    dev: dev.domain.com

  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    certificateName: '*.domain.com'
    createRoute53Record: true
```
