### ISSUE TITLE
An error occurred: ApiGatewayDeploymentxxxxx - No integration defined for method - when v1.28 was used

### ISSUE THREAD

**Issue by densbozz** [serverless/serverless#5100]
# This is a (Bug Report)
This error started July 4 and coincidentally 1.28.0 was released.
our CodeBuild is failing since then.

In our CodeBuild spec...

------------------------ code build spec ---------------

version: 0.2

phases:
  install:
      commands:
        - ls -a
        - npm install -g serverless
  build:
    commands:
        - npm install --only=dev
  post_build:
    commands:
        - serverless deploy --stage $APP_DEPLOYMENT_ENVIRONMENT --package serverless

---------------------------------------------

## Description

For bug reports:
* What went wrong? - CodeBuild failed. This also impacted our update on existing API G where it somehow deleted method (OPTIONS) on some api endpoints.
* What did you expect should have happened? - our build was successful before, there are no other config or yml changes implemented except on business application code.
* What was the config you used? - no update on config
* What stacktrace or error message from your provider did you see?

## Additional Data - Error Stack in Code Build

Serverless: Checking Stack update progress...
....................................................................................................................................
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: ApiGatewayDeploymentxxxxxxx - No integration defined for method (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: xxxxxxxxxxxxxxxxxxx).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.3.1
     Serverless Version:     1.27.3
 

[Container] 2018/07/06 04:46:55 Command did not exit successfully serverless deploy --stage $APP_DEPLOYMENT_ENVIRONMENT --package serverless exit status 1
[Container] 2018/07/06 04:46:55 Phase complete: POST_BUILD Success: false
[Container] 2018/07/06 04:46:55 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: serverless deploy --stage $APP_DEPLOYMENT_ENVIRONMENT --package serverless. Reason: exit status 1

**Comment by drexler** [comment]
@densbozz the output references that you're still using v1.27.3. That rules out the newer version as a probable cause.

**Comment by mitchelljfs** [comment]
@densbozz I was experiencing the same issue, the exact same error output and resources missing the OPTIONS method. It appears to be related to a change in 1.28.0, because when deploying after the switch there are create method events being output in the event log despite no changes to my configuration. 

It seems like serverless was attempting to create OPTIONS methods that were already existent. 

**I was able to resolve it** by removing `cors: true` from all of my API Gateway resources in my serverless.yml, deploying, then adding `cors: true` back and deploying once more. I would presume that setting `cors: false` instead of removing/commenting them out would also suffice.

**Comment by densbozz** [comment]
@mitchelljfs - thanks for the response. this makes sense now. can you confirm the workaround you did is just one time, and your succeeding serverless deployments have been successful?

**Comment by mitchelljfs** [comment]
@densbozz no problem. I have not run into the problem more than once per stage, after using one of the two methods I described. So, yes.

**Comment by dschep** [comment]
We're also experiencing this issue. The workaround is less than ideal, so hopefully this'll be resolved in 1.28.1

**Comment by skylarmb** [comment]
simply removing `cors: true` from my http events didn't seem to do it. I deleted all the http events (except for one test event), deployed, restored all events, deployed again. NOTE: It appears this completely re-creates the Lambda function instead of just updating it as all settings (environment variables, VPCs, roles, etc) were lost.

**Comment by pmuens** [comment]
Hey @densbozz @drexler @mitchelljfs @dschep and @skylarmb!
Thanks for reporting and discussing solutions for this issue 👍

So I tried to reproduce this today with the following (super simple) service:

```yml
service: regression

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: test
          method: POST
          cors: true
```

I started with a deployment via `1.27.3`, after that I re-deployed (still using `1.27.3`). Then I updated to `1.28.0` and re-deployed again. Unfortunately I'm not able to trigger the described error. I'm pretty sure that there might be something more I need to configure on the API Gateway end to force the error to pop up.

Can anyone of you share a simple (redacted) `serverless.yml` so that we can reproduce this on our end? Thanks in advance!

**Comment by skylarmb** [comment]
@pmuens here is a redacted version of our `serverless.yml`. We have many more http and scheduled events than these but this is just a sample

```
plugins:
  - serverless-apigw-binary
  - serverless-api-stage
  - serverless-plugin-split-stacks
  - serverless-offline

service: my-service
package:
  exclude:
    - ".env"
    - "coverage/**"
    - "test/**"
    - "scripts/**"
    - "ddl/**"
    - "docs/**"
    - "./*.json"
provider:
  timeout: 300
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: us-east-1
  profile: foobar
  role: arn:aws:iam::123456789000:role/foobar-api-executor
  apiKeys:
    - ${opt:stage}-someApiKey
custom:
  apigwBinary:
    types:
      - 'application/octet-stream'
      - 'application/pdf'
  stageSettings:
    MethodSettings:
        DataTraceEnabled: true
        HttpMethod: "*"
        LoggingLevel: INFO
        ResourcePath: "/*"
        MetricsEnabled: true
  development:
    eventsEnabled: true
functions:
  root:
    handler: index.proxyRouter
    events:
      - schedule:
          name: 'X${opt:stage}SomeEventName'
          rate: cron(0 13 ? * MON *)
          enabled: ${self:custom.${opt:stage}.eventsEnabled}
          input:
            name: 'someEventName'
            stage: ${opt:stage}
      - http:
          cors: true
          method: get
          path: /api/baz
          authorizer:
            arn: ${file(./.serverless.env.yml):COGNITO_POOL_ARN}
      - http:
          cors: true
          method: post
          path: '/api/public/{id}/qux'

```
