### ISSUE TITLE
API gateway not routing to express routes

### ISSUE THREAD

**Issue by carasel** [serverless/serverless#5101]
I have written a simple express app, which I am deploying to a lambda using the serverless framework.

```
//app.js
'use strict'
const express = require('express')
const bodyParser = require('body-parser')
const awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')
const app = express()

app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))
app.use(awsServerlessExpressMiddleware.eventContext())

app.use('/topic', require('./routes/topic-route'))

app.get('/', (req, res) => res.send('Hello World!'))

module.exports = app
```
```
//topic-route.js
'use strict'
const express = require('express')
const topicRoute = express.Router()

topicRoute.get('/:id', (req, res) => {
    //code to return topic    
})

topicRoute.get('/', (req, res) => {
    res.send("Hello from the topic route!")    
})

module.exports = topicRoute
```

I have added the following to my serverless.yaml:
```
  ExpressLambda:
    warmup: true
    handler: APIs/APIs/express-experiment/lambda.handler
    runtime: nodejs8.10
    events:
      - http:
          path: /app/express-experiment
          method: ANY
          cors: true
          authorizer: Authorizer
      - http:
          path: /app/express-experiment/topic/{proxy+}
          method: ANY
          cors: true
          authorizer: Authorizer
    vpc:
      vpcName: '${env:VPC_NAME}'
      securityGroupIds:
        - ${env:VPC_SECURITY_GROUP}
      subnetIds:
        - ${env:VPC_SUBNET}
```

This all works as expected locally, but when deployed to aws I get an error: Cannot GET /app/express-experiment

I assume there's something wrong with my serverless.yaml, but I can't figure out what's missing. 

(As an aside it would be great if you guys could add a serverless framework yaml example as well as cloudformation)
