### ISSUE TITLE
AWS SQS event Trigger for Lambdas Created as Disabled

### ISSUE THREAD

**Issue by pedrodelgallego** [serverless/serverless#5102]
# This is a Bug Report 

## Description
Hi, 

I am testing the new SQS trigger, the creation of the queue and the lambda works well, but the status of the trigger is disabled. This is how my yml looks like: 

```
service:
  name: kopi-orders-api

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:*
    Resource: arn:aws:sqs:*:*:*
  - Effect: Allow
    Action:
      - sqs:ListQueues
    Resource: "*"

custom:
  ordersQueueName: ${self:provider.stage}-orders-queue

resources:
  Resources:
    ordersQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.ordersQueueName}

functions:
  create-order:
    handler: orders/create.create
    events:
      - sqs:
        arn: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:${self:custom.ordersQueueName}
        batchSize: 1
        enabled: true
```

And this is how it looks like in the aws console right after the creation.

 ![lambda after executing sls deploy](https://discourse-cdn-sjc2.com/standard10/uploads/serverless/optimized/2X/a/a0fcef0a7115a88a061607be21c97b095f218868_1_690x332.png)

If I manually toggle the status to enabled, everything works as expect

* What went wrong?
Lambda trigger event was created, but it status is disabled

* What did you expect should have happened?
Lambda trigger event was created, wiht status is enabled

* What was the config you used?
see above

* What stacktrace or error message from your provider did you see?
none

## Additional Data

* ***Serverless Framework Version you're using***:
1.28.0

* ***Operating System***:
macos x

* ***Stack Trace***:
none

* ***Provider Error messages***:
none

**Comment by pedrodelgallego** [comment]
Thanks @alexdebrie, 

it was the indentation issue. The template was not failling neither creating the event trigger, but It looks  that there was an EventSourceMapping from a previuous execution. I needed to manually remove via the aws cli ```aws lambda delete-event-source-mapping --uuid 3a9e218d-61be-4d1c-98a1-23f289a9bea1```

Kudos for implementing this feature.

**Comment by protzi** [comment]
@pedrodelgallego I have pretty same configuration but when deploy is done, SQS trigger is not created at the left corner of configuration dashboard ( like on your screen ). Any ideas what I did wrong ?
```
service:
  name: serverless-demo

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:TestQueue

functions:
  chargeInvoice:
    handler: functions/charge/invoice.handler
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:TestQueue
          batchSize: 1
          enabled: true

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "TestQueue"
```

**Comment by alexdebrie** [comment]
@pedrodelgallego Glad to hear!

@protzi I can try to help. Can you try the second step I recommended for @pedrodelgallego ? Use the following command (assuming you have jq installed):

```cat .serverless/cloudformation-template-update-stack.json | jq ".Resources.ChargeInvoiceEventSourceMappingSQSTestQueue"```

? 

I'm not 100% sure I got the resource name right here. Let me know if you get any output there.

**Comment by protzi** [comment]
@alexdebrie I've got null. :(

**Comment by alexdebrie** [comment]
Ahh yep, that makes sense 😄. Glad to see it's working now, @protzi !

**Comment by mateen-hussain** [comment]
@alexdebrie I am not sure why my below serverless.yml successfully creates an SQS lambda trigger:

```
functions:
   reminder-notification:
     handler: "notification_messages/send.send"
     events:
       - sqs: arn:aws:sqs:${self:provider.region}:${self:provider.accountId}:${self:provider.environment.REMINDER_NOTIFICATION_SQS}
```

but this one fails to create any

```
   reminder-notification:
     handler: "notification_messages/send.send"
     events:
       - sqs:
           batchSize: 1
           enabled: true
           arn:
             Fn::GetAtt:
               - ${self:provider.environment.REMINDER_NOTIFICATION_SQS}
               - Arn
```

My resources section looks like:

```
resources:
  Resources:
    ReminderNotificationSQS:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.REMINDER_NOTIFICATION_SQS}
```

there is no problem with indentation though

**Comment by alexdebrie** [comment]
Hey @mateen-hussain, did you figure this out? I tested your configurations with `sls package` and the CloudFormation appeared to be correct.

**Comment by mateen-hussain** [comment]
@alexdebrie I did delete the local `.serverless` folder and did a deploy. But before that I even did `sls remove` to remove existing stack and then the changes took effect. Not sure if it is related or not.

**Comment by alexdebrie** [comment]
Sounds good, @mateen-hussain. The first step -- deleting `.serverless` folder -- shouldn't have had an impact as that is recreated on each deploy. The second step -- doing `sls remove` -- *might* have done it, but I'm not sure why. 😄

**Comment by v4l3nt1n** [comment]
Alo folks, i had the same issue, suddenly the triggered lambda for the SQS queue appeared disabled.
Doing sls remove and re-deploying solved it.
also not sure why... if i realize it ill leave it here
regards

**Comment by mateen-hussain** [comment]
@alexdebrie I am seeing this issue again, and worse it has effected my prod deployment. I have tried `sls remove` and delete the local `.serverless` folder and then run deploy and still the trigger isnt getting created.

This issue needs to be fixed or atleast a workaround shown?

Is there a way to hold deployment of Lambda function untill the SQS has been deployed, by something like 

```
reminder-notification:
    DependsOn: ReminderNotificationSQS
    handler: "notification_messages/send.send"
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ReminderNotificationSQS
              - Arn
          batchSize: 1
          enabled: true
```
