### ISSUE TITLE
Cognito authorizer statusCode problems

### ISSUE THREAD

**Issue by 6iix** [serverless/serverless#5104]
# This is a (Bug Report / Feature Proposal)

## Description
I deployed the api I am using as a test with a custom authorizer. The responses on lambda completely changed. Now when I return {statusCode: 400, body: {foo: "bar"} the entire object returns and the statusCode does not update on the client I am using. 
For bug reports:
* What went wrong?
responses from lambda are the entire response, statusCodes are not updating. 
* What did you expect should have happened?
if the response has statusCode 400 the response statusCode should be 400
* What was the config you used?
```
service: polyapps-api
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: us-west-2
  timeout: 30
  apiKeys: 
    - apiKey-${opt:stage}
  environment:
    UserPoolId: xxxxx
    ClientId:xxxx
functions:
  login:
    handler: src/api/cognito/login.default
    events: 
      - http:
          path: login
          method: POST
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-west-2:xxxxxx:userpool/xxxxxxxxx
            claims:
              - email
  register:
    handler: src/api/cognito/register.default
    events: 
      - http:
          path: register
          method: POST
          private: true
  confirmRegister:
    handler: src/api/cognito/confirmRegister.default
    events:
      - http:
          path: confirmRegister
          method: POST
          private: true
  refreshToken:
    handler: src/api/cognito/refreshToken.default
    events:
      - http:
          path: tokens
          method: POST
          private: true
custom:
    webpackIncludeModules: true
package:
  exclude:
    - .gitignore
    - .git/**
    - .idea/**
    - .vscode/**
plugins:
  - serverless-domain-manager
  - serverless-webpack
  - serverless-offline
```
* What stacktrace or error message from your provider did you see?
 no stack trace
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.28.0
* ***Operating System***:
mac os mojave
