### ISSUE TITLE
AWS SQS triggers not completed

### ISSUE THREAD

**Issue by jamesdixon** [serverless/serverless#5105]
# This is a (Bug Report / Feature Proposal)
Probably a misconfiguration rather than a bug...

## Description
I'm adding the SQS event for triggering a few of my functions, but after deploying, no trigger has been created.

For bug reports:
* What went wrong?
SQS triggers were not created
* What did you expect should have happened?
SQS triggers should have been created
* What was the config you used?
```
service: email-service

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2

package:
  individually: true

functions:
  sendEmail:
    handler: lib/sendEmail/index.handler
    events:
      - sqs: 
          arn: ${self:deployVariables.SEND_EMAIL_SQS_ARN}
          enabled: true
  createEmail:
    handler: lib/createEmail/index.handler
    events:
      - sqs: 
          arn: ${self:deployVariables.CREATE_EMAIL_SQS_ARN}
          enabled: true
  createCampaign:
    handler: lib/createCampaign/index.handler
    events:
      - sqs: 
          arn: ${self:deployVariables.CREATE_CAMPAIGN_SQS_ARN}
          enabled: true
  sendGridEvent:
    handler: lib/sendGridEvent/index.handler
    events:
      - http:
          path: /sendGridEvent
          method: post

custom:
  deploy:
    environments: ${file(config/env.yml)}
    variables: ${file(config/variables.yml)}

plugins:
  - serverless-offline
  - serverless-plugin-deploy-environment
  - serverless-webpack
```
* What stacktrace or error message from your provider did you see?
None 👎 

Similar or dependent issues:
* #5102 

My configuration differs a bit from those in #5102 and I'm new to AWS, so again, could totally be a misconfiguration.

## Additional Data

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: OS X High Sierra
* ***Stack Trace***:
* ***Provider Error messages***:
