### ISSUE TITLE
EventType error after upgrading to 1.28

### ISSUE THREAD

**Issue by mpadmaraj** [serverless/serverless#5106]
# This is a Bug Report

## Description
After upgrading serverless to 1.28 the deployment is failing.
For bug reports:
* What went wrong?
`serverless deploy` is complaining about EventType.
* What did you expect should have happened?
Deployment should have worked
* What was the config you used?
```yml

service:
  name: send-notification
  description: 'This is implementation of contact form'

custom:
  eventgateway:
    url: ${env:EVENT_GATEWAY_APPLICATION}
    accessKey: ${env:EVENT_GATEWAY_ACCESS_KEY}

plugins:
  - "@serverless/serverless-event-gateway-plugin"

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
     URL: ${self:custom.eventgateway.url}

functions:
  sendMessage:
    handler: handler.send
    events:
      - eventgateway:
          type: sync
          event: http
          path: /send/message
          method: POST
  sendMail:
    handler: handler.sendMail
    events:
      - eventgateway:
          type: async
          event: app.sendMail

```
* What stacktrace or error message from your provider did you see?
```python

  Couldn't create subscriptions for send-notification-dev-sendMail. Error: Failed to subscribe the event undefined to the function send-notification-dev-sendMail due the error: Subscription doesn't validate. Validation error: Key: 'Subscription.Type' Error:Field validation for 'Type' failed on the 'required' tag
Key: 'Subscription.EventType' Error:Field validation for 'EventType' failed on the 'required' tag

 Couldn't create subscriptions for send-notification-dev-sendMail. Error: Failed to subscribe the event app.sendMail to the function send-notification-dev-sendMail due the error: Subscription doesn't validate. Validation error: Key: 'Subscription.Type' Error:Field validation for 'Type' failed on the 'required' tag
Key: 'Subscription.EventType' Error:Field validation for 'EventType' failed on the 'required' tag

```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data
Has the serverless.yml schema changed? I'm trying to use the http event of the eventgateway and also trying to emit an event on eventgateway.

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: Mac OS
* ***Stack Trace***:
```python
~/serverless/contact-form$ serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: send-notification
stage: dev
region: us-east-1
stack: send-notification-dev
api keys:
  None
endpoints:
  None
functions:
  sendMessage: send-notification-dev-sendMessage
  sendMail: send-notification-dev-sendMail

Event Gateway Plugin
 
  Error --------------------------------------------------
 
  Couldn't create subscriptions for send-notification-dev-sendMail. Error: Failed to subscribe the event app.sendMail to the function send-notification-dev-sendMail due the error: Subscription doesn't validate. Validation error: Key: 'Subscription.Type' Error:Field validation for 'Type' failed on the 'required' tag
Key: 'Subscription.EventType' Error:Field validation for 'EventType' failed on the 'required' tag
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.28.0

```
* ***Provider Error messages***:
