### ISSUE TITLE
Enabled configuration for scheduled event is ignored

### ISSUE THREAD

**Issue by AndreaAdvanon** [serverless/serverless#5111]
# This is a Bug Report

## Description

```
functions:
  scheduler:
    handler: handler.schedule
    events:
      - schedule:
          enabled: false
          rate: rate(3 minutes)
```
After deploying this lambda, on the AWS console I can see that the `CloudWatch Event` is enabled.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.28.0
* ***Operating System***: Fedora 28
* ***Stack Trace***: 
* ***Provider Error messages***:

**Comment by alexdebrie** [comment]
Hey @AndreaAdvanon, sorry to hear you're having this problem. Can you run the following command in your terminal (requires [jq](https://stedolan.github.io/jq/) to be installed):

```
$ cat .serverless/cloudformation-template-update-stack.json | jq ".Resources.SchedulerEventsRuleSchedule1"
```

You should see output with the following:

```
{
  "Type": "AWS::Events::Rule",
  "Properties": {
    "ScheduleExpression": "rate(3 minutes)",
    "State": "DISABLED",
    "Targets": [
      {
        "Arn": {
          "Fn::GetAtt": [
            "SchedulerLambdaFunction",
            "Arn"
          ]
        },
        "Id": "schedulerSchedule"
      }
    ]
  }
}
```

I'm particularly interested in whether you see `"State": "DISABLED",` in your config.

**Comment by AndreaAdvanon** [comment]
Weird, I do, I guess this is correct, right?

But I try the deploy twice, even with `--force`. Could this be a bug in `CloudFormation`?

**Comment by AndreaAdvanon** [comment]
```YAML
service: scheduled-test

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          enabled: false
          rate: rate(3 minutes)
```

This configuration has the same issue.

**Comment by alexdebrie** [comment]
That is weird, @AndreaAdvanon. I just did a test deploy, and it seems to be showing the same thing for me in the Lambda UI. However, when I go to the CloudWatch Rules UI by clicking on the Rule from the Lambda page, it shows it as disabled.

My guess is that it's an issue with the Lambda UI? My function isn't actually getting invoked, so it doesn't seem to be enabled.

**Comment by AndreaAdvanon** [comment]
Yes, I think it's a bug on their UI. My lambda is also not being run. I guess you can close this then, sorry :smile:

**Comment by alexdebrie** [comment]
No problem! 😄 I'll try to pass it along to some AWS contacts.

**Comment by alexdebrie** [comment]
@AndreaAdvanon I spoke with @alexcasalboni at AWS. The issue is that there is both an `AWS::Events::Rule` (that can be enabled / disabled) as well as the trigger in the Lambda UI (that can be enabled / disabled). The Lambda UI is showing the _trigger_ state, which is enabled. However, we can't actually touch that with CloudFormation. The `AWS::Events::Rule` is set to disabled, which is what we set with CloudFormation. If either the trigger or the Rule is disabled, it won't trigger your Lambda.

So, not quite a UI bug 😄.

Thanks to @alexcasalboni for the help 👏

**Comment by tara-influxdata** [comment]
Hi @alexdebrie, I am curious if CloudFormation still doesn't support setting a Lambda's trigger state? Thanks!

**Comment by alexdebrie** [comment]
Hi @tara-influxdata, is this for a scheduled event? If so, you can set the scheduled event to have `enabled: false`. This will configure both the Lambda function and the CloudWatch Event Rule, and the _Rule_ will be marked as disabled.

Does that handle your situation?

**Comment by tara-influxdata** [comment]
Thank you for the quick response. Yes it is for three scheduled events. I have tried setting them to `enabled: false` and both the Lambda function trigger state, and the CloudWatch Event Rule do not change / remain in an `enabled: true` state. The `serverless-state.json` file and the `cloudformation-template-update-stack.json` file both remain in an enabled state. I'm on OSX, serverless version output is:

```
Framework Core: 1.54.0
Plugin: 3.1.2
SDK: 2.1.2
Components Core: 1.1.1
Components CLI: 1.2.3
```

**Comment by alexdebrie** [comment]
@tara-influxdata Hmm! That's odd :) Can you paste your full `serverless.yml`, or at least the `functions` section so I can take a look and try to repro?

**Comment by tara-influxdata** [comment]
@alexdebrie Yes, thank you for your help!!

```
functions:
  docs-html-s3:
    handler: bin/docs-html-s3
    events:
      - schedule: rate(1 day)
        enabled: false
      - schedule: rate(1 day)
        enabled: false
      - schedule: rate(1 day)
        enabled: false
```
