### ISSUE TITLE
Basic sls deploy fails on dynamoDB create - validation error detected

### ISSUE THREAD

**Issue by CiscoKidxx** [serverless/serverless#5120]
### **THIS IS A BUG REPORT**

When trying to `sls deploy -v` I receive `CREATE_FAILED - AWS::DynamoDB::Table - UserDynamoDbTable` and then a rollback. Why does **'drucaas-dev'** fail to satisfy constraints?

**System Details:**
```
Node Version:  8.9.1
Serverless Version: 1.25.0
OS: Windows 7
```

**Error:**

```
 Serverless Error ---------------------------------------

An error occurred: UserDynamoDbTable - 1 validation error detected: Value 'drucaas-dev,' at 'tableName' failed to satisfy constrain
t: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+ (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: Validati
onException; Request ID: RCKJ7SH45A9GFPLESGUARKBTFBVV4KQNSO5AEMVJF66Q9ASUAAJG).
```

**serverless.yml:**
```
service: drucaas 

plugins:
  - serverless-offline
  - serverless-dynamodb-local

# Configuration variables
custom:
  secrets: ${file(secrets.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret},
    JWT_EXPIRATION_TIME: ${self:custom.secrets.jwtExp},
    USER_TABLE: ${self:service}-${opt:stage, self:provider.stage},
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
      Resource: "*"

# The `functions` block defines what code to deploy
functions:
  login:
    handler: functions/login.handler
    events:
      - http:
          path: users/login
          method: post
          cors: true
  authorize:
    handler: functions/authorize.handler
  register:
    handler: functions/register.handler
    events:
      - http:
          path: users/register
          method: post
          cors: true
  validate:
    handler: functions/validate.handler
    events:
      - http:
          path: users/validate
          method: post
          cors: true
  getScore:
    handler: functions/getScore.handler
    events:
      - http:
          path: getScore
          method: get
          cors: true
          authorizer: authorize # Get scores are protected
  getIssue:
    handler: functions/getIssue.handler
    events:
      - http:
          path: issues
          method: get
          cors: true

resources:
  Resources:
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "username"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "username"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.USER_TABLE}
        Tags:
          - Key: "project"
            Value: ${self:service}
```
