### ISSUE TITLE
Variables are not resolved in hooks functions of a plugin

### ISSUE THREAD

**Issue by SkxNMDI5** [serverless/serverless#5123]
# This is a Bug Report

## Description

* Variables are not resolved in hooks functions of a plugin
* Variables to be resolved
* Configuration :
serverless.yml
```yml
service: variables-plugin-test
frameworkVersion: ">=1.0.0 <2.0.0"
plugins:
   - test-variables

provider:
  name: aws
  region: eu-west-1

custom:
  conf:
    email: ${opt:email, "email@example.com"}
```

plugin test-variables.js :
```
"use strict";

class TestPlugin {
  constructor(serverless, options) {
    this.serverless = serverless;
    this.options = options;
    this.provider = this.serverless.getProvider("aws");
    this.region = this.provider.getRegion();
    this.hooks = {
      "after:deploy:deploy": this.test.bind(this)
    };
  }

  test() {
    console.log(this.serverless.service.custom.conf);
  }
}

module.exports = TestPlugin;
```

* Log :
Calling ```serverless deploy``` :
```
{ email: '${opt:email, "email@example.com"}' }
```

Similar or dependent issues:
* https://github.com/serverless/serverless/pull/3911

## Additional Data

* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***:  macOS 10.13.5
