### ISSUE TITLE
"individualy: true" seems be broken for Google Cloud (ENOENT: no such file or directory, lstat '....\.build\.serverless')

### ISSUE THREAD

**Issue by aadamovich** [serverless/serverless#5125]
# This is a Bug Report

## Description

* What went wrong?

Packaging of functions fail for Google Cloud and TypeScript functions if "individually: true" is used.

* What did you expect should have happened?

Correct packages are produced for all functions.

* What was the config you used?

```
service: my-proxy

provider:
  name: google
  runtime: nodejs
  project: my-proxy
  credentials: service_key.json
  memorySize: 512
  timeout: 540s
  labels:
    application: My Proxy

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  individually: true
  artifact: my-proxy.zip
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - yarn*
    - service_key.json
  include:
    - "*.js"

functions:
  proxy:
    handler: proxy
    events:
      - http: path
    package:
      artifact: proxy.zip 
  proxy2:
    handler: proxy2
    package:
      artifact: proxy2.zip 
      include:
        - "data/*.json"
    events:
      - http: path

```

* What stacktrace or error message from your provider did you see?

```
Serverless: Packaging service...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, lstat 'E:\Work\serverless-experiment\.build\.serverless'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, lstat 'E:\Work\serverless-experiment\.build\.serverless'
    at PluginManager.invoke (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:390:22)
    at PluginManager.run (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:421:17)
    at variables.populateService.then.then (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:163:33)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:102:23)
From previous event:
    at Serverless.run (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:150:8)
    at serverless.init.then (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\bin\serverless:42:50)
    at <anonymous>
```

## Additional Data

* ***Serverless Framework Version you're using***:

```
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           9.11.1
     Serverless Version:     1.28.0

```
Plugin versions:

```
  "dependencies": {
    "serverless-google-cloudfunctions": "^1.2.0",
    "serverless-plugin-typescript": "^1.1.5"
  },

```

* ***Operating System***:

    Windows 10

**Comment by aadamovich** [comment]
Full project reproducing the error is here: https://github.com/watch-devtube/serverless-experiment

**Comment by aadamovich** [comment]
If I remove the `artifact` parameter then I get the following error message:

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, open 'E:\Work\serverless-experiment\.build\package.json'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: ENOENT: no such file or directory, open 'E:\Work\serverless-experiment\.build\package.json'
    at Package.getFileContent (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\zipService.js:116:15)
    at Package.getFileContentAndStat (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\zipService.js:105:12)
    at Array.map (<anonymous>)
    at WriteStream.output.on (C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\zipService.js:83:29)
    at WriteStream.emit (events.js:180:13)
    at WriteStream.emit (domain.js:422:20)
    at C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:214:14
    at C:\Users\xaad\AppData\Roaming\npm\node_modules\serverless\node_modules\graceful-fs\graceful-fs.js:241:16
    at FSReqWrap.oncomplete (fs.js:153:20)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           9.11.1
     Serverless Version:     1.28.0
 

```

The config is the following:

```
service: my-proxy

provider:
  name: google
  runtime: nodejs
  project: my-proxy
  credentials: service_key.json
  memorySize: 512
  timeout: 540s
  labels:
    application: My Proxy

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  individually: true
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - yarn*
    - service_key.json
  include:
    - "*.js"

functions:
  proxy:
    handler: proxy
    events:
      - http: path
  proxy2:
    handler: proxy2
    package:
      include:
        - "data/*.json"
    events:
      - http: path

```
