### ISSUE TITLE
Serverless reference variable from file cannot used twice

### ISSUE THREAD

**Issue by kkesley** [serverless/serverless#5137]
Hi I'm implementing a custom CORS for all of my functions and I used an external file to define the CORS object.

```
service: user

provider:
  name: aws
  runtime: go1.x
  region: us-east-1

functions:
  create:
    runtime: go1.x
    handler: create/bin/main
    package:
      include:
        - ./create/bin/**
    events:
      - http:
          path: user
          method: post
          cors: ${file(../../serverless-cors.yml):custom.cors}
  list:
    runtime: go1.x
    handler: list/bin/main
    package:
      include:
        - ./list/bin/**
    events:
      - http:
          path: user
          method: get
          cors: ${file(../../serverless-cors.yml):custom.cors}
  show:
    runtime: go1.x
    handler: show/bin/main
    package:
      include:
        - ./show/bin/**
    events:
      - http:
          path: user/{user-id}
          method: get
          cors: ${file(../../serverless-cors.yml):custom.cors}
  update:
    runtime: go1.x
    handler: update/bin/main
    package:
      include:
        - ./update/bin/**
    events:
      - http:
          path: user/{user-id}
          method: post
          cors: ${file(../../serverless-cors.yml):custom.cors}
  delete:
    runtime: go1.x
    handler: delete/bin/main
    package:
      include:
        - ./delete/bin/**
    events:
      - http:
          path: user/{user-id}
          method: delete
          cors: ${file(../../serverless-cors.yml):custom.cors}
```

The first reference went ok but the subsequent ones will have when I use `sls print`
`'$["functions"]["create"]["events"][0]["http"]["cors"]'`

And it resulted in failure in deploying
Is this a known issue?
