### ISSUE TITLE
Serverless deploy with --package and --aws-profile

### ISSUE THREAD

**Issue by GeekOnGadgets** [serverless/serverless#5150]
# This is a (Bug Report / Feature Proposal)

## Description

Created CI/CD pipeline to deploy lambda function. In build step, package using `serverless package` and push `.serverless` directory  to s3 artifacts bucket. In deploy step use the build package from s3 to deploy to different env using `serverless deploy --aws-profile ${ENV} --package path-to-folder 

Note: I am passing the `deploymentBucket` as variable during `deploy` step. I also have serverless.yml in as referred in this https://github.com/serverless/serverless/issues/4715 issue.

For bug reports:
* What went wrong?
```
Serverless Error ---------------------------------------

  Resource ServerlessDeploymentBucket does not exist for stack bucket
```
* What did you expect should have happened?
Expected to use the profile and deploy using already created build
* What was the config you used?
```
service:
  name: ${env:SERVICE_NAME}-lambda

# Add the serverless-webpack plugin
plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-offline-scheduler
provider:
    name: aws
    runtime: nodejs6.10
    stage: ${env:ENV}
    region: ap-southeast-1
    deploymentBucket: ${env:BUCKET_NAME}
```

* What stacktrace or error message from your provider did you see?
None from AWS provider.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
Serverless Version: 1.28.0
* ***Operating System***:
OS:   darwin
* ***Stack Trace***:
* ***Provider Error messages***:

Note: I was able to put a workaround removing `--package` flag from `serverless deploy`, which worked but it did build it again. Which makes my build satge obsolete.

Thank You :)
