### ISSUE TITLE
Set custom region on Google Cloud

### ISSUE THREAD

**Issue by maranovot** [serverless/serverless#5158]
# This is a bug report

## Description

* After changing region in serverless.yml the region stays us-central1
* I expected the function to be deployed in the specified region.
* My config: 
```
service: my-service

provider:
  name: google
  runtime: nodejs
  project: my-project
  region: europe-west1 <------ CHANGING REGION HERE
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
```

## Additional Data

* ***Serverless Framework Version***: 1.28.0
* ***Operating System***: macOS 10.13.5 High Sierra
