### ISSUE TITLE
Unable to update serverless 0.5.x stack with serverless 1.x

### ISSUE THREAD

**Issue by brainstormtrooper** [serverless/serverless#5164]
# This is a (Bug Report)

## Description

* What went wrong?
Unable to update serverless 0.5.x stack with serverless 1.x
* What did you expect should have happened?
Stack updates like before
* What was the config you used?
```
service: <service name>
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stackName: ${self:service}-${self:provider.stage}-r
  stage: ${opt:stage, file(serverless.env.yml):stage, env:ENV}
  region: ${opt:region, file(serverless.env.yml):region, env:DEPLOYMENT_REGION}
  profile: ${opt:stage, file(serverless.env.yml):profile, env:AWS_PROFILE}
  environment:
    ENV: ${opt:stage, file(serverless.env.yml):stage, env:ENV}
    REGION: ${opt:region, file(serverless.env.yml):region, env:DEPLOYMENT_REGION} 


plugins:
  - serverless-build-plugin
  - serverless-offline

custom:
  serverless-offline:
    babelOptions:
      presets:
        - env:
            targets:
              node: "6.10"
            useBuiltIns: true
    plugins:
      - serverless-offline
      - transform-runtime
      - transform-regenerator
      - transform-class-properties
      - transform-object-rest-spread
      - transform-object-assign
      - transform-async-to-generator

functions:
  quote:
    handler: QuoteService/functions/handler.handler
    timeout: 15
    memory: 128
    events:
      - http:
          path: quote
          method: POST
```
* What stacktrace or error message from your provider did you see?
Resource ServerlessDeploymentBucket does not exist for stack <stack name here>

## Additional Data

* ***Serverless Framework Version you're using***: 1.28
* ***Operating System***: Linux and Windows
* ***Stack Trace***: 
ServerlessError: Resource ServerlessDeploymentBucket does not exist for stack xxx-quote-service-roplrdev-r
    at BbPromise.fromCallback.catch.err (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:270:11)
From previous event:
    at persistentRequest (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:253:13)
    at doCall (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:205:9)
    at BbPromise (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:222:14)
From previous event:
    at persistentRequest (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:203:38)
    at Object.request.requestQueue.add [as promiseGenerator] (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:243:49)
    at Queue._dequeue (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/promise-queue/lib/index.js:153:30)
    at /home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/promise-queue/lib/index.js:109:18
From previous event:
    at Queue.add (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/promise-queue/lib/index.js:94:16)
    at AwsProvider.request (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:243:39)
    at AwsProvider.getServerlessDeploymentBucketName (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:384:17)
    at AwsDeploy.setBucketName (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/lib/setBucketName.js:11:26)
From previous event:
    at Object.aws:deploy:deploy:checkForChanges [as hook] (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:105:10)
    at BbPromise.reduce (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/home/xxx-dev/xxx/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/home/xxx-dev/Documents/xxx/xxx/test_rick/quote-service/node_modules/serverless/bin/serverless:43:50)
