### ISSUE TITLE
Unable to set up AWS credentials with SSM interpolations

### ISSUE THREAD

**Issue by ledfusion** [serverless/serverless#5165]
# This is a Bug Report

As requested on #4984, I am opening an independent issue.

## Description

I am hitting a "chicken and egg" situation with serverless.

I am running `serverless config credentials --provider aws --key ... --secret ... ` with `serverless.yml` already created and some SSM variable interpolations:

```yml
service: my-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  region: eu-west-1
  environment: 
    # Try to fetch MY_API_MONGODB_URL_xxxx from SSM.
    # Use "mongodb://localhost:27017" if the above doesn't exist
    MONGODB_URI: ${ssm:MY_API_MONGODB_URL_${self:provider.stage}~true, "mongodb://localhost:27017/my-app"}
```

Instead of assigning the fallback value to `provider.environment.MONGODB_URI`, serverless will attempt to fetch the SSM variable. Because credentials are not yet defined, fetching from SSM will fail and execution will interrupt.

```
serverless config credentials --provider aws --key 1234 --secret 2345
 
 Serverless Warning --------------------------------------
 
  ################################################################################
 
 
 Serverless Warning --------------------------------------
 
  # 2503: 4 of 5 promises have settled
 
 
 Serverless Warning --------------------------------------
 
  # 2503: 1 unsettled promises:
 
 
 Serverless Warning --------------------------------------
 
  # 2503:   ssm:MY_API_MONGODB_URL_dev~true waited on by: ${ssm:MY_API_MONGODB_URL_dev~true, "mongodb://localhost:27017/test"}
 
 
 Serverless Warning --------------------------------------
 
  ################################################################################
 
 
  Serverless Error ---------------------------------------
 
  AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.1
     Serverless Version:     1.29.0

```

So I can't use serverless to define the credentials that I need to run it.

## Workaround:

Running the same command without the `serverless.yml` file or without any SSM interpolation, execution will do fine. 

Bypassing the checks in `lib/classes/Variables.js` > `getValueFromSsm` (lines 694-697) will also do the trick. But otherwise, it will get stuck into the vicious circle described above. 

Thank you!

## Additional Data

* Serverless 1.29.0
* MacOS 10.11
* NodeJS 8.11.1
