### ISSUE TITLE
cannot update an existing lambda

### ISSUE THREAD

**Issue by brainstormtrooper** [serverless/serverless#5175]
# This is a Bug Report

## Description

* What went wrong?
I cannot update an existing labda
* What did you expect should have happened?
lambda function should update
* What was the config you used?
```
service: xxx-manifest-service

frameworkVersion: ">=1.1.0 <2.0.0"

cf: ${file(serverless.env.yml):cf.${self:provider.stage}.${self:provider.region}}


resources:
  Resources: ${file(serverless.cf.yml):Resources}
  Outputs: ${file(serverless.cf.yml):Outputs}

provider:
  name: aws
  stackName: ${self:service}-${self:provider.stage}-r
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-serverlessdeploymentbucket
  runtime: nodejs6.10

  stage: ${opt:stage, file(serverless.env.yml):stage, env:LR_ENV} # roplrdev
  region: ${opt:region, file(serverless.env.yml):region, env:DEPLOYMENT_REGION} # eu-west-1 
  profile: ${opt:stage, file(serverless.env.yml):profile, env:AWS_PROFILE} # roplrdev


  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: arn:aws:logs:${self:provider.region}:*:* # arn:aws:logs:eu-west-1:675819241958:log-group:/aws/lambda/process-manifest:log-stream
    - Effect: Allow
      Action:
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:SendMessage
        - sqs:GetQueueUrl
        - sqs:GetQueueAttributes
      Resource: arn:aws:sqs:${self:provider.region}:*:xxx-instrumentation-gateway-${self:provider.stage}-ingest
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::xxx-document-storage-${self:provider.stage}-documents/*
        - arn:aws:s3::*:xxx-manifest-service*
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${self:provider.stage}-manifests
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${self:provider.stage}-manifest-shipments
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${self:provider.stage}-manifests/*
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${self:provider.stage}-manifest-shipments/*
    - Effect: Allow
      Action:
        - kinesis:*
      Resource: arn:aws:kinesis:${self:provider.region}:*:stream/${self:service}-${self:provider.stage}-*-stream

  environment:
    ENV: ${self:provider.stage}
    REGION: ${self:provider.region}
    TRIM_HORIZON: "10"
    SERVERLESS_PROJECT: ${self:service}
    SERVERLESS_STAGE: ${self:provider.stage}
    SERVERLESS_REGION: ${self:provider.region}
    MANIFEST_STREAM: ${self:service}-${self:provider.stage}-manifest-stream
    MANIFEST_TABLE: ${self:service}-${self:provider.stage}-manifests
    MANIFEST_SHIPMENTS_TABLE: ${self:service}-${self:provider.stage}-manifest-shipments
    DOCUMENT_STORAGE_S3: xxx-document-storage-${self:provider.stage}-documents
    MANIFEST_PROCESSING_STORAGE_S3: ${self:service}-${self:provider.stage}-processing
    # MANIFEST_STREAM_ARN: ${self:cf.ManifestStreamArn} # ${cf:${self:service}-${self:provider.stage}.ManifestStreamArn}
    # SHIPMENT_STREAM_ARN: ${self:cf.ShipmentStreamArn} # ${cf:${self:service}-${self:provider.stage}.ShipmentStreamArn}
    # READY_MANIFEST_STREAM_ARN: ${self:cf.ReadyManifestStreamArn} # ${cf:${self:service}-${self:provider.stage}.ReadyManifestStreamArn}
    # GROUPED_MANIFEST_SHIPMENT_STREAM_ARN: ${self:cf.GroupedManifestShipmentsStreamArn} # ${cf:${self:service}-${self:provider.stage}.GroupedManifestShipmentsStreamArn}
    

plugins:
  - serverless-build-plugin
  - serverless-offline
  - "@xxx/serverless-xxx-registry"
  - serverless-plugin-create-deployment-bucket

custom:
  serverless-offline:
    babelOptions:
      presets:
        - env:
            targets:
              node: "6.10"
            useBuiltIns: true

functions:
  process-manifest:
    name: ${self:service}-process-manifest
    description: "Process manifest stream and create records for manifest shipments streams"
    handler: src/functions/process-manifest/handler.handler
    timeout: 300
    memory: 1024
    events:
      - stream:
          name: "manifests-stream"
          type: kinesis
          arn:
            Fn::GetAtt:
              - ManifestStream
              - Arn
          startingPosition: TRIM_HORIZON
          batchSize: 1
          enabled: true
  process-shipments:
    name: ${self:service}-process-shipments
    description: "Process set of shipments, get shipment details and update manifest status"
    handler: src/functions/process-shipments/handler.handler
    timeout: 300
    memory: 1024
    events:
      - stream:
          name: "shipments-stream"
          type: kinesis
          arn:
            Fn::GetAtt:
              - ShipmentStream
              - Arn
          startingPosition: TRIM_HORIZON
          batchSize: 1
          enabled: true
  group-shipments:
    name: ${self:service}-group-shipments
    description: "Group manifest' shipments based on integration id and limit"
    handler: src/functions/group-shipments/handler.handler
    timeout: 6
    memory: 128
    events:
      - stream:
          name: readyStream
          type: kinesis
          # arn: READY_MANIFEST_STREAM_ARN
          arn:
            Fn::GetAtt:
              - ReadyManifestStream
              - Arn
          startingPosition: TRIM_HORIZON
          batchSize: 1
          enabled: true
  create-manifest:
    name: ${self:service}-create-manifest
    handler: src/functions/create-manifest/handler.handler
    timeout: 60
    memory: 256
    events:
      - http:
          path: manifests
          # name: manifests
          method: POST
          type: AWS
  get-manifest:
    name: ${self:service}-get-manifest
    description: "Get Manifest Details"
    handler: src/functions/get-manifest/handler.handler
    timeout: 60
    memory: 256
    events:
      - http:
          path: manifests/{id}
          # name: manifests
          method: GET
          type: AWS    
  complete-manifest:
    name: ${self:service}-complete-manifest
    description: "Generate shipping list and send to callback url once manifest shipments is done."
    handler: src/functions/complete-manifest/handler.handler
    timeout: 300
    memory: 1024

  manifest-shipmentst:
    name: ${self:service}-manifest-shipments
    description: "Manifest set of shipments (send request to integrations, generate shipping list and update manifest status)"
    handler: src/functions/manifest-shipments/handler.handler
    timeout: 300
    memory: 1024
    events:
      - stream:
          name: "do-manifest-stream"
          type: kinesis
          # arn: GROUPED_MANIFEST_SHIPMENT_STREAM_ARN
          arn:
            Fn::GetAtt:
              - GroupedManifestShipmentsStream
              - Arn
          startingPosition: TRIM_HORIZON
          batchSize: 1
          enabled: true
```
* What stacktrace or error message from your provider did you see?
Error message : `An error occurred: GroupDashshipmentsLambdaFunction - xxx-manifest-service-group-shipments already exists.`

Stack Trace:
```
ServerlessError: An error occurred: GroupDashshipmentsLambdaFunction - xxx-manifest-service-group-shipments already exists.
    at provider.request.then (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:112:33)
From previous event:
    at AwsDeploy.monitorStack (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:26:12)
    at provider.request.then (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:30)
From previous event:
    at AwsDeploy.update (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:95:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:112:12)
From previous event:
    at AwsDeploy.updateStack (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:106:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:135:39)
From previous event:
    at Object.aws:deploy:deploy:updateStack [as hook] (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:131:10)
    at BbPromise.reduce (/builds/xxx/manifest-service/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/builds/xxx/manifest-service/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/builds/xxx/manifest-service/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at AwsDeploy.BbPromise.bind.then (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:101:48)
From previous event:
    at Object.deploy:deploy [as hook] (/builds/xxx/manifest-service/node_modules/serverless/lib/plugins/aws/deploy/index.js:97:10)
    at BbPromise.reduce (/builds/xxx/manifest-service/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/builds/xxx/manifest-service/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/builds/xxx/manifest-service/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/builds/xxx/manifest-service/node_modules/serverless/lib/Serverless.js:163:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/builds/xxx/manifest-service/node_modules/serverless/lib/Serverless.js:150:8)
    at serverless.init.then (/builds/xxx/manifest-service/node_modules/serverless/bin/serverless:42:50)
```
## Additional Data

* ***Serverless Framework Version you're using***: 1.28
* ***Operating System***: Windows/Linux
* The lambda DOES exist... I'm trying to update it ...
