### ISSUE TITLE
sls deploy overwrites functions for different environments

### ISSUE THREAD

**Issue by afgallo** [serverless/serverless#5176]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
I've run `sls deploy --stage development` and then run `sls deploy --stage staging` and got an API gateway with two stages and two lambdas
* What did you expect should have happened?
Expected sls to have created an API gateway with two stages and 4 lambdas, two for each environment (development and staging).
* What was the config you used?
```
service: opportunity-svc

frameworkVersion: "=1.29.2"

provider:
  name: aws
  profile: my-sls # The default profile (aws credentials) to use with this service
  stage: ${opt:stage, 'development'}
  stackName: my-serverless-stack
  apiName: my-api
  region: us-east-1
  deploymentBucket:
    name: my-sls-deploy-bucket
    serverSideEncryption: AES256
  memorySize: 3008
  runtime: nodejs8.10
  timeout: 5
  versionFunctions: true # Optional function versioning
  endpointType: regional # Optional endpoint configuration for API Gateway REST API. Default is Edge.

functions:
  SaveOpportunity:
    description: Saves an Opportunity
    handler: src/SaveOpportunityService.handler
    events:
      - http: post /api/opportunity
  GetOpportunity:
    description: Gets an Opportunity 
    handler: src/GetOpportunityService.handler
    events:
      - http: get /api/opportunity

plugins:
  - serverless-webpack
  - serverless-offline
```

* What stacktrace or error message from your provider did you see?
No errors, commands complete successfully.

For feature proposals:

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.29.2
* ***Operating System***: macOS High Sierra
* ***Stack Trace***: No stack trace
* ***Provider Error messages***: No errors
