### ISSUE TITLE
Accessing files from Golang code

### ISSUE THREAD

**Issue by rayhaanq** [serverless/serverless#5184]
I'm using the firebase admin sdk for firebase cloud messaging and it needs me to use a json filepath string containing my credentials. I've tried putting the file in he same folder as the file trying to access it. But the file doesn't exist. How do I access the file? I've also tried adding custom variables and setting it to the file location, so:
``` 
provider:
  name: aws
  runtime: go1.x
  profile: serverless
  custom: ${file(./firebase-creds.json)}
  environment:
    someEnv: "bla"
  region: eu-west-2
```

but how do i access that form my code? 

 Environment Information -----------------------------
     OS:                     win32
     Node Version:           9.10.1
     Serverless Version:     1.29.2
