### ISSUE TITLE
{"errorMessage":"invalid_request"} when running deploy

### ISSUE THREAD

**Issue by johnlim** [serverless/serverless#5188]
# This is a Bug Report

## Description
Following the getting started guide at https://github.com/serverless/platform/blob/master/docs/event-gateway/getting-started.md, running `serverless deploy` with v1.29.2 results in the error 
```{"errorMessage":"invalid_request"}```. 
If i rollback serverless cli to v1.28.0, the following error results instead 
``` Failed to fetch the event types list due the error: API key not set.```.

For convenience, I've reproduced the serverless.yml here:
```
service: my-service

app: <your-app-name>
tenant: <your-tenant-name>

provider:
  name: aws
  runtime: nodejs8.10

functions:
  main:
    handler: handler.main
    events:
      - eventgateway:
          type: sync
          eventType: http.request
          path: /
          method: GET

custom:
  eventTypes:
    http.request:
          
plugins:
  - "@serverless/serverless-event-gateway-plugin"
```
## Additional Data
v1.28.0
```
Event Gateway Plugin
 
  Error --------------------------------------------------
 
  Failed to fetch the event types list due the error: API key not set.
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.28.0
```
v1.29.2
```
 Error --------------------------------------------------
 
  {"errorMessage":"invalid_request"}
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.29.2
```
