### ISSUE TITLE
CloudWatch empty FilterPattern

### ISSUE THREAD

**Issue by AndreaAdvanon** [serverless/serverless#5196]
# This is a Bug Report

## Description
I'm trying to subscribe a lambda function to multiple cloudwatchLogs, filtering for the string `error: `:
```yaml
service: myservice

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  logRetentionInDays: 30
  environment:
    SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}

functions:
  slack-logs:
    handler: handler.logs
    events:
      - cloudwatchLog: '/aws/lambda/lambda1'
        filter: 'error: '
      - cloudwatchLog: '/aws/lambda/lambda2'
        filter: 'error: '
```
After deploy, both filters are empty:
```bash
cat .serverless/cloudformation-template-update-stack.json | jq ".Resources.SlackDashlogsLogsSubscriptionFilterCloudWatchLog1"
{
  "Type": "AWS::Logs::SubscriptionFilter",
  "DependsOn": "SlackDashlogsLambdaPermissionLogsSubscriptionFilterCloudWatchLog1",
  "Properties": {
    "LogGroupName": "/aws/lambda/lambda1",
    "FilterPattern": "",
    "DestinationArn": {
      "Fn::GetAtt": [
        "SlackDashlogsLambdaFunction",
        "Arn"
      ]
    }
  }
}

```

## Additional Data

* ***Serverless Framework Version you're using***: 1.29.2
* ***Operating System***: Fedora 28

**Comment by AndreaAdvanon** [comment]
Ah, my bad, the should be:
```yaml
    events:
      - cloudwatchLog: 
          logGroup: '/aws/lambda/lambda1'
          filter: 'error: '
```
