### ISSUE TITLE
SQS trigger not created?

### ISSUE THREAD

**Issue by madhuravius** [serverless/serverless#5198]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:

* What went wrong?

I am using AWS as my provider. I have used a number of event triggers and needed to use SQS as an event trigger for my lambda. 

When I specify an ARN or use an Fn::ImportValue, no event source mapping is created in the .serverless directory (thus, no event
trigger for that SQS lambda appears).

I followed this documentation: https://serverless.com/framework/docs/providers/aws/events/sqs/

* What did you expect should have happened?

An event source mapping should be created and when I view the lambda panel in AWS I should see it as a trigger on the GUI.
I can create it manually (but I would prefer to allow serverless to create it for me). 

* What was the config you used? See the below markdown snippet which corresponds to the function.

The only section that has been added/changed is below (out of a large yaml):

```
functions:
    nameOfSQSFunction:
        handler: directory/nameofservice.service
        timeout: 30
        events:
            - sqs:
                batchSize: 10 # max size is currently 10
                enabled: true
                arn:
                   Fn::ImportValue: ${opt:stage}-exportedIdFromAWS
```

I also tried specifying the ARN directly:

```
functions:
    nameOfSQSFunction:
        handler: directory/nameofservice.service
        timeout: 30
        events:
            - sqs:
                batchSize: 10 # max size is currently 10
                enabled: true
                arn: arn:aws:sqs:region:XXXXXX:myQueue

```

Initially I was concerned maybe it was a permissions issue somewhere and added `sqs:*` under permissions but it appears this 
is related to event source mapping (?) not really SQS itself, so I've since removed that.

* What stacktrace or error message from your provider did you see? 

There is no stack trace.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #5085
* #5105 - checked for the same mistake (version of sls)
* #5102 - disabled trigger by default (which is why i put enabled: true) -- But if you look at this comment they are examining the source mapping:
https://github.com/serverless/serverless/issues/5102#issuecomment-403222199 which is simply not present in my .serverless/update stack file

Disabled by default 

## Additional Data

* ***Serverless Framework Version you're using***: v1.28.0 and v1.29.2 (attempted this on both versions)
* ***Operating System***: Mac OS X High Sierra
* ***Stack Trace***: No stack trace
* ***Provider Error messages***: No errors

**Comment by lukegrecki** [comment]
I'm having the same issue. So far unable to fix the issue by giving more permissions to both the serverless user or the lambda IAM role. 

If it helps the function in question originally had an SNS trigger on it, but I changed it to have an existing SQS queue as it's event source.

**Comment by theslyone** [comment]
This feature was a recent functionality added on aws, the serverless package has been updated also so you might need to update yours to a more recent version( e.g 1.30.1)

Try
```
npm update serverless@latest -g
```

**Comment by madhuravius** [comment]
I had the most recent version installed globally, I believe my mistake was sillier than that. At the top of serverless.yml there is a version that can be specified and I was specifying a version that was too old. 

Due to other breaking changes we can't currently update, but I will try to do so and see if this bug is of my own doing. Thanks!

**Comment by BigChief45** [comment]
I am experiencing the same issue. No SQS queue is added to the Lambda function in the *Triggers* section after it is deployed.

From @madhuravius 's comment, I tried adding the latest version to `serverless.yml` as described in the [docs](https://serverless.com/framework/docs/providers/aws/events/sqs#pinning-a-version):

```yaml
frameworkVersion: "=1.30.1"
```

And tried deploying again. But the SQS trigger still won't be created.

**Comment by ejweiler** [comment]
I had a similar problem, I was sending things to SQS but nothing was being picked up from the Queue. Things used to work, and I had recently done a round of cleaning up permissions. I didn't think I needed to allow 'sqs:ListQueues', but putting this back has things working again.

Based on [this doc page](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-lambda-function-trigger.html) about lambdas, I thought I could get away with applying these permissions to my queue, but it only worked when ListQueues was granted.

- sqs:ChangeMessageVisibility
- sqs:DeleteMessage
- sqs:GetQueueAttributes
- sqs:ReceiveMessage

**Comment by agindre** [comment]
I had the issue.
When I checked my serverless version, it was 1.26.1.
I updated it to 1.30.1 and everything is working fine now. Just be careful you restart your current bash session to get the last version of serverless cli.

**Comment by poisa** [comment]
In my case this works:

```yml
functions:
  index:
    handler: handlers/index.handler
    reservedConcurrency: 1
    events:
      - sqs: ${self:custom.${opt:stage}.Sqs}
```

But the actual documented format doesn't:

```yml
functions:
  index:
    handler: handlers/index.handler
    reservedConcurrency: 1
    events:
      - sqs:
        arn: ${self:custom.${opt:stage}.Sqs}
        batchSize: 1
```

So far I've found no way of getting the `batchSize` to be recognized in my lambda function. No matter what I do it gets set as the default of 10.

**Comment by maorkavod** [comment]
I have a mac and also had this problem.
I solve it by : 

npm uninstall -g serverless
npm uninstall  serverless
npm install -g serverless@1.30.3

than deploy again, it shuold have an sqs trigger working.

**Comment by ejweiler** [comment]
@poisa Try indenting the lines with 'arn' and 'batchSize' 2 more spaces to the right. I believe your yaml format is invalid as above. Here is one of my configs that I have working with 1.32.0, but it was working with 1.30 as well.

```yaml  
  eventHandler:  
    handler: backend/lambdas/eventHandler.handler  
    timeout: 30
    memorySize: 1024
    reservedConcurrency: 2
    onError:
      Ref: DeadLetterQueueTopic
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EventQueue
              - Arn
          batchSize: 1
```

**Comment by ejweiler** [comment]
> I have a mac and also had this problem.
> I solve it by :
> 
> npm uninstall -g serverless
> npm uninstall serverless
> npm install -g serverless@1.30.3
> 
> than deploy again, it shuold have an sqs trigger working.

To sort of echo this, sometimes my stack just deploys with the Lambda triggers disabled and I need to redeploy. (The stack, not the package) It's only ever occurred when developing and constantly removing and deploying quickly. In the AWS console of your queue you can check if the trigger is enabled.

**Comment by Bartinger** [comment]
Experiencing the same issue with `1.32.0` with the following configuration:

```yaml
frameworkVersion: "=1.32.0"

...

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        Fn::GetAtt: [BroadcastMessageQueue, Arn]

...

functions:
  handle-broadcast-message-queue-events:
    handler: dist/functions/functions.handleBroadcastMessageQueueEvents
    timeout: 300
    memorySize: 256
    events:
      - sqs:
        arn:
          Fn::GetAtt: [BroadcastMessageQueue, Arn]
        batchSize: 10

...

resources:
  Resources:
    BroadcastMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqsQueueBroadcastMessages}
        #MessageRetentionPeriod: 3600 # 1h
        VisibilityTimeout: 300 # Must be at least as long as function timeout
```

I tried adding it via the GUI which first returned a permission error (had to add `sqs:GetQueueAttributes`) then an error that the  `VisibilityTimeout` can't be lower than the function timeout. Now I'm able to add the SQS trigger manually but not automatically via the serverless template

**Comment by ejweiler** [comment]
@Bartinger for your function, the indentation below `- sqs` doesn't look to be enough.

**Comment by Bartinger** [comment]
@ejweiler Thank you very much. Few wasted hours but I'm glad it works now.

**Comment by bobmoff** [comment]
I also experienced indent issues, which is hard to spot as they just get silently ignored. But anyway, would be great if yaml format was validated prior to deploys, and preferably an error stating what is wrong. :)

**Comment by dattatrayhkulkarni-espressif** [comment]
I am facing a similar issue, the  SQS trigger for Lambda is not created.

Here is my Serverless.yml file

```
service: cloudformation-demo

plugins:
  - serverless-pseudo-parameters

custom:
  CONNECT_DEVICE_SQS_ROLE_NAME: SqSConnectRole
  CONNECT_DEVICE_SQS_QUEUE_NAME: connectDeviceSQSDemo1


provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1


package:
 individually: true
 exclude:
   - ./**

functions:
   lambdaenvinfo:
    handler: bin/handlers/lambdaenvinfo
    timeout: 900
    package:
     exclude:
        - "**/**"
     include:
       - ./bin/handlers/lambdaenvinfo
     events:
       - sqs: arn:aws:sqs:us-east-1:account_id:connectDeviceSQSDemo
```

**Comment by jim-jigx** [comment]
I had the same issue with the SQS trigger not being created and no error messages or CFT errors. The fix for me was to increase the indentation for the arn and batchSize parameters.

serverless --version:
Framework Core: 1.60.1
Plugin: 3.2.6
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0

Thanks to the comments above for pointing me in the right direction!

**Comment by tvb** [comment]
Just ran into this. Fixed it by increasing the indentation for the `arn` and `batchSize` parameters with 2 more spaces.

**Comment by apsoto** [comment]
indent fixed for me too....very frustrating...it's valid yaml so my editor doesn't complain, but obviously not valid

I was following along the example here:
https://www.serverless.com/framework/docs/providers/aws/events/sqs/

The indentation is there, but very easy to miss.

**Comment by bahrmichael** [comment]
I had a typo where I used `event` instead of `events`.

Wrong:
```yaml
functions:
  myFunction:
    handler: myFunction.handle
    event:
      - sqs:
          arn: "arn"
```

Correct:
```yaml
functions:
  myFunction:
    handler: myFunction.handle
    events:
      - sqs:
          arn: "arn"
```

Tracked this down by running `sls print` where I saw `events: []`. That made me check the definition again.
