### ISSUE TITLE
Cannot see any cloud formation stack on AWS and my Lambdas after I run sls deploy

### ISSUE THREAD

**Issue by kushalmahajan** [serverless/serverless#5200]
Here's my YML file
```
service: aws-nodejs # NOTE: update this with your service name

app: serverless-dev
tenant: kushalvm

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: devProfile
  region: us-east-1
custom:
  defaultStage: dev
  profiles:
    dev: devProfile
    prod: prodProfile
functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /users
         method: GET

  todos:
    handler: src/todos.handler
    events:
      - http:
          path: /todos
          method: GET

  todo:
    handler: src/todo.handler
    events:
      - http:
          path: /todo/{id}
          method: GET
          request:
            parameters:
              id: true
  
plugins:
  - serverless-offline
```

Now, I have [default] and [devProfile] in my aws credentials. Made sure that I created these users on aws and they have correct secret id and private secret key.

I have a bunch of simple lambda functions. I don't know why my cloud formation is not getting created. Although I see my s3 bucket created and listing a single zip file after multiple deployments. Hope, that's fine too.

Neither do I see lambda functions in console management of AWS. Although everything is present in serverless dashboard and I can verify my AWS account id to be correct

**Comment by cdeocampo** [comment]
Hi @kushalmahajan.

It might be related to what I'm experiencing. Have you done `export AWS_PROFILE=<your-aws-profile>` prior to running `sls deploy`?

**Comment by dschep** [comment]
Could you share the output of `sls info` @kushalmahajan?

**Comment by pmuens** [comment]
Closing this issue since it's quite stale and not enough information was provided. Please re-open once more info is available.

**Comment by thauvette** [comment]
I am having a similar issue. I can see the s3 bucket being created but I don't see a new cloudFormation stack or any new lambda functions. 

Running `serverless deploy` gives me the expected output as does `sls info`. 

`serverless.yml`

```
service: aws-correct-service-name

provider:
  name: aws
  runtime: nodejs8.10
  profile: calProfile
  stage: dev
  region: us-east-1

functions:
  getAvailability:
    handler: handler.getAvailabilty
    events:
      - http:
          path: availability/
          method: post
  getUserEvents:
    handler: handler.getUserEvents
    events:
      - http:
          path: userEvents/
          method: post
  createEvents:
    handler: handler.createEvents
    events:
      - http:
          path: set/
          method: post
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
plugins:
  - serverless-offline
  - serverless-webpack
```

`sls info` output: 
```
Service Information
service: aws-correct-service-name
stage: dev
region: us-east-1
stack: aws-correct-service-name-dev
api keys:
  None
endpoints:
  POST - https://someId.execute-api.us-east-1.amazonaws.com/dev/availability
  POST - https://someId.execute-api.us-east-1.amazonaws.com/dev/userEvents
  POST - https://someId.execute-api.us-east-1.amazonaws.com/dev/set
functions:
  getAvailability: aws-correct-service-name-dev-getAvailability
  getUserEvents: aws-correct-service-name-dev-getUserEvents
  createEvents: aws-correct-service-name-dev-createEvents
```
