### ISSUE TITLE
refer to auto-generated resources in CloudFormation

### ISSUE THREAD

**Issue by glikson** [serverless/serverless#5202]
# This is a Feature Proposal
## Description
In some cases, when I add Resources to serverless.yml, I need to refer to resources which are auto-generated by the serverless framework (e.g., in a "DependsOn" clause). See specific example at the bottom.

Currently, the documentation [1] suggests generating the Cloud Formation template, and looking it up there. 

It could be great if I could use some sort of built-in function(s) to refer to an auto-generated resource. Or at least the normalized name (which I then could use to construct the full resource name, following the naming convention specified in [1]).

[1] https://serverless.com/framework/docs/providers/aws/guide/resources/

## Additional Data
* ***Serverless Framework Version you're using***: 1.27.3
* ***Operating System***: Ubuntu 16
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by Mortinke** [comment]
We have the same requirement. We try to execute the generated lambda function with a AWS::CloudFormation::CustomResource:
```
functions:
  <function_name>:
    name: <function_name>

resources:
  Resources:
    Init<function_name>:
      Type: AWS::CloudFormation::CustomResource
      Properties:
        ServiceToken:
           Fn::Join: [ "", [ "arn:aws:lambda:", Ref: AWS::Region, ":", Ref: AWS::AccountId, ":function:<function_name>" ] ]
        Type: <function_name> Initialization
```

...but we get always the error:
```
  | AWS::CloudFormation::CustomResource | Init<function_name> | Function  not found:  arn:aws:lambda:<region>:<account_id>:function:<function_name>  (Service: AWSLambda; Status Code: 404; Error Code:  ResourceNotFoundException; Request ID:  ........)
```


```
