### ISSUE TITLE
schedule event name is generated incorrectly

### ISSUE THREAD

**Issue by tuanquynet** [serverless/serverless#5206]
# This is a (Bug Report / Feature Proposal)
This is a bug

## Description

For bug reports:
* What went wrong?
name of schedule event is duplicate. It generate 'notification-queue-scheduler-notification-queue-scheduler-staging'. It happen with version 1.30.0. But it was working with version 1.29.1.

* What did you expect should have happened?
Event name which is generated should be 'notification-queue-scheduler-staging'
* What was the config you used?
```
service: aws-gp

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

functions:
    handler: notification-queue/index.handler
    timeout: 60
    package:
      include:
        - notification-queue/**
    events:
      - schedule:
          name: notification-queue-scheduler-${opt:stage, self:provider.stage}
          description: a scheduler for notification queue
          rate: cron(0 17 * * ? *)
          enabled: false
```
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.30.0
* ***Operating System***: macos
* ***Stack Trace***:
* ***Provider Error messages***:  
An error occurred: NotificationDashqueueEventsRuleSchedule1 - 1 validation error detected: Value 'notification-queue-scheduler-notification-queue-scheduler-staging' at 'name' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: 33cd08e5-9d80-11e8-a087-6d978620ef35).
