### ISSUE TITLE
[object Object] as environment variable when using CF functions

### ISSUE THREAD

**Issue by AndreaAdvanon** [serverless/serverless#5209]
# This is a Bug Report

## Description
I wanted to define a custom `arn`:
```yaml
custom:
  myCustomTopic:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - my-custom-topic
```
 and use it as an environment variable:
```yaml
  environment:
    MY_CUSTOM_TOPIC: ${self:custom.myCustomTopic}
```

But if I try at runtime:
```js
console.dir(process.env.MY_CUSTOM_TOPIC)
```
I get:
```
'[object Object]'
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.29.2
* ***Operating System***: Fedora 28

**Comment by choxnox** [comment]
I can confirm I have the same issue referencing DynamoDB table from within environment variable:


```
provider:
  environment:
    DYNAMODB_TABLES_EVENTS:
      Ref: EventsTable

resources:
  Resources:
    EventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stackName}-events
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
```

When I use that environment variable inside Lambda function I get back the string with value: `[object Object]`.

**Comment by nerdmax** [comment]
+1

**Comment by shawnmclean** [comment]
When running this locally, it would be good to have the env var resolved to undefined instead of [Object object]

**Comment by alexdorand** [comment]
Any plans to fix this bug anytime soon?

**Comment by mapsi** [comment]
Same here with 

sls 1.32.0
aws-sdk 2.338.0

**Comment by snajahi** [comment]
+1

**Comment by herebebogans** [comment]
[serverless-export-env](https://www.npmjs.com/package/serverless-export-env) plugin along with serverless-offline will allow it to be referenced locally.

**Comment by marekopatril** [comment]
+1

**Comment by yashutanna** [comment]
+1

**Comment by devashish90** [comment]
+1

**Comment by keaeriksson** [comment]
+1

**Comment by gromozeka1974** [comment]
+1

**Comment by bryan-lifelink** [comment]
+1

**Comment by diosney** [comment]
Bump!

**Comment by diegoaguilar** [comment]
@AndreaAdvanon did you find a workaround or fix for this?

**Comment by OskarKaminski** [comment]
The issue seems to occur only while invoking functions locally.
I use https://github.com/arabold/serverless-export-env.

1. Install serverless-export-env
2. `sls export-env` - this will create `.env` file in your service directory
3. Invoke your lambda with -e flag `sls invoke local -f yourFunction -e YOUR_ENV_VARIABLE=value-from-dotenv-file`

This works perfectly for local testing ;)

**Comment by arlensiuerendira** [comment]
For me what worked is to simply do an invoke without the local flag. Depends on what needs to be done.

**Comment by pmuens** [comment]
Hey everyone,
I tried to reproduce this issue but I was unsuccessful in doing so. On my machine the correct CloudFormation is produced. Can someone give some pointer as to how this functionality behaves incorrectly? What are the steps to reproduce this issue?

**Comment by herebebogans** [comment]
@pmenus. I *think* the original poster was referring to runtime as `sls invoke local` not lambda runtime

In which case this is not a bug. 

As mentioned the servleress-export-env plugin allows these cloudformation refs to be resolved via serverless offline or invoke local.

**Comment by herebebogans** [comment]
@pmuens I dont think this is a serverless bug.  
I think this would be better explained in the documentation for `sls invoke` around how Environment variables using cloudformation references are not resolved and a pointer to the `serverless-export-env` plugin.

**Comment by pmuens** [comment]
Thanks for the update @herebebogans :+1:

Since I was not able to reproduce this bug and no one updated the thread with a reliable way to reproduce it I'll close this issue for now. Feel free to re-open if you're still facing this problem.

**Comment by janoist1** [comment]
I'm still getting this exact same issue. Running sls locally with offline plugin.

**Comment by medikoo** [comment]
> I'm still getting this exact same issue. Running sls locally with offline plugin.

I believe it should be reported then to https://github.com/dherault/serverless-offline

**Comment by LiranCohen** [comment]
I'm really surprised that a few things like this have not been solved yet as this issue is over a year old... and closed by the maintainer?!?

This should really be a part of the framework itself and not rely on 3rd party plugins and hacks to accomplish.   I plan on possibly writing a compressive plugin that will help with these types of development issues at some point in the future.

For the time being my solution is as follows:
I use the **serverless-export-env** plugin to export the env variables into a .env file
_(this plugin also has some caveats to watch out for as it doesn't support Fn::GetAtt if you're using those in your environment section)_

I then modified the **serverless-dotenv-plugin**, which loads .env into your lambdas, to only do so when the invoke local function is called.

This effectively writes the env variables that are usually available to lambda to a .env file, and then exports them to the local lambda execution environment to be available for consumption.

Hopes this helps anyone else that is having these issues.  This is purely a hack and I'd really like to find a better way around it (maybe instead of relying on 2 separate plugins).

**Comment by kailip** [comment]
As a workaround for this issue, I'm using **serverless-cloudside-plugin**. With this plugin invoking function locally changes from `sls invoke local` to `sls invoke cloudside`, and there are real values instead of [object Object].

**Comment by medikoo** [comment]
> I'm really surprised that a few things like this have not been solved yet as this issue is over a year old... and closed by the maintainer?!?

@LiranCohen have you read the thread? It's a bug of a plugin and not the framework. Have you tried to report it to https://github.com/dherault/serverless-offline ?

**Comment by LiranCohen** [comment]
> > I'm really surprised that a few things like this have not been solved yet as this issue is over a year old... and closed by the maintainer?!?
> 
> @LiranCohen have you read the thread? It's a bug of a plugin and not the framework. Have you tried to report it to https://github.com/dherault/serverless-offline ?

I'm not using the serverless-offline plugin as it doesn't support runtimes like Go.  This is not an issue with the serverless-offline plugin, same thing happens without that plugin.  I've managed some workarounds however as mentioned above.  I will take a look at serverless-cloudside-plugin as I've heard this mentioned by someone on Slack.

**Comment by adamdabbracci** [comment]
I also had this issue after upgrading my Serverless framework version to latest (1.58.0). Referencing  RDS credentials stored in Secrets Manager started printing as "[Object object]". Looks like it was introduced in `1.38.0`, and downgrading to `1.37.1` seems to fix it. 

Based on the commits in that release, I'm guessing this commit changed how it works:

https://github.com/serverless/serverless/pull/5842/files

Which added this check only for Secrets Manager params:
```
        if (param.startsWith('/aws/reference/secretsmanager')) {
          try {
            const json = JSON.parse(plainText);
            return BbPromise.resolve(json);
          } catch (err) {
            // return as plain text if value is not JSON
          }
        }
        return BbPromise.resolve(plainText);
```
I'll keep poking once I get past this feature to see if I can open a PR.

**Temporary Solution**: downgrade to `1.37.1`.

**Comment by medikoo** [comment]
@adamdabbracci can you prepare a test case, that reproduces the issue (without any plugins involved) ?

**Comment by adamdabbracci** [comment]
I attempted to reproduce this but it looks like this is an intended change. 1.38.0 introduced a convoluted way of referencing JSON blobs (which is how SM stores RDS credentials): https://github.com/serverless/serverless/issues/5869#issuecomment-467919391. You now have to reference each property from the stored credentials individually instead of pulling the entire object in:

**Old way (up to 1.37)**
```
provider:
  name: aws
  runtime: nodejs10.x
  profile: shine
  stage: dev
  environment:
    DB_CREDS: ${ssm:/aws/reference/secretsmanager/YOUR_SECRET_NAME~true}
```

**New way (after 1.38.0)**
```
custom:
  dbCreds: ${ssm:/aws/reference/secretsmanager/YOUR_SECRET_NAME~true}
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  environment:
    DB_USERNAME: ${self:custom.dbCreds.username}
```
I wasn't able to deploy the sample until I updated the structure. So I guess I just need to update my project to this format and I should be good to go. 

Thanks for checking :)

**Comment by medikoo** [comment]
Thanks @adamdabbracci for investigating this out!

A nice improvement to the framework could be to stringify objects into JSON string and not to `'[object Object]' in such cases (PR's welcome!)

**Comment by navrkald** [comment]
This issue still persist on serverless 1.59.3

**Comment by medikoo** [comment]
@navrkald technically it's not a bug.

Environment variables by nature can only be strings, hence when you try to assing an object to it, it results with `'[object Object]'` string

**Comment by navrkald** [comment]
Hello @medikoo we have problem that environment variable doesn't contain correct ARN when we are doing `sls invoke local ...`

our code look like this:
```yaml
functions:
  LambdaName:
    handler: path/to.handler
    environment:
      someSnsTopicArn:
        Ref: SomeSnsTopic

resources:
  Resources:
    SomeSnsTopic:
      Type: AWS::SNS::Topic
```
When we run:
* `sls deploy -s some_stage` it works
* `sls invoke -s some_stage -f LambdaName` it works
* `sls invoke local -s some_stage -f LambdaName` **doesn't work**

I expect the environment variable `someSnsTopicArn` contains correct ARN, not '[object Object]' when running `sls invoke local`.
