### ISSUE TITLE
Cannot deploy to some stages because function name duplicated in arn

### ISSUE THREAD

**Issue by kdavidmoore** [serverless/serverless#5213]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? **Tried to deploy my AWS lambda service to the `test` stage using `serverless deploy -s test --force`; the operation failed with an error. When I inspected the error, I found that it was trying to duplicate my function name in the arn, e.g., `function:executeScript2_executeScript2_test`. I do not get this error when deploying to dev (the default stage) using `serverless deploy`. Edit: I also get the error when trying `serverless deploy -s dev` but not `serverless deploy`.**
* What did you expect should have happened? **My service should have deployed to `test`.**
* What was the config you used?
```
service: <REDACTED>-scripts

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

package:
 individually: true
 exclude:
  - src/**
 include:
  - bin/**

custom:
  dburl:
    dev: <REDACTED>
    test: <REDACTED>
    prod: <REDACTED>

functions:
  jobsCron:
    name: jobsCron_${self:provider.stage, 'dev'}
    handler: bin/jobscron
    description: Checks for jobs.
    role: <REDACTED>
    events:
      - schedule: rate(1 minute)
    timeout: 30
    environment:
      STAGE: ${self:provider.stage}
      DB_URL: ${self:custom.dburl.${self:provider.stage}}
      MY_AWS_ACCESS_KEY_ID: <REDACTED>
      MY_AWS_SECRET_ACCESS_KEY: <REDACTED>

  executeScript2:
    name: executeScript2_${self:provider.stage, 'dev'}
    runtime: nodejs8.10
    handler: src/executeScript2/executeScript2.handler
    package:
      include:
        - 'src/executeScript2/executeScript2.js'
        - 'src/executeScript2/node_modules/**'
    role: <REDACTED>
    description: <REDACTED>
    timeout: 30
    environment:
      STAGE: ${self:provider.stage}
```

* What stacktrace or error message from your provider did you see?
> An error occurred: ExecuteScript2LambdaFunction - Function not found: arn:aws:lambda:us-XXX-X:XXX-redacted-XXXXX:function:executeScript2_executeScript2_test (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 888b8deb-a013-11e8-839f-4136a6d3ce16).
Note that the function name is repeated twice before the stage name (executeScript2_executeScript2_test).

Similar or dependent issues:
I've seen Resource Not Found issues, but none where the function name was duplicated like this.

## Additional Data
> Your Environment Information -----------------------------
>      OS:                     darwin
>      Node Version:           8.11.1
>      Serverless Version:     1.30.0
