### ISSUE TITLE
SQS Dead letter target does not exist...

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#5215]
# This is a Bug Report

## Description
We have "backout" queues for each SQS queue and I want/need to be able to create both the "function" queue and "backout" queue at the same time. Creating SQS queues I can't create the dead-letter-queue at the same time as it fails for missing teh dead-letter-queue (=our "backout" queue).

For bug reports:
* What went wrong?
Queues are not created and an error is thrown

* What did you expect should have happened?
That both queues were created

* What was the config you used?
```
resources:
  Resources:
    lambdaTestSLSQueueCreate:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'lambda-test-sls-queue-create'
        MessageRetentionPeriod: 7
        RedrivePolicy:
          deadLetterTargetArn: 'arn:aws:sqs:eu-west-1:290634095615:backout-test-sls-queue-create'
          maxReceiveCount: 3
    backoutTestSLSQueueCreate:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'backout-test-sls-queue-create'
        MessageRetentionPeriod: 14
        RedrivePolicy:
          deadLetterTargetArn: 'arn:aws:sqs:eu-west-1:290634095615:dead-letter-queue'
          maxReceiveCount: 1
```
* What stacktrace or error message from your provider did you see?
```An error occurred: lambdaTestSLSQueueCreate - Value {"deadLetterTargetArn":"arn:aws:sqs:eu-west-1:290634095615:backout-test-sls-queue-create","maxReceiveCount":"3"} for parameter RedrivePolicy is invalid. Reason: Dead letter target does not exist. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue;```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: v1.30
* ***Operating System***: WSL (Ubuntu)
* ***Stack Trace***: See above
* ***Provider Error messages***:

**Comment by yahehe** [comment]
I've got this working for myself like so:
```
resources:
  Resources:
    FailedQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.resourceNameBase}-failed
    IncomingQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.resourceNameBase}-incoming
        RedrivePolicy:
          deadLetterTargetArn: 
            Fn::GetAtt:
              - FailedQueue
              - Arn
          maxReceiveCount: 3
```
