### ISSUE TITLE
Cannot pass * as default value

### ISSUE THREAD

**Issue by errordeveloper** [serverless/serverless#5225]
# This is a Bug Report

## Description

* What went wrong?

When I set `${env:ALLOW_ORIGIN, "*"}` it gets passed as is.

* What did you expect should have happened?

As `${env:ALLOW_ORIGIN, "foo"}` works, I'd expect `${env:ALLOW_ORIGIN, "*"}` to work also.

* What was the config you used?

```
service: community-slack

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    SLACK_TEAM: ${env:SLACK_TEAM}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    ALLOW_ORIGIN: ${env:ALLOW_ORIGIN, "*"}

functions:
  doInvite:
    handler: handler.doInvite
    events:
      - http:
          path: invite
          method: post
          cors:
            origin: ${env:ALLOW_ORIGIN, "*"}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
plugins:
  - serverless-stack-output

custom:
  output:
    file: .serverless/output-${opt:stage, self:provider.stage}.json

package:
  exclude:
    - 'node_modules/**'
    - 'docs/**'
    - '*.md'
    - 'LICENSE'
    - '*.sh'
    - '*.env'
    - 'package-lock.json'
    - 'package.json'
    - '.vscode/**'
```

* What stacktrace or error message from your provider did you see?

No error.

## Additional Data

* ***Serverless Framework Version you're using***: 1.30.1
* ***Operating System***: macOS
