### ISSUE TITLE
Using default variable in events schedule rate generates invalid ScheduleExpression parameter

### ISSUE THREAD

**Issue by adamwpc** [serverless/serverless#5230]
# This is a (Bug Report)

## Description
When I try to use a variable ( `${opt:schedule-rate, 'rate(7 days)}` ) to set the schedule rate for an event and leave it unset (ie. I do not pass in `--schedule-rate bla`) - the cloudformation ScheduleExpression generated has no space between the amount and the unit and so the deploy fails. 
eg: 
when `opt:schedule-rate` is provided: `"ScheduleExpression": "rate(7 days)",`
vs when not provided: `"ScheduleExpression": "rate(7days)",`

For bug reports:
* What went wrong?
The deploy failed. 

* What did you expect should have happened?
The deploy should have succeeded. 

* What was the config you used?
```
service: my-bla-service

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: ${opt:stage, 'qa1'}
  region: ${opt:region, 'eu-west-1'}
  endpointType: REGIONAL
  deploymentBucket:
    name: my-bla-deployments
  environment:
    LOG_LEVEL: Debug
  vpc:
    securityGroupIds:
      - ${opt:security-group-id}
    subnetIds:
      - ${opt:subnet-zone-a}
      - ${opt:subnet-zone-b}
      - ${opt:subnet-zone-c}

package:
  artifact: bin/deploy-package.zip

functions:
  download:
    handler: My.Namespace::My.Namespace.Class::Function
    memorySize: 1024
    timeout: 300
    events:
      - schedule:
          rate: ${opt:schedule-rate, 'rate(7 days)'}
          enabled: true
```

* What stacktrace or error message from your provider did you see?
`An error occurred: DownloadEventsRuleSchedule1 - Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: xyz).`

## Additional Data

* ***Serverless Framework Version you're using***: `1.26.0`
* ***Operating System***: Windows 10 Pro
* ***Stack Trace***:  n/a
* ***Provider Error messages***: `An error occurred: DownloadEventsRuleSchedule1 - Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: xyz).`
