### ISSUE TITLE
DynamoDB table name duplication

### ISSUE THREAD

**Issue by zambonni** [serverless/serverless#5231]
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong? 
I configure a dynamoDb table with name (inside resource block)
`TableName:${self:provider.environment.DYNAMODB_MESSAGES_TABLE}`
and inside provider > environment:
`DYNAMODB_MESSAGES_TABLE: my-table-name-${opt:stage, self:provider.stage}`
As a result, i found a table with name (for example for dev stage):
`my-table-name-my-table-name-dev`

* What did you expect should have happened?
A new dynamoDB table named `my-table-name-dev`
* What was the config you used?
```
messagesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_MESSAGES_TABLE}
        AttributeDefinitions:
          - AttributeName: messageId
            AttributeType: N
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
```
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.30.1
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
