### ISSUE TITLE
  Trying to populate non string value into a string for variable ${file(.env.dev.yml)}. Please make sure the value of the property is a string.

### ISSUE THREAD

**Issue by jascination** [serverless/serverless#5235]
# This is a Bug Report

## Description

* What went wrong?

Upgraded from v1.29 to 1.31, and now when I try to start Serverless locally with:

`cross-env IS_OFFLINE=TRUE AMP_MOCK_DB=TRUE serverless offline start --stage dev --host 0.0.0.0`

 I get:

`Trying to populate non string value into a string for variable ${file(.env.dev.yml)}. Please make sure the value of the property is a string.
`

* What did you expect should have happened?

This only happened after updating, so I assume there are breaking changes somewhere that I haven't found in the release notes...

* What was the config you used?

Here's my serverless.yml. The issue seems to be with the line

`environment: '${file(.env.${opt:stage, self:provider.stage}.yml)}'`

Note that before this error, I also get this warning:
```

 Serverless Warning --------------------------------------

  A valid option to satisfy the declaration 'opt:service' could not be found.


```

This has always been there and has never caused issues, but may be an issue with our update? Full config below:

```

service: ${opt:service, 'myappname'}
frameworkVersion: '>=1.0.0 <2.0.0'
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: 'ap-southeast-2'
  role: '${self:custom.roles.default}'

  deploymentBucket:
    name: '${self:provider.stage}-${self:service}-deployment-bucket'
    serverSideEncryption: 'AES256'

  # VPC configuration per environment (dev, qa, prod)
  # This is required for deployment, but not during Lambda execution.
  vpc: '${file(./serverless-vpc-config.yml):${opt:stage, self:provider.stage}}'

  environment: '${file(.env.${opt:stage, self:provider.stage}.yml)}'

functions:
  ${file(resource/serverlessHelper.js):aggregatedFunctions}

plugins:
  - serverless-swagger-documentation
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-domain-manager

resources:
  Resources:
    '${file(resource/serverlessHelper.js):cloudformationResources}'

custom:
#   serverless-dynamodb-local plugin configuration
  s3:
    host: localhost
    port: 4000
    inMemory: true
    directory: '${env:BUCKET_DIR, self:custom.default_bucket_directory}'
    cors: false
      # Uncomment only if you already have a S3 server running locally
      # noStart: true

  default_bucket_directory: ./temp

  # serverless-webpack configuration
  webpack:
    includeModules: 
      forceExclude: 
        - aws-sdk
    packager: 'yarn'


  # Authentication/Authorizer variables
  fnAuthorizer: ${file(./resource/serverlessHelper.js):getAuthorizerForEnvironment}

```

## Additional Data

* ***Serverless Framework Version you're using***:
Serverless 1.30.1
