### ISSUE TITLE
Environment variable for a function doesn't work

### ISSUE THREAD

**Issue by saumilsdk** [serverless/serverless#5244]
I have tried setting environment variables in provider which works fine. But if I do the same for a function it is "undefined". Please fix asap

**Comment by saumilsdk** [comment]
Sorry @williamdenton for "please fix asap" thing. I think i put that after getting frustrated trying to resolve the issue.  Here is the details which might help to solve the issue.
Serverless version: 1.26.0
```
  listAssets:
    handler: src/lambda/asset.list
    environment:
       ASSET_KEY: abcdefgh
    events:
      - http:
          path: assets
          method: get
          cors: true
          authorizer:  ${self:custom.uaaAuthorizer}
```
Manners : Thank you :)
