### ISSUE TITLE
Config populate error after 1.30.1 upgrade

### ISSUE THREAD

**Issue by Tsopic** [serverless/serverless#5245]
## Description
* What went wrong?
Deploy unsuccessful after upgrading to serverless 1.30.1
* What did you expect should have happened?
Succesful deploy
* What was the config you used?
```
custom:
  serverless-kms-secrets:
    secretsFile: ./serverless/kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml
  kmsSecrets: ${file(./serverless/kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
  config: ${file(./serverless/config.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
```

* What stacktrace or error message from your provider did you see?

```
$ npx sls deploy --stage=dev
 
  Serverless Error ---------------------------------------
 
  Trying to populate non string value into a string for variable ${file(./serverless/kms-secrets.dev.eu-west-1.yml)}. Please make sure the value of the property is a string.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.30.1

```
