### ISSUE TITLE
Deploying to different stages, revoke the API keys from the previous stage.

### ISSUE THREAD

**Issue by khaledosman** [serverless/serverless#5246]
# This is a (Bug Report / Feature Proposal)
Bug
## Description
I'm using stackName and apiName to deploy different stages to the same api & stack.. The problem is when I use ```sls deploy --stage live``` to deploy to a different environment. The api keys stop working for dev and only works in live, until I deploy to dev again where dev works but live doesn't.

in AWS usage plans I see my API attached for one stage only

here's my serverless.yml file 
```
service:
  name: my-app

plugins:
  - serverless-webpack
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .git/**
    - .serverless/**
    - yarn.lock
    - package-lock.json
  excludeDevDependencies: true  

custom:
  bucket: 'my-s3-bucket'
  dynamodb_table: My-App-Users #${self:service.name}-${opt:stage, self:provider.stage}
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  role: arn:aws:iam::dasdsdsadsaadas:role/lambda_basic_execution
  stackName: my-app-stack 
  apiName: my-app-api
  apiKeys:
    # - ${self:provider.stage}-myAPIKey
    - my-app-apikey
  environment:
    NODE_ENV: PRODUCTION
    S3_BUCKET: ${self:custom.bucket}
    DYNAMODB_TABLE: ${self:custom.dynamodb_table}
    AWS_STAGE: ${self:provider.stage}

  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb_table}"

functions:
  MyService:
    handler: handler.handle
    events:
      - http:
          method: get
          path: user-location
          private: true
          cors: true
```
serverless v1.30.1

**Comment by khaledosman** [comment]
I guess I was thinking about environments and stages the wrong way, the way AWS API Gateway does staging is not really helpful as it still uses the same lambda function with a single log group in cloudwatch and just adds the stage as a url path in API Gateway, so perhaps its ok that serverless uses a single usage plan and a single apikey for it.

I removed the apiname, stack name from my serverless.yml and added back 
```
apiKeys:
     - ${self:provider.stage}-myAPIKey
```
to let serverless create 2 different cloudformation stacks and 2 api gateways with separate lambda functions and log groups. which made more sense to separate the lambda function's code in different environments to prevent dev deployments to affect live and vice versa. I was just hoping to somehow group them together instead of creating multiple services.

**Comment by avvi00** [comment]
I think this is an issue, at least there is no clear way to work around the problem of API keys being overwritten by the last stage to deploy. 

If you have multiple API Gateway stages, you can indicate a separate lambda (and hence cloudwatch log) by naming the lambda in the serverless.yml. 

Here is a simplified serverless.yml which shows the issue.

```
service: myservice
provider:
  name: aws
  stage: ${opt:stage}
  apiKeys:
    - name: ${self:service}-${opt:stage}
      value: ${opt:api_key}
  stackName: ${self:service}
functions:
  Function1:
    name: ${self:service}-${opt:stage}-Function1
    events:
      - http: 
          path: function1
          method: post
          private: true
```

`sls deploy --stage dev --api_key 1234` creates
- a rest api endpoint at https:///something.amazonaws.com/dev/function1
- backing lambda: myservice-dev-Function1 
- new API key called `myservice-dev` with a value of 1234

So at this point the endpoint requires x-api-key header of 1234.

`sls deploy --stage test --api_key 5678`  creates
- a rest api endpoint at https:///something.amazonaws.com/test/function1 and a new API key called 
- backing lambda: myservice-test-Function1 `myservice-test` 
- new API key with a value of 5678. 

Now my expectation is that test/function1 requires API key 5678 and dev/function1 requires 1234, but dev/function1 now requires 5678.

I could maybe work around this by providing both API keys in parameters, and using the usage plans to correlate, but assuming I have dev, test and prod stages this would me my deployment for dev requires keys for test and prod to be passed in as well, which is dangerous in terms of security and ci/cd and messy.

Would love to hear if there is a correct serverless approach to solving this.


Serverless version: **1.47.0**
Node version : **10.3.0**
Platform: **Windows 10**
