### ISSUE TITLE
Intermittent: Unable to teardown resources when lambda is deployed in custom VPC

### ISSUE THREAD

**Issue by drexler** [serverless/serverless#5252]
# This is a (Bug Report)

## Description
`sls remove` sometime hangs on attempting to teardown resources  after a lambda has been deployed in a custom VPC.

For bug reports:
* What went wrong?
The output  hangs waiting for cloudformation to tear the resources down. I have to manually log into the AWS console and explicitly detach and delete the associated ENI with the lambda in order to get the stack deletion to complete. 

* What did you expect should have happened?
Resources should be torn down without user intervention in the AWS Console. 

* What was the config you used?
```
service: notification-scheduler

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 300   # AWS Lambda runtime limit (5 mins)
  versionFunctions: false
  memorySize: 128
  vpc:
    securityGroupIds:
      - ${file(${opt:variables}):lambdaExecutionSecurityGroup}
    subnetIds:
      - ${file(${opt:variables}):privateSubnetId1}
      - ${file(${opt:variables}):privateSubnetId2}
    
  environment:  #environment variables
    awsRegion: ${file(${opt:variables}):awsRegion}
    dbUsername: ${file(${opt:variables}):dbUsername}
    dbPassword: ${file(${opt:variables}):dbPassword}
    dbEndpoints: ${file(${opt:variables}):dbEndpoints}

  iamRoleStatements: 
    - Effect: Allow
      Action: # Gives permission to create the necessary ENIs for execution in VPC
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
        - ec2:DetachNetworkInterface
      Resource: "arn:aws:ec2:us-east-1:*:*"

functions:
  updateAlertTriggers:
    handler: src/handler.updateAlertTriggers
    events:
      - schedule: 
          rate: cron(0/2 * * * ? *)    # Run every 2 minutes (Test)  cron(0 9 * * ? *)   # Run at 0900 UTC each day
          enabled: true

        
plugins:
  - serverless-webpack
  - serverless-cloudformation-resource-counter

custom:
  webpack: 
    webpackConfig: ./webpack/${file(${opt:variables}):webpackConfigurationFile}
    includeModules: true   
    packager: 'npm
```

## Additional Data

* ***Serverless Framework Version you're using***: 
1.30.1
* ***Operating System***:
MacOs High Sierra v10.13.6
