### ISSUE TITLE
S3Bucket - Encountered unsupported property ServerSideEncryptionByDefault.

### ISSUE THREAD

**Issue by AnthonyWC** [serverless/serverless#5259]
# This is a Bug Report

## Description

I had the following:

```
  - Resources:
      S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: "${self:service}-${opt:stage, self:provider.stage}"
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: SSE-KMS
          ServerSideEncryptionByDefault:
            KMSMasterKeyID: "aws:kms:${self:provider.stage}:#{AWS::AccountId}:key/${self:custom.kms.${self:provider.stage}}"
```

* What stacktrace or error message from your provider did you see?

```
Serverless: Uploading CloudFormation file to S3...
--
  | Serverless: Uploading artifacts...
  | Serverless: Uploading service .zip file to S3 (17.04 MB)...
  | Serverless: Validating template...
  | Serverless: Updating Stack...
  | Serverless: Checking Stack update progress...
  | CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - dataeng-buildkite-test-dev
  | CloudFormation - CREATE_FAILED - AWS::S3::Bucket - S3Bucket
  | CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - dataeng-buildkite-test-dev
  | CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - dataeng-buildkite-test-dev
  | CloudFormation - DELETE_COMPLETE - AWS::S3::Bucket - S3Bucket
  | CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - dataeng-buildkite-test-dev
  | Serverless: Operation failed!
  |  
  | Serverless Error ---------------------------------------
  |  
  | An error occurred: S3Bucket - Encountered unsupported property ServerSideEncryptionByDefault.
  |  
  | Get Support --------------------------------------------
  | Docs:          docs.serverless.com
  | Bugs:          github.com/serverless/serverless/issues
  | Issues:        forum.serverless.com
  |  
  | Your Environment Information -----------------------------
  | OS:                     linux
  | Node Version:           8.11.2
  | Serverless Version:     1.30.1
  |  

```

I followed the CF template according to: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-bucketencryption (but they didn't have a KMS example)..

**Comment by AnthonyWC** [comment]
nm this worked:

```
  - Resources:
      S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: "${self:service}-${opt:stage, self:provider.stage}"
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: 'aws:kms'
                  KMSMasterKeyID: "aws:kms:${self:provider.stage}:#{AWS::AccountId}:key/${self:custom.kms.${self:provider.stage}}"
```
