### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by Mr-SD** [serverless/serverless#5260]
# This is a (Bug Report)

## Description
CORS is not working. 

For bug reports:
* What went wrong?
Setting `cors:true` didn't enable CORS on api gateway.

* What did you expect should have happened?
CORS should be enabled for the endpoint on API Gateway.

* What was the config you used?
```
service: cors-test

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          cors: true

```

* What stacktrace or error message from your provider did you see?
None.

## Additional Data

* ***Serverless Framework Version you're using***: 1.30
* ***Operating System***: NixOS
