### ISSUE TITLE
raw flag during invoke not doing anything

### ISSUE THREAD

**Issue by xrendan** [serverless/serverless#5264]
I have deployed the following function: 

```
def handler(event, context):
    logging.error(event)

    # data = json.loads(event)
    data = event
    if 'src' not in data or 'dst' not in data or 'message' not in data:
        logging.error("Validation Failed")
        raise Exception("Missing required attribute, make sure you include 'src', 'dst' and 'message' attributes")

    plivo_response = send_message(data['src'], data['dst'], data['message'])

    response = {
        "statusCode": 200,
        "body": plivo_response
    }
    return response

in this context when invoked with **serverless invoke local -f send_message -l --data {"dst":"1111111111","src":"222222222","message":"test"} --type Event --raw**

event is the string "{dst:1111111111,src:222222222,message:test}" which is evidently being parsed since the double quotes are removed

```

For bug reports:

* What went wrong?

--raw doesn't do anything, data continues to be parsed

* What did you expect should have happened?
raw string to be sent to function as event data

* What was the config you used?

serverless.yml
```
service: service # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    PLIVO_AUTH_ID: ${file(env.json):PLIVO_AUTH_ID}
    PLIVO_AUTH_TOKEN: ${file(env.json):PLIVO_AUTH_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1


functions:
  send_message:
    handler: messaging.handler

  schedule_message:
    handler: scheduling.handler


resources:
  Resources:
    PendingMessagesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      # Important! This should be switched to Retain when actual data is present
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
```

* ***Serverless Framework Version you're using***: 1.30.3
* ***Operating System***: Windows
