### ISSUE TITLE
Setting provider.stage causes serverless package/deploy to hang.

### ISSUE THREAD

**Issue by thomasmichaelwallace** [serverless/serverless#5275]
Setting provider.stage:

```
provider:
  name: aws
  runtime: nodejs8.10
  stage: whatever
```

Seems to cause serverless to hang indefinitely (100% CPU usage from node) since upgrading from 1.29.7 to 1.30.2.

Possibly related: #5241

**Comment by shanehandley** [comment]
Hey @thomasmichaelwallace are you seeing the same issue with `1.30.3`? I cannot reproduce this with the current release using the follwing basic config:

```yaml
service: test-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: whatever
```

Both `sls deploy` and `sls package` execute for me:

```bash
sls deploy
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Service Information
service: test-service
stage: whatever
region: us-east-1
stack: test-service-whatever
api keys:
  None
endpoints:
  None
functions:
  None
```
