### ISSUE TITLE
Request:  Machine parsable output for "serverless info"

### ISSUE THREAD

**Issue by brettswift** [serverless/serverless#5281]
# This is a  Feature Proposal

## Description

The output from `serverless info -v` is fairly parsable, but it would be nice if it was more so. 

For instance, if I want to parse stack outputs from this example: 

```
Service Information
service: bswift-mock-function
stage: mock
region: us-west-2
stack: bswift-mock-function-mock
api keys:
  None
endpoints:
  None
functions:
  createUser: bswift-mock-function-mock-createUser
  resetPassword: bswift-mock-function-mock-resetPassword

Stack Outputs
ResetPasswordLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:1234567899:function:bswift-mock-function-mock-resetPassword:1
CreateUserLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:1234567899:function:bswift-mock-function-mock-createUser:1
ServerlessDeploymentBucketName: bswift-mock-function-moc-serverlessdeploymentbuck-1irhxs118rehn

```

I would need to cut the file after "Stack Outputs"  and then parse as yaml,  (or cut on ':')  and get my key/values pairs. 

Is that enough for me?  Yes.   Does it make me think the output might change? Yes.  

If there was an explicit machine parsable output this might help me in some 'funky'  CICD flows. 

For feature proposals:
* If I run serverless and want to get some information in the next step, it would be nice to have easier access to this.

Similar or dependent issues:
* couldn't find one
