### ISSUE TITLE
Allow specifying a custom prefix under which the artifacts will be deployed to S3

### ISSUE THREAD

**Issue by weeniearms** [serverless/serverless#5293]
# This is a Feature Proposal

## Description

Currently, the prefix under which artifacts are deployed is hardcoded to `serverless`, which might not be a perfect fit for every setup. E.g. when using fine grained access control based on prefix where each team/service is assigned a role with access to a specific prefix in a shared S3 bucket.

Therefore, configuration should support an option for specifying a custom `deploymentPrefix` (or something similar) as in the example below.

```
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  deploymentPrefix: my-app-prefix
```

Willing to submit a PR if you would find it useful and we agree on what the config should look like.
