### ISSUE TITLE
Add to AWS Lambda function the option to set a S3 zip file as package artifact

### ISSUE THREAD

**Issue by bzemms** [serverless/serverless#5315]
# This is a (Feature Proposal)

## Description
For deployment propose, I suggest to add to AWS Lambda **function** the option to set a **S3 zip file** as package **artifact** 

exactly as it allowed in Cloud Formation:  [aws-properties-lambda-function-code](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html)

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

In use case of a deployment mode, when build / packaging and tests are done in a separate process than serverless framework. or multiple deployment on different stages.

* If there is additional config how would it look
```yml;
functions:
  foo:
    package:
      artifact: 
        S3Bucket: my_bucket
        S3Key: my_folder/my_key.zip
```
Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
