### ISSUE TITLE
Cannot use functions in the custom section of serverless.yml

### ISSUE THREAD

**Issue by HetorusNL** [serverless/serverless#5316]
# This is a Bug Report
_Note that sensitive information has been replaced with example text, without impacting correctness or the mentioned errors._

### What went wrong?
When writing a serverless.yml for aws, functions are not resolved in the custom section of the serverless.yml file used by various plugins.
Functions include:
* Fn::ImportValue \<name\> (import the value of a cloudformation export)
* Fn::GetAtt: [\<id\>, \<property\>]  (get the value for the property defined in the same serverless.yml file)
* Ref: ${AWS::AccountId}
So when plugins access the function that should generate a value, the function is parsed as [Object object], which is highly likely just the {function: argument} object mentioned above.

### What did you expect should have happened?
I expect the functions be executed before the values are parsed into the plugins.

### What was the config you used?
The (minimal) config used is:
```yaml
# name of the serverless service
service: serverless-service

# basic settings specifying aws is used in combination with python 3.6(.6)
provider:
  name: aws
  runtime: python3.6
  stackName: serverless-stackname

custom:
  # this will cause the serverless-s3-remover plugin to empty the s3 buckets before stack deletion
  remover:
    buckets:
      # both options below don't work
      - Ref: TestBucket  # reference to a resource in this yaml
      - Fn::ImportValue: TestBucketOtherStack  # when a different stack is deployed and exports the bucket name with this name
      # however, hardcoding the bucketname does:
      - test-bucket-1234567890-us-east-1

# resources and outputs specified according to cloudformation template and syntax
resources:
  Resources:
    # the bucket resources generated by this template
    TestBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName:
          Fn::Join:
            - "-"
            - - test-bucket
              - Ref: AWS::AccountId
              - Ref: AWS::Region

  Outputs:
    # the exports of the bucketnames that are generated by this template
    TestBucket:
      Value:
        Ref: TestBucket
      Export:
        Name: TestBucket

    TestBucketArn:
      Value:
        Fn::GetAtt: [TestBucket, Arn]
      Export:
        Name: TestBucketArn

plugins:
  - serverless-s3-remover
```

### What stacktrace or error message from your provider did you see?
the command serverless s3remove is used to invoke the plugin (with the two buckets specified in the custom section of serverless.yml, and the third is the hardcoded bucket name):
```bash
username@machine:~/some/path/here$ serverless s3remove
S3 Remover: Faild: [object Object] may not be empty.
S3 Remover: Faild: [object Object] may not be empty.
S3 Remover: Success: test-bucket-1234567890-us-east-1 is empty.
```

## Similar or dependent issues:
Not found.

## Additional Data

* ***Serverless Framework Version you're using***:
Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.12.0
     Serverless Version:     1.32.0

* ***Operating System***:
Linux (Debian Stretch).

* ***Stack Trace***:
Stack trace is pasted above.

* ***Provider Error messages***:
Provider did not output error messages.

**Comment by danmoore83** [comment]
+ 1. 
Hey guys. Love the serverless framework.

Just wanted to note that this also affects included yml files as well.
e.g. `custom: ${file(./config/serverless/custom.yml):custom}`

The serverless object inside the constructor of plugins only has the reference to the file like above, rather than the resolved file contents. 
This is causing some plugins not to work correctly (in my case serverless-plugin-offline-dynamodb-stream)

I can work around it currently by including those items directly in the core serverless.yml file but would be good to not have to.

Thanks.

**Comment by oniice** [comment]
Also having this same issue

I have my buckets named like this:
```
custom:
  myBucket: ${self:provider.stage}-${self:service}-failed-files-#{AWS::AccountId}
  remover:
    buckets:
      - ${self:custom.myBucket}
```

And when the remover runs, it hasn't got the transformed properties
