### ISSUE TITLE
UserPoolUser update may delete the user instead.

### ISSUE THREAD

**Issue by LosD** [serverless/serverless#5317]
# This is a Bug Report

## Description
Updating an immutable attribute of an AWS::Cognito::UserPoolUser ends up with a deleted user.

This might be an issue with CloudFormation itself, though, but I'm not sure, so I thought I'd start here.

It might also be a configuration user. I've taken the configuration from AWS' sass-identity-cognito multi tenant example, and it works there, but the setup is a bit weird, as it's from before the UserNameAttribute UserPool property arrived. In general that doesn't really matter, as users doesn't sign themselves up, but I guess it might affect how Serverless or Cloudformation treats updating (I'll experiment a bit around this).

For bug reports:
* What went wrong?
CloudFormation creates the new user (I guess it can't update, since the changed value is immutable). Then deletes the original user. However, I guess that original user is really the new user, since the new user is gets deleted.

* What did you expect should have happened?
New user is created, and not re-deleted.
* What was the config you used?
Here's the relevant bits:
```YAML
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.productName}-${self:custom.stage}-system
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate:
          ...
        UnusedAccountValidityDays: 90
      AliasAttributes:
      - phone_number
      AutoVerifiedAttributes:
      - email
      - phone_number
      MfaConfiguration: OFF
      Policies:
        PasswordPolicy:
          ...
      SmsConfiguration:
        ...
      Schema:
      - Name: 'email'
        Required: true
      - AttributeDataType: String
        DeveloperOnlyAttribute: false
        Mutable: false
        Name: 'tenant'
        Required: false
        StringAttributeConstraints:
          MaxLength: 256
          MinLength: 1
  InitialSystemAdminUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      UserPoolId:
        Ref: CognitoUserPool
      Username: ${self:custom.systemUserEmail}
      DesiredDeliveryMediums:
      - EMAIL
      ForceAliasCreation: true
      UserAttributes:
      - Name: email
        Value: ${self:custom.systemUserEmail}
      - Name: custom:tenant
        Value: ${self:custom.systemTenantId}
      - Name: given_name
        Value: System
      - Name: family_name
        Value: Admin
```
* What stacktrace or error message from your provider did you see?
None.

## Additional Data

* ***Serverless Framework Version you're using***: 1.31.0
* ***Operating System***: Ubuntu Linux
