### ISSUE TITLE
Variable interpolation fails on nested interpolation

### ISSUE THREAD

**Issue by Tehnix** [serverless/serverless#5336]
# This is a Bug Report

## Description

When using nested variable interpolation, serverless will fail during `sls print`, for the provider variable `stage`, if it contains an `opt:stage` in the nesting that has not been passed.

More concretely, the following template will fail when running `sls --stage prod print` but pass when given `sls print` (i.e. without the `opt`, meaning it will use the opts fallback).

```yaml
service: vpc

provider:
  name: aws
  region: eu-west-1
  stage: ${self:custom.vpcStage}

custom:
  vpcStageMap:
    prod: prod
    staging: staging
    integration: staging
  vpcStage: ${self:custom.vpcStageMap.${self:custom.originalStage}}
  originalStage: ${opt:stage, 'staging'}
```

Running `sls --stage prod` fails to resolve `provider.stage` with,

```
 Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:custom.vpcstage' could not be found.


  Serverless Error ---------------------------------------

  Trying to populate non string value into a string for variable ${self:custom.vpcstage}. Please make sure the value of the property is a string.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.32.0

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Running with `sls print` succeeds with,

```
service: vpc
provider:
  stage: staging
  region: eu-west-1
  name: aws
custom:
  vpcStageMap:
    prod: prod
    staging: staging
    integration: staging
  vpcStage: staging
  originalStage: staging
...
```

A workaround on the problem is to provide a fallback on `stage: ${self:custom.vpcStage}` such as,

```yaml
service: vpc

provider:
  name: aws
  region: eu-west-1
  stage: ${self:custom.vpcStage, 'FALLBACK-NOT-A-VALID-STAGE'}
...
```

Which will resolve correctly using the actual value passed to `originalStage: ${opt:stage, 'staging'}`, giving the following for `sls --stage prod`,

```
service: vpc
provider:
  stage: prod
  region: eu-west-1
  name: aws
custom:
  vpcStageMap:
    prod: prod
    staging: staging
    integration: staging
  vpcStage: prod
  originalStage: prod
...
```

This seems to be an error `opt:stage` not getting resolved properly at the time that `provider.stage` is looked at. A further note is that this only seems to affect `provider.stage`, and possible other places that *require*  a string (e.g. environment variables), but not in other places, like in `custom`, etc.

Let me know if there is more information I can give to help with debugging this! We often seem to experience problems with how variables are resolved :/

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: macOS 10.14.0

**Comment by exoego** [comment]
It seems that the issue is not reproducible from the given configuration on v1.36.1.
`sls deploy --stage prod` finishes successfully.

BTW, I noticed the error message contains all-lowercase **vpcstage** 

```
  A valid service attribute to satisfy the declaration 'self:custom.vpcstage' could not be found.
```

but it is camel-case **vpcStage** in the provided yml. Are these correct?

```yml
custom:
  vpcStageMap:
    prod: prod
    staging: staging
    integration: staging
  vpcStage: ${self:custom.vpcStageMap.${self:custom.originalStage}}
```
