### ISSUE TITLE
Resolution of template variables in provider.profile should happen before getting CloudFormation outputs

### ISSUE THREAD

**Issue by aneilbaboo** [serverless/serverless#5337]
# This is a Bug Report

## Description

I have the following in my `serverless.yml`:

```yaml
service:
  name: myservice

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.common.stage}
  region: ${self:custom.common.region}
  profile: ${self:custom.common.profile}
  deploymentBucket: myservice-deployment-bucket

custom:
  common: ${file(./serverless/common.js).values}
```

For bug reports:
* What went wrong?
If I add Cloudformation template variables (`${cf:stack.var}`) to the above `serverless.yml` file, I get an error. For example, if I add cf references to the custom section:

```yaml
custom:
  common: ${file(./serverless/common.js).values}
  subnetId: ${cf:app-init.subNetId}
  securityGroupId: ${cf:app-init.securityGroupId}
```

I get an error `Profile ${self:custom.common.profile} does not exist`. 

I'm guessing that resolution of CloudFormation outputs happens before resolving template variables in the provider key. 

* What did you expect should have happened?

Resolution of template variables in `provider.profile` should happen before querying CloudFormation outputs.

* What was the config you used?

We deploy our serverless stack across several different AWS accounts. We use Serverless template variables to determine the profile, so we need variable resolution to happen *before* `${cf:stack.var}` expressions are evaluated.

* What stacktrace or error message from your provider did you see?

```shell
$ sls print
Loading offline.env environment
Serverless: Generating offline settings

  Error --------------------------------------------------

  Profile ${self:custom.common.profile} does not exist

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.32.0
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: macOS High Sierra 10.13.6

**Comment by balmasi** [comment]
did you find a way to resolve it? It's more than a month later and I'm seeing the same issue

**Comment by aneilbaboo** [comment]
I couldn't get `${cf:...}` variables to work because of this issue. I managed to get things working by declaring an export for the output, and then importing that using `Fn::ImportValue: ...` where I needed to consume the value.

e.g.,

```yaml
# globals/serverless.yml creates global resources used several other stacks:
...
Outputs:
  systemId:
    Description: The system VPC id
    Value: 
      Ref: SystemVPC
    Export:
      Name: SystemVPCId
```

```yaml
# in backend/serverless.yml, we can access the global resources like this:
...
custom:
  systemVPCId: 
    Fn::ImportValue: SystemVPCId
```

Now we can access the global resource using: `${self:custom.systemVPCId}`.

**Comment by aneilbaboo** [comment]
@balmasi  I never managed to get `${cf:...}` variables to work. 

Instead, I exported each output, and then imported it in other stacks using `Fn::ImportValue: ...`.

e.g.,

```yaml
# globals/serverless.yml creates global resources used several other stacks:
...
Outputs:
  systemId:
    Description: The system VPC id
    Value: 
      Ref: SystemVPC
    Export:
      Name: SystemVPCId
```

```yaml
# in backend/serverless.yml, we import the exported value like this:
...
custom:
  systemVPCId: 
    Fn::ImportValue: SystemVPCId
```

Now we can refer to it using: `${self:custom.systemVPCId}`.

**Comment by Elias-Serneels** [comment]
> @balmasi I never managed to get `${cf:...}` variables to work.
> 
> Instead, I exported each output, and then imported it in other stacks using `Fn::ImportValue: ...`.


Thanks for this. It really helped me out in one of my projects.

I didn't notice at first that I had to explicitly export the values to be able to reference them this way (previously when using ${cf:..} this wasn't required). 

And just a tip: cloudformation exports are unique within a region so to work around this I added the stack-name to all of them:
```yml
Outputs:
  systemId:
    Description: The system VPC id
    Value: 
      Ref: SystemVPC
    Export:
      Name: !Sub "${AWS::StackName}-SystemVPCId"
```
