### ISSUE TITLE
[User Error] Typo in serverless.yml that should probably be detected at parse time

### ISSUE THREAD

**Issue by ablankenship10** [serverless/serverless#5340]
# This is a (Bug Report / Feature Proposal)

Bug Report / Feature

## Description

Feel pretty dumb about this one but suggesting a potential fix that could save others in the future.

Attempting to setup an S3 Bucket with Lambda event notification on ObjectCreate event, ended up spending hours tracking down an issue that should probably be caught at serverless.yml parse time.

For bug reports:
* What went wrong?

The stack was mostly deployed fine until the very end where a somewhat cryptic error was returned. The error was:  

`An error occurred: S3BucketContent - Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: BDAD922E1C8F9AF8; S3 Extended Request ID: OveJPtub1t7kBmokwpQuoRNoBWT2qTtwf671Pi2jVQU5cKcm2mLyzN4XF76oU6EcSc0Gb74MmQU=).`

After several hours I traced the issue to a typo in a variable:

`SourceArn: arn:aws:s3:::{$self:custom.contentBucket}`

instead of the correct:

`SourceArn: arn:aws:s3:::${self:custom.contentBucket}`

Note the flip of `{$self:...` instead of `${self:...`

* What did you expect should have happened?

An error message telling me the yaml failed to parse due to a typo.

* What was the config you used?

```
service: 'myservice'

custom:
  contentBucket: ${self:service}-${self:provider.stage}-content

provider:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::${self:custom.contentBucket}
        - arn:aws:s3:::${self:custom.contentBucket}/*


functions:
  ContentCreate:
    handler: src/controllers/content.create
    events:
      - s3: content

resources:
  Resources:
    S3BucketContent:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${self:custom.contentBucket}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
    ContentCreateLambdaPermissionContentS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - ContentCreateLambdaFunction
            - Arn
        Principal: s3.amazonaws.com
        Action: lambda:InvokeFunction
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: arn:aws:s3:::{$self:custom.contentBucket}

```

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Additional parsing checks for invalid usage of variables. I realize this case may be a valid string but even a non fatal warning would be nice. Regex could detect various potential typo errors that could indicate a user wrote a variable incorrectly.

Such cases as:

`{$ ...}` - $ inside brackets
`{self ... }`  - Missing $ when attempting to use brackets around potential variables such as self or provider

* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Ubuntu Linux
* ***Stack Trace***:
* ***Provider Error messages***:

`An error occurred: S3BucketContent - Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: BDAD922E1C8F9AF8; S3 Extended Request ID: OveJPtub1t7kBmokwpQuoRNoBWT2qTtwf671Pi2jVQU5cKcm2mLyzN4XF76oU6EcSc0Gb74MmQU=).`
