### ISSUE TITLE
serverless creates public S3 buckets even when I explicitly set AccessControl to Private

### ISSUE THREAD

**Issue by ishanjain28** [serverless/serverless#5341]
# This is a Bug Report

## Description

My latest configuration file is here, https://hastebin.com/irulusodem.http

My objective is to, 
* Create a private S3 bucket with some Bucket policy.
* Attach a lambda function to the bucket. So, Every time an object is created, The lambda function should be triggered. 

Initially, I had a simpler configuration file, https://hastebin.com/ejowodogaf.http but this kept creating a Public S3 bucket so, I figured you guys might have changed something. So I changed the configuration file to the one at the beginning of the description and it still keeps creating Public s3 buckets. There is no error anywhere and I just can not figure out any reason for this.

For bug reports:
* What went wrong? I set up a resource(S3 bucket) in the resources section. I explicitly set `AccessControl` to `Private` but it still keeps creating Public S3 bucket. 
* What did you expect should have happened? It should have created a Private S3 bucket
* What was the config you used? 
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Linux(Linux y50 4.18.10-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 26 09:48:22 UTC 2018 x86_64 GNU/Linux)
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by ishanjain28** [comment]
This was fixed by fixing Principal from `*` to Root AWS Account ARN.

**Comment by kmualem** [comment]
Can you please paste here the serverless file that set the accessControl of the bucket to private?

Thanks!

**Comment by MatthewNielsen27** [comment]
Posting this for future reference:

```yaml
resources:
  Resources:
    MyBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:custom.my_bucket_name}
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
```

The above config creates a bucket with no public access.
