### ISSUE TITLE
Bad dynamic ARN property on sqs event

### ISSUE THREAD

**Issue by AndreaAdvanon** [serverless/serverless#5345]
# This is a Bug Report

## Description
I'm trying to set an sqs event using a dynamic arn:
```yaml
service: myservice

custom:
  region: eu-central-1
  mySQSQueue:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - sqs
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - ${env:MY_SQS_QUEUE}

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}

functions:
  fun:
    handler: handler.myhandler
    events:
      - sqs:
          arn: ${self:custom.mySQSQueue}
          batchSize: 10
```

But I get this error:
```
  Bad dynamic ARN property on sqs event in function "fun" If you use a dynamic "arn" (such as with Fn::GetAtt or Fn::ImportValue) there must only be one key (either Fn::GetAtt or Fn::ImportValue) in the arn object. Please check the docs for more info.
```
even if I'm using `Fn::Join:` just once.

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: Fedora 28
