### ISSUE TITLE
Cannot deploy different stage with Shared API Gateway

### ISSUE THREAD

**Issue by kyeljmd** [serverless/serverless#5347]
This is my cloudformation script

`{  
   "AWSTemplateFormatVersion":"2010-09-09",
   "Description":"API",
   "Resources":{
      "APIGw":{  
         "Type":"AWS::ApiGateway::RestApi",
         "Properties":{  
            "Name":"API-GW"
         }
      }
   },
   "Outputs":{
      "ApiGwRestApiId":{  
         "Value":{  
            "Ref":"APIGw"
         },
         "Export":{  
            "Name":"apigw-restApiId"
         }
      },
      "eyesApiGwRestApiRootResourceId":{  
         "Value":{  
            "Fn::GetAtt":[  
               "APIGw",
               "RootResourceId"
            ]
         },
         "Export":{  
            "Name":"apigw-rootResourceId"
         }
      }
   }
}`

```
service: template-test-service

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  stage: ${self:custom.environment.stage}
  environment:
    stage: ${self:custom.environment.stage}
  apiGateway:
    restApiId:
      'Fn::ImportValue': apigw-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': apigw-rootResourceId

```

When I perform an sls deploy --stage dev this works however when I perform an sls deploy --stage prod it fails. with this error 

`Another resource with the same parent already has this name`

What is a way to work around this?

**Comment by mskutin** [comment]
This is not a bug, each stage should have its own API Gateway, so you can reference restApiId and rootResourceId of each stage in your template. Consider the following example:

```yaml
service: master-api
provider:
  name: aws
custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  prefix: ${self:service}-${self:custom.region}-${self:custom.stage}
resources:
  Resources:
    rootApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.prefix}
  Outputs:
    rootApiGatewayId:
      Value:
        Ref: rootApiGateway
      Export:
        Name: ${self:custom.prefix}-restApiId
    rootApiGatewayResourceId:
      Value:
         Fn::GetAtt:
          - rootApiGateway
          - RootResourceId
      Export:
        Name: ${self:custom.prefix}-rootResourceId
```

```yaml
service: service-a
custom:
  stage: "${opt:stage, self:provider.stage}"
  region: ${opt:region, self:provider.region}
  prefix: ${self:service}-${self:custom.region}-${self:custom.stage}
  rootApiGatewayId: "master-api-${self:custom.region}-${self:custom.stage}-restApiId"
  rootApiGatewayResourceId: "master-api-${self:custom.region}-${self:custom.stage}-rootResourceId"
provider:
  name: aws
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.rootApiGatewayId}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.rootApiGatewayResourceId}
```

Once you deploy master-api stack for dev and for prod stages you will be able to use exported references across your AWS account.
