### ISSUE TITLE
Feature Proposal: Support for Loop

### ISSUE THREAD

**Issue by AnthonyWC** [serverless/serverless#5352]
## Description

Currently serverless does not have support for loop.  I think it would be quite useful to have built-in support to loop through (at least initially) list.  If we look at other tools like Ansible (which also use YAML in their config format), they supported loop. 

For feature proposals:

It should be possible to implement this (perhaps as a plugin) that acts as a template engine that generate the exact code (for the loop) just prior to conversion to cloudformation.

For syntax reference, we can consider to adopt similar syntax like ansible loop (https://docs.ansible.com/ansible/2.5/user_guide/playbooks_loops.html)

Basic sample use case:

```
 - Resources:
      SSMParameter: << This have to be indexed in the code based on list length 
        Type: AWS::SSM::Parameter
        Properties:
          Name: "/foo/${{ item }}"
          Type: String
          Value: ${{ item }}
  loop:
    - value1
    - value2

(or equivalently)
custom:
  bar:
   - value1
   - value2

loop:
  ${custom:bar}

```

Result
 ```
 - Resources:
      SSMParameter1:
        Type: AWS::SSM::Parameter
        Properties:
          Name: "/foo/value1"
          Type: String
          Value: value1

  - Resources:
      SSMParameter2:
        Type: AWS::SSM::Parameter
        Properties:
          Name: "/foo/value2"
          Type: String
          Value: value2
```
