### ISSUE TITLE
Unexpected warning when unresolved deep variable has a fallback

### ISSUE THREAD

**Issue by onebytegone** [serverless/serverless#5353]
# This is a Bug Report

## Description

It's not clear yet if this is actually a bug or not. Either way, at least this behavior will be documented.

For bug reports:

* What went wrong?

    When a deep variable within a fallback is not found, the fallback works but a warning is logged to the CLI.

    ```
    $ sls package --cfg=bar
     Serverless Warning --------------------------------------
    
      A valid undefined to satisfy the declaration 'deep:2.test' could not be found.
    
    Serverless: Packaging service...
    Serverless: Excluding development dependencies...
    $ yq -r .Resources.HelloLambdaFunction.Properties.Environment.Variables.FOO .serverless/cloudformation-template-update-stack.json
    dev
    ```

    This warning does not get printed when the deep variable is found. Of course in this case, the fallback value isn't being used.

    ```
    $ sls package --cfg=foo
    Serverless: Packaging service...
    Serverless: Excluding development dependencies...
    $ yq -r .Resources.HelloLambdaFunction.Properties.Environment.Variables.FOO .serverless/cloudformation-template-update-stack.json
    override
    ```

* What did you expect should have happened?

    As noted in https://github.com/serverless/serverless/issues/5027#issuecomment-425909717, my initial reaction was that the warning is unexpected. The purpose of the fallback is to handle the situation when the variable does not exist. However, I could also see a case being made for having a warning (perhaps at a debug level though?).

* What was the config you used?

    _The following is from: https://github.com/serverless/serverless/issues/5027#issuecomment-402871790_

    Download: [warn_unsatisfied_deep_var.zip](https://github.com/serverless/serverless/files/2446267/warn_unsatisfied_deep_var.zip)
    
    #### serverless.yml
    
    ```yml
    service: broken
    
    provider:
      name: aws
      runtime: nodejs6.10
      environment:
        FOO: ${self:custom.config.test, self:provider.stage}
    
    custom:
      config: ${file(./${opt:cfg}.yml)}
    
    functions:
      hello:
        handler: handler.hello
    ```
    
    #### foo.yml
    
    ```yml
    test: 'override'
    other: ignore
    ```
    
    #### bar.yml
    
    ```yml
    other: ignore
    ```

* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
* #5027

## Additional Data

* ***Serverless Framework Version you're using***: v1.32.0
* ***Operating System***: n/a
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a
