### ISSUE TITLE
Custom error status codes using pattern matching not working

### ISSUE THREAD

**Issue by saikumar-madana** [serverless/serverless#5382]
In my project, I am using serverless. I am trying to change the default statusCodes and response. I have tried the following.

```
dashboard:
  handler: src/common/dashboard.dashboard
  role: CommonServicesFullAccessRole
  timeout: 30
  events:
    - http:
        integration: lambda
        path: ui/dashboard/
        method: get
        request: 
          parameters: 
            paths: 
              id: true
        response:
          headers:
            Content-Type: "'text/html'"
          template: $input.path('$')
          statusCodes:
            400:
              pattern: '[\s\S]*Bad Request[\s\S]*'
              template: $input.path('$.errorMessage')
              headers:
                Content-Type: "'text/plain'"
```

In my lambda I am returning the error callback as
`
return callback('Bad Request');`

Still I am not able to get the response with the specified statusCode. I am not sure where the exact error is. Following is the response I am getting.

![image](https://user-images.githubusercontent.com/17292167/46862388-4ff5de00-ce32-11e8-85a5-ea837b9da677.png)

Please help me solve this.
Thank you...
