### ISSUE TITLE
The CloudFormation template is invalid: Template format error

### ISSUE THREAD

**Issue by 8vius** [serverless/serverless#5385]
I'm getting the stated error when trying to deploy to my `prod` stage, we previously were only deploying to the default stage and this resource in particular we had to rename to consider the stages. This is the block where it's failing:

```
    startDemoSubmission:
      name: startDemoSubmission-${self:custom.stage}
      definition:
        Comment: "Handles creating a demo instance and sending it to a submission chain"
        StartAt: SetupDemo
        States:
          SetupDemo:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-submissions_setupDemoSubmission"
            Next: CreateSubmissionChain

          CreateSubmissionChain:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-submissions_createSubmissionChain"
            Next: DebitArtistAccount
```

These are how we have our outputs set:

```
resources:
  Outputs:
    StateMachine:
      Description: "The ARN of the provisioned state machine"
      Value:
        Ref: StartDemoSubmission
    UserPoolId:
      Value:
        Ref: CognitoUserPool
    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
    IdentityPoolId:
      Value:
        Ref: CognitoIdentityPool
    EmailTemplatesBucketName:
      Value:
        Ref: EmailTemplatesBucket
```

And the error itself:

```
  Error --------------------------------------------------

  The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [StartDemoSubmission] in the Resources block of the template

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2
     Serverless Version:     1.31.0
```
