### ISSUE TITLE
The pool: <POOL_ID> property should also support Ref

### ISSUE THREAD

**Issue by JaderCM** [serverless/serverless#5401]
_Originally posted by @HyperBrain in https://github.com/serverless/serverless/issues/3637#issuecomment-302641979_

If an existent User Pool change the logical Id to have the prefix "CognitoUserPool" a new User Pool will be created and all users will be lost.

To avoid create a new Pool Id to use the feature of Cognito Pool Triggers with Lambda Functions to keep the existent users, it's necessary have a way to reference an existent pool.

**Comment by hassankhan** [comment]
From memory, I think this issue was blocked because of #3212. Happy to be corrected though.

**Comment by JaderCM** [comment]
@hassankhan could you help me to use a existent user pool (that was created by serverless framework) as a reference of a lambda function?

My example:

```yaml
functions:
  CognitoTriggerPostConfirmationLambdaFunction:
    handler: Cognito/Triggers.PostConfirmation
    events:
      - cognitoUserPool:
          pool: [How-Reference-ExistentUserPool?]
          trigger: PostConfirmation

resources:
  Resources:
    ExistentUserPool:
      Type: AWS::Cognito::UserPool
```

**Comment by ebisbe** [comment]
I'm stuck with the same as @JaderCM I have a preexisting Cognito Pool that the logical Id is not prepended with CognitoUserPool.

**Comment by JaderCM** [comment]
My workaround was change the source and works. But I cannot keep this branch in my machine and if this change will apply, we will break the current configurations that are using this feature.

[Current master/lib/plugins/aws/lib/naming.js (line 263):](https://github.com/serverless/serverless/blame/master/lib/plugins/aws/lib/naming.js#L263)
```javascript
getCognitoUserPoolLogicalId(poolId) {
  return `CognitoUserPool${this.normalizeNameToAlphaNumericOnly(poolId)}`;
},
```
My workaround:
```javascript
getCognitoUserPoolLogicalId(poolId) {
  return poolId;
},
```

**Comment by ebisbe** [comment]
I prefer a proper solution to the problem rather than what you propose so I can stick with the correct versioning of the framework. For the moment I will configure the trigger manually and add a reminder as a comment but good to know the workaround  @JaderCM

**Comment by hassankhan** [comment]
@JaderCM as you correctly determined, this won't be possible without a change to the framework itself. My advice would be to create a pull request and making sure that any existing tests pass while adding a few more tests to verify the new changes.

**Comment by JaderCM** [comment]
What do you think to create a new property in your class with the name existentPoolId?

I can create the pull request with these changes/tests/docs. But first, I would like to discuss with you because this is "your son". :smiley:

**Comment by hassankhan** [comment]
Haha I wouldn't say I was _that_ attached to it, but I appreciate it 👍 

Personally I think it shouldn't need a separate property, but allow `Ref` usage similar to how other events work. That said, the decision should rest with the framework maintainers IMO.

/cc @horike37 @HyperBrain @pmuens @eahefnawy

**Comment by ahawkins** [comment]
This behavior is confusing and possible destructive. That's not a good combination for anything in production. If you specify a pool name that doesn't exist, then a new one is created. That's unexpected. If you specify a pool name that doesn't match to anything in the template, then there's no error either. That's confusing.

I think the technical problem is that there's no CloudFormation resource directly applied to Lambda. Instead it must be configured on the UserPool. You can see this for yourself in the AWS console. There's no way to add a trigger from the Lambda console. You have to go into Cognito and associate it there.

Given serverless strange (to me) behavior, I think it's better to create the user pool ourself and associate trigger's via Lambda ARNs. Those are easy enough to write in which also avoid circular dependencies (which is another issue entirely trying to define user pool triggers).

Here's a snippet from my resources section demonstrating my solution. Note that I'm using the pseudo parameter plugin for nice `AWS::Region` and friends replacements. 

```yml
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: "${self:service}-${self:provider.stage}"
        # .... snipped ....
        LambdaConfig:
          PostConfirmation: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-postConfirmation"
```
`postConfirmation` is the name of a function.

My verdict: **do not use the provided Cognito User Pool events.**
