### ISSUE TITLE
reservedConcurrency configuration is not persisting to the stack

### ISSUE THREAD

**Issue by raids** [serverless/serverless#5402]
# This is a Bug Report

## Description

A function's `reservedConcurrency` property is not being persisted to the CloudFormation template and therefore stack. See my function configuration below:

```yaml
functions:
  functionName:
    handler: bin/function-binary
    reservedConcurrency: 0
    events:
    - sqs: ${self:custom.sqsQueueArn}
```

There are no errors or anything, the property is just ignored. According to the docs, it should be a valid property: https://serverless.com/framework/docs/providers/aws/guide/functions/

For feature proposals:
N/A

Similar or dependent issues:
N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: MacOS
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
