### ISSUE TITLE
Function event (schedule): Fn::GetAtt is not resolved inside schedule.input

### ISSUE THREAD

**Issue by spg** [serverless/serverless#5441]
# This is a Bug Report

## Description

* What went wrong?
`Fn::GetAtt` was not evaluated inside the `input` field

* What did you expect should have happened?
The `ClusterArn` field in `input` should be resolved to the ARN of the `Cluster` resource

* What was the config you used?
Here's my serverless.yml file:

```yml
service: my-service

provider:
  name: aws
  runtime: python3.6
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._'\",\\-\\/\\(\\)]+?)}" # Use this for allowing CloudFormation Pseudo-Parameters in your serverless.yml -- e.g. ${AWS::Region}. All other Serverless variables work as usual.

package:
  exclude:
    - "*/**"
  include:
    - handler.py

functions:
  hello:
    handler: handler.handler
    runtime: python3.6
    memorySize: 128
    timeout: 30
    environment:
      CLUSTER_ARN: { Fn::GetAtt: [ Cluster, Arn ] }
    events:
    - schedule:
        rate: rate(1 minute)
        input:
          ClusterArn:  { Fn::GetAtt: [ Cluster, Arn ] }

resources:
    Cluster:
      Type: AWS::ECS::Cluster

```

Also, here's the Lambda's code (handler.py):
```python
import os


def handler(event, context):
    print(event)
    print(os.environ['CLUSTER_ARN'])
```

Checking out the CloudWatch logs, we can see that the `ClusterArn` is not resolved for the input value, but it's resolved for the environment variable:

```shell
START RequestId: 581a443c-dec5-11e8-b696-7f11041d6214 Version: $LATEST
{'ClusterArn': {'Fn::GetAtt': ['Cluster', 'Arn']}}
arn:aws:ecs:us-east-1:XXXXXXXXX:cluster/my-service-Cluster-KY39WYLK43N9
END RequestId: 581a443c-dec5-11e8-b696-7f11041d6214
REPORT RequestId: 581a443c-dec5-11e8-b696-7f11041d6214  Duration: 0.35 ms       Billed Duration: 100 ms         Memory Size: 128 MB     Max Memory Used: 21 MB  
```

* What stacktrace or error message from your provider did you see?
None

Similar or dependent issues:
N/A

## Additional Data

* ***Serverless Framework Version you're using***:   1.32.0
* ***Operating System***: OS X
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by federicojasson** [comment]
The same seems to happen with `Ref`:

```yaml
...
functions:
  MyFunction:
    ...
    events:
      - schedule:
          name: ...
          rate: ...
          input:
            url:
              Ref: 'Queue' # not working

...

resources:
  Resources:
    Queue:
      Type: AWS::SQS::Queue
      Properties:
        ...
```

Generates a literal JSON input:

```json
  ...
  "Input": "{\"url\":{\"Ref\":\"Queue\"}}"
  ...
```

I'm not sure if that's expected or not.
