### ISSUE TITLE
Trying to populate non string value into a string for variable ${self:provider.environment.XXX}

### ISSUE THREAD

**Issue by Stimul8d** [serverless/serverless#5470]
# This is a Bug Report

## Description

* What went wrong?
I am unable to use a ref'd env variable because it believes it is not a string.

* What did you expect should have happened?
The variable to be usable

* What was the config you used?

Here's my (edited) .yml ... The issue is in the custom scripts section.

```
service: test-api 

provider:
  name: aws
  runtime: nodejs6.10
  endpointType: regional
  stage: dev
  profile: default
  logRetentionInDays: 14
  region: eu-west-1
  environment:
    USER_POOL_ID: 
      Ref: CognitoUserPool

functions:
  submit:
    handler: handler.submit
    timeout: 10
    events:
      - http:
          path: submit
          method: put
          cors:
            origin: '*'
            headers:
                - Authorization
                - Content-Type
                - correlationId
                - X-Amz-Date
                - X-Amz-Security-Token
                - X-Amz-User-Agent
                - X-Api-Key

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: user_pool
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: client
        GenerateSecret: true
        UserPoolId:
          Ref: CognitoUserPool  

plugins:
  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
      'deploy:deploy': echo ${self:provider.environment.USER_POOL_ID}
```

* What stacktrace or error message from your provider did you see?

`  Trying to populate non string value into a string for variable ${self:provider.environment.USER_POOL_ID}. Please make sure the value of the property is a string.`

Similar or dependent issues:
* #5235 - But I think they may not be the same thing.

## Additional Data

* ***Serverless Framework Version you're using***: 1.32.0
* ***Operating System***: macOS 10.14
* ***Stack Trace***: As above
* ***Provider Error messages***: As above

**Comment by Stimul8d** [comment]
I should add that if I export-env, the user pool id is written successfully.

**Comment by jkruse14** [comment]
We just ran into something similar:

```
provider:
...
  environment:
    hello: 'world'

custom:
  another: ${self:provider.environment.hello}
```

Would fail; however, the below works

```
provider:
  hello: 'world'
...
  environment:
  ...
custom:
  another: ${self:provider.hello}
```

My *theory* (I have not found documentation) is that the provider.environment is *not* to be used with the serverless.yml, but is used to set up the process.env in nodejs.

We ended up moving these "environment" variables (which weren't **true** environment variables) to the custom section in our serverless.yml.
