### ISSUE TITLE
Stack at Packing external modules

### ISSUE THREAD

**Issue by stevezau** [serverless/serverless#5484]
# This is a Bug Report

## Description
I am unable to run sls deploy. Serverless is stuck at `Serverless: Packing external modules:..`

I've left it for over 1-2 hours and it's just stuck at that point. This did work in the past but I believe on an older serverless version.

Is there some way i can see what's going on? I've turned on `export SLS_DEBUG=*`

## Additional Data
* ***Serverless Framework Version you're using***:
```
    "serverless": "^1.32.0",
    "serverless-offline": "^3.31.0",
    "serverless-webpack": "^5.2.0",
```

* ***Operating System***:
Mac OSX 10.13.6

* ***Stack Trace***:
```
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 938ms
Built at: 14/11/2018 1:25:28 pm
         Asset      Size  Chunks             Chunk Names
    handler.js  75.1 KiB       0  [emitted]  handler
handler.js.map   156 KiB       0  [emitted]  handler
Entrypoint handler = handler.js handler.js.map
 [0] external "source-map-support/register" 42 bytes {0} [built]
 [1] external "moment-timezone" 42 bytes {0} [built]
 [2] external "chrono-node" 42 bytes {0} [built]
 [3] external "mindbody-api" 42 bytes {0} [built]
 [4] external "promise-pool-executor" 42 bytes {0} [built]
 [5] external "moment-range" 42 bytes {0} [built]
 [6] external "tough-cookie" 42 bytes {0} [built]
 [7] external "cheerio" 42 bytes {0} [built]
 [8] external "console-stamp" 42 bytes {0} [built]
 [9] external "lodash" 42 bytes {0} [built]
[10] external "deep-equal" 42 bytes {0} [built]
[11] external "axios" 42 bytes {0} [built]
[12] external "moment" 42 bytes {0} [built]
[13] external "phone" 42 bytes {0} [built]
[17] ./handler.js + 21 modules 69.8 KiB {0} [built]
     | ./handler.js 875 bytes [built]
     | ./src/appointments/index.js 5.62 KiB [built]
     | ./src/employees/index.js 2.23 KiB [built]
     | ./src/products/index.js 3.61 KiB [built]
     | ./src/services/index.js 2.88 KiB [built]
     | ./src/clients/index.js 313 bytes [built]
     | ./src/sales/index.js 11.4 KiB [built]
     | ./src/wages/index.js 5.3 KiB [built]
     | ./src/appointments/graph.schema.js 1.87 KiB [built]
     | ./src/utils.js 8.41 KiB [built]
     | ./src/cookie.js 1.56 KiB [built]
     | ./src/employees/graph.schema.js 1.1 KiB [built]
     | ./src/products/graph.schema.js 842 bytes [built]
     | ./src/services/graph.schema.js 1020 bytes [built]
     | ./src/clients/clients.js 3.68 KiB [built]
     |     + 7 hidden modules
    + 3 hidden modules
Serverless: Invoke webpack:package
Serverless: WARNING: Could not determine version of module source-map-support
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: source-map-support, moment-timezone@^0.5.23, chrono-node@^1.3.5, mindbody-api@file:../mindbody-api, promise-pool-executor@^1.1.1, moment-range@^4.0.1, moment@^2.22.2, tough-cookie@^2.4.3, cheerio@^1.0.0-rc.2, console-stamp@^0.2.7, lodash@^4.17.11, deep-equal@^1.0.1, axios@^0.18.0, phone@^2.2.0, limiter@^1.1.3, node-geocoder@^3.22.0, uuid@^3.3.2
```

# Config
```
service: dogue-mb

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment: ${file(./env.yml)}
  stage: prod
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    babelOptions:
      presets: ["node8"]

functions:
  getAppointments:
    timeout: 30
    description: Get Sales Data
    memorySize: 256
    handler: handler.getSales
 
....#### MORE FUNCTIONS BELOW HERE###
```
