### ISSUE TITLE
CloudFlare Workers & Webpack bundling

### ISSUE THREAD

**Issue by valentinbora** [serverless/serverless#5487]
# This is a Bug Report

## Description

* What went wrong?

The `serverless-cloudflare-workers@0.1.1` plugin does not work well with `serverless-webpack@5.2.0`. It seems to attempt to deploy the wrong artifact (i.e. the unbundled code).

* What did you expect should have happened?

It should have picked up the bundled version of the code and deployed that to CloudFlare APIs.

* What was the config you used?

```
service:
    name: myservice
    config:
        accountId: **** 
        zoneId: **** 
        workers:
            myworker:
                routes:
                    - abc.example.com/*

    custom:
        webpack:
            webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
            includeModules: true   # Node modules configuration for packaging
            packager: 'npm'   # Packager that will be used to package your external modules

provider:
    name: cloudflare

plugins:
    - serverless-webpack
    - serverless-cloudflare-workers

functions:
    routeDigitalOceanStage:
        handler: worker.handleRequest
        worker: myworker
        script: worker
        events:
            - http:
                url: abc.example.com/hello
                method: GET
```

* What stacktrace or error message from your provider did you see?

```
> sls deploy
Serverless: Bundling with Webpack...
Time: 1929ms
Built at: 11/14/2018 1:32:00 PM
    Asset      Size  Chunks             Chunk Names
worker.js  3.53 KiB       0  [emitted]  worker
Entrypoint worker = worker.js
 [0] ./node_modules/lodash/_baseIteratee.js 370 bytes {0} [built]
 [1] ./worker.js 2.08 KiB {0} [built]
 [2] ./node_modules/lodash/find.js 1.27 KiB {0} [built]
 [3] ./node_modules/lodash/_createFind.js 853 bytes {0} [built]
 [4] ./node_modules/lodash/isArrayLike.js 830 bytes {0} [built]
 [5] ./node_modules/lodash/isFunction.js 993 bytes {0} [built]
 [6] ./node_modules/lodash/_baseGetTag.js 565 bytes {0} [built]
 [7] ./node_modules/lodash/isObject.js 733 bytes {0} [built]
 [8] ./node_modules/lodash/isLength.js 802 bytes {0} [built]
 [9] ./node_modules/lodash/keys.js 204 bytes {0} [built]
[10] ./node_modules/lodash/_overArg.js 382 bytes {0} [built]
[11] ./node_modules/lodash/findIndex.js 1.62 KiB {0} [built]
[12] ./node_modules/lodash/_baseFindIndex.js 766 bytes {0} [built]
[13] ./node_modules/lodash/toInteger.js 370 bytes {0} [built]
Serverless: Packaging service...
Serverless: deploying route: [REDACTED]/*
Serverless: ❌  Fatal Error, Script Not Deployed!
Serverless: --> Error Code:10021
--> Error Message: "Uncaught SyntaxError: Unexpected identifier
  at line 1
"
Serverless: ✅  Routes Deployed
Serverless: ✅  Routes Deployed
```

Similar or dependent issues:
* #5258

## Additional Data

* ***Serverless Framework Version you're using***: `1.32.0`
* ***Operating System***: macOS 10.13.4
* ***Stack Trace***: See above
* ***Provider Error messages***: See above
