### ISSUE TITLE
Support for lambda trigger AWS Cognito UserMigration

### ISSUE THREAD

**Issue by collinglass** [serverless/serverless#5513]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

The use case is for supporting the lambda trigger User Migration inside AWS Cognito UserPool.

Here is a screenshot of the AWS Cognito console showing the trigger.

![screen shot 2018-11-22 at 9 40 37 am](https://user-images.githubusercontent.com/3614712/48891074-c7a82700-ee3a-11e8-9028-9c2714bfe8e4.png)

Here is what I imagine it would look like in the serverless template.

```
functions:
  migrateUser:
    handler: handler.migrateUser
    events:
      - cognitoUserPool:
          pool: MyUserPool
          trigger: UserMigration
```

Here is the error I got when I attempted to use it in my serverless template.

![screen shot 2018-11-22 at 9 42 55 am](https://user-images.githubusercontent.com/3614712/48891255-25d50a00-ee3b-11e8-9727-f84c1f677b73.png)

* If there is additional config how would it look

Similar or dependent issues:
