### ISSUE TITLE
S3 variable in yml variables file produces error

### ISSUE THREAD

**Issue by eangeeag** [serverless/serverless#5520]
# This is a Bug Report

## Description

I have a couple of S3 objects with AWS ids that I reference from the `serverless.yml` file in the following way:

```yaml
mode:
    local: local
    dev: cloud
    qa: cloud
    uat: cloud
    staging: cloud
    prod: cloud
serverlessTerraform:
    vpc:
      securityGroupIds: ${file(./serverlessTerraform.${self:custom.mode.${self:provider.stage}}.yml):securityGroupIds}
      subnetIds: ${file(./serverlessTerraform.${self:custom.mode.${self:provider.stage}}.yml):subnetIds}
    role :
      warmup: ${file(./serverlessTerraform.${self:custom.mode.${self:provider.stage}}.yml):roleWarmup}
      endpoint: ${file(./serverlessTerraform.${self:custom.mode.${self:provider.stage}}.yml):roleEndpoint}
```

The VPC key will be later used to supply VPC configuration for my lambdas as well as the roles.

This is the content of `serverlessTerraform.cloud.yml` file:

```yaml
securityGroupIds:
  - ${s3:${self:custom.serverlessBucket}/billpayments-lambda-postgres-https-access-sg-${self:provider.stage}}
subnetIds:
  - ${s3:${self:custom.serverlessBucket}/private-subnet-0}
  - ${s3:${self:custom.serverlessBucket}/private-subnet-1}
roleEndpoint: ${s3:${self:custom.serverlessBucket}/billpayments-api-role-${self:provider.stage}}
```

* What went wrong
When running `serverless deploy -v --stage dev` I get the following message:
```
Invalid variable reference syntax for variable s3:com-billpayments-serverless-dev. You can only reference env vars, options, & files. You can check our docs for more info.
```
Variables referenced from `serverless.yml` are being correctly referenced but no the s3 variables. 

* What did you expect should have happened?
Variables from s3 should have been read correctly and the `serverless deploy -v --stage dev` command should have continued without errors.

## Additional Data

* ***Serverless Framework Version you're using***:
`1.33.2`
* ***Operating System***:
MacOS Sierra  `10.13.6`
