### ISSUE TITLE
Do we support DynamoDB on-demand mode now?

### ISSUE THREAD

**Issue by 82949712** [serverless/serverless#5535]
Announce new billing model today

**Comment by robinvw1** [comment]
DynamoDB on-demand `is available globally in all commercial regions.`, they're telling in their announcement: https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing/

I've just tried it out by adding [BillingMode](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-billingmode):

```yaml
resources:
  Resources:
    ExampleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ExampleTable
        AttributeDefinitions:
          - AttributeName: exampleId
            AttributeType: S
        KeySchema:
          - AttributeName: exampleId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
```

Note that you don't need the `ProvisionedThroughput` (`ReadCapacityUnits`, `WriteCapacityUnits`) keys in your CloudFormation template anymore. Also note that updating your stack for the first time with this change will take a while, as your DynamoDB table will switch to On-Demand capacity.

![image](https://user-images.githubusercontent.com/793157/49213158-e884f500-f3c3-11e8-8171-f186cf7a12bd.png)
