### ISSUE TITLE
Set IoT permission without creating new rule

### ISSUE THREAD

**Issue by swhite24** [serverless/serverless#5541]
# This is a Feature Proposal

## Description

* Current support for creating IoT rules with a lambda action works great, but lambda can also be invoked by rules without being the direct action of the rule.  [See the docs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-functions.html#iot-func-aws-lambda) for more details.
* I would envision the only necessary configuration to be the ARN of an existing IoT rule, with the behavior changing to only create the `AWS::Lambda::Permission` and omit the `AWS::IoT::TopicRule`
* Potential config example:
  ```yaml
  functions:
    myfunc:
      handler: bin/handler
      events:
        - iot:
            arn: arn:aws:iot:us-east-1:11223344:rule/my-rule
  ```

Similar or dependent issues:
