### ISSUE TITLE
Lambda Layer not created

### ISSUE THREAD

**Issue by evgenykireev** [serverless/serverless#5549]
# This is a Bug Report

## Description

I follow documentation for lambda layers support - https://serverless.com/framework/docs/providers/aws/guide/layers/

* What went wrong?
CloudFormation failed with an error.

* What did you expect should have happened?
A layer is created and linked to a lambda function

* What was the config you used?
```
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

  layers:
    test:
      path: node_modules

functions:
  hello:
    handler: handler.hello
    layers:
       - {Ref: TestLambdaLayer}
```

* What stacktrace or error message from your provider did you see?
```
 The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [TestLambdaLayer] in the Resources block of the template
```

## Additional Data

* ***Serverless Framework Version you're using***:
1.34.0

* ***Operating System***:
macOS Sierra 10.13.5 

* ***Provider Error messages***:
Error --------------------------------------------------
  The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [TestLambdaLayer] in the Resources block of the template
