### ISSUE TITLE
Conditional custom authorizer depending on the stage

### ISSUE THREAD

**Issue by casertap** [serverless/serverless#5553]
# This is a Feature Proposal

## Description

The use case: You want to add a basic auth (using an authorizer) to access the staging environment but not for the production.
If the authorizer bloc would have an `enabled` attribute (like the pluging: serverless-domain-manager) we could do something like this:

```
custom:
  stage: ${opt:stage}
  staging_auth: true
  prod_auth: false 
...
     authorizer:
            enabled: ${custom:stage}_auth
            name: authorizerFunc
            ...
```
