### ISSUE TITLE
Lambda layers packaging problem

### ISSUE THREAD

**Issue by perzanko** [serverless/serverless#5556]
I've used the new serverless feature Layers in my nodejs project. I encountered packing problem with layer nodemodules.zip

This is what I got in console
```
  Error --------------------------------------------------

  ENOENT: no such file or directory, stat '/Users/perzanko/Workspace/htd/projects/vave-lambda-nodejs/.build/.serverless/nodemodules.zip'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, stat '/Users/perzanko/Workspace/htd/projects/vave-lambda-nodejs/.build/.serverless/nodemodules.zip'
    at Object.statSync (fs.js:829:3)
    at BbPromise.map (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:118:24)
From previous event:
    at AwsDeploy.uploadFunctionsAndLayers (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:117:22)
From previous event:
    at AwsDeploy.uploadArtifacts (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:19:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:113:39)
From previous event:
    at Object.aws:deploy:deploy:uploadArtifacts [as hook] (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:109:10)
    at BbPromise.reduce (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.spawn (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:409:17)
    at AwsDeploy.BbPromise.bind.then (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:95:48)
From previous event:
    at Object.deploy:deploy [as hook] (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:10)
    at BbPromise.reduce (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
From previous event:
    at PluginManager.invoke (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/perzanko/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/bin/serverless:44:28)
```

This is my config:

```
service: ${self:custom.envConfig.service}

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-aws-alerts
  - serverless-plugin-split-stacks
  - serverless-dependson-plugin
  - serverless-prune-plugin

custom:
  envConfig: ${file(./config/${opt:stage}.config.js)}
  splitStacks:
    perFunction: false
    perType: true


provider:
  name: aws
  stage: ${opt:stage}
  region: ${self:custom.envConfig.region}
  runtime: nodejs8.10
  environment:
    ENV: ${opt:stage}
  role: lambdaDefaultRole
  vpc: ${self:custom.envConfig.vpc}


layers:
  nodemodules:
    path: node_modules

functions:
  organizations_getOrganizations:
    handler: src/handlers/organizations/getOrganizations/getOrganizations.default
    alarms:
      - errorAlert
    layers:
      - {Ref: NodemodulesLambdaLayer}
 ...more functions
```

I did a very ugly workaround:
1. `serverless package --stage development`
2. I edited manually layers.artifact path in `serverless-state.json`
from `../.build/.serverless/nodemodules.zip` to `../.serverless/nodemodules.zip`
3. `serverless deploy --stage development --package ./.serveless`

There is any solution for that or it's just a bug?
