### ISSUE TITLE
Function "rod-MyFunctionName" doesn't exist in this Service

### ISSUE THREAD

**Issue by JonasLaux** [serverless/serverless#5557]
# This is a Bug Report

## Description

* What went wrong?

I'm deploying to GCloud Functions. When i do this with `sls deploy`, the deployment runs through, also everything is updated and online, but the whole process ends with an error.
So, my CI is failing all the time, but it actually worked.

* What did you expect should have happened?

Mostly the same, but exiting with a success.

* What was the config you used?

```
service: my-service # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs8
  project: myProject
  credentials: ./key_file.json 
  stage: prod
  region: europe-west1
  environment:
    ....

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  myFunction:
    handler: myFunction    
    events:
      - http: path
  mySecondFunction:
    handler: mySecondFunction
    events:
      - http: path
  myThirdFunction:
    handler: myThirdFunction
    events:
      - http: path
```

* What stacktrace or error message from your provider did you see?

```
Serverless: Done...
 
  Serverless Error ---------------------------------------
 
  Function "rod-myFunction" doesn't exist in this Service
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           11.3.0
     Serverless Version:     1.34.1
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
