### ISSUE TITLE
schedule from file with default value removes space

### ISSUE THREAD

**Issue by q42jaap** [serverless/serverless#5558]
# This is a Bug Report

## Description

* What went wrong?
I ran `serverless deploy --stage custom`. The serverless.yml refers to files like `serverless.prod.config.json` depending on the stage name.
I have a variable schedule, it's running faster on acceptance than on prod.
Because I was using a `custom` stage there is no `serverless.custom.config.json` and all the settings fall back to their default in serverless.yml.

from serverless.yml:
```
  applereceiptstoupdate:
    handler: src/handler.appleFindReceiptsInNeedOfUpdate
    timeout: 10
    events:
      # In the apple sandbox time runs faster, so we need to check the apple receipts faster.
      - schedule: ${file(./serverless.${self:provider.stage}.config.json):AppleReciptsToUpdateSchedule, 
"rate(3 hours)"}
```

The following updatestack.json was produced:
```
    "ApplereceiptstoupdateEventsRuleSchedule1": {
      "Type": "AWS::Events::Rule",
      "Properties": {
        "ScheduleExpression": "rate(3hours)",
        "State": "ENABLED",
        "Targets": [
          {
            "Arn": {
              "Fn::GetAtt": [
                "ApplereceiptstoupdateLambdaFunction",
                "Arn"
              ]
            },
            "Id": "applereceiptstoupdateSchedule"
          }
        ]
      }
    },
```
Note that the space between `3` and `hours` disappeared for the schedule.
This results in an error when pushing the stack to aws.

* What did you expect should have happened?
The space should not have been removed.

* What stacktrace or error message from your provider did you see?
```
  An error occurred: ApplereceiptstoupdateEventsRuleSchedule1 - Parameter ScheduleExpression is not valid. (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: ...).
```
## Additional Data
When deploying from a stage that does have a file with AppleReciptsToUpdateSchedule in it, the `rate(3 hours)` is correctly used...

* ***Serverless Framework Version you're using***: 1.34.1
* ***Operating System***: macOS 10.14.1
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by dschep** [comment]
Confirmed in [dschep-bug-repos/sls-5558](https://github.com/dschep-bug-repos/sls-5558). Seems spaces are stripped from any defaults. That's not good 😢

**Comment by dschep** [comment]
See the workaround branch of that repo for a fix. The change for your service would be:
```yaml
custom:
  defaultAppleReciptsToUpdateSchedule: rate(3 hours)
# stuff....
functions:
  applereceiptstoupdate:
    handler: src/handler.appleFindReceiptsInNeedOfUpdate
    timeout: 10
    events:
      # In the apple sandbox time runs faster, so we need to check the apple receipts faster.
      - schedule: ${file(./serverless.${self:provider.stage}.config.json):AppleReciptsToUpdateSchedule, 
self:custom.defaultAppleReciptsToUpdateSchedule}
```
