### ISSUE TITLE
Support for Application Load Balancers events

### ISSUE THREAD

**Issue by owliveira** [serverless/serverless#5572]
# This is a Feature Proposal

## Description

As announced in Re:Invent, Lambda functions are now able to be set as targets for Application Load Balancer events, which is such like another fashion over setting up an API Gateway that triggers a Lambda.

For more detailed information about the announcement: [AWS Blog](https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/)
Using the feature with AWS CLI: [AWS Docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application//lambda-functions.html)

This feature request is all about:
* Allow to configure ALB events for triggering functions

Example of usage (under events section): 
```
events:
    - alb:
        name: load-balancer-name
        listener: HTTPS:443
        host: www.example.com
        path: /lambda/my-handler-function
```

Similar or dependent issues:

Let me now if you need some more detailed information.

**Comment by alecventura** [comment]
This would be awesome!

**Comment by dschep** [comment]
Would you expect this to create the ALB for you or require an existing ALB?

**Comment by owliveira** [comment]
AWS gives us two ways of using this new feature, the first is by creating an ALB and providing the Lambda's ARN. The second, you can point up an existing ALB in the Lambda configuration page. The second one seems to be more likely to the framework, so, **requiring an existing ALB would make more sense**, I guess.

**Comment by novemberde** [comment]
@owliveira Additionally, host and listener on ALB are able to be an array.
So there're two options.

Here's second example of usage.

```yml
events:
    - alb:
        name: load-balancer-name
        listeners: 
            - HTTPS: 443
              HOST: www.example.com
              PATH: /lambda/my-handler-function
            - HTTPS: 443
              HOST: www.example2.com
              PATH: /*
            - HTTPS: 80
              HOST: www.example.com
              PATH: /lambda/my-handler-function
```
I'm looking forward to applying this feature on my production!
