### ISSUE TITLE
Deploy only functions without layers

### ISSUE THREAD

**Issue by m0d00d** [serverless/serverless#5578]
# This is a Feature Proposal

Executing 
```
serverless deply
````

upload function artefacts and layers at the same time. However, libraries in layers don't change that often. So there should be a way to only update the function code without updating layer code / libs.

# Description

Using for exampe the Java runtime and having libraries that are more than 20MB, updating the libraries of a layer every time `sls deploy` is executed is very time consuming and unnecessary. So it would be good to have a deploy option where the layer is not updated, but only the function code.

**Comment by dschep** [comment]
Alas, I don't think this is possible in a single service because of CloudFormation. If you leave the layer out of the, you wouldn't be able to use a ref to it. I've tested uploading a template which references the previous demployment's copies of the layer contents in s3 in hopes that CFN would realize the layer was the same as what was already created and thus not publish a new one, alas, it still publishes a new version.


One way to handle this is to have your layer & your service using the layer in different serverless projects.

In your service's `serverless.yml`:
```yaml
service: foobar
provider:
  name: aws
  language: python3.6
functions:
  hello:
    handler: handler.hello
    layers:
      - ${cf:foobar-layer-dev.FoobarLayerExport}
```
Then in a separate project managing your layer:
```yaml
service: foobar-layer
provider:
  name: aws
layers:
  foobar:
    path: layer
resources:
  Outputs:
    FoobarLayerExport:
        Value:
          Ref: FoobarLambdaLayer
        Export:
          Name: FoobarLambdaLayer
```
