### ISSUE TITLE
Badly indented sqs event deploying silently without a trigger

### ISSUE THREAD

**Issue by majorgilles** [serverless/serverless#5581]
## Description

* What went wrong?
Using

```
events:
      - sqs:
      arn: ${self:custom.queues.updateVehicle.arn}
      batchSize: 1
      enabled: true
```

no error was thrown upon deploying the related lambda.
on the aws console, I can observe that no trigger has been added to the lambda.

* What did you expect should have happened?
An actual error indicating missing properties in the sqs event: lack of arn or other property at least.
Lambda should not have been deployed

## Additional Data

* ***Serverless Framework Version you're using***: ^1.32.0
* ***Operating System***: osx Mojave
