### ISSUE TITLE
Add layers to all functions in stack

### ISSUE THREAD

**Issue by 0xh0b0** [serverless/serverless#5582]
# This is a Feature Proposal

## Description
Add the same set of layers to all functions in stack.
Today, the layers should be added to each function.
```yaml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10
  layers:
    - arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:layer:xxxxx:mylayer1
    - arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:layer:xxxxx:mylayer2

functions:
  hello1:
    handler: handler.hello1
  hello2:
    handler: handler.hello2
```

**Comment by dschep** [comment]
Interesting proposal. I can see the utility of this. 

For now, use variables to do this:
```yaml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

custom:
  layers:
    - arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:layer:xxxxx:mylayer1
    - arn:aws:lambda:us-east-1:xxxxxxxxxxxxx:layer:xxxxx:mylayer2

functions:
  hello1:
    handler: handler.hello1
    layers: ${self:custom.layers}
  hello2:
    handler: handler.hello2
    layers: ${self:custom.layers}
```
