### ISSUE TITLE
Layer directory not found when overriding service-level exclude property

### ISSUE THREAD

**Issue by spg** [serverless/serverless#5583]
# This is a Bug Report

## Description

* What went wrong?
I get the following error when deploying my stack: `No file matches include / exclude patterns`

Here is my `serverless.yml`:
```yaml
service: my-service

provider:
  name: aws
  runtime: python3.7

package:
  exclude:
  - ./**

layers:
  layerOne:
    path: layerOne
    package:
      include:
      - layerOne
```

`layerOne` is a directory containing a single non-empty file (`my_module.py`).

The only way I found to avoid this problem was to change the layer's `include` property:
```yaml
service: my-service

provider:
  name: aws
  runtime: python3.7

package:
  exclude:
  - ./**

layers:
  layerOne:
    path: layerOne
    package:
      include:
      - "./**"
```

* What did you expect should have happened?
The `layerOne` directory should have been included without having to include all project files (using `"./**"`)
* What was the config you used?
See `serverless.yml` snippet above
* What stacktrace or error message from your provider did you see?
```bash
~/layertesting » sls deploy --verbose
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           9.3.0
     Serverless Version:     1.34.1
```

Similar or dependent issues:
* n/a

## Additional Data

* ***Serverless Framework Version you're using***:
See stacktrace above
* ***Operating System***:
See stacktrace above
* ***Stack Trace***:
See stacktrace above
* ***Provider Error messages***:
See stacktrace above

**Comment by dschep** [comment]
Hmm. I imagine this is caused by the same issue as #5329


however... if your goal is to exclude files outside of the layerOne directory, those are already not included in the layer contents. Also, layer contents are automatically excluded from function's contents.

**Comment by dogzzdogzz** [comment]
My exclude/include in serverless.yml as below worked well before,
```
package:
  exclude:
    - ./**
  individually: true
functions:
  hello:
    package:
      include:
      - hello/**
```
until I added layers, I got " No file matches include / exclude patterns"  error
```
layers:
  foo:
    path: bar
```
