### ISSUE TITLE
How to create complex routes

### ISSUE THREAD

**Issue by mudaser-caremerge** [serverless/serverless#5584]
Hi,

My application requirement is that i have to create a long and complex route using serverless for example

```
GET /users/:user_id/subjects
GET /users/:user_id/subjects/passed
GET /users/:user_id/subjects/:subject_id
```

**Comment by dschep** [comment]
http events support that:
```yaml
functions:
  subjects:
    handler: handlers.subjects
    events:
      - http:
          method: get
          path: /users/{user_id}/subjects
```
