### ISSUE TITLE
Cyclic dependency issues

### ISSUE THREAD

**Issue by aflesner** [serverless/serverless#5586]
# This is a Bug Report

## Description

Hello, I am still seeing errors related to this bug, is it considered fixed?

Here is my serverless.yml

```
service: submitorder

provider:
  name: aws
  runtime: dotnetcore2.1
  stage: dev
  region: us-east-1
  environment:
    S3_ORDER_BUCKET: ${self:service}-${self:provider.stage}-orders
    SQS_ORDER_QUEUE: ${self:service}-${self:provider.stage}-orders-queue


package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  submit:
    handler: CsharpHandlers::SubmitOrderSteps.Handler::Submit
  trigger:
    handler: CsharpHandlers::SubmitOrderSteps.BucketFunction::Handle
    events:
      - s3:
          bucket: orders
          event: s3:ObjectCreated:*

stepFunctions:
  stateMachines:
    submitstepfunc1:
      name: 'submitstepfunc1'
      events:
        - schedule: cron(0/5 * ? * MON-FRI *)
        - schedule: cron(0/5 0-19 ? * SAT *)
        - schedule: cron(0/5 5-23 ? * SUN *)
      definition:
        Comment: "Submit a sales order"
        StartAt: Submit1
        States:
          Submit1:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-submit"
            Catch:
              - ErrorEquals: ["InvalidRequest"]
                Next: InvalidRequestFallback
              - ErrorEquals: ["InternalServer"]
                Next: InternalServerFallback
              - ErrorEquals: ["ServerDown"]
                Next: ServerDownFallback
              - ErrorEquals: ["States.All"]
                Next: CatchAllFallback
            End: true
          InvalidRequestFallback:
            Type: Pass
            Result: "Invalid Request"
            End: true
          InternalServerFallback:
            Type: Pass
            Result: "Internal Server Error"
            End: true
          ServerDownFallback:
            Type: Pass
            Result: "Server Down"
            End: true
          CatchAllFallback:
            Type: Pass
            Result: "Catch All"
            End: true

resources:
  Resources:
    SQSOrderQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.SQS_ORDER_QUEUE}
    S3BucketOrders:
      DependsOn:
        - TriggerLambdaPermissionOrdersS3
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_ORDER_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
```

The error I am getting is
```
An error occurred: S3BucketOrders - Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 1AB4BFD5FB03D02C; S3 Extended Request ID: AoURg6S+hjCrJ5Qvkh9myDE4nTDI02wNdX4kHXMd6h1tK70Eontd8OQbP7bTz88jR7dYTnF1CFw=).
```

Based upon what I was reading on AWS support it says we are supposed to put the DependsOn in the Bucket to avoid the circular dependency. If this is not a bug in serverless could someone help me with the correct code to get this to deploy with serverless?

Similar or dependent issues:
* #3038

## Additional Data

* ***Serverless Framework Version you're using***: 1.34.1
* ***Operating System***: Windows
* ***Stack Trace***:
* ***Provider Error messages***:
```
An error occurred: S3BucketOrders - Unable to validate the following destination configurations (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 1AB4BFD5FB03D02C; S3 Extended Request ID: AoURg6S+hjCrJ5Qvkh9myDE4nTDI02wNdX4kHXMd6h1tK70Eontd8OQbP7bTz88jR7dYTnF1CFw=).
```
