### ISSUE TITLE
http event causing deployment failure - "Resource creation cancelled"

### ISSUE THREAD

**Issue by jacknewcombe-je** [serverless/serverless#5591]
# This is a Bug Report

## Description

* What went wrong?

Serverless failed to deploy after adding an http event definition to a lambda

* What did you expect should have happened?

Successful deployment

* What was the config you used?

```
functions:
  sync:
    handler: src/sync.sync
    description: Updates s3 config file on a schedule
  read:
    handler: src/read.read
    description: Reads config data from s3
    events:
      - http:
          path: read
          method: GET
```

Removing the 'events' section results in a successful deployment

* What stacktrace or error message from your provider did you see?

```
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - je-lunchtime-data-prdev
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ReadLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - LunchBucket
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - ReadLogGroup
CloudFormation - CREATE_FAILED - AWS::S3::Bucket - LunchBucket
CloudFormation - CREATE_FAILED - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - je-lunchtime-data-prdev
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_COMPLETE - AWS::S3::Bucket - LunchBucket
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ReadLogGroup
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - je-lunchtime-data-prdev
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: ReadLogGroup - Resource creation cancelled.
```

^^ ReadLogGroup is not relevant - a different component is reported each time but with the same message: "Resource creation cancelled.". Presumably the real error is swallowed.

Similar or dependent issues:
N/A

## Additional Data

* Serverless 1.34.1 + NodeJS 11.3.0
* MacOS Mojave
