### ISSUE TITLE
Copy self:provider.tags into all resources

### ISSUE THREAD

**Issue by onnimonni** [serverless/serverless#5593]
# This is a Feature Proposal
**TL;DR:** I would like to use provider tags for all created resources

## Description
AFAIK almost companies use tagging for splitting costs into different departments inside the organisation.

For example if I use `InvoiceID` like this
```yaml
service:
  name: lambda-service-name

provider:
  name: aws
  stage: ${env:ENVIRONMENT, 'development'}
  tags:
    InvoiceID: 1234567

resources:
  Resources:
    S3Reports:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: your-bucket-name-here
```
If I create functions with this configuration they will correctly get the `InvoiceID` tag.
But the `S3::Bucket` included here won't and I need to duplicate this tag into each resources.

It's weird that serverless still adds the `STAGE` tag but not the others:
<img width="390" alt="screen shot 2018-12-13 at 1 51 14 pm" src="https://user-images.githubusercontent.com/5691777/49937034-37f81480-fede-11e8-8896-8a24e1b893de.png">

Could we add all tags into all resources? Or a helper function which I could use to add all tags easily into all resources?
