### ISSUE TITLE
[Layers] Template format error: Unresolved resource dependencies [node-modules-global-api] in the Resources block of the template

### ISSUE THREAD

**Issue by MaxVinogradov** [serverless/serverless#5596]
I have lambdas config in the separate file:
```
# Layers
layers:
  node-modules-global-api:
    path: node_modules
    description: node-modules for api-global

functions: ${file(./serverlessFunctions.yml)}
```

Part of lambda config: 
```
authenticate:
  handler: functions/authenticate/index.handler
  name: ${self:custom.prefix}-authenticate
  tracing: true
  layers:
  - {Ref: node-modules-global-api}
  events:
    - http:
        path: authenticate
        method: post
        cors: true
  tags:
    type: authenticate
    target: user
    http: post
```
What can be wrong?
