### ISSUE TITLE
Included files not packaged

### ISSUE THREAD

**Issue by raym0nd93** [serverless/serverless#5609]
# This is a Bug Report

## Description

* What went wrong?

When deploying serverless functions(packaged individually), included files are ignored(except for package.json, package-lock.json and node_modules). 

* What did you expect should have happened?

The files stated under `include:` should be included. This does work in version 1.34.1

* What was the config you used?
```
package:
  individually: true
  include:
    - ../_helpers/logging.js
    - node_modules/**
    - package.json
    - package-lock.json
  exclude:
    - '*/**'
```

* What stacktrace or error message from your provider did you see?

No error message is provided, but the files are ignored

Similar or dependent issues:
* #5608

## Additional Data

* ***Serverless Framework Version you're using***:
1.35.0
* ***Operating System***:
Ubunut 18.04.1
* ***Stack Trace***:
* ***Provider Error messages***:
