### ISSUE TITLE
Glue crawler unsupported property: DynamodbTargets

### ISSUE THREAD

**Issue by jorenvh1** [serverless/serverless#5611]
# This is a Bug Report

## Description
I'm trying to add a glue crawler with a dynamodb table as a target to my serverless.yml but when deploying I get the following error:
`An error occurred: signaturesGlueCrawler - Property validation failure: [Encountered unsupported properties in {/Targets}: [DynamoDBTargets]].`

Used config:
```signaturesGlueCrawler:
      Type: AWS::Glue::Crawler
      Properties:
        Name: ${self:custom.prefix}-signatures-glue-crawler
        Role:
          Ref: signaturesGlueRoleCrawler
        DatabaseName: ${self:custom.prefix}-glue-db
        Schedule:
          ScheduleExpression: cron(0 3 * * ? *) 
        Targets:
          DynamoDBTargets:
            - Path: ${self:custom.dynamodb_tables.signatures}
```

The documentation of cloudformation does not state that DynamoDBTargets is a valid option: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-targets.html

But when I look at the web api, it does have the option: https://docs.aws.amazon.com/glue/latest/webapi/API_CrawlerTargets.html

Also, creating the crawler manually through the aws console gives you the option to crawl from a dynamodb table.

## Additional Data

* ***Serverless Framework Version you're using***: 1.35.0
* ***Operating System***: macOS Mojave 10.14.2

**Comment by jorenvh1** [comment]
Apparently this option is not yet supported for cloudformation, it is for the web api and console

**Comment by jprivillaso** [comment]
Does anyone know if this feature is going to be added to cloudformation ?

**Comment by farfaro** [comment]
I have the same problem with MongoDb Connection

```
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      DatabaseName: myDB
      Name: myCrawler
      Role: someRole
      SchemaChangePolicy: 
        DeleteBehavior: DEPRECATE_IN_DATABASE
        UpdateBehavior: UPDATE_IN_DATABASE
      Targets:
        MongoDBTargets:
        - ConnectionName: myConnection
          Path: my/path
          ScanAll: true
```

ERROR in console:
_Property validation failure: [Encountered unsupported properties in {/Targets}: [MongoDBTargets]]_
