### ISSUE TITLE
Ensure AWS S3 buckets created by Serverless can't be accessed over HTTP

### ISSUE THREAD

**Issue by a-h** [serverless/serverless#5621]
# This is a Feature Proposal

## Description

At a recent security audit I had done on some infrastructure, several of the S3 buckets created by the Serverless Framework showed up as not having `SecureTransport` flag set to true as part of the Bucket Policy.

While the buckets aren't created public, it's also (maybe?) a relatively simple change to enforce the policy.

The security team provided an example policy to apply to each newly created (or existing) bucket:

```json
{
    "Statement":[
        {
            "Action": "s3:*",
            "Effect":"Deny",
            "Principal": "*",
            "Resource":"arn:aws:s3:::<bucketname>/*",
            "Condition":{
                "Bool":
                { "aws:SecureTransport": false }
            }
        }
    ]
}
```

Similar or dependent issues:
* None

**Comment by dschep** [comment]
That's a good idea @a-h!

**Comment by mushketyk** [comment]
I would like to work on this feature if nobody minds.

**Comment by neverendingqs** [comment]
You can work around this for now by adding the bucket policy yourself:

```yaml
resources:
  Resources:
    ...
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: ServerlessDeploymentBucket
      PolicyDocument:
        Statement:
          - Action: 's3:*'
            Effect: Deny
            Principal: '*'
            Resource:
              - 'Fn::Join':
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: ServerlessDeploymentBucket
                    - /*
            Condition:
              Bool:
                'aws:SecureTransport': false
```
