### ISSUE TITLE
Cloudwatch event source not being created

### ISSUE THREAD

**Issue by aroca** [serverless/serverless#5629]
# This is a Bug Report

## Description

* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Hey guys, I am not able to create events here.
I am using

sls --version
1.33.1
I see no errors and nothing gets created. I just tested with the same test as in this doc..
```
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  environment:
    NODE_ENV: ${self:custom.stage}
    DEBUG: "*"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:*
      Resource:
        - "*"

plugins:
  - serverless-offline

custom:
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  serverless-offline:
    port: 4010

functions:
  GetTest:
    handler: src/test.get
    events:
      - cloudwatchEvent:
        event:
          source:
            - "aws.ec2"
          detail-type:
            - "EC2 Instance State-change Notification"
          detail:
             state:
               - pending
```
The scheduled events are created correctly.

Thanks

Similar or dependent issues:
* #12345

## Additional Data

* ***sls --version
1.33.1***:
* ***Operating System: MacOS Sierra***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by dschep** [comment]
The event specification isn't indented correctly. Use:
```yaml
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  environment:
    NODE_ENV: ${self:custom.stage}
    DEBUG: "*"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:*
      Resource:
        - "*"

plugins:
  - serverless-offline

custom:
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  serverless-offline:
    port: 4010

functions:
  GetTest:
    handler: src/test.get
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
               state:
                 - pending
```
