### ISSUE TITLE
AWS Cognito + Serverless Framework

### ISSUE THREAD

**Issue by livertonoliveira** [serverless/serverless#5633]
Guys, 

I'd like to use AWS Cognito to handle social authentication on my app that is going to use serverless framework and I can't understand how to do this.

Does anybody have a tutorial to help me with? I'd be so grateful!

**Comment by cyberfox1** [comment]
https://aws-amplify.github.io/docs/js/start

**Comment by smartinspereira** [comment]
just create a cognito userpool and set the arn as authorizer on all http events, in your serverless lambda config, that need authentication.
every request, to a function using this  authorizer, now has to have an `Authorization` header field containing a token, [read this for further information on how to obtain such a token.](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html)

```
foobar
  handler: src/foobar.handler
    events:
      - http:
           method: get
           path: /foo/bar
           authorizer: arn:aws:cognito-idp:REGION:ACCOUNT_ID:userpool/USER_POOL_ID
```
