### ISSUE TITLE
Unable to import module 'index': Error

### ISSUE THREAD

**Issue by AdamZaczek** [serverless/serverless#5643]
# This is a Bug Report

## Description

* What went wrong?
My function does not work after running ```sls deploy``` but works perfectly in offline mode.
* What did you expect should have happened?
I expect my function to work when being deployed.
* What was the config you used?
Deps
```json
{
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@babel/register": "^7.0.0",
    "@babel/runtime": "^7.2.0",
    "axios": "^0.18.0",
    "babel-cli": "^6.26.0",
    "babel-loader": "^8.0.4",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "chai": "^4.1.2",
    "graphql-playground-middleware-express": "^1.7.8",
    "mocha": "^5.2.0",
    "morgan": "^1.9.1",
    "serverless-offline": "^3.31.3",
    "webpack": "^4.28.2",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "apollo-server": "^2.3.1",
    "apollo-server-express": "^2.3.1",
    "apollo-server-lambda": "^2.3.1",
    "bcryptjs": "^2.4.3",
    "cors": "^2.8.4",
    "dataloader": "^1.4.0",
    "dotenv": "^6.2.0",
    "express": "^4.16.4",
    "graphql": "^14.0.2",
    "graphql-resolvers": "^0.2.2",
    "jsonwebtoken": "^8.3.0",
    "mongoose": "^5.4.0",
    "serverless": "^1.35.1",
    "serverless-http": "^1.8.0",
    "serverless-webpack": "^5.2.0"
  }
```
Serverless.yml
```yml
service: abc
tenant: adamzaczek
app: abc
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules:
      forceExclude:
        - graphql-playground-middleware-express
        - morgan
        - "@babel/runtime"
    webpackConfig: ./webpack.config.js

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  credentials:
    accessKeyId: totallyMyRealAccessKey
    secretAccessKey: notASecretAnymore
  region: us-east-1
functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get
```

webpack.config.js
```js
const path = require("path");
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");
module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    minimize: false
  },
  performance: {
    hints: false
  },
  devtool: "nosources-source-map",
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "babel-loader"
          }
        ]
      }
    ]
  },
  output: {
    libraryTarget: "commonjs2",
    path: path.join(__dirname, ".webpack"),
    filename: "[name].js",
    sourceMapFilename: "[file].map"
  }
};
```

OS: darwin
Node Version: 8.10.0
Serverless Version: 1.35.1

* What stacktrace or error message from your provider did you see?
Logs from cloudwatch:
```
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/index.js:122:18)
at __webpack_require__ (/var/task/index.js:21:30)
at Module.<anonymous> (/var/task/index.js:220:21)
at __webpack_require__ (/var/task/index.js:21:30)
at /var/task/index.js:85:18
at Object.<anonymous> (/var/task/index.js:88:10)
```
Similar or dependent issues:
* https://github.com/serverless/serverless/issues/4493

## Additional Data

* ***Serverless Framework Version you're using***:
1.35.1
* ***Operating System***:
darwin
* ***Stack Trace***:
```
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/index.js:122:18)
at __webpack_require__ (/var/task/index.js:21:30)
at Module.<anonymous> (/var/task/index.js:220:21)
at __webpack_require__ (/var/task/index.js:21:30)
at /var/task/index.js:85:18
at Object.<anonymous> (/var/task/index.js:88:10)
```
* ***Provider Error messages***:
Unable to import module 'index': Error

I've spent a lot of time trying to fix this issue but I had no success in doing so yet :/ Sls offline works perfectly and zip file looks ok. It creates ```index.js``` ```index.js.map``` ```package.json``` and ```node_modules```.
This is my first time using serverless but I did my best not to miss on any steps necessary for the deploy to work.  Do you know what might be the issue?
