### ISSUE TITLE
Artifact path in serverless-state.json is incorrect

### ISSUE THREAD

**Issue by warapitiya** [serverless/serverless#5645]
# This is a Bug Report

## Description

* What went wrong?
File `artifact/serverless-state.json` created by command `sls package -p artifact -s ci` is containing a wrong artifact path. (folder name should be `artifact` instead of `.serverless`)
```json
{
  "package": {
    "artifact": "/Users/mt/dev/project/.serverless/createFunction.zip"
  }
}
```
* What did you expect should have happened?
Artifact path should contains `artifact` instead of `.serverless`.
```json
{
  "package": {
    "artifact": "/Users/mt/dev/project/artifact/createFunction.zip"
  }
}
```
* What was the config you used?
```yml
service: projectName
provider:
  mockProperty: value 
package:
  individually: true
  exclude:
    - src/*
    - package.json
    - README.md
functions:
  createFunction:
    handler: src/create.handler
    name: value
    package:
      include:
        - src/create.js
    events:
      mockProperty: value 
    
  getFunction:
    handler: src/get.handler
    mockProperty: value 
    package:
      include:
        - src/get.js
    events:
      - http:
          mockProperty: value
```
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #4188

## Additional Data

* ***Serverless Framework Version you're using***:
1.35.0
* ***Operating System***:
MacOs 10.14.1 (18B75)
* ***Stack Trace***:
```txt

Serverless Error ---------------------------------------
--
02-Jan-2019 09:26:11 |  
02-Jan-2019 09:26:11 | No createFunction.zip file found in the package path you provided.
02-Jan-2019 09:26:11 |  
02-Jan-2019 09:26:11 | Stack Trace --------------------------------------------
02-Jan-2019 09:26:11 |  
02-Jan-2019 09:26:11 | ServerlessError: No createFunction.zip file found in the package path you provided.
02-Jan-2019 09:26:11 | at serverless.service.getAllFunctions.forEach.functionName (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/extendedValidate.js:70:17)
02-Jan-2019 09:26:11 | at Array.forEach (<anonymous>)
02-Jan-2019 09:26:11 | at AwsDeploy.extendedValidate (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/extendedValidate.js:58:49)
02-Jan-2019 09:26:11 | From previous event:
02-Jan-2019 09:26:11 | at AwsDeploy.BbPromise.bind.then.then.then (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:86:14)
02-Jan-2019 09:26:11 | From previous event:
02-Jan-2019 09:26:11 | at Object.before:deploy:deploy [as hook] (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:80:10)
02-Jan-2019 09:26:11 | at BbPromise.reduce (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/classes/PluginManager.js:391:55)
02-Jan-2019 09:26:11 | From previous event:
02-Jan-2019 09:26:11 | at PluginManager.invoke (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
02-Jan-2019 09:26:11 | at PluginManager.run (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
02-Jan-2019 09:26:11 | at variables.populateService.then.then (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/Serverless.js:157:33)
02-Jan-2019 09:26:11 | at runCallback (timers.js:810:20)
02-Jan-2019 09:26:11 | at tryOnImmediate (timers.js:768:5)
02-Jan-2019 09:26:11 | at processImmediate [as _immediateCallback] (timers.js:745:5)
02-Jan-2019 09:26:11 | From previous event:
02-Jan-2019 09:26:11 | at Serverless.run (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/lib/Serverless.js:144:8)
02-Jan-2019 09:26:11 | at serverless.init.then (/home/ec2-user/.asdf/installs/nodejs/8.11.3/.npm/lib/node_modules/serverless/bin/serverless:44:28)
02-Jan-2019 09:26:11 | at <anonymous>
02-Jan-2019 09:26:11 |  
02-Jan-2019 09:26:11 | Get Support --------------------------------------------
02-Jan-2019 09:26:11 | Docs:          docs.serverless.com
02-Jan-2019 09:26:11 | Bugs:          github.com/serverless/serverless/issues
02-Jan-2019 09:26:11 | Issues:        forum.serverless.com
02-Jan-2019 09:26:11 |  
02-Jan-2019 09:26:11 | Your Environment Information -----------------------------
02-Jan-2019 09:26:11 | OS:                     linux
02-Jan-2019 09:26:11 | Node Version:           8.11.3
02-Jan-2019 09:26:11 | Serverless Version:     1.35.0
02-Jan-2019 09:26:11 |  


```
* ***Provider Error messages***:

**Comment by ahmed-abdulmoniem** [comment]
This is happening with me as well.

**Comment by dschep** [comment]
I see you link to #4188. As such, does #5297 fix your issue? `npm i -g fruffin/serverless#fix-4188`

**Comment by james-bjss** [comment]
I am still suffering from this in 1.66.

If I specify a package directory when building then the artifact paths in `serverless-state.json ` incorrectly include the `/.serverless` directory in the artifact path

In addition to the above the paths appear to be absolute. This causes an issue for us as the build location may differ between our packaging and deployment agents.

Are the paths supposed to be absolute?

I have the following specified in my ` serverless.yml`

```
package:
  individually: true
  exclude:
    - functions/**
    - node_modules/**
    - static/**
    - ./*

functions:
  otp:
    handler: functions/otp/handler.otp
    package:
      include:
        - functions/otp/** 
```

If if I package this with the command `serverless package --package testpackage`

This results in the following entry in serverless.yml:
```  "functions": {
      "otp": {
        "handler": "functions/otp/handler.otp",
        "package": {
          "include": [
            "functions/otp/**"
          ],
          "artifact": "/home/vsts/work/1/s/.serverless/otp.zip"
        },`
