### ISSUE TITLE
Add support for BatchParameters in Cloudwatch event rule

### ISSUE THREAD

**Issue by brettcooper** [serverless/serverless#5648]
# Support the use of BatchParameters within Target for an AWS CloudWatch Event Rule

## Description

* I am trying to create a CloudWatch rule to schedule an AWS Batch event to trigger, but Serverless currently doesn't support the "BatchParameters" section of the rule. I am receiving the following error:
```
Serverless: Operation failed!
 
  Serverless Error ---------------------------------------
 
  An error occurred: TaskSchedule - Encountered unsupported property BatchParameters.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           10.14.1
     Serverless Version:     1.35.1
```
* Here is the Serverless YAML:
```
    TaskSchedule:
      Type: AWS::Events::Rule
      Properties:
        Description: "Exports RFM data from DynamoDB to S3."
        Name: ${self:custom.stage}-rfm-ipaas-export-to-s3
        ScheduleExpression: cron(0 0 * * ? *)
        State: "ENABLED"
        Targets:
        - Id: "RFMExportToS3Target"
          Arn: arn:aws:batch:${self:provider.region}:${env:AWS_ACCOUNT_ID}:job-queue/queue1
          RoleArn: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/ecsEventsRole
          BatchParameters:
            JobName: rfm-exporter-ipaas-1
            JobDefinition: arn:aws:batch:${self:provider.region}:${env:AWS_ACCOUNT_ID}:job-definition/${self:service}:latest
```
See the "Sends a batch job command to an AWS Batch job queue" section of the PutTargets API reference:
https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutTargets.html#API_PutTargets_Examples

Similar or dependent issues:
* #713, #1450
