### ISSUE TITLE
If stage name is a variable then you can not create an http binding

### ISSUE THREAD

**Issue by efimk-lu** [serverless/serverless#5655]
# This is a Bug Report

## Description

* What went wrong?
I deployed my sls stack and got the following error:
`Serverless plugin "/lib/plugins/aws/provider/awsProvider.js" initialization errored: Invalid stage name ${self:custom.env}: it should contains only [a-zA-Z0-9] for AWS provider if http event are present since API Gateway stage name cannot contains hyphens.`
* What did you expect should have happened?
A successful deploy
* What was the config you used?
```
provider:
  name: aws
  stage: ${self:custom.env}
...
functions:
  get_transactions:
    events:
      - http:
        ...
```
when ${self:custom.env} resolves to dev
* What stacktrace or error message from your provider did you see?
`lib/plugins/aws/provider/awsProvider.js" initialization errored: Invalid stage name ${self:custom.env}: it should contains only [a-zA-Z0-9] for AWS provider if http event are present since API Gateway stage name cannot contains hyphens.`
Similar or dependent issues:
* #3528

## Additional Data

* ***Serverless Framework Version you're using***:
1.35.1
* ***Operating System***:
osx
* ***Stack Trace***:
NA
* ***Provider Error messages***:
lib/plugins/aws/provider/awsProvider.js" initialization errored: Invalid stage name ${self:custom.env}: it should contains only [a-zA-Z0-9] for AWS provider if http event are present since API Gateway stage name cannot contains hyphens.`

**Comment by dschep** [comment]
Hmm. That's odd. I'm not able to reproduce this issue. Could you share a full `serverless.yml` that causes the issue for me to try?

Here's the `serverless.yml` I used:
```yaml
service: sls-5655 # NOTE: update this with your service name
custom:
  stage: custom-stage
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
functions:
  hello:
    handler: handler.hello
```

And here's the output when I run `sls deploy`:
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (387 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
................
Serverless: Stack update finished...
Service Information
service: sls-5655
stage: custom-stage
region: us-east-1
stack: sls-5655-custom-stage
api keys:
  None
endpoints:
  None
functions:
  hello: sls-5655-custom-stage-hello
layers:
  None
```

and here's the output of `sls print`
```yaml
service: sls-5655
custom:
  stage: custom-stage
provider:
  stage: custom-stage
  name: aws
  runtime: nodejs8.10
functions:
  hello:
    handler: handler.hello
```
