### ISSUE TITLE
Deploy Lambda without service

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#5660]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I just want to deploy a lambda with serverless without a service prefixing the name. Ideally the stage will be suffixed to the lambda name, not the service name. E.g.

foo-dev-bar

would just be:

bar-dev

* If there is additional config how would it look

No

Similar or dependent issues:
N/A

**Comment by dschep** [comment]
Do you mean thename of the lambda? just use the name option then:

```yaml
service: test
functions:
  hello:
    handler: handler.hello
    name: hello
```

This will name the lambda `hello` instead of `test-dev-hello`
