### ISSUE TITLE
Lambda schedule not updating

### ISSUE THREAD

**Issue by ian-vitaexmachina** [serverless/serverless#5668]
Hello,

When I create a lambda function, and set a schedule (e.g. 2 hours) - I cannot have this schedule update even if I do a full deploy, forced function deploy etc.

So if I have this on creation:

```
ingestAirportSchedule:
    handler: functions/ingestAirportSchedule.ingestAirportSchedule
    timeout: 30
    events:
      - schedule: rate(12 hours)
      - http: 'GET /ingest'
```

I get a lambda function that executes every 12 hours OK.

But when I update to this:

```
ingestAirportSchedule:
    handler: functions/ingestAirportSchedule.ingestAirportSchedule
    timeout: 30
    events:
      - schedule: rate(3 hours)
      - http: 'GET /ingest'
```
The schedule just stays at 12 hours.

Thanks!
Ian.
