### ISSUE TITLE
Unable to reference a DynamoDB Stream ARN

### ISSUE THREAD

**Issue by ctindel** [serverless/serverless#5671]
According to the docs we're able to get the arn attribute of a dynamodb stream as long as the dynamodb table itself is created out of serverless, but it doesn't seem to be working for me.

Maybe I'm just missing something? Here's my config:

```
resources:
  Resources:
    FileDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: file
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  compute:
    handler: handler.pushStream
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - FileDynamoDbTable
              - StreamArn
          batchSize: 1
          startingPosition: TRIM_HORIZON
```

And here's the resulting error:

The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource file.

I know I can hardcode the ARN but i'd like to avoid that for obvious reasons.
