### ISSUE TITLE
'sls print' contains Warnings.

### ISSUE THREAD

**Issue by shouki-s** [serverless/serverless#5676]
# This is a Bug Report

## Description

* What went wrong?

It came to occur since 1.36.0.
Output of `sls print` contains Warnings.

The reproduction code is as follows.

My serverless.yml:
```yaml
service: servicename

provider:
  name: aws
  runtime: nodejs8.10

functions:
  function1:
    handler: lib/proxy.handler
  function2:
    handler: lib/proxy.handler
```

Yes, We have multiple functions having same handler.
The difference between the two functions is environment variables and so on.

shell script:
```bash
sls print
```

stdout:
```
Serverless: Warning: A handler "lib/proxy.handler" is duplicated in functions: function1, function2.
service: servicename
provider:
  name: aws
  runtime: nodejs8.10
functions:
  function1:
    handler: lib/proxy.handler
  function2:
    handler: lib/proxy.handler
```

* What did you expect should have happened?

`sls print` should output valid yaml.
Warnings should be written to stderr. Otherwise, `sls print` should not output warnings.

* What was the config you used?

As mentioned above.

* What stacktrace or error message from your provider did you see?

Similar or dependent issues:

Add warning for multiple functions having same handler: https://github.com/serverless/serverless/issues/4414 https://github.com/serverless/serverless/pull/5638

// I think that this warning itself is useful.

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.0
* ***Operating System***: darwin
* ***Stack Trace***:
* ***Provider Error messages***:
