### ISSUE TITLE
Config Plugins

### ISSUE THREAD

**Issue by aronim** [serverless/serverless#5679]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

I wrote the [serverless-plugin-parent](https://github.com/aronim/serverless-plugin-parent) plugin to try and pull common configuration into a central place, with the intention of reducing the amount of configuration needed in large multi-service projects. I basically merged the parent serverless.yml with services serverless.yml in the Plugin's constructor. Unfortunately this does come in a bit late during the initialisation process, and is rather unreliable. Would it be possible to create a special kind Plugin, ie. Configuration Plugin. That could be loaded prior to the Core Plugins, without any hooks or commands, whose sole purpose is to edit the Service Model.

* If there is additional config how would it look
```
service: Service1

config-plugins:
  - serverless-plugin-parent

```

Similar or dependent issues:
*

**Comment by exoego** [comment]
Serverless framework offers a [`${file}` variable to load a configuration from external file](https://serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-in-other-files).
I think it support your use-case: common configuration in a centeral place.
What is your pain point that `${file}` can not address?

**Comment by aronim** [comment]
Hi Exoego,

I have a large set of micro-services, large enough that I hit the 200 resource per stack limit of CloudFormation, so I have to split them over 12 stacks/services. I would still however like to keep everything behind a single API Gateway. This means that I have created an API Gateway separate from my individual Serverless services. What I have done is move the provider.apiGateway configuration out into a "parent" serverless.yml using the serverless-plugin-parent plugin. 

### Common Configuration
./serverless.yml
```yaml
provider:
  name: aws
  stage: ${opt:stage, "Test"}
  runtime: python3.6
  role: DefaultRole
  deploymentBucket: aronim-serverless
  vpc:
    securityGroupIds:
      - { "Fn::GetAtt": [ SecurityGroup, GroupId ] }
    subnetIds:
      - { "Fn::ImportValue": "Aronim-${self:provider.stage}-SubnetAId" }
      - { "Fn::ImportValue": "Aronim-${self:provider.stage}-SubnetBId" }
      - { "Fn::ImportValue": "Aronim-${self:provider.stage}-SubnetCId" }
  apiGateway:
    restApiId: { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiId" }
    restApiRootResourceId: { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiRootResourceId" }
    restApiResources:
      "/shipments":                                               { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiShipmentsResourceId" }
      "/shipments/{shipmentId}":                                  { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiShipmentResourceId" }
      "/shipments/{shipmentId}/orders":                           { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiOrdersResourceId" }
      "/shipments/{shipmentId}/orders/{orderId}":                 { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiOrderResourceId" }
      "/shipments/{shipmentId}/orders/{orderId}/items":           { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiOrderItemsResourceId" }
      "/shipments/{shipmentId}/orders/{orderId}/items/{itemId}":  { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiOrderItemResourceId" }
      "/shipments/{shipmentId}/invoice":                          { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiInvoiceResourceId" }
      "/shipments/{shipmentId}/invoice/{viewportId}":             { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiViewportResourceId" }
      "/shipments/{shipmentId}/invoice/{viewportId}/regions":     { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiViewportRegionsResourceId" }
      "/processes":                                               { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiProcessesResourceId" }
      "/tasks":                                                   { "Fn::ImportValue": "Aronim-${self:provider.stage}-RestApiTasksResourceId" }
  environment:
    STAGE: ${self:provider.stage}
    ELASTICACHE_CLUSTER_ENDPOINT_ADDRESS: { "Fn::ImportValue": "Aronim-${self:provider.stage}-ElasticacheClusterEndpointAddress" }
    ELASTICACHE_CLUSTER_ENDPOINT_PORT: { "Fn::ImportValue": "Aronim-${self:provider.stage}-ElasticacheClusterEndpointPort" }

plugins:
  - serverless-python-requirements
```

### Individual Service Configuration - Current
./service1/serverless.yml
```yaml
provider:      
  name: aws    

plugins:
  - serverless-plugin-parent
  - serverless-python-requirements
```

### Individual Service Configuration - with proposed change
./service1/serverless.yml
```yaml
plugins:
  - serverless-plugin-parent
```

Can you please show me how you can achieve this brevity using ${file(..)}?

Kind regards,
Kevin
