### ISSUE TITLE
Invalid stage name ${opt:stage, 'dev'}

### ISSUE THREAD

**Issue by dallashuggins** [serverless/serverless#5684]
# This is a Bug Report

## I just downloaded the new version of the serverless app (v1.36.0) per the suggestion of npm. When I used `sls deploy` I received an error telling me my stage name is invalid, which I had not received until now. 

* What went wrong?

I updated to version `1.36.0` from `1.35.1` and tried to deploy and got an error saying I have an invalid stage name. The following is from my `serverless.yml` file. I am setting the stage name just as is specified in [this resource](https://serverless.com/framework/docs/providers/aws/guide/variables/), and it was working up until I installed the new version.  

* What did you expect should have happened?
The deploy should have been successful. 

* What was the config you used?
```
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
```

* What stacktrace or error message from your provider did you see?
`Serverless plugin "/Users/dally/.nvm/versions/node/v10.4.1/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js" initialization errored: Invalid stage name ${opt:stage, 'dev'}: it should contains only [a-zA-Z0-9] for AWS provider if http event are present since API Gateway stage name cannot contains hyphens.`

Similar or dependent issues:
* #4396 (unlike this issue, updating the package was the issue)

**Comment by dallashuggins** [comment]
After reading through #4396, I tried `sls deploy --stage dev` and I was able to successfully deploy and the stage name did come through correctly. Close this if you'd like, though I thought you may want to know that the basic `sls deploy` doesn't work any longer.

**Comment by efimk-lu** [comment]
See https://github.com/serverless/serverless/pull/5658

**Comment by dschep** [comment]
Agreed with @rictorres, it's still a bug. But, I can't reproduce it 😖 

```
[:sls-5684] $ grep -v -e '^$' -e '^ *#' serverless.yml
service: sls-5684 # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
functions:
  hello:
    handler: handler.hello
[:sls-5684] $ sls --version && sls deploy
1.36.0
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (387 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Stack update finished...
Service Information
service: sls-5684
stage: dev
region: us-east-1
stack: sls-5684-dev
api keys:
  None
endpoints:
  None
functions:
  hello: sls-5684-dev-hello
layers:
  None
```
