### ISSUE TITLE
The specified bucket does not exist: Should tell me the bucket name

### ISSUE THREAD

**Issue by jdufresne** [serverless/serverless#5699]
# This is a Bug Report

## Description

* What went wrong?

```
  Serverless Error ---------------------------------------
 
  The specified bucket does not exist
```

* What did you expect should have happened?

I expect the error message to tell me what "specified bucket" is so that I can further debug the issue. I never explicitly specified a bucket, so I'm not sure what I should be looking for. I think that would make the error more useful.

* What was the config you used?

```yml
service: my-service

provider:
  name: aws
  runtime: python3.6
  timeout: ${env:LAMBDA_TIMEOUT}

functions:
  erezlife:
    handler: serverless.handler
    events:
      - sqs: ${env:SQS_QUEUE_ARN}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy: []
```

* What stacktrace or error message from your provider did you see?

```
Serverless: Generated requirements from /home/jon/devel/erezlife/requirements.txt in /home/jon/devel/erezlife/.serverless/requirements.txt...
Serverless: Installing requirements from /home/jon/devel/erezlife/.serverless/requirements/requirements.txt ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
 
  Serverless Error ---------------------------------------
 
  The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.12.0
     Serverless Version:     1.35.1
```

Similar or dependent issues:
N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.35.1
* ***Operating System***: Fedora Linux 27
* ***Stack Trace***: N/A
* ***Provider Error messages***: See above
