### ISSUE TITLE
individually packaged lambdas cant be invoked locally, module importation breaks

### ISSUE THREAD

**Issue by ibabicuy** [serverless/serverless#5711]
```
package:
  individually: True

provider:
  name: aws
  profile: meitre
  runtime: python3.6
  region: 'us-east-1'

functions:
  check-pax-availability:
    module: check_availability
    handler: check_availability.run
    layers:
      - ${cf:${self:custom.layerService}.OrtoolsLayer}
  check-pax-availability-intervals:
    module: check_availability_SAT_rotation_interval
    handler: check_availability_SAT_rotation_interval.run
    warmup:
      enabled: true
      concurrency: 50
    memorySize: 1024
    layers:
      - ${cf:${self:custom.layerService}.OrtoolsLayer}
  check-available-times:
    module: check_available_times
    handler: check_available_times.run
    warmup:
      enabled: true
      concurrency: 20
    memorySize: 1024
    layers:
      - ${cf:${self:custom.layerService}.Boto3Layer}
  auto-assign-tables:
    module: auto_assign_tables
    handler: auto_assign_tables.run
    layers:
      - ${cf:${self:custom.layerService}.Boto3Layer}
      - ${cf:${self:custom.layerService}.OrtoolsLayer}
  layout-generation-unique-product:
    module: layouts_generation_utils
    handler: layouts_generation_utils.run
  lambda-metrics-processor:
    module: lambda_metrics_processor
    handler: lambda_metrics_processor.run
    memorySize: 1024
    timeout: 30
    layers:
      - ${cf:${self:custom.layerService}.Boto3Layer}
```

which works on the lambdas, but when called with
`serverless invoke local`

it raises the following error:
```AttributeError: module 'lambda_metrics_processor' has no attribute 'run'```
