### ISSUE TITLE
Serverless exits after entering MFA code

### ISSUE THREAD

**Issue by ProTip** [serverless/serverless#5713]
# This is a Bug Report

## Description
The upgrade to `1.36.1` from `1.35.1` appears to have broken my deploys. After entering my MFA code serverless exits 0 with no further output, not even with `SLS_DEBUG=*`.

* What went wrong?
Serverless exits after assume the AWS role
* What did you expect should have happened?
Continue to deployment
* What was the config you used?
```yaml
service: myservice # NOTE: update this with your service name

# Add the serverless-webpack plugin
plugins:
  - serverless-s3-sync

custom:
  stage: ${opt:stage, self:provider.stage}
  tf_workspace: spark-${self:custom.stage}
  s3Sync:
  - bucketName: spark-site-${self:custom.stage}.foo.com
    localDir: ./dist
    params:
    - index.html:
        CacheControl: no-cache

provider:
  name: aws
  region: us-west-2
  runtime: nodejs8.10
  stage: stage
  profile: myprofile
```
* What stacktrace or error message from your provider did you see?
Debug logging outputs the assume role, then nothing else.

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.1
* ***Operating System***: macOS 10.13.4
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
