### ISSUE TITLE
exclude devDependencies not working after 1.35.0 on windows, node v8.11.3, npm 5.6.0

### ISSUE THREAD

**Issue by mikehanney** [serverless/serverless#5745]
# exclude devDependencies not working after 1.35.0 on windows, node v8.11.3, npm 5.6.0

## Description

Exclude devDependencies does not work in any release after 1.35.0 on windows 10 with node v8.11.3, npm 5.6.0.

I have dozens of projects, all produce small .zips using 1.34.1 , all produce huge .zips using  1.35.0 through 1.36.0.

1.33.2 - working
1.34.0 - working
1.34.1 - working
1.35.0 through 1.36.0 not working 

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/4830

**Comment by pmuens** [comment]
Thanks for opening @mikehanney 👍

Could be related to https://github.com/serverless/serverless/pull/5574

**Comment by dschep** [comment]
Might be a duplicate of #5609

**Comment by exoego** [comment]
@mikehanney 
To reproduce issue, could you provide the config file facing this issue?

**Comment by ImreC** [comment]
@exoego 
Size at 1.34 = 26.25 mb, size at 1.36 = 44.23 mb
package.json 
```
{
  "name": "frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "deploy": "nuxt build && sls deploy",
    "build": "nuxt build",
    "start": "cross-env LOCAL=true node index.js",
    "dev": "nuxt",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.18.0",
    "express": "^4.16.4",
    "nuxt": "^2.4.2",
    "nuxt-purgecss": "^0.2.1",
    "serve-favicon": "^2.5.0",
    "serverless-apigw-binary": "^0.4.4",
    "serverless-content-encoding": "^1.1.0",
    "serverless-http": "^1.9.0"
  },
  "devDependencies": {
    "autoprefixer": "^8.6.4",
    "babel-eslint": "^8.2.1",
    "cross-env": "^5.2.0",
    "eslint": "^5.0.1",
    "eslint-config-prettier": "^3.1.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-prettier": "2.6.2",
    "eslint-plugin-vue": "^4.0.0",
    "nodemon": "^1.11.0",
    "prettier": "1.14.3",
    "serverless-domain-manager": "^2.6.13",
    "tailwindcss": "~0.6.6",
    "terser": "^3.14.1"
  }
}
```

config 
```
service: frontend

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.env.NODE_ENV}
  region: eu-central-1
  environment:
    NODE_ENV: ${self:custom.env.NODE_ENV}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-content-encoding

custom:
  env: ${file(env.json)}
  apigwBinary:
    types:
      - '*/*'
```
