### ISSUE TITLE
Multiple Identity Sources on Api Gateway Custom Authorizer

### ISSUE THREAD

**Issue by enzo-beltrami** [serverless/serverless#5746]
# This is a Feature Proposal

## Description

- I would like to have multiple Identity sources on my API Gateway Authorizer

I think it would look something like this:

```
    authorizer:
        arn: arn:aws:lambda:us-east-2:********:function:authorizer
        identitySource:
            - method.request.header.Authorization
            - method.request.header.User-Agent
        type: request
```
