### ISSUE TITLE
initialization errored: Invalid or unexpected token

### ISSUE THREAD

**Issue by sjacob316** [serverless/serverless#5753]
# This is a Bug Report

## Description

* What went wrong?
**When I try deploying my application I get an error.**
* What did you expect should have happened?
**Successful deployment** 
* What was the config you used?
* What stacktrace or error message from your provider did you see?

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.3
* ***Operating System***: Windows 7
* ***Stack Trace***:
* ***Provider Error messages***:
`Serverless plugin "c:\users\admin\source\repos\testproj\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js" initialization errored: Invalid or unexpected token`

**Comment by exoego** [comment]
@sjacob316 could you share some reproducible `serverless.yml` and command (e.g. `sls deploy --someEnv=foo`) ?

**Comment by nsaud01** [comment]
I'm getting a similar error:

```
  Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-plugin-parcel" initialization errored: Unexpected token (
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.10.3
     Serverless Version:     1.28.0
```

Here's my serverless.yml
```
service: encoding-lambda

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-parcel

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs8.10

functions:
  encodingEntry:
    handler: src/handler.encodingEntry
    events:
      - http:
          path: encodingEntry
          method: get
  encodingTest:
    handler: src/handler.encodingTest
    events:
      - http:
          path: encodingTest
          method: get
```
