### ISSUE TITLE
AWS: Default value is not supported in and ${s3} 

### ISSUE THREAD

**Issue by exoego** [serverless/serverless#5756]
# This is a Bug Report

## Description

* What went wrong
   * Serverless throws error instead of using fallback if `${s3}` variables syntax can not retrieve value from AWS. 

* What did you expect should have happened?
   * Fallback value should be used as same as other variables syntax do so.
   * Note: `${ssm}` syntax is already able to use default if value is not found in AWS.

* What was the config you used?

```yml
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

custom:
  envVar: ${env:hoge, 'fallback'}
  optVar: ${opt:hoge, 'fallback'}
  selfVar: ${self:custom.xxx, 'fallback'}
  fileVar: ${file(./not-found):nooo, 'fallback'}
  # Note: cf is already reported in issue #4940
  # cfVar: ${cf:no-such-stuck-exists.UNDEFINED_KEY, 'fallback'} 
  s3Var: ${s3:no/such/key, 'fallback'}
  ssmVar: ${ssm:/path/to/service/myParam, 'fallback'}
```

    
* What stacktrace or error message from your provider did you see?

```
$ sls print                                                     
  Serverless Error ---------------------------------------
 
  Error getting value for s3:no/such/key. The specified bucket is not valid.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.36.3
```
Similar or dependent issues:
* #4940:  Default values for cf references
