### ISSUE TITLE
serverless deploy -f [function] - doesn't create new version of the function

### ISSUE THREAD

**Issue by ankithkonda** [serverless/serverless#5764]
# This is a Bug Report

## Description

* What went wrong?
`sls deploy -f [function]` - doesn't create a new version of the function
* What did you expect should have happened?
after `sls deploy -f [function]`, if the function's version is 3, then the new updates should create a new version - 4
* What was the config you used?
```yml

service: [service-name] # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

functions:
  LTI_Authenticator:
    handler: functions/LTI_Authenticator.handler
    role: myDefaultRole

  AppSync_Authenticator:
    handler: functions/AppSync_Authenticator.handler
    role: myDefaultRole

resources:
  Resources:
    myDefaultRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-role-Lambda-Policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:lambda"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "function"
                          - "${self:service}-${self:provider.stage}-LTI_Authenticator"
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:lambda"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "function"
                          - "${self:service}-${self:provider.stage}-AppSync_Authenticator"


```
* What stacktrace or error message from your provider did you see?
```bash
> sls deploy -f AppSync_Authenticator

Serverless: Bundling with Webpack...
Time: 547ms
Built at: 2019-01-30 12:08:58
                             Asset      Size                           Chunks             Chunk Names
functions/AppSync_Authenticator.js  4.05 KiB  functions/AppSync_Authenticator  [emitted]  functions/AppSync_Authenticator
Entrypoint functions/AppSync_Authenticator = functions/AppSync_Authenticator.js
[./functions/AppSync_Authenticator.js] 92 bytes {functions/AppSync_Authenticator} [built]
Serverless: Packaging function: AppSync_Authenticator...
Serverless: Uploading function: AppSync_Authenticator (1.48 KB)...
Serverless: Successfully deployed function: AppSync_Authenticator
Serverless: Successfully updated function: AppSync_Authenticator
```

no logs are written when I do - `sls deploy -f [function]`

Similar or dependent issues:
n/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.3
* ***Operating System***: MacOS 10.14
* ***Stack Trace***: see above
* ***Provider Error messages***: n/a see above
