### ISSUE TITLE
Custom variableSyntax with file variable resolution fails (${{deep:0})

### ISSUE THREAD

**Issue by emilbryggare** [serverless/serverless#5769]
# This is a Bug Report
## Description
* What went wrong?
Custom variable syntax and file variable resolutions results in faulty variables containing ${{deep:0...}

* What did you expect should have happened?
I expected the template using a custom variable syntax to work with ${file} variable resolution. And produce the following results.
```
$ sls print
service: template
provider:
  name: aws
  runtime: nodejs8.10
custom:
  settings:
    description: this is dummy
functions:
  hello:
    handler: handler.hello
    description: this is dummy
```
* What was the config you used?
```
# env.yml
description: this is dummy
```
 ```
# serverless.yml - Errorneous template with a custom variable syntax 
service: template

provider:
  name: aws
  runtime: nodejs8.10
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

custom:
  settings: ${{file(./env.yml)}}

functions:
  hello:
    handler: handler.hello
    description: ${{self:custom.settings.description}}
```
```
# serverless.yml - Successful template without variable syntax 
service: template

provider:
  name: aws
  runtime: nodejs8.10

custom:
  settings: ${file(./env.yml)}

functions:
  hello:
    handler: handler.hello
    description: ${self:custom.settings.description}
```
```
# serverless.yml - Successful template with a custom variable syntax and selecting one variable with file 
service: template

provider:
  name: aws
  runtime: nodejs8.10
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

custom:
  settings: ${{file(./env.yml):description}}

functions:
  hello:
    handler: handler.hello
    description: ${{self:custom.settings}}
```

* What stacktrace or error message from your provider did you see?
```
$ sls print
service: template
provider:
  name: aws
  runtime: nodejs8.10
  variableSyntax: '\${{([ ~:a-zA-Z0-9._@\''",\-\/\(\)]+?)}}'
custom:
  settings:
    description: this is dummy
functions:
  hello:
    handler: handler.hello
    description: '${{deep:0}.description}'
```
Similar or dependent issues:
* #4946
* #4953
* #4989

## Additional Data
@TassSinclair You mentioned this got resolved in #4989, is it still working for you? 
@erikerikson worked on these issues last year. Including him in the bug report in case he is interested in following this.

* ***Serverless Framework Version you're using***: 1.36.3
* ***Operating System***: Mac OS 10.14.2 

## Update 20190201
* Added example with a successful template using file and variable syntax but only selecting 1 variable.
* I should also mention that this issue is not a blocker for me as I managed to work around the issue with the successful template above. So as far as I am concerned you can prioritize this however you see fit.
