### ISSUE TITLE
Getting "Unable to import module 'index': Error" despite the fact configuration used to work.

### ISSUE THREAD

**Issue by AdamZaczek** [serverless/serverless#5776]
# This is a Bug Report

## Description
My api stopped working suddenly today despite it having no serverless configuration changes in the last two weeks. I get "Unable to import module 'index': Error" in logs and 502 status when trying to query my endpoints. I deploy on a daily basis and I already tried several working old commits with no success.  It's worth to note that api works in offline mode.

* What went wrong?
Working configuration suddenly broke when deploying. 502 status when querying endpoint, "Unable to import module 'index': Error" in logs.
* What did you expect should have happened?
Endpoint should work as it used to
* What was the config you used?
serverless.yml
```
service: ...
tenant: adamzaczek
app: ...
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    includeModules: true
    webpackConfig: ./webpack.config.js
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  credentials:
    accessKeyId: ...
    secretAccessKey: ...
  region: eu-central-1
functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get
```
webpack.config.js
```
const path = require('path')
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')
module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  optimization: {
    minimize: false
  },
  performance: {
    hints: false
  },
  devtool: 'nosources-source-map',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader'
          }
        ]
      }
    ]
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    sourceMapFilename: '[file].map'
  }
}

```

Export part of index.js
```
const app = express()

...

const handler = serverless(app)
export { handler }
```
package.json
```
{
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "npx sls offline start --useSeparateProcesses",
    "test": "mocha --require @babel/register 'tests/**/*.spec.js'",
    "seed": "npx babel-node utils/seedDb.js"
  },
  "keywords": [],
  "author": "Adam Żaczek",
  "devDependencies": {
    "@babel/node": "^7.0.0",
    "serverless-offline": "^3.31.3"
  },
  "dependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/register": "^7.0.0",
    "@babel/runtime": "^7.2.0",
    "@sentry/node": "^4.5.0",
    "apollo-server": "^2.3.1",
    "apollo-server-express": "^2.3.1",
    "apollo-server-lambda": "^2.3.1",
    "axios": "^0.18.0",
    "babel-loader": "^8.0.4",
    "bcryptjs": "^2.4.3",
    "chai": "^4.1.2",
    "cors": "^2.8.4",
    "dataloader": "^1.4.0",
    "dotenv": "^6.2.0",
    "express": "^4.16.4",
    "graphql": "^14.0.2",
    "graphql-playground-middleware-express": "^1.7.8",
    "graphql-resolvers": "^0.2.2",
    "jsonwebtoken": "^8.3.0",
    "mocha": "^5.2.0",
    "mongoose": "^5.4.0",
    "morgan": "^1.9.1",
    "serverless": "^1.36.3",
    "serverless-http": "^1.8.0",
    "serverless-webpack": "^5.2.0",
    "webpack": "^4.28.2",
    "webpack-node-externals": "^1.7.2"
  }
}

```
* What stacktrace or error message from your provider did you see?
```
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/apollo-env/lib/polyfills/array.js:3:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/3017

## Additional Data

* ***Serverless Framework Version you're using***:
1.36.3
* ***Operating System***:
MacOs
* ***Stack Trace***:
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/apollo-env/lib/polyfills/array.js:3:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
* ***Provider Error messages***:
"Unable to import module 'index': Error"
