### ISSUE TITLE
Incorrect parsing of GetAtt with multiple dots

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#5777]
# This is a Bug Report

## Description

* What went wrong?
```
  Error --------------------------------------------------

  The CloudFormation template is invalid: Template error: resource Database does not support attribute type Endpoint in Fn::GetAtt
```

* What did you expect should have happened?
It should've worked.

Serverless does not parse multiple dots properly in `GetAtt`, e.g.:

```yaml
    DatabaseEndpointUrl:
      Description: RDS database hostname and port
      Value: !Join [":", !GetAtt Database.Endpoint.Address, !GetAtt Database.Endpoint.Port]
```

This is valid, yet the output Serverless creates is:

```json
    "DatabaseEndpointUrl": {
      "Description": "RDS database hostname and port",
      "Value": {
        "Fn::Join": [
          ":",
          {
            "Fn::GetAtt": [
              "Database",
              "Endpoint"
            ]
          },
          {
            "Fn::GetAtt": [
              "Database",
              "Endpoint"
            ]
          }
        ]
      }
    }
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.36.3
* ***Operating System***: macOS 10.14.3
* ***Stack Trace***: N/A
* ***Provider Error messages***: See above
