### ISSUE TITLE
cacheControl field in cors config ignored

### ISSUE THREAD

**Issue by pchynoweth** [serverless/serverless#5779]
# This is a Bug Report

## Description

* What went wrong?
`cacheControl` in `cors` configuration was specified but ignored
* What did you expect should have happened?
`Cache-Control` added to header as described in https://github.com/serverless/serverless/blob/master/docs/providers/aws/events/apigateway.md
* What was the config you used?
```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
            cacheControl: 'max-age=600, s-maxage=600, proxy-revalidate'
```
* What stacktrace or error message from your provider did you see?
N/A

Similar or dependent issues:
* None found

## Additional Data

* ***Serverless Framework Version you're using***:
Tested with master (1.36.3)
* ***Operating System***:
Linux (Arch)
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A

It appears `cacheControl` is filtered out in `validate.js`.  I will follow up with a PR.  However, I am not entirely sure how useful this feature is anyway.  This post suggests this header value doesn't really do anything: https://stackoverflow.com/questions/40731465/access-control-max-age-vs-cache-control

> Also note that Access-Control-Max-Age can only be used (meaningfully) in preflight requests, that employ HTTP OPTIONS. At the same time HTTP spec (RFC 7231) does not permit caching in HTTP OPTIONS request ("Responses to the OPTIONS method are not cacheable"), so in essence, for HTTP OPTIONS, you are left only with Access-Control-Max-Age
