### ISSUE TITLE
deploy function --update-config does not update layer info

### ISSUE THREAD

**Issue by Kivol** [serverless/serverless#5786]
# This is a Bug Report

## Description

* What went wrong?
* What did you expect should have happened?
`sls deploy function -f foo --update-config` should update layer info, but it does not update it.

* What was the config you used?
```
functions:
  foo:
    handler: handlers.foo
    layers:
      - arn:aws:lambda:ap-northeast-2:############:layer:myLayer:${opt:version}
```

## Additional Data

It looks like the code to process `layers` option is missing in this file:
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deployFunction/index.js

Thanks,
Kivol
