### ISSUE TITLE
Serverless schedule events dont do anything

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#5789]
I am using sls 1.36.3 on RHEL7 with node v8.11.4.

When I add events schedule to a function nothing at all results in cloudwatch rules:

```
functions:
  myfun:
    name: ${self:custom.name}
    handler: myfun.new_message
    events:
    - schedule:    
      rate: rate(1 minutes)
      input:
        keep_warm: true
```

**Comment by pmuens** [comment]
Hey @cyberfox1 thanks for opening 👍

It looks like your `serverless.yml` is not correctly indented. It should look smth. like this:

```yml
functions:
  myfun:
    name: ${self:custom.name}
    handler: myfun.new_message
    events:
      - schedule: rate: rate(1 minutes)
```

That should fix the issue.
