### ISSUE TITLE
Support for TimeoutInMinutes when creating a Cloudformation Stack

### ISSUE THREAD

**Issue by thiagohirata** [serverless/serverless#5814]
# This is a Feature Proposal

## Description

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

The **CreateStack** API call accepts the `TimeoutInMinutes` parameters, but there is no way to set it when deploying a stack with serverless

* If there is additional config how would it look

```
provider:
  name: aws
  createStack:
    timeoutInMinutes: 1
```
