### ISSUE TITLE
Removal of existing CloudWatch Log Event Subscriptions do not work in some case

### ISSUE THREAD

**Issue by exoego** [serverless/serverless#5817]
# This is a Bug Report

## Description

* What went wrong?
    * `Resource limit exceeded` error occurs. 
    * The subscriptions removing (added in PR #5554) seems to fail handling some cases.

* What did you expect should have happened?
   * Existing subscriptions should be removed before updating stack, then updating stack complete successfully with new subscriptions.

* What was the config you used?

1. First, `sls deploy` the app service to be watched

```yml
service: my-app

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello1:
    handler: handler.hello
  hello2:
    handler: handler.hello
  hello3:
    handler: handler.hello
```

2. Then, `sls deploy` the watcher service.

```yml
service: watcher

provider:
  name: aws
  runtime: nodejs8.10

custom:
  target: /aws/lambda/my-app-${self:provider.stage}

functions:
  watcher:
    handler: handler.hello
    events:
      - cloudwatchLog: '${self:custom.target}-hello1'
      - cloudwatchLog: '${self:custom.target}-hello2'
      - cloudwatchLog: '${self:custom.target}-hello3'
```

3. Finally, rearrange `cloudwatchLog` events, then `sls deploy --force` watcher service.

```yml
service: watcher

provider:
  name: aws
  runtime: nodejs8.10

custom:
  target: /aws/lambda/my-app-${self:provider.stage}

functions:
  watcher:
    handler: handler.hello
    events: # rearranged !!
      - cloudwatchLog: '${self:custom.target}-hello3'
      - cloudwatchLog: '${self:custom.target}-hello2'
      - cloudwatchLog: '${self:custom.target}-hello1'
```
then the bellow error occurs.

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service watcher.zip file to S3 (387 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......
Serverless: Operation failed!
Serverless: View the full error output: <URL>

  Serverless Error ---------------------------------------
 
  An error occurred: WatcherLogsSubscriptionFilterCloudWatchLog2 - Resource limit exceeded. (Service: AWSLogs; Status Code: 400; Error Code: LimitExceededException; Request ID: <REQUEST_ID>).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.37.1
```

Similar or dependent issues:
* #3447 Similar. The issue which PR #5554 tried to resolve.
* #5700 Related. Subscriptions are accidentally(?) removed after #5554.

## Additional Data

* ***Serverless Framework Version you're using***: v.1.37.1
* ***Operating System***: Ubuntu 18
