### ISSUE TITLE
sls print gives different variable resolution than sls info, deploy, etc.

### ISSUE THREAD

**Issue by blissboy** [serverless/serverless#5830]
# This is a Bug Report

## Description
This `serverless.yml` file
```
devoverrides: ${file(./../../devOverrides.yml)}

overrideStage: ${opt.stage, devoverrides.stage}

# The `service` block is the name of the service
service: ingest

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, self:devoverrides.stage, 'delete-nostage'}
  runtime: nodejs8.10

# The `functions` block defines what code to deploy
functions:
  ingest:
    handler: src/ingest.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - s3:
          bucket: xxx-poc-ingest-${self:provider.stage}
          event: s3:ObjectCreated:*
```

does this for `serverless print`:

```
devoverrides:
  stage: dev-jpw
service: ingest
provider:
  stage: dev-jpw
  region: us-west-2
  name: aws
  runtime: nodejs8.10
functions:
  ingest:
    handler: src/ingest.helloWorld
    events:
      - s3:
          bucket: xxx-poc-ingest-dev-jpw
          event: 's3:ObjectCreated:*'
```

and does this for `sls info`
```  Serverless Error ---------------------------------------
 
  Stack with id ingest-delete-nostage does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.37.1 
```

I would expect the resolved value for the stack to be `ingest-dev-jpw` not `ingest-delete-nostack` in the info output. 

Similar or dependent issues:
* #5828 

## Additional Data

* ***Serverless Framework Version you're using***:
1.37.1
* ***Operating System***:
MacOS

* ***Stack Trace***:
* ***Provider Error messages***:
