### ISSUE TITLE
Custom name for Google cloud functions

### ISSUE THREAD

**Issue by peric** [serverless/serverless#5845]
# Custom name for Google cloud functions

## Description

For `AWS lambda`, it is possible to set custom name for a Lambda function (https://serverless.com/framework/docs/providers/aws/guide/functions/, line 14 in the example).

I want to be able to do the same with `google` provider, where config will look something like this:

```yaml
functions:
  handler:
    handler: Handler
    name: BackupHandler
    memorySize: 256
    timeout: 300s
```

There are multiple reasons why this can be useful

* better (and more descriptive) naming of google cloud functions. e.g. if you have multiple cloud functions in the same project, some are written in python and some in golang, you'll end up with names like `backup_handler` and `BackupHandler`
* if you have a package named `backup`, `golint` recommends you have a function named `Handler` and not `BackupHandler`. But if you deploy `Handler` to google cloud, it's just not descriptive enough
