### ISSUE TITLE
CORS issue - Firefox

### ISSUE THREAD

**Issue by drexler** [serverless/serverless#5877]
# This is a Bug Report
I have a set of deployed microservices which can be accessed by an web application across different browsers. Cross-browser testing **works** on all major browsers with the exception of Firefox v65. Help appreciated with this. 

## Description

* What went wrong?
client code:
```
const req = new Request('https://custom-domain.com/basePath/cors-issues');
const testfoo = await fetch(req, {
    method: 'POST',
    mode: 'cors',
    headers: {
        "Content-Type": "application/json",
        "Authorization": `${sessionStorage.getItem('access_token')}`,
    },
    body: JSON.stringify({
        fooMachu: 'test'
    }), 
})
```

serverless.yml:
```
...
corsIssue:
    handler: src/handler.corsIssue
    events:
        - http:
            path: /cors-issues
            method: post
            authorizer: ${file(../internal-api/serverless-output.json):TokenVerifierArn}
            cors: true
```

handler:
```
export function corsIssue (event, context, callback) {

    // Headers: custom class which builds out response headers
    const headers = new Headers();
    headers.append('Access-Control-Allow-Origin', '*');
    headers.append('Access-Control-Allow-Credentials', 'true');
    headers.append('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, DELETE');
    headers.append(
            'Access-Control-Allow-Headers',
            'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers',
        );

    const response = { statusCode: 200, headers: headers.toJSON(), body: JSON.stringify(event) }

    callback(undefined, response)
}
```
* What did you expect should have happened?
CORS request should have gone through.
* What was the config you used?
* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
1.32
* ***Operating System***:
MacOS High Sierra v10.13.6
* ***Stack Trace***:
* ***Provider Error messages***:
