### ISSUE TITLE
TimeToLive permissions missing from the IAM credentials template for AWS

### ISSUE THREAD

**Issue by domdomegg** [serverless/serverless#5896]
# This is a Bug Report

## Description

* What went wrong?

Described a `TimeToLiveSpecification` for an AWS DynamoDB Table. Tried deploying function but it failed on the basis that the AWS IAM policy the Serverless agent was acting on lacked the `dynamodb:DescribeTimeToLive` permission. It also should have the permission `dynamodb:UpdateTimeToLive`.

* What did you expect should have happened?

Serverless config would be executed fine while using the default [IAM credentials template for AWS](https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8).

* What was the config you used?

[Default IAM credentials template](https://gist.github.com/ServerlessBot/7618156b8671840a539f405dea2704c8)

`resources` section of `serverless.yml`:

```yaml
resources:
  Resources:
    MyTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: 'N'
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: MyTableName
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
```

* What stacktrace or error message from your provider did you see?

```
An error occurred: MyTable - User: [removed] is not authorized to perform: dynamodb:DescribeTimeToLive on resource: [removed]
```

I believe the template should be updated to add these permissions:
- `dynamodb:DescribeTimeToLive`
- `dynamodb:UpdateTimeToLive`

## Additional Data

* ***Serverless Framework Version you're using***: 1.38.0
* ***Operating System***: win32
* ***Provider Error messages***: `An error occurred: MyTable - User: [removed] is not authorized to perform: dynamodb:DescribeTimeToLive on resource: [removed]`
