### ISSUE TITLE
WebSocket Authenticator not mapped

### ISSUE THREAD

**Issue by delprofundo** [serverless/serverless#5902]
# This is a Bug Report

## Description

* What went wrong?

Created WebSocket connection endpoint (worked by itself) and some other routes. Now added an authorizer. its function gets created but it does not get mapped to the APIG Authorizer.

* What did you expect should have happened?
* What was the config you used?

```
functions:
  socketAuthorize:
    name: ${self:provider.stage}-${self:custom.grub}-socketAuthorize
    handler: sec/socketAuthorize.handler
    description: must use US spelling for authorize function. auth just for socket conn
  authorize:
    name: ${self:provider.stage}-${self:custom.grub}-authorize
    handler: sec/authorize.handler
    description: must use US spelling for authorize function.
  createNotification:
      handler: handler.createNotification
      name: ${self:provider.stage}-${self:custom.grub}-createNotification
      description: create a basic notification record
      events:
      - http:
          path: /
          method: post
  subscribeChannel:
    handler: handler.subscribeChannel
    name: ${self:provider.stage}-${self:custom.grub}-subscribeChannel
    events:
      - websocket:
          route: $connect
          authorizer:
            name: socketAuthorize
            identitySource:
              - 'route.request.header.Authorization'
  disconnectUser:
    handler: handler.disconnectUser
    name: ${self:provider.stage}-${self:custom.grub}-disconnectUser
    events:
      - websocket:
          route: $disconnect
  SocketEcho:
    handler: handler.socketEcho
    events:
      - websocket:
          route: secho
```

* What stacktrace or error message from your provider did you see?

no error. it deployed and running the connect route calls the connect function but does not call the authorizer (ie: no log entry for auth).

## Additional Data

* ***Serverless Framework Version you're using***:
"serverless": "^1.38.0"

I wondered if the presence of the other Authorizer was causing the problem but removing it made no difference.
