### ISSUE TITLE
Error using websockets with role ARN

### ISSUE THREAD

**Issue by jtmckay** [serverless/serverless#5906]
Same issue as https://github.com/serverless/serverless/issues/5868

But the error occurs when using an existing ARN for the role.

EG:

```yml
functions:
  connectionManager:
    handler: handler.connectionManager
    role: arn:aws:iam::123456789:role/TEST_ENV_Lambda
    events:
      - websocket:
          route: $connect
```

EG 2:

```yml
provider:
  name: aws
  runtime: nodejs8.10
  stackName: ${self:service}-${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}
  role: arn:aws:iam::123456789:role/TEST_ENV_Lambda
```

**Comment by pmuens** [comment]
Hey @jtmckay thanks for opening 👍

I tried to reproduce this bug using the latest `master`. Here's the config I've used:

```yml
service:
  name: test

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    role: arn:aws:iam::XXXXX:role/test-dev-us-east-1-lambdaRole
    events:
      - websocket:
          route: $connect
```

(Un)fortunately I couldn't reproduce this. Could you checkout the latest `master` to see if it has already been fixed? Thanks!
