### ISSUE TITLE
Cognito Authorizer not being created when specified in Websockets template

### ISSUE THREAD

**Issue by mrowles** [serverless/serverless#5910]
# This is a Bug Report

## Description

I've added a Cognito ARN to the `authorizer` property in my websockets  config, but my API's get created in API Gateway without an authorizer. I expected that, as per normal REST API's, that it is created. I've followed the [docs accordingly](https://serverless.com/framework/docs/providers/aws/events/websocket#using-authorizers).

Alternatively, if this is not allowed, it would be good that the docs state as such and suggest alternatives in using the Cognito JWT to authenticate a user and pass their info on to the websockets function. Right now, the only thing I can see working is if I implement some sort of custom authorizer which duplicates the Cognito JWT decoder logic, which seems [very complex and brittle](https://github.com/awslabs/aws-support-tools/tree/master/Cognito/decode-verify-jwt).

**serverless.yml:**
```
connectionHandler:
    handler: search.connectionHandler
    events:
      - websocket:
          route: $connect
          authorizer:
            arn: ${self:provider.environment.authoriserArn} // cognito user pool arn
      - websocket:
          route: $disconnect
          authorizer:
            arn: ${self:provider.environment.authoriserArn} // cognito user pool arn
```

Similar or dependent issues:
N/A

## Additional Data

* ***Serverless Framework Version you're using***: 1.38
* ***Operating System***: Unix
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by AlexRex** [comment]
I tried the same with custom authorizer and is not working neither for me. I've been checking the pull request that was recently created to add the support to websockets (https://github.com/serverless/serverless/pull/5824) and looks like there's no logic to add the authorization.

@eahefnawy Is this something missing in your PR?

**Comment by eahefnawy** [comment]
Is that using master? The PR you referenced does not include authorizers, but I just merged authorizers support which was not released yet. Seems like the docs are "too updated" though 😅 ... sorry about that.

**Comment by eahefnawy** [comment]
@mrowles we've fixed the docs to point to the released version, not master. However, could you confirm that master is working for you? I'm not sure yet if Cognito authorizers is supported.

**Comment by mrowles** [comment]
@eahefnawy 😂That's cool, thanks for the quick reply anyways mate! 

In the case that Cognito Authorisers aren't supported out of the box (yet...😉), I'll use the JWT decoder from the provided example and retrofit it to look at `queryParams` instead of `headers` (and provide example).

**Comment by marcelschulze** [comment]
Damn it, I only had a look at the last release notes "add websocket support" and then I checked out the authoriser example... wasted 2 hours testing in the morning why it isn't working  🙈. But no problem, better too fast as too slow 🎉 Thank you very much for all the cool stuff.

Is it possible to specify master as a serverless version in the config file, or how would I go about that?

**Comment by marcelschulze** [comment]
Can somebody quickly assist me here please? This has nothing todo with the protected connect endpoint, but anyway here it comes:

 I always get the access denied error when I try to post a ws message back to the client via the ApiGatewayManagementApi postToConnection:
`... service is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:eu-central-1:********7181:[MY_ID]/dev/POST/@connections/WlwDYcq3FiAAcsg%3D`

I tried to add in my serverless.yml:
```yml
iamRoleStatements:
    - Effect: Allow
      Action:
        - execute-api:POST
        - execute-api:Invoke
      Resource:
        - arn:aws:execute-api:${self:provider.region}:*:#{AWS::AccountId}/${self:provider.stage}/POST/@connections/*
  
```

It did work for all my other resources like SNS or DynamoDB so far. Anybody has an idea whats wrong?

Sorry if it is a rookie mistake, but I'm only learning aws and serverless for the last week. 

Thanks a lot.

**Comment by mrowles** [comment]
Resolved in 1.39.1 (at least for a `$connect` custom authoriser). Thanks for the quick resolution!

I ended up with:

```
functions:
  ...
  connectionHandler:
    handler: handler.connectionHandler
    events:
      - websocket:
          route: $connect
          authorizer:
            name: customAuthoriser
            identitySource:
              - 'route.request.querystring.Authorizer'
```

And passing through the wss connection with a query string parameter (not ideal, but seems to be the way):

```
const subjectConfig: WebSocketSubjectConfig<any> = {
  url: `wss://abcd1234.execute-api.ap-region-1.amazonaws.com/pre?Authorizer=${token}`
};
this.subject = webSocket(subjectConfig);
```
