### ISSUE TITLE
Question: Can I configure cors at a provider level for all functions? 

### ISSUE THREAD

**Issue by danielcondemarin** [serverless/serverless#5913]
From reading the docs, it seems like I have to enable `cors` for each individual function. Also the docs suggest that functions inherit config from the provider, but doesn't seem to apply for cors.  Is that right?

Ideally I would be able to do:

```yml
provider:
  name: aws
  cors:
      origins:
        - http://example.com
        - http://example2.com
...
```

which then applies that cors config to all functions. If that's not possible atm, would you consider a PR?
