### ISSUE TITLE
access-control-allow-origin overwritten

### ISSUE THREAD

**Issue by crowecawcaw** [serverless/serverless#5920]
# This is a Bug Report

## Description
When setting the ```access-control-allow-origin ``` header to a domain name inside a Lambda function, the header gets overwritten to ```access-control-allow-origin: *```. I expected the header to remain as I set it. I am using a Lamba function with the lambda-proxy integration. When I test my code offline using serverless-offline, the headers are set correctly without being overwritten. My serverless.yml looks like:

```
functions:
  api:
    handler: src/lambda.handler
    events:
      - http: any {proxy+}
```

Similar or dependent issues: none

## Additional Data

* ***Serverless Framework Version you're using***: 1.38.0
* ***Operating System***: MacOS
* ***Stack Trace***: n\a
* ***Provider Error messages***: n\a

**Comment by drexler** [comment]
@crowecawcaw curious, do you get the right header when you explicitly set the origin as such:
```
functions:
  api:
    handler: src/lambda.handler
    events:
      - http: any {proxy+}
        cors:
          origin: 'your-origin.com'
```
