### ISSUE TITLE
CloudWatchEvent Rule Created Incorrectly on AWS

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [serverless/serverless#5923]
# This is a Bug Report

## Description

* What went wrong?

In my `serverless.yml` under one of my functions I wanted to make it run only when it receives a ClouwatchEvent. So I added this:

```YAML
  events:
    - cloudwatchEvent:
        name: ${self:custom.service.name}-importProducts-rule
        event:
          source:
            - 'ip.bo.data-entry'
          detail-type:
            - 'GiftsValidationResult'
          detail:
            validationResult:
              products:
                isValid:
                  - true
              promotions:
                isValid:
                  - true
              gifts:
                isValid:
                  - true
```
After deployment, I checked the created rule under CloudWatch and I found it is converting the `true` flag to `"true"` string with quotes which makes the pattern fail to match the incoming events.

From AWS:

```JSON
{
  "detail-type": [
    "GiftsValidationResult"
  ],
  "source": [
    "ip.bo.data-entry"
  ],
  "detail": {
    "validationResult": {
      "promotions": {
        "isValid": [
          "true"
        ]
      },
      "products": {
        "isValid": [
          "true"
        ]
      },
      "gifts": {
        "isValid": [
          "true"
        ]
      }
    }
  }
}
```

* What did you expect should have happened?

I expected to see the rule in AWS as follows:

```JSON
{
  "detail-type": [
    "GiftsValidationResult"
  ],
  "source": [
    "ip.bo.data-entry"
  ],
  "detail": {
    "validationResult": {
      "promotions": {
        "isValid": [
          true
        ]
      },
      "products": {
        "isValid": [
          true
        ]
      },
      "gifts": {
        "isValid": [
          true
        ]
      }
    }
  }
}
```
As you can see the `true` without any quotes.

When I changed the wrong to the correct format by hand, it worked as expected but serverless deployment adds the quotes around the true/false flags. 

* What was the config you used?

N/A

* What stacktrace or error message from your provider did you see?

N/A

Similar or dependent issues:

N/A

## Additional Data

* ***Serverless Framework Version you're using***: `v1.37.1`
* ***Operating System***: Windows 10
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
