### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by ReidWeb** [serverless/serverless#5927]
# This is a Bug Report

## Description

* What went wrong?

Execution of `serverless package` yields `Cannot read property 'substr' of undefined` - there is no change in my `serverless.yml` from the prior version.

* What did you expect should have happened?

`serverless package` does not yield the correct result, it should execute successfully.

* What was the config you used?

```yml
service: myFunction
tenant: myAccount
app: myApp

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 25
  memorySize: 128
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

  environment:
    ENV: ${opt:stage, self:provider.stage}
    REGION: ${opt:stage, self:provider.region}
    TRACING_ENABLED: true

# you can add packaging information here
package:
  excludeDevDependencies: true

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-tracing
  - serverless-iam-roles-per-function
  - serverless-plugin-optimize
  - serverless-offline

functions:
  myFunction:
    name: myProject-${self:provider.stage}-${self:service}
    handler: src/handler.handler
    tracing: true
    layers:
      - [REDACTED]
    package:
      include:
        - src/**
        - node_modules/**
        - package.json
    iamRoleStatementsInherit: true
```
* What stacktrace or error message from your provider did you see?

```
Serverless: Optimize: starting engines
Serverless: Optimize: myApp-dev-myFunction
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Tracing ENABLED for function "myApp-dev-myFunction"

  Type Error ---------------------------------------------

  Cannot read property 'substr' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.15.0
     Serverless Version:     1.39.0
```

Similar or dependent issues:
* None

## Additional Data

* ***Serverless Framework Version you're using***: 1.39.0, functions fine with identical config running against 1.38.0
* ***Operating System***: MacOS
* ***Stack Trace***: As above
* ***Provider Error messages***: As above
