### ISSUE TITLE
Version 1.39.0 causing CircleCI deployment script to fail.

### ISSUE THREAD

**Issue by gevorggalstyan** [serverless/serverless#5928]
# This is a Bug Report

## Description

* What went wrong? After updating to v1.39.0 our deployment script crashes on CircleCI.
* What did you expect should have happened? The update should not affect the deploy process and deploy as 1.38.0 was doing.
* What was the config you used? In terms of this issue, I think it is worth mentioning that we are using serverless-webpack plugin.
* What stacktrace or error message from your provider did you see? I have pasted the deployment logs at the bottom.

## Additional Data

Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, stat '/home/circleci/repo/.serverless/.serverless/serverless-api.zip'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.15.1
     Serverless Version:     1.39.0
 
Exited with code 1

**Comment by PMCorbett** [comment]
I am seeing precisely the same issue on CircleCI. I am also using the serverless-webpack plugin

Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
 
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, stat '/home/circleci/repo/.serverless/.serverless/engage.zip'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.11.4
     Serverless Version:     1.39.0
 
Exited with code 1

**Comment by twitchy9000** [comment]
I am seeing the same issue when attempting to deploy from CircleCI and from local.

serverless-webpack
package:
  individually: true

Serverless: Packaging service...

  Serverless Error ---------------------------------------

  No getBrand.zip file found in the package path you provided.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.10.0
     Serverless Version:     1.39.0

**Comment by srdone** [comment]
I am also seeing the issue locally and on our build server. It appears to be drilling down into the `/.serverless` folder twice to look for the `.zip` file, given the ENOENT message.

I have confirmed that `1.38.0` is working without issue.

**Comment by mbunge** [comment]
Confirmed for local Deployment and AWS CodeDeploy / Pipelines too!

## Local

```
  ENOENT: no such file or directory, stat '/Users/tackleberry/projects/my-custom-project-name/.serverless/.serverless/my-custom-project-name.zip'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

`/.serverless/.serverless` seems to be wrong at this point.

## CodeBuild Error:

```
Serverless Warning --------------------------------------
 A valid file to satisfy the declaration 'file(resources/dynamodb-table.yml)' could not be found.
 Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
 Error --------------------------------------------------

ENOENT: no such file or directory, stat 'artifacts/dev/.serverless/my-fixed-project-name.zip'
```

**Comment by dinamic** [comment]
Confirmed. It also happens on our setup. 

I tried to fix it myself by editing `.serverless/serverless-state.json` to no avail.

Granted, I have no clue how serverless works, but was trying to make it work somehow. I can't deploy no more. :(

**Comment by mbunge** [comment]
I also opened an issue in serverless-webpack channel: https://github.com/serverless-heaven/serverless-webpack/issues/491

**Comment by mbunge** [comment]
Forcing serverless@1.38.0 in CircleCI config and for AWS in your CodeBuildDeployProject.Source.BuildSpec config.

**Comment by dinamic** [comment]
Going thru changes, I feel like this is the one that broke things.

https://github.com/serverless/serverless/pull/5297

**Comment by guice** [comment]
Same issue. It's global. Happens with every service of ours.

**Comment by dschep** [comment]
Are all of you using serverless-webpack like @mbunge is?

**Comment by rrosenblum** [comment]
I am having this issue and I am not using `serverless-webpack`.

**Comment by guice** [comment]
I am using `serverless-webpack`. The error I get is a double `.severless/.serverless` in the package path.

**Comment by guice** [comment]
I am using `serverless-webpack`. The error I get is a double `.serverless/.serverless` in the package path.

**Comment by dschep** [comment]
@rrosenblum, could you provide your `serverless.yml`?

**Comment by rrosenblum** [comment]
Here is a copy of my [serverless.yml](https://gist.github.com/rrosenblum/bcc0fe426455ddafdb7a3004f99d662b).

**Comment by hiloboy0119** [comment]
I am getting the error as well.  I'm not using `serverless-webpack`.  I am however using `serverless-python-requirements` and I saw a related issue on their github:

https://github.com/UnitedIncome/serverless-python-requirements/issues/332

**Comment by keithalpichi** [comment]
I'm also encountering Jenkins build issues using the latest version 1.39.0:
```
  Serverless Error ---------------------------------------
 
  No src-some-package-name-dev-run.zip file found in the package path you provided.
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.39.0
```
And our serverless.yml:
```

service: some-package-name

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-domain-manager

provider:
  name: aws
  runtime: python3.6
  versionFunctions: true
    
package:
  individually: true
  exclude:
    - 'example/**'
    - 'numpy/*.pyc'
    - 'numpy/**/*.pyc'
    - 'code/**'
    - './**/*.pyc'
    - './**/__pycache__/*.pyc'
    - 'requirements/**/*.pyc'
    - './serverless/requirements/**/*.pyc'
    - 'node_modules/**/*.md'
    - '*.ts'
    - 'src/*.ts'
    - 'src/**/*.ts'
    - 'src/*.json'
    - 'src/**/*.json'
    - README.md
    - '*.json'
    - 'setup/*'
    - 'setup'
    - 'test/'
    - .gitignore
    - serverless.yml
    - 'test_set'
    - 'test_set/**'
    - 'json_contract'
    - 'json_contract/**'
    - 'codes/__pycache__'
    - 'codes/__pycache__/**'
    - 'train'
    - 'db'
    - 'para/**'
    - 'old/**'

functions:
  run:
    handler: index.run
    module: src
    timeout: 300
    memorySize: 3008

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    slimPatterns:
      - "**/*.egg-info*"
      - "**/*.pyc"
      - "**/tests"
      - "test/*"
```

I realize the error occurs before deploying to AWS S3.
