### ISSUE TITLE
function.package.artifact breaks deploy if zip files have same name

### ISSUE THREAD

**Issue by dpeek** [serverless/serverless#5939]
# This is a Bug Report

## Description

* What went wrong?

I packaged my own artifacts with the same zip file name:

```
/packages/foo/bin/lambda.zip
/packages/bar/bin/lambda.zip
/packages/boo/bin/lambda.zip
```

When I deployed my functions they all had the same code.

* What did you expect should have happened?

Serverless should have renamed the artifacts based on the function name when uploading to S3 so that they didn't overwrite each other.

```
/packages/foo/bin/lambda.zip -> s3://deploy/serverless/service/stage/timestamp/foo.zip
/packages/bar/bin/lambda.zip -> s3://deploy/serverless/service/stage/timestamp/bar.zip
/packages/boo/bin/lambda.zip -> s3://deploy/serverless/service/stage/timestamp/boo.zip
```
* What was the config you used?

```
template:
    handler: index.handler
    package:
      artifact: packages/template/bin/lambda.zip
  web:
    handler: index.handler
    package:
      artifact: packages/web/bin/lambda.zip
```
* What stacktrace or error message from your provider did you see?

No errors, my functions were just all the same.

## Additional Data

* Serverless 1.39.1
* macOS
