### ISSUE TITLE
Custom authorizer for websockets connection not passing claims to next function and calling $disconnect rather than $connect

### ISSUE THREAD

**Issue by mrowles** [serverless/serverless#5942]
# This is a Bug Report

## Description

I have a custom authoriser function in front of a websocket connection function, which is successful but does not pass or trigger the actual connection function it sits in front of.

I have tried to return the value, resolve it as a promise or, what I'd expect to work, pass it as a value in the callback.

**serverless.yml**

```
customAuthoriser:
  handler: handler.customAuthoriser
  cors: true
connectionHandler:
  handler: handler.connectionHandler
  events:
    - websocket:
        route: $connect
        authorizer:
          name: customAuthoriser
          identitySource:
            - 'route.request.querystring.Authorizer'
    - websocket:
        route: $disconnect
```

**connectionHandler.js**

```
export async function customAuthoriser(event, context, callback) {
  console.log('enter customAuthoriser');
  let someErr;
  let claims;

  return new Promise((resolve, reject) => {

      // do some stuff to get claims

      if (someErr) {
          reject(someErr);
      }

      // doesn't work
      callback(null, claims);

      // doesn't work
      resolve(claims);

      // also doesn't work
      return claims;
  });
}
```

**connectionHandler.js**

```
// this never gets hit
export async function connectionHandler(event, context, callback) {
  console.log('enter connectionHandler');

  // if it ever gets called, I'd expect this to have a value
  console.log(event.requestContext.authorizer.claims.sub);
}
```

**client.ts**

```
import {webSocket, WebSocketSubjectConfig} from 'rxjs/webSocket';

private subject: Subject;

private setupWebsockets(token: string) {
  const subjectConfig: WebSocketSubjectConfig<any> = {
    url: `wss://abcd1234.execute-api.ap-southeast-1.amazonaws.com/pre?Authorizer=${token}`
  };
  this.subject = webSocket(subjectConfig);

  this.subject.subscribe(
    (msg) => console.log('message received: ' + msg),
    (err) => console.error(err),
    () => console.log('complete')
  );
}
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.39.1
* ***Operating System***: N/A
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by eahefnawy** [comment]
thanks for reporting @mrowles ... I'm guessing you're using Cognito?

**Comment by mrowles** [comment]
@eahefnawy Yep! Which aren't/weren't supported for Websockets out of the box as of 1.39.1. So I rolled my own custom one. However, not sure if it matters what the auth is, looks like this might be a problem beyond that.

**Comment by mrowles** [comment]
I've updated, this is actually triggering (as of `serverless@1.40.0`) but still no claims passed over

**Comment by mrowles** [comment]
I have even tried separating the `$connect` & `$disconnect` handlers and it keeps sending it to the $disconnect:

```
  connectHandler:
    handler: handler.connectHandler
    events:
      - websocket:
          route: $connect
          authorizer:
            name: customAuthoriser
            identitySource:
              - 'route.request.querystring.Authorizer'
  disconnectHandler:
    handler: handler.disconnectHandler
    events:
      - websocket:
          route: $disconnect
```

I have even tried a different client websocket library to no avail:

```
import {ClientOptions, SubscriptionClient} from 'subscriptions-transport-ws';
import {WebSocketLink} from 'apollo-link-ws';

private setupWebsockets(token: string) {
    const url = `wss://abcd1234.execute-api.ap-southeast-2.amazonaws.com/pre?Authorizer=${token}`;
    const subscriptionClientOptions: ClientOptions = {
        reconnect: true
    };

    const subscriptionClient = new SubscriptionClient(url, subscriptionClientOptions);

    const link = new WebSocketLink(subscriptionClient);
}
```

I'm either doing something wrong, or this is a genuine bug.
