### ISSUE TITLE
Weird event indentation issue

### ISSUE THREAD

**Issue by incompletude** [serverless/serverless#5953]
I'm using 2 spaces indentation.

This first example contains 2 spaces in every new level, and does not work. The error is `Missing or invalid "path" property in function "hello" for http event in serverless.yml`.

```
service: my-custom-name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
        path: users/create
        method: get
```

For this to work, I have 2 use 1 space for the event, and 4 spaces for the options (or 2 and 6 spaces):

```
service: my-custom-name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
     - http:
        path: users/create
        method: get
```

Am I missing something here? The first example is parsed as valid yaml.

**Comment by pmuens** [comment]
@incompletude thanks for opening.

Yes, that some of the downsides of using YAML for configuration here.

While

```
functions:
  hello:
    handler: handler.hello
    events:
      - http:
        path: users/create
        method: get

```

looks correct it must be

```
functions:
  hello:
    handler: handler.hello
    events:
      - http: # indent by 2 here
          path: users/create
          method: get
```

Hope that this helps.
