### ISSUE TITLE
Cannot create send permissions for websockets on APIGateway

### ISSUE THREAD

**Issue by alpeshgaglani** [serverless/serverless#5955]
I'm trying to create permissions for sending a message on websocket API gateway. My policy looks like
```
                PolicyDocument:
                  Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action:
                        - 'execute-api:ManageConnections'
                      Resource: #!Sub 'arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${self:custom.RestapiId}/*'
                        - 'Fn::Join':
                            - ':'
                            -
                              - 'arn:aws:execute-api'
                              - Ref: 'AWS::Region'
                              - Ref: 'AWS::AccountId'
                              - 'Fn::Join':
                                - '/'
                                -
                                  - Ref: ApiGatewayRestApi
                                  - '*'
```
My provider is set as:
```
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'dev'}
  region: us-west-2
  websocketsApiName: sync-${self:provider.stage}
  websocketsApiRouteSelectionExpression: $request.body.action
```
I was assuming that I can get the Ref for websocket api like we do for Rest api. 
I tried to get Ref for  ApiGatewayWebsocket(s)Api, but that doesnt work either.
What is the logical name for the websocket api?
