### ISSUE TITLE
lambda environments wont reupdate if you delete one of them in lambda console.

### ISSUE THREAD

**Issue by sleiter88** [serverless/serverless#5958]
- What went wrong?
I cannot reupdate environments variables if you previosly delete one of them in AWS lambda console. It seems if you modify the environments directly in the console, CloudFormation cannot detect any change in the CloudFormation stack template so nothing is happen if you deploy again the function.

- How to reproduce?
Deploy a project(pyton 2.7) with some environments variables.  Then go to aws lambda console and delete it directly and save the function. Now try to deploy the project again (sls deploy -s test for example) and you will see your environments does not upload anymore.

- What was the config you used?
```
service: internal-invitation

provider:
  name: aws
  runtime: python2.7
  region: eu-west-1
  role: arn:aws:iam::awsrole:role/service-role/bitLambdaRole
  environment:
    CAMPAIGN_TABLE: ${self:custom.stage}_pax_campaigns
    INFLUENCERS_TABLE: ${self:custom.stage}_pax_influencers
    PAYMENT_TABLE: ${self:custom.stage}_pax_payments
    DAY_FEE: 1
    ENDPOINT_ACCEPT_REJECT_CAMPAIGN: ${self:custom.api_path.campaign}
    INFLUENCER_EMAIL_INVITATION_QUEUE: ${self:custom.INFLUENCER_EMAIL_INVITATION_QUEUE}
    SENDER: "Binfluencer <admin@binfluencer.es>"
    COPY_EMAIL: "contacto@binfluencer.io"
    CHAT_ID: ${self:custom.CHAT_ID}
    LINKADIA_NETWORK_DOMAIN: ${self:custom.LINKADIA_NETWORK_DOMAIN}
    LINKADIA_API_KEY: ${self:custom.LINKADIA_API_KEY}
    ELASTIC_ENDPOINT: ${self:custom.ELASTIC_ENDPOINT}
    MAX_NUMBER_MESSAGES: ${self:custom.MAX_NUMBER_MESSAGES}


custom:
  stage: ${opt:stage, self:provider.stage}
  stages:
    - dev
    - test
    - prod
  vpc:
    securityGroupIds:
    - sg-0afd7ad8c72c5addd
    - sg-29e54451
    subnetIds:
    - subnet-5f20eb05
    - subnet-ef9f1689
    - subnet-7c069f34
    - subnet-0e5fd584d0bbe9293
  api_path: ${file(stages/${self:custom.stage}.yml):api_path}
  CHAT_ID: ${file(stages/${self:custom.stage}.yml):CHAT_ID}
  LINKADIA_NETWORK_DOMAIN: ${file(stages/${self:custom.stage}.yml):LINKADIA_NETWORK_DOMAIN}
  INFLUENCER_EMAIL_INVITATION_QUEUE: ${file(stages/${self:custom.stage}.yml):INFLUENCER_EMAIL_INVITATION_QUEUE}
  LINKADIA_API_KEY: ${file(stages/${self:custom.stage}.yml):LINKADIA_API_KEY}
  ELASTIC_ENDPOINT: ${file(stages/${self:custom.stage}.yml):ELASTIC_ENDPOINT}
  MAX_NUMBER_MESSAGES: ${file(stages/${self:custom.stage}.yml):MAX_NUMBER_MESSAGES}


plugins:
  - serverless-python-requirements
  - serverless-dir-config-plugin
  - serverless-stage-manager

```
similar issue: #3007
