### ISSUE TITLE
error in fresh deployments after removing the whole cloudformation stack

### ISSUE THREAD

**Issue by KanesYang** [serverless/serverless#5961]
Hi, all

As it said in the title, I just delete all the cloudformation stack and try to do the fresh deploy again. but when I run the `sls deploy --verbose`, it shows the error
```

The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ServerlessDeploymentBucket] in the Resources block of the template

 For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable
```

I double check my serverless.yml file, but found I don’t define a bucket with Name ServerlessDeploymentBucket.

Then I go to the AWS console, after clicking my root stack (I am using the serverless-split-stack plugin),
there is only a simple template

```
AWSTemplateFormatVersion: 2010-09-09
Description: The AWS CloudFormation template for this Serverless application
Resources:
  ServerlessDeploymentBucket:
    Type: 'AWS::S3::Bucket'
Outputs:
  ServerlessDeploymentBucketName:
    Value: !Ref ServerlessDeploymentBucket

```

while actually in my origin serverless.yaml, there are more than 1200 lines. Quite wondering what is the error related to the serverless. Appreciated for anyone could help. Thanks.

Edit: there are a bunch of plugin I am using which maybe useful for troubleshooting the error:

```
serverless-content-encoding
serverless-pseudo-parameters
serverless-webpack
serverless-offline
serverless-plugin-split-stacks
serverless-plugin-custom-roles
serverless-domain-manager
serverless-s3-deploy
serverless-plugin-tracing


```
Regards.
