### ISSUE TITLE
websocket serverless deploy --> You need to set the "route" when using the websocket event.

### ISSUE THREAD

**Issue by AngeloChecked** [serverless/serverless#5962]
Hello everyone,

I downloaded the serverless websocket example [here](https://github.com/serverless/serverless-websockets-plugin/tree/master/example),

i installed package requested 
`npm install`

i created IAM user with permissions:
`AWSLambdaFullAccess` +
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1449904348000",
            "Effect": "Allow",
            "Action": [
                "cloudformation:UpdateStack",
                "cloudformation:CreateStack",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResource",
                "cloudformation:ValidateTemplate",
                "apigateway:DELETE",
                "apigateway:GET",
                "apigateway:POST",
                "apigateway:PUT",
                "apigateway:GetResources",
                "iam:CreateRole",
                "iam:PutRolePolicy",
                "iam:DeleteRolePolicy",
                "iam:DeleteRole"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

i setted the credentials
`serverless config credentials --provider aws --key AKIAIOSFODNN7EXAMPLE --secret wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY`

i tryed to deploy the example: 
`serverless deploy`

the result is
```bash
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Serverless Error ---------------------------------------

  You need to set the "route" when using the websocket event.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           10.15.1
     Serverless Version:     1.39.1`
```

googling the only link i found about this error is:
 [validate.js](lib/plugins/aws/package/compile/events/websockets/lib/validate.js)

solutions?

**Comment by AngeloChecked** [comment]
solved, i modified the serverless.yml file
```yaml
  connectionManager:
    handler: src/handler.connectionManager
    events:
      - websocket:
          routeKey: $connect
      - websocket:
          routeKey: $disconnect

  # just in case we are getting weird / bad data
  # we can react to it with a sane response
  defaultMessages:
    handler: src/handler.defaultMessage
    events:
      - websocket:
          routeKey: $default

  # handle chat app messages
  sendMessage:
    handler: src/handler.sendMessage
    events:
      - websocket:
          routeKey: sendMessage

  # Channel Subscriptions
  channelManager:
    handler: src/handler.channelManager
    events:
      - websocket:
          routeKey: subscribeChannel
      - websocket:
routeKey: unsubscribeChannel
```
to:

```yaml
connectionManager:
    handler: src/handler.connectionManager
    events:
      - websocket:
        routeKey: $connect
      - websocket:
        routeKey: $disconnect

  # just in case we are getting weird / bad data
  # we can react to it with a sane response
  defaultMessages:
    handler: src/handler.defaultMessage
    events:
      - websocket:
        routeKey: $default

  # handle chat app messages
  sendMessage:
    handler: src/handler.sendMessage
    events:
      - websocket:
        routeKey: sendMessage

  # Channel Subscriptions
  channelManager:
    handler: src/handler.channelManager
    events:
      - websocket:
        routeKey: subscribeChannel
      - websocket:
        routeKey: unsubscribeChannel
```
