### ISSUE TITLE
Editing the Dynamodb Stream event in cloudformation.yml does not overwrite previous stream event

### ISSUE THREAD

**Issue by ajhool** [serverless/serverless#5966]
# This is a Bug Report

## Description
* What went wrong?

I deployed a lambda function with a dynamodb stream and everything worked well. Then, I changed the dynamodb stream and the dynamodb stream ARN changed/updated as a consequence. I updated my `serverless.yml` file with the updated stream ARN. After the change to `serverless.yml`, when I run `serverless deploy --force`, the lambda function still points to the old stream arn, the stream event trigger does not seem to update.

* What did you expect should have happened?

Changing the stream ARN in serverless.yml and redeploying should cause the lambda function to point to the updated stream ARN. It appears to still be pointing to the old/stale stream ARN.

* What was the config you used?

(Please note that the `*** SOME MESSAGE ***` notation is used for placeholders)
```
# serverless.yml
service: myservice # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  role: *** ADD A PERMISSIVE ROLE HERE ***

# you can overwrite defaults here
stage: dev
region: us-east-1

# you can add packaging information here
package:
  include:
    - handler.ts

functions:
  myFunction:
    handler: handler.handler
    role: *** ADD A BASIC EXECUTION ROLE HERE ***
    -stream:
      type: dynamodb
      arn: arn:aws:dynamodb:us-east-1:***MYACCOUNTID***:table/MyTable/stream/2019-03-27T20:56:49.726
      batchSize: 100
      startingPosition: LATEST
      enabled: false
plugins:
  - serverless-plugin-typescript
  - serverless-offline
```

* What stacktrace or error message from your provider did you see?
There is no direct error message, but the error message from using a stale stream arn is:
`Last processing result: PROBLEM: Stream is closed`

Similar or dependent issues:
None found

## Additional Data

* ***Serverless Framework Version you're using***:
1.39.1
* ***Operating System***:
osx 10.13.6
* ***Stack Trace***:
* ***Provider Error messages***:
There is no direct error message, but the error message from using a stale stream arn is:
`Last processing result: PROBLEM: Stream is closed`

**Comment by ajhool** [comment]
Ah, the correct syntax needs an events object, like so:

```
  myFunction:
    handler: handler.handler
    role: *** ADD A BASIC EXECUTION ROLE HERE ***
    events: 
      - stream:
        type: dynamodb
        arn: arn:aws:dynamodb:us-east-1:***MYACCOUNTID***:table/MyTable/stream/2019-03-27T20:56:49.726
        batchSize: 100
        startingPosition: LATEST
        enabled: false
```

Will leave this open because it might still be a bug that serverless does not complain about this bad syntax, but am happy to close it if that reasoning is incorrect!
