### ISSUE TITLE
Always uploading even code and requirements are unchanged

### ISSUE THREAD

**Issue by levFarkas** [serverless/serverless#5969]
I am using ### python-requirements-plugin to dockerize pip to install requirements transparently. 
The problem is that if ### requirements.txt contains at least 1 dependancy, skipping feature does not work. Zip hashes become differently, whenever I use packaging.
Always uploading takes too much time.
Here is my yml:

```
service: touch-event-save # NOTE: update this with your service name
package:
  exclude:
    - venv/**
    - .idea/**

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  accountId: '#{AWS::AccountId}'
  touchEventDataTableName: ${opt:touchEventDataTableName, 'touch_event_data'}
  touchEventDataTableArn: arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.touchEventDataTableName}
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource: ${self:custom.touchEventDataTableArn}

  environment:
    TOUCH_EVENT_DATA_TABLE_NAME: ${self:custom.touchEventDataTableName}
    TOUCH_EVENT_DATA_REGION: ${self:provider.region}

functions:
  save:
    handler: handler.run

```
What went wrong?
If I remove `dockerizePip: non-linux` it works correctly,  but thats unusable for us, we have to use docker.  

Update:
S3 zip and local file have the same content 
Thank you for your answer
