### ISSUE TITLE
Deploy fails to warn or error on empty AWS schedules

### ISSUE THREAD

**Issue by Ray-B** [serverless/serverless#5978]
# This is a Bug Report

## Description

* What went wrong? 

sls deploy was run, and failed to warn/error on an empty schedule being defined.

It looks like the issue results from the YAML. Both examples provided below are valid yaml as per spec, but the bottom example will result in serverless ignoring the defined schedule / seeing it as empty, and failing to create the correct resources, but still report as successful. 

This is problematic because it's a _very_ easy mistake to make, and insidious to debug..."why is this resource missing if sls is saying everything deployed ok?"

* What did you expect should have happened? 

I would have expected at a minimum a warning, and preferably a way to 'treat warnings as errors';

* What was the config you used?

_Will create the expected # of resources_
```yaml
functions:
  updatePlumbus:
    name: updatePlumbus-production
    handler: src/handler.updatePlumbus
    description: Updates the plumbus for the production environment
    reservedConcurrency: 1 
    events:
      - schedule:
          name: replicon-production-release-plan-gen
          description: 'Triggers the update of the plumbus'
          rate: rate(5 minutes)
```

_Will create **incorrect** # of resources (notice the indentation difference in the schedule)_
```yaml
functions:
  updatePlumbus:
    name: updatePlumbus-production
    handler: src/handler.updatePlumbus
    description: Updates the plumbus for the production environment
    reservedConcurrency: 1 
    events:
      - schedule:
        name: replicon-production-release-plan-gen
        description: 'Triggers the update of the plumbus'
        rate: rate(5 minutes)
```

* What stacktrace or error message from your provider did you see?

_Log result when **incorrect #** of resources are created (should be 7 resources created for a basic aws lambda with a schedule):_

```log Serverless: Checking Stack update progress...
.........
Serverless: Stack update finished...
Service Information
service: updatePlumbus
stage: prod
region: us-west-2
stack: updatePlumbus-prod
resources: 5
api keys:
 None
endpoints:
 None
functions:
 updatePlumbus: updatePlumbus-prod-updatePlumbus
layers:
 None
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.38.0
* ***Operating System***: ubuntu
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by exoego** [comment]
```yaml
- schedule:
    name: production-plumbusScheduler
    description: 'Triggers the update of the plumbus'
    rate: rate(5 minutes)
```

is correct. `schedule` property should have attributes. It is same as below (json)

```javascript
{
  schedule: {
    name: 'production-plumbusScheduler',
    description: 'Triggers the update of the plumbus',
    rate: 'rate(5 minutes)'
  }
}
```

```yaml
- schedule:
   name: production-plumbusScheduler
   description: 'Triggers the update of the plumbus'
   rate: rate(5 minutes)
```

is incorrect. It is same as below in json

```javascript
{
  schedule: {},
  name: 'production-plumbusScheduler',
  description: 'Triggers the update of the plumbus',
  date: 'rate(5 minutes)'
}
```

where `schedule` is empty.
