### ISSUE TITLE
Api gateway will be deleted after use share restapi id with original service

### ISSUE THREAD

**Issue by kog-7** [serverless/serverless#5984]
# This is a Bug Report

## Description

apigateway will be deleted after i use share restapi id with original service,this service is for the first lambda service which create the apigateway  restapi id

**Comment by allanchua101** [comment]
Hi @kog-7,

You can fix this problem by deploying your API gateway in a separate service to prevent deletion of an attached function:

## Gateway as a Service
```yml
service: eshop-gateway
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  stage: prod
resources:
  Resources:
    EShopGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: EShopGW
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: EShopGW
      Export:
        Name: EShopGW-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - EShopGW
          - RootResourceId
      Export:
        Name: EShopGW-rootResourceId
```

## Attaching a function

```yml
service: eshop-products
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  stage: prod
  apiGateway:
    restApiId:
      "Fn::ImportValue": EShopGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": EShopGW-rootResourceId
functions:
  get-products:
    handler: handler.getProducts
    events:
      - http:
          path: products/list
          method: get
```

You can view a full sample [here](https://github.com/allanchua101/api-gateway-comparables/tree/master/004_AWS_Lambda)
