### ISSUE TITLE
SLS commands hanging completely

### ISSUE THREAD

**Issue by justjoeyuk** [serverless/serverless#5985]
# This is a Bug Report

## Description
All the SLS commands are failing. I've tried it on two machines with different versions. One being the latest, one being 1.32.0. SLS is the only command that's working. `sls credentials configure` even hangs. It seems to have happened after the clocks changed by an hour.

* What went wrong?
It just hangs indefinitely.

* What did you expect should have happened?
The commands should be executing successfully.

* What was the config you used?
A yaml file that has worked fine for months.

* What stacktrace or error message from your provider did you see?
None.

Similar or dependent issues:
N/A

## Additional Data
N/A

* ***Serverless Framework Version you're using***: 1.32.0 / @latest
* ***Operating System***: Linux Mint / Windows WSL
* ***Stack Trace***: None
* ***Provider Error messages***: None

**Comment by justjoeyuk** [comment]
It looks like AWS is having lambda API issues.. so I'll track this and close the ticket if it starts working again. European zone. https://status.aws.amazon.com/

**Comment by justjoeyuk** [comment]
AWS have resolved the Lambda API issues and I'm still getting this issue. I've left it up.

**Comment by eahefnawy** [comment]
@justjoeyuk does that happen with the latest version as well?

>  It seems to have happened after the clocks changed by an hour.

I think I faced this issue long time ago. Had something to do with the aws api keys being out of sync. If i remember correctly, I fixed it by correctly syncing the time. Could you try that?

Ref:
https://superuser.com/questions/155785/mac-os-x-date-time-synchronization

**Comment by justjoeyuk** [comment]
@eahefnawy Not working. If I checkout the hello-world example, it works and uploads... I've not changed the yml in weeks, although it's my suspicion that it's the only thing that could be messing up. Almost no commands work and --verbose does nothing.

**Comment by justjoeyuk** [comment]
```
service: booking-service

custom:
  stage: ${opt:stage, self:provider.stage}
  authorizer:
    arn: arn:aws:lambda:eu-west-1:<redacted>:function:auth-service-${self:custom.stage}-authenticate-user
    type: request
    resultTtlInSeconds: 0
    identitySource: method.request.header.Authorization
  cors:
    origin: "*"
    headers:
      - Access-Control-Allow-Origin
      - Content-Type
      - Authorization
      - x-tabb-place
    allowCredentials: false
  env:
    DB_HOST:
      prod: "<redacted>"
      dev: "<redacted>"
    VENUE_FUNCTION_NAME:
      prod: "venue-service-prod-get-details"
      dev: "venue-service-dev-get-details"
    IQOS_ADD_LEAD_FUNCTION_NAME:
      prod: "iqos-service-prod-add-lead"
      dev: "iqos-service-dev-add-lead"
    STRIPE_KEY:
      prod: <redacted>
      dev: <redatcted>
    BOOKING_CREATED_ANS_TOPIC:
      prod: "arn:aws:sns:eu-west-1:<redacted>:booking-created-prod"
      dev: "arn:aws:sns:eu-west-1:<redacted>:booking-created-dev"
    PENDING_BOOKING_CREATED_ANS_TOPIC:
      prod: "arn:aws:sns:eu-west-1:<redacted>:pending-booking-created-prod"
      dev: "arn:aws:sns:eu-west-1:<redacted>:pending-booking-created-dev"
    PENDING_BOOKING_UPDATED_ANS_TOPIC:
      prod: "arn:aws:sns:eu-west-1:<redacted>:pending-booking-updated-prod"
      dev: "arn:aws:sns:eu-west-1:<redacted>:pending-booking-updated-dev"
    WEB_APP_URL:
      prod: "https://tabb.app"
      dev: "https://staging.tabb.app"

provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: go1.x
  region: eu-west-1
  environment:
    DB_HOST: ${self:custom.env.DB_HOST.${self:custom.stage}}
    VENUE_FUNCTION_NAME: ${self:custom.env.VENUE_FUNCTION_NAME.${self:custom.stage}}
    IQOS_ADD_LEAD_FUNCTION_NAME: ${self:custom.env.IQOS_ADD_LEAD_FUNCTION_NAME.${self:custom.stage}}
    STRIPE_KEY: ${self:custom.env.STRIPE_KEY.${self:custom.stage}}
    BOOKING_CREATED_ANS_TOPIC: ${self:custom.env.BOOKING_CREATED_ANS_TOPIC.${self:custom.stage}}
    PENDING_BOOKING_CREATED_ANS_TOPIC: ${self:custom.env.PENDING_BOOKING_CREATED_ANS_TOPIC.${self:custom.stage}}
    PENDING_BOOKING_UPDATED_ANS_TOPIC: ${self:custom.env.PENDING_BOOKING_UPDATED_ANS_TOPIC.${self:custom.stage}}
    WEB_APP_URL: ${self:custom.env.WEB_APP_URL.${self:custom.stage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:eu-west-1:<redacted>:function:venue-service-dev-get-details"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:eu-west-1:<redacted>:function:venue-service-prod-get-details"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:eu-west-1:<redacted>:function:iqos-service-dev-add-lead"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:eu-west-1:<redacted>:function:iqos-service-prod-add-lead"

    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "${self:custom.env.BOOKING_CREATED_ANS_TOPIC.${self:custom.stage}}"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "${self:custom.env.PENDING_BOOKING_CREATED_ANS_TOPIC.${self:custom.stage}}"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "${self:custom.env.PENDING_BOOKING_UPDATED_ANS_TOPIC.${self:custom.stage}}"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  calculate-deposit:
    handler: bin/calculate-deposit/calculate-deposit
    events:
      - http:
          path: calculate-deposit
          method: post
          cors: ${self:custom.cors}
  get-pending-bookings:
    handler: bin/get-pending-bookings/get-pending-bookings
    events:
      - http:
          path: pending
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  fetch-bookings:
    handler: bin/fetch-bookings/fetch-bookings
    events:
      - http:
          path: fetch-bookings
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  fetch-iqos-bookings:
    handler: bin/fetch-iqos-bookings/fetch-iqos-bookings
    events:
      - http:
          path: fetch-iqos-bookings
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  search-bookings:
    handler: bin/search-bookings/search-bookings
    events:
      - http:
          path: search-bookings
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  create-booking:
    handler: bin/create-booking/create-booking
    events:
      - http:
          path: create-booking
          method: post
          cors: ${self:custom.cors}
  refund-booking:
    handler: bin/refund-booking/refund-booking
    events:
      - http:
          path: refund-booking
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  delete-booking:
    handler: bin/delete-booking/delete-booking
    events:
      - http:
          path: delete-booking
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  create-pending-booking:
    handler: bin/create-pending-booking/create-pending-booking
    events:
      - http:
          path: create-pending-booking
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  send-booking-reminder:
    handler: bin/send-booking-reminder/send-booking-reminder
    events:
      - http:
          path: send-booking-reminder
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  update-booking:
    handler: bin/update-booking/update-booking
    events:
      - http:
          path: update-booking
          authorizer: ${self:custom.authorizer}
          method: post
          cors: ${self:custom.cors}
  fetch-payment-source:
    handler: bin/fetch-payment-source/fetch-payment-source
    events:
      - http:
          path: fetch-payment-source
          method: post
          cors: ${self:custom.cors}
resources:
  Resources:
    4xxGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    5xxGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

```
