### ISSUE TITLE
invoke local docker layer download caching is broken

### ISSUE THREAD

**Issue by endeepak** [serverless/serverless#5990]
# This is a Bug Report

## Description

* What went wrong?
Importing a layer during `invoke local --docker` works in first run and fails in subsequent runs

The issue is due to code mentioned in https://github.com/serverless/serverless/pull/5863/files#r271205741

Code Link: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/index.js#L262

* What did you expect should have happened?
Importing a layer during `invoke local --docker` should work in all runs

* What was the config you used?
`serverless.yml`
```yml
service: layer-cache-bug

provider:
  name: aws
  runtime: python2.7

functions:
  hello:
    handler: handler.hello
    layers:
      - <your-layer-arn-here>
```

`handler.py`
```py
import your_layer

def hello(event, context):
    return "hello"
```

* What stacktrace or error message from your provider did you see?
```
Traceback (most recent call last):
  File "/var/task/handler.py", line 1, in <module>
    import your_layer
ImportError: No module named your_layer
```

Similar or dependent issues: None

## Additional Data

* ***Serverless Framework Version you're using***: 1.40.0
* ***Operating System***: darwin
* ***Stack Trace***: Added Above
* ***Provider Error messages***: Added Above
