### ISSUE TITLE
Sls tries to create S3 bucket twice if a Lambda function is subscribed to S3 events

### ISSUE THREAD

**Issue by mushketyk** [serverless/serverless#6001]
# This is a Bug Report

## Description

I have an S3 bucket that is created by `serverless` and I want to subscribe a Lambda function to events from this bucket. No external resources are used.

* What went wrong?

`serverless` generates two resources in CloudFormation JSON to create two buckets with *the same name*.

* What did you expect should have happened?

`serverless` should attach an event to an existing bucket instead of attempting to create a bucket twice.

* What was the config you used?

```yml
provider:
  name: aws
  runtime: nodejs8.10

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    S3_BUCKET: my-bucket-name-${opt:stage, self:provider.stage}

functions:
    SendUploadNotifications:
    handler: functions/s3/sendNotifications.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*

resources:
   ImagesBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
```

* What stacktrace or error message from your provider did you see?

```
An error occurred: S3BucketServerless - serverless-app already exists in stack arn:aws:cloudformation:us-east-1 ...
```

Similar or dependent issues:
* #4284
* #1891

But this one seems different since the bucket is already managed by the serverless.yml and it should be reused.

## Additional Data

* ***Serverless Framework Version you're using***: `serverless@1.40.0`
* ***Operating System***: macOs Mojave 10.14.4
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by chekalsky** [comment]
Resolution is to make s3 bucket `existing: true`:

```
...
functions:
    SendUploadNotifications:
    handler: functions/s3/sendNotifications.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
...
```
