### ISSUE TITLE
Multiple Issues with Layers + Node Modules

### ISSUE THREAD

**Issue by iq-dot** [serverless/serverless#6005]
# This is a Bug Report

## Description

I am having various issues trying to get a layer with node_modules which is shared by several functions in my serverless file.

I have tried first creating a layer with just node_modules, however due to how the layer is extracted in /opt my functions can not find node_modules.

I tried to set the NODE_PATH but it overwrites the existing NODE_PATH leading to other errors, I could not find any way to append, is there a way?

I then tried to created a 'nodejs' folder to match the directory structures of where layers are searched for, however I can not use package exclude I get the error 'No file matches include / exclude patterns'.

Here is my config with the relevant option:

```
layers:
  analyticsShared:
    path: nodejs
    name: analytics-shared-${opt:stage, self:provider.stage}
    description: "Shared node modules for analytics"

package:
  exclude:
    - node_modules/**
    - nodejs/**

functions:
  track:
    handler: analytics.queue
    timeout: 30
    layers:
      - {Ref: AnalyticsSharedLambdaLayer}
```

I tried using node_modules directly without package exclude and symlink but I need a way to append to the NODE_PATH.

There seems to be multiple issues with tryings to get node_modules as a layer, is there a documented way to get this working or are these known issues?

## Additional Data

* ***Serverless Framework Version you're using***:  1.4
* ***Operating System***: Mac OSX
