### ISSUE TITLE
Load plugin from path

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#6017]
# This is a Feature Proposal

## Description

At the moment we can load plugins like this:

```yaml
plugins:
  - plugin1
  - plugin2
```

or in a specific directory:

```yaml
plugins:
  localPath: './custom_serverless_plugins'
  modules:
    - plugin1
    - plugin2
```

However this changes the directory for all plugins.

It would be very useful to be able to include a module using a relative path:

```yaml
plugins:
  - plugin1
  - plugin2
  - src/foo/bar/plugin3
```

## Use case

My use case is that I want to distribute my plugin without NPM (it is a plugin for a serverless PHP framework, so the plugin will be distributed with the rest of the PHP source code). Because of that I want users to be able to include the plugin, yet don't mess up their "localPath" just for this specific plugin.
