### ISSUE TITLE
Is there a way to create events when deploying functions individually?

### ISSUE THREAD

**Issue by LF4ce** [serverless/serverless#6021]
I've noticed that in my current settings my events are not being created when deploying functions individually. It only works if I do a full deploy.

Is there something I'm missing or this is the only way to have events created?

The deploy command I'm running is:
`serverless deploy function -f place-holder --stage staging`

My serverless.yml looks like this:
```
plugins:
  - serverless-webpack
service: etl
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment: ${file(env-${self:provider.stage}.yml)}
functions:
  place-holder:
    handler: etl/place-holder/index.handler # reference the file and exported method
    events:
      - schedule: rate(1 day)
    package:
      individually: true
```
