### ISSUE TITLE
Custom Authorizer not getting created and connection handler is not working

### ISSUE THREAD

**Issue by loganathan-s** [serverless/serverless#6024]
# This is a Bug Report

## Description

I configured an existing authorizer lambda function in front of a WebSocket connection function.  But the API gateway doesn't link the existing authorizer into the WebSocket API gateway. 

Even I create the authorizer manually from the AWS user interface, the authorizer/connectionHandler functions is not getting called and my connections are always successful irrespective of any errors.

### serverless.yml

```
functions:
  connectionHandler:
    handler: src/WebsocketServer/WebsocketServer.connectionHandler
    events:
      - websocket:
        route: $connect
        authorizer:
          name: arn:aws:lambda:us-east-1:xxxxx:function:authentication-dev-authenticated
          identitySource:
            - 'route.request.querystring.token'
      - websocket:
        route: $disconnect
  defaultHandler:
    handler: src/WebsocketServer/WebsocketServer.defaultHandler
    events:
      - websocket: $default #simple event definition without extra route property
  messageHandler:
    handler: src/WebsocketServer/WebsocketServer.messageHandler
    events:
      - websocket:
          route: message
```

### Connection Handler:

```
module.exports.connectionHandler = async (event, context) => {
  console.log('$connect Triggered');
  const payload = JSON.parse(event.body);
  console.log(event.requestContext.connectionId);
  console.log('$connect Triggered');
  return success;
};
```

Similar or dependent issues:
* #5942

## Additional Data

* ***Serverless Framework Version you're using***: 1.40.0
* ***Operating System***: Mac

**Comment by grvhi** [comment]
I am also experiencing this bug. In my case, switching from:
```
events:
      - websocket: $disconnect
      - websocket: $default
      - websocket: $connect
```
To:
```
events:
      - websocket: $disconnect
      - websocket: $default
      - websocket:
          route: $connect
          authorizer: my-authorizer
```
Results in the `cloudformation-template-update-stack.json` file completely omitting the `$connect` route, hence the $connect route is not wired up to the authorizer function. So it would seem that using the extended format causes the route not to be rendered into the Cloudformation template.
