### ISSUE TITLE
Invoke local with custom runtime fails because unable to unzip whole package

### ISSUE THREAD

**Issue by marcinczeczko** [serverless/serverless#6028]
# This is a Bug Report
Invoke local with docker fails because of ZIP with folders

## Description
* What went wrong?
When running `sls invoke local --docker -f hello` I'm getting the error
```
Error: ENOENT: no such file or directory, open '.serverless/invokeLocal/artifact/lib/org.jboss.slf4j.slf4j-jboss-logging-1.1.0.Final.jar'
    at zip.files.(anonymous function).async.then.fileData (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:309:23)
    at runNextTicks (internal/process/next_tick.js:47:5)
    at processImmediate (timers.js:610:7)
    at process.topLevelDomainCallback (domain.js:126:23)
```
It's due to the fact the function zip consists a subfolders, the zip contents is as follows:
```
├── amazon-lambda-dynamodb-1.0-SNAPSHOT-runner.jar
├── bootstrap
└── lib
    ├── some.jar
    ├── other.jar
```
If checked `.serverless` folder you can find that only top level jar & bootstrap file is extracted
```
.serverless
├── invokeLocal
│   ├── Dockerfile
│   └── artifact
│       ├── amazon-lambda-dynamodb-1.0-SNAPSHOT-runner.jar
│       └── bootstrap
```
* What did you expect should have happened?
Zip is extracted and docker started

* What was the config you used?
```
service: hello-lambda

provider:
  name: aws
  runtime: provided
  stage: dev
  region: eu-central-1

package:
  artifact: target/amazon-lambda-dynamodb-1.0-SNAPSHOT.zip

functions:
  hello:
    handler: handler
    events:
      - http:
          method: get
          path: user
```
* What stacktrace or error message from your provider did you see?
See above

## Additional Data
* ***Serverless Framework Version you're using***: 1.14.0
* ***Operating System***: MacOS
* ***Stack Trace***: see above
* ***Provider Error messages***:
