### ISSUE TITLE
[Windows] Deployment skipped irregularily if package.artifact contains "/" and versionFunction is false

### ISSUE THREAD

**Issue by exoego** [serverless/serverless#6030]
# This is a Bug Report

## Description

* What went wrong?
Deployments (`sls deploy`) are skipped irregularily (sometimes success) even if exteranal artifact (zip file) is updated.
It seems that serverless fail to handle `/` in artifact path on Windows when checking timestamp of artifact.

* What did you expect should have happened?
Deployment skipping algorithm should consider timestamp of external artifact regardless of path separator

* What was the config you used?

```yaml
service: "example"
provider:
  name: "aws"
  versionFunctions: false
  deploymentBucket:
    name: "MY-SERVERLESS-BUCKET-NAME-HERE"
  runtime: "nodejs8.10"
functions:
  getFooBar:
    handler: "handler.getFooBar"
    events:
    - http:
        path: "/foo/{bar}"
        method: "get"
package:
  # we use this configuration on Windows & Linux
  artifact: "../../target/lambda.zip"
```
* What stacktrace or error message from your provider did you see?
N/A
* Similar or dependent issues:
N/A

## Additional Data
* Terminal: `git-bash (bash 4.4.19)` on Windows 10.
* ***Serverless Framework Version you're using***: `1.40.0`
* ***Operating System***: Windows 10 (this issue occurs) & Linux (No problem)
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
