### ISSUE TITLE
Feature request: variable property names in serverless.yml

### ISSUE THREAD

**Issue by uclaeagit** [serverless/serverless#6032]
Hi, this issue comes into play with lambda layers combined with branches for different environments. Sorry if there's an easy fix for this, but I haven't found anything.

We have a dev branch and a stage branch for our lambda layers. Unfortunately I can't inject these variables like I need to, because these are properties (not values) in serverless.yml.

Here's dev:
```
layers:
  dplibdev:
    name: ${self:provider.stage}-dplib # optional, Deployed Lambda layer name
...
resources:
  Outputs:
    DplibdevLayerExport:
      Value:
        Ref: Dplib${self:provider.stage}LambdaLayer
      Export:
        Name: Dplib${self:provider.stage}LambdaLayer
```

And here's stage:
```
layers:
  dplibstage:
    name: ${self:provider.stage}-dplib # optional, Deployed Lambda layer name
...
resources:
  Outputs:
    DplibstageLayerExport:
      Value:
        Ref: Dplib${self:provider.stage}LambdaLayer
      Export:
        Name: Dplib${self:provider.stage}LambdaLayer
```

So how this plays out is I need a separate serverless.yml file for each branch, and in my CI/CD, I rename that file to serverless.yml to deploy. Maybe I'm missing something but this seems less than ideal.
