### ISSUE TITLE
sls package doesn't work without AWS credentials

### ISSUE THREAD

**Issue by koterpillar** [serverless/serverless#6034]
# This is a Bug Report

## Description

* What went wrong?

Performing `sls package` of a function configured to receive AWS Lambda API Gateway events without having valid AWS credentials fails with "AWS provider credentials not found."

* What did you expect should have happened?

`sls package` creating the required deployment artifacts even when no AWS credentials are present in the environment. This was working prior to v1.41.0.

* What was the config you used?

Relevant parts:

```
provider:
  name: aws
  runtime: nodejs8.10

functions:
  apigw:
    handler: test
    events:
      - http:
          path: hello/{name}
          method: get
```

* What stacktrace or error message from your provider did you see?

```
  Serverless Error ---------------------------------------
 
  AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.
```

Similar or dependent issues:
* https://github.com/serverless/serverless/issues/6029#issuecomment-484929852 describes a similar issue but doesn't appear to be related to the problem originally stated in #6029.

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.0
* ***Operating System***: Linux
* ***Stack Trace***: none provided
* ***Provider Error messages***:

```
AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>.
```
