### ISSUE TITLE
Using a variable for Seconds in Wait Type of a State in aws-step-function fails while deploy 

### ISSUE THREAD

**Issue by g-g-n** [serverless/serverless#6041]
**What went wrong?**
When trying to use a variable for Seconds attribute in the Wait type of State in aws-step function, then the deploy command fails with below error:

_Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Expected value of type Integer at /States/WaitTill/Seconds_

Also checked that the generated CFT json puts a double-quote around the variable. 

**What did you expect should have happened?**
The deploy should have gone through successfully. Tried by putting a hardcoded value for the Seconds attribute, like 60 and it works fine. 

**What was the config you used?**
serverless.yml:

```
service: test-service

provider:
  name: aws
  runtime: python3.7

functions:
  decide-seconds-to-wait:
    handler: handler.decide_seconds_to_wait
    description: Decide the wait time based on certain things

stepFunctions:
  stateMachines:
      definition:
        StartAt: DecideSecondsToWait
        States:          
          DecideSecondsToWait:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-decide-seconds-to-wait
            TimeoutSeconds: 10
            "ResultPath": "$.Result"    
            Next: WaitTill      
          WaitTill:
            Type: Wait
            Seconds: $.Result.seconds_to_wait
            #Seconds: 60
            Next: EndState
          EndState:
            Type: Succeed 
plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-python-requirements

```

**Additional Data**
_Serverless Framework Version you're using_: 1.38.0
_Operating System_: MacOS Mojave v 10.14.4
_Stack Trace_: N/A
_Provider Error messages_: See above
