### ISSUE TITLE
Allow Fn::Join in stream event source

### ISSUE THREAD

**Issue by Tybot204** [serverless/serverless#6047]
# This is a Feature Proposal

## Description

I have a use case where I want to configure a lambda to read from a Kinesis stream with a different ARN based on account ID. This lambda will be deployed across different staging and production environments, and using the built in references for account ID simplifies config greatly.

Example config wanted:
```yml
events:
  - stream
      type: kinesis
      arn:
        Fn::Join:
          - ":"
          - - arn
            - aws
            - kinesis
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - MyOtherKinesisStream
```

This is currently not possible because of a filter only allowing the `Fn::GetAttr` and `Fn::ImportValue` methods to be used in stream event definitions.

Similar or dependent issues:

This is almost identical to an issue raised last year for SQS event sources.
* https://github.com/serverless/serverless/issues/5345

Following the PR (https://github.com/serverless/serverless/pull/5351) closing the above issue, I have a fork with the necessary changes ready to create a PR off of if there is a want for this feature: https://github.com/serverless/serverless/compare/master...Tybot204:master
