### ISSUE TITLE
Multiple methods per function

### ISSUE THREAD

**Issue by AlexeyPlodenko** [serverless/serverless#6056]
# This is a Feature Proposal

## Description

* I would like to list multiple methods per functions, instead of copy-pasting each function's configuration for each method separately. I am aware of using ANY for this purpose. But this seems to be an overkill for the situations when I need to handle only GET and POST.
* Possible config. may look like that:
```YML
functions:
  stats:
    handler: src/endpoints/stats.handler
    events:
      - http:
          path: stats
          method: get,post # <---- HERE
          cors: true
```
or
```YML
functions:
  stats:
    handler: src/endpoints/stats.handler
    events:
      - http:
          path: stats
          methods: # <---- HERE
            - get
            - post
          cors: true
```
Internally this may unfold into the same FaaS config. as copy-pasting method would generate. But as a lazy dev. I do not want to think about that in the configuration file.

If there is a way to do it, please suggest.

Thank you.
