### ISSUE TITLE
Existing URLs Return 500 After Moving From Lambda Per Route To Single Lambda With {proxy+}

### ISSUE THREAD

**Issue by onebytegone** [serverless/serverless#6058]
# This is a Bug Report

## Description

* What went wrong?
   * When "merging" existing functions with distinct routes into a new function that uses `{proxy+}` (à la [Lambda API][lambda-api], [`lambda-express`][lambda-express]), the preexisting APIGW routes (i.e. URLs that worked before the deploy of the merged function) will return a 500 after the first deploy. Once the stack is redeployed with `--force`, the preexisting URLs will start to work normally again. 

   [lambda-api]: https://github.com/jeremydaly/lambda-api
   [lambda-express]: https://github.com/silvermine/lambda-express
* What did you expect should have happened?
   * That calls to URLs on the old routes would work on the first deploy of the consolidated function as `{proxy+}` should match all routes.
* What was the config you used?
   * See [Steps to Reproduce Issue](#steps-to-reproduce-issue)
* What stacktrace or error message from your provider did you see? 
   * None
* Why does this happen? 
   * When an APIGW deployment is created, the [deployment saves an API summary for the current resources][apisummary] (i.e. `AWS::ApiGateway::Resource`). When the APIGW resources in the serverless.yml are changed (e.g. route is renamed or added), a new APIGW deployment is created. With the current order of events, CloudFormation will create the new APIGW deployment when both the old APIGW resources and the new APIGW resources exist. This means if you have a deployed route of `/ping` and rename it to `/another-ping`, after the first deployment with the new route, both `/ping` and `/another-ping` will work (because the Lambda function that served the old route still exists and is called) – even though your serverless.yml file no longer specifies that `/ping` should work. However, when deploying a stack that deletes the old functions and creates a new function to handle all the existing routes, the function(s) for the old APIGW resources no longer exist. Therefore, the old routes will 500 until force deploying again, thus removing the old APIGW resources that pointed to the deleted functions.

   [apisummary]: https://docs.aws.amazon.com/apigateway/api-reference/resource/deployment/#apiSummary

   * Order of events:
      1. Preexisting API:

         ```
         - AWS::Lambda::Function (Ping)
         - AWS::ApiGateway::Resource (`/ping`)
         - AWS::ApiGateway::Deployment (DeploymentA)
         - AWS::ApiGateway::Deployment A
            - `/ping` routes to:
               - "Ping" Lambda Fn
         ```

      1. Developer deploys new API, replacing `Ping` lambda with `API` lambda with `{proxy+}`:

         ```
         - AWS::Lambda::Function (API)
         - AWS::ApiGateway::Resource (`/{proxy+}`)
         - AWS::ApiGateway::Deployment (DeploymentB)
            - `/ping` routes to:
               - "Ping" Lambda Fn that no longer exists, causing 500
            - `/{proxy+}` routes to:
               - "API" Lambda Fn
         ```

      1. Developer redeploys API with `--force`:

         ```
         - AWS::Lambda::Function (API)
         - AWS::ApiGateway::Resource (`/{proxy+}`)
         - AWS::ApiGateway::Deployment (DeploymentC)
            - `/{proxy+}` routes to:
               - "API" Lambda Fn
         ```
* Is this actually a serverless framework issue?
   * Maybe. The root cause of the issue appears to be the order of operations that CloudFormation uses creates the APIGW resources and deployments. As such, this might be something that needs to be passed upstream to the AWS teams. However, for a user of the serverless framework, this is unexpected and potentially dangerous behavior. In the case the behavior of CloudFormation and APIGW are correct, perhaps there is is something that serverless can do to reduce the risk, either by deploying in a way that prevents this issue or a least warns the developer of the issue.

Similar or dependent issues:
* #3785 (possibly)

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: n/a
* ***Stack Trace***: n/a
* ***Provider Error messages***: n/a

## Steps to Reproduce Issue

1. Deploy a new stack that contains a Lambda function with an API Gateway event. (source: [apigw-deployment-example-function-per-route.zip](https://github.com/serverless/serverless/files/3121761/apigw-deployment-example-function-per-route.zip))

   ```yml
   service: apigw-deployment-example

   provider:
      name: aws
      runtime: nodejs8.10

   functions:
      ping:
         handler: index.handler
         memorySize: 128
         timeout: 1
         events:
            - http: 'GET /ping'
   ```

1. Note the API Summary for the API Gateway deployment:

   ```
   $ aws apigateway get-deployments --rest-api-id bxttwudvs0
   {
      "items": [
         {
            "id": "fb4m1s",
            "createdDate": 1556225573
         }
      ]
   }
   $ aws apigateway get-deployment --rest-api-id bxttwudvs0 --deployment-id fb4m1s  --embed apisummary
   {
      "apiSummary": {
         "/ping": {
            "GET": {
               "apiKeyRequired": false,
               "authorizationType": "NONE"
            }
         }
      },
      "id": "fb4m1s",
      "createdDate": 1556225573
   }
   ```

1. Redeploy the stack with an update that replaces the `ping` function with a new function that accepts all requests (i.e. `/{proxy+}`) (source: [apigw-deployment-example-single-function-api.zip](https://github.com/serverless/serverless/files/3121764/apigw-deployment-example-single-function-api.zip))

   ```yml
   service: apigw-deployment-example

   provider:
      name: aws
      runtime: nodejs8.10

   functions:
      api: # NOTE: This function takes the place of the previous "ping" function
         handler: index.handler
         memorySize: 128
         timeout: 1
         events:
            - http: 'GET /{proxy+}'
   ```

1. Note the API Summary for the API Gateway deployment contains the original `/ping` and new `/{proxy+}` paths:

   ```yml
   $ aws apigateway get-deployments --rest-api-id bxttwudvs0
   {
      "items": [
         {
            "id": "mt8dc7",
            "createdDate": 1556225799
         }
      ]
   }
   $ aws apigateway get-deployment --rest-api-id bxttwudvs0 --deployment-id mt8dc7  --embed apisummary
   {
      "apiSummary": {
         "/{proxy+}": {
            "GET": {
               "apiKeyRequired": false,
               "authorizationType": "NONE"
            }
         },
         "/ping": {
            "GET": {
               "apiKeyRequired": false,
               "authorizationType": "NONE"
            }
         }
      },
      "id": "mt8dc7",
      "createdDate": 1556225799
   }
   ```

1. Observe that the original `/ping` path does not work (even though it should with the proxy resource) and a request to another path works.

   ```
   $ curl https://bxttwudvs0.execute-api.us-east-1.amazonaws.com/dev/ping
   {"message": "Internal server error"}
   $ curl https://bxttwudvs0.execute-api.us-east-1.amazonaws.com/dev/some-other-url
   {"pong":1556225924542}
   ```

1. Redeploy the stack using `--force`

1. Note the API Summary for the API Gateway deployment only contains the `/{proxy+}` path.

   ```
   $ aws apigateway get-deployments --rest-api-id bxttwudvs0
   {
      "items": [
         {
            "id": "p6r9b3",
            "createdDate": 1556225963
         }
      ]
   }
   $ aws apigateway get-deployment --rest-api-id bxttwudvs0 --deployment-id p6r9b3 --embed apisummary
   {
      "apiSummary": {
         "/{proxy+}": {
            "GET": {
               "apiKeyRequired": false,
               "authorizationType": "NONE"
            }
         }
      },
      "id": "p6r9b3",
      "createdDate": 1556225963
   }
   ```

1. Observe that now the original `/ping` path now works.

   ```
   $ curl https://bxttwudvs0.execute-api.us-east-1.amazonaws.com/dev/ping
   {"pong":1556226028157}
   $ curl https://bxttwudvs0.execute-api.us-east-1.amazonaws.com/dev/some-other-url
   {"pong":1556226031913}
   ```

**Comment by shughes-uk** [comment]
Got caught by this today when deploying. Is there a workaround to deploy without interruptions? Deploying and then deploying again with --force might take up to 40 minutes in between in which half my endpoints return 500 errors.

**Comment by onebytegone** [comment]
Unfortunately, the only way I've been able to safely deploy this type of change is with a "per-region" deploy. The basic procedure has been:

1. Divert traffic hitting the API in a given region to a different region
2. Once traffic stops for the given region, deploy the changes to the given region
3. Redeploy with `--force`
4. Smoke test
5. Allow traffic to return to the region
6. Repeat for the remaining regions

Of course the above only works for APIs that are running in multiple regions and treats this as an upgrade that cannot occur with traffic hitting the API.

However, it _might_ be possible to preform the deploy while traffic is hitting the API with the following. Disclaimer: I haven't been test this very thoroughly, so please take with a grain of salt.

1. Update `serverless.yml`:
   - Remove the `http` event from the preexisting lambda function(s), but leave the function(s)
   - Add an `AWS::Lambda::Permission` resource(s) that allows APIGW to invoke the preexisting lambda function(s)
      - This is to replace what Serverless auto-creates for you when using the `http` event
   - Add a new lambda function that uses the `http` event with `{proxy+}` path
   - Using the example from the issue, the serverless.yml should look something like:

      ```yml
      service: apigw-deployment-example

      provider:
         name: aws
         runtime: nodejs8.10

      functions:
         api: # NOTE: This function will take the place of the 'ping' function
            handler: index.handler
            memorySize: 128
            timeout: 1
            events:
               - http: 'GET /{proxy+}'
         ping:
            handler: index.handler
            memorySize: 128
            timeout: 1
            # NOTE: This function used to have an `http` event

      resources:
         Resources:
            PingInvokePermissionForAPIGW:
               Type: 'AWS::Lambda::Permission'
               Properties:
                  Action: 'lambda:InvokeFunction'
                  FunctionName: { 'Fn::GetAtt': [ 'PingLambdaFunction', 'Arn' ] }
                  Principal: 'apigateway.amazonaws.com'
                  SourceArn: { 'Fn::Join': [ '', [ 'arn:', { 'Ref': 'AWS::Partition' }, ':execute-api:', { 'Ref': 'AWS::Region' }, ':', { 'Ref': 'AWS::AccountId' }, ':', { 'Ref': 'ApiGatewayRestApi' }, '/*/*' ] ] }
      ```

2. Deploy
3. Update `serverless.yml`:
   - Remove the original lambda function(s)
   - Remove the manually created `AWS::Lambda::Permission`
4. Deploy again

The basic idea is since APIGW is still trying to invoke the old functions, if the deploy that adds the `{proxy+}` contains the original functions and allows APIGW to invoke them, the 500 errors shouldn't occur (since APIGW can still call these "old" routes). Then on the next deploy (which removes what is causing APIGW to try to invoke the original functions), the original functions and `AWS::Lambda::Permission` can go away. At least that's the theory.
