### ISSUE TITLE
Cloudformation Custom Resource doesn't get called

### ISSUE THREAD

**Issue by jextrevor** [serverless/serverless#6065]
# This is a Bug Report

## Description

* What went wrong?
I created a CloudFormation custom resource that calls one of my serverless lambda functions. When creating the stack for the first time, the lambda associated with the custom resource doesn't get called, and creating the stack hangs.
* What did you expect should have happened?
The lambda associated with the custom resource should have executed correctly.
* What was the config you used?
```
provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    CustomResource:
      Type: Custom::CustomResource
      Properties:
        ServiceToken: !GetAtt HelloLambdaFunction.Arn
```
* What stacktrace or error message from your provider did you see?
Looking into the Cloudwatch logs, it looks like the custom resource starts creation before the HelloLambdaVersion gets created. I thought about using a DependsOn directive with the HelloLambdaVersion, but there isn't a way to retrieve the name of that from the serverless.yml file.

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: Windows 10, build 17134.407
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
