### ISSUE TITLE
`key.startsWith is not a function` when including resources from external files

### ISSUE THREAD

**Issue by rafaelrpinto** [serverless/serverless#6072]
# This is a Bug Report

## Description

* What went wrong?

When deploying a stack which the resources section includes resources from an external file the deployment fails with the following message `key.startsWith is not a function`

* What did you expect should have happened?

The deployment should have succeeded or maybe a meaningful validation error message displayed.

* What was the config you used?

serverless.yml:

```yaml
service: my-test-stack

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:REGION}
  deploymentBucket: ${env:DEPLOYMENT_BUCKET_NAME}

resources:
  Description: Test resources stack
  Resources:
    - ${file(./vpc-test.yml):resources}       
 ```
vpc-test.ym

```yaml
resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.192.0.0/16
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: my-test-vpc
```

* What stacktrace or error message from your provider did you see?

```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: [AWS s3 200 0.839s 0 retries] getBucketLocation({ Bucket: 'my-deployment-bucket' })
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.795s 0 retries] describeStacks({ StackName: 'my-test-stack-unstable' })
Serverless: [AWS s3 200 0.764s 0 retries] listObjectsV2({ Bucket: 'my-deployment-bucket',
  Prefix: 'serverless/my-test-stack/unstable' })
Serverless: [AWS sts 200 0.441s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
 
  Type Error ---------------------------------------------
 
  key.startsWith is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: key.startsWith is not a function
    at _.forEach (/myproject/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:10:15)
    at arrayEach (/myproject/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/myproject/node_modules/lodash/lodash.js:9344:14)
    at Object.normalizeCloudFormationTemplate (/myproject/node_modules/serverless/lib/plugins/aws/lib/normalizeFiles.js:9:7)
    at AwsDeploy.uploadCloudFormationFile (/myproject/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:28:43)
From previous event:
    at AwsDeploy.uploadArtifacts (/myproject/node_modules/serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js:18:8)
From previous event:
    at AwsDeploy.BbPromise.bind.then (/myproject/node_modules/serverless/lib/plugins/aws/deploy/index.js:111:39)
From previous event:
    at Object.aws:deploy:deploy:uploadArtifacts [as hook] (/myproject/node_modules/serverless/lib/plugins/aws/deploy/index.js:107:10)
    at BbPromise.reduce (/myproject/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/myproject/node_modules/serverless/lib/classes/PluginManager.js:408:22)

    at PluginManager.spawn (/myproject/node_modules/serverless/lib/classes/PluginManager.js:426:17)
    at AwsDeploy.BbPromise.bind.then (/myproject/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
    at Object.deploy:deploy [as hook] (/myproject/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:10)
    at BbPromise.reduce (/myproject/node_modules/serverless/lib/classes/PluginManager.js:408:55)
From previous event:
    at PluginManager.invoke (/myproject/node_modules/serverless/lib/classes/PluginManager.js:408:22)
    at PluginManager.run (/myproject/node_modules/serverless/lib/classes/PluginManager.js:439:17)
    at variables.populateService.then (/myproject/node_modules/serverless/lib/Serverless.js:109:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (/myproject/node_modules/serverless/lib/Serverless.js:96:6)
    at serverless.init.then (/myproject/node_modules/serverless/bin/serverless:43:28)
    at /myproject/node_modules/graceful-fs/graceful-fs.js:111:16
    at /myproject/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (/myproject/node_modules/serverless/bin/serverless:43:6)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at /myproject/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/myproject/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.41.1
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: Ubuntu 18.04
* ***Stack Trace***: See above
* ***Provider Error messages***: N/A

**Comment by tobilg** [comment]
I had a similar problem. Try this:

```yaml
service: my-test-stack

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:REGION}
  deploymentBucket: ${env:DEPLOYMENT_BUCKET_NAME}

resources:
  Description: Test resources stack
  - ${file(./vpc-test.yml)}
```

```yaml
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.192.0.0/16
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: my-test-vpc
```
