### ISSUE TITLE
Deploy a new service with tracing.apiGateway enabled fails

### ISSUE THREAD

**Issue by AndreaAdvanon** [serverless/serverless#6081]
# This is a Bug Report

## Description
Trying to deploy a new service with `tracing.apiGateway` enabled fails:
```
An error occurred: ApiGatewayUsagePlan - API Stage not found: ...:dev (Service: AmazonApiGateway; Status Code: 404; Error Code: NotFoundException; Request ID: ...).
```
```
service: some-service

provider:
  name: aws
  tracing:
    lambda: true
    apiGateway: true
  layers:
    - some-layer
  runtime: nodejs8.10
  logRetentionInDays: 30
  apiKeys:
    - ${self:service}-${self:provider.stage}

plugins:
  - serverless-prune-plugin
  - serverless-offline
  - serverless-log-forwarding

functions:
   ...
```
without `apiGateway: true` it works.

## Additional Data

* ***Serverless Framework Version you're using***: 1.41.1
* ***Operating System***: Fedora 29
* ***Stack Trace***:
* ***Provider Error messages***:
