### ISSUE TITLE
Development dependencies of dependencies are included in package when using NPM + Lerna

### ISSUE THREAD

**Issue by tommedema** [serverless/serverless#6090]
# This is a Bug Report

## Description

* What went wrong?
Serverless packages dev dependencies of dependencies when using lerna (without hoisting)

* What did you expect should have happened?
Serverless should not package dev dependencies of dependencies

* What was the config you used?

Run this in the lerna workspace:

```
npm install
npx lerna bootstrap
```

Run this inside a lerna package (not the workspace):
```
npx serverless serverless package --verbose
```

The result is that dev dependencies of dependencies are packaged.

* What stacktrace or error message from your provider did you see?

Similar or dependent issues:
- https://github.com/lerna/lerna/issues/1589

## Additional Data

* ***Serverless Framework Version you're using***:
1.41.1

* ***Operating System***:
MacOS

**Comment by tommedema** [comment]
An ugly and slow workaround I am currently using is to install the `serverless-plugin-scripts` plugin and have it re-install the entire workspace with production only dependencies, then package, and then re-install everything again with all development dependencies too:

serverless.yml
```
plugins:
  - serverless-plugin-scripts

custom:
  scripts:
    scripts:
    hooks:

      # Workaround for https://github.com/serverless/serverless/issues/6090
      # Re-installs lerna mono repo with production dependencies only
      'before:package:createDeploymentArtifacts': cd ../.. && npx lerna clean --yes && npx lerna bootstrap -- --production
      # Restores development dependencies post-packaging
      'after:package:createDeploymentArtifacts': cd ../.. && npx lerna bootstrap
```

Of course this is super slow and error prone, so I hope a real solution can be found.
