### ISSUE TITLE
APi gateway endpoint not deleted after sls remove

### ISSUE THREAD

**Issue by joonhwa** [serverless/serverless#6091]
# This is a Bug Report

## Description

Endpoint still exists in API Gateway stage after running sls remove

Steps to recreate:
1. sls create --template aws-nodejs --path helloService
2. Edit apiGateway key in serverles.yml to point to an existing shared API gateway
3. sls deploy (to stage v1)
4. Invoke function via http endpoint. All is good.
4. sls remove

* What went wrong?
Endpoint still exists in deployed v1 stage. All other API gateway resource  were deleted.

* What did you expect should have happened?
Endpoint should be removed as well. A new deployment should be done to reflect the latest API state

* What was the config you used?
provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs8.10
  apiGateway:
    restApiId: ${ssm:api-gateway-id~true}
    restApiRootResourceId:  ${ssm:root-resource-id~true}
    description: Hello service
  stage: v1

* What stacktrace or error message from your provider did you see?
NA

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***:
1.38.0
* ***Operating System***:
Linux
* ***Stack Trace***:
NA
* ***Provider Error messages***:
NA

**Comment by pmuens** [comment]
Hey @joonhwa thanks for opening :+1:

Not quite sure if I understand what's going on here. Given that you're introducing an external REST API via the `provider` config it's not under direct management by the Serverless Framework. In that case the REST API needs to be managed externally.

**Comment by joonhwa** [comment]
@pmuens  Thanks for replying. Let me clarify a bit more on my issue.

1. I used terraform to spin up an API gateway and put in whatever config i needed. That is all done and good.
2. I wanted to use severless solely for managing functions. sls deploy should deploy function code to lambda and event trigger to the referenced api gateway and sls remove should remove every single trace of everything.
3. When i do sls remove, the lambda code and the API gateway resource were deleted. However, the deployed endpoint in the API stage are not removed. I am still able to access that http endpoint even though the lambda resource backing it has been removed.

During sls deploy, there is a deployment of my API resource to my specified stage. When it comes to sls remove, shouldn't a deployment be made so that the endpoint be removed totally?

**Comment by pillpack-raisch** [comment]
I've also seen this occur with http request events defined in `serverless.yaml` with no `apiGateway ` section. Rolling back to v1.40.0 fixes the issue.

Serverless Framework Version you're using: 1.44.1
Operating System: OSX 10.13.6
Config:
```
service: testservice
provider:
  name: aws
  runtime: nodejs10.x
  stage: gamma
  tags: ...
  logs:
    restApi: true
  environment: ...
  region: us-east-1
  iamRoleStatements: ...
functions:
  entry:
    handler: index.entryPoint
    events:
      - http:
          method: get
          path: /
          cors: true
```
