### ISSUE TITLE
Enhancements for API Gateway REST API log setup

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#6094]
With https://github.com/serverless/serverless/pull/6057 we've added support for API Gateway REST API access logs.

Our main goal was to keep the initial implementation as simple as possible.

With this issue we want to gather more feedback on the required level of configurability. Feel free to join the discussion and discuss what you need when working with API Gateway logs.

**Comment by gootdude** [comment]
please expose the following fields for configuration of the log group and log format

- AWS::Logs::LogGroup
    - Properties
        - LogGroupName
        - RetentionInDays
- AWS::ApiGateway::Stage
    - AccessLogSettings
        - Format

Here's our current serverless.yml that we use to create the log group and set retention time as well as the custom format:

```
resources:
  Resources:
    ABCAccessLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: ABC-${self:provider.stage}
        RetentionInDays: ${file(./config.yml):accessLogRetentionInDays}
    ABCGatewayStage:
      Type: 'AWS::ApiGateway::Stage'
      Properties:
        DeploymentId:
          Ref: __deployment__
        RestApiId:
          Ref: ABCApiGateway
        StageName: ${self:provider.stage}
        TracingEnabled: true
        MethodSettings:
          - HttpMethod: "*"
            ResourcePath: "/*"
            MetricsEnabled: true
            DataTraceEnabled: false
        AccessLogSetting:
          Format: '{"apiId":"$context.apiId","stage":"$context.stage","resourcePath":"$context.resourcePath","requestId":"$context.requestId","awsEndpointRequestId":"$context.awsEndpointRequestId","xrayTraceId":"$context.xrayTraceId","requestTime":"$context.requestTime","requestTimeEpoch":$context.requestTimeEpoch,"httpMethod":"$context.httpMethod","status":"$context.status","path":"$context.path"}'
          DestinationArn:
                Fn::GetAtt:
                  - OneAccessLogGroup
                  - Arn
```
