### ISSUE TITLE
Feature Request: Usage plans for Websockets API

### ISSUE THREAD

**Issue by langep** [serverless/serverless#6096]
# This is a Feature Proposal

## Description

AWS supports setting ApiKeyRequired to true for the $connect route. This is useful specifically when setting the `apiKeySource` value to "AUTHORIZER". Currently, there is no way to add these values from serverless.

My main goal is to connect the WebSockets API Gateway to the same usage plans created for the Rest API and set the ApiKeyRequired value on the $connect route which uses a custom authorizer that will provide the key because browsers don't support setting custom headers.

A possible implementation of setting the ApiKeyRequired value could look as follows.

```
events:
  - websocket:
      private: true
      routeKey: $connect
```

A possible implementation of connecting the usage plan could look as follows.

```
websocketsApiUsagePlans:
  - free
 usagePlan: 
   - free
     quota:
       limit: 5000
       offset: 2
       period: MONTH
     throttle:
       burstLimit: 200
       rateLimit: 100
```

Similar or dependent issues:
* [Issue in old serverless-websocket-plugin](https://github.com/serverless/serverless-websockets-plugin/issues/23)
