### ISSUE TITLE
Missing required key 'restApiId' in params in 1.42.0

### ISSUE THREAD

**Issue by aaronjensen** [serverless/serverless#6100]
# This is a Bug Report

## Description

* What went wrong?

After upgrading to 1.42.0, I can no longer deploy. I get:

```
  Serverless Error ---------------------------------------
 
  Missing required key 'restApiId' in params
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           8.11.4
     Serverless Version:     1.42.0
```

* What did you expect should have happened?

It should have worked like the previous version did.

* What was the config you used?

<details>
<summary>`serverless.yml`</summary>

```
service: my-app-consent

cors: &cors
  origins:
    - '${file(../../packages/dev/config/env.js):env.POWER_UP_URL}'
  headers:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - SPOOF
  allowCredentials: false

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  logRetentionInDays: 14
  apiGateway:
    restApiId: '${file(../../packages/dev/config/env.js):env.REST_API_ID}'
    restApiRootResourceId: '${file(../../packages/dev/config/env.js):env.REST_API_ROOT_RESOURCE_ID}'
  deploymentBucket:
    serverSideEncryption: AES256
  environment:
    AWS_ACCOUNT_ID: '${file(../../packages/dev/config/env.js):env.AWS_ACCOUNT_ID}'
    ENV_NAMESPACE: ${self:custom.namespace}
  iamRoleStatements:
    - Effect: 'Allow'
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.namespace}-userConsents'
      Action:
        - dynamodb:PutItem

plugins:
  - serverless-sentry
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  stage: ${opt:stage, self:provider.stage}
  namespace: my-app-${self:custom.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: false
    packager: 'yarn'
  serverless-offline:
    httpsProtocol: '../../config/localhost'
    port: 8003
  sentry:
    dsn: ${file(../../packages/dev/config/env.js):env.SENTRY_FUNCTIONS_DSN}
    captureTimeoutWarnings: false

functions:
  record-consent:
    handler: src/handlers/recordConsent.lambda
    events:
      - http:
          path: /consent
          method: post
          cors: *cors
```

</details>

* What stacktrace or error message from your provider did you see?

See above

Similar or dependent issues:

None

## Additional Data

* ***Serverless Framework Version you're using***: 1.42.0
* ***Operating System***: any
* ***Stack Trace***: none
* ***Provider Error messages***: see above

**Comment by aaronjensen** [comment]
Additional debug info:

```
Serverless: [AWS sts 200 0.366s 0 retries] getCallerIdentity({})
Serverless: [AWS apigateway 200 0.409s 0 retries] getRestApis({ limit: 500 })
Serverless: [AWS apigateway undefined 0.001s 0 retries] getStage({ restApiId: null, stageName: 'staging' })
Serverless: [AWS apigateway undefined 0.001s 0 retries] getDeployments({ restApiId: null, limit: 500 })

  Serverless Error ---------------------------------------

  Missing required key 'restApiId' in params

  Stack Trace --------------------------------------------

ServerlessError: Missing required key 'restApiId' in params
    at promise.catch.err (/Users/aaronjensen/Source/hello-epics/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:302:11)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           8.11.4
     Serverless Version:     1.42.0
```

**Comment by adamclerk** [comment]
I'm seeing this error as of this morning as well.

**Comment by sharstream** [comment]
Same error  from here, I tried to deploy the serverless yml but it couldn't deploy successfully because  is missing required key 'restApiId' in params.

**Comment by ceefour** [comment]
👍 I'm getting this too with v1.42.1. I'll try downgrading to v1.41.1.

**Comment by mrusme** [comment]
Same for me:

```
  Serverless Error --------------------------------------- 
  
  Missing required key 'restApiId' in params 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     OS:                     linux 
     Node Version:           8.11.0 
     Serverless Version:     1.42.1 
```

**Comment by medikoo** [comment]
Fixed and published with v1.42.2

**Comment by fabianib102** [comment]
> 👍 I'm getting this too after upgrading from v1.36.1 to v1.42.1. I'll try downgrading to v1.41.1.
> 
> After downgrading to v1.41.1 I get another problem: (Update: turned out to be due to `serverless-domain-manager` v3.2.1, after downgrading to v2.6.13 I can now deploy successfully using serverless v1.41.x or earlier, but not with v1.42.1)
> 
> ```
>   Error: Failed to find CloudFormation resources for x.xyz.com
> ```
> 
> argh, bad time to upgrade :(

I fix this problem, changing version with  v1.41.1

**Comment by alaasdk** [comment]
I rolled back to version v1.41.1 and everything worked just fine.

`npm i -g serverless@v1.41.1`

**Comment by bpg** [comment]
Just tried to deploy with 1.42.2:
```
Serverless Error ---------------------------------------
 
  Missing required key 'restApiId' in params
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           10.15.3
     Serverless Version:     1.42.2
```

**Comment by medikoo** [comment]
@bpg Thanks for report. Can you run it with `-d` and show us full error stack trace, also can you show us `serverless.yml` (at least related details)?

**Comment by bpg** [comment]
Now I can't reproduce it, simple re-deploy of existing stack helped. But this time I also removed `node_modules` folder, so that might be a caching issue.

**Comment by medikoo** [comment]
> Now I can't reproduce it, simple re-deploy of existing stack helped. But this time I also removed node_modules folder, so that might be a caching issue.

Interesting, especially that in env information v1.42.2 was listed.

**Comment by bpg** [comment]
I have plugins:
```
plugins:
  - serverless-plugin-aws-alerts
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-domain-manager
```
custom domain config
```
  customDomain:
    domainName: ${self:custom.prefix}.example.com
    basePath: api
    certificateName: '*.example.com'
    createRoute53Record: true
    endpointType: 'regional'
```
provider settings:
```
provider:
  name: aws
  runtime: java8
  region: us-east-1
  memorySize: 1024
  timeout: 120
  versionFunctions: false
  cfLogs: true
  logRetentionInDays: 60
  apiKeys:
    - ${self:custom.prefix}
```
I have multiple lambda handlers configured with http event like:
```
    events:
      - http:
          path: /some/thing
          method: get
          cors: true
          authorizer: aws_iam
```
and finally a custom resource in `resources`:
```
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.prefix}
```
