### ISSUE TITLE
"Serverless plugin "serverless-plugin-existing-s3" initialization errored..." when deploying after update to 1.42.2

### ISSUE THREAD

**Issue by laneschmidt** [serverless/serverless#6118]
# This is a Bug Report

## Description

* **What went wrong?**
I updated Serverless this morning (from 1.41.1), then tried to deploy my project with `sls deploy -v`, then ran into the error below.
* **What did you expect should have happened?**
Normal deployment
* **What was the config you used?**
Here's my `serverless.yml`:
```
service: textract-service

provider:
  name: aws
  runtime: python3.7
  timeout: 10
  region: us-east-1
  environment:
    STATE_MACHINE_ARN: ${self:resources.Outputs.TextractStepFunctions.Value}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "states:*"
      Resource:
        Fn::Join:
          - ""
          - - "<the-chumiest-bucket's ARN> or *"

plugins:
  - serverless-plugin-existing-s3
  - serverless-step-functions
  - serverless-pseudo-parameters

layers:
  boto3Layer:
    package:
      artifact: boto3_layer.zip
    allowedAccounts:
      - "*"

functions:
  startTextractStateMachine:
    handler: src/start_textract_state_machine.lambda_handler
    role: arn:...lambda-s3-role
    layers:
      - {Ref: Boto3LayerLambdaLayer}
    events:
      - existingS3:
          bucket: the-chumiest-bucket
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: input1/
            - suffix: .pdf
      - existingS3:
          bucket: the-chumiest-bucket
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: input2/
            - suffix: .pdf
  callTextract:
    handler: src/call_textract.lambda_handler
    role: arn:...lambda-s3-role
    layers:
      - {Ref: Boto3LayerLambdaLayer}
  getTextractOutput:
    handler: src/get_textract_output.lambda_handler
    role: arn:...lambda-s3-role
    layers:
      - {Ref: Boto3LayerLambdaLayer}
  parseTextractOutput:
    handler: src/parse_textract_output.lambda_handler
    role: arn:...lambda-s3-role
    layers:
      - {Ref: Boto3LayerLambdaLayer}

stepFunctions:
  stateMachines:
    textractStepFunc:
      name: TextractStepFunctions
      definition:
        StartAt: StartTextractStateMachine
        States:
          StartTextractStateMachine:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{AWS::StackName}-startTextractStateMachine"
            Next: CallTextract
          CallTextract:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{AWS::StackName}-callTextract"
            End: true

resources:
  Outputs:
    TextractStepFunctions:
      Description: The ARN of the state machine
      Value:
        Ref: TextractStepFunctions
```
* **What stacktrace or error message from your provider did you see?**
```
Serverless Error ---------------------------------------

Serverless plugin "serverless-plugin-existing-s3" initialization errored: Cannot find module 'serverless-plugin-existing-s3'
Require stack:
- /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js
- /usr/local/lib/node_modules/serverless/lib/Serverless.js
- /usr/local/lib/node_modules/serverless/lib/utils/autocomplete.js
- /usr/local/lib/node_modules/serverless/bin/serverless
Require stack:
```

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: 1.42.2
* ***Operating System***: Ubuntu 18.04 LTS
* ***Node Version***: 12.2.0
