### ISSUE TITLE
API Gateway cognito authorizer scopes don't work with a authorizerId

### ISSUE THREAD

**Issue by Fledermausification** [serverless/serverless#6125]
# This is a Bug Report

## Description

* What went wrong?
OAuth Scopes were not added to the API Gateway method when using an authorizerId rather than an arn.
* What did you expect should have happened?
The OAuth Scopes should have been added to the API Gateway method.
* What was the config you used?
```yaml
service: cognito-scope-bug
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  endpointType: REGIONAL

functions:
  cognito-authorizer:
    handler: handler.handler
    events:
      - http:
          path: test
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: CognitoAuthorizer
            #Using arn instead of authorizerId works
            # arn: COGNITO_ARN_GOES_HERE
            scopes:
              - app-name/scope.read

resources:
  Resources:
    CognitoAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: CognitoAuthorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        ProviderARNs:
          - COGNITO_ARN_GOES_HERE
        RestApiId:
          Ref: ApiGatewayRestApi
```
* What stacktrace or error message from your provider did you see?
None. It deployed fine but the scopes were not added.

Similar or dependent issues:
* OAuth scope functionality was added with #6000

## Additional Data

* ***Serverless Framework Version you're using***:
1.42.2
* ***Operating System***:
MacOS Mojave 10.14.4
* ***Stack Trace***:
None.
* ***Provider Error messages***:
None.
