### ISSUE TITLE
Single S3 bucket for serverless config

### ISSUE THREAD

**Issue by alshdavid** [serverless/serverless#6126]
Could we have an option to use a single S3 bucket to store our serverless configs?
My S3 is packed to the brim with serverless folders and it's so hard to find what I am looking for

**Comment by exoego** [comment]
Yes we can!
```yaml
provider:
  deploymentBucket:
    name: BUCKET_NAME_HERE
```

Refer
https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
