### ISSUE TITLE
Add support for websockets two-way routes

### ISSUE THREAD

**Issue by Mzem** [serverless/serverless#6130]
This feature was already added to serverless-websocket-plugin, can you add it to the framework?

> Adds support for two-way routes by using the **routeResponseSelectionExpression** property. When this property is set, RouteResponseSelectionExpression will be set on the Route and a RouteResponse is also created.

**Comment by DougHamil** [comment]
I also ran into this missing feature and I put together an [implementation](https://github.com/DougHamil/serverless/tree/websocket-integration-response).

It should work similarly to the serverless-websocket-plugin implementation, where this configuration:
```
functions:
  hello:
    handler: handler.helloHandler
    events:
      - websocket:
          route: hello
          routeResponseSelectionExpression: $default

```
would set the RouteResponseSelectionExpression property on the Route resource and create a RouteResponse resource associated with the Route.

If this solution looks okay, I'm happy to submit a PR for this change.
