### ISSUE TITLE
Api gateway logging attempting to create a role

### ISSUE THREAD

**Issue by shredder2500** [serverless/serverless#6134]
# This is a Bug Report

## Description

* What went wrong? enabling logging on api gateway made serverless attempt to create a role. We are not allowed to create or modify roles via our serverless.
* What did you expect should have happened? use role provided for the api gateway to use if a role is needed.
* What was the config you used?
``` provider:
  name: aws
  runtime: nodejs8.10
  logs:
    restApi: true 
```
* What stacktrace or error message from your provider did you see?
```Serverless Error ---------------------------------------

 An error occurred: xxx: iam:CreateRole User: arn:aws:sts::xxx:assumed-role/xxx is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::xxx:role/xxx with an explicit deny.
```
Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version you're using***: tried with 1.42.2 and 1.42.3
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by pmuens** [comment]
Hey @shredder2500 thanks for opening :+1:

That's correct. You need to create a new role in order for AWS to pipe API Gateway logs ino CloudWatch.

**Comment by shredder2500** [comment]
@pmuens
Can you specify a role that exists instead of creating one

**Comment by Bryconc** [comment]
Agreed. You should be able to specify and existing role for API Logs. Similar to how you can specify existing execution role.

This would be helpful as my security is hesitant to give pipeline IAM create role permissions.

**Comment by eeroniemi** [comment]
I am unable to enable API Gateway logs because of this. I think you should be able to run `serverless deploy` without giving it permission to create new roles.

**Comment by jeremy-poteet** [comment]
This is a requirement at my company as well.  We really need the ability to enable the API Gateway logs but the creation of a new role is a show stopper.  We can ensure that the role we use has the proper policies in place, but there is no way the creation of a new IAM role by the CICD pipeline will be allowed.

**Comment by justinlazaro-iselect** [comment]
having an issue here, 

Hi guys, got issue enabling the logs in serverless, about serverless is creating a `serverlessApiGatewayCloudWatchRole` right now we have a `permissionbounday` in AWS, is any solution or implementation that i can include the Permisson boundary or reference the `role` that i created


error: An error occurred: IamRoleCustomResourcesLambdaExecution - API: iam:CreateRole User: arn:aws:sts:******* is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::******

```
logs:
    restApi:
      accessLogging: true
      format: 'requestId: $context.requestId'
      executionLogging: true
      level: INFO
      fullExecutionData: true
      frameworkLambda: true
```

```
// referencing
CloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      PermissionsBoundary: ******
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
```

```
tried to do this
provider:
...
role: !GetAtt
    - CloudWatchRole
    - Arn
```

**Comment by sunilhari** [comment]
I am also facing the same issue.Even after specifying role in configuration,it is trying to create an lambda with custom resources.Since I have restriction on creating roles,it is stopping me from enabling cloudwatch logs for API gateway through serverless.yml file

```yaml
logs:
    restApi: # Optional configuration which specifies if API Gateway logs are used. This can either be set to true to use defaults, or configured via subproperties.
      executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
      level: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
      fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
      role: <role to write logs to cloudwatch> #
```
