### ISSUE TITLE
S3 Bucket Object Lifecycle support

### ISSUE THREAD

**Issue by franciscocpg** [serverless/serverless#6141]
# This is a Feature Proposal

## Description

I want to configure lifecycle for a bucket created by s3 event (like #3308).

I read [custom bucket configuration](https://serverless.com/framework/docs/providers/aws/events/s3#custom-bucket-configuration) but since my bucket name is dynamic (eg: `${self:provider.stage}-my-bucket`) I'm not sure how to follow the logical IDs rules explained there.

So, is there a way to have a bucket created by s3 event AND configure a lifecyle for it?

Similar or dependent issues:
* #3308

**Comment by herebebogans** [comment]
@franciscocpg 

Try this config for an event on upload of a *.gz file to a cloudformation customised s3 bucket.

```
....
....

functions:
  myfunction:
    handler: handler.createEvent                      
    events:
      - s3:
          bucket: example
          event: s3:ObjectCreated:*
          rules:
            - suffix: .gz
...
...
                      
resources:
  Description: My S3 Event Stack
  Resources:
    S3BucketExample:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.stage}-my-example-bucket
        LifecycleConfiguration:
          Rules:
            -
              ExpirationInDays: 7
              Prefix: '/'
              Status: Enabled 
                       
    MyfunctionLambdaPermissionExampleS3:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt MyfunctionLambdaFunction.Arn
        Principal: s3.amazonaws.com
        Action: lambda:InvokeFunction
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: arn:aws:s3:::${self:custom.stage}-my-example-bucket
```

**Comment by phirapara** [comment]
How can we add lifecycle configuration for existing s3 bucket. It is not allowing for existing s3 bucket.

**Comment by pgrzesik** [comment]
@phirapara Hello, what are you trying to achieve? Use existing backed as event trigger or you want to adjust it's lifecycle configuration?

**Comment by phirapara** [comment]
@pgrzesik, Thanks for responding.

 I am using existing as bucket trigger(as shown below) which works fine , and  I want to add lifecycle policy to that existing bucket.
 ```
functions:
  myFunction:
     handler: imageProcessor
    events:
      - s3:
          bucket: ExistingBucket
          rules:
            - prefix: images/
          existing: true
```
 I tried to configure it under resources, but it does not allow to use exiting resource
