### ISSUE TITLE
Generated aws cf template can not be validated if setting the retain as 'true' of layer

### ISSUE THREAD

**Issue by zxkane** [serverless/serverless#6146]
# This is a Bug Report

## Description

* What went wrong?
Failed to deploy aws lambda due to below error,

> Error --------------------------------------------------
> 
>   The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [DependenciesLambdaLayer] in the Resources block of the template

* What did you expect should have happened?

The deployment goes well or report the configuration issue earlier. 

* What was the config you used?

The function refers to the layer created in same serverless.yml.

```
functions:
  dingtalk-callback:
    handler: com.github.zxkane.dingtalk.Callback::handleRequest # required, handler set in AWS Lambda
    name: ${self:provider.stage}-dingtalk-callback # optional, Deployed Lambda name
    description: Callback of dingtalk # optional, Description to publish to AWS
    memorySize: 384 # optional, in MB, default is 1024
    timeout: 15 # optional, in seconds, default is 6
    reservedConcurrency: 5 # optional, reserved concurrency limit for this function. By default, AWS uses account concurrency limit
    tracing: PassThrough # optional, overwrite, can be 'Active' or 'PassThrough'
    artifact: build/libs/dingtalk-callback-1.0.0-SNAPSHOT.jar
    layers: # An optional list Lambda Layers to use
      - {Ref: DependenciesLambdaLayer}
    events: # The Events that trigger this Function
      - http: # This creates an API Gateway HTTP endpoint which can be used to trigger this function.  Learn more in "events/apigateway"
          path: dingtalk # Path for this endpoint
          method: post # HTTP method for this endpoint
          cors: false # Turn on CORS for this endpoint, but don't forget to return the right header in your response
          request:
            parameters:
              querystrings:
                timestamp: true
                nonce: true
                signature: true


layers:
  dependencies:
    path: build/deps
    name: ${self:provider.stage}-dingtalk-callback-deps # optional, Deployed Lambda layer name
    description: DingTalk Dependencies Layer # optional, Description to publish to AWS
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - java8
    licenseInfo: Available under the MIT-0 license. # optional, a string specifying license information
    allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
      - '*'
    retain: true # optional, false by default. If true, layer versions are not deleted as new ones are created
```

* What stacktrace or error message from your provider did you see?

> Stack Trace --------------------------------------------
> 
> Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [DependenciesLambdaLayer] in the Resources block of the template
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:24:13
> From previous event:
>     at AwsDeploy.validateTemplate (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:19:12)
> From previous event:
>     at AwsDeploy.<anonymous> (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
> From previous event:
>     at Object.aws:deploy:deploy:validateTemplate [as hook] (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:10)
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:422:55
> From previous event:
>     at PluginManager.invoke (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:422:22)
>     at PluginManager.spawn (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:440:17)
>     at AwsDeploy.<anonymous> (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
> From previous event:
>     at Object.deploy:deploy [as hook] (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:10)
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:422:55
> From previous event:
>     at PluginManager.invoke (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:422:22)
>     at PluginManager.run (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:453:17)
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/Serverless.js:110:33
>     at processImmediate (internal/timers.js:439:21)
>     at process.topLevelDomainCallback (domain.js:126:23)
> From previous event:
>     at Serverless.run (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/lib/Serverless.js:97:6)
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/bin/serverless:43:28
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
>     at FSReqCallback.oncomplete (fs.js:153:20)
> From previous event:
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/bin/serverless:43:6
>     at processImmediate (internal/timers.js:439:21)
>     at process.topLevelDomainCallback (domain.js:126:23)
> From previous event:
>     at /usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/bin/serverless:28:46
>     at Object.<anonymous> (/usr/local/Cellar/serverless/1.42.3/libexec/lib/node_modules/serverless/bin/serverless:65:4)
>     at Module._compile (internal/modules/cjs/loader.js:759:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
>     at Module.load (internal/modules/cjs/loader.js:628:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
>     at internal/main/run_main_module.js:17:11

## Additional Data

* ***Serverless Framework Version you're using***:
1.42.3
* ***Operating System***:
macosx 10.14.5
* ***Stack Trace***:
* ***Provider Error messages***:
