### ISSUE TITLE
Api Gateway Websocket cognito authorizer support

### ISSUE THREAD

**Issue by gregadunbit** [serverless/serverless#6161]
I am trying to use Cognito authorizer in a WebSocket connect route:

```yaml
connectionManager:
    handler: bin/ConnectionManager
    events:
      - websocket:
          route: $connect
          authorizer: 
          name: authorizer
          arn: 'arn'
          identitySouce: 
          - 'route.request.header.Authorization'
          - 'route.request.querystring.Auth'
          scopes: 
          - 'scope1'
      - websocket:
          route: $disconnect
```

* ***Serverless Framework Version you're using***:  1.42.3
* ***Operating System***:
* ***Stack Trace***:  
* ***Provider Error messages***:   Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource AuthorizerLambdaFunction
