### ISSUE TITLE
Files are included twice in the package zip file when using non-normalized paths.

### ISSUE THREAD

**Issue by yannvgn** [serverless/serverless#6164]
# This is a Bug Report

## Description

* What went wrong?

Using non-normalized paths (like `./somefile.txt`) in `package: include` section leads to files being included twice in the package zip file.

serverless.yml:
```yml
service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs10.x

functions:
  helloWorld:
    handler: handler.helloWorld

package:
  exclude:
    - "**"
  include:
    - handler.js
    - ./somefile.txt
```

```
sls package
zipinfo .serverless/serverless-hello-world.zip
```

zipinfo output:
```
Archive:  .serverless/serverless-hello-world.zip
Zip file size: 640 bytes, number of entries: 3
-rw-r--r--  4.5 unx        0 bl stor 80-Jan-01 00:00 ./somefile.txt
-rw-r--r--  4.5 unx      385 bl defN 80-Jan-01 00:00 handler.js
-rw-r--r--  4.5 unx        0 bl stor 80-Jan-01 00:00 somefile.txt
3 files, 385 bytes uncompressed, 270 bytes compressed:  29.9%
```

`somefile.txt` has been included twice, once as `somefile.txt`, once as `./somefile.txt`.

The issue could be fixed in `fast-glob` or `globby`, depending on their decision (see Similar or dependent issues).

* What did you expect should have happened?

The package zip file should not contain such duplicates.

* What was the config you used?
hello-world boilerplate

* What stacktrace or error message from your provider did you see?
N/A

Similar or dependent issues:
* https://github.com/mrmlnc/fast-glob/issues/190
* https://github.com/sindresorhus/globby/issues/119

## Additional Data

* ***Serverless Framework Version you're using***:
1.43.0
* ***Operating System***:
macOS 10.14
* ***Stack Trace***:
N/A
* ***Provider Error messages***:
N/A
