### ISSUE TITLE
serverless 1.42.x unsets api gateway logging level on previously existing deployment

### ISSUE THREAD

**Issue by scamden** [serverless/serverless#6165]
# This is a Bug Report

## Description

* What went wrong?
  Deploying serverless with api gateway functions unsets logging_level (presumably because of the new `logs.restApi` feature). Even though the api gateway deployment already existed and had logging level set to info, deploying the function sets it back to false despite the option logs.restApi not being set to false
* What did you expect should have happened?
don't modify the setting if i didn't provide an explicit value.
* What was the config you used?
relevant bits:

``` 
 apiGateway:
    restApiId: ${ssm:/infra/api-id}
    restApiRootResourceId: ${ssm:/infra/api-root-resource-id}
```
```
functions:
  api:
    name: ${self:custom.stageNames.${self:provider.stage}, self:custom.defaultName}
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /admin
          method: ANY
          integration: mock
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              text/xhtml: '{ "statusCode" : 200 }'
              application/json: '{ "statusCode" : 200 }'
          response:
            statusCodes:
              403:
                pattern: ''
      - http:
          path: '{proxy+}'
          method: ANY
```
* What stacktrace or error message from your provider did you see?
none

Similar or dependent issues:
* #6094 

## Additional Data

* ***Serverless Framework Version you're using***: 1.42.3
* ***Operating System***: amazon linux 2
* ***Stack Trace***: none
* ***Provider Error messages***:none
