### ISSUE TITLE
Importing python package cryptography 2.6.1 fails with module import error

### ISSUE THREAD

**Issue by neotheicebird** [serverless/serverless#6167]
# This is a Bug Report

## Description

* What went wrong?

Unable to use package `cryptography`. Leads to import error.

* What did you expect should have happened?

There shouldn't be an import error and this works fine locally.

* What was the config you used?

```
# serverless.yaml
...
provider:
  name: aws
  runtime: python3.6
custom:
  pythonRequirements:
    dockerizePip: true
    fileName: ../requirements.txt

plugins:
  - serverless-python-requirements
```
```
# requirements.txt
cryptography==2.6.1
```

* What stacktrace or error message from your provider did you see?

Leads to `Unable to import module 'auth': No module named 'cryptography'`

Similar or dependent issues:

This is a similar issue documented in Chalice

https://github.com/aws/chalice/issues/764

## Additional Data

* ***Serverless Framework Version: 1.43.0***:
* ***Operating System: Ubuntu 18.04***:
