### ISSUE TITLE
Add support for custom names for models used in AWS API Gateway Basic Request Validation

### ISSUE THREAD

**Issue by DaphneOlrichs** [serverless/serverless#6171]
# This is a Feature Proposal

## Description

With the changes made in #5956, it is now possible to add a request schema to your lambda function for the API Gateway to use. However, doing this means an `AWS::ApiGateway::Model` is being added to the Cloudformation JSON without a name. This then resolves to a Model in API Gateway with a generated ID as name.

**It would be nice if it would be possible to give a custom name for the `AWS::ApiGateway::Model` created, so it will be clearer and easier to understand and find in API Gateway.**

P.S.: If you use the plugins `serverless-aws-documentation` and `serverless-reqvalidator-plugin` to make use of models for request validation (as described [here](https://stackoverflow.com/questions/49133294/request-validation-using-serverless-framework)), this is already possible. However, it would be nice to use the new and improved way without plugins 😄

Similar or dependent issues:
* Found this while using the new way introduced in #5956.

## Different possible solutions

I can get this feature working by editing the setup for the request schemas, but that would mean a breaking change. I haven't found a way to do this without breaking the current version of request schemas (besides defining a completely new setup to use alongside it), so if anybody has any ideas about that I would love to hear them 😃

Either way, if desired, I can make a pull request for whatever new setup.

### Current setup
```yml
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          request:
            schema:
              application/json: ${file(create_request.json)}
```

### Breaking new setup
Something like:
```yml
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          request:
            schemas:
              - contentType: application/json
                definition: ${file(create_request.json)}
                name: createRequest
```

### Non-breaking new setup
With this newly defined setup the 'old' setup as in #5956 would still work as well.
Something like:
```yml
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          request:
            models:
              - contentType: application/json
                definition: ${file(create_request.json)}
                name: createRequest
```

**Comment by atz** [comment]
💯% this is necessary.  Beyond custom name, multiple functions MUST be able to use the **same** model, instead of creating many different models with the same content.  

The entire point of having a schema is to drive convergence between clients and endpoints.  I should only have to update one model in a Gateway to affect ALL the functions that adhere to it.  

Enhancements requested:
- Allow name, as in OP
- Allow description (currently empty, making the lack of custom name worse)
- Allow mechanism to provide JSON that doesn't remove JSON formatting (i.e. coercing it into single-line), so that the schemas themselves are still readable in console.  
- Allow schema specification by name, rather than by content (i.e. reuse instead of copy)

All together, this suggests defining a schema *separate* from a method and referencing it from the method definition.  Instead, we have many mechanically randomly named models with no descriptions, forcing us to read the schema bodies themselves to understand what each is, but the schema body has been reformatted to reduce readability.  Are they really the same or not?  Who knows?

This particularly affects other teams that are writing clients for the API Gateway apps that we define in serverless.

**Comment by angelcervera** [comment]
Because it is not possible to define the name, AWS API Gateway it is generating random names for every model in every deployment.
We have customers using the services and use the "SDK Generation" option in the API Gateway Stage Editor, but it generates code with different model names every time, so it is necessary to refactor the generated code or modify the client after every deployment.

This functionality is necessary.

**Comment by medikoo** [comment]
Great thanks for all the comments, we're happy to bake that in. What do you think about following proposal:

```yaml
provider:
  apiGateway:
    schemas:
      # Reusable schemas definitions
      foo: ${file(foo-schema.json)} # name: foo
      bar:
        name: BarSchema # (optional) If not set schema name would be "bar"
        schema: ${file(bar-schema.json)} 
        description: Schema description

functions:
  foo:
    events:
      - http:
          request:
            schema: foo # reusable "foo" schema picked
      - http:
          request:
            schema: ${file(nameless-schema.json)} # current behaviour
      - http:
          request:
            schema:
              # Schema defined inline (not-reusable)
              name: InlineSchema
              schema: ${file(inline-named-schema.json)} 
              description: Inline schema description
```

**Comment by jmcguffee** [comment]
I think the above makes sense. I don't have the case where my models need reusable, but would be good to have. I know the `serverless-aws-documentation` plugin creates models as well so this will definitely cause some issues with naming, but that is a separate issue. I will work on implementing the above recommendation into my PR and if anyone else has comments on the matter I will take those into account as wel.

**Comment by medikoo** [comment]
> I don't have the case where my models need reusable

I'm also not sure about this use case. @atz can you put more light, on why do you feel it's important to have?

**Comment by jmcguffee** [comment]
also I realize that 
```yaml
    events:
      - http:
          request:
            schema: foo # reusable "foo" schema picked
```
will need to have some type of content type defined as well. We could default to `application/json` but that is a huge assumption.

**Comment by jmcguffee** [comment]
I would propose
```yaml
provider:
  apiGateway:
    schemas:
      # Reusable schemas definitions
      foo: ${file(foo-schema.json)} # name: foo
      bar:
        name: BarSchema # (optional) If not set schema name would be "bar"
        schema: ${file(bar-schema.json)} 
        description: Schema description

functions:
  foo:
    events:
      - http:
          request:
            schema: 
                application/json: foo # reusable "foo" schema picked
      - http:
          request:
            schema: 
               application/json: ${file(nameless-schema.json)} # current behaviour
      - http:
          request:
            schema:
              application/json: # Schema defined inline (not-reusable)
                name: InlineSchema
                schema: ${file(inline-named-schema.json)} 
                description: Inline schema description
```
