### ISSUE TITLE
API Gateway 3rd level endpoints fail with 403

### ISSUE THREAD

**Issue by adam-t-b** [serverless/serverless#6176]
# This is a Bug Report

## Description

* What went wrong?
AWS function event paths with 3 levels are deploying to API Gateway and lambda but consistently throwing 403's on execution. I successfully tested the endpoint and function directly in their respective dashboards. Executing the endpoint from chrome dev tools throws a 403. (err message below)
* What did you expect should have happened?
The endpoint should actually execute and return something.
* What was the config you used?
```
user-invite:
    handler: user-invite.handler
    description: Endpoint for inviting a user to the application including setting their password.
    events:
    - http:
        path: /${self:custom.version}/user/invite
        method: post
        cors: true
        authorizer:
          name: user-authorize
          resultTtlInSeconds: 3600
          identitySource: method.request.header.Authorization
```
The provider has a basic lambda role which use used on all my 2 level paths with no issue. This same endpoint works if I shorten it to 2 levels (i.e. path: /${self:custom.version}/invite).
Also, the authorizer works as expected on all 2 level api endpoints. On 3 level endpoints it never gets called, nor do the the lambda functions.
* What stacktrace or error message from your provider did you see?
POST https://{{API_ID}.execute-api.us-west-2.amazonaws.com/dev/v1/user/verify 403
:1 Access to XMLHttpRequest at 'https://{{API_ID}}.execute-api.us-west-2.amazonaws.com/dev/v1/user/verify' from origin 'https://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
UserService.js?5e44:18 error: Error: Network Error
    at createError (createError.js?2d83:16)
    at XMLHttpRequest.handleError (xhr.js?b50d:87)
Similar or dependent issues:

## Additional Data

* SLS version 1.42.3
* Vue js CLI 3.x
* Windows 10
* Red circle on forehead from wall

**Comment by adam-t-b** [comment]
Hmmm... all my text is disappearing when I submit....

**Comment by pmuens** [comment]
Hey @adam-t-b thanks for opening :+1:

It looks like your indentation for the `http` event is wrong.

Your code should look smth. like this:

```yaml
user-invite:
    handler: user-invite.handler
    description: Endpoint for inviting a user to the application including setting their password.
    events:
      - http:
          path: /${self:custom.version}/user/invite
          method: post
          cors: true
          authorizer:
            name: user-authorize
            resultTtlInSeconds: 3600
            identitySource: method.request.header.Authorization
```

That should do the trick.

**Comment by adam-t-b** [comment]
@pmuens This seems like a candidate for an error to be thrown by serverless when validating the yml files.
SLS already throws an error when the path property is only single indented after the http prop.

This config:
```
- http:
  path: /${self:custom.version}/test/one
```
Throws:
```
Serverless Error ---------------------------------------

Missing or invalid "path" property in function "user-verify" for http event in serverless.yml. If you define an http event, make sure you pass a valid value for it, either as string syntax, or object syntax. Please check the indentation of your config values if you use the object syntax. Please check the docs for more options.
```

I would think this config: 
```
events:
- http:
```
Would throw an error too.

I'd be happy to attempt a PR to save someone else many hours of frustration.  This type of bug is worse because on the AWS side everything _looks_ like its running and deployed correctly. Cost me 4-6 hrs.

**Comment by travislondon** [comment]
I am not sure I see the same problem exactly, but here is what my definition looks like:

  subelements:
    handler: Elements.getSubElementsForContainer
    events:
      - http:
          path: elements/{elementId}/subelements/{containerId}
          method: get
          authorizer: ${self:custom.authorizer.validate}
          cors: true

Everything works perfectly when testing in the AWS console.  However I receive a 403 when hitting it with the client.

I know that I have had ones that match this pretty closely that worked, but they have now been disabled.

Any help appreciated.

**Comment by travislondon** [comment]
I am wondering if this is more related to having the two path vars, as this works:

path: elements/{elementId}/subelements

**Comment by adam-t-b** [comment]
@travislondon I have another app that's running SLS 1.32.0 which has this route:
```
admin-board-update:
    handler: admin-board-update.handler
    description: Updates a board using a userId and BoardId. Returns 200 OK.
    events:
      - http:
          path: /${self:custom.version}/admin/boards/{userid}/{boardid}
          method: put
          request:
            parameters:
              paths:
                boardid: true
                userid: true
          cors: true
          authorizer:
            name: user-authorize
            resultTtlInSeconds: 3600
            identitySource: method.request.header.Authorization
```
It has zero issues and contains 2 path vars as well as being 5 levels deep.  I'm going to try reverting back to this version and see if things are more stable.

**Comment by adam-t-b** [comment]
-Update, 
The issue was with my authorizer after all.  The response I was getting was a 403, and the error text was around CORS issues, which just means the error I was getting didn't have the correct headers.  I added the following resource to get a better understanding of the issue:
```
Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
```
That helped me to narrow it down a little.  The final issue was that the custom authorizer was caching the response for 3600 and was using a specific arn for the resource.  This meant my initial requests (GET) would be cached, but the subsequent request (POST) would always fail.  I saw false positives because I would deploy my app through the console while not refreshing the page, which would mean I could occasionally get a request through successfully.

One thing of note that was also helpful in debugging was turning on the API Gateway logs using this property under provider:
```
provider:
  logs:
    restApi: true
```

**Comment by travislondon** [comment]
Glad to hear you resolved it.  I am not sure where my problem lied, but caching was an issue.  I have no need for caching so I turned it off on AWS and redeployed.  Something I changed has resolved the issue.  Sounds like the same issue I was having.  Thanks for the log tip, I will add that next time.

**Comment by 0v3rst33r** [comment]
I know this is closed already, but my solution in the end was:
```
    Resources:
        GatewayResponseDefault4XX:
            Type: 'AWS::ApiGateway::GatewayResponse'
            Properties:
                ResponseParameters:
                    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
                    gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
                ResponseType: DEFAULT_4XX
                RestApiId:
                    Ref: 'ApiGatewayRestApi'
```
and the fix being the line:
```
                    gatewayresponse.header.Access-Control-Allow-Credentials: "'true'"
```
