### ISSUE TITLE
Deploy is using the wrong path to read serverless-state.json

### ISSUE THREAD

**Issue by jeffogata** [serverless/serverless#6179]
# This is a Bug Report

## Description

* What went wrong?

Deploying with version 1.43.0 to AWS fails with an error indicating that the `serverless-state.json` file cannot be found.  The same deployment using version 1.41.1 succeeds.  This sounds similar to [#5381](https://github.com/serverless/serverless/issues/5381), but the stack trace points to code that was added fairly recently, so I suspect it is a new issue.

The full text of the error message and stack trace is below, but briefly, the error is

> ENOENT: no such file or directory, open '/codebuild/output/src819372752/src/codebuild/output/src819372752/src/artifacts/stg/serverless-state.json' 

In the logs, the error appears after the stack is successfully updated and the service information and stack outputs are logged.

The command I use to package the artifacts in the `buildspec.yml` file is:

    sls package -p artifacts/stg -s stg`

The command to deploy the package:

    sls deploy -s $env -p $CODEBUILD_SRC_DIR/artifacts/$env -v`

I included the following command in the deploy script to check the contents of the artifacts directory:

    ls $CODEBUILD_SRC_DIR/artifacts/$env/**`

and the output shows the file:

> /codebuild/output/src819372752/src/artifacts/stg/cea-payment-portal-api.zip 
> /codebuild/output/src819372752/src/artifacts/stg/cloudformation-template-create-stack.json 
> /codebuild/output/src819372752/src/artifacts/stg/cloudformation-template-update-stack.json 
> /codebuild/output/src819372752/src/artifacts/stg/serverless-state.json 
> 

* What did you expect should have happened?

    The deployment should have found the `serverless-state.json` file and finished successfully.

* What was the config you used?

    serverless.yml:

```
service: cea-payment-portal-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  region: 'us-east-2'
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  tracing:
    apiGateway: true
    lambda: true
  vpc:
    securityGroupIds:
      - sg-00000000
    subnetIds:
      - subnet-111111111
      - subnet-22222222

package:
  exclude:
    - __tests__/**

functions:
  hello-get:
    handler: src/hello/hello-get-handler.hello
    events:
      - http:
          method: get
          path: hello
    environment:
      ENVIRONMENT: ${ssm:/cea-payment-portal-api/${self:provider.stage}/environment}
  invoices:
    handler: src/invoices/invoices-get-handler.getInvoice
    events:
      - http:
          method: get
          path: invoices
    environment:
      CALLEMALL_DB_NAME: ${ssm:/cea-payment-portal-api/${self:provider.stage}/callemall-db-name}
      CALLEMALL_DB_USER_RO: ${ssm:/cea-payment-portal-api/${self:provider.stage}/callemall-db-user-ro}
      CALLEMALL_DB_PASSWORD_RO: ${ssm:/cea-payment-portal-api/${self:provider.stage}/callemall-db-password-ro}
      CALLEMALL_DB_SERVER: ${ssm:/cea-payment-portal-api/${self:provider.stage}/callemall-db-server}
      
plugins:
  - serverless-offline
  - '@anttiviljami/serverless-stack-output'

custom:
  output:
    file: .build/stack.json
```

* What stacktrace or error message from your provider did you see?

    This is a partial stack trace, the full stack trace is below.

>   Error -------------------------------------------------- 
>   
>   ENOENT: no such file or directory, open '/codebuild/output/src819372752/src/codebuild/output/src819372752/src/artifacts/stg/serverless-state.json' 
>   
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable. 
>   
>   Stack Trace -------------------------------------------- 
>   
> Error: ENOENT: no such file or directory, open '/codebuild/output/src819372752/src/codebuild/output/src819372752/src/artifacts/stg/serverless-state.json' 
>     at Object.openSync (fs.js:439:3) 
>     at Object.readFileSync (fs.js:344:35) 
>     at readFileSync (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/utils/fs/readFileSync.js:7:24) 
>     at Utils.readFileSync (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/Utils.js:72:12) 
>     at AwsCompileApigEvents.getServiceState (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/getServiceState.js:10:34) 
>     at Object.after:deploy:deploy [as hook] (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:77:39) 
>     at BbPromise.reduce (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:422:55) 
> 

* Similar or dependent issues:

* #5381

## Additional Data

* ***Serverless Framework Version you're using***:

    1.43.0

* ***Operating System***:

    Ubuntu

* ***Stack Trace***:

>   Stack Trace -------------------------------------------- 
>   
> Error: ENOENT: no such file or directory, open '/codebuild/output/src819372752/src/codebuild/output/src819372752/src/artifacts/stg/serverless-state.json' 
>     at Object.openSync (fs.js:439:3) 
>     at Object.readFileSync (fs.js:344:35) 
>     at readFileSync (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/utils/fs/readFileSync.js:7:24) 
>     at Utils.readFileSync (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/Utils.js:72:12) 
>     at AwsCompileApigEvents.getServiceState (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/lib/getServiceState.js:10:34) 
>     at Object.after:deploy:deploy [as hook] (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:77:39) 
>     at BbPromise.reduce (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:422:55) 
> From previous event: 
>     at PluginManager.invoke (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:422:22) 
>     at PluginManager.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:453:17) 
>     at variables.populateService.then (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/Serverless.js:110:33) 
>     at runCallback (timers.js:705:18) 
>     at tryOnImmediate (timers.js:676:5) 
>     at processImmediate (timers.js:658:5) 
>     at process.topLevelDomainCallback (domain.js:120:23) 
> From previous event: 
>     at Serverless.run (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/Serverless.js:97:6) 
>     at serverless.init.then (/usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless:43:28) 
>     at /usr/local/share/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:111:16 
>     at /usr/local/share/.config/yarn/global/node_modules/graceful-fs/graceful-fs.js:45:10 
>     at FSReqWrap.oncomplete (fs.js:141:20) 
> From previous event: 
>     at initializeErrorReporter.then (/usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless:43:6) 
>     at runCallback (timers.js:705:18) 
>     at tryOnImmediate (timers.js:676:5) 
>     at processImmediate (timers.js:658:5) 
>     at process.topLevelDomainCallback (domain.js:120:23) 
> From previous event: 
>     at /usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless:28:46 
>     at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/serverless/bin/serverless:65:4) 
>     at Module._compile (internal/modules/cjs/loader.js:689:30) 
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10) 
>     at Module.load (internal/modules/cjs/loader.js:599:32) 
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12) 
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3) 
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12) 
>     at startup (internal/bootstrap/node.js:283:19) 
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) 
>   
>   Get Support -------------------------------------------- 
>      Docs:          docs.serverless.com 
>      Bugs:          github.com/serverless/serverless/issues 
>      Issues:        forum.serverless.com 
>   
>   Your Environment Information --------------------------- 
>      OS:                     linux 
>      Node Version:           10.15.0 
>      Serverless Version:     1.43.0 
> 

  

* ***Provider Error messages***:

>   Error -------------------------------------------------- 
>   
>   ENOENT: no such file or directory, open '/codebuild/output/src819372752/src/codebuild/output/src819372752/src/artifacts/stg/serverless-state.json' 
>
