### ISSUE TITLE
Deploying requires inexistent packages

### ISSUE THREAD

**Issue by vicary** [serverless/serverless#6180]
# This is a Bug Report

## Description

* What went wrong?
    I was developing with `serverless-appsync-plugin` along with a few lambda, after a few runs of `sls deploy` it suddenly prompts for missing modules in the `node_modules/.bin` directory.

    First it wants `node-gyp`, I manually installed that as a workaround, it then asks for `node-ninja`. I suspect there is a list of missing internal dependencies from `serverless-cli` because of some misconfiguration I made in the way.

    I recently updated serverless with `sudo npm up -g serverless`, not sure if that introduces the error.

* What did you expect should have happened?
    My application should deploy normally like before.

* What was the config you used?
    ```
    # Welcome to serverless. Read the docs
    # https://serverless.com/framework/docs/

    # Serverless.yml is the configuration the CLI
    # uses to deploy your code to your provider of choice
    # https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/#serverlessyml-reference

    # The `service` block is the name of the service
    service: test-api

    # The `provider` block defines where your service will be deployed
    provider:
      name: aws
      runtime: nodejs10.x
      stackName: test-api
      deployementPrefix: test
      tracing:
        lambda: true

    plugins:
      - serverless-plugin-typescript

    functions:
      test:
        handler: lambda/test.handler
        description: Test function that dumps it's input.
        onError: arn:aws:sns:ap-southeast-1:571664442729:NotifyHQ
    ```

* What stacktrace or error message from your provider did you see?
    ```
    Error: ENOENT: no such file or directory, open '/Users/Vicary/Documents/GitHub/omniwe/graphql-api-serverless/.build/node_modules/.bin/node-ninja'
        at Package.getFileContent (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:130:15)
        at Package.getFileContentAndStat (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:119:12)
        at Array.map (<anonymous>)
        at WriteStream.output.on (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:91:29)
        at WriteStream.emit (events.js:189:13)
        at WriteStream.EventEmitter.emit (domain.js:441:20)
        at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:231:14
        at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:258:16
        at FSReqWrap.args [as oncomplete] (fs.js:140:20)
    ```

## Additional Data

* ***Serverless Framework Version you're using***: 1.43.0
* ***Operating System***: darwin
* ***Stack Trace***:
* ***Provider Error messages***: ENOENT: no such file or directory, open '/Users/Vicary/Documents/GitHub/omniwe/graphql-api-serverless/.build/node_modules/.bin/node-gyp'
