### ISSUE TITLE
Cannot read property 'length' of undefined when defining a string authorizer

### ISSUE THREAD

**Issue by camilosampedro** [serverless/serverless#6185]
# This is a Bug Report

## Description

* What went wrong?
Running `serverless deploy` on a serverless.yml file that has a lambda function with a "string" authorizer (AWS Cognito authorizer). I found out by debugging that it is related to the claims in `validate.js` file (https://github.com/serverless/serverless/blob/add5e3ebb5d3d9050e36bf720ab9ab1c3fd8f3d8/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js#L223). If I manually define it as `[]` at the beginning, it will execute successfully.
* What did you expect should have happened?
To deploy successfully.
* What was the config you used?
My lambda function section looks like:
```
  my-function:
    handler: bin/my-function
    timeout: 15
    package:
      include:
        - bin/my-function
    role: "arn:aws:iam::${self:custom.tenant_id}:role/${self:custom.project_name}-${self:custom.env}-my-function-lambda-role"
    events:
      - http:
          path: my-path
          method: any
          authorizer: "arn:aws:cognito-idp:${self:custom.region}:${self:custom.tenant_id}:userpool/${self:custom.cognito_user_pool}"
      - http:
          path: my-path/{id}
          method: any
          authorizer: "arn:aws:cognito-idp:${self:custom.region}:${self:custom.tenant_id}:userpool/${self:custom.cognito_user_pool}"
    environment:
      MY_VARIABLE: "/${self:custom.project_name}-${self:custom.env}"
```
* What stacktrace or error message from your provider did you see?
The error message is from serverless itself

Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***: MacOS Mojave 10.14.5
* ***Stack Trace***: 
```
 
  Type Error ---------------------------------------------
 
  Cannot read property 'length' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'length' of undefined
    at AwsCompileApigEvents.getAuthorizer (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:286:17)
    at _.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:51:36)
    at arrayEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:43:9)
    at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:2996:24)
    at /usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9344:14)
    at AwsCompileApigEvents.validate (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js:42:7)
    at Object.package:compileEvents [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js:53:31)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:446:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:446:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:464:17)
    at Deploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:122:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:446:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:446:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:477:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:110:33)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:97:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:6)
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:65:4)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
```
* ***Provider Error messages***:
No error messages from the provider.
