### ISSUE TITLE
Adding rule for CloudWatch Events through serverless doesn't work

### ISSUE THREAD

**Issue by mikhama** [serverless/serverless#6189]
# This is a Bug Report

## Description

* What went wrong?
I have defined CloudWatch Event for my lambda function in `serverless.yml` like was written in this document: https://serverless.com/framework/docs/providers/aws/events/cloudwatch-event/
Lambda was deployed successfully, but rule was not created.
* What did you expect should have happened?
I expected that rule on this page would be added:
https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#rules:
* What was the config you used?
```yml
provider:
  name: aws
  runtime: nodejs8.10

functions:
  onHealthEvent:
    handler: handler.sendEmailNotification
    events:
      - cloudwatchEvent:
        event:
          source:
            - aws.health
```
* What stacktrace or error message from your provider did you see?
I didn't see any errors. Lambda deployed successfully.

Similar or dependent issues:
* I didn't find issue when rule was not created.

## Additional Data

* ***Serverless Framework Version you're using***:
1.43.0
* ***Operating System***:
Windows 10
* ***Stack Trace***:
No errors
* ***Provider Error messages***:
No errors

**Comment by pmuens** [comment]
Hey @mikhama thanks for opening 👍
It looks like your `serverless.yml` isn't formatted correctly. Here's how it should look like:

```yml
provider:
  name: aws
  runtime: nodejs8.10

functions:
  onHealthEvent:
    handler: handler.sendEmailNotification
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.health
```
