### ISSUE TITLE
PATCH verb failing CORS preflight as AWS Lambda

### ISSUE THREAD

**Issue by rcldesign** [serverless/serverless#6190]
# This is a Bug Report
For whatever reason, no matter what I do, I can’t get a preflight request to allow the PATCH verb. This configuration snippet is what I’ve configured for my API endpoint, but the actual preflight is just allowing OPTIONS, GET, POST.

## Description

* What went wrong?
API Gateway responded to the preflight request with just OPTIONS, GET, POST verbs

* What did you expect should have happened?
The preflight request should have returned with the verbs listed in the serverless.yml file

* What was the config you used?
Excerpt from serverless.yml for this endpoint: 

```
patchfiles:
  handler: services/files.patchFiles
  memorySize: 128
  timeout: 10
  events:
    - http:
        path: files/{id}
        method: patch
        authorizer:
          arn: arn:aws:**************
        cors:
          origin: ‘*’
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
          allowCredentials: false
          cacheControl: ‘max-age=600, s-maxage=600, proxy-revalidate’
          methods: ‘DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT’
```
I have also tried this with the methods being an array of strings to no avail.

* What stacktrace or error message from your provider did you see?
Preflight response is as follows: 

![image](https://user-images.githubusercontent.com/1377385/58585008-6eb3b400-820c-11e9-9594-fd48ad675678.png)

## Additional Data

* ***Serverless Framework Version you're using***:
1.42.3

* ***Operating System***:
AWS Lambda, Node 8.10
