### ISSUE TITLE
sls package --package command doesn't create a zip file in the specified directory

### ISSUE THREAD

**Issue by sheoranpranava91** [serverless/serverless#6193]
# This is a Bug Report

## Description
* What went wrong?
I was following the quick start guide for serverless https://serverless.com/framework/docs/providers/google/guide/quick-start/ and created a service as mentioned in the guide. I ran the following commands: 
```
serverless create --template google-nodejs --path my-service
cd my-service
npm install
```
I edited the serverless.yml to contain a valid key path and tried the following command
```
serverless package --package /tmp
```
Running the above command doesn't produce any result in the /tmp directory. Instead, the .serverless folder is created in the my-service folder

* What did you expect should have happened?
I expected to see a zip file in my /tmp directory

* What was the config you used?
My serverless.yml config is
```
service: my-service # NOTE: Don't put the word "google" in here

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-central1
  project: ruckussgdc-mlisa
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: /Users/psheoran/myKey.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
```
* What stacktrace or error message from your provider did you see?
There was no error message in the console

## Additional Data

* ***Serverless Framework Version you're using***: 1.44.1
* ***Operating System***: MacOS Mojave 10.14.3
* ***Node version***: 10.12.0

I followed the AWS quickstart guide and was able to generate the zip file at the same path.
