### ISSUE TITLE
EnterpriseLogAccessIamRole contains malformed policy

### ISSUE THREAD

**Issue by austinn** [serverless/serverless#6197]
# This is a Bug Report

## Description

I noticed when I updated to v1.44.0 that whenever I try and deploy resources, serverless generates EnterpriseLogAccessIamRole which contains an invalid policy. The cloudformation-template contains the policy LogFilterAccess with an empty Resource array, which is an invalid policy according to AWS.

My serverless.yml:

```
tenant: [omitted]
app: [omitted]

service: auth

frameworkVersion: ">=1.44.0"

plugins:
  - '@serverless/enterprise-plugin'

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

custom:
  stage: ${opt:stage, self:provider.stage}
  cognito:
    app:
      userPool: ${self:service}-app-user-pool-${self:custom.stage}
      identityPool: AppIdentityPoolDev

resources:
  Resources:
    AppUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.cognito.app.userPool}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    MobileAppClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-mobile-app-client-${self:custom.stage}
        UserPoolId:
          Ref: AppUserPool
        GenerateSecret: true

  Outputs:
    AppUserPool:
      Value:
        Ref: AppUserPool
    MobileAppClient:
      Value:
        Ref: MobileAppClient
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.44.1
* ***Operating System***: Mac OS 10.14.5
* ***Stack Trace***:
* ***Provider Error messages***:

> An error occurred: EnterpriseLogAccessIamRole - Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: dc158686-378c-4d01-97fb-1414d55a735d)
