### ISSUE TITLE
Invoke local only works if i provide a `-d` flag

### ISSUE THREAD

**Issue by AleskiWeb** [serverless/serverless#6204]
# This is a Bug Report

## Description

* What went wrong?
For some reason `serverless invoke local -f my-function` does nothing. With `SLS_DEBUG=true` I see it reaches the `Serverless: Invoke invoke:local` and does nothing else. For some reason if i provide a `-d` flag (for data, but leave it empty) then the function runs as per usual: `serverless invoke local -f my-function -d`

* What did you expect should have happened?
The function should run without the necessity to provide a data object/path to a data.json

* What was the config you used?
I am also using `serverless-webpack` and `serverless-plugin-scripts`

```
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

functions:
  db-migrate:
    handler: src/lambda/db-migrate/handler.handler
```

* What stacktrace or error message from your provider did you see?
Nothing

## Additional Data

* ***Serverless Framework Version you're using***: Tried with latest and an older version
* ***Operating System***: Windows 10
* ***Stack Trace***:
* ***Provider Error messages***:
