### ISSUE TITLE
Region is not getting resolved in following configuration

### ISSUE THREAD

**Issue by saumilsdk** [serverless/serverless#6214]
I have used another yml file for loading stage based configuration but unable to get region resolved in that case. Please help.
```

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  configuration: ${file(./deploy/config/${opt:stage, self:provider.stage}.yml)}
  region: ${self:provider.configuration.provider.region}
```
