### ISSUE TITLE
_No VPC_ option for individual Lambda Functions

### ISSUE THREAD

**Issue by jgreen01su** [serverless/serverless#6221]
```yaml
service: service-name

provider:
  name: aws
  vpc:
    securityGroupIds:
      - securityGroupId1
      - securityGroupId2
    subnetIds:
      - subnetId1
      - subnetId2

functions:
  hello:
    handler: handler.hello
    vpc: null

  world:
    handler: handler.world
```
In the above template, I'd expect the `hello` function to not have any VPC and the `world` function to have the VPC from `provider`.

# This is a Feature Proposal

## Description

I’m trying to create an AWS lambda function without a VPC. In my `serverless.yml`, I have a `vpc` defined in `provider` because most of my lambda functions need to run inside it, but I have one function that needs to be run outside with no VPC. I can't find a _No VPC_ option in the documentation.
