### ISSUE TITLE
IAM policy on lambda execution role contains incorrect resource prefixes for writing logs when manually specifying function name

### ISSUE THREAD

**Issue by weeniearms** [serverless/serverless#6236]
# This is a Bug Report

## Description

The policies for `logs:CreateLogStream` and `logs:PutLogEvents` actions have resources with an incorrect prefix compared to the created log groups when additionally specifying the function name manually.
As of 1.45.0 these statements are generated with `arn:aws:logs:region:account:log-group:/aws/lambda/{service}-{stage}-{function}:*`, while in 1.44.1 it used to be `arn:aws:logs:region:account:log-group:/aws/lambda/{functionObject.name}:*`.

Due to this bug, no logs show up in CloudWatch for such functions as the created log groups do not match the IAM statements.

Sample config:
```
service: ${self:custom.service.name}

custom:
  service:
    name: log-group-issue-lambda

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  stackName: ${self:custom.service.name}
  apiKeys:
    - ${self:custom.service.name}-key

functions:
  hello:
    name: ${self:custom.service.name}-hello
    handler: handler.hello
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.45.0
* ***Operating System***: Linux 4.15.0-50-generic
* ***Stack Trace***: n/a
* ***Provider Error messages***: none
