### ISSUE TITLE
Authorizer, principalId missing ini Lambda

### ISSUE THREAD

**Issue by tsan** [serverless/serverless#6237]
# This is a Bug Report

## Description

Hi,

So I use serverlees-offline to work on my project, and I use a custom authorizer to check my jwt token. Everythinig is finie and I'm able to get the principalID (event.requestContext.authorizer.principalId). 

```
  myProfile:
    handler: user/UserHandler.myProfile
    events:
      - http:
          path: profile
          method: get
          cors: true
          integration: lambda-proxy
          private: true
          authorizer: verify-token

```

But when deploy on my AWS, the authorizer object is not pass to the lambda. I was using it to get the user id.

I try to look at it but I wasn't able to know why it isn't working when deploy. 

## Additional Data

* ***Serverless Framework Version you're using***: 1.37.1
* ***Operating System***: MacOS 10.14.5
