### ISSUE TITLE
Deployment skipped when stackTags are changed

### ISSUE THREAD

**Issue by psoares-resilient** [serverless/serverless#6243]
# This is a Bug Report

## Description

* What went wrong?

> Serverless skips deployment when stackTags are updated and template remains unchanged.

* What did you expect should have happened?
> The actual CloudFormation resource has changed, so an update should be triggered. forcing the deployment causes an update, but it shouldn't have to be forced to update itself in this situation.
* What was the config you used?
>Simple reproduceable serverless.yml: 
```
service: whatevernamehere

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: eu-west-2
  stackTags:
      product: test-tags-product
      environment: tes-tags-env
      # another: another-tag
      # uncomment the above line after the first deploy

custom:
  s3BucketName: test-tag-bucket-${opt:stage}

resources:
  - Resources:
      FIBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
          BucketName: ${self:custom.s3BucketName}
      FIBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: UserAndRoleLocked
              Action:
                - s3:*
              Effect: Allow
              Resource:
                - arn:aws:s3:::${self:custom.s3BucketName}/*
                - arn:aws:s3:::${self:custom.s3BucketName}
              Principal: '*'
          Bucket:
            Ref: FIBucket
```
* What stacktrace or error message from your provider did you see?
> None, just a serverless message skipping the deployment because service files have not changed.
Similar or dependent issues:
* #12345

## Additional Data

* ***Serverless Framework Version you're using***:
> 1.45.1
* ***Operating System***:
> macOS mojave 10.14.3
* ***Stack Trace***:
> Serverless: Packaging service...
> Serverless: Service files not changed. Skipping deployment...
* ***Provider Error messages***:
