### ISSUE TITLE
AWS lambda 504 Timeout response template does not work

### ISSUE THREAD

**Issue by jormaechea** [serverless/serverless#6245]
# This is a Bug Report

## Description

* What went wrong?
Lambda integration response template's pattern is wrong. It doesn't match lambda's timeout response.
* What did you expect should have happened?
It should have matched and return an HTTP Status 504.
* What was the config you used?
```yml
# serverless.yml
service: SampleService

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  timeout: 1

functions:
  SampleApi:
    handler: SampleApi.handler
    events:
      - http:
          integration: lambda
          path: sample-api
          method: get
          include:
            - SampleApi.js
```
```js
// SampleApi.js
exports.handler = async function(event, context, callback) {
	await new Promise(resolve => setTimeout(() => resolve(), 1500));
	callback();
};
```
* What stacktrace or error message from your provider did you see?
None

Similar or dependent issues:
None

## Additional Data

* ***Serverless Framework Version you're using***:
1.44.1
* ***Operating System***:
Linux Ubuntu 18.04
* ***Stack Trace***:
None
* ***Provider Error messages***:
None
