### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ccarnero** [serverless/serverless#6252]
Similar or dependent issues:
* #4697

Hi,

Trying to automate our deployment process I came across with this code: https://github.com/pavelvlasov/serverless-js-config-example which uses a Javascript's configuration file; and I faced with this issue

Digging into serverless code I found the function resources.js; based on @marlomgirardi comment (#4697), I replaced every occurrence of the path variable from **line 234 to 243** to *"$/path"* and the issue goes away, once I deploy my stack to AMZ everything seems to be right

Because of my lack of knowledge related to amazon's APIG, and how serverless interact with it I'm not sure if this change could impact negatively in other services; that's why I didn't create a new PR; do all these things have some sense? is there a bug or I missing something?

Best Regards
Christian

**Comment by pmuens** [comment]
Hey @ccarnero thanks for opening 👍

Can you share your `serverless.yml` file? Thanks!

**Comment by ccarnero** [comment]
Hi @pmuens, thanks for your time, remember I mention [we are using the approach of using a serverless .js file](https://github.com/pavelvlasov/serverless-js-config-example) instead of a .yml

```
module.exports = {
  "service": "candidateGetPRofile",
  "provider": {
    "name": "aws",
    "runtime": "nodejs8.10",
    "stage": "poc",
    "region": "sa-east-1",
    "versionFunctions": false,
    "timeout": 30,
    "logLevel": "debug",
    "iotEndpointPrefix": "iot-ats",
    "apiGateway": {
      "restApiId": {
        "Fn::ImportValue": "api-gateway:poc:rest-api-id"
      },
      "restApiRootResourceId": {
        "Fn::ImportValue": "api-gateway:poc:root-resource-id"
      },
      "restApiResources": {
        "/": "rootId",
        "/candidate": "candidateID",
        "/candidate/{idCandidate}": "candidate/idCandidateID"
      }
    }
  },
  "functions": {
    "newGetProfile": {
      "handler": "getProfile.handler",
      "events": [
        {
          "http": {
            "path": "/candidate/{idCandidate}",
            "method": "get",
            "cors": true,
            "authorizer": {
              "type": "CUSTOM",
              "authorizerId": {
                "Fn::ImportValue": "....."
              }
            }
          }
        }
      ],
      "layers": [
        "${cf:aws-layer-layer1}",
        "${cf:aws-layer-layer2}"
      ]
    }
  }
}
``` 

best regards
Christian

**Comment by fzaffarana** [comment]
Same. 

I had some problems implementing js in serverless, because there isn't enough information about it.

Any good source for that?

**Comment by 300LiterPropofol** [comment]
I am trying to deploy serverless from gitlab CI so changing the source code of serverless software is not really an option for me. I wonder whether the serverless team have fixed this `restApiResources` path issue since this question is still open in 2021 June.

**Comment by pgrzesik** [comment]
Hello @300LiterPropofol - could you please share what version of Serverless Framework are you using and if possible, a small reproducible example that would help us diagnosing the issue? The original one is quite outdated.

**Comment by 300LiterPropofol** [comment]
Thank you for your quick response @pgrzesik! I am using serverless 2.41.2
```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.4.0
     Framework Version:         2.41.2 (standalone)
     Plugin Version:            5.0.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
```
The issue I hit is exactly as marlomgirardi mentioned in this [#4697](https://github.com/serverless/serverless/issues/4697)
My serverless.yml is: 
```
service: myservice

frameworkVersion: '2'
useDotenv: true
unresolvedVariablesNotificationMode: error
variablesResolutionMode: 20210326
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'temp'}
  region: eu-west-1
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221
  apiGateway:
    restApiId: ${env:rest_api_id}
    restApiRootResourceId: ${env:root_source_id}
    restApiResources: 
      /pats: {env:path_id}
  
package:
  patterns:
    - '!README.md'

functions:
  pats_handler:
    handler: handler.patsHandler
    memorySize: 1024
    timeout: 120
    events:
      - http:
          path: pats
          method: post
          cors: true
```
The issue occurs on `restApiResources:` field, if I write my serverledd.yml file exactly like above. I will have `TypeError: Cannot read property 'name' of undefined` error, if I changed the above as marlomgirardi suggested to `restApiResources:  pats: {env:path_id}`, i.e., remove the `/`, I will get `An error occurred: ApiGatewayMethodPatsDashreportsOptions - Method already exists for this resource (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: d93b6d8a-cfc7-40fd-ac05-b8102b3c0028; Proxy: null).` error, same error as marlomgirardi pointed out.

**Comment by 300LiterPropofol** [comment]
Let me explain myself more in case it helps. The thing I am trying to do here is:
I already have an api gateway and a HTTP endpoint to post to, which is set by another serverless service. Therefore I have the restApiId, restApiRootResourceId and restApiResources id for the already set path, i.e., `http://mydomian.io/pats`.
And now I would like to add another lambda function that listens to the same endpoint request but pass the event somewhere else, i.e., `POST http://mydomian.io/pats` is supposed to trigger 2 lambda functions, one is the previous working one, and another is the serverless.yml I posted above. I met issue deploying the second lambda since it seems it can not reuse the `restApiResources`.

**Comment by 300LiterPropofol** [comment]
Hi @pgrzesik , sorry to disturb. I wonder has there been some progress on this path issue? I searched the repository and couldn't found the aforementioned '$/path' code. Should I raise a new issue on this?

**Comment by pgrzesik** [comment]
Hello @300LiterPropofol - thanks for additional explanation - unfortunatelly I did not have time to dive deeper into this specific issue. One question I have because I'm not sure - is it possible to hook up more than 1 Lambda to the same endpoint? How would that even work? Response from which handler would be returned to the user? The error you get (see below) suggests that it's not possible

```
An error occurred: ApiGatewayMethodPatsDashreportsOptions - Method already exists for this resource (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: d93b6d8a-cfc7-40fd-ac05-b8102b3c0028; Proxy: null).
```

**Comment by 300LiterPropofol** [comment]
Thanks for your response! That's a good point. Now I'm not sure whether I understand the serverless document correctly or not. From my understanding, the field `restApiId`,  `restApiRootResourceId` and `restApiResources` exist for reusing the same api gateway, same api root path and same api unroot path. Maybe my interpretation was wrong in the beginning? If it is not possible to hook 2 lambdas to the same endpoint at all, I wonder what the `restApiResources` field is used for in `serverless.yml`.

**Comment by pgrzesik** [comment]
Hey @300LiterPropofol - if I'm not mistaken, `restApiResources` is used to list all already existing resources e.g. if you already have `/posts` defined and you try to define `/posts/{id}` for that API it will error out if you don't specify `/posts` in `restApiResources`.

**Comment by henrydobson** [comment]
Hi everyone, I have been experiencing this issue today and in my troubleshooting found a possible solution for cases where AWS::ApiGateway::Method resources are defined in resources for the REST API Resources you're trying to share.

I’m using Serverless compose and a global API gateway definition but I’ve run into this bug.

In summary, when I attempt to reference the existing REST API Resources in a service using Fn::Import (or any other method including hard coding the ResourceId), I get the following error if the key starts with /
`TypeError: Cannot read properties of undefined (reading 'name')`
and I get a already exists in stack conflict when I remove it.
`CREATE_FAILED: ApiGatewayMethodNolocoDashvalidatorPost (AWS::ApiGateway::Method)
xxxxxxxx|yyyyy|POST already exists in stack arn:aws:cloudformation:xxxxx:xxxxxxx:stack/xxxxxx/xxxxxxxx`
There doesn’t seem to be a valid way to reference these APIs.

Here’s some code samples:
```
# global/serverless.yml
...
resources:
  Resources:
    ...
    StripeValidatorResource:
      Type: 'AWS::ApiGateway::Resource'
      Properties:
        RestApiId: !Ref ApiGw
        ParentId: !GetAtt ApiGw.RootResourceId
        PathPart: 'stripe-validator'
    StripeValidatorMethodPost:
      Type: 'AWS::ApiGateway::Method'
      Properties:
        RestApiId: !Ref ApiGw
        ResourceId: !Ref StripeValidatorResource
        HttpMethod: POST
        ApiKeyRequired: false
        AuthorizationType: NONE
        Integration:
          Type: MOCK
    StripeValidatorApiDeployment:
      Type: 'AWS::ApiGateway::Deployment'
      DependsOn:
        - StripeValidatorMethodPost
      Properties:
        RestApiId: !Ref ApiGw
        StageName: ${self:provider.stage}
  Outputs:
    StripeValidatorRestApiResource:
      Value:
        Fn::GetAtt:
          - StripeValidatorResource
          - ResourceId
      Export:
        Name: ApiGw-StripeValidatorResource

# service/serverless.yml
...
provider:
  apiGateway:
    restApiId:
      'Fn::ImportValue': ApiGw-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': ApiGw-rootResourceId
    restApiResources:
      'stripe-validator':                                 # attempted with and without / 
        'Fn::ImportValue': ApiGw-StripeValidatorResource
```

Resolution for me was achieved by removing AWS::ApiGateway::Method resources from the global/serverless.yml and removing the `/` from the restApiResources keys.

I hope this helps someone else.
