### ISSUE TITLE
How to split monolith serverless project into micro service serverless for  cloud formation resource limit 200 error?

### ISSUE THREAD

**Issue by bala1074** [serverless/serverless#6260]
**Monolith serverless.yml**
```
service: microservices-node-rest-api
provider:
  name: aws
  runtime: nodejs8.10
functions:
  getSvc1:
    handler: service1/service1.get
    events:
    - http:
        path: service1
        method: get
        cors: true
  getSvc2:
    handler: service2/service2.get
    events:
    - http:
        path: service2
        method: get
        cors: true
```

**Micro-service serverless.yml**
```
service: ms-poc-svc1
provider:
  name: aws
  runtime: nodejs8.10
  apiGateway:
    restApiId: https://veralccm3c.execute-api.us-east-1.amazonaws.com
functions:
  getSvc1:
    handler: service1.get
    events:
    - http:
        path: service1
        method: get
        cors: true
```

When I try to deploy micro service I am getting errors.
 The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource ApiGatewayRestApi

Is this the right way of tranforming existed monolith serverless app to microservice app with multiple serverless.yml specific to each micro service. If yes, how to deploy all micro services at once..
