### ISSUE TITLE
Using 2 or more "CloudWatchLog event handlers" for the same lambda fails to create correct permissions

### ISSUE THREAD

**Issue by rickalm** [serverless/serverless#6266]
# This is a Bug Report

## Description

```
functions:
  dummy-logger:
    handler: handler.logger
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/yada-${self:provider.stage}-dummy'
          filter: 'REPORT'
      - cloudwatchLog:
          logGroup: '/aws/lambda/yada-${self:provider.stage}-dummy2'
          filter: 'REPORT'
```

* 2 AWS::Logs::SubscriptionFilter objects are created (using index see issue #6263)
* Only one AWS::Lambda::Permission is created (likely from index 1/blank)
* Permission Object only refers to logGroup from first SubscriptionFilter handler
* Template fails with:
`Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function. (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 0b096e01-87d2-11e9-b52a-59a1410a5e04)`

Similar or dependent issues:
* #5833
* #6263

## Additional Data

* serverless@1.44.1
* Ubuntu and MacOs(Darwin)
* 'Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function. (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 0b096e01-87d2-11e9-b52a-59a1410a5e04)'
* As reported on 6/5 [forum.serverless.com](https://forum.serverless.com/t/aws-provider-fails-if-2-or-more-cloudwatchlog-events-listed/8483)
