### ISSUE TITLE
Include and RENAME file

### ISSUE THREAD

**Issue by cyberfox1** [serverless/serverless#6269]
package:
      individually: true
      exclude:
        - ./**
      include:
        - foo-${self:custom.stage}.js:bar.js

**Comment by medikoo** [comment]
@cyberfox1 I don't understand this report, can you share more details?

**Comment by Necromancerx** [comment]
He wants to include `foo-dev.js` then rename it to `bar.js` afterwards. Is this currently supported? Thanks

**Comment by medikoo** [comment]
@Necromancerx it is. See example in docs: https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-in-other-files

**Comment by Necromancerx** [comment]
@medikoo does this support folder? I want to move/rename the included external lib folder `/external-lib/Cryptodome` and move it to the root folder of the lambda package as `/Cryptodome/`.

```
package:
  individually: true
  exclude:
    - ./**
  include:
    - ../../external-lib/Cryptodome/**:Cryptodome/ #doesn't work
    - ../../external-lib/Cryptodome/**:Cryptodome/** #doesn't work
```

**Comment by medikoo** [comment]
@Necromancerx paths outside of service context will not work. Base for packing in Framework logic is service folder, against that you may apply `include` and `exclude` rules

**Comment by piyushk96** [comment]
@medikoo I think you have shared the wrong link.
I also have the same requirement. I have a file in `private/config.test.js` and I want this file to be included as `private/config.js` in my serverless package. I don't think this functionality of renaming files is currently supported by serverless.

**Comment by medikoo** [comment]
Sorry, indeed I didn't get this request initially.

Framework internal packaging, packages files as is, if you want to rely on bundling of any other file processing (as renaming) you need to resort to plugins.

Note that extending current patterns format with proposal as `<sourceName>:<destName>` is not on a table. Patterns are glob patterns and `foo:bar` is a valid glob pattern, so it won't be a great idea to introduce an ambiguity here.

Technically this could work as:

```yaml
package:
  renameInstructions:
    - source: foo-${self:custom.stage}.js
      dest: bar.js
```

But as mentioned such feature should rather be introduced via plugin and not be part of a core (due to low demand)
