### ISSUE TITLE
Support shared websocket API

### ISSUE THREAD

**Issue by christophgysin** [serverless/serverless#6270]
# This is a Feature Proposal

## Description

We currently support sharing the AWS::ApiGateway::RestApi using:
```yaml
provider:
  apiGateway:
    restApiId: xxxxxxxxx
```
I would like to be able to also support sharing the websocket API (AWS::ApiGatewayV2::Api), e.g. using:
```yaml
provider:
  apiGateway:
    restApiId: xxxxxxxxx
    websocketApiId: yyyyyyyyy
```
