### ISSUE TITLE
Serverless not in sync with aws console

### ISSUE THREAD

**Issue by jasonlimantoro** [serverless/serverless#6273]
# This is a Feature Proposal

## Description
The serverless deployment must keep the configurations in the AWS Management Console **in sync** with `serverless.yml`

## Example use case flow: 
1. My `serverless.yml` file
```yml
functions:
  graphql:
    handler: graphql.hello
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer: aws_iam
      - http:
          path: graphql
          method: get
          cors: true
          authorizer: aws_iam
```
2. I go to AWS Management Console in the API Gateway section
3. I manually change the authorizer of one of the endpoints from `AWS_IAM` to `NONE`
4. I run again `serverless deploy` without any modification to the file
5. The configuration still says `NONE` instead of `AWS_IAM`, which makes it out of sync with the `serverless.yml`.

## Expected behavior
The deployment should overwrite the conflicting configuration.

## Additional notes
I was wondering if the `--force` flag solved it. But it didn't. I guess the flag was made for another use case.
The use case is not limited to just lambda authorizer but applies to other configs as well, (e.g. S3, Dynamodb, etc.).

## Similar or dependent issues:
- I haven't found any

Any ideas are welcome :)
