### ISSUE TITLE
Deployment not skipped, even if no change, when artifact is specified in package section

### ISSUE THREAD

**Issue by RJEah1** [serverless/serverless#6274]
# This is a Bug Report

## Description

* What went wrong?
Stack deployment is not skipped when no change and when the artifact is specified in package section. I use maven to build artifact from java sources. Example: 
package:
  artifact: target/my-artifact.jar

I do 2 successive sls deploy --stage XXX with the same artifact (one build only)

If I don't specify the artifact, so that, a zip file is generated, there is no problem with my 2 successive deploy. The second deployment is skipped because there is no change.

* What did you expect should have happened?
I think, even if I specify an artifact, the deployment should be skipped when the artifact (and also the stack) is the same.

* What was the config you used?
Serverless 1.45.1. 
MacOS, Windows10/UbuntuBash
Build java sources with maven.
* What stacktrace or error message from your provider did you see?
No error. Normal traces: 
sls deploy --stage XXX
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service my-artifact.jar file to S3 (30.78 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....
Serverless: Stack update finished...
Service Information
...

## Additional Data

* ***Serverless Framework Version you're using***: 1.45.1
* ***Operating System***: Windows 10/Ubuntu bash, MacOS Mojave 10.14.5
* ***Stack Trace***: No error
* ***Provider Error messages***: No error

**Comment by yyamano** [comment]
I can't reproduce it. 

@RJEah1 I'm not sure if I understand the procedure correctly. I'm wondering if you can show me your serveless.yml and tell me what exactly you did?

Here is my procedure.

1. Generate a java maven project by "sls create -t aws-java-maven"
2. Apply the following change.

```
--- serverless.yml.orig	2021-04-14 17:29:13.000000000 +0900
+++ serverless.yml	2021-04-14 17:52:39.000000000 +0900
@@ -11,7 +11,7 @@
 #
 # Happy Coding!
 
-service: aws-java-maven
+service: yyamano-aws-java-maven
 # app and org for use with dashboard.serverless.com
 #app: your-app-name
 #org: your-org-name
@@ -91,6 +91,8 @@
 #          conditions:
 #            host: example.com
 #            path: /hello
+  hello2:
+    handler: com.serverless.Handler
 
 #    Define function environment variables here
 #    environment:
```

3. Build a jar by "mvn package"
4. Deploy  the jar by "sls deploy"

```
% sls deploy
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service hello-dev.jar file to S3 (3.22 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..............
Serverless: Stack update finished...
Service Information
service: yyamano-aws-java-maven
stage: dev
region: us-east-1
stack: yyamano-aws-java-maven-dev
resources: 9
api keys:
  None
endpoints:
  None
functions:
  hello: yyamano-aws-java-maven-dev-hello
  hello2: yyamano-aws-java-maven-dev-hello2
layers:
  None
% sls deploy
Serverless: Packaging service...
Serverless: Service files not changed. Skipping deployment...
Service Information
service: yyamano-aws-java-maven
stage: dev
region: us-east-1
stack: yyamano-aws-java-maven-dev
resources: 9
api keys:
  None
endpoints:
  None
functions:
  hello: yyamano-aws-java-maven-dev-hello
  hello2: yyamano-aws-java-maven-dev-hello2
layers:
  None
```
