### ISSUE TITLE
Unable to run sls remove after adding apiKeys

### ISSUE THREAD

**Issue by joetravis** [serverless/serverless#6283]
# This is a Bug Report

## Description

* What went wrong?
** I am unable to run `sls remove` successfully after adding apiKeys to my serverless config, as it appears that the removal process for apiKeys is inappropriately appending stage name to the stack name  
* What did you expect should have happened?
** Running `sls remove` should remove the stack successfully, including api keys
* What was the config you used?
```
service:
  name: ${opt:env}-${self:provider.region}-${self:custom.name}

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage}
  region: ${self:custom.config.region}
  stackName: ${self:service.name}
  apiKeys:
  - statusCheckKey-${opt:env}
  logRetentionInDays: 14
  logs:
    restApi: true
```
* What stacktrace or error message from your provider did you see?
```
Serverless: [AWS cloudformation 400 0.403s 0 retries] describeStackResource({ StackName: 'pr-43-us-west-2-xxx-pr-43',
  LogicalResourceId: 'ApiGatewayRestApi' })
 
  Serverless Error ---------------------------------------
 
  Stack 'pr-43-us-west-2-xxx-pr-43' does not exist
 
  Stack Trace --------------------------------------------
 
ServerlessError: Stack 'pr-43-us-west-2-xxx-pr-43' does not exist
    at promise.catch.err (/home/circleci/repo/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:302:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Similar or dependent issues:
* 

## Additional Data
```
  Your Environment Information ---------------------------
     OS:                     linux
     Node Version:           10.14.2
     Serverless Version:     1.44.1
```
* ***Serverless Framework Version you're using***:
** 1.44.1
* ***Operating System***:
** linux
* ***Stack Trace***:
** see above
* ***Provider Error messages***:
** see above
