### ISSUE TITLE
sls deploy doesn't create layers neither associate layer to my function

### ISSUE THREAD

**Issue by MacHu-GWU** [serverless/serverless#6295]
## Description

* What went wrong? ``serverless deploy`` command doesn't deploy my layers. I think I followed the tutorial correctly https://serverless.com/framework/docs/providers/aws/guide/layers/
* What did you expect should have happened? **I expect in my lambda console, the layer is specified and a new layer version has been created.***
* What was the config you used?

```yml
# -*- coding: utf-8 -*-
# all available properties in serverless.yml when provider is aws
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service:
  name: my-service # ${file(./config/config-final-for-python.json):SERVICE_NAME_SLUG}

provider:
  name: aws
  stage: dev
  stackName: my-service-dev
  runtime: python3.6
  region: us-east-1
  profile: my_aws_profile
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: my-deploy-bucket-name
  deploymentPrefix: serverless
  role: arn:aws:iam::xxx:role/lambda-basic-execution
  versionFunctions: false

package:
  artifact: ./build/lambda/source.zip

layers:
  all_in_one_layer:
    package:
      artifact: <absolute-path-to-layer>/layer.zip
    name: my-service-dev
    compatibleRuntimes:
      - python3.6
    allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
      - '*'
    retain: false

functions:
  my_func:
    handler: my_service.handlers.my_func.handler
    description:
    layers:
      - {Ref: all_in_one_layer}
```

* What stacktrace or error message from your provider did you see? **I didn't see layer in my function console, and no layers been created.**
