### ISSUE TITLE
Documentation for SLS X Kubeless is incorrect and can lead to severe crashes from Kubeless

### ISSUE THREAD

**Issue by Eurymone** [serverless/serverless#6297]
# This is a Bug Report

## Description

The documentation for Serverless X Kubeless is wrong regarding one of the example provided by the documentation:

```yml
service: service-name
provider:
  name: kubeless
  environment:
    SYSTEM_NAME: mySystem
    TABLE_NAME: tableName1

plugins:
  - serverless-kubeless

functions:
  users:
    # The kubernetes secret  will be mounted at `/secret1`
    # Note that the secret cannot have any `/`'s in the name
    handler: handler.users
    environment:
    # The environment variable `PROD_USER_PASSWORD` would be set to "happy"
      - name: PROD_USER_PASSWORD
        valueFrom:
            secretKeyRef:
              - name: secret1
                key: password
```
The dash in yaml is for collection, while the `secretKeyRef` should contain an object with 2 properties instead.

It causes massive crashes from Kubeless that ends up up being unable to list functions anymore and refuse any updates on any functions until the problem is fixed. 

While the reaction from kubeless to this configuration error should probably be handled better, I believe we could fix the documentation on SLS as well by moving from:
```
    environment:
    # The environment variable `PROD_USER_PASSWORD` would be set to "happy"
      - name: PROD_USER_PASSWORD
        valueFrom:
            secretKeyRef:
              - name: secret1
                key: password
```
To:
```
    environment:
    # The environment variable `PROD_USER_PASSWORD` would be set to "happy"
      - name: PROD_USER_PASSWORD
        valueFrom:
            secretKeyRef:
              name: secret1
              key: password
```
* What stacktrace or error message from your provider did you see?
Nothing. SLS and SLS-Kubeless don't raise any error to this configuration.

## Additional Data

* ***Serverless Framework Version you're using***: 
serverless: 1.43.0
serverless-kubeless : 0.7.1
* ***Operating System***: 
Debian stretch
