### ISSUE TITLE
#6240 made lambda execution role names longer, violating maxlength constraint

### ISSUE THREAD

**Issue by russell-dot-js** [serverless/serverless#6338]
# This is a Bug Report

## Description

- What went wrong?
#6240 made the IAM role names longer by appending "lambdaRole" to the end, violating the length constraint

- What did you expect should have happened?
IAM role names should be in same format

- What was the config you used?
Minimal serverless.yml below:

```
service:
  name: hello-i-am-borke-service

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10

  iamRoleStatements:
    # lambda
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - "*"
    
functions:
  borken:
    handler: src/handlers/borken.handle
    timeout: 30
    iamRoleStatementsInherit: true
    iamRoleStatements:
        # sf
        - Effect: "Allow"
          Action:
            - "states:StartExecution"
          Resource:
            - "*"

plugins:
  - serverless-iam-roles-per-function
```

Run with sls deploy --stage=staging or --stage=production to repro

- What stacktrace or error message from your provider did you see?
Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: ...).

- Related to:
https://github.com/serverless/serverless/issues/2856

## Additional Data
- framework version >= 1.45.1
