### ISSUE TITLE
Alb events for lambda named with underscore

### ISSUE THREAD

**Issue by dorperetzvia** [serverless/serverless#6339]
# This is a Bug Report

## Description
Cannot use alb event on function which contains '_' (underscore) in their name

- What went wrong?
 while deploying a stack with lambda called `update_config` with an alb event,
got an error. once renaming the lambda to `update-config` everything went smooth

- What did you expect should have happened?
- What was the config you used?
  using aws as provider
- What stacktrace or error message from your provider did you see?
  An error occurred: UpdateUnderscoreconfigAlbTargetGroup - Target group name 'update_config-dev' can only contain characters that are alphanumeric characters or hyphens(-) (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: 33fabf56-a08b-11e9-b1f8-a3442cc5e4a9).

Similar or dependent issues:

## Additional Data
using 
- **1.46.1**:
- **mac**:
- **_Stack Trace_**:
- **An error occurred: UpdateUnderscoreconfigAlbTargetGroup - Target group name 'update_config-dev' can only contain characters that are alphanumeric characters or hyphens(-) (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: 33fabf56-a08b-11e9-b1f8-a3442cc5e4a9).
**:

**Comment by cbm-egoubely** [comment]
I think this will be fixed by #6322 on the next release.

**Comment by cbm-egoubely** [comment]
I can confirm that this is fixed by the latest release.
I think you can close the issue @pmuens.

To test : 

```yaml
service: test

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false

package:
  excludeDevDependencies: false
  exclude:
  - '**/*'
  include:
  - ./hello.js

functions:
  hello_world:
    handler: hello.hello
    events:
      - alb:
          listenerArn: { Ref: HTTPListener }
          priority: 5
          conditions:
            path: /hello

custom:
  defaultRegion: us-east-1
  defaultStage: dev
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  objectPrefix: '${self:service}-${self:custom.stage}'

resources:
  Outputs:
    LoadBalancerDNSName:
      Value: { 'Fn::GetAtt': [ LoadBalancer, 'DNSName' ] }
      Export: { Name: '${self:custom.objectPrefix}-LoadBalancerDNSName' }
    ListenerArn:
      Value: { 'Ref': HTTPListener }
  Resources:
    VPC:
      Type: 'AWS::EC2::VPC'
      Properties:
        CidrBlock: 172.31.0.0/16
        EnableDnsHostnames: true
    InternetGateway:
      Type: 'AWS::EC2::InternetGateway'
    VPCGatewayAttachment:
      Type: 'AWS::EC2::VPCGatewayAttachment'
      Properties:
        VpcId: { Ref: VPC }
        InternetGatewayId: { Ref: InternetGateway }
    RouteTable:
      Type: 'AWS::EC2::RouteTable'
      Properties:
        VpcId: { Ref: VPC }
    InternetRoute:
      Type: 'AWS::EC2::Route'
      DependsOn: VPCGatewayAttachment
      Properties:
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: { Ref: InternetGateway }
        RouteTableId: { Ref: RouteTable }
    SubnetA:
      Type: 'AWS::EC2::Subnet'
      Properties:
        AvailabilityZone: '${self:custom.region}a'
        CidrBlock: 172.31.0.0/20
        MapPublicIpOnLaunch: false
        VpcId: { Ref: VPC }
    SubnetB:
      Type: 'AWS::EC2::Subnet'
      Properties:
        AvailabilityZone: '${self:custom.region}b'
        CidrBlock: 172.31.16.0/20
        MapPublicIpOnLaunch: false
        VpcId: { Ref: VPC }
    SubnetARouteTableAssociation:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
        SubnetId: { Ref: SubnetA }
        RouteTableId: { Ref: RouteTable }
    SubnetBRouteTableAssociation:
      Type: 'AWS::EC2::SubnetRouteTableAssociation'
      Properties:
        SubnetId: { Ref: SubnetB }
        RouteTableId: { Ref: RouteTable }
    SecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupName: 'http-https'
        GroupDescription: 'HTTPS / HTTPS inbound; Nothing outbound'
        VpcId: { Ref: VPC }
        SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        -
          IpProtocol: -1
          FromPort: '1'
          ToPort: '1'
          CidrIp: 127.0.0.1/32
    LoadBalancer:
      Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
      Properties:
        Type: 'application'
        Name: '${self:custom.objectPrefix}'
        IpAddressType: 'ipv4'
        Scheme: 'internet-facing'
        LoadBalancerAttributes:
        - { Key: 'deletion_protection.enabled', Value: false }
        - { Key: 'routing.http2.enabled', Value: false }
        - { Key: 'access_logs.s3.enabled', Value: false }
        SecurityGroups:
        - { Ref: SecurityGroup }
        Subnets:
        - { Ref: SubnetA }
        - { Ref: SubnetB }
    HTTPListener:
      Type: 'AWS::ElasticLoadBalancingV2::Listener'
      Properties:
        LoadBalancerArn: { Ref: LoadBalancer }
        Port: 80
        Protocol: 'HTTP'
        DefaultActions:
        -
          Type: 'fixed-response'
          Order: 1
          FixedResponseConfig:
            StatusCode: 404
            ContentType: 'application/json'
            MessageBody: '{ "not": "found" }'
```
