### ISSUE TITLE
Step Function Action not deployed

### ISSUE THREAD

**Issue by Feint90** [serverless/serverless#6352]
# This is a Bug Report

## Description

- What went wrong?
When deploying a step function that is hooked to an existing API gateway, the action is not deployed to the gateway.
** Doc article how it should work according to you: https://serverless.com/plugins/serverless-step-functions/#custom-step-functions-action
- What did you expect should have happened?
For the API Gateway to have the configured action set.
- What was the config you used?
```
stepFunctions:
  stateMachines:
    StepFuncName:
      name: StepFuncName
      events:
        - http:
            path: /path
            method: POST
            action: StartExecution
      definition:
           ...
```
- What stacktrace or error message from your provider did you see?
None, SLS says it deployed succesfully
Similar or dependent issues:
None that I could find
## Additional Data
I tested pointing the step function to a new path and it would deploy succesfully, if I try to deploy to an existing path, it did not deploy the action.

- **_Serverless Framework Version you're using_**: 1.46.1
- **_Operating System_**: Win10/Linux shell/ build pipeline
- **_Stack Trace_**:
- **_Provider Error messages_**:
