### ISSUE TITLE
CW alarms created from stateMachines contain multipe "Dash" in alarm name

### ISSUE THREAD

**Issue by airmonitor** [serverless/serverless#6353]
# This is a Bug Report

## Description

- What went wrong?
Very long CW alarm, contain "Dash" instead of "-". Alarm was created from stateMachines.

> IoTAutomation-prd-IoTAutomationDashprdDashIoTAutomationExecutionsFailedAlarm-DKXRCQPR5LVQ

- What did you expect should have happened?

> IoTAutomation-prd-IoTAutomation-prd-IoTAutomationExecutionsFailedAlarm-DKXRCQPR5LVQ

- What was the config you used?
```
stepFunctions:
  stateMachines:
    IoTAutomation:
      alarms:
        topics:
          ok: ${self:provider.sns_cloudwatch_alarm_topic}
          alarm: ${self:provider.sns_cloudwatch_alarm_topic}
          insufficientData: ${self:provider.sns_cloudwatch_alarm_topic}
        metrics:
          - executionsFailed
```

- What stacktrace or error message from your provider did you see?
There is no stack trace

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: 1.46.1
- **_Operating System_**: Linux Mint 19.1
- **_Stack Trace_**: N/A
- **_Provider Error messages_**: N/A
