### ISSUE TITLE
Support for the new Amazon EventBridge - New Event-Driven Service from AWS

### ISSUE THREAD

**Issue by majoraze** [serverless/serverless#6363]
# This is a Feature Proposal

## Description

- Amazon launched the EventBridge Service as a Event-driven between your own apps and SaaS services.

Links from the product:
https://aws.amazon.com/eventbridge/
https://aws.amazon.com/blogs/aws/amazon-eventbridge-event-driven-aws-integration-for-your-saas-applications/
https://aws.amazon.com/about-aws/whats-new/2019/07/introducing-amazon-eventbridge/

It will be a nice feature to use in favor of SQS or Kinesis streams in some situations.

**Comment by pmuens** [comment]
Hey @majoraze thanks for adding :+1:

We're already looking into that. Would be super awesome if people can share proposals for a potential `serverless.yml` configuration.

Also ccing @serverless/framework-maintainers here.

**Comment by pmuens** [comment]
Hey everyone,
I just spent some time to look into this today. The following are some useful resources I've used to understand how the `EventBridge` differs from traditional CloudWatch events:

- https://aws.amazon.com/about-aws/whats-new/2019/07/introducing-amazon-eventbridge/
- https://aws.amazon.com/blogs/aws/amazon-eventbridge-event-driven-aws-integration-for-your-saas-applications/
- https://docs.aws.amazon.com/eventbridge/index.html?shortFooter=true
- https://docs.aws.amazon.com/eventbridge/latest/userguide/what-is-amazon-eventbridge.html
- https://docs.aws.amazon.com/eventbridge/latest/APIReference/Welcome.html
- https://console.aws.amazon.com/events/home?region=us-east-1#/rules/create

Generally speaking the `EventBridge` is a higher-level abstraction on top of CloudWatch events. As you all might know we've already got the `schedule` and `cloudwatchEvent` event types, so the `serverless.yml` equivalent for the `eventBridge` event can be derived from that.

Here's my proposal for the 2 types an `eventBridge` event can have:

```
service: test

provider:
  name: aws
  runtime: nodejs10.x

functions:
  test:
    handler: handler.handler
    events:
      - eventBridge:
          name: schedule-event-bridge
          # leave the `eventBus` property empty to use the default AWS event bus
          eventBus: arn:aws:events:us-east-1:444455556666:event-bus/default
          # accepts the same arguments as our `schedule` event source
          schedule: rate(10 minutes)
          # `input` OR
          input:
            key1: value1
            key2: value2
            stageParams:
              stage: dev
          # `inputPath` OR
          inputPath: '$.stageVariables'
          # `inputTransformer`
          inputTransformer:
            inputPathsMap:
              eventTime: '$.time'
            inputTemplate: '{"time": <eventTime>, "key1": "value1"}'
      - eventBridge:
          name: pattern-event-bridge
          # leave the `eventBus` property empty to use the default AWS event bus
          eventBus: arn:aws:events:us-east-1:444455556666:event-bus/default
          pattern:
            source:
              - aws.cloudformation
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - cloudformation.amazonaws.com
          # `input` OR
          input:
            key1: value1
            key2: value2
            stageParams:
              stage: dev
          # `inputPath` OR
          inputPath: '$.stageVariables'
          # `inputTransformer`
          inputTransformer:
            inputPathsMap:
              eventTime: '$.time'
            inputTemplate: '{"time": <eventTime>, "key1": "value1"}'
```

Apparently there's no CloudFormation support for the time-being. Given that I'd propose that we leverage our custom CloudFormation capabilities we've just added with the last release (see #6290 and #6362).

Let me know what you think! Does it makes sense? Are we missing something?
