### ISSUE TITLE
No multiple events for existing S3 bucket possible

### ISSUE THREAD

**Issue by rmbl** [serverless/serverless#6369]
# This is a Bug Report

## Description

I can't add multiple event types to the same bucket and same function. Trying to deploy it throws an error because the statement id seems to be the same for both (internal) lambda functions.

Config:
```
  s3-events:
    handler: events/s3-events.handler
    events:
      - s3:
          bucket: ${self:custom.config.images.bucket}
          existing: true
          event: s3:ObjectCreated:*
      - s3:
          bucket: ${self:custom.config.images.bucket}
          existing: true
          event: s3:ObjectRemoved:*
```

## Additional Data

- **_Serverless Framework Version you're using_**: 1.47.0
- **_Operating System_**: Linux Mint 19.1
- **_Stack Trace_**: None
- **_Provider Error messages_**: The statement id (${api}-${stage}-${function}-${bucket}) provided already exists. Please provide a new statement id, or remove the existing statement.
