### ISSUE TITLE
Cannot create disabled schedule using syntax 'enabled: false'

### ISSUE THREAD

**Issue by mbacchi** [serverless/serverless#6381]
# This is a Bug Report

## Description
Deploying a scheduled function produces a CFN template with `"State": "ENABLED"` regardless of what string is used in the serverless.yml `enabled` field.

If I use `enabled: true` the CFN json contains: `"State": "ENABLED"`

If I use `enabled: false` the CFN json contains: `"State": "ENABLED"`

If I use `enabled: whatever` the CFN json contains: `"State": "ENABLED"`

- What went wrong?
The schedule is always enabled, even when using the syntax `enabled: false`

- What did you expect should have happened?
The schedule should be disabled if using `enabled: false`

- What was the config you used?
Names changed to protect the innocent, this is the functions section of my serverless.yml
```
functions:
  myfunc:
    handler: myfile.myfunc
    events:
      - schedule: rate(1 minute)
        enabled: false
```
- What stacktrace or error message from your provider did you see?
None, it just always runs the function even though the schedule should be disabled.

Similar or dependent issues:

- This was reported in the forum [here](https://forum.serverless.com/t/bug-serverless-yml-functions-fn-name-events-enabled-does-not-control-aws-rule-state-value-at-all/8310) but there seems to be no answer or resolution to that report.

## Additional Data

- **_Serverless Framework Version you're using_**:
sls --version
1.46.1
- **_Operating System_**:
Linux
- **_Stack Trace_**:
N/A
- **_Provider Error messages_**:
N/A

**Comment by pmuens** [comment]
Hey @mbacchi thanks for opening :+1:

It looks like your `serverless.yml` is not formatted correctly. Here's how it should look like:

```yaml
functions:
  myfunc:
    handler: myfile.myfunc
    events:
      - schedule:
           rate(1 minute)
           enabled: false
```
