### ISSUE TITLE
minimumSizeCompression is not updated in apiGateway

### ISSUE THREAD

**Issue by CyrineBS** [serverless/serverless#6396]
# This is a Bug Report

## Description

I'm using the serverless-api-compression plugin and it's working fine. Except that the minimumCompressionSize remains 0 whatever value I choose.

I followed the documentation https://serverless.com/framework/docs/providers/aws/events/apigateway#compression and here is my serverless.yml: 
```
provider:
     name: aws
     runtime: nodejs8.10
     region: eu-west-1
     apiGateway:
        minimumCompressionSize: 1024
...
```

See attached image bellow. The compression is activated but the minimumCompressionSize is never updated.

![Capture d’écran 2019-07-18 à 10 41 25](https://user-images.githubusercontent.com/16957806/61442937-caff9e00-a948-11e9-9df0-0b88867dca41.png)

## Additional Data

- **_Serverless Framework Version you're using_**: 1.46.1
- nodeJs version: nodejs8.10
