### ISSUE TITLE
Conflicting API keys when deploying same aws service to different stages

### ISSUE THREAD

**Issue by aslettemark** [serverless/serverless#6400]
# This is a Bug Report

## Description

- What went wrong?
Conflicting API gateway keys when deploying same aws service to different stages.
- What did you expect should have happened?
API keys in different stages should be independent of each other.
- What was the config you used?
```yaml
service: my-service

custom:
  stage: ${opt:stage, self:provider.stage}
  project: Projectname-${self:custom.stage}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  runtime: python3.7
  memorySize: 1024
  timeout: 5
  apiKeys:
    - name: ${self:custom.project}-mykey1
    - name: ${self:custom.project}-mykey2
      value: ${ssm:parameter_key}
  usagePlan:
    throttle:
      burstLimit: 200
      rateLimit: 50
  tags:
    Project: ${self:custom.project}

package:
  individually: true
  exclude:
    - "./**"

functions:
  func_one:
    handler: func_one/func_one.handler
    name: func_one-${self:custom.project}
    description: func_one lambda
    role: 'arn:aws:iam::xxxx'
    package:
      include:
        - 'func_one/*.py'
    events:
      - http:
          path: func_one/{type}
          method: post
          private: true

```
```sls deploy --stage stage1```
```sls deploy --stage stage2```
- What stacktrace or error message from your provider did you see?
An error occurred: ApiGatewayApiKey2 - API Key already exists (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException; Request ID: xxxx).

Similar or dependent issues:

- #3631 Suggests a workaround that is already implemented in my config, as every key name has a stage variable

## Additional Data

- **_Serverless Framework Version you're using_**: 1.46.1
- **_Operating System_**: linux
