### ISSUE TITLE
1.48.0 parsing errors with cloudformation YAML shorthand ! tags

### ISSUE THREAD

**Issue by herebebogans** [serverless/serverless#6407]
The 1.48.0 release causes YAML parsing errors on previously valid serverless.yml config that use cloudformation Shorthand tags eg !Ref !GetAtt.

serverless.yml example.

```
service: demo

provider:
  name: aws
  stage: dev
  runtime: nodejs10.x

functions:
  demo:
    handler: src/demo.handler
    environment:
      BUCKET: !Ref Bucket
    events:
      - http:
          path: hello-world
          method: get

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-bucket-${self:provider.stage}
```

generates error

```/Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/node_modules/js-yaml/lib/js-yaml/loader.js:167
  return new YAMLException(
         ^
YAMLException: unknown tag !<!Ref> in "/Users/xxx/fullstack/xxxx/serverless.yml" at line 11, column 26:
          BUCKET: !Ref Bucket
```

same config works fine with 1.47.0
