### ISSUE TITLE
Can't attach event to an existing bucket with an !ImportValue name

### ISSUE THREAD

**Issue by quassnoi** [serverless/serverless#6416]
# This is a Bug Report

## Description

Create a serverless template like this:

```
service: test

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: !ImportValue test
          events:
            - s3:ObjectCreated:*
          existing: true
```

and run it:

```
# npx sls prepare
```

- What went wrong?

The CloudFormation template generated is invalid.

```
# cat .serverless/cloudformation-template-update-stack.json | jq ".Resources.IamRoleCustomResourcesLambdaExecution.Properties.Policies[0].PolicyDocument.Statement[0].Resource"

"arn:aws:s3:::[object Object]"
```
- What did you expect should have happened?

I expected the S3 Bucket ARN in the policy to be a valid ARN (generated using `Fn::Join` from the imported bucket name)

- What was the config you used?

```
service: test

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: !ImportValue test
          events:
            - s3:ObjectCreated:*
          existing: true
```

- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**:

```
1.48.2 (Enterprise Plugin: 1.3.1, Platform SDK: 2.0.3)
```

- **_Operating System_**:

```
Linux 4.14.128-112.105.amzn2.x86_64 #1 SMP Wed Jun 19 16:53:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- **_Stack Trace_**:
- **_Provider Error messages_**:
