### ISSUE TITLE
Could not locate deployment bucket. Error: AWS provider credentials not found.

### ISSUE THREAD

**Issue by mdw2000** [serverless/serverless#6421]
## Description

I'm getting the following error when deploying after upgrading to `1.48.2` from `1.45.1`.

I'm using a custom deployment bucket but worked fine.

```
 Serverless Error --------------------------------------- 
  
  Could not locate deployment bucket. Error: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://bit.ly/aws-creds-setup>. 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     Operating System:          linux 
     Node Version:              10.14.1 
     Serverless Version:        1.48.2 
     Enterprise Plugin Version: 1.3.1 
     Platform SDK Version:      2.0.3 
```

Provider config: 

```
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  timeout: 28
  stage: ${opt:stage, "dev"}
  deploymentBucket: bb-deploy
  memorySize: 1024
```

I'm deploying using an AWS CodeBuild project.  No special config there, using the standard Linux image provided by CodeBuild.
