### ISSUE TITLE
Can't deploy function with existing S3 bucket event

### ISSUE THREAD

**Issue by Werter12** [serverless/serverless#6423]
# This is a Bug Report

## Description

- What went wrong?
When I deploying service with this function error occurred.
- What did you expect should have happened?
Service and function is deployed.
- What was the config you used?
```yml
service: newservice

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: prod
  environment:
    BASE_LAYER: arn:aws:lambda:eu-central-1:071770025447:layer:BaseLayer:1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::new-bucket12

functions:
  convertZipped:
    handler: convertZipped.handler
    layers: 
      - ${self:provider.environment.BASE_LAYER}
    events:
      - s3:
          bucket: newbucket12
          event: s3:ObjectCreated:*
          rules:
            - prefix: static/js/
            - suffix: .gz
          existing: true
```
- What stacktrace or error message from your provider did you see?
>  :x: ConvertZippedCustomS31 - Failed to create resource. Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**:
  Serverless Version:     1.47.0
- **_Operating System_**:
   OS:                     darwin
- **_Stack Trace_**:
- **_Provider Error messages_**:
>  :x: ConvertZippedCustomS31 - Failed to create resource. Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.
