### ISSUE TITLE
websocket "request" body validation

### ISSUE THREAD

**Issue by andrhamm** [serverless/serverless#6424]
# This is a Feature Proposal

## Description

AWS supports body validation on API Gateway Websocket events similar to the HTTP request body validation that Serverless already supports. The implementation could look the same as for HTTP events:

```
customFooHandler:
    handler: handler.fooHandler
    events:
      - websocket:
          route: foo
          request:
            schema:
              application/json: ${file(foo.json)}
```

See: [https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-selection-expressions.html#apigateway-websocket-api-model-selection-expressions](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-selection-expressions.html#apigateway-websocket-api-model-selection-expressions)

Similar or dependent issues:
