### ISSUE TITLE
Running Lambda Function written in Go on AWS - error while loading shared libraries

### ISSUE THREAD

**Issue by StefanCepa** [serverless/serverless#6434]
# This is a Bug Report

## Description

- What went wrong? I have created 2x Lambda functions, one uses Tensorflow library and once I try to execute it i am getting following error:
```
START RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56 Version: $LATEST
/var/task/bin/inference: error while loading shared libraries: libtensorflow.so.1: cannot open shared object file: No such file or directory
END RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56
REPORT RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56	Duration: 39.02 ms	Billed Duration: 100 ms 	Memory Size: 3008 MB	Max Memory Used: 15 MB	
RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56 Process exited before completing request
```
**inference** is compiled version of my lambda function  written in **Go**.

- What did you expect should have happened?  I expected my Lambda function to run. And show some logs at least. I have logs that are suppose to be shown before handler is invoked and right after handler is invoked. None of them is shown. So I am guessing that this error occurs while mounting Docker container or something.

- What was the config you used?
```
service: LambdaConfigService

provider:
  name: aws
  runtime: go1.x
  stage: debug
  region: us-east-1
  versionFunctions: false
  environment:
    STAGE: ${self:provider.stage}
    MAX_FRAME_NUM_TO_PROCESS: "3000"
    MAX_URL_VALID_DURATION: "300"
    S3_REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action: "s3:*"
      Resource: "*"

package:
  include:
    - ./bin/**
  exclude:
    - ./**
    
functions:
  Thumbnail:
    handler: bin/thumbnail
    description: Used in order to generate thumnails given a time range and a source id
    timeout: 300
    memorySize: 3008
    events:
       - http:
          path: ai/thumbnail
          method: post
          cors: true
      
  Inference:
    handler: bin/inference
    description: Used in order to perform statistical inference over the list of JPEG files
    timeout: 300
    memorySize: 3008
    events:
       - http:
          path: ai/inference
          method: post
          cors: true
```
And here are Makefile commands I used to build my functions:

```
build-thumbnail:
	env GOOS=linux $(GOBUILD) -ldflags="-s -w" -o $(THUMBNAIL_BINARY) -v $(THUMBNAIL_SOURCE)
	zip $(THUMBNAIL_ZIP) $(THUMBNAIL_BINARY)

build-inference:
	env GOOS=linux $(GOBUILD) -ldflags="-s -w" -o $(INFERENCE_BINARY) -v $(INFERENCE_SOURCE)
	zip $(INFERENCE_ZIP) $(INFERENCE_BINARY)
```

- What stacktrace or error message from your provider did you see?
```
START RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56 Version: $LATEST
/var/task/bin/inference: error while loading shared libraries: libtensorflow.so.1: cannot open shared object file: No such file or directory
END RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56
REPORT RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56	Duration: 39.02 ms	Billed Duration: 100 ms 	Memory Size: 3008 MB	Max Memory Used: 15 MB	
RequestId: 165088ce-b188-43e3-8371-8cdfa0480c56 Process exited before completing request

```

## Additional Data

- **_Serverless Framework Version you're using_**: 1.46.1
- **_Operating System_**: Ubuntu 18.06
