### ISSUE TITLE
CloudFormation Resource DependsOn Lambda Not Working

### ISSUE THREAD

**Issue by wenindoubt** [serverless/serverless#6438]
# This is a Bug Report

## Description

- What went wrong?
A CloudFormation resource, `AWS::Lambda::Permission`, cannot `DependsOn` a Lambda function.

- What did you expect should have happened?
The CloudFormation resource should wait for the lambda function to be deployed.

- What was the config you used?

```
Resources:
    UserPoolLambdaInvokePermission:
      Type: AWS::Lambda::Permission
      DependsOn: CognitoCustomMessageLambdaFunction
      Properties:
        Action: lambda:InvokeFunction
        Principal: cognito-idp.amazonaws.com
        FunctionName: arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-cognitoCustomMessage
        SourceArn: arn:aws:cognito-idp:${self:provider.region}:#{AWS::AccountId}:userpool/${self:provider.environment.USER_POOL_ID}

functions:
  cognitoCustomMessage:
    handler: src/main/lambdas/handler.cognitoCustomMessage
```

I even performed a `serverless package`, viewed `serverless-state.json`, and ensured that the lambda function has a generated name of `CognitoCustomMessageLambdaFunction`.

- What stacktrace or error message from your provider did you see?

Here is the error message:

> An error occurred: CognitoCustomMessageLambdaFunction - Function not found: arn:aws:lambda:us-west-2:XXXXXXXXXXXX:function:my-service-dev-cognitoCustomMessage (Service: AWSLambdaInternal; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 8884f0c7-66d8-43dd-a0ca-ecea29d9ecd3).

Similar or dependent issues:

This issue is closed but I am currently experiencing the same bug.
https://github.com/serverless/serverless/issues/4523

## Additional Data

- **_Serverless Framework Version you're using_**: 1.40.0
- **_Operating System_**: macOS 10.14.5
- **_Stack Trace_**:
- **_Provider Error messages_**:
