### ISSUE TITLE
S3 event, Existing Bucket. s3:ObjectCreated:Put creating s3:ObjectCreated:* if event is a list

### ISSUE THREAD

**Issue by fcarrasco** [serverless/serverless#6439]
# This is a Bug Report

## Description
I need to create an event to s3:ObjectCreated:Put on an existing bucket.
events:
      - s3:
          bucket: bucketName
          event: 
            - s3:ObjectCreated:Put
It creates an s3:ObjectCreated:* if the event is a list

If the event is a string it works correctly (event: s3:ObjectCreated:Put)

- What went wrong?
events:
      - s3:
          bucket: bucketName
          event: 
            - s3:ObjectCreated:Put
The event created was s3:ObjectCreated:*

- What did you expect should have happened?
The event should be s3:ObjectCreated:Put

- What was the config you used?
- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**: 1.48.3
- **_Operating System_**: Ubuntu 19.04
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by pmuens** [comment]
Hey @fcarrasco thanks for opening :+1:

This is related to https://github.com/serverless/serverless/issues/6461 and https://github.com/serverless/serverless/issues/3448.

The PR https://github.com/serverless/serverless/pull/6477 actually fixes this shortcoming.

**Comment by tcastelli** [comment]
Got a nice infinite execution of lambdas because of this bug. Hopefully it gets fixed since when trying to use 
```
 events: [
                            "s3:ObjectCreated:Put",
                            "s3:ObjectCreated:Post",
                            "s3:ObjectCreated:CompleteMultipartUpload"
                        ],
```
they changed to s3:ObjectCreated:* and I specifically had left :Copy out for a reason :(

**Comment by jorenvh1** [comment]
@tcastelli Do you have any workaround for this? I am also doing the following:

```
- s3:
          bucket: ${self:custom.tf.s3_bucket_name}
          events:
            - s3:ObjectCreated:Put
            - s3:ObjectCreated:Post
            - s3:ObjectCreated:CompleteMultipartUpload
          rules:
            - prefix:/
            - suffix: .png
          existing: true
```

They are also changed to s3:ObjectCreated:*
