### ISSUE TITLE
S3Bucket - Encountered unsupported property ExposeHeader

### ISSUE THREAD

**Issue by tumdav** [serverless/serverless#6442]
Serverless configuration

```yml
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - POST
                - PUT
                - HEAD
              MaxAge: 3000
```

I tried to add 
```yml
        CorsConfiguration:
          CorsRules:
            -
              ExposeHeader:
                - ETag
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - POST
                - PUT
                - HEAD
              MaxAge: 3000
```  

```yml
        CorsConfiguration:
          CorsRules:
            -
              ExposeHeaders:
                - ETag
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - POST
                - PUT
                - HEAD
              MaxAge: 3000
```  

```yml
        CorsConfiguration:
          CorsRules:
            -
              ExposeHeader: ETag
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - POST
                - PUT
                - HEAD
              MaxAge: 3000
```  

but  no result
