### ISSUE TITLE
Cloudwatch log group subscriptions are removed on subsequent deploys in gov-cloud

### ISSUE THREAD

**Issue by maafk** [serverless/serverless#6443]
# This is a Bug Report

## Description

- What went wrong?
  - Log group subscription event is deleted on subsequent deploys in gov-cloud
- What did you expect should have happened?
  - That the lambda event source remains
- What was the config you used?
```
service: my-service

provider:
  name: aws
  runtime: python3.6
  region: us-gov-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - cloudwatchLog:
          logGroup: '/var/log/cloud-init-output.log'
          filter: 'some filter'
```
- What stacktrace or error message from your provider did you see?
None

The issue can be found in this line [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/checkForChanges.js#L220) where the partition is hard coded to `aws`.

Gov-cloud uses the [partition](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html) `aws-us-gov`, so in this situation `oldDestinationArn` will _never_ equal `newDestinationArn `, therefore deleting the subscription filter.

This doesn't happen on an initial deploy, but only subsequent deploys in [`checkForChanges`](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/checkForChanges.js)

**I have a PR ready** for this (tested and working), so happy to send.

Similar or dependent issues:

- #5700

## Additional Data

- **_Serverless Framework Version you're using_**: 1.48.3
- **_Operating System_**: MacOs 10.14.5
- **_Stack Trace_**: None
- **_Provider Error messages_**: None
