### ISSUE TITLE
s3 event, not adding triggers to resize images.

### ISSUE THREAD

**Issue by tarunjangra** [serverless/serverless#6455]
# This is a Bug Report

## Description
I want to create lambda function which can resize image and create different thumbnails. 

- What went wrong?
  Nothing was wrong on cli console. It is showing everything successfully executed. I can also see created resources in lambda console. Lambda function is there.
- What did you expect should have happened?
It should also add triggers in lambda console which will trigger lambda function when i put image in the corresponding bucket.
- What was the config you used?
```yml
service: User
frameworkVersion: ">=1.48.4"

custom:
  bucket: gi3-original-bucket

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 192
  timeout: 10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
  logRetentionInDays: 5
  stage: dev
  region: ap-south-1
functions:
  GICreateThumbnails:
    handler: GICreateThumbnails.handler
    name: GICreateThumbnails # optional, Deployed Lambda name
    description: To create thumbnail of the uploaded picture on s3. # optional, Description to publish to AWS
    events:
      - s3:
        bucket: ${self:custom.bucket}
        event: s3:ObjectCreated:*
        rules:
          - prefix: images/user/
          - suffix: .png
        existing: true
      - s3:
        bucket: ${self:custom.bucket}
        event: s3:ObjectRemoved:*
        rules:
          - prefix: images/user/
          - suffix: .png
        existing: true
```
- What stacktrace or error message from your provider did you see?
Nothing. As i did not get any error on cli console.

## Additional Data
- **_Node Version_**:  8.11.2
- **_Serverless Framework Version you're using_**:1.48.4
- **_Operating System_**:darwin
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by HumbleBeck** [comment]
Isnt it suppose to be like
```
- s3:
    bucket: ${self:custom.bucket}
    event: s3:ObjectCreated:*
    rules:
      - prefix: images/user/
      - suffix: .png
    existing: true
- s3:
    bucket: ${self:custom.bucket}
    event: s3:ObjectRemoved:*
    rules:
      - prefix: images/user/
      - suffix: .png
    existing: true
```
I believe its not aligned correctly

**Comment by tarunjangra** [comment]
I have tried all possible indentations. Tried what you said even. Getting error:
` Cannot read property 'events' of undefined`
when deploying using 
```bash
sls deploy --aws-profile <my-profile>
```

**Comment by pmuens** [comment]
Hey @tarunjangra thanks for opening :+1:

The indentation seems to be incorrect as @HumbleBeck mentioned... Could you look into the generated CloudFormation template? You can find it in the `.serverless` directory (it's the on with the `update` in the filename?

Furthermore can you post your most-recent `serverless.yml` file (since you've indented it according to @HumbleBeck comment)?

Thanks in advance :+1:

**Comment by tarunjangra** [comment]
Here is latest yml file which is throwing "Cannot read property 'events' of undefined"

```yml
service: User
frameworkVersion: ">=1.48.4"

custom:
  bucket: gi3-original

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 192
  timeout: 10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
  logRetentionInDays: 5
  stage: dev
  region: ap-south-1
functions:
  GICreateThumbnails:
    handler: GICreateThumbnails.handler
    name: GICreateThumbnails # optional, Deployed Lambda name
    description: To create thumbnail of the uploaded picture on s3. # optional, Description to publish to AWS
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: "s3:ObjectCreated:*"
          rules:
            - prefix: "images/user/"
            - suffix: ".png"
          existing: true
      - s3:
          bucket: ${self:custom.bucket}
          event: "s3:ObjectRemoved:*"
          rules:
            - prefix: "images/user/"
            - suffix: ".png"
          existing: true
```
CF updated template.

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "GICreateThumbnailsLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/GICreateThumbnails",
        "RetentionInDays": 5
      }
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": {
              "Fn::Join": [
                "-",
                [
                  "dev",
                  "User",
                  "lambda"
                ]
              ]
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogStream"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/User-dev*:*"
                    },
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/GICreateThumbnails:*"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:PutLogEvents"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/User-dev*:*:*"
                    },
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/GICreateThumbnails:*:*"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "s3:*"
                  ],
                  "Resource": "*"
                }
              ]
            }
          }
        ],
        "Path": "/",
        "RoleName": {
          "Fn::Join": [
            "-",
            [
              "User",
              "dev",
              {
                "Ref": "AWS::Region"
              },
              "lambdaRole"
            ]
          ]
        }
      }
    },
    "EnterpriseLogAccessIamRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::802587217904:root"
              },
              "Action": "sts:AssumeRole",
              "Condition": {
                "StringEquals": {
                  "sts:ExternalId": "ServerlessEnterprise-RX4lssfDGXRkpxRw5Z"
                }
              }
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "LogFilterAccess",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:FilterLogEvents"
                  ],
                  "Resource": [
                    {
                      "Fn::GetAtt": [
                        "GICreateThumbnailsLogGroup",
                        "Arn"
                      ]
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    },
    "GICreateThumbnailsLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/User/dev/1564147293529-2019-07-26T13:21:33.529Z/User.zip"
        },
        "FunctionName": "GICreateThumbnails",
        "Handler": "s_GICreateThumbnails.handler",
        "MemorySize": 192,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs8.10",
        "Timeout": 10,
        "Description": "To create thumbnail of the uploaded picture on s3."
      },
      "DependsOn": [
        "GICreateThumbnailsLogGroup",
        "IamRoleLambdaExecution"
      ]
    },
    "GICreateThumbnailsLambdaVersionbOjfe0hPDE56hDArl0uYj7HIp20OECCzbNJQWgSQikA": {
      "Type": "AWS::Lambda::Version",
      "DeletionPolicy": "Retain",
      "Properties": {
        "FunctionName": {
          "Ref": "GICreateThumbnailsLambdaFunction"
        },
        "CodeSha256": "bbADheXU1AcKOGKq/YsfXbm1DvWrtmUykD++ysY7WyE=",
        "Description": "To create thumbnail of the uploaded picture on s3."
      }
    },
    "GICreateThumbnailsCustomS31": {
      "Type": "Custom::S3",
      "Version": 1,
      "DependsOn": [
        "GICreateThumbnailsLambdaFunction",
        "CustomDashresourceDashexistingDashs3LambdaFunction"
      ],
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "CustomDashresourceDashexistingDashs3LambdaFunction",
            "Arn"
          ]
        },
        "FunctionName": "GICreateThumbnails",
        "BucketName": "gi3-original",
        "BucketConfig": {
          "Event": "s3:ObjectCreated:*",
          "Rules": [
            {
              "Prefix": "images/user/"
            },
            {
              "Suffix": ".png"
            }
          ]
        }
      }
    },
    "GICreateThumbnailsCustomS32": {
      "Type": "Custom::S3",
      "Version": 1,
      "DependsOn": [
        "GICreateThumbnailsLambdaFunction",
        "CustomDashresourceDashexistingDashs3LambdaFunction"
      ],
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "CustomDashresourceDashexistingDashs3LambdaFunction",
            "Arn"
          ]
        },
        "FunctionName": "GICreateThumbnails",
        "BucketName": "gi3-original",
        "BucketConfig": {
          "Event": "s3:ObjectRemoved:*",
          "Rules": [
            {
              "Prefix": "images/user/"
            },
            {
              "Suffix": ".png"
            }
          ]
        }
      }
    },
    "CustomDashresourceDashexistingDashs3LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/User/dev/15641f47293529-2019-07-26T13:21:33.529Z/custom-resources.zip"
        },
        "FunctionName": "User-dev-custom-resource-existing-s3",
        "Handler": "s3/handler.handler",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleCustomResourcesLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs10.x",
        "Timeout": 6
      },
      "DependsOn": [
        "IamRoleCustomResourcesLambdaExecution"
      ]
    },
    "IamRoleCustomResourcesLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": {
              "Fn::Join": [
                "-",
                [
                  "dev",
                  "User",
                  "custom-resources-lambda"
                ]
              ]
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Resource": "arn:aws:s3:::gi3-original",
                  "Action": [
                    "s3:PutBucketNotification",
                    "s3:GetBucketNotification"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Resource": "arn:aws:s3:::gi3-original",
                  "Action": [
                    "s3:PutBucketNotification",
                    "s3:GetBucketNotification"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Resource": "arn:aws:lambda:*:*:function:GICreateThumbnails",
                  "Action": [
                    "lambda:AddPermission",
                    "lambda:RemovePermission"
                  ]
                }
              ]
            }
          }
        ]
      }
    },
    "CloudWatchLogsSubscriptionFilterGICreateThumbnailsLogGroup": {
      "Type": "AWS::Logs::SubscriptionFilter",
      "Properties": {
        "DestinationArn": "arn:aws:logs:ap-south-1:802587217904:destination:RX4lssfDGXRkpxsdfRw5Z#r7bcpdCHlhYz4rcxH2#User#dev",
        "FilterPattern": "?\"REPORT RequestId: \" ?\"SERVERLESS_ENTERPRISE\"",
        "LogGroupName": {
          "Ref": "GICreateThumbnailsLogGroup"
        }
      }
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "EnterpriseLogAccessIamRole": {
      "Value": {
        "Fn::GetAtt": [
          "EnterpriseLogAccessIamRole",
          "Arn"
        ]
      }
    },
    "GICreateThumbnailsLambdaFunctionQualifiedArn": {
      "Description": "Current Lambda function version",
      "Value": {
        "Ref": "GICreateThumbnailsLambdaVersionbOje0hPDE56hDArl0uYj7HIp2sdf0OECCzbNJQWgSQikA"
      }
    }
  }
}
```

**Comment by pmuens** [comment]
Hey @tarunjangra thanks for posting the code.

I just copied and pasted it and I don't see the error "Cannot read property 'events' of undefined".

Can you export the `SLS_DEBUG=*` env variable so that we can see the stack trace? Thanks in advance!

**Comment by tarunjangra** [comment]
Hi @pmuens Thanks for taking time to debug this thing. Following is the stack trace.

```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
platform-sdk fetching: POST https://api.serverless.com/core/tenants/ginvoicing/applications/ginvoicing/profileValue
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
platform-sdk fetching: GET https://api.serverless.com/core/tenants/ginvoicing/applications/ginvoicing
Serverless: 
User stats error: Request network error: { FetchError: network timeout at: https://tracking.serverlessteam.com/v1/track
    at Timeout._onTimeout (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/node-fetch/index.js:126:13)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  name: 'FetchError',
  message: 'network timeout at: https://tracking.serverlessteam.com/v1/track',
  type: 'request-timeout' }
platform-sdk fetching: GET https://api.serverless.com/core/meta
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: [AWS sts 200 1.207s 0 retries] getCallerIdentity({})
platform-sdk fetching: POST https://api.serverless.com/malt/destinations/create
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Safeguards Processing...
Serverless: Safeguards Results:

   Summary --------------------------------------------------

   passed - allowed-stages
   warned - require-cfn-role
   passed - framework-version
   passed - allowed-runtimes
   warned - no-wild-iam-role-statements
   warned - allowed-regions
   warned - require-dlq
   passed - no-secret-env-vars
Serverless: Publishing service to the Serverless Dashboard...
Serverless: [AWS sts 200 1.26s 0 retries] getCallerIdentity({})
Serverless: [AWS cloudformation 200 0.398s 0 retries] describeStacks({ StackName: 'User-dev' })
platform-sdk fetching: POST https://api.serverless.com/core/tenants/ginvoicing/applications/ginvoicing/services/User/stages/dev/regions/ap-south-1/deployments
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/ginvoicing/applications/ginvoicing/services/User/stage/dev/region/ap-south-1
 
  Type Error ---------------------------------------------
 
  Cannot read property 'events' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'events' of undefined
    at Object.events [as function] (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/lib/safeguards/policies/require-dlq.js:36:74)
    at /Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/lib/safeguards/index.js:121:11
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/safeguards/index.js:9:103)
    at _next (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/safeguards/index.js:11:194)
    at /Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/safeguards/index.js:11:364
    at new Promise (<anonymous>)
    at /Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/safeguards/index.js:11:97
    at /Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/lib/safeguards/index.js:96:27
    at Array.map (<anonymous>)
    at map (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/lib/safeguards/index.js:96:36)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/safeguards/index.js:9:103)
    at _next (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/safeguards/index.js:11:194)
    at <anonymous>
From previous event:
    at PluginManager.invoke (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.run (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:496:17)
    at variables.populateService.then (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/Serverless.js:116:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/Serverless.js:103:74)
    at serverless.init.then (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless.js:52:28)
    at /Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at initializeErrorReporter.then (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless.js:52:6)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Object.<anonymous> (/Users/tarunjangra/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless.js:38:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              8.11.2
     Serverless Version:        1.48.4
     Enterprise Plugin Version: 1.3.2
     Platform SDK Version:      2.1.0
```

**Comment by pmuens** [comment]
I see. Thanks a lot for posting the stack trace @tarunjangra :+1:

We'll dig deeper into this issue...

**Comment by pmuens** [comment]
@tarunjangra we've just patched the issue via https://github.com/serverless/enterprise-plugin/pull/227

Can you re-install Serverless to get the latest version of all the packages (especially the new version of the enterprise plugin)? That should fix the problem.

**Comment by tarunjangra** [comment]
@pmuens Thank you to update me about this. It worked but I got new problem. 

It is doing fine if there is only one Event. I can see the trigger attached lambda console. But when i put two event's it gives me following error.

`An error occurred: GICreateThumbnailsCustomS32 - Failed to create resource. The statement id (GICreateThumbnails-gi3-original) provided already exists. Please provide a new statement id, or remove the existing statement. See details in CloudWatch Log: 2019/07/26/[$LATEST]72cd5e24c1b04708a553fdb3bedebdfb.`

worked for one event.

```yml
service: User
frameworkVersion: ">=1.48.4"

custom:
  bucket: gi3-original

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 192
  timeout: 10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
  logRetentionInDays: 5
  stage: dev
  region: ap-south-1
functions:
  GICreateThumbnails:
    handler: GICreateThumbnails.handler
    name: GICreateThumbnails # optional, Deployed Lambda name
    description: To create thumbnail of the uploaded picture on s3. # optional, Description to publish to AWS
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: "s3:ObjectCreated:*"
          rules:
            - prefix: "images/user/"
            - suffix: ".png"
          existing: true
```
