### ISSUE TITLE
API gateway generated key name not prefixed with stage

### ISSUE THREAD

**Issue by revmischa** [serverless/serverless#6458]
Context: https://serverless-contrib.slack.com/archives/CA4QT5VU3/p1564126720163800

The generated resource name for API gateway keys (e.g. "ApiGatewayApiKey1") doesn't contain service/stage, so it conflicts if you deploy your app to more than one stage

config:
```
apiKeys:
    - name: "${self:custom.stackName}-key1"
      value: 'blah blah'
      description: Api key description
```
`name` is not used for generating the resource name.
outputs:
```
    "ApiGatewayApiKey1": {
      "Type": "AWS::ApiGateway::ApiKey",
      "Properties": {
        "Enabled": true,
        "Name": "qc-dev-key1",
        "Value": "blah blah",
        "Description": "Api key description",
        "StageKeys": [
          {
            "RestApiId": {
              "Ref": "ApiGatewayRestApi"
            },
            "StageName": "dev"
          }
```

Error:
```
  An error occurred: ApiGatewayApiKey1 - API Key already exists (Service: AmazonApiGateway; Status Code: 409; Error Code: ConflictException;).

```
