### ISSUE TITLE
Modifying `iamRoleStatements` of a Function aren't updated on `sls deploy`

### ISSUE THREAD

**Issue by AleskiWeb** [serverless/serverless#6485]
# This is a Bug Report

## Description

- What went wrong?
I am using the following `iamRoleStatement` on a specific function: 
```
iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
        Resource: !GetAtt s3PollerQueue.Arn
      - Effect: 'Allow'
        Action:
          - sqs:SendMessage
          - sqs:GetQueueUrl
        Resource: !GetAtt urlCrawlerQueue.Arn
```

First of all, the `Allow` actions above, only the first set of them are applied, to both SQS Arns (for some reason)

Secondly, when I modify these, and then run `sls deploy` or `sls deploy --force` modifying both function and `serverless.yml` code, the changes aren't reflected in the AWS console.

- What did you expect should have happened?
Either the configuration to work against both SQS Arns independently, or that deploying with new permissions modifies them.

**Comment by AhmedMKamal** [comment]
Any updates on this?

**Comment by seba-i** [comment]
Also having the issue of changes to iamRoleStatements section not being written during redeploy. In the past this has worked for me (added a ddb index), but not now (v1.70.1) when adding a second ddb table.

**Comment by uehondor** [comment]
I've also just encountered this issue. I updated to the latest version of serverless `1.74.1` and this made no difference. The changes to the IAM role permission weren't picked up.

Any update what the issue might be and a possible fix?

**Comment by petrgazarov** [comment]
In my case I have two separate deployments with different stages. `iamRoleStatements` was reflected correctly in one deployment, but in the other deployment the role never updated. I went so far as to delete and recreate the CF stack but the role still didn't have the statements. I upgraded from `serverless@2.15.0` to `serverless@2.37.1` and the problem was fixed.

**Comment by hubatish** [comment]
2023 here & running into the same issue as described by the title. My serverless.yml contains:

```
  iamRoleStatements:
    - Effect: "Allow"	
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dyanmodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["MyDb1", "Arn"] }
        - { "Fn::GetAtt": ["MyDb2", "Arn"]}
```

It worked a while ago to update my function to have all of those permissions, except BatchGetItem which I just added yesterday. That has not been updated, even after multiple `serverless deploy`, `serverless deploy --force`, updating serverless version, and commiting / pushing to my repo.
