### ISSUE TITLE
Deployment failing with generic error

### ISSUE THREAD

**Issue by brubom** [serverless/serverless#6487]
# This is a Bug Report

## Description

- What went wrong?
I'm trying to deploy a lambda function into aws, using circleci. It fails, throwing a generic error:
```
/home/circleci/repo/node_modules/@serverless/core/src/utils/index.js:8
  ...fs,
  ^^^^

SyntaxError: Expected identifier, string or number
```
Deployment works on my mac.

- What did you expect should have happened?
The code should be deployed or at least I should received a more informative error. serverless is being deployed as part of the process so I'm clueless about what is wrong.

- What was the config you used?
```

service: konig-credit-bureau-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

functions:
  score:
    handler: handler.main
    events:
      - http:
          path: creditscore
          method: get
          cors: true
          authorizer: aws_iam
          request:
            parameters:
              querystrings:
                cpf: true
                birthdate: true
                email: true
                fullname: true
                mobile: true
                montlyIncome: true
                creditValue: true
                installments: true

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

```
- What stacktrace or error message from your provider did you see?

## Additional Data
- **_Node Version_**: chakracore-10.6.0
- **_Serverless Framework Version you're using_**: 1.49.0
- **_Operating System_**: Ubuntu SMP
- **_Stack Trace_**:
```
SyntaxError: Expected identifier, string or number
   at Script (vm.js:82:7)
   at createScript (vm.js:246:3)
   at runInThisContext (vm.js:298:3)
   at Module.prototype._compile (internal/modules/cjs/loader.js:657:3)
   at Module._extensions[.js] (internal/modules/cjs/loader.js:700:3)
   at Module.prototype.load (internal/modules/cjs/loader.js:599:3)
   at tryModuleLoad (internal/modules/cjs/loader.js:538:5)
   at Module._load (internal/modules/cjs/loader.js:530:3)
   at Module.prototype.require (internal/modules/cjs/loader.js:637:3)
   at require (internal/modules/cjs/helpers.js:20:7)
```

- **_Provider Error messages_**:
