### ISSUE TITLE
TypeError: Cannot read property 'refs' of undefined

### ISSUE THREAD

**Issue by sent-hil** [serverless/serverless#6497]
#6268 This is a Bug Report

## Description
I had a working [serverless golang app](https://github.com/WalkerAndCoBrandsInc/bender) that deployed to AWS lambda. To facilitate multiple serverless apps under the same repo, I [moved](https://github.com/WalkerAndCoBrandsInc/bender/compare/cron-check?expand=1) the original app to a folder and tried deploying and got an error.

The app itself was successfully deployed, but the error still happens.

- What went wrong?
Deploy failed.

- What did you expect should have happened?

- What was the config you used?
```
service: bender
app: bender
tenant: senthil
provider:
  name: aws
  runtime: go1.x
  stage: dev
package:
  exclude:
    - ./**
  include:
    - ./bin/**
    - ./config.yml
functions:
  bender:
    handler: bin/bender
    events:
      - http:
          path: /
          method: post

```
- What stacktrace or error message from your provider did you see?
```
Serverless: Removing old service artifacts from S3...
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Publishing service to the Serverless Dashboard...
TypeError: Cannot read property 'refs' of undefined
    at /usr/local/lib/node_modules/serverless/node_modules/@serverless/lib/deployment/parse.js:126:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/parse.js:21:103)
    at _next (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/parse.js:23:194)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

  Type Error ---------------------------------------------

  Cannot read property 'refs' of undefined
```

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: `1.49.0 (Enterprise Plugin: 1.3.6, Platform SDK: 2.1.0)`
- **_Operating System_**: OSX
- **_Stack Trace_**:
- **_Provider Error messages_**:
