### ISSUE TITLE
User Pool Properties are removed after add trigger to existing a pool

### ISSUE THREAD

**Issue by hiramatsutaku** [serverless/serverless#6499]
# This is a Bug Report

## Description

>- What went wrong?

After add trigger to existing a pool, AutoVerifiedAttributes property of the pool was removed.

>- What did you expect should have happened?

I expect not to remove AutoVerifiedAttributes property after add trigger to existing pools.

>- What was the config you used?

I've used the serverless.yml below.

```
functions:
  hello:
    handler: handler.hello
    events:
      - cognitoUserPool:
          pool: sample
          trigger: PostConfirmation
          existing: true
```
The whole is here: https://github.com/hiramatsutaku/sls-debug-for-trigger-existing-pools/blob/master/serverless.yml

>- What stacktrace or error message from your provider did you see?

1. Create User Pool

```
$ aws cognito-idp create-user-pool --pool-name sample --auto-verified-attributes email | jq '.UserPool.Id'
"ap-northeast-1_B9u8qsQOT"
$ aws cognito-idp describe-user-pool --user-pool-id ap-northeast-1_B9u8qsQOT | jq '.UserPool.AutoVerifiedAttributes'
[
  "email"
]
```

2. Add trigger to existing User Pool

<details>
<summary>sls deploy</summary>

```
$ npx sls deploy --profile my-profile-here
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service sample.zip file to S3 (87.16 KB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........................
Serverless: Stack update finished...
Service Information
service: sample
stage: dev
region: ap-northeast-1
stack: sample-dev
resources: 8
api keys:
  None
endpoints:
  None
functions:
  hello: sample-dev-hello
layers:
  None
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
```

</details>

3. Check user pool

```
$ aws cognito-idp describe-user-pool --user-pool-id ap-northeast-1_B9u8qsQOT  --profile my-profile-here | jq '.UserPool.AutoVerifiedAttributes'
null
```

I expect to return 

not `null` but ↓

```
[
  "email"
]
```

Diff of User Pool (aws cognito-idp describe-user-pool command output) 

```
% diff -u etc/before.json etc/after.json
--- etc/before.json	2019-08-03 23:29:05.000000000 +0900
+++ etc/after.json	2019-08-03 23:28:59.000000000 +0900
@@ -218,15 +218,12 @@
         "VerificationMessageTemplate": {
             "DefaultEmailOption": "CONFIRM_WITH_CODE"
         },
-        "LastModifiedDate": 1564839772.279,
+        "LastModifiedDate": 1564842153.819,
         "AdminCreateUserConfig": {
             "UnusedAccountValidityDays": 7,
             "AllowAdminCreateUserOnly": false
         },
         "EmailConfiguration": {},
-        "AutoVerifiedAttributes": [
-            "email"
-        ],
         "Policies": {
             "PasswordPolicy": {
                 "RequireLowercase": true,
@@ -240,6 +237,8 @@
         "CreationDate": 1564839772.279,
         "EstimatedNumberOfUsers": 0,
         "Id": "ap-northeast-1_M2sH6hGdb",
-        "LambdaConfig": {}
+        "LambdaConfig": {
+            "PostConfirmation": "arn:aws:lambda:ap-northeast-1:***********:function:sample-dev-hello"
+        }
     }
 }
```

>Similar or dependent issues:

- The feature I used was added #6362.

## Additional Data

- **_Serverless Framework Version you're using_**: 1.49.0
- **_Operating System_**: macOS Mojave Version 10.14.3
- **_Stack Trace_**: -
- **_Provider Error messages_**: -

**Comment by ahmetcetin** [comment]
Other settings are also affected. I have the following CognitoUserPool definition:

```
Type: AWS::Cognito::UserPool
Properties:
  # Generate a name based on the stage
  UserPoolName: "${self:custom.${self:custom.stage}UserPoolName}"
  # Set email as an alias
  UsernameAttributes:
    - email
  AutoVerifiedAttributes:
    - email
  Schema:
    - Name: name
      AttributeDataType: String
      Mutable: true
      Required: true
    - Name: email
      AttributeDataType: String
      Mutable: false
      Required: true
  Policies:
    PasswordPolicy:
      RequireLowercase: true
      RequireUppercase: false
      RequireSymbols: false
      RequireNumbers: false
      MinimumLength: 8

```

And function defined as:
```
functions:
  presign:
    handler: backend/pre_signup.handler
    events:
      - cognitoUserPool:
          pool: "${self:custom.${self:custom.stage}UserPoolName}"
          trigger: PreSignUp
          existing: true
```

After adding existing: true in function trigger, the password policy reset to default cognito settings, which requires lowercase, uppercase, symbol, and a number. 

Strangely, when I change the any of the password policy settings, like changing minimum length to 6, after deploying, it corrects the password policy settings, but this time, PreSignUp trigger is removed in cognito userpool.
