### ISSUE TITLE
Amazon EventBridge not compatible with partner event sources

### ISSUE THREAD

**Issue by trevorrecker** [serverless/serverless#6514]
# This is a Bug Report

## Description

When deploying an AWS Lambda that is triggered by Amazon EventBridge using a partner event source (such as segment.com) a CloudFormation error occurs that the event bus cannot be found. This error appears to be caused by the way the event bus ARN is parsed by Serverless, detailed below.

Configuration:

```yaml
# ...
functions:
  # ...
  create-request:
    handler: functions/handler.createRequest
    events:
      - eventBridge:
          eventBus: 'arn:aws:events:us-east-1:XXXXXXXXXXXX:event-bus/aws.partner/segment.com/XXXXXXXXXX'
          pattern:
            source:
              - 'aws.partner/segment.com/XXXXXXXXXX'
            detail:
              event:
                - 'My Event'
              type:
                - 'track'
# ...
```

The deployment error that is displayed in the console is:

```
Failed to create resource. Event bus XXXXXXXXXX does not exist. See details in CloudWatch Log: 2019/08/06/[$LATEST][...].
```

In the current implementation, Serverless parses out the event bus ARN so it only includes the text after the last `/` character. In the case of partner sources, a portion of the ARN is omitted by this approach.

[Current implementation](https://github.com/serverless/serverless/blob/2c1315666a3bd25c6c744cb810b830dd6d248160/lib/plugins/aws/package/compile/events/eventBridge/index.js#L122) added in #6397 [here](https://github.com/serverless/serverless/commit/871b04e238b19bc9c57a9b430685ad157b52b98b#diff-8996f21d004732c3332fe2aeb726f6bbR122):

```javascript
eventBusName = EventBus.split('/').pop();
```

This implementation works for custom event busses formatted as follows:

```
event-bus/<bus_name>
```

However, it is not compatible with event busses from partner sources or any ARN containing additional `/` characters such as the Segment event bus in my example:

```
event-bus/aws.partner/segment.com/XXXXXXXXXX
```

The above ARN path is converted to `event-bus/XXXXXXXXXX` which does not exist.

Similar or dependent issues:

- #6363 - PR #6397 

## Additional Data

- **_Serverless Framework Version you're using_**: v1.49.0
- **_Operating System_**: Mac OS X 10.14.6
- **_Stack Trace_**:
- **_Provider Error messages_**:
- **_Forum Post_**: https://forum.serverless.com/t/amazon-eventbridge-partner-event-sources-error/9011
