### ISSUE TITLE
Improve the SQS documentation part

### ISSUE THREAD

**Issue by tristanbes** [serverless/serverless#6516]
# This is a Feature Proposal

## Description

- Improve the documentation about the SQS part : https://serverless.com/framework/docs/providers/aws/events/sqs/

As a new serverless user, I'm having trouble understanding how to configure the SQS queue to call lambda;

Few question I've asked myself after reading this doc and started to copy paste the code:

1/ In the example, we have under the `event` node, a lot of `sqs` keys; Are they all needed ? Or are they just different format ?
Depending on this answer, it should be added in the code block that they are "just different format" (if they are);

Maybe you should put 2 code blocks; the first one with the "minimal" configuration, and another one containing the other format you can use;

```
    events:
      - sqs: arn:aws:sqs:region:XXXXXX:MyFirstQueue
      - sqs:
          arn:
            Fn::GetAtt:
              - MySecondQueue
              - Arn
        - sqs:
            arn:
              Fn::ImportValue: MyExportedQueueArnId
        - sqs:
            arn:
              Fn::Join:
                - ':'
                - - arn
                  - aws
                  - sqs
                  - Ref: AWS::Region
                  - Ref: AWS::AccountId
                  - MyOtherQueue
```

2/ What about IAM permissions ? I've come across somes issues but there's nothing official; What are the permission needed to allow a lambda to be called when there's item in the SQS queue ?

Thank you;
