### ISSUE TITLE
AWS X-Ray for API Gateway isn't being enabled

### ISSUE THREAD

**Issue by oscarwest** [serverless/serverless#6521]
# This is a Bug Report

## Description

- What went wrong?
When deploying a Cloudformation stack to AWS, the X-Ray tracing on the API Gateway won't enable.
- What did you expect should have happened?
To see the Checkbox in the AWS GUI and to see the API Gateway in X-Ray.
- What was the config you used?
```

service: "someservice"

frameworkVersion: ">=1.6.0 <2.1.0"

provider:
  name: aws
  profile: 'dev'
  stage: 'dev'
  region: eu-north-1
  memorySize: 128
  timeout: 30
  versionFunctions: false
  stackName: stack-example
  runtime: dotnetcore2.1
  environment:
    DEBUG_LOGGING: true
    UNWRAP_AGGREGATE_EXCEPTIONS: 1
  logs:
    restApi: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: '*'
    - Effect: Allow
      Action:
        - xray:PutTelemetryRecords
        - xray:PutTraceSegments
      Resource: '*'
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource: "*"
  tracing:
    apiGateway: true
    lambda: true

package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip
  
functions:
  foo:
    handler: AwsSlsExampleStack.Lambda::AwsSlsExampleStack.Lambda.Functions.FooFunction::Run
    events:
      - http:
          path: Foo
          method: post
          cors: true
  fooBar:
    handler: AwsSlsExampleStack.Lambda::AwsSlsExampleStack.Lambda.Functions.FooBarFunction::Run
    #onError: somearn
  fooBarEventSub:
    handler: AwsSlsExampleStack.Lambda::AwsSlsExampleStack.Lambda.Functions.FooBarEventSubFunction::Run
    events:
      - sns: foo-topic

  fooBarEventError:
    handler: AwsSlsExampleStack.Lambda::AwsSlsExampleStack.Lambda.Functions.FooBarEventErrorFunction::Run
    events:
      - sns: foo-dlq-topic

```
- What stacktrace or error message from your provider did you see?
No errors. Output from sls deploy -v
```
Serverless: [AWS apigateway 200 0.409s 0 retries] updateStage({
  restApiId: '...',
  stageName: 'dev',
  patchOperations: [
    ...
    { op: 'replace', path: '/tracingEnabled', value: 'true' },
    ...
  ]
})
```

I also tried to update the stage using the AWS CLI, it looks to be enabled but still no traces and can't see the checkbox in the stage GUI.
```
aws apigateway update-stage \
    --rest-api-id id \
    --stage-name dev \
    --patch-operations op=replace,path=/tracingEnabled,value=true \
    --region eu-north-1
```

## Additional Data

- 1.49.0 (Enterprise Plugin: 1.3.7, Platform SDK: 2.1.0), frameworkVersion: ">=1.6.0 <2.1.0"
- OSX 10.14.5
