### ISSUE TITLE
exclude fails when filename contains ".."

### ISSUE THREAD

**Issue by carwinz** [serverless/serverless#6530]
# This is a Bug Report

## Description

- What went wrong? Files with ".." in the filename were included in the package when they should have been excluded.
- What did you expect should have happened? The files should not have been included in the package.
- What was the config you used?

```
service: sls-bug
provider:
  name: aws
functions:
  myfunc:
    handler: handler.hello
package:
  exclude:
    - "./**"
  include:
    - "**.js"
```

- What stacktrace or error message from your provider did you see?

No errors, but the file was included in the bundle.

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**:  1.49.0
- **_Operating System_**: Ubuntu 16.04
- **_Stack Trace_**: N/A
- **_Provider Error messages_**: N/A

To reproduce:

    touch exclude..jpg
    touch exclude.jpg
    sls package

Open .serverless/sls-bug.zip and you'll see that `exclude..jpg` is there, but `exclude.jpg` is not.

Workaround is to add this exclude:

    "**/*..jpg"
