### ISSUE TITLE
Error updating stack when using external websocket Api Id

### ISSUE THREAD

**Issue by m-ronchi** [serverless/serverless#6533]
# This is a Bug Report

## Description

- What went wrong?
deploying multiple stacks with the same websocket api ID gives a `WebsocketsDeploymentStage - Stage already exists` error

- What did you expect should have happened?
the route defined in the stack2 config should be added to the websocket defined in the stack1 config
- What was the config you used?
stack1:
```
service:
  name: stack1

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 256

functions: 
  func1:
    handler: func.handler
    events:
      - websocket:
          route: route1

resources:
  - Outputs:
      WebsocketsApi:
        Value:
          Ref: WebsocketsApi
        Export:
          Name: Test-ExportWebsocketApi
```

stack2:
```
service:
  name: stack2
  
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 256
  apiGateway:
    websocketApiId:
      'Fn::ImportValue': Test-ExportWebsocketApi

functions: 
  func2:
    handler: func.handler
    events:
      - websocket:
          route: route2
```

- What stacktrace or error message from your provider did you see?
```
An error occurred: WebsocketsDeploymentStage - Stage already exists (Service: AmazonApiGatewayV2; Status Code: 409; Error Code: ConflictException; Request ID: <some guid>).
```

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: 1.49.0
- **_Operating System_**: OSX Mojave 10.14.4
- **_Stack Trace_**:
[sls_deploy_log.txt](https://github.com/serverless/serverless/files/3496439/sls_deploy_log.txt)

- **_Provider Error messages_**: (included in attachment above)

note: the same error happens if I put an explicit ID in the config, instead of using `Fn::ImportValue`
