### ISSUE TITLE
no region in template url when request Cloud Formation to validateTemplate 

### ISSUE THREAD

**Issue by complex007** [serverless/serverless#6539]
Now S3 bucket has specific region, and can only be access by url like
`https://s3.ap-southeast-1.amazonaws.com/xxxx
`
but in [source code](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/utils/getS3EndpointForRegion.js), serverless will return
`
https://s3.amazonaws.com/xxxx
`
This will cause error for cloud formation when validating the template.

**Comment by santoshyadav198613** [comment]
Hi @medikoo ,
I will look into it.

**Comment by medikoo** [comment]
Great thanks @santoshyadav198613! Do you have already any progress on this?

**Comment by santoshyadav198613** [comment]
Hi will work over the weekend.

**Comment by pmuens** [comment]
Hey @complex007 and @santoshyadav198613 thanks for opening and looking into this 👍

@skantipu just opened #6633 to fix this. Can one of you checkout his PR and see if this solves the problem?


I tried to test it myself but I don't have a `serverless.yml` to validate that this PR fixes the issue. It would be really helpful if someone can post a `serverless.yml` here which showcases the regression. Thanks in advance!

**Comment by pmuens** [comment]
I looked into this issue today and tried to reproduce this with this `serverless.yml` file:

```yaml
service: test-${self:custom.idx}

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1

custom:
  idx: 0

functions:
  hello:
    handler: functions/handler.greeter
```

I couldn't enforce the error even when using with the `ap-southeast-1` region.

I'll close this issue and the corresponding PR for now.

Please re-open this issue with a `serverless.yml` config file and steps to reproduce if this is still a problem.
