### ISSUE TITLE
Serverless deploy hangs and eventually fails when creating EventBridge resources

### ISSUE THREAD

**Issue by ryanhelms** [serverless/serverless#6553]
# This is a Bug Report

## Description

- What went wrong?

I am trying to create a proof-of-concept using the new EventBridge service but I am hitting issues early. I am unable to get the resources to deploy successfully.  

- What did you expect should have happened?

The EventBridge resources would be created

- What was the config you used?
```
functions: 
  ProcessEvent:
    handler: Enumis.Api.Events::Enumis.Api.Events.EventBridgeEventProxy::ProcessEvent
    events:
      - eventBridge:
          eventBus: some-bus-name
          pattern:
            source:
              - acme.topic
```

- What stacktrace or error message from your provider did you see?
```
Serverless Error ---------------------------------------

An error occurred: ProcessEventCustomEventBridge1 - Custom Resource failed to stabilize in expected time.

Get Support --------------------------------------------
```

Similar or dependent issues:

## Additional Data

- **_Serverless Framework_**: 1.50.0
- **_Operating System_**: Windows 10
- **_Stack Trace_**: 
- **_Provider Error messages_**: An error occurred: ProcessEventCustomEventBridge1 - Custom Resource failed to stabilize in expected time.
