### ISSUE TITLE
Variable Defaults cannot have + in them

### ISSUE THREAD

**Issue by nikkon226** [serverless/serverless#6559]
# Variable defaults cannot have `+` in them

## Description

- What went wrong?
When putting in a default value for a variable (at least for opt and env), the default value cannot have a `+` character, even if it is enclosed in single quotes (double quotes as well). When parsing, there is no error, but it prints out the entire line to be interpreted: `TEST: ${env:MYVAR, 'test+'}`.
- What did you expect should have happened?
It should have printed out `TEST: 'test'`
- What was the config you used?
```
service: development
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  environment:
    TEST: ${env:MYVAR,'test+'}
    TEST2: ${env:MYVAR,'test'}
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get
```

- What stacktrace or error message from your provider did you see?
No error messages

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: 1.50.0
- **_Operating System_**: Linux Mint 19.1
- **_Stack Trace_**: None
- **_Provider Error messages_**: None
