### ISSUE TITLE
Stack Policy is not set on stack creation

### ISSUE THREAD

**Issue by nadobando** [serverless/serverless#6563]
# This is a Bug Report

## Description

- What went wrong? 
Stack policy is not set on first deploy and is set after first update
so if I change a DynamoDB table which attribute requires replacement the data on this table will be lost
- What did you expect should have happened?
Stack policy is set after stack creation
- What was the config you used?
```yaml
provider:
  name: aws
  runtime: java8
  stage: ${opt:stage,'test'}
  region: ${env:APP_REGION}
  cfnRole: ${env:CFN_ROLE}
  stackPolicy:
    - Effect: Allow
      Action: Update:Modify
      Principal: "*"
      Resource: "*"


    - Effect: Deny
      Action:
        - Update:Delete
        - Update:Replace

      Principal: "*"
      Resource: "*"
      Condition:
        StringEquals:
          ResourceType:
            - AWS::DynamoDB::Table
            - AWS::SNS::Topic
```

- What stacktrace or error message from your provider did you see?
No Stack Trace

## Additional Data

- **_Serverless Framework Version you're using_**: 1.46.1
- **_Operating System_**: WSL
