### ISSUE TITLE
Being able to set "Default Visibility Timeout" for SQS queue in AWS

### ISSUE THREAD

**Issue by QAnders** [serverless/serverless#6565]
# This is a Feature Proposal

## Description

- When using long(er) running Lambdas triggered by SQS AWS recommends to have the SQS "Default Visibility Timeout" set to 6 times the Lambda timeout. It would be very useful to be able to set the Default Visibility Timeout for the SQS queue in Sereverless.yaml so if I change the functions timeout I can also set a higher value on the SQS queues Default Visibility Timeout.

Similar or dependent issues:

- N/A

**Comment by QAnders** [comment]
Recommendation can be read here: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#events-sqs-queueconfig

> To allow your function time to process each batch of records, set the source queue's visibility timeout to at least 6 times the timeout that you configure on your function. The extra time allows for Lambda to retry if your function execution is throttled while your function is processing a previous batch.

**Comment by jaffacake** [comment]
This is already possible when you define your SQS resource in the serverless.yaml:

```
Resources:
  TestQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: testing
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - TestDLQ
            - Arn
        maxReceiveCount: 5
      VisibilityTimeout: 40
```
