### ISSUE TITLE
Can't see spans on new dashboard

### ISSUE THREAD

**Issue by zakaria-soufiani** [serverless/serverless#6572]
# This is a Bug Report

## Description

- What went wrong?
 Deployed a basic python3.7 lambda that writes to a dynamo table using the new version but can't see spans on the invocation dashboard page
- What did you expect should have happened?
Being able to see spans of dynamo being called
- What was the config you used?
```
org: zakxx
app: sls-demo
service: sls-demo

provider:
  name: aws
  runtime: python3.7
  profile: sls-local
  stage: dev
  region: ap-southeast-2
  environment:
    REGION: ${self:provider.region}
    DYNAMODB_TABLE: 'sls-table'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
```
- What stacktrace or error message from your provider did you see?
none

## Additional Data

- **_Serverless Framework Version you're using_**: 1.50.0
- **_Operating System_**: MacOS Darwin
- **_Stack Trace_**: none
- **_Provider Error messages_**: none
