### ISSUE TITLE
cognitoUserPool with existing true create another userpool

### ISSUE THREAD

**Issue by michelem09** [serverless/serverless#6579]
# This is a Bug Report

## Description

- What went wrong?

If I use `existing:true` on a Cognito User Pool event, the userpool is created instead using that

- What did you expect should have happened?

Should use the existing one

- What was the config you used?

```
functions:
  preSignUp:
    handler: src/preSignUp.handler
    memorySize: 128
    timeout: 10
    layers:
      - { Ref: AuthToolsCommonLambdaLayer }
    events:
      - cognitoUserPool:
          pool: myUserPoolName
          trigger: PreSignUp
          existing: true
```

- What stacktrace or error message from your provider did you see?

Similar or dependent issues:

- #12345

## Additional Data

- **_Serverless Framework Version you're using_**: 1.50.0
- **_Operating System_**: Mac OS

**Comment by michelem09** [comment]
I think you should refer to userPool by `poolId` and not by `pool` (name).

**Comment by medikoo** [comment]
@pmuens take a look, when you're available

**Comment by exoego** [comment]
> I think you should refer to userPool by `poolId` and not by `pool` (name).

Initially planned so, but `pool` was chosen in https://github.com/serverless/serverless/pull/6362

**Comment by michelem09** [comment]
Honestly I don't know how this can work, you cannot get a userPool by name because name is not unique and there isn't any method to do so.
Indeed when I deploy this config I have two identical-named user pools in my cognito, one created by sls and my existing one.

Investigating your code there is something weird, because here you try to get resource by `poolName` https://github.com/serverless/serverless/blob/35d1b8b1a33c723bddd18c0b7a210c7c69c660d5/lib/plugins/aws/package/compile/events/cognitoUserPool/index.js#L312

But then that function `getCognitoUserPoolLogicalId` seems to look for `poolId` instead https://github.com/serverless/serverless/blob/6a84748fe39074cc6edbdd527f2f8e8e88a3298e/lib/plugins/aws/lib/naming.js#L364

I tried also to use my `poolId` in the config but a new pool with `poolId` as `name` is created.

**Comment by pmuens** [comment]
Thanks for reporting @michelem09 :+1:

We've chosen `pool` so that there's nothing the user hast to change in his config in order to make the support for existing Cognito User Pools to work. It seems like the problem occurs only when there are 2 pools with the same name (our integration tests for example work fine since they only create pools with different names).

We should certainly fix that and try to find a way to implement support for this while keeping the same config.

**Comment by michelem09** [comment]
Well, don't forget the problem is about the `existing: true` option, probably letting create the pool from sls works fine. To keep compatibility you could add the `poolId` option only for who wants to use existing pool. Please let me know if you wanna try something, I will be available.

**Comment by pmuens** [comment]
Hey @michelem09 thanks again for reporting and sorry for the slow response on our end.

I just looked into this today. (Un)fortunately I couldn't reproduce the reported error. Maybe it has been fixed in the meantime?

I do see the problem using the non-unique pool name for existing user pools. I tested this today with 2 pools having the same name. In my case the pool I created at first gets the Trigger attached, whereas the other pool is simply ignored.

Given that such a change should be backwards compatible we might need to introduce the `poolId` config as you and @exoego mentioned above. Would be nice if we somehow could determine if we're dealing with a pool `id` or a pool `name` so that we can leave the API the same (sticking to the `pool` config parameter) and just trigger different code-paths internally based on whether we're dealing with a pool `name` or an `id`.

Anyway, changing implementing this would be a different issue and we should therefore track that in a different issue since this only concerns a bug where a User Pool is created rather than updated (which I couldn't reproduce with the current `master` as mentioned above).

**Comment by 3dw1np** [comment]
I have got the same issue if I have already a cognitoUserPool created by a Cloudformation Stack and trying to use it in serverless by:

`  cognito_custom_message:
    handler: cognitoCustomMessage.handler
    name: notif-cognito_custom_message-${self:provider.stage}
    events:
      - cognitoUserPool:
          pool: MyUserPool_${self:provider.stage}
          trigger: CustomMessage
          existing: true
`

It will try to create a new one.

**Comment by medikoo** [comment]
> It will try to create a new one.

Can you confirm you're relying on latest `serverless` version? We've just fixed related issue: https://github.com/serverless/serverless/pull/7065 and it was published with v1.59.2

**Comment by 3dw1np** [comment]
Yes I am.

```
serverless -v
Framework Core: 1.59.3
Plugin: 3.2.5
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by medikoo** [comment]
Thanks can you share all your config (with sensitive parts masked out) ? Or at least minimal config with which you find it happening

**Comment by 3dw1np** [comment]
```
service: notifications-lambdas
Description: "Lambdas for notifications"

custom:
  AWS_SES_REGION:
    dev: eu-west-1
    stg: eu-west-1
    prd: eu-west-1
  AWS_SNS_REGION:
    dev: eu-west-1
    stg: eu-west-1
    prd: eu-west-1
  ROLE_ARN:
    dev: arn:aws:iam::*****:role/Lambda_*****_Role_dev
    stg: arn:aws:iam::*****:role/Lambda_*****_Notifications_Role_stg
    prd: arn:aws:iam::*****:role/Lambda_*****_Notifications_Role_prd
  SNS_TOPIC_ARN:
    dev: arn:aws:sns:eu-central-1:*****:bnta-notifications
    stg: arn:aws:sns:eu-central-1:*****:bnta-notifications
    prd: arn:aws:sns:eu-central-1:*****:bnta-notifications
  AWS_S3_TPL_BUCKET_NAME:
    dev: templates-*****-dev
    stg: templates-*****-stg
    prd: templates-*****-prd
  AWS_S3_TPL_HTML_PATH:
    dev: email_html
    stg: email_html
    prd: email_html
  EMAIL_SENDER:
    dev: ***** <no-reply@dev.*****.com>
    stg: ***** <no-reply@stg.*****.com>
    prd: ***** <no-reply@*****.com>
  BASE_WEB_URL:
    dev: https://dev.*****.com.s3-website.eu-central-1.amazonaws.com/
    stg: https://stg.*****.com
    prd: https://*****.com
  BASE_TEMPLATES_URL:
    dev: https://templates-*****-dev.s3-website-eu-central-1.amazonaws.com
    stg: https://templates-*****-stg.s3-website-eu-central-1.amazonaws.com
    prd: https://templates-*****-prd.s3-website-eu-central-1.amazonaws.com
  BASE_CDN_URL:
    dev: https://s3-eu-central-1.amazonaws.com/cdn-*****-dev
    stg: https://s3-eu-central-1.amazonaws.com/cdn-*****-stg
    prd: https://s3-eu-central-1.amazonaws.com/cdn-*****-prd
  
provider:
  name: aws
  stackName: ${self:service.name}
  stage: ${opt:stage, 'dev'}
  runtime: python2.7
  region: eu-central-1
  environment:
    ENV: ${self:provider.stage}
    AWS_SES_REGION: ${self:custom.AWS_SES_REGION.${self:provider.stage}}
    AWS_SNS_REGION: ${self:custom.AWS_SNS_REGION.${self:provider.stage}}
    AWS_S3_TPL_BUCKET_NAME: ${self:custom.AWS_S3_TPL_BUCKET_NAME.${self:provider.stage}}
    AWS_S3_TPL_HTML_PATH: ${self:custom.AWS_S3_TPL_HTML_PATH.${self:provider.stage}}
    EMAIL_SENDER: ${self:custom.EMAIL_SENDER.${self:provider.stage}}
    BASE_WEB_URL: ${self:custom.BASE_WEB_URL.${self:provider.stage}}
    BASE_TEMPLATES_URL: ${self:custom.BASE_TEMPLATES_URL.${self:provider.stage}}
    BASE_CDN_URL: ${self:custom.BASE_CDN_URL.${self:provider.stage}}
  deploymentBucket:
    name: infra-*******-${self:provider.stage}
  role: ${self:custom.ROLE_ARN.${self:provider.stage}}
  stackTags:
    env: ${self:provider.stage}

functions:
  cognito_custom_message:
    handler: cognitoCustomMessage.handler
    name: notif-cognito_custom_message-${self:provider.stage}
    events:
      - cognitoUserPool:
          pool: pool_${self:provider.stage}
          trigger: CustomMessage
          existing: true

plugins:
  - serverless-python-requirements

```

**Comment by 3dw1np** [comment]
but the exact error is: 

ServerlessError: An error occurred: CognitoUnderscorecustomUnderscoremessageCustomCognitoUserPool1 - Failed to create resource. User: arn:aws:sts::******:assumed-role/notifications-lambdas-IamRoleCustomResourcesLambda-******/notifications-lambdas-dev-custom-resource-existing-cup is not authorized to perform: iam:PassRole on resource: arn:aws:iam::******:role/service-role/Cognito_******_SMS_Role_dev See details in CloudWatch Log: 2019/12/12/[$LATEST]6ec6f38694b*********.

**Comment by medikoo** [comment]
@3dw1np if I read correctly error is that AWS rejected creation of `CognitoUnderscorecustomUnderscoremessageCustomCognitoUserPool1` resource due to lack of sufficient rights (`iam:PassRole`).

If that's correct, you need to ensure that user with which you're deploying the stack has necessary rights to create all resources that are outcome of your configuration.

**Comment by jameshartt** [comment]
Seeing the same issue as @3dw1np, the user deploying has full access, think this could be a separate bug, maybe not even associated with Serverless framework? But not able to attach an existing Cognito User Pool to a Lambda.

Have a similar setup to @3dw1np.

**Comment by jameshartt** [comment]
Here is my `serverless.yml`

service: users

plugins:
  - serverless-webpack
  - serverless-plugin-monorepo

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 256
  tracing:
    lambda: true

  environment:
    TABLE_NAME:
      ${file(../database/serverless.yml):custom.TABLE_NAME}


  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - 'Fn::ImportValue': ShowsTableArn-${self:custom.stage}
    - Effect: Allow
      Action: 
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: 
        - "*"
functions:
  signedUp:
    handler: src/signedUp.main
    events:
      - cognitoUserPool:
          pool: user-pool-${self:custom.stage}
          trigger: PostConfirmation
          existing: true

**Comment by medikoo** [comment]
@jameshartt thanks for detailed information. Are you using latest version of a framework (v1.60.0) ? 

If so, and problem still occurs, can you help me derive a minimal test case that reproduces that, and which derives from this service: https://github.com/medikoo/test-serverless/blob/2069c7d4856b2191307f27e86dc30d539b60f386/serverless.yml ?

This is the simple service, which deploys without issues on my side. It attaches to existing `test-pool` cognito pool, which was created with default settings.

**Comment by jameshartt** [comment]
Positive on v1.60.0, will get together the test tomorrow, thanks for your speedy reply!

**Comment by jameshartt** [comment]
So put together a test, can reproduce whilst checking out your service on that hash.

I can give you the slightly modified (removing Imports etc.) auth service that creates the existing user pool with the same name in your repo.

```
service: auth-test

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 256
  tracing:
    lambda: true

resources:
  Resources:
    SNSRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument: 
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal: 
                Service: 
                  - "cognito-idp.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "CognitoSNSPolicy"
            PolicyDocument: 
              Version: "2012-10-17"
              Statement: 
                - Effect: "Allow"
                  Action: "sns:publish"
                  Resource: "*"

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: test-pool
        AutoVerifiedAttributes:
          - email
        SmsConfiguration:
          ExternalId: sms-config-external
          SnsCallerArn: !GetAtt SNSRole.Arn
        Schema:
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
          - Name: phone_number
            AttributeDataType: String
            Mutable: false
            Required: true
        UsernameAttributes:
          - email
          - phone_number

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: test-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false

    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: IdentityPool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClient
            ProviderName:
              Fn::GetAtt: [ "CognitoUserPool", "ProviderName" ]
              
    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [CognitoAuthRole, Arn]
            
    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Federated: 'cognito-identity.amazonaws.com'
              Action:
                - 'sts:AssumeRoleWithWebIdentity'
              Condition:
                StringEquals:
                  'cognito-identity.amazonaws.com:aud':
                    Ref: CognitoIdentityPool
                'ForAnyValue:StringLike':
                  'cognito-identity.amazonaws.com:amr': authenticated
        Policies:
          - PolicyName: 'CognitoAuthorizedPolicy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'mobileanalytics:PutEvents'
                    - 'cognito-sync:*'
                    - 'cognito-identity:*'
                  Resource: '*'
                
                # Allow users to invoke our API
                - Effect: 'Allow'
                  Action:
                    - 'execute-api:Invoke'
                  Resource:
                    Fn::Join:
                      - ''
                      -
                        - 'arn:aws:execute-api:'
                        - Ref: AWS::Region
                        - ':'
                        - Ref: AWS::AccountId
                        - ':'
                        - '*'
                        - '/*'


  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool

    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient

    IdentityPoolId:
      Value:
        Ref: CognitoIdentityPool
```
The exact error is different to the one I get, but it is of the same type (failing to create a resource):
```
Serverless: View the full error output: https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-central-1%3A702707212168%3Astack%2Ftest-cognito-user-pool-existing-dev%2Fab80edf0-2246-11ea-be3a-0ac843449136

  Serverless Error ---------------------------------------

  An error occurred: FunctionCustomCognitoUserPool1 - Failed to create resource. Cannot read property 'Id' of null See details in CloudWatch Log: 2019/12/19/[$LATEST]1be6400bae3f4555acfb637d33b24b28.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              13.4.0
     Framework Version:         1.60.0
     Plugin Version:            3.2.6
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

**Comment by medikoo** [comment]
@jameshartt thanks for that info.

Does CloudFormation deployment on AWS side, fails with `Cannot read property 'Id' of null` ?
That actually looks as some obvious bug on AWS side, which I believe should be reported to them.

Can you share full debug log, when running it with `SLS_DEBUG=*`?

**Comment by jameshartt** [comment]
On it now 😄

**Comment by jameshartt** [comment]
Sorry, my first test was wrong because it was in a different region, my bad (not enough coffee consumed just yet...!). However, I do now have my original issue.

Here first is the log for the auth service (some things redacted and changed)
[auth-log.txt](https://github.com/serverless/serverless/files/3982986/auth-log.txt)

Secondly your test service, in eu-west-1:
[test-serverless-log.txt](https://github.com/serverless/serverless/files/3983042/test-serverless-log.txt)

**Comment by jameshartt** [comment]
Thanks a lot for your assistance, hopefully I'm not doing anything too stupid!

**Comment by medikoo** [comment]
Thank you @jameshartt I have that reproduced locally. Looking into it.

**Comment by jameshartt** [comment]
Excellent stuff, thank you very much!

**Comment by jan-wilhelm** [comment]
This is still happening for me on 1.64.0

**Comment by medikoo** [comment]
@jan-wilhelm it must be some other reason then. Please prepare a minimal test case (which doesn't involve any plugins) which reproduces that reliable and report it with other issue.

**Comment by yashutanna** [comment]
hey guys 

@jameshartt 
Im facing the same issue...
not really sure where i am going wrong. 

what did you do to fix this from AWS's side?

 Serverless Error ---------------------------------------
 
  An error occurred: CognitoCustomMessageTriggerCustomCognitoUserPool1 - Failed to create resource. Cannot read property 'Id' of null See details in CloudWatch Log: 2020/03/13/[$LATEST]767f9448e7ce4b9b82be3d24e1b5c00a.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.0
     Framework Version:         1.60.5
     Plugin Version:            3.5.0
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

**Comment by nirLumigo** [comment]
@yashutanna 
It happened to me when I passed user-pool-id instead of user-pool-name.

**Comment by medikoo** [comment]
@yashutanna you're using outdated version of a Framework, please update

**Comment by YannicEl** [comment]
passing userpool name insted of userpool id fixed the problem for me aswell

**Comment by adil-uddin** [comment]
@medikoo @pmuens is it possible to use` findUserPoolById` instead of `findUserPoolByName` to get existing Cognito user pools ? Currently, it seems the event only works when we use userPoolName instead of Arn. I run multiple microservices in my app and use Outputs to refer to resources and we can only output the Arn of the user pool.

**Comment by medikoo** [comment]
@adil-uddin can you open a new issue, with use case description

**Comment by jeremy-london** [comment]
Has there been an issue opened the use case @adil-uddin had? 

Additionally found my way here after getting caught with the `Id` of the pool rather than the `name`.. it returned the CloudWatch log error

Could you point me the right way to get the online docs updated to add a note to the Existing User Pools Section?
https://www.serverless.com/framework/docs/providers/aws/events/cognito-user-pool#using-existing-pools

A simple note about what `pool` should be would help alot! (i.e.: Use the name instead of the Pool ID)

**Comment by medikoo** [comment]
@jeremy-london docs are handled here: https://github.com/serverless/serverless/blob/master/docs/providers/aws/events/cognito-user-pool.md

**Comment by morgler** [comment]
I tried referencing the Cognito pool by all these methods, but all gave the `Failed to create resource` error:

- ARN
- Pool-ID (eu-central_…)
- Name (as the title in the AWS console)
- Normalized name (CognitoUserPool<Pool-ID>)
- Normalized name using name (CognitoUserPool<NameFromConsole>)

The user pool and the lambda function are in the same region (eu-central-1). What am I missing?

**Comment by medikoo** [comment]
@morgler For general support please check:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

**Comment by morgler** [comment]
@medikoo thanks. I figured it out and it worked by just using the plain name given to the user pool without any prefixes. 

Might be helpful on this case for people also getting the error: use the plain name without prefixes (not the ID, not the ARN).

**Comment by CodySwannGT** [comment]
Using the name doesn't make a ton of sense because there is no way to export the name from CloudFormation.

I want to do something like this:

```
preTokenGeneration:
    handler: src/lambdas/cognito/pre-token-generation.handler
    events:
      - cognitoUserPool:
          pool: 
            Fn::ImportValue: UserPoolId
          trigger: PreTokenGeneration
          existing: true
```

But it's not possible because user pool name is not available to export
