### ISSUE TITLE
Amazon Partner EventBridge resource name violates name constraints

### ISSUE THREAD

**Issue by trevorrecker** [serverless/serverless#6594]
# This is a Bug Report

## Description

When a Lambda subscribes to a custom event source in Amazon EventBridge, the resource name (such as the Rule that is created) contains the partner prefix which includes slash (`/`) characters that fail Amazon's validation. In addition to this, the prefix takes up a large portion of the 64 characters allowed for an ARN identifier. 

For events sourced from Segment.com, the rule ARN looks like the following:

```
aws.partner/segment.com/XXXXXXXXXX/dispatcher-dev-create-request-sf-rule-1
```

The error output (shown below) says the name does not comply with Amazon's regular expression pattern of: `[\.\-_A-Za-z0-9]+`.

The partner prefix (`aws.partner/segment.com/XXXXXXXXXX/`) takes up 35 characters of the identifier, and with the service, stage, and function name included, this particular example is 74 characters long, which surpasses Amazon's 64 character limit.

In addition to this prefix taking up space and failing validation, the creation of EventBridge resources like this rule do not throw an error during deployment. Instead, the deploy completes as expected and then the rule is shown as an error in the AWS Console, displaying the following error in the interface:

```
There was an error while retrieving details for rule aws.partner/segment.com/XXXXXXXXXX/dispatcher-dev-create-request-sf-rule-1.
Details: 2 validation errors detected: 
Value 'aws.partner/segment.com/XXXXXXXXXX/dispatcher-dev-create-request-sf-rule-1' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_A-Za-z0-9]+; 
Value 'aws.partner/segment.com/XXXXXXXXXX/dispatcher-dev-create-request-sf-rule-1' at 'name' failed to satisfy constraint: Member must have length less than or equal to 64.
```

Similar or dependent issues:

- #6514 
- #6518 

## Additional Data

- **_Serverless Framework Version you're using_**: 1.50.0
- **_Operating System_**: macOS Mojave 10.14.6
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by pmuens** [comment]
Hey @trevorrecker thanks for opening :+1:

I tried to reproduce this today but I ran into an Issue where I cannot configure Segment anymore (it returns `Validation Error not implemented integration` when I use the event tester for EventBridge on Segments end).

In the meantime could you post a `serverless.yml` file which I can use to reproduce this bug? I remember that I deployed a test service in the past when we both fixed the other issue and in that case everything worked smoothly.

Thanks in advance and let me know if you need any help here.

**Comment by trevorrecker** [comment]
@pmuens Here's a stripped down `serverless.yml` that is what I used when the above error occurred:

```yaml
service: salesforce-dispatcher

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
 
functions:
  create-request-sf:
    handler: functions/create-request-sf.handler
    events:
    - eventBridge:
        eventBus: 'arn:aws:events:us-east-1:111111111111:event-bus/aws.partner/segment.com/XXXXXXXXXX'
        pattern:
          source:
            - 'aws.partner/segment.com/XXXXXXXXXX'
          detail:
            event:
              - 'Event Name Here'
            type:
              - 'track'
        inputPath: '$.detail'
```

Here's the JSON for the event that I sent in Segment's Event Tester that should trigger the above function:

```JSON
{
  "messageId": "test-message-56nm9m",
  "timestamp": "2019-09-06T03:59:40.083Z",
  "type": "track",
  "email": "test@example.org",
  "projectId": "XXXXXXXXXX",
  "properties": {},
  "userId": "test-user-abc123",
  "event": "Event Name Here"
}
```

I sent the above from the following page: `https://app.segment.com/{accountName}/destinations/amazon-eventbridge/sources/java/event-tester`

> In the above, Amazon account ID, segment ID and segment account name have all been replaced with placeholders.

When I deployed this before, the `serverless deploy` went through fine but going to the Lambda in the AWS console, clicking on the Segment.com trigger and viewing the Rule that was created displays the error in the interface that I mentioned in the initial post.

**Comment by pmuens** [comment]
Thanks for the update @trevorrecker :+1:

After some fiddling I was finally able to reproduce the problem. Looking into a potential fix right now...

**Comment by trevorrecker** [comment]
@pmuens Any updates on this issue? We are still unable to use EventBridge with partner sources.

**Comment by pmuens** [comment]
Hey @trevorrecker thanks for pining and sorry for the slow response on my end.

I just looked into this again but couldn't reproduce the bug anymore. Here's the service I've used:

```yaml
service: my-test-service-${self:custom.idx}

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  region: us-east-1
  stage: dev

custom:
  idx: 0

functions:
  hello:
    handler: functions/handler.handler
    events:
      - eventBridge:
          eventBus: arn:aws:events:us-east-1:YYYYYY:event-bus/aws.partner/segment.com/XXXXXX
          pattern:
            source:
              - aws.partner/segment.com/XXXXXX
            detail:
              event:
                - 'Event Name Here'
              type:
                - 'track'
          inputPath: '$.detail'
```

I do see the "Segment" event source and everything is configured according to the `serverless.yml` file.

Maybe AWS has fixed such a problem in the meantime? Could you update to the newest Serverless Framework version and try again?

The only thing we might want to improve is the naming which can get quite verbose and therefore exceed the 64 char limit, but before doing that I wanted to ensure that the main EventBridge functionality works with AWS Partner event sources.
