### ISSUE TITLE
Support MaximumBatchingWindowInSeconds parameter for DynamoDB and Kinesis triggers

### ISSUE THREAD

**Issue by vladgolubev** [serverless/serverless#6610]
# This is a Feature Proposal

## Description

See https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html#stream-events

> By default, Lambda invokes your function as soon as records are available in the stream. If the batch it reads from the stream only has one record in it, Lambda only sends one record to the function. To avoid invoking the function with a small number of records, you can tell the event source to buffer records for up to 5 minutes by configuring a batch window. Before invoking the function, Lambda continues to read records from the stream until it has gathered a full batch, or until the batch window expires.

See https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#25200

> feature: Lambda: Adds a "MaximumBatchingWindowInSeconds" parameter to event source mapping api's. Usable by Dynamodb and Kinesis event sources.

#### Suggested config

```yml
functions:
  preprocess:
    handler: handler.preprocess
    events:
      - stream:
          arn: arn:aws:kinesis:region:XXXXXX:stream/foo
          batchSize: 100
          maximumBatchingWindowInSeconds: 300
          startingPosition: LATEST
```
