### ISSUE TITLE
serverless deploy fails with ROLLBACK_COMPLETE error

### ISSUE THREAD

**Issue by carlosonunez** [serverless/serverless#6612]
# This is a Bug Report

## Description

- What went wrong?

I got the following error message upon trying to re-deploy my function after a previous error:

```
Serverless Error ---------------------------------------

  Stack:arn:aws:cloudformation:us-east-2:018790755515:stack/gmail-to-expensify-forwarding-service-dev/0ac0c780-cb27-11e9-9a01-0ab95d3a5528 is in ROLLBACK_COMPLETE state and can not be updated.
```

- What did you expect should have happened?

Serverless should have attempted to deploy the function.

- What was the config you used?

```
---
service:
  name: gmail-to-expensify-forwarding-service

frameworkVersion: '>=1.0.0'

provider:
  name: aws
  runtime: ruby2.5
  region: ${opt:region, 'us-east-2'}
  memorySize: 128
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}
  deploymentPrefix: serverless

package:
  include:
    - lib/**
    - bin/**
    - .env

functions:
  forwarderBegin:
    handler: bin/forwarder.begin
    description: Begins scanning for and forwarding receipts.
    timeout: 60
    events:
      - schedule:
          name: Gmail Receipt check
          description: Checks for receipts
          rate: rate(1 minute)
          enabled: true
```
- What stacktrace or error message from your provider did you see?

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service gmail-to-expensify-forwarding-service.zip file to S3 (13.76 KB)...
Serverless: Validating template...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

  Stack:arn:aws:cloudformation:us-east-2:018790755515:stack/gmail-to-expensify-forwarding-service-dev/0ac0c780-cb27-11e9-9a01-0ab95d3a5528 is in ROLLBACK_COMPLETE state and can not be updated.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.16.1
     Framework Version:         1.50.0
     Plugin Version:            1.3.8
     SDK Version:               2.1.0

```

Similar or dependent issues:

- #12345

## Additional Data

Using `awscli` to manually delete the CloudFormation stack seems to resolve the issue.

- **_Serverless Framework Version you're using_**:
- **_Operating System_**:
- **_Stack Trace_**:
- **_Provider Error messages_**:
