### ISSUE TITLE
Unzipped size must be smaller than 182402329 bytes

### ISSUE THREAD

**Issue by ElGecko76** [serverless/serverless#6619]
Hi,

I have a Symfony 4 website and I would like deploy it but I have this error : 

> An error occurred: ConsoleLambdaFunction - Unzipped size must be smaller than 182402329 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 8c900c39-3347-4c60-9e9f-3b14a3eb3fbb).

when I use this following command : 

> serverless deploy -v

![image](https://user-images.githubusercontent.com/19478137/64129443-4fed2c80-cdbc-11e9-87bc-2aded41aeab2.png)

serverless.yaml :

```
service: bref-symfony

provider:
    name: aws
    region: eu-west-3
    runtime: provided
    environment:
        # Symfony environment variables
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    website:
        handler: public/index.php
        timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
    console:
        handler: bin/console
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-73} # PHP
            - ${bref:layer.console} # The "console" layer
```

How can I make it work please?
