### ISSUE TITLE
Too Many Requests error of CustomApiGatewayAccountCloudWatchRole resource

### ISSUE THREAD

**Issue by hoang-innomizetech** [serverless/serverless#6643]
# This is a Bug Report

## Description
I have customized the logs as below:

```
logs:
    restApi: # Optional configuration which specifies if API Gateway logs are used. This can either be set to true to use defaults, or configured via subproperties.
      accessLogging: true # Optional configuration which enables or disables access logging. Defaults to true.
      format: 'requestId: $context.requestId' # Optional configuration which specifies the log format to use for access logging.
      executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
      level: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
      fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
    websocket: false # Optional configuration which specifies if Websockets logs are used
    frameworkLambda: true # Optional, whether to write CloudWatch logs for custom resource lambdas as added by the framework
```

- When deploying I am getting Too Many Requests error that prevents deploy the serverless service
- If I disabled the logs config, then I will able to deploy service without any error

## Additional Data

An error occurred: CustomApiGatewayAccountCloudWatchRole - Failed to create resource. Too Many Requests See details in CloudWatch Log: 2019/09/06/[$LATEST]fedeb44ac1a446bc8ff6fb8558122435.

Framework Core: 1.51.0
Plugin: 1.3.9
SDK: 2.1.0
