### ISSUE TITLE
API Keys must be strings

### ISSUE THREAD

**Issue by airmonitor** [serverless/serverless#6651]
# This is a Bug Report

## Description

- What went wrong?
  API Keys were not created.

- What did you expect should have happened?
  API Keys with assigned usage plan were created.

- What was the config you used?

```
  apiKeys:
    - buenos:
        - ${self:service}:${self:provider.stage}-BuenosPotatos
    - pomidoros:
        - ${self:service}:${self:provider.stage}-PomidorosMark
        - ${self:service}:${self:provider.stage}-PomidorosTom
  usagePlan:
    - buenos:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100
    - pomidoros:
        quota:
          limit: 100000
          period: MONTH
          offset: 2
        throttle:
          burstLimit: 200
          rateLimit: 100
```
 
- What stacktrace or error message from your provider did you see?
```
Serverless: [serverless-plugin-epsagon] Wrapping your functions with Epsagon...
Serverless: [serverless-plugin-epsagon] You have some Python Lambda functions. Please make sure Epsagon's Python library is installed.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: [serverless-plugin-epsagon] Cleaning up Epsagon's handlers
 
  Serverless Error ---------------------------------------
 
  API Keys must be strings
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Framework Version:         1.51.0
     Plugin Version:            1.3.11
     SDK Version:               2.1.0
 

```
Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**:  1.51.0
- **_Operating System_**: VERSION="19.2 (Tina)"
- **_Stack Trace_**:
- **_Provider Error messages_**:
