### ISSUE TITLE
AWS API GW WebSocket logs does not respect logRetentionInDays

### ISSUE THREAD

**Issue by exoego** [serverless/serverless#6657]
# This is a Bug Report

## Description

- What went wrong?
Log retentions days not set for CloudWatch log group for websocket.

- What did you expect should have happened?
Log retension days should be set, as same as for lambda and rest APIs.

- What was the config you used?
```yaml
service: logs

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  logRetentionInDays: "3"
  logs:
    restApi: true
    websocket: true

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
  helloWebSocket:
    handler: handler.hello
    events:
      - websocket: "$connect"
```
- What stacktrace or error message from your provider did you see?
No stack trace.

Similar or dependent issues:

- None

## Additional Data

- **_Serverless Framework Version you're using_**: 1.51.0
- **_Operating System_**: Ubuntu 18.04
- **_Stack Trace_**: None
- **_Provider Error messages_**: None
