### ISSUE TITLE
CorsRules does not support ExposeHeader

### ISSUE THREAD

**Issue by Laurian** [serverless/serverless#6669]
# This is a Bug Report

## Description

- What went wrong?
`sls deploy` reported `An error occurred: StorageBucket - Encountered unsupported property ExposeHeader.`

- What did you expect should have happened?

sls to update the bucket’s CORS Policy with:
```xml
<ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
<ExposeHeader>x-amz-request-id</ExposeHeader>
<ExposeHeader>x-amz-id-2</ExposeHeader>
<ExposeHeader>ETag</ExposeHeader>
```

- What was the config you used?
```yaml
resources:
  Resources:
    StorageBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
              ExposeHeader:
                - x-amz-server-side-encryption
                - x-amz-request-id
                - x-amz-id-2
                - ETag
```

- What stacktrace or error message from your provider did you see?

Without `ExposeHeader` support I cannot upload to S3 from browser with aws-amplify
```
AWSS3Provider - error uploading ETagMissing:
No access to ETag property on response.
Check CORS configuration to expose ETag header
```

Similar or dependent issues:

- #6442

## Additional Data

- **_Serverless Framework Version you're using_**: 1.51.0
- **_Operating System_**: macOS 10.15 beta
- **_Provider Error messages_**: AWSS3Provider - error uploading ETagMissing: No access to ETag property on response. Check CORS configuration to expose ETag header.
