### ISSUE TITLE
[AWS] Granular logRetentionInDays configurations

### ISSUE THREAD

**Issue by exoego** [serverless/serverless#6672]
# This is a Feature Proposal

## Description

Currently, we have only global `logRetentionInDays`.
```yaml
provider:
  name: aws
  logRetentionInDays: '3'
```

However, `logRetentionInDays` may vary depending on AWSs (rest API, websocket, lambda...) because their loggin volume/velocity may vary.

It would be great if we can configure `logRetentionInDays` per AWS, something like this:
```yaml
provider:
  name: aws
  logs:
    websocket:
      retentionInDays: '3'
    restApi:
      retentionInDays: '5'
```

Original idea: https://github.com/serverless/serverless/pull/6658#pullrequestreview-286064940
