### ISSUE TITLE
Native VPC support - Expert setup

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless#6674]
Extend https://github.com/serverless/serverless/issues/6673 so that one can tweak the `vpc` setup via a custom config.

```yaml
vpc:
  availabilityZones: 2
  internetGateway: false
  subnets:
    private:
      cidrBlock: '10.0.0.0/22'
```

Again, shoutouts to @alexdebrie who came up with the idea.
