### ISSUE TITLE
Resolve CloudFormation functions for invoke local

### ISSUE THREAD

**Issue by Ryanauger95** [serverless/serverless#6680]
Right now, If I have a variable definition:
```
TOPIC_ARN:
    Fn::Join:
    - ""
    - - "arn:aws:sns:"
      - ${self:provider.environment.DEPLOY_REGION}"
      - ":"
      - Ref: "AWS::AccountId"
      - ":"
      - ${self:custom.TOPIC
```

It won't run Fn::Join locally. The entire output just becomes a string:
console.log(TOPIC_ARN): “{ ‘Fn::Join’: [ ‘’, [Array] ] } }”

Is there any way/what should we do about this when testing locally?

**Comment by Wintereise** [comment]
> Is there any way/what should we do about this when testing locally?

We've been namespacing it under custom.

```    
 custom:
   innerAWSSNSPlatformApplicationArn:
        local: arn:aws:sns:${self:provider.region}:${self:custom.awsAccountId}:app/GCM/${self:service}-staging-push-sns
        dev: arn:aws:sns:${self:provider.region}:${self:custom.awsAccountId}:app/GCM/${self:service}-${self:provider.stage}-push-sns
        staging: arn:aws:sns:${self:provider.region}:${self:custom.awsAccountId}:app/GCM/${self:service}-${self:provider.stage}-push-sns
        prod: arn:aws:sns:${self:provider.region}:${self:custom.awsAccountId}:app/GCM/${self:service}-${self:provider.stage}-push-sns
```

Then, where you actually use it, you could go `${self:custom.<key>.<stage>`, the trick would be to hardcode it for local.

Only a workaround, but has served us well so far.
