### ISSUE TITLE
Serverless Error: InternalFailure with Bitbucket CI/CD

### ISSUE THREAD

**Issue by anuj9196** [serverless/serverless#6690]
# This is a Bug Report

## Description

I'm using **Bitbucket CI/CD** to automate deployment. I have the following **bitbucket-pipeline.yml** content
```
image: node:11.13.0-alpine

pipelines:
  branches:
    staging:
      - step:
          caches:
            - node
          deployment: staging
          script:
            - apk add python3
            - npm install -g serverless
            - npm install -g @angular/cli
            - npm install
            - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
            - serverless deploy --stage ${DEPLOYMENT_STAGE} --no-confirm
```
and the following is the `serverless.yml` content
```
service: myapp
app: myapp
org: org

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, self:custom.variables.stage}
  region: ${opt:region, self:custom.variables.region}
  memorySize: ${opt:memory, self:custom.variables.memorySize}
  timeout: ${opt:timeout, self:custom.variables.timeout}
  logRetentionInDays: 14
  deploymentBucket:
    tags:
      name: ${self:custom.namePrefix}
  deploymentPrefix: ${self:custom.variables.deploymentPrefix}
  versionFunctions: ${self:custom.variables.versionFunctions}
  endpointType: ${self:custom.variables.endpointType}
  tracing:
    apiGateway: ${self:custom.variables.tracing.apiGateway}
    lambda: ${self:custom.variables.tracing.lambda}
  logs:
    restApi:
      accessLogging: ${self:custom.variables.logs.restApi.accessLogging}
      format: 'requestId: $context.requestId'
      executionLogging: ${self:custom.variables.logs.restApi.executionLogging}
      level: ${self:custom.variables.logs.restApi.level}
      fullExecutionData: ${self:custom.variables.logs.restApi.fullExecutionData}
    websocket: ${self:custom.variables.logs.websocket}
    frameworkLambda: ${self:custom.variables.logs.frameworkLambda}

packages:
  exclude:
    - .git/**
    - env.yml
    - readme.md

plugins:
  - fullstack-serverless
  - serverless-offline

custom:
  variables:
    stage: ${env:DEPLOYMENT_STAGE, 'dev'}
    region: ${env:AWS_REGION, 'us-west-2'}
    memorySize: ${env:MEMORY_SIZE, '512'}
    timeout: ${env:TIMEOUT, '30'}
    deploymentPrefix: ${env:DEPLOYMENT_PREFIX, 'serverless'}
    versionFunctions: false # ${env:VERSION_FUNCTIONS, 'false'}
    endpointType: ${env:ENDPOINT_TYPE, 'Edge'}
    tracing:
      apiGateway: true # ${env:TRACING_API_GATEWAY, 'true'}
      lambda: true # ${env:TRACING_LAMBDA, 'true'}
    logs:
      restApi:
        accessLogging: true # ${env:LOGS_ACCESS_LOGGING, 'true'}
        executionLogging: true # ${env:LOGS_EXECUTION_LOGGING, 'true'}
        level: ${env:LOGS_LEVEL, 'INFO'}
        fullExecutionData: true # ${env:LOGS_FULL_EXECUTION_DATA, 'true'}
      websocket: true # ${env:LOGS_WEBSOCKET, 'true'}
      frameworkLambda: true # ${env:LOGS_FRAMEWORK_LAMBDA, 'true'}

  namePrefix: ${self:provider.stage}-${self:provider.region}
  fullstack:
    bucketName: serverless-${self:custom.namePrefix}-frontend
    distributionFolder: webapp/dist/webapp
    singlePageApp: true
    clientCommand: npm install && ng build --aot --prod
    clientSrcPath: webapp

functions:
  hello:
    handler: handler.server
    description: Node Express application handler # Description of the function
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: truehttp://slss.io/sg-require-cfn-role

      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
```

- What went wrong?
The deployment of AWS services was successful but pipeline failed.

- What did you expect should have happened?
The deployment should be a success.

- What stacktrace or error message from your provider did you see?
```
Service Information
service: myapp
stage: qa
region: us-west-2
stack: myapp-qa
resources: 25
api keys:
  None
endpoints:
  ANY - https://p4avkpjr6c.execute-api.us-west-2.amazonaws.com/qa/
  ANY - https://p4avkpjr6c.execute-api.us-west-2.amazonaws.com/qa/{proxy+}
functions:
  hello: myapp-qa-hello
layers:
  None
CloudFront domain name
  dktfzu0tjrisz.cloudfront.net (CNAME: -)
Serverless: Recoverable error occurred (InternalFailure), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (InternalFailure), sleeping for 5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (InternalFailure), sleeping for 5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (InternalFailure), sleeping for 5 seconds. Try 4 of 4
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/org/applications/myapp/services/myapp/stage/qa/region/us-west-2
 
  Serverless Error ---------------------------------------
 
  InternalFailure
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              11.13.0
     Framework Version:         1.52.0
     Plugin Version:            2.0.0
     SDK Version:               2.1.1
```

Similar or dependent issues:

## Additional Data

- **_Serverless Framework Version you're using_**: 1.52.0
- **_Operating System_**: linux
- **_Stack Trace_**:
- **_Provider Error messages_**: InternalFailure
