### ISSUE TITLE
Deployment fails with error "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#6701]
# This is a Bug Report

## Description

- What went wrong?
When executing `serverless deploy` deployment failed at step `Serverless: Excluding development dependencies...` with an error `RangeError: Maximum call stack size exceeded`
- What did you expect should have happened?
Deployment should have completed as expected
- What was the config you used?
```yml
service: serverless-template
org: goingout
app: goingout
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  stackTags:
    Name: ${self:service}
    service_name: ${self:service}
    environment: ${opt:stage, self:provider.stage}
    managed_by: sls
functions:
  receiveNewUserEvent:
    handler: src/functions/receiveNewUserEvent.receiveNewUserEvent
plugins:
  - serverless-pseudo-parameters
  - serverless-mocha-plugin
custom:
  serverless-mocha-plugin:
    testTemplate: templates/testTemplate.ejs
    functionTemplate: templates/functionTemplate.ejs
resources:
  Resources:
    entityTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:service}-entity-${opt:stage, self:provider.stage}
        AttributeDefinitions: 
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
```
- What stacktrace or error message from your provider did you see?
```
Range Error --------------------------------------------
 
  RangeError: Maximum call stack size exceeded
      at Function.[Symbol.hasInstance] (<anonymous>)
      at WriteStream (/builds/going-out/goingout-report-service/node_modules/graceful-fs/graceful-fs.js:200:14)
      at WriteStream (/builds/going-out/goingout-report-service/node_modules/graceful-fs/graceful-fs.js:201:29)
      at WriteStream (/builds/going-out/goingout-report-service/node_modules/graceful-fs/graceful-fs.js:201:29)
      at WriteStream (/builds/going-out/goingout-report-service/node_modules/graceful-fs/graceful-fs.js:201:29)
...repeated a few 100 times...
at WriteStream (/builds/going-out/goingout-report-service/node_modules/graceful-fs/graceful-fs.js:201:29)
      at new WriteStream (/builds/going-out/goingout-report-service/node_modules/graceful-fs/graceful-fs.js:201:29)
      at Object.createWriteStream (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:306:12)
      at Package.zipFiles (/builds/going-out/goingout-report-service/node_modules/serverless/lib/plugins/package/lib/zipService.js:80:23)
      at resolveFilePathsAll.then.filePaths (/builds/going-out/goingout-report-service/node_modules/serverless/lib/plugins/package/lib/packageService.js:120:12)
      at tryCatcher (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromise0 (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/promise.js:619:10)
      at Promise._settlePromises (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/promise.js:699:18)
      at _drainQueueStep (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/builds/going-out/goingout-report-service/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.16.3
     Framework Version:         1.52.0
     Plugin Version:            2.0.0
     SDK Version:               2.1.1
```
Similar or dependent issues:

## Additional Data
When I rolled back to 1.51.0, deployment succeeded
