### ISSUE TITLE
Default deploymentBucket should enable S3 block public access

### ISSUE THREAD

**Issue by john-aws** [serverless/serverless#6706]
The default serverless deployment bucket should take advantage of the newish [S3 Block Public Access](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html) feature. It's a security best practice.

Underlying template changes would be to include:

```
PublicAccessBlockConfiguration:
    BlockPublicAcls: true
    BlockPublicPolicy: true
    IgnorePublicAcls: true
    RestrictPublicBuckets: true
```
