### ISSUE TITLE
Lambda fails: "Runtime.ImportModuleError: Error: Cannot find module <module name>"

### ISSUE THREAD

**Issue by codeinaire** [serverless/serverless#6724]
# This is a Bug Report

## Description

- What went wrong?
I created two lambda layers and when I tested the lambda's on which they depend I got the following error: Runtime.ImportModuleError: Error: Cannot find module <package name>

However, without using the layers configuration the functions run successfully. For this reason I figured it may be a bug.
- What did you expect should have happened?
The lambdas to run successfully
- What was the config you used?
```
service: auth0-custom-authorizers

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2

layers:
  graphql:
    path: node_modules # required, path to layer contents on disk
    name: graphql # optional, Deployed Lambda layer name
    description: This is for the graphql lambda # optional, Description to publish to AWS
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs10.x
    licenseInfo: GPLv3 # optional, a string specifying license information
    allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
      - '*****'
    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created
  authorizer:
    path: custom_authorizer/lambda/node_modules # required, path to layer contents on disk
    name: authorizer # optional, Deployed Lambda layer name
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs10.x
    allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
      - '829131444792'

functions:
  auth:
    handler: custom_authorizer/lambda/authorizer.auth
    cors: true
    environment:
      TOKEN_ISSUER: *****
      AUDIENCE: *****
      JWKS_URI: *****
    layers:
      - { Ref: AuthorizerLambdaLayer }
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/index.graphql
    events:
    - http:
        path: nmm-app
        method: post
        authorizer: auth
        cors: true
    - http:
        path: nmm-app
        method: get
        authorizer: auth
        cors: true
    layers:
    # Name = <name of layer>LambdaLayer
      - { Ref: GraphqlLambdaLayer }

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
```
- What stacktrace or error message from your provider did you see?
```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module '<module name>'",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'dotenv'",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}
```
Similar or dependent issues:

Not sure if this is fundamentally similar, but it's the same error message:
- #6529 

## Additional Data

Then I tried to package my node modules in a `nodejs` folder as per these [instructions](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path) and used the package artifact key instead of the more explicit way of adding layers that I included above:

```
layers:
  graphql:
    package:
      artifact: graphql_node_modules.zip
  authorizer:
    package:
      artifact: authorizer_node_modules.zip
```

This, to my surprise, actually worked.

- **_Serverless Framework Version you're using_**: 
```
Framework Core: 1.52.2
Plugin: 3.0.0
SDK: 2.1.1
```
- **_Operating System_**: Mojave 10.14.6
- **_Stack Trace_**:
- **_Provider Error messages_**:

**Comment by chintanvyas360** [comment]
Many others and I also facing the same issue.
This took me here: https://stackoverflow.com/questions/55539223/serverless-lambda-layers-cannot-find-module-request

package artifact works for me too.

**Comment by Pranjal631** [comment]
[index.js.zip](https://github.com/serverless/serverless/files/3957758/index.js.zip)

**Comment by gruckionvit** [comment]
Getting the same issue, but I am not using serverless

**Comment by sators** [comment]
I spent a while troubleshooting this in our environment - turns out we had a .gitignore file that was including `node-modules` that was in the `nodejs` folder, thus apparently telling Lambda/Layers to ignore the `node_modules` folder...removing the `.gitignore` file from the lambda layer .zip file resolves the missing dependency error on our side...

**Comment by xenowits** [comment]
I am using amplify for adding lambda layer. I got this issue. It solved it by updating the latest layer version manually in the lambda.

**Comment by prabhjeet6** [comment]
@codeinaire  does that mean, i need to create a zip for each individual dependency

**Comment by johnEthicalTechnology** [comment]
@prabhjeet6 this was a while ago but from the looks of my original post you need to create a zip of the `node_modules` folder for each lambda function that you are using in `serverless.yml` and include it as per this bit of code:
```
layers:
  graphql:
    package:
      artifact: graphql_node_modules.zip
  authorizer:
    package:
      artifact: authorizer_node_modules.zip
```
