### ISSUE TITLE
Unable to deploy single lambda function for version  1.52.1 

### ISSUE THREAD

**Issue by mahi1518** [serverless/serverless#6752]
### sls deploy -f "function_name" is not working throwing and exception 
My serverless version is:
Framework Core: 1.52.1
Plugin: 3.0.0
SDK: 2.1.1
`sls deploy -f function_name` is not working 
it throws and errors the complete trackback would be
`TypeError: Cannot read property 'artifact' of undefined
      at ServerlessPythonRequirements.BbPromise.bind.then.then.then (/home/mahesh/shuttle/H2OLambda/pythonh20lambda/node_modules/serverless-python-requirements/index.js:176:48)
`

Any update on this would be appreciated.
Thank you

**Comment by pmuens** [comment]
Hey @mahi1518 can you please post your `serverless.yml` file? Does that file contain a `function_name` function?

**Comment by jusmari** [comment]
I'm getting exactly this same error while trying to deploy single function with `sls deploy -f function_name`. I Have not touched my `serverless.yml` after updating serverless to 
```
Framework Core: 1.52.2
Plugin: 3.0.0
SDK: 2.1.1
```
Tried to reinstall everything but the issue continues to exist.

**Comment by babu-upcomer** [comment]
Same here. It just stopped working so. 

```
Framework Core: 1.53.0
Plugin: 3.1.0
SDK: 2.1.1
Components Core: 1.0.0
Components CLI: 1.2.3
```

**Comment by AkhilRaja** [comment]
Same here. I am also unable to deploy a single function.

**Comment by mahi1518** [comment]
@pmuens 
`service: AWSSERVERLESS`
`provider:`
  `name: aws`
  `runtime: python2.7`
  `profile: *********`
  `memorySize: 1024`
  `timeout: 300`
  `versionFunctions: false`
`stage: TEST`
  `region: ap-southeast-1`
  `role: arn:aws:iam::*********:role/lambda_basic_execution`
`functions:`
  `CheckWalletBlns:`
   ` handler: Handler/CheckWalletBlns.CheckCreditBlnprocesss`
   ` name: CheckWalletBlns`
`plugins:`
 ` - serverless-python-requirements`
`custom:`
  `pythonRequirements:`
    `dockerizePip: non-linux`
`package:`
  `exclude:`
 ` - .env/**`
  `- .idea/**`
  `- .gitignore`
 ` - node_modules/**`
 ` - Backup/**`
  `excludeDevDependencies: false`
My os is Ubuntu  18.04.5 LTS

**Comment by FatalTouch** [comment]
same issue, had to rollback to version 1.51.0 to upload a single function.

**Comment by NSpehler** [comment]
Same here ☝️

**Comment by Westermann** [comment]
✋Same

**Comment by AikawaKai** [comment]
Same problem here

**Comment by roberto-d** [comment]
1.54.0 the problem is still here.

**Comment by geoffbp** [comment]
Also seeing the same problem

**Comment by AikawaKai** [comment]
As provisional solution I am using the --false flag

`sls deploy -s dev --false`

**Comment by whobutsb** [comment]
@AikawaKai what does the `--false` flag do?

**Comment by AikawaKai** [comment]
> @AikawaKai what does the `--false` flag do?

One of my colleague suggested me this solution, but I am not sure of the flag meaning. I searched but there is no info on serverless. What I know is that when I do the deploy with this flag and I have local modifies it overwrite my lambdas with the new versions

**Comment by franklintw** [comment]
Same problem here

**Comment by Maheshkumar094** [comment]
One the solution I found is to downgrade it to version 
Framework Core: 1.51.0
Plugin: 1.3.11
SDK: 2.1.2
1. npm uninstall -g serverless
2. npm install -g serverless@1.51.0

**Comment by matteomorelli** [comment]
Issue seems to be present even in version 1.55.1
```
Node Version:              10.13.0
Framework Version:         1.55.1
Plugin Version:            3.2.0
SDK Version:               2.1.2
Components Core Version:   1.1.2
Components CLI Version:    1.4.0
```

This issue appear only trying to deploy a single function:
sls deploy -f function_name -s stage_name 
```
Serverless: Excluding development dependencies...
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'artifact' of undefined
```
If I deploy all the services it works: sls deploy -s stage_name
Use of --false flag does not help in my case.

**Comment by drexler** [comment]
@matteomorelli mind posting your `serverless.yml` file?

**Comment by matteomorelli** [comment]
> @matteomorelli mind posting your `serverless.yml` file?

Sure.
@drexler this is an excerpt, I hope can help:

```
frameworkVersion: ">=1.3.0 <2.0.0"

service: my-service

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-iam-roles-per-function

custom:
  pythonRequirements:
    dockerizePip: true
  defTimeout: 30
  # Custom configuration file
  config: ${file(./conf/${self:provider.stage}.yml)}
  # Prerequisite serverless-domain-manager
  customDomain:
    domainName: ${self:custom.config.domain.url}
    basePath: “seviceprefix” # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.config.domain.enabled}
    certificateName: “*.service.com”
  # This bucket should be in main cloudformation file
  docBucketName: ${self:custom.config.buckets.doc}
  # SNS topic name for contract template build
  snsDocumentBuild: ${self:custom.config.snsTopic.pubDocTemp}-${self:provider.stage}

provider:
  name: aws
  runtime: python2.7
  logRetentionInDays: 7
  stage: ${opt:stage, 'local'} # If no --stage flag is provided, local is used
  region: ${self:custom.config.aws.region}
  profile: ${self:custom.config.aws.profile} # The default profile to use with this service
  memorySize: 256 # Overwrite the default memory size. Default is 1024

  iamRoleStatements:
    # AWSLambdaVPCAccessExecutionRole
    - Effect: Allow
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource:
        - "*"

  vpc:
    securityGroupIds:
      - ${self:custom.config.vpc.sgId}
    subnetIds:
      - ${self:custom.config.vpc.subnetIdA}
      - ${self:custom.config.vpc.subnetIdB}
      - ${self:custom.config.vpc.subnetIdB}

package:
  exclude:
    - node_modules/**
    - json/mock/**
    - conf/**

functions:
  # API clients resource collection
  # Resource collection - my-service
  idTasks:
    handler: handler.id_tasks
    timeout: ${self:custom.defTimeout}
    events:
      - http:
          path: /{id}/tasks
          method: any
          cors: true
          private: true

```

**Comment by ygrosu** [comment]
same here: 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.11.1
     Framework Version:         1.54.0
     Plugin Version:            3.1.2
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

Sadly --false

**Comment by jkinred** [comment]
From those posting config snippets so far, this is likely an issue in the `serverless-python-requirements` plugin.

There is an issue open in that project tracking this:
https://github.com/UnitedIncome/serverless-python-requirements/issues/414

Unless anyone is experiencing this issue is **not** using `serverless-python-requirements` it probably makes sense to track it over there.

**Comment by satejsarker** [comment]
new update 1.57.0 did not solve the problem , still have to downgrade it for resolving this issue 


    1 npm uninstall -g serverless
   2  npm install -g serverless@1.51.0
@ Maheshkumar094 thanks for the solution

**Comment by lesichkovm** [comment]
Same issue happening with PHP functions.

 TypeError: Cannot read property 'artifact' of undefined
      at Php.getArtifactPath (/node_modules/serverless-openwhisk/compile/functions/runtimes/base.js:99:30)
      at Php.getArtifactZip (/node_modules/serverless-openwhisk/compile/functions/runtimes/base.js:92:31)
      at Php.generateActionPackage (/node_modules/serverless-openwhisk/compile/functions/runtimes/base.js:83:17)

**Comment by dtenenba** [comment]
If this **is** an issue with `serverless-python-requirements` it is one that has some dependencies/interactions with serverless itself, in that it is fixed by installing an earlier version of serverless (as described by @satejsarker ) and then reinstalling `serverless-python-requirements`. 

The fact that it seems to happen with PHP functions as well (see above comment) suggests this is not solely an issue with `serverless-python-requirements`.

**Comment by lesichkovm** [comment]
Definitely not a Python only issue.

**Comment by nexeh** [comment]
Same issue here. python.

**Comment by arashilmg** [comment]
Same issue here  on version 1.60, for me only happens on the `serverless-python-requirements` plugin

     Framework Version:         1.60.1
     Plugin Version:            3.2.6
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

**Comment by riyadparvez** [comment]
Same issue with `serverless-python-requirements`.

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Framework Version:         1.60.5
     Plugin Version:            3.2.7
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

**Comment by victoraldir** [comment]
Facing the same problem with python. I am also using `serverless-python-requirements`

```
Framework Core: 1.61.3
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by meteabogdan** [comment]
Same issue here using python

**Comment by harnit-bakshi** [comment]
Same issue as well

**Comment by ovunccetin** [comment]
I found a workaround but I'm not sure about the side effects.

The problem is the following line (line # 176 in my version) in _serverless-python-requirements/index.js_ file: 

```
arguments[1].functionObj && 
    arguments[1].functionObj.package.artifact.
```
It simply assumes the existence of package.artifact path in your function definition in serverless.yml.

As a work around I added "package: artifact: " to my function as follows and it worked:

```
post-apu-events:
    handler: hello.handler
    package:
      artifact:
    events:
      - http:
          path: hello
          method: get
```

**Comment by mgolfieri** [comment]
ovunccetin's workaround works great, so far no drawbacks.

**Comment by lephuongbg** [comment]
@ovunccetin Your workaround can be shorten to just:

```yaml
hello:
    # ...
    package: {}
```

**Comment by billydh** [comment]
@ovunccetin and @lephuongbg  confirming your workaround also works for serverless `1.65.0`.

**Comment by jimpudar** [comment]
As mentioned by @jkinred, this is not a problem with serverless, it's in the serverless-python-requirements plugin.

There is an open PR in that repository (https://github.com/UnitedIncome/serverless-python-requirements/pull/490) which fixes the underlying issue

This issue should be closed here.

**Comment by yehonadav** [comment]
same issue here
im running on windows 10
trying to deploy single python - flask function

my system:
     Operating System:           win32
     Node Version:                  12.13.0
     Framework Version:         1.78.1
     Plugin Version:                  3.7.0
     SDK Version:                      2.3.1
     Components Version:        2.33.4

my serverless plugins:
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline

**Comment by rib** [comment]
I've had a similar issue for a while now, and hoped it would get resolved in a newer version of the serverless framework but I guess now that it's a more esoteric error that few people are hitting for some reason...

This is how it's failing for me

```bash
Serverless: Invoke package:function
Serverless: Packaging function: workoutdb...

  Error --------------------------------------------------

  Error: ENOENT: no such file or directory, open '/home/rib/src/realfit-rest-apis/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip'
      at Object.openSync (fs.js:443:3)
      at Object.readFileSync (fs.js:343:35)
      at AwsDeployFunction.deployFunction (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:229:21)
      at AwsDeployFunction.BbPromise.bind.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:36:27)
  From previous event:
      at Object.deploy:function:deploy [as hook] (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/aws/deployFunction/index.js:34:12)
  From previous event:
      at PluginManager.invoke (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at PluginManager.spawn (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:518:17)
      at BbPromise.try (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/deploy/deploy.js:112:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/plugins/deploy/deploy.js:102:22)
      at BbPromise.reduce (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:498:55)
  From previous event:
      at PluginManager.invoke (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at getHooks.reduce.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:533:24)
  From previous event:
      at PluginManager.run (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/classes/PluginManager.js:533:8)
      at variables.populateService.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/Serverless.js:162:33)
  From previous event:
      at Serverless.run (/home/rib/src/realfit-rest-apis/node_modules/serverless/lib/Serverless.js:149:74)
      at serverless.init.then.then (/home/rib/src/realfit-rest-apis/node_modules/serverless/scripts/serverless.js:58:26)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/home/rib/src/realfit-rest-apis/node_modules/serverless/scripts/serverless.js:58:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.<anonymous> (/home/rib/src/realfit-rest-apis/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at findNodeScript.then.existing (/home/rib/.node_modules/lib/node_modules/npx/node_modules/libnpx/index.js:268:14)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.21.0
     Framework Version:         1.83.0 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

my serverless plugins:
plugins:
  - serverless-rust
  - serverless-domain-manager

There is clearly something up with how the path for this file is built:

`/home/rib/src/realfit-rest-apis/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip` since it contains a duplication of the `/home/rib/src/realfit-rest-apis` path


This is the relvant code in `plugins/aws/deployFunction/index.js` getting the path, right before the failure:
```javascript
deployFunction() {
    const artifactFileName = this.provider.naming.getFunctionArtifactName(this.options.function);
    let artifactFilePath =
      this.serverless.service.package.artifact || path.join(this.packagePath, artifactFileName);

    // check if an artifact is used in function package level
    const functionObject = this.serverless.service.getFunction(this.options.function);
    if (_.get(functionObject, 'package.artifact')) {
      artifactFilePath = functionObject.package.artifact;
      console.log("Test: " + artifactFilePath); // DEBUG
    }

    const data = fs.readFileSync(artifactFilePath);
```

And with the above debugging I see the path comes from this `_.get(functionObject, 'package.artifact')` case.

This sounds related to @ovunccetin's workaround above except I'm not using the `serverless-python-requirements` plugin as far as i know (can it be pulled in as a dependency somehow?)

Checking in `serverless-rust/index.js` I see:
```javascript
      // If all went well, we should now have find a packaged compiled binary under `target/lambda/release`.
      //
      // The AWS "provided" lambda runtime requires executables to be named
      // "bootstrap" -- https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html
      //
      // To avoid artifact naming conflicts when we potentially have more than one function
      // we leverage the ability to declare a package artifact directly
      // see https://serverless.com/framework/docs/providers/aws/guide/packaging/
      // for more information
      const artifactPath = path.join(
        this.srcPath,
        `target/lambda/${"dev" === profile ? "debug" : "release"}`,
        `${binary}.zip`
      );
      console.log("AP: " + artifactPath); // DEBUG
      func.package = func.package || {};
      func.package.artifact = artifactPath;
```

And can see that `serverless-rust` is setting an absolute path to the artifact which seems a bit risky, since I can easily imagine other parts of serverless might be expecting that to be a relative path and that's how I probably get the error above.

Blindly grepping I found this in `lib/plugins/package/lib/packageService.js`

```javascript
packageFunction(functionName) {
    const functionObject = this.serverless.service.getFunction(functionName);
    const funcPackageConfig = functionObject.package || {};

    // use the artifact in function config if provided
    if (funcPackageConfig.artifact) {
      const filePath = path.join(this.serverless.config.servicePath, funcPackageConfig.artifact);
      console.log("filePath: join(" + this.serverless.config.servicePath + "," + funcPackageConfig.artifact + ")" ); // DEBUG
      functionObject.package.artifact = filePath;
      return BbPromise.resolve(filePath);
    }
```
And see that filePath is made from joining `/home/rib/src/realfit-rest-apis` and `/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip`, resulting in `/home/rib/src/realfit-rest-apis/home/rib/src/realfit-rest-apis/target/lambda/release/workoutdb.zip`

So although serverless-rust could potentially be changed to set a relative artifact path, I guess the fix in this case is that `packageFunction` should consider the possibility that the artifact path is already an absolute path and in that case it shouldn't concatenate with the servicePath.

Using this code instead:
```javascript
    // use the artifact in function config if provided
    if (funcPackageConfig.artifact) {
      const filePath = path.isAbsolute(funcPackageConfig.artifact) ?
            funcPackageConfig.artifact :
            path.join(this.serverless.config.servicePath, funcPackageConfig.artifact);
      console.log("filePath: join(" + this.serverless.config.servicePath + "," + funcPackageConfig.artifact + ")" );
      functionObject.package.artifact = filePath;
      return BbPromise.resolve(filePath);
    }
```

fixed the issue for me and let me deploy a single function again - yay!

Okey, so I wasn't originally planning to follow the trail through to a conclusion, but hopefully that helps resolve the same issue for a few others too. I guess this is actually a slightly different variation of the problem people are seeing come from `serverless-python-requirements`

**Comment by rib** [comment]
I wonder if the title for this issue can maybe be updated to reflect the `serverless-python-requirements` specific nature of this issue. 

I was given feedback on my PR that it wasn't related to this issue, even though (from my pov) I was also "Unable to deploy a single lambda function" and my issue was also _similarly_ related to package artifacts.

**Comment by cscetbon** [comment]
It's been a year and this issue is still there, really annoying ... thank you @ovunccetin for your workaround .

**Comment by bitsofinfo** [comment]
experiencing the same.

**Comment by jinpeng0102** [comment]
```
functions:
  handler:
    handler: functions/handler.handler
    package: {} # This fixes the issue.
    events:
      - http:
          path: /map
          method: post
          cors: true
```
