### ISSUE TITLE
Cannot cross-stack refer Websocket API

### ISSUE THREAD

**Issue by nathalieDOXA** [serverless/serverless#6762]
# Bug Report

## Description

1. What did you do? 
I created Websocket API by AWS Cloud formation 
```
Resources:
    NotificationWebSocketApi:
    Type: "AWS::ApiGatewayV2::Api"
    Properties:
      Name: !Sub "notification-websocket-api-${EnvName}"
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      Description: "Notification Websocket API gateway"
Outputs:
  NotificationWebsocketApiID:
     Description: The ID of the Notification REST AGW
     Value: !Ref NotificationWebSocketApi
     Export:
      Name: !Sub "${AWS::StackName}-NotificationWebsocketApiID-${EnvName}"
  NotificationWebsocketEndpoint:
    Description: "API endpoint"
    Value: !Sub "wss://${NotificationWebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvName}"
```
Then I refer it in my serverless service:
```
service: notification-ws
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: ap-southeast-1
  apiGateway:
    websocketApiId: ${cf:${self:custom.apigateway_stack}.NotificationWebsocketApiID}
functions:
  connectionHandler:
    name: notification-connectionHandler-${self:provider.stage}
    handler: handler.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
```

2. What happened?
Serverless doesn't use the websocketApiId cross-stack reference.
Serverless created a new end-point.
```
Service Information
service: notification-ws
stage: stag
region: ap-southeast-1
stack: notification-ws-stag
resources: 24
api keys:
  None
endpoints:
  wss://mc3vnd8g9h.execute-api.ap-southeast-1.amazonaws.com/stag
functions:
  connectionHandler: notification-connectionHandler-stag
  defaultHandler: notification-defaultHandler-stag
  sendMessageHandler: notification-sendMessageHandler-stag
layers:
  None
Serverless Enterprise: Run `serverless login` and deploy again to explore, monitor, secure your serverless project for free.
```
3. What should've happened?
Serverless should use the cross-stack reference Websocket endpoint instead of creating a new one.

Please help me with this case.

Thanks in advance,
Nathalie

**Comment by pmuens** [comment]
Hey @nathalieDOXA thanks for opening :+1:

In your `notification-ws` service can you run `serverless print` and print it here so that we see the fully resolved `serveless.yml` file? Is the `websocketApiId` successfully resolved?

**Comment by nathalieDOXA** [comment]
Hi @pmuens ,
Thanks for your quick response.

Here it is:

`serverless print`
```
service: notification-ws
custom:
  aws_account_id: xxxxxxxxxxxxx
  apigateway_stack: APIStack-stag
  logRetentionInDays: 30
provider:
  stage: stag
  region: ap-southeast-1
  name: aws
  runtime: nodejs8.10
  role: 'arn:aws:iam::631568474454:role/lambda-basic-execution'
  apiGateway:
    websocketApiId: 2nw848x85c
  websocketsApiRouteSelectionExpression: $request.body.action
  environment:
    stage: stag
  logRetentionInDays: 30
functions:
  connectionHandler:
    name: notification-connectionHandler-stag
    handler: handler.connectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultHandler:
    name: notification-defaultHandler-stag
    handler: handler.defaultHandler
    events:
      - websocket:
          route: $default
  sendMessageHandler:
    name: notification-sendMessageHandler-stag
    handler: handler.sendMessageHandler
    events:
      - websocket:
          route: sendMessage
resources:
  Resources:
    ChatTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: appUserId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
          - AttributeName: appUserId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: notification-stag
```
`serverless deploy` (the endpoint changes comparing to my previous post because I removed the service and deploy again)
```
Service Information
service: notification-ws
stage: stag
region: ap-southeast-1
stack: notification-ws-stag
resources: 24
api keys:
  None
endpoints:
  wss://po3mb9ubwd.execute-api.ap-southeast-1.amazonaws.com/stag
functions:
  connectionHandler: notification-connectionHandler-stag
  defaultHandler: notification-defaultHandler-stag
  sendMessageHandler: notification-sendMessageHandler-stag
layers:
  None
Serverless: Removing old service artifacts from S3...
Serverless Enterprise: Run `serverless login` and deploy again to explore, monitor, secure your serverless project for free.
```
