### ISSUE TITLE
Cron job params inaccessible

### ISSUE THREAD

**Issue by dutzi** [serverless/serverless#6765]
# Bug Report

## Description

When adding:

```
          input:
            key1: value1
            key2: value2
```

To my serverless.yml, the Lambda's `event` (first param passed to handler) object is undefined. So I can't access the values.

**serverless.yml**
```
plugins:
  - serverless-plugin-package-json

service: scraper
app: untitled-project
org: dutzi

provider:
  name: aws
  runtime: nodejs10.x

custom:
  enterprise:
    collectLambdaLogs: false

functions:
  scrape:
    name: scrape
    description: "Version: ${pkgjson:version}"
    handler: handler.scrape
    timeout: 900
    events:
      - schedule:
          rate: cron(0 5 * * ? *)
          input:
            key1: value1
            key2: value2
      - http:
          method: get
          path: scrape
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    environment:
      NODE_ENV: production
      BROWSERLESS_API_KEY: ${env:BROWSERLESS_API_KEY}
      SENDGRID_API_KEY: ${env:SENDGRID_API_KEY}
      VERSION: ${pkgjson:version}
```
