### ISSUE TITLE
Lambda layer versions are not being retained

### ISSUE THREAD

**Issue by cheslip** [serverless/serverless#6769]
# Bug Report

## Description

1. What did you do?
Deployed a layer-only service with `retain: true`
1. What happened?
Previous layer version is deleted
1. What should've happened?
Since `retain` is set to `true`, the previous layer version should still be available
1. What's the content of your `serverless.yml` file?
```
service: config-layer
provider:
  name: aws
  profile: personal
layers:
  config:
    path: ./
    retain: true
    compatibleRuntimes:
      - nodejs10.x
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
[debug.txt](https://github.com/serverless/serverless/files/3667804/debug.txt)

Similar or dependent issues:

- #6010
- #6532 

In PR #6545, S3 key was removed from the sha hash, which results in the same logical id with every deployment. I believe cloudformation removes versions with the same logical id, regardless of `DeletionPolicy: Retain` being set.

**Comment by danielstandby** [comment]
Any news on this one?

**Comment by mregnauld** [comment]
Will there be any fix soon?

**Comment by palafoxernesto** [comment]
I'm interested too, what are next steps on this?

**Comment by Jltp1972** [comment]
Very interested as well. Would like to use Layers for common dependencies, but need versions working to avoid breaking changes when dependencies are updated.

**Comment by besi5190** [comment]
I'm interested too. Any news on this?

**Comment by snaggled** [comment]
+1

**Comment by daneholmberg** [comment]
+1

**Comment by quanght55** [comment]
Any news on this? :(

**Comment by mrn3** [comment]
I am fairly new to using layers in serverless.  I am quite surprised that this bug still exists.  In particular, we have issues when we deploy our lambdas (using Atlassian Bamboo as our CI/CD) which depend on layers in another Cloudformation stack (centralized), and then we need to roll back the release.  Since the lambda layers are not being retained, the rollback fails.  

I have seen the workaround of going back to serverless 1.43.0, but I am currently on 1.60.4, so I am worried about the impact of reverting back to a version that was ages ago.

**Comment by mschwerdtfeger** [comment]
+1

**Comment by throrin19** [comment]
I confirm, the `retain` option does not works. I really need it in order to add layer management in my CI without breaking my lambdas running in the old version

**Comment by mfogel** [comment]
There's a work-around for this posted [here](https://github.com/UnitedIncome/serverless-python-requirements/issues/403#issuecomment-538428191) for python-based layers

**Comment by Enase** [comment]
@mfogel As I understand it for python only. do you know any solution for nodejs?

**Comment by mfogel** [comment]
@Enase nope, sorry

**Comment by throrin19** [comment]
After tests, the retain option works fine in version 1.43.0

**Comment by SeaGuy** [comment]
+1 for nodejs

**Comment by daninfpj** [comment]
@mfogel’s suggested solution works. The example he links to is specific to when you’re using `serverless-python-requirements`, but the same thing can be applied to any layer.

So in this case:

```yaml
layers:
  config:
    …

resources:
  Resources:
    ConfigLambdaLayer:
      UpdateReplacePolicy: Retain
```

That will add the `"UpdateReplacePolicy": "Retain"` to you LambdaLayer resource in CF.

However, **you need to remove the `retain: true`** option from the lambda definition, otherwise the resource name will include a hash (`ConfigLambdaLayer45fc268c545bc3fbbeb97170ca79de7a4721daeb`) and the `UpdateReplacePolicy` will apply to a different, empty resource `ConfigLambdaLayer`.

That should work for node as well. (@Enase, @SeaGuy)

**Comment by RenatoFranze** [comment]
@daninfpj , I tried your solution but I got this error when trying to deploy the layer:

`Error: The CloudFormation template is invalid: Template format error: Every Resources object must contain a Type member`

So, any workaround for nodejs besides downgrade to 1.43.0 version?

**Comment by daninfpj** [comment]
> The CloudFormation template is invalid: Template format error: Every Resources object must contain a Type member

@RenatoFranze I think that error is unrelated to this specific issue. It’s telling you that you need to define a type for your resource.

In the example I posted, I don’t do that explicitly because the layer definition already does it, but I’m not sure if you’re doing that or if you’re referring correctly to your layer. In the example, a `config` entry in the `layers` key generates a `ConfigLambdaLayer` resource.

**Comment by RenatoFranze** [comment]
Indeed, @daninfpj , it was my mistake with the resource name Thank you very much!

**Comment by DeekshaPandit** [comment]
@RenatoFranze , Did any solution work for you? I am using nodejs and using the following template.

serverless.yml:

service: my-common-layer
provider:
 name: aws
 runtime: nodejs10.x
layers:
 MyCommonLayer:
   path: nodejs
   description: "base common layer which contains common-node and common-mongo"
   retain: true

and this does not work for me. Help?

**Comment by RenatoFranze** [comment]
Hi @DeekshaPandit ,

The solution suggested by mfogel and daninfpj worked for me. 

Template:

```
service: "anything you want"

provider:
  name: aws
  region: ${opt:region, 'us-east-1'} 
  stage: ${opt:stage, 'dev'}

layers:
  namelayer:
    path: modules
    name: "anything you want"
    description: "Your description"
    retain: false

resources:
  Resources:
    NameLayerLambdaLayer:
      UpdateReplacePolicy: Retain
```

**Comment by DeekshaPandit** [comment]
@RenatoFranze ,
what should I put for this key NameLayerLambdaLayer:? I am new to AWS.little confused

**Comment by RenatoFranze** [comment]
If you name your layer like 'aaaa', in here:

```
layers:
  aaaa:
```

You should use 'Aaaa' in the resource name:

```
resources:
  Resources:
    AaaaLambdaLayer:
      UpdateReplacePolicy: Retain
```

**Comment by DeekshaPandit** [comment]
@RenatoFranze ,

service: xx-common-layer
provider:
  name: aws
layers:
  XXCommonLayer:
    path: nodejs  
    description: Common layer for all lambdas
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs10.x
    retain: false

resources:
  Resources:
    XXCommonLayer:
      UpdateReplacePolicy: Retain

getting this error: 

  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: Template format error: Every Resources object must contain a Type member.


Seems like we have to define this template another way. Or did I miss something? Do I need to specify Type explicitly here?

**Comment by RenatoFranze** [comment]
@DeekshaPandit , you missed the 'LambdaLayer' part in 'XXCommonLayer' resource name:

```
resources:
  Resources:
    XXCommonLayerLambdaLayer:
      UpdateReplacePolicy: Retain
```
