### ISSUE TITLE
Cognito user pool not updating on deploy

### ISSUE THREAD

**Issue by xShirase** [serverless/serverless#6772]
# Bug Report

## Description
Deploy creates invisible Cognito resources instead of updating existing ones

### What did you do?

The user pool exists already with an id of `eu_west-2_xxxxx`. I sls deployed to attach the trigger to it

### What happened?

The trigger isn't updated, and worryingly, CloudFormation shows a CognitoUserPool resource being created, with a new id of ` eu-west-2_yyyyy`. This pool does not show as a duplicate in Cognito, it doesn't show up at all. The trigger on the original pool is not updated, but the stack deploy is all green.

### What should've happened?
It should have updated the trigger on the existing pool or thrown some sort of dupe error

### What's the content of your `serverless.yml` file?

serverless.yml
```
    Resources:
        CognitoUserPoolTestUserPool:
            Type: AWS::Cognito::UserPool
            Properties:
                UserPoolName: testuserpool
functions:
    # cognito
    preTokenGeneration:
        handler: src/handlers/cognito/preTokenGeneration.handler
        events:
            - cognitoUserPool:
                pool: TestUserPool  
                trigger: PreTokenGeneration
```

### What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Nothing of note, no errors or warnings

Similar or dependent issues:

- #5282
