### ISSUE TITLE
Removing a lambda with an S3 trigger event causes deployment to fail

### ISSUE THREAD

**Issue by zkrige** [serverless/serverless#6778]
# Bug Report

## Description

1. What did you do?
I removed a lambda from my serverless.yml file. the lambda looked like this
```
lambdaFunction:
  handler: src/handlers/s3/event.handler
  description: imports data from .json file
  timeout: 30
  memorySize: 256
  events:
    - s3:
        bucket: ${self:custom.resources.PRIMARY_BUCKET}
        existing: true
        event: s3:ObjectCreated:*
        rules:
          - prefix: import/
```
2. What happened?
the deploy cannot remove permissions on the removed lambda, which causes a rollback

1. What should've happened?
the deploy should successfully remove the permissions on the lambda

1. What's the content of your `serverless.yml` file?
as above

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

I've done some digging, and come to the conclusion that the custom lambda serverless creates (CustomDashresourceDashexistingDashs3LambdaFunction) to manage permissions no longer has context of the removed lambda, so it is not included in its permissions. 

If I view the policy summary for the serverless custom lambda, it only has my new s3 lambdas in its policy, not the old ones, so it is unable to delete the old ones

If I manually log in to console and change the role to one that has removepermission access across all lambdas, then it works fine
