### ISSUE TITLE
The always restApi logs enable when using an SSM parameter in the configuration.

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [serverless/serverless#6782]
# Bug Report

## Description

1. What did you do?

I enable logs depending on the stage using SSM parameters.

1. What happened?

The API Gateway logs enable for every stage. The SSM values for `dev` and `test` stages were `false`, and `staging` and `prod` were `true`.

1. What should've happened?

API Gateway logs should have been disabled for `dev` and `test`, and enabled for `staging` and `prod`.

1. What's the content of your `serverless.yml` file?

```yaml
provider:
  logs:
    restApi:
      accessLogging:     ${ssm:/${self:provider.env}/API_GW_LOGS}
      executionLogging:  ${ssm:/${self:provider.env}/API_GW_LOGS}
      fullExecutionData: ${ssm:/${self:provider.env}/API_GW_LOGS}
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Not captured.

Similar or dependent issues:

- #12345

**Comment by exoego** [comment]
There are lots of non-string configuration (boolean or numeric) in severless framework, and most of them does not treat string given from `$opt` unfortunately.
It is recommended to use `$file` variable and use booleans/numbers in those files.
https://github.com/serverless/serverless/pull/6561#issuecomment-523006447

This was discussed in https://github.com/serverless/serverless/pull/6561

**Comment by medikoo** [comment]
Thanks @miguel-a-calles-mba for report.

For resources like `process.env` where value can only be a string (or not be set at at all). I believe the best convention to express booleans is to use var names as `ENABLE_*` or `DISABLE_*`, and resolve _boolean_ result basing on var existence (an empty string also may indicate _falsy_ value).

In JavaScript `Boolean("false") === true`, and I believe in it's best to stick to that characteristics when parsing YAML. Otherwise we may end with some nasty side effects.

**Comment by miguel-a-calles-mba** [comment]
> Thanks @miguel-a-calles-mba for report.
> 
> For resources like `process.env` where value can only be a string (or not be set at at all). I believe the best convention to express booleans is to use var names as `ENABLE_*` or `DISABLE_*`, and resolve _boolean_ result basing on var existence (an empty string also may indicate _falsy_ value).
> 
> In JavaScript `Boolean("false") === true`, and I believe in it's best to stick to that characteristics when parsing YAML. Otherwise we may end with some nasty side effects.

Would this type of change help with the overall problem?
https://github.com/serverless/serverless/pull/6787
It passed unit tests.
I'm testing the `sls deploy` in my development environment.

**Comment by medikoo** [comment]
>Would this type of change help with the overall problem?

I'm not sure if it's not a good idea to translate `"false"` to `false`. To avoid confusion and unwanted side effects we should rather follow how coercion in JS language works.

Anyway, let's focus exactly on your problem:
- Is _string_ the only possible value type of SSM parameter? (is there no way to store booleans or numbers?) 
- If it's the case, can you make a `API_GW_LOGS` an empty string (`''`) when you're after `false` and e.g. (`'1'`) when you're after truthy value?

**Comment by miguel-a-calles-mba** [comment]
> * Is _string_ the only possible value type of SSM parameter? (is there no way to store booleans or numbers?)
Correct. It only returns strings.
> * If it's the case, can you make a `API_GW_LOGS` an empty string (`''`) when you're after `false` and e.g. (`'1'`) when you're after truthy value?
Thanks. I'll give it a try, but I don't think SSM allows empty strings.

**Comment by medikoo** [comment]
> Thanks. I'll give it a try, but I don't think SSM allows empty strings.

Ok, let us know

**Comment by miguel-a-calles-mba** [comment]
SSM will not accept an empty string. I tried setting the SSM value as a single space string and a zero string to no avail.

**Comment by miguel-a-calles-mba** [comment]
I'm not fond of this workaround, but it works. Is there a cleaner way to do this?

```yaml
provider:
  logs:
    restApi:
      accessLogging:     ${self:custom.restApiLogs.${ssm:/${self:provider.env}/API_GW_LOGS}}
      executionLogging:  ${self:custom.restApiLogs.${ssm:/${self:provider.env}/API_GW_LOGS}}
      fullExecutionData: ${self:custom.restApiLogs.${ssm:/${self:provider.env}/API_GW_LOGS}}

custom:
  restApiLogs:
    true: true
    false: false
```

**Comment by miguel-a-calles-mba** [comment]
This is a little cleaner, but alternate suggestions are welcomed. Thanks.

```yaml
provider:
  logs:
    restApi:
      accessLogging:     ${self:custom.${ssm:/${self:provider.env}/API_GW_LOGS}}
      executionLogging:  ${self:custom.${ssm:/${self:provider.env}/API_GW_LOGS}}
      fullExecutionData: ${self:custom.${ssm:/${self:provider.env}/API_GW_LOGS}}

custom:
  true: true
  false: false
```

**Comment by medikoo** [comment]
Indeed I double checked, and the only available types are _string_ and _string list_.

Probably cleanest way to approach it then, is to depend on existence of a parametr, and set resolver as:

```yaml
accessLogging:  ${ssm:/${self:provider.env}/API_GW_LOGS, false}
```

If `API_GW_LOGS` exists, it'll resolve to truthy value, if it doesn't it'll be `false`.

Some other idea worth exploring could be to support some extra decorators in variable resolvers, through that we could mark the intention of converting string `'true'` and `'false'` to boolean as proposed in your PR. That may look as:

```yaml
accessLogging:  ${ssm:/${self:provider.env}/API_GW_LOGS|strToBool}
# or
accessLogging:  ${@strToBool(ssm:/${self:provider.env}/API_GW_LOGS)}
```

Still such feature will require an implementation which may not be that trivial (variables handling is already pretty complicated)
