### ISSUE TITLE
Error: Not Found: at Gaxios.request (node_modules/gaxios/src/gaxios.ts:86:15)

### ISSUE THREAD

**Issue by santi6291** [serverless/serverless#6820]
#Bug Report

Hello, This really weird issue happened, my configs to deploy to google cloud were working fine but then, I started getting the error below when I run `serversless deploy`

## Error output
```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "first"...
Serverless: Uploading artifacts...

  Error --------------------------------------------------

  Error: Not Found
      at Gaxios.request (node_modules/gaxios/src/gaxios.ts:86:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From previous event:
      at PluginManager.invoke (node_modules/serverless/lib/classes/PluginManager.js:505:22)
      at getHooks.reduce.then (node_modules/serverless/lib/classes/PluginManager.js:540:24)
  From previous event:
      at PluginManager.run (node_modules/serverless/lib/classes/PluginManager.js:540:8)
      at variables.populateService.then (node_modules/serverless/lib/Serverless.js:115:33)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Serverless.run (node_modules/serverless/lib/Serverless.js:102:74)
      at serverless.init.then (node_modules/serverless/bin/serverless.js:72:30)
      at node_modules/graceful-fs/graceful-fs.js:111:16
      at node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at node_modules/serverless-google-cloudfunctions/node_modules/graceful-fs/graceful-fs.js:57:14
      at node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  From previous event:
      at initializeErrorReporter.then (node_modules/serverless/bin/serverless.js:72:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (node_modules/serverless/bin/serverless.js:57:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.3
     Framework Version:         1.54.0
     Plugin Version:            3.1.2
     SDK Version:               2.1.2
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
```

## serverless.yml
```
service: my-service

provider:
  name: google
  stage: production
  runtime: nodejs10
  region: us-central1
  project: [PROJECT_ID]
  credentials: ~/.gcloud/keystore.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - .git/**
    - node_modules/**
    - src/**
    - coverage/**
    - test/**
    - .github/**
    - .vscode/**
    - .gitignore
    - .editorconfig
    - .env
    - .env.example
    - .eslintignore
    - .eslintrc
    - .gitignore
    - .travis.yml
    - README.md
    - jest.config.js
    - tsconfig.json

functions:
  first:
    handler: http
    events:
      - http: path

```

## package.json
```
{
    "engines": {
        "node": ">=10.16.0"
    },
    "main": "dist/handler.js",
    "dependencies": {
        "acorn": "^7.1.0",
        "async": "^3.1.0",
        "bluebird": "^3.5.5",
        "dotenv": "^8.1.0",
        "errorhandler": "^1.5.1",
        "express": "^4.17.1",
        "firebase-admin": "^8.6.0",
        "firebase-functions": "^3.3.0",
        "lusca": "^1.6.1",
        "request": "^2.88.0",
        "request-promise": "^4.2.4",
        "winston": "^3.2.1"
    },
    "devDependencies": {
        "@types/async": "^3.0.2",
        "@types/bluebird": "^3.5.27",
        "@types/chai": "^4.2.3",
        "@types/concurrently": "^4.1.0",
        "@types/dotenv": "^6.1.1",
        "@types/errorhandler": "^0.0.32",
        "@types/eslint": "^6.1.1",
        "@types/express": "^4.17.1",
        "@types/jest": "^24.0.18",
        "@types/lusca": "^1.6.1",
        "@types/node": "^12.7.8",
        "@types/request": "^2.48.3",
        "@types/request-promise": "^4.1.44",
        "@types/supertest": "^2.0.8",
        "@types/winston": "^2.4.4",
        "@typescript-eslint/eslint-plugin": "^2.3.1",
        "@typescript-eslint/parser": "^2.3.1",
        "chai": "^4.2.0",
        "concurrently": "^4.1.2",
        "eslint": "^6.4.0",
        "jest": "^24.9.0",
        "nodemon": "^1.19.2",
        "supertest": "^4.0.2",
        "ts-jest": "^24.1.0",
        "ts-node": "^8.4.1",
        "typescript": "^3.6.3",
        "serverless": "^1.54.0",
        "serverless-google-cloudfunctions": "^2.3.3"
    }
}

```

**Comment by santi6291** [comment]
More context, I found out this was do to serversless not creating the storage bucket and trying to upload the package. there should be a clearers error message but also very strange that it can't create the bucket when it was able to before

**Comment by martynfagg** [comment]
I'm seeing exactly the same behaviour on a new 'hello world' type function (very minimal).

How did you work around the issue @santi6291 ? I'm not sure what bucket I need to create? Thanks

**Comment by santi6291** [comment]
I changed the name of `service: my-service`, and it seemed to be able to create a bucket and function fine.

**Comment by martynfagg** [comment]
Thanks @santi6291. I had already changed it, but still quite a generic name. I think there must have been a clash with someone else's service/project but the error reporting didn't make this clear.

All good now.

**Comment by pmuens** [comment]
Hey @santi6291,
thanks for opening. I just tried to reproduce this problem today but (un)fortunately was not able to do so. Everything deployed fine on my end 🤔

Here's the config I've used:

```yaml
service: gtest

provider:
  name: google
  stage: dev
  runtime: nodejs8
  region: us-central1
  project: some-project
  credentials: ~/.gcloud/some-project.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
```

```json
{
  "name": "google",
  "version": "0.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "serverless.com",
  "license": "MIT",
  "devDependencies": {
    "serverless-google-cloudfunctions": "*"
  }
}
```

It might've something todo with your dependencies / project setup. Also note that the service name should not include `google` (there's a reference with taken names I cannot find ATM which forbids the usage of `google` and such).
