### ISSUE TITLE
How to set up Domain url field for AWS Cognito Resource on serverless.yaml

### ISSUE THREAD

**Issue by thierryx96** [serverless/serverless#6830]
Hi,

How can I set up the `Amazon Cognito domain` field in the `CognitoUserPoolClient` on `serverless.yaml`.

*Screenshot on AWS Console:*

![Capture](https://user-images.githubusercontent.com/4757194/66730540-c2f6c200-ee95-11e9-9b49-3d0d0c6d2dd9.PNG)

*Copy of my serverless.yaml:*

```
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:provider.stage}-xxx-userpool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:provider.stage}-xxx-userpool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false



```

Thanks a lot!

Thierry

**Comment by iaarnio** [comment]
I would also need possibility so set the domain. And callback and sign out URLs. All needed details for using e.g. https://github.com/aws/amazon-cognito-auth-js

**Comment by EHadoux** [comment]
Given that it's not closed yet, I'll give you the answer @thierryx96 (I imagine you know it already but for posterity and the sake of closing this issue). You need to use:
```
CognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    Domain: MYDOMAIN # what is before .auth.REGION.amazoncognito.com
    UserPoolId:
      Ref: CognitoUserPool # given the name of your resource
```
