### ISSUE TITLE
Unable to require (non-npm) external JS code (NodeJS/AWS)

### ISSUE THREAD

**Issue by Mixelated** [serverless/serverless#6832]
Followed some of the tutorials, while my npm packages are all working fine I can't seem to require my Models folder/custom files.

What I tried: 
```
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2

package:
  include:
    - ../models/'
  excludeDevDependencies: false


plugins:
  - serverless-plugin-include-dependencies

custom:
  includeDependencies:
    always: '../models/' 

functions:
  hello:
    handler: handler.hello
```

trying to require the User model like this:
`const User = require('../models/user')`
