### ISSUE TITLE
Support NotAction and NotResource

### ISSUE THREAD

**Issue by kabo** [serverless/serverless#6841]
# Feature Proposal

## Description

Currently Serverless refuses to build if there are iamRoleStatements that contain [`NotAction`](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notaction.html) or [`NotResource`](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notresource.html).

These should be supported, as they are valid IAM role statements.

e.g. to allow a lambda to send text messages, but not publish to any SNS topics
```yaml
      - Effect: 'Allow'
        Action: 'sns:Publish'
        NotResource: 'arn:aws:sns:*:*:*'
```
