### ISSUE TITLE
Provide Multi-CloudFront Distribution Support 

### ISSUE THREAD

**Issue by kling-appfire** [serverless/serverless#6843]
# Feature Proposal
Reconfigure to allow multiple CF distros to associate to the same Lambda@Edge.
Also, document the following properties for the event. All are very important:
memorySize
timeout
allowedHttpMethods - not sure it even exists but absolutely necessary. several behavior switches missing.

## Description

```
  otherEndpoint:
    name: an-other-api-endpoint
    handler: src/serv/other.example
    role: lambdaEdgeRole
    #not documented but needed, otherwise defaults 1048 and can't associate with CF behavior
    memorySize: 128 
    timeout: 4 #not documented either, otherwise defaults to 6 and cannot assoc with CF behavior
    package:
      include: 
        - src/serv/other.js
 events:
    - cloudFront: #should support a list of CF Distributions!!! Would be awesome.
         eventType: viewer-request
         pathPattern: /lifecycle*
         #allowedHttpMethods: //this isnt actually an attribute. just placing here to point out its missing
               - GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE
        origin:
           DomainName: lt51j3t-73zgem9.s3.amazonaws.com
             CustomOriginConfig:
               OriginProtocolPolicy: match-viewer
```

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Reconfigure to allow multiple CF distros to associate to the same Lambda@Edge. Many usecases where a single lambda would be assoicated to many CF distro path behaviors. Can't configure it. Have to write very lengthy, sophisticated aws-sdk to add them manually after deploy.
