### ISSUE TITLE
Ability to pick lambda version or aliases in api gateway configuration (function.name.events.http)

### ISSUE THREAD

**Issue by pavelkuchin** [serverless/serverless#6849]
# Feature Proposal

## Description

I think it would be useful to have ability to specify lambda version or aliases in api gateway configuration. As a use case consider situation when lambda have non backward compatible changes in request/response structure.

How about new attributes `version` and `alias` under functions.{name}.events.http, so it would look like this:
```
functions:
  execute:
    handler: src.execute_model.lambda_handler
    description: Execute model
    events:
      - http:
          path: /api/v1/model
          version: 1
          method: POST
      - http:
          path: /api/v2/model
          method: POST
```
