### ISSUE TITLE
Step function do not inherit global tags

### ISSUE THREAD

**Issue by psech** [serverless/serverless#6850]
# Bug Report

serverless@1.54.0

## Description

1. What did you do?
Provided `stackTags` under `provider` in serverless.yml. Like in [docs](https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/)
1. What happened?
My step function has not been tagged
1. What should've happened?
My step function should have been tagged according to [docs](https://serverless.com/plugins/serverless-step-functions/#tags)

> You can specify tags on each state machine. Additionally, any global tags (specified under provider section in your serverless.yml) would be merged in as well.

1. What's the content of your `serverless.yml` file?
```
provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'ap-southeast-2'}
  stage: ${opt:stage, 'dev'}
  stackTags:
    Description: "Serverless Build of service: ${self:service}"
    Service: "${self:service}"
    Branch: "${opt:branchId, 'manual'}"
    Build: "${opt:buildId, 'manual'}"
    Template: None
    Environment: "${opt:stage}"
    Team: QA
...
stepFunctions:
  stateMachines:
    calculateQualityScore:
      name: ${self:provider.environment.STATE_MACHNE_NAME}
      definition:
        Comment: "Calculates QualityScore"
        StartAt: FetchBugs
        States:
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Notging significant, normal deployment

Similar or dependent issues: N/A
