### ISSUE TITLE
Updating the API gateway integration without touching lambda function code 

### ISSUE THREAD

**Issue by ChanduReddy123** [serverless/serverless#6859]
Hello,

Is there any way to update the Lambda function integration without touching the code which is already deployed in the lambda function.

I want to update my function called user update 

**From** 
```
  userupdate:
    handler: users.update
    events:
      - http:
          path: /user/update
          method: post
```

**To**
```
  userupdate:
    handler: users.update
    events:
      - http:
          path: /user/update
          method: post
          request:
            parameters:
              querystrings:
                name: true
```

deploying the function with `serverless deploy function -f userupdate ` is trying to update the code but not checking the changes in the configuration file.

`serverless deploy` will work fine for my case but I don't want to touch the other resources.

Is there any way to do it.
