### ISSUE TITLE
Can't create two lambdas using the same eventBus

### ISSUE THREAD

**Issue by eduardonunesp** [serverless/serverless#6882]
# Bug Report

## Description

Create two lambda functions using the same eventBus on EventBridge service gives an error that eventBus cannot be created.

1. What did you do?
Try to create two lambda functions using the same event bus

1. What happened?
Gives an error failed to create resource already exists

1. What should've happened?
Create the two lambdas using the same eventBus

1. What's the content of your `serverless.yml` file?
```yaml
service: my-service

provider:
  name: aws
  stage: ${opt:stage}
  runtime: go1.x
  region: us-east-1

package:
  exclude:
  stage: ${opt:stage}
    - ./**
  include:
    - ./bin/**

functions:
  plans-create:
    handler: bin/eventbridge/plans/create
    events:
      - eventBridge:
          eventBus: mybus-${opt:stage}
          pattern:
            source:
            - prod.admin.plans
            detail-type:
            - plan-created

  plans-update:
    handler: bin/eventbridge/plans/update
    events:
      - eventBridge:
          eventBus: mybus-${opt:stage}
          pattern:
            source:
              - prod.admin.plans
            detail-type:
              - plan-updated
``` 

 Failed to create resource. Event bus mybus-dev already exists.

Similar or dependent issues:

- #1842

**Comment by eduardonunesp** [comment]
Ok find a way to workaround this, like the following example, but it needs at least the `arn:aws` to work

```yaml
custom:
  accountNumber: 123456789
  eventBus: arn:aws:events:us-east-1:${self:custom.accountNumber}:event-bus/mybus-${opt:stage}

functions:
  plans-create:
    handler: bin/eventbridge/plans/create
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBus}
          pattern:
            source:
            - prod.admin.plans
            detail-type:
            - plan-created

resources:
  Resources:
    EventBridgeBus:
      Type: AWS::Events::EventBus
      Properties:
          Name: mybus-${opt:stage}
```

**Comment by eduardonunesp** [comment]
The downside is that you can't delete the bus later since it should have some rules on it

**Comment by TreeMan360** [comment]
I have the same issue FWIW

**Comment by TreeMan360** [comment]
Is anyone looking at this? It’s causing me an issue in combination with https://github.com/horike37/serverless-step-functions/issues/289#issuecomment-568885886

**Comment by michalorman** [comment]
Having same issue. I was trying to work this around with following:

```yaml
functions:
  function-name:
    handler: ...
    events:
      - eventBridge:
          eventBus: !GetAtt
            - EventBus
            - Arn

resources:
  Resources:
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: custom-name
```

And getting:

```
TypeError: EventBus.startsWith is not a function
      at /Users/morman/.nvm/versions/node/v12.14.0/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/eventBridge/index.js:123:30
```

I'd expect that the `EventBus` created in `resources` section can be properly referenced and it's arn obtained with `!GetAtt`.

I'm on 1.62 version:

```
$ sls -v
Framework Core: 1.62.0
Plugin: 3.3.0
SDK: 2.3.0
Components Core: 1.1.2
Components CLI: 1.4.0
```
