### ISSUE TITLE
EnterpriseLogAccessIamRole -Too many parameters

### ISSUE THREAD

**Issue by joebernard** [serverless/serverless#6891]
# Bug Report

## Description

I have 61 lambda functions in my stack. Upon packaging, serverless is creating a Role called `EnterpriseLogAccessIamRole`. In the CloudFormation json it outputs 61 parameters, one for each of my functions. This causes CloudFormation to return the following error:

> Parameter count 61 is greater than max allowed 60.

CloudFormation only allows 60 parameters. I'm forced to disable Enterprise to work around the issue and deploy (commenting out `app:` in serverless.yml seems to do it).

Obviously this is not optimal as I'd like to use those enterprise features. It seems like Serverless Enterprise won't deploy with more than 60 functions due to this issue.

1. What did you do?
Deployed with 61 functions
1. What happened?
CloudFormation returned an error (too many parameters)
1. What should've happened?
Serverless should consolidate or break out those parameters so we don't hit that limit.

**Comment by dschep** [comment]
Could you share your `serverless.yml`? In attempting to reproduce this, I hit the 200 max resource limit instead.

**Comment by joebernard** [comment]
I am using the `split-stacks` plugin to workaround the 200 resource limit. My full `serverless.yml` is fairly large but here are the relevant bits:

```
org: myOrg
service: myService

plugins:
  - serverless-plugin-split-stacks
  - serverless-appsync-plugin
  - serverless-webpack
  - serverless-plugin-aws-alerts

package:
  individually: true

provider:
  versionFunctions: false

custom:
  splitStacks:
    perFunction: true
    perType: false

webpack:
    packager: "yarn"
    webpackConfig: "./webpack.config.js"
```
