### ISSUE TITLE
Serverless doesn't assume iam role when fetching AWS SSM variables

### ISSUE THREAD

**Issue by ludoblues** [serverless/serverless#6893]
# Bug Report

## Description

1. What did you do?
I am trying to fill some of my serverless.yml values with AWS Parameter Store variables

1. What happened?
Serverless doesn't assume the role from the provider, so the variables are not found.
If i store the variables directly in the iam user account Paramater Store, it works, so i am sure this is the point.

1. What should've happened?
Serverless should've assumed the role i specify in the provider section before fetching SSM variables

1. What's the content of your `serverless.yml` file?
```
service: myservice
org: myorg
app: myapp

custom:
  project: myproject

provider:
  name: aws
  region: eu-west-1
  role: ${opt:aws_role, 'arn:aws:iam::*****:role/*****'}
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  subnetIds:
    - ${ssm:/${self:custom.project}/${self:provider.stage}/subnet/private_a}
    - ${ssm:/${self:custom.project}/${self:provider.stage}/subnet/private_b}
  securityGroupIds:
    - ${ssm:/${self:custom.project}/${self:provider.stage}/security-group/lambda}

functions:
  register:
    name: ${self:org}-${self:app}-${self:provider.stage}-register
    handler: lambdas/register/handler.handler
    events:
      - http:
          path: register
          method: post
          cors: true
```
