### ISSUE TITLE
Bug in example code on AWS

### ISSUE THREAD

**Issue by half2me** [serverless/serverless#6900]
# Bug Report

## Description

1. What did you do?
I followed a simple 'Hello World' tutorial: [https://serverless.com/blog/serverless-express-rest-api/](https://serverless.com/blog/serverless-express-rest-api/), wrote the sample hello-world code and deployed with the `serverless deploy` command.
1. What happened?
It deployed my code, but upon accessing it, I just got an internal server error. When I logged onto my AWS Lambda console, I checked the code it had deployed. Everything seemed to be fine, except for my `index.js` file. It looked like this:
![image](https://user-images.githubusercontent.com/6759894/67788415-312cae80-fa6a-11e9-94a4-a995d430bfbf.png)
I have no idea what went wrong, as I didn't get any errors while deploying, but if I replace this weird code with the original contents of my index.js, my app starts working fine, and I get the "Hello World" response as I would expect. I don't know what is causing this, I am using windows and powershell.
1. What should've happened?
It should have deployed nicely, and my app sould be accessible and working (I guess)
1. What's the content of your `serverless.yml` file?
```yaml
org: halftome
service: fless
app: myapp

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
```
