### ISSUE TITLE
sls test sending a null body

### ISSUE THREAD

**Issue by Zacby** [serverless/serverless#6901]
# Bug Report

## Description
I'm following the integration test [documentation.](https://serverless.com/framework/docs/dashboard/testing/)

1. What did you do?
Whenever I combine `body` and `form` in the same request I'm getting a `null` body.

My test file looks like this.

```
- name: returns 200 when api_key is valid
  endpoint:
    function: functionName
  request:
    body: 'some _text'
    form:
      api_key: 'some_api_key'
      app_id: 'some_app_id',
      feed_name: 'some_feed_name'
  response:
    status: 200
    body:
      message: "Success"
```

I started testing the function with:

```
ls invoke local --function functionName  
```

Also when I test it with post man everything works fine.

Similar or dependent issues:
I didn’t find any similar issues

**Comment by Zacby** [comment]
If I use this structure for the test:

```
name: returns 200 when api_key is valid
  endpoint:
    function: functionName
  response: true
  request:
    form:
      api_key: 'some_api_key'
      app_id: 'some_app_id',
      feed_name: 'some_feed_name'
    body: ${file(/test/fixtures/some-file.json)}
```
two out of ten times it will work, the other eight times my lambda will receive `queryStringParameters:null` and `body:${file(/test/fixtures/some-file.json)}` with the file location as string.
