### ISSUE TITLE
alexaSmartHome Trigger is not added to my Aws lambda

### ISSUE THREAD

**Issue by lokesho** [serverless/serverless#6903]
# Bug Report

## I Added a event trigger to my serverless yaml file to deploy a aws lambda and adding a trigger.

Yaml Code for event trigger.

      events:
      - alexaSmartHome:
          appId: ${self:custom.awsAlexaSkill.${opt:stage, self:provider.stage}}
          enabled: true

When it is deployed it is not adding a trigger to my lambda.

If it is a Alexa Skill Kit trigger it works fine only Facing with alexaSmartHome Trigger.Below code Just works fine

      events:
      - alexaSkill:
          appId: ${self:custom.awsAlexaSkill.${opt:stage, self:provider.stage}}
          enabled: true

**Comment by pmuens** [comment]
Hey @lokesho thanks for opening :+1:

Apparently your indentation is wrong. This should do the trick:

```yaml
  events:
    - alexaSkill:
        appId: ${self:custom.awsAlexaSkill.${opt:stage, self:provider.stage}}
        enabled: true
```
