### ISSUE TITLE
Cannot use serverless remove when using existing buckets with s3 events

### ISSUE THREAD

**Issue by joshuaduffy** [serverless/serverless#6905]
# Bug Report

## Description

Observed with latest version of serverless 1.55.1

1. What did you do?
Ran `serverless remove` to delete a stack that contains a number of lambdas that are attached an existing bucket (as detailed in https://serverless.com/framework/docs/providers/aws/events/s3/#using-existing-buckets)

1. What happened?

Stack failed to delete with:

```
An error occurred: ResourceContentEventCustomS31 - Failed to delete resource. The specified bucket does not exist See details in CloudWatch Log: 2019/10/30/[$LATEST]d80e4ccd09fc4483bf18b9e3c3b63ec3.
```

1. What should've happened?

Stack should delete.

1. What's the content of your `serverless.yml` file?

Bucket created in resources section...

```
resources:
  Resources:
    ContentBucket:
      Type: AWS::S3::Bucket
```

... and referenced with `existing=true` flag

```
  thing:
    handler: thing
    package:
      artifact: ./artifacts/thing.zip
    events:
      - s3:
          bucket: ${self:provider.contentBucket}
          events:
            - s3:ObjectCreated:*
          existing: true
```
