### ISSUE TITLE
AWS unable to use tags with custom partition name `aws-cn`

### ISSUE THREAD

**Issue by flosch-hb** [serverless/serverless#6925]
# Bug Report

AWS provider tagging fails on custom partition when a function is deployed as an API Gateway

## Description

1. What did you do?
I am deploying an API Gateway with serverless in 2 different partitions: one "regular" AWS account (partition name being `aws`) and one specific to AWS China (partition name being `aws-cn`):
> serverless deploy --stage dev --region cn-northwest-1

2. What happened?
A Serverless Error occurs and breaks the deployment

3. What should've happened?
The deployment should finish without error

4. What's the content of your `serverless.yml` file?

```yaml
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'} # overridden in CLI
  memorySize: 128
  timeout: 15
  # ...
  tags:
    foo: 'bar'

functions:
  hello-world:
    handler: functions/hello-world.handler
    runtime: nodejs10.x
    endpointType: regional # "regional" is required for AWS China, this can of course be set as a variable for different regions
    events:
      - http:
          path: /
          method: GET
          cors: true
```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
> Serverless: [AWS apigateway 400 4.774s 0 retries] tagResource({
>    resourceArn: 'arn:aws:apigateway:cn-northwest-1::/restapis/{XXXXXX}/stages/{YYYYYY}',
>    tags: { foo: 'bar' }
> })
> Serverless Error ---------------------------------------
 > ServerlessError: Expected ARN arn:aws-cn:apigateway:cn-northwest-1::/restapis/{XXXXXX}/stages/{YYYYYY} for Stage {YYYYYY} on RestApi {XXXXXX}, not arn:aws:apigateway:cn-northwest-1::/restapis/{XXXXXX}/stages/{YYYYYY}

The `tagResource()` in this case references the wrong partition name `arn:aws:[...]` instead of `arn:aws-cn:[...]`.

The deployment works when I comment out the `tags` config from the provider, which makes me think this is indeed a bug.

I just have a small doubt if I am missing some config for this to work, but I have not found anything related to that in the doc so far, so trying this bug report.

PS: I would be happy to submit a PR, if you wish to point me to the right direction to find the tagResource?
