### ISSUE TITLE
Enabling XRay tracing on an existing stack fails

### ISSUE THREAD

**Issue by jamesmbourne** [serverless/serverless#6931]
# Bug Report

## Description

When enabling AWS X-Ray tracing on an existing stack, the update fails with the following error:

```
An error occurred: HelloLambdaFunction - The provided execution role does not have permissions to call PutTraceSegments on XRAY (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: ********-****-****-****-************).
```

This error does not seem to be reproducible 100% of the time and appears to be a race to update the Lambda Execution role and the function itself.

1. What did you do?

   - Deploy a Serverless stack with tracing disable
   - Update `provider.tracing.lambda` to `true`
   - Re-deploy the stack

1. What happened?
   - The error `The provided execution role does not have permissions to call PutTraceSegments on XRAY` is returned and the stack does not update
1. What should've happened?
   - The stack updates, grants the necessary permissions to the execution role, and enables Lambda X-Ray tracing
1. What's the content of your `serverless.yml` file?

   - Initial stack creation:

   ```yml
   service:
     name: xray-permissions

   provider:
     name: aws
     runtime: nodejs10.x

   functions:
     hello:
       handler: handler.hello
       events:
         - http:
             method: get
             path: hello
   ```

   - Update:

   ```yml
   service:
     name: xray-permissions

   provider:
     name: aws
     runtime: nodejs10.x
     tracing:
       lambda: true # This has been enabled after creation

   functions:
     hello:
       handler: handler.hello
       events:
         - http:
             method: get
             path: hello
   ```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

- #3495
