### ISSUE TITLE
Serverless deploy cannot work in aws china region again

### ISSUE THREAD

**Issue by liangruibupt** [serverless/serverless#6933]
# serverless.yml snippet as below:

```
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 120
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: cn-north-1
  endpointType: REGIONAL
  role: arn:aws-cn:iam::xxxxxxx:role/lambda_basic_execution
```

# Execute the command
serverless deploy -v --aws-profile cn-north-1 --region cn-north-1

CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_FAILED - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy

# Analysis:
From cloudformation event:
```
Policy has invalid resource (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: F71CCB66B83C23E0; S3 Extended Request ID: qUd5Z8E6Hm2hwbjiVF2aSysrvYZ0iGtyILkOdslMP8snWKWTEH4KXdnwlNXCAf2ep9M9NZEN/Kw=)
```

I checked the policy ARN is wrong: arn:aws:s3::: should be arn:aws-cn:s3:::
{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}},"ServerlessDeploymentBucketPolicy":{"Type":"AWS::S3::BucketPolicy","Properties":{"Bucket":{"Ref":"ServerlessDeploymentBucket"},"PolicyDocument":{"Statement":[{"Action":"s3:*","Effect":"Deny","Principal":"*","Resource":[{"Fn::Join":["",["arn:aws:s3:::",{"Ref":"ServerlessDeploymentBucket"},"/*"]]}],"Condition":{"Bool":{"aws:SecureTransport":false}}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}

I checked below merge
https://github.com/serverless/serverless/pull/6127

It worked before, but failed on serverless@1.57.0
