### ISSUE TITLE
Layer Version Update Doesn't Retain Version Policy

### ISSUE THREAD

**Issue by lukiffer** [serverless/serverless#6943]
# Bug Report

## Description

When you deploy a layer, the layer version policy is correctly applied. If you then subsequently deploy an update to the layer, the layer version policy is correctly applied to the latest version but the previous version loses this policy.

1. What did you do?

Deployed a layer with the `retain: true` option. Then made an update to the layer and deployed.

1. What happened?

The latest version of the layer has the layer version policy applied, but the previous version does not.

1. What should've happened?

Both the new version and previous version(s) should have had the layer version policy applied.

1. What's the content of your `serverless.yml` file?

```
service: example-service
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region}
  stage: ${opt:stage}

layers:
  ArmorLogRelay:
    path: "dist"
    compatibleRuntimes:
      - python3.7
    allowedAccounts:
      - "*"
    licenseInfo: Apache License 2.0
    retain: true
```
