### ISSUE TITLE
sns topic not triggering lambda after programmatic deployment

### ISSUE THREAD

**Issue by LEscobar-Driver** [serverless/serverless#6946]
# Bug Report

## Description

I am deploying a lambda function which is triggered by an sns topic. I have a serverless yaml file which I used 2 months back and everything was deploying perfect. Yesterday I deleted the entire cloudfirmation stack and simply redeployed the same yaml file and now the sns topic has no subscription and the lambda function has no trigger. 

1. What did you do? sls deployed my stack
1. What happened? programtic integrations didnt occur as expected
1. What should've happened? sns topic should have lambda function subscribed and lambda should have sns topic trigger.
1. What's the content of your `serverless.yml` file?
```
service: selenium-lambda

provider:
  name: aws
  runtime: python3.6
  memorySize: 1024
  timeout: 900
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage,'beta'}
  apiKeys: 
    - ${opt:key, 'beta_key'}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"


functions:
  mailFileCheck:
    environment:
      aws_access_key_id: ${file(../config/env-var/aws-${opt:env, 'labs'}.json):aws_access_key_id}
      aws_secret_access_key: ${file(../config/env-var/aws-${opt:env, 'labs'}.json):aws_secret_access_key}
      aws_region: ${file(../config/env-var/aws-${opt:env, 'labs'}.json):aws_region}
      s3_access_key_id: ${file(../config/env-var/aws-s3-legacy-access.json):aws_access_key_id}
      s3_secret_access_key: ${file(../config/env-var/aws-s3-legacy-access.json):aws_secret_access_key}
      bucket: ${file(../config/env-var/publish.json):bucket}
    handler: main.endpoint
    layers:
      - ${cf:selenium-layer-beta.SeleniumLayerExport}
      - ${cf:selenium-layer-beta.ChromedriverLayerExport}
      - ${cf:pandas-layer-beta.PandasLayerExport}
    timeout: 900 
    memorySize: 3008
    events:
      - sns:
        arn: !Ref Trigger
        topicName: InitTrigger


  snsLambdaPublisher:
    handler: publish.handler
    package:
      individually: true
      exclude:
        - func/**
        - main.py
        - results.py
    layers: 
      - ${cf:other-requirements-beta.OtherRequirementsLayerExport:2}
    environment:
      aws_access_key_id: ${file(../config/env-var/aws-${opt:env, 'labs'}.json):aws_access_key_id}
      aws_secret_access_key: ${file(../config/env-var/aws-${opt:env, 'labs'}.json):aws_secret_access_key}
      aws_region: ${file(../config/env-var/aws-${opt:env, 'labs'}.json):aws_region}
      bucket: ${file(../config/env-var/publish.json):bucket}
      sns_topic: ${file(../config/env-var/publish.json):sns_topic}
      acct_id: ${file(../config/env-var/publish.json):acct_id}
    events:
      - http:
          path: ${opt:publish, 'V1/publish'}
          method: get
          cors: true
          private: true
          integration: lambda
          memorySize: 128 
          request:
            template:
              application/json: >
                {
                  "dropID" : "$input.params('dropID')",
                  "rebuild" : "$input.params('rebuild')"
                }


resources:
  Resources:

    Trigger:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: InitTrigger
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

- #12345
