### ISSUE TITLE
aws-go/aws-go-dep Template does not deploy after creating project

### ISSUE THREAD

**Issue by CairoAtlas** [serverless/serverless#6947]
# Bug Report
Run serverless deploy --aws-profile [profile] after creating new serverless project from aws-go and it fails
## Description
Error:
```
Macbook:serverlessProductsApi user$ serverless create --template aws-go-dep
Serverless: Generating boilerplate...
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.57.0
 -------'

Serverless: Successfully generated boilerplate for template: "aws-go-dep"
Serverless: NOTE: Please update the "service" property in serverless.yml with your service name
Macbook:serverlessProductsApi user$ serverless deploy --aws-profile sandbox
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.15.1
     Framework Version:         1.57.0
     Plugin Version:            3.2.2
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

```

Steps to reproduce
1. Create serverless project with aws-go or aws-go-dep template
2. Run serverless deploy

My serverless yaml file is exactly what was produced from the template except all comments removed and added stage
```
service: serverlessProductsApi

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, "test"}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get
```
