### ISSUE TITLE
Request with binary media returns 500

### ISSUE THREAD

**Issue by tinexw** [serverless/serverless#6949]
# Bug Report

## Description
When using `binaryMediaTypes` in combination with lambda non-proxy integration, then a 500 error is always returned. When using the lambda proxy integration (as given here: #6063 ) everything works fine.

The only workaround I found is to manually edit the referenced lambda function once and to re-deploy the stage (as described here: #4628). This adds additional permission to the function's policy - which I assume is what "fixes" the issue.

Lambda policy **before** applying workaround:
```
aws lambda get-policy --function-name test-dev-hello  
{
    "Policy": "{\"Version\":\"2012-10-17\",\"Id\":\"default\",\"Statement\":[{\"Sid\":\"test-dev-HelloLambdaPermissionApiGateway-T1A01LP3JK5R\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"apigateway.amazonaws.com\"},\"Action\":\"lambda:InvokeFunction\",\"Resource\":\"arn:aws:lambda:eu-central-1:123:function:test-dev-hello\",\"Condition\":{\"ArnLike\":{\"AWS:SourceArn\":\"arn:aws:execute-api:eu-central-1:123:z9qb5x6fnb/*/*\"}}}]}",
    "RevisionId": "4d4b049e-f69b-4aad-a14b-76d4fba515ff"
}

```

Lambda policy **after** applying workaround:
```
aws lambda get-policy --function-name test-dev-hello  
{
    "Policy": "{\"Version\":\"2012-10-17\",\"Id\":\"default\",\"Statement\":[{\"Sid\":\"test-dev-HelloLambdaPermissionApiGateway-T1A01LP3JK5R\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"apigateway.amazonaws.com\"},\"Action\":\"lambda:InvokeFunction\",\"Resource\":\"arn:aws:lambda:eu-central-1:123:function:test-dev-hello\",\"Condition\":{\"ArnLike\":{\"AWS:SourceArn\":\"arn:aws:execute-api:eu-central-1:123:z9qb5x6fnb/*/*\"}}},{\"Sid\":\"653c0028-bc43-43b0-84d5-f8c3ae45d8f4\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"apigateway.amazonaws.com\"},\"Action\":\"lambda:InvokeFunction\",\"Resource\":\"arn:aws:lambda:eu-central-1:123:function:test-dev-hello\",\"Condition\":{\"ArnLike\":{\"AWS:SourceArn\":\"arn:aws:execute-api:eu-central-1:123:z9qb5x6fnb/*/GET/hello\"}}}]}",
    "RevisionId": "79bb00a3-93b9-4fd6-8bf6-95cb49a3818a"
}


```

1. What did you do?
- Created an API gateway with 

```
binaryMediaTypes:
      - '*/*'
```

and a simple function with `integration: lambda`.

1. What happened?
- Calling the function returns 500.
1. What should've happened?
- Calling the function should return 200.
1. What's the content of your `serverless.yml` file?

```
service: test

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: hello
          integration: lambda
```

```
// handler.js
'use strict';

module.exports.hello = async (event) => {
  return "hello";
};
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

- #2797
- #4628

**Comment by tinexw** [comment]
Might not be caused by the missing permission after all. I modified the `serverless.yml` to include the additional lambda permission. But it still doesn't work.

```
resources:
  Resources:
    ApiGatewayMethodHelloGet:
     # To ensure that permission is created before deployment  - in the hope that this would somehow fix it...
      DependsOn: HelloLambdaPermission
      Type: AWS::ApiGateway::Method
    HelloLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt HelloLambdaFunction.Arn
        Action: 'lambda:InvokeFunction'
        Principal: apigateway.amazonaws.com
        SourceArn: !Join ["", ["arn:aws:execute-api:", "${self:provider.region}:", "123:", !Ref ApiGatewayRestApi, "/*/GET/hello"]]
```
