### ISSUE TITLE
Get Lambda Function Version

### ISSUE THREAD

**Issue by thadeubrito** [serverless/serverless#6953]
Hi guys, I've been trying to get lambda function version to set it in an alert param. The problem is the dynamic hash added after LambdaVersion key name on https://github.com/serverless/serverless/blob/85438ea4664bb1990dab2103fccaceacb8ba39ab/lib/plugins/aws/lib/naming.js#L161

I would like to user something like this:
```yml
- Name: ExecutedVersion
  Value:
    Fn::GetAtt:
      - AuthorizeLambdaVersionEicIz9XIpPWv5CiEyiCQSnLX9gPsQvENBJNL0ZVc
      - Version
```

but without digest. Another way to get the latest version number is valid as well. Anyone can help me?
