### ISSUE TITLE
Enabling API Gateway Logs in serverless.yml tries to create new IAM Role and a new Lambda

### ISSUE THREAD

**Issue by sunilhari** [serverless/serverless#6973]
# Bug Report

## Description

1. What did you do?
 ```yml
logs:
    restApi: # Optional configuration which specifies if API Gateway logs are used. This can either be set to true to use defaults, or configured via subproperties.
      executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
      level: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
      fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
      role: <role that allows pushing to logs to cloudwatch>#
```
I have added this configuration in my serverless.yml file to enable cloudwatch logging for API gateway.

2.  What happened?
 I got the following error while I tried to deploy
```
  An error occurred: IamRoleCustomResourcesLambdaExecution - API: iam:CreateRole User: arn:aws:sts::<some role name> is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::<some resource name>with an explicit deny
```
I have restricted access to this account and i dont have access to create IAM roles.I have observed that it tries to create a role (`IamRoleCustomResourcesLambdaExecution`) and new Lambda `-custom-resource-apigw-cw-role`

3. What should've happened?
 It should have enabled cloudwatch logs for API gateway

4. What's the content of your `serverless.yml` file?
```yml
# along with other resources
logs:
    restApi: # Optional configuration which specifies if API Gateway logs are used. This can either be set to true to use defaults, or configured via subproperties.
      executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
      level: INFO # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
      fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
      role: <role to write to cloudwatch> #
```

Similar or dependent issues:

- #6134 
This issue was closed with suggesting a resolution.Hence creating another issue.

**Comment by jdahlke** [comment]
I'm having the same issue.
The error seems to be here.

https://github.com/serverless/serverless/blob/d33ee52d28b3d19c4df9bfdd63ac86b63ee6995d/lib/plugins/aws/package/compile/events/lib/ensureApiGatewayCloudWatchRole.js#L16

Even though `roleArn` is configured via `logs.restApi.role`, it still tries to create a custom resource `apiGatewayCloudWatchRole`.

**Comment by medikoo** [comment]
In that case specify externally created role that should cover custom resource lambda invocations.
Role's ARN should be passed to `provider.cfnRole` setting.

Still, note this role will cover both CloudFormation stack deployments, and cover Lambda invocations, so both services need to be listed as trusted principal services (if not, deployments will fail as here: https://github.com/serverless/serverless/issues/6876)

**Comment by sunilhari** [comment]
@medikoo 

- I just need serverless to enable logs while creating/Adding resources to API gateway and I have provided the role in restApi.role.
- I do not want serverless to create any custom lambda resources just to enable logs in API gateway.I just want API gateway logs to flow to cloudwatch.

Can you help me understand why serverless is trying to create custom resources in the first place ?

**Comment by medikoo** [comment]
> Can you help me understand why serverless is trying to create custom resources in the first place ?

Custom resources solve configuration which cannot be done efficiently via CloudFormation (it's either not supported, or supported in limited form).

In case of API Gateway logs, we need to ensure that there's IAM role with appriopriate access rights assigned to region wide APIGW CloudWatch logs role setting.

While in theory that can be accomplished via CloudFormation, in that form it requires creation of new IAM role with every new stack. We solve it via custom resources, so we reuse same role resource across different stacks.

**Comment by sunilhari** [comment]
In my case I have specific role created by my cloud admin team for API gateway to push logs to cloudwatch.
How can I use the same role  in CF stack to push API gateway logs.?

**Comment by medikoo** [comment]
> How can I use the same role in CF stack to push API gateway logs.?

Configure its arn at `provider.logs.restApi.role` in `serverless.yml`

**Comment by sunilhari** [comment]
@medikoo 

So even if i set the above configuration, it still tries to create a new role.
That is the actual problem I am facing.

**Comment by seylas** [comment]
Is it possible to add some parameter "patchAPIGatewayAccountRole" with a default value of "true"? So if false, it wouldn't create a custom lambda and add CloudWatch put logs role to API Gateway account. 
The intention is to have a possibility to manage API Gateway account role by [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-account.html) at some earlier step for account and not from serverless framework.

**Comment by pmuens** [comment]
Apparently https://github.com/serverless/serverless/pull/6747 introduced the functionality to wrap the role into a custom CloudFormation resources which seems to be the main issue here.

@sunilhari so the idea is to simply not use custom CloudFormation resources at all when using the `provider.restApi.logs` property?

I'm not too familiar with the initial implementation of using custom CloudFormation resources for REST API roles. @medikoo any objections to change the behavior of passing everything through custom CloudFormation resources? Are there any downsides to this approach?

**Comment by medikoo** [comment]
@pmuens to my understanding, the issue is, that what was implemented here: https://github.com/serverless/serverless/pull/6747 doesn't seem to work (I contacted you, as you were finalizing that PR :)

I've explained [here](https://github.com/serverless/serverless/issues/6973#issuecomment-557483607) why we handle that via custom resource. Technically via CF we will have to create with each new stack new role, without ability to remove it once stack is removed (hence in case of a lot of stacks is processed used will end with many not needed roles created in his AWS console)

**Comment by pmuens** [comment]
> @pmuens to my understanding, the issue is, that what was implemented here: #6747 doesn't seem to work (I contacted you, as you were finalizing that PR :)

I just tested it and it works just fine on my machine. The `role` arn I specify is set as the CloudWatch log role ARN for API Gateway.

> I've explained here why we handle that via custom resource. Technically via CF we will have to create with each new stack new role, without ability to remove it once stack is removed (hence in case where a lot of stacks are processed, user will end with many not needed roles created in his AWS console)

I see. So it's an either / or here. Either we go via custom CloudFormation resources to not deal with dozens of roles or we don't and users will face the aforementioned issue of having a bunch of unused roles in their account when they remove their stacks.

Given that, what is the solution here?

**Comment by medikoo** [comment]
> Given that, what is the solution here?

I think we should coin, whether there is a bug or not.

@sunilhari and few others state, that even with `provider.logs.restApi.role` setting being set, the _apiGatewayCloudWatchRole_ custom resource attempts to create a new IAM role.

@pmuens you state that you've just tested it, and that's not the case, correct?

**Comment by pmuens** [comment]
> @pmuens you state that you've just tested it, and that's not the case, correct?

@medikoo Yes, it's working in my case. It's still creating a role for the Lambda to execute the custom resource in which we wrap the role creation (see implementation in https://github.com/serverless/serverless/pull/6747).

According to the issue description, creating a new role is not allowed, correct @sunilhari? So apparently we can't wrap the role creation in a custom resource in that case since the custom resource which is backed by a Lambda needs an IAM Role to execute the custom resource Lambda code. That seems to be the main issue here.

**Comment by medikoo** [comment]
> @medikoo Yes, it's working in my case. It's still creating a role for the Lambda to execute the custom resource in which we wrap the role creation (see implementation in #6747).

ok but that we allow to override with `provider.cfnRole`. If it's set new role should not be created.

So the solution is to have both configured `provider.cfnRole` and `provider.logs.restApi.role` that should ensure there's not attempt to create a new role by the framework.

**Comment by medikoo** [comment]
@sunilhari can you confirm then, if you stil face the issue, having both `provider.cfnRole` and `provider.logs.restApi.role` configured ?

**Comment by sunilhari** [comment]
Correct me if am wrong.
So i will have to configure IAM role of the user account who is executing the CF stack.
In another words,I should specify my access role here
Is my understanding correct?

**Comment by medikoo** [comment]
@sunilhari via `cfnRole` setting you may provision a dedicated role which should be used for stack deployment. See `RoleARN` explanation at https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html for more info.

The same role then will be used for custom resource lambda invocations. This the way to ensure that Framework will not create its own dedicated role for that.

**Comment by ywang9009gmail** [comment]
Hi, What's the suggested solution? Could someone explain? Thanks

**Comment by coyoteecd** [comment]
@ywang9009gmail The solution is mentioned a few comments above:

> So the solution is to have both configured provider.cfnRole and provider.logs.restApi.role that should ensure there's not attempt to create a new role by the framework.

The effect is that serverless will then use the `cfnRole` to run that custom resource lambda that checks and assigns to API Gateway the CloudWatch role you specified by `restApi.role`. If you already specify a `cfnRole` for limited-access deployments, that role must have a number of permissions assigned which were mentioned across various other issues. This is what policies I had to add to get it working (statements below extracted from role definition of MyCfnRole, I specified only stuff I had to add to be able to deploy once I enabled the logs):

```
Resources:
  MyCfnRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyCfnRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
[...]
      Policies:
        - PolicyName: CloudWatch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !Sub arn:#{AWS::Partition}:iam::#{AWS::AccountId}:role/MyCfnRole
                  - !Sub arn:#{AWS::Partition}:iam::#{AWS::AccountId}:role/MyApiLogRole
              - Effect: Allow
                Action:
                  - apigateway:GET
                  - apigateway:PATCH
                Resource:
                  - arn:#{AWS::Partition}:apigateway:*::/account
[...]

      ManagedPolicyArns:
        # Required for deploying custom resources (which serverless uses to activate API Gateway logs)
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
```
With this above config, I can confirm it works using the latest serverless v1.63, so I mentioned here in case somebody else hits it.

@medikoo @pmuens  I played with this and I have to say I do not like the custom resource solution. At a minimum, I **needs** a dedicated documentation page to explain the effects of each setting, I had to wade through multiple github issues to figure out how it works and basically wasted a day. Admittedly, part of it discovering the missing permissions, given that CloudFormation is not always helpful. I have also ran into #6643, which in my case was likely due to lack of permissions, but the error was hidden away by the 10-retry logic in the custom resource which possibly got me the "too many requests errors".

I understand that the CloudWatch log ARN is a global setting and you can't add/remove it at will. What I would like to see then is for serverless **not** to try to set it at all. I am perfectly fine setting up a role at account level and assign it to API Gateway directly through CloudFormation resources (I do this in a separate "account setup" deployment). And I do not want the API deployment to create a custom resource just to double-check my ARN there, it looks like too much hassle to me and it forces me to grant additional permissions which are better left to the "account setup" part.

One simple way is to add an extra boolean setting to control this behavior. When false, assume it's been assigned externally and do not create the custom resource (but: more settings = more confusion). 

Another way is to just make this the default behavior and assume that when a role is given, it's been also configured in API Gateway, so no need to use the custom resource at all. Document this (see above) and it'll be fine. Figuring out all those permissions certainly takes more time than setting up the role via `resources` section.

**Comment by larsbe** [comment]
I was also facing the issue that even though I specified an existing role, a new one was created.

I'm not sure if this is a reliable workaround but what seems to work for me is simply creating an `AWS::ApiGateway::Account` manually.

```
ApiGatewayAccount:
        Type: 'AWS::ApiGateway::Account'
        DependsOn: ApiGatewayRestApi
        Properties:
          CloudWatchRoleArn: 'arn:aws:iam::#{AWS::AccountId}:role/cloudwatch-logs-role-name'
```

After this, the correct role (`'arn:aws:iam::#{AWS::AccountId}:role/cloudwatch-logs-role-name'`) was referenced in the API Gateway settings.

**Comment by medikoo** [comment]
@coyoteecd Thanks for all this input, it's very valuable

> I have also ran into #6643, which in my case was likely due to lack of permissions, but the error was hidden away by the 10-retry logic

It'll be good to have that fixed. Can you create a separate issue and explain exactly what error occured that should not be retried, when it was.

> And I do not want the API deployment to create a custom resource just to double-check my ARN there, it looks like too much hassle to me and it forces me to grant additional permissions which are better left to the "account setup" part.

We're definitely open for PR that provides that and improves the documentation so it's more transparent

**Comment by medikoo** [comment]
> I was also facing the issue that even though I specified an existing role, a new one was created.

@larsbe are you using maybe Serverless Dashboard? Maybe it was the log access role that's created for you (that could be overridden by `custom.enterprise.logAccessIamRole` setting).

Otherwise if you feel that role remains created, when it shouldn't  please create a reproducible minimal test case.  Currently we're not aware of any bugs on that level.

**Comment by IrmantasM** [comment]
Why is this closed? I don't understand where is the solution?

**Comment by coyoteecd** [comment]
@IrmantasM have you read through #7333?

**Comment by jeffmurphy** [comment]
> Why is this closed? I don't understand where is the solution? I am following serverless documentation, specifying existing role:
> 
> ```
> provider:
>   name: aws
>   logs:
>     restApi:
>       role: arn:aws:iam::#{AWS::AccountId}:role/api-gateway-role
> ```
> 
> And serverless for who knows what reason is trying to create some new role:
> 
> ```
> An error occurred: IamRoleCustomResourcesLambdaExecution - 
> API: iam:CreateRole User: arn:aws:iam::xxxx:user/service.jenkins.app.nonprod.user 
> is not authorized to perform: iam:CreateRole on resource: 
> arn:aws:iam::xxxx:role/xxx-xxx-xxx-xxx-IamRoleCustomResourcesLambda-10F8BW2I9CEUQ.
> ```

```
provider:
  logs:
    restApi:
      roleManagedExternally: true # disables automatic role creation/checks done by Serverless
```
https://serverless.com/framework/docs/providers/aws/events/apigateway#logs

**Comment by IrmantasM** [comment]
Thanks @jeffmurphy trying this now, at same time docs say:

```
Let Serverless assign an existing IAM role that you created before the deployment, if not already assigned:

provider:
  logs:
    restApi:
      role: arn:aws:iam::123456:role
```

I might not be reading this correctly but to me it means that specifying role should be enough "assign an existing IAM role that you created before the deployment"

**Comment by coyoteecd** [comment]
@IrmantasM the problem is that for Serverless to assign that role (or to check that it's already assigned), it needs to run a custom Lambda function that does that verification. See also the note in that documentation section. 

It is **that Lambda function** that needs a role, and Serverless tries to auto-create one for you because you're probably not using the `cfnRole` property. See also [my comment above](https://github.com/serverless/serverless/issues/6973#issuecomment-583739682).

**Comment by IrmantasM** [comment]
Thanks @coyoteecd , after adding `roleManagedExternally: true` I no longer get any errors.

Thanks for mentioning about `cfnRole`, I wasn't aware about this property, will definitely check it out as it seems to be recommended best practice.

**Comment by PatrykMilewski** [comment]
`roleManagedExternally: true` fixed the problem for me:

```
  logs:
    restApi:
      level: INFO
      role: "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
      roleManagedExternally: true
```
