### ISSUE TITLE
CORS - allowCredentials: false - does not omit response headers Access-Control-Allow-Credentials

### ISSUE THREAD

**Issue by wildhaber** [serverless/serverless#6994]
# Bug Report

### What did you do?

Setting up a resource with CORS and set `allowCredentials: false` e.g.

```yaml
# ...

functions:
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          path: product/{id}
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

# ...
```

### What happened?

The response headers of a CORS preflight contained the `access-control-allow-credentials`-header. 

```
access-control-allow-credentials: false
```

### What should've happened?

According to the specifications, the only valid value for this header is `'true'` and should be omitted when false.

> The only valid value for this header is true (case-sensitive). If you don't need credentials, omit this header entirely (rather than setting its value to false).

source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials

> Access-Control-Allow-Credentials = %s"true" ; case-sensitive

source: https://fetch.spec.whatwg.org/#http-new-header-syntax

### What's the content of your `serverless.yml` file?

(excerpts)

```yaml
functions:
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          path: product/{id}
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
```

or:

```yaml
functions:
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          path: product/{id}
          method: get
          cors: true
```

### What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

(let me know if this is relevant :-) )

### Similar or dependent issues:

- not found

---

### Further information:

I've preparing this issue as wished in the [contribution guidelines](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#when-you-propose-a-new-feature-or-bug-fix)  before submitting a PR. 

If you agree on this bug/improvement the code is ready to be submitted as PR (https://github.com/wildhaber/serverless/tree/fix/cors-omit-access-control-alow-credentials-on-false)

The required change is tiny:

```javascript
// lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js
      const preflightHeaders = {
        'Access-Control-Allow-Origin': `'${origin}'`,
        'Access-Control-Allow-Headers': `'${config.headers.join(',')}'`,
        'Access-Control-Allow-Methods': `'${config.methods.join(',')}'`,
      };

      // Only set Access-Control-Allow-Credentials when explicitly allowed (omit if false)
      if(config.allowCredentials === true) {
        preflightHeaders['Access-Control-Allow-Credentials'] = `'${config.allowCredentials}'`;
      }
```
[see diff](https://github.com/serverless/serverless/compare/master...wildhaber:fix/cors-omit-access-control-alow-credentials-on-false#diff-872f8cac897abe18c7e8d00884f15926L33-R39)

(+ [Tests](https://github.com/serverless/serverless/compare/master...wildhaber:fix/cors-omit-access-control-alow-credentials-on-false#diff-047d4bdcd95d2284771376374067d708) / + [Docs](https://github.com/serverless/serverless/compare/master...wildhaber:fix/cors-omit-access-control-alow-credentials-on-false#diff-871929e390d61a5d2a3b505ac9b4bf24R287))
