### ISSUE TITLE
Custom Resource does not support AWS US Gov Cloud Region (us-gov-west-1)

### ISSUE THREAD

**Issue by jmb12686** [serverless/serverless#6995]
# Bug Report

## Description

1. What did you do?
Attempting to deploy a serverless application in `us-gov-west-1` that utilizes Custom Resources (an AWS Lambda function with event trigger on existing S3 bucket. 

1. What happened?
The CloudFormation stack hangs for one hour on deploying the Custom S3 resource and rolls back.  I noticed errors occurring on the Custom Resource lambda, but no logging was present.  After editing the serverless cloudformation to add logging rights to the custom resource lambda, I noticed the error is due to `/lib/plugins/aws/customResource/utils.js` not supporting Lambda ARN pattern for `us-gov-west-1`.  The offending lines in the code are [here](https://github.com/serverless/serverless/blob/1249361035362c8fc33c6ade7c3b3f09bea34f4d/lib/plugins/aws/customResources/resources/utils.js#L59) and [here](https://github.com/serverless/serverless/blob/1249361035362c8fc33c6ade7c3b3f09bea34f4d/lib/plugins/aws/customResources/resources/utils.js#L64)

The lambda arn schema in Gov Cloud is a bit different than other regions:
`arn:aws-us-gov:lambda:us-gov-west-1:XXXXXXXXXX:function:s3-asset-scanner-app-3-dev-scanner`

The error from custom resource lambda:
```
START RequestId: 3119d862-248a-45cb-b343-a3ec830ec496 Version: $LATEST

2019-11-21T18:31:34.257Z	3119d862-248a-45cb-b343-a3ec830ec496	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property '0' of null",
    "stack": [
        "TypeError: Cannot read property '0' of null",
        "    at getEnvironment (/var/task/utils.js:67:19)",
        "    at create (/var/task/s3/handler.js:19:33)",
        "    at handler (/var/task/s3/handler.js:9:12)",
        "    at Runtime.handler (/var/task/utils.js:78:28)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}

END RequestId: 3119d862-248a-45cb-b343-a3ec830ec496
REPORT RequestId: 3119d862-248a-45cb-b343-a3ec830ec496	Duration: 3.48 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 84 MB	Init Duration: 312.26 ms	
START RequestId: 3119d862-248a-45cb-b343-a3ec830ec496 Version: $LATEST
2019-11-21T18:32:33.423Z	3119d862-248a-45cb-b343-a3ec830ec496	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property '0' of null",
    "stack": [
        "TypeError: Cannot read property '0' of null",
        "    at getEnvironment (/var/task/utils.js:67:19)",
        "    at create (/var/task/s3/handler.js:19:33)",
        "    at handler (/var/task/s3/handler.js:9:12)",
        "    at Runtime.handler (/var/task/utils.js:78:28)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
END RequestId: 3119d862-248a-45cb-b343-a3ec830ec496
REPORT RequestId: 3119d862-248a-45cb-b343-a3ec830ec496	Duration: 6.18 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 84 MB	
```

1. What should've happened?

Stack should have deployed correctly, and the supporting Custom Resource lambda should properly parse ARNs in US Gov Cloud regions, such as **`arn:aws-us-gov:lambda:us-gov-west-1**

1. What's the content of your `serverless.yml` file?

```yaml
service: s3-asset-scanner-app-3

provider:
  name: aws
  endpointType: REGIONAL  
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'} ## dev stage is default, can be overridden by CLI (for ex: serverless deploy --stage prod
  region: us-gov-west-1
  profile: ${opt:profile, 'pgfs-ci-service'} ##This must match a valid IAM profile in ~/.aws/credentials
  #profile name default is 'pgfs-ci-service', can be interpolated using the stage for different environments, or overridden by the CLI

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  s3BucketArn: 'arn:aws-us-gov:s3:::REDACTED'
  s3BucketName: 'REDACTED'
  allowedMIMETypes: 'image/png,image/jpeg,image/gif'
  notificationTopicArn: 'sadfsdf'

package:
  exclude:
    - node_modules/**/*

functions:
  scanner:
    handler: handler.scanner
    memorySize: 128
    environment:
      S3_BUCKET_ARN: ${self:custom.s3BucketArn}
      S3_BUCKET_NAME: ${self:custom.s3BucketName}
      ALLOWED_MIME_TYPES: ${self:custom.allowedMIMETypes}
      NOTIFICATION_TOPIC_ARN: ${self:custom.notificationTopicArn}
    events:
      - s3:
          bucket: REDACTED #TODO Parameterize this later
          event: s3:ObjectCreated:*
          existing: true         

```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

serverless version / environment info:

```ps
  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.15.1
     Framework Version:         1.58.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

serverless deploy:

```ps
$ serverless deploy --region us-gov-west-1 --stage dev --verbose
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - s3-asset-scanner-app-2-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - s3-asset-scanner-app-2-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service s3-asset-scanner-app-2.zip file to S3 (2.27 KB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - s3-asset-scanner-app-2-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ScannerLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ScannerLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ScannerLogGroup
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleCustomResourcesLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ScannerLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - ScannerLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - CustomDashresourceDashexistingDashs3LambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - ScannerLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ScannerLambdaVersioneApviq3i7hGfN1vukw8srmJo9fJueqjd0L2VNHoNrVw
CloudFormation - CREATE_IN_PROGRESS - Custom::S3 - ScannerCustomS31
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - ScannerLambdaVersioneApviq3i7hGfN1vukw8srmJo9fJueqjd0L2VNHoNrVw
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - ScannerLambdaVersioneApviq3i7hGfN1vukw8srmJo9fJueqjd0L2VNHoNrVw
Pulling docker image gitlab/gitlab-runner-helper:x86_64-05161b14 ...
ERROR: Job failed: execution took longer than 1h0m0s seconds
```
Similar or dependent issues:

- None that I know of
