### ISSUE TITLE
Cannot resolve a variable that contains non ascii character as a default value

### ISSUE THREAD

**Issue by kdnakt** [serverless/serverless#6997]
- # Bug Report

## Description

1. What did you do?
I'm using serverless framework version `1.58.0`, and I tried `sls print` command with a `serverless.yml` with following lines

```
custom:
  stage: ${opt:stage, 'develop'}
  myname: ${opt:myname, 'システム管理者'}
  # `システム管理者` means `System Administrator` in Japanese.
  
functions:
  hello:
    handler: handler.hello
    environment:
      stage: ${self:custom.stage}
      myname: ${self:custom.myname}
```

1. What happened?
And the result is:
```
custom:
  stage: develop
  myname: '${opt:myname, ''システム管理者''}'
functions:
  hello:
    handler: handler.hello
    environment:
      stage: develop
      myname: '${opt:myname, ''システム管理者''}'
```

1. What should've happened?
I want it to be as follows:
```
custom:
  stage: develop
  myname: システム管理者
functions:
  hello:
    handler: handler.hello
    environment:
      stage: develop
      myname: システム管理者
```

1. What's the content of your `serverless.yml` file?
Whole file is here:
```
service: japanese-test

provider:
  name: aws
  runtime: python3.8
  memorySize: 256

custom:
  stage: ${opt:stage, 'develop'}
  myname: ${opt:myname, 'システム管理者'}
  
functions:
  hello:
    handler: handler.hello
    environment:
      stage: ${self:custom.stage}
      myname: ${self:custom.myname}
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
There seems to be nothing special.
The result is:
```
$ SLS_DEBUG=* sls print
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
service: japanese-test
provider:
  name: aws
  runtime: python3.8
  memorySize: 256
custom:
  stage: develop
  myname: '${opt:myname, ''システム管理者''}'
functions:
  hello:
    handler: handler.hello
    environment:
      stage: develop
      myname: '${opt:myname, ''システム管理者''}'
    events: []
    name: japanese-test-dev-hello
```

Similar or dependent issues:

- #4624
