### ISSUE TITLE
AWS Lambda Destination

### ISSUE THREAD

**Issue by bluebeel** [serverless/serverless#7007]
# AWS Lambda Destination

## Description

[AWS Lambda Destinations](https://aws.amazon.com/fr/blogs/compute/introducing-aws-lambda-destinations/) for asynchronous invocations. This is a feature that provides visibility into Lambda function invocations and routes the execution results to AWS services, simplifying event-driven applications and reducing code complexity.

I have already simply tried to add a cloudformation resource: 

```
functions:
  hello:
    handler: src/hello.handler
    events:
      - sqs:
          batchSize: 1
          arn: ${arn}

resources: # CloudFormation template syntax
  Resources:
    HelloLambdaFunction:
      Type: AWS::Lambda::EventInvokeConfig
      Properties:
          FunctionName: "hello"
          Qualifier: "$LATEST"
          MaximumEventAgeInSeconds: 600
          MaximumRetryAttempts: 0
          DestinationConfig:
              OnSuccess:
                  Destination: ${arn}
              OnFailure:
                  Destination: ${arn}
```

But i got this error: `Update of resource type is not permitted. The new template modifies resource type of the following resources: [HelloLambdaFunction]`

Yours sincerely.
