### ISSUE TITLE
Warning when using `nodejs12.x` as runtime value

### ISSUE THREAD

**Issue by isotopeee** [serverless/serverless#7011]
# Bug Report

## Description

1. What did you do?
I've used `nodejs12.x` as the `runtime` value and run `sls deploy`. I've already upgraded to the latest `serverless` version `1.58.0`

1. What happened?
I'm getting a warning when running `sls deploy`:
![image](https://user-images.githubusercontent.com/17417116/69642049-26326180-109c-11ea-9d37-48e3d46685f6.png)

1. What should've happened?
Since on `serverless@1.58.0`, the default runtime is `nodejs12.x`, I assume the said runtime shouldn't raise a warning.

1. What's the content of your `serverless.yml` file?
```yml
# more config above
provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs12.x
  apiKeys:
    - ${self:provider.stage}-${self:service.name}-developer-key
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
# more config below
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
I haven't tried this step.

Similar or dependent issues:
