### ISSUE TITLE
AWS Now Supports Max Retry Attempts

### ISSUE THREAD

**Issue by Gerst20051** [serverless/serverless#7012]
Add support for the new lambda config option `MaximumRetryAttempts`.

Retry attempts – The number of times Lambda retries when the function returns an error, between 0 and 2.

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-max-retry-attempts-event-age-asynchronous-invocations/

**Comment by medikoo** [comment]
Thanks @Gerst20051 We definitely should support that. Any help would be appreciated

**Comment by keithalpichi** [comment]
Hey @Gerst20051. If you don't plan to implement this I'd like to try to take a stab at it.

**Comment by medikoo** [comment]
@keithalpichi Thank you!

**Comment by avinasherupaka** [comment]
Please check this out, this PR can fix this issue https://github.com/serverless/serverless/pull/7040

**Comment by Gerst20051** [comment]
@avinasherupaka I think streams handle this differently than lambdas. The only possible values, in this case, are `0, 1, or 2`.

**Comment by edenporan** [comment]
I don't understand why this issue is closed. I don't see a way to control MaximumRetryAttempts for anything other than streams

**Comment by dangreaves** [comment]
@medikoo Looks like this shouldn't have been closed by the attached MR as it only adds support for using `MaximumRetryAttempts` in the stream event (as opposed to all events).

**Comment by medikoo** [comment]
Reopenning, as indeed #7040 didn't address this request specifically

**Comment by mskg** [comment]
You can easily do this with a custom resource

```
   XXXAsyncConfig:
      Type: AWS::Lambda::EventInvokeConfig
      Properties:
        FunctionName:
          Ref: XXXLambdaFunction
        MaximumRetryAttempts: 0
        Qualifier: $LATEST
```
