### ISSUE TITLE
Stream permissions

### ISSUE THREAD

**Issue by evheniy** [serverless/serverless#7018]
If I have more than 1 dynamodb stream per serverless.yml each function has permissions for all streams:

````
functions:
  test1:
    handler: test1.handler
    tags:
      type: test
    events:
      - stream: "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/test1/stream/timestamp"

  test2:
    handler: test2.handler
    tags:
      type: test
    events:
      - stream: "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/test2/stream/timestamp"
````
And results in aws console:

````
Lambda -> Functions -> test1

Resource: Actions

arn:aws:dynamodb:region:accountId:table/test1/stream/timestamp:
Allow: dynamodb:GetRecords
Allow: dynamodb:GetShardIterator
Allow: dynamodb:DescribeStream
Allow: dynamodb:ListStreams

arn:aws:dynamodb:region:accountId:table/test2/stream/timestamp:
Allow: dynamodb:GetRecords
Allow: dynamodb:GetShardIterator
Allow: dynamodb:DescribeStream
Allow: dynamodb:ListStreams

````

Each function should have only own permissions. It's a good practice. 
success Installed "serverless@1.58.0" with binaries...
