### ISSUE TITLE
NoClassDefFoundError: AWSCredentials when executing Java lambda function with dependencies provided as "Layers" (java/lib)

### ISSUE THREAD

**Issue by distributev** [serverless/serverless#7020]
# Bug Report

## Description

1. What did you do?

I'm trying to execute a Java lambda which has its dependencies provided in a zip file (all deps are in java/lib folder) 

1. What happened?

I get  java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials

![image](https://user-images.githubusercontent.com/19224635/69727650-40635280-1123-11ea-94b5-b65164674675.png)

1. What should've happened?

Should have worked.

1. What's the content of your `serverless.yml` file?
```
service: service-name

frameworkVersion: '>=1.2.0 <2.0.0'

app: app-name
org: org-name

provider:
  name: aws
  runtime: java8
  region: us-east-1

package:
  artifact: target/jar-name.jar

functions:
  work:
    handler: com.package.name.Handler
    events:
      - http:
          path: /job/{id}
          method: get
          cors: true
      - http:
          path: /job/{id}/{undo}
          method: get
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:624139199278:layer:00-layer-name:1
```
Inside pom.xml I have

```
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-lambda-java-core</artifactId>
	<version>${aws-lambda-java-core.version}</version>
</dependency>
			
<dependency>
		<groupId>com.amazonaws</groupId>
		<artifactId>aws-java-sdk-s3</artifactId>
		<version>${aws-java-sdk.version}</version>
</dependency>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/dependencies-layer/java/lib</outputDirectory>
							<includeScope>runtime</includeScope>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<finalName>${project.artifactId}-dependencies</finalName>
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>../src/main/resources/assembly-dependencies-layer.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>

```
![image](https://user-images.githubusercontent.com/19224635/69727548-101bb400-1123-11ea-93cb-139be5ea5d2a.png)

This is how the "dependencies" zip file looks inside

![image](https://user-images.githubusercontent.com/19224635/69727299-8ff54e80-1122-11ea-8861-679c3b624215.png)

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Everything works fine when I run serverless deploy

Similar or dependent issues:

I searched but could not find similar issue.
