### ISSUE TITLE
serverless invoke local fails with NoClassDefFoundError: when the dependencies are provided in a separate zip file.

### ISSUE THREAD

**Issue by distributev** [serverless/serverless#7021]
# Bug Report

## Description

1. What did you do?

I tried to execute serverless invoke local --function work for a java lambda function where all the dependencies are uploaded in a zip file as "Layers" - the zip file respects the java/lib folder conventions and the log4j2 jars are provided.

I do not use the maven-shade plugin as I need to provide the dependencies in a separate zip file (serverless deploy was always failing before when using maven-shade since it was trying to upload the fat 100MB jar each time - now the serverless deploy commands always works since the jar file is only 100kb - unfortunately I get the below errors when doing like that)

1. What happened?

![image](https://user-images.githubusercontent.com/19224635/69737678-187cea80-1135-11ea-8d4c-7edf77a3c7f4.png)

1. What should've happened?

Should have worked.

1. What's the content of your `serverless.yml` file?

```
service: service-name

frameworkVersion: '>=1.2.0 <2.0.0'

app: app-name
org: org-name

provider:
  name: aws
  runtime: java8
  region: us-east-1

package:
  artifact: target/jar-name.jar

functions:
  work:
    handler: com.package.name.Handler
    events:
      - http:
          path: /job/{id}
          method: get
          cors: true
      - http:
          path: /job/{id}/{undo}
          method: get
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:624139199278:layer:00-layer-name:1
```
Inside pom.xml I have

```
<dependency>
	<groupId>com.amazonaws</groupId>
	<artifactId>aws-lambda-java-core</artifactId>
	<version>${aws-lambda-java-core.version}</version>
</dependency>
			
<dependency>
		<groupId>com.amazonaws</groupId>
		<artifactId>aws-java-sdk-s3</artifactId>
		<version>${aws-java-sdk.version}</version>
</dependency>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/dependencies-layer/java/lib</outputDirectory>
							<includeScope>runtime</includeScope>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<finalName>${project.artifactId}-dependencies</finalName>
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>../src/main/resources/assembly-dependencies-layer.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>

```
![image](https://user-images.githubusercontent.com/19224635/69727548-101bb400-1123-11ea-93cb-139be5ea5d2a.png)

This is how the "dependencies" zip file looks inside

![image](https://user-images.githubusercontent.com/19224635/69737932-8de8bb00-1135-11ea-9063-8c7a88e7ced5.png)
