### ISSUE TITLE
WebsocketsDeploymentStage - The following context variables are not supported: [$context.status]

### ISSUE THREAD

**Issue by leclercb** [serverless/serverless#7027]
# Bug Report

## Description

1. What did you do?

Our application is deploying fine since months, we made a minor change in the code (100% sure this is not linked, we even reverted it and re-deployed) and tried to deploy the application.

It was still working 6 days ago, with the same code, the same config, the same version of serverless (1.58.0).

1. What happened?

Now it suddenly fails with:

```
An error occurred: WebsocketsDeploymentStage - The following context variables are not supported: [$context.status] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 1dbfbe25-2faf-4359-ac74-6162e477a5a5).
```

1. What should've happened?

Successfull deployment, nothing has change in the configuration, nothing about websockets which were working fine for months till now. No trace of "$context.status" anywhere in our code.

1. What's the content of your `serverless.yml` file?

```
service: xyz-server
app: xyz-server
tenant: abc

custom:
  ...
  dynamodb:
    stages:
      - local
    start:
      migrate: true
  serverless-offline:
    port: 2000
    websocketPort: 2001
  serverless-offline-ssm-provider:
    file: .ssm
  warmup:
    enabled:
      - prod
    prewarm: true
    concurrency: 2
    tags:
      ...

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  websocketsApiRouteSelectionExpression: $request.body.action
  tags:
    ...
  logs:
    websocket: true
  environment:
    ...
  iamRoleStatements:
    ...

functions:
  server:
    handler: src/handlers/EsmServerHandler.handler
    memorySize: 512
    timeout: 6
    events:
      - http:
          path: /
          method: ANY
          cors: false
      - http:
          path: /{any+}
          method: ANY
          cors: false
  websocket:
    handler: src/handlers/EsmWebSocketHandler.handler
    memorySize: 256
    timeout: 6
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
    warmup:
      enabled: false
  cognitotrigger:
    handler: src/handlers/EsmCognitoTriggerHandler.handler
    memorySize: 256
    timeout: 6
    warmup:
      enabled: false

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-warmup
  - serverless-dynamodb-local
  - serverless-offline-ssm-provider
  - serverless-offline

package:
  exclude:
    - .dynamodb/**
    - aws/**
    - build/**
    - coverage/**
    - data/**
    - dist/**
    - lib/**
    - postman/**
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

serverless@1.58.0

```
Serverless: Operation failed! 
Serverless: View the full error output: [...]
Serverless: Publishing service to the Serverless Dashboard... 
Serverless: Successfully published your service to the Serverless Dashboard: [...]
  
  Serverless Error --------------------------------------- 
  
  An error occurred: WebsocketsDeploymentStage - The following context variables are not supported: [$context.status] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 1dbfbe25-2faf-4359-ac74-6162e477a5a5). 
  
  Get Support -------------------------------------------- 
     Docs:          docs.serverless.com 
     Bugs:          github.com/serverless/serverless/issues 
     Issues:        forum.serverless.com 
  
  Your Environment Information --------------------------- 
     Operating System:          linux 
     Node Version:              10.16.3 
     Framework Version:         1.57.0 
     Plugin Version:            3.2.3 
     SDK Version:               2.0.4 
     Components Core Version:   1.0.0 
     Components CLI Version:    1.4.0 
```
