### ISSUE TITLE
Cannot activate API gateway logs for shared API gateway 

### ISSUE THREAD

**Issue by tinexw** [serverless/serverless#7036]
# Bug Report

## Description
The API gateway log settings are not applied when using a shared API gateway as described [here](https://serverless.com/framework/docs/providers/aws/events/apigateway#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources).

1. What did you do?
- Created `serverless.yml` my copying the example from the [docs](https://serverless.com/framework/docs/providers/aws/events/apigateway#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources) and added 
```
logs:
    restApi: true
```
- Ran `sls deploy`
1. What happened?
- API Gateway logs are not enabled.
1. What should've happened?
- API Gateway logs should have been enabled.
1. What's the content of your `serverless.yml` file?
```
service: my-api
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  logs:
    restApi: true
resources:
  Resources:
    MyApiGW:
      Type: 'AWS::ApiGateway::RestApi'
      Properties:
        Name: MyApiGW
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: MyApiGW
      Export:
        Name: MyApiGateway-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        'Fn::GetAtt':
        - MyApiGW
        - RootResourceId
      Export:
        Name: MyApiGateway-rootResourceId
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
No difference. However, if I add a http function I can see that the AWS CLI is used to set the log settings. If no http function is defined, [updateStage.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js) is not called.
I tried to remove [this](https://github.com/serverless/serverless/blob/cd93739393c236be1bec61c4e51e1f848005bb41/lib/plugins/aws/package/compile/events/apiGateway/index.js#L78) line, but then I get
```
Serverless: [AWS apigateway 200 0.202s 0 retries] getRestApis({ position: undefined, limit: 500 })
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Rest API id could not be resolved.
  This might be caused by a custom API Gateway configuration.
  
  In given setup stage specific options such as `tracing`, `logs` and `tags` are not supported.
```
I guess as a workaround I can define my own resources. However, I would gladly submit a PR to allow setting this with the log level properties.

Similar or dependent issues:

- There are several issues on API gateway logs but I did not find the exact same one.

**Comment by medikoo** [comment]
Will be fixed with: https://github.com/serverless/serverless/pull/7034

Note, that for shared APIGW, logs need to be configured in place in which APIGW is configured (and not in services which refer to it)

**Comment by tinexw** [comment]
> 
> Note, that for shared APIGW, logs need to be configured in place in which APIGW is configured (and not in services which refer to it)

Yes, that’s what I was trying, see the example above.

**Comment by medikoo** [comment]
> Yes, that’s what I was trying, see the example above.

Sorry (I was fast reading) indeed it's a different case, and for your case, bug is here: https://github.com/serverless/serverless/blob/0b3f0213e7149456ccfa56ea1b13de34d362fc4c/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L101

Let me prepare PR

**Comment by tinexw** [comment]
Hi @medikoo , thanks for supplying this fix so soon. However, it's still not working.

There is still the issue, that [updateStage.js](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js) is not called unless I remove [this](https://github.com/serverless/serverless/blob/cd93739393c236be1bec61c4e51e1f848005bb41/lib/plugins/aws/package/compile/events/apiGateway/index.js#L78) line. I can submit a PR that removed the line but I'm not sure of the implications because it was explicitly added by [this commit](https://github.com/serverless/serverless/commit/98ef25bce192d5dcb054043ac363d75e8733a933#diff-a053d5364c6f7aa212359136bffe6880.).

Even after removing the line, it does not immediately work. The issue is that initially there is no stage - so the log settings cannot be applied. If I deploy the API gateway, then the first service and then the API gateway again, it works. 

Do you prefer if I create a new issue for this or is it fine to track it in here?

**Comment by medikoo** [comment]
@tinexw indeed, it shouldn't be like that. It's updateStage logic that should eventually discard changes if it finds no API GW configured and sees no http events.

PR to fix it, is very welcome

**Comment by lunascat** [comment]
Using following `serverless.yml` file, I still run into the same issue, that API gateway logs are disabled (for a shared API gateway):

```
service: nodejs-example

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  logRetentionInDays: 30
  apiGateway:
    restApiId: !Ref RestApi
    restApiRootResourceId: !Ref RestApiRoot
    metrics: true
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: true
      level: INFO
      accessLogging: true
      format: 'requestId: $context.requestId'

functions:
  hello:
    handler: handler.hello
    description: This is a test lambda
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:
    RestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: nodejs-example
        Description: API GW to test enabling logging, tracing and metrics

    RestApiRoot:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref RestApi
        ParentId: !GetAtt RestApi.RootResourceId
        PathPart: "test"
```

Am I missing something here? If I delete the custom API GW and let serverless create the GW itself, the logging is enabled as expected.

**Comment by medikoo** [comment]
@lunascat Logging should be set in context of stack with which API Gateway is created. In your case you're referencing an external stack, and in such case Framework does not attempt to tweak logging settings (as that's just not safe).

Issue is that Framework doesn't crash with meaningful error on such configuration. if you wish to see that, please open a new bug report

**Comment by lunascat** [comment]
@medikoo Thanks for the quick reply.

The API Gateway is created within the same stack (see Resources part at the end). For me, it looks like the same case as in the original example above, except for the http function part (and the restApi reference in provider.apiGateway). What is the difference from serverless' point of view?

**Comment by medikoo** [comment]
> The API Gateway is created within the same stack 

Then please remove `apiGateway.restApiId` setting. This is intended to point the API's configured externally only

**Comment by lunascat** [comment]
So, if I remove `apiGateway.restApiId` and the http function and move it to a different stack, using the shared API Gateway, the log settings are still not enabled.
In fact our scenario looks a bit more complicated, with a [shared authorizer](https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#easiest-and-cicd-friendly-example-of-using-shared-api-gateway-and-api-resources):

<details>
  <summary>shared api-gateway serverless.yml</summary>

```yaml

service: nodejs-auth-example
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  logRetentionInDays: 30
  apiGateway:
    metrics: true
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: true

functions:
  authorizer:
    handler: src/functions/authorize.handler
    description: Lambda authorizer for the api gateway.

resources:
  Resources:
    RestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: nodejs-auth-example
        Description: API GW with auth to test enabling logging, tracing and metrics

    RestApiRoot:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: !Ref RestApi
        ParentId: !GetAtt RestApi.RootResourceId
        PathPart: "test"

    ApiAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 3600
        IdentitySource: method.request.header.Authorization
        Name: authorizer
        RestApiId: !Ref RestApi
        Type: TOKEN
        AuthorizerUri: 
          !Join [ '', [ arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/, !GetAtt AuthorizerLambdaFunction.Arn, /invocations ] ]
    
    ApiAuthorizerPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt AuthorizerLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: apigateway.amazonaws.com

  Outputs:
    RestApiId:
      Value: !Ref RestApi
      Export: { Name: "api-gw:RestApiId" }

    RestApiRoot:
      Value: !Ref RestApiRoot
      Export: { Name: "api-gw:RestApiRootId" }
                    
    AuthorizerId:
      Value: !Ref ApiAuthorizer
      Export: { Name: "api-gw:ApiAuthorizer"}
```

</details>

<details>
  <summary>service serverless.yml</summary>

```yaml
service: hello
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  apiGateway:
    restApiId: ${self:custom.restApiId}
    restApiRootResourceId: ${self:custom.restApiRootId}

custom:
  restApiId: !ImportValue api-gw:RestApiId
  restApiRootId: !ImportValue api-gw:RestApiRootId
  authorizerId: !ImportValue api-gw:ApiAuthorizer

functions:
  hello:
    handler: src/functions/handler.hello
    description: This is a test lambda to test secured access to API Gateway methods.
    events:
      - http:
          path: /hello
          method: get
          authorizer: 
            type: CUSTOM 
            authorizerId: ${self:custom.authorizerId}
```

</details>

Are we supposed to define a custom log ressource in this case, because it's also a custom API Gateway, not managed by serverless?

**Comment by medikoo** [comment]
@lunascat If I see correctly you miss `AWS::ApiGateway::Deployment` resource configuration in first stack.  Once it's defined, then logging should be turned on.

Note that logging can only be configured on a _deployed_ API Gateway stage (we need a deployment resource there)

**Comment by lunascat** [comment]
@medikoo Thanks, that works like a charm!

For reference, here's the Deployment ressource definition:
```yaml
plugins:
  - serverless-plugin-bind-deployment-id

resources:
  Resources:
    RestApi:
      ...

    RestApiRoot:
      ...

    __deployment__:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId: !Ref RestApi
```
