### ISSUE TITLE
Can't access CF outputs using documented variable syntax

### ISSUE THREAD

**Issue by kiddrew** [serverless/serverless#7037]
# Bug Report

## Description

I posted on the forums too, but I'm fairly certain this is a bug. I can output CF values from a stack just fine, but using the ${output} variable syntax does not work. I checked the code - there's no handler for the "output" variable, so the parser throws an error.

1. What did you do?
I used the documented output variable to access a CF Output. The documentation is here:

https://serverless.com/framework/docs/dashboard/output-variables/

2. What happened?

I got an error message from the parser. The output variable is not valid.

3. What should've happened?
According to the docs, that should have accessed the value I exported from my other stack

4. What's the content of your `serverless.yml` file?

```
service: my-service
app: my-app
org: my-org

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  region: us-east-1

custom:
  elasticache:
    cache_instance_size:
      dev: cache.t2.micro
      prod: cache.r5.large

resources:
  Resources:
    ServerlessStorageSecurityGroup:
      DependsOn: VPC
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Ingress for Redis Cluster
        VpcId: ${output:${self:app}-network-${self:provider.stage}.VpcId}
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '6379'
          ToPort: '6379'
          SourceSecurityGroupId: ${output:${self:app}-network-${self:provider.stage}.ServerlessSecurityGroupId}
    ServerlessCacheSubnetGroup:
      Type: AWS::ElastiCache::SubnetGroup
      Properties:
        Description: "Cache Subnet Group"
        SubnetIds: ${output:${self:app}-network-${self:provider.stage}.PrivateSubnetAId}
    ElasticCacheCluster:
      DependsOn: ServerlessStorageSecurityGroup
      Type: AWS::ElastiCache::CacheCluster
      Properties:
        ClusterName: ${self:service}-${self:provider.stage}-cluster
        AutoMinorVersionUpgrade: true
        Engine: redis
        CacheNodeType: ${self:custom.elasticache.cache_instance_size.${self:provider.stage}}
        NumCacheNodes: 1
        VpcSecurityGroupIds:
        - "Fn::GetAtt": ServerlessStorageSecurityGroup.GroupId
        CacheSubnetGroupName:
          Ref: ServerlessCacheSubnetGroup

outputs:
  RedisHost: {"Fn::GetAtt": [ElasticCacheCluster, RedisEndpoint.Address]}
```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
platform-sdk fetching: POST https://api.serverless.com/core/tenants/knownintent/applications/my-app/profileValue

  Serverless Error ---------------------------------------

  ServerlessError: Invalid variable reference syntax for variable output:my-app-network-dev.VpcId. You can only reference env vars, options, & files. You can check our docs for more info.
      at Variables.getValueFromSource (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:554:32)
      at Variables.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/lib/variables.js:48:19)
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/variables.js:3:103)
      at _next (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/variables.js:5:194)
      at /usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/variables.js:5:364
      at new Promise (<anonymous>)
      at Variables.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/variables.js:5:97)
      at Variables.getValueFromSource (/usr/local/lib/node_modules/serverless/node_modules/@serverless/lib/variables.js:9:3)
      at Variables.splitAndGet (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:400:17)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:337:41
      at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
      at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
      at Variables.populateMatches (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:337:14)
      at Variables.populateValue (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:368:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:250:12
      at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
      at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
      at Variables.populateVariables (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:249:14)
      at Variables.populateObjectImpl (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:282:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:287:12
  From previous event:
      at Variables.populateObjectImpl (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:286:65)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:163:16
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:162:10
      at Variables.initialCall (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:67:12)
      at Variables.populateService (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:160:17)
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:103:27)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:60:28
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:157:23)
  From previous event:
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:60:6
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:46:39)
      at Module._compile (internal/modules/cjs/loader.js:936:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
      at Module.load (internal/modules/cjs/loader.js:790:32)
      at Function.Module._load (internal/modules/cjs/loader.js:703:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
      at internal/main/run_main_module.js:17:11

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.10.0
     Framework Version:         1.51.0
     Plugin Version:            1.3.11
     SDK Version:               2.2.1

```

**Comment by pmuens** [comment]
Hey @kiddrew thanks for opening :+1:

Are you signed-into the Serverless Framework Dashboard since `outputs` is pulling from the Dashboards store.

If you want to use raw CloudFormation Outputs you might want to include them in your `resources` definition like this:

```yaml
resources:
  Resources:
    ...
  Outputs:
    ... # <-- Define the Outputs here
```
