### ISSUE TITLE
Invalid format in AccessLogSettings produced for websocket Api GW stage

### ISSUE THREAD

**Issue by henhal** [serverless/serverless#7038]
# Bug Report

## Description

I have a websocket API gateway which has been deployed multiple times successfully. Now, all of a sudden the stack fails due to the `Format` of the `AccessLogSettings` in my `AWS::ApiGatewayV2::Stage` resource called `WebsocketsDeploymentStage` including `$context.status` which is not a valid context variable for websocket API:s, only REST API:s.
I don't know if this is due to a recent change in SLS or in AWS, but this API was deployed many times before without issues.

`The following context variables are not supported: [$context.status] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: aa19bd81-9ef4-4182-89cd-29ae21d46fa1)
`

My serverless.yml file simply contains one or more functions with websocket events:

```
functions:
  MyWebSocketFunction:
    handler: websocket.handler
    events:
      - websocket:
          route: $connect 
```

This automatically causes SLS to create CF resources `WebsocketsDeploymentStage` etc:

```
  "WebsocketsDeploymentStage": {
      "Type": "AWS::ApiGatewayV2::Stage",
      "Properties": {
        "ApiId": {
          "Ref": "WebsocketsApi"
        },
        "DeploymentId": {
          "Ref": "WebsocketsDeployment1575366683940"
        },
        "StageName": "dev",
        "Description": "Serverless Websockets",
        "AccessLogSettings": {
          "DestinationArn": {
            "Fn::Sub": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${WebsocketsLogGroup}"
          },
          "Format": "$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] \"$context.eventType $context.routeKey $context.connectionId\" $context.status $context.requestId"
        },
        "DefaultRouteSettings": {
          "DataTraceEnabled": true,
          "LoggingLevel": "INFO"
        }
      }
    },
```

I managed to temporarily resolve this by overriding the `WebsocketsDeploymentStage` resource to override the `AccessLogSettings.Format` property and remove `$context.status` from the value:

```
resources:
  Resources:
    ...
    WebsocketsDeploymentStage:
      # Overriding faulty format generated by SLS
      Properties:
        AccessLogSettings:
          Format: "$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] \"$context.eventType $context.routeKey $context.connectionId\" $context.requestId"
```

 Then the stack was deployed just fine. But it seems like SLS is applying a default format string for the deployment stage which is not accepted by CF due to the use of the unsupported variable `$context.status`.

Similar or dependent issues:
