### ISSUE TITLE
Serverless invoke local plugin for aws provider seems to be broken after updating to 1.59

### ISSUE THREAD

**Issue by idealwebsolutions** [serverless/serverless#7050]
# Bug Report

## Description

1. What did you do?
**Upgraded serverless from 1.58 to 1.59 using npm global flag**
2. What happened?
**When attempting to invoke any function locally, the following error is thrown**
`TypeError:` Cannot read property 'accessKeyId' of null`

3. What should've happened?
**Runs a function locally without issue. Downgrading serverless back to 1.58 fixes the problem.**
4. What's the content of your `serverless.yml` file?
```yaml
service:
  name: live
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  subscribe:
    handler: src/handler.subscribe
    events:
      - http:
          method: post
          path: subscribe
  unsubscribe:
    handler: src/handler.unsubscribe
    events:
      - http:
          method: delete
          path: unsubscribe
```
5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke invoke:local
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'accessKeyId' of null
      at AwsInvokeLocal.loadEnvVars (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:133:27)
  From previous event:
      at Object.before:invoke:local:loadEnvVars [as hook] (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:33:12)
      at BbPromise.reduce (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:489:55)
  From previous event:
      at PluginManager.invoke (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:489:22)
      at getHooks.reduce.then (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:524:24)
  From previous event:
      at PluginManager.run (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/classes/PluginManager.js:524:8)
      at variables.populateService.then (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/Serverless.js:115:33)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:120:23)
  From previous event:
      at Serverless.run (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/lib/Serverless.js:102:74)
      at serverless.init.then (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/bin/serverless.js:72:30)
      at /home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /home/wk/Github/live/node_modules/graceful-fs/graceful-fs.js:57:14
      at /home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  From previous event:
      at initializeErrorReporter.then (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/bin/serverless.js:72:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:120:23)
  From previous event:
      at Object.<anonymous> (/home/wk/.nvm/versions/node/v10.15.3/lib/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (internal/modules/cjs/loader.js:701:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
      at Module.load (internal/modules/cjs/loader.js:600:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
      at Function.Module._load (internal/modules/cjs/loader.js:531:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.15.3
     Framework Version:         1.59.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

Similar or dependent issues: **N/A**
