### ISSUE TITLE
Serverless deploy creating an extra empty bucket after each deployment

### ISSUE THREAD

**Issue by rhlr** [serverless/serverless#7053]
Hi,

I'm using serverless to create various services on aws. Whenever I try to deploy a new service it creates an extra empty bucket.We've a usecase in which we need to create a lots of services         >100,000 and since `AWS` has a limit of 100 buckets it's getting difficult to create more services. Also the empty buckets are not getting deleted even manually. Here's my configuration:
```
service: ${opt:title}

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
   name: aws
  runtime: python3.7
  memorySize: ${opt:memory}
  deploymentBucket:
     name: mybucket-14mndqk7

functions:
  get:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: ${opt:path}
          method: ${opt:method}
```
