### ISSUE TITLE
After update to serverless version 1.58.0 to 1.59.0 deploy of function using AWS::Lambda::EventSourceMapping fails

### ISSUE THREAD

**Issue by gezb** [serverless/serverless#7055]
# Bug Report

## Description

When attempting to redeploy an updated function to AWS  using serverless version 1.59.0 the deploy fails at the CloudFormation step with an error around missing EventSourceMapping. Deploy of the same code with 1.58.0 works

1. What did you do?

Made a change to the Python source code of my serverless function with no other changes that would have changed the Cloudformation (except the location of the code) and attempted to update it using `sls deploy`

2. What happened?

The deploy fails when applying the CloudFormation with the following error 

Serverless Error --------------------------------------- 
  
  An error occurred: ApachelogloaderEventSourceMappingKinesisApacheLogs - The resource you requested does not exist. (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: cd6ae276-2455-4756-bf29-d343759905a3).

3. What should've happened?

The updated function should have deployed successfully (and does with Serverless version 1.58.0)

4. What's the content of your `serverless.yml` file?

```yaml
service: log-elasticsearch-load

provider:
  name: aws
  runtime: python3.6
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'research'}
  memorySize: 256
  timeout: 240
  logRetentionInDays: 14
  versionFunctions: false
  stackTags:
    Name: ${self:service.name}
    Description: Service to push log messages into ElasticSearch
    Owner: ${opt:owner}
    OwnerFunction: ${opt:ownerFunction}
    Customer: ${opt:customer}
  deploymentBucket:
    serverSideEncryption: AES256
    name: <bucket name>
  vpc:
    securityGroupIds:
    - ${ssm:lambda-default-securitygroup-id}
    subnetIds:
    - ${ssm:private-core-subnet-id1}
    - ${ssm:private-core-subnet-id2}
    - ${ssm:private-core-subnet-id3}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:DescribeParameters"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
        - "ssm:GetParameters"
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:ssm:'
            - ${self:provider.region}
            - ':'
            - Ref: 'AWS::AccountId'
            - ':parameter/*'
    - Effect: "Allow"
      Action:
        - "kms:Decrypt"
      Resource: ${ssm:kinesis-stream-kms-key}

plugins:
  - serverless-python-requirements

package:
  exclude:
    - venv/**
    - .vscode/**
    - .idea/**
    - node_modules/**
    - tests/**
    - requirements.txt
    - .pytest_cache/**
    - __pycache__/**

custom:
  pythonRequirements:
    zip: true
    noDeploy:
    - boto3
    - botocore
    - jmespath
    - python-dateutil
    - s3transfer
    - pytest
    - attrs
    - more-itertools
    - pluggy
    - py
    - setuptools
    - pip
    - six
    - docutils
    - pipdeptree
    - autopep8
    - pycodestyle
    - pylint
    - astroid
    - lazy-object-proxy
    - wrapt
    - colorama
    - isort
    - mccabe

functions:
  apachelogloader:
    handler: handler.handle
    name: ApacheLogsElasticSearchLoader
    description: Push log messages coming from Apache into ElasticSearch
    tags:
      Name: Apache Logs ElasticSearch Loader
      Service: Application Monitoring
      Role: Application
      Description: Push log messages coming from Apache into ElasticSearch
      Owner: ${opt:owner}
      OwnerFunction: ${opt:ownerFunction}
      Customer: ${opt:customer}
    events:
      - stream:
          arn: ${ssm:apache-logs-stream}
          batchSize: 300
          startingPosition: TRIM_HORIZON
          enabled: true
resources:
  Description: >
    Service to push log messages into ElasticSearch
```

5.  Other information

When doing a diff of the between the CloudFormation for the last successful and the failed deployment the only difference is the ParallelizationFactor of 1 

    "ApachelogloaderEventSourceMappingKinesisApacheLogs": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": "IamRoleLambdaExecution",
      "Properties": {
        "BatchSize": 300,
      "ParallelizationFactor": 1,
        "EventSourceArn": "arn:aws:kinesis:eu-west-1:493661126902:stream/ApacheLogs",
        "FunctionName": {
          "Fn::GetAtt": [
            "ApachelogloaderLambdaFunction",
            "Arn"
          ]
        },
        "StartingPosition": "TRIM_HORIZON",
        "Enabled": "True"
      }
    }
