### ISSUE TITLE
Syntax Error after updating to Serverless 1.59.2 (2019-12-06) 

### ISSUE THREAD

**Issue by jdpy19** [serverless/serverless#7066]
# Bug Report

## Description
A simple health check function is not working as expected after updating to the most recent version of Serverless released this morning (2019-12-06) and installing Sequelize. Invoking the local function raises a Syntax error that seems to be traced to the serverless package. Running the function last night resulted in the expected 200 response; however, after updating serverless the build is not completed and function is not run. 

\* Disclaimer: This is my first bug report, feedback is greatly appreciated. 

1. What did you do?
  * I installed the latest version of serverless using the command:
    * `npm i -g serverless`
  * I installed sequelize using the command :
    * `npm install --save sequelize`
1. What happened?
  * I am now receiving an error when I try to run my health check 
    * `serverless invoke local --function healthCheck `
1. What should've happened?
  * I expected to receive a 200 response after a successful health check, I modified my function to do nothing but respond if the build succeeded. 

1. What's the content of your `serverless.yml` file?
```
service: sundaybudget-app-api

# Create an optimized package for our functions 
package:
  individually: true

custom:
  secrets: ${file(secrets.json)}

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  vpc: 
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds: 
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}
      - ${self:custom.secrets.SUBNET4_ID}
      - ${self:custom.secrets.SUBNET5_ID}
      - ${self:custom.secrets.SUBNET6_ID}
    region:
      - us-east-1
  iamRoleStatemetns:
    - Effect: "Allow"
      Action: 
        - "rds:*"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*" 
  environment: 
  # Database ENVS
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    RDS_HOSTNAME: ${self:custom.secrets.RDS_HOSTNAME}
    RDS_PORT: ${self:custom.secrets.RDS_PORT}
    RDS_DB_NAME: ${self:custom.secrets.RDS_DB_NAME}
    RDS_USERNAME: ${self:custom.secrets.RDS_USERNAME}
    RDS_PASSWORD: ${self:custom.secrets.RDS_PASSWORD}

functions:
  healthCheck:
    handler: goals.healthCheck
    events:
      - http:
        path: /
        method: get
        cors: true
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: DOTENV: Loading environment variables from .env:
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
 
  Syntax Error -------------------------------------------
 
  SyntaxError: Unexpected token } in JSON at position 537
  SyntaxError: Unexpected token } in JSON at position 537
      at JSON.parse (<anonymous>)
      at Object.parseJC [as parse] (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/json-cycle/cycle.js:136:28)
      at parse (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/utils/fs/parse.js:22:15)
      at readFileSync (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/utils/fs/readFileSync.js:8:10)
      at Utils.readFileSync (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Utils.js:84:12)
      at Variables.getValueFromFile (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:714:47)
      at Variables.getValueFromSource (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:565:17)
      at Variables.splitAndGet (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:434:17)
      at _.map.match (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:371:41)
      at arrayMap (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
      at Function.map (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
      at Variables.populateMatches (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:371:14)
      at Variables.populateValue (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:402:30)
      at Variables.getValueFromDeep (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:863:20)
      at Variables.getValueFromSource (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:565:17)
      at Variables.splitAndGet (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:434:17)
      at _.map.match (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:371:41)
      at arrayMap (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
      at Function.map (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
      at Variables.populateMatches (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:371:14)
      at Variables.populateValue (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:402:30)
      at BbPromise.all.then.then.result (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:407:23)
      at tryCatcher (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:673:18)
      at PromiseArray._resolve (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:127:19)
      at PromiseArray._promiseFulfilled (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise_array.js:145:14)
      at Promise._settlePromise (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:609:26)
      at Promise._fulfillPromises (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:704:14)
      at Promise._settlePromises (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:730:18)
      at _drainQueueStep (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Variables.populateValue (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:405:8)
      at requiredConfigs.map.config (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:168:16)
      at Array.map (<anonymous>)
      at disableDepedentServices (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:167:48)
      at Variables.disableDepedentServices (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:125:12)
      at Variables.prepopulateService (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:166:19)
      at initialCall (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:195:12)
      at Variables.initialCall (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:100:12)
      at Variables.populateService (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/classes/Variables.js:194:17)
      at Serverless.run (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/lib/Serverless.js:102:27)
      at serverless.init.then (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/bin/serverless.js:72:30)
      at /home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /home/ec2-user/environment/sundaybudget-app-api/node_modules/graceful-fs/graceful-fs.js:57:14
      at /home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
  From previous event:
      at initializeErrorReporter.then (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/bin/serverless.js:72:8)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.17.0/lib/node_modules/serverless/bin/serverless.js:61:4)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
      at startup (internal/bootstrap/node.js:283:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.17.0
     Framework Version:         1.59.2
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

Similar or dependent issues:

- #12345
