### ISSUE TITLE
How to use Elastic search exported domain name in appsync datasource

### ISSUE THREAD

**Issue by sidrazia** [serverless/serverless#7075]
I have defined and exported elastic search end point in serverless.yml as below:
```
Resources:
  ExportSearch:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: 6.4
      DomainName: export-search
 #Some other properties
Outputs:
  ExportSearchDomainEndpoint:
    Value:
       Fn::GetAtt:
        - ExportSearch
        - DomainEndpoint
    Export:
      Name: ExportSearchDomainEndpoint
```

Now I want to use this in appsync:
```
custom:
  appSync:
    name: ${self:provider.stackName}
    dataSources:
      - type: AMAZON_ELASTICSEARCH
        name: IndexName
        description: 'Index Name'
        config:
          endpoint: !ImportValue ExportSearchDomainEndpoint
```

However, its throwing error when I try deploying appsync:
```
  Serverless Error ---------------------------------------
 
  An error occurred: GraphQlDsIndexName - Property validation failure: [Value for property {/ElasticsearchConfig/Endpoint} does not match pattern {(?i)https?://.*$}].
```
I have latest serverless version deployed:

```
$ serverless --version
Framework Core: 1.59.3
Plugin: 3.2.5
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0
```

**Comment by sidrazia** [comment]
Does anyone get chance to see?

**Comment by hidekazu-karino** [comment]
DomainEndPoint is the domain-specific endpoint and this lacks prefix http:// or https:// (see [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#aws-resource-elasticsearch-domain-return-values)) Endpoint of AppSync's datasource must match pattern {(?i)https?://.*$} so using Fn::Join can help you.

```yaml
custom:
  appSync:
    name: ${self:provider.stackName}
    dataSources:
      - type: AMAZON_ELASTICSEARCH
        name: IndexName
        description: 'Index Name'
        config:
          endpoint: 
            Fn::Join:
            - ''
            - - 'https://'
            - - !ImportValue ExportSearchDomainEndpoint
          
```
