### ISSUE TITLE
Cannot read property 'X-Amzn-Trace-Id' of null - Testing Serverless Framework Pro wrapped Lambda function in API Gateway Console

### ISSUE THREAD

**Issue by serverlessguru** [serverless/serverless#7096]
# Bug Report

## Description
Cannot read property 'X-Amzn-Trace-Id' of null. This is caused by testing a Serverless Framework Pro wrapped Lambda function in API Gateway Console.

1. What did you do?
Deployed serverless framework API with single lambda function using the Serverless Framework Pro integration.
1. What happened?
All resources deployed properly. When testing the function in the API gateway console, it broke with the following error:
```
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'X-Amzn-Trace-Id' of null",
    "stack": [
        "TypeError: Cannot read property 'X-Amzn-Trace-Id' of null",
        "    at Runtime.handler (/var/task/serverless_sdk/index.js:9:87215)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
``` 
1. What should've happened?
It should not require that attribute if the API Gateway console doesn't support it, in their test request.
1. What's the content of your `serverless.yml` file?
```
org: xxxxx
app: xxxxxxxx
service: xxxxxx-auth-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}
  profile: ${opt:profile, "xxxxxxxx"}
functions:
  test:
    name: ${self:custom.base}-test
    handler: index.handler
    events:
      - http:
          path: /test
          method: ANY
          cors: true
custom:
  base: ${self:service}-${self:provider.stage}

# https://serverless.com/framework/docs/dashboard/output-variables/
outputs:
  ApiEndpoint:
    Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayRestApi
        - .execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}
  ApiId:
    Ref: ApiGatewayRestApi
  ApiResourceId:
    Fn::GetAtt:
    - ApiGatewayRestApi
    - RootResourceId
```
