### ISSUE TITLE
Access-Control-Allow-Methods being accumulated from previous definitions

### ISSUE THREAD

**Issue by bazaglia** [serverless/serverless#7098]
# Bug Report

## Description

When deploying to AWS setting custom cors, the `Access-Control-Allow-Methods` header is not being set correctly on preflight request. When cors value is to `true` this doesn't happen, so it's an issue only when cors settings are manually set.

Let's say we have a cors.yml file:

```yaml
cors:
  origins: ${file(./config/${self:provider.stage}.yml):cors.origins}
  headers:
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
  allowCredentials: true
```

And then, three functions with three different HTTP methods, being declared in the follolwing sequence in the serverless.yml file:

```yaml
functions:
  firstFunction:
    handler: src/functions/first/first.handler
    events:
      - http:
          method: post
          path: v1/first
          cors: ${file(./resources/cors.yml)}
          authorizer: ${self:custom.authorizer}

  secondFunction:
    handler: src/functions/second/second.handler
    events:
      - http:
          method: put
          path: v1/second
          cors: ${file(./resources/cors.yml)}
          authorizer: ${self:custom.authorizer}

  thirdFunction:
    handler: src/functions/third/third.handler
    events:
      - http:
          method: delete
          path: v1/third
          cors: ${file(./resources/cors.yml)}
          authorizer: ${self:custom.authorizer}

```

This is how Serverless Framework is generating the header mappings, which I can confirm navigating to OPTIONS inside the resource on AWS console and checking Header Mappings values inside the Integration Response section:

* `/v1/first`: 'OPTIONS,POST'
* `/v1/second`: 'OPTIONS,POST,PUT'
* `/v1/third`: 'OPTIONS,POST,PUT,DELETE'

As it is easy to conclude, serverless.yml is actually accumulating HTTP methods from previous functions and including them when setting the header for the next functions, following the same order as it is declared in serverless.yml. So for an endpoint which method is DELETE we're actually getting on preflight request `Access-Control-Allow-Methods` allowing POST and PUT as well.
