### ISSUE TITLE
VPC-LINK Connection Type - Gov Cloud - Expected ARN not valid

### ISSUE THREAD

**Issue by jostendorf** [serverless/serverless#7100]
I was following the example to setup a vpc link to a nlb endpoint.  The api gateway resources are created, but they are incorrect.  It is setup as a http connection type.  The steps to create are:

region: us-gov-west-1
type: regional

Example setup for vpc-link:
```
functions:
  searchFunction:
      handler: handler.handler (seems to be required)
      events:
          - http:
                path: search
               method: post
               integration: http-proxy
              connectionType: vpc-link
              connectionId: 'a0dqy8'
              cors: true
              request:
                  uri: http://nlb.api.com/search
                  method: post
```

Creates API Gatway with an integration type of HTTP.  It has the correct endpoint and the use HTTP Proxy integration checkbox is checked.  The method is correct.

I was expecting it to be setup as a VPC Link, however this did not happen.

Also on deploy I received this error:
Expected ARN arn:aws-us-gov:apigateway:us-gov-west-1::/restapis/pwpyvh5ul4/stages/dev for Stage dev on RestApi pwyvh5ul4, not arn:aws:apigateway:us-gov-west-1::/restapis/pwpyv5ul4/stages/dev
