### ISSUE TITLE
AWS Stack Rollback Configuration 

### ISSUE THREAD

**Issue by joshuanapoli** [serverless/serverless#7134]
# Feature Proposal
Set Rollback Configuration using AWS provider configuration.

## Description
I would like our serverless framework deployments to be safer. CloudFormation can automatically [monitor and roll back stack operations]. I just need the serverless framework to set the `RollbackConfiguration` in calls to createStack, [updateStack] or createChangeSet.

I think that it is natural to specify the configuration with a new `rollbackConfiguration` property in `serverless.yml`. For example:

```yaml
provider:
  name: aws
  rollbackConfiguration:
    MonitoringTimeInMinutes: 20
    RollbackTriggers:
      - Arn: arn:aws:cloudwatch:us-east-1:000000000000:alarm:health
        Type: AWS::CloudWatch::Alarm
      - Arn: arn:aws:cloudwatch:us-east-1:000000000000:alarm:latency
        Type: AWS::CloudWatch::Alarm
```

## Similar or dependent issues
[serverless-plugin-canary-deployments] serves a similar role. However, it only works with certain triggers (I need CloudFront triggers, which are not supported). The plugin only affects rollback of the lambda function version, which leaves us vulnerable to configuration problems in the CloudFormation template.

[monitor and roll back stack operations]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-rollback-triggers.html
[updateStack]: https://github.com/serverless/serverless/blob/f93b27bf684d9a14b1e67ec554a7719ca3628135/lib/plugins/aws/lib/updateStack.js#L54
[serverless-plugin-canary-deployments]: https://github.com/davidgf/serverless-plugin-canary-deployments
