### ISSUE TITLE
JSON Validation error: Detecting a JSON file as YAML

### ISSUE THREAD

**Issue by skysb** [serverless/serverless#7136]
I am trying to validate a JSON file with the template validator however it keeps giving me the following error:

"An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: YAML not well-formed. (line 2, column 31)"

However if I convert the JSON file into a YAML file and run the validation, it seems to be working right for me?

This was working around 24 hours ago and at some point it seems like it stopped validating?

The YAML file that gets validated correctly is:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application that uses the ASP.NET Core framework running
  in Amazon Lambda.
Resources:
  AspNetCoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ""
      Runtime: dotnetcore2.1
      CodeUri: ""
      MemorySize: 256
      Timeout: 30
      Role: 
      Policies:
      - AWSLambdaFullAccess
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
        RootResource:
          Type: Api
          Properties:
            Path: "/"
            Method: ANY
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
```
 

and the JSON file that fails is:

```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Transform": "AWS::Serverless-2016-10-31",
    "Description": "An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda.",
    "Resources": {
        "AspNetCoreFunction": {
            "Type": "AWS::Serverless::Function",
            "Properties": {
                "Handler": "",
                "Runtime": "dotnetcore2.1",
                "CodeUri": "",
                "MemorySize": 256,
                "Timeout": 30,
                "Role": null,
                "Policies": [
                    "AWSLambdaFullAccess"
                ],
                "Events": {
                    "ProxyResource": {
                        "Type": "Api",
                        "Properties": {
                            "Path": "/{proxy+}",
                            "Method": "ANY"
                        }
                    },
                    "RootResource": {
                        "Type": "Api",
                        "Properties": {
                            "Path": "/",
                            "Method": "ANY"
                        }
                    }
                }
            }
        }
    },
    "Outputs": {
        "ApiURL": {
            "Description": "API endpoint URL for Prod environment",
            "Value": {
                "Fn::Sub": "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
            }
        }
    }
}
```

The command I am using for this is:

`aws cloudformation validate-template --template-body file://serverless.template
`

As said before, the JSON validation for some reason was working correctly before and it is in fact the one that is provided as a blueprint for dotnet lambda function:

https://github.com/aws/aws-lambda-dotnet/blob/master/Blueprints/BlueprintDefinitions/Msbuild-NETCore_2_1/AspNetCoreWebApp/template/src/BlueprintBaseName.1/serverless.template

Is there anything I am missing out or any changes that have been carried out recently?

Cheers
Sky
