### ISSUE TITLE
Conflicting deployment error when updating AWS Lambdas with Provisioned Concurrency 

### ISSUE THREAD

**Issue by justinrcs** [serverless/serverless#7137]
Using Framework v1.60.3
Have an API deployed via serverless framework with valid ProvisionedConcurrency settings
Attempting to run an update results in AWS Cloudformation throwing the error:

> "A conflicting deployment is in progress"

This was the operation Cloudformation was trying to run:
`MethodXProvConcLambdaAlias`

No configuration changes were made in-between deployments.

Disabling provisionedConcurrency setting in configuration allows the API to be updated successfully

**Comment by justinrcs** [comment]
Update: it looks like this error occurs if Lambda versioning is enabled.
Including this config setting 

```
provider :
  versionFunctions: false

```
Allows the API to be updated

**Comment by JeffersonSchuler** [comment]
I am getting the same error with versionFunctions set to false. 

Also from 1.60.2 release notes:  Fix provisioned concurrency setup (closes #7059):
Fix provisioned concurrency configuration. Configure on alias, and not on version. Thanks to that it can work with versioning enabled.....

**Comment by jeffjen** [comment]
Also got this issue on `1.60.4`

From what I gathered, if my deployment only had one function to deploy, it will update correctly consistently; it will report this error if I have more than one function to deploy, leading me to believe that CodeDeploy is triggered more than once per deployment.

**Comment by medikoo** [comment]
@justinrcs thanks for report. I understand this happens when no changes to configuration are made, just version of framework is upgraded.

I think you should be able to recover by clearing a provisioned concurrency configuration for one deployment, and then repeating deployment with configuration brought back.

Note that provisioned concurrency support prior v1.60.2 was not really usable, It was set just for initial lambda deployment and any further updates to lambda were not covered (also eventual API Gateway endpoint was not triggering the provisioned lambda version).

So ideally it's best to remove old provisioned concurrency configration and set new one with 1.60.2+

**Comment by superandrew213** [comment]
@medikoo I deployed with`provisionedConcurrency` setting with v1.60.4.  This correclty set the provisioned concurrency on the lambda functions.

Then I redeployed again with no changes and get:

> "A conflicting deployment is in progress"

**Comment by justinrcs** [comment]
@medikoo Tried the following with Framework v.1.60.3:

1. brand new api with concurrency settings: successfully deploys
2. redeploy api after changing code: 

> A conflicting deployment is in progress.

3. redeploy api after disabling concurrency: successfully deploys
4. redeploy api after re-enabling concurrency: successfully deploys
5. redeploy api after changing code: 

> A conflicting deployment is in progress.

6. set versionFunctions to false and disable concurrency: successfully deploys
7. re-enable concurrency: successfully deploys
8. redeploy api after changing code: 

> A conflicting deployment is in progress.

**Comment by linjunpop** [comment]
Here's what I got with v1.60.4:

![image](https://user-images.githubusercontent.com/214616/71606740-ac1b5e00-2bae-11ea-9fee-b900001885fa.png)

**Comment by linjunpop** [comment]
## Root cause

After reaching to the AWS support, the provisioned concurrency works well if there's only one lambda with provisioned concurrency enabled.

If there are more than two lambdas on one service/stack, we will get the error `A conflicting deployment is in progress` while updating the `XXXLambdaFunctionProvConcLambdaAlias`.

## Workaround

Here's the workaround by setting an explicit `DependsOn` between lambda functions provisioned alias:

```yaml
resources:
  Resources:
    SlashCommandProvConcLambdaAlias:
      DependsOn:
        - "SlashCommandLambdaFunction" # generated by the Serverless framework
        - "MeetProvConcLambdaAlias" # Add this line
```

Full serverless template:

```yaml
provider:
  name: aws
  runtime: nodejs10.x
  profile: ${opt:aws_profile, 'slack-developer'}
  stage: ${self:custom.stage}
  region: ${opt:region}
  stackName: ${self:custom.resourcePrefix}

functions:
  meet:
    name: ${self:custom.resourcePrefix}-meet
    handler: src/lambda/meet.handleMeet
    provisionedConcurrency: 1
  slashCommand:
    name: ${self:custom.resourcePrefix}-slash-command
    handler: src/lambda/slash_command.handleCommand
    events:
      - http:
          path: /{brand}/slash-command
          method: post
    provisionedConcurrency: 1

resources:
  Resources:
    SlashCommandProvConcLambdaAlias:
      DependsOn:
        - "SlashCommandLambdaFunction"
        - "MeetProvConcLambdaAlias"
```

**Comment by justinrcs** [comment]
@linjunpop Thank you for documenting the workaround. I can confirm that this does indeed work.
In my test API I have 6 functions and managed to get the deployment working by doing:

```
resources:
  Resources:
    Function1ProvConcLambdaAlias:
      DependsOn:
         - "Function1LambdaFunction"
         - "Function2ProvConcLambdaAlias"
    Function2ProvConcLambdaAlias:
      DependsOn:
         - "Function2LambdaFunction"
         - "Function3ProvConcLambdaAlias"
    Function3ProvConcLambdaAlias:
      DependsOn:
         - "Function3LambdaFunction"
         - "Function4ProvConcLambdaAlias"
    Function4ProvConcLambdaAlias:
      DependsOn:
         - "Function4LambdaFunction"
         - "Function5ProvConcLambdaAlias"
    Function5ProvConcLambdaAlias:
      DependsOn:
         - "Function5LambdaFunction"
         - "Function6ProvConcLambdaAlias"
    Function6ProvConcLambdaAlias:
      DependsOn:
         - "Function6LambdaFunction"
```
