### ISSUE TITLE
different functions to different SQS trigger doesn't work

### ISSUE THREAD

**Issue by legrandjeremy** [serverless/serverless#7139]
# Bug Report

## Description

I tried to use serverless in order to use 2 different functions with related SQS trigger.

I used different version of serverless, from 1.55 to 1.60.4.

For example :

```
  function1:
    name: ${self:service}-function1
    description: "XXX"
    handler: src/function1.handler
    private: true
    memorySize: 128
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-1:11111111111111:sqs-identifier1
          batchSize: 1
          
  function2:
    name: ${self:service}-function2
    description: "XXX"
    handler: src/function2.handler
    private: true
    memorySize: 128
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-1:11111111111111:sqs-identifier2
          batchSize: 1
```

But the `function2` will be the trigger of `arn:aws:sqs:eu-west-1:11111111111111:sqs-identifier1` SQS instead `arn:aws:sqs:eu-west-1:11111111111111:sqs-identifier2` SQS.

If I deployed the functions separetly all worked as expected...

Hope it helps,

Jeremy
