### ISSUE TITLE
How to invoke a lambda edge function before to any apiGatewayRestApi function request?

### ISSUE THREAD

**Issue by josoroma** [serverless/serverless#7141]
I was wondering... How to invoke a lambda edge function before to any apiGatewayRestApi function request?

Thanks!

**Comment by FanFataL** [comment]
Here, you are creating cloudfront distribution with lambda-edge event. 
One of the limitation for lambda-edge functions is unable to use env variables and more like memory limit, executon time limit etc.
To handle env variables you cant use serverless-dotenv-plugin, instead of this you can use serverless-plugin-embedded-env-in-code.

I don't know what you want to achive but my advice is to use authorizer insted of cf-event.
https://serverless.com/framework/docs/providers/aws/events/apigateway/#http-endpoints-with-custom-authorizers

**Comment by josoroma** [comment]
@FanFataL thanks for your insights. This is what I am trying to achieve:

> Call a Lambda@Edge function before each API request. Invoke the "request" interceptor every time a request is sent to the origin.

I am creating the resource but I just can't make the edge function run before calling any other api-function.

I am getting a `Status Code: 403 Forbidden` response using the new Api Distribution URL as the new endpoint URL within my current `conf/amplify.js` file.

## Part of my current serverless.yml file

```
...
plugins:
...
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge' # Associate a Lambda with a CloudFront distribution
...

functions:

  # Call a Lambda@Edge function before each API request.
  # Invoke the "request" interceptor every time a request is sent to the origin.
  request:
    name: 'scb-courses-api-${self:custom.stage}-request-api-gateway-distribution'
    handler: course/interceptors/request.main
    memorySize: 128
    timeout: 1
    lambdaAtEdge:
      distribution: 'ApiGatewayDistribution'
      eventType: 'origin-request'

  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /courses
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: course/create.main
    events:
      - http:
          path: courses
          method: post
          cors: true
          authorizer: aws_iam

...

resources:
  ...
  # cloudfront invoke lambda@edge before API Gateway request
  - ${file(resources/api-gateway-distribution.yml)}
  ...
```

## The resource/distribution is currently created through resources/api-gateway-distribution.yml

```
  Resources:
    ApiGatewayDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: Api Gateway Distribution
          DefaultCacheBehavior:
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
              QueryString: false
          Enabled: true
          Origins:
            - Id: ApiGatewayOrigin
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api.us-east-1.amazonaws.com
              OriginPath: /development
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
```

## where `course/interceptors/request.js` is:

```
/**
 * https://serverless.com/framework/docs/providers/aws/events/cloudfront
 * https://serverless.com/blog/lambda-at-edge-support-added
 *
 * Add support for associating a Lambda function with a CloudFront distribution
 * to take advantage of the Lambda@Edge features of CloudFront:
 *
 *  - https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge
 *
 * Instead of calling the URL we did earlier (the API Gateway URL),
 * we are going to use a different URL which points to the CloudFront
 * Distribution:
 *
 *  - https://www.yld.io/blog/caching-in-with-cloudfront-using-serverless
 */

export const main = (event, context, callback) => {
  console.log('*====> event: ', event);

  const request = event.Records[0].cf.request;

  console.log('*====> request: ', request);

  callback(null, request);
};
```

## my current `conf/amplify.js` file, the one used by the frontend side:

```
export const amplifyConf = {
  Auth: {
    identityPoolId: '...',
    region: 'us-east-1',
    userPoolId: '...',
    userPoolWebClientId: '...',
  },
  API: {
    endpoints: [
      {
        name: 'ApiGatewayRestApi',
        endpoint: 'https://{ApiGatewayDistributionURL}.cloudfront.net',
      },
    ],
  },
};

export const storageSourceConf = {
  Storage: {
    bucket: '...',
    region: 'us-east-1',
    identityPoolId: '...',
  },
};
```

**Comment by FanFataL** [comment]
Hi @josoroma 

Try to add Authorization header to forwarded values to the behavior option in the cloudfront distribution settings. 
Optionaly you can add access controll headers if you want use xhr requests with the api.

```
ForwardedValues:
  QueryString: false
  Headers:
    - "Authorization"
    - "Access-Control-Request-Headers"
    - "Access-Control-Request-Method"
```

**Comment by josoroma** [comment]
@FanFataL thanks!

No luck yet!

![image](https://user-images.githubusercontent.com/69951/71688034-bd0dd000-2d64-11ea-9256-d725f0b40213.png)

```
Access to XMLHttpRequest at 'https://{ApiGateWayRestApi}.cloudfront.net/courses' from origin 'http://localhost:3002' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

```
functions:
  authreq:
    name: 'scb-courses-api-${self:custom.stage}-authreq'
    handler: course/interceptor/authreq.main
    memorySize: 128
    timeout: 1
    lambdaAtEdge:
      distribution: 'ApiGatewayDistribution'
      eventType: 'origin-request'

...
resources:
  ...
  - ${file(resources/api-gateway-distribution.yml)}
```

```
Resources:
  ApiGatewayDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Api Gateway Distribution
        DefaultCacheBehavior:
          TargetOriginId: ApiGatewayOrigin
          ViewerProtocolPolicy: 'redirect-to-https'
          DefaultTTL: 10
          ForwardedValues:
            QueryString: false
            Headers:
              - "Authorization"
              - "Access-Control-Request-Headers"
              - "Access-Control-Request-Method"
        Enabled: true
        Origins:
          - Id: ApiGatewayOrigin
            DomainName:
              Fn::Join:
                - "."
                - - Ref: ApiGatewayRestApi
                  - execute-api.us-east-1.amazonaws.com
            OriginPath: /development
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only

Outputs:
  ApiGatewayDistributionDomain:
    Value:
      'Fn::GetAtt': [ ApiGatewayDistribution, DomainName ]
```

**Comment by FanFataL** [comment]
Default methods handled by the Cloudfront are HEAD and GET, you need to add OPTIONS or all of them. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#cfn-cloudfront-distribution-defaultcachebehavior-allowedmethods

```
DefaultCacheBehavior:
  AllowedMethods:
    - "GET"
    - "HEAD"
    - "OPTIONS"
    - "PUT"
    - "PATCH"
    - "POST"
    - "DELETE"
  CachedMethods:
    - "GET"
    - "HEAD"
    - "OPTIONS"
```

Additionaly you need to enable cors in the lambda function sls configuration (if `cors: *` is not enough for you try this:)
```
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
```
