### ISSUE TITLE
S3 event with existing bucket and custom IAM role does not work

### ISSUE THREAD

**Issue by JakubMatejka** [serverless/serverless#7143]
# Bug Report

## Description

We use an S3 event to handle uploads to a bucket. So far we used a bucket provisioned by Serverless but now we want to use an already existing bucket.

1. What did you do?

We added `existing: true` to the event. We use custom IAM roles for Lambda execution and CloudFormation deployment so we had to update their permissions for the other bucket and for the created "custom resources" lambda function.

1. What happened?

Deployment failed on this CF error:
![image](https://user-images.githubusercontent.com/215660/71473841-13b16200-27d9-11ea-9c67-b57fc4f7e98e.png)

Evidently, Serverless is trying to let the CF role to assume itself. By looking to the source code I found out that the cfnRole is passed as execution role of the custom lambda function: https://github.com/serverless/serverless/blob/2938a95b8711d3bfab1e665318f46f66db91d6a4/lib/plugins/aws/customResources/index.js#L177 from: https://github.com/serverless/serverless/blob/2938a95b8711d3bfab1e665318f46f66db91d6a4/lib/plugins/aws/customResources/index.js#L81. But I would say that there should be `serverless.service.provider.role` instead. What do you think?

1. What should've happened?

The deployment should be completed successfully.

1. What's the content of your `serverless.yml` file?

The whole file is here: https://gist.github.com/JakubMatejka/899d9fea178c53df292838ccd3e8f8d8
The most important parts are:

```
...
provider:
  name: aws
  region: ${env:REGION}
  stage: ${env:STAGE}
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30
  versionFunctions: false
  deploymentBucket:
    name: "${env:SERVICE_NAME}-${env:REGION}-deployment"
  tracing:
    apiGateway: true
    lambda: true
  environment:
    ...
  cfnRole: ${env:CLOUDFORMATION_ROLE_ARN}
  role: ${env:LAMBDA_EXECUTION_ROLE_ARN}
  vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP}
    subnetIds:
      - ${env:VPC_SUBNET1}
      - ${env:VPC_SUBNET2}

functions:
  service:
    timeout: 30
    handler: src/lambda/service.handler
    tags:
      KeboolaStack: ${env:KEBOOLA_STACK}
    events:
      -
        s3:
          bucket: "${env:S3_BUCKET}"
          event: "s3:ObjectCreated:Put"
          suffix: .png
          existing: true
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

> Your Environment Information ---------------------------
>      Operating System:          linux
>      Node Version:              12.14.0
>      Framework Version:         1.60.4
>      Plugin Version:            3.2.6
>      SDK Version:               2.2.1
>      Components Core Version:   1.1.2
>      Components CLI Version:    1.4.0

Similar or dependent issues:

-
