### ISSUE TITLE
Please do not hard code ARN partition for websocket 

### ISSUE THREAD

**Issue by gaox2002** [serverless/serverless#7149]
# Bug Report

## Description

I am using aws china, where I set iamRoleStatement as 
```
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws-cn:execute-api:*:*:**/@connections/*"
```
 however, serverless always add an extra policy as
```
{
  "Effect": "Allow",
  "Action": [
    "execute-api:ManageConnections"
  ],
  "Resource": [
    "arn:aws:execute-api:*:*:*/@connections/*"
  ]
}
```
when I do the deployment, it reports
`ServerlessError: Stack:arn:aws-cn:cloudformation:cn-northwest-1:xxxx is in ROLLBACK_COMPLETE state and can not be updated.`

as I can search in the repository, this line may the cause
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/websockets/lib/api.js#L42

- #12345
