### ISSUE TITLE
Multi-line values in logs.restApi.format

### ISSUE THREAD

**Issue by maros7** [serverless/serverless#7162]
# Bug Report

## Description

1. What did you do?
Tried to setup log format in API Gateway using the following `serverless.yml` config:
```yaml
provider:
  name: aws
  logs:
    restApi:
      format: >-
        {
          "accountId": "$context.accountId",
          "apiId": "$context.apiId",
          "awsEndpointRequestId": "$context.awsEndpointRequestId",
          "domainName": "$context.domainName",
          "domainPrefix": "$context.domainPrefix",
          "error.message": "$context.error.message",
          "error.messageString": "$context.error.messageString",
          "error.responseType": "$context.error.responseType",
          "error.validationErrorString": "$context.error.validationErrorString",
          "extendedRequestId": "$context.extendedRequestId",
          "httpMethod": "$context.httpMethod",
          "identity.accountId": "$context.identity.accountId",
          "identity.apiKey": "$context.identity.apiKey",
          "identity.apiKeyId": "$context.identity.apiKeyId",
          "identity.caller": "$context.identity.caller",
          "identity.cognitoAuthenticationProvider": "$context.identity.cognitoAuthenticationProvider",
          "identity.cognitoAuthenticationType": "$context.identity.cognitoAuthenticationType",
          "identity.cognitoIdentityId": "$context.identity.cognitoIdentityId",
          "identity.cognitoIdentityPoolId": "$context.identity.cognitoIdentityPoolId",
          "identity.principalOrgId": "$context.identity.principalOrgId",
          "identity.sourceIp": "$context.identity.sourceIp",
          "identity.user": "$context.identity.user",
          "identity.userAgent": "$context.identity.userAgent",
          "identity.userArn": "$context.identity.userArn",
          "path": "$context.path",
          "protocol": "$context.protocol",
          "requestId": "$context.requestId",
          "requestOverride.header.header_name": "$context.requestOverride.header.header_name",
          "requestOverride.path.path_name": "$context.requestOverride.path.path_name",
          "requestOverride.querystring.querystring_name": "$context.requestOverride.querystring.querystring_name",
          "responseOverride.header.header_name": "$context.responseOverride.header.header_name",
          "responseOverride.status": $context.responseOverride.status,
          "requestTime": "$context.requestTime",
          "requestTimeEpoch": $context.requestTimeEpoch,
          "resourceId": "$context.resourceId",
          "resourcePath": "$context.resourcePath",
          "stage": "$context.stage",
          "wafResponseCode": "$context.wafResponseCode",
          "webaclArn": "$context.webaclArn",
          "xrayTraceId": "$context.xrayTraceId",
          "authorizer.integrationLatency": $context.authorizer.integrationLatency,
          "integrationLatency": $context.integrationLatency,
          "integrationStatus": $context.integrationStatus,
          "responseLatency": $context.responseLatency,
          "responseLength": $context.responseLength,
          "status": $context.status
        }
```
1. What happened? This error:
```
Serverless: [AWS sts 200 0.509s 0 retries] getCallerIdentity({})
Serverless: [AWS apigateway 200 0.363s 0 retries] getRestApis({ position: undefined, limit: 500 })
Serverless: [AWS apigateway 200 0.224s 0 retries] getStage({ restApiId: 'xxx', stageName: 'xxx' })
Serverless: [AWS apigateway 400 0.282s 0 retries] updateStage({
  restApiId: 'xxx',
  stageName: 'xxx',
  patchOperations: [
    { op: 'replace', path: '/tracingEnabled', value: 'true' },
    {
      op: 'replace',
      path: '/accessLogSettings/destinationArn',
      value: 'arn:aws:logs:eu-west-1:xxx:log-group:/aws/api-gateway/xxx'
    },
    {
      op: 'replace',
      path: '/accessLogSettings/format',
      value: '{\n' +
        '  "accountId": "$context.accountId",\n' +
        '  "apiId": "$context.apiId",\n' +
        '  "awsEndpointRequestId": "$context.awsEndpointRequestId",\n' +
        '  "domainName": "$context.domainName",\n' +
        '  "domainPrefix": "$context.domainPrefix",\n' +
        '  "error.message": "$context.error.message",\n' +
        '  "error.messageString": "$context.error.messageString",\n' +
        '  "error.responseType": "$context.error.responseType",\n' +
        '  "error.validationErrorString": "$context.error.validationErrorString",\n' +
        '  "extendedRequestId": "$context.extendedRequestId",\n' +
        '  "httpMethod": "$context.httpMethod",\n' +
        '  "identity.accountId": "$context.identity.accountId",\n' +
        '  "identity.apiKey": "$context.identity.apiKey",\n' +
        '  "identity.apiKeyId": "$context.identity.apiKeyId",\n' +
        '  "identity.caller": "$context.identity.caller",\n' +
        '  "identity.cognitoAuthenticationProvider": "$context.identity.cognitoAuthenticationProvider",\n' +
        '  "identity.cognitoAuthenticationType": "$context.identity.cognitoAuthenticationType",\n' +
        '  "identity.cognitoIdentityId": "$context.identity.cognitoIdentityId",\n' +
        '  "identity.cognitoIdentityPoolId": "$context.identity.cognitoIdentityPoolId",\n' +
        '  "identity.principalOrgId": "$context.identity.principalOrgId",\n' +
        '  "identity.sourceIp": "$context.identity.sourceIp",\n' +
        '  "identity.user": "$context.identity.user",\n' +
        '  "identity.userAgent": "$context.identity.userAgent",\n' +
        '  "identity.userArn": "$context.identity.userArn",\n' +
        '  "path": "$context.path",\n' +
        '  "protocol": "$context.protocol",\n' +
        '  "requestId": "$context.requestId",\n' +
        '  "requestOverride.header.header_name": "$context.requestOverride.header.header_name",\n' +
        '  "requestOverride.path.path_name": "$context.requestOverride.path.path_name",\n' +
        '  "requestOverride.querystring.querystring_name": "$context.requestOverride.querystring.querystring_name",\n' +
        '  "responseOverride.header.header_name": "$context.responseOverride.header.header_name",\n' +
        '  "responseOverride.status": $context.responseOverride.status,\n' +
        '  "requestTime": "$context.requestTime",\n' +
        '  "requestTimeEpoch": $context.requestTimeEpoch,\n' +
        '  "resourceId": "$context.resourceId",\n' +
        '  "resourcePath": "$context.resourcePath",\n' +
        '  "stage": "$context.stage",\n' +
        '  "wafResponseCode": "$context.wafResponseCode",\n' +
        '  "webaclArn": "$context.webaclArn",\n' +
        '  "xrayTraceId": "$context.xrayTraceId",\n' +
        '  "authorizer.integrationLatency": $context.authorizer.integrationLatency,\n' +
        '  "integrationLatency": $context.integrationLatency,\n' +
        '  "integrationStatus": $context.integrationStatus,\n' +
        '  "responseLatency": $context.responseLatency,\n' +
        '  "responseLength": $context.responseLength,\n' +
        '  "status": $context.status\n' +
        '}\n'
    },
    { op: 'replace', path: '/*/*/logging/dataTrace', value: 'true' },
    { op: 'replace', path: '/*/*/logging/loglevel', value: 'INFO' },
    [length]: 5
  ]
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Access Log format must be single line: '{
    "accountId": "$context.accountId",
    "apiId": "$context.apiId",
    "awsEndpointRequestId": "$context.awsEndpointRequestId",
    "domainName": "$context.domainName",
    "domainPrefix": "$context.domainPrefix",
    "error.message": "$context.error.message",
    "error.messageString": "$context.error.messageString",
    "error.responseType": "$context.error.responseType",
    "error.validationErrorString": "$context.error.validationErrorString",
    "extendedRequestId": "$context.extendedRequestId",
    "httpMethod": "$context.httpMethod",
    "identity.accountId": "$context.identity.accountId",
    "identity.apiKey": "$context.identity.apiKey",
    "identity.apiKeyId": "$context.identity.apiKeyId",
    "identity.caller": "$context.identity.caller",
    "identity.cognitoAuthenticationProvider": "$context.identity.cognitoAuthenticationProvider",
    "identity.cognitoAuthenticationType": "$context.identity.cognitoAuthenticationType",
    "identity.cognitoIdentityId": "$context.identity.cognitoIdentityId",
    "identity.cognitoIdentityPoolId": "$context.identity.cognitoIdentityPoolId",
    "identity.principalOrgId": "$context.identity.principalOrgId",
    "identity.sourceIp": "$context.identity.sourceIp",
    "identity.user": "$context.identity.user",
    "identity.userAgent": "$context.identity.userAgent",
    "identity.userArn": "$context.identity.userArn",
    "path": "$context.path",
    "protocol": "$context.protocol",
    "requestId": "$context.requestId",
    "requestOverride.header.header_name": "$context.requestOverride.header.header_name",
    "requestOverride.path.path_name": "$context.requestOverride.path.path_name",
    "requestOverride.querystring.querystring_name": "$context.requestOverride.querystring.querystring_name",
    "responseOverride.header.header_name": "$context.responseOverride.header.header_name",
    "responseOverride.status": $context.responseOverride.status,
    "requestTime": "$context.requestTime",
    "requestTimeEpoch": $context.requestTimeEpoch,
    "resourceId": "$context.resourceId",
    "resourcePath": "$context.resourcePath",
    "stage": "$context.stage",
    "wafResponseCode": "$context.wafResponseCode",
    "webaclArn": "$context.webaclArn",
    "xrayTraceId": "$context.xrayTraceId",
    "authorizer.integrationLatency": $context.authorizer.integrationLatency,
    "integrationLatency": $context.integrationLatency,
    "integrationStatus": $context.integrationStatus,
    "responseLatency": $context.responseLatency,
    "responseLength": $context.responseLength,
    "status": $context.status
  }
  '
      at /Users/maros7/.../node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:326:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         1.59.0
     Plugin Version:            3.2.5
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
1. What should've happened? Newlines should have been stripped. I'm assuming that https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L228 should be something like:
```javascript
      logFormat = logs.format.replace(/\r?\n/g, '');
```
The deployment works just fine if the above change is done.
1. What's the content of your `serverless.yml` file? See above
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`) See above

Similar or dependent issues:

- #3094

**Comment by medikoo** [comment]
@maros7 It looks as an error in your configuration. Error message states: _Access Log format must be single line_, and in your `serverless.yml` it's multi line

**Comment by maros7** [comment]
Typically using `>-` in YAML should remove any newlines. So, I wouldn't consider my configuration to be incorrect.
```yaml
provider:
  name: aws
  logs:
    restApi:
      format: >-
        {
...
```

**Comment by medikoo** [comment]
> Typically using `>-` in YAML should remove any newlines

It doesn't seem to be the case. Does YAML spec says that?

**Comment by maros7** [comment]
I updated the above comment with some more info. In any case, you can also see this example [here](https://nodeca.github.io/js-yaml/#yaml=LS0tCm11bHRpTGluZTogPi0KICB0ZXN0CiAgdGVzdA==). I assume that you are using `js-yaml` for parsing the YAML file(s).  And [here](https://yaml.org/spec/current.html#folded%20style/information%20model) is the spec.

**Comment by medikoo** [comment]
@maros7 Do you mean it's due to bug on `js-yaml` side? Have you reported that issue over there? (or if there already exist one, can you link it here)

**Comment by maros7** [comment]
The additional indentation was causing this issue:
```yaml
provider:
  name: aws
  logs:
    restApi:
      format: >-
        {
          "accountId": "$context.accountId",
          "apiId": "$context.apiId",
```
I.e. indentation of `{` vs. `"apiId": "$context.apiId",`and so on.
Sorry for the noise!
