### ISSUE TITLE
`async: true` no longer returns immediately with status of 200

### ISSUE THREAD

**Issue by bbrock25** [serverless/serverless#7169]
# Bug Report

The `async: true` feature to specify using event invocation in AWS ceases to return an immediate response with a status of 200 in versions 1.60.x.

I reverted back to 1.59.3 to revert to the expected behavior as documented [here](https://serverless.com/framework/docs/providers/aws/events/apigateway/#using-asynchronous-integration)

## What did you do?
upgraded from 1.59.3 to the latest version

## What happened?
- requests started returning the return value of the handler rather than an immediate 200, this is important since there is a timeout limit on the service using my function

## What should've happened?
immediate response with a status of 200

## What's the content of your `serverless.yml` file?
```
slack_slash_command:
  handler: endpoints.slack_slash_command
  events:
    - http:
        path: slack_slash_command
        method: post
        cors: true
        async: true
```

## What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

didn't check this, issue was successfully resolved by reverting to prior version
