### ISSUE TITLE
Serverless deployment issue with imported bucket name with 2 events

### ISSUE THREAD

**Issue by sidrazia** [serverless/serverless#7176]
We have 2 events registered in lambda on same bucket as below:
```
     events:
       - s3:
          bucket: !ImportValue S3Bucket
           event: s3:ObjectCreated:*
           existing: true
       - s3:
          bucket: !ImportValue S3Bucket
           event: s3:ObjectRemoved:*
           existing: true
```
However when we try to deploy lambda, serverless is throwing error:
```
  Serverless Error ---------------------------------------
 
  Only one S3 Bucket can be configured per function. In "product-lambda" you're attempting to configure "[object Object]" and "[object Object]" at the same time.
```
Seems like this is happening because of following check in serverless code and serverless is handling imported bucket names as object:
```
if (bucket !== currentBucketName) {
              const errorMessage = [
                'Only one S3 Bucket can be configured per function.',
                ` In "${FunctionName}" you're attempting to configure "${currentBucketName}" and "${bucket}" at the same time.`,
              ].join('');
              throw new this.serverless.classes.Error(errorMessage);
            }
```
This is working fine if either bucket name is directly mentioned above instead of importing it or if we have only one event registered. Can anyone pls fix this?
