### ISSUE TITLE
After upgrading to 1.60.5, can't set environment variables via CLI

### ISSUE THREAD

**Issue by oolooroo** [serverless/serverless#7181]
# Bug Report

## Description

What did you do?
```sls env -a abc -v abc```

1. What happened?

 ```
  Serverless Error ---------------------------------------
 
  "abc" is not a valid sub command. Run "serverless env" to see a more helpful error message for this command.
```

1. What should've happened?
An environment.yml file should have been generated with a variable 'abc' of value 'abc'.

1. What's the content of your `serverless.yml` file?
```
service: test

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
