### ISSUE TITLE
1.60.5 Environment Variable Jumble

### ISSUE THREAD

**Issue by g33kcentric** [serverless/serverless#7188]
# Bug Report

## Description 

Hi there!

I recently updated to serverless 1.60.5 and now all of my functions seem to share the environement variables from the first function defined in the serverless.yml file. 

Function one in serverless.yml

```
webform_submission_receive:
    name: webform-submission-receive-${self:provider.stage}
    description: Receives webform submissions, validates them and sends them to a queue.
    handler: receive.handler
    environment:
      SQS_QUEUE: ${self:custom.queue-endpoints.${self:provider.stage}}
      MAX_FIELD_LENGTH: 255
      ACCESS_KEY_ID: ${self:custom.queue-options.${self:provider.stage}.accessKeyId}
      SECRET_ACCESS_KEY: ${self:custom.queue-options.${self:provider.stage}.secretAccessKey}
      SSL_ENABLED: ${self:custom.queue-options.${self:provider.stage}.sslEnabled}
      REGION: ${self:provider.region}
```

Function two in serverless.yml (this is called from the first function)

```
webform_communicator_send:
    name: webform-communicator-send-${self:provider.stage}
    description: Receives webform submissions, validates them and sends them to a queue.
    handler: communicator.handler
    environment:
      COMMUNICATOR_URL: ${self:custom.queue-options.${self:provider.stage}.communicatorUrl}
      COMMUNICATOR_LOGIN: ${self:custom.queue-options.${self:provider.stage}.communicatorLogin}
      COMMUNICATOR_PASSWORD: ${self:custom.queue-options.${self:provider.stage}.communicatorPassword}
      SLACK_URL: ${self:custom.queue-options.${self:provider.stage}.slackURL}
```

Before **webform_communicator_send** had access to it's own environement variables (**COMMUNICATOR_URL** etc), but now can only access the environement variables from the first function (**SQS_Queue** etc)

I also have the following plugins enabled:

 - serverless-offline-aws-sqs
 - serverless-offline-lambda
 - serverless-pseudo-parameters
 - serverless-offline

Thanks!

Also apologies for not adding a bug label, im not sure how to add one after the fact
