### ISSUE TITLE
Serverless deploy is not packaging puppeteer-core on deploy

### ISSUE THREAD

**Issue by simsketch** [serverless/serverless#7192]
# Bug Report
Serverless deploy is not packaging puppeteer-core on deploy

## Description
Even though puppeteer-core is listed as a dependency in package.json, it does not get packaged up in the zip file. I know this because I inspected the zip in .serverless and found that the folder was missing. When I add it manually and upload a zip manually to the lambda function, I no longer get the error.

1. What did you do?
Deployed my endpoint
2. What happened?
Uploaded successfully, but invocation fails because of a MODULE_NOT_FOUND error
3. What should've happened?
It shouldn't be missing any modules
4. What's the content of your `serverless.yml` file?
```
  hap-l-shipping-out-endicia:
    handler: dist/endicia/index.handler
    timeout: 30
    exclude:
      - src/**
      - data/mock/**
    include:
      - dist/endicia/index.js
    events:
      - http:
          path: /posts/shipping-out
          integration: lambda
          method: post
          cors: true
      - schedule:
          name: endicia-daily-report-generate
          rate: cron(0 12 * * ? *)
          enabled: true
```
5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
I don't get any errors or logs worthy of noting here, deploy is successful, all other functions appear to functioning normally

Similar or dependent issues:
https://github.com/alixaxel/chrome-aws-lambda/issues/45

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'puppeteer-core'\nRequire stack:\n- /var/task/dist/endicia/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'puppeteer-core'",
    "Require stack:",
    "- /var/task/dist/endicia/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:956:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)",
    "    at Module.load (internal/modules/cjs/loader.js:812:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)",
    "    at internal/main/run_main_module.js:17:11"
  ]
}
```
