### ISSUE TITLE
Default APIGW Resource Policy breaks least privilege and can allow for up-privileging 

### ISSUE THREAD

**Issue by DrColza** [serverless/serverless#7211]
# Bug Report
The Default API Gateway Policy merged here https://github.com/serverless/serverless/pull/7138 conflicts with [the best practice of granting least privilege, or granting only the permissions required to perform a task](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege) and introduces potential security vulnerability for unauthorized access to api-endpoints.

## Description 

When a default policy allowing anyone to invoke any api endpoint is applied to the APIGW then any pre-existing IAM roles/policies which currently rely on implicit denys being in place will be circumvented.

1. What did you do?
Upgraded to serverless v1.60.5
1. What happened?
**Given** a read-only user is authenticated and assigned an IAM Policy like the following which only allows invocation of GET endpoints
```json
{
    "principalId": "CMSReadOnlyAccess",
    "policyDocument": {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "VisualEditor1",
                "Effect": "Allow",
                "Action": "execute-api:Invoke",
                "Resource": [
                    "arn:aws:execute-api:eu-west-1::api_id/stage/GET/*"
                ]
            }
        ]
    }
}
```
**When** they request an endpoint of method `POST`
**Then** they have authorized access to the `POST` endpoint

This means that even though the customAuthorizer has correctly identified them as being read-only and been assigned a read-only policy, they get authorized write access any endpoint due to the APIGW default policy because the IAM policy attached to a read-only user looks like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:eu-west-1:<acc_id>:<api_id>/*/*/*",
            "Condition": {
                "IpAddress": {
                    "aws:SourceIp": [
                        "0.0.0.0/0",
                        "::/0"
                    ]
                }
            }
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": [
                "arn:aws:execute-api:eu-west-1::api_id/stage/GET/*"
            ]
        }
    ]
}
```

1. What should've happened?
**Given** the read-only user should only have access to `GET` endpoints 
**When** they try to access a `POST` endpoint 
**Then** they should receive a http 403 response

1. What's the content of your `serverless.yml` file?
```yml
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  tracing:
    lambda: true
    apiGateway: true

functions:
  customAuthorizer:
    handler: index.auth
    events:
      - http:
          path: /auth
          method: GET
          cors: true

  get_user:
    handler: index.handler
    events:
      - http:
          path: /user/{id}
          method: GET
          cors: true
          authorizer: customAuthorizer

  update_user:
    handler: index.handler
    events:
      - http:
          path: /update/user/{id}
          method: POST
          cors: true
          authorizer: customAuthorizer
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

This explains the customAuthorizer not working in this issue #7189 even after the fix for that particular bug was addressed.
