### ISSUE TITLE
serverless logs stopped working

### ISSUE THREAD

**Issue by charlieongithub** [serverless/serverless#7214]
# Bug Report
`sls logs -f functionName -t` stopped working after upgrade to `1.61.0` from `1.57.0`
## Description

I've upgraded the serverless framework today and since then I don't see any output coming out of the `sls logs` command. It is just hanging in there. I can however see the logs on CloudWatch directly. 

1. What did you do?

I've upgraded the serverless framework today.

I didn't change any configuration in my serverless.yml other than configuring `provisionedConcurrency: 5`

2. What happened?
Since then I don't see any output coming out from the `sls logs` command. It is just hanging in there. 

3. What should've happened?

The latest logs from AWS Lambda should appear in the console

4. What's the content of your `serverless.yml` file?

```
...
provider:
  region: eu-central-1
  name: aws
  runtime: nodejs10.x
  timeout: 30
  stage: ${self:custom.secrets.NODE_ENV}
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_PORT: ${self:custom.secrets.DB_PORT}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}

functions:
  functionName:
    provisionedConcurrency: 5
    handler: src/handler.functionName
    events:
      - http:
          method: get
          path: test
          integration: lambda
          cors: true
...
```
