### ISSUE TITLE
A bug in the newest Serverless version - 1.61.2

### ISSUE THREAD

**Issue by turakvlad** [serverless/serverless#7225]
# Bug Report

## Description

1. What did you do?

I update the Serverless framework from 1.61.1 to 1.61.2.

1. What happened?

My Serverless config stopped working. 

My simplified config:

```
service:
  name: sa-weekly-report

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:NODE_ENV, 'dev'}
  region: ${opt:region, 'eu-central-1'}

custom:
  customDomain:
    domainName: sa-weekly-report.startdeliver.io
    certificateName: '*.startdeliver.io'
    endpointType: 'regional'

functions:
  # Some functions go here...  

plugins:
  - serverless-domain-manager
```

I invoke the domain's creation with `sls create_domain`.

1. What should've happened?

It should work as it worked in 1.61.1. But instead I am getting this:

```
  Error --------------------------------------------------
 
  Error: Error: '*******************************' was not created in API Gateway.
  ConfigError: Missing region in config
      at createDomainName.catch (/root/app/node_modules/serverless-domain-manager/index.js:108:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.18.1
     Framework Version:         1.61.2
     Plugin Version:            3.2.7
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 

Exited with code exit status 1
```

Similar or dependent issues:

- the same problem is described in the plugin's repository - https://github.com/amplify-education/serverless-domain-manager/issues/306
