### ISSUE TITLE
Adding Kinesis stream as a trigger for lambda

### ISSUE THREAD

**Issue by rohitkaruturi** [serverless/serverless#7228]
I am trying to add a kinesis stream as an event trigger, below is the snippet from serverless.yml

```
    events:
      - stream:
          type: kinesis
          streamName: helper
          arn: arn:aws:kinesis:us-east-1:737373737505:stream/helper
          bisectBatchOnFunctionError: true
          batchSize: 11
          maximumRetryAttempts: 10
          startingPosition: LATEST
          parallelizationFactor: 10
          enabled: true 
```
Note: The kinesis stream already exist in the system

The deployment  is successful but some of the configuration is ignored, didn't find it in the generated  CFT as well.

Below is the generated CFT for the trigger:
```
  OrderEventSourceMappingKinesisHelper
    Type: 'AWS::Lambda::EventSourceMapping'
    DependsOn: IamRoleLambdaExecution
    Properties:
      BatchSize: 11
      EventSourceArn: 'arn:aws:kinesis:us-east-1:737373737505:stream/helper'
      FunctionName: !GetAtt 
        - ProcessorLambdaFunction
        - Arn
      StartingPosition: LATEST
      Enabled: 'True'
```
Below is the details of the added trigger:
```
**Details**
Batch size: 11
Batch window: None
Concurrent batches per shard: 1
Last processing result: No records processed
Maximum age of record: 604800
On-failure destination:
{
  "onFailure": {}
}
Retry attempts: 10000
Split batch on error: No
```

parallelizationFactor & bisectBatchOnFunctionError are ignored, did I miss anything or is it a bug?
