### ISSUE TITLE
Deployment failure when setting trigger to different existing bucket

### ISSUE THREAD

**Issue by AntonOellerer** [serverless/serverless#7238]
# Bug Report

## Description
I am trying to create a lambda function which is called via an s3 trigger from an existing bucket.
This bucket should be configurable at deploy time, so it is set via a command line parameter.
When testing with a testing bucket, the function worked fine, but when I wanted to deploy it for a production bucket, I get the error 
`An error occurred: AutoRotateCustomS31 - Failed to update resource. Unable to validate the following destination configurations See details in CloudWatch Log: ...`
When I remove the function before deploying (with `sls remove`) the following deployment works fine, no matter to which bucket, but any deployment trying to deploy to a different bucket fail again.

1. What did you do?
Changed the bucket which triggers the serverless function.
1. What happened?
The above mentioned error gets thrown
1. What should've happened?
The function gets deployed and the trigger configured correctly
1. What's the content of your `serverless.yml` file?

```yml
 service:
  name: xxx

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 14
  deploymentBucket:
    name: xxx
  versionFunctions: false
  environment:
    LIBVIPS_PATH: vips
    VIPS_DISC_THRESHOLD: 2g
    SERVERLESS_SERVICE: ${self:service.name}
    SERVERLESS_STAGE: ${self:provider.stage}
    SERVERLESS_REGION: ${self:provider.region}
    RELEASE: ${opt:release, 'test'}
  stackTags:
    service: xxx
    environment: ${self:provider.stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::docutools-${self:provider.stage}-${self:custom.config.bucket}/*'

functions:
  xxx:
    handler: xxx.main
    events:
      - s3:
          bucket: xxx-${self:provider.stage}-${self:custom.config.bucket}
          event: s3:ObjectCreated:${self:custom.config.operation}
          rules:
            - suffix: .jpg
          existing: true
    memorySize: 512
    timeout: 30
    environment:
      SENTRY_MEMORY_THRESHOLD: 512
      SENTRY_TIMEOUT_THRESHOLD: 30
      SENTRY_LOG_LEVEL: DEBUG
      SENTRY_ENVIRONMENT: ${self:provider.stage}
    layers:
      - arn:aws:lambda:eu-central-1:679230420267:layer:pyvips:1


plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
  config: 
    bucket: ${opt:bucket, 'temporary'}
    operation: ${opt:operation, 'Copy'}

package:
  exclude:
    - venv/**
    - docker/**
    - xxx.py.*
    - node_modules/**
    - lambci/**
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generated requirements from /home/xxx/Projects/xxx/requirements.txt in /home/xxx/Projects/xxx/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /home/xxx/.cache/serverless-python-requirements/18febe1bb6b3eccb91d7e262ae9473ea61f98ebeff44bb08f20cee00f05e11a1_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: [AWS s3 200 0.235s 0 retries] getBucketLocation({ Bucket: 'yyy' })
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.255s 0 retries] describeStacks({ StackName: 'xxx' })
Serverless: [AWS s3 200 0.193s 0 retries] listObjectsV2({
  Bucket: 'yyy',
  Prefix: 'serverless/xxx/staging'
})
Serverless: [AWS s3 200 0.181s 0 retries] headObject({
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579604985025-2020-01-21T11:09:45.025Z/xxx.zip'
})
Serverless: [AWS s3 200 0.197s 0 retries] headObject({
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579604985025-2020-01-21T11:09:45.025Z/custom-resources.zip'
})
Serverless: [AWS s3 200 0.186s 0 retries] headObject({
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579604985025-2020-01-21T11:09:45.025Z/compiled-cloudformation-template.json'
})
Serverless: [AWS lambda 200 0.26s 0 retries] getFunction({ FunctionName: 'xxx' })
Serverless: [AWS sts 200 0.574s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.203s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 4136 more bytes>,
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'L4wkhJe5WEijEW1dmU5EcbI6qKNmIaDwXiacO2AmS6I=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service xxx.zip file to S3 (19.46 MB)...
Serverless: [AWS s3 200 0.224s 0 retries] createMultipartUpload({
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/xxx.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'hu+CY1Tbk7T9Lb1FJ0bRCgkDbl5BPexEOI7t2VH4PDk=' }
})
Serverless: [AWS s3 200 3.857s 0 retries] uploadPart({
  Body: <Buffer e5 da a3 1c e4 7b 45 e6 1d af c8 41 d1 97 65 8a f6 8a 1c 8c 7b e5 85 ec 0c 75 fa a4 65 6f d2 3f b4 a2 d1 ef aa 8e d0 32 77 82 b6 3a c9 43 9b 9b bc d5 ... 4675562 more bytes>,
  ContentLength: 4675612,
  PartNumber: 4,
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/xxx.zip',
  UploadId: 'Pb7JzArWnzgl_IU9OLKLmcyRr54iZp2jLirmmp3zRqLn_xvznKuqOJ8Q2R6JHcQMmp.BuXpsIwg_.fZYw5s.HP56wYCg.lH7hy_3v9WNvSAs75tB3Ghz4B8t6e5zNin5'
})
Serverless: [AWS s3 200 4.092s 0 retries] uploadPart({
  Body: <Buffer 13 0f 67 8f a6 ce cf 2a 76 4d 55 77 47 1b 63 73 6d ab e2 01 af 27 59 0f 67 a7 5f 6b 6f 8f 5f a7 57 96 ce 2c ef 1f 91 f6 d5 6f 96 4e 39 cb 77 b4 69 e4 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 2,
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/xxx.zip',
  UploadId: 'Pb7JzArWnzgl_IU9OLKLmcyRr54iZp2jLirmmp3zRqLn_xvznKuqOJ8Q2R6JHcQMmp.BuXpsIwg_.fZYw5s.HP56wYCg.lH7hy_3v9WNvSAs75tB3Ghz4B8t6e5zNin5'
})
Serverless: [AWS s3 200 4.21s 0 retries] uploadPart({
  Body: <Buffer 50 4b 03 04 0a 00 00 00 08 00 00 00 21 00 6f d5 03 6e d7 01 00 00 78 04 00 00 0e 00 00 00 2e 67 69 74 6c 61 62 2d 63 69 2e 79 6d 6c c5 52 4d 8b db 30 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/xxx.zip',
  UploadId: 'Pb7JzArWnzgl_IU9OLKLmcyRr54iZp2jLirmmp3zRqLn_xvznKuqOJ8Q2R6JHcQMmp.BuXpsIwg_.fZYw5s.HP56wYCg.lH7hy_3v9WNvSAs75tB3Ghz4B8t6e5zNin5'
})
Serverless: [AWS s3 200 4.221s 0 retries] uploadPart({
  Body: <Buffer 5e 77 ef ec 75 9a b1 2b d0 60 a7 7d 73 17 16 bb f3 1b f2 94 26 dc 66 f8 97 5d d9 c4 af 3f af d3 94 48 93 87 0a d0 84 c7 0d b3 93 52 b6 10 cb e1 fe 0c ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 3,
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/xxx.zip',
  UploadId: 'Pb7JzArWnzgl_IU9OLKLmcyRr54iZp2jLirmmp3zRqLn_xvznKuqOJ8Q2R6JHcQMmp.BuXpsIwg_.fZYw5s.HP56wYCg.lH7hy_3v9WNvSAs75tB3Ghz4B8t6e5zNin5'
})
Serverless: [AWS s3 200 0.326s 0 retries] completeMultipartUpload({
  MultipartUpload: {
    Parts: [
      { ETag: '"c394d82161b06b475557c290287d601c"', PartNumber: 1 },
      { ETag: '"4b0bf61e28829b1940374ee71e9c71af"', PartNumber: 2 },
      { ETag: '"751afadfa52b3350e73500e880fdbfa4"', PartNumber: 3 },
      { ETag: '"99d48ae1e56aab6032cd78fc94d46a6c"', PartNumber: 4 },
      [length]: 4
    ]
  },
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/xxx.zip',
  UploadId: 'Pb7JzArWnzgl_IU9OLKLmcyRr54iZp2jLirmmp3zRqLn_xvznKuqOJ8Q2R6JHcQMmp.BuXpsIwg_.fZYw5s.HP56wYCg.lH7hy_3v9WNvSAs75tB3Ghz4B8t6e5zNin5'
})
Serverless: Uploading custom CloudFormation resources...
Serverless: [AWS s3 200 0.191s 0 retries] createMultipartUpload({
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/custom-resources.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'tlW9jBdjg04uPYabugNwaqSPKsNFjJXihjjoAp2SRjQ=' }
})
Serverless: [AWS s3 200 1.146s 0 retries] uploadPart({
  Body: <Buffer 8c 69 03 df 49 c8 e8 57 c3 4f b5 bd 94 2c 88 81 78 ab b2 ff fe d8 57 54 cc b8 be 51 a0 35 55 a1 80 4f 67 49 c2 86 5b 9b b5 a4 93 30 a5 27 3d 49 de 45 ... 1402606 more bytes>,
  ContentLength: 1402656,
  PartNumber: 2,
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/custom-resources.zip',
  UploadId: 'zZ.kwuTRe5GJ5vhre0sycjpoKqJnHtESCw2u0CecAUcyfkZtQGJ9.Sd7LaqNOWxEz8iDWdnq3L5dGmZt1SYHWKZTZwntDWAHQZmcZslHlRdxyW23qECil74rSu4mmb6_'
})
Serverless: [AWS s3 200 1.824s 0 retries] uploadPart({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 81 45 35 50 00 00 00 00 00 00 00 00 00 00 00 00 09 00 00 00 52 45 41 44 4d 45 2e 6d 64 8d cd c1 09 80 30 0c 46 e1 7b a7 ... 5242830 more bytes>,
  ContentLength: 5242880,
  PartNumber: 1,
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/custom-resources.zip',
  UploadId: 'zZ.kwuTRe5GJ5vhre0sycjpoKqJnHtESCw2u0CecAUcyfkZtQGJ9.Sd7LaqNOWxEz8iDWdnq3L5dGmZt1SYHWKZTZwntDWAHQZmcZslHlRdxyW23qECil74rSu4mmb6_'
})
Serverless: [AWS s3 200 0.235s 0 retries] completeMultipartUpload({
  MultipartUpload: {
    Parts: [
      { ETag: '"17284b1bc2fd912643c5f9be9194422c"', PartNumber: 1 },
      { ETag: '"21b408917aabcf4dbf94f3c2a904824a"', PartNumber: 2 },
      [length]: 2
    ]
  },
  Bucket: 'yyy',
  Key: 'serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/custom-resources.zip',
  UploadId: 'zZ.kwuTRe5GJ5vhre0sycjpoKqJnHtESCw2u0CecAUcyfkZtQGJ9.Sd7LaqNOWxEz8iDWdnq3L5dGmZt1SYHWKZTZwntDWAHQZmcZslHlRdxyW23qECil74rSu4mmb6_'
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.298s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/yyy/serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/compiled-cloudformation-template.json'
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 0.468s 0 retries] updateStack({
  StackName: 'xxx-staging',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/yyy/serverless/xxx/staging/1579605626235-2020-01-21T11:20:26.235Z/compiled-cloudformation-template.json',
  Tags: [
    { Key: 'STAGE', Value: 'staging' },
    { Key: 'service', Value: 'xxx' },
    { Key: 'environment', Value: 'staging' },
    [length]: 3
  ]
})
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.473s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-central-1:679230420267:stack/xxx-staging/1fddf420-3c3e-11ea-bfdd-06a619e5de86'
})
...Serverless: [AWS cloudformation 200 0.405s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-central-1:679230420267:stack/xxx-staging/1fddf420-3c3e-11ea-bfdd-06a619e5de86'
})
Serverless: [AWS cloudformation 200 0.411s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-central-1:679230420267:stack/xxx-staging/1fddf420-3c3e-11ea-bfdd-06a619e5de86'
})
Serverless: [AWS cloudformation 200 0.348s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-central-1:679230420267:stack/xxx-staging/1fddf420-3c3e-11ea-bfdd-06a619e5de86'
})
.....Serverless: [AWS cloudformation 200 0.326s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-central-1:679230420267:stack/xxx-staging/1fddf420-3c3e-11ea-bfdd-06a619e5de86'
})
Serverless: [AWS cloudformation 200 0.337s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-central-1:679230420267:stack/xxx-staging/1fddf420-3c3e-11ea-bfdd-06a619e5de86'
})
..Serverless: [AWS cloudformation 200 0.317s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:eu-central-1:679230420267:stack/xxx-staging/1fddf420-3c3e-11ea-bfdd-06a619e5de86'
})
..
Serverless: Operation failed!
Serverless: View the full error output: https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-central-1%3A679230420267%3Astack%2Fxxx-staging%2F1fddf420-3c3e-11ea-bfdd-06a619e5de86
 
  Serverless Error ---------------------------------------
 
  ServerlessError: An error occurred: xxxS31 - Failed to update resource. Unable to validate the following destination configurations See details in CloudWatch Log: 2020/01/21/[$LATEST]4ec41625153c46568e67eafe979bf742.
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:125:33
  From previous event:
      at AwsDeploy.monitorStack (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:28:12)
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:107:28
  From previous event:
      at AwsDeploy.update (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:107:8)
  From previous event:
      at AwsDeploy.<anonymous> (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:121:35)
  From previous event:
      at AwsDeploy.updateStack (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:117:33)
  From previous event:
      at AwsDeploy.<anonymous> (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:39)
  From previous event:
      at Object.aws:deploy:deploy:updateStack [as hook] (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:123:30)
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at AwsDeploy.<anonymous> (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Serverless.run (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/Serverless.js:120:74)
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/bin/serverless.js:75:30
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/bin/serverless.js:75:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)
  From previous event:
      at Object.<anonymous> (/home/xxx/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/bin/serverless.js:64:4)
      at Module._compile (internal/modules/cjs/loader.js:955:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
      at Module.load (internal/modules/cjs/loader.js:811:32)
      at Function.Module._load (internal/modules/cjs/loader.js:723:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
      at internal/main/run_main_module.js:17:11
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.14.1
     Framework Version:         1.61.2
     Plugin Version:            3.2.7
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0

 ```

Similar or dependent issues:

- #6461 

## Additional Data:
* OS: Fedora 31
* `sls --version`:  
    * Framework Core: 1.61.2
    * Plugin: 3.2.7
    * SDK: 2.2.1
    * Components Core: 1.1.2
    * Components CLI: 1.4.0

**Comment by AntonOellerer** [comment]
And another question: where can I find the log output?
I did not find it in the log group of the function, or any other log group for that matter.

**Comment by medikoo** [comment]
@AntonOellerer thanks for report. Can you minimize the test case, so it doesn't involve any plugins and unrelated configuration (which doesn't influence the issue in a any way)?

**Comment by AntonOellerer** [comment]
Here you go (its the base project created with `serverless` -> `aws-python` and then some modifications):
```yaml
service: xxx-dyn-bucket-test

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 14
  deploymentBucket:
    name: serverless-eu-frankfurt
  versionFunctions: false
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::yyy-${self:provider.stage}-${self:custom.config.bucket}/*'

custom:
 config: 
   bucket: ${opt:bucket, 'temporary'}
   operation: ${opt:operation, 'Copy'}

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: yyy-${self:provider.stage}-${self:custom.config.bucket}
          event: s3:ObjectCreated:${self:custom.config.operation}
          rules:
            - suffix: .jpg
          existing: true
```

**Comment by KrustyHack** [comment]
Ay,

I got the same behaviour with my code :

```yaml
service: ultima-api
# app and org for use with dashboard.serverless.com
app: ultima-api
org: xxx

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  memorySize: 512
  timeout: 180

  iamManagedPolicies:
    - "arn:aws:iam::xxx:policy/BcnUltima"

  environment:
    TEST: ${self:custom.${self:provider.stage}.s3-temp-bucket}

functions:
  onS3UnzipToS3:
    handler: src/handler.onS3UnzipToS3
    events:
      - s3:
          bucket: ${self:custom.${self:provider.stage}.s3-temp-bucket}
          existing: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  prod:
    s3-temp-bucket: xxx-prod
  dev:
    s3-temp-bucket: xxx-dev
```

If I use xxx-prod bucket all works fine (it was the first bucket I used with my function). But if I use xxx-dev bucket I got same error as @AntonOellerer :

```
ServerlessError: An error occurred: OnS3UnzipToS3CustomS31 - Failed to update resource. Unable to validate the following destination configurations See details in CloudWatch Log: 2020/06/07/[$LATEST]xxx.
```

What can I do to help debugging this ?
