### ISSUE TITLE
Binary and CORS support does not work togather

### ISSUE THREAD

**Issue by prasanthsd** [serverless/serverless#7243]
# Bug Report

## Description

1. What did you do?
Enabled binary media support and enabled cors support for each of the methods in serverless.yml. Setting cors true for the method creates OPTIONS request for the API GW endpoint and a MOCK end point is associated with the request. All of the stuff are created by the serverless framework deploy command without any manual configurations.
1. What happened?
API GW returns a 500 response with message "Internal server error" for OPTIONS requests when binary support is enabled and returns a proper 200 response otherwise when I remove "binaryMediaTypes" from serverless.yml and redeploy. When it returns a 500 response the below log entries can be seen for the API GW:
```
18:18:11 Method request body before transformations: [Binary Data]
18:18:11 Execution failed due to configuration error: Unable to transform response
```
1. What should've happened?
A 200 response should have been returned as with binary support disabled.
1. What's the content of your `serverless.yml` file?
```
provider:
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  someRandomFunction:
    handler: src/handlers/someHandler.getSomeData
    events:
      - http:
          path: getdata
          method: get
          cors: true

resources:
 Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Deployment is a success and no errors are reported.

Similar or dependent issues:
Similar discussions that I have found are linked below
https://forums.aws.amazon.com/thread.jspa?threadID=256140

**Comment by prasanthsd** [comment]
Finally found this after lots of searching around.

https://github.com/duro/serverless-binary-cors

This is not a serverless framework bug but rather a AWS thing which is not documented by them. But would be great to incorporate what this plugin does to the serverless framework itself if binary and cors is enabled at the same time in serverless.yml

**Comment by medikoo** [comment]
Thanks @prasanthsd for that report. We're definitely open for PR that brings that into the framework

**Comment by jimbol** [comment]
Was this ever added?

**Comment by medikoo** [comment]
> Was this ever added?

If it would, issue would be closed

**Comment by AJ84177** [comment]
Is there any progress in this issue :)

**Comment by medikoo** [comment]
@AJ84177 we're open for PR, that introduces similar patch as currently is done by plugin mentioned above. Are you interested in preparing a PR?

**Comment by ezeikel** [comment]
Having the same issue and the plugin mentioned by @prasanthsd didn't work for me. Adding `- serverless-binary-cors` to the plugins array makes no difference. What does work for me is just commenting out `binaryMediaTypes` e.g.

```
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    FRONTEND_URL: ${param:frontend-url, 'http://localhost:3000'}
    DATABASE_URL: ${param:database-url}
    SENTRY_DSN: ${param:sentry-dsn}
    APP_SECRET: ${param:app-secret}
    MAIL_HOST: ${param:mail-host}
    MAIL_PORT: 2525
    MAIL_USER: ${param:mail-user}
    MAIL_PASS: ${param:mail-pass}
    CLOUDINARY_KEY: ${param:cloudinary-key}
    CLOUDINARY_SECRET: ${param:cloudinary-secret}
  # apiGateway:
  #   binaryMediaTypes:
  #     - '*/*'
```

I can't actually remember why I have `binaryMediaTypes` set in the first place 🤔
