### ISSUE TITLE
gomod.sh overwrites go.mod if it exists

### ISSUE THREAD

**Issue by ro-tex** [serverless/serverless#7244]
# Bug Report

## Description

1. What did you do?
I added some dependencies and ran `make` in order to compile all needed binaries.
1. What happened?
My `go.mod` file got overwritten with the default one used by serverless.
1. What should've happened?
My `go.mod` file should have remained untouched as it was tuned for the needs of my project.
1. What's the content of your `serverless.yml` file?
```
service: golambda
app: go-lambda

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  docs:
    handler: bin/docs
    environment:
      JWT_SECRET: ${env:JWT_SECRET}
    events:
      - http:
          path: v0/docs
          method: get
      - http:
          path: v0/docs
          method: post
      - http:
          path: v0/docs/{id}
          method: any

plugins:
  - serverless-dotenv-plugin
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
% SLS_DEBUG=* serverless deploy
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - JWT_SECRET
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.355s 0 retries] describeStacks({ StackName: 'golambda-dev' })
```

Note: I wasn't sure if this behaviour was desired or not, so I [asked on the forum](https://forum.serverless.com/t/why-does-serverless-overwrite-my-go-mod-on-each-build/9976) but I didn't get a response.
