### ISSUE TITLE
AWS ALB event source and provisioned concurrency don't work when enabled together

### ISSUE THREAD

**Issue by ReddytoRumble** [serverless/serverless#7247]
# Bug Report

## Description

1. What did you do?
I am deploying a lambda function with an alb event source and a provisioned concurrency. 

1. What happened?
The target group is created with the lambda as a target and uses the `$Latest` version. The lambda function is created with a provisioned concurrency of 4 which is pinned to a specific version of the lambda function (i.e not Latest) and also creates an alias called `Provisioned`.
None of my requests to the lambda function are making use of the provisioned concurrency because of this misconfiguration

1. What should've happened?
I was expecting the lambda that was registered to the target group to be registered with the version that the `Provisioned` alias was pinned to. 

1. What's the content of your `serverless.yml` file?
```
server: #Function Name
    handler: src/lambda.handler
    environment:
      ...
    memorySize: 512
    timeout: 30
    reservedConcurrency: 100
    provisionedConcurrency: 4
    vpc:
      securityGroupIds: ${self:custom.${self:provider.stage}.appSecurityGroupIds}
      subnetIds: ${self:custom.${self:provider.stage}.appSubnetIds}
    events:
      - alb:
          listenerArn: 
            Ref: Listener
          priority: 70
          conditions:
            path: /*
            host: ${self:custom.${self:provider.stage}.dnsRecordName}
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
No errors reported with serverless deploy command

Similar or dependent issues:
