### ISSUE TITLE
event.query instead of event.queryStringParameters with lambda integration

### ISSUE THREAD

**Issue by VersBinarii** [serverless/serverless#7249]
# Bug Report

## Description
When using lambda integraion the event object contains the 'query' field instead of expected 'queryStringParameters'. This becomes troublesome when developing code with Typescript.

The following:
```
foo:
    handler: handler.foo
    events:
      - http:
          path: /foo
          method: get
          integration: lambda
```

results in this template for both content types (`application/json` and `application/x-www-form-urlencoded`) to define 'query' field.

Similar or dependent issues:

- #2958
