### ISSUE TITLE
SSM warning is now throwing an error

### ISSUE THREAD

**Issue by jeremiahlukus** [serverless/serverless#7255]
# Bug Report

## Description

1. What did you do? upgrade serverless
1. What happened? 
```
Serverless Error ---------------------------------------
  ParameterNotFound
```
1. What should've happened? 
```
 Serverless Warning
 A valid SSM parameter to satisfy the declaration .... could not be found
```
1. What's the content of your `serverless.yml` file?
my stages are:

```
int1:
  basicAuthUsername: ${ssm:/app/int/basic_auth_user}
uat:
  basicAuthUsername: ${ssm:/app/uat/basic_auth_user}
prod:
  basicAuthUsername: ${ssm:/app/prod/basic_auth_user}
```
int1 and uat live in the same aws account prod is in a different account. This did just spit out a warning saying this doesn't exist now i cannot deploy the app. 

I think just not evaluating other stages would fix this issue. ie. when i do `sls deploy --stage int` why should the prod ssm get executed?
