### ISSUE TITLE
Cannot set $default, $connect, $disconnect on previously deployed API Websocket Gateway

### ISSUE THREAD

**Issue by cbarlow1993** [serverless/serverless#7260]
# Bug Report
When utilizing an already deployed API Websocket Gateway, $connect, $disconnect and $default can not be deployed. 

`An error occurred: SconnectWebsocketsRoute - Route with key $connect already exists for this API (Service: AmazonApiGatewayV2; Status Code: 409; Error Code: ConflictException; Request ID: XXX).`

## Description
I declare by Websocket API  Gateway in another serverless file and import the gateway into a separate file where I declare the routes. No routes are set in other files. Instead, I get the error which is understandable, but as I haven't declared the routes, I'd expect them to be able to be managed.
```
Some omitted... 
provider:
  name: aws
  region: eu-west-1
  stage: dev2
  memorySize: 256
  runtime: nodejs12.x

  apiGateway:
    websocketApiId: 
      Fn::ImportValue: ApiGatewayWebsocketApiId

functions:
  connect:
      handler: websocketManager.connect
      events:
        - websocket:
            route: $connect # authorizers are only for connect routes
            authorizer:
              # depends on the Authorizer in Auth
              arn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:custom.STAGE}-authorizer
              identitySource:
                - 'route.request.querystring.token'

  disconnect:
    handler: websocketManager.disconnect
    events:
      - websocket:
          route: $disconnect
    
  default:
    handler: default.main
    events:
      - websocket:
          route: $default

```

 ```
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.3.1
     Framework Version:         1.60.4
     Plugin Version:            3.2.6
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```
