### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by nasat75** [serverless/serverless#7268]
Hello,

Seems like I cannot invoke a part of lambda on terminal.
but it's success invoking by vanilla lambda.

Here's serverless config

#### summary
- it's success that below below functions 
  - sendOsaka
  - sendDev
- but, a rest of function, `sendTokyo` can't invoked...

#### this is my error console

```
$ sls invoke -f sendTokyo -p ./button-dummy.json --log --aws-profile tambourine-domestic
Serverless: DOTENV: Loading environment variables from .env:
Serverless: 	 - WEBHOOK_OSAKA
Serverless: 	 - WEBHOOK_TOKYO
Serverless: 	 - WEBHOOK_DEV
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: connect ECONNREFUSED 127.0.0.1:80",
    "trace": [
        "Runtime.UnhandledPromiseRejection: Error: connect ECONNREFUSED 127.0.0.1:80",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:210:5)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:485:21)",
        "    at processPromiseRejections (internal/process/promises.js:201:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:32)"
    ]
}
--------------------------------------------------------------------
START RequestId: 347d622c-2f48-4164-94a9-2e4d4c9a761a Version: $LATEST
2020-01-29 19:30:13.817 (+09:00)	347d622c-2f48-4164-94a9-2e4d4c9a761a	INFO	{ text: 'コーヒー淹れたよ' }2020-01-29T10:30:13.818Z
REPORT RequestId: 347d622c-2f48-4164-94a9-2e4d4c9a761a	Duration: 75.74 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 28 MB

Unknown application error occurred



  Error --------------------------------------------------

  Invoked function failed

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           12.3.1
     Serverless Version:     1.21.1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Here's serverless config:

```
service:
  name: notify-coffee
# app and org for use with dashboard.serverless.com
app: notify-coffee
org: nasat75

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  region: ap-northeast-1

functions:
  sendOsaka:
    handler: notify.handle
    environment:
      WEBHOOK_URL: ${env:WEBHOOK_OSAKA}
    events:
      - http:
          path: /osaka
          method: post
          response:
            headers:
              Content-Type: "'application/json'"
  sendTokyo:
    handler: notify.handle
    environment:
      WEBHOOK_URL: ${env:WEBHOOK_TOKYO}
    events:
      - http:
          path: /tokyo
          method: post
          response:
            headers:
              Content-Type: "'application/json'"
```
