### ISSUE TITLE
Layer not deployed when foldername contains a dots.

### ISSUE THREAD

**Issue by Brianvdb** [serverless/serverless#7280]
# Bug Report

### What did you do?

Build ImageMagick and added to my layers.

### What happened?

Got an error:
```
Error: ENOENT: no such file or directory, open '/app/layer/imagemagick/etc/X11/fontpath.d/default-ghostscript'
```
The file exists. When I change the directory name fontpath.d to something without a dot in it, then it works..

### What should've happened?
Directory with a dot in the name should have worked.

### What's the content of your `serverless.yml` file?
```
service: test

provider:
  name: aws
  runtime: nodejs12.x

package:
  individually: true
  exclude:
    - layer/**
    - functions/**
    - node_modules/**
    - package.json
    - package-lock.json
    - serverless.yml

layers:
  imagemagick:
    name: imagemagick
    path: layer/imagemagick
    package:
      artificat: layer/imagemagick.zip
```
Only showing relevant part..

### Similar or dependent issues:
- #5934 seems to be fixed before, but bug was re-introduced.
