### ISSUE TITLE
ApiGateway Method should be dependent on the alias being provisioned 

### ISSUE THREAD

**Issue by Arditc** [serverless/serverless#7284]
# Bug Report

## Description
If you have a lambda already deployed via serverless, and then you add provisioning to the lambda existing lambda which is already running, you will get an `Internal Server Error` from the API Gateway until the lambda with the alias `provisioned` has the `provisioned` lambda. 

1. What did you do?
Create this type of stack:
- API Gateway => Lamda Proxy => Lambda
 - Deploy and run.
- should be getting a `200` status code from the lambda via the API Gateway
- Add provisioning to the lambda ( check message below to see before and after changes done to the serverless.yml)
- During the deployment of the provisioning, hit the API Gateway, you'll get a 500 error

1. What should've happened?

I could see in the CF stack that's being generated:

In the `AWS::ApiGateway::Method` section there is **no** DependsOn section which tells it to wait until the lambda has been fully provisioned before apply this step. This is to ensure that we have the provisioned resource.

```
"ApiGatewayMethodApiVarGet": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "GET",
        "RequestParameters": {
          "method.request.path.id": true
        },
        "ResourceId": {
          "Ref": "ApiGatewayResourceApiVar"
        }
}
```

Let me know if you need any more information.

**Comment by Arditc** [comment]
Before:
```service:
  name: test

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-import-apigateway
  - serverless-prune-plugin
  - serverless-plugin-git-variables

provider:
  name: aws
  logs:
    restApi: true
  runtime: nodejs10.x
  region: ${env:AWS_REGION}
  deploymentBucket:
    name: artifacts-${env:AWS_REGION}-${env:AWS_ACCOUNT_ID}

functions:
  test:
    events:
      - http:
          method: get
          path: api/test
    handler: /src/index.handler
    onError: ${ssm:/dead-letter-queue/sns-topic/arn}
    role: ${ssm:/lambda_iam_role/arn}
```

After:

```
service:
  name: test

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-import-apigateway
  - serverless-prune-plugin
  - serverless-plugin-git-variables

provider:
  name: aws
  logs:
    restApi: true
  runtime: nodejs10.x
  region: ${env:AWS_REGION}
  deploymentBucket:
    name: artifacts-${env:AWS_REGION}-${env:AWS_ACCOUNT_ID}

functions:
  test:
    events:
      - http:
          method: get
          path: api/test
    handler: /src/index.handler
    onError: ${ssm:/dead-letter-queue/sns-topic/arn}
    role: ${ssm:/lambda_iam_role/arn}
    provisionedConcurrency: 1
```
