### ISSUE TITLE
Syntax Error - missing ")" in /var/task/serverless_sdk/index.js file after deployment

### ISSUE THREAD

**Issue by smlok** [serverless/serverless#7287]
# Bug Report

## Description

1. What did you do?
I deployed a serverless React Next.js app to AWS Lambda

2. What happened?
Lambda shows green "Update complete" and all looks fine there, but when I follow the provided endpoint link, the browser returns {"message": "Internal server error"}.

3. What should've happened?
It should have shown my app in the browser running on AWS Lambda server.

4. What's the content of your `serverless.yml` file?
```
org: fkolms
app: ssr-react-next-app
service: ssr-react-next

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}
  
plugins:
  - serverless-apigw-binary
  # - serverless-domain-manager

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN}
    basePath: ''
    stage: ${self:custom.secrets.NODE_ENV}
    createRoute53Record: true
    # endpointType: 'regional'
    # if the ACM certificate is created in a region except for `'us-east-1'` you need `endpointType: 'regional'`
```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
There were no errors while deploying the app. However, after deploying I can see in serverless dashboard that there is a syntax error because of a "missing ) after an argument list" /var/task/serverless_sdk/index.js file on line 9. I can't find that file on my local drive so I assume the serverless file is not compiled correctly. Running Node 12 and latest npm versions.
