### ISSUE TITLE
Profile <NAME> does not exists

### ISSUE THREAD

**Issue by paulcruse-syn** [serverless/serverless#7290]
# Bug Report

## Description

1. What did you do?

I am trying to package my serverless package command within AWS codebuild using this command:
`serverless package --stage $BUILD_STAGE --aws_envs cloud --profile $BUILD_STAGE --region $AWS_REGION`
Here is the full buildspec: 
```yml
version: 0.2
env:
    variables:
        REPO_NAME: api-node-enogen-contracts
        LOCAL_BUILD_DIR: .serverless
        S3_ARTIFACT_BUCKET: 's3://syngenta-cicd-build-artifacts'
        dev: 'arn:aws:iam::990176370942:role/CICD'
        qa: 'arn:aws:iam::743443941247:role/CICD'
        uat: 'arn:aws:iam::052908401056:role/CICD'
        prod: 'arn:aws:iam::613836678580:role/CICD'
        BUILD_STAGES: |
            dev
            qa
            uat
            prod
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - npm install || exit 1
            - npm install -g serverless
    pre_build:
        commands:
            - TRIGGER_SOURCE=$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -f1 -d'/')
            - TRIGGER_ATRIBUTE=$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -f2 -d'/')
            - |
                if expr "${TRIGGER_SOURCE}" != "pr"; then
                    if expr "${TRIGGER_SOURCE}" == "tag"; then
                        DEPLOY_STAGE=$TRIGGER_ATRIBUTE
                    elif expr "${TRIGGER_SOURCE}" == "branch" && expr "${TRIGGER_ATRIBUTE}" == "master"; then
                        DEPLOY_STAGE=dev
                    fi
                fi
            - |
                if expr "${DEPLOY_STAGE}"; then
                    aws configure --profile default set aws_access_key_id $AWS_ACCESS_KEY_ID
                    aws configure --profile default set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                    aws configure --profile default set output json
                    aws configure --profile default set region $AWS_REGION
                    aws configure list
                fi
        finally:
            - echo "FINISHED PRE-BUILD"
    build:
        commands:
            # - npm run scan || exit 1
            - |
                if expr "${DEPLOY_STAGE}"; then
                    for BUILD_STAGE in $BUILD_STAGES
                    do
                        echo "ARTIFACTING $BUILD_STAGE"
                        BUILD_ROLE_ARN=$(eval echo \${${BUILD_STAGE}})
                        aws configure set role_arn $BUILD_ROLE_ARN --profile $BUILD_STAGE
                        aws configure set profile.$BUILD_STAGE.source_profile default
                        aws configure list --profile $BUILD_STAGE
                        SLS_DEBUG=* serverless package --stage $BUILD_STAGE --aws_envs cloud --profile $BUILD_STAGE --region $AWS_REGION
                        aws s3 sync $LOCAL_BUILD_DIR $S3_ARTIFACT_BUCKET/$REPO_NAME/$BUILD_STAGE/$CODEBUILD_RESOLVED_SOURCE_VERSION
                        rm -rf $LOCAL_BUILD_DIR
                        echo "$BUILD_STAGE ARTIFACT UPLOADED"
                    done
                fi
        finally:
            - echo "FINISHED BUILD"
    post_build:
        commands:
            - |
                if expr "${DEPLOY_STAGE}"; then
                    DEPLOY_ROLE_ARN=$(eval echo \${${DEPLOY_STAGE}})
                    DEPLOY_ROLE=$(aws sts assume-role --role-arn $DEPLOY_ROLE_ARN --role-session-name $DEPLOY_STAGE-$REPO_NAME --output json)
                    AWS_ACCESS_KEY_ID=$(echo $DEPLOY_ROLE | jq -r .Credentials.AccessKeyId)
                    AWS_SECRET_ACCESS_KEY=$(echo $DEPLOY_ROLE | jq -r .Credentials.SecretAccessKey)
                    AWS_SESSION_TOKEN=$(echo $DEPLOY_ROLE | jq -r .Credentials.SessionToken)
                    aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                    aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
                    aws configure set profile.$DEPLOY_STAGE.source_profile default
                    export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
                    export AWS_SDK_LOAD_CONFIG=1
                fi
            - |
                if expr "${DEPLOY_STAGE}"; then
                    echo "DOWNLOADING $DEPLOY_STAGE ARTIFACT"
                    mkdir $LOCAL_BUILD_DIR || exit 1
                    aws s3 sync $S3_ARTIFACT_BUCKET/$REPO_NAME/$DEPLOY_STAGE/$CODEBUILD_RESOLVED_SOURCE_VERSION $LOCAL_BUILD_DIR || exit 1
                    echo "DEPLOYING $DEPLOY_STAGE"
                    serverless deploy --package $LOCAL_BUILD_DIR --stage $DEPLOY_STAGE --aws_envs cloud --profile $DEPLOY_STAGE --region $AWS_REGION || exit 1
                    echo "FINISHED $DEPLOY_STAGE DEPLOYMENT"
                fi
        finally:
            - echo "FINISHED POST-BUILD"
```

1. What happened?
The package command errors out saying:
```bash
Error ----------------------------------------------------

Error: Profile dev does not exist
```

1. What should've happened?
It should've packaged

1. What's the content of your `serverless.yml` file?
```yml
app: enogen
service: contract
package:
    individually: true
    exclude:
        - .*
        - .**/**
        - aws/**
        - test/**
        - README.md
        - buildspec.yml
        - serverless.yml
        - package.json
        - package-lock.json
custom:
    authorizer: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):authorizer}
    cors: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):cors}
    policies: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):policies}
    environment: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):environment}
    serverless-offline:
        port: 9000
        stage: local
        prefix: ${self:service}
        region: us-east-2
        noAuth: true
    dynamodb:
        stages:
            - local
        start:
            port: 4000
            inMemory: true
            migrate: true
            seed: true
        seed:
            contracts:
                sources:
                    -
                        table: ${self:provider.stackTags.name}-contracts
                        sources: [./test/seed/contracts.json]
provider:
    name: aws
    runtime: nodejs12.x
    logRetentionInDays: 14
    versionFunctions: false
    endpointType: regional
    environment: ${self:custom.environment}
    profile: ${opt:stage, 'local'}
    stage: ${opt:stage, 'local'}
    region: ${opt:region, 'us-east-2'}
    stackName: ${self:provider.stackTags.name}
    apiName: ${self:provider.stackTags.name}
    deploymentBucket:
        name: '${self:provider.stage}-syngenta-deployments'
    stackTags:
        name: ${self:provider.stage}-${self:app}-${self:service}
        service: ${self:service}
        environment: ${self:provider.stage}
        managed-by: serverless
    iamRoleStatements:
        - '${file(./aws/iamroles/dynamodb.yml)}'
        - '${file(./aws/iamroles/sns.yml)}'
resources:
    - '${file(./aws/resources/apigateway.yml)}'
    - '${file(./aws/resources/dynamodb.yml)}'
functions:
    v1-apigateway-handler:
        name: ${self:provider.stackTags.name}-v1-apigateway-handler
        description: API Router handler
        handler: application/v1/controller/apigateway/_router.route
        memorySize: 512
        timeout: 30
        events:
            - http:
                path: /v1
                method: ANY
                cors: ${self:custom.cors}
                authorizer: ${self:custom.authorizer}
            - http:
                path: /v1/{proxy+}
                method: ANY
                cors: ${self:custom.cors}
                authorizer: ${self:custom.authorizer}
plugins:
    - serverless-dynamodb-local
    - serverless-offline
    - serverless-plugin-bind-deployment-id
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```

Serverless: Load command interactiveCli
--
154 | Serverless: Load command config
155 | Serverless: Load command config:credentials
156 | Serverless: Load command config:tabcompletion
157 | Serverless: Load command config:tabcompletion:install
158 | Serverless: Load command config:tabcompletion:uninstall
159 | Serverless: Load command create
160 | Serverless: Load command install
161 | Serverless: Load command package
162 | Serverless: Load command deploy
163 | Serverless: Load command deploy:function
164 | Serverless: Load command deploy:list
165 | Serverless: Load command deploy:list:functions
166 | Serverless: Load command invoke
167 | Serverless: Load command invoke:local
168 | Serverless: Load command info
169 | Serverless: Load command logs
170 | Serverless: Load command metrics
171 | Serverless: Load command print
172 | Serverless: Load command remove
173 | Serverless: Load command rollback
174 | Serverless: Load command rollback:function
175 | Serverless: Load command slstats
176 | Serverless: Load command plugin
177 | Serverless: Load command plugin
178 | Serverless: Load command plugin:install
179 | Serverless: Load command plugin
180 | Serverless: Load command plugin:uninstall
181 | Serverless: Load command plugin
182 | Serverless: Load command plugin:list
183 | Serverless: Load command plugin
184 | Serverless: Load command plugin:search
185 | Serverless: Load command config
186 | Serverless: Load command config:credentials
187 | Serverless: Load command rollback
188 | Serverless: Load command rollback:function
189 | Serverless: Load command upgrade
190 | Serverless: Load command uninstall
191 | Serverless: Load command dynamodb
192 | Serverless: Load command dynamodb:migrate
193 | Serverless: Load command dynamodb:seed
194 | Serverless: Load command dynamodb:start
195 | Serverless: Load command dynamodb:noStart
196 | Serverless: Load command dynamodb:remove
197 | Serverless: Load command dynamodb:install
198 | Serverless: Load command offline
199 | Serverless: Load command offline:start
200 | Serverless: Load command login
201 | Serverless: Load command logout
202 | Serverless: Load command generate-event
203 | Serverless: Load command test
204 | Serverless: Load command dashboard
205 | Serverless: Load command output
206 | Serverless: Load command output:get
207 | Serverless: Load command output:list
208 | Serverless: Load command param
209 | Serverless: Load command param:get
210 | Serverless: Load command param:list
211 |  
212 | Error --------------------------------------------------
213 |  
214 | Error: Profile dev does not exist
215 | at Object.addProfileCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:100:15)
216 | at AwsProvider.getCredentials (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:374:12)
217 | at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:226:48)
218 | at Variables.getValueFromCf (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:756:8)
219 | at Variables.getValueFromSource (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:567:17)
220 | at Variables.splitAndGet (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:436:17)
221 | at _.map.match (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:373:41)
222 | at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
223 | at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
224 | at Variables.populateMatches (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:373:14)
225 | at Variables.populateValue (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:404:30)
226 | at _.map.variable (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:286:12)
227 | at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
228 | at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
229 | at Variables.populateVariables (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:285:14)
230 | at Variables.populateObjectImpl (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:318:30)
231 | From previous event:
232 | at Variables.populateObjectImpl (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:322:65)
233 | at prepopulateService.then (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:199:16)
234 | at runCallback (timers.js:705:18)
235 | at tryOnImmediate (timers.js:676:5)
236 | at processImmediate (timers.js:658:5)
237 | at process.topLevelDomainCallback (domain.js:126:23)
238 | From previous event:
239 | at initialCall (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:198:10)
240 | at Variables.initialCall (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:102:12)
241 | at Variables.populateService (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:196:17)
242 | at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:120:27)
243 | at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:75:30)
244 | at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
245 | at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
246 | at FSReqWrap.args [as oncomplete] (fs.js:140:20)
247 | From previous event:
248 | at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless.js:75:8)
249 | at runCallback (timers.js:705:18)
250 | at tryOnImmediate (timers.js:676:5)
251 | at processImmediate (timers.js:658:5)
252 | at process.topLevelDomainCallback (domain.js:126:23)
253 | From previous event:
254 | at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:64:4)
255 | at Module._compile (internal/modules/cjs/loader.js:778:30)
256 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
257 | at Module.load (internal/modules/cjs/loader.js:653:32)
258 | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
259 | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
260 | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
261 | at startup (internal/bootstrap/node.js:283:19)
262 | at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
263 |  
264 | Get Support --------------------------------------------
265 | Docs:          docs.serverless.com
266 | Bugs:          github.com/serverless/serverless/issues
267 | Issues:        forum.serverless.com
268 |  
269 | Your Environment Information ---------------------------
270 | Operating System:          linux
271 | Node Version:              10.16.3
272 | Framework Version:         1.62.0
273 | Plugin Version:            3.3.0
274 | SDK Version:               2.3.0
275 | Components Core Version:   1.1.2
276 | Components CLI Version:    1.4.0
```
