### ISSUE TITLE
Stack with id [STACK-NAME] does not exist... in linux AWS CodeBuild multi-account deployment

### ISSUE THREAD

**Issue by paulcruse-syn** [serverless/serverless#7291]
# Bug Report

## Description
1. What did you do?
Trying to package and deploy my app using AWS cocde-build
1. What happened?
It provides the error described in the title
1. What should've happened?
It should've just deployed
1. What's the content of your `serverless.yml` file?
```yml
app: xxxxxx
service: contract
package:
    individually: true
    exclude:
        - .*
        - .**/**
        - aws/**
        - test/**
        - README.md
        - buildspec.yml
        - serverless.yml
        - package.json
        - package-lock.json
custom:
    authorizer: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):authorizer}
    cors: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):cors}
    policies: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):policies}
    environment: ${file(./aws/envs/${opt:aws_envs, 'local'}.yml):environment}
    serverless-offline:
        port: 9000
        stage: local
        prefix: ${self:service}
        region: us-east-2
        noAuth: true
    dynamodb:
        stages:
            - local
        start:
            port: 4000
            inMemory: true
            migrate: true
            seed: true
        seed:
            contracts:
                sources:
                    -
                        table: ${self:provider.stackTags.name}-contracts
                        sources: [./test/seed/contracts.json]
provider:
    name: aws
    runtime: nodejs12.x
    logRetentionInDays: 14
    versionFunctions: false
    endpointType: regional
    environment: ${self:custom.environment}
    stage: ${opt:stage, 'local'}
    profile: ${opt:stage, 'local'}
    region: ${opt:region, 'us-east-2'}
    stackName: ${self:provider.stackTags.name}
    apiName: ${self:provider.stackTags.name}
    deploymentBucket:
        name: '${self:provider.stage}-xxxxxx-deployments'
    stackTags:
        name: ${self:provider.stage}-${self:app}-${self:service}
        service: ${self:service}
        environment: ${self:provider.stage}
        managed-by: serverless
    iamRoleStatements:
        - '${file(./aws/iamroles/dynamodb.yml)}'
        - '${file(./aws/iamroles/sns.yml)}'
resources:
    - '${file(./aws/resources/apigateway.yml)}'
    - '${file(./aws/resources/dynamodb.yml)}'
functions:
    v1-apigateway-handler:
        name: ${self:provider.stackTags.name}-v1-apigateway-handler
        description: API Router handler
        handler: application/v1/controller/apigateway/_router.route
        memorySize: 512
        timeout: 30
        events:
            - http:
                path: /v1
                method: ANY
                cors: ${self:custom.cors}
                authorizer: ${self:custom.authorizer}
            - http:
                path: /v1/{proxy+}
                method: ANY
                cors: ${self:custom.cors}
                authorizer: ${self:custom.authorizer}
plugins:
    - serverless-dynamodb-local
    - serverless-offline
    - serverless-plugin-bind-deployment-id
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```bash
Serverless: Load command interactiveCli
--
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command dynamodb
Serverless: Load command dynamodb:migrate
Serverless: Load command dynamodb:seed
Serverless: Load command dynamodb:start
Serverless: Load command dynamodb:noStart
Serverless: Load command dynamodb:remove
Serverless: Load command dynamodb:install
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: [AWS cloudformation 400 0.066s 0 retries] describeStacks({ StackName: 'dev-platform-authorizer' })
Serverless: [AWS cloudformation 400 0.061s 0 retries] describeStacks({ StackName: 'dev-platform-model-revisions' })
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Stack with id dev-platform-authorizer does not exist
      at promise.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:329:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.16.3
     Framework Version:         1.62.0
     Plugin Version:            3.3.0
     SDK Version:               2.3.0
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

I tested to make sure it was there by running this command in codebuild:
`aws cloudformation describe-stacks --profile dev --stack-name dev-platform-authorizer --region us-east-2` and so I know it works...
