### ISSUE TITLE
Allow omitting the AWS::Lambda::Permission for cross-account authorizers

### ISSUE THREAD

**Issue by glb** [serverless/serverless#7296]
# Feature Proposal

Support skipping the creation of an `AWS::Lambda::Permission` resource for cross-account authorizer functions.

### Use case

When you specify an authorizer ARN for a function, the AWS provider for `serverless` currently generates an `AWS::Lambda::Permission` resource in the CloudFormation Template.

If the authorizer is [in another account](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-lambda-authorizer-cross-account-lambda-authorizer.html), creating the `AWS::Lambda::Permission` resource fails because the stack doesn't have permissions to modify Lambda permissions across accounts.

It would be good to be able to suppress generating this resource when the authorizer is a cross-account Lambda authorizer.

### Proposed config

```
functions:
  sample:
    ...
    events:
      - http:
          ...
          authorizer:
            name: authorizer
            arn: arn:aws:lambda:REGION:ACCOUNT:function:FUNCTION_NAME
            crossAccount: true
```

When `event.authorizer.crossAccount` is true, skip generating the `AWS::Lambda::Permission` resource.

## Related code

https://github.com/serverless/serverless/blob/b9c8049455b4f48ce9247edeb6561e5c302373ae/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js#L60
