### ISSUE TITLE
Package individually at the function level is broken

### ISSUE THREAD

**Issue by juanjoDiaz** [serverless/serverless#7303]
# Bug Report

## Description

Set `package individually` at a function level but not at the service level.
This actually works if I set `package individually` to true at the service level 

1. What happened?

The function was package individually:

```yaml
myFunc:
  package:
    individually: true
    exclude:
      - '**'
    include:
      - 'myFolder/**'

```

However, all the services files are included in the generated bundle.

I expected that only the files in `myFolder` would have been added.

The problem seems to be at https://github.com/serverless/serverless/blob/master/lib/plugins/package/lib/packageService.js#L21

`this.serverless.service.package.include` should be empty since it's not defined at the service level instead of containing all the files in the project. But I can't find where it's being populated.
Or is there any other way to achieve this that I'm missing?

**Comment by medikoo** [comment]
@juanjoDiaz thanks for report. `exclude` and `include` settings expect an array. Therefore it should be configured as:

```yaml
myFunc:
  package:
    individually: true
    exclude:
      - '**'
    include:
      - 'myFolder/**'
```

Such configuration errors should be picked in future by schema validation: https://github.com/serverless/serverless/issues/6562

**Comment by juanjoDiaz** [comment]
Yeah. My bad when fast typing the example. I fixed it.

The issue is still there.
Package individually at the function level doesn't work.

**Comment by medikoo** [comment]
@juanjoDiaz I'm not able to reproduce that, e.g. see this test case: https://github.com/medikoo/test-serverless/tree/489b285381bd83029e07906bc101bfc7d6ca63dd It packages lambda per instructions as expected

**Comment by blairexico** [comment]
I am seeing same issue:

```
    forwardIncomingHeaders:
        handler: lambdas/forwardIncomingHeaders.handler
        package:
            individually: true
            exclude:
                - node_modules/**
        lambdaAtEdge:
            - distribution: 'ApiDistribution' # this name is set by the cloudfront plugin
              eventType: 'viewer-response'
        memorySize: 128
        timeout: 5
```

I get just one zip file, and I cant deploy because the file is too big for edge.

An error occurred: ApiDistribution - The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 5028222 Max allowed: 1048576 Function

**Comment by joker-8989** [comment]
I'm having the same issue with the latest 1.80.0 version.
If function-level packaging doesn't work,
Only packaging at the service level.
Configurations with many Lambda deployments will have a significant performance penalty.

**Comment by medikoo** [comment]
@joker-8989 can you prepare as simple as possible test case that exposes the issue?

**Comment by stevematdavies** [comment]
This is now also an issue at the service level

**Comment by medikoo** [comment]
@stevematdavies can you prepare as simple as possible test case that reproduces the issue?

**Comment by stevematdavies** [comment]
Our code is a rather involved code and has some private / corporate features so I cant copy it here.
However, the issue is exactly as shown above

In our `serverless.yml `file

we have

```
 package:
    individually: true
    package:
      exclude:
        - ./**
      include:
        - handler.js
```

However, on deploy, all excluded folders are added
