### ISSUE TITLE
Fn::Join is using last token/line as entire string instead of only the tokens contents

### ISSUE THREAD

**Issue by jenlcabral** [serverless/serverless#7310]
# Bug Report

## Description

1. What did you do?
Updated version of serverless from 1.39.1 to 1.62.0. No serverless.yml changes. 
1. What happened?
```
    - Effect: Allow
      Action:
        - ssm:GetParameters
      Resource:
        - Fn::Join:
          - ""
          - - "arn:aws:ssm:us-east-1:000000000000:parameter/"
            - "named.db."
            - ${self:custom.currentStage}
            - ".*"
```
now the creates a resource that looks like this:
```"arn:aws:ssm:us-east-1:000000000000:parameter/named.db.development - \".*\""]```

1. What should've happened?
When we were using 1.39.1, the resource was created without the extra escape characters:
```"arn:aws:ssm:us-east-1:000000000000:parameter/named.db.development.*"```

1. What's the content of your `serverless.yml` file?
```
service:
  name: polaris-lambda

custom:
  defaultStage: development
  currentStage: ${opt:env, self:custom.defaultStage}

provider:
  name: aws
  region: ${file(./config/${opt:env}.json):region}
  runtime: nodejs12.x
  timeout: 30 # seconds
  stage: ${self:custom.currentStage}
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - ssm:GetParameters
      Resource:
        - Fn::Join:
          - ""
          - - "arn:aws:ssm:us-east-1:000000000000:parameter/"
            - "named.db."
            - ${self:custom.currentStage}
            - ".*"
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
No errors in the output. Can be provided if necessary. 

Similar or dependent issues:

- #12345
