### ISSUE TITLE
Can't add CloudWatch subscription to function with Enterprise

### ISSUE THREAD

**Issue by revmischa** [serverless/serverless#7316]
I cannot add a cloudwatch subscription for logs when I am using Enterprise.

```
functions:
  monitor:  # client monitor poller
    handler: handler.monitor_entry
    greengrass:
      subscriptions:
        - target: "cloud"
          subject: '/metromon/client/#'

  logger:  # handler for logs generated by monitor functions
    handler: handler.logger_entry
    events:
      # trigger on events from lambda logs
      - cloudwatchLog: "/aws/greengrass/Lambda/#{AWS::Region}/#{AWS::AccountId}/${self:custom.stackName}-monitor"
```
Results in the error:
`An error occurred: CloudWatchLogsSubscriptionFilterClientActiveMessageLogGroup - Resource limit exceeded. (Service: AWSLogs; Status Code: 400; Error Code: LimitExceededException; Request ID: ea660d28-cf2f-4e20-8a11-3ddf515b2717).`

I assume because Enterprise attaches its own CWL subscription to each function and there is a maximum of one. My setup works without Enterprise fine.
