### ISSUE TITLE
deploy --package with layers issue

### ISSUE THREAD

**Issue by ed-sparkes** [serverless/serverless#7318]
# Bug Report

## Description

1. What did you do?

I create a package in my CI using `sls package --package /tmp/mypackage` and this successfully packages everything including my layers. 

I then store the output of the publish as a build artefact and my CI gets the artefact  to deploy. 

I deploy using `sls deploy --package /tmp/mypackage` pointing to the artefact folder that was created during packaging. 

1. What happened?

I get an error saying File does not exist `/original/source/location/.serverless/rpackages.zip` 

1. What should've happened?

Should look for the layer zip in the package folder provided not in the original source location, i don't have the original source, just the output of the packaging. The output has everything it needs but the deploy seems to look for the layer zips in the original source location rather than the package location

1. What's the content of your `serverless.yml` file?

```
service: cj-rfunctions

provider:
  name: aws

# you can overwrite defaults here
  stage: dev
  region: eu-west-1
  
package:
  include:
    - src/**
  exclude:
    - serverless.yml
    - package.json
    - yarn.lock
    - node_modules/**
    - bootstrap.sh

layers:
  rpackages:
    path: rpackages
functions:
  plackettLuce:
    handler: plackettLuce.handler
    description: plackettLuce R
    memorySize: 3008
    timeout: 60
    runtime: provided
    layers: 
      - arn:aws:lambda:eu-west-1:131329294410:layer:r-runtime-3_6_0:12
      - arn:aws:lambda:eu-west-1:131329294410:layer:r-recommended-3_6_0:12
      - {Ref: RpackagesLambdaLayer}
resources:
  - Outputs:
        PlackettLuceArn:
          Value: 
            Fn::GetAtt: PlackettLuceLambdaFunction.Arn
          Export:
            Name: ${self:custom.stage}-PlackettLuceFunctionArn
plugins:


custom:
    # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
```
