### ISSUE TITLE
Variable interpolation when not using custom  

### ISSUE THREAD

**Issue by aslafy-z** [serverless/serverless#7325]
# Bug Report

## Description

1. What did you do?

```shell
$ serverless print
```

1. What happened?

It shows warnings

1. What should've happened?

There should be no warnings

1. What's the content of your `serverless.yml` file?

Fails with warnings when getting values from `custom2` object: https://gist.github.com/aslafy-z/0f5486f83c388936e38a548bff123a33

Works when getting values from `custom` object: https://gist.github.com/aslafy-z/d850252aeeaf5148a5afffdae770a23e

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable

N/A

1. Questions

I've been looking for documentation for a special treatment of the `custom` object, but was unable to find so. How can I reference variables within another key that `custom` without triggering warnings? It is a bug or a feature?

Thank you

**Comment by medikoo** [comment]
Thanks @aslafy-z for report. I believe `custom` is the channel through which user custom config should go.

Will following not work for you?

```yaml
service: test
provider: aws
custom:
  someDict:
    foo: foo
    bar: bar
  type: ${self:custom.someDict.${opt:type}}
```
