### ISSUE TITLE
Cloudformation unable to rollback with provisioned concurrency setup

### ISSUE THREAD

**Issue by jeffjen** [serverless/serverless#7329]
# Bug Report

## Description

1. What did you do?

Deployed a serverless application with provisioned concurrency setup, but failed due to FUNCTION_ERROR_INIT_FAILURE

1. What happened?

When cloudformation attempts to rollback, the process failed with  

> Invalid function version N. Function version N is already included in routing configuration. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 980bae52-2db6-4770-a81b-4fc2a53dfc87)

Cloudformation Stack gets stuck in this state.  The only resolution is to delete the stack. 

1. What should've happened?

Cloudformation  should be able to rollback to previous state, allowing new stack updates

1. What's the content of your `serverless.yml` file?

```yaml
service: django-app

package:
  individually: true
  exclude:
    - "**"

plugins:
  - serverless-wsgi

custom:
  timestamp: ${file(./docker/sls/timestamp.js):now}
  version: 0.0.0-${self:provider.stage}-${self:custom.timestamp}
  stage: ${opt:stage, 'at-ut'}
  wsgi:
    packRequirements: false
    app: django_app.wsgi.application

x-lambda-property: &lambda-property
  role: ${ssm:/infra/${self:provider.stage}/v1/lambda/serverless/role-for-vpc-exec}
  layers:
    - ${cf:django-${self:provider.stage}.DjangoLayerExport}
    - ${cf:secrets-${self:provider.stage}.SecretsLayerExport}

provider:
  name: aws
  runtime: python3.6
  stage: ${env:DEPLOY_STAGE, 'at-ut'}
  region: ap-northeast-1
  memorySize: 256
  logRetentionInDays: 180
  tags:
    version: ${self:custom.version}
  deploymentBucket:
    name: ${ssm:/infra/${self:provider.stage}/v1/lambda/serverless/bucket-name}
  environment:
    DEPLOY_STATUS: ${self:provider.stage, 'development-aws'}
    DEPLOY_ENV_BUCKET: ${ssm:/infra/${self:provider.stage}/v1/lambda/serverless/bucket-name}
    DEPLOY_ENV_KEY: dotenv/${self:service}/${self:provider.stage}/.env
    DEPLOY_AT: ${self:custom.timestamp}
  vpc:
    securityGroupIds:
      "Fn::Split":
        - ","
        - ${ssm:/infra/${self:provider.stage}/v1/vpc/security-group-ids}
    subnetIds:
      "Fn::Split":
        - ","
        - ${ssm:/infra/${self:provider.stage}/v1/vpc/subnet-ids}

functions:
  wsgi:
    name: ${self:service}-${self:custom.stage}-wsgi
    handler: wsgi_handler.handler
    provisionedConcurrency: ${ssm:/${self:provider.stage}/v1/${self:service}/default/provisioned-concurrency}
    <<: *lambda-property
    memorySize: 1024
    timeout: 29
    environment:
      APP_NAME: "django-app::wsgi"
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

resources:
  Conditions:
    ShouldProvision:
      Fn::Equals:
        - ${self:provider.stage}
        - ${self:custom.stage}

  Resources:
    CustomDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      Condition: ShouldProvision
      DependsOn: ApiGatewayDeployment${sls:instanceId}
      Properties:
        Stage: ${self:provider.stage}
        DomainName: ${cf:${env:APP_SITE, 'sample-site'}-${self:provider.stage}-cms.OneSite}
        RestApiId:
          Ref: ApiGatewayRestApi
```
