### ISSUE TITLE
Cannot invoke serverless with --docker option while inside docker

### ISSUE THREAD

**Issue by kaktusas2598** [serverless/serverless#7337]
# Bug Report

## Description

I am trying to test my lambda functions locally withing docker, but I am having problems while using "local --docker" option.

1. What did you do?

Execute: sudo serverless invoke local --docker -f function

1. What happened?

Error while Building Docker Image:

```
Error: spawn docker ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
      at onErrorNT (internal/child_process.js:415:16)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

1. What should've happened?

Expected to see lambda function output, which I do get if I execute same command outside my docker container

1. What's the content of your `serverless.yml` file?

```
service: CleanUpCircleCIS3Buckets

provider:
    name: aws
    region: eu-west-1
    runtime: python3.7
    tags:
        Environment: Staging
    role: arn:aws:iam::xxxxxxxxxx:role/service-role/CleanUpCircleCIS3Buckets-role-6ucuo9we

functions:
    function:
        handler: lambda_function.lambda_handler
        events:
            - schedule: cron(0 9-18 ? * MON-FRI *)
        timeout: 10 # Timeout in seconds
        memorySize: 128
        description: 'Periodically deletes Circle CI S3 Buckets which are older than 2 hours.'
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

I am getting same error with SLS_DEBUG option:

```
Error: spawn docker ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
      at onErrorNT (internal/child_process.js:415:16)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

We are testing our docker image before deploying - running unit tests, coding standard checks and etc. So naturally we would want to test our lambda functions too, while in Docker container.
