### ISSUE TITLE
Permission Denied /var/task/s_helloworld.py : File Generated By Serverless

### ISSUE THREAD

**Issue by jcronq** [serverless/serverless#7340]
# Bug Report

## Description

1. What did you do?
Deployed HelloWorld Python3.8 function, and attempted to invoke it (in lambda) using serverless cli.

I am using serverless cli from Ubuntu 18.04 server. 

umask is set to 002

1. What happened?

-------------------------------------------------------------------------
**The serverless generated files are created with permissions 770 (ie. Not world readable)**

--------------------------------------------------------------------
START RequestId: 007ccf1d-73c4-463f-9ed7-10da1b134e74 Version: $LATEST
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/s_helloWorld.py'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 300, in find_module
    with open(file_path, 'rb') as file:END RequestId: 007ccf1d-73c4-463f-9ed7-10da1b134e74
REPORT RequestId: 007ccf1d-73c4-463f-9ed7-10da1b134e74  Duration: 187.43 ms     Billed Duration: 200 ms   Memory Size: 1024 MB    Max Memory Used: 21 MB

Unknown application error occurred
-------------------------------------------------------------------------
The contents of smartvpn-ctl.zip (which is subsequently uploaded to aws)
```
rwxrwxrwx  1 cronqj cronqj   77 Jan  1  1980 simple.py*
-rwxrwx---  1 cronqj cronqj  715 Jan  1  1980 s_helloWorld.py*
-rwxrwx---  1 cronqj cronqj  18K Jan  1  1980 package-lock.json*
-rwxrwx---  1 cronqj cronqj  585 Jan  1  1980 package.json*
-rwxrwxrwx  1 cronqj cronqj 4.9K Jan  1  1980 handler.py*
-rwxrwx---  1 cronqj cronqj  118 Jan  1  1980 data_test.json*
-rwxrwx---  1 cronqj cronqj  26M Feb 15 19:56 smartvpn-ctl.zip*
drwxrwx---  2 cronqj cronqj    6 Feb 15 19:56 __pycache__/
drwxrwx---  3 cronqj cronqj    8 Feb 15 19:56 managers/
drwxrwx---  3 cronqj cronqj    6 Feb 15 19:56 serverless_sdk/
drwxrwx---  3 cronqj cronqj    7 Feb 15 19:56 tests/
drwxrwx---  3 cronqj cronqj    8 Feb 15 19:56 utils/
...
```

1. What should've happened?
The function should have executed.

1. What's the content of your `serverless.yml` file?
```
service: smartvpn-ctl                                                                              
app: smartvpn-ctl-app                                                             
org: jcronq                                                                       
                                                                                  
provider:                                                                         
  name: aws                                                                       
  runtime: python3.8                                                              
  stage: dev                                                                      
  version: 
                                                                                  
plugins:                                                                          
  - serverless-domain-manager                                                     
  - serverless-python-requirements                                                
custom:                                                                           
  customDomain:                                                                   
    domainName: api.cozyhem.com                                                   
    basePath: ${self:provider.version}                                            
    stage: ${self:provider.stage}                                                 
    createRoute53Record: true                                  
package:                                                                          
  include:                                                                        
    - managers/**                                                                 
                                                                                  
functions:                                                                        
  helloWorld:                                                                     
    handler: simple.helloWorld                                                    
    events:                                                                       
      - http:                                                                     
          path: helloWorld                                                        
          method: get
```
-------------------
No problems when using 'invoke local'

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```

{
    "errorMessage": "[Errno 13] Permission denied: '/var/task/s_helloWorld.py'",
    "errorType": "PermissionError",
    "stackTrace": [
        "  File \"/var/lang/lib/python3.8/imp.py\", line 300, in find_module\n    with open(file_path, 'rb') as file:\n"
    ]
}
--------------------------------------------------------------------
START RequestId: 8eba830c-75a5-4aac-a103-a274f8f76fff Version: $LATEST
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/s_helloWorld.py'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 300, in find_module
    with open(file_path, 'rb') as file:END RequestId: 8eba830c-75a5-4aac-a103-a274f8f76fff
REPORT RequestId: 8eba830c-75a5-4aac-a103-a274f8f76fff  Duration: 190.97 ms     Billed Duration: 200 ms   Memory Size: 1024 MB    Max Memory Used: 21 MB

Unknown application error occurred
  Error --------------------------------------------------
 
  Error: Invoked function failed
      at AwsInvoke.log (/usr/lib/node_modules/serverless/lib/plugins/aws/invoke/index.js:105:31)
      at AwsInvoke.tryCatcher (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:130:23)


```

Similar or dependent issues:
https://github.com/serverless/serverless/issues/5006

This issue is similar, except my user generated script has permissions 777 and I can see that reflected in the .zip as well.

The s_helloworld.py file is being generated by serverless, so I have no control over setting permissions in between it being generated and it being uploaded to lambda.

- #12345
