### ISSUE TITLE
Allow setting a number of revisions on Lambda Layers

### ISSUE THREAD

**Issue by jasonmccallister** [serverless/serverless#7344]
# Feature Proposal

Allow a configuration option on layers that specifies the number of layers to retain during deployments.

## Description

Currently there is only one option for managing layers with Lambda, retain or delete (documented here https://serverless.com/framework/docs/providers/aws/guide/layers/). However, there are cases where you may wish to keep X number of revisions before deleting them (canary deployments, rolling releases, and etc).  

Example configuration:

```yaml
layers:
  vendor:
    path: layers
    name: some-layer-name
    description: "describe the layers use case"
    retain: true
    versions: 10
```

We could set the option to retain to be true and manually delete the layers after x amount of time with a custom script, but this option would be more practical and elegant.
