### ISSUE TITLE
maximumRetryAttempts does not update on subsequent changes to serverless.yml if that's the only change

### ISSUE THREAD

**Issue by Kunamatata** [serverless/serverless#7365]
# Bug Report

## Description

1. What did you do?
Add `maxmimumRetryAttempts` as a property of event streams in `serverless.yml`
1. What happened?
Subsequent updates to `maxmimumRetryAttempts` only did not update after deploying if nothing else in `serverless.yml` changed
1. What should've happened?
Subsequent updates to `maxmimumRetryAttempts` should update after deploying if that was the only change inside `serverless.yml`
1. What's the content of your `serverless.yml` file?
Relevant to this update:
```yaml
    events:
      - stream:
          arn: "arn:my-arn"
          startingPosition: LATEST
          batchSize: ${self:custom.batchSize.${self:provider.stage}}
          batchWindow: 5
          maximumRetryAttempts: 3
```
Example where `maximumRetryAttempts` does not update after deploying:
```yaml
batchWindow: 5
maximumRetryAttempts: 2
```
```yaml
batchWindow: 5
maximumRetryAttempts: 3
```
It would only update if you were to update another property with the `maximumRetryAttempts` change. 
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
This output does not provide any information relevant this bug.

Similar or dependent issues:

- #7040 - Provided the support for `maximumRetryAttempts`
