### ISSUE TITLE
AWS SQS Event Source does not work with a Lambda with provisionedConcurrency

### ISSUE THREAD

**Issue by patrickdeshpande** [serverless/serverless#7371]
# Bug Report
Hello, I have a similar issue to issue [#7247](https://github.com/serverless/serverless/issues/7247) to report.

## Description

1. What did you do?
I attempted to enable Provisioned Concurrency for a Lambda with an SQS source
1. What happened?
The SQS Trigger remained on the $LATEST lambda, and did not switch over to the provisioned alias.

I confirmed after sending test messages to the source SQS queue that the $LATEST lambda was invoked. I did see the provisioned alias initialize, but it never processed any events.

2. What should've happened?
The SQS Trigger should have been on the provisioned alias. I have tested this successfully with another source (AWS API Gateway)

3. What's the content of your `serverless.yml` file?

I am just sharing a subsection of my serverless.yml file, since the entire file is not relevant to this issue.
```
MyFunction:
  package:
    artifact: <myartifact>
  handler: <myhandler>
  provisionedConcurrency: 1 # The only diff, I have tested and deployed the rest of my serverless file many times w/o issue.
```
4. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
I would prefer not to share this because I don't think it is relevant to the issue. Thanks.

Similar or dependent issues:

- #7247
