### ISSUE TITLE
Option to create AWS DynamoDB Table Groups

### ISSUE THREAD

**Issue by csath** [serverless/serverless#7373]
## This is a Feature Request

Request an option to create an AWS DynamoDB Table Groups and add DynamoDB table resources to that table group

On AWS console it is possible to create DynamoDB table groups and organize  DynamoDB tables and resources easily.

But I couldn't find a way/option to group my DynamoDB tables in serverless.

![image](https://user-images.githubusercontent.com/30233361/75004769-3a66de80-5492-11ea-9505-c6dfbb8c8294.png)

**Comment by medikoo** [comment]
@csath thanks for request

Still currently Framework doesn't have any functionality built-in for creating & managing DynamoDb tables. So I'm not sure what exactly you want to propose (?)

Do you rely on some plugin that creates tables for you?

**Comment by caligo-erik** [comment]
This would be a very helpful configuration feature. 
When specifying the dynamodb tables (resources) in the serverless.yml file, add a property group, something like this:

```yaml
Resources: 
  SomethingTable:
    Type: AWS::DynamoDB::Table
    Group: TableGroupSomething    # <-- requested resource property
    DeletionPolicy: Retain
    Properties:
      TableName: SomethingTable
      KeySchema:      
        - AttributeName: partition
          KeyType: HASH               
        - AttributeName: sort
          KeyType: RANGE      
      AttributeDefinitions:
        - AttributeName: partition
          AttributeType: S
        - AttributeName: sort
          AttributeType: S
```
