### ISSUE TITLE
v 1.64 regression using aws_iam auth

### ISSUE THREAD

**Issue by lejacobroy** [serverless/serverless#7377]
# Bug Report

## Description

Deploys were running fine with 1.60.5, I updated serverless to 1.64.0 and my API gateway/lambda functions are not being authenticated (using aws_iam). 
Thinking it was my code, I reverted the previous commits but the problem was still there. After a few hours of non-working deployments, I reverted serverless back to 1.60.5 and the problem is gone, even with my code changes.

Because of my tests, I'm pretty sure that some breaking changes happened between the two versions. I wasn't able to isolate it from the changelog.

1. What did you do? 
Updated serverless from 1.60.5 to 1.64.0

1. What happened? 
Lambda functions are not authenticated using aws_iam, throws an error 403 "missing authentication token"

1. What should've happened? 
Queries to API endpoints should be authenticated (as they are in 1.60.5)

1. What's the content of your `serverless.yml` file? 
```
service: api

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-plugin-split-stacks
  - serverless-plugin-warmup
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  stage: ${opt:stage, self:provider.stage}
  splitStacks:
    #nestedStackCount: 150 # Controls the number of created nested stacks
    perFunction: false
    perType: true
    perGroupFunction: false
    custom: ./stacks-map.js
    force: true
    #stackConcurrency: 5 # Controls if enabled and how much stacks are deployed in parallel. Disabled if absent.
    #resourceConcurrency: 10 # Controls how much resources are deployed in parallel. Disabled if absent.

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

environment:
  stripeSecretKey: ${self:custom.environment.stripeSecretKey}

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: "Allow"
      Action:
        - "states:ListStateMachines"
        - "states:StartExecution"
      Resource: "arn:aws:states:*:*:*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"

functions:

  billing:
    handler: billing/billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
  etc..

```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Nothing different between the two versions.

Similar or dependent issues:
Haven't found any...
