### ISSUE TITLE
http events stop me from deploying

### ISSUE THREAD

**Issue by RickCraig** [serverless/serverless#7391]
# Bug Report

## Description

on `MONGO_URL="the-url" serverless deploy --verbose --force --aws-profile myprofile` the process is stopping at: `Serverless: Installing dependencies for custom CloudFormation resources...`, I've found that removing the http events allows the deployment to complete successfully. There is no error, i've changed the format and re-written the configuration to make sure I didn't have any erroneous characters. My current config is:

```yml
service: surveys
app: myapp
org: myorg

plugins:
  - serverless-package-external

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    MONGO_URL: ${env:MONGO_URL}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-0887xxx
    subnetIds:
      - subnet-02e0xxx
      - subnet-0d6xxx
      - subnet-035xxx
      - subnet-0cbxxx

functions:
  duplicate:
    handler: helpers.duplicate
    events:
      - http:
          path: survey/duplicate
          method: post
          cors: true

custom:
  packageExternal:
    external:
      - '../models'
```

With SLS_DEBUG:

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
platform-sdk fetching: POST https://api.serverless.com/core/tenants/myorg/applications/myapp/profileValue
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: [serverless-package-external] Symlinking ../models
Serverless: [serverless-package-external] is complete
platform-sdk fetching: GET https://api.serverless.com/core/tenants/myorg/applications/myapp
platform-sdk fetching: GET https://api.serverless.com/core/meta
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
```

My expectation is that it will deploy to AWS and create an API Gateway to allow me to access this function my interface.

Similar issues:
- #6557
