### ISSUE TITLE
(AWS) Tagging works with new lambda functions, not existing

### ISSUE THREAD

**Issue by pradheepap** [serverless/serverless#7423]
# Bug Report
(AWS) Tagging works with new lambda functions, not existing
## Description
Tagging for lambda functions appears to work at point of function creation only, it isn't possible to apply tags to existing functions.

1. What did you do?
    I added tags for the lambda function which are already created.
1. What happened?
  The tags are not appearing in the lamda configuration
1. What should've happened?
   The tags should be appearing in the lambda
1. What's the content of your `serverless.yml` file?
```yml
provider:
   stackTags:
      PROJECT: cxf
  tags:
    SERVICE: micro
getFix:
    name: ${self:service}-getFix-${self:custom.suffix}
    handler: src/fix/transform/handler.getFix
    description: Lambda to transform
    timeout: 300
    package:
      include:
        - src/fix/transform/**
        - src/fix/util/**
    tags:
      REALM: ${self:custom.realm}
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
There is no error.

Similar or dependent issues:
- #4138
