### ISSUE TITLE
Serverless package stuck at removing .webpack for aws-nodejs-typescript template

### ISSUE THREAD

**Issue by bmight** [serverless/serverless#7425]
# Bug Report

## Description

1. What did you do?
```
mkdir serverless-test
cd serverless-test
serverless create --template aws-nodejs-typescript
yarn install
$env:SLS_DEUBG = '*'
serverless package --verbose
```
1. What happened?
Stuck after `Serverless: Remove C:\Users\brandon.might\workspace\serverless-test\.webpack`
If I restart Windows and run the package command again it works for the first time. If I run it a second time it hangs again.

1. What should've happened?
Finished the package

1. What's the content of your `serverless.yml` file?
```
service:
  name: serverless-test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Using configuration:
{
  "webpackConfig": "./webpack.config.js",
  "includeModules": true,
  "packager": "npm",
  "packagerOptions": {},
  "keepOutputDirectory": false
}
Serverless: Removing C:\Users\brandon.might\workspace\serverless-test\.webpack
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 354ms
Built at: 03/04/2020 11:15:21 AM
         Asset      Size  Chunks                   Chunk Names
    handler.js  1.28 KiB       0  [emitted]        handler
handler.js.map  5.27 KiB       0  [emitted] [dev]  handler
Entrypoint handler = handler.js handler.js.map
[0] ./handler.ts 326 bytes {0} [built]
[1] external "source-map-support/register" 42 bytes {0} [built]
Serverless: Invoke webpack:package
Serverless: Fetch dependency graph from C:\Users\brandon.might\workspace\serverless-test\package.json
Serverless: Packing external modules: source-map-support@^0.5.10
Serverless: Package took [2064 ms]
Serverless: Copy modules: C:\Users\brandon.might\workspace\serverless-test\.webpack\service [40 ms]
Serverless: Prune: C:\Users\brandon.might\workspace\serverless-test\.webpack\service [1866 ms]
Serverless: Run scripts: C:\Users\brandon.might\workspace\serverless-test\.webpack\service [0 ms]
Serverless: Zip service: C:\Users\brandon.might\workspace\serverless-test\.webpack\service [149 ms]
Serverless: Packaging service...
Serverless: Remove C:\Users\brandon.might\workspace\serverless-test\.webpack
```

1. Version Info
```
OS: Windows 10 (1909)

node: 12.16.1

Framework Core: 1.65.0
Plugin: 3.4.1
SDK: 2.3.0
Components: 2.22.3
```
