### ISSUE TITLE
AWS HTTP API name setting is broken

### ISSUE THREAD

**Issue by egirshov** [serverless/serverless#7433]
# Bug Report

## Description

Looks like setting custom HTTP API name (AWS provider) is broken, if I don't set `provider.httpApiName`, the default pattern is used (`<service>-<stage>`) but if I set one,
the API would be named "undefined"

```
service: http-api-service

provider:
  name: aws
  httpApiName: http-api

functions:
  test-function:
    handler: index.handler
    events:
      -  httpApi: 'GET /'
```
