### ISSUE TITLE
Obsolete `DependsOn` with Lambda functions

### ISSUE THREAD

**Issue by MattGould1** [serverless/serverless#7437]
# Bug Report

## Description

Lambda functions have an obsolete `DependsOn` resource.

1. What did you do? 
I ran the `sls package` command

1. What happened?
A `cloudformation-template-update-stack.json` was generated with 

```
    "NylasLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "removed",
          "S3Key": "removed"
        },
        "FunctionName": "removed",
        "Handler": "functions/nylas/index.handler",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x",
        "Timeout": 600,
        "TracingConfig": {
          "Mode": "Active"
        },
        "Environment": {
          "Variables": {
            "NYLAS_APP_ID": "missing_NYLAS_APP_ID",
            "NYLAS_APP_SECRET": "missing_NYLAS_APP_SECRET"
          }
        }
      },
      "DependsOn": [
        "NylasLogGroup",
        "IamRoleLambdaExecution" # Issue is here, this isn't required because dependency is enforced by "Fn:GetAtt"
      ]
    },
```

1. What should've happened?

```
    "NylasLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "removed",
          "S3Key": "removed"
        },
        "FunctionName": "removed",
        "Handler": "functions/nylas/index.handler",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x",
        "Timeout": 600,
        "TracingConfig": {
          "Mode": "Active"
        },
        "Environment": {
          "Variables": {
            "NYLAS_APP_ID": "missing_NYLAS_APP_ID",
            "NYLAS_APP_SECRET": "missing_NYLAS_APP_SECRET"
          }
        }
      },
      "DependsOn": [
        "NylasLogGroup",
        # Remove the IamRoleLambdaExecution depedency
      ]
    },
```

1. What's the content of your `serverless.yml` file?

```
service: ${self:custom.project.name}

package:
  individually: true

provider:
  name: aws
  tracing:
    lambda: true
  versionFunctions: false
  stage: ${file(./serverless.js):provider.stage}
  stackName: ${file(./serverless.js):project.stackName}
  runtime: ${file(./serverless.js):provider.runtime}
  region: ${file(./serverless.js):provider.region}
  logRetentionInDays: ${file(./serverless.js):provider.logRetentionInDays}

  deploymentBucket:
    name: ${file(./serverless.js):provider.deploymentBucket.name}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource: '*'

plugins:
  - '@dathuis/serverless-stack-output'
  - serverless-webpack
  - serverless-offline

custom:
  project: ${file(./serverless.js):project}

  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      packagePath: '../../package.json'
      forceExclude:
        - aws-sdk
    packager: 'npm'

functions:
  nylas:
    handler: functions/nylas/index.handler
    environment:
      NYLAS_APP_ID: ${env:NYLAS_APP_ID, 'missing_NYLAS_APP_ID'}
      NYLAS_APP_SECRET: ${env:NYLAS_APP_SECRET, 'missing_NYLAS_APP_SECRET'}
    memorySize: 1024
    timeout: 600
```

- #12345
