### ISSUE TITLE
Property Resources/NotifyFlowsEventSourceMappingSQSNotifyFlowsSQSQueue/Properties/Enabled should be of type Boolean

### ISSUE THREAD

**Issue by MattGould1** [serverless/serverless#7438]
# Bug Report

## Description
The resource Resources/NotifyFlowsEventSourceMappingSQSNotifyFlowsSQSQueue/Properties/Enabled seems to have a default value of "True"  this should be a boolean type.

1. What did you do?
I ran `sls package`
1. What happened?
A `cloudformation-template-update-stack.json` was generated with

```
"NotifyAppSyncAboutActivityEventSourceMappingSQSNotifyAppSyncAboutActivitySQSQueue": {
  "Type": "AWS::Lambda::EventSourceMapping",
  "DependsOn": "IamRoleLambdaExecution",
  "Properties": {
    "BatchSize": 10,
    "EventSourceArn": {
      "Fn::GetAtt": [
        "notifyAppSyncAboutActivitySQSQueue",
        "Arn"
      ]
    },
    "FunctionName": {
      "Fn::GetAtt": [
        "NotifyAppSyncAboutActivityLambdaFunction",
        "Arn"
      ]
    },
    "Enabled": "True"
  }
},
```

1. What should've happened?

```
"NotifyAppSyncAboutActivityEventSourceMappingSQSNotifyAppSyncAboutActivitySQSQueue": {
  "Type": "AWS::Lambda::EventSourceMapping",
  "DependsOn": "IamRoleLambdaExecution",
  "Properties": {
    "BatchSize": 10,
    "EventSourceArn": {
      "Fn::GetAtt": [
        "notifyAppSyncAboutActivitySQSQueue",
        "Arn"
      ]
    },
    "FunctionName": {
      "Fn::GetAtt": [
        "NotifyAppSyncAboutActivityLambdaFunction",
        "Arn"
      ]
    },
    "Enabled": true # boolean type true
  }
},
```
1. What's the content of your `serverless.yml` file?

```
notifyAppSyncAboutActivity:
  handler: sns/notifyAppSyncAboutActivity/index.handler
  memorySize: 512
  timeout: 120
  environment:
    AppSyncEndpoint:
      Fn::ImportValue: ${file(./serverless.js):Imports.AppSyncEndpoint}
  events:
    - sqs:
        enabled: true
        arn:
          Fn::GetAtt:
            - notifyAppSyncAboutActivitySQSQueue
            - Arn
```

- #12345
