### ISSUE TITLE
httpApi timeout over 29 seconds message on functions that don't use the httpApi

### ISSUE THREAD

**Issue by Nemo64** [serverless/serverless#7440]
# Bug Report

## Description

I have a function definition like this:
```yaml
functions:

  website:
    handler: public/index.php
    timeout: 15 # seconds (max would be 29 though api gateway limitation)
    layers:
      - ${bref:layer.php-73-fpm}
    events:
      - httpApi: '*'

  console:
    handler: bin/console.php
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-73}
      - ${bref:layer.console} # The "console" layer
```

This creates a warning
 
```
 Serverless Warning --------------------------------------
 
  Function timeout setting (120) is greater than maximum allowed timeout for HTTP API endpoint (29s). This may introduce situation where endpoint times out for succesful lambda invocation.
```

However, the function with 120 seconds timeout is not registered for the httpApi.
This was introduced in #7420

**Comment by jgeurts** [comment]
Seeing the same warning for lambdas triggered by cloudfront event:

```
  deleteUnusedLambdaVersions:
    handler: src/services/public/deleteUnusedLambdaVersions.handler
    memorySize: 128
    reservedConcurrency: 1
    events:
      - schedule: rate(1 day)
    timeout: 300
```

Gives the following warning:

```
Serverless Warning --------------------------------------
Function timeout setting (300) is greater than maximum allowed timeout for HTTP API endpoint (29s). This may introduce situation where endpoint times out for succesful lambda invocation.
```
