### ISSUE TITLE
Variables from javascript files must be a function

### ISSUE THREAD

**Issue by clar-cmp** [serverless/serverless#7443]
Right now, variables defined in JavaScript files must be functions, as referenced here: https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-other-files

Although allowing functions is helpful, this is unfortunately very frustrating when exporting simple constant strings or numbers, as these simply fail. What I'd like is to be able to have:

file.js:

```js
module.exports = {
    num: 1,
    str: 'hello',
    other: () => 'thing',
};
```

serverless.yml:

```yml
custom:
    num: ${file(./file.js):num}
    str: ${file(./file.js):str}
    other: ${file(./file.js):other}
```

Yield:

```yml
custom:
    num: 1
    str: hello
    other: thing
```

`sls --version`:

```
Framework Core: 1.66.0
Plugin: 3.4.1
SDK: 2.3.0
Components: 2.22.3
```

I consider this a bug and not a feature request, because the current behaviour causes weird errors.
