### ISSUE TITLE
Cannot resolve "provider" from file variable

### ISSUE THREAD

**Issue by lbertenasco** [serverless/serverless#7444]
Hey, I'm getting an error on my serverless.yml:

`provider: ${file(../../commons/serverless/provider.js):default}`
where provider.js is : `{name: 'aws'}`
it gets translated by sls print as:
```
provider:
  name:
    name: aws
```

`package: ${file(../../commons/serverless/package.js):default}`
Works perfect and it's the same .js script...
Is this a bug?

Even if I do: `provider: ${file(../../commons/serverless/package.js):default}`
it gets printed as indented inside provider.name...

https://github.com/serverless/serverless/blob/master/lib/plugins/print/print.js#L50
```
   // provider treatment and defaults
    this.cache.serviceProvider = service.provider;
    if (_.isString(this.cache.serviceProvider)) {
      service.provider = { name: this.cache.serviceProvider };
    }
    service.provider = _.merge(
      {
        stage: 'dev',
        region: 'us-east-1',
        variableSyntax: '\\${([^{}]+?)}',
      },
      service.provider
    );
```
This is definetly the issue!
${file(...)} is being treated as a string.

`sls print` with:
```
serverless.cli.consoleLog('serverless.service.provider');
  serverless.cli.consoleLog(serverless.service.provider);
```
in `provider.js` gives:
```
serverless.service.provider
{
  stage: 'dev',
  variableSyntax: undefined,
  name: '${file(../../commons/serverless/provider.js):default}',
  versionFunctions: true,
  remoteFunctionData: null
}
serverless.service.provider
{
  stage: 'dev',
  variableSyntax: '\\${([ ~:a-zA-Z0-9._@\'",\\-\\/\\(\\)*?]+?)}',
  name: {
    name: 'aws',
    runtime: 'nodejs10.x',
    stage: 'dev',
```

**Comment by unfor19** [comment]
Your `${file..}` references to `default` in provider.js, maybe you should do
${file(../../commons/serverless/provider.js):default.name}

So your provider references to **default.name** and not just **default**?

**Comment by unfor19** [comment]
Why are you referencing the whole provider section? and not just the `provider.name` section?
Maybe this will work for you - 

`serverless yml file`
```yaml
provider:
  name: ${file(../../commons/serverless/provider.js):name}
```

I replaced `default` with `name` because it looks like you're referencing to `name` in the provider.js file. Or maybe it should be `default.name`

**Comment by lbertenasco** [comment]
@unfor19 Because I'm importing more than just the `name`
```
provider:
  name: aws
  runtime: ${file(../../commons/environments/${self:custom.currentStage}.yml):provider.runtime}
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
  logRetentionInDays: ${file(../../commons/environments/${self:custom.currentStage}.yml):provider.logRetentionInDays}
  tracing: ${file(../../commons/environments/${self:custom.currentStage}.yml):provider.tracing}
  deploymentBucket:
    name: ${file(../../commons/environments/${self:custom.currentStage}.yml):provider.deploymentBucket.name}
  memorySize: 512
  timeout: 10
  environment: ${file(../../commons/serverless/provider/environment.js):default}
  iamRoleStatements: ${file(../../commons/serverless/provider/iam-role-statements.js):default}
```

**Comment by medikoo** [comment]
@lbertenasco thanks for reporting. When I look at your description I have a notion there are a lot of other factors involved, and issue might be related to some plugins.

Can you prepare as simple as possible (no plugins involved) test case, that exposes an issue?

Ideally it should be just plain simple `serverless.yml` file and `provider.js` (I believe for successful test case you do not have to configure any functions).

**Comment by beldougie** [comment]
Bump! I am experiencing this problem as well - I am trying to find a way to omit role settings when deploying to localstack, but setting them when deploying to AWS. Building the provider block in a javascript file seemed like a good way to build it, but when I output a single object with something like

```js
{
  name: 'aws',
  runtime: 'nodejs12.x',
 stage: '${opt:stage, 'dev}'
// ... etc
}
```

and add the line to my serverless.yml

```yml
provider: ${file(./config/${opt:stage}.provider.js)}
```

when I run `npx sls print` the output is

```yml
provider:
  name:
    name: 'aws'
    runtime: 'nodejs12.x'
    stage: 'dev'
```

This seems like a really simple bug to fix - it looks like it's expecting the provider to only ever be a string for name. But then actually parses the object being returned correctly. This is blocking us at the moment and we could really do with a quick fix
