### ISSUE TITLE
"cors: true" default origin wildcard removed by `generateCorsResponseTemplate`

### ISSUE THREAD

**Issue by Bhuser** [serverless/serverless#7446]
# Bug Report

## Description

1. What did you do?
In the process of updating to a newer version of serverless (v1.31 to v1.62) I expected the cors behavior to stay the same. I have `cors: true` set to receive all the defaults.

1. What happened?
After deploying the wildcard was missing from `Access-Control-Allow-Origin` and all preflights are failing.

![Screen Shot 2020-03-10 at 9 18 54 AM](https://user-images.githubusercontent.com/5738268/76327451-0542f480-62b8-11ea-940a-10857fc189a0.png)

1. What should've happened?
After deploying nothing should have changed when upgrading serverless. I would still expect to see the `cors: true` setting all of the defaults as described in documentation: https://serverless.com/framework/docs/providers/aws/events/apigateway#enabling-cors

1. What's the content of your `serverless.yml` file?
```
functions:
  myFunction:
    description: Description of function.
    handler: handler.myFunction
    timeout: 25
    events:
      - http:
          path: my/path
          method: get
          cors: true
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Everything looks as expected - no errors are thrown.

Findings
When trying to diagnose what was happening - the 'override' message in the screenshot above (from the API Gateway Console) led me to the functions `generateCorsResponseTemplate` and `regexifyWildcards` in `cors.js`. 

![Screen Shot 2020-03-10 at 10 17 11 AM](https://user-images.githubusercontent.com/5738268/76328581-78993600-62b9-11ea-9491-97d928bf3d5d.png)

If that generated code in AWS is updated to `$origin.matches(".+")` then I get the expected outcome `"Access-Control-Allow-Origin":"*"`.
A possible solution could be updating `.*` to `.+` in the function `regexifyWildcards` in `cors.js`. So when `cors: true` the defaults remain as expected.
