### ISSUE TITLE
sls invoke local working for not standalone version 

### ISSUE THREAD

**Issue by adimango** [serverless/serverless#7447]
# Bug Report

## Description

1. What did you do?
- I installed the test python3 AWS using: `serverless create --template aws-python3 --hello`
1. What happened?
- I'm not able to run it locally but it works on AWS
1. What should've happened?
- it should run locally with `sls invoke local --function hello`
1. What's the content of your `serverless.yml` file?
```
service: hello

provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  # you can define service wide environment variables here
  #  environment:
  #    variable1: value1
  environment:

# you can add packaging information here
# package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  start:
    handler: handler.hello
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/snapshot/serverless/lib/plugins/aws/invokeLocal/invoke.py': [Errno 2] No such file or directory
```

**Mac configuration** NOT working

Framework Core: 1.66.0 **(standalone)**
Plugin: 3.4.1
SDK: 2.3.0
Components: 2.22.3

**Mac configuration** working

Framework Core: 1.66.0 
Plugin: 3.4.1
SDK: 2.3.0
Components: 2.22.3

What's the difference between without or with **(standalone)**
