### ISSUE TITLE
Generated function.json in Azure Python function causes error

### ISSUE THREAD

**Issue by Josh-a-e** [serverless/serverless#7451]
# Bug Report

## Description

1. What did you do?
1. What happened?
1. What should've happened?
1. What's the content of your `serverless.yml` file?
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Similar or dependent issues:

- #12345

# Bug Report

## Description

1. What did you do?
Created an Azure Python function, as per instructions and ran it with serverless offline
1. What happened?
I got this error:
```logs
[3/11/20 3:04:01 PM] Executed 'Functions.hello' (Failed, Id=10bef4e3-8653-426b-98ed-50196b0e0168)
[3/11/20 3:04:01 PM] System.Private.CoreLib: Exception while executing function: Functions.hello. System.Private.CoreLib: Result: Failure
[3/11/20 3:04:01 PM] Exception: FunctionLoadError: cannot load the hello function: the following parameters are declared in function.json but not in Python: {'res'}
[3/11/20 3:04:01 PM] Stack:   File "/demo/packages/etl/node_modules/azure-functions-core-tools/bin/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 245, in _handle__function_load_request
[3/11/20 3:04:01 PM]     function_id, func, func_request.metadata)
[3/11/20 3:04:01 PM]   File "/demo/packages/etl/node_modules/azure-functions-core-tools/bin/workers/python/3.6/LINUX/X64/azure_functions_worker/functions.py", line 110, in add_function
[3/11/20 3:04:01 PM]     f'the following parameters are declared in function.json but '
```
1. What should've happened?
No error
1. What's the content of your `serverless.yml` file?
(pure boiler plate, without comments)
```yaml
service: demo-etl
provider:
  name: azure
  region: West Europe
  runtime: python3.6
  environment:
    VARIABLE_FOO: "foo"
plugins:
  - serverless-azure-functions
package:
  exclude:
    - env/**
    - .env/**
functions:
  hello:
    handler: src/handlers/hello.main
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Unknown

## Resolution

This came down to this automatically generated file having an issue:

```json
{
  "disabled": false,
  "bindings": [
    {
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "authLevel": "anonymous",
      "methods": ["GET"]
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res" // <- wrong
    }
  ],
  "entryPoint": "main",
  "scriptFile": "../src/handlers/hello.py"
}
```

by changing the `name` property on the `out` binding to `"$return"`, as implied here:

https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-03

Things started worked 👌
