### ISSUE TITLE
Batch size ignored on yaml file

### ISSUE THREAD

**Issue by sf8193** [serverless/serverless#7453]
# Bug Report

## Description

1. What did you do?

My event stream configuration is ignored, code looks like this

```
functions:
  fxn:
    handler: lambda.handler.LambdaTimestreamHandler
    name: ${self:custom.service_name}
    events:
      - stream: arn:aws:kinesis:${self:provider.region}:${self:custom.aws_account_number}:stream/${self:provider.environment.SOURCE_STREAM_NAME}
        batchSize: 70
        enabled: True
        startingPosition: LATEST
```

when I do this I get this output in cloud formation

```
"EventSourceMappingName":{
   "Type":"AWS::Lambda::EventSourceMapping",
   "DependsOn":"FuncRole",
   "Properties":{
      "BatchSize":10,
      "EventSourceArn":"arn:aws:kinesis:us-west-2:account-number:stream/stream-name",
      "FunctionName":{
         "Fn::GetAtt":[
            "FxnLambdaFunction",
            "Arn"
         ]
      },
      "StartingPosition":"TRIM_HORIZON",
      "Enabled":"True"
   }
},
```

Now when I try the yaml the way below,

```
functions:
  fxn:
    handler: lambda.handler.LambdaTimestreamHandler
    ## tracing: Active
    name: ${self:custom.service_name}
    events:
      - stream:
        arn: arn:aws:kinesis:${self:provider.region}:${self:custom.aws_account_number}:stream/${self:provider.environment.SOURCE_STREAM_NAME}
        batchSize: 70
        enabled: true
        startingPosition: LATEST
```
No event source mapping shows up at all, (it deletes the event source mapping if I try to update from first to second). Is there anything obvious I am missing in the configuration?

Similar or dependent issues:

#4176
