### ISSUE TITLE
Go Handler use context.Context instead of events.APIGatewayProxyRequest

### ISSUE THREAD

**Issue by azukaar** [serverless/serverless#7454]
# Bug Report

## Description

Using the basic setup with :

```
func Handler(ctx context.Context) (Response, error) {

}

func main() {
	lambda.Start(Handler)
}
```

The input type of the first argument of the handler is context.Context instead of events.APIGatewayProxyRequest, so I cant read the body, the HTTP method or whatever from it.
(if I try to make it events.APIGatewayProxyRequest, it yeld an error saying it cannot unmarshall the parameter).
There isn't a lot of documentation for usage of Serverless in Go, but every piece of code I found online seems to be able to use APIGatewayProxyRequest, so I assume it's a bug?

Serverless is running : 1.66.0

And I do : serverless invoke local --function createProfile

THis is my serverless file:

```
service: yoderapi

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

plugins:
  - serverless-offline

functions:
  # Create Profile
  # internal use only
  createProfile:
    handler: bin/profile
    events:
      - http:
          path: profile
          method: post

```

Thanks for help
