### ISSUE TITLE
sls remove doesn't remove AWS Http Api resources other than stage dev

### ISSUE THREAD

**Issue by Albert-Gao** [serverless/serverless#7460]
# Bug Report

>    "serverless": "^1.66.0",

## Description

```yaml
org: teamingcloud
app: teaming-cloud-backend
service:
  name: teaming-cloud-backend

custom:
  stage: ${opt:stage, 'dev'}
  enterprise:
    collectLambdaLogs: false

provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:aws:iam::049606384301:role/serverlessDeploy
  region: us-east-1
  logs:
    restApi: false
  environment:
    GIT_BRANCH: ${self:custom.stage}

functions:
  login:
    handler: dist/api/login.handler
    events:
      - httpApi:
          path: /login
          method: POST
          cors: true
          timeout: 15
```

I just tried to deploy my functions to different stages with the new aws http api.

1. Running `sls deploy --stage dev`: deployed functions and endpoints
1. Running `sls deploy --stage uat`: deployed functions and endpoints (different endpoints and different functions, which is correct, I suppose?)
1. when deploying `uat`, saw this warning, but still everything works

```bash
   Summary --------------------------------------------------

   warned - allowed-stages
   passed - allowed-runtimes
   passed - no-secret-env-vars
   passed - no-unsafe-wildcard-iam-permissions
   passed - framework-version
   passed - allowed-regions
   passed - require-cfn-role

   Details --------------------------------------------------

   1) Warned - Stage name "uat" not in list of permitted names: ["dev","qa","prod"]
      details: http://slss.io/sg-allowed-stages
      Limit the stages that can be used.
```

4. running `sls remove`

```bash
AlbertGao@Albert-LottoNZ-Laptop backend % sls remove
Serverless: Getting all objects in S3 bucket...
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
Serverless: Checking Stack removal progress...
..................................................................................
Serverless: Stack removal finished...
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/teamingcloud/applications/teaming-cloud-backend/services/teaming-cloud-backend/stage/dev/region/us-east-1
AlbertGao@Albert-LottoNZ-Laptop backend %
```

5. Open AWS console, `dev` stage resources has been removed, `uat` stage still there (api gateway and lambdas)
