### ISSUE TITLE
Variables: Lack of support for (non string) default plain values

### ISSUE THREAD

**Issue by jbsulli** [serverless/serverless#7462]
Ex:
```
service:
  name: test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          enabled: ${self:custom.doesnotexist, false}
```

Using `sls print` I get:
```
service:
  name: test
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs10.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
    name: test-dev-hello
```

**Note**: the `enabled` key is missing entirely

This happens for custom values and keys other than `enabled` as well.

Seems to be related to https://github.com/serverless/serverless/pull/3891

Framework Core: 1.66.0
Plugin: 3.5.0
SDK: 2.3.0
Components: 2.22.3

**Comment by jbsulli** [comment]
My workaround for now:

```
service:
  name: test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

custom:
  false: false

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          enabled: ${self:custom.doesnotexist, self:custom.false}
```
