### ISSUE TITLE
Access key Id is inactive error on Alibaba cloud

### ISSUE THREAD

**Issue by mohdizzy** [serverless/serverless#7468]
# Bug Report

## Description

1. Wanted to deploy a simply SLS function on Alibaba cloud. Followed the documentation steps.

2. On running `serverless deploy` I get an error 
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "objectevent"...
Serverless: Finished Packaging.
Serverless: Creating log project sls-<ACCOUNTID>-ap-south-1-logs...

  Invalid Access Key Id Error ----------------------------

  InvalidAccessKeyIdError: AccessKeyId <ACCESSKEY> is inactive


```
3. serverless.yml looks like this

```
service: myslsfunction

provider:
  name: aliyun
  runtime: nodejs8
  region: ap-south-1
  credentials: ./credentials # path must be absolute

plugins:
  - serverless-aliyun-function-compute

package:
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**

functions:
  objectevent:
    handler: index.osseventtrigger
    events:
      - oss:
          sourceArn: acs:oss:ap-south-1:ACCOUNTID:mizzy
          triggerConfig:
            events:
              - oss:ObjectCreated:PutObject
```

I have verified all the permissions of the user. Tried even creating new access keys. Can't seem to pin down on where the problem lies. Any insight would be appreciated, thanks.
