### ISSUE TITLE
Packaging breaks when including it from another yaml

### ISSUE THREAD

**Issue by ouamer-dahmani** [serverless/serverless#7472]
# Bug Report

## Description

1. What did you do?
I want to have a common serverless.yml file used for all deployments. The strategy I adopt is to use ${opt.service} to resolve which service is to be deployed or invoked or whatever and then read the appropriate yaml file.

serverless.yml
```yaml
custom:
  config: ${file(./env.yml):${opt:stage}.config}
  env: ${file(./env.yml):${opt:stage}.env}

service: ${file(./services/${opt:service}/service.yml):service}

plugins:
  - serverless-offline
  - serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${self:custom.config.region}
  iamRoleStatements: ${file(./services/${opt:service}/service.yml):iamRoleStatements, ""}
  role: ${file(./services/${opt:service}/service.yml):role, ""}

package: ${file(./services/${opt:service}/service.yml):package}
functions: ${file(./services/${opt:service}/service.yml):functions}
```

services/service1/service.yml
```yaml
package:
  include:
    - services/service1/src/**
  exclude:
    - ./**

service: service1

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:Query"
    Resource:
      - Fn::Join:
        - ""
        - - ${self:custom.env.TABLE_NAME_PAGES}
      - Fn::Join:
        - ""
        - - ${self:custom.env.TABLE_NAME_PAGES}
          - "/index/*"

functions:
  getPageData:
      handler: /services/service1/src/handler.handler
      name:  ${self:service}-${opt:stage}-getPageData
      memorySize: 128
      environment:
        TABLE_NAME: ${self:custom.env.TABLE_NAME_PAGES}
        TABLE_REGION: ${self:custom.env.TABLE_REGION}
      events:
        # implementing GET requests to the end points /data of second service.
        # note that we do not have base path PATH2 here since it is not requires as we
        # are already in service of PATH2
        - http:
            method: get
            path: service1/getPageData
            cors: true
```

2. What happened?
Env variables are correctly imported from the other yaml and deployment and all that work correctly.
However I noticed that the package that is deployed contains everything in my root folder rather than just what I specified in `package`.

If I inline the `package` stuff in `services/service1/service.yml` directly in `serverless.yml` it works.

3. What should've happened?
It should have just included what was specified in the package.

I did a quick test and inlined the `package` stuff directly and then packaging worked correctly.

```yaml
custom:
  config: ${file(./env.yml):${opt:stage}.config}
  env: ${file(./env.yml):${opt:stage}.env}

service: ${file(./services/${opt:service}/service.yml):service}

plugins:
  - serverless-offline
  - serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${self:custom.config.region}
  iamRoleStatements: ${file(./services/${opt:service}/service.yml):iamRoleStatements, ""}
  role: ${file(./services/${opt:service}/service.yml):role, ""}

package:
  include:
    - services/service1/src/**
  exclude:
    - ./**
functions: ${file(./services/${opt:service}/service.yml):functions}
```

4. What's the content of your `serverless.yml` file?
See first example above.

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command create
Serverless: Load command create:test
Serverless: Load command create:function
Serverless: Load command invoke
Serverless: Load command invoke:test
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```
Similar or dependent issues:
