### ISSUE TITLE
Not able to use Origin Id from CloudFrontDistribution

### ISSUE THREAD

**Issue by summera** [serverless/serverless#7485]
# Bug Report
When attempting to use the Origin Id from `CloudFrontDistribution` like so:

```yaml
functions:
  viewerRequest:
    handler: viewer-request-function/index.handler
    events:
      - cloudFront:
          pathPattern: "*"
          eventType: viewer-request
          origin: myS3Origin
  originResponse:
    handler: origin-response-function/index.handler
    events:
      - cloudFront:
          pathPattern: "*"
          eventType: origin-response
          origin: myS3Origin

resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
          - DomainName: ${self:custom.cliOptions.destinationImageBucket}.s3.amazonaws.com
            Id: myS3Origin
            S3OriginConfig:
             ...
```
I get the following error:

> Exactly one of CustomOriginConfig and S3OriginConfig must be specified

This is because of [this line](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/cloudFront/index.js#L130) that is checking for the `s3:` prefix in the origin and if it doesn't exist, is adding in `CustomOriginConfig` which I'm not using. 

If I change the origin to be `s3:myS3Origin` things break with:

> ServerlessError: An error occurred: CloudFrontDistribution - One or more of your origins or origin groups do not exist. (Service: AmazonCloudFront; Status Code: 404; Error Code: NoSuchOrigin;

This is because `TargetOriginId` gets set to: 

```json
"TargetOriginId": "s3/mys3origin",
```

## Description

1. What did you do? 
Please see above.
1. What happened? 
Please see above.
1. What should've happened? 
Used `myS3Origin` correctly without error.
1. What's the content of your `serverless.yml` file? 
Please see above
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
See error messages above.

**Comment by summera** [comment]
Fixed by explicitly setting `origin` on each function and removing my configuration for manually setting the oridin ID in my custom `S3OriginConfig`.

**Comment by medikoo** [comment]
@summera if you believe there's a bug in a Framework, we're definitely open for fixing it. Let us know

**Comment by JacksonGariety** [comment]
@summera can you give an example of how you fixed this? My stack oscillates between throwing the "one or more origins do not exist..." error and the "exactly one of..." error.

**Comment by summera** [comment]
@JacksonGariety we ended up not using serverless for our final solution to what we were trying to do so it's been a while since I've dealt with this, but I think it was something like this:

```yml
functions:
  viewerRequest:
    handler: viewer-request-function/index.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin: s3:${self:custom.cliOptions.destinationImageBucket}.s3.amazonaws.com
  originResponse:
    handler: origin-response-function/index.handler
    events:
      - cloudFront:
          eventType: origin-response
          origin: s3:${self:custom.cliOptions.destinationImageBucket}.s3.amazonaws.com
```
