### ISSUE TITLE
Cannot access lambda with many endpoints using custom domain

### ISSUE THREAD

**Issue by ribtoks** [serverless/serverless#7491]
# Bug Report

## Description

1. What did you do?

High-level goal is to use my domain in front of single lambda function with couple of http endpoints. I created a template that used `serverless-domain-manager` and a lambda function with few endpoints. After running `serverless deploy` all resources were created without errors. 

(also I provisioned certificates in ACM and setup CNAME in my DNS provider to point to CloudFront that I found in the output)

2. What happened?

All endpoints worked with "execute-api" URL but I was always getting 404 when trying to access the API using custom domain. When viewed in AWS Console, API Gateway's URL was one of the endpoints that I set, which was different from the one I'm trying to access through http request.

I viewed the requests in the API Gateway CloudWatch logs and they were going through right to lambda and then failing with 404. I have a feeling that the fact that API Gateway's URL was only 1 of the endpoints somehow disabled other or something along those lines.

3. What should've happened?

API should have been working through custom domain as well as through standard path.

4. What's the content of your `serverless.yml` file?

```
service: xpiks-backend
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  apiKeys:
    - name: ${self:provider.stage}-access-key
  usagePlan:
    throttle:
      burstLimit: 10
      rateLimit: 2

plugins:
  - serverless-iam-roles-per-function
  - serverless-domain-manager

package:
  individually: true
  exclude:
    - ./**

functions:
  helloworld:
    memorySize: 128
    handler: bin/helloworld
    package:
      include:
        - ./bin/helloworld
    events:
      - http:
          path: hello
          method: GET
          cors: true
          private: true
      - http:
          path: world
          method: POST
          cors: true
          private: true

custom:
  customDomain:
    domainName: api.helloworld.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: edge

```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

Not relevant since the deployment does not fail.
