### ISSUE TITLE
Function timeout setting (29) is greater than maximum allowed timeout for HTTP API endpoint (29s).

### ISSUE THREAD

**Issue by tommedema** [serverless/serverless#7496]
# Bug Report

## Description

1. What did you do?
Ran `serverless deploy` with a function timeout of `29`

1. What happened?
Serverless Framework warned me:

```
Function timeout setting (29) is greater than maximum allowed timeout for HTTP API endpoint (29s). This may introduce situation where endpoint times out for succesful lambda invocation.
```

1. What should've happened?

It should not warn me because the timeout is not greater than 29 seconds. It is exactly 29 seconds.

1. What's the content of your `serverless.yml` file?

```
provider:
  name: aws
  stage: ${{opt:stage, 'local'}}
  region: ${{opt:region, 'us-west-2'}}

  # in serverless 1.59.3, provisioned concurrency cannot be used if
  # function versioning is enabled
  versionFunctions: false

  runtime: nodejs12.x
  memorySize: 256
  timeout: 29
```

Additionally, I'm getting this warning for serverless packages where I have indeed set the timeout > 30 seconds, but am NOT using API gateway to access the functions (instead am using s3 events).
