### ISSUE TITLE
S3 event with existing true fails if separate stacks have same service/stage value

### ISSUE THREAD

**Issue by et304383** [serverless/serverless#7502]
# Bug Report

## Description
Serverless doesn't seem to handle the custom resource naming correctly when using S3 events across multiple stacks with the same service name (but different stack name values).

**What did you do?**
I tried to add an event on a Lambda function attached to an existing S3 bucket.  At the same time, an existing serverless deployment with the same service name but a different (custom) stack name also has a Lambda function with an S3 event attached.

I am not following an anti-pattern as separating serverless stacks to prevent hitting the 200 resource limit is recommended by the serverless documentation.

**What happened?**
I received an error:
An error occurred: CustomDashresourceDashexistingDashs3LambdaFunction - myservice-dev-custom-resource-existing-s3 already exists in stack arn:aws:cloudformation:us-east-1:999999999999:stack/myservice-clam-av-dev/uuid-goes-here.

**What should've happened?**
Serverless should not be naming the function and this deployment should have went through without naming collision on the function.

**What's the content of your `serverless.yml` file?**
Key area:

```
    events:
      - s3:
          bucket: !Ref CodeMirrorBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: /
            - suffix: tag
          existing: true
```

What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
This isn't relevant.

TLDR: serverless should not give custom names to the custom resource Lambdas it creates as they are going to collide across stacks.
