### ISSUE TITLE
EventBridge event not correctly treat "true"

### ISSUE THREAD

**Issue by airmonitor** [serverless/serverless#7506]
# Bug Report

## Description

1. What did you do?
Create lambda invoked via event from EventBridge

1. What happened?
oops, error :)

1. What should've happened?
true not "true"
in 
[{"exists":"true"}]

1. What's the content of your `serverless.yml` file?
https://pastebin.pl/view/8846bc90

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

` ServerlessError: An error occurred: CarDetailsToDynamoDBCustomEventBridge1 - Failed to update resource. Event pattern is not valid. Reason: exists match pattern must be either true or false.
   at [Source: (String)"{"detail-type":["Lambda Function Invocation Result - Success"],"source":["lambda"],"detail":{"responsePayload":{"license_plate":[{"exists":"true"}]}}}"; line: 1, column: 141] See details in CloudWatch Log: 2020/03/25/[$LATEST]c8287290ed044dfa98074c2e58e1e8bc.
`

https://pastebin.pl/view/03bde7c6

Similar or dependent issues:

- #12345

**Comment by tume** [comment]
I got hit with the same bug as well and seems to be an issue in cloudformation itself: 
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251

**Comment by medikoo** [comment]
@airmonitor can you paste content of your `serlveress.yml` directly, and same with the `sls deploy` output? The pastebin links have expired, and we have no access to this now.

**Comment by robertomoreno** [comment]
I got the same error:

serverless.yml
```  
installmentInvoiceSetup:
    handler: src/installmentInvoiceSetup.handler
    role: ActivecampaignRole
    alarms:
      - functionErrors
    events:
      - eventBridge:
          eventBus: ${self:custom.config.eventbridge.arn}
          pattern:
            detail:
              action:
                - StripeCheckoutEvent
              payload:
                installments: 
                  - exists: ${strToBool(true)}
```
I also tried using `${strToBool(true)}` rather just `true` but it is the same. 

sls deploy output is:
```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Warning: Not deploying alerts on stage dev
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service academia-users.zip file to S3 (445.04 KB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............................................................................
Serverless: Operation failed!
Serverless: View the full error output: https://eu-west-1.console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-west-1%3A724229523824%3Astack%2Facademia-users-dev%2F97407300-6176-11ea-85a1-0659495bde12
 
  Serverless Error ---------------------------------------
 
  An error occurred: InstallmentInvoiceSetupCustomEventBridge1 - Failed to create resource. Event pattern is not valid. Reason: exists match pattern must be either true or false.
   at [Source: (String)"{"detail":{"payload":{"installments":[{"exists":"true"}]},"action":["StripeCheckoutEvent"]}}"; line: 1, column: 50] See details in CloudWatch Log: 2020/04/19/[$LATEST]ee73835d74c448d5b146f3b6d1241c7c.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              11.8.0
     Framework Version:         1.67.3
     Plugin Version:            3.6.6
     SDK Version:               2.3.0
     Components Version:        2.29.1

```

**Comment by robertomoreno** [comment]
I checked the generated Cloudfront template and looks like it is parsed properly
```
    "InstallmentInvoiceSetupCustomEventBridge1": {
      ...
      "Properties": {
        ...
        "EventBridgeConfig": {
          ...
          "Pattern": {
            "detail": {
              "action": [
                "StripeCheckoutEvent"
              ],
              "payload": {
                "installments": [
                  {
                    "exists": true
                  }
                ]
              }
            }
          }
        }
      }
    }
```
Is this an issue with Cloudfront then?

**Comment by medikoo** [comment]
@robertomoreno it looks as an issue with AWS, I believe you should contact its support about that

**Comment by robertomoreno** [comment]
According to the following ticket in the SAM project, Cloudfront team is already working on it: https://github.com/awslabs/serverless-application-model/issues/1455

**Comment by daedal-knickerbockers** [comment]
Any new information about the deployment of the fix?

**Comment by dobeerman7** [comment]
Any updates? The issue still persists.

**Comment by ljacobsson** [comment]
I can confirm that this now works for me. See activity on this [this issue](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251#issuecomment-670824840)

I tried with this yaml and it deployed correctly:
```
source:
- aws.codepipeline
detail-type:
- CodePipeline Action Execution State Change
detail:
  type:
    owner:
    - exists: true
  version:
  - numeric:
    - ">"
    - 5
```

The same issue was also true for numeric values, but both booleans and numbers now works :partying_face:

**Comment by stanvit** [comment]
@ljacobsson , are you creating an `AWS::Events::Rule` resource or adding an `eventBridge` event hook to your function?

Because in my stack with the following (abridged) configuration I'm still getting errors:

```yaml
functions:
 dualPurpose:
    handler: functions/loghandler.handler
    events:
    - eventBridge:
        eventBusName: ${self:custom.EventBusName}
        pattern:
          detail-type: ["dual"]
          detail:
            delaySeconds:
            - exists: false
```

when trying to deploy, I'm getting back:

```
  Serverless Error ---------------------------------------

  An error occurred: DualPurposeCustomEventBridge1 - Failed to update resource. Event pattern is not valid. Reason: exists match pattern must be either true or false.
   at [Source: (String)"{"detail-type":["dual"],"detail":{"delaySeconds":[{"exists":"false"}]}}"; line: 1, column: 62] See details in CloudWatch Log: 2020/08/10/[$LATEST]XXYYZZ.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.7.0
     Framework Version:         1.78.1
     Plugin Version:            3.7.0
     SDK Version:               2.3.1
     Components Version:        2.34.1
```

the error comes from the lambda function responsible for `Custom::EventBridge` resource type:

```json
    "DualPurposeCustomEventBridge1": {
      "Type": "Custom::EventBridge",
      "Version": 1,
      "DependsOn": [
        "DualPurposeLambdaFunction",
        "CustomDashresourceDasheventDashbridgeLambdaFunction"
      ],
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "CustomDashresourceDasheventDashbridgeLambdaFunction",
            "Arn"
          ]
        },
        "FunctionName": "lmd-event-client-dev-dualPurpose",
        "EventBridgeConfig": {
          "RuleName": "lmd-event-client-dev-dualPurpose-rule-1",
          "Pattern": {
            "detail-type": [
              "dual"
            ],
            "detail": {
              "delaySeconds": [
                {
                  "exists": false
                }
              ]
            }
          }
        }
      }
    }
```

**Comment by ljacobsson** [comment]
@stanvit 
Ah sorry - I was creating an `AWS::Events::Rule`

Seems this is fixed in CloudFormation/SAM, but not when using Serverless Framework. I guess the [fix](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/251) on the CloudFormation side treats `AWS::Events::Rule` in a special way that's not the same for custom resources.

**Comment by medikoo** [comment]
In context of a Framework, we're actually bounced by bug in AWS SDK (not in CloudFormation), as we pass the configuration (as passed to ClouFromation template), to [`eventBrigde.putRule`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EventBridge.html#putRule-property) method, here: https://github.com/serverless/serverless/blob/26bdc9efdd70a28b596a652a9c58f2739b6cf16a/lib/plugins/aws/customResources/resources/eventBridge/lib/eventBridge.js#L51

And it's at this point, where outcome is unexpected

**Comment by CCBet** [comment]
Can the **exists** clause be used with **1/0** values instead of **true/false**?

**Comment by siliconcat** [comment]
Affected by this issue. Does anyone have a workaround? Thanks!

**Comment by serverlesspolska** [comment]
we are affected by this issue as well

```
functions:
  name:
    handler: src/function.handler
    events:
      - eventBridge:
          eventBus: ServiceBusArn...
          description: ...
          pattern:
            source:
              - my-source
            detail-type:
              - EVENT_TYPE
            detail:
              entityId: 
                - numeric:
                    - "=": 159
```
Unfortunately, this `numeric` rule does not work as number 159 is wrapped in `"` chars and becomes a string `"159"`.

```
Failed to create resource. Event pattern is not valid. 
Reason: Invalid member in numeric match: {
   at [Source: (String)"{
               "detail-type":["EVENT_TYPE"],
               "source":["my-source"],
               "detail":{ 
                     "entityId":[{"numeric":[{"=":"159"}]}]
  }
}
"; line: 1, column: 126]
```

In `serverless-step-functions` they implement it properly, maybe you could check how they are doing it :-)

**Comment by medikoo** [comment]
@serverlesspolska this was coined as issue with AWS CloudFormation, in case of above configuration, resource in sent template is constructed by Framework as:

```javascript
"EventBridgeConfig": {
          "RuleName": "test-event-bridge-lambda-dev-myFunction-rule-1",
          "EventBus": "ServiceBusArn...",
          "Pattern": {
            "source": [
              "my-source"
            ],
            "detail-type": [
              "EVENT_TYPE"
            ],
            "detail": {
              "entityId": [
                {
                  "numeric": [
                    {
                      "=": 159
                    }
                  ]
                }
              ]
            }
          }
```
As you can clearly see Framework configures _number_ value not _string_ value.

It may work with `serverless-step-functions` as I take it's through different resource type that configuration gets in, and in such case handling on CloudFormation side may not be faulty

Anyway, we're open for any specific suggestions on how that can be fixed on our side (if reasonable fix is possible)

**Comment by serverlesspolska** [comment]
Indeed, you're right @medikoo 
Thanks for replay.

**Comment by soda0289** [comment]
This pull request #8437 fixed the issue for me. It uses cloudformation "AWS::Events::Rule" instead of custom resource that serverless currently uses.

**Comment by xShirase** [comment]
Confirmed closed, `true` is treated properly :

```
pattern:
    detail-type:
      - AccountModified
        detail:
          prop: 
            - exists: true
```                

Deploys the following to EventBridge :
```
{
  "detail-type": ["AccountModified"],
  "detail": {
    "prop": [{
      "exists": true
    }]
  }
}
```
