### ISSUE TITLE
Configuring SES to an existing userpool removes already added lambdatriggers

### ISSUE THREAD

**Issue by severi** [serverless/serverless#7510]
# Bug Report

## Description

1. What did you do?
Added `EmailConfiguration` to my existing user pools Cloudformation to send cognito emails via SES (https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html). Serverless functions were configured using the `existing: true` parameter.

1. What happened?
The existing lambda triggers I had configured via the Serverless Framework disappeared from the userpool. If I create a new stack from scratch it seems to create the lambdas correctly. I suppose this is somehow related to me using the `existing: true` flag

I tried to circumvent the problem by renaming the lambda trigger function names, but this also failed

```
ServerlessError: An error occurred: CustomMessageTriggerCustomCognitoUserPool1 - Failed to delete resource. User: arn:xxxxxxx:assumed-role/yyyy-IamRoleCustomResourcesLa-zzzzz/stackname-custom-resource-existing-cup is not authorized to perform: lambda:RemovePermission on resource: arn:aws:lambda:xxxxx:12314123:function:stackname-customMessageTrigger See details in CloudWatch Log:.
```

1. What should've happened?
The lambda triggers should not have disappeared.

1. What's the content of your `serverless.yml` file?
```
service: example

package:
  individually: true

plugins:
  - serverless-bundle

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    stage: ${self:custom.stage}

functions:
  preSignUp:
    handler: services/cognito/preSignUp.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-user-pool
          trigger: PreSignUp
          existing: true
  customMessage:
    handler: services/cognito/customMessage.handler
    events:
      - cognitoUserPool:
          pool: ${self:custom.stage}-user-pool
          trigger: CustomMessage
          existing: true

resources:
  - ${file(resources/cognito-user-pool.yml)} # creates the userpool
  - ${file(resources/cognito-identity-pool.yml)}
```
