### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by johnykes** [serverless/serverless#7518]
Hi, I'm trying to create a function with CORS enabled. 
The function works as expected using Postman (cors headers present), but I get CORS error when trying from a browser (no cors header).
```
const getTicket = async event => {
    var ticketNumber = Date.now();
    return {
        headers: {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Methods': '*',
            'Access-Control-Allow-Origin': '*',
        },
        statusCode: 200,
        body: JSON.stringify({"ticketNumber": ticketNumber})
    };
};
```
```
functions:
  getTicket:
    handler: code/common/ticket.getTicket
    runtime: nodejs12.x
    events:
      - http:
          method: get
          path: getTicket
          cors: true
          authorizer: 
            arn: ${self:custom.auth0.authorizer_arn}
```
I also tried few more ways of writing the serverless.yaml file, but none of them worked, the only difference between them being the created methods in my API Gateway. Sometimes I got GET+OPTIONS methods, sometimes only GET, but never worked with CORS.

I get the error:
"Access to XMLHttpRequest at 'https://...amazonaws.com/prod/getTicket' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
