### ISSUE TITLE
Unable to modify `ApiGatewayStage`

### ISSUE THREAD

**Issue by nlang** [serverless/serverless#7530]
# Bug Report

## Description

I need to set a stage variable to be used in my Lambda Authorizer. Since there seems to be no way to do this with configuration in `serverless.yml` I decided to add a Stage definition to resources.

I tried:
1. Adding an `extension` to `resources`:

```
resources:
  extensions:
    ApiGatewayStage:
      Properties:
        Variables:
          SOME_VAR: "some-val"
```

That produces:
```
Error: The CloudFormation template is invalid: Template format error: [/Resources/ApiGatewayStage] Every Resources object must contain a Type member.
      at /Users/nic/.nvm/versions/node/v12.16.1/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
```
When I add  the `Type` member, the next error ist:
```
Error: ApiGatewayStage: Sorry, extending the Type resource attribute at this point is not supported. Feel free to propose support for it in the Framework issue tracker: https://github.com/serverless/serverless/issues
```

2. adding a full `ApiGateway::Stage` definition to the `Resources` section:
```
resources:
  Resources:

    ...

    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      DependsOn:
        - ApiGatewayDeployment
      Properties:
        StageName: ${opt:stage}
        RestApiId: !Ref MyApiGatewayApi
        DeploymentId: !Ref ApiGatewayDeployment
        Variables:
          SOME_VAR: "some-val"
```

That always leads to the following error, no matter if it is a fresh deployment or update.:
```
ServerlessError: An error occurred: ApiGatewayStage - dev already exists.
```

Any ideas? Is there any chance for me to add my stage variable?

Thanks a bunch!
Nic

**Comment by nlang** [comment]
Ok, I've found the reason for the odd behavior by diggin into the source code. Stage related stuff is currently not handled by CloudFormation but by a script in `apiGateway/lib/hack`.

What do you think about a config option in the `apiGateway` section of `serverless.yml` to add stage variables? I would volunteer to create a PR for that.

In my mind it looks like this:

```
provider:
  apiGateway:
    stageVariables:
      foo: bar
      baz: yolo
```

Any thoughts?
