### ISSUE TITLE
v1.67.0 Could not unzip uploaded file

### ISSUE THREAD

**Issue by ianberdin** [serverless/serverless#7534]
# Bug Report

## Description

1. What did you do: AWS, nodejs HTTP API with events
1. What happened?:  CustomDashresourceDashapigwDashcwDashroleLambdaFunction - Could not unzip uploaded file
1. What should've happened?: Success deploy
1. What's the content of your `serverless.yml` file?
```yml
app: myapp
org: myorg
service: myservice

provider:
  name: aws
  runtime: nodejs12.x

functions:
  api:
    handler: handler.http
    events:
      - http:
          path: /packages/{packages}
          method: post
```

It works with v1.66.0.
- #12345
