### ISSUE TITLE
Framework 1.67.0 SDK: 2.3.0 major breaking issue with Express

### ISSUE THREAD

**Issue by TreeMan360** [serverless/serverless#7543]
# Bug Report

## Description

When using the Serverless Framework Enterprise/Pro deployment where the Serverless SDK is included ```Express``` fails to work correctly.

Removing ```app``` & ```tenant``` in the ```serverless.yml``` to cause a deployment without the SDK resolves the issue.  You can see myself and another experiencing this issue here:

- https://stackoverflow.com/questions/60998835/highly-confusing-express-router-issue
- https://forum.serverless.com/t/highly-confusing-express-router-issue/10987/10

1. What did you do?
Deploy any serverless function which uses Express with the Serverless Framework SDK 2.3.0

2. What happened?
Express (```apollo-server-expresss```) behaves wierdly:
- Unable to resolve ```express.Router()```
- Response payload includes http headers in body

3. What should've happened?
```Express``` should work as expected

4. What's the content of your `serverless.yml` file?
```
service: express-test
app: XXXX
tenant: XXXXX

plugins:
  - serverless-deployment-bucket
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  timeout: 29
  memorySize: 3008
  tracing:
    apiGateway: true
    lambda: true
  deploymentBucket:
    name: ${self:service}-${self:custom.currentStage}-deployment-bucket
    serverSideEncryption: AES256

custom: ${file(./serverless-common.yml):custom}
package:
  include:
    - ./dist/**
  exclude:
    - node_modules/aws-sdk/**

functions:
  index:
    handler: ./dist/lambda.handler
    name: bm-${self:custom.currentStage}-express-test
    events:
      - http:
          path: "/{proxy+}"
          method: POST
```

5. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=*serverless deploy`)
https://gist.github.com/TreeMan360/bcfcb46f4e3ef12d9d1baebb0394840c

6. Basically all the information required is in the links at the top of this report.

**Comment by scouredimage** [comment]
Thanks for reporting @TreeMan360. This does look like a regression introduced in `v3.5.0` of Plugin. While we look into this, you can disable the instrumentation by adding the following section to your `serverless.yml`:

```yaml
custom:
  enterprise:
    disableFrameworksInstrumentation: true
```
