### ISSUE TITLE
Can Lambda@Edge attach to an existing CloudFront distribution?

### ISSUE THREAD

**Issue by crespowang** [serverless/serverless#7547]
Hello. It looks like when a Lambda@Edge is created, Serverless always tries to create the CloudFront distribution, is that right?
For example, 
```
functions:
  viewerRequest:
    handler: functions/viewerRequest.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin: https://assets-local.inq.com
```
will try to create the distribution rather than add a trigger to the existing one.
