### ISSUE TITLE
Lambda@Edge with custom default Origin and serverless lambda origin

### ISSUE THREAD

**Issue by marcelalburg** [serverless/serverless#7568]
# Bug Report
My setup has a default CloudFront S3 Origin that is my default. Additionally i create one cloud-front event to my lambda function with and individual pathPattern. After deployment, serverless changed my default origin with the pathPattern of the lambda function.

Serverless Version: 
Framework Core: 1.67.3
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.29.1

## Description

After my deployment in CloudFront -> Origins and Origin Groups i see in "Origin Domain name and path" two times my s3 buckets with the same path.

My expectation is that my S3Origin path is s3://bucketname.s3.amazonaws.com/

and S3OriginLambda path is s3://bucketname.s3.amazonaws.com/images with the lambda edge function.

```
functions:
  resize:
    handler: handler.handler
    events:
      - cloudFront:
          eventType: origin-response
          pathPattern: /images/*
          isDefaultOrigin: false
          origin: s3://bucketname.s3.amazonaws.com/images

Resources:
  resources:
    CloudFrontDistribution:
      DependsOn:
        - WebsiteBucket
        - CloudFrontOriginAccessIdentity
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          PriceClass: PriceClass_100
          HttpVersion: http2
          Aliases:
            - ${self:provider.env.cloudfront_alias}

          Comment: ${self:service}-${opt:stage, self:provider.stage}

          Origins:
            - Id: S3Origin
              DomainName: !GetAtt WebsiteBucket.DomainName
              S3OriginConfig:
                # Restricting Bucket access through an origin access identity
                OriginAccessIdentity:
                  Fn::Join:
                    - ""
                    - - "origin-access-identity/cloudfront/"
                      - !Ref CloudFrontOriginAccessIdentity

            - Id: S3OriginLambda
              DomainName: !GetAtt WebsiteBucket.DomainName
              OriginPath: /images
              S3OriginConfig:
                # Restricting Bucket access through an origin access identity
                OriginAccessIdentity:
                  Fn::Join:
                    - ""
                    - - "origin-access-identity/cloudfront/"
                      - !Ref CloudFrontOriginAccessIdentity

          CacheBehaviors:
            - PathPattern: "images/*"
              Compress: true
              AllowedMethods:
                - GET
                - HEAD
                - OPTIONS
              TargetOriginId: S3OriginLambda
              DefaultTTL: 300000
              ForwardedValues:
                  QueryString: false
                  Cookies:
                    Forward : none
              ViewerProtocolPolicy: redirect-to-https

          DefaultCacheBehavior:
            # Compress resources automatically ( gzip )
            Compress: true
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            TargetOriginId: S3Origin
            MinTTL: 3600
            DefaultTTL: 3600
            ViewerProtocolPolicy: redirect-to-https

          ViewerCertificate:
            AcmCertificateArn: ${self:provider.env.cloudfront_cert_arn}
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2018
          Logging:
            Bucket: !GetAtt WebsiteBucket.DomainName
            Prefix: CloudFrontDistributionLogs  
```

Thanks
Marcel
