### ISSUE TITLE
Recoverable error occurred (socket hang up), sleeping for ~6 seconds. Try 1 of 4

### ISSUE THREAD

**Issue by SafiqurRhaman** [serverless/serverless#7570]
# Bug Report

## I was trying to deploy application using Serverless framework in AWS.

1. What did I do?
I tried to deploy using this command "serverless deploy -v"

1. What happened?
```
CloudFormation "CREATE_COMPLETE"
Stack create finished.
Uploading CloudFormation file to S3...
```
But after that I got this error "Recoverable error occurred (socket hang up), sleeping for ~6 seconds. Try 1 of 4"

1. What should've happened?

 `Uploading CloudFormation file to S3...`
Related files should stored on S3, but no file uploaded into S3

1. Content of your `serverless.yml` file?
```
service: api-service

provider:
  name: aws
  runtime: python3.6
  region: us-west-2

plugins:
  - serverless-python-requirements

functions:
  get_zones:
    handler: handler.get_zones
    events:
      - http:
          path: v1.0/get_zones
          method: get
          cors: true

  get_current_time:
    handler: handler.get_current_time
    events:
      - http:
          # In order for path variables to work, API Gateway also needs them in the method path itself
          path: v1.0/get_current_time/{region}
          method: get
          cors: true
          request:
            parameters:
              paths:
                region: true
```
