### ISSUE TITLE
Pass CORS allowCredentials directive to method and integration responses

### ISSUE THREAD

**Issue by ThomasAribart** [serverless/serverless#7575]
# Feature Proposal

## Description

When using `lambda` integration with CORS enabled and setting the `allowCredentials` to `true`, the `Access-Control-Allow-Credentials` header is present in the OPTION request response but not in the subsequent request response, which blocks the browser from reading it.

<img width="380" alt="Serverless.yml" src="https://user-images.githubusercontent.com/38014240/79142514-eb676680-7dbb-11ea-8466-04aabb975a11.png">

<img width="942" alt="API Gateway" src="https://user-images.githubusercontent.com/38014240/79142533-f15d4780-7dbb-11ea-9a64-3d9c41b47c0a.png">

<img width="459" alt="browser network error" src="https://user-images.githubusercontent.com/38014240/79142606-0d60e900-7dbc-11ea-84e9-1fcdb5eccd2e.png">

<img width="483" alt="browser console error" src="https://user-images.githubusercontent.com/38014240/79142547-f621fb80-7dbb-11ea-83b8-167e559a8ec4.png">

This forces me to additionally set the `Access-Control-Allow-Credentials` to `true` in the response headers of my lambda.

Is it possible to pass down the original allowCredential directive to the method and integration responses ?

Current configuration:
```
functions:
  refresh:
    handler: /my/handler
    events:
      - http:
          method: get
          path: my/path
          integration: lambda
          cors:
            origin: http://localhost:3000/
            allowCredentials: true
          response:
            headers:
              Access-Control-Allow-Credentials: "'true'"
```

Desired configuration:
```
functions:
  refresh:
    handler: /my/handler
    events:
      - http:
          method: get
          path: my/path
          integration: lambda
          cors:
            origin: http://localhost:3000/
            allowCredentials: true
```

Many thanks,

Thomas
