### ISSUE TITLE
Serverless deploy ignores S3 event trigger

### ISSUE THREAD

**Issue by john-aws** [serverless/serverless#7579]
# Bug Report

## Description

The `DropHandler` function below attempts to configure an S3 event trigger on the bucket `S3BucketDrop` but the `events` attribute seems to be completely ignored by serverless deploy. No event trigger is added, and no warning or error is emitted.

Versions in use are:

Framework Core: 1.67.3
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.29.1

```
service: test-s3-event

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: jason
  stackName: test-s3-event

resources:
  Resources:
    S3BucketDrop:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: test-s3-event-bucket

    S3BucketDropPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: test-s3-event-bucket
        PolicyDocument:
          Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::123412341234:user/mary
            Resource:
              - 'arn:aws:s3:::test-s3-event-bucket/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

    RoleFileDropHandler:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: s3-access
            PolicyDocument:
              Statement:
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeletetObject
                Resource: 'arn:aws:s3:::test-s3-event-bucket/*'

functions:
  DropHandler:
    handler: index.handler
    description: Testing sls event triggers
    role: RoleFileDropHandler
    events:
      - s3:
        bucket: drop
        # bucket: S3BucketDrop
        event: s3:ObjectCreated:*

```

**Comment by herebebogans** [comment]
You need to add a `provider.s3.drop` section see

Custom bucket configuration

https://serverless.com/framework/docs/providers/aws/events/s3/

**Comment by john-aws** [comment]
Thanks. I made that modification, at least as far as I understand the documentation. I also simplified the template just to get going, but was not able to make this work. The following doesn't actually even create the `test-s3-event-bucket` bucket.

```
service: test-s3-event

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: jason
  stackName: test-s3-event
  s3:
    drop:
      name: test-s3-event-bucket

functions:
  DropHandler:
    handler: drop.handler
    description: Testing sls event triggers
    role: RoleFileDropHandler
    events:
      - s3:
        bucket: drop
        event: s3:ObjectCreated:*

resources:
  Resources:
 
    RoleFileDropHandler:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        Policies:
          - PolicyName: s3-access
            PolicyDocument:
              Statement:
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeletetObject
                Resource: 'arn:aws:s3:::test-s3-event-bucket/*'

```

**Comment by herebebogans** [comment]
```
    events:
      - s3:
        bucket: drop
        event: s3:ObjectCreated:*
```

should be 

```
    events:
      - s3:
          bucket: drop
          event: s3:ObjectCreated:*
```
