### ISSUE TITLE
Serverless not deploying new resources deleted via GUI

### ISSUE THREAD

**Issue by joshghent** [serverless/serverless#7581]
# Bug Report

## Description

1. What did you do?
A resource (an SQS queue) got deleted because for some reason serverless said that the resource already existed and would seemingly not deploy past it. I decided to delete it and run a fresh deployment. 

2. What happened?
This did not then redeploy the queue, instead it seemed to do nothing with the modified resources.

3. What should've happened?
It should have overwritten the drifted resources and freshly deployed the deleted queue and set it up as a DLQ for another queue (also specified in the serverless config)

1. What's the content of your `serverless.yml` file?
```yaml
service: my-lambda

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  deploymentBucket: ${self:service}-deployments-${opt:region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource:
        - arn:aws:sqs:${opt:region}:${env:AWS_ACCOUNT_ID}:yy-${opt:stage}.fifo
        - arn:aws:sqs:${opt:region}:${env:AWS_ACCOUNT_ID}:xx-${opt:stage}.fifo
    - Effect: Allow
      Action:
        - kms:GenerateDataKey
        - KMS:Decrypt
        - KMS:Encrypt
      Resource:
        - arn:aws:kms:${opt:region}:${env:AWS_ACCOUNT_ID}:key/*

plugins:
  - serverless-plugin-aws-alerts
  - serverless-python-requirements

package:
  exclude:
    - .travis.yml
    - "*.env"
    - env.tar.gz
    - env.tar.gz.enc
    - .eslintrc.js
    - yarn.lock
    - .ci/**
    - tests/**
    - node_modules/.bin/**
    - node_modules/.yarn-integrity
    - README.md
    - package-lock.json
    - "*/__pycache__/**"
    - "*.pyc"
    - venv/**

functions:
  XxFunction:
    handler: my-lambda/xx.handler
    environment:
      ENV: ${opt:stage}
      region: ${env:REGION, opt:region}
    tags:
      env: ${opt:stage}
    timeout: 300
    events:
      - sqs: arn:aws:sqs:${opt:region}:${env:AWS_ACCOUNT_ID}:xx-${opt:stage}.fifo

  YyFunction:
    handler: my-lambda/yy.handler
    environment:
      ENV: ${opt:stage}
    tags:
      env: ${opt:stage}
    timeout: 300
    events:
      - sqs: arn:aws:sqs:${opt:region}:${env:AWS_ACCOUNT_ID}:yy-${opt:stage}.fifo

resources:
  Resources:
    MasterKey:
      -- REMOVED from the template for this bug report but this resource is ok ---

    YyQueue:
      Type: "AWS::SQS::Queue"
      DependsOn: YyDeadLetterQueue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        KmsMasterKeyId:
          Ref: MasterKey
        KmsDataKeyReusePeriodSeconds: 86400 # 1 day
        QueueName: yy-${opt:stage}.fifo
        VisibilityTimeout: 300
        MessageRetentionPeriod: ${env:MESSAGE_RETENTION_SECONDS}
        RedrivePolicy:
          deadLetterTargetArn:
            "Fn::GetAtt":
              - YyDeadLetterQueue
              - Arn
          maxReceiveCount: 3

    YyDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        FifoQueue: true
        ContentBasedDeduplication: true
        KmsMasterKeyId:
          Ref: MasterKey
        KmsDataKeyReusePeriodSeconds: 86400 # 1 day
        QueueName: yy-dead-letter-${opt:stage}.fifo
        MessageRetentionPeriod: 1209600

    XxQueue:
      Type: "AWS::SQS::Queue"
      DependsOn: YyDeadLetterQueue
      Properties:
        ContentBasedDeduplication: true
        DelaySeconds: 300
        FifoQueue: true
        KmsMasterKeyId:
          Ref: MasterKey
        KmsDataKeyReusePeriodSeconds: 86400 # 1 day
        QueueName: xx-${opt:stage}.fifo
        VisibilityTimeout: 300
        MessageRetentionPeriod: ${env:MESSAGE_RETENTION_SECONDS}
        RedrivePolicy:
          deadLetterTargetArn:
            "Fn::GetAtt":
              - XxDeadLetterQueue
              - Arn
          maxReceiveCount: 3

    XxDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        FifoQueue: true
        ContentBasedDeduplication: true
        KmsMasterKeyId:
          Ref: MasterKey
        KmsDataKeyReusePeriodSeconds: 86400 # 1 day
        QueueName: xx-dead-letter-${opt:stage}.fifo
        MessageRetentionPeriod: 1209600
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
Trimmed for brevity but let me know if you need anything else of the output. The rest is just mostly the loading and packaging...
```
Serverless: [AWS lambda 200 0.463s 0 retries] getFunction({ FunctionName: 'my-lambda-prod-YyFunction' })
Serverless: [AWS lambda 200 0.49s 0 retries] getFunction({ FunctionName: 'my-lambda-prod-XxFunction' })
Serverless: Service files not changed. Skipping deployment...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 200 0.447s 0 retries] describeStacks({ StackName: 'my-lambda-prod' })
Serverless: [AWS cloudformation 200 0.436s 0 retries] listStackResources({ StackName: 'my-lambda-prod' })
Service Information
service: my-lambda
stage: prod
region: us-east-1
stack: my-lambda-prod
resources: 27
api keys:
  None
endpoints:
  None
functions:
  YyFunction: my-lambda-prod-YyFunction
  XxFunction: my-lambda-prod-XxFunction
layers:
  None
Serverless: Invoke aws:deploy:finalize
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
```

Similar or dependent issues:
Perhaps this one? https://github.com/serverless/serverless/issues/5652

Thanks in advance for your help
