### ISSUE TITLE
httpApi cloudformation Ref?

### ISSUE THREAD

**Issue by jazjaazjaaaz** [serverless/serverless#7590]
I am currently using this on serverless.yml to implement CORS

```
provider:
  httpApi:
    Ref: httpApiCustom
functions:
  login:
    name: 'login'
    events:
      - httpApi: POST /login

resources:
  Resources:
    httpApiCustom:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: api-name
        ProtocolType: HTTP
        CorsConfiguration:
          AllowOrigins: 
            - '*'
    httpApiCustomStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        ApiId:
          Ref: httpApiCustom
        StageName: ${self:provider.stage}
```

But it seems is does not reference to the cloudformation and instead creates 2 APIs, one which has the routes with no CORS, and the other one has the CORS but no routes. Any ideas?

**Comment by jonasduever** [comment]
Maybe the `extensions` section is what you're looking for?

```
resources:
  extensions:
    HttpApi:
      Properties:
        Tags:
          Project: 'Example'
    HttpApiStage:
      Properties:
        DefaultRouteSettings:
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 200
```

If you just want to set the CORS headers, just follow the [docs](https://serverless.com/framework/docs/providers/aws/events/http-api#cors-setup):
```
provider:
  httpApi:
    cors: 
      allowedOrigins: '*'
      [...]
```

**Comment by jazjaazjaaaz** [comment]
@jonasduever, I tried it but no luck. Also the same with the docs. Setting cors:true deploys the API but does not apply the CORS configuration for it.

Nevertheless it is working now. I noticed on the template that the framework uses "HttpApi" as resource name and tried to set the custom one with the same name and it applies now the configuration from the custom template.

```
provider:
  httpApi:
    Ref: HttpApi
functions:
  login:
    name: 'login'
    events:
      - httpApi: POST /login

resources:
  Resources:
    HttpApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: api-name
        ProtocolType: HTTP
        CorsConfiguration:
          AllowOrigins: 
            - '*'
    HttpApiStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        ApiId:
          Ref: HttpApi
        StageName: ${self:provider.stage}
```

It's just weird though that when trying to set the CORS as stated in the docs. It's not working
