### ISSUE TITLE
Support Lambda reading from multiple SQS queues.

### ISSUE THREAD

**Issue by dyang108** [serverless/serverless#7591]
# Feature Proposal

## Description

1. What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
I'd like for lambda to have more than one sqs event mapping. We handle traffic from multiple (similar) queues, and it'd be awesome to have something like this:
```
 myfunction:
     ...
     events:
      - sqs:
         arn: arn:aws:sqs:us-west-2:111111111111:queue1
      - sqs:
         arn: arn:aws:sqs:us-west-2:111111111111:queue2
```

What I'm currently observing is that we only bind the event for the *last* sqs queue
1. **Optional:** If there is additional config how would it look

Similar or dependent issues:

- #12345
