### ISSUE TITLE
Improve function event configuration format

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#7601]
Currently events are configured with YAML as follows:

```yaml
functions:
  functionName:
    events:
      - evenType:
          eventProperty: "foo"
```

Which translate to following JSON:

```json
{
  "functions":  {
    "functionName": {
      "events": [
        {
          "eventType": {
            "eventProperty": "foo"
          }
        }
      ]
    }
  }
}
```

Which weird and not intutive. Many users fall on this, producing configurations which are not read properly.

More proper construct would be:

```yaml
functions:
  functionName:
    events:
      - type: eventType
        eventProperty: "foo"
```

Which would translate to following JSON:

```json
{
  "functions":  {
    "functionName": {
      "events": [
        {
          "type": "eventType",
          "eventProperty": "foo"
        }
      ]
    }
  }
}
```
