### ISSUE TITLE
AWS Lambda Destination Function doesn't exist in this Service

### ISSUE THREAD

**Issue by strumwolf** [serverless/serverless#7618]
# Bug Report

## Description
When using 
```
...
destination:
  onFailure: ${SQS.Arn}
```
in my function declaration, I receive a `Function "#{TaxQueue.Arn}" doesn't exist in this Service` error.

1. What did you do?
Attempted to deploy a function with an Async destination on failure
1. What happened?
Deployment failed with `Function "#{TaxQueue.Arn}" doesn't exist in this Service` error.
1. What should've happened?
Deployment should have succeeded adding the SQS queue as the destination.

I'm no expert on the ins and out of _how_ serverless does it's thing, but https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/functions/index.js#L611 seems like it would never attempt to add any action other than a function. Maybe I'm wrong?
1. What's the content of your `serverless.yml` file?
```
service: fye-tax-reporting

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.REGION}
  stage: ${opt:stage, self:custom.stage}
  iamRoleStatements:
    - Sid: sqsPermissions
      Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        - '#{TaxQueue.Arn}'
    - Sid: networkPermissions
      Effect: Allow
      Action:
        - 'ec2:CreateNetworkInterface'
        - 'ec2:DescribeNetworkInterfaces'
        - 'ec2:DetachNetworkInterface'
        - 'ec2:DeleteNetworkInterface'
      Resource: '*'

  timeout: 120
  vpc:
    ...

functions:
  ImportFromS3:
    name: fye-tax-reporting-import-from-s3-${self:provider.stage}
    handler: functions/import-from-s3/index.handler
    destinations:
      onFailure: '#{TaxQueue.Arn}'
    vpc:
      securityGroupIds:
        - ${self:custom.RDS_SECURITY_GROUP}
    environment:
      TAX_TABLE: ${self:custom.TAX_TABLE}
      SQS_QUEUE: '#{TaxQueue}'
      PGHOST: ${self:custom.PGHOST}
      PGPORT: ${self:custom.PGPORT}
      PGDATABASE: ${self:custom.PGDATABASE}
      PGUSER: ${self:custom.PGUSER}
      PGPASSWORD: ${self:custom.PGPASSWORD}
    events:
      - s3:
          bucket: '#{RawBucket}'
          event: s3:ObjectCreated:Put
          rules:
            - prefix: FYE-TaxCallOut
            - suffix: .csv
          existing: true
      - sqs:
          enabled: true
          batchSize: 1
          arn: '#{TaxQueue.Arn}'
    tags:
      application: tax-reporting

custom:
...

resources:
  Resources:
    ...

    TaxQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: tax-reporting-load-queue-${self:provider.stage}
        VisibilityTimeout: 300
        RedrivePolicy:
          maxReceiveCount: 3
          deadLetterTargetArn: '#{TaxDLQ.Arn}'
        Tags:
          - Key: application
            Value: tax-reporting

    TaxDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: tax-reporting-load-dlq-${self:provider.stage}
        Tags:
          - Key: application
            Value: tax-reporting

```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)
```
...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Function "#{TaxQueue.Arn}" doesn't exist in this Service
      at Service.getFunction (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/Service.js:232:11)
      at AwsCompileFunctions.ensureTargetExecutionPermission (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:629:39)
      at AwsCompileFunctions.memoized [as ensureTargetExecutionPermission] (/Users/briankurtz/.config/yarn/global/node_modules/lodash/lodash.js:10552:27)
      at AwsCompileFunctions.compileFunctionDestinations (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:593:14)
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:555:56
      at ReadStream.<anonymous> (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:465:15)
      at ReadStream.emit (events.js:311:20)
      at ReadStream.EventEmitter.emit (domain.js:482:12)
      at internal/fs/streams.js:241:14
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:555:40
  From previous event:
      at AwsCompileFunctions.compileFunction (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:121:25)
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:642:62
  From previous event:
      at AwsCompileFunctions.compileFunctions (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:642:22)
  From previous event:
      at Object.package:compileFunctions [as hook] (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:32:12)
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at PluginManager.spawn (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:510:17)
      at Deploy.<anonymous> (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:490:55
  From previous event:
      at PluginManager.invoke (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/Users/briankurtz/.config/yarn/global/node_modules/serverless/lib/Serverless.js:120:74)
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/bin/serverless.js:82:30
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:136:16
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:136:16
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
      at FSReqCallback.oncomplete (fs.js:154:23)
  From previous event:
      at /Users/briankurtz/.config/yarn/global/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/Users/briankurtz/.config/yarn/global/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:1158:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
      at Module.load (internal/modules/cjs/loader.js:1002:32)
      at Function.Module._load (internal/modules/cjs/loader.js:901:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47
```

Similar or dependent issues:
...
