### ISSUE TITLE
batchWindow: None ,  Retry attempts: 10000

### ISSUE THREAD

**Issue by jarriaga** [serverless/serverless#7630]
# batchWindow in DynamodDB 

## Description

after successfully configured a lambda function with an event stream using dynamodb Stream ARN, the property batchWindow was not updated neither maximumRetryAttempts into the event lambda function

1. What did you do?
I have configured a lambda function with event stream using dynamodb with a batchSize: 300 and batchWindow: 360,

1. What happened?
the function was created successfully but the trigger in the lambda function does not save the batchWindow option even when this was added to the serverless.yml file

1. What should've happened?
batchWindow property should have 360 as value
maximumRetryAttempts: 10

1. What's the content of your `serverless.yml` file?

```
service: maxmind-cache  

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  stage: stage
  memorySize: 512
  deploymentBucket:
    name: xserverless.deploys


functions:
  api:
    handler: index.handler
    description: Lambda Function for Maxmind 
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  stats:
    handler: stats.handler
    description: Maxmind Stats Generator
    events:
      - stream:
          arn: arn:aws:dynamodb:us-east-1:425231278465:table/MAXMIND-request/stream/2020-04-27T23:32:22.272
          batchSize: 300
          batchWindow: 360
          type: dynamodb
          maximumRetryAttempts: 10
          startingPosition: LATEST
          enabled: true

```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

added output here 
[SLS_DEBUG-file.txt](https://github.com/serverless/serverless/files/4543854/SLS_DEBUG-file.txt)

Similar or dependent issues:

[similar issue](https://github.com/serverless/serverless/issues/3090)

![image](https://user-images.githubusercontent.com/6171891/80456056-8864ec00-88f2-11ea-802d-896bb2c37d53.png)
