### ISSUE TITLE
CloudFormation is waiting for NetworkInterfaces associated with the Lambda Function to be cleaned up.

### ISSUE THREAD

**Issue by jamesla** [serverless/serverless#7633]
# Bug Report

When removing a serverless deployment (that is configured to use an AWS VPC) the stack hangs on "CloudFormation is waiting for NetworkInterfaces associated with the Lambda Function to be cleaned up." for 45 minutes before AWS killing the stack.

```
provider:
  name: aws
  httpApi:
    id: ${env:APIGW_ID}
  stage: ${env:STAGE}
  runtime: nodejs12.x
  region: us-east-1
  role: ${env:ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}
    serverSideEncryption: AES256
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP}
    subnetIds:
      - ${env:SUBNET_A}
      - ${env:SUBNET_B}
```

Once it times out and cloudformation just force deletes the stack, you can see that it leaves a bunch of network interfaces bound to the security groups which appear to be where the problem lies.

If I remove the VPC: block then it removes quickly.

It would appear there is a race condition in the way that the cloudformation template gets built. Has anybody seen this one before?
