### ISSUE TITLE
AWS Cloudformation Rollback / Delete, verbose mode doesn't show CF error.

### ISSUE THREAD

**Issue by herebebogans** [serverless/serverless#7635]
_What did you do?_

Deployed a serverless stack for first time with an error causing a CF rollback and delete stack.
What happened?

> CF Error above
> ....
> CloudFormation - DELETE_COMPLETE - AWS::CloudFormation::Stack -mystack-mystage
> Serverless: Stack create finished...
> 
>   Serverless Error ---------------------------------------
> 
>   Stack with id mystack-mystage does not exist

_What should've happened?_

sls deploy should determine the rollback / delete stack as an error and unsuccessful deployment.
output should show the cloudformation error as an update stack operation does.

**Comment by medikoo** [comment]
@herebebogans thanks for report. It's definitely worth fixing. PR's welcome!

**Comment by AhmedFat7y** [comment]
I tried to reproduce the issue but couldn't

This happens because when you monitor a stack you check its status? and the status will be `DELETE_IN_PROGRESS` rather than an error and `serverless` will not detect the issue?

**Comment by medikoo** [comment]
@AhmedFat7y this error happens only when you deploy service for first time. To reproduce you need to:
1. Configure service with an error that'll be exposed by CloudFormation (during deployment of stack, and not validation of a template)
2. Deploy service

Real CloudFormation error will be hidden, instead Framework will crash not meaningfully as above

**Comment by AhmedFat7y** [comment]
@medikoo 
> 1. Configure service with an error that'll be exposed by CloudFormation (during deployment of stack, and not validation of a template)

I tried to do that, but it displays the CF error normally. I'm not sure how to reproduce, so a list of stack events from such cases can be helpful

**Comment by medikoo** [comment]
@AhmedFat7y indeed I also have problems in reproducing that.

@herebebogans can you provide a bit more details, e.g, full content of `serverless.yml` ?

**Comment by TfNSWTicketingSolutionsDevelopment** [comment]
Sorry I left a key piece of info out of the report.

This only occurs when you specify a deploymentBucket in provider.

Here's a minimal serverless.yml to recreate the issue.

```
service: sls-rollback-issue

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  deploymentBucket: my-existing-deployment-bucket
resources:
  Resources:
    ##############################
    # S3
    ##############################
    TestBucket:
      Type: AWS::S3::Bucket
      Properties:
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: three
              Prefix: "/"
              Status: Enabled
```
 Output

```
$ sls deploy --verbose
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - sls-rollback-issue-dev
CloudFormation - CREATE_FAILED - AWS::S3::Bucket - TestBucket
CloudFormation - DELETE_IN_PROGRESS - AWS::CloudFormation::Stack - sls-rollback-issue-dev
CloudFormation - DELETE_COMPLETE - AWS::S3::Bucket - TestBucket
CloudFormation - DELETE_COMPLETE - AWS::CloudFormation::Stack - sls-rollback-issue-dev
Serverless: Stack create finished...

  Serverless Error ---------------------------------------

  Stack with id sls-rollback-issue-dev does not exist
```

The "three" for ExpirationInDays is invalid at cloudformation run time.

**Comment by herebebogans** [comment]
Sorry I left a key piece of info out of the report.

This only occurs when you specify an existing deploymentBucket in provider.

Here's a minimal serverless.yml to recreate the issue.

```
service: sls-rollback-issue

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  deploymentBucket: my-existing-deployment-bucket
resources:
  Resources:
    TestBucket:
      Type: AWS::S3::Bucket
      Properties:
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: three
              Prefix: "/"
              Status: Enabled
```
 Output

```
$ sls deploy --verbose
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - sls-rollback-issue-dev
CloudFormation - CREATE_FAILED - AWS::S3::Bucket - TestBucket
CloudFormation - DELETE_IN_PROGRESS - AWS::CloudFormation::Stack - sls-rollback-issue-dev
CloudFormation - DELETE_COMPLETE - AWS::S3::Bucket - TestBucket
CloudFormation - DELETE_COMPLETE - AWS::CloudFormation::Stack - sls-rollback-issue-dev
Serverless: Stack create finished...

  Serverless Error ---------------------------------------

  Stack with id sls-rollback-issue-dev does not exist
```

The "three" for ExpirationInDays is invalid at cloudformation run time and causes a rollback.
