### ISSUE TITLE
ALB Listener import syntax considered invalid by lambda alb event config code

### ISSUE THREAD

**Issue by mjhanke** [serverless/serverless#7646]
# Bug Report

## Description

1. What did you do? Used `"Fn::ImportValue: ${self:custom.other-service-name}-ALBListenerArn"` for lambda function's alb `listenerArn` property
1. What happened? `Invalid ALB listenerArn in function "${functionName}".`
1. What should've happened? serverless should fetch the valid Arn from another stack
1. What's the content of your `serverless.yml` file?

```
functions:
...
function-invoked-by-alb:
  handler: wsgi.handler
    timeout: 30
    events:
      - http: ANY /api/{version}/endpoint
      - alb:
          priority: 1
          listenerArn:
            "Fn::ImportValue: ${self:custom.other-service-name}-ALBListenerArn"
          conditions:
            path: /api/v?/endpoint
    environment:
      ....
```

The source code causing this behavior is here: https://github.com/serverless/serverless/blob/81eb62a7fb56da01ecfc9ded3b6cc25df38e6348/lib/plugins/aws/package/compile/events/alb/lib/validate.js#L102-L104

**Comment by medikoo** [comment]
@mjhanke thanks for report. Still it's not really a bug, more an intended limitation.

To construct properly ALB event we need to have complete ALB info upfront. Currently in code it's resolved sync way.

Also normally we allow _packaging_ feature to work offline. Introducing here a dependency on CloudFormation, will no longer allow to package project without issuing AWS SDK requests.

**Comment by mjhanke** [comment]
> Still it's not really a bug, more an intended limitation.

What do you mean by "intended limitation"?

We use the "Fn::Import" syntax all over the place in our serverless project.

The ALB event sugar creates a [ListenerRule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listenerrule.html#cfn-elasticloadbalancingv2-listenerrule-listenerarn).

Can you help me understand why the generated ListenerRule would be invalid with the Fn::Import syntax?

**Comment by medikoo** [comment]
@mjhanke please see the implementation, and see that on packaging level we need to resolve ALB Id and listener id from ARN: https://github.com/serverless/serverless/blob/81eb62a7fb56da01ecfc9ded3b6cc25df38e6348/lib/plugins/aws/package/compile/events/alb/lib/validate.js#L106-L112

We do it on spot, without dependency on external resources. Also note that service packaging also works that way (offline, without dependency on external resources)

**Comment by mjhanke** [comment]
Interesting. I'm trying to reconcile this with our existing use of the "Fn::Import" syntax with the serverless framework

```yaml
provider:
  name: aws
  runtime: python3.6
  ...
  role:
    Fn::ImportValue: ${self:custom.infrastructureServiceName}-lambdaExecutionRoleArn
  environment:
    ...
  vpc:
    securityGroupIds:
      - Fn::ImportValue: ${self:custom.infrastructureServiceName}-serverlessSecurityGroupId
    subnetIds:
      - Fn::ImportValue: ${self:custom.infrastructureServiceName}-PrivateSubnetNoInternet1
      - Fn::ImportValue: ${self:custom.infrastructureServiceName}-PrivateSubnetNoInternet2
      - Fn::ImportValue: ${self:custom.infrastructureServiceName}-PrivateSubnetNoInternet3
```

This syntax works for those cases. Is what you're saying that support of that syntax is considered a feature? not a bug?
