### ISSUE TITLE
Deployment appears to fail when removing a Lambda function using EventBridge (but doesn't)

### ISSUE THREAD

**Issue by ThomasAribart** [serverless/serverless#7655]
# Bug Report

## Description

1. What did you do?

I deployed a stack with Lambda functions connected to EventBridge, and removed one.

1. What happened?

The deployment appeared to fail: The message "Operation failed!" appeared. However, the lambda is correctly removed.

1. What should've happened?

The deployment should have gone smoothly, and not triggered a false positive.

1. What's the content of your `serverless.yml` file?

```
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: test
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  test1:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever
  test2:
    handler: test.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          pattern:
            source:
              - whatever
            detail-type:
              - whatever

custom:
  eventBusArn: arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:event-bus/my-bus
```

1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

*An error occurred: CustomEventBridge1 - Failed to delete resource. User: ...-custom-resource-event-bridge is not authorized to perform: lambda:RemovePermission on resource: ...test3 See details in CloudWatch Log: ...*
