### ISSUE TITLE
Cannot use ref in ARN of dyanamodb stream

### ISSUE THREAD

**Issue by bsafwen** [serverless/serverless#7660]
# Bug Report

## Description

1. What did you do?
I am using nested stacks with the help of serverless-plugin-split-stacks. I exported a table's arn from nested stack A and I am trying to reference it in the root stack using Ref in the arn of the dynamodb stream event that will trigger a lambda.
1. What happened?
I get this error when packaging my service:
`ServerlessError: Bad dynamic ARN property on stream event in function "send-app-to-central-v1" If you use a dynamic "arn" (such as with Fn::GetAtt, Fn::Join, Ref or Fn::ImportValue) there must only be one key (either Fn::GetAtt, Fn::Join, Ref or Fn::ImportValue) in the arn object. Please check the docs for more info.`
1. What should've happened?
Serverless should have accepted the reference.
1. What's the content of your `serverless.yml` file?
```
   mylambda:
    handler: src/file.handlerV1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sts:AssumeRole
        Resource: ${self:custom.vars.XXX}
      - Effect: Allow
        Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
        Resource: !Join ['/', ['arn:aws:dynamodb:*:*:table', !Ref myTable]]
     events:
       - stream:
           type: dynamodb
           arn: !Ref myTable
```
1. What's the output you get when you use the `SLS_DEBUG=*` environment variable (e.g. `SLS_DEBUG=* serverless deploy`)

` 
  Serverless Error ---------------------------------------
 
  ServerlessError: Bad dynamic ARN property on stream event in function "mylambda" If you use a dynamic "arn" (such as with Fn::GetAtt, Fn::Join, Ref or Fn::ImportValue) there must only be one key (either Fn::GetAtt, Fn::Join, Ref or Fn::ImportValue) in the arn object. Please check the docs for more info.
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:140:25
      at Array.forEach (<anonymous>)
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:94:28
      at Array.forEach (<anonymous>)
      at AwsCompileStreamEvents.compileStreamEvents (/home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/plugins/aws/package/compile/events/stream/index.js:44:47)
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/classes/PluginManager.js:490:55
      at doneOne (/home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/node_modules/fs-extra/lib/copy/ncp.js:237:40)
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/node_modules/fs-extra/lib/copy/ncp.js:122:11
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/node_modules/graceful-fs/polyfills.js:243:20
      at FSReqCallback.oncomplete (fs.js:159:23)
  From previous event:
      at PluginManager.invoke (/home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/classes/PluginManager.js:490:22)
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/classes/PluginManager.js:525:24
  From previous event:
      at PluginManager.run (/home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/classes/PluginManager.js:525:8)
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/Serverless.js:133:33
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Serverless.run (/home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/lib/Serverless.js:120:74)
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/bin/serverless.js:82:30
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:144:16
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:61:14
      at FSReqCallback.oncomplete (fs.js:159:23)
  From previous event:
      at /home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/bin/serverless.js:82:8
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/home/safwen/workspace/appwatch-lambda/appwatch/node_modules/serverless/bin/serverless.js:71:4)
      at Module._compile (internal/modules/cjs/loader.js:1123:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
      at Module.load (internal/modules/cjs/loader.js:972:32)
      at Function.Module._load (internal/modules/cjs/loader.js:872:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at /usr/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
`

Similar or dependent issues:
