### ISSUE TITLE
Enable setting contentHandling property at the integration response level

### ISSUE THREAD

**Issue by ThomasAribart** [serverless/serverless#7705]
### Use case description

On my project, I need to convert a lambda response to binary in API Gateway, which can be done by using lambda integration, returning a b64 encoded string and setting the response contentHandling property to CONVERT_TO_BINARY.

However, I want to convert the returned value only when the lambda's execution is successful. When it errored, I want to pass the body through so I can read it. It means having different contentHandling properties for different integration response.

CloudFormation enables setting the contentHandling property on a per integration response basis. However, this is not implemented in Serverless yet.

### Proposed solution

```
functions:
  test:
    handler: test.handler
    events:
      - http:
          method: get
          path: api/test
          integration: lambda
          response:
            statusCodes:
              200:
                pattern: ''
                contentHandling: CONVERT_TO_BINARY
              400:
                pattern: '400'
                contentHandling: CONVERT_TO_TEXT
```

=> The content handling property is correctly set for each integration response.
