### ISSUE TITLE
service.package.artifact not respected when packing layer

### ISSUE THREAD

**Issue by ZBAGI** [serverless/serverless#7713]
According to [serverless guide for packaging](https://www.serverless.com/framework/docs/providers/aws/guide/packaging/)

> For complete control over the packaging process you can specify your own artifact zip file. Serverless won't zip your service if this is configured and therefore exclude and include will be ignored. 

But providing `service.package.artifact` still causes layer to be packed.
`packageLayer` should respect that option and skip package creation.
At:
https://github.com/serverless/serverless/blob/9591d5a232c641155613d23b0f88ca05ea51b436/lib/plugins/package/lib/packageService.js#L87
should be additional check for `|| this.serverless.service.package.artifact`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: Example

package:
  artifact: build.zip
  
plugins:
  - serverless-tsc-builder
  - serverless-offline

custom: 
  stage: ${opt:stage}
  name: ${self:service}-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  stage: ${self:custom.stage}
  environment:
      stage: ${self:custom.stage}

layers:
  Util:
    name: ${self:custom.name}
    path: ./
    compatibleRuntimes:
      - nodejs12.x
```

</details>
