### ISSUE TITLE
'sls deploy' get some network issue in scf component 

### ISSUE THREAD

**Issue by xkelvinx666** [serverless/serverless#7714]
I download the demo from cloud.tencent.com. there is a network issue. they engineers describe that it is some issue from serverless core package. I try using another component which is website, and it work correctly

```
 Error: write EPROTO 4590425536:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at /usr/local/Cellar/serverless/1.70.0/libexec/lib/node_modules/serverless/node_modules/@serverless/utils-china/library/common/abstract_client.js:93:20
    at ClientRequest.<anonymous> (/usr/local/Cellar/serverless/1.70.0/libexec/lib/node_modules/serverless/node_modules/@serverless/utils-china/library/common/http/http_connection.js:73:7)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:463:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

37s › scfmydemo › write EPROTO 4590425536:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

![image](https://user-images.githubusercontent.com/15306173/81533515-f0a6d980-9398-11ea-8e30-5536b6d3dc0e.png)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
component: scf
name: scfmydemo
org: test
app: scfApp
stage: dev

inputs:
  name: scfMyFunction
  src: ./src
  runtime: Nodejs10.15
  region: ap-guangzhou
  handler: index.main_handler
  events:
    - apigw:
        name: serverless_api
        parameters:
          protocols:
            - http
            - https
          serviceName:
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /index
              method: GET
```

</details>

<details>
<summary><b><code>REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
sls deploy
```

</details>

<b>Installed version</b>

```
serverless ⚡ framework

       v2.30.10

node: v14.2.0
npm: v6.14.5
os:  Mac os  Mojave 10.14.6
```
