### ISSUE TITLE
Request from localhost will not complete

### ISSUE THREAD

**Issue by mattgraygithub** [serverless/serverless#7724]
I have some Serverless Lambdas written in Typescript and deployed to AWS with API Gateway. They work perfectly through the AWS Console and using serverless invoke local (on most machines). 

Back when I was in the office before lockdown, they worked perfectly on my machine using serverless invoke local; and my integration tests which call the RDS database using the Lambdas, all passed when ran on this machine. Now, for some very strange reason that I can't fathom, serverless invoke local now doesn't return anything on this machine; and the tests all fail for the same reason. And it only happens on this machine! If any of my colleagues clone the same repository and run it on their machines, everything works and the tests pass. It even works perfectly on my old laptop (which is very slow and out of date and I can't use it for work) connected to the same network! 

I don't believe it's a problem with blocked ports or network settings on my machine, because other services that make external calls from local all work perfectly. To test this (and test my AWS settings) I've even set up a Java/Springboot project and made calls to exactly the same database on the same port. It calls the database and returns the data as expected.

Yet in the serverless project, when running `serverless invoke local`, it tells me the handlers have been built successfully and gives no errors (even with `SLS_DEBUG=*`, but doesn't actually return the data. 

And every test fails with: 

`: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:`

I've also tried using the serverless-offline plugin and when using that, the lambdas get built with no errors and when trying the endpoints in a browser or with postman, it does nothing. Just shows a never ending spinning wheel and 'waiting for localHost', even though this also works as expected on every other computer!

I'm running macOS Catalina 10.15.4 (did a fresh install thinking it might solve this error - but it had no effect!)

I really would like to use the serverless framework but I can't use it if it will not allow me to work in a local environment on this machine!

Please help!

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: openspace-backend

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    PROD_DB_URI: ${env:PROD_DB_URI}
    PROD_DB_USER: ${env:PROD_DB_USER}
    PROD_DB_PASSWD: ${env:PROD_DB_PASSWD}
    PROD_DB_NAME: ${env:PROD_DB_NAME}
    DB_PORT: ${env:DB_PORT}

functions:
  getSessions:
    handler: SessionsHandler.getSessions
    events:
      - http:
          method: get
          path: /api/sessions

  addSession:
    handler: SessionsHandler.addASession
    events:
      - http:
          method: post
          path: /api/sessions

  editSession:
    handler: SessionsHandler.editASession
    events:
      - http:
          method: put
          path: /api/sessions/{id}

  deleteSession:
    handler: SessionsHandler.deleteASession
    events:
      - http:
          method: delete
          path: /api/sessions/{id}

  updateLike:
    handler: SessionsHandler.updateALike
    events:
      - http:
          method: post
          path: /api/sessions/{id}/likes/{email}

  getSpaces:
    handler: SpacesHandler.getSpaces
    events:
      - http:
          method: get
          path: /api/spaces

  addSpace:
    handler: SpacesHandler.addASpace
    events:
      - http:
          method: post
          path: /api/spaces

  editSpace:
    handler: SpacesHandler.editASpace
    events:
      - http:
          method: put
          path: /api/spaces/{id}

  deleteSpace:
    handler: SpacesHandler.deleteASpace
    events:
      - http:
          method: delete
          path: /api/spaces/{id}
```
</details>

<details>
<summary><b><code>
export SLS_DEBUG=*
serverless invoke local --function getSessions
</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: DOTENV: Loading environment variables from .env:
Serverless: 	 - PROD_DB_URI
Serverless: 	 - PROD_DB_USER
Serverless: 	 - PROD_DB_PASSWD
Serverless: 	 - PROD_DB_NAME
Serverless: 	 - DB_PORT
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke invoke:local
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Starting type checking service...
Using 1 worker with 2048MB memory limit
Time: 2969ms
Built at: 13/05/2020 14:58:24
             Asset      Size           Chunks             Chunk Names
SessionsHandler.js  27.8 KiB  SessionsHandler  [emitted]  SessionsHandler
Entrypoint SessionsHandler = SessionsHandler.js
[./SessionsHandler.ts] 1.66 KiB {SessionsHandler} [built]
[./src/Connection/ConnectionService.ts] 650 bytes {SessionsHandler} [built]
[./src/SessionsRepository/SessionsRepository.ts] 2.5 KiB {SessionsHandler} [built]
[./src/SessionsService/SessionsService.ts] 1.57 KiB {SessionsHandler} [built]
[dotenv] external "dotenv" 42 bytes {SessionsHandler} [built]
[pg] external "pg" 42 bytes {SessionsHandler} [built]
```

</details>

<b>Installed version</b>

```
Framework Core: 1.70.0
Plugin: 3.6.11
SDK: 2.3.0
Components: 2.30.10
```
