### ISSUE TITLE
Variable substitution fails on `provider` key

### ISSUE THREAD

**Issue by terry-au** [serverless/serverless#7727]
When attempting to use a common provider across my services, through a `file(…)` reference, a `name` key is inserted under `provider` and the referenced value placed under it, breaking the `serverless.yml` schema.

In the output below the `provider` key has a single child `name` key, whose value is that of the referenced value. The `foobar` key, which uses the exact same file reference does not contain the root child `name` key and produces the expected output.

<details>
<summary>
<code>
serverless.yml
</code>
</summary>

```yaml
service: hello-world

provider: ${file(./serverless.common.yml):provider}

foobar: ${file(./serverless.common.yml):provider}
```
</details>
<details>
<summary>
<code>
serverless.common.yml
</code>
</summary>

```yaml
provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  memorySize: 1024
  timeout: 60
  versionFunctions: true
  tracing:
    lambda: true
```
</details>

<details>
<summary><b><code>sls print</code> output</b></summary>

```yaml
service: hello-world
provider:
  name:
    name: aws
    runtime: nodejs10.x
    region: ap-southeast-2
    memorySize: 1024
    timeout: 60
    versionFunctions: true
    tracing:
      lambda: true
foobar:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  memorySize: 1024
  timeout: 60
  versionFunctions: true
  tracing:
    lambda: true
```

</details>

<b>Installed version</b>

```
Framework Core: 1.70.1
Plugin: 3.6.11
SDK: 2.3.0
Components: 2.30.10
```
