### ISSUE TITLE
Can't deploy an app

### ISSUE THREAD

**Issue by miholeus** [serverless/serverless#7732]
App is not deployed. I get an error.
Error is returned everytime I run
```
sls deploy
```
command
```
Fetch Error --------------------------------------------
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-bot

app: mhlbot
org: miholeus

provider:
  name: aws
  runtime: python3.8
  timeout: 10
  environment:
    SLACK_CLIENT_ID: 'xxxx'
    SLACK_CLIENT_SECRET: 'xxxx'
    SLACK_INCOMING_WEBHOOK_URL: 'xxx'
    PING_SERVICE_URL: 'xxx'
    PING_SERVICE_TIMEOUT: 5

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  authorization:
    handler: handler.authorization
    events:
      - http:
          method: get
          path: slack/authorization
  ping:
    handler: handler.ping
    events:
      - http:
          method: post
          path: slack/ping
  status:
    handler: handler.check_status
    events:
      - schedule: rate(1 minute)
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls deploy</code> output</b></summary>

```
SLS_DEBUG=* sls deploy
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
platform-sdk fetching: POST https://api.serverless.com/core/tenants/miholeus/applications/mhlbot/profileValue

  Fetch Error --------------------------------------------

  FetchError: request to https://api.serverless.com/core/tenants/miholeus/applications/mhlbot/profileValue failed, reason: read ECONNRESET
      at ClientRequest.<anonymous> (/usr/local/Cellar/serverless/1.70.1/libexec/lib/node_modules/serverless/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
      at ClientRequest.emit (events.js:315:20)
      at ClientRequest.EventEmitter.emit (domain.js:485:12)
      at TLSSocket.socketErrorListener (_http_client.js:463:9)
      at TLSSocket.emit (events.js:315:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at emitErrorNT (internal/streams/destroy.js:100:8)
      at emitErrorCloseNT (internal/streams/destroy.js:68:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
  From previous event:
      at PluginManager.asyncPluginInit (/usr/local/Cellar/serverless/1.70.1/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:634:22)
      at PluginManager.loadAllPlugins (/usr/local/Cellar/serverless/1.70.1/libexec/lib/node_modules/serverless/lib/classes/PluginManager.js:116:17)
      at /usr/local/Cellar/serverless/1.70.1/libexec/lib/node_modules/serverless/lib/Serverless.js:96:35
      at processImmediate (internal/timers.js:456:21)
  From previous event:
      at Serverless.init (/usr/local/Cellar/serverless/1.70.1/libexec/lib/node_modules/serverless/lib/Serverless.js:94:8)
      at Object.<anonymous> (/usr/local/Cellar/serverless/1.70.1/libexec/lib/node_modules/serverless/bin/serverless.js:79:4)
      at Module._compile (internal/modules/cjs/loader.js:1176:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
      at Module.load (internal/modules/cjs/loader.js:1040:32)
      at Function.Module._load (internal/modules/cjs/loader.js:929:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.2.0
     Framework Version:         1.70.1
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10
```

</details>

<b>Installed version</b>

```
Framework Core: 1.70.1
Plugin: 3.6.11
SDK: 2.3.0
Components: 2.30.10
```
