### ISSUE TITLE
"Cannot create proxy with a non-object as target or handler" on invoke local

### ISSUE THREAD

**Issue by spark323** [serverless/serverless#7737]
I get "Cannot create proxy with a non-object as target or handler" error on invoke local to test my lambda function. I can deploy stacks just fine. 

```yaml


##I used correct information in real situation (i could deploy stacks without any problem)

service: myservicename
# app and org for usewith dashboard.serverless.com
app: myappname
org: myorg



provider:
  name: aws
  runtime: nodejs12.x  
  role: arn:aws:iam::xxx:role/service-role/myLambdaExe
  stage: dev
  region: ap-northeast-2
  stackName: ${self:app}-lambda-1
  # profile: spark
  environment:
    app: ${self:app} 



functions:
  hello:
    handler: src/test/test.handler
    events:
      - http:
          path: hello
          method: get
          cors: true
```

</details>

I ran this commend

 serverless invoke local -f hello   --c serverless_lambda_1.yml</code> 

<b>Installed version</b>

```
Framework Core: 1.68.0
Plugin: 3.6.8
SDK: 2.3.0
Components: 2.30.2
```
