### ISSUE TITLE
redrivePolicy for SNS events - CloudFormation Template error

### ISSUE THREAD

**Issue by niranjannm** [serverless/serverless#7745]
**SLS Template Used:**

```
events:
  - sns:
      arn: <sns_arn>
      filterPolicy: <sns_filter_policy>
      redrivePolicy:
        deadLetterTargetArn: <sqs_arn>
```

**Error:**

`Error: The CloudFormation template is invalid: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.`

**More Details:**

- Believe the error to be happening from AWS::SQS::QueuePolicy of the generated CloudFormation.
- Below is what generated currently,

```
"Queues": [
  {
    "Fn::Join": [
      "",
      "https://sqs.<REGION>.",
      {
        "Ref": "AWS::URLSuffix"
      },
      "/<Account#>/<SQS_Name>"
    ]
  }
]
```

- _Guess issue will be fixed if it was below?!_

```
"Queues": [
  {
    "Fn::Join": [
      "", 
      [
        "https://sqs.<REGION>.",
        {
          "Ref": "AWS::URLSuffix"
        },
        "/<Account#>/<SQS_Name>"
      ]
    ]
  }
]
```

**SLS Version:**

```
Framework Core: 1.71.1
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
```

**Related Commit#:** 

[`de8cfff7c71839bb77df18e1d6d7aae33d55fd83`](https://github.com/serverless/serverless/pull/7239/commits/de8cfff7c71839bb77df18e1d6d7aae33d55fd83)

cc: @tcastelli @medikoo
