### ISSUE TITLE
"Serverless deploy" command is not using the path to artifact from "serverless.yml"

### ISSUE THREAD

**Issue by KnupMan** [serverless/serverless#7753]
**Describe the issue**
`serverless deploy` started to throw an error, but it was working okay before.
The problem happened just after release [1.71.2](https://github.com/serverless/serverless/releases/tag/v1.71.2) version.
I am assuming it started to add prefix `.serverless` for artifact's path, even I set it to just `artifact.zip` on `serverless.yml`.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: hello

provider:
  timeout: 20
  memorySize: 1536
  name: aws
  stage: production
  region: us-east-1
  runtime: nodejs12.x
  endpointType: REGIONAL
  versionFunctions: false
  tracing:
    lambda: true
  deploymentBucket: hello
  apiGateway:
    minimumCompressionSize: 0
  environment:
    ENVIRONMENT: ${opt:stage}

package:
  artifact: artifact.zip

plugins:
  - serverless-api-gateway-caching
  - serverless-associate-waf

custom:
  associateWaf:
    name: ${opt:stage}-hello
  apiGatewayCaching:
    enabled: true
    clusterSize: '0.5'
    ttlInSeconds: 60
    dataEncrypted: false
    perKeyInvalidation:
      requireAuthorization: true
      handleUnauthorizedRequests: IgnoreWithWarning

functions:
  helloFunc:
    handler: lib/hello-func/handler.handler
    name: ${opt:stage}-${self:service}-helloFunc
    memorySize: 3008
    timeout: 10
    events:
      - http:
          path: '/hello'
          method: get
          cors: true
```

</details>

<details>
<summary><b><code>serverless deploy --stage $ENVIRONMENT --package .serverless</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
  [AWS sts 200 0.05s 0 retries] getCallerIdentity({})
Serverless: Invoke deploy
Serverless: Invoke aws:common:validate
Serverless: [AWS s3 200 0.036s 0 retries] getBucketLocation({ Bucket: '***' })
Serverless: Invoke aws:common:moveArtifactsToTemp
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.06s 0 retries] describeStacks({ StackName: '***' })
Serverless: [AWS s3 200 0.037s 0 retries] listObjectsV2({
              Bucket: '***',
              Prefix: '***'
})
Serverless: [AWS s3 200 0.051s 0 retries] headObject({
              Bucket: '***',
              Key: '***'
})
Serverless: [AWS s3 200 0.104s 0 retries] headObject({
              Bucket: '***',
              Key: '***'
})
Serverless: [AWS lambda 200 0.064s 0 retries] getFunction({ FunctionName: '***' })

Error --------------------------------------------------

Error: ENOENT: no such file or directory, open '/home/circleci/repo/.serverless/artifact.zip'
         at /snapshot/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:143:9
         at Array.map (<anonymous>)
         at AwsDeploy.checkIfDeploymentIsNecessary (/snapshot/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:142:50)
         at AwsDeploy.<anonymous> (/snapshot/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:28:14)
From previous event:
  at AwsDeploy.checkForChanges (/snapshot/serverless/lib/plugins/aws/deploy/lib/checkForChanges.js:27:8)
From previous event:
  at Object.aws:deploy:deploy:checkForChanges [as hook] (/snapshot/serverless/lib/plugins/aws/deploy/index.js:104:12)
  at /snapshot/serverless/lib/classes/PluginManager.js:490:55
From previous event:
  at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
  at PluginManager.spawn (/snapshot/serverless/lib/classes/PluginManager.js:510:17)
  at AwsDeploy.<anonymous> (/snapshot/serverless/lib/plugins/aws/deploy/index.js:93:48)
From previous event:
  at Object.deploy:deploy [as hook] (/snapshot/serverless/lib/plugins/aws/deploy/index.js:89:30)
  at /snapshot/serverless/lib/classes/PluginManager.js:490:55
From previous event:
  at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:490:22)
  at /snapshot/serverless/lib/classes/PluginManager.js:525:24
From previous event:
  at PluginManager.run (/snapshot/serverless/lib/classes/PluginManager.js:525:8)
  at /snapshot/serverless/lib/Serverless.js:133:33
From previous event:
  at Serverless.run (/snapshot/serverless/lib/Serverless.js:120:74)
  at /snapshot/serverless/bin/serverless.js:80:26
  at processImmediate (internal/timers.js:456:21)
  at process.topLevelDomainCallback (domain.js:137:15)
From previous event:
  at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:80:4)
  at Module._compile (pkg/prelude/bootstrap.js:1320:22)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
  at Module.load (internal/modules/cjs/loader.js:1000:32)
  at Function.Module._load (internal/modules/cjs/loader.js:899:14)
  at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
  at internal/main/run_main_module.js:18:47

Get Support --------------------------------------------
Docs:          docs.serverless.com
Bugs:          github.com/serverless/serverless/issues
Issues:        forum.serverless.com

Your Environment Information ---------------------------
Operating System:          linux
Node Version:              12.16.1
Framework Version:         1.71.2 (standalone)
Plugin Version:            3.6.12
SDK Version:               2.3.0
Components Version:        2.30.11

  error Command failed with exit code 1.
```

</details>

<b>Installed version</b>

```
1.71.2
```
