### ISSUE TITLE
Documented ${self:provider.stage} doesn't resolve stage as expected

### ISSUE THREAD

**Issue by trondhindenes** [serverless/serverless#7767]
The variable `${self:provider.stage}` doesn't get set correctly when using the `--stage` command-line argument.

Given this file:
```yaml
---
service: kestrel-events-processor

provider:
  name: aws
  runtime: python3.8
  #stage: staging
  region: eu-west-1
  iamManagedPolicies:
    #- ${file(variables.yml):${self:provider.stage}-${self:provider.region}.s3_read_write_policy_arn}
  logRetentionInDays: 14

functions:
  s3_processor:
    handler: handler.doit
    events:
      - s3:
          bucket: ${file(variables.yml):${self:provider.stage}-${self:provider.region}.s3_bucket_name}
          event: s3:ObjectCreated:*
          rules:
            - prefix: kinesis/
          existing: true
    environment:
      BUCKET_NAME: ${file(variables.yml):${self:provider.stage}-${self:provider.region}.s3_bucket_name}
      WHAT: ${self:provider.region}
      WY: ${self:provider.stage}
      WHOO: ${self:provider.stage}-${self:provider.region}
```
And this command:
`serverless package --stage prod --region us-east-1`
I would expect the value of the "WHAT" and "WHOO" environment variables to be contain "prod". However, this is what gets set in the `.serverless/cloudformation-template-update-stack.json`:
```
        "Environment": {
          "Variables": {
            "BUCKET_NAME": {},
            "WHAT": "us-east-1",
            "WY": "dev",
            "WHOO": "dev-us-east-1"
          }
        }
```

As you can see, region is correctly resolved, but stage is not.

<b>Installed version</b>

```
Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11

```
