### ISSUE TITLE
Override functionName of CustomDashresourceDashapigwDashcwDashroleLambdaFunction

### ISSUE THREAD

**Issue by srashish** [serverless/serverless#7768]
I'm facing issues while trying to override function name of CustomDashresourceDashapigwDashcwDashroleLambdaFunction which gets generated when using API Logs in serverless yaml under provider section.

I've seen that it follows the name convention - `${self:service}-${self:custom.stage}-custom-resource-apigw-cw-role,` I'm trying to override it to use something like this `${self:service}-${self:custom.prefix, self:custom.stage}-custom-resource-apigw-cw-role`

Initial error while deploying

`An error occurred: ApiGatewayLogGroup - /aws/api-gateway/feature-service-dev already exists.
`
Tried overriding this with renaming LogGroupName under resources

serverless.yml

`logs: restApi: true iamrole: arn:aws:iam::XXXXXXXXXX:role/serverlessApiGatewayCloudWatchRole
`
`resources: extensions: ApiGatewayLogGroup: Properties: LogGroupName: /aws/apigateway/${self:service}-${self:custom.prefix, self:custom.stage}
`
The generated CF template json which this section is below

`"CustomDashresourceDashapigwDashcwDashroleLambdaFunction": { "Type": "AWS::Lambda::Function", "Properties": { "Code": { "S3Bucket": "XXXXXXX", "S3Key": "serverless/service-name/dev/xxxxxxxxxxx-2020-05-18T12:46:39.248Z/custom-resources.zip" }, "FunctionName": "feature-service-dev-custom-resource-apigw-cw-role", "Handler": "apiGatewayCloudWatchRole/handler.handler", "MemorySize": 1024, "Runtime": "nodejs12.x", "Timeout": 180, "Role": { "Fn::GetAtt": [ "IamRoleCustomResourcesLambdaExecution", "Arn" ] } }, "DependsOn": [ "IamRoleCustomResourcesLambdaExecution" ] },`

<details>
<summary><code>serverless.yml</code></summary>

```
service: ${self:custom.service.name}

plugins:
  - serverless-iam-roles-per-function
  - serverless-aws-resource-names
  - serverless-pseudo-parameters
  - serverless-domain-manager
  - serverless-mocha-plugin
  - serverless-prune-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  prefix: ${opt:prefix, self:provider.stage}
  domain_manager_basemapping:
    dev:
      dev: 'features'
    prod:
      prod: 'features'
    other: ${opt:prefix, 'dev'}-features
  service:
        name: feature-xxxxx
  serverless-aws-resource-names:
    source: mapping.json
    variables:
      prefix: ${self:custom.prefix}
  domains:
    prod: api.${self:provider.region}.wayforward.io
    dev: api.${self:provider.region}.dev.wayforward.io
  customDomain:
    basePath: ${self:custom.domain_manager_basemapping.${self:provider.stage}.${self:custom.prefix, 'dev'}, self:custom.domain_manager_basemapping.other}
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRoute53Record: true
  names:
    testClientSecretName: xxxxxxxxxxxxxxxx
  url:
    getFeatures: 'v1'
  settings:
    dev:
      xxxxxxxx: xxxxxxxx
      xxxxxxxxxx: xxxxxxxxxxx
      xxxxxxxxxx: xxxxxxxxxxx
      xxxxxxxxxxx: xxxxx-test.xxxxxxxxx.com
    prod:
      xxxxxxxxx: xxxxxxxxxxx
      xxxxxxxxxx: xxxxxxx
      xxxxxxxxxx: xxxxxxxxx
      xxxxxxxxxx: xxxxxxxxxxxxxxxx
  # serverless-prune-plugin
  prune:
    automatic: true
    number: 3
  serverless-iam-roles-per-function:
    defaultInherit: true

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs10.x
  environment:
    stage: ${self:custom.stage}
  deploymentBucket:
    name: xxxxxxxxxxxxx
  logs:
    restApi: true
    iamrole:  xxxxxxxxxxxxxxxxxxxxxxx


functions:
  auth:
    handler: functions/auth.handler
    cors: true
    provisionedConcurrency: 1
  get-features:
    handler: functions/feature.handler
    timeout: 60
    events:
      - http:
          path: v1
          method: get
          authorizer:
            name: auth
            resultTtlInSeconds: 0
          cors: true
    provisionedConcurrency: 1
        
resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    ApiGatewayLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/apigateway/${self:service}-${self:custom.prefix, self:custom.stage}
  extensions:
    ApiGatewayLogGroup:
      Properties:
        LogGroupName: /aws/apigateway/${self:service}-${self:custom.prefix, self:custom.stage}
```

</details>

<details>
<summary><b><code>sls --stage=dev --prefix=test deploy</code> output</b></summary>

```
An error occurred: ApiGatewayLogGroup - /aws/api-gateway/feature-service-dev already exists.
```

</details>

<b>1.71.3</b>

```
Serverless: Setting custom naming conventions...
Serverless: Setting custom function names...
Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
` OUTPUT
```
