### ISSUE TITLE
Websocket error referring to external stack Api ID

### ISSUE THREAD

**Issue by benheymink** [serverless/serverless#7769]
**Description**
Serverless version 
I have an external Websocket API created by CF:

```
    websocketApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${opt:stage}
        ProtocolType: WEBSOCKET

    websocketApiStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        ApiId: !Ref websocketApi
        StageName: $default
        AutoDeploy: true

    websocketApiCustomDomainMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties:
        ApiId: !Ref websocketApi
        ApiMappingKey: ${opt:stage}
        DomainName: ${self:custom.accountConfig.websocketDomain}
        Stage: !Ref websocketApiStage

  Outputs:
    websocketApiId:
      Value: !Ref websocketApi
```

This is then referenced in another serverless service:

```
provider:
  name: aws
  runtime: ${file(../../../../serverless-properties.yml):custom.default.runtime}
  memorySize: ${file(../../../../serverless-properties.yml):custom.default.memorySize}
  logRetentionInDays: ${self:custom.accountConfig.logRetentionInDays}
  stackTags: ${file(../../../../serverless-properties.yml):custom.stackTags}
  apiGateway:
    websocketApiId: ${file(../../properties.yml):webSocketApi}
  environment: ${file(../../properties.yml):environment}
  deploymentBucket: 
    name: ${file(../../../../serverless-properties.yml):custom.deploymentBucket}

functions:
  resources:
    handler: src/handler.run
    events:
      - websocket: $connect
```

What happens:

Deployment fails template validation with:

` Error: The CloudFormation template is invalid: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.`

If I remove the serverless function events - i.e. remove the following lines from my serverless file:

```
    events:
      - websocket: $connect
```

No error, and the function is deployed as expected (albeit without a binding for the $connect event)

Here is the output from `serverless print` (with the $connect event included, and some sensitive data masked):

```
service: websocket
custom:
  accountConfig:
    pointInTimeRecoveryEnabled: false
    logRetentionInDays: 1
    domain: XXXXXXX
    url: 'http://XXXXXXX'
    apiDomain: XXXXX
    websocketDomain: XXXXXXX
    certificate: >-
      arn:aws:acm:us-east-1:XXXXXXX:certificate/XXXXX-f038-4266-b21f-XXXXX
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  logRetentionInDays: 1
  stackTags:
    owner: XXXXXXX
  apiGateway:
    websocketApiId:
      id: 5xxggbuj0m
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    stage: ben
  deploymentBucket:
    name: XXXXXXXXX-1fnqm5irwjjn0
functions:
  resources:
    handler: src/handler.run
    events:
      - websocket: $connect
    name: websocket-XXXXXX
```

No idea where it's tripping up, can anyone shed some light?
