### ISSUE TITLE
Warning: Accessing non-existent property * of module exports inside circular dependency

### ISSUE THREAD

**Issue by ggmartins** [serverless/serverless#7771]
```
please advise how to fix these warnings. This was working a few months ago and it doesn't show without this yaml. Thanks in advance.

```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: serverless-iotlab

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-s3-local #https://www.npmjs.com/package/serverless-s3-local

provider:
  name: aws
  runtime: nodejs12

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    AUTH0_JWKS_URL: 'https://XXXX.auth0.com/.well-known/jwks.json'
    IOT_TABLE: iot-${self:provider.stage}
    IOT_INDEX: iotIdIndex-${self:provider.stage}
    S3_BUCKET_PCAP: serverless-iotpcap-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IOT_TABLE}
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::${self:provider.environment.S3_BUCKET_PCAP}/*

custom:
  topicName: pcapUploadTopic-${self:provider.stage}
  documentation:
    api:
      info:
        version: v0.0.1
        title: IoT Device Managing and Profiling 
        description: Serverless Application for IoT Device Managing and Profiling

  serverless-offline:
    port: 8001
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 3001
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: iot-${self:provider.stage}
            sources: [./dynamodb-seedtest.json]
  s3:
    port: 3002
    directory: /tmp 
  #models:
    #  - name: TodoRequest
    #    contentType: application/json
    #    schema: ${file(models/TodoItem.json)} # TODO change to 'requests/CreateTodoRequest.ts'
    #  - name: TudoUpdateRequest
    #    contentType: application/json
    #    schema: ${file(models/TodoUpdate.json)}

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

resources:
  Resources:
    #### API Gateway & Request Body Validation #############
    GatewayResponseDefault4XX: #Edge Optimized
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,DELETE,PATCH,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
    #### .pcap File Bucket ############
    BucketPcap:
      Type: AWS::S3::Bucket
      DependsOn: SNSTopicPolicy
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET_PCAP}
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:Put
              Topic: !Ref ImagesTopic
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: BucketPcapPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.S3_BUCKET_PCAP}/*'
        Bucket: !Ref BucketPcap
    IOTTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid #partitionKey
            AttributeType: S
          # https://stackoverflow.com/questions/30866030/number-of-attributes-in-key-schema-must-match-the-number-of-attributes-defined-i
          - AttributeName: createdAt #indexKey
            AttributeType: S
          - AttributeName: lastSeen  #indexKey
            AttributeType: S
        KeySchema:
          - AttributeName: uuid #partitionKey
            KeyType: HASH
          - AttributeName: createdAt #sortKey
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.IOT_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.IOT_INDEX}
            KeySchema:
              - AttributeName: uuid  #partitionKey
                KeyType: HASH
              - AttributeName: lastSeen  #indexKey
                KeyType: RANGE
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index

```

</details>

```

```
<details>
<summary><b><code>SLS_DEBUG=* sls version</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command webpack
Serverless: Load command downloadDocumentation
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command dynamodb
Serverless: Load command dynamodb:migrate
Serverless: Load command dynamodb:seed
Serverless: Load command dynamodb:start
Serverless: Load command dynamodb:noStart
Serverless: Load command dynamodb:remove
Serverless: Load command dynamodb:install
Serverless: Load command s3
Serverless: Load command s3:start
Serverless: Load command s3:create
Serverless: Load command s3:remove
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
(node:84637) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:84637) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:84637) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
```

</details>

sls version
(same as output)

<b>Framework Core: 1.71.3</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
```
