### ISSUE TITLE
Error creating cognito triggers after updating Cognito CloudFormation file

### ISSUE THREAD

**Issue by andre-castro-garcia** [serverless/serverless#7774]
### Use case description
I'm having an issue with Cognito triggers on my environment. I'm deploying the mu Cognito User Pool using two files (one for creating the Cognito User Pool and the other for the triggers, which I deploy using serverless deploy).

<details>
<summary><code>resource.yml</code></summary>

```yaml
Resources:
  CognitoSNSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cognito-idp.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${StageParam}-cognito-sns-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'sns:publish'
                Resource: '*'
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      MfaConfiguration: OPTIONAL
      UserPoolName: !Sub ${StageParam}-cognito-general-user-pool
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
        - SMS_MFA
      SmsConfiguration:
        ExternalId: !Sub ${StageParam}-external
        SnsCallerArn: !GetAtt CognitoSNSRole.Arn
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AWS::AccountId}-${StageParam}-cognito-pool
      UserPoolId:
        Ref: CognitoUserPool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${StageParam}-api-client
      GenerateSecret: False
      ReadAttributes:
        - name
        - family_name
        - email
        - phone_number
      WriteAttributes:
        - name
        - family_name
        - phone_number
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      CallbackURLs:
        - http://localhost:3000
      LogoutURLs:
        - http://localhost:3000/logout
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - openid
        - profile
        - email
        - phone
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId:
        Ref: CognitoUserPool
```

</details>

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  customMessageHandler:
    name: ${self:StageSuffix}-custom-message-handler
    handler: events/custom-message-handler/index.handler
    description: 'Cognito: Custom Message Handler'
    environment: ${self:custom.environment}
    events:
      - cognitoUserPool:
          pool: ${self:StageSuffix}-cognito-general-user-pool
          trigger: CustomMessage
          existing: True
```

</details>

I'm not sure if it is a bug or a feature request, or some mistake from AWS Cloudformation engine.
After some tests I realized what is happening:

1. I deployed the Cognito User Pool using the `resource.yml` file above (works pretty fine);
2. I deployed the triggers using the `serverless.yml` file above (continue works fine);
3. I sent a request to AWS API `aws cognito-idp describe-user-pool <...>` and it returns me a Cognito JSON with LambaConfig node configured with all my triggers;
4. I add a node VerificationMessageTemplate to `resource.yml` and upload again (seems to be work fine);
5. I sent a new request to AWS API `aws cognito-idp describe-user-pool <...>` and it returns me a Cognito JSON with LambaConfig empty (CloudFormation engine 😨 removed all my triggers);
6. I run "serverless deploy" again, and my triggers don't recreated.

Looking for the files generated by "serverless package" command, I noticed that the result file uses a custom resource to attach the trigger to an existing Cognito User Pool. Also I noticed that the custom resource inside a generated Cloudformation file never changes in the next packages, so I guess that CloudFormation does not update the resource (because it is never changed).

```json
{
   "CustomMessageHandlerCustomCognitoUserPool1":{
      "Type":"Custom::CognitoUserPool",
      "Version":1,
      "DependsOn":[
         "CustomMessageHandlerLambdaFunction",
         "CustomDashresourceDashexistingDashcupLambdaFunction"
      ],
      "Properties":{
         "ServiceToken":{
            "Fn::GetAtt":[
               "CustomDashresourceDashexistingDashcupLambdaFunction",
               "Arn"
            ]
         },
         "FunctionName":"dev-custom-message-handler",
         "UserPoolName":"dev-cognito-general-user-pool",
         "UserPoolConfigs":[
            {
               "Trigger":"CustomMessage"
            }
         ]
      }
   }
}
```

In the lambda application (see image below), you can notice the same behaviour, look that the function updates, but the custom resource not, this is the reason why my triggers don't came back.

![Screenshot from 2020-05-21 18-52-18](https://user-images.githubusercontent.com/35741698/82610375-9f66c900-9b94-11ea-9ba6-62192979fdc0.jpg)

### Proposed solution

I was thinking to add some `dummy` key in the CloudFormation template generated by serverless to force an update. Something like this:
https://github.com/andre-castro-garcia/serverless/blob/0c6c019f4e856919e6aacb4fb4284265fd116190/lib/plugins/aws/package/compile/events/cognitoUserPool/index.js#L179

#### Related Issue
https://github.com/serverless/serverless/issues/7405

**Comment by medikoo** [comment]
@andre-castro-garcia this looks closely related to https://github.com/serverless/serverless/issues/7510

From what I see, any attempt to update the Cognito Pool, will remove triggers as setup by the Framework. I think it needs to be clarified with AWS.

Also I wonder weather it happens only in case of Cognito Pools deployed via CloudFormation stack. It might be that when you setup Cognito Pool directly via console or CLI, there might be no such issue.

> I was thinking to add some dummy key in the CloudFormation template generated by serverless to force an update. Something like this:

It looks as imperfect patch, as it doesn't ensure that configured triggers are not removed, it will just ensured that they're put back if they're removed, and we need to deploy for that (right ?)

I'd first put all weight on understanding why AWS behaves like that, and wether it's a specifity of Cognito Pool being deployed via CloudFormation template

**Comment by andre-castro-garcia** [comment]
@medikoo thanks for your reply.....

I suppose that the error should be fixed by AWS, my suggestion is only some kind of trick until the AWS change this behavior when updating the Cognito from cloudformation stack.

Anyway, for fixed this I changed my CI steps and deploys the Cognito in the last step, in this case I can pick the lambda ARN from `serverless deploy` and added to a cognito using `LambdaConfig` property.

My files updated, just for reference:

<details>
<summary><code>resource.yml</code></summary>

```yaml
Resources:
  CognitoSNSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cognito-idp.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${StageParam}-cognito-sns-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'sns:publish'
                Resource: '*'
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      MfaConfiguration: OPTIONAL
      UserPoolName: !Sub ${StageParam}-cognito-general-user-pool
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
        - SMS_MFA
      SmsConfiguration:
        ExternalId: !Sub ${StageParam}-external
        SnsCallerArn: !GetAtt CognitoSNSRole.Arn
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      LambdaConfig:
        CustomMessage:
          Fn::ImportValue: !Sub ${StageParam}-custom-message-handler
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${AWS::AccountId}-${StageParam}-cognito-pool
      UserPoolId:
        Ref: CognitoUserPool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${StageParam}-api-client
      GenerateSecret: False
      ReadAttributes:
        - name
        - family_name
        - email
        - phone_number
      WriteAttributes:
        - name
        - family_name
        - phone_number
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      CallbackURLs:
        - http://localhost:3000
      LogoutURLs:
        - http://localhost:3000/logout
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - openid
        - profile
        - email
        - phone
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId:
        Ref: CognitoUserPool
  CognitoCustomMessageLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName:
        Fn::ImportValue: !Sub ${StageParam}-custom-message-handler
      SourceArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*
```

</details>

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  customMessageHandler:
    name: ${self:StageSuffix}-custom-message-handler
    handler: events/custom-message-handler/index.handler
    description: 'Cognito: Custom Message Handler'
    environment: ${self:custom.environment}
resources:
  # Inside a cloudformation template each function is created as capitalized
  # string with 'LambdaFunction' suffix
  # Example: Lambda function 'customMessageHandler' generates a 'CustomMessageHandlerLambdaFunction' resource
  Outputs:
    CustomMessageHandlerARN:
      Value: !GetAtt CustomMessageHandlerLambdaFunction.Arn
      Export:
        Name: ${self:StageSuffix}-custom-message-handler
```

</details>

Thanks for your help 😄
