### ISSUE TITLE
serverless invoke local for Python on Windows fails

### ISSUE THREAD

**Issue by cbourner** [serverless/serverless#7792]
When I run:

`serverless invoke local --function hello`

I get the following error:

`python: can't open file 'C:\snapshot\serverless\lib\plugins\aws\invokeLocal\invoke.py': [Errno 2] No such file or directory`

I am on Windows 10.  Serverless was installed via chocolatey, not npm.

The Lambda deploys to AWS and runs correctly - the problem is only in invoking it locally.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: python-opentracing

provider:
  name: aws
  runtime: python3.8
  stage: dev
  deploymentBucket: <removed>
  region: ap-southeast-2
  memorySize: 128
  tracing:
    lambda: true
  timeout: 15

functions:
  hello:
    handler: handler.hello
    environment:
      DD_API_KEY: <removed>
      DD_MERGE_XRAY_TRACES: true
      DD_ENV: dev
      DD_SERVICE: opentracing-example
      DD_VERSION: 0.1.2
    tags:
      env: dev
      service: opentracing-example
      datadog: monitor

custom:
  company: <removed>
  pythonRequirements:
    dockerizePip: true
    slim: true
    slimPatterns: "**/*.egg-info*"
    noDeploy:
      - boto3
      - botocore
      - pytest
```

</details>

<details>
<summary><b><code>serverless invoke local --function hello</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command datadog
Serverless: Load command datadog:clean
Serverless: Load command datadog:generate
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: [AWS cloudformation 200 0.29s 0 retries] describeStacks({ StackName: 'erm-base-infra' })
Serverless: Invoke invoke:local
Serverless: Auto instrumenting functions with Datadog
Serverless: Adding Lambda Layers to functions
python: can't open file 'C:\snapsh
ot\serverless\lib\plugins\aws\invokeLocal\invoke.py': [Errno 2] No such file or directory

Serverless: Cleaning up Datadog Handlers
```

</details>

<b>Installed version</b>

```
Framework Core: 1.71.3 (standalone)
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
```
