### ISSUE TITLE
Can't deploy to new region af-south-1

### ISSUE THREAD

**Issue by hyacinthus** [serverless/serverless#7796]
I can deploy to default opened regions but can't deploy to af-south-1 .
I've enabled that region, and can create resource in Africa region manually.

I've recreate a profile in pro dashboard named `prod` after enabled that region. not work.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: lottodata
app: lottoserver
service: resource

custom:
  table: Lottery-${self:provider.stage}
  bucketLottery: lottery-${self:provider.region}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  profile: ${opt:stage, 'dev'}
  # deploymentBucket: serverless-deployment-${self:provider.region}

resources:
  Resources:
    Lottery:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: Data
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: GSI-1
            KeySchema:
              - AttributeName: SK
                KeyType: HASH
              - AttributeName: Data
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
    S3BucketLottery:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketLottery}

```

</details>

<details>
<summary><b><code>sls deploy --stage prod --region af-south-1 --aws-profile prod</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
platform-sdk fetching: POST https://api.serverless.com/core/tenants/lottodata/applications/lottoserver/profileValue
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
platform-sdk fetching: GET https://api.serverless.com/core/tenants/lottodata/applications/lottoserver
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 403 2.712s 0 retries] describeStacks({ StackName: 'resource-prod' })
Serverless: Publishing service to the Serverless Dashboard...
Serverless: [AWS sts 200 1.807s 0 retries] getCallerIdentity({})
Serverless: [AWS cloudformation 403 1.715s 0 retries] describeStacks({ StackName: 'resource-prod' })
ServerlessError: The security token included in the request is invalid
    at C:\Users\hyaci\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:331:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Serverless Error ---------------------------------------

  ServerlessError: The security token included in the request is invalid
      at C:\Users\hyaci\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\provider\awsProvider.js:331:27
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              13.12.0
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.0
     Components Version:        2.30.11
```

</details>

<b>Installed version</b>

```
Framework Core: 1.71.3
Plugin: 3.6.12
SDK: 2.3.0
Components: 2.30.11
```
