### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by brentpabst** [serverless/serverless#7797]
When running any serverless command in my project I get the error in the subject of this issue.  Previous issue was opened and then closed as the original reporter didn't fill out the issue report.  I've posted the output while leveraging the serverless-offline plugin, however even just trying to load serverless --version results in the same error.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: my-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-stage-manager

provider:
  name: aws
  runtime: go1.x
  stage:
    - local
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true
  apiGateway:
    minimumCompressionSize: 0
  environment:
    DATABASE_HOST: ${self:custom.environment.DATABASE_HOST.${self:provider.stage}}
    DATABASE_NAME: ${self:custom.environment.DATABASE_NAME.${self:provider.stage}}
    DATABASE_USER: ${self:custom.environment.DATABASE_USER.${self:provider.stage}}
    DATABASE_PASSWORD: ${self:custom.environment.DATABASE_PASSWORD.${self:provider.stage}}

custom:
  stages:
    - local
  environment:
    DATABASE_HOST:
      local: host.docker.internal
    DATABASE_NAME:
      local: my-db
    DATABASE_USER:
      local: postgres
    DATABASE_PASSWORD:
      local: localdev

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  root:
    handler: bin/root
    events:
      - http:
          path: /
          method: get
          cors: true
  create-accounts:
    handler: bin/create-accounts
    events:
      - http:
          path: accounts
          method: post
          cors: true
```

</details>

<details>
<summary><b><code>REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'trim' of undefined
      at Variables.splitByComma (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:484:26)
      at Variables.splitAndGet (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:438:24)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:379:41
      at arrayMap (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
      at Function.map (/usr/local/lib/node_modules/serverless/node_modules/lodash/lodash.js:9554:14)
      at Variables.populateMatches (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:379:14)
      at Variables.populateValue (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:410:30)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:176:16
      at Array.map (<anonymous>)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:175:48
      at Variables.disableDepedentServices (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:133:12)
      at Variables.prepopulateService (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:174:19)
      at /usr/local/lib/node_modules/serverless/lib/classes/Variables.js:203:12
      at Variables.initialCall (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:108:12)
      at Variables.populateService (/usr/local/lib/node_modules/serverless/lib/classes/Variables.js:202:17)
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:120:27)
      at /usr/local/lib/node_modules/serverless/bin/serverless.js:80:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:80:4)
      at Module._compile (internal/modules/cjs/loader.js:1200:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
      at Module.load (internal/modules/cjs/loader.js:1049:32)
      at Function.Module._load (internal/modules/cjs/loader.js:937:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.3.0
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.1
     Components Version:        2.30.12
 
 
 Serverless Information ----------------------------------
 
  ############################################################################################
    # 2501: 0 of 0 promises have settled
    # 2501: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
 
 
 Serverless Information ----------------------------------
 
  ############################################################################################
    # 5005: 0 of 0 promises have settled
    # 5005: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
 
 
 Serverless Information ----------------------------------
 
  ############################################################################################
    # 7511: 0 of 0 promises have settled
    # 7511: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
```

</details>

<b>Installed version</b>

```
     Operating System:          darwin
     Node Version:              14.3.0
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.1
     Components Version:        2.30.12
```

**Comment by brentpabst** [comment]
I think I fixed this issue.  Specifically, I corrupted my serverless.yml file here:

```yaml
provider:
  stage:
    - local
```

Which is incorrect and should have simply been this:
```yaml
provider:
  stage: local
```

Almost wish there was a serverless.yml validation routine that executes as it would have called out my stupidity much sooner ;)
