### ISSUE TITLE
Can't deploy because an error `Could not locate deployment bucket. Error: Deployment bucket is not in the same region as the lambda function`

### ISSUE THREAD

**Issue by zhaoyi0113** [serverless/serverless#7800]
I am using latest version of serverless and `localstack/localstack` docker image. I started the localstack docker image by running the command: `localstack start --docker`. 
Then I created a s3 bucket manually by running the command `aws s3api create-bucket --bucket dbs --region ap-southeast-2 --endpoint http://localhost:4572`.

When I deploy `serverless deploy --stage local`, I got below error:

```
Serverless Error ---------------------------------------
 
  Could not locate deployment bucket. Error: Deployment bucket is not in the same region as the lambda function
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.2
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.0
     Components Version:        Unavailable
```

Below is my `serverless` yml file:

```
service:
  name: ${opt:componentName}-api

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - "serverless-localstack"

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost # optional - LocalStack host to connect to
    autostart: true  # optional - start LocalStack in Docker on Serverless deploy
    endpoints:
      # This section is optional - can be used for customizing the target endpoints
      S3: http://localhost:4572
      DynamoDB: http://localhost:4569
      CloudFormation: http://localhost:4581
      ES: http://localhost:4578
      Lambda: http://localhost:4574
    lambda:
      # Enable this flag to improve performance
      mountCode: False
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: False

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  websocketApiRouteSelectionExpression: $request.body.action
  deploymentBucket:
    name: dbs

```

Why does it say the bucket is not in the same region? I have specified the region as ap-southeast-2.
