### ISSUE TITLE
AWS Kinesis Event Source not attaching with right provisioned Concurrency Lambda Alias

### ISSUE THREAD

**Issue by xharsin** [serverless/serverless#7802]
I have a use-case to use Kinesis Stream as a trigger for Lambda function with Provisioned Concurrency. According to the Documentation the Event should be attached to the automatically created alias `provisioned` , but it is always attaching to the `Latest` Default version of Lambda. 

So the Lambda version Provisioned with Provisioned concurrency is not triggering as the event is added to `LATEST` and version with Concurrency is being utilised. 

Ideal case: 

Kinesis Trigger should be attached to the Lambda with Provisioned Concurrency.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  function:
    name: kinesis-test-function
    handler: src.enricher_handler.handler
    provisionedConcurrency: 200
    timeout: 360
    memorySize: 128
    events:
      - stream:
          arn: arn:aws:kinesis:eu-west-1:xxxxxxxxx:stream/test-stream
          startingPosition: LATEST
          batchSize: 5
          parallelizationFactor: 10
          bisectBatchOnFunctionError: true
          maximumRetryAttempts: 50
```

</details>

</details>

<b>Installed version</b>

```
Framework Core: 1.67.3
Plugin: 3.6.6
SDK: 2.3.0
```
