### ISSUE TITLE
Cannot use equalto `=` in env value for sls invoke local

### ISSUE THREAD

**Issue by sappusaketh** [serverless/serverless#7819]
**Q1: Describe the issue**
I have equal to `=` in  an env var value and my local invoke is not working as expected because when sls is parsing the env var values it is splitting based on `=` symbol which is causing an error in my lambda because of incomplete string being parsed

**Q2: Provide (in below placeholder) output of serverless --version**
<b>Installed version</b>
```
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.12
```

**Q3: Provide (in below placeholder) FULL content of serverless.yml**
<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: function-with-environment-variables

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: handler.app
    environment:
      FOO: ${ssm:/app/foo}
```
</details>

<details>
<summary><code>handler.js</code></summary>

```javascript

'use strict';

module.exports.app = (event, context, callback) => {
  // logs `B` 
 // expetced `B=AR`
  console.log('FOO: ', process.env.FOO);
  
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: 'User created',
    }),
  };

  callback(null, response);
};
```
</details>

looks like env vars are split using `=`
https://github.com/serverless/serverless/blob/e39cdfdf02adba8b83f4bbf83208fdf81e32c1d7/lib/plugins/invoke/invoke.js#L128-L129

```shell
sls invoke local -f app    -e FOO="B=AR"
```
