### ISSUE TITLE
Attach latest lambda layer version

### ISSUE THREAD

**Issue by adriantomas** [serverless/serverless#7828]
### Use case description

I want the Lambdas I deploy to use the latest layer version available.

### Proposed solution

Actually we are using:
```
myLambda:
    handler: lambda.handler
    layers:
      - arn:aws:lambda:<Region>:<AccountId>:layer:<LayerName>:<LayerVersion>
```
Probably would need to change to Array of Objects:
```
myLambda:
    handler: lambda.handler
    layers:
      - arn:aws:lambda:<Region>:<AccountId>:layer:<LayerName>:<LayerVersion> # Default behaviour
      - name: <LayerName> # Req
        version: <LayerVersion> # Opt
        latest: true | false # Opt 
```

The way to discover the latest version is through:
```
aws lambda list-layer-versions --layer-name <LayerName> --region <Region> --query 'LayerVersions[0].LayerVersionArn'
```

If you provide me some details I can try to create a PR with this change.
