### ISSUE TITLE
DisableLogs Does Not Disable the Creation of Log Groups

### ISSUE THREAD

**Issue by mburolla** [serverless/serverless#7846]
It's my understanding that Serverless creates a Log Group for Lambda functions, and adding `disableLogs: true` to the YML disables the creation of these Log Groups.  When I deploy my Serverless project with `disableLogs: true` and examine the CloudFormation template, I still see the log group that Serverless creates.

I am not able to create my own custom log group and attach a Lambda function to it.  The `dependsOn` array in the CloudFormation template contains the log group Serverless created and my own custom log group, and I believe that a Lambda function cannot log to two log groups at the same time and I think this is the reason why my Log Group is not collecting any logs.

Here is my YML file:

```
service: util-access-test-reachability-4

provider:
  name: aws
  stackName: util-access-test-reachability-4
  stage: dev
  region: us-east-2
  runtime: nodejs12.x
  timeout: 5
  memorySize: 256
  disableLogs: true

  vpc:
    securityGroupIds:
      - xxx
    subnetIds:
      - xxx
      - xxx
      - xxx

package:
  include:
    - ./node_modules/**  
functions:
 
  accessTest:
    name: access-test-reachability-4
    role: arn:aws:iam::xxx:role/access-test-role
    handler: handler.accessTest
    dependsOn:
       - AccessTestLogGroup4

resources:
  Resources:
    AccessTestLogGroup4:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /my_log_group
```

CloudFormation template snippet:
```
   "AccessTestLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "xxx"
        },
        "FunctionName": "access-test-reachability-4",
        "Handler": "handler.accessTest",
        "MemorySize": 256,
        "Role": "arn:aws:iam::xxx:role/access-test-role",
        "Runtime": "nodejs12.x",
        "Timeout": 5,
        "VpcConfig": {
          "SecurityGroupIds": [
            "xxx"
          ],
          "SubnetIds": [
            "xxx",
            "xxx",
            "xxx"
          ]
        }
      },
      "DependsOn": [
        "AccessTestLogGroup",  <============= WHY IS THIS HERE?
        "AccessTestLogGroup4"
      ]
    }
```
I'm using Serverless 1.73.1
