### ISSUE TITLE
Cannot use a variable name in provider and runtime fields in serverless.yml

### ISSUE THREAD

**Issue by bhorkarg** [serverless/serverless#7847]
When we use a variable reference in the provider and runtime fields in serverless.yml, the sls deploy command exits after the "Packaging service" phase without giving errors. However the service is not deployed. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myservice

custom: 
  slsCommon: ${file(../../serverless/serverless.common.yml)}

provider:
  name: ${self:custom.slsCommon.provider.name}
  runtime: ${self:custom.slsCommon.provider.runtime}
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    ApiGw:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MyAPI

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: ApiGw
      Export:
        Name: myservice-${self:provider.stage}-ApiGw-restApiId

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGw
          - RootResourceId
      Export:
        Name: myservice-${self:provider.stage}-ApiGw-rootResourceId
```
</details>
<details>
<summary><code>serverless.common.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: python3.8
```
</details>

<details>
<summary><b><code>SLS_DEBUG=\* serverless deploy --verbose -r eu-north-1</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
```

</details>

<b>Installed version</b>

```
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.15
```
