### ISSUE TITLE
Support for EFS in lambda function configuration

### ISSUE THREAD

**Issue by eldos-dl** [serverless/serverless#7848]
### Use case description
AWS has recently announced support for EFS in Lambda functions.
https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/

Using them would help in different use cases as described in the blog. It would be great if we could configure the same in serverless.yaml

**Comment by medikoo** [comment]
@eldos-dl great thanks for opening this! We definitely should support it. Still before patching a PR we should agree on some implementation spec (at least how it should look on configuration level).

We welcome any feedback

**Comment by kziemski** [comment]
its already in cloudformation   

AWS::Lambda::Function Properties FileSystemConfigs

FileSystemConfig
Arn: String
LocalMountPath: String

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-filesystemconfigs

**Comment by jefftougas** [comment]
> It would be great if we could configure the same in serverless.yaml

I agree it'd be nice to have efs mount support built in to the main `functions` config section. Fyi though, this is already technically possible using the [resources.extensions](https://www.serverless.com/framework/docs/providers/aws/guide/resources#override-aws-cloudformation-resource). I've included a simplified serverless.yml based on my working code below, in case it helps anyone else who for whom the resource extension capability is unfamiliar.

Something like this should work (assuming a preexisting efs and access point, and a real account number):

```markdown
functions:
  write-post:
    handler: handler.writePost

resources:
  extensions:
    WriteDashPostLambdaFunction:
      Properties:
        FileSystemConfigs:
          - Arn: arn:aws:elasticfilesystem:us-east-1:111111111111:access-point/fsap-abc123xyz45glhfjk
            LocalMountPath: /mnt/bigLibs

```

A more comprehensive serverless.yml might go a step further and create the efs resources too; then each `FileSystemConfig['Arn']` could do a lookup of the resulting efs access point arn rather than hardcode it.

**Comment by lsb** [comment]
At the very least, I would appreciate a boolean flag that uploads the files to EFS instead of Lambda's default storage. Much like in Python, for example, `custom.pythonRequirements.zip: true` zips the contents (and trades slower initial startup for larger code size).

Supporting the use case of mounting an arbitrary file system is a nice to have, but supporting the core use case of "here is my app with its files and the bundle is enormous and I would like to prune nothing please" is my first ask. The rest of the Serverless experience is so seamless to start with that that is what I would expect.

(perhaps the default should be EFS? using the default Lambda storage is a nice cost-saving measure but for deploying (for instance) pytorch and fastai the zipped bundle maxes out the file system and the non-zipped bundle is >250MB)

**Comment by leecheeaun** [comment]
Perhaps add the option to use EFS under `functions`?

```
functions:
  func_one:
    handler: func_one.hello
    efs:
      - arn:aws:elasticfilesystem:us-east-1:111111111111:access-point/fsap-abc123xyz45glhfjk
      - LocalMountPath: /mnt/bigLibs
```

**Comment by medikoo** [comment]
@leecheeaun that's good suggestion, still I'd probably stick closer to how it's done in CloudFormation, so:

```yaml
functions:
  function:
    handler: function.handler
    fileSystemConfigs:
      - arn: aws:elasticfilesystem:us-east-1:111111111111:access-point/first
        localMountPath: /mnt/first
      - arn: aws:elasticfilesystem:us-east-1:111111111111:access-point/second
        localMountPath: /mnt/second
```

And implementation should probably be handled somewhere [here](https://github.com/serverless/serverless/blob/0e56be3f67eda929a2c73036f79e8d8724b456d0/lib/plugins/aws/package/compile/functions/index.js#L420) in similar fashion as its done for other functionalities

PR is very welcome!!

**Comment by pgrzesik** [comment]
Hello :wave: If no one else is interested, I would like to give it a try over the weekend

**Comment by jesseproudman** [comment]
@jefftougas Thanks for the tip. Using that sample YAML with our EFS config, I'm getting the following validation error:

```
  Error: The CloudFormation template is invalid: Template format error: [/Resources/WriteDashPostLambdaFunction] Every Resources object must contain a Type member.
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
```

Any ideas on how to resolve that one?

**Comment by medikoo** [comment]
@pgrzesik Your help will be much appreciated. Go for it!

**Comment by pgrzesik** [comment]
Hello team :wave: I gave it a spin and I wanted to validate if the chosen path is the correct one - the proposal is available as a part of this PR: https://github.com/serverless/serverless/pull/8042

Questions that I have so far:
1. Is this the proper place for the implementation of this functionality? Following @medikoo suggestion I would assume the answer is yes, but I wanted to double check
2. Do we want to stick to `fileSystemConfigs` configuration, resembling the CloudFormation parameters even though at most 1 `fileSystemConfig` is supported as of right now? It's a bit confusing at the moment, but we're constrained by AWS here
3. Should we validate that function has VPC configured as a part of framework logic or should we just rely on CF output for that type of errors?
4. In the proposal, there's only basic support for EFS as all EFS-related resources have to already exist. Should we consider a bit more advanced support that would create EFS filesystem + access point in a similar way to e.g. creating S3 buckets on SNS topics? 

Any feedback would be more than welcome :raised_hands: 

After resolving the above, the next steps for me are to clean-up the codebase, extend the functionality (if needed), add unit & integration tests + documentation.

Thanks in advance :bow:

**Comment by NoelBaron** [comment]
> > It would be great if we could configure the same in serverless.yaml

> A more comprehensive serverless.yml might go a step further and create the efs resources too; then each `FileSystemConfig['Arn']` could do a lookup of the resulting efs access point arn rather than hardcode it.

Thanks @jefftougas. I accomplished the lookup by referencing the `AccessPoint` Arn. When doing this, you must implement `DependsOn` to ensure `MountTarget` availability.

```
    MyAccessPoint:
      [Truncated]
      DependsOn: MyMountTarget

  extensions:
    MyLambdaFunction:
      Properties:
        FileSystemConfigs:
          - Arn: !GetAtt MyAccessPoint.Arn
            LocalMountPath: /mnt/home
      DependsOn: MyFileSystem
```
