### ISSUE TITLE
Log retention not properly set

### ISSUE THREAD

**Issue by vavarodrigues** [serverless/serverless#7852]
I'm using plugin `serverless-plugin-log-retention` and don't work, it no set `"RetentionInDays"`

code snippet cloudformation

```
"HelloLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/test-log-retention-plugin-dev-hello"
      }
    }
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test-log-retention-plugin

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - './**'

provider:
  name: aws
  profile: dev
  state: dev
  runtime: python3.7

custom:
  logRetentionInDays: 1

plugins:
  - serverless-plugin-log-retention
functions:
  hello:
    handler: handler.lambda_handler
    package:
      include:
        - handler.py
```

</details>

<details>
<summary><b><code>REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.728s 0 retries] describeStacks({ StackName: 'test-log-retention-plugin-dev' })
Serverless: [AWS cloudformation 200 0.742s 0 retries] describeStackResource({
  StackName: 'test-log-retention-plugin-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.737s 0 retries] listObjectsV2({
  Bucket: 'test-log-retention-plugi-serverlessdeploymentbuck-1f3tqdk800hc2',
  Prefix: 'serverless/test-log-retention-plugin/dev'
})
Serverless: [AWS s3 200 0.668s 0 retries] headObject({
  Bucket: 'test-log-retention-plugi-serverlessdeploymentbuck-1f3tqdk800hc2',
  Key: 'serverless/test-log-retention-plugin/dev/1592503456145-2020-06-18T18:04:16.145Z/hello.zip'
})
Serverless: [AWS s3 200 0.666s 0 retries] headObject({
  Bucket: 'test-log-retention-plugi-serverlessdeploymentbuck-1f3tqdk800hc2',
  Key: 'serverless/test-log-retention-plugin/dev/1592503456145-2020-06-18T18:04:16.145Z/compiled-cloudformation-template.json'
})
Serverless: [AWS lambda 200 0.702s 0 retries] getFunction({ FunctionName: 'test-log-retention-plugin-dev-hello' })
Serverless: Service files not changed. Skipping deployment...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 200 0.682s 0 retries] describeStacks({ StackName: 'test-log-retention-plugin-dev' })
Serverless: [AWS cloudformation 200 0.671s 0 retries] listStackResources({ StackName: 'test-log-retention-plugin-dev', NextToken: undefined })
Service Information
service: test-log-retention-plugin
stage: dev
region: us-east-1
stack: test-log-retention-plugin-dev
resources: 6
api keys:
  None
endpoints:
  None
functions:
  hello: test-log-retention-plugin-dev-hello
layers:
  None

Stack Outputs
HelloLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:11111111111:function:test-log-retention-plugin-dev-hello:1
ServerlessDeploymentBucketName: test-log-retention-plugi-serverlessdeploymentbuck-1f3tqdk800hc2

Serverless: Invoke aws:deploy:finalize
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
```

</details>

<b>Installed version</b>

```
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.15
```
