### ISSUE TITLE
AWS API Gateway HTTP API logRetentionInDays not taken into account

### ISSUE THREAD

**Issue by jonnedeprez** [serverless/serverless#7855]
- What happens:
Log retentions days not set for CloudWatch log group for httpApi.
- What did you expect should have happened?
Log retension days should be set like for rest and websockets

It is basically the same issue as #6657, but for HTTP API.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: nodejs12.x
  logs:
    httpApi: true
  logRetentionInDays: 14
```
</details>

<b>Installed version</b>

```
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.16
```
