### ISSUE TITLE
Lambda trigger doesn't work for existing s3 bucket event

### ISSUE THREAD

**Issue by boriskurikhin** [serverless/serverless#7859]
I'm running Serverless `1.72.0`. My function gets deployed fine, however, it does not invoke upon the s3 event indicated in `serverless.yml`. After further inspection, it seems as if the trigger does not get added at all (not visible in Designer). When I try to manually add it, I get the following error: `Configurations overlap. Configurations on the same bucket cannot share a common event type.`. The objects are being added to the s3 bucket via a POST request.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: klassroom-api

app: klassroomio
org: klassroom

# this works fine
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetBucketNotification"
        - "s3:PutBucketNotification"
      Resource:
        - "arn:aws:s3:::klassroom-files/*"
functions:
  confirmFileTrigger:
    handler: src/confirmFile.handler
    events:
      - s3:
        bucket: klassroom-files
        event: s3:ObjectCreated:*
        existing: true
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - *****
Serverless:      - *****
Serverless:      - *****
Serverless:      - *****
Serverless:      - *****
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Safeguards Processing...
Serverless: Safeguards Results:

   Summary --------------------------------------------------

   passed - framework-version
   warned - require-cfn-role
   passed - allowed-stages
   passed - allowed-runtimes
   passed - no-secret-env-vars
   passed - allowed-regions
   passed - no-unsafe-wildcard-iam-permissions

   Details --------------------------------------------------

   1) Warned - no cfnRole set
      details: http://slss.io/sg-require-cfn-role
      Require the cfnRole option, which specifies a particular role for CloudFormation to assume while deploying.


Serverless: Safeguards Summary: 6 passed, 1 warnings, 0 errors
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service klassroom-api.zip file to S3 (23.04 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......................................................................................................................................
Serverless: Stack update finished...
Service Information
service: klassroom-api
stage: dev
region: us-east-1
stack: klassroom-api-dev
resources: 8
api keys:
  None
endpoints:
  None
functions:
  confirmFileTrigger: klassroom-api-dev-confirmFileTrigger
layers:
  None
Serverless: Removing old service artifacts from S3...
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: https://dashboard.serverless.com/tenants/klassroom/applications/klassroomio/services/klassroom-api/stage/dev/region/us-east-1
```

</details>

![Screen Shot 2020-06-22 at 1 33 53 AM](https://user-images.githubusercontent.com/29171967/85252848-d564ca80-b42a-11ea-9974-4685f576b154.png)
![Screen Shot 2020-06-22 at 1 34 58 AM](https://user-images.githubusercontent.com/29171967/85252850-d5fd6100-b42a-11ea-8f9f-e9082adeffe8.png)

<b>Installed version</b>

```
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.13
```

**Comment by exoego** [comment]
Each event properties should have more indent than event name, e.g.:

```
    - s3:
         bucket: klassroom-files
         event: s3:ObjectCreated:*
         existing: true
```

This is very common mistake and annoying since no warning.
Enhancement is proposed in #5916.
