### ISSUE TITLE
Support creating dynamodb global table

### ISSUE THREAD

**Issue by zhaoyi0113** [serverless/serverless#7865]
I'd like to deploy global table for my dynamodb table. I have read through this blog: https://www.serverless.com/blog/build-multiregion-multimaster-application-dynamodb-global-tables/ but it doesn't support deploy global table via serverless configuration file. I have to run a separate script for that which is not automatic. 

### Use case description

⚠️⚠️ REPLACE WITH DESCRIPTION

### Proposed solution

```
Resources:
  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.deviceTableName}
      Regions:
         - ap-southeast-1
         - xxx
```
⚠️⚠️ REPLACE WITH PROPOSAL
