### ISSUE TITLE
Not able to invoke Kotlin functions locally

### ISSUE THREAD

**Issue by ninadingole** [serverless/serverless#7866]
Created serverless service using template `aws-kotlin-jvm-gradle` then inside the directory did `./gradlew build` and tried `sls invoke local -f "hello"`, and getting following error:
```
Error: ENOENT: no such file or directory, open '/Users/neenad/aws-kotlin-jvm-gradle/.serverless/invokeLocal/artifact/kotlin/'
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: aws-kotlin-jvm-gradle

provider:
  name: aws
  runtime: java11


package:
  artifact: build/libs/hello-dev-all.jar

functions:
  hello:
    handler: com.serverless.Handler

```

</details>

<details>
<summary><b><code>sls invoke local -f "hello" OR sls invoke local --docker -f "hello"</code> output</b></summary>

```
Serverless: Packaging service...

  Error --------------------------------------------------

  Error: ENOENT: no such file or directory, open '/Users/neenad/aws-kotlin-jvm-gradle/.serverless/invokeLocal/artifact/kotlin/'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         1.73.1
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.31.1
```

</details>

<b>Installed version</b>

```
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.31.1
```
