### ISSUE TITLE
Custom variable resolution happens before properties it depends on are resolved

### ISSUE THREAD

**Issue by williamsandonz** [serverless/serverless#7867]
When my local plugin's variable resolver method is called, upon accessing variables defined in this.serverless.service , any values with ${self:foo} are not interpolated making them unusable. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
app: my-app
service: my-service
plugins:
  - my-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:app}-${self:provider.stage}-${self:service}
  stage: dev
functions:
  hello:
    handler: handler.hello
resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${foo:bar}
```
</details>

And if you create a local plugin at .serverless_plugins / my-plugin

<details>
<summary><code>Plugin</code></summary>

```javascript
'use strict';

class MyPlugin {
  constructor(serverless, options) {
    this.serverless = serverless;
    this.options = options;
    this.variableResolvers = {
      foo: {
        isDisabledAtPrepopulation: true,
        resolver: (path) => {
          console.log(this.serverless.service.provider.stackName);
        },
        serviceName: 'Not prepopulated...',
      }
    };
  }
}
module.exports = MyPlugin;
```
</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
${self:app}-${self:provider.stage}-${self:service}
```
But expected 

```
my-app-dev-my-service
```
</details>

<b>Installed version</b>

```
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.31.2
```
This is a problem in my situation because my variable resolution requires using aws-sdk to call describe-stacks which requires accessing this.serverless.service.provider.stackName and  it's quite common for this to be defined with ${self:app}-${self:provider.stage}-${self:service}.
