### ISSUE TITLE
Serverless Error - iamRoleStatements should be an array of objects, where each object has Effect, Action / NotAction, Resource / NotResource fields

### ISSUE THREAD

**Issue by jsposato** [serverless/serverless#7869]
<details>
<summary><code>serverless.yml</code></summary>
The piece of my serverless.yml where I am trying to import IAM statements from another file:

```yaml
  iamRoleStatements:
    - ${file(../../serverless.common.yml):serverlessDeploymentBucketPolicy}
    - ${file(../../serverless.common.yml):lambdaDataLakeBucketPolicy}
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "arn:aws:sqs:*:nnnnnnnnnn:*"
```
A policy in the serverless.common.yml file in the root of the repository:
```yaml
lambdaPolicyXRay:
  - Effect: "Allow"
    Action:
      - "xray:PutTraceSegments"
      - "xray:PutTelemetryRecords"
    Resource: "*"
```

</details>

<details>
<summary><b><code>sls info</code> output</b></summary>

```
  Serverless Error ---------------------------------------
  iamRoleStatements should be an array of objects, where each object has Effect, Action / NotAction, Resource / NotResource fields. Specifically, statement 0 is missing the following properties: Effect, Action / NotAction, Resource / NotResource; statement 1 is missing the following properties: Effect, Action / NotAction, Resource / NotResource; statement 2 is missing the following properties: Effect, Action / NotAction, Resource / NotResource
```

</details>

<b>1.73.1</b>

```
 sls --version
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.20
```

**Comment by medikoo** [comment]
@jsposato for general support please use https://forum.serverless.com/ or https://www.serverless.com/slack

**Comment by jsposato** [comment]
this wasn't a support request, I was trying to report a possible bug.  I forgot to put in my issue that when you follow what I have above, the `sls print` outputs the statements with double `-` which causes the error.  The only workaround I could find was for each of the policies I'm importing to have only one Effect,Action,Resource statement.

**Comment by medikoo** [comment]
@jsposato From what I see, Framework behaves properly. Note that what lands in `iamRoleStatements`, by your configuration is array of arrays and not array of objects. Error message is pretty descriptive.

**Comment by luisdemarchi** [comment]
@jsposato 

serverless.yml
```
  iamRoleStatements:
    - ${file(../../serverless.common.yml):serverlessDeploymentBucketPolicy}
    - ${file(../../serverless.common.yml):lambdaDataLakeBucketPolicy}
    - ${file(../../serverless.common.yml):lambdaPolicyXRay}
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "arn:aws:sqs:*:nnnnnnnnnn:*"
```

common

```
lambdaPolicyXRay:
    Effect: "Allow"
    Action:
      - "xray:PutTraceSegments"
      - "xray:PutTelemetryRecords"
    Resource: "*"
```
