### ISSUE TITLE
Lambda layer not attaching to function when use arn

### ISSUE THREAD

**Issue by feeh27** [serverless/serverless#7876]
I haven’t been able to attach the layer to the Lambda Function.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: product-types

frameworkVersion: '>=1.34.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'sa-east-1'}
  stage: ${opt:stage, 'DEV'}
  layers:
    - arn:aws:lambda:${self:provider.region}:************:layer:Elasticsearch-NodeJS-${self:provider.stage}:1

package:
  exclude:
    - ./**
  include:
    - src/**

functions:
  getAll:
    name: ProductTypes-GetAll-${self:provider.stage}
    handler: src/handlers.getAll
    runtime: ${self:provider.runtime}
    events:
      - http:
          method: get
          path: product-types
          cors: true
    layers: ${self:provider.layers}

  getByCode:
    name: ProductTypes-GetByCode-${self:provider.stage}
    handler: src/handlers.getByCode
    runtime: ${self:provider.runtime}
    events:
      - http:
          method: get
          path: product-types/{code}
          cors: true
    layers: ${self:provider.layers}

```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service product-types.zip file to S3 (2.76 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....................
Serverless: Stack update finished...
Service Information
service: product-types
stage: DEV
region: sa-east-1
stack: product-types-DEV
resources: 19
api keys:
  None
endpoints:
  GET - https://XXXXXXXX.execute-api.sa-east-1.amazonaws.com/DEV/product-types
  GET - https://XXXXXXXX.execute-api.sa-east-1.amazonaws.com/DEV/product-types/{code}
functions:
  getAll: ProductTypes-GetAll-DEV
  getByCode: ProductTypes-GetByCode-DEV
layers:
  None
Serverless: Removing old service artifacts from S3...
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.

```

</details>

<b>Installed version</b>

```
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.31.3
```

**Node version:** 12.16.1

**Comment by medikoo** [comment]
@feeh27 Use root `custom` instead of `provider` namespace for reusable layer configuration.

I believe it doesn't work, as `layers` is not recognized as `provider` property and is silently discarded (error reporting on that will be fixed with https://github.com/serverless/serverless/issues/6562 which is around the corner)

**Comment by feeh27** [comment]
@medikoo I already used these settings directly on the layers object and the result is still the same, I only managed to use the layers when they are declared in the same file.

**Comment by feeh27** [comment]
@medikoo I already used these settings directly on the layers object and the result is still the same, I only managed to use the layers when they are declared in the same file.

I believe the problem is linked to the use of ARN.

This file below has the standard use of the template and still does not work:

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: product-types

frameworkVersion: '>=1.34.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'sa-east-1'}
  stage: ${opt:stage, 'DEV'}

package:
  exclude:
    - ./**
  include:
    - src/**

functions:
  getAll:
    name: ProductTypes-GetAll-${self:provider.stage}
    handler: src/handlers.getAll
    runtime: ${self:provider.runtime}
    events:
      - http:
          method: get
          path: product-types
          cors: true
    layers:
      - arn:aws:lambda:${self:provider.region}:************:layer:Elasticsearch-NodeJS-${self:provider.stage}:1
  getByCode:
    name: ProductTypes-GetByCode-${self:provider.stage}
    handler: src/handlers.getByCode
    runtime: ${self:provider.runtime}
    events:
      - http:
          method: get
          path: product-types/{code}
          cors: true
    layers:
      - arn:aws:lambda:${self:provider.region}:************:layer:Elasticsearch-NodeJS-${self:provider.stage}:1

```

</details>

**Comment by medikoo** [comment]
> @medikoo I already used these settings directly on the layers object

`layers` is dedicated for constructing layers and not for referencing an existing ones.

**Comment by feeh27** [comment]
> > @medikoo I already used these settings directly on the layers object
> 
> `layers` is dedicated for constructing layers and not for referencing an existing ones.

@medikoo, sorry, that's not what I meant, I used it directly in the layers attribute of the functions object, has the example of serverless.yml in the comment above.

**Comment by medikoo** [comment]
> I haven’t been able to attach the layer to the Lambda Function.

Why do you assume that layers are not attached to lambda function?

**Comment by feeh27** [comment]
> > I haven’t been able to attach the layer to the Lambda Function.
> 
> Why do you assume that layers are not attached to lambda function?

Because my code is not working due to dependencies that are found in the layers and I was able to implement it when the layer is built in the same file.

**Comment by feeh27** [comment]
> > I haven’t been able to attach the layer to the Lambda Function.
> 
> Why do you assume that layers are not attached to lambda function?

Because my code is not working due to dependencies that are found in the layers and I was able to implement it when the layer is built in the same file.

Below my layer configuration:
<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: elasticsearch-layer

frameworkVersion: '>=1.34.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'sa-east-1'}
  stage: ${opt:stage, 'DEV'}
  environment:
    NODE_PATH: "./:/opt/node_modules"

# layers
layers:
  elasticsearch-nodejs:
    name: Elasticsearch-NodeJS-${self:provider.stage}
    path: ./layer
    compatibleRuntimes:
      - nodejs12.x
    package:
      include:
        - ./layer/node_modules/**
      exclude:
        - ./**/.yarnclean
        - ./**/node_modules/**/tests
        - ./**/package.json
        - ./**/yarn.lock

```

</details>
