### ISSUE TITLE
AWS API Gateway: Custom 200 status code response is ignored

### ISSUE THREAD

**Issue by sps-software** [serverless/serverless#7892]
Serverless version 1.74.1

Deploying with lambda integration does not apply response mapping template to 200 response.

After deploying, and navigating to the API Gateway console, I _can_ see the corresponding '$input.path("$.errorMessage")' templates for 400, 404, and 500 responses, however there is no template for a 200 response. This means the the stringified JSON body will not be parsed for a response. 

for example:

```
{
    "isBase64Encoded": false,
    "statusCode": 200,
    "headers": {
        "Content-Type": "application/json"
    },
    "body": "{\"so\":\"much\",\"data\":\"wow\"}"
}
```
 I can add the template, save it, and after a redeploy (and possibly hitting "save" again in the apo gateway template console) it will respond with give the expected response (only the parsed json body):

```
{
    "so": "much",
    "data": "wow"
}
``` 

<details>
<summary><code>serverless.yml</code></summary>

```yaml

service: test-xray-stack-trace

custom:
  stage: staging

plugins: 
  - serverless-offline
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs12.x
  stage: staging
  region: us-east-2

functions:
  throwError:
    tracing: true
    handler: handler.throwError
    role:  ${ssm:/artspot/iam/cancelation-lambda-role-${self:custom.stage}}
    events:
      - http:
          path: /throw-error
          method: get
          integration: lambda  
          response:
            statusCodes:
              200:
                pattern: '.*"statusCode":200,.*' # JSON response
                template: $input.path("$.body") # JSON return object
              400:
                pattern: '.*"statusCode":400,.*' # JSON response
                template: $input.path("$.errorMessage") # JSON return object
              404:
                pattern: '.*"statusCode":404,.*' # JSON response
                template: $input.path("$.errorMessage") # JSON return object
              500:
                pattern: '.*"statusCode":500,.*' # JSON response
                template: $input.path("$.errorMessage") # JSON return object
```

</details>

This question isn't really relevant. I pasted the output above.

<b>Installed version</b>

```
Framework Core: 1.74.1
Plugin: 3.6.14
SDK: 2.3.1
Components: 2.31.6
```
