### ISSUE TITLE
s3 permissions not apply

### ISSUE THREAD

**Issue by arpecop** [serverless/serverless#7894]
I am having trouble accessing s3, the error is "Access Denied" when I look at the permissions only "List Bucket" is applied 
![Screenshot 2020-07-01 at 12 03 35](https://user-images.githubusercontent.com/168974/86225521-05cb0800-bb93-11ea-9898-cf6f8c90770a.png)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: rudixlab
app: rudixlab

service: dynamodbone
plugins:
    - serverless-domain-manager
custom:
    customDomain:
        domainName: 'rudixlab.com'
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: true
provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-central-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:DescribeTable
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource:
              - arn:aws:dynamodb:eu-central-1:*:*
        - Effect: Allow
          Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
          Resource:
              - 'arn:aws:s3:::'
functions:
    app:
        handler: server.handler
        memorySize: 256
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
```

</details>

<details>
<summary><b><code>REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
Framework Core: 1.74.1 (standalone)
Plugin: 3.6.14
SDK: 2.3.1
Components: 2.31.6
```
