### ISSUE TITLE
Resolving unresolved variables inside of ${file(...):func} prints endless "0 of 0 promises have settled" message

### ISSUE THREAD

**Issue by walery** [serverless/serverless#7896]
Sometimes variable that are taken inside of function called from `${file(...js):func}` has unresolved variables. See for more details #7895.
It looks like the `serverless.variables.populateProperty(...)` can resolve strings with variables. As it returns Promise we need to handle it with callback.
Everything works fine except that sls hangs with this message:

```
 Serverless Information ----------------------------------

  ############################################################################################
    # 2478: 0 of 0 promises have settled
    # 2478: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################
```

This message didn't stop to appear.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: ${self:custom.product}-${self:custom.component}

provider:
  name: aws

custom:
  product: foo
  component: backend

resources:
  - Outputs:
      Foo:
        Value: ${file(foo.js):bar}
```

</details>

<details>
<summary><code>foo.js</code></summary>

```js
module.exports.bar = (serverless) => {
    const originalStackName = serverless.providers.aws.naming.getStackName();
    serverless.cli.consoleLog(`\noriginal stackName: ${originalStackName}`);

    return serverless.variables.populateProperty(originalStackName)
        .then(stackName => {
            serverless.cli.consoleLog(`resolved stackName: ${stackName}\n`)

            return new Promise((resolve) => {
                resolve('just dummy... .then(...) version');
            });
        });
};
```

</details>

<details>
<summary><b><code>sls print</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev

original stackName: ${self:custom.product}-${self:custom.component}-dev
resolved stackName: foo-backend-dev

service: foo-backend
provider:
  name: aws
custom:
  product: foo
  component: backend
resources:
  - Outputs:
      Foo:
        Value: just dummy... .then(...) version


 Serverless Information ----------------------------------

  ############################################################################################
    # 2478: 0 of 0 promises have settled
    # 2478: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################


 Serverless Information ----------------------------------

  ############################################################################################
    # 4980: 0 of 0 promises have settled
    # 4980: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################


 Serverless Information ----------------------------------

  ############################################################################################
    # 7482: 0 of 0 promises have settled
    # 7482: 0 are taking longer than expected:
    # This can result from latent connections but may represent a cyclic variable dependency
    ##########################################################################################

^C
```

</details>

<b>Installed version</b>

```
Framework Core: 1.74.1
Plugin: 3.6.15
SDK: 2.3.1
Components: 2.31.9
```
