### ISSUE TITLE
Cannot use VSCode debugger with Python runtime

### ISSUE THREAD

**Issue by dwbelliston** [serverless/serverless#7898]
VSCode debugger cannot attach tty when using python runtime and invoking the function with invoke 'local'

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: crumbs

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  account: ${opt:account, 'bgd'}
  runtime: python3.8

functions:
  crumbsMaker:
    name: crumbs
    handler: src/crumbs.handler
```

</details>

<details>
<summary><code>crumbs.py</code></summary>

```python

def handler(evt=None, ctx=None):
    try:
        print('crumb')
        a = 5
        print('crumbs')
    except Exception as err:
        raise err
```
</details>

<details>
<summary><code>launch.json (vscode debugger)</code></summary>

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "sls",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/serverless/bin/serverless",
      "args": [
        "invoke",
        "local",
        "--function",
        "crumbsMaker",
        "--path",
        "test/oanda_raw/event.json",
        "--stage",
        "dev"
      ]
    }
  ]
}
```

</details>

<details>
<summary><b><code>/usr/local/bin/node --inspect-brk=41235 node_modules/serverless/bin/serverless invoke local --function crumbsMaker --path test/oanda_raw/event.json --stage dev </code> output</b></summary>

```
Debugger listening on ws://127.0.0.1:41235/8a1481ab-55cf-4e1f-9c7f-1032fe304ccb
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Traceback (most recent call last):
  File "/Users/dwbelliston/code/nuskin/oanda-ingestion/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 83, in <module>

CLI.js:371
    sys.stdin = open('/dev/tty')
OSError: [Errno 6] Device not configured: '/dev/tty'
```

</details>

<b>Installed version</b>

```
Framework Core: 1.61.2
Plugin: 3.2.7
SDK: 2.2.1
Components Core: 1.1.2
Components CLI: 1.4.0
```
