### ISSUE TITLE
IdentitySource not getting reflected in authorizer for type request

### ISSUE THREAD

**Issue by singla96** [serverless/serverless#7899]
Trying to add multiple request identitySources for type request. But none of them are getting reflected 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  x1:
    handler: abc/file.func

  funccc:
    handler: x/file.function  
    events:
      - http:
          path: abc/fvg
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - xyz
              - abc
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
          authorizer:
            name: x1
            resultTtlInSeconds: 3600
            type: request
            identitySource: method.request.header.abc, method.request.header.xyz

```

</details>

 simple sls deploy is being used. But cannot provide its output right away

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

 Updated today but was happening previously as well

<b>Installed version</b>

```
Framework Core: 1.74.1
Plugin: 3.6.15
SDK: 2.3.1
Components: 2.31.10
```
