### ISSUE TITLE
Use serverless.ts configuration file format for aws-nodejs-typescript example

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#7933]
### Use case description

Since #7755 has been merged, and thanks to https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/serverless/plugins/aws/provider/awsProvider.d.ts definition, it is now possible to enforce serverless configuration file format using typescript types.

Serverless configuration file definition only covers AWS provider as of today.

Template `aws-nodejs-typescript` still uses `serverless.yml` file despite all functions being written in typescript.

### Proposed solution

Update `aws-nodejs-typescript` template to use `serverless.ts` description file with correct definition import from `DefinitlyTyped` repository.
Update documentation to reflect possibility to use `serverless.ts` file.

**Comment by ffxsam** [comment]
Just curious about the rationale behind using `serverless.ts` vs `serverless.yml`. I liked the YAML format because I could easily include CloudFormation resources at the end:

```yaml
resources:
  Description: Buckets, SNS event, and Lambda funcs
  Parameters:
    Stage:
      Type: String
      Default: ${self:custom.stage}
  Conditions:
    ProductionEnv: !Equals [!Ref Stage, prod]

  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
# etc.
```

It's not clear how to do this with the new format.
