### ISSUE TITLE
Adding env variable break post lambdas

### ISSUE THREAD

**Issue by Minifranger** [serverless/serverless#7935]
I have a problem where the only action of adding a env variable to my serverless.yml breaks the only post lambda I have. The env variables are correctly loaded to the lambda :

![image](https://user-images.githubusercontent.com/22295712/87342494-9d453900-c54b-11ea-82eb-455b43f77639.png)

However, my react app that makes the api calls to that lambda doesn't even reach the endpoint (no logs are found). The only action of removing the PRICE_TABLE and redeploying fix the api calls from my app. All my others lambdas works fine either way.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: dofus-bubble

package:
  individually: true

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3

  environment:
    ACCOUNT: '166257563783'
    AWS_UTILS: 46
    DYNAMODB_TABLE: ${self:service}
    PRICE_TABLE: ${self:service}

  iamRoleStatements:
    - Effect: Allow
      Action:
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

  events:
    - http:
        cors: true
  layers:
    - "arn:aws:lambda:${opt:region, self:provider.region}:${self:provider.environment.ACCOUNT}:layer:aws-utils:${self:provider.environment.AWS_UTILS}"

functions:
  scan_consumables:
    handler: dofus_bubble/dofapi/lambdas.scan_consumables
    events:
      - http:
          path: dofus_bubble/consumables
          method: get
  scan_equipments:
    handler: dofus_bubble/dofapi/lambdas.scan_equipments
    events:
      - http:
          path: dofus_bubble/equipments
          method: get
  scan_idols:
    handler: dofus_bubble/dofapi/lambdas.scan_idols
    events:
      - http:
          path: dofus_bubble/idols
          method: get
  scan_resources:
    handler: dofus_bubble/dofapi/lambdas.scan_resources
    events:
      - http:
          path: dofus_bubble/resources
          method: get
  scan_weapons:
    handler: dofus_bubble/dofapi/lambdas.scan_weapons
    events:
      - http:
          path: dofus_bubble/weapons
          method: get
  _scan_items:
    handler: dofus_bubble/dofapi/lambdas._scan_items
    events:
      - http:
          path: dofus_bubble
          method: get
  scan_items:
    handler: dofus_bubble/price/lambdas.scan
    events:
      - http:
          path: dofus_bubble/dynamodb
          method: get
  get_item:
    handler: dofus_bubble/price/lambdas.get
    events:
      - http:
          path: dofus_bubble/dynamodb/{_id}
          method: get
  put_item:
    handler: dofus_bubble/price/lambdas.put
    events:
      - http:
          path: dofus_bubble/dynamodb
          method: post
  scan_items_craft:
    handler: dofus_bubble/dofus/lambdas.scan_items_craft
    events:
      - http:
          path: dofus_bubble/dofus
          method: get
  scan_consumables_price:
    handler: dofus_bubble/dofus/lambdas.scan_consumables_price
    events:
      - http:
          path: dofus_bubble/dofus/consumables
          method: get
  scan_equipments_price:
    handler: dofus_bubble/dofus/lambdas.scan_equipments_price
    events:
      - http:
          path: dofus_bubble/dofus/equipments
          method: get
  scan_idols_price:
    handler: dofus_bubble/dofus/lambdas.scan_idols_price
    events:
      - http:
          path: dofus_bubble/dofus/idols
          method: get
  scan_resources_price:
    handler: dofus_bubble/dofus/lambdas.scan_resources_price
    events:
      - http:
          path: dofus_bubble/dofus/resources
          method: get
  scan_weapons_price:
    handler: dofus_bubble/dofus/lambdas.scan_weapons_price
    events:
      - http:
          path: dofus_bubble/dofus/weapons
          method: get
```

</details>
