### ISSUE TITLE
Issue with 1.75.0 and HTTP API

### ISSUE THREAD

**Issue by jameswoodley** [serverless/serverless#7946]
When creating a HTTP API on 1.75.0 using

```
provider:
  httpApi:
    payload: '2.0'

function:
  <snip>
  events:
      - httpApi: 'POST /links'
```
It "seems" to get deployed, althought I can't see any verbose output due to https://github.com/serverless/serverless/issues/7944. However calling the API I get an "Internal Server Error" and no logs in Cloudwatch

Literally just rolling back to 1.74.1 and redeploying fixes everything
