### ISSUE TITLE
">-" is replaced by "|-" in Resources section which causes AWS::ApiGatewayV2::Stage deployment to fail

### ISSUE THREAD

**Issue by dankochetov** [serverless/serverless#7950]
I have the following YAML snippet in my Resources section:
```yaml
Resources:
  WebSocketsAPIStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: ###
      StageName: ${self:custom.stage}
      AccessLogSettings:
        DestinationArn: !Sub ###
        Format: >-
          {
            "caller" = "$context.identity.caller",
            "connectionId" = "$context.connectionId",
            "eventType" = "$context.eventType",
            "ip" = "$context.identity.sourceIp",
            "requestId" = "$context.requestId",
            "requestTime" = "$context.requestTime",
            "routeKey" = "$context.routeKey",
            "status" = "$context.status",
            "user" = "$context.identity.user"
          }
      DefaultRouteSettings:
        DataTraceEnabled: true
        DetailedMetricsEnabled: true
        LoggingLevel: INFO
```

When I invoke `serverless print`, the snippet is transformed into this:
```yaml
Resources:
    WebSocketsAPIStage:
      Type: 'AWS::ApiGatewayV2::Stage'
      Properties:
        ApiId: ###
        StageName: ###
        AccessLogSettings:
          DestinationArn:
            'Fn::Sub': >-
              ###
          Format: |-
            {
              "caller" = "$context.identity.caller",
              "connectionId" = "$context.connectionId",
              "eventType" = "$context.eventType",
              "ip" = "$context.identity.sourceIp",
              "requestId" = "$context.requestId",
              "requestTime" = "$context.requestTime",
              "routeKey" = "$context.routeKey",
              "status" = "$context.status",
              "user" = "$context.identity.user"
            }
        DefaultRouteSettings:
          DataTraceEnabled: true
          DetailedMetricsEnabled: true
          LoggingLevel: INFO
```

As you can see, the `>-` in the Format field gets replaced by `|-` which causes the deployment to fail, because this field is expected to be a single line by AWS. This is the error I'm receiving:
```
The following errors are found in Access Log Format: Access Log format must be single line: '{ "caller" = "$context.identity.caller", "connectionId" = "$context.connectionId", "eventType" = "$context.eventType", "ip" = "$context.identity.sourceIp", "requestId" = "$context.requestId", "requestTime" = "$context.requestTime", "routeKey" = "$context.routeKey", "status" = "$context.status", "user" = "$context.identity.user" }' (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 9db9e351-9f1d-4497-83d8-88227ab85aa0; Proxy: null)
```

<b>Installed version</b>

```
6.14.4
```
