### ISSUE TITLE
Native Terraform Integration

### ISSUE THREAD

**Issue by mcalhoun** [serverless/serverless#7959]
### Use case description

[The definitive guide to using Terraform with the Serverless Framework](https://www.serverless.com/blog/definitive-guide-terraform-serverless) describes the use cases for using Terraform to provision shared, non-app-specific infrastructure. In the guide, it is suggested that Terraform should store its outputs in [AWS SSM Parameter Store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html), however, this requires tight coupling between Terraform modules and Serverless configurations. 

### Proposed solution

My proposal is to add native support to read Terraform outputs directly. In the example below, Serverless would resolve the `db_url` output from the Terraform module located at `/infrastructure-live/prod/us-east-1/prod/data-stores/postgres`

```yaml
 functions:
      darksky:
        handler: handler.darksky
        environment: 
          DARKSKY_DB_URL: ${terraform:/infrastructure-live/prod/us-east-1/prod/data-stores/postgres~db_url}
        events:
          - http:
              path: /darksky/{latitude}/{longitude}
              method: get
```
