### ISSUE TITLE
aws-clojurescript-gradle template failed to invoke local

### ISSUE THREAD

**Issue by yyamano** [serverless/serverless#7960]
aws-clojurescript-gradle template failed to invoke local.
I don't change generated code.

I guess the issue is related with #7025

```
sls create -t aws-clojurescript-gradle -p aws-clojurescript-gradle
cd aws-clojurescript-gradle
./gradlew build
sls invoke local -f hello
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-clojurescript-gradle
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - ./**
    - build/**
  include:
    - node_modules/**
    - build/clojurescript/main/functions.js

functions:
  hello:
    handler: build/clojurescript/main/functions.hello
    events:
      - http:
          path: hello
          method: get

  now:
    handler: build/clojurescript/main/functions.now
    events:
      - http:
          path: now
          method: get
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

```

</details>

<details>
<summary><b><code>sls invoke local -f hello</code> output</b></summary>

```
Error: Cannot find module 'moment'
Require stack:
- /private/tmp/aws-clojurescript-gradle/build/clojurescript/main/functions.js
- /opt/pkg/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js
- /opt/pkg/lib/node_modules/serverless/lib/plugins/index.js
- /opt/pkg/lib/node_modules/serverless/lib/classes/PluginManager.js
- /opt/pkg/lib/node_modules/serverless/lib/Serverless.js
- /opt/pkg/lib/node_modules/serverless/lib/utils/autocomplete.js
- /opt/pkg/lib/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/private/tmp/aws-clojurescript-gradle/build/clojurescript/main/functions.js:2116:755)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/opt/pkg/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:696:33)
    at AwsInvokeLocal.invokeLocal (/opt/pkg/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:183:19)
    at AwsInvokeLocal.tryCatcher (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/aws-clojurescript-gradle/build/clojurescript/main/functions.js',
    '/opt/pkg/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js',
    '/opt/pkg/lib/node_modules/serverless/lib/plugins/index.js',
    '/opt/pkg/lib/node_modules/serverless/lib/classes/PluginManager.js',
    '/opt/pkg/lib/node_modules/serverless/lib/Serverless.js',
    '/opt/pkg/lib/node_modules/serverless/lib/utils/autocomplete.js',
    '/opt/pkg/lib/node_modules/serverless/bin/serverless.js'
  ]
}
 
  Error --------------------------------------------------
 
  Error: Exception encountered when loading /private/tmp/aws-clojurescript-gradle/build/clojurescript/main/functions
      at AwsInvokeLocal.invokeLocalNodeJs (/opt/pkg/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:701:13)
      at AwsInvokeLocal.invokeLocal (/opt/pkg/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:183:19)
      at AwsInvokeLocal.tryCatcher (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/opt/pkg/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.3.0
     Framework Version:         1.75.1
     Plugin Version:            3.6.16
     SDK Version:               2.3.1
     Components Version:        2.32.0
```

</details>

<b>Installed version</b>

```
Framework Core: 1.75.1
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```
