### ISSUE TITLE
package individual: true cause file not found when packaging.

### ISSUE THREAD

**Issue by c19** [serverless/serverless#7962]
To Reproduce:

clone this to local machine: https://github.com/serverless/examples/tree/master/aws-node-puppeteer

replace `serverless.yml` with the following content:
```
service: scrapper-lambda
provider:
  name: aws
  profile: bijietech-dev
  runtime: nodejs12.x

plugins:
  - serverless-offline
  - serverless-plugin-chrome

package:
  individually: true

functions:
  hello:
    handler: handler.hello
    memorySize: 1536MB
    timeout: 30
    package:
      exclude:
        - node_modules/puppeteer/.local-chromium/**
    events:
      - http:
          path: /
          method: get
```

run `npm i`

run `sls package`

And you get this error: 
```
sls package
Serverless: Injecting Headless Chrome...
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Error --------------------------------------------------

  Error: ENOENT: no such file or directory, open '/Users/user/Documents/serverless-examples/aws-node-puppeteer/.build/.serverless/hello.zip'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.3.0
     Framework Version:         1.71.3
     Plugin Version:            3.6.12
     SDK Version:               2.3.0
     Components Version:        Unavailable
```

works fine if you use the original serverless.yml. seems like package individual: true changed the `serverless.service.functions.hello.package.artifact` to `/Users/user/Documents/serverless-examples/aws-node-puppeteer/.build/.serverless/hello.zip` but Actually the hello.zip is located at `/Users/user/Documents/serverless-examples/aws-node-puppeteer/.serverless/hello.zip`
