### ISSUE TITLE
logIngestMode: pull is not working.

### ISSUE THREAD

**Issue by jerber** [serverless/serverless#7967]
logIngestMode: pull is not having serverless pull the logs from my aws lambda function. The serverless dashboard says there are no function calls even though I'm successfully calling the function.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

app: my-app
org: my-org

provider:
  name: aws
  runtime: python3.8
  stage: ${env:STAGE, 'dev'}
  timeout: 15
  tracing: # what does this do exactly?
    lambda: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: "*"

functions:
  app:
    handler: main.handler
    warmup: true
    package: {} # https://github.com/serverless/serverless/issues/6752
    events:
      - http: ANY /
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-plugin-warmup


package:
  exclude:
    - node_modules/**
    - venv/**
    - env/**
    - magic_venv/**
    - .env


custom:
  enterprise:
    logIngestMode: pull
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy:
      - boto3
      - botocore
      - s3transfer
      - pytest
      - typer
  warmup:
    concurrency: 5 # Warm up 5 concurrent instances
    prewarm: true
```

</details>

<details>
<summary><b><code>sls deploy</code> despite having a working deployed function, the logs are not pulled by serverless to the dashboard.</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
Framework Core: 1.75.1
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```
