### ISSUE TITLE
Type validation mismatch for StatusCode in AWS::ApiGateway::Method response objects

### ISSUE THREAD

**Issue by Undre4m** [serverless/serverless#7970]
The **StatusCode** property for the compiled API gateway method response's template is of wrong type, as defined by [AWS official documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-methodresponse.html#cfn-apigateway-method-methodresponse-statuscode)

```yaml
functions:
  name:
    events:
      - http:
          response:
            statusCodes:
              200:
                pattern: ''
```

```json
...
  "MethodResponses": [
    {
        "ResponseParameters": {},
        "ResponseModels": {},
        "StatusCode": 200
    }
...
```

Type: **Int**
Expected Type: **String**

The type mismatch does not affect deployment (to this day) to AWS services but does so for localstack and others who expect a cloudformation template consistent with documented definitions.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: example

plugins:
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.defaultStage}

provider:
  name: aws
  runtime: nodejs12.x
  defaultStage: development

functions:
  name:
    handler: src/index.handler
    events:
      - http:
          path: v1
          method: post
          integration: lambda
          response:
            template: $input.path('$')
            statusCodes:
              200:
                pattern: ''
              400:
                pattern: '.*"customLambdaError".*'
                template: $input.path('$.errorMessage')
              409:
                pattern: '.*"statusCode":409,.*'
                template:
                  application/json: $input.path("$.errorMessage")
                  application/xml: $input.path("$.body.errorMessage")
                headers:
                  Content-Type: "'application/json+hal'"

      - http:
          path: v1
          method: get
          integration: lambda
          request:
            parameters:
              querystrings:
                code: true
                state: true
          response:
            statusCodes:
              201:
                pattern: ''
              302:
                pattern: http.*
                headers:
                  Location: integration.response.body.errorMessage
                  Cache-Control: "'no-cache, no-store, must-revalidate'"
```

</details>

<details>
<summary><b><code>package</code> output</b></summary>

```
serverless package -s development
```

</details>

<b>Installed version</b>

```
Framework Core: 1.75.1
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```

I will link and open an issue at _localstack/serverless-localstack_ as it's affecting deployment with that particular stack but bottomline this is an issue in how sls compiles the cloudformation template in a manner inconsistent with what's expected according to documentation.
