### ISSUE TITLE
API Gateway missing aws_iam authorizer and cors

### ISSUE THREAD

**Issue by snowman2** [serverless/serverless#7971]
API Gateway missing aws_iam authorizer and cors

Template excerpt:
```
        "ApiGatewayMethodAny": {
            "Type": "AWS::ApiGateway::Method",
            "Properties": {
                "HttpMethod": "ANY",
                "RequestParameters": {},
                "ResourceId": {
                    "Fn::GetAtt": [
                        "ApiGatewayRestApi",
                        "RootResourceId"
                    ]
                },
                "RestApiId": {
                    "Ref": "ApiGatewayRestApi"
                },
                "ApiKeyRequired": false,
                "AuthorizationType": "NONE",
                "Integration": {
                    "IntegrationHttpMethod": "POST",
                    "Type": "AWS_PROXY",
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myservice

provider:
  name: aws
  runtime: python3.6

custom:
# https://www.serverless.com/plugins/serverless-wsgi
  wsgi:
    app: api.wsgi.application
    packRequirements: false
# https://www.npmjs.com/package/serverless-python-requirements
  pythonRequirements:
    slim: true
    strip: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
        cors: true
        authorizer: aws_iam
      - http: ANY {proxy+}
        cors: true
        authorizer: aws_iam
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Deployed without error.
```

</details>

<b>Installed version</b>

```
Framework Core: 1.75.1
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```

Am I doing something wrong?

**Comment by snowman2** [comment]
It was me, this works:
```
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          method: any
          path: /
          authorizer: aws_iam
          cors: true
      - http:
          method: any
          path: '{proxy+}'
          authorizer: aws_iam
          cors: true
```
