### ISSUE TITLE
Please help, endpoints are not created

### ISSUE THREAD

**Issue by aikodeio** [serverless/serverless#7985]
Hello! when i run the command `serverless deploy` the console shows the following log:

```
PS G:\Apps\aws-lambda\node> serverless deploy -v

*** resolver04.vtr.net no encuentra 169.254.169.254: Non-existent domain
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Service Information
service: node
stage: production
region: us-west-2
stack: node-production
resources: 2
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None

Stack Outputs
ServerlessDeploymentBucketName: node-production-serverlessdeploymentbucket-1c7re1gornyvd
```

Lambda function and endpoints **are not created**

Is it for this reason? I do not get it
`*** resolver04.vtr.net no encuentra 169.254.169.254: Non-existent domain`

My serverless.yml:

```
service: node

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 2048
    timeout: 5
    stage: production
    region: us-west-2

function:
    api:
        handler: lambda.handler
        events:
            - http: 
                method: get
                path: /production-path
```

Thanks!
