### ISSUE TITLE
Discovery Service parameters in serverless.yml for gcloud config 

### ISSUE THREAD

**Issue by kalyco** [serverless/serverless#7996]
Discovery Service parameters in serverless.yml for gcloud config

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: process-snapshots-bag

provider:
  name: google
  runtime: nodejs10
  # change to environment variable
  project: ${opt:post_process_bucket_id, 'stg-mfp-analytics'}
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack
  - serverless-discovery-plugin

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - .gitignore
    - .git/**

custom:
  webpack:
    webpackConfig: 'webpack.config.js'  # Name of webpack configuration file
    includeModules:
       forceInclude:
         - rosbag # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules

  discovery:
    discoveryServiceUri: 'https://cloudfunctions.googleapis.com/$discovery/rest?version=v1beta2'
    deployHandler: scripts/deploy.handler # Same syntax as you already know
    accessKeyId: ${env:DISCOVERY_KEY_ID}
    removeHandler: scripts/remove.handler # Same syntax as you already know
    file: .build/stack.yml # toml, yaml, yml, and json format is available


functions:
  processSnapshotsBag:
    handler: processSnapshotsBag
    memorySize: 512
    timeout: 300s
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: projects/${opt:storage-project-id, 'stg-mfp-analytics'}/buckets/${opt:bag-bucket, 'stg-mfp-bags-snapshots'}

  # NOTE: the following uses an "event" event (pubSub event in this case).
  # Please create the corresponding resources in the Google Cloud
  # before deploying this service through Serverless

  #second:
  #  handler: event
  #  events:
  #    - event:
  #        eventType: providers/cloud.pubsub/eventTypes/topic.publish
  #        resource: projects/*/topics/my-topic

# you can define resources, templates etc. the same way you would in a
# Google Cloud deployment configuration
#resources:
#  resources:
#    - type: storage.v1.bucket
#      name: my-serverless-service-bucket
#  imports:
#    - path: my_template.jinja
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/src/mfp_post_processing(master*) » sls deploy                                                                                                                                    kalyco@Kaylas-MacBook-Pro
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command logs
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
Time: 5274ms
Built at: 07/27/2020 2:37:19 PM
                 Asset       Size  Chunks                    Chunk Names
dist/SnapshotBags.d.ts  165 bytes          [emitted]         
         dist/grm.d.ts   77 bytes          [emitted]         
       dist/index.d.ts  100 bytes          [emitted]         
dist/rosMsgToJSON.d.ts  392 bytes          [emitted]         
              index.js   4.41 MiB       0  [emitted]  [big]  main
Entrypoint main [big] = index.js
  [1] external "util" 42 bytes {0} [built]
 [26] external "fs" 42 bytes {0} [built]
 [43] external "path" 42 bytes {0} [built]
 [90] external "os" 42 bytes {0} [built]
[171] ./node_modules/define-properties/index.js 1.57 KiB {0} [built]
[239] ./node_modules/util.promisify/implementation.js 2.83 KiB {0} [built]
[247] ./node_modules/util.promisify/polyfill.js 236 bytes {0} [built]
[264] external "child_process" 42 bytes {0} [built]
[344] ./node_modules/lodash/lodash.js 530 KiB {0} [built]
[351] multi babel-polyfill util.promisify ./lib/index.ts 52 bytes {0} [built]
[352] ./node_modules/babel-polyfill/lib/index.js 833 bytes {0} [built]
[353] ./node_modules/core-js/shim.js 8.03 KiB {0} [built]
[550] ./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js 23.9 KiB {0} [built]
[554] ./node_modules/util.promisify/index.js 615 bytes {0} [built]
[581] ./lib/index.ts 8.8 KiB {0} [built]
    + 853 hidden modules

WARNING in ./node_modules/hash-stream-validation/index.js
Module not found: Error: Can't resolve 'fast-crc32c' in '/Users/kalyco/src/mfp_post_processing/node_modules/hash-stream-validation'
 @ ./node_modules/hash-stream-validation/index.js
 @ ./node_modules/@google-cloud/storage/src/file.js
 @ ./node_modules/@google-cloud/storage/src/index.js
 @ ./lib/index.ts
 @ multi babel-polyfill util.promisify ./lib/index.ts
Serverless: Invoke webpack:package
Serverless: WARNING: Could not determine version of module rosbag
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: rosbag
Serverless: WARNING: Could not determine version of module rosbag
Serverless: Packaging service...
Serverless: Compiling function "processSnapshotsBag"...
 
  Error --------------------------------------------------
 
  Error: Error: Discovery document not found for API service: cloudfunctions.googleapis.com format: rest version: v1beta2
      at /Users/kalyco/src/mfp_post_processing/node_modules/serverless-google-cloudfunctions/provider/googleProvider.js:50:36
      at /Users/kalyco/src/mfp_post_processing/node_modules/googleapis/lib/googleapis.js:184:14
      at handleError (/Users/kalyco/src/mfp_post_processing/node_modules/googleapis/lib/generator_utils.js:50:5)
      at _generate (/Users/kalyco/src/mfp_post_processing/node_modules/googleapis/lib/discovery.js:240:14)
      at Request._callback (/Users/kalyco/src/mfp_post_processing/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:106:7)
      at Request.self.callback (/Users/kalyco/src/mfp_post_processing/node_modules/request/request.js:185:22)
      at Request.emit (events.js:315:20)
      at Request.EventEmitter.emit (domain.js:482:12)
      at Request.<anonymous> (/Users/kalyco/src/mfp_post_processing/node_modules/request/request.js:1154:10)
      at Request.emit (events.js:315:20)
      at Request.EventEmitter.emit (domain.js:482:12)
      at IncomingMessage.<anonymous> (/Users/kalyco/src/mfp_post_processing/node_modules/request/request.js:1076:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at IncomingMessage.EventEmitter.emit (domain.js:482:12)
      at endReadableNT (_stream_readable.js:1221:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
  From previous event:
      at PluginManager.invoke (/snapshot/serverless/lib/classes/PluginManager.js:476:22)
      at /snapshot/serverless/lib/classes/PluginManager.js:511:24
  From previous event:
      at PluginManager.run (/snapshot/serverless/lib/classes/PluginManager.js:511:8)
      at /snapshot/serverless/lib/Serverless.js:131:33
  From previous event:
      at Serverless.run (/snapshot/serverless/lib/Serverless.js:118:74)
      at /snapshot/serverless/bin/serverless.js:80:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (/snapshot/serverless/bin/serverless.js:80:4)
      at Module._compile (pkg/prelude/bootstrap.js:1320:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
      at Module.load (internal/modules/cjs/loader.js:984:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.1
     Framework Version:         1.74.1 (standalone)
     Plugin Version:            3.6.14
     SDK Version:               2.3.1
     Components Version:        2.31.6
```

</details>

<b>Installed version</b>

```
Framework Core: 1.74.1 (standalone)
Plugin: 3.6.14
SDK: 2.3.1
Components: 2.31.6
```
