### ISSUE TITLE
AWS auth still broken on 1.77

### ISSUE THREAD

**Issue by etaoins** [serverless/serverless#7997]
AWS auth is broken with serverless 1.76 & 1.77 after working successfully on 1.75. This affects multiple repos.

Our typical deployment setup runs in a `node-12:alpine` container using [docker-compose-buildkite-plugin](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin). The deployment happens within the AWS account and depends on the EC2 metadata for auth.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: db-client-heartbeat

custom:
  description: Heartbeat for observing database failover characteristics
  seekWebKmsKeyArn: REDACTED

  env: ${self:custom.envs.${env:ENVIRONMENT}}
  envs:
    dev:
      isProduction: 'false'
      seekWebSecretArn: REDACTED
      subnetIds:
        - REDACTED
        - REDACTED
        - REDACTED
      vpcId: REDACTED
    prod:
      isProduction: 'true'
      seekWebSecretArn: REDACTED
      subnetIds:
        - REDACTED
        - REDACTED
        - REDACTED
      vpcId: REDACTED

provider:
  logRetentionInDays: 30
  name: aws
  region: ap-southeast-2
  runtime: nodejs12.x
  stackName: ${self:service}
  stage: ${env:ENVIRONMENT}
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)]+?)}"
  deploymentBucket:
    name: ${cf:infra-artefacts.BucketName}
  iamRoleStatements:
    - Action: kms:Decrypt
      Effect: Allow
      Resource: ${self:custom.seekWebKmsKeyArn}
    - Action: secretsmanager:GetSecretValue
      Effect: Allow
      Resource: ${self:custom.env.seekWebSecretArn}-??????
  vpc:
    securityGroupIds:
      - !Ref SecurityGroup
    subnetIds: ${self:custom.env.subnetIds}

package:
  exclude:
    - ./**
    - '!node_modules/**'
  include:
    - lib/**

functions:
  Heartbeat:
    name: ${self:service}
    handler: lib/app.handler
    description: ${self:custom.description}
    memorySize: 128
    reservedConcurrency: 5
    timeout: 900
    environment:
      ENVIRONMENT: ${env:ENVIRONMENT}
      REGION: ${self:provider.region}
      SEEKWEB_SECRET_ARN: ${self:custom.env.seekWebSecretArn}
      SERVICE: ${self:service}
      VERSION: ${env:VERSION}
    events:
      - schedule:
          rate: rate(10 minutes)

resources:
  # This becomes the Lambda application's description
  Description: ${self:custom.description}

  Resources:
    CloudWatchInvokeConfig:
      Type: AWS::Lambda::EventInvokeConfig
      Properties:
        FunctionName: !Ref HeartbeatLambdaFunction
        MaximumRetryAttempts: 0
        Qualifier: $LATEST

    SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: ${self:service}
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
        VpcId: ${self:custom.env.vpcId}
```

</details>

<details>
<summary><b><code>serverless deploy --force --verbose</code> output</b></summary>

```
Serverless Error ---------------------------------------
--
  |  
  | Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
  |  
  | Get Support --------------------------------------------
  | Docs:          docs.serverless.com
  | Bugs:          github.com/serverless/serverless/issues
  | Issues:        forum.serverless.com
  |  
  | Your Environment Information ---------------------------
  | Operating System:          linux
  | Node Version:              12.18.2
  | Framework Version:         1.77.0
  | Plugin Version:            3.6.18
  | SDK Version:               2.3.1
  | Components Version:        2.33.0

```

</details>

<b>Installed version</b>

```
Framework Core: 1.77.0
Plugin: 3.6.18
SDK: 2.3.1
Components: 2.33.0
```
