### ISSUE TITLE
Python serverless sdk "UnboundLocalError": "local variable 'response' referenced before assignment"

### ISSUE THREAD

**Issue by gclindsey** [serverless/serverless#8005]
My code appears correct and runs locally, but more importantly it contains no variable 'response'. Occurs when running the function in AWS Lambda which uses layers containing the [pyppeteer](https://github.com/pyppeteer/pyppeteer) package and headless chrome binary from [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda). 

This issue appears to be very similar to [#6801](https://github.com/serverless/serverless/issues/6801), see stack trace for details:
```
"  File \"/var/task/serverless_sdk/__init__.py\", line 567, in wrapper\n    if response:\n"
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test

provider:
  name: aws
  runtime: python3.7
  environment:
    HOME: /tmp

functions:
  functionName:
    handler: handler.run
    layers:
      - arn:aws:lambda:us-east-1:XXXXXXXXXXXX:layer:data-analysis-utils:1
      - arn:aws:lambda:us-east-1:XXXXXXXXXXXX:layer:chrome-aws-lambda:1
      - arn:aws:lambda:us-east-1:XXXXXXXXXXXX:layer:pyppeteer-selenium:1
```

</details>

<details>
<summary><b><code>Command</code> output</b></summary>

```
serverless invoke -f testTikTok --logs

{
  "errorMessage": "local variable 'response' referenced before assignment",
  "errorType": "UnboundLocalError",
  "stackTrace": [
    ...
    "  File \"/opt/python/lib/python3.7/site-packages/pyppeteer/launcher.py\", line 305, in launch\n    return await Launcher(options, **kwargs).launch()\n",
    "  File \"/opt/python/lib/python3.7/site-packages/pyppeteer/launcher.py\", line 166, in launch\n    self.browserWSEndpoint = get_ws_endpoint(self.url)\n",
    "  File \"/opt/python/lib/python3.7/site-packages/pyppeteer/launcher.py\", line 227, in get_ws_endpoint\n    with urlopen(url) as f:\n",
    "  File \"/var/lang/lib/python3.7/urllib/request.py\", line 222, in urlopen\n    return opener.open(url, data, timeout)\n",
    "  File \"/var/lang/lib/python3.7/urllib/request.py\", line 525, in open\n    response = self._open(req, data)\n",
    "  File \"/var/lang/lib/python3.7/urllib/request.py\", line 543, in _open\n    '_open', req)\n",
    "  File \"/var/lang/lib/python3.7/urllib/request.py\", line 503, in _call_chain\n    result = func(*args)\n",
    "  File \"/var/lang/lib/python3.7/urllib/request.py\", line 1347, in http_open\n    return self.do_open(http.client.HTTPConnection, req)\n",
    "  File \"/var/task/serverless_sdk/__init__.py\", line 567, in wrapper\n    if response:\n"
  ]
}
```

</details>

<b>Installed version</b>

```
Framework Core: 1.77.1
Plugin: 3.6.18
SDK: 2.3.1
Components: 2.33.0
```
