### ISSUE TITLE
Http Request Parameter/Header Validation

### ISSUE THREAD

**Issue by bmpickford** [serverless/serverless#8009]
### Use case description

Currently we are required to validate query parameters inside the application middleware, and would like to move that logic out similar to how the request body is validated using JSON schema before the request reaches the application. Some examples of validation we use is basic type validation i.e. number, as well as validating UUID's and custom enums.

### Proposed solution
Using the same syntax as json schema would for validation using regex, the implementation could be something similar like:
```
request:
  parameters:
    paths:
      someUUID:
        required: true
        type: string
        pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
```
