### ISSUE TITLE
DynamoDB table is not created

### ISSUE THREAD

**Issue by yevhenshymotiuk** [serverless/serverless#8011]
DynamoDB table is not created though it is described in logging (--verbose option)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: stickers-storage-bot

provider:
  name: aws
  runtime: go1.x
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
    DYNAMODB_TABLE: ${self:service}-users
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  webhook:
    handler: bin/webhook
    events:
      - http: POST /

  setWebhook:
    handler: bin/setwebhook
    events:
      - http: POST /set-webhook

package:
  exclude:
    - ./**
  include:
    - ./bin/**

```

</details>

<details>
<summary><b><code>sls deploy -v</code> output</b></summary>

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - stickers-storage-bot-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - stickers-storage-bot-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service stickers-storage-bot.zip file to S3 (6.41 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - stickers-storage-bot-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - usersTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SetWebhookLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - WebhookLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - SetWebhookLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::DynamoDB::Table - usersTable
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - WebhookLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - WebhookLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - SetWebhookLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceSetDashwebhook
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Resource - ApiGatewayResourceSetDashwebhook
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Resource - ApiGatewayResourceSetDashwebhook
CloudFormation - CREATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SetWebhookLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - WebhookLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - WebhookLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Function - SetWebhookLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - WebhookLambdaFunction
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Function - SetWebhookLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodPost
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - WebhookLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - WebhookLambdaVersiontQ4mlW22YcMW7bSDb6w416Dag8kUJAOD7pn5LndnA4
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodPost
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodSetDashwebhookPost
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - WebhookLambdaPermissionApiGateway
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SetWebhookLambdaVersionw6CrTCPEspmdRDkw7pmA1MUu22gvtkLFywpPTqWs0YY
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Method - ApiGatewayMethodSetDashwebhookPost
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - SetWebhookLambdaPermissionApiGateway
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodPost
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Permission - SetWebhookLambdaPermissionApiGateway
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Method - ApiGatewayMethodSetDashwebhookPost
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - SetWebhookLambdaVersionw6CrTCPEspmdRDkw7pmA1MUu22gvtkLFywpPTqWs0YY
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - SetWebhookLambdaVersionw6CrTCPEspmdRDkw7pmA1MUu22gvtkLFywpPTqWs0YY
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - WebhookLambdaVersiontQ4mlW22YcMW7bSDb6w416Dag8kUJAOD7pn5LndnA4
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - WebhookLambdaVersiontQ4mlW22YcMW7bSDb6w416Dag8kUJAOD7pn5LndnA4
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1596155473881
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1596155473881
CloudFormation - CREATE_COMPLETE - AWS::ApiGateway::Deployment - ApiGatewayDeployment1596155473881
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - WebhookLambdaPermissionApiGateway
CloudFormation - CREATE_COMPLETE - AWS::DynamoDB::Table - usersTable
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Permission - SetWebhookLambdaPermissionApiGateway
CloudFormation - UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - stickers-storage-bot-dev
CloudFormation - UPDATE_COMPLETE - AWS::CloudFormation::Stack - stickers-storage-bot-dev
Serverless: Stack update finished...
Service Information
service: stickers-storage-bot
stage: dev
region: us-east-1
stack: stickers-storage-bot-dev
resources: 17
api keys:
  None
endpoints:
  POST - https://yvh185rzu9.execute-api.us-east-1.amazonaws.com/dev
  POST - https://yvh185rzu9.execute-api.us-east-1.amazonaws.com/dev/set-webhook
functions:
  webhook: stickers-storage-bot-dev-webhook
  setWebhook: stickers-storage-bot-dev-setWebhook
layers:
  None

Stack Outputs
SetWebhookLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:283664111224:function:stickers-storage-bot-dev-setWebhook:15
WebhookLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:283664111224:function:stickers-storage-bot-dev-webhook:16
ServiceEndpoint: https://yvh185rzu9.execute-api.us-east-1.amazonaws.com/dev
ServerlessDeploymentBucketName: stickers-storage-bot-dev-serverlessdeploymentbuck-14mr4jti6fkas
```

</details>

<b>Installed version</b>

```
Framework Core: 1.75.1
Plugin: 3.6.16
SDK: 2.3.1
Components: 2.32.0
```
