### ISSUE TITLE
Add multiple object support for environmental variables

### ISSUE THREAD

**Issue by sajithneyo** [serverless/serverless#8037]
### Use case description

Currently, environment option in provider and in function level can only accept a single JSON object. It's better to have multiple object support.

### Proposed solution

```
environment:
  - ${self:custom.obj1}
  - ${self:custom.obj2}
```

**Comment by medikoo** [comment]
@sajithneyo great thanks for proposal!

It definitely makes sense to support input from many sources there.

Still we have many places like that, and I wonder whether we can come up with some global solution that will allow us to use it everywhere, and not  address each property like that individually.

It'll probably will have to be some variables resolution extension

**Comment by sajithneyo** [comment]
@medikoo yeah, it's better to have a global solution for that. but until that, it's better to have this feature for envs.

**Comment by medikoo** [comment]
I was thinking about sorting this with notation as following:

```yaml
environment:
  FOO: someVal
  $extend:
    - ${self:custom.obj1}
    - ${self:custom.obj2}
```

Still one problem I see, is that setting `$exclude` key (literally) would be impossible with that. Ideally we should not limit what keys can be used in objects (still that problem is probably already shared by var resolvers, which do not offer any escape mechanism to `${`)

**Comment by glb** [comment]
@medikoo it looks like the gitlab folks are doing something similar by extending YAML syntax, you may want to check out [their proposal](https://gitlab.com/groups/gitlab-org/-/epics/4381).

**Comment by medikoo** [comment]
@glb great thanks for linking that. That looks very neat.  Indeed maybe then it'll be better to do it as follows:

```yaml
environment:
  FOO: someVal
  !merge:
    - ${self:custom.obj1}
    - ${self:custom.obj2}
```

What do you think?

Note: I've put it slightly differently, as I think notation they propose (in `rules: !merge` example), will not really work, as it doesn't seem as valid YAML structure (but I didn't tested that through)

**Comment by glb** [comment]
@medikoo I don't know enough about how tags work in YAML processing to comment. I liked their proposal, if that's something that can actually be done.

**Comment by medikoo** [comment]
@glb I've replaced `$extend` with `!merge` in implementation proposal, as I think it's more intuitive, and as it's something else as our variables, I think it's ok to use `!` not `$` as prefix.

PR that implements that is welcome!

**Comment by medikoo** [comment]
On revisiting this, I have following thoughts:

A solution that works across all types of configs (YAML, JSON etc), is probably best if configured with our variables syntax. We can introduce e.g. `${merge(obj1, obj2, obj3)}`  which will do single level merge on either plain objects or arrays.

Downside is that we cannot merge _inline_ part with _externally_ configured parts. `${merge}`could only work with externally configured parts. Therefore eventual _inline_ part if needed will have to be configured in some side property, e.g.:

```yaml
custom:
  environment:
    FOO: value

provider:
  environment: ${merge(${self:custom.environment}, ${file(common-env.json)}})}
```

Downside of that, is that in context of YAML, it's not as convient to use, but specifically for YAML we can introduce a cleaner solution based on YAML function, which will work only in context of YAML confiugurations, and may look as:

```yaml
custom:
  environment:
    FOO: value

provider:
  environment: !merge
    - FOO: value
    - ${file(common-env.json)}
```

Both methods I think should be relatively easy to implement. @pgrzesik @glb what do you think?

**Comment by pgrzesik** [comment]
Thanks for proposal @medikoo. I like the approach based on variable syntax as it's the most universal, minus the downside that you highlighted. Then, if there's a need for that, we could also add the second, yaml-specific syntax with `!merge`

**Comment by medikoo** [comment]
Thanks @pgrzesik I've updated main description with instructions how we can implement it. Let me know what you think about it. 

As you mention I would definitely first got with `merge` variable source, and then eventually also `!merge` YAML extension can be provided

**Comment by glb** [comment]
Still required after serverless/utils#79 and #9314 are merged (if they're acceptable):
1. version bump for `serverless/utils`
2. update `serverless/serverless` to pick up new `serverless/utils` version, document `!merge` tag. Is `variables.md` the right place as stated in the description or is there somewhere else that makes sense?

**Comment by glb** [comment]
@medikoo I am running into some complexity with the `!merge` version of this, which I think is actually the most useful one. The problem is that the `!merge` processing happens during YAML parsing, but if someone has something like:

```yml
resources:
  Resources: !merge
    - ${file(file1.yml)}
    - ${file(file2.yml)}
```

we won't know the resolved values of `${file(file1.yml)}` and `${file(file2.yml)}` until after variable resolution.

I tried making the `!merge args` implementation simply insert `${merge(args)}` but it doesn't work with inputs like:

```yml
resources:
  Resources: !merge
    - a: 1
    - b: 2
```

because `Variable syntax error at "test": Invalid variable param at index 8 in "${merge({"a":"1"},{"b":"2"}}`). What I'm currently considering is remembering the inputs, replacing with placeholders, and transforming into something like `${merge(${_placeholder(1),${_placeholder(2)}}` where `_placeholder` retrieves the stored values. `_placholder` is probably not the right name for this.

Thoughts?
