### ISSUE TITLE
Serverless Rate exceeded for Cloudformation API

### ISSUE THREAD

**Issue by Fiiii** [serverless/serverless#8040]
Hi there! I have an issue connected with throttling on CloudFormation API. 
![Screenshot 2020-08-03 at 11 51 47](https://user-images.githubusercontent.com/10417758/89171151-0a635180-d581-11ea-8f7e-e81c80cd28e5.png)

Right now there is: 
- 26 functions 
- 3 dynamo tables, 1 sqs queue. 
- sum: 160 cf resources 

The issue occurs on the serverless deployment

```
  ServerlessError: An error occurred: 
BroadcastToClientsEventSourceMappingDynamodbChannelsMessagesTable - Rate exceeded for operation 'Rate exceeded (Service: Lambda, Status Code: 429, Request ID: b8b7796b-e9d7-4c84-9615-7d2a98c1c85b, Extended Request ID: null)
'..node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:125:33
  From previous event:
      at AwsDeploy.monitorStack (node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:28:12)
      at node_modules/serverless/lib/plugins/aws/lib/updateStack.js:115:28
```
I'm pasting cloudformation error. Its always the same on sqs and dynamodb stream events mapping.

This is my investigation:
1. CloudFormation resources limit ~160 - checked
2. Resources names limit (64) - I renamed to resources to the shortnames & error still occurs randomly - checked
Core issue always comes from EventSourceMapping resource creation.
ie. (BroadcastToClientsEventSourceMappingDynamodbChannelsMessagesTable - Rate exceeded for operation 'Rate exceeded (Service: Lambda, Status Code: 429)  
3. Error occurs only on "**new stack creation**" - all resources are triggered to deploy and then cloudformation returns rate exceed response on EventSourceMapping resource - checked
4. Deploying new stack needs to comment 50% of the functions in the resources files - checked
5. Splitting plugin doesn't help in type/group mode

<details>
<summary><code>serverless.yml</code></summary>

```yaml
broadcastToClients:
  handler: bin/broadcastToClients
  package:
    include:
      - bin/broadcastToClients
  events:
    - stream:
        type: dynamodb
        batchSize: 1
        enabled: true
        startingPosition: LATEST
        arn:
          Fn::GetAtt:
            - channelsMessagesTable
            - StreamArn


channelBackup:
  handler: bin/channelBackup
  package:
    include:
      - bin/channelBackup
  events:
    - sqs:
        exist: true
        arn:
          Fn::GetAtt:
            - backupQueue
            - Arn
```

</details>

<details>
<summary><b><code>deploy command</code></b></summary>

```
sls deploy --verbose --stage xyz
```

</details>

     Node Version:              12.18.1
     Framework Version:         1.73.1
     Plugin Version:            3.6.14
     SDK Version:               2.3.1
     Components Version:        2.31.6

<b>Installed version</b>

```
1.73.1
```
