### ISSUE TITLE
maximumRetryAttempts can not be set to number 0

### ISSUE THREAD

**Issue by lephuongbg** [serverless/serverless#8046]
Version 1.78 allows setting `maximumRetryAttempts` directly on function config but unfortunately it doesn't accept number `0`. The config will reverts to default value of `2`. 

Workaround: Use `'0'` (string) instead of `0` (number).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test-service
provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  timeout: 20
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
functions:
  executions-run:
    handler: handler.handler
    timeout: 300
    maximumRetryAttempts: 0
```

</details>

<b>Installed version</b>

```
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.1
```
