### ISSUE TITLE
Configuration error on lambda s3 events that should work according to docs and worked in the past

### ISSUE THREAD

**Issue by mvrska** [serverless/serverless#8047]
Hi, I jsut updated from `1.74.1` to `1.78.1` and am getting the following error:
```
Serverless: Configuration error:
Serverless: - at 'functions.imagesBucket.events[0]': unrecognized property 'event'
Serverless: - at 'functions.imagesBucket.events[0]': unrecognized property 'bucket'
Serverless: - at 'functions.imagesBucket.events[0]': unrecognized property 'existing'
Serverless: - at 'functions.imagesBucket.events[1]': unrecognized property 'event'
Serverless: - at 'functions.imagesBucket.events[1]': unrecognized property 'bucket'
Serverless: - at 'functions.imagesBucket.events[1]': unrecognized property 'existing'
```
when trying to deploy my stack.

The code `serverless.yml` part in question is
```yaml
imagesBucket:
    handler: imagesBucket.handler
    events:
      - s3:
        event: s3:ObjectCreated:*
        bucket: ${self:custom.s3ImagesBucketName}
        existing: true
      - s3:
        event: s3:ObjectRemoved:*
        bucket: ${self:custom.s3ImagesBucketName}
        existing: true
```

this was working just fine for several of my projects and is according to docs:
```yaml
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: photos
          event: s3:ObjectCreated:*
      - s3:
          bucket: photos
          event: s3:ObjectRemoved:*
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: ${self:custom.serviceName}

custom:
  serviceName: ${env:APP_NAME}
  stage: ${opt:stage, self:provider.stage}
  serviceStage: ${self:custom.serviceName}-${self:custom.stage}

  s3ImagesBucketName: ${self:custom.serviceStage}-images

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:APP_STAGE, 'dev'}
  region: ${env:APP_REGION}
  endpointType: REGIONAL
  logs:
    websocket: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
        - "s3:ListObjectsV2"
      Resource:
        - !GetAtt S3BucketImages.Arn
        - !Join [ '/',[!GetAtt S3BucketImages.Arn, '*']]

  tags:
    project: ${self:custom.serviceName}

  deploymentPrefix: ${self:custom.serviceName}-serverless

  profile: ${env:AWS_PROFILE}

  versionFunctions: false

functions:
  app:
    handler: index.handler
    timeout: 20
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
  
  imagesBucket:
    handler: imagesBucket.handler
    events:
      - s3:
        event: s3:ObjectCreated:*
        bucket: ${self:custom.s3ImagesBucketName}
        existing: true
      - s3:
        event: s3:ObjectRemoved:*
        bucket: ${self:custom.s3ImagesBucketName}
        existing: true


resources:
  S3BucketImages:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3ImagesBucketName}
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
  
  ImagesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3BucketImages
        PolicyDocument:
          Statement:
            -
              Action:
                - "s3:GetObject"
                - "s3:ListBucket"
              Effect: "Allow"
              Resource:
                - !GetAtt S3BucketImages.Arn
                - !Join [ '/',[!GetAtt S3BucketImages.Arn, '*']]
              Principal: "*"
              # Condition:
              #   StringLike:
              #     aws:Referer:
              #       - "https://realinfobox.netlify.com/*"
              #       - "http://localhost/*"
  
  ImagesBucketLambdaPermissionAvatarsS3:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ImagesBucketLambdaFunction.Arn
      Principal: 's3.amazonaws.com'
      Action: 'lambda:InvokeFunction'
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn: !GetAtt S3BucketImages.Arn

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
(base) PS C:\_Data\_Work\RealInfoBox\backend\dev> serverless deploy
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - APP_NAME
Serverless:      - APP_STAGE
Serverless:      - APP_REGION
Serverless:      - ACCOUNT_ID
Serverless:      - APP_SECRET
Serverless:      - AWS_PROFILE
Serverless:      - API_URL
Serverless:      - FRONTEND_URL
Serverless:      - TABLE_THROUGHPUT_PROD
Serverless:      - TABLE_THROUGHPUT_DEFAULT
Serverless:      - S3_IMAGES_BUCKET_URL
Serverless:      - SES_EMAIL
Serverless:      - SES_DOMAIN
Serverless:      - SES_IDENTITY_ARN
Serverless:      - TEST_EMAIL
Serverless:      - SQS_MAILING_QUEUE_NAME
Serverless:      - SQS_DRIPS_QUEUE_NAME
Serverless:      - SENTRY_URL
Serverless:      - SLS_DEBUG
Serverless:      - EMAIL_WIDTH
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Configuration error:
Serverless: - at 'functions.imagesBucket.events[0]': unrecognized property 'event'
Serverless: - at 'functions.imagesBucket.events[0]': unrecognized property 'bucket'
Serverless: - at 'functions.imagesBucket.events[0]': unrecognized property 'existing'
Serverless: - at 'functions.imagesBucket.events[1]': unrecognized property 'event'
Serverless: - at 'functions.imagesBucket.events[1]': unrecognized property 'bucket'
Serverless: - at 'functions.imagesBucket.events[1]': unrecognized property 'existing'
Serverless: If you prefer to not continue when error in configuration is approached, ensure `configValidationMode: error` in your config
Serverless: If errors are influenced by an external plugin, enquiry at plugin repository so schema extensions are added (https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema)
Serverless: If errors seem invalid, please report at https://github.com/serverless/serverless/issues/new?template=bug_report.md
Serverless: If you find this functionality problematic, you may turn it off with `configValidationMode: off` setting
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service $$$$$$$$$$.zip file to S3 (43.91 MB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
............................
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: $$$$$$$
stage: v1
region: us-east-1
stack: $$$$$$$-v1
resources: 63
api keys:
  None
endpoints:
  ANY - https://$$$$$$$$$$.execute-api.us-east-1.amazonaws.com/v1/
  ANY - https://$$$$$$$$$$.execute-api.us-east-1.amazonaws.com/v1/{proxy+}
functions:
  app: $$$$$$$$$$-v1-app
  customMessage: $$$$$$$$$$-v1-customMessage
  imagesBucket: $$$$$$$$$$-v1-imagesBucket
  scheduledCampaignSender: $$$$$$$$$$-v1-scheduledCampaignSender
  scheduledDripSender: $$$$$$$$$$-v1-scheduledDripSender
  emailer: $$$$$$$$$$-v1-emailer
  dripEmailer: $$$$$$$$$$-v1-dripEmailer
  emailDelivery: $$$$$$$$$$-v1-emailDelivery
  handleAppTableEvents: $$$$$$$$$$-v1-handleAppTableEvents
layers:
  None
Serverless: Invoke aws:deploy:finalize
Serverless: Removing old service artifacts from S3...
```

</details>

<b>Installed version</b>

```
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.1
```
