### ISSUE TITLE
Object spread doesn't work out of the box (aws-nodejs-ecma-script template)

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#8060]
Object spread doesn't work out of the box.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: repro-no-obj-spread
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
    events:
      - http:
          method: get
          path: second
```

</details>

<details>
<summary><b><code>sls offline && curl http://localhost:3000/dev/second</code> output</b></summary>

```
ERROR in ./second.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: Unexpected token (13:8)
```

</details>

<b>Installed version</b>

```
Framework Core: 1.77.1
Plugin: 3.6.18
SDK: 2.3.1
Components: 2.33.0
```

<b>Reproduction</b>

https://github.com/ffxsam/repro-no-obj-spread

1. Clone repo
1. Run `yarn`
1. Run `sls offline`
1. Then `curl http://localhost:3000/dev/second`
