### ISSUE TITLE
serverless.yml validation fails for Outputs section in 1.78.0

### ISSUE THREAD

**Issue by joebernard** [serverless/serverless#8063]
`sls deploy` fails in 1.78.0 with the following error:
> Configuration error at root: unrecognized property 'outputs'

The same configuration will successfully deploy with `serverless@1.77.1`. I believe the issue has to do with [this](https://github.com/serverless/serverless/pull/7335) merge.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: myOrg
app: myApp-app

service: myApplambda

plugins:
  - serverless-plugin-split-stacks
  - serverless-appsync-plugin
  - serverless-webpack
  - serverless-plugin-aws-alerts
  - serverless-pseudo-parameters

package:
  individually: true

configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'dev'}
  role: ${output:myAppresources.LambdaExecutionRoleArn}
  profile: ${self:custom.profile.${self:provider.stage}}
  region: us-east-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  logRetentionInDays: 120
  vpc:
    securityGroupIds:
      - ${output:myAppresources.SecurityGroupDefault}
    subnetIds:
      - ${output:myAppresources.Subnet1}
      - ${output:myAppresources.Subnet2}
      - ${output:myAppresources.Subnet3}
      - ${output:myAppresources.Subnet4}
      - ${output:myAppresources.Subnet5}
      - ${output:myAppresources.Subnet6}
  environment:
    STAGE: ${self:provider.stage}

custom:
  profile:
    dev: myApp-development
    prod: myApp-production
  splitStacks:
    perFunction: true
    perType: false
  notificationEmail: me@me.com
  scheduledTasksEnabled:
    dev: true
    prod: true
  elasticsearchBatchSize: 20
  webpack:
    packager: yarn
    webpackConfig: ./webpack.config.js
  appSync:
    - ${file(serverless/authenticated-api.yml)}
    - ${file(serverless/unauthenticated-api.yml)}
functions:
  - ${file(serverless/lambdas.yml)}
layers:
  ffmpeg:
    path: src/layers
    name: ffmpeg
    description: FFMPEG for AWS Lambda
    compatibleRuntimes:
      - nodejs10.x
      - python3.6
      - ruby2.5
      - java8
      - go1.x
    licenseInfo: GPL-2.0-or-later
resources:
  Resources:
    cognitoCreateAuthChallengeTriggerPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          { Fn::GetAtt: [CognitoCreateAuthChallengeTriggerLambdaFunction, Arn] }
        Principal: cognito-idp.amazonaws.com
        SourceArn: ${output:myAppauthentication.UserPoolArn}
outputs:
  UnauthenticatedGraphQlApiArn: { Ref: myAppunauthenticatedGraphQlApi }
```

</details>

I have also tried capitalizing `Output` and moving it under `resources` as shown [here](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/). That config returns a different error under `serverless@1.78.0`:

> Error: The CloudFormation template is invalid: Template format error: Invalid outputs property : [Ref].
      at /Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13

However the docs [here](https://www.serverless.com/framework/docs/dashboard/output-variables/) show it lowercased and at the root level of the yml doc. Only `output` lowercased will work under `serverless@1.77.1`.

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
sls deploy
```

</details>

<b>Installed version</b>

```
Framework Core: 1.78.0
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.1
```

**Comment by preshetin** [comment]
> I believe the issue has to do with [this](https://github.com/serverless/serverless/pull/7335) merge.

Hi @joebernard thanks for using this new validation feature! I'm co-author of the PR. When developing @medikoo asked me to remove schema related to Outputs in https://github.com/serverless/serverless/pull/7335#discussion_r389321173 as it was considered as deprecated.

I also noticed your `serverless.yaml` contains `configValidationMode` set to `error`. So if you want not to break thinks and just report to console, just set it to `warn`.

I hope @medikoo will share his thoughts on why using Outputs in config is a deprecated

**Comment by preshetin** [comment]
@joebernard so accourding to [serverless docs](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/) Outputs should be placed under `resources` section, like this:

```
resources:
  Resources:
    cognitoCreateAuthChallengeTriggerPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          { Fn::GetAtt: [CognitoCreateAuthChallengeTriggerLambdaFunction, Arn] }
        Principal: cognito-idp.amazonaws.com
        SourceArn: ${output:myAppauthentication.UserPoolArn}
  Outputs:
    UnauthenticatedGraphQlApiArn: { Ref: myAppunauthenticatedGraphQlApi }
```

The schema for the resources section is relaxed and just requires it to be an object.

**Comment by joebernard** [comment]
@preshetin Configuring `Outputs` under `Resources` seems to be correct according to the docs [here](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/), but with that config I get a different error:

> Error: The CloudFormation template is invalid: Template format error: Invalid outputs property : [Ref].
      at /Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13

Looks like this is because `serverless@1.78.0` doesn't like this format anymore:
```yaml
Resources:
  Outputs:
    MyServiceArn: { Ref: MyServiceArn }
```
That used to work with `serverless@1.77.1`. I can only get the following format to work with `serverless@1.78.0`:
```yaml
Resources:
  Outputs:
    MyServiceArn:
      Value:
        "Ref": MyService
      Export:
        Name: MyServiceArn
```
Same output variable but much more verbose syntax. I'm not sure why this changed.

Also, I've been putting `outputs` at the root based on [this](https://www.serverless.com/blog/outputs-and-secrets) blog post. It is also documented that way [here](https://www.serverless.com/framework/docs/dashboard/output-variables#define-outputs-for-shared-services) so there is some inconsistency in the docs making this even more confusing. `outputs` at the root does work in versions before 1.78.0. 

Setting `configValidationMode: warn` still results in errors and a failed deployment. I'm only able to workaround this issue by rolling back to `serverless@1.77.1` or updating my entire config to use the new more verbose format.
