### ISSUE TITLE
AWS maximumRetryAttempts not able to set to 0

### ISSUE THREAD

**Issue by nithinvenugopal** [serverless/serverless#8065]
maximumRetryAttempts is setting AWS Lambda Retry attempts but only 1 and 2 works and not able to set this value to 0. If I set this to 0, it defaults to 2.

Expected Retry attempts value is between 0 and 2 and hence maximumRetryAttempts should take those values as well.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  test:
    handler: lambda_function.lambda_handler
    name: test-${self:provider.stage}
    timeout: 900
    maximumRetryAttempts: 0
```
