### ISSUE TITLE
Documentation error in `docs/provider/aws/events/apigateway.md#share-authorizer`

### ISSUE THREAD

**Issue by KerberosMorphy** [serverless/serverless#8078]
At Share Authorizer section the `scopes` key isn't well indented causing this error:

```text
ServerlessError: An error occurred: ApiGatewayMethodUsersPost - Value of property AuthorizerId must be of type String.
```

```diff
functions:
  createUser:
     ...
    events:
      - http:
          path: /users
          ...
          authorizer:
            # Provide both type and authorizerId
            type: COGNITO_USER_POOLS # TOKEN or REQUEST or COGNITO_USER_POOLS, same as AWS Cloudformation documentation
            authorizerId:
              Ref: ApiGatewayAuthorizer  # or hard-code Authorizer ID
# THIS
-             scopes: # Optional - List of Oauth2 scopes when type is COGNITO_USER_POOLS
-               - myapp/myscope
# SHOULD BE THAT
+           scopes: # Optional - List of Oauth2 scopes when type is COGNITO_USER_POOLS
+             - myapp/myscope
```

**Comment by medikoo** [comment]
@KerberosMorphy great thanks for reporting. PR with a fix is highly welcome!

**Comment by KerberosMorphy** [comment]
@medikoo I'll try to do a PR, never done one in another repo than my own.

**Comment by dvillarama** [comment]
Same issue for me
```
Serverless: Configuration warning:
Serverless:   at 'functions.contactsCreate.events[0].httpApi.authorizer.id': should be string
```

```
provider:
  authorizerId:.
    Fn::ImportValue: authorizerId-${self:provider.stage}
functions:
  contactsCreate:
    handler: src/routes/contacts.create
    events:
      - httpApi:
          path: /v1/accounts/{accountId}/contacts
          method: POST
          authorizer:
            id: ${self:provider.authorizerId}
```
