### ISSUE TITLE
Resource based policy incorrectly created when attaching an event brige event to a lambda

### ISSUE THREAD

**Issue by esteban-aristizabal** [serverless/serverless#8079]
When attaching an event bridge event to a lambda, the corresponding resource based policy permission in the lambda is created with an incorrect ARN. The expected resource based policy "ArnLike" should include "AWS:SourceArn": "arn:aws:events:us-east-1:412465614222:rule/usrv-analytics-qa-syncSubscription-rule-1" but it includes the "default" part: "AWS:SourceArn": "arn:aws:events:us-east-1:412465614222:rule/default/usrv-analytics-qa-syncSubscription-rule-1" so no logs are shown in the lambda that the event has been received due to the incorrect permission.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: &service
  name: usrv-analytics
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:USRV_STAGE}
  tracing: true
  timeout: 29
  stackTags:
    COST: BY TRANSACTION
    SERVICE: ALL
    INTEGRATION: KUSHKI
    ENVIRONMENT: ${ssm:/tags/environment/${self:provider.stage}}
   
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - lambda:GetFunction
        - lambda:EnableReplication
      Resource: "arn:aws:lambda:us-east-1:*:*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource:
        "Fn::GetAtt":
          - files
          - Arn
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParametersByPath
      Resource: "*"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "*"
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
          - "*"
  vpc:
    securityGroupIds:
      - ${ssm:${self:custom.prefix}/VPC_SG, env:VPC_SG}
    subnetIds:
      - ${ssm:${self:custom.prefix}/VPC_SUBNET1, env:VPC_SUBNET1}
custom:
  service: *service
  resources:
    snsFile: ${self:provider.stage}-${self:custom.service.name}-file
    s3File: ${self:provider.stage}-${self:custom.service.name}-file
  prefix: /${self:provider.stage}/${self:custom.service.name}
  #  localstack:
  #    debug: true
  #    host: http://localhost
  #    stages:
  #      - dev
  webpack:
    packager: 'npm'
    includeModules:
      forceInclude:
        - firebase-admin
        - node-redshift
        - jsonpath
      forceExclude:
        - aws-sdk
  tagEnv:
    ci: TESTING
    qa: TESTING
    uat: TESTING
    stg: TESTING
    primary: PRODUCTION
  apiGatewayTags: ${self:custom.kushkiTag}
  kushkiTag:
    COST: BY TRANSACTION
    SERVICE: ALL
    INTEGRATION: KUSHKI
    ENVIRONMENT: ${self:custom.tagEnv.${self:provider.stage}}
  cloudWatchLogsTags: ${self:custom.kushkiTag}
  customDomain:
    basePath: ${ssm:${self:custom.prefix}/BASE_PATH,env:BASE_PATH}
    domainName: ${ssm:${self:custom.prefix}/DOMAIN, env:USRV_DOMAIN}
    stage: ${self:provider.stage}
    certificateName: ${ssm:${self:custom.prefix}/CERTIFICATENAME, env:USRV_CERT}
    createRoute53Record: false
  enabledAnomalyCheck:
    ci: false
    qa: false
    uat: false
    stg: false
    primary: true
  apigwBinary:
    types:
      - 'text/plain'
  deploymentSettings:
    stages:
      - ci
      - qa
      - stg
      - uat
      - primary
    type: ${file(ServerlessScripts.js):canaryDeploymentType.${env:USRV_STAGE}}
plugins: # ${file(sls_plugins.yml):${self:custom.stage}, file(sls_plugins.yml):default}
  - serverless-webpack
  - serverless-domain-manager
  - serverless-apigw-binary
  - serverless-dynamodb-autoscaling
  - serverless-prune-plugin
  - serverless-cloudformation-resource-counter
  - serverless-tag-cloud-watch-logs
  - serverless-plugin-tracing
package:
  individually: true
  excludeDevDependencies: true
functions:
  syncSubscription:
    handler: src/handler/SyncSubscriptionHandler.HANDLER
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - "com.kushki.subscription"
            detail-type:
              - "subscription"
          inputPath: "$.detail"
    vpc:
      securityGroupIds:
        - ${ssm:${self:custom.prefix}/VPC_SG}
      subnetIds:
        - ${ssm:${self:custom.prefix}/VPC_SUBNET1}
        - ${ssm:${self:custom.prefix}/VPC_SUBNET2}
resources:
  Resources:
    GatewayResponseDefaultUNAUTHORIZED:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        StatusCode: 400
        ResponseTemplates:
          "application/json": "{\n \"message\": \"ID de comercio o credencial no válido\",\n \"code\": \"K004\" \n }"
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    files:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.resources.s3File}
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: 1
              Status: Enabled
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

![image](https://user-images.githubusercontent.com/12003255/90187730-defe1500-dd7f-11ea-9085-536780fcfed1.png)
</details>

<b>Installed version</b>

```
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.3
```
