### ISSUE TITLE
s3 provider custom cloudformation breaking changes in 1.75

### ISSUE THREAD

**Issue by herebebogans** [serverless/serverless#8081]
This is more documenting the behaviour for other people that might have this issue

In 1.74.1 the following config in provider worked to customise the cloudformation generated for a named s3 bucket with an event

```
provider:
  s3:
    bucketOne:
      name: my-custom-bucket
      VersioningConfiguration:
        Status: Enabled
```

In 1.75 with the same settings

```
 "VersioningConfiguration" is not a valid bucket property.A bucket could only be configured with the following properties:
  name, accelerateConfiguration, accessControl, analyticsConfigurations, bucketEncryption, bucketName, corsConfiguration, inventoryConfigurations, lifecycleConfiguration, loggingConfiguration, metricsConfigurations, notificationConfiguration, objectLockConfiguration, objectLockEnabled, publicAccessBlockConfiguration, replicationConfiguration, tags, versioningConfiguration, websiteConfiguration
```

changing to
```
provider:
  s3:
    bucketOne:
      name: my-custom-bucket
      versioningConfiguration:
        Status: Enabled
```

works - which the docs for s3 event do call out the need for camelCase properties.
