### ISSUE TITLE
"Error: Profile [profile] does not exist" when configuring new profile

### ISSUE THREAD

**Issue by phmasek** [serverless/serverless#8086]
Getting `Error: Profile dev does not exist` when configuring new credentials. No profiles have yet been configured, thus configuring the credentials. This is done in bitbucket pipelines for deployment. Not getting this error when a profile is already configured locally.

I understand that the `profile` parameter in the `serverless.yml` is the culprit. However, shouldn't it be possible to configure credentials although having the profile attribute set?

If I remove the `profile` attribute in the config file I will instead receive errors (with the same command) about missing credentials when serverless tries to fetch `ssm` parameters.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: reducted-service

provider:
  name: aws
  runtime: nodejs10.x
  profile: ${self:custom.profile.${opt:stage, 'local'}}
  stage: ${opt:stage, 'local'}
  region: eu-north-1
  timeout: 30
  apiKeys:
    - ${opt:stage, 'dev'}-developerKey
    - ${opt:stage, 'dev'}-reducted.seKey
  usagePlan:
    throttle:
      burstLimit: 100
      rateLimit: 50
  stackTags:
    Project: "reducted"
    deployed_by: "reducted"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:*:*:function:*-reducted"

  environment:
    ENVIRONMENT: ${self:provider.stage}
    REDUCTED_HOST: ${self:custom.reducted.host.${self:provider.stage}}
    REDUCTED_USER: ${self:custom.reducted.user.${self:provider.stage}}
    REDUCTED_PASSWORD: ${self:custom.reducted.password.${self:provider.stage}}
    REDUCTED_TOKEN: ${self:custom.reducted.token.${self:provider.stage}}
    REDUCTED_HOST: ${self:custom.reducted.host.${self:provider.stage}}
    REDUCTED_KEY: ${self:custom.reducted.apiKey.${self:provider.stage}}
    REDUCTED_HOST: ${self:custom.reducted.host.${self:provider.stage}}

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3

  customDomain:
    domainName: ${self:custom.domainName.${self:provider.stage}}
    basePath: 'reducted'
    stage: ${self:provider.stage}
    createRoute53Record: true
  
  profile:
    prod: prod
    dev: dev
    local: default

  domainName:
    prod: reducted
    dev: dev.reducted
    local: dev.reducted

  reducted:
    host:
      prod: "reducted"
      dev: ${ssm:reducted-dev}
      local: "reducted"
    user:
      prod: "reducted"
      dev: ${ssm:reducted-dev}
      local: "reducted"
    password:
      prod: 'reducted'
      dev: ${ssm:eduAdminPassword-dev~true}
      local: 'reducted'

  reducted:
    host:
      prod: 'reducted'
      dev: 'reducted'
      local: 'reducted'
    token:
      prod: 'reducted'
      dev: 'reducted' # Expiring key
      local: 'reducted'

  reducted:
    host:
      prod: 'reducted'
      dev: 'reducted'
      local: 'reducted'
    apiKey:
      prod: 'reducted'
      dev: 'reducted'
      local: 'reducted'

functions:
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - http:
          path: reducted
          method: post
          private: true
      - schedule: 
          rate: cron(15 7 ? * MON *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(0/30 5-17 ? * MON-FRI *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(5/30 5-17 ? * MON-FRI *)
          enabled: true
  reducted:
    timeout: 900
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(10/15 19-21 ? * MON-FRI *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(15 5-17 ? * MON-FRI *)
          enabled: true

  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - http:
          path: reducted
          method: post
          private: true
      - schedule: 
          rate: cron(20/30 6-16 ? * MON-FRI *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - http:
          path: reducted
          method: post
          private: true
      - schedule: 
          rate: cron(25/30 6-16 ? * MON-FRI *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - http:
          path: reducted
          method: post
          private: true
          request:
            parameters:
              paths:
                personId: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - http:
          path: reducted
          method: post
          private: true
          request:
            parameters:
              paths:
                userId: true
  reducted:
    timeout: 900
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(25/15 5-17 ? * MON-FRI *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: user
    events:
      - schedule: 
          rate: cron(30 5-17 ? * MON-FRI *)
          enabled: true

  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(35/30 5-17 ? * MON-FRI *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(40/30 5-17 ? * MON-FRI *)
          enabled: true
  reducted:
    handler: src/reducted
    tags:
      type: reducted
    events:
      - schedule: 
          rate: cron(45/30 5-17 ? * MON-FRI *)
          enabled: true

package:
  include:
    - ../node_modules/**
    - ../utils/**
  excludeDevDependencies: false
```

</details>

<details>
<summary><b><code>SLS_DEBUG=1 ./node_modules/serverless/bin/serverless.js config credentials --stage dev --profile dev --provider aws --key ${AWS_DEV_LAMBDA_KEY} --secret ${AWS_DEV_LAMBDA_SECRET}</code> output</b></summary>

```
+ SLS_DEBUG=1 ./node_modules/serverless/bin/serverless.js config credentials --stage dev --profile dev --provider aws --key ${AWS_DEV_LAMBDA_KEY} --secret ${AWS_DEV_LAMBDA_SECRET}
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command prune
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
 
  Error --------------------------------------------------
 
  Error: Profile dev does not exist
      at Object.addProfileCredentials (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:101:15)
      at AwsProvider.getCredentials (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:371:12)
      at AwsProvider.request (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:227:48)
      at Variables.getValueFromSsm (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:828:8)
      at Variables.getValueFromSource (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:577:17)
      at Variables.splitAndGet (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:445:17)
      at matches.map.match (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:382:38)
      at Array.map (<anonymous>)
      at Variables.populateMatches (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:382:20)
      at Variables.populateValue (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:413:30)
      at variables.map.variable (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:295:12)
      at Array.map (<anonymous>)
      at Variables.populateVariables (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:294:22)
      at Variables.populateObjectImpl (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:327:30)
      at prepopulateService.then (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:208:16)
  From previous event:
      at initialCall (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:207:10)
      at Variables.initialCall (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:111:12)
      at Variables.populateService (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/Variables.js:205:17)
      at Serverless.run (/opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/Serverless.js:118:27)
      at serverless.init.then (/opt/atlassian/pipelines/agent/build/node_modules/serverless/bin/serverless.js:80:26)
      at processImmediate (internal/timers.js:443:21)
      at process.topLevelDomainCallback (domain.js:136:23)
  From previous event:
      at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/serverless/bin/serverless.js:80:4)
      at Module._compile (internal/modules/cjs/loader.js:805:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
      at Module.load (internal/modules/cjs/loader.js:672:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
      at Function.Module._load (internal/modules/cjs/loader.js:604:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:868:12)
      at internal/main/run_main_module.js:21:11
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              11.13.0
     Framework Version:         1.73.1
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.31.3
```

</details>

<b>Installed version</b>

```
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.31.3
```
