### ISSUE TITLE
Failed to rename lambda function with s3-event

### ISSUE THREAD

**Issue by dazza-codes** [serverless/serverless#8090]
A lambda function rollback fails when it has an s3-event connected to an existing s3-data bucket (not the serverless deployment bucket and serverless does not manage this s3-data-bucket).  The CloudFormation (CFN) error was:

```
Failed to delete resource. User: arn:aws:sts::{ACC_ID}:assumed-role/service-IamRoleCustomResourcesLambdaExecu-1C47N98L7GNKL/service-custom-resource-existing-s3 is not authorized to perform: lambda:RemovePermission on resource: arn:aws:lambda:us-west-2:{ACC_ID}:function:service-etlLambdaFunction See details in CloudWatch Log: 2020/08/17/[$LATEST]4d0054a765a741b6ae4ce8c9812f1749
```
No idea how to find more information from the log at `2020/08/17/[$LATEST]4d0054a765a741b6ae4ce8c9812f1749`, seems to be a dangling reference.

The CFN rollback started because a new sls-deploy renames one of the lambda functions and that update did not go smoothly; it looks like the CFN state ended up with two lambda functions that both share the same s3-event, so the lambda-rename did not work as expected

```
Failed to create resource. Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type. See details in CloudWatch Log: 2020/08/17/[$LATEST]d2039e73ae4f402fa67f823707f5fdd4
```

To try to reproduce this, try to deploy a stack with a function that has an s3-event on an s3-bucket that already exists.  Then rename the function and try to redeploy the stack.  The event is something like

```
functions:
  etlConvertCsv:
    description: Convert CSV
    handler: etl/csv.lambda_handler
    events:
      - s3:
          bucket: ${self:provider.dataBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: data
            - suffix: .csv
          existing: true
```

After that is deployed, rename the function, e.g. `etlConvertCsv` -> `etlCsv`.  Then redeploy the stack.  If the sequence of the function rename is somehow dependent on something else for the s3-data-bucket that is `existing`, it might be messed up.  (Sorry, don't have time to reproduce this exactly; startup work is a higher priority...)

<b>Installed version</b>

```
$ serverless --version
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.3
```
