### ISSUE TITLE
Serverless.yml package exclude does not work

### ISSUE THREAD

**Issue by lbittner-pdftron** [serverless/serverless#8093]
Hi there!

I am trying to exclude files from a certain function using the `exclude` functionality on a per function basis. However, it seems like this setting is completely ignored.

Using the serverless config below, my `merge` deployment contains `/lib/linux`, which is expected, but the `auth` package also contains `/lib/linux` even though it is excluded. Ive tried every variation of glob patterns and ignore/include combos I can think of, but I cannot get this to work.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: ...

package:
  individually: true
  include:
    - keys/**
    - lib/linux/**
  exclude:
    - node_modules/aws-sdk/**
    
custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    ENV:
      production: "production"
      staging: "staging"
  myBuckets:
    ENV:
      staging: ... 
      production: ...
provider:
  name: aws
  runtime: nodejs10.x

functions:
  merge:
    handler: services/merge/handler.handle
    environment:
      ENV: ${self:custom.myEnvironment.ENV.${self:custom.myStage}}
    events:
      - http:
          path: /xfdf/merge
          method: post
          cors: true
  auth:
    handler: services/auth/handler.handle
    package:
      exclude:
        - node_modules/**
        - keys/**
        - lib/linux/**
    events:
      - cloudFront:
          eventType: viewer-request
          origin:
            DomainName: ${self:custom.myBuckets.ENV.${self:custom.myStage}}
            S3OriginConfig:
              OriginAccessIdentity: ...
          behavior:
            ForwardedValues:
              QueryString: true
              Headers:
                - 'Access-Control-Request-Headers'
                - 'Access-Control-Request-Method'
                - 'Origin'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
```

</details>

I am deploying using `sls deploy --stage staging`. The output is normal.

<b>Installed version</b>

```
$ sls --version
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.5
```

**Comment by lbittner-pdftron** [comment]
Hi,

I managed to get it working by doing 

```yml
  auth:
    handler: services/auth/handler.handle
    package:
      include:
        - '!lib/**'
```
I'm not sure if `exclude` is supposed to work or not. If this is expected behaviour, you can close this ticket.

Thanks,
Logan

**Comment by medikoo** [comment]
@lbittner-pdftron thanks for report

This is a packaging logic design issue. Firstly global and individual rules for _include_ and _exclude_ are concatanated together. Then first _exclude_ and after that _include_ rules are applied. Hence in your case _global_ `lib/linux/**` include shadows _individual_ `lib/linux/**` exclude rule.

I believe right fix for that is to:

1. Replace `include` and `exclude` with single `patterns` rules set (better name welcome), then in one list we can setup both _include_ and _exclude_ rules as follows:

```yaml
package:
  patterns:
    - "includePath/**"
    - "!excludePath/**"
```

2. Ensure that _individual_ rules take priority over _global_ so e.g. _global `lib/**` will be shadowed by local `!lib/**`

--- 

This should be implemented in two phases

1. In first phase we support both ways (`include` and `exclude`) and `patterns` (we should crash if both are used), and we show a [deprecation notice](https://github.com/serverless/serverless/blob/master/CONTRIBUTING.md#configuring-deprecations) if `include` or `exclude` is used
2. With new major we remove support for `include` and `exclude`.

PR is welcome!
