### ISSUE TITLE
MSK support as an event to trigger Lambdas

### ISSUE THREAD

**Issue by safv12** [serverless/serverless#8117]
Lambda now supports Amazon MSK as an event source, so it can consume messages and integrate with downstream serverless workflows. It will be great to have a Kafka event to trigger the functions from serverless.

https://aws.amazon.com/es/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/

### Proposed solution

(_Updated on the go, to reflect final agreement_):

Event name `msk`, with support for following properties:
- `batchSize`: _optional_, maps to `BatchSize`
- `arn`: _required_, maps to `EventSourceArn`
- `enabled`: _optional_, maps to `Enabled`
- `startingPosition`: _optional_ (but _required_ in AWS), maps to `StartingPosition` with default set to `TRIM_HORIZON`
- `topic`: _required_ (technically _optional_ in AWS, but it's due to implied support for other stream sources), maps to `Topics[0]`

**Comment by medikoo** [comment]
@safv12 thanks for proposal. We're definitely open for that.

Can you outline how kafka event properties will translate to CloudFormation template? Are those listed properties the only properties we intend to support?

**Comment by pgrzesik** [comment]
Hello team :wave: I was recently looking at how it's supported at CloudFormation level and how well that could fit into what is already supported by Serverless Framework. Underneath, it's using the same `EventSourceMapping` resource that is already in use for `sqs` and `stream` events (reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html). Additional available property for MSK is `Topics` used to specify the Kafka topic(s). Given that, we could follow a convention like this:

```
functions:
  compute:
    handler: handler.compute
    events:
      - msk:
          arn: arn:aws:kafka:region:XXXXXX:Cluster/xxx
          topic: kafka-topic
          startingPosition: LATEST
          batchSize: 1000
```

`msk` can be replaced by `kafka` in my opinion as well.
