### ISSUE TITLE
AWS (existing) Cognito User Pool Event Source not attaching with right provisioned Concurrency Lambda Alias

### ISSUE THREAD

**Issue by hoonoh** [serverless/serverless#8128]
Functions with `provisionedConcurrency` with (existing) `cognitoUserPool` event are not being mapped to provisioned alias.
This is mostly identical with #7802, and similar with #7371,#7726 and #7285.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
  authCognitoPreTokenGen:
    layers:
      - ${ssm:/${self:provider.stage}/layers/common/latest/arn}
    handler: src/auth/cognito-pre-token-generation.handler
    provisionedConcurrency: 1
    events:
      - cognitoUserPool:
          pool: ${self:custom.cognitoUserPool.name}
          existing: true
          trigger: PreTokenGeneration
```

</details>

<b>Installed version</b>

```
Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.7
```
