### ISSUE TITLE
Configuration warning when using Cloudformation intrinsic function in authorizers 

### ISSUE THREAD

**Issue by lephuongbg** [serverless/serverless#8135]
The cloudformation output is fine so there shouldn't be warning if we use CF `Ref` or `GetAtt` function at `issuerUrl` or `audience`.

```yaml
    authorizers:
      jwt:
        identitySource: $request.header.Authorization
        issuerUrl: !Ref JWTIssuerUrl
        audience: !Ref JWTAudience
```

```
Serverless: Configuration warning:
Serverless:   at 'provider.httpApi.authorizers.jwt.issuerUrl': should be string
Serverless:   at 'provider.httpApi.authorizers.jwt.audience': unsupported configuration format
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: fmi-registration

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  httpApi:
    payload: '1.0'
    authorizers:
      jwt:
        identitySource: $request.header.Authorization
        issuerUrl: !Ref JWTIssuerUrl
        audience: !Ref JWTAudience

functions:
  api:
    handler: handler.index
    timeout: 15
    events:
      - httpApi:
          method: '*'
          path: '/private/{proxy+}'
          authorizer:
            name: jwt
    maximumRetryAttempts: 0

resources:
  Parameters:
    JWTAudience:
      Type: String
      Default: http://api
    JWTIssuerUrl:
      Type: String
      Default: https://tenant.auth0.com/
```

</details>

<b>Installed version</b>

```
Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.6
```
