### ISSUE TITLE
When providing an arns as role, a depends on IamRoleLambdaExecution is generated for lamdbda's that have sqs or dynamodb streams as event

### ISSUE THREAD

**Issue by devnoo** [serverless/serverless#8150]
When I want to reuse an existing role for the functions, or a role comming from a nested stack on which i do an !GetAtt, the generation of the eventmappings seems to break.
  "*SourceMappingDynamodbCommon": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": "IamRoleLambdaExecution",

During cloudformation validation this will give the error that iamrolelambdaexecution does not exist.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: service-name

provider:
  configValidationMode : warn
  name: aws
  runtime: python3.8
  memorySize: 128
  
  role: '{{existing role arn}}'
## deploy it in our vpc
functions:
  at_listener:
    handler: src.sync.at_listener.handle
    role:  bla
    events:
      - sqs:
          arn: '{{existing queue arn}}'
          batchSize: 1

plugins:
  - serverless-aws-nested-stacks
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-deployment-bucket
  - serverless-dynamodb-local
  - serverless-reqvalidator-plugin

resources:
#  TODO due to bug in serverless

#  DH::Dummy::IamRoleLambdaExecution
#  - ${file(./cf_templates/data.yml)}
#  - ${file(./cf_templates/sqs.yml)}
#  - ${file(./cf_templates/tables.yml)}
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```
  Error --------------------------------------------------
 
  Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [IamRoleLambdaExecution] in the Resources block of the template
      at provider.request.catch.error (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13)
  From previous event:
      at AwsDeploy.validateTemplate (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:16:85)
  From previous event:
      at AwsDeploy.BbPromise.bind.then (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:119:39)
  From previous event:
      at Object.aws:deploy:deploy:validateTemplate [as hook] (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:115:30)
      at BbPromise.reduce (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:498:55)
  From previous event:
      at PluginManager.invoke (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at PluginManager.spawn (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:518:17)
      at AwsDeploy.BbPromise.bind.then (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:93:48)
  From previous event:
      at Object.deploy:deploy [as hook] (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:89:30)
      at BbPromise.reduce (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:498:55)
  From previous event:
      at PluginManager.invoke (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:498:22)
      at getHooks.reduce.then (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:533:24)
  From previous event:
      at PluginManager.run (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:533:8)
      at variables.populateService.then (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/Serverless.js:136:33)
  From previous event:
      at Serverless.run (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/lib/Serverless.js:123:74)
      at serverless.init.then (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/scripts/serverless.js:54:26)
      at runCallback (timers.js:694:18)
      at tryOnImmediate (timers.js:665:5)
      at processImmediate (timers.js:647:5)
      at process.topLevelDomainCallback (domain.js:121:23)
  From previous event:
      at Object.<anonymous> (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/scripts/serverless.js:54:4)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at Object.<anonymous> (/Users/job/.nvm/versions/node/v10.10.0/lib/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
      at startup (internal/bootstrap/node.js:279:19)
      at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

</details>

<b>Installed version</b>

```
Framework Core: 1.80.0
Plugin: 3.8.1
SDK: 2.3.1
Components: 2.34.9
```

**Comment by medikoo** [comment]
@devnoo this looks as issue on plugin side (most likely `serverless-aws-nested-stacks`), can you please report it at its repository?

If you strongly believe there's some issue in core, please update the reproducible test case to not have any plugins involved.

**Comment by devnoo** [comment]
well it seems that it is in the aws provider, at least they can't fix it without it i think.

in this function:
`resolveFunctionIamRoleResourceName(functionObj) {
    const customRole = functionObj.role || this.serverless.service.provider.role;
    if (customRole) {
      if (typeof customRole === 'string') {
        // check whether the custom role is an ARN
        if (customRole.includes(':')) return null;
        return customRole;
      }
      if (
        // otherwise, check if we have an in-service reference to a role ARN
        customRole['Fn::GetAtt'] &&
        Array.isArray(customRole['Fn::GetAtt']) &&
        customRole['Fn::GetAtt'].length === 2 &&
        typeof customRole['Fn::GetAtt'][0] === 'string' &&
        typeof customRole['Fn::GetAtt'][1] === 'string' &&
        customRole['Fn::GetAtt'][1] === 'Arn'
      ) {
        return customRole['Fn::GetAtt'][0];
      }
      if (
        // otherwise, check if we have an import or parameters ref
        customRole['Fn::ImportValue'] ||
        customRole.Ref
      ) {
        return null;
      }
    }
    return 'IamRoleLambdaExecution';
  }`
if you use a getatt without arn as the second argument like you would do with an output of a nested stack, it will return IamRoleLambaExecution.
So it will happen when you have   role: !GetAtt Common.Outputs.LambdaRoleArn as role.
I would maybe not cal it a bug, but it does not allow for using a nested stack output as a role either.

i would expect that if i pass a getatt it would return that
the compile stream now gets back IamRoleLambdaExecution while the rest of serverless picks ups the output and uses the role.
I worked around it by having an IamRoleLambdaExecution resource that is just a dummy custom resource.

**Comment by medikoo** [comment]
@denvo function you're referring was introduced with v1.81, while you report against v1.80.

Again, we need a valid bug report to be able to reason about. Can you update description with respect to all bug template remarks?

**Comment by MatthewDahl** [comment]
I was able to reproduce this exact issue without any plugins. I've included the `serverless.yml` and the resulting cloudformation when using `sls package --stage test`. We can see that there is a `DependsOn` reference to `IamRoleLambdaExecution`, but no resource by that name.

<details>
  <summary><code>serverless.yml</code></summary>
  
  ```yaml
  service: example-function
  
  useDotenv: true
  
  provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-west-2'}
  
    iam:
      role: !Sub arn:aws:iam::${AWS::AccountId}:role/${env:IAM_ROLE_NAME}
  
  functions:
    exampleFunction:
      handler: src/handler.exampleFunction
      name: ${self:service}-${self:provider.stage}
      timeout: 60
      events:
        - sqs:
            arn:
              !Join 
                - ':'
                - - 'arn:aws:sqs'
                  - !Ref AWS::Region
                  - !Ref AWS::AccountId
                  - ${env:SQS_NAME}-${self:provider.stage}
            batchSize: 1
  ```
</details>

<details>
  <summary><code>cloudformation-template-update-stack.json</code></summary>
  
  ```json
  {
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "The AWS CloudFormation template for this Serverless application",
    "Resources": {
      "ServerlessDeploymentBucket": {
        "Type": "AWS::S3::Bucket",
        "Properties": {
          "BucketEncryption": {
            "ServerSideEncryptionConfiguration": [
              {
                "ServerSideEncryptionByDefault": {
                  "SSEAlgorithm": "AES256"
                }
              }
            ]
          }
        }
      },
      "ServerlessDeploymentBucketPolicy": {
        "Type": "AWS::S3::BucketPolicy",
        "Properties": {
          "Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "PolicyDocument": {
            "Statement": [
              {
                "Action": "s3:*",
                "Effect": "Deny",
                "Principal": "*",
                "Resource": [
                  {
                    "Fn::Join": [
                      "",
                      [
                        "arn:",
                        {
                          "Ref": "AWS::Partition"
                        },
                        ":s3:::",
                        {
                          "Ref": "ServerlessDeploymentBucket"
                        },
                        "/*"
                      ]
                    ]
                  },
                  {
                    "Fn::Join": [
                      "",
                      [
                        "arn:",
                        {
                          "Ref": "AWS::Partition"
                        },
                        ":s3:::",
                        {
                          "Ref": "ServerlessDeploymentBucket"
                        }
                      ]
                    ]
                  }
                ],
                "Condition": {
                  "Bool": {
                    "aws:SecureTransport": false
                  }
                }
              }
            ]
          }
        }
      },
      "ExampleFunctionLogGroup": {
        "Type": "AWS::Logs::LogGroup",
        "Properties": {
          "LogGroupName": "/aws/lambda/example-function-test"
        }
      },
      "ExampleFunctionLambdaFunction": {
        "Type": "AWS::Lambda::Function",
        "Properties": {
          "Code": {
            "S3Bucket": {
              "Ref": "ServerlessDeploymentBucket"
            },
            "S3Key": "serverless/example-function/test/1621365849933-2021-05-18T19:24:09.933Z/example-function.zip"
          },
          "Handler": "src/handler.exampleFunction",
          "Runtime": "nodejs12.x",
          "FunctionName": "example-function-test",
          "MemorySize": 1024,
          "Timeout": 60,
          "Role": {
            "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/swiftterm-generic-lambda-execution-role-all"
          }
        },
        "DependsOn": [
          "ExampleFunctionLogGroup"
        ]
      },
      "ExampleFunctionLambdaVersionlCitXwZr9KJDdXkcqntXMxz6PetIfKWJ33rkJBHjnA": {
        "Type": "AWS::Lambda::Version",
        "DeletionPolicy": "Retain",
        "Properties": {
          "FunctionName": {
            "Ref": "ExampleFunctionLambdaFunction"
          },
          "CodeSha256": "ZURCjjYlnUt1GEowM0kTfvBOtv7u8BgvVLHzWeHdVFY="
        }
      },
      "ExampleFunctionEventSourceMappingSQSSwifttermschedulessqstest": {
        "Type": "AWS::Lambda::EventSourceMapping",
        "DependsOn": [
          "IamRoleLambdaExecution"
        ],
        "Properties": {
          "BatchSize": 1,
          "EventSourceArn": {
            "Fn::Join": [
              ":",
              [
                "arn:aws:sqs",
                {
                  "Ref": "AWS::Region"
                },
                {
                  "Ref": "AWS::AccountId"
                },
                "swiftterm-schedules-sqs-test"
              ]
            ]
          },
          "FunctionName": {
            "Fn::GetAtt": [
              "ExampleFunctionLambdaFunction",
              "Arn"
            ]
          },
          "Enabled": true
        }
      }
    },
    "Outputs": {
      "ServerlessDeploymentBucketName": {
        "Value": {
          "Ref": "ServerlessDeploymentBucket"
        },
        "Export": {
          "Name": "sls-example-function-test-ServerlessDeploymentBucketName"
        }
      },
      "ExampleFunctionLambdaFunctionQualifiedArn": {
        "Description": "Current Lambda function version",
        "Value": {
          "Ref": "ExampleFunctionLambdaVersionlCitXwZr9KJDdXkcqntXMxz6PetIfKWJ33rkJBHjnA"
      },
      "Export": {
        "Name": "sls-example-function-test-ExampleFunctionLambdaFunctionQualifiedArn"
      }
    }
  }
}
  ```
</details>
