### ISSUE TITLE
ServerlessError: Configuration error at 'functions.E2E.events[0]': unrecognized property 'rate'

### ISSUE THREAD

**Issue by adilev26** [serverless/serverless#8162]
failed to deploy schedule rule, validation failed in 1.80.0.
tried to deploy in 1.77.1 and did not fail on validation but rule and lambda trigger did not deploy.

get message : 
ServerlessError: Configuration error at 'functions.E2E.events[0]': unrecognized property 'rate'

<details>
<summary><code>serverless.yml</code></summary>

```yaml
  E2E:
    handler: someHandler
    package:
      individually: true
      artifact: someArtifact
    events:
      - schedule:
        name: ${ssm:/Lambda/event_bridge_rule_name~true}
        rate: cron(1 1 1 1 ? 1970)

    vpc:
      securityGroupIds:
        - ${ssm:/Lambda/security_group~true}
      subnetIds:
        - ${ssm:/Lambda/vpc_subnet~true}

```

</details>

<details>
<summary><b><code>serverless print --stage testing --verbose</code> output</b></summary>

```
Serverless: Load command studio
Serverless: Load command dev
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Configuration error: 
       at 'functions.E2E.events[0]': unrecognized property 'name'
       at 'functions.E2E.events[0]': unrecognized property 'rate'
       at 'functions.E2E.events[0]': unrecognized property 'name'
       at 'functions.E2E.events[0]': unrecognized property 'rate'
      at ConfigSchemaHandler.handleErrorMessages (/usr/local/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js:78:15)
      at ConfigSchemaHandler.validateConfig (/usr/local/lib/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js:66:12)
      at Service.validate (/usr/local/lib/node_modules/serverless/lib/classes/Service.js:200:43)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:133:20
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:123:74)
      at /usr/local/lib/node_modules/serverless/scripts/serverless.js:54:26
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/scripts/serverless.js:54:4)
      at Module._compile (internal/modules/cjs/loader.js:1075:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
      at Module.load (internal/modules/cjs/loader.js:940:32)
      at Function.Module._load (internal/modules/cjs/loader.js:781:14)
      at Module.require (internal/modules/cjs/loader.js:964:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:1075:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
      at Module.load (internal/modules/cjs/loader.js:940:32)
      at Function.Module._load (internal/modules/cjs/loader.js:781:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
      at internal/main/run_main_module.js:17:47
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.9.0
     Framework Version:         1.78.0
     Plugin Version:            3.8.2
     SDK Version:               2.3.1
     Components Version:        2.34.9
```

</details>

<b>Installed version</b>

```
1.80.0
```
