### ISSUE TITLE
EFS throws a warning when it shouldn't (I think)

### ISSUE THREAD

**Issue by jliebrand** [serverless/serverless#8189]
I am using the new support for EFS. Another stack outputs the ARN of the EFS and I use it as follows

```
functions:
  myLambda:
    handler: src/main.something
    fileSystemConfig:
      localMountPath: /mnt/efs
      arn:
        'Fn::ImportValue': ${self:custom.stage}-my-efs-access-point-arn

```

While this works, it throws the following warning during deploy:

```
Serverless: Configuration warning at 'functions.myLambda.fileSystemConfig.arn': should be string
```

Looks like the validation doesn't realise values can be imported?
