### ISSUE TITLE
Puts invalid comment to created CF distribution

### ISSUE THREAD

**Issue by whitecolor** [serverless/serverless#8194]
It puts `dev` comment where should be `prod`

![image](https://user-images.githubusercontent.com/736697/92328869-435d7d00-f07d-11ea-9d68-82d42d8400bd.png)

![image](https://user-images.githubusercontent.com/736697/92328864-2759db80-f07d-11ea-9094-ad8caff3317b.png)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: serverless-route

provider:
  name: aws
  runtime: nodejs12.x

functions:
  routeCharta:
    handler: routeRequest.handleRequest
    events:
      - cloudFront:
          eventType: viewer-request
          origin: ...

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          PriceClass: PriceClass_100
          # Aliases:
          #   - staging.charta.life
          ViewerCertificate:
            AcmCertificateArn:...
            SslSupportMethod: sni-only
          DefaultRootObject: 'index.html'
          DefaultCacheBehavior:
            Compress: true

plugins:
  - serverless-plugin-typescript
```

</details>

<b>Installed version</b>

```
Framework Core: 1.82.0
Plugin: 3.8.3
SDK: 2.3.1
Components: 2.34.9

```
