### ISSUE TITLE
Delete protection does not appear in console

### ISSUE THREAD

**Issue by joker-8989** [serverless/serverless#8197]
After upgrading serverless to the latest I have set delete protection on the DB but it doesn't show up in the console.

Curiously, the console doesn't seem to be delete protected in the notation, but the resource remains when you actually remove it.

```    
DBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: "100"
        AllowMajorVersionUpgrade: false
        AutoMinorVersionUpgrade: false
        BackupRetentionPeriod: "7"
        CopyTagsToSnapshot: true
        DBInstanceIdentifier:
          Ref: AWS::StackName
        DBInstanceClass: db.t2.micro
        DBParameterGroupName:
          Ref: DBParameterGroup
        DBSubnetGroupName:
          Fn::ImportValue: xxxxxx-DbSubnetGroup
        Engine: postgres
        EngineVersion: 11
        DBName: TestDB
        MasterUsername: Test
        MasterUserPassword: Test0000
        MultiAZ: true
        Port: "5432"
        PubliclyAccessible: false
        StorageType: gp2
        Tags:
        - Key: Name
          Value:
            Ref: AWS::StackName
        VPCSecurityGroups:
        - Fn::ImportValue: xxxxxx-DefaultSecurityGroup
      DeletionPolicy: Retain
```

The environment is as follows.
```
Node: v12.18.3
Serverless: 1.82.0
```
