### ISSUE TITLE
Configuration warning at 'plugins': should be array when using Enhanced Object

### ISSUE THREAD

**Issue by aykutaras** [serverless/serverless#8206]
When we specify enhanced object in plugins declaration, serverless gives that warning which is misleading. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: serverless-example

plugins:
  localPath: '../somedir/plugindir'
  modules:
    - serverless-plugin-tracing
    - serverless-webpack
    - serverless-offline
    - some-local-plugin

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello

```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
Serverless: Configuration warning at 'plugins': should be array
Serverless:
Serverless: If you prefer to not continue ensure "configValidationMode: error" in your config
Serverless: If errors are influenced by an external plugin, enquiry at plugin repository so schema extensions are added (https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema)
Serverless: If errors seem invalid, please report at https://github.com/serverless/serverless/issues/new?template=bug_report.md
Serverless: If you find this functionality problematic, you may turn it off with "configValidationMode: off" setting
Serverless:
Serverless: Bundling with Webpack...
```

</details>

<b>Installed version</b>

```
Framework Core: 1.81.1 (local)
Plugin: 3.8.2
SDK: 2.3.1
Components: 2.34.9
```
