### ISSUE TITLE
ec2:DescribeSecurityGroups permissions error for VPC Security Group

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#8209]
Trying to deploy a lambda into an existing VPC and getting the error below. Says my OnboardLambdaFunction doesn't have permissions to DescribeSecurityGroups. I've tried removing the vpc config and deploying just the policy first but no luck.

```
Your access has been denied by EC2, please make sure your request credentials have permission to DescribeSecurityGroups for sg-xxxx. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation. (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: fd8a2f09-0101-4d97-97fb-eae502816edf; Proxy: null)
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

provider:
  name: aws
  region: us-east-2
  runtime: nodejs12.x
  stage: dev
  
functions:
  onboard:
    handler: api/onboard.onboard
    description: POST /api/onboard
    role: lambdaOnboard
    vpc:
      securityGroupIds:
        - ${self:custom.vpc.securityGroupId.${self:provider.stage}}
      subnetIds:
        - ${self:custom.vpc.subnetId1.${self:provider.stage}}
        - ${self:custom.vpc.subnetId2.${self:provider.stage}}
        - ${self:custom.vpc.subnetId3.${self:provider.stage}}
    events: ...

resources:
  Resources:                        
    lambdaOnboard:
      Type: AWS::IAM::Role
      Properties:
        RoleName: lambdaOnboard
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: lambdaOnboardPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/${self:service}-${self:provider.stage}-onboard:*:*'
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DescribeSecurityGroups
                  Resource: '*'

# custom configs
custom:
  acctID: ${file(./env/vars.js):getAccountId}
  vpc:
    securityGroupId:
      prod: sg-xxxx
      dev: sg-xxxx
    subnetId1:
      prod: subnet-xxxx
      dev: subnet-xxxx
    subnetId2:
      prod: subnet-xxxx
      dev: subnet-xxxx
    subnetId3:
      prod: subnet-xxxx
      dev: subnet-xxxx

# third party plugins
plugins:
  - serverless-iam-roles-per-function
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
ServerlessError: An error occurred: OnboardLambdaFunction - Your access has been denied by EC2, please make sure your request credentials have permission to DescribeSecurityGroups for sg-xxxx. EC2 Error Code: UnauthorizedOperation. EC2 Error Message: You are not authorized to perform this operation. (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: fd8a2f09-0101-4d97-97fb-eae502816edf; Proxy: null)
```

</details>

<b>Installed version</b>

```
1.82.0
```
