### ISSUE TITLE
NODE_EXTRA_CA_CERTS not being read

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#8232]
I have a Certificate Authority file (.pem) that i'm bundling with my lambda and I have added the `NODE_EXTRA_CA_CERTS` to my environment variables with the path to the cert file. Unfortunately, when i make my requests back to my on-prem server, node is giving the following error:
```
UNABLE_TO_GET_ISSUER_CERT_LOCALLY
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  region: us-east-2
  runtime: nodejs12.x
  endpointType: regional
  stage: dev
  environment:
    S3_ARTIFACTS: sast-artifacts
    NODE_EXTRA_CA_CERTS: /var/task/.certs/My-Root-CA.pem
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
UNABLE_TO_GET_ISSUER_CERT_LOCALLY
```

</details>

<b>Installed version</b>

```
1.83.0
```
