### ISSUE TITLE
Lambda Deployment Package and Serverless Package do not include same folders

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#8252]
When viewing the contents of my serverless package in `.serverless/my-service.zip`, it includes all files/folders not in my exclude block. However, when i export my lambda deployment package in AWS, a `config` folder and its files are missing.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

provider:
  name: aws
  region: us-east-2
  runtime: nodejs12.x
  endpointType: regional
  stage: dev
  environment:
    NODE_EXTRA_CA_CERTS: /var/task/certs/my-cert.pem
  logs:
    restApi: true
  logRetentionInDays: 14

functions:
  onboard:
    handler: api/onboard.onboard
    description: POST /my/api/onboard
    vpc:
      securityGroupIds:
        - ${self:custom.vpc.securityGroupId.${self:provider.stage}}
      subnetIds:
        - ${self:custom.vpc.subnetId1.${self:provider.stage}}
        - ${self:custom.vpc.subnetId2.${self:provider.stage}}
        - ${self:custom.vpc.subnetId3.${self:provider.stage}}
    layers:
      - my-layers-arn
    events:
      - http:
          path: /onboard
          method: post
          cors: true
          integration: lambda
          request:
            passThrough: NEVER
            schema:
              application/json: ${file(models/onboard.schema.json)}
            template:
              application/json: $input.body
          response:
            statusCodes:
              200:
                pattern: ''
              400:
                pattern: '.*"400".*'
                template: ${file(resources/error-response-template.yml)}
              401:
                pattern: '.*"401".*'
                template: ${file(resources/error-response-template.yml)}

# custom configs
custom:
  acctID: ${file(./env/vars.js):getAccountId}
  vpc:
    securityGroupId:
      prod: xxxx
      dev: xxxx
    subnetId1:
      prod: xxxx
      dev: xxxx
    subnetId2:
      prod: xxxx
      dev: xxxx
    subnetId3:
      prod: xxxx
      dev: xxxx

# exclude the code coverage files and circle ci files
package:
  include:
    - config
    - config/**
  exclude:
    - .circleci/**
    - .git/**
    - coverage/**
    - .gitignore
    - .jshintrc
    - '**/*.test.js'
    - '*.tf'
    - package.json
    - package-lock.json
    - README.md
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
sls package
```

</details>

<b>Installed version</b>

```
1.82.0
```
