### ISSUE TITLE
Provisioned Concurrency should allow for zero to be set, to enable per environment configuration

### ISSUE THREAD

**Issue by claydanford** [serverless/serverless#8253]
### Use case description

Currently provisioned concurrency cannot be set to `0` even if I want environment/stage specific configuration. We should allow `0` so in lower environments PC is disabled but enabled in higher environments.

### Proposed solution

```javascript
if (shouldVersionFunction || functionObject.provisionedConcurrency && functionObject.provisionedConcurrency > 0) {}
```

**Comment by medikoo** [comment]
@claydanford Doesn't `0` translate to _no provisioned concurrency_ ? Why not removing this setting if we're not after securing provisioned concurrency?

**Comment by claydanford** [comment]
@medikoo Here is my situation:

**dev:**

```yaml
functions:
  hello:
    provisionedConcurrency: 0
```

**prod:**

```yaml
functions:
  hello:
    provisionedConcurrency: 1
```

To achieve I could easily pull from another file or ssm:

```yaml
functions:
  hello:
    provisionedConcurrency: ${file(${self:provider.stage}.json):provisionedConcurrency}
```

But since I cannot set zero I cannot use zero in the file, which leads to this ugly solution, moving all of the function configuration to a custom block. Note, many lines of configuration are missing but would look much worse and be harder to work with.

```yaml
functions:
  hello: ${self:custom.functions.${self:provider.stage}.hello}

custom:
  functions:
    dev:
      hello:
    prod:
      hello:
        provisionedConcurrency: 1
```

Another ugly example:

```yaml
functions:
  hello: ${self:custom.functions.${self:provider.stage}.hello}

custom:
  functions:
    dev:
      hello:
        handler: src/handler.hello
        events:
          - http:
              path: v1/hello
              method: GET
              cors: true
    prod:
      hello:
        handler: src/handler.hello
        provisionedConcurrency: 1
        events:
          - http:
              path: v1/hello
              method: GET
              cors: true
```

As you can see when you have multiple stages and multiple functions this is extremely difficult to work with.
