### ISSUE TITLE
Configuration validation warning for eventBridge trigger

### ISSUE THREAD

**Issue by revbingo** [serverless/serverless#8264]
I have the following in my serverless.yml

```
  events-consumer:
    handler: src/event/handlers.consumer
    environment:
      <<: *dbEnv
      STAGE: ${self:provider.stage}
    events:
      - sns:
          arn:
            Fn::ImportValue: events-${self:provider.stage}-consumer
          topicName: events-${self:provider.stage}-consumer
      - eventBridge:
          eventBus: ${self:custom.events.eventBus}
          pattern:
            source:
              - consumer
          inputTransformer:
            inputPathsMap:
              deviceId: $.detail.deviceId
              message: $.detail.message
              timestamp: $.detail.timestamp
              organisation: $.detail.organisation
              status: $.detail.status
              record: $.detail.record
              payload: $.detail.payload
            inputTemplate: '{ "deviceId": <deviceId>, "message": <message>, "timestamp": <timestamp>, "organisation": <organisation>, "status": <status>, "record": <record>, "payload": <payload> }'
```

After upgrading from 1.67 to 1.83, the configuration validator is giving a warning

`Serverless:   at 'functions['events-consumer'].events[1].eventBridge': unsupported configuration format`

However, the configuration still works as expected and correctly creates the EventBridge trigger for my lambda function.

Is this simply something missing from the schema definition?
