### ISSUE TITLE
redrivePolicy with deadLetterTargetArn for SNS events failed to create AWS::SQS::QueuePolicy

### ISSUE THREAD

**Issue by 5up3r20e** [serverless/serverless#8267]
redrivePolicy with deadLetterTargetArn for SNS events failed to create AWS::SQS::QueuePolicy

i found an existent issue but it's already closed https://github.com/serverless/serverless/issues/7745
* linked code, refer to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html aws cloudformation document, you can see the usage here is a bug
https://github.com/serverless/serverless/blob/e1ca63c06a824e18fdd92f5c6c3efbf7f5f644d2/lib/plugins/aws/package/compile/events/sns/index.js#L119-L125

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
 handleUserAuthenticated:
    handler: handler.handleUserAuthenticated
    events:
      - sns:
          arn: <snsTopicArn>
          redrivePolicy:
            deadLetterTargetArn: arn:aws:sqs:ap-southeast-2:<accountid>:myDLQ
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Error: The CloudFormation template is invalid: Template error: every Fn::Join object requires two parameters, (1) a string delimiter and (2) a list of strings to be joined or a function that returns a list of strings (such as Fn::GetAZs) to be joined.
```

</details>

<b>Installed version</b>

```
Framework Core: 2.1.1 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.3
```
