### ISSUE TITLE
cognitoUserPool Function Events Refers to pools as "Pool" not "ARN", "Name", "Id"

### ISSUE THREAD

**Issue by colinbjohnson** [serverless/serverless#8269]
When using a cognitoUserPool event within a function, the property used to refer to a User Pool resource is called a "pool". This creates a lack of clarity when configuring an event.

- AWS documentation refers to `cognitoUserPool` resources by either Arn ([as a CloudFormation Output](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html)) or Id ([as a CloudFormation Output](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html)) or PoolName or UserPoolName ([as a CloudFormation Property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-userpoolname)).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: service

provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
  stage: ${opt:stage}

functions:
  functionname:
    handler: function.handler
    events:
      - cognitoUserPool:
          existing: true
          # pool is ambiguous in meaning
          pool: poolname
          trigger: UserMigration
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
colinjohnson@cjohnson07 lambdas % serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service service.zip file to S3 (1.11 KB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......
Serverless: Stack update finished...
Service Information
service: service
stage: dev
region: us-west-2
stack: auth-dev
resources: 9
api keys:
  None
endpoints:
  None
functions:
  function
layers:
  None
Serverless: Removing old service artifacts from S3...

```

</details>

<b>Installed version</b>

```
Framework Core: 2.1.1
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.3
```
