### ISSUE TITLE
vpc.securityGroupIds and vpc.subnetIds only allow string, warn on Ref

### ISSUE THREAD

**Issue by devpow112** [serverless/serverless#8282]
Before introduction of schema validation doing the following worked without warning
```
vpc:
  securityGroupIds: [ !Ref LambdaSecurityGroup ]
  subnetIds: [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]
```
This now causes schema validation issues as only strings are allowed now

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test

package:
  individually: true
  excludeDevDependencies: false
  include:
    - package.json
  exclude:
    - ./**

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  vpc:
    securityGroupIds: [ !Ref LambdaSecurityGroup ]
    subnetIds: [ !Ref PrivateSubnet1, !Ref PrivateSubnet2 ]

resources:
  Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: false
        EnableDnsSupport: true
    PrivateSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        MapPublicIpOnLaunch: false
        AvailabilityZone: !Select [ 0, !GetAZs '' ]
        CidrBlock: 10.0.1.0/24
    PrivateSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        MapPublicIpOnLaunch: false
        AvailabilityZone: !Select [ 1, !GetAZs '' ]
        CidrBlock: 10.0.2.0/24
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: lambda-security-group
        GroupDescription: Allow all outbound traffic, no inbound
        SecurityGroupIngress:
          - IpProtocol: -1
            CidrIp: 127.0.0.1/32
        VpcId: !Ref VPC
```

</details>

<details>
<summary><b><code>serverless package</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'provider.vpc.securityGroupIds[0]': should be string
Serverless:   at 'provider.vpc.subnetIds[0]': should be string
Serverless:   at 'provider.vpc.subnetIds[1]': should be string
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.2.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.4
```
I believe this can simply be fixed by adjusting https://github.com/serverless/serverless/blob/b867df147aea5e1f57a9d275e2a389efbbcf38aa/lib/plugins/aws/provider/awsProvider.js#L273 to also allow for `Ref`

```
awsLambdaVpcConfig: {
  type: 'object',
  properties: {
    securityGroupIds: {
      type: 'array',
      items: {
        anyOf: [
          { type: 'string' },
          { $ref: '#/definitions/awsCfRef' }
        ]
      },
      maxItems: 5,
    },
    subnetIds: {
      type: 'array',
      items: {
        anyOf: [
          { type: 'string' },
          { $ref: '#/definitions/awsCfRef' }
        ]
      },
      maxItems: 16,
    },
  },
}
```

**Comment by medikoo** [comment]
@devpow112 indeed, thanks for reporting. In this case we can probably support all CloudFormation functions (assuming it makes sense). PR is welcome!

(cc @fredericbarthelet )

**Comment by devpow112** [comment]
Yes @medikoo, good thought about all the CloudFormation functions. `Ref` was just my use case. I'll work on a PR for this. Thanks for the quick response.

**Comment by dashmug** [comment]
@devpow112 @medikoo Can we allow environment variables as well?

My VPC config comes from environment variables like this:

```yaml
functions:  
  functionOne:    
    vpc:
      securityGroupIds:
        - ${env:SECURITY_GROUP_ID, ''}
      subnetIds:
        - ${env:SUBNET_1, ''}
        - ${env:SUBNET_2, ''}
        - ${env:SUBNET_3, ''}
```

And `serverless` complains with `unsupported configuration format` for both `securityGroupIds` and `subNetIds`.

**Comment by medikoo** [comment]
@dashmug variables are resolved before validation. If you have configuration warning, it means that given construct resolved to not supported format (I assume that empty strings may not be allowed as valid)

**Comment by binaryartifex** [comment]
I'd like to extend on this. In my opinion, securityGroupIds and subnetIds can potentially be dynamic in size, especially if these parameters are derived from an AWS ssm parameter store. My vpc fields are declared via the following -

```
  vpc:
    securityGroupIds:
      {
        "Fn::Split":
          [",", "${ssm:/RDS/${self:provider.stage}/security-groups/lambda}"],
      }
    subnetIds:
      {
        "Fn::Split":
          [",", "${ssm:/RDS/${self:provider.stage}/subnets/private}"],
      }
```

Unfortunately, serverless validation doesn't accept these as valid arrays. any help would be greatly appreciated...

**Comment by medikoo** [comment]
@binaryartifex your case is discussed at https://github.com/serverless/serverless/issues/8513

**Comment by pashka4281** [comment]
@medikoo 


> @dashmug variables are resolved before validation. If you have configuration warning, it means that given construct resolved to not supported format (I assume that empty strings may not be allowed as valid)

Is this also true for component-based services? (e.g. express). I'm doing the exact same thing @dashmug  described except it looks like variables do not get resolved if placed in the array:



```
14s › Serverless › 2 validation errors detected: Value '[${env:VPC_SG_1, ''}]' at 'vpcConfig.securityGroupIds' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 1024, Member must have length greater than or equal to 0, Member must satisfy regular expression pattern: ^sg-[0-9a-z]*$]; Value '[${env:VPC_SUBNET_1, ''}, ${env:VPC_SUBNET_2, ''}]' at 'vpcConfig.subnetIds' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 1024, Member must have length greater than or equal to 0, Member must satisfy regular expression pattern: ^subnet-[0-9a-z]*$]
```


```
  vpc:
    securityGroupIds:
      - ${env:VPC_SG_1, ''}
    subnetIds:
      - ${env:VPC_SUBNET_1, ''}
      - ${env:VPC_SUBNET_2, ''}
 ```
