### ISSUE TITLE
schema validations for environment variables fail

### ISSUE THREAD

**Issue by dazza-codes** [serverless/serverless#8285]
For serverless 2.x, the schema validation fails for environment variables

With `serverless.yaml` that contains environment variables, e.g.

```yaml
provider:
  environment:
    FLASK_ENV: development

functions:
  funcName:
    environment:
      ANY_ENV: avalue
```

The errors are like:
```
Serverless:   at 'functions.funcName.environment.ANY_ENV': unsupported configuration format
Serverless:   at 'provider.environment.FLASK_ENV': unsupported configuration format
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  environment:
    FLASK_ENV: development

functions:
  funcName:
    environment:
      ANY_ENV: avalue
```
</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
Serverless:   at 'functions.funcName.environment.ANY_ENV': unsupported configuration format
Serverless:   at 'provider.environment.FLASK_DEBUG': unsupported configuration format
Serverless:   at 'provider.environment.DATADOG_ENABLED': unsupported configuration format
```
</details>

<b>Installed version</b>

```
Framework Core: 2.2.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.4
```

**Comment by medikoo** [comment]
@dazza-codes I'm not able to reproduce that error, also `serverless.yml` you've proved is incomplete (testing it out results with `"service" property is missing in serverless.yml` error).

Can you provide full content of `serverless.yml` (but minimal, without any plugins involved) ?

**Comment by sorenandersen** [comment]
Running `serverless deploy` on the following `serverless.yml`:

```
service: temp-aws-nodejs-hello

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
```

will yield a warning like:

```
Configuration warning at 'provider.environment.AWS_NODEJS_CONNECTION_REUSE_ENABLED': unsupported configuration format
```

Installed version:
```
Framework Core: 2.3.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.5
```

**Comment by janoist1** [comment]
I had the same issue after upgrading serverless from 1 to 2. What worked for me was to use a string value instead of integer. `1` 👉 `"1"`

**Comment by thtliife** [comment]
I have the exact same problem.
And wrapping in quotes isn't always an option.

Imagine the following:

```yml
service: temp-aws-nodejs-hello

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    environment:
      TEST_VAR:
        'Fn::Join':
          - ''
          - - 'foo'
            - 'bar'
```

do a `serverless deploy` with that `serverless.yml` and it will result in:
```bash
$ serverless deploy

  Serverless Error ---------------------------------------

  Configuration error at 'functions.hello.environment.TEST_VAR': unsupported configuration format

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.12.0
     Framework Version:         2.3.0 (local)
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.0
```

This issue does not occur in v2.1.1 (The version my project was on previously)
