### ISSUE TITLE
SNS filter policy in functions logs wrong warning

### ISSUE THREAD

**Issue by Edweis** [serverless/serverless#8294]
Hi all, I found that this : 
```yaml
functions:
  archiveProduct:
    handler: functions/archiveProduct.default
    events:
      - sns:
          topicName: ${self:provider.environment.ROUTING_TOPIC_NAME}
          filterPolicy:
            action:
              - archive
              - unarchive
```
logs the following warning
```
Serverless: Configuration warning:
Serverless:   at 'functions.archiveProduct.events[0].sns': unsupported configuration format
```

However the SNS subscriptions are successfully handled.
I can send a PR if someone points me where the ajv model is.
