### ISSUE TITLE
Support 'Fn::Transform' 'AWS::Include'

### ISSUE THREAD

**Issue by vorobievalex** [serverless/serverless#8300]
### Use case description

sls deploy throws a warning when 'Fn::Transform' is used:
`Configuration warning at 'resources.Resources': unrecognized property 'Fn::Transform'`

Still include is handled correctly on the CloudFormation side.

Sample code:
**serverless.yml:**
```
service: poc-inline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  anyfunction:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get

resources:
  # Additn transform to make 'Serverless' set CAPABILITY_AUTO_EXPAND:
  Transform: []  
  Resources:
    'Fn::Transform':
      Name: 'AWS::Include'
      Parameters:
        Location: s3://poc-include/bucket-inline.yml

```
**bucket-inline.yml:**
```
S3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: deleteme
```

PS:
Include is used in order to use common code for similar resources used in several hundred Lambdas. If there is any other mechanism to keep common code DRY, I will appreciate any help on it.

### Proposed solution

Do not throw the warning above and support at least some CloudFormation macros.
