### ISSUE TITLE
Allow boolean environment variables

### ISSUE THREAD

**Issue by danilofuchs** [serverless/serverless#8311]
### Use case description

Currently, Serverless only allows string values as environment variables. This is completely acceptable, as envs can only be strings.

My use case is the following:

```yaml
provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    # Turn this on when needing to debug timing
    lambda: true
  environment:
    XRAY_ENABLED: "${self:provider.tracing.lambda}"
```

`true` is boolean, so when validating, serverless will raise the warning:
```
Serverless: Configuration warning:
Serverless:   at 'provider.environment.XRAY_ENABLED': unsupported configuration format
```

But, during runtime, `XRAY_ENABLED` will be `"true"` (string).

I cannot use `lambda: "true"` as the field expects a boolean.

### Proposed solution

Serverless should allow usage of boolean values on environment variables with no warnings about unsupported configuration, as it is clearly supported (it converted to string after all)

I understand I could look into some weird workarounds using the `custom` field, but I feel it would be hard to understand in the future.
