### ISSUE TITLE
Number Properties Cannot be Options

### ISSUE THREAD

**Issue by seang96** [serverless/serverless#8336]
Some properties require numbers, I'd like to make them configurable options for deployment, but they are returned as strings giving the error "Encountered non numeric value for property". From what I have seen in the past, PR #5727 it seems to be an intended feature. Maybe the best approach to fix this issue and keep compatibility is a string to number type casting similar to string to boolean casting from PR #6869?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: ${self:custom.service.name}

provider:
    name: aws
    stackName: ${self:custom.service.name}-${self:provider.stage}
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-west-2'}

custom:
    service:
        name: ${self:custom.service.project}-db
        project: ${opt:project}

resources:
    Resources:
        RDSCluster:
            Type: 'AWS::RDS::DBCluster'
            Properties:
                # Begin: Update requires Replacement
                Engine: aurora-mysql
                EngineMode: serverless
                StorageEncrypted: true
                # End: Update requires Replacement
                DBClusterParameterGroupName: default.aurora-mysql5.7
                EnableHttpEndpoint: true
                BackupRetentionPeriod: ${opt:backup, 1)
                ScalingConfiguration:
                    AutoPause: true
                    MinCapacity: 1
                    MaxCapacity: 2
                    SecondsUntilAutoPause: 300
```

</details>

<details>
<summary><b><code>sls deploy --project test</code> output</b></summary>

```
Serverless Error ---------------------------------------
 
  An error occurred: RDSCluster - Encountered non numeric value for property BackupRetentionPeriod.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.3
     Framework Version:         1.70.1
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10
```

</details>

<b>Installed version</b>

```
Framework Core: 2.4.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```
