### ISSUE TITLE
Schema validation for Fn::Join flags empty delimiter

### ISSUE THREAD

**Issue by glb** [serverless/serverless#8344]
The schema validation for `Fn::Join` seems incorrect. It is perfectly valid for the delimiter string for `Fn::Join` to be the empty string.

> If a delimiter is the empty string, the set of values are concatenated with no delimiter.

([link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html))

Yet the tool complains when validating:

```text
Serverless: Configuration warning at 'functions.example.environment.EXAMPLE['Fn::Join'][0]': should NOT be shorter than 1 characters
```

This is because the schema says that the minimum length for the delimiter parameter is 1:

https://github.com/serverless/serverless/blob/7e4871b223647952b412fc7c7d119597494d56e1/lib/plugins/aws/provider/awsProvider.js#L262

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: example
  
frameworkVersion: ">=2.0.0 <3.0.0"

provider:
  name: aws

functions:
  example:
    handler: example.example
    environment:
      EXAMPLE:
        "Fn::Join":
          - ""
          - - "ex"
            - "ample"
```

</details>

<details>
<summary><b><code> sls package --verbose </code> output</b></summary>

```
Serverless: Configuration warning at 'functions.example.environment.EXAMPLE['Fn::Join'][0]': should NOT be shorter than 1 characters
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.7.0
     Framework Version:         2.4.0
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.4.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

Suggested fix: remove the `minLength: 1` for the first parameter to `Fn::Join`.
