### ISSUE TITLE
AWS API Gateway: Allow stage customization

### ISSUE THREAD

**Issue by nl-brett-stime** [serverless/serverless#8346]
### Use case description

API Gateway has a feature to manage different stages (dev/qa/prod). However, some users have their stages split across different AWS accounts. Other users may manage stages via IaC tools such as Cloud Formation, Terraform and Serverless. In these cases, API Gateway's stage feature becomes redundant: https://stackoverflow.com/a/53652722/93345

### Proposed solution

Allow the stage value sent to API Gateway to differ from Serverless' stage but fall back to Serverless' stage as a default value.

E.g.,

```
  provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  apiGateway:
    stage: aValueThatDiffersFromTheOneAbove
```
