### ISSUE TITLE
Bug: Deployment checks erroneously fail if local artifacts are placed in ".serverless/NAME.zip"

### ISSUE THREAD

**Issue by ryan-roemer** [serverless/serverless#8350]
Extracting this issue from https://github.com/serverless/serverless/issues/8187#issuecomment-703154176 so I can do a quick PR... I'll have a full regression test in the PR which will hopefully explain the isolated situation more.

The code at issue is: https://github.com/serverless/serverless/blob/75bf185785dc2b0a91b6500f353df92990e90f47/lib/plugins/aws/deploy/lib/checkForChanges.js#L138-L144

The issue is that if a plugin (like jetpack does) or outside build process places it's _own_ artifact into `.serverless/<FROM_PACKAGE_ARTIFACT>.zip` and sets `package.artifact` we end up with a case wherein we glob `.serverless/<FROM_PACKAGE_ARTIFACT>.zip` first in the sync glob and then add the exact same file(s) again in the `package.artifact` code in the conditional. This has the effect of (1) doing extra unneeded I/O for the hash calculation and (2) adding extra identical hashes to the `localHashes` array which causes the `_.isEqual()` check to be false and ultimately serverless will deploy when it otherwise shouldn't.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# .. Just a sample:
functions:
  my-fun:
    handler: index.handler
    package:
      # Assume this is created out of band by a separate process.
      artifact: ".serverless/my-fun.zip"
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
# EXPECT
Serverless: Service files not changed. Skipping deployment...

# ACTUAL => Gets a full deployment.
```

</details>

<b>Installed version</b>

```
Framework Core: 2.4.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```
