### ISSUE TITLE
Unable to set environmental variable for websocket

### ISSUE THREAD

**Issue by MatteoInfi** [serverless/serverless#8363]
I am unable to set the api websocket gateway endpoint on a function

```

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 900
  region: my-region
  environment:
    API_GATEWAY_WS_ENDPOINT: !Join ['', ['https://', !Ref WebsocketsApi, '.execute-api.', "${self:provider.region}", '.amazonaws.com/', "${opt:stage}/"]]


  pushPostgresEvent:
    handler: services/realtime/pushPostgresEvent/handler.default
    memorySize: 128
    timeout: 15
    environment:
      API_GATEWAY_WS_ENDPOINT: !Join ['', ['https://', !Ref WebsocketsApi, '.execute-api.', "${self:provider.region}", '.amazonaws.com/', "${opt:stage}/"]]


```

Both return an empty string

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.7

```
