### ISSUE TITLE
Serverless framework creating $default stage even if we provide explicit stage name when creating HTTP API.

### ISSUE THREAD

**Issue by shaheer-k** [serverless/serverless#8367]
Why the serverless framework creating $default stage even if we provide explicit stage name when creating HTTP API.
```
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
functions:
  handler:
    runtime: dotnetcore3.1
    handler: MyHandler
    events:
      - httpApi: '*'
```

**Comment by medikoo** [comment]
@shaheer-k for general support please use https://forum.serverless.com/ or https://www.serverless.com/slack

**Comment by HaaLeo** [comment]
@shaheer-k how did you solve the issue? I have the exact same question.

**Comment by HaaLeo** [comment]
For anybody else who may has the same problem: I ended up with overwriting the the `HttpApiStage`:
```yml
resources:
  extensions:
    HttpApiStage:
      Properties:
        StageName: ${self:provider.stage}
```
