### ISSUE TITLE
When using my own `deploymentBucket`  sls dont show the real error 

### ISSUE THREAD

**Issue by gipsh** [serverless/serverless#8377]
I'm using serverless and deploying to a custom bucket with the parameter  `deploymentBucket` defined on the yml. 
I also had an error on my yml where the name of the lambda function was in conflict with other lambda in another stack.  

While using the `deploymentBucket` serverless always showed this message after deploy step finished: 

ServerlessError: Stack with id xxxxxxx does not exist  

This message was correct as the stack was not deployed correctly.
When i removed the    `deploymentBucket`  directive the real error was shown on console. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test-test-test

custom:
  config:
    region: xxxxx
    stage: dev
provider:
  stage: dev
  region: xxxxx
  name: aws
  runtime: python3.7
  deploymentBucket:
    name: serverless.xxxxx.dev.deploys
    serverSideEncryption: AES256
  environment:
    LOG_LEVEL: INFO
functions:
  blabla_get:
    name: blabla_get
    handler: blabla/blabla.get
    events:
      - http:
          path: /blabla
          method: get
          cors: true
          integration: lambda
          response:
            headers:
              Content-Type: '''application/json'''
            template: $input.path('$')
            statusCodes:
              '200':
                pattern: '*'
                template: $input.path("$")
                headers:
                  Content-Type: '''application/jsonl'''
```

</details>

<details>

<summary><b><code>
SLS_DEBUG=* sls deploy
</code> output</b></summary>

```
Serverless: Stack create finished…
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 400 0.836s 0 retries] describeStacks({ StackName: ‘test-test-test’ })

Serverless Error ---------------------------------------

ServerlessError: Stack with id test-test-test does not exist
```

</details>

<b>Installed version</b>

```
Framework Core: 2.5.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```
