### ISSUE TITLE
DLQ for EventBridge rules

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#8379]
### Use case description

AWS has recently released support for Dead Letter Queue for EventBridge: https://aws.amazon.com/fr/blogs/compute/improved-failure-recovery-for-amazon-eventbridge/

We could implement support for this feature in Serverless

### Proposed solution

Use similar schema for DLQ declaration than existing [lambda DLQ](https://www.serverless.com/framework/docs/providers/aws/guide/functions#dead-letter-queue-dlq). Unlike lambda DLQ which supports both SNS and SQS arn as DLQ target, EventBridge DLQ only support SQS.

The DLQ configuration for an eventBridge bus is a per target configuration.

```yml
myFunction:
  handler: index.main
  onError: arn:aws:sns:us-east-1:XXXXXX:test # <-- Original existing DLQ on lambda invoke configuration
  events:
    - eventBridge:
        eventBus: custom-saas-events
        onError: arn:aws:sqs:us-east-1:XXXXXX:test # <-- New eventbridge DLQ on eventBridge target
        pattern:
          source:
            - saas.external
```

This new key `onError` on `eventBridge` function triggers configuration would allow any of the `awsArn` allowed types.
