### ISSUE TITLE
Configuration error when using custom variables in outputs section

### ISSUE THREAD

**Issue by joebernard** [serverless/serverless#8382]
Attempting to access a nested `custom` variable results in an array being stored in `outputs` instead of a string.

```yaml
provider:
  name: aws
  stage: ${opt:stage,'dev'}

custom:
  profile:
    dev: profile-development
    prod: profile-production

outputs:
  profile: ${self:custom.profile.${self:provider.stage}}
```

```
serverless deploy --stage prod
```
It will generate a validation warning but still deploy:
`Serverless: Configuration warning at 'outputs.profile': unsupported configuration format`

If I inspect my outputs variables in the dashboard I see something like this instead of a string:
```
[
 0: profile-production
]
```

This causes other services to fail to deploy since they were expecting a string.

<b>Installed version</b>

```
Framework Core: 2.6.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

Rolling back to version 2.4.0 fixes the issue.
