### ISSUE TITLE
authorizer: aws_iam is causing a `unsupported configuration format` schema error in serverless v2.6.0

### ISSUE THREAD

**Issue by michael-wolfenden** [serverless/serverless#8387]
`authorizer: aws_iam` is causing a schema configuration error in `serverless v2.6.0`. Reverting to `serverless v2.5.0` resolves the issue.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: posts/create
          method: post
          authorizer: aws_iam    
```

</details>

<details>
<summary><b><code>npx serverless package</code> output</b></summary>

```
Serverless: Configuration warning at 'functions.hello.events[0].http.authorizer': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...    
```

</details>

<b>Installed version</b>

```
Framework Core: 2.6.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```
