### ISSUE TITLE
"A version for this Lambda function exists ( 8 ). Modify the function to create a new version.." even when functions have changed

### ISSUE THREAD

**Issue by Bersaelor** [serverless/serverless#8392]
I have a serverless.yml with 29 functions (194 resources, just under the limit).

As of a few days ago, every time I change a function and `sls deploy -s prod`, I get an error during the Cloudformation 
stack deployment:

```
  Serverless Error ---------------------------------------
 
  An error occurred: CognitoDashverificationDashemailLambdaVersionNfb3OPkVsKcH9oNj9EXkK8zZS2ELzrjV7yI1dpp7cU - A version for this Lambda function exists ( 8 ). Modify the function to create a new version..
```

This happens regardless of function changed. The error always mentions a different function than the one I had changed, since I obviously don't change every function every time. I tried it in `2.6.0`, `2.5.0`, `2.4.0`, `2.3.0`, all with the same result.
Going back to `2.2.0` it works again as before.

I tried reducing my yml to a minimal version that reproduces the issue, by deploying reduced versions to my `dev` environment. Unfortunately deploying to `dev` seemed to always work, regardless of the amount of lambda functions.
And in production environment, I can't just remove functions and deploy the reduced production list. (One should note here that in the `dev` environment, I have to remove the `CandidatesDynamoDbTable` otherwise it'll complain that the table already exists, thats the only difference in the serverless.yml between posting to `dev` and `prod`).

Here's a redacted serverless.yml that reproduces the issue:

<details>
<summary><code>serverless.yml</code></summary>

```
service: ARCMS # NOTE: update this with your service name
#app: your-app-name
#tenant: your-tenant-name

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    MESSAGE:
      prod: "This is production environment"
      dev: "This is development environment"
  users-role: ***
  region: ${opt:region, self:provider.region}
  environment:
    NEWORDERTOPIC: ***
    REQUESTDXFTOPIC: ***
    MESSAGE: ***
    CANDIDATE_TABLE: ***
    IMAGE_BUCKET: ***
    MODEL_BUCKET: ***
    STAGE: ***
    ACCESS_STORE: ***
    ACCESS_MANAGER: ***
    ACCESS_ADMIN: ***
    
provider:
  name: aws
  stage: dev
  runtime: nodejs10.x
  region: eu-central-1

package:
  individually: true
  exclude:
    - "**/*"
    - node_modules/**

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"   
          - AttributeName: "sk"
            AttributeType: "S"   
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "sk"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.CANDIDATE_TABLE}


functions:
  appData:
    handler: categories/categories.appData
    role: ${self:custom.users-role}
    memorySize: 512
    description: Cached, public endpoint with categories and models
    package:
      include:
        - categories/categories.js
        - shared/**
    events:
      - http:
          path: /{brand}/app-data
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true

  refresh-app-data:
    handler: categories/categories.refreshAppData
    role: ${self:custom.users-role}
    memorySize: 512
    description: Refresh the cached appdata of categories and models manually before it's expired
    package:
      include:
        - categories/categories.js
        - shared/**
    events:
      - http:
          path: /{brand}/refresh-app-data
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: ***

  categories:
    handler: categories/categories.all
    role: ${self:custom.users-role}
    memorySize: 512
    description: Cached, public collections endpoint
    package:
      include:
        - categories/categories.js
        - shared/**
    events:
      - http:
          path: /{brand}/categories
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: ***

  create-category:
    handler: categories/categories.createNew
    role: ${self:custom.users-role}
    memorySize: 512
    description: Create new category with posted values should the current user have enough rights
    package:
      include:
        - categories/categories.js
        - shared/**
    events:
      - http:
          path: /{brand}/categories
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: ***

  set-category-status:
    handler: categories/categories.setStatus
    role: ${self:custom.users-role}
    memorySize: 512
    description: Set status of existing category
    package:
      include:
        - categories/categories.js
        - shared/**
    events:
      - http:
          path: /{brand}/category/{category}/setStatus
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: ***x

  delete-category:
    handler: categories/categories.delete
    role: ${self:custom.users-role}
    memorySize: 512
    description: Delete category should the current user have enough rights
    package:
      include:
        - categories/categories.js
        - shared/**
    events:
      - http:
          path: /{brand}/categories/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                brand: true
                id: true
          authorizer:
            name: authorizer
            arn: ***

  models:
    handler: models/models.all
    role: ${self:custom.users-role}
    memorySize: 512
    description: Cached, public model endpoint
    package:
      include:
        - models/models.js
        - shared/**
    events:
      - http:
          path: /{brand}/category/{category}/models
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true
                category: true

  get-model:
    handler: models/models.get
    role: ${self:custom.users-role}
    memorySize: 512
    description: get a single model should the current user have enough rights
    package:
      include:
        - models/models.js
        - shared/**
    events:
      - http:
          path: /{brand}/category/{category}/models/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true
                category: true
                id: true
          authorizer:
            name: authorizer
            arn: ***

  set-model-status:
    handler: models/models.setStatus
    role: ${self:custom.users-role}
    memorySize: 512
    description: set publish/unpublish status on models
    package:
      include:
        - models/models.js
        - shared/**
    events:
      - http:
          path: /{brand}/category/{category}/models/{id}/setStatus
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
                category: true
                id: true
          authorizer:
            name: authorizer
            arn: ***

  create-model:
    handler: models/models.createNew
    role: ${self:custom.users-role}
    memorySize: 512
    description: Create new model with posted values should the current user have enough rights
    package:
      include:
        - models/models.js
        - shared/**
    events:
      - http:
          path: /{brand}/category/{category}/models
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
                category: true
          authorizer:
            name: authorizer
            arn: ***

  copy-model:
    handler: models/models.copy
    role: ${self:custom.users-role}
    memorySize: 512
    description: Copy an existing model to a new brand and collection
    package:
      include:
        - models/models.js
        - shared/**
    events:
      - http:
          path: /{brand}/category/{category}/models/{id}
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
                category: true
                id: true
          authorizer:
            name: authorizer
            arn: ***

  delete-model:
    handler: models/models.delete
    role: ${self:custom.users-role}
    memorySize: 512
    description: Delete model should the current user have enough rights
    package:
      include:
        - models/models.js
        - shared/**
    events:
      - http:
          path: /{brand}/category/{category}/models/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                brand: true
                category: true
                id: true
          authorizer:
            name: authorizer
            arn: ***

  tags:
    handler: tags/tags.all
    role: ${self:custom.users-role}
    memorySize: 512
    description: all tags for one brand
    package:
      include:
        - tags/tags.js
        - shared/**
    events:
      - http:
          path: tags/{brand}/
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: ***

  create-tag:
    handler: tags/tags.createNew
    role: ${self:custom.users-role}
    memorySize: 512
    description: create new tag with name for brand
    package:
      include:
        - tags/tags.js
        - shared/**
    events:
      - http:
          path: tags/{brand}/
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: ***

  my-brands:
    handler: user/brands.get
    role: ${self:custom.users-role}
    memorySize: 512
    description: Get all brands the current uses is member in
    package:
      include:
        - user/brands.js
        - shared/access_methods.js
        - brand_settings.json
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  create-user:
    handler: user/user.createNew
    role: ${self:custom.users-role}
    memorySize: 512
    description: Create new user with posted values should the current user have enough rights
    package:
      include:
        - user/user.js
        - shared/access_methods.js
    events:
      - http:
          path: user
          method: post
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  resend-user-invite:
    handler: user/user.resendInvite
    role: ${self:custom.users-role}
    memorySize: 512
    description: Resend invitation for existing user
    package:
      include:
        - user/user.js
        - shared/access_methods.js
    events:
      - http:
          path: user/resend/
          method: post
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  delete-user:
    handler: user/user.delete
    role: ${self:custom.users-role}
    memorySize: 512
    description: Delete user should the current user have enough rights
    package:
      include:
        - user/user.js
        - shared/access_methods.js
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
          authorizer:
            name: authorizer
            arn: ***

  users-by-brand:
    handler: brand/users.all
    role: ${self:custom.users-role}
    timeout: 30
    memorySize: 512
    description: Get all users for a given brand
    package:
      include:
        - brand/users.js
        - shared/access_methods.js
        - shared/pagination.js
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  get-devices:
    handler: devices/devices.all
    role: ${self:custom.users-role}
    memorySize: 512
    description: Get all devices for the current user
    package:
      include:
        - devices/devices.js
    events:
      - http:
          path: devices
          method: get
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  check-device:
    handler: devices/devices.check
    role: ${self:custom.users-role}
    memorySize: 512
    description: Check in with a device, add it if needed or reply that the user has used up his quota
    package:
      include:
        - devices/devices.js
    events:
      - http:
          path: device/check
          method: post
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  delete-device:
    handler: devices/devices.delete
    role: ${self:custom.users-role}
    memorySize: 512
    description: Delete a device from the current user
    package:
      include:
        - devices/devices.js
    events:
      - http:
          path: device/{id}
          method: delete
          request:
            parameters:
              paths:
                id: true
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  get-orders-v2:
    handler: orders/orders.allPaginated
    role: ${self:custom.users-role}
    memorySize: 512
    description: Get all orders for the current user or a specified third user depending on the accessLvl
    package:
      include:
        - orders/orders.js
        - shared/access_methods.js
        - brand_settings.json
        - shared/pagination.js
        
    events:
      - http:
          path: v2/orders
          method: get
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  copy-orders:
    handler: orders/convert.copyFromTo
    role: ${self:custom.users-role}
    memorySize: 512
    description: Copy all orders by one user to a different user, typically to generate a larger data set
    package:
      include:
        - orders/convert.js
        - shared/access_methods.js

  get-order:
    handler: orders/orders.order
    role: ${self:custom.users-role}
    memorySize: 512
    description: Get a specific order based on brand, user and timeStamp
    package:
      include:
        - orders/orders.js
        - shared/access_methods.js
        - shared/pagination.js
        - brand_settings.json
    events:
      - http:
          path: order/{id}
          method: get
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  create-order:
    handler: orders/orders.create
    role: ${self:custom.users-role}
    memorySize: 512
    description: Create and save a new order
    package:
      include:
        - orders/orders.js
        - shared/pagination.js
        - shared/access_methods.js
        - brand_settings.json
    environment:
      emailSNSArn: { "Fn::Join" : ["", ["arn:aws:sns:${self:custom.region}:", { "Ref" : "AWS::AccountId" }, ":${self:provider.environment.NEWORDERTOPIC}" ] ]  }
      dxfFileRequestArn: { "Fn::Join" : ["", ["arn:aws:sns:${self:custom.region}:", { "Ref" : "AWS::AccountId" }, ":${self:provider.environment.REQUESTDXFTOPIC}" ] ]  }
    events:
      - http:
          path: order/create
          method: post
          cors: true
          authorizer:
            name: authorizer
            arn: ***
      - http:
          path: order
          method: post
          cors: true
          authorizer:
            name: authorizer
            arn: ***

  send-new-order-mails:
    handler: email-notifications/emails.newOrder
    role: ${self:custom.users-role}
    memorySize: 512
    description: Send email notifications when new order is received
    package:
      include:
        - email-notifications/**
        - '!email-notifications/tests/**'
        - node_modules/mustache/mustache.min.js
        - brand_settings.json
    events:
      - sns: ${self:provider.environment.NEWORDERTOPIC}

  create-dxf-files:
    handler: email-notifications/dxffilemail.newRequest
    role: ${self:custom.users-role}
    memorySize: 2048
    timeout: 300
    description: Send email with a number of created dxf files for the ordered frames
    package:
      include:
        - email-notifications/dxffilemail.js
        - email-notifications/DXFCombiner.js
        - email-notifications/locales.js
        - brand_settings.json
        - node_modules/nodemailer/**
        - node_modules/makerjs/**
        - node_modules/bezier-js/**
        - node_modules/clone/**
        - node_modules/graham_scan/**
        - node_modules/kdbush/**
        - node_modules/xml2js/**
        - node_modules/sax/**
        - node_modules/xmlbuilder/**
    events:
      - sns: ${self:provider.environment.REQUESTDXFTOPIC}

  cognito-verification-email:
    handler: email-notifications/cognito.verification
    role: ${self:custom.users-role}
    memorySize: 512
    description: Send email with verification code for password reset
    package:
      include:
        - email-notifications/**
        - '!email-notifications/tests/**'
        - node_modules/mustache/mustache.min.js
        - brand_settings.json

```
</details>

<details>
<summary><b><code>  sls deploy -s prod </code> output</b></summary>

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service appData.zip file to S3 (6.54 KB)...
Serverless: Uploading service refresh-app-data.zip file to S3 (6.54 KB)...
Serverless: Uploading service categories.zip file to S3 (6.54 KB)...
Serverless: Uploading service cognito-verification-email.zip file to S3 (52.15 KB)...
Serverless: Uploading service create-dxf-files.zip file to S3 (628.95 KB)...
Serverless: Uploading service send-new-order-mails.zip file to S3 (52.15 KB)...
Serverless: Uploading service create-order.zip file to S3 (6.1 KB)...
Serverless: Uploading service get-order.zip file to S3 (6.1 KB)...
Serverless: Uploading service copy-orders.zip file to S3 (2.35 KB)...
Serverless: Uploading service get-orders-v2.zip file to S3 (6.1 KB)...
Serverless: Uploading service delete-device.zip file to S3 (2.83 KB)...
Serverless: Uploading service check-device.zip file to S3 (2.83 KB)...
Serverless: Uploading service get-devices.zip file to S3 (2.83 KB)...
Serverless: Uploading service users-by-brand.zip file to S3 (3.24 KB)...
Serverless: Uploading service delete-user.zip file to S3 (5.28 KB)...
Serverless: Uploading service resend-user-invite.zip file to S3 (5.28 KB)...
Serverless: Uploading service create-user.zip file to S3 (5.28 KB)...
Serverless: Uploading service my-brands.zip file to S3 (2.74 KB)...
Serverless: Uploading service create-tag.zip file to S3 (4.21 KB)...
Serverless: Uploading service tags.zip file to S3 (4.21 KB)...
Serverless: Uploading service delete-model.zip file to S3 (8.18 KB)...
Serverless: Uploading service copy-model.zip file to S3 (8.18 KB)...
Serverless: Uploading service create-model.zip file to S3 (8.18 KB)...
Serverless: Uploading service set-model-status.zip file to S3 (8.18 KB)...
Serverless: Uploading service get-model.zip file to S3 (8.18 KB)...
Serverless: Uploading service models.zip file to S3 (8.18 KB)...
Serverless: Uploading service delete-category.zip file to S3 (6.54 KB)...
Serverless: Uploading service set-category-status.zip file to S3 (6.54 KB)...
Serverless: Uploading service create-category.zip file to S3 (6.54 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........................................................................................................
Serverless: Operation failed!
Serverless: View the full error output: ***
 
  Serverless Error ---------------------------------------
 
  An error occurred: CopyDashordersLambdaVersionvk88Tcgtu1LRggMQjJl6aOhSHdDZS5FGb62HpriD14 - A version for this Lambda function exists ( 5 ). Modify the function to create a new version..
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.0
     Framework Version:         2.6.0
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1

</details>

<b>Installed version</b>

Framework Core: 2.6.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
