### ISSUE TITLE
Configuration warning for prebuilt archive layer

### ISSUE THREAD

**Issue by thomaschen** [serverless/serverless#8397]
I'm getting a configuration warning that the layer should have required property `path`, even though the [documentation](https://www.serverless.com/framework/docs/providers/aws/guide/layers/) suggested that `path` is not required for a prebuilt archive layer.

> You can also specify a prebuilt archive to create your layer. When you do this, you do not need to specify the path element of your layer.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

layers:
  xyz:
    package:
      artifact: xyz.zip
```

</details>

<details>
<summary><b><code>serverless package</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Configuration warning at 'layers.xyz': should have required property 'path'
...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.6.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```
