### ISSUE TITLE
lambda trigger cloudwatchEvent issue with `stage` parameter

### ISSUE THREAD

**Issue by FinnFrotscher** [serverless/serverless#8402]
Cloudwatch event definition specifies a `stage` parameter to stop a lambda from triggering on a cloudwatch event from another stage.

```
[lambda name]
  events:
  - cloudwatchEvent:
      event:
        source:
          - 'aws.mediaconvert'
        detail-type:
          - 'MediaConvert Job State Change'
        detail:
          stage:
            - ${opt:stage , 'dev'}
          status:
            - 'COMPLETE'
            - 'ERROR'
```

Since having included this parameter, the lambda has not been triggered at all. 
If i omit this parameter, the lambda triggers on all stages simultaneously, independent of the eventsource stage.

```yaml
# complete transcoding status lambda
transcodingStatus:
  handler: packages/transcoding-pipeline/dist/transcodingStatus.handler
  package:
    exclude:
      - ./**
    include:
      - packages/transcoding-pipeline/dist/transcodingStatus.js
  timeout: 30
  events:
  - cloudwatchEvent:
      event:
        source:
          - 'aws.mediaconvert'
        detail-type:
          - 'MediaConvert Job State Change'
        detail:
          stage:
            - ${opt:stage , 'dev'}
          status:
            - 'COMPLETE'
            - 'ERROR'
  environment:
    API_URL: ${self:custom.config.apiEndpoint}
    CLIENT_AUTH_BEARER: ${self:custom.config.clientAuthBearer}


# Media Convert Job definition
TranscodingMediaConvertJobRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:custom.settings.transcoding.mediaConvertJobRoleName}
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        Effect: Allow
        Principal:
          Service:
            - mediaconvert.amazonaws.com
            - mediaconvert.eu-central-1.amazonaws.com
            - mediaconvert.${self:provider.region}.amazonaws.com
        Action:
          - 'sts:AssumeRole'
    Path: '/'
    Policies:
      - PolicyName: MediaConvertJobRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
                - sns:*
                - logs:*
                - cloudwatch:*
                - autoscaling:Describe*
              Resource: '*'

```

```
⟩serverless --version                                                         
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.3.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.0
```
