### ISSUE TITLE
AWS IAM: using '*' in Resource for some valid actions for Rekognition generates "unsupported configuration format" warning

### ISSUE THREAD

**Issue by faheel** [serverless/serverless#8417]
According to the [IAM user guide for AWS Rekognition](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonrekognition.html) using `'*'` is valid as a `Resource` in the IAM role statements for some actions (such as `rekognition:DetectText`):

> The Resource types column indicates whether each action supports resource-level permissions. If there is no value for this column, you must specify all resources ("\*") in the Resource element of your policy statement. If the column includes a resource type, then you can specify an ARN of that type in a statement with that action. Required resources are indicated in the table with an asterisk (\*). If you specify a resource-level permission ARN in a statement using this action, then it must be of this type. Some actions support multiple resource types. If the resource type is optional (not indicated as required), then you can choose to use one but not the other.

But a configuration warning is generated that says "unsupported configuration format" when using the following:

```yaml
provider:
  name: aws 
 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:DetectText
      Resource:
        - '*'
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test-rekognition-iam

provider:
  name: aws
  profile: ${opt:profile, 'default'}
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - rekognition:DetectText
      Resource:
        - '*'

functions:
  DummyLambda:
    runtime: nodejs12.x
    memorySize: 128
    timeout: 10
    handler: lambda.handler
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls deploy</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.8.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Configuration warning at 'provider.iamRoleStatements[0].Resource[0]': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...

<deployment proceeds and succeeds>
```

</details>

<b>Installed version</b>

```
Framework Core: 2.8.0 (local)
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.2.3
```
