### ISSUE TITLE
Deep directories trigger AWS 128 char limit for handler unless restructure zip package

### ISSUE THREAD

**Issue by deitch** [serverless/serverless#8419]
Deep lambda zip file hits 128 char limit.

I have a repository with many lambdas. For various reasons, the path to the target include (in this case, golang compiled binary, but could be anything) is a few directories deep, each of which has a long filename. AWS doesn't accept handlers that are >128 chars in length. This means that my deploy fails.

Possible solution: Provide the ability to control the structured of the Lambda zip file package.

Since I am including everything from the long path in `include`, and then have to repeat it in my `handler`, if serverless could put it in the root of the zip file, the repetitive entry in `handler` would go away, and AWS would be happy.

Note: may be related to #3366

<details>
<summary><code>serverless.yml</code></summary>

Note: cannot include all of serverless.yaml due to it being private, but enough here to reproduce the issue

```yaml
  get_member_history_by_id:
    handler: build_path/member_service/deep_service_one/get_member_history_by_id_handler/get_member_history_by_id_handler_/get_member_history_by_id_handler
    package:
      individually: true
      include:
        - ../build_path/member_service/deep_service_one/get_member_history_by_id_handler/get_member_history_by_id_handler_/get_member_history_by_id_handler
```

Notice:

* the `handler` is >128 chars
* the `handler` and `include` are almost identical, very much breaking DRY

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
ServerlessError: An error occurred: GetUnderscoreencounterUnderscorebyUnderscoreidLambdaFunction - 1 validation error detected: Value 'build_path/member_service/deep_service_one/get_member_history_by_id_handler/get_member_history_by_id_handler_/get_member_history_by_id_handler' at 'handler' failed to satisfy constraint: Member must have length less than or equal to 128 (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: cab248fa-b51e-42d4-b1d0-45406a468d7a; Proxy: null).
```

</details>

<b>Installed version</b>

```
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.3
```

### Other Relevant Info

It would be work, and it would be smoother, if I could do:

```yml
  get_member_history_by_id:
    handler: get_member_history_by_id_handler
    package:
      individually: true
      include:
        - ../build_path/member_service/deep_service_one/get_member_history_by_id_handler/get_member_history_by_id_handler_/get_member_history_by_id_handler
```

I imagine that the `include` would need some `target`, or perhaps it might be:

```yaml
  get_member_history_by_id:
    handler: build_path/member_service/deep_service_one/get_member_history_by_id_handler/get_member_history_by_id_handler_/get_member_history_by_id_handler
    package:
      individually: true
      includeFiles:
        - ../build_path/member_service/deep_service_one/get_member_history_by_id_handler/get_member_history_by_id_handler_/get_member_history_by_id_handler
```

or some other flag to indicate that it should restructure. #3366 would work too.

I am happy to submit a PR for this, if we can agree on the right approach that will be accepted.
