### ISSUE TITLE
Serverless gives "unsupported configuration format" during deploy through TravisCI.

### ISSUE THREAD

**Issue by UdittLamba** [serverless/serverless#8421]
TravisCI somehow does not deploy the environment variables to the Lambda function and gives the following warning on console:
```
$ cd replicant-backend && sls deploy

Serverless: Configuration warning:

Serverless:   at 'provider.environment.SCHEMA': unsupported configuration format

Serverless:   at 'provider.environment.USERNAME': unsupported configuration format

Serverless:   at 'provider.environment.PASSWORD': unsupported configuration format

Serverless:   at 'provider.environment.HOST': unsupported configuration format

Serverless:   at 'provider.environment.TELEGRAM_TOKEN': unsupported configuration format

Serverless:   at 'provider.environment.CHAT_ID': unsupported configuration format

Serverless:  

Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

**My TravisCI.yml:**
```
language: node_js
node_js:
  - "12"
install:
  - npm install serverless -g
  - npm install
script:
  - cd replicant-backend && sls deploy
```

**My serverless.yml:**
```
service: replicant
# app and org for use with dashboard.serverless.com
app: replicant-app
org: udittlamba

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SCHEMA:  ${file(./serverless.env.yml):SCHEMA, ''}
    USERNAME:  ${file(./serverless.env.yml):USERNAME, ''}
    PASSWORD:  ${file(./serverless.env.yml):PASSWORD, ''}
    HOST:  ${file(./serverless.env.yml):HOST, ''}
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
    CHAT_ID: ${file(./serverless.env.yml):CHAT_ID, ''}
  timeout: 30
functions:
 -----------
```
