### ISSUE TITLE
Configuration warning: unrecognized property 'module'

### ISSUE THREAD

**Issue by luislhl** [serverless/serverless#8423]
I'm getting this warning during deploys when trying to use the functions `module` option, since version 2.7.0.
The same thing works with 2.6.0

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: boilerplate-lambda

provider:
  name: aws
  runtime: python3.7
  stage: dev

package:
  individually: true

functions:
  lambda-1:
    module: lambda1 
    handler: src/main.main

  lambda-2:
    module: lambda2
    handler: src/main.main

plugins:
  - serverless-python-requirements
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'functions['lambda-1']': unrecognized property 'module'
Serverless:   at 'functions['lambda-2']': unrecognized property 'module'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```

</details>

<b>Installed version</b>

```
Framework Core: 2.7.0
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.2.4
```
