### ISSUE TITLE
Unable change identity source in a new deployment

### ISSUE THREAD

**Issue by MatteoInfi** [serverless/serverless#8424]
Serverless framework is unable to change the `identitySource` of the authorizer.
My first deployment was the following:

```

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 900
  region: my-region


functions:
  handler: /src/my-handler
  events:
   - websocket:
      route: $connect
      authorizer: arn:aws:lambda:my-region-1:dev:function:my-function

```

After that I have changed to this:

```

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 900
  region: my-region


functions:
  handler: /src/my-handler
  events:
   - websocket:
      route: $connect
      authorizer: arn:aws:lambda:my-region-1:dev:function:my-function
      identitySource:
        - 'route.request.querystring.Auth'

```

In the AWS console the `IdentitySource` still shows "Auth (header)"

<b>Installed version</b>

```
Framework Core: 1.79.0
Plugin: 3.7.1
SDK: 2.3.1
Components: 2.34.7

```
