### ISSUE TITLE
Error that S3 Bucket Already Exists

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#8425]
When deploying to AWS, I receive the following error, even though this s3 bucket does not exist:
`ServerlessError: An error occurred: S3BucketArtifacts - sast-artifacts already exists.`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-microservices

provider:
  name: aws
  runtime: nodejs12.x
  endpointType: regional
  stage: ${opt:stage, 'dev'}
  environment:
    S3_ARTIFACTS: sast-artifacts
  s3:
    artifacts:
      name: ${self:provider.environment.S3_ARTIFACTS}
      lifecycleConfiguration:
        Rules:
          - Id: SASTArtifactLifecycleRules
            Status: Enabled
            ExpirationInDays: '1'

functions:
  artifact:
    handler: api/artifact.artifact
    role: lambdaSASTArtifact
    events:
      - s3:
          bucket: artifacts
          event: s3:ObjectCreated:*

  presign:
    handler: api/presign.url
    role: lambdaSASTPresign
    events:
      - http:
          path: /presign
          method: POST
          integration: lambda

resources:
  Resources:
    lambdaSASTArtifact:
      Type: AWS::IAM::Role
      Properties:
        RoleName: lambdaSASTArtifact
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: lambdaSASTArtifactPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/${self:service}-${self:provider.stage}-artifact:*:*'
    
    lambdaSASTPresign:
      Type: AWS::IAM::Role
      Properties:
        RoleName: lambdaSASTPresign
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: lambdaSASTPresignPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/${self:service}-${self:provider.stage}-presign:*:*'
                - Effect: Allow
                  Action:
                    - S3:PutObject
                  Resource:
                    - 'arn:aws:s3:::${self:provider.environment.S3_ARTIFACTS}/*'
plugins:
  - serverless-iam-roles-per-function
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
export SLS_DEBUG=*
./node_modules/serverless/bin/serverless.js deploy --package _artifacts/sast --stage prod
-----
Serverless: Operation failed!
Serverless: View the full error output: https://*********.console.aws.amazon.com/cloudformation/home?region=*********#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3A*********%3A385329293423%3Astack%2Fmy-microservices-prod%2Ffcb56b70-13ad-11eb-83da-06f1edcd3eb8
 
  Serverless Error ---------------------------------------
 
  ServerlessError: An error occurred: S3BucketArtifacts - sast-artifacts already exists.
      at /home/circleci/sast-microservices/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:99:23
      at processImmediate (internal/timers.js:456:21)
  From previous event:
      at /home/circleci/sast-microservices/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.4
     Framework Version:         2.8.0 (local)
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.2.5
 

Exited with code exit status 1
```

</details>

<b>Installed version</b>

```
Serverless: serverless-certificate-creator version 1.3.0 called
Framework Core: 2.8.0 (local)
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.2.5
```
