### ISSUE TITLE
Question: How to enable request validation?

### ISSUE THREAD

**Issue by jack1902** [serverless/serverless#8443]
## Background

So i originally opened https://forum.serverless.com/t/how-do-you-add-a-request-validator-to-api-gateway/12923 on the serverless forums but i haven't had any responses.

I can see https://github.com/serverless/serverless/issues/6172 might be related but i didn't want to hijack that issue hence why i created this one.

## Question

How do i enable request validation in serverless natively without using any plugins? I have a function which has some headers that i want to enforce be on the inbound request, but when i do:

```yaml
my_func:
  request:
    parameters:
      headers:
        X-Timestamp: true
        X-Signature: true
```

I can still send a request that is accepted to my end lambda which isn't what i expected to happen
