### ISSUE TITLE
Dashboard integration significantly introduces Lambda duration

### ISSUE THREAD

**Issue by vbichkovsky** [serverless/serverless#8449]
Enabling Dashboard integration via setting org and app properties in serverless.yml while using webpack packaging and aws-sdk as a runtime dependency, results in significant Lambda runtime duration when an error occurs in the handler.

<details>
<summary><code>serverless.yml</code></summary>

```yaml

service: issue
frameworkVersion: '2'

org: your-org-here
app: sls-issue

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-1
  memorySize: 256
  timeout: 10

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: /
          method: get

```

</details>

<details>
<summary>I've prepared a sample project in a public repo: https://github.com/vbichkovsky/sls-issue
In order to expose a problem, the app has to be deployed and an API Gateway endpoint has to be called.</summary>

</details>

<b>Installed version</b>

```
Framework Core: 2.8.0 (local)
Plugin: 4.1.1
SDK: 2.3.2
Components: 3.2.7

```
