### ISSUE TITLE
Extending configuration validation for `http` events

### ISSUE THREAD

**Issue by DianaIonita** [serverless/serverless#8458]
### Use case description

As a plugin creator
I want to be able to add configuration validation to the `http` event that my plugin extends
So that a plugin user is informed in case they misconfigure it

### What I have tried
If my plugin has a configuration like this:
```yml
myFunction:
  events:
    - http:
        method: get
        myCustomProperty:
          customSetting: aValue
```

I have tried to define it like this, but it seems that this overrides the whole `http` event validation:
```js
const schema = {
    type: 'object',
    properties: {
      myCustomProperty: {
        type: 'object',
        properties: {
          customSetting: { type: 'string' }
        }
      }
    }
  }

serverless.configSchemaHandler.defineFunctionEvent('aws', 'http', schema);
```

### Proposed solution

For instance, the framework could offer a method that extends validation for a given type of event:
```js
serverless.configSchemaHandler.extendFunctionEvent('aws', 'http', schema);
```
