### ISSUE TITLE
Serverless 2.9.0 breaks retro compatibility with XRay tracking

### ISSUE THREAD

**Issue by nykolaslima** [serverless/serverless#8459]
After serverless 2.9.0 release, the XRay tracing stopped working throwing the following error:
```
Serverless Error ---------------------------------------
 
  An error occurred: DaysDashwithDashconditionDashrefresherLambdaFunction - 1 validation error detected: Value 'false' at 'tracingConfig.mode' failed to satisfy constraint: Member must satisfy enum value set: [event] (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException; Request ID: 7e89961e-2020-43d8-88c3-2f8b9eab5e04; Proxy: null).
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: retail-integrated

provider:
  name: aws
  runtime: python3.6
  versionFunctions: false
  stage: dev
  region: us-east-1
  tracing:
    lambda: false
    apiGateway: false

  functions:
    days-with-condition-refresher:
      timeout: 900
      handler: functions/days_with_condition_refresher.handle
        events:
          - schedule: cron(0 8 * * ? *)
```

</details>

<b>Installed version</b>

```
2.9.0
```
