### ISSUE TITLE
Go local test takes forever in "Excluding development dependencies" step.

### ISSUE THREAD

**Issue by bwpedro** [serverless/serverless#8461]
In my serverless project I have a mix of node.js and golang lambdas.

When I run `serverless invoke local --function ${functionName} --path ${path}` in node.js it runs just fine.

But when I try to run the same thing with a go function (**using docker #4746**), serverless takes forever in the "Excluding development dependencies" step.

It seems like it needs to deploy all functions before executing the **local** test.

In my case I have 3 functions in serveless.yml, one "Excluding development dependencies" for each function.

```
AppSync Plugin: GraphQl schema valid
Serverless: [serverless-jetpack] Skipping individual packaging for 1 functions
Serverless: [serverless-jetpack] Packaging 0 functions, 0 services, and 0 layers with concurrency 3
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
```

I was trying in a different project which I have more than 30 functions and it just took forever to test and I just had to gave up using go and use node.js instead.

If I deploy the function and test the **remote** function (just invoke, without local) it works but if I make a change I have to deploy the whole function to test.

My provider in serverless.yml:

```
provider:
    name: aws
    runtime: nodejs12.x
    profile: smart-parking
    memorySize: 128
    versionFunctions: false
```

Here's two functions in my serverless.yml, one for node.js and other for go:

```
parking:
    name: ${self:app}-parking-${self:custom.stage}
    handler: functions/parking/main.handler
    package:
        include:
            - functions/parking/*
            - functions/parking/*/**
    environment:
        APP: ${self:app}
        STAGE: ${self:custom.stage}

myGoFunction:
    name: ${self:app}-myGoFunction-${self:custom.stage}
    handler: functions/myGoFunction/main.go
    runtime: go1.x
    package:
        include:
            - functions/myGoFunction/*
            - functions/myGoFunction/*/**
```

My plugins:

```
plugins:
    - serverless-appsync-plugin
    - serverless-go-plugin
    - serverless-jetpack
```

**PS:** I have tested **without** the **serverless-jetpack plugin** and **without serverless-go-plugin** and still got the same "Excluding development dependencies" in **local** test.

This is without the jetpack plugin

```
AppSync Plugin: GraphQl schema valid
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
```

My package.json:

```
"serverless": "^2.9.0",
"serverless-appsync-plugin": "^1.4.0",
"serverless-go-plugin": "^2.0.1",
"serverless-jetpack": "^0.10.7"
```

I'm using macOS Catalina 10.15.6.

I know the go function **only works locally with docker** and I can see my function running if I just **wait the excluding development dependencies**, but it just **takes too much time** if the project is big enough.
