### ISSUE TITLE
"sls login" results in warnings "unsupported configuration format" regarding ${param:....} in the environment - section

### ISSUE THREAD

**Issue by mtin79** [serverless/serverless#8464]
Hi there,
we upgraded from serverless version 1 to version 2.

after executing "sls login" we get the following warnings display:
```
npx sls login
Serverless: Configuration warning:
Serverless:   at 'provider.environment.DB_ENDPOINT': unsupported configuration format
Serverless:   at 'provider.environment.DB_PORT': unsupported configuration format
Serverless:   at 'provider.environment.DB_NAME': unsupported configuration format
Serverless:   at 'provider.environment.DB_USERNAME': unsupported configuration format
Serverless:   at 'provider.environment.DB_PASSWORD': unsupported configuration format
Serverless:   at 'provider.environment.ORDERARTICLES_S3_BUCKET': unsupported configuration format
Serverless:   at 'provider.environment.ORDERARTICLES_FILENAME_EXTENSION': unsupported configuration format
Serverless:   at 'provider.environment.ORDERARTICLES_FILEPATH': unsupported configuration format
Serverless:   at 'app': should match pattern "^[a-z0-9][a-z0-9-]{1,37}[a-z0-9]$"
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Logging you in via your default browser...
Serverless: You sucessfully logged in to Serverless.
```

the serverless.yml in the warned about section looks like this:
```
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "eu-central-1"}
  stage: ${opt:stage, "development"}
  environment:
    DB_ENDPOINT: ${param:DB_ENDPOINT}
    DB_PORT: ${param:DB_PORT}
    DB_NAME: ${param:DB_NAME}
    DB_USERNAME: ${param:DB_USERNAME}
    DB_PASSWORD: ${param:DB_PASSWORD}
    ORDERARTICLES_S3_BUCKET: ${param:ORDERARTICLES_S3_BUCKET}
    ORDERARTICLES_FILENAME_EXTENSION: ${param:ORDERARTICLES_FILENAME_EXTENSION}
    ORDERARTICLES_FILEPATH: ${param:ORDERARTICLES_FILEPATH}
```
