### ISSUE TITLE
Stack remove fail to remove EventBridge because it has rules associated

### ISSUE THREAD

**Issue by onhate** [serverless/serverless#8479]
Because I use the same EventBridge on many lambdas I have to create the EventBridge resource separated and add events (rules) pointing to the Eventbus's Arn

```yml
custom:
  eventBus: EventBus-${self:custom.stage}
  eventBusArn: arn:aws:events:${self:custom.region}:${self:custom.account}:event-bus/${self:custom.eventBus}

functions:
  onXXX:
    handler: src/xxx.handler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          ...

  onYYY:
    handler: src/yyyhandler
    events:
      - eventBridge:
          eventBus: ${self:custom.eventBusArn}
          ...

resources:
  Resources:
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.eventBus}
```

I have tried reproducing this issue with smaller set of resources and tried to create a smaller serverless.yml but I did not succeed, my stack is pretty big we have about 180 resources, the only plugin we have is serverless-webpack and serverless-offline which does not affect production deployments.

But when I tried to remove my stack running `sls remove` it fails to remove EventBus saying that is cannot be removed because it has rules associated with it. It does not happens consistently but most of the time it does. It looks like some race condition that tries to remove the EventBus before the lambdas are removed or something like this, I'm posting this issue as placeholder while I collect more evidences and create a reproducible serverless.yml

```
CloudFormation - DELETE_FAILED - AWS::CloudFormation::Stack - xxx-lab
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=xxx-lab
 
  Serverless Error ---------------------------------------
 
  An error occurred: EventBus - EventBus can't be deleted since it has rules. (Service: AWSEvents; Status Code: 400; Error Code: ValidationException; Request ID: f70115d1-bd84-4f8d-bbae-ba11948b8d86).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.4
     Framework Version:         2.8.0
     Plugin Version:            4.1.1
     SDK Version:               2.3.2
     Components Version:        3.2.3
```
