### ISSUE TITLE
In serverless versions 2.3.0 and higher, Resolution of Nested Variables is incomplete / broken

### ISSUE THREAD

**Issue by logicalor** [serverless/serverless#8487]
Serverless 2.3.0 and higher does not always resolve nested variables correctly.  Presumably Serverless supports nested variables, as they are [mentioned in Serverless' documentation](https://www.serverless.com/framework/docs/providers/aws/guide/variables/#pseudo-parameters-reference), and resolved correctly prior to v2.3.0.  

The example below is a version of the aws-nodejs template (ie what is created when running `serverless create --template aws-nodejs`) modified to include a nested variable to define `provider.region`.  `provider.region` is then used to provide an environment variable to the handler.  The handler code is modified to emit the provided environment variable.

As the examples demonstrate, in serverless v2.2.0 and below, the region is correctly interpreted from the yml config and passed into the handler.  In 2.3.0 and higher, the region is not correctly interpreted, and instead a literal fragment of the nested variable is passed instead.

I believe this is due to a [regex change that was introduced in v2.3.0](https://github.com/serverless/serverless/compare/v2.2.0...v2.3.0#diff-7b7d751f2df28f817f1976de1e894047b20630e5ec9b14738918125bb0e63e3c) to [address CloudFormation variable label collisions](https://github.com/serverless/serverless/issues/3184), which has had the inadvertent effect of breaking nested variable resolution.  My belief that this is the issue is further reinforced by the fact if I revert the regex in question in any ^2.2.0 version of serverless, the problem goes away.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-bork
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.${env.STAGE, 'development'}.regions.${self:custom.${env.STAGE, 'development'}.defaultRegion}, ${env:AWS_REGION, 'ap-southeast-2'}}
  environment:
    TEST_REGION: ${self:provider.region}

functions:
  hello:
    handler: handler.hello

custom:
  development:
    defaultRegion: "0"
    regions:
      - ap-southeast-2
      - ap-southeast-1
  staging:
    defaultRegion: "0"
    regions:
      - ap-southeast-2
      - ap-southeast-1
  production:
    defaultRegion: "0"
    regions:
      - ap-southeast-2
      - ap-southeast-1
```

</details>

<details>
<summary><code>handler.js</code></summary>

```
'use strict';

module.exports.hello = async event => {
  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: `Region is ${process.env.TEST_REGION}`,
        input: event,
      },
      null,
      2
    ),
  };
};
```

</details>

<details>
<summary><b><code>(serverless v2.2.0) serverless invoke local -f hello --data {}</code> output</b></summary>

```
{
    "statusCode": 200,
    "body": "{\n  \"message\": \"Region is ap-southeast-2\",\n  \"input\": {}\n}"
}

```
</details>

<details>
<summary><b><code>(serverless ^v2.2.0) serverless invoke local -f hello --data {}</code> output</b></summary>

```
Serverless: Configuration warning at 'provider.region': should be equal to one of the allowed values [us-east-1, us-east-2, us-gov-east-1, us-gov-west-1, us-west-1, us-west-2, af-south-1, ap-east-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1, eu-north-1, eu-south-1, eu-west-1, eu-west-2, eu-west-3, me-south-1, sa-east-1]
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
{
    "statusCode": 200,
    "body": "{\n  \"message\": \"Region is ${self:custom.${env.STAGE, 'development'}.regions.${self:custom.${env.STAGE, 'development'}.defaultRegion}, ap-southeast-2}\",\n  \"input\": {}\n}"
}
```

</details>

<b>Installed version</b>

```
Framework Core: 2.11.0
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```
