### ISSUE TITLE
API Gateway Resource Provider "unsupported configuration format"

### ISSUE THREAD

**Issue by rcedwardsiii** [serverless/serverless#8488]
> API Gateway Resource Provider "unsupported configuration format"

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myservice

frameworkVersion: ^2.11.0

provider:
  name: aws
  runtime: nodejs12.x
  endpointType: PRIVATE
  apiGateway:
    shouldStartNameWithService: true
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
 
```

</details>

<details>
<summary><b><code>sls package -v</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Configuration warning at 'provider.resourcePolicy[0].Resource[0]': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<b>Installed version</b>

```
Framework Core: 2.11.0
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

**Comment by rcedwardsiii** [comment]
Even though there is a warning, the policy is deployed successfully as expected.

**Comment by medikoo** [comment]
@rcedwardsiii thanks for report. As I check (by inspecting internals) config validation complains about `execute-api:/*/*/*` at `Resource`.

By schema it's an _arn_ pattern that's expected there, and any _arn_ pattern starts with `arn:`.

Technically if referenced via `arn:aws:execute-api:/*/*/*` you wouldn't see any warning (see https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-iam-policy-examples-for-api-execution.html)

Are you sure that notation where `arn: aws` prefix is stripped is supported well on AWS side? It might be that AWS doesn't throw an error for you but resource remains not recognized as expected

**Comment by rcedwardsiii** [comment]
@medikoo thanks for the follow up. The link and arn format you are referring to are IAM based policy. The item is question is an API Gateway _**resource**_ based policy. (see https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-examples.html)

Resource Section: `execute-api:/stage/GET/pets`

Also, you can reference this directly from the **serverless.com** documentation: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
```yaml
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - '123.123.123.123'
```
Note, AWS automatically expands this out in the policy when applied to include the API gateway name:

`arn:aws:execute-api:us-east-1:<_ACCOUNT_>:<_ENDPOINT_NAME_>/\*/\*/\*`

Hope this helps to clarify.
