### ISSUE TITLE
Trying to populate non string value into a string for variable ${self:provider.deploymentBucket}. Please make sure the value of the property is a string.

### ISSUE THREAD

**Issue by sidgupta94** [serverless/serverless#8491]
When I try to deploy with serverless versions >= 2.10.0, I get the following error:
`Trying to populate non string value into a string for variable ${self:provider.deploymentBucket}. Please make sure the value of the property is a string.`
Earlier, it automatically used to take the deployment bucket name when I refer ${self:provider.deploymentBucket}. Now, that behaviour seems to have changed.

<details>
<summary><code></code></summary>

```yaml
service: abc

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, self:provider.stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  endpointType: REGIONAL
  role: abcServiceDefaultRole
  environment: ${self:custom.environment.${self:provider.stage}}
  memorySize: 3008
  timeout: 30
  deploymentBucket:
    name: travelstop-${self:provider.stage}-deploys
    serverSideEncryption: AES256
```

</details>

<details>
<summary><b><code>sls deploy --stage dev --region ap-south-1</code></b></summary>

```
`Trying to populate non string value into a string for variable ${self:provider.deploymentBucket}. Please make sure the value of the property is a string.`

```

</details>

<b>Installed version</b>

```
Framework Core: 2.10.0
```
