### ISSUE TITLE
Support API Gateway setting to disable the default REST API endpoint (disableExecuteApiEndpoint)

### ISSUE THREAD

**Issue by KnupMan** [serverless/serverless#8492]
### Use case description

[Amazon API Gateway now supports disabling the default REST API endpoint](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-api-gateway-now-supports-disabling-the-default-rest-api-endpoint/), so when I am using a custom domain name for an API, which is created via Serverless, I would like also to have the ability to disable this option.

### Proposed solution

This option is an API-wide and can be introduced in the same way as `provider.apiGateway.apiKeySourceType` property.
However the CF RestApi resource doesn't support `disableExecuteApiEndpoint` for now, but the support will be added soon.

The serverless config would look like:
```yaml
service: myService

provider:
  ...
  apiGateway:
    disableExecuteApiEndpoint: true # allow boolean as a value (by default API GW is created with this option set to "false")
```
