### ISSUE TITLE
devDependencies aren’t excluded work with npm 7

### ISSUE THREAD

**Issue by iamakulov** [serverless/serverless#8500]
With npm 7, `serverless` fails to exclude `devDependencies` from `package.json`. This is likely due to the fact that npm 7 changed the lockfile format (`lockfileVersion` is now 2).

<details>
<summary><code>serverless.yml</code></summary>

The `serverless.yml` was taken from [the official starter](https://github.com/serverless/serverless-starter).

```yaml
service: serverless-starter

provider:
  name: aws
  runtime: nodejs4.3

functions:
  single:
    handler: single.handler
    events:
      - http:
          path: single
          method: get
      - http:
          path: single
          method: post
  multiCreate:
    handler: multiCreate.handler
    events:
      - http:
          path: multi/create
          method: get
  multiShow:
    handler: multiShow.handler
    events:
      - http:
          path: multi/show/{id}
          method: get
```

</details>

<details>
<summary>Steps to reproduce</summary>

Incorrect behavior with npm 7.0.8:

```sh
# Clone the official starter
git clone https://github.com/serverless/serverless-starter
cd serverless-starter

# Switch to Node 15 which comes with npm 7 (using https://github.com/tj/n)
sudo n 15
npm --version
# → 7.0.8

# Add a devDependency
npm i --save-dev serverless
npx serverless version
# → Framework Core: 2.11.1 (local)
# → Plugin: 4.1.2
# → SDK: 2.3.2
# → Components: 3.3.0

# Package the function
npx serverless package
du -h .serverless/serverless-starter.zip
# → 35M	.serverless/serverless-starter.zip
```

Correct behavior with npm 6.14.8:

```sh
# Clone the official starter
git clone https://github.com/serverless/serverless-starter
cd serverless-starter

# Switch to Node 12 which comes with npm 6 (using https://github.com/tj/n)
sudo n 12
npm --version
# → 6.14.8

# Add a devDependency
npm i --save-dev serverless
npx serverless version
# → Framework Core: 2.11.1 (local)
# → Plugin: 4.1.2
# → SDK: 2.3.2
# → Components: 3.3.0

# Package the function
npx serverless package
du -h .serverless/serverless-starter.zip
# → 72K	.serverless/serverless-starter.zip
```

</details>

<b>Installed version</b>

```
Framework Core: 2.11.1 (local)
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```
