### ISSUE TITLE
Support Price Class in CloudFront Events

### ISSUE THREAD

**Issue by ljwagerfield** [serverless/serverless#8502]
### Use case description

I need to specify different price classes for my Lambda@Edge functions.

### Proposed solution

Add a `priceClass` property to the `cloudFront` event type.

**Comment by ljwagerfield** [comment]
Since `PriceClass` is a distribution-level attribute, having multiple `PriceClass`es would require multiple distributions.

There's also other distribution-level attributes, like logging, geo-restrictions, HTTP2, and so forth...

**I'd like to extend my feature request** to allow all distribution-level attributes to be settable, and have Serverless create the appropriate number of distributions (i.e. reusing the same distribution for the functions where all these attributes match).

I've created a POC -- works fine for me:

https://github.com/upload-io/serverless/commit/b74c496692da27f05d602a07a51b165d17f8dd72?branch=b74c496692da27f05d602a07a51b165d17f8dd72&diff=split

**Comment by medikoo** [comment]
@ljwagerfield Thanks for proposal.

I believe we can do that. We could probably go that route:

```yaml
provider:
  cloudFront:
    distributions:
      default:
        # Eventual customizations to default distribution (one created by the Framework now)
        priceClass: PriceClass_100
      other:
        # Settings for custom distributions to be used instead of default one
        priceClass: PriceClass_200

functions:
  function:
    events:
      - cloudFront:
          distribution: other # Indicate to use "other" (not default) distribution)
```

This definitely will require a certain refactor in [lib/plugins/aws/package/compile/events/cloudFront/index.js](https://github.com/serverless/serverless/blob/cc103f147eddcb29e38937326cc551473925e535/lib/plugins/aws/package/compile/events/cloudFront/index.js), so different distributions are supported.

Let me know what you think

**Comment by ljwagerfield** [comment]
This sounds great.

I've also needed to add **origin groups** to the distribution, but perhaps this can be a separate ticket.

I mention it to make sure we don't paint ourselves into a corner -- but your solution looks good and could be later expanded to support origin groups (just like I have in my fork of Serverless).

I know it's unrelated, but if you're interested, the code on my fork allows the following setup:

```yaml
functions:
  myFunc:
    handler: myFunc.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin: ${self:custom.originGroupUri}
          distribution: ${self:custom.cdn1Distribution}
      - cloudFront:
          eventType: viewer-request
          origin: ${self:custom.originGroupUri}
          distribution: ${self:custom.cdn2Distribution}

custom:
  origins:
    primary:
      Id: primary-origin
      DomainName: foo.s3.amazonaws.com
      S3OriginConfig:
        OriginAccessIdentity:
          Fn::Join:
            - ''
            - - 'origin-access-identity/cloudfront/'
              - Ref: cloudFrontOAI
    secondary:
      Id: secondary-origin
      DomainName: example.com
      CustomOriginConfig:
        OriginProtocolPolicy: match-viewer
  originList:
    - ${self:custom.origins.primary}
    - ${self:custom.origins.secondary}

  originGroup:
    id: origin-group
    failoverCriteria:
      - 403
    members:
      - ${self:custom.origins.primary.Id}
      - ${self:custom.origins.secondary.Id}
  originGroupList:
    - ${self:custom.originGroup}
  originGroupUri: group://${self:custom.originGroup.id}

  cdn1Distribution:
    name: CDN1
    origins: ${self:custom.originList}
    originGroups: ${self:custom.originGroupList}
    properties:
      PriceClass: PriceClass_100
  cdn2Distribution:
    name: CDN2
    origins: ${self:custom.originList}
    originGroups: ${self:custom.originGroupList}
    properties:
      PriceClass: PriceClass_All

resources:
  Resources:
    ...
```

The main difference I guess is that I have a `properties` section that simply drops down into CloudFormation config -- but the abstraction you've mentioned seems safer, as you don't want people clobbering auto-generated stuff.
