### ISSUE TITLE
Adding a serverless.js file breaks expected functionality for Next.js Serverless Component with next-i18next support

### ISSUE THREAD

**Issue by kylekirkby** [serverless/serverless#8503]
I'm trying to deploy the infrastructure required running a multi-environment next.js app with i18n support. There is an issue where the `@sls-next/serverless-component` fails to add the translation JSON files to the `default-lambda` src. Someone in another issue (https://github.com/serverless-nextjs/serverless-next.js/issues/383#issuecomment-667716885) suggested extending the `sls-next/serverless-component` with a `serverless.js` file. This seems logical and great until adding this file breaks everything else. Adding a `serverless.js` file to extend a component results in `serverless` requiring a `service` and `provider` property but then still fails to deploy as expected.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
myNextApp:
  component: "./"
  inputs:
    timeout: 30
  memory: 1024
```

</details>

<details>
<summary><code>serverless.js</code></summary>

```js
// serverless.js
const NextJsComponent = require("serverless-next.js/serverless");
const fs = require("fs-extra");

class MyNextJsComponent extends NextJsComponent {
  async default(inputs = {}) {
    if (inputs.build !== false) {
      console.log("-> Building...");
      await this.build(inputs);
      console.log("Building was successful");
    }
    console.log("-> Copying locales directory...");
    this.copyLocales();
    console.log("Locale directory was copied successfully");
    console.log("-> Updating manifest...");
    this.updateNonDynamicManifest();
    console.log("Manifest update successful");
    console.log("-> Deploying...");
    return this.deploy(inputs);
  }

  copyLocales() {
    const localeSrc = "./static/locales";
    const localeDest = "./.serverless_nextjs/default-lambda/static/locales";
    fs.copySync(localeSrc, localeDest, { recursive: true });
  }

  updateNonDynamicManifest() {
    const manifestFileName =
      "./.serverless_nextjs/default-lambda/manifest.json";
    const manifestJson = require(manifestFileName);
    manifestJson.pages.ssr.nonDynamic["/index"] = "pages/index.js";
    fs.writeFileSync(manifestFileName, JSON.stringify(manifestJson));
  }
}

module.exports = MyNextJsComponent;

```

</details>

<details>
<summary><b><code>npx serverless</code> output</b></summary>

```yaml
  Serverless Error ---------------------------------------

  "service" property is missing in serverless.yml

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.1
     Framework Version:         2.11.1 (standalone)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.3.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.11.1 (standalone)
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

**Comment by dphang** [comment]
The way next-18n works is that it expects locales to be in the local filesystem (Lambda in this case), however the component doesn't know about specific packages like next-18n. Two things:

1. Actually I added an input `builds.postBuildCommands` which lets you run arbitrary commands after **build** but before **deploy**. So you can use it to add additional things into the `.serverless_nextjs` directory. For example, you can copy files into `default-lambda`, which is useful for next-18n or other similar packages that need files in the local filesystem (Lambda in this case). See here: https://github.com/serverless-nextjs/serverless-next.js/issues/767#issuecomment-722756351. You can try to copy the locales files using that method by adding any JS script, e.g `your-script.js`. Then you can execute it by adding `postBuildCommands: ["node your-script.js"]`, and it will run in between build and deploy steps.

2. For extending the component, you should try to inspect the structure `@sls-next/serverless-component` package and might need to point it to something like `/Users/danielphang/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.18/node_modules/@sls-next/serverless-component/dist/component.js` instead (or `src/component.ts` might work if you have TypeScript).

I think that error happens when Serverless can't resolve the component, then treats it like a regular Serverless framework app, not Serverless Components (it has to extend Component which is from Serverless).

**Comment by kylekirkby** [comment]
Wow! Thank you @dphang for the in-depth reply! 

> Actually I added an input build.postBuildCommands which lets you run arbitrary commands after build but before deploy. So you can use it to add additional things into the .serverless_nextjs directory. For example, you can copy files into default-lambda, which is useful for next-18n or other similar packages that need files in the local filesystem (Lambda in this case). See here: serverless-nextjs/serverless-next.js#767 (comment). You can try to copy the locales files using that method by adding any JS script, e.g your-script.js. Then you can execute it by adding postBuildCommands: ["node your-script.js"], and it will run in between build and deploy steps.

This seems like a totally logical way to copy over the locales files. I don't know why I didn't think of/see this in the README.  
> ```js
> import NextJsComponent from "@sls-next/serverless-component";
> ```
> or
> ```js 
> const NextJsComponent = require("@sls-next/serverless-component");
> ```
I've just tried adding the `@sls-next/serverless-component` to my `package.json` and importing/requiring using the suggestions you provided but still get:
```yaml

  Serverless Error ---------------------------------------

  "service" property is missing in serverless.yml

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.18.1
     Framework Version:         2.11.1 (standalone)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.3.0
```
I'm starting to think that `serverless` may have removed the functionality for extending a component and importing directly. From the documentation I cannot see any reference to using ./ to import an extended version of a component.

I'm going to try using the postBuildCommands suggestion now and see where I get! Thank you again!
