### ISSUE TITLE
AWS Lambda: Support Fn::Split in `vpc.securityGroupIds` and `vpc.subnetIds` configurations

### ISSUE THREAD

**Issue by vmj** [serverless/serverless#8513]
`sls` produces correct CloudFormation, but issues a configuration warning. This has been discussed and fixed in issue #8282 but I guess `Split` function slipped the radar.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: hello-world
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  vpc:
    subnetIds: !Split
      - ','
      - "sn1,sn2"
    securityGroupIds: !Split
      - ','
      - "sg1,sg2"

functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b>output</b></summary>

```
✔ ~/src/testing/serverless-fw/hello-world ➭ sls package
Serverless: Configuration warning:
Serverless:   at 'provider.vpc.securityGroupIds': should be array
Serverless:   at 'provider.vpc.subnetIds': should be array
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.11.1 (local)
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

**Comment by medikoo** [comment]
@vmj thanks for reporting. Indeed as we pass those setting as is to CloudFormation template, we should openly support functions as `Fn::Split`.

Question is what else in terms of intrinsic functions should be supported in such case?

**Comment by vmj** [comment]
@medikoo Ah, I missed that it is the short form `!Split` that triggers the warning, and `Fn::Split` works without a warning.  Thanks!

I'll take a look over the weekend if I manage to produce a PR, unless someone beats me to it.  I'm not at all familiar with the code base but I'm thinking of making short form work the same as long form.  Or do you already know it won't work?

**Comment by medikoo** [comment]
@vmj In my understanding `!Split` is resolved to `Fn::Split` **before** config validation, and it's `Fn::Split` notation that is not recognized.

In config schema we support only array notation currently: https://github.com/serverless/serverless/blob/3feafbceb5777904ea19aab1765c85935d5aa904/lib/plugins/aws/provider/awsProvider.js#L431

**Comment by vmj** [comment]
@medikoo I just tried a couple of times, and `!Split` triggers a warning, `Fn::Split` does not.

**Comment by medikoo** [comment]
> @medikoo I just tried a couple of times, and !Split triggers a warning, Fn::Split does not.

Can you share `Fn::Split` configuration variant?

**Comment by roball24** [comment]
I can confirm the warning is logged with `Fn::Split` for me

**Comment by vmj** [comment]
Sorry, I was wrong.

```yaml
service: hello-world
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  vpc:
    subnetIds: Fn::Split [',', "sn1,sn2"]
    securityGroupIds: Fn::Split
      - ','
      - "sg1,sg2"

functions:
  hello:
    handler: handler.hello
```

with above and `sls package`, there's no warning but the output doesn't look valid.  It contains:

```json
        "VpcConfig": {
          "SecurityGroupIds": [
            "Fn::Split - ',' - \"sg1,sg2\""
          ],
          "SubnetIds": [
            "Fn::Split [',', \"sn1,sn2\"]"
          ]
        }
```

But with following `serverless.yml`:

```yaml
service: hello-world
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  vpc:
    subnetIds: !Split [',', "sn1,sn2"]
    securityGroupIds: !Split
      - ','
      - "sg1,sg2"

functions:
  hello:
    handler: handler.hello
```

and `sls package`, you should get a warning and valid output:

```json
        "VpcConfig": {
          "SecurityGroupIds": {
            "Fn::Split": [
              ",",
              "sg1,sg2"
            ]
          },
          "SubnetIds": {
            "Fn::Split": [
              ",",
              "sn1,sn2"
            ]
          }
        }
```

**Comment by vmj** [comment]
Yet another correction.  The correct long form is:

```yaml
service: hello-world
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  vpc:
    subnetIds:
      Fn::Split: [',', "sn1,sn2"]
    securityGroupIds:
      Fn::Split:
        - ','
        - "sg1,sg2"

functions:
  hello:
    handler: handler.hello
```

and now it behaves the same as `!Split` in the original issue comment: warning and valid output.

**Comment by takeda** [comment]
@vmj this is just a nitpick, because I seen this everywhere, you wrote:

```yaml
    subnetIds:
      Fn::Split: [',', "sn1,sn2"]
    securityGroupIds:
      Fn::Split:
        - ','
        - "sg1,sg2"
```

it's probably better to write it like this:
```yaml
    subnetIds: {"Fn::Split": [",", "sn1,sn2"]}
    securityGroupIds: {"Fn::Split": [",", "sg1,sg2"]}
```

I doubt this will solve the original issue (I think it will require serverless code change), but it makes easier to read when the long form is used.

@medikoo to answer your question here's what I'm doing in my configuration:
```yaml
    vpc:
      subnetIds: !Split [",", !ImportValue PrivateSubnets]
      securityGroupIds:
      - !ImportValue DefaultSecurityGroup
```

Ideally I think all functions should be supported. I also think this will be a problem for validation. For example if I use !Ref it typically is a string, but I believe it could also be an array if I would use a parameter of an array type (it doesn't look to me like it makes sense to use parameters, but maybe there actually is a use case where it would be beneficial)

**Comment by younghoonk17** [comment]
Any updates on this? 

I would also like to use `Fn::GetAtt` to get values from our `Custom::ResourcesLookup`. 

This snippet works but produces warning.

```yaml
vpc:
    subnetIds: 
      "Fn::GetAtt":
        - CustomResourcesLookup
        - ResourceId
```

**Comment by medikoo** [comment]
This was addressed with https://github.com/serverless/serverless/pull/9266 (for some reason issue was not closed then, closing it now)

**Comment by medikoo** [comment]
@younghoonk17 in terms of `Fn::GetAtt`, it supported, but on _item_ level not _array_ level, so following will work:

```yaml
vpc:
  subnetIds: 
    - "Fn::GetAtt":
      - CustomResourcesLookup
      - ResourceId
```
