### ISSUE TITLE
Deployment in CI/CD does not work (probably reated to login and/or stage)

### ISSUE THREAD

**Issue by Clemens85** [serverless/serverless#8536]
I am trying to get the deployment of a simple lambda to work on my CI/CD system (CircleCI), but now after probably spending half a day and reading lots of related issues, I am giving up, but provide an issue in here due to  I have absolutely no clue about what I am doing wrong....

So what is the problem?
I got firstly lots of errors like "Trying to populate non string value into a string for variable ${opt:stage}. Please make sure the value of  the property is a string." (and similar related errors to that one)
I then found many github issues like these ones:
- https://github.com/serverless/serverless/issues/3210
- https://github.com/Nordstrom/serverless-artillery/issues/72
- https://github.com/serverless/serverless/issues/4942
- https://github.com/serverless/serverless/issues/3714
- https://github.com/serverless/serverless/issues/5235

What did I try?
Firstly, I updated  to the latest serverless version (2.12.0).
I then tried several different configs in my severless.yml, e.g. just using the opt:stage variable, or using the self:provider.stage variable etc....  
... But I think after all this is not the real problem... on my local machine (Ubuntu 16) I can successfully deploy... so I think it is more an issue with the CI system (also using Linux) and the needed serverless login...

This is the code (after installing the needed dependencies) on my CI system:
`AWS_ACCESS_KEY_ID=XXX`
`AWS_SECRET_ACCESS_KEY=XXX`
`SERVERLESS_ACCESS_KEY=XXX`
`GOOGLE_MAPS_KEY_JS=XXX`
`echo "GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_KEY_JS}" > secrets.prod.yml # Workaround for not working plugin`
`serverless login`
`serverless deploy --stage prod`

When I don't perform the login step (line 5), and try to just execute the deploy step,  I get an SLS error indicating that I must login before deploying. I realized that for doing so, I must therefore setup a valid SERVERLESS_ACCESS_KEY.
But now, when I execute this  build-step, the build hangs because it wants to perform a browser based login.... (see output in Q3)

At the beginning of my description I wrote something about errors with the stage... I think that this is somehow related to the problem I now have, Because at the beginning of my attempts, my provider-confing in the serverless.yml looked like that:
```
...
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
...
```

And that gave me the following output when trying to perform the login:
```
 Serverless Warning --------------------------------------
  A valid option to satisfy the declaration 'opt:stage' could not be found.
 
 Serverless Warning --------------------------------------
  A valid service attribute to satisfy the declaration 'self:provider.stage' could not be found.
 
 Serverless Warning --------------------------------------
  A valid option to satisfy the declaration 'opt:stage,self:provider.stage' could not be found.
 
  Serverless Error ---------------------------------------
  Trying to populate non string value into a string for variable ${self:provider.stage}. Please make sure the value of the property is a string.
```

This is really strange and quite annoying, because I have absolutely no idea what might be wrong... (therefore I assume that it might be a bug?!). Any help is really appreciated!

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: geocode-service
app: myorg-functions
org: myorg

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-central-1
  environment:
    BACKEND_BASE_URL: ${self:custom.backendBaseUrl.${opt:stage, self:provider.stage}}
    GOOGLE_MAPS_API_KEY: ${self:custom.secrets.GOOGLE_MAPS_API_KEY}

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
  stages:
    - dev
    - prod
  backendBaseUrl:
    dev: 'https://localhost/rest'
    prod: 'https://myorg.eu/rest'

  serverless-offline-sqs:
    autoCreate: true                 # create queue if not exists
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-central-1
    accountId: x
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

functions:
  update-sqs:
    handler: geocode-service/handlerSqs.update
    events:
      - sqs:
          batchSize: 1
          queueName: geocode
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - geocode

package:
  individually: true

plugins:
  - serverless-plugin-reducer
  - serverless-offline-sqs
  - serverless-offline
  - serverless-secrets-plugin
```

</details>

<details>
<summary><b><code>
SERVERLESS_ACCESS_KEY=XXX
serverless login
</code> output</b></summary>

```
 Serverless Warning --------------------------------------
 
  A valid file to satisfy the declaration 'file(secrets.prod.yml)' could not be found.
 
 
 Serverless Warning --------------------------------------
 
  A valid file to satisfy the declaration 'file(secrets.prod.yml)' could not be found.
 
Serverless: Configuration warning at 'functions['update-sqs'].events[0].sqs': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Logging you in via your default browser...
```

</details>

<b>Installed version</b>

```
2.12.0
```

**Comment by medikoo** [comment]
@Clemens85 this tracker is purely for confirmed bug reports and feature requests.

For general support please check:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

**Comment by aeciolevy** [comment]
@Clemens85 @medikoo I am having the same issue.


<details>
  <summary>serverless.yml</summary>

```
service: click-vaquejada-auth

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs12.x

custom:
  stage: ${opt:stage}

resources:
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
```

</details>

<details>
<summary> congnito-user-pool.yml </summary>

```
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:service}-${self:custom.stage}-user-pool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: False
          RequireNumbers: True
          RequireSymbols: False
          RequireUppercase: True

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:service}-{self:custom.stage}-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
  # for access app sync on AWS console
  UserPoolClientPlayground:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:service}-${self:custom.stage}-client-playground
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false

# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool
  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
  UserPoolClientPlayground:
    Value:
      Ref: UserPoolClientPlayground
```

</details>

### Error
```
An error occurred: CognitoUserPoolClient - 1 validation error detected: Value 'click-vaquejada-auth-{self:provider.stage}-user-pool-client' at 'clientName' 
failed to satisfy constraint: Member must satisfy regular expression pattern: [\w\s+=,.@-]+ (Service: 
AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: a9af1d4a-6d1b-44a1-bc1d-23239f21e344; Proxy: null).
```

### Sls Print

```
  A valid option to satisfy the declaration 'opt:stage' could not be found.
```
