### ISSUE TITLE
kinesis event trigger is missing kinesis:ListShards in default iam role

### ISSUE THREAD

**Issue by 5up3r20e** [serverless/serverless#8540]
serverless deployment is all good
but we caught some permission issue in cloudtrail
AccessDenied

User: arn:aws:sts::<accountId>:assumed-role/<rolename>/awslambda_719_20201123193819853 is not authorized to perform: kinesis:ListShards on resource: <stream arn>

when checked the default iam role created by serverless https://github.com/serverless/serverless/blob/6c6881c853d9a42ed3c99f7c7acaa7cb98bd0a1b/lib/plugins/aws/package/compile/events/stream/index.js#L108
the permission is 
{
                  "Effect": "Allow",
                  "Action": [
                    "kinesis:GetRecords",
                    "kinesis:GetShardIterator",
                    "kinesis:DescribeStream",
                    "kinesis:ListStreams"
                  ],
                 "Resource": [
                       <stream arn>
                  ]
}

according to aws document https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html
the required permission is
kinesis:DescribeStream

kinesis:DescribeStreamSummary

kinesis:GetRecords

kinesis:GetShardIterator

kinesis:ListShards

kinesis:ListStreams

kinesis:SubscribeToShard

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  handleKinesisStream:
    handler: src/handler.handleKinesisStream
    events:
      - stream:
          type: kinesis
          arn: <kinesis stream arn>
```

</details>

<details>

</details>

<b>Installed version</b>

```
Framework Core: 2.2.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.1.4
```
