### ISSUE TITLE
Serverless deploy does not fire rollback lifecycle event

### ISSUE THREAD

**Issue by paries** [serverless/serverless#8546]
When running a serverless deploy -v , if a codedeploy issues a rollback a rollback lifecycle is not fired (excuse me if that is not  the correct term or not)

I have created a simple serverless plugin to log the lifecycle events.

`        this.hooks = {
            'after:webpack:package:packExternalModules': this.packExternalModules.bind(this),
            'before:aws:deploy:deploy:updateStack': this.updateStack.bind(this),
            'after:rollback:rollback': this.rollback.bind(this),
            'before:rollback:rollback': this.rollback.bind(this),
            'before:rollback:initialize': this.rollback.bind(this),
            'after:rollback': this.rollback.bind(this),
            'rollback': this.rollback.bind(this),
            'aws:rollback:initialize': this.rollback.bind(this),
            'aws:rollback': this.rollback.bind(this),
            'before:aws:rollback': this.rollback.bind(this),
            'before:aws:rollback:rollback': this.rollback.bind(this)
        };`

after:webpack:package:packExternalModules consoles fine
before:aws:deploy:deploy:updateStack consoles fine

as you can see i try lots of different rollbacks and none of these ever log

below is the output of when i call this.serverless.cli.log

> Serverless: Uploading custom CloudFormation resources...
> Serverless: Validating template...
> Serverless: ****** before:aws:deploy:deploy:updateStack

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: emvio-ach
plugins:
- serverless-webpack
- serverless-offline
- serverless-prune-plugin
- serverless-domain-manager
- serverless-plugin-warmup
- serverless-plugin-canary-deployments
- serverless-plugin-aws-alerts
- "./src/my-hook-plugin"
- serverless-hooks
custom:
  warmup:
    prewarm: true
    timeout: 30
    enabled: true
  serverless-offline:
    port: 3014
  prune:
    automatic: true
    number: 3
  customDomain:
    certificateName: "${file(./config/serverlessConfig.js):getEnv.certificateName}"
    domainName: "${file(./config/serverlessConfig.js):getEnv.domainName}"
    basePath: ach
    stage: "${self:provider.stage}"
    createRoute53Record: false
  serverless-hooks:
    hookPrefix: hook
    runAllOptions:
      env: "${env:EMVIO_CONFIG_ENV}"
      slackChannel: randys_errors
provider:
  name: aws
  runtime: nodejs12.x
  stage: "${file(./config/serverlessConfig.js):getEnv.stage}"
  region: "${file(./config/serverlessConfig.js):getEnv.region}"
  timeout: 30
  role: "${file(./config/serverlessConfig.js):getEnv.iamRole}"
  tracing:
    lambda: true
  logs:
    restApi: true
  environment:
    NODE_ENV: "${env:NODE_ENV}"
    EMVIO_CONFIG_ENV: "${env:EMVIO_CONFIG_ENV}"
    SNS_EVENT: "${file(./config/serverlessConfig.js):getEnv.snsEvent}"
  vpc:
    securityGroupIds:
    - "${file(./config/serverlessConfig.js):getEnv.securityGroupId}"
    subnetIds:
    - "${file(./config/serverlessConfig.js):getEnv.subnetIdOne}"
    - "${file(./config/serverlessConfig.js):getEnv.subnetIdTwo}"
functions:
  tweety:
    handler: src/tweety.main
    timeout: 900
    memorySize: 2048
    maximumRetryAttempts: 0
    deploymentSettings:
      type: Canary10Percent5Minutes
      alias: Live
      alarms:
      - name: "${file(./config/serverlessConfig.js):getEnv.canary.alarmMetricAPIName}-alarm"
    events:
    - http:
        path: v3/tweety
        method: post
        cors: true
        authorizer:
          arn: "${file(./config/serverlessConfig.js):getEnv.basicAuthorizer}"
  databaseUpdates:
    handler: src/databaseUpdates.main
    description: Update database

```

</details>

<details>
<summary><b><code>serverless deploy -v</code> output</b></summary>

```
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - TweetyLambdaVersion10Hgqtk5p5TtINLkG44bCi7k6Vy0yAYUdqz23kq19AU
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - CreateAchBrokerLambdaFunctionAliasLive
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - TweetyLambdaFunctionAliasLive
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - GetAchSummaryLambdaFunctionAliasLive
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - CreateAchBrokerLambdaFunctionAliasLive
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - TweetyLambdaFunctionAliasLive
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - GetAchSummaryLambdaFunctionAliasLive
Serverless: [AWS cloudformation 200 0.502s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
Serverless: [AWS cloudformation 200 0.417s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
Serverless: [AWS cloudformation 200 0.412s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - GetAchSummaryLambdaFunctionAliasLive
CloudFormation - UPDATE_FAILED - AWS::Lambda::Alias - GetAchSummaryLambdaFunctionAliasLive
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - TweetyLambdaFunctionAliasLive
Serverless: [AWS cloudformation 200 0.416s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Alias - CreateAchBrokerLambdaFunctionAliasLive
Serverless: [AWS cloudformation 200 0.43s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
CloudFormation - UPDATE_FAILED - AWS::Lambda::Alias - CreateAchBrokerLambdaFunctionAliasLive
Serverless: [AWS cloudformation 200 0.42s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
CloudFormation - UPDATE_FAILED - AWS::Lambda::Alias - TweetyLambdaFunctionAliasLive
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - emvio-ach-development
Serverless: [AWS cloudformation 200 0.413s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
Serverless: [AWS cloudformation 200 0.415s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - TweetyLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - GetAchSummaryLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - WarmUpPluginLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - BrokerAchCreateLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - CustomDashresourceDashapigwDashcwDashroleLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - CreateAchBrokerLambdaFunction
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - DatabaseUpdatesLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - CustomDashresourceDashapigwDashcwDashroleLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - WarmUpPluginLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - TweetyLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - BrokerAchCreateLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - CreateAchBrokerLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - DatabaseUpdatesLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - GetAchSummaryLambdaFunction
Serverless: [AWS cloudformation 200 0.449s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:720154970215:stack/emvio-ach-development/364490d0-be4a-11e7-a414-50fae98974fd'
})
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Alias - TweetyLambdaFunctionAliasLive
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Alias - CreateAchBrokerLambdaFunctionAliasLive
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Alias - GetAchSummaryLambdaFunctionAliasLive
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - emvio-ach-development
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - BrokerAchCreateLambdaVersiongc9VN8qO0IK2ufwHXMr05MERcvp2ZXXdQeJoiLzLY
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - TweetyLambdaVersion10Hgqtk5p5TtINLkG44bCi7k6Vy0yAYUdqz23kq19AU
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - GetAchSummaryLambdaVersion8M85TyIFTwJKC0bmNLuS58dpQlvGR2vT18S0WhADFBU
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - CreateAchBrokerLambdaVersionjRkIKfb7HPNl2L3gYYk09E9pbV1vby9nZeMhGBNeE
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - WarmUpPluginLambdaVersionwJfhZt9cwu0U5gtnsONbKq9gyxYY8UfpvGWWirfTn8
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - DatabaseUpdatesLambdaVersionwB90zivKoExAj3NABbI18UFXfs2rOvDasyCzRSH50DA
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - emvio-ach-development
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation

  Serverless Error ---------------------------------------

  ServerlessError: An error occurred: GetAchSummaryLambdaFunctionAliasLive - Rollback successful.
      at /Users/randyparieswork/Projects/emvio-ach-service/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:94:23
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:126:23)
  From previous event:
      at /Users/randyparieswork/Projects/emvio-ach-service/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:27:12

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.0.0
     Framework Version:         1.83.0 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

</details>

<b>Installed version</b>

```
serverless --version
Framework Core: 1.51.0
Plugin: 1.3.11
SDK: 2.1.0
```
