### ISSUE TITLE
Error: {"message": "Internal server error"}

### ISSUE THREAD

**Issue by tbell511** [serverless/serverless#8548]
As of today, I'm running into an issue when deploying that I've never seen before.  I was successfully able to deploy a few weeks ago but now cannot. Even if I try to deploy the same commit that was last successful, I run into the same error.

A team member I work with, tried on their computer as well with the same result. 

We are getting this error, `Error: {"message": "Internal server error"}` coming from what appears to be `logsCollection.js`

Please let me know if I can provide any more info that would be helpful!

**Please Note: I replaced my actual org and app name with "my-org" and "my-app".**

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: my-org
app: my-org
service: my-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: 
    true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  profile: memberstack-api
  environment:
    DB_URL: ${self:custom.DB_URL}
    redis_port: ${self:custom.redis_port}
    redis_host: ${self:custom.redis_host}
    redis_password: ${self:custom.redis_password}
    
custom:
  DB_URL: ${env:DB_URL}
  redis_port: ${env:redis_port}
  redis_host: ${env:redis_host}
  redis_password: ${env:redis_password}

functions:
  api:
    handler: ./my-api/handler.handler
    events:
      - http: 
          path: /v1/members
          method: post
      - http:
          path: /v1/members/{param}
          method: post
      - http:
          path: /v1/members/{param}
          method: get
      - http:
          path: /v1/members
          method: get
      - http:
          path: /v1/members/{param}
          method: delete
    
```

</details>

<details>
<summary><b><code>serverless deploy -s dev</code> output</b></summary>

```
tyler@Tylers-MacBook-Pro my-app % SLS_DEBUG=* serverless deploy -s dev
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.3.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - redis_port
Serverless:      - redis_host
Serverless:      - redis_password
Serverless:      - DB_URL
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
platform-sdk fetching: POST https://api.serverless.com/core/tenants/my-org/applications/my-org/profileValue
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
platform-sdk fetching: GET https://api.serverless.com/core/meta
platform-sdk fetching: GET https://api.serverless.com/core/tenants/memberstack/applications/my-app
platform-sdk fetching: GET https://api.serverless.com/core/meta
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: [AWS sts 200 0.244s 0 retries] getCallerIdentity({})
platform-sdk fetching: POST https://api.serverless.com/malt/destinations/create
 
  Error --------------------------------------------------
 
  Error: {"message": "Internal server error"}
      at module.exports (/Users/tyler/node_modules/@serverless/enterprise-plugin/lib/logsCollection.js:74:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at ServerlessEnterprisePlugin.<anonymous> (/Users/tyler/node_modules/@serverless/enterprise-plugin/lib/plugin.js:435:11)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.12.0
     Framework Version:         2.3.0 (local)
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.3.0 (local)
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.0
```
