### ISSUE TITLE
Lambda EventBridge subscription "virtual" batching

### ISSUE THREAD

**Issue by PatrykMilewski** [serverless/serverless#8551]
### Use case description

As we know, EventBridge is great service for event-driven architectures. However due to lack of batching feature, it might be not always the best option to choose, since Lambdas might be not fast enough to catch up with events stream.

As Serverless user I would like to have an option, to have "virtual" batching, which is achievable by creating following data pipeline:
- Event publisher -> EventBridge -> SQS -> Lambda
- Event publisher -> EventBridge -> Kinesis Stream -> Lambda

It has pros and cons:
- SQS/Kinesis stream collects events and based on already existing Lambda features, batching with batch size and batch window can be enabled
- However the cost also increases, because you need to pay for both: EventBridge and SQS/Kinesis stream

Thanks to this we can have event bus architecture, while having batch windows and batch sizes defined.

Why do I think, that Serverless Framework should support that?
The problem is, that if I want to use this pattern, then I need to give up on Serverless built-in EventBridge <=> Lambda integration, which ends up creating some ugly-looking, plain CloudFormation code:
```yaml
functions:
  consumer:
    handler: consumer.handler
    events:
      - sqs:
         arn: !GetAtt SQS.Arn
         batchSize: 10

resources:
  Resources:
    EventBridgeSQSRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: "default"
        EventPattern: { "source": [ "my.custom.event" ]}
        State: ENABLED
        Targets:
          - Arn: !GetAtt SQS.Arn
            Id: "SQSRule"

  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQS
      PolicyDocument:
        Statement:
          - Action:
              - SQS:SendMessage
            Effect: "Allow"
            Resource: !GetAtt SQS.Arn
            Principal:
              Service:
                - "events.amazonaws.com"
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt EventBridgeSQSRule.Arn

  SQS:
    Type: AWS::SQS::Queue
```
Same thing can be done for Kinesis Stream.

I believe that it would extend EventBridge use cases and make it easier to use, with this additional layer of abstraction.

### Proposed solution

My proposed solution would be to hide all that logic behind Lambda events definition:
```yaml
functions:
  consumer:
    handler: consumer.handler
    events:
      - eventBridge:
          batching: "sqs" | "sqsfifo" (?) | "kinesis"
          batchSize: 1 ... 500
          batchWindow: 1 ... 300
          pattern:
            source:
              - "my.custom.event" 
```
Thanks to this additional abstraction, it's really easy to achieve batching for EventBridge events.

### Notes

Inspired by: 
https://medium.com/@jgilbert001/combining-the-best-of-aws-eventbridge-and-aws-kinesis-9b363b043ade
https://forum.serverless.com/t/cloudformation-eventbridge-and-sqs-rule/12644/2

I believe it's blocked until #7148 is resolved.

**Comment by medikoo** [comment]
@PatrykMilewski thanks for that, that's very interesting idea.

I'd just probably configure it as:

```yaml
functions:
  consumer:
    events:
      - eventBridge:
          batch:
            type: "sqs" | "kinesis" # Start with minimal, expand on demand
            size:
              minimum: 1
              maximum: 10000
            window:
              minimum: 1
              maximum: 300
```

> I believe it's blocked until #7148 is resolved.

Yes, I would definitely wait for that, and if we go with it, implement it just for CloudFormation variant

**Comment by PatrykMilewski** [comment]
@medikoo 
Looks good! I believe minimum and maximum properties are not needed, I just wanted to show that both SQS and Kinesis have the same min max values for those, so it could be simply:
```yaml
functions:
  consumer:
    events:
      - eventBridge:
          batch:
            type: "sqs" | "kinesis"
            size: 5000
            window: 150
```
