### ISSUE TITLE
Still, DisableLogs Does Not Disable the Creation of Log Groups

### ISSUE THREAD

**Issue by hagsfdf** [serverless/serverless#8554]
I added `disableLogs: true` under the function (NOT IN the `provider` section), as in the official documentation. 
`sls deploy` is executed with no error.

Then, the bunch of **previous** log groups are wiped out. But still, it makes a new log group and puts its log to it.

Our main concern is that, `putEvent` to the log group is being so expensive (due to frequent invocation). So we want to disable logging once in for all. I thought that setting `disableLogs: true` would serve our purpose. If it is not the way it works, could you give us an advice for another way to disable logging?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  myFunc:
    disableLogs: true
    handler: handler.handler_records
    description: Dynamo stream to kinesis record producer for ${opt:product} ApplicationProfiles (${self:provider.stage})
    events:
      - stream:
          arn: ${self:custom.${opt:product}.${self:provider.stage}.profile.dynamoStreamArn}
          batchSize: 100
          startingPosition: LATEST
    environment:
      KINESIS_STREAM_REGION: ${self:custom.${opt:product}.${self:provider.stage}.kinesisStreamRegion}
      KINESIS_STREAM_NAME: ${self:custom.${opt:product}.${self:provider.stage}.profile.kinesisStreamName}
      KINESIS_IAM_ROLE_ARN: ${self:custom.${opt:product}.${self:provider.stage}.kinesisIamRoleArn}
```

</details>

<b>Installed version</b>

```
(node:50165) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Framework Core: 1.77.1
Plugin: 3.6.18
SDK: 2.3.1
Components: 2.33.2
```
