### ISSUE TITLE
environment.variables' failed to satisfy constraint on defining _JAVA_OPTIONS for java runtimes in lambda

### ISSUE THREAD

**Issue by AnupamJuniwal** [serverless/serverless#8564]
I wanted to define and override some default JVM arguments that are placed by lambda by default, which I was able to do locally using `sam local` and `_JAVA_OPTIONS`. But when publishing the application to the cloud it seems like there is a constraint because of which I won't be able to define any env variables starting with `_` which does not make sense to me.
 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
Globals:
  Function:
    Environment:
      Variables:
        _JAVA_OPTIONS: -Xshare:off
```

</details>
