### ISSUE TITLE
Serverless: TypeError: Cannot read property 'outputs' of undefined #2

### ISSUE THREAD

**Issue by s1mrankaur** [serverless/serverless#8567]
```

service: testnewman
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-plugin-stack-config
  - serverless-plugin-newman
  - serverless-shell

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'simi33'}
  region: ${opt:region, 'us-west-2'}
  profile: ${opt:profile, 'sandbox'}


functions:
  hello:
    handler: handler.hello

custom:
  collection:
    file: test/postman_collection.json
  environment:
    file: test/deploy.postman_environment.json
    values:
      - key: endpoint
        enabled: true
        value: ServiceEndpoint
        type: OUTPUTS

```

This is what my serverless.yml file looks like. The lambda function gets created fine. 

When I run the command:

` serverless outputs --stage simi33 --region us-west-2`

It says:

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Retrieving Outputs...
Serverless: getValues.error: User: arn:aws:iam::102483920364:user/sikau is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-west-2:102483920364:stack/testnewman-simi33/*
Serverless: TypeError: Cannot read property 'outputs' of undefined
```
This isn't a permissions issue. I am otherwise able to deploy the application if not using stack-config plugin. 

If I run sls deploy -v command, This is what I get:

```

Stack Outputs
HelloLambdaFunctionQualifiedArn: arn:aws:lambda:us-west-2:102483920364:function:testnewman-simi33-hello:1
ServerlessDeploymentBucketName: testnewman-simi33-serverlessdeploymentbucket-1u4ci9eebg2es

Serverless: Retrieving Outputs...
Serverless: Calling CloudFormation...
Serverless: getValues.error: User: arn:aws:iam::102483920364:user/sikau is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-west-2:102483920364:stack/testnewman-simi33/*
Serverless: Writing Outputs...
Serverless: TypeError: Cannot read property 'outputs' of undefined
```

How can I fix this?
