### ISSUE TITLE
ALB listener path should be optional

### ISSUE THREAD

**Issue by jinhong-** [serverless/serverless#8568]
Path is optional in alb events. While validations are only warnings if path is omitted, deployment will fail because the cloud formation stack template generated will include a path pattern condition with null value

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: a
frameworkVersion: '2'
provider:
  name: aws
  runtime: go1.x
  httpApi:
    payload: "2.0"
plugins:
  - serverless-go-plugin
functions:
  app:
    handler: ./server.go
    events:
      - alb:
          listenerArn: arn
          priority: 1
          conditions: 
            host: example.com
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Error: The CloudFormation template is invalid: [/Resources/AppAlbListenerRule1/Type/Conditions/0/Values/0] 'null' values are not allowed in templates
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.11.1 (local)
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```
