### ISSUE TITLE
http integration schema validation

### ISSUE THREAD

**Issue by Enase** [serverless/serverless#8573]
**Description**

Setup function http event with integration type set [according documentation](https://www.serverless.com/framework/docs/providers/aws/events/apigateway/)

**Actual result:** 
`Configuration warning at 'functions.fnc_name_goes_here.events[0].http.integration': unsupported configuration format`

**Expected result:** 
No configuration warning

Config example:

<details>
<summary><code>serverless.yml</code></summary>

```yaml
  fnc_name_goes_here:
    name: fnc_name_goes_here
    handler: functions/fnc_name_goes_here/index.handler
    events:
      - http:
          path: user_get
          method: post
          cors:
            origin: '*'
            maxAge: 43200
          integration: lambda-proxy
          authorizer:
            type: aws_iam
```
</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
...
Serverless: Configuration warning at 'functions.fnc_name_goes_here.events[0].http.integration': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.14.0
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.4.3
```
