### ISSUE TITLE
Serverless layer removing old layer version permissions

### ISSUE THREAD

**Issue by raym0nd93** [serverless/serverless#8578]
I am using layers to create private, reusable code in a central AWS environment. Other AWS accounts reuse this code, thus including the layer. In order to have versioning for the code, and not forcing the other AWS accounts to update, I set `retain: true` in de configuration. The lambda layer is indeed retained, but permission to the old lambda layer version is revoked. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: helpers

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

layers:
  helpers:
    path: "dist"
    retain: true
    allowedAccounts:
      - XXXXXXXXXXXX
      - XXXXXXXXXXXX
```

</details>

<b>Installed version</b>

```
Framework Core: 2.14.0
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.4.3
```
