### ISSUE TITLE
Support for image_config for AWS Lambda function

### ISSUE THREAD

**Issue by arekt** [serverless/serverless#8583]
There is new `image:` option that can create AWS Lambda function based on docker container image.
It would be nice to support `image_config` as well, to override image `Command`, `EntryPoint` and `WorkingDirectory`.

```
functions:
  hello:
    image: ${env:DOCKER_IMAGE}
   
  hello2:
    image: ${env:DOCKER_IMAGE}
    image_config:
      command: ["app.handler2"]
```

or even

```
provider:
  image: ${env:DOCKER_IMAGE}
functions:
  hello:
    image_config:
      command: ["app.handler"]
  hello2:
    image_config:
      command: ["app.handler2"]
      working_dir: "/var/task/experimental"
  hello3:
    image_config:
      command: ["app.swift_handler"]
      entry_point: 
         - /var/runtime/swift_bootstrap
```

### Use case description

It would be possible to share one docker image and choose specific handler per lambda function.
It would be event better if `provider` section allows to define global image, shared between all lambda functions that contain image_config parameter. Similar like it's done for `layers`.

### Proposed solution
At the moment you can achieve similar thing overriding LambdaFunction in Resources

```
service: sls-container-image-test
useDotenv: true
provider: 
  name: aws
  region: ap-northeast-1

functions:
  hello:
    image: ${env:DOCKER_IMAGE}
  hello2:
    image: ${env:DOCKER_IMAGE}

resources:
  Resources:
    Hello2LambdaFunction:
      Type: AWS::Lambda::Function
      Properties: 
        ImageConfig:
          EntryPoint: 
            - /var/runtime/bootstrap
          Command: ["app.handler2"]
```

**Comment by medikoo** [comment]
@arekt great thanks for proposal. We're definitely open for it, still to be more on par with current conventions I believe it should be configured in a way that we expand already defined `image`  property, So extended configuration we could look as follows:

```yaml
functions:
  hello:
    image:
      uri: 000000000000.dkr.ecr.sa-east-1.amazonaws.com/test-lambda-docker@sha256:6bb600b4d6e1d7cf521097177dd0c4e9ea373edb91984a505333be8ac9455d38
      command: ...
      workingDir: ...
```

What do you think?

Also what exactly properties do you believe we should support, and how will they map to generated CloudFormation  template?

**Comment by arekt** [comment]
@medikoo sorry for the late response, was busy week.
 I'm fine with keeping everything under "image" or "image -> config".
Only this three properties are supported by Cloud Formation: 
```
    ImageConfig:
      Command:
        - "app.lambda_handler" 
      EntryPoint:
        - "entrypoint1"
      WorkingDirectory: "workDir"
```

That's how SAM is translating: https://github.com/aws/serverless-application-model/blob/develop/tests/translator/output/basic_function_withimageuri.json
