### ISSUE TITLE
Support for functionless AWS services integration - DynamoDB x API Gateway

### ISSUE THREAD

**Issue by fredericbarthelet** [serverless/serverless#8616]
### Use case description

A very large proportion of use cases can today be covered without the extensive use of lambda to glue it all. This proposal opens the discussion wether direct AWS services integration with each other should be supported as well.
Of course, straight CloudFormation could do the job for such use case. But there is a lot of hassle dealing with the various resources to be provisioned. The Serverless framework service definition offers a much simpler way of defining features.

With such feature, the Serverless framework would both use the `functions` keyword for easy setup of features requiring the integration of custom lambda code, but also an additional root keyword, for functionalities that can be achieved without the use of lambda.

This feature request is centered around a basic use case, but you're welcome to propose a different one : DynamoDB integration with API Gateway V1. The proposed solution takes into account the quantity of various integration already available and is not limited to this use case in particular. This is to ensure the proposed syntax will allow in the futur other services integration.

### Proposed solution

This feature allow provisioning of required resources to open API Gateway HTTP routes for a simple `CRUD` use-case, integrating with DynamoDB API `PutItem`, `GetItem`, `UpdateItem` and `DeleteItem`. It leverages the existing `schema` and `template` properties defined within `http` event type for lambda triggers in order to perform input validation and proper mapping for DynamoDB actions integration. This feature includes :

- eased-up provisioning of DynamoDB tables with an AWS provider specific property `dynamodb`
- new `integrations` property at serverless service definition root for features where a service is the final target. In this case, dynamodb is the final target of the feature (similar to functions keyword). This keyword would gather all features definition targeting other services than lambda at its end (wether it's dynamodb, s3, stepfunction, kinesis, ...)
- each item in `integrations` require specifying a target (similar to `handler`), a type (to use provider specific configuration) and an action. Each item would rely on similar `events` definition for function defining which entry point should allow interacting with this persistence layer (it can be `http` like in this exemple, but could as well be `iot` for an IoT rule i.e.)

```yaml
service: myService
provider:
  name: aws
  runtime: nodejs12.x
  dynamodb:
    ArticleTable:
      partitionKey:
        S: id
      sortKey:
        N: timestamp
integrations:
  createArticle:
    type: dynamodb
    target: ArticleTable
    action: PutItem
    events:
      - http:
           path: article
           method: post
           request:
             schema:
               application/json: ${file(create_article.json)}
             template:
               application/json: ${file(create_article_mapping.vtl.json)}
```

Such definition would :

- create a new dynamodb table `ArticleTable`
- create all the same resources as if the `http` event was defined for a lambda integration except for the role and the integration part of the `AWS::ApiGateway::Method`
- create a modified version of the new role assumed by api gateway to be able to execute `PutItem` on dynamodb
- create a modified version of the `AWS::ApiGateway::Method` to perform DynamoDB integration

I'm happy to provide a first POC of such feature in a PR for advanced implementation details if you deem the feature itself worth implementing in the framework.

**Comment by medikoo** [comment]
@fredericbarthelet thanks for proposal. I have similar thought, and do not personally like that Framework is that function centric. Still other issue we deal with, is that Framework is a constantly growing monolith, while some of the functionalities could live well as plugins.

What probably would be better for this use case is to agree on some convention for extending Framework in that direction, and simply let plugins to extend Framework, e.g. in your case there could be a plugin which configures DynamoDb integrations.

Let me know what you think

**Comment by fredericbarthelet** [comment]
Perfectly fine for me this way @medikoo :)

Would you be for me to actually develop a POC (based on DynamoDB integration) on the framework, agree on the integration convention with all potential issues addressed and working properly on the POC, and then to open another PR with the part required as a baseline in the framework and move the rest to a dedicated plugin repo ?

**Comment by medikoo** [comment]
@fredericbarthelet I wonder what we really need on Framework side. As I think of it, in minimal approach nothing extra should be needed. As technically you may create a plugin that defines `provider.dynamoDb` property and attach to deployment lifecycle hooks, and voilà, it'll just work.

Same if we want to define top level property (but having that we're signalling that property is provider agnostic, so in this case it should not be dynamodb specific).

What are your thoughts?

**Comment by fredericbarthelet** [comment]
@medikoo, on framework side, we need to define at least `integrations` key schema to enforce coherent declaration among the future multitude of plugin that will provide service integrations. I would as well enforce integration lifecycle deployment on framework side, and allow plugin to hook on each phase of the `deploy` command - defined in main framework. WDYT ?

I'll be happy to work on a proposal this weekend to show you better what I mean. Maybe we can discuss then what's in the scope of the framework, and what should be delegated to specific plugins.

**Comment by medikoo** [comment]
@fredericbarthelet Ok, I understand your proposal is to go with something as:

```yaml
integrations:
  <integrationName>
    type: <integrationType>
    ...<integration config>
```

But my impression is that current Framework conventions are more as:

```yaml
# provider agnostic integrations:
<integrationType>:
  <integrationName>:
   ...<integrationConfig>

# provider specific integrations:
provider:
  <integrationType>:
    <integrationName>:
     ...<integrationConfig>
```

What do you think?

**Comment by fredericbarthelet** [comment]
I was making the parallel with `functions` conventions :

```yml
functions: # <-- defined at provider agnostic schema level, in lib/configSchema.js
  <functionName>: # <-- defined at provider agnostic schema level, in lib/configSchema.js
    handler: # <-- defined at provider plugin level, in lib/plugins/aws/provider.js
    events: # <-- defined at provider agnostic schema level, in lib/configSchema.js
      - httpApi: # <-- defined at provider compileEvent provider plugin level, in lib/plugins/aws/package/compile/events/httpApi.js
```

Unlike `functions` which does not require `type` since `provider.name` is sufficient to know what is a function (if provider is `aws`, function is a lambda ...), `integrations` requires an additional typing - one integration with a `provider.name` set to `aws` is not enough to understand which target service should be provisioned. Another option would be not to use `integrations` key, but provider agnostic - single service - keys. Like `noSqlDatabases`, which would be interpreted to `dynamodb` in the case of provider being AWS, or cosmosDB in Azure. However, I'm not a big fan of this solution, as the quantity of root level keys will greatly increase.

If we apply this reasoning to this proposal :

```yml
provider:
  dynamodb: # <-- defined at provider plugin level, in lib/plugins/aws/provider.js - or we need a new API on configSchema to add new property on existing provider for the new external plugin
integrations: # <-- should be defined at provider agnostic schema level, in lib/configSchema.js
  <integrationName>:  # <-- should be defined at provider agnostic schema level, in lib/configSchema.js
    type: # <-- should be defined at provider agnostic schema level, in lib/configSchema.js, to ensure coherence among providers
    target: # <-- defined at new external plugin level, but could be moved to lib/configSchema.js to make sure all provider have a similar pattern
    action: # <-- defined at new external plugin level, but could be moved to lib/configSchema.js to make sure all provider have a similar pattern and a constraint could be added on lib/plugins/aws/provider.js for AWS specific constraints on available actions
    events: # <-- defined at provider agnostic schema level, in lib/configSchema.js
      - httpApi: # <-- defined at new external plugin level
```

WDYT ?

**Comment by medikoo** [comment]
> Unlike functions which does not require type since provider.name is sufficient to know what is a function (if provider is aws, function is a lambda ...), integrations requires an additional typing 

@fredericbarthelet thanks for explanations, still I don't understand this argument. In my eyes it's more like that:

Currently Framework is function centric, and offers only _functions_ integrations, which can be configured through top level `functions` property, simply as follows:

```yaml
provider:
  name: aws

functions:
  someFunction:
    handler: index.handler
    runtime: nodejs12.x
    events:
      - http: GET /foo
```  

In your proposal, you want to introduce other integrations, but also to configure them differently with more generic form, in which (theoretically) _function_ integrations could be configured as:

```yaml
provider:
  name: aws
  runtime: nodejs12.x
  lambda:
    someLambda:
      handler: index.hanlder
      runtime: nodejs12.x
       
integrations:
  someFunction:
    type: function
    target: someLambda
    action: invokeSync
    events:
      - http: GET /foo
```

I'm not convinced by this new format, firstly it derives with how we configure current _function_ integrations, secondly feels unnecessarily verbose.

Now focusing on your use case. I think it respecting the current Framework conventions, the closest representation of _dynamodb_ integration would be:

```yaml
provider:
  name: aws

dynamoDb:
  ArticleTable:
    partitionKey:
      S: id
    sortKey:
      N: timestamp
    events:
      - http:
          action: PutItem
          path: article
          method: post
          request:
            schema:
              application/json: ${file(create_article.json)}
            template:
              application/json: ${file(create_article_mapping.vtl.json)}
```

I know at beginning I pointed that top-level is _provider agnostic_, and provider specific things should rather be nested at `provider`, but the more I think of it the more I feel that this argument is flawed, as Framework service as currently designed can target only single provider, so in all cases config is provider specific.

We can then assume, that it's fine to add new integrations top level (as it's with `functions`), and at `provider` group settings for side resources which are generated through main integrations config
