### ISSUE TITLE
unable to setup more than one cloudwatchlog as events trigger

### ISSUE THREAD

**Issue by jastsai** [serverless/serverless#8624]
When we setup more than one cloudwatchLog under events, we see 

The Lambda console can't validate one or more event sources for this trigger. The most common cause is when a source ARN includes a wildcard (*) character. You can manage unvalidated triggers using the AWS CLI or AWS SDK.
The Lambda console no longer supports disabling S3 and CloudWatch Logs triggers. Delete these triggers to stop further actions.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: monitoring
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-2

functions:
  hello:

    handler: handler.hello
    events:
      - cloudwatchLog:
          logGroup: "/aws/lambda/prod-cloneSubAccounts"
      - cloudwatchLog:
          logGroup: "/aws/lambda/backend-prod-handlers"
          filter: "?error ?ERROR ?Error ?Exit ?EXIT ?Stop ?STOP ?Timed out"
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service lambda-monitoring.zip file to S3 (3.33 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.......
Serverless: Stack update finished...
Service Information
service: lambda-monitoring
stage: prod
region: ap-southeast-2
stack: lambda-monitoring-prod
resources: 9
api keys:
  None
endpoints:
  None
functions:
  hello: lambda-monitoring-prod-hello
layers:
  None
Serverless: Removing old service artifacts from S3...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.15.0
Plugin: 4.2.0
SDK: 2.3.2
Components: 3.4.3
```
