### ISSUE TITLE
RetryPolicy for EventBridge rules

### ISSUE THREAD

**Issue by ojongerius** [serverless/serverless#8625]
### Use case description

Eventbridge has added improved failure recovery for a while now, see https://aws.amazon.com/fr/blogs/compute/improved-failure-recovery-for-amazon-eventbridge/

Next to support for a DLQ, for which an issue was raised in https://github.com/serverless/serverless/issues/8379 we'd love to see support for a a retry policy (`AWS::Events::Rule::RetryPolicy`).

### Proposed solution

Add `retryPolicy` for `eventBridge` rules, a policy consists of `maximumEventAgeInSeconds` and `maximumRetryAttempts`.
See the Cloudformation documentation at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-retrypolicy.html#cfn-events-rule-retrypolicy-maximumretryattempts:

```json
{
  "MaximumEventAgeInSeconds" : Integer,
  "MaximumRetryAttempts" : Integer
}
```

Example usage would look like:

```yaml
myFunction:
  handler: index.main
  events:
    - eventBridge:
        retryPolicy:
          maximumEventAgeInSeconds: 3600 # Integer
          maximumRetryAttempts: 3 # Integer
        onError: arn:aws:sqs:us-east-1:XXXXXX:test # suggested in 8379
        eventBus: custom-saas-events
        pattern:
          source:
            - saas.external
```
