### ISSUE TITLE
Request parameter validation doesn't work

### ISSUE THREAD

**Issue by vajafari** [serverless/serverless#8635]
I create a serverless function with an HTTP event that needs validation of some parameters in the query string.  I expect when some parameter in the querystring set as required, the serverless framework automatically add **RequestValidator** to the compiled Cloud Formation and request validated based on request parameters and header.  I completely read [this issue](https://github.com/serverless/serverless/issues/5034#issue-331318739) but the answers is based on some kind of hacking final Cloud Formation. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: someproject
provider:
  name: aws
  region: us-east-2
  stage: "${opt:stage, 'dev'}"
  environment:
    ENV: "${opt:stage, 'dev'}"
    REGION: "${self:provider.region}"
    PROJECTNAME: someproject
custom:
  currentStage: "${self:provider.stage}"
functions:
  mongoget:
    handler: mongo-handlers/mongo-get.handler
    events:
    - http:
        method: GET
        path: article
        integration: AWS_PROXY
        request:
          parameters:
            querystrings:
              articleid: true
              writerid: false
```

</details>

<details>

As you can see here parameters marked as required but the is no request validator for the method

![image](https://user-images.githubusercontent.com/32508725/102458592-b5206c00-4059-11eb-8b85-a723f063bd25.png)

</details>

<b>Installed version</b>

```
Framework Core: 2.11.1
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

**Comment by pgrzesik** [comment]
Hello @vajafari :wave: Thanks for reporting the issue. I believe the problem you have is the same one as in the issue you've referenced: https://github.com/serverless/serverless/issues/5034 I've managed to replicate your issue and currently, the workaround for it is to use `resources` section in `serverless.yml` that adds `AWS::ApiGateway::RequestValidator`. I know it's not an ideal situation, but with taking advantage of that, I believe you should be able to resolve your problem at least for now. 

Below you can find an example of such `resources` section added to your `serverless.yml` file

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: someproject
provider:
  name: aws
  region: us-east-2
  stage: "${opt:stage, 'dev'}"
  environment:
    ENV: "${opt:stage, 'dev'}"
    REGION: "${self:provider.region}"
    PROJECTNAME: someproject
custom:
  currentStage: "${self:provider.stage}"
functions:
  mongoget:
    handler: mongo-handlers/mongo-get.handler
    events:
    - http:
        method: GET
        path: article
        integration: AWS_PROXY
        request:
          parameters:
            querystrings:
              articleid: true
              writerid: false
resources:
  Resources:
    ParameterRequestValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: ParameterRequestValidator
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true
    ApiGatewayMethodArticleGet:
      Properties:
          RequestValidatorId:
             Ref: ParameterRequestValidator
```
</details>

Please let us know if that helps and as for the original problem, let's track it on the original ticket if the root cause is the same. We'd also be very happy to accept a PR that resolves that bug without having to extend the CloudFormation template via `resources` :tada:
