### ISSUE TITLE
Docker deployment says Source image is invalid

### ISSUE THREAD

**Issue by inian** [serverless/serverless#8636]
serverless.yml
```yml
service: hello-world-service
provider:
  name: aws
  region: ap-southeast-1
functions:
  hello:
    image: xxx.dkr.ecr.ap-southeast-1.amazonaws.com/hello-world:latest@sha256:xxx
```

Dockerfile
```
FROM public.ecr.aws/lambda/nodejs:12
COPY app.js package.json /var/task/
RUN npm install
CMD [ "app.handler" ]  
```

app.js
```
module.exports.handler = () => {
  console.log("hello world");
};
```

When I deploy the same image to a lambda from the aws console, it works fine. But when I deploy via serverless, it errors out with ` Source image xxx.dkr.ecr.ap-southeast-1.amazonaws.com/hello-world:latest@sha256:xxx is not valid. Provide a valid source image`

The ECR repo is a private repo.
