### ISSUE TITLE
Github CI 

### ISSUE THREAD

**Issue by JohnnyJumper** [serverless/serverless#8640]
Trying to deploy via github CI fails due to not being able to login into serverless. I do want to use a serverless dashboard from time to time as it provides quite useful features for us.  We have created a new SERVERLESS_ACCESS_KEY and added it to Github secrets as an env variable, but that seems to not working either. 

We did everything from run-in-cicd link to set it up correctly, connected the github, chose the repository and directory. 

It does work if I remove the org field from serverless.yml but then the serverless dashboard doesn't register a new deploy.
Is there a place where I need to provide SERVERLESS_ACCESS_KEY besides just putting it in env on github secrets? 

The error we are getting is:

yarn run v1.22.5
$ yarn run serverless deploy
$ <PATH>/node_modules/.bin/serverless deploy
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
error Command failed with exit code 1.
 
error Command failed with exit code 1.
  Serverless Error ---------------------------------------
 
  You are not currently logged in. Follow instructions in http://slss.io/run-in-cicd to setup env vars for authentication.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.1
     Framework Version:         1.73.1
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.16
 
 
 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
app: moverup-server
# org: moveruppprofilepics
service: expressAPI-epsagon2
plugins:
  - serverless-plugin-typescript
provider:
 name: aws
 runtime: nodejs10.x
 stage: prod-2
 region: us-west-2
 timeout: 30
functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      SECRET: ${env:SECRET}
      LINK: ${env:LINK}
      API_KEY: ${env:API_KEY}
      DOMAIN: ${env:DOMAIN}
      DEV: ${env:DEV}

```
</details>
