### ISSUE TITLE
Support API Gateway v2 setting to disable the default HTTP API endpoint

### ISSUE THREAD

**Issue by gdraynz** [serverless/serverless#8642]
### Use case description

There is an option to disable the default endpoints when using HTTP APIs, which is available via CloudFormation on the contrary to the same feature for REST APIs described in #8492.
This allows the creation of an HTTP API responding to a custom domain but not to `https://{id}.execute-api.{region}.amazonaws.com`.

### Proposed solution

This could be handled with a simple boolean defaulted to `false` in the `httpApi` provider configuration:
```yaml
provider:
  name: aws
  httpApi:
    name: some-api
    disableDefaultEndpoint: true
```

Then the right property should be set in the CloudFormation template:
```yml
HttpApi:
  Type: AWS::ApiGatewayV2::Api
  Properties: 
    Name: "some-api"
    DisableExecuteApiEndpoint: true
```
