### ISSUE TITLE
Environment variables undefined after redeploying lambda to AWS

### ISSUE THREAD

**Issue by Aror** [serverless/serverless#8653]
I have a lambda in a pipeline. It is deployed with `serverless deploy` via github actions config. The first time I deployed the lambda, it worked fine. I proceeded to delete the stack. Then when I tried to re-deploy the lambda, I got the following error: 

```
"errorType": "MissingRequiredParameter",
    "errorMessage": "Missing required key 'Role' in params",
    "code": "MissingRequiredParameter",
    "message": "Missing required key 'Role' in params",
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: lambda-mediaconvert
custom:
  environment: ${file(env.yml):default}
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.environment.REGION}
  stage: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: ${self:custom.environment.BUCKET_RESOURCE}
    - Effect: Allow
      Action:
        - "iam:PassRole"
      Resource: ${self:custom.environment.MEDIACONVERT_ROLE}
    - Effect: Allow
      Action:
        - "mediaconvert:*"
      Resource: "*"
functions:
  startJob:
    handler: handler.startJob
    events:
      - s3:
          bucket: ${self:custom.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: media/
            - suffix: .mp4
          existing: true
      - s3:
          bucket: ${self:custom.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: media/
            - suffix: .mxf
          existing: true

```

</details>

<details>
<summary><b><code>GITHUB Actions workflow config</code> output</b></summary>

```
  Deploy:
    name: deploy
    needs: Test 
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transcode-video-lambda
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create env file
        run: |
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Set up Node 12
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Install NPM dependencies
        run: |
          npm install -g yarn
          yarn install
      - name: Deploy to AWS
        run: serverless deploy
```

</details>

<b>Installed version</b>

```
Framework Core: 2.15.0
Plugin: 4.2.0
SDK: 2.3.2
Components: 3.4.3
```
It appears that my lambda now does not have access to environment variables after a redeploy. Is there a way around this?

**Comment by pgrzesik** [comment]
Hello @Aror :wave: Thanks for reporting the issue. Before continuing, could you please validate if that problem happens only in Github Actions? E.g. you could do the deployment from local machine twice to check if it's a potential bug within the Framework or if it's an issue with Github Actions setup. In addition, if you could include a richer error stack trace (if possible), that would be great. Thanks in advance :+1:

**Comment by Aror** [comment]
Hi @pgrzesik Thanks for following up on the submission. I can confirm that deploying twice via command line `serverless deploy` works without issue. Please note that the GitHub Actions config runs the same command: `serverless deploy`.

This is the error stack trace:

```
2020-12-21T19:22:43.651Z	ERROR	Invoke Error 	
{
    "errorType": "MissingRequiredParameter",
    "errorMessage": "Missing required key 'Role' in params",
    "code": "MissingRequiredParameter",
    "message": "Missing required key 'Role' in params",
    "time": "2020-12-21T19:22:43.650Z",
    "stack": [
        "MissingRequiredParameter: Missing required key 'Role' in params",
        "    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)",
        "    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:61:14)",
        "    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)",
        "    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)",
        "    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9",
        "    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:386:7)",
        "    at /var/runtime/node_modules/aws-sdk/lib/config.js:404:9"
    ]
}
```

This is the actual lambda function:

```
'use strict';
const AWS = require('aws-sdk');

const mediaConvert = new AWS.MediaConvert({
  endpoint: process.env.MEDIACONVERT_ENDPOINT,
  region: process.env.REGION
});

module.exports.startJob = async event => {
  const input = `s3://${event.Records[0].s3.bucket.name}/${event.Records[0].s3.object.key}`;
  const job = {
    "Role": process.env.MEDIACONVERT_ROLE,
    "JobTemplate": process.env.MEDIACONVERT_JOB_NAME,
    "Settings": {
      "Inputs": [{
        "FileInput": input,
      }]
    }
  };

  await mediaConvert.createJob(job).promise();
};
```

My current workaround is to manually provide the lambda with environment variables via the console but that is not ideal. Any thoughts on what could be causing the issue?

**Comment by pgrzesik** [comment]
Hello @Aror :wave: Thanks for submitting more details. It seems like the issue is most likely related to Github Actions setup and it looks like you're not actually passing environment variables to your functions in your configuration file. 

As it's most likely not a bug, I'd like you to move that discussion to one of our other support channels:
- https://forum.serverless.com/
- https://www.serverless.com/slack
- http://stackoverflow.com/questions/tagged/serverless-framework

**Comment by Aror** [comment]
Hi @pgrzesik 👋 

I just wanted to followup and provide a **solution** in case anyone stumbles on a similar issue.  You were correct about it being an issue with the `serverless.yml` configuration. I did not pass environment variables to the actual lambda function.

Here is a snippet of the updated config that I hope helps someone if they run into the same problem:

```
functions:
  startJob:
    handler: handler.startJob
    environment: ${file(env.yml):production}
``` 

All that was needed was `environment: ${file(env.yml):production}`
