### ISSUE TITLE
Have an ability to set iam role tags

### ISSUE THREAD

**Issue by runk** [serverless/serverless#8669]
### Use case description

Sometimes there are use cases when it's needed for lambda execution role to have special tags (same as `function.tags`). Those can be used for attribution, access control or something else. 

Currently there're at least two ways to have those:

- Use top level `stackTags` which will be "cascaded" to all application resources. Cons: all resources will get the tag, while it's only intended for the execution role.
- Use custom role. Cons: boilerplate code, additional complexity for the user.

### Proposed solution

Add `iamRoleTags` directive with standard key-value format like so:

```yaml
iamRoleTags:
  reader: 'restricted'
  foo: 'bar'

iamRoleStatements: 
  - Effect: Allow
    Action:
      - s3:GetObject
    Resource:
      - arn:aws:s3:::sensitive-data
```

I'm happy to craft a PR for this change as long as this proposal gets endorsement from the maintainers.

**Comment by pgrzesik** [comment]
Hello @runk, thanks a lot for submitting your proposal. It totally makes sense to be considered, however, I'm wondering about the potential approaches when it comes to implementation. Your proposal is one option, but whenever I see two properties that would apply to the same resource, it suggests that it might be worth considering if it wouldn't be better to gather them under a common property e.g.

```
iamRole:
  statements: ...
  tags: ...
```

The potential "issue" with the above approach is that it's a breaking change and would have to be implemented with deprecations, while the `iamRoleTags` are simpler to implement. 

I'd love to get your opinions on that @medikoo @runk

**Comment by runk** [comment]
While I like the idea about putting statements and tags under common parent, more things need to be considered perhaps.

- How will it work with existing `role` directive
- Same as above re `iamManagedPolicies` directive

I guess another option would be making `role` to accept either a string (role arn) or basic role structure as you suggested @pgrzesik. As I know `role` already takes precedence over `iamRoleStatements` etc, which is good in this case. 

Going to leave this for reference perhaps: https://www.serverless.com/framework/docs/providers/aws/guide/iam/

**Comment by pgrzesik** [comment]
@runk You're correct that `role` will always take precedence and definitely, having `role` and `iamRole` would create more confusion for users. The alternative here could be being more specific with naming. Using `role` as an umbrella for all configurations (both for default roles and custom roles) is an interesting idea, too. I'm not yet sure about the potential dangers of that approach.

**Comment by medikoo** [comment]
>  whenever I see two properties that would apply to the same resource, it suggests that it might be worth considering if it wouldn't be better to gather them under a common property e.g.

+1. It indeed again puts us on path of introducing new deprecation, but I think it's good idea to group it. We also have other IAM related properties. I'd group them all under `provider.iam` as below:

```yaml
provider:
  iam:
    role: # either a directly assigned ARN or object with below options
      permissionBoundary: ...
      managedPolicies: ...
      statements: ...
      tags: ...
    deploymentRole: ... # Replacement for `cfnRole`
```

In that case I'd split this work into two independent tasks. First that moves us to new configuration, and second that follows with introduction of `provider.iam.role.tags`
