### ISSUE TITLE
Error 502 => message: Internal server error on Lambda Proxy Integration

### ISSUE THREAD

**Issue by SRIRAM301090** [serverless/serverless#8671]
**Error 502: "message": "Internal server error on Lambda Proxy Integration"**
I get this response whenever lambda throws exceptional error, otherwise I get the valid json response.
I am unable to get error response from Lambda in exception case and always getting Error 502: "message": "Internal server error". I use Python as run-time and it works if proxy-integration is removed. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: vtaf-client-authentication
app: vtaf-nextgen

frameworkVersion: '2'
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "Lambda:*"
      Resource:
      - "*"
functions:
  signup:
    handler: users/signup.signup
    events:
      - http:
          path: users
          method: post
          cors: true

```

</details>

<details>
<summary><b><code>{
  Response body: "message": "Internal server error"
}</summary>
<summary><b><code>{
  Response body: "message": "Internal server error"
}</summary>
```
Log:
Thu Dec 24 12:12:44 UTC 2020 : Lambda execution failed with status 200 due to customer function error: An error occurred (UsernameExistsException) when calling the SignUp operation: An account with the given email already exists.. Lambda request id: c7b7a532-5a63-4c8a-a5fb-e55892d0dd81
Thu Dec 24 12:12:44 UTC 2020 : Method completed with status: 502


</details>

<!--
Q4: Provide (in below placeholder) output of serverless --version
-->

<b>Installed version</b>

```
Serverless V2.16.1
```
