### ISSUE TITLE
Service not found error when trying to deploy

### ISSUE THREAD

**Issue by joebernard** [serverless/serverless#8673]
I'm trying to deploy a new service. It was working for a while, then serverless started returning an error:

> Error: {"errorMessage":"Service not found. - Please contact support and provide this identifier to reference this issue - GWD23S8BLW8R"}
      at _callee$ (/Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/src/utils/checkHttpResponse.js:19:9)
      at tryCatch (/Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/node_modules/regenerator-runtime/runtime.js:118:21)
      at step (/Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:191)
      at /Users/joebernard/.nvm/versions/node/v14.2.0/lib/node_modules/serverless/node_modules/@serverless/platform-sdk/dist/utils/checkHttpResponse.js:7:361
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

I've tried deleting the service from the dashboard and directly in CloudFront and recreating it, but I get the same error. Other services will deploy just fine, but not this one.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: snacktime-admin-authentication
# app and org for use with dashboard.serverless.com
app: juncture-app
org: joebernard

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage,'dev'}
  profile: ${self:custom.profile.${self:provider.stage}} # security profile from AWS config file (~/.aws/credentials)
  region: us-east-1
  logRetentionInDays: 120
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
sls deploy
```

</details>

<b>Installed version</b>

```
Framework Core: 2.16.1
Plugin: 4.3.0
SDK: 2.3.2
Components: 3.4.3
```
