### ISSUE TITLE
Group IAM-related properties under `provider.iam`

### ISSUE THREAD

**Issue by pgrzesik** [serverless/serverless#8681]
As of right now, we have multiple properties related to IAM, such as `iamRoleStatements`, `iamManagedPolicies`, etc defined as direct properties of `provider. The goal of this task is to move all IAM-related properties under `provider.iam` namespace, as suggested in: https://github.com/serverless/serverless/issues/8669#issuecomment-751683919

```
provider:
  iam:
    role: # either a directly assigned ARN or object with below options
      permissionBoundary: ...
      managedPolicies: ...
      statements: ...
    deploymentRole: ... # Replacement for `cfnRole`
```

As it is a breaking change, we need to introduce it by deprecating the old syntax: https://github.com/serverless/serverless/blob/master/docs/deprecations.md
