### ISSUE TITLE
Whitespace is not allowed in AWS tags

### ISSUE THREAD

**Issue by rohit-gohri** [serverless/serverless#8704]
As mentioned in https://github.com/serverless/serverless/issues/8304#issuecomment-753356291

Whitespace is not allowed currently by `serverless` in Tags even though AWS allows it.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: app

frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  region: ap-southeast-1
  stage: dev
  runtime: nodejs12.x
  tags:
    'Cost Center': cd-app
    Layer: Workers


functions:
  click-listener:
    handler: handler
    name: click
    description: click
    tags:
      Application: 'ClickListener'
```

</details>

<details>
<summary><b><code>serverless package</code> output</b></summary>

```
  Serverless Error ---------------------------------------

  Configuration error at 'provider.tags': unrecognized property 'Cost Center'
```

</details>

<b>Installed version</b>

```
Framework Core: 2.17.0 (standalone)
Plugin: 4.4.0
SDK: 2.3.2
Components: 3.4.3
```
