### ISSUE TITLE
unrecognized property 'params' on scheduled event

### ISSUE THREAD

**Issue by tomer-amir** [serverless/serverless#8715]
I am trying to create a scheduled lambda function using the Serverless framework and to send it different parameters from different events.

here is my serverless configuration:
```yaml
functions:
  profile:
    timeout: 10
    handler: profile.profile
    events:
      - schedule:
          rate: rate(1 minute)
          params:
            hello: world
```
The issue is that when I run sls deploy, I get the following warning:
```
Serverless:   at 'functions.profile.events[0]': unrecognized property 'params'
```
And the function does run, but doesn't get the parameter.
This is basically copied from the documentation [here](https://www.serverless.com/framework/docs/providers/openwhisk/events/schedule/#schedule/), so it should work...

Am I missing something?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  profile:
    timeout: 10
    handler: profile.profile
    events:
      - schedule:
          rate: rate(1 minute)
          params:
            hello: world
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'functions.profile.events[0].schedule': unrecognized property 'params'

```

</details>

<b>Installed version</b>

```
$ serverless --version
Framework Core: 2.16.1 (standalone)
Plugin: 4.3.0
SDK: 2.3.2
Components: 3.4.3

```
