### ISSUE TITLE
serverless deploy error: In given setup stage specific options such as `tracing`, `logs` and `tags` are not supported.

### ISSUE THREAD

**Issue by yeukfei02** [serverless/serverless#8720]
`serverless.yml`

```yaml
service: my-api

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: development
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
    JWT_SECRET: ${param:JWT_SECRET}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: my-api
  lambdaHashingVersion: 20201221
  timeout: 30

functions:
  main:
    handler: src/main/handler.main
    events:
      - http:
          path: /
          method: get
          cors: true

  otherFunc:
    ...

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-split-stacks
```

I have this error:

```

 Serverless Error ---------------------------------------
 
  Rest API id could not be resolved.
  This might be caused by a custom API Gateway configuration.
  
  In given setup stage specific options such as `tracing`, `logs` and `tags` are not supported.
  
  Please update your configuration (or open up an issue if you feel that there's a way to support your setup).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.20.0
     Framework Version:         2.17.0 (local)
     Plugin Version:            4.4.1
     SDK Version:               2.3.2
     Components Version:        3.4.3
```

Anyone know how to fix this?
As deploy to sls dashboard now become red icon.
Any input is welcome...thanks
