### ISSUE TITLE
Cannot find module 'ajv/dist/compile/codegen'

### ISSUE THREAD

**Issue by lewgordon** [serverless/serverless#8727]
Not sure if this is something that just can't be helped, but it seems that if a NodeJS project has a dependency on `ajv^6` it'll cause the packaging step to fail.  I believe this was caused by the bump to `ajv^7`.  I know that many projects still depend on the earlier version, so it might break a lot of projects.

Steps to reproduce:

1. Create a new project using `sls init`
2. Select NodeJS project
3. Install `ajv^6` via `npm i ajv@^6`
4. Execute `sls package`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
 
  Error --------------------------------------------------
 
  Error: Cannot find module 'ajv/dist/compile/codegen'
  Require stack:
  - /tmp/test/node_modules/ajv-keywords/dist/definitions/typeof.js
  - /tmp/test/node_modules/ajv-keywords/dist/keywords/typeof.js
  - /tmp/test/node_modules/ajv-keywords/dist/keywords/index.js
  - /tmp/test/node_modules/ajv-keywords/dist/index.js
  - /tmp/test/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js
  - /tmp/test/node_modules/serverless/lib/Serverless.js
  - /usr/local/lib/node_modules/serverless/lib/Serverless.js
  - /usr/local/lib/node_modules/serverless/scripts/serverless.js
  - /usr/local/lib/node_modules/serverless/bin/serverless.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
      at Function.Module._load (internal/modules/cjs/loader.js:840:27)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (/tmp/test/node_modules/ajv-keywords/src/definitions/typeof.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (/tmp/test/node_modules/ajv-keywords/src/keywords/typeof.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (/tmp/test/node_modules/ajv-keywords/src/keywords/index.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (/tmp/test/node_modules/ajv-keywords/src/index.ts:3:1)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at ConfigSchemaHandler.validateConfig (/tmp/test/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js:102:5)
      at Service.validate (/tmp/test/node_modules/serverless/lib/classes/Service.js:222:41)
      at /tmp/test/node_modules/serverless/lib/Serverless.js:200:49
      at tryCatcher (/tmp/test/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/tmp/test/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/tmp/test/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/tmp/test/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/tmp/test/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/tmp/test/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/tmp/test/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/tmp/test/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/tmp/test/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.3
     Framework Version:         2.11.1 (local)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.3.0
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.18.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```

**Comment by srdone** [comment]
I'm seeing this issue - we've had to specify 2.17.0 in order for our deploys to work.

**Comment by srdone** [comment]
I should add - we don't have a direct dependency on ajv, but we're using other packages that likely have dependencies on ajv.

**Comment by medikoo** [comment]
@lewgordon Thanks for report, Still this looks to me as issue in your setup, at least provided information shows that:

You use globally installed `serverless` v2.18.0 , which in context of `/tmp/test` fallbacks to it's locally installed `serverless` v2.11.1.

And it appears that local `serverless` installation in `tmp/test/node_modules` v2.11.1 is broken:

Note that v2.11.1 depends on `ajv-keywords@^3.5.2` -> https://github.com/serverless/serverless/blob/bde334c10f33a813a16e158832eb61c56e77d822/package.json#L30
and requires it in `lib/class/ConfigSchemaHandler/index.js`:
https://github.com/serverless/serverless/blob/bde334c10f33a813a16e158832eb61c56e77d822/lib/classes/ConfigSchemaHandler/index.js#L102

Still what it receives in your case is `ajv-keywords` v4, we can tell that by resolved require path `ajv-keywords/dist/index.js` exposed in your stack trace which is specific to v4 -> https://npmview.now.sh/ajv-keywords@4 while v3 looks as https://npmview.now.sh/ajv-keywords@3.

How did you install `serverless` locally? Is this referenced in `package.json` of `/tmp/test`?, because if it's not and then e.g.  `ajv-keywords@4` was installed in context of `/tmp/test`  it possibly could break the unlisted `serverless` installation

**Comment by srdone** [comment]
In our case, serverless is installed as a dev dependency of our project. We are not using ajv directly (though one or more of our dependencies are bringing it in on install).

**Comment by claylevering** [comment]
As a note, had the same issues starting in `2.18.0` - Our team uses the `serverless` library in our dev dependencies and of course we have some library dependencies on AJV but at least in the app we're working with now, the list of dependencies is fairly minimal:

```
  ...
  "devDependencies": {
    "jest": "^26.6.3",
    "serverless": "^2.17.0",
    "serverless-offline": "^6.8.0",
    "serverless-plugin-git-variables": "^5.1.0"
  },
  "dependencies": {
    "INTERNAL LIBRARY": "^1.0.0-alpha.6"
  }
```

2.17.0 works, 2.18.0 fails with the AJV errors listed above.

**Comment by claylevering** [comment]
I should note we never leverage a global serverless installation.  We rely on `nvm` and per-repo version locking with either `npx sls` or `npm` scripts to call any serverless executions (e.g. `npm run deploy:production` ==> `serverless deploy --stage production`)

**Comment by medikoo** [comment]
It'll be great to find out how this broken state happens.

At least in @lewgordon it looks as broken installation issue, which is not an issue in `serverless` library itself (as it doesn't install by itself, but via tools as `npm` or `yarn`)

Even if service on its own depends on `ajv` or `ajv-keywords` at different versions than ones on which `serverless` depends. Then installer should ensure versions on which `serverless` expects in its `node_modules` folder (that's how npm and yarn based installation works)

**Comment by FergusMcGlynn** [comment]
I am running into this issue as well. I actually have two projects that use `serverless` as a dev dependency - I upgraded both to use version `2.18.0` yesterday in order to fix the [axios security vulnerability](https://github.com/serverless/serverless/issues/8712) - for one project there were no problems running `serverless deploy`, but for the other I get the same error as the original poster: `Cannot find module 'ajv/dist/compile/codegen'`.

Running `npm ls ajv` on both projects, I see that on the project where `serverless deploy` fails, I have an `UNMET PEER DEPENDENCY`:
```
$ npm ls ajv

+-- jest@26.6.3
| `-- @jest/core@26.6.3
|   `-- jest-config@26.6.3
|     `-- jest-environment-jsdom@26.6.2
|       `-- jsdom@16.4.0
|         `-- request@2.88.2
|           `-- har-validator@5.1.5
|             `-- ajv@6.12.6  deduped
+-- serverless@2.18.0
| +-- UNMET PEER DEPENDENCY ajv@7.0.3
| `-- ajv-formats@1.5.1
|   `-- ajv@7.0.3
`-- xo@0.33.1
  `-- eslint@7.17.0
    +-- @eslint/eslintrc@0.2.2
    | `-- ajv@6.12.6  deduped
    +-- ajv@6.12.6
    `-- table@6.0.7
      `-- ajv@7.0.3
```

But on the other project, where `serverless deploy` works fine, no peer dependency issues, even though the conditions regarding `ajv` look very similar:
```
$ npm ls ajv                                                          

+-- @percy/script@1.1.0                                               
| `-- @percy/agent@0.28.6                                             
|   `-- percy-client@3.8.0                                            
|     `-- request@2.88.2                                              
|       `-- har-validator@5.1.5                                       
|         `-- ajv@6.12.6  deduped                                     
+-- @university-of-york/esg-lib-pattern-library-react-components@6.1.4
| `-- babel-plugin-react-css-modules@5.2.6                            
|   `-- ajv@6.12.6                                                    
+-- next@10.0.5                                                       
| +-- sass-loader@10.0.5                                              
| | `-- schema-utils@3.0.0                                            
| |   `-- ajv@6.12.6  deduped                                         
| +-- schema-utils@2.7.1                                              
| | `-- ajv@6.12.6  deduped                                           
| `-- webpack@4.44.1                                                  
|   +-- ajv@6.12.6  deduped                                           
|   +-- schema-utils@1.0.0                                            
|   | `-- ajv@6.12.6  deduped                                         
|   `-- terser-webpack-plugin@1.4.5                                   
|     `-- schema-utils@1.0.0                                          
|       `-- ajv@6.12.6  deduped                                       
+-- serverless@2.18.0                                                 
| +-- ajv@7.0.3                                                       
| `-- ajv-formats@1.5.1                                               
|   `-- ajv@7.0.3                                                     
`-- xo@0.33.1                                                         
  `-- eslint@7.17.0                                                   
    +-- @eslint/eslintrc@0.2.2                                        
    | `-- ajv@6.12.6  deduped                                         
    +-- ajv@6.12.6  deduped                                           
    `-- table@6.0.7                                                   
      `-- ajv@7.0.3        
```

I don't understand why there would be an unmet peer dependency in one project and not the other. Neither explicitly includes `ajv` as a dependency. Also, it looks to me like `serverless` has [`ajv` as an explicit dependency](https://github.com/serverless/serverless/blob/v2.18.0/package.json#L29), so I'm confused by the peer dependency issue here.

**Comment by lewgordon** [comment]
Sorry about that @medikoo ! I agree there was something wrong in my setup.  I reproduced the issue I was seeing again, though.  I believe there might have been a typo in my original post.  Here are the files for the most recent reproduction.  Let me know if you need additional information or find anything I've missed.

This time I already ran it in the context of a container to isolate the filesystem. I used [node](https://hub.docker.com/_/node) with tag `12`.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: 
#      - s3: 
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
```

</details>

<details>
<summary><code>sls package</code> output</summary>

 ```
  Error --------------------------------------------------
 
  Error: Cannot find module 'ajv/dist/compile/codegen'
  Require stack:
  - /git/node_modules/ajv-keywords/dist/definitions/typeof.js
  - /git/node_modules/ajv-keywords/dist/keywords/typeof.js
  - /git/node_modules/ajv-keywords/dist/keywords/index.js
  - /git/node_modules/ajv-keywords/dist/index.js
  - /git/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js
  - /git/node_modules/serverless/lib/Serverless.js
  - /git/node_modules/serverless/scripts/serverless.js
  - /git/node_modules/serverless/bin/serverless.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
      at Function.Module._load (internal/modules/cjs/loader.js:667:27)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/definitions/typeof.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/keywords/typeof.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/keywords/index.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/index.ts:3:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at ConfigSchemaHandler.validateConfig (/git/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js:102:5)
      at Service.validate (/git/node_modules/serverless/lib/classes/Service.js:222:41)
      at /git/node_modules/serverless/lib/Serverless.js:200:49
      at tryCatcher (/git/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/git/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/git/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/git/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/git/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/git/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/git/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/git/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/git/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.20.1
     Framework Version:         2.18.0 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.6
```

</details>

**Installed version**

```
Framework Core: 2.18.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```

**Comment by lewgordon** [comment]
Here's another example of probably a more realistic scenario, where there is a dependency on `ajv@^6`.  Again using a node:12 container.

<details>
<summary><code>package.json</code></summary>

```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ajv": "^6.12.6"
  },
  "devDependencies": {
    "serverless": "^2.18.0"
  }
}
```

</details>

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: test
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: 
#      - s3: 
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
```

</details>

<details>
<summary><code>sls package</code> output</summary>

```
  Error --------------------------------------------------
 
  Error: Cannot find module 'ajv/dist/compile/codegen'
  Require stack:
  - /git/node_modules/ajv-keywords/dist/definitions/typeof.js
  - /git/node_modules/ajv-keywords/dist/keywords/typeof.js
  - /git/node_modules/ajv-keywords/dist/keywords/index.js
  - /git/node_modules/ajv-keywords/dist/index.js
  - /git/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js
  - /git/node_modules/serverless/lib/Serverless.js
  - /git/node_modules/serverless/scripts/serverless.js
  - /git/node_modules/serverless/bin/serverless.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
      at Function.Module._load (internal/modules/cjs/loader.js:667:27)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/definitions/typeof.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/keywords/typeof.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/keywords/index.ts:2:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/git/node_modules/ajv-keywords/src/index.ts:3:1)
      at Module._compile (internal/modules/cjs/loader.js:999:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at ConfigSchemaHandler.validateConfig (/git/node_modules/serverless/lib/classes/ConfigSchemaHandler/index.js:102:5)
      at Service.validate (/git/node_modules/serverless/lib/classes/Service.js:222:41)
      at /git/node_modules/serverless/lib/Serverless.js:200:49
      at tryCatcher (/git/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/git/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/git/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/git/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/git/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/git/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/git/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/git/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/git/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.20.1
     Framework Version:         2.18.0 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.6
```
</details>

<details>
<summary><code>history</code> output</summary>

```
root@a78b7ee06b20:/git# history
    1  mkdir git
    2  cd git
    3  cat <<EOF >> package.json
...
EOF

    4  npm i
    5  cat <<EOF >> serverless.yml
...
EOF

    6  sls package
    7  export PATH=/git/node_modules/.bin:$PATH
    8  sls package
```

</details>
