### ISSUE TITLE
serverless invoke local not working for maven project

### ISSUE THREAD

**Issue by JaspreetChhabra** [serverless/serverless#8729]
I am trying to invoke aws java function locally using "invoke local" command, but getting below error. 

> serverless invoke local -f FirstFunction

Error:

> Error: Artifact undefined doesn't exists, please compile it first.
      at AwsInvokeLocal.callJavaBridge (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:580:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:518:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:553:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:553:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:203:33
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:190:74)
      at /usr/local/lib/node_modules/serverless/scripts/serverless.js:50:26

I have also created the invoke-bridge-1.0.1.jar inside the /usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/runtimeWrappers/java/target using mvn package command.
Have also tried giving chmod 777 permission to the target folder. The project is a spring boot project and I am trying to invoke the lambda locally. Deployed the lambda on aws and it is working fine. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# 
service: lms-develop-ns

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: java11
  region: us-west-2
  stage: dev
  timeout: 60
  memorySize: 256
  
functions:
  FirstFunction:
    name: FirstFunction
    handler: com.csod.FirstFunction::handleRequest
    runtime: java11
    Policies:
      - LambdaInvokePolicy:
          FunctionName:
            !Ref SecondFunction
    iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction 
        Resource:
          - arn:aws:lambda:us-west-2:*:* 
    package:
      individually: true
      artifact: build/distributions/lms-develop-ns-final.zip

  SecondFunction:
    name: SecondFunction
    handler: com.csod.SecondFunction::handleRequest
    runtime: java11
    iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource:
          - arn:aws:lambda:us-west-2:*:*
    package:
      individually: true
      artifact: build/distributions/lms-develop-ns-final.zip
```

</details>

<details>
<summary><b><code> serverless invoke local -f FirstFunction</code> output</b></summary>

```
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.18.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Configuration warning:
Serverless:   at 'functions.FirstFunction': unrecognized property 'Policies'
Serverless:   at 'functions.FirstFunction': unrecognized property 'iamRoleStatements'
Serverless:   at 'functions.SecondFunction': unrecognized property 'iamRoleStatements'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke invoke:local
Serverless: Building Java bridge, first invocation might take a bit longer.
 
  Error --------------------------------------------------
 
  Error: Artifact undefined doesn't exists, please compile it first.
      at AwsInvokeLocal.callJavaBridge (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:580:13)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:518:22)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:553:24
  From previous event:
      at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:553:8)
      at /usr/local/lib/node_modules/serverless/lib/Serverless.js:203:33
      at processImmediate (internal/timers.js:461:21)
  From previous event:
      at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:190:74)
      at /usr/local/lib/node_modules/serverless/scripts/serverless.js:50:26
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.19.0
     Framework Version:         2.18.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.6

```

</details>

<b>Installed version</b>

```
Framework Core: 2.18.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```
