### ISSUE TITLE
When using async: true HTTP event and setting the timeout > 30 seconds WARNING is shown

### ISSUE THREAD

**Issue by MEGApixel23** [serverless/serverless#8739]
When using async: true HTTP event and setting the timeout > 30 seconds the following warning is shown:
`WARNING: Function first has timeout of 31 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.`
It's not relevant since the lambda handler will be invoked in async mode and the response to API Gateway will be returned immediately.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: nodejs10.x
functions:
  myFunction:
    handler: handler.main
    timeout: 240
    events:
      - http:
          path: some/url/here
          method: get
          async: true
```

</details>

<details>
<summary><b><code>sls deploy --stage dev</code> output</b></summary>

```
Serverless: WARNING: Function wufooFormSubmittedHook has timeout of 240 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
```

</details>

<b>Installed version</b>

```
Framework Core: 2.17.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```
