### ISSUE TITLE
Model validation failed (#/EventSourceArn: failed validation constraint for keyword [pattern])

### ISSUE THREAD

**Issue by throrin19** [serverless/serverless#8758]
When I want to publish my functions with last version of serverless (2.18.0) I have this error for function using sqs event with arn directly setted : 

```
Model validation failed (#/EventSourceArn: failed validation constraint for keyword [pattern])
```

When I try in previous version (2.16.1) It works fine

```yaml
service: my-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${env:AWS_DEFAULT_PROFILE}
  region: eu-west-1
  memorySize: 1024
  timeout: 60
  logRetentionInDays: ${self:custom.${opt:stage, 'dev'}.RetentionInDays}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - cloudwatch:*
        - cloudformation:*
        - ec2:*
        - events:*
        - iot:*
        - lambda:*
        - rds:*
        - route53:*
        - s3:*
        - sns:*
        - sqs:*
        - tag:*
        - es:*
        - xray:*
        - apigateway:*
        - elasticloadbalancing:*
      Resource: "*"
  vpc: ${self:custom.${opt:stage, 'dev'}.vpc}
  environment:
    NODE_ENV: production
    WIRES_ENV: ${self:custom.${opt:stage, 'dev'}.WIRES_ENV}

custom:
  dev:
    accountId : 0123456789345
    WIRES_ENV: development
    RetentionInDays: 30
    moduleLayer: arn:aws:lambda:eu-west-1:0123456789345:layer:serverless-module-dev:12
    vpc:
      securityGroupIds:
        - sg-xxxxxxxxxxxxxxxxx
      subnetIds:
        - subnet-xxxxxxxxxxxxxxxxx
        - subnet-xxxxxxxxxxxxxxxxx
        - subnet-xxxxxxxxxxxxxxxxx
  prune:
    automatic: true
    number: 3

package:
  individually: true
  exclude:
    - node_modules/**
    - wires.*.json
    - claudia/**
    - core/test/**
    - invoke/**
    - test/**
    - tests/**
    - graphite-storage-schemas/**
    - sources/**
    - scripts/**
    - migrations/**
    - modules/**/test/**
    - '*.js'
    - '.nyc_output/**'
    - '.vscode/**'
    - '.editorconfig'
    - '.eslintignore'
    - '.eslintrc'
    - '.gitignore'
    - '.npmignore'
    - 'jsconfig.json'
    - README.md
    - .DS_Store
    - '**/.DS_Store'
  include:
    - _init.js
    - package.json
    - wires-defaults.json
    - wires.${self:custom.${opt:stage, 'dev'}.WIRES_ENV}.json

functions:
  my-function:
    handler: my-function.handler
    reservedConcurrency: 5
    package:
      individually: true
      include:
        - my-function.js
    layers:
      - ${self:custom.${opt:stage, 'dev'}.moduleLayer}
    events:
      - sqs: arn:aws:sqs:eu-west-1:${self:custom.${opt:stage, 'dev'}.accountId}:${self:custom.${opt:stage, 'dev'}.WIRES_ENV}-test

plugins:
  - serverless-prune-plugin

```

```
Serverless Warning --------------------------------------
 
  A valid environment variable to satisfy the declaration 'env:AWS_DEFAULT_PROFILE' could not be found.
 
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service my-function.zip file to S3 (322.64 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - UPDATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MyDashFunctionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MyDashFunctionLambdaFunction
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MyDashFunctionLambdaVersionpfFLqPl6dceyKRrLZYMakXPRNalRIGvyAl96c2l4nM
CloudFormation - CREATE_IN_PROGRESS - AWS::Lambda::Version - MyDashFunctionLambdaVersionpfFLqPl6dceyKRrLZYMakXPRNalRIGvyAl96c2l4nM
CloudFormation - CREATE_COMPLETE - AWS::Lambda::Version - MyDashFunctionLambdaVersionpfFLqPl6dceyKRrLZYMakXPRNalRIGvyAl96c2l4nM
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::EventSourceMapping - MyDashFunctionEventSourceMappingSQSDevelopmentmeasures
CloudFormation - UPDATE_FAILED - AWS::Lambda::EventSourceMapping - MyDashFunctionEventSourceMappingSQSDevelopmentmeasures
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-dev
CloudFormation - UPDATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - UPDATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
CloudFormation - UPDATE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - MyDashFunctionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::Function - MyDashFunctionLambdaFunction
CloudFormation - UPDATE_COMPLETE - AWS::Lambda::EventSourceMapping - MyDashFunctionEventSourceMappingSQSDevelopmentmeasures
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-dev
CloudFormation - DELETE_SKIPPED - AWS::Lambda::Version - MyDashFunctionLambdaVersionpfFLqPl6dceyKRrLZYMakXPRNalRIGvyAl96c2l4nM
CloudFormation - DELETE_COMPLETE - AWS::Lambda::EventSourceMapping - MyDashFunctionEventSourceMappingSQSDevelopmentmeasures
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - serverless-dev
Serverless: Operation failed!
```

<b>Installed version</b>

```
2.18.0
```

**Comment by pgrzesik** [comment]
Hello @throrin19, thanks for reporting. `1.18.0` is not the latest version - do you have a chance to upgrade to latest? Would you be able to post whole stacktrace for situation where your deployment errors out?

**Comment by throrin19** [comment]
Oh sorry. It's 2.18.0. Not 1.18.0. I'm very I'm really distracted today

**Comment by pgrzesik** [comment]
No worries @throrin19, unfortunatelly I wasn't able to reproduce the issue. Do you think you'd have a chance to provide the output of `sls deploy` with that error visible? The one you provided does not include that error. Thanks in advance :bow:

**Comment by Skymogul** [comment]
We are also seeing this in 2.18. It appears to be happening for us any time on a new deployment of an SQS event source mapping:

```
An error occurred: GetCaseDetailsEventSourceMappingSQSRdncaCaseIdQueueprod - Model validation failed (#/EventSourceArn: failed validation constraint for keyword [pattern]).

Your Environment Information ---------------------------
Operating System:          linux
Node Version:              14.4.0
Framework Version:         2.18.0 (standalone)
Plugin Version:            4.4.2
SDK Version:               2.3.2
Components Version:        3.4.5
```

Found a seemingly related issue being discussed for some time in the AWS SAM repo: https://github.com/aws/serverless-application-model/issues/1699.

**Comment by pgrzesik** [comment]
@Skymogul are you seeing it only after upgrading to 2.18.0? I was trying to reproduce but I didn't manage to - could either of you @Skymogul or @throrin19 provide anonymized version of resolved `sqs` ARN? Is there a chance that they're resolved incorrectly and contain invalid characters? I would really appreciate that, thanks in advance :bow:

**Comment by Skymogul** [comment]
@pgrzesik Sure, here's the (anonymized) relevant bit from `serverless print`:
```
processEvent:
     handler: lambdas/processEvent/handler.handle
     timeout: 30
     events:
       - sqs:
           arn: arn:aws:sqs:us-east-1:00000000000:rdn-ci-EventQueue-prod
```

**Comment by Skymogul** [comment]
@pgrzesik Sorry, the above was for a different one that failed in the same way. For the original error I posted above, the relevant `serverless print`:
```
functions:
   getCaseDetails:
     handler: lambdas/getCaseDetails/handler.handle
     layers:
       $ref: $["custom"]["stages"]["prod"]["layers"]
     timeout: 30
     reservedConcurrency: 4
     events:
       - sqs:
           arn: arn:aws:sqs:us-east-1:00000000000:rdn-ca-CaseIdQueue-prod
```

**Comment by pgrzesik** [comment]
Thanks a ton @Skymogul :bow: I'm trying to reproduce, but still didn't manage to on both `2.18.0` and `2.19.0` framework versions. I'm honestly puzzled, as the resolved `arn` for `sqs` in your example above looks valid, I've tried to reproduce the with the exact same naming pattern for `sqs` and it's passing. I'll continue investigation, I've also noticed that in the linked SAM issue someone reported similar problem 3 days ago. Does the issue still persist for you?

**Comment by Skymogul** [comment]
@pgrzesik As to the Serverless version, our CD pipelines currently just take the latest version, installing it by piping `https:slss.io/install | bash`  (on my list). 

What's weirder is that we have two AWS accounts, a non-prod and a prod account. We're only seeing it on the prod account. I removed the stack from our non-prod environment and re-deployed it, no problem. This suggests it might be an account configuration issue, but I'd expect a different error if we were running up against an IAM issue or something like that.

From the non-prod account where it seems to be working, I also did `serverless print`:

```
   getCaseDetails:
     handler: lambdas/getCaseDetails/handler.handle
     layers:
       - >-
         arn:aws:lambda:us-east-1:000000000000:layer:oracleDbInstantClientLibraries:1
     timeout: 30
     reservedConcurrency: 4
     events:
       - sqs:
           arn: arn:aws:sqs:us-east-1:000000000000:rdn-ca-CaseIdQueue-dev
     name: rdn-ca-dev-getCaseDetails
```

ARN looks valid here, too. I'm stumped.

**Comment by Skymogul** [comment]
@pgrzesik The only other thing I can offer is what the CloudFormation events list looks like on the stack:

![image](https://user-images.githubusercontent.com/37735539/104954628-94b83a00-5996-11eb-9847-3e0454b7134b.png)

**Comment by pgrzesik** [comment]
Thank you @Skymogul for all additional details. I'm still trying to reproduce it on different AWS accounts but no luck so far - I'll keep you posted as soon as I find something that might be causing it

**Comment by pgrzesik** [comment]
Hello @Skymogul - unfortunately, no luck with reproducing other than hitting one interesting case where it actually fails with the same error message - I've purposefully provided invalid AccountId in sqs `arn` (I just removed one digit). Is there any chance that the `arn` for `sqs` in template that gets deployed is resolved incorrectly and is missing e.g. a digit? I know this is a long shot, but I didn't find anything else (yet!)

**Comment by throrin19** [comment]
Same as @Skymogul I have no more informations. In my case the SQS already exists before deployment. 

I use CI to launch serverless command and publish my lambdas. If I force version 2.16.1 (previous used version in my CI) it works fine, but If I pass to 2.18.0, I have this error. 

But I find no more information about generated ARN or other in cloudFormation part

**Comment by adam133** [comment]
Found this issue as it was one of the only discussions I could find about this error. I don't have much to contribute, but I don't *think* this is a Serverless issue - we use our own provisioner via boto3.

`Properties validation failed for resource MyStackName with message: #/SourceBucketArn: failed validation constraint for keyword [pattern] #/ExecutionRoleArn: failed validation constraint for keyword [pattern]`

This is for creating a stack for AWS Mangaged Airflow, which also implements and uses an SQS queue behind the scenes. The values for those two parameters in the template: 

`"SourceBucketArn": "arn:aws:s3:::mybucketname"`
`"ExecutionRoleArn": {"Ref": "MyRoleName"}`

Just thought I'd post here as it might be related and help troubleshoot.

**Comment by adam133** [comment]
Update - instead of using `Ref` to get the ARN of the role, I used `GetAtt` and now I no longer get the error on that one. Doesn't explain why the bucket string is failing validation though.

```"ExecutionRoleArn": {"Fn::GetAtt": ["MyRoleName", "Arn"]}```

**Comment by pgrzesik** [comment]
I've did some extra digging and while I didn't find the root cause yet, I think we could potentially improve the validation on Framework side for SQS's `arn`. Right now we're using a simple `^arn:` regex for that, where it's way more detailed for `EventSourceArn`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-eventsourcearn 

I believe that would help us uncover the error with e.g. how the `arn` is resolved from variables. We'd be happy to accept a PR with that improvement :raised_hands:

**Comment by Skymogul** [comment]
@pgrzesik We tried this deployment again last night. It failed again and I opened a ticket with AWS. I believe we have found the problem. This is what AWS found had been submitted from their backend tools (I've anonymized the account number): 

```
{
  "BatchSize":"10",
  "FunctionName":"arn:aws:lambda:us-east-1:011111111111:function:rdn-ca-prod-addAcceptCase",
  "Enabled":"true",
  "EventSourceArn":"arn:aws:sqs:us-east-1:11111111111:rdn-ca-AddAcceptCaseQueue-prod"
}
```
Notice that the account ID in `FunctionName` has a leading zero and is 12 digits long. This is a correct ARN. The SQS queue ARN in the `EventSourceArn` has no leading 0, meaning it's 11 digits long and thus is not a correctly formatted ARN.

The reason this doesn't work in our prod account but does work in our non-prod account? Our prod account is old enough to have an 11 digit account number and needs a leading zero. Our non-prod account is much newer, is a full 12 digits and doesn't need a leading zero.

**Comment by pgrzesik** [comment]
Thank you @Skymogul for followup and a reproducible example :bow: I've managed to reproduce it myself and I believe that the different parsing behavior was also introduced with upgrade of https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md as it changed YAML spec from 1.1 to 1.2 which changes how numbers are interpreted. What's more interesting that the older version was producing even weirder results as with YAML 1.1 numbers with leading `0` were interpreted as octal. 

I've also tested passing `accountId` as string and that's in my opinion the best bet moving forward. 

@throrin19 Would you be able to confirm that in your situation the error is caused by the same thing?

As for the error message getting written to `stdout` - this is something that is in general on our radar - we have a plan for bigger refactoring of our error/logging machinery. However, it still would be good to improve `sqs` arn validation as it should help in this particular case.

Once again, thanks @Skymogul :bow:

**Comment by throrin19** [comment]
@pgrzesik haha it's seems the same. My account ID start with `0`

**Comment by Skymogul** [comment]
I was finally able to get a release out to production changing the account number to a string today, and it worked.

You might want to document this unintended breaking change somewhere.

As for stderr, I found that I just need to adjust the CD tooling to catch the exit code. It's non-zero as expected, but we weren't catching it properly.

**Comment by pgrzesik** [comment]
Thanks @Skymogul for confirmation. I'm still puzzled on how it could work previously, as the previous version parses numbers with leading zeros as octal, which produces invalid `accountId` as well. As for the documentation - that's a great call, however, there's not really a good place to put it, as in your case it's a custom property which, do you have a suggestion where do you think it would be a good place to warn about such issue? 

@throrin19 thanks for confirming :bow:

**Comment by kolinekp** [comment]
@throrin19: I had the same problem and according to your serverless.yml, it's caused by the same cause.

I have noticed, you are also using a custom variable to store your AccountId and it also starts with a 0.
Can you try wrapping your AccountId value in single quotes? `accountId : '0123456789345'` 

I believe the serverless framework treats it as a number, and thus, removes all the leading zeroes. You can also confirm it when inspecting the final CloudFormation template which should be a part of your ServerlessDeploymentBucket.

**Comment by crearc** [comment]
It's worth noting that my accountId is not zero-prefixed and I'm seeing the exact same error. Obfuscated below:

```
  processor:
    handler: src/processor.process
    timeout: 900
    reservedConcurrency: 10
    layers:
      - arn:aws:lambda:us-east-1:XXXXXXXXXXXX:layer:LambdaInsightsExtension:14
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:XXXXXXXXXXXX:processor-queue-dev.fifo
```
