### ISSUE TITLE
AWS tags containing dashes are rejected

### ISSUE THREAD

**Issue by Jalle19** [serverless/serverless#8764]
Trying to define a stack tag with the name `foo:bar-baz` produces a configuration error: `Configuration error at 'provider.tags': unrecognized property 'foo:bar-baz'`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: app

frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  region: eu-central-1
  stage: dev
  runtime: nodejs12.x
  tags:
    'foo:bar-baz': foo
    'foo:bar': bar


functions:
  click-listener:
    handler: handler
    name: click
    description: click
    tags:
      Application: 'ClickListener'
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
 
  Serverless Error ---------------------------------------
 
  Configuration error at 'provider.tags': unrecognized property 'foo:bar-baz'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.4
     Framework Version:         2.18.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.4.6

```

</details>

<b>Installed version</b>

```
Framework Core: 2.18.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.6
```
