### ISSUE TITLE
Error "Event references not configured authorizer 'name'" when following authorizer tutorial

### ISSUE THREAD

**Issue by BryanCrotaz** [serverless/serverless#8781]
Completely failed to work out how to add authorizers to my httpAPI, so trying every example you have.

Followed https://www.serverless.com/framework/docs/providers/aws/events/apigateway#http-endpoints-with-custom-authorizers

I think although this is an http event it's actually a RESTApi?

Get an error `Event references not configured authorizer '<function-name>'` and I can't find any reference to this in the docs. Don't know what event I should be adding to the authorizer function as the examples don't list any events.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: dotnetcore2.1

  stage: dev
  region: us-east-1

  apiGateway:
    minimumCompressionSize: 1024

  httpApi:
    cors: true
    payload: "2.0"
    
package:
  individually: true

functions:

  apiAuthorizer:
    handler: AuthApi::AuthApi.AuthHandlers::Authorize
    package:
      include:
        - AuthApi/AuthApi.csproj
    iamRoleStatements:
      - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
        Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        Resource:
        - 'Fn::Join':
            - ':'
            -
                - 'arn:aws:logs'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'log-group:/aws/lambda/*:*:*'

  get-metric-history:
    handler: DashboardApi::DashboardApi.HistoryHandlers::GetMetricHistory
    environment:
      DeviceMetricsTable: 
        Ref: DeviceMetricsTable
    events:
      - http: 
          path: metrics/history
          method: get
          cors: true
          authorizer: apiAuthorizer
    package:
      include:
        - DashboardApi/DashboardApi.csproj
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource:
          Fn::GetAtt:
            - DeviceMetricsTable
            - Arn
      - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
        Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        Resource:
        - 'Fn::Join':
            - ':'
            -
                - 'arn:aws:logs'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'log-group:/aws/lambda/*:*:*'
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>
</details>

<b>Installed version</b>

```
C:\projects\led-monitor>serverless --version
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 1.77.1
Plugin: 3.6.18
SDK: 2.3.1
Components: 2.33.2
```

**Comment by pgrzesik** [comment]
Hello @BryanCrotaz, thanks for reporting, before treating it as a bug, could you please upgrade to the latest version of Framework (we're currently on `2.19.0` where you're on `1.77.1`) to ensure that the issue wasn't fixed in the meantime?

**Comment by BryanCrotaz** [comment]
I'm using my fork https://github.com/serverless/serverless/pull/8043 as .net isn't supported by master, but I'll try to rebase it.

**Comment by BryanCrotaz** [comment]
No, same problem on master.

**Comment by BryanCrotaz** [comment]
My function definition:

```yaml
  get-metric-history:
    handler: DashboardApi::DashboardApi.HistoryHandlers::GetMetricHistory
    environment:
      DeviceMetricsTable: 
        Ref: DeviceMetricsTable
    events:
      - httpApi: 
          path: metrics/history
          method: get
          authorizer: apiAuthorizer
    package:
      include:
        - DashboardApi/DashboardApi.csproj
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource:
          Fn::GetAtt:
            - DeviceMetricsTable
            - Arn
      - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
        Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        Resource:
        - 'Fn::Join':
            - ':'
            -
                - 'arn:aws:logs'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'log-group:/aws/lambda/*:*:*'
 ```

**Comment by BryanCrotaz** [comment]
Authorizer:
```yaml
  apiAuthorizer:
    handler: AuthApi::AuthApi.AuthHandlers::Authorize
    package:
      include:
        - AuthApi/AuthApi.csproj
    iamRoleStatements:
      - Effect: Allow # note that these rights are given in the default policy and are required if you want logs out of your lambda(s)
        Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        Resource:
        - 'Fn::Join':
            - ':'
            -
                - 'arn:aws:logs'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'log-group:/aws/lambda/*:*:*'

```

**Comment by BryanCrotaz** [comment]
Am I using it incorrectly?

**Comment by BryanCrotaz** [comment]
Worked it out, but error messages were not very helpful. Created a PR with more informative messages.

**Comment by pgrzesik** [comment]
Thanks for the update @BryanCrotaz - do you think we could close this issue then? As for supporting different types of authorizers for HTTP API, let's track that discussion here: https://github.com/serverless/serverless/issues/8210#issuecomment-752148877

**Comment by ed-sparkes** [comment]
#8210 seems to have been forgotten about, 5+ months after release of AWS functionality and hardly any activity on this, kinda takes the zero-friction out of the 'zero-friction serverless deployment'

**Comment by pgrzesik** [comment]
Hello @ed-sparkes - unfortunatelly, there were some other priorities in the meantime, but we plan to dedicate time to #8210 in the coming weeks. I'll follow up later this week on the original issue about authorizers. Sorry for inconvenience.

I'll close this issue and let's move all potential discussions to #8210

**Comment by astuyve** [comment]
👋🏻  Hi @pgrzesik ❤️ 
I noticed this issue today as I was setting up a demo. I received the same message using an HTTP API:
![image](https://user-images.githubusercontent.com/1598537/128783230-d03271c8-1624-4c5f-b47a-ad7c28410396.png)
Naturally I tracked down this issue and #8210 where I found the correct syntax, but so many Serverless blog posts and references use the old style syntax. This led me to attempt this, which throws the above error:
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
          # Broken, do not use
          authorizer: authorizerFunction
```

Instead this works:
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
          customAuthorizer:
            type: request
            functionName: authorizerFunction
```

Would it be possible/would you accept a PR which creates a validation warning when a user uses this syntax? Is there another way this could prevent people from tripping up on `"Event references not configured authorizer 'name'"` while using HTTP APIs?

Thanks, hope you're well!
