### ISSUE TITLE
!Sub in the eventBus

### ISSUE THREAD

**Issue by Wurstnase** [serverless/serverless#8782]
It's not possible to use !Sub in the eventBus.
<details>
<summary><code>serverless-with-pseudo-parameters-plugin.yml</code></summary>

```yml
plugins:
  - serverless-pseudo-parameters

service: dummy

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: dev

functions:
  myevent:
    handler: dummy.handler
    events:
      - eventBridge:
          eventBus: "arn:aws:events:${self:provider.region}:#{AWS::AccountId}:event-bus/dummy-events-${self:provider.stage}"
          pattern:
            source:
              - com.example
```

</details>

The `serverless-with-pseudo-parameters-plugin.yml` above is working.
The `serverless.yml` below not.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: dummy

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: dev

functions:
 myevent:
    handler: dummy.handler
    events:
      - eventBridge:
          eventBus: !Sub "arn:aws:events:${self:provider.region}:${AWS::AccountId}:event-bus/dummy-events-${self:provider.stage}"
          pattern:
            source:
              - com.example

```

</details>

<details>
<summary><b><code>npx sls package</code> output</b></summary>

```
Serverless: Configuration warning at 'functions.myevent.events[0].eventBridge.eventBus': should be string
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.19.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```
