### ISSUE TITLE
Add the enabled flag to API key settings

### ISSUE THREAD

**Issue by JorisPhilipsen** [serverless/serverless#8791]
### Use case description

I was wondering if it would be possible to add the enabled boolean flag to the API key settings in the serverless.yml file. 

### Proposed solution

My proposal would be creating something like this:

```
provider:
  name: aws
  apiKeys:
    - name: ${self:provider.stage}-test-a
      description: Api key test a
      enabled: true
    - name: ${self:provider.stage}-test-b
      description: Api key test b
      enabled: false
   - name: ${self:provider.stage}-test-c
      description: Api key test c
```

If you don't provide an enabled flag, it would be true by default.

Thanks a lot for the great framework you've all made,

Joris
