### ISSUE TITLE
"local invoke" command fails with "[Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by owad** [serverless/serverless#8806]
`serverless invoke local` started failing after upgrading serverless to v2.19.0 (from v.2.18.0). 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
  stage: dev
  region: eu-west-1

functions:
  coffee:
    handler: handler.coffee
    events:
      - http:
          path: coffee
          method: post

```

</details>

<details>
<summary><b><code>serverless invoke local --function coffee --data '{"health": ""}'</code> output</b></summary>

```
$ serverless upgrade 
Serverless: Downloading new version...
Serverless: Successfully upgraded to v2.19.0
$ serverless invoke local --function coffee --data '{"health": ""}'
python3: can't open file '/home/owad/.serverless/artifacts/2.19.0/runtimeWrappers/invoke.py': [Errno 2] No such file or directory
```

</details>

<b>Installed version</b>

```
$ serverless --version 
Framework Core: 2.19.0 (standalone)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7

```
