### ISSUE TITLE
Zipping functions under node v 15.6.0  doesn't work properly

### ISSUE THREAD

**Issue by Selion05** [serverless/serverless#8807]
<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: some-service

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 512
functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: api
          method: get
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
  Serverless Error ---------------------------------------

  An error occurred: ApiLambdaFunction - Uploaded file must be a non-empty zip (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 6724df3d-1291-4cdc-95ca-20fe0b50e5b3; Proxy: null).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              15.6.0
     Framework Version:         1.83.2
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

</details>

unzipping  the package  with unzip

<details>

<summary><b><code>unzip .serverless/some-service.zip -d .serverless/package</code> output</b>
</summary>

```
Archive:  .serverless/some-service.zip
  inflating: .serverless/package/src/index.js   bad CRC 0d3775aa  (should be 00000000)
  inflating: .serverless/package/src/index.ts   bad CRC 1f21f9c6  (should be 00000000)
```

</details>

works but  with `nautilus` every file has  size 0.

Same thing happens if i try serverless 2.20.

so i tried `sls package` with node  14.5.4

<details>
<summary><b><code>unzip .serverless/some-service.zip -d .serverless/package</code> output</b></summary>

```
Archive:  .serverless/some-service.zip
  inflating: .serverless/package/src/index.js
  inflating: .serverless/package/src/index.ts

```
</details>

and the `bad CRC 1f21f9c6` errors are gone
