### ISSUE TITLE
Add support for `tumblingWindowInSeconds` for `stream` event type

### ISSUE THREAD

**Issue by pgrzesik** [serverless/serverless#8815]
### Use case description

Recently, AWS announced support for `TumblingWindowInSeconds` setting, which enables better support for streaming analytics with AWS Lambda. Reference: https://aws.amazon.com/blogs/compute/using-aws-lambda-for-streaming-analytics/

### Proposed solution

Introduce additional property, `tumblingWindowInSeconds` for `stream` event type, that will allow using capabilities described above with Serverless Framework. 

Reference CloudFormation documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-tumblingwindowinseconds 

Example configuration:
```
functions:
  process:
    handler: handler.process
    events:
      - stream:
          arn: arn:aws:kinesis:region:XXXXXX:stream/foo
          tumblingWindowInSeconds: 100
```

Implementation should properly pass that property to `EventSourceMapping` CF Resource: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/stream.js#L201

All feedback is welcome, we'd be also very happy to accept a PR with implementation for this one :raised_hands:
