### ISSUE TITLE
Add support for Amazon MQ as an event source for AWS Lambda

### ISSUE THREAD

**Issue by pgrzesik** [serverless/serverless#8816]
### Use case description

AWS recently announced support for Amazon MQ as an event source for AWS Lambda. Reference article: https://aws.amazon.com/blogs/compute/using-amazon-mq-as-an-event-source-for-aws-lambda/

### Proposed solution

Introduce a new event type, `mq`, that will allow to use Amazon MQ as an event source for `functions` defined with Serverless Framework. General implementation will be fairly similar to e.g. `msk`: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/msk/index.js

Based on documentation, Amazon MQ integration supports the following properties on CloudFormation level:
- `SourceAccessConfigurations` 
- `Queues`
- `BatchSize`
- `Enabled`
- `EventSourceArn`

which could translate to the following event definition:

```
functions:
  process:
    handler: handler.process
    events:
      - mq:
          arn: arn:aws:mq:us-east-1:0000:broker:ExampleMQBroker:b-xxx-xxx
          enabled: true
          queue: queue-name
          batchSize: 100
          accessConfigurations:
            basicAuth: arn:aws:secretsmanager:us-east-1:01234567890:secret:MySecret
```

`accessConfigurations` should be consistent with approach used in: https://github.com/serverless/serverless/pull/8784/files

All feedback is welcome, we'd be more than happy to accept a PR adding support for this one :raised_hands:
