### ISSUE TITLE
False positive with cloudFront.origin schema validation

### ISSUE THREAD

**Issue by frozenbonito** [serverless/serverless#8817]
`serverless` warns that `cloudFront.origin.Id` is required property, but it is actually wrong.
The deployment without `cloudFront.origin.Id` will be successful and work fine.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: cloudfront-test

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  lambdaAtEdge:
    handler: index.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin:
            DomainName: mybucket.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/XXXXXXXXXXXXXX
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
$ sls deploy
Serverless: Configuration warning at 'functions.lambdaAtEdge.events[0].cloudFront.origin': should have required property 'Id'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service cloudfront-test.zip file to S3 (257 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.....................
Serverless: Stack update finished...
Service Information
service: cloudfront-test
stage: dev
region: us-east-1
stack: cloudfront-test-dev
resources: 8
api keys:
  None
endpoints:
  CloudFront - xxxxxxxxxxxxxx.cloudfront.net
functions:
  lambdaAtEdge: cloudfront-test-dev-lambdaAtEdge
layers:
  None

********************************************************************************************************************************************
Serverless: Announcing an enhanced experience for Serverless Full-Stack Applications: https://github.com/serverless-components/fullstack-app
********************************************************************************************************************************************
```

</details>

<b>Installed version</b>

```
Framework Core: 2.20.1 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```
