### ISSUE TITLE
CloudFront CachePolicy is not uniquely named

### ISSUE THREAD

**Issue by frozenbonito** [serverless/serverless#8818]
According to [CloudFomation document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cachepolicy-cachepolicyconfig.html), CachePolicy must have _unique_ name.

However, serverless generates CachePolicy name by key of `provider.cloudFront.cachePolicies` simply.
It makes deployment to fail when deploying to multiple stage.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: cloudfront-cache-policy-test

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  cloudFront:
    cachePolicies:
      myCachePolicy:
        MinTTL: 0
        MaxTTL: 86000
        DefaultTTL: 3600
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

functions:
  lambdaAtEdge:
    handler: index.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin:
            DomainName: mybucket.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/XXXXXXXXXXXXXX
          cachePolicy:
            name: myCachePolicy
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
$ sls deploy
Serverless: Configuration warning at 'functions.lambdaAtEdge.events[0].cloudFront.origin': should have required property 'Id'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service cloudfront-cache-policy-test.zip file to S3 (257 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
........................
Serverless: Stack update finished...
Service Information
service: cloudfront-cache-policy-test
stage: dev
region: us-east-1
stack: cloudfront-cache-policy-test-dev
resources: 9
api keys:
  None
endpoints:
  CloudFront - xxxxxxxxxxxxxx.cloudfront.net
functions:
  lambdaAtEdge: cloudfront-cache-policy-test-dev-lambdaAtEdge
layers:
  None
```

```
$ npx sls deploy --stage prd
Serverless: Configuration warning at 'functions.lambdaAtEdge.events[0].cloudFront.origin': should have required property 'Id'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service cloudfront-cache-policy-test.zip file to S3 (257 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%XXXXXXXXXXXXXX%3Astack%2Fcloudfront-cache-policy-test-prd%2Fxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

  Serverless Error ---------------------------------------

  An error occurred: CloudFrontCachePolicyMyCachePolicy - Internal error reported from downstream service during operation 'AWS::CloudFront::CachePolicy'..

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.15.0
     Framework Version:         2.20.1 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.5.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.20.1 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```
