### ISSUE TITLE
cloudFront.origin should support CF intrinsic functions

### ISSUE THREAD

**Issue by frozenbonito** [serverless/serverless#8819]
`cloudFront.origin` supports CloudFormation yaml syntax for specific setup.
That means it also supports CloudFormation intrinsic functions, and it actually works fine.

However, config schema doesn't support CF intrinsic functions, so serverless reports warnings about them.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: cloudfront-cf-function-test

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  lambdaAtEdge:
    handler: index.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin:
            DomainName:
              Fn::GetAtt:
                - S3Bucket
                - DomainName
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Sub: origin-access-identity/cloudfront/${OriginAccessIdentity}

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mybucket
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3Bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  Fn::Sub: arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OriginAccessIdentity}
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - "/"
                  - - Fn::GetAtt:
                        - S3Bucket
                        - Arn
                    - "*"
    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment:
            Ref: AWS::StackName
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
$ sls deploy
Serverless: Configuration warning:
Serverless:   at 'functions.lambdaAtEdge.events[0].cloudFront.origin': should have required property 'Id'
Serverless:   at 'functions.lambdaAtEdge.events[0].cloudFront.origin.DomainName': should be string
Serverless:   at 'functions.lambdaAtEdge.events[0].cloudFront.origin.S3OriginConfig.OriginAccessIdentity': should be string
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service cloudfront-cf-function-test.zip file to S3 (257 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..............................
Serverless: Stack update finished...
Service Information
service: cloudfront-cf-function-test
stage: dev
region: us-east-1
stack: cloudfront-cf-function-test-dev
resources: 11
api keys:
  None
endpoints:
  CloudFront - xxxxxxxxxxxxxx.cloudfront.net
functions:
  lambdaAtEdge: cloudfront-cf-function-test-dev-lambdaAtEdge
layers:
  None
```

</details>

<b>Installed version</b>

```
Framework Core: 2.20.1 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```
