### ISSUE TITLE
`maximumRetryAttempts` not honoured at function or event level

### ISSUE THREAD

**Issue by brianjd** [serverless/serverless#8830]
`maximumRetryAttempts` value not being honoured at either event or function level.

<details>
<summary>
<code>
serverless.yml
</code>
</summary>

```yaml
  fnName:
    handler: src/my/handler/path.handler
    memorySize: 3008
    timeout: 900 # 15 minutes in seconds (max value)
    maximumRetryAttempts: 10 <-- not honoured
    events:
      - stream:
          type: kinesis
          arn: arn::kinesis
          batchSize: 10
          startingPosition: LATEST
          enabled: true
          parallelizationFactor: 2
          maximumRetryAttempts: 10 <-- no honoured either
```

</details>

<details>
<summary><b><code>N/A</code> output</b></summary>

```
N/A
```

</details>

<b>Installed version</b>

```
2.20.0
```

**Comment by pgrzesik** [comment]
Hello @brianjd, thanks for reporting. `maximumRetryAttempts` is not supported on function level, however, it's supported on event level. I've tried to reproduce your issue with minimal example but it seem to be working correctly. Are you able to share e.g. screenshots from corresponding trigger definitions where the `maximumRetryAttempts` option is not taken into account?

Example that I've used when trying to reproduce:
```
frameworkVersion: '2'
service: servicename

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:xxxxxxxxxx:stream/test-stream
          maximumRetryAttempts: 15

```
