### ISSUE TITLE
TypeError: Cannot read property 'objectMode' of undefined`

### ISSUE THREAD

**Issue by Needith** [serverless/serverless#8837]
Ok so the problem I have is this weird ```  TypeError: Cannot read property 'objectMode' of undefined``` error. The thing happends when I run deploy with ```serverless-python-requirements``` and ```serverless-s3-sync``` plugins. This does not happend when i run plugins separetly OR when i remove the lambda function from and both plugins are in .yaml file. 
And yes I know my framework version is old. I tried reinstalling everything (npm, sls, all the plugins) and getting the newest version but it didnt help so I downgraded back to 1.83 (we use it in other projects and switching is sometimes problematic).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-api

package:
  exclude:
    - node_modules/**
    - venv/**

provider:
  name: aws
  runtime: python3.7
  memorySize: 128
  timeout: 4
  stage: ${opt:stage, 'test'}
  region: eu-west-1
  endpointType: REGIONAL
  environment:
    STAGE: ${self:provider.stage}

functions:
  hello:
    handler: hello.hello
    events:
      - http:
          path: '/hello'
          method: get

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.variables.siteBucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.variables.siteBucketName}/*

custom:
  variables:
    siteBucketName: ${self:custom.customDomain.domainName}
  customDomain:
    basePath: ""
    domainName: ${self:provider.stage}.horser.eu
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: regional
  s3Sync:
    - bucketName: ${self:custom.customDomain.domainName}
      localDir: ./front
      prefix: front
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    noDeploy:
      - pytest
      - moto
      - docutils
      - jmespath

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
  - serverless-s3-sync
  - serverless-domain-manager

```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls deploy </code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command s3sync
Serverless: Load command s3sync:bucket
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generated requirements from /home/mrudnoru/projects/horser/api/requirements.txt in /home/mrudnoru/projects/horser/api/.serverless/requirements.txt...
Serverless: Using static cache of requirements found at /home/mrudnoru/.cache/serverless-python-requirements/4b70188ec1fa84b9be43dc1b6cb5a0387255d0057e8a57fe9314c41981050281_slspyc ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'objectMode' of undefined
      at WriteStream.Writable.write (_stream_writable.js:294:24)
      at NodejsStreamOutputAdapter.ondata (/home/mrudnoru/projects/horser/api/node_modules/readable-stream/lib/_stream_readable.js:619:20)
      at NodejsStreamOutputAdapter.emit (events.js:314:20)
      at NodejsStreamOutputAdapter.EventEmitter.emit (domain.js:483:12)
      at addChunk (/home/mrudnoru/projects/horser/api/node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (/home/mrudnoru/projects/horser/api/node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at NodejsStreamOutputAdapter.Readable.push (/home/mrudnoru/projects/horser/api/node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at StreamHelper.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/nodejs/NodejsStreamOutputAdapter.js:22:19)
      at ConvertWorker.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/StreamHelper.js:165:20)
      at ConvertWorker.emit (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
      at ConvertWorker.push (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:48:14)
      at ConvertWorker.processChunk (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/ConvertWorker.js:21:10)
      at ZipFileWorker.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:154:18)
      at ZipFileWorker.emit (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
      at ZipFileWorker.push (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:48:14)
      at ZipFileWorker.push (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/generate/ZipFileWorker.js:371:38)
      at ZipFileWorker.closedSource (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/generate/ZipFileWorker.js:423:14)
      at DataLengthProbe.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/generate/ZipFileWorker.js:480:14)
      at DataLengthProbe.emit (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
      at DataLengthProbe.end (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:61:18)
      at GenericWorker.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:157:18)
      at GenericWorker.emit (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
      at GenericWorker.end (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:61:18)
      at DataLengthProbe.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:157:18)
      at DataLengthProbe.emit (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
      at DataLengthProbe.end (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:61:18)
      at Crc32Probe.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:157:18)
      at Crc32Probe.emit (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
      at Crc32Probe.end (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:61:18)
      at DataWorker.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:157:18)
      at DataWorker.emit (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:122:42)
      at DataWorker.end (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/GenericWorker.js:61:18)
      at DataWorker._tick (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/DataWorker.js:92:21)
      at DataWorker._tickAndRepeat (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/stream/DataWorker.js:72:10)
      at Immediate.<anonymous> (/home/mrudnoru/projects/horser/api/node_modules/jszip/lib/utils.js:381:18)
      at processImmediate (internal/timers.js:461:21)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.20.0
     Framework Version:         1.83.0
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9

```

</details>

<b>Installed version</b>

```
Framework Core: 1.83.0
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9

```
