### ISSUE TITLE
An error occurred: ApiGatewayLogGroup

### ISSUE THREAD

**Issue by TrierHealth** [serverless/serverless#8841]
Hi,

For the past 2 days our deployments are failing with the below reason. Earlier it was absolutely fine.

An error occurred: ApiGatewayLogGroup - Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/api-gateway/ourloggroupname"}' already exists.

Thanks,.
Ravi.

**Comment by pgrzesik** [comment]
Hello @TrierHealth, sorry to hear that - could you provide a bit more details about the issue? What Framework version are you currently using?

**Comment by TrierHealth** [comment]
Hi,

We are using 1.83.0. The same version has been working fine. But the issue started recently when I posted it here. Earlier api gateway loggroup wasn't enabled from serverless.yml, but later added. could that be causing something? Also, for a couple of apis we are able to run the severless yml after deleting the api gateway log group manually. But that is not working always.

Thanks,
Ravi V.

**Comment by pgrzesik** [comment]
Thanks for providing more information @TrierHealth - do you have an option to upgrade to latest version of Serverless Framework (we're now on `2.21.1`) and see if the problem persists? Are you using any plugins related to `apiGateway` that might be interfering with configuration?

**Comment by TrierHealth** [comment]
Hi,
I can try with 2.21.1 and let you know.
The below are the plugins we are using:
```
plugins:
  - serverless-offline
  - serverless-ignore
  - serverless-domain-manager
```
The provider config is as below

```
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true # optional, enables tracing for all functions (can be true (true equals 'Active') 'Active' or 'PassThrough')
    apiGateway: true
  apiGateway:
    metrics: true
  logs:
    restApi: true
```
