### ISSUE TITLE
Container deployment: entryPoint and command are ignored

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#8842]
The `entryPoint` and `command` options when using Docker images are not configured on the Lambda. These settings are ignored.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  ecr:
    images:
      app:
        path: .

functions:
  app:
    image: app
    entryPoint:
      - foo
    command:
      - bar
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Deployment via `sls deploy` is OK
```

The Lambda is not configured correctly:

<img width="1060" alt="Screen 20210127 qIUfV1cC@2x" src="https://user-images.githubusercontent.com/720328/105998043-8a8bef00-60ac-11eb-865a-8da6e47c4888.png">

</details>

<b>Installed version</b>

```
Framework Core: 2.21.1
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```

**Comment by pgrzesik** [comment]
Hello @mnapoli :wave: In order to provide these settings you have to use object-based definition for an image, for example:

```
provider:
  name: aws
  ecr:
    images:
      app:
        path: .

functions:
  app:
    image: 
      name app
      entryPoint:
        - foo
      command:
        - bar
```

Is there documentation where it's listed in a way that you provided? I would appreciate the link so it can be fixed :100: 

Thanks!
