### ISSUE TITLE
Missing type definition for provider.logRetentionInDays

### ISSUE THREAD

**Issue by frozenbonito** [serverless/serverless#8843]
`provider.logRetentionInDays` property requires number, but there is no type definition for it in config schema.
This issue breaks type coercion (#8319) and prevents making it configurable by option or environment variable.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myservice

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  logRetentionInDays: ${opt:log-retention}
  lambdaHashingVersion: 20201221

functions:
  lambdaAtEdge:
    handler: index.handler
```

</details>

<details>
<summary><b><code>sls package --log-retention 7</code> output</b></summary>

```
$ sls package --log-retention 7
Serverless: Configuration warning at 'provider.logRetentionInDays': should be equal to one of the allowed values
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.21.1 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```
