### ISSUE TITLE
httpAPI enable detailed metrics not working

### ISSUE THREAD

**Issue by estebanes22** [serverless/serverless#8854]
using httpAPI for AWS API Gateway. I need to enable detailed metrics so I added the flag to the provider as instructed:
![image](https://user-images.githubusercontent.com/51391611/106304489-0444e980-6221-11eb-89d0-3ee02becb6d1.png)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  logs:
      httpApi: true
  name: aws
  runtime: ${self:custom.nodejsRuntime}
  stage: dev
  region: ${opt:region,'us-east-2'} # this allows us to specify the region through a CLI argument
  deploymentBucket: ${env:DEPLOYMENT_BUCKET} #parent bucket for S3 deployment artifacts
  httpApi:
    authorizers:
      forgerockAuthorizer: 
        identitySource: $request.header.Authorization
        issuerUrl: ${env:AUTHORIZER_ISSUER_URL}
        audience:
          - XXXXXXXXXXXXX
          - XXXXXXXXXXXXX
    cors:
      allowedOrigins: 
        ${file(./cors-origins.yml)}
      allowedHeaders:
        - "*"
      allowedMethods:
        - GET
        - PUT
        - POST
      exposedResponseHeaders:
        - "*"
      maxAge: 60 #seconds
  metrics: true
```

</details>

```
Serverless: Configuration warning at 'provider': unrecognized property 'metrics'
```

</details>

<b>Installed version</b>

```
serverless@2.15.0
```
