### ISSUE TITLE
Customize the Dockerfile name when deploying Docker images

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#8856]
### Use case description

Currently, when deploying using a Docker image, we must create a file named `Dockerfile`.

Goal: deploy Docker images with a custom Dockerfile name, e.g. `app.Dockerfile`.

### Proposed solution

```yaml
provider:
  name: aws
  ecr:
    images:
      app:
        path: .
        file: app.Dockerfile
```

This would match the existing options of [`docker build`](https://docs.docker.com/engine/reference/commandline/build/):

- [`path`](https://docs.docker.com/engine/reference/commandline/build/#build-with-path) lets us change the context path
- [`-f`](https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f) lets us customize the Dockerfile file name

I have noticed that the file name is currently hardcoded:

https://github.com/serverless/serverless/blob/f5174ffa8027392525a7c57ea1fa59627a61bcc1/lib/plugins/aws/provider.js#L1901
