### ISSUE TITLE
Prevent resource creation

### ISSUE THREAD

**Issue by mschwebler-tgm** [serverless/serverless#8877]
### Use case description

Some resources created by default cause problems in certain scenarios. 

**Example:**
When using an authorizer lambda function from another account, serverless tries to create a lambda-permission-resource in the remote account.
```json
"Resources": {
  "AuthorizerLambdaPermissionApiGateway": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": "arn:aws:lambda:eu-west-1:xxxxxxxxxxxx:function:my-custom-authorizer",
        "Action": "lambda:InvokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":execute-api:",
              {
                "Ref": "AWS::Region"
              },
              ":",
              {
                "Ref": "AWS::AccountId"
              },
              ":",
              {
                "Ref": "ApiGatewayRestApi"
              },
              "/*/*"
            ]
          ]
        }
      }
    }
}
```
Of course, this results in a "Permission Denied" error, as serverless cannot create this resource in the remote account.
My current workaround is to add a hook to `after:package:finalize` in order to cut out the resource using JQ.

### Proposed solution

**Suggestion 1**
Enhance the "extensions" feature to be able to override whole resources instead of just properties.
```yaml
...

resources:
  extensions:
    AuthorizerLambdaPermissionApiGateway: ${AWS:NoValue}
```

**Suggestion 2**
Similar to the "extensions" feature there could be a "preventCreation" or "doNotCreate" configuration option:
```yaml
...

resources:
  preventCreation:
    - 'AuthorizerLambdaPermissionApiGateway'
```

**Comment by pgrzesik** [comment]
Hello @mschwebler-tgm, thanks for submitting your proposal. Do you have any other places where do you think such functionality might be needed? For your specific use case, there's `managedExternally` setting that can be used to disable `AWS::Lambda::Permission` creation for this very scenario. Please see the related docs: https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#http-endpoints-with-custom-authorizers and below an example with how it's used:

```
functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
          authorizer:
            arn: xxx:xxx:Lambda-Name
            managedExternally: true
```

Please let me know if that addresses your use case, thanks in advance :bow:
