### ISSUE TITLE
When invoking locally hangs on "Serverless: Installing dependencies for custom CloudFormation resources..."

### ISSUE THREAD

**Issue by mcaubrey** [serverless/serverless#8879]
When invoking locally via a command such as `SLS_DEBUG=* sls invoke local -f login -d "{ \"key\": \"foobar\" }" -vvv` it hangs on `Serverless: Invoke aws:common:moveArtifactsToPackage` without ever throwing an error (after leaving it that way for an hour, it is yet to be seen if it might eventually throw some error). This occurred only when data was passed. When do data was passed (`SLS_DEBUG=* sls invoke local -f login -vvv`) it invoked without a problem. 

In the process of writing this bug report. I made a copy of my project, removed plugins and sensitive information, and tried to reproduce the problem. Upon trying to reproduce the problem from a different folder, the invocation hanged at `Serverless: Installing dependencies for custom CloudFormation resources...` This seems to occur without regard to whether or not data is passed. 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: dummy-for-reproduction

frameworkVersion: "2"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

custom: ${file(./config.json)}

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.stage}
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  memorySize: 128
  logs:
    restApi: true
  stackTags:
    squad: Test
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment: ${opt:environment, self:custom.environment}

functions:
  login:
    handler: bin/login
    events:
      - http:
          path: login
          method: get
          cors: true
    environment:
      reference: "http://example.com/interal-wiki-url"

```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls invoke local -f login -d "{ \"key\": \"foobar\" }" -vvv</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Serverless constructor expects resolved service configuration path to be provided via "config.configurationPath".
            Starting from next major Serverless will no longer auto resolve that path internally.
            More Info: https://www.serverless.com/framework/docs/deprecations/#MISSING_SERVICE_CONFIGURATION_PATH
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.22.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.1
```
