### ISSUE TITLE
AWS Cognito Event Triggers for CustomEmailSender & CustomSMSSender

### ISSUE THREAD

**Issue by ksparakis** [serverless/serverless#8889]
Cognito has two hidden triggers, that are not available on the console but can be pointed to in the documentation:

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-sender-triggers.html

I would love to be able to link my serverless lambda function to this event within the serverless.yaml.

This seems to be what is currently allowed:
`Serverless: Configuration warning at 'functions.QueueEmailSvc.events[0].cognitoUserPool.trigger': should be equal to one of the allowed values [PreSignUp, PostConfirmation, PreAuthentication, PostAuthentication, PreTokenGeneration, CustomMessage, DefineAuthChallenge, CreateAuthChallenge, VerifyAuthChallengeResponse, UserMigration]`

### Use case description

These hidden AWS Cognito triggers allow us to send emails/sms via a different provider.  I would like to be able to use serverless deploy to deploy my lambdas and hook them directly to these triggers.

### Proposed solution

The proposed solution here is to be able to connect my aws lambda to both of these hidden lambda triggers directly in my serverless.yaml. This would in effect link these functions to the CustomEmailSender and CustomSMSSender triggers in my cognito userpool.

```
functions:
  ExampFunc:
    name:  test123
    handler: src/test.handler
    events:
      - cognitoUserPool:
         pool: {COGNITO_USER_POOL_ID}
         trigger: CustomEmailSender
  ExampFunc2:
    name:  test1234
    handler: src/test2.handler
    events:
      - cognitoUserPool:
         pool: {COGNITO_USER_POOL_ID}
         trigger: CustomSMSSender
```
