### ISSUE TITLE
Allow overriding schema properties

### ISSUE THREAD

**Issue by juanjoDiaz** [serverless/serverless#8903]
### Use case description

In order to minimize repeating myself and favour configuration over coding, I wrote  https://github.com/juanjoDiaz/serverless-middleware which I use in many of my serverless projects.

The plugin essentially allows me to do:
```yaml
functions:
  myFunction:
    handler:
      - auth.authenticate
      - auth.authorize
      - myFunction.handler
      - catch: utils.handlerError
```

This have been extremely handy to have common middleware that I reuse across my functions.

When trying to add schema validation to my plugin, I've found that I can't override the type of `handler` to also support arrays.

> Property 'functions[].handler' already have a definition - this property might have already been defined by the Serverless framework or one other plugin

I understand that #8655 was added just to prevent collisions and that this request might be controversial.
However, what if I want to actually override an existing property?
Is it really my only option to add new property to the function?

### Proposed solution

Allow overriding existing property definitions.
If we want to be extra safe, we can keep the current behaviour as default and add a 3rd parameter to the `defineFunctionProperties` to allow this. `canOverride` or something like that.

**Comment by pgrzesik** [comment]
Thanks for your proposal @juanjoDiaz :bow: I'm not sure about this one, as overriding properties such as `handler` seems dangerous, but on the other hand it's plugin's responsibility to handle any potential issues with that. Out of curiosity - did you consider resolving these middlewares on JS/TS code level e.g. with https://github.com/middyjs/middy? I'm curious about specific use-case here. 

@medikoo what is your opinion on potentially allowing to override `handler` schema via plugins?

**Comment by medikoo** [comment]
@juanjoDiaz I think changing the meaning of core properties can be quite confusing and error-prone for users. I personally feel it's good to keep them locked from external changes (let the plugins extend but purely via extra properties)

Now, answering this specific case, I think it can be expressed quite neatly with below approach:

```yaml
functions:
  myFunction:
    handler: myFunction.handler
    middlewares:
      - auth.authenticate
      - auth.authorize
    errorHandler: utils.handlerError
```

What do you think?

**Comment by juanjoDiaz** [comment]
Your proposal is not bad but it's limiting since you can't have middlewares that run before or after the plugin, and you can't have multiple error handlers in the middle of the stack.

Let's say something like:
```yaml
  myFunction:
    handler:
     - db.connect
      - auth.authenticate
      - auth.authorize
      - catch: auth.checkIfAnonymousIsAllowed
      - myFunction.handler
      - catch: utils.handlerError
     - db.disconnect
```

My current alternative idea is to completely ignore the `handler` and just use a `middlewares` (or even `handlers`) property but I find it not as good.

I started out with something like middy. However, I found it repetitive since most middleware is used in all of my functions.
The greatness of my plugin is that you can define global middlewares that applies to all the functions and you can specify if they should be before or after the handler.
```yaml
custom:
  middleware:
    pre:
      - auth.authenticate
      - auth.authorize
    pos:
      - catch: utils.handlerError
  
functions:
  myFunction:
    handler:
      - catch: auth.IgnoreAuthErrorIfAnonymousIsAllowed
      - myFunction.handler
```

No worries. I understand if you don't want to override properties. And I can go with my plan B. 🙂
