### ISSUE TITLE
Since v2.20.0 sls remove makes (unnecessary?) call to ecr.describeRepositories which fails due to an invalid repositoryName

### ISSUE THREAD

**Issue by philiiiiiipp** [serverless/serverless#8905]
Since v2.20.0, when running `sls remove` on our stack, there seems to be a call to `ecr.describeRepositories` 

```
Serverless: [AWS ecr 400 0.22s 0 retries] describeRepositories({
  repositoryNames: [ 'serverless-dh--bb-wc--app-i-162848903', [length]: 1 ],
  registryId: '723289434150'
})
```

causing

```
ServerlessError: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''
      at /Users/philipp/node/dev/dh/bb-wc/node_modules/serverless/lib/plugins/aws/provider.js:1418:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Which is weird, since we are not using `ecr` at all, but also makes the call for removal of the stack fail. ( The CF ressources are still cleaned up, it appears to be called after the cf removal has been triggered ).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: ${self:custom.project.name}

provider:
  name: aws
  stage: ${file(./serverless.js):provider.stage}
  stackName: ${file(./serverless.js):project.stackName}
  runtime: ${file(./serverless.js):provider.runtime}
  region: ${file(./serverless.js):provider.region}
  deploymentBucket:
    name: ${file(./serverless.js):provider.deploymentBucket.name}

plugins:
  - 'serverless-s3-sync'

custom:
  project: ${file(./serverless.js):project}

  output:
    file: cf-values.json

  # Syncs all static files of our SPA
  s3Sync:
    - bucketName: ${file(./serverless.js):project.alias}
      localDir: build
      acl: public-read
      deleteRemoved: false
      defaultContentType: text/html
      params:
        - '**/**.html':
            'CacheControl': 'public, max-age=0, must-revalidate'
        - '**/**/!(sw).js':
            'CacheControl': 'public, max-age=31536000, immutable'

resources:
  Resources:
    S3DistributionBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${file(./serverless.js):project.alias}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: 'index.html'
          ErrorDocument: 'index.html'

    # Restrict access only through CloudFront
    S3DistributionBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: S3DistributionBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${file(./serverless.js):project.alias}/*

    AppCloudFront:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          Enabled: true
          PriceClass: 'PriceClass_100'
          DefaultRootObject: 'index.html'
          ViewerCertificate: ${file(./serverless.js):project.ViewerCertificate}
          Origins:
            - DomainName: ${file(./serverless.js):project.CF_Origin.DistributionBucket.DomainName}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
              Id: ${file(./serverless.js):project.CF_Origin.DistributionBucket.Id}
          DefaultCacheBehavior:
            Compress: true
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'
            TargetOriginId: ${file(./serverless.js):project.CF_Origin.DistributionBucket.Id}
            ViewerProtocolPolicy: redirect-to-https
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ErrorCachingMinTTL: 0
              ResponsePagePath: /index.html

  Outputs:
    CloudFrontId:
      Description: Cloudfront Id
      Value:
        Ref: AppCloudFront
    CloudFrontURL:
      Description: Autogenerated cloudfront url
      Value:
        Fn::GetAtt: [AppCloudFront, DomainName]

```

</details>

<details>
<summary><b><code>sls remove "--stage" "i-162848903"</code> output</b></summary>

```

sls remove "--stage" "i-162848903"

simple-git deprecation notice: git.silent: logging should be configured using the `debug` library / `DEBUG` environment variable, this will be an error in version 3
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.22.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Invoke remove
getCallerIdentity
{}
Serverless: Getting all objects in S3 bucket...
listObjectsV2
{
  "Bucket": "dh--dev",
  "Prefix": "serverless/dh--bb-wc--app/i-162848903"
}
Serverless: [AWS s3 200 0.26s 0 retries] listObjectsV2({
  Bucket: 'dh--dev',
  Prefix: 'serverless/dh--bb-wc--app/i-162848903'
})
Serverless: Removing objects in S3 bucket...
Serverless: Removing Stack...
deleteStack
{
  "StackName": "dh--bb-wc--i-162848903--app"
}
Serverless: [AWS sts 200 0.523s 0 retries] getCallerIdentity({})
describeRepositories
{
  "repositoryNames": [
    "serverless-dh--bb-wc--app-i-162848903"
  ],
  "registryId": "713289334150"
}
Serverless: [AWS ecr 400 0.22s 0 retries] describeRepositories({
  repositoryNames: [ 'serverless-dh--bb-wc--app-i-162848903', [length]: 1 ],
  registryId: '713289334150'
})
 
  Serverless Error ---------------------------------------
 
  ServerlessError: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''
      at /Users/philipp/node/dev/dh/bb-wc/node_modules/serverless/lib/plugins/aws/provider.js:1418:27
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         2.22.0 (local)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.6.2
```

</details>

<b>Installed version</b>

```
npm list serverless
bb-wc@1.0.0 /Users/philipp/node/dev/dh/bb-wc
└── serverless@2.22.0 
```
