### ISSUE TITLE
Image repository name does not support slashes

### ISSUE THREAD

**Issue by Haggus** [serverless/serverless#8917]
I'm using AWS ECR for storing an image, that is then used by a lambda function.

Defining it in my `serverless.yml` as such:

```yml
functions:
  process-lambda:
    image: "<account_number>.dkr.ecr.us-west-2.amazonaws.com/user-services/process-lambda:latest"
```

When trying to deploy, I'm getting this:

`The repository with name 'user-services' does not exist in the registry with id '<account_number>'`

I'm assuming the code that reads repository name, does not take slashes into account, as the actual repository name is `user-services/process-lambda`.

It's worth mentioning, that when I specify an image using SHA (process-lambda@sha:00000), then it recognizes repository name correctly.

I'm using Serverless in latest stable version `2.23.0`
