### ISSUE TITLE
Too long execution role name

### ISSUE THREAD

**Issue by trigaut** [serverless/serverless#8924]
When running sls deploy on a service with a long service name, a cloud formation validation error prevent to deploy. 
Because the roleName of IamRoleLambdaExecution length exceeds the 64 characters limit.

<details>
<summary><code>serverless.yml</code></summary>

```yaml

service: my-very-very-very-very-very-very-very-long-service-name
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code> sls deploy </code> output</b></summary>

![image](https://user-images.githubusercontent.com/7863528/107498012-8921f280-6b93-11eb-90ed-346eec5782fa.png)

</details>

<b>Installed version</b>

```
Framework Core: 2.18.0 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```

Serverless framework could replace too long role names by shorter ones with a md5 hash similar to 
https://github.com/serverless/serverless/blob/c8547e87520ad0f7dbfb3e083a4399ba43e49703/lib/plugins/aws/customResources/index.js#L57-L65

WDYT ?
