### ISSUE TITLE
httpAPI unable to add tags to gateway

### ISSUE THREAD

**Issue by estebanes22** [serverless/serverless#8934]
API Gateway http API does not tag the gateway. The deployment finishes without errors but at the end I see no tags on these gateways.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
using tags under the aws provider doesn't seem to tag the gateway itself
service: gateway-proxy

provider:
  logs:
    httpApi: true
  name: aws
  runtime: ${self:custom.nodejsRuntime}
  stage: dev
  region: ${opt:region,'us-east-2'} # this allows us to specify the region through a CLI argument
  deploymentBucket: ${env:DEPLOYMENT_BUCKET} #parent bucket for S3 deployment artifacts
  tags:
    Key1: Value1
    Key2: Value2

  httpApi:
    metrics: true
    authorizers:
...etc
```

</details>

</details>

<b>Installed version</b>

```
serverless@2.15.0
```
