### ISSUE TITLE
Cloudformation Modules Bug ?

### ISSUE THREAD

**Issue by stephenbawks** [serverless/serverless#8941]
Tried creating a new Cloudformation Module today I think Serverless Framework is missing the ability to specify `CAPABILITY_AUTO_EXPAND` which I believe is required to use a Cloudformation Module.

```yaml

Resources:
  HTTPCustomDomain:
    Type: CompanyName::HTTPApi::DomainName::MODULE
    Properties:
      ApiType:
        Ref: ApiType
      CertificateArn:
        Ref: CertificateArn
      CustomDomainName:
        Ref: CustomDomainName
      PublicHostedZoneId:
        Ref: PublicHostedZoneId

```

I am passing that into my serverless.yml file under the Resources section.  It should be pointing to the Cloudformation module that I created this morning (no errors, seems to validate correctly) and I can see the module now in my Cloudformation registry with no issues.  

However when I try and do a serveless deploy with that I am getting the error:

`Error: The CloudFormation template is invalid: Invalid template property or properties [HTTPCustomDomain]`

My hunch is that its not doing the `CAPABILITY_AUTO_EXPAND` capability option and hence not actually grabbing the module correctly.  I cannot seem to find any other examples of people trying to use modules yet in Serverless Framework and really looking for some help on this one.  

Cloudformation Capabilities link [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html#API_UpdateStack_RequestParameters)
</details>

Version:
```
Framework Core: 2.20.0 (standalone)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```
