### ISSUE TITLE
Cross-region SNS event triggers not working using CF intrinsic functions

### ISSUE THREAD

**Issue by OliverHofkens** [serverless/serverless#8944]
Configuring cross-region SNS event triggers for functions does not work when specifying the topic ARN using CloudFormation intrinsic functions. 

This functionality was originally implemented in Serverless before (Bug #3676 & PR #6366), and later fixed for the `serverless-pseudo-parameters` plugin (Bug #6760 & PR #6879). Recent versions of Serverless made the `serverless-pseudo-parameters` plugin obsolete, because we can now just use the `!Sub arn:aws:...:${AWS::AccountId}:...` syntax. But when using this syntax, the required `region` field is not added to the `Subscription` struct in CloudFormation, leading to the error:

`An error occurred: ... Invalid parameter: TopicArn (Service: AmazonSNS; Status Code: 400; ...)`

Relevant code starts at: https://github.com/serverless/serverless/blob/7213d1d4f85c7d1583c0eba531e026d3f7a8e96c/lib/plugins/aws/package/compile/events/sns.js#L72

<details>
<summary><code>serverless.yml</code></summary>

```yaml
---
service: my-service

custom:
    sns_topic: my-topic

provider:
    name: aws
    runtime: python3.8
    region: eu-west-1

functions:
    handle_sns_event:
        handler: my.handler
        events:
            - sns:
                  # Same region, works perfectly:
                  arn: !Sub arn:aws:sns:eu-west-1:${AWS::AccountId}:${self:custom.sns_topic}
                  topicName: ${self:custom.sns_topic}-eu-west-1
            - sns:
                  # Different region, errors with "Invalid parameter: TopicArn"
                  arn: !Sub arn:aws:sns:ap-southeast-2:${AWS::AccountId}:${self:custom.sns_topic}
                  topicName: ${self:custom.sns_topic}-ap-southeast-2
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
...
Serverless: Validating template...
Serverless: Updating Stack...

  Serverless Error ---------------------------------------

An error occurred: ...eventsapsoutheast2 - Invalid parameter: TopicArn (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: 087d742e-0729-5e90-8d0c-2c8ea80708da; Proxy: null).

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.8.0
     Framework Version:         2.22.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.6.1


```

</details>

<b>Installed version</b>

```
Framework Core: 2.22.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.1

```
