### ISSUE TITLE
ALB multiple host conditions fails cloudformation validation

### ISSUE THREAD

**Issue by zswanson** [serverless/serverless#8954]
Serverless template with an ALB event that has multiple (more than 1) `host` conditions produces incorrect cloudformation schema and fails validation with AWS, causing a stack rollback. The underlying issue is that cloudformation requires a HostHeaderConfig element when multiple hosts are used in a condition.

The following is the Serverless output in cloudformation right now, but this is invalid.
```
{
            "Field": "host-header",
            "Values": [
              "host1.com",
              "host2.org",
              "host3.net"
            ]
          }
```

It should instead look like this:
```
{
      "Field": "host-header",
      "HostHeaderConfig": {
         "Values": [
             "host1.com",
             "host2.org",
             "host3.net"
         ]
     }
 }
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: myservice
configValidationMode: error

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'us-east-1'}

  versionFunctions: true
  memorySize: 128
  timeout: 10
  logRetentionInDays: 14

  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
    maxPreviousDeploymentArtifacts: 10

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParametersByPath
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:ssm'
            - '${self:provider.region}'
            - Ref: 'AWS::AccountId'
            - 'parameter/${self:provider.stage}/myservice/*'

functions:
  myfunction:
    handler: dist/myhandler
    environment:
      STAGE: ${opt:stage, 'staging'}
    package:
      include:
        - ./dist/**
      exclude:
        - ./**
    events:
      - alb:
          listenerArn: ${ssm:/infra/staging/lambda_alb/https_listener_arn}
          priority: 1
          conditions:
            path: /*
            method:
              - GET
            host:
              - host1.com
              - host2.org
              - host3.net
```

</details>

<details>
<summary><b><code>serverless deploy -s staging</code> output</b></summary>

```
13:28 $ sls deploy -s staging
Serverless: Deprecation warning: Starting with next major version, default value of provider.lambdaHashingVersion will be equal to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service myservice.zip file to S3 (9.61 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.........................
Serverless: Operation failed!
Serverless: View the full error output: <redacted>

  Serverless Error ---------------------------------------

  An error occurred: LandingAlbListenerRule1 - Invalid request provided: AWS::ElasticLoadBalancingV2::ListenerRule Validation exception.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.5.0
     Framework Version:         2.22.0
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.6.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.22.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.6.1
```
