### ISSUE TITLE
Please add Tags to EventBridge Rules

### ISSUE THREAD

**Issue by antstanley** [serverless/serverless#8958]
### Use case description

I need to add Tags to EventBridge Rules created by the Serverless Framework. EventBridge Metrics are all based on Rules, not the eventbus. Without being able to add Tags the EventBridge Rules, I am unable to use the [CloudWatch Metrics Explorer](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Metrics-Explorer.html) to get stats on my EventBridge Rules. Serverless Framework today does not offer the capability to add Tags to rules.

This feature was [requested back in 2019](https://github.com/serverless/serverless/issues/6363#issuecomment-511216036), and appears to have been ignored at the time. It's creating an issue right now, as it hampers the ability to monitor EventBridge.

### Proposed solution

Add a `tags` property consisting of an array key/value objects to the `pattern` property in the rule definition

```
   
       - eventBridge:
          eventBus: my-event-bus
          pattern:
            source:
              - aws.cloudformation
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - cloudformation.amazonaws.com
            tags:
            - key: service
              value: ${self:service}
            - key: stage
              value: ${self:stage}

```

Any assistance in getting this added would be greatly appreciated.
