### ISSUE TITLE
Parameter Replacement for s3 bucket event not working

### ISSUE THREAD

**Issue by mcshiz** [serverless/serverless#8969]
```
  SeedTable:
    handler: functions/SeedTable.handler
    timeout: 900
    memorySize: 2048
    maximumRetryAttempts: 0
    events:
      - s3:
          bucket: !Sub photos-${AWS::AccountId}-test
          event: s3:ObjectCreated:*
          rules:
            - prefix: geo-segments/
            - suffix: .json
```
Results in:
```
Serverless: Packaging service...
 
  Serverless Error ---------------------------------------
 
  [object Object] - Bucket name must conform to pattern (?!^(\d{1,3}\.){3}\d{1,3}$)(^(([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9-]*[a-z0-9])$). Please check provider.s3.[object Object] and/or s3 events of function "SeedTable".
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.10.1
     Framework Version:         2.25.2 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.0
```
**Note**
It also no longer works with the `serverless-pseudo-parameters` plugin 
     `bucket: photos-#{AWS::AccountId}-test`
