### ISSUE TITLE
Stack X does not exist when S3 bucket is full

### ISSUE THREAD

**Issue by ferasallaou** [serverless/serverless#8988]
This is my Env information
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.1
     Framework Version:         2.12.0 (standalone)
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.0
```

When I tried to deploy a new function using `sls deploy` I got the following Error
```
 Serverless Error ---------------------------------------
 
  Stack 'Canarias-development' does not exist
 ```

Even though it was my first time deploying it.
When I tried `sls deploy -v` I got the following message
```
 Serverless Error ---------------------------------------
 
  An error occurred: ServerlessDeploymentBucket - You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: 268E39F02B4E145D; S3 Extended Request ID: REQUESTID=; Proxy: null).
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: Canarias
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}
  region: us-west-2
  profile: default
  memorySize: 512
  environment:
    NODE_PATH: "./:/opt"

 functions:
   app:
     handler: index.defineAuthChallange
     events:
       - http:
           path: /
           method: ANY
       - http:
           path: /{proxy+}
           method: ANY
```

</details>
