### ISSUE TITLE
Maximum batch window in seconds must be greater than 0 if maximum batch size is greater than 10

### ISSUE THREAD

**Issue by MatteoGioioso** [serverless/serverless#8989]
I am trying to set a batchSize for SQS bigger than 10 in **serverless 1.83**, but I keep getting this error:

```
serverless framework An error occurred Invalid request provided: Maximum batch window in seconds must be greater than 0 if maximum batch size is greater than 10

```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 900

resources:
  Resources:
    myQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "MyQueueName"
        VisibilityTimeout: 5400
        ReceiveMessageWaitTimeSeconds: 20

  myFunction:
    handler: path/to/handler.default
    events:
      - sqs:
          arn: arn:aws:sqs:...
          batchSize: 1000
          maximumBatchingWindow: 60
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
Framework Core: 1.83.2
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
