### ISSUE TITLE
Variables resolver reports following resolution errors: Value not found at "self" source -  version ^2.26.0

### ISSUE THREAD

**Issue by ikp4success** [serverless/serverless#8994]
**Q1: Describe the issue**
`./configs/dev.json`
file contents below
```
       { 
           "concurrency": {
                 "some_lambda_function_1": null, # uses account concurrency
                 "some_lambda_function_2": 5
             }
       }
```
it turns out if you try to reference a null value key in serverless.yml it throws `Value not found at "self" source.`

![image](https://user-images.githubusercontent.com/7339334/109044841-e1cbb200-76a0-11eb-928e-e13f6c24a6dd.png)

**Q2: Are we not allowed to reference null values anymore in variables?**

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: some_service
variablesResolutionMode: 20210119
custom:
   config: ${file(./configs/${self:provider.stage}.json)}
functions:
  some_lambda_function_1:
      handler: handler.func
      reservedConcurrency: ${self:custom.config.concurrency.some_lambda_function_1}
  some_lambda_function_2:
      handler: handler.func
      reservedConcurrency: ${self:custom.config.concurrency.some_lambda_function_2}
```

</details>

<b>"serverless": "^2.26.0"</b>

i think the error is coming from     https://github.com/serverless/serverless/blob/bc62e59280ec997442546411676f705036721077/lib/configuration/variables/resolve.js#L141
https://github.com/serverless/serverless/blob/13444caa28a5fdb268599c8fa67f4bfef1dd5e36/scripts/serverless.js#L107

**Comment by medikoo** [comment]
@ikp4success thanks for report!

In new variables resolver consistency is improved, in sense that if (any) variable source reports lack of value (as `null`), then to accept it as valid, you need to configure the fallback for it. However, now also `null` is allowed as fallback.

So in your case following will work as intended:

```yaml
functions:
  some_lambda_function_1:
      handler: handler.func
      reservedConcurrency: ${self:custom.config.concurrency.some_lambda_function_1, null}
  some_lambda_function_2:
      handler: handler.func
      reservedConcurrency: ${self:custom.config.concurrency.some_lambda_function_2, null}
```
