### ISSUE TITLE
${self:provider.stage} Adding local to named stage deploys since 2.26.0 update

### ISSUE THREAD

**Issue by Dleary4395** [serverless/serverless#8995]
**Q1: Describe the issue**
When deploying using `sls deploy -s dev`, our sqs names are being set to local even though the rest of the build is using the proper stage name.

**Q2: Serverless config**
```
service: our-service-name

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'local'}
  region: us-west-1
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

resources:
  Resources:
    ServiceDeadletterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.stage}-service-name-deadletter.fifo
        FifoQueue: true
    ServiceQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.stage}-service-name.fifo
        FifoQueue: true
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ServiceDeadletterQueue.Arn
          maxReceiveCount: 3
```

The queue names being created in AWS are:
`local-service-name-deadletter.fifo`
`local-service-name.fifo`

even though the stage name in the build is correctly being set to dev:
![image](https://user-images.githubusercontent.com/7482021/109050621-9799ff00-76a7-11eb-895d-e8ada0ef341b.png)

**Edit:**
This is also changing all our environment variables to the local values as well
