### ISSUE TITLE
Custom variables and fallbacks aren't working with new 2.26.0 version

### ISSUE THREAD

**Issue by cole-at-work** [serverless/serverless#8999]
With the new version of `2.26.0`, custom variables and their fallbacks aren't resolving as they were in the previous version of `2.25.2`. We are creating custom variables based on which stage is being deployed. For all stages the variable is resolving to the `other` option - see below. The error is being caused by the variable being the incorrect variable for the environment.

Is there a better way to define stage specific variables? Are we doing something wrong?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  stage: ${opt:stage, 'dev'}
custom:
  domain:
    name: ${self:custom.domain.options.${self:provider.stage}, self:custom.domain.options.other}
    options:
      prod: 'theProdOption'
      pilot: 'thePilotOption'
      dev: 'theDevOption'
      other: 'theOtherOption'
```

</details>

<details>
<summary><b><code>serverless deploy --stage pilot</code> output</b></summary>

```
 ServerlessError: An error occurred: ApiMapping - Invalid domain name identifier specified (Service: AmazonApiGateway; Status Code: 404; Error Code: NotFoundException; Request ID: fb93b250-a7eb-4214-a07a-21a8df9bd8a9; Proxy: null).
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:94:23
```

</details>

<b>Installed version</b>

```
     Operating System:          linux
     Node Version:              12.16.2
     Framework Version:         2.26.0
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.1
```
