### ISSUE TITLE
Variables: Introduce access to resolved AWS `accountId` and `region` (via `aws:..`)

### ISSUE THREAD

**Issue by garethmcc** [serverless/serverless#9005]
### Use case description

When configuring a serverless.yml file, sometimes you may need to include the account ID or region for an AWS account in a way that doesn't resolve using CFN syntax. The only way to reliably do so is to inject the account ID using external key/value mechanisms such as dashboard params, environment variables, ssm, etc.

### Proposed solution

The ability to reference a built in variable that resolves to the correct account ID or region. For example:
```yml
custom:
  awsAccountId: ${aws:accountId}
  awsRegion: ${aws:region}
```
