### ISSUE TITLE
alreay exists in stack

### ISSUE THREAD

**Issue by Venus713** [serverless/serverless#9006]
I'm running a my serverless project.
I tried to deploy the my project using following command `sls deploy`, but it gives a following error.
```
Serverless: Checking Stack update progress...
..............................
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A343919453800%3Astack%2Fdata-pipeline-4byte-software-dev%2Fbd8fcf70-7736-11eb-b32c-0acf59e535ed
 
  Serverless Error ---------------------------------------
 
  An error occurred: S3Bucketsoftwarecsvdata - software-csv-data already exists in stack arn:aws:cloudformation:us-east-1:343919453800:stack/data-pipeline-software-dev/bd8fcf70-7736-11eb-b32c-0acf59e535ed.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              15.8.0
     Framework Version:         2.25.2 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.0
```
I tried to deploy a project that it worked fine a 2 months ago, but it also give same error.
Please give me a suggestion.

**Comment by pgrzesik** [comment]
Hello @Venus713, thanks for reporting. Could you please show an example `serverless.yml` file of your configuration to aid in investigating this issue? Are you using `s3` events?

**Comment by Venus713** [comment]
Hi, Thank you for your reply.
Here is my serverless.yml.
```
service: software
frameworkVersion: '2'

custom:
  projectName: software
  documentsTableName: ${self:custom.projectName}-data
  s3bucketName: ${self:custom.projectName}-csv-data
  tableThroughput: 10
  pythonRequirements:
    dockerizePip: non-linux
    layer: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    DB_TABLE_NAME: ${self:custom.documentsTableName}
    S3_BUCKET_NAME: ${self:custom.s3bucketName}
    REGION: ${self:provider.region}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ DataPipelineTable, Arn ]
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
        - 's3:ListBucket'
      Resource: 
        - "arn:aws:s3:::${self:custom.s3bucketName}/*"
        - "arn:aws:s3:::${self:custom.s3bucketName}"

plugins:
  - serverless-python-requirements
  - serverless-offline
functions:
  import_csv_to_db:
    handler: src.handler.import_csv_to_db
    events:
      - s3:
          bucket: ${self:custom.s3bucketName}
          event: s3:ObjectCreated:Put
          rules:
            - suffix: .csv

resources:
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3-bucket.yml)}
```
And here is my s3-bucket.yml.
```
Resources:
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3bucketName}
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
  
  AttachmentsBucketAllowPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AttachmentsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: 
              - "s3:GetObject"
            Resource: 
              - "arn:aws:s3:::${self:custom.s3bucketName}/*"
            Principal: "*"

# Print out the name of the bucket that is created
Outputs:
  AttachmentsBucketName:
    Value:
      Ref: AttachmentsBucket
```
