### ISSUE TITLE
provider.profile with dynamic/nested fallback value resolved incorrectly after update to v2.27

### ISSUE THREAD

**Issue by coyoteecd** [serverless/serverless#9010]
Our frontend repos use serverless + serverless-s3-sync to publish SPA files to an existing S3 bucket.
For convenience, we use a provider.profile that is dynamically selected based on deployment stage; however, in our Jenkins CI pipeline we do not use the profile setting, therefore we override it by passing an empty `--aws-profile=` option.

Up to v2.25, the following variable resolved correctly:
```
provider:
  profile: ${opt:aws-profile, self:custom.deploymentProfiles.${self:provider.stage}, self:custom.deploymentProfiles.dev}

custom:
  deploymentProfiles:
    prod: app-prod
    dev: app-${self:provider.stage}
```
When invoked with `serverless s3sync --stage mystage`, profile resolved to _app-mystage_. After update to v2.27, this resolves to _mystage_.

Removing opt:aws-profile fixes the variable resolution. So the following: `${self:custom.deploymentProfiles.${self:provider.stage}, self:custom.deploymentProfiles.dev}` resolves to _app-mystage_ (with v2.27). But then I lose the ability to override/disable the profile, because `serverless s3sync --stage mystage --aws-profile=` does not work anymore.

I did a bit of debugging to ensure that it's not the fault of the plugin, it looks like the variable resolution done [here ](https://github.com/serverless/serverless/blob/3e47dcc706c64fd107dd88ce17cb8c94eab409b2/scripts/serverless.js#L88-L94) already populates the profile with the incorrect value.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
plugins:
  - serverless-s3-sync

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:aws-profile, self:custom.deploymentProfiles.${self:provider.stage}, self:custom.deploymentProfiles.dev}

custom:
  deploymentProfiles:
    prod: app-prod
    dev: app-${self:provider.stage}
```

</details>

<details>
<summary><b><code>serverless s3sync --stage mystage</code> output</b></summary>

```
 Error --------------------------------------------------

  Error: Profile mystage does not exist
      at Object.addProfileCredentials (K:\SWS\sws-admin\node_modules\serverless\lib\plugins\aws\provider.js:146:15)
      at AwsProvider.getCredentials (K:\SWS\sws-admin\node_modules\serverless\lib\plugins\aws\provider.js:1508:12)
      at AwsProvider.request (K:\SWS\sws-admin\node_modules\serverless\lib\plugins\aws\provider.js:1350:48)
      at Variables.getValueFromCf (K:\SWS\sws-admin\node_modules\serverless\lib\classes\Variables.js:763:8)
      at Variables.getValueFromSource (K:\SWS\sws-admin\node_modules\serverless\lib\classes\Variables.js:579:17)
      at Variables.splitAndGet (K:\SWS\sws-admin\node_modules\serverless\lib\classes\Variables.js:448:17)
      at K:\SWS\sws-admin\node_modules\serverless\lib\classes\Variables.js:387:40
      at Array.map (<anonymous>)
      at Variables.populateMatches (K:\SWS\sws-admin\node_modules\serverless\lib\classes\Variables.js:387:20)
      at Variables.populateValue (K:\SWS\sws-admin\node_modules\serverless\lib\classes\Variables.js:418:30)
```

Above error shows that provider.profile was resolved to 'mystage' instead of 'app-mystage' as it was doing pre-v2.26.
</details>

<b>Installed version</b>

```
     Framework Version:         2.27.0 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.1
```
