### ISSUE TITLE
Unable to use ${AWS::Region} or ${AWS::AccountId} in stackTags

### ISSUE THREAD

**Issue by jamie-unmind** [serverless/serverless#9012]
I would like to use the `stackTags` property in order to tag all resources in my CloudFormation stack. I would like to use `!Sub ${AWS::Region}` and `!Sub ${AWS::AccountId}` as tag values. However, I get the following Serverless error while updating the stack:
```
Serverless Error ---------------------------------------
--
268 |  
269 | There were 2 validation errors:
270 | * InvalidParameterType: Expected params.Tags[1].Value to be a string
271 | * InvalidParameterType: Expected params.Tags[2].Value to be a string
272 |  
273 | Get Support --------------------------------------------
274 | Docs:          docs.serverless.com
275 | Bugs:          github.com/serverless/serverless/issues
276 | Issues:        forum.serverless.com
277 |  
278 | Your Environment Information ---------------------------
279 | Operating System:          linux
280 | Node Version:              12.16.3
281 | Framework Version:         1.83.0 (local)
282 | Plugin Version:            3.8.4
283 | SDK Version:               2.3.2
284 | Components Version:        2.34.9
```

Is this possible in some other way? I have quite a few CF resources inside the `Resources` section where I'm trying to avoid having to set the tagging per resource.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)]+?)}" # Use this for allowing CloudFormation Pseudo-Parameters in your serverless.yml -- e.g. ${AWS::Region}. All other Serverless variables work as usual.
  region: eu-west-1
  runtime: nodejs12.x  
  stackTags:
    aws_region: !Sub ${AWS::Region}
    aws_account_id: !Sub ${AWS::AccountId}    
  environment:
    STAGE: ${self:provider.stage}

resources:
  - Description: ${file(./package.json):description}
  - ${file(cloudformation-resources/iam.yml)}
  - ${file(cloudformation-resources/security-groups.yml)}

functions:
  myFunc:
    handler: ./src/handlers/myFunc.default
    role: MyFuncRole    
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
sls deploy --stage dev
```

</details>

<b>Installed version</b>

```
Framework Core: 1.83.0 (local)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
