### ISSUE TITLE
No xxx.zip provided when trying to deploy package using CodePipeline/CodeBuild

### ISSUE THREAD

**Issue by ghost** [serverless/serverless#9015]
I'm trying to deploy a serverless app with two functions using CodeBuild. In the serverless.yml I used settings for packaging individually with includes and excludes. When I remove these settings from the yaml file, everything runs perfectly. Because we are going to add a lot more functions in the future we really need this functionality to work with AWS CodeBuild.

I feel like this is somehow related to this bug which is closed recently: https://github.com/serverless/serverless/issues/4720

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: xxx
app: xxx-app

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10
  memorySize: 1546
  stage: ${opt:stage}
  iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'secretsmanager:GetSecretValue'
        Resource:
              - ${self:custom.secretArn.${self:provider.stage}}
  region: eu-west-1
  apiGateway:
    restApiId: ${ssm:/api-gateway/${opt:apiName}/${self:provider.stage}/api-id~true}
    restApiRootResourceId: ${ssm:/api-gateway/${opt:apiName}/${self:provider.stage}/root-resource-id~true}

custom:
  secretArn:
    dev: xxx
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500
  apiKeys:
    - name: xxx
      value:
        encrypted: ${ssm:/kms/${opt:apiName}/${self:provider.stage}/api-key~true}
        kmsKeyRegion: eu-west-1

package:
  individually: true
  exclude:
    - ./**

functions:
  function1:
    handler: src/main/function1.getData
    package:
      include:
        - src/main/function1.js
        - src/libs/helper/**
        - node_modules/**
    events:
        - http:
            path: /x/x/x
            method: GET
            private: true
  function2:
    handler: src/main/function2.getData
    package:
      include:
        - src/main/function2.js
        - node_modules/**
    events:
        - http:
            path: /y/y/y
            method: GET
            cors: true

plugins:
  - serverless-api-gateway-throttling
  - serverless-add-api-key
  - serverless-aws-documentation
```

</details>

<details>
<summary><b><code>serverless deploy --stage $ENV --package $CODEBUILD_SRC_DIR/artifacts/$ENV -v</code> output</b></summary>

```

Serverless Error ---------------------------------------
--
  
 No function1.zip file found in the package path you provided.
 
```

</details>

<b>Installed version</b>

```
 Operating System:          linux
 Node Version:              12.16.1
 Framework Version:         2.27.1
 Plugin Version:            4.4.3
 SDK Version:               2.3.2
 Components Version:        3.7.1
```
