### ISSUE TITLE
SLS v2.26.0 or after, CLI commands do not work. Only version command.

### ISSUE THREAD

**Issue by iDVB** [serverless/serverless#9016]
https://serverless-contrib.slack.com/archives/C6TNP39CK/p1614268752000600
Something odd is happening with SLS on any version **after v2.25.2**
When I run `serverless -v` , I get the following…
```
Framework Core: 2.27.1
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```
However ANY other command nothing happens at all. The terminal just successfully returns with ZERO output.

**-- This is also happening in our CI pipeline now with the updated version. --**
**-- Reverting to v2.25.2 resolves the issue --**
**-- Issue starts at v2.26.0 --**

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: stack-proxy

frameworkVersion: ">=2.15.0 <3.0.0"

custom:
  vars: ${file(./vars.yml):${self:provider.stage}, file(./vars.yml):dev}
  epsagon:
    token: NOTTELLING
    appName: ${self:custom.vars.STACKNAME}
    packageJsonPath: ./functions/package.json
  webpack:
    webpackConfig: "./functions/webpack.config.js"
    packager: "yarn"
    excludeFiles: ./functions/**/*.test.js
    includeModules:
      packagePath: "./functions/package.json"
      forceExclude:
        - aws-sdk
  customDomain:
    domainName: ${self:custom.vars.API_DOMAIN}
    certificateName: "*.${self:custom.vars.ROOT_DOMAIN}"
    basePath: "1.0"
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.vars.CREATE_API_DOMAIN}

provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x
  logRetentionInDays: 3
  stage: ${opt:stage, "dev"}
  deploymentBucket:
    name: ${cf:marketing-resources-prod.DeploymentBucket}
  awsKmsKeyArn: ${self:custom.vars.SECRETS_KEY_ARN}
  stackTags: ${self:custom.vars.STACK_TAGS}

functions:
  cfproxyentry:
    handler: functions/cfproxyentry/index.handler
    memorySize: 128
    timeout: 30
    role: CFProxyEntryRole
    package:
      include:
        - functions/cfproxyentry/**/*
    environment:
      ORIGINMAP_TABLE: { Ref: OriginMapTBL }
      DOMAIN: ${self:custom.vars.APEX_DOMAIN}
  originrequestproxy:
    handler: functions/originrequest-proxy/index.handler
    memorySize: 512
    timeout: 30
    role: OriginRequestProxyRole
    lambdaAtEdge:
      distribution: CDN
      eventType: origin-request
    package:
      include:
        - functions/originrequest-proxy/**/*
  originrequest:
    handler: functions/originrequest/index.handler
    memorySize: 512
    timeout: 30
    role: OriginRequestRole
    package:
      include:
        - functions/originrequest/**/*
  originresponse:
    handler: functions/originresponse/index.handler
    memorySize: 128
    timeout: 30
    role: OriginResponseRole
    lambdaAtEdge:
      distribution: CDN
      eventType: origin-response
    package:
      include:
        - functions/originresponse/**/*
  githubwebhook:
    handler: functions/githubwebhook/index.handler
    runtime: nodejs12.x
    memorySize: 256
    timeout: 30
    role: GithubWebhookRole
    events:
      - http:
          path: github/deletebranch
          method: post
          cors: true
    environment:
      PROD_CI_ROLE_ARN: ${self:custom.vars.PROD_CI_ROLE_ARN}
      DEV_CI_ROLE_ARN: ${self:custom.vars.DEV_CI_ROLE_ARN}
      DEV_GITHUB_WEBHOOK_ROLE_ARN: ${self:custom.vars.DEV_GITHUB_WEBHOOK_ROLE_ARN}
      PROD_DEPLOYMENT_BUCKET: ${self:custom.vars.PROD_DEPLOYMENT_BUCKET}
      DEV_DEPLOYMENT_BUCKET: ${self:custom.vars.DEV_DEPLOYMENT_BUCKET}
      DEBUG: "*"
      EPSAGON_DEBUG: "TRUE"
    package:
      include:
        - functions/githubwebhook/**/*
  codefreshtrigger:
    handler: functions/codefreshtrigger/index.handler
    memorySize: 256
    timeout: 30
    role: CodeFreshTriggerRole
    events:
      - http:
          path: codefresh/triggerpipeline
          method: post
          cors: true
    environment:
      CODEFRESH_API: ${self:custom.vars.CODEFRESH_API}
      SECRETS: ${self:custom.vars.SECRETS}
    package:
      include:
        - functions/codefreshtrigger/**/*

resources:
  Description: Marketing Stack Proxy (*.${self:custom.vars.APEX_DOMAIN})
  Transform:
    - Name: CommonTags
      Parameters: ${self:custom.vars.STACK_TAGS}
  Resources:
    SSLCert:
      Type: "AWS::CertificateManager::Certificate"
      Properties:
        DomainName: "*.${self:custom.vars.APEX_DOMAIN}"
    OriginMapTBL:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.vars.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: Host
            AttributeType: S
        KeySchema:
          - AttributeName: Host
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    OriginRequestProxyRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.vars.ORIGINREQUESTPROXY_ROLE_NAME}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.vars.ORIGINREQUESTPROXY_ROLE_NAME}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource: "arn:aws:logs:*:*:*"
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:ListBucket
                  Resource:
                    - {
                        "Fn::Join":
                          ["", ["arn:aws:s3:::", { Ref: DefaultBucket }]],
                      }
                    - {
                        "Fn::Join":
                          ["", ["arn:aws:s3:::", { Ref: DefaultBucket }, "/*"]],
                      }
                    - "arn:aws:s3:::*"
                - Effect: Allow
                  Action:
                    - dynamodb:GetItem
                    - dynamodb:Query
                    - dynamodb:DescribeStream
                    - dynamodb:GetRecords
                    - dynamodb:GetShardIterator
                    - dynamodb:ListStreams
                  Resource:
                    - "Fn::Join":
                        - ""
                        - - "arn:aws:dynamodb:"
                          - { Ref: "AWS::Region" }
                          - ":"
                          - { Ref: "AWS::AccountId" }
                          - ":table/"
                          - ${self:custom.vars.TABLE_PREFIX}
                    - "Fn::Join":
                        - ""
                        - - "arn:aws:dynamodb:"
                          - { Ref: "AWS::Region" }
                          - ":"
                          - { Ref: "AWS::AccountId" }
                          - ":table/"
                          - ${self:custom.vars.TABLE_PREFIX}
                          - "/index/*"
    OriginRequestRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.vars.ORIGINREQUEST_ROLE_NAME}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.vars.ORIGINREQUEST_ROLE_NAME}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource: "arn:aws:logs:*:*:*"
    OriginResponseRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.vars.ORIGINRESPONSE_ROLE_NAME}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - edgelambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.vars.ORIGINRESPONSE_ROLE_NAME}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource: "arn:aws:logs:*:*:*"
    CodeFreshTriggerRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.vars.STACKNAME}-cfTriggerRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.vars.STACKNAME}-cfTriggerRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:*:*:*
                - Effect: Allow
                  Action:
                    - kms:Decrypt
                  Resource: ${self:custom.vars.SECRETS_KEY_ARN}
    GithubWebhookRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.vars.GITHUB_WEBHOOK_ROLE_NAME}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.vars.GITHUB_WEBHOOK_ROLE_NAME}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:*:*:*"
                - Effect: Allow
                  Action:
                    - cloudformation:DeleteStack
                  Resource:
                    - "arn:aws:cloudformation:*:*:stack/*-rc-*/*"
                    - "arn:aws:cloudformation:*:*:stack/*-feat-*/*"
                - Effect: Allow
                  Action:
                    - cloudformation:DescribeStacks
                    - cloudformation:DescribeAccountLimits
                    - cloudformation:DescribeChangeSet
                    - cloudformation:DescribeStackEvents
                    - cloudformation:DescribeStackInstance
                    - cloudformation:DescribeStackResource
                    - cloudformation:DescribeStackResources
                    - cloudformation:DescribeStackSet
                    - cloudformation:DescribeStackSetOperation
                    - cloudformation:EstimateTemplateCost
                    - cloudformation:GetStackPolicy
                    - cloudformation:GetTemplate
                    - cloudformation:GetTemplateSummary
                    - iam:PassRole
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:DeleteObject
                    - s3:HeadBucket
                    - s3:ListBucketVersions
                    - s3:DeleteObjectVersion
                    - s3:PutBucketVersioning
                  Resource:
                    - "arn:aws:s3:::*-rc-*"
                    - "arn:aws:s3:::*-feat-*"
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:DeleteObject
                  Resource:
                    - "arn:aws:s3:::${self:custom.vars.PROD_DEPLOYMENT_BUCKET}"
                    - "arn:aws:s3:::${self:custom.vars.PROD_DEPLOYMENT_BUCKET}/*"
                - Effect: Allow
                  Action:
                    - sts:AssumeRole
                  Resource: ${self:custom.vars.DEV_GITHUB_WEBHOOK_ROLE_ARN}
    CFProxyEntryRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.vars.CFPROXYENTRY_ROLE_NAME}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                AWS: ${self:custom.vars.AWS_SANDBOX_ACCOUNT_ARN}
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.vars.CFPROXYENTRY_ROLE_NAME}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "arn:aws:logs:*:*:*"
                - Effect: Allow
                  Action:
                    - "iam:PassRole"
                  Resource:
                    - "*"
                - Effect: Allow
                  Action:
                    - dynamodb:*
                  Resource:
                    - "Fn::Join":
                        - ""
                        - - "arn:aws:dynamodb:"
                          - { Ref: "AWS::Region" }
                          - ":"
                          - { Ref: "AWS::AccountId" }
                          - ":table/"
                          - ${self:custom.vars.TABLE_PREFIX}
                    - "Fn::Join":
                        - ""
                        - - "arn:aws:dynamodb:"
                          - { Ref: "AWS::Region" }
                          - ":"
                          - { Ref: "AWS::AccountId" }
                          - ":table/"
                          - ${self:custom.vars.TABLE_PREFIX}
                          - "/index/*"
    DeployerRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.vars.DEPLOYER_ROLE_NAME}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: cloudformation.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.vars.DEPLOYER_ROLE_NAME}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "*"
                  Resource: "*"
    CrossAccountPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: { Ref: CfproxyentryLambdaFunction }
        Principal: ${self:custom.vars.AWS_SANDBOX_ACCOUNT_ARN}
    CloudfrontOAI:
      Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Created for ${self:custom.vars.STACKNAME}
    DefaultBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        AccessControl: Private
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
    BucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket: { Ref: DefaultBucket }
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            Effect: Allow
            Principal:
              AWS:
                - { "Fn::GetAtt": [OriginRequestRole, Arn] }
              CanonicalUser:
                - { "Fn::GetAtt": [CloudfrontOAI, S3CanonicalUserId] }
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - { "Fn::Join": ["", ["arn:aws:s3:::", { Ref: DefaultBucket }]] }
              - {
                  "Fn::Join":
                    ["", ["arn:aws:s3:::", { Ref: DefaultBucket }, "/*"]],
                }
    CDN:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          Aliases:
            - "*.${self:custom.vars.APEX_DOMAIN}"
          ViewerCertificate:
            AcmCertificateArn: { Ref: SSLCert }
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2018
          WebACLId: ${self:custom.vars.WAF}
          Enabled: true
          HttpVersion: http2
          PriceClass: PriceClass_100
          IPV6Enabled: true
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
              Headers:
                - Host
                - CloudFront-Viewer-Country
                - Accept-Language
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            # PathPattern: String
            # SmoothStreaming: Boolean
            TargetOriginId: WebsiteBucketOrigin
            # TrustedSigners:
            #   - String
            ViewerProtocolPolicy: redirect-to-https
          Origins:
            - DomainName: { "Fn::GetAtt": [DefaultBucket, DomainName] }
              Id: WebsiteBucketOrigin
              S3OriginConfig:
                OriginAccessIdentity:
                  {
                    "Fn::Join":
                      [
                        "",
                        [
                          "origin-access-identity/cloudfront/",
                          { Ref: CloudfrontOAI },
                        ],
                      ],
                  }
    DnsRecords:
      Type: "AWS::Route53::RecordSetGroup"
      Properties:
        HostedZoneName: ${self:custom.vars.HOSTED_ZONE}
        Comment: "DNS records associated with ${self:custom.vars.STACKNAME}"
        RecordSets:
          - Name: "*.${self:custom.vars.APEX_DOMAIN}."
            Type: A
            AliasTarget:
              DNSName: { "Fn::GetAtt": [CDN, DomainName] }
              HostedZoneId: Z2FDTNDATAQYW2

  Outputs:
    OriginRequestLambdaARN:
      Description: OriginRequest Lambda ARN
      Value:
        Fn::GetAtt:
          - OriginrequestLambdaFunction
          - Arn
      Export:
        Name: ${self:custom.vars.STACKNAME}-originrequest-lambda-arn
    OriginRequestRoleARN:
      Description: OriginRequest Role ARN
      Value: { "Fn::GetAtt": [OriginRequestRole, Arn] }
      Export:
        Name: ${self:custom.vars.ORIGINREQUEST_ROLE_NAME}-arn
    OriginRequestProxyRoleARN:
      Description: OriginRequestProxy Role ARN
      Value: { "Fn::GetAtt": [OriginRequestProxyRole, Arn] }
      Export:
        Name: ${self:custom.vars.ORIGINREQUESTPROXY_ROLE_NAME}-arn
    OriginResponseLambdaARN:
      Description: OriginResponse Lambda ARN
      Value:
        Fn::GetAtt:
          - OriginresponseLambdaFunction
          - Arn
      Export:
        Name: ${self:custom.vars.STACKNAME}-originresponse-lambda-arn
    OriginMapTBL:
      Description: Proxy DynamoDB Origin Mapping Table
      Value: { Ref: OriginMapTBL }
      Export:
        Name: ${self:custom.vars.TABLE_NAME}
    CloudfrontOAI:
      Description: Proxy CloudFront Origin Access Identity S3CanonicalUserId
      Value: { "Fn::GetAtt": [CloudfrontOAI, S3CanonicalUserId] }
      Export:
        Name: ${self:custom.vars.CLOUDFRONT_OAI_NAME}
    CfProxyentryLambdaARN:
      Description: CFProxyEntry Lambda ARN
      Value:
        Fn::GetAtt:
          - CfproxyentryLambdaFunction
          - Arn
      Export:
        Name: ${self:custom.vars.STACKNAME}-cfproxyentry-lambda-arn
    Domain:
      Description: Stack Proxy Apex Domain
      Value: ${self:custom.vars.APEX_DOMAIN}

plugins:
  - serverless-plugin-epsagon # <-- Must be first
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-git-variables
  - serverless-plugin-cloudfront-lambda-edge

package:
  individually: true
  exclude:
    - "**/*"
```

</details>

<details>
<summary><b><code>vars.yml</b></summary>

```
default: &default
  STAGE: ${opt:stage, "dev"}
  STACKNAME: ${self:service}-${self:custom.vars.STAGE}
  STACK_TAGS:
    SERVICE: ${self:service}
    STAGE: ${self:custom.vars.STAGE}
    GIT_REPOSITORY: ${git:repository}
    GIT_BRANCH: ${self:custom.vars.STAGE}
  TABLE_PREFIX: ${self:custom.vars.STACKNAME}-*
  TABLE_NAME: ${self:custom.vars.STACKNAME}-domainmap
  WAF: { "Fn::ImportValue": "sandbox-wafacl-prod" }
  PROD_DEPLOYMENT_BUCKET: ${cf:NOTTELLING.DeploymentBucket}
  DEV_DEPLOYMENT_BUCKET: ${env:DEV_DEPLOYMENT_BUCKET}
  CLOUDFRONT_OAI_NAME: ${self:custom.vars.STACKNAME}-cloudfrontoai
  AWS_PROD_ACCOUNT_ARN: "arn:aws:iam::NOTTELLING:root"
  AWS_SANDBOX_ACCOUNT_ARN: "arn:aws:iam::NOTTELLING:root"
  ORIGINREQUESTPROXY_ROLE_NAME: ${self:custom.vars.STACKNAME}-originrequestproxy-role
  ORIGINREQUEST_ROLE_NAME: ${self:custom.vars.STACKNAME}-originrequest-role
  ORIGINRESPONSE_ROLE_NAME: ${self:custom.vars.STACKNAME}-originresponse-role
  CFPROXYENTRY_ROLE_NAME: ${self:custom.vars.STACKNAME}-cfproxyentry-role
  DEPLOYER_ROLE_NAME: ${self:custom.vars.STACKNAME}-deployer-role
  PROD_CI_ROLE_ARN: { "Fn::GetAtt": [DeployerRole, Arn] }
  DEV_CI_ROLE_ARN: ${env:DEV_CI_ROLE_ARN}
  DEV_GITHUB_WEBHOOK_ROLE_ARN: ${env:DEV_GITHUB_WEBHOOK_ROLE_ARN}
  GITHUB_API: "https://api.github.com/graphql"
  GITHUB_WEBHOOK_ROLE_NAME: ${self:custom.vars.STACKNAME}-githubwebhookrole
  GITHUB_WEBHOOK_SECRET: ${ssm:stack-proxy-nottelling}
  GITHUB_ACCESS_TOKEN: ${ssm:stack-proxy-nottelling2}
  CODEFRESH_API: https://NOTTELLING/api
  CREATE_API_DOMAIN: false

dev:
  <<: [*default]
  SECRETS_KEY_ARN: arn:aws:kms:us-east-1:NOTTELLING
  ROOT_DOMAIN: NOTTELLING.com
  APEX_DOMAIN: ${self:provider.stage}.${self:custom.vars.ROOT_DOMAIN}
  HOSTED_ZONE: ${self:custom.vars.ROOT_DOMAIN}.
  API_DOMAIN: api.${self:custom.vars.ROOT_DOMAIN}
  SECRETS: NOTTELLING

prod:
  <<: [*default]
  SECRETS_KEY_ARN: arn:aws:kms:us-east-1:NOTTELLING
  ROOT_DOMAIN: NOTELL.com
  APEX_DOMAIN: dev.${self:custom.vars.ROOT_DOMAIN}
  HOSTED_ZONE: ${self:custom.vars.ROOT_DOMAIN}.
  CREATE_API_DOMAIN: true
  API_DOMAIN: api.${self:custom.vars.ROOT_DOMAIN}
  SECRETS: NOTTELLING

```
</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
➜  stack-proxy git:(hotfix-resp) ✗ npm i -g serverless
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
/Users/me/.nvm/versions/node/v14.15.1/bin/sls -> /Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/bin/serverless.js
/Users/me/.nvm/versions/node/v14.15.1/bin/serverless -> /Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/bin/serverless.js

> snappy@6.3.5 install /Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/node_modules/snappy
> prebuild-install || node-gyp rebuild


> protobufjs@6.10.2 postinstall /Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/serverless/node_modules/protobufjs
> node scripts/postinstall


> serverless@2.27.1 postinstall /Users/me/.nvm/versions/node/v14.15.1/lib/node_modules/serverless
> node ./scripts/postinstall.js


   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serverless Framework successfully installed!    │
   │                                                   │
   │   To start your first project run 'serverless'.   │
   │                                                   │
   └───────────────────────────────────────────────────┘

+ serverless@2.27.1
added 663 packages from 485 contributors in 50.776s
➜  stack-proxy git:(hotfix-resp) ✗ serverless -v
Framework Core: 2.27.1
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
➜  stack-proxy git:(hotfix-resp) ✗ serverless help
➜  stack-proxy git:(hotfix-resp) ✗ serverless info
➜  stack-proxy git:(hotfix-resp) ✗ serverless
➜  stack-proxy git:(hotfix-resp) ✗ 
```

</details>

<b>Installed version</b>

```
Framework Core: 2.27.1
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```
