### ISSUE TITLE
Support for lambda authorizers in HTTP API

### ISSUE THREAD

**Issue by devduvan** [serverless/serverless#9018]
### Use case description

I'm creating a lambda authorizer for my HTTP API with cloudformation because AWS has already support lambda authorizers in HTTP apis but when i'm going to try reference in my function on serverless i have the next error: "An error occurred: HttpApiRoutePostCompanies - Invalid authorizer ID specified. Setting the authorization type to JWT requires a valid JWT authorizer. (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: e7d522ce-ff1d-4545-b520-5877a70caa1e; Proxy: null)."

I seen in official doc that for now serverless only support JWT authorizer for HTTP apis but i don't found some issue about this, so i'm creating this issue for track when serverless support the lambda authorizer for HTTP apis.

<summary><code>serverless.yml</code></summary>

```yaml
functions:
  create:
      name: create-test
      handler: src/create-test.handler
      package:
        exclude:
          - ./**
        include:
          - src/create-test.js
      events:
        - httpApi:
            method: POST
            path: /create-test
            authorizer:
              id:
                Ref: MyAuthorizer
resources:
  Resources:
    MyAuthorizer:
      Type: "AWS::ApiGatewayV2::Authorizer"
      Properties:
        Name: "my-authorizer"
        ApiId:
          "Fn::ImportValue": ${self:custom.app.name}-api-id
        AuthorizerType: REQUEST
    AuthorizerUri: arn:aws:apigateway:{region}:lambda:path/2015-03-31/functions/arn:aws:lambda: {region}:{account id}:function:{Function name}/invocations
        IdentitySource:
          - $request.header.Authorization
        AuthorizerPayloadFormatVersion: "2.0"
        EnableSimpleResponses: true

```

<b>Installed version</b>

```
Framework Core: 2.27.1
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

### Proposed solution

It would be nice if support is added for using Lambda Authorizer in HTTP apis
