### ISSUE TITLE
Support explicit null values in serverless.yml without generating a warning

### ISSUE THREAD

**Issue by swisener** [serverless/serverless#9021]
Occasionally, I would like to set a configuration value explicitly to null in serverless.yml. For example, if I would like an AWS Lambda configured with reservedConcurrency in some stages (e.g. production), but not others. Currently, you can accomplish this like so:

```yaml
custom:
  qa: 
    reservedConcurrency: null # Or just omit this key entirely
  prod:
    reservedConcurrency: 10
functions:
  myFunction: 
    handler: someHandler
    reservedConcurrency: ${self:custom.${self:stage}.reservedConcurrency}
```

This currently works, but generates a warning (A valid service attribute to satisfy the declaration 'self:custom.qa.reservedConcurrency' could not be found) in the qa stage, since the value evaluates to null. I'd like to be able to set an attribute to a value that functions as null, but will not generate a warning. One idea is to have an explicit value that will function as null internally, but the variable resolver can view as a resolved value. Then I can use a default value like so:

```yaml
reservedConcurrency: ${self:custom.${self:stage}.reservedConcurrency, EXPLICIT_NULL}
```
