### ISSUE TITLE
Deprecation warnings when using ${file()} with arbitrary file extensions

### ISSUE THREAD

**Issue by ffxsam** [serverless/serverless#9026]
### Use case description

I'm getting deprecation warnings that seem to say in future versions of Serverless, I won't be able to use `${file()}` on arbitrary text-based file types (e.g. .graphql).

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "resources.4.Resources.GraphQLSchema.Properties.Definition": Cannot parse "schema.gql": Unsupported file extension,
              - Cannot resolve variable at "resources.4.Resources.QueryGetFoldersResolver.Properties.RequestMappingTemplate": Cannot parse "getSubscription-req.vtl": Unsupported file extension,
              - Cannot resolve variable at "resources.4.Resources.QueryGetFoldersResolver.Properties.ResponseMappingTemplate": Cannot parse "getSubscription-res.vtl": Unsupported file extension,
              - Cannot resolve variable at "resources.4.Resources.MutationCreateTrackResolver.Properties.RequestMappingTemplate": Cannot parse "updateSubscription-req.vtl": Unsupported file extension,
              - Cannot resolve variable at "resources.4.Resources.MutationCreateTrackResolver.Properties.ResponseMappingTemplate": Cannot parse "updateSubscription-res.vtl": Unsupported file extension
            From a next major it we will be communicated with a thrown error.
```

Example serverless.yml excerpt:

```yaml
  QueryGetSubscriptionResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Query
      FieldName: getSubscription
      DataSourceName: !GetAtt RDSDataSource.Name
      RequestMappingTemplate: ${file(./graphql/resolver-templates/getSubscription-req.vtl)}
      ResponseMappingTemplate: ${file(./graphql/resolver-templates/getSubscription-res.vtl)}
    DependsOn: GraphQLSchema
  MutationUpdateSubscriptionResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      TypeName: Mutation
      FieldName: updateSubscription
      DataSourceName: !GetAtt RDSDataSource.Name
      RequestMappingTemplate: ${file(./graphql/resolver-templates/updateSubscription-req.vtl)}
      ResponseMappingTemplate: ${file(./graphql/resolver-templates/updateSubscription-res.vtl)}
    DependsOn: GraphQLSchema

```

### Proposed solution

Unsure.

```
Framework Core: 2.27.1
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

**Comment by ffxsam** [comment]
This is actually more serious than I thought. It says it's a deprecation warning, but it actually removed all of our AppSync resolvers from our stack!

**Comment by mohdizzy** [comment]
I am seeing this for .yml extensions too. When referencing some local variable imports with `file`, the stack fails with the error above

**Comment by medikoo** [comment]
@ffxsam Thanks for report. Note that this is just a warning (not an error), and should not change in anywa how deployment works for you. If new parser cannot resolve the variable, then old parser handles the configuration in exactly same way as in old versions.

Can you provide more details on why you assume new version removed your AppSync resolvers?

**Comment by medikoo** [comment]
Otherwise, we will add support for plain text file imports to new variables resolver shortly

**Comment by ami000** [comment]
<img width="1096" alt="Screen Shot 2021-03-01 at 3 55 15 PM" src="https://user-images.githubusercontent.com/25586319/109484520-89345480-7aa6-11eb-9fee-e6bf00a89cbc.png">

With the above serverless.yml, I am facing the same error (also screenshotted below)-

<img width="1299" alt="Screenshot_2021-03-01_at_5_55_22_PM" src="https://user-images.githubusercontent.com/25586319/109486244-9d795100-7aa8-11eb-8d59-9cbe9742229c.png">

**Comment by medikoo** [comment]
@ami000 as mentioned above, it's a _warning_ (not an _error_) that doesn't change how deployment is processed (when comparing with older version of a Framework).

One confusing bit about you're input, is that in first screenshot you show that you've set `variablesResolutionMode`, and this setting, will turn this _warning_ to an _error_. While in second screenshot you show output when it's handed as _warning_ (so no `variablesResolutionMode` set)

**Comment by ami000** [comment]
Apologies, please ignore my previous comment-

I have attached my yaml below-

```yaml

service: XXXXX
# app and org for use with dashboard.serverless.com
app: XXXXX
org: XXXXXXX #this is different based on stage. Cannot make dynamic.
#variablesResolutionMode: 20210219
plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-prune-plugin
  # - serverless-plugin-scripts

package:
  excludeDevDependencies: true
  exclude:
    - .github/**
    - .byc_output/**
    - .vsscode/**
    - charts/**
    - devops/**
    - patches/**
    - src/**
    - tests/**
    - tracker/**
    - .cfignore
    - .editorconfig
    - .env
    - .env1
    - .gitignore
    - debug.log
    - jest.config.js
    - README.md
    - test.env
    - tsconfig.json
    - tslint.json
    - tsoa.json

custom:
  accountId: ${file(./serverless-config.js):getAccountId}
  prune:
    automatic: true
    number: 3

```

The above yaml resulted in the below error-
<img width="1195" alt="Screen Shot 2021-03-01 at 4 06 25 PM" src="https://user-images.githubusercontent.com/25586319/109487347-1a58fa80-7aaa-11eb-834b-32f1a5e63565.png">


And so I set the `variablesResolutionMode: 20210219`.

Which then resulted in the main issue.
