### ISSUE TITLE
Deployment fails when useDotenv references undefined environment variable in v2.28.0

### ISSUE THREAD

**Issue by emibelli** [serverless/serverless#9027]
Command `serverless deploy` fails when `useDotenv` field in `serverless.yml` references undefined/unexisting environment variable `SLS_USE_DOTENV` after updating Serverless Framework to v2.28.0 (issue did not occur using Serverless Framework v2.27.1).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-aws-nodejs-test

useDotenv: ${env:SLS_USE_DOTENV, true}

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - ${env:AWS_BUCKET_NAME}
        - Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - ${env:AWS_BUCKET_NAME}
              - "/*"
  vpc:
    securityGroupIds:
      Fn::Split:
        - ","
        - ${env:AWS_SECURITY_GROUP_IDS}
    subnetIds:
      Fn::Split:
        - ","
        - ${env:AWS_SUBNET_IDS}
  environment:
    NODE_ENV: ${env:NODE_ENV}
    AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: GET

```

</details>

<details>
<summary><b><code>SLS_DEBUG=* serverless deploy</code> output</b></summary>

```
emibelli@ODIN:~/serverless-aws-nodejs-test$ SLS_DEBUG=* serverless deploy

  Serverless Error ---------------------------------------

  ServerlessError: Cannot resolve serverless.yml: "useDotenv" is not accessible (configured behind variables which cannot be resolved at this stage)
      at /home/emibelli/.nvm/versions/node/v14.15.0/lib/node_modules/serverless/scripts/serverless.js:187:17

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.0
     Framework Version:         2.28.0
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.1

```

</details>

<b>Installed version</b>

```
emibelli@ODIN:~/serverless-aws-nodejs-test$ serverless --version
Framework Core: 2.28.0
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```
