### ISSUE TITLE
Unable to configure STAGE tag 

### ISSUE THREAD

**Issue by jamie-unmind** [serverless/serverless#9031]
Serverless appears to be adding a `STAGE` tag to my CFn stack by default. Is it possible to configure this to be lowercased to `stage`?

<img width="1270" alt="Screenshot 2021-03-01 at 14 31 30" src="https://user-images.githubusercontent.com/75371176/109511421-eb875800-7a9a-11eb-940a-2e035635caa8.png">

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)]+?)}" # Use this for allowing CloudFormation Pseudo-Parameters in your serverless.yml -- e.g. ${AWS::Region}. All other Serverless variables work as usual.
  region: eu-west-1
  runtime: nodejs12.x  
  stackTags:
    aws_region: !Sub ${AWS::Region}
    aws_account_id: !Sub ${AWS::AccountId}    
  environment:
    STAGE: ${self:provider.stage}

resources:
  - Description: ${file(./package.json):description}
  - ${file(cloudformation-resources/iam.yml)}
  - ${file(cloudformation-resources/security-groups.yml)}

functions:
  myFunc:
    handler: ./src/handlers/myFunc.default
    role: MyFuncRole   
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
sls deploy --stage dev
```

</details>

<b>Installed version</b>

```
Framework Core: 1.83.0 (local)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
