### ISSUE TITLE
Logical not of boolean value of variables in serverless yml file

### ISSUE THREAD

**Issue by s1mrankaur** [serverless/serverless#9037]
I am looking to do something like:
    thundra_agent_lambda_debugger_enable: !Not ${self:custom.thundra.disable}
    thundra_lambda_publish_cloudwatch_enable: !Not ${self:custom.thundra.disable}

Surprising that it does not seem to be an option
<!--

**Comment by pgrzesik** [comment]
Hello @s1mrankaur - thanks for reporting. Could you please share a bit more about what are you trying to achieve? In the above example, is there a reason as to why you cannot flip the logic on `custom.thundra` level and use `enable` instead of `disable`? Notation as you're presenting with `!Not` could be viable on CloudFormation level, but it seems like it's not the case in your example.

**Comment by jcuozzo** [comment]
I just ran into this and was also surprised there's no option.  Possible workaround is:
```yml
custom:
  negate:
    true: false
    false: true
  mySetting: true
  myOtherSetting: ${self:custom.negate.${self:custom.mySetting}}
```
