### ISSUE TITLE
provider.apiGateway.shouldStartNameWithService as true does not works for websocket API

### ISSUE THREAD

**Issue by onhate** [serverless/serverless#9038]
Setting provider.apiGateway.shouldStartNameWithService to true does not renames the API for Websocket lambdas.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: xxx-xxx

configValidationMode: off
frameworkVersion: ^2.28.0

provider:
  name: aws
  apiGateway:
    shouldStartNameWithService: true

functions:
  wsGraphqlHandler:
    handler: src/ws-handler.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
```

</details>

I have both REST and Websocket on same serverless deployment and it works for REST but not for Websockets

![image](https://user-images.githubusercontent.com/980905/109584160-cff27080-7adf-11eb-9395-a393324f79aa.png)
