### ISSUE TITLE
provider.iam.role configuration validation warns incorrectly

### ISSUE THREAD

**Issue by DaveLo** [serverless/serverless#9044]
If I define a provider role like so:
```yaml
provider:
  iam:
    role:
      managedPolicies:
        - !ImportValue CustomerTableWrite
        - !Ref CustomerTableRead
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/PutEventBridgeEventsPolicy
```
I receive the following warning
```
Configuration warning:
   at 'provider.iam.role.managedPolicies[0]': should be string
   at 'provider.iam.role.managedPolicies[1]': should be string
   at 'provider.iam.role.managedPolicies[2]': should be string
```
but this is definitely a working configuration which attaches the referenced policies, and according to the docs a [valid one](https://www.serverless.com/framework/docs/providers/aws/guide/iam/).

>Alongside provider.iam.role.statements managed policies can also be added to this service-wide Role, define managed policies in provider.iam.role.managedPolicies. These will also be merged into the generated IAM Role so you can use Join, Ref or any other CloudFormation method or feature here too.

<details>
<summary><code>serverless.yml</code></summary>

Created a minimal reproduction with a single internal reference.

```yaml
service: api
frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs14.x
  region: "us-east-1"
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iam:
    role:
      managedPolicies:
        - !Ref EBPutEvents

functions:
  helloFunc:
    handler: handler.hello
    timeout: 20

resources:
  Resources:
    EBPutEvents:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: "*"

```

</details>

<details>
<summary><b><code>⚠️⚠️ sls deploy OR sls package</code> output</b></summary>

I ran this with debug and not, and there isn't a difference in the relevant configuration warning so I've included the shorter deploy log.

```
Serverless: Configuration warning at 'provider.iam.role.managedPolicies[0]': should be string
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service api.zip file to S3 (392 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..................
Serverless: Stack update finished...
Service Information
service: api
stage: dev
region: us-east-1
stack: api-dev
resources: 7
api keys:
  None
endpoints:
  None
functions:
  helloFunc: api-dev-helloFunc
layers:
  None
```

</details>

<b>Installed version</b>

```
Framework Core: 2.28.1
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

**Comment by pgrzesik** [comment]
Thanks for reporting @DaveLo :bow: I believe in this case it's an issue with our schema validation, which does not accept CF intrinsic functions and instead expects strings that start with `arn`. I don't see a reason as to why we couldn't support CF functions as well.

We'd be more than happy to accept a PR that relaxes schema to also allow CF intrinsic functions. :partying_face:

**Comment by ktardif** [comment]
Somewhat related, the old deprecated `provider.role` let you specify a custom resource name from the `resources.Resources` block, however `provider.iam.role` no longer allows this and just results in a `Configuration error at 'provider.iam.role': should match pattern "^arn:"` error. This prevents just simply renaming the property as outlined in the [documentation](https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS). If this behavior is intentional it would be best to update the documentation to mention it.

**Comment by pgrzesik** [comment]
@ktardif thanks for reporting - could you provide an example of exact configuration that was working previously that is no longer working for you in that case? I believe it's a mistake in new approach as we didn't intend to change the possible values.

**Comment by DaveLo** [comment]
@pgrzesik , looking lightly at this (not super familiar with the internals)

https://github.com/serverless/serverless/blob/42a1cdb6f1b4ca90e9e7f43852672897cb9ec1f9/lib/plugins/aws/provider.js#L843

would the solve here be to update this from `'#/definitions/awsArnString'` to `'#/definitions/awsArn'`?

**Comment by ktardif** [comment]
@pgrzesik Stripping out unrelated items:

```yaml
provider:
  name: aws

  #deprecated variant
  #works as expected; properly references resources.Resources.someLambdaRole
  role: someLambdaRole

  #errors with:
  #'provider.iam.role': should match pattern "^arn:"
  provider:
    iam:
      role: someLambdaRole

resources:
  Resources:
    someLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: SomeLambdaRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - edgelambda.amazonaws.com
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: BasicLambdaExecution
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
```

File was originally written for serverless 1.57. `provider.role` still works properly on 2.x but it's marked as deprecated, however like I mentioned previously `provider.iam.role` doesn't accept the above value.
