### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by ariel-frischer** [serverless/serverless#9073]
`serverless deploy` is running into global config errors and Error: EMFILE: too many open files. I've tried uninstalling and reinstalling global serverless command as well as restarting my computer. It used to deploy until I tried to upgrade my global serverless with `npm i -g serverless/serverless`.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: aws-node-puppeteer
app: initiate-web
org: arielf

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

plugins:
  - serverless-offline
  - serverless-plugin-chrome

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - layer/**
    - tmp/**
    - .vscode/*
    - yarn.*
    - .eslintrc.json
    - .prettierrc

functions:
  urlToVideo:
    handler: handler.urlToVideo
    memorySize: 3000
    timeout: 30
    environment:
      FFMPEG_PATH: /opt/ffmpeg/ffmpeg
      FFPROBE_PATH: /opt/ffmpeg/ffprobe
    events:
      - http:
          path: /
          method: get
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Injecting Headless Chrome...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: User Configuration warning: Cannot resolve global config file: C:\Users\Ariel\.serverlessrc 
Error: EMFILE: too many open files, open 'C:\Users\Ariel\.serverlessrc'
Serverless: Your previous global config was renamed to C:\Users\Ariel\.serverlessrc.bak for debugging. Default global config will be recreated under C:\Users\Ariel\.serverlessrc.

  Serverless Error ---------------------------------------

  Cannot read file node_modules\moment\src\locale\th.js due to: EMFILE: too many open files, open 'C:\Users\Ariel\sls-node-puppeteer\.build\node_modules\moment\src\locale\th.js'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.19.0
     Framework Version:         2.28.6
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.2```
```
</details>

<b>Installed version</b>

```
Framework Core: 2.28.6
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2
```
<details>

<summary><b><code>package.json</code> dependencies</b></summary>

```
  "dependencies": {
    "chrome-launcher": "^0.13.4",
    "puppeteer": "^2.1.0",
    "serverless-offline": "^6.8.0",
    "serverless-plugin-chrome": "^1.0.0-55.3",
    "timesnap-core": "^0.2.0"
  },
  "devDependencies": {
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "prettier": "^2.2.1",
    "prettier-eslint": "^12.0.0"
  }
```
</details>
