### ISSUE TITLE
Unable to deploy app, that was previously deployed.

### ISSUE THREAD

**Issue by muhammadfaizan** [serverless/serverless#9075]
I was Trying to deploy app, but it was not uploading, it just got stuck and stayed stuck on uploading state. like this
![image](https://user-images.githubusercontent.com/5428176/109942175-c17da200-7cf5-11eb-8a52-a85736630b99.png)

After updating serverless I am receiving new kind of error:
⚠️⚠️ REPLACE WITH DESCRIPTION

<details>
<summary><code>serverless.yml</code></summary>

```yaml

service: xxxxxxxxx
provider:
  name: aws
  stage: ${opt:stage, 'staging'}
  region: eu-central-1
  runtime: nodejs12.x
  timeout: 30
  environment:
    ....
functions:
  app: # Function name
    handler: index.handler 
    events: 
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*' 
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Pragma
            allowCredentials: false
  cron-cs: 
    handler: cron/index.func1
    events: 
      - schedule: rate(5 minutes)
  cron-cu: 
    handler: cron/index.func2
    events: 
      - schedule: rate(2 minutes)
  cron-ct:
    handler: cron/index.func3
    events: 
      - schedule: rate(600 minutes)
```

</details>

<details>
<summary><b><code>$ serverless deploy -s production</code> output</b></summary>

```


Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.28.6")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: User Configuration warning: Cannot resolve global config file: C:\Users\Muhammad Faizan\.serverlessrc
Error: EMFILE: too many open files, open 'C:\Users\Muhammad Faizan\.serverlessrc'
Serverless: Your previous global config was renamed to C:\Users\Muhammad Faizan\.serverlessrc.bak for debugging. Default global config will be recreated under C:\Users\Muhammad Faizan\.serverlessrc.
Serverless: Error: EMFILE: too many open files, open 'C:\Users\Muhammad Faizan\.serverlessrc.1685763462'
    at Object.openSync (fs.js:440:3)
    at Function.writeFileSync [as sync] (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\utils\node_modules\write-file-atomic\index.js:205:13)    
    at storeConfig (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\utils\config.js:50:21)
    at createDefaultGlobalConfig (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\utils\config.js:72:3)
    at getGlobalConfig (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\utils\config.js:129:10)
    at getConfig (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\utils\config.js:134:24)
    at Object.get (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\node_modules\@serverless\utils\config.js:183:18)
    at module.exports (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\lib\utils\analytics\generatePayload.js:82:45)
    at Object.before:deploy:deploy [as hook] (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy.js:123:27)
    at PluginManager.invoke (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:502:9)
    at PluginManager.run (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:541:5)
    at Serverless.run (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:267:5)
    at C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\scripts\serverless.js:222:7
Serverless: Unable to store serverless config: C:\Users\Muhammad Faizan\.serverlessrc due to EMFILE error
 
  Serverless Error ---------------------------------------

  ServerlessError: Cannot read file node_modules\mongoose\lib\helpers\symbols.js due to: EMFILE: too many open files, open 'd:\Workspace\Timify\Products\timify-video-calls-backend\node_modules\mongoose\lib\helpers\symbols.js'
      at Package.getFileContentAndStat (C:\Users\Muhammad Faizan\AppData\Roaming\npm\node_modules\serverless\lib\plugins\package\lib\zipService.js:126:13)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.14.0
     Framework Version:         2.28.6
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.2

```

</details>

<b>Installed version</b>

```
Framework Core: 2.28.6
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2

```
