### ISSUE TITLE
The JSON schema for resourcePolicy does not allow account numbers

### ISSUE THREAD

**Issue by blue-urban-sky** [serverless/serverless#9077]
### The JSON schema for resourcePolicy does not allow account numbers

A plain account number or list of account numbers should be a valid input to the`provider.apiGateway.resourcePolicy.Principal.AWS` config ([Docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html)) it is currently expecting `arn:aws`

So this:
```yaml

    resourcePolicy:
      - Effect: Allow
        Principal:
          AWS: 
           - 123456789012
           - 987654321098
```
Causes this:

```
Serverless: Configuration warning:
Serverless:   at 'provider.apiGateway.resourcePolicy[0].Principal.AWS[0]': unsupported configuration format
Serverless:   at 'provider.apiGateway.resourcePolicy[0].Principal.AWS[1]': unsupported configuration format
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml

service: test

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal:
          AWS: 
           - 123456789012
           - 987654321098
        Action: execute-api:Invoke
        Resource:
          - arn:aws:execute-api:/*/*/*

functions:
  test:
    handler: rest_api/evaluate/post/handler.handle
    events:
      - http:
          path: /test
          method: post
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'provider.apiGateway.resourcePolicy[0].Principal.AWS[0]': unsupported configuration format
Serverless:   at 'provider.apiGateway.resourcePolicy[0].Principal.AWS[1]': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.14.1
     Framework Version:         2.28.6
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.2
```

</details>

<b>Installed version</b>

```
Framework Core: 2.28.7 (local)
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2

```
