### ISSUE TITLE
Incorrect configuration warning for apiKeys object

### ISSUE THREAD

**Issue by lyndoh** [serverless/serverless#9080]
There appears to be a mismatch between the config validation and the implementation for aws api gateway apiKeys where multiple usage plans are allowed.
A configuraton warning like:

> Configuration warning at 'provider.apiGateway.apiKeys[0].nolimit[0]': should be string

is displayed when an apiKey object is configured where the "multiple usage plan" format is used (see serverless.yml). However the CFT compiles with the configured values and deploys successfully as expected. 
CFT will contain valid/expected output along the lines of:
```
"ApiGatewayApiKeyNolimit1": {
      "Type": "AWS::ApiGateway::ApiKey",
      "Properties": {
        "Enabled": true,
        "Description": "Key for unlimited API access",
```
Happy to PR a fix to the config validation schema.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: blah
  region: ap-southeast-2
  profile: ${env:AWS_PROFILE}
  endpointType: REGIONAL
  lambdaHashingVersion: 20201221 # will become default in serverless 3.0
  apiGateway:
    shouldStartNameWithService: true
    apiKeys:
      - nolimit:
          - description: Key for unlimited API access
    usagePlan:
      - nolimit:
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
Serverless: Configuration warning at 'provider.apiGateway.apiKeys[0].nolimit[0]': should be string
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.28.7 (local)
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2
```
