### ISSUE TITLE
Deprecation warning: Resolved a JS function not confirmed to work with a new parser, falling back to old resolver

### ISSUE THREAD

**Issue by robjohnston-iw** [serverless/serverless#9081]
Serverless Javascript function variables result in a deprecation warning being logged:
`Deprecation warning: Resolved a JS function not confirmed to work with a new parser, falling back to old resolver`

The current resolver does successfully invoke the function and resolve the variable. The function definition matches the required format for the new resolver as described here: https://www.serverless.com/framework/docs/providers/aws/guide/variables#exporting-a-function

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: function-example
frameworkVersion: '2'

custom:
  functionResult: ${file(./function.js)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    environment:
      VARIABLE: ${self:custom.functionResult}
```

</details>

<details>
<summary><code>function.js</code></summary>

```js
module.exports = async ({ options, resolveConfigurationProperty }) => {
    return 'function-output';
}
```

</details>

The problem occurs when using the `serverless deploy` command, however with the above example the issue is most easily demonstrated using the `serverless print` command.

<details>
<summary><b><code>serverless print</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "custom.functionResult": Cannot parse "function.js": Resolved a JS function not confirmed to work with a new parser, falling back to old resolver
            From a next major it we will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210219" in your service config, to adapt to this behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
service:
  name: function-example
frameworkVersion: '2'
custom:
  functionResult: function-output
provider:
  stage: dev
  region: us-east-1
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  versionFunctions: true
  variableSyntax: \${([^{}:]+?(?:\(|:)(?:[^:{}][^{}]*?)?)}
functions:
  hello:
    handler: handler.hello
    environment:
      VARIABLE: function-output
    events: []
    name: function-example-dev-hello
```

The deprecation warning is output, however the current resolver has correctly set `functions.hello.environment.VARIABLE` to the return value of the function: `function-output`.

</details>

<b>Installed version</b>

```
Framework Core: 2.28.7
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2
```
