### ISSUE TITLE
Allow configuration of ECR repository encryption

### ISSUE THREAD

**Issue by jaikdean** [serverless/serverless#9083]
### Use case description

When using Docker images in Lambda, Serverless automatically creates an ECR repository using the default encryption settings, meaning it must be manually managed to use a customer-managed KMS key for encryption.

### Proposed solution

Add optional configuration of a customer-managed KMS key for the ECR repository through `serverless.yml`.

**Comment by pgrzesik** [comment]
Hello @jaikdean, thanks for reporting - that totally makes sense - what do you think would be the best place to configure it?

**Comment by jaikdean** [comment]
I'm not sure what standards there are and what's used in similar cases elsewhere,

*Existing behaviour using default encryption configuration*

```yaml
provider:
  ecr:
    encryption:
      kms: false
```

*Using KMS with the default key*

```yaml
provider:
  ecr:
    encryption:
      kms: true
```

*Using KMS with a specified key*

```yaml
provider:
  ecr:
    encryption:
      kms: true
      kmsKeyArn: "arn:aws:kms:eu-west-1:874356678234:key/942c9221-7d2c-493b-bc34-7cf2c0378e46"
```

**Comment by pgrzesik** [comment]
Thanks for the proposal @jaikdean - from what I see there are three options:
- using AES256 - it's default
- using KMS with default CMK
- using KMS with provided CKM

I think we might consider skipping `encryption` nesting as I don't see any additional encryption-related settings for ECR repos available, which gives us the following options

```
provider:
  ecr:
    kmsKeyArn: 'default' (to use KMS with default key)
    kmsKeyArn: 'arn:xxx' (to use KMS with provided key)
```

Alternatively, we could go with

```
provider:
  ecr:
    encryption:
      type: kms
      kmsKeyArn: 'arn:xxx' (to use KMS with provided key)
```

None of the above are necessarily "clean" solutions - @medikoo - what is your opinion on the above? What do you think @jaikdean ?

**Comment by medikoo** [comment]
@pgrzesik @jaikdean how about:

```yaml
provider:
  ecr:
    kmsEncryption: true # using KMS with default key
    kmsEncryption:
      arn: 'arn:xxx' # using KMS with provided key
```

We follow such convention in case of some other settings, Internally `true` should be treated as`{}` and lack of `arn` property on `kmsEncryption` should trigger setup with default key
