### ISSUE TITLE
When using the aws provider, provider.iam.role has different semantics than provider.role

### ISSUE THREAD

**Issue by ktardif** [serverless/serverless#9090]
The deprecated `provider.role` let you specify a custom resource name from the `resources.Resources` block, however `provider.iam.role` no longer allows this and just results in a `Configuration error at 'provider.iam.role': should match pattern "^arn:"` error. This prevents just simply renaming the property as outlined in the [documentation](https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS).

File was originally written for serverless 1.57. `provider.role` still works as expected on 2.x but it's marked as deprecated, however `provider.iam.role` doesn't accept the same value.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws

  #deprecated variant
  #works as expected; properly references resources.Resources.someLambdaRole
  role: someLambdaRole

  #errors with:
  #'provider.iam.role': should match pattern "^arn:"
  provider:
    iam:
      role: someLambdaRole

resources:
  Resources:
    someLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: SomeLambdaRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - edgelambda.amazonaws.com
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: BasicLambdaExecution
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
```

</details>

<details>
<summary><b><code>sls deploy -v --stage=dev</code> output</b></summary>

```
  Serverless Error ---------------------------------------

  Configuration error at 'provider.iam.role': should match pattern "^arn:"

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.28.7 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.2
```

</details>

<b>Installed version</b>

```
Framework Core: 2.28.7 (local)
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2
```
