### ISSUE TITLE
Support for vtl files is broken

### ISSUE THREAD

**Issue by chuckthepiranha** [serverless/serverless#9096]
Support for vtl files is broken. In lib/configuration/read.js, there is a switch case that excludes vtl files. This seems to have come from an update in January. The default case is: 
```js
default:
       throw new ServerlessError(
         `Cannot parse "${path.basename(configurationPath)}": Usupported file extension`,
         'UNSUPPORTED_CONFIGURATION_TYPE'
       );
   }
```
This is clearly a bug seeing at there used to be support for vtl files and it works if I paste the template directly into the serverless file. However, this is a pain seeing as I would have to paste a template that I use in several places under every function that uses it.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
events:
      - http:
          path: outbound-mms/{userId}
          method: post
          integration: lambda
          request:
            parameters:
              paths:
                userId: true
            template:
              application/x-www-form-urlencoded: ${file(velocity-language-templates/x-www-form-urlencoded.vtl)}
```

</details>

<details>
<summary><b><code>Deprecation warning: Variables resolver reports following resolution errors:</code>output</b></summary>

```
 - Cannot resolve variable at "custom.apiGatewayServiceProxies.0.http.request.template.application/x-www-form-urlencoded": Cannot parse "x-www-form-urlencoded.vtl": Unsupported file extension
```

</details>

<b>Installed version</b>

```
Framework Core: 2.21.1 (local)
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.1
```
