### ISSUE TITLE
devDependencies aren’t excluded with npm 7

### ISSUE THREAD

**Issue by birsi** [serverless/serverless#9101]
With `npm 7.6.2`, `serverless` fails to exclude `devDependencies` from `package.json`.

Directly relating to: https://github.com/serverless/serverless/issues/8500

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-starter

provider:
  name: aws
  runtime: nodejs4.3

functions:
  single:
    handler: single.handler
    events:
      - http:
          path: single
          method: get
      - http:
          path: single
          method: post
  multiCreate:
    handler: multiCreate.handler
    events:
      - http:
          path: multi/create
          method: get
  multiShow:
    handler: multiShow.handler
    events:
      - http:
          path: multi/show/{id}
          method: get
```

</details>

<details>
<summary>Steps to reproduce</summary>

Incorrect behaviour with `npm 7.6.2` including full `devDependencies` in `node_modules` with `185M` 

```
# Clone the official starter
git clone https://github.com/serverless/serverless-starter
cd serverless-starter

# Switch to Node 15 which comes with npm 7 (using https://github.com/tj/n)
sudo n 15
npm --version
# → 7.0.8

# Add a devDependency
npm i --save-dev serverless
npx serverless version
# → Framework Core: 2.11.1 (local)
# → Plugin: 4.1.2
# → SDK: 2.3.2
# → Components: 3.3.0

# Package the function
npx serverless package
du -h .serverless/serverless-starter.zip
# → 37M	.serverless/serverless-starter.zip

du -h .serverless/serverless-starter/node_modules
# → 185M node_modules
```
</details>

<b>Installed version</b>

```
Framework Core: 2.29.0 (local)
Plugin: 4.5.0
SDK: 4.2.0
Components: 3.7.3

nodejs: 14.16.0
npm: 7.6.2

System Version: macOS 11.2.2 (20D80)
Kernel Version: Darwin 20.3.0
```
