### ISSUE TITLE
resolveConfigurationProperty cannot resolve variables

### ISSUE THREAD

**Issue by Ganitzsh** [serverless/serverless#9113]
`resolveConfigurationProperty` trhows an error when resolving a property containing variables. I tried with simple values and it works.

<details>

<summary>
<code>serverless.yml</code>
</summary>

```yaml
service: pop-cloud-functions
variablesResolutionMode: 20210219
useDotenv: true

provider:
  name: google
  runtime: nodejs12
  region: ${env:GC_REGION}
  project: ${env:GC_PROJECT_ID}

plugins:
  - serverless-google-cloudfunctions
  - serverless-dotenv-plugin # I need it too

custom:
  topicPrefix: projects/${self:provider.project}/topics/${env:GC_TOPIC_PREFIX}
  vpcConnector: ${env:GC_VPC_CONNECTOR, ''}
  vpcConnectorPath: projects/${env:GC_PROJECT_ID}/locations/${env:GC_REGION}/connectors/${self:custom.vpcConnector}

functions: ${file(./generator.js)}
```

</details>

<details>
<summary><b><code>generator.js</code></summary>

```js
module.exports = async ({ resolveConfigurationProperty }) => {
  console.log(await resolveConfigurationProperty(['custom']));
  return {};
}
```
</details>

<details>
<summary><b><code>sls deploy -v</code> output</b></summary>

```
Serverless Error ----------------------------------------

  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "functions": Cannot resolve "generator.js": Returned JS function errored with: ServerlessError: Cannot resolve variable
      at /opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:314:15
      at async Promise.all (index 0)
      at async VariablesResolver.resolveDependentProperty (/opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:306:5)
      at async module.exports (/Users/ganitzsh/Dev/popwork/pop-cloud-functions/dist/generator.js:17:16)
      at async /opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/sources/file.js:116:22
      at async Object.resolve (/opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/sources/file.js:53:21)
      at async VariablesResolver.Object.defineProperties.memoizeMethods.resolveSource.d.normalizer.type.type (/opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:435:24)
      at async /opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:214:20
      at async VariablesResolver.resolveVariableSource (/opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:212:9)
      at async VariablesResolver.resolveVariable (/opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:128:24)
      at async /opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:60:9
      at async Promise.all (index 0)
      at async VariablesResolver.resolveVariables (/opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:54:5)
      at async VariablesResolver.self (/opt/homebrew/lib/node_modules/serverless/lib/configuration/variables/resolve.js:334:9)
      at async Promise.all (index 6)
      at async /opt/homebrew/lib/node_modules/serverless/scripts/serverless.js:122:11

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.11.0
     Framework Version:         2.29.0
     Plugin Version:            4.5.0
     SDK Version:               n/a
     Components Version:        3.7.3
```

</details>

<b>Installed version</b>

```
Framework Core: 2.29.0
Plugin: 4.5.0
SDK: 4.2.0
Components: 3.7.3
```

The `.env` file contains all the variables, and it was working when using the old way. The only update I did was to add the
