### ISSUE TITLE
AWS provider credentials not found. when stack spend some time.

### ISSUE THREAD

**Issue by jolivaSan** [serverless/serverless#9114]
While checking the stack status serverles sometime loose the credentials, we are using a EC2 runners with a profile that allow us execute serverless in the same AWS account, work perfectly but sometime when the stack spend some time serverless return a auth error.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: proxy-lambda

plugins:
  modules:
    - serverless-associate-waf
    - serverless-plugin-canary-deployments

custom:
  associateWaf:
    name: basic-default-waf-tf-whitelist
    version: V2

provider:
  name: aws
  runtime: nodejs12.x
  stage: pro
  region: eu-west-2
  timeout: 30
  deploymentBucket:
    name: tf-aws-payments-eu-west-2-pro
  vpc:
    securityGroupIds:
      - sg-01f7a4b592260ed66
    subnetIds:
      - subnet-056cad46b299b846c
      - subnet-08f006acfb8974afc
      - subnet-08f006acfb8974afc
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi:
      fullExecutionData: false
      format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller": "$context.identity.caller", "user": "$context.identity.user", "requestTime": "$context.requestTime", "httpMethod": "$context.httpMethod", "resourcePath": "$context.resourcePath", "status": "$context.status", "protocol": "$context.protocol", "responseLength": "$context.responseLength"}'
  deploymentSettings:
    alias: Live
    type: Canary10Percent10Minutes
    stages:
      - dev
      - staging
      - pro

functions:
  proxy:
    handler: index.doProxy
    events:
      - http:
          path: introspect-proxy
          method: post

```

</details>

<details>
<summary><b><code>sls deploy --stage pro</code> output</b></summary>

```
Serverless: [AWS cloudformation 200 1.131s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
Serverless: [AWS cloudformation 200 1.294s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
Serverless: [AWS cloudformation 200 1.186s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
Serverless: [AWS cloudformation 200 1.119s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
Serverless: [AWS cloudformation 200 1.108s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
Serverless: [AWS cloudformation 200 1.176s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
Serverless: [AWS cloudformation 200 1.185s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
Serverless: [AWS cloudformation undefined 2.015s 0 retries] describeStackEvents(***
  StackName: 'arn:aws:cloudformation:eu-west-2:141082945919:stack/payments-initiation-staging/586ed410-6bab-11eb-9ed1-027695c7d5b2'
***)
 
  Serverless Error ---------------------------------------
 
  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
      at /__w/pisp-payments-initiation-slz/pisp-payments-initiation-slz/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:105:21
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.20.2
     Framework Version:         2.27.1 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.19.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```
