### ISSUE TITLE
Provide plugin specific options in plugins section

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9116]
### Use case description

Idea originally proposed by @DavidWells at https://github.com/serverless/serverless/issues/9100#issuecomment-796442323

Instead of grouping plugin specific options at `custom` section as:

```yaml
custom:
  pluginWithConfig:
    someProp: 1
    someProp: 2
```

Group them directly in `plugins` section:

```yaml
plugins:
  - plugin-without-config
  - path: plugin-with-config
    config:
      someProp: 1
      someProp: 2
```

Alternatively we may explore switching from _array_ form to _object_ notation (technically both forms could remain to be supported)

```yaml
plugins:
  plugin-without-config: true
  plugin-with-config:
    someProp: 1
    someProp: 2
```

### Proposed solution

I think it'll be more convenient to introduce it on grounds on v3, once we drop completely currently deprecated plugins notation with https://github.com/serverless/serverless/issues/7909
