### ISSUE TITLE
AWS provider credentials not found with 2.30.0

### ISSUE THREAD

**Issue by Quicksaver** [serverless/serverless#9119]
Upgrading from 2.29.0 to 2.30.0 breaks deployments with
```
 Serverless Error ----------------------------------------

  AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
```

Provider access is set via dashboard. I even created a new one (which also works with 2.29.0). It looks like it finds it according to the output, but doesn't use it?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: myorg
app: myapp
service: myservice

frameworkVersion: ">=2.2.0"

useDotenv: true

package:
  individually: true
  exclude:
    - .env
    - .env.dist
    - .eslintrc.json
    - .gitignore
    - yarn.lock

custom:
  STAGE: ${opt:stage, env:STAGE, self:provider.stage}
  lambdaRole: LambdaRole-${self:custom.STAGE}

provider:
  name: aws
  apiGateway:
    shouldStartNameWithService: true
  environment:
    STAGE: ${self:custom.STAGE} # Override the one in .env if specified through opt
  iam:
    role: LambdaRole
  layers:
    - { Ref: BaseLambdaLayer }
  # Region is being passed through to the command as an argument,
  # due to a bug that apparently (to me) only happens in Node.js 12;
  # see https://github.com/serverless/serverless/issues/4251
  region: ${env:AWS_REGION}
  runtime: nodejs12.x
  versionFunctions: false

functions:

resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: ${self:custom.lambdaRole}
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
          - arn:aws:iam::aws:policy/AWSLambdaExecute
          - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                  - "sts:AssumeRole"

```

</details>

<details>
<summary><b><code>serverless deploy --stage qa --region us-east-1</code> output</b></summary>

```
.env | cut -d '=' -f2))
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Using provider credentials, configured via dashboard: https://app.serverless.com/myorg/apps/myapp/myservice/qa/us-east-1/providers
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Publication to Serverless Dashboard errored with:
            AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.

 Serverless Error ----------------------------------------

  ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
      at /Users/me/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/lib/aws/request.js:193:31
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From previous event:
      at AwsDeploy.createStack (/Users/me/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/lib/plugins/aws/deploy/lib/createStack.js:73:8)
      at processImmediate (internal/timers.js:456:21)
  From previous event:
      at Object.aws:deploy:deploy:createStack [as hook] (/Users/me/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:99:73)
      at PluginManager.invoke (/Users/me/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/lib/classes/PluginManager.js:541:20)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async PluginManager.spawn (/Users/me/.nvm/versions/node/v12.18.3/lib/node_modules/serverless/lib/classes/PluginManager.js:563:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.3
     Framework Version:         2.30.0
     Plugin Version:            4.5.0
     SDK Version:               4.2.0
     Components Version:        3.7.3

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

<b>Installed version</b>

```
$ serverless --version
Framework Core: 2.30.0
Plugin: 4.5.0
SDK: 4.2.0
Components: 3.7.3
```
