### ISSUE TITLE
Improve feedback to user deploying template with errors

### ISSUE THREAD

**Issue by john-aws** [serverless/serverless#9130]
### Use case description

Improve feedback to user deploying template with errors

It's common, in fact probable, that sls users will attempt to deploy serverless templates that have bugs in them. The `sls deploy` step is not very forgiving of common user errors and does not provide meaningful help to users to identify their mistakes. This leads to frustration with sls and time wasted.

### Proposed solution

It would be very helpful if sls performed an appropriate level of template/schema validation and emit well-formed, directed error messages rather than subsequently fail with opaque internal exceptions.

The sls tools should never trust the user's template input to be well-formed or semantically valid but sls does not perform sufficient pre-validation to prevent the sls code failing with runtime JavaScript errors such as TypeError. An example is provided below.

Additionally, write unit tests that cause sls to process templates with various content problems e.g. missing function declarations, missing required properties within function declarations, presence of extraneous declarations (possibly indicating mis-indented declaration), mis-typed declarations, and more.

### Sample Template

```yaml
service: test-s3-mybucket

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stackName: test-s3-mybucket
  s3:
    mybucket:
      name: test-s3-mybucket7

functions:
  ABCHandler:
    handler: index.handler
    description: Testing mybucket uploads
    events:
      - s3:
        bucket: mybucket
        event: s3:ObjectCreated:*
  XYZHandler:
```

When deploying using `npx serverless deploy -v`, this will result in:
 
```
 Type Error ----------------------------------------------
 
  TypeError: Cannot read property 'events' of null
      at testing/node_modules/serverless/lib/classes/Service.js:179:24
      at Array.forEach (<anonymous>)
      at Service.setFunctionNames (testing/node_modules/serverless/lib/classes/Service.js:178:36)
      at Serverless.run (testing/node_modules/serverless/lib/Serverless.js:265:18)
      at testing/node_modules/serverless/scripts/serverless.js:240:24
```

The problem here is that `XYZHandler` is actually an empty function declaration with no configured events.

Example enhanced validation: if the code is going to process a list of events and assume that `events` is present and is an array then the code should validate that events have actually been configured and fail with an appropriate message such as "No events configured for XYZHandler".
