### ISSUE TITLE
Setting up Lambda@Edge and CloudFront

### ISSUE THREAD

**Issue by emilpaw** [serverless/serverless#9138]
I have some troubles setting up CloudFront and Lambda@Edge for our SPA.

My goal is to serve all requests with the origin `myfrontendbucket.s3-website.eu-central-1.amazonaws.com`, but invoke my `edge-redirector` Lamda@Edge function if the path `somepath/` is accessed.

The CloudFront setup works, but the Lambda is not associated with the CacheBehaviour. Weirdly, it creates the Lambda@Edge function at the region eu-central-1 and to my knowledge only us-east-1 works with Lambda@Edge. Is there anything I missed?

This is my serverless.yml configuration, at least the part which is related to my issue.

 ```yaml
functions:
  edge-redirector:
    handler: edge-redirector/edge-redirector/main.lambda_handler
    events:
      - cloudFront:
        eventType: origin-request
        pathPattern: somepath/*
        origin:
          DomainName: myfrontendbucket.s3-website.eu-central-1.amazonaws.com
resources:
  Resources:
    CloudfrontDistribution:
      Type: AWS::CloudFront::Distribution
      DeletionPolicy: Retain
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: myfrontendbucket.s3-website.eu-central-1.amazonaws.com
              Id: someid
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          Enabled: 'true'
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: someid
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          CacheBehaviors:
            - PathPattern: somepath/*
              AllowedMethods:
                - GET
                - HEAD
              TargetOriginId: someid
              ViewerProtocolPolicy: redirect-to-https
              CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
```

Output of `sls deploy --stage XXX-develop --frontendbucket myfrontendbucket
```
...
Serverless:   at 'functions['edge-redirector'].events[0]': unsupported function event
...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Service files not changed. Skipping deployment...
Service Information
...
api keys:
  None
endpoints:
  ANY - https://XXXXXXXX.execute-api.eu-central-1.amazonaws.com/sck-develop
  ANY - https://XXXXXXXX.execute-api.eu-central-1.amazonaws.com/sck-develop/{proxy+}
functions:
...
  edge-redirector: XXX-edge-redirector
layers:
None
```

Installed Version:
``
Framework Core: 2.28.7
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.2
``

I greatly appreciate any input on this.

**Comment by pgrzesik** [comment]
Hello @emilpaw, thanks for reporting, could you please follow the issue template that is shown when you try to create a new issue - please include the Framework version that you're using.

**Comment by emilpaw** [comment]
> could you please follow the issue template that is shown when you try to create a new issue - please include the Framework version that you're using.

Oh sorry, I have overlooked it. I edited my issue.

**Comment by pgrzesik** [comment]
Thank you :bow: There's a warning being emitted that points to invalid configuration:
```
Serverless:   at 'functions['edge-redirector'].events[0]': unsupported function event
```

I believe that the event definition is incorrect there as it misses proper indentation:

```
functions:
 edge-redirector:
   handler: edge-redirector/edge-redirector/main.lambda_handler
   events:
     - cloudFront:
         eventType: origin-request
         pathPattern: somepath/*
         origin:
           DomainName: myfrontendbucket.s3-website.eu-central-1.amazonaws.com
```

Could you please check if that's what is causing the issue here?
