### ISSUE TITLE
sls deploy error with serverless version 2.30.* when using https_proxy

### ISSUE THREAD

**Issue by AndreasAugustin** [serverless/serverless#9146]
## update

Small test revealed that `npx serverless deploy` is not working anymore using a `https_proxy`.
The reason: `https-proxy-agent` is not supporting the `WHATWG URL` as constructor parameter. Details please scroll down within this issue description to the `edit` section.

## Original comment
Original issue title:  `The “options” or “port” or “path” argument must be specified when using https_proxy version 2.30.*`

With latest version `2.30.3` when deploying and using an exported (env variable) `https_proxy` I get an error

```bash
The “options” or “port” or “path” argument must be specified
```

When the proxy is unset, then everything is working as expected.

**Remark:**
This is also described in https://forum.serverless.com/t/the-options-or-port-or-path-argument-must-be-specified/14413/3

<details>
<summary>
<code>

</code>
</summary>

```yaml
frameworkVersion: '2'
useDotEnv: true
plugins:
  - serverless-webpack
  - serverless-appsync-plugin
provider: 
  name: aws
  runtime: nodejs14.x

```

</details>

<details>
<summary><b><code>npx serverless --stage=${STAGE} deploy</code> </b></summary>

```bash
....
The “options” or “port” or “path” argument must be specified 
```

</details>

<b>Installed version</b>

```
Framework Core: 2.30.3
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.5
```

## Edit (summarize of the following content):

It seems that the [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent) is not able to use the [WHATWG URL](https://nodejs.org/api/url.html#url_legacy_urlobject) The problem is likely line `46` within [https-proxy-agent src/agent.ts](https://github.com/TooTallNate/node-https-proxy-agent/blob/master/src/agent.ts)

```typescript
const proxy: HttpsProxyAgentOptions = { ...opts };
```

The [WHATWG URL](https://github.com/nodejs/node/blob/master/lib/url.js) is not enumerable in the current implementation. That means that the spread operator (or Object.assign) is not working and the shallow clone above is broken.
[issue](https://github.com/TooTallNate/node-https-proxy-agent/issues/117).

The mentioned error (in this issue title) is related to `node15` because `nodejs` added some more validation steps. 
Am not sure if the current implementation is really working with `node14`.

**Comment by AndreasAugustin** [comment]
Think I found the root cause.
Workaround: pin the serverless version to 2.29.0.
With latest releases a new file [lib/aws/request.js](https://github.com/serverless/serverless/compare/v2.29.0...v2.30.0#diff-53bd04d8d8329cd036c09761a906e0cc5efaa64a4c371b9b6db52b85afdabd38)
was introduced.
Inside those changes `URL` is used not [url](https://www.npmjs.com/package/url) anymore.
The `url.parse` command returned an object with a path property. the `URL` object does not have the path property.
Was not able to proove that yet.

**Comment by medikoo** [comment]
@AndreasAugustin This looks as an issue in one of the plugins you're using and not Serverless. Can you confirm you get similar error with no plugins involved (?)

**Comment by AndreasAugustin** [comment]
@medikooI I will do that, yes. Sorry that I haven't done this before.

**Comment by medikoo** [comment]
@AndreasAugustin can you explain in more detail the problem. What entity exactly relies on `path` property? Can you provide a direct link to code line where this dependency occurs

**Comment by AndreasAugustin** [comment]
Confirmed that it is *not* a plugin issue.
Wrote a small test stack:

```yaml
service: sls-test

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  logRetentionInDays: 14
  timeout: 10
  # lambdaHashingVersion: 20201221

  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256

  environment:
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}

package:
  excludeDevDependencies: true

functions:
  myHandler:
    handler: src/handler.myHandler
```

## Command:

```bash
npx serverless deploy
```

### Output

```bash
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Recoverable error occurred (The "options" or "port" or "path" argument must be specified), sleeping for ~7 seconds. Try 1 of 4
Serverless: Recoverable error occurred (The "options" or "port" or "path" argument must be specified), sleeping for ~5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (The "options" or "port" or "path" argument must be specified), sleeping for ~6 seconds. Try 3 of 4
Serverless: Recoverable error occurred (The "options" or "port" or "path" argument must be specified), sleeping for ~6 seconds. Try 4 of 4
 
 Serverless Error ----------------------------------------
 
  The "options" or "port" or "path" argument must be specified
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.11.0
     Framework Version:         2.30.3 (local)
     Plugin Version:            4.5.1
     SDK Version:               4.2.0
     Components Version:        3.7.5
```

Serverless version is within the output.
Without proxy: everything works fine. With set proxy: above error occurs.

Could also be an issue with the proxy itself, but downgrading the serverless version to ` 2.27.1` is working with the proxy.
