### ISSUE TITLE
Plugin construction documentation is misleading

### ISSUE THREAD

**Issue by WolfWalter** [serverless/serverless#9149]
My servereless.yml file has mix of external plugins like serverless-webpack and local plugins like "./lib/serverless/plugins/check-stage-name". Since the version 2.30.0 the external plugins do not get executed when there are also local plugins. When I remove the local plugins it works. I was able to fix the issue by reverting the commit a9a48f675e8695dc3b795218d0eb23553c33f9d8

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: sp-api
variablesResolutionMode: 20210219

plugins:
  - serverless-webpack
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - ./lib/serverless/plugins/check-stage-name
  - ./lib/serverless/plugins/check-git-branch-before-deploy
...
```

</details>

<details>
<summary><b><code>sls deploy --config serverless-api.yml --verbose</code> output</b></summary>

```
Serverless: CheckGitBranchBeforeDeploy: No branch requirement for stage "wlt"
Done in 1.80s.

```

</details>

<b>Installed version</b>

```
sls --version
Framework Core: 2.30.0 (local)
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.5
Done in 0.66s.
```
