### ISSUE TITLE
Variables are not being resolved 

### ISSUE THREAD

**Issue by hejkerooo** [serverless/serverless#9156]
```yaml
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: sls-test

frameworkVersion: '2'
plugins:
 - my-plugin

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

custom:
  webServiceEndpoint:
    Fn::Join:
      - ''
      - - 'https://'
        - Ref: ApiGatewayRestApi
        - '.execute-api.'
        - Ref: AWS::Region
        - '.amazonaws.com/'
        - ${self:provider.stage}

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello-world
          method: get
          cors: true
```

Plugin code:
```js
import Serverless from 'serverless';
import { customTopLevelPropertySchema } from './config';

class ServerlessPlugin {
  public hooks: any;
  protected serverless: Serverless;

  constructor(serverless: Serverless, options: any) {
    this.serverless = serverless;
    this.defineConfiguration();

    this.hooks = {
      'after:deploy:deploy': this.afterDeployFunctions.bind(this),
    };
  }

  private async afterDeployFunctions(): Promise<void> {
    const options = this.serverless.service.custom;
    console.log(options.webServiceEndpoint);
  }
  private defineConfiguration(): void {
    this.serverless.configSchemaHandler.defineCustomProperties(
      customTopLevelPropertySchema,
    );
  }
}

module.exports = ServerlessPlugin;

```
`console.log(options.webServiceEndpoint)` prints 
```
⚠️⚠️ {"Fn::Join":["",["https://",{"Ref":"ApiGatewayRestApi"},".execute-api.",{"Ref":"AWS::Region"},".amazonaws.com/","dev"]]}}
</details>

```

<b>Installed version</b>

```
⚠️⚠️ REPLACE WITH `serverless --version` OUTPUT
Framework Core: 2.6.0
Plugin: 4.0.4
SDK: 2.3.2
Components: 3.2.1
```

**Comment by AndreasAugustin** [comment]
Hi, 

hope I understand your question right.
AFAIK the way you declare the variables, they are resolved at `CloudFormation` level and not on `serverless` level.
What you can do is to use something like

[Reference CloudFormation Outputs](https://www.serverless.com/framework/docs/providers/aws/guide/variables/)

```yaml
service: new-service
provider: aws
functions:
  hello:
    name: ${cf:another-service-dev.functionPrefix}-hello
    handler: handler.hello
  world:
    name: ${cf:another-stack.functionPrefix}-world
    handler: handler.world
```

That will read your variables from the `Cloudformation` stack. The problem with this approach is that you will run in race conditions because with the first deployment your variables won't be present at the (non existent) stack.
