### ISSUE TITLE
Support Amazon S3 Object Lambda

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#9158]
### Use case description

Announced at https://aws.amazon.com/blogs/aws/introducing-amazon-s3-object-lambda-use-your-code-to-process-data-as-it-is-being-retrieved-from-s3/

It'll be great to provide a straightforward support for this new functionality

### Proposed solution

_TBA_

/cc @pgrzesik

**Comment by pgrzesik** [comment]
Hello :wave: I've dug a bit into the configuration and there are quite a few options that can be configured. I've pondered with different ways of incorporating it into the Framework and the most reasonable one (in my opinion) would be something similar to:

```
functions:
  customFunc:
    handler: index.handler
    s3ObjectConfigurations:
      - 
        bucket: <name-of-bucket> # Required
        policy: <access-policy> # Optional policy for access point
        # Maybe a catch-all to enable all below? e.g blockPublicAccess: true
        blockPublicAcls: true # Optional
        blockPublicPolicy: true # Optional
        ignorePublicAcls: true # Optional
        restrictPublicBuckets: true # Optional
        vpc: <id-of-vpc> # Optional. Allows connections only from specified VPC
        supportRangeRequests: true # Optional
        supportPartNumberRequests: true # Optional
        metrics: true # Optional. Enables CloudWatch Metrics 
        payload: <optional-payload-passed-to-func> # Optional. Payload that is passed to Lambda function
```

It is possible to use the same function for multiple separate access points, that's why the array notation. The alternative option would be to define it as a top level property in service or inside `provider`, but since these are directly tied to functions I think it makes the most sense to define them in a similar way to `events`. 

Related CloudFormation docs:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-accesspoint.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3objectlambda-accesspoint.html

Based on the above, we need to first create `AWS::S3::AccessPoint` which is later used to create `AWS::S3ObjectLambda::AccessPoint` resource that sets up the actual integration.

Any feedback on the above would be more than welcome :raised_hands:

**Comment by medikoo** [comment]
@pgrzesik looks great. What's not perfectly clear to me is meaning of all _public access_ option (even after I read explanations on AWS side) - it'll be probably easiest to discuss it during one of the next calls.

**Comment by antstanley** [comment]
Hey Folks! Just checking on any progress on this? Is there a plan to support Object Lambda in Serverless Framework anytime soon?

**Comment by pgrzesik** [comment]
Hello @antstanley - at the moment we don't plan to actively work on implementation for it in the short term, but we'd be more than happy to accept a contribution from community for it :raised_hands: Still, before implementation, it would be great to finalize the implementation spec :+1:

**Comment by Lokesh-Jawale** [comment]
Hi @pgrzesik can I look into this? is PR for this change still welcome?

**Comment by medikoo** [comment]
@Lokesh-Jawale let's first fully clarify how we will introduce this to the Framework.

As I look at it now, I wonder why not introduce it as `s3ObjectConfiguration` event (?) Having that, it could be configured as:

```yaml
functions:
  customFunc:
    handler: index.handler
    events:
      - s3ObjectConfiguration:
          bucket: <name-of-bucket> # Required
          # .. other options
```

And best would be to specify each option and relation to generated CF template before we proceed with implementation.

@Lokesh-Jawale it's very welcome for you to take over, so let's please start with the spec
