### ISSUE TITLE
Configuration warning: at 'functions.NAME.image': should have property entryPoint when property command is present

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#9173]
I'm creating a docker image using the following example in the AWS Docs, which defines the `ENTRYPOINT`:
https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-create-2

Trying to figure out why I'm getting this warning and if I can ignore it or figure out what I need to do, to get rid of it.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service
frameworkVersion: 2

provider:
  name: aws
  region: us-west-1
  ecr:
    images:
      tokenization:
        path: ./
  stage: ${opt:stage, 'dev'}
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  renew:
    description: 'POST /${self:provider.stage}/renew'
    image: 
      name: tokenization
      command:
        - tokenization.renew
    timeout: 15
    events:
      - http:
          path: /renew
          method: post
          integration: lambda


  unlock:
    description: 'POST /${self:provider.stage}/unlock'
    image: 
      name: tokenization
      command:
        - tokenization.unlock
    timeout: 15
    events:
      - http:
          path: /unlock
          method: post
          integration: lambda

package:
  individually: true
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'functions.renew.image': should have property entryPoint when property command is present
Serverless:   at 'functions.unlock.image': should have property entryPoint when property command is present
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
```

</details>

<b>Installed version</b>

```
Framework Core: 2.31.0 (local)
Plugin: 4.5.2
SDK: 4.2.2
Components: 3.7.6
```
