### ISSUE TITLE
Error: npm ls -prod -json -depth=1 failed with code 1

### ISSUE THREAD

**Issue by Vivek205** [serverless/serverless#9187]
I'm trying to deploy my lambda, but getting error.
`Error: npm ls -prod -json -depth=1 failed with code 1`

Note: I'm using a local package in the npm.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-apigwy-binary
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: 'us-east-1'
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid
  styleTransferAi:
    handler: src/handlers/styleTransferAi.handler
    events:
      - http:
          method: POST
          path: /styletransferai
          contentHandling: CONVERT_TO_BINARY

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  apigwBinary:
    types:           #list of mime-types
      - 'image/jpeg'
      - 'image/png'
```

</details>

<details>
<summary><b><code> sls deploy -f styleTransferAi -v</code> output</b></summary>

```
Serverless: Using configuration:
{
  "packager": "npm",
  "packagerOptions": {},
  "webpackConfig": "node_modules/serverless-bundle/src/webpack.config.js",
  "includeModules": {
    "forceExclude": [
      "aws-sdk"
    ],
    "forceInclude": null,
    "packagePath": "package.json"
  },
  "keepOutputDirectory": false,
  "concurrency": 8
}
Serverless: Removing /Users/vivek/Documents/Learning/serverless-course/auction-service/.webpack
Serverless: Bundling with Webpack...

Serverless: Fetch dependency graph from /Users/vivek/Documents/Learning/serverless-course/auction-service/package.json
 
 Error ---------------------------------------------------
 
  Error: npm ls -prod -json -depth=1 failed with code 1
      at ChildProcess.<anonymous> (/Users/vivek/Documents/Learning/serverless-course/auction-service/node_modules/serverless-webpack/lib/utils.js:91:16)
      at ChildProcess.emit (events.js:314:20)
      at ChildProcess.EventEmitter.emit (domain.js:483:12)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:314:20)
      at Socket.EventEmitter.emit (domain.js:483:12)
      at Pipe.<anonymous> (net.js:676:12)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.19.0
     Framework Version:         2.30.3
     Plugin Version:            4.5.1
     SDK Version:               4.2.0
     Components Version:        3.7.4
```

</details>

<b>Installed version</b>

```
Framework Core: 2.30.3
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.4
```
