### ISSUE TITLE
AWSLambdaFullAccess is deprecated

### ISSUE THREAD

**Issue by markvitapoly** [serverless/serverless#9188]
sls deploy says AWSLambdaFullAccess not found.

<details>
<summary><code>serverless.yml
</code></summary>

```yaml
org: someorg
app: my-express-app
component: express
name: express-starter

inputs:
  src: ./

```

</details>

```
serverless ⚡framework

components version: 3.7.7
```

More information from others with same issue in forums: https://forum.serverless.com/t/policy-arniam-policy-awslambdafullaccess-does-not-exist-or-is-not-attachable/14537
