### ISSUE TITLE
Could not locate deployment bucket. Error: AWS profile "dev" doesn't seem to be configured

### ISSUE THREAD

**Issue by ajays1991** [serverless/serverless#9190]
Operating System:          linux
 Node Version:              10.19.0
 Framework Version:         2.31.0
 Plugin Version:            4.5.2
 SDK Version:               4.2.2
 Components Version:        3.7.7

serverless is not picking the aws credentials, i tried with default and profile credentials using the following command

`serverless config credentials --provider aws --key ********** --secret ********* --profile dev
`
I can verify the profile created in AWS credentials file. Then i run the deploy command

`sudo sls deploy --aws-profile dev`

I getting the following errror:

```
Serverless: Injecting required Python packages to package...
 
 Serverless Error ----------------------------------------
 
  Could not locate deployment bucket. Error: AWS profile "dev" doesn't seem to be configured

``` 

I also tried to run the serverless deploy with default profile but then i get the following errror. Serverless is completely  neglecting the AWS credentials.

```
serverless: Injecting required Python packages to package...
 
 Serverless Error ----------------------------------------
 
  Could not locate deployment bucket. Error: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: <http://slss.io/aws-creds-setup>.
 
```

**Comment by pgrzesik** [comment]
Hello @ajays1991, thanks for reporting and sorry you've run into trouble. Could you please provide a minimal reproducible example with `serverless.yml` configuration that results in the issue above? It will help me with reproducing this problem on my side. Thanks in advance. :bow:

**Comment by ajays1991** [comment]
```
org: some-org
app: some-app
service: some-service

provider:
  name: aws
  runtime: python3.7
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 900 # optional, in seconds, default is 6
# you can overwrite defaults here
  stage: dev
  region: eu-west-1
  profile: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
        - "lambda:*"
        -  "rds:*"
      Resource: "*"
  deploymentBucket:
    name: some-bucket
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
    tags:
      service: ${self:service}

# you can add packaging information here
package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: true
  secrets: ${file(secrets.dev.yml)}

functions:
  merchant-reconciliation:
    handler: lambda_handler.handler
    module: reconciliation
    description: Function is used to generate reconciliation reports for the merchants
    environment:
      MONGODB_DATABASE_NAME: ${self:custom.secrets.MONGODB_DATABASE_NAME}
      MONGODB_COLLECTION_NAME: ${self:custom.secrets.MONGODB_COLLECTION_NAME}
      MONGODB_MONGO_URI: ${self:custom.secrets.MONGODB_MONGO_URI}
      MONGODB_PASSWORD: ${self:custom.secrets.MONGODB_PASSWORD}
      RECON_BUCKET_NAME: ${self:custom.secrets.RECON_BUCKET_NAME}
      #SENTRY_DSN: ${self:custom.secrets.SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${opt:stage,self:provider.stage}
      SENTRY_RELEASE: v20.e.0
      RDS_HOST: ${self:custom.secrets.RDS_HOST}
      RDS_USER: ${self:custom.secrets.RDS_USER}
      RDS_PASSWORD: ${self:custom.secrets.RDS_PASSWORD}
      RDS_DATABASE: ${self:custom.secrets.RDS_DATABASE}
      RDS_CHARSET: ${self:custom.secrets.RDS_CHARSET}
      STAGE: ${self:custom.secrets.STAGE}
    events:
      - schedule:
          name: merchant-reconciliation-${opt:stage, self:provider.stage}
          description: 'This is to trigger merchant reconciliation reports '
          rate: cron(0 5 1 * ? *)
          enabled: true
      - schedule:
          name: merchant-reconciliation_1_4-${opt:stage, self:provider.stage}
          description: 'This is to trigger merchant reconciliation reports every 4th day '
          rate: rate(4 days)
          enabled: true
          input:
            run: 1_4

plugins:
  - serverless-python-requirements
  - serverless-secrets-plugin

```
