### ISSUE TITLE
export AWS_PROFILE overrules profile mapping to stage

### ISSUE THREAD

**Issue by zanettin** [serverless/serverless#9194]
in a terminal where i have `export AWS_PROFILE=my-prod` executed, the profile mapping within the `serverless.yml` file is no longer working. the default env in my `serverless.yml` file is set to `dev` and this stage is mapped to the profile `my-dev`. if i execute any cmd, all actions will be executed against the `my-prod` account and not agains `my-dev` (because of the above mentioned `export`). this can be workaround be defining `--aws-profile my-dev` again. as soon as i execute `unset AWS_PROFILE` everything is working as expected again.

in the case below, the `sls deploy` cmd will fail because the certificate does not exist on the prod account but just on develop.

not sure if this is a bug or an intended behavior but seems to me a bit risky to rely on the exported value and not on the mapping.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: nest-serverless-lambda-demo

plugins:
  - serverless-domain-manager
  - serverless-webpack
  - serverless-offline

custom:
  # current stage
  stage: ${opt:stage, self:provider.stage}
  # base domain
  baseDomain: service.domain.tld
  # map certificates to stages
  certificates:
    prod: "*.${self:custom.baseDomain}"
    stage: "*.stage.${self:custom.baseDomain}"
    dev: "*.dev.${self:custom.baseDomain}"
  # map custom domains to stages
  domains:
    prod: sls-test.${self:custom.baseDomain}
    stage: sls-test.stage.${self:custom.baseDomain}
    dev: sls-test.dev.${self:custom.baseDomain}
  # map aws profiles to stages
  profile:
    prod: my-prod
    stage: my-develop
    dev: my-develop
  # configure custom domains
  customDomain:
    basePath: ""
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRoute53Record: true
    certificateName: ${self:custom.certificates.${self:custom.stage}}
    endpointType: regional
    securityPolicy: tls_1_2
    autoDomain: true # create and remove domains on sls deploy / remove
  # configure webpack
  webpack:
    includeModules: true
    packager: yarn
    excludeFiles: test/**/*

provider:
  name: aws
  profile: ${self:custom.profile.${self:custom.stage}}
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 256
  timeout:  10
  stage: dev
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  main:
    name: ${self:custom.stage}-${self:service}
    description: 'the description provided by butler'
    handler: src/lambda.handler
    # provisionedConcurrency: 1 # <- enable just if needed
    events:
      - http:
          method: any
          path: /{any+}
    environment:
      DUMMY_KEY: ${ssm:/ws/sls-test-service/dummy,'n/A'}
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
SLS_DEBUG=* sls deploy
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.30.3")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command create_domain
Serverless: Load command delete_domain
Serverless: Load command webpack
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
assets by path ../../dist/src/*.ts 759 bytes
  asset ../../dist/src/bootstrap.d.ts 317 bytes [compared for emit]
  asset ../../dist/src/app.controller.d.ts 236 bytes [compared for emit]
  asset ../../dist/src/lambda.d.ts 77 bytes [compared for emit]
  asset ../../dist/src/app.service.d.ts 72 bytes [compared for emit]
  asset ../../dist/src/app.module.d.ts 35 bytes [compared for emit]
  asset ../../dist/src/app.controller.spec.d.ts 11 bytes [compared for emit]
  asset ../../dist/src/main.d.ts 11 bytes [compared for emit]
asset src/lambda.js 1.52 MiB [emitted] [minimized] (name: src/lambda) 1 related asset
asset ../../dist/test/app.e2e-spec.d.ts 11 bytes [compared for emit]
orphan modules 223 KiB [orphan] 146 modules
runtime modules 1.03 KiB 5 modules
modules by path ./node_modules/ 2.56 MiB
  javascript modules 2.3 MiB 528 modules
  json modules 260 KiB
    modules by path ./node_modules/iconv-lite/encodings/tables/*.json 86.7 KiB 8 modules
    4 modules
modules by path ./src/*.ts 5.45 KiB
  ./src/lambda.ts 324 bytes [built] [code generated]
  ./src/app.module.ts 1.06 KiB [built] [code generated]
  ./src/bootstrap.ts 1.04 KiB [built] [code generated]
  ./src/app.controller.ts 2.1 KiB [built] [code generated]
  ./src/app.service.ts 963 bytes [built] [code generated]
17 modules

WARNING in ./node_modules/@nestjs/common/utils/load-package.util.js 9:39-59
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nestjs/core/nest-factory.js 5:28-77
 @ ./node_modules/@nestjs/core/index.js 27:21-46
 @ ./src/bootstrap.ts 7:15-38
 @ ./src/lambda.ts 5:20-42

WARNING in ./node_modules/@nestjs/core/helpers/load-adapter.js 9:39-63
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nestjs/core/nest-factory.js 10:23-56
 @ ./node_modules/@nestjs/core/index.js 27:21-46
 @ ./src/bootstrap.ts 7:15-38
 @ ./src/lambda.ts 5:20-42

WARNING in ./node_modules/@nestjs/core/helpers/optional-require.js 6:39-59
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@nestjs/core/nest-application.js 11:27-64
 @ ./node_modules/@nestjs/core/index.js 25:21-50
 @ ./src/bootstrap.ts 7:15-38
 @ ./src/lambda.ts 5:20-42

WARNING in ./node_modules/express/lib/view.js 81:13-25
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/express/lib/application.js 22:11-28
 @ ./node_modules/express/lib/express.js 18:12-36
 @ ./node_modules/express/index.js 11:0-41
 @ ./src/bootstrap.ts 4:16-34
 @ ./src/lambda.ts 5:20-42

webpack compiled with 4 warnings in 10985 ms
Serverless: Invoke webpack:package
Serverless: No external modules needed
(node:95854) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless Domain Manager: Info: Creating domain name before deploy.
Serverless Domain Manager: Error:  sls-test.dev.service.domain.tld does not exist
Serverless Domain Manager: Error: sls-test.dev.service.domain.tld:  Error: Could not find the certificate *.dev.service.domain.tld.
 
 Error ---------------------------------------------------
 
  Error: Unable to create domain sls-test.dev.service.domain.tld
      at ServerlessCustomDomain.<anonymous> (/Users/me/Development/tests/sls-nest/node_modules/serverless-domain-manager/dist/src/index.js:182:23)
      at Generator.throw (<anonymous>)
      at rejected (/Users/me/Development/tests/sls-nest/node_modules/serverless-domain-manager/dist/src/index.js:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.1
     Framework Version:         2.30.3
     Plugin Version:            4.5.2
     SDK Version:               4.2.2
     Components Version:        3.7.6

```

</details>

<b>Installed version</b>

```
Framework Core: 2.30.3
Plugin: 4.5.2
SDK: 4.2.2
Components: 3.7.6
```
