### ISSUE TITLE
Package does not recognize "patterns" configuration

### ISSUE THREAD

**Issue by Rukenshia** [serverless/serverless#9196]
When trying to use the `package.patterns`, I receive the following warning:

```
Serverless: Configuration warning at 'package': unrecognized property 'patterns'
```

I am using the most recent version of serverless.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: billing
frameworkVersion: '2'

custom:
  env: ${file(serverless/config/${opt:stage}.yml)}
  pythonRequirements:
    dockerizePip: true

package:
  patterns:
    - 'lib/**'
    - '*.py'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  region: eu-central-1

  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetBucketLocation
            - s3:ListBucket
            - s3:GetObject
            - s3:PutObject
            - s3:AbortMultipartUpload
            - s3:ListMultipartUploadParts
            - s3:ListBucketMultipartUploads
          Resource:
            - 'arn:aws:s3:::${self:custom.env.AthenaQueryResultsBucketName}'
            - 'arn:aws:s3:::${self:custom.env.AthenaQueryResultsBucketName}/*'
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - 'arn:aws:s3:::${self:custom.env.BillingDataBucketName}'
            - 'arn:aws:s3:::${self:custom.env.BillingDataBucketName}/*'
        - Effect: Allow
          Action:
            - athena:StartQueryExecution
            - athena:GetQueryExecution
            - glue:CreateDatabase
            - glue:DeleteDatabas
            - glue:GetDatabase
            - glue:GetDatabase
            - glue:UpdateDatabase
            - glue:CreateTable
            - glue:DeleteTable
            - glue:BatchDeleteTable
            - glue:UpdateTable
            - glue:GetTable
            - glue:GetTable
            - glue:BatchCreatePartition
            - glue:CreatePartition
            - glue:DeletePartition
            - glue:BatchDeletePartition
            - glue:UpdatePartition
            - glue:GetPartition
            - glue:GetPartition
            - glue:BatchGetPartition
          Resource:
            - '*'

functions:
  create_athena_partitions:
    handler: create_athena_partitions.lambda_handler
    events:
      - schedule: cron(0 8 1 * ? *)
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* npx sls deploy --stage prod</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Configuration warning at 'package': unrecognized property 'patterns'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.31.0 (local)
Plugin: 4.5.2
SDK: 4.2.2
Components: 3.7.7
```
