### ISSUE TITLE
!Sub unexpectedly works with function-level `role` param

### ISSUE THREAD

**Issue by faucherb94** [serverless/serverless#9199]
The end goal of what I've done is an easy way to reference the AWS account ID of the current cli session without hard-coding it in serverless.yml, specifically for setting the IAM role to be used by functions to an IAM role that already exists in the target account. Either something that was able to insert `"Fn::Sub": "...${AWS::AccountId)..."` into the resulting CF template output, or something that actually grabbed the account ID from the cli (e.g. with a backend call to `aws sts`) and inserted the actual account ID into the CF template, would have been acceptable.

Prior to sls 2.30 and the deprecation of the [pseudoparameters plugin](https://github.com/svdgraaf/serverless-pseudo-parameters), it was possible to use `#{AWS::AccountId}` directly in both `provider.iam.role` and `functions.<function>.role`, and sls would convert it to a `"Fn::Sub":` statement in the CF template. That plugin claims all of its functionality now exists natively in sls as of v2.30, but that is clearly untrue. Attempting something like so:

```yaml
frameworkVersion: '2'

provider:
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/MyRole
```

results in a configuration warning:

```
> sls package
...
Serverless: Configuration warning:
Serverless:   at 'provider.iam.role': unsupported configuration format
...
```

and sls acts as if I left the `provider.iam` block completely blank, i.e. the resulting CF template creates the default IAM role for all functions, rather than referencing the existing one.

What I found _does_ achieve my goal is using `!Sub` at the function level:

```yaml
frameworkVersion: '2'

provider:
  # leave iam block empty

functions:
  MyFunc:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/MyRole
```

or using a `custom` value for using the same role for multiple functions:

```yaml
frameworkVersion: '2'

provider:
  # leave iam block empty

custom:
  ExecRole: !Sub arn:aws:iam::${AWS::AccountId}:role/MyRole

functions:
  MyFunc1:
    role: ${self:custom.ExecRole}
  MyFunc2:
    role: ${self:custom.ExecRole}
```

This still results in a configuration warning (both using a `custom` value and not):

```
> sls package
...
Serverless: Configuration warning:
Serverless:   at 'functions.MyFunc1.role': unsupported configuration format
Serverless:   at 'functions.MyFunc2.role': unsupported configuration format
...
```

_but_ the resulting CF template has the expected values, e.g. `!Sub arn:...${AWS::AccountId}...` is correctly turned into `"Fn::Sub": "arn:...${AWS::AccountId}..."`, and it's accepted by AWS when deployed.

For the sake of debugging, I also tried setting `provider.iam.role` to `arn:...${AWS::AccountId}...` without `!Sub` e.g.

```yaml
frameworkVersion: '2'

provider:
  iam:
    role: arn:aws:iam::${AWS::AccountId}:role/MyRole
```

and `sls package` runs with no config warnings, but `sls deploy` fails because the CF template output literally sets the `role` field of the functions to the string value `"arn:aws:iam::${AWS::AccountId}:role/MyRole"` _without_ `"Fn::Sub"`, which is invalid.

Something isn't right here - either the configuration warning should be correct and `!Sub` expressions should not be properly translated into the CF template at both the global _and_ function levels, or `!Sub` expressions should work at the function level and sls shouldn't be throwing a configuration warning (I'd obviously prefer the latter).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: snapshot-lambdas

frameworkVersion: '2'

package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, env:AWS_DEFAULT_REGION}
  stackName: snapshot-lambdas
  lambdaHashingVersion: '20201221'

functions:
  TakeSnapshotsAurora:
    name: TakeSnapshotsAurora
    role: ${self:custom.ExecRole}
    memorySize: 512
    package:
      include:
      - TakeSnapshotsAurora/*
      - snapshots_tool_utils.py
    handler: TakeSnapshotsAurora/lambda_function.lambda_handler
    runtime: python3.7
    timeout: 300
    environment:
      INTERVAL: '24' # Hours between snapshots
      PATTERN: ${self:custom.ClusterNamePattern}
      LOG_LEVEL: ${self:custom.LogLevel}
      REGION_OVERRIDE: ${self:custom.SourceRegionOverride}
    events:
    - schedule:
        name: TakeSnapshotsAuroraSchedule
        rate: cron(${self:custom.BackupSchedule})

  DeleteOldSnapshotsAurora:
    name: DeleteOldSnapshotsAurora
    role: ${self:custom.ExecRole}
    memorySize: 512
    package:
      include:
      - DeleteOldSnapshotsAurora/*
      - snapshots_tool_utils.py
    handler: DeleteOldSnapshotsAurora/lambda_function.lambda_handler
    runtime: python3.7
    timeout: 300
    environment:
      RETENTION_DAYS: '7'
      PATTERN: ${self:custom.ClusterNamePattern}
      LOG_LEVEL: ${self:custom.LogLevel}
      REGION_OVERRIDE: ${self:custom.SourceRegionOverride}
    events:
    - schedule:
        name: DeleteOldSnapshotsAuroraSchedule
        rate: cron(0 0 * * ? *) # 00:00 UTC every day, 1 hour before taking snapshots runs

custom:
  ExecRole: !Sub arn:aws:iam::${AWS::AccountId}:role/MyRole
  pythonRequirements:
    pythonBin: python3
    dockerizePip: false
    slim: true
  ClusterNamePattern: ALL_CLUSTERS
  BackupSchedule: '0 1 * * ? *' # 01:00 UTC/19:00 CST every day
  LogLevel: INFO # [ DEBUG, INFO, WARN, ERROR, CRITICAL ]
  SourceRegionOverride: 'NO'

plugins:
- serverless-plugin-include-dependencies
- serverless-python-requirements

```
</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Configuration warning:
Serverless:   at 'functions.TakeSnapshotsAurora.role': unsupported configuration format
Serverless:   at 'functions.DeleteOldSnapshotsAurora.role': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generated requirements from requirements.txt in .serverless/requirements.txt...
Serverless: Using static cache of requirements found at [redacted] ...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Injecting required Python packages to package...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.31.0 (local)
Plugin: 4.5.2
SDK: 4.2.2
Components: 3.7.6
```
