### ISSUE TITLE
Serverless isn't building and pushing image to ECR

### ISSUE THREAD

**Issue by corydorning53** [serverless/serverless#9204]
I have defined an image path in `provider.ecr` but its not being built and deployed to ECR. Does a `function` have to reference an image for this deployment to occur?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-service
frameworkVersion: 2

provider:
  name: aws
  region: us-east-2
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      # docker container used for scheduling daily unlocks
      unlock:
        path: ./unlock/
  # default stage, to use prod run the command 'sls deploy --stage prod' when deploying
  stage: ${opt:stage, 'dev'}
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
 Serverless Warning --------------------------------------
 
  Configured "frameworkVersion" does not represent a valid semver version range, version validation is skipped
 
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Service Information
service: my-service
stage: dev
region: us-east-2
stack: my-service
resources: 2
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None
```

</details>

<b>Installed version</b>

```
Framework Core: 2.32.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.7.7
```
