### ISSUE TITLE
When providing a role ARN containing !Sub to a function with sns/sqs events, a DependsOn is generated to non-existing IamRoleLambdaExecution

### ISSUE THREAD

**Issue by coyoteecd** [serverless/serverless#9212]
This issue is somewhat similar to #8150, but it occurs in a different context, without a nested stack.
Our app stack uses externally defined roles, referenced by ARN in function definitions. To avoid hardcoding the account, we've been using the serverless-pseudo-parameters plugin. I am trying to get rid of the plugin and replace it with native support of `${AWS::AccountId}`. This works fine for normal lambdas, but not for lambdas with SQS/SNS events attached.

<details>
<summary><code>serverless.yml (before)</code></summary>

```yaml
service: example
plugins:
  - serverless-pseudo-parameters

functions:
  myfunc:
    handler: handler.js
    role: arn:aws:iam::#{AWS::AccountId}:role/myfuncRunRole
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:#{AWS::AccountId}:someQueue
```

<summary><code>serverless.yml (after)</code></summary>

```yaml
service: example
functions:
  myfunc:
    handler: handler.js
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/myfuncRunRole
    events:
      - sqs:
          arn: !Sub arn:aws:sqs:us-east-1:${AWS::AccountId}:someQueue
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
[....]
Serverless: Validating template...

  Error --------------------------------------------------

  Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [IamRoleLambdaExecution] in the Resources block of the template
```

</details>

<b>Installed version</b>

```
Framework Core: 2.19.0 (local)
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

I believe the issue is in `resolveFunctionIamRoleResourceName` here: https://github.com/serverless/serverless/blob/0a84f1c84ee4e7ac32d9b5c247eba7f25da0d14a/lib/plugins/aws/provider.js#L1559-L1563

Adding an extra check like this would probably solve my problem:
```
if (customRole['Fn::Sub'] && typeof customRole['Fn::Sub'] === 'string' && customRole['Fn::Sub'].includes(':')) {
   // custom role is an expression containing an ARN
  return null;
}
```

If the above looks okay, I can send a PR for it.

**Comment by pgrzesik** [comment]
Hello @coyoteecd - that's a nice catch :+1: I think we don't have to go that deep with check and instead we could just verify if it has `Fn::Sub` property similar as we check of `Fn::Import` here: https://github.com/serverless/serverless/blob/0a84f1c84ee4e7ac32d9b5c247eba7f25da0d14a/lib/plugins/aws/provider.js#L1575

I don't think we should inspect the value of `Sub` further, because if it does not include `:` then we shouldn't pass silently and return the default role because I don't think that's the intention of someone passing invalid `Sub` value to `role` param. In such a case I believe we should rely on CloudFormation which will most likely error out during deployment due to an invalid role being passed. What do you think?

**Comment by coyoteecd** [comment]
Agree, I don't see a situation where one would use !Sub with anything else than a role name

**Comment by pratik-vii** [comment]
Hello! @pgrzesik 

My Config is like this.
```yml
service: example
functions:
  myfunc:
    handler: handler.js
    role: ${file(./config.json):ROLE}
    events:
      - sqs:
          arn: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:someQueue
```
The role is working fine here as I am not using `!Sub`, but it is breaking for sqs event arn.
in `compileSQSEvents` [here](https://github.com/serverless/serverless/blob/5601025dd8a4075cb463e2dcfb67d6c52984582a/lib/plugins/aws/package/compile/events/sqs.js#L69) as well. we will have to add `Fn::Sub` check as well.
