### ISSUE TITLE
Make it possible to specify the full TargetGroup name when using an ALB event

### ISSUE THREAD

**Issue by cbm-gplassard** [serverless/serverless#9213]
### Use case description

Hello, we would like to make the TargetGroup names more predictable / human readable when using AWS Lambda with ALB. There are several reasons for this but mostly because we would like to make the CloudWatch Metrics easier to use (when displayed on dashboards, when creating alarms, ...).

From what I understand today the name is created with a hash, even though it's possible to specify a common prefix. The prefix would not be enough for our use case since it is defined at the provider level.

Would it be possible to add a parameter to specify the full TargetGroup name when creating the event ?  It would then be the user's responsibility to ensure there are no duplicates. I'm not exaclty sure how it should behave in conjonction with the targetGroupPrefix.

### Proposed solution

```yml
functions:
  albEventConsumer:
    handler: handler.hello
    events:
      - alb:
          listenerArn: arn:aws:elasticloadbalancing:us-east-1:12345:listener/app/my-load-balancer/50dc6c495c0c9188/
          priority: 1
          targetGroupName: albEventConsumer-${opt:stage}
          conditions:
            path: /hello
```

Thank you !
