### ISSUE TITLE
SSM variables: referencing variables that are a SecureString that contain a stringified JSON fails

### ISSUE THREAD

**Issue by lassesteffen** [serverless/serverless#9217]
With the new variable resolution mode I get configuration errors when trying to reference a `Secure String` in SSM that contains a stringified JSON (for my google service account). An error is reported trying to decode that variable

<details>
<summary><code>serverless.yml</code></summary>

```yaml
...

frameworkVersion: '>=2.0.0'
configValidationMode: error

provider:
  stage: ${opt:stage, 'dev'}
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  memorySize: ${self:custom.variables.memorySize.${self:provider.stage}} # in MB, default is 1024
  environment:
    GOOGLE_SERVICE_ACCOUNT: ${ssm:/production/google-service-account~true}
...
```

</details>

<details>
<summary><b><code>
npx sls print     </code> output</b></summary>

```                                                                                                                                                                            5s  10:00:23
Serverless: Deprecation warning: Syntax for referencing SSM parameters was upgraded with automatic type detection and there's no need to add "~true" or "~split" postfixes to variable references.
            Drop those postfixes and set "variablesResolutionMode: 20210326" in your service config to adapt to a new behavior.
            Starting with next major release, this will be communicated with a thrown error.
            
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
 
 Serverless Error ----------------------------------------
 
  Configuration error: 
       at 'provider.environment.GOOGLE_SERVICE_ACCOUNT': unsupported configuration format
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.32.1 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.32.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```
