### ISSUE TITLE
Configuration warning at 'functions.s3ToEFS.events[0].s3.bucket': should be string

### ISSUE THREAD

**Issue by isaacpalomero** [serverless/serverless#9218]
When I try to deploy the SLS, the configuration validation print out this: 
`Configuration warning at 'functions.s3ToEFS.events[0].s3.bucket': should be string`

This is my code (partial):
```yaml
functions:
  s3ToEFS:
    handler: src/endpoints/s3ToEFS.handler
    timeout: 120
    vpc:
      securityGroupIds: ${file(env.yml):${self:custom.stage}.securityGroupIds}
      subnetIds: ${file(env.yml):${self:custom.stage}.subnetIds}
    events:
      - s3:
          bucket: !Ref InputToSapBucket
          event: s3:ObjectCreated:*
          existing: true
```

I've tried also this with the same warning:
```yaml
  bucket: !Join [ "", [ !Ref InputToSapBucket, "" ] ] 
```
