### ISSUE TITLE
Migrating from iamRoleStatement to iam.role.statement for s3 with * fails deployment because of regex validation

### ISSUE THREAD

**Issue by lassesteffen** [serverless/serverless#9219]
I get an error that the statementId is not set correctly after migration from using `iamRoleStatement` to `iam.role.statement`. Might be related to https://github.com/serverless/serverless/blob/c45f66117892e6f5948274288d7dda41f96dfe85/lib/plugins/aws/customResources/resources/s3/lib/permissions.js where only the `*` is filtered out, not the `/*`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: craftdrive-serverless
org: craftdrive
app: craftdrive

frameworkVersion: '>=2.0.0'

provider:
  stage: ${opt:stage, 'dev'}
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  memorySize: ${self:custom.variables.memorySize.${self:provider.stage}} # in MB, default is 1024
  versionFunctions: false
  iam:
    role:
      RoleName: MyCraftdriveServerlessLambdaRole
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource: '*'
        - Effect: 'Allow'
          Action:
            - 'SNS:Publish'
          Resource: '*'
        - Effect: 'Allow' # grant s3 permissions for file upload
          Action:
            - 's3:*'
          Resource: # Joins default s3 prefix with bucket name of stage
            - 'arn:aws:s3:::${self:custom.variables.s3Bucket.${self:provider.stage}}'
        - Effect: 'Allow' # grant s3 permissions
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::koppla-data-imports/*'

plugins:
  - serverless-domain-manager
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary
  - serverless-plugin-warmup
  - serverless-sentry
  - serverless-plugin-apollo-graphql-federation

useDotenv: true

custom:
  ...
  variables:
    s3Bucket: # bucket used for file upload
      dev: 'craftdrive-server-assets-dev/*'
      staging: 'craftdrive-server-assets-staging/*'
      prod: 'craftdrive-server-assets/*'
      ...

package:
  individually: true # create individual packages per function

functions:
  fileUploadedHandler:
    timeout: 40 # file resizing might take some time
    handler: src/handler/s3/index.handler
    events:
      - s3:
          bucket: ${self:custom.variables.s3Bucket.${self:provider.stage}}
          event: s3:ObjectCreated:*
          existing: true
          # TODO: consider prefix/suffix rule to reduce invocations
...
```

</details>

<details>
<summary><b><code> serverless --stage=staging deploy</code> output</b></summary>

```
Serverless: Deprecation warning: "serverless" command options are expected to follow command and not be put before the command.
            Starting from next major Serverless will no longer support the latter form.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_BEFORE_COMMAND
Serverless: Configuration warning at 'provider.iam.role': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: WarmUp: Skipping warmer "enabled" creation. No functions to warm up.
Serverless: WarmUp: Skipping warmer "prewarm" creation. No functions to warm up.
Serverless: Bundling with Webpack...
asset scripts/migrate.js 6.73 MiB [emitted] (name: scripts/migrate) 1 related asset
orphan modules 714 KiB [orphan] 201 modules
runtime modules 1.11 KiB 5 modules
modules by path ./node_modules/ 5.95 MiB 682 modules
modules by path ./src/ 704 KiB
  modules by path ./src/datastore/ 693 KiB 168 modules
  modules by path ./src/contracts/ 1.25 KiB 4 modules
  modules by path ./src/services/*.ts 2.99 KiB
    ./src/services/logger.ts 2 KiB [built] [code generated]
    ./src/services/dbLogger.ts 1010 bytes [built] [code generated]
  modules by path ./src/ioc/framework/*.ts 890 bytes
    ./src/ioc/framework/decorator.ts 479 bytes [built] [code generated]
    ./src/ioc/framework/collector.ts 411 bytes [built] [code generated]
  ./src/utils/config.ts 5.96 KiB [built] [code generated]
22 modules
webpack compiled successfully in 45010 ms
asset src/handler/customerImport.js 28.6 MiB [emitted] (name: src/handler/customerImport) 1 related asset
orphan modules 2.3 MiB [orphan] 738 modules
runtime modules 1.37 KiB 6 modules
javascript modules 22.2 MiB
  modules by path ./node_modules/ 20.7 MiB
    cacheable modules 20.7 MiB 2421 modules
    5 modules
  modules by path ./src/ 1.5 MiB 534 modules
json modules 5.9 MiB 637 modules
webpack compiled successfully in 125632 ms
asset src/handler/fileUploadCleaner.js 28.6 MiB [emitted] (name: src/handler/fileUploadCleaner) 1 related asset
orphan modules 2.3 MiB [orphan] 738 modules
runtime modules 1.37 KiB 6 modules
javascript modules 22.2 MiB
  modules by path ./node_modules/ 20.7 MiB
    cacheable modules 20.7 MiB 2421 modules
    5 modules
  modules by path ./src/ 1.5 MiB 534 modules
json modules 5.9 MiB 637 modules
webpack compiled successfully in 127494 ms
asset src/handler/leanStatusReminder.js 28.6 MiB [emitted] (name: src/handler/leanStatusReminder) 1 related asset
orphan modules 2.3 MiB [orphan] 738 modules
runtime modules 1.37 KiB 6 modules
javascript modules 22.2 MiB
  modules by path ./node_modules/ 20.7 MiB
    cacheable modules 20.7 MiB 2421 modules
    5 modules
  modules by path ./src/ 1.5 MiB 534 modules
json modules 5.9 MiB 637 modules
webpack compiled successfully in 128737 ms
asset src/handler/s3/index.js 28.6 MiB [emitted] (name: src/handler/s3/index) 1 related asset
orphan modules 2.3 MiB [orphan] 738 modules
runtime modules 1.37 KiB 6 modules
javascript modules 22.2 MiB
  modules by path ./node_modules/ 20.7 MiB
    cacheable modules 20.7 MiB 2421 modules
    5 modules
  modules by path ./src/ 1.5 MiB 536 modules
json modules 5.9 MiB 637 modules
webpack compiled successfully in 142127 ms
asset src/index.js 31.5 MiB [emitted] (name: src/index) 1 related asset
asset src/index_bg.wasm 755 KiB [emitted] [from: node_modules/@apollo/query-planner-wasm/dist/index_bg.wasm] (auxiliary name: src/index)
orphan modules 2.3 MiB [orphan] 738 modules
runtime modules 1.4 KiB 7 modules
modules by path ./node_modules/ 28.6 MiB
  javascript modules 22.6 MiB
    cacheable modules 22.6 MiB 2607 modules
    ./node_modules/typeorm/platform/ sync 160 bytes [built] [code generated]
    ./node_modules/typeorm/connection/ sync 160 bytes [built] [code generated]
    ./node_modules/typeorm/util/ sync 160 bytes [built] [code generated]
    ./node_modules/app-root-path/lib/ sync 160 bytes [built] [code generated]
    ./node_modules/type-graphql/dist/helpers/ sync 160 bytes [built] [code generated]
  json modules 5.99 MiB 645 modules
modules by path ./src/ 2.24 MiB 753 modules
31 modules
webpack compiled successfully in 157470 ms
Serverless: No external modules needed
(node:10258) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
Serverless: Copying existing artifacts...
Serverless: WarmUp: Skipping warmer "enabled" creation. No functions to warm up.
Serverless: WarmUp: Skipping warmer "prewarm" creation. No functions to warm up.
Serverless: Packaging service...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service customerImport.zip file to S3 (9.49 MB)...
Serverless: Uploading service fileUploadedHandler.zip file to S3 (9.5 MB)...
Serverless: Uploading service graphql.zip file to S3 (10.56 MB)...
Serverless: Uploading service fileUploadCleaner.zip file to S3 (9.49 MB)...
Serverless: Uploading service sendTrafficLightStatusReminder.zip file to S3 (9.49 MB)...
Serverless: Uploading service migrate.zip file to S3 (2.71 MB)...
Serverless: Uploading custom CloudFormation resources...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.............................
Serverless: Operation failed!
Serverless: View the full error output: https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aeu-central-1%3A113719728833%3Astack%2Fcraftdrive-serverless-staging%2F243abe80-b4a3-11ea-9c40-0264b9b54242
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: https://app.serverless.com/craftdrive/apps/craftdrive/craftdrive-serverless/staging/eu-central-1
 
 Serverless Error ----------------------------------------
 
  An error occurred: FileUploadedHandlerCustomS31 - Received response status [FAILED] from custom resource. Message returned: 1 validation error detected: Value 'craftdrive-serverless-staging-fileUploadedHandler-craftdrive-server-assets-staging/' at 'statementId' failed to satisfy constraint: Member must satisfy regular expression pattern: ([a-zA-Z0-9-_]+) See details in CloudWatch Log: 2021/04/01/[$LATEST]ffc0dc0dee074a33afc365d65df98b7b (RequestId: 28b8d06f-c950-4e18-9ac0-6b32c95d0250).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.4.0
     Framework Version:         2.31.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.1
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-graphql@2.17.0 deploy:staging: `cross-env NODE_ENV=production cross-env NODE_OPTIONS=--max_old_space_size=8192 serverless --stage=staging deploy && npm run db:migrate:remote --stage=staging`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-graphql@2.17.0 deploy:staging script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lassesteffen/.npm/_logs/2021-04-01T09_26_35_736Z-debug.log
```

</details>

<b>Installed version</b>

```
Framework Core: 2.31.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```
