### ISSUE TITLE
Layers showing warnings when using "package.patterns"

### ISSUE THREAD

**Issue by yhrabovskyinomi** [serverless/serverless#9221]
Q1: Layers were showing warnings to not use "include" and "exclude" in package, and when i changed that to "patterns" i can see configuration warning

Serverless: Configuration warning:
Serverless:   at 'layers.common.package': unrecognized property 'patterns'
Serverless:   at 'layers.deps.package': unrecognized property 'patterns'
Serverless:   at 'layers.resources.package': unrecognized property 'patterns'
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation

```

service: layers
variablesResolutionMode: 20210326
provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}

layers: 
  common:
    name: common
    path: ./common
    description: Common python lib
    compatibleRuntimes:
      - python3.8
    retain: true
    package:
      patterns:
        - './python/**'
```

Framework Core: 2.32.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
