### ISSUE TITLE
First time deploy to aws apigateway errors out with: Invalid tag key. Tag keys cannot start with 'aws:' (case insensitive)

### ISSUE THREAD

**Issue by mgresko** [serverless/serverless#9223]
First time deploy in aws api gateway fails creation with tagKey error on cloudformation aws: tags

When running serverless for the first time the deployment is failing when serverless is trying to reconcile tags on api gateway and it sees the AWS newly added aws:cloudformation:logical-id, aws:cloudformation:stage, aws:cloudformation:stack-name and then tries to remove them.  However, they are tags that are set by cloudformation and they cannot be added or removed outside of aws. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

Traced code to https://github.com/serverless/serverless/blob/c5ba682a6bc4fc96151c75cdf50cff2468d6def5/lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js#L319

Basically it needs to skip trying to remove any tag that starts with 'aws:'

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: python3.7
  stage: ${env:LABEL,'local'}
  versionFunctions: false
  memorySize: 512

stackTags:
    something: "no"

  customDomain:
    endpointType: regional
    domainName: "${ssm:/${env:LABEL}/infrastructure/something/domain_name~true}"
    stage: "${self:provider.stage}"
    certificateArn: "${ssm:/${env:LABEL}/infrastructure/dns/acm_wildcard_certificate/arn~true}"
    securityPolicy: tls_1_2

  stageSettings:
    MethodSettings:
      DataTraceEnabled: true
      HttpMethod: "*"
      LoggingLevel: "INFO"
      ResourcePath: "/*"
      MetricsEnabled: true

```

</details>

<details>
<summary><b><code>LABEL=blah sls deploy</code> output</b></summary>

```
...
  Serverless Error ---------------------------------------
 
  Invalid tag key. Tag keys cannot start with 'aws:' (case insensitive)
  ```

</details>

<b>1.83.2 and also exists with latest 2.x</b>

```
Serverless: Setting custom naming conventions...
Serverless: Setting custom function names...Framework Core: 1.83.2 (local)Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
