### ISSUE TITLE
Supporting SASL/SCRAM auth with MSK events

### ISSUE THREAD

**Issue by pedrocava** [serverless/serverless#9224]
### Use case description

There's an MSK cluster running with SASL auth. There's a backend producing events and a Serverless application listening to certain topics, using messages to trigger parametrized reactions, such as calling other lambda functions or uploading data to a DB. 

### Proposed solution

AWS has recently started supporting [SASL auth for MSK events](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-now-supports-sasl-scram-authentication-for-functions-triggered-from-amazon-msk/ ). Unfortunately, [this feature's documentation in CloudFormation is rather scarce](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-msk-cluster-clientauthentication.html).

Extending the convention @pgrzesik provided [here](https://github.com/serverless/serverless/issues/8117#issuecomment-679317363), we should have something like:

```
functions:
  compute:
    handler: handler.compute
    events:
      - msk:
          arn: arn:aws:kafka:region:XXXXXX:Cluster/xxx
          topic: kafka-topic
          startingPosition: LATEST
          batchSize: 1000
          saslScram512: arn:aws:secrets_manager:xxxxxxxxx
```

The ARN provided to `saslScram512` should be associated with the secret created during the SASL setup, described in more detail [here](https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html). Much like the `accessConfigurations` field in [`kafka` events works](https://github.com/serverless/serverless/blob/ff605018a70a7156b0ca021adb080a4b4e0f2ede/docs/providers/aws/events/kafka.md).
