### ISSUE TITLE
AppSync datasource variables are not resolved anymore

### ISSUE THREAD

**Issue by FabianEhringer** [serverless/serverless#9225]
Since I upgraded from serverless framework version `2.32.1`, variables in my AppSync datasource are not resolved anymore.
I'm not sure if this is a problem with the variable resolution in general or just together with an AppSync datasource.

```yaml
custom:
  ...

  httpEndpointBaseUrl: ${env:HTTP_ENDPOINT_BASE_URL}

  appSync:
    name: appsync-api
    ...
    dataSources:
      - type: HTTP
        name: HttpEndpoint
        config:
          endpoint: ${self:custom.httpEndpointBaseUrl}
  ...
```

The environment variables are resolved correctly (`custom.httpEndpointBaseUrl` contains the correct value), but the url for the HTTP request of the AppSync resolver looks like this: `$%7Bself:custom.httpEndpointBaseUrl%7D/rest/v1/`.

It has to be a serverless problem, because changing the serverless framework version back to `2.32.0` solves the problem.

**NOT working** with the following versions:
```
yarn global list --pattern serverless
yarn global v1.22.10
info "serverless@2.32.1" has binaries:
   - serverless
   - sls
 
yarn list --pattern serverless
yarn list v1.22.10
├─ serverless-appsync-plugin@1.8.0
├─ serverless-appsync-simulator@0.12.0
├─ serverless-deployment-bucket@1.4.1
├─ serverless-offline-sns@0.68.0
├─ serverless-offline@6.9.0
├─ serverless-plugin-modularize@1.0.9
└─ serverless-webpack@5.4.0
```

**working** with the following versions:
```
yarn global list --pattern serverless
yarn global v1.22.10
info "serverless@2.32.0" has binaries:
   - serverless
   - sls
 
yarn list --pattern serverless
yarn list v1.22.10
├─ serverless-appsync-plugin@1.8.0
├─ serverless-appsync-simulator@0.12.0
├─ serverless-deployment-bucket@1.4.1
├─ serverless-offline-sns@0.68.0
├─ serverless-offline@6.9.0
├─ serverless-plugin-modularize@1.0.9
└─ serverless-webpack@5.4.0
```
