### ISSUE TITLE
Cannot exclude all by default and exclude devDependencies with `package.patterns`

### ISSUE THREAD

**Issue by G-Rath** [serverless/serverless#9226]
#8581 deprecated `package.exclude` & `package.include` in favor of just `package.patterns`, but the way this is applied means we can't both exclude everything by default and take use of excluding dev dependencies, as including `node_modules` results in the dev dependencies all being added back.

This is what I had:

```
package:
  include:
    - ${self:custom.outDir}/**/*
    - package.json
  exclude:
    - '**/*'
    - '!node_modules/**'
    - '**/tsconfig*.json'
    - '**/*.d.ts'
    - '**/*.gradle'
    - '**/*.h'
    - '**/*.html'
    - '**/*.java'
    - '**/*.m'
    - '**/*.map'
    - '**/*.md'
    - '**/*.pbxproj'
    - '**/*.pem'
    - '**/*.podspec'
    - '**/*.ts'
    - '**/*.tsbuildinfo'
    - '**/*.txt'
    - '**/*.un~'
    - '**/*.xcworkspacedata'
    - '**/*.xml'
    - '**/*.yml'
```

This is it converted to `patterns`:

```
package:
  patterns:
    - '!**/*'
    - ${self:custom.outDir}/**/*
    - 'package.json'
    - 'node_modules/**'
    - '!**/tsconfig*.json'
    - '!**/*.d.ts'
    - '!**/*.gradle'
    - '!**/*.h'
    - '!**/*.html'
    - '!**/*.java'
    - '!**/*.m'
    - '!**/*.map'
    - '!**/*.md'
    - '!**/*.pbxproj'
    - '!**/*.pem'
    - '!**/*.podspec'
    - '!**/*.ts'
    - '!**/*.tsbuildinfo'
    - '!**/*.txt'
    - '!**/*.un~'
    - '!**/*.xcworkspacedata'
    - '!**/*.xml'
    - '!**/*.yml'
```

By excluding everything at the start, it means I don't have to manually list every file - i.e I recently added `.npmrc` to my project, which doesn't need to be in the package, and I don't have to change anything.

I also exclude a number of files that are in `node_modules` because these are not needed for the packages to function.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: my-app

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x

package:
  patterns:
    - '!**/*'
    - ${self:custom.outDir}/**/*
    - 'package.json'
    - 'node_modules/**'
    - '!**/tsconfig*.json'
    - '!**/*.d.ts'
    - '!**/*.gradle'
    - '!**/*.h'
    - '!**/*.html'
    - '!**/*.java'
    - '!**/*.m'
    - '!**/*.map'
    - '!**/*.md'
    - '!**/*.pbxproj'
    - '!**/*.pem'
    - '!**/*.podspec'
    - '!**/*.ts'
    - '!**/*.tsbuildinfo'
    - '!**/*.txt'
    - '!**/*.un~'
    - '!**/*.xcworkspacedata'
    - '!**/*.xml'
    - '!**/*.yml'
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
$ sls package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.32.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```
