### ISSUE TITLE
False positive for a "Configuration warning" relating CloudFront's path pattern

### ISSUE THREAD

**Issue by Chris1904** [serverless/serverless#9228]
CloudFront's path pattern allows for using `?` and `*` wildcard characters. But when using a pattern such as `pathPattern: /???/*`, which is a legit path, it throws this warning: 

```
Serverless:   at 'functions.OriginRequest.events[0].cloudFront.pathPattern': should match pattern "^([A-Za-z0-9_.*$/~"'@:+-]|&amp;)+$"
```

The issue is self-explanatory due to the warning. The path pattern allows for `?` but the generated warning has it failing because of it.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
  stage: ${opt:stage,'dev'}
  region: ${self:custom.settings.region}

functions:
  OriginRequest: # lambda@edge function used to validate the password if media has one
    handler: src/OriginRequest.handler
    runtime: nodejs12.x # edge only supports 12
    timeout: 5
    memorySize: 512
    role: LambdaEdgeRole
    events:
      - cloudFront:
          eventType: origin-request
          pathPattern: /???/*.jp*g
          origin: ${self:custom.origins.myApiGatewayOrigin}
          cachePolicy:
            name: meemaCachePolicy
          behavior:
            ViewerProtocolPolicy: redirect-to-https
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.31.0 (standalone)
Plugin: 4.5.2
SDK: 4.2.2
Components: 3.7.7
```
