### ISSUE TITLE
Use custom properties for CloudFormation Transforms with the Serverless schema validation

### ISSUE THREAD

**Issue by vorobievalex** [serverless/serverless#9243]
### Use case description

With the function definition schema validation enforced from v2.7.0, it is not possible to use custom properties handled by the company internal transforms.

The following example fails the schema validation due to the custom parameter "commonParameters". However, this parameter is expected by a [Transform macros](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-macros.html) installed in my account.
```
functions:
  under-newrelic-mntrng:
    handler: index.endpoint
    events:
      - http:
          path: test
          method: get
    commonParameters:
      - apiFunction

```

I am yet going to implement a 'fake' plugin with the sole purpose to [extend validation schema](https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#extending-validation-schema) with commonParameters.

Though, I believe there should be a more elegant integrated solution for this use case.

### Proposed solution

It might be allowed to extend the validation schema within the template itself. For example with the extension declaration in the custom block:
```
custom:
  schemaExtensions:
    functions: commonParameters

```
