### ISSUE TITLE
ssm variables not resolving in 2.33.1

### ISSUE THREAD

**Issue by s1mrankaur** [serverless/serverless#9245]
```

registration-service:  Serverless Information ----------------------------------
registration-service:
registration-service:   ############################################################################################
registration-service:     # 150007: 6 of 8 promises have settled
registration-service:     # 150007: 2 are taking longer than expected:
registration-service:     # 150007:   ssm:/cyc/apiKey waited on by: ${ssm:/cyc/apiKey}
registration-service:     # 150007:   ssm:/cyc/authtoken waited on by: ${ssm:/cyc/authtoken}
registration-service:     # This can result from latent connections but may represent a cyclic variable dependency
```

<details>
<summary><code>serverless.yml</code></summary>

Follows the relevant bit:
```yaml
  environment:
    cyc_apiKey: ${ssm:/cyc/apiKey}
    cyc_agent_lambda_debugger_auth_token: ${ssm:/cyc/authtoken}
```

</details>

sls deploy -v --stage sandbox
<details>
<summary><b><code></code> output</b></summary>

```
registration-service:  Serverless Information ----------------------------------
registration-service:
registration-service:   ############################################################################################
registration-service:     # 150007: 6 of 8 promises have settled
registration-service:     # 150007: 2 are taking longer than expected:
registration-service:     # 150007:   ssm:/cyc/apiKey waited on by: ${ssm:/cyc/apiKey}
registration-service:     # 150007:   ssm:/cyc/authtoken waited on by: ${ssm:/cyc/authtoken}
registration-service:     # This can result from latent connections but may represent a cyclic variable dependency
```

</details>

<b>Installed version</b>

```
$ serverless --version
Framework Core: 2.33.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1```

**Comment by pgrzesik** [comment]
Hello @s1mrankaur, thanks for reporting. Could you share a bit more about your issue? Did that started to occur after upgrading to `2.33.1` and worked fine on previous versions? Could you also share a bit more about your service configuration? Any other specific settings in `serverless.yml`?

**Comment by s1mrankaur** [comment]
@pgrzesik  This is happening when I run the SLS deploy commands from Lerna at the root for all services.  It started happening recently but happened before upgrading too.  

Follows more info from serverless.yml

```

service: registration-service
plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function
  - serverless-aws-documentation
  - serverless-stack-output
  - serverless-api-gateway-throttling
  - serverless-plugin-thundra

frameworkVersion: "2"
provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'sandbox'}
  # profile: ${opt:profile, 'viewlinc-sandbox'}
  profile: ${opt:profile}
  logRetentionInDays: 14
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - ${file(iam/logs-iam.yml):logsIAM}
    - ${file(../../shared/iam/x-ray-tracing-iam.yml):xRayIAM}

  environment:
     VARIABLES HERE
  apiKeys:
     KEYS HERE

functions: ${file(resources/sls-functions.yml)}


custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  bundle:
    tsConfig: "../../tsconfig.json"
  thundra:
    disable: ${self:custom.thundra_APM_disable.${self:provider.stage}}
  thundra_APM_disable:
    dev: true
    prod: true
    staging: true
    sandbox: true
  thundra_debugger_enable:
    dev: false
    prod: false
    staging: false
    sandbox: false
    other: false

```
