### ISSUE TITLE
Env file is not being deploy to Lambda

### ISSUE THREAD

**Issue by tipputhynhean** [serverless/serverless#9249]
After deploy to AWS, the env is not being deploy from `.env`

![image](https://user-images.githubusercontent.com/20786858/113704974-0d61a380-9707-11eb-9eb8-e672275a8e72.png)

<details>
<summary>
<code>
serverless.yml
</code></summary>

```yaml
service: testenv

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
```

</details>

<details>
<summary><b><code>.env</code> </summary>

```
TEST=true
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service testenv.zip file to S3 (569 B)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Stack update finished...
Service Information
service: testenv
stage: dev
region: us-east-1
stack: testenv-dev
resources: 6
api keys:
  None
endpoints:
  None
functions:
  hello: testenv-dev-hello
layers:
  None
```

</details>

<b>Installed version</b>

```
Framework Core: 2.33.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```
