### ISSUE TITLE
binary files download

### ISSUE THREAD

**Issue by joneldiablo** [serverless/serverless#9253]
I can't download any binary from the serverless project, I'm using express:

```
  const key = req.pathParams.path;
  try {
    const data = await s3.s3GetFileObject(BUCKET_URL + key);
    res.set({
      'content-type': data.ContentType,
      'content-disposition': 'inline; filename=' + key.split('/').pop(),
      'content-length': data.Body.length,
      'cache-control': 'private, no-cache, no-store, must-revalidate'
    });
    res.send(data.Body);
  } catch (error) {
    if (error.code === 'NoSuchKey') {
      res.status(404)
      return res.end();
    } else {
      console.log(error);
      return res.status(500).json({ error: true, description: error });
    }
  }
```
this works fine but the file downloaded always is corrupted, the files in bucket are ok.
if I store the file with `fs.writeFileSync('f*ckingFile',data.Body);`
the file is ok....... but the `res.send(data.Body)` always is corrupted. I have tryed  many ways, nothing working

============== and I have this other code:
```
      req.query.fields = ['id', 'uuid', 'xml', 'pdf'];
      const { data: rows } = await super.get(req, res, modelObject, true);
      const files = rows.reduce((files, row) => {
        if (row.xml.includes(BUCKET_URL))
          files.push([row.xml, row.uuid + '.xml']);
        if (row.pdf.includes(BUCKET_URL))
          files.push([row.pdf, row.uuid + '.pdf']);
        return files;
      }, []);
      const zip = await this.zipFromS3(files);
      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-disposition', `attachment; filename=${req.force.rfc}.zip`);
      res.setHeader('Content-Length', zip.length);
      res.end(zip);
```
the same thing is hapening here
the zip file is corrupted tooooooooooooooooooo but if I use fs.writeFileSync file is ok.
so
somthing is wrong with serverlesssssss or I have wrong configuration. mi serverless.yml file:
`````
service: validex-api-${self:provider.stage}

provider:
  versionFunctions: false
  name: aws
  endpointType: REGIONAL
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
    - "arn:aws:iam::438515322517:policy/startAndDownEc2"
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  memorySize: 128
  timeout: 30
  tags:
    app: ${self:custom.app}
    stage: ${self:provider.stage}
    country: ${self:custom.country}
  logRetentionInDays: 90
  apiGateway:
    minimumCompressionSize: 1024
    binaryMediaTypes:
      - '*/*'
  apiKeys:
    - ${self:provider.stage}-${self:service}
  usagePlan:
    quota:
      limit: 100000
      offset: 0
      period: MONTH
    throttle:
      burstLimit: 5000
      rateLimit: 10000
  environment:
    DOMAIN: ${ssm:/${self:provider.stage}/api/endpoint~true}
    #....... many variables
package:
  individually: true
  exclude:
    - "*/test/**"

plugins:
  # - serverless-webpack
  - serverless-plugin-split-stacks
  - serverless-api-gateway-caching
  - serverless-domain-manager
  - serverless-api-compression
  - serverless-offline
  - serverless-prune-plugin
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'
      - 'image/jpeg'
      - 'text/html'
      - 'application/pdf'
  webpack:
    packagePath: ./package.json
    includeModules: true
  module-name: 'validex'
  app: 'VALIDEX'
  country: 'MX'
  prune:
    automatic: true
    includeLayers: true
    number: 5
  allowed-headers:
    - Content-Type
    - X-Amz-Date
    - Access-Control-Allow-Origin
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - force
  customDomain:
    domainName: ${ssm:/${self:provider.stage}/api/endpoint~true}
    stage: ${self:provider.stage}
    createRoute53Record: true

  splitStacks:
    perFunction: true
    perType: false
  apiGatewayCaching:
    enabled: true #true
    clusterSize: '0.5'
    ttlInSeconds: 60
    perKeyInvalidation:
      requireAuthorization: false # default is true
      handleUnauthorizedRequests: Fail # default is "IgnoreWithWarn
  contentEncoding:
    contentCompression: 1000 # Minimum body size required for compression in bytes



functions:
 ###................... so many functions here
  session: ${file(./src/@session/serverless.yml)}
  users: ${file(./src/@users/serverless.yml)}
  files: ${file(./src/@files/serverless.yml)}

````
