### ISSUE TITLE
API Gateway minimumCompressionSize cannot be disabled

### ISSUE THREAD

**Issue by lemonJS** [serverless/serverless#9255]
**Issue:**

If you remove `providers.apiGateway.minimumCompressionSize` once it has been set, the compression remains active in API Gateway.

**Serverless.yaml:**
```yaml
service: test

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
```

**Command:**
```shell
$ serverless deploy
```

**Installed version:**
```shell
$ serverless --version
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.33.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.2
```

Removing this block and redeploying leaves compression enabled:
```yaml
# apiGateway:
#    minimumCompressionSize: 1024
```

![Screenshot 2021-04-07 at 11 49 01](https://user-images.githubusercontent.com/13802459/113855002-6da02600-9797-11eb-9ef8-4185afd66fea.png)
