### ISSUE TITLE
Layers are not being deployed correctly to lambda layers - release 2.34.0

### ISSUE THREAD

**Issue by abilani** [serverless/serverless#9262]
⚠️⚠️ REPLACE WITH DESCRIPTION

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# layers:
  base:
    path: ./layers/modules
    compatibleRuntimes:
      - nodejs12.x
    package:
      include:
        - node_modules/**
```

</details>

<b>2.34.0</b>
