### ISSUE TITLE
`custom-resource-apigw-cw-role` labmda func stage undefined

### ISSUE THREAD

**Issue by yeukfei02** [serverless/serverless#9268]
`sls deploy`..aws lambda `apigw-cw-role` func

the lambda func name show like this: `trello-clone-api-undefined-custom-resource-apigw-cw-role`

**serverless.yml**

```
org: yeukfei05
app: trello-clone-api
service: trello-clone-api

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1
  apiName: trello-clone-api-prod
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: production
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
    JWT_SECRET: ${param:JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: trello clone api prod
  lambdaHashingVersion: 20201221

functions:
  graphql:
    handler: src/graphql/handler.graphqlHandler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-prune-plugin
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-split-stacks

custom:
  prune:
    automatic: true
    number: 3
```
