### ISSUE TITLE
sls deploy fails to update stack for docker based lambda functions

### ISSUE THREAD

**Issue by jdupl123** [serverless/serverless#9276]
when calling `sls deploy` with an already deployed stack cloud formation update fails with error 
```
Resource handler returned message: "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:{function detain} (Service: Lambda, Status Code: 409, Request ID: {id}, Extended Request ID: null)" (RequestToken: {id}, HandlerErrorCode: GeneralServiceException)
```

this seems to be related to updating a docker based deploy.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: service_name
frameworkVersion: '2'
provider:
  name: aws
  stage: ${env:LAMBDA_STAGE}
  runtime: python3.6
  region: us-west-2
  timeout: 300
  memorySize: 192
  iam:
    role:
      statements:
          ** roles ***
  ecr:
    images: # Definitions of images that later can be referenced by key in `function.image`
      baseimage:
        path: ./ # Path to Docker context that will be used when building that image locally
        buildArgs:
          ** env ***

plugins:
  - serverless-prune-plugin
custom:
  prune:
    automatic: true
    # use PRUNE_N__${LAMBDA_STAGE} if it exists, otherwise PRUNE_N
    # this allows the use of a preproduction-specific setting
    number: ${env:PRUNE_N__${env:LAMBDA_STAGE}, env:PRUNE_N, '20'}


functions:
  funcName:
    image:
      name: baseimage
      command:
        - handlers.entry.funcName
    timeout: 300
    memorySize: 2048

```

</details>

<details>
<summary><b><code>sls deploy -r "${AWS_REGION_NAME}" --verbose</code> output</b></summary>

```
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - ********-v2-*******
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - ********-v2-*******
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_IN_PROGRESS - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function
CloudFormation - UPDATE_FAILED - AWS::Lambda::Function - ****Function

```

</details>

<b>Installed version</b>

```
Framework Core: 2.34.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.2
```
