### ISSUE TITLE
sls invoke local tries to build the java bridge if artifact is not defined

### ISSUE THREAD

**Issue by yyamano** [serverless/serverless#9279]
If package.artifact is not defined, sls invoke local tries to build the java bridge and looks hangup.

You can reproduce the problem:

1. Generate a java maven project by "sls create -t aws-java-maven"
2. Apply the following change.
3. sls invoke local -f hello

```
--- serverless.yml.orig	2021-04-09 18:45:34.000000000 +0900
+++ serverless.yml	2021-04-09 18:46:46.000000000 +0900
@@ -50,12 +50,14 @@
 #    variable1: value1
 
 # you can add packaging information here
-package:
-  artifact: target/hello-dev.jar
+#package:
+#  artifact: target/hello-dev.jar
 
 functions:
   hello:
     handler: com.serverless.Handler
+    package:
+      artifact: target/hello-dev.jar
 #    The following are a few example events you can configure
 #    NOTE: Please make sure to change your handler code to work with those events
 #    Check the event documentation for details
```
The problem comes from here. invokeLocalJava() tries to build the bridge with mvn if callJavaBridge() throws an exception.

https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/plugins/aws/invokeLocal/index.js#L635-L642

But callJavaBridge() throws an exception if the artifact doesn't exist.

https://github.com/serverless/serverless/blob/7072795a50ce87879089d41335641ac37d4abd09/lib/plugins/aws/invokeLocal/index.js#L574-L578

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-java-maven
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    package:
      artifact: target/hello-dev.jar
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - httpApi:
#          path: /users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

```

</details>

<details>
<summary><b><code>sls invoke local -f hello</code> output</b></summary>

```
% sls invoke local -f hello
Serverless: Building Java bridge, first invocation might take a bit longer.
```

</details>

<b>Installed version</b>

```
Framework Core: 2.34.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.2
```
