### ISSUE TITLE
Feature Request: use intrinsic functions in eventbridge detail pattern

### ISSUE THREAD

**Issue by DaveLo** [serverless/serverless#9293]
### Use case description

Was following along with this [AWS blog](https://aws.amazon.com/blogs/compute/using-dynamic-amazon-s3-event-handling-with-amazon-eventbridge/) for using cloudtrail to trigger eventbridge events on an S3 bucket (which is using SAM/CFN) and the event rule looks like 
```yaml
EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "EventRule"
      State: "ENABLED"
      EventPattern: 
        source: 
          - "aws.s3"
        detail: 
          eventName: 
            - "PutObject"
          requestParameters:
            bucketName: !Ref SourceBucketName
```

when trying this in serverless, using the new-ish CFN eventbridge integration, I ran into issues deploying this
```yaml
uploadHandler:
  handler: src/events/upload.handler;
  events:
    - eventBridge:
        pattern:
          source:
            - "aws.s3"
          detail-type:
            - AWS API Call via CloudTrail
          detail:
            eventName:
              - "PutObject"
            requestParameters:
              bucketName:
                - !Ref SourceBucketName
   ```
with an error
> An error occurred: {LongGeneratedName}EventBridgeRule - Event pattern is not valid. Reason: Unrecognized match type Ref

Looking at the config schema and the resolver it looks like the event pattern is passed directly through and stringified. I'm not sure looking at it if there is a way to implement my request from serverless, but it seems like if CFN/SAM can manage it there must be a way?

**Comment by pgrzesik** [comment]
Hello @DaveLo, thanks for reporting and linking to an article from AWS. I believe it might be a "leftover" from a still supported custom-resource backed support for EventBridge integration. Looking at one of the examples from the article it seems like CF supports intrinsic functions for patterns without issues, which suggests that we should be able support it as well. 

We'd be more than happy to accept a PR that introduces it, but please keep in mind that it might not be possible to support it if custom resource is used (we might still have people using the custom-resource backed integration).

**Comment by bboure** [comment]
I came across this issue today as well.

My use case

```yaml
    events:
      - eventBridge:
          pattern:
            account:
              - !Sub ${AWS::AccountId}
```

As @DaveLo mentioned, the [pattern is stringified](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/eventBridge/index.js#L411), which prevents CloudFormation to actually evaluate the values.

As per the [CloudFormation Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventpattern) Event Rules, Cloudformation accepts a JSON object (just look at the Example).

If I pass the Pattern directly as an Object (non stringified), it works as expected.

I haven't looked into it (yet), but I'm pretty sure that it won't be possible to support that if custom-resource is sued. However, I don't think this must be a blocker for this fix. This is a detail that might just be pointed out in the doc.

I'd be happy to open a PR if this solution is acceptable.


https://github.com/serverless/serverless/compare/master...bboure:fix/eventBridgeEventPattern?expand=1
