### ISSUE TITLE
AWS - API Gateway Authorizer - "CUSTOM" type error

### ISSUE THREAD

**Issue by uncodable** [serverless/serverless#9294]
When using the authorizer type as `CUSTOM` it will throw:
> Configuration warning at 'functions.health.events[0].http.authorizer.type': unsupported configuration format

This still successfully creates the AWS cloudformation template with the api gateway, however seems just a validation error, because the "CUSTOM" type is an actual gateway authorizer type.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  health:
    handler: handler.health
    events:
      - http:
          path: auth/health
          method: get
          cors:
            origin: '*'
            allowCredentials: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:service-gateway-${self:custom.stage}.ApiGatewayAuthorizerId}
```

</details>

<b>Installed version</b>

```
Framework Core: 2.33.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1
```

**Comment by pgrzesik** [comment]
Hello @uncodable, thanks for submitting your issue. Underneath, `CUSTOM` is not a valid authorizer type but rather a valid authorization method. `type` is translated to `Type` property of `AWS::ApiGateway::Authorizer` resource (reference docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html#cfn-apigateway-authorizer-type) while `CUSTOM` is a valid `AuthorizationType` property for `AWS::ApiGateway::Method` resource. 

The supported values for `authorizer.type` are as following (case insensitive):
- TOKEN 
- REQUEST
- COGNITO_USER_POOLS
- AWS_IAM

The first three are 1:1 types passed to `AWS::ApiGateway::Authorizer` while `AWS_IAM` serves as a convenience type, as for IAM no actual Authorizer resource needs to be created. It might work by chance with "type: CUSTOM", but it can also have some side-effects that I'm not aware of.

**Comment by uncodable** [comment]
Hey @pgrzesik,

Thanks for getting back to me.

Please see the CloudFormation event response (if you set the type to something other than a correct type FOOBAR etc):
>  An error occurred: ApiGatewayMethodAuthHealthGet - Invalid AuthorizationType specified. Valid options are NONE,AWS_IAM,CUSTOM,COGNITO_USER_POOLS,AWS_CROSS_ACCOUNT_IAM,JWT (Service: AmazonApiGateway; Status Code: 400; Error Code: BadRequestException; Request ID: REMOVED; Proxy: null).

**Comment by pgrzesik** [comment]
The error is for `AWS::ApiGateway::Method` property `AuthorizationType` - it is resolved internally based on authorizer type. Additionally, all possible values are not valid in all cases, as e.g. when ID of an existing authorizer is provided, you can only specify `CUSTOM` or `COGNITO_USER_POOLS`. I realise that it might be a bit confusing, but some of the concepts are hard to translate and here I guess decision has been made to rely only on actual `AWS::ApiGateway::Authorizer` types and properly translate them to `AuthorizationType` for `AWS::ApiGateway::Method`

**Comment by uncodable** [comment]
Thanks @pgrzesik is what I'm doing in the above example right to use an existing `CUSTOM` authorizer then in this use case? I have a service that generates api gateway & the authorizer etc, then I want it to use that existing authorizer. Appreciate you getting back to me, thanks in advance.

**Comment by pgrzesik** [comment]
Hey @uncodable - you should provide the same `type` as the authorizer you're providing has - please see the documentation: https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#share-authorizer

E.g. if the authorizer referenced by `authorizerId` is of `REQUEST` type, then provide `type: request`.

**Comment by uncodable** [comment]
Thanks for coming back to me @pgrzesik appreciate the help 👍🏻

**Comment by uncodable** [comment]
@pgrzesik I'm getting:

> An error occurred: ApiGatewayMethodAuthHealthGet - Invalid AuthorizationType specified. Valid options are NONE,AWS_IAM,CUSTOM,COGNITO_USER_POOLS,AWS_CROSS_ACCOUNT_IAM,JWT

It wont let me use `TOKEN` but works on deployment with `CUSTOM`

serverless.yml:
```yml
functions:
  health:
    handler: handler.health
    events:
      - http:
          path: auth/health
          method: get
          cors:
            origin: '*'
            allowCredentials: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:service-gateway-${self:custom.stage}.ApiGatewayAuthorizerId}
```
