### ISSUE TITLE
Schema validation missing for cloudwatchEvent?

### ISSUE THREAD

**Issue by masonjm** [serverless/serverless#9295]
I've created a new lambda using the `aws-ruby` template. When I try to add a cloudwatchEvent trigger I get validation warning:

```
Serverless: Configuration warning at 'functions.hello.events[0]': unsupported function event
```

Here's the serverless.yml:

```yaml
service: example-serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - cloudwatchEvent:
        event:
          source:
            - "aws.ec2"
          detail-type:
            - "EC2 Instance State-change Notification"
          detail:
            state:
              - pending
```

I think this is a valid config (it matches what's in the documentation and the template, at least). The documentation at https://www.serverless.com/framework/docs/configuration-validation/ makes me think a schema definition might be missing?

**Comment by pgrzesik** [comment]
Hello @masonjm - from what I see it's not a valid config, the properties for `cloudwatchEvent` are not indented properly. It should look like this:

```
(...)
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ec2"
            detail-type:
              - "EC2 Instance State-change Notification"
            detail:
              state:
                - pending
```

Let me know if that helps :bow:
