### ISSUE TITLE
Feature proposal: fail when duplicate resource IDs are detected

### ISSUE THREAD

**Issue by glb** [serverless/serverless#9299]
It would be great if the framework would detect and (warn | fail) when there are duplicate resource IDs in a service description.

### Use case description

Here's a (super-simplified) example of a problematic service. It takes advantage of the fact that Serverless lets you provide `resources` as an array of objects, which is super-useful for grouping things together. In this example it's easy to see that there is a collision, but if you think that each array item could be read in from a separate file, it can get tricky to make sure that you don't have collisions.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test

provider:
  name: aws

resources:
  - Resources:
      a:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: aTag
              Value: first

    # oops, collision!
  - Resources:
      a:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: aTag
              Value: second
```

</details>

When [`mergeArrays`](https://github.com/serverless/serverless/blob/19805d71eabb68bd7fd4046aa23090ef85fb1c36/lib/classes/Service.js#L206) merges the two entries in the `resources` array, you'll end up with a bucket with tags `aTag: second`.

### Proposed solution

I propose adding a new configuration item `provider.duplicateResourceBehavior` that will control what the framework does when it detects this situation.

The default behaviour would be to ignore the issue as the framework does today. If the value of `provider.duplicateResourceBehavior` is `warn`, the framework should emit a warning and continue with the merge. If the value of `provider.duplicateResourceBehavior` is `fail`, the framework should throw an error.

Examples:

<details>
<summary><code>serverless.yml</code> - <code>warn</code></summary>

```yaml
service: test

provider:
  name: aws
  duplicateResourceBehavior: warn

resources:
  - Resources:
      a:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: aTag
              Value: first

    # oops, collision!
  - Resources:
      a:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: aTag
              Value: second
```

</details>

Result:

```sh
% bin/serverless.js package
 
 Serverless Warning --------------------------------------
 
  Duplicate resource logical ID `a` found in resources!
```

<details>
<summary><code>serverless.yml</code> - <code>fail</code></summary>

```yaml
service: test

provider:
  name: aws
  duplicateResourceBehavior: fail

resources:
  - Resources:
      a:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: aTag
              Value: first

    # oops, collision!
  - Resources:
      a:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: aTag
              Value: second
```

</details>

Result:

```sh
% bin/serverless.js package
 
 
 Serverless Error ----------------------------------------
 
  Duplicate resource logical ID `a` found in resources!
```

If this proposal is accepted, I can provide a PR that patches `mergeArrays` with this behaviour. Thoughts?

**Comment by pgrzesik** [comment]
Hello @glb, thanks for your proposal. It sounds like a useful feature, when it comes to potential values I think we should stick to `warn` and `error` values to be consistent with e.g. `configValidationMode`, which supports `warn`, `error` and `off`. 

@medikoo What do you think about introducing such functionality?

**Comment by medikoo** [comment]
Thanks @glb for proposal.

We lean towards a generic solution that will allow to concat data from multiple sources, and which will replace `mergeArrays` functionality -> https://github.com/serverless/serverless/issues/8037 

So having that in might, I would no further tweak what we consider a legacy functionality, but focus on shipping that new solution, and in it unconditionally crash when two properties with same key are to be added to object.  To my understanding such scenario cannot be intentional, and can only be result of logic error. What do you think?

**Comment by glb** [comment]
@medikoo while I agree (again) that it would be great for the proposal in #8037 to be done, I don't see folks jumping in to implement it, and as I've commented before it's not something I think I'm competent to help with given my time constraints. I would agree that the behaviour of that new implementation would be great as you described it: crash when there's a collision. I'm not 100% clear on how it would work with this example:

<detail>
<summary><code>serverless.yml with !merge at top-level resources</code></summary>

```yaml
resources:
  !merge:
    - Resources:
        a:
          Type: AWS::S3::Bucket
          Properties:
            Tags:
              - Key: aTag
                Value: first

      # oops, collision!
    - Resources:
        a:
          Type: AWS::S3::Bucket
          Properties:
            Tags:
              - Key: aTag
                Value: second
```

</detail>

unless you are proposing this, perhaps?

<detail>
<summary><code>serverless.yml with !merge at second-level resources.Resources</code></summary>

```yaml
resources:
  Resources:
    !merge:
      - a:
          Type: AWS::S3::Bucket
          Properties:
            Tags:
              - Key: aTag
                Value: first

      # oops, collision!
      - a:
          Type: AWS::S3::Bucket
          Properties:
            Tags:
              - Key: aTag
                Value: second
```

</detail>

For now, our teams use the existing `mergeArrays` functionality extensively, and one recently had an outage as a result of a collision. You may consider it legacy functionality, but for us it's a core feature and extremely useful. I don't want to break backwards compatibility for existing folks, and I do want to put in a guardrail that helps folks like us avoid outages without having to rewrite all of our `serverless.yml` files to use a new mechanism. It's a lot easier to get a team to add `provider.duplicateResourceBehavior: error` to their YAML than it is to get them to restructure their `resources`, and I've got several teams each with many services.

I have a branch that implements what I've proposed, has tests, and it would take a small number of minutes to adjust it based on @pgrzesik 's suggestions.

Thoughts?
