### ISSUE TITLE
Request validators model, Value of property RestApiId must be of type String

### ISSUE THREAD

**Issue by MarcWadai** [serverless/serverless#9305]
Hi,
I am using this version of serverless 
```
Framework Core: 1.77.1
Plugin: 3.6.18
SDK: 2.3.1
Components: 2.33.2
```

Because I hit the hard limit of 20 requests validators, so I used the model to reuse some schemas. But then i got this error :
`Value of property RestApiId must be of type String`.

This is my code in my serverless.yml : 
```
provider:
  name: aws
  runtime: nodejs12.x
  ...
  apiGateway:
    restApiId: ${env:REST_ID}
    restApiRootResourceId: ${env:ROOT_RESSOURCE_ID}
    request:
      schemas:
        item-visibility:
          schema: ${file(./documentation/request/itemVisibility.json)}
          name: ItemVisibility
```

I am doing something wrong ?
