### ISSUE TITLE
CLI function deployment bug

### ISSUE THREAD

**Issue by joebernard** [serverless/serverless#9315]
When trying to redeploy an existing lambda using `serverless deploy function -f myFunction`, serverless packages it but then attempts to upload a different function. It fails to find the package and errors.

In the below example, I try to upload the lambda `saveComment`. It packages `saveComment` but then attempts to upload `savePost` (another one of my lambdas). Since that wasn't packaged, it fails. This happens with any lambda I try to upload individually. Deploying everything with `serverless deploy` does work.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: myorg
app: my-app

service: myapp

plugins:
  - serverless-plugin-split-stacks
  - serverless-webpack
  - serverless-plugin-aws-alerts
package:
  individually: true
configValidationMode: warn
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  lambdaHashingVersion: 20201221
  iam:
    role: ${output:junctureresources.LambdaExecutionRoleArn}
  webpack:
    packager: yarn # Packager that will be used to package your external modules
    webpackConfig: ./webpack.config.js # Name of webpack configuration file
functions:
  - ${file(serverless/lambdas.yml)}
```

</details>

<details>
<summary><b><code>serverless deploy function -f saveComment</code></b></summary>

```
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessWebpack for "out"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Bundling with Webpack...
Build completed in 2.296s

asset src/services/saveComment/index.js 1.93 MiB [emitted] [big] (name: src/services/saveComment/index)
orphan modules 303 KiB [orphan] 160 modules
runtime modules 1.04 KiB 5 modules
cacheable modules 1.64 MiB 310 modules
optional modules 3.29 KiB [optional]
  ./node_modules/moment/locale/ sync ^\.\/.*$ 3.21 KiB [optional] [built] [code generated]
  external "bufferutil" 42 bytes [optional] [built] [code generated]
  external "utf-8-validate" 42 bytes [optional] [built] [code generated]
16 modules
webpack 5.33.2 compiled successfully in 2295 ms
Serverless: Copying existing artifacts...
 
 Error ---------------------------------------------------
 
  Error: ENOENT: no such file or directory, copyfile '/opt/projects/myapp/myapp-lambda/.webpack/savePost.zip' -> '.serverless/savePost.zip'
      at Object.copyFileSync (fs.js:1907:3)
      at ServerlessWebpack.copyArtifactByName (/opt/projects/myapp/myapp-lambda/node_modules/serverless-webpack/lib/packageModules.js:86:6)
      at /opt/projects/myapp/myapp-lambda/node_modules/serverless-webpack/lib/packageModules.js:133:66
      at arrayEach (/opt/projects/myapp/myapp-lambda/node_modules/lodash/lodash.js:530:11)
      at Function.forEach (/opt/projects/myapp/myapp-lambda/node_modules/lodash/lodash.js:9410:14)
      at ServerlessWebpack.copyExistingArtifacts (/opt/projects/myapp/myapp-lambda/node_modules/serverless-webpack/lib/packageModules.js:133:9)
      at ServerlessWebpack.tryCatcher (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/opt/projects/myapp/myapp-lambda/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

</details>

<b>Installed version</b>

```
Framework Core: 2.35.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.2
```
