### ISSUE TITLE
Wrong configuration warning on logRetentionInDays with SSM param

### ISSUE THREAD

**Issue by luigidragone96** [serverless/serverless#9317]
Hi,
I have encountered validation problems in the field logRetentionInDays under provider when using an ssm parameter.

For example:
`logRetentionInDays: ${ssm:/lambda/log-retention-in-days}`

Generate this warning:
`Configuration warning at 'provider.logRetentionInDays': should be equal to one of the allowed values`

The SSM parameter contain a valid value for logRetentionInDays (1).
I use the last version of serverless framework.

**Comment by pgrzesik** [comment]
Hello @luigidragone96, thanks for reporting. Could you post the output of `sls print` command (with any sensitive parts hidden)?



Also, for the next time, could you please follow the issue template that is visible when you start creating a new issue?

**Comment by medikoo** [comment]
@pgrzesik it might be that coercion is not applied to enum values, and we expect there number, while SSM resolves with a string.

If that's the case, we can introduce `toNumber` variable source (as e.g. have `strToBool`) to help address such use case

**Comment by pgrzesik** [comment]
@medikoo I thought that as well, but I simply tested locally with string values e.g. `logRetentionInDays: '1'` and there were no schema errors present, which was a bit surprising.

**Comment by luigidragone96** [comment]
> Hello @luigidragone96, thanks for reporting. Could you post the output of `sls print` command (with any sensitive parts hidden)?
> 
> Also, for the next time, could you please follow the issue template that is visible when you start creating a new issue?

Sorry for the missing template, for the next time i will follow the issue template!

Appears that the SSM parameter is inserted as a string. In AWS the parameter is simply `1` without any quotes.
This is the complete output of `sls print` command:
```
service:
  name: login
frameworkVersion: '2'
provider:
  stage: dev
  region: eu-south-1
  name: aws
  runtime: nodejs12.x
  profile: dev-profile
  logRetentionInDays: '1'
  lambdaHashingVersion: '20201221'
  deploymentBucket: ####HIDDEN####
  deploymentPrefix: login
  versionFunctions: true
  deploymentBucketObject:
    name: ####HIDDEN####
  variableSyntax: '\${([^{}:]+?(?:\(|:)(?:[^:{}][^{}]*?)?)}'
package:
  individually: true
functions:
  cognito-custom-email:
    handler: ####HIDDEN####
    memorySize: 256
    environment:
      sesRegion: eu-west-1
    events: []
    name: ####HIDDEN####
plugins:
  - serverless-bundle
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
custom:
  defaultStage: dev
  profiles:
    dev: dev-profile
    prod: prod-profile
  bundle:
    linting: false
  prune:
    automatic: true
    number: 3
```

**Comment by pgrzesik** [comment]
Thanks for sharing @luigidragone96 - could you please still follow the initial template and share a minimal reproducible example if possible? I've tried to replicate it with different scenarios, and e.g. the following:
```
service: testing-service

configValidationMode: 'error'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-south-1
  lambdaHashingVersion: '20201221'
  logRetentionInDays: ${ssm:/lambda/test-param}

functions:
  function1:
    handler: handler.hello
    events:
      - httpApi: '*'
```

does not result in an error and properly resolves the `logRetentionInDays` property. When I change to e.g. `111` which is not a valid value, it correctly errors out. Maybe there's something specific to your config that I'm missing in my repro example
