### ISSUE TITLE
sls offline not working anymore with 2.36.0

### ISSUE THREAD

**Issue by Gummy47** [serverless/serverless#9333]
Hi there,

I'm having an issue here with the latest version 2.36.0.
When running `sls offline`, I get the following error :

```
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:125:11)
      at Object.relative (path.js:492:5)
      at getWebpackConfigPath (C:\git\xkinvest\awsxk\node_modules\serverless-bundle\index.js:10:15)
      at applyWebpackOptions (C:\git\xkinvest\awsxk\node_modules\serverless-bundle\index.js:21:20)
      at ServerlessPlugin.<anonymous> (C:\git\xkinvest\awsxk\node_modules\serverless-bundle\index.js:89:7)
      at PluginManager.invoke (C:\Users\PC-DEV-001\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:552:20)
      at PluginManager.spawn (C:\Users\PC-DEV-001\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:574:16)
      at ServerlessPlugin.prepareOfflineInvoke (C:\git\xkinvest\awsxk\node_modules\serverless-webpack\lib\prepareOfflineInvoke.js:15:42)
      at ServerlessPlugin.tryCatcher (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
```

This used to work fine with previous version 2.35.0, so I'll stick to that one for now.
Given that I have no idea where to look for clues, I figured I'd reach out here to let you know of the issue.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: xxx
app: xxx
org: xxx

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: xxx
  region: eu-west-3

  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action: 
        - ec2:CreateNetworkInterface
        - ec2:DeleteNetworkInterface
        - ec2:DescribeNetworkInterfaces
    - Effect: Allow
      Resource: "*"
      Action: 
        - elasticfilesystem:ClientMount
        - elasticfilesystem:ClientRootAccess
        - elasticfilesystem:ClientWrite
        - elasticfilesystem:DescribeMountTargets

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  bundle:
    linting: false
    externals:
      - better-sqlite3
    caching: false
    forceExclude:                   # Don't include these in the package
      - aws-sdk

functions:
  testfile:
    handler: testfile.testfile
    events:
      - http:
          path: testfile
          method: post
          cors: true
    vpc:
      securityGroupIds: 
        - xxx
      subnetIds:
        - xxx
        - xxx
    fileSystemConfig:
      localMountPath: /mnt/efs
      arn: xxx

  medieval:
    handler: handler.handler
    events:
      - http: 
          method: any
          path: api/
      - http:
          method: any
          path: 'api/{proxy+}'
    vpc:
      securityGroupIds: 
        - xxx
      subnetIds:
        - xxx
        - xxx
    fileSystemConfig:
      localMountPath: /mnt/efs
      arn: xxx

resources:
  Resources:
    AccessPointResource:
      Type: "AWS::EFS::AccessPoint"
      Properties:
        FileSystemId: fs-853b1c34
        PosixUser:
          Uid: "1000"
          Gid: "1000"
        RootDirectory:
          CreationInfo:
            OwnerUid: "1000"
            OwnerGid: "1000"
            Permissions: "0777"
          Path: "/efs"

```

</details>

<details>
<summary><b><code>sls offline</code> output</b></summary>

```
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessPlugin for "out"
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache", "dockerHost", "dockerHostServicePath", "dockerNetwork"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
            More Info: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2

 Type Error [ E R R_ I N V A L I D_ A R G_ T Y P E] ------

  TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:125:11)
      at Object.relative (path.js:492:5)
      at getWebpackConfigPath (C:\git\xkinvest\awsxk\node_modules\serverless-bundle\index.js:10:15)
      at applyWebpackOptions (C:\git\xkinvest\awsxk\node_modules\serverless-bundle\index.js:21:20)
      at ServerlessPlugin.<anonymous> (C:\git\xkinvest\awsxk\node_modules\serverless-bundle\index.js:89:7)
      at PluginManager.invoke (C:\Users\PC-DEV-001\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:552:20)
      at PluginManager.spawn (C:\Users\PC-DEV-001\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:574:16)
      at ServerlessPlugin.prepareOfflineInvoke (C:\git\xkinvest\awsxk\node_modules\serverless-webpack\lib\prepareOfflineInvoke.js:15:42)
      at ServerlessPlugin.tryCatcher (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues (C:\git\xkinvest\awsxk\node_modules\bluebird\js\release\async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.22.0
     Framework Version:         2.36.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.3
```

</details>

<b>Installed version</b>

```
Framework Core: 2.36.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3
```

Thanks for your attention. If you need additional details, please ask.
