### ISSUE TITLE
aws-node-express-dynamodb-api is not deployable

### ISSUE THREAD

**Issue by sydetion** [serverless/serverless#9335]
- Used create app in app.serverless.com to create a aws-node-express-dynamodb-api application.
- Added AWS credentials
- followed instructions leads to following issue

<details>
<summary><code>serverless.yml</code></summary>

```yaml
org: bluewire
app: test1
service: test1

frameworkVersion: '2'

custom:
  tableName: 'users-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Serverless: Using provider credentials, configured via dashboard: https://app.serverless.com/bluewire/apps/test1/test1/dev/us-east-1/providers

 Type Error ----------------------------------------------

  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      at validateString (internal/validators.js:124:11)
      at Object.join (path.js:375:7)
      at wrap (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\node_modules\@serverless\enterprise-plugin\lib\wrap.js:344:31)
      at ServerlessEnterprisePlugin.<anonymous> (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\node_modules\@serverless\enterprise-plugin\lib\plugin.js:444:17)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async PluginManager.invoke (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\lib\classes\PluginManager.js:552:9)
      at async PluginManager.spawn (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\lib\classes\PluginManager.js:574:5)
      at async Object.before:deploy:deploy [as hook] (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\lib\plugins\deploy.js:49:11)
      at async PluginManager.invoke (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\lib\classes\PluginManager.js:552:9)
      at async PluginManager.run (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\lib\classes\PluginManager.js:598:7)
      at async Serverless.run (C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\lib\Serverless.js:312:5)
      at async C:\Users\Tobias.Hocke\AppData\Local\nvs\node\14.16.0\x64\node_modules\serverless\scripts\serverless.js:612:9
```

</details>

<b>Installed version</b>

```
Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.0
     Framework Version:         2.36.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.3

serverless --version
Framework Core: 2.36.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3
```
