### ISSUE TITLE
Invoke local with aws-nodejs-typescript template not working: TypeError: core_1.default is not a function

### ISSUE THREAD

**Issue by guifel** [serverless/serverless#9342]
Invoke local on the base aws nodeJS typscript template does not work. 
```
serverless create --template aws-nodejs-typescript
npm i --dev
npx sls invoke local -f hello --path src/functions/hello/mock.json
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
import type { AWS } from '@serverless/typescript';

import hello from '@functions/hello';

const serverlessConfiguration: AWS = {
  service: 'abc',
  frameworkVersion: '2',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true,
    },
  },
  plugins: ['serverless-webpack'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
    },
    lambdaHashingVersion: '20201221',
  },
  // import the function via paths
  functions: { hello },
};

module.exports = serverlessConfiguration;

```

</details>

<details>
<summary><b><code>npx sls invoke local -f hello --path src/functions/hello/mock.json</code></b></summary>

```
felley@XPS:~/Documents/tmp/abc$ npx sls invoke local -f hello --path src/functions/hello/mock.json
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessWebpack for "out"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Deprecation warning: Starting with next major version, "http.request.schema" property will be replaced by "http.request.schemas".
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_SCHEMAS
Serverless: Bundling with Webpack...
asset src/functions/hello/handler.js 10.7 KiB [emitted] (name: src/functions/hello/handler)
runtime modules 937 bytes 4 modules
built modules 803 bytes [built]
  cacheable modules 677 bytes
    ./src/functions/hello/handler.ts 348 bytes [built] [code generated]
    ./src/libs/apiGateway.ts 137 bytes [built] [code generated]
    ./src/libs/lambda.ts 192 bytes [built] [code generated]
  modules by path external "@middy/ 84 bytes
    external "@middy/core" 42 bytes [built] [code generated]
    external "@middy/http-json-body-parser" 42 bytes [built] [code generated]
  external "source-map-support/register" 42 bytes [built] [code generated]
webpack compiled successfully in 136 ms
TypeError: core_1.default is not a function
    at Object.middyfy (/home/felley/Documents/tmp/abc/src/libs/lambda.ts:5:15)
    at Object.<anonymous> (/home/felley/Documents/tmp/abc/src/functions/hello/handler.ts:16:21)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module.m._compile (/home/felley/Documents/tmp/abc/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (/home/felley/Documents/tmp/abc/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:745:33)
    at AwsInvokeLocal.invokeLocal (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:222:19)
    at Object.invoke:local:invoke [as hook] (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:49:47)
    at PluginManager.invoke (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/classes/PluginManager.js:552:20)
    at PluginManager.run (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/classes/PluginManager.js:598:7)
    at Serverless.run (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/Serverless.js:313:5)
    at /home/felley/Documents/tmp/abc/node_modules/serverless/scripts/serverless.js:612:9
 
 Error ---------------------------------------------------
 
  Error: Exception encountered when loading /home/felley/Documents/tmp/abc/src/functions/hello/handler
      at AwsInvokeLocal.invokeLocalNodeJs (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:749:13)
      at AwsInvokeLocal.invokeLocal (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:222:19)
      at Object.invoke:local:invoke [as hook] (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:49:47)
      at PluginManager.invoke (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/classes/PluginManager.js:552:20)
      at PluginManager.run (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/classes/PluginManager.js:598:7)
      at Serverless.run (/home/felley/Documents/tmp/abc/node_modules/serverless/lib/Serverless.js:313:5)
      at /home/felley/Documents/tmp/abc/node_modules/serverless/scripts/serverless.js:612:9
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              15.11.0
     Framework Version:         2.37.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.37.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```
