### ISSUE TITLE
Variables not resolving correctly

### ISSUE THREAD

**Issue by manuelaguirre** [serverless/serverless#9348]
We have a json file in our repository that holds every path to SSM variables in our AWS parameter store. We then import them in the `serverless.yml` file referencing their relative paths. It worked just fine until yesterday.  When we run `sls deploy` these variables don't get parsed correctly and instead the ssm path string gets loaded into the Cloudformation stack (not the value stored in said ssm variables). 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: service-name

plugins:
  - serverless-bundle
  - serverless-deployment-bucket
  - serverless-offline

frameworkVersion: '2'

package:
  individually: true

custom:
  apiVersion: '**'
  bundle:
    aliases:
      -**
      -**

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, '****'}
  apiGateway:
    restApiRootResourceId: ****
    restApiId: ****
    restApiResources:
      /**: ****
  runtime: nodejs12.x
  deploymentBucket:
    name: ****
    # serverSideEncription: AES256
    maxPreviousDeploymentArtifacts: 5
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ****
        - ****
        - ****
        - ****
        - ****
        - ****
      Resource: ****'
    - Effect: Allow
      Action:
        - ****
        - ****
      Resource: ****
    - Effect: Allow
      Action:
        - ****
      Resource: 
      - '****'
  environment:
    AWS_ENVIRONMENT_REGION: ${opt:region, ****}
    DATABASE_CONNECTION_URI: ${${file(./settings/${opt:stage, self:provider.stage, 'dev'}.settings.json):DATABASE_CONNECTION_URI}}
    ENV_VAR: ${${file(./settings/${opt:stage, self:provider.stage, '***'}.settings.json):ENV_VAR}}
    ENV_VAR2: ${${file(./settings/${opt:stage, self:provider.stage, '***'}.settings.json):ENV_VAR2}}
    ENV_VAR3: ${${file(./settings/${opt:stage, self:provider.stage, '***'}.settings.json):ENV_VAR3}}

functions:
  ***:
    handler: src/handlers/***.handle
    events:
      - http:
          path: ${self:custom.apiVersion}/***/***
          method: POST
          cors: true
  ***:
    handler: src/handlers/***.handle
    events:
      - http:
          path: ${self:custom.apiVersion}/***/***
          method: PUT
          cors: true
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessPlugin for "out"
             - ServerlessOffline for "apiKey", "corsAllowHeaders", "corsAllowOrigin", "corsDisallowCredentials", "corsExposedHeaders", "disableCookieValidation", "enforceSecureCookies", "hideStackTraces", "host", "httpPort", "httpsProtocol", "lambdaPort", "noPrependStageInUrl", "noAuth", "ignoreJWTSignature", "noTimeout", "prefix", "printOutput", "resourceRoutes", "useChildProcesses", "useWorkerThreads", "websocketPort", "webSocketHardTimeout", "webSocketIdleTimeout", "useDocker", "layersDir", "dockerReadOnly", "functionCleanupIdleTimeSeconds", "allowCache", "dockerHost", "dockerHostServicePath", "dockerNetwork"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
            More Info: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Using deployment bucket '****'
Serverless: Bundling with Webpack...


Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: Excluding external modules: aws-sdk
Serverless: No external modules needed
Serverless: Copying existing artifacts...
Serverless: Packaging service...
Serverless: Using deployment bucket '****'
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service ****.zip file to S3 (1020.88 KB)...
Serverless: Uploading service ****.zip file to S3 (1020.66 KB)...
Serverless: Validating template...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
......
Serverless: Operation failed!
Serverless: View the full error output: ****
 
 Serverless Error ----------------------------------------
 
  An error occurred: ApiGatewayResourceV1 - Invalid API identifier specified ***:${ssm:/****~true} (Service: AmazonApiGateway; Status Code: 404; Error Code: NotFoundException; Request ID: e3b5a6c5-20bd-4ff7-a401-8338f745ac51; Proxy: null).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.1
     Framework Version:         2.37.1 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.0
 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

</details>

<b>Installed version</b>

```
 2.37.1 (local)
```

**Comment by colforbin13** [comment]
I've been seeing similar issues all day today. I can set `configValidationMode: off` and it works, but this has been working until today, what am I missing?

relevant serverless.yml file portion
```
service: OurServiceNameHere

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  stackName: ${self:service}
```

Error from running serverless deploy
```
Configuration error: 
       at 'provider.region': should be equal to one of the allowed values [us-east-1, us-east-2, us-gov-east-1, us-gov-west-1, us-west-1, us-west-2, af-south-1, ap-east-1, ap-northeast-1, ap-northeast-2, ap-northeast-3, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, cn-north-1, cn-northwest-1, eu-central-1, eu-north-1, eu-south-1, eu-west-1, eu-west-2, eu-west-3, me-south-1, sa-east-1]
       at 'provider.stackName': should match pattern "^[a-zA-Z][a-zA-Z0-9-]*$"
```

**Comment by medikoo** [comment]
@manuelaguirre I think I know where's the issue. Technically it worked by side effect for you.

I suspect that your current configuration shares constructs similar to below:

_settings.json_

```json
{  "DATABASE_CONNECTION_URI": "ssm:key" }
```

_serverless.yml_

```yaml
provider:
  environment:
    DATABASE_CONNECTION_URI: ${${file(./settings.json):DATABASE_CONNECTION_URI}}
```

Above won't work with recent version, as we no longer follow up with variable resolution on strings which are a result of concatenation of strings coming from different sources (as that can introduce unwanted side effect, and e.g. will make eventual escapes as `\${` ineffective)

In this case what ends in `provider.environment.DATABASE_CONNECTION_URI` is a string concatenated of three parts: `${`, (resolved `${file: ..}` variable), and `}`, And that result in not put back to variable resolution machinery.

To have this work right, ensure that variable references are not constructed by multiple sources in multiple location (that's definitely an anti-pattern). 

In this case you should be able to easily fix it by reconfiguring notation to:

_settings.json_

```json
{  "DATABASE_CONNECTION_URI": "${ssm:key}" }
```

_serverless.yml_

```yaml
provider:
  environment:
    DATABASE_CONNECTION_URI: ${file(./settings.json):DATABASE_CONNECTION_URI}
```
