### ISSUE TITLE
iam resource per function

### ISSUE THREAD

**Issue by esteveslima** [serverless/serverless#9349]
Currently, the [iam documentation](https://www.serverless.com/framework/docs/providers/aws/guide/iam#custom-iam-roles-for-each-function) implies a quite big configuration to define a iam role for each function, requiring the creation of an entire resource configuration only to add an extra permission. 
Would be possible to have an easier configuration as syntax sugar for the creation of a new iam role(with extra permissions) to the function?
E.g.:

This:
```
someFuntion:
  handler: "..."
  role:
    name: roleName
    statements:
    - Effect: Allow
      Action:
      - s3:PutObject
      Resource: arn:...
```

Would result on something like the following behind the scenes(the new role would be created automatically with the default + new permissions):

```
someFuntion:
  handler: "..."
  role: roleName
  dependsOn:
  - roleName
```
