### ISSUE TITLE
Output collision when deploying a split service into the same bucket

### ISSUE THREAD

**Issue by TMiNus** [serverless/serverless#9361]
Due to #9313, the name of the bucket where the deployment occurred is being exported by default. If a service is divided into multiple files deploying to the same bucket, the default outputs are gonna conflict with each other. 

<details>
<summary><code>serverless_A.yml</code></summary>

```yaml
service: lol

useDotenv: true

provider:
  name: aws
  runtime: dotnetcore3.1
  stage: dev
  stackName: stack-A
  deploymentBucket:
    name: bucket
  deploymentPrefix: prefix

functions:
  FunctionA:
    .....
```

</details>

<details>
<summary><code>serverless_B.yml</code></summary>

```yaml
service: lol

useDotenv: true

provider:
  name: aws
  runtime: dotnetcore3.1
  stage: dev
  stackName: stack-B
  deploymentBucket:
    name: bucket
  deploymentPrefix: prefix

functions:
  FunctionB:
    .....
```
</details>

<b>Installed version</b>

```
Framework Core: 2.38
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```

**Comment by pgrzesik** [comment]
Hello @TMiNus, is this an actual behavior that you're observing in your use case? Are you using some kind of plugin that allows setup as above? Because if you do your deployments as in above, with the exact same `service` set in separate `serverless.yml` files, then both deploys will be updating the same CloudFormation stack. In you example, if you deploy like this:

```
sls deploy --config serverless_A.yml
sls deploy --config serverless_B.yml
```

then your stack will only have `FunctionB` defined.

Could you please share a reproducible example of issue that you're observing + follow the issue template that is visible when you create a new issue (especially the output of the command with error).

**Comment by TMiNus** [comment]
Hello @pgrzesik, thanks for answering. I am not using any plugin, I just have a service that is logically divided into multiple Folders. My current setup is just going to each one of those folders doing

`sls deploy --stage dev `

**Comment by pgrzesik** [comment]
But if you do it this way, with the same `service` defined in each `serverless.yml` file then all these deploys will alter the same CloudFormation stack, which in the end will make only the last deployment effective (as all previous updates will be undone by last deploy). Am I missing something in your setup?

**Comment by TMiNus** [comment]
I have updated `serverless_A.yml` and `serverless_B.yml` to reflect those are two separate stacks.

**Comment by TMiNus** [comment]
The way I read the merge request, I see two ways to accommodate my current use case

Solution One:
Exten

**Comment by pgrzesik** [comment]
Thanks for clarification @TMiNus - if you're using this stack then in fact there will be a collision. I agree that in order to support that specific use case (I don't think it's very common to be honest), we need to either factor `stackName` into the export, which I'm not sure if it's a good direction or expose a setting that will allow to disable generation of these output export names. @medikoo What do you think?

**Comment by medikoo** [comment]
@TMiNus using very same `service` and `stage` for two actually different service, may break in many places. So even if we address this issue, it's very likely at some point you'll face problems in other areas.

All internal configuration in a Framework stands on assumption that in your environment there's no other _service_ that shares same `service` and `stage` name . So best way to recover is to ensure that those are you unique for each service. Ideally if you use different `service` name for each sub service.

Note that `stackName` is property through which _only_ CloudFormation stack name is customized, it doesn't influence any naming elsewhere. All other generated resource names still use `<service>-<stage>` as common prefix, and we definitely don't want add any exception from that.

**Comment by cameroncf** [comment]
@medikoo I too have run into this same collision problem with this change, which I strangely have not run into before, despite using the same service name in quite a few apps. I typically use `<app>-<service>-<stage>` for values internally in my serverless.yml templates and this seems to be the pattern used by the stackname too, probably for similar collision avoidance reasons.

One of my very frequently offending use cases here would be using a service called `data` or `dynamo` within my apps to store all the data related configs. This results in `appone-data-prod` and `apptwo-data-prod` stacks, sometimes living in the same AWS account.

My vote would be that a better standard naming practice would be to include the appname so that configurations properly isolate resources by stack. However, an alternative solution to this might be adding a warning if a potential collision is detected in someone's configurations. Otherwise this becomes a ticking time bomb lurking in many already deployed configurations.

**Comment by medikoo** [comment]
> My vote would be that a better standard naming practice would be to include the appname

@cameroncf great thanks for your input. I know that we lack some good dedicated documentation on that, but `app` is dashboard only parameter, that allows to additionally group services. There's no `app` concept in non-dashboard involved deployment (in general `app` is not used anywhere for resource naming)

In light of that I  believe best recommended practice would be to prefix service name with an app, so if _app_ is `app`, then  good _service_ name would be `app-service`.

We're currently reworking our internals so _app_ is optional, and if it's not provided, then it's assumed as same value as `service`

**Comment by cameroncf** [comment]
> There's no app concept in non-dashboard involved deployment (in general app is not used anywhere for resource naming)

@medikoo This is good to know! First I said "wait app name is in stackName!" but I've cut and pasted the provider meta so many times actually forgotten that `stackName` was something I've configured to include the app's name. Doh!

So then - I still would support a warning if duplicate service names are detected. Detecting errors at the earliest possible moment in development is generally a good thing. Especially if this is a time bomb sort of issue in multiple areas of the framework.

**Comment by cameroncf** [comment]
> I'm not sure if it's possible to reliably introduce such detection. How do you imagine it could work?

I'm not sure where this lands actually since you wouldn't have enough information to detect this anywhere but the Dashboard. This may be a naive suggestion for reasons. The dashboard knows the account for each provider, and knows the names of all the services within an org. Seems like duplicate detection could happen there within any given org where same account + sane service name = warning.

**Comment by medikoo** [comment]
@cameroncf yes, technically in dashboard realm we could validate if same `service` was not already deployed to other `app`. I'll raise it internally, as such restriction logically makes big sense.

**Comment by dorankangwai** [comment]
Hi @pgrzesik we are also specifying the stackName but using the same service for 2 different serverless deployments

Example serverless configs
```
service: s1

provider:
  name: aws
  region: us-west-2
  deploymentBucket:
    name: doran-deploy
  stackName: s1-init

resources:
  Resources:
    b1:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: doran-b1
```

and
```
service: s1

provider:
  name: aws
  region: us-west-2
  deploymentBucket:
    name: doran-deploy

resources:
  Resources:
    b1:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: doran-b2
```

with the newer version of serverless this leads to the export collision for ServerlessDeploymentBucketName export.
```
Export with name sls-s1-dev-ServerlessDeploymentBucketName is already exported by stack s1-init. Delete requested by user.
```

**Comment by pgrzesik** [comment]
Hello @dorankangwai - thanks for sharing your setup. As @medikoo wrote in previous comment (https://github.com/serverless/serverless/issues/9361#issuecomment-826572600), internal assumption within the Framework is that `service` with `stage` are unique and a lot of internal assumptions about that are made internally (e.g. when constructing unique names). Deploying the same `service` with altering `stackName` is discouraged, as it might cause even more issues in the future. It would be recommended to ensure that `service` is unique between separate services.

**Comment by dorankangwai** [comment]
Thanks @pgrzesik for your reply. I can see how it is important that there is a way for the framework to form a unique identifier and we can certainly change our setup to use unique stack names. At the moment we do have a concern about the automatic export of outputs. Is there a way or will there be an option in the future to disable automatic exports?
It is important to us that we have control over what a stack exports.

**Comment by pgrzesik** [comment]
Hello @dorankangwai :wave: Could you share more about why is that important? We'd love to learn about potential use cases or downsides of such behavior to make a decision.

**Comment by dorankangwai** [comment]
Hi @pgrzesik I will have to admit that the main reason at the moment is because I don't want to change the service name of the serverless definition. Given the wide spread use of ${self:service} throughout the 2 stacks that have the same service name it would be a change that would require extensive testing to ensure that there was no adverse impact. The other reason is that (unless I misunderstand #9313 ) is that if there is no export then it is exported automatically. This seems odd given that CloudFormation lets you create outputs with an export. Lastly it seems like we are loosing control of what is visible to other stacks, where the need to prevent another stack seeing an output may be important.

**Comment by mscharp** [comment]
@pgrzesik 

Ok, here is the simplest way to recreate my issue, using the default serverless setup.  My stack is incredibly more complicated than this, but hopefully this demonstrates the problem clearly.  Note that due to my company's policies, there are some settings that I needed to provide that you most likely wouldn't.  I've commented them out.  There is only a single difference in the yaml between the two.  `custom.env` is `dev` for yaml 1 and `dit` for yaml 2.


Service 1:  `sls deploy --stage uat`

```
service:
  name: bug-test
#  awsKmsKeyArn: arn:aws:kms:us-east-1:6543242262:key/e1425a37-6c88-4520-acd6-9aee45s53

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  stackName: MyApp-SLS-${self:service}-${self:custom.env}-${self:provider.stage}
  tags:
    applicationid: ap133294
 # deploymentBucket:
 #   name: mybucket-us-east-1-dev
 #   serverSideEncryption: aws:kms

custom:
  env: dev
#  lambdaRole:
#    'Fn::ImportValue': aps-ap133294-evtmgmt-MyRole-${self:custom.env}-${self:provider.stage}

functions:
  hello:
    name: hello-${self:custom.env}-${self:provider.stage}
    handler: handler.hello
#    role: ${self:custom.lambdaRole}`
```

Output:
```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.stackName": String value consist of variable which resolve with non-string value
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name.
            More Info: https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION
Serverless: Deprecation warning: Starting with next major version, "awsKmsKeyArn" service property will be replaced by "provider.kmsKeyArn"
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_KMS_KEY_ARN
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service bug-test.zip file to S3 (49.58 KB)...
Serverless: Validating template...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
...........
Serverless: Stack create finished...
Service Information
service: bug-test
stage: src
region: us-east-1
stack: MyApp-SLS-bug-test-dev-src
resources: 3
api keys:
  None
endpoints:
  None
functions:
  hello: hello-dev-src
layers:
  None
```


Service 2:  `sls deploy --stage uat`

```
service:
  name: bug-test
#  awsKmsKeyArn: arn:aws:kms:us-east-1:6543242262:key/e1425a37-6c88-4520-acd6-9aee45s53

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  stackName: MyApp-SLS-${self:service}-${self:custom.env}-${self:provider.stage}
  tags:
    applicationid: ap133294
 # deploymentBucket:
 #   name: mybucket-us-east-1-dev
 #   serverSideEncryption: aws:kms

custom:
  env: dit
#  lambdaRole:
#    'Fn::ImportValue': aps-ap133294-evtmgmt-MyRole-${self:custom.env}-${self:provider.stage}

functions:
  hello:
    name: hello-${self:custom.env}-${self:provider.stage}
    handler: handler.hello
#    role: ${self:custom.lambdaRole}`
```

Output:
```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.stackName": String value consist of variable which resolve with non-string value
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Starting from next major object notation for "service" property will no longer be recognized. Set "service" property directly with service name.
            More Info: https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION
Serverless: Deprecation warning: Starting with next major version, "awsKmsKeyArn" service property will be replaced by "provider.kmsKeyArn"
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_KMS_KEY_ARN
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service bug-test.zip file to S3 (49.58 KB)...
Serverless: Validating template...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
...
Serverless: Stack create finished...
 
 Serverless Error ----------------------------------------
 
  Stack with id MyApp-SLS-bug-test-dit-src does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.3
     Framework Version:         2.43.1 (local)
     Plugin Version:            5.1.3
     SDK Version:               4.2.2
     Components Version:        3.10.0
```

Looking at the deployment in cloudformation, I can see this message in the events tab:

`Export with name sls-bug-test-src-HelloLambdaFunctionQualifiedArn is already exported by stack MyApp-SLS-bug-test-dev-src. Delete requested by user.`

To reiterate, we have multiple "environments" each with multiple "stages" per AWS account, and each env-stage combination is deployed to its own CFN stack.  This worked fine before this change was added, but is now breaking.  Like @dorankangwai mentioned... changing how we name our resources and deploy our stacks would not be a trivial matter, especially given that we're already in production with the current setup.  It would have been nice if users would have needed to "opt in", but barring that, if we could "opt out" of it, that would suit our needs.

**Comment by pgrzesik** [comment]
Thanks a lot @mscharp for sharing. The issue I see in this setup is that the `service` name is duplicated across two different stacks and it's bypassed by having an additional property called `env` being used when constructing `stackName`. Regardless of the export issue, I would advise to not do that, as a lot of internals of the Framework depend on the fact that the combination of `service` and `stage` is unique and that's not the case in your setup, so sooner or later you might run into more issues with that approach.

As for the option to opt-out from the default exports, I think we might consider it, but the current issues are rather caused by bypassing the standard `service` and `stage` uniqueness by constructing different stack names.

**Comment by callum-tait-pbx** [comment]
@pgrzesik we've ran into this too, do we know which version this change occured in so we can in the short term version in sls whilst we look at trying to migrate (this will be hard) away from how we use sls should the opt-out functionality not be implemented

**Comment by m-radzikowski** [comment]
I run onto this issue as well. My setup is a monorepo containing multiple sls services. A single monorepo is a "project", holding multiple "services" (see #9095). Two or more projects can be deployed to the same AWS account.

The logical stack naming, through specifying custom CloudFormation stack name, is in the format:

```
project-stage-service
```

for example:

```
projectA-prod-api
```

If two "projects" contain a service with the same name, now it causes a collision.

While it could be refactored to prepend the service name with a project name, like 

```yml
service: projectA-api
```

the logical top-to-bottom order of `project -> stage -> service` in the resource names would break, or the sls service name would need to be separate from the CF stack name. So easily doable on our side, but kind of ugly solutions.

To keep our naming strategy the best solution right now seems to be to override the exported name like this:

```yml
Outputs:
  ServerlessDeploymentBucketName:
    Value: !Ref ServerlessDeploymentBucket
    Export:
      Name: projectA-${self:service}-ServerlessDeploymentBucketName
```

But would be much nicer to have a simple param in sls itself, something like:

```yml
provider:
 deploymentBucket:
   exportName: false
```

**Comment by medikoo** [comment]
> the logical top-to-bottom order of `project -> stage -> service` in the resource names would break,

@m-radzikowski thanks for sharing. Is there any specific reason why it's not `project -> service -> stage`?

Such will work naturally with Serverless Framework services. Also in Serverless Dashboard we have a concept of `app`, which aligns with concept of `project`  (and in UI logical order is `app -> service -> stage`)

**Comment by m-radzikowski** [comment]
If a single app/project consists of multiple services/stacks, then when you filter resources in AWS by the name start, more often we want to look for "all resources for projectA on prod" than "all service X resources from different stages for projectA". So I just type "projectA-prod" and have what I need. By looking for resources I mean CF stacks, Lambda functions, etc. in AWS Console.

At least this naming convention makes more sense for us. If something different works for anyone else, so be it :-) I think it's nice if the framework offers good defaults, but also allows for some customization for special / more complicated needs.

I see my use-case scenario is only one of few, that resulted in the collision this issue is about. I think the main problem here is that while CloudFormation provides quite good isolation, for example by generating random suffixes to many resource names (like S3 buckets), exporting CF output under that must be unique breaks this isolation.

If you agree to this, I could make a PR with the `exportName` flag that I proposed. I don't know what was the reason to implement this export in the first place, but maybe it would be worth rethinking what should be the default behavior? Should the name be exported by default or not?

**Comment by medikoo** [comment]
@m-radzikowski collision of export names is just one of many things that may fail. All internal naming in a Framework stands on a principle that `<service>-<stage>` is unique for a stage, If you create situations where that could not be the case, then many things can go wrong.

I think in your case, what we probably look after, is setting that allows to switch prefix naming order from `<service>-<stage>` to `<stage>-<service>`. Unfortunately implementing such option is easier said than done, as that order is hard-coded in most of the places (but that could be improved, and it's possible to address that)

**Comment by m-radzikowski** [comment]
@medikoo well, that would be best. But to be honest, we are using Serverless Framework pretty extensively, in multiple projects with different requirements, and so far we did not face any problems related to the naming. Well, this is the first one. Maybe it's a bigger issue when using serverless.com platform.

For the naming, would be best if the whole naming strategy could be overridden. SF generates names in `<service>-<stage>` format for API Gtw, Functions, SF stack, etc. We override those names.
Maybe most flexible would be to allow overriding this whole format? So we can set the naming in the stack as, for example, `projectA-<stage>-<service>`, and anyone else with a different naming schema could set own as well.

Regarding the main issue here, the CF output collision - if you decide how to handle this, I'm willing to help.

**Comment by medikoo** [comment]
> Maybe most flexible would be to allow overriding this whole format?

Yes, that sounds good. We probably could introduce something as `commonPrefix` property, which will default to `<service>-<stage>`. 

Can you open a dedicated issue for that?

**Comment by pgrzesik** [comment]
After discussing further with @medikoo, we've determined that the best way to move forward here is to introduce in context of `v2` a flag that will allow to disable default export names that are automatically added following implementation from https://github.com/serverless/serverless/pull/9313

The property will be set on `provider` level:

```
provider:
  disableDefaultExportNames: true
```

It will also automatically trigger deprecation, as in `v3` it is going to be removed. The plan for the future is to implement the ability to override naming conventions (see https://github.com/serverless/serverless/issues/9604), which will allow to universally address the issue of clashing names, not only in exports but also in all other possible places (as mentioned, overriding `stackName` only can lead to hard to diagnose bugs as Framework internally depends on uniqueness of `service` and `stage` combination)

@medikoo does the proposed property name sound good to you?

**Comment by medikoo** [comment]
That looks great. I just wonder wether `disableDefaultOutputs` would make better name, but I might not have best insight into where given terminology is used.

What's your take. In what context it's _outputs_ and in what it's _export names_ ?

**Comment by pgrzesik** [comment]
I think `disableDefaultOutputs` is a bit misleading, because the outputs will still be a part of the CloudFormation stack, the only thing that is problematic here are _export names_ that are being added to specific outputs. Outputs are in context of stack, where the export name allows to reference that output in other stacks by that export name - it has to be unique in context of specific AWS region. That's why I believe `disableDefaultOutputs` is not the best choice.

**Comment by medikoo** [comment]
@pgrzesik indeed, so maybe `disableDefaultOutputExportNames` ?

**Comment by pgrzesik** [comment]
Sounds good to me, thanks for suggestion @medikoo :+1:

**Comment by m-radzikowski** [comment]
@pgrzesik @medikoo firstly - thank you for implementing this!

When I added the flag, I got this deprecation: https://www.serverless.com/framework/docs/deprecations/#DISABLE_DEFAULT_OUTPUT_EXPORT_NAMES

Will the v3 have no default exports so this won't be needed? Or will the conflict be resolved in some other way?

**Comment by medikoo** [comment]
> Will the v3 have no default exports so this won't be needed? Or will the conflict be resolved in some other way?

@m-radzikowski We've introduced a flag so you can opt out from default exports, as we agreed, it was kind of breaking change, and it should not have been introduced that way.

So this flag is sort of fix to that, it allows you to opt out from this functionality in context of v2. Still in v3 export names will be added unconditionally (hence deprecation message on a flag).

Best and the only reliable fix, so this conflict doesn't happen is to ensure that `<service>-<stage>` is unique among services you deploy.

Otherwise I think adding support for `baseName` (handled at #9604) should also give you some more runway, but we don't have ETA on this. We've provided a description on how to implement this feature and we welcome the PR with that.

**Comment by m-radzikowski** [comment]
Understood, thank you!

**Comment by rdemorais** [comment]
Guys,

I'm here because I ran into the same problem. The solution was to manipulate how the outputs was generated. The Serverless.yml end up like that:

```yaml
resources:
  Outputs:
    ServiceEndpoint:
      Export:
        Name: ${self:service}-${self:provider.stage, 'stage'}-${self:custom.stackName}-ServiceEndpoint
    ModulesLambdaLayerS3Key:
      Export:
        Name: ${self:service}-${self:provider.stage, 'stage'}-${self:custom.stackName}-ModulesLambdaLayerS3Key
    DistributionDomainName:
      Export:
        Name: ${self:service}-${self:provider.stage, 'stage'}-${self:custom.stackName}-DistributionDomainName
    ServerlessDeploymentBucketName:
      Export:
        Name: ${self:service}-${self:provider.stage, 'stage'}-${self:custom.stackName}-ServerlessDeploymentBucketName
    ModulesLambdaLayerHash:
      Export:
        Name: ${self:service}-${self:provider.stage, 'stage'}-${self:custom.stackName}-ModulesLambdaLayerHash
    ModulesLambdaLayerQualifiedArn:
      Export:
        Name: ${self:service}-${self:provider.stage, 'stage'}-${self:custom.stackName}-ModulesLambdaLayerQualifiedArn
```

Hope it can help someone.
