### ISSUE TITLE
Cannot deploy schema validation in a shared API Gateway

### ISSUE THREAD

**Issue by edsondewes** [serverless/serverless#9369]
We are deploying multiple services on a shared API Gateway. After #9319 we are unable to deploy different services with schema validation enabled. 
Only the first service register the API Gateway models, and the following generate an error: `ApiGatewayService2RequestValidator - Validate request body and querystring parameters|pg0abup0m0 already exists in stack`

Using serverless 2.37.x it works fine. Is there any recommendation to work around this problem, or is it a bug?
I made a repository with the reproduction of the error: https://github.com/edsondewes/sls-repro-shared-apig

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: service2

useDotenv: true
variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  versionFunctions: false
  apiGateway:
    restApiId:
      'Fn::ImportValue': MyApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': MyApiGateway-rootResourceId
  
functions:
  myhandler2:
    handler: ./service2/handler2.handle
    events:
      - http:
          method: post
          path: service2/handler
          request:
            schemas:
              application/json: ${file(./service2/schema2.json)}

```

</details>

<details>
<summary><b>output</b></summary>

```
 Serverless Error ----------------------------------------

  An error occurred: ApiGatewayService2RequestValidator - Validate request body and querystring parameters|pg0abup0m0 already exists in stack arn:aws:cloudformation:us-east-1:529947977678:stack/service1-dev/f9e11580-a6c8-11eb-9c16-0a90b7832da7.
```

</details>

<b>Installed version</b>

```
Framework Core: 2.38.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```
