### ISSUE TITLE
deploy to cloudflare worker always overwrite worker's environments to empy

### ISSUE THREAD

**Issue by YEriin** [serverless/serverless#9372]
Serverless framwork always overwrite my cloudflare worker's environments (which can be set in the worker's setting in the dashboard of cloudflare) to empty when i use serverless framwork to deploy worker from local even if i have set environment in serverless.yml.

Is this a bug or is there something that i have missed?

```yaml
service: hi

frameworkVersion: '2'

useDotenv: true

provider:
  name: cloudflare
  environment:
    SOME_VAR: some_var
  config:
    accountId: ${env:ACCOUNT_ID}
    zoneId: ${env:ZONE_ID}

plugins:
  - serverless-cloudflare-workers

functions:
  hi:
    name: hi
    script: hi
```

![image](https://user-images.githubusercontent.com/24295786/116201244-e1689980-a76b-11eb-8c3e-de10044d5463.png)

version info: 
Framework Core: 2.38.0 (standalone)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
