### ISSUE TITLE
Tags are not applied to HttpApiStage

### ISSUE THREAD

**Issue by filipgolonka** [serverless/serverless#9395]
Looks like tags are applied to HttpApi resource but not  to HttpApiStage, which cause this not to be visible in Cost Explorer later.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: ${env:SERVICE_NAME}

plugins:
  - serverless-offline
  - serverless-tag-cloud-watch-logs
  - serverless-domain-manager

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  region: eu-north-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  tags:
    billed-team: golonka-team
    billed-service: '${self:service}'
  httpApi:
    useProviderTags: true

custom:
  customDomain:
    domainName: ${self:service}.golonka.yells.cloud
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'
    apiType: http
  cloudWatchLogsTags:
    team: golonka-team
    billed-service: '${self:service}'

functions:
  app:
    handler: ./serverless.handler
    events:
      - httpApi:
          method: '*'
          path: /
      - httpApi:
          method: '*'
          path: '/{proxy+}'
    environment:
      PUBLICATION: ${env:PUBLICATION}
      HOST: ${env:HOST}
```

</details>

<b>Installed version</b>

```
Framework Core: 2.31.0 (local)
Plugin: 4.5.2
SDK: 4.2.2
Components: 3.7.7
```
