### ISSUE TITLE
"fileSystemConfig" has no effect

### ISSUE THREAD

**Issue by toxygene** [serverless/serverless#9398]
I am attempting to attach an EFS file system to a Lambda. To accomplish this, I first created the file system, access point, and mount targets via `resources`, then added the `fileSystemConfig` properties to the Lambda. On deploy, the EFS resources are created properly, but the file system is not attached to the Lambda.

To ensure the EFS resources were configured properly, I tried attaching the file system to the Lambda via the AWS CLI tool, which worked.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: efs-test

provider:
  name: aws
  runtime: python3.8
  vpc:
    securityGroupIds:
      - [redacted]
    subnetIds:
      - [redacted]
      - [redacted]

functions:
  hello:
    handler: handler.hello
    fileSystemConfig:
      localMountPath: /mnt/tmp
      arn: !GetAtt AssetUploaderTempFileSystemAccessPoint.Arn

resources:
  Resources:
    AssetUploaderTempFileSystem:
      Type: AWS::EFS::FileSystem
    AssetUploaderTempFileSystemAccessPoint:
      Type: AWS::EFS::AccessPoint
      Properties:
        FileSystemId: !Ref AssetUploaderTempFileSystem
        PosixUser:
          Uid: 1000
          Gid: 1000
        RootDirectory:
          CreationInfo:
            OwnerUid: 1000
            OwnerGid: 1000
            Permissions: "0755"
          Path: /asset-uploader-tmp
    AssetUploaderTempFileSystemSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: [redacted]
        GroupDescription: "Security group for the mount target of the asset uploader temp file system"
        SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"
    AssetUploaderTempFileSystemMountTarget:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId: !Ref AssetUploaderTempFileSystem
        SubnetId: [redacted]
        SecurityGroups:
        - !Ref AssetUploaderTempFileSystemSecurityGroup
    AssetUploaderTempFileSystemMountTarget1C:
      Type: AWS::EFS::MountTarget
      Properties:
        FileSystemId: !Ref AssetUploaderTempFileSystem
        SubnetId: [redacted]
        SecurityGroups:
        - !Ref AssetUploaderTempFileSystemSecurityGroup
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
justin.hendrickson@ML11085 temp % SLS_DEBUG=* sls deploy
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.775s 0 retries] describeStacks({ StackName: 'efs-test-dev' })
Serverless: [AWS cloudformation 200 0.865s 0 retries] describeStackResource({
  StackName: 'efs-test-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.667s 0 retries] listObjectsV2({
  Bucket: 'efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg',
  Prefix: 'serverless/efs-test/dev'
})
Serverless: [AWS s3 200 0.25s 0 retries] headObject({
  Bucket: 'efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg',
  Key: 'serverless/efs-test/dev/1619712794594-2021-04-29T16:13:14.594Z/efs-test.zip'
})
Serverless: [AWS s3 200 0.263s 0 retries] headObject({
  Bucket: 'efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg',
  Key: 'serverless/efs-test/dev/1619712794594-2021-04-29T16:13:14.594Z/compiled-cloudformation-template.json'
})
Serverless: [AWS lambda 200 0.297s 0 retries] getFunction({ FunctionName: 'efs-test-dev-hello' })
Serverless: [AWS sts 200 0.226s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.298s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 3854 more bytes>,
  Bucket: 'efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg',
  Key: 'serverless/efs-test/dev/1619713110705-2021-04-29T16:18:30.705Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'TFFRwzgLw7c8TaKOkv3T43WVHn8VI7y7deKOTQ/AMKk=' }
})
Serverless: Uploading artifacts...
Serverless: Uploading service efs-test.zip file to S3 (390 B)...
Serverless: [AWS s3 200 0.324s 0 retries] putObject({
  Body: <Buffer 50 4b 03 04 14 00 08 00 08 00 00 00 21 00 00 00 00 00 00 00 00 00 00 00 00 00 0a 00 00 00 68 61 6e 64 6c 65 72 2e 70 79 b5 51 3d 4f c3 30 10 dd f3 2b ... 340 more bytes>,
  Bucket: 'efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg',
  Key: 'serverless/efs-test/dev/1619713110705-2021-04-29T16:18:30.705Z/efs-test.zip',
  ContentType: 'application/zip',
  Metadata: { filesha256: 'DZ155BihcDB1mkYHXLu2aUmQujW0WbM2duHiD7f3dPw=' }
})
Serverless: Validating template...
Serverless: [AWS cloudformation 200 0.623s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg/serverless/efs-test/dev/1619713110705-2021-04-29T16:18:30.705Z/compiled-cloudformation-template.json'
})
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 1.022s 0 retries] updateStack({
  StackName: 'efs-test-dev',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg/serverless/efs-test/dev/1619713110705-2021-04-29T16:18:30.705Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'dev' }, [length]: 1 ]
})
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.405s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:538493872512:stack/efs-test-dev/cd737a80-a905-11eb-9d6a-1254a8a4acf7'
})
.Serverless: [AWS cloudformation 200 0.344s 0 retries] describeStackEvents({
  StackName: 'arn:aws:cloudformation:us-east-1:538493872512:stack/efs-test-dev/cd737a80-a905-11eb-9d6a-1254a8a4acf7'
})
....
Serverless: Stack update finished...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 200 0.264s 0 retries] describeStacks({ StackName: 'efs-test-dev' })
Serverless: [AWS cloudformation 200 0.299s 0 retries] listStackResources({ StackName: 'efs-test-dev', NextToken: undefined })
Service Information
service: efs-test
stage: dev
region: us-east-1
stack: efs-test-dev
resources: 11
api keys:
  None
endpoints:
  None
functions:
  hello: efs-test-dev-hello
layers:
  None
Serverless: Invoke aws:deploy:finalize
Serverless: [AWS s3 200 0.235s 0 retries] listObjectsV2({
  Bucket: 'efs-test-dev-serverlessdeploymentbucket-16rd8aukhmteg',
  Prefix: 'serverless/efs-test/dev'
})
```

</details>

<b>Installed version</b>

```
Framework Core: 1.78.1
Plugin: 3.7.0
SDK: 2.3.1
Components: 2.34.2
```
