### ISSUE TITLE
'TypeError: Cannot read property "'options'" of undefined' after updating to 2.39.1

### ISSUE THREAD

**Issue by gwoods22** [serverless/serverless#9428]
I just updated from 2.17.0 to 2.39.1 and immediately I was not able to deploy. This was the error I was receiving directly after updating:

```
Type Error ----------------------------------------------

  TypeError: Cannot read property 'options' of undefined
      at module.exports (/Users/graeme/Documents/Projects/aws-grade-scraper/node_modules/serverless/lib/utils/telemetry/generatePayload.js:133:66)
      at async PluginManager.run (/Users/graeme/Documents/Projects/aws-grade-scraper/node_modules/serverless/lib/classes/PluginManager.js:607:35)
      at async Serverless.run (/Users/graeme/Documents/Projects/aws-grade-scraper/node_modules/serverless/lib/Serverless.js:324:5)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:240:7
```

So I took a look at `utils/telemetry/generatePayload.js` and found the undefined object was commandSchema which is loaded using resolveInput() from `cli/resolve-input.js`. I played around with how commandSchema was returned and although I have little knowledge of the inner workings, I was able to deploy successfully by not passing the commandsSchema param to the exported function on line 38+ in `cli/resolve-input.js`. Instead I just loaded commandsSchema from the file `./commandsSchema/` so I changed it from this:
```
module.exports = memoizee((commandsSchema = require('./commands-schema')) => {
  commandsSchema = ensureMap(commandsSchema);
```
to this:
```
module.exports = memoizee((commandsSchemaParam) => {
  let commandsSchema = require('./commands-schema')
  commandsSchema = ensureMap(commandsSchema);
```

I'm assuming there is more nuance to the issue than this solution and maybe it is just something on my end and not an actual bug, but I thought I would open an issue here just in case this is a more widespread bug.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: aws
useDotenv: true
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-2
  versionFunctions: false
  # function parameters
  runtime: nodejs12.x
  memorySize: 2048
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::${env:S3_SCREENSHOT_BUCKET}/*
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: arn:aws:s3:::*

functions:
  grade-scraper:
    handler: grade-scraper.handler
    layers:
      - arn:aws:lambda:___private__lambda__layer___
    environment:
      __removed__for__privacy__

resources:
  Resources:
    screenshotsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: ${env:S3_SCREENSHOT_BUCKET}
        AccessControl: Private
    screenshotsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Principal: "*"
              Resource: arn:aws:s3:::${env:S3_SCREENSHOT_BUCKET}/*
        Bucket:
          Ref: screenshotsBucket      
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.39.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: DOTENV: Loading environment variables from .env:
Serverless: 	 - MOSAIC_USERNAME
Serverless: 	 - MOSAIC_PASSWORD
Serverless: 	 - TWILIO_ACCOUNT_SID
Serverless: 	 - TWILIO_AUTH_TOKEN
Serverless: 	 - S3_SCREENSHOT_BUCKET
Serverless: 	 - T_CONSUMER_KEY
Serverless: 	 - T_CONSUMER_SECRET
Serverless: 	 - T_ACCESS_TOKEN_KEY
Serverless: 	 - T_ACCESS_TOKEN_SECRET
Serverless: 	 - SLS_DEBUG
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
            More Info: https://www.serverless.com/framework/docs/deprecations/#PROVIDER_IAM_SETTINGS

 Type Error ----------------------------------------------

  TypeError: Cannot read property 'options' of undefined
      at module.exports (/Users/graeme/Documents/Projects/aws-grade-scraper/node_modules/serverless/lib/utils/telemetry/generatePayload.js:133:66)
      at async PluginManager.run (/Users/graeme/Documents/Projects/aws-grade-scraper/node_modules/serverless/lib/classes/PluginManager.js:607:35)
      at async Serverless.run (/Users/graeme/Documents/Projects/aws-grade-scraper/node_modules/serverless/lib/Serverless.js:324:5)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:240:7

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.3
     Framework Version:         2.39.1 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.1
```

</details>

<b>Installed version</b>

```
Framework Core: 2.39.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.1
```
