### ISSUE TITLE
Lambda container deployment hangs when packaging service

### ISSUE THREAD

**Issue by Jordan-Eckowitz** [serverless/serverless#9433]
We are trying to deploy a Lambda container and it hangs at the phase where it says **packaging service...**

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: <service-name>
frameworkVersion: '>=1.1.0 <3.0.0'
provider:
  name: aws
  stage: '${opt:stage, "dev"}'
  region: '${opt:region, "us-east-1"}'
functions:
  <function-name>:
    image: <account>.dkr.ecr.<region>.amazonaws.com/<repository>@<digest>
```

</details>

<details>
<summary><b><code>serverless deploy --stage dev --config serverless.yml --verbose</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Packaging service...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.39.2 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```
