### ISSUE TITLE
Can't Add Files To Pckage using package:pattern

### ISSUE THREAD

**Issue by mjflipmind** [serverless/serverless#9434]
It doesn't seem possible to include files in the generated package zip using the pattern syntax but the include syntax is deprecated.

Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS

Can only include these files in the zip with this:

  include:
    - ormconfig.js
    - src/api/oas-doc.yaml
    - secrets.json

<details>
<summary><code>serverless.yml</code></summary>

```yaml

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - 'src/**'
    - 'node_modules/**'
    - '!node_modules/browserify*'
    - '!node_modules/cli-*'
    - '!node_modules/decompress*'
    - '!node_modules/es-*'
    - '!node_modules/websocket-*'
    - '!node_modules/webpack*'
    - '!node_modules/cli-*'
    - '!node_modules/cli-highlight'
    - '!node_modules/coffeescript'
    - '!node_modules/crypto-browserify'
    - '!node_modules/console-browser'
    - '!node_modules/source-map'
    - '!node_modules/keypress'
    - '!node_modules/aws-sign2'
  include:
    - ormconfig.js
    - src/api/oas-doc.yaml
    - secrets.json
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
sls package
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.39.2 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```
