### ISSUE TITLE
Missing "handler" property in function with container lambda

### ISSUE THREAD

**Issue by letto4135** [serverless/serverless#9441]
Q1: Describe the issue

sls deploy --noDeploy --stage dev --region us-west-2

Running this command with the following yaml produces missing handler error, but handler is not valid when using images.
Using the sample defined [here](https://www.serverless.com/framework/docs/providers/aws/guide/functions/) also produces this error

```yaml
service: ${self:custom.config.appName}

provider:
  name: aws
  ecr:
    images:
      lsfimage:
        path: ./
        file: Dockerfile.we

functions:
  validate:
    image: lsfimage
```

Error:

Missing "handler" property in function "validate". Please make sure you point to the correct lambda handler. For example: handler.hello. Please check the docs for more info

Dockerfile.we:
```
FROM public.ecr.aws/lambda/python:3.8
COPY . ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt
CMD ["validator.validate"]
```
