### ISSUE TITLE
Log format string ignored

### ISSUE THREAD

**Issue by thelpbogeyman** [serverless/serverless#9443]
When trying to enable API Gateway logging via `serverless.yml`, set the following:

```yaml
provider:
  name: aws
  apiGateway:
    metrics: true
  logs:
    restApi: true
```

API Gateway is successfully created and default logging string is set:
```
requestId: $context.requestId, ip: $context.identity.sourceIp, caller: $context.identity.caller, user: $context.identity.user, requestTime: $context.requestTime, httpMethod: $context.httpMethod, resourcePath: $context.resourcePath, status: $context.status, protocol: $context.protocol, responseLength: $context.responseLength
```

However, I wish to customize the logging format (as per AWS docs) to this:
```json
{ 
  "requestId":"$context.requestId",
  "ip": "$context.identity.sourceIp",
  "caller":"$context.identity.caller",
  "user":"$context.identity.user",
  "requestTime":"$context.requestTime",
  "httpMethod":"$context.httpMethod",
  "resourcePath":"$context.resourcePath",
  "status":"$context.status",
  "protocol":"$context.protocol",
  "responseLength":"$context.responseLength",
  "stage":"$context.stage",
  "apiId":"$context.apiId",
  "apiKey":"$context.identity.apiKey"
}
```

So, I amended the string in `serverless.yml`:
```yaml
provider:
  name: aws
  apiGateway:
    metrics: true
  logs:
    restApi: true
    format: '{ "requestId":"$context.requestId", "ip":"$context.identity.sourceIp", "caller":"$context.identity.caller","user":"$context.identity.user", "requestTime":$context.requestTimeEpoch,"httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath","status":$context.status, "protocol":"$context.protocol","responseLength":"$context.responseLength","stage":"$context.stage","apiId":"$context.apiId","apiKey":"$context.identity.apiKey"}'
```

Each time, I generated the CFn template. No format string is included in the output, and consequently the log format string in AWS console is not set correctly.

No errors reported during template creation nor during deploy.

<b>Installed version</b>

```
Framework Core: 2.40.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```

**Comment by pgrzesik** [comment]
Hello @thelpbogeyman :wave: I believe that in your case the problem is caused by invalid configuration. Instead of 
```
logs:
  restApi: true
  format: ...
```

you should use 

```
logs:
  restApi:
    format: ...
```

You can find more details in the documentation here: https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#logs

Could you also please include the output of running the `serverless deploy` command? Were there any warnings about invalid configuration?

**Comment by thelpbogeyman** [comment]
So, I tried modifying the section in `serverless.yml`:

```yaml
  logs:
    restApi:
      format: '{ "requestId":"$context.requestId" }'
```

> You can find more details in the documentation here: https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#logs

Yes, I did refer to the docs originally.

> Could you also please include the output of running the `serverless deploy` command? Were there any warnings about invalid configuration?

Due to the proprietary nature, no I cannot post it all.
There were no warnings, and the deploy (and package) is successfully executed.

In looking in the `./.serverless` folder at the generated files:
```
cloudformation-template-update-stack.json
custom-resources.zip
loanpal-client-api.zip
serverless-state.json
```

The only time I see the format string is in the `serverless-state.json` generated file.
