### ISSUE TITLE
Fn::Split : vpcEndpointIds should be an array

### ISSUE THREAD

**Issue by lbrulet** [serverless/serverless#9453]
I'm trying upgrade serverless from 1.77.1 to 2.40 and by using Fn::Split to convert that string into an array `vpce-xxxx,vpce-xxxx` to 
```
  apiGatewayVpcEndpointIds:
    default:
      Fn::Split:
        - ','
        - ${env:VPC_API_ENDPOINT_ID}
```
I am encountering a problem which display a warning
`Configuration warning at 'provider.vpcEndpointIds': should be array`

<details>
<summary><code>serverless.yml</code></summary>

```yaml
custom:
  splitStacks:
    perType: true
  apiGatewayVpcEndpointIds:
    default:
      Fn::Split:
        - ','
        - ${env:VPC_API_ENDPOINT_ID}
  apiGatewayResourcePolicy:
    default:
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          StringEquals:
            aws:sourceVpce:
              Fn::Split:
                - ','
                - ${env:VPC_API_ENDPOINT_ID}
  vpcSettings:
    default:
      securityGroupIds:
        Fn::Split:
          - ','
          - ${env:VPC_SG_IDS}
      subnetIds:
        Fn::Split:
          - ','
          - ${env:VPC_SUBNET_IDS}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 300
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET_NAME}
    blockPublicAccess: true
  role: ${env:LAMBDA_ROLE_ARN}
  endpointType: ${env:API_GATEWAY_ENDPOINT_TYPE, 'private'}
  apiGateway:
    resourcePolicy: ${self:custom.apiGatewayResourcePolicy.default}
  vpcEndpointIds: ${self:custom.apiGatewayVpcEndpointIds.default}
  vpc: ${self:custom.vpcSettings.default}
  stackTags:
    Project: ###
    Service: ${self:service}
    ApplicationName: ###
    Department: Software Development
    Environment: ${self:provider.stage}
    Company: ###
```

</details>

<b>Command used<b>
```
npx sls deploy
```

</details>

<b>Installed version</b>

```
Framework Core: 2.40.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```
