### ISSUE TITLE
`serverless create_domain` hang forever from 2.40.0-096ed965 and newer

### ISSUE THREAD

**Issue by duythanhduong** [serverless/serverless#9468]
Hello all,

I got an issue when I deployed my app with serverless.

When I called `serverless create_domain`, it hang forerer from serverless version 2.40.0-096ed965.

![image](https://user-images.githubusercontent.com/57696511/117939381-2ecf3400-b332-11eb-8ebb-6e9fe570da67.png)

It still run ok with version 2.40.0-7361e049 and older

![image](https://user-images.githubusercontent.com/57696511/117940168-ff6cf700-b332-11eb-8a58-68aae2a09303.png)

I have tried to pull code and saw a few new commits in build 2.40.0-096ed965. 

- fix(Telemetry): Let old versions report telemetry old way
- fix(CLI): Fix local installation fallback
- refactor: Resolve path to package in `resolveLocalServerlessPath`
- fix(Telemetry): For local fallback ensure to report locally used version

I am not sure there is any problem or something news from framework that I need to adapt but I didn't know.

Please help me to check this case.

Thank you so much!

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: Name

provider:
  name: aws
  runtime: nodejs12.x
  stackTags:
    Project: ${env:PROJECT}
    Environment: ${env:PROJECT_ENV}
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        StringEquals:
          aws:sourceVpce: ${env:VPC_ENDPOINT}
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  timeout: 30
  endpointType: PRIVATE
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP}
    subnetIds:
      - ${env:SUBNET_A}
      - ${env:SUBNET_B}
      - ${env:SUBNET_C}
  apiGateway:
    shouldStartNameWithService: true
    disableExecuteApiEndpoint: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource: "*"

plugins:
  - serverless-plugin-warmup-ts-bridge-v2
  - serverless-plugin-warmup
  - serverless-domain-manager
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline-lambda
  - serverless-offline-sqs
  - serverless-offline

custom:
  defaultStage: dev
  defaultRegion: ap-southeast-1
  warmup:
    default:
      prewarm: true
      enabled: true
      schedule: rate(3 minutes)
  customDomain:
    rest:
      domainName: ${env:API_DOMAIN}
      stage: ${self:provider.stage}
      certificateArn: ${env:CERT_ARN}
      createRoute53Record: false
      endpointType: "regional"
      securityPolicy: tls_1_2
    websocket:
      domainName: ${env:WSS_DOMAIN}
      stage: ${self:provider.stage}
      certificateArn: ${env:CERT_ARN}
      createRoute53Record: false
      endpointType: "regional"
      securityPolicy: tls_1_2
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false


package:
  exclude:
    - dist/**
    - .gitignore
    - .git/**

functions:
  health: ${file(./yamls/functions/health.yml)}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
```

</details>

<details>
<summary><b><code>serverless create_domain</code> output</b></summary>

![image](https://user-images.githubusercontent.com/57696511/117942053-dbaab080-b334-11eb-9765-d2e99cdb03ac.png)

</details>

<b>Installed version</b>

![image](https://user-images.githubusercontent.com/57696511/117943179-0fd2a100-b336-11eb-8334-6a2a7b8e1bc5.png)
