### ISSUE TITLE
 Serverless command "deploy" not found

### ISSUE THREAD

**Issue by RobinSobtiTR** [serverless/serverless#9470]
When I run the "serverless deploy" command, it says that:
Serverless command "deploy" not found. Run "serverless help" for a list of all available commands.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: test-ops
plugins:
  - serverless-dotenv-plugin
provider:
  name: awsx
  runtime: nodejs12.x
  stackName: test-ops-dev-use1
  deploymentBucket:
    name: a202909-serverless-deployment-use1

functions:
  OpsUiGraphqlLambda:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    role: OpsUILambdaRole
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
resources:
  Resources:
    OpsUILambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: test-ops-use1
        Path: /
        PermissionsBoundary: arn:aws:iam::xxxxxxxxx:policy/tr-permission-boundary
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        MaxSessionDuration: 3600
        Policies:
          - PolicyName: test-ops-use1
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Action:
                    - xray:*
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'
                  Effect: Allow
                - Action:
                    - ssm:GetParameters
                    - ssm:GetParameter
                  Resource: '*'
                  Effect: Allow
                - Action:
                    - ecs:*
                  Resource: '*'
                  Effect: Allow
                - Action:
                    - iam:PassRole
                  Resource: "*"
                  Effect: Allow
                - Action:
                    - ec2:DescribeNetworkInterfaces
                    - ec2:CreateNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ec2:DescribeInstances
                    - ec2:AttachNetworkInterface
                  Resource: "*"
                  Effect: Allow
                - Action:
                    - s3:GetObject
                    - s3:PutObject
                  Resource: "arn:aws:s3:::test-ops-report-dev-use1/*"
                  Effect: Allow
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.37.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - DATABASE_URL
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
 
 Serverless Error ----------------------------------------
 
  ServerlessError: Serverless command "deploy" not found. Run "serverless help" for a list of all available commands.
      at module.exports (/Users/u6108018/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/lib/cli/ensure-supported-command.js:38:11)
      at /Users/user1/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/scripts/serverless.js:415:55
      at /Users/user1/.nvm/versions/node/v12.14.1/lib/node_modules/serverless/scripts/serverless.js:607:9
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.14.1
     Framework Version:         2.37.1
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.0

```

</details>

<b>Installed version</b>

```
Framework Core: 2.37.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```

**Comment by pgrzesik** [comment]
Hello @RobinSobtiTR - could you please upgrade to the latest version of the Framework, `2.41.1` and verify if the problem still persists?

**Comment by RobinSobtiTR** [comment]
I tried that and don't see that error now. However, the deployment is stuck at:

<details>
<summary><code>Error</code></summary>

```yaml
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.41.1")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - DATABASE_URL
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
```
</details>
