### ISSUE TITLE
Multiple Plugins returning - TypeError: Cannot read property 'options' of undefined with v > 2.39.0

### ISSUE THREAD

**Issue by etothepii** [serverless/serverless#9473]
⚠️⚠️ This issue impact multiple plugins by when using a version > 2.39. Plugin bugs should not be reported here, but an issue impacting multiple plugins has serverless as the common denominator ⚠️⚠️

When using the latest version of serverless with external plugins such as serverless-domain-manager and serverless-offline, as reported by others on [stackoverflow](https://stackoverflow.com/questions/67454564/serverless-offline-throws-configuration-error-or-cannot-read-property-option/) I get an error. This error does not appear to occur if using v2.38.0 or before but does if using v2.39.0 or later 

```TypeError: Cannot read property 'options' of undefined 
      at module.exports (node_modules/serverless/lib/utils/telemetry/generatePayload.js:133:66)
      at async PluginManager.run (node_modules/serverless/lib/classes/PluginManager.js:607:35)
      at async Serverless.run (node_modules/serverless/lib/Serverless.js:324:5)
      at async /.../node_modules/serverless/scripts/serverless.js:601:9
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: submissions

app: some_app
org: some_org

frameworkVersion: "2"
configValidationMode: "error"

provider:
  region: us-east-1
  name: aws
  runtime: python3.8
  stage: dev
  lambdaHashingVersion: 20201221
  profile: some_profile

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: example.com
    basePath: ""
    stage: dev
    createRoute53Record: true
    endpointType: regional
    apiType: http

```

</details>

<details>
<summary><b><code>sls create_domain</code> output</b></summary>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Using provider credentials, configured via dashboard: https://app.serverless.com/cactusbm/apps/marmalade-io/submissions/dev/us-east-1/providers
 
 Type Error ----------------------------------------------
 
  TypeError: Cannot read property 'options' of undefined
      at module.exports (node_modules/serverless/lib/utils/telemetry/generatePayload.js:146:66)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
      at async PluginManager.run (node_modules/serverless/lib/classes/PluginManager.js:607:35)
      at async Serverless.run (node_modules/serverless/lib/Serverless.js:327:5)
      at async /.../node_modules/serverless/scripts/serverless.js:601:9
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              15.5.1
     Framework Version:         2.41.1 (local)
     Plugin Version:            4.6.0
     SDK Version:               4.2.2
     Components Version:        3.9.2

```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.41.1 (local)
Plugin: 4.6.0
SDK: 4.2.2
Components: 3.9.2
```
