### ISSUE TITLE
Support AWS::CloudFront::Function

### ISSUE THREAD

**Issue by FanFataL** [serverless/serverless#9475]
Hi guys,

What do you think about support Cloudfront Functions in serverless?

https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/

### Use case description

This is the new feature from the AWS supporting smaller function to execute on CloudFront.

#### The config for this could be something like this:

```
functions:
  myFunctionAtEdge:
    runtime: cloudfront-js-1.0
    package:
      individually: true
      patterns:
        - my-function-at-edge.js
    events:
      - cloudFrontFunction:
          eventType: viewer-response
          origin: s3://bucketname.s3.amazonaws.com/files
```

Since the Cloudformation supports Cloudfront Function its possible to implenet this feature into serverless.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-functionassociation.html

If you agree I can manage to develop this feature.

Thanks.

**Comment by pgrzesik** [comment]
Hello @FanFataL, thanks a lot for the proposal, I agree that it would be great to support newly introduced `CloudFront Functions`. Before deciding on the approach, I have a few questions:
1. How should the packaging of such functions look like? If I'm not mistaken, you have to provide code directly to CF template instead of e.g. uploading it to `S3`.
2. Should we ensure that functions that have `cloudFrontFunction` event specitifed are not allowed to accept any other event types? I believe we should, as they're a bit different construct
3. Can a single CloudFront Function be associated with multiple "events" or it will always have only one event defined?
4. Do CloudFront Function have to be defined in a single `.js` file?

I'm just getting up to speed with this new offering, any other feedback/questions/suggestions will be much appreciated,

**Comment by FanFataL** [comment]
Hi @pgrzesik 

1. Yes you are right, you need to embed the code into cf template
2. We should
3. It can be assciate with multiple events
4. Yes, since you are embeeding this function into cf template

My proposition for config is to move this away from top level `functions` config and add to the top level `cloudFrontFunctions`

```
cloudFrontFunctions:
  myFunctionAtEdge:
    name: myFunctionAtEdge #default autogenerated
    runtime: cloudfront-js-1.0 #default
    publish: true #default
    file: src/my-function-at-edge.js
    events:
       - eventType: viewer-response
         origin: s3://bucketname.s3.amazonaws.com/files
```
