### ISSUE TITLE
SAM template is invalid. Path '/{proxy+}' contains method 'x-amazon-apigateway-any-method' which is not a supported method ['OPTIONS', 'GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'PATCH']

### ISSUE THREAD

**Issue by lorilew** [serverless/serverless#9480]
Hi, I've not made any recent changes to our serverless template, but now our builds are failing because of the following error:

Error output:
Failed to create CloudFormation change set: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Structure of the SAM template is invalid. Path '/{proxy+}' contains method 'x-amazon-apigateway-any-method' which is not a supported method 'OPTIONS', 'GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'PATCH'

<details>
<summary><code>serverless.yml</code></summary>

```yaml
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Description": "XXX",
  "Parameters": {
        "sg" : {
            "Description" : "Security Group",
            "Type" : "String"
        },
        "subnet1" : {
           "Description" : "Subnet 1",
           "Type" : "String"
        },
        "subnet2" : {
           "Description" : "Subnet 2",
           "Type" : "String"
        },
        "subnet3" : {
           "Description" : "Subnet 3",
           "Type" : "String"
        },
        "userpoolarn" : {
          "Description" : "Userpool arn",
          "Type" : "String"
        },
        "userpoolid" : {
          "Description" : "Userpool id",
          "Type" : "String"
        }
   },
  "Conditions": {},
  "Resources": {
    "IncanLambaFunctionRole": {
    "Type": "AWS::IAM::Role",
    "Properties": {
    "ManagedPolicyArns": [ "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole" ],
    "AssumeRolePolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [{
        "Action": ["sts:AssumeRole"],
        "Effect": "Allow",
        "Principal": {
            "Service": ["lambda.amazonaws.com"]
            }
          }]
         }
       }
    },
    "IncansApi" : {
        "Type" : "AWS::Serverless::Api",
        "Properties" : {
        "Cors" : {
            "AllowMethods" : "'GET,POST,PUT,DELETE,OPTIONS'",
            "AllowHeaders" : "'Access-Control-Allow-Headers, Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization'",
            "AllowOrigin" : "'*'",
            "AllowCredentials" : "true"
        },
        "StageName" : "Prod",
            "Auth" : {
                "DefaultAuthorizer" : "IncansCognitoAuthorizer",
                "AddDefaultAuthorizerToCorsPreflight": false,
                "Authorizers" :  {
                    "IncansCognitoAuthorizer" : {
                    "UserPoolArn" : { "Ref" : "userpoolarn" }
                    }
                }
            }
        }
    },
    "AspNetCoreFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "IncansApi::IncansApi.LambdaEntryPoint::FunctionHandlerAsync",
        "Runtime": "dotnetcore3.1",
        "CodeUri": "",
        "MemorySize": 1600,
        "Timeout": 60,
        "AutoPublishAlias": "live",
        "Layers" : [{"Fn::Sub": "arn:aws:lambda:eu-west-1:${AWS::AccountId}:layer:drawing-layer:1"}],
        "ProvisionedConcurrencyConfig" : {
            "ProvisionedConcurrentExecutions" : 2
        },
        "Role": null,
        "Policies": [
          "AWSLambda_FullAccess",
          "AmazonSSMReadOnlyAccess",
          "AWSKeyManagementServicePowerUser",
          "SecretsManagerReadWrite",
          {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": "kms:Decrypt",
                        "Resource": "*"
                    }
                ]
            },
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": "sts:*",
                        "Resource": "*"
                    }
                ]
            },
            {
                "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": "cognito-idp:AdminCreateUser",
                            "Resource": {"Ref" : "userpoolarn"}
                        }
                    ]
            },
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "cognito-idp:AdminEnableUser",
                            "cognito-idp:AddCustomAttributes",
                            "cognito-idp:AdminCreateUser",
                            "cognito-idp:AdminDisableUser",
                            "cognito-idp:AdminRemoveUserFromGroup",
                            "cognito-idp:AdminAddUserToGroup",
                            "cognito-idp:AdminUpdateUserAttributes",
                            "cognito-idp:AdminGetUser",
                            "cognito-idp:AdminResetUserPassword"
                        ],
                        "Resource": { "Ref" : "userpoolarn" }
                    }
                ]
            }
        ],
        "Environment": {
          "Variables": {"USER_POOL_ID": { "Ref": "userpoolid" }, "FONTCONFIG_PATH" : "/opt/lib/etc" }
        },
        "VpcConfig": {
          "SecurityGroupIds" : [ { "Ref" : "sg" } ],
          "SubnetIds" : [ { "Ref" : "subnet1" } , { "Ref" : "subnet2" } , { "Ref" : "subnet3" }  ]
        },
        "Events": {
          "ProxyResource": {
            "Type": "Api",
            "Properties": {
              "RestApiId" : { "Ref" : "XXX" },
              "Path": "/{proxy+}",
              "Method": "ANY"
            }
          },
          "RootResource": {
            "Type": "Api",
            "Properties": {
              "RestApiId" : { "Ref" : "XXX" },
              "Path": "/",
              "Method": "ANY"
            }
          }
        }
      }
    }
  },
  "Outputs": {
    "ApiURL": {
      "Description": "API endpoint URL for Prod environment",
      "Value": {
        "Fn::Sub": "https://${XXX}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
      }
    }
  }
}

```

</details>

<details>
<summary><b><code>AWS code build spec</code> output</b></summary>

```
version: 0.2
env:
  variables:
    DOTNET_ROOT: /root/.dotnet
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Restore started on `date`
      - export PATH="$PATH:/root/.dotnet/tools"
      - ArtifactStoreS3Location=$( aws cloudformation describe-stacks --region eu-west-1  --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='ArtifactStoreS3Location'].OutputValue" --output text)
      - CFBuildRole=$( aws cloudformation describe-stacks --region eu-west-1  --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='CFBuildRole'].OutputValue" --output text)
      - UserPoolArn=$( aws cloudformation describe-stacks --region eu-west-1  --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='UserPoolArn'].OutputValue" --output text)
      - UserPoolId=$( aws cloudformation describe-stacks --region eu-west-1  --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" --output text)
      - RootStackName=$( aws cloudformation describe-stacks --region eu-west-1 --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='RootStackName'].OutputValue" --output text)
      - SecurityGroup=$( aws cloudformation describe-stacks --region eu-west-1 --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='SecurityGroup'].OutputValue" --output text)
      - KmsKeyId=$( aws cloudformation describe-stacks --region eu-west-1 --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='KmsKeyId'].OutputValue" --output text)
      - Subnets=$( aws cloudformation describe-stacks --region eu-west-1 --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='Subnets'].OutputValue" --output text)
      - Subnet1=$( aws cloudformation describe-stacks --region eu-west-1 --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='Subnet1'].OutputValue" --output text)
      - Subnet2=$( aws cloudformation describe-stacks --region eu-west-1 --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='Subnet2'].OutputValue" --output text)
      - Subnet3=$( aws cloudformation describe-stacks --region eu-west-1 --stack-name $Stage --query "Stacks[0].Outputs[?OutputKey=='Subnet3'].OutputValue" --output text)
      - cd IncansApi
      - dotnet clean
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet tool install -g Amazon.Lambda.Tools
      - dotnet tool update -g Amazon.Lambda.Tools
      - dotnet lambda deploy-serverless --role-arn $CFBuildRole --configuration Release --region eu-west-1 --s3-prefix IncansApi-$Stage/ --s3-bucket $ArtifactStoreS3Location --stack-name $Stage-api --framework netcoreapp3.1 --template serverless.template --environment-variables "\"LD_LIBRARY_PATH\"=\"/opt/lib\"" --template-parameters "sg=$SecurityGroup;subnet1=$Subnet1;subnet2=$Subnet2;subnet3=$Subnet3;userpoolarn=$UserPoolArn;userpoolid=$UserPoolId;kmskeyid=$KmsKeyId;artifactstore=$ArtifactStoreS3Location"

```

</details>

<b>Installed version</b>

```
Framework Core: 1.83.3
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
