### ISSUE TITLE
TypeError: Cannot read property 'Ref' of undefined

### ISSUE THREAD

**Issue by nrszysiak** [serverless/serverless#9500]
I'm trying to deploy & run Python AWS Lambda function on APIGateway with an use of a LocalStack framework. The issue seems to be kind of similar to #6497.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: [service_name]
custom:
  logRetentionInDays: 14
  prune:
    automatic: true
    number: 3
  localstack:
    debug: true
    stages:
      - local
    endpointFile: localstack_endpoints.json

provider:
  name: aws
  profile: ${opt:profile, 'stg'}
  runtime: python3.7
  region: eu-west-1
  memorySize: 128
  stage: v1
  endpointType: REGIONAL
  deploymentBucket:
    name: [deployment_bucker_prefix]-${opt:profile, 'stg'}
  apiGateway:
    restApiId: ${ssm:rest-api-id}
    restApiRootResourceId: ${ssm:rest-api-root-resource-id}

package:
  individually: true

functions:
  [function_name]:
    handler: [handler]
    name: [name]
    timeout: 30
    environment:
      RDS_SECRET_NAME: ${ssm:RDS_SECRET_NAME}
    layers:
      - ${ssm:pymysql_layer_arn}
      - ${ssm:retrying_layer_arn}
      - ${ssm:lambda_utils_layer_arn}
    role:
      Fn::GetAtt:
        - lambdaRole
        - Arn
    package:
      include:
        - lambdas/**
      exclude:
        - "**/**"
    events:
      - http:
          path:  [path]
          method: get
          request:
            parameters:
              paths:
                partner: true
                personal_number: true
      - schedule:
          name: [schedule_name]
          rate: rate(10 minutes)
          inputTransformer:
            inputTemplate: '{"pathParameters": {[params]}}'
    vpc:
      securityGroupIds:
        - ${ssm:private-security-group}
      subnetIds:
        - ${ssm:private-subnet-a-id}
        - ${ssm:private-subnet-b-id}
        - ${ssm:private-subnet-c-id}

resources:
  Resources:
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: [role_name]
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: [policy_name]
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - rds:*
                    - ssm:*
                    - secretsmanager:*
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DeleteNetworkInterface
                  Resource: "*"

plugins:
  - serverless-prune-plugin
  - serverless-plugin-log-retention
  - serverless-localstack
```

</details>

<details>
<summary><b><code>sls deploy --stage local</code> output</b></summary>

```
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: v1
Serverless: config.stage: local
Serverless: Loading endpointJson from localstack_endpoints.json
Serverless: Intercepting service CloudFormation
Serverless: Intercepting service Lambda
Serverless: Intercepting service S3
Serverless: Intercepting service ApiGateway
Serverless: Using serverless-localstack
Serverless: Deprecation warning: "provider.profile" is not accessible (configured behind variables which cannot be resolved at this stage).
            Starting with next major release, this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to this behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: v1
Serverless: config.stage: local
Serverless: Using serverless-localstack
Serverless: Reconfiguring service acm to use http://localhost:4566
Serverless: Reconfiguring service amplify to use http://localhost:4566
Serverless: Reconfiguring service apigateway to use http://localhost:4566
Serverless: Reconfiguring service apigatewayv2 to use http://localhost:4566
Serverless: Reconfiguring service application-autoscaling to use http://localhost:4566
Serverless: Reconfiguring service appsync to use http://localhost:4566
Serverless: Reconfiguring service athena to use http://localhost:4566
Serverless: Reconfiguring service autoscaling to use http://localhost:4566
Serverless: Reconfiguring service batch to use http://localhost:4566
Serverless: Reconfiguring service cloudformation to use http://localhost:4566
Serverless: Reconfiguring service cloudfront to use http://localhost:4566
Serverless: Reconfiguring service cloudsearch to use http://localhost:4566
Serverless: Reconfiguring service cloudtrail to use http://localhost:4566
Serverless: Reconfiguring service cloudwatch to use http://localhost:4566
Serverless: Reconfiguring service cloudwatchlogs to use http://localhost:4566
Serverless: Reconfiguring service codecommit to use http://localhost:4566
Serverless: Reconfiguring service cognito-idp to use http://localhost:4566
Serverless: Reconfiguring service cognito-identity to use http://localhost:4566
Serverless: Reconfiguring service docdb to use http://localhost:4566
Serverless: Reconfiguring service dynamodb to use http://localhost:4566
Serverless: Reconfiguring service dynamodbstreams to use http://localhost:4566
Serverless: Reconfiguring service ec2 to use http://localhost:4566
Serverless: Reconfiguring service ecr to use http://localhost:4566
Serverless: Reconfiguring service ecs to use http://localhost:4566
Serverless: Reconfiguring service eks to use http://localhost:4566
Serverless: Reconfiguring service elasticache to use http://localhost:4566
Serverless: Reconfiguring service elasticbeanstalk to use http://localhost:4566
Serverless: Reconfiguring service elb to use http://localhost:4566
Serverless: Reconfiguring service elbv2 to use http://localhost:4566
Serverless: Reconfiguring service emr to use http://localhost:4566
Serverless: Reconfiguring service es to use http://localhost:4566
Serverless: Reconfiguring service events to use http://localhost:4566
Serverless: Reconfiguring service firehose to use http://localhost:4566
Serverless: Reconfiguring service glacier to use http://localhost:4566
Serverless: Reconfiguring service glue to use http://localhost:4566
Serverless: Reconfiguring service iam to use http://localhost:4566
Serverless: Reconfiguring service iot to use http://localhost:4566
Serverless: Reconfiguring service iotanalytics to use http://localhost:4566
Serverless: Reconfiguring service iotevents to use http://localhost:4566
Serverless: Reconfiguring service iot-data to use http://localhost:4566
Serverless: Reconfiguring service iot-jobs-data to use http://localhost:4566
Serverless: Reconfiguring service kafka to use http://localhost:4566
Serverless: Reconfiguring service kinesis to use http://localhost:4566
Serverless: Reconfiguring service kinesisanalytics to use http://localhost:4566
Serverless: Reconfiguring service kms to use http://localhost:4566
Serverless: Reconfiguring service lambda to use http://localhost:4566
Serverless: Reconfiguring service logs to use http://localhost:4566
Serverless: Reconfiguring service mediastore to use http://localhost:4566
Serverless: Reconfiguring service neptune to use http://localhost:4566
Serverless: Reconfiguring service organizations to use http://localhost:4566
Serverless: Reconfiguring service qldb to use http://localhost:4566
Serverless: Reconfiguring service rds to use http://localhost:4566
Serverless: Reconfiguring service redshift to use http://localhost:4566
Serverless: Reconfiguring service route53 to use http://localhost:4566
Serverless: Reconfiguring service s3 to use http://localhost:4566
Serverless: Reconfiguring service s3control to use http://localhost:4566
Serverless: Reconfiguring service sagemaker to use http://localhost:4566
Serverless: Reconfiguring service sagemaker-runtime to use http://localhost:4566
Serverless: Reconfiguring service secretsmanager to use http://localhost:4566
Serverless: Reconfiguring service ses to use http://localhost:4566
Serverless: Reconfiguring service sns to use http://localhost:4566
Serverless: Reconfiguring service sqs to use http://localhost:4566
Serverless: Reconfiguring service ssm to use http://localhost:4566
Serverless: Reconfiguring service stepfunctions to use http://localhost:4566
Serverless: Reconfiguring service sts to use http://localhost:4566
Serverless: Reconfiguring service timestream to use http://localhost:4566
Serverless: Reconfiguring service transfer to use http://localhost:4566
Serverless: Reconfiguring service xray to use http://localhost:4566
Serverless: Reconfiguring service CloudFormation to use http://localhost:4566
Serverless: Reconfiguring service Lambda to use http://localhost:4566
Serverless: Reconfiguring service S3 to use http://localhost:4566
Serverless: Reconfiguring service ApiGateway to use http://localhost:4566
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: v1
Serverless: config.stage: local
Serverless: Deprecation warning: Unresolved variable references will be communicated with a thrown error, starting from next major
            More Info: https://www.serverless.com/framework/docs/deprecations/#VARIABLES_ERROR_ON_UNRESOLVED

 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:rest-api-id' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:rest-api-root-resource-id' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:pymysql_layer_arn' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:RDS_SECRET_NAME' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:retrying_layer_arn' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:lambda_utils_layer_arn' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:private-subnet-a-id' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:private-security-group' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:private-subnet-b-id' could not be found.


 Serverless Warning --------------------------------------

  A valid SSM parameter to satisfy the declaration 'ssm:private-subnet-c-id' could not be found.

Serverless: Configuration warning:
Serverless:   at 'functions['api-player-segmentation'].layers[0]': unsupported configuration format
Serverless:   at 'functions['api-player-segmentation'].layers[1]': unsupported configuration format
Serverless:   at 'functions['api-player-segmentation'].layers[2]': unsupported configuration format
Serverless:   at 'functions['api-player-segmentation'].vpc.securityGroupIds[0]': unsupported configuration format
Serverless:   at 'functions['api-player-segmentation'].vpc.subnetIds[0]': unsupported configuration format
Serverless:   at 'functions['api-player-segmentation'].vpc.subnetIds[1]': unsupported configuration format
Serverless:   at 'functions['api-player-segmentation'].vpc.subnetIds[2]': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error"
to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Deprecation warning: Support for "package.include" and "package.exclude" will be removed with next major release. Please use "package.patterns" instead
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_PACKAGE_PATTERNS
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Packaging service...
Serverless: Excluding development dependencies...

 Type Error ----------------------------------------------

  TypeError: Cannot read property 'Ref' of undefined
      at functionProperties.Layers.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:724:35)
      at Array.forEach (<anonymous>)
      at extractLayerConfigurationsFromFunction (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:723:29)
      at AwsCompileFunctions.compileFunction (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:445:9)
      at LocalstackPlugin.compileFunction (/mnt/c/Users/nszys/PycharmProjects/aws-bigdata-api/api_player_segmentation/node_modules/serverless-localstack/src/index.js:172:50)
      at Promise.all.allFunctions.map (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:668:64)
      at Array.map (<anonymous>)
      at AwsCompileFunctions.compileFunctions (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions.js:668:37)
      at AwsCompileFunctions.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.19.0
     Framework Version:         2.40.0
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.2

```

</details>

<b>Installed version</b>

```
Framework Core: 2.40.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2

```
