### ISSUE TITLE
Cannot read property 'options' of undefined  at module.exports SLS Version 12.43.0

### ISSUE THREAD

**Issue by william1benn** [serverless/serverless#9512]
Upgraded to Serverless 2.43.0 on node version 12.20.2 after the upgrade, I am throwing an error 
```
Cannot read property 'options' of undefined
    at module.exports (/repo/node_modules/serverless/lib/utils/telemetry/generatePayload.js:193:66)
```
Template: 
```
service: orderDetailsHooks

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: v1

custom:
  bundle:
    linting: false 
  
package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline


functions:

  reciever: 
    handler: ./src/functions/Sqs/handler.SQSProcess

```

```
sls deploy and sls deploy -v
```
This error started to occur after upgrade to serverless version 2.43.0
