### ISSUE TITLE
Not using default value for SSM on 2.43.0

### ISSUE THREAD

**Issue by ricardoul** [serverless/serverless#9516]
When  updating to 2.43.0 version from 2.39.1
the ssm default value fails with
SLACK_APP_TOKEN: ${ssm:graphql_token, 'dev'}
 ServerlessError: Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.environment.SLACK_APP_TOKEN": ParameterNotFound: null

⚠️⚠️ REPLACE WITH DESCRIPTION

<details>
<summary><code>serverless.yml</code></summary>

```yaml


service: my-graphql-core

frameworkVersion: "^2.39.1"
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 30
  region: us-west-2
  stage: ${opt:stage, 'stage'}
  iam:
    role:
      statements: ${file(conf/iam/${self:provider.stage}.yml)}
  versionFunctions: false
  deploymentBucket:
    name: ${self:custom.conf.deployment.bucket}

  layers: ${file(conf/layers/${self:provider.stage}.yml)}


environment:
    AWS_ACCOUNT_ID: '#{AWS::AccountId}'
    SLACK_APP_TOKEN: ${ssm:graphql_token, 'dev'}

package:
  patterns:
    - "!./node_modules/**"
    - "!node_modules/**"
    - "!venv/**"
    - 
plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-latest-layer-version
  - serverless-sequelize-migrations
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
➜sls deploy -v  --stage mystage
ServerlessError: Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.environment.SLACK_APP_TOKEN": ParameterNotFound: null
      at Request.extractError (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/json.js:52:27)
      at Request.callListeners (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:313:13)
      at IncomingMessage.emit (events.js:203:15)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  ----------------------------------------------------------------------------------------------------
      at module.exports (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/lib/configuration/variables/eventually-report-resolution-errors.js:24:13)
      at processSpanPromise (/home/ricardoul/.nvm/versions/node/v10.23.3/lib/node_modules/serverless/scripts/serverless.js:626:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.23.3
     Framework Version:         2.43.0
     Plugin Version:            5.1.3
     SDK Version:               4.2.2
     Components Version:        3.10.0

```

</details>

<b>Installed version</b>

```
Framework Core: 2.43.0
Plugin: 5.1.3
SDK: 4.2.2
Components: 3.10.0
```
