### ISSUE TITLE
API Gateway with usage plans and api key groups are not config errors

### ISSUE THREAD

**Issue by dazza-codes** [serverless/serverless#9529]
The example for API keys in https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
does not provide any nested values for groups of API users.  i.e.

```yaml
    apiKeys: # List of API keys to be used by your service API Gateway REST API
      - myFirstKey
        value: myFirstKeyValue
        description: myFirstKeyDescription
        customerId: myFirstKeyCustomerId
      - ${opt:stage}-myFirstKey
      - ${env:MY_API_KEY} # you can hide it in a serverless variable
```

In the example below, the API users are grouped into 2 groups that have different usage plans.

Why are the groups of API users below raising configuration errors like the following?

```text
$ sls info
Serverless: Configuration warning:
Serverless:   at 'provider.apiGateway.apiKeys[0].paid[0]': should be string
Serverless:   at 'provider.apiGateway.apiKeys[1].free[0]': should be string
Serverless:   at 'provider.apiGateway.apiKeys[1].free[1]': should be string
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
```

Sample of API users and usage plans for groups of users:

```yaml

provider:

  apiGateway:

    apiKeys:
      - paid:
        - name: api-userA-dev
          value: secret-key-a
          customerId: userA
      - free:
        - name: api-userB-dev
          value: secret-key-b
          customerId: userB
        - name: api-userC-dev
          value: secret-key-c
          customerId: userC

    usagePlan:
      - paid:
          quota:
            limit: 1000000
            offset: 0
            period: DAY
          throttle:
            burstLimit: 1000
            rateLimit: 500
      - free:
          quota:
            limit: 5000
            offset: 0
            period: DAY
          throttle:
            burstLimit: 50
            rateLimit: 10

```

<b>Installed version</b>

```
Framework Core: 2.41.2
Plugin: 5.1.0
SDK: 4.2.2
Components: 3.9.2
```
