### ISSUE TITLE
Cannot define custom route on websocket

### ISSUE THREAD

**Issue by softmarshmallow** [serverless/serverless#9530]
Working version

global

`websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body`

```
  # connection from master client
  wsconnect:
    handler: handler-ws-connection.connectHandler
    events:
      - websocket:
          route: $connect
  wsdisconnect:
    handler: handler-ws-connection.disconnectHandler
    events:
      - websocket:
          route: $disconnect
```

error causing new route
```
  # authentication of master client & registering connection to session.
  wsauth:
    handler: handler-ws-connection.getAuthorized
    events:
      - websocket:
          route: $getauthorized # { action: "getauthorized" }

```

throws error while deploy
```
ServerlessError: An error occurred: SgetauthorizedWebsocketsRoute - The provided route key is not formatted properly (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: ******-4***-9600-7de8****e9e; Proxy: null).
```

![image](https://user-images.githubusercontent.com/16307013/120080398-b3bc9a80-c0f3-11eb-8a4f-a336e47a395b.png)

Only the custom route key won't work

Maybe related (Though i've tried remove & deploy again, still same error)
- https://github.com/serverless/serverless/issues/7260
