### ISSUE TITLE
Unable to invoke Java individual package artifact locally.

### ISSUE THREAD

**Issue by ymotuz-sc** [serverless/serverless#9537]
Hi!
I'm trying to invoke the Java lambda function locally but got an error during invocation.
#### Command:

```bash
serverless invoke local --function send-notification
```

#### Result:

```bash
Serverless: Invoke invoke:local
 
 Serverless Error ----------------------------------------
 
  ServerlessError: Artifact undefined doesn't exist, please compile it first.
      at AwsInvokeLocal.invokeLocalJava (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:640:13)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.1
     Framework Version:         2.43.1
     Plugin Version:            5.1.4
     SDK Version:               4.2.2
     Components Version:        3.10.1
```

#### FULL content of serverless.yml
```
frameworkVersion: '=2.43.1'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  memorySize: 512
  timeout: 60
  stage: dev
  region: eu-central-1

package:
  individually: true

plugins:
  - serverless-offline

functions:
  send-notification:
    handler: com.depl.worker.notification.handler.SqsHandler
    events:
      - sqs: ${env:SQS_QUEUE_ARN}
    environment:
      LOG_LEVEL: ${env:LOG_LEVEL}
    package:
      artifact: handlers/sqs/target/sqs-handler-1.0-SNAPSHOT.jar
      individually: true

custom:
  serverless-offline:
    host: "0.0.0.0"
```

#### Docker environment:
```
FROM node:12.16.1

RUN apt-get update
RUN apt-get install -y openjdk-8-jdk
RUN apt-get install -y maven

RUN npm install -g serverless@2.43.1
```

#### Debug

I debugged `usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js` file and found out, that 
in line 251 you have the following code:
```
    if (['java8', 'java11'].includes(runtime)) {
      const className = handler.split('::')[0];
      const handlerName = handler.split('::')[1] || 'handleRequest';
      const artifact =
        this.options.package && this.options.package.artifact
          ? this.options.package.artifact
          : this.serverless.service.package.artifact;
      return this.invokeLocalJava(
        'java',
        className,
        handlerName,
        artifact,
        this.options.data,
        this.options.context
      );
    }

```
In my case `this.options` does not contain `package` variable.
here is my output of `this.options` variable:
```
{
  function: 'send-notification',
  stage: 'dev',
  region: 'eu-central-1',
  functionObj: {
    handler: 'com.depl.worker.notification.handler.SqsHandler',
    events: [ [Object] ],
    environment: {
      LOG_LEVEL: 'WARN'
    },
    package: {
      artifact: 'handlers/sqs/target/sqs-handler-1.0-SNAPSHOT.jar',
      individually: true
    },
    name: 'ap-lambda-java-dev-send-notification'
  },
  data: ''
}
```

as you can see `package` is situated in `functionObj` variable, not in the root of `options`.

Is the individual apckage artifact retrieved correctly?

Thanks.
