### ISSUE TITLE
AWS Cognito Trigger PreSignUp_ExternalProvider cannot be gernated because of underscore

### ISSUE THREAD

**Issue by bldcaveman** [serverless/serverless#9549]
When deploying a Lambda trigger for PreSignUp_ExternalProvider AWS rejects the autogenerated cloudformation name of FunctionNameLambdaPermissionCognitoUserPoolQNABUserPoolTriggerSourcePreSignUp_ExternalPro

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:
  cognitoExternalCheck:
    handler: cognitotriggers/presignup.handler
    events:
      - cognitoUserPool:
          pool: QNABUserPool
          trigger: PreSignUp_ExternalProvider

```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
The CloudFormation template is invalid: Template format error: Resource name CognitoExternalCheckLambdaPermissionCognitoUserPoolQNABUserPoolTriggerSourcePreSignUp_ExternalProvider is non alphanumeric```

</details>

<!--
Q4: Provide (in below placeholder) output of serverless --version
-->

<b>Installed version</b>

```
2.43.1```
