### ISSUE TITLE
Serverless Pro deployment to AWS Lambdas fails updating log group

### ISSUE THREAD

**Issue by dseeker** [serverless/serverless#9552]
Serverless Pro deployment to AWS Lambdas fail to update existing stack
2 weeks ago it was working fine, last week stacks stopped updating without any changes in package.json dependencies. 
It seems the stack template generated has a different Log group method. 
Deploying a new stage from scratch works, updating the older ones doesn't.

Before Working:
```
 "CloudWatchLogsSubscriptionFilterGenerateLogGroup": {
      "Type": "AWS::Logs::SubscriptionFilter",
      "Properties": {
        "DestinationArn": ...
        "LogGroupName": {
          "Ref": "GenerateLogGroup"
        }
      }
    },
```

Now Failing:

```
 "CWLSubFilterGenerateLogGroupEuCentral1": {
      "Type": "AWS::Logs::SubscriptionFilter",
      "Properties": {
        "DestinationArn": "...
        "LogGroupName": {
          "Ref": "GenerateLogGroup"
        }
      }
    },
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: img-serverless
# app and org for use with dashboard.serverless.com
app: img-serverless
org: eyzhub

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.stage, 'dev'}
  region: eu-central-1
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  logs:
    restApi:
      accessLogging: false
      fullExecutionData: false
      level: ERROR
# you can add packaging information here
package:
  exclude:
    - node_modules/@jimp/**/test/images/**
    - node_modules/**/**test**/**
    - '*.ts*'
functions:
  generate:
    handler: handler.generate
    # you can overwrite defaults here
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6
    environment:
      secretAccessKey: ${param:secretAccessKey}
      accessKeyId: ${param:accessKeyId}
      dropboxKey: ${param:dropboxKey}
      dropboxSecret: ${param:dropboxSecret}
      dropboxToken: ${param:dropboxToken}
      kmc_admin_secret: ${param:kmc_admin_secret}
      kmc_secret: ${ param:kmc_secret }
      kmc_partnerId: ${ param:kmc_partnerId }
      kmc_subpartnerId: ${ param:kmc_subpartnerId }
    events:
        - http:
            method: ANY
            path: /
        - http:
            method: ANY
            path: /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - aws-serverless-api-cloudfront

custom:
  stage: ${file(config_utils.js):getStage}
  defaultTTL:
    devimg: 60
    img: 0
    other: 3600
  concurrency:
    devimg: 0
    img: 2
    other: 0
  apigwBinary:
    types:
      - '*/*'
      - 'application/octet-stream'
      - 'application/zip'
      - 'image/png'
      - 'image/jpeg'
  apiCloudFront:
    compress: true
    fullDomainName: ${file(config_utils.js):getAllDomainAlternatives}
    certificate: ${param:certificate}
    priceClass: PriceClass_100
    querystring: none
    cookies: none
    defaultTTL: ${self:custom.defaultTTL.${self:custom.stage}, self:custom.defaultTTL.other}
    maxTTL: ${self:custom.defaultTTL.${self:custom.stage}, self:custom.defaultTTL.other}

```

</details>

<details>
<summary><b><code>Serverless Pro</code> output</b></summary>

```
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.............
Serverless: Operation failed!
Serverless Error ----------------------------------------
 
  An error occurred: CWLSubFilterApiGatewayLogGroupEuCentral1 - The specified log group does not exist. (Service: AWSLogs; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 36837529-14b4-4a5b-8e76-d2a1d01116c2; Proxy: null).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.1
     Framework Version:         2.43.1
     Plugin Version:            5.1.4
     SDK Version:               4.2.2
     Components Version:        3.10.1
```

</details>

<b>Installed version</b>

```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.22.1
     Framework Version:         2.43.1
     Plugin Version:            5.1.4
     SDK Version:               4.2.2
     Components Version:        3.10.1
```
