### ISSUE TITLE
IAM error using a custom deployment role and s3 events

### ISSUE THREAD

**Issue by sensiblejay** [serverless/serverless#9553]
Small bit of background, I've been transitioning a serverless application from being deployed with administrator privileges to one with something a bit more locked down. I ran across a strange issue.

When configuring a function to use S3 events from an existing bucket, and when using a custom cloudformation role, there is an automatically defined support lambda which tries to assume the custom cloudformation role.  

This happens [here in the code](https://github.com/serverless/serverless/blob/7d6bc45b0d1967984b037f3955173d9594f63a8a/lib/plugins/aws/customResources/index.js#L183
).
```javascript
if (customDeploymentRole) {
      customResourceFunction.Properties.Role = customDeploymentRole;
}
```

I believe this role should be a lambda execution role instead.

The function also uses the existence of the custom deployment role to decide if it should create a one-off role for the lambda to assume. I'm not certain what the correct logic is there.

In my case I am also defining a custom lambda execution role and I would want that used here - however I also noticed that this lambda has no triggers defined so I'm not sure why it's necessary. However, if I remove the `existing: true` line from the function definition, it tries to recreate the bucket, which also errors out the deployment.

A fake but representative `serverless.yml` to describe the relevant pieces is as follows.
```yaml
provider:
  iam:
    role: my-lambda-execution-role
    deploymentRole: my-cloudformation-deployment-role

...
functions:
    my_s3_watcher:
      handler: my-handler
      events:
        - s3:
            bucket: my-existing-bucket
            event: s3:ObjectCreated:Put
            existing: true
```

executed with

```shell
sls deploy
```

resulting in
```shell
Serverless Error ----------------------------------------
 
  An error occurred: CustomDashresourceDashexistingDashs3LambdaFunction - Resource handler returned message: "User: ${arn for my-cloudformation-deployment-role}/AWSCloudFormation is not authorized to perform: iam:PassRole on resource: ${arn for my-cloudformation-deployment-role}"
```

Installed version

```
Framework Core: 2.44.0 (local)
Plugin: 5.2.0
SDK: 4.2.3
Components: 3.11.0
```
