### ISSUE TITLE
serverless deploy gets stuck forever after printing Endpoints

### ISSUE THREAD

**Issue by premraval-pr** [serverless/serverless#9555]
I have created a REST API using NodeJs and TypeScript using [aws-nodejs-typescript](https://github.com/serverless/serverless/tree/master/lib/plugins/create/templates/aws-nodejs-typescript) template. The whole code works fine on localhost using serverless-offline but as soon as I run serverless deploy, it starts all the steps, and then after printing endpoints, functions, and layers, it gets stuck. If I try to run the Endpoints given above, I get`{ "message": "Internal Server Error"}`  as a response to all POST, PATCH, and DELETE requests and all GET requests show some CloudFront error.

<details>
<summary><code>serverless.ts</code></summary>

```ts
import type { AWS } from "@serverless/typescript";
import {
	getUser,
	addUser,
	delUser,
	patchUser,
	loginUser,
	getUserByToken,
	getBuildings,
	addBuilding,
	delBuilding,
	patchBuilding,
	// getTemplates,
	addTemplate,
	delTemplate,
	patchTemplate,
	getUserLogs,
	getTemplateLogs,
	addUserLog,
	addTemplateLog,
	patchTemplateLog,
	patchIntent,
	getSpecific,
	analyzeEmail,
	smallTalk
} from "@functions/index";
import { default as connect } from "@db/connectMongo";

connect();

const serverlessConfiguration: AWS = {
	service: "stan-backend",
	frameworkVersion: "2",
	custom: {
	},
	plugins: [],
	provider: {
		name: "aws",
		runtime: "nodejs14.x",
		apiGateway: {
			minimumCompressionSize: 1024,
			shouldStartNameWithService: true,
		},
		environment: {
			AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1",
		},
		lambdaHashingVersion: "20201221",
	},
	// import the function via paths
	functions: {
		getUser,
		addUser,
		delUser,
		patchUser,
		loginUser,
		getUserByToken,
		getBuildings,
		addBuilding,
		patchBuilding,
		delBuilding,
		// getTemplates,
		addTemplate,
		delTemplate,
		patchTemplate,
		getUserLogs,
		getTemplateLogs,
		addUserLog,
		addTemplateLog,
		patchTemplateLog,
		patchIntent,
		getSpecific,
		analyzeEmail,
		smallTalk
	},
};

module.exports = serverlessConfiguration;

```

</details>

<details>
<summary><b><code>SLS_DEBUG=* serverless deploy</code> output</b></summary>

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Deprecation warning: Starting with next major version, "http.request.schema" property will be replaced by "http.request.schemas".
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_SCHEMAS
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Db Connected!!
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service stan-backend.zip file to S3 (36.22 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
................................................................................................................................................
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: stan-backend
stage: dev
region: us-east-1
stack: stan-backend-dev
resources: 150
api keys:
  None
endpoints:
  GET - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user/{email}
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user
  DELETE - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user
  PATCH - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user/login
  GET - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user/token/{token}
  GET - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/buildings/{building_token}
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/buildings
  PATCH - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/buildings
  DELETE - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/buildings
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/templates
  DELETE - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/templates
  PATCH - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/templates
  GET - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/logs/users
  GET - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/logs/templates
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/logs/users
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/logs/templates
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/logs/templates/review
  PATCH - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/intent
  GET - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/templates/{id}/{building_name}/{datetime}
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user/email
  POST - https://rkmg39eisf.execute-api.us-east-1.amazonaws.com/dev/user/smalltalk
functions:
  getUser: stan-backend-dev-getUser
  addUser: stan-backend-dev-addUser
  delUser: stan-backend-dev-delUser
  patchUser: stan-backend-dev-patchUser
  loginUser: stan-backend-dev-loginUser
  getUserByToken: stan-backend-dev-getUserByToken
  getBuildings: stan-backend-dev-getBuildings
  addBuilding: stan-backend-dev-addBuilding
  patchBuilding: stan-backend-dev-patchBuilding
  delBuilding: stan-backend-dev-delBuilding
  addTemplate: stan-backend-dev-addTemplate
  delTemplate: stan-backend-dev-delTemplate
  patchTemplate: stan-backend-dev-patchTemplate
  getUserLogs: stan-backend-dev-getUserLogs
  getTemplateLogs: stan-backend-dev-getTemplateLogs
  addUserLog: stan-backend-dev-addUserLog
  addTemplateLog: stan-backend-dev-addTemplateLog
  patchTemplateLog: stan-backend-dev-patchTemplateLog
  patchIntent: stan-backend-dev-patchIntent
  getSpecific: stan-backend-dev-getSpecific
  analyzeEmail: stan-backend-dev-analyzeEmail
  smallTalk: stan-backend-dev-smallTalk
layers:
  None
Serverless: Invoke aws:deploy:finalize

```

</details>

<b>Installed version</b>

```
Framework Core: 2.44.0
Plugin: 5.2.0
SDK: 4.2.3
Components: 3.11.0
```
