### ISSUE TITLE
Unrecognized CLI Options

### ISSUE THREAD

**Issue by rsd-raul** [serverless/serverless#9576]
### Context:
Our use case requires deploying the same infrastructure twice (or more) with different stack names, so I'm trying to set up some fairly standard CLI Options to achieve this as we currently do with Serverless 1.X.

Our deployment looks like:

```
sls deploy --stackName NAME_A --profile production --stage prod --region us-west-1
sls deploy --stackName NAME_B --profile production --stage prod --region us-west-1
```

Similarly, our removals are:

```
sls remove --stackName NAME_A --profile production --stage prod --region us-west-1
sls remove --stackName NAME_B --profile production --stage prod --region us-west-1
```

### Issue:
Right now, when deploying just with the --stackName option:
```
sls deploy --stackName test
```
I get the warning:
> Deprecation warning: Detected unrecognized CLI options: "--stackName".
> Starting with the next major, Serverless Framework will report them with a thrown error
> More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS

And as expected, it uses the default value specified on the serverless.yml, completely ignoring the CLI.

On the other hand, as I'm not overriding the service.name as I used to do, I don't think I'll be able to deploy 2 Stacks as they share the same Service name, thus sharing some resource names... Any advice on that front would be much appreciated.

<details>
<summary><code>serverless.yml</code></summary>

```yaml

service: MyServiceName

frameworkVersion: '2'

# Enabling future default behaviors
useDotenv: true
configValidationMode: error
variablesResolutionMode: 20210326

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-tree-shake

package:
  individually: true
  excludeDevDependencies: false

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

  stackName: ${opt:stackName, 'T001'}
  # profile: ${opt:profile, 'development'}      # AWS Credentias profile to use.
  stage: ${opt:stage, 'dev'}                  # Options 'dev' || 'prod'
  region: ${opt:region, 'us-west-2'}

functions:
  hello:
    handler: lambdas/test_lambda/src/handler.hello
    events:
      - http:
          path: /
          method: get
```

</details>

<details>
<summary><b><code>sls deploy --stackName test</code> output</b></summary>

```
Serverless: Deprecation warning: Detected unrecognized CLI options: "--stackName".
            Starting with the next major, Serverless Framework will report them with a thrown error
            More Info: https://www.serverless.com/framework/docs/deprecations/#UNSUPPORTED_CLI_OPTIONS
Serverless: Compiling with Typescript...
Serverless: Typescript compiled.
Serverless: Packaging service...
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service hello.zip file to S3 (129.95 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
............................
Serverless: Stack update finished...
Service Information
service: MyServiceName
stage: dev
region: us-west-2
stack: T001
resources: 10
api keys:
  None
endpoints:
  GET - https://hoq6mlhp2c.execute-api.us-west-2.amazonaws.com/dev/
functions:
  hello: MyServiceName-dev-hello
layers:
  None
```

</details>

<b>Installed version</b>

Framework Core: 2.45.1
Plugin: 5.3.0
SDK: 4.2.3
Components: 3.11.0

**Comment by medikoo** [comment]
@rsd-raul use environment variables instead:

```yml
provider:
  stackName: ${env:STACK_NAME, 'T001'}
```

```
STACK_NAME=test sls deploy
```

--- 

We've introduced validation of CLI options, and that cannot be done reliably without removing support for _free form_ options. For free form process configuration properties, we advise to use environment variables instead.

**Comment by rsd-raul** [comment]
Understood, it's a shame as I thoroughly enjoyed the custom CLI options, but I get it validation and custom options are always compatible.

Closing the issue.

**Comment by pgrzesik** [comment]
Hey @rsd-raul - I have one additional question - what is your motivation behind deploying the exact same service in the same stage multiple times under different stack names? It's generally discouraged, as internally Framework highly depends on uniqueness of `service` and `stage` combination and you might stumble upon unexpected issues moving forward with such pattern.

**Comment by rsd-raul** [comment]
Hey @pgrzesik, in our case Service and StackName are one and the same, that's why we don't run into issues, without custom CLI options it means I'll have to override service.name with ENV variables, instead of doing what we used to do:
```
service:
  name: ${self:provider.stackName}

 ...

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

  stackName: ${opt:stackName, 'T001'}
```

Btw, having a hard time figuring out how to set up the service.name after [the deprecation](https://www.serverless.com/framework/docs/deprecations/#SERVICE_OBJECT_NOTATION), is it now something like provider.serviceName?
