### ISSUE TITLE
Superfluous `S3OriginConfig` added to generated cloudformation template

### ISSUE THREAD

**Issue by Arachin** [serverless/serverless#9584]
When using `npx serverless -- package` with the following Cloudformation config, an additional and unwanted `S3OriginConfig` parameter is generated (in addition to the `CustomOriginConfig ` we specify ourselves), resulting in the error `Exactly one of CustomOriginConfig and S3OriginConfig must be specified`.

The issue only seems to affect the first origin specified.

The issue is solved by re-ordering the origins so that the s3 origin is defined first.

Might be related to: https://github.com/serverless/serverless/issues/7485

<details>
<summary><code>serverless.yml</code></summary>

```yaml
provider:
  name: aws
  stage: ${opt:stage}
  versionFunctions: false
  runtime: nodejs12.x
  tracing:
    lambda: true
  region: us-east-1
  deploymentBucket:
    name: ...
  stackTags:
    environment: ${self:provider.stage}
  logRetentionInDays: 30

resources:
  extensions:
    RouteLambdaFunction:
      DeletionPolicy: Delete
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: ...
          DefaultCacheBehavior:
            CachePolicyId: ...
            OriginRequestPolicyId: ...
            TargetOriginId: s3/${self:custom.config.s3OriginBucketName}.s3.amazonaws.com${self:custom.config.s3OriginPath}
            TrustedKeyGroups:
              - ${self:custom.config.cloudFrontURLSigningKeyGroupId}
            ViewerProtocolPolicy: redirect-to-https
          Enabled: true
          Origins:
            - DomainName: ${self:custom.config.<api-gateway-thing>}
              Id: ${self:custom.config.<api-gateway-thing>}
              OriginPath: /api
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
            - DomainName: ${self:custom.config.<another-api-gateway-thing>}
              Id: ${self:custom.config.<another-api-gateway-thing>}
              OriginPath: /api
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
            - DomainName: ${self:custom.config.s3OriginBucketName}.s3.amazonaws.com
              Id: s3/${self:custom.config.s3OriginBucketName}.s3.amazonaws.com${self:custom.config.s3OriginPath}
              OriginPath: ${self:custom.config.s3OriginPath}
              S3OriginConfig:
                OriginAccessIdentity: origin-access-identity/cloudfront/${self:custom.config.cloudFrontOriginAccessIdentityId}
```

</details>

<details>
<summary><b><code>npx serverless -- package</code> output</b></summary>

```
          "Origins": [
            {
              "DomainName": "...",
              "OriginPath": "/3392",
              "S3OriginConfig": {},
              "Id": "...",
              "CustomOriginConfig": {
                "OriginProtocolPolicy": "https-only"
              }
              ]
            },
            {
              "DomainName": "...",
              "Id": "...",
              "OriginPath": "/api",
              "CustomOriginConfig": {
                "OriginProtocolPolicy": "https-only"
              }
            },
            {
              "DomainName": "...",
              "Id": "s3/<bucket-name>.s3.amazonaws.com/3392",
              "OriginPath": "/3392",
              "S3OriginConfig": {
                "OriginAccessIdentity": "..."
              }
            }
          ] 
```

</details>

<b>Installed version</b>

```
Framework Core: 2.45.2 (local)
Plugin: 5.3.0
SDK: 4.2.3
Components: 3.12.0
```
