### ISSUE TITLE
Serverless incorrectly warns that `TrustedKeyGroups` as a CloudFront behavior is invalid

### ISSUE THREAD

**Issue by dave-continuum-media** [serverless/serverless#9595]
Serverless complains that `TrustedKeyGroups` isn't a valid attribute but it deploys correctly and CloudFormation documentation states that it's a valid part of the cache behaviour.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-trustedkeygroups

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: static
variablesResolutionMode: 20210326

provider:
  name: aws
  stage: ${opt:stage}
  versionFunctions: false
  runtime: nodejs12.x
  tracing:
    lambda: true
  region: us-east-1
  deploymentBucket:
    name: serverless-deploy
  stackTags:
    environment: ${self:provider.stage}
  logRetentionInDays: 30

resources:
  extensions:
    RouteLambdaFunction:
      DeletionPolicy: Delete
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: !Join [ ' ', [ 'Otis Client stack', !Ref AWS::StackName ] ]
          DefaultCacheBehavior:
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
            TargetOriginId: s3/${self:custom.config.s3OriginBucketName}.s3.amazonaws.com${self:custom.config.s3OriginPath}
            TrustedKeyGroups:
              - ${self:custom.config.cloudFrontURLSigningKeyGroupId}
            ViewerProtocolPolicy: redirect-to-https
          Enabled: true
          Origins:
            - DomainName: ${self:custom.config.s3OriginBucketName}.s3.amazonaws.com
              Id: s3/${self:custom.config.s3OriginBucketName}.s3.amazonaws.com${self:custom.config.s3OriginPath}
              OriginPath: ${self:custom.config.s3OriginPath}
              S3OriginConfig:
                OriginAccessIdentity: origin-access-identity/cloudfront/${self:custom.config.cloudFrontOriginAccessIdentityId}
            - DomainName: ${self:custom.config.apiDomain}
              Id: custom/${self:custom.config.apiDomain}
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
              
functions:
  route:
    handler: handlers/router.handler
    events:
      - cloudFront:
          eventType: viewer-request
          origin: s3://${self:custom.config.s3OriginBucketName}.s3.amazonaws.com${self:custom.config.s3OriginPath}
      - cloudFront:
          eventType: viewer-request
          pathPattern: /api/*
          origin: custom://${self:custom.config.apiDomain}
          behavior:
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
              - 'PUT'
              - 'POST'
              - 'PATCH'
              - 'DELETE'
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            TrustedKeyGroups:
              - ${self:custom.config.cloudFrontURLSigningKeyGroupId}

custom:
  config:
    cloudFrontURLSigningKeyGroupId: abcdef
    cloudFrontOriginAccessIdentityId: fedcba
    s3OriginBucketName: static
    s3OriginPath: /files
    apiDomain: api.serverless.com
```

</details>

<details>
<summary><b><code>serverless package --stage test</code> output</b></summary>

```
Serverless: Configuration warning at 'functions.route.events[1].cloudFront.behavior': unrecognized property 'TrustedKeyGroups'
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Packaging service...
Serverless: Excluding development dependencies...
```

</details>

<b>Installed version</b>

```
Framework Core: 2.35.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.3
```
