### ISSUE TITLE
HTTP API should have same behavior as REST API when attaching an authorizer

### ISSUE THREAD

**Issue by raytorres280** [serverless/serverless#9596]
Following #8781, I would expect after PR #9192 was merged that I should be able to utilize authorizers the same between httpApi events (HTTP) and http events (REST). Attempting to attach my authorizer to the httpApi endpoint still results in the error.

<details>
<summary><code>serverless.yml (works)</code></summary>

```yaml
functions:
  adminAuthorizer:
    handler: lambdex_handler.handler
    package:
      artifact: ./dist/services.live_receptionist/live_receptionist_service_admin_authorizer.zip

  get_is_enabled:
    handler: lambdex_handler.handler
    package:
      artifact: ./dist/services.live_receptionist/live_receptionist_service_get_is_enabled.zip
    events:
      - http:
          path: /get_is_enabled
          method: get
          authorizer: adminAuthorizer
```

</details>

<details>
<summary><code>serverless.yml (breaks)</code></summary>

```yaml
functions:
  ...

  update_status:
    handler: lambdex_handler.handler
    package:
      artifact: ./dist/services.live_receptionist/live_receptionist_service_update_status.zip
    events:
      - httpApi:
          path: /update_status
          method: get
          authorizer: adminAuthorizer

```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless Error ----------------------------------------

  Event references not configured authorizer 'adminAuthorizer'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.22.1
     Framework Version:         2.46.0 (local)
     Plugin Version:            5.3.0
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

</details>

<b>Installed version</b>

```
2.46.0
```
