### ISSUE TITLE
warning while resolving ssm parameter

### ISSUE THREAD

**Issue by Bolik777** [serverless/serverless#9597]
when i set the projectDir parameter, i see warnings coming from ssm parameters
```yaml
myFunction:
handler: functions/function.handler
memorySize: 128
environment:
my_var: ${ssm:/path/to/var~false}
```

and the warning is about the ssm parameter:

`
Cannot resolve variable at "functions.2.myFunction.environment.my_var": Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_, 
`

```yaml
service: my-service

custom: ${file(stages/${self:provider.stage}.yml)}

package:
  individually: true

projectDir: ../../../

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage,'dev'}


resources:
  - ${file(resources/sns.yml)}


functions:
  - ${file(resources/myFuncs.yml)}
```

</details>

<details>
<summary><b><code>serverless deploy --aws-profile my_profile</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "functions.2.myFunction.environment.my_var": Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_,
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Bundling with Webpack...
Serverless: Excluding external modules: aws-sdk
Serverless: No external modules needed
Serverless: Copying existing artifacts...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service myHandlerFunction.zip file to S3 (318.73 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......................................................................................................................................
Serverless: Stack update finished...
Service Information
service: my-service
stage: dev
region: eu-central-1
stack: my_stack_name
resources: 192
api keys:
  None
endpoints:
  - LIST OF ENDPOINTS
functions:
  - LIST OF FUNCTIONS
layers:
  None
functions
  functions
Serverless: Removing old service artifacts from S3...
```

</details>

<b>Installed version</b>

```
     Node Version:              14.15.0
     Framework Version:         2.45.2
     Plugin Version:            5.3.0
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

**Comment by medikoo** [comment]
@Bolik777 can you share content of `resources/myFuncs.yml`, especially how exactly `functions.2.myFunction.environment.my_var` property is configured.

My current assumption is that you're using legacy `~<instruction>` postfix, which names instruction which is not even supported in old resolver (hence it's ignored by new resolved and passed through to AWS request. If instruction would be valid you'd receive a warning about instruction which is about to be deprecated)

**Comment by Bolik777** [comment]
hi @medikoo ,

thanks for looking into it. I actually posted the contents of the resources/myFuncs.yml right on the top. Here is the complete setup including event config

```yaml

myFunction:
  handler: functions/function.handler
  memorySize: 128
  environment: 
    my_var: ${ssm:/path/to/var~false}
  events:
    - http:
        path: /path/subpath
        method: get
        cors: true
        private: true
        authorizer:
          type: COGNITO_USER_POOLS
          authorizerId: ${self:custom.apiAuthorizer}
```
