### ISSUE TITLE
Wrong provider initialization from file variable

### ISSUE THREAD

**Issue by jeanbmar** [serverless/serverless#9599]
A provider is incorrectly initialized when the 2 following conditions are met:
- The provider is referencing a file (common.yml)
- The file referenced is not located in the same directory as serverless.yml

Commands work fine if common.yml and serverless.yml are in the same directory (with adjusted path in serverless.yml of course).

`sls print` shows a wrong result related to this piece of code, but the real issue must happen somewhere else:
https://github.com/serverless/serverless/blob/93233d1abe217068cceb5310c519eea6e7e77350/lib/classes/Service.js#L121-L126

<details>
<summary><code>common.yml</code></summary>

```yaml
provider:
  name: aws
  region: eu-west-3
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
```
</details>
<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: foo
provider: ${file(../common.yml):provider}
```
</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider": Cannot load file from outside of a project directory (with "projectDir" setting you may extend project boundary)
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Configuration warning: Unrecognized provider '[object Object]'
Serverless:
Serverless: You're relying on provider plugin which doesn't provide a validation schema for its config.
Serverless: Please report the issue at its bug tracker linking: https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema
Serverless: You may turn off this message with "configValidationMode: off" setting
Serverless:

 Serverless Error ----------------------------------------

  The specified provider "[object Object]" does not exist.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.1
     Framework Version:         2.46.0
     Plugin Version:            5.3.0
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

</details>

<details>
<summary><b><code>sls print</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider": Cannot load file from outside of a project directory (with "projectDir" setting you may extend project boundary)
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
service:
  name: foo
provider:
  stage: dev
  name: 
    name: aws
    region: eu-west-3
    runtime: nodejs14.x
    stage: dev
```

</details>

<b>Installed version</b>

```
Framework Core: 2.46.0
Plugin: 5.3.0
SDK: 4.2.3
Components: 3.12.0
```
