### ISSUE TITLE
cloudfront.behaviour.CachePolicyId not respected

### ISSUE THREAD

**Issue by Arachin** [serverless/serverless#9606]
Specifying the `CachePolicyId` within `cloudfront.behaviour` is ignored, and must be replaced with `cloudfront.cachePolicy.id`. If this is intentional we'd expect a warning in the output.

<details>
<summary><code>serverless.yml</code></summary>

**CachePolicyId ignored:**
```yaml
- cloudFront:
  eventType: viewer-request
  pathPattern: /api/*
  origin: custom://abc
  behavior:
    ViewerProtocolPolicy: redirect-to-https
    AllowedMethods:
      - 'GET'
      - 'HEAD'
      - 'OPTIONS'
      - 'PUT'
      - 'POST'
      - 'PATCH'
      - 'DELETE'
    CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
    OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
    TrustedKeyGroups:
      - example
```

**Works:**
```yaml
- cloudFront:
  eventType: viewer-request
  pathPattern: /api/*
  origin: custom://abc
  cachePolicy:
    id: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
  behavior:
    ViewerProtocolPolicy: redirect-to-https
    AllowedMethods:
      - 'GET'
      - 'HEAD'
      - 'OPTIONS'
      - 'PUT'
      - 'POST'
      - 'PATCH'
      - 'DELETE'
    OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
    TrustedKeyGroups:
      - example
```

</details>

<b>Installed version</b>

```
Framework Core: 2.46.0
Plugin: 5.3.0
SDK: 4.2.3
Components: 3.12.0
```
