### ISSUE TITLE
provider.iam.role.name not used

### ISSUE THREAD

**Issue by joeythomaschaske** [serverless/serverless#9607]
The framework does not use the `provider.iam.role.name` value I am passing it. The default just uses the `serviceName` but we deploy multiple instances of the same stack under different stages and need to pass in the stage as well to make the LambdaExecutionRole unique

```yaml
  iam:
    role:
      name: 'override'
      statements: ${file(./shared-attributes.yml):iamRoleStatements}
```

```
 Serverless Error ----------------------------------------
 
  An error occurred: IamRoleLambdaExecution - payment-engine-admin-account-api-role already exists in stack arn:aws:cloudformation:us-east-1:671462319378:stack/payment-engine-admin-account-api-qa/e62369c0-9715-11eb-adfd-0e400500bd61.
```

```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.4
     Framework Version:         2.41.2 (local)
     Plugin Version:            5.1.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
```

**Comment by pgrzesik** [comment]
Hello @joeythomaschaske :wave: Thanks a lot for reporting. I've just tried to reproduce the issue but I couldn't, below is my config:

```
service: example-function

provider:
  name: aws
  iam:
    role:
      name: somenewname

functions:
  exampleFunction:
    handler: src/handler.exampleFunction
```

and the generated role has the proper name set:
```
"IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {...}
        "Policies": [...]
        "Path": "/",
        "RoleName": "somenewname"
      }
    },
```

Could you please provide a full reproducible example that I can execute on my side to nail down the cause of this bug? Could you also please try to run it with the latest version of the Framework?
