### ISSUE TITLE
Deploy finish successfully but error log was displayed.

### ISSUE THREAD

**Issue by yukitaka13-1110** [serverless/serverless#9608]
I deployed and success update resource.
But log output said fatal error occurred.

<img width="882" alt="スクリーンショット 2021-06-16 15 21 38" src="https://user-images.githubusercontent.com/22259776/122168280-0ef1d980-ceb7-11eb-8d5c-b1c58cb8c73e.png">

Is this error not related to deployment?

#### Version

```
$ serverless --version
Framework Core: 2.46.0
Plugin: 5.3.0
SDK: 4.2.3
Components: 3.12.0
```

#### Plugin I use
```yaml
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2

plugins:
  - serverless-appsync-plugin
```
