### ISSUE TITLE
Errors in variable sources are swallowed up

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#9610]
Given a plugin that provides a custom variable source (in my case Lift),
When the plugin throws an error when resolving a variable,
Then the error shown to the user is not the original error.

The user message is confusing: the error shown to the users should be the original error.

Actual output:

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.environment.QUEUE_URL": No construct named 'jobsABC' was found, the ${construct:jobsABC.queueUrl} variable is invalid.
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER

 Serverless Error ----------------------------------------

  Invalid variable reference syntax for variable construct:jobsABC.queueUrl. You can only reference env vars, options, & files. You can check our docs for more info.
```

Expected output (or similar):

```
 Serverless Error ----------------------------------------

  Cannot resolve variable at "provider.environment.QUEUE_URL": No construct named 'jobsABC' was found, the ${construct:jobsABC.queueUrl} variable is invalid.
```

Example `serverless.yml`:

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: foo
provider:
    name: aws
    environment:
        # There's a typo here: `jobsABC` is an unknown construct
        QUEUE_URL: ${construct:jobsABC.queueUrl}

functions:
    publisher:
        handler: publisher.handler

constructs:
    jobs:
        type: queue
        worker:
            handler: worker.handler

plugins:
    - serverless-lift
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.environment.QUEUE_URL": No construct named 'jobsABC' was found, the ${construct:jobsABC.queueUrl} variable is invalid.
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER

 Serverless Error ----------------------------------------

  Invalid variable reference syntax for variable construct:jobsABC.queueUrl. You can only reference env vars, options, & files. You can check our docs for more info.
```

</details>

<b>Installed version</b>

```
Framework Core: 2.46.0
Plugin: 5.3.0
SDK: 4.2.3
Components: 3.12.0
```
