### ISSUE TITLE
Using AWS Secrets Manager requires `~true` suffix on variables

### ISSUE THREAD

**Issue by anfreita** [serverless/serverless#9611]
Running sls version `2.35.0` but checking master this issue appears to still be there

Trying to pull in values from AWS Secrets Manager doesn't work as described in the documentation [here](https://www.serverless.com/framework/docs/providers/aws/guide/variables/#reference-variables-using-aws-secrets-manager). In order to tell the sdk to use decryption one needs to additionally append `~true` to the variable, e.g.

```
${ssm:/aws/reference/secretsmanager/secret-id~true}
```

Docs should be updated to reflect this.

**Comment by medikoo** [comment]
@anfreita thanks for report. Please upgrade to the latest version of a Framework (Documentation documents latest version)

**Comment by anfreita** [comment]
@medikoo thanks for the quick response. While I'm running an older version, the documentation still appears incorrect for the latest version of serverless. The portion of code I'm referring to is this [regex pattern](https://github.com/serverless/serverless/blob/v2.46.0/lib/classes/Variables.js#L66) (note this is in the latest tagged version) which is used [here](https://github.com/serverless/serverless/blob/v2.46.0/lib/classes/Variables.js#L814) to get a secret from SSM. That pattern will match an AWS Secrets Manager string (e.g. `${ssm:/aws/reference/secretsmanager/secret_ID_in_Secrets_Manager}`) but in order to actually get a secret from Secrets manager using the AWS SSM SDK, one needs to pass `WithDecryption=true` (as documented [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html)), which that function will only do if `~true` is included as a suffix on the given variable.

Take for example the aws-python template. Assuming you've set up a secret in AWS Secrets Manager called `foo`, the first one will throw a warning that it is unable to access that variable while the second will work. The documentation states that the first is the way to do it.

```
service: aws-python
functions:
  hello:
    handler: handler.hello
    environment:
      FOO: ${ssm:/aws/reference/secretsmanager/foo}  # will throw a warning and will be left out of the compiled cf stack
```

```
service: aws-python
functions:
  hello:
    handler: handler.hello
    environment:
      FOO: ${ssm:/aws/reference/secretsmanager/foo~true}  # will correctly resolve to the configured secret
```

I hope this is clear. This is not a question, I am not experiencing an issue or bug, this issue is only to point out an area of the documentation that is incomplete and hopefully help others that are running into the same thing I was.
