### ISSUE TITLE
Major feature drop in v 2.46.0 - provider.variableSyntax

### ISSUE THREAD

**Issue by secnerdette** [serverless/serverless#9612]
Hello,
`provider.variableSyntax` setting is essential for many serverless users including us because it's the only way we can add custom variables to generate our CloudFormation (CF) files in order to dynamically populate CF and that seems to have been dropped in the [new variables resolver release](https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER).  Additionally, the warning on it previously suggested the new resolver will be enforced starting v 3.0 . However, looks like it has already been enforced in v 2.46.0 making matters even worse. This changed abruptly broke our essential deployments last night. Please help us fix it.

Note: In the error dump below it will only show 'warnings' and seems to be working. However, when we deploy the code with serverless, it essentially tries to write an empty skeleton CF file, essentially blowing up our entire infra although there are no 'errors' anywhere technically since a skeleton CF file with no infra reference by variables is still a valid CF file.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: socless-playbooks

provider:
  name: aws
  runtime: python3.7
  variableSyntax: "\\${{([ :a-zA-Z0-9._,\\-\\/\\(\\)]+?)}}"
  stage: ${{opt:stage}}
  region: ${{opt:region}}

plugins:
  - sls-apb

custom:
  statesRole: ${{cf:socless-${{self:provider.stage}}.StatesExecutionRoleArn}}
  socless:
    CreateEvents: ${{cf:socless-${{self:provider.stage}}.CreateEvents}}
    MergeParallelOutput: ${{cf:socless-${{self:provider.stage}}.MergeParallelOutput}}
    Counter: ${{cf:socless-${{self:provider.stage}}.Counter}}
    AwaitMessageResponseActivity: ${{cf:socless-${{self:provider.stage}}.AwaitMessageResponseActivity}}
    SetInvestigationStatus: ${{cf:socless-${{self:provider.stage}}.SetInvestigationStatus}}
    QueryCustomMapping: ${{cf:socless-${{self:provider.stage}}.QueryCustomMapping}}
    AddCustomMapping: ${{cf:socless-${{self:provider.stage}}.AddCustomMapping}}
    CacheResults: ${{cf:socless-${{self:provider.stage}}.CacheResults}}
```

</details>

<details>
<summary><b><code>⚠️⚠️ serverless deploy $npm_package_config_stage</code> output</b></summary>

```
Serverless: Deprecation warning: Serverless Framework was enhanced with a new variables resolver which doesn't recognize "provider.variableSyntax" setting.Starting with a new major it will be the only resolver that's used.. Drop setting from a configuration to adapt to it
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: StepFunctions logging not enabled. To ship playbook logs, set custom.sls_apb.logging = true in serverless.yml
Serverless: Rendering State Machine for ./playbooks/abc/playbook.json...
Serverless: Rendering State Machine for ./playbooks/def/playbook.json...
Serverless: Deprecation warning: Unresolved variable references will be communicated with a thrown error, starting from next major
            More Info: https://www.serverless.com/framework/docs/deprecations/#VARIABLES_ERROR_ON_UNRESOLVED
 
 Serverless Warning --------------------------------------
```

</details>

<b>Installed version</b>

```
2.46.0
```
