### ISSUE TITLE
Nested variables are not resolved as expected

### ISSUE THREAD

**Issue by poldark101** [serverless/serverless#9619]
**Issue:**
I am working with a multi-service repo. I'm on 2.46.0 and I'm setting projectDir and the variablesResolutionMode in all my serverless.yml files.  This resolved my variables that were reaching outside of the current service directory.  However I am now having an issue with resolving the service name.  Perhaps plugin:serverless-pseudo-parameters is conflicting with the resolver.  
Note: config.dev.yml:servicePrefix -> references ->config.all.yml:servicePrefix

**serverless.yml**
```
projectDir: ../../
variablesResolutionMode: 20210326
service: ${file(${self:projectDir}deploy/serverless/config.${self:custom.myStage}.yml):servicePrefix}-xyz
custom:
  myStage: ${opt:stage, 'sandbox'}
  myVPC: ${file(${self:projectDir}deploy/serverless/config.${self:custom.myStage}.yml):myVPC}
  myAppName: ${self:service}
  myAppNameForStage: ${self:custom.myAppName}-${self:custom.myStage}
  accountId: !Ref AWS::AccountId

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.myStage}
  region: ${opt:region, 'us-east-1'}
  # LM app tags for account governance service
  stackTags: ${file(../../deploy/serverless/config.all.yml):stackTags}
  deploymentBucket:
    name: bucket-123
 
plugins:
  - serverless-pseudo-parameters
```

**Project Structure**
```
services
--service1
   --serverless.yml
--service2
   --serverless.yml
deploy
--serverless
```

Note: config.dev.yml:servicePrefix -> references ->config.all.yml:servicePrefix

**Output**
I get the following error on deploy:
_Serverless: Configuration warning at 'service.name': should match pattern "^[a-zA-Z][0-9a-zA-Z-]+$"
..
The stack service name "**${file(../../deploy/serverless/config.all.yml):servicePrefix}-xyz-dev**" is not valid. A service name should only contain alphanumeric (case sensitive) and hyphens. It should start with an alphabetic character and shouldn't exceed 128 characters._

```
serverless --version
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.46.0 (local)
Plugin: 5.4.0
SDK: 4.2.3
Components: 3.12.0
LIBP45P-11550CF:aws-help-services
```
