### ISSUE TITLE
Serverless: Auto update: Unexpected response from npm

### ISSUE THREAD

**Issue by MeRahulAhire** [serverless/serverless#9625]
I've update `sls` to following version
```js
Framework Core: 2.47.0
Plugin: 5.4.0
SDK: 4.2.3
Components: 3.12.0
```
and I'm suddenly unable to `sls deploy`  and gives me the following error.
```bash
Serverless: Auto update: Unexpected response from npm
```
Any idea on how to solve it?

**Comment by pgrzesik** [comment]
Hello @MeRahulAhire, thanks for reporting. Does that prevent you from deploying? It should only print this warning and still proceed normally with deployment - is that not the case?

**Comment by MeRahulAhire** [comment]
@pgrzesik 
It's not deploying. It gives that warning and then quits the process.

**Comment by medikoo** [comment]
@MeRahulAhire can you post full command output when run with `SLS_DEBUG=*`?

In our logic it's just a log that doesn't prevent any further processing, so I think issue lies somewhere else. Can you also post full content of `serveless.yml`, and confirm weather eventually used plugins do not influence the issue

**Comment by MeRahulAhire** [comment]
I think I got what's the problem with my yml script. The `serverless-ignore` plugin is causing that issue. After commenting it out, my stack gets deployed 

Here's the code below
```yml
service: s3-sample

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "s3:AbortMultipartUpload"
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
  environment:
    bucketName: ${self:custom.bucketName}     

custom:
  bucketName: random-name

functions:
  putObject:
    handler: objects/API/putObject.handler
    events:
      - http:
          path: /putObject
          method: post
          cors: true
  getSignedUrl:
    handler: objects/API/putPreSignedUrl.handler
    events:
      - http:
          path: /getSignedUrl
          method: post
          cors: true

  getUploadId:
    handler: objects/API/multiPartUpload/createMultiPartUpload.handler
    events:
      - http:
          path: /getUploadId
          method: post
          cors: true
  getUploadPart:
    handler: objects/API/multiPartUpload/getUploadPart.handler
    events:
      - http:
          path: /getUploadPart
          method: post
          cors: true 
  completeMultiPartUpload:
    handler: objects/API/multiPartUpload/completeMultipartUpload.handler
    events:
      - http:
          path: /completeUpload
          method: post
          cors: true   
  abortMultiPartUpload:
    handler: objects/API/multiPartUpload/abortMultiPartUpload.handler
    events:
      - http:
          path: /abortUpload
          method: post
          cors: true                            

          
resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: Private
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              ExposedHeaders:
                - ETag  
# plugins:
#   - serverless-ignore
```
