### ISSUE TITLE
shouldStartNameWithService ignored for HTTP API gateway

### ISSUE THREAD

**Issue by IlyaSemenov** [serverless/serverless#9631]
For HTTP API gateways, `provider.apiGateway.shouldStartNameWithService` is ignored. The API gateway is always named as `stage-service`.

### Expected

With `shouldStartNameWithService` enabled, HTTP API gateway is named as `service-stage`.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: xyz-web

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  endpointType: REGIONAL
  apiGateway:
    binaryMediaTypes:
      - "*/*"
    shouldStartNameWithService: true

package:
  patterns:
    - "!**"
    - dist/aws-lambda-handler/**
    - public/**

functions:
  vite:
    handler: dist/aws-lambda-handler/index.handler
    events:
      - httpApi: "*"
```

</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
❯ yarn serverless deploy
yarn run v1.22.10
$ /Users/semenov/work/xyz-web/node_modules/.bin/serverless deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service xyz-web.zip file to S3 (772.13 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
..............................
Serverless: Stack update finished...
Service Information
service: xyz-web
stage: dev
region: us-east-1
stack: xyz-web-dev
resources: 11
api keys:
  None
endpoints:
  ANY - https://yokkida.execute-api.us-east-1.amazonaws.com
functions:
  vite: xyz-web-dev-vite
layers:
  None
```

</details>

<b>Installed version</b>

```
❯ yarn serverless --version
yarn run v1.22.10
$ /Users/semenov/work/xyz-web/node_modules/.bin/serverless --version
Framework Core: 2.47.0 (local)
Plugin: 5.4.0
SDK: 4.2.3
Components: 3.12.0
```

___

The source of problem is clearly seen, for REST API this flag is taken into account:

https://github.com/serverless/serverless/blob/d7c39f082a874d8c913969866d11b15ef2e68b2f/lib/plugins/aws/lib/naming.js#L251-L260

and for HTTP API it is not:

https://github.com/serverless/serverless/blob/d7c39f082a874d8c913969866d11b15ef2e68b2f/lib/plugins/aws/lib/naming.js#L647-L656
