### ISSUE TITLE
Serverless creates cloudwatch related IAM policy statements with empty resources when ` disableLogs: true` option is set, custom IAM policies are added to functions.

### ISSUE THREAD

**Issue by sappusaketh** [serverless/serverless#9633]
Serverless in creating IAM policy statements with resources as `[]` when ` disableLogs: true` option is set and when managed policies are added to functions. Tried running sls package to see whats wrong turns out below statements are added to `IamRoleLambdaExecution`

```json
  "PolicyDocument": {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Effect": "Allow",
        "Action": [
          "logs:CreateLogStream",
          "logs:CreateLogGroup"
        ],
        "Resource": []
      },
      {
        "Effect": "Allow",
        "Action": [
          "logs:PutLogEvents"
        ],
        "Resource": []
      }

```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: aws-node # NOTE: update this with your service name

frameworkVersion: '>=2.0.0 <3.0.0'


provider:
  name: aws
  runtime: nodejs12.x
  iam: 
    role: 
      name: helloworld
      managedPolicies:
        - Ref: helloworldLambdaSharedManagedPolicies

functions:
  hello:
    handler: handler.hello
    disableLogs: true

custom:
  resources:
    helloworldLambdaSharedManagedPolicies:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement: 
            Effect: Allow
            Action: 
              - sqs:SendMessage
            Resource: "*"
```

</details>

<details>
<summary><b><code>sls deploy</code> output</b></summary>

```
Serverless Error ----------------------------------------
 
  An error occurred: IamRoleLambdaExecution - Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: db366463-cc87-4ebd-bfd9-907fe22c8af9; Proxy: null).
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.1
     Framework Version:         2.46.0 (local)
     Plugin Version:            5.4.0
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.46.0
Plugin: 5.4.0
SDK: 4.2.3
Components: 3.12.0
```
