### ISSUE TITLE
AWS: Go template - Internal server error on M1 chip

### ISSUE THREAD

**Issue by sysint64** [serverless/serverless#9645]
I tried to create the `aws-go` template without any changes and deploy it.
Using MacBook with M1 chip I get an Internal server error. When I tried to deploy my function manually I went to the console and try run test and got more details:

```
{
  "errorMessage": "fork/exec /var/task/reports: exec format error",
  "errorType": "PathError"
}
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: demo
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - httpApi:
          path: /hello
          method: get
  world:
    handler: bin/world
    events:
      - httpApi:
          path: /world
          method: get
```

</details>

<details>
<summary><b>command</b></summary>

```
make deploy
```

</details>

<b>Installed version</b>

```
Framework Core: 2.48.0
Plugin: 5.4.1
SDK: 4.2.3
Components: 3.12.0
```
