### ISSUE TITLE
provider.vpc.subnetIds (and securityGroupIds) does not support Fn::FindInMap

### ISSUE THREAD

**Issue by niclasmeier** [serverless/serverless#9652]
When using the `provider.vpc` settings to run Lambda functions in a VPC the configuration does not support the Cloudformation function `Fn::FindInMap`. We have a multi-account setup and therefore we require the account ID to be part of the lookup, this is why we are using `Fn::FindInMap` and a Cloudformation `Mapping` in the `resources` section (can be seen at the bottom of the file) .

The schema definition (`/lib/plugins/aws/provider.js`) does only cover a list of `awsCfInstruction` or `awsCfSplit ` it also should include `Fn::FindInMap` (any maybe more CF functions that can return arrays).

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: playground
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221


  vpc:
    securityGroupIds: sg-123
    subnetIds:
      Fn::FindInMap:
        - Ref: AWS::AccountId
        - Ref: AWS::Region
        - "ApplicationSubnets"

functions:
  hello:
    handler: handler.hello

# you can add CloudFormation resource templates here
resources:
  Mappings:
    000000000000:
      eu-central-1:
        ApplicationSubnets:
          - subnet-123
          - subnet-456
          - subnet-789
```

</details>

<details>
<summary><b><code>sls package</code> output</b></summary>

```
Serverless: Configuration warning:
Serverless:   at 'provider.vpc.subnetIds': unrecognized property 'Fn::FindInMap'
Serverless:   at 'provider.vpc.subnetIds': should have required property 'Fn::Split'
Serverless:
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Packaging service...
Serverless: Excluding development dependencies...

 Serverless Error ----------------------------------------

  No file matches include / exclude patterns

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.13.1
     Framework Version:         2.48.0
     Plugin Version:            5.4.2
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.48.0
Plugin: 5.4.2
SDK: 4.2.3
Components: 3.12.0
```
