### ISSUE TITLE
provider.apiGateway.resourcePolicy[].Principal.AWS should support intrinsic function

### ISSUE THREAD

**Issue by lephuongbg** [serverless/serverless#9661]
We are using `Fn:If` in the `Principal.AWS` value to dynamically specify the principal, like following:

```yaml
#...
        Principal:
          AWS:
            Fn::If:
              - Condition
              - Account1Arn
              - Account2Arn
```

This config currently gets a warning: `Configuration warning at 'provider.apiGateway.resourcePolicy[1].Principal.AWS': should be equal to constant`
