### ISSUE TITLE
Same function name as file name

### ISSUE THREAD

**Issue by singla96** [serverless/serverless#9688]
I accidentally used filename as function name too. e.g. filename = abc.js, main function = abc 

<details>
<summary><code>serverless.yml</code></summary>

```yaml
detailFunction:
    handler: src/func/v1/detailFunction.detailFunction
    events:
      - http:
          path: v1/detailFunction
          method: post
          cors: ${self:custom.cors}
          authorizer: ${self:custom.authorizer}
```

</details>

<details>
<summary><b><code>SET SLS_DEBUG=*&^nodemon -w src --exec "node %USERPROFILE%\\AppData\\Roaming\\npm\\node_modules\\serverless\\bin\\serverless.js offline -s dev"</code> output</b></summary>

```
⚠️⚠️ REPLACE WITH FULL COMMAND OUTPUT
```

</details>

<b>Installed version</b>

```
Framework Core: 2.40.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```
