### ISSUE TITLE
Unable to configure provisioned concurrency 0

### ISSUE THREAD

**Issue by jackmuskopf** [serverless/serverless#9715]
When using `configValidationMode: error` and provisioned concurrency is set to 0 for some function, an error is thrown requiring:
```
Configuration error at 'functions.authorizer.provisionedConcurrency': should be >= 1
```

### Use case description

This would be useful in cases where provisioned concurrency is only desired for certain stage deployments.  It allows the provisioned concurrency configuration to be conditional.

### Proposed solution

Allow provisioned concurrency 0 - it currently works without `configValidationMode: error`, which is useful in cases where provisioned currency is only desired for certain stage deployments.  It allows the provisioned concurrency configuration to be conditional.

```
functions:
  authorizer:
    handler: handler
    provisionedConcurrency: ${self:custom.config.authorizer-provisioned-concurrency}
```
