### ISSUE TITLE
Cognito  PostConfirmation trigger not being created.

### ISSUE THREAD

**Issue by nan140114** [serverless/serverless#9717]
I'm trying to create a lambda function with a Cognito User Pool trigger. The Function and User Pool are being created but the trigger isn't being created.

![image](https://user-images.githubusercontent.com/5685675/124856808-cf2b8880-df70-11eb-8878-f81c91c4c978.png)

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: vXXXXXX
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  createUser:
    handler: bin/create-user
    events:
      - cognitoUserPool:
          pool: MyUserPool
          trigger: PostConfirmation

  getUser:
    handler: bin/get-user
    events:
      - httpApi:
          path: /get-user
          method: get
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
........
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service vXXXXXX-back.zip file to S3 (7.67 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.............................................
Serverless: Stack update finished...
Serverless: Invoke aws:info
Service Information
service: vXXXXXX-back
stage: dev
region: us-east-1
stack: vXXXXXX-back-dev
resources: 16
api keys:
  None
endpoints:
  GET - https://XXXXXX.execute-api.us-east-1.amazonaws.com/get-user
functions:
  createUser: vXXXXXX-back-dev-createUser
  getUser: vXXXXXX-back-dev-getUser
layers:
  None
Serverless: Invoke aws:deploy:finalize
```

</details>

<b>Installed version</b>

```
$ serverless --version
Framework Core: 2.51.0 (standalone)
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.2
```
