### ISSUE TITLE
Serverless:   at 'functions.foo.http.request.template': should be object

### ISSUE THREAD

**Issue by bissli82** [serverless/serverless#9718]
I've upgraded from Serverless 1.4 to 2.50. 
When running serverless install plugin <> 
I'm getting warnings about my serverless.yml: 
On all the places I have includes e.g. ( template: ${file(./request_apigateway.yml)} ) on the serverless.yml

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: create-new-account

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage , 'dev'}
  region: ${opt:region,'us-west-1'}
  logRetentionInDays: 90
  versionFunctions: false
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
    
custom:
  stages:
    - dev
    - staging
    - prod


functions:
  SetUserConfirmedCreation:
    handler: lambdas.allplatforms.lambda_set_user_confirmed_creation.set_user_confirmed_creation
    timeout: 30
    events:
      - http:
          path: organizations/set-user-confirmed-creation
          method: post
          integration: lambda
          cors:
            allowCredentials: true
            origins:
              - https://${self:custom.domainName.${self:provider.stage}}
          request:
            template: ${file(./request_apigateway.yml)}
          response: ${file(./response_apigateway.yml)}
          authorizer: ${self:custom.authorizer}


package:
 

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-stage-manager
  - serverless-domain-manager
  - serverless-associate-waf
  - serverless-plugin-log-subscription
  - serverless-s3-sync

resources:
  Resources:
       


```

<summary><code>request_apigateway.yml</code></summary>

```
application/json: |
  #set( $body = $input.json("$") )
  #define( $loop )
    {
    #foreach($key in $map.keySet())
        #set( $k = $util.escapeJavaScript($key) )
        #set( $v = $util.escapeJavaScript($map.get($key)).replaceAll("\\'", "'") )
        "$k":
          "$v"
          #if( $foreach.hasNext ) , #end
    #end
    }
  #end

  {
    "customBody": $body,
    "method": "$context.httpMethod",

    #set( $map = $context.authorizer )
    "authorizer": $loop,

    #set( $map = $input.params().querystring )
    "querystring": $loop,

    #set( $map = $input.params().path )
    "path": $loop
  }
```

</details>

<details>
<summary><b><code>⚠️⚠️ REPLACE WITH FULL COMMAND NAME</code> output</b></summary>

```
Serverless: Deprecation warning: Support for Node.js versions below v12 will be dropped with next major release. Please upgrade at https://nodejs.org/en/
            More Info: https://www.serverless.com/framework/docs/deprecations/#OUTDATED_NODEJS
(node:275) ExperimentalWarning: The fs.promises API is experimental
(node:275) ExperimentalWarning: The dns.promises API is experimental
Serverless: Deprecation warning: "provider.region" is not accessible (configured behind variables which cannot be resolved at this stage).
            Starting with next major release, this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to this behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Configuration warning:
Serverless:   at 'functions.SetUserConfirmedCreation.events[0].http.request.template': should be object
Serverless:   at 'functions.SetUserConfirmedCreation.events[0].http.response': should be object

```
<summary><code>response_apigateway.yml</code></summary>

```
headers:
  Content-Type: "'application/json'"
  Access-Control-Allow-Credentials: "'true'"
template: $input.json("$")
statusCodes:
  400:
    pattern: '.*"statusCode":[\s]*400.*'
    template: $input.path("$.errorMessage")
    headers:
      Content-Type: "'application/json'"
  500:
    pattern: '.*"statusCode":[\s]*500.*'
    template: $input.path("$.errorMessage")
    headers:
      Content-Type: "'application/json'"
</details>
```

<b>Installed version</b>

```
Framework Core: 2.50.0
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.2
```
