### ISSUE TITLE
TypeError: Cannot read property 'Fn::GetAtt' of undefined

### ISSUE THREAD

**Issue by chris-hinds** [serverless/serverless#9723]
Running `sls deploy --stage dev` when using `!ImportValue` is raising the following TypeError;

```
TypeError: Cannot read property 'Fn::GetAtt' of undefined
```

The service that I am deploying is importing an output of another stack. This stack has already been deployed. There is only a single occurrence of `Fn::GetAtt` and it is in the stack that is already deployed. If I remove the `!ImportValue` the stack deploys fine.

Running with `SLS_DEBUG=*` doesn't give any extra info

<details>
<summary><code>serverless.yml</code></summary>

Stack I am trying to deploy now
```yaml
projectDir: ../
useDotenv: true
stage: dev # Default stage

plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-domain-manager

package:
  individually: true

custom:
  bundle: ${file(../commonServerlessConfig.yml):bundle}
  apiDomain: ${file(../commonServerlessConfig.yml):apiDomain}
  customDomain: ${file(../commonServerlessConfig.yml):customDomain}

provider:
  name: aws
  region: ${file(../commonServerlessConfig.yml):region}
  runtime: ${file(../commonServerlessConfig.yml):runtime}
  memorySize: ${file(../commonServerlessConfig.yml):memorySize}
  timeout: ${file(../commonServerlessConfig.yml):timeout}
  versionFunctions: ${file(../commonServerlessConfig.yml):versionFunctions}
  apiGateway: ${file(../commonServerlessConfig.yml):apiGateway}
  

functions:
  organisationEventHandler:
    handler: organisationEventHandler/index.organisationEventHandler
    name: organisations-event-handler
    description: Organisations event handler
    events:
      - sqs: !ImportValue OrganisationsQueueArn
```

Stack that makes use of `Fn::GetAtt` (this has already been deployed)
```

provider:
  name: aws
  region: eu-west-1
  stackName: ****-api-gateway

resources:
  Resources:
    ****ApiGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ****ApiGW

  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: ****ApiGW
      Export:
        Name: ****ApiGateway-restApiId

    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ****ApiGW
          - RootResourceId
      Export:
        Name: ****ApiGateway-rootResourceId
```

</details>

<details>
<summary><b><code>sls deploy --stage dev</code> output</b></summary>

```
Serverless: Copying existing artifacts...
Serverless: Packaging service...

 Type Error ----------------------------------------------

  TypeError: Cannot read property 'Fn::GetAtt' of undefined
      at /Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sqs.js:61:33
      at /Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sqs.js:70:15
      at Array.forEach (<anonymous>)
      at /Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sqs.js:44:28
      at Array.forEach (<anonymous>)
      at AwsCompileSQSEvents.compileSQSEvents (/Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/sqs.js:34:47)
      at PluginManager.invoke (/Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/classes/PluginManager.js:576:20)
      at async PluginManager.spawn (/Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/classes/PluginManager.js:598:5)
      at async Object.before:deploy:deploy [as hook] (/Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/plugins/deploy.js:60:11)
      at async PluginManager.invoke (/Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/classes/PluginManager.js:576:9)
      at async PluginManager.run (/Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/classes/PluginManager.js:634:7)
      at async Serverless.run (/Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/lib/Serverless.js:441:5)
      at async /Users/chinds/.nvm/versions/node/v14.15.5/lib/node_modules/serverless/scripts/serverless.js:745:9

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.5
     Framework Version:         2.51.1
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3
```

</details>

<b>Installed version</b>

```
Framework Core: 2.51.1
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.3
```
