### ISSUE TITLE
Serverless framework can't see configuration if it configured with variables when it tries to install plugin

### ISSUE THREAD

**Issue by mohovkm** [serverless/serverless#9731]
I have `servless.yml` configured with variables. It works fine with the syntax provided in the docs:
```bash
SLS_PROVIDER=aws sls deploy
```

However, when I use this syntax to install any plugin I receive configuration error:
Example commands (that suppose to work, but outputs an error):
```bash
SLS_PROVIDER=azure sls plugin install -n serverless-azure-functions
```
or
```bash
SLS_PROVIDER=azure sls plugin install -n serverless-python-requirements
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: MultiCloudDev

provider: ${self:custom.provider.${env:SLS_PROVIDER}}

functions: ${self:custom.functions.${env:SLS_PROVIDER}}

plugins:
  - serverless-azure-functions
  - serverless-python-requirements

package:
  patterns:
    - 'classes/**'
    - 'functions/**'

custom:
  provider:
    aws:
      name: aws
      runtime: python3.8
      stage: dev

    azure:
      name: azure
      region: West Europe
      runtime: python3.8
      os: linux 
      prefix: "multicloud"
      stage: dev

  functions:
    aws:
      main:
        handler: lambda_main.handler
        events:
          - http:
              path: /
              method: get
        name: aws-MultiCloudDev
        description: ${self:custom.description}
        memorySize: 512
        timeout: 10
    
    azure:
      azure-MultiCloudDev:
        handler: azure_main.main
        description: ${self:custom.description}
        events:
          - http: true
            methods:
              - GET
            path: /
            authLevel: function

  description: MiltiCloud solution to publish and run code with Azure Functions and AWS Lambda

  pythonRequirements:
    dockerizePip: true
    zip: false

```

</details>

<details>
<summary><b><code>SLS_PROVIDER=azure sls plugin install -n serverless-python-requirements</code> output</b></summary>

```
Serverless Error ----------------------------------------
 
Unexpected "0" function configuration: Expected object received '$')
 
Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.51.2
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3
```

</details>

<b>Installed version</b>

```
Framework Core: 2.51.2
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.3
```

<b>Desired behavior</b>
Support variables in yml with all the commands, especially with plugin install.

It will also be cool if we could install plugins only for desired provider, example:

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: MultiCloudDev

provider: ${self:custom.provider.${env:SLS_PROVIDER}}

functions: ${self:custom.functions.${env:SLS_PROVIDER}}

plugins: ${self:custom.plugins.${env:SLS_PROVIDER}}

custom:
  plugins:
    azure:
      - serverless-azure-functions
      - serverless-python-requirements
    aws:
      - serverless-python-requirements

...
```

**Comment by mohovkm** [comment]
There is another issue, related to config variables. Ping me, if I need to add this as a separate issue.

Serverless framework `plugin install` will not work if the `package` session will be configured with variables. Below is the full yml file, which works fine with the command:
```bash
SLS_PROVIDER=azure sls deploy
```

<details>

<summary><code>serverless.yml</code></summary>

```yaml
service: MultiCloudDev

provider: ${self:custom.provider.${env:SLS_PROVIDER}}

functions: ${self:custom.functions.${env:SLS_PROVIDER}}

plugins: ${self:custom.plugins.${env:SLS_PROVIDER}}

package: ${self:custom.package.${env:SLS_PROVIDER}}

custom:
  provider:
    aws:
      name: aws
      runtime: python3.8
      stage: dev

    azure:
      name: azure
      region: West Europe
      runtime: python3.8
      os: linux 
      prefix: "multicloud"
      stage: dev

  functions:
    aws:
      main:
        handler: lambda_main.handler
        events:
          - http:
              path: /
              method: get
        name: aws-MultiCloudDev
        description: ${self:custom.description}
        memorySize: 512
        timeout: 10
    
    azure:
      azure-MultiCloudDev:
        handler: azure_main.main
        description: ${self:custom.description}
        events:
          - http: true
            methods:
              - GET
            path: /
            authLevel: function

  description: MiltiCloud solution to publish and run code with Azure Functions and AWS Lambda

  pythonRequirements:
    dockerizePip: true
    zip: false

  plugins:
    azure:
      - serverless-azure-functions
      - serverless-python-requirements
    aws:
      - serverless-python-requirements
  
  package:
    azure:
      patterns:
        - 'classes/**'
        - 'functions/**'
        - '!lambda_main.py'
    aws:
      patterns:
        - 'classes/**'
        - 'functions/**'
        - '!azure_main.py'
```
</details>

Output of `plugin install` command with package configured with variables:

<details>

<summary><b><code>SLS_PROVIDER=azure sls plugin install -n serverless-python-requirements</code> output</b>
</summary>

```bash
Serverless Error ----------------------------------------
 
  Cannot resolve serverless.yml: "package.path" property is not accessible (configured behind variables which cannot be resolved at this stage)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.51.2
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3
```
</details>
