### ISSUE TITLE
Serverless fails to resolve function from Javascript file

### ISSUE THREAD

**Issue by conor-mullen** [serverless/serverless#9737]
After upgrading to the latest version of Serverless, my existing `serverless.yml` stopped working as Serverless cannot resolve the functions from Javascript files.

The latest version where this worked was `2.30.3` and this stopped working in `2.31.0`.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: foobar

# Varaibles will be resolved differently in serverless v3
# this ensures we are compatible https://www.serverless.com/framework/docs/deprecations#new-variables-resolver
variablesResolutionMode: 20210326

provider:
  # Lambdas will be hashed differently in serverless v3
  # see https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  lambdaHashingVersion: 20201221

  name: aws
  stackName: foobar-${self:provider.stage}
  runtime: nodejs14.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'development'}
  environment: 
    ROLE_ARN: ${self:custom.vaultConfig.ROLE_ARN}

custom:
  vaultConfig: ${file(./vault-config.js):${self:provider.stage}}

```

</details>

<details>
<summary><code>vault-config.js</code></summary>

```yaml
const production = () => {
	return {
		'ROLE_ARN': 'production'
	};
};

const development = () => {
	return {
		'ROLE_ARN': 'development'
	};
};

module.exports = ({ options }) =>  {
	return {
		[options.stage]: development,
		'production': production,
	};
};

```

</details>

<details>
<summary><b><code>./node_modules/.bin/serverless deploy --stage foobar</code> output</b></summary>

```
 Serverless Error ----------------------------------------
 
  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.environment.ROLE_ARN": Cannot resolve variable at "custom.vaultConfig": Source "file" returned not supported result: "[Function: development]",
    - Cannot resolve variable at "custom.vaultConfig": Source "file" returned not supported result: "[Function: development]"
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.13.0
     Framework Version:         2.51.2 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3
```

</details>

<b>Installed version</b>

```
Framework Core: 2.51.2 (local)
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.3
```
