### ISSUE TITLE
Unable to override `service` using command option

### ISSUE THREAD

**Issue by SkippyZA** [serverless/serverless#9753]
In my previous projects I was configuring the name of the service using a command option. This let my team each deploy their own stack using a unique CF stack name. This was done by setting `service: ${opt:serviceName, 'default-service-name'}`.

Since version 2.32.0, when attempting this, the commands fail with the following error: `Cannot resolve serverless.yml: "service" property is not accessible (configured behind variables which cannot be resolved at this stage)`.

If I switch to using an environment variable instead of a command options (`${opt:....` to ${env:....`) then it will succeed.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: ${opt:serviceName, 'hermes'}
frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  memorySize: 512
  versionFunctions: false
  logRetentionInDays: 14
  tracing:
    apiGateway: true
    lambda: 'Active'
  deploymentBucket:
    blockPublicAccess: true
    name: catalog.${self:provider.region}.deploys
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "*"
  environment:
    SERVICE_NAME: ${self:service}

plugins:
  - serverless-go-plugin

functions:
  hello:
    handler: function/hello/main.go
    events:
      - httpApi:
          path: /hello
          method: get
```
</details>

<details>
<summary><b><code>serverless deploy --serviceName dev1-hermes</code> output</b></summary>

```
 Serverless Error ----------------------------------------

  Cannot resolve serverless.yml: "service" property is not accessible (configured behind variables which cannot be resolved at this stage)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.3
     Framework Version:         2.44.0
     Plugin Version:            5.2.0
     SDK Version:               4.2.3
     Components Version:        3.11.0
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.52.0 (local)
Plugin: 5.4.3
SDK: 4.2.3
Components: 3.13.4
```
