### ISSUE TITLE
AWS HTTP Event Request URI not honored when Integration is AWS

### ISSUE THREAD

**Issue by whardier** [serverless/serverless#9772]
I believe this is not honoring the presence of a valid `request.uri` or a top level attribute along with `integration` when the integration is `AWS`.  As it stands the documentation for this is wrong OR I am missing something that will replace the URI with that of an AWS service.

https://github.com/serverless/serverless/blob/b775613d62ce3153084e3bff00a7db9420645be2/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js#L60-L83

Example config:

```
    events:
      - http:
          path: stripe/webhook/events
          method: POST
          integration: AWS
          request:
            uri:
              Fn::GetAtt: [sqsStripeWebhookEventsQueue, Arn]
            template:
              application/json: '{ "httpMethod" : "$context.httpMethod" }'
            passThrough: NEVER
```
