### ISSUE TITLE
Feature Request: Allow multiple comma- or list-delimited method values per API Gateway event

### ISSUE THREAD

**Issue by alecbw** [serverless/serverless#9782]
#### Q1: Description

Basically, I want to allow an API Gateway endpoint to tolerate exactly two HTTP verbs (`GET` and `POST`), but not `ANY`/`"*"` (it would appear the latter causes problems with CORS preflight OPTIONS, among other considerations).

It is certainly possible at the moment to do so by duplicating the `- http: ` event as such:
```
functions:
  function1:
    handler: folder/function1.lambda_handler
    events:
      - http:
          path: /path
          method: GET
      - http:
          path: /path
          method: POST
```
But I have quite a few functions, and each has a relatively involved CORS setup, so doing so would mean 50+ lines of duplicated YAML.

#### Q2: Proposed solution

Ideally, I could do either:
```
    events:
      - http:
          path: /path
          method: GET, POST
```
or
```
    events:
      - http:
          path: /path
          method: 
            - GET
            - POST
```

I realize having the same endpoint accept both verbs - rather than splitting it to two endpoints - is a little weird, bordering on an anti-pattern. But that's where my business logic is taking it.

#### My env

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.1
     Framework Version:         2.52.1
     Plugin Version:            5.4.3
     SDK Version:               4.2.5
     Components Version:        3.14.0

**Comment by pgrzesik** [comment]
Hello @alecbw :wave: Thanks a lot for submitting your proposal. I'm honestly a little bit on the fence with allowing such configuration pattern. On one hand it could be fine and we can generate proper resources for it, on the other, it looks a bit weird and I'm not sure if we should allow such option at all. As for sharing CORS configuration, did you consider `httpApi` event type instead of `http`? It allows for CORS configuration for all events/functions on provider level. 

@mnapoli What do you think from Framework's API standpoint about accepting/allowing to specify more than one supported method for an event?

**Comment by alecbw** [comment]
Appreciate the feedback, @pgrzesik. Agree that there is an implicit architecture style question baked into the feature request.

As for `httpApi` - we need API key gated endpoints (`private: true`), and HTTP API doesn't currently support them: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html

**Comment by mnapoli** [comment]
Hi, that's an interesting topic here 🤔 

> I realize having the same endpoint accept both verbs - rather than splitting it to two endpoints - is a little weird, bordering on an anti-pattern.

I wouldn't consider it _that_ weird TBH. After all, single-Lambda function APIs are a very widespread use case so I wouldn't judge.

My take would be: why not gather feedback by keeping the issue open? If there is demand, we can expect others to chime in, add 👍  and/or comment. After all, unless this issue duplicates another, this is the first time this is brought up so it might not be worth jumping the gun immediately.

Also, as you mentioned @pgrzesik, HTTP API kind of resolves the root cause (CORS). We could expect HTTP APIs to get feature parity with REST APIs eventually, so the root cause may disappear.

---

Separately from that, on the syntax, the feature would be to allow a list of methods (instead of a single method). That would make sense to represent it as a real YAML list, like any other list. I.e. something like:

```yaml
    method:
      - GET
      - POST
    # which can also be written in a short form:
    method: [GET, POST]
```

But I guess the syntax is a detail for now.
