### ISSUE TITLE
Environment variables defined with CloudFormation method Fn::ImportValue are not resolved correctly when referenced from IAM role statements

### ISSUE THREAD

**Issue by k0mmsussert0d** [serverless/serverless#9794]
Environment variables set with `Fn::ImportValue` intrinsic function are not resolved correctly when referenced from `iam.role.statements[].Resource[]`.

**Real life example:**
Set up 2 stacks – for the sake of example named **dependencies** and **main**. **dependencies** stack does not have any functions, it just defines some resources and exports them.

<details>
<summary><code>dependencies stack serverless.yml</code></summary>

```yaml
resources:
  Resources:
    Table:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: TableGSI
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
        BillingMode: PAY_PER_REQUEST
        TableName: table-stack-a
    Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: sls-bug-demo-bucket-stack-a
  Outputs:
    TableName:
      Value:
        Ref: Table
      Export:
        Name: ${self:provider.environment.DOMAIN_PREFIX}-table-name
    BucketName:
      Value:
        Ref: Bucket
      Export:
        Name: ${self:provider.environment.DOMAIN_PREFIX}-bucket-name
```

</details>

The other stack, **main**, import those values in `provider.environment` sections using `Fn::ImportValue` function. This works fine, and such defined variables can be referenced during runtime and in multiple other sections of the file.

<details>
<summary><code>main stack provider section</code></summary>

```yaml
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TABLE_NAME:
      'Fn::ImportValue': ${self:service}-deps-${sls:stage}-table-name
    BUCKET_NAME:
      'Fn::ImportValue': ${self:service}-deps-${sls:stage}-bucket-name
```

</details>

For example, `"{self:provider.environment.TABLE_NAME}"` works for setting properties of functions:
<details>
<summary><code>environment Fn::ImportValue value used in functions.?.handler</code></summary>

```yaml
functions:
  names:
    handler: "${self:provider.environment.TABLE_NAME}"
    events:
      - httpApi:
          method: GET
          path: /
```

</details>

I also tried using `"${self:provider.environment.TABLE_NAME}"` in properties under `provider` section. I can confirm it functions properly at least for `deploymentBucket` property.

However, when I try to reference environment variables from IAM role's resources,
<details>
<summary><code>environment Fn::ImportValue value used in iam.role.statements.Resources[] (BUG)</code></summary>

```yaml
service: sls-bug-demo
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TABLE_NAME:
      'Fn::ImportValue': ${self:service}-deps-${sls:stage}-table-name
    BUCKET_NAME:
      'Fn::ImportValue': ${self:service}-deps-${sls:stage}-bucket-name
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}"
          - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}/index"
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource:
          - "arn:aws:s3:::{$self:provider.environment.BUCKET_NAME}"
functions:
  names:
    handler: handler.handler
    events:
      - httpApi:
          method: GET
          path: /
```

</details>

and run `sls deploy` or `sls print`, I'm getting an error:
```
Trying to populate non string value into a string for variable ${sls:stage}. Please make sure the value of the property is a string.
```
and following warnings:
```
Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.iam.role.statements.0.Resource.0": Value not found at "self" source,
              - Cannot resolve variable at "provider.iam.role.statements.0.Resource.1": Value not found at "self" source
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
```

Adding `variablesResolutionMode: 20210326` changes the error:
```
 Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.iam.role.statements.0.Resource.0": Value not found at "self" source,
    - Cannot resolve variable at "provider.iam.role.statements.0.Resource.1": Value not found at "self" source
```

Here I provide full example, consisting of two serverless.yml files https://github.com/k0mmsussert0d/sls-varres-bug-demo
The first to be deployed is the one in `dependencies` directory, because it creates CF exports. Then, `main` deployment can be attempted to observe the bug.

**Expected behavior:**
As [stated in the docs](https://www.serverless.com/framework/docs/providers/aws/guide/iam#the-default-iam-role), I can use `can use Join, Ref or any other CloudFormation method or feature [for IAM role statements].` Therefore, I expect environment variables defined as results CloudFormation functions to be resolved properly while being referenced from IAM role statements, as they currently are in probably any other part of the structure of serverless.yml. Under current conditions, I fail to find a method of determining whether such environment variables can be referenced in a specific part of the structure or not.

<details>
<summary><b><code>SLS_DEBUG=* ../node_modules/.bin/sls print</code> output</b></summary>

```
 Serverless Error ----------------------------------------
 
  ServerlessError: Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.iam.role.statements.0.Resource.0": Value not found at "self" source,
    - Cannot resolve variable at "provider.iam.role.statements.0.Resource.1": Value not found at "self" source
      at module.exports (/home/max/Projects/sls-bug-demo/node_modules/serverless/lib/configuration/variables/eventually-report-resolution-errors.js:24:13)
      at /home/max/Projects/sls-bug-demo/node_modules/serverless/scripts/serverless.js:370:13
      at async /home/max/Projects/sls-bug-demo/node_modules/serverless/scripts/serverless.js:209:9
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.1
     Framework Version:         2.52.1 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.14.2
 
```

</details>

<b>Installed version</b>

```
Framework Core: 2.52.1 (local)
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.14.2
```

**Comment by pgrzesik** [comment]
Thanks for reporting @k0mmsussert0d :bow: So there are a few things to unpack:
1. The error you're seeing is not related to resolution of `${self:provider.environment.TABLE_NAME}` but rather to `${opt:region, self:provider.region}`. As `region` is not set via `opt` or set on `provider`, this resolution fails - you can provide a fallback value or use `${aws:region}` which is a shorthand for `${opt:region, self:provider.region, "us-east-1"}`
2. After resolving above, the error you will see will look like this ` Cannot resolve variable at "provider.iam.role.statements.0.Resource.0": String value consist of variable which resolve with non-string value`. As it says, the variable resolves to a non-string value which makes it impossible to construct the correct final string. 

As for the use of CF intrinsic functions - they can be used for IAM role statements as listed in documentation. In the example you've shared, you're trying to insert an CF intrinsic function that is an object inside a string value, which is impossible - in order to do such replacements in CF you would have to use e.g. `Sub`, `Fn:Join` functions, but crafting proper reference here would be quite cumbersome I believe. 

Alternatively, you could use `cf` variable source instead of using `Fn::Import` here to avoid using CF intrinsic functions: https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-cloudformation-outputs

When using `cf`, the resolution of values will happen during variable resolution on Framework side, not during actual deployment with CloudFormation as it is the case with CF intrinsic functions.

**Comment by k0mmsussert0d** [comment]
@pgrzesik thank you for your reply. I'm aware of `cf` variable source and actually used it as a workaround when I first encountered the problem (see https://github.com/k0mmsussert0d/sf-microblog/blob/master/services/api/serverless.yml).

As for using non-string values for properties requiring strings. Based on your explanation, I suppose that `Fn::ImportValue` is resolved by CloudFormation, not "locally" before a template is sent to AWS for deployment. Are other CF functions, like `Sub` or `Fn::Join` working in a different way then, resulting in string values being injected before actual deployment? I would be very thankful if you could put some light on it for me, please. If not terribly inconvenient, I'd use references to AWS documentation.

**Comment by pgrzesik** [comment]
Hey @k0mmsussert0d - all CF functions are not resolved locally but only during actual CloudFormation deployment, however, it is possible to compose/nest them using different functions like this:

```
!Join
  - ''
  - - 'arn:'
    - !Ref AWS::Partition
    - ':s3:::elasticbeanstalk-*-'
    - !Ref AWS::AccountId
```

taken from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-join.html

or 

```
Name: !Sub
  - www.${Domain}
  - { Domain: !Ref RootDomainName }
```

taken from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

**Comment by igor-levkov** [comment]
@k0mmsussert0d Just was handling same issue. So couple of observations:
1. Problem when you are trying to mix CF Intrinsic functions + serverless substitution.
2. If you defined mixed variable, i.e. using CF or CF + serverless features, then this variable must be referenced using Sub. Try something like:
```yaml
Action:
  - dynamodb:Query
Resource:
  - !Sub
    - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${tableName}"
    - tableName: ${self:provider.environment.TABLE_NAME}
```
**NOTE**. Short version of Sub won't work.
