### ISSUE TITLE
An error occurred: MainAlbListenerRule10 - Resource handler returned message: "Invalid request provided: AWS::ElasticLoadBalancingV2::ListenerRule Validation exception

### ISSUE THREAD

**Issue by IRCraziestTaxi** [serverless/serverless#9802]
While monitoring stack update progress, after a while, the following error occurs:

```
ServerlessError: An error occurred: MainAlbListenerRule10 - Resource handler returned message: "Invalid request provided: AWS::ElasticLoadBalancingV2::ListenerRule Validation exception" (RequestToken: xxx-xxx-xxx-xxx-xxx, HandlerErrorCode: InvalidRequest).
```

And nothing more. I have googled like crazy and found nothing useful for this error while using serverless. Obviously, since the error fails to give any hints as to why the listener rule is not validating, I do not know where to start. I borrowed this `serverless.yml` file from another working project.

Note: All instances of `xxx` in the file and output below are just masking. I have filled in the correct account IDs, ARNs, etc.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: app-name-api

plugins:
    - serverless-offline
    - serverless-webpack

custom:
    webpack:
        packager: 'npm'
        includeModules:
            forceInclude:
                - mysql

provider:
    name: aws
    stage: test
    runtime: nodejs14.x
    region: us-east-1
    profile: app-name-deploy
    deploymentBucket:
        blockPublicAccess: true
    vpc:
      securityGroupIds:
        - sg-xxx
      subnetIds:
        - subnet-xxx
        - subnet-xxx
    environment:
        API_GLOBAL_PREFIX: '/api/v1'
        APP_DOMAIN_EMAIL: 'noreply@mydomain.com'
        APP_NAME: 'App Name'
        APP_WEBSITE_URL: 'https://app.app-name.mydomain.com'
        TYPEORM_CONNECTION: 'mysql'
        TYPEORM_DATABASE: 'app-name-api'
        TYPEORM_HOST: 'xxx'
        TYPEORM_PASSWORD: 'xxx'
        TYPEORM_PORT: '3306'
        TYPEORM_USERNAME: 'xxx'
functions:
    main:
        handler: src/lambda.handler
        memorySize: 1024
        timeout: 900
        events:
            - alb:
                listenerArn: arn:aws:elasticloadbalancing:us-east-1:xxx:listener/app/app-name-api-test-public-alb/xxx/xxx
                priority: 10
                targetGroupName: app-name-api-test-target-group
                conditions:
                    host: api.app-name.test.mydomain.com
                    path: /api/v1/*
                healthCheck:
                    path: /api/v1/health
                    intervalSeconds: 35
                    timeoutSeconds: 30
                    healthyThresholdCount: 2
                    unhealthyThresholdCount: 2
                    matcher:
                        httpCode: '200'

```

</details>

<details>
<summary><b><code>SLS_DEBUG=* npm run sls:deploy -- --config brands/brand-name/config/serverless/serverless.test.yml</code> output</b></summary>

Note: Since I only have serverless installed locally and not globally, the `sls:deploy` script is a simple passthrough to `sls` in my package.json: `"sls:deploy": "sls deploy",`

```
IRCraziestTaxi@IRCraziestTaxis-MacBook-Pro app-name.api % SLS_DEBUG=* npm run sls:deploy -- --config brands/brand-name/config/serverless/serverless.test.yml

> app-name.api@0.0.1 sls:deploy /Users/IRCraziestTaxi/Projects/app-name.api
> sls deploy "--config" "brands/brand-name/config/serverless/serverless.test.yml"

Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.52.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command webpack
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Invoke webpack:validate
Serverless: Invoke webpack:compile
Serverless: Bundling with Webpack...
assets by path ../../dist/src/ 54 KiB 217 assets
assets by path ../../dist/libs/ 8.65 KiB
  assets by path ../../dist/libs/domain/src/ 7.68 KiB 20 assets
  assets by path ../../dist/libs/aws/src/*.ts 566 bytes
    asset ../../dist/libs/aws/src/aws.service.d.ts 459 bytes [compared for emit]
    asset ../../dist/libs/aws/src/index.d.ts 61 bytes [compared for emit]
    asset ../../dist/libs/aws/src/aws.module.d.ts 35 bytes [compared for emit]
    asset ../../dist/libs/aws/src/aws.service.spec.d.ts 11 bytes [compared for emit]
  assets by path ../../dist/libs/app/src/*.ts 430 bytes
    asset ../../dist/libs/app/src/app.service.d.ts 323 bytes [compared for emit]
    asset ../../dist/libs/app/src/index.d.ts 61 bytes [compared for emit]
    asset ../../dist/libs/app/src/app.module.d.ts 35 bytes [compared for emit]
    asset ../../dist/libs/app/src/app.service.spec.d.ts 11 bytes [compared for emit]
asset src/lambda.js 470 KiB [emitted] (name: src/lambda)
asset ../../dist/test/app.e2e-spec.d.ts 11 bytes [compared for emit]
modules by path ./src/ 427 KiB 193 modules
modules by path ./libs/ 33.2 KiB
  modules by path ./libs/domain/src/ 25.1 KiB 19 modules
  modules by path ./libs/app/src/*.ts 3.32 KiB 3 modules
  modules by path ./libs/aws/src/*.ts 4.72 KiB
    ./libs/aws/src/index.ts 686 bytes [built] [code generated]
    ./libs/aws/src/aws.module.ts 1.22 KiB [built] [code generated]
    ./libs/aws/src/aws.service.ts 2.82 KiB [built] [code generated]
modules by path external "@nestjs/ 294 bytes 7 modules
modules by path external "@responsekit/ 84 bytes
  external "@responsekit/nestjs" 42 bytes [built] [code generated]
  external "@responsekit/core" 42 bytes [built] [code generated]
12 modules
webpack compiled successfully in 9727 ms
Serverless: Invoke webpack:package
Serverless: WARNING: Could not determine version of module express
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: @nestjs/platform-express@^7.6.15, @nestjs/common@^7.6.15, reflect-metadata@^0.1.13, rxjs@^7.0.0, @nestjs/core@^7.6.15, aws-serverless-express@^3.4.0, express, @nestjs/swagger@^4.8.0, @responsekit/nestjs@^1.0.0, @responsekit/core@^1.0.1, typeorm-transactional-cls-hooked@^0.1.20, typeorm@^0.2.32, @nestjs/config@0.6.3, @nestjs/typeorm@^7.1.5, @nestjs/cqrs@^7.0.1, typeorm-linq-repository@^1.1.1, ts-simple-automapper@^1.0.3, class-transformer@^0.4.0, aws-sdk@^2.943.0, class-validator@^0.13.1, bcryptjs@^2.4.3, jsonwebtoken@^8.5.1, ts-simple-nameof@^1.3.1, mysql@^2.18.1
Serverless: WARNING: Could not determine version of module express
Serverless: Copying existing artifacts...
Serverless: Packaging service...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service app-name-api.zip file to S3 (24.37 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...........................
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3Axxx%3Astack%app-name-api-test%2Fxxx-xxx-xxx-xxx-xxx
 
 Serverless Error ----------------------------------------
 
  ServerlessError: An error occurred: MainAlbListenerRule10 - Resource handler returned message: "Invalid request provided: AWS::ElasticLoadBalancingV2::ListenerRule Validation exception" (RequestToken: 8200ada6-cdf9-08e2-e5f5-b667dbb91484, HandlerErrorCode: InvalidRequest).
      at /Users/IRCraziestTaxi/Projects/app-name.api/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:129:23
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async AwsDeploy.update (/Users/IRCraziestTaxi/Projects/app-name.api/node_modules/serverless/lib/plugins/aws/lib/updateStack.js:144:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.52.0 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.5
     Components Version:        3.13.4
 
Serverless: Deprecation warnings:

Service configuration is expected to be placed in a root of a service (working directory). All paths, function handlers in a configuration are resolved against service directory".
Starting from next major Serverless will no longer permit configurations nested in sub directories.
More Info: https://www.serverless.com/framework/docs/deprecations/#NESTED_CUSTOM_CONFIGURATION_PATH

Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES

Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-name.api@0.0.1 sls:deploy: `sls deploy "--config" "brands/brand-name/config/serverless/serverless.test.yml"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-name.api@0.0.1 sls:deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/IRCraziestTaxi/.npm/_logs/2021-08-03T20_57_29_429Z-debug.log
```

</details>

<b>Installed version</b>

```
Framework Core: 2.52.0 (local)
Plugin: 5.4.3
SDK: 4.2.5
Components: 3.13.4
```
