### ISSUE TITLE
AWS_PROFILE takes precedence over AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN

### ISSUE THREAD

**Issue by nicolaevladescu** [serverless/serverless#9821]
When trying to use AWS STS temporary credentials `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN`) via `export`, the `serverless` cli works as intended. But if `AWS_PROFILE` is present (exported in the current shell) is does not, it tries to use the profile.

So from what i know working with the AWS Python SDK, and the aws cli, every other env var should be ignored when the above trio of vars are present. I have no experience with the AWS Javascript SDK but i presume the credential discovery process should converge more or less. Am i wrong?

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: aws-python-rest-api-project

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
```

</details>

<details>
<summary><b><code>serverless info</code> output</b></summary>

```
 Serverless Error ----------------------------------------
 
  The security token included in the request is invalid.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.6.1
     Framework Version:         2.53.1
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.14.2
```

</details>

<b>Installed version</b>

```
Framework Core: 2.53.1
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.14.2
```
