### ISSUE TITLE
Improve message in `serverless` output

### ISSUE THREAD

**Issue by mnapoli** [serverless/serverless#9822]
I ran `serverless` in an existing service (that doesn't use the Dashboard).

It displayed the following message:

> Your project is live and available in ./sls-cli-design-api

That's incorrect in that case (the directory doesn't exist) because I ran `sls` **in** the service directory. The message should probably say something like:

> Your project is live.

---

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: sls-cli-design-api
frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs14.x
    stage: prod
    lambdaHashingVersion: 20201221
    environment:
        TABLE_NAME: ${construct:table.tableName}
        GITHUB_TOKEN_READ: ${ssm:/sls-cli-design-api/prod/github-token}

functions:
    refresh:
        handler: refresh.handler

constructs:
    table:
        type: database/dynamodb-single-table

plugins:
  - serverless-lift
```

</details>

<details>
<summary><b><code>sls</code> output</b></summary>

```

 Do you want to deploy your project? Yes

Packaging succesful

Deployment succesful

Your project is live and available in ./sls-cli-design-api

  Run serverless info in the project directory
    View your endpoints and services

  Run serverless deploy in the directory
    Redeploy your service after you've updated your service code or configuration

  Run serverless invoke and serverless logs in the project directory
    Invoke your functions directly and view the logs

  Run serverless in the project directory
    Add metrics, alerts, and a log explorer, by enabling the dashboard functionality
```

</details>

<b>Installed version</b>

```
2.53.1
```
