### ISSUE TITLE
Fn::ImportValue cross stack references not working with SNS Events

### ISSUE THREAD

**Issue by Borduhh** [serverless/serverless#9829]
When using `Fn::ImportValue` in the `sns` event, we get a deployment issue. We've tried directly importing them in the function event and importing them as a custom variable. When importing as a custom variable, we use them in the environment variables and they work.

### Version 1
serverless.yml
```yaml
custom:
  TransactionSNSArn: 
    Fn::ImportValue: our-exported-arn-${self:custom.resourceStage}
  
  TransactionSNSName:
    Fn::ImportValue: our-exported-topic-name-${self:custom.resourceStage}

functions:
  TestFunction:
    name: TestFunction
    handler: src/functions/testFunction.handler
    events:
      - sns:
          arn: ${self:custom.TransactionSNSArn}
          topicName: ${self:custom.TransactionSNSName}
```

### Version 2
```yaml
functions:
  TestFunction:
    name: TestFunction
    handler: src/functions/testFunction.handler
    events:
      - sns:
          arn: 
              Fn::ImportValue: our-exported-arn-${self:custom.resourceStage}
          topicName:
              Fn::ImportValue: our-exported-topic-name-${self:custom.resourceStage}
```

```
SLS_DEBUG=* serverless package --stage pr59 --package sls-package-output
```

```
Type Error ----------------------------------------------
 
  TypeError: name.replace is not a function
      at Object.normalizeNameToAlphaNumericOnly (/tmp/seed/source/node_modules/serverless/lib/plugins/aws/lib/naming.js:32:36)
      at Object.normalizeTopicName (/tmp/seed/source/node_modules/serverless/lib/plugins/aws/lib/naming.js:349:17)
      at Object.getLambdaSnsSubscriptionLogicalId (/tmp/seed/source/node_modules/serverless/lib/plugins/aws/lib/naming.js:479:82)
      at /tmp/seed/source/node_modules/serverless/lib/plugins/aws/package/compile/events/sns.js:185:64
      at Array.forEach (<anonymous>)
      at /tmp/seed/source/node_modules/serverless/lib/plugins/aws/package/compile/events/sns.js:63:28
      at Array.forEach (<anonymous>)
      at AwsCompileSNSEvents.compileSNSEvents (/tmp/seed/source/node_modules/serverless/lib/plugins/aws/package/compile/events/sns.js:59:47)
      at PluginManager.invoke (/tmp/seed/source/node_modules/serverless/lib/classes/PluginManager.js:576:20)
      at async PluginManager.run (/tmp/seed/source/node_modules/serverless/lib/classes/PluginManager.js:636:7)
      at async Serverless.run (/tmp/seed/source/node_modules/serverless/lib/Serverless.js:443:5)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:745:9
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.15.4
     Framework Version:         2.52.1 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.14.2
 
ERROR: name.replace is not a function
```

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.52.1 (local)
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.14.2
```
