### ISSUE TITLE
httpApi duplicate method for ANY too restrictive

### ISSUE THREAD

**Issue by kazkansouh** [serverless/serverless#9840]
I think the following check is not required:

https://github.com/serverless/serverless/blob/87ce28ee4ea0e975859b8d32be8f2edd824b4cda/lib/plugins/aws/package/compile/events/httpApi.js#L553-L557

Essentially, AWS will apply more specific routes first and then fall back to an `ANY` handler before falling back to the `$default` handler.

This means that a config such as the following needs an override to work as desired:

```yaml
functions:
  proxy:
    handler: handler.handler
    events:
      - httpApi:
          method: OPTIONS
          path: /a/{proxy+}
      - httpApi:
          method: '*'
          path: /a/{proxy+}
          authorizer:
            name: cognito
            scopes:
              - some-api-scope
```

That is, it need to be written as follows:
```yaml
functions:
  proxy:
    handler: handler.handler
    events:
      - httpApi:
          method: OPTIONS
          path: /a/{proxy+}
      - httpApi:
          method: GET
          path: /a/{proxy+}
          authorizer:
            name: cognito
            scopes:
              - some-api-scope
resources:
  extensions:
    HttpApiRouteGetProxyVar:
      Properties:
        RouteKey: ANY /a/{proxy+}
```

If its acceptable, I can submit a small PR that removes the identified check?
