### ISSUE TITLE
Serverless deploy throws Circular Dependency error for valid CloudFormation template

### ISSUE THREAD

**Issue by Gageperrin** [serverless/serverless#9841]
I am trying to deploy an RDS Aurora Serverless DB using the Serverless Framework. I am following the example provided [here](https://forum.serverless.com/t/aws-rds-aurora-serverless-questions/11720). The provided repo had some variable declaration errors, but the main problem comes when provisioning the instance itself.

Running `serverless deploy` triggers the following error:

```The CloudFormation template is invalid: Circular dependency between resources: [AuroraDBCluster, SecretRDSInstanceAttachment]```

However when I copy over the `ClusterSecret`, `AuroraDBCluster`, and `SecretRDSInstanceAttachment` resources to a CloudFormation template. The template deploys without any issues.

The RDS code itself seems to be basically an exact copy of what is provided in the [CloudFormation docs here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html#aws-resource-secretsmanager-secrettargetattachment--examples). Everything is fine on the CloudFormation side, but Serverless claims the CloudFormation template is not valid.

<details>
<summary><code>serverless.yml</code></summary>

Relevant top level `serverless.yml` snippets
```service: app-serverless
Description: App Infrastructure

frameworkVersion: '>=1.61.0 <=1.67.0'

plugins:
  - serverless-python-requirements


custom:
  stage: ${opt:stage, self:provider.stage}
  region:
    prod: us-east-2 # Ohio
    default: us-west-2 # Oregon
  DBdeletionPolicy:
    dev: Delete
    prod: Retain
  logRetention:
    prod: 180
    default: 14
  DBClusterARN:
    Fn::Join:
      - ':'
      - - 'arn:aws:rds'
        - Ref: 'AWS::Region'
        - Ref: 'AWS::AccountId'
        - 'cluster'
        - !Ref AuroraDBCluster
  DBUpdateReplacePolicy:
    dev: Delete
    prod: Retain
  DBClusterIdentifier: !Ref AuroraDBCluster
  DBBackupRetentionPeriod:
    dev: 1
    prod: 7
  DBDeletionProtection:
    dev: false
    prod: true
  DBAutopause:
    dev: true
    prod: true 
    default: true 

provider:
  name: aws
  runtime: python3.7
  stage: dev
  stackName: ${self:custom.stage}-${self:service.name}
  region: ${self:custom.region.${self:custom.stage}, self:custom.region.default}
  stackTags:
    APP: Test
    STAGE: ${self:custom.stage}
  logs:
    restApi: true
  logRetentionInDays: ${self:custom.logRetention.${self:custom.stage}, self:custom.logRetention.default}
```

Resource file:
```yaml
Resources:
  # RDS log group, when created automatically by the serverless framework,
  # gets orphaned and is not deleted when the cloudformation stack is deleted.
  # To make sure it is deleted along with the stack,
  # we create it manually and include it in the stack. 
  RDSClusterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
        LogGroupName: /aws/rds/cluster/${self:custom.stage}-cluster/postgresql
        RetentionInDays: ${self:provider.logRetentionInDays}

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: ${self:provider.stackName}-DBSubnetGroup
      SubnetIds:
        - !Ref SubnetAPrivate	
        - !Ref SubnetBPrivate

  SGIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: ClusterSecurityGroup
    Properties: 
      Description: "RDS port ingress Self Reference"
      FromPort: '5432'
      GroupId: !Ref ClusterSecurityGroup
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref ClusterSecurityGroup
      ToPort: '5432'
  
  ClusterSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId:
        Fn::Join:
        - ""
        - - !Ref VPC
      Tags:
      - Key: Name
        Value: ${self:provider.stackName}-AuroraClusterSecurityGroup


  # Info about this resource below
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html
  ClusterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:provider.stackName}-AuroraClusterSecret
      Description: 'This is the Master secret for the RDS Aurora cluster'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    UpdateReplacePolicy: ${self:custom.DBUpdateReplacePolicy.${self:custom.stage}, self:custom.DBUpdateReplacePolicy.default}
    DeletionPolicy: ${self:custom.DBdeletionPolicy.${self:custom.stage}, self:custom.deletionPolicy.default}
    Properties:
      DBClusterIdentifier: ${self:custom.DBClusterIdentifier}
      DatabaseName: ${self:custom.DatabaseName}
      Engine: aurora-postgresql
      EngineMode: serverless
      EngineVersion: "10.7"
      EnableHttpEndpoint: true
      BackupRetentionPeriod: ${self:custom.DBBackupRetentionPeriod.${self:custom.stage}, self:custom.DBBackupRetentionPeriod.default}
      DeletionProtection: ${self:custom.DBDeletionProtection.${self:custom.stage}, self:custom.DBDeletionProtection.default}
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref ClusterSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref ClusterSecret, ':SecretString:password}}' ]]
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
      - !Ref ClusterSecurityGroup  
      ScalingConfiguration:
        AutoPause: ${self:custom.DBAutopause.${self:custom.stage}, self:custom.DBautopause.default}

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref ClusterSecret
      TargetId: !Ref AuroraDBCluster
      TargetType: AWS::RDS::DBCluster
```

CloudFormation Template:
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyRDSSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "This is a Secrets Manager secret for an RDS DB instance"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  # This is an RDS instance resource. The master username and password use dynamic references
  # to resolve values from Secrets Manager. The dynamic reference guarantees that CloudFormation
  # will not log or persist the resolved value. We use a Ref to the secret resource's logical id
  # to construct the dynamic reference, since the secret name is generated by CloudFormation.
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref MyRDSSecret, ':SecretString:password}}' ]]
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: 'rotation-instance'

  #This is a SecretTargetAttachment resource which updates the referenced Secret resource with properties about
  #the referenced RDS instance
  SecretRDSInstanceAttachment:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref MyRDSSecret
      TargetId: !Ref MyRDSInstance
      TargetType: AWS::RDS::DBInstance
```
</details>

<details>
<summary><b><code>serverless deploy</code> output</b></summary>

```
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Deprecation warning: Variables resolver reports following resolution errors:
              - Cannot resolve variable at "provider.stackName": Value not found at "self" source,
              - Cannot resolve variable at "resources.2.Resources.AuroraDBCluster.Properties.DatabaseName": Value not found at "self" source
            From a next major this will be communicated with a thrown error.
            Set "variablesResolutionMode: 20210326" in your service config, to adapt to new behavior now
            More Info: https://www.serverless.com/framework/docs/deprecations/#NEW_VARIABLES_RESOLVER
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Load command dev
 
 Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:custom.DatabaseName' could not be found.
 
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Packaging service...
Serverless: Injecting required Python packages to package...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 200 0.648s 0 retries] describeStacks({ StackName: 'app-serverless' })
Serverless: [AWS cloudformation 200 0.609s 0 retries] describeStackResource({
  StackName: 'app-serverless',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.607s 0 retries] listObjectsV2({
  Bucket: 'app-server-serverlessdeploymentbuck-1n69tsz89om5i',
  Prefix: 'serverless/app-serverless/dev'
})
Serverless: [AWS s3 200 0.714s 0 retries] headObject({
  Bucket: 'dev-app-server-serverlessdeploymentbuck-1n69tsz89om5i',
  Key: 'serverless/app-serverless/dev/1628862839149-2021-08-13T13:53:59.149Z/compiled-cloudformation-template.json'
})
Serverless: [AWS sts 200 0.226s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.544s 0 retries] putObject({
  Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... 5645 more bytes>,
  Bucket: 'dev-app-server-serverlessdeploymentbuck-1n69tsz89om5i',
  Key: 'serverless/app-serverless/dev/1628865246408-2021-08-13T14:34:06.408Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'Whn1di8Gf40cCHu4WrwwmESE9NSnLopdHIdOS+fJcog=' }
})
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: [AWS cloudformation 400 0.783s 0 retries] validateTemplate({
  TemplateURL: 'https://s3.amazonaws.com/app-server-serverlessdeploymentbuck-1n69tsz89om5i/serverless/app-serverless/dev/1628865246408-2021-08-13T14:34:06.408Z/compiled-cloudformation-template.json'
})
 
  Error --------------------------------------------------
 
  Error: The CloudFormation template is invalid: Circular dependency between resources: [AuroraDBCluster, SecretRDSInstanceAttachment]
      at /project/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at tryCatcher (/project/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/project/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/project/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/projectnode_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/projectnode_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/projectnode_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/projectnode_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/projectnode_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/project/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

</details>

<b>Installed version</b>

```
Framework Core: 1.66.0 (standalone)
Plugin: 3.8.4
SDK: 2.3.2
Components: 2.34.9
```
