### ISSUE TITLE
httpApi with customAuthorizer produces invalid Cloudformation resource. Incorrect scope injection for 'DependsOn'.

### ISSUE THREAD

**Issue by UncleGrim** [serverless/serverless#9848]
When using LambdaAuthorizer in provider, the outputted cloudformation template creates an invalid cloudformation template. The "DependsOn" attribute is injected as part of the `properties` not the core resource.

```
// .serverless/cloudformation-template-update-stack.json
...
    "CustomAuthorizerLambdaAuthorizerPermissionHttpApi": {
	"Type": "AWS::Lambda::Permission",
	"Properties": {
		"FunctionName": {
			"Fn::Join": [
				":",
				[{
						"Fn::GetAtt": [
							"AuthorizerFuncLambdaFunction",
							"Arn"
						]
					},
					"provisioned"
				]
			]
		},
		"Action": "lambda:InvokeFunction",
		"Principal": "apigateway.amazonaws.com",
		"SourceArn": {
			"Fn::Join": [
				"",
				[
					"arn:",
					{
						"Ref": "AWS::Partition"
					},
					":execute-api:",
					{
						"Ref": "AWS::Region"
					},
					":",
					{
						"Ref": "AWS::AccountId"
					},
					":",
					{
						"Ref": "HttpApi"
					},
					"/*"
				]
			]
		},
		"DependsOn": "AuthorizerFuncLambdaFunction"  <--- This should not be in the Properties scope
	}
	  <---- Should be in the top level scope for this resource.
},
    ...
```

```yaml
# ⚠️⚠️ REPLACE THIS COMMENT WITH FULL serverless.yml CONTENT
provider:
  httpApi:
    authorizers:
        customAuthorizer:
            type: request
            functionName: authorizerFunc
functions:
    authorizerFunc:
        handler: src/authorizer/authorizer.auth
    api:
        handler: src/handlers/rest.handler
        events:
            - httpApi:
                  path: /v1/{proxy+}
                  method: '*'
                  metrics: true
                  authorizer: 
                     name: customAuthorizer
```

<summary><b><code>serverless deploy</code> output</b></summary>

```
 Serverless Error ----------------------------------------

  An error occurred: CustomAuthorizerLambdaAuthorizerPermissionHttpApi - Encountered unsupported property DependsOn.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.2
     Framework Version:         2.54.0 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.15.0
```

</details>

<b>Installed version</b>

```
Framework Core: 2.54.0 (local)
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.15.0
```
