### ISSUE TITLE
AWS API Gateway: Improve validation of CORS configuration

### ISSUE THREAD

**Issue by justingrant** [serverless/serverless#9858]
Serverless CLI commands report a configuration warning about CORS configuration for AWS Lambda functions when using the expanded (non-boolean) format of CORS config. I copied this configuration from Serverless's own [blog post](https://www.serverless.com/blog/cors-api-gateway-survival-guide#how-do-i-handle-preflight-requests-with-serverless) about configuring CORS support for Lambda functions. I'm using the second configuration format in the post that allows `origin`, `headers`, and `allowCredentials` properties under the `cors` key. (The other way to configure CORS is simply to use a boolean value.)

This configuration format also matches the TS types for the cors key in @types/serverless: https://github.com/serverless/typescript/blob/b700b729a0ad15aac0a6ed9dc146047a2a7aa583/index.d.ts#L190-L199

I get this error:

```
Serverless: Configuration warning at 'functions.createUser.events[0].http.cors': unsupported configuration format
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: repro

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  stage: prod
  region: us-east-1

functions:
  createUser:
    handler: src/createUser.main
    events:
      - http:
          path: user
          method: post
          cors:
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - cognito-identity-id
          authorizer: aws_iam
```

</details>

<details>
<summary><b><code>SLS_DEBUG=* sls info</code> output</b></summary>

```
justingrant@jgmac api % SLS_DEBUG=* sls info
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: To ensure safe major version upgrades ensure "frameworkVersion" setting in service configuration (recommended setup: "frameworkVersion: ^2.55.0")

Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Configuration warning at 'functions.createUser.events[0].http.cors': unsupported configuration format
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Invoke info
Serverless: Invoke aws:info
Service Information
service: h3-api
stage: prod
region: us-east-1
stack: h3-api-prod
resources: 130
api keys:
  None
endpoints:
  POST - (redacted)
functions:
  createUser: h3-api-prod-createUser
layers:
  None
```

</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.55.0 (local)
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.15.1
```
