### ISSUE TITLE
new `aws:accountId`, `aws:region` variables cannot be referenced/are failing to resolve

### ISSUE THREAD

**Issue by lwoodson** [serverless/serverless#9861]
The documentation describes use of the `aws:accountId` and `aws:region` variables [here](https://www.serverless.com/framework/docs/providers/aws/guide/variables#referencing-aws-specific-variables).  These were introduced in [version 2.50.0](https://github.com/serverless/serverless/blob/master/CHANGELOG.md).  In version 2.54.0, these are failing to resolve with the following error message:

```
Invalid variable reference syntax for variable aws:accountId. You can only reference env vars, options, & files. You can check our docs for more info.
```

<details>
<summary><code>serverless.yml</code></summary>

```yaml
frameworkVersion: "2"
service: delete-me

custom:
  namespace: ${self:service}-${opt:env}
  config:
    env: ${file(config/${opt:env}.yml)}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: aws
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs12.x
  tracing:
    lambda: Active
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  iamRoleStatements: []
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    APPLICATION_AND_QUALIFIER: ${self:service}
    ACCOUNT_ID: ${aws:accountId}
    REGION: ${aws:region}
    ENVIRONMENT: ${opt:stage}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  - Conditions:
      IsDev:
        Fn::Equals:
          - ${opt:env}
          - dev
      IsNotDev:
        Fn::Not:
          - Condition: IsDev
```

</details>

<details>
<summary><b><code>yarn sls package --stage dev</code> output</b></summary>

```
yarn run v1.22.10
warning ../../../../../package.json: No license field
$ sls package --service delete-me --env dev

 Serverless Error ----------------------------------------

  Invalid variable reference syntax for variable aws:accountId. You can only reference env vars, options, & files. You can check our docs for more info.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.1
     Framework Version:         2.54.0 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.6
     Components Version:        3.15.0

Serverless: Deprecation warnings:

CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
 - ServerlessWebpack for "out"
Please report this issue in plugin issue tracker.
Starting with next major release, this will be communicated with a thrown error.
More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
```

</details>

<b>Installed version</b>

```
Framework Core: 2.54.0 (local)
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.15.0
✨  Done in 1.88s.
```
