### ISSUE TITLE
Support being able to disable an EventBridge rule

### ISSUE THREAD

**Issue by jakejscott** [serverless/serverless#9864]
Currently `State` is hardcoded to `ENABLED`. We'd like to be able to set a flag `enabled: false` on the rule.
https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/compile/events/eventBridge/index.js#L344

Proposed config:

```yml
  events:
    - eventBridge:
        schedule: cron(0 0 * * ? *)
        enabled: false
```

**Comment by nirwanrajnp** [comment]
I am guessing this feature has been released but when I was trying it out but I am getting config validation warning. 
```
functions:
  myFunction:
    handler: src/handlers/jobs/myFunction.handler
    events:
      - schedule: 
        rate: rate(1 hour)
        enabled: false
```
The config warning I am getting
```
Serverless: Configuration warning at 'functions.myFunction.events[0]': unsupported function event
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
```
Enviroment
```
Framework Core: 2.57.0
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```
