### ISSUE TITLE
Feature Request: Allow multiple cron/rate expressions in AWS schedule event

### ISSUE THREAD

**Issue by federicojasson** [serverless/serverless#9867]
### Use case description

Currently, configuring a function to be executed at multiple schedules requires multiple event entries, each of them potentially specifying additional properties (e.g. enabled, input):

```yaml
functions:
  my-function:
    handler: ...
    events:
      - schedule:
          rate: cron(...)
          input:
            ...
      - schedule:
          rate: cron(...)
          input:
            ...
```

When the `input` is long and complex, it requires duplicating those additional properties (or initialize them in a `custom` section).

Having multiple cron expressions is quite common. For example, when a function has to be run at different times based on the day of the week, there's no way to express it using a single cron expression:
- `cron(0 0/4 ? * MON-FRI *)`
- `cron(0 2 ? * SAT-SUN *)`

### Proposed solution

If the `rate` value admits arrays of cron/rate expressions, this would be straightforward:

```yaml
functions:
  my-function:
    handler: ...
    events:
      - schedule:
          rate:
            - cron(...)
            - cron(...)
          input:
            ...
```

Internally, the framework would generate one CloudWatch Event rule per entry.
Behavior would remain backward-compatible for non-array values.

**Comment by federicojasson** [comment]
@pgrzesik @medikoo I'm working on this feature.

I have a cuple of design questions for you:

**A - Name in case of arrays of multiple items.**
If the `name` variable is specified along an array of more than one rate expressions, and we simply create several `AWS::Events::Rule` resources with it, that would generate duplicated resource names, generating a CloudFormation error (as names must be unique in the same region):

```yaml
functions:
  my-function:
    handler: ...
    events:
      - schedule:
          name: my-custom-name
          rate:
            - cron(...)
            - cron(...)
```

This would generate two `my-custom-name` rules.
I can think of two options:

1. Let it fail, as it would happen if one defines two `schedule` objects with the same name without even using a rate array.
```yaml
functions:
  my-function:
    handler: ...
    events:
      # This generates an error
      - schedule:
          name: my-custom-name
          rate: cron(...)
      - schedule:
          name: my-custom-name
          rate: cron(...)
```

2. Add an incremental index when a rate array of more than one item is specified:
```yaml
functions:
  my-function:
    handler: ...
    events:
      # This generates an error
      - schedule:
          name: my-custom-name
          rate:
            - cron(...) # Will be named my-custom-name1
            - cron(...) # Will be named my-custom-name2
      - schedule:
          name: my-other-name
          rate:
            - cron(...) # Will be named my-other-name, without any index (because there's only one item)
```
This may open the door for other errors, like:
```yaml
functions:
  my-function:
    handler: ...
    events:
      # This generates an error
      - schedule:
          name: my-custom-name
          rate:
            - cron(...) # Will be named my-custom-name1
            - cron(...) # Will be named my-custom-name2
      - schedule:
          name: my-custom-name1 # This one is now duplicated
          rate: cron(...)
```

**B - Empty arrays**
What should we do in these cases?

```yaml
functions:
  my-function:
    handler: ...
    events:
      - schedule:
          rate: []
```

I think we have two options here as well:
1. Raise an error.
2. Silently ignoring that event (i.e. not create any rule).
