### ISSUE TITLE
Serverless:  No file matches include / exclude patterns

### ISSUE THREAD

**Issue by nomanmaqsood** [serverless/serverless#9873]
When I add layers in my serverless.yml file I got the following error

```
 
 Serverless Error ----------------------------------------
 
  No file matches include / exclude patterns
```
 
In the layer, I am giving the path of the folder that is available on the root of the folder where serverless.yml is also located. In the folder, it is a pem file only

this is my serverless.yml

```
service: foundation

useDotenv: true

custom:
  pcFoundationStackName: foundation-${self:provider.stage}

provider:
  name: aws
  stackName: ${self:service}-${self:provider.stage}
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

layers:
  myLayer:
    path: certificates

plugins:
  - serverless-deployment-bucket
  - serverless-pseudo-parameters
  - serverless-plugin-typescript

functions:
  - ${file(./src/hello/function.yml)}

resources:
  - ${file(./resources/outputs.yml)}

```

runtime: Nodejs

version:

    "serverless": "^2.31.0",
    "serverless-plugin-typescript": "^1.1.9",
    "serverless-pseudo-parameters": "^2.5.0",
    "typescript": "^4.2.4"

**Comment by pgrzesik** [comment]
Hello @nomanmaqsood :wave: Could you please upgrade to the latest Framework verison? Do you have any chance to share a full reproducible example that I could run on my side?

**Comment by nomanmaqsood** [comment]
Hey @pgrzesik I tried doing it with the latest version as well but still get the same problem. 

I am sorry I cannot share the running code

**Comment by pgrzesik** [comment]
Hello @nomanmaqsood - it does not have to be your production code - just a small example with some dummy code that I can use to reproduce on my side. Would you be able to provide such an example?

**Comment by nomanmaqsood** [comment]
@pgrzesik I tried to debug it and add a console in serverless frameworks. I see the files array is empty. Serverless framework is not able to read the file path

**Comment by pgrzesik** [comment]
@nomanmaqsood Thanks for that detail - I would assume that's what is happening, but it's hard to debug if I don't have a reproducible example. Would you be able to provide simple repo on which I could reproduce this issue?

**Comment by alexandrubese** [comment]
I also have the same problem:


layers:
  MyCode:
    path: layers/mycode
    name: my-cod-dependencies
    compatibleRuntimes:
      - nodejs14.x

functions:
  my-func:
    handler: handler
    layers:
      - { Ref: MyCodeLambdaLayer }
    events:
      - http:..

Folder structure is:

layers
--- mycode
------ nodejs
---------node_modules
---------package.json


ServerlessError: No file matches include / exclude patterns
      at /usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:296:13
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:107:9
      at async Promise.all (index 1)
      at async Package.packageService (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:111:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.5
     Framework Version:         2.56.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.16.0

**Comment by pgrzesik** [comment]
Hello @alexandrubese :wave: Thanks for reporting, I've just tried to reproduce with the following example

```
service: layers-repro

provider:
  name: aws
  runtime: nodejs14.x

layers:
  MyCode:
    path: layers/mycode
    name: my-code-dependencies
    compatibleRuntimes:
      - nodejs14.x

functions:
  my-func:
    handler: handler
    layers:
      - { Ref: MyCodeLambdaLayer }
```

and such `layers` dir

```
layers
└── mycode
    └── nodejs
        ├── node_modules
        │   └── lodash.get
        │       ├── index.js
        │       ├── LICENSE
        │       ├── package.json
        │       └── README.md
        ├── package.json
        └── package-lock.json
```

and it was all packaged correctly. Could you please share a minimal reproducible example of your configuration? Ideally in form of a simple github repo that I can try out on my side and see what might be the case
