### ISSUE TITLE
Serverless Lambda Provisioned Concurrency creating Alias "provisioned" instead of creating stage or custom name

### ISSUE THREAD

**Issue by naveenbalaneni** [serverless/serverless#9875]
While enabling the Provisioned Concurrency for lambdas, serverless framework creating alias as provisioned, is there any way we can use stage name or custom name like AutoPublishAlias.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
functions:

  rtn-api-router:
    name: "rtn-api-router"
    handler: rtn-api-router.handler
    layers:
      - !Ref rtnLayer
    package:
      individually: true
      artifact: "${self:custom.s3Key}/rtn-api-router-v${self:custom.version}.zip"
    provisionedConcurrency: 1
```
</details>

<b>Installed version</b>

```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.54.0 (local)
Plugin: 5.4.3
SDK: 4.2.6
Components: 3.15.0
```
