### ISSUE TITLE
warning as "should be string"

### ISSUE THREAD

**Issue by riteshnus** [serverless/serverless#9885]
Hi Team, I have updated my project with the latest serverless package as 2.56.0, now while packing I am getting the below warnings. 

**FUNCTION IS:** 

```
events:
      - http:
          path: internet
          method: post
          cors: true
          private: true
          integration: http
          connectionType: vpc-link
          connectionId: !ImportValue ${self:custom.stackname.internetApigw}-${self:custom.tagging.env}-internetvpclink
          request:
            uri:
              Fn::Join: 
                - ''
                - - https://
                  - ${self:custom.internetApigwRestApiId.${self:custom.tagging.env}}
                  - '.execute-api.ap-southeast-1.amazonaws.com/'
                  - ${self:custom.tagging.env}
                  - /internet
            method: post
            parameters:
              headers:
                x-api-key:
                  required: true
                  mappedValue:
                    Fn::Join:
                      - ''
                      - - "'"
                        - Fn::GetAtt:
                            - GetApiKeyValue
                            - apigwkey
                        - "'"
          response:
            statusCodes:
              200:
                template: '{}'
```

WARNING:

`Configuration warning:
Serverless:   at 'functions.internet.events[0].http.connectionId': should be string
Serverless:   at 'functions.internet.events[0].http.request.parameters.headers['x-api-key'].mappedValue': should be string
Serverless:   at 'functions.internet.events[0].http.request.uri': should be string`

I am getting these 3 warnings, and am unable to resolve these. Although I am using it correctly and was working with the older version as 1.83.0.

Please help out.
