### ISSUE TITLE
Configuration Warning for Cloudfront Origin

### ISSUE THREAD

**Issue by sweber83** [serverless/serverless#9917]
We implemented a project with sls where we use a Cloudfront Distribution with an S3 origin.
When deploying the config, we get this warning:
```
Serverless: Configuration warning:
Serverless:   at 'functions.originRequestHandler.events[0].cloudFront.origin': unrecognized property 'Id'
```
I'm not sure why sls thinks the 'Id' property should not be there, the AWS docs require the property.
Here's the relevant section of the docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html

Because of time constraints I can't provide a minimal serverless.yml, which reproduces the problem.

<b>Installed version</b>

```
Framework Core: 2.57.0 (local)
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```

**Comment by pgrzesik** [comment]
Hello @sweber83 :wave: Thanks for reporting. Having reproducible `serverless.yml` here would immensely speed up potential resolution & debugging. Could you please add it whenever you have time?

**Comment by sweber83** [comment]
Hello @pgrzesik ,
I created a config, which reproduces the issue.
It's not even required to deploy the config, packaging with `sls package` is enough to reproduce.
```
service: issue-9917

provider:
  name: aws

functions:
  originRequestHandler:
    events:
      - cloudFront:
          origin:
            DomainName: somebucket.s3.amazonaws.com
            Id: S3-Proxy
            S3OriginConfig: {}
```
