### ISSUE TITLE
Permissions errors on deploy

### ISSUE THREAD

**Issue by ray-itech** [serverless/serverless#9927]
When running `yarn serverless deploy` (equivalent: `node ./node_modules/.bin/serverless deploy`) via a Jenkins pipeline, i get the following permission errors:

```
Error: EACCES: permission denied, mkdir '/.serverless'
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.16.0
     Framework Version:         2.57.0 (local)
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0 

Serverless: Error: EACCES: permission denied, open '/.serverlessrc.3496394065'
```

Am I missing a configuration in `serverless.yml` ? Thanks

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: contentful-s3-export

package:
  exclude:
    - '/*'
    - '*~'
    - 'test/**'
  include:
    - 'src/**'
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

functions:
  exportContentfulSpace:
    handler: dist/src/handlers/exportContentfulSpace.get
    memorySize: 2048
    timeout: 900
    description: Export Contentful space to S3.
    reservedConcurrency: 5
```

</details>

Serverless version is `2.32`
