### ISSUE TITLE
Invalid "--config" value: Cannot find "uat-serverless.yml" in service folder

### ISSUE THREAD

**Issue by wllam44** [serverless/serverless#9950]
Hi,

I tried to run` serverless deploy -c uat-serverless.yml` in bitbucket pipelines but the system show the error message "Invalid "--config" value: Cannot find "uat-serverless.yml" in service folder".  Already checked that the uat-serverless.yml file is in the root folder, and the command works fine in local development. Hope someone can help me. Thank you so much.

Here's the Bitbucket scripts to run serverless:
```
pipelines:
  branches:
    uat-build:
      - step:
          name: Deploy to UAT
          deployment: staging
          clone:
            enabled: false
          caches:
            - node
          script:
            - npm -g config set user root
            - npm install -g serverless
            - yarn install
            - serverless deploy -c uat-serverless.yml
```

Here's the error message shown in the Bitbucket Pipelines:
```
+ serverless deploy -c uat-serverless.yml
 
 Serverless Error ----------------------------------------
 
  'Invalid "--config" value: Cannot find "uat-serverless.yml" in service folder
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.3
     Framework Version:         2.58.0
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0
```
