### ISSUE TITLE
API Gateway RestApi Got Deleted After Succesful Deployement of new_stage

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [serverless/serverless#9965]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

**Issue** :  API Gateway Rest Api Got Deleted, When I Tried to Deploy app in  new stage `alpha`, when using Custom apiGateway Config

## Steps To Reproduce:

- Deploy `dev` stage
- Deploy `alpha` stage with the apiGateway created for `dev` stage  (specify in `serverless.yml` >> `provider` >> `apiGateway` )

`Issue`: It Doesn't Showing Any Error, It behaving like Everything was successfully Done, Even Showing New Endpoint Url with new stage `alpha`, *But It deleting the Api Gateway Rest API in background*

(When I tried to Access the End point URL I got Forbidden Error, when i look at AWS API Gateway Console , the Resource is No longer Available )

### Service configuration (serverless.yml) content

```yaml
service: serverless-explore

provider:
  name: aws
  runtime: python3.7
  useDotenv: true
  memorySize: 512
  timeout: 60
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  profile: ${opt:profile, 'default'}
  stackName: ${self:service}
  apiName: ${self:service}-api
  apiGateway: 
    restApiId: "abc123"
    restApiRootResourceId: "abcroot123"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: explore/v1
          method: post
```

### Command name and used flags

serverless deploy --stage alpha

### Command output

```shell
Serverless: Configuration warning at 'provider': unrecognized property 'useDotenv'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: WARNING: Function hello has timeout of 60 seconds, however, it's attached to API Gateway so it's automatically limited to 30 seconds.
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service serverless-explore.zip file to S3 (2.56 kB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
......................................
Serverless: Stack update finished...
Service Information
service: serverless-explore
stage: alpha
region: ap-south-1
stack: serverless-explore
resources: 11
api keys:
  None
endpoints:
  POST - https://abc123.execute-api.ap-south-1.amazonaws.com/alpha/explore/v1
functions:
  hello: serverless-explore-alpha-hello
layers:
  None
```

### Environment information

```shell
Framework Core: 2.59.0
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```
