### ISSUE TITLE
http/request/schemas does not work, schema validation return 500

### ISSUE THREAD

**Issue by 300LiterPropofol** [serverless/serverless#9971]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I used the serverless built-in schema validation to create an aws api-gateway --> lambda pipleine that listens to my post request to an endpoint. My serverless config is as below. The deployment, i.e., `serverless deploy --stage dev` is successful. But when I start using the deployed api-gateway to post requests, I will get an error saying 
```
Fri Sep 17 15:42:02 UTC 2021 : Request body validation failed due to an unexpected error
Fri Sep 17 15:42:02 UTC 2021 : Execution failed due to configuration error: Request body validation failed due to an unexpected error
Fri Sep 17 15:42:02 UTC 2021 : Method completed with status: 500
```
I am sure I am using a request content that fulfills the schema defined in `serverless.yml`. When I use a completely wrong request content, I will get this error
```
Fri Sep 17 15:49:06 UTC 2021 : Method request body before transformations: {"test": 1, "tester": 2}
Fri Sep 17 15:49:06 UTC 2021 : Request body does not match model schema for content type application/json: [instance failed to match at least one required schema among 2] 
Fri Sep 17 15:49:06 UTC 2021 : Method completed with status: 400
```
And when I completely removed the schema validation part, the api-gateway can be invoked normally and give a code 200 response. So it seems a bug with the built-in schema validation part.

Please help me. Thank you very much!

### Service configuration (serverless.yml) content

```yaml
service: test

frameworkVersion: '2'
useDotenv: true
unresolvedVariablesNotificationMode: error
variablesResolutionMode: 20210326
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'temp'}
  region: eu-west-1
  endpointType: regional
  apiGateway:
    shouldStartNameWithService: true
    disableDefaultEndpoint: true
  versionFunctions: true

functions:
  start_testing:
    handler: handler.start
    description: Test lambda function chained after an API gateway
    events:
      - http:
          path: test
          method: post
          cors: true
          request:
            schemas:
              application/json: 
                schema: ${file(schema.json)}
                name: Schema
                description: 'Validation model'
```

### Command name and used flags

Not relevant

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.59.0 (standalone)
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```
