### ISSUE TITLE
AWS S3 unrecognized property 'BucketKeyEnabled'

### ISSUE THREAD

**Issue by jlarmstrongiv** [serverless/serverless#9983]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm thinking this might just be due to the newness of the `BucketKeyEnabled` feature, but I’m unsure.  It’s listed in the official documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html and saves substantial costs.  It is nowhere to be found in the codebase, unlike `ServerSideEncryptionByDefault`

Serverless: Running "serverless" installed locally (in service node_modules)

 Serverless Error ----------------------------------------

  Configuration error at 'provider.s3['bucketname'].bucketEncryption.ServerSideEncryptionConfiguration[0]': unrecognized property 'BucketKeyEnabled'

  Learn more about configuration validation here: http://slss.io/configuration-validation

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.0
     Framework Version:         2.59.0 (local)
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0

### Service configuration (serverless.yml) content

```yaml
N/A I am making dynamic buckets with S3 using js.  
But here’s the essentials for the s3 config.  
Most likely, the `BucketKeyEnabled` needs to be added to the code base, 
like `ServerSideEncryptionByDefault`.


service: "longanduniqueservicenameforslstouse"
frameworkVersion: '2'
variablesResolutionMode: 20210326
configValidationMode: error

provider:
  name: aws
  region: us-east-1
  lambdaHashingVersion: 20201221
  s3: # If you need to configure the bucket itself, you'll need to add s3 resources to the provider configuration
    longAndUniqueBucketNameForSlsToUse: # Eventual additional properties in camel case
    # Supported properties are the same ones as supported by CF resource for S3 bucket: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
      name: my-custom-bucket-name
      versioningConfiguration:
        Status: Enabled
      bucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
```

### Command name and used flags

N/A sls remove, sls deploy

### Command output

```shell
Serverless: Running "serverless" installed locally (in service node_modules)

 Serverless Error ----------------------------------------

  Configuration error at 'provider.s3['bucketname'].bucketEncryption.ServerSideEncryptionConfiguration[0]': unrecognized property 'BucketKeyEnabled'

  Learn more about configuration validation here: http://slss.io/configuration-validation

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.0
     Framework Version:         2.59.0 (local)
     Plugin Version:            5.4.4
     SDK Version:               4.3.0
     Components Version:        3.17.0
```

### Environment information

```shell
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 2.59.0 (local)
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.0
```
