### ISSUE TITLE
Local dependencies prevent the google cloud function from building

### ISSUE THREAD

**Issue by HariShyamU** [serverless/serverless#9993]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

I'm trying to implement code sharing between multiple services by using npm local dependencies. Here is the code structure:

endpoints
- servicename
- - package.json
- - serverless.yml
libs
- database.js
- auth.js
- package.json

I've added the libs folder as a local dependency to my function like so:

`  "dependencies": {
    "libs": "../../libs"
  }`

When the cloud build is initiated for deployment, I get an error shown below during deployment:

Build failed: npm ERR! code EEXIST
npm ERR! syscall mkdir
npm ERR! path /workspace/node_modules/libs
npm ERR! errno -17
npm ERR! EEXIST: file already exists, mkdir '/workspace/node_modules/libs'
npm ERR! File exists: /workspace/node_modules/libs
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

### Service configuration (serverless.yml) content

```yaml
service: servicename

provider:
  name: google
  stage: dev
  runtime: nodejs14
  region: asia-south1
  project: project-name
  credentials: "../../creds.json"

frameworkVersion: '2'

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  get:
    handler: servicehandler
    events:
      - http: path
```

### Command name and used flags

serverless deploy --region asia-south1

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 2.59.0
Plugin: 5.4.4
SDK: 4.3.0
Components: 3.17.1
```
